In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-06-26 00:00:00
end   = 2026-09-26 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-06-26
end_date_str   = 2026-09-26

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

  ticker       value
0      A    49077.54
1     AA  1070919.38
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 13598

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
# market_cap ніде далі не використовується (єдина згадка — у 'fields' вище),
# тому він не має відсіювати тикери: рядок викидаємо лише якщо бракує ticker або lvl3
tickers_df = tickers_df.dropna(subset=["ticker", "lvl3"])

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,133 рядків

  ticker       value                         lvl3  market_cap
0      A    49077.54  Medical Equipment & Devices     48714.0
1     AA  1070919.38              Metals & Mining     11308.0
2   AAAU   305631.17                          NaN         NaN
3   AACG       15.23                     Software        37.0
4   AADX    46808.46          Aerospace & Defense      2179.0

In [7]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [8]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 61 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Banks',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Investment Management',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Other Financial Services',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [9]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "IBIT"],
    "Banking": ["XLF", "KRE", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "IBIT"],
    "Insurance": ["XLF"],
    "Specialty Finance": ["XLF", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV"],
    "IT Services": ["QQQ"],
    "Semiconductors": ["SOXX", "DRAM"],
    "Technology Hardware": ["QQQ", "SOXX"],
    "Internet Media & Services": ["QQQ", "KWEB", "FXI"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "XRT"],
    "Cable & Satellite": ["SPY", "IWM"],
    "Telecommunications": ["QQQ"],
    "Publishing & Broadcasting": ["QQQ"],
    "Entertainment Content": ["QQQ", "ARKK"],
    "Advertising & Marketing": ["QQQ"],

    # --- Industrials ---
    "Aerospace & Defense": ["NASA", "ITA"],
    "Diversified Industrials": ["XLB", "IWM"],
    "Industrial Intermediate Prod": ["XLB", "IWM"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["XLB", "IWM"],
    "Machinery": ["XLB", "IWM"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["XLB", "IWM"],
    "Electrical Equipment": ["QQQ", "XLB"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XOP", "XLE", "UNG"],
    "Oil & Gas Supply Chain": ["XOP", "XLE", "UNG"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE"],
    "Electric Utilities": ["XLU"],
    "Gas & Water Utilities": ["XLU"],
    "Renewable Energy": ["XLE", "ARKK"],
    "Chemicals": ["XLB", "URA"],
    "Metals & Mining": ["GDX", "FCX", "COPX", "URA", "SLV"],
    "Steel": ["XLB", "GDX"],
    "Construction Materials": ["XLB", "IWM"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM"],

    # --- Health Care ---
    "Biotech & Pharma": ["XBI"],
    "Medical Equipment & Devices": ["XLV"],
    "Health Care Facilities & Svcs": ["XLV", "IWM"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP"],
    "Beverages": ["XLP"],
    "Household Products": ["XLP"],
    "Tobacco & Cannabis": ["XLP"],
    "Retail - Consumer Staples": ["XLP", "XRT"],
    "Wholesale - Consumer Staples": ["XLP"],

    "Retail - Discretionary": ["XRT", "IWM", "SPY"],
    "Wholesale - Discretionary": ["XRT", "IWM"],
    "Consumer Services": ["IWM", "SPY"],
    "Leisure Facilities & Services": ["IWM", "SPY"],
    "Leisure Products": ["XRT", "IWM"],
    "Apparel & Textile Products": ["XRT", "IWM"],
    "Automotive": ["QQQ", "IWM"],
    "Home & Office Products": ["XRT", "IWM"],
    "Home Construction": ["XLB", "IWM"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [10]:
# ------------------------------------------------

In [11]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [12]:
# Кеш сирого фетчу. /daily/gaps і /reports тягнулись ДВІЧІ за прогін — тут і в
# комірці 42 — тобто ~14 500 зайвих запитів, і саме вони й провокували 429.
# Складаємо результат ДО відкидання викидів: комірка 42 рахує sigma на СИРИХ
# гепах, і підстановка вже обрізаних занизила б її.
CRACEN_FETCH_CACHE = {}


def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
    max_workers_net=8,        # 64 потоки без пауз давали суцільні 429
    max_fail_ratio=0.15,      # 4.4% остаточних відмов виміряно як НОРМУ для цього
                              # API навіть з retry; бар упритул до норми валив би
                              # прогін через раз. Ловить справжню відмову, не шум.
):
    import random
    import time
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    _fails = {"gaps": 0, "reports": 0}

    def _request_with_retry(endpoint, params, *, max_retries=6, backoff=0.5):
        """Повторює запит при 429/мережевих збоях з наростаючою паузою.
        Той самий підхід, що в /intraday/v3. Вичерпавши спроби — кидає
        останній виняток, який ловить виклик вище."""
        for attempt in range(max_retries + 1):
            try:
                return DatumApi.data_request(endpoint, params)
            except Exception:
                if attempt == max_retries:
                    raise
                time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))

    def _fetch_gap(t):
        try:
            dfg = _request_with_retry("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            _fails["gaps"] += 1
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = _request_with_retry("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            _fails["reports"] += 1
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(max_workers_net,
                                            len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    _total = len(gap_futs) + len(rep_futs)
    _failed = _fails["gaps"] + _fails["reports"]
    if _total and _failed / _total > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_failed} з {_total} запитів "
            f"({_failed / _total * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Далі вийшла б порожня або обрізана мапа bench/corr/beta."
        )

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    CRACEN_FETCH_CACHE.clear()
    CRACEN_FETCH_CACHE.update({
        "window": (s_date, e_date),
        "last_n_reports": int(last_n_reports),
        "tickers": set(stocks),
        "gaps": stock_gaps.copy(),      # сирі, до drop anomalies нижче
        "reports": reports.copy(),
    })

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [13]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7133 etfs=28 window=2026-06-26..2026-09-26

WARN gaps fail SLAI: 404 Client Error: Not Found for url: https://api.datum-rd.com/daily/gaps?ticker=SLAI&start_date=2026-06-26&end_date=2026-09-26&format=json_records

DONE pairs: 7022 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 7022 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: Diversified Banks, Investment Management, Other Financial Services, UNKNOWN
  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.251074  0.193897  Advertising & Marketing         51
1     AEHL      QQQ  0.198895  0.800403  Advertising & Marketing         50
2      APP      QQQ  0.197896  0.214978  Advertising & Marketing         50
3     BAOS      QQQ -0.090989 -0.230467  Advertising & Marketing         51
4     CDLX      QQQ  0.371634  0.328845  Advertising & Marketing         50
Rows in raw stock-etf pairs: 15727
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           QQQ   0.251074        0.193897  Advertising & Marketing
1     AEHL           QQQ   0.198895        0.800403  Advertising & Marketing
2      APP           QQQ   0.197896        0.214978  Advertising & Marketing
3     BAOS           QQQ  -0.090989       -0.230467  Advertising & Marketing
4     CDLX           QQQ   0.371634        0.328845  Advertising & Marketing

   n_overlap
0         51
1         50
2         50
3         51
4         50
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [14]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [15]:
TICKERS

     ticker       value                         lvl3  market_cap
0         A    49077.54  Medical Equipment & Devices     48714.0
1        AA  1070919.38              Metals & Mining     11308.0
2      AAAU   305631.17                          NaN         NaN
3      AACG       15.23                     Software        37.0
4      AADX    46808.46          Aerospace & Defense      2179.0
...     ...         ...                          ...         ...
7128   ZVOL     3407.81                          NaN         NaN
7129   ZVRA     9506.70             Biotech & Pharma       655.0
7130    ZWS     1612.50                    Machinery      7737.0
7131   ZYBT     4584.99             Biotech & Pharma        38.0
7132   ZYME    81581.01             Biotech & Pharma      1896.0

[7133 rows x 4 columns]

In [16]:
import pandas as pd

# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0    ARKK
1    COPX
2    DRAM
3     FCX
4     FXI
5     GDX
6    IBIT
7     IGV
8     ITA
9     IWM
10    KRE
11   KWEB
12   NASA
13    QQQ
14    SLV
15   SOXX
16    SPY
17    UNG
18    URA
19    XBI
20    XLB
21    XLE
22    XLF
23    XLP
24    XLU
25    XLV
26    XOP
27    XRT

In [17]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=16,
    parallel_tickers=True,
    max_workers_tickers=16,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 7133 тікерів (пропущено 0 по старому маніфесту) | 2026-06-26 00:00:00 → 2026-09-26 23:59:59 | interval=1 | next batch #17526 | run=29284d2f

   workers: tickers=16, chunks=16 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-06-26 → 2026-09-24 (91 днів)

   📈 обробляються дні: 2026-09-25 → 2026-09-26 (2 днів)

   psutil · старт · 🧠 RAM: 316.4 MB

[10/7133] ✓ AAON: 395 рядків |   0.14% | ETA 20:23

[20/7133] ✓ AB: 250 рядків |   0.28% | ETA 17:21

[30/7133] ✓ ABCB: 198 рядків |   0.42% | ETA 16:04

[40/7133] – ABNG: empty |   0.56% | ETA 15:30

[50/7133] ✓ ACAD: 402 рядків |   0.70% | ETA 15:19

   • RAM · 🧠 RAM: 343.6 MB

   ⏳ перед flush · 🧠 RAM: 343.6 MB

💾 batch 17526 → 14,815 рядків (всього 14,815 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17526.csv.gz

   ✅ після flush · 🧠 RAM: 348.4 MB

[60/7133] ✓ ACHC: 348 рядків |   0.84% | ETA 15:46

[70/7133] ✓ ACON: 36 рядків |   0.98% | ETA 15:38

[80/7133] ✓ ACTG: 87 рядків |   1.12% | ETA 15:17

[90/7133] ✓ ADBE: 564 рядків |   1.26% | ETA 15:16

[100/7133] ✓ ADIL: 32 рядків |   1.40% | ETA 15:17

   • RAM · 🧠 RAM: 354.7 MB

   ⏳ перед flush · 🧠 RAM: 354.6 MB

💾 batch 17527 → 13,314 рядків (всього 28,129 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17527.csv.gz

   ✅ після flush · 🧠 RAM: 357.1 MB

[110/7133] ✓ ADNT: 303 рядків |   1.54% | ETA 15:23

[120/7133] – AEMS: empty |   1.68% | ETA 15:14

[130/7133] ✓ AEP: 409 рядків |   1.82% | ETA 15:05

[140/7133] ✓ AFG: 193 рядків |   1.96% | ETA 14:59

[150/7133] ✓ AGIQ: 7 рядків |   2.10% | ETA 14:57

   • RAM · 🧠 RAM: 358.5 MB

   ⏳ перед flush · 🧠 RAM: 358.5 MB

💾 batch 17528 → 11,766 рядків (всього 39,895 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17528.csv.gz

   ✅ після flush · 🧠 RAM: 358.6 MB

[160/7133] ✓ AGNT: 317 рядків |   2.24% | ETA 14:58

[170/7133] ✓ AGRO: 231 рядків |   2.38% | ETA 14:52

[180/7133] ✓ AIFA: 92 рядків |   2.52% | ETA 14:45

[190/7133] ✓ AIMD: 120 рядків |   2.66% | ETA 14:42

[200/7133] ✓ AIPI: 184 рядків |   2.80% | ETA 14:38

   • RAM · 🧠 RAM: 360.3 MB

   ⏳ перед flush · 🧠 RAM: 360.3 MB

💾 batch 17529 → 11,246 рядків (всього 51,141 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17529.csv.gz

   ✅ після flush · 🧠 RAM: 361.2 MB

[210/7133] ✓ AIT: 262 рядків |   2.94% | ETA 14:45

[220/7133] ✓ AKAN: 155 рядків |   3.08% | ETA 14:40

[230/7133] ✓ ALB: 411 рядків |   3.22% | ETA 14:32

[240/7133] ✓ ALGM: 413 рядків |   3.36% | ETA 14:27

[250/7133] ✓ ALLE: 321 рядків |   3.50% | ETA 14:24

   • RAM · 🧠 RAM: 362.6 MB

   ⏳ перед flush · 🧠 RAM: 362.6 MB

💾 batch 17530 → 13,109 рядків (всього 64,250 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17530.csv.gz

   ✅ після flush · 🧠 RAM: 363.3 MB

[260/7133] ✓ ALMU: 287 рядків |   3.65% | ETA 14:31

[270/7133] ✓ ALZN: 27 рядків |   3.79% | ETA 14:30

[280/7133] ✓ AMBA: 399 рядків |   3.93% | ETA 14:29

[290/7133] ✓ AMCI: 24 рядків |   4.07% | ETA 14:28

[300/7133] ✓ AMKR: 499 рядків |   4.21% | ETA 14:27

   • RAM · 🧠 RAM: 365.4 MB

   ⏳ перед flush · 🧠 RAM: 365.4 MB

💾 batch 17531 → 13,704 рядків (всього 77,954 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17531.csv.gz

   ✅ після flush · 🧠 RAM: 366.9 MB

[310/7133] ✓ AMPH: 204 рядків |   4.35% | ETA 14:31

[320/7133] ✓ AMSC: 310 рядків |   4.49% | ETA 14:30

[330/7133] ✓ AMX: 354 рядків |   4.63% | ETA 14:29

[340/7133] ✓ AMZZ: 134 рядків |   4.77% | ETA 14:29

[350/7133] ✓ ANF: 352 рядків |   4.91% | ETA 14:29

   • RAM · 🧠 RAM: 372.8 MB

   ⏳ перед flush · 🧠 RAM: 372.8 MB

💾 batch 17532 → 12,291 рядків (всього 90,245 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17532.csv.gz

   ✅ після flush · 🧠 RAM: 376.0 MB

[360/7133] ✓ ANNA: 89 рядків |   5.05% | ETA 14:34

[370/7133] ✓ AON: 400 рядків |   5.19% | ETA 14:31

[380/7133] ✓ APC: 209 рядків |   5.33% | ETA 14:30

[390/7133] ✓ APLY: 90 рядків |   5.47% | ETA 14:28

[400/7133] ✓ APPS: 413 рядків |   5.61% | ETA 14:25

   • RAM · 🧠 RAM: 377.2 MB

   ⏳ перед flush · 🧠 RAM: 377.2 MB

💾 batch 17533 → 9,981 рядків (всього 100,226 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17533.csv.gz

   ✅ після flush · 🧠 RAM: 379.0 MB

[410/7133] ✓ APPX: 403 рядків |   5.75% | ETA 14:29

[420/7133] ✓ ARCC: 411 рядків |   5.89% | ETA 14:28

[430/7133] ✓ ARCX: 16 рядків |   6.03% | ETA 14:27

[440/7133] ✓ ARKO: 266 рядків |   6.17% | ETA 14:25

[450/7133] ✓ ARMG: 654 рядків |   6.31% | ETA 14:23

   • RAM · 🧠 RAM: 380.5 MB

   ⏳ перед flush · 🧠 RAM: 380.5 MB

💾 batch 17534 → 14,231 рядків (всього 114,457 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17534.csv.gz

   ✅ після flush · 🧠 RAM: 381.0 MB

[460/7133] – ARQQW: empty |   6.45% | ETA 14:27

[470/7133] ✓ AS: 398 рядків |   6.59% | ETA 14:25

[480/7133] ✓ ASGI: 171 рядків |   6.73% | ETA 14:23

[490/7133] ✓ ASML: 779 рядків |   6.87% | ETA 14:22

[500/7133] ✓ ASUR: 84 рядків |   7.01% | ETA 14:21

   • RAM · 🧠 RAM: 382.6 MB

   ⏳ перед flush · 🧠 RAM: 382.6 MB

💾 batch 17535 → 11,674 рядків (всього 126,131 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17535.csv.gz

   ✅ після flush · 🧠 RAM: 382.6 MB

[510/7133] ✓ AT: 10 рядків |   7.15% | ETA 14:22

[520/7133] ✓ ATII: 38 рядків |   7.29% | ETA 14:19

[530/7133] ✓ ATLC: 66 рядків |   7.43% | ETA 14:17

[540/7133] ✓ ATRA: 47 рядків |   7.57% | ETA 14:14

[550/7133] ✓ AU: 442 рядків |   7.71% | ETA 14:14

   • RAM · 🧠 RAM: 383.7 MB

   ⏳ перед flush · 🧠 RAM: 383.7 MB

💾 batch 17536 → 10,291 рядків (всього 136,422 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17536.csv.gz

   ✅ після flush · 🧠 RAM: 384.7 MB

[560/7133] ✓ AVA: 308 рядків |   7.85% | ETA 14:16

[570/7133] ✓ AVAH: 363 рядків |   7.99% | ETA 14:14

[580/7133] ✓ AVGV: 61 рядків |   8.13% | ETA 14:13

[590/7133] ✓ AVNT: 270 рядків |   8.27% | ETA 14:12

[600/7133] ✓ AVSC: 133 рядків |   8.41% | ETA 14:10

   • RAM · 🧠 RAM: 386.3 MB

   ⏳ перед flush · 🧠 RAM: 386.3 MB

💾 batch 17537 → 11,797 рядків (всього 148,219 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17537.csv.gz

   ✅ після flush · 🧠 RAM: 386.5 MB

[610/7133] ✓ AVX: 239 рядків |   8.55% | ETA 14:13

[620/7133] ✓ AXP: 462 рядків |   8.69% | ETA 14:11

[630/7133] ✓ AXTI: 810 рядків |   8.83% | ETA 14:12

[640/7133] ✓ AZTR: 78 рядків |   8.97% | ETA 14:10

[650/7133] ✓ BABW: 4 рядків |   9.11% | ETA 14:09

   • RAM · 🧠 RAM: 390.8 MB

   ⏳ перед flush · 🧠 RAM: 390.8 MB

💾 batch 17538 → 12,494 рядків (всього 160,713 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17538.csv.gz

   ✅ після flush · 🧠 RAM: 392.8 MB

[660/7133] ✓ BAM: 396 рядків |   9.25% | ETA 14:10

[670/7133] ✓ BAX: 395 рядків |   9.39% | ETA 14:09

[680/7133] ✓ BBC: 30 рядків |   9.53% | ETA 14:08

[690/7133] ✓ BBD: 393 рядків |   9.67% | ETA 14:07

[700/7133] ✓ BBYY: 2 рядків |   9.81% | ETA 14:06

   • RAM · 🧠 RAM: 397.4 MB

   ⏳ перед flush · 🧠 RAM: 397.4 MB

💾 batch 17539 → 11,566 рядків (всього 172,279 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17539.csv.gz

   ✅ після flush · 🧠 RAM: 402.5 MB

[710/7133] ✓ BCCC: 24 рядків |   9.95% | ETA 14:07

[720/7133] ✓ BCO: 200 рядків |  10.09% | ETA 14:05

[730/7133] ✓ BCX: 121 рядків |  10.23% | ETA 14:04

[740/7133] ✓ BEEM: 99 рядків |  10.37% | ETA 14:01

[750/7133] ✓ BENF: 1,100 рядків |  10.51% | ETA 13:59

   • RAM · 🧠 RAM: 397.3 MB

   ⏳ перед flush · 🧠 RAM: 397.3 MB

💾 batch 17540 → 10,958 рядків (всього 183,237 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17540.csv.gz

   ✅ після flush · 🧠 RAM: 400.2 MB

[760/7133] ✓ BEZ: 580 рядків |  10.65% | ETA 14:00

[770/7133] ✓ BGC: 371 рядків |  10.79% | ETA 13:58

[780/7133] ✓ BGLD: 10 рядків |  10.94% | ETA 13:57

[790/7133] ✓ BHP: 533 рядків |  11.08% | ETA 13:56

[800/7133] ✓ BIDU: 560 рядків |  11.22% | ETA 13:54

   • RAM · 🧠 RAM: 401.3 MB

   ⏳ перед flush · 🧠 RAM: 401.3 MB

💾 batch 17541 → 10,404 рядків (всього 193,641 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17541.csv.gz

   ✅ після flush · 🧠 RAM: 402.0 MB

[810/7133] ✓ BIRD: 173 рядків |  11.36% | ETA 13:55

[820/7133] ✓ BIV: 381 рядків |  11.50% | ETA 13:53

[830/7133] ✓ BJRI: 234 рядків |  11.64% | ETA 13:52

[840/7133] ✓ BKR: 458 рядків |  11.78% | ETA 13:51

[850/7133] – BLCN: empty |  11.92% | ETA 13:50

   • RAM · 🧠 RAM: 403.8 MB

   ⏳ перед flush · 🧠 RAM: 403.8 MB

💾 batch 17542 → 14,363 рядків (всього 208,004 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17542.csv.gz

   ✅ після flush · 🧠 RAM: 405.9 MB

[860/7133] ✓ BLMN: 378 рядків |  12.06% | ETA 13:51

[870/7133] ✓ BLV: 332 рядків |  12.20% | ETA 13:50

[880/7133] ✓ BMNG: 181 рядків |  12.34% | ETA 13:50

[890/7133] ✓ BMO: 259 рядків |  12.48% | ETA 13:50

[900/7133] ✓ BNDX: 392 рядків |  12.62% | ETA 13:48

   • RAM · 🧠 RAM: 404.7 MB

   ⏳ перед flush · 🧠 RAM: 404.7 MB

💾 batch 17543 → 12,538 рядків (всього 220,542 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17543.csv.gz

   ✅ після flush · 🧠 RAM: 406.4 MB

[910/7133] ✓ BOEG: 57 рядків |  12.76% | ETA 13:49

[920/7133] ✓ BOND: 360 рядків |  12.90% | ETA 13:48

[930/7133] ✓ BPOP: 218 рядків |  13.04% | ETA 13:46

[940/7133] ✓ BRIA: 6 рядків |  13.18% | ETA 13:45

[950/7133] ✓ BRKW: 10 рядків |  13.32% | ETA 13:45

   • RAM · 🧠 RAM: 408.5 MB

   ⏳ перед flush · 🧠 RAM: 408.5 MB

💾 batch 17544 → 9,951 рядків (всього 230,493 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17544.csv.gz

   ✅ після flush · 🧠 RAM: 410.0 MB

[960/7133] ✓ BRRR: 46 рядків |  13.46% | ETA 13:46

[970/7133] ✓ BSAC: 298 рядків |  13.60% | ETA 13:45

[980/7133] ✓ BST: 126 рядків |  13.74% | ETA 13:45

[990/7133] ✓ BTCI: 312 рядків |  13.88% | ETA 13:43

[1000/7133] ✓ BTCU: 72 рядків |  14.02% | ETA 13:42

   • RAM · 🧠 RAM: 401.4 MB

   ⏳ перед flush · 🧠 RAM: 401.5 MB

💾 batch 17545 → 10,837 рядків (всього 241,330 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17545.csv.gz

   ✅ після flush · 🧠 RAM: 402.8 MB

[1010/7133] ✓ BTMD: 37 рядків |  14.16% | ETA 13:43

[1020/7133] ✓ BUD: 396 рядків |  14.30% | ETA 13:42

[1030/7133] ✓ BULL: 575 рядків |  14.44% | ETA 13:42

[1040/7133] ✓ BWEN: 112 рядків |  14.58% | ETA 13:41

[1050/7133] ✓ BWXT: 393 рядків |  14.72% | ETA 13:40

   • RAM · 🧠 RAM: 406.3 MB

   ⏳ перед flush · 🧠 RAM: 406.3 MB

💾 batch 17546 → 11,557 рядків (всього 252,887 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17546.csv.gz

   ✅ після flush · 🧠 RAM: 410.0 MB

[1060/7133] ✓ BYAH: 275 рядків |  14.86% | ETA 13:42

[1070/7133] ✓ CAH: 365 рядків |  15.00% | ETA 13:40

[1080/7133] ✓ CAIE: 279 рядків |  15.14% | ETA 13:39

[1090/7133] ✓ CALX: 332 рядків |  15.28% | ETA 13:38

[1100/7133] ✓ CAPS: 417 рядків |  15.42% | ETA 13:38

   • RAM · 🧠 RAM: 409.7 MB

   ⏳ перед flush · 🧠 RAM: 409.7 MB

💾 batch 17547 → 13,042 рядків (всього 265,929 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17547.csv.gz

   ✅ після flush · 🧠 RAM: 411.6 MB

[1110/7133] ✓ CATG: 60 рядків |  15.56% | ETA 13:38

[1120/7133] ✓ CATX: 370 рядків |  15.70% | ETA 13:37

[1130/7133] ✓ CBRG: 596 рядків |  15.84% | ETA 13:36

[1140/7133] ✓ CCBG: 41 рядків |  15.98% | ETA 13:35

[1150/7133] ✓ CCHH: 25 рядків |  16.12% | ETA 13:34

   • RAM · 🧠 RAM: 407.9 MB

   ⏳ перед flush · 🧠 RAM: 408.0 MB

💾 batch 17548 → 11,469 рядків (всього 277,398 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17548.csv.gz

   ✅ після flush · 🧠 RAM: 408.5 MB

[1160/7133] ✓ CCTG: 58 рядків |  16.26% | ETA 13:35

[1170/7133] ✓ CDLR: 143 рядків |  16.40% | ETA 13:34

[1180/7133] ✓ CDNS: 456 рядків |  16.54% | ETA 13:32

[1190/7133] ✓ CECO: 242 рядків |  16.68% | ETA 13:31

[1200/7133] ✓ CETY: 4 рядків |  16.82% | ETA 13:31

   • RAM · 🧠 RAM: 411.4 MB

   ⏳ перед flush · 🧠 RAM: 411.5 MB

💾 batch 17549 → 11,617 рядків (всього 289,015 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17549.csv.gz

   ✅ після flush · 🧠 RAM: 413.7 MB

[1210/7133] ✓ CFG: 392 рядків |  16.96% | ETA 13:33

[1220/7133] ✓ CGEN: 70 рядків |  17.10% | ETA 13:32

[1230/7133] ✓ CGMM: 331 рядків |  17.24% | ETA 13:30

[1240/7133] ✓ CHAU: 56 рядків |  17.38% | ETA 13:30

[1250/7133] ✓ CHGG: 202 рядків |  17.52% | ETA 13:28

   • RAM · 🧠 RAM: 414.7 MB

   ⏳ перед flush · 🧠 RAM: 414.7 MB

💾 batch 17550 → 12,689 рядків (всього 301,704 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17550.csv.gz

   ✅ після flush · 🧠 RAM: 414.9 MB

[1260/7133] ✓ CHOW: 117 рядків |  17.66% | ETA 13:29

[1270/7133] ✓ CHT: 137 рядків |  17.80% | ETA 13:28

[1280/7133] ✓ CIGL: 29 рядків |  17.94% | ETA 13:27

[1290/7133] ✓ CIRC: 161 рядків |  18.08% | ETA 13:26

[1300/7133] ✓ CLAR: 99 рядків |  18.23% | ETA 13:25

   • RAM · 🧠 RAM: 403.0 MB

   ⏳ перед flush · 🧠 RAM: 403.0 MB

💾 batch 17551 → 10,826 рядків (всього 312,530 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17551.csv.gz

   ✅ після flush · 🧠 RAM: 403.2 MB

[1310/7133] ✓ CLMT: 356 рядків |  18.37% | ETA 13:25

[1320/7133] ✓ CLOZ: 228 рядків |  18.51% | ETA 13:24

[1330/7133] ✓ CLVT: 380 рядків |  18.65% | ETA 13:23

[1340/7133] ✓ CMND: 70 рядків |  18.79% | ETA 13:22

[1350/7133] ✓ CMCO: 289 рядків |  18.93% | ETA 13:21

   • RAM · 🧠 RAM: 404.9 MB

   ⏳ перед flush · 🧠 RAM: 404.9 MB

💾 batch 17552 → 12,141 рядків (всього 324,671 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17552.csv.gz

   ✅ після flush · 🧠 RAM: 407.8 MB

[1360/7133] ✓ CMRE: 158 рядків |  19.07% | ETA 13:21

[1370/7133] ✓ CNO: 231 рядків |  19.21% | ETA 13:20

[1380/7133] ✓ CNQQ: 6 рядків |  19.35% | ETA 13:19

[1390/7133] ✓ CNXU: 112 рядків |  19.49% | ETA 13:17

[1400/7133] ✓ CODA: 66 рядків |  19.63% | ETA 13:17

   • RAM · 🧠 RAM: 408.0 MB

   ⏳ перед flush · 🧠 RAM: 408.0 MB

💾 batch 17553 → 11,043 рядків (всього 335,714 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17553.csv.gz

   ✅ після flush · 🧠 RAM: 409.9 MB

[1410/7133] ✓ COIG: 70 рядків |  19.77% | ETA 13:18

[1420/7133] ✓ COMB: 48 рядків |  19.91% | ETA 13:17

[1430/7133] ✓ CONI: 248 рядків |  20.05% | ETA 13:16

[1440/7133] ✓ COR: 385 рядків |  20.19% | ETA 13:16

[1450/7133] ✓ CORZW: 22 рядків |  20.33% | ETA 13:15

   • RAM · 🧠 RAM: 416.1 MB

   ⏳ перед flush · 🧠 RAM: 416.1 MB

💾 batch 17554 → 13,627 рядків (всього 349,341 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17554.csv.gz

   ✅ після flush · 🧠 RAM: 419.0 MB

[1460/7133] ✓ COZX: 44 рядків |  20.47% | ETA 13:15

[1470/7133] ✓ CPER: 274 рядків |  20.61% | ETA 13:14

[1480/7133] ✓ CR: 215 рядків |  20.75% | ETA 13:12

[1490/7133] ✓ CRCO: 144 рядків |  20.89% | ETA 13:11

[1500/7133] ✓ CRF: 363 рядків |  21.03% | ETA 13:11

   • RAM · 🧠 RAM: 416.7 MB

   ⏳ перед flush · 🧠 RAM: 416.9 MB

💾 batch 17555 → 13,436 рядків (всього 362,777 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17555.csv.gz

   ✅ після flush · 🧠 RAM: 416.7 MB

[1510/7133] ✓ CRK: 384 рядків |  21.17% | ETA 13:11

[1520/7133] – CRNX: empty |  21.31% | ETA 13:10

[1530/7133] ✓ CRVL: 137 рядків |  21.45% | ETA 13:09

[1540/7133] ✓ CRY: 9 рядків |  21.59% | ETA 13:08

[1550/7133] ✓ CSEX: 76 рядків |  21.73% | ETA 13:06

   • RAM · 🧠 RAM: 417.7 MB

   ⏳ перед flush · 🧠 RAM: 417.7 MB

💾 batch 17556 → 11,635 рядків (всього 374,412 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17556.csv.gz

   ✅ після flush · 🧠 RAM: 417.8 MB

[1560/7133] ✓ CSTL: 212 рядків |  21.87% | ETA 13:06

[1570/7133] ✓ CTKB: 302 рядків |  22.01% | ETA 13:05

[1580/7133] ✓ CTRE: 371 рядків |  22.15% | ETA 13:04

[1590/7133] ✓ CURE: 61 рядків |  22.29% | ETA 13:02

[1600/7133] ✓ CVBF: 366 рядків |  22.43% | ETA 13:02

   • RAM · 🧠 RAM: 417.4 MB

   ⏳ перед flush · 🧠 RAM: 417.4 MB

💾 batch 17557 → 12,114 рядків (всього 386,526 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17557.csv.gz

   ✅ після flush · 🧠 RAM: 418.5 MB

[1610/7133] ✓ CVRX: 246 рядків |  22.57% | ETA 13:02

[1620/7133] ✓ CWH: 390 рядків |  22.71% | ETA 13:01

[1630/7133] ✓ CWVX: 467 рядків |  22.85% | ETA 12:59

[1640/7133] ✓ CYN: 113 рядків |  22.99% | ETA 12:58

[1650/7133] ✓ CZR: 355 рядків |  23.13% | ETA 12:57

   • RAM · 🧠 RAM: 420.3 MB

   ⏳ перед flush · 🧠 RAM: 420.3 MB

💾 batch 17558 → 11,286 рядків (всього 397,812 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17558.csv.gz

   ✅ після flush · 🧠 RAM: 420.6 MB

[1660/7133] ✓ DAN: 353 рядків |  23.27% | ETA 12:58

[1670/7133] ✓ DBB: 119 рядків |  23.41% | ETA 12:57

[1680/7133] ✓ DC: 361 рядків |  23.55% | ETA 12:56

[1690/7133] ✓ DCOR: 111 рядків |  23.69% | ETA 12:55

[1700/7133] ✓ DDM: 135 рядків |  23.83% | ETA 12:54

   • RAM · 🧠 RAM: 424.0 MB

   ⏳ перед flush · 🧠 RAM: 424.0 MB

💾 batch 17559 → 12,739 рядків (всього 410,551 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17559.csv.gz

   ✅ після flush · 🧠 RAM: 426.4 MB

[1710/7133] ✓ DFAC: 358 рядків |  23.97% | ETA 12:54

[1720/7133] ✓ DFAU: 280 рядків |  24.11% | ETA 12:53

[1730/7133] ✓ DFIV: 352 рядків |  24.25% | ETA 12:52

[1740/7133] ✓ DGNX: 207 рядків |  24.39% | ETA 12:51

[1750/7133] ✓ DHR: 395 рядків |  24.53% | ETA 12:50

   • RAM · 🧠 RAM: 432.1 MB

   ⏳ перед flush · 🧠 RAM: 432.1 MB

💾 batch 17560 → 13,700 рядків (всього 424,251 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17560.csv.gz

   ✅ після flush · 🧠 RAM: 433.5 MB

[1760/7133] ✓ DIPS: 3 рядків |  24.67% | ETA 12:49

[1770/7133] ✓ DJIA: 38 рядків |  24.81% | ETA 12:49

[1780/7133] ✓ DLN: 119 рядків |  24.95% | ETA 12:48

[1790/7133] ✓ DLTH: 62 рядків |  25.09% | ETA 12:46

[1800/7133] ✓ DOCS: 384 рядків |  25.23% | ETA 12:45

   • RAM · 🧠 RAM: 432.9 MB

   ⏳ перед flush · 🧠 RAM: 432.9 MB

💾 batch 17561 → 22,617 рядків (всього 446,868 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17561.csv.gz

   ✅ після flush · 🧠 RAM: 436.6 MB

[1810/7133] ✓ DON: 206 рядків |  25.38% | ETA 12:45

[1820/7133] ✓ DPZ: 391 рядків |  25.52% | ETA 12:44

[1830/7133] ✓ DRIP: 382 рядків |  25.66% | ETA 12:43

[1840/7133] ✓ DRN: 350 рядків |  25.80% | ETA 12:42

[1850/7133] ✓ DSGR: 215 рядків |  25.94% | ETA 12:40

   • RAM · 🧠 RAM: 431.6 MB

   ⏳ перед flush · 🧠 RAM: 431.6 MB

💾 batch 17562 → 11,017 рядків (всього 457,885 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17562.csv.gz

   ✅ після flush · 🧠 RAM: 428.6 MB

[1860/7133] ✓ DTCX: 68 рядків |  26.08% | ETA 12:40

[1870/7133] ✓ DUG: 133 рядків |  26.22% | ETA 12:39

[1880/7133] ✓ DVA: 280 рядків |  26.36% | ETA 12:39

[1890/7133] ✓ DXLG: 275 рядків |  26.50% | ETA 12:38

[1900/7133] ✓ DZZ: 1 рядків |  26.64% | ETA 12:37

   • RAM · 🧠 RAM: 426.0 MB

   ⏳ перед flush · 🧠 RAM: 425.9 MB

💾 batch 17563 → 10,083 рядків (всього 467,968 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17563.csv.gz

   ✅ після flush · 🧠 RAM: 428.4 MB

[1910/7133] ✓ EAF: 244 рядків |  26.78% | ETA 12:37

[1920/7133] ✓ ECBK: 9 рядків |  26.92% | ETA 12:35

[1930/7133] ✓ EDF: 81 рядків |  27.06% | ETA 12:34

[1940/7133] ✓ EDD: 135 рядків |  27.20% | ETA 12:33

[1950/7133] ✓ EFG: 410 рядків |  27.34% | ETA 12:32

   • RAM · 🧠 RAM: 428.3 MB

   ⏳ перед flush · 🧠 RAM: 428.3 MB

💾 batch 17564 → 10,806 рядків (всього 478,774 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17564.csv.gz

   ✅ після flush · 🧠 RAM: 430.2 MB

[1960/7133] ✓ EG: 327 рядків |  27.48% | ETA 12:32

[1970/7133] ✓ EHGO: 100 рядків |  27.62% | ETA 12:30

[1980/7133] ✓ EIS: 32 рядків |  27.76% | ETA 12:29

[1990/7133] ✓ ELDN: 281 рядків |  27.90% | ETA 12:28

[2000/7133] ✓ ELPW: 518 рядків |  28.04% | ETA 12:27

   • RAM · 🧠 RAM: 434.6 MB

   ⏳ перед flush · 🧠 RAM: 434.6 MB

💾 batch 17565 → 10,226 рядків (всього 489,000 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17565.csv.gz

   ✅ після flush · 🧠 RAM: 434.7 MB

[2010/7133] ✓ EMB: 393 рядків |  28.18% | ETA 12:26

[2020/7133] ✓ ENGS: 256 рядків |  28.32% | ETA 12:25

[2030/7133] ✓ ENLV: 185 рядків |  28.46% | ETA 12:24

[2040/7133] ✓ ENTG: 368 рядків |  28.60% | ETA 12:23

[2050/7133] ✓ EOSE: 881 рядків |  28.74% | ETA 12:21

   • RAM · 🧠 RAM: 435.6 MB

   ⏳ перед flush · 🧠 RAM: 435.6 MB

💾 batch 17566 → 12,240 рядків (всього 501,240 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17566.csv.gz

   ✅ після flush · 🧠 RAM: 437.2 MB

[2060/7133] ✓ EPOL: 229 рядків |  28.88% | ETA 12:21

[2070/7133] ✓ EQPT: 408 рядків |  29.02% | ETA 12:19

[2080/7133] ✓ ERO: 369 рядків |  29.16% | ETA 12:18

[2090/7133] ✓ ESAB: 296 рядків |  29.30% | ETA 12:17

[2100/7133] ✓ ESRT: 392 рядків |  29.44% | ETA 12:16

   • RAM · 🧠 RAM: 437.9 MB

   ⏳ перед flush · 🧠 RAM: 437.9 MB

💾 batch 17567 → 11,562 рядків (всього 512,802 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17567.csv.gz

   ✅ після flush · 🧠 RAM: 438.4 MB

[2110/7133] ✓ ETHB: 275 рядків |  29.58% | ETA 12:15

[2120/7133] ✓ ETNG: 4 рядків |  29.72% | ETA 12:14

[2130/7133] ✓ EUO: 13 рядків |  29.86% | ETA 12:13

[2140/7133] ✓ EVER: 286 рядків |  30.00% | ETA 12:11

[2150/7133] ✓ EVR: 364 рядків |  30.14% | ETA 12:10

   • RAM · 🧠 RAM: 439.0 MB

   ⏳ перед flush · 🧠 RAM: 439.0 MB

💾 batch 17568 → 12,199 рядків (всього 525,001 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17568.csv.gz

   ✅ після flush · 🧠 RAM: 441.1 MB

[2160/7133] ✓ EWG: 355 рядків |  30.28% | ETA 12:10

[2170/7133] ✓ EWO: 35 рядків |  30.42% | ETA 12:09

[2180/7133] ✓ EXE: 404 рядків |  30.56% | ETA 12:07

[2190/7133] ✓ EXI: 70 рядків |  30.70% | ETA 12:06

[2200/7133] ✓ EZRA: 16 рядків |  30.84% | ETA 12:05

   • RAM · 🧠 RAM: 441.3 MB

   ⏳ перед flush · 🧠 RAM: 441.3 MB

💾 batch 17569 → 13,628 рядків (всього 538,629 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17569.csv.gz

   ✅ після flush · 🧠 RAM: 442.0 MB

[2210/7133] ✓ EZU: 319 рядків |  30.98% | ETA 12:05

[2220/7133] ✓ FBDT: 361 рядків |  31.12% | ETA 12:03

[2230/7133] ✓ FBIO: 229 рядків |  31.26% | ETA 12:02

[2240/7133] ✓ FBRT: 380 рядків |  31.40% | ETA 12:01

[2250/7133] ✓ FCN: 192 рядків |  31.54% | ETA 12:00

   • RAM · 🧠 RAM: 440.2 MB

   ⏳ перед flush · 🧠 RAM: 440.2 MB

💾 batch 17570 → 12,236 рядків (всього 550,865 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17570.csv.gz

   ✅ після flush · 🧠 RAM: 442.6 MB

[2260/7133] ✓ FCXG: 3 рядків |  31.68% | ETA 11:59

[2270/7133] ✓ FDVV: 391 рядків |  31.82% | ETA 11:58

[2280/7133] ✓ FEMR: 91 рядків |  31.96% | ETA 11:57

[2290/7133] ✓ FETH: 402 рядків |  32.10% | ETA 11:56

[2300/7133] ✓ FGBI: 23 рядків |  32.24% | ETA 11:54

   • RAM · 🧠 RAM: 444.3 MB

   ⏳ перед flush · 🧠 RAM: 444.4 MB

💾 batch 17571 → 11,062 рядків (всього 561,927 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17571.csv.gz

   ✅ після flush · 🧠 RAM: 444.8 MB

[2310/7133] ✓ FHI: 261 рядків |  32.38% | ETA 11:54

[2320/7133] ✓ FICO: 408 рядків |  32.52% | ETA 11:53

[2330/7133] ✓ FIW: 84 рядків |  32.67% | ETA 11:52

[2340/7133] ✓ FLGT: 170 рядків |  32.81% | ETA 11:50

[2350/7133] ✓ FLNA: 307 рядків |  32.95% | ETA 11:49

   • RAM · 🧠 RAM: 447.3 MB

   ⏳ перед flush · 🧠 RAM: 447.3 MB

💾 batch 17572 → 11,020 рядків (всього 572,947 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17572.csv.gz

   ✅ після flush · 🧠 RAM: 448.7 MB

[2360/7133] ✓ FLS: 330 рядків |  33.09% | ETA 11:49

[2370/7133] ✓ FLYW: 325 рядків |  33.23% | ETA 11:47

[2380/7133] ✓ FMFC: 131 рядків |  33.37% | ETA 11:46

[2390/7133] ✓ FNG: 136 рядків |  33.51% | ETA 11:45

[2400/7133] ✓ FNLC: 39 рядків |  33.65% | ETA 11:44

   • RAM · 🧠 RAM: 442.3 MB

   ⏳ перед flush · 🧠 RAM: 442.4 MB

💾 batch 17573 → 11,928 рядків (всього 584,875 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17573.csv.gz

   ✅ після flush · 🧠 RAM: 444.0 MB

[2410/7133] ✓ FOX: 283 рядків |  33.79% | ETA 11:44

[2420/7133] ✓ FRAF: 28 рядків |  33.93% | ETA 11:43

[2430/7133] ✓ FRNM: 255 рядків |  34.07% | ETA 11:41

[2440/7133] ✓ FRVO: 654 рядків |  34.21% | ETA 11:40

[2450/7133] ✓ FSS: 184 рядків |  34.35% | ETA 11:39

   • RAM · 🧠 RAM: 446.6 MB

   ⏳ перед flush · 🧠 RAM: 446.6 MB

💾 batch 17574 → 12,254 рядків (всього 597,129 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17574.csv.gz

   ✅ після flush · 🧠 RAM: 448.5 MB

[2460/7133] ✓ FTH: 290 рядків |  34.49% | ETA 11:38

[2470/7133] ✓ FTHM: 1,175 рядків |  34.63% | ETA 11:37

[2480/7133] ✓ FUFU: 28 рядків |  34.77% | ETA 11:36

[2490/7133] ✓ FVCB: 67 рядків |  34.91% | ETA 11:35

[2500/7133] ✓ FVRR: 240 рядків |  35.05% | ETA 11:34

   • RAM · 🧠 RAM: 437.5 MB

   ⏳ перед flush · 🧠 RAM: 437.3 MB

💾 batch 17575 → 13,172 рядків (всього 610,301 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17575.csv.gz

   ✅ після flush · 🧠 RAM: 440.0 MB

[2510/7133] – GAMB: empty |  35.19% | ETA 11:33

[2520/7133] ✓ GANX: 232 рядків |  35.33% | ETA 11:32

[2530/7133] ✓ GBTC: 436 рядків |  35.47% | ETA 11:31

[2540/7133] ✓ GCTS: 352 рядків |  35.61% | ETA 11:30

[2550/7133] ✓ GDLC: 41 рядків |  35.75% | ETA 11:28

   • RAM · 🧠 RAM: 433.6 MB

   ⏳ перед flush · 🧠 RAM: 433.6 MB

💾 batch 17576 → 15,911 рядків (всього 626,212 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17576.csv.gz

   ✅ після flush · 🧠 RAM: 432.7 MB

[2560/7133] ✓ GEF: 158 рядків |  35.89% | ETA 11:28

[2570/7133] ✓ GENI: 462 рядків |  36.03% | ETA 11:27

[2580/7133] ✓ GEVX: 97 рядків |  36.17% | ETA 11:26

[2590/7133] ✓ GGLS: 32 рядків |  36.31% | ETA 11:24

[2600/7133] ✓ GHC: 187 рядків |  36.45% | ETA 11:23

   • RAM · 🧠 RAM: 429.4 MB

   ⏳ перед flush · 🧠 RAM: 429.2 MB

💾 batch 17577 → 14,050 рядків (всього 640,262 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17577.csv.gz

   ✅ після flush · 🧠 RAM: 432.7 MB

[2610/7133] ✓ GIAX: 84 рядків |  36.59% | ETA 11:23

[2620/7133] ✓ GLD: 902 рядків |  36.73% | ETA 11:21

[2630/7133] ✓ GLOB: 273 рядків |  36.87% | ETA 11:20

[2640/7133] ✓ GLND: 1,198 рядків |  37.01% | ETA 11:19

[2650/7133] ✓ GM: 425 рядків |  37.15% | ETA 11:18

   • RAM · 🧠 RAM: 433.8 MB

   ⏳ перед flush · 🧠 RAM: 433.8 MB

💾 batch 17578 → 13,451 рядків (всього 653,713 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17578.csv.gz

   ✅ після flush · 🧠 RAM: 435.4 MB

[2660/7133] ✓ GNOM: 45 рядків |  37.29% | ETA 11:17

[2670/7133] ✓ GNTA: 28 рядків |  37.43% | ETA 11:16

[2680/7133] ✓ GOOD: 204 рядків |  37.57% | ETA 11:14

[2690/7133] ✓ GOOP: 16 рядків |  37.71% | ETA 11:13

[2700/7133] ✓ GOVX: 103 рядків |  37.85% | ETA 11:12

   • RAM · 🧠 RAM: 438.4 MB

   ⏳ перед flush · 🧠 RAM: 438.4 MB

💾 batch 17579 → 10,911 рядків (всього 664,624 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17579.csv.gz

   ✅ після flush · 🧠 RAM: 440.0 MB

[2710/7133] ✓ GPMT: 115 рядків |  37.99% | ETA 11:11

[2720/7133] ✓ GRDN: 248 рядків |  38.13% | ETA 11:10

[2730/7133] ✓ GRID: 325 рядків |  38.27% | ETA 11:09

[2740/7133] ✓ GRNT: 360 рядків |  38.41% | ETA 11:08

[2750/7133] ✓ GSBD: 262 рядків |  38.55% | ETA 11:06

   • RAM · 🧠 RAM: 442.1 MB

   ⏳ перед flush · 🧠 RAM: 442.0 MB

💾 batch 17580 → 13,356 рядків (всього 677,980 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17580.csv.gz

   ✅ після flush · 🧠 RAM: 443.7 MB

[2760/7133] ✓ GSM: 293 рядків |  38.69% | ETA 11:06

[2770/7133] ✓ GTM: 391 рядків |  38.83% | ETA 11:05

[2780/7133] ✓ GWH: 553 рядків |  38.97% | ETA 11:03

[2790/7133] ✓ GWAV: 10 рядків |  39.11% | ETA 11:02

[2800/7133] ✓ HAO: 83 рядків |  39.25% | ETA 11:01

   • RAM · 🧠 RAM: 444.3 MB

   ⏳ перед flush · 🧠 RAM: 444.3 MB

💾 batch 17581 → 11,407 рядків (всього 689,387 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17581.csv.gz

   ✅ після flush · 🧠 RAM: 447.9 MB

[2810/7133] ✓ HASI: 307 рядків |  39.39% | ETA 11:01

[2820/7133] ✓ HCC: 179 рядків |  39.53% | ETA 10:59

[2830/7133] ✓ HDSN: 171 рядків |  39.67% | ETA 10:58

[2840/7133] ✓ HE: 383 рядків |  39.81% | ETA 10:57

[2850/7133] ✓ HGV: 303 рядків |  39.96% | ETA 10:56

   • RAM · 🧠 RAM: 451.0 MB

   ⏳ перед flush · 🧠 RAM: 451.0 MB

💾 batch 17582 → 11,599 рядків (всього 700,986 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17582.csv.gz

   ✅ після flush · 🧠 RAM: 454.1 MB

[2860/7133] ✓ HIMS: 594 рядків |  40.10% | ETA 10:55

[2870/7133] ✓ HKIT: 74 рядків |  40.24% | ETA 10:54

[2880/7133] ✓ HLIO: 226 рядків |  40.38% | ETA 10:53

[2890/7133] ✓ HMYY: 11 рядків |  40.52% | ETA 10:52

[2900/7133] ✓ HOFT: 13 рядків |  40.66% | ETA 10:50

   • RAM · 🧠 RAM: 455.2 MB

   ⏳ перед flush · 🧠 RAM: 455.2 MB

💾 batch 17583 → 10,621 рядків (всього 711,607 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17583.csv.gz

   ✅ після flush · 🧠 RAM: 456.0 MB

[2910/7133] ✓ HOOG: 184 рядків |  40.80% | ETA 10:50

[2920/7133] ✓ HP: 303 рядків |  40.94% | ETA 10:48

[2930/7133] ✓ HQY: 355 рядків |  41.08% | ETA 10:47

[2940/7133] ✓ HSCS: 85 рядків |  41.22% | ETA 10:46

[2950/7133] ✓ HSY: 352 рядків |  41.36% | ETA 10:44

   • RAM · 🧠 RAM: 458.5 MB

   ⏳ перед flush · 🧠 RAM: 458.7 MB

💾 batch 17584 → 12,950 рядків (всього 724,557 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17584.csv.gz

   ✅ після flush · 🧠 RAM: 459.6 MB

[2960/7133] ✓ HTLD: 301 рядків |  41.50% | ETA 10:43

[2970/7133] ✓ HUHU: 36 рядків |  41.64% | ETA 10:42

[2980/7133] ✓ HUT: 498 рядків |  41.78% | ETA 10:41

[2990/7133] ✓ HYFM: 14 рядків |  41.92% | ETA 10:40

[3000/7133] ✓ HYPD: 243 рядків |  42.06% | ETA 10:38

   • RAM · 🧠 RAM: 457.5 MB

   ⏳ перед flush · 🧠 RAM: 457.5 MB

💾 batch 17585 → 10,713 рядків (всього 735,270 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17585.csv.gz

   ✅ після flush · 🧠 RAM: 458.9 MB

[3010/7133] ✓ IALT: 379 рядків |  42.20% | ETA 10:37

[3020/7133] ✓ IAUX: 391 рядків |  42.34% | ETA 10:36

[3030/7133] ✓ IBOT: 19 рядків |  42.48% | ETA 10:35

[3040/7133] ✓ IBTI: 187 рядків |  42.62% | ETA 10:34

[3050/7133] ✓ ICON: 26 рядків |  42.76% | ETA 10:32

   • RAM · 🧠 RAM: 461.5 MB

   ⏳ перед flush · 🧠 RAM: 461.5 MB

💾 batch 17586 → 11,705 рядків (всього 746,975 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17586.csv.gz

   ✅ після flush · 🧠 RAM: 463.9 MB

[3060/7133] ✓ IDA: 264 рядків |  42.90% | ETA 10:32

[3070/7133] ✓ IDHQ: 147 рядків |  43.04% | ETA 10:30

[3080/7133] ✓ IEI: 399 рядків |  43.18% | ETA 10:29

[3090/7133] ✓ IEX: 194 рядків |  43.32% | ETA 10:28

[3100/7133] ✓ IFS: 109 рядків |  43.46% | ETA 10:27

   • RAM · 🧠 RAM: 450.5 MB

   ⏳ перед flush · 🧠 RAM: 450.5 MB

💾 batch 17587 → 11,513 рядків (всього 758,488 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17587.csv.gz

   ✅ після flush · 🧠 RAM: 450.3 MB

[3110/7133] ✓ IGSB: 383 рядків |  43.60% | ETA 10:26

[3120/7133] ✓ IJR: 392 рядків |  43.74% | ETA 10:24

[3130/7133] ✓ ILIT: 21 рядків |  43.88% | ETA 10:23

[3140/7133] ✓ IMCC: 442 рядків |  44.02% | ETA 10:22

[3150/7133] ✓ IMTE: 3 рядків |  44.16% | ETA 10:21

   • RAM · 🧠 RAM: 445.4 MB

   ⏳ перед flush · 🧠 RAM: 445.4 MB

💾 batch 17588 → 20,874 рядків (всього 779,362 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17588.csv.gz

   ✅ після flush · 🧠 RAM: 447.8 MB

[3160/7133] ✓ INBX: 121 рядків |  44.30% | ETA 10:20

[3170/7133] ✓ INDV: 317 рядків |  44.44% | ETA 10:19

[3180/7133] ✓ INGM: 339 рядків |  44.58% | ETA 10:17

[3190/7133] ✓ INN: 347 рядків |  44.72% | ETA 10:16

[3200/7133] ✓ INSE: 140 рядків |  44.86% | ETA 10:15

   • RAM · 🧠 RAM: 436.2 MB

   ⏳ перед flush · 🧠 RAM: 436.2 MB

💾 batch 17589 → 12,259 рядків (всього 791,621 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17589.csv.gz

   ✅ після flush · 🧠 RAM: 440.5 MB

[3210/7133] ✓ INUV: 109 рядків |  45.00% | ETA 10:14

[3220/7133] ✓ IONQ: 1,112 рядків |  45.14% | ETA 10:13

[3230/7133] ✓ IOT: 406 рядків |  45.28% | ETA 10:12

[3240/7133] ✓ IPWR: 79 рядків |  45.42% | ETA 10:10

[3250/7133] ✓ IQV: 341 рядків |  45.56% | ETA 10:09

   • RAM · 🧠 RAM: 443.8 MB

   ⏳ перед flush · 🧠 RAM: 443.8 MB

💾 batch 17590 → 17,433 рядків (всього 809,054 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17590.csv.gz

   ✅ після flush · 🧠 RAM: 446.9 MB

[3260/7133] ✓ IREZ: 504 рядків |  45.70% | ETA 10:08

[3270/7133] ✓ ISBA: 25 рядків |  45.84% | ETA 10:07

[3280/7133] ✓ ISTR: 84 рядків |  45.98% | ETA 10:06

[3290/7133] ✓ ITOT: 376 рядків |  46.12% | ETA 10:05

[3300/7133] ✓ IVA: 407 рядків |  46.26% | ETA 10:03

   • RAM · 🧠 RAM: 450.0 MB

   ⏳ перед flush · 🧠 RAM: 450.0 MB

💾 batch 17591 → 12,791 рядків (всього 821,845 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17591.csv.gz

   ✅ після flush · 🧠 RAM: 451.6 MB

[3310/7133] ✓ IVOO: 87 рядків |  46.40% | ETA 10:02

[3320/7133] ✓ IVW: 380 рядків |  46.54% | ETA 10:01

[3330/7133] ✓ IX: 228 рядків |  46.68% | ETA 10:00

[3340/7133] ✓ IXG: 37 рядків |  46.82% | ETA 09:59

[3350/7133] ✓ JAGU: 139 рядків |  46.96% | ETA 09:58

   • RAM · 🧠 RAM: 455.4 MB

   ⏳ перед flush · 🧠 RAM: 455.4 MB

💾 batch 17592 → 12,911 рядків (всього 834,756 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17592.csv.gz

   ✅ після flush · 🧠 RAM: 456.9 MB

[3360/7133] ✓ IZM: 170 рядків |  47.11% | ETA 09:57

[3370/7133] ✓ JBHT: 357 рядків |  47.25% | ETA 09:55

[3380/7133] ✓ JCI: 391 рядків |  47.39% | ETA 09:54

[3390/7133] ✓ JFIN: 22 рядків |  47.53% | ETA 09:53

[3400/7133] ✓ JHX: 393 рядків |  47.67% | ETA 09:52

   • RAM · 🧠 RAM: 458.5 MB

   ⏳ перед flush · 🧠 RAM: 458.5 MB

💾 batch 17593 → 12,684 рядків (всього 847,440 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17593.csv.gz

   ✅ після flush · 🧠 RAM: 460.2 MB

[3410/7133] ✓ JMIA: 329 рядків |  47.81% | ETA 09:51

[3420/7133] ✓ JONE: 2 рядків |  47.95% | ETA 09:50

[3430/7133] ✓ JPEF: 77 рядків |  48.09% | ETA 09:48

[3440/7133] ✓ JRSH: 81 рядків |  48.23% | ETA 09:47

[3450/7133] ✓ JSPR: 109 рядків |  48.37% | ETA 09:45

   • RAM · 🧠 RAM: 462.0 MB

   ⏳ перед flush · 🧠 RAM: 461.8 MB

💾 batch 17594 → 11,232 рядків (всього 858,672 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17594.csv.gz

   ✅ після flush · 🧠 RAM: 464.4 MB

[3460/7133] ✓ KALA: 152 рядків |  48.51% | ETA 09:45

[3470/7133] ✓ KAI: 118 рядків |  48.65% | ETA 09:43

[3480/7133] ✓ KD: 395 рядків |  48.79% | ETA 09:42

[3490/7133] ✓ KEY: 395 рядків |  48.93% | ETA 09:41

[3500/7133] ✓ KGLD: 155 рядків |  49.07% | ETA 09:39

   • RAM · 🧠 RAM: 466.7 MB

   ⏳ перед flush · 🧠 RAM: 466.7 MB

💾 batch 17595 → 9,517 рядків (всього 868,189 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17595.csv.gz

   ✅ після flush · 🧠 RAM: 467.9 MB

[3510/7133] ✓ KIO: 164 рядків |  49.21% | ETA 09:38

[3520/7133] – KLXER: empty |  49.35% | ETA 09:37

[3530/7133] ✓ KMTS: 200 рядків |  49.49% | ETA 09:36

[3540/7133] ✓ KNRX: 13 рядків |  49.63% | ETA 09:34

[3550/7133] ✓ KORP: 124 рядків |  49.77% | ETA 09:33

   • RAM · 🧠 RAM: 470.0 MB

   ⏳ перед flush · 🧠 RAM: 470.0 MB

💾 batch 17596 → 12,519 рядків (всього 880,708 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17596.csv.gz

   ✅ після flush · 🧠 RAM: 469.2 MB

[3560/7133] ✓ KQQQ: 75 рядків |  49.91% | ETA 09:32

[3570/7133] ✓ KRNY: 260 рядків |  50.05% | ETA 09:31

[3580/7133] ✓ KSCP: 288 рядків |  50.19% | ETA 09:29

[3590/7133] ✓ KVHI: 59 рядків |  50.33% | ETA 09:28

[3600/7133] ✓ KXIN: 94 рядків |  50.47% | ETA 09:27

   • RAM · 🧠 RAM: 469.1 MB

   ⏳ перед flush · 🧠 RAM: 469.1 MB

💾 batch 17597 → 16,717 рядків (всього 897,425 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17597.csv.gz

   ✅ після flush · 🧠 RAM: 471.5 MB

[3610/7133] ✓ KYMR: 248 рядків |  50.61% | ETA 09:26

[3620/7133] ✓ LAND: 282 рядків |  50.75% | ETA 09:24

[3630/7133] ✓ LAZR: 135 рядків |  50.89% | ETA 09:23

[3640/7133] ✓ LBTYK: 369 рядків |  51.03% | ETA 09:22

[3650/7133] ✓ LCUT: 189 рядків |  51.17% | ETA 09:20

   • RAM · 🧠 RAM: 470.9 MB

   ⏳ перед flush · 🧠 RAM: 470.9 MB

💾 batch 17598 → 11,775 рядків (всього 909,200 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17598.csv.gz

   ✅ після flush · 🧠 RAM: 473.2 MB

[3660/7133] ✓ LEGN: 359 рядків |  51.31% | ETA 09:19

[3670/7133] ✓ LFTO: 177 рядків |  51.45% | ETA 09:18

[3680/7133] ✓ LGPS: 33 рядків |  51.59% | ETA 09:17

[3690/7133] ✓ LHSW: 440 рядків |  51.73% | ETA 09:15

[3700/7133] ✓ LINK: 62 рядків |  51.87% | ETA 09:14

   • RAM · 🧠 RAM: 462.9 MB

   ⏳ перед flush · 🧠 RAM: 462.9 MB

💾 batch 17599 → 10,177 рядків (всього 919,377 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17599.csv.gz

   ✅ після flush · 🧠 RAM: 465.3 MB

[3710/7133] – LIXT: empty |  52.01% | ETA 09:13

[3720/7133] ✓ LKFT: 217 рядків |  52.15% | ETA 09:12

[3730/7133] ✓ LMRI: 235 рядків |  52.29% | ETA 09:10

[3740/7133] ✓ LOAN: 22 рядків |  52.43% | ETA 09:09

[3750/7133] ✓ LOFF: 413 рядків |  52.57% | ETA 09:08

   • RAM · 🧠 RAM: 447.7 MB

   ⏳ перед flush · 🧠 RAM: 447.7 MB

💾 batch 17600 → 10,996 рядків (всього 930,373 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17600.csv.gz

   ✅ після flush · 🧠 RAM: 449.4 MB

[3760/7133] ✓ LONZ: 59 рядків |  52.71% | ETA 09:06

[3770/7133] ✓ LPLA: 389 рядків |  52.85% | ETA 09:05

[3780/7133] ✓ LRCX: 611 рядків |  52.99% | ETA 09:04

[3790/7133] ✓ LSPD: 292 рядків |  53.13% | ETA 09:02

[3800/7133] ✓ LU: 344 рядків |  53.27% | ETA 09:01

   • RAM · 🧠 RAM: 446.7 MB

   ⏳ перед flush · 🧠 RAM: 446.7 MB

💾 batch 17601 → 10,011 рядків (всього 940,384 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17601.csv.gz

   ✅ після flush · 🧠 RAM: 448.1 MB

[3810/7133] ✓ LVLU: 20 рядків |  53.41% | ETA 09:00

[3820/7133] ✓ LWAY: 89 рядків |  53.55% | ETA 08:59

[3830/7133] ✓ LXRX: 390 рядків |  53.69% | ETA 08:57

[3840/7133] ✓ MA: 402 рядків |  53.83% | ETA 08:56

[3850/7133] ✓ MAMO: 24 рядків |  53.97% | ETA 08:55

   • RAM · 🧠 RAM: 451.4 MB

   ⏳ перед flush · 🧠 RAM: 451.4 MB

💾 batch 17602 → 13,243 рядків (всього 953,627 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17602.csv.gz

   ✅ після flush · 🧠 RAM: 453.8 MB

[3860/7133] ✓ MASK: 151 рядків |  54.11% | ETA 08:53

[3870/7133] ✓ MATX: 151 рядків |  54.25% | ETA 08:52

[3880/7133] ✓ MBX: 249 рядків |  54.40% | ETA 08:51

[3890/7133] ✓ MCD: 836 рядків |  54.54% | ETA 08:49

[3900/7133] ✓ MCRI: 105 рядків |  54.68% | ETA 08:48

   • RAM · 🧠 RAM: 456.0 MB

   ⏳ перед flush · 🧠 RAM: 456.0 MB

💾 batch 17603 → 12,648 рядків (всього 966,275 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17603.csv.gz

   ✅ після flush · 🧠 RAM: 457.5 MB

[3910/7133] ✓ MDIA: 10 рядків |  54.82% | ETA 08:47

[3920/7133] ✓ MDT: 433 рядків |  54.96% | ETA 08:46

[3930/7133] ✓ MEOH: 327 рядків |  55.10% | ETA 08:44

[3940/7133] ✓ METU: 783 рядків |  55.24% | ETA 08:43

[3950/7133] ✓ MG: 235 рядків |  55.38% | ETA 08:41

   • RAM · 🧠 RAM: 457.6 MB

   ⏳ перед flush · 🧠 RAM: 457.7 MB

💾 batch 17604 → 12,607 рядків (всього 978,882 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17604.csv.gz

   ✅ після flush · 🧠 RAM: 459.3 MB

[3960/7133] ✓ MGV: 198 рядків |  55.52% | ETA 08:40

[3970/7133] ✓ MGX: 40 рядків |  55.66% | ETA 08:39

[3980/7133] ✓ MIRA: 63 рядків |  55.80% | ETA 08:38

[3990/7133] ✓ MKL: 312 рядків |  55.94% | ETA 08:36

[4000/7133] ✓ MLEC: 12 рядків |  56.08% | ETA 08:34

   • RAM · 🧠 RAM: 460.4 MB

   ⏳ перед flush · 🧠 RAM: 460.4 MB

💾 batch 17605 → 9,827 рядків (всього 988,709 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17605.csv.gz

   ✅ після flush · 🧠 RAM: 461.6 MB

[4010/7133] ✓ MLTX: 377 рядків |  56.22% | ETA 08:33

[4020/7133] ✓ MNDR: 114 рядків |  56.36% | ETA 08:31

[4030/7133] ✓ MNSO: 292 рядків |  56.50% | ETA 08:29

[4040/7133] ✓ MOBX: 228 рядків |  56.64% | ETA 08:27

[4050/7133] ✓ MORT: 289 рядків |  56.78% | ETA 08:26

   • RAM · 🧠 RAM: 462.2 MB

   ⏳ перед flush · 🧠 RAM: 462.2 MB

💾 batch 17606 → 11,004 рядків (всього 999,713 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17606.csv.gz

   ✅ після flush · 🧠 RAM: 462.6 MB

[4060/7133] ✓ MPLT: 203 рядків |  56.92% | ETA 08:24

[4070/7133] ✓ MRBK: 72 рядків |  57.06% | ETA 08:22

[4080/7133] ✓ MRT: 34 рядків |  57.20% | ETA 08:20

[4090/7133] ✓ MRVI: 379 рядків |  57.34% | ETA 08:19

[4100/7133] ✓ MSFD: 321 рядків |  57.48% | ETA 08:17

   • RAM · 🧠 RAM: 463.6 MB

   ⏳ перед flush · 🧠 RAM: 463.6 MB

💾 batch 17607 → 12,854 рядків (всього 1,012,567 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17607.csv.gz

   ✅ після flush · 🧠 RAM: 464.1 MB

[4110/7133] ✓ MSM: 295 рядків |  57.62% | ETA 08:15

[4120/7133] ✓ MSTP: 35 рядків |  57.76% | ETA 08:14

[4130/7133] ✓ MTB: 305 рядків |  57.90% | ETA 08:12

[4140/7133] ✓ MTDR: 358 рядків |  58.04% | ETA 08:10

[4150/7133] ✓ MTX: 94 рядків |  58.18% | ETA 08:08

   • RAM · 🧠 RAM: 462.8 MB

   ⏳ перед flush · 🧠 RAM: 462.8 MB

💾 batch 17608 → 14,216 рядків (всього 1,026,783 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17608.csv.gz

   ✅ після flush · 🧠 RAM: 463.9 MB

[4160/7133] ✓ MUR: 385 рядків |  58.32% | ETA 08:07

[4170/7133] ✓ MUX: 284 рядків |  58.46% | ETA 08:05

[4180/7133] ✓ MWYN: 8 рядків |  58.60% | ETA 08:03

[4190/7133] ✓ MZTI: 166 рядків |  58.74% | ETA 08:01

[4200/7133] ✓ NAMM: 178 рядків |  58.88% | ETA 08:00

   • RAM · 🧠 RAM: 464.6 MB

   ⏳ перед flush · 🧠 RAM: 464.6 MB

💾 batch 17609 → 13,387 рядків (всього 1,040,170 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17609.csv.gz

   ✅ після flush · 🧠 RAM: 465.0 MB

[4210/7133] ✓ NATR: 94 рядків |  59.02% | ETA 07:58

[4220/7133] ✓ NBIL: 661 рядків |  59.16% | ETA 07:56

[4230/7133] ✓ NCI: 186 рядків |  59.30% | ETA 07:55

[4240/7133] ✓ NCT: 330 рядків |  59.44% | ETA 07:53

[4250/7133] ✓ NDLS: 155 рядків |  59.58% | ETA 07:51

   • RAM · 🧠 RAM: 458.8 MB

   ⏳ перед flush · 🧠 RAM: 458.8 MB

💾 batch 17610 → 13,307 рядків (всього 1,053,477 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17610.csv.gz

   ✅ після flush · 🧠 RAM: 459.3 MB

[4260/7133] ✓ NESR: 352 рядків |  59.72% | ETA 07:50

[4270/7133] ✓ NEXN: 219 рядків |  59.86% | ETA 07:48

[4280/7133] ✓ NFTY: 25 рядків |  60.00% | ETA 07:46

[4290/7133] ✓ NIC: 117 рядків |  60.14% | ETA 07:44

[4300/7133] ✓ NIKL: 39 рядків |  60.28% | ETA 07:43

   • RAM · 🧠 RAM: 450.0 MB

   ⏳ перед flush · 🧠 RAM: 450.0 MB

💾 batch 17611 → 10,676 рядків (всього 1,064,153 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17611.csv.gz

   ✅ після flush · 🧠 RAM: 450.4 MB

[4310/7133] ✓ NKLR: 214 рядків |  60.42% | ETA 07:41

[4320/7133] ✓ NLY: 475 рядків |  60.56% | ETA 07:39

[4330/7133] ✓ NNDM: 320 рядків |  60.70% | ETA 07:37

[4340/7133] ✓ NOG: 382 рядків |  60.84% | ETA 07:36

[4350/7133] ✓ NOWL: 575 рядків |  60.98% | ETA 07:34

   • RAM · 🧠 RAM: 446.3 MB

   ⏳ перед flush · 🧠 RAM: 446.3 MB

💾 batch 17612 → 14,626 рядків (всього 1,078,779 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17612.csv.gz

   ✅ після flush · 🧠 RAM: 446.8 MB

[4360/7133] ✓ NPKI: 282 рядків |  61.12% | ETA 07:32

[4370/7133] ✓ NSIT: 168 рядків |  61.26% | ETA 07:31

[4380/7133] ✓ NTNX: 389 рядків |  61.40% | ETA 07:29

[4390/7133] ✓ NTCT: 204 рядків |  61.54% | ETA 07:27

[4400/7133] ✓ NU: 522 рядків |  61.69% | ETA 07:25

   • RAM · 🧠 RAM: 429.7 MB

   ⏳ перед flush · 🧠 RAM: 429.7 MB

💾 batch 17613 → 9,988 рядків (всього 1,088,767 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17613.csv.gz

   ✅ після flush · 🧠 RAM: 430.1 MB

[4410/7133] ✓ NUVB: 394 рядків |  61.83% | ETA 07:24

[4420/7133] ✓ NVDS: 93 рядків |  61.97% | ETA 07:22

[4430/7133] ✓ NVO: 746 рядків |  62.11% | ETA 07:20

[4440/7133] ✓ NVX: 15 рядків |  62.25% | ETA 07:19

[4450/7133] ✓ NWGL: 56 рядків |  62.39% | ETA 07:17

   • RAM · 🧠 RAM: 423.3 MB

   ⏳ перед flush · 🧠 RAM: 423.3 MB

💾 batch 17614 → 12,394 рядків (всього 1,101,161 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17614.csv.gz

   ✅ після flush · 🧠 RAM: 423.8 MB

[4460/7133] ✓ NXAT: 17 рядків |  62.53% | ETA 07:15

[4470/7133] ✓ NXTC: 86 рядків |  62.67% | ETA 07:14

[4480/7133] ✓ NYXH: 156 рядків |  62.81% | ETA 07:12

[4490/7133] ✓ OBDC: 415 рядків |  62.95% | ETA 07:10

[4500/7133] ✓ ODC: 89 рядків |  63.09% | ETA 07:08

   • RAM · 🧠 RAM: 424.6 MB

   ⏳ перед flush · 🧠 RAM: 424.6 MB

💾 batch 17615 → 10,180 рядків (всього 1,111,341 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17615.csv.gz

   ✅ після flush · 🧠 RAM: 425.0 MB

[4510/7133] – ODV: empty |  63.23% | ETA 07:07

[4520/7133] ✓ OGC: 290 рядків |  63.37% | ETA 07:05

[4530/7133] ✓ OILU: 112 рядків |  63.51% | ETA 07:03

[4540/7133] ✓ OKTA: 471 рядків |  63.65% | ETA 07:02

[4550/7133] – OLPX: empty |  63.79% | ETA 07:00

   • RAM · 🧠 RAM: 425.2 MB

   ⏳ перед flush · 🧠 RAM: 425.2 MB

💾 batch 17616 → 11,656 рядків (всього 1,122,997 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17616.csv.gz

   ✅ після flush · 🧠 RAM: 425.7 MB

[4560/7133] ✓ OMEX: 171 рядків |  63.93% | ETA 06:58

[4570/7133] ✓ ONDS: 862 рядків |  64.07% | ETA 06:57

[4580/7133] ✓ ONTO: 251 рядків |  64.21% | ETA 06:55

[4590/7133] ✓ OPCH: 360 рядків |  64.35% | ETA 06:53

[4600/7133] ✓ OPTT: 183 рядків |  64.49% | ETA 06:51

   • RAM · 🧠 RAM: 425.0 MB

   ⏳ перед flush · 🧠 RAM: 425.0 MB

💾 batch 17617 → 12,199 рядків (всього 1,135,196 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17617.csv.gz

   ✅ після flush · 🧠 RAM: 425.6 MB

[4610/7133] ✓ OR: 259 рядків |  64.63% | ETA 06:50

[4620/7133] – ORGN: empty |  64.77% | ETA 06:48

[4630/7133] ✓ ORIC: 341 рядків |  64.91% | ETA 06:46

[4640/7133] ✓ OSS: 299 рядків |  65.05% | ETA 06:45

[4650/7133] ✓ OTF: 346 рядків |  65.19% | ETA 06:43

   • RAM · 🧠 RAM: 424.9 MB

   ⏳ перед flush · 🧠 RAM: 424.9 MB

💾 batch 17618 → 18,317 рядків (всього 1,153,513 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17618.csv.gz

   ✅ після flush · 🧠 RAM: 426.7 MB

[4660/7133] ✓ OVBC: 28 рядків |  65.33% | ETA 06:41

[4670/7133] ✓ OXY/W: 32 рядків |  65.47% | ETA 06:40

[4680/7133] ✓ PAAI: 615 рядків |  65.61% | ETA 06:38

[4690/7133] ✓ PALD: 75 рядків |  65.75% | ETA 06:36

[4700/7133] ✓ PAPL: 111 рядків |  65.89% | ETA 06:35

   • RAM · 🧠 RAM: 426.4 MB

   ⏳ перед flush · 🧠 RAM: 426.4 MB

💾 batch 17619 → 13,058 рядків (всього 1,166,571 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17619.csv.gz

   ✅ після flush · 🧠 RAM: 427.1 MB

[4710/7133] ✓ PATK: 250 рядків |  66.03% | ETA 06:33

[4720/7133] ✓ PAY: 311 рядків |  66.17% | ETA 06:31

[4730/7133] ✓ PBI: 285 рядків |  66.31% | ETA 06:30

[4740/7133] ✓ PCLA: 58 рядків |  66.45% | ETA 06:28

[4750/7133] ✓ PCT: 405 рядків |  66.59% | ETA 06:26

   • RAM · 🧠 RAM: 425.2 MB

   ⏳ перед flush · 🧠 RAM: 425.2 MB

💾 batch 17620 → 11,820 рядків (всього 1,178,391 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17620.csv.gz

   ✅ після flush · 🧠 RAM: 425.7 MB

[4760/7133] ✓ PDS: 90 рядків |  66.73% | ETA 06:25

[4770/7133] ✓ PENG: 442 рядків |  66.87% | ETA 06:23

[4780/7133] ✓ PERI: 218 рядків |  67.01% | ETA 06:21

[4790/7133] ✓ PFGC: 361 рядків |  67.15% | ETA 06:20

[4800/7133] ✓ PGC: 84 рядків |  67.29% | ETA 06:18

   • RAM · 🧠 RAM: 426.9 MB

   ⏳ перед flush · 🧠 RAM: 426.9 MB

💾 batch 17621 → 13,515 рядків (всього 1,191,906 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17621.csv.gz

   ✅ після flush · 🧠 RAM: 427.4 MB

[4810/7133] ✓ PGX: 356 рядків |  67.43% | ETA 06:16

[4820/7133] ✓ PHOE: 6 рядків |  67.57% | ETA 06:15

[4830/7133] ✓ PII: 296 рядків |  67.71% | ETA 06:13

[4840/7133] ✓ PKBK: 37 рядків |  67.85% | ETA 06:11

[4850/7133] ✓ PLAY: 381 рядків |  67.99% | ETA 06:09

   • RAM · 🧠 RAM: 428.4 MB

   ⏳ перед flush · 🧠 RAM: 428.4 MB

💾 batch 17622 → 11,874 рядків (всього 1,203,780 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17622.csv.gz

   ✅ після flush · 🧠 RAM: 426.8 MB

[4860/7133] ✓ PLRZ: 4 рядків |  68.13% | ETA 06:08

[4870/7133] ✓ PLTW: 125 рядків |  68.27% | ETA 06:06

[4880/7133] ✓ PM: 392 рядків |  68.41% | ETA 06:05

[4890/7133] ✓ PMA: 15 рядків |  68.55% | ETA 06:03

[4900/7133] ✓ PNTG: 143 рядків |  68.69% | ETA 06:01

   • RAM · 🧠 RAM: 420.8 MB

   ⏳ перед flush · 🧠 RAM: 420.8 MB

💾 batch 17623 → 10,344 рядків (всього 1,214,124 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17623.csv.gz

   ✅ після flush · 🧠 RAM: 421.2 MB

[4910/7133] ✓ PODD: 361 рядків |  68.83% | ETA 06:00

[4920/7133] ✓ POWR: 178 рядків |  68.98% | ETA 05:58

[4930/7133] ✓ PPTA: 300 рядків |  69.12% | ETA 05:56

[4940/7133] ✓ PRCT: 369 рядків |  69.26% | ETA 05:55

[4950/7133] ✓ PRLB: 210 рядків |  69.40% | ETA 05:53

   • RAM · 🧠 RAM: 419.4 MB

   ⏳ перед flush · 🧠 RAM: 419.4 MB

💾 batch 17624 → 11,942 рядків (всього 1,226,066 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17624.csv.gz

   ✅ після flush · 🧠 RAM: 419.9 MB

[4960/7133] ✓ PRQR: 279 рядків |  69.54% | ETA 05:51

[4970/7133] ✓ PRSU: 1,002 рядків |  69.68% | ETA 05:50

[4980/7133] ✓ PSIX: 219 рядків |  69.82% | ETA 05:48

[4990/7133] ✓ PSTL: 162 рядків |  69.96% | ETA 05:46

[5000/7133] ✓ PTCT: 323 рядків |  70.10% | ETA 05:45

   • RAM · 🧠 RAM: 411.9 MB

   ⏳ перед flush · 🧠 RAM: 411.9 MB

💾 batch 17625 → 11,738 рядків (всього 1,237,804 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17625.csv.gz

   ✅ після flush · 🧠 RAM: 412.4 MB

[5010/7133] ✓ PTRN: 404 рядків |  70.24% | ETA 05:43

[5020/7133] ✓ PVAL: 375 рядків |  70.38% | ETA 05:41

[5030/7133] ✓ PWRD: 53 рядків |  70.52% | ETA 05:40

[5040/7133] ✓ PYXS: 288 рядків |  70.66% | ETA 05:38

[5050/7133] ✓ QDEL: 300 рядків |  70.80% | ETA 05:36

   • RAM · 🧠 RAM: 398.1 MB

   ⏳ перед flush · 🧠 RAM: 398.1 MB

💾 batch 17626 → 14,907 рядків (всього 1,252,711 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17626.csv.gz

   ✅ після flush · 🧠 RAM: 398.8 MB

[5060/7133] ✓ QLTA: 101 рядків |  70.94% | ETA 05:35

[5070/7133] ✓ QLYS: 264 рядків |  71.08% | ETA 05:33

[5080/7133] ✓ QNDX: 309 рядків |  71.22% | ETA 05:31

[5090/7133] ✓ QQQJ: 244 рядків |  71.36% | ETA 05:30

[5100/7133] ✓ QS: 564 рядків |  71.50% | ETA 05:28

   • RAM · 🧠 RAM: 393.2 MB

   ⏳ перед flush · 🧠 RAM: 393.2 MB

💾 batch 17627 → 13,062 рядків (всього 1,265,773 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17627.csv.gz

   ✅ після flush · 🧠 RAM: 393.8 MB

[5110/7133] ✓ QUBX: 31 рядків |  71.64% | ETA 05:26

[5120/7133] ✓ QURE: 386 рядків |  71.78% | ETA 05:25

[5130/7133] ✓ RADX: 23 рядків |  71.92% | ETA 05:23

[5140/7133] ✓ RBB: 118 рядків |  72.06% | ETA 05:21

[5150/7133] ✓ RBNE: 30 рядків |  72.20% | ETA 05:20

   • RAM · 🧠 RAM: 383.9 MB

   ⏳ перед flush · 🧠 RAM: 383.9 MB

💾 batch 17628 → 11,466 рядків (всього 1,277,239 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17628.csv.gz

   ✅ після flush · 🧠 RAM: 384.5 MB

[5160/7133] ✓ RCBC: 68 рядків |  72.34% | ETA 05:18

[5170/7133] ✓ RDCM: 48 рядків |  72.48% | ETA 05:17

[5180/7133] ✓ RDWR: 151 рядків |  72.62% | ETA 05:15

[5190/7133] ✓ REAX: 361 рядків |  72.76% | ETA 05:13

[5200/7133] ✓ REIT: 20 рядків |  72.90% | ETA 05:12

   • RAM · 🧠 RAM: 381.7 MB

   ⏳ перед flush · 🧠 RAM: 381.7 MB

💾 batch 17629 → 10,991 рядків (всього 1,288,230 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17629.csv.gz

   ✅ після flush · 🧠 RAM: 382.3 MB

[5210/7133] ✓ RENT: 106 рядків |  73.04% | ETA 05:10

[5220/7133] ✓ REX: 110 рядків |  73.18% | ETA 05:08

[5230/7133] ✓ RGNT: 17 рядків |  73.32% | ETA 05:07

[5240/7133] ✓ RGTU: 63 рядків |  73.46% | ETA 05:05

[5250/7133] ✓ RIME: 323 рядків |  73.60% | ETA 05:03

   • RAM · 🧠 RAM: 383.1 MB

   ⏳ перед flush · 🧠 RAM: 383.1 MB

💾 batch 17630 → 13,140 рядків (всього 1,301,370 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17630.csv.gz

   ✅ після flush · 🧠 RAM: 383.7 MB

[5260/7133] ✓ RJET: 46 рядків |  73.74% | ETA 05:02

[5270/7133] ✓ RKLX: 698 рядків |  73.88% | ETA 05:00

[5280/7133] ✓ RML: 21 рядків |  74.02% | ETA 04:58

[5290/7133] ✓ RMSG: 154 рядків |  74.16% | ETA 04:57

[5300/7133] ✓ ROBT: 62 рядків |  74.30% | ETA 04:55

   • RAM · 🧠 RAM: 383.4 MB

   ⏳ перед flush · 🧠 RAM: 383.4 MB

💾 batch 17631 → 11,867 рядків (всього 1,313,237 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17631.csv.gz

   ✅ після flush · 🧠 RAM: 384.1 MB

[5310/7133] ✓ ROM: 56 рядків |  74.44% | ETA 04:54

[5320/7133] ✓ ROST: 391 рядків |  74.58% | ETA 04:52

[5330/7133] ✓ RRGB: 106 рядків |  74.72% | ETA 04:50

[5340/7133] ✓ RSG: 335 рядків |  74.86% | ETA 04:49

[5350/7133] ✓ RTX: 424 рядків |  75.00% | ETA 04:47

   • RAM · 🧠 RAM: 380.1 MB

   ⏳ перед flush · 🧠 RAM: 380.1 MB

💾 batch 17632 → 11,639 рядків (всього 1,324,876 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17632.csv.gz

   ✅ після flush · 🧠 RAM: 381.6 MB

[5360/7133] ✓ RVLV: 279 рядків |  75.14% | ETA 04:45

[5370/7133] ✓ RWL: 250 рядків |  75.28% | ETA 04:44

[5380/7133] ✓ RXST: 279 рядків |  75.42% | ETA 04:42

[5390/7133] ✓ SA: 237 рядків |  75.56% | ETA 04:40

[5400/7133] ✓ SAIC: 148 рядків |  75.70% | ETA 04:39

   • RAM · 🧠 RAM: 380.4 MB

   ⏳ перед flush · 🧠 RAM: 380.4 MB

💾 batch 17633 → 12,054 рядків (всього 1,336,930 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17633.csv.gz

   ✅ після flush · 🧠 RAM: 381.0 MB

[5410/7133] ✓ SANA: 403 рядків |  75.84% | ETA 04:37

[5420/7133] ✓ SBFG: 32 рядків |  75.98% | ETA 04:36

[5430/7133] ✓ SBSI: 67 рядків |  76.13% | ETA 04:34

[5440/7133] ✓ SCCR: 123 рядків |  76.27% | ETA 04:32

[5450/7133] ✓ SCHL: 370 рядків |  76.41% | ETA 04:31

   • RAM · 🧠 RAM: 381.7 MB

   ⏳ перед flush · 🧠 RAM: 381.7 MB

💾 batch 17634 → 13,321 рядків (всього 1,350,251 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17634.csv.gz

   ✅ після flush · 🧠 RAM: 382.3 MB

[5460/7133] ✓ SCHY: 347 рядків |  76.55% | ETA 04:29

[5470/7133] ✓ SCMB: 331 рядків |  76.69% | ETA 04:27

[5480/7133] ✓ SCYX: 37 рядків |  76.83% | ETA 04:26

[5490/7133] ✓ SDEV: 1,124 рядків |  76.97% | ETA 04:24

[5500/7133] ✓ SEIC: 320 рядків |  77.11% | ETA 04:23

   • RAM · 🧠 RAM: 383.8 MB

   ⏳ перед flush · 🧠 RAM: 383.8 MB

💾 batch 17635 → 14,475 рядків (всього 1,364,726 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17635.csv.gz

   ✅ після flush · 🧠 RAM: 384.4 MB

[5510/7133] ✓ SER: 23 рядків |  77.25% | ETA 04:21

[5520/7133] ✓ SFNC: 364 рядків |  77.39% | ETA 04:19

[5530/7133] ✓ SGC: 28 рядків |  77.53% | ETA 04:18

[5540/7133] ✓ SGRT: 28 рядків |  77.67% | ETA 04:16

[5550/7133] ✓ SGRX: 136 рядків |  77.81% | ETA 04:14

   • RAM · 🧠 RAM: 385.6 MB

   ⏳ перед flush · 🧠 RAM: 385.6 MB

💾 batch 17636 → 12,039 рядків (всього 1,376,765 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17636.csv.gz

   ✅ після flush · 🧠 RAM: 386.2 MB

[5560/7133] ✓ SHMD: 520 рядків |  77.95% | ETA 04:13

[5570/7133] ✓ SHO: 363 рядків |  78.09% | ETA 04:11

[5580/7133] ✓ SIG: 259 рядків |  78.23% | ETA 04:10

[5590/7133] ✓ SIGI: 210 рядків |  78.37% | ETA 04:08

[5600/7133] ✓ SITX: 17 рядків |  78.51% | ETA 04:06

   • RAM · 🧠 RAM: 385.4 MB

   ⏳ перед flush · 🧠 RAM: 385.4 MB

💾 batch 17637 → 12,257 рядків (всього 1,389,022 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17637.csv.gz

   ✅ після flush · 🧠 RAM: 386.9 MB

[5610/7133] ✓ SKHZ: 342 рядків |  78.65% | ETA 04:05

[5620/7133] ✓ SKYH: 124 рядків |  78.79% | ETA 04:03

[5630/7133] ✓ SKYY: 147 рядків |  78.93% | ETA 04:01

[5640/7133] ✓ SLGL: 22 рядків |  79.07% | ETA 04:00

[5650/7133] ✓ SLNH: 450 рядків |  79.21% | ETA 03:58

   • RAM · 🧠 RAM: 388.2 MB

   ⏳ перед flush · 🧠 RAM: 388.2 MB

💾 batch 17638 → 11,888 рядків (всього 1,400,910 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17638.csv.gz

   ✅ після flush · 🧠 RAM: 388.8 MB

[5660/7133] ✓ SMA: 252 рядків |  79.35% | ETA 03:57

[5670/7133] ✓ SLYG: 145 рядків |  79.49% | ETA 03:55

[5680/7133] ✓ SMCY: 354 рядків |  79.63% | ETA 03:53

[5690/7133] ✓ SMJF: 183 рядків |  79.77% | ETA 03:52

[5700/7133] ✓ SMU: 129 рядків |  79.91% | ETA 03:50

   • RAM · 🧠 RAM: 386.9 MB

   ⏳ перед flush · 🧠 RAM: 386.9 MB

💾 batch 17639 → 13,316 рядків (всього 1,414,226 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17639.csv.gz

   ✅ після flush · 🧠 RAM: 387.5 MB

[5710/7133] ✓ SNDC: 119 рядків |  80.05% | ETA 03:48

[5720/7133] ✓ SNES: 22 рядків |  80.19% | ETA 03:47

[5730/7133] ✓ SNDR: 278 рядків |  80.33% | ETA 03:45

[5740/7133] – SNYR: empty |  80.47% | ETA 03:44

[5750/7133] ✓ SOLV: 308 рядків |  80.61% | ETA 03:42

   • RAM · 🧠 RAM: 376.2 MB

   ⏳ перед flush · 🧠 RAM: 376.2 MB

💾 batch 17640 → 13,589 рядків (всього 1,427,815 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17640.csv.gz

   ✅ після flush · 🧠 RAM: 376.9 MB

[5760/7133] ✓ SONY: 434 рядків |  80.75% | ETA 03:40

[5770/7133] ✓ SORA: 2 рядків |  80.89% | ETA 03:39

[5780/7133] ✓ SPAX: 413 рядків |  81.03% | ETA 03:37

[5790/7133] ✓ SPCU: 389 рядків |  81.17% | ETA 03:35

[5800/7133] ✓ SPGP: 94 рядків |  81.31% | ETA 03:34

   • RAM · 🧠 RAM: 370.0 MB

   ⏳ перед flush · 🧠 RAM: 370.0 MB

💾 batch 17641 → 16,990 рядків (всього 1,444,805 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17641.csv.gz

   ✅ після flush · 🧠 RAM: 371.5 MB

[5810/7133] ✓ SPOG: 19 рядків |  81.45% | ETA 03:32

[5820/7133] ✓ SPOT: 435 рядків |  81.59% | ETA 03:31

[5830/7133] ✓ SPT: 317 рядків |  81.73% | ETA 03:29

[5840/7133] ✓ SPUS: 298 рядків |  81.87% | ETA 03:27

[5850/7133] ✓ SPYI: 455 рядків |  82.01% | ETA 03:26

   • RAM · 🧠 RAM: 371.3 MB

   ⏳ перед flush · 🧠 RAM: 371.3 MB

💾 batch 17642 → 14,176 рядків (всього 1,458,981 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17642.csv.gz

   ✅ після flush · 🧠 RAM: 372.0 MB

[5860/7133] ✓ SQNS: 27 рядків |  82.15% | ETA 03:24

[5870/7133] ✓ SRVR: 87 рядків |  82.29% | ETA 03:23

[5880/7133] ✓ SSM: 177 рядків |  82.43% | ETA 03:21

[5890/7133] ✓ SSPC: 608 рядків |  82.57% | ETA 03:19

[5900/7133] ✓ STAK: 847 рядків |  82.71% | ETA 03:18

   • RAM · 🧠 RAM: 373.5 MB

   ⏳ перед flush · 🧠 RAM: 373.5 MB

💾 batch 17643 → 14,855 рядків (всього 1,473,836 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17643.csv.gz

   ✅ після flush · 🧠 RAM: 374.2 MB

[5910/7133] ✓ STEX: 302 рядків |  82.85% | ETA 03:16

[5920/7133] ✓ STLA: 598 рядків |  82.99% | ETA 03:14

[5930/7133] ✓ STRD: 190 рядків |  83.13% | ETA 03:13

[5940/7133] ✓ STUB: 400 рядків |  83.27% | ETA 03:11

[5950/7133] ✓ SUNC: 224 рядків |  83.42% | ETA 03:10

   • RAM · 🧠 RAM: 376.1 MB

   ⏳ перед flush · 🧠 RAM: 376.1 MB

💾 batch 17644 → 11,857 рядків (всього 1,485,693 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17644.csv.gz

   ✅ після flush · 🧠 RAM: 376.7 MB

[5960/7133] ✓ SUIG: 343 рядків |  83.56% | ETA 03:08

[5970/7133] ✓ SVM: 363 рядків |  83.70% | ETA 03:06

[5980/7133] ✓ SWK: 360 рядків |  83.84% | ETA 03:05

[5990/7133] ✓ SXTC: 56 рядків |  83.98% | ETA 03:03

[6000/7133] ✓ SYM: 393 рядків |  84.12% | ETA 03:01

   • RAM · 🧠 RAM: 377.6 MB

   ⏳ перед flush · 🧠 RAM: 377.6 MB

💾 batch 17645 → 14,788 рядків (всього 1,500,481 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17645.csv.gz

   ✅ після flush · 🧠 RAM: 378.4 MB

[6010/7133] ✓ TAOP: 175 рядків |  84.26% | ETA 03:00

[6020/7133] ✓ TARS: 281 рядків |  84.40% | ETA 02:58

[6030/7133] – TBRG: empty |  84.54% | ETA 02:57

[6040/7133] ✓ TCMD: 155 рядків |  84.68% | ETA 02:55

[6050/7133] ✓ TCX: 46 рядків |  84.82% | ETA 02:53

   • RAM · 🧠 RAM: 378.3 MB

   ⏳ перед flush · 🧠 RAM: 378.3 MB

💾 batch 17646 → 10,563 рядків (всього 1,511,044 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17646.csv.gz

   ✅ після flush · 🧠 RAM: 378.8 MB

[6060/7133] ✓ TDIC: 523 рядків |  84.96% | ETA 02:52

[6070/7133] ✓ TE: 799 рядків |  85.10% | ETA 02:50

[6080/7133] ✓ TEN: 219 рядків |  85.24% | ETA 02:49

[6090/7133] ✓ TESL: 3 рядків |  85.38% | ETA 02:47

[6100/7133] ✓ TFX: 290 рядків |  85.52% | ETA 02:45

   • RAM · 🧠 RAM: 380.3 MB

   ⏳ перед flush · 🧠 RAM: 380.3 MB

💾 batch 17647 → 13,483 рядків (всього 1,524,527 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17647.csv.gz

   ✅ після flush · 🧠 RAM: 380.9 MB

[6110/7133] ✓ THC: 273 рядків |  85.66% | ETA 02:44

[6120/7133] ✓ THH: 176 рядків |  85.80% | ETA 02:42

[6130/7133] ✓ THRY: 229 рядків |  85.94% | ETA 02:41

[6140/7133] ✓ TJGC: 90 рядків |  86.08% | ETA 02:39

[6150/7133] ✓ TLPH: 45 рядків |  86.22% | ETA 02:37

   • RAM · 🧠 RAM: 381.6 MB

   ⏳ перед flush · 🧠 RAM: 381.6 MB

💾 batch 17648 → 12,280 рядків (всього 1,536,807 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17648.csv.gz

   ✅ після flush · 🧠 RAM: 382.1 MB

[6160/7133] ✓ TMCI: 152 рядків |  86.36% | ETA 02:36

[6170/7133] – TMCWW: empty |  86.50% | ETA 02:34

[6180/7133] – TMHC: empty |  86.64% | ETA 02:32

[6190/7133] ✓ TOMZ: 61 рядків |  86.78% | ETA 02:31

[6200/7133] ✓ TNON: 485 рядків |  86.92% | ETA 02:29

   • RAM · 🧠 RAM: 383.4 MB

   ⏳ перед flush · 🧠 RAM: 383.4 MB

💾 batch 17649 → 12,754 рядків (всього 1,549,561 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17649.csv.gz

   ✅ після flush · 🧠 RAM: 384.0 MB

[6210/7133] ✓ TOYO: 217 рядків |  87.06% | ETA 02:28

[6220/7133] ✓ TQQQ: 1,169 рядків |  87.20% | ETA 02:26

[6230/7133] ✓ TREX: 381 рядків |  87.34% | ETA 02:24

[6240/7133] ✓ TRN: 233 рядків |  87.48% | ETA 02:23

[6250/7133] ✓ TRST: 68 рядків |  87.62% | ETA 02:21

   • RAM · 🧠 RAM: 385.3 MB

   ⏳ перед flush · 🧠 RAM: 385.3 MB

💾 batch 17650 → 12,021 рядків (всього 1,561,582 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17650.csv.gz

   ✅ після flush · 🧠 RAM: 385.9 MB

[6260/7133] ✓ TRUP: 271 рядків |  87.76% | ETA 02:20

[6270/7133] ✓ TSDD: 476 рядків |  87.90% | ETA 02:18

[6280/7133] ✓ TSLS: 224 рядків |  88.04% | ETA 02:16

[6290/7133] ✓ TSLZ: 481 рядків |  88.18% | ETA 02:15

[6300/7133] ✓ TSUI: 77 рядків |  88.32% | ETA 02:13

   • RAM · 🧠 RAM: 385.7 MB

   ⏳ перед flush · 🧠 RAM: 385.7 MB

💾 batch 17651 → 14,201 рядків (всього 1,575,783 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17651.csv.gz

   ✅ після flush · 🧠 RAM: 386.4 MB

[6310/7133] ✓ TTDU: 89 рядків |  88.46% | ETA 02:12

[6320/7133] ✓ TTRX: 86 рядків |  88.60% | ETA 02:10

[6330/7133] ✓ TWFG: 74 рядків |  88.74% | ETA 02:08

[6340/7133] ✓ TWN: 21 рядків |  88.88% | ETA 02:07

[6350/7133] ✓ TXT: 363 рядків |  89.02% | ETA 02:05

   • RAM · 🧠 RAM: 387.0 MB

   ⏳ перед flush · 🧠 RAM: 387.0 MB

💾 batch 17652 → 11,782 рядків (всього 1,587,565 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17652.csv.gz

   ✅ після flush · 🧠 RAM: 387.5 MB

[6360/7133] ✓ TYGO: 274 рядків |  89.16% | ETA 02:04

[6370/7133] ✓ UAN: 35 рядків |  89.30% | ETA 02:02

[6380/7133] – UBXG: empty |  89.44% | ETA 02:00

[6390/7133] ✓ UFCS: 95 рядків |  89.58% | ETA 01:59

[6400/7133] ✓ UEC: 533 рядків |  89.72% | ETA 01:57

   • RAM · 🧠 RAM: 385.7 MB

   ⏳ перед flush · 🧠 RAM: 385.7 MB

💾 batch 17653 → 10,659 рядків (всього 1,598,224 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17653.csv.gz

   ✅ після flush · 🧠 RAM: 386.3 MB

[6410/7133] ✓ UHS: 267 рядків |  89.86% | ETA 01:55

[6420/7133] ✓ UMC: 456 рядків |  90.00% | ETA 01:54

[6430/7133] ✓ UNCY: 253 рядків |  90.14% | ETA 01:52

[6440/7133] ✓ UNM: 328 рядків |  90.28% | ETA 01:51

[6450/7133] ✓ UPSX: 89 рядків |  90.42% | ETA 01:49

   • RAM · 🧠 RAM: 373.2 MB

   ⏳ перед flush · 🧠 RAM: 373.2 MB

💾 batch 17654 → 11,889 рядків (всього 1,610,113 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17654.csv.gz

   ✅ після flush · 🧠 RAM: 374.7 MB

[6460/7133] ✓ URNM: 265 рядків |  90.56% | ETA 01:47

[6470/7133] ✓ USAX: 89 рядків |  90.71% | ETA 01:46

[6480/7133] ✓ USHY: 394 рядків |  90.85% | ETA 01:44

[6490/7133] ✓ USFR: 483 рядків |  90.99% | ETA 01:43

[6500/7133] ✓ USO: 859 рядків |  91.13% | ETA 01:41

   • RAM · 🧠 RAM: 368.3 MB

   ⏳ перед flush · 🧠 RAM: 368.3 MB

💾 batch 17655 → 12,571 рядків (всього 1,622,684 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17655.csv.gz

   ✅ після flush · 🧠 RAM: 368.9 MB

[6510/7133] ✓ UTSI: 4 рядків |  91.27% | ETA 01:39

[6520/7133] ✓ UWM: 173 рядків |  91.41% | ETA 01:38

[6530/7133] ✓ VALN: 15 рядків |  91.55% | ETA 01:36

[6540/7133] ✓ VB: 383 рядків |  91.69% | ETA 01:35

[6550/7133] ✓ VC: 205 рядків |  91.83% | ETA 01:33

   • RAM · 🧠 RAM: 370.0 MB

   ⏳ перед flush · 🧠 RAM: 370.0 MB

💾 batch 17656 → 12,271 рядків (всього 1,634,955 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17656.csv.gz

   ✅ після flush · 🧠 RAM: 370.8 MB

[6560/7133] ✓ VEEE: 110 рядків |  91.97% | ETA 01:31

[6570/7133] ✓ VERU: 93 рядків |  92.11% | ETA 01:30

[6580/7133] ✓ VFH: 360 рядків |  92.25% | ETA 01:28

[6590/7133] ✓ VGUS: 127 рядків |  92.39% | ETA 01:27

[6600/7133] ✓ VIDA: 37 рядків |  92.53% | ETA 01:25

   • RAM · 🧠 RAM: 372.1 MB

   ⏳ перед flush · 🧠 RAM: 372.1 MB

💾 batch 17657 → 13,744 рядків (всього 1,648,699 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17657.csv.gz

   ✅ після flush · 🧠 RAM: 372.7 MB

[6610/7133] ✓ VIPS: 367 рядків |  92.67% | ETA 01:23

[6620/7133] ✓ VLGEA: 63 рядків |  92.81% | ETA 01:22

[6630/7133] ✓ VLRS: 188 рядків |  92.95% | ETA 01:20

[6640/7133] ✓ VNM: 249 рядків |  93.09% | ETA 01:19

[6650/7133] ✓ VNT: 328 рядків |  93.23% | ETA 01:17

   • RAM · 🧠 RAM: 373.8 MB

   ⏳ перед flush · 🧠 RAM: 373.8 MB

💾 batch 17658 → 13,288 рядків (всього 1,661,987 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17658.csv.gz

   ✅ після flush · 🧠 RAM: 374.5 MB

[6660/7133] ✓ VOOV: 96 рядків |  93.37% | ETA 01:15

[6670/7133] ✓ VPG: 250 рядків |  93.51% | ETA 01:14

[6680/7133] ✓ VRDN: 366 рядків |  93.65% | ETA 01:12

[6690/7133] ✓ VRSN: 316 рядків |  93.79% | ETA 01:10

[6700/7133] ✓ VSEC: 149 рядків |  93.93% | ETA 01:09

   • RAM · 🧠 RAM: 374.9 MB

   ⏳ перед flush · 🧠 RAM: 374.9 MB

💾 batch 17659 → 12,507 рядків (всього 1,674,494 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17659.csv.gz

   ✅ після flush · 🧠 RAM: 375.5 MB

[6710/7133] ✓ VST: 692 рядків |  94.07% | ETA 01:07

[6720/7133] ✓ VTIX: 90 рядків |  94.21% | ETA 01:06

[6730/7133] ✓ VUZI: 311 рядків |  94.35% | ETA 01:04

[6740/7133] ✓ VXX: 526 рядків |  94.49% | ETA 01:02

[6750/7133] ✓ W: 386 рядків |  94.63% | ETA 01:01

   • RAM · 🧠 RAM: 376.4 MB

   ⏳ перед flush · 🧠 RAM: 376.4 MB

💾 batch 17660 → 15,410 рядків (всього 1,689,904 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17660.csv.gz

   ✅ після flush · 🧠 RAM: 377.7 MB

[6760/7133] ✓ WASH: 69 рядків |  94.77% | ETA 00:59

[6770/7133] ✓ WCC: 293 рядків |  94.91% | ETA 00:58

[6780/7133] ✓ WD: 250 рядків |  95.05% | ETA 00:56

[6790/7133] ✓ WEAT: 287 рядків |  95.19% | ETA 00:54

[6800/7133] ✓ WERN: 322 рядків |  95.33% | ETA 00:53

   • RAM · 🧠 RAM: 378.1 MB

   ⏳ перед flush · 🧠 RAM: 378.1 MB

💾 batch 17661 → 9,813 рядків (всього 1,699,717 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17661.csv.gz

   ✅ після flush · 🧠 RAM: 378.7 MB

[6810/7133] ✓ WFF: 408 рядків |  95.47% | ETA 00:51

[6820/7133] ✓ WHK: 153 рядків |  95.61% | ETA 00:50

[6830/7133] ✓ WKEY: 21 рядків |  95.75% | ETA 00:48

[6840/7133] ✓ WLDS: 61 рядків |  95.89% | ETA 00:46

[6850/7133] ✓ WOR: 206 рядків |  96.03% | ETA 00:45

   • RAM · 🧠 RAM: 379.9 MB

   ⏳ перед flush · 🧠 RAM: 379.9 MB

💾 batch 17662 → 12,174 рядків (всього 1,711,891 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17662.csv.gz

   ✅ після flush · 🧠 RAM: 380.5 MB

[6860/7133] ✓ WRB: 382 рядків |  96.17% | ETA 00:43

[6870/7133] – WSR: empty |  96.31% | ETA 00:42

[6880/7133] ✓ WTFC: 180 рядків |  96.45% | ETA 00:40

[6890/7133] ✓ WULX: 265 рядків |  96.59% | ETA 00:38

[6900/7133] ✓ WXM: 13 рядків |  96.73% | ETA 00:37

   • RAM · 🧠 RAM: 381.8 MB

   ⏳ перед flush · 🧠 RAM: 381.8 MB

💾 batch 17663 → 13,663 рядків (всього 1,725,554 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17663.csv.gz

   ✅ після flush · 🧠 RAM: 382.5 MB

[6910/7133] ✓ WYY: 312 рядків |  96.87% | ETA 00:35

[6920/7133] ✓ XCH: 7 рядків |  97.01% | ETA 00:34

[6930/7133] ✓ XCUR: 6 рядків |  97.15% | ETA 00:32

[6940/7133] ✓ XGN: 189 рядків |  97.29% | ETA 00:30

[6950/7133] ✓ XLSI: 12 рядків |  97.43% | ETA 00:29

   • RAM · 🧠 RAM: 382.5 MB

   ⏳ перед flush · 🧠 RAM: 382.5 MB

💾 batch 17664 → 10,238 рядків (всього 1,735,792 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17664.csv.gz

   ✅ після flush · 🧠 RAM: 383.0 MB

[6960/7133] ✓ XLU: 507 рядків |  97.57% | ETA 00:27

[6970/7133] ✓ XNTK: 153 рядків |  97.71% | ETA 00:26

[6980/7133] ✓ XPAY: 44 рядків |  97.86% | ETA 00:24

[6990/7133] ✓ XPH: 100 рядків |  98.00% | ETA 00:22

[7000/7133] ✓ XRPT: 507 рядків |  98.14% | ETA 00:21

   • RAM · 🧠 RAM: 383.7 MB

   ⏳ перед flush · 🧠 RAM: 383.7 MB

💾 batch 17665 → 11,188 рядків (всього 1,746,980 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17665.csv.gz

   ✅ після flush · 🧠 RAM: 384.2 MB

[7010/7133] ✓ XSPI: 118 рядків |  98.28% | ETA 00:19

[7020/7133] ✓ XTIA: 352 рядків |  98.42% | ETA 00:18

[7030/7133] ✓ XYL: 387 рядків |  98.56% | ETA 00:16

[7040/7133] – YBMN: empty |  98.70% | ETA 00:14

[7050/7133] ✓ YETI: 324 рядків |  98.84% | ETA 00:13

   • RAM · 🧠 RAM: 383.5 MB

   ⏳ перед flush · 🧠 RAM: 383.5 MB

💾 batch 17666 → 8,197 рядків (всього 1,755,177 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17666.csv.gz

   ✅ після flush · 🧠 RAM: 384.1 MB

[7060/7133] ✓ YMAX: 278 рядків |  98.98% | ETA 00:11

[7070/7133] ✓ YRD: 27 рядків |  99.12% | ETA 00:10

[7080/7133] ✓ YYAI: 212 рядків |  99.26% | ETA 00:08

[7090/7133] ✓ ZDAI: 14 рядків |  99.40% | ETA 00:06

[7100/7133] ✓ ZETA: 504 рядків |  99.54% | ETA 00:05

   • RAM · 🧠 RAM: 379.7 MB

   ⏳ перед flush · 🧠 RAM: 379.7 MB

💾 batch 17667 → 10,223 рядків (всього 1,765,400 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17667.csv.gz

   ✅ після flush · 🧠 RAM: 378.5 MB

[7110/7133] ✓ ZJYL: 27 рядків |  99.68% | ETA 00:03

[7120/7133] ✓ ZSTK: 33 рядків |  99.82% | ETA 00:02

[7130/7133] ✓ ZURA: 367 рядків |  99.96% | ETA 00:00

[7133/7133] ✓ ZYME: 302 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 373.1 MB

💾 batch 17668 → 8,102 рядків (всього 1,773,502 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_17668.csv.gz

   ✅ після flush · 🧠 RAM: 371.0 MB

   🔚 фінал · 🧠 RAM: 371.0 MB

🏁 Готово. Нових рядків: 1,773,502 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 19:01

In [18]:
# ================== FAST LOCAL POST-PROCESSING (no API calls) ==================
# Читання батчів робить pyarrow (нативний багатопотоковий CSV-парсер) замість
# pandas.read_csv, а premarket-фільтр і денні open/close рахуються за ОДИН прохід
# по gz-файлах замість двох.
import os, gc, glob, time, threading
from typing import Optional, List, Tuple

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.csv as pacsv
import pyarrow.compute as pc
import pyarrow.dataset as pads
from concurrent.futures import ThreadPoolExecutor

_INTRADAY_COLS = ["ticker", "dt", "o", "h", "l", "c", "v"]

# Парсимо у float64, щоб денні open/close збігалися з попередньою (pandas) реалізацією
# біт у біт; premarket-рядки перед записом кастимо назад у float32 — стара схема на диску.
_INTRADAY_TYPES = {
    "ticker": pa.string(), "dt": pa.string(),
    "o": pa.float64(), "h": pa.float64(), "l": pa.float64(),
    "c": pa.float64(), "v": pa.float64(),
}
_PREMARKET_SCHEMA = pa.schema([
    ("ticker", pa.string()), ("dt", pa.string()),
    ("o", pa.float32()), ("h", pa.float32()), ("l", pa.float32()),
    ("c", pa.float32()), ("v", pa.float32()),
])


# ---------- спільні хелпери для мерджів по тікеру (використовують клітинки 28/40/44) ----------
def _ticker_codes(s: pd.Series):
    """Факторизує колонку тікерів і нормалізує (strip+upper) ЛИШЕ унікальні значення.

    Повертає (codes, categories); codes[i] == -1 означає null. Сенс у тому, щоб
    strip/upper і словниковий пошук виконувались над ~10^3 унікальними тікерами,
    а не над ~10^6 рядками батча.
    """
    cat = s.astype("category")
    cats = pd.Index(cat.cat.categories.astype(str)).str.strip().str.upper()
    return cat.cat.codes.to_numpy(), cats


def _expand(values: np.ndarray, codes: np.ndarray, fill):
    """Розгортає масив «на категорію» назад «на рядок»; де codes == -1 ставить fill."""
    out = np.empty(codes.shape, dtype=values.dtype if values.dtype != object else object)
    valid = codes >= 0
    out[valid] = values[codes[valid]]
    if (~valid).any():
        out[~valid] = fill
    return out


def _map_by_ticker(codes: np.ndarray, cats: pd.Index, mapping: dict, numeric: bool):
    vals = cats.map(mapping)
    if numeric:
        vals = pd.to_numeric(pd.Series(vals), errors="coerce").to_numpy(dtype="float64")
        return _expand(vals, codes, np.nan)
    vals = np.asarray(pd.Series(vals).astype(object).to_numpy(), dtype=object)
    return _expand(vals, codes, None)


# ---------- читання intraday-батчів ----------
def _open_intraday_csv(path: str, block_size: int):
    return pacsv.open_csv(
        path,
        read_options=pacsv.ReadOptions(use_threads=True, block_size=block_size),
        convert_options=pacsv.ConvertOptions(
            include_columns=_INTRADAY_COLS, column_types=_INTRADAY_TYPES
        ),
    )


def _time_date_mask(dt_arr, start_time, end_time, date_min, date_max):
    t = pc.utf8_slice_codeunits(dt_arr, 11, 19)
    mask = pc.and_(pc.greater_equal(t, start_time), pc.less_equal(t, end_time))
    if date_min is not None or date_max is not None:
        d = pc.utf8_slice_codeunits(dt_arr, 0, 10)
        if date_min is not None:
            mask = pc.and_(mask, pc.greater_equal(d, date_min))
        if date_max is not None:
            mask = pc.and_(mask, pc.less_equal(d, date_max))
    return mask


def _oc_from_table(tbl: pa.Table) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Перший open у вікні 09:30–09:35 і останній close у 15:55–15:59 на (ticker, date)."""
    OPEN_FROM, OPEN_TO = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    hhmm = pc.utf8_slice_codeunits(tbl.column("dt"), 11, 16)
    m_o = pc.and_(pc.and_(pc.greater_equal(hhmm, OPEN_FROM), pc.less_equal(hhmm, OPEN_TO)),
                  pc.is_valid(tbl.column("o")))
    m_c = pc.and_(pc.and_(pc.greater_equal(hhmm, CLOSE_FROM), pc.less_equal(hhmm, CLOSE_TO)),
                  pc.is_valid(tbl.column("c")))

    def _reduce(mask, val_col, keep):
        sub = tbl.select(["ticker", "dt", val_col]).filter(mask)
        if sub.num_rows == 0:
            return pd.DataFrame(columns=["ticker", "date", "dt", val_col])
        d = sub.to_pandas()
        d["date"] = d["dt"].str.slice(0, 10)
        d = d.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep=keep)
        return d[["ticker", "date", "dt", val_col]]

    return _reduce(m_o, "o", "first"), _reduce(m_c, "c", "last")


def _finalize_oc(open_parts: List[pd.DataFrame], close_parts: List[pd.DataFrame]) -> pd.DataFrame:
    opens = (pd.concat(open_parts, ignore_index=True) if open_parts
             else pd.DataFrame(columns=["ticker", "date", "dt", "o"]))
    closes = (pd.concat(close_parts, ignore_index=True) if close_parts
              else pd.DataFrame(columns=["ticker", "date", "dt", "c"]))
    if len(opens):
        opens = opens.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="first")
    if len(closes):
        closes = closes.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="last")
    opens = opens[["ticker", "date", "o"]].rename(columns={"o": "open"})
    closes = closes[["ticker", "date", "c"]].rename(columns={"c": "close"})

    out = (opens.merge(closes, on=["ticker", "date"], how="outer")
                .sort_values(["ticker", "date"], kind="stable").reset_index(drop=True))
    out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)
    return out


def collect_premarket_and_oc(
    folder: str,
    out_path: str,
    oc_out_path: Optional[str] = None,
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    build_oc: bool = True,
    max_workers: int = 4,
    block_size: int = 64 << 20,
    compression: str = "snappy",
    sort_chunk: bool = True,
    verbose: bool = True,
):
    """ОДИН прохід по {folder}/{pattern}: пише відфільтровані рядки у out_path і
    (опційно) денні open/close у oc_out_path.

    Замінює пару collect_premarket_by_day_stream + build_oc_from_intraday_folder,
    які раніше читали й розтискали ті самі gz-файли двічі.

    Порядок рядків МІЖ файлами недетермінований (файли читаються паралельно).
    Це безпечно: усі наступні кроки — мерджі по ключах, а фінальний файл
    фізично сортується у клітинці 47. Для точного старого порядку — max_workers=1.
    """
    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    if os.path.exists(out_path):
        os.remove(out_path)

    t0 = time.time()
    lock = threading.Lock()
    state = {"writer": None, "in": 0, "out": 0, "files": 0}
    open_parts: List[pd.DataFrame] = []
    close_parts: List[pd.DataFrame] = []

    def _handle(path: str):
        reader = _open_intraday_csv(path, block_size)
        loc_open, loc_close = [], []
        n_in = n_out = 0
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            tbl = pa.Table.from_batches([rb])
            n_in += tbl.num_rows

            if build_oc:
                o_df, c_df = _oc_from_table(tbl)
                if len(o_df):
                    loc_open.append(o_df)
                if len(c_df):
                    loc_close.append(c_df)

            cut = tbl.filter(_time_date_mask(tbl.column("dt"), start_time, end_time,
                                             date_min, date_max))
            if cut.num_rows:
                cut = cut.cast(_PREMARKET_SCHEMA)
                if sort_chunk:
                    cut = cut.sort_by([("ticker", "ascending"), ("dt", "ascending")])
                n_out += cut.num_rows
                with lock:
                    if state["writer"] is None:
                        state["writer"] = pq.ParquetWriter(out_path, cut.schema,
                                                           compression=compression)
                    state["writer"].write_table(cut)

        with lock:
            state["in"] += n_in
            state["out"] += n_out
            state["files"] += 1
            open_parts.extend(loc_open)
            close_parts.extend(loc_close)
            if verbose:
                print(f"  [{state['files']}/{len(files)}] {os.path.basename(path)}  "
                      f"in={state['in']:,} out={state['out']:,} "
                      f"elapsed={time.time()-t0:,.1f}s", flush=True)

    rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]" if (date_min or date_max) else ""
    if verbose:
        print(f"▶️ START: {folder}/{pattern} → {out_path}  files={len(files)} "
              f"workers={max_workers}{rng_str}", flush=True)
    try:
        if max_workers and max_workers > 1:
            with ThreadPoolExecutor(max_workers=max_workers) as ex:
                list(ex.map(_handle, files))
        else:
            for p in files:
                _handle(p)
    finally:
        if state["writer"] is not None:
            state["writer"].close()

    df_oc = None
    if build_oc:
        df_oc = _finalize_oc(open_parts, close_parts)
        if oc_out_path:
            os.makedirs(os.path.dirname(oc_out_path) or ".", exist_ok=True)
            df_oc.to_parquet(oc_out_path, index=False)

    if verbose:
        print(f"✅ DONE  in={state['in']:,} → out={state['out']:,}  to {out_path}  "
              f"in {time.time()-t0:,.1f}s", flush=True)
    return out_path, df_oc


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,
    date_max: Optional[str] = None,
    aggregate: bool = False,
    chunksize: int = 200_000,          # лишено для сумісності виклику; pyarrow керує блоками сам
    compression: str = "snappy",
    log_every: int = 5,                # лишено для сумісності виклику
    sort_chunk: bool = True,
    max_workers: int = 4,
    verbose: bool = True,
):
    """Тонка обгортка над collect_premarket_and_oc (build_oc=False) — щоб старі
    виклики працювали без змін."""
    if aggregate:
        raise NotImplementedError("aggregate=True у цьому пайплайні не використовується")
    path, _ = collect_premarket_and_oc(
        folder, out_path, oc_out_path=None, pattern=pattern,
        start_time=start_time, end_time=end_time,
        date_min=date_min, date_max=date_max, build_oc=False,
        max_workers=max_workers, compression=compression,
        sort_chunk=sort_chunk, verbose=verbose,
    )
    return path

In [19]:
# Один прохід по gz-батчах: одразу і premarket-рядки, і денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,
    date_max=end_date_str,
    build_oc=True,
    max_workers=4,
)
print(df_oc.head())

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  files=17668 workers=4  date=[2026-06-26..2026-09-26]

  [1/17668] intraday_0003.csv.gz  in=727,885 out=0 elapsed=0.7s

  [2/17668] intraday_0004.csv.gz  in=1,470,913 out=0 elapsed=0.7s

  [3/17668] intraday_0002.csv.gz  in=2,357,625 out=0 elapsed=0.8s

  [4/17668] intraday_0001.csv.gz  in=3,333,452 out=0 elapsed=0.8s

  [5/17668] intraday_0007.csv.gz  in=4,094,033 out=0 elapsed=1.4s

  [6/17668] intraday_0005.csv.gz  in=4,968,024 out=0 elapsed=1.4s

  [7/17668] intraday_0006.csv.gz  in=5,923,107 out=0 elapsed=1.6s

  [8/17668] intraday_0008.csv.gz  in=6,732,671 out=0 elapsed=1.6s

  [9/17668] intraday_0010.csv.gz  in=7,670,259 out=0 elapsed=2.1s

  [10/17668] intraday_0009.csv.gz  in=8,610,085 out=0 elapsed=2.2s

  [11/17668] intraday_0011.csv.gz  in=9,348,724 out=0 elapsed=2.2s

  [12/17668] intraday_0012.csv.gz  in=10,202,410 out=0 elapsed=2.2s

  [13/17668] intraday_0015.csv.gz  in=10,806,484 out=0 elapsed=2.6s

  [14/17668] intraday_0014.csv.gz  in=11,471,803 out=0 elapsed=2.7s

  [15/17668] intraday_0013.csv.gz  in=12,333,647 out=0 elapsed=2.7s

  [16/17668] intraday_0016.csv.gz  in=13,369,434 out=0 elapsed=3.0s

  [17/17668] intraday_0018.csv.gz  in=14,058,532 out=0 elapsed=3.1s

  [18/17668] intraday_0019.csv.gz  in=14,795,001 out=0 elapsed=3.3s

  [19/17668] intraday_0017.csv.gz  in=15,723,943 out=0 elapsed=3.3s

  [20/17668] intraday_0020.csv.gz  in=16,555,781 out=0 elapsed=3.5s

  [21/17668] intraday_0021.csv.gz  in=17,382,589 out=0 elapsed=3.9s

  [22/17668] intraday_0022.csv.gz  in=18,114,555 out=0 elapsed=3.9s

  [23/17668] intraday_0023.csv.gz  in=18,895,557 out=0 elapsed=3.9s

  [24/17668] intraday_0024.csv.gz  in=19,686,597 out=0 elapsed=4.1s

  [25/17668] intraday_0025.csv.gz  in=20,416,242 out=0 elapsed=4.4s

  [26/17668] intraday_0027.csv.gz  in=21,080,210 out=0 elapsed=4.4s

  [27/17668] intraday_0026.csv.gz  in=21,935,669 out=0 elapsed=4.5s

  [28/17668] intraday_0028.csv.gz  in=22,943,087 out=0 elapsed=4.8s

  [29/17668] intraday_0031.csv.gz  in=23,677,097 out=0 elapsed=5.0s

  [30/17668] intraday_0029.csv.gz  in=24,623,614 out=0 elapsed=5.1s

  [31/17668] intraday_0030.csv.gz  in=25,543,444 out=0 elapsed=5.1s

  [32/17668] intraday_0032.csv.gz  in=26,359,346 out=0 elapsed=5.3s

  [33/17668] intraday_0034.csv.gz  in=27,046,628 out=0 elapsed=5.6s

  [34/17668] intraday_0033.csv.gz  in=27,922,589 out=0 elapsed=5.7s

  [35/17668] intraday_0035.csv.gz  in=28,741,745 out=0 elapsed=5.7s

  [36/17668] intraday_0036.csv.gz  in=29,561,610 out=0 elapsed=6.0s

  [37/17668] intraday_0037.csv.gz  in=30,234,721 out=0 elapsed=6.1s

  [38/17668] intraday_0038.csv.gz  in=30,924,778 out=0 elapsed=6.2s

  [39/17668] intraday_0039.csv.gz  in=31,684,289 out=0 elapsed=6.3s

  [40/17668] intraday_0040.csv.gz  in=32,407,718 out=0 elapsed=6.5s

  [41/17668] intraday_0041.csv.gz  in=33,301,794 out=0 elapsed=6.7s

  [42/17668] intraday_0043.csv.gz  in=34,013,644 out=0 elapsed=6.8s

  [43/17668] intraday_0042.csv.gz  in=34,960,739 out=0 elapsed=6.8s

  [44/17668] intraday_0044.csv.gz  in=35,766,274 out=0 elapsed=7.0s

  [45/17668] intraday_0045.csv.gz  in=36,568,713 out=0 elapsed=7.2s

  [46/17668] intraday_0046.csv.gz  in=37,383,804 out=0 elapsed=7.3s

  [47/17668] intraday_0047.csv.gz  in=38,250,311 out=0 elapsed=7.4s

  [48/17668] intraday_0048.csv.gz  in=38,906,436 out=0 elapsed=7.5s

  [49/17668] intraday_0049.csv.gz  in=39,851,960 out=0 elapsed=7.9s

  [50/17668] intraday_0050.csv.gz  in=40,684,592 out=0 elapsed=7.9s

  [51/17668] intraday_0051.csv.gz  in=41,414,383 out=0 elapsed=8.0s

  [52/17668] intraday_0052.csv.gz  in=42,279,351 out=0 elapsed=8.1s

  [53/17668] intraday_0053.csv.gz  in=42,998,896 out=0 elapsed=8.4s

  [54/17668] intraday_0054.csv.gz  in=43,729,514 out=0 elapsed=8.5s

  [55/17668] intraday_0055.csv.gz  in=44,542,383 out=0 elapsed=8.5s

  [56/17668] intraday_0056.csv.gz  in=45,360,329 out=0 elapsed=8.7s

  [57/17668] intraday_0057.csv.gz  in=46,118,655 out=0 elapsed=8.9s

  [58/17668] intraday_0058.csv.gz  in=46,830,377 out=0 elapsed=9.0s

  [59/17668] intraday_0059.csv.gz  in=47,587,522 out=0 elapsed=9.1s

  [60/17668] intraday_0060.csv.gz  in=48,264,439 out=0 elapsed=9.1s

  [61/17668] intraday_0062.csv.gz  in=49,011,023 out=0 elapsed=9.6s

  [62/17668] intraday_0061.csv.gz  in=50,022,323 out=0 elapsed=9.6s

  [63/17668] intraday_0064.csv.gz  in=50,907,540 out=0 elapsed=9.8s

  [64/17668] intraday_0063.csv.gz  in=51,861,073 out=0 elapsed=9.8s

  [65/17668] intraday_0066.csv.gz  in=52,548,161 out=0 elapsed=10.1s

  [66/17668] intraday_0065.csv.gz  in=53,344,110 out=0 elapsed=10.2s

  [67/17668] intraday_0067.csv.gz  in=54,114,222 out=0 elapsed=10.3s

  [68/17668] intraday_0068.csv.gz  in=54,938,820 out=0 elapsed=10.4s

  [69/17668] intraday_0070.csv.gz  in=55,597,571 out=0 elapsed=10.6s

  [70/17668] intraday_0069.csv.gz  in=56,497,048 out=0 elapsed=10.7s

  [71/17668] intraday_0071.csv.gz  in=57,135,058 out=0 elapsed=10.8s

  [72/17668] intraday_0072.csv.gz  in=57,879,667 out=0 elapsed=11.0s

  [73/17668] intraday_0073.csv.gz  in=58,674,810 out=0 elapsed=11.2s

  [74/17668] intraday_0074.csv.gz  in=59,409,405 out=0 elapsed=11.3s

  [75/17668] intraday_0075.csv.gz  in=60,167,330 out=0 elapsed=11.4s

  [76/17668] intraday_0076.csv.gz  in=60,866,670 out=0 elapsed=11.4s

  [77/17668] intraday_0077.csv.gz  in=61,676,095 out=0 elapsed=11.8s

  [78/17668] intraday_0080.csv.gz  in=62,376,615 out=0 elapsed=11.9s

  [79/17668] intraday_0079.csv.gz  in=63,295,220 out=0 elapsed=12.0s

  [80/17668] intraday_0078.csv.gz  in=64,355,814 out=0 elapsed=12.0s

  [81/17668] intraday_0081.csv.gz  in=65,173,353 out=0 elapsed=12.4s

  [82/17668] intraday_0082.csv.gz  in=65,962,271 out=0 elapsed=12.5s

  [83/17668] intraday_0083.csv.gz  in=66,748,390 out=0 elapsed=12.7s

  [84/17668] intraday_0084.csv.gz  in=67,918,886 out=0 elapsed=12.9s

  [85/17668] intraday_0085.csv.gz  in=68,693,048 out=0 elapsed=13.0s

  [86/17668] intraday_0086.csv.gz  in=69,620,846 out=0 elapsed=13.2s

  [87/17668] intraday_0087.csv.gz  in=70,564,187 out=0 elapsed=13.3s

  [88/17668] intraday_0088.csv.gz  in=71,397,243 out=0 elapsed=13.5s

  [89/17668] intraday_0089.csv.gz  in=72,281,904 out=0 elapsed=13.5s

  [90/17668] intraday_0090.csv.gz  in=73,069,473 out=0 elapsed=13.7s

  [91/17668] intraday_0091.csv.gz  in=73,999,201 out=0 elapsed=14.0s

  [92/17668] intraday_0092.csv.gz  in=74,831,839 out=0 elapsed=14.0s

  [93/17668] intraday_0093.csv.gz  in=75,647,498 out=0 elapsed=14.1s

  [94/17668] intraday_0094.csv.gz  in=76,528,738 out=0 elapsed=14.3s

  [95/17668] intraday_0095.csv.gz  in=77,378,774 out=0 elapsed=14.6s

  [96/17668] intraday_0096.csv.gz  in=78,260,543 out=0 elapsed=14.6s

  [97/17668] intraday_0097.csv.gz  in=79,032,923 out=0 elapsed=14.7s

  [98/17668] intraday_0098.csv.gz  in=79,802,827 out=0 elapsed=14.8s

  [99/17668] intraday_0100.csv.gz  in=80,600,542 out=0 elapsed=15.2s

  [100/17668] intraday_0099.csv.gz  in=81,661,660 out=0 elapsed=15.3s

  [101/17668] intraday_0101.csv.gz  in=82,593,388 out=0 elapsed=15.3s

  [102/17668] intraday_0102.csv.gz  in=83,527,121 out=0 elapsed=15.4s

  [103/17668] intraday_0103.csv.gz  in=84,317,945 out=0 elapsed=15.8s

  [104/17668] intraday_0104.csv.gz  in=85,159,844 out=0 elapsed=15.9s

  [105/17668] intraday_0106.csv.gz  in=85,949,588 out=0 elapsed=16.0s

  [106/17668] intraday_0105.csv.gz  in=86,821,848 out=0 elapsed=16.0s

  [107/17668] intraday_0107.csv.gz  in=87,885,246 out=0 elapsed=16.5s

  [108/17668] intraday_0108.csv.gz  in=88,679,847 out=0 elapsed=16.5s

  [109/17668] intraday_0109.csv.gz  in=89,619,231 out=0 elapsed=16.7s

  [110/17668] intraday_0110.csv.gz  in=90,640,909 out=0 elapsed=16.8s

  [111/17668] intraday_0111.csv.gz  in=91,427,941 out=0 elapsed=17.1s

  [112/17668] intraday_0112.csv.gz  in=92,259,949 out=0 elapsed=17.2s

  [113/17668] intraday_0113.csv.gz  in=93,022,660 out=0 elapsed=17.3s

  [114/17668] intraday_0114.csv.gz  in=93,859,984 out=0 elapsed=17.4s

  [115/17668] intraday_0115.csv.gz  in=94,616,153 out=0 elapsed=17.6s

  [116/17668] intraday_0117.csv.gz  in=95,401,469 out=0 elapsed=17.9s

  [117/17668] intraday_0116.csv.gz  in=96,350,237 out=0 elapsed=17.9s

  [118/17668] intraday_0119.csv.gz  in=97,075,034 out=0 elapsed=18.1s

  [119/17668] intraday_0118.csv.gz  in=98,245,742 out=0 elapsed=18.3s

  [120/17668] intraday_0120.csv.gz  in=99,105,343 out=0 elapsed=18.5s

  [121/17668] intraday_0121.csv.gz  in=100,150,376 out=0 elapsed=18.6s

  [122/17668] intraday_0122.csv.gz  in=100,938,876 out=0 elapsed=18.6s

  [123/17668] intraday_0123.csv.gz  in=101,790,604 out=0 elapsed=18.8s

  [124/17668] intraday_0124.csv.gz  in=102,767,055 out=0 elapsed=19.2s

  [125/17668] intraday_0125.csv.gz  in=103,648,833 out=0 elapsed=19.2s

  [126/17668] intraday_0126.csv.gz  in=104,596,744 out=0 elapsed=19.3s

  [127/17668] intraday_0127.csv.gz  in=105,314,012 out=0 elapsed=19.4s

  [128/17668] intraday_0128.csv.gz  in=106,066,285 out=0 elapsed=19.7s

  [129/17668] intraday_0129.csv.gz  in=106,926,182 out=0 elapsed=19.9s

  [130/17668] intraday_0131.csv.gz  in=107,680,974 out=0 elapsed=19.9s

  [131/17668] intraday_0134.csv.gz  in=107,729,125 out=0 elapsed=19.9s

  [132/17668] intraday_0130.csv.gz  in=108,551,408 out=0 elapsed=20.0s

  [133/17668] intraday_0135.csv.gz  in=108,567,766 out=0 elapsed=20.0s

  [134/17668] intraday_0136.csv.gz  in=108,586,456 out=0 elapsed=20.0s

  [135/17668] intraday_0137.csv.gz  in=108,598,507 out=0 elapsed=20.0s

  [136/17668] intraday_0138.csv.gz  in=108,611,037 out=0 elapsed=20.0s

  [137/17668] intraday_0139.csv.gz  in=108,624,721 out=0 elapsed=20.0s

  [138/17668] intraday_0140.csv.gz  in=108,639,628 out=0 elapsed=20.0s

  [139/17668] intraday_0141.csv.gz  in=108,652,214 out=0 elapsed=20.0s

  [140/17668] intraday_0142.csv.gz  in=108,666,192 out=0 elapsed=20.0s

  [141/17668] intraday_0143.csv.gz  in=108,681,523 out=0 elapsed=20.1s

  [142/17668] intraday_0145.csv.gz  in=108,696,729 out=0 elapsed=20.1s

  [143/17668] intraday_0144.csv.gz  in=108,729,449 out=0 elapsed=20.1s

  [144/17668] intraday_0146.csv.gz  in=108,761,230 out=0 elapsed=20.1s

  [145/17668] intraday_0147.csv.gz  in=108,776,203 out=0 elapsed=20.1s

  [146/17668] intraday_0148.csv.gz  in=108,787,503 out=0 elapsed=20.2s

  [147/17668] intraday_0149.csv.gz  in=108,798,800 out=0 elapsed=20.2s

  [148/17668] intraday_0132.csv.gz  in=109,461,076 out=0 elapsed=20.2s

  [149/17668] intraday_0150.csv.gz  in=109,477,550 out=0 elapsed=20.2s

  [150/17668] intraday_0151.csv.gz  in=109,493,543 out=0 elapsed=20.2s

  [151/17668] intraday_0152.csv.gz  in=109,505,698 out=0 elapsed=20.2s

  [152/17668] intraday_0153.csv.gz  in=109,517,425 out=0 elapsed=20.2s

  [153/17668] intraday_0154.csv.gz  in=109,532,249 out=0 elapsed=20.3s

  [154/17668] intraday_0156.csv.gz  in=109,545,610 out=0 elapsed=20.3s

  [155/17668] intraday_0155.csv.gz  in=109,561,190 out=0 elapsed=20.3s

  [156/17668] intraday_0157.csv.gz  in=109,573,389 out=0 elapsed=20.3s

  [157/17668] intraday_0159.csv.gz  in=109,585,001 out=0 elapsed=20.3s

  [158/17668] intraday_0158.csv.gz  in=109,614,934 out=0 elapsed=20.3s

  [159/17668] intraday_0160.csv.gz  in=109,627,373 out=0 elapsed=20.3s

  [160/17668] intraday_0161.csv.gz  in=109,639,687 out=0 elapsed=20.3s

  [161/17668] intraday_0162.csv.gz  in=109,656,973 out=0 elapsed=20.3s

  [162/17668] intraday_0165.csv.gz  in=109,669,596 out=0 elapsed=20.4s

  [163/17668] intraday_0163.csv.gz  in=109,686,802 out=0 elapsed=20.4s

  [164/17668] intraday_0164.csv.gz  in=109,701,993 out=0 elapsed=20.4s

  [165/17668] intraday_0168.csv.gz  in=109,712,850 out=0 elapsed=20.4s

  [166/17668] intraday_0166.csv.gz  in=109,726,460 out=0 elapsed=20.4s

  [167/17668] intraday_0167.csv.gz  in=109,747,301 out=0 elapsed=20.4s

  [168/17668] intraday_0169.csv.gz  in=109,761,632 out=0 elapsed=20.4s

  [169/17668] intraday_0171.csv.gz  in=109,773,053 out=0 elapsed=20.4s

  [170/17668] intraday_0170.csv.gz  in=109,788,593 out=0 elapsed=20.5s

  [171/17668] intraday_0133.csv.gz  in=110,569,494 out=0 elapsed=20.5s

  [172/17668] intraday_0172.csv.gz  in=110,580,228 out=0 elapsed=20.5s

  [173/17668] intraday_0173.csv.gz  in=110,593,066 out=0 elapsed=20.5s

  [174/17668] intraday_0174.csv.gz  in=110,605,870 out=0 elapsed=20.5s

  [175/17668] intraday_0175.csv.gz  in=110,620,244 out=0 elapsed=20.5s

  [176/17668] intraday_0176.csv.gz  in=110,637,126 out=0 elapsed=20.5s

  [177/17668] intraday_0177.csv.gz  in=110,652,077 out=0 elapsed=20.5s

  [178/17668] intraday_0178.csv.gz  in=110,666,020 out=0 elapsed=20.5s

  [179/17668] intraday_0179.csv.gz  in=110,679,724 out=0 elapsed=20.5s

  [180/17668] intraday_0180.csv.gz  in=110,693,457 out=0 elapsed=20.6s

  [181/17668] intraday_0182.csv.gz  in=110,705,949 out=0 elapsed=20.6s

  [182/17668] intraday_0183.csv.gz  in=110,723,493 out=0 elapsed=20.6s

  [183/17668] intraday_0181.csv.gz  in=110,754,307 out=0 elapsed=20.6s

  [184/17668] intraday_0184.csv.gz  in=110,770,536 out=0 elapsed=20.6s

  [185/17668] intraday_0185.csv.gz  in=110,784,589 out=0 elapsed=20.6s

  [186/17668] intraday_0187.csv.gz  in=110,798,315 out=0 elapsed=20.6s

  [187/17668] intraday_0186.csv.gz  in=110,812,773 out=0 elapsed=20.6s

  [188/17668] intraday_0189.csv.gz  in=110,825,918 out=0 elapsed=20.6s

  [189/17668] intraday_0188.csv.gz  in=110,849,387 out=0 elapsed=20.6s

  [190/17668] intraday_0191.csv.gz  in=110,863,852 out=0 elapsed=20.6s

  [191/17668] intraday_0190.csv.gz  in=110,877,560 out=0 elapsed=20.6s

  [192/17668] intraday_0192.csv.gz  in=110,889,613 out=0 elapsed=20.7s

  [193/17668] intraday_0194.csv.gz  in=110,899,748 out=0 elapsed=20.7s

  [194/17668] intraday_0193.csv.gz  in=110,911,659 out=0 elapsed=20.7s

  [195/17668] intraday_0195.csv.gz  in=110,926,310 out=0 elapsed=20.7s

  [196/17668] intraday_0196.csv.gz  in=110,938,931 out=0 elapsed=20.7s

  [197/17668] intraday_0197.csv.gz  in=110,953,423 out=0 elapsed=20.7s

  [198/17668] intraday_0198.csv.gz  in=110,968,845 out=0 elapsed=20.7s

  [199/17668] intraday_0200.csv.gz  in=110,980,268 out=0 elapsed=20.7s

  [200/17668] intraday_0199.csv.gz  in=110,995,048 out=0 elapsed=20.7s

  [201/17668] intraday_0202.csv.gz  in=111,009,575 out=0 elapsed=20.8s

  [202/17668] intraday_0201.csv.gz  in=111,023,231 out=0 elapsed=20.8s

  [203/17668] intraday_0203.csv.gz  in=111,036,171 out=0 elapsed=20.8s

  [204/17668] intraday_0204.csv.gz  in=111,047,240 out=0 elapsed=20.8s

  [205/17668] intraday_0205.csv.gz  in=111,057,791 out=0 elapsed=20.8s

  [206/17668] intraday_0208.csv.gz  in=111,069,941 out=0 elapsed=20.8s

  [207/17668] intraday_0207.csv.gz  in=111,083,537 out=0 elapsed=20.8s

  [208/17668] intraday_0206.csv.gz  in=111,096,777 out=0 elapsed=20.8s

  [209/17668] intraday_0209.csv.gz  in=111,109,213 out=0 elapsed=20.8s

  [210/17668] intraday_0210.csv.gz  in=111,120,563 out=0 elapsed=20.8s

  [211/17668] intraday_0211.csv.gz  in=111,136,024 out=0 elapsed=20.8s

  [212/17668] intraday_0212.csv.gz  in=111,156,081 out=0 elapsed=20.8s

  [213/17668] intraday_0213.csv.gz  in=111,170,551 out=0 elapsed=20.8s

  [214/17668] intraday_0214.csv.gz  in=111,183,384 out=0 elapsed=20.9s

  [215/17668] intraday_0215.csv.gz  in=111,197,300 out=0 elapsed=20.9s

  [216/17668] intraday_0216.csv.gz  in=111,211,568 out=0 elapsed=20.9s

  [217/17668] intraday_0217.csv.gz  in=111,225,093 out=0 elapsed=20.9s

  [218/17668] intraday_0218.csv.gz  in=111,244,102 out=0 elapsed=20.9s

  [219/17668] intraday_0219.csv.gz  in=111,256,130 out=0 elapsed=20.9s

  [220/17668] intraday_0221.csv.gz  in=111,273,224 out=0 elapsed=20.9s

  [221/17668] intraday_0220.csv.gz  in=111,288,427 out=0 elapsed=20.9s

  [222/17668] intraday_0222.csv.gz  in=111,302,939 out=0 elapsed=20.9s

  [223/17668] intraday_0223.csv.gz  in=111,317,643 out=0 elapsed=21.0s

  [224/17668] intraday_0225.csv.gz  in=111,332,084 out=0 elapsed=21.0s

  [225/17668] intraday_0224.csv.gz  in=111,345,732 out=0 elapsed=21.0s

  [226/17668] intraday_0226.csv.gz  in=111,358,887 out=0 elapsed=21.0s

  [227/17668] intraday_0227.csv.gz  in=111,373,404 out=0 elapsed=21.0s

  [228/17668] intraday_0229.csv.gz  in=111,387,264 out=0 elapsed=21.0s

  [229/17668] intraday_0228.csv.gz  in=111,403,698 out=0 elapsed=21.0s

  [230/17668] intraday_0230.csv.gz  in=111,418,264 out=0 elapsed=21.0s

  [231/17668] intraday_0231.csv.gz  in=111,430,225 out=0 elapsed=21.0s

  [232/17668] intraday_0232.csv.gz  in=111,444,220 out=0 elapsed=21.1s

  [233/17668] intraday_0233.csv.gz  in=111,461,382 out=0 elapsed=21.1s

  [234/17668] intraday_0235.csv.gz  in=111,476,002 out=0 elapsed=21.1s

  [235/17668] intraday_0234.csv.gz  in=111,490,802 out=0 elapsed=21.1s

  [236/17668] intraday_0237.csv.gz  in=111,503,362 out=0 elapsed=21.1s

  [237/17668] intraday_0239.csv.gz  in=111,520,073 out=0 elapsed=21.1s

  [238/17668] intraday_0238.csv.gz  in=111,536,974 out=0 elapsed=21.1s

  [239/17668] intraday_0236.csv.gz  in=111,553,893 out=0 elapsed=21.1s

  [240/17668] intraday_0240.csv.gz  in=111,568,283 out=0 elapsed=21.1s

  [241/17668] intraday_0241.csv.gz  in=111,584,827 out=0 elapsed=21.1s

  [242/17668] intraday_0242.csv.gz  in=111,598,399 out=0 elapsed=21.2s

  [243/17668] intraday_0243.csv.gz  in=111,625,135 out=0 elapsed=21.2s

  [244/17668] intraday_0244.csv.gz  in=111,641,791 out=0 elapsed=21.2s

  [245/17668] intraday_0245.csv.gz  in=111,654,087 out=0 elapsed=21.2s

  [246/17668] intraday_0246.csv.gz  in=111,669,545 out=0 elapsed=21.2s

  [247/17668] intraday_0247.csv.gz  in=111,683,569 out=0 elapsed=21.2s

  [248/17668] intraday_0248.csv.gz  in=111,697,128 out=0 elapsed=21.2s

  [249/17668] intraday_0249.csv.gz  in=111,712,496 out=0 elapsed=21.2s

  [250/17668] intraday_0250.csv.gz  in=111,728,198 out=0 elapsed=21.2s

  [251/17668] intraday_0251.csv.gz  in=111,741,334 out=0 elapsed=21.2s

  [252/17668] intraday_0253.csv.gz  in=111,754,681 out=0 elapsed=21.3s

  [253/17668] intraday_0252.csv.gz  in=111,775,789 out=0 elapsed=21.3s

  [254/17668] intraday_0254.csv.gz  in=111,790,210 out=0 elapsed=21.3s

  [255/17668] intraday_0255.csv.gz  in=111,808,314 out=0 elapsed=21.3s

  [256/17668] intraday_0257.csv.gz  in=111,823,567 out=0 elapsed=21.3s

  [257/17668] intraday_0256.csv.gz  in=111,839,272 out=0 elapsed=21.3s

  [258/17668] intraday_0258.csv.gz  in=111,855,418 out=0 elapsed=21.3s

  [259/17668] intraday_0259.csv.gz  in=111,870,028 out=0 elapsed=21.3s

  [260/17668] intraday_0260.csv.gz  in=111,886,263 out=0 elapsed=21.3s

  [261/17668] intraday_0261.csv.gz  in=111,900,357 out=0 elapsed=21.3s

  [262/17668] intraday_0263.csv.gz  in=111,914,867 out=0 elapsed=21.3s

  [263/17668] intraday_0262.csv.gz  in=111,926,807 out=0 elapsed=21.3s

  [264/17668] intraday_0264.csv.gz  in=111,940,725 out=0 elapsed=21.3s

  [265/17668] intraday_0266.csv.gz  in=111,949,648 out=0 elapsed=21.3s

  [266/17668] intraday_0265.csv.gz  in=111,964,686 out=0 elapsed=21.4s

  [267/17668] intraday_0267.csv.gz  in=111,977,949 out=0 elapsed=21.4s

  [268/17668] intraday_0268.csv.gz  in=111,978,303 out=0 elapsed=21.4s

  [269/17668] intraday_0271.csv.gz  in=112,194,521 out=0 elapsed=21.6s

  [270/17668] intraday_0269.csv.gz  in=112,490,892 out=0 elapsed=21.6s

  [271/17668] intraday_0272.csv.gz  in=112,723,596 out=0 elapsed=21.6s

  [272/17668] intraday_0270.csv.gz  in=112,987,663 out=0 elapsed=21.6s

  [273/17668] intraday_0273.csv.gz  in=113,246,304 out=0 elapsed=21.8s

  [274/17668] intraday_0274.csv.gz  in=113,527,425 out=0 elapsed=21.8s

  [275/17668] intraday_0275.csv.gz  in=113,760,473 out=0 elapsed=21.8s

  [276/17668] intraday_0276.csv.gz  in=114,011,989 out=0 elapsed=21.9s

  [277/17668] intraday_0277.csv.gz  in=114,313,153 out=0 elapsed=22.0s

  [278/17668] intraday_0279.csv.gz  in=114,555,762 out=0 elapsed=22.0s

  [279/17668] intraday_0278.csv.gz  in=114,801,886 out=0 elapsed=22.1s

  [280/17668] intraday_0280.csv.gz  in=115,056,079 out=0 elapsed=22.1s

  [281/17668] intraday_0282.csv.gz  in=115,248,860 out=0 elapsed=22.2s

  [282/17668] intraday_0283.csv.gz  in=115,448,136 out=0 elapsed=22.2s

  [283/17668] intraday_0286.csv.gz  in=115,486,870 out=0 elapsed=22.3s

  [284/17668] intraday_0281.csv.gz  in=115,748,047 out=0 elapsed=22.3s

  [285/17668] intraday_0284.csv.gz  in=116,043,246 out=0 elapsed=22.3s

  [286/17668] intraday_0285.csv.gz  in=116,298,084 out=0 elapsed=22.5s

  [287/17668] intraday_0287.csv.gz  in=116,525,928 out=0 elapsed=22.5s

  [288/17668] intraday_0288.csv.gz  in=116,746,745 out=0 elapsed=22.5s

  [289/17668] intraday_0289.csv.gz  in=116,965,439 out=0 elapsed=22.5s

  [290/17668] intraday_0290.csv.gz  in=117,225,315 out=0 elapsed=22.7s

  [291/17668] intraday_0291.csv.gz  in=117,445,345 out=0 elapsed=22.7s

  [292/17668] intraday_0292.csv.gz  in=117,685,256 out=0 elapsed=22.7s

  [293/17668] intraday_0293.csv.gz  in=117,927,992 out=0 elapsed=22.7s

  [294/17668] intraday_0295.csv.gz  in=118,142,206 out=0 elapsed=22.8s

  [295/17668] intraday_0294.csv.gz  in=118,357,943 out=0 elapsed=22.9s

  [296/17668] intraday_0296.csv.gz  in=118,563,185 out=0 elapsed=22.9s

  [297/17668] intraday_0297.csv.gz  in=118,843,298 out=0 elapsed=22.9s

  [298/17668] intraday_0300.csv.gz  in=119,066,942 out=0 elapsed=23.1s

  [299/17668] intraday_0299.csv.gz  in=119,328,932 out=0 elapsed=23.1s

  [300/17668] intraday_0298.csv.gz  in=119,612,107 out=0 elapsed=23.1s

  [301/17668] intraday_0301.csv.gz  in=119,831,995 out=0 elapsed=23.1s

  [302/17668] intraday_0302.csv.gz  in=119,886,957 out=0 elapsed=23.1s

  [303/17668] intraday_0304.csv.gz  in=120,123,356 out=0 elapsed=23.3s

  [304/17668] intraday_0305.csv.gz  in=120,358,027 out=0 elapsed=23.3s

  [305/17668] intraday_0306.csv.gz  in=120,604,925 out=0 elapsed=23.3s

  [306/17668] intraday_0303.csv.gz  in=120,902,289 out=0 elapsed=23.3s

  [307/17668] intraday_0307.csv.gz  in=121,125,738 out=0 elapsed=23.5s

  [308/17668] intraday_0308.csv.gz  in=121,351,202 out=0 elapsed=23.5s

  [309/17668] intraday_0309.csv.gz  in=121,589,830 out=0 elapsed=23.6s

  [310/17668] intraday_0310.csv.gz  in=121,811,036 out=0 elapsed=23.6s

  [311/17668] intraday_0311.csv.gz  in=122,090,746 out=0 elapsed=23.7s

  [312/17668] intraday_0312.csv.gz  in=122,392,310 out=0 elapsed=23.7s

  [313/17668] intraday_0313.csv.gz  in=122,629,607 out=0 elapsed=23.7s

  [314/17668] intraday_0314.csv.gz  in=122,890,640 out=0 elapsed=23.8s

  [315/17668] intraday_0315.csv.gz  in=123,155,037 out=0 elapsed=23.9s

  [316/17668] intraday_0318.csv.gz  in=123,389,138 out=0 elapsed=23.9s

  [317/17668] intraday_0316.csv.gz  in=123,637,922 out=0 elapsed=23.9s

  [318/17668] intraday_0317.csv.gz  in=123,900,660 out=0 elapsed=24.0s

  [319/17668] intraday_0319.csv.gz  in=124,176,134 out=0 elapsed=24.1s

  [320/17668] intraday_0320.csv.gz  in=124,416,353 out=0 elapsed=24.2s

  [321/17668] intraday_0321.csv.gz  in=124,669,219 out=0 elapsed=24.2s

  [322/17668] intraday_0322.csv.gz  in=124,909,648 out=0 elapsed=24.2s

  [323/17668] intraday_0323.csv.gz  in=125,155,264 out=0 elapsed=24.3s

  [324/17668] intraday_0324.csv.gz  in=125,389,255 out=0 elapsed=24.4s

  [325/17668] intraday_0325.csv.gz  in=125,649,135 out=0 elapsed=24.4s

  [326/17668] intraday_0326.csv.gz  in=125,911,356 out=0 elapsed=24.4s

  [327/17668] intraday_0327.csv.gz  in=126,118,825 out=0 elapsed=24.5s

  [328/17668] intraday_0330.csv.gz  in=126,315,329 out=0 elapsed=24.6s

  [329/17668] intraday_0329.csv.gz  in=126,524,157 out=0 elapsed=24.6s

  [330/17668] intraday_0328.csv.gz  in=126,779,582 out=0 elapsed=24.6s

  [331/17668] intraday_0331.csv.gz  in=127,046,519 out=0 elapsed=24.7s

  [332/17668] intraday_0333.csv.gz  in=127,253,545 out=0 elapsed=24.8s

  [333/17668] intraday_0332.csv.gz  in=127,538,683 out=0 elapsed=24.8s

  [334/17668] intraday_0334.csv.gz  in=127,816,232 out=0 elapsed=24.8s

  [335/17668] intraday_0335.csv.gz  in=128,092,776 out=0 elapsed=24.9s

  [336/17668] intraday_0336.csv.gz  in=128,295,496 out=0 elapsed=25.0s

  [337/17668] intraday_0337.csv.gz  in=128,525,452 out=0 elapsed=25.0s

  [338/17668] intraday_0338.csv.gz  in=128,783,286 out=0 elapsed=25.1s

  [339/17668] intraday_0339.csv.gz  in=129,042,667 out=0 elapsed=25.1s

  [340/17668] intraday_0340.csv.gz  in=129,240,852 out=0 elapsed=25.1s

  [341/17668] intraday_0341.csv.gz  in=129,458,823 out=0 elapsed=25.2s

  [342/17668] intraday_0342.csv.gz  in=129,667,620 out=0 elapsed=25.2s

  [343/17668] intraday_0343.csv.gz  in=129,899,349 out=0 elapsed=25.3s

  [344/17668] intraday_0344.csv.gz  in=130,138,366 out=0 elapsed=25.3s

  [345/17668] intraday_0345.csv.gz  in=130,376,937 out=0 elapsed=25.4s

  [346/17668] intraday_0346.csv.gz  in=130,559,285 out=0 elapsed=25.4s

  [347/17668] intraday_0347.csv.gz  in=130,772,959 out=0 elapsed=25.5s

  [348/17668] intraday_0348.csv.gz  in=131,024,833 out=0 elapsed=25.5s

  [349/17668] intraday_0350.csv.gz  in=131,261,296 out=0 elapsed=25.6s

  [350/17668] intraday_0349.csv.gz  in=131,570,921 out=0 elapsed=25.6s

  [351/17668] intraday_0351.csv.gz  in=131,797,285 out=0 elapsed=25.6s

  [352/17668] intraday_0352.csv.gz  in=132,033,883 out=0 elapsed=25.7s

  [353/17668] intraday_0353.csv.gz  in=132,292,867 out=0 elapsed=25.8s

  [354/17668] intraday_0354.csv.gz  in=132,523,180 out=0 elapsed=25.8s

  [355/17668] intraday_0355.csv.gz  in=132,836,273 out=0 elapsed=25.9s

  [356/17668] intraday_0356.csv.gz  in=133,077,260 out=0 elapsed=25.9s

  [357/17668] intraday_0358.csv.gz  in=133,361,149 out=0 elapsed=26.1s

  [358/17668] intraday_0357.csv.gz  in=133,649,154 out=0 elapsed=26.1s

  [359/17668] intraday_0359.csv.gz  in=133,915,035 out=0 elapsed=26.1s

  [360/17668] intraday_0360.csv.gz  in=134,168,226 out=0 elapsed=26.1s

  [361/17668] intraday_0361.csv.gz  in=134,407,423 out=0 elapsed=26.3s

  [362/17668] intraday_0362.csv.gz  in=134,663,024 out=0 elapsed=26.3s

  [363/17668] intraday_0363.csv.gz  in=134,908,995 out=0 elapsed=26.3s

  [364/17668] intraday_0364.csv.gz  in=135,155,263 out=0 elapsed=26.3s

  [365/17668] intraday_0365.csv.gz  in=135,380,830 out=0 elapsed=26.4s

  [366/17668] intraday_0368.csv.gz  in=135,614,304 out=0 elapsed=26.5s

  [367/17668] intraday_0366.csv.gz  in=135,878,241 out=0 elapsed=26.5s

  [368/17668] intraday_0367.csv.gz  in=136,162,187 out=0 elapsed=26.5s

  [369/17668] intraday_0369.csv.gz  in=136,435,160 out=0 elapsed=26.6s

  [370/17668] intraday_0371.csv.gz  in=136,707,812 out=0 elapsed=26.7s

  [371/17668] intraday_0372.csv.gz  in=136,974,668 out=0 elapsed=26.7s

  [372/17668] intraday_0370.csv.gz  in=137,296,332 out=0 elapsed=26.8s

  [373/17668] intraday_0373.csv.gz  in=137,544,174 out=0 elapsed=26.8s

  [374/17668] intraday_0375.csv.gz  in=137,747,513 out=0 elapsed=26.9s

  [375/17668] intraday_0374.csv.gz  in=138,017,550 out=0 elapsed=26.9s

  [376/17668] intraday_0376.csv.gz  in=138,328,425 out=0 elapsed=27.0s

  [377/17668] intraday_0377.csv.gz  in=138,565,665 out=0 elapsed=27.0s

  [378/17668] intraday_0379.csv.gz  in=138,818,657 out=0 elapsed=27.1s

  [379/17668] intraday_0378.csv.gz  in=139,087,787 out=0 elapsed=27.2s

  [380/17668] intraday_0381.csv.gz  in=139,361,407 out=0 elapsed=27.3s

  [381/17668] intraday_0380.csv.gz  in=139,648,162 out=0 elapsed=27.3s

  [382/17668] intraday_0382.csv.gz  in=139,904,999 out=0 elapsed=27.4s

  [383/17668] intraday_0383.csv.gz  in=140,179,278 out=0 elapsed=27.4s

  [384/17668] intraday_0385.csv.gz  in=140,391,955 out=0 elapsed=27.5s

  [385/17668] intraday_0384.csv.gz  in=140,640,779 out=0 elapsed=27.5s

  [386/17668] intraday_0386.csv.gz  in=140,878,294 out=0 elapsed=27.6s

  [387/17668] intraday_0387.csv.gz  in=141,147,253 out=0 elapsed=27.6s

  [388/17668] intraday_0388.csv.gz  in=141,399,520 out=0 elapsed=27.7s

  [389/17668] intraday_0389.csv.gz  in=141,725,055 out=0 elapsed=27.8s

  [390/17668] intraday_0390.csv.gz  in=141,949,153 out=0 elapsed=27.8s

  [391/17668] intraday_0391.csv.gz  in=142,203,569 out=0 elapsed=27.8s

  [392/17668] intraday_0392.csv.gz  in=142,457,409 out=0 elapsed=27.9s

  [393/17668] intraday_0393.csv.gz  in=142,721,977 out=0 elapsed=28.0s

  [394/17668] intraday_0394.csv.gz  in=142,966,664 out=0 elapsed=28.0s

  [395/17668] intraday_0395.csv.gz  in=143,253,685 out=0 elapsed=28.0s

  [396/17668] intraday_0396.csv.gz  in=143,532,614 out=0 elapsed=28.1s

  [397/17668] intraday_0397.csv.gz  in=143,777,948 out=0 elapsed=28.1s

  [398/17668] intraday_0398.csv.gz  in=144,034,957 out=0 elapsed=28.2s

  [399/17668] intraday_0399.csv.gz  in=144,258,829 out=0 elapsed=28.2s

  [400/17668] intraday_0400.csv.gz  in=144,480,592 out=0 elapsed=28.3s

  [401/17668] intraday_0401.csv.gz  in=144,678,165 out=0 elapsed=28.3s

  [402/17668] intraday_0403.csv.gz  in=144,891,486 out=0 elapsed=28.4s

  [403/17668] intraday_0402.csv.gz  in=145,151,541 out=0 elapsed=28.4s

  [404/17668] intraday_0406.csv.gz  in=145,166,253 out=0 elapsed=28.4s

  [405/17668] intraday_0404.csv.gz  in=145,327,551 out=0 elapsed=28.4s

  [406/17668] intraday_0407.csv.gz  in=145,351,978 out=0 elapsed=28.4s

  [407/17668] intraday_0408.csv.gz  in=145,364,245 out=0 elapsed=28.4s

  [408/17668] intraday_0409.csv.gz  in=145,377,611 out=0 elapsed=28.5s

  [409/17668] intraday_0410.csv.gz  in=145,392,730 out=0 elapsed=28.5s

  [410/17668] intraday_0411.csv.gz  in=145,408,587 out=0 elapsed=28.5s

  [411/17668] intraday_0412.csv.gz  in=145,419,651 out=0 elapsed=28.5s

  [412/17668] intraday_0405.csv.gz  in=145,644,055 out=0 elapsed=28.5s

  [413/17668] intraday_0414.csv.gz  in=145,658,626 out=0 elapsed=28.5s

  [414/17668] intraday_0413.csv.gz  in=145,671,610 out=0 elapsed=28.5s

  [415/17668] intraday_0415.csv.gz  in=145,684,409 out=0 elapsed=28.5s

  [416/17668] intraday_0416.csv.gz  in=145,695,807 out=0 elapsed=28.5s

  [417/17668] intraday_0419.csv.gz  in=145,707,084 out=0 elapsed=28.5s

  [418/17668] intraday_0417.csv.gz  in=145,720,559 out=0 elapsed=28.5s

  [419/17668] intraday_0418.csv.gz  in=145,734,865 out=0 elapsed=28.6s

  [420/17668] intraday_0420.csv.gz  in=145,746,540 out=0 elapsed=28.6s

  [421/17668] intraday_0423.csv.gz  in=145,758,041 out=0 elapsed=28.6s

  [422/17668] intraday_0421.csv.gz  in=145,773,344 out=0 elapsed=28.6s

  [423/17668] intraday_0422.csv.gz  in=145,786,663 out=0 elapsed=28.6s

  [424/17668] intraday_0424.csv.gz  in=145,797,862 out=0 elapsed=28.6s

  [425/17668] intraday_0428.csv.gz  in=145,811,051 out=0 elapsed=28.6s

  [426/17668] intraday_0425.csv.gz  in=145,822,815 out=0 elapsed=28.6s

  [427/17668] intraday_0427.csv.gz  in=145,834,867 out=0 elapsed=28.6s

  [428/17668] intraday_0426.csv.gz  in=145,846,867 out=0 elapsed=28.6s

  [429/17668] intraday_0430.csv.gz  in=145,857,686 out=0 elapsed=28.7s

  [430/17668] intraday_0431.csv.gz  in=145,869,097 out=0 elapsed=28.7s

  [431/17668] intraday_0432.csv.gz  in=145,880,010 out=0 elapsed=28.7s

  [432/17668] intraday_0429.csv.gz  in=145,893,068 out=0 elapsed=28.7s

  [433/17668] intraday_0433.csv.gz  in=145,907,644 out=0 elapsed=28.7s

  [434/17668] intraday_0434.csv.gz  in=145,923,420 out=0 elapsed=28.7s

  [435/17668] intraday_0435.csv.gz  in=145,939,651 out=0 elapsed=28.7s

  [436/17668] intraday_0436.csv.gz  in=145,951,958 out=0 elapsed=28.7s

  [437/17668] intraday_0438.csv.gz  in=145,964,938 out=0 elapsed=28.7s

  [438/17668] intraday_0437.csv.gz  in=145,976,928 out=0 elapsed=28.8s

  [439/17668] intraday_0439.csv.gz  in=145,994,748 out=0 elapsed=28.8s

  [440/17668] intraday_0441.csv.gz  in=146,006,670 out=0 elapsed=28.8s

  [441/17668] intraday_0440.csv.gz  in=146,018,926 out=0 elapsed=28.8s

  [442/17668] intraday_0443.csv.gz  in=146,030,660 out=0 elapsed=28.8s

  [443/17668] intraday_0442.csv.gz  in=146,044,273 out=0 elapsed=28.8s

  [444/17668] intraday_0444.csv.gz  in=146,056,615 out=0 elapsed=28.8s

  [445/17668] intraday_0446.csv.gz  in=146,070,179 out=0 elapsed=28.8s

  [446/17668] intraday_0445.csv.gz  in=146,084,577 out=0 elapsed=28.8s

  [447/17668] intraday_0447.csv.gz  in=146,098,749 out=0 elapsed=28.8s

  [448/17668] intraday_0448.csv.gz  in=146,112,265 out=0 elapsed=28.9s

  [449/17668] intraday_0450.csv.gz  in=146,125,627 out=0 elapsed=28.9s

  [450/17668] intraday_0451.csv.gz  in=146,138,212 out=0 elapsed=28.9s

  [451/17668] intraday_0449.csv.gz  in=146,175,913 out=0 elapsed=28.9s

  [452/17668] intraday_0454.csv.gz  in=146,188,677 out=0 elapsed=28.9s

  [453/17668] intraday_0453.csv.gz  in=146,201,274 out=0 elapsed=28.9s

  [454/17668] intraday_0452.csv.gz  in=146,219,751 out=0 elapsed=28.9s

  [455/17668] intraday_0455.csv.gz  in=146,243,311 out=0 elapsed=28.9s

  [456/17668] intraday_0457.csv.gz  in=146,257,424 out=0 elapsed=28.9s

  [457/17668] intraday_0456.csv.gz  in=146,269,716 out=0 elapsed=28.9s

  [458/17668] intraday_0458.csv.gz  in=146,282,797 out=0 elapsed=29.0s

  [459/17668] intraday_0459.csv.gz  in=146,296,147 out=0 elapsed=29.0s

  [460/17668] intraday_0460.csv.gz  in=146,311,892 out=0 elapsed=29.0s

  [461/17668] intraday_0462.csv.gz  in=146,325,476 out=0 elapsed=29.0s

  [462/17668] intraday_0461.csv.gz  in=146,337,792 out=0 elapsed=29.0s

  [463/17668] intraday_0463.csv.gz  in=146,350,280 out=0 elapsed=29.0s

  [464/17668] intraday_0464.csv.gz  in=146,362,048 out=0 elapsed=29.0s

  [465/17668] intraday_0466.csv.gz  in=146,374,668 out=0 elapsed=29.0s

  [466/17668] intraday_0467.csv.gz  in=146,391,937 out=0 elapsed=29.0s

  [467/17668] intraday_0465.csv.gz  in=146,417,843 out=0 elapsed=29.1s

  [468/17668] intraday_0468.csv.gz  in=146,429,806 out=0 elapsed=29.1s

  [469/17668] intraday_0469.csv.gz  in=146,444,443 out=0 elapsed=29.1s

  [470/17668] intraday_0470.csv.gz  in=146,459,130 out=0 elapsed=29.1s

  [471/17668] intraday_0471.csv.gz  in=146,471,756 out=0 elapsed=29.1s

  [472/17668] intraday_0472.csv.gz  in=146,483,702 out=0 elapsed=29.1s

  [473/17668] intraday_0473.csv.gz  in=146,495,640 out=0 elapsed=29.1s

  [474/17668] intraday_0474.csv.gz  in=146,508,636 out=0 elapsed=29.1s

  [475/17668] intraday_0475.csv.gz  in=146,521,728 out=0 elapsed=29.1s

  [476/17668] intraday_0476.csv.gz  in=146,533,238 out=0 elapsed=29.1s

  [477/17668] intraday_0477.csv.gz  in=146,542,494 out=0 elapsed=29.1s

  [478/17668] intraday_0478.csv.gz  in=146,554,934 out=0 elapsed=29.2s

  [479/17668] intraday_0480.csv.gz  in=146,566,656 out=0 elapsed=29.2s

  [480/17668] intraday_0479.csv.gz  in=146,579,673 out=0 elapsed=29.2s

  [481/17668] intraday_0481.csv.gz  in=146,591,926 out=0 elapsed=29.2s

  [482/17668] intraday_0482.csv.gz  in=146,603,171 out=0 elapsed=29.2s

  [483/17668] intraday_0485.csv.gz  in=146,620,556 out=0 elapsed=29.2s

  [484/17668] intraday_0483.csv.gz  in=146,631,235 out=0 elapsed=29.2s

  [485/17668] intraday_0484.csv.gz  in=146,643,216 out=0 elapsed=29.2s

  [486/17668] intraday_0487.csv.gz  in=146,653,651 out=0 elapsed=29.2s

  [487/17668] intraday_0486.csv.gz  in=146,665,512 out=0 elapsed=29.2s

  [488/17668] intraday_0488.csv.gz  in=146,679,315 out=0 elapsed=29.2s

  [489/17668] intraday_0489.csv.gz  in=146,691,816 out=0 elapsed=29.2s

  [490/17668] intraday_0490.csv.gz  in=146,709,671 out=0 elapsed=29.3s

  [491/17668] intraday_0491.csv.gz  in=146,724,538 out=0 elapsed=29.3s

  [492/17668] intraday_0492.csv.gz  in=146,738,727 out=0 elapsed=29.3s

  [493/17668] intraday_0493.csv.gz  in=146,752,962 out=0 elapsed=29.3s

  [494/17668] intraday_0496.csv.gz  in=146,767,868 out=0 elapsed=29.3s

  [495/17668] intraday_0495.csv.gz  in=146,781,445 out=0 elapsed=29.3s

  [496/17668] intraday_0494.csv.gz  in=146,796,225 out=0 elapsed=29.4s

  [497/17668] intraday_0497.csv.gz  in=146,815,798 out=0 elapsed=29.4s

  [498/17668] intraday_0498.csv.gz  in=146,828,986 out=0 elapsed=29.4s

  [499/17668] intraday_0499.csv.gz  in=146,840,301 out=0 elapsed=29.4s

  [500/17668] intraday_0501.csv.gz  in=146,859,439 out=0 elapsed=29.4s

  [501/17668] intraday_0500.csv.gz  in=146,879,764 out=0 elapsed=29.4s

  [502/17668] intraday_0503.csv.gz  in=146,893,402 out=0 elapsed=29.4s

  [503/17668] intraday_0502.csv.gz  in=146,910,524 out=0 elapsed=29.4s

  [504/17668] intraday_0505.csv.gz  in=146,925,862 out=0 elapsed=29.4s

  [505/17668] intraday_0504.csv.gz  in=146,938,528 out=0 elapsed=29.4s

  [506/17668] intraday_0507.csv.gz  in=146,954,063 out=0 elapsed=29.4s

  [507/17668] intraday_0506.csv.gz  in=146,990,344 out=0 elapsed=29.5s

  [508/17668] intraday_0510.csv.gz  in=147,001,711 out=0 elapsed=29.5s

  [509/17668] intraday_0509.csv.gz  in=147,017,771 out=0 elapsed=29.5s

  [510/17668] intraday_0508.csv.gz  in=147,046,916 out=0 elapsed=29.5s

  [511/17668] intraday_0511.csv.gz  in=147,060,675 out=0 elapsed=29.5s

  [512/17668] intraday_0512.csv.gz  in=147,077,697 out=0 elapsed=29.5s

  [513/17668] intraday_0513.csv.gz  in=147,090,371 out=0 elapsed=29.5s

  [514/17668] intraday_0515.csv.gz  in=147,105,173 out=0 elapsed=29.5s

  [515/17668] intraday_0517.csv.gz  in=147,121,833 out=0 elapsed=29.5s

  [516/17668] intraday_0516.csv.gz  in=147,136,854 out=0 elapsed=29.5s

  [517/17668] intraday_0514.csv.gz  in=147,154,561 out=0 elapsed=29.5s

  [518/17668] intraday_0518.csv.gz  in=147,166,721 out=0 elapsed=29.6s

  [519/17668] intraday_0519.csv.gz  in=147,180,329 out=0 elapsed=29.6s

  [520/17668] intraday_0520.csv.gz  in=147,191,638 out=0 elapsed=29.6s

  [521/17668] intraday_0522.csv.gz  in=147,204,899 out=0 elapsed=29.6s

  [522/17668] intraday_0521.csv.gz  in=147,217,859 out=0 elapsed=29.6s

  [523/17668] intraday_0524.csv.gz  in=147,230,968 out=0 elapsed=29.6s

  [524/17668] intraday_0526.csv.gz  in=147,243,887 out=0 elapsed=29.6s

  [525/17668] intraday_0523.csv.gz  in=147,258,699 out=0 elapsed=29.6s

  [526/17668] intraday_0525.csv.gz  in=147,274,492 out=0 elapsed=29.6s

  [527/17668] intraday_0527.csv.gz  in=147,287,469 out=0 elapsed=29.6s

  [528/17668] intraday_0530.csv.gz  in=147,301,758 out=0 elapsed=29.7s

  [529/17668] intraday_0528.csv.gz  in=147,318,714 out=0 elapsed=29.7s

  [530/17668] intraday_0529.csv.gz  in=147,331,059 out=0 elapsed=29.7s

  [531/17668] intraday_0531.csv.gz  in=147,347,109 out=0 elapsed=29.7s

  [532/17668] intraday_0532.csv.gz  in=147,361,302 out=0 elapsed=29.7s

  [533/17668] intraday_0533.csv.gz  in=147,376,091 out=0 elapsed=29.7s

  [534/17668] intraday_0536.csv.gz  in=147,387,653 out=0 elapsed=29.7s

  [535/17668] intraday_0535.csv.gz  in=147,398,200 out=0 elapsed=29.7s

  [536/17668] intraday_0534.csv.gz  in=147,412,623 out=0 elapsed=29.7s

  [537/17668] intraday_0537.csv.gz  in=147,423,684 out=0 elapsed=29.7s

  [538/17668] intraday_0539.csv.gz  in=147,434,680 out=0 elapsed=29.8s

  [539/17668] intraday_0540.csv.gz  in=147,444,705 out=0 elapsed=29.8s

  [540/17668] intraday_0538.csv.gz  in=147,458,505 out=0 elapsed=29.8s

  [541/17668] intraday_0541.csv.gz  in=147,466,999 out=0 elapsed=29.8s

  [542/17668] intraday_0544.csv.gz  in=147,493,880 out=0 elapsed=29.8s

  [543/17668] intraday_0543.csv.gz  in=147,523,470 out=0 elapsed=29.8s

  [544/17668] intraday_0542.csv.gz  in=147,565,316 out=0 elapsed=29.8s

  [545/17668] intraday_0545.csv.gz  in=147,606,543 out=0 elapsed=29.8s

  [546/17668] intraday_0548.csv.gz  in=147,630,483 out=0 elapsed=29.9s

  [547/17668] intraday_0549.csv.gz  in=147,658,073 out=0 elapsed=29.9s

  [548/17668] intraday_0546.csv.gz  in=147,689,491 out=0 elapsed=29.9s

  [549/17668] intraday_0547.csv.gz  in=147,723,194 out=0 elapsed=29.9s

  [550/17668] intraday_0550.csv.gz  in=147,752,711 out=0 elapsed=29.9s

  [551/17668] intraday_0551.csv.gz  in=147,780,245 out=0 elapsed=29.9s

  [552/17668] intraday_0552.csv.gz  in=147,804,284 out=0 elapsed=29.9s

  [553/17668] intraday_0553.csv.gz  in=147,832,832 out=0 elapsed=29.9s

  [554/17668] intraday_0556.csv.gz  in=147,856,606 out=0 elapsed=30.0s

  [555/17668] intraday_0555.csv.gz  in=147,879,085 out=0 elapsed=30.0s

  [556/17668] intraday_0557.csv.gz  in=147,910,613 out=0 elapsed=30.0s

  [557/17668] intraday_0554.csv.gz  in=147,941,618 out=0 elapsed=30.0s

  [558/17668] intraday_0558.csv.gz  in=147,970,209 out=0 elapsed=30.0s

  [559/17668] intraday_0560.csv.gz  in=147,994,077 out=0 elapsed=30.0s

  [560/17668] intraday_0561.csv.gz  in=148,021,150 out=0 elapsed=30.0s

  [561/17668] intraday_0559.csv.gz  in=148,048,023 out=0 elapsed=30.0s

  [562/17668] intraday_0562.csv.gz  in=148,073,086 out=0 elapsed=30.0s

  [563/17668] intraday_0563.csv.gz  in=148,097,855 out=0 elapsed=30.1s

  [564/17668] intraday_0565.csv.gz  in=148,125,108 out=0 elapsed=30.1s

  [565/17668] intraday_0564.csv.gz  in=148,152,228 out=0 elapsed=30.1s

  [566/17668] intraday_0566.csv.gz  in=148,175,781 out=0 elapsed=30.1s

  [567/17668] intraday_0567.csv.gz  in=148,198,952 out=0 elapsed=30.1s

  [568/17668] intraday_0568.csv.gz  in=148,219,961 out=0 elapsed=30.1s

  [569/17668] intraday_0569.csv.gz  in=148,251,292 out=0 elapsed=30.1s

  [570/17668] intraday_0570.csv.gz  in=148,284,544 out=0 elapsed=30.1s

  [571/17668] intraday_0571.csv.gz  in=148,316,989 out=0 elapsed=30.2s

  [572/17668] intraday_0572.csv.gz  in=148,341,303 out=0 elapsed=30.2s

  [573/17668] intraday_0573.csv.gz  in=148,367,608 out=0 elapsed=30.2s

  [574/17668] intraday_0574.csv.gz  in=148,395,071 out=0 elapsed=30.2s

  [575/17668] intraday_0575.csv.gz  in=148,428,911 out=0 elapsed=30.2s

  [576/17668] intraday_0576.csv.gz  in=148,459,676 out=0 elapsed=30.2s

  [577/17668] intraday_0577.csv.gz  in=148,485,209 out=0 elapsed=30.2s

  [578/17668] intraday_0578.csv.gz  in=148,517,233 out=0 elapsed=30.2s

  [579/17668] intraday_0580.csv.gz  in=148,543,926 out=0 elapsed=30.2s

  [580/17668] intraday_0582.csv.gz  in=148,574,960 out=0 elapsed=30.3s

  [581/17668] intraday_0581.csv.gz  in=148,607,706 out=0 elapsed=30.3s

  [582/17668] intraday_0579.csv.gz  in=148,659,685 out=0 elapsed=30.3s

  [583/17668] intraday_0583.csv.gz  in=148,688,678 out=0 elapsed=30.3s

  [584/17668] intraday_0584.csv.gz  in=148,719,216 out=0 elapsed=30.3s

  [585/17668] intraday_0586.csv.gz  in=148,746,838 out=0 elapsed=30.3s

  [586/17668] intraday_0585.csv.gz  in=148,772,890 out=0 elapsed=30.3s

  [587/17668] intraday_0587.csv.gz  in=148,798,828 out=0 elapsed=30.3s

  [588/17668] intraday_0589.csv.gz  in=148,827,976 out=0 elapsed=30.4s

  [589/17668] intraday_0591.csv.gz  in=148,855,791 out=0 elapsed=30.4s

  [590/17668] intraday_0590.csv.gz  in=148,886,729 out=0 elapsed=30.4s

  [591/17668] intraday_0588.csv.gz  in=148,938,696 out=0 elapsed=30.4s

  [592/17668] intraday_0592.csv.gz  in=148,966,176 out=0 elapsed=30.4s

  [593/17668] intraday_0594.csv.gz  in=148,992,313 out=0 elapsed=30.4s

  [594/17668] intraday_0595.csv.gz  in=149,019,311 out=0 elapsed=30.4s

  [595/17668] intraday_0593.csv.gz  in=149,055,519 out=0 elapsed=30.5s

  [596/17668] intraday_0596.csv.gz  in=149,080,692 out=0 elapsed=30.5s

  [597/17668] intraday_0597.csv.gz  in=149,107,419 out=0 elapsed=30.5s

  [598/17668] intraday_0599.csv.gz  in=149,133,905 out=0 elapsed=30.5s

  [599/17668] intraday_0598.csv.gz  in=149,161,545 out=0 elapsed=30.5s

  [600/17668] intraday_0600.csv.gz  in=149,185,832 out=0 elapsed=30.5s

  [601/17668] intraday_0601.csv.gz  in=149,210,192 out=0 elapsed=30.5s

  [602/17668] intraday_0602.csv.gz  in=149,232,632 out=0 elapsed=30.5s

  [603/17668] intraday_0603.csv.gz  in=149,266,332 out=0 elapsed=30.5s

  [604/17668] intraday_0604.csv.gz  in=149,292,076 out=0 elapsed=30.5s

  [605/17668] intraday_0605.csv.gz  in=149,320,593 out=0 elapsed=30.6s

  [606/17668] intraday_0606.csv.gz  in=149,352,504 out=0 elapsed=30.6s

  [607/17668] intraday_0607.csv.gz  in=149,401,073 out=0 elapsed=30.6s

  [608/17668] intraday_0608.csv.gz  in=149,423,867 out=0 elapsed=30.6s

  [609/17668] intraday_0609.csv.gz  in=149,449,906 out=0 elapsed=30.6s

  [610/17668] intraday_0610.csv.gz  in=149,475,762 out=0 elapsed=30.6s

  [611/17668] intraday_0614.csv.gz  in=149,501,089 out=0 elapsed=30.7s

  [612/17668] intraday_0613.csv.gz  in=149,522,605 out=0 elapsed=30.7s

  [613/17668] intraday_0611.csv.gz  in=149,552,353 out=0 elapsed=30.7s

  [614/17668] intraday_0612.csv.gz  in=149,575,053 out=0 elapsed=30.7s

  [615/17668] intraday_0618.csv.gz  in=149,595,242 out=0 elapsed=30.7s

  [616/17668] intraday_0616.csv.gz  in=149,619,906 out=0 elapsed=30.7s

  [617/17668] intraday_0617.csv.gz  in=149,649,271 out=0 elapsed=30.7s

  [618/17668] intraday_0615.csv.gz  in=149,684,038 out=0 elapsed=30.7s

  [619/17668] intraday_0619.csv.gz  in=149,706,447 out=0 elapsed=30.8s

  [620/17668] intraday_0622.csv.gz  in=149,733,290 out=0 elapsed=30.8s

  [621/17668] intraday_0621.csv.gz  in=149,767,692 out=0 elapsed=30.8s

  [622/17668] intraday_0620.csv.gz  in=149,803,181 out=0 elapsed=30.8s

  [623/17668] intraday_0623.csv.gz  in=149,829,559 out=0 elapsed=30.8s

  [624/17668] intraday_0625.csv.gz  in=149,858,646 out=0 elapsed=30.8s

  [625/17668] intraday_0624.csv.gz  in=149,888,290 out=0 elapsed=30.8s

  [626/17668] intraday_0626.csv.gz  in=149,918,669 out=0 elapsed=30.8s

  [627/17668] intraday_0627.csv.gz  in=149,952,541 out=0 elapsed=30.8s

  [628/17668] intraday_0630.csv.gz  in=149,983,158 out=0 elapsed=30.9s

  [629/17668] intraday_0629.csv.gz  in=150,017,090 out=0 elapsed=30.9s

  [630/17668] intraday_0628.csv.gz  in=150,051,815 out=0 elapsed=30.9s

  [631/17668] intraday_0631.csv.gz  in=150,082,344 out=0 elapsed=30.9s

  [632/17668] intraday_0632.csv.gz  in=150,109,334 out=0 elapsed=30.9s

  [633/17668] intraday_0634.csv.gz  in=150,142,308 out=0 elapsed=30.9s

  [634/17668] intraday_0633.csv.gz  in=150,170,587 out=0 elapsed=30.9s

  [635/17668] intraday_0635.csv.gz  in=150,198,877 out=0 elapsed=30.9s

  [636/17668] intraday_0636.csv.gz  in=150,223,517 out=0 elapsed=30.9s

  [637/17668] intraday_0637.csv.gz  in=150,254,101 out=0 elapsed=31.0s

  [638/17668] intraday_0638.csv.gz  in=150,287,667 out=0 elapsed=31.0s

  [639/17668] intraday_0639.csv.gz  in=150,316,577 out=0 elapsed=31.0s

  [640/17668] intraday_0640.csv.gz  in=150,344,888 out=0 elapsed=31.0s

  [641/17668] intraday_0641.csv.gz  in=150,374,658 out=0 elapsed=31.0s

  [642/17668] intraday_0642.csv.gz  in=150,406,279 out=0 elapsed=31.0s

  [643/17668] intraday_0643.csv.gz  in=150,440,063 out=0 elapsed=31.0s

  [644/17668] intraday_0644.csv.gz  in=150,471,135 out=0 elapsed=31.1s

  [645/17668] intraday_0645.csv.gz  in=150,504,092 out=0 elapsed=31.1s

  [646/17668] intraday_0646.csv.gz  in=150,530,150 out=0 elapsed=31.1s

  [647/17668] intraday_0647.csv.gz  in=150,559,265 out=0 elapsed=31.1s

  [648/17668] intraday_0648.csv.gz  in=150,588,431 out=0 elapsed=31.1s

  [649/17668] intraday_0649.csv.gz  in=150,616,816 out=0 elapsed=31.1s

  [650/17668] intraday_0650.csv.gz  in=150,647,955 out=0 elapsed=31.1s

  [651/17668] intraday_0651.csv.gz  in=150,672,868 out=0 elapsed=31.1s

  [652/17668] intraday_0652.csv.gz  in=150,705,622 out=0 elapsed=31.1s

  [653/17668] intraday_0653.csv.gz  in=150,740,623 out=0 elapsed=31.1s

  [654/17668] intraday_0654.csv.gz  in=150,767,795 out=0 elapsed=31.2s

  [655/17668] intraday_0655.csv.gz  in=150,796,374 out=0 elapsed=31.2s

  [656/17668] intraday_0657.csv.gz  in=150,823,361 out=0 elapsed=31.2s

  [657/17668] intraday_0658.csv.gz  in=150,848,941 out=0 elapsed=31.2s

  [658/17668] intraday_0656.csv.gz  in=150,880,261 out=0 elapsed=31.2s

  [659/17668] intraday_0659.csv.gz  in=150,912,920 out=0 elapsed=31.2s

  [660/17668] intraday_0660.csv.gz  in=150,940,951 out=0 elapsed=31.2s

  [661/17668] intraday_0662.csv.gz  in=150,967,623 out=0 elapsed=31.2s

  [662/17668] intraday_0661.csv.gz  in=151,019,866 out=0 elapsed=31.3s

  [663/17668] intraday_0665.csv.gz  in=151,049,664 out=0 elapsed=31.3s

  [664/17668] intraday_0663.csv.gz  in=151,079,871 out=0 elapsed=31.3s

  [665/17668] intraday_0664.csv.gz  in=151,112,109 out=0 elapsed=31.3s

  [666/17668] intraday_0666.csv.gz  in=151,145,019 out=0 elapsed=31.3s

  [667/17668] intraday_0669.csv.gz  in=151,173,963 out=0 elapsed=31.3s

  [668/17668] intraday_0667.csv.gz  in=151,209,604 out=0 elapsed=31.3s

  [669/17668] intraday_0668.csv.gz  in=151,238,489 out=0 elapsed=31.3s

  [670/17668] intraday_0670.csv.gz  in=151,268,576 out=0 elapsed=31.4s

  [671/17668] intraday_0673.csv.gz  in=151,291,931 out=0 elapsed=31.4s

  [672/17668] intraday_0672.csv.gz  in=151,321,611 out=0 elapsed=31.4s

  [673/17668] intraday_0671.csv.gz  in=151,354,334 out=0 elapsed=31.4s

  [674/17668] intraday_0675.csv.gz  in=151,374,813 out=0 elapsed=31.4s

  [675/17668] intraday_0677.csv.gz  in=151,393,046 out=0 elapsed=31.4s

  [676/17668] intraday_0676.csv.gz  in=151,415,623 out=0 elapsed=31.4s

  [677/17668] intraday_0674.csv.gz  in=151,447,334 out=0 elapsed=31.5s

  [678/17668] intraday_0680.csv.gz  in=151,574,848 out=0 elapsed=31.6s

  [679/17668] intraday_0678.csv.gz  in=151,756,233 out=0 elapsed=31.6s

  [680/17668] intraday_0679.csv.gz  in=151,916,048 out=0 elapsed=31.6s

  [681/17668] intraday_0681.csv.gz  in=152,035,572 out=0 elapsed=31.6s

  [682/17668] intraday_0682.csv.gz  in=152,183,889 out=0 elapsed=31.7s

  [683/17668] intraday_0684.csv.gz  in=152,303,931 out=0 elapsed=31.7s

  [684/17668] intraday_0685.csv.gz  in=152,436,248 out=0 elapsed=31.8s

  [685/17668] intraday_0683.csv.gz  in=152,597,012 out=0 elapsed=31.8s

  [686/17668] intraday_0688.csv.gz  in=152,724,884 out=0 elapsed=31.9s

  [687/17668] intraday_0687.csv.gz  in=152,867,810 out=0 elapsed=31.9s

  [688/17668] intraday_0686.csv.gz  in=153,012,576 out=0 elapsed=31.9s

  [689/17668] intraday_0689.csv.gz  in=153,154,517 out=0 elapsed=31.9s

  [690/17668] intraday_0692.csv.gz  in=153,255,887 out=0 elapsed=32.0s

  [691/17668] intraday_0691.csv.gz  in=153,383,278 out=0 elapsed=32.0s

  [692/17668] intraday_0690.csv.gz  in=153,542,476 out=0 elapsed=32.1s

  [693/17668] intraday_0693.csv.gz  in=153,725,767 out=0 elapsed=32.1s

  [694/17668] intraday_0695.csv.gz  in=153,859,202 out=0 elapsed=32.2s

  [695/17668] intraday_0694.csv.gz  in=153,997,703 out=0 elapsed=32.2s

  [696/17668] intraday_0696.csv.gz  in=154,134,404 out=0 elapsed=32.2s

  [697/17668] intraday_0697.csv.gz  in=154,268,443 out=0 elapsed=32.2s

  [698/17668] intraday_0699.csv.gz  in=154,401,727 out=0 elapsed=32.3s

  [699/17668] intraday_0698.csv.gz  in=154,540,161 out=0 elapsed=32.3s

  [700/17668] intraday_0700.csv.gz  in=154,667,673 out=0 elapsed=32.3s

  [701/17668] intraday_0701.csv.gz  in=154,856,762 out=0 elapsed=32.4s

  [702/17668] intraday_0702.csv.gz  in=154,996,117 out=0 elapsed=32.4s

  [703/17668] intraday_0704.csv.gz  in=155,113,959 out=0 elapsed=32.4s

  [704/17668] intraday_0703.csv.gz  in=155,240,129 out=0 elapsed=32.4s

  [705/17668] intraday_0705.csv.gz  in=155,402,243 out=0 elapsed=32.5s

  [706/17668] intraday_0708.csv.gz  in=155,522,748 out=0 elapsed=32.5s

  [707/17668] intraday_0707.csv.gz  in=155,681,342 out=0 elapsed=32.6s

  [708/17668] intraday_0706.csv.gz  in=155,861,235 out=0 elapsed=32.6s

  [709/17668] intraday_0709.csv.gz  in=155,997,571 out=0 elapsed=32.6s

  [710/17668] intraday_0710.csv.gz  in=156,136,449 out=0 elapsed=32.7s

  [711/17668] intraday_0712.csv.gz  in=156,273,222 out=0 elapsed=32.7s

  [712/17668] intraday_0713.csv.gz  in=156,396,389 out=0 elapsed=32.7s

  [713/17668] intraday_0711.csv.gz  in=156,619,873 out=0 elapsed=32.7s

  [714/17668] intraday_0714.csv.gz  in=156,768,452 out=0 elapsed=32.8s

  [715/17668] intraday_0715.csv.gz  in=156,903,093 out=0 elapsed=32.8s

  [716/17668] intraday_0716.csv.gz  in=157,041,253 out=0 elapsed=32.8s

  [717/17668] intraday_0717.csv.gz  in=157,196,573 out=0 elapsed=32.9s

  [718/17668] intraday_0718.csv.gz  in=157,344,926 out=0 elapsed=32.9s

  [719/17668] intraday_0719.csv.gz  in=157,478,345 out=0 elapsed=32.9s

  [720/17668] intraday_0720.csv.gz  in=157,642,115 out=0 elapsed=33.0s

  [721/17668] intraday_0721.csv.gz  in=157,766,245 out=0 elapsed=33.0s

  [722/17668] intraday_0722.csv.gz  in=157,888,287 out=0 elapsed=33.0s

  [723/17668] intraday_0723.csv.gz  in=158,046,991 out=0 elapsed=33.0s

  [724/17668] intraday_0724.csv.gz  in=158,185,787 out=0 elapsed=33.1s

  [725/17668] intraday_0725.csv.gz  in=158,327,072 out=0 elapsed=33.1s

  [726/17668] intraday_0726.csv.gz  in=158,468,376 out=0 elapsed=33.1s

  [727/17668] intraday_0727.csv.gz  in=158,616,553 out=0 elapsed=33.1s

  [728/17668] intraday_0730.csv.gz  in=158,652,357 out=0 elapsed=33.2s

  [729/17668] intraday_0728.csv.gz  in=158,785,668 out=0 elapsed=33.2s

  [730/17668] intraday_0729.csv.gz  in=158,897,969 out=0 elapsed=33.2s

  [731/17668] intraday_0732.csv.gz  in=159,034,234 out=0 elapsed=33.3s

  [732/17668] intraday_0731.csv.gz  in=159,182,736 out=0 elapsed=33.3s

  [733/17668] intraday_0733.csv.gz  in=159,312,419 out=0 elapsed=33.3s

  [734/17668] intraday_0734.csv.gz  in=159,445,206 out=0 elapsed=33.3s

  [735/17668] intraday_0736.csv.gz  in=159,565,824 out=0 elapsed=33.4s

  [736/17668] intraday_0735.csv.gz  in=159,729,226 out=0 elapsed=33.4s

  [737/17668] intraday_0738.csv.gz  in=159,848,715 out=0 elapsed=33.4s

  [738/17668] intraday_0737.csv.gz  in=159,994,738 out=0 elapsed=33.4s

  [739/17668] intraday_0739.csv.gz  in=160,108,715 out=0 elapsed=33.5s

  [740/17668] intraday_0740.csv.gz  in=160,251,867 out=0 elapsed=33.6s

  [741/17668] intraday_0741.csv.gz  in=160,398,732 out=0 elapsed=33.6s

  [742/17668] intraday_0742.csv.gz  in=160,541,414 out=0 elapsed=33.6s

  [743/17668] intraday_0743.csv.gz  in=160,694,567 out=0 elapsed=33.6s

  [744/17668] intraday_0746.csv.gz  in=160,828,300 out=0 elapsed=33.7s

  [745/17668] intraday_0745.csv.gz  in=160,981,424 out=0 elapsed=33.7s

  [746/17668] intraday_0744.csv.gz  in=161,134,735 out=0 elapsed=33.7s

  [747/17668] intraday_0747.csv.gz  in=161,275,438 out=0 elapsed=33.8s

  [748/17668] intraday_0749.csv.gz  in=161,392,280 out=0 elapsed=33.8s

  [749/17668] intraday_0750.csv.gz  in=161,519,801 out=0 elapsed=33.8s

  [750/17668] intraday_0748.csv.gz  in=161,658,304 out=0 elapsed=33.8s

  [751/17668] intraday_0751.csv.gz  in=161,769,784 out=0 elapsed=33.8s

  [752/17668] intraday_0753.csv.gz  in=161,901,320 out=0 elapsed=34.0s

  [753/17668] intraday_0752.csv.gz  in=162,036,013 out=0 elapsed=34.0s

  [754/17668] intraday_0755.csv.gz  in=162,159,711 out=0 elapsed=34.0s

  [755/17668] intraday_0754.csv.gz  in=162,296,789 out=0 elapsed=34.0s

  [756/17668] intraday_0756.csv.gz  in=162,402,013 out=0 elapsed=34.0s

  [757/17668] intraday_0757.csv.gz  in=162,533,048 out=0 elapsed=34.1s

  [758/17668] intraday_0758.csv.gz  in=162,707,166 out=0 elapsed=34.1s

  [759/17668] intraday_0759.csv.gz  in=162,866,044 out=0 elapsed=34.1s

  [760/17668] intraday_0760.csv.gz  in=162,999,521 out=0 elapsed=34.2s

  [761/17668] intraday_0761.csv.gz  in=163,114,446 out=0 elapsed=34.2s

  [762/17668] intraday_0762.csv.gz  in=163,249,987 out=0 elapsed=34.2s

  [763/17668] intraday_0763.csv.gz  in=163,397,708 out=0 elapsed=34.2s

  [764/17668] intraday_0764.csv.gz  in=163,552,555 out=0 elapsed=34.3s

  [765/17668] intraday_0765.csv.gz  in=163,688,782 out=0 elapsed=34.3s

  [766/17668] intraday_0766.csv.gz  in=163,846,217 out=0 elapsed=34.4s

  [767/17668] intraday_0767.csv.gz  in=163,993,651 out=0 elapsed=34.4s

  [768/17668] intraday_0768.csv.gz  in=164,150,804 out=0 elapsed=34.4s

  [769/17668] intraday_0769.csv.gz  in=164,303,234 out=0 elapsed=34.4s

  [770/17668] intraday_0770.csv.gz  in=164,436,536 out=0 elapsed=34.5s

  [771/17668] intraday_0771.csv.gz  in=164,570,092 out=0 elapsed=34.5s

  [772/17668] intraday_0772.csv.gz  in=164,716,922 out=0 elapsed=34.5s

  [773/17668] intraday_0773.csv.gz  in=164,847,419 out=0 elapsed=34.5s

  [774/17668] intraday_0774.csv.gz  in=164,988,419 out=0 elapsed=34.6s

  [775/17668] intraday_0775.csv.gz  in=165,118,612 out=0 elapsed=34.6s

  [776/17668] intraday_0777.csv.gz  in=165,255,747 out=0 elapsed=34.7s

  [777/17668] intraday_0776.csv.gz  in=165,422,237 out=0 elapsed=34.7s

  [778/17668] intraday_0778.csv.gz  in=165,571,124 out=0 elapsed=34.7s

  [779/17668] intraday_0779.csv.gz  in=165,730,454 out=0 elapsed=34.7s

  [780/17668] intraday_0780.csv.gz  in=165,861,510 out=0 elapsed=34.8s

  [781/17668] intraday_0781.csv.gz  in=165,998,218 out=0 elapsed=34.8s

  [782/17668] intraday_0782.csv.gz  in=166,166,029 out=0 elapsed=34.8s

  [783/17668] intraday_0783.csv.gz  in=166,322,779 out=0 elapsed=34.9s

  [784/17668] intraday_0784.csv.gz  in=166,461,856 out=0 elapsed=34.9s

  [785/17668] intraday_0785.csv.gz  in=166,594,735 out=0 elapsed=34.9s

  [786/17668] intraday_0786.csv.gz  in=166,733,614 out=0 elapsed=35.0s

  [787/17668] intraday_0789.csv.gz  in=166,797,967 out=0 elapsed=35.0s

  [788/17668] intraday_0788.csv.gz  in=166,946,735 out=0 elapsed=35.0s

  [789/17668] intraday_0787.csv.gz  in=167,078,657 out=0 elapsed=35.0s

  [790/17668] intraday_0790.csv.gz  in=167,244,773 out=0 elapsed=35.1s

  [791/17668] intraday_0791.csv.gz  in=167,405,798 out=0 elapsed=35.1s

  [792/17668] intraday_0793.csv.gz  in=167,545,130 out=0 elapsed=35.1s

  [793/17668] intraday_0792.csv.gz  in=167,710,769 out=0 elapsed=35.1s

  [794/17668] intraday_0795.csv.gz  in=167,843,169 out=0 elapsed=35.2s

  [795/17668] intraday_0794.csv.gz  in=167,993,933 out=0 elapsed=35.2s

  [796/17668] intraday_0796.csv.gz  in=168,118,552 out=0 elapsed=35.3s

  [797/17668] intraday_0797.csv.gz  in=168,273,090 out=0 elapsed=35.3s

  [798/17668] intraday_0798.csv.gz  in=168,419,998 out=0 elapsed=35.4s

  [799/17668] intraday_0800.csv.gz  in=168,564,380 out=0 elapsed=35.4s

  [800/17668] intraday_0799.csv.gz  in=168,732,695 out=0 elapsed=35.4s

  [801/17668] intraday_0801.csv.gz  in=168,875,476 out=0 elapsed=35.4s

  [802/17668] intraday_0802.csv.gz  in=169,018,762 out=0 elapsed=35.5s

  [803/17668] intraday_0804.csv.gz  in=169,159,481 out=0 elapsed=35.5s

  [804/17668] intraday_0803.csv.gz  in=169,326,594 out=0 elapsed=35.5s

  [805/17668] intraday_0805.csv.gz  in=169,500,098 out=0 elapsed=35.6s

  [806/17668] intraday_0806.csv.gz  in=169,648,754 out=0 elapsed=35.6s

  [807/17668] intraday_0807.csv.gz  in=169,786,706 out=0 elapsed=35.7s

  [808/17668] intraday_0809.csv.gz  in=169,913,759 out=0 elapsed=35.7s

  [809/17668] intraday_0808.csv.gz  in=170,069,026 out=0 elapsed=35.7s

  [810/17668] intraday_0810.csv.gz  in=170,199,485 out=0 elapsed=35.7s

  [811/17668] intraday_0813.csv.gz  in=170,302,526 out=0 elapsed=35.8s

  [812/17668] intraday_0811.csv.gz  in=170,436,393 out=0 elapsed=35.8s

  [813/17668] intraday_0812.csv.gz  in=170,569,218 out=0 elapsed=35.8s

  [814/17668] intraday_0817.csv.gz  in=170,583,417 out=0 elapsed=35.8s

  [815/17668] intraday_0816.csv.gz  in=170,622,032 out=0 elapsed=35.8s

  [816/17668] intraday_0814.csv.gz  in=170,719,341 out=0 elapsed=35.8s

  [817/17668] intraday_0819.csv.gz  in=170,731,543 out=0 elapsed=35.9s

  [818/17668] intraday_0818.csv.gz  in=170,745,538 out=0 elapsed=35.9s

  [819/17668] intraday_0820.csv.gz  in=170,761,937 out=0 elapsed=35.9s

  [820/17668] intraday_0815.csv.gz  in=170,873,117 out=0 elapsed=35.9s

  [821/17668] intraday_0822.csv.gz  in=170,887,164 out=0 elapsed=35.9s

  [822/17668] intraday_0821.csv.gz  in=170,902,088 out=0 elapsed=35.9s

  [823/17668] intraday_0823.csv.gz  in=170,912,904 out=0 elapsed=35.9s

  [824/17668] intraday_0824.csv.gz  in=170,934,292 out=0 elapsed=35.9s

  [825/17668] intraday_0825.csv.gz  in=170,951,617 out=0 elapsed=35.9s

  [826/17668] intraday_0826.csv.gz  in=170,965,004 out=0 elapsed=35.9s

  [827/17668] intraday_0827.csv.gz  in=170,974,625 out=0 elapsed=35.9s

  [828/17668] intraday_0830.csv.gz  in=170,984,779 out=0 elapsed=36.0s

  [829/17668] intraday_0829.csv.gz  in=170,998,135 out=0 elapsed=36.0s

  [830/17668] intraday_0828.csv.gz  in=171,025,124 out=0 elapsed=36.0s

  [831/17668] intraday_0831.csv.gz  in=171,034,647 out=0 elapsed=36.0s

  [832/17668] intraday_0832.csv.gz  in=171,048,427 out=0 elapsed=36.0s

  [833/17668] intraday_0835.csv.gz  in=171,059,748 out=0 elapsed=36.0s

  [834/17668] intraday_0834.csv.gz  in=171,072,575 out=0 elapsed=36.0s

  [835/17668] intraday_0833.csv.gz  in=171,085,053 out=0 elapsed=36.0s

  [836/17668] intraday_0836.csv.gz  in=171,100,482 out=0 elapsed=36.0s

  [837/17668] intraday_0839.csv.gz  in=171,112,343 out=0 elapsed=36.0s

  [838/17668] intraday_0837.csv.gz  in=171,125,104 out=0 elapsed=36.0s

  [839/17668] intraday_0838.csv.gz  in=171,138,213 out=0 elapsed=36.0s

  [840/17668] intraday_0840.csv.gz  in=171,150,913 out=0 elapsed=36.1s

  [841/17668] intraday_0841.csv.gz  in=171,171,242 out=0 elapsed=36.1s

  [842/17668] intraday_0843.csv.gz  in=171,183,510 out=0 elapsed=36.1s

  [843/17668] intraday_0842.csv.gz  in=171,194,078 out=0 elapsed=36.1s

  [844/17668] intraday_0844.csv.gz  in=171,207,678 out=0 elapsed=36.1s

  [845/17668] intraday_0845.csv.gz  in=171,222,799 out=0 elapsed=36.1s

  [846/17668] intraday_0847.csv.gz  in=171,235,133 out=0 elapsed=36.1s

  [847/17668] intraday_0846.csv.gz  in=171,249,394 out=0 elapsed=36.1s

  [848/17668] intraday_0848.csv.gz  in=171,262,538 out=0 elapsed=36.1s

  [849/17668] intraday_0849.csv.gz  in=171,275,034 out=0 elapsed=36.2s

  [850/17668] intraday_0851.csv.gz  in=171,286,602 out=0 elapsed=36.2s

  [851/17668] intraday_0850.csv.gz  in=171,299,233 out=0 elapsed=36.2s

  [852/17668] intraday_0852.csv.gz  in=171,321,977 out=0 elapsed=36.2s

  [853/17668] intraday_0853.csv.gz  in=171,333,791 out=0 elapsed=36.2s

  [854/17668] intraday_0854.csv.gz  in=171,344,863 out=0 elapsed=36.2s

  [855/17668] intraday_0855.csv.gz  in=171,367,005 out=0 elapsed=36.2s

  [856/17668] intraday_0856.csv.gz  in=171,379,672 out=0 elapsed=36.2s

  [857/17668] intraday_0857.csv.gz  in=171,392,578 out=0 elapsed=36.2s

  [858/17668] intraday_0858.csv.gz  in=171,405,058 out=0 elapsed=36.2s

  [859/17668] intraday_0859.csv.gz  in=171,419,692 out=0 elapsed=36.3s

  [860/17668] intraday_0860.csv.gz  in=171,431,803 out=0 elapsed=36.3s

  [861/17668] intraday_0861.csv.gz  in=171,443,753 out=0 elapsed=36.3s

  [862/17668] intraday_0862.csv.gz  in=171,455,819 out=0 elapsed=36.3s

  [863/17668] intraday_0863.csv.gz  in=171,468,222 out=0 elapsed=36.3s

  [864/17668] intraday_0864.csv.gz  in=171,482,017 out=0 elapsed=36.3s

  [865/17668] intraday_0865.csv.gz  in=171,498,820 out=0 elapsed=36.3s

  [866/17668] intraday_0866.csv.gz  in=171,510,495 out=0 elapsed=36.3s

  [867/17668] intraday_0868.csv.gz  in=171,520,177 out=0 elapsed=36.3s

  [868/17668] intraday_0870.csv.gz  in=171,531,938 out=0 elapsed=36.3s

  [869/17668] intraday_0869.csv.gz  in=171,544,738 out=0 elapsed=36.3s

  [870/17668] intraday_0867.csv.gz  in=171,560,121 out=0 elapsed=36.3s

  [871/17668] intraday_0871.csv.gz  in=171,570,872 out=0 elapsed=36.3s

  [872/17668] intraday_0872.csv.gz  in=171,582,750 out=0 elapsed=36.4s

  [873/17668] intraday_0873.csv.gz  in=171,595,221 out=0 elapsed=36.4s

  [874/17668] intraday_0874.csv.gz  in=171,608,084 out=0 elapsed=36.4s

  [875/17668] intraday_0875.csv.gz  in=171,620,028 out=0 elapsed=36.4s

  [876/17668] intraday_0876.csv.gz  in=171,630,652 out=0 elapsed=36.4s

  [877/17668] intraday_0877.csv.gz  in=171,640,867 out=0 elapsed=36.4s

  [878/17668] intraday_0878.csv.gz  in=171,651,507 out=0 elapsed=36.4s

  [879/17668] intraday_0879.csv.gz  in=171,664,546 out=0 elapsed=36.4s

  [880/17668] intraday_0880.csv.gz  in=171,677,195 out=0 elapsed=36.4s

  [881/17668] intraday_0881.csv.gz  in=171,692,003 out=0 elapsed=36.4s

  [882/17668] intraday_0882.csv.gz  in=171,705,429 out=0 elapsed=36.4s

  [883/17668] intraday_0883.csv.gz  in=171,716,945 out=0 elapsed=36.5s

  [884/17668] intraday_0884.csv.gz  in=171,727,599 out=0 elapsed=36.5s

  [885/17668] intraday_0885.csv.gz  in=171,739,848 out=0 elapsed=36.5s

  [886/17668] intraday_0886.csv.gz  in=171,751,580 out=0 elapsed=36.5s

  [887/17668] intraday_0887.csv.gz  in=171,764,466 out=0 elapsed=36.5s

  [888/17668] intraday_0888.csv.gz  in=171,777,220 out=0 elapsed=36.5s

  [889/17668] intraday_0891.csv.gz  in=171,789,324 out=0 elapsed=36.5s

  [890/17668] intraday_0890.csv.gz  in=171,800,600 out=0 elapsed=36.5s

  [891/17668] intraday_0889.csv.gz  in=171,812,341 out=0 elapsed=36.5s

  [892/17668] intraday_0892.csv.gz  in=171,823,805 out=0 elapsed=36.6s

  [893/17668] intraday_0893.csv.gz  in=171,834,942 out=0 elapsed=36.6s

  [894/17668] intraday_0894.csv.gz  in=171,844,703 out=0 elapsed=36.6s

  [895/17668] intraday_0895.csv.gz  in=171,855,495 out=0 elapsed=36.6s

  [896/17668] intraday_0896.csv.gz  in=171,866,627 out=0 elapsed=36.6s

  [897/17668] intraday_0899.csv.gz  in=171,877,805 out=0 elapsed=36.6s

  [898/17668] intraday_0897.csv.gz  in=171,893,861 out=0 elapsed=36.6s

  [899/17668] intraday_0900.csv.gz  in=171,905,564 out=0 elapsed=36.6s

  [900/17668] intraday_0898.csv.gz  in=171,918,523 out=0 elapsed=36.6s

  [901/17668] intraday_0901.csv.gz  in=171,931,030 out=0 elapsed=36.6s

  [902/17668] intraday_0904.csv.gz  in=171,943,471 out=0 elapsed=36.6s

  [903/17668] intraday_0902.csv.gz  in=171,956,075 out=0 elapsed=36.6s

  [904/17668] intraday_0905.csv.gz  in=171,970,659 out=0 elapsed=36.6s

  [905/17668] intraday_0903.csv.gz  in=171,985,253 out=0 elapsed=36.6s

  [906/17668] intraday_0907.csv.gz  in=171,997,646 out=0 elapsed=36.7s

  [907/17668] intraday_0909.csv.gz  in=172,010,099 out=0 elapsed=36.7s

  [908/17668] intraday_0908.csv.gz  in=172,023,330 out=0 elapsed=36.7s

  [909/17668] intraday_0906.csv.gz  in=172,037,663 out=0 elapsed=36.7s

  [910/17668] intraday_0910.csv.gz  in=172,050,205 out=0 elapsed=36.7s

  [911/17668] intraday_0912.csv.gz  in=172,061,924 out=0 elapsed=36.7s

  [912/17668] intraday_0913.csv.gz  in=172,075,072 out=0 elapsed=36.7s

  [913/17668] intraday_0914.csv.gz  in=172,086,374 out=0 elapsed=36.7s

  [914/17668] intraday_0911.csv.gz  in=172,098,538 out=0 elapsed=36.7s

  [915/17668] intraday_0915.csv.gz  in=172,110,713 out=0 elapsed=36.8s

  [916/17668] intraday_0916.csv.gz  in=172,121,855 out=0 elapsed=36.8s

  [917/17668] intraday_0917.csv.gz  in=172,134,361 out=0 elapsed=36.8s

  [918/17668] intraday_0918.csv.gz  in=172,146,865 out=0 elapsed=36.8s

  [919/17668] intraday_0919.csv.gz  in=172,158,436 out=0 elapsed=36.8s

  [920/17668] intraday_0920.csv.gz  in=172,171,440 out=0 elapsed=36.8s

  [921/17668] intraday_0921.csv.gz  in=172,185,852 out=0 elapsed=36.8s

  [922/17668] intraday_0922.csv.gz  in=172,198,803 out=0 elapsed=36.8s

  [923/17668] intraday_0924.csv.gz  in=172,211,447 out=0 elapsed=36.8s

  [924/17668] intraday_0923.csv.gz  in=172,222,572 out=0 elapsed=36.8s

  [925/17668] intraday_0925.csv.gz  in=172,236,557 out=0 elapsed=36.9s

  [926/17668] intraday_0928.csv.gz  in=172,250,216 out=0 elapsed=36.9s

  [927/17668] intraday_0926.csv.gz  in=172,262,535 out=0 elapsed=36.9s

  [928/17668] intraday_0927.csv.gz  in=172,274,527 out=0 elapsed=36.9s

  [929/17668] intraday_0929.csv.gz  in=172,288,263 out=0 elapsed=36.9s

  [930/17668] intraday_0930.csv.gz  in=172,300,820 out=0 elapsed=36.9s

  [931/17668] intraday_0932.csv.gz  in=172,313,987 out=0 elapsed=36.9s

  [932/17668] intraday_0931.csv.gz  in=172,327,186 out=0 elapsed=36.9s

  [933/17668] intraday_0933.csv.gz  in=172,337,937 out=0 elapsed=36.9s

  [934/17668] intraday_0935.csv.gz  in=172,352,351 out=0 elapsed=36.9s

  [935/17668] intraday_0934.csv.gz  in=172,363,031 out=0 elapsed=36.9s

  [936/17668] intraday_0936.csv.gz  in=172,375,984 out=0 elapsed=36.9s

  [937/17668] intraday_0937.csv.gz  in=172,391,434 out=0 elapsed=37.0s

  [938/17668] intraday_0938.csv.gz  in=172,403,487 out=0 elapsed=37.0s

  [939/17668] intraday_0940.csv.gz  in=172,415,056 out=0 elapsed=37.0s

  [940/17668] intraday_0939.csv.gz  in=172,428,760 out=0 elapsed=37.0s

  [941/17668] intraday_0942.csv.gz  in=172,443,152 out=0 elapsed=37.0s

  [942/17668] intraday_0941.csv.gz  in=172,456,071 out=0 elapsed=37.0s

  [943/17668] intraday_0944.csv.gz  in=172,470,100 out=0 elapsed=37.0s

  [944/17668] intraday_0943.csv.gz  in=172,491,366 out=0 elapsed=37.0s

  [945/17668] intraday_0946.csv.gz  in=172,505,217 out=0 elapsed=37.0s

  [946/17668] intraday_0945.csv.gz  in=172,517,214 out=0 elapsed=37.1s

  [947/17668] intraday_0947.csv.gz  in=172,527,681 out=0 elapsed=37.1s

  [948/17668] intraday_0950.csv.gz  in=172,539,547 out=0 elapsed=37.1s

  [949/17668] intraday_0949.csv.gz  in=172,551,538 out=0 elapsed=37.1s

  [950/17668] intraday_0948.csv.gz  in=172,563,487 out=0 elapsed=37.1s

  [951/17668] intraday_0951.csv.gz  in=172,571,876 out=0 elapsed=37.1s

  [952/17668] intraday_0953.csv.gz  in=172,583,445 out=0 elapsed=37.1s

  [953/17668] intraday_0952.csv.gz  in=172,591,936 out=0 elapsed=37.1s

  [954/17668] intraday_0954.csv.gz  in=172,594,176 out=0 elapsed=37.1s

  [955/17668] intraday_0955.csv.gz  in=172,609,257 out=0 elapsed=37.1s

  [956/17668] intraday_0956.csv.gz  in=172,623,524 out=0 elapsed=37.1s

  [957/17668] intraday_0957.csv.gz  in=172,635,211 out=0 elapsed=37.2s

  [958/17668] intraday_0958.csv.gz  in=172,657,646 out=0 elapsed=37.2s

  [959/17668] intraday_0959.csv.gz  in=172,672,377 out=0 elapsed=37.2s

  [960/17668] intraday_0960.csv.gz  in=172,686,888 out=0 elapsed=37.2s

  [961/17668] intraday_0961.csv.gz  in=172,703,954 out=0 elapsed=37.2s

  [962/17668] intraday_0962.csv.gz  in=172,716,282 out=0 elapsed=37.2s

  [963/17668] intraday_0963.csv.gz  in=172,729,667 out=0 elapsed=37.2s

  [964/17668] intraday_0964.csv.gz  in=172,744,539 out=0 elapsed=37.2s

  [965/17668] intraday_0965.csv.gz  in=172,758,327 out=0 elapsed=37.2s

  [966/17668] intraday_0968.csv.gz  in=172,770,498 out=0 elapsed=37.3s

  [967/17668] intraday_0966.csv.gz  in=172,792,608 out=0 elapsed=37.3s

  [968/17668] intraday_0967.csv.gz  in=172,806,586 out=0 elapsed=37.3s

  [969/17668] intraday_0969.csv.gz  in=172,816,729 out=0 elapsed=37.3s

  [970/17668] intraday_0971.csv.gz  in=172,828,749 out=0 elapsed=37.3s

  [971/17668] intraday_0972.csv.gz  in=172,842,226 out=0 elapsed=37.3s

  [972/17668] intraday_0970.csv.gz  in=172,856,089 out=0 elapsed=37.3s

  [973/17668] intraday_0973.csv.gz  in=172,876,609 out=0 elapsed=37.3s

  [974/17668] intraday_0976.csv.gz  in=172,888,906 out=0 elapsed=37.3s

  [975/17668] intraday_0977.csv.gz  in=172,900,830 out=0 elapsed=37.3s

  [976/17668] intraday_0974.csv.gz  in=172,912,465 out=0 elapsed=37.4s

  [977/17668] intraday_0975.csv.gz  in=172,937,964 out=0 elapsed=37.4s

  [978/17668] intraday_0978.csv.gz  in=172,951,142 out=0 elapsed=37.4s

  [979/17668] intraday_0981.csv.gz  in=172,964,273 out=0 elapsed=37.4s

  [980/17668] intraday_0980.csv.gz  in=172,975,120 out=0 elapsed=37.4s

  [981/17668] intraday_0982.csv.gz  in=172,988,287 out=0 elapsed=37.4s

  [982/17668] intraday_0984.csv.gz  in=173,002,938 out=0 elapsed=37.4s

  [983/17668] intraday_0979.csv.gz  in=173,051,841 out=0 elapsed=37.4s

  [984/17668] intraday_0983.csv.gz  in=173,067,616 out=0 elapsed=37.4s

  [985/17668] intraday_0985.csv.gz  in=173,080,108 out=0 elapsed=37.4s

  [986/17668] intraday_0986.csv.gz  in=173,092,348 out=0 elapsed=37.4s

  [987/17668] intraday_0988.csv.gz  in=173,105,709 out=0 elapsed=37.5s

  [988/17668] intraday_0989.csv.gz  in=173,117,385 out=0 elapsed=37.5s

  [989/17668] intraday_0990.csv.gz  in=173,129,002 out=0 elapsed=37.5s

  [990/17668] intraday_0987.csv.gz  in=173,161,035 out=0 elapsed=37.5s

  [991/17668] intraday_0992.csv.gz  in=173,171,820 out=0 elapsed=37.5s

  [992/17668] intraday_0993.csv.gz  in=173,183,210 out=0 elapsed=37.5s

  [993/17668] intraday_0991.csv.gz  in=173,196,319 out=0 elapsed=37.5s

  [994/17668] intraday_0994.csv.gz  in=173,210,070 out=0 elapsed=37.5s

  [995/17668] intraday_0998.csv.gz  in=173,220,967 out=0 elapsed=37.5s

  [996/17668] intraday_0995.csv.gz  in=173,232,895 out=0 elapsed=37.5s

  [997/17668] intraday_0996.csv.gz  in=173,246,623 out=0 elapsed=37.5s

  [998/17668] intraday_0997.csv.gz  in=173,262,519 out=0 elapsed=37.5s

  [999/17668] intraday_0999.csv.gz  in=173,274,768 out=0 elapsed=37.6s

  [1000/17668] intraday_1000.csv.gz  in=173,287,073 out=0 elapsed=37.6s

  [1001/17668] intraday_10000.csv.gz  in=173,298,407 out=10,638 elapsed=37.6s

  [1002/17668] intraday_10001.csv.gz  in=173,312,102 out=24,333 elapsed=37.6s

  [1003/17668] intraday_10002.csv.gz  in=173,324,401 out=36,632 elapsed=37.6s

  [1004/17668] intraday_10003.csv.gz  in=173,337,308 out=49,539 elapsed=37.6s

  [1005/17668] intraday_10004.csv.gz  in=173,354,361 out=66,491 elapsed=37.7s

  [1006/17668] intraday_10005.csv.gz  in=173,368,716 out=80,846 elapsed=37.7s

  [1007/17668] intraday_10006.csv.gz  in=173,387,818 out=99,948 elapsed=37.7s

  [1008/17668] intraday_10007.csv.gz  in=173,403,189 out=115,319 elapsed=37.7s

  [1009/17668] intraday_10009.csv.gz  in=173,416,053 out=128,183 elapsed=37.7s

  [1010/17668] intraday_10008.csv.gz  in=173,429,708 out=141,838 elapsed=37.7s

  [1011/17668] intraday_1001.csv.gz  in=173,445,201 out=141,838 elapsed=37.7s

  [1012/17668] intraday_10010.csv.gz  in=173,457,751 out=154,388 elapsed=37.8s

  [1013/17668] intraday_10011.csv.gz  in=173,468,274 out=164,911 elapsed=37.8s

  [1014/17668] intraday_10012.csv.gz  in=173,481,818 out=178,455 elapsed=37.8s

  [1015/17668] intraday_10013.csv.gz  in=173,492,257 out=188,894 elapsed=37.8s

  [1016/17668] intraday_10014.csv.gz  in=173,506,755 out=203,392 elapsed=37.8s

  [1017/17668] intraday_10017.csv.gz  in=173,517,983 out=214,620 elapsed=37.8s

  [1018/17668] intraday_10015.csv.gz  in=173,531,861 out=228,498 elapsed=37.8s

  [1019/17668] intraday_10016.csv.gz  in=173,548,138 out=244,775 elapsed=37.8s

  [1020/17668] intraday_10018.csv.gz  in=173,559,020 out=255,657 elapsed=37.8s

  [1021/17668] intraday_1002.csv.gz  in=173,571,034 out=255,657 elapsed=37.9s

  [1022/17668] intraday_10019.csv.gz  in=173,584,284 out=268,883 elapsed=37.9s

  [1023/17668] intraday_10021.csv.gz  in=173,594,676 out=279,275 elapsed=37.9s

  [1024/17668] intraday_10020.csv.gz  in=173,606,839 out=291,438 elapsed=37.9s

  [1025/17668] intraday_10023.csv.gz  in=173,621,192 out=305,791 elapsed=37.9s

  [1026/17668] intraday_10022.csv.gz  in=173,636,830 out=321,429 elapsed=37.9s

  [1027/17668] intraday_10024.csv.gz  in=173,650,340 out=334,939 elapsed=37.9s

  [1028/17668] intraday_10025.csv.gz  in=173,666,792 out=351,391 elapsed=37.9s

  [1029/17668] intraday_10028.csv.gz  in=173,679,738 out=364,337 elapsed=38.0s

  [1030/17668] intraday_10027.csv.gz  in=173,690,976 out=375,575 elapsed=38.0s

  [1031/17668] intraday_10029.csv.gz  in=173,701,949 out=386,548 elapsed=38.0s

  [1032/17668] intraday_10026.csv.gz  in=173,713,343 out=397,942 elapsed=38.0s

  [1033/17668] intraday_1003.csv.gz  in=173,724,417 out=397,942 elapsed=38.0s

  [1034/17668] intraday_10031.csv.gz  in=173,732,382 out=405,172 elapsed=38.0s

  [1035/17668] intraday_10030.csv.gz  in=173,745,417 out=418,207 elapsed=38.0s

  [1036/17668] intraday_10032.csv.gz  in=173,756,598 out=429,388 elapsed=38.1s

  [1037/17668] intraday_10033.csv.gz  in=173,765,209 out=437,999 elapsed=38.1s

  [1038/17668] intraday_10034.csv.gz  in=173,779,993 out=452,783 elapsed=38.1s

  [1039/17668] intraday_10035.csv.gz  in=173,791,702 out=464,481 elapsed=38.1s

  [1040/17668] intraday_10036.csv.gz  in=173,803,469 out=476,248 elapsed=38.1s

  [1041/17668] intraday_10037.csv.gz  in=173,813,914 out=486,693 elapsed=38.1s

  [1042/17668] intraday_10038.csv.gz  in=173,825,913 out=498,692 elapsed=38.1s

  [1043/17668] intraday_1004.csv.gz  in=173,840,091 out=498,692 elapsed=38.1s

  [1044/17668] intraday_10039.csv.gz  in=173,855,224 out=513,825 elapsed=38.1s

  [1045/17668] intraday_10041.csv.gz  in=173,866,003 out=524,604 elapsed=38.2s

  [1046/17668] intraday_10040.csv.gz  in=173,880,973 out=539,574 elapsed=38.2s

  [1047/17668] intraday_10043.csv.gz  in=173,895,538 out=554,139 elapsed=38.2s

  [1048/17668] intraday_10042.csv.gz  in=173,909,948 out=566,021 elapsed=38.2s

  [1049/17668] intraday_10044.csv.gz  in=173,922,978 out=579,051 elapsed=38.2s

  [1050/17668] intraday_10045.csv.gz  in=173,934,968 out=591,041 elapsed=38.2s

  [1051/17668] intraday_10046.csv.gz  in=173,948,577 out=604,650 elapsed=38.2s

  [1052/17668] intraday_10047.csv.gz  in=173,961,864 out=617,937 elapsed=38.2s

  [1053/17668] intraday_10048.csv.gz  in=173,972,289 out=628,362 elapsed=38.3s

  [1054/17668] intraday_10049.csv.gz  in=173,983,878 out=639,951 elapsed=38.3s

  [1055/17668] intraday_1005.csv.gz  in=173,996,009 out=639,951 elapsed=38.3s

  [1056/17668] intraday_10050.csv.gz  in=174,007,014 out=650,956 elapsed=38.3s

  [1057/17668] intraday_10053.csv.gz  in=174,017,820 out=661,762 elapsed=38.3s

  [1058/17668] intraday_10052.csv.gz  in=174,028,703 out=672,645 elapsed=38.3s

  [1059/17668] intraday_10051.csv.gz  in=174,044,240 out=688,182 elapsed=38.3s

  [1060/17668] intraday_10054.csv.gz  in=174,056,999 out=700,941 elapsed=38.3s

  [1061/17668] intraday_10055.csv.gz  in=174,070,268 out=714,210 elapsed=38.4s

  [1062/17668] intraday_10056.csv.gz  in=174,084,047 out=727,989 elapsed=38.4s

  [1063/17668] intraday_10057.csv.gz  in=174,096,010 out=739,952 elapsed=38.4s

  [1064/17668] intraday_10058.csv.gz  in=174,110,134 out=754,076 elapsed=38.4s

  [1065/17668] intraday_10059.csv.gz  in=174,124,151 out=766,170 elapsed=38.4s

  [1066/17668] intraday_1006.csv.gz  in=174,135,744 out=766,170 elapsed=38.4s

  [1067/17668] intraday_10060.csv.gz  in=174,147,864 out=778,290 elapsed=38.4s

  [1068/17668] intraday_10061.csv.gz  in=174,159,004 out=789,430 elapsed=38.4s

  [1069/17668] intraday_10062.csv.gz  in=174,169,216 out=799,642 elapsed=38.4s

  [1070/17668] intraday_10063.csv.gz  in=174,182,840 out=813,266 elapsed=38.4s

  [1071/17668] intraday_10064.csv.gz  in=174,196,788 out=827,214 elapsed=38.5s

  [1072/17668] intraday_10066.csv.gz  in=174,214,169 out=838,737 elapsed=38.5s

  [1073/17668] intraday_10065.csv.gz  in=174,228,926 out=853,494 elapsed=38.5s

  [1074/17668] intraday_10067.csv.gz  in=174,240,135 out=864,703 elapsed=38.5s

  [1075/17668] intraday_10068.csv.gz  in=174,251,887 out=876,455 elapsed=38.5s

  [1076/17668] intraday_1007.csv.gz  in=174,263,628 out=876,455 elapsed=38.6s

  [1077/17668] intraday_10069.csv.gz  in=174,277,560 out=890,387 elapsed=38.6s

  [1078/17668] intraday_10070.csv.gz  in=174,288,874 out=901,701 elapsed=38.6s

  [1079/17668] intraday_10071.csv.gz  in=174,302,221 out=915,048 elapsed=38.6s

  [1080/17668] intraday_10072.csv.gz  in=174,313,102 out=925,929 elapsed=38.6s

  [1081/17668] intraday_10073.csv.gz  in=174,325,425 out=938,252 elapsed=38.6s

  [1082/17668] intraday_10074.csv.gz  in=174,337,182 out=950,009 elapsed=38.6s

  [1083/17668] intraday_10075.csv.gz  in=174,349,131 out=961,958 elapsed=38.6s

  [1084/17668] intraday_10076.csv.gz  in=174,361,949 out=974,776 elapsed=38.7s

  [1085/17668] intraday_10078.csv.gz  in=174,374,173 out=987,000 elapsed=38.7s

  [1086/17668] intraday_10077.csv.gz  in=174,386,686 out=999,513 elapsed=38.7s

  [1087/17668] intraday_10079.csv.gz  in=174,400,188 out=1,013,015 elapsed=38.7s

  [1088/17668] intraday_1008.csv.gz  in=174,412,772 out=1,013,015 elapsed=38.7s

  [1089/17668] intraday_10080.csv.gz  in=174,424,526 out=1,024,769 elapsed=38.7s

  [1090/17668] intraday_10081.csv.gz  in=174,435,760 out=1,036,003 elapsed=38.7s

  [1091/17668] intraday_10082.csv.gz  in=174,448,352 out=1,048,595 elapsed=38.7s

  [1092/17668] intraday_10083.csv.gz  in=174,459,564 out=1,059,807 elapsed=38.7s

  [1093/17668] intraday_10084.csv.gz  in=174,470,737 out=1,070,980 elapsed=38.8s

  [1094/17668] intraday_10085.csv.gz  in=174,482,074 out=1,082,317 elapsed=38.8s

  [1095/17668] intraday_10086.csv.gz  in=174,495,205 out=1,094,172 elapsed=38.8s

  [1096/17668] intraday_10087.csv.gz  in=174,507,203 out=1,105,768 elapsed=38.8s

  [1097/17668] intraday_10088.csv.gz  in=174,523,964 out=1,119,156 elapsed=38.8s

  [1098/17668] intraday_10089.csv.gz  in=174,535,717 out=1,130,909 elapsed=38.8s

  [1099/17668] intraday_1009.csv.gz  in=174,548,204 out=1,130,909 elapsed=38.8s

  [1100/17668] intraday_10090.csv.gz  in=174,560,505 out=1,143,210 elapsed=38.8s

  [1101/17668] intraday_10092.csv.gz  in=174,572,076 out=1,154,781 elapsed=38.9s

  [1102/17668] intraday_10091.csv.gz  in=174,591,151 out=1,168,631 elapsed=38.9s

  [1103/17668] intraday_10093.csv.gz  in=174,602,807 out=1,180,287 elapsed=38.9s

  [1104/17668] intraday_10094.csv.gz  in=174,615,731 out=1,192,248 elapsed=38.9s

  [1105/17668] intraday_10095.csv.gz  in=174,627,995 out=1,204,512 elapsed=38.9s

  [1106/17668] intraday_10096.csv.gz  in=174,639,992 out=1,216,509 elapsed=38.9s

  [1107/17668] intraday_10097.csv.gz  in=174,652,795 out=1,229,312 elapsed=38.9s

  [1108/17668] intraday_10098.csv.gz  in=174,664,516 out=1,241,033 elapsed=38.9s

  [1109/17668] intraday_10099.csv.gz  in=174,674,900 out=1,251,417 elapsed=39.0s

  [1110/17668] intraday_1010.csv.gz  in=174,686,259 out=1,251,417 elapsed=39.0s

  [1111/17668] intraday_10100.csv.gz  in=174,701,061 out=1,266,219 elapsed=39.0s

  [1112/17668] intraday_10103.csv.gz  in=174,718,038 out=1,280,483 elapsed=39.0s

  [1113/17668] intraday_10101.csv.gz  in=174,729,948 out=1,292,393 elapsed=39.0s

  [1114/17668] intraday_10102.csv.gz  in=174,744,186 out=1,306,626 elapsed=39.0s

  [1115/17668] intraday_10104.csv.gz  in=174,757,104 out=1,319,544 elapsed=39.0s

  [1116/17668] intraday_10106.csv.gz  in=174,769,649 out=1,332,089 elapsed=39.1s

  [1117/17668] intraday_10105.csv.gz  in=174,779,150 out=1,341,590 elapsed=39.1s

  [1118/17668] intraday_10107.csv.gz  in=174,791,625 out=1,354,065 elapsed=39.1s

  [1119/17668] intraday_10108.csv.gz  in=174,805,362 out=1,367,802 elapsed=39.1s

  [1120/17668] intraday_10109.csv.gz  in=174,818,895 out=1,381,335 elapsed=39.1s

  [1121/17668] intraday_1011.csv.gz  in=174,832,910 out=1,381,335 elapsed=39.1s

  [1122/17668] intraday_10111.csv.gz  in=174,843,441 out=1,391,866 elapsed=39.1s

  [1123/17668] intraday_10110.csv.gz  in=174,856,747 out=1,405,172 elapsed=39.1s

  [1124/17668] intraday_10113.csv.gz  in=174,867,890 out=1,416,315 elapsed=39.2s

  [1125/17668] intraday_10114.csv.gz  in=174,879,822 out=1,428,247 elapsed=39.2s

  [1126/17668] intraday_10112.csv.gz  in=174,892,709 out=1,441,134 elapsed=39.2s

  [1127/17668] intraday_10115.csv.gz  in=174,904,120 out=1,452,545 elapsed=39.2s

  [1128/17668] intraday_10116.csv.gz  in=174,913,540 out=1,461,965 elapsed=39.2s

  [1129/17668] intraday_10117.csv.gz  in=174,924,577 out=1,473,002 elapsed=39.2s

  [1130/17668] intraday_10118.csv.gz  in=174,937,686 out=1,486,111 elapsed=39.2s

  [1131/17668] intraday_10119.csv.gz  in=174,955,152 out=1,503,577 elapsed=39.2s

  [1132/17668] intraday_1012.csv.gz  in=174,967,732 out=1,503,577 elapsed=39.2s

  [1133/17668] intraday_10120.csv.gz  in=174,980,833 out=1,516,678 elapsed=39.3s

  [1134/17668] intraday_10121.csv.gz  in=174,993,414 out=1,529,259 elapsed=39.3s

  [1135/17668] intraday_10123.csv.gz  in=175,008,341 out=1,544,186 elapsed=39.3s

  [1136/17668] intraday_10122.csv.gz  in=175,023,118 out=1,555,644 elapsed=39.3s

  [1137/17668] intraday_10124.csv.gz  in=175,035,241 out=1,567,767 elapsed=39.3s

  [1138/17668] intraday_10125.csv.gz  in=175,050,846 out=1,583,372 elapsed=39.3s

  [1139/17668] intraday_10126.csv.gz  in=175,061,503 out=1,594,029 elapsed=39.3s

  [1140/17668] intraday_10128.csv.gz  in=175,074,870 out=1,607,376 elapsed=39.3s

  [1141/17668] intraday_10127.csv.gz  in=175,086,727 out=1,619,233 elapsed=39.4s

  [1142/17668] intraday_1013.csv.gz  in=175,098,511 out=1,619,233 elapsed=39.4s

  [1143/17668] intraday_10129.csv.gz  in=175,111,971 out=1,632,693 elapsed=39.4s

  [1144/17668] intraday_10130.csv.gz  in=175,124,483 out=1,645,205 elapsed=39.4s

  [1145/17668] intraday_10131.csv.gz  in=175,136,810 out=1,657,532 elapsed=39.4s

  [1146/17668] intraday_10132.csv.gz  in=175,149,729 out=1,670,451 elapsed=39.4s

  [1147/17668] intraday_10133.csv.gz  in=175,161,959 out=1,682,681 elapsed=39.4s

  [1148/17668] intraday_10135.csv.gz  in=175,174,477 out=1,695,199 elapsed=39.5s

  [1149/17668] intraday_10134.csv.gz  in=175,187,272 out=1,707,994 elapsed=39.5s

  [1150/17668] intraday_10137.csv.gz  in=175,199,744 out=1,720,466 elapsed=39.5s

  [1151/17668] intraday_10136.csv.gz  in=175,210,624 out=1,731,346 elapsed=39.5s

  [1152/17668] intraday_10138.csv.gz  in=175,224,341 out=1,745,063 elapsed=39.5s

  [1153/17668] intraday_10139.csv.gz  in=175,238,312 out=1,759,034 elapsed=39.5s

  [1154/17668] intraday_1014.csv.gz  in=175,250,734 out=1,759,034 elapsed=39.5s

  [1155/17668] intraday_10140.csv.gz  in=175,263,520 out=1,771,820 elapsed=39.5s

  [1156/17668] intraday_10141.csv.gz  in=175,274,722 out=1,783,022 elapsed=39.5s

  [1157/17668] intraday_10143.csv.gz  in=175,287,441 out=1,795,741 elapsed=39.6s

  [1158/17668] intraday_10142.csv.gz  in=175,302,143 out=1,810,443 elapsed=39.6s

  [1159/17668] intraday_10144.csv.gz  in=175,304,744 out=1,813,044 elapsed=39.6s

  [1160/17668] intraday_10146.csv.gz  in=175,385,002 out=1,893,302 elapsed=39.8s

  [1161/17668] intraday_10145.csv.gz  in=175,488,143 out=1,996,443 elapsed=39.8s

  [1162/17668] intraday_10148.csv.gz  in=175,556,139 out=2,064,439 elapsed=39.8s

  [1163/17668] intraday_10147.csv.gz  in=175,646,836 out=2,155,136 elapsed=39.8s

  [1164/17668] intraday_1015.csv.gz  in=175,658,448 out=2,155,136 elapsed=39.8s

  [1165/17668] intraday_10149.csv.gz  in=175,742,690 out=2,239,378 elapsed=39.9s

  [1166/17668] intraday_10150.csv.gz  in=175,837,504 out=2,334,192 elapsed=39.9s

  [1167/17668] intraday_10152.csv.gz  in=175,919,447 out=2,416,135 elapsed=40.0s

  [1168/17668] intraday_10151.csv.gz  in=176,024,115 out=2,520,803 elapsed=40.0s

  [1169/17668] intraday_10153.csv.gz  in=176,106,851 out=2,603,539 elapsed=40.0s

  [1170/17668] intraday_10154.csv.gz  in=176,202,640 out=2,699,137 elapsed=40.1s

  [1171/17668] intraday_10155.csv.gz  in=176,291,780 out=2,788,277 elapsed=40.1s

  [1172/17668] intraday_10156.csv.gz  in=176,368,566 out=2,865,063 elapsed=40.1s

  [1173/17668] intraday_1016.csv.gz  in=176,378,774 out=2,865,063 elapsed=40.1s

  [1174/17668] intraday_10157.csv.gz  in=176,486,272 out=2,964,948 elapsed=40.2s

  [1175/17668] intraday_10159.csv.gz  in=176,565,652 out=3,044,169 elapsed=40.3s

  [1176/17668] intraday_10160.csv.gz  in=176,643,143 out=3,121,660 elapsed=40.3s

  [1177/17668] intraday_10158.csv.gz  in=176,745,607 out=3,217,199 elapsed=40.3s

  [1178/17668] intraday_10161.csv.gz  in=176,836,371 out=3,302,113 elapsed=40.3s

  [1179/17668] intraday_10162.csv.gz  in=176,935,275 out=3,401,017 elapsed=40.5s

  [1180/17668] intraday_10163.csv.gz  in=177,018,870 out=3,484,612 elapsed=40.5s

  [1181/17668] intraday_10164.csv.gz  in=177,097,805 out=3,563,547 elapsed=40.5s

  [1182/17668] intraday_10165.csv.gz  in=177,173,337 out=3,639,079 elapsed=40.5s

  [1183/17668] intraday_10167.csv.gz  in=177,262,478 out=3,728,011 elapsed=40.6s

  [1184/17668] intraday_10169.csv.gz  in=177,353,990 out=3,817,744 elapsed=40.7s

  [1185/17668] intraday_1017.csv.gz  in=177,368,210 out=3,817,744 elapsed=40.7s

  [1186/17668] intraday_10168.csv.gz  in=177,458,354 out=3,907,877 elapsed=40.7s

  [1187/17668] intraday_10166.csv.gz  in=177,556,583 out=4,006,106 elapsed=40.7s

  [1188/17668] intraday_10173.csv.gz  in=177,626,194 out=4,075,717 elapsed=40.9s

  [1189/17668] intraday_10172.csv.gz  in=177,712,425 out=4,161,270 elapsed=40.9s

  [1190/17668] intraday_10170.csv.gz  in=177,796,337 out=4,245,182 elapsed=40.9s

  [1191/17668] intraday_10171.csv.gz  in=177,892,985 out=4,331,713 elapsed=40.9s

  [1192/17668] intraday_10174.csv.gz  in=177,987,050 out=4,425,777 elapsed=41.0s

  [1193/17668] intraday_10177.csv.gz  in=178,060,406 out=4,496,404 elapsed=41.0s

  [1194/17668] intraday_10176.csv.gz  in=178,158,363 out=4,594,361 elapsed=41.0s

  [1195/17668] intraday_1018.csv.gz  in=178,169,747 out=4,594,361 elapsed=41.1s

  [1196/17668] intraday_10175.csv.gz  in=178,284,746 out=4,709,360 elapsed=41.1s

  [1197/17668] intraday_10179.csv.gz  in=178,369,299 out=4,793,913 elapsed=41.1s

  [1198/17668] intraday_10178.csv.gz  in=178,443,812 out=4,868,376 elapsed=41.2s

  [1199/17668] intraday_10180.csv.gz  in=178,531,134 out=4,955,698 elapsed=41.2s

  [1200/17668] intraday_10181.csv.gz  in=178,609,433 out=5,033,997 elapsed=41.3s

  [1201/17668] intraday_10182.csv.gz  in=178,706,787 out=5,126,805 elapsed=41.3s

  [1202/17668] intraday_10183.csv.gz  in=178,782,131 out=5,202,149 elapsed=41.4s

  [1203/17668] intraday_10185.csv.gz  in=178,867,029 out=5,279,803 elapsed=41.4s

  [1204/17668] intraday_10184.csv.gz  in=178,941,200 out=5,353,974 elapsed=41.4s

  [1205/17668] intraday_10186.csv.gz  in=179,030,280 out=5,441,608 elapsed=41.4s

  [1206/17668] intraday_1019.csv.gz  in=179,044,194 out=5,441,608 elapsed=41.5s

  [1207/17668] intraday_10187.csv.gz  in=179,132,835 out=5,528,305 elapsed=41.6s

  [1208/17668] intraday_10189.csv.gz  in=179,223,820 out=5,619,290 elapsed=41.6s

  [1209/17668] intraday_10188.csv.gz  in=179,306,094 out=5,701,564 elapsed=41.6s

  [1210/17668] intraday_10190.csv.gz  in=179,404,199 out=5,799,669 elapsed=41.7s

  [1211/17668] intraday_10191.csv.gz  in=179,477,175 out=5,872,645 elapsed=41.7s

  [1212/17668] intraday_10193.csv.gz  in=179,560,022 out=5,955,492 elapsed=41.8s

  [1213/17668] intraday_10192.csv.gz  in=179,641,608 out=6,037,078 elapsed=41.8s

  [1214/17668] intraday_10194.csv.gz  in=179,714,178 out=6,109,648 elapsed=41.8s

  [1215/17668] intraday_10195.csv.gz  in=179,797,092 out=6,192,562 elapsed=41.8s

  [1216/17668] intraday_10196.csv.gz  in=179,873,334 out=6,268,804 elapsed=41.9s

  [1217/17668] intraday_1020.csv.gz  in=179,886,710 out=6,268,804 elapsed=41.9s

  [1218/17668] intraday_10197.csv.gz  in=179,967,131 out=6,342,165 elapsed=41.9s

  [1219/17668] intraday_10199.csv.gz  in=180,045,985 out=6,421,019 elapsed=42.0s

  [1220/17668] intraday_10198.csv.gz  in=180,141,936 out=6,514,434 elapsed=42.0s

  [1221/17668] intraday_10200.csv.gz  in=180,219,078 out=6,591,576 elapsed=42.0s

  [1222/17668] intraday_10201.csv.gz  in=180,320,540 out=6,693,038 elapsed=42.0s

  [1223/17668] intraday_10204.csv.gz  in=180,397,846 out=6,770,098 elapsed=42.1s

  [1224/17668] intraday_10202.csv.gz  in=180,481,986 out=6,854,238 elapsed=42.1s

  [1225/17668] intraday_10203.csv.gz  in=180,560,584 out=6,932,145 elapsed=42.1s

  [1226/17668] intraday_10205.csv.gz  in=180,648,610 out=7,020,171 elapsed=42.2s

  [1227/17668] intraday_10206.csv.gz  in=180,725,971 out=7,097,231 elapsed=42.2s

  [1228/17668] intraday_10207.csv.gz  in=180,799,011 out=7,170,271 elapsed=42.2s

  [1229/17668] intraday_1021.csv.gz  in=180,812,113 out=7,170,271 elapsed=42.2s

  [1230/17668] intraday_10208.csv.gz  in=180,899,720 out=7,257,878 elapsed=42.3s

  [1231/17668] intraday_10209.csv.gz  in=180,978,301 out=7,336,223 elapsed=42.3s

  [1232/17668] intraday_10210.csv.gz  in=181,052,594 out=7,410,516 elapsed=42.3s

  [1233/17668] intraday_10211.csv.gz  in=181,167,961 out=7,525,883 elapsed=42.4s

  [1234/17668] intraday_10212.csv.gz  in=181,261,979 out=7,619,287 elapsed=42.5s

  [1235/17668] intraday_10214.csv.gz  in=181,341,598 out=7,698,819 elapsed=42.5s

  [1236/17668] intraday_10213.csv.gz  in=181,443,640 out=7,800,861 elapsed=42.5s

  [1237/17668] intraday_10215.csv.gz  in=181,538,956 out=7,894,219 elapsed=42.5s

  [1238/17668] intraday_10218.csv.gz  in=181,620,140 out=7,975,403 elapsed=42.7s

  [1239/17668] intraday_10216.csv.gz  in=181,692,504 out=8,045,629 elapsed=42.7s

  [1240/17668] intraday_10217.csv.gz  in=181,785,178 out=8,138,303 elapsed=42.7s

  [1241/17668] intraday_10219.csv.gz  in=181,875,893 out=8,229,018 elapsed=42.7s

  [1242/17668] intraday_1022.csv.gz  in=181,886,623 out=8,229,018 elapsed=42.7s

  [1243/17668] intraday_10220.csv.gz  in=181,961,528 out=8,303,923 elapsed=42.7s

  [1244/17668] intraday_10222.csv.gz  in=182,044,920 out=8,387,315 elapsed=42.9s

  [1245/17668] intraday_10221.csv.gz  in=182,145,905 out=8,488,300 elapsed=42.9s

  [1246/17668] intraday_10223.csv.gz  in=182,240,480 out=8,582,875 elapsed=42.9s

  [1247/17668] intraday_10224.csv.gz  in=182,318,621 out=8,661,016 elapsed=42.9s

  [1248/17668] intraday_10226.csv.gz  in=182,395,541 out=8,737,936 elapsed=43.0s

  [1249/17668] intraday_10227.csv.gz  in=182,457,836 out=8,800,231 elapsed=43.0s

  [1250/17668] intraday_10225.csv.gz  in=182,538,188 out=8,880,583 elapsed=43.1s

  [1251/17668] intraday_10228.csv.gz  in=182,613,443 out=8,955,265 elapsed=43.1s

  [1252/17668] intraday_1023.csv.gz  in=182,626,752 out=8,955,265 elapsed=43.1s

  [1253/17668] intraday_10229.csv.gz  in=182,716,973 out=9,045,486 elapsed=43.1s

  [1254/17668] intraday_10232.csv.gz  in=182,808,339 out=9,136,852 elapsed=43.3s

  [1255/17668] intraday_10233.csv.gz  in=182,881,371 out=9,209,761 elapsed=43.3s

  [1256/17668] intraday_10231.csv.gz  in=182,996,678 out=9,325,068 elapsed=43.3s

  [1257/17668] intraday_10230.csv.gz  in=183,109,757 out=9,438,147 elapsed=43.3s

  [1258/17668] intraday_10234.csv.gz  in=183,208,010 out=9,530,079 elapsed=43.4s

  [1259/17668] intraday_10237.csv.gz  in=183,288,361 out=9,610,430 elapsed=43.5s

  [1260/17668] intraday_10236.csv.gz  in=183,393,885 out=9,715,954 elapsed=43.5s

  [1261/17668] intraday_10235.csv.gz  in=183,482,340 out=9,804,409 elapsed=43.5s

  [1262/17668] intraday_10238.csv.gz  in=183,563,343 out=9,885,412 elapsed=43.6s

  [1263/17668] intraday_1024.csv.gz  in=183,575,279 out=9,885,412 elapsed=43.6s

  [1264/17668] intraday_10239.csv.gz  in=183,675,534 out=9,985,667 elapsed=43.6s

  [1265/17668] intraday_10240.csv.gz  in=183,764,000 out=10,074,133 elapsed=43.6s

  [1266/17668] intraday_10243.csv.gz  in=183,851,576 out=10,158,228 elapsed=43.8s

  [1267/17668] intraday_10242.csv.gz  in=183,936,284 out=10,242,936 elapsed=43.8s

  [1268/17668] intraday_10244.csv.gz  in=184,025,697 out=10,332,349 elapsed=43.8s

  [1269/17668] intraday_10241.csv.gz  in=184,116,987 out=10,422,905 elapsed=43.8s

  [1270/17668] intraday_10246.csv.gz  in=184,211,037 out=10,510,576 elapsed=43.9s

  [1271/17668] intraday_10245.csv.gz  in=184,301,232 out=10,598,336 elapsed=44.0s

  [1272/17668] intraday_10247.csv.gz  in=184,375,035 out=10,672,139 elapsed=44.0s

  [1273/17668] intraday_10248.csv.gz  in=184,462,634 out=10,759,738 elapsed=44.0s

  [1274/17668] intraday_1025.csv.gz  in=184,497,338 out=10,759,738 elapsed=44.0s

  [1275/17668] intraday_10249.csv.gz  in=184,588,888 out=10,851,288 elapsed=44.1s

  [1276/17668] intraday_10251.csv.gz  in=184,675,075 out=10,937,475 elapsed=44.1s

  [1277/17668] intraday_10252.csv.gz  in=184,757,746 out=11,017,720 elapsed=44.2s

  [1278/17668] intraday_10250.csv.gz  in=184,853,516 out=11,112,632 elapsed=44.2s

  [1279/17668] intraday_10254.csv.gz  in=184,932,618 out=11,191,734 elapsed=44.2s

  [1280/17668] intraday_10253.csv.gz  in=185,043,773 out=11,302,889 elapsed=44.2s

  [1281/17668] intraday_10255.csv.gz  in=185,128,272 out=11,384,835 elapsed=44.3s

  [1282/17668] intraday_10257.csv.gz  in=185,227,350 out=11,483,913 elapsed=44.3s

  [1283/17668] intraday_10256.csv.gz  in=185,323,770 out=11,580,320 elapsed=44.4s

  [1284/17668] intraday_1026.csv.gz  in=185,335,351 out=11,580,320 elapsed=44.4s

  [1285/17668] intraday_10258.csv.gz  in=185,423,611 out=11,663,726 elapsed=44.4s

  [1286/17668] intraday_10259.csv.gz  in=185,518,466 out=11,758,581 elapsed=44.4s

  [1287/17668] intraday_10260.csv.gz  in=185,601,650 out=11,841,765 elapsed=44.5s

  [1288/17668] intraday_10261.csv.gz  in=185,686,507 out=11,926,287 elapsed=44.6s

  [1289/17668] intraday_10262.csv.gz  in=185,785,713 out=12,025,493 elapsed=44.6s

  [1290/17668] intraday_10263.csv.gz  in=185,902,292 out=12,142,072 elapsed=44.6s

  [1291/17668] intraday_10264.csv.gz  in=186,037,542 out=12,277,322 elapsed=44.7s

  [1292/17668] intraday_10266.csv.gz  in=186,135,980 out=12,375,760 elapsed=44.8s

  [1293/17668] intraday_10267.csv.gz  in=186,211,912 out=12,451,692 elapsed=44.8s

  [1294/17668] intraday_1027.csv.gz  in=186,224,247 out=12,451,692 elapsed=44.8s

  [1295/17668] intraday_10265.csv.gz  in=186,327,889 out=12,555,334 elapsed=44.8s

  [1296/17668] intraday_10268.csv.gz  in=186,419,031 out=12,646,002 elapsed=44.8s

  [1297/17668] intraday_10269.csv.gz  in=186,494,597 out=12,721,504 elapsed=44.9s

  [1298/17668] intraday_10271.csv.gz  in=186,567,903 out=12,794,810 elapsed=45.0s

  [1299/17668] intraday_10273.csv.gz  in=186,659,060 out=12,885,555 elapsed=45.1s

  [1300/17668] intraday_10270.csv.gz  in=186,762,094 out=12,988,589 elapsed=45.1s

  [1301/17668] intraday_10272.csv.gz  in=186,856,537 out=13,083,032 elapsed=45.1s

  [1302/17668] intraday_10274.csv.gz  in=186,968,075 out=13,194,570 elapsed=45.2s

  [1303/17668] intraday_10277.csv.gz  in=187,046,020 out=13,272,515 elapsed=45.2s

  [1304/17668] intraday_10276.csv.gz  in=187,128,249 out=13,354,744 elapsed=45.2s

  [1305/17668] intraday_10275.csv.gz  in=187,202,004 out=13,428,499 elapsed=45.2s

  [1306/17668] intraday_1028.csv.gz  in=187,213,776 out=13,428,499 elapsed=45.2s

  [1307/17668] intraday_10278.csv.gz  in=187,304,715 out=13,519,438 elapsed=45.3s

  [1308/17668] intraday_10279.csv.gz  in=187,386,833 out=13,599,400 elapsed=45.3s

  [1309/17668] intraday_10280.csv.gz  in=187,484,710 out=13,697,277 elapsed=45.4s

  [1310/17668] intraday_10282.csv.gz  in=187,578,318 out=13,790,885 elapsed=45.4s

  [1311/17668] intraday_10281.csv.gz  in=187,689,067 out=13,897,487 elapsed=45.5s

  [1312/17668] intraday_10283.csv.gz  in=187,797,424 out=14,005,844 elapsed=45.5s

  [1313/17668] intraday_10284.csv.gz  in=187,871,229 out=14,079,649 elapsed=45.5s

  [1314/17668] intraday_10285.csv.gz  in=187,959,414 out=14,167,834 elapsed=45.6s

  [1315/17668] intraday_10287.csv.gz  in=188,035,902 out=14,244,322 elapsed=45.6s

  [1316/17668] intraday_1029.csv.gz  in=188,047,630 out=14,244,322 elapsed=45.6s

  [1317/17668] intraday_10286.csv.gz  in=188,145,189 out=14,338,715 elapsed=45.6s

  [1318/17668] intraday_10288.csv.gz  in=188,260,016 out=14,433,372 elapsed=45.7s

  [1319/17668] intraday_10289.csv.gz  in=188,321,560 out=14,485,950 elapsed=45.7s

  [1320/17668] intraday_10292.csv.gz  in=188,335,624 out=14,500,014 elapsed=45.7s

  [1321/17668] intraday_10293.csv.gz  in=188,347,682 out=14,512,072 elapsed=45.7s

  [1322/17668] intraday_10291.csv.gz  in=188,416,034 out=14,580,424 elapsed=45.8s

  [1323/17668] intraday_10290.csv.gz  in=188,496,204 out=14,660,594 elapsed=45.8s

  [1324/17668] intraday_10295.csv.gz  in=188,506,119 out=14,670,509 elapsed=45.8s

  [1325/17668] intraday_10294.csv.gz  in=188,521,614 out=14,686,004 elapsed=45.8s

  [1326/17668] intraday_10296.csv.gz  in=188,533,188 out=14,697,578 elapsed=45.8s

  [1327/17668] intraday_10299.csv.gz  in=188,543,450 out=14,707,840 elapsed=45.8s

  [1328/17668] intraday_1030.csv.gz  in=188,555,490 out=14,707,840 elapsed=45.8s

  [1329/17668] intraday_10297.csv.gz  in=188,568,962 out=14,721,312 elapsed=45.8s

  [1330/17668] intraday_10298.csv.gz  in=188,581,890 out=14,734,240 elapsed=45.9s

  [1331/17668] intraday_10300.csv.gz  in=188,593,313 out=14,745,663 elapsed=45.9s

  [1332/17668] intraday_10301.csv.gz  in=188,606,985 out=14,759,335 elapsed=45.9s

  [1333/17668] intraday_10303.csv.gz  in=188,617,823 out=14,770,173 elapsed=45.9s

  [1334/17668] intraday_10304.csv.gz  in=188,630,246 out=14,782,596 elapsed=45.9s

  [1335/17668] intraday_10302.csv.gz  in=188,641,915 out=14,794,265 elapsed=45.9s

  [1336/17668] intraday_10305.csv.gz  in=188,655,133 out=14,807,483 elapsed=45.9s

  [1337/17668] intraday_10306.csv.gz  in=188,664,538 out=14,816,888 elapsed=46.0s

  [1338/17668] intraday_10307.csv.gz  in=188,675,244 out=14,827,594 elapsed=46.0s

  [1339/17668] intraday_10308.csv.gz  in=188,688,056 out=14,840,406 elapsed=46.0s

  [1340/17668] intraday_10309.csv.gz  in=188,701,110 out=14,853,460 elapsed=46.0s

  [1341/17668] intraday_1031.csv.gz  in=188,721,100 out=14,853,460 elapsed=46.0s

  [1342/17668] intraday_10310.csv.gz  in=188,732,815 out=14,865,175 elapsed=46.0s

  [1343/17668] intraday_10311.csv.gz  in=188,743,799 out=14,876,159 elapsed=46.0s

  [1344/17668] intraday_10313.csv.gz  in=188,757,228 out=14,889,588 elapsed=46.1s

  [1345/17668] intraday_10312.csv.gz  in=188,768,189 out=14,900,549 elapsed=46.1s

  [1346/17668] intraday_10314.csv.gz  in=188,780,661 out=14,913,021 elapsed=46.1s

  [1347/17668] intraday_10315.csv.gz  in=188,792,750 out=14,925,110 elapsed=46.1s

  [1348/17668] intraday_10316.csv.gz  in=188,804,444 out=14,936,804 elapsed=46.1s

  [1349/17668] intraday_10317.csv.gz  in=188,815,229 out=14,947,589 elapsed=46.1s

  [1350/17668] intraday_10318.csv.gz  in=188,826,476 out=14,958,836 elapsed=46.1s

  [1351/17668] intraday_1032.csv.gz  in=188,836,584 out=14,958,836 elapsed=46.2s

  [1352/17668] intraday_10320.csv.gz  in=188,847,459 out=14,969,711 elapsed=46.2s

  [1353/17668] intraday_10319.csv.gz  in=188,858,824 out=14,981,076 elapsed=46.2s

  [1354/17668] intraday_10322.csv.gz  in=188,873,166 out=14,995,418 elapsed=46.2s

  [1355/17668] intraday_10321.csv.gz  in=188,885,572 out=15,007,824 elapsed=46.2s

  [1356/17668] intraday_10323.csv.gz  in=188,900,017 out=15,021,716 elapsed=46.2s

  [1357/17668] intraday_10324.csv.gz  in=188,909,570 out=15,031,269 elapsed=46.2s

  [1358/17668] intraday_10325.csv.gz  in=188,919,534 out=15,041,233 elapsed=46.2s

  [1359/17668] intraday_10326.csv.gz  in=188,930,923 out=15,052,622 elapsed=46.3s

  [1360/17668] intraday_10327.csv.gz  in=188,942,860 out=15,064,559 elapsed=46.3s

  [1361/17668] intraday_10328.csv.gz  in=188,953,908 out=15,075,607 elapsed=46.3s

  [1362/17668] intraday_1033.csv.gz  in=188,965,453 out=15,075,607 elapsed=46.3s

  [1363/17668] intraday_10329.csv.gz  in=188,976,686 out=15,086,840 elapsed=46.3s

  [1364/17668] intraday_10330.csv.gz  in=188,987,032 out=15,097,186 elapsed=46.3s

  [1365/17668] intraday_10331.csv.gz  in=188,996,876 out=15,107,030 elapsed=46.3s

  [1366/17668] intraday_10333.csv.gz  in=189,008,354 out=15,118,508 elapsed=46.3s

  [1367/17668] intraday_10332.csv.gz  in=189,019,146 out=15,129,300 elapsed=46.3s

  [1368/17668] intraday_10334.csv.gz  in=189,032,417 out=15,142,571 elapsed=46.3s

  [1369/17668] intraday_10335.csv.gz  in=189,043,121 out=15,153,275 elapsed=46.4s

  [1370/17668] intraday_10336.csv.gz  in=189,056,271 out=15,166,425 elapsed=46.4s

  [1371/17668] intraday_10338.csv.gz  in=189,066,419 out=15,176,573 elapsed=46.4s

  [1372/17668] intraday_10337.csv.gz  in=189,079,317 out=15,189,471 elapsed=46.4s

  [1373/17668] intraday_10339.csv.gz  in=189,093,158 out=15,201,317 elapsed=46.4s

  [1374/17668] intraday_1034.csv.gz  in=189,104,555 out=15,201,317 elapsed=46.4s

  [1375/17668] intraday_10340.csv.gz  in=189,116,343 out=15,213,105 elapsed=46.4s

  [1376/17668] intraday_10341.csv.gz  in=189,126,157 out=15,222,919 elapsed=46.5s

  [1377/17668] intraday_10342.csv.gz  in=189,137,335 out=15,233,479 elapsed=46.5s

  [1378/17668] intraday_10343.csv.gz  in=189,148,045 out=15,244,189 elapsed=46.5s

  [1379/17668] intraday_10344.csv.gz  in=189,158,176 out=15,254,320 elapsed=46.5s

  [1380/17668] intraday_10345.csv.gz  in=189,170,240 out=15,266,384 elapsed=46.5s

  [1381/17668] intraday_10346.csv.gz  in=189,181,511 out=15,277,655 elapsed=46.5s

  [1382/17668] intraday_10347.csv.gz  in=189,192,631 out=15,288,775 elapsed=46.5s

  [1383/17668] intraday_10348.csv.gz  in=189,204,668 out=15,300,812 elapsed=46.5s

  [1384/17668] intraday_10349.csv.gz  in=189,215,483 out=15,311,627 elapsed=46.6s

  [1385/17668] intraday_1035.csv.gz  in=189,230,735 out=15,311,627 elapsed=46.6s

  [1386/17668] intraday_10351.csv.gz  in=189,240,797 out=15,321,689 elapsed=46.6s

  [1387/17668] intraday_10350.csv.gz  in=189,252,102 out=15,332,994 elapsed=46.6s

  [1388/17668] intraday_10352.csv.gz  in=189,263,616 out=15,344,508 elapsed=46.6s

  [1389/17668] intraday_10353.csv.gz  in=189,273,565 out=15,354,457 elapsed=46.6s

  [1390/17668] intraday_10354.csv.gz  in=189,285,616 out=15,366,508 elapsed=46.6s

  [1391/17668] intraday_10355.csv.gz  in=189,298,092 out=15,378,984 elapsed=46.6s

  [1392/17668] intraday_10356.csv.gz  in=189,308,623 out=15,389,515 elapsed=46.6s

  [1393/17668] intraday_10357.csv.gz  in=189,326,487 out=15,401,418 elapsed=46.7s

  [1394/17668] intraday_10358.csv.gz  in=189,340,638 out=15,415,569 elapsed=46.7s

  [1395/17668] intraday_10359.csv.gz  in=189,353,256 out=15,428,187 elapsed=46.7s

  [1396/17668] intraday_1036.csv.gz  in=189,377,458 out=15,428,187 elapsed=46.7s

  [1397/17668] intraday_10360.csv.gz  in=189,390,683 out=15,441,412 elapsed=46.7s

  [1398/17668] intraday_10361.csv.gz  in=189,402,208 out=15,452,937 elapsed=46.7s

  [1399/17668] intraday_10363.csv.gz  in=189,412,105 out=15,462,834 elapsed=46.7s

  [1400/17668] intraday_10362.csv.gz  in=189,423,970 out=15,474,699 elapsed=46.7s

  [1401/17668] intraday_10364.csv.gz  in=189,434,947 out=15,485,676 elapsed=46.8s

  [1402/17668] intraday_10365.csv.gz  in=189,446,829 out=15,497,558 elapsed=46.8s

  [1403/17668] intraday_10366.csv.gz  in=189,458,931 out=15,509,660 elapsed=46.8s

  [1404/17668] intraday_10368.csv.gz  in=189,470,146 out=15,520,875 elapsed=46.8s

  [1405/17668] intraday_10367.csv.gz  in=189,482,310 out=15,533,039 elapsed=46.8s

  [1406/17668] intraday_10369.csv.gz  in=189,492,194 out=15,542,923 elapsed=46.8s

  [1407/17668] intraday_1037.csv.gz  in=189,504,725 out=15,542,923 elapsed=46.8s

  [1408/17668] intraday_10373.csv.gz  in=189,515,478 out=15,553,676 elapsed=46.9s

  [1409/17668] intraday_10372.csv.gz  in=189,526,766 out=15,564,964 elapsed=46.9s

  [1410/17668] intraday_10370.csv.gz  in=189,538,997 out=15,577,195 elapsed=46.9s

  [1411/17668] intraday_10371.csv.gz  in=189,549,655 out=15,587,853 elapsed=46.9s

  [1412/17668] intraday_10374.csv.gz  in=189,558,451 out=15,596,649 elapsed=46.9s

  [1413/17668] intraday_10376.csv.gz  in=189,570,334 out=15,608,532 elapsed=46.9s

  [1414/17668] intraday_10375.csv.gz  in=189,580,448 out=15,618,646 elapsed=46.9s

  [1415/17668] intraday_10377.csv.gz  in=189,596,045 out=15,634,243 elapsed=46.9s

  [1416/17668] intraday_10378.csv.gz  in=189,609,647 out=15,647,845 elapsed=47.0s

  [1417/17668] intraday_1038.csv.gz  in=189,621,352 out=15,647,845 elapsed=47.0s

  [1418/17668] intraday_10379.csv.gz  in=189,633,115 out=15,659,608 elapsed=47.0s

  [1419/17668] intraday_10382.csv.gz  in=189,643,734 out=15,670,227 elapsed=47.0s

  [1420/17668] intraday_10383.csv.gz  in=189,657,518 out=15,684,011 elapsed=47.0s

  [1421/17668] intraday_10381.csv.gz  in=189,671,287 out=15,697,780 elapsed=47.0s

  [1422/17668] intraday_10380.csv.gz  in=189,680,840 out=15,707,333 elapsed=47.0s

  [1423/17668] intraday_10384.csv.gz  in=189,693,266 out=15,719,759 elapsed=47.1s

  [1424/17668] intraday_10387.csv.gz  in=189,706,122 out=15,732,615 elapsed=47.1s

  [1425/17668] intraday_10385.csv.gz  in=189,717,062 out=15,743,555 elapsed=47.1s

  [1426/17668] intraday_10388.csv.gz  in=189,729,576 out=15,756,069 elapsed=47.1s

  [1427/17668] intraday_10386.csv.gz  in=189,742,115 out=15,768,608 elapsed=47.1s

  [1428/17668] intraday_10390.csv.gz  in=189,754,488 out=15,780,981 elapsed=47.1s

  [1429/17668] intraday_10391.csv.gz  in=189,765,566 out=15,792,059 elapsed=47.2s

  [1430/17668] intraday_10389.csv.gz  in=189,777,441 out=15,803,934 elapsed=47.2s

  [1431/17668] intraday_1039.csv.gz  in=189,790,465 out=15,803,934 elapsed=47.2s

  [1432/17668] intraday_10392.csv.gz  in=189,802,400 out=15,815,869 elapsed=47.2s

  [1433/17668] intraday_10393.csv.gz  in=189,815,004 out=15,828,473 elapsed=47.2s

  [1434/17668] intraday_10395.csv.gz  in=189,826,454 out=15,839,923 elapsed=47.2s

  [1435/17668] intraday_10394.csv.gz  in=189,836,666 out=15,850,135 elapsed=47.2s

  [1436/17668] intraday_10396.csv.gz  in=189,849,361 out=15,862,830 elapsed=47.2s

  [1437/17668] intraday_10397.csv.gz  in=189,860,975 out=15,874,444 elapsed=47.2s

  [1438/17668] intraday_10398.csv.gz  in=189,872,737 out=15,886,206 elapsed=47.2s

  [1439/17668] intraday_10399.csv.gz  in=189,883,013 out=15,896,482 elapsed=47.3s

  [1440/17668] intraday_1040.csv.gz  in=189,895,412 out=15,896,482 elapsed=47.3s

  [1441/17668] intraday_10400.csv.gz  in=189,910,843 out=15,911,913 elapsed=47.3s

  [1442/17668] intraday_10401.csv.gz  in=189,920,129 out=15,921,199 elapsed=47.3s

  [1443/17668] intraday_10402.csv.gz  in=189,931,805 out=15,932,875 elapsed=47.3s

  [1444/17668] intraday_10403.csv.gz  in=189,952,125 out=15,948,837 elapsed=47.3s

  [1445/17668] intraday_10405.csv.gz  in=189,962,185 out=15,958,897 elapsed=47.4s

  [1446/17668] intraday_10404.csv.gz  in=189,975,359 out=15,972,071 elapsed=47.4s

  [1447/17668] intraday_10406.csv.gz  in=189,990,426 out=15,987,138 elapsed=47.4s

  [1448/17668] intraday_10407.csv.gz  in=190,003,378 out=16,000,090 elapsed=47.4s

  [1449/17668] intraday_10408.csv.gz  in=190,014,957 out=16,011,669 elapsed=47.4s

  [1450/17668] intraday_10409.csv.gz  in=190,030,073 out=16,024,850 elapsed=47.4s

  [1451/17668] intraday_1041.csv.gz  in=190,045,358 out=16,024,850 elapsed=47.4s

  [1452/17668] intraday_10411.csv.gz  in=190,062,125 out=16,041,617 elapsed=47.4s

  [1453/17668] intraday_10410.csv.gz  in=190,077,193 out=16,056,685 elapsed=47.4s

  [1454/17668] intraday_10413.csv.gz  in=190,091,156 out=16,070,648 elapsed=47.5s

  [1455/17668] intraday_10412.csv.gz  in=190,105,540 out=16,085,032 elapsed=47.5s

  [1456/17668] intraday_10414.csv.gz  in=190,115,831 out=16,095,323 elapsed=47.5s

  [1457/17668] intraday_10415.csv.gz  in=190,127,352 out=16,106,844 elapsed=47.5s

  [1458/17668] intraday_10416.csv.gz  in=190,138,032 out=16,117,524 elapsed=47.5s

  [1459/17668] intraday_10418.csv.gz  in=190,148,855 out=16,128,347 elapsed=47.5s

  [1460/17668] intraday_10417.csv.gz  in=190,161,069 out=16,140,561 elapsed=47.5s

  [1461/17668] intraday_10419.csv.gz  in=190,173,715 out=16,153,207 elapsed=47.5s

  [1462/17668] intraday_1042.csv.gz  in=190,185,728 out=16,153,207 elapsed=47.5s

  [1463/17668] intraday_10420.csv.gz  in=190,198,732 out=16,166,211 elapsed=47.6s

  [1464/17668] intraday_10421.csv.gz  in=190,212,555 out=16,180,034 elapsed=47.6s

  [1465/17668] intraday_10422.csv.gz  in=190,223,133 out=16,190,612 elapsed=47.6s

  [1466/17668] intraday_10423.csv.gz  in=190,234,082 out=16,201,561 elapsed=47.6s

  [1467/17668] intraday_10424.csv.gz  in=190,244,951 out=16,212,430 elapsed=47.6s

  [1468/17668] intraday_10425.csv.gz  in=190,256,265 out=16,223,744 elapsed=47.6s

  [1469/17668] intraday_10426.csv.gz  in=190,267,065 out=16,234,544 elapsed=47.6s

  [1470/17668] intraday_10427.csv.gz  in=190,281,516 out=16,248,995 elapsed=47.6s

  [1471/17668] intraday_10429.csv.gz  in=190,294,215 out=16,261,694 elapsed=47.7s

  [1472/17668] intraday_1043.csv.gz  in=190,310,268 out=16,261,694 elapsed=47.7s

  [1473/17668] intraday_10428.csv.gz  in=190,326,010 out=16,277,436 elapsed=47.7s

  [1474/17668] intraday_10430.csv.gz  in=190,341,261 out=16,292,687 elapsed=47.7s

  [1475/17668] intraday_10432.csv.gz  in=190,352,179 out=16,303,605 elapsed=47.7s

  [1476/17668] intraday_10431.csv.gz  in=190,363,283 out=16,314,709 elapsed=47.7s

  [1477/17668] intraday_10433.csv.gz  in=190,375,823 out=16,327,249 elapsed=47.7s

  [1478/17668] intraday_10434.csv.gz  in=190,385,834 out=16,337,260 elapsed=47.7s

  [1479/17668] intraday_10435.csv.gz  in=190,398,422 out=16,349,848 elapsed=47.7s

  [1480/17668] intraday_10436.csv.gz  in=190,407,256 out=16,358,682 elapsed=47.7s

  [1481/17668] intraday_10438.csv.gz  in=190,415,622 out=16,367,048 elapsed=47.7s

  [1482/17668] intraday_10437.csv.gz  in=190,426,352 out=16,377,778 elapsed=47.8s

  [1483/17668] intraday_10439.csv.gz  in=190,440,829 out=16,392,255 elapsed=47.8s

  [1484/17668] intraday_1044.csv.gz  in=190,454,999 out=16,392,255 elapsed=47.8s

  [1485/17668] intraday_10440.csv.gz  in=190,467,263 out=16,404,519 elapsed=47.8s

  [1486/17668] intraday_10443.csv.gz  in=190,478,684 out=16,415,940 elapsed=47.8s

  [1487/17668] intraday_10441.csv.gz  in=190,491,777 out=16,429,033 elapsed=47.8s

  [1488/17668] intraday_10442.csv.gz  in=190,501,251 out=16,438,507 elapsed=47.8s

  [1489/17668] intraday_10444.csv.gz  in=190,515,555 out=16,452,811 elapsed=47.8s

  [1490/17668] intraday_10446.csv.gz  in=190,527,314 out=16,464,570 elapsed=47.9s

  [1491/17668] intraday_10445.csv.gz  in=190,540,326 out=16,477,582 elapsed=47.9s

  [1492/17668] intraday_10447.csv.gz  in=190,551,500 out=16,488,756 elapsed=47.9s

  [1493/17668] intraday_10449.csv.gz  in=190,565,609 out=16,502,865 elapsed=47.9s

  [1494/17668] intraday_10448.csv.gz  in=190,579,035 out=16,516,291 elapsed=47.9s

  [1495/17668] intraday_1045.csv.gz  in=190,593,370 out=16,516,291 elapsed=47.9s

  [1496/17668] intraday_10450.csv.gz  in=190,605,078 out=16,527,999 elapsed=47.9s

  [1497/17668] intraday_10452.csv.gz  in=190,619,233 out=16,542,154 elapsed=48.0s

  [1498/17668] intraday_10453.csv.gz  in=190,629,204 out=16,552,125 elapsed=48.0s

  [1499/17668] intraday_10454.csv.gz  in=190,639,607 out=16,562,528 elapsed=48.0s

  [1500/17668] intraday_10451.csv.gz  in=190,651,958 out=16,574,879 elapsed=48.0s

  [1501/17668] intraday_10455.csv.gz  in=190,664,580 out=16,587,501 elapsed=48.0s

  [1502/17668] intraday_10457.csv.gz  in=190,676,207 out=16,598,875 elapsed=48.0s

  [1503/17668] intraday_10456.csv.gz  in=190,690,050 out=16,612,718 elapsed=48.0s

  [1504/17668] intraday_10458.csv.gz  in=190,700,110 out=16,622,778 elapsed=48.0s

  [1505/17668] intraday_10459.csv.gz  in=190,710,999 out=16,633,667 elapsed=48.0s

  [1506/17668] intraday_1046.csv.gz  in=190,723,721 out=16,633,667 elapsed=48.0s

  [1507/17668] intraday_10460.csv.gz  in=190,737,368 out=16,647,314 elapsed=48.0s

  [1508/17668] intraday_10461.csv.gz  in=190,749,492 out=16,659,438 elapsed=48.1s

  [1509/17668] intraday_10462.csv.gz  in=190,761,623 out=16,671,569 elapsed=48.1s

  [1510/17668] intraday_10463.csv.gz  in=190,773,305 out=16,683,251 elapsed=48.1s

  [1511/17668] intraday_10465.csv.gz  in=190,784,503 out=16,694,449 elapsed=48.1s

  [1512/17668] intraday_10464.csv.gz  in=190,795,768 out=16,705,714 elapsed=48.1s

  [1513/17668] intraday_10466.csv.gz  in=190,807,446 out=16,717,392 elapsed=48.1s

  [1514/17668] intraday_10467.csv.gz  in=190,819,138 out=16,729,084 elapsed=48.1s

  [1515/17668] intraday_10469.csv.gz  in=190,834,254 out=16,744,200 elapsed=48.2s

  [1516/17668] intraday_10468.csv.gz  in=190,846,577 out=16,756,523 elapsed=48.2s

  [1517/17668] intraday_1047.csv.gz  in=190,862,993 out=16,756,523 elapsed=48.2s

  [1518/17668] intraday_10470.csv.gz  in=190,875,034 out=16,768,564 elapsed=48.2s

  [1519/17668] intraday_10471.csv.gz  in=190,884,844 out=16,778,374 elapsed=48.2s

  [1520/17668] intraday_10472.csv.gz  in=190,895,719 out=16,789,249 elapsed=48.2s

  [1521/17668] intraday_10473.csv.gz  in=190,908,012 out=16,801,542 elapsed=48.2s

  [1522/17668] intraday_10474.csv.gz  in=190,921,235 out=16,814,765 elapsed=48.2s

  [1523/17668] intraday_10475.csv.gz  in=190,932,834 out=16,826,364 elapsed=48.2s

  [1524/17668] intraday_10478.csv.gz  in=190,941,934 out=16,835,464 elapsed=48.3s

  [1525/17668] intraday_10476.csv.gz  in=190,954,937 out=16,847,287 elapsed=48.3s

  [1526/17668] intraday_1048.csv.gz  in=190,966,683 out=16,847,287 elapsed=48.3s

  [1527/17668] intraday_10477.csv.gz  in=190,976,486 out=16,857,090 elapsed=48.3s

  [1528/17668] intraday_10479.csv.gz  in=190,987,267 out=16,867,871 elapsed=48.3s

  [1529/17668] intraday_10480.csv.gz  in=190,999,633 out=16,880,237 elapsed=48.3s

  [1530/17668] intraday_10481.csv.gz  in=191,013,916 out=16,894,520 elapsed=48.3s

  [1531/17668] intraday_10483.csv.gz  in=191,026,281 out=16,906,885 elapsed=48.3s

  [1532/17668] intraday_10484.csv.gz  in=191,039,514 out=16,920,118 elapsed=48.4s

  [1533/17668] intraday_10482.csv.gz  in=191,051,320 out=16,931,924 elapsed=48.4s

  [1534/17668] intraday_10485.csv.gz  in=191,063,187 out=16,942,611 elapsed=48.4s

  [1535/17668] intraday_10487.csv.gz  in=191,074,211 out=16,953,635 elapsed=48.4s

  [1536/17668] intraday_10486.csv.gz  in=191,086,201 out=16,965,625 elapsed=48.4s

  [1537/17668] intraday_10488.csv.gz  in=191,097,044 out=16,976,468 elapsed=48.4s

  [1538/17668] intraday_1049.csv.gz  in=191,109,327 out=16,976,468 elapsed=48.4s

  [1539/17668] intraday_10489.csv.gz  in=191,124,073 out=16,987,922 elapsed=48.5s

  [1540/17668] intraday_10490.csv.gz  in=191,135,386 out=16,999,235 elapsed=48.5s

  [1541/17668] intraday_10491.csv.gz  in=191,146,905 out=17,010,754 elapsed=48.5s

  [1542/17668] intraday_10492.csv.gz  in=191,158,166 out=17,022,015 elapsed=48.5s

  [1543/17668] intraday_10493.csv.gz  in=191,170,388 out=17,034,237 elapsed=48.5s

  [1544/17668] intraday_10494.csv.gz  in=191,184,131 out=17,047,980 elapsed=48.5s

  [1545/17668] intraday_10495.csv.gz  in=191,195,455 out=17,059,304 elapsed=48.5s

  [1546/17668] intraday_10496.csv.gz  in=191,207,953 out=17,071,802 elapsed=48.5s

  [1547/17668] intraday_10498.csv.gz  in=191,218,622 out=17,082,471 elapsed=48.6s

  [1548/17668] intraday_10499.csv.gz  in=191,230,928 out=17,094,777 elapsed=48.6s

  [1549/17668] intraday_10497.csv.gz  in=191,242,310 out=17,106,159 elapsed=48.6s

  [1550/17668] intraday_1050.csv.gz  in=191,254,843 out=17,106,159 elapsed=48.6s

  [1551/17668] intraday_10500.csv.gz  in=191,265,624 out=17,116,940 elapsed=48.6s

  [1552/17668] intraday_10502.csv.gz  in=191,275,832 out=17,127,148 elapsed=48.6s

  [1553/17668] intraday_10501.csv.gz  in=191,289,829 out=17,141,145 elapsed=48.6s

  [1554/17668] intraday_10504.csv.gz  in=191,300,214 out=17,151,530 elapsed=48.6s

  [1555/17668] intraday_10503.csv.gz  in=191,311,306 out=17,162,622 elapsed=48.6s

  [1556/17668] intraday_10505.csv.gz  in=191,326,633 out=17,177,949 elapsed=48.7s

  [1557/17668] intraday_10506.csv.gz  in=191,339,959 out=17,191,275 elapsed=48.7s

  [1558/17668] intraday_10507.csv.gz  in=191,353,372 out=17,204,688 elapsed=48.7s

  [1559/17668] intraday_10508.csv.gz  in=191,366,201 out=17,217,517 elapsed=48.7s

  [1560/17668] intraday_10509.csv.gz  in=191,378,469 out=17,229,785 elapsed=48.7s

  [1561/17668] intraday_1051.csv.gz  in=191,391,399 out=17,229,785 elapsed=48.7s

  [1562/17668] intraday_10510.csv.gz  in=191,402,922 out=17,241,308 elapsed=48.7s

  [1563/17668] intraday_10511.csv.gz  in=191,414,362 out=17,252,748 elapsed=48.7s

  [1564/17668] intraday_10512.csv.gz  in=191,427,095 out=17,265,481 elapsed=48.8s

  [1565/17668] intraday_10513.csv.gz  in=191,441,197 out=17,279,583 elapsed=48.8s

  [1566/17668] intraday_10514.csv.gz  in=191,453,662 out=17,292,048 elapsed=48.8s

  [1567/17668] intraday_10515.csv.gz  in=191,466,019 out=17,304,405 elapsed=48.8s

  [1568/17668] intraday_10517.csv.gz  in=191,479,174 out=17,317,560 elapsed=48.8s

  [1569/17668] intraday_10516.csv.gz  in=191,489,616 out=17,328,002 elapsed=48.8s

  [1570/17668] intraday_10518.csv.gz  in=191,500,361 out=17,338,747 elapsed=48.9s

  [1571/17668] intraday_10519.csv.gz  in=191,517,136 out=17,351,428 elapsed=48.9s

  [1572/17668] intraday_1052.csv.gz  in=191,528,476 out=17,351,428 elapsed=48.9s

  [1573/17668] intraday_10520.csv.gz  in=191,539,553 out=17,362,505 elapsed=48.9s

  [1574/17668] intraday_10521.csv.gz  in=191,548,793 out=17,371,745 elapsed=48.9s

  [1575/17668] intraday_10522.csv.gz  in=191,558,748 out=17,381,700 elapsed=48.9s

  [1576/17668] intraday_10523.csv.gz  in=191,571,999 out=17,394,951 elapsed=48.9s

  [1577/17668] intraday_10526.csv.gz  in=191,583,042 out=17,405,994 elapsed=48.9s

  [1578/17668] intraday_10524.csv.gz  in=191,599,923 out=17,422,875 elapsed=49.0s

  [1579/17668] intraday_10525.csv.gz  in=191,613,474 out=17,436,426 elapsed=49.0s

  [1580/17668] intraday_10527.csv.gz  in=191,625,063 out=17,448,015 elapsed=49.0s

  [1581/17668] intraday_10528.csv.gz  in=191,637,417 out=17,460,369 elapsed=49.0s

  [1582/17668] intraday_10529.csv.gz  in=191,648,915 out=17,471,867 elapsed=49.0s

  [1583/17668] intraday_10531.csv.gz  in=191,661,320 out=17,484,272 elapsed=49.0s

  [1584/17668] intraday_10530.csv.gz  in=191,676,660 out=17,499,612 elapsed=49.0s

  [1585/17668] intraday_1053.csv.gz  in=191,702,121 out=17,499,612 elapsed=49.0s

  [1586/17668] intraday_10532.csv.gz  in=191,712,691 out=17,510,182 elapsed=49.0s

  [1587/17668] intraday_10533.csv.gz  in=191,724,144 out=17,521,635 elapsed=49.1s

  [1588/17668] intraday_10535.csv.gz  in=191,736,480 out=17,533,971 elapsed=49.1s

  [1589/17668] intraday_10534.csv.gz  in=191,750,756 out=17,548,247 elapsed=49.1s

  [1590/17668] intraday_10536.csv.gz  in=191,762,218 out=17,559,709 elapsed=49.1s

  [1591/17668] intraday_10537.csv.gz  in=191,774,898 out=17,572,389 elapsed=49.1s

  [1592/17668] intraday_1054.csv.gz  in=191,786,676 out=17,572,389 elapsed=49.2s

  [1593/17668] intraday_10539.csv.gz  in=191,798,799 out=17,584,512 elapsed=49.2s

  [1594/17668] intraday_10540.csv.gz  in=191,811,141 out=17,596,854 elapsed=49.2s

  [1595/17668] intraday_10541.csv.gz  in=191,821,206 out=17,606,919 elapsed=49.2s

  [1596/17668] intraday_10538.csv.gz  in=191,833,411 out=17,619,124 elapsed=49.2s

  [1597/17668] intraday_10542.csv.gz  in=191,847,106 out=17,632,819 elapsed=49.2s

  [1598/17668] intraday_10543.csv.gz  in=191,860,497 out=17,646,210 elapsed=49.2s

  [1599/17668] intraday_10544.csv.gz  in=191,873,765 out=17,659,478 elapsed=49.2s

  [1600/17668] intraday_10546.csv.gz  in=191,883,535 out=17,669,248 elapsed=49.2s

  [1601/17668] intraday_10547.csv.gz  in=191,899,213 out=17,684,926 elapsed=49.2s

  [1602/17668] intraday_10545.csv.gz  in=191,911,207 out=17,696,920 elapsed=49.2s

  [1603/17668] intraday_10548.csv.gz  in=191,922,325 out=17,708,038 elapsed=49.2s

  [1604/17668] intraday_10549.csv.gz  in=191,934,020 out=17,719,733 elapsed=49.3s

  [1605/17668] intraday_1055.csv.gz  in=191,945,961 out=17,719,733 elapsed=49.3s

  [1606/17668] intraday_10550.csv.gz  in=191,959,255 out=17,733,027 elapsed=49.3s

  [1607/17668] intraday_10553.csv.gz  in=191,973,301 out=17,747,073 elapsed=49.3s

  [1608/17668] intraday_10551.csv.gz  in=191,986,721 out=17,760,493 elapsed=49.3s

  [1609/17668] intraday_10552.csv.gz  in=191,997,209 out=17,770,981 elapsed=49.3s

  [1610/17668] intraday_10554.csv.gz  in=192,014,320 out=17,788,092 elapsed=49.4s

  [1611/17668] intraday_10555.csv.gz  in=192,026,119 out=17,799,891 elapsed=49.4s

  [1612/17668] intraday_10556.csv.gz  in=192,041,326 out=17,815,098 elapsed=49.4s

  [1613/17668] intraday_10557.csv.gz  in=192,055,721 out=17,829,493 elapsed=49.4s

  [1614/17668] intraday_10558.csv.gz  in=192,073,305 out=17,847,077 elapsed=49.4s

  [1615/17668] intraday_10559.csv.gz  in=192,087,964 out=17,861,736 elapsed=49.4s

  [1616/17668] intraday_1056.csv.gz  in=192,104,345 out=17,861,736 elapsed=49.4s

  [1617/17668] intraday_10560.csv.gz  in=192,121,551 out=17,877,898 elapsed=49.4s

  [1618/17668] intraday_10561.csv.gz  in=192,133,103 out=17,889,450 elapsed=49.5s

  [1619/17668] intraday_10562.csv.gz  in=192,144,919 out=17,901,266 elapsed=49.5s

  [1620/17668] intraday_10563.csv.gz  in=192,163,727 out=17,919,309 elapsed=49.5s

  [1621/17668] intraday_10564.csv.gz  in=192,177,119 out=17,932,701 elapsed=49.5s

  [1622/17668] intraday_10565.csv.gz  in=192,188,190 out=17,943,772 elapsed=49.5s

  [1623/17668] intraday_10567.csv.gz  in=192,200,439 out=17,956,021 elapsed=49.5s

  [1624/17668] intraday_10566.csv.gz  in=192,212,373 out=17,967,955 elapsed=49.5s

  [1625/17668] intraday_10568.csv.gz  in=192,227,801 out=17,983,383 elapsed=49.5s

  [1626/17668] intraday_10569.csv.gz  in=192,237,880 out=17,993,462 elapsed=49.6s

  [1627/17668] intraday_1057.csv.gz  in=192,247,988 out=17,993,462 elapsed=49.6s

  [1628/17668] intraday_10570.csv.gz  in=192,259,039 out=18,004,513 elapsed=49.6s

  [1629/17668] intraday_10571.csv.gz  in=192,271,326 out=18,016,800 elapsed=49.6s

  [1630/17668] intraday_10573.csv.gz  in=192,282,303 out=18,027,777 elapsed=49.6s

  [1631/17668] intraday_10572.csv.gz  in=192,294,038 out=18,039,512 elapsed=49.6s

  [1632/17668] intraday_10574.csv.gz  in=192,309,581 out=18,055,055 elapsed=49.7s

  [1633/17668] intraday_10575.csv.gz  in=192,325,550 out=18,071,024 elapsed=49.7s

  [1634/17668] intraday_10577.csv.gz  in=192,341,512 out=18,086,986 elapsed=49.7s

  [1635/17668] intraday_10578.csv.gz  in=192,352,820 out=18,098,294 elapsed=49.7s

  [1636/17668] intraday_10576.csv.gz  in=192,366,390 out=18,111,864 elapsed=49.7s

  [1637/17668] intraday_10579.csv.gz  in=192,377,295 out=18,122,769 elapsed=49.7s

  [1638/17668] intraday_1058.csv.gz  in=192,390,464 out=18,122,769 elapsed=49.7s

  [1639/17668] intraday_10581.csv.gz  in=192,402,041 out=18,134,346 elapsed=49.7s

  [1640/17668] intraday_10580.csv.gz  in=192,414,731 out=18,147,036 elapsed=49.8s

  [1641/17668] intraday_10582.csv.gz  in=192,424,495 out=18,156,800 elapsed=49.8s

  [1642/17668] intraday_10584.csv.gz  in=192,435,113 out=18,167,418 elapsed=49.8s

  [1643/17668] intraday_10583.csv.gz  in=192,442,942 out=18,175,247 elapsed=49.8s

  [1644/17668] intraday_10585.csv.gz  in=192,449,461 out=18,181,766 elapsed=49.8s

  [1645/17668] intraday_10586.csv.gz  in=192,464,150 out=18,196,455 elapsed=49.8s

  [1646/17668] intraday_10588.csv.gz  in=192,475,631 out=18,207,936 elapsed=49.8s

  [1647/17668] intraday_10587.csv.gz  in=192,488,237 out=18,220,542 elapsed=49.8s

  [1648/17668] intraday_10589.csv.gz  in=192,497,724 out=18,230,029 elapsed=49.8s

  [1649/17668] intraday_1059.csv.gz  in=192,520,541 out=18,230,029 elapsed=49.8s

  [1650/17668] intraday_10591.csv.gz  in=192,534,405 out=18,243,893 elapsed=49.9s

  [1651/17668] intraday_10590.csv.gz  in=192,546,024 out=18,255,512 elapsed=49.9s

  [1652/17668] intraday_10592.csv.gz  in=192,560,255 out=18,269,743 elapsed=49.9s

  [1653/17668] intraday_10593.csv.gz  in=192,571,033 out=18,280,521 elapsed=49.9s

  [1654/17668] intraday_10594.csv.gz  in=192,582,280 out=18,291,768 elapsed=49.9s

  [1655/17668] intraday_10595.csv.gz  in=192,595,813 out=18,305,301 elapsed=49.9s

  [1656/17668] intraday_10596.csv.gz  in=192,609,901 out=18,319,389 elapsed=49.9s

  [1657/17668] intraday_10597.csv.gz  in=192,621,978 out=18,331,466 elapsed=50.0s

  [1658/17668] intraday_10598.csv.gz  in=192,636,878 out=18,346,366 elapsed=50.0s

  [1659/17668] intraday_10599.csv.gz  in=192,649,921 out=18,359,409 elapsed=50.0s

  [1660/17668] intraday_1060.csv.gz  in=192,664,818 out=18,359,409 elapsed=50.0s

  [1661/17668] intraday_10601.csv.gz  in=192,674,785 out=18,369,376 elapsed=50.0s

  [1662/17668] intraday_10600.csv.gz  in=192,684,453 out=18,379,044 elapsed=50.0s

  [1663/17668] intraday_10603.csv.gz  in=192,696,983 out=18,391,574 elapsed=50.0s

  [1664/17668] intraday_10602.csv.gz  in=192,708,930 out=18,403,521 elapsed=50.0s

  [1665/17668] intraday_10604.csv.gz  in=192,720,002 out=18,414,593 elapsed=50.1s

  [1666/17668] intraday_10605.csv.gz  in=192,730,468 out=18,425,059 elapsed=50.1s

  [1667/17668] intraday_10606.csv.gz  in=192,741,091 out=18,435,682 elapsed=50.1s

  [1668/17668] intraday_10608.csv.gz  in=192,753,605 out=18,448,196 elapsed=50.1s

  [1669/17668] intraday_1061.csv.gz  in=192,765,531 out=18,448,196 elapsed=50.1s

  [1670/17668] intraday_10609.csv.gz  in=192,777,126 out=18,459,791 elapsed=50.1s

  [1671/17668] intraday_10607.csv.gz  in=192,791,539 out=18,474,204 elapsed=50.1s

  [1672/17668] intraday_10610.csv.gz  in=192,804,805 out=18,487,470 elapsed=50.2s

  [1673/17668] intraday_10611.csv.gz  in=192,815,899 out=18,498,564 elapsed=50.2s

  [1674/17668] intraday_10613.csv.gz  in=192,827,740 out=18,510,405 elapsed=50.2s

  [1675/17668] intraday_10612.csv.gz  in=192,839,907 out=18,522,572 elapsed=50.2s

  [1676/17668] intraday_10614.csv.gz  in=192,851,671 out=18,534,336 elapsed=50.2s

  [1677/17668] intraday_10615.csv.gz  in=192,863,475 out=18,546,140 elapsed=50.2s

  [1678/17668] intraday_10617.csv.gz  in=192,875,372 out=18,558,037 elapsed=50.2s

  [1679/17668] intraday_10616.csv.gz  in=192,890,648 out=18,573,313 elapsed=50.2s

  [1680/17668] intraday_10619.csv.gz  in=192,901,848 out=18,584,513 elapsed=50.2s

  [1681/17668] intraday_10618.csv.gz  in=192,911,489 out=18,594,154 elapsed=50.3s

  [1682/17668] intraday_10620.csv.gz  in=192,923,179 out=18,605,844 elapsed=50.3s

  [1683/17668] intraday_10621.csv.gz  in=192,934,757 out=18,617,422 elapsed=50.3s

  [1684/17668] intraday_1062.csv.gz  in=192,948,250 out=18,617,422 elapsed=50.3s

  [1685/17668] intraday_10622.csv.gz  in=192,960,101 out=18,629,273 elapsed=50.3s

  [1686/17668] intraday_10623.csv.gz  in=192,971,702 out=18,640,874 elapsed=50.3s

  [1687/17668] intraday_10624.csv.gz  in=192,982,758 out=18,651,930 elapsed=50.3s

  [1688/17668] intraday_10625.csv.gz  in=192,992,755 out=18,661,927 elapsed=50.3s

  [1689/17668] intraday_10626.csv.gz  in=193,003,744 out=18,672,916 elapsed=50.3s

  [1690/17668] intraday_1063.csv.gz  in=193,015,990 out=18,672,916 elapsed=50.4s

  [1691/17668] intraday_10627.csv.gz  in=193,028,163 out=18,685,089 elapsed=50.4s

  [1692/17668] intraday_10629.csv.gz  in=193,039,597 out=18,696,523 elapsed=50.4s

  [1693/17668] intraday_10628.csv.gz  in=193,053,148 out=18,710,074 elapsed=50.4s

  [1694/17668] intraday_10630.csv.gz  in=193,066,757 out=18,723,683 elapsed=50.4s

  [1695/17668] intraday_10631.csv.gz  in=193,078,923 out=18,735,849 elapsed=50.4s

  [1696/17668] intraday_10632.csv.gz  in=193,089,114 out=18,746,040 elapsed=50.4s

  [1697/17668] intraday_10633.csv.gz  in=193,100,961 out=18,757,887 elapsed=50.4s

  [1698/17668] intraday_10635.csv.gz  in=193,111,010 out=18,767,936 elapsed=50.5s

  [1699/17668] intraday_10634.csv.gz  in=193,122,352 out=18,779,278 elapsed=50.5s

  [1700/17668] intraday_10637.csv.gz  in=193,133,490 out=18,790,416 elapsed=50.5s

  [1701/17668] intraday_10636.csv.gz  in=193,144,518 out=18,801,444 elapsed=50.5s

  [1702/17668] intraday_10638.csv.gz  in=193,156,016 out=18,812,942 elapsed=50.5s

  [1703/17668] intraday_10639.csv.gz  in=193,168,091 out=18,825,017 elapsed=50.5s

  [1704/17668] intraday_1064.csv.gz  in=193,180,748 out=18,825,017 elapsed=50.5s

  [1705/17668] intraday_10640.csv.gz  in=193,197,008 out=18,838,615 elapsed=50.5s

  [1706/17668] intraday_10641.csv.gz  in=193,207,136 out=18,848,743 elapsed=50.5s

  [1707/17668] intraday_10643.csv.gz  in=193,218,944 out=18,860,551 elapsed=50.6s

  [1708/17668] intraday_10642.csv.gz  in=193,232,262 out=18,873,869 elapsed=50.6s

  [1709/17668] intraday_10644.csv.gz  in=193,242,564 out=18,884,171 elapsed=50.6s

  [1710/17668] intraday_10645.csv.gz  in=193,254,212 out=18,895,819 elapsed=50.6s

  [1711/17668] intraday_10647.csv.gz  in=193,264,057 out=18,905,664 elapsed=50.6s

  [1712/17668] intraday_10648.csv.gz  in=193,278,022 out=18,919,629 elapsed=50.6s

  [1713/17668] intraday_10646.csv.gz  in=193,290,555 out=18,932,162 elapsed=50.6s

  [1714/17668] intraday_10649.csv.gz  in=193,301,021 out=18,942,628 elapsed=50.6s

  [1715/17668] intraday_1065.csv.gz  in=193,312,841 out=18,942,628 elapsed=50.6s

  [1716/17668] intraday_10650.csv.gz  in=193,324,118 out=18,953,905 elapsed=50.7s

  [1717/17668] intraday_10651.csv.gz  in=193,334,023 out=18,963,810 elapsed=50.7s

  [1718/17668] intraday_10652.csv.gz  in=193,347,785 out=18,977,572 elapsed=50.7s

  [1719/17668] intraday_10653.csv.gz  in=193,362,194 out=18,991,981 elapsed=50.7s

  [1720/17668] intraday_10654.csv.gz  in=193,376,250 out=19,006,037 elapsed=50.7s

  [1721/17668] intraday_10656.csv.gz  in=193,389,699 out=19,018,522 elapsed=50.8s

  [1722/17668] intraday_10655.csv.gz  in=193,400,851 out=19,029,674 elapsed=50.8s

  [1723/17668] intraday_10658.csv.gz  in=193,412,888 out=19,041,711 elapsed=50.8s

  [1724/17668] intraday_10659.csv.gz  in=193,425,688 out=19,054,511 elapsed=50.8s

  [1725/17668] intraday_10657.csv.gz  in=193,438,500 out=19,067,323 elapsed=50.8s

  [1726/17668] intraday_1066.csv.gz  in=193,453,179 out=19,067,323 elapsed=50.8s

  [1727/17668] intraday_10660.csv.gz  in=193,465,948 out=19,080,082 elapsed=50.8s

  [1728/17668] intraday_10662.csv.gz  in=193,477,112 out=19,091,246 elapsed=50.9s

  [1729/17668] intraday_10663.csv.gz  in=193,487,470 out=19,101,604 elapsed=50.9s

  [1730/17668] intraday_10661.csv.gz  in=193,498,772 out=19,112,906 elapsed=50.9s

  [1731/17668] intraday_10664.csv.gz  in=193,512,112 out=19,126,246 elapsed=50.9s

  [1732/17668] intraday_10665.csv.gz  in=193,523,263 out=19,137,397 elapsed=50.9s

  [1733/17668] intraday_10666.csv.gz  in=193,534,241 out=19,148,375 elapsed=50.9s

  [1734/17668] intraday_10668.csv.gz  in=193,543,067 out=19,157,201 elapsed=50.9s

  [1735/17668] intraday_10669.csv.gz  in=193,553,430 out=19,167,564 elapsed=50.9s

  [1736/17668] intraday_10667.csv.gz  in=193,563,317 out=19,177,451 elapsed=50.9s

  [1737/17668] intraday_1067.csv.gz  in=193,575,117 out=19,177,451 elapsed=51.0s

  [1738/17668] intraday_10672.csv.gz  in=193,588,208 out=19,190,542 elapsed=51.0s

  [1739/17668] intraday_10671.csv.gz  in=193,605,443 out=19,207,777 elapsed=51.0s

  [1740/17668] intraday_10670.csv.gz  in=193,618,290 out=19,220,624 elapsed=51.0s

  [1741/17668] intraday_10673.csv.gz  in=193,629,579 out=19,231,913 elapsed=51.0s

  [1742/17668] intraday_10674.csv.gz  in=193,640,769 out=19,243,103 elapsed=51.0s

  [1743/17668] intraday_10676.csv.gz  in=193,652,167 out=19,254,501 elapsed=51.0s

  [1744/17668] intraday_10675.csv.gz  in=193,665,237 out=19,267,571 elapsed=51.1s

  [1745/17668] intraday_10677.csv.gz  in=193,679,459 out=19,281,793 elapsed=51.1s

  [1746/17668] intraday_10679.csv.gz  in=193,691,400 out=19,293,734 elapsed=51.1s

  [1747/17668] intraday_10678.csv.gz  in=193,702,271 out=19,304,605 elapsed=51.1s

  [1748/17668] intraday_1068.csv.gz  in=193,719,334 out=19,304,605 elapsed=51.1s

  [1749/17668] intraday_10680.csv.gz  in=193,730,541 out=19,315,812 elapsed=51.1s

  [1750/17668] intraday_10683.csv.gz  in=193,742,802 out=19,328,073 elapsed=51.2s

  [1751/17668] intraday_10681.csv.gz  in=193,755,938 out=19,341,209 elapsed=51.2s

  [1752/17668] intraday_10682.csv.gz  in=193,768,917 out=19,354,188 elapsed=51.2s

  [1753/17668] intraday_10684.csv.gz  in=193,781,291 out=19,366,562 elapsed=51.2s

  [1754/17668] intraday_10685.csv.gz  in=193,792,695 out=19,377,966 elapsed=51.2s

  [1755/17668] intraday_10686.csv.gz  in=193,804,194 out=19,389,465 elapsed=51.2s

  [1756/17668] intraday_10687.csv.gz  in=193,816,699 out=19,401,970 elapsed=51.2s

  [1757/17668] intraday_10688.csv.gz  in=193,827,508 out=19,412,779 elapsed=51.2s

  [1758/17668] intraday_1069.csv.gz  in=193,840,443 out=19,412,779 elapsed=51.3s

  [1759/17668] intraday_10690.csv.gz  in=193,858,598 out=19,427,068 elapsed=51.3s

  [1760/17668] intraday_10689.csv.gz  in=193,869,957 out=19,438,427 elapsed=51.3s

  [1761/17668] intraday_10691.csv.gz  in=193,882,998 out=19,451,468 elapsed=51.3s

  [1762/17668] intraday_10692.csv.gz  in=193,893,905 out=19,462,375 elapsed=51.3s

  [1763/17668] intraday_10693.csv.gz  in=193,905,003 out=19,473,473 elapsed=51.3s

  [1764/17668] intraday_10695.csv.gz  in=193,916,121 out=19,484,591 elapsed=51.3s

  [1765/17668] intraday_10694.csv.gz  in=193,930,799 out=19,499,269 elapsed=51.3s

  [1766/17668] intraday_10696.csv.gz  in=193,943,208 out=19,511,678 elapsed=51.4s

  [1767/17668] intraday_10697.csv.gz  in=193,955,324 out=19,523,794 elapsed=51.4s

  [1768/17668] intraday_10698.csv.gz  in=193,968,370 out=19,536,840 elapsed=51.4s

  [1769/17668] intraday_10699.csv.gz  in=193,978,838 out=19,547,308 elapsed=51.4s

  [1770/17668] intraday_1070.csv.gz  in=193,994,495 out=19,547,308 elapsed=51.4s

  [1771/17668] intraday_10700.csv.gz  in=194,009,802 out=19,562,615 elapsed=51.4s

  [1772/17668] intraday_10702.csv.gz  in=194,022,333 out=19,575,146 elapsed=51.4s

  [1773/17668] intraday_10701.csv.gz  in=194,037,499 out=19,590,312 elapsed=51.4s

  [1774/17668] intraday_10703.csv.gz  in=194,050,795 out=19,603,608 elapsed=51.4s

  [1775/17668] intraday_10704.csv.gz  in=194,066,351 out=19,619,164 elapsed=51.5s

  [1776/17668] intraday_10705.csv.gz  in=194,083,548 out=19,636,361 elapsed=51.5s

  [1777/17668] intraday_10706.csv.gz  in=194,097,466 out=19,650,279 elapsed=51.5s

  [1778/17668] intraday_10708.csv.gz  in=194,109,406 out=19,662,219 elapsed=51.5s

  [1779/17668] intraday_10707.csv.gz  in=194,123,170 out=19,675,983 elapsed=51.5s

  [1780/17668] intraday_10709.csv.gz  in=194,134,473 out=19,687,286 elapsed=51.5s

  [1781/17668] intraday_1071.csv.gz  in=194,144,395 out=19,687,286 elapsed=51.5s

  [1782/17668] intraday_10710.csv.gz  in=194,154,172 out=19,697,063 elapsed=51.5s

  [1783/17668] intraday_10711.csv.gz  in=194,166,657 out=19,709,548 elapsed=51.5s

  [1784/17668] intraday_10712.csv.gz  in=194,178,008 out=19,720,899 elapsed=51.6s

  [1785/17668] intraday_10713.csv.gz  in=194,190,629 out=19,733,520 elapsed=51.6s

  [1786/17668] intraday_10714.csv.gz  in=194,202,790 out=19,745,681 elapsed=51.6s

  [1787/17668] intraday_10715.csv.gz  in=194,217,638 out=19,760,529 elapsed=51.6s

  [1788/17668] intraday_10716.csv.gz  in=194,228,215 out=19,771,106 elapsed=51.6s

  [1789/17668] intraday_10717.csv.gz  in=194,239,198 out=19,782,089 elapsed=51.6s

  [1790/17668] intraday_10718.csv.gz  in=194,251,767 out=19,794,658 elapsed=51.6s

  [1791/17668] intraday_10719.csv.gz  in=194,263,025 out=19,805,916 elapsed=51.7s

  [1792/17668] intraday_1072.csv.gz  in=194,289,774 out=19,805,916 elapsed=51.7s

  [1793/17668] intraday_10720.csv.gz  in=194,301,410 out=19,817,552 elapsed=51.7s

  [1794/17668] intraday_10721.csv.gz  in=194,316,292 out=19,832,434 elapsed=51.7s

  [1795/17668] intraday_10722.csv.gz  in=194,331,243 out=19,847,385 elapsed=51.7s

  [1796/17668] intraday_10723.csv.gz  in=194,345,545 out=19,861,687 elapsed=51.7s

  [1797/17668] intraday_10724.csv.gz  in=194,361,273 out=19,877,415 elapsed=51.7s

  [1798/17668] intraday_10726.csv.gz  in=194,371,697 out=19,887,839 elapsed=51.7s

  [1799/17668] intraday_10725.csv.gz  in=194,383,023 out=19,899,165 elapsed=51.7s

  [1800/17668] intraday_10727.csv.gz  in=194,396,349 out=19,912,491 elapsed=51.7s

  [1801/17668] intraday_10728.csv.gz  in=194,407,066 out=19,923,208 elapsed=51.8s

  [1802/17668] intraday_1073.csv.gz  in=194,418,157 out=19,923,208 elapsed=51.8s

  [1803/17668] intraday_10729.csv.gz  in=194,428,206 out=19,933,257 elapsed=51.8s

  [1804/17668] intraday_10730.csv.gz  in=194,434,425 out=19,939,476 elapsed=51.8s

  [1805/17668] intraday_10731.csv.gz  in=194,444,008 out=19,949,059 elapsed=51.8s

  [1806/17668] intraday_10734.csv.gz  in=194,444,009 out=19,949,060 elapsed=51.8s

  [1807/17668] intraday_10733.csv.gz  in=194,444,015 out=19,949,066 elapsed=51.8s

  [1808/17668] intraday_10732.csv.gz  in=194,452,238 out=19,957,289 elapsed=51.8s

  [1809/17668] intraday_10735.csv.gz  in=194,452,241 out=19,957,292 elapsed=51.8s

  [1810/17668] intraday_10737.csv.gz  in=194,452,248 out=19,957,299 elapsed=51.8s

  [1811/17668] intraday_10736.csv.gz  in=194,452,252 out=19,957,303 elapsed=51.8s

  [1812/17668] intraday_10738.csv.gz  in=194,452,254 out=19,957,305 elapsed=51.8s

  [1813/17668] intraday_10739.csv.gz  in=194,452,255 out=19,957,306 elapsed=51.8s

  [1814/17668] intraday_10740.csv.gz  in=194,452,260 out=19,957,311 elapsed=51.8s

  [1815/17668] intraday_10741.csv.gz  in=194,452,263 out=19,957,314 elapsed=51.8s

  [1816/17668] intraday_10742.csv.gz  in=194,452,266 out=19,957,317 elapsed=51.8s

  [1817/17668] intraday_10744.csv.gz  in=194,452,268 out=19,957,319 elapsed=51.9s

  [1818/17668] intraday_10743.csv.gz  in=194,452,271 out=19,957,322 elapsed=51.9s

  [1819/17668] intraday_1074.csv.gz  in=194,468,712 out=19,957,322 elapsed=51.9s

  [1820/17668] intraday_10746.csv.gz  in=194,468,717 out=19,957,327 elapsed=51.9s

  [1821/17668] intraday_10747.csv.gz  in=194,468,719 out=19,957,329 elapsed=51.9s

  [1822/17668] intraday_10748.csv.gz  in=194,468,720 out=19,957,330 elapsed=51.9s

  [1823/17668] intraday_10749.csv.gz  in=194,468,722 out=19,957,332 elapsed=51.9s

  [1824/17668] intraday_10745.csv.gz  in=194,470,978 out=19,957,988 elapsed=51.9s

  [1825/17668] intraday_10750.csv.gz  in=194,470,980 out=19,957,990 elapsed=51.9s

  [1826/17668] intraday_10751.csv.gz  in=194,470,983 out=19,957,993 elapsed=51.9s

  [1827/17668] intraday_10752.csv.gz  in=194,470,984 out=19,957,994 elapsed=51.9s

  [1828/17668] intraday_1075.csv.gz  in=194,484,232 out=19,957,994 elapsed=51.9s

  [1829/17668] intraday_10755.csv.gz  in=194,484,233 out=19,957,995 elapsed=51.9s

  [1830/17668] intraday_10754.csv.gz  in=194,484,234 out=19,957,996 elapsed=51.9s

  [1831/17668] intraday_10753.csv.gz  in=194,484,402 out=19,958,164 elapsed=51.9s

  [1832/17668] intraday_10756.csv.gz  in=194,484,404 out=19,958,166 elapsed=51.9s

  [1833/17668] intraday_10757.csv.gz  in=194,484,407 out=19,958,169 elapsed=51.9s

  [1834/17668] intraday_10759.csv.gz  in=194,484,408 out=19,958,170 elapsed=51.9s

  [1835/17668] intraday_10758.csv.gz  in=194,484,659 out=19,958,421 elapsed=51.9s

  [1836/17668] intraday_10760.csv.gz  in=194,484,660 out=19,958,422 elapsed=52.0s

  [1837/17668] intraday_10761.csv.gz  in=194,484,663 out=19,958,425 elapsed=52.0s

  [1838/17668] intraday_10762.csv.gz  in=194,484,665 out=19,958,427 elapsed=52.0s

  [1839/17668] intraday_10763.csv.gz  in=194,484,666 out=19,958,428 elapsed=52.0s

  [1840/17668] intraday_1076.csv.gz  in=194,499,960 out=19,958,428 elapsed=52.0s

  [1841/17668] intraday_10764.csv.gz  in=194,499,961 out=19,958,429 elapsed=52.0s

  [1842/17668] intraday_10765.csv.gz  in=194,499,962 out=19,958,430 elapsed=52.0s

  [1843/17668] intraday_10766.csv.gz  in=194,499,963 out=19,958,431 elapsed=52.0s

  [1844/17668] intraday_10767.csv.gz  in=194,499,965 out=19,958,433 elapsed=52.0s

  [1845/17668] intraday_10769.csv.gz  in=194,503,018 out=19,959,607 elapsed=52.0s

  [1846/17668] intraday_10768.csv.gz  in=194,503,038 out=19,959,627 elapsed=52.0s

  [1847/17668] intraday_10770.csv.gz  in=194,503,042 out=19,959,631 elapsed=52.0s

  [1848/17668] intraday_10773.csv.gz  in=194,503,043 out=19,959,632 elapsed=52.0s

  [1849/17668] intraday_10771.csv.gz  in=194,503,044 out=19,959,633 elapsed=52.0s

  [1850/17668] intraday_10772.csv.gz  in=194,503,045 out=19,959,634 elapsed=52.0s

  [1851/17668] intraday_10774.csv.gz  in=194,503,046 out=19,959,635 elapsed=52.0s

  [1852/17668] intraday_10776.csv.gz  in=194,503,050 out=19,959,639 elapsed=52.0s

  [1853/17668] intraday_10775.csv.gz  in=194,503,056 out=19,959,645 elapsed=52.0s

  [1854/17668] intraday_1077.csv.gz  in=194,516,100 out=19,959,645 elapsed=52.0s

  [1855/17668] intraday_10777.csv.gz  in=194,516,101 out=19,959,646 elapsed=52.0s

  [1856/17668] intraday_10778.csv.gz  in=194,516,105 out=19,959,650 elapsed=52.1s

  [1857/17668] intraday_10779.csv.gz  in=194,516,107 out=19,959,652 elapsed=52.1s

  [1858/17668] intraday_10780.csv.gz  in=194,516,109 out=19,959,654 elapsed=52.1s

  [1859/17668] intraday_10782.csv.gz  in=194,516,113 out=19,959,658 elapsed=52.1s

  [1860/17668] intraday_10781.csv.gz  in=194,516,114 out=19,959,659 elapsed=52.1s

  [1861/17668] intraday_10783.csv.gz  in=194,516,115 out=19,959,660 elapsed=52.1s

  [1862/17668] intraday_1078.csv.gz  in=194,528,837 out=19,959,660 elapsed=52.1s

  [1863/17668] intraday_10784.csv.gz  in=194,528,841 out=19,959,664 elapsed=52.1s

  [1864/17668] intraday_10785.csv.gz  in=194,528,842 out=19,959,665 elapsed=52.1s

  [1865/17668] intraday_10786.csv.gz  in=194,528,843 out=19,959,666 elapsed=52.1s

  [1866/17668] intraday_10789.csv.gz  in=194,528,847 out=19,959,670 elapsed=52.1s

  [1867/17668] intraday_10788.csv.gz  in=194,528,854 out=19,959,677 elapsed=52.1s

  [1868/17668] intraday_10787.csv.gz  in=194,528,896 out=19,959,719 elapsed=52.1s

  [1869/17668] intraday_10790.csv.gz  in=194,528,898 out=19,959,721 elapsed=52.1s

  [1870/17668] intraday_10791.csv.gz  in=194,528,903 out=19,959,726 elapsed=52.1s

  [1871/17668] intraday_10793.csv.gz  in=194,528,904 out=19,959,727 elapsed=52.1s

  [1872/17668] intraday_10792.csv.gz  in=194,531,104 out=19,961,210 elapsed=52.1s

  [1873/17668] intraday_10794.csv.gz  in=194,531,107 out=19,961,213 elapsed=52.1s

  [1874/17668] intraday_10795.csv.gz  in=194,531,111 out=19,961,217 elapsed=52.1s

  [1875/17668] intraday_10797.csv.gz  in=194,531,112 out=19,961,218 elapsed=52.1s

  [1876/17668] intraday_1079.csv.gz  in=194,546,728 out=19,961,218 elapsed=52.2s

  [1877/17668] intraday_10796.csv.gz  in=194,546,729 out=19,961,219 elapsed=52.2s

  [1878/17668] intraday_10798.csv.gz  in=194,546,731 out=19,961,221 elapsed=52.2s

  [1879/17668] intraday_10799.csv.gz  in=194,546,733 out=19,961,223 elapsed=52.2s

  [1880/17668] intraday_10800.csv.gz  in=194,546,735 out=19,961,225 elapsed=52.2s

  [1881/17668] intraday_1080.csv.gz  in=194,559,642 out=19,961,225 elapsed=52.2s

  [1882/17668] intraday_10802.csv.gz  in=194,559,643 out=19,961,226 elapsed=52.2s

  [1883/17668] intraday_10803.csv.gz  in=194,559,646 out=19,961,229 elapsed=52.2s

  [1884/17668] intraday_10801.csv.gz  in=194,559,648 out=19,961,231 elapsed=52.2s

  [1885/17668] intraday_10805.csv.gz  in=194,559,651 out=19,961,234 elapsed=52.2s

  [1886/17668] intraday_10806.csv.gz  in=194,559,654 out=19,961,237 elapsed=52.2s

  [1887/17668] intraday_10807.csv.gz  in=194,559,655 out=19,961,238 elapsed=52.2s

  [1888/17668] intraday_10804.csv.gz  in=194,559,756 out=19,961,339 elapsed=52.2s

  [1889/17668] intraday_10809.csv.gz  in=194,559,757 out=19,961,340 elapsed=52.2s

  [1890/17668] intraday_10808.csv.gz  in=194,559,760 out=19,961,343 elapsed=52.2s

  [1891/17668] intraday_10811.csv.gz  in=194,559,763 out=19,961,346 elapsed=52.2s

  [1892/17668] intraday_10812.csv.gz  in=194,559,765 out=19,961,348 elapsed=52.2s

  [1893/17668] intraday_1081.csv.gz  in=194,572,971 out=19,961,348 elapsed=52.2s

  [1894/17668] intraday_10810.csv.gz  in=194,579,658 out=19,963,833 elapsed=52.3s

  [1895/17668] intraday_10813.csv.gz  in=194,579,661 out=19,963,836 elapsed=52.3s

  [1896/17668] intraday_10815.csv.gz  in=194,579,664 out=19,963,839 elapsed=52.3s

  [1897/17668] intraday_10814.csv.gz  in=194,579,976 out=19,964,151 elapsed=52.3s

  [1898/17668] intraday_10818.csv.gz  in=194,579,979 out=19,964,154 elapsed=52.3s

  [1899/17668] intraday_10817.csv.gz  in=194,580,027 out=19,964,202 elapsed=52.3s

  [1900/17668] intraday_10816.csv.gz  in=194,583,648 out=19,965,776 elapsed=52.3s

  [1901/17668] intraday_10819.csv.gz  in=194,583,656 out=19,965,784 elapsed=52.3s

  [1902/17668] intraday_10820.csv.gz  in=194,583,657 out=19,965,785 elapsed=52.3s

  [1903/17668] intraday_10821.csv.gz  in=194,583,658 out=19,965,786 elapsed=52.3s

  [1904/17668] intraday_10823.csv.gz  in=194,583,661 out=19,965,789 elapsed=52.3s

  [1905/17668] intraday_10822.csv.gz  in=194,583,761 out=19,965,889 elapsed=52.3s

  [1906/17668] intraday_10824.csv.gz  in=194,583,766 out=19,965,894 elapsed=52.3s

  [1907/17668] intraday_10825.csv.gz  in=194,583,773 out=19,965,901 elapsed=52.3s

  [1908/17668] intraday_10826.csv.gz  in=194,583,786 out=19,965,914 elapsed=52.3s

  [1909/17668] intraday_1082.csv.gz  in=194,604,881 out=19,965,914 elapsed=52.3s

  [1910/17668] intraday_10827.csv.gz  in=194,604,883 out=19,965,916 elapsed=52.3s

  [1911/17668] intraday_10829.csv.gz  in=194,604,888 out=19,965,921 elapsed=52.3s

  [1912/17668] intraday_10828.csv.gz  in=194,604,926 out=19,965,959 elapsed=52.3s

  [1913/17668] intraday_10831.csv.gz  in=194,604,932 out=19,965,965 elapsed=52.4s

  [1914/17668] intraday_10830.csv.gz  in=194,604,939 out=19,965,972 elapsed=52.4s

  [1915/17668] intraday_10832.csv.gz  in=194,604,943 out=19,965,976 elapsed=52.4s

  [1916/17668] intraday_1083.csv.gz  in=194,618,839 out=19,965,976 elapsed=52.4s

  [1917/17668] intraday_10833.csv.gz  in=194,618,847 out=19,965,984 elapsed=52.4s

  [1918/17668] intraday_10836.csv.gz  in=194,618,850 out=19,965,987 elapsed=52.4s

  [1919/17668] intraday_10837.csv.gz  in=194,618,852 out=19,965,989 elapsed=52.4s

  [1920/17668] intraday_10835.csv.gz  in=194,619,113 out=19,966,250 elapsed=52.4s

  [1921/17668] intraday_10838.csv.gz  in=194,619,117 out=19,966,254 elapsed=52.4s

  [1922/17668] intraday_10834.csv.gz  in=194,621,662 out=19,967,002 elapsed=52.4s

  [1923/17668] intraday_10839.csv.gz  in=194,621,695 out=19,967,035 elapsed=52.4s

  [1924/17668] intraday_10840.csv.gz  in=194,621,698 out=19,967,038 elapsed=52.4s

  [1925/17668] intraday_10842.csv.gz  in=194,621,707 out=19,967,047 elapsed=52.4s

  [1926/17668] intraday_10843.csv.gz  in=194,621,709 out=19,967,049 elapsed=52.4s

  [1927/17668] intraday_1084.csv.gz  in=194,634,902 out=19,967,049 elapsed=52.4s

  [1928/17668] intraday_10841.csv.gz  in=194,634,903 out=19,967,050 elapsed=52.4s

  [1929/17668] intraday_10846.csv.gz  in=194,634,907 out=19,967,054 elapsed=52.4s

  [1930/17668] intraday_10845.csv.gz  in=194,634,912 out=19,967,059 elapsed=52.4s

  [1931/17668] intraday_10844.csv.gz  in=194,635,230 out=19,967,165 elapsed=52.4s

  [1932/17668] intraday_10848.csv.gz  in=194,635,233 out=19,967,168 elapsed=52.4s

  [1933/17668] intraday_10847.csv.gz  in=194,635,237 out=19,967,172 elapsed=52.4s

  [1934/17668] intraday_10849.csv.gz  in=194,635,240 out=19,967,175 elapsed=52.5s

  [1935/17668] intraday_10852.csv.gz  in=194,635,255 out=19,967,190 elapsed=52.5s

  [1936/17668] intraday_10851.csv.gz  in=194,635,258 out=19,967,193 elapsed=52.5s

  [1937/17668] intraday_10850.csv.gz  in=194,635,261 out=19,967,196 elapsed=52.5s

  [1938/17668] intraday_10853.csv.gz  in=194,635,265 out=19,967,200 elapsed=52.5s

  [1939/17668] intraday_1085.csv.gz  in=194,648,438 out=19,967,200 elapsed=52.5s

  [1940/17668] intraday_10856.csv.gz  in=194,648,440 out=19,967,202 elapsed=52.5s

  [1941/17668] intraday_10854.csv.gz  in=194,648,441 out=19,967,203 elapsed=52.5s

  [1942/17668] intraday_10855.csv.gz  in=194,648,446 out=19,967,208 elapsed=52.5s

  [1943/17668] intraday_10858.csv.gz  in=194,648,447 out=19,967,209 elapsed=52.5s

  [1944/17668] intraday_10857.csv.gz  in=194,649,023 out=19,967,586 elapsed=52.5s

  [1945/17668] intraday_10859.csv.gz  in=194,649,682 out=19,967,827 elapsed=52.5s

  [1946/17668] intraday_10860.csv.gz  in=194,649,775 out=19,967,920 elapsed=52.5s

  [1947/17668] intraday_1086.csv.gz  in=194,660,242 out=19,967,920 elapsed=52.5s

  [1948/17668] intraday_10862.csv.gz  in=194,660,257 out=19,967,935 elapsed=52.5s

  [1949/17668] intraday_10861.csv.gz  in=194,660,557 out=19,968,047 elapsed=52.5s

  [1950/17668] intraday_10863.csv.gz  in=194,660,575 out=19,968,065 elapsed=52.6s

  [1951/17668] intraday_10864.csv.gz  in=194,661,350 out=19,968,840 elapsed=52.6s

  [1952/17668] intraday_10866.csv.gz  in=194,662,442 out=19,969,050 elapsed=52.6s

  [1953/17668] intraday_10865.csv.gz  in=194,662,583 out=19,969,191 elapsed=52.6s

  [1954/17668] intraday_10867.csv.gz  in=194,662,776 out=19,969,384 elapsed=52.6s

  [1955/17668] intraday_10868.csv.gz  in=194,665,010 out=19,971,618 elapsed=52.6s

  [1956/17668] intraday_10869.csv.gz  in=194,665,424 out=19,972,032 elapsed=52.6s

  [1957/17668] intraday_10871.csv.gz  in=194,665,666 out=19,972,274 elapsed=52.6s

  [1958/17668] intraday_1087.csv.gz  in=194,678,961 out=19,972,274 elapsed=52.6s

  [1959/17668] intraday_10872.csv.gz  in=194,679,067 out=19,972,380 elapsed=52.6s

  [1960/17668] intraday_10870.csv.gz  in=194,691,964 out=19,976,849 elapsed=52.6s

  [1961/17668] intraday_10874.csv.gz  in=194,692,569 out=19,977,454 elapsed=52.6s

  [1962/17668] intraday_10875.csv.gz  in=194,692,578 out=19,977,463 elapsed=52.6s

  [1963/17668] intraday_10873.csv.gz  in=194,692,653 out=19,977,538 elapsed=52.6s

  [1964/17668] intraday_10876.csv.gz  in=194,696,348 out=19,978,556 elapsed=52.7s

  [1965/17668] intraday_10878.csv.gz  in=194,696,621 out=19,978,829 elapsed=52.7s

  [1966/17668] intraday_10877.csv.gz  in=194,696,742 out=19,978,852 elapsed=52.7s

  [1967/17668] intraday_10880.csv.gz  in=194,696,786 out=19,978,896 elapsed=52.7s

  [1968/17668] intraday_10879.csv.gz  in=194,696,879 out=19,978,989 elapsed=52.7s

  [1969/17668] intraday_1088.csv.gz  in=194,709,084 out=19,978,989 elapsed=52.7s

  [1970/17668] intraday_10881.csv.gz  in=194,710,361 out=19,980,266 elapsed=52.7s

  [1971/17668] intraday_10882.csv.gz  in=194,713,834 out=19,981,264 elapsed=52.7s

  [1972/17668] intraday_10883.csv.gz  in=194,714,234 out=19,981,664 elapsed=52.7s

  [1973/17668] intraday_10884.csv.gz  in=194,714,253 out=19,981,683 elapsed=52.7s

  [1974/17668] intraday_10886.csv.gz  in=194,714,266 out=19,981,696 elapsed=52.7s

  [1975/17668] intraday_10885.csv.gz  in=194,714,385 out=19,981,815 elapsed=52.7s

  [1976/17668] intraday_10888.csv.gz  in=194,714,946 out=19,982,267 elapsed=52.8s

  [1977/17668] intraday_10887.csv.gz  in=194,715,047 out=19,982,368 elapsed=52.8s

  [1978/17668] intraday_1089.csv.gz  in=194,725,931 out=19,982,368 elapsed=52.8s

  [1979/17668] intraday_10889.csv.gz  in=194,726,057 out=19,982,494 elapsed=52.8s

  [1980/17668] intraday_10892.csv.gz  in=194,726,202 out=19,982,639 elapsed=52.8s

  [1981/17668] intraday_10890.csv.gz  in=194,726,344 out=19,982,781 elapsed=52.8s

  [1982/17668] intraday_10891.csv.gz  in=194,726,655 out=19,983,092 elapsed=52.8s

  [1983/17668] intraday_10893.csv.gz  in=194,726,791 out=19,983,228 elapsed=52.8s

  [1984/17668] intraday_10896.csv.gz  in=194,726,817 out=19,983,254 elapsed=52.8s

  [1985/17668] intraday_10895.csv.gz  in=194,727,081 out=19,983,518 elapsed=52.8s

  [1986/17668] intraday_10894.csv.gz  in=194,727,172 out=19,983,609 elapsed=52.8s

  [1987/17668] intraday_10897.csv.gz  in=194,727,316 out=19,983,753 elapsed=52.8s

  [1988/17668] intraday_10899.csv.gz  in=194,727,619 out=19,984,056 elapsed=52.8s

  [1989/17668] intraday_1090.csv.gz  in=194,735,424 out=19,984,056 elapsed=52.8s

  [1990/17668] intraday_10898.csv.gz  in=194,737,255 out=19,984,591 elapsed=52.8s

  [1991/17668] intraday_10900.csv.gz  in=194,737,289 out=19,984,625 elapsed=52.8s

  [1992/17668] intraday_10902.csv.gz  in=194,737,319 out=19,984,655 elapsed=52.9s

  [1993/17668] intraday_10904.csv.gz  in=194,737,321 out=19,984,657 elapsed=52.9s

  [1994/17668] intraday_10901.csv.gz  in=194,738,187 out=19,985,523 elapsed=52.9s

  [1995/17668] intraday_10903.csv.gz  in=194,738,199 out=19,985,535 elapsed=52.9s

  [1996/17668] intraday_10905.csv.gz  in=194,738,208 out=19,985,544 elapsed=52.9s

  [1997/17668] intraday_10909.csv.gz  in=194,738,217 out=19,985,553 elapsed=52.9s

  [1998/17668] intraday_10906.csv.gz  in=194,738,395 out=19,985,731 elapsed=52.9s

  [1999/17668] intraday_10908.csv.gz  in=194,740,576 out=19,986,465 elapsed=52.9s

  [2000/17668] intraday_10907.csv.gz  in=194,741,278 out=19,987,167 elapsed=52.9s

  [2001/17668] intraday_10910.csv.gz  in=194,741,333 out=19,987,222 elapsed=52.9s

  [2002/17668] intraday_1091.csv.gz  in=194,753,787 out=19,987,222 elapsed=53.0s

  [2003/17668] intraday_10912.csv.gz  in=194,765,449 out=19,998,884 elapsed=53.0s

  [2004/17668] intraday_10911.csv.gz  in=194,781,414 out=20,014,849 elapsed=53.0s

  [2005/17668] intraday_10913.csv.gz  in=194,795,259 out=20,028,694 elapsed=53.0s

  [2006/17668] intraday_10914.csv.gz  in=194,805,461 out=20,038,896 elapsed=53.0s

  [2007/17668] intraday_10916.csv.gz  in=194,819,352 out=20,052,787 elapsed=53.0s

  [2008/17668] intraday_10917.csv.gz  in=194,833,870 out=20,067,305 elapsed=53.0s

  [2009/17668] intraday_10918.csv.gz  in=194,844,969 out=20,078,404 elapsed=53.1s

  [2010/17668] intraday_10915.csv.gz  in=194,856,895 out=20,090,330 elapsed=53.1s

  [2011/17668] intraday_1092.csv.gz  in=194,863,206 out=20,090,330 elapsed=53.1s

  [2012/17668] intraday_10919.csv.gz  in=194,874,308 out=20,101,432 elapsed=53.1s

  [2013/17668] intraday_10922.csv.gz  in=194,885,131 out=20,112,255 elapsed=53.1s

  [2014/17668] intraday_10920.csv.gz  in=194,898,602 out=20,125,726 elapsed=53.1s

  [2015/17668] intraday_10921.csv.gz  in=194,911,528 out=20,138,652 elapsed=53.1s

  [2016/17668] intraday_10923.csv.gz  in=194,924,696 out=20,151,820 elapsed=53.1s

  [2017/17668] intraday_10925.csv.gz  in=194,933,936 out=20,161,060 elapsed=53.1s

  [2018/17668] intraday_10924.csv.gz  in=194,949,014 out=20,176,138 elapsed=53.1s

  [2019/17668] intraday_10926.csv.gz  in=194,959,164 out=20,186,288 elapsed=53.2s

  [2020/17668] intraday_10927.csv.gz  in=194,973,460 out=20,200,584 elapsed=53.2s

  [2021/17668] intraday_10929.csv.gz  in=194,985,775 out=20,212,899 elapsed=53.2s

  [2022/17668] intraday_1093.csv.gz  in=195,000,644 out=20,212,899 elapsed=53.2s

  [2023/17668] intraday_10930.csv.gz  in=195,010,988 out=20,223,243 elapsed=53.2s

  [2024/17668] intraday_10928.csv.gz  in=195,025,419 out=20,237,674 elapsed=53.2s

  [2025/17668] intraday_10931.csv.gz  in=195,036,739 out=20,248,994 elapsed=53.2s

  [2026/17668] intraday_10932.csv.gz  in=195,053,385 out=20,262,759 elapsed=53.2s

  [2027/17668] intraday_10934.csv.gz  in=195,066,015 out=20,275,389 elapsed=53.3s

  [2028/17668] intraday_10933.csv.gz  in=195,077,482 out=20,286,856 elapsed=53.3s

  [2029/17668] intraday_10935.csv.gz  in=195,089,998 out=20,299,372 elapsed=53.3s

  [2030/17668] intraday_10936.csv.gz  in=195,100,659 out=20,310,033 elapsed=53.3s

  [2031/17668] intraday_10939.csv.gz  in=195,111,123 out=20,320,497 elapsed=53.3s

  [2032/17668] intraday_10937.csv.gz  in=195,133,849 out=20,337,244 elapsed=53.3s

  [2033/17668] intraday_10938.csv.gz  in=195,144,607 out=20,348,002 elapsed=53.3s

  [2034/17668] intraday_1094.csv.gz  in=195,159,395 out=20,348,002 elapsed=53.3s

  [2035/17668] intraday_10940.csv.gz  in=195,172,591 out=20,361,198 elapsed=53.4s

  [2036/17668] intraday_10941.csv.gz  in=195,187,708 out=20,376,315 elapsed=53.4s

  [2037/17668] intraday_10943.csv.gz  in=195,196,894 out=20,385,485 elapsed=53.4s

  [2038/17668] intraday_10942.csv.gz  in=195,210,527 out=20,399,118 elapsed=53.4s

  [2039/17668] intraday_10944.csv.gz  in=195,221,468 out=20,410,059 elapsed=53.4s

  [2040/17668] intraday_10948.csv.gz  in=195,233,383 out=20,421,974 elapsed=53.5s

  [2041/17668] intraday_10945.csv.gz  in=195,246,998 out=20,435,589 elapsed=53.5s

  [2042/17668] intraday_10946.csv.gz  in=195,257,939 out=20,446,530 elapsed=53.5s

  [2043/17668] intraday_10947.csv.gz  in=195,268,883 out=20,457,474 elapsed=53.5s

  [2044/17668] intraday_10949.csv.gz  in=195,279,383 out=20,467,974 elapsed=53.5s

  [2045/17668] intraday_1095.csv.gz  in=195,291,322 out=20,467,974 elapsed=53.5s

  [2046/17668] intraday_10951.csv.gz  in=195,301,213 out=20,477,865 elapsed=53.5s

  [2047/17668] intraday_10950.csv.gz  in=195,311,151 out=20,487,803 elapsed=53.5s

  [2048/17668] intraday_10952.csv.gz  in=195,321,776 out=20,498,428 elapsed=53.5s

  [2049/17668] intraday_10953.csv.gz  in=195,335,037 out=20,511,689 elapsed=53.5s

  [2050/17668] intraday_10954.csv.gz  in=195,347,281 out=20,523,933 elapsed=53.5s

  [2051/17668] intraday_10955.csv.gz  in=195,361,557 out=20,538,209 elapsed=53.6s

  [2052/17668] intraday_10957.csv.gz  in=195,371,867 out=20,548,519 elapsed=53.6s

  [2053/17668] intraday_10956.csv.gz  in=195,383,173 out=20,559,825 elapsed=53.6s

  [2054/17668] intraday_10958.csv.gz  in=195,394,892 out=20,571,544 elapsed=53.6s

  [2055/17668] intraday_10959.csv.gz  in=195,406,375 out=20,583,027 elapsed=53.6s

  [2056/17668] intraday_1096.csv.gz  in=195,417,949 out=20,583,027 elapsed=53.6s

  [2057/17668] intraday_10960.csv.gz  in=195,427,571 out=20,592,649 elapsed=53.6s

  [2058/17668] intraday_10961.csv.gz  in=195,438,868 out=20,603,946 elapsed=53.6s

  [2059/17668] intraday_10962.csv.gz  in=195,449,273 out=20,614,351 elapsed=53.6s

  [2060/17668] intraday_10964.csv.gz  in=195,460,391 out=20,625,469 elapsed=53.7s

  [2061/17668] intraday_10963.csv.gz  in=195,472,037 out=20,637,115 elapsed=53.7s

  [2062/17668] intraday_10966.csv.gz  in=195,485,117 out=20,650,195 elapsed=53.7s

  [2063/17668] intraday_10965.csv.gz  in=195,498,683 out=20,663,761 elapsed=53.7s

  [2064/17668] intraday_10967.csv.gz  in=195,512,098 out=20,677,176 elapsed=53.7s

  [2065/17668] intraday_10969.csv.gz  in=195,521,625 out=20,686,703 elapsed=53.7s

  [2066/17668] intraday_1097.csv.gz  in=195,536,680 out=20,686,703 elapsed=53.7s

  [2067/17668] intraday_10968.csv.gz  in=195,564,167 out=20,704,791 elapsed=53.7s

  [2068/17668] intraday_10970.csv.gz  in=195,576,398 out=20,717,022 elapsed=53.8s

  [2069/17668] intraday_10971.csv.gz  in=195,589,078 out=20,729,702 elapsed=53.8s

  [2070/17668] intraday_10972.csv.gz  in=195,599,178 out=20,739,802 elapsed=53.8s

  [2071/17668] intraday_10973.csv.gz  in=195,612,234 out=20,752,858 elapsed=53.8s

  [2072/17668] intraday_10975.csv.gz  in=195,622,841 out=20,763,465 elapsed=53.8s

  [2073/17668] intraday_10974.csv.gz  in=195,633,783 out=20,774,407 elapsed=53.8s

  [2074/17668] intraday_10976.csv.gz  in=195,644,289 out=20,784,913 elapsed=53.8s

  [2075/17668] intraday_10977.csv.gz  in=195,659,010 out=20,799,634 elapsed=53.8s

  [2076/17668] intraday_10978.csv.gz  in=195,675,587 out=20,816,211 elapsed=53.8s

  [2077/17668] intraday_10979.csv.gz  in=195,688,699 out=20,829,323 elapsed=53.8s

  [2078/17668] intraday_1098.csv.gz  in=195,703,243 out=20,829,323 elapsed=53.8s

  [2079/17668] intraday_10980.csv.gz  in=195,715,464 out=20,841,544 elapsed=53.8s

  [2080/17668] intraday_10981.csv.gz  in=195,727,336 out=20,853,416 elapsed=53.9s

  [2081/17668] intraday_10983.csv.gz  in=195,739,741 out=20,865,821 elapsed=53.9s

  [2082/17668] intraday_10984.csv.gz  in=195,754,752 out=20,880,832 elapsed=53.9s

  [2083/17668] intraday_10982.csv.gz  in=195,765,851 out=20,891,931 elapsed=53.9s

  [2084/17668] intraday_10985.csv.gz  in=195,778,235 out=20,904,315 elapsed=53.9s

  [2085/17668] intraday_10986.csv.gz  in=195,788,900 out=20,914,980 elapsed=53.9s

  [2086/17668] intraday_10987.csv.gz  in=195,801,706 out=20,927,786 elapsed=53.9s

  [2087/17668] intraday_10988.csv.gz  in=195,812,223 out=20,938,303 elapsed=54.0s

  [2088/17668] intraday_10989.csv.gz  in=195,825,462 out=20,951,542 elapsed=54.0s

  [2089/17668] intraday_1099.csv.gz  in=195,837,318 out=20,951,542 elapsed=54.0s

  [2090/17668] intraday_10990.csv.gz  in=195,847,436 out=20,961,660 elapsed=54.0s

  [2091/17668] intraday_10991.csv.gz  in=195,859,537 out=20,973,761 elapsed=54.0s

  [2092/17668] intraday_10993.csv.gz  in=195,868,214 out=20,982,438 elapsed=54.0s

  [2093/17668] intraday_10992.csv.gz  in=195,885,108 out=20,994,091 elapsed=54.0s

  [2094/17668] intraday_10995.csv.gz  in=195,898,179 out=21,007,162 elapsed=54.0s

  [2095/17668] intraday_10994.csv.gz  in=195,909,785 out=21,018,768 elapsed=54.0s

  [2096/17668] intraday_10996.csv.gz  in=195,931,899 out=21,040,882 elapsed=54.1s

  [2097/17668] intraday_10997.csv.gz  in=195,943,151 out=21,052,134 elapsed=54.1s

  [2098/17668] intraday_10998.csv.gz  in=195,954,810 out=21,063,793 elapsed=54.1s

  [2099/17668] intraday_10999.csv.gz  in=195,970,880 out=21,076,678 elapsed=54.1s

  [2100/17668] intraday_1100.csv.gz  in=195,983,560 out=21,076,678 elapsed=54.1s

  [2101/17668] intraday_11000.csv.gz  in=195,997,140 out=21,090,258 elapsed=54.1s

  [2102/17668] intraday_11002.csv.gz  in=196,013,074 out=21,106,192 elapsed=54.2s

  [2103/17668] intraday_11003.csv.gz  in=196,024,246 out=21,117,364 elapsed=54.2s

  [2104/17668] intraday_11001.csv.gz  in=196,035,121 out=21,128,239 elapsed=54.2s

  [2105/17668] intraday_11004.csv.gz  in=196,060,939 out=21,144,938 elapsed=54.2s

  [2106/17668] intraday_11005.csv.gz  in=196,073,692 out=21,157,691 elapsed=54.2s

  [2107/17668] intraday_11007.csv.gz  in=196,086,615 out=21,170,614 elapsed=54.2s

  [2108/17668] intraday_11006.csv.gz  in=196,099,930 out=21,183,929 elapsed=54.2s

  [2109/17668] intraday_11008.csv.gz  in=196,111,150 out=21,195,149 elapsed=54.2s

  [2110/17668] intraday_11009.csv.gz  in=196,124,476 out=21,208,475 elapsed=54.2s

  [2111/17668] intraday_1101.csv.gz  in=196,138,657 out=21,208,475 elapsed=54.2s

  [2112/17668] intraday_11010.csv.gz  in=196,150,327 out=21,220,145 elapsed=54.3s

  [2113/17668] intraday_11011.csv.gz  in=196,162,485 out=21,232,303 elapsed=54.3s

  [2114/17668] intraday_11012.csv.gz  in=196,174,603 out=21,244,421 elapsed=54.3s

  [2115/17668] intraday_11013.csv.gz  in=196,185,727 out=21,255,545 elapsed=54.3s

  [2116/17668] intraday_11014.csv.gz  in=196,197,830 out=21,267,648 elapsed=54.3s

  [2117/17668] intraday_11015.csv.gz  in=196,212,256 out=21,282,074 elapsed=54.3s

  [2118/17668] intraday_11016.csv.gz  in=196,224,591 out=21,294,409 elapsed=54.3s

  [2119/17668] intraday_11017.csv.gz  in=196,236,357 out=21,306,175 elapsed=54.4s

  [2120/17668] intraday_11018.csv.gz  in=196,248,776 out=21,318,594 elapsed=54.4s

  [2121/17668] intraday_11019.csv.gz  in=196,262,463 out=21,332,281 elapsed=54.4s

  [2122/17668] intraday_1102.csv.gz  in=196,277,312 out=21,332,281 elapsed=54.4s

  [2123/17668] intraday_11020.csv.gz  in=196,289,202 out=21,344,171 elapsed=54.4s

  [2124/17668] intraday_11021.csv.gz  in=196,302,566 out=21,357,535 elapsed=54.4s

  [2125/17668] intraday_11022.csv.gz  in=196,313,213 out=21,368,182 elapsed=54.4s

  [2126/17668] intraday_11024.csv.gz  in=196,325,163 out=21,380,132 elapsed=54.4s

  [2127/17668] intraday_11023.csv.gz  in=196,338,716 out=21,393,685 elapsed=54.4s

  [2128/17668] intraday_11025.csv.gz  in=196,352,312 out=21,407,281 elapsed=54.5s

  [2129/17668] intraday_11026.csv.gz  in=196,373,880 out=21,426,784 elapsed=54.5s

  [2130/17668] intraday_11027.csv.gz  in=196,389,649 out=21,442,553 elapsed=54.5s

  [2131/17668] intraday_11029.csv.gz  in=196,404,897 out=21,457,801 elapsed=54.5s

  [2132/17668] intraday_11028.csv.gz  in=196,420,641 out=21,473,545 elapsed=54.5s

  [2133/17668] intraday_1103.csv.gz  in=196,431,363 out=21,473,545 elapsed=54.5s

  [2134/17668] intraday_11030.csv.gz  in=196,447,942 out=21,490,124 elapsed=54.5s

  [2135/17668] intraday_11031.csv.gz  in=196,465,034 out=21,507,216 elapsed=54.6s

  [2136/17668] intraday_11032.csv.gz  in=196,478,433 out=21,520,615 elapsed=54.6s

  [2137/17668] intraday_11034.csv.gz  in=196,489,553 out=21,531,735 elapsed=54.6s

  [2138/17668] intraday_11033.csv.gz  in=196,501,582 out=21,543,764 elapsed=54.6s

  [2139/17668] intraday_11035.csv.gz  in=196,511,987 out=21,554,169 elapsed=54.6s

  [2140/17668] intraday_11037.csv.gz  in=196,522,678 out=21,564,860 elapsed=54.6s

  [2141/17668] intraday_11036.csv.gz  in=196,536,094 out=21,578,276 elapsed=54.6s

  [2142/17668] intraday_11039.csv.gz  in=196,549,529 out=21,591,711 elapsed=54.6s

  [2143/17668] intraday_11038.csv.gz  in=196,562,519 out=21,604,701 elapsed=54.6s

  [2144/17668] intraday_1104.csv.gz  in=196,575,204 out=21,604,701 elapsed=54.6s

  [2145/17668] intraday_11040.csv.gz  in=196,591,853 out=21,621,350 elapsed=54.7s

  [2146/17668] intraday_11041.csv.gz  in=196,602,081 out=21,631,578 elapsed=54.7s

  [2147/17668] intraday_11042.csv.gz  in=196,612,316 out=21,641,813 elapsed=54.7s

  [2148/17668] intraday_11043.csv.gz  in=196,625,020 out=21,654,517 elapsed=54.7s

  [2149/17668] intraday_11044.csv.gz  in=196,636,694 out=21,666,191 elapsed=54.7s

  [2150/17668] intraday_11045.csv.gz  in=196,648,038 out=21,677,535 elapsed=54.7s

  [2151/17668] intraday_11046.csv.gz  in=196,663,993 out=21,693,490 elapsed=54.7s

  [2152/17668] intraday_11047.csv.gz  in=196,679,877 out=21,709,374 elapsed=54.7s

  [2153/17668] intraday_11048.csv.gz  in=196,693,462 out=21,722,959 elapsed=54.7s

  [2154/17668] intraday_11049.csv.gz  in=196,708,220 out=21,737,717 elapsed=54.8s

  [2155/17668] intraday_1105.csv.gz  in=196,723,537 out=21,737,717 elapsed=54.8s

  [2156/17668] intraday_11051.csv.gz  in=196,735,341 out=21,749,521 elapsed=54.8s

  [2157/17668] intraday_11053.csv.gz  in=196,747,728 out=21,761,908 elapsed=54.8s

  [2158/17668] intraday_11050.csv.gz  in=196,758,935 out=21,773,115 elapsed=54.8s

  [2159/17668] intraday_11052.csv.gz  in=196,771,048 out=21,785,228 elapsed=54.8s

  [2160/17668] intraday_11054.csv.gz  in=196,780,795 out=21,794,975 elapsed=54.8s

  [2161/17668] intraday_11055.csv.gz  in=196,787,001 out=21,801,181 elapsed=54.8s

  [2162/17668] intraday_11056.csv.gz  in=196,797,593 out=21,811,773 elapsed=54.8s

  [2163/17668] intraday_11057.csv.gz  in=196,803,809 out=21,817,989 elapsed=54.9s

  [2164/17668] intraday_11058.csv.gz  in=196,817,842 out=21,832,022 elapsed=54.9s

  [2165/17668] intraday_11059.csv.gz  in=196,828,864 out=21,843,044 elapsed=54.9s

  [2166/17668] intraday_1106.csv.gz  in=196,840,242 out=21,843,044 elapsed=54.9s

  [2167/17668] intraday_11060.csv.gz  in=196,854,438 out=21,857,240 elapsed=54.9s

  [2168/17668] intraday_11061.csv.gz  in=196,864,775 out=21,867,577 elapsed=54.9s

  [2169/17668] intraday_11063.csv.gz  in=196,877,408 out=21,880,210 elapsed=54.9s

  [2170/17668] intraday_11062.csv.gz  in=196,889,235 out=21,892,037 elapsed=54.9s

  [2171/17668] intraday_11064.csv.gz  in=196,902,658 out=21,905,460 elapsed=54.9s

  [2172/17668] intraday_11065.csv.gz  in=196,913,071 out=21,915,873 elapsed=55.0s

  [2173/17668] intraday_11066.csv.gz  in=196,924,369 out=21,927,171 elapsed=55.0s

  [2174/17668] intraday_11067.csv.gz  in=196,937,330 out=21,940,132 elapsed=55.0s

  [2175/17668] intraday_11068.csv.gz  in=196,949,839 out=21,952,641 elapsed=55.0s

  [2176/17668] intraday_11069.csv.gz  in=196,960,177 out=21,962,979 elapsed=55.0s

  [2177/17668] intraday_1107.csv.gz  in=196,970,341 out=21,962,979 elapsed=55.0s

  [2178/17668] intraday_11070.csv.gz  in=196,982,600 out=21,975,238 elapsed=55.0s

  [2179/17668] intraday_11072.csv.gz  in=196,993,109 out=21,985,747 elapsed=55.1s

  [2180/17668] intraday_11071.csv.gz  in=197,005,821 out=21,998,459 elapsed=55.1s

  [2181/17668] intraday_11073.csv.gz  in=197,016,252 out=22,008,890 elapsed=55.1s

  [2182/17668] intraday_11074.csv.gz  in=197,029,453 out=22,022,091 elapsed=55.1s

  [2183/17668] intraday_11075.csv.gz  in=197,041,762 out=22,034,400 elapsed=55.1s

  [2184/17668] intraday_11076.csv.gz  in=197,053,930 out=22,046,568 elapsed=55.1s

  [2185/17668] intraday_11077.csv.gz  in=197,063,688 out=22,056,326 elapsed=55.1s

  [2186/17668] intraday_11078.csv.gz  in=197,075,025 out=22,067,663 elapsed=55.1s

  [2187/17668] intraday_1108.csv.gz  in=197,088,079 out=22,067,663 elapsed=55.1s

  [2188/17668] intraday_11079.csv.gz  in=197,099,154 out=22,078,738 elapsed=55.1s

  [2189/17668] intraday_11080.csv.gz  in=197,111,362 out=22,090,946 elapsed=55.2s

  [2190/17668] intraday_11081.csv.gz  in=197,123,160 out=22,102,744 elapsed=55.2s

  [2191/17668] intraday_11082.csv.gz  in=197,136,111 out=22,115,695 elapsed=55.2s

  [2192/17668] intraday_11084.csv.gz  in=197,149,334 out=22,128,918 elapsed=55.2s

  [2193/17668] intraday_11083.csv.gz  in=197,160,403 out=22,139,987 elapsed=55.2s

  [2194/17668] intraday_11085.csv.gz  in=197,171,120 out=22,150,704 elapsed=55.2s

  [2195/17668] intraday_11086.csv.gz  in=197,181,362 out=22,160,946 elapsed=55.3s

  [2196/17668] intraday_11087.csv.gz  in=197,194,662 out=22,174,246 elapsed=55.3s

  [2197/17668] intraday_11088.csv.gz  in=197,209,464 out=22,189,048 elapsed=55.3s

  [2198/17668] intraday_1109.csv.gz  in=197,222,115 out=22,189,048 elapsed=55.3s

  [2199/17668] intraday_11089.csv.gz  in=197,235,501 out=22,202,434 elapsed=55.3s

  [2200/17668] intraday_11090.csv.gz  in=197,244,830 out=22,211,763 elapsed=55.3s

  [2201/17668] intraday_11091.csv.gz  in=197,254,308 out=22,221,241 elapsed=55.3s

  [2202/17668] intraday_11092.csv.gz  in=197,266,001 out=22,232,934 elapsed=55.3s

  [2203/17668] intraday_11093.csv.gz  in=197,278,927 out=22,245,860 elapsed=55.3s

  [2204/17668] intraday_11094.csv.gz  in=197,289,094 out=22,256,027 elapsed=55.4s

  [2205/17668] intraday_11095.csv.gz  in=197,300,211 out=22,267,144 elapsed=55.4s

  [2206/17668] intraday_11097.csv.gz  in=197,309,056 out=22,275,989 elapsed=55.4s

  [2207/17668] intraday_11096.csv.gz  in=197,320,203 out=22,287,136 elapsed=55.4s

  [2208/17668] intraday_11098.csv.gz  in=197,330,194 out=22,297,127 elapsed=55.4s

  [2209/17668] intraday_11099.csv.gz  in=197,340,712 out=22,307,645 elapsed=55.4s

  [2210/17668] intraday_11101.csv.gz  in=197,353,589 out=22,319,706 elapsed=55.5s

  [2211/17668] intraday_1110.csv.gz  in=197,373,399 out=22,319,706 elapsed=55.5s

  [2212/17668] intraday_11100.csv.gz  in=197,386,588 out=22,332,895 elapsed=55.5s

  [2213/17668] intraday_11102.csv.gz  in=197,399,364 out=22,345,671 elapsed=55.5s

  [2214/17668] intraday_11105.csv.gz  in=197,410,697 out=22,357,004 elapsed=55.5s

  [2215/17668] intraday_11106.csv.gz  in=197,422,953 out=22,369,260 elapsed=55.5s

  [2216/17668] intraday_11104.csv.gz  in=197,433,015 out=22,379,322 elapsed=55.5s

  [2217/17668] intraday_11103.csv.gz  in=197,445,117 out=22,391,424 elapsed=55.5s

  [2218/17668] intraday_11107.csv.gz  in=197,453,322 out=22,399,629 elapsed=55.5s

  [2219/17668] intraday_1111.csv.gz  in=197,464,972 out=22,399,629 elapsed=55.6s

  [2220/17668] intraday_11108.csv.gz  in=197,476,488 out=22,411,145 elapsed=55.6s

  [2221/17668] intraday_11109.csv.gz  in=197,487,097 out=22,421,754 elapsed=55.6s

  [2222/17668] intraday_11110.csv.gz  in=197,497,797 out=22,432,454 elapsed=55.6s

  [2223/17668] intraday_11112.csv.gz  in=197,510,113 out=22,444,770 elapsed=55.6s

  [2224/17668] intraday_11111.csv.gz  in=197,522,306 out=22,456,963 elapsed=55.6s

  [2225/17668] intraday_11114.csv.gz  in=197,534,397 out=22,469,054 elapsed=55.6s

  [2226/17668] intraday_11113.csv.gz  in=197,546,246 out=22,480,903 elapsed=55.6s

  [2227/17668] intraday_11115.csv.gz  in=197,558,988 out=22,493,645 elapsed=55.6s

  [2228/17668] intraday_11116.csv.gz  in=197,568,137 out=22,502,794 elapsed=55.7s

  [2229/17668] intraday_11117.csv.gz  in=197,581,149 out=22,515,806 elapsed=55.7s

  [2230/17668] intraday_11119.csv.gz  in=197,591,630 out=22,526,287 elapsed=55.7s

  [2231/17668] intraday_1112.csv.gz  in=197,602,844 out=22,526,287 elapsed=55.7s

  [2232/17668] intraday_11118.csv.gz  in=197,614,472 out=22,537,915 elapsed=55.7s

  [2233/17668] intraday_11121.csv.gz  in=197,624,802 out=22,548,245 elapsed=55.7s

  [2234/17668] intraday_11120.csv.gz  in=197,636,720 out=22,560,163 elapsed=55.7s

  [2235/17668] intraday_11122.csv.gz  in=197,646,271 out=22,569,714 elapsed=55.7s

  [2236/17668] intraday_11123.csv.gz  in=197,657,164 out=22,580,607 elapsed=55.8s

  [2237/17668] intraday_11124.csv.gz  in=197,673,111 out=22,596,554 elapsed=55.8s

  [2238/17668] intraday_11125.csv.gz  in=197,685,761 out=22,609,204 elapsed=55.8s

  [2239/17668] intraday_11126.csv.gz  in=197,698,870 out=22,622,313 elapsed=55.8s

  [2240/17668] intraday_11127.csv.gz  in=197,710,324 out=22,633,767 elapsed=55.8s

  [2241/17668] intraday_11128.csv.gz  in=197,721,748 out=22,645,191 elapsed=55.8s

  [2242/17668] intraday_11129.csv.gz  in=197,732,838 out=22,656,281 elapsed=55.8s

  [2243/17668] intraday_1113.csv.gz  in=197,750,415 out=22,656,281 elapsed=55.8s

  [2244/17668] intraday_11130.csv.gz  in=197,761,905 out=22,667,771 elapsed=55.9s

  [2245/17668] intraday_11132.csv.gz  in=197,774,699 out=22,680,565 elapsed=55.9s

  [2246/17668] intraday_11133.csv.gz  in=197,785,248 out=22,691,114 elapsed=55.9s

  [2247/17668] intraday_11131.csv.gz  in=197,798,214 out=22,704,080 elapsed=55.9s

  [2248/17668] intraday_11134.csv.gz  in=197,808,137 out=22,714,003 elapsed=55.9s

  [2249/17668] intraday_11136.csv.gz  in=197,821,386 out=22,727,252 elapsed=55.9s

  [2250/17668] intraday_11135.csv.gz  in=197,832,492 out=22,738,358 elapsed=55.9s

  [2251/17668] intraday_11137.csv.gz  in=197,842,332 out=22,748,198 elapsed=56.0s

  [2252/17668] intraday_11138.csv.gz  in=197,852,516 out=22,758,382 elapsed=56.0s

  [2253/17668] intraday_1114.csv.gz  in=197,865,431 out=22,758,382 elapsed=56.0s

  [2254/17668] intraday_11139.csv.gz  in=197,873,909 out=22,766,860 elapsed=56.0s

  [2255/17668] intraday_11140.csv.gz  in=197,883,166 out=22,776,117 elapsed=56.0s

  [2256/17668] intraday_11141.csv.gz  in=197,895,164 out=22,788,115 elapsed=56.0s

  [2257/17668] intraday_11144.csv.gz  in=197,907,321 out=22,800,272 elapsed=56.0s

  [2258/17668] intraday_11145.csv.gz  in=197,917,994 out=22,810,945 elapsed=56.0s

  [2259/17668] intraday_11142.csv.gz  in=197,932,559 out=22,825,510 elapsed=56.0s

  [2260/17668] intraday_11143.csv.gz  in=197,948,814 out=22,841,765 elapsed=56.0s

  [2261/17668] intraday_11146.csv.gz  in=197,960,120 out=22,853,071 elapsed=56.1s

  [2262/17668] intraday_11147.csv.gz  in=197,972,953 out=22,865,904 elapsed=56.1s

  [2263/17668] intraday_11148.csv.gz  in=197,984,028 out=22,876,979 elapsed=56.1s

  [2264/17668] intraday_11149.csv.gz  in=197,997,673 out=22,890,624 elapsed=56.1s

  [2265/17668] intraday_1115.csv.gz  in=198,010,627 out=22,890,624 elapsed=56.1s

  [2266/17668] intraday_11150.csv.gz  in=198,021,333 out=22,901,330 elapsed=56.1s

  [2267/17668] intraday_11153.csv.gz  in=198,033,465 out=22,913,462 elapsed=56.1s

  [2268/17668] intraday_11151.csv.gz  in=198,047,165 out=22,927,162 elapsed=56.1s

  [2269/17668] intraday_11154.csv.gz  in=198,059,796 out=22,939,793 elapsed=56.2s

  [2270/17668] intraday_11152.csv.gz  in=198,071,729 out=22,951,726 elapsed=56.2s

  [2271/17668] intraday_11156.csv.gz  in=198,084,723 out=22,964,720 elapsed=56.2s

  [2272/17668] intraday_11155.csv.gz  in=198,095,464 out=22,975,461 elapsed=56.2s

  [2273/17668] intraday_11157.csv.gz  in=198,105,741 out=22,985,738 elapsed=56.2s

  [2274/17668] intraday_11158.csv.gz  in=198,117,291 out=22,997,288 elapsed=56.2s

  [2275/17668] intraday_1116.csv.gz  in=198,130,266 out=22,997,288 elapsed=56.2s

  [2276/17668] intraday_11159.csv.gz  in=198,140,433 out=23,007,455 elapsed=56.2s

  [2277/17668] intraday_11161.csv.gz  in=198,152,814 out=23,019,836 elapsed=56.3s

  [2278/17668] intraday_11160.csv.gz  in=198,164,691 out=23,031,713 elapsed=56.3s

  [2279/17668] intraday_11162.csv.gz  in=198,177,083 out=23,044,105 elapsed=56.3s

  [2280/17668] intraday_11163.csv.gz  in=198,187,407 out=23,054,429 elapsed=56.3s

  [2281/17668] intraday_11165.csv.gz  in=198,199,287 out=23,066,309 elapsed=56.5s

  [2282/17668] intraday_11167.csv.gz  in=198,210,649 out=23,077,671 elapsed=56.5s

  [2283/17668] intraday_11166.csv.gz  in=198,223,585 out=23,090,607 elapsed=56.5s

  [2284/17668] intraday_11164.csv.gz  in=198,236,558 out=23,103,580 elapsed=56.5s

  [2285/17668] intraday_11169.csv.gz  in=198,249,898 out=23,116,920 elapsed=56.6s

  [2286/17668] intraday_11170.csv.gz  in=198,261,475 out=23,128,497 elapsed=56.6s

  [2287/17668] intraday_1117.csv.gz  in=198,273,500 out=23,128,497 elapsed=56.6s

  [2288/17668] intraday_11168.csv.gz  in=198,285,828 out=23,140,825 elapsed=56.6s

  [2289/17668] intraday_11171.csv.gz  in=198,295,918 out=23,150,915 elapsed=56.6s

  [2290/17668] intraday_11172.csv.gz  in=198,308,883 out=23,163,880 elapsed=56.6s

  [2291/17668] intraday_11173.csv.gz  in=198,326,343 out=23,181,340 elapsed=56.6s

  [2292/17668] intraday_11174.csv.gz  in=198,340,661 out=23,195,658 elapsed=56.6s

  [2293/17668] intraday_11175.csv.gz  in=198,354,758 out=23,209,755 elapsed=56.6s

  [2294/17668] intraday_11176.csv.gz  in=198,370,655 out=23,225,652 elapsed=56.7s

  [2295/17668] intraday_11177.csv.gz  in=198,383,335 out=23,238,332 elapsed=56.7s

  [2296/17668] intraday_11178.csv.gz  in=198,397,259 out=23,252,256 elapsed=56.7s

  [2297/17668] intraday_1118.csv.gz  in=198,407,828 out=23,252,256 elapsed=56.7s

  [2298/17668] intraday_11179.csv.gz  in=198,420,182 out=23,264,610 elapsed=56.7s

  [2299/17668] intraday_11180.csv.gz  in=198,432,250 out=23,276,678 elapsed=56.7s

  [2300/17668] intraday_11182.csv.gz  in=198,443,434 out=23,287,862 elapsed=56.7s

  [2301/17668] intraday_11181.csv.gz  in=198,454,224 out=23,298,652 elapsed=56.7s

  [2302/17668] intraday_11183.csv.gz  in=198,465,084 out=23,309,512 elapsed=56.7s

  [2303/17668] intraday_11184.csv.gz  in=198,477,240 out=23,321,668 elapsed=56.8s

  [2304/17668] intraday_11185.csv.gz  in=198,488,782 out=23,333,210 elapsed=56.8s

  [2305/17668] intraday_11186.csv.gz  in=198,502,953 out=23,347,381 elapsed=56.8s

  [2306/17668] intraday_11187.csv.gz  in=198,513,328 out=23,357,756 elapsed=56.8s

  [2307/17668] intraday_11188.csv.gz  in=198,523,867 out=23,368,295 elapsed=56.8s

  [2308/17668] intraday_11189.csv.gz  in=198,534,704 out=23,379,132 elapsed=56.8s

  [2309/17668] intraday_1119.csv.gz  in=198,548,301 out=23,379,132 elapsed=56.8s

  [2310/17668] intraday_11191.csv.gz  in=198,558,463 out=23,389,294 elapsed=56.9s

  [2311/17668] intraday_11190.csv.gz  in=198,570,222 out=23,401,053 elapsed=56.9s

  [2312/17668] intraday_11193.csv.gz  in=198,585,231 out=23,416,062 elapsed=56.9s

  [2313/17668] intraday_11192.csv.gz  in=198,599,451 out=23,430,282 elapsed=56.9s

  [2314/17668] intraday_11194.csv.gz  in=198,613,323 out=23,444,154 elapsed=56.9s

  [2315/17668] intraday_11195.csv.gz  in=198,627,191 out=23,458,022 elapsed=56.9s

  [2316/17668] intraday_11197.csv.gz  in=198,638,468 out=23,469,299 elapsed=56.9s

  [2317/17668] intraday_11196.csv.gz  in=198,651,541 out=23,482,372 elapsed=56.9s

  [2318/17668] intraday_11198.csv.gz  in=198,663,583 out=23,494,414 elapsed=57.0s

  [2319/17668] intraday_11201.csv.gz  in=198,670,655 out=23,501,486 elapsed=57.0s

  [2320/17668] intraday_1120.csv.gz  in=198,684,504 out=23,501,486 elapsed=57.0s

  [2321/17668] intraday_11200.csv.gz  in=198,697,025 out=23,514,007 elapsed=57.0s

  [2322/17668] intraday_11199.csv.gz  in=198,707,115 out=23,524,097 elapsed=57.0s

  [2323/17668] intraday_11202.csv.gz  in=198,713,776 out=23,530,758 elapsed=57.0s

  [2324/17668] intraday_11204.csv.gz  in=198,715,150 out=23,532,132 elapsed=57.0s

  [2325/17668] intraday_11203.csv.gz  in=198,727,577 out=23,544,559 elapsed=57.0s

  [2326/17668] intraday_11205.csv.gz  in=198,736,239 out=23,549,229 elapsed=57.1s

  [2327/17668] intraday_11206.csv.gz  in=198,741,356 out=23,549,952 elapsed=57.1s

  [2328/17668] intraday_11207.csv.gz  in=198,750,132 out=23,553,953 elapsed=57.1s

  [2329/17668] intraday_11209.csv.gz  in=198,760,555 out=23,564,376 elapsed=57.1s

  [2330/17668] intraday_11208.csv.gz  in=198,774,246 out=23,578,067 elapsed=57.1s

  [2331/17668] intraday_1121.csv.gz  in=198,789,454 out=23,578,067 elapsed=57.1s

  [2332/17668] intraday_11210.csv.gz  in=198,804,473 out=23,593,086 elapsed=57.1s

  [2333/17668] intraday_11212.csv.gz  in=198,815,343 out=23,603,956 elapsed=57.1s

  [2334/17668] intraday_11211.csv.gz  in=198,824,910 out=23,613,523 elapsed=57.2s

  [2335/17668] intraday_11213.csv.gz  in=198,837,255 out=23,625,868 elapsed=57.2s

  [2336/17668] intraday_11214.csv.gz  in=198,850,845 out=23,639,458 elapsed=57.2s

  [2337/17668] intraday_11215.csv.gz  in=198,859,905 out=23,648,518 elapsed=57.2s

  [2338/17668] intraday_11216.csv.gz  in=198,871,773 out=23,660,386 elapsed=57.2s

  [2339/17668] intraday_11217.csv.gz  in=198,884,449 out=23,673,062 elapsed=57.2s

  [2340/17668] intraday_11219.csv.gz  in=198,894,276 out=23,682,889 elapsed=57.2s

  [2341/17668] intraday_1122.csv.gz  in=198,910,219 out=23,682,889 elapsed=57.3s

  [2342/17668] intraday_11218.csv.gz  in=198,922,545 out=23,695,215 elapsed=57.3s

  [2343/17668] intraday_11220.csv.gz  in=198,938,367 out=23,709,289 elapsed=57.3s

  [2344/17668] intraday_11222.csv.gz  in=198,947,940 out=23,718,862 elapsed=57.3s

  [2345/17668] intraday_11221.csv.gz  in=198,959,784 out=23,730,706 elapsed=57.3s

  [2346/17668] intraday_11223.csv.gz  in=198,970,754 out=23,741,676 elapsed=57.3s

  [2347/17668] intraday_11224.csv.gz  in=198,981,854 out=23,752,776 elapsed=57.3s

  [2348/17668] intraday_11225.csv.gz  in=198,994,572 out=23,765,494 elapsed=57.3s

  [2349/17668] intraday_11226.csv.gz  in=199,006,037 out=23,776,959 elapsed=57.3s

  [2350/17668] intraday_11227.csv.gz  in=199,015,713 out=23,786,635 elapsed=57.3s

  [2351/17668] intraday_11229.csv.gz  in=199,027,729 out=23,798,651 elapsed=57.4s

  [2352/17668] intraday_1123.csv.gz  in=199,041,017 out=23,798,651 elapsed=57.4s

  [2353/17668] intraday_11228.csv.gz  in=199,056,901 out=23,811,181 elapsed=57.4s

  [2354/17668] intraday_11230.csv.gz  in=199,069,443 out=23,823,723 elapsed=57.4s

  [2355/17668] intraday_11231.csv.gz  in=199,081,360 out=23,835,640 elapsed=57.4s

  [2356/17668] intraday_11232.csv.gz  in=199,093,684 out=23,847,964 elapsed=57.4s

  [2357/17668] intraday_11233.csv.gz  in=199,105,785 out=23,860,065 elapsed=57.5s

  [2358/17668] intraday_11235.csv.gz  in=199,116,275 out=23,870,555 elapsed=57.5s

  [2359/17668] intraday_11234.csv.gz  in=199,127,031 out=23,881,311 elapsed=57.5s

  [2360/17668] intraday_11236.csv.gz  in=199,137,036 out=23,891,316 elapsed=57.5s

  [2361/17668] intraday_11237.csv.gz  in=199,149,735 out=23,904,015 elapsed=57.5s

  [2362/17668] intraday_1124.csv.gz  in=199,162,073 out=23,904,015 elapsed=57.5s

  [2363/17668] intraday_11238.csv.gz  in=199,176,764 out=23,918,706 elapsed=57.5s

  [2364/17668] intraday_11240.csv.gz  in=199,186,222 out=23,928,164 elapsed=57.6s

  [2365/17668] intraday_11241.csv.gz  in=199,196,356 out=23,938,298 elapsed=57.6s

  [2366/17668] intraday_11239.csv.gz  in=199,208,900 out=23,950,842 elapsed=57.6s

  [2367/17668] intraday_11242.csv.gz  in=199,220,902 out=23,962,844 elapsed=57.6s

  [2368/17668] intraday_11243.csv.gz  in=199,233,102 out=23,975,044 elapsed=57.6s

  [2369/17668] intraday_11245.csv.gz  in=199,244,546 out=23,986,488 elapsed=57.6s

  [2370/17668] intraday_11244.csv.gz  in=199,254,645 out=23,996,587 elapsed=57.6s

  [2371/17668] intraday_11246.csv.gz  in=199,265,767 out=24,007,709 elapsed=57.6s

  [2372/17668] intraday_11247.csv.gz  in=199,275,662 out=24,017,604 elapsed=57.6s

  [2373/17668] intraday_11249.csv.gz  in=199,286,631 out=24,028,573 elapsed=57.7s

  [2374/17668] intraday_11248.csv.gz  in=199,295,829 out=24,037,771 elapsed=57.7s

  [2375/17668] intraday_1125.csv.gz  in=199,308,498 out=24,037,771 elapsed=57.7s

  [2376/17668] intraday_11250.csv.gz  in=199,320,942 out=24,050,215 elapsed=57.7s

  [2377/17668] intraday_11252.csv.gz  in=199,334,523 out=24,063,796 elapsed=57.7s

  [2378/17668] intraday_11253.csv.gz  in=199,346,312 out=24,075,585 elapsed=57.7s

  [2379/17668] intraday_11251.csv.gz  in=199,356,958 out=24,086,231 elapsed=57.7s

  [2380/17668] intraday_11254.csv.gz  in=199,366,992 out=24,096,265 elapsed=57.7s

  [2381/17668] intraday_11255.csv.gz  in=199,377,720 out=24,106,993 elapsed=57.7s

  [2382/17668] intraday_11257.csv.gz  in=199,386,767 out=24,116,040 elapsed=57.8s

  [2383/17668] intraday_11256.csv.gz  in=199,398,383 out=24,127,656 elapsed=57.8s

  [2384/17668] intraday_11258.csv.gz  in=199,413,721 out=24,141,089 elapsed=57.8s

  [2385/17668] intraday_11259.csv.gz  in=199,424,364 out=24,151,732 elapsed=57.8s

  [2386/17668] intraday_1126.csv.gz  in=199,438,548 out=24,151,732 elapsed=57.8s

  [2387/17668] intraday_11260.csv.gz  in=199,449,933 out=24,163,117 elapsed=57.8s

  [2388/17668] intraday_11261.csv.gz  in=199,461,716 out=24,174,900 elapsed=57.8s

  [2389/17668] intraday_11262.csv.gz  in=199,472,559 out=24,185,743 elapsed=57.8s

  [2390/17668] intraday_11263.csv.gz  in=199,486,351 out=24,199,535 elapsed=57.8s

  [2391/17668] intraday_11264.csv.gz  in=199,499,031 out=24,212,215 elapsed=57.8s

  [2392/17668] intraday_11266.csv.gz  in=199,508,687 out=24,221,871 elapsed=57.9s

  [2393/17668] intraday_11265.csv.gz  in=199,520,596 out=24,233,780 elapsed=57.9s

  [2394/17668] intraday_11267.csv.gz  in=199,532,727 out=24,245,911 elapsed=57.9s

  [2395/17668] intraday_11268.csv.gz  in=199,544,820 out=24,258,004 elapsed=57.9s

  [2396/17668] intraday_11269.csv.gz  in=199,554,879 out=24,268,063 elapsed=57.9s

  [2397/17668] intraday_1127.csv.gz  in=199,566,819 out=24,268,063 elapsed=57.9s

  [2398/17668] intraday_11270.csv.gz  in=199,584,714 out=24,282,774 elapsed=57.9s

  [2399/17668] intraday_11271.csv.gz  in=199,595,330 out=24,293,390 elapsed=57.9s

  [2400/17668] intraday_11272.csv.gz  in=199,604,945 out=24,303,005 elapsed=57.9s

  [2401/17668] intraday_11273.csv.gz  in=199,619,211 out=24,317,271 elapsed=58.0s

  [2402/17668] intraday_11274.csv.gz  in=199,633,151 out=24,331,211 elapsed=58.0s

  [2403/17668] intraday_11275.csv.gz  in=199,643,474 out=24,341,534 elapsed=58.0s

  [2404/17668] intraday_11276.csv.gz  in=199,656,766 out=24,354,826 elapsed=58.0s

  [2405/17668] intraday_11278.csv.gz  in=199,667,785 out=24,365,845 elapsed=58.0s

  [2406/17668] intraday_11277.csv.gz  in=199,679,237 out=24,377,297 elapsed=58.0s

  [2407/17668] intraday_11279.csv.gz  in=199,691,856 out=24,389,916 elapsed=58.0s

  [2408/17668] intraday_1128.csv.gz  in=199,710,236 out=24,389,916 elapsed=58.0s

  [2409/17668] intraday_11280.csv.gz  in=199,722,042 out=24,401,722 elapsed=58.0s

  [2410/17668] intraday_11281.csv.gz  in=199,736,579 out=24,414,871 elapsed=58.1s

  [2411/17668] intraday_11282.csv.gz  in=199,750,169 out=24,428,461 elapsed=58.1s

  [2412/17668] intraday_11283.csv.gz  in=199,761,684 out=24,439,976 elapsed=58.1s

  [2413/17668] intraday_11284.csv.gz  in=199,771,606 out=24,449,898 elapsed=58.1s

  [2414/17668] intraday_11285.csv.gz  in=199,781,377 out=24,459,669 elapsed=58.1s

  [2415/17668] intraday_11286.csv.gz  in=199,794,565 out=24,472,857 elapsed=58.1s

  [2416/17668] intraday_11287.csv.gz  in=199,804,435 out=24,482,727 elapsed=58.1s

  [2417/17668] intraday_11289.csv.gz  in=199,812,791 out=24,491,083 elapsed=58.1s

  [2418/17668] intraday_1129.csv.gz  in=199,826,102 out=24,491,083 elapsed=58.1s

  [2419/17668] intraday_11288.csv.gz  in=199,836,881 out=24,501,862 elapsed=58.2s

  [2420/17668] intraday_11290.csv.gz  in=199,846,110 out=24,511,091 elapsed=58.2s

  [2421/17668] intraday_11291.csv.gz  in=199,856,929 out=24,521,910 elapsed=58.2s

  [2422/17668] intraday_11293.csv.gz  in=199,873,743 out=24,538,724 elapsed=58.2s

  [2423/17668] intraday_11292.csv.gz  in=199,887,807 out=24,552,788 elapsed=58.2s

  [2424/17668] intraday_11295.csv.gz  in=199,897,993 out=24,562,974 elapsed=58.2s

  [2425/17668] intraday_11294.csv.gz  in=199,910,077 out=24,575,058 elapsed=58.2s

  [2426/17668] intraday_11296.csv.gz  in=199,921,257 out=24,586,238 elapsed=58.2s

  [2427/17668] intraday_11297.csv.gz  in=199,934,169 out=24,599,150 elapsed=58.2s

  [2428/17668] intraday_11299.csv.gz  in=199,947,299 out=24,612,280 elapsed=58.3s

  [2429/17668] intraday_11298.csv.gz  in=199,958,397 out=24,623,378 elapsed=58.3s

  [2430/17668] intraday_1130.csv.gz  in=199,970,659 out=24,623,378 elapsed=58.3s

  [2431/17668] intraday_11300.csv.gz  in=199,980,618 out=24,633,337 elapsed=58.3s

  [2432/17668] intraday_11303.csv.gz  in=199,991,727 out=24,644,446 elapsed=58.3s

  [2433/17668] intraday_11301.csv.gz  in=200,007,693 out=24,660,412 elapsed=58.3s

  [2434/17668] intraday_11302.csv.gz  in=200,018,534 out=24,671,253 elapsed=58.3s

  [2435/17668] intraday_11305.csv.gz  in=200,029,938 out=24,682,657 elapsed=58.4s

  [2436/17668] intraday_11304.csv.gz  in=200,043,722 out=24,696,441 elapsed=58.4s

  [2437/17668] intraday_11306.csv.gz  in=200,055,491 out=24,708,210 elapsed=58.4s

  [2438/17668] intraday_11307.csv.gz  in=200,065,601 out=24,718,320 elapsed=58.4s

  [2439/17668] intraday_11308.csv.gz  in=200,077,649 out=24,730,368 elapsed=58.4s

  [2440/17668] intraday_1131.csv.gz  in=200,089,347 out=24,730,368 elapsed=58.4s

  [2441/17668] intraday_11309.csv.gz  in=200,099,058 out=24,740,079 elapsed=58.4s

  [2442/17668] intraday_11310.csv.gz  in=200,111,080 out=24,752,101 elapsed=58.4s

  [2443/17668] intraday_11311.csv.gz  in=200,122,395 out=24,763,416 elapsed=58.4s

  [2444/17668] intraday_11313.csv.gz  in=200,133,793 out=24,774,814 elapsed=58.5s

  [2445/17668] intraday_11312.csv.gz  in=200,146,772 out=24,787,793 elapsed=58.5s

  [2446/17668] intraday_11315.csv.gz  in=200,159,548 out=24,800,569 elapsed=58.5s

  [2447/17668] intraday_11314.csv.gz  in=200,171,150 out=24,812,171 elapsed=58.5s

  [2448/17668] intraday_11316.csv.gz  in=200,183,078 out=24,824,099 elapsed=58.5s

  [2449/17668] intraday_11317.csv.gz  in=200,194,226 out=24,835,247 elapsed=58.5s

  [2450/17668] intraday_11319.csv.gz  in=200,207,313 out=24,848,334 elapsed=58.5s

  [2451/17668] intraday_11318.csv.gz  in=200,219,750 out=24,860,771 elapsed=58.6s

  [2452/17668] intraday_1132.csv.gz  in=200,233,467 out=24,860,771 elapsed=58.6s

  [2453/17668] intraday_11321.csv.gz  in=200,243,924 out=24,871,228 elapsed=58.6s

  [2454/17668] intraday_11320.csv.gz  in=200,255,214 out=24,882,518 elapsed=58.6s

  [2455/17668] intraday_11322.csv.gz  in=200,267,330 out=24,894,634 elapsed=58.6s

  [2456/17668] intraday_11325.csv.gz  in=200,280,938 out=24,908,242 elapsed=58.6s

  [2457/17668] intraday_11324.csv.gz  in=200,296,116 out=24,923,420 elapsed=58.6s

  [2458/17668] intraday_11323.csv.gz  in=200,313,046 out=24,940,350 elapsed=58.7s

  [2459/17668] intraday_11326.csv.gz  in=200,329,736 out=24,957,040 elapsed=58.7s

  [2460/17668] intraday_11327.csv.gz  in=200,341,728 out=24,969,032 elapsed=58.7s

  [2461/17668] intraday_11328.csv.gz  in=200,356,979 out=24,984,283 elapsed=58.7s

  [2462/17668] intraday_11329.csv.gz  in=200,368,396 out=24,995,700 elapsed=58.7s

  [2463/17668] intraday_1133.csv.gz  in=200,382,000 out=24,995,700 elapsed=58.7s

  [2464/17668] intraday_11330.csv.gz  in=200,393,223 out=25,006,923 elapsed=58.7s

  [2465/17668] intraday_11331.csv.gz  in=200,404,770 out=25,018,470 elapsed=58.7s

  [2466/17668] intraday_11333.csv.gz  in=200,415,427 out=25,029,127 elapsed=58.7s

  [2467/17668] intraday_11334.csv.gz  in=200,427,301 out=25,041,001 elapsed=58.8s

  [2468/17668] intraday_11335.csv.gz  in=200,438,616 out=25,052,316 elapsed=58.8s

  [2469/17668] intraday_11332.csv.gz  in=200,451,370 out=25,065,070 elapsed=58.8s

  [2470/17668] intraday_11336.csv.gz  in=200,465,818 out=25,079,518 elapsed=58.8s

  [2471/17668] intraday_11337.csv.gz  in=200,478,450 out=25,092,007 elapsed=58.8s

  [2472/17668] intraday_11338.csv.gz  in=200,489,682 out=25,103,239 elapsed=58.8s

  [2473/17668] intraday_11339.csv.gz  in=200,500,490 out=25,114,047 elapsed=58.8s

  [2474/17668] intraday_11340.csv.gz  in=200,512,357 out=25,125,914 elapsed=58.8s

  [2475/17668] intraday_11341.csv.gz  in=200,524,798 out=25,132,237 elapsed=58.8s

  [2476/17668] intraday_1134.csv.gz  in=200,550,299 out=25,132,237 elapsed=58.8s

  [2477/17668] intraday_11342.csv.gz  in=200,562,875 out=25,144,813 elapsed=58.9s

  [2478/17668] intraday_11343.csv.gz  in=200,577,383 out=25,159,321 elapsed=58.9s

  [2479/17668] intraday_11345.csv.gz  in=200,591,240 out=25,173,178 elapsed=58.9s

  [2480/17668] intraday_11344.csv.gz  in=200,610,516 out=25,190,267 elapsed=58.9s

  [2481/17668] intraday_11346.csv.gz  in=200,625,843 out=25,205,594 elapsed=58.9s

  [2482/17668] intraday_11347.csv.gz  in=200,637,956 out=25,217,707 elapsed=58.9s

  [2483/17668] intraday_11348.csv.gz  in=200,649,124 out=25,228,875 elapsed=58.9s

  [2484/17668] intraday_11349.csv.gz  in=200,662,455 out=25,242,206 elapsed=59.0s

  [2485/17668] intraday_1135.csv.gz  in=200,678,499 out=25,242,206 elapsed=59.0s

  [2486/17668] intraday_11350.csv.gz  in=200,689,991 out=25,253,698 elapsed=59.0s

  [2487/17668] intraday_11351.csv.gz  in=200,699,837 out=25,263,544 elapsed=59.0s

  [2488/17668] intraday_11352.csv.gz  in=200,706,649 out=25,270,356 elapsed=59.0s

  [2489/17668] intraday_11353.csv.gz  in=200,717,771 out=25,281,478 elapsed=59.0s

  [2490/17668] intraday_11354.csv.gz  in=200,724,974 out=25,288,681 elapsed=59.0s

  [2491/17668] intraday_11355.csv.gz  in=200,738,706 out=25,302,413 elapsed=59.0s

  [2492/17668] intraday_11356.csv.gz  in=200,750,437 out=25,314,144 elapsed=59.0s

  [2493/17668] intraday_11358.csv.gz  in=200,759,737 out=25,323,444 elapsed=59.1s

  [2494/17668] intraday_11357.csv.gz  in=200,773,508 out=25,337,215 elapsed=59.1s

  [2495/17668] intraday_11359.csv.gz  in=200,784,371 out=25,348,078 elapsed=59.1s

  [2496/17668] intraday_1136.csv.gz  in=200,795,824 out=25,348,078 elapsed=59.1s

  [2497/17668] intraday_11360.csv.gz  in=200,808,903 out=25,361,157 elapsed=59.1s

  [2498/17668] intraday_11361.csv.gz  in=200,822,463 out=25,374,717 elapsed=59.1s

  [2499/17668] intraday_11362.csv.gz  in=200,833,184 out=25,385,438 elapsed=59.1s

  [2500/17668] intraday_11363.csv.gz  in=200,844,342 out=25,396,596 elapsed=59.1s

  [2501/17668] intraday_11364.csv.gz  in=200,857,222 out=25,409,476 elapsed=59.1s

  [2502/17668] intraday_11365.csv.gz  in=200,869,450 out=25,421,704 elapsed=59.1s

  [2503/17668] intraday_11366.csv.gz  in=200,879,663 out=25,431,917 elapsed=59.3s

  [2504/17668] intraday_11367.csv.gz  in=200,892,374 out=25,444,628 elapsed=59.3s

  [2505/17668] intraday_11368.csv.gz  in=200,905,034 out=25,457,288 elapsed=59.3s

  [2506/17668] intraday_11369.csv.gz  in=200,913,914 out=25,466,168 elapsed=59.4s

  [2507/17668] intraday_1137.csv.gz  in=200,927,677 out=25,466,168 elapsed=59.4s

  [2508/17668] intraday_11371.csv.gz  in=200,940,015 out=25,478,506 elapsed=59.4s

  [2509/17668] intraday_11370.csv.gz  in=200,949,516 out=25,488,007 elapsed=59.4s

  [2510/17668] intraday_11373.csv.gz  in=200,960,156 out=25,498,647 elapsed=59.4s

  [2511/17668] intraday_11372.csv.gz  in=200,973,129 out=25,511,620 elapsed=59.4s

  [2512/17668] intraday_11376.csv.gz  in=200,985,692 out=25,524,183 elapsed=59.5s

  [2513/17668] intraday_11374.csv.gz  in=201,008,455 out=25,541,161 elapsed=59.5s

  [2514/17668] intraday_11375.csv.gz  in=201,018,511 out=25,551,217 elapsed=59.5s

  [2515/17668] intraday_11378.csv.gz  in=201,029,617 out=25,562,323 elapsed=59.5s

  [2516/17668] intraday_11377.csv.gz  in=201,046,674 out=25,576,714 elapsed=59.5s

  [2517/17668] intraday_1138.csv.gz  in=201,058,122 out=25,576,714 elapsed=59.5s

  [2518/17668] intraday_11379.csv.gz  in=201,071,228 out=25,589,820 elapsed=59.5s

  [2519/17668] intraday_11381.csv.gz  in=201,083,502 out=25,602,094 elapsed=59.5s

  [2520/17668] intraday_11380.csv.gz  in=201,095,329 out=25,613,921 elapsed=59.6s

  [2521/17668] intraday_11383.csv.gz  in=201,105,198 out=25,623,790 elapsed=59.6s

  [2522/17668] intraday_11382.csv.gz  in=201,115,871 out=25,634,463 elapsed=59.6s

  [2523/17668] intraday_11384.csv.gz  in=201,128,016 out=25,646,608 elapsed=59.6s

  [2524/17668] intraday_11386.csv.gz  in=201,141,248 out=25,659,840 elapsed=59.6s

  [2525/17668] intraday_11385.csv.gz  in=201,156,212 out=25,674,804 elapsed=59.6s

  [2526/17668] intraday_11387.csv.gz  in=201,165,905 out=25,684,497 elapsed=59.6s

  [2527/17668] intraday_11388.csv.gz  in=201,176,107 out=25,694,699 elapsed=59.6s

  [2528/17668] intraday_11389.csv.gz  in=201,188,750 out=25,707,342 elapsed=59.6s

  [2529/17668] intraday_1139.csv.gz  in=201,200,951 out=25,707,342 elapsed=59.6s

  [2530/17668] intraday_11390.csv.gz  in=201,212,389 out=25,718,780 elapsed=59.7s

  [2531/17668] intraday_11391.csv.gz  in=201,223,291 out=25,729,682 elapsed=59.7s

  [2532/17668] intraday_11392.csv.gz  in=201,234,799 out=25,741,190 elapsed=59.7s

  [2533/17668] intraday_11395.csv.gz  in=201,246,503 out=25,752,894 elapsed=59.8s

  [2534/17668] intraday_11393.csv.gz  in=201,260,066 out=25,766,457 elapsed=59.8s

  [2535/17668] intraday_11396.csv.gz  in=201,270,741 out=25,777,132 elapsed=59.8s

  [2536/17668] intraday_11394.csv.gz  in=201,280,543 out=25,786,934 elapsed=59.8s

  [2537/17668] intraday_11397.csv.gz  in=201,293,275 out=25,799,666 elapsed=59.8s

  [2538/17668] intraday_1140.csv.gz  in=201,306,432 out=25,799,666 elapsed=59.8s

  [2539/17668] intraday_11398.csv.gz  in=201,317,138 out=25,810,372 elapsed=59.8s

  [2540/17668] intraday_11399.csv.gz  in=201,330,368 out=25,823,602 elapsed=59.8s

  [2541/17668] intraday_11400.csv.gz  in=201,342,686 out=25,835,920 elapsed=59.8s

  [2542/17668] intraday_11401.csv.gz  in=201,353,878 out=25,847,112 elapsed=59.8s

  [2543/17668] intraday_11404.csv.gz  in=201,362,846 out=25,856,080 elapsed=59.9s

  [2544/17668] intraday_11402.csv.gz  in=201,373,580 out=25,866,814 elapsed=59.9s

  [2545/17668] intraday_11403.csv.gz  in=201,385,438 out=25,878,672 elapsed=59.9s

  [2546/17668] intraday_11405.csv.gz  in=201,397,905 out=25,890,936 elapsed=59.9s

  [2547/17668] intraday_11407.csv.gz  in=201,408,276 out=25,901,307 elapsed=59.9s

  [2548/17668] intraday_11406.csv.gz  in=201,418,692 out=25,911,723 elapsed=59.9s

  [2549/17668] intraday_11408.csv.gz  in=201,431,341 out=25,924,372 elapsed=59.9s

  [2550/17668] intraday_11409.csv.gz  in=201,442,201 out=25,935,232 elapsed=59.9s

  [2551/17668] intraday_1141.csv.gz  in=201,452,998 out=25,935,232 elapsed=59.9s

  [2552/17668] intraday_11410.csv.gz  in=201,466,771 out=25,949,005 elapsed=59.9s

  [2553/17668] intraday_11411.csv.gz  in=201,479,295 out=25,961,529 elapsed=60.0s

  [2554/17668] intraday_11413.csv.gz  in=201,489,672 out=25,971,906 elapsed=60.0s

  [2555/17668] intraday_11412.csv.gz  in=201,502,593 out=25,984,827 elapsed=60.0s

  [2556/17668] intraday_11414.csv.gz  in=201,514,733 out=25,996,967 elapsed=60.0s

  [2557/17668] intraday_11415.csv.gz  in=201,525,578 out=26,007,812 elapsed=60.0s

  [2558/17668] intraday_11416.csv.gz  in=201,536,559 out=26,018,793 elapsed=60.0s

  [2559/17668] intraday_11417.csv.gz  in=201,548,569 out=26,030,803 elapsed=60.0s

  [2560/17668] intraday_11419.csv.gz  in=201,558,134 out=26,040,368 elapsed=60.1s

  [2561/17668] intraday_11418.csv.gz  in=201,569,016 out=26,051,250 elapsed=60.1s

  [2562/17668] intraday_1142.csv.gz  in=201,580,681 out=26,051,250 elapsed=60.1s

  [2563/17668] intraday_11420.csv.gz  in=201,593,507 out=26,064,076 elapsed=60.1s

  [2564/17668] intraday_11422.csv.gz  in=201,605,747 out=26,076,316 elapsed=60.1s

  [2565/17668] intraday_11423.csv.gz  in=201,618,959 out=26,089,528 elapsed=60.1s

  [2566/17668] intraday_11424.csv.gz  in=201,631,713 out=26,102,282 elapsed=60.1s

  [2567/17668] intraday_11421.csv.gz  in=201,646,136 out=26,116,705 elapsed=60.1s

  [2568/17668] intraday_11425.csv.gz  in=201,659,730 out=26,128,332 elapsed=60.1s

  [2569/17668] intraday_11426.csv.gz  in=201,671,472 out=26,140,074 elapsed=60.1s

  [2570/17668] intraday_11427.csv.gz  in=201,683,362 out=26,151,964 elapsed=60.2s

  [2571/17668] intraday_11428.csv.gz  in=201,696,555 out=26,165,157 elapsed=60.2s

  [2572/17668] intraday_11429.csv.gz  in=201,709,733 out=26,178,335 elapsed=60.2s

  [2573/17668] intraday_1143.csv.gz  in=201,725,093 out=26,178,335 elapsed=60.2s

  [2574/17668] intraday_11430.csv.gz  in=201,737,241 out=26,190,483 elapsed=60.2s

  [2575/17668] intraday_11431.csv.gz  in=201,748,117 out=26,201,359 elapsed=60.2s

  [2576/17668] intraday_11432.csv.gz  in=201,758,790 out=26,212,032 elapsed=60.2s

  [2577/17668] intraday_11433.csv.gz  in=201,772,399 out=26,225,641 elapsed=60.2s

  [2578/17668] intraday_11434.csv.gz  in=201,783,029 out=26,236,271 elapsed=60.2s

  [2579/17668] intraday_11435.csv.gz  in=201,793,928 out=26,247,170 elapsed=60.3s

  [2580/17668] intraday_11436.csv.gz  in=201,802,710 out=26,255,952 elapsed=60.3s

  [2581/17668] intraday_11437.csv.gz  in=201,812,048 out=26,265,290 elapsed=60.3s

  [2582/17668] intraday_11438.csv.gz  in=201,822,597 out=26,275,839 elapsed=60.3s

  [2583/17668] intraday_1144.csv.gz  in=201,835,809 out=26,275,839 elapsed=60.3s

  [2584/17668] intraday_11439.csv.gz  in=201,848,735 out=26,288,765 elapsed=60.3s

  [2585/17668] intraday_11441.csv.gz  in=201,860,731 out=26,300,761 elapsed=60.3s

  [2586/17668] intraday_11440.csv.gz  in=201,881,661 out=26,320,112 elapsed=60.4s

  [2587/17668] intraday_11442.csv.gz  in=201,892,430 out=26,330,881 elapsed=60.4s

  [2588/17668] intraday_11443.csv.gz  in=201,903,262 out=26,341,713 elapsed=60.4s

  [2589/17668] intraday_11444.csv.gz  in=201,916,965 out=26,355,416 elapsed=60.4s

  [2590/17668] intraday_11445.csv.gz  in=201,927,552 out=26,366,003 elapsed=60.4s

  [2591/17668] intraday_11446.csv.gz  in=201,942,379 out=26,380,830 elapsed=60.4s

  [2592/17668] intraday_11447.csv.gz  in=201,951,744 out=26,390,195 elapsed=60.4s

  [2593/17668] intraday_11448.csv.gz  in=201,965,193 out=26,403,644 elapsed=60.4s

  [2594/17668] intraday_11449.csv.gz  in=201,977,310 out=26,415,761 elapsed=60.4s

  [2595/17668] intraday_1145.csv.gz  in=201,988,099 out=26,415,761 elapsed=60.4s

  [2596/17668] intraday_11450.csv.gz  in=202,001,120 out=26,428,782 elapsed=60.5s

  [2597/17668] intraday_11451.csv.gz  in=202,014,733 out=26,442,395 elapsed=60.5s

  [2598/17668] intraday_11452.csv.gz  in=202,025,829 out=26,453,491 elapsed=60.5s

  [2599/17668] intraday_11453.csv.gz  in=202,041,826 out=26,467,840 elapsed=60.5s

  [2600/17668] intraday_11454.csv.gz  in=202,053,094 out=26,479,108 elapsed=60.5s

  [2601/17668] intraday_11455.csv.gz  in=202,063,933 out=26,489,947 elapsed=60.5s

  [2602/17668] intraday_11456.csv.gz  in=202,075,645 out=26,501,659 elapsed=60.5s

  [2603/17668] intraday_11458.csv.gz  in=202,087,156 out=26,513,170 elapsed=60.5s

  [2604/17668] intraday_11457.csv.gz  in=202,097,510 out=26,523,524 elapsed=60.6s

  [2605/17668] intraday_1146.csv.gz  in=202,111,712 out=26,523,524 elapsed=60.6s

  [2606/17668] intraday_11459.csv.gz  in=202,124,813 out=26,536,625 elapsed=60.6s

  [2607/17668] intraday_11460.csv.gz  in=202,136,661 out=26,548,473 elapsed=60.6s

  [2608/17668] intraday_11462.csv.gz  in=202,149,086 out=26,560,898 elapsed=60.6s

  [2609/17668] intraday_11463.csv.gz  in=202,161,761 out=26,573,573 elapsed=60.6s

  [2610/17668] intraday_11461.csv.gz  in=202,172,996 out=26,584,808 elapsed=60.6s

  [2611/17668] intraday_11464.csv.gz  in=202,184,814 out=26,596,626 elapsed=60.6s

  [2612/17668] intraday_11465.csv.gz  in=202,197,551 out=26,609,363 elapsed=60.7s

  [2613/17668] intraday_11466.csv.gz  in=202,210,098 out=26,621,910 elapsed=60.7s

  [2614/17668] intraday_11467.csv.gz  in=202,222,801 out=26,634,613 elapsed=60.7s

  [2615/17668] intraday_11468.csv.gz  in=202,232,160 out=26,643,972 elapsed=60.7s

  [2616/17668] intraday_11469.csv.gz  in=202,245,997 out=26,657,809 elapsed=60.7s

  [2617/17668] intraday_1147.csv.gz  in=202,257,708 out=26,657,809 elapsed=60.7s

  [2618/17668] intraday_11470.csv.gz  in=202,274,764 out=26,674,865 elapsed=60.7s

  [2619/17668] intraday_11472.csv.gz  in=202,288,952 out=26,689,053 elapsed=60.8s

  [2620/17668] intraday_11471.csv.gz  in=202,302,572 out=26,702,673 elapsed=60.8s

  [2621/17668] intraday_11473.csv.gz  in=202,317,686 out=26,717,787 elapsed=60.8s

  [2622/17668] intraday_11474.csv.gz  in=202,331,748 out=26,731,849 elapsed=60.8s

  [2623/17668] intraday_11476.csv.gz  in=202,344,908 out=26,745,009 elapsed=60.8s

  [2624/17668] intraday_11477.csv.gz  in=202,356,492 out=26,756,593 elapsed=60.8s

  [2625/17668] intraday_11475.csv.gz  in=202,371,554 out=26,771,655 elapsed=60.8s

  [2626/17668] intraday_11478.csv.gz  in=202,384,497 out=26,784,598 elapsed=60.8s

  [2627/17668] intraday_11479.csv.gz  in=202,396,068 out=26,796,169 elapsed=60.9s

  [2628/17668] intraday_11480.csv.gz  in=202,407,225 out=26,807,326 elapsed=60.9s

  [2629/17668] intraday_1148.csv.gz  in=202,418,493 out=26,807,326 elapsed=60.9s

  [2630/17668] intraday_11481.csv.gz  in=202,430,518 out=26,819,351 elapsed=60.9s

  [2631/17668] intraday_11482.csv.gz  in=202,443,347 out=26,832,180 elapsed=60.9s

  [2632/17668] intraday_11483.csv.gz  in=202,459,176 out=26,848,009 elapsed=60.9s

  [2633/17668] intraday_11485.csv.gz  in=202,470,432 out=26,859,265 elapsed=60.9s

  [2634/17668] intraday_11486.csv.gz  in=202,480,692 out=26,869,525 elapsed=60.9s

  [2635/17668] intraday_11484.csv.gz  in=202,493,501 out=26,882,334 elapsed=60.9s

  [2636/17668] intraday_11487.csv.gz  in=202,506,357 out=26,895,190 elapsed=61.0s

  [2637/17668] intraday_11488.csv.gz  in=202,517,229 out=26,906,062 elapsed=61.0s

  [2638/17668] intraday_1149.csv.gz  in=202,531,412 out=26,906,062 elapsed=61.0s

  [2639/17668] intraday_11489.csv.gz  in=202,543,232 out=26,917,882 elapsed=61.0s

  [2640/17668] intraday_11491.csv.gz  in=202,556,255 out=26,930,905 elapsed=61.0s

  [2641/17668] intraday_11490.csv.gz  in=202,571,507 out=26,946,157 elapsed=61.0s

  [2642/17668] intraday_11492.csv.gz  in=202,584,939 out=26,959,589 elapsed=61.0s

  [2643/17668] intraday_11493.csv.gz  in=202,599,698 out=26,974,348 elapsed=61.0s

  [2644/17668] intraday_11494.csv.gz  in=202,611,039 out=26,985,689 elapsed=61.0s

  [2645/17668] intraday_11498.csv.gz  in=202,618,454 out=26,993,104 elapsed=61.1s

  [2646/17668] intraday_11497.csv.gz  in=202,631,409 out=27,006,059 elapsed=61.1s

  [2647/17668] intraday_11495.csv.gz  in=202,644,476 out=27,019,126 elapsed=61.1s

  [2648/17668] intraday_11496.csv.gz  in=202,654,747 out=27,029,397 elapsed=61.1s

  [2649/17668] intraday_11499.csv.gz  in=202,661,856 out=27,036,506 elapsed=61.1s

  [2650/17668] intraday_11501.csv.gz  in=202,664,890 out=27,039,540 elapsed=61.1s

  [2651/17668] intraday_1150.csv.gz  in=202,676,521 out=27,039,540 elapsed=61.1s

  [2652/17668] intraday_11502.csv.gz  in=202,683,370 out=27,043,336 elapsed=61.1s

  [2653/17668] intraday_11500.csv.gz  in=202,695,424 out=27,055,390 elapsed=61.1s

  [2654/17668] intraday_11503.csv.gz  in=202,708,396 out=27,068,362 elapsed=61.1s

  [2655/17668] intraday_11504.csv.gz  in=202,720,379 out=27,080,345 elapsed=61.2s

  [2656/17668] intraday_11505.csv.gz  in=202,733,039 out=27,093,005 elapsed=61.2s

  [2657/17668] intraday_11506.csv.gz  in=202,741,950 out=27,101,916 elapsed=61.2s

  [2658/17668] intraday_11507.csv.gz  in=202,752,993 out=27,112,959 elapsed=61.2s

  [2659/17668] intraday_11508.csv.gz  in=202,765,271 out=27,125,237 elapsed=61.2s

  [2660/17668] intraday_11509.csv.gz  in=202,779,245 out=27,139,211 elapsed=61.2s

  [2661/17668] intraday_1151.csv.gz  in=202,792,273 out=27,139,211 elapsed=61.2s

  [2662/17668] intraday_11510.csv.gz  in=202,803,403 out=27,150,341 elapsed=61.2s

  [2663/17668] intraday_11511.csv.gz  in=202,814,077 out=27,161,015 elapsed=61.2s

  [2664/17668] intraday_11512.csv.gz  in=202,826,622 out=27,173,560 elapsed=61.3s

  [2665/17668] intraday_11513.csv.gz  in=202,837,688 out=27,184,626 elapsed=61.3s

  [2666/17668] intraday_11514.csv.gz  in=202,849,136 out=27,196,074 elapsed=61.3s

  [2667/17668] intraday_11515.csv.gz  in=202,860,917 out=27,207,855 elapsed=61.3s

  [2668/17668] intraday_11516.csv.gz  in=202,872,222 out=27,219,160 elapsed=61.3s

  [2669/17668] intraday_11518.csv.gz  in=202,881,965 out=27,228,903 elapsed=61.3s

  [2670/17668] intraday_11517.csv.gz  in=202,890,920 out=27,237,858 elapsed=61.3s

  [2671/17668] intraday_11519.csv.gz  in=202,902,934 out=27,249,872 elapsed=61.3s

  [2672/17668] intraday_11520.csv.gz  in=202,914,546 out=27,261,484 elapsed=61.4s

  [2673/17668] intraday_1152.csv.gz  in=202,941,233 out=27,261,484 elapsed=61.4s

  [2674/17668] intraday_11521.csv.gz  in=202,952,580 out=27,272,831 elapsed=61.4s

  [2675/17668] intraday_11522.csv.gz  in=202,962,377 out=27,282,628 elapsed=61.4s

  [2676/17668] intraday_11524.csv.gz  in=202,972,933 out=27,293,184 elapsed=61.4s

  [2677/17668] intraday_11523.csv.gz  in=202,984,245 out=27,304,496 elapsed=61.4s

  [2678/17668] intraday_11526.csv.gz  in=202,994,750 out=27,315,001 elapsed=61.4s

  [2679/17668] intraday_11525.csv.gz  in=203,006,609 out=27,326,860 elapsed=61.4s

  [2680/17668] intraday_11527.csv.gz  in=203,018,828 out=27,339,079 elapsed=61.4s

  [2681/17668] intraday_11528.csv.gz  in=203,029,584 out=27,349,835 elapsed=61.5s

  [2682/17668] intraday_11529.csv.gz  in=203,041,518 out=27,361,769 elapsed=61.5s

  [2683/17668] intraday_1153.csv.gz  in=203,054,126 out=27,361,769 elapsed=61.5s

  [2684/17668] intraday_11531.csv.gz  in=203,063,410 out=27,371,053 elapsed=61.5s

  [2685/17668] intraday_11530.csv.gz  in=203,074,600 out=27,382,243 elapsed=61.5s

  [2686/17668] intraday_11533.csv.gz  in=203,088,615 out=27,396,258 elapsed=61.5s

  [2687/17668] intraday_11535.csv.gz  in=203,088,812 out=27,396,455 elapsed=61.5s

  [2688/17668] intraday_11532.csv.gz  in=203,100,813 out=27,408,456 elapsed=61.5s

  [2689/17668] intraday_11536.csv.gz  in=203,101,206 out=27,408,849 elapsed=61.5s

  [2690/17668] intraday_11534.csv.gz  in=203,112,739 out=27,420,382 elapsed=61.5s

  [2691/17668] intraday_11537.csv.gz  in=203,112,810 out=27,420,453 elapsed=61.5s

  [2692/17668] intraday_11538.csv.gz  in=203,112,845 out=27,420,488 elapsed=61.6s

  [2693/17668] intraday_11539.csv.gz  in=203,113,119 out=27,420,624 elapsed=61.6s

  [2694/17668] intraday_11540.csv.gz  in=203,113,124 out=27,420,629 elapsed=61.6s

  [2695/17668] intraday_11541.csv.gz  in=203,113,152 out=27,420,657 elapsed=61.6s

  [2696/17668] intraday_1154.csv.gz  in=203,123,700 out=27,420,657 elapsed=61.6s

  [2697/17668] intraday_11542.csv.gz  in=203,123,775 out=27,420,732 elapsed=61.6s

  [2698/17668] intraday_11543.csv.gz  in=203,131,501 out=27,428,458 elapsed=61.6s

  [2699/17668] intraday_11545.csv.gz  in=203,143,060 out=27,440,017 elapsed=61.6s

  [2700/17668] intraday_11544.csv.gz  in=203,153,552 out=27,450,509 elapsed=61.6s

  [2701/17668] intraday_11547.csv.gz  in=203,163,665 out=27,460,622 elapsed=61.6s

  [2702/17668] intraday_11548.csv.gz  in=203,175,366 out=27,472,323 elapsed=61.7s

  [2703/17668] intraday_11546.csv.gz  in=203,210,936 out=27,495,834 elapsed=61.7s

  [2704/17668] intraday_11549.csv.gz  in=203,219,942 out=27,504,840 elapsed=61.7s

  [2705/17668] intraday_1155.csv.gz  in=203,233,284 out=27,504,840 elapsed=61.7s

  [2706/17668] intraday_11550.csv.gz  in=203,243,439 out=27,514,995 elapsed=61.7s

  [2707/17668] intraday_11552.csv.gz  in=203,254,051 out=27,525,607 elapsed=61.7s

  [2708/17668] intraday_11551.csv.gz  in=203,264,721 out=27,536,277 elapsed=61.7s

  [2709/17668] intraday_11553.csv.gz  in=203,277,146 out=27,548,702 elapsed=61.7s

  [2710/17668] intraday_11554.csv.gz  in=203,287,750 out=27,559,306 elapsed=61.8s

  [2711/17668] intraday_11555.csv.gz  in=203,298,843 out=27,570,399 elapsed=61.8s

  [2712/17668] intraday_11556.csv.gz  in=203,312,067 out=27,583,623 elapsed=61.8s

  [2713/17668] intraday_11557.csv.gz  in=203,321,619 out=27,593,175 elapsed=61.8s

  [2714/17668] intraday_11558.csv.gz  in=203,332,069 out=27,603,625 elapsed=61.8s

  [2715/17668] intraday_11559.csv.gz  in=203,343,553 out=27,615,109 elapsed=61.8s

  [2716/17668] intraday_1156.csv.gz  in=203,355,506 out=27,615,109 elapsed=61.8s

  [2717/17668] intraday_11560.csv.gz  in=203,365,654 out=27,625,257 elapsed=61.8s

  [2718/17668] intraday_11561.csv.gz  in=203,388,600 out=27,644,081 elapsed=61.9s

  [2719/17668] intraday_11563.csv.gz  in=203,397,326 out=27,652,807 elapsed=61.9s

  [2720/17668] intraday_11562.csv.gz  in=203,407,833 out=27,663,314 elapsed=61.9s

  [2721/17668] intraday_11564.csv.gz  in=203,419,383 out=27,674,864 elapsed=61.9s

  [2722/17668] intraday_11565.csv.gz  in=203,430,592 out=27,686,048 elapsed=61.9s

  [2723/17668] intraday_11566.csv.gz  in=203,441,222 out=27,696,678 elapsed=61.9s

  [2724/17668] intraday_11567.csv.gz  in=203,452,839 out=27,708,295 elapsed=61.9s

  [2725/17668] intraday_11568.csv.gz  in=203,464,580 out=27,720,036 elapsed=61.9s

  [2726/17668] intraday_11569.csv.gz  in=203,475,074 out=27,730,530 elapsed=61.9s

  [2727/17668] intraday_1157.csv.gz  in=203,487,488 out=27,730,530 elapsed=61.9s

  [2728/17668] intraday_11570.csv.gz  in=203,498,980 out=27,742,022 elapsed=61.9s

  [2729/17668] intraday_11573.csv.gz  in=203,511,162 out=27,754,204 elapsed=62.0s

  [2730/17668] intraday_11571.csv.gz  in=203,523,201 out=27,766,243 elapsed=62.0s

  [2731/17668] intraday_11574.csv.gz  in=203,533,201 out=27,776,243 elapsed=62.0s

  [2732/17668] intraday_11575.csv.gz  in=203,546,482 out=27,789,059 elapsed=62.0s

  [2733/17668] intraday_11572.csv.gz  in=203,556,470 out=27,799,047 elapsed=62.0s

  [2734/17668] intraday_11576.csv.gz  in=203,566,016 out=27,808,593 elapsed=62.0s

  [2735/17668] intraday_11577.csv.gz  in=203,579,564 out=27,822,141 elapsed=62.0s

  [2736/17668] intraday_1158.csv.gz  in=203,596,747 out=27,822,141 elapsed=62.1s

  [2737/17668] intraday_11579.csv.gz  in=203,610,367 out=27,835,761 elapsed=62.1s

  [2738/17668] intraday_11578.csv.gz  in=203,626,417 out=27,849,286 elapsed=62.1s

  [2739/17668] intraday_11580.csv.gz  in=203,639,094 out=27,861,963 elapsed=62.1s

  [2740/17668] intraday_11581.csv.gz  in=203,650,837 out=27,873,706 elapsed=62.1s

  [2741/17668] intraday_11582.csv.gz  in=203,660,737 out=27,883,606 elapsed=62.1s

  [2742/17668] intraday_11583.csv.gz  in=203,672,163 out=27,895,032 elapsed=62.1s

  [2743/17668] intraday_11584.csv.gz  in=203,683,971 out=27,906,840 elapsed=62.2s

  [2744/17668] intraday_11585.csv.gz  in=203,695,347 out=27,918,216 elapsed=62.2s

  [2745/17668] intraday_11586.csv.gz  in=203,707,182 out=27,930,051 elapsed=62.2s

  [2746/17668] intraday_11588.csv.gz  in=203,716,859 out=27,939,728 elapsed=62.2s

  [2747/17668] intraday_11587.csv.gz  in=203,727,518 out=27,950,387 elapsed=62.2s

  [2748/17668] intraday_11589.csv.gz  in=203,740,985 out=27,963,854 elapsed=62.2s

  [2749/17668] intraday_1159.csv.gz  in=203,756,646 out=27,963,854 elapsed=62.2s

  [2750/17668] intraday_11590.csv.gz  in=203,766,005 out=27,973,213 elapsed=62.2s

  [2751/17668] intraday_11591.csv.gz  in=203,777,016 out=27,984,224 elapsed=62.3s

  [2752/17668] intraday_11593.csv.gz  in=203,784,662 out=27,991,870 elapsed=62.3s

  [2753/17668] intraday_11594.csv.gz  in=203,795,915 out=28,003,123 elapsed=62.3s

  [2754/17668] intraday_11592.csv.gz  in=203,805,593 out=28,012,801 elapsed=62.3s

  [2755/17668] intraday_11595.csv.gz  in=203,816,659 out=28,023,867 elapsed=62.3s

  [2756/17668] intraday_11597.csv.gz  in=203,829,560 out=28,036,768 elapsed=62.3s

  [2757/17668] intraday_11596.csv.gz  in=203,844,927 out=28,052,135 elapsed=62.3s

  [2758/17668] intraday_11598.csv.gz  in=203,857,132 out=28,064,340 elapsed=62.3s

  [2759/17668] intraday_1160.csv.gz  in=203,866,668 out=28,064,340 elapsed=62.3s

  [2760/17668] intraday_11599.csv.gz  in=203,875,988 out=28,073,660 elapsed=62.4s

  [2761/17668] intraday_11600.csv.gz  in=203,889,570 out=28,087,242 elapsed=62.4s

  [2762/17668] intraday_11603.csv.gz  in=203,900,040 out=28,097,712 elapsed=62.4s

  [2763/17668] intraday_11602.csv.gz  in=203,912,890 out=28,110,562 elapsed=62.4s

  [2764/17668] intraday_11604.csv.gz  in=203,924,721 out=28,122,393 elapsed=62.4s

  [2765/17668] intraday_11601.csv.gz  in=203,934,798 out=28,132,470 elapsed=62.4s

  [2766/17668] intraday_11606.csv.gz  in=203,947,488 out=28,145,160 elapsed=62.4s

  [2767/17668] intraday_11605.csv.gz  in=203,958,453 out=28,156,125 elapsed=62.5s

  [2768/17668] intraday_11607.csv.gz  in=203,970,387 out=28,168,059 elapsed=62.5s

  [2769/17668] intraday_11608.csv.gz  in=203,982,327 out=28,179,999 elapsed=62.5s

  [2770/17668] intraday_1161.csv.gz  in=203,994,451 out=28,179,999 elapsed=62.5s

  [2771/17668] intraday_11609.csv.gz  in=204,007,668 out=28,193,216 elapsed=62.5s

  [2772/17668] intraday_11610.csv.gz  in=204,019,120 out=28,204,668 elapsed=62.5s

  [2773/17668] intraday_11611.csv.gz  in=204,028,816 out=28,214,364 elapsed=62.5s

  [2774/17668] intraday_11612.csv.gz  in=204,040,014 out=28,225,562 elapsed=62.5s

  [2775/17668] intraday_11613.csv.gz  in=204,049,673 out=28,235,221 elapsed=62.6s

  [2776/17668] intraday_11614.csv.gz  in=204,060,714 out=28,246,262 elapsed=62.6s

  [2777/17668] intraday_11615.csv.gz  in=204,074,412 out=28,259,960 elapsed=62.6s

  [2778/17668] intraday_11617.csv.gz  in=204,085,286 out=28,270,834 elapsed=62.6s

  [2779/17668] intraday_11616.csv.gz  in=204,097,073 out=28,282,621 elapsed=62.6s

  [2780/17668] intraday_11618.csv.gz  in=204,109,538 out=28,295,086 elapsed=62.6s

  [2781/17668] intraday_11619.csv.gz  in=204,123,189 out=28,308,737 elapsed=62.6s

  [2782/17668] intraday_1162.csv.gz  in=204,136,618 out=28,308,737 elapsed=62.6s

  [2783/17668] intraday_11620.csv.gz  in=204,147,190 out=28,319,309 elapsed=62.6s

  [2784/17668] intraday_11621.csv.gz  in=204,158,237 out=28,330,356 elapsed=62.6s

  [2785/17668] intraday_11622.csv.gz  in=204,170,614 out=28,342,733 elapsed=62.7s

  [2786/17668] intraday_11623.csv.gz  in=204,184,387 out=28,356,506 elapsed=62.7s

  [2787/17668] intraday_11624.csv.gz  in=204,193,968 out=28,366,087 elapsed=62.7s

  [2788/17668] intraday_11625.csv.gz  in=204,206,896 out=28,379,015 elapsed=62.7s

  [2789/17668] intraday_11628.csv.gz  in=204,219,531 out=28,391,650 elapsed=62.7s

  [2790/17668] intraday_11627.csv.gz  in=204,231,905 out=28,404,024 elapsed=62.7s

  [2791/17668] intraday_11626.csv.gz  in=204,246,760 out=28,418,879 elapsed=62.7s

  [2792/17668] intraday_1163.csv.gz  in=204,260,896 out=28,418,879 elapsed=62.8s

  [2793/17668] intraday_11629.csv.gz  in=204,274,917 out=28,432,900 elapsed=62.8s

  [2794/17668] intraday_11630.csv.gz  in=204,291,245 out=28,449,228 elapsed=62.8s

  [2795/17668] intraday_11631.csv.gz  in=204,305,593 out=28,463,576 elapsed=62.8s

  [2796/17668] intraday_11632.csv.gz  in=204,318,472 out=28,476,455 elapsed=62.8s

  [2797/17668] intraday_11633.csv.gz  in=204,329,270 out=28,487,253 elapsed=62.8s

  [2798/17668] intraday_11634.csv.gz  in=204,340,943 out=28,498,926 elapsed=62.8s

  [2799/17668] intraday_11635.csv.gz  in=204,352,498 out=28,510,481 elapsed=62.8s

  [2800/17668] intraday_11636.csv.gz  in=204,364,861 out=28,522,844 elapsed=62.9s

  [2801/17668] intraday_11637.csv.gz  in=204,375,226 out=28,532,552 elapsed=62.9s

  [2802/17668] intraday_11638.csv.gz  in=204,387,307 out=28,544,633 elapsed=62.9s

  [2803/17668] intraday_11639.csv.gz  in=204,399,705 out=28,557,031 elapsed=62.9s

  [2804/17668] intraday_1164.csv.gz  in=204,410,313 out=28,557,031 elapsed=62.9s

  [2805/17668] intraday_11640.csv.gz  in=204,425,058 out=28,571,776 elapsed=62.9s

  [2806/17668] intraday_11641.csv.gz  in=204,437,926 out=28,584,220 elapsed=62.9s

  [2807/17668] intraday_11643.csv.gz  in=204,448,815 out=28,595,109 elapsed=62.9s

  [2808/17668] intraday_11642.csv.gz  in=204,459,170 out=28,605,464 elapsed=62.9s

  [2809/17668] intraday_11644.csv.gz  in=204,470,225 out=28,616,519 elapsed=62.9s

  [2810/17668] intraday_11645.csv.gz  in=204,481,199 out=28,627,493 elapsed=63.0s

  [2811/17668] intraday_11646.csv.gz  in=204,494,750 out=28,641,044 elapsed=63.0s

  [2812/17668] intraday_11647.csv.gz  in=204,508,923 out=28,655,217 elapsed=63.0s

  [2813/17668] intraday_11648.csv.gz  in=204,521,157 out=28,667,451 elapsed=63.0s

  [2814/17668] intraday_11649.csv.gz  in=204,536,918 out=28,683,212 elapsed=63.0s

  [2815/17668] intraday_1165.csv.gz  in=204,551,221 out=28,683,212 elapsed=63.0s

  [2816/17668] intraday_11651.csv.gz  in=204,564,163 out=28,695,837 elapsed=63.0s

  [2817/17668] intraday_11653.csv.gz  in=204,574,241 out=28,705,915 elapsed=63.1s

  [2818/17668] intraday_11650.csv.gz  in=204,585,648 out=28,717,322 elapsed=63.1s

  [2819/17668] intraday_11654.csv.gz  in=204,596,432 out=28,727,756 elapsed=63.1s

  [2820/17668] intraday_11652.csv.gz  in=204,613,404 out=28,742,211 elapsed=63.1s

  [2821/17668] intraday_11655.csv.gz  in=204,622,271 out=28,750,092 elapsed=63.1s

  [2822/17668] intraday_11656.csv.gz  in=204,630,445 out=28,758,266 elapsed=63.1s

  [2823/17668] intraday_11658.csv.gz  in=204,630,574 out=28,758,395 elapsed=63.1s

  [2824/17668] intraday_11657.csv.gz  in=204,641,044 out=28,768,865 elapsed=63.1s

  [2825/17668] intraday_11659.csv.gz  in=204,654,038 out=28,781,859 elapsed=63.2s

  [2826/17668] intraday_1166.csv.gz  in=204,665,087 out=28,781,859 elapsed=63.2s

  [2827/17668] intraday_11661.csv.gz  in=204,678,469 out=28,795,241 elapsed=63.2s

  [2828/17668] intraday_11660.csv.gz  in=204,690,382 out=28,807,154 elapsed=63.2s

  [2829/17668] intraday_11663.csv.gz  in=204,700,847 out=28,817,619 elapsed=63.2s

  [2830/17668] intraday_11662.csv.gz  in=204,710,578 out=28,827,350 elapsed=63.2s

  [2831/17668] intraday_11664.csv.gz  in=204,723,544 out=28,840,316 elapsed=63.3s

  [2832/17668] intraday_11665.csv.gz  in=204,737,965 out=28,854,737 elapsed=63.3s

  [2833/17668] intraday_11666.csv.gz  in=204,748,893 out=28,865,665 elapsed=63.3s

  [2834/17668] intraday_11667.csv.gz  in=204,760,234 out=28,877,006 elapsed=63.3s

  [2835/17668] intraday_11668.csv.gz  in=204,772,482 out=28,889,254 elapsed=63.3s

  [2836/17668] intraday_11669.csv.gz  in=204,784,557 out=28,901,329 elapsed=63.3s

  [2837/17668] intraday_1167.csv.gz  in=204,796,897 out=28,901,329 elapsed=63.3s

  [2838/17668] intraday_11670.csv.gz  in=204,807,471 out=28,911,903 elapsed=63.3s

  [2839/17668] intraday_11672.csv.gz  in=204,819,448 out=28,923,880 elapsed=63.3s

  [2840/17668] intraday_11673.csv.gz  in=204,829,397 out=28,933,829 elapsed=63.3s

  [2841/17668] intraday_11674.csv.gz  in=204,838,576 out=28,943,008 elapsed=63.4s

  [2842/17668] intraday_11671.csv.gz  in=204,850,760 out=28,955,192 elapsed=63.4s

  [2843/17668] intraday_11676.csv.gz  in=204,864,279 out=28,968,711 elapsed=63.4s

  [2844/17668] intraday_11675.csv.gz  in=204,876,144 out=28,980,576 elapsed=63.4s

  [2845/17668] intraday_11677.csv.gz  in=204,887,774 out=28,992,206 elapsed=63.4s

  [2846/17668] intraday_11678.csv.gz  in=204,898,109 out=29,002,541 elapsed=63.4s

  [2847/17668] intraday_11679.csv.gz  in=204,908,803 out=29,013,235 elapsed=63.4s

  [2848/17668] intraday_1168.csv.gz  in=204,920,660 out=29,013,235 elapsed=63.4s

  [2849/17668] intraday_11680.csv.gz  in=204,932,563 out=29,025,138 elapsed=63.5s

  [2850/17668] intraday_11681.csv.gz  in=204,945,165 out=29,037,740 elapsed=63.5s

  [2851/17668] intraday_11683.csv.gz  in=204,957,432 out=29,050,007 elapsed=63.5s

  [2852/17668] intraday_11682.csv.gz  in=204,969,048 out=29,061,623 elapsed=63.5s

  [2853/17668] intraday_11684.csv.gz  in=204,979,975 out=29,072,550 elapsed=63.5s

  [2854/17668] intraday_11686.csv.gz  in=204,990,364 out=29,082,939 elapsed=63.5s

  [2855/17668] intraday_11685.csv.gz  in=205,002,566 out=29,095,141 elapsed=63.5s

  [2856/17668] intraday_11687.csv.gz  in=205,012,401 out=29,104,976 elapsed=63.5s

  [2857/17668] intraday_11689.csv.gz  in=205,025,861 out=29,118,436 elapsed=63.6s

  [2858/17668] intraday_11688.csv.gz  in=205,038,345 out=29,130,920 elapsed=63.6s

  [2859/17668] intraday_1169.csv.gz  in=205,052,164 out=29,130,920 elapsed=63.6s

  [2860/17668] intraday_11691.csv.gz  in=205,061,897 out=29,140,653 elapsed=63.6s

  [2861/17668] intraday_11690.csv.gz  in=205,074,611 out=29,153,367 elapsed=63.6s

  [2862/17668] intraday_11692.csv.gz  in=205,084,855 out=29,163,611 elapsed=63.6s

  [2863/17668] intraday_11693.csv.gz  in=205,096,725 out=29,175,481 elapsed=63.6s

  [2864/17668] intraday_11694.csv.gz  in=205,110,338 out=29,189,094 elapsed=63.6s

  [2865/17668] intraday_11695.csv.gz  in=205,120,916 out=29,199,672 elapsed=63.6s

  [2866/17668] intraday_11696.csv.gz  in=205,132,267 out=29,211,023 elapsed=63.7s

  [2867/17668] intraday_11697.csv.gz  in=205,142,059 out=29,220,815 elapsed=63.7s

  [2868/17668] intraday_11698.csv.gz  in=205,152,951 out=29,231,707 elapsed=63.7s

  [2869/17668] intraday_11699.csv.gz  in=205,163,186 out=29,241,942 elapsed=63.7s

  [2870/17668] intraday_1170.csv.gz  in=205,173,622 out=29,241,942 elapsed=63.7s

  [2871/17668] intraday_11700.csv.gz  in=205,184,912 out=29,253,232 elapsed=63.7s

  [2872/17668] intraday_11701.csv.gz  in=205,197,823 out=29,266,143 elapsed=63.7s

  [2873/17668] intraday_11703.csv.gz  in=205,209,544 out=29,277,864 elapsed=63.7s

  [2874/17668] intraday_11702.csv.gz  in=205,220,867 out=29,289,187 elapsed=63.7s

  [2875/17668] intraday_11704.csv.gz  in=205,233,598 out=29,301,918 elapsed=63.7s

  [2876/17668] intraday_11705.csv.gz  in=205,243,408 out=29,311,728 elapsed=63.7s

  [2877/17668] intraday_11706.csv.gz  in=205,255,228 out=29,323,548 elapsed=63.8s

  [2878/17668] intraday_11708.csv.gz  in=205,265,786 out=29,334,106 elapsed=63.8s

  [2879/17668] intraday_11709.csv.gz  in=205,277,219 out=29,345,539 elapsed=63.8s

  [2880/17668] intraday_11707.csv.gz  in=205,287,963 out=29,356,283 elapsed=63.8s

  [2881/17668] intraday_1171.csv.gz  in=205,298,689 out=29,356,283 elapsed=63.8s

  [2882/17668] intraday_11710.csv.gz  in=205,308,631 out=29,366,225 elapsed=63.8s

  [2883/17668] intraday_11712.csv.gz  in=205,320,759 out=29,378,353 elapsed=63.9s

  [2884/17668] intraday_11713.csv.gz  in=205,332,889 out=29,390,483 elapsed=63.9s

  [2885/17668] intraday_11714.csv.gz  in=205,343,402 out=29,400,996 elapsed=63.9s

  [2886/17668] intraday_11711.csv.gz  in=205,353,212 out=29,410,806 elapsed=63.9s

  [2887/17668] intraday_11715.csv.gz  in=205,365,162 out=29,422,756 elapsed=63.9s

  [2888/17668] intraday_11716.csv.gz  in=205,376,735 out=29,434,329 elapsed=63.9s

  [2889/17668] intraday_11717.csv.gz  in=205,387,339 out=29,444,933 elapsed=63.9s

  [2890/17668] intraday_11718.csv.gz  in=205,399,276 out=29,456,870 elapsed=63.9s

  [2891/17668] intraday_11719.csv.gz  in=205,411,298 out=29,468,892 elapsed=63.9s

  [2892/17668] intraday_1172.csv.gz  in=205,425,560 out=29,468,892 elapsed=64.0s

  [2893/17668] intraday_11720.csv.gz  in=205,437,078 out=29,480,410 elapsed=64.0s

  [2894/17668] intraday_11721.csv.gz  in=205,448,763 out=29,492,095 elapsed=64.0s

  [2895/17668] intraday_11723.csv.gz  in=205,459,506 out=29,502,838 elapsed=64.0s

  [2896/17668] intraday_11722.csv.gz  in=205,470,074 out=29,513,406 elapsed=64.0s

  [2897/17668] intraday_11724.csv.gz  in=205,480,382 out=29,523,714 elapsed=64.0s

  [2898/17668] intraday_11725.csv.gz  in=205,494,375 out=29,537,707 elapsed=64.0s

  [2899/17668] intraday_11726.csv.gz  in=205,506,276 out=29,549,608 elapsed=64.0s

  [2900/17668] intraday_11727.csv.gz  in=205,520,303 out=29,563,635 elapsed=64.0s

  [2901/17668] intraday_11728.csv.gz  in=205,532,378 out=29,575,710 elapsed=64.0s

  [2902/17668] intraday_11729.csv.gz  in=205,543,053 out=29,586,385 elapsed=64.1s

  [2903/17668] intraday_1173.csv.gz  in=205,557,891 out=29,586,385 elapsed=64.1s

  [2904/17668] intraday_11730.csv.gz  in=205,568,170 out=29,596,664 elapsed=64.1s

  [2905/17668] intraday_11731.csv.gz  in=205,579,775 out=29,608,269 elapsed=64.1s

  [2906/17668] intraday_11732.csv.gz  in=205,592,919 out=29,621,413 elapsed=64.1s

  [2907/17668] intraday_11734.csv.gz  in=205,604,417 out=29,632,911 elapsed=64.1s

  [2908/17668] intraday_11733.csv.gz  in=205,617,475 out=29,645,969 elapsed=64.1s

  [2909/17668] intraday_11736.csv.gz  in=205,627,450 out=29,655,944 elapsed=64.2s

  [2910/17668] intraday_11735.csv.gz  in=205,638,744 out=29,667,238 elapsed=64.2s

  [2911/17668] intraday_11737.csv.gz  in=205,652,717 out=29,681,211 elapsed=64.2s

  [2912/17668] intraday_11738.csv.gz  in=205,662,980 out=29,691,474 elapsed=64.2s

  [2913/17668] intraday_11739.csv.gz  in=205,673,508 out=29,702,002 elapsed=64.2s

  [2914/17668] intraday_1174.csv.gz  in=205,686,180 out=29,702,002 elapsed=64.2s

  [2915/17668] intraday_11740.csv.gz  in=205,696,158 out=29,711,980 elapsed=64.2s

  [2916/17668] intraday_11741.csv.gz  in=205,704,603 out=29,720,425 elapsed=64.2s

  [2917/17668] intraday_11742.csv.gz  in=205,715,704 out=29,731,526 elapsed=64.2s

  [2918/17668] intraday_11743.csv.gz  in=205,727,626 out=29,743,448 elapsed=64.3s

  [2919/17668] intraday_11744.csv.gz  in=205,744,890 out=29,760,712 elapsed=64.3s

  [2920/17668] intraday_11745.csv.gz  in=205,756,917 out=29,772,739 elapsed=64.3s

  [2921/17668] intraday_11746.csv.gz  in=205,769,035 out=29,784,857 elapsed=64.3s

  [2922/17668] intraday_11747.csv.gz  in=205,779,145 out=29,794,967 elapsed=64.3s

  [2923/17668] intraday_11748.csv.gz  in=205,792,939 out=29,808,761 elapsed=64.3s

  [2924/17668] intraday_11749.csv.gz  in=205,802,467 out=29,818,289 elapsed=64.3s

  [2925/17668] intraday_11750.csv.gz  in=205,815,402 out=29,831,224 elapsed=64.4s

  [2926/17668] intraday_1175.csv.gz  in=205,827,491 out=29,831,224 elapsed=64.4s

  [2927/17668] intraday_11751.csv.gz  in=205,838,769 out=29,842,502 elapsed=64.4s

  [2928/17668] intraday_11752.csv.gz  in=205,849,258 out=29,852,991 elapsed=64.4s

  [2929/17668] intraday_11753.csv.gz  in=205,861,050 out=29,864,783 elapsed=64.4s

  [2930/17668] intraday_11754.csv.gz  in=205,874,601 out=29,878,334 elapsed=64.4s

  [2931/17668] intraday_11755.csv.gz  in=205,887,365 out=29,891,098 elapsed=64.4s

  [2932/17668] intraday_11756.csv.gz  in=205,899,036 out=29,902,769 elapsed=64.4s

  [2933/17668] intraday_11757.csv.gz  in=205,911,122 out=29,914,855 elapsed=64.4s

  [2934/17668] intraday_11759.csv.gz  in=205,921,570 out=29,925,303 elapsed=64.5s

  [2935/17668] intraday_11758.csv.gz  in=205,932,951 out=29,936,684 elapsed=64.5s

  [2936/17668] intraday_1176.csv.gz  in=205,945,989 out=29,936,684 elapsed=64.5s

  [2937/17668] intraday_11760.csv.gz  in=205,957,596 out=29,948,291 elapsed=64.5s

  [2938/17668] intraday_11761.csv.gz  in=205,967,110 out=29,957,805 elapsed=64.5s

  [2939/17668] intraday_11763.csv.gz  in=205,980,007 out=29,970,702 elapsed=64.5s

  [2940/17668] intraday_11762.csv.gz  in=205,991,792 out=29,982,487 elapsed=64.5s

  [2941/17668] intraday_11765.csv.gz  in=206,003,008 out=29,993,703 elapsed=64.6s

  [2942/17668] intraday_11764.csv.gz  in=206,015,270 out=30,005,965 elapsed=64.6s

  [2943/17668] intraday_11766.csv.gz  in=206,025,292 out=30,015,987 elapsed=64.6s

  [2944/17668] intraday_11767.csv.gz  in=206,039,376 out=30,030,071 elapsed=64.6s

  [2945/17668] intraday_11768.csv.gz  in=206,049,521 out=30,040,216 elapsed=64.6s

  [2946/17668] intraday_11769.csv.gz  in=206,061,387 out=30,052,082 elapsed=64.6s

  [2947/17668] intraday_1177.csv.gz  in=206,073,460 out=30,052,082 elapsed=64.6s

  [2948/17668] intraday_11770.csv.gz  in=206,086,209 out=30,064,831 elapsed=64.6s

  [2949/17668] intraday_11771.csv.gz  in=206,099,719 out=30,078,341 elapsed=64.7s

  [2950/17668] intraday_11773.csv.gz  in=206,112,956 out=30,091,578 elapsed=64.7s

  [2951/17668] intraday_11772.csv.gz  in=206,123,426 out=30,102,048 elapsed=64.7s

  [2952/17668] intraday_11775.csv.gz  in=206,135,226 out=30,113,848 elapsed=64.7s

  [2953/17668] intraday_11774.csv.gz  in=206,150,840 out=30,129,462 elapsed=64.7s

  [2954/17668] intraday_11777.csv.gz  in=206,164,176 out=30,142,798 elapsed=64.7s

  [2955/17668] intraday_11776.csv.gz  in=206,178,339 out=30,156,961 elapsed=64.7s

  [2956/17668] intraday_11778.csv.gz  in=206,194,442 out=30,173,064 elapsed=64.7s

  [2957/17668] intraday_11779.csv.gz  in=206,208,112 out=30,186,734 elapsed=64.7s

  [2958/17668] intraday_1178.csv.gz  in=206,221,670 out=30,186,734 elapsed=64.7s

  [2959/17668] intraday_11780.csv.gz  in=206,236,141 out=30,201,205 elapsed=64.8s

  [2960/17668] intraday_11781.csv.gz  in=206,246,871 out=30,211,935 elapsed=64.8s

  [2961/17668] intraday_11782.csv.gz  in=206,259,920 out=30,224,984 elapsed=64.8s

  [2962/17668] intraday_11783.csv.gz  in=206,271,232 out=30,236,296 elapsed=64.8s

  [2963/17668] intraday_11784.csv.gz  in=206,283,195 out=30,248,259 elapsed=64.8s

  [2964/17668] intraday_11785.csv.gz  in=206,293,919 out=30,258,983 elapsed=64.8s

  [2965/17668] intraday_11786.csv.gz  in=206,304,757 out=30,269,821 elapsed=64.9s

  [2966/17668] intraday_11787.csv.gz  in=206,317,895 out=30,282,959 elapsed=64.9s

  [2967/17668] intraday_11788.csv.gz  in=206,331,616 out=30,296,680 elapsed=64.9s

  [2968/17668] intraday_1179.csv.gz  in=206,347,435 out=30,296,680 elapsed=64.9s

  [2969/17668] intraday_11789.csv.gz  in=206,357,908 out=30,307,153 elapsed=64.9s

  [2970/17668] intraday_11790.csv.gz  in=206,368,692 out=30,317,937 elapsed=64.9s

  [2971/17668] intraday_11791.csv.gz  in=206,380,249 out=30,329,494 elapsed=64.9s

  [2972/17668] intraday_11793.csv.gz  in=206,390,324 out=30,339,569 elapsed=64.9s

  [2973/17668] intraday_11792.csv.gz  in=206,402,094 out=30,351,339 elapsed=64.9s

  [2974/17668] intraday_11794.csv.gz  in=206,416,535 out=30,365,780 elapsed=65.0s

  [2975/17668] intraday_11795.csv.gz  in=206,431,598 out=30,380,843 elapsed=65.0s

  [2976/17668] intraday_11796.csv.gz  in=206,444,067 out=30,393,312 elapsed=65.0s

  [2977/17668] intraday_11797.csv.gz  in=206,459,750 out=30,408,995 elapsed=65.0s

  [2978/17668] intraday_11799.csv.gz  in=206,471,706 out=30,420,951 elapsed=65.0s

  [2979/17668] intraday_11798.csv.gz  in=206,482,718 out=30,431,963 elapsed=65.0s

  [2980/17668] intraday_1180.csv.gz  in=206,502,336 out=30,431,963 elapsed=65.0s

  [2981/17668] intraday_11800.csv.gz  in=206,515,151 out=30,444,778 elapsed=65.1s

  [2982/17668] intraday_11801.csv.gz  in=206,524,725 out=30,454,352 elapsed=65.1s

  [2983/17668] intraday_11802.csv.gz  in=206,536,355 out=30,465,982 elapsed=65.1s

  [2984/17668] intraday_11803.csv.gz  in=206,542,426 out=30,472,053 elapsed=65.1s

  [2985/17668] intraday_11804.csv.gz  in=206,552,067 out=30,481,694 elapsed=65.1s

  [2986/17668] intraday_11805.csv.gz  in=206,561,059 out=30,490,686 elapsed=65.1s

  [2987/17668] intraday_11807.csv.gz  in=206,575,053 out=30,504,680 elapsed=65.1s

  [2988/17668] intraday_11806.csv.gz  in=206,598,194 out=30,518,522 elapsed=65.1s

  [2989/17668] intraday_11809.csv.gz  in=206,610,766 out=30,531,094 elapsed=65.2s

  [2990/17668] intraday_1181.csv.gz  in=206,625,306 out=30,531,094 elapsed=65.2s

  [2991/17668] intraday_11808.csv.gz  in=206,638,444 out=30,544,232 elapsed=65.2s

  [2992/17668] intraday_11810.csv.gz  in=206,647,883 out=30,553,671 elapsed=65.2s

  [2993/17668] intraday_11811.csv.gz  in=206,659,431 out=30,565,219 elapsed=65.2s

  [2994/17668] intraday_11813.csv.gz  in=206,673,698 out=30,579,486 elapsed=65.2s

  [2995/17668] intraday_11812.csv.gz  in=206,687,528 out=30,593,316 elapsed=65.2s

  [2996/17668] intraday_11814.csv.gz  in=206,699,256 out=30,605,044 elapsed=65.2s

  [2997/17668] intraday_11815.csv.gz  in=206,711,354 out=30,617,142 elapsed=65.3s

  [2998/17668] intraday_11816.csv.gz  in=206,724,259 out=30,630,047 elapsed=65.3s

  [2999/17668] intraday_11817.csv.gz  in=206,736,833 out=30,642,621 elapsed=65.3s

  [3000/17668] intraday_1182.csv.gz  in=206,751,489 out=30,642,621 elapsed=65.3s

  [3001/17668] intraday_11819.csv.gz  in=206,764,881 out=30,656,013 elapsed=65.3s

  [3002/17668] intraday_11818.csv.gz  in=206,775,682 out=30,666,814 elapsed=65.3s

  [3003/17668] intraday_11820.csv.gz  in=206,788,427 out=30,679,559 elapsed=65.3s

  [3004/17668] intraday_11821.csv.gz  in=206,797,687 out=30,688,819 elapsed=65.3s

  [3005/17668] intraday_11822.csv.gz  in=206,809,059 out=30,700,191 elapsed=65.3s

  [3006/17668] intraday_11823.csv.gz  in=206,822,751 out=30,713,883 elapsed=65.4s

  [3007/17668] intraday_11824.csv.gz  in=206,837,460 out=30,728,592 elapsed=65.4s

  [3008/17668] intraday_11825.csv.gz  in=206,847,754 out=30,738,886 elapsed=65.4s

  [3009/17668] intraday_11826.csv.gz  in=206,858,040 out=30,749,172 elapsed=65.4s

  [3010/17668] intraday_11827.csv.gz  in=206,868,775 out=30,759,907 elapsed=65.4s

  [3011/17668] intraday_11828.csv.gz  in=206,881,265 out=30,772,397 elapsed=65.4s

  [3012/17668] intraday_11829.csv.gz  in=206,893,632 out=30,784,764 elapsed=65.4s

  [3013/17668] intraday_1183.csv.gz  in=206,908,635 out=30,784,764 elapsed=65.4s

  [3014/17668] intraday_11830.csv.gz  in=206,920,472 out=30,796,601 elapsed=65.4s

  [3015/17668] intraday_11831.csv.gz  in=206,933,754 out=30,809,883 elapsed=65.5s

  [3016/17668] intraday_11832.csv.gz  in=206,945,365 out=30,821,494 elapsed=65.5s

  [3017/17668] intraday_11834.csv.gz  in=206,957,312 out=30,833,441 elapsed=65.5s

  [3018/17668] intraday_11833.csv.gz  in=206,969,081 out=30,845,210 elapsed=65.5s

  [3019/17668] intraday_11835.csv.gz  in=206,979,142 out=30,855,271 elapsed=65.5s

  [3020/17668] intraday_11836.csv.gz  in=206,991,893 out=30,868,022 elapsed=65.5s

  [3021/17668] intraday_11837.csv.gz  in=207,005,542 out=30,881,671 elapsed=65.5s

  [3022/17668] intraday_11838.csv.gz  in=207,018,583 out=30,894,712 elapsed=65.5s

  [3023/17668] intraday_11839.csv.gz  in=207,028,889 out=30,905,018 elapsed=65.6s

  [3024/17668] intraday_1184.csv.gz  in=207,042,635 out=30,905,018 elapsed=65.6s

  [3025/17668] intraday_11840.csv.gz  in=207,054,204 out=30,916,587 elapsed=65.6s

  [3026/17668] intraday_11841.csv.gz  in=207,066,678 out=30,929,061 elapsed=65.6s

  [3027/17668] intraday_11843.csv.gz  in=207,078,542 out=30,940,925 elapsed=65.6s

  [3028/17668] intraday_11842.csv.gz  in=207,091,519 out=30,953,902 elapsed=65.6s

  [3029/17668] intraday_11844.csv.gz  in=207,102,301 out=30,964,684 elapsed=65.6s

  [3030/17668] intraday_11845.csv.gz  in=207,113,031 out=30,975,414 elapsed=65.6s

  [3031/17668] intraday_11846.csv.gz  in=207,123,881 out=30,986,264 elapsed=65.7s

  [3032/17668] intraday_11847.csv.gz  in=207,135,460 out=30,997,843 elapsed=65.7s

  [3033/17668] intraday_11848.csv.gz  in=207,148,960 out=31,011,343 elapsed=65.7s

  [3034/17668] intraday_11849.csv.gz  in=207,159,507 out=31,021,890 elapsed=65.7s

  [3035/17668] intraday_1185.csv.gz  in=207,171,770 out=31,021,890 elapsed=65.7s

  [3036/17668] intraday_11850.csv.gz  in=207,184,242 out=31,034,362 elapsed=65.7s

  [3037/17668] intraday_11851.csv.gz  in=207,198,308 out=31,048,428 elapsed=65.7s

  [3038/17668] intraday_11853.csv.gz  in=207,209,892 out=31,060,012 elapsed=65.7s

  [3039/17668] intraday_11852.csv.gz  in=207,221,755 out=31,071,875 elapsed=65.7s

  [3040/17668] intraday_11854.csv.gz  in=207,233,701 out=31,083,821 elapsed=65.7s

  [3041/17668] intraday_11855.csv.gz  in=207,245,760 out=31,095,880 elapsed=65.8s

  [3042/17668] intraday_11856.csv.gz  in=207,256,093 out=31,106,213 elapsed=65.8s

  [3043/17668] intraday_11857.csv.gz  in=207,268,159 out=31,118,279 elapsed=65.8s

  [3044/17668] intraday_11858.csv.gz  in=207,277,351 out=31,127,471 elapsed=65.8s

  [3045/17668] intraday_11859.csv.gz  in=207,288,385 out=31,138,505 elapsed=65.8s

  [3046/17668] intraday_1186.csv.gz  in=207,309,947 out=31,138,505 elapsed=65.8s

  [3047/17668] intraday_11860.csv.gz  in=207,320,425 out=31,148,983 elapsed=65.8s

  [3048/17668] intraday_11861.csv.gz  in=207,333,923 out=31,162,481 elapsed=65.8s

  [3049/17668] intraday_11862.csv.gz  in=207,346,974 out=31,175,532 elapsed=65.9s

  [3050/17668] intraday_11863.csv.gz  in=207,358,559 out=31,187,117 elapsed=65.9s

  [3051/17668] intraday_11864.csv.gz  in=207,370,894 out=31,199,452 elapsed=65.9s

  [3052/17668] intraday_11865.csv.gz  in=207,381,467 out=31,210,025 elapsed=65.9s

  [3053/17668] intraday_11866.csv.gz  in=207,392,820 out=31,221,319 elapsed=65.9s

  [3054/17668] intraday_11867.csv.gz  in=207,405,279 out=31,233,778 elapsed=65.9s

  [3055/17668] intraday_11868.csv.gz  in=207,415,876 out=31,244,375 elapsed=65.9s

  [3056/17668] intraday_11869.csv.gz  in=207,427,144 out=31,255,643 elapsed=65.9s

  [3057/17668] intraday_1187.csv.gz  in=207,441,249 out=31,255,643 elapsed=65.9s

  [3058/17668] intraday_11871.csv.gz  in=207,450,673 out=31,265,067 elapsed=66.0s

  [3059/17668] intraday_11870.csv.gz  in=207,463,234 out=31,277,628 elapsed=66.0s

  [3060/17668] intraday_11872.csv.gz  in=207,477,599 out=31,291,522 elapsed=66.0s

  [3061/17668] intraday_11873.csv.gz  in=207,492,255 out=31,306,178 elapsed=66.0s

  [3062/17668] intraday_11874.csv.gz  in=207,503,684 out=31,317,607 elapsed=66.0s

  [3063/17668] intraday_11876.csv.gz  in=207,514,124 out=31,328,047 elapsed=66.0s

  [3064/17668] intraday_11875.csv.gz  in=207,527,874 out=31,341,797 elapsed=66.0s

  [3065/17668] intraday_11877.csv.gz  in=207,537,462 out=31,351,385 elapsed=66.0s

  [3066/17668] intraday_11878.csv.gz  in=207,551,155 out=31,365,078 elapsed=66.1s

  [3067/17668] intraday_1188.csv.gz  in=207,563,068 out=31,365,078 elapsed=66.1s

  [3068/17668] intraday_11879.csv.gz  in=207,575,896 out=31,377,906 elapsed=66.1s

  [3069/17668] intraday_11880.csv.gz  in=207,587,509 out=31,389,519 elapsed=66.1s

  [3070/17668] intraday_11881.csv.gz  in=207,600,879 out=31,402,889 elapsed=66.1s

  [3071/17668] intraday_11883.csv.gz  in=207,610,398 out=31,412,408 elapsed=66.1s

  [3072/17668] intraday_11882.csv.gz  in=207,623,373 out=31,425,383 elapsed=66.1s

  [3073/17668] intraday_11885.csv.gz  in=207,636,798 out=31,438,808 elapsed=66.2s

  [3074/17668] intraday_11884.csv.gz  in=207,648,513 out=31,450,523 elapsed=66.2s

  [3075/17668] intraday_11886.csv.gz  in=207,658,877 out=31,460,887 elapsed=66.2s

  [3076/17668] intraday_11887.csv.gz  in=207,668,443 out=31,470,453 elapsed=66.2s

  [3077/17668] intraday_11888.csv.gz  in=207,677,133 out=31,479,143 elapsed=66.2s

  [3078/17668] intraday_11889.csv.gz  in=207,688,252 out=31,490,262 elapsed=66.2s

  [3079/17668] intraday_1189.csv.gz  in=207,701,405 out=31,490,262 elapsed=66.2s

  [3080/17668] intraday_11891.csv.gz  in=207,715,475 out=31,504,332 elapsed=66.2s

  [3081/17668] intraday_11890.csv.gz  in=207,728,226 out=31,517,083 elapsed=66.3s

  [3082/17668] intraday_11892.csv.gz  in=207,744,574 out=31,533,431 elapsed=66.3s

  [3083/17668] intraday_11893.csv.gz  in=207,756,695 out=31,545,552 elapsed=66.3s

  [3084/17668] intraday_11894.csv.gz  in=207,768,052 out=31,556,909 elapsed=66.3s

  [3085/17668] intraday_11896.csv.gz  in=207,780,312 out=31,569,169 elapsed=66.3s

  [3086/17668] intraday_11895.csv.gz  in=207,791,719 out=31,580,576 elapsed=66.3s

  [3087/17668] intraday_11897.csv.gz  in=207,805,722 out=31,594,579 elapsed=66.3s

  [3088/17668] intraday_11898.csv.gz  in=207,816,860 out=31,605,717 elapsed=66.3s

  [3089/17668] intraday_11899.csv.gz  in=207,827,878 out=31,616,735 elapsed=66.3s

  [3090/17668] intraday_1190.csv.gz  in=207,840,106 out=31,616,735 elapsed=66.4s

  [3091/17668] intraday_11900.csv.gz  in=207,853,968 out=31,630,597 elapsed=66.4s

  [3092/17668] intraday_11902.csv.gz  in=207,866,486 out=31,643,115 elapsed=66.4s

  [3093/17668] intraday_11903.csv.gz  in=207,878,778 out=31,655,407 elapsed=66.4s

  [3094/17668] intraday_11901.csv.gz  in=207,891,426 out=31,668,055 elapsed=66.4s

  [3095/17668] intraday_11904.csv.gz  in=207,903,186 out=31,679,815 elapsed=66.4s

  [3096/17668] intraday_11905.csv.gz  in=207,915,466 out=31,692,095 elapsed=66.4s

  [3097/17668] intraday_11907.csv.gz  in=207,928,051 out=31,704,680 elapsed=66.4s

  [3098/17668] intraday_11906.csv.gz  in=207,940,044 out=31,716,673 elapsed=66.4s

  [3099/17668] intraday_11908.csv.gz  in=207,951,043 out=31,727,672 elapsed=66.5s

  [3100/17668] intraday_11909.csv.gz  in=207,963,631 out=31,740,260 elapsed=66.5s

  [3101/17668] intraday_11911.csv.gz  in=207,975,446 out=31,752,075 elapsed=66.5s

  [3102/17668] intraday_1191.csv.gz  in=207,987,904 out=31,752,075 elapsed=66.5s

  [3103/17668] intraday_11910.csv.gz  in=208,001,368 out=31,765,539 elapsed=66.5s

  [3104/17668] intraday_11912.csv.gz  in=208,013,051 out=31,777,222 elapsed=66.5s

  [3105/17668] intraday_11914.csv.gz  in=208,027,509 out=31,791,680 elapsed=66.6s

  [3106/17668] intraday_11915.csv.gz  in=208,037,762 out=31,801,933 elapsed=66.6s

  [3107/17668] intraday_11913.csv.gz  in=208,048,985 out=31,813,156 elapsed=66.6s

  [3108/17668] intraday_11916.csv.gz  in=208,060,395 out=31,824,566 elapsed=66.6s

  [3109/17668] intraday_11917.csv.gz  in=208,074,172 out=31,838,343 elapsed=66.6s

  [3110/17668] intraday_11919.csv.gz  in=208,084,330 out=31,848,501 elapsed=66.6s

  [3111/17668] intraday_11918.csv.gz  in=208,097,958 out=31,862,129 elapsed=66.6s

  [3112/17668] intraday_1192.csv.gz  in=208,110,192 out=31,862,129 elapsed=66.6s

  [3113/17668] intraday_11920.csv.gz  in=208,122,993 out=31,874,930 elapsed=66.6s

  [3114/17668] intraday_11921.csv.gz  in=208,137,540 out=31,889,477 elapsed=66.7s

  [3115/17668] intraday_11923.csv.gz  in=208,150,363 out=31,902,300 elapsed=66.7s

  [3116/17668] intraday_11922.csv.gz  in=208,164,722 out=31,916,659 elapsed=66.7s

  [3117/17668] intraday_11924.csv.gz  in=208,179,512 out=31,931,449 elapsed=66.7s

  [3118/17668] intraday_11925.csv.gz  in=208,196,702 out=31,948,639 elapsed=66.7s

  [3119/17668] intraday_11927.csv.gz  in=208,210,617 out=31,962,554 elapsed=66.7s

  [3120/17668] intraday_11926.csv.gz  in=208,224,612 out=31,976,549 elapsed=66.7s

  [3121/17668] intraday_11928.csv.gz  in=208,236,434 out=31,988,371 elapsed=66.7s

  [3122/17668] intraday_11929.csv.gz  in=208,249,067 out=32,001,004 elapsed=66.7s

  [3123/17668] intraday_1193.csv.gz  in=208,261,050 out=32,001,004 elapsed=66.8s

  [3124/17668] intraday_11930.csv.gz  in=208,273,607 out=32,013,561 elapsed=66.8s

  [3125/17668] intraday_11931.csv.gz  in=208,286,106 out=32,026,060 elapsed=66.8s

  [3126/17668] intraday_11932.csv.gz  in=208,297,551 out=32,037,505 elapsed=66.8s

  [3127/17668] intraday_11934.csv.gz  in=208,309,572 out=32,049,526 elapsed=66.8s

  [3128/17668] intraday_11935.csv.gz  in=208,324,704 out=32,064,658 elapsed=66.8s

  [3129/17668] intraday_11933.csv.gz  in=208,337,586 out=32,077,540 elapsed=66.8s

  [3130/17668] intraday_11936.csv.gz  in=208,347,793 out=32,087,747 elapsed=66.8s

  [3131/17668] intraday_11937.csv.gz  in=208,359,064 out=32,099,018 elapsed=66.8s

  [3132/17668] intraday_11938.csv.gz  in=208,370,369 out=32,110,323 elapsed=66.9s

  [3133/17668] intraday_1194.csv.gz  in=208,388,060 out=32,110,323 elapsed=66.9s

  [3134/17668] intraday_11939.csv.gz  in=208,399,840 out=32,122,103 elapsed=66.9s

  [3135/17668] intraday_11940.csv.gz  in=208,410,845 out=32,133,108 elapsed=66.9s

  [3136/17668] intraday_11941.csv.gz  in=208,423,987 out=32,146,250 elapsed=66.9s

  [3137/17668] intraday_11942.csv.gz  in=208,438,901 out=32,161,164 elapsed=66.9s

  [3138/17668] intraday_11943.csv.gz  in=208,452,515 out=32,174,778 elapsed=66.9s

  [3139/17668] intraday_11944.csv.gz  in=208,468,146 out=32,190,409 elapsed=66.9s

  [3140/17668] intraday_11945.csv.gz  in=208,480,499 out=32,202,762 elapsed=66.9s

  [3141/17668] intraday_11946.csv.gz  in=208,492,025 out=32,214,288 elapsed=67.0s

  [3142/17668] intraday_11947.csv.gz  in=208,504,406 out=32,226,669 elapsed=67.0s

  [3143/17668] intraday_11948.csv.gz  in=208,515,163 out=32,237,426 elapsed=67.0s

  [3144/17668] intraday_11949.csv.gz  in=208,527,627 out=32,249,890 elapsed=67.0s

  [3145/17668] intraday_1195.csv.gz  in=208,537,470 out=32,249,890 elapsed=67.0s

  [3146/17668] intraday_11950.csv.gz  in=208,544,007 out=32,256,427 elapsed=67.0s

  [3147/17668] intraday_11952.csv.gz  in=208,555,077 out=32,267,497 elapsed=67.0s

  [3148/17668] intraday_11951.csv.gz  in=208,567,633 out=32,278,066 elapsed=67.0s

  [3149/17668] intraday_11953.csv.gz  in=208,583,248 out=32,293,681 elapsed=67.1s

  [3150/17668] intraday_11954.csv.gz  in=208,596,444 out=32,306,877 elapsed=67.1s

  [3151/17668] intraday_11955.csv.gz  in=208,609,551 out=32,319,646 elapsed=67.1s

  [3152/17668] intraday_11956.csv.gz  in=208,620,649 out=32,330,744 elapsed=67.1s

  [3153/17668] intraday_11957.csv.gz  in=208,632,610 out=32,342,705 elapsed=67.1s

  [3154/17668] intraday_1196.csv.gz  in=208,652,493 out=32,342,705 elapsed=67.1s

  [3155/17668] intraday_11958.csv.gz  in=208,667,157 out=32,357,369 elapsed=67.1s

  [3156/17668] intraday_11960.csv.gz  in=208,678,604 out=32,368,816 elapsed=67.1s

  [3157/17668] intraday_11959.csv.gz  in=208,695,078 out=32,385,290 elapsed=67.1s

  [3158/17668] intraday_11961.csv.gz  in=208,707,088 out=32,397,300 elapsed=67.2s

  [3159/17668] intraday_11962.csv.gz  in=208,720,958 out=32,411,170 elapsed=67.2s

  [3160/17668] intraday_11964.csv.gz  in=208,732,314 out=32,422,526 elapsed=67.2s

  [3161/17668] intraday_11963.csv.gz  in=208,745,424 out=32,435,636 elapsed=67.2s

  [3162/17668] intraday_11965.csv.gz  in=208,758,755 out=32,448,967 elapsed=67.2s

  [3163/17668] intraday_11966.csv.gz  in=208,771,297 out=32,461,509 elapsed=67.2s

  [3164/17668] intraday_11967.csv.gz  in=208,781,178 out=32,471,390 elapsed=67.2s

  [3165/17668] intraday_11968.csv.gz  in=208,792,487 out=32,482,699 elapsed=67.2s

  [3166/17668] intraday_11969.csv.gz  in=208,806,413 out=32,496,625 elapsed=67.3s

  [3167/17668] intraday_11970.csv.gz  in=208,819,646 out=32,509,858 elapsed=67.3s

  [3168/17668] intraday_1197.csv.gz  in=208,834,834 out=32,509,858 elapsed=67.3s

  [3169/17668] intraday_11971.csv.gz  in=208,847,263 out=32,522,287 elapsed=67.3s

  [3170/17668] intraday_11972.csv.gz  in=208,858,586 out=32,533,610 elapsed=67.3s

  [3171/17668] intraday_11973.csv.gz  in=208,869,301 out=32,544,325 elapsed=67.3s

  [3172/17668] intraday_11974.csv.gz  in=208,881,412 out=32,556,436 elapsed=67.3s

  [3173/17668] intraday_11975.csv.gz  in=208,894,418 out=32,569,442 elapsed=67.3s

  [3174/17668] intraday_11977.csv.gz  in=208,906,766 out=32,581,790 elapsed=67.4s

  [3175/17668] intraday_11976.csv.gz  in=208,919,831 out=32,594,855 elapsed=67.4s

  [3176/17668] intraday_11978.csv.gz  in=208,931,890 out=32,606,914 elapsed=67.4s

  [3177/17668] intraday_11979.csv.gz  in=208,943,685 out=32,618,709 elapsed=67.4s

  [3178/17668] intraday_1198.csv.gz  in=208,959,137 out=32,618,709 elapsed=67.4s

  [3179/17668] intraday_11981.csv.gz  in=208,970,594 out=32,630,166 elapsed=67.4s

  [3180/17668] intraday_11980.csv.gz  in=208,989,631 out=32,645,798 elapsed=67.4s

  [3181/17668] intraday_11983.csv.gz  in=209,004,029 out=32,660,196 elapsed=67.4s

  [3182/17668] intraday_11982.csv.gz  in=209,017,017 out=32,673,184 elapsed=67.5s

  [3183/17668] intraday_11984.csv.gz  in=209,030,441 out=32,686,608 elapsed=67.5s

  [3184/17668] intraday_11985.csv.gz  in=209,040,726 out=32,696,893 elapsed=67.5s

  [3185/17668] intraday_11987.csv.gz  in=209,054,036 out=32,710,203 elapsed=67.5s

  [3186/17668] intraday_11988.csv.gz  in=209,067,606 out=32,723,773 elapsed=67.5s

  [3187/17668] intraday_11989.csv.gz  in=209,079,959 out=32,736,126 elapsed=67.5s

  [3188/17668] intraday_1199.csv.gz  in=209,093,671 out=32,736,126 elapsed=67.5s

  [3189/17668] intraday_11986.csv.gz  in=209,106,154 out=32,748,609 elapsed=67.5s

  [3190/17668] intraday_11990.csv.gz  in=209,117,266 out=32,759,721 elapsed=67.6s

  [3191/17668] intraday_11992.csv.gz  in=209,129,565 out=32,771,108 elapsed=67.6s

  [3192/17668] intraday_11991.csv.gz  in=209,140,951 out=32,782,494 elapsed=67.6s

  [3193/17668] intraday_11993.csv.gz  in=209,152,242 out=32,793,785 elapsed=67.6s

  [3194/17668] intraday_11994.csv.gz  in=209,164,519 out=32,806,062 elapsed=67.6s

  [3195/17668] intraday_11996.csv.gz  in=209,176,569 out=32,818,112 elapsed=67.6s

  [3196/17668] intraday_11998.csv.gz  in=209,188,832 out=32,830,375 elapsed=67.6s

  [3197/17668] intraday_11995.csv.gz  in=209,202,359 out=32,843,902 elapsed=67.7s

  [3198/17668] intraday_11997.csv.gz  in=209,218,945 out=32,858,295 elapsed=67.7s

  [3199/17668] intraday_11999.csv.gz  in=209,230,846 out=32,870,196 elapsed=67.7s

  [3200/17668] intraday_12000.csv.gz  in=209,243,333 out=32,882,683 elapsed=67.7s

  [3201/17668] intraday_12001.csv.gz  in=209,255,914 out=32,895,264 elapsed=67.7s

  [3202/17668] intraday_12002.csv.gz  in=209,266,087 out=32,905,437 elapsed=67.7s

  [3203/17668] intraday_1200.csv.gz  in=209,289,343 out=32,905,437 elapsed=67.7s

  [3204/17668] intraday_12003.csv.gz  in=209,301,994 out=32,918,088 elapsed=67.7s

  [3205/17668] intraday_12004.csv.gz  in=209,312,779 out=32,928,873 elapsed=67.7s

  [3206/17668] intraday_12006.csv.gz  in=209,325,608 out=32,941,702 elapsed=67.8s

  [3207/17668] intraday_12005.csv.gz  in=209,336,323 out=32,952,417 elapsed=67.8s

  [3208/17668] intraday_12007.csv.gz  in=209,349,876 out=32,965,970 elapsed=67.8s

  [3209/17668] intraday_12008.csv.gz  in=209,362,220 out=32,978,314 elapsed=67.8s

  [3210/17668] intraday_12009.csv.gz  in=209,375,062 out=32,991,156 elapsed=67.8s

  [3211/17668] intraday_1201.csv.gz  in=209,388,192 out=32,991,156 elapsed=67.8s

  [3212/17668] intraday_12010.csv.gz  in=209,401,071 out=33,004,035 elapsed=67.8s

  [3213/17668] intraday_12011.csv.gz  in=209,411,445 out=33,014,409 elapsed=67.9s

  [3214/17668] intraday_12012.csv.gz  in=209,423,480 out=33,026,444 elapsed=67.9s

  [3215/17668] intraday_12014.csv.gz  in=209,434,886 out=33,037,850 elapsed=67.9s

  [3216/17668] intraday_12013.csv.gz  in=209,447,465 out=33,050,429 elapsed=67.9s

  [3217/17668] intraday_12015.csv.gz  in=209,459,444 out=33,062,408 elapsed=67.9s

  [3218/17668] intraday_12016.csv.gz  in=209,471,344 out=33,074,308 elapsed=67.9s

  [3219/17668] intraday_12017.csv.gz  in=209,481,183 out=33,084,147 elapsed=67.9s

  [3220/17668] intraday_12018.csv.gz  in=209,492,432 out=33,095,396 elapsed=67.9s

  [3221/17668] intraday_12019.csv.gz  in=209,514,694 out=33,114,323 elapsed=68.0s

  [3222/17668] intraday_1202.csv.gz  in=209,528,204 out=33,114,323 elapsed=68.0s

  [3223/17668] intraday_12020.csv.gz  in=209,541,855 out=33,127,974 elapsed=68.0s

  [3224/17668] intraday_12022.csv.gz  in=209,554,300 out=33,140,419 elapsed=68.0s

  [3225/17668] intraday_12021.csv.gz  in=209,568,497 out=33,154,616 elapsed=68.0s

  [3226/17668] intraday_12023.csv.gz  in=209,578,818 out=33,164,937 elapsed=68.0s

  [3227/17668] intraday_12024.csv.gz  in=209,590,705 out=33,176,824 elapsed=68.0s

  [3228/17668] intraday_12025.csv.gz  in=209,603,563 out=33,189,682 elapsed=68.0s

  [3229/17668] intraday_12027.csv.gz  in=209,617,699 out=33,203,818 elapsed=68.0s

  [3230/17668] intraday_12026.csv.gz  in=209,630,256 out=33,216,375 elapsed=68.1s

  [3231/17668] intraday_12028.csv.gz  in=209,642,574 out=33,228,693 elapsed=68.1s

  [3232/17668] intraday_12029.csv.gz  in=209,653,430 out=33,239,549 elapsed=68.1s

  [3233/17668] intraday_1203.csv.gz  in=209,666,902 out=33,239,549 elapsed=68.1s

  [3234/17668] intraday_12030.csv.gz  in=209,677,742 out=33,250,389 elapsed=68.1s

  [3235/17668] intraday_12032.csv.gz  in=209,689,813 out=33,262,460 elapsed=68.1s

  [3236/17668] intraday_12031.csv.gz  in=209,703,522 out=33,276,169 elapsed=68.1s

  [3237/17668] intraday_12034.csv.gz  in=209,714,084 out=33,286,731 elapsed=68.1s

  [3238/17668] intraday_12033.csv.gz  in=209,725,901 out=33,298,548 elapsed=68.1s

  [3239/17668] intraday_12035.csv.gz  in=209,735,497 out=33,308,144 elapsed=68.2s

  [3240/17668] intraday_12036.csv.gz  in=209,747,534 out=33,320,181 elapsed=68.2s

  [3241/17668] intraday_12037.csv.gz  in=209,763,158 out=33,335,805 elapsed=68.2s

  [3242/17668] intraday_12038.csv.gz  in=209,781,813 out=33,354,460 elapsed=68.2s

  [3243/17668] intraday_12040.csv.gz  in=209,793,606 out=33,366,253 elapsed=68.3s

  [3244/17668] intraday_1204.csv.gz  in=209,804,701 out=33,366,253 elapsed=68.3s

  [3245/17668] intraday_12039.csv.gz  in=209,817,883 out=33,379,435 elapsed=68.3s

  [3246/17668] intraday_12041.csv.gz  in=209,828,326 out=33,389,878 elapsed=68.3s

  [3247/17668] intraday_12042.csv.gz  in=209,842,147 out=33,403,699 elapsed=68.3s

  [3248/17668] intraday_12043.csv.gz  in=209,853,187 out=33,414,739 elapsed=68.3s

  [3249/17668] intraday_12045.csv.gz  in=209,863,498 out=33,425,050 elapsed=68.3s

  [3250/17668] intraday_12044.csv.gz  in=209,878,945 out=33,440,497 elapsed=68.3s

  [3251/17668] intraday_12046.csv.gz  in=209,890,853 out=33,452,405 elapsed=68.3s

  [3252/17668] intraday_12047.csv.gz  in=209,905,151 out=33,466,703 elapsed=68.4s

  [3253/17668] intraday_12048.csv.gz  in=209,919,100 out=33,480,652 elapsed=68.4s

  [3254/17668] intraday_1205.csv.gz  in=209,933,184 out=33,480,652 elapsed=68.4s

  [3255/17668] intraday_12049.csv.gz  in=209,945,820 out=33,493,288 elapsed=68.4s

  [3256/17668] intraday_12050.csv.gz  in=209,958,429 out=33,505,897 elapsed=68.4s

  [3257/17668] intraday_12053.csv.gz  in=209,969,422 out=33,516,890 elapsed=68.4s

  [3258/17668] intraday_12051.csv.gz  in=209,982,498 out=33,529,966 elapsed=68.4s

  [3259/17668] intraday_12052.csv.gz  in=209,993,477 out=33,540,945 elapsed=68.4s

  [3260/17668] intraday_12055.csv.gz  in=210,005,494 out=33,552,962 elapsed=68.5s

  [3261/17668] intraday_12056.csv.gz  in=210,017,733 out=33,565,201 elapsed=68.5s

  [3262/17668] intraday_12054.csv.gz  in=210,031,110 out=33,578,578 elapsed=68.5s

  [3263/17668] intraday_12057.csv.gz  in=210,044,646 out=33,592,114 elapsed=68.5s

  [3264/17668] intraday_12058.csv.gz  in=210,057,080 out=33,604,548 elapsed=68.5s

  [3265/17668] intraday_12059.csv.gz  in=210,068,904 out=33,616,372 elapsed=68.5s

  [3266/17668] intraday_1206.csv.gz  in=210,086,572 out=33,616,372 elapsed=68.5s

  [3267/17668] intraday_12060.csv.gz  in=210,099,628 out=33,629,428 elapsed=68.5s

  [3268/17668] intraday_12061.csv.gz  in=210,113,322 out=33,643,122 elapsed=68.6s

  [3269/17668] intraday_12064.csv.gz  in=210,126,745 out=33,656,545 elapsed=68.6s

  [3270/17668] intraday_12063.csv.gz  in=210,139,072 out=33,668,872 elapsed=68.6s

  [3271/17668] intraday_12065.csv.gz  in=210,152,876 out=33,682,676 elapsed=68.6s

  [3272/17668] intraday_12062.csv.gz  in=210,165,103 out=33,694,903 elapsed=68.6s

  [3273/17668] intraday_12066.csv.gz  in=210,175,978 out=33,705,778 elapsed=68.6s

  [3274/17668] intraday_12067.csv.gz  in=210,190,249 out=33,720,049 elapsed=68.6s

  [3275/17668] intraday_12069.csv.gz  in=210,203,795 out=33,733,595 elapsed=68.7s

  [3276/17668] intraday_1207.csv.gz  in=210,216,274 out=33,733,595 elapsed=68.7s

  [3277/17668] intraday_12068.csv.gz  in=210,234,461 out=33,751,782 elapsed=68.7s

  [3278/17668] intraday_12070.csv.gz  in=210,249,563 out=33,766,884 elapsed=68.7s

  [3279/17668] intraday_12072.csv.gz  in=210,264,450 out=33,781,771 elapsed=68.7s

  [3280/17668] intraday_12071.csv.gz  in=210,281,376 out=33,798,697 elapsed=68.7s

  [3281/17668] intraday_12073.csv.gz  in=210,296,936 out=33,814,257 elapsed=68.7s

  [3282/17668] intraday_12074.csv.gz  in=210,312,419 out=33,829,480 elapsed=68.8s

  [3283/17668] intraday_12075.csv.gz  in=210,324,773 out=33,841,834 elapsed=68.8s

  [3284/17668] intraday_12076.csv.gz  in=210,337,851 out=33,854,912 elapsed=68.8s

  [3285/17668] intraday_12077.csv.gz  in=210,349,982 out=33,867,043 elapsed=68.8s

  [3286/17668] intraday_12078.csv.gz  in=210,362,049 out=33,879,110 elapsed=68.8s

  [3287/17668] intraday_12079.csv.gz  in=210,373,950 out=33,891,011 elapsed=68.8s

  [3288/17668] intraday_1208.csv.gz  in=210,398,877 out=33,891,011 elapsed=68.8s

  [3289/17668] intraday_12080.csv.gz  in=210,411,414 out=33,903,548 elapsed=68.8s

  [3290/17668] intraday_12081.csv.gz  in=210,424,427 out=33,916,561 elapsed=68.9s

  [3291/17668] intraday_12082.csv.gz  in=210,439,637 out=33,931,771 elapsed=68.9s

  [3292/17668] intraday_12083.csv.gz  in=210,451,538 out=33,943,672 elapsed=68.9s

  [3293/17668] intraday_12084.csv.gz  in=210,462,154 out=33,954,288 elapsed=68.9s

  [3294/17668] intraday_12085.csv.gz  in=210,475,225 out=33,967,359 elapsed=68.9s

  [3295/17668] intraday_12086.csv.gz  in=210,485,895 out=33,978,029 elapsed=68.9s

  [3296/17668] intraday_12087.csv.gz  in=210,498,683 out=33,990,817 elapsed=68.9s

  [3297/17668] intraday_12089.csv.gz  in=210,514,318 out=34,006,452 elapsed=68.9s

  [3298/17668] intraday_12088.csv.gz  in=210,528,611 out=34,020,745 elapsed=68.9s

  [3299/17668] intraday_12090.csv.gz  in=210,542,719 out=34,034,853 elapsed=68.9s

  [3300/17668] intraday_1209.csv.gz  in=210,560,042 out=34,034,853 elapsed=69.0s

  [3301/17668] intraday_12091.csv.gz  in=210,574,378 out=34,049,189 elapsed=69.0s

  [3302/17668] intraday_12092.csv.gz  in=210,586,463 out=34,061,274 elapsed=69.0s

  [3303/17668] intraday_12093.csv.gz  in=210,599,329 out=34,074,140 elapsed=69.0s

  [3304/17668] intraday_12094.csv.gz  in=210,611,162 out=34,085,973 elapsed=69.0s

  [3305/17668] intraday_12095.csv.gz  in=210,626,795 out=34,101,606 elapsed=69.0s

  [3306/17668] intraday_12096.csv.gz  in=210,635,748 out=34,110,559 elapsed=69.1s

  [3307/17668] intraday_12097.csv.gz  in=210,642,871 out=34,117,682 elapsed=69.1s

  [3308/17668] intraday_12098.csv.gz  in=210,654,864 out=34,129,675 elapsed=69.1s

  [3309/17668] intraday_12099.csv.gz  in=210,660,731 out=34,135,542 elapsed=69.1s

  [3310/17668] intraday_1210.csv.gz  in=210,693,168 out=34,135,542 elapsed=69.1s

  [3311/17668] intraday_12103.csv.gz  in=210,933,153 out=34,156,258 elapsed=69.4s

  [3312/17668] intraday_12101.csv.gz  in=211,192,348 out=34,178,749 elapsed=69.4s

  [3313/17668] intraday_12102.csv.gz  in=211,492,811 out=34,205,090 elapsed=69.4s

  [3314/17668] intraday_12100.csv.gz  in=211,820,512 out=34,238,384 elapsed=69.4s

  [3315/17668] intraday_12107.csv.gz  in=212,090,093 out=34,262,591 elapsed=69.6s

  [3316/17668] intraday_12104.csv.gz  in=212,411,090 out=34,287,386 elapsed=69.6s

  [3317/17668] intraday_12105.csv.gz  in=212,725,299 out=34,315,832 elapsed=69.7s

  [3318/17668] intraday_12106.csv.gz  in=213,052,933 out=34,346,702 elapsed=69.7s

  [3319/17668] intraday_1211.csv.gz  in=213,064,749 out=34,346,702 elapsed=69.7s

  [3320/17668] intraday_12108.csv.gz  in=213,365,675 out=34,371,668 elapsed=69.8s

  [3321/17668] intraday_12109.csv.gz  in=213,663,648 out=34,396,358 elapsed=69.9s

  [3322/17668] intraday_12111.csv.gz  in=213,940,481 out=34,420,519 elapsed=69.9s

  [3323/17668] intraday_12110.csv.gz  in=214,254,888 out=34,445,007 elapsed=69.9s

  [3324/17668] intraday_12112.csv.gz  in=214,518,587 out=34,472,557 elapsed=70.1s

  [3325/17668] intraday_12113.csv.gz  in=214,805,837 out=34,499,004 elapsed=70.1s

  [3326/17668] intraday_12115.csv.gz  in=215,036,527 out=34,522,055 elapsed=70.1s

  [3327/17668] intraday_12114.csv.gz  in=215,251,420 out=34,541,969 elapsed=70.2s

  [3328/17668] intraday_12116.csv.gz  in=215,572,984 out=34,571,263 elapsed=70.3s

  [3329/17668] intraday_1212.csv.gz  in=215,588,821 out=34,571,263 elapsed=70.4s

  [3330/17668] intraday_12119.csv.gz  in=215,813,757 out=34,591,690 elapsed=70.4s

  [3331/17668] intraday_12118.csv.gz  in=216,066,121 out=34,613,229 elapsed=70.4s

  [3332/17668] intraday_12117.csv.gz  in=216,363,515 out=34,638,488 elapsed=70.4s

  [3333/17668] intraday_12120.csv.gz  in=216,642,107 out=34,661,318 elapsed=70.6s

  [3334/17668] intraday_12121.csv.gz  in=216,908,945 out=34,685,543 elapsed=70.6s

  [3335/17668] intraday_12122.csv.gz  in=217,160,061 out=34,711,656 elapsed=70.7s

  [3336/17668] intraday_12123.csv.gz  in=217,441,091 out=34,749,844 elapsed=70.7s

  [3337/17668] intraday_12124.csv.gz  in=217,720,659 out=34,775,781 elapsed=70.8s

  [3338/17668] intraday_12125.csv.gz  in=217,970,495 out=34,799,002 elapsed=70.8s

  [3339/17668] intraday_12126.csv.gz  in=218,194,535 out=34,820,677 elapsed=70.9s

  [3340/17668] intraday_12127.csv.gz  in=218,459,762 out=34,844,635 elapsed=70.9s

  [3341/17668] intraday_1213.csv.gz  in=218,481,451 out=34,844,635 elapsed=70.9s

  [3342/17668] intraday_12128.csv.gz  in=218,733,193 out=34,867,502 elapsed=71.0s

  [3343/17668] intraday_12129.csv.gz  in=219,025,493 out=34,893,496 elapsed=71.1s

  [3344/17668] intraday_12131.csv.gz  in=219,297,836 out=34,918,521 elapsed=71.2s

  [3345/17668] intraday_12130.csv.gz  in=219,683,536 out=34,948,768 elapsed=71.2s

  [3346/17668] intraday_12132.csv.gz  in=219,916,195 out=34,969,024 elapsed=71.2s

  [3347/17668] intraday_12133.csv.gz  in=220,214,766 out=34,995,770 elapsed=71.3s

  [3348/17668] intraday_12134.csv.gz  in=220,507,376 out=35,021,952 elapsed=71.4s

  [3349/17668] intraday_12136.csv.gz  in=220,763,867 out=35,046,591 elapsed=71.4s

  [3350/17668] intraday_12135.csv.gz  in=221,017,636 out=35,071,265 elapsed=71.5s

  [3351/17668] intraday_1214.csv.gz  in=221,033,314 out=35,071,265 elapsed=71.5s

  [3352/17668] intraday_12137.csv.gz  in=221,257,801 out=35,091,193 elapsed=71.5s

  [3353/17668] intraday_12138.csv.gz  in=221,548,628 out=35,115,168 elapsed=71.6s

  [3354/17668] intraday_12139.csv.gz  in=221,775,397 out=35,141,193 elapsed=71.6s

  [3355/17668] intraday_12140.csv.gz  in=222,020,234 out=35,162,645 elapsed=71.7s

  [3356/17668] intraday_12141.csv.gz  in=222,291,389 out=35,186,819 elapsed=71.8s

  [3357/17668] intraday_12142.csv.gz  in=222,558,052 out=35,211,137 elapsed=71.8s

  [3358/17668] intraday_12143.csv.gz  in=222,834,841 out=35,236,199 elapsed=71.9s

  [3359/17668] intraday_12144.csv.gz  in=223,139,207 out=35,263,760 elapsed=72.0s

  [3360/17668] intraday_12145.csv.gz  in=223,382,869 out=35,287,168 elapsed=72.0s

  [3361/17668] intraday_12146.csv.gz  in=223,626,012 out=35,309,270 elapsed=72.1s

  [3362/17668] intraday_12148.csv.gz  in=223,843,653 out=35,330,130 elapsed=72.2s

  [3363/17668] intraday_1215.csv.gz  in=223,856,471 out=35,330,130 elapsed=72.2s

  [3364/17668] intraday_12149.csv.gz  in=224,095,539 out=35,353,163 elapsed=72.2s

  [3365/17668] intraday_12147.csv.gz  in=224,385,444 out=35,379,259 elapsed=72.2s

  [3366/17668] intraday_12151.csv.gz  in=224,605,311 out=35,399,542 elapsed=72.4s

  [3367/17668] intraday_12150.csv.gz  in=224,849,074 out=35,422,700 elapsed=72.4s

  [3368/17668] intraday_12153.csv.gz  in=225,090,563 out=35,443,973 elapsed=72.4s

  [3369/17668] intraday_12152.csv.gz  in=225,427,243 out=35,471,996 elapsed=72.5s

  [3370/17668] intraday_12154.csv.gz  in=225,680,141 out=35,495,902 elapsed=72.6s

  [3371/17668] intraday_12155.csv.gz  in=225,987,689 out=35,524,058 elapsed=72.7s

  [3372/17668] intraday_12156.csv.gz  in=226,270,380 out=35,549,684 elapsed=72.7s

  [3373/17668] intraday_12157.csv.gz  in=226,523,504 out=35,572,990 elapsed=72.7s

  [3374/17668] intraday_1216.csv.gz  in=226,537,923 out=35,572,990 elapsed=72.7s

  [3375/17668] intraday_12158.csv.gz  in=226,807,839 out=35,599,398 elapsed=72.8s

  [3376/17668] intraday_12159.csv.gz  in=227,052,218 out=35,622,197 elapsed=72.9s

  [3377/17668] intraday_12161.csv.gz  in=227,290,102 out=35,644,611 elapsed=72.9s

  [3378/17668] intraday_12160.csv.gz  in=227,595,707 out=35,669,838 elapsed=72.9s

  [3379/17668] intraday_12162.csv.gz  in=227,847,719 out=35,692,853 elapsed=73.0s

  [3380/17668] intraday_12163.csv.gz  in=228,099,372 out=35,715,809 elapsed=73.1s

  [3381/17668] intraday_12164.csv.gz  in=228,320,836 out=35,736,211 elapsed=73.1s

  [3382/17668] intraday_12165.csv.gz  in=228,626,606 out=35,766,973 elapsed=73.2s

  [3383/17668] intraday_12166.csv.gz  in=228,930,578 out=35,795,155 elapsed=73.2s

  [3384/17668] intraday_1217.csv.gz  in=228,945,018 out=35,795,155 elapsed=73.3s

  [3385/17668] intraday_12167.csv.gz  in=229,217,505 out=35,820,341 elapsed=73.3s

  [3386/17668] intraday_12168.csv.gz  in=229,486,216 out=35,845,737 elapsed=73.3s

  [3387/17668] intraday_12169.csv.gz  in=229,750,975 out=35,869,936 elapsed=73.4s

  [3388/17668] intraday_12170.csv.gz  in=229,956,041 out=35,889,324 elapsed=73.5s

  [3389/17668] intraday_12172.csv.gz  in=230,213,790 out=35,914,806 elapsed=73.5s

  [3390/17668] intraday_12171.csv.gz  in=230,486,328 out=35,940,618 elapsed=73.6s

  [3391/17668] intraday_12173.csv.gz  in=230,760,392 out=35,967,850 elapsed=73.6s

  [3392/17668] intraday_12174.csv.gz  in=231,031,301 out=35,995,475 elapsed=73.7s

  [3393/17668] intraday_12175.csv.gz  in=231,276,048 out=36,018,209 elapsed=73.7s

  [3394/17668] intraday_12176.csv.gz  in=231,524,937 out=36,038,469 elapsed=73.8s

  [3395/17668] intraday_1218.csv.gz  in=231,547,219 out=36,038,469 elapsed=73.8s

  [3396/17668] intraday_12177.csv.gz  in=231,811,347 out=36,062,482 elapsed=73.8s

  [3397/17668] intraday_12178.csv.gz  in=232,081,654 out=36,087,235 elapsed=73.9s

  [3398/17668] intraday_12179.csv.gz  in=232,341,082 out=36,111,117 elapsed=74.0s

  [3399/17668] intraday_12181.csv.gz  in=232,535,300 out=36,130,853 elapsed=74.0s

  [3400/17668] intraday_12180.csv.gz  in=232,807,775 out=36,154,819 elapsed=74.0s

  [3401/17668] intraday_12182.csv.gz  in=233,053,758 out=36,175,998 elapsed=74.1s

  [3402/17668] intraday_12183.csv.gz  in=233,325,233 out=36,200,349 elapsed=74.2s

  [3403/17668] intraday_12185.csv.gz  in=233,652,829 out=36,235,092 elapsed=74.3s

  [3404/17668] intraday_12184.csv.gz  in=234,028,631 out=36,270,441 elapsed=74.3s

  [3405/17668] intraday_12186.csv.gz  in=234,317,159 out=36,298,346 elapsed=74.3s

  [3406/17668] intraday_1219.csv.gz  in=234,331,218 out=36,298,346 elapsed=74.4s

  [3407/17668] intraday_12187.csv.gz  in=234,596,994 out=36,322,138 elapsed=74.4s

  [3408/17668] intraday_12188.csv.gz  in=234,867,329 out=36,345,649 elapsed=74.5s

  [3409/17668] intraday_12189.csv.gz  in=235,149,352 out=36,369,535 elapsed=74.6s

  [3410/17668] intraday_12191.csv.gz  in=235,396,811 out=36,392,265 elapsed=74.6s

  [3411/17668] intraday_12190.csv.gz  in=235,746,650 out=36,422,674 elapsed=74.6s

  [3412/17668] intraday_12192.csv.gz  in=236,002,200 out=36,443,676 elapsed=74.7s

  [3413/17668] intraday_12193.csv.gz  in=236,303,666 out=36,471,028 elapsed=74.8s

  [3414/17668] intraday_12194.csv.gz  in=236,603,410 out=36,498,268 elapsed=74.9s

  [3415/17668] intraday_12195.csv.gz  in=236,903,274 out=36,524,510 elapsed=74.9s

  [3416/17668] intraday_12196.csv.gz  in=237,158,842 out=36,548,263 elapsed=74.9s

  [3417/17668] intraday_1220.csv.gz  in=237,179,804 out=36,548,263 elapsed=75.0s

  [3418/17668] intraday_12197.csv.gz  in=237,442,844 out=36,571,120 elapsed=75.1s

  [3419/17668] intraday_12198.csv.gz  in=237,713,074 out=36,595,876 elapsed=75.1s

  [3420/17668] intraday_12199.csv.gz  in=237,955,374 out=36,614,728 elapsed=75.1s

  [3421/17668] intraday_12200.csv.gz  in=238,290,213 out=36,643,672 elapsed=75.2s

  [3422/17668] intraday_12201.csv.gz  in=238,518,712 out=36,662,912 elapsed=75.3s

  [3423/17668] intraday_12202.csv.gz  in=238,805,947 out=36,688,544 elapsed=75.3s

  [3424/17668] intraday_12203.csv.gz  in=239,120,049 out=36,716,850 elapsed=75.4s

  [3425/17668] intraday_12204.csv.gz  in=239,414,823 out=36,741,127 elapsed=75.5s

  [3426/17668] intraday_12205.csv.gz  in=239,646,734 out=36,767,674 elapsed=75.5s

  [3427/17668] intraday_12206.csv.gz  in=239,920,235 out=36,792,313 elapsed=75.6s

  [3428/17668] intraday_1221.csv.gz  in=239,935,724 out=36,792,313 elapsed=75.6s

  [3429/17668] intraday_12207.csv.gz  in=240,268,815 out=36,822,670 elapsed=75.6s

  [3430/17668] intraday_12209.csv.gz  in=240,521,291 out=36,844,604 elapsed=75.7s

  [3431/17668] intraday_12208.csv.gz  in=240,788,048 out=36,867,772 elapsed=75.7s

  [3432/17668] intraday_12210.csv.gz  in=241,121,091 out=36,896,853 elapsed=75.9s

  [3433/17668] intraday_12212.csv.gz  in=241,387,749 out=36,920,277 elapsed=75.9s

  [3434/17668] intraday_12213.csv.gz  in=241,663,964 out=36,946,020 elapsed=75.9s

  [3435/17668] intraday_12211.csv.gz  in=241,982,222 out=36,975,689 elapsed=75.9s

  [3436/17668] intraday_12214.csv.gz  in=242,251,198 out=37,011,045 elapsed=76.1s

  [3437/17668] intraday_12215.csv.gz  in=242,491,876 out=37,034,969 elapsed=76.1s

  [3438/17668] intraday_12216.csv.gz  in=242,821,382 out=37,063,408 elapsed=76.2s

  [3439/17668] intraday_1222.csv.gz  in=242,833,510 out=37,063,408 elapsed=76.2s

  [3440/17668] intraday_12217.csv.gz  in=243,173,542 out=37,094,556 elapsed=76.2s

  [3441/17668] intraday_12218.csv.gz  in=243,467,450 out=37,129,627 elapsed=76.4s

  [3442/17668] intraday_12219.csv.gz  in=243,765,136 out=37,158,245 elapsed=76.4s

  [3443/17668] intraday_12221.csv.gz  in=243,995,494 out=37,183,526 elapsed=76.4s

  [3444/17668] intraday_12220.csv.gz  in=244,335,193 out=37,214,643 elapsed=76.5s

  [3445/17668] intraday_12223.csv.gz  in=244,565,889 out=37,237,652 elapsed=76.5s

  [3446/17668] intraday_12222.csv.gz  in=244,833,073 out=37,261,995 elapsed=76.6s

  [3447/17668] intraday_12224.csv.gz  in=245,139,181 out=37,289,607 elapsed=76.7s

  [3448/17668] intraday_12225.csv.gz  in=245,373,590 out=37,310,758 elapsed=76.7s

  [3449/17668] intraday_12226.csv.gz  in=245,683,492 out=37,342,442 elapsed=76.8s

  [3450/17668] intraday_1223.csv.gz  in=245,696,953 out=37,342,442 elapsed=76.8s

  [3451/17668] intraday_12227.csv.gz  in=245,974,321 out=37,368,833 elapsed=76.8s

  [3452/17668] intraday_12229.csv.gz  in=246,230,009 out=37,391,295 elapsed=76.9s

  [3453/17668] intraday_12228.csv.gz  in=246,568,706 out=37,420,840 elapsed=77.0s

  [3454/17668] intraday_12231.csv.gz  in=246,830,957 out=37,443,702 elapsed=77.0s

  [3455/17668] intraday_12230.csv.gz  in=247,093,409 out=37,465,202 elapsed=77.0s

  [3456/17668] intraday_12233.csv.gz  in=247,329,262 out=37,486,489 elapsed=77.1s

  [3457/17668] intraday_12232.csv.gz  in=247,648,535 out=37,512,374 elapsed=77.2s

  [3458/17668] intraday_12234.csv.gz  in=247,921,041 out=37,538,583 elapsed=77.3s

  [3459/17668] intraday_12235.csv.gz  in=248,242,467 out=37,570,867 elapsed=77.3s

  [3460/17668] intraday_12236.csv.gz  in=248,535,824 out=37,597,097 elapsed=77.4s

  [3461/17668] intraday_1224.csv.gz  in=248,547,752 out=37,597,097 elapsed=77.4s

  [3462/17668] intraday_12237.csv.gz  in=248,870,513 out=37,628,250 elapsed=77.5s

  [3463/17668] intraday_12238.csv.gz  in=249,126,005 out=37,652,340 elapsed=77.5s

  [3464/17668] intraday_12239.csv.gz  in=249,374,765 out=37,675,971 elapsed=77.6s

  [3465/17668] intraday_12240.csv.gz  in=249,652,365 out=37,699,360 elapsed=77.6s

  [3466/17668] intraday_12241.csv.gz  in=249,903,085 out=37,722,483 elapsed=77.7s

  [3467/17668] intraday_12243.csv.gz  in=250,111,178 out=37,737,247 elapsed=77.8s

  [3468/17668] intraday_12242.csv.gz  in=250,406,449 out=37,761,516 elapsed=77.8s

  [3469/17668] intraday_12246.csv.gz  in=250,410,235 out=37,761,820 elapsed=77.8s

  [3470/17668] intraday_12244.csv.gz  in=250,606,302 out=37,780,778 elapsed=77.8s

  [3471/17668] intraday_12248.csv.gz  in=250,607,537 out=37,780,920 elapsed=77.8s

  [3472/17668] intraday_12247.csv.gz  in=250,609,952 out=37,781,438 elapsed=77.8s

  [3473/17668] intraday_12249.csv.gz  in=250,614,661 out=37,782,882 elapsed=77.8s

  [3474/17668] intraday_1225.csv.gz  in=250,627,502 out=37,782,882 elapsed=77.8s

  [3475/17668] intraday_12252.csv.gz  in=250,628,497 out=37,783,421 elapsed=77.9s

  [3476/17668] intraday_12251.csv.gz  in=250,629,016 out=37,783,487 elapsed=77.9s

  [3477/17668] intraday_12250.csv.gz  in=250,637,107 out=37,786,284 elapsed=77.9s

  [3478/17668] intraday_12254.csv.gz  in=250,640,167 out=37,786,972 elapsed=77.9s

  [3479/17668] intraday_12255.csv.gz  in=250,640,384 out=37,787,003 elapsed=77.9s

  [3480/17668] intraday_12253.csv.gz  in=250,653,186 out=37,793,960 elapsed=77.9s

  [3481/17668] intraday_12256.csv.gz  in=250,654,836 out=37,794,481 elapsed=77.9s

  [3482/17668] intraday_12257.csv.gz  in=250,655,726 out=37,794,580 elapsed=77.9s

  [3483/17668] intraday_12258.csv.gz  in=250,658,148 out=37,794,808 elapsed=77.9s

  [3484/17668] intraday_12245.csv.gz  in=250,932,259 out=37,821,787 elapsed=77.9s

  [3485/17668] intraday_12259.csv.gz  in=250,932,374 out=37,821,789 elapsed=77.9s

  [3486/17668] intraday_1226.csv.gz  in=250,943,002 out=37,821,789 elapsed=78.0s

  [3487/17668] intraday_12261.csv.gz  in=250,943,842 out=37,821,868 elapsed=78.0s

  [3488/17668] intraday_12260.csv.gz  in=250,944,107 out=37,822,000 elapsed=78.0s

  [3489/17668] intraday_12263.csv.gz  in=250,950,494 out=37,824,837 elapsed=78.0s

  [3490/17668] intraday_12264.csv.gz  in=250,950,584 out=37,824,850 elapsed=78.0s

  [3491/17668] intraday_12262.csv.gz  in=250,951,802 out=37,825,085 elapsed=78.0s

  [3492/17668] intraday_12265.csv.gz  in=250,953,650 out=37,825,906 elapsed=78.0s

  [3493/17668] intraday_12266.csv.gz  in=250,956,829 out=37,826,270 elapsed=78.0s

  [3494/17668] intraday_12267.csv.gz  in=250,957,297 out=37,826,270 elapsed=78.0s

  [3495/17668] intraday_12268.csv.gz  in=250,960,177 out=37,826,554 elapsed=78.0s

  [3496/17668] intraday_12269.csv.gz  in=250,963,823 out=37,827,925 elapsed=78.0s

  [3497/17668] intraday_12270.csv.gz  in=250,965,549 out=37,828,159 elapsed=78.0s

  [3498/17668] intraday_1227.csv.gz  in=250,979,780 out=37,828,159 elapsed=78.1s

  [3499/17668] intraday_12271.csv.gz  in=250,986,611 out=37,831,307 elapsed=78.1s

  [3500/17668] intraday_12273.csv.gz  in=250,991,470 out=37,831,307 elapsed=78.1s

  [3501/17668] intraday_12272.csv.gz  in=250,993,699 out=37,832,511 elapsed=78.1s

  [3502/17668] intraday_12275.csv.gz  in=250,994,186 out=37,832,569 elapsed=78.1s

  [3503/17668] intraday_12274.csv.gz  in=250,994,745 out=37,832,709 elapsed=78.1s

  [3504/17668] intraday_12279.csv.gz  in=251,005,097 out=37,843,061 elapsed=78.1s

  [3505/17668] intraday_12277.csv.gz  in=251,018,237 out=37,856,201 elapsed=78.1s

  [3506/17668] intraday_12276.csv.gz  in=251,034,671 out=37,872,635 elapsed=78.1s

  [3507/17668] intraday_12278.csv.gz  in=251,047,083 out=37,885,047 elapsed=78.1s

  [3508/17668] intraday_1228.csv.gz  in=251,055,347 out=37,885,047 elapsed=78.2s

  [3509/17668] intraday_12280.csv.gz  in=251,067,663 out=37,897,363 elapsed=78.2s

  [3510/17668] intraday_12281.csv.gz  in=251,082,854 out=37,912,554 elapsed=78.2s

  [3511/17668] intraday_12282.csv.gz  in=251,097,079 out=37,926,779 elapsed=78.2s

  [3512/17668] intraday_12283.csv.gz  in=251,109,950 out=37,939,650 elapsed=78.2s

  [3513/17668] intraday_12284.csv.gz  in=251,122,989 out=37,952,689 elapsed=78.2s

  [3514/17668] intraday_12285.csv.gz  in=251,135,959 out=37,965,659 elapsed=78.3s

  [3515/17668] intraday_12287.csv.gz  in=251,147,796 out=37,977,496 elapsed=78.3s

  [3516/17668] intraday_12286.csv.gz  in=251,160,056 out=37,989,756 elapsed=78.3s

  [3517/17668] intraday_12288.csv.gz  in=251,174,256 out=38,003,956 elapsed=78.3s

  [3518/17668] intraday_12289.csv.gz  in=251,188,333 out=38,018,033 elapsed=78.3s

  [3519/17668] intraday_1229.csv.gz  in=251,199,030 out=38,018,033 elapsed=78.3s

  [3520/17668] intraday_12290.csv.gz  in=251,209,547 out=38,028,550 elapsed=78.3s

  [3521/17668] intraday_12291.csv.gz  in=251,219,712 out=38,038,715 elapsed=78.3s

  [3522/17668] intraday_12294.csv.gz  in=251,231,271 out=38,050,274 elapsed=78.4s

  [3523/17668] intraday_12293.csv.gz  in=251,243,854 out=38,062,857 elapsed=78.4s

  [3524/17668] intraday_12292.csv.gz  in=251,258,187 out=38,077,190 elapsed=78.4s

  [3525/17668] intraday_12296.csv.gz  in=251,269,045 out=38,088,048 elapsed=78.4s

  [3526/17668] intraday_12297.csv.gz  in=251,281,667 out=38,100,670 elapsed=78.4s

  [3527/17668] intraday_12295.csv.gz  in=251,292,955 out=38,111,958 elapsed=78.4s

  [3528/17668] intraday_12298.csv.gz  in=251,306,372 out=38,125,375 elapsed=78.4s

  [3529/17668] intraday_12299.csv.gz  in=251,317,441 out=38,136,444 elapsed=78.4s

  [3530/17668] intraday_1230.csv.gz  in=251,329,037 out=38,136,444 elapsed=78.4s

  [3531/17668] intraday_12300.csv.gz  in=251,341,564 out=38,148,971 elapsed=78.5s

  [3532/17668] intraday_12301.csv.gz  in=251,352,971 out=38,160,378 elapsed=78.5s

  [3533/17668] intraday_12302.csv.gz  in=251,365,608 out=38,173,015 elapsed=78.5s

  [3534/17668] intraday_12304.csv.gz  in=251,377,377 out=38,184,784 elapsed=78.5s

  [3535/17668] intraday_12303.csv.gz  in=251,389,006 out=38,196,413 elapsed=78.5s

  [3536/17668] intraday_12305.csv.gz  in=251,402,168 out=38,209,575 elapsed=78.5s

  [3537/17668] intraday_12306.csv.gz  in=251,417,174 out=38,224,581 elapsed=78.5s

  [3538/17668] intraday_12308.csv.gz  in=251,427,390 out=38,234,797 elapsed=78.5s

  [3539/17668] intraday_12309.csv.gz  in=251,441,515 out=38,248,922 elapsed=78.6s

  [3540/17668] intraday_12307.csv.gz  in=251,454,947 out=38,262,354 elapsed=78.6s

  [3541/17668] intraday_1231.csv.gz  in=251,470,226 out=38,262,354 elapsed=78.6s

  [3542/17668] intraday_12312.csv.gz  in=251,482,634 out=38,274,762 elapsed=78.6s

  [3543/17668] intraday_12311.csv.gz  in=251,496,226 out=38,288,354 elapsed=78.6s

  [3544/17668] intraday_12313.csv.gz  in=251,506,262 out=38,298,390 elapsed=78.6s

  [3545/17668] intraday_12310.csv.gz  in=251,519,558 out=38,311,686 elapsed=78.6s

  [3546/17668] intraday_12314.csv.gz  in=251,532,111 out=38,324,239 elapsed=78.6s

  [3547/17668] intraday_12315.csv.gz  in=251,541,659 out=38,333,787 elapsed=78.7s

  [3548/17668] intraday_12316.csv.gz  in=251,552,215 out=38,344,343 elapsed=78.7s

  [3549/17668] intraday_12317.csv.gz  in=251,565,546 out=38,357,674 elapsed=78.7s

  [3550/17668] intraday_12318.csv.gz  in=251,577,843 out=38,369,971 elapsed=78.7s

  [3551/17668] intraday_12319.csv.gz  in=251,589,826 out=38,381,954 elapsed=78.7s

  [3552/17668] intraday_12320.csv.gz  in=251,603,402 out=38,395,530 elapsed=78.7s

  [3553/17668] intraday_1232.csv.gz  in=251,617,915 out=38,395,530 elapsed=78.7s

  [3554/17668] intraday_12321.csv.gz  in=251,630,692 out=38,408,307 elapsed=78.8s

  [3555/17668] intraday_12322.csv.gz  in=251,643,005 out=38,420,620 elapsed=78.8s

  [3556/17668] intraday_12324.csv.gz  in=251,657,628 out=38,435,243 elapsed=78.8s

  [3557/17668] intraday_12325.csv.gz  in=251,667,766 out=38,445,381 elapsed=78.8s

  [3558/17668] intraday_12326.csv.gz  in=251,679,647 out=38,457,262 elapsed=78.8s

  [3559/17668] intraday_12327.csv.gz  in=251,688,711 out=38,466,326 elapsed=78.8s

  [3560/17668] intraday_12323.csv.gz  in=251,701,098 out=38,478,713 elapsed=78.8s

  [3561/17668] intraday_12328.csv.gz  in=251,714,856 out=38,492,471 elapsed=78.9s

  [3562/17668] intraday_1233.csv.gz  in=251,726,057 out=38,492,471 elapsed=78.9s

  [3563/17668] intraday_12329.csv.gz  in=251,736,412 out=38,502,826 elapsed=78.9s

  [3564/17668] intraday_12330.csv.gz  in=251,749,008 out=38,515,422 elapsed=78.9s

  [3565/17668] intraday_12331.csv.gz  in=251,763,356 out=38,529,770 elapsed=78.9s

  [3566/17668] intraday_12332.csv.gz  in=251,775,622 out=38,542,036 elapsed=79.0s

  [3567/17668] intraday_12333.csv.gz  in=251,786,940 out=38,553,354 elapsed=79.0s

  [3568/17668] intraday_12334.csv.gz  in=251,797,691 out=38,564,105 elapsed=79.0s

  [3569/17668] intraday_12335.csv.gz  in=251,809,789 out=38,576,203 elapsed=79.0s

  [3570/17668] intraday_12336.csv.gz  in=251,821,673 out=38,588,087 elapsed=79.0s

  [3571/17668] intraday_12337.csv.gz  in=251,834,168 out=38,600,582 elapsed=79.0s

  [3572/17668] intraday_12338.csv.gz  in=251,845,385 out=38,611,799 elapsed=79.0s

  [3573/17668] intraday_12339.csv.gz  in=251,857,849 out=38,624,263 elapsed=79.0s

  [3574/17668] intraday_1234.csv.gz  in=251,869,147 out=38,624,263 elapsed=79.0s

  [3575/17668] intraday_12340.csv.gz  in=251,878,482 out=38,633,598 elapsed=79.1s

  [3576/17668] intraday_12341.csv.gz  in=251,893,228 out=38,648,344 elapsed=79.1s

  [3577/17668] intraday_12343.csv.gz  in=251,905,290 out=38,660,406 elapsed=79.1s

  [3578/17668] intraday_12342.csv.gz  in=251,920,715 out=38,675,831 elapsed=79.1s

  [3579/17668] intraday_12344.csv.gz  in=251,934,528 out=38,689,644 elapsed=79.1s

  [3580/17668] intraday_12345.csv.gz  in=251,947,001 out=38,702,117 elapsed=79.1s

  [3581/17668] intraday_12346.csv.gz  in=251,957,117 out=38,712,233 elapsed=79.1s

  [3582/17668] intraday_12349.csv.gz  in=251,969,884 out=38,725,000 elapsed=79.2s

  [3583/17668] intraday_12348.csv.gz  in=251,982,793 out=38,737,909 elapsed=79.2s

  [3584/17668] intraday_1235.csv.gz  in=251,997,296 out=38,737,909 elapsed=79.2s

  [3585/17668] intraday_12347.csv.gz  in=252,010,748 out=38,751,361 elapsed=79.2s

  [3586/17668] intraday_12351.csv.gz  in=252,022,612 out=38,763,225 elapsed=79.2s

  [3587/17668] intraday_12350.csv.gz  in=252,036,277 out=38,776,890 elapsed=79.2s

  [3588/17668] intraday_12353.csv.gz  in=252,047,589 out=38,788,202 elapsed=79.2s

  [3589/17668] intraday_12352.csv.gz  in=252,058,814 out=38,799,427 elapsed=79.2s

  [3590/17668] intraday_12356.csv.gz  in=252,070,560 out=38,811,173 elapsed=79.3s

  [3591/17668] intraday_12354.csv.gz  in=252,084,178 out=38,824,791 elapsed=79.3s

  [3592/17668] intraday_12355.csv.gz  in=252,096,393 out=38,837,006 elapsed=79.3s

  [3593/17668] intraday_12357.csv.gz  in=252,107,947 out=38,848,560 elapsed=79.3s

  [3594/17668] intraday_12358.csv.gz  in=252,119,214 out=38,859,827 elapsed=79.3s

  [3595/17668] intraday_1236.csv.gz  in=252,133,267 out=38,859,827 elapsed=79.4s

  [3596/17668] intraday_12360.csv.gz  in=252,149,016 out=38,875,576 elapsed=79.4s

  [3597/17668] intraday_12359.csv.gz  in=252,161,250 out=38,887,810 elapsed=79.4s

  [3598/17668] intraday_12361.csv.gz  in=252,178,639 out=38,905,199 elapsed=79.4s

  [3599/17668] intraday_12362.csv.gz  in=252,191,950 out=38,918,510 elapsed=79.4s

  [3600/17668] intraday_12364.csv.gz  in=252,203,461 out=38,930,021 elapsed=79.4s

  [3601/17668] intraday_12363.csv.gz  in=252,215,396 out=38,941,956 elapsed=79.4s

  [3602/17668] intraday_12365.csv.gz  in=252,227,796 out=38,954,356 elapsed=79.4s

  [3603/17668] intraday_12367.csv.gz  in=252,238,552 out=38,965,112 elapsed=79.4s

  [3604/17668] intraday_12366.csv.gz  in=252,253,320 out=38,979,880 elapsed=79.4s

  [3605/17668] intraday_12368.csv.gz  in=252,264,312 out=38,990,872 elapsed=79.4s

  [3606/17668] intraday_12369.csv.gz  in=252,279,801 out=39,006,361 elapsed=79.5s

  [3607/17668] intraday_1237.csv.gz  in=252,292,116 out=39,006,361 elapsed=79.5s

  [3608/17668] intraday_12370.csv.gz  in=252,304,549 out=39,018,794 elapsed=79.5s

  [3609/17668] intraday_12373.csv.gz  in=252,315,677 out=39,029,922 elapsed=79.5s

  [3610/17668] intraday_12372.csv.gz  in=252,328,576 out=39,042,821 elapsed=79.5s

  [3611/17668] intraday_12371.csv.gz  in=252,341,092 out=39,055,337 elapsed=79.5s

  [3612/17668] intraday_12374.csv.gz  in=252,353,981 out=39,068,226 elapsed=79.5s

  [3613/17668] intraday_12375.csv.gz  in=252,367,447 out=39,081,692 elapsed=79.6s

  [3614/17668] intraday_12378.csv.gz  in=252,381,019 out=39,095,264 elapsed=79.6s

  [3615/17668] intraday_12377.csv.gz  in=252,391,929 out=39,106,174 elapsed=79.6s

  [3616/17668] intraday_12376.csv.gz  in=252,403,584 out=39,117,829 elapsed=79.6s

  [3617/17668] intraday_12379.csv.gz  in=252,417,348 out=39,131,593 elapsed=79.6s

  [3618/17668] intraday_12380.csv.gz  in=252,432,068 out=39,145,051 elapsed=79.6s

  [3619/17668] intraday_1238.csv.gz  in=252,444,168 out=39,145,051 elapsed=79.6s

  [3620/17668] intraday_12381.csv.gz  in=252,456,847 out=39,157,730 elapsed=79.6s

  [3621/17668] intraday_12382.csv.gz  in=252,469,865 out=39,170,748 elapsed=79.7s

  [3622/17668] intraday_12384.csv.gz  in=252,480,884 out=39,181,767 elapsed=79.7s

  [3623/17668] intraday_12383.csv.gz  in=252,496,233 out=39,197,116 elapsed=79.7s

  [3624/17668] intraday_12385.csv.gz  in=252,508,683 out=39,209,566 elapsed=79.7s

  [3625/17668] intraday_12386.csv.gz  in=252,522,842 out=39,223,725 elapsed=79.7s

  [3626/17668] intraday_12388.csv.gz  in=252,534,627 out=39,235,510 elapsed=79.7s

  [3627/17668] intraday_12387.csv.gz  in=252,549,718 out=39,250,601 elapsed=79.7s

  [3628/17668] intraday_12389.csv.gz  in=252,563,015 out=39,263,898 elapsed=79.7s

  [3629/17668] intraday_1239.csv.gz  in=252,577,723 out=39,263,898 elapsed=79.7s

  [3630/17668] intraday_12391.csv.gz  in=252,590,954 out=39,277,129 elapsed=79.8s

  [3631/17668] intraday_12390.csv.gz  in=252,606,393 out=39,292,568 elapsed=79.8s

  [3632/17668] intraday_12392.csv.gz  in=252,620,401 out=39,306,576 elapsed=79.8s

  [3633/17668] intraday_12393.csv.gz  in=252,636,731 out=39,322,906 elapsed=79.8s

  [3634/17668] intraday_12395.csv.gz  in=252,650,315 out=39,336,490 elapsed=79.8s

  [3635/17668] intraday_12396.csv.gz  in=252,666,841 out=39,353,016 elapsed=79.8s

  [3636/17668] intraday_12394.csv.gz  in=252,685,433 out=39,371,608 elapsed=79.8s

  [3637/17668] intraday_12398.csv.gz  in=252,697,753 out=39,383,928 elapsed=79.9s

  [3638/17668] intraday_1240.csv.gz  in=252,711,811 out=39,383,928 elapsed=79.9s

  [3639/17668] intraday_12399.csv.gz  in=252,724,403 out=39,396,520 elapsed=79.9s

  [3640/17668] intraday_12397.csv.gz  in=252,758,923 out=39,418,036 elapsed=79.9s

  [3641/17668] intraday_12400.csv.gz  in=252,771,355 out=39,430,468 elapsed=79.9s

  [3642/17668] intraday_12402.csv.gz  in=252,784,467 out=39,443,580 elapsed=79.9s

  [3643/17668] intraday_12401.csv.gz  in=252,795,345 out=39,454,458 elapsed=80.0s

  [3644/17668] intraday_12403.csv.gz  in=252,807,016 out=39,466,129 elapsed=80.0s

  [3645/17668] intraday_12404.csv.gz  in=252,822,870 out=39,481,983 elapsed=80.0s

  [3646/17668] intraday_12405.csv.gz  in=252,833,431 out=39,492,544 elapsed=80.0s

  [3647/17668] intraday_12407.csv.gz  in=252,845,134 out=39,504,247 elapsed=80.0s

  [3648/17668] intraday_12406.csv.gz  in=252,856,395 out=39,515,508 elapsed=80.0s

  [3649/17668] intraday_12408.csv.gz  in=252,870,711 out=39,529,824 elapsed=80.0s

  [3650/17668] intraday_12409.csv.gz  in=252,881,309 out=39,540,422 elapsed=80.1s

  [3651/17668] intraday_1241.csv.gz  in=252,891,080 out=39,540,422 elapsed=80.1s

  [3652/17668] intraday_12410.csv.gz  in=252,904,800 out=39,554,142 elapsed=80.1s

  [3653/17668] intraday_12411.csv.gz  in=252,919,435 out=39,568,777 elapsed=80.1s

  [3654/17668] intraday_12413.csv.gz  in=252,933,385 out=39,582,727 elapsed=80.1s

  [3655/17668] intraday_12412.csv.gz  in=252,947,687 out=39,597,029 elapsed=80.1s

  [3656/17668] intraday_12414.csv.gz  in=252,961,932 out=39,611,274 elapsed=80.1s

  [3657/17668] intraday_12415.csv.gz  in=252,973,648 out=39,622,990 elapsed=80.1s

  [3658/17668] intraday_12417.csv.gz  in=252,983,982 out=39,633,324 elapsed=80.2s

  [3659/17668] intraday_12416.csv.gz  in=252,996,602 out=39,645,944 elapsed=80.2s

  [3660/17668] intraday_12418.csv.gz  in=253,009,698 out=39,659,040 elapsed=80.2s

  [3661/17668] intraday_12419.csv.gz  in=253,017,733 out=39,667,075 elapsed=80.2s

  [3662/17668] intraday_12420.csv.gz  in=253,025,345 out=39,674,687 elapsed=80.2s

  [3663/17668] intraday_1242.csv.gz  in=253,040,331 out=39,674,687 elapsed=80.2s

  [3664/17668] intraday_12421.csv.gz  in=253,053,892 out=39,688,248 elapsed=80.2s

  [3665/17668] intraday_12422.csv.gz  in=253,057,505 out=39,691,861 elapsed=80.2s

  [3666/17668] intraday_12424.csv.gz  in=253,070,389 out=39,704,745 elapsed=80.3s

  [3667/17668] intraday_12423.csv.gz  in=253,088,474 out=39,722,830 elapsed=80.3s

  [3668/17668] intraday_12425.csv.gz  in=253,102,867 out=39,737,223 elapsed=80.3s

  [3669/17668] intraday_12426.csv.gz  in=253,115,109 out=39,748,696 elapsed=80.3s

  [3670/17668] intraday_12427.csv.gz  in=253,127,389 out=39,760,976 elapsed=80.3s

  [3671/17668] intraday_12428.csv.gz  in=253,142,244 out=39,775,831 elapsed=80.3s

  [3672/17668] intraday_1243.csv.gz  in=253,157,514 out=39,775,831 elapsed=80.3s

  [3673/17668] intraday_12429.csv.gz  in=253,176,682 out=39,794,999 elapsed=80.4s

  [3674/17668] intraday_12430.csv.gz  in=253,188,243 out=39,806,560 elapsed=80.4s

  [3675/17668] intraday_12431.csv.gz  in=253,202,184 out=39,820,501 elapsed=80.4s

  [3676/17668] intraday_12432.csv.gz  in=253,216,449 out=39,834,766 elapsed=80.4s

  [3677/17668] intraday_12433.csv.gz  in=253,229,838 out=39,848,155 elapsed=80.4s

  [3678/17668] intraday_12434.csv.gz  in=253,242,928 out=39,861,245 elapsed=80.4s

  [3679/17668] intraday_12435.csv.gz  in=253,257,019 out=39,875,336 elapsed=80.4s

  [3680/17668] intraday_12436.csv.gz  in=253,271,194 out=39,889,511 elapsed=80.4s

  [3681/17668] intraday_12437.csv.gz  in=253,293,466 out=39,904,574 elapsed=80.4s

  [3682/17668] intraday_12438.csv.gz  in=253,306,341 out=39,916,479 elapsed=80.5s

  [3683/17668] intraday_1244.csv.gz  in=253,317,398 out=39,916,479 elapsed=80.5s

  [3684/17668] intraday_12439.csv.gz  in=253,332,154 out=39,931,079 elapsed=80.5s

  [3685/17668] intraday_12440.csv.gz  in=253,345,750 out=39,944,675 elapsed=80.5s

  [3686/17668] intraday_12443.csv.gz  in=253,357,196 out=39,956,121 elapsed=80.5s

  [3687/17668] intraday_12441.csv.gz  in=253,368,020 out=39,966,945 elapsed=80.5s

  [3688/17668] intraday_12442.csv.gz  in=253,378,660 out=39,977,585 elapsed=80.5s

  [3689/17668] intraday_12445.csv.gz  in=253,391,223 out=39,990,148 elapsed=80.5s

  [3690/17668] intraday_12444.csv.gz  in=253,404,027 out=40,002,952 elapsed=80.5s

  [3691/17668] intraday_12446.csv.gz  in=253,416,350 out=40,015,275 elapsed=80.6s

  [3692/17668] intraday_12447.csv.gz  in=253,429,188 out=40,028,113 elapsed=80.6s

  [3693/17668] intraday_1245.csv.gz  in=253,439,869 out=40,028,113 elapsed=80.6s

  [3694/17668] intraday_12449.csv.gz  in=253,453,384 out=40,041,628 elapsed=80.6s

  [3695/17668] intraday_12448.csv.gz  in=253,465,215 out=40,053,459 elapsed=80.6s

  [3696/17668] intraday_12450.csv.gz  in=253,477,210 out=40,065,454 elapsed=80.6s

  [3697/17668] intraday_12451.csv.gz  in=253,489,121 out=40,077,365 elapsed=80.6s

  [3698/17668] intraday_12452.csv.gz  in=253,502,552 out=40,090,796 elapsed=80.6s

  [3699/17668] intraday_12453.csv.gz  in=253,518,670 out=40,106,914 elapsed=80.7s

  [3700/17668] intraday_12454.csv.gz  in=253,532,816 out=40,121,060 elapsed=80.7s

  [3701/17668] intraday_12455.csv.gz  in=253,543,320 out=40,131,564 elapsed=80.7s

  [3702/17668] intraday_12456.csv.gz  in=253,558,192 out=40,146,436 elapsed=80.7s

  [3703/17668] intraday_12457.csv.gz  in=253,574,238 out=40,161,443 elapsed=80.7s

  [3704/17668] intraday_12458.csv.gz  in=253,588,525 out=40,175,730 elapsed=80.7s

  [3705/17668] intraday_12459.csv.gz  in=253,600,465 out=40,187,670 elapsed=80.7s

  [3706/17668] intraday_1246.csv.gz  in=253,611,996 out=40,187,670 elapsed=80.7s

  [3707/17668] intraday_12460.csv.gz  in=253,623,532 out=40,199,206 elapsed=80.7s

  [3708/17668] intraday_12461.csv.gz  in=253,635,942 out=40,211,616 elapsed=80.8s

  [3709/17668] intraday_12463.csv.gz  in=253,647,324 out=40,222,998 elapsed=80.8s

  [3710/17668] intraday_12462.csv.gz  in=253,658,414 out=40,234,088 elapsed=80.8s

  [3711/17668] intraday_12464.csv.gz  in=253,673,500 out=40,249,174 elapsed=80.8s

  [3712/17668] intraday_12465.csv.gz  in=253,685,521 out=40,261,195 elapsed=80.8s

  [3713/17668] intraday_12468.csv.gz  in=253,697,688 out=40,273,362 elapsed=80.8s

  [3714/17668] intraday_12467.csv.gz  in=253,713,082 out=40,288,756 elapsed=80.8s

  [3715/17668] intraday_12466.csv.gz  in=253,726,174 out=40,301,848 elapsed=80.8s

  [3716/17668] intraday_12469.csv.gz  in=253,738,980 out=40,314,654 elapsed=80.9s

  [3717/17668] intraday_1247.csv.gz  in=253,751,964 out=40,314,654 elapsed=80.9s

  [3718/17668] intraday_12471.csv.gz  in=253,765,616 out=40,328,306 elapsed=80.9s

  [3719/17668] intraday_12472.csv.gz  in=253,781,198 out=40,340,383 elapsed=80.9s

  [3720/17668] intraday_12470.csv.gz  in=253,792,727 out=40,351,912 elapsed=80.9s

  [3721/17668] intraday_12473.csv.gz  in=253,805,477 out=40,364,662 elapsed=80.9s

  [3722/17668] intraday_12474.csv.gz  in=253,816,043 out=40,375,228 elapsed=80.9s

  [3723/17668] intraday_12475.csv.gz  in=253,828,892 out=40,388,077 elapsed=81.0s

  [3724/17668] intraday_12476.csv.gz  in=253,841,338 out=40,400,523 elapsed=81.0s

  [3725/17668] intraday_12477.csv.gz  in=253,853,884 out=40,413,069 elapsed=81.0s

  [3726/17668] intraday_12478.csv.gz  in=253,868,645 out=40,427,830 elapsed=81.0s

  [3727/17668] intraday_12479.csv.gz  in=253,879,230 out=40,438,415 elapsed=81.0s

  [3728/17668] intraday_1248.csv.gz  in=253,892,285 out=40,438,415 elapsed=81.0s

  [3729/17668] intraday_12481.csv.gz  in=253,903,357 out=40,449,487 elapsed=81.0s

  [3730/17668] intraday_12480.csv.gz  in=253,914,944 out=40,461,074 elapsed=81.1s

  [3731/17668] intraday_12482.csv.gz  in=253,927,871 out=40,474,001 elapsed=81.1s

  [3732/17668] intraday_12483.csv.gz  in=253,940,086 out=40,486,216 elapsed=81.1s

  [3733/17668] intraday_12484.csv.gz  in=253,952,252 out=40,498,382 elapsed=81.1s

  [3734/17668] intraday_12485.csv.gz  in=253,965,378 out=40,511,508 elapsed=81.1s

  [3735/17668] intraday_12486.csv.gz  in=253,977,481 out=40,523,611 elapsed=81.1s

  [3736/17668] intraday_12487.csv.gz  in=253,988,094 out=40,534,224 elapsed=81.1s

  [3737/17668] intraday_12489.csv.gz  in=254,003,873 out=40,550,003 elapsed=81.1s

  [3738/17668] intraday_1249.csv.gz  in=254,015,482 out=40,550,003 elapsed=81.1s

  [3739/17668] intraday_12488.csv.gz  in=254,028,934 out=40,563,455 elapsed=81.1s

  [3740/17668] intraday_12490.csv.gz  in=254,042,792 out=40,577,313 elapsed=81.2s

  [3741/17668] intraday_12491.csv.gz  in=254,057,384 out=40,591,905 elapsed=81.2s

  [3742/17668] intraday_12492.csv.gz  in=254,070,229 out=40,604,750 elapsed=81.2s

  [3743/17668] intraday_12493.csv.gz  in=254,081,653 out=40,616,174 elapsed=81.2s

  [3744/17668] intraday_12494.csv.gz  in=254,093,749 out=40,628,270 elapsed=81.2s

  [3745/17668] intraday_12496.csv.gz  in=254,106,682 out=40,641,203 elapsed=81.2s

  [3746/17668] intraday_12495.csv.gz  in=254,120,696 out=40,655,217 elapsed=81.2s

  [3747/17668] intraday_12497.csv.gz  in=254,134,660 out=40,669,181 elapsed=81.3s

  [3748/17668] intraday_12498.csv.gz  in=254,146,294 out=40,680,815 elapsed=81.3s

  [3749/17668] intraday_1250.csv.gz  in=254,157,103 out=40,680,815 elapsed=81.3s

  [3750/17668] intraday_12499.csv.gz  in=254,170,117 out=40,693,829 elapsed=81.3s

  [3751/17668] intraday_12500.csv.gz  in=254,181,636 out=40,705,348 elapsed=81.3s

  [3752/17668] intraday_12502.csv.gz  in=254,193,391 out=40,717,103 elapsed=81.3s

  [3753/17668] intraday_12501.csv.gz  in=254,208,103 out=40,731,815 elapsed=81.3s

  [3754/17668] intraday_12503.csv.gz  in=254,220,813 out=40,744,525 elapsed=81.3s

  [3755/17668] intraday_12504.csv.gz  in=254,232,313 out=40,756,025 elapsed=81.4s

  [3756/17668] intraday_12506.csv.gz  in=254,245,174 out=40,768,886 elapsed=81.4s

  [3757/17668] intraday_12505.csv.gz  in=254,256,149 out=40,779,861 elapsed=81.4s

  [3758/17668] intraday_12507.csv.gz  in=254,271,220 out=40,794,932 elapsed=81.4s

  [3759/17668] intraday_12508.csv.gz  in=254,289,210 out=40,812,922 elapsed=81.4s

  [3760/17668] intraday_12509.csv.gz  in=254,303,451 out=40,827,163 elapsed=81.4s

  [3761/17668] intraday_1251.csv.gz  in=254,316,285 out=40,827,163 elapsed=81.5s

  [3762/17668] intraday_12510.csv.gz  in=254,327,365 out=40,838,243 elapsed=81.5s

  [3763/17668] intraday_12511.csv.gz  in=254,339,528 out=40,850,406 elapsed=81.5s

  [3764/17668] intraday_12512.csv.gz  in=254,352,826 out=40,863,704 elapsed=81.5s

  [3765/17668] intraday_12513.csv.gz  in=254,364,821 out=40,875,699 elapsed=81.5s

  [3766/17668] intraday_12515.csv.gz  in=254,376,394 out=40,887,272 elapsed=81.5s

  [3767/17668] intraday_12514.csv.gz  in=254,391,670 out=40,902,548 elapsed=81.5s

  [3768/17668] intraday_12516.csv.gz  in=254,407,426 out=40,918,304 elapsed=81.6s

  [3769/17668] intraday_12517.csv.gz  in=254,421,788 out=40,932,666 elapsed=81.6s

  [3770/17668] intraday_12518.csv.gz  in=254,433,102 out=40,943,980 elapsed=81.6s

  [3771/17668] intraday_1252.csv.gz  in=254,445,070 out=40,943,980 elapsed=81.6s

  [3772/17668] intraday_12519.csv.gz  in=254,458,389 out=40,957,299 elapsed=81.6s

  [3773/17668] intraday_12520.csv.gz  in=254,469,947 out=40,968,857 elapsed=81.6s

  [3774/17668] intraday_12521.csv.gz  in=254,483,931 out=40,982,841 elapsed=81.6s

  [3775/17668] intraday_12523.csv.gz  in=254,498,723 out=40,997,633 elapsed=81.7s

  [3776/17668] intraday_12522.csv.gz  in=254,509,973 out=41,008,883 elapsed=81.7s

  [3777/17668] intraday_12524.csv.gz  in=254,522,162 out=41,021,072 elapsed=81.7s

  [3778/17668] intraday_12525.csv.gz  in=254,534,919 out=41,033,829 elapsed=81.7s

  [3779/17668] intraday_12526.csv.gz  in=254,548,212 out=41,047,122 elapsed=81.7s

  [3780/17668] intraday_12529.csv.gz  in=254,560,572 out=41,059,482 elapsed=81.7s

  [3781/17668] intraday_12528.csv.gz  in=254,575,123 out=41,074,033 elapsed=81.7s

  [3782/17668] intraday_12527.csv.gz  in=254,589,977 out=41,088,887 elapsed=81.7s

  [3783/17668] intraday_1253.csv.gz  in=254,602,758 out=41,088,887 elapsed=81.7s

  [3784/17668] intraday_12530.csv.gz  in=254,615,596 out=41,101,725 elapsed=81.8s

  [3785/17668] intraday_12533.csv.gz  in=254,629,912 out=41,116,041 elapsed=81.8s

  [3786/17668] intraday_12532.csv.gz  in=254,641,911 out=41,128,040 elapsed=81.8s

  [3787/17668] intraday_12531.csv.gz  in=254,656,539 out=41,142,668 elapsed=81.8s

  [3788/17668] intraday_12534.csv.gz  in=254,671,361 out=41,157,490 elapsed=81.8s

  [3789/17668] intraday_12535.csv.gz  in=254,684,241 out=41,170,370 elapsed=81.8s

  [3790/17668] intraday_12536.csv.gz  in=254,696,724 out=41,182,853 elapsed=81.9s

  [3791/17668] intraday_12537.csv.gz  in=254,710,772 out=41,196,901 elapsed=81.9s

  [3792/17668] intraday_12539.csv.gz  in=254,723,654 out=41,209,783 elapsed=81.9s

  [3793/17668] intraday_12538.csv.gz  in=254,740,585 out=41,226,714 elapsed=81.9s

  [3794/17668] intraday_1254.csv.gz  in=254,753,134 out=41,226,714 elapsed=81.9s

  [3795/17668] intraday_12540.csv.gz  in=254,769,143 out=41,242,723 elapsed=81.9s

  [3796/17668] intraday_12541.csv.gz  in=254,788,764 out=41,262,344 elapsed=82.0s

  [3797/17668] intraday_12542.csv.gz  in=254,803,840 out=41,277,420 elapsed=82.0s

  [3798/17668] intraday_12543.csv.gz  in=254,821,568 out=41,295,148 elapsed=82.0s

  [3799/17668] intraday_12544.csv.gz  in=254,834,600 out=41,308,180 elapsed=82.0s

  [3800/17668] intraday_12545.csv.gz  in=254,846,858 out=41,320,438 elapsed=82.0s

  [3801/17668] intraday_12546.csv.gz  in=254,859,642 out=41,333,222 elapsed=82.0s

  [3802/17668] intraday_12547.csv.gz  in=254,872,367 out=41,345,947 elapsed=82.0s

  [3803/17668] intraday_12548.csv.gz  in=254,884,548 out=41,358,128 elapsed=82.0s

  [3804/17668] intraday_12549.csv.gz  in=254,896,392 out=41,369,972 elapsed=82.0s

  [3805/17668] intraday_1255.csv.gz  in=254,908,885 out=41,369,972 elapsed=82.0s

  [3806/17668] intraday_12550.csv.gz  in=254,923,075 out=41,384,162 elapsed=82.1s

  [3807/17668] intraday_12551.csv.gz  in=254,937,930 out=41,399,017 elapsed=82.1s

  [3808/17668] intraday_12553.csv.gz  in=254,949,680 out=41,410,767 elapsed=82.1s

  [3809/17668] intraday_12552.csv.gz  in=254,963,285 out=41,424,372 elapsed=82.1s

  [3810/17668] intraday_12554.csv.gz  in=254,974,573 out=41,435,660 elapsed=82.1s

  [3811/17668] intraday_12555.csv.gz  in=254,989,202 out=41,450,289 elapsed=82.1s

  [3812/17668] intraday_12556.csv.gz  in=255,000,711 out=41,461,798 elapsed=82.1s

  [3813/17668] intraday_12557.csv.gz  in=255,013,693 out=41,474,780 elapsed=82.1s

  [3814/17668] intraday_12558.csv.gz  in=255,028,613 out=41,489,700 elapsed=82.1s

  [3815/17668] intraday_12559.csv.gz  in=255,044,108 out=41,505,195 elapsed=82.2s

  [3816/17668] intraday_1256.csv.gz  in=255,063,672 out=41,505,195 elapsed=82.2s

  [3817/17668] intraday_12560.csv.gz  in=255,077,606 out=41,519,129 elapsed=82.2s

  [3818/17668] intraday_12561.csv.gz  in=255,093,697 out=41,535,220 elapsed=82.2s

  [3819/17668] intraday_12562.csv.gz  in=255,105,323 out=41,546,846 elapsed=82.2s

  [3820/17668] intraday_12564.csv.gz  in=255,117,307 out=41,558,830 elapsed=82.2s

  [3821/17668] intraday_12563.csv.gz  in=255,130,226 out=41,571,749 elapsed=82.2s

  [3822/17668] intraday_12565.csv.gz  in=255,142,225 out=41,583,748 elapsed=82.3s

  [3823/17668] intraday_12567.csv.gz  in=255,148,960 out=41,590,483 elapsed=82.3s

  [3824/17668] intraday_12566.csv.gz  in=255,159,094 out=41,600,617 elapsed=82.3s

  [3825/17668] intraday_12569.csv.gz  in=255,165,232 out=41,606,755 elapsed=82.3s

  [3826/17668] intraday_12568.csv.gz  in=255,179,345 out=41,620,868 elapsed=82.3s

  [3827/17668] intraday_1257.csv.gz  in=255,196,915 out=41,620,868 elapsed=82.3s

  [3828/17668] intraday_12570.csv.gz  in=255,214,369 out=41,638,322 elapsed=82.3s

  [3829/17668] intraday_12571.csv.gz  in=255,227,260 out=41,651,213 elapsed=82.3s

  [3830/17668] intraday_12573.csv.gz  in=255,238,396 out=41,662,349 elapsed=82.4s

  [3831/17668] intraday_12572.csv.gz  in=255,251,980 out=41,675,933 elapsed=82.4s

  [3832/17668] intraday_12575.csv.gz  in=255,266,235 out=41,690,188 elapsed=82.4s

  [3833/17668] intraday_12574.csv.gz  in=255,277,869 out=41,701,822 elapsed=82.4s

  [3834/17668] intraday_12577.csv.gz  in=255,290,717 out=41,714,670 elapsed=82.4s

  [3835/17668] intraday_12576.csv.gz  in=255,307,762 out=41,731,715 elapsed=82.4s

  [3836/17668] intraday_12578.csv.gz  in=255,320,746 out=41,744,699 elapsed=82.4s

  [3837/17668] intraday_12579.csv.gz  in=255,334,555 out=41,758,508 elapsed=82.5s

  [3838/17668] intraday_1258.csv.gz  in=255,347,391 out=41,758,508 elapsed=82.5s

  [3839/17668] intraday_12580.csv.gz  in=255,360,628 out=41,771,745 elapsed=82.5s

  [3840/17668] intraday_12581.csv.gz  in=255,372,294 out=41,783,411 elapsed=82.5s

  [3841/17668] intraday_12582.csv.gz  in=255,387,063 out=41,798,180 elapsed=82.5s

  [3842/17668] intraday_12583.csv.gz  in=255,400,506 out=41,811,623 elapsed=82.5s

  [3843/17668] intraday_12584.csv.gz  in=255,410,286 out=41,821,403 elapsed=82.5s

  [3844/17668] intraday_12585.csv.gz  in=255,421,356 out=41,832,473 elapsed=82.5s

  [3845/17668] intraday_12586.csv.gz  in=255,436,400 out=41,847,517 elapsed=82.6s

  [3846/17668] intraday_12588.csv.gz  in=255,446,307 out=41,857,424 elapsed=82.6s

  [3847/17668] intraday_12587.csv.gz  in=255,459,541 out=41,870,658 elapsed=82.6s

  [3848/17668] intraday_12589.csv.gz  in=255,470,106 out=41,881,223 elapsed=82.6s

  [3849/17668] intraday_1259.csv.gz  in=255,483,550 out=41,881,223 elapsed=82.6s

  [3850/17668] intraday_12590.csv.gz  in=255,494,605 out=41,892,278 elapsed=82.6s

  [3851/17668] intraday_12591.csv.gz  in=255,506,950 out=41,904,623 elapsed=82.6s

  [3852/17668] intraday_12592.csv.gz  in=255,518,937 out=41,916,610 elapsed=82.6s

  [3853/17668] intraday_12593.csv.gz  in=255,530,958 out=41,928,631 elapsed=82.7s

  [3854/17668] intraday_12594.csv.gz  in=255,545,023 out=41,942,696 elapsed=82.7s

  [3855/17668] intraday_12595.csv.gz  in=255,556,185 out=41,953,858 elapsed=82.7s

  [3856/17668] intraday_12596.csv.gz  in=255,568,060 out=41,965,733 elapsed=82.7s

  [3857/17668] intraday_12597.csv.gz  in=255,580,813 out=41,978,486 elapsed=82.7s

  [3858/17668] intraday_12598.csv.gz  in=255,592,645 out=41,990,318 elapsed=82.7s

  [3859/17668] intraday_1260.csv.gz  in=255,607,842 out=41,990,318 elapsed=82.7s

  [3860/17668] intraday_12599.csv.gz  in=255,621,072 out=42,003,548 elapsed=82.7s

  [3861/17668] intraday_12600.csv.gz  in=255,637,099 out=42,019,575 elapsed=82.7s

  [3862/17668] intraday_12601.csv.gz  in=255,650,388 out=42,032,864 elapsed=82.8s

  [3863/17668] intraday_12602.csv.gz  in=255,660,431 out=42,042,907 elapsed=82.8s

  [3864/17668] intraday_12603.csv.gz  in=255,673,643 out=42,056,119 elapsed=82.8s

  [3865/17668] intraday_12604.csv.gz  in=255,686,580 out=42,069,056 elapsed=82.8s

  [3866/17668] intraday_12606.csv.gz  in=255,699,204 out=42,081,680 elapsed=82.8s

  [3867/17668] intraday_12605.csv.gz  in=255,712,617 out=42,095,093 elapsed=82.8s

  [3868/17668] intraday_12607.csv.gz  in=255,723,325 out=42,105,801 elapsed=82.8s

  [3869/17668] intraday_1261.csv.gz  in=255,736,635 out=42,105,801 elapsed=82.9s

  [3870/17668] intraday_12609.csv.gz  in=255,747,158 out=42,115,880 elapsed=82.9s

  [3871/17668] intraday_12608.csv.gz  in=255,763,546 out=42,128,794 elapsed=82.9s

  [3872/17668] intraday_12610.csv.gz  in=255,775,487 out=42,140,735 elapsed=82.9s

  [3873/17668] intraday_12611.csv.gz  in=255,789,638 out=42,154,886 elapsed=82.9s

  [3874/17668] intraday_12612.csv.gz  in=255,800,781 out=42,166,029 elapsed=82.9s

  [3875/17668] intraday_12613.csv.gz  in=255,822,549 out=42,182,864 elapsed=83.0s

  [3876/17668] intraday_12614.csv.gz  in=255,836,742 out=42,197,057 elapsed=83.0s

  [3877/17668] intraday_12615.csv.gz  in=255,849,330 out=42,209,645 elapsed=83.0s

  [3878/17668] intraday_12616.csv.gz  in=255,860,488 out=42,220,803 elapsed=83.0s

  [3879/17668] intraday_12617.csv.gz  in=255,872,070 out=42,232,385 elapsed=83.0s

  [3880/17668] intraday_1262.csv.gz  in=255,884,146 out=42,232,385 elapsed=83.0s

  [3881/17668] intraday_12618.csv.gz  in=255,897,470 out=42,245,709 elapsed=83.0s

  [3882/17668] intraday_12619.csv.gz  in=255,908,076 out=42,256,315 elapsed=83.0s

  [3883/17668] intraday_12622.csv.gz  in=255,922,818 out=42,271,057 elapsed=83.1s

  [3884/17668] intraday_12621.csv.gz  in=255,932,885 out=42,281,124 elapsed=83.1s

  [3885/17668] intraday_12620.csv.gz  in=255,965,767 out=42,301,821 elapsed=83.1s

  [3886/17668] intraday_12623.csv.gz  in=255,978,738 out=42,314,792 elapsed=83.1s

  [3887/17668] intraday_12627.csv.gz  in=255,990,411 out=42,326,465 elapsed=83.2s

  [3888/17668] intraday_12626.csv.gz  in=256,001,709 out=42,337,763 elapsed=83.2s

  [3889/17668] intraday_12625.csv.gz  in=256,015,507 out=42,351,561 elapsed=83.2s

  [3890/17668] intraday_12624.csv.gz  in=256,027,793 out=42,363,847 elapsed=83.2s

  [3891/17668] intraday_1263.csv.gz  in=256,041,090 out=42,363,847 elapsed=83.2s

  [3892/17668] intraday_12629.csv.gz  in=256,055,307 out=42,377,073 elapsed=83.2s

  [3893/17668] intraday_12630.csv.gz  in=256,066,956 out=42,388,722 elapsed=83.2s

  [3894/17668] intraday_12628.csv.gz  in=256,077,241 out=42,399,007 elapsed=83.2s

  [3895/17668] intraday_12631.csv.gz  in=256,090,591 out=42,411,960 elapsed=83.3s

  [3896/17668] intraday_12633.csv.gz  in=256,103,233 out=42,424,602 elapsed=83.3s

  [3897/17668] intraday_12634.csv.gz  in=256,112,434 out=42,433,803 elapsed=83.3s

  [3898/17668] intraday_12632.csv.gz  in=256,134,565 out=42,450,652 elapsed=83.3s

  [3899/17668] intraday_12635.csv.gz  in=256,148,863 out=42,464,950 elapsed=83.3s

  [3900/17668] intraday_12637.csv.gz  in=256,162,093 out=42,478,180 elapsed=83.3s

  [3901/17668] intraday_12636.csv.gz  in=256,176,925 out=42,493,012 elapsed=83.4s

  [3902/17668] intraday_12638.csv.gz  in=256,190,474 out=42,506,561 elapsed=83.4s

  [3903/17668] intraday_1264.csv.gz  in=256,205,048 out=42,506,561 elapsed=83.4s

  [3904/17668] intraday_12639.csv.gz  in=256,219,180 out=42,520,693 elapsed=83.4s

  [3905/17668] intraday_12640.csv.gz  in=256,229,495 out=42,531,008 elapsed=83.4s

  [3906/17668] intraday_12641.csv.gz  in=256,241,714 out=42,543,070 elapsed=83.4s

  [3907/17668] intraday_12642.csv.gz  in=256,255,362 out=42,556,718 elapsed=83.4s

  [3908/17668] intraday_12643.csv.gz  in=256,267,739 out=42,569,095 elapsed=83.4s

  [3909/17668] intraday_12644.csv.gz  in=256,281,393 out=42,582,447 elapsed=83.4s

  [3910/17668] intraday_12645.csv.gz  in=256,292,343 out=42,593,397 elapsed=83.5s

  [3911/17668] intraday_12646.csv.gz  in=256,304,644 out=42,605,698 elapsed=83.5s

  [3912/17668] intraday_12647.csv.gz  in=256,315,866 out=42,616,920 elapsed=83.5s

  [3913/17668] intraday_12649.csv.gz  in=256,326,798 out=42,627,852 elapsed=83.5s

  [3914/17668] intraday_12648.csv.gz  in=256,340,313 out=42,641,367 elapsed=83.5s

  [3915/17668] intraday_1265.csv.gz  in=256,351,909 out=42,641,367 elapsed=83.5s

  [3916/17668] intraday_12650.csv.gz  in=256,364,703 out=42,654,161 elapsed=83.5s

  [3917/17668] intraday_12652.csv.gz  in=256,374,586 out=42,664,044 elapsed=83.5s

  [3918/17668] intraday_12651.csv.gz  in=256,385,471 out=42,674,929 elapsed=83.6s

  [3919/17668] intraday_12653.csv.gz  in=256,399,431 out=42,688,889 elapsed=83.6s

  [3920/17668] intraday_12654.csv.gz  in=256,413,134 out=42,702,592 elapsed=83.6s

  [3921/17668] intraday_12655.csv.gz  in=256,428,977 out=42,718,435 elapsed=83.6s

  [3922/17668] intraday_12656.csv.gz  in=256,442,333 out=42,731,791 elapsed=83.6s

  [3923/17668] intraday_12657.csv.gz  in=256,460,843 out=42,747,109 elapsed=83.6s

  [3924/17668] intraday_12658.csv.gz  in=256,471,942 out=42,758,208 elapsed=83.6s

  [3925/17668] intraday_1266.csv.gz  in=256,486,717 out=42,758,208 elapsed=83.6s

  [3926/17668] intraday_12659.csv.gz  in=256,500,109 out=42,771,600 elapsed=83.6s

  [3927/17668] intraday_12660.csv.gz  in=256,514,516 out=42,786,007 elapsed=83.7s

  [3928/17668] intraday_12662.csv.gz  in=256,525,753 out=42,797,244 elapsed=83.7s

  [3929/17668] intraday_12663.csv.gz  in=256,541,160 out=42,812,651 elapsed=83.7s

  [3930/17668] intraday_12661.csv.gz  in=256,554,556 out=42,826,047 elapsed=83.7s

  [3931/17668] intraday_12664.csv.gz  in=256,568,300 out=42,839,791 elapsed=83.7s

  [3932/17668] intraday_12665.csv.gz  in=256,579,228 out=42,850,719 elapsed=83.7s

  [3933/17668] intraday_12667.csv.gz  in=256,590,014 out=42,861,505 elapsed=83.7s

  [3934/17668] intraday_12666.csv.gz  in=256,603,840 out=42,875,331 elapsed=83.7s

  [3935/17668] intraday_12668.csv.gz  in=256,616,442 out=42,887,933 elapsed=83.8s

  [3936/17668] intraday_1267.csv.gz  in=256,628,762 out=42,887,933 elapsed=83.8s

  [3937/17668] intraday_12669.csv.gz  in=256,640,216 out=42,899,387 elapsed=83.8s

  [3938/17668] intraday_12670.csv.gz  in=256,652,522 out=42,911,693 elapsed=83.8s

  [3939/17668] intraday_12671.csv.gz  in=256,664,717 out=42,923,888 elapsed=83.8s

  [3940/17668] intraday_12673.csv.gz  in=256,678,976 out=42,938,147 elapsed=83.8s

  [3941/17668] intraday_12672.csv.gz  in=256,690,876 out=42,950,047 elapsed=83.8s

  [3942/17668] intraday_12674.csv.gz  in=256,703,588 out=42,962,759 elapsed=83.9s

  [3943/17668] intraday_12676.csv.gz  in=256,715,884 out=42,975,055 elapsed=83.9s

  [3944/17668] intraday_12675.csv.gz  in=256,729,834 out=42,989,005 elapsed=83.9s

  [3945/17668] intraday_12677.csv.gz  in=256,744,152 out=43,003,323 elapsed=83.9s

  [3946/17668] intraday_12678.csv.gz  in=256,757,037 out=43,016,208 elapsed=83.9s

  [3947/17668] intraday_12679.csv.gz  in=256,768,460 out=43,027,631 elapsed=83.9s

  [3948/17668] intraday_1268.csv.gz  in=256,779,591 out=43,027,631 elapsed=83.9s

  [3949/17668] intraday_12680.csv.gz  in=256,793,627 out=43,041,667 elapsed=84.0s

  [3950/17668] intraday_12682.csv.gz  in=256,806,492 out=43,054,532 elapsed=84.0s

  [3951/17668] intraday_12681.csv.gz  in=256,821,252 out=43,069,292 elapsed=84.0s

  [3952/17668] intraday_12683.csv.gz  in=256,833,606 out=43,081,646 elapsed=84.0s

  [3953/17668] intraday_12684.csv.gz  in=256,848,725 out=43,096,765 elapsed=84.0s

  [3954/17668] intraday_12686.csv.gz  in=256,862,452 out=43,110,492 elapsed=84.0s

  [3955/17668] intraday_12685.csv.gz  in=256,877,607 out=43,125,647 elapsed=84.0s

  [3956/17668] intraday_12687.csv.gz  in=256,893,945 out=43,141,985 elapsed=84.0s

  [3957/17668] intraday_12689.csv.gz  in=256,906,845 out=43,154,885 elapsed=84.1s

  [3958/17668] intraday_1269.csv.gz  in=256,918,082 out=43,154,885 elapsed=84.1s

  [3959/17668] intraday_12688.csv.gz  in=256,939,211 out=43,176,014 elapsed=84.1s

  [3960/17668] intraday_12691.csv.gz  in=256,952,452 out=43,189,255 elapsed=84.1s

  [3961/17668] intraday_12690.csv.gz  in=256,968,534 out=43,205,337 elapsed=84.1s

  [3962/17668] intraday_12693.csv.gz  in=256,985,770 out=43,221,046 elapsed=84.1s

  [3963/17668] intraday_12692.csv.gz  in=256,998,221 out=43,233,497 elapsed=84.1s

  [3964/17668] intraday_12694.csv.gz  in=257,010,542 out=43,245,818 elapsed=84.1s

  [3965/17668] intraday_12695.csv.gz  in=257,022,489 out=43,257,765 elapsed=84.2s

  [3966/17668] intraday_12696.csv.gz  in=257,034,362 out=43,269,638 elapsed=84.2s

  [3967/17668] intraday_12697.csv.gz  in=257,046,913 out=43,282,189 elapsed=84.2s

  [3968/17668] intraday_12699.csv.gz  in=257,060,443 out=43,295,719 elapsed=84.2s

  [3969/17668] intraday_12698.csv.gz  in=257,074,430 out=43,309,706 elapsed=84.2s

  [3970/17668] intraday_1270.csv.gz  in=257,085,186 out=43,309,706 elapsed=84.2s

  [3971/17668] intraday_12701.csv.gz  in=257,096,433 out=43,320,953 elapsed=84.2s

  [3972/17668] intraday_12702.csv.gz  in=257,110,071 out=43,334,591 elapsed=84.3s

  [3973/17668] intraday_12700.csv.gz  in=257,122,295 out=43,346,815 elapsed=84.3s

  [3974/17668] intraday_12703.csv.gz  in=257,134,426 out=43,358,946 elapsed=84.3s

  [3975/17668] intraday_12704.csv.gz  in=257,146,273 out=43,370,793 elapsed=84.3s

  [3976/17668] intraday_12705.csv.gz  in=257,160,829 out=43,385,349 elapsed=84.3s

  [3977/17668] intraday_12706.csv.gz  in=257,177,201 out=43,401,721 elapsed=84.3s

  [3978/17668] intraday_12707.csv.gz  in=257,190,927 out=43,415,447 elapsed=84.3s

  [3979/17668] intraday_12708.csv.gz  in=257,206,698 out=43,431,218 elapsed=84.3s

  [3980/17668] intraday_12709.csv.gz  in=257,218,350 out=43,442,870 elapsed=84.3s

  [3981/17668] intraday_1271.csv.gz  in=257,241,901 out=43,442,870 elapsed=84.4s

  [3982/17668] intraday_12711.csv.gz  in=257,252,593 out=43,453,562 elapsed=84.4s

  [3983/17668] intraday_12710.csv.gz  in=257,264,947 out=43,465,916 elapsed=84.4s

  [3984/17668] intraday_12712.csv.gz  in=257,277,521 out=43,478,490 elapsed=84.4s

  [3985/17668] intraday_12714.csv.gz  in=257,283,634 out=43,484,603 elapsed=84.4s

  [3986/17668] intraday_12713.csv.gz  in=257,293,707 out=43,494,676 elapsed=84.4s

  [3987/17668] intraday_12716.csv.gz  in=257,300,474 out=43,501,443 elapsed=84.4s

  [3988/17668] intraday_12715.csv.gz  in=257,315,237 out=43,516,206 elapsed=84.4s

  [3989/17668] intraday_12717.csv.gz  in=257,331,616 out=43,532,585 elapsed=84.5s

  [3990/17668] intraday_12719.csv.gz  in=257,344,351 out=43,545,320 elapsed=84.5s

  [3991/17668] intraday_12718.csv.gz  in=257,358,261 out=43,559,230 elapsed=84.5s

  [3992/17668] intraday_1272.csv.gz  in=257,371,457 out=43,559,230 elapsed=84.5s

  [3993/17668] intraday_12720.csv.gz  in=257,381,395 out=43,569,168 elapsed=84.5s

  [3994/17668] intraday_12721.csv.gz  in=257,393,869 out=43,581,642 elapsed=84.5s

  [3995/17668] intraday_12722.csv.gz  in=257,407,190 out=43,594,963 elapsed=84.5s

  [3996/17668] intraday_12723.csv.gz  in=257,422,590 out=43,610,363 elapsed=84.5s

  [3997/17668] intraday_12724.csv.gz  in=257,433,045 out=43,620,818 elapsed=84.6s

  [3998/17668] intraday_12726.csv.gz  in=257,446,088 out=43,633,861 elapsed=84.6s

  [3999/17668] intraday_12725.csv.gz  in=257,459,982 out=43,647,755 elapsed=84.6s

  [4000/17668] intraday_12727.csv.gz  in=257,472,428 out=43,660,201 elapsed=84.6s

  [4001/17668] intraday_12728.csv.gz  in=257,484,066 out=43,671,839 elapsed=84.6s

  [4002/17668] intraday_12729.csv.gz  in=257,510,308 out=43,691,055 elapsed=84.6s

  [4003/17668] intraday_1273.csv.gz  in=257,528,383 out=43,691,055 elapsed=84.6s

  [4004/17668] intraday_12730.csv.gz  in=257,541,323 out=43,703,995 elapsed=84.6s

  [4005/17668] intraday_12731.csv.gz  in=257,551,318 out=43,713,990 elapsed=84.7s

  [4006/17668] intraday_12732.csv.gz  in=257,560,580 out=43,723,252 elapsed=84.7s

  [4007/17668] intraday_12734.csv.gz  in=257,572,815 out=43,735,487 elapsed=84.7s

  [4008/17668] intraday_12733.csv.gz  in=257,587,144 out=43,749,816 elapsed=84.7s

  [4009/17668] intraday_12736.csv.gz  in=257,598,225 out=43,760,897 elapsed=84.7s

  [4010/17668] intraday_12735.csv.gz  in=257,608,403 out=43,771,075 elapsed=84.7s

  [4011/17668] intraday_12737.csv.gz  in=257,618,764 out=43,781,436 elapsed=84.7s

  [4012/17668] intraday_12738.csv.gz  in=257,630,827 out=43,793,495 elapsed=84.7s

  [4013/17668] intraday_12739.csv.gz  in=257,643,134 out=43,805,802 elapsed=84.8s

  [4014/17668] intraday_1274.csv.gz  in=257,659,354 out=43,805,802 elapsed=84.8s

  [4015/17668] intraday_12740.csv.gz  in=257,670,784 out=43,817,232 elapsed=84.8s

  [4016/17668] intraday_12741.csv.gz  in=257,686,021 out=43,832,469 elapsed=84.8s

  [4017/17668] intraday_12742.csv.gz  in=257,697,226 out=43,843,197 elapsed=84.8s

  [4018/17668] intraday_12743.csv.gz  in=257,709,974 out=43,855,945 elapsed=84.8s

  [4019/17668] intraday_12745.csv.gz  in=257,721,655 out=43,867,626 elapsed=84.8s

  [4020/17668] intraday_12744.csv.gz  in=257,734,453 out=43,880,424 elapsed=84.8s

  [4021/17668] intraday_12746.csv.gz  in=257,748,046 out=43,894,017 elapsed=84.8s

  [4022/17668] intraday_12749.csv.gz  in=257,758,465 out=43,904,436 elapsed=84.9s

  [4023/17668] intraday_12747.csv.gz  in=257,775,662 out=43,919,988 elapsed=84.9s

  [4024/17668] intraday_1275.csv.gz  in=257,787,212 out=43,919,988 elapsed=84.9s

  [4025/17668] intraday_12748.csv.gz  in=257,800,535 out=43,933,311 elapsed=84.9s

  [4026/17668] intraday_12750.csv.gz  in=257,813,324 out=43,946,100 elapsed=84.9s

  [4027/17668] intraday_12753.csv.gz  in=257,826,025 out=43,958,801 elapsed=84.9s

  [4028/17668] intraday_12752.csv.gz  in=257,839,434 out=43,972,210 elapsed=84.9s

  [4029/17668] intraday_12751.csv.gz  in=257,852,515 out=43,985,291 elapsed=84.9s

  [4030/17668] intraday_12754.csv.gz  in=257,863,097 out=43,995,873 elapsed=84.9s

  [4031/17668] intraday_12755.csv.gz  in=257,874,439 out=44,007,215 elapsed=85.0s

  [4032/17668] intraday_12757.csv.gz  in=257,885,102 out=44,017,878 elapsed=85.0s

  [4033/17668] intraday_12756.csv.gz  in=257,895,133 out=44,027,909 elapsed=85.0s

  [4034/17668] intraday_12759.csv.gz  in=257,906,324 out=44,039,100 elapsed=85.0s

  [4035/17668] intraday_12758.csv.gz  in=257,919,724 out=44,052,500 elapsed=85.0s

  [4036/17668] intraday_1276.csv.gz  in=257,932,551 out=44,052,500 elapsed=85.0s

  [4037/17668] intraday_12760.csv.gz  in=257,944,926 out=44,064,875 elapsed=85.1s

  [4038/17668] intraday_12762.csv.gz  in=257,956,413 out=44,076,362 elapsed=85.1s

  [4039/17668] intraday_12763.csv.gz  in=257,967,632 out=44,087,581 elapsed=85.1s

  [4040/17668] intraday_12761.csv.gz  in=257,981,825 out=44,101,774 elapsed=85.1s

  [4041/17668] intraday_12764.csv.gz  in=257,993,942 out=44,112,862 elapsed=85.1s

  [4042/17668] intraday_12765.csv.gz  in=258,006,220 out=44,125,140 elapsed=85.1s

  [4043/17668] intraday_12767.csv.gz  in=258,017,898 out=44,136,818 elapsed=85.1s

  [4044/17668] intraday_12766.csv.gz  in=258,028,361 out=44,147,281 elapsed=85.2s

  [4045/17668] intraday_12768.csv.gz  in=258,039,354 out=44,158,274 elapsed=85.2s

  [4046/17668] intraday_12769.csv.gz  in=258,052,608 out=44,171,430 elapsed=85.2s

  [4047/17668] intraday_1277.csv.gz  in=258,064,537 out=44,171,430 elapsed=85.2s

  [4048/17668] intraday_12770.csv.gz  in=258,076,474 out=44,183,367 elapsed=85.2s

  [4049/17668] intraday_12771.csv.gz  in=258,088,231 out=44,195,124 elapsed=85.2s

  [4050/17668] intraday_12773.csv.gz  in=258,099,038 out=44,205,931 elapsed=85.2s

  [4051/17668] intraday_12772.csv.gz  in=258,112,774 out=44,219,667 elapsed=85.2s

  [4052/17668] intraday_12774.csv.gz  in=258,124,864 out=44,231,757 elapsed=85.2s

  [4053/17668] intraday_12776.csv.gz  in=258,136,486 out=44,243,379 elapsed=85.3s

  [4054/17668] intraday_12775.csv.gz  in=258,146,379 out=44,253,272 elapsed=85.3s

  [4055/17668] intraday_12777.csv.gz  in=258,159,841 out=44,266,734 elapsed=85.3s

  [4056/17668] intraday_12778.csv.gz  in=258,170,837 out=44,277,730 elapsed=85.3s

  [4057/17668] intraday_1278.csv.gz  in=258,183,497 out=44,277,730 elapsed=85.3s

  [4058/17668] intraday_12779.csv.gz  in=258,195,271 out=44,289,504 elapsed=85.3s

  [4059/17668] intraday_12780.csv.gz  in=258,207,129 out=44,301,362 elapsed=85.3s

  [4060/17668] intraday_12781.csv.gz  in=258,216,025 out=44,310,258 elapsed=85.3s

  [4061/17668] intraday_12782.csv.gz  in=258,229,491 out=44,323,724 elapsed=85.3s

  [4062/17668] intraday_12783.csv.gz  in=258,243,271 out=44,337,504 elapsed=85.4s

  [4063/17668] intraday_12784.csv.gz  in=258,256,496 out=44,350,729 elapsed=85.4s

  [4064/17668] intraday_12785.csv.gz  in=258,269,933 out=44,364,166 elapsed=85.4s

  [4065/17668] intraday_12786.csv.gz  in=258,285,875 out=44,378,063 elapsed=85.4s

  [4066/17668] intraday_12787.csv.gz  in=258,296,504 out=44,388,692 elapsed=85.4s

  [4067/17668] intraday_12788.csv.gz  in=258,308,339 out=44,400,527 elapsed=85.4s

  [4068/17668] intraday_1279.csv.gz  in=258,320,250 out=44,400,527 elapsed=85.4s

  [4069/17668] intraday_12789.csv.gz  in=258,332,726 out=44,413,003 elapsed=85.4s

  [4070/17668] intraday_12790.csv.gz  in=258,344,329 out=44,424,606 elapsed=85.5s

  [4071/17668] intraday_12791.csv.gz  in=258,357,843 out=44,438,120 elapsed=85.5s

  [4072/17668] intraday_12792.csv.gz  in=258,369,919 out=44,450,196 elapsed=85.5s

  [4073/17668] intraday_12793.csv.gz  in=258,386,376 out=44,463,748 elapsed=85.5s

  [4074/17668] intraday_12794.csv.gz  in=258,396,320 out=44,473,692 elapsed=85.5s

  [4075/17668] intraday_12795.csv.gz  in=258,409,744 out=44,487,116 elapsed=85.5s

  [4076/17668] intraday_12797.csv.gz  in=258,421,375 out=44,498,747 elapsed=85.5s

  [4077/17668] intraday_12798.csv.gz  in=258,432,902 out=44,510,274 elapsed=85.6s

  [4078/17668] intraday_12796.csv.gz  in=258,444,139 out=44,521,511 elapsed=85.6s

  [4079/17668] intraday_1280.csv.gz  in=258,454,940 out=44,521,511 elapsed=85.6s

  [4080/17668] intraday_12799.csv.gz  in=258,465,121 out=44,531,692 elapsed=85.6s

  [4081/17668] intraday_12800.csv.gz  in=258,478,137 out=44,544,708 elapsed=85.6s

  [4082/17668] intraday_12801.csv.gz  in=258,490,818 out=44,557,389 elapsed=85.6s

  [4083/17668] intraday_12802.csv.gz  in=258,507,274 out=44,573,845 elapsed=85.6s

  [4084/17668] intraday_12805.csv.gz  in=258,517,642 out=44,584,213 elapsed=85.7s

  [4085/17668] intraday_12804.csv.gz  in=258,529,632 out=44,596,203 elapsed=85.7s

  [4086/17668] intraday_12803.csv.gz  in=258,543,342 out=44,609,913 elapsed=85.7s

  [4087/17668] intraday_12807.csv.gz  in=258,555,933 out=44,622,504 elapsed=85.7s

  [4088/17668] intraday_12806.csv.gz  in=258,568,323 out=44,634,894 elapsed=85.7s

  [4089/17668] intraday_12809.csv.gz  in=258,580,242 out=44,645,567 elapsed=85.7s

  [4090/17668] intraday_1281.csv.gz  in=258,594,863 out=44,645,567 elapsed=85.8s

  [4091/17668] intraday_12810.csv.gz  in=258,609,071 out=44,659,775 elapsed=85.8s

  [4092/17668] intraday_12808.csv.gz  in=258,623,481 out=44,674,185 elapsed=85.8s

  [4093/17668] intraday_12811.csv.gz  in=258,637,427 out=44,688,131 elapsed=85.8s

  [4094/17668] intraday_12812.csv.gz  in=258,649,450 out=44,700,126 elapsed=85.8s

  [4095/17668] intraday_12814.csv.gz  in=258,661,966 out=44,712,642 elapsed=85.8s

  [4096/17668] intraday_12815.csv.gz  in=258,675,356 out=44,726,032 elapsed=85.8s

  [4097/17668] intraday_12813.csv.gz  in=258,702,662 out=44,744,020 elapsed=85.8s

  [4098/17668] intraday_12816.csv.gz  in=258,711,938 out=44,753,296 elapsed=85.8s

  [4099/17668] intraday_12818.csv.gz  in=258,722,968 out=44,764,326 elapsed=85.9s

  [4100/17668] intraday_12819.csv.gz  in=258,735,375 out=44,776,733 elapsed=85.9s

  [4101/17668] intraday_1282.csv.gz  in=258,746,754 out=44,776,733 elapsed=85.9s

  [4102/17668] intraday_12817.csv.gz  in=258,759,078 out=44,789,057 elapsed=85.9s

  [4103/17668] intraday_12820.csv.gz  in=258,773,222 out=44,803,201 elapsed=85.9s

  [4104/17668] intraday_12821.csv.gz  in=258,785,056 out=44,815,035 elapsed=85.9s

  [4105/17668] intraday_12823.csv.gz  in=258,797,665 out=44,827,644 elapsed=86.0s

  [4106/17668] intraday_12822.csv.gz  in=258,812,249 out=44,842,228 elapsed=86.0s

  [4107/17668] intraday_12824.csv.gz  in=258,828,385 out=44,857,266 elapsed=86.0s

  [4108/17668] intraday_12825.csv.gz  in=258,840,530 out=44,869,411 elapsed=86.0s

  [4109/17668] intraday_12826.csv.gz  in=258,852,525 out=44,881,406 elapsed=86.0s

  [4110/17668] intraday_12828.csv.gz  in=258,866,730 out=44,895,611 elapsed=86.0s

  [4111/17668] intraday_12827.csv.gz  in=258,879,620 out=44,908,501 elapsed=86.0s

  [4112/17668] intraday_12829.csv.gz  in=258,891,741 out=44,920,622 elapsed=86.1s

  [4113/17668] intraday_1283.csv.gz  in=258,903,612 out=44,920,622 elapsed=86.1s

  [4114/17668] intraday_12830.csv.gz  in=258,916,397 out=44,933,407 elapsed=86.1s

  [4115/17668] intraday_12831.csv.gz  in=258,930,479 out=44,947,489 elapsed=86.1s

  [4116/17668] intraday_12833.csv.gz  in=258,942,330 out=44,959,340 elapsed=86.1s

  [4117/17668] intraday_12832.csv.gz  in=258,956,403 out=44,973,413 elapsed=86.1s

  [4118/17668] intraday_12834.csv.gz  in=258,971,670 out=44,988,680 elapsed=86.1s

  [4119/17668] intraday_12835.csv.gz  in=258,991,089 out=45,008,099 elapsed=86.1s

  [4120/17668] intraday_12836.csv.gz  in=259,004,012 out=45,021,022 elapsed=86.1s

  [4121/17668] intraday_12838.csv.gz  in=259,016,290 out=45,033,300 elapsed=86.1s

  [4122/17668] intraday_12837.csv.gz  in=259,031,411 out=45,048,421 elapsed=86.2s

  [4123/17668] intraday_1284.csv.gz  in=259,043,285 out=45,048,421 elapsed=86.2s

  [4124/17668] intraday_12839.csv.gz  in=259,055,675 out=45,060,811 elapsed=86.2s

  [4125/17668] intraday_12840.csv.gz  in=259,068,620 out=45,073,756 elapsed=86.2s

  [4126/17668] intraday_12841.csv.gz  in=259,081,313 out=45,086,449 elapsed=86.2s

  [4127/17668] intraday_12843.csv.gz  in=259,093,863 out=45,097,966 elapsed=86.2s

  [4128/17668] intraday_12842.csv.gz  in=259,104,371 out=45,108,474 elapsed=86.2s

  [4129/17668] intraday_12844.csv.gz  in=259,116,572 out=45,120,675 elapsed=86.2s

  [4130/17668] intraday_12845.csv.gz  in=259,130,058 out=45,134,161 elapsed=86.3s

  [4131/17668] intraday_12847.csv.gz  in=259,141,102 out=45,145,205 elapsed=86.3s

  [4132/17668] intraday_12846.csv.gz  in=259,154,219 out=45,157,632 elapsed=86.3s

  [4133/17668] intraday_12848.csv.gz  in=259,165,084 out=45,168,497 elapsed=86.3s

  [4134/17668] intraday_1285.csv.gz  in=259,178,238 out=45,168,497 elapsed=86.3s

  [4135/17668] intraday_12849.csv.gz  in=259,190,658 out=45,180,917 elapsed=86.3s

  [4136/17668] intraday_12850.csv.gz  in=259,201,123 out=45,191,382 elapsed=86.3s

  [4137/17668] intraday_12851.csv.gz  in=259,214,030 out=45,204,289 elapsed=86.3s

  [4138/17668] intraday_12852.csv.gz  in=259,228,361 out=45,218,620 elapsed=86.3s

  [4139/17668] intraday_12853.csv.gz  in=259,243,583 out=45,233,842 elapsed=86.4s

  [4140/17668] intraday_12854.csv.gz  in=259,256,746 out=45,247,005 elapsed=86.4s

  [4141/17668] intraday_12855.csv.gz  in=259,269,888 out=45,260,147 elapsed=86.4s

  [4142/17668] intraday_12856.csv.gz  in=259,282,057 out=45,272,316 elapsed=86.4s

  [4143/17668] intraday_12857.csv.gz  in=259,296,700 out=45,285,141 elapsed=86.4s

  [4144/17668] intraday_12858.csv.gz  in=259,308,425 out=45,296,866 elapsed=86.4s

  [4145/17668] intraday_12860.csv.gz  in=259,317,866 out=45,306,307 elapsed=86.5s

  [4146/17668] intraday_12861.csv.gz  in=259,325,032 out=45,313,473 elapsed=86.5s

  [4147/17668] intraday_1286.csv.gz  in=259,357,846 out=45,313,473 elapsed=86.5s

  [4148/17668] intraday_12859.csv.gz  in=259,371,189 out=45,326,816 elapsed=86.5s

  [4149/17668] intraday_12862.csv.gz  in=259,385,015 out=45,340,642 elapsed=86.5s

  [4150/17668] intraday_12863.csv.gz  in=259,391,221 out=45,346,848 elapsed=86.5s

  [4151/17668] intraday_12864.csv.gz  in=259,406,739 out=45,362,366 elapsed=86.5s

  [4152/17668] intraday_12865.csv.gz  in=259,419,387 out=45,375,014 elapsed=86.5s

  [4153/17668] intraday_12866.csv.gz  in=259,431,351 out=45,386,978 elapsed=86.5s

  [4154/17668] intraday_12867.csv.gz  in=259,442,388 out=45,398,015 elapsed=86.6s

  [4155/17668] intraday_12868.csv.gz  in=259,453,896 out=45,409,523 elapsed=86.6s

  [4156/17668] intraday_12869.csv.gz  in=259,467,152 out=45,422,779 elapsed=86.6s

  [4157/17668] intraday_1287.csv.gz  in=259,488,026 out=45,422,779 elapsed=86.6s

  [4158/17668] intraday_12871.csv.gz  in=259,498,596 out=45,433,349 elapsed=86.6s

  [4159/17668] intraday_12870.csv.gz  in=259,511,346 out=45,446,099 elapsed=86.6s

  [4160/17668] intraday_12872.csv.gz  in=259,524,719 out=45,459,472 elapsed=86.6s

  [4161/17668] intraday_12873.csv.gz  in=259,538,498 out=45,473,251 elapsed=86.7s

  [4162/17668] intraday_12875.csv.gz  in=259,550,407 out=45,485,160 elapsed=86.7s

  [4163/17668] intraday_12874.csv.gz  in=259,561,968 out=45,496,721 elapsed=86.7s

  [4164/17668] intraday_12877.csv.gz  in=259,575,200 out=45,509,953 elapsed=86.7s

  [4165/17668] intraday_12879.csv.gz  in=259,585,266 out=45,520,019 elapsed=86.7s

  [4166/17668] intraday_12878.csv.gz  in=259,594,418 out=45,529,171 elapsed=86.7s

  [4167/17668] intraday_12876.csv.gz  in=259,630,114 out=45,552,268 elapsed=86.7s

  [4168/17668] intraday_1288.csv.gz  in=259,643,396 out=45,552,268 elapsed=86.7s

  [4169/17668] intraday_12881.csv.gz  in=259,656,650 out=45,565,522 elapsed=86.8s

  [4170/17668] intraday_12880.csv.gz  in=259,669,870 out=45,578,742 elapsed=86.8s

  [4171/17668] intraday_12882.csv.gz  in=259,679,585 out=45,588,457 elapsed=86.8s

  [4172/17668] intraday_12884.csv.gz  in=259,690,622 out=45,599,494 elapsed=86.8s

  [4173/17668] intraday_12883.csv.gz  in=259,701,365 out=45,610,237 elapsed=86.8s

  [4174/17668] intraday_12885.csv.gz  in=259,713,372 out=45,622,244 elapsed=86.8s

  [4175/17668] intraday_12886.csv.gz  in=259,725,200 out=45,634,072 elapsed=86.8s

  [4176/17668] intraday_12887.csv.gz  in=259,736,750 out=45,645,622 elapsed=86.8s

  [4177/17668] intraday_12888.csv.gz  in=259,750,522 out=45,659,394 elapsed=86.8s

  [4178/17668] intraday_12889.csv.gz  in=259,769,128 out=45,673,501 elapsed=86.9s

  [4179/17668] intraday_1289.csv.gz  in=259,783,445 out=45,673,501 elapsed=86.9s

  [4180/17668] intraday_12890.csv.gz  in=259,796,089 out=45,686,145 elapsed=86.9s

  [4181/17668] intraday_12891.csv.gz  in=259,808,568 out=45,698,624 elapsed=86.9s

  [4182/17668] intraday_12892.csv.gz  in=259,818,027 out=45,708,083 elapsed=86.9s

  [4183/17668] intraday_12893.csv.gz  in=259,832,044 out=45,722,100 elapsed=86.9s

  [4184/17668] intraday_12894.csv.gz  in=259,846,077 out=45,736,133 elapsed=86.9s

  [4185/17668] intraday_12895.csv.gz  in=259,859,072 out=45,749,128 elapsed=86.9s

  [4186/17668] intraday_12896.csv.gz  in=259,868,895 out=45,758,951 elapsed=87.0s

  [4187/17668] intraday_12898.csv.gz  in=259,880,546 out=45,770,602 elapsed=87.0s

  [4188/17668] intraday_12899.csv.gz  in=259,893,477 out=45,783,533 elapsed=87.0s

  [4189/17668] intraday_12897.csv.gz  in=259,906,218 out=45,796,274 elapsed=87.0s

  [4190/17668] intraday_1290.csv.gz  in=259,920,160 out=45,796,274 elapsed=87.0s

  [4191/17668] intraday_12900.csv.gz  in=259,932,415 out=45,808,529 elapsed=87.0s

  [4192/17668] intraday_12901.csv.gz  in=259,943,786 out=45,819,900 elapsed=87.0s

  [4193/17668] intraday_12902.csv.gz  in=259,954,516 out=45,830,630 elapsed=87.1s

  [4194/17668] intraday_12903.csv.gz  in=259,964,186 out=45,840,300 elapsed=87.1s

  [4195/17668] intraday_12904.csv.gz  in=259,974,565 out=45,850,679 elapsed=87.1s

  [4196/17668] intraday_12905.csv.gz  in=259,986,952 out=45,863,066 elapsed=87.1s

  [4197/17668] intraday_12906.csv.gz  in=259,998,664 out=45,874,778 elapsed=87.1s

  [4198/17668] intraday_12907.csv.gz  in=260,011,024 out=45,887,138 elapsed=87.1s

  [4199/17668] intraday_12909.csv.gz  in=260,021,658 out=45,897,772 elapsed=87.1s

  [4200/17668] intraday_12908.csv.gz  in=260,035,234 out=45,911,348 elapsed=87.1s

  [4201/17668] intraday_1291.csv.gz  in=260,054,730 out=45,911,348 elapsed=87.1s

  [4202/17668] intraday_12910.csv.gz  in=260,066,281 out=45,922,899 elapsed=87.1s

  [4203/17668] intraday_12911.csv.gz  in=260,077,040 out=45,933,658 elapsed=87.2s

  [4204/17668] intraday_12912.csv.gz  in=260,089,446 out=45,946,064 elapsed=87.2s

  [4205/17668] intraday_12913.csv.gz  in=260,099,764 out=45,956,382 elapsed=87.2s

  [4206/17668] intraday_12914.csv.gz  in=260,111,486 out=45,968,104 elapsed=87.2s

  [4207/17668] intraday_12915.csv.gz  in=260,121,868 out=45,978,486 elapsed=87.2s

  [4208/17668] intraday_12916.csv.gz  in=260,135,294 out=45,991,912 elapsed=87.2s

  [4209/17668] intraday_12917.csv.gz  in=260,146,539 out=46,002,877 elapsed=87.2s

  [4210/17668] intraday_12919.csv.gz  in=260,159,268 out=46,015,606 elapsed=87.2s

  [4211/17668] intraday_1292.csv.gz  in=260,169,259 out=46,015,606 elapsed=87.3s

  [4212/17668] intraday_12918.csv.gz  in=260,181,686 out=46,028,033 elapsed=87.3s

  [4213/17668] intraday_12920.csv.gz  in=260,192,288 out=46,038,635 elapsed=87.3s

  [4214/17668] intraday_12921.csv.gz  in=260,203,011 out=46,049,358 elapsed=87.3s

  [4215/17668] intraday_12922.csv.gz  in=260,213,791 out=46,060,138 elapsed=87.3s

  [4216/17668] intraday_12923.csv.gz  in=260,225,556 out=46,071,903 elapsed=87.3s

  [4217/17668] intraday_12924.csv.gz  in=260,237,122 out=46,083,469 elapsed=87.3s

  [4218/17668] intraday_12925.csv.gz  in=260,248,970 out=46,095,317 elapsed=87.3s

  [4219/17668] intraday_12927.csv.gz  in=260,260,874 out=46,107,221 elapsed=87.3s

  [4220/17668] intraday_12926.csv.gz  in=260,272,294 out=46,118,641 elapsed=87.4s

  [4221/17668] intraday_12928.csv.gz  in=260,281,230 out=46,127,577 elapsed=87.4s

  [4222/17668] intraday_12929.csv.gz  in=260,293,842 out=46,140,189 elapsed=87.4s

  [4223/17668] intraday_1293.csv.gz  in=260,305,936 out=46,140,189 elapsed=87.4s

  [4224/17668] intraday_12930.csv.gz  in=260,319,540 out=46,153,793 elapsed=87.4s

  [4225/17668] intraday_12931.csv.gz  in=260,331,335 out=46,165,588 elapsed=87.4s

  [4226/17668] intraday_12932.csv.gz  in=260,344,310 out=46,178,563 elapsed=87.4s

  [4227/17668] intraday_12933.csv.gz  in=260,355,849 out=46,190,102 elapsed=87.5s

  [4228/17668] intraday_12935.csv.gz  in=260,367,821 out=46,202,074 elapsed=87.5s

  [4229/17668] intraday_12936.csv.gz  in=260,379,845 out=46,214,098 elapsed=87.5s

  [4230/17668] intraday_12937.csv.gz  in=260,391,756 out=46,226,009 elapsed=87.5s

  [4231/17668] intraday_12934.csv.gz  in=260,400,977 out=46,235,230 elapsed=87.5s

  [4232/17668] intraday_12938.csv.gz  in=260,413,306 out=46,247,559 elapsed=87.5s

  [4233/17668] intraday_12939.csv.gz  in=260,425,283 out=46,259,536 elapsed=87.5s

  [4234/17668] intraday_12940.csv.gz  in=260,434,613 out=46,268,866 elapsed=87.5s

  [4235/17668] intraday_1294.csv.gz  in=260,447,053 out=46,268,866 elapsed=87.5s

  [4236/17668] intraday_12941.csv.gz  in=260,458,303 out=46,280,116 elapsed=87.5s

  [4237/17668] intraday_12942.csv.gz  in=260,472,760 out=46,294,573 elapsed=87.6s

  [4238/17668] intraday_12945.csv.gz  in=260,482,526 out=46,304,339 elapsed=87.6s

  [4239/17668] intraday_12944.csv.gz  in=260,493,797 out=46,315,610 elapsed=87.6s

  [4240/17668] intraday_12943.csv.gz  in=260,505,703 out=46,327,516 elapsed=87.6s

  [4241/17668] intraday_12946.csv.gz  in=260,516,376 out=46,338,189 elapsed=87.7s

  [4242/17668] intraday_12949.csv.gz  in=260,530,994 out=46,352,807 elapsed=87.7s

  [4243/17668] intraday_12947.csv.gz  in=260,543,145 out=46,364,958 elapsed=87.7s

  [4244/17668] intraday_1295.csv.gz  in=260,555,602 out=46,364,958 elapsed=87.7s

  [4245/17668] intraday_12948.csv.gz  in=260,568,480 out=46,377,836 elapsed=87.7s

  [4246/17668] intraday_12950.csv.gz  in=260,583,013 out=46,392,369 elapsed=87.7s

  [4247/17668] intraday_12951.csv.gz  in=260,594,657 out=46,404,013 elapsed=87.8s

  [4248/17668] intraday_12953.csv.gz  in=260,605,700 out=46,415,056 elapsed=87.8s

  [4249/17668] intraday_12952.csv.gz  in=260,617,172 out=46,426,528 elapsed=87.8s

  [4250/17668] intraday_12954.csv.gz  in=260,631,088 out=46,440,444 elapsed=87.8s

  [4251/17668] intraday_12955.csv.gz  in=260,643,019 out=46,452,375 elapsed=87.8s

  [4252/17668] intraday_12956.csv.gz  in=260,653,424 out=46,462,780 elapsed=87.8s

  [4253/17668] intraday_12957.csv.gz  in=260,669,165 out=46,478,521 elapsed=87.8s

  [4254/17668] intraday_12959.csv.gz  in=260,681,327 out=46,490,683 elapsed=87.8s

  [4255/17668] intraday_12958.csv.gz  in=260,692,390 out=46,501,746 elapsed=87.8s

  [4256/17668] intraday_1296.csv.gz  in=260,709,228 out=46,501,746 elapsed=87.8s

  [4257/17668] intraday_12960.csv.gz  in=260,721,439 out=46,513,957 elapsed=87.8s

  [4258/17668] intraday_12962.csv.gz  in=260,733,258 out=46,525,776 elapsed=87.9s

  [4259/17668] intraday_12961.csv.gz  in=260,745,110 out=46,537,628 elapsed=87.9s

  [4260/17668] intraday_12963.csv.gz  in=260,756,922 out=46,549,440 elapsed=87.9s

  [4261/17668] intraday_12964.csv.gz  in=260,767,234 out=46,559,752 elapsed=87.9s

  [4262/17668] intraday_12965.csv.gz  in=260,778,194 out=46,570,712 elapsed=87.9s

  [4263/17668] intraday_12966.csv.gz  in=260,790,812 out=46,583,330 elapsed=87.9s

  [4264/17668] intraday_12967.csv.gz  in=260,802,642 out=46,595,160 elapsed=87.9s

  [4265/17668] intraday_12968.csv.gz  in=260,813,730 out=46,606,248 elapsed=87.9s

  [4266/17668] intraday_1297.csv.gz  in=260,834,585 out=46,606,248 elapsed=88.0s

  [4267/17668] intraday_12970.csv.gz  in=260,846,229 out=46,617,892 elapsed=88.0s

  [4268/17668] intraday_12969.csv.gz  in=260,860,158 out=46,631,821 elapsed=88.0s

  [4269/17668] intraday_12971.csv.gz  in=260,875,435 out=46,647,098 elapsed=88.0s

  [4270/17668] intraday_12972.csv.gz  in=260,885,759 out=46,657,422 elapsed=88.0s

  [4271/17668] intraday_12974.csv.gz  in=260,899,861 out=46,671,524 elapsed=88.0s

  [4272/17668] intraday_12973.csv.gz  in=260,916,571 out=46,685,302 elapsed=88.0s

  [4273/17668] intraday_12975.csv.gz  in=260,930,822 out=46,699,553 elapsed=88.1s

  [4274/17668] intraday_12976.csv.gz  in=260,941,344 out=46,710,075 elapsed=88.1s

  [4275/17668] intraday_12977.csv.gz  in=260,954,017 out=46,722,748 elapsed=88.1s

  [4276/17668] intraday_12978.csv.gz  in=260,967,994 out=46,736,725 elapsed=88.1s

  [4277/17668] intraday_12979.csv.gz  in=260,982,068 out=46,750,799 elapsed=88.1s

  [4278/17668] intraday_1298.csv.gz  in=261,000,957 out=46,750,799 elapsed=88.1s

  [4279/17668] intraday_12980.csv.gz  in=261,013,580 out=46,763,422 elapsed=88.1s

  [4280/17668] intraday_12981.csv.gz  in=261,027,760 out=46,777,602 elapsed=88.1s

  [4281/17668] intraday_12983.csv.gz  in=261,039,687 out=46,789,529 elapsed=88.1s

  [4282/17668] intraday_12982.csv.gz  in=261,058,048 out=46,807,890 elapsed=88.2s

  [4283/17668] intraday_12984.csv.gz  in=261,073,462 out=46,823,304 elapsed=88.2s

  [4284/17668] intraday_12985.csv.gz  in=261,083,343 out=46,833,185 elapsed=88.2s

  [4285/17668] intraday_12987.csv.gz  in=261,095,373 out=46,845,215 elapsed=88.2s

  [4286/17668] intraday_12988.csv.gz  in=261,107,880 out=46,857,722 elapsed=88.2s

  [4287/17668] intraday_12989.csv.gz  in=261,118,675 out=46,868,517 elapsed=88.2s

  [4288/17668] intraday_12986.csv.gz  in=261,132,229 out=46,882,071 elapsed=88.2s

  [4289/17668] intraday_1299.csv.gz  in=261,146,837 out=46,882,071 elapsed=88.2s

  [4290/17668] intraday_12990.csv.gz  in=261,158,490 out=46,893,724 elapsed=88.3s

  [4291/17668] intraday_12991.csv.gz  in=261,170,068 out=46,905,302 elapsed=88.3s

  [4292/17668] intraday_12993.csv.gz  in=261,181,753 out=46,916,987 elapsed=88.3s

  [4293/17668] intraday_12994.csv.gz  in=261,194,124 out=46,929,358 elapsed=88.3s

  [4294/17668] intraday_12992.csv.gz  in=261,207,182 out=46,942,416 elapsed=88.3s

  [4295/17668] intraday_12995.csv.gz  in=261,217,194 out=46,952,428 elapsed=88.3s

  [4296/17668] intraday_12996.csv.gz  in=261,230,745 out=46,965,979 elapsed=88.3s

  [4297/17668] intraday_12997.csv.gz  in=261,240,907 out=46,976,141 elapsed=88.4s

  [4298/17668] intraday_12998.csv.gz  in=261,254,060 out=46,989,294 elapsed=88.4s

  [4299/17668] intraday_12999.csv.gz  in=261,267,899 out=47,003,133 elapsed=88.4s

  [4300/17668] intraday_1300.csv.gz  in=261,280,408 out=47,003,133 elapsed=88.4s

  [4301/17668] intraday_13000.csv.gz  in=261,294,911 out=47,017,636 elapsed=88.4s

  [4302/17668] intraday_13001.csv.gz  in=261,308,454 out=47,031,179 elapsed=88.4s

  [4303/17668] intraday_13003.csv.gz  in=261,319,807 out=47,042,532 elapsed=88.4s

  [4304/17668] intraday_13002.csv.gz  in=261,333,142 out=47,055,867 elapsed=88.4s

  [4305/17668] intraday_13004.csv.gz  in=261,345,560 out=47,068,285 elapsed=88.4s

  [4306/17668] intraday_13005.csv.gz  in=261,356,562 out=47,079,287 elapsed=88.4s

  [4307/17668] intraday_13006.csv.gz  in=261,369,897 out=47,092,622 elapsed=88.5s

  [4308/17668] intraday_13007.csv.gz  in=261,378,627 out=47,101,352 elapsed=88.5s

  [4309/17668] intraday_13008.csv.gz  in=261,386,264 out=47,108,989 elapsed=88.5s

  [4310/17668] intraday_13009.csv.gz  in=261,400,013 out=47,122,738 elapsed=88.5s

  [4311/17668] intraday_13010.csv.gz  in=261,403,887 out=47,126,612 elapsed=88.5s

  [4312/17668] intraday_1301.csv.gz  in=261,416,387 out=47,126,612 elapsed=88.5s

  [4313/17668] intraday_13011.csv.gz  in=261,417,107 out=47,126,612 elapsed=88.5s

  [4314/17668] intraday_13015.csv.gz  in=261,427,624 out=47,137,129 elapsed=88.5s

  [4315/17668] intraday_13013.csv.gz  in=261,440,657 out=47,150,162 elapsed=88.5s

  [4316/17668] intraday_13014.csv.gz  in=261,453,386 out=47,162,891 elapsed=88.5s

  [4317/17668] intraday_13012.csv.gz  in=261,470,746 out=47,180,251 elapsed=88.6s

  [4318/17668] intraday_13017.csv.gz  in=261,485,320 out=47,194,825 elapsed=88.6s

  [4319/17668] intraday_13016.csv.gz  in=261,498,074 out=47,207,579 elapsed=88.6s

  [4320/17668] intraday_13018.csv.gz  in=261,510,897 out=47,220,402 elapsed=88.6s

  [4321/17668] intraday_13019.csv.gz  in=261,522,950 out=47,232,455 elapsed=88.6s

  [4322/17668] intraday_1302.csv.gz  in=261,536,197 out=47,232,455 elapsed=88.6s

  [4323/17668] intraday_13020.csv.gz  in=261,550,136 out=47,246,394 elapsed=88.6s

  [4324/17668] intraday_13021.csv.gz  in=261,562,768 out=47,259,026 elapsed=88.7s

  [4325/17668] intraday_13023.csv.gz  in=261,575,017 out=47,271,275 elapsed=88.7s

  [4326/17668] intraday_13022.csv.gz  in=261,588,152 out=47,284,410 elapsed=88.7s

  [4327/17668] intraday_13024.csv.gz  in=261,602,772 out=47,299,030 elapsed=88.7s

  [4328/17668] intraday_13025.csv.gz  in=261,615,995 out=47,312,253 elapsed=88.7s

  [4329/17668] intraday_13026.csv.gz  in=261,625,781 out=47,322,039 elapsed=88.7s

  [4330/17668] intraday_13028.csv.gz  in=261,639,604 out=47,335,862 elapsed=88.7s

  [4331/17668] intraday_13027.csv.gz  in=261,649,646 out=47,345,904 elapsed=88.7s

  [4332/17668] intraday_13029.csv.gz  in=261,663,469 out=47,359,727 elapsed=88.7s

  [4333/17668] intraday_1303.csv.gz  in=261,676,137 out=47,359,727 elapsed=88.7s

  [4334/17668] intraday_13030.csv.gz  in=261,686,113 out=47,369,703 elapsed=88.8s

  [4335/17668] intraday_13031.csv.gz  in=261,696,615 out=47,380,205 elapsed=88.8s

  [4336/17668] intraday_13032.csv.gz  in=261,708,570 out=47,392,160 elapsed=88.8s

  [4337/17668] intraday_13033.csv.gz  in=261,720,496 out=47,404,086 elapsed=88.8s

  [4338/17668] intraday_13035.csv.gz  in=261,733,069 out=47,416,659 elapsed=88.8s

  [4339/17668] intraday_13034.csv.gz  in=261,745,952 out=47,429,542 elapsed=88.8s

  [4340/17668] intraday_13036.csv.gz  in=261,760,540 out=47,444,130 elapsed=88.8s

  [4341/17668] intraday_13037.csv.gz  in=261,772,036 out=47,455,242 elapsed=88.9s

  [4342/17668] intraday_13038.csv.gz  in=261,784,270 out=47,467,476 elapsed=88.9s

  [4343/17668] intraday_1304.csv.gz  in=261,795,444 out=47,467,476 elapsed=88.9s

  [4344/17668] intraday_13039.csv.gz  in=261,808,095 out=47,480,127 elapsed=88.9s

  [4345/17668] intraday_13041.csv.gz  in=261,820,761 out=47,492,793 elapsed=88.9s

  [4346/17668] intraday_13042.csv.gz  in=261,837,542 out=47,509,574 elapsed=88.9s

  [4347/17668] intraday_13040.csv.gz  in=261,849,024 out=47,521,056 elapsed=88.9s

  [4348/17668] intraday_13043.csv.gz  in=261,862,764 out=47,534,796 elapsed=88.9s

  [4349/17668] intraday_13044.csv.gz  in=261,873,298 out=47,545,330 elapsed=89.0s

  [4350/17668] intraday_13045.csv.gz  in=261,885,010 out=47,557,042 elapsed=89.0s

  [4351/17668] intraday_13046.csv.gz  in=261,897,522 out=47,569,554 elapsed=89.0s

  [4352/17668] intraday_13048.csv.gz  in=261,909,985 out=47,582,017 elapsed=89.0s

  [4353/17668] intraday_13049.csv.gz  in=261,921,364 out=47,593,396 elapsed=89.0s

  [4354/17668] intraday_1305.csv.gz  in=261,933,138 out=47,593,396 elapsed=89.0s

  [4355/17668] intraday_13047.csv.gz  in=261,946,629 out=47,606,887 elapsed=89.0s

  [4356/17668] intraday_13050.csv.gz  in=261,958,234 out=47,618,492 elapsed=89.0s

  [4357/17668] intraday_13051.csv.gz  in=261,967,429 out=47,627,687 elapsed=89.0s

  [4358/17668] intraday_13052.csv.gz  in=261,978,392 out=47,638,650 elapsed=89.1s

  [4359/17668] intraday_13053.csv.gz  in=261,991,258 out=47,651,516 elapsed=89.1s

  [4360/17668] intraday_13054.csv.gz  in=262,004,637 out=47,664,895 elapsed=89.1s

  [4361/17668] intraday_13057.csv.gz  in=262,015,006 out=47,675,264 elapsed=89.1s

  [4362/17668] intraday_13056.csv.gz  in=262,029,424 out=47,689,682 elapsed=89.1s

  [4363/17668] intraday_13055.csv.gz  in=262,041,643 out=47,701,901 elapsed=89.1s

  [4364/17668] intraday_13058.csv.gz  in=262,053,723 out=47,713,981 elapsed=89.1s

  [4365/17668] intraday_1306.csv.gz  in=262,065,582 out=47,713,981 elapsed=89.1s

  [4366/17668] intraday_13059.csv.gz  in=262,078,384 out=47,726,783 elapsed=89.1s

  [4367/17668] intraday_13060.csv.gz  in=262,088,724 out=47,737,123 elapsed=89.2s

  [4368/17668] intraday_13061.csv.gz  in=262,100,563 out=47,748,962 elapsed=89.2s

  [4369/17668] intraday_13062.csv.gz  in=262,111,136 out=47,759,535 elapsed=89.2s

  [4370/17668] intraday_13063.csv.gz  in=262,123,383 out=47,771,782 elapsed=89.2s

  [4371/17668] intraday_13064.csv.gz  in=262,137,844 out=47,786,243 elapsed=89.2s

  [4372/17668] intraday_13066.csv.gz  in=262,151,131 out=47,799,530 elapsed=89.2s

  [4373/17668] intraday_13068.csv.gz  in=262,163,286 out=47,811,685 elapsed=89.2s

  [4374/17668] intraday_13067.csv.gz  in=262,175,414 out=47,823,813 elapsed=89.2s

  [4375/17668] intraday_13065.csv.gz  in=262,187,111 out=47,835,510 elapsed=89.2s

  [4376/17668] intraday_13069.csv.gz  in=262,199,258 out=47,847,657 elapsed=89.2s

  [4377/17668] intraday_1307.csv.gz  in=262,211,373 out=47,847,657 elapsed=89.3s

  [4378/17668] intraday_13071.csv.gz  in=262,223,010 out=47,859,294 elapsed=89.3s

  [4379/17668] intraday_13070.csv.gz  in=262,235,613 out=47,871,897 elapsed=89.3s

  [4380/17668] intraday_13073.csv.gz  in=262,249,366 out=47,885,650 elapsed=89.3s

  [4381/17668] intraday_13072.csv.gz  in=262,264,107 out=47,900,391 elapsed=89.3s

  [4382/17668] intraday_13074.csv.gz  in=262,281,465 out=47,914,509 elapsed=89.3s

  [4383/17668] intraday_13075.csv.gz  in=262,292,452 out=47,925,496 elapsed=89.3s

  [4384/17668] intraday_13076.csv.gz  in=262,304,074 out=47,937,118 elapsed=89.4s

  [4385/17668] intraday_13077.csv.gz  in=262,320,241 out=47,953,285 elapsed=89.4s

  [4386/17668] intraday_13079.csv.gz  in=262,334,074 out=47,967,118 elapsed=89.4s

  [4387/17668] intraday_13078.csv.gz  in=262,346,109 out=47,979,153 elapsed=89.4s

  [4388/17668] intraday_1308.csv.gz  in=262,357,994 out=47,979,153 elapsed=89.4s

  [4389/17668] intraday_13081.csv.gz  in=262,369,143 out=47,990,302 elapsed=89.4s

  [4390/17668] intraday_13080.csv.gz  in=262,381,624 out=48,002,783 elapsed=89.4s

  [4391/17668] intraday_13082.csv.gz  in=262,391,038 out=48,012,197 elapsed=89.4s

  [4392/17668] intraday_13083.csv.gz  in=262,404,125 out=48,025,284 elapsed=89.4s

  [4393/17668] intraday_13084.csv.gz  in=262,417,650 out=48,038,809 elapsed=89.5s

  [4394/17668] intraday_13086.csv.gz  in=262,428,428 out=48,049,587 elapsed=89.5s

  [4395/17668] intraday_13085.csv.gz  in=262,441,825 out=48,062,984 elapsed=89.5s

  [4396/17668] intraday_13087.csv.gz  in=262,454,807 out=48,075,966 elapsed=89.5s

  [4397/17668] intraday_13088.csv.gz  in=262,464,713 out=48,085,872 elapsed=89.5s

  [4398/17668] intraday_1309.csv.gz  in=262,475,445 out=48,085,872 elapsed=89.5s

  [4399/17668] intraday_13090.csv.gz  in=262,488,163 out=48,098,590 elapsed=89.5s

  [4400/17668] intraday_13089.csv.gz  in=262,503,733 out=48,114,160 elapsed=89.5s

  [4401/17668] intraday_13091.csv.gz  in=262,514,634 out=48,125,061 elapsed=89.6s

  [4402/17668] intraday_13092.csv.gz  in=262,526,172 out=48,136,599 elapsed=89.6s

  [4403/17668] intraday_13093.csv.gz  in=262,537,161 out=48,147,588 elapsed=89.6s

  [4404/17668] intraday_13094.csv.gz  in=262,549,173 out=48,159,600 elapsed=89.6s

  [4405/17668] intraday_13095.csv.gz  in=262,561,064 out=48,171,491 elapsed=89.6s

  [4406/17668] intraday_13096.csv.gz  in=262,579,590 out=48,190,017 elapsed=89.6s

  [4407/17668] intraday_13097.csv.gz  in=262,595,150 out=48,205,577 elapsed=89.6s

  [4408/17668] intraday_13099.csv.gz  in=262,606,247 out=48,216,674 elapsed=89.7s

  [4409/17668] intraday_13098.csv.gz  in=262,617,714 out=48,228,141 elapsed=89.7s

  [4410/17668] intraday_1310.csv.gz  in=262,629,361 out=48,228,141 elapsed=89.7s

  [4411/17668] intraday_13100.csv.gz  in=262,642,507 out=48,241,287 elapsed=89.7s

  [4412/17668] intraday_13103.csv.gz  in=262,653,355 out=48,252,135 elapsed=89.7s

  [4413/17668] intraday_13101.csv.gz  in=262,664,746 out=48,263,526 elapsed=89.7s

  [4414/17668] intraday_13102.csv.gz  in=262,680,304 out=48,279,084 elapsed=89.7s

  [4415/17668] intraday_13104.csv.gz  in=262,693,759 out=48,292,539 elapsed=89.7s

  [4416/17668] intraday_13105.csv.gz  in=262,707,210 out=48,305,990 elapsed=89.7s

  [4417/17668] intraday_13106.csv.gz  in=262,720,438 out=48,319,218 elapsed=89.7s

  [4418/17668] intraday_13107.csv.gz  in=262,732,869 out=48,331,649 elapsed=89.8s

  [4419/17668] intraday_13108.csv.gz  in=262,745,201 out=48,343,981 elapsed=89.8s

  [4420/17668] intraday_13109.csv.gz  in=262,758,063 out=48,356,843 elapsed=89.8s

  [4421/17668] intraday_1311.csv.gz  in=262,769,513 out=48,356,843 elapsed=89.8s

  [4422/17668] intraday_13110.csv.gz  in=262,781,766 out=48,369,096 elapsed=89.8s

  [4423/17668] intraday_13112.csv.gz  in=262,794,689 out=48,382,019 elapsed=89.8s

  [4424/17668] intraday_13111.csv.gz  in=262,807,328 out=48,394,658 elapsed=89.8s

  [4425/17668] intraday_13113.csv.gz  in=262,818,992 out=48,406,322 elapsed=89.8s

  [4426/17668] intraday_13114.csv.gz  in=262,830,972 out=48,418,302 elapsed=89.8s

  [4427/17668] intraday_13116.csv.gz  in=262,843,431 out=48,430,761 elapsed=89.9s

  [4428/17668] intraday_13115.csv.gz  in=262,857,171 out=48,444,501 elapsed=89.9s

  [4429/17668] intraday_13117.csv.gz  in=262,872,145 out=48,459,475 elapsed=89.9s

  [4430/17668] intraday_13119.csv.gz  in=262,886,956 out=48,474,286 elapsed=89.9s

  [4431/17668] intraday_13118.csv.gz  in=262,899,488 out=48,486,818 elapsed=89.9s

  [4432/17668] intraday_1312.csv.gz  in=262,916,732 out=48,486,818 elapsed=89.9s

  [4433/17668] intraday_13122.csv.gz  in=262,929,566 out=48,499,652 elapsed=90.0s

  [4434/17668] intraday_13120.csv.gz  in=262,941,201 out=48,511,287 elapsed=90.0s

  [4435/17668] intraday_13123.csv.gz  in=262,954,864 out=48,524,950 elapsed=90.0s

  [4436/17668] intraday_13121.csv.gz  in=262,967,992 out=48,538,078 elapsed=90.0s

  [4437/17668] intraday_13124.csv.gz  in=262,978,862 out=48,548,948 elapsed=90.0s

  [4438/17668] intraday_13125.csv.gz  in=262,993,555 out=48,563,641 elapsed=90.0s

  [4439/17668] intraday_13126.csv.gz  in=263,009,099 out=48,579,185 elapsed=90.0s

  [4440/17668] intraday_13127.csv.gz  in=263,023,676 out=48,593,762 elapsed=90.0s

  [4441/17668] intraday_13128.csv.gz  in=263,039,582 out=48,609,668 elapsed=90.1s

  [4442/17668] intraday_13129.csv.gz  in=263,057,847 out=48,627,933 elapsed=90.1s

  [4443/17668] intraday_1313.csv.gz  in=263,069,143 out=48,627,933 elapsed=90.1s

  [4444/17668] intraday_13130.csv.gz  in=263,084,829 out=48,643,619 elapsed=90.1s

  [4445/17668] intraday_13131.csv.gz  in=263,100,743 out=48,659,533 elapsed=90.1s

  [4446/17668] intraday_13133.csv.gz  in=263,113,185 out=48,671,975 elapsed=90.1s

  [4447/17668] intraday_13132.csv.gz  in=263,127,694 out=48,686,484 elapsed=90.1s

  [4448/17668] intraday_13134.csv.gz  in=263,139,276 out=48,698,066 elapsed=90.1s

  [4449/17668] intraday_13135.csv.gz  in=263,150,508 out=48,709,298 elapsed=90.2s

  [4450/17668] intraday_13136.csv.gz  in=263,163,512 out=48,722,302 elapsed=90.2s

  [4451/17668] intraday_13137.csv.gz  in=263,174,365 out=48,733,155 elapsed=90.2s

  [4452/17668] intraday_13138.csv.gz  in=263,186,761 out=48,745,551 elapsed=90.2s

  [4453/17668] intraday_1314.csv.gz  in=263,196,308 out=48,745,551 elapsed=90.2s

  [4454/17668] intraday_13139.csv.gz  in=263,209,179 out=48,758,422 elapsed=90.2s

  [4455/17668] intraday_13140.csv.gz  in=263,228,144 out=48,774,900 elapsed=90.2s

  [4456/17668] intraday_13141.csv.gz  in=263,238,727 out=48,785,483 elapsed=90.3s

  [4457/17668] intraday_13143.csv.gz  in=263,251,221 out=48,797,977 elapsed=90.3s

  [4458/17668] intraday_13144.csv.gz  in=263,262,838 out=48,809,594 elapsed=90.3s

  [4459/17668] intraday_13142.csv.gz  in=263,274,462 out=48,821,218 elapsed=90.3s

  [4460/17668] intraday_13145.csv.gz  in=263,287,646 out=48,834,402 elapsed=90.3s

  [4461/17668] intraday_13146.csv.gz  in=263,302,326 out=48,849,082 elapsed=90.3s

  [4462/17668] intraday_13148.csv.gz  in=263,316,233 out=48,862,989 elapsed=90.3s

  [4463/17668] intraday_1315.csv.gz  in=263,328,092 out=48,862,989 elapsed=90.3s

  [4464/17668] intraday_13149.csv.gz  in=263,342,220 out=48,877,117 elapsed=90.3s

  [4465/17668] intraday_13147.csv.gz  in=263,357,792 out=48,892,689 elapsed=90.3s

  [4466/17668] intraday_13150.csv.gz  in=263,370,226 out=48,905,123 elapsed=90.4s

  [4467/17668] intraday_13151.csv.gz  in=263,383,016 out=48,917,913 elapsed=90.4s

  [4468/17668] intraday_13152.csv.gz  in=263,396,612 out=48,931,509 elapsed=90.4s

  [4469/17668] intraday_13154.csv.gz  in=263,405,909 out=48,940,806 elapsed=90.4s

  [4470/17668] intraday_13155.csv.gz  in=263,413,892 out=48,948,789 elapsed=90.4s

  [4471/17668] intraday_13153.csv.gz  in=263,450,946 out=48,972,892 elapsed=90.4s

  [4472/17668] intraday_13156.csv.gz  in=263,466,369 out=48,988,315 elapsed=90.4s

  [4473/17668] intraday_13157.csv.gz  in=263,471,788 out=48,993,734 elapsed=90.4s

  [4474/17668] intraday_1316.csv.gz  in=263,484,666 out=48,993,734 elapsed=90.5s

  [4475/17668] intraday_13160.csv.gz  in=263,517,027 out=49,026,095 elapsed=90.5s

  [4476/17668] intraday_13161.csv.gz  in=263,527,985 out=49,037,053 elapsed=90.5s

  [4477/17668] intraday_13159.csv.gz  in=263,566,930 out=49,075,998 elapsed=90.5s

  [4478/17668] intraday_13158.csv.gz  in=263,615,108 out=49,124,176 elapsed=90.6s

  [4479/17668] intraday_13162.csv.gz  in=263,621,166 out=49,130,234 elapsed=90.6s

  [4480/17668] intraday_13163.csv.gz  in=263,662,721 out=49,171,531 elapsed=90.6s

  [4481/17668] intraday_13166.csv.gz  in=263,696,445 out=49,205,255 elapsed=90.7s

  [4482/17668] intraday_13164.csv.gz  in=263,736,758 out=49,245,568 elapsed=90.7s

  [4483/17668] intraday_13165.csv.gz  in=263,770,469 out=49,279,279 elapsed=90.7s

  [4484/17668] intraday_13167.csv.gz  in=263,808,723 out=49,317,533 elapsed=90.7s

  [4485/17668] intraday_13170.csv.gz  in=263,826,982 out=49,335,792 elapsed=90.7s

  [4486/17668] intraday_1317.csv.gz  in=263,841,998 out=49,335,792 elapsed=90.7s

  [4487/17668] intraday_13169.csv.gz  in=263,859,477 out=49,353,271 elapsed=90.7s

  [4488/17668] intraday_13168.csv.gz  in=263,901,074 out=49,394,868 elapsed=90.8s

  [4489/17668] intraday_13171.csv.gz  in=263,945,556 out=49,433,901 elapsed=90.8s

  [4490/17668] intraday_13173.csv.gz  in=263,983,008 out=49,471,353 elapsed=90.8s

  [4491/17668] intraday_13174.csv.gz  in=264,020,985 out=49,509,330 elapsed=90.8s

  [4492/17668] intraday_13175.csv.gz  in=264,057,300 out=49,545,645 elapsed=90.9s

  [4493/17668] intraday_13172.csv.gz  in=264,091,109 out=49,579,454 elapsed=90.9s

  [4494/17668] intraday_13176.csv.gz  in=264,138,899 out=49,624,639 elapsed=90.9s

  [4495/17668] intraday_13177.csv.gz  in=264,170,584 out=49,656,324 elapsed=90.9s

  [4496/17668] intraday_1318.csv.gz  in=264,184,578 out=49,656,324 elapsed=90.9s

  [4497/17668] intraday_13178.csv.gz  in=264,213,214 out=49,684,960 elapsed=90.9s

  [4498/17668] intraday_13179.csv.gz  in=264,241,715 out=49,713,461 elapsed=90.9s

  [4499/17668] intraday_13180.csv.gz  in=264,283,791 out=49,755,537 elapsed=91.0s

  [4500/17668] intraday_13181.csv.gz  in=264,315,909 out=49,787,655 elapsed=91.0s

  [4501/17668] intraday_13182.csv.gz  in=264,350,644 out=49,822,390 elapsed=91.0s

  [4502/17668] intraday_13183.csv.gz  in=264,386,276 out=49,858,022 elapsed=91.0s

  [4503/17668] intraday_13186.csv.gz  in=264,388,237 out=49,859,983 elapsed=91.0s

  [4504/17668] intraday_13185.csv.gz  in=264,419,243 out=49,890,989 elapsed=91.1s

  [4505/17668] intraday_13187.csv.gz  in=264,448,698 out=49,920,444 elapsed=91.1s

  [4506/17668] intraday_13184.csv.gz  in=264,492,548 out=49,961,406 elapsed=91.1s

  [4507/17668] intraday_1319.csv.gz  in=264,505,437 out=49,961,406 elapsed=91.1s

  [4508/17668] intraday_13188.csv.gz  in=264,542,427 out=49,998,396 elapsed=91.1s

  [4509/17668] intraday_13189.csv.gz  in=264,577,925 out=50,033,894 elapsed=91.1s

  [4510/17668] intraday_13190.csv.gz  in=264,619,028 out=50,073,382 elapsed=91.2s

  [4511/17668] intraday_13193.csv.gz  in=264,657,294 out=50,111,648 elapsed=91.2s

  [4512/17668] intraday_13191.csv.gz  in=264,698,572 out=50,152,926 elapsed=91.2s

  [4513/17668] intraday_13192.csv.gz  in=264,731,246 out=50,185,600 elapsed=91.2s

  [4514/17668] intraday_13194.csv.gz  in=264,768,762 out=50,223,116 elapsed=91.3s

  [4515/17668] intraday_13195.csv.gz  in=264,777,284 out=50,231,638 elapsed=91.3s

  [4516/17668] intraday_13196.csv.gz  in=264,817,844 out=50,272,198 elapsed=91.3s

  [4517/17668] intraday_13197.csv.gz  in=264,852,154 out=50,306,508 elapsed=91.3s

  [4518/17668] intraday_13199.csv.gz  in=264,888,280 out=50,341,396 elapsed=91.4s

  [4519/17668] intraday_13198.csv.gz  in=264,927,203 out=50,380,319 elapsed=91.4s

  [4520/17668] intraday_1320.csv.gz  in=264,940,398 out=50,380,319 elapsed=91.4s

  [4521/17668] intraday_13200.csv.gz  in=264,977,558 out=50,417,479 elapsed=91.4s

  [4522/17668] intraday_13203.csv.gz  in=264,987,806 out=50,427,727 elapsed=91.4s

  [4523/17668] intraday_13204.csv.gz  in=264,999,384 out=50,439,305 elapsed=91.4s

  [4524/17668] intraday_13201.csv.gz  in=265,032,392 out=50,472,313 elapsed=91.4s

  [4525/17668] intraday_13202.csv.gz  in=265,069,662 out=50,509,583 elapsed=91.5s

  [4526/17668] intraday_13206.csv.gz  in=265,097,769 out=50,537,690 elapsed=91.5s

  [4527/17668] intraday_13205.csv.gz  in=265,128,063 out=50,567,959 elapsed=91.5s

  [4528/17668] intraday_13207.csv.gz  in=265,170,393 out=50,610,289 elapsed=91.5s

  [4529/17668] intraday_1321.csv.gz  in=265,184,265 out=50,610,289 elapsed=91.5s

  [4530/17668] intraday_13208.csv.gz  in=265,225,882 out=50,651,754 elapsed=91.5s

  [4531/17668] intraday_13209.csv.gz  in=265,264,231 out=50,690,103 elapsed=91.5s

  [4532/17668] intraday_13210.csv.gz  in=265,300,976 out=50,725,653 elapsed=91.6s

  [4533/17668] intraday_13211.csv.gz  in=265,337,358 out=50,762,035 elapsed=91.6s

  [4534/17668] intraday_13212.csv.gz  in=265,347,028 out=50,771,705 elapsed=91.6s

  [4535/17668] intraday_13213.csv.gz  in=265,361,900 out=50,786,577 elapsed=91.6s

  [4536/17668] intraday_13214.csv.gz  in=265,398,637 out=50,823,314 elapsed=91.7s

  [4537/17668] intraday_13216.csv.gz  in=265,425,360 out=50,850,037 elapsed=91.7s

  [4538/17668] intraday_13217.csv.gz  in=265,465,543 out=50,890,220 elapsed=91.7s

  [4539/17668] intraday_13215.csv.gz  in=265,504,220 out=50,928,897 elapsed=91.7s

  [4540/17668] intraday_1322.csv.gz  in=265,517,759 out=50,928,897 elapsed=91.7s

  [4541/17668] intraday_13218.csv.gz  in=265,555,718 out=50,966,856 elapsed=91.7s

  [4542/17668] intraday_13219.csv.gz  in=265,588,793 out=50,999,931 elapsed=91.8s

  [4543/17668] intraday_13221.csv.gz  in=265,613,731 out=51,024,869 elapsed=91.8s

  [4544/17668] intraday_13220.csv.gz  in=265,647,892 out=51,059,030 elapsed=91.8s

  [4545/17668] intraday_13222.csv.gz  in=265,675,339 out=51,086,477 elapsed=91.8s

  [4546/17668] intraday_13223.csv.gz  in=265,720,977 out=51,132,115 elapsed=91.8s

  [4547/17668] intraday_13224.csv.gz  in=265,752,100 out=51,163,238 elapsed=91.9s

  [4548/17668] intraday_13225.csv.gz  in=265,792,907 out=51,204,045 elapsed=91.9s

  [4549/17668] intraday_13226.csv.gz  in=265,825,526 out=51,236,664 elapsed=91.9s

  [4550/17668] intraday_13227.csv.gz  in=265,867,150 out=51,278,288 elapsed=91.9s

  [4551/17668] intraday_1323.csv.gz  in=265,880,312 out=51,278,288 elapsed=91.9s

  [4552/17668] intraday_13231.csv.gz  in=265,881,802 out=51,279,778 elapsed=92.0s

  [4553/17668] intraday_13229.csv.gz  in=265,916,090 out=51,314,066 elapsed=92.0s

  [4554/17668] intraday_13230.csv.gz  in=265,948,495 out=51,346,471 elapsed=92.0s

  [4555/17668] intraday_13228.csv.gz  in=265,987,237 out=51,382,394 elapsed=92.0s

  [4556/17668] intraday_13232.csv.gz  in=266,022,061 out=51,417,218 elapsed=92.1s

  [4557/17668] intraday_13233.csv.gz  in=266,054,641 out=51,449,200 elapsed=92.1s

  [4558/17668] intraday_13235.csv.gz  in=266,089,818 out=51,484,377 elapsed=92.1s

  [4559/17668] intraday_13234.csv.gz  in=266,130,174 out=51,524,733 elapsed=92.1s

  [4560/17668] intraday_13236.csv.gz  in=266,159,949 out=51,554,508 elapsed=92.1s

  [4561/17668] intraday_13239.csv.gz  in=266,172,330 out=51,566,889 elapsed=92.1s

  [4562/17668] intraday_1324.csv.gz  in=266,185,709 out=51,566,889 elapsed=92.2s

  [4563/17668] intraday_13237.csv.gz  in=266,220,840 out=51,602,020 elapsed=92.2s

  [4564/17668] intraday_13238.csv.gz  in=266,256,749 out=51,637,929 elapsed=92.2s

  [4565/17668] intraday_13240.csv.gz  in=266,277,332 out=51,658,512 elapsed=92.2s

  [4566/17668] intraday_13241.csv.gz  in=266,311,843 out=51,693,023 elapsed=92.2s

  [4567/17668] intraday_13242.csv.gz  in=266,353,469 out=51,731,390 elapsed=92.3s

  [4568/17668] intraday_13243.csv.gz  in=266,392,063 out=51,769,984 elapsed=92.3s

  [4569/17668] intraday_13244.csv.gz  in=266,439,153 out=51,815,945 elapsed=92.3s

  [4570/17668] intraday_13245.csv.gz  in=266,469,125 out=51,845,917 elapsed=92.3s

  [4571/17668] intraday_13246.csv.gz  in=266,513,712 out=51,888,904 elapsed=92.3s

  [4572/17668] intraday_13249.csv.gz  in=266,514,526 out=51,889,718 elapsed=92.3s

  [4573/17668] intraday_1325.csv.gz  in=266,525,411 out=51,889,718 elapsed=92.3s

  [4574/17668] intraday_13247.csv.gz  in=266,570,909 out=51,935,216 elapsed=92.4s

  [4575/17668] intraday_13248.csv.gz  in=266,605,146 out=51,969,453 elapsed=92.4s

  [4576/17668] intraday_13251.csv.gz  in=266,642,187 out=52,006,494 elapsed=92.4s

  [4577/17668] intraday_13250.csv.gz  in=266,682,908 out=52,047,215 elapsed=92.4s

  [4578/17668] intraday_13252.csv.gz  in=266,717,978 out=52,082,285 elapsed=92.4s

  [4579/17668] intraday_13253.csv.gz  in=266,753,758 out=52,118,065 elapsed=92.4s

  [4580/17668] intraday_13254.csv.gz  in=266,784,158 out=52,148,465 elapsed=92.5s

  [4581/17668] intraday_13255.csv.gz  in=266,826,806 out=52,190,243 elapsed=92.5s

  [4582/17668] intraday_13256.csv.gz  in=266,856,703 out=52,220,140 elapsed=92.5s

  [4583/17668] intraday_13257.csv.gz  in=266,894,826 out=52,258,263 elapsed=92.6s

  [4584/17668] intraday_13259.csv.gz  in=266,895,540 out=52,258,977 elapsed=92.6s

  [4585/17668] intraday_13260.csv.gz  in=266,896,734 out=52,260,171 elapsed=92.6s

  [4586/17668] intraday_13258.csv.gz  in=266,927,532 out=52,290,969 elapsed=92.6s

  [4587/17668] intraday_1326.csv.gz  in=266,939,768 out=52,290,969 elapsed=92.6s

  [4588/17668] intraday_13261.csv.gz  in=266,970,999 out=52,322,200 elapsed=92.6s

  [4589/17668] intraday_13263.csv.gz  in=267,006,349 out=52,357,550 elapsed=92.7s

  [4590/17668] intraday_13264.csv.gz  in=267,048,407 out=52,399,608 elapsed=92.7s

  [4591/17668] intraday_13262.csv.gz  in=267,084,855 out=52,436,056 elapsed=92.7s

  [4592/17668] intraday_13266.csv.gz  in=267,123,975 out=52,475,176 elapsed=92.7s

  [4593/17668] intraday_13265.csv.gz  in=267,167,539 out=52,518,740 elapsed=92.7s

  [4594/17668] intraday_13268.csv.gz  in=267,203,104 out=52,554,305 elapsed=92.7s

  [4595/17668] intraday_13267.csv.gz  in=267,245,554 out=52,596,755 elapsed=92.8s

  [4596/17668] intraday_1327.csv.gz  in=267,258,738 out=52,596,755 elapsed=92.8s

  [4597/17668] intraday_13272.csv.gz  in=267,261,512 out=52,599,529 elapsed=92.8s

  [4598/17668] intraday_13269.csv.gz  in=267,294,337 out=52,632,354 elapsed=92.8s

  [4599/17668] intraday_13270.csv.gz  in=267,329,374 out=52,667,391 elapsed=92.8s

  [4600/17668] intraday_13274.csv.gz  in=267,329,624 out=52,667,641 elapsed=92.8s

  [4601/17668] intraday_13271.csv.gz  in=267,360,045 out=52,698,062 elapsed=92.8s

  [4602/17668] intraday_13275.csv.gz  in=267,360,338 out=52,698,355 elapsed=92.8s

  [4603/17668] intraday_13273.csv.gz  in=267,392,950 out=52,730,967 elapsed=92.8s

  [4604/17668] intraday_13277.csv.gz  in=267,393,488 out=52,731,505 elapsed=92.9s

  [4605/17668] intraday_13276.csv.gz  in=267,415,912 out=52,744,493 elapsed=92.9s

  [4606/17668] intraday_13278.csv.gz  in=267,416,321 out=52,744,902 elapsed=92.9s

  [4607/17668] intraday_13279.csv.gz  in=267,416,645 out=52,745,226 elapsed=92.9s

  [4608/17668] intraday_1328.csv.gz  in=267,430,301 out=52,745,226 elapsed=92.9s

  [4609/17668] intraday_13281.csv.gz  in=267,430,937 out=52,745,862 elapsed=92.9s

  [4610/17668] intraday_13282.csv.gz  in=267,431,212 out=52,746,137 elapsed=92.9s

  [4611/17668] intraday_13280.csv.gz  in=267,432,031 out=52,746,956 elapsed=92.9s

  [4612/17668] intraday_13283.csv.gz  in=267,432,433 out=52,747,358 elapsed=92.9s

  [4613/17668] intraday_13284.csv.gz  in=267,433,025 out=52,747,950 elapsed=92.9s

  [4614/17668] intraday_13285.csv.gz  in=267,448,016 out=52,762,866 elapsed=93.0s

  [4615/17668] intraday_13288.csv.gz  in=267,457,469 out=52,772,319 elapsed=93.0s

  [4616/17668] intraday_13287.csv.gz  in=267,469,777 out=52,784,627 elapsed=93.0s

  [4617/17668] intraday_13286.csv.gz  in=267,481,872 out=52,796,722 elapsed=93.0s

  [4618/17668] intraday_13289.csv.gz  in=267,493,327 out=52,808,177 elapsed=93.0s

  [4619/17668] intraday_1329.csv.gz  in=267,504,290 out=52,808,177 elapsed=93.0s

  [4620/17668] intraday_13290.csv.gz  in=267,518,540 out=52,822,427 elapsed=93.0s

  [4621/17668] intraday_13291.csv.gz  in=267,532,884 out=52,836,771 elapsed=93.1s

  [4622/17668] intraday_13292.csv.gz  in=267,543,821 out=52,847,708 elapsed=93.1s

  [4623/17668] intraday_13293.csv.gz  in=267,555,773 out=52,859,660 elapsed=93.1s

  [4624/17668] intraday_13294.csv.gz  in=267,568,284 out=52,872,171 elapsed=93.1s

  [4625/17668] intraday_13295.csv.gz  in=267,578,720 out=52,882,607 elapsed=93.1s

  [4626/17668] intraday_13299.csv.gz  in=267,581,467 out=52,885,354 elapsed=93.1s

  [4627/17668] intraday_13297.csv.gz  in=267,592,349 out=52,896,236 elapsed=93.1s

  [4628/17668] intraday_13296.csv.gz  in=267,604,326 out=52,908,213 elapsed=93.1s

  [4629/17668] intraday_13298.csv.gz  in=267,618,481 out=52,922,368 elapsed=93.1s

  [4630/17668] intraday_1330.csv.gz  in=267,631,563 out=52,922,368 elapsed=93.2s

  [4631/17668] intraday_13300.csv.gz  in=267,640,810 out=52,931,615 elapsed=93.2s

  [4632/17668] intraday_13302.csv.gz  in=267,651,222 out=52,942,027 elapsed=93.2s

  [4633/17668] intraday_13301.csv.gz  in=267,662,177 out=52,952,982 elapsed=93.2s

  [4634/17668] intraday_13303.csv.gz  in=267,673,389 out=52,964,194 elapsed=93.2s

  [4635/17668] intraday_13304.csv.gz  in=267,686,027 out=52,976,832 elapsed=93.2s

  [4636/17668] intraday_13305.csv.gz  in=267,698,611 out=52,989,416 elapsed=93.2s

  [4637/17668] intraday_13308.csv.gz  in=267,708,845 out=52,999,650 elapsed=93.3s

  [4638/17668] intraday_13307.csv.gz  in=267,721,054 out=53,011,859 elapsed=93.3s

  [4639/17668] intraday_13306.csv.gz  in=267,733,438 out=53,024,243 elapsed=93.3s

  [4640/17668] intraday_13309.csv.gz  in=267,744,417 out=53,035,222 elapsed=93.3s

  [4641/17668] intraday_1331.csv.gz  in=267,763,460 out=53,035,222 elapsed=93.3s

  [4642/17668] intraday_13311.csv.gz  in=267,773,404 out=53,045,166 elapsed=93.3s

  [4643/17668] intraday_13312.csv.gz  in=267,781,188 out=53,052,950 elapsed=93.3s

  [4644/17668] intraday_13313.csv.gz  in=267,786,675 out=53,058,437 elapsed=93.4s

  [4645/17668] intraday_13310.csv.gz  in=267,798,058 out=53,069,820 elapsed=93.4s

  [4646/17668] intraday_13314.csv.gz  in=267,810,288 out=53,082,050 elapsed=93.4s

  [4647/17668] intraday_13315.csv.gz  in=267,821,573 out=53,093,335 elapsed=93.4s

  [4648/17668] intraday_13318.csv.gz  in=267,832,012 out=53,103,346 elapsed=93.4s

  [4649/17668] intraday_13316.csv.gz  in=267,846,420 out=53,117,754 elapsed=93.4s

  [4650/17668] intraday_13317.csv.gz  in=267,858,354 out=53,129,688 elapsed=93.4s

  [4651/17668] intraday_13319.csv.gz  in=267,869,384 out=53,140,718 elapsed=93.4s

  [4652/17668] intraday_1332.csv.gz  in=267,881,062 out=53,140,718 elapsed=93.4s

  [4653/17668] intraday_13320.csv.gz  in=267,889,843 out=53,149,499 elapsed=93.5s

  [4654/17668] intraday_13321.csv.gz  in=267,899,416 out=53,159,072 elapsed=93.5s

  [4655/17668] intraday_13323.csv.gz  in=267,911,036 out=53,170,692 elapsed=93.5s

  [4656/17668] intraday_13322.csv.gz  in=267,922,642 out=53,182,298 elapsed=93.5s

  [4657/17668] intraday_13326.csv.gz  in=267,922,643 out=53,182,299 elapsed=93.5s

  [4658/17668] intraday_13325.csv.gz  in=267,928,000 out=53,187,656 elapsed=93.5s

  [4659/17668] intraday_13324.csv.gz  in=267,943,138 out=53,201,337 elapsed=93.5s

  [4660/17668] intraday_13327.csv.gz  in=267,952,096 out=53,210,295 elapsed=93.5s

  [4661/17668] intraday_13328.csv.gz  in=267,965,553 out=53,221,877 elapsed=93.6s

  [4662/17668] intraday_1333.csv.gz  in=267,980,730 out=53,221,877 elapsed=93.6s

  [4663/17668] intraday_13329.csv.gz  in=267,991,594 out=53,232,741 elapsed=93.6s

  [4664/17668] intraday_13330.csv.gz  in=268,001,959 out=53,243,106 elapsed=93.6s

  [4665/17668] intraday_13331.csv.gz  in=268,011,890 out=53,253,037 elapsed=93.6s

  [4666/17668] intraday_13332.csv.gz  in=268,024,406 out=53,265,553 elapsed=93.6s

  [4667/17668] intraday_13334.csv.gz  in=268,035,273 out=53,276,420 elapsed=93.6s

  [4668/17668] intraday_13333.csv.gz  in=268,046,472 out=53,287,619 elapsed=93.6s

  [4669/17668] intraday_13335.csv.gz  in=268,057,868 out=53,299,015 elapsed=93.6s

  [4670/17668] intraday_13336.csv.gz  in=268,068,543 out=53,309,690 elapsed=93.7s

  [4671/17668] intraday_13339.csv.gz  in=268,070,367 out=53,311,514 elapsed=93.7s

  [4672/17668] intraday_13337.csv.gz  in=268,082,369 out=53,323,516 elapsed=93.7s

  [4673/17668] intraday_13338.csv.gz  in=268,101,232 out=53,338,805 elapsed=93.7s

  [4674/17668] intraday_1334.csv.gz  in=268,113,445 out=53,338,805 elapsed=93.7s

  [4675/17668] intraday_13340.csv.gz  in=268,117,058 out=53,342,418 elapsed=93.7s

  [4676/17668] intraday_13343.csv.gz  in=268,125,657 out=53,351,017 elapsed=93.7s

  [4677/17668] intraday_13341.csv.gz  in=268,142,531 out=53,364,608 elapsed=93.7s

  [4678/17668] intraday_13342.csv.gz  in=268,152,688 out=53,374,765 elapsed=93.7s

  [4679/17668] intraday_13344.csv.gz  in=268,166,595 out=53,388,672 elapsed=93.7s

  [4680/17668] intraday_13348.csv.gz  in=268,177,528 out=53,399,605 elapsed=93.8s

  [4681/17668] intraday_13347.csv.gz  in=268,189,466 out=53,411,543 elapsed=93.8s

  [4682/17668] intraday_13345.csv.gz  in=268,202,823 out=53,424,900 elapsed=93.8s

  [4683/17668] intraday_13346.csv.gz  in=268,219,284 out=53,439,997 elapsed=93.8s

  [4684/17668] intraday_1335.csv.gz  in=268,231,310 out=53,439,997 elapsed=93.8s

  [4685/17668] intraday_13349.csv.gz  in=268,239,487 out=53,448,174 elapsed=93.9s

  [4686/17668] intraday_13351.csv.gz  in=268,251,407 out=53,460,094 elapsed=93.9s

  [4687/17668] intraday_13350.csv.gz  in=268,262,936 out=53,471,519 elapsed=93.9s

  [4688/17668] intraday_13352.csv.gz  in=268,275,982 out=53,484,565 elapsed=93.9s

  [4689/17668] intraday_13353.csv.gz  in=268,283,400 out=53,491,983 elapsed=93.9s

  [4690/17668] intraday_13354.csv.gz  in=268,284,080 out=53,492,663 elapsed=93.9s

  [4691/17668] intraday_13355.csv.gz  in=268,296,368 out=53,504,951 elapsed=93.9s

  [4692/17668] intraday_13356.csv.gz  in=268,307,939 out=53,516,522 elapsed=94.0s

  [4693/17668] intraday_13357.csv.gz  in=268,319,877 out=53,528,460 elapsed=94.0s

  [4694/17668] intraday_13358.csv.gz  in=268,331,321 out=53,539,904 elapsed=94.0s

  [4695/17668] intraday_1336.csv.gz  in=268,345,300 out=53,539,904 elapsed=94.0s

  [4696/17668] intraday_13359.csv.gz  in=268,354,480 out=53,549,084 elapsed=94.0s

  [4697/17668] intraday_13360.csv.gz  in=268,365,945 out=53,560,549 elapsed=94.0s

  [4698/17668] intraday_13362.csv.gz  in=268,379,560 out=53,574,164 elapsed=94.0s

  [4699/17668] intraday_13363.csv.gz  in=268,393,226 out=53,587,830 elapsed=94.0s

  [4700/17668] intraday_13364.csv.gz  in=268,406,519 out=53,601,123 elapsed=94.0s

  [4701/17668] intraday_13361.csv.gz  in=268,417,915 out=53,612,519 elapsed=94.0s

  [4702/17668] intraday_13365.csv.gz  in=268,428,709 out=53,623,313 elapsed=94.0s

  [4703/17668] intraday_13366.csv.gz  in=268,441,239 out=53,635,843 elapsed=94.1s

  [4704/17668] intraday_13367.csv.gz  in=268,452,189 out=53,646,793 elapsed=94.1s

  [4705/17668] intraday_13368.csv.gz  in=268,464,069 out=53,658,673 elapsed=94.1s

  [4706/17668] intraday_13369.csv.gz  in=268,480,214 out=53,673,830 elapsed=94.1s

  [4707/17668] intraday_13370.csv.gz  in=268,491,366 out=53,684,982 elapsed=94.1s

  [4708/17668] intraday_1337.csv.gz  in=268,506,234 out=53,684,982 elapsed=94.1s

  [4709/17668] intraday_13371.csv.gz  in=268,520,029 out=53,698,777 elapsed=94.1s

  [4710/17668] intraday_13372.csv.gz  in=268,532,133 out=53,710,881 elapsed=94.1s

  [4711/17668] intraday_13373.csv.gz  in=268,543,707 out=53,722,455 elapsed=94.2s

  [4712/17668] intraday_13374.csv.gz  in=268,554,642 out=53,733,390 elapsed=94.2s

  [4713/17668] intraday_13375.csv.gz  in=268,567,030 out=53,745,778 elapsed=94.2s

  [4714/17668] intraday_13376.csv.gz  in=268,578,338 out=53,757,086 elapsed=94.2s

  [4715/17668] intraday_13377.csv.gz  in=268,587,787 out=53,766,497 elapsed=94.2s

  [4716/17668] intraday_13378.csv.gz  in=268,599,626 out=53,778,336 elapsed=94.2s

  [4717/17668] intraday_1338.csv.gz  in=268,612,246 out=53,778,336 elapsed=94.2s

  [4718/17668] intraday_13379.csv.gz  in=268,622,463 out=53,788,553 elapsed=94.2s

  [4719/17668] intraday_13380.csv.gz  in=268,634,424 out=53,800,514 elapsed=94.2s

  [4720/17668] intraday_13381.csv.gz  in=268,645,491 out=53,811,581 elapsed=94.3s

  [4721/17668] intraday_13382.csv.gz  in=268,657,396 out=53,823,486 elapsed=94.3s

  [4722/17668] intraday_13384.csv.gz  in=268,668,236 out=53,834,326 elapsed=94.3s

  [4723/17668] intraday_13383.csv.gz  in=268,681,075 out=53,847,165 elapsed=94.3s

  [4724/17668] intraday_13385.csv.gz  in=268,695,324 out=53,861,414 elapsed=94.3s

  [4725/17668] intraday_13386.csv.gz  in=268,706,277 out=53,872,367 elapsed=94.3s

  [4726/17668] intraday_13387.csv.gz  in=268,717,117 out=53,883,207 elapsed=94.3s

  [4727/17668] intraday_13388.csv.gz  in=268,728,984 out=53,895,074 elapsed=94.3s

  [4728/17668] intraday_13389.csv.gz  in=268,742,629 out=53,908,719 elapsed=94.4s

  [4729/17668] intraday_1339.csv.gz  in=268,756,871 out=53,908,719 elapsed=94.4s

  [4730/17668] intraday_13390.csv.gz  in=268,766,855 out=53,918,703 elapsed=94.4s

  [4731/17668] intraday_13391.csv.gz  in=268,779,495 out=53,931,343 elapsed=94.4s

  [4732/17668] intraday_13393.csv.gz  in=268,791,789 out=53,943,637 elapsed=94.4s

  [4733/17668] intraday_13392.csv.gz  in=268,805,741 out=53,957,589 elapsed=94.4s

  [4734/17668] intraday_13394.csv.gz  in=268,819,824 out=53,971,672 elapsed=94.4s

  [4735/17668] intraday_13395.csv.gz  in=268,834,092 out=53,985,940 elapsed=94.4s

  [4736/17668] intraday_13397.csv.gz  in=268,847,479 out=53,999,327 elapsed=94.5s

  [4737/17668] intraday_13399.csv.gz  in=268,860,041 out=54,011,889 elapsed=94.5s

  [4738/17668] intraday_13398.csv.gz  in=268,873,447 out=54,025,295 elapsed=94.5s

  [4739/17668] intraday_13396.csv.gz  in=268,890,303 out=54,042,151 elapsed=94.5s

  [4740/17668] intraday_1340.csv.gz  in=268,902,233 out=54,042,151 elapsed=94.5s

  [4741/17668] intraday_13401.csv.gz  in=268,911,127 out=54,051,045 elapsed=94.5s

  [4742/17668] intraday_13402.csv.gz  in=268,923,743 out=54,063,661 elapsed=94.6s

  [4743/17668] intraday_13400.csv.gz  in=268,935,562 out=54,075,480 elapsed=94.6s

  [4744/17668] intraday_13403.csv.gz  in=268,945,582 out=54,085,500 elapsed=94.6s

  [4745/17668] intraday_13404.csv.gz  in=268,956,579 out=54,096,497 elapsed=94.6s

  [4746/17668] intraday_13405.csv.gz  in=268,968,817 out=54,108,735 elapsed=94.6s

  [4747/17668] intraday_13407.csv.gz  in=268,977,670 out=54,117,588 elapsed=94.6s

  [4748/17668] intraday_13406.csv.gz  in=268,991,380 out=54,131,298 elapsed=94.6s

  [4749/17668] intraday_13409.csv.gz  in=269,003,296 out=54,143,214 elapsed=94.6s

  [4750/17668] intraday_1341.csv.gz  in=269,019,456 out=54,143,214 elapsed=94.6s

  [4751/17668] intraday_13408.csv.gz  in=269,029,890 out=54,153,648 elapsed=94.6s

  [4752/17668] intraday_13410.csv.gz  in=269,040,176 out=54,163,934 elapsed=94.6s

  [4753/17668] intraday_13411.csv.gz  in=269,052,707 out=54,176,465 elapsed=94.7s

  [4754/17668] intraday_13413.csv.gz  in=269,066,024 out=54,189,782 elapsed=94.7s

  [4755/17668] intraday_13412.csv.gz  in=269,079,688 out=54,203,446 elapsed=94.7s

  [4756/17668] intraday_13414.csv.gz  in=269,091,315 out=54,215,073 elapsed=94.7s

  [4757/17668] intraday_13415.csv.gz  in=269,106,060 out=54,229,818 elapsed=94.7s

  [4758/17668] intraday_13416.csv.gz  in=269,116,913 out=54,240,671 elapsed=94.7s

  [4759/17668] intraday_13417.csv.gz  in=269,127,581 out=54,251,339 elapsed=94.7s

  [4760/17668] intraday_13418.csv.gz  in=269,139,552 out=54,263,310 elapsed=94.8s

  [4761/17668] intraday_13419.csv.gz  in=269,151,069 out=54,274,827 elapsed=94.8s

  [4762/17668] intraday_1342.csv.gz  in=269,162,567 out=54,274,827 elapsed=94.8s

  [4763/17668] intraday_13420.csv.gz  in=269,172,314 out=54,284,574 elapsed=94.8s

  [4764/17668] intraday_13421.csv.gz  in=269,177,981 out=54,290,241 elapsed=94.8s

  [4765/17668] intraday_13424.csv.gz  in=269,178,157 out=54,290,417 elapsed=94.8s

  [4766/17668] intraday_13423.csv.gz  in=269,185,747 out=54,298,007 elapsed=94.8s

  [4767/17668] intraday_13425.csv.gz  in=269,186,212 out=54,298,472 elapsed=94.8s

  [4768/17668] intraday_13426.csv.gz  in=269,186,955 out=54,299,215 elapsed=94.8s

  [4769/17668] intraday_13427.csv.gz  in=269,187,660 out=54,299,920 elapsed=94.8s

  [4770/17668] intraday_13422.csv.gz  in=269,199,694 out=54,311,954 elapsed=94.8s

  [4771/17668] intraday_13429.csv.gz  in=269,200,101 out=54,312,361 elapsed=94.8s

  [4772/17668] intraday_13428.csv.gz  in=269,200,266 out=54,312,526 elapsed=94.8s

  [4773/17668] intraday_13432.csv.gz  in=269,200,749 out=54,313,009 elapsed=94.9s

  [4774/17668] intraday_13430.csv.gz  in=269,201,142 out=54,313,402 elapsed=94.9s

  [4775/17668] intraday_13431.csv.gz  in=269,201,437 out=54,313,697 elapsed=94.9s

  [4776/17668] intraday_1343.csv.gz  in=269,214,676 out=54,313,697 elapsed=94.9s

  [4777/17668] intraday_13434.csv.gz  in=269,215,232 out=54,314,253 elapsed=94.9s

  [4778/17668] intraday_13433.csv.gz  in=269,215,792 out=54,314,813 elapsed=94.9s

  [4779/17668] intraday_13435.csv.gz  in=269,216,020 out=54,315,041 elapsed=94.9s

  [4780/17668] intraday_13437.csv.gz  in=269,216,709 out=54,315,730 elapsed=94.9s

  [4781/17668] intraday_13436.csv.gz  in=269,217,375 out=54,316,396 elapsed=94.9s

  [4782/17668] intraday_13438.csv.gz  in=269,217,670 out=54,316,691 elapsed=94.9s

  [4783/17668] intraday_13439.csv.gz  in=269,217,963 out=54,316,984 elapsed=94.9s

  [4784/17668] intraday_13440.csv.gz  in=269,218,235 out=54,317,256 elapsed=94.9s

  [4785/17668] intraday_13441.csv.gz  in=269,218,593 out=54,317,614 elapsed=94.9s

  [4786/17668] intraday_13442.csv.gz  in=269,218,668 out=54,317,689 elapsed=94.9s

  [4787/17668] intraday_13443.csv.gz  in=269,218,841 out=54,317,862 elapsed=94.9s

  [4788/17668] intraday_1344.csv.gz  in=269,234,097 out=54,317,862 elapsed=94.9s

  [4789/17668] intraday_13446.csv.gz  in=269,234,239 out=54,318,004 elapsed=94.9s

  [4790/17668] intraday_13447.csv.gz  in=269,234,808 out=54,318,573 elapsed=95.0s

  [4791/17668] intraday_13448.csv.gz  in=269,235,259 out=54,319,024 elapsed=95.0s

  [4792/17668] intraday_13445.csv.gz  in=269,235,994 out=54,319,759 elapsed=95.0s

  [4793/17668] intraday_13450.csv.gz  in=269,236,674 out=54,320,439 elapsed=95.0s

  [4794/17668] intraday_13444.csv.gz  in=269,253,044 out=54,332,020 elapsed=95.0s

  [4795/17668] intraday_13449.csv.gz  in=269,253,792 out=54,332,768 elapsed=95.0s

  [4796/17668] intraday_1345.csv.gz  in=269,268,136 out=54,332,768 elapsed=95.0s

  [4797/17668] intraday_13452.csv.gz  in=269,268,525 out=54,333,157 elapsed=95.0s

  [4798/17668] intraday_13451.csv.gz  in=269,268,675 out=54,333,307 elapsed=95.0s

  [4799/17668] intraday_13453.csv.gz  in=269,268,895 out=54,333,527 elapsed=95.0s

  [4800/17668] intraday_13454.csv.gz  in=269,271,155 out=54,335,787 elapsed=95.0s

  [4801/17668] intraday_13456.csv.gz  in=269,271,604 out=54,336,236 elapsed=95.0s

  [4802/17668] intraday_13455.csv.gz  in=269,271,722 out=54,336,354 elapsed=95.0s

  [4803/17668] intraday_13457.csv.gz  in=269,271,866 out=54,336,498 elapsed=95.0s

  [4804/17668] intraday_13458.csv.gz  in=269,271,898 out=54,336,530 elapsed=95.0s

  [4805/17668] intraday_13459.csv.gz  in=269,272,050 out=54,336,682 elapsed=95.0s

  [4806/17668] intraday_13462.csv.gz  in=269,272,312 out=54,336,944 elapsed=95.1s

  [4807/17668] intraday_13460.csv.gz  in=269,272,463 out=54,337,095 elapsed=95.1s

  [4808/17668] intraday_13461.csv.gz  in=269,272,832 out=54,337,425 elapsed=95.1s

  [4809/17668] intraday_1346.csv.gz  in=269,285,382 out=54,337,425 elapsed=95.1s

  [4810/17668] intraday_13463.csv.gz  in=269,285,416 out=54,337,459 elapsed=95.1s

  [4811/17668] intraday_13464.csv.gz  in=269,285,807 out=54,337,850 elapsed=95.1s

  [4812/17668] intraday_13465.csv.gz  in=269,285,960 out=54,338,003 elapsed=95.1s

  [4813/17668] intraday_13467.csv.gz  in=269,286,136 out=54,338,179 elapsed=95.1s

  [4814/17668] intraday_13468.csv.gz  in=269,286,262 out=54,338,305 elapsed=95.1s

  [4815/17668] intraday_13466.csv.gz  in=269,286,799 out=54,338,842 elapsed=95.1s

  [4816/17668] intraday_13471.csv.gz  in=269,287,355 out=54,339,398 elapsed=95.1s

  [4817/17668] intraday_13470.csv.gz  in=269,288,192 out=54,340,235 elapsed=95.1s

  [4818/17668] intraday_13469.csv.gz  in=269,288,922 out=54,340,965 elapsed=95.1s

  [4819/17668] intraday_13472.csv.gz  in=269,289,102 out=54,341,145 elapsed=95.1s

  [4820/17668] intraday_13473.csv.gz  in=269,289,293 out=54,341,336 elapsed=95.1s

  [4821/17668] intraday_13474.csv.gz  in=269,289,434 out=54,341,477 elapsed=95.1s

  [4822/17668] intraday_1347.csv.gz  in=269,304,802 out=54,341,477 elapsed=95.1s

  [4823/17668] intraday_13477.csv.gz  in=269,305,034 out=54,341,709 elapsed=95.1s

  [4824/17668] intraday_13476.csv.gz  in=269,305,358 out=54,342,033 elapsed=95.1s

  [4825/17668] intraday_13478.csv.gz  in=269,305,841 out=54,342,516 elapsed=95.2s

  [4826/17668] intraday_13480.csv.gz  in=269,305,891 out=54,342,566 elapsed=95.2s

  [4827/17668] intraday_13475.csv.gz  in=269,315,337 out=54,348,568 elapsed=95.2s

  [4828/17668] intraday_13479.csv.gz  in=269,315,491 out=54,348,722 elapsed=95.2s

  [4829/17668] intraday_1348.csv.gz  in=269,326,369 out=54,348,722 elapsed=95.2s

  [4830/17668] intraday_13481.csv.gz  in=269,326,528 out=54,348,881 elapsed=95.2s

  [4831/17668] intraday_13482.csv.gz  in=269,327,583 out=54,349,936 elapsed=95.2s

  [4832/17668] intraday_13483.csv.gz  in=269,328,340 out=54,350,693 elapsed=95.2s

  [4833/17668] intraday_13484.csv.gz  in=269,328,784 out=54,351,137 elapsed=95.2s

  [4834/17668] intraday_13486.csv.gz  in=269,329,470 out=54,351,823 elapsed=95.2s

  [4835/17668] intraday_13485.csv.gz  in=269,329,499 out=54,351,852 elapsed=95.2s

  [4836/17668] intraday_13488.csv.gz  in=269,329,916 out=54,352,269 elapsed=95.2s

  [4837/17668] intraday_13490.csv.gz  in=269,330,253 out=54,352,606 elapsed=95.2s

  [4838/17668] intraday_13489.csv.gz  in=269,330,728 out=54,353,081 elapsed=95.2s

  [4839/17668] intraday_13487.csv.gz  in=269,331,334 out=54,353,490 elapsed=95.2s

  [4840/17668] intraday_13492.csv.gz  in=269,331,896 out=54,354,052 elapsed=95.2s

  [4841/17668] intraday_13491.csv.gz  in=269,332,150 out=54,354,306 elapsed=95.2s

  [4842/17668] intraday_13494.csv.gz  in=269,332,370 out=54,354,526 elapsed=95.3s

  [4843/17668] intraday_13493.csv.gz  in=269,332,635 out=54,354,791 elapsed=95.3s

  [4844/17668] intraday_13495.csv.gz  in=269,332,870 out=54,355,026 elapsed=95.3s

  [4845/17668] intraday_1349.csv.gz  in=269,345,152 out=54,355,026 elapsed=95.3s

  [4846/17668] intraday_13496.csv.gz  in=269,345,691 out=54,355,565 elapsed=95.3s

  [4847/17668] intraday_13498.csv.gz  in=269,345,714 out=54,355,588 elapsed=95.3s

  [4848/17668] intraday_13499.csv.gz  in=269,346,152 out=54,356,026 elapsed=95.3s

  [4849/17668] intraday_13497.csv.gz  in=269,346,568 out=54,356,442 elapsed=95.3s

  [4850/17668] intraday_13500.csv.gz  in=269,347,150 out=54,357,024 elapsed=95.3s

  [4851/17668] intraday_1350.csv.gz  in=269,358,586 out=54,357,024 elapsed=95.3s

  [4852/17668] intraday_13502.csv.gz  in=269,359,313 out=54,357,751 elapsed=95.3s

  [4853/17668] intraday_13501.csv.gz  in=269,360,802 out=54,359,214 elapsed=95.3s

  [4854/17668] intraday_13503.csv.gz  in=269,361,688 out=54,360,100 elapsed=95.3s

  [4855/17668] intraday_13504.csv.gz  in=269,362,190 out=54,360,602 elapsed=95.3s

  [4856/17668] intraday_13506.csv.gz  in=269,362,473 out=54,360,885 elapsed=95.3s

  [4857/17668] intraday_13505.csv.gz  in=269,362,816 out=54,361,228 elapsed=95.3s

  [4858/17668] intraday_13507.csv.gz  in=269,363,614 out=54,362,026 elapsed=95.3s

  [4859/17668] intraday_13509.csv.gz  in=269,363,889 out=54,362,301 elapsed=95.3s

  [4860/17668] intraday_13511.csv.gz  in=269,364,298 out=54,362,710 elapsed=95.3s

  [4861/17668] intraday_13510.csv.gz  in=269,364,960 out=54,363,372 elapsed=95.3s

  [4862/17668] intraday_1351.csv.gz  in=269,380,186 out=54,363,372 elapsed=95.4s

  [4863/17668] intraday_13512.csv.gz  in=269,380,477 out=54,363,663 elapsed=95.4s

  [4864/17668] intraday_13508.csv.gz  in=269,405,315 out=54,377,690 elapsed=95.4s

  [4865/17668] intraday_13513.csv.gz  in=269,405,487 out=54,377,862 elapsed=95.4s

  [4866/17668] intraday_13514.csv.gz  in=269,405,912 out=54,378,287 elapsed=95.4s

  [4867/17668] intraday_13516.csv.gz  in=269,406,528 out=54,378,903 elapsed=95.4s

  [4868/17668] intraday_13515.csv.gz  in=269,406,792 out=54,379,167 elapsed=95.4s

  [4869/17668] intraday_13517.csv.gz  in=269,406,913 out=54,379,288 elapsed=95.4s

  [4870/17668] intraday_13518.csv.gz  in=269,407,034 out=54,379,409 elapsed=95.4s

  [4871/17668] intraday_13519.csv.gz  in=269,407,413 out=54,379,788 elapsed=95.4s

  [4872/17668] intraday_13520.csv.gz  in=269,408,518 out=54,380,893 elapsed=95.4s

  [4873/17668] intraday_13521.csv.gz  in=269,409,134 out=54,381,509 elapsed=95.4s

  [4874/17668] intraday_13523.csv.gz  in=269,409,408 out=54,381,783 elapsed=95.4s

  [4875/17668] intraday_13522.csv.gz  in=269,410,062 out=54,382,437 elapsed=95.4s

  [4876/17668] intraday_13524.csv.gz  in=269,410,563 out=54,382,938 elapsed=95.4s

  [4877/17668] intraday_1352.csv.gz  in=269,424,045 out=54,382,938 elapsed=95.4s

  [4878/17668] intraday_13525.csv.gz  in=269,424,143 out=54,383,036 elapsed=95.4s

  [4879/17668] intraday_13526.csv.gz  in=269,425,233 out=54,384,126 elapsed=95.5s

  [4880/17668] intraday_13527.csv.gz  in=269,425,452 out=54,384,345 elapsed=95.5s

  [4881/17668] intraday_13528.csv.gz  in=269,425,816 out=54,384,709 elapsed=95.5s

  [4882/17668] intraday_13529.csv.gz  in=269,425,989 out=54,384,882 elapsed=95.5s

  [4883/17668] intraday_13531.csv.gz  in=269,427,188 out=54,386,081 elapsed=95.5s

  [4884/17668] intraday_13530.csv.gz  in=269,427,622 out=54,386,515 elapsed=95.5s

  [4885/17668] intraday_13532.csv.gz  in=269,428,407 out=54,387,300 elapsed=95.5s

  [4886/17668] intraday_13534.csv.gz  in=269,429,349 out=54,388,242 elapsed=95.5s

  [4887/17668] intraday_1353.csv.gz  in=269,445,675 out=54,388,242 elapsed=95.5s

  [4888/17668] intraday_13533.csv.gz  in=269,446,961 out=54,389,528 elapsed=95.5s

  [4889/17668] intraday_13536.csv.gz  in=269,447,729 out=54,390,296 elapsed=95.5s

  [4890/17668] intraday_13537.csv.gz  in=269,448,151 out=54,390,718 elapsed=95.5s

  [4891/17668] intraday_13538.csv.gz  in=269,448,879 out=54,391,446 elapsed=95.5s

  [4892/17668] intraday_13535.csv.gz  in=269,450,177 out=54,392,744 elapsed=95.5s

  [4893/17668] intraday_13539.csv.gz  in=269,450,356 out=54,392,923 elapsed=95.5s

  [4894/17668] intraday_13540.csv.gz  in=269,450,564 out=54,393,131 elapsed=95.5s

  [4895/17668] intraday_13541.csv.gz  in=269,450,844 out=54,393,411 elapsed=95.6s

  [4896/17668] intraday_1354.csv.gz  in=269,464,164 out=54,393,411 elapsed=95.6s

  [4897/17668] intraday_13543.csv.gz  in=269,464,334 out=54,393,581 elapsed=95.6s

  [4898/17668] intraday_13544.csv.gz  in=269,464,921 out=54,394,168 elapsed=95.6s

  [4899/17668] intraday_13542.csv.gz  in=269,465,102 out=54,394,349 elapsed=95.6s

  [4900/17668] intraday_13546.csv.gz  in=269,465,284 out=54,394,531 elapsed=95.6s

  [4901/17668] intraday_13545.csv.gz  in=269,466,135 out=54,395,382 elapsed=95.6s

  [4902/17668] intraday_13547.csv.gz  in=269,466,527 out=54,395,774 elapsed=95.6s

  [4903/17668] intraday_13548.csv.gz  in=269,467,004 out=54,396,251 elapsed=95.6s

  [4904/17668] intraday_13549.csv.gz  in=269,467,377 out=54,396,624 elapsed=95.6s

  [4905/17668] intraday_13550.csv.gz  in=269,467,971 out=54,397,218 elapsed=95.6s

  [4906/17668] intraday_13551.csv.gz  in=269,468,152 out=54,397,399 elapsed=95.6s

  [4907/17668] intraday_13552.csv.gz  in=269,468,347 out=54,397,594 elapsed=95.6s

  [4908/17668] intraday_13553.csv.gz  in=269,468,812 out=54,398,059 elapsed=95.6s

  [4909/17668] intraday_13554.csv.gz  in=269,469,051 out=54,398,298 elapsed=95.6s

  [4910/17668] intraday_1355.csv.gz  in=269,481,556 out=54,398,298 elapsed=95.6s

  [4911/17668] intraday_13555.csv.gz  in=269,482,263 out=54,399,005 elapsed=95.6s

  [4912/17668] intraday_13557.csv.gz  in=269,482,682 out=54,399,424 elapsed=95.6s

  [4913/17668] intraday_13558.csv.gz  in=269,483,013 out=54,399,755 elapsed=95.6s

  [4914/17668] intraday_13556.csv.gz  in=269,483,328 out=54,400,070 elapsed=95.6s

  [4915/17668] intraday_13559.csv.gz  in=269,483,845 out=54,400,587 elapsed=95.6s

  [4916/17668] intraday_13562.csv.gz  in=269,483,928 out=54,400,670 elapsed=95.7s

  [4917/17668] intraday_13561.csv.gz  in=269,484,547 out=54,401,289 elapsed=95.7s

  [4918/17668] intraday_13560.csv.gz  in=269,486,118 out=54,402,288 elapsed=95.7s

  [4919/17668] intraday_1356.csv.gz  in=269,501,306 out=54,402,288 elapsed=95.7s

  [4920/17668] intraday_13565.csv.gz  in=269,525,968 out=54,426,950 elapsed=95.7s

  [4921/17668] intraday_13564.csv.gz  in=269,551,202 out=54,452,184 elapsed=95.8s

  [4922/17668] intraday_13567.csv.gz  in=269,576,506 out=54,477,488 elapsed=95.8s

  [4923/17668] intraday_13566.csv.gz  in=269,599,361 out=54,500,343 elapsed=95.8s

  [4924/17668] intraday_13563.csv.gz  in=269,632,169 out=54,533,151 elapsed=95.8s

  [4925/17668] intraday_1357.csv.gz  in=269,645,549 out=54,533,151 elapsed=95.8s

  [4926/17668] intraday_13568.csv.gz  in=269,676,879 out=54,564,481 elapsed=95.9s

  [4927/17668] intraday_13569.csv.gz  in=269,705,114 out=54,592,716 elapsed=95.9s

  [4928/17668] intraday_13570.csv.gz  in=269,726,756 out=54,614,358 elapsed=95.9s

  [4929/17668] intraday_13572.csv.gz  in=269,752,534 out=54,640,136 elapsed=95.9s

  [4930/17668] intraday_13571.csv.gz  in=269,765,002 out=54,652,604 elapsed=95.9s

  [4931/17668] intraday_13573.csv.gz  in=269,794,324 out=54,681,926 elapsed=96.0s

  [4932/17668] intraday_13575.csv.gz  in=269,822,790 out=54,709,699 elapsed=96.0s

  [4933/17668] intraday_13574.csv.gz  in=269,840,393 out=54,727,302 elapsed=96.0s

  [4934/17668] intraday_13576.csv.gz  in=269,867,585 out=54,754,494 elapsed=96.0s

  [4935/17668] intraday_13577.csv.gz  in=269,893,083 out=54,779,992 elapsed=96.0s

  [4936/17668] intraday_13579.csv.gz  in=269,914,467 out=54,801,376 elapsed=96.0s

  [4937/17668] intraday_13578.csv.gz  in=269,936,559 out=54,823,468 elapsed=96.0s

  [4938/17668] intraday_1358.csv.gz  in=269,949,867 out=54,823,468 elapsed=96.0s

  [4939/17668] intraday_13581.csv.gz  in=269,952,158 out=54,825,759 elapsed=96.1s

  [4940/17668] intraday_13580.csv.gz  in=269,972,066 out=54,845,667 elapsed=96.1s

  [4941/17668] intraday_13585.csv.gz  in=269,994,431 out=54,868,032 elapsed=96.1s

  [4942/17668] intraday_13582.csv.gz  in=270,018,426 out=54,892,027 elapsed=96.1s

  [4943/17668] intraday_13584.csv.gz  in=270,040,704 out=54,914,305 elapsed=96.1s

  [4944/17668] intraday_13583.csv.gz  in=270,062,140 out=54,935,741 elapsed=96.1s

  [4945/17668] intraday_13587.csv.gz  in=270,089,002 out=54,962,603 elapsed=96.2s

  [4946/17668] intraday_13586.csv.gz  in=270,113,246 out=54,986,847 elapsed=96.2s

  [4947/17668] intraday_13588.csv.gz  in=270,143,047 out=55,016,648 elapsed=96.2s

  [4948/17668] intraday_1359.csv.gz  in=270,158,783 out=55,016,648 elapsed=96.2s

  [4949/17668] intraday_13589.csv.gz  in=270,187,049 out=55,044,914 elapsed=96.2s

  [4950/17668] intraday_13590.csv.gz  in=270,208,446 out=55,066,311 elapsed=96.3s

  [4951/17668] intraday_13591.csv.gz  in=270,230,015 out=55,087,880 elapsed=96.3s

  [4952/17668] intraday_13592.csv.gz  in=270,252,367 out=55,110,232 elapsed=96.3s

  [4953/17668] intraday_13593.csv.gz  in=270,275,433 out=55,133,298 elapsed=96.3s

  [4954/17668] intraday_13594.csv.gz  in=270,293,650 out=55,151,515 elapsed=96.3s

  [4955/17668] intraday_13595.csv.gz  in=270,316,332 out=55,173,588 elapsed=96.3s

  [4956/17668] intraday_13596.csv.gz  in=270,342,208 out=55,199,464 elapsed=96.4s

  [4957/17668] intraday_13597.csv.gz  in=270,364,205 out=55,221,461 elapsed=96.4s

  [4958/17668] intraday_13598.csv.gz  in=270,389,022 out=55,246,278 elapsed=96.4s

  [4959/17668] intraday_1360.csv.gz  in=270,403,396 out=55,246,278 elapsed=96.4s

  [4960/17668] intraday_13599.csv.gz  in=270,432,344 out=55,275,226 elapsed=96.4s

  [4961/17668] intraday_13600.csv.gz  in=270,457,419 out=55,300,301 elapsed=96.4s

  [4962/17668] intraday_13603.csv.gz  in=270,457,421 out=55,300,303 elapsed=96.4s

  [4963/17668] intraday_13601.csv.gz  in=270,479,583 out=55,322,465 elapsed=96.4s

  [4964/17668] intraday_13602.csv.gz  in=270,504,240 out=55,347,122 elapsed=96.4s

  [4965/17668] intraday_13604.csv.gz  in=270,522,378 out=55,365,260 elapsed=96.5s

  [4966/17668] intraday_13606.csv.gz  in=270,544,122 out=55,387,004 elapsed=96.5s

  [4967/17668] intraday_13605.csv.gz  in=270,573,004 out=55,415,886 elapsed=96.5s

  [4968/17668] intraday_13607.csv.gz  in=270,595,750 out=55,438,632 elapsed=96.5s

  [4969/17668] intraday_13608.csv.gz  in=270,620,893 out=55,463,775 elapsed=96.5s

  [4970/17668] intraday_1361.csv.gz  in=270,635,338 out=55,463,775 elapsed=96.5s

  [4971/17668] intraday_13609.csv.gz  in=270,658,117 out=55,486,554 elapsed=96.6s

  [4972/17668] intraday_13610.csv.gz  in=270,684,118 out=55,512,555 elapsed=96.6s

  [4973/17668] intraday_13611.csv.gz  in=270,705,089 out=55,533,526 elapsed=96.6s

  [4974/17668] intraday_13612.csv.gz  in=270,726,738 out=55,555,175 elapsed=96.6s

  [4975/17668] intraday_13613.csv.gz  in=270,752,665 out=55,581,102 elapsed=96.6s

  [4976/17668] intraday_13615.csv.gz  in=270,762,267 out=55,590,704 elapsed=96.6s

  [4977/17668] intraday_13616.csv.gz  in=270,763,102 out=55,591,539 elapsed=96.6s

  [4978/17668] intraday_13614.csv.gz  in=270,799,192 out=55,620,613 elapsed=96.7s

  [4979/17668] intraday_13617.csv.gz  in=270,823,037 out=55,644,458 elapsed=96.7s

  [4980/17668] intraday_1362.csv.gz  in=270,835,457 out=55,644,458 elapsed=96.7s

  [4981/17668] intraday_13618.csv.gz  in=270,867,528 out=55,676,529 elapsed=96.7s

  [4982/17668] intraday_13620.csv.gz  in=270,894,291 out=55,703,292 elapsed=96.7s

  [4983/17668] intraday_13619.csv.gz  in=270,922,431 out=55,731,432 elapsed=96.7s

  [4984/17668] intraday_13622.csv.gz  in=270,940,122 out=55,749,123 elapsed=96.7s

  [4985/17668] intraday_13621.csv.gz  in=270,962,541 out=55,771,542 elapsed=96.7s

  [4986/17668] intraday_13623.csv.gz  in=270,989,667 out=55,798,668 elapsed=96.8s

  [4987/17668] intraday_13625.csv.gz  in=271,015,358 out=55,824,359 elapsed=96.8s

  [4988/17668] intraday_13624.csv.gz  in=271,040,828 out=55,849,829 elapsed=96.8s

  [4989/17668] intraday_13626.csv.gz  in=271,065,923 out=55,874,924 elapsed=96.8s

  [4990/17668] intraday_13629.csv.gz  in=271,065,924 out=55,874,925 elapsed=96.8s

  [4991/17668] intraday_13628.csv.gz  in=271,077,080 out=55,886,081 elapsed=96.9s

  [4992/17668] intraday_1363.csv.gz  in=271,087,710 out=55,886,081 elapsed=96.9s

  [4993/17668] intraday_13630.csv.gz  in=271,107,721 out=55,906,092 elapsed=96.9s

  [4994/17668] intraday_13627.csv.gz  in=271,131,129 out=55,929,500 elapsed=96.9s

  [4995/17668] intraday_13631.csv.gz  in=271,155,129 out=55,953,500 elapsed=96.9s

  [4996/17668] intraday_13632.csv.gz  in=271,173,391 out=55,971,762 elapsed=96.9s

  [4997/17668] intraday_13634.csv.gz  in=271,199,547 out=55,997,918 elapsed=97.0s

  [4998/17668] intraday_13635.csv.gz  in=271,227,934 out=56,026,305 elapsed=97.0s

  [4999/17668] intraday_13633.csv.gz  in=271,251,663 out=56,050,034 elapsed=97.0s

  [5000/17668] intraday_13636.csv.gz  in=271,283,316 out=56,081,352 elapsed=97.0s

  [5001/17668] intraday_13637.csv.gz  in=271,313,798 out=56,111,834 elapsed=97.0s

  [5002/17668] intraday_1364.csv.gz  in=271,326,913 out=56,111,834 elapsed=97.0s

  [5003/17668] intraday_13638.csv.gz  in=271,350,345 out=56,135,266 elapsed=97.0s

  [5004/17668] intraday_13639.csv.gz  in=271,377,704 out=56,162,625 elapsed=97.0s

  [5005/17668] intraday_13641.csv.gz  in=271,378,548 out=56,163,469 elapsed=97.0s

  [5006/17668] intraday_13642.csv.gz  in=271,379,706 out=56,164,627 elapsed=97.0s

  [5007/17668] intraday_13640.csv.gz  in=271,401,706 out=56,186,627 elapsed=97.1s

  [5008/17668] intraday_13645.csv.gz  in=271,427,402 out=56,212,323 elapsed=97.1s

  [5009/17668] intraday_13643.csv.gz  in=271,454,453 out=56,239,374 elapsed=97.1s

  [5010/17668] intraday_13644.csv.gz  in=271,480,063 out=56,264,984 elapsed=97.1s

  [5011/17668] intraday_13646.csv.gz  in=271,504,341 out=56,289,262 elapsed=97.2s

  [5012/17668] intraday_13647.csv.gz  in=271,528,131 out=56,313,052 elapsed=97.2s

  [5013/17668] intraday_1365.csv.gz  in=271,539,675 out=56,313,052 elapsed=97.2s

  [5014/17668] intraday_13649.csv.gz  in=271,564,321 out=56,337,698 elapsed=97.2s

  [5015/17668] intraday_13648.csv.gz  in=271,588,842 out=56,362,219 elapsed=97.2s

  [5016/17668] intraday_13650.csv.gz  in=271,613,415 out=56,386,792 elapsed=97.2s

  [5017/17668] intraday_13651.csv.gz  in=271,634,834 out=56,408,211 elapsed=97.2s

  [5018/17668] intraday_13653.csv.gz  in=271,660,174 out=56,433,551 elapsed=97.3s

  [5019/17668] intraday_13652.csv.gz  in=271,685,554 out=56,458,931 elapsed=97.3s

  [5020/17668] intraday_13654.csv.gz  in=271,712,029 out=56,485,406 elapsed=97.3s

  [5021/17668] intraday_13655.csv.gz  in=271,738,700 out=56,512,077 elapsed=97.3s

  [5022/17668] intraday_13656.csv.gz  in=271,757,631 out=56,529,335 elapsed=97.3s

  [5023/17668] intraday_13657.csv.gz  in=271,768,051 out=56,539,755 elapsed=97.3s

  [5024/17668] intraday_1366.csv.gz  in=271,780,309 out=56,539,755 elapsed=97.4s

  [5025/17668] intraday_13659.csv.gz  in=271,805,735 out=56,565,181 elapsed=97.4s

  [5026/17668] intraday_13658.csv.gz  in=271,831,313 out=56,590,759 elapsed=97.4s

  [5027/17668] intraday_13660.csv.gz  in=271,854,706 out=56,614,152 elapsed=97.4s

  [5028/17668] intraday_13661.csv.gz  in=271,883,752 out=56,643,198 elapsed=97.4s

  [5029/17668] intraday_13662.csv.gz  in=271,916,434 out=56,675,880 elapsed=97.4s

  [5030/17668] intraday_13663.csv.gz  in=271,941,225 out=56,700,671 elapsed=97.4s

  [5031/17668] intraday_13664.csv.gz  in=271,971,555 out=56,731,001 elapsed=97.5s

  [5032/17668] intraday_13665.csv.gz  in=272,006,701 out=56,766,147 elapsed=97.5s

  [5033/17668] intraday_13667.csv.gz  in=272,009,939 out=56,769,385 elapsed=97.5s

  [5034/17668] intraday_13666.csv.gz  in=272,045,742 out=56,805,188 elapsed=97.5s

  [5035/17668] intraday_13668.csv.gz  in=272,057,374 out=56,816,820 elapsed=97.5s

  [5036/17668] intraday_1367.csv.gz  in=272,065,262 out=56,816,820 elapsed=97.5s

  [5037/17668] intraday_13670.csv.gz  in=272,082,966 out=56,834,524 elapsed=97.5s

  [5038/17668] intraday_13669.csv.gz  in=272,108,865 out=56,860,423 elapsed=97.6s

  [5039/17668] intraday_13672.csv.gz  in=272,131,175 out=56,882,733 elapsed=97.6s

  [5040/17668] intraday_13673.csv.gz  in=272,153,854 out=56,905,412 elapsed=97.6s

  [5041/17668] intraday_13671.csv.gz  in=272,181,905 out=56,933,463 elapsed=97.6s

  [5042/17668] intraday_13674.csv.gz  in=272,210,568 out=56,962,126 elapsed=97.6s

  [5043/17668] intraday_13676.csv.gz  in=272,229,605 out=56,981,163 elapsed=97.7s

  [5044/17668] intraday_13677.csv.gz  in=272,254,827 out=57,006,385 elapsed=97.7s

  [5045/17668] intraday_13678.csv.gz  in=272,278,780 out=57,030,338 elapsed=97.7s

  [5046/17668] intraday_13675.csv.gz  in=272,306,861 out=57,058,419 elapsed=97.7s

  [5047/17668] intraday_1368.csv.gz  in=272,317,920 out=57,058,419 elapsed=97.7s

  [5048/17668] intraday_13679.csv.gz  in=272,332,677 out=57,073,176 elapsed=97.7s

  [5049/17668] intraday_13681.csv.gz  in=272,334,454 out=57,074,953 elapsed=97.7s

  [5050/17668] intraday_13680.csv.gz  in=272,335,182 out=57,075,681 elapsed=97.7s

  [5051/17668] intraday_13683.csv.gz  in=272,359,623 out=57,100,122 elapsed=97.8s

  [5052/17668] intraday_13685.csv.gz  in=272,381,561 out=57,122,060 elapsed=97.8s

  [5053/17668] intraday_13682.csv.gz  in=272,436,075 out=57,165,054 elapsed=97.8s

  [5054/17668] intraday_13684.csv.gz  in=272,467,762 out=57,196,741 elapsed=97.8s

  [5055/17668] intraday_13687.csv.gz  in=272,493,847 out=57,222,826 elapsed=97.8s

  [5056/17668] intraday_13686.csv.gz  in=272,522,176 out=57,251,155 elapsed=97.9s

  [5057/17668] intraday_13688.csv.gz  in=272,545,396 out=57,274,375 elapsed=97.9s

  [5058/17668] intraday_1369.csv.gz  in=272,552,918 out=57,274,375 elapsed=97.9s

  [5059/17668] intraday_13690.csv.gz  in=272,565,845 out=57,287,302 elapsed=97.9s

  [5060/17668] intraday_13689.csv.gz  in=272,589,373 out=57,310,830 elapsed=97.9s

  [5061/17668] intraday_13692.csv.gz  in=272,602,999 out=57,324,456 elapsed=97.9s

  [5062/17668] intraday_13691.csv.gz  in=272,625,826 out=57,347,283 elapsed=97.9s

  [5063/17668] intraday_13694.csv.gz  in=272,658,041 out=57,377,526 elapsed=98.0s

  [5064/17668] intraday_13693.csv.gz  in=272,690,966 out=57,410,451 elapsed=98.0s

  [5065/17668] intraday_13695.csv.gz  in=272,721,145 out=57,439,734 elapsed=98.0s

  [5066/17668] intraday_13696.csv.gz  in=272,744,618 out=57,463,207 elapsed=98.0s

  [5067/17668] intraday_13697.csv.gz  in=272,767,103 out=57,485,692 elapsed=98.0s

  [5068/17668] intraday_1370.csv.gz  in=272,767,155 out=57,485,692 elapsed=98.1s

  [5069/17668] intraday_13698.csv.gz  in=272,796,195 out=57,514,732 elapsed=98.1s

  [5070/17668] intraday_13699.csv.gz  in=272,826,712 out=57,545,249 elapsed=98.1s

  [5071/17668] intraday_13700.csv.gz  in=272,849,040 out=57,567,577 elapsed=98.1s

  [5072/17668] intraday_13702.csv.gz  in=272,859,442 out=57,577,530 elapsed=98.1s

  [5073/17668] intraday_13701.csv.gz  in=272,884,519 out=57,602,607 elapsed=98.1s

  [5074/17668] intraday_13703.csv.gz  in=272,901,854 out=57,619,942 elapsed=98.1s

  [5075/17668] intraday_13704.csv.gz  in=272,930,743 out=57,648,831 elapsed=98.1s

  [5076/17668] intraday_13706.csv.gz  in=272,953,901 out=57,671,989 elapsed=98.2s

  [5077/17668] intraday_13705.csv.gz  in=272,972,500 out=57,690,588 elapsed=98.2s

  [5078/17668] intraday_1371.csv.gz  in=272,972,725 out=57,690,588 elapsed=98.2s

  [5079/17668] intraday_13708.csv.gz  in=272,997,124 out=57,714,987 elapsed=98.2s

  [5080/17668] intraday_13707.csv.gz  in=273,031,055 out=57,748,918 elapsed=98.2s

  [5081/17668] intraday_13709.csv.gz  in=273,055,941 out=57,773,804 elapsed=98.3s

  [5082/17668] intraday_13710.csv.gz  in=273,080,128 out=57,797,991 elapsed=98.3s

  [5083/17668] intraday_13712.csv.gz  in=273,103,425 out=57,821,288 elapsed=98.3s

  [5084/17668] intraday_13711.csv.gz  in=273,139,525 out=57,855,122 elapsed=98.4s

  [5085/17668] intraday_13713.csv.gz  in=273,168,645 out=57,884,242 elapsed=98.4s

  [5086/17668] intraday_13716.csv.gz  in=273,188,853 out=57,904,450 elapsed=98.4s

  [5087/17668] intraday_13715.csv.gz  in=273,197,586 out=57,913,183 elapsed=98.4s

  [5088/17668] intraday_13714.csv.gz  in=273,223,832 out=57,939,429 elapsed=98.4s

  [5089/17668] intraday_1372.csv.gz  in=273,223,850 out=57,939,429 elapsed=98.4s

  [5090/17668] intraday_13717.csv.gz  in=273,245,485 out=57,961,064 elapsed=98.4s

  [5091/17668] intraday_13718.csv.gz  in=273,276,607 out=57,992,186 elapsed=98.5s

  [5092/17668] intraday_13719.csv.gz  in=273,308,474 out=58,024,053 elapsed=98.5s

  [5093/17668] intraday_13721.csv.gz  in=273,329,843 out=58,045,422 elapsed=98.5s

  [5094/17668] intraday_13720.csv.gz  in=273,357,996 out=58,073,575 elapsed=98.5s

  [5095/17668] intraday_13723.csv.gz  in=273,382,565 out=58,098,144 elapsed=98.5s

  [5096/17668] intraday_13722.csv.gz  in=273,407,426 out=58,123,005 elapsed=98.6s

  [5097/17668] intraday_13725.csv.gz  in=273,431,781 out=58,147,360 elapsed=98.6s

  [5098/17668] intraday_13724.csv.gz  in=273,477,619 out=58,185,205 elapsed=98.6s

  [5099/17668] intraday_13726.csv.gz  in=273,499,511 out=58,207,097 elapsed=98.6s

  [5100/17668] intraday_13728.csv.gz  in=273,508,222 out=58,215,808 elapsed=98.6s

  [5101/17668] intraday_13727.csv.gz  in=273,527,239 out=58,234,825 elapsed=98.6s

  [5102/17668] intraday_1373.csv.gz  in=273,527,285 out=58,234,825 elapsed=98.6s

  [5103/17668] intraday_13729.csv.gz  in=273,550,239 out=58,257,779 elapsed=98.6s

  [5104/17668] intraday_13732.csv.gz  in=273,575,352 out=58,282,892 elapsed=98.7s

  [5105/17668] intraday_13731.csv.gz  in=273,604,791 out=58,312,331 elapsed=98.7s

  [5106/17668] intraday_13730.csv.gz  in=273,637,392 out=58,344,504 elapsed=98.7s

  [5107/17668] intraday_13734.csv.gz  in=273,664,513 out=58,371,625 elapsed=98.7s

  [5108/17668] intraday_13733.csv.gz  in=273,694,869 out=58,399,206 elapsed=98.7s

  [5109/17668] intraday_13735.csv.gz  in=273,715,929 out=58,420,266 elapsed=98.7s

  [5110/17668] intraday_13736.csv.gz  in=273,739,609 out=58,443,946 elapsed=98.8s

  [5111/17668] intraday_13738.csv.gz  in=273,760,900 out=58,465,237 elapsed=98.8s

  [5112/17668] intraday_13737.csv.gz  in=273,784,048 out=58,488,385 elapsed=98.8s

  [5113/17668] intraday_13739.csv.gz  in=273,813,177 out=58,517,514 elapsed=98.8s

  [5114/17668] intraday_1374.csv.gz  in=273,813,181 out=58,517,514 elapsed=98.8s

  [5115/17668] intraday_13740.csv.gz  in=273,828,568 out=58,532,901 elapsed=98.8s

  [5116/17668] intraday_13741.csv.gz  in=273,835,312 out=58,539,645 elapsed=98.8s

  [5117/17668] intraday_13742.csv.gz  in=273,859,205 out=58,563,538 elapsed=98.9s

  [5118/17668] intraday_13743.csv.gz  in=273,894,822 out=58,594,887 elapsed=98.9s

  [5119/17668] intraday_13744.csv.gz  in=273,917,856 out=58,617,921 elapsed=98.9s

  [5120/17668] intraday_13745.csv.gz  in=273,945,450 out=58,645,515 elapsed=98.9s

  [5121/17668] intraday_13746.csv.gz  in=273,980,622 out=58,678,610 elapsed=99.0s

  [5122/17668] intraday_13747.csv.gz  in=274,003,037 out=58,701,025 elapsed=99.0s

  [5123/17668] intraday_1375.csv.gz  in=274,003,099 out=58,701,025 elapsed=99.0s

  [5124/17668] intraday_13749.csv.gz  in=274,030,182 out=58,726,807 elapsed=99.0s

  [5125/17668] intraday_13748.csv.gz  in=274,054,134 out=58,750,759 elapsed=99.0s

  [5126/17668] intraday_13750.csv.gz  in=274,082,045 out=58,778,670 elapsed=99.1s

  [5127/17668] intraday_13751.csv.gz  in=274,112,879 out=58,809,504 elapsed=99.1s

  [5128/17668] intraday_13753.csv.gz  in=274,137,575 out=58,834,200 elapsed=99.1s

  [5129/17668] intraday_13752.csv.gz  in=274,171,186 out=58,865,889 elapsed=99.1s

  [5130/17668] intraday_13754.csv.gz  in=274,179,510 out=58,874,213 elapsed=99.1s

  [5131/17668] intraday_13755.csv.gz  in=274,204,666 out=58,899,369 elapsed=99.1s

  [5132/17668] intraday_13757.csv.gz  in=274,228,857 out=58,923,560 elapsed=99.1s

  [5133/17668] intraday_13756.csv.gz  in=274,255,195 out=58,949,898 elapsed=99.2s

  [5134/17668] intraday_1376.csv.gz  in=274,255,281 out=58,949,898 elapsed=99.2s

  [5135/17668] intraday_13758.csv.gz  in=274,281,346 out=58,975,963 elapsed=99.2s

  [5136/17668] intraday_13759.csv.gz  in=274,300,968 out=58,995,585 elapsed=99.2s

  [5137/17668] intraday_13760.csv.gz  in=274,325,124 out=59,019,741 elapsed=99.2s

  [5138/17668] intraday_13763.csv.gz  in=274,348,621 out=59,043,238 elapsed=99.3s

  [5139/17668] intraday_13762.csv.gz  in=274,372,189 out=59,066,806 elapsed=99.3s

  [5140/17668] intraday_13761.csv.gz  in=274,400,495 out=59,095,112 elapsed=99.3s

  [5141/17668] intraday_13764.csv.gz  in=274,419,065 out=59,113,682 elapsed=99.3s

  [5142/17668] intraday_13765.csv.gz  in=274,442,726 out=59,137,343 elapsed=99.3s

  [5143/17668] intraday_13768.csv.gz  in=274,443,417 out=59,138,034 elapsed=99.3s

  [5144/17668] intraday_13767.csv.gz  in=274,444,002 out=59,138,619 elapsed=99.3s

  [5145/17668] intraday_13766.csv.gz  in=274,475,071 out=59,169,688 elapsed=99.4s

  [5146/17668] intraday_1377.csv.gz  in=274,475,955 out=59,169,688 elapsed=99.4s

  [5147/17668] intraday_13769.csv.gz  in=274,497,328 out=59,191,061 elapsed=99.4s

  [5148/17668] intraday_13770.csv.gz  in=274,522,530 out=59,216,263 elapsed=99.4s

  [5149/17668] intraday_13772.csv.gz  in=274,548,951 out=59,242,684 elapsed=99.4s

  [5150/17668] intraday_13771.csv.gz  in=274,571,289 out=59,265,022 elapsed=99.4s

  [5151/17668] intraday_13774.csv.gz  in=274,595,009 out=59,288,742 elapsed=99.5s

  [5152/17668] intraday_13773.csv.gz  in=274,617,994 out=59,311,727 elapsed=99.5s

  [5153/17668] intraday_13776.csv.gz  in=274,643,238 out=59,336,971 elapsed=99.5s

  [5154/17668] intraday_13775.csv.gz  in=274,670,261 out=59,363,994 elapsed=99.5s

  [5155/17668] intraday_13777.csv.gz  in=274,695,500 out=59,389,233 elapsed=99.5s

  [5156/17668] intraday_13778.csv.gz  in=274,718,150 out=59,411,883 elapsed=99.5s

  [5157/17668] intraday_1378.csv.gz  in=274,734,532 out=59,411,883 elapsed=99.5s

  [5158/17668] intraday_13779.csv.gz  in=274,760,157 out=59,437,508 elapsed=99.6s

  [5159/17668] intraday_13783.csv.gz  in=274,760,164 out=59,437,515 elapsed=99.6s

  [5160/17668] intraday_13782.csv.gz  in=274,769,111 out=59,446,462 elapsed=99.6s

  [5161/17668] intraday_13780.csv.gz  in=274,793,553 out=59,470,904 elapsed=99.6s

  [5162/17668] intraday_13781.csv.gz  in=274,818,579 out=59,495,452 elapsed=99.6s

  [5163/17668] intraday_13784.csv.gz  in=274,845,360 out=59,522,233 elapsed=99.7s

  [5164/17668] intraday_13786.csv.gz  in=274,873,101 out=59,549,974 elapsed=99.7s

  [5165/17668] intraday_13785.csv.gz  in=274,898,264 out=59,575,137 elapsed=99.7s

  [5166/17668] intraday_13787.csv.gz  in=274,923,868 out=59,600,741 elapsed=99.7s

  [5167/17668] intraday_1379.csv.gz  in=274,938,482 out=59,600,741 elapsed=99.7s

  [5168/17668] intraday_13789.csv.gz  in=274,959,668 out=59,621,927 elapsed=99.8s

  [5169/17668] intraday_13788.csv.gz  in=274,992,088 out=59,654,347 elapsed=99.8s

  [5170/17668] intraday_13791.csv.gz  in=275,020,430 out=59,682,689 elapsed=99.8s

  [5171/17668] intraday_13790.csv.gz  in=275,046,711 out=59,707,746 elapsed=99.8s

  [5172/17668] intraday_13793.csv.gz  in=275,061,495 out=59,722,530 elapsed=99.8s

  [5173/17668] intraday_13792.csv.gz  in=275,091,000 out=59,752,035 elapsed=99.8s

  [5174/17668] intraday_13794.csv.gz  in=275,094,454 out=59,755,489 elapsed=99.8s

  [5175/17668] intraday_13795.csv.gz  in=275,122,520 out=59,783,555 elapsed=99.9s

  [5176/17668] intraday_13796.csv.gz  in=275,149,542 out=59,810,577 elapsed=99.9s

  [5177/17668] intraday_1380.csv.gz  in=275,162,503 out=59,810,577 elapsed=99.9s

  [5178/17668] intraday_13797.csv.gz  in=275,196,831 out=59,844,905 elapsed=99.9s

  [5179/17668] intraday_13799.csv.gz  in=275,225,842 out=59,873,219 elapsed=99.9s

  [5180/17668] intraday_13798.csv.gz  in=275,262,286 out=59,909,663 elapsed=99.9s

  [5181/17668] intraday_13801.csv.gz  in=275,284,448 out=59,931,825 elapsed=100.0s

  [5182/17668] intraday_13800.csv.gz  in=275,313,256 out=59,960,633 elapsed=100.0s

  [5183/17668] intraday_13803.csv.gz  in=275,333,249 out=59,980,626 elapsed=100.0s

  [5184/17668] intraday_13802.csv.gz  in=275,359,290 out=60,006,667 elapsed=100.0s

  [5185/17668] intraday_13805.csv.gz  in=275,376,954 out=60,024,331 elapsed=100.0s

  [5186/17668] intraday_13806.csv.gz  in=275,378,448 out=60,025,825 elapsed=100.0s

  [5187/17668] intraday_13804.csv.gz  in=275,405,510 out=60,052,887 elapsed=100.1s

  [5188/17668] intraday_13808.csv.gz  in=275,428,063 out=60,075,440 elapsed=100.1s

  [5189/17668] intraday_1381.csv.gz  in=275,442,969 out=60,075,440 elapsed=100.1s

  [5190/17668] intraday_13807.csv.gz  in=275,471,363 out=60,103,834 elapsed=100.1s

  [5191/17668] intraday_13809.csv.gz  in=275,495,109 out=60,127,580 elapsed=100.1s

  [5192/17668] intraday_13810.csv.gz  in=275,516,690 out=60,149,161 elapsed=100.1s

  [5193/17668] intraday_13812.csv.gz  in=275,540,833 out=60,173,304 elapsed=100.2s

  [5194/17668] intraday_13811.csv.gz  in=275,568,314 out=60,200,512 elapsed=100.2s

  [5195/17668] intraday_13813.csv.gz  in=275,594,376 out=60,226,574 elapsed=100.2s

  [5196/17668] intraday_13814.csv.gz  in=275,624,106 out=60,256,304 elapsed=100.2s

  [5197/17668] intraday_13818.csv.gz  in=275,625,911 out=60,258,109 elapsed=100.2s

  [5198/17668] intraday_13815.csv.gz  in=275,653,602 out=60,285,800 elapsed=100.2s

  [5199/17668] intraday_13816.csv.gz  in=275,680,811 out=60,313,009 elapsed=100.2s

  [5200/17668] intraday_13817.csv.gz  in=275,705,127 out=60,337,325 elapsed=100.3s

  [5201/17668] intraday_13819.csv.gz  in=275,714,226 out=60,346,424 elapsed=100.3s

  [5202/17668] intraday_1382.csv.gz  in=275,728,776 out=60,346,424 elapsed=100.3s

  [5203/17668] intraday_13820.csv.gz  in=275,757,210 out=60,374,088 elapsed=100.3s

  [5204/17668] intraday_13822.csv.gz  in=275,777,454 out=60,394,332 elapsed=100.3s

  [5205/17668] intraday_13821.csv.gz  in=275,796,396 out=60,413,274 elapsed=100.3s

  [5206/17668] intraday_13823.csv.gz  in=275,824,250 out=60,441,128 elapsed=100.3s

  [5207/17668] intraday_13824.csv.gz  in=275,840,189 out=60,457,067 elapsed=100.4s

  [5208/17668] intraday_13826.csv.gz  in=275,852,257 out=60,469,135 elapsed=100.4s

  [5209/17668] intraday_13825.csv.gz  in=275,863,889 out=60,480,767 elapsed=100.4s

  [5210/17668] intraday_13827.csv.gz  in=275,875,245 out=60,492,016 elapsed=100.4s

  [5211/17668] intraday_13828.csv.gz  in=275,886,461 out=60,503,232 elapsed=100.4s

  [5212/17668] intraday_1383.csv.gz  in=275,901,381 out=60,503,232 elapsed=100.4s

  [5213/17668] intraday_13829.csv.gz  in=275,914,898 out=60,516,749 elapsed=100.4s

  [5214/17668] intraday_13830.csv.gz  in=275,927,300 out=60,529,151 elapsed=100.4s

  [5215/17668] intraday_13833.csv.gz  in=275,927,622 out=60,529,473 elapsed=100.5s

  [5216/17668] intraday_13832.csv.gz  in=275,931,466 out=60,533,317 elapsed=100.5s

  [5217/17668] intraday_13831.csv.gz  in=275,942,678 out=60,544,529 elapsed=100.5s

  [5218/17668] intraday_13834.csv.gz  in=275,943,728 out=60,545,579 elapsed=100.5s

  [5219/17668] intraday_13835.csv.gz  in=275,954,516 out=60,556,367 elapsed=100.5s

  [5220/17668] intraday_13838.csv.gz  in=275,964,598 out=60,566,449 elapsed=100.5s

  [5221/17668] intraday_13837.csv.gz  in=275,973,692 out=60,575,543 elapsed=100.5s

  [5222/17668] intraday_13836.csv.gz  in=275,987,764 out=60,589,615 elapsed=100.5s

  [5223/17668] intraday_13839.csv.gz  in=276,004,687 out=60,606,538 elapsed=100.5s

  [5224/17668] intraday_1384.csv.gz  in=276,018,163 out=60,606,538 elapsed=100.5s

  [5225/17668] intraday_13840.csv.gz  in=276,032,386 out=60,620,761 elapsed=100.6s

  [5226/17668] intraday_13841.csv.gz  in=276,042,529 out=60,630,904 elapsed=100.6s

  [5227/17668] intraday_13842.csv.gz  in=276,054,437 out=60,642,812 elapsed=100.6s

  [5228/17668] intraday_13843.csv.gz  in=276,069,912 out=60,658,287 elapsed=100.6s

  [5229/17668] intraday_13845.csv.gz  in=276,083,894 out=60,672,269 elapsed=100.6s

  [5230/17668] intraday_13844.csv.gz  in=276,095,228 out=60,683,603 elapsed=100.6s

  [5231/17668] intraday_13847.csv.gz  in=276,095,401 out=60,683,776 elapsed=100.7s

  [5232/17668] intraday_13846.csv.gz  in=276,101,809 out=60,690,184 elapsed=100.7s

  [5233/17668] intraday_13849.csv.gz  in=276,113,737 out=60,702,112 elapsed=100.7s

  [5234/17668] intraday_1385.csv.gz  in=276,127,083 out=60,702,112 elapsed=100.7s

  [5235/17668] intraday_13848.csv.gz  in=276,136,314 out=60,711,343 elapsed=100.7s

  [5236/17668] intraday_13850.csv.gz  in=276,148,183 out=60,723,212 elapsed=100.7s

  [5237/17668] intraday_13853.csv.gz  in=276,161,045 out=60,736,074 elapsed=100.7s

  [5238/17668] intraday_13852.csv.gz  in=276,176,396 out=60,751,425 elapsed=100.8s

  [5239/17668] intraday_13851.csv.gz  in=276,189,821 out=60,764,850 elapsed=100.8s

  [5240/17668] intraday_13854.csv.gz  in=276,199,273 out=60,774,302 elapsed=100.8s

  [5241/17668] intraday_13855.csv.gz  in=276,212,046 out=60,787,075 elapsed=100.8s

  [5242/17668] intraday_13856.csv.gz  in=276,223,216 out=60,798,245 elapsed=100.8s

  [5243/17668] intraday_13857.csv.gz  in=276,234,953 out=60,809,982 elapsed=100.8s

  [5244/17668] intraday_13858.csv.gz  in=276,246,285 out=60,821,314 elapsed=100.8s

  [5245/17668] intraday_13859.csv.gz  in=276,257,194 out=60,832,223 elapsed=100.8s

  [5246/17668] intraday_1386.csv.gz  in=276,271,621 out=60,832,223 elapsed=100.8s

  [5247/17668] intraday_13861.csv.gz  in=276,281,096 out=60,841,698 elapsed=100.8s

  [5248/17668] intraday_13860.csv.gz  in=276,292,190 out=60,852,792 elapsed=100.9s

  [5249/17668] intraday_13863.csv.gz  in=276,303,149 out=60,863,751 elapsed=100.9s

  [5250/17668] intraday_13862.csv.gz  in=276,314,001 out=60,874,603 elapsed=100.9s

  [5251/17668] intraday_13865.csv.gz  in=276,325,733 out=60,886,335 elapsed=100.9s

  [5252/17668] intraday_13866.csv.gz  in=276,339,857 out=60,900,459 elapsed=100.9s

  [5253/17668] intraday_13864.csv.gz  in=276,355,009 out=60,915,611 elapsed=100.9s

  [5254/17668] intraday_13867.csv.gz  in=276,364,151 out=60,924,750 elapsed=100.9s

  [5255/17668] intraday_13868.csv.gz  in=276,364,483 out=60,925,082 elapsed=100.9s

  [5256/17668] intraday_13869.csv.gz  in=276,373,713 out=60,934,312 elapsed=101.0s

  [5257/17668] intraday_13870.csv.gz  in=276,384,765 out=60,945,364 elapsed=101.0s

  [5258/17668] intraday_13871.csv.gz  in=276,395,815 out=60,956,414 elapsed=101.0s

  [5259/17668] intraday_1387.csv.gz  in=276,411,122 out=60,956,414 elapsed=101.0s

  [5260/17668] intraday_13872.csv.gz  in=276,423,466 out=60,968,758 elapsed=101.0s

  [5261/17668] intraday_13873.csv.gz  in=276,435,947 out=60,981,239 elapsed=101.0s

  [5262/17668] intraday_13874.csv.gz  in=276,448,525 out=60,993,817 elapsed=101.1s

  [5263/17668] intraday_13875.csv.gz  in=276,460,101 out=61,005,393 elapsed=101.1s

  [5264/17668] intraday_13876.csv.gz  in=276,470,526 out=61,015,818 elapsed=101.1s

  [5265/17668] intraday_13877.csv.gz  in=276,482,608 out=61,027,900 elapsed=101.1s

  [5266/17668] intraday_13878.csv.gz  in=276,493,754 out=61,038,858 elapsed=101.1s

  [5267/17668] intraday_13879.csv.gz  in=276,505,344 out=61,050,448 elapsed=101.1s

  [5268/17668] intraday_1388.csv.gz  in=276,515,734 out=61,050,448 elapsed=101.1s

  [5269/17668] intraday_13880.csv.gz  in=276,526,991 out=61,061,705 elapsed=101.1s

  [5270/17668] intraday_13881.csv.gz  in=276,532,568 out=61,067,282 elapsed=101.1s

  [5271/17668] intraday_13882.csv.gz  in=276,542,970 out=61,077,684 elapsed=101.2s

  [5272/17668] intraday_13883.csv.gz  in=276,552,888 out=61,087,602 elapsed=101.2s

  [5273/17668] intraday_13884.csv.gz  in=276,566,280 out=61,100,994 elapsed=101.2s

  [5274/17668] intraday_13885.csv.gz  in=276,579,140 out=61,113,854 elapsed=101.2s

  [5275/17668] intraday_13888.csv.gz  in=276,590,278 out=61,124,992 elapsed=101.2s

  [5276/17668] intraday_13887.csv.gz  in=276,601,764 out=61,136,478 elapsed=101.2s

  [5277/17668] intraday_13886.csv.gz  in=276,616,183 out=61,150,897 elapsed=101.2s

  [5278/17668] intraday_13889.csv.gz  in=276,626,025 out=61,160,739 elapsed=101.2s

  [5279/17668] intraday_1389.csv.gz  in=276,638,848 out=61,160,739 elapsed=101.2s

  [5280/17668] intraday_13891.csv.gz  in=276,650,722 out=61,172,613 elapsed=101.3s

  [5281/17668] intraday_13892.csv.gz  in=276,651,796 out=61,173,687 elapsed=101.3s

  [5282/17668] intraday_13890.csv.gz  in=276,664,712 out=61,186,603 elapsed=101.3s

  [5283/17668] intraday_13893.csv.gz  in=276,668,829 out=61,190,720 elapsed=101.3s

  [5284/17668] intraday_13894.csv.gz  in=276,678,947 out=61,200,838 elapsed=101.3s

  [5285/17668] intraday_13895.csv.gz  in=276,692,465 out=61,214,356 elapsed=101.3s

  [5286/17668] intraday_13896.csv.gz  in=276,703,149 out=61,225,040 elapsed=101.3s

  [5287/17668] intraday_13897.csv.gz  in=276,714,285 out=61,236,176 elapsed=101.3s

  [5288/17668] intraday_13898.csv.gz  in=276,724,762 out=61,246,653 elapsed=101.4s

  [5289/17668] intraday_13899.csv.gz  in=276,735,309 out=61,257,200 elapsed=101.4s

  [5290/17668] intraday_1390.csv.gz  in=276,750,759 out=61,257,200 elapsed=101.4s

  [5291/17668] intraday_13900.csv.gz  in=276,762,791 out=61,269,232 elapsed=101.4s

  [5292/17668] intraday_13901.csv.gz  in=276,775,291 out=61,281,732 elapsed=101.4s

  [5293/17668] intraday_13902.csv.gz  in=276,792,713 out=61,299,154 elapsed=101.4s

  [5294/17668] intraday_13903.csv.gz  in=276,805,254 out=61,311,695 elapsed=101.4s

  [5295/17668] intraday_13905.csv.gz  in=276,816,051 out=61,322,492 elapsed=101.4s

  [5296/17668] intraday_13904.csv.gz  in=276,827,318 out=61,333,759 elapsed=101.5s

  [5297/17668] intraday_13906.csv.gz  in=276,838,474 out=61,344,915 elapsed=101.5s

  [5298/17668] intraday_13907.csv.gz  in=276,850,931 out=61,357,372 elapsed=101.5s

  [5299/17668] intraday_13908.csv.gz  in=276,862,653 out=61,369,094 elapsed=101.5s

  [5300/17668] intraday_13909.csv.gz  in=276,871,981 out=61,378,422 elapsed=101.5s

  [5301/17668] intraday_1391.csv.gz  in=276,883,694 out=61,378,422 elapsed=101.5s

  [5302/17668] intraday_13910.csv.gz  in=276,896,865 out=61,391,593 elapsed=101.5s

  [5303/17668] intraday_13912.csv.gz  in=276,907,832 out=61,402,560 elapsed=101.5s

  [5304/17668] intraday_13911.csv.gz  in=276,918,688 out=61,413,416 elapsed=101.5s

  [5305/17668] intraday_13913.csv.gz  in=276,931,015 out=61,425,743 elapsed=101.6s

  [5306/17668] intraday_13914.csv.gz  in=276,942,792 out=61,437,520 elapsed=101.6s

  [5307/17668] intraday_13916.csv.gz  in=276,949,371 out=61,444,099 elapsed=101.6s

  [5308/17668] intraday_13915.csv.gz  in=276,961,274 out=61,456,002 elapsed=101.6s

  [5309/17668] intraday_13917.csv.gz  in=276,962,247 out=61,456,975 elapsed=101.6s

  [5310/17668] intraday_13918.csv.gz  in=276,975,084 out=61,469,812 elapsed=101.6s

  [5311/17668] intraday_13919.csv.gz  in=276,987,708 out=61,482,436 elapsed=101.6s

  [5312/17668] intraday_1392.csv.gz  in=276,998,659 out=61,482,436 elapsed=101.6s

  [5313/17668] intraday_13920.csv.gz  in=277,008,683 out=61,492,460 elapsed=101.7s

  [5314/17668] intraday_13922.csv.gz  in=277,019,790 out=61,503,567 elapsed=101.7s

  [5315/17668] intraday_13921.csv.gz  in=277,031,671 out=61,515,448 elapsed=101.7s

  [5316/17668] intraday_13924.csv.gz  in=277,042,044 out=61,525,821 elapsed=101.7s

  [5317/17668] intraday_13925.csv.gz  in=277,052,843 out=61,536,620 elapsed=101.7s

  [5318/17668] intraday_13923.csv.gz  in=277,067,802 out=61,551,579 elapsed=101.7s

  [5319/17668] intraday_13926.csv.gz  in=277,080,558 out=61,564,335 elapsed=101.7s

  [5320/17668] intraday_13927.csv.gz  in=277,095,510 out=61,579,287 elapsed=101.7s

  [5321/17668] intraday_13928.csv.gz  in=277,107,552 out=61,591,329 elapsed=101.8s

  [5322/17668] intraday_1393.csv.gz  in=277,121,816 out=61,591,329 elapsed=101.8s

  [5323/17668] intraday_13929.csv.gz  in=277,134,671 out=61,604,184 elapsed=101.8s

  [5324/17668] intraday_13930.csv.gz  in=277,147,607 out=61,617,120 elapsed=101.8s

  [5325/17668] intraday_13931.csv.gz  in=277,160,615 out=61,630,128 elapsed=101.8s

  [5326/17668] intraday_13932.csv.gz  in=277,173,214 out=61,642,727 elapsed=101.8s

  [5327/17668] intraday_13933.csv.gz  in=277,187,053 out=61,656,566 elapsed=101.8s

  [5328/17668] intraday_13934.csv.gz  in=277,204,774 out=61,674,287 elapsed=101.8s

  [5329/17668] intraday_13935.csv.gz  in=277,216,411 out=61,685,924 elapsed=101.8s

  [5330/17668] intraday_13937.csv.gz  in=277,228,376 out=61,697,889 elapsed=101.9s

  [5331/17668] intraday_13936.csv.gz  in=277,242,624 out=61,712,137 elapsed=101.9s

  [5332/17668] intraday_13938.csv.gz  in=277,256,147 out=61,725,660 elapsed=101.9s

  [5333/17668] intraday_13939.csv.gz  in=277,265,911 out=61,735,424 elapsed=101.9s

  [5334/17668] intraday_1394.csv.gz  in=277,279,110 out=61,735,424 elapsed=101.9s

  [5335/17668] intraday_13940.csv.gz  in=277,290,447 out=61,746,761 elapsed=101.9s

  [5336/17668] intraday_13942.csv.gz  in=277,302,106 out=61,758,420 elapsed=101.9s

  [5337/17668] intraday_13941.csv.gz  in=277,314,354 out=61,770,668 elapsed=101.9s

  [5338/17668] intraday_13943.csv.gz  in=277,325,229 out=61,781,543 elapsed=101.9s

  [5339/17668] intraday_13946.csv.gz  in=277,337,401 out=61,793,715 elapsed=102.0s

  [5340/17668] intraday_13944.csv.gz  in=277,352,112 out=61,808,426 elapsed=102.0s

  [5341/17668] intraday_13945.csv.gz  in=277,361,994 out=61,818,308 elapsed=102.0s

  [5342/17668] intraday_13947.csv.gz  in=277,372,968 out=61,829,282 elapsed=102.0s

  [5343/17668] intraday_13948.csv.gz  in=277,385,423 out=61,841,737 elapsed=102.0s

  [5344/17668] intraday_1395.csv.gz  in=277,399,054 out=61,841,737 elapsed=102.0s

  [5345/17668] intraday_13949.csv.gz  in=277,411,612 out=61,854,295 elapsed=102.0s

  [5346/17668] intraday_13951.csv.gz  in=277,425,118 out=61,867,801 elapsed=102.0s

  [5347/17668] intraday_13952.csv.gz  in=277,438,146 out=61,880,829 elapsed=102.1s

  [5348/17668] intraday_13950.csv.gz  in=277,450,767 out=61,893,450 elapsed=102.1s

  [5349/17668] intraday_13953.csv.gz  in=277,462,764 out=61,905,447 elapsed=102.1s

  [5350/17668] intraday_13954.csv.gz  in=277,475,169 out=61,917,852 elapsed=102.1s

  [5351/17668] intraday_13955.csv.gz  in=277,485,974 out=61,928,657 elapsed=102.1s

  [5352/17668] intraday_13956.csv.gz  in=277,499,462 out=61,942,145 elapsed=102.1s

  [5353/17668] intraday_13957.csv.gz  in=277,510,147 out=61,952,830 elapsed=102.1s

  [5354/17668] intraday_13958.csv.gz  in=277,522,488 out=61,965,171 elapsed=102.1s

  [5355/17668] intraday_1396.csv.gz  in=277,535,234 out=61,965,171 elapsed=102.2s

  [5356/17668] intraday_13959.csv.gz  in=277,546,376 out=61,976,313 elapsed=102.2s

  [5357/17668] intraday_13962.csv.gz  in=277,547,937 out=61,977,874 elapsed=102.2s

  [5358/17668] intraday_13960.csv.gz  in=277,556,626 out=61,986,563 elapsed=102.2s

  [5359/17668] intraday_13961.csv.gz  in=277,570,159 out=62,000,096 elapsed=102.2s

  [5360/17668] intraday_13964.csv.gz  in=277,571,725 out=62,001,662 elapsed=102.2s

  [5361/17668] intraday_13963.csv.gz  in=277,573,380 out=62,002,285 elapsed=102.2s

  [5362/17668] intraday_13965.csv.gz  in=277,573,540 out=62,002,445 elapsed=102.2s

  [5363/17668] intraday_13966.csv.gz  in=277,573,542 out=62,002,447 elapsed=102.2s

  [5364/17668] intraday_13968.csv.gz  in=277,573,676 out=62,002,581 elapsed=102.2s

  [5365/17668] intraday_13969.csv.gz  in=277,573,984 out=62,002,889 elapsed=102.2s

  [5366/17668] intraday_13970.csv.gz  in=277,574,100 out=62,003,005 elapsed=102.2s

  [5367/17668] intraday_13967.csv.gz  in=277,592,046 out=62,014,286 elapsed=102.2s

  [5368/17668] intraday_13972.csv.gz  in=277,592,653 out=62,014,893 elapsed=102.2s

  [5369/17668] intraday_1397.csv.gz  in=277,604,375 out=62,014,893 elapsed=102.2s

  [5370/17668] intraday_13971.csv.gz  in=277,605,463 out=62,015,858 elapsed=102.2s

  [5371/17668] intraday_13973.csv.gz  in=277,605,667 out=62,016,062 elapsed=102.2s

  [5372/17668] intraday_13975.csv.gz  in=277,605,698 out=62,016,093 elapsed=102.2s

  [5373/17668] intraday_13976.csv.gz  in=277,608,961 out=62,018,543 elapsed=102.3s

  [5374/17668] intraday_13974.csv.gz  in=277,629,932 out=62,033,355 elapsed=102.3s

  [5375/17668] intraday_13978.csv.gz  in=277,630,273 out=62,033,642 elapsed=102.3s

  [5376/17668] intraday_13977.csv.gz  in=277,634,188 out=62,036,840 elapsed=102.3s

  [5377/17668] intraday_13979.csv.gz  in=277,634,234 out=62,036,886 elapsed=102.3s

  [5378/17668] intraday_13981.csv.gz  in=277,634,282 out=62,036,934 elapsed=102.3s

  [5379/17668] intraday_13980.csv.gz  in=277,635,956 out=62,038,608 elapsed=102.3s

  [5380/17668] intraday_1398.csv.gz  in=277,649,861 out=62,038,608 elapsed=102.3s

  [5381/17668] intraday_13982.csv.gz  in=277,650,745 out=62,039,492 elapsed=102.3s

  [5382/17668] intraday_13983.csv.gz  in=277,650,770 out=62,039,517 elapsed=102.3s

  [5383/17668] intraday_13984.csv.gz  in=277,650,801 out=62,039,548 elapsed=102.3s

  [5384/17668] intraday_13985.csv.gz  in=277,650,965 out=62,039,712 elapsed=102.3s

  [5385/17668] intraday_13986.csv.gz  in=277,653,765 out=62,042,264 elapsed=102.3s

  [5386/17668] intraday_13987.csv.gz  in=277,653,906 out=62,042,405 elapsed=102.3s

  [5387/17668] intraday_13988.csv.gz  in=277,654,033 out=62,042,532 elapsed=102.3s

  [5388/17668] intraday_1399.csv.gz  in=277,666,779 out=62,042,532 elapsed=102.4s

  [5389/17668] intraday_13991.csv.gz  in=277,679,328 out=62,055,081 elapsed=102.6s

  [5390/17668] intraday_13990.csv.gz  in=277,694,650 out=62,070,403 elapsed=102.6s

  [5391/17668] intraday_13992.csv.gz  in=277,707,065 out=62,082,818 elapsed=102.6s

  [5392/17668] intraday_13989.csv.gz  in=277,737,479 out=62,098,526 elapsed=102.6s

  [5393/17668] intraday_13994.csv.gz  in=277,748,723 out=62,109,770 elapsed=102.6s

  [5394/17668] intraday_13993.csv.gz  in=277,759,518 out=62,120,565 elapsed=102.6s

  [5395/17668] intraday_13995.csv.gz  in=277,774,428 out=62,135,475 elapsed=102.6s

  [5396/17668] intraday_13996.csv.gz  in=277,786,744 out=62,147,791 elapsed=102.7s

  [5397/17668] intraday_13998.csv.gz  in=277,799,962 out=62,161,009 elapsed=102.7s

  [5398/17668] intraday_13997.csv.gz  in=277,811,393 out=62,172,440 elapsed=102.7s

  [5399/17668] intraday_13999.csv.gz  in=277,823,570 out=62,184,617 elapsed=102.7s

  [5400/17668] intraday_1400.csv.gz  in=277,842,977 out=62,184,617 elapsed=102.7s

  [5401/17668] intraday_14000.csv.gz  in=277,854,611 out=62,196,251 elapsed=102.7s

  [5402/17668] intraday_14002.csv.gz  in=277,866,042 out=62,207,682 elapsed=102.7s

  [5403/17668] intraday_14001.csv.gz  in=277,878,006 out=62,219,646 elapsed=102.7s

  [5404/17668] intraday_14004.csv.gz  in=277,889,074 out=62,230,714 elapsed=102.8s

  [5405/17668] intraday_14003.csv.gz  in=277,903,231 out=62,244,871 elapsed=102.8s

  [5406/17668] intraday_14006.csv.gz  in=277,907,428 out=62,249,068 elapsed=102.8s

  [5407/17668] intraday_14005.csv.gz  in=277,915,590 out=62,257,230 elapsed=102.8s

  [5408/17668] intraday_14007.csv.gz  in=277,926,794 out=62,268,434 elapsed=102.8s

  [5409/17668] intraday_14008.csv.gz  in=277,942,109 out=62,283,749 elapsed=102.8s

  [5410/17668] intraday_14009.csv.gz  in=277,954,104 out=62,295,744 elapsed=102.9s

  [5411/17668] intraday_1401.csv.gz  in=277,967,860 out=62,295,744 elapsed=102.9s

  [5412/17668] intraday_14010.csv.gz  in=277,981,793 out=62,309,677 elapsed=102.9s

  [5413/17668] intraday_14011.csv.gz  in=277,993,294 out=62,321,178 elapsed=102.9s

  [5414/17668] intraday_14014.csv.gz  in=278,003,486 out=62,331,370 elapsed=102.9s

  [5415/17668] intraday_14012.csv.gz  in=278,016,625 out=62,344,509 elapsed=102.9s

  [5416/17668] intraday_14013.csv.gz  in=278,026,302 out=62,354,186 elapsed=102.9s

  [5417/17668] intraday_14015.csv.gz  in=278,039,190 out=62,367,008 elapsed=102.9s

  [5418/17668] intraday_14016.csv.gz  in=278,051,263 out=62,379,081 elapsed=102.9s

  [5419/17668] intraday_14017.csv.gz  in=278,064,761 out=62,392,579 elapsed=102.9s

  [5420/17668] intraday_14019.csv.gz  in=278,077,844 out=62,405,662 elapsed=103.0s

  [5421/17668] intraday_1402.csv.gz  in=278,090,764 out=62,405,662 elapsed=103.0s

  [5422/17668] intraday_14018.csv.gz  in=278,105,975 out=62,420,873 elapsed=103.0s

  [5423/17668] intraday_14020.csv.gz  in=278,115,375 out=62,430,273 elapsed=103.0s

  [5424/17668] intraday_14022.csv.gz  in=278,118,012 out=62,432,910 elapsed=103.0s

  [5425/17668] intraday_14023.csv.gz  in=278,121,137 out=62,436,035 elapsed=103.0s

  [5426/17668] intraday_14021.csv.gz  in=278,134,200 out=62,449,098 elapsed=103.0s

  [5427/17668] intraday_14024.csv.gz  in=278,145,438 out=62,460,336 elapsed=103.0s

  [5428/17668] intraday_14025.csv.gz  in=278,157,612 out=62,472,510 elapsed=103.0s

  [5429/17668] intraday_14026.csv.gz  in=278,167,458 out=62,482,356 elapsed=103.1s

  [5430/17668] intraday_14027.csv.gz  in=278,178,172 out=62,493,070 elapsed=103.1s

  [5431/17668] intraday_14028.csv.gz  in=278,190,159 out=62,505,057 elapsed=103.1s

  [5432/17668] intraday_1403.csv.gz  in=278,201,244 out=62,505,057 elapsed=103.1s

  [5433/17668] intraday_14029.csv.gz  in=278,215,817 out=62,519,630 elapsed=103.1s

  [5434/17668] intraday_14030.csv.gz  in=278,226,960 out=62,530,773 elapsed=103.1s

  [5435/17668] intraday_14031.csv.gz  in=278,241,731 out=62,545,544 elapsed=103.1s

  [5436/17668] intraday_14032.csv.gz  in=278,253,618 out=62,557,431 elapsed=103.1s

  [5437/17668] intraday_14033.csv.gz  in=278,264,529 out=62,568,342 elapsed=103.1s

  [5438/17668] intraday_14034.csv.gz  in=278,278,080 out=62,581,893 elapsed=103.2s

  [5439/17668] intraday_14035.csv.gz  in=278,288,274 out=62,592,087 elapsed=103.2s

  [5440/17668] intraday_14036.csv.gz  in=278,299,007 out=62,602,820 elapsed=103.2s

  [5441/17668] intraday_14037.csv.gz  in=278,308,444 out=62,612,257 elapsed=103.2s

  [5442/17668] intraday_14039.csv.gz  in=278,320,896 out=62,624,709 elapsed=103.2s

  [5443/17668] intraday_14038.csv.gz  in=278,329,098 out=62,632,911 elapsed=103.2s

  [5444/17668] intraday_1404.csv.gz  in=278,344,370 out=62,632,911 elapsed=103.2s

  [5445/17668] intraday_14040.csv.gz  in=278,355,387 out=62,643,928 elapsed=103.2s

  [5446/17668] intraday_14041.csv.gz  in=278,366,677 out=62,655,218 elapsed=103.3s

  [5447/17668] intraday_14042.csv.gz  in=278,376,691 out=62,665,232 elapsed=103.3s

  [5448/17668] intraday_14043.csv.gz  in=278,388,392 out=62,676,933 elapsed=103.3s

  [5449/17668] intraday_14044.csv.gz  in=278,401,595 out=62,690,136 elapsed=103.3s

  [5450/17668] intraday_14046.csv.gz  in=278,414,789 out=62,703,330 elapsed=103.3s

  [5451/17668] intraday_14045.csv.gz  in=278,425,881 out=62,714,422 elapsed=103.3s

  [5452/17668] intraday_14047.csv.gz  in=278,436,148 out=62,724,689 elapsed=103.6s

  [5453/17668] intraday_1405.csv.gz  in=278,453,091 out=62,724,689 elapsed=103.6s

  [5454/17668] intraday_14049.csv.gz  in=278,463,618 out=62,735,216 elapsed=103.6s

  [5455/17668] intraday_14048.csv.gz  in=278,474,619 out=62,746,217 elapsed=103.6s

  [5456/17668] intraday_14052.csv.gz  in=278,479,909 out=62,751,507 elapsed=103.6s

  [5457/17668] intraday_14051.csv.gz  in=278,484,250 out=62,755,848 elapsed=103.6s

  [5458/17668] intraday_14050.csv.gz  in=278,498,581 out=62,770,179 elapsed=103.6s

  [5459/17668] intraday_14053.csv.gz  in=278,509,433 out=62,781,031 elapsed=103.6s

  [5460/17668] intraday_14054.csv.gz  in=278,520,316 out=62,791,914 elapsed=103.6s

  [5461/17668] intraday_14055.csv.gz  in=278,532,435 out=62,804,033 elapsed=103.6s

  [5462/17668] intraday_14056.csv.gz  in=278,545,639 out=62,817,237 elapsed=103.7s

  [5463/17668] intraday_14057.csv.gz  in=278,557,087 out=62,828,685 elapsed=103.7s

  [5464/17668] intraday_14059.csv.gz  in=278,567,652 out=62,839,250 elapsed=103.7s

  [5465/17668] intraday_14058.csv.gz  in=278,580,254 out=62,851,852 elapsed=103.7s

  [5466/17668] intraday_14060.csv.gz  in=278,590,782 out=62,862,380 elapsed=103.7s

  [5467/17668] intraday_1406.csv.gz  in=278,606,530 out=62,862,380 elapsed=103.7s

  [5468/17668] intraday_14061.csv.gz  in=278,621,265 out=62,877,115 elapsed=103.7s

  [5469/17668] intraday_14062.csv.gz  in=278,632,494 out=62,888,344 elapsed=103.7s

  [5470/17668] intraday_14063.csv.gz  in=278,644,152 out=62,900,002 elapsed=103.8s

  [5471/17668] intraday_14064.csv.gz  in=278,651,578 out=62,907,428 elapsed=103.8s

  [5472/17668] intraday_14065.csv.gz  in=278,653,442 out=62,909,292 elapsed=103.8s

  [5473/17668] intraday_14066.csv.gz  in=278,666,847 out=62,922,697 elapsed=103.8s

  [5474/17668] intraday_14068.csv.gz  in=278,680,121 out=62,935,971 elapsed=103.8s

  [5475/17668] intraday_14067.csv.gz  in=278,695,292 out=62,951,142 elapsed=103.8s

  [5476/17668] intraday_1407.csv.gz  in=278,710,414 out=62,951,142 elapsed=103.8s

  [5477/17668] intraday_14069.csv.gz  in=278,721,634 out=62,962,362 elapsed=103.9s

  [5478/17668] intraday_14070.csv.gz  in=278,732,305 out=62,973,033 elapsed=103.9s

  [5479/17668] intraday_14071.csv.gz  in=278,743,889 out=62,984,617 elapsed=103.9s

  [5480/17668] intraday_14072.csv.gz  in=278,758,092 out=62,998,820 elapsed=103.9s

  [5481/17668] intraday_14073.csv.gz  in=278,770,415 out=63,011,143 elapsed=103.9s

  [5482/17668] intraday_14074.csv.gz  in=278,779,770 out=63,020,498 elapsed=103.9s

  [5483/17668] intraday_14075.csv.gz  in=278,794,538 out=63,035,266 elapsed=103.9s

  [5484/17668] intraday_14076.csv.gz  in=278,805,461 out=63,046,189 elapsed=103.9s

  [5485/17668] intraday_14078.csv.gz  in=278,816,935 out=63,057,663 elapsed=103.9s

  [5486/17668] intraday_14077.csv.gz  in=278,828,957 out=63,069,685 elapsed=103.9s

  [5487/17668] intraday_1408.csv.gz  in=278,842,549 out=63,069,685 elapsed=104.0s

  [5488/17668] intraday_14079.csv.gz  in=278,854,092 out=63,081,228 elapsed=104.0s

  [5489/17668] intraday_14080.csv.gz  in=278,865,865 out=63,093,001 elapsed=104.0s

  [5490/17668] intraday_14081.csv.gz  in=278,878,833 out=63,105,969 elapsed=104.0s

  [5491/17668] intraday_14083.csv.gz  in=278,889,815 out=63,116,951 elapsed=104.0s

  [5492/17668] intraday_14082.csv.gz  in=278,900,676 out=63,127,812 elapsed=104.0s

  [5493/17668] intraday_14084.csv.gz  in=278,914,304 out=63,141,440 elapsed=104.0s

  [5494/17668] intraday_14085.csv.gz  in=278,926,911 out=63,154,047 elapsed=104.0s

  [5495/17668] intraday_14086.csv.gz  in=278,939,200 out=63,166,336 elapsed=104.0s

  [5496/17668] intraday_14087.csv.gz  in=278,950,651 out=63,177,787 elapsed=104.1s

  [5497/17668] intraday_1409.csv.gz  in=278,963,311 out=63,177,787 elapsed=104.1s

  [5498/17668] intraday_14089.csv.gz  in=278,978,811 out=63,193,287 elapsed=104.1s

  [5499/17668] intraday_14090.csv.gz  in=278,989,355 out=63,203,831 elapsed=104.1s

  [5500/17668] intraday_14091.csv.gz  in=279,000,952 out=63,215,428 elapsed=104.1s

  [5501/17668] intraday_14088.csv.gz  in=279,036,653 out=63,242,594 elapsed=104.1s

  [5502/17668] intraday_14092.csv.gz  in=279,049,944 out=63,255,885 elapsed=104.1s

  [5503/17668] intraday_14093.csv.gz  in=279,063,622 out=63,269,563 elapsed=104.1s

  [5504/17668] intraday_14095.csv.gz  in=279,077,502 out=63,283,443 elapsed=104.2s

  [5505/17668] intraday_14096.csv.gz  in=279,091,410 out=63,297,351 elapsed=104.2s

  [5506/17668] intraday_14097.csv.gz  in=279,103,946 out=63,309,887 elapsed=104.2s

  [5507/17668] intraday_14094.csv.gz  in=279,116,619 out=63,322,560 elapsed=104.2s

  [5508/17668] intraday_14098.csv.gz  in=279,129,677 out=63,335,618 elapsed=104.2s

  [5509/17668] intraday_1410.csv.gz  in=279,142,877 out=63,335,618 elapsed=104.2s

  [5510/17668] intraday_14099.csv.gz  in=279,159,266 out=63,352,007 elapsed=104.3s

  [5511/17668] intraday_14100.csv.gz  in=279,175,492 out=63,368,233 elapsed=104.3s

  [5512/17668] intraday_14102.csv.gz  in=279,190,303 out=63,383,044 elapsed=104.3s

  [5513/17668] intraday_14103.csv.gz  in=279,201,174 out=63,393,915 elapsed=104.3s

  [5514/17668] intraday_14101.csv.gz  in=279,214,623 out=63,407,364 elapsed=104.3s

  [5515/17668] intraday_14104.csv.gz  in=279,227,661 out=63,420,402 elapsed=104.3s

  [5516/17668] intraday_14105.csv.gz  in=279,237,552 out=63,430,293 elapsed=104.3s

  [5517/17668] intraday_14106.csv.gz  in=279,250,440 out=63,443,181 elapsed=104.3s

  [5518/17668] intraday_14108.csv.gz  in=279,263,611 out=63,456,352 elapsed=104.4s

  [5519/17668] intraday_14107.csv.gz  in=279,274,118 out=63,466,859 elapsed=104.4s

  [5520/17668] intraday_14109.csv.gz  in=279,284,391 out=63,477,132 elapsed=104.4s

  [5521/17668] intraday_1411.csv.gz  in=279,298,226 out=63,477,132 elapsed=104.4s

  [5522/17668] intraday_14111.csv.gz  in=279,308,153 out=63,487,059 elapsed=104.4s

  [5523/17668] intraday_14112.csv.gz  in=279,320,066 out=63,498,972 elapsed=104.4s

  [5524/17668] intraday_14110.csv.gz  in=279,336,350 out=63,515,256 elapsed=104.4s

  [5525/17668] intraday_14113.csv.gz  in=279,347,555 out=63,526,461 elapsed=104.4s

  [5526/17668] intraday_14114.csv.gz  in=279,361,152 out=63,540,058 elapsed=104.4s

  [5527/17668] intraday_14116.csv.gz  in=279,374,931 out=63,553,837 elapsed=104.5s

  [5528/17668] intraday_14115.csv.gz  in=279,386,197 out=63,565,103 elapsed=104.5s

  [5529/17668] intraday_14118.csv.gz  in=279,398,935 out=63,577,841 elapsed=104.5s

  [5530/17668] intraday_14117.csv.gz  in=279,413,786 out=63,592,692 elapsed=104.5s

  [5531/17668] intraday_1412.csv.gz  in=279,425,790 out=63,592,692 elapsed=104.5s

  [5532/17668] intraday_14119.csv.gz  in=279,438,675 out=63,605,577 elapsed=104.5s

  [5533/17668] intraday_14120.csv.gz  in=279,450,807 out=63,617,709 elapsed=104.5s

  [5534/17668] intraday_14121.csv.gz  in=279,461,663 out=63,628,565 elapsed=104.5s

  [5535/17668] intraday_14122.csv.gz  in=279,473,633 out=63,640,535 elapsed=104.6s

  [5536/17668] intraday_14123.csv.gz  in=279,483,948 out=63,650,850 elapsed=104.6s

  [5537/17668] intraday_14124.csv.gz  in=279,495,956 out=63,662,858 elapsed=104.6s

  [5538/17668] intraday_14125.csv.gz  in=279,507,305 out=63,674,207 elapsed=104.6s

  [5539/17668] intraday_14126.csv.gz  in=279,514,626 out=63,681,528 elapsed=104.6s

  [5540/17668] intraday_14127.csv.gz  in=279,528,195 out=63,695,097 elapsed=104.6s

  [5541/17668] intraday_14129.csv.gz  in=279,539,497 out=63,706,399 elapsed=104.6s

  [5542/17668] intraday_1413.csv.gz  in=279,553,239 out=63,706,399 elapsed=104.6s

  [5543/17668] intraday_14128.csv.gz  in=279,569,384 out=63,722,544 elapsed=104.6s

  [5544/17668] intraday_14130.csv.gz  in=279,582,011 out=63,735,171 elapsed=104.6s

  [5545/17668] intraday_14131.csv.gz  in=279,593,879 out=63,747,039 elapsed=104.7s

  [5546/17668] intraday_14134.csv.gz  in=279,607,424 out=63,760,584 elapsed=104.7s

  [5547/17668] intraday_14133.csv.gz  in=279,621,658 out=63,774,818 elapsed=104.7s

  [5548/17668] intraday_14135.csv.gz  in=279,632,558 out=63,785,718 elapsed=104.7s

  [5549/17668] intraday_14132.csv.gz  in=279,647,034 out=63,798,997 elapsed=104.7s

  [5550/17668] intraday_14136.csv.gz  in=279,659,505 out=63,811,468 elapsed=104.7s

  [5551/17668] intraday_14137.csv.gz  in=279,671,352 out=63,823,315 elapsed=104.8s

  [5552/17668] intraday_14138.csv.gz  in=279,683,035 out=63,834,998 elapsed=104.8s

  [5553/17668] intraday_14139.csv.gz  in=279,694,357 out=63,846,320 elapsed=104.8s

  [5554/17668] intraday_1414.csv.gz  in=279,707,418 out=63,846,320 elapsed=104.8s

  [5555/17668] intraday_14140.csv.gz  in=279,722,587 out=63,860,323 elapsed=104.8s

  [5556/17668] intraday_14143.csv.gz  in=279,728,669 out=63,866,405 elapsed=104.9s

  [5557/17668] intraday_14141.csv.gz  in=279,742,948 out=63,880,684 elapsed=104.9s

  [5558/17668] intraday_14142.csv.gz  in=279,751,954 out=63,889,690 elapsed=104.9s

  [5559/17668] intraday_14144.csv.gz  in=279,762,924 out=63,900,660 elapsed=104.9s

  [5560/17668] intraday_14147.csv.gz  in=279,774,350 out=63,912,086 elapsed=104.9s

  [5561/17668] intraday_14145.csv.gz  in=279,785,320 out=63,923,056 elapsed=104.9s

  [5562/17668] intraday_14146.csv.gz  in=279,799,356 out=63,937,092 elapsed=104.9s

  [5563/17668] intraday_14148.csv.gz  in=279,811,826 out=63,949,562 elapsed=104.9s

  [5564/17668] intraday_14149.csv.gz  in=279,824,177 out=63,961,913 elapsed=104.9s

  [5565/17668] intraday_14150.csv.gz  in=279,837,209 out=63,974,945 elapsed=104.9s

  [5566/17668] intraday_14151.csv.gz  in=279,846,962 out=63,984,698 elapsed=105.0s

  [5567/17668] intraday_1415.csv.gz  in=279,859,141 out=63,984,698 elapsed=105.0s

  [5568/17668] intraday_14153.csv.gz  in=279,870,349 out=63,995,906 elapsed=105.0s

  [5569/17668] intraday_14152.csv.gz  in=279,880,471 out=64,006,028 elapsed=105.0s

  [5570/17668] intraday_14154.csv.gz  in=279,891,120 out=64,016,677 elapsed=105.0s

  [5571/17668] intraday_14155.csv.gz  in=279,905,276 out=64,030,833 elapsed=105.0s

  [5572/17668] intraday_14157.csv.gz  in=279,918,895 out=64,044,452 elapsed=105.0s

  [5573/17668] intraday_14158.csv.gz  in=279,928,615 out=64,054,172 elapsed=105.0s

  [5574/17668] intraday_14156.csv.gz  in=279,943,858 out=64,069,415 elapsed=105.0s

  [5575/17668] intraday_14159.csv.gz  in=279,947,536 out=64,073,093 elapsed=105.1s

  [5576/17668] intraday_1416.csv.gz  in=279,959,356 out=64,073,093 elapsed=105.1s

  [5577/17668] intraday_14160.csv.gz  in=279,961,359 out=64,075,096 elapsed=105.1s

  [5578/17668] intraday_14161.csv.gz  in=279,973,827 out=64,087,564 elapsed=105.1s

  [5579/17668] intraday_14162.csv.gz  in=279,984,003 out=64,097,647 elapsed=105.1s

  [5580/17668] intraday_14163.csv.gz  in=279,995,153 out=64,108,797 elapsed=105.1s

  [5581/17668] intraday_14164.csv.gz  in=280,004,942 out=64,118,586 elapsed=105.1s

  [5582/17668] intraday_14165.csv.gz  in=280,015,200 out=64,128,844 elapsed=105.2s

  [5583/17668] intraday_14166.csv.gz  in=280,027,603 out=64,141,247 elapsed=105.2s

  [5584/17668] intraday_14167.csv.gz  in=280,037,818 out=64,151,462 elapsed=105.2s

  [5585/17668] intraday_14169.csv.gz  in=280,051,549 out=64,165,193 elapsed=105.2s

  [5586/17668] intraday_14168.csv.gz  in=280,065,579 out=64,179,223 elapsed=105.2s

  [5587/17668] intraday_1417.csv.gz  in=280,079,050 out=64,179,223 elapsed=105.2s

  [5588/17668] intraday_14170.csv.gz  in=280,091,453 out=64,191,626 elapsed=105.2s

  [5589/17668] intraday_14171.csv.gz  in=280,103,250 out=64,203,423 elapsed=105.2s

  [5590/17668] intraday_14173.csv.gz  in=280,106,674 out=64,206,847 elapsed=105.2s

  [5591/17668] intraday_14172.csv.gz  in=280,119,217 out=64,219,390 elapsed=105.3s

  [5592/17668] intraday_14174.csv.gz  in=280,122,534 out=64,222,707 elapsed=105.3s

  [5593/17668] intraday_14175.csv.gz  in=280,132,350 out=64,232,523 elapsed=105.3s

  [5594/17668] intraday_14176.csv.gz  in=280,147,931 out=64,248,104 elapsed=105.3s

  [5595/17668] intraday_14178.csv.gz  in=280,158,246 out=64,258,419 elapsed=105.3s

  [5596/17668] intraday_14179.csv.gz  in=280,172,597 out=64,272,770 elapsed=105.3s

  [5597/17668] intraday_14177.csv.gz  in=280,183,859 out=64,284,032 elapsed=105.3s

  [5598/17668] intraday_1418.csv.gz  in=280,198,347 out=64,284,032 elapsed=105.3s

  [5599/17668] intraday_14180.csv.gz  in=280,209,650 out=64,295,335 elapsed=105.4s

  [5600/17668] intraday_14181.csv.gz  in=280,220,955 out=64,306,640 elapsed=105.4s

  [5601/17668] intraday_14182.csv.gz  in=280,231,276 out=64,316,961 elapsed=105.4s

  [5602/17668] intraday_14183.csv.gz  in=280,243,089 out=64,328,774 elapsed=105.4s

  [5603/17668] intraday_14184.csv.gz  in=280,255,082 out=64,340,767 elapsed=105.4s

  [5604/17668] intraday_14186.csv.gz  in=280,264,393 out=64,350,078 elapsed=105.4s

  [5605/17668] intraday_14185.csv.gz  in=280,276,901 out=64,362,586 elapsed=105.4s

  [5606/17668] intraday_14187.csv.gz  in=280,280,753 out=64,366,438 elapsed=105.4s

  [5607/17668] intraday_14188.csv.gz  in=280,286,941 out=64,372,626 elapsed=105.5s

  [5608/17668] intraday_14189.csv.gz  in=280,300,026 out=64,385,711 elapsed=105.5s

  [5609/17668] intraday_1419.csv.gz  in=280,313,922 out=64,385,711 elapsed=105.5s

  [5610/17668] intraday_14190.csv.gz  in=280,326,691 out=64,398,480 elapsed=105.5s

  [5611/17668] intraday_14193.csv.gz  in=280,336,046 out=64,407,835 elapsed=105.5s

  [5612/17668] intraday_14192.csv.gz  in=280,348,651 out=64,420,440 elapsed=105.6s

  [5613/17668] intraday_14191.csv.gz  in=280,359,730 out=64,431,519 elapsed=105.6s

  [5614/17668] intraday_14194.csv.gz  in=280,372,102 out=64,443,891 elapsed=105.6s

  [5615/17668] intraday_14195.csv.gz  in=280,384,582 out=64,456,371 elapsed=105.6s

  [5616/17668] intraday_14197.csv.gz  in=280,396,261 out=64,468,050 elapsed=105.6s

  [5617/17668] intraday_14196.csv.gz  in=280,408,854 out=64,480,643 elapsed=105.6s

  [5618/17668] intraday_14199.csv.gz  in=280,418,788 out=64,490,577 elapsed=105.6s

  [5619/17668] intraday_1420.csv.gz  in=280,434,917 out=64,490,577 elapsed=105.6s

  [5620/17668] intraday_14198.csv.gz  in=280,446,949 out=64,502,609 elapsed=105.6s

  [5621/17668] intraday_14200.csv.gz  in=280,459,893 out=64,515,553 elapsed=105.6s

  [5622/17668] intraday_14201.csv.gz  in=280,472,494 out=64,528,154 elapsed=105.7s

  [5623/17668] intraday_14203.csv.gz  in=280,483,354 out=64,539,014 elapsed=105.7s

  [5624/17668] intraday_14202.csv.gz  in=280,495,049 out=64,550,709 elapsed=105.7s

  [5625/17668] intraday_14204.csv.gz  in=280,504,203 out=64,559,863 elapsed=105.7s

  [5626/17668] intraday_14205.csv.gz  in=280,514,521 out=64,570,181 elapsed=105.7s

  [5627/17668] intraday_14207.csv.gz  in=280,529,812 out=64,585,472 elapsed=105.7s

  [5628/17668] intraday_14206.csv.gz  in=280,542,456 out=64,598,116 elapsed=105.7s

  [5629/17668] intraday_14209.csv.gz  in=280,557,033 out=64,612,693 elapsed=105.7s

  [5630/17668] intraday_1421.csv.gz  in=280,569,156 out=64,612,693 elapsed=105.7s

  [5631/17668] intraday_14208.csv.gz  in=280,583,739 out=64,627,276 elapsed=105.7s

  [5632/17668] intraday_14210.csv.gz  in=280,594,824 out=64,638,361 elapsed=105.8s

  [5633/17668] intraday_14211.csv.gz  in=280,606,999 out=64,650,536 elapsed=105.8s

  [5634/17668] intraday_14212.csv.gz  in=280,617,349 out=64,660,886 elapsed=105.8s

  [5635/17668] intraday_14214.csv.gz  in=280,627,193 out=64,670,730 elapsed=105.8s

  [5636/17668] intraday_14213.csv.gz  in=280,642,402 out=64,685,939 elapsed=105.8s

  [5637/17668] intraday_14216.csv.gz  in=280,654,910 out=64,698,447 elapsed=105.9s

  [5638/17668] intraday_14215.csv.gz  in=280,667,284 out=64,710,821 elapsed=105.9s

  [5639/17668] intraday_14217.csv.gz  in=280,678,797 out=64,722,334 elapsed=105.9s

  [5640/17668] intraday_14218.csv.gz  in=280,691,534 out=64,735,071 elapsed=105.9s

  [5641/17668] intraday_14219.csv.gz  in=280,702,430 out=64,745,967 elapsed=105.9s

  [5642/17668] intraday_1422.csv.gz  in=280,716,219 out=64,745,967 elapsed=105.9s

  [5643/17668] intraday_14220.csv.gz  in=280,728,438 out=64,758,186 elapsed=105.9s

  [5644/17668] intraday_14221.csv.gz  in=280,739,956 out=64,769,704 elapsed=106.0s

  [5645/17668] intraday_14223.csv.gz  in=280,751,571 out=64,781,319 elapsed=106.0s

  [5646/17668] intraday_14222.csv.gz  in=280,762,024 out=64,791,772 elapsed=106.0s

  [5647/17668] intraday_14224.csv.gz  in=280,774,298 out=64,804,046 elapsed=106.0s

  [5648/17668] intraday_14225.csv.gz  in=280,786,672 out=64,816,420 elapsed=106.0s

  [5649/17668] intraday_14226.csv.gz  in=280,798,934 out=64,828,682 elapsed=106.0s

  [5650/17668] intraday_14227.csv.gz  in=280,812,526 out=64,841,879 elapsed=106.0s

  [5651/17668] intraday_14228.csv.gz  in=280,823,837 out=64,853,190 elapsed=106.0s

  [5652/17668] intraday_14229.csv.gz  in=280,835,149 out=64,864,502 elapsed=106.1s

  [5653/17668] intraday_1423.csv.gz  in=280,850,228 out=64,864,502 elapsed=106.1s

  [5654/17668] intraday_14230.csv.gz  in=280,864,816 out=64,879,090 elapsed=106.1s

  [5655/17668] intraday_14231.csv.gz  in=280,876,372 out=64,890,646 elapsed=106.1s

  [5656/17668] intraday_14232.csv.gz  in=280,887,801 out=64,902,075 elapsed=106.1s

  [5657/17668] intraday_14233.csv.gz  in=280,900,483 out=64,914,757 elapsed=106.1s

  [5658/17668] intraday_14234.csv.gz  in=280,914,016 out=64,928,290 elapsed=106.1s

  [5659/17668] intraday_14235.csv.gz  in=280,926,284 out=64,940,558 elapsed=106.1s

  [5660/17668] intraday_14236.csv.gz  in=280,940,110 out=64,954,384 elapsed=106.2s

  [5661/17668] intraday_14237.csv.gz  in=280,953,299 out=64,967,573 elapsed=106.2s

  [5662/17668] intraday_14238.csv.gz  in=280,965,265 out=64,979,539 elapsed=106.2s

  [5663/17668] intraday_1424.csv.gz  in=280,978,738 out=64,979,539 elapsed=106.2s

  [5664/17668] intraday_14239.csv.gz  in=280,994,307 out=64,995,108 elapsed=106.2s

  [5665/17668] intraday_14240.csv.gz  in=281,011,316 out=65,012,117 elapsed=106.2s

  [5666/17668] intraday_14243.csv.gz  in=281,023,409 out=65,024,210 elapsed=106.3s

  [5667/17668] intraday_14241.csv.gz  in=281,038,522 out=65,039,323 elapsed=106.3s

  [5668/17668] intraday_14244.csv.gz  in=281,050,891 out=65,051,692 elapsed=106.3s

  [5669/17668] intraday_14242.csv.gz  in=281,064,309 out=65,065,110 elapsed=106.3s

  [5670/17668] intraday_14245.csv.gz  in=281,076,521 out=65,077,322 elapsed=106.3s

  [5671/17668] intraday_14246.csv.gz  in=281,085,402 out=65,086,203 elapsed=106.3s

  [5672/17668] intraday_14247.csv.gz  in=281,097,856 out=65,098,657 elapsed=106.3s

  [5673/17668] intraday_14248.csv.gz  in=281,108,976 out=65,109,777 elapsed=106.3s

  [5674/17668] intraday_14249.csv.gz  in=281,121,009 out=65,121,810 elapsed=106.3s

  [5675/17668] intraday_1425.csv.gz  in=281,134,529 out=65,121,810 elapsed=106.4s

  [5676/17668] intraday_14250.csv.gz  in=281,147,574 out=65,134,855 elapsed=106.4s

  [5677/17668] intraday_14251.csv.gz  in=281,160,752 out=65,148,033 elapsed=106.4s

  [5678/17668] intraday_14252.csv.gz  in=281,170,682 out=65,157,963 elapsed=106.4s

  [5679/17668] intraday_14253.csv.gz  in=281,182,560 out=65,169,841 elapsed=106.4s

  [5680/17668] intraday_14254.csv.gz  in=281,193,541 out=65,180,822 elapsed=106.4s

  [5681/17668] intraday_14255.csv.gz  in=281,207,931 out=65,195,212 elapsed=106.4s

  [5682/17668] intraday_14256.csv.gz  in=281,220,028 out=65,207,309 elapsed=106.4s

  [5683/17668] intraday_14257.csv.gz  in=281,233,300 out=65,220,581 elapsed=106.5s

  [5684/17668] intraday_14258.csv.gz  in=281,247,374 out=65,234,655 elapsed=106.5s

  [5685/17668] intraday_14259.csv.gz  in=281,259,067 out=65,246,348 elapsed=106.5s

  [5686/17668] intraday_1426.csv.gz  in=281,271,081 out=65,246,348 elapsed=106.5s

  [5687/17668] intraday_14261.csv.gz  in=281,281,062 out=65,256,329 elapsed=106.5s

  [5688/17668] intraday_14262.csv.gz  in=281,293,533 out=65,268,800 elapsed=106.6s

  [5689/17668] intraday_14260.csv.gz  in=281,307,720 out=65,282,987 elapsed=106.6s

  [5690/17668] intraday_14264.csv.gz  in=281,317,708 out=65,292,975 elapsed=106.6s

  [5691/17668] intraday_14263.csv.gz  in=281,329,117 out=65,304,384 elapsed=106.6s

  [5692/17668] intraday_14266.csv.gz  in=281,336,841 out=65,312,108 elapsed=106.6s

  [5693/17668] intraday_14265.csv.gz  in=281,349,446 out=65,324,713 elapsed=106.6s

  [5694/17668] intraday_14268.csv.gz  in=281,359,027 out=65,334,294 elapsed=106.6s

  [5695/17668] intraday_14267.csv.gz  in=281,369,847 out=65,345,114 elapsed=106.6s

  [5696/17668] intraday_1427.csv.gz  in=281,381,062 out=65,345,114 elapsed=106.6s

  [5697/17668] intraday_14269.csv.gz  in=281,396,811 out=65,360,863 elapsed=106.6s

  [5698/17668] intraday_14270.csv.gz  in=281,409,213 out=65,373,265 elapsed=106.7s

  [5699/17668] intraday_14271.csv.gz  in=281,422,242 out=65,386,294 elapsed=106.7s

  [5700/17668] intraday_14272.csv.gz  in=281,431,815 out=65,395,867 elapsed=106.7s

  [5701/17668] intraday_14273.csv.gz  in=281,443,561 out=65,407,613 elapsed=106.7s

  [5702/17668] intraday_14274.csv.gz  in=281,457,274 out=65,421,326 elapsed=106.7s

  [5703/17668] intraday_14275.csv.gz  in=281,471,725 out=65,435,777 elapsed=106.7s

  [5704/17668] intraday_14276.csv.gz  in=281,481,260 out=65,445,312 elapsed=106.7s

  [5705/17668] intraday_14277.csv.gz  in=281,494,202 out=65,458,254 elapsed=106.7s

  [5706/17668] intraday_14278.csv.gz  in=281,506,447 out=65,470,499 elapsed=106.7s

  [5707/17668] intraday_14279.csv.gz  in=281,517,646 out=65,481,698 elapsed=106.7s

  [5708/17668] intraday_1428.csv.gz  in=281,533,735 out=65,481,698 elapsed=106.8s

  [5709/17668] intraday_14280.csv.gz  in=281,543,964 out=65,491,927 elapsed=106.8s

  [5710/17668] intraday_14281.csv.gz  in=281,555,768 out=65,503,731 elapsed=106.8s

  [5711/17668] intraday_14284.csv.gz  in=281,558,801 out=65,506,764 elapsed=106.8s

  [5712/17668] intraday_14282.csv.gz  in=281,573,217 out=65,521,180 elapsed=106.8s

  [5713/17668] intraday_14283.csv.gz  in=281,581,741 out=65,529,704 elapsed=106.8s

  [5714/17668] intraday_14285.csv.gz  in=281,592,418 out=65,540,381 elapsed=106.9s

  [5715/17668] intraday_14286.csv.gz  in=281,603,701 out=65,551,664 elapsed=106.9s

  [5716/17668] intraday_14288.csv.gz  in=281,614,085 out=65,562,048 elapsed=106.9s

  [5717/17668] intraday_14287.csv.gz  in=281,627,818 out=65,575,781 elapsed=106.9s

  [5718/17668] intraday_14289.csv.gz  in=281,640,553 out=65,588,516 elapsed=106.9s

  [5719/17668] intraday_1429.csv.gz  in=281,660,463 out=65,588,516 elapsed=106.9s

  [5720/17668] intraday_14290.csv.gz  in=281,672,619 out=65,600,672 elapsed=106.9s

  [5721/17668] intraday_14291.csv.gz  in=281,685,602 out=65,613,655 elapsed=106.9s

  [5722/17668] intraday_14292.csv.gz  in=281,695,436 out=65,623,489 elapsed=106.9s

  [5723/17668] intraday_14293.csv.gz  in=281,705,465 out=65,633,518 elapsed=107.0s

  [5724/17668] intraday_14294.csv.gz  in=281,717,010 out=65,645,063 elapsed=107.0s

  [5725/17668] intraday_14295.csv.gz  in=281,728,084 out=65,656,137 elapsed=107.0s

  [5726/17668] intraday_14296.csv.gz  in=281,740,704 out=65,668,757 elapsed=107.0s

  [5727/17668] intraday_14297.csv.gz  in=281,757,718 out=65,685,771 elapsed=107.0s

  [5728/17668] intraday_14298.csv.gz  in=281,769,816 out=65,697,869 elapsed=107.0s

  [5729/17668] intraday_14299.csv.gz  in=281,773,922 out=65,701,975 elapsed=107.0s

  [5730/17668] intraday_1430.csv.gz  in=281,786,064 out=65,701,975 elapsed=107.0s

  [5731/17668] intraday_14300.csv.gz  in=281,797,740 out=65,713,651 elapsed=107.1s

  [5732/17668] intraday_14302.csv.gz  in=281,807,019 out=65,722,930 elapsed=107.1s

  [5733/17668] intraday_14301.csv.gz  in=281,819,821 out=65,735,732 elapsed=107.1s

  [5734/17668] intraday_14303.csv.gz  in=281,831,640 out=65,747,551 elapsed=107.1s

  [5735/17668] intraday_14304.csv.gz  in=281,840,530 out=65,756,441 elapsed=107.1s

  [5736/17668] intraday_14305.csv.gz  in=281,851,025 out=65,766,936 elapsed=107.1s

  [5737/17668] intraday_14306.csv.gz  in=281,862,637 out=65,778,548 elapsed=107.1s

  [5738/17668] intraday_14307.csv.gz  in=281,874,382 out=65,790,293 elapsed=107.1s

  [5739/17668] intraday_14308.csv.gz  in=281,886,938 out=65,802,849 elapsed=107.2s

  [5740/17668] intraday_14309.csv.gz  in=281,900,819 out=65,816,730 elapsed=107.2s

  [5741/17668] intraday_1431.csv.gz  in=281,914,922 out=65,816,730 elapsed=107.2s

  [5742/17668] intraday_14311.csv.gz  in=281,926,438 out=65,828,246 elapsed=107.2s

  [5743/17668] intraday_14310.csv.gz  in=281,937,608 out=65,839,416 elapsed=107.2s

  [5744/17668] intraday_14312.csv.gz  in=281,949,696 out=65,851,504 elapsed=107.2s

  [5745/17668] intraday_14314.csv.gz  in=281,960,786 out=65,862,594 elapsed=107.2s

  [5746/17668] intraday_14313.csv.gz  in=281,970,999 out=65,872,807 elapsed=107.2s

  [5747/17668] intraday_14315.csv.gz  in=281,980,610 out=65,882,418 elapsed=107.3s

  [5748/17668] intraday_14316.csv.gz  in=281,989,935 out=65,891,743 elapsed=107.3s

  [5749/17668] intraday_14317.csv.gz  in=281,996,321 out=65,898,129 elapsed=107.3s

  [5750/17668] intraday_14318.csv.gz  in=282,008,336 out=65,910,144 elapsed=107.3s

  [5751/17668] intraday_14319.csv.gz  in=282,019,111 out=65,920,919 elapsed=107.3s

  [5752/17668] intraday_1432.csv.gz  in=282,032,139 out=65,920,919 elapsed=107.3s

  [5753/17668] intraday_14320.csv.gz  in=282,042,290 out=65,931,070 elapsed=107.3s

  [5754/17668] intraday_14321.csv.gz  in=282,053,053 out=65,941,833 elapsed=107.4s

  [5755/17668] intraday_14322.csv.gz  in=282,065,852 out=65,954,632 elapsed=107.4s

  [5756/17668] intraday_14323.csv.gz  in=282,076,973 out=65,965,753 elapsed=107.4s

  [5757/17668] intraday_14324.csv.gz  in=282,088,047 out=65,976,827 elapsed=107.4s

  [5758/17668] intraday_14325.csv.gz  in=282,097,947 out=65,986,727 elapsed=107.4s

  [5759/17668] intraday_14327.csv.gz  in=282,106,975 out=65,995,755 elapsed=107.4s

  [5760/17668] intraday_14329.csv.gz  in=282,120,868 out=66,009,582 elapsed=107.4s

  [5761/17668] intraday_14328.csv.gz  in=282,135,751 out=66,024,465 elapsed=107.4s

  [5762/17668] intraday_1433.csv.gz  in=282,147,393 out=66,024,465 elapsed=107.4s

  [5763/17668] intraday_14326.csv.gz  in=282,158,256 out=66,035,328 elapsed=107.4s

  [5764/17668] intraday_14330.csv.gz  in=282,171,498 out=66,048,570 elapsed=107.5s

  [5765/17668] intraday_14333.csv.gz  in=282,172,908 out=66,049,980 elapsed=107.5s

  [5766/17668] intraday_14332.csv.gz  in=282,183,897 out=66,060,969 elapsed=107.5s

  [5767/17668] intraday_14331.csv.gz  in=282,195,181 out=66,072,253 elapsed=107.5s

  [5768/17668] intraday_14334.csv.gz  in=282,199,097 out=66,076,169 elapsed=107.5s

  [5769/17668] intraday_14336.csv.gz  in=282,210,893 out=66,087,965 elapsed=107.5s

  [5770/17668] intraday_14337.csv.gz  in=282,222,495 out=66,099,567 elapsed=107.5s

  [5771/17668] intraday_14335.csv.gz  in=282,234,000 out=66,111,072 elapsed=107.5s

  [5772/17668] intraday_14338.csv.gz  in=282,243,053 out=66,120,125 elapsed=107.5s

  [5773/17668] intraday_1434.csv.gz  in=282,257,308 out=66,120,125 elapsed=107.6s

  [5774/17668] intraday_14339.csv.gz  in=282,271,906 out=66,134,723 elapsed=107.6s

  [5775/17668] intraday_14341.csv.gz  in=282,284,317 out=66,147,134 elapsed=107.6s

  [5776/17668] intraday_14340.csv.gz  in=282,294,605 out=66,157,422 elapsed=107.6s

  [5777/17668] intraday_14342.csv.gz  in=282,304,760 out=66,167,577 elapsed=107.6s

  [5778/17668] intraday_14343.csv.gz  in=282,314,745 out=66,177,562 elapsed=107.6s

  [5779/17668] intraday_14344.csv.gz  in=282,326,400 out=66,189,217 elapsed=107.6s

  [5780/17668] intraday_14345.csv.gz  in=282,339,651 out=66,202,468 elapsed=107.7s

  [5781/17668] intraday_14347.csv.gz  in=282,351,387 out=66,214,204 elapsed=107.7s

  [5782/17668] intraday_14346.csv.gz  in=282,369,364 out=66,232,181 elapsed=107.7s

  [5783/17668] intraday_14348.csv.gz  in=282,382,461 out=66,245,278 elapsed=107.7s

  [5784/17668] intraday_14349.csv.gz  in=282,393,184 out=66,256,001 elapsed=107.7s

  [5785/17668] intraday_1435.csv.gz  in=282,406,938 out=66,256,001 elapsed=107.7s

  [5786/17668] intraday_14350.csv.gz  in=282,418,779 out=66,267,842 elapsed=107.7s

  [5787/17668] intraday_14351.csv.gz  in=282,432,388 out=66,281,451 elapsed=107.7s

  [5788/17668] intraday_14352.csv.gz  in=282,446,658 out=66,295,721 elapsed=107.7s

  [5789/17668] intraday_14353.csv.gz  in=282,456,458 out=66,305,521 elapsed=107.8s

  [5790/17668] intraday_14354.csv.gz  in=282,471,614 out=66,320,677 elapsed=107.8s

  [5791/17668] intraday_14357.csv.gz  in=282,471,655 out=66,320,718 elapsed=107.8s

  [5792/17668] intraday_14355.csv.gz  in=282,482,621 out=66,331,684 elapsed=107.8s

  [5793/17668] intraday_14356.csv.gz  in=282,490,744 out=66,339,807 elapsed=107.8s

  [5794/17668] intraday_1436.csv.gz  in=282,502,667 out=66,339,807 elapsed=107.8s

  [5795/17668] intraday_14358.csv.gz  in=282,515,253 out=66,352,393 elapsed=107.8s

  [5796/17668] intraday_14359.csv.gz  in=282,525,525 out=66,362,665 elapsed=107.8s

  [5797/17668] intraday_14361.csv.gz  in=282,536,458 out=66,373,598 elapsed=107.8s

  [5798/17668] intraday_14360.csv.gz  in=282,548,052 out=66,385,192 elapsed=107.9s

  [5799/17668] intraday_14362.csv.gz  in=282,561,426 out=66,398,566 elapsed=107.9s

  [5800/17668] intraday_14363.csv.gz  in=282,574,821 out=66,411,961 elapsed=107.9s

  [5801/17668] intraday_14364.csv.gz  in=282,586,288 out=66,423,428 elapsed=107.9s

  [5802/17668] intraday_14365.csv.gz  in=282,597,753 out=66,434,893 elapsed=107.9s

  [5803/17668] intraday_14366.csv.gz  in=282,607,927 out=66,445,067 elapsed=107.9s

  [5804/17668] intraday_14367.csv.gz  in=282,622,881 out=66,460,021 elapsed=107.9s

  [5805/17668] intraday_14368.csv.gz  in=282,632,851 out=66,469,991 elapsed=107.9s

  [5806/17668] intraday_14369.csv.gz  in=282,644,270 out=66,481,410 elapsed=108.0s

  [5807/17668] intraday_1437.csv.gz  in=282,658,980 out=66,481,410 elapsed=108.0s

  [5808/17668] intraday_14370.csv.gz  in=282,671,737 out=66,494,167 elapsed=108.0s

  [5809/17668] intraday_14372.csv.gz  in=282,683,609 out=66,506,039 elapsed=108.0s

  [5810/17668] intraday_14371.csv.gz  in=282,698,189 out=66,520,619 elapsed=108.0s

  [5811/17668] intraday_14373.csv.gz  in=282,709,979 out=66,532,409 elapsed=108.0s

  [5812/17668] intraday_14374.csv.gz  in=282,722,499 out=66,544,929 elapsed=108.0s

  [5813/17668] intraday_14375.csv.gz  in=282,734,804 out=66,557,234 elapsed=108.1s

  [5814/17668] intraday_14377.csv.gz  in=282,749,899 out=66,572,329 elapsed=108.1s

  [5815/17668] intraday_14378.csv.gz  in=282,769,607 out=66,592,037 elapsed=108.1s

  [5816/17668] intraday_14376.csv.gz  in=282,784,298 out=66,606,728 elapsed=108.1s

  [5817/17668] intraday_14379.csv.gz  in=282,794,802 out=66,617,232 elapsed=108.1s

  [5818/17668] intraday_1438.csv.gz  in=282,807,712 out=66,617,232 elapsed=108.1s

  [5819/17668] intraday_14380.csv.gz  in=282,823,133 out=66,632,653 elapsed=108.1s

  [5820/17668] intraday_14381.csv.gz  in=282,833,094 out=66,642,614 elapsed=108.2s

  [5821/17668] intraday_14383.csv.gz  in=282,843,493 out=66,653,013 elapsed=108.2s

  [5822/17668] intraday_14382.csv.gz  in=282,856,502 out=66,666,022 elapsed=108.2s

  [5823/17668] intraday_14385.csv.gz  in=282,866,486 out=66,676,006 elapsed=108.2s

  [5824/17668] intraday_14384.csv.gz  in=282,878,528 out=66,688,048 elapsed=108.2s

  [5825/17668] intraday_14386.csv.gz  in=282,891,267 out=66,700,787 elapsed=108.2s

  [5826/17668] intraday_14387.csv.gz  in=282,901,362 out=66,710,882 elapsed=108.2s

  [5827/17668] intraday_14389.csv.gz  in=282,910,180 out=66,719,700 elapsed=108.2s

  [5828/17668] intraday_1439.csv.gz  in=282,920,187 out=66,719,700 elapsed=108.2s

  [5829/17668] intraday_14388.csv.gz  in=282,936,795 out=66,736,308 elapsed=108.3s

  [5830/17668] intraday_14390.csv.gz  in=282,948,560 out=66,748,073 elapsed=108.3s

  [5831/17668] intraday_14391.csv.gz  in=282,959,431 out=66,758,944 elapsed=108.3s

  [5832/17668] intraday_14393.csv.gz  in=282,969,710 out=66,769,223 elapsed=108.3s

  [5833/17668] intraday_14392.csv.gz  in=282,983,219 out=66,782,732 elapsed=108.3s

  [5834/17668] intraday_14394.csv.gz  in=283,001,253 out=66,799,953 elapsed=108.3s

  [5835/17668] intraday_14395.csv.gz  in=283,015,031 out=66,813,731 elapsed=108.3s

  [5836/17668] intraday_14396.csv.gz  in=283,028,235 out=66,826,935 elapsed=108.3s

  [5837/17668] intraday_14397.csv.gz  in=283,041,941 out=66,840,641 elapsed=108.4s

  [5838/17668] intraday_14398.csv.gz  in=283,053,644 out=66,852,344 elapsed=108.4s

  [5839/17668] intraday_14399.csv.gz  in=283,064,072 out=66,862,772 elapsed=108.4s

  [5840/17668] intraday_1440.csv.gz  in=283,077,986 out=66,862,772 elapsed=108.4s

  [5841/17668] intraday_14400.csv.gz  in=283,090,766 out=66,875,552 elapsed=108.4s

  [5842/17668] intraday_14401.csv.gz  in=283,100,360 out=66,885,146 elapsed=108.4s

  [5843/17668] intraday_14402.csv.gz  in=283,113,089 out=66,897,875 elapsed=108.4s

  [5844/17668] intraday_14403.csv.gz  in=283,123,541 out=66,908,327 elapsed=108.4s

  [5845/17668] intraday_14404.csv.gz  in=283,130,883 out=66,915,669 elapsed=108.5s

  [5846/17668] intraday_14406.csv.gz  in=283,131,564 out=66,916,350 elapsed=108.5s

  [5847/17668] intraday_14405.csv.gz  in=283,145,915 out=66,930,701 elapsed=108.5s

  [5848/17668] intraday_14407.csv.gz  in=283,161,911 out=66,946,697 elapsed=108.5s

  [5849/17668] intraday_14408.csv.gz  in=283,173,423 out=66,958,209 elapsed=108.5s

  [5850/17668] intraday_14409.csv.gz  in=283,186,675 out=66,971,461 elapsed=108.5s

  [5851/17668] intraday_1441.csv.gz  in=283,201,213 out=66,971,461 elapsed=108.5s

  [5852/17668] intraday_14410.csv.gz  in=283,212,335 out=66,982,583 elapsed=108.5s

  [5853/17668] intraday_14411.csv.gz  in=283,223,823 out=66,994,071 elapsed=108.5s

  [5854/17668] intraday_14413.csv.gz  in=283,235,870 out=67,006,118 elapsed=108.6s

  [5855/17668] intraday_14412.csv.gz  in=283,250,747 out=67,020,995 elapsed=108.6s

  [5856/17668] intraday_14415.csv.gz  in=283,263,288 out=67,033,536 elapsed=108.6s

  [5857/17668] intraday_14414.csv.gz  in=283,274,483 out=67,044,731 elapsed=108.6s

  [5858/17668] intraday_14416.csv.gz  in=283,287,386 out=67,057,634 elapsed=108.6s

  [5859/17668] intraday_14417.csv.gz  in=283,298,195 out=67,068,443 elapsed=108.6s

  [5860/17668] intraday_14418.csv.gz  in=283,309,394 out=67,079,642 elapsed=108.6s

  [5861/17668] intraday_1442.csv.gz  in=283,320,814 out=67,079,642 elapsed=108.6s

  [5862/17668] intraday_14420.csv.gz  in=283,321,608 out=67,080,436 elapsed=108.7s

  [5863/17668] intraday_14419.csv.gz  in=283,333,527 out=67,092,355 elapsed=108.7s

  [5864/17668] intraday_14421.csv.gz  in=283,346,756 out=67,105,584 elapsed=108.7s

  [5865/17668] intraday_14422.csv.gz  in=283,360,613 out=67,119,441 elapsed=108.7s

  [5866/17668] intraday_14423.csv.gz  in=283,370,484 out=67,129,312 elapsed=108.7s

  [5867/17668] intraday_14424.csv.gz  in=283,382,057 out=67,140,885 elapsed=108.7s

  [5868/17668] intraday_14425.csv.gz  in=283,396,292 out=67,155,120 elapsed=108.7s

  [5869/17668] intraday_14427.csv.gz  in=283,410,339 out=67,169,167 elapsed=108.7s

  [5870/17668] intraday_14426.csv.gz  in=283,421,796 out=67,180,624 elapsed=108.7s

  [5871/17668] intraday_14428.csv.gz  in=283,433,256 out=67,192,084 elapsed=108.8s

  [5872/17668] intraday_1443.csv.gz  in=283,448,215 out=67,192,084 elapsed=108.8s

  [5873/17668] intraday_14430.csv.gz  in=283,460,173 out=67,204,042 elapsed=108.8s

  [5874/17668] intraday_14429.csv.gz  in=283,473,979 out=67,217,848 elapsed=108.8s

  [5875/17668] intraday_14433.csv.gz  in=283,478,911 out=67,222,780 elapsed=108.8s

  [5876/17668] intraday_14432.csv.gz  in=283,486,898 out=67,230,767 elapsed=108.8s

  [5877/17668] intraday_14431.csv.gz  in=283,497,769 out=67,241,638 elapsed=108.8s

  [5878/17668] intraday_14434.csv.gz  in=283,510,796 out=67,254,665 elapsed=108.9s

  [5879/17668] intraday_14435.csv.gz  in=283,519,946 out=67,263,815 elapsed=108.9s

  [5880/17668] intraday_14436.csv.gz  in=283,532,575 out=67,276,444 elapsed=108.9s

  [5881/17668] intraday_14438.csv.gz  in=283,545,459 out=67,289,328 elapsed=108.9s

  [5882/17668] intraday_14437.csv.gz  in=283,557,892 out=67,301,761 elapsed=108.9s

  [5883/17668] intraday_14439.csv.gz  in=283,570,379 out=67,314,248 elapsed=108.9s

  [5884/17668] intraday_1444.csv.gz  in=283,584,490 out=67,314,248 elapsed=108.9s

  [5885/17668] intraday_14440.csv.gz  in=283,594,323 out=67,324,081 elapsed=108.9s

  [5886/17668] intraday_14441.csv.gz  in=283,605,044 out=67,334,802 elapsed=108.9s

  [5887/17668] intraday_14442.csv.gz  in=283,613,952 out=67,343,710 elapsed=109.0s

  [5888/17668] intraday_14443.csv.gz  in=283,624,182 out=67,353,940 elapsed=109.0s

  [5889/17668] intraday_14444.csv.gz  in=283,636,478 out=67,366,236 elapsed=109.0s

  [5890/17668] intraday_14445.csv.gz  in=283,643,704 out=67,373,462 elapsed=109.0s

  [5891/17668] intraday_14446.csv.gz  in=283,650,103 out=67,379,861 elapsed=109.0s

  [5892/17668] intraday_14447.csv.gz  in=283,662,153 out=67,391,911 elapsed=109.0s

  [5893/17668] intraday_14448.csv.gz  in=283,673,684 out=67,403,442 elapsed=109.0s

  [5894/17668] intraday_14449.csv.gz  in=283,684,903 out=67,414,661 elapsed=109.0s

  [5895/17668] intraday_1445.csv.gz  in=283,695,594 out=67,414,661 elapsed=109.0s

  [5896/17668] intraday_14451.csv.gz  in=283,705,581 out=67,424,648 elapsed=109.1s

  [5897/17668] intraday_14450.csv.gz  in=283,716,926 out=67,435,993 elapsed=109.1s

  [5898/17668] intraday_14453.csv.gz  in=283,729,246 out=67,448,313 elapsed=109.1s

  [5899/17668] intraday_14452.csv.gz  in=283,741,577 out=67,460,644 elapsed=109.1s

  [5900/17668] intraday_14455.csv.gz  in=283,754,032 out=67,473,099 elapsed=109.1s

  [5901/17668] intraday_14454.csv.gz  in=283,766,487 out=67,485,554 elapsed=109.1s

  [5902/17668] intraday_14456.csv.gz  in=283,777,859 out=67,496,926 elapsed=109.1s

  [5903/17668] intraday_14457.csv.gz  in=283,789,491 out=67,508,558 elapsed=109.1s

  [5904/17668] intraday_14458.csv.gz  in=283,799,222 out=67,518,289 elapsed=109.1s

  [5905/17668] intraday_14459.csv.gz  in=283,810,962 out=67,530,029 elapsed=109.1s

  [5906/17668] intraday_1446.csv.gz  in=283,823,582 out=67,530,029 elapsed=109.1s

  [5907/17668] intraday_14460.csv.gz  in=283,829,913 out=67,536,360 elapsed=109.2s

  [5908/17668] intraday_14462.csv.gz  in=283,840,239 out=67,546,686 elapsed=109.2s

  [5909/17668] intraday_14461.csv.gz  in=283,850,729 out=67,557,176 elapsed=109.2s

  [5910/17668] intraday_14463.csv.gz  in=283,860,733 out=67,567,180 elapsed=109.2s

  [5911/17668] intraday_14464.csv.gz  in=283,875,134 out=67,581,581 elapsed=109.2s

  [5912/17668] intraday_14465.csv.gz  in=283,888,803 out=67,595,250 elapsed=109.2s

  [5913/17668] intraday_14466.csv.gz  in=283,901,260 out=67,607,707 elapsed=109.2s

  [5914/17668] intraday_14468.csv.gz  in=283,910,579 out=67,617,026 elapsed=109.3s

  [5915/17668] intraday_14469.csv.gz  in=283,921,845 out=67,628,292 elapsed=109.3s

  [5916/17668] intraday_14467.csv.gz  in=283,934,984 out=67,641,431 elapsed=109.3s

  [5917/17668] intraday_1447.csv.gz  in=283,947,950 out=67,641,431 elapsed=109.3s

  [5918/17668] intraday_14470.csv.gz  in=283,960,495 out=67,653,976 elapsed=109.3s

  [5919/17668] intraday_14471.csv.gz  in=283,971,541 out=67,665,022 elapsed=109.3s

  [5920/17668] intraday_14473.csv.gz  in=283,974,750 out=67,668,231 elapsed=109.3s

  [5921/17668] intraday_14472.csv.gz  in=283,986,817 out=67,680,298 elapsed=109.3s

  [5922/17668] intraday_14474.csv.gz  in=283,990,050 out=67,683,531 elapsed=109.3s

  [5923/17668] intraday_14475.csv.gz  in=284,003,748 out=67,697,229 elapsed=109.3s

  [5924/17668] intraday_14476.csv.gz  in=284,015,770 out=67,709,251 elapsed=109.4s

  [5925/17668] intraday_14477.csv.gz  in=284,028,811 out=67,722,292 elapsed=109.4s

  [5926/17668] intraday_14478.csv.gz  in=284,039,083 out=67,732,564 elapsed=109.4s

  [5927/17668] intraday_14479.csv.gz  in=284,049,203 out=67,742,684 elapsed=109.4s

  [5928/17668] intraday_1448.csv.gz  in=284,063,228 out=67,742,684 elapsed=109.4s

  [5929/17668] intraday_14480.csv.gz  in=284,076,326 out=67,755,782 elapsed=109.4s

  [5930/17668] intraday_14481.csv.gz  in=284,092,126 out=67,771,582 elapsed=109.4s

  [5931/17668] intraday_14482.csv.gz  in=284,106,173 out=67,785,629 elapsed=109.4s

  [5932/17668] intraday_14483.csv.gz  in=284,120,649 out=67,800,105 elapsed=109.4s

  [5933/17668] intraday_14485.csv.gz  in=284,132,145 out=67,811,601 elapsed=109.5s

  [5934/17668] intraday_14484.csv.gz  in=284,149,594 out=67,828,923 elapsed=109.5s

  [5935/17668] intraday_14486.csv.gz  in=284,161,837 out=67,841,129 elapsed=109.5s

  [5936/17668] intraday_14488.csv.gz  in=284,173,178 out=67,852,470 elapsed=109.5s

  [5937/17668] intraday_14487.csv.gz  in=284,190,378 out=67,869,670 elapsed=109.5s

  [5938/17668] intraday_14489.csv.gz  in=284,201,312 out=67,880,604 elapsed=109.5s

  [5939/17668] intraday_1449.csv.gz  in=284,212,910 out=67,880,604 elapsed=109.5s

  [5940/17668] intraday_14492.csv.gz  in=284,213,069 out=67,880,763 elapsed=109.6s

  [5941/17668] intraday_14491.csv.gz  in=284,219,374 out=67,887,068 elapsed=109.6s

  [5942/17668] intraday_14490.csv.gz  in=284,233,786 out=67,901,480 elapsed=109.6s

  [5943/17668] intraday_14493.csv.gz  in=284,244,765 out=67,912,459 elapsed=109.6s

  [5944/17668] intraday_14494.csv.gz  in=284,256,651 out=67,924,345 elapsed=109.6s

  [5945/17668] intraday_14495.csv.gz  in=284,268,601 out=67,936,295 elapsed=109.6s

  [5946/17668] intraday_14496.csv.gz  in=284,279,023 out=67,946,717 elapsed=109.6s

  [5947/17668] intraday_14497.csv.gz  in=284,290,949 out=67,958,643 elapsed=109.6s

  [5948/17668] intraday_14498.csv.gz  in=284,304,532 out=67,972,226 elapsed=109.6s

  [5949/17668] intraday_14499.csv.gz  in=284,318,167 out=67,985,861 elapsed=109.7s

  [5950/17668] intraday_1450.csv.gz  in=284,337,401 out=67,985,861 elapsed=109.7s

  [5951/17668] intraday_14500.csv.gz  in=284,349,247 out=67,997,707 elapsed=109.7s

  [5952/17668] intraday_14501.csv.gz  in=284,360,747 out=68,009,207 elapsed=109.7s

  [5953/17668] intraday_14502.csv.gz  in=284,371,252 out=68,019,712 elapsed=109.7s

  [5954/17668] intraday_14504.csv.gz  in=284,380,889 out=68,029,349 elapsed=109.7s

  [5955/17668] intraday_14503.csv.gz  in=284,396,043 out=68,044,503 elapsed=109.7s

  [5956/17668] intraday_14505.csv.gz  in=284,407,015 out=68,055,475 elapsed=109.7s

  [5957/17668] intraday_14506.csv.gz  in=284,420,679 out=68,069,139 elapsed=109.7s

  [5958/17668] intraday_14507.csv.gz  in=284,435,519 out=68,083,979 elapsed=109.8s

  [5959/17668] intraday_14509.csv.gz  in=284,455,209 out=68,103,460 elapsed=109.8s

  [5960/17668] intraday_14508.csv.gz  in=284,465,438 out=68,113,689 elapsed=109.8s

  [5961/17668] intraday_1451.csv.gz  in=284,477,805 out=68,113,689 elapsed=109.8s

  [5962/17668] intraday_14510.csv.gz  in=284,489,849 out=68,125,733 elapsed=109.8s

  [5963/17668] intraday_14511.csv.gz  in=284,503,460 out=68,139,344 elapsed=109.8s

  [5964/17668] intraday_14513.csv.gz  in=284,520,907 out=68,156,791 elapsed=109.9s

  [5965/17668] intraday_14514.csv.gz  in=284,538,374 out=68,174,258 elapsed=109.9s

  [5966/17668] intraday_14512.csv.gz  in=284,552,117 out=68,188,001 elapsed=109.9s

  [5967/17668] intraday_14515.csv.gz  in=284,565,547 out=68,201,431 elapsed=109.9s

  [5968/17668] intraday_14516.csv.gz  in=284,578,591 out=68,214,475 elapsed=109.9s

  [5969/17668] intraday_14518.csv.gz  in=284,590,971 out=68,226,855 elapsed=109.9s

  [5970/17668] intraday_14517.csv.gz  in=284,601,893 out=68,237,777 elapsed=109.9s

  [5971/17668] intraday_14519.csv.gz  in=284,611,216 out=68,247,100 elapsed=109.9s

  [5972/17668] intraday_1452.csv.gz  in=284,623,688 out=68,247,100 elapsed=109.9s

  [5973/17668] intraday_14521.csv.gz  in=284,633,799 out=68,257,211 elapsed=110.0s

  [5974/17668] intraday_14522.csv.gz  in=284,644,823 out=68,268,229 elapsed=110.0s

  [5975/17668] intraday_14520.csv.gz  in=284,657,997 out=68,281,403 elapsed=110.0s

  [5976/17668] intraday_14524.csv.gz  in=284,671,794 out=68,295,200 elapsed=110.0s

  [5977/17668] intraday_14523.csv.gz  in=284,684,011 out=68,307,417 elapsed=110.0s

  [5978/17668] intraday_14525.csv.gz  in=284,694,898 out=68,318,304 elapsed=110.0s

  [5979/17668] intraday_14526.csv.gz  in=284,705,082 out=68,328,488 elapsed=110.0s

  [5980/17668] intraday_14527.csv.gz  in=284,716,864 out=68,340,270 elapsed=110.1s

  [5981/17668] intraday_14528.csv.gz  in=284,730,048 out=68,353,454 elapsed=110.1s

  [5982/17668] intraday_1453.csv.gz  in=284,742,551 out=68,353,454 elapsed=110.1s

  [5983/17668] intraday_14529.csv.gz  in=284,754,171 out=68,365,074 elapsed=110.1s

  [5984/17668] intraday_14530.csv.gz  in=284,767,835 out=68,378,738 elapsed=110.1s

  [5985/17668] intraday_14531.csv.gz  in=284,781,446 out=68,392,349 elapsed=110.1s

  [5986/17668] intraday_14532.csv.gz  in=284,794,618 out=68,405,521 elapsed=110.1s

  [5987/17668] intraday_14534.csv.gz  in=284,805,115 out=68,416,018 elapsed=110.2s

  [5988/17668] intraday_14536.csv.gz  in=284,818,570 out=68,429,473 elapsed=110.2s

  [5989/17668] intraday_14535.csv.gz  in=284,832,198 out=68,443,101 elapsed=110.2s

  [5990/17668] intraday_14533.csv.gz  in=284,847,625 out=68,458,528 elapsed=110.2s

  [5991/17668] intraday_14537.csv.gz  in=284,858,085 out=68,468,988 elapsed=110.2s

  [5992/17668] intraday_14539.csv.gz  in=284,866,961 out=68,477,864 elapsed=110.2s

  [5993/17668] intraday_1454.csv.gz  in=284,879,705 out=68,477,864 elapsed=110.2s

  [5994/17668] intraday_14538.csv.gz  in=284,892,106 out=68,490,265 elapsed=110.2s

  [5995/17668] intraday_14540.csv.gz  in=284,903,710 out=68,501,869 elapsed=110.2s

  [5996/17668] intraday_14541.csv.gz  in=284,912,437 out=68,510,596 elapsed=110.3s

  [5997/17668] intraday_14543.csv.gz  in=284,923,894 out=68,522,053 elapsed=110.3s

  [5998/17668] intraday_14542.csv.gz  in=284,938,390 out=68,536,549 elapsed=110.3s

  [5999/17668] intraday_14545.csv.gz  in=284,949,504 out=68,547,663 elapsed=110.3s

  [6000/17668] intraday_14544.csv.gz  in=284,964,117 out=68,562,276 elapsed=110.3s

  [6001/17668] intraday_14546.csv.gz  in=284,975,380 out=68,573,539 elapsed=110.3s

  [6002/17668] intraday_14548.csv.gz  in=284,987,865 out=68,586,024 elapsed=110.4s

  [6003/17668] intraday_14547.csv.gz  in=285,000,327 out=68,598,486 elapsed=110.4s

  [6004/17668] intraday_1455.csv.gz  in=285,012,568 out=68,598,486 elapsed=110.4s

  [6005/17668] intraday_14549.csv.gz  in=285,024,169 out=68,610,087 elapsed=110.4s

  [6006/17668] intraday_14550.csv.gz  in=285,037,301 out=68,623,219 elapsed=110.4s

  [6007/17668] intraday_14551.csv.gz  in=285,049,470 out=68,635,388 elapsed=110.4s

  [6008/17668] intraday_14553.csv.gz  in=285,059,805 out=68,645,723 elapsed=110.4s

  [6009/17668] intraday_14552.csv.gz  in=285,069,975 out=68,655,893 elapsed=110.4s

  [6010/17668] intraday_14554.csv.gz  in=285,081,197 out=68,667,115 elapsed=110.4s

  [6011/17668] intraday_14555.csv.gz  in=285,082,363 out=68,668,281 elapsed=110.4s

  [6012/17668] intraday_14556.csv.gz  in=285,090,704 out=68,676,622 elapsed=110.4s

  [6013/17668] intraday_14557.csv.gz  in=285,108,670 out=68,693,607 elapsed=110.5s

  [6014/17668] intraday_14558.csv.gz  in=285,118,644 out=68,703,581 elapsed=110.5s

  [6015/17668] intraday_1456.csv.gz  in=285,129,752 out=68,703,581 elapsed=110.5s

  [6016/17668] intraday_14559.csv.gz  in=285,140,022 out=68,713,851 elapsed=110.5s

  [6017/17668] intraday_14560.csv.gz  in=285,154,573 out=68,728,402 elapsed=110.5s

  [6018/17668] intraday_14561.csv.gz  in=285,166,061 out=68,739,890 elapsed=110.5s

  [6019/17668] intraday_14563.csv.gz  in=285,177,978 out=68,751,807 elapsed=110.5s

  [6020/17668] intraday_14564.csv.gz  in=285,191,004 out=68,764,833 elapsed=110.6s

  [6021/17668] intraday_14562.csv.gz  in=285,203,232 out=68,777,061 elapsed=110.6s

  [6022/17668] intraday_14565.csv.gz  in=285,216,081 out=68,789,910 elapsed=110.6s

  [6023/17668] intraday_14566.csv.gz  in=285,225,882 out=68,799,711 elapsed=110.6s

  [6024/17668] intraday_14567.csv.gz  in=285,237,589 out=68,811,418 elapsed=110.6s

  [6025/17668] intraday_14568.csv.gz  in=285,247,925 out=68,821,754 elapsed=110.6s

  [6026/17668] intraday_14569.csv.gz  in=285,260,621 out=68,834,450 elapsed=110.6s

  [6027/17668] intraday_1457.csv.gz  in=285,273,184 out=68,834,450 elapsed=110.6s

  [6028/17668] intraday_14570.csv.gz  in=285,285,052 out=68,846,318 elapsed=110.7s

  [6029/17668] intraday_14571.csv.gz  in=285,285,100 out=68,846,366 elapsed=110.7s

  [6030/17668] intraday_14573.csv.gz  in=285,297,134 out=68,858,400 elapsed=110.7s

  [6031/17668] intraday_14572.csv.gz  in=285,314,305 out=68,873,734 elapsed=110.7s

  [6032/17668] intraday_14574.csv.gz  in=285,325,900 out=68,885,329 elapsed=110.7s

  [6033/17668] intraday_14575.csv.gz  in=285,335,313 out=68,894,742 elapsed=110.7s

  [6034/17668] intraday_14576.csv.gz  in=285,347,419 out=68,906,848 elapsed=110.7s

  [6035/17668] intraday_14577.csv.gz  in=285,355,692 out=68,915,056 elapsed=110.7s

  [6036/17668] intraday_14578.csv.gz  in=285,365,999 out=68,925,363 elapsed=110.8s

  [6037/17668] intraday_14579.csv.gz  in=285,378,426 out=68,937,790 elapsed=110.8s

  [6038/17668] intraday_1458.csv.gz  in=285,391,308 out=68,937,790 elapsed=110.8s

  [6039/17668] intraday_14580.csv.gz  in=285,403,478 out=68,949,960 elapsed=110.8s

  [6040/17668] intraday_14581.csv.gz  in=285,416,008 out=68,962,490 elapsed=110.8s

  [6041/17668] intraday_14582.csv.gz  in=285,430,631 out=68,977,113 elapsed=110.8s

  [6042/17668] intraday_14584.csv.gz  in=285,437,566 out=68,984,048 elapsed=110.8s

  [6043/17668] intraday_14585.csv.gz  in=285,439,750 out=68,986,232 elapsed=110.8s

  [6044/17668] intraday_14583.csv.gz  in=285,463,181 out=69,005,924 elapsed=110.8s

  [6045/17668] intraday_14586.csv.gz  in=285,473,297 out=69,016,040 elapsed=110.9s

  [6046/17668] intraday_14587.csv.gz  in=285,485,400 out=69,028,143 elapsed=110.9s

  [6047/17668] intraday_14588.csv.gz  in=285,500,150 out=69,042,893 elapsed=110.9s

  [6048/17668] intraday_14589.csv.gz  in=285,511,604 out=69,054,347 elapsed=110.9s

  [6049/17668] intraday_1459.csv.gz  in=285,528,660 out=69,054,347 elapsed=110.9s

  [6050/17668] intraday_14590.csv.gz  in=285,539,499 out=69,065,186 elapsed=110.9s

  [6051/17668] intraday_14592.csv.gz  in=285,551,036 out=69,076,723 elapsed=110.9s

  [6052/17668] intraday_14591.csv.gz  in=285,563,057 out=69,088,744 elapsed=110.9s

  [6053/17668] intraday_14593.csv.gz  in=285,572,440 out=69,098,127 elapsed=111.0s

  [6054/17668] intraday_14594.csv.gz  in=285,583,454 out=69,109,141 elapsed=111.0s

  [6055/17668] intraday_14596.csv.gz  in=285,593,864 out=69,119,551 elapsed=111.0s

  [6056/17668] intraday_14597.csv.gz  in=285,605,427 out=69,131,114 elapsed=111.0s

  [6057/17668] intraday_14595.csv.gz  in=285,617,319 out=69,143,006 elapsed=111.0s

  [6058/17668] intraday_14598.csv.gz  in=285,623,867 out=69,149,554 elapsed=111.0s

  [6059/17668] intraday_14599.csv.gz  in=285,632,133 out=69,157,820 elapsed=111.0s

  [6060/17668] intraday_1460.csv.gz  in=285,644,010 out=69,157,820 elapsed=111.0s

  [6061/17668] intraday_14600.csv.gz  in=285,657,237 out=69,171,047 elapsed=111.1s

  [6062/17668] intraday_14601.csv.gz  in=285,670,835 out=69,184,645 elapsed=111.1s

  [6063/17668] intraday_14604.csv.gz  in=285,681,020 out=69,194,830 elapsed=111.1s

  [6064/17668] intraday_14603.csv.gz  in=285,691,162 out=69,204,972 elapsed=111.1s

  [6065/17668] intraday_14602.csv.gz  in=285,702,836 out=69,216,646 elapsed=111.1s

  [6066/17668] intraday_14605.csv.gz  in=285,714,647 out=69,228,457 elapsed=111.1s

  [6067/17668] intraday_14606.csv.gz  in=285,726,841 out=69,240,233 elapsed=111.2s

  [6068/17668] intraday_14608.csv.gz  in=285,739,074 out=69,252,466 elapsed=111.2s

  [6069/17668] intraday_14607.csv.gz  in=285,750,531 out=69,263,923 elapsed=111.2s

  [6070/17668] intraday_14609.csv.gz  in=285,760,397 out=69,273,789 elapsed=111.2s

  [6071/17668] intraday_1461.csv.gz  in=285,771,947 out=69,273,789 elapsed=111.2s

  [6072/17668] intraday_14611.csv.gz  in=285,784,761 out=69,286,603 elapsed=111.2s

  [6073/17668] intraday_14612.csv.gz  in=285,786,138 out=69,287,980 elapsed=111.2s

  [6074/17668] intraday_14610.csv.gz  in=285,794,461 out=69,296,303 elapsed=111.2s

  [6075/17668] intraday_14613.csv.gz  in=285,797,143 out=69,298,985 elapsed=111.2s

  [6076/17668] intraday_14614.csv.gz  in=285,806,690 out=69,308,532 elapsed=111.2s

  [6077/17668] intraday_14615.csv.gz  in=285,817,800 out=69,319,642 elapsed=111.3s

  [6078/17668] intraday_14617.csv.gz  in=285,833,766 out=69,335,608 elapsed=111.3s

  [6079/17668] intraday_14618.csv.gz  in=285,847,315 out=69,349,157 elapsed=111.3s

  [6080/17668] intraday_14616.csv.gz  in=285,860,571 out=69,362,413 elapsed=111.3s

  [6081/17668] intraday_14619.csv.gz  in=285,872,284 out=69,374,126 elapsed=111.3s

  [6082/17668] intraday_1462.csv.gz  in=285,884,516 out=69,374,126 elapsed=111.3s

  [6083/17668] intraday_14620.csv.gz  in=285,894,974 out=69,384,584 elapsed=111.3s

  [6084/17668] intraday_14621.csv.gz  in=285,906,236 out=69,395,846 elapsed=111.4s

  [6085/17668] intraday_14622.csv.gz  in=285,919,973 out=69,409,583 elapsed=111.4s

  [6086/17668] intraday_14623.csv.gz  in=285,931,883 out=69,421,493 elapsed=111.4s

  [6087/17668] intraday_14624.csv.gz  in=285,941,485 out=69,431,095 elapsed=111.4s

  [6088/17668] intraday_14625.csv.gz  in=285,955,520 out=69,445,130 elapsed=111.4s

  [6089/17668] intraday_14626.csv.gz  in=285,965,372 out=69,454,982 elapsed=111.4s

  [6090/17668] intraday_14627.csv.gz  in=285,975,951 out=69,465,561 elapsed=111.4s

  [6091/17668] intraday_14628.csv.gz  in=285,988,205 out=69,477,815 elapsed=111.4s

  [6092/17668] intraday_1463.csv.gz  in=286,001,391 out=69,477,815 elapsed=111.4s

  [6093/17668] intraday_14629.csv.gz  in=286,012,636 out=69,489,060 elapsed=111.4s

  [6094/17668] intraday_14630.csv.gz  in=286,024,301 out=69,500,725 elapsed=111.5s

  [6095/17668] intraday_14631.csv.gz  in=286,034,453 out=69,510,877 elapsed=111.5s

  [6096/17668] intraday_14632.csv.gz  in=286,044,953 out=69,521,377 elapsed=111.5s

  [6097/17668] intraday_14635.csv.gz  in=286,057,731 out=69,534,155 elapsed=111.5s

  [6098/17668] intraday_14633.csv.gz  in=286,070,101 out=69,546,525 elapsed=111.5s

  [6099/17668] intraday_14634.csv.gz  in=286,085,482 out=69,561,906 elapsed=111.5s

  [6100/17668] intraday_14636.csv.gz  in=286,097,208 out=69,573,632 elapsed=111.5s

  [6101/17668] intraday_14637.csv.gz  in=286,108,672 out=69,585,096 elapsed=111.6s

  [6102/17668] intraday_14638.csv.gz  in=286,118,445 out=69,594,869 elapsed=111.6s

  [6103/17668] intraday_14639.csv.gz  in=286,131,692 out=69,608,116 elapsed=111.6s

  [6104/17668] intraday_1464.csv.gz  in=286,148,386 out=69,608,116 elapsed=111.6s

  [6105/17668] intraday_14640.csv.gz  in=286,159,431 out=69,619,161 elapsed=111.6s

  [6106/17668] intraday_14641.csv.gz  in=286,170,395 out=69,630,125 elapsed=111.6s

  [6107/17668] intraday_14642.csv.gz  in=286,183,978 out=69,643,708 elapsed=111.6s

  [6108/17668] intraday_14644.csv.gz  in=286,195,179 out=69,654,909 elapsed=111.6s

  [6109/17668] intraday_14643.csv.gz  in=286,209,029 out=69,668,759 elapsed=111.7s

  [6110/17668] intraday_14646.csv.gz  in=286,221,266 out=69,680,996 elapsed=111.7s

  [6111/17668] intraday_14645.csv.gz  in=286,232,626 out=69,692,356 elapsed=111.7s

  [6112/17668] intraday_14647.csv.gz  in=286,243,942 out=69,703,672 elapsed=111.7s

  [6113/17668] intraday_14648.csv.gz  in=286,257,568 out=69,717,298 elapsed=111.7s

  [6114/17668] intraday_14649.csv.gz  in=286,271,334 out=69,731,064 elapsed=111.7s

  [6115/17668] intraday_1465.csv.gz  in=286,284,667 out=69,731,064 elapsed=111.7s

  [6116/17668] intraday_14651.csv.gz  in=286,296,458 out=69,742,855 elapsed=111.8s

  [6117/17668] intraday_14650.csv.gz  in=286,313,781 out=69,760,178 elapsed=111.8s

  [6118/17668] intraday_14652.csv.gz  in=286,328,060 out=69,774,457 elapsed=111.8s

  [6119/17668] intraday_14653.csv.gz  in=286,338,258 out=69,784,655 elapsed=111.8s

  [6120/17668] intraday_14654.csv.gz  in=286,350,543 out=69,796,940 elapsed=111.8s

  [6121/17668] intraday_14655.csv.gz  in=286,361,206 out=69,807,603 elapsed=111.8s

  [6122/17668] intraday_14657.csv.gz  in=286,371,471 out=69,817,868 elapsed=111.8s

  [6123/17668] intraday_14656.csv.gz  in=286,383,324 out=69,829,684 elapsed=111.8s

  [6124/17668] intraday_14658.csv.gz  in=286,395,499 out=69,841,859 elapsed=111.8s

  [6125/17668] intraday_14659.csv.gz  in=286,406,319 out=69,852,679 elapsed=111.8s

  [6126/17668] intraday_1466.csv.gz  in=286,420,668 out=69,852,679 elapsed=111.8s

  [6127/17668] intraday_14661.csv.gz  in=286,429,697 out=69,861,708 elapsed=111.9s

  [6128/17668] intraday_14660.csv.gz  in=286,443,777 out=69,875,788 elapsed=111.9s

  [6129/17668] intraday_14663.csv.gz  in=286,454,498 out=69,886,509 elapsed=111.9s

  [6130/17668] intraday_14664.csv.gz  in=286,467,670 out=69,899,681 elapsed=111.9s

  [6131/17668] intraday_14662.csv.gz  in=286,478,052 out=69,910,063 elapsed=111.9s

  [6132/17668] intraday_14665.csv.gz  in=286,490,846 out=69,922,620 elapsed=111.9s

  [6133/17668] intraday_14666.csv.gz  in=286,503,991 out=69,935,765 elapsed=111.9s

  [6134/17668] intraday_14668.csv.gz  in=286,517,684 out=69,949,458 elapsed=112.0s

  [6135/17668] intraday_14667.csv.gz  in=286,530,780 out=69,962,554 elapsed=112.0s

  [6136/17668] intraday_1467.csv.gz  in=286,546,098 out=69,962,554 elapsed=112.0s

  [6137/17668] intraday_14669.csv.gz  in=286,558,612 out=69,975,068 elapsed=112.0s

  [6138/17668] intraday_14670.csv.gz  in=286,570,212 out=69,986,668 elapsed=112.0s

  [6139/17668] intraday_14671.csv.gz  in=286,582,366 out=69,998,822 elapsed=112.0s

  [6140/17668] intraday_14672.csv.gz  in=286,594,730 out=70,011,186 elapsed=112.0s

  [6141/17668] intraday_14673.csv.gz  in=286,604,831 out=70,021,287 elapsed=112.0s

  [6142/17668] intraday_14674.csv.gz  in=286,620,019 out=70,036,475 elapsed=112.1s

  [6143/17668] intraday_14676.csv.gz  in=286,628,732 out=70,045,188 elapsed=112.1s

  [6144/17668] intraday_14675.csv.gz  in=286,639,419 out=70,055,875 elapsed=112.1s

  [6145/17668] intraday_14679.csv.gz  in=286,640,320 out=70,056,776 elapsed=112.1s

  [6146/17668] intraday_14678.csv.gz  in=286,640,552 out=70,057,008 elapsed=112.1s

  [6147/17668] intraday_14677.csv.gz  in=286,652,674 out=70,069,130 elapsed=112.1s

  [6148/17668] intraday_14680.csv.gz  in=286,652,827 out=70,069,283 elapsed=112.1s

  [6149/17668] intraday_14681.csv.gz  in=286,653,345 out=70,069,801 elapsed=112.1s

  [6150/17668] intraday_14682.csv.gz  in=286,653,613 out=70,070,069 elapsed=112.1s

  [6151/17668] intraday_1468.csv.gz  in=286,669,484 out=70,070,069 elapsed=112.1s

  [6152/17668] intraday_14683.csv.gz  in=286,669,875 out=70,070,460 elapsed=112.1s

  [6153/17668] intraday_14685.csv.gz  in=286,670,447 out=70,071,032 elapsed=112.1s

  [6154/17668] intraday_14686.csv.gz  in=286,670,670 out=70,071,255 elapsed=112.1s

  [6155/17668] intraday_14684.csv.gz  in=286,671,226 out=70,071,811 elapsed=112.1s

  [6156/17668] intraday_14688.csv.gz  in=286,671,450 out=70,072,035 elapsed=112.1s

  [6157/17668] intraday_14687.csv.gz  in=286,671,810 out=70,072,395 elapsed=112.2s

  [6158/17668] intraday_14689.csv.gz  in=286,672,640 out=70,073,225 elapsed=112.2s

  [6159/17668] intraday_14690.csv.gz  in=286,673,020 out=70,073,605 elapsed=112.2s

  [6160/17668] intraday_14691.csv.gz  in=286,673,448 out=70,074,033 elapsed=112.2s

  [6161/17668] intraday_14692.csv.gz  in=286,674,082 out=70,074,667 elapsed=112.2s

  [6162/17668] intraday_1469.csv.gz  in=286,688,679 out=70,074,667 elapsed=112.2s

  [6163/17668] intraday_14693.csv.gz  in=286,689,047 out=70,075,035 elapsed=112.2s

  [6164/17668] intraday_14694.csv.gz  in=286,689,185 out=70,075,173 elapsed=112.2s

  [6165/17668] intraday_14697.csv.gz  in=286,689,429 out=70,075,417 elapsed=112.2s

  [6166/17668] intraday_14695.csv.gz  in=286,690,179 out=70,076,167 elapsed=112.2s

  [6167/17668] intraday_14698.csv.gz  in=286,690,507 out=70,076,495 elapsed=112.2s

  [6168/17668] intraday_14699.csv.gz  in=286,691,078 out=70,077,066 elapsed=112.2s

  [6169/17668] intraday_1470.csv.gz  in=286,704,927 out=70,077,066 elapsed=112.2s

  [6170/17668] intraday_14696.csv.gz  in=286,705,462 out=70,077,601 elapsed=112.2s

  [6171/17668] intraday_14700.csv.gz  in=286,705,594 out=70,077,733 elapsed=112.2s

  [6172/17668] intraday_14701.csv.gz  in=286,706,026 out=70,078,165 elapsed=112.2s

  [6173/17668] intraday_14703.csv.gz  in=286,706,383 out=70,078,522 elapsed=112.2s

  [6174/17668] intraday_14702.csv.gz  in=286,706,642 out=70,078,781 elapsed=112.2s

  [6175/17668] intraday_14704.csv.gz  in=286,706,950 out=70,079,089 elapsed=112.2s

  [6176/17668] intraday_14705.csv.gz  in=286,707,264 out=70,079,403 elapsed=112.3s

  [6177/17668] intraday_14707.csv.gz  in=286,707,920 out=70,080,059 elapsed=112.3s

  [6178/17668] intraday_14708.csv.gz  in=286,708,522 out=70,080,661 elapsed=112.3s

  [6179/17668] intraday_14706.csv.gz  in=286,708,577 out=70,080,716 elapsed=112.3s

  [6180/17668] intraday_14709.csv.gz  in=286,709,505 out=70,081,644 elapsed=112.3s

  [6181/17668] intraday_14710.csv.gz  in=286,709,801 out=70,081,940 elapsed=112.3s

  [6182/17668] intraday_14711.csv.gz  in=286,709,994 out=70,082,133 elapsed=112.3s

  [6183/17668] intraday_14713.csv.gz  in=286,710,185 out=70,082,324 elapsed=112.3s

  [6184/17668] intraday_14714.csv.gz  in=286,710,496 out=70,082,635 elapsed=112.3s

  [6185/17668] intraday_14712.csv.gz  in=286,710,843 out=70,082,982 elapsed=112.3s

  [6186/17668] intraday_1471.csv.gz  in=286,724,691 out=70,082,982 elapsed=112.3s

  [6187/17668] intraday_14716.csv.gz  in=286,725,047 out=70,083,338 elapsed=112.3s

  [6188/17668] intraday_14715.csv.gz  in=286,725,402 out=70,083,693 elapsed=112.3s

  [6189/17668] intraday_14717.csv.gz  in=286,725,553 out=70,083,844 elapsed=112.3s

  [6190/17668] intraday_14718.csv.gz  in=286,725,617 out=70,083,908 elapsed=112.3s

  [6191/17668] intraday_14721.csv.gz  in=286,726,237 out=70,084,528 elapsed=112.3s

  [6192/17668] intraday_14719.csv.gz  in=286,726,303 out=70,084,594 elapsed=112.3s

  [6193/17668] intraday_14720.csv.gz  in=286,726,621 out=70,084,912 elapsed=112.3s

  [6194/17668] intraday_14722.csv.gz  in=286,726,684 out=70,084,975 elapsed=112.4s

  [6195/17668] intraday_14723.csv.gz  in=286,727,045 out=70,085,336 elapsed=112.4s

  [6196/17668] intraday_14724.csv.gz  in=286,727,209 out=70,085,500 elapsed=112.4s

  [6197/17668] intraday_1472.csv.gz  in=286,740,524 out=70,085,500 elapsed=112.4s

  [6198/17668] intraday_14726.csv.gz  in=286,740,714 out=70,085,690 elapsed=112.4s

  [6199/17668] intraday_14725.csv.gz  in=286,741,037 out=70,086,013 elapsed=112.4s

  [6200/17668] intraday_14727.csv.gz  in=286,741,386 out=70,086,362 elapsed=112.4s

  [6201/17668] intraday_14728.csv.gz  in=286,741,532 out=70,086,508 elapsed=112.4s

  [6202/17668] intraday_14729.csv.gz  in=286,741,661 out=70,086,637 elapsed=112.4s

  [6203/17668] intraday_14730.csv.gz  in=286,742,447 out=70,087,423 elapsed=112.4s

  [6204/17668] intraday_14731.csv.gz  in=286,743,137 out=70,088,113 elapsed=112.4s

  [6205/17668] intraday_14732.csv.gz  in=286,743,521 out=70,088,497 elapsed=112.4s

  [6206/17668] intraday_1473.csv.gz  in=286,755,168 out=70,088,497 elapsed=112.4s

  [6207/17668] intraday_14734.csv.gz  in=286,755,306 out=70,088,635 elapsed=112.4s

  [6208/17668] intraday_14733.csv.gz  in=286,756,040 out=70,089,369 elapsed=112.4s

  [6209/17668] intraday_14735.csv.gz  in=286,756,161 out=70,089,490 elapsed=112.4s

  [6210/17668] intraday_14736.csv.gz  in=286,756,350 out=70,089,679 elapsed=112.4s

  [6211/17668] intraday_14737.csv.gz  in=286,756,716 out=70,090,045 elapsed=112.4s

  [6212/17668] intraday_14739.csv.gz  in=286,756,877 out=70,090,206 elapsed=112.4s

  [6213/17668] intraday_14738.csv.gz  in=286,757,069 out=70,090,398 elapsed=112.4s

  [6214/17668] intraday_14740.csv.gz  in=286,757,538 out=70,090,867 elapsed=112.5s

  [6215/17668] intraday_14741.csv.gz  in=286,757,641 out=70,090,970 elapsed=112.5s

  [6216/17668] intraday_1474.csv.gz  in=286,770,157 out=70,090,970 elapsed=112.5s

  [6217/17668] intraday_14742.csv.gz  in=286,770,192 out=70,091,005 elapsed=112.5s

  [6218/17668] intraday_14743.csv.gz  in=286,770,824 out=70,091,637 elapsed=112.5s

  [6219/17668] intraday_14744.csv.gz  in=286,771,753 out=70,092,566 elapsed=112.5s

  [6220/17668] intraday_14745.csv.gz  in=286,771,835 out=70,092,648 elapsed=112.5s

  [6221/17668] intraday_14746.csv.gz  in=286,772,036 out=70,092,849 elapsed=112.5s

  [6222/17668] intraday_14748.csv.gz  in=286,772,653 out=70,093,466 elapsed=112.5s

  [6223/17668] intraday_14747.csv.gz  in=286,773,161 out=70,093,974 elapsed=112.5s

  [6224/17668] intraday_14749.csv.gz  in=286,773,449 out=70,094,262 elapsed=112.5s

  [6225/17668] intraday_14750.csv.gz  in=286,773,992 out=70,094,805 elapsed=112.5s

  [6226/17668] intraday_14751.csv.gz  in=286,774,205 out=70,095,018 elapsed=112.5s

  [6227/17668] intraday_14752.csv.gz  in=286,774,404 out=70,095,217 elapsed=112.5s

  [6228/17668] intraday_14753.csv.gz  in=286,775,127 out=70,095,940 elapsed=112.5s

  [6229/17668] intraday_1475.csv.gz  in=286,789,301 out=70,095,940 elapsed=112.5s

  [6230/17668] intraday_14755.csv.gz  in=286,789,593 out=70,096,232 elapsed=112.5s

  [6231/17668] intraday_14754.csv.gz  in=286,789,786 out=70,096,425 elapsed=112.5s

  [6232/17668] intraday_14756.csv.gz  in=286,790,141 out=70,096,780 elapsed=112.5s

  [6233/17668] intraday_14757.csv.gz  in=286,790,331 out=70,096,970 elapsed=112.5s

  [6234/17668] intraday_14758.csv.gz  in=286,790,640 out=70,097,279 elapsed=112.5s

  [6235/17668] intraday_14759.csv.gz  in=286,790,740 out=70,097,379 elapsed=112.6s

  [6236/17668] intraday_14760.csv.gz  in=286,791,126 out=70,097,765 elapsed=112.6s

  [6237/17668] intraday_14761.csv.gz  in=286,791,833 out=70,098,472 elapsed=112.6s

  [6238/17668] intraday_14762.csv.gz  in=286,792,998 out=70,099,637 elapsed=112.6s

  [6239/17668] intraday_1476.csv.gz  in=286,805,781 out=70,099,637 elapsed=112.6s

  [6240/17668] intraday_14764.csv.gz  in=286,806,668 out=70,100,524 elapsed=112.6s

  [6241/17668] intraday_14763.csv.gz  in=286,807,679 out=70,101,535 elapsed=112.6s

  [6242/17668] intraday_14765.csv.gz  in=286,808,163 out=70,102,019 elapsed=112.6s

  [6243/17668] intraday_14766.csv.gz  in=286,808,782 out=70,102,638 elapsed=112.6s

  [6244/17668] intraday_14767.csv.gz  in=286,808,915 out=70,102,771 elapsed=112.6s

  [6245/17668] intraday_14768.csv.gz  in=286,810,044 out=70,103,900 elapsed=112.6s

  [6246/17668] intraday_14769.csv.gz  in=286,810,215 out=70,104,051 elapsed=112.6s

  [6247/17668] intraday_14770.csv.gz  in=286,810,521 out=70,104,357 elapsed=112.6s

  [6248/17668] intraday_14771.csv.gz  in=286,810,884 out=70,104,720 elapsed=112.6s

  [6249/17668] intraday_14772.csv.gz  in=286,811,217 out=70,105,053 elapsed=112.6s

  [6250/17668] intraday_1477.csv.gz  in=286,825,232 out=70,105,053 elapsed=112.6s

  [6251/17668] intraday_14774.csv.gz  in=286,825,441 out=70,105,262 elapsed=112.6s

  [6252/17668] intraday_14775.csv.gz  in=286,825,724 out=70,105,545 elapsed=112.6s

  [6253/17668] intraday_14773.csv.gz  in=286,831,284 out=70,109,487 elapsed=112.7s

  [6254/17668] intraday_14777.csv.gz  in=286,831,835 out=70,110,038 elapsed=112.7s

  [6255/17668] intraday_14778.csv.gz  in=286,832,079 out=70,110,282 elapsed=112.7s

  [6256/17668] intraday_14776.csv.gz  in=286,832,339 out=70,110,542 elapsed=112.7s

  [6257/17668] intraday_14779.csv.gz  in=286,832,856 out=70,111,059 elapsed=112.7s

  [6258/17668] intraday_14780.csv.gz  in=286,833,293 out=70,111,496 elapsed=112.7s

  [6259/17668] intraday_14781.csv.gz  in=286,834,615 out=70,112,818 elapsed=112.7s

  [6260/17668] intraday_1478.csv.gz  in=286,847,151 out=70,112,818 elapsed=112.7s

  [6261/17668] intraday_14784.csv.gz  in=286,847,368 out=70,113,035 elapsed=112.7s

  [6262/17668] intraday_14783.csv.gz  in=286,847,818 out=70,113,485 elapsed=112.7s

  [6263/17668] intraday_14782.csv.gz  in=286,848,999 out=70,114,145 elapsed=112.7s

  [6264/17668] intraday_14785.csv.gz  in=286,849,750 out=70,114,896 elapsed=112.7s

  [6265/17668] intraday_14786.csv.gz  in=286,849,850 out=70,114,996 elapsed=112.7s

  [6266/17668] intraday_14787.csv.gz  in=286,850,245 out=70,115,391 elapsed=112.7s

  [6267/17668] intraday_14788.csv.gz  in=286,850,493 out=70,115,639 elapsed=112.7s

  [6268/17668] intraday_14789.csv.gz  in=286,850,929 out=70,116,075 elapsed=112.7s

  [6269/17668] intraday_14790.csv.gz  in=286,851,270 out=70,116,416 elapsed=112.7s

  [6270/17668] intraday_14791.csv.gz  in=286,851,590 out=70,116,736 elapsed=112.8s

  [6271/17668] intraday_14792.csv.gz  in=286,852,547 out=70,117,693 elapsed=112.8s

  [6272/17668] intraday_14793.csv.gz  in=286,853,252 out=70,118,398 elapsed=112.8s

  [6273/17668] intraday_1479.csv.gz  in=286,866,210 out=70,118,398 elapsed=112.8s

  [6274/17668] intraday_14794.csv.gz  in=286,867,410 out=70,119,598 elapsed=112.8s

  [6275/17668] intraday_14796.csv.gz  in=286,868,163 out=70,120,351 elapsed=112.8s

  [6276/17668] intraday_14798.csv.gz  in=286,868,378 out=70,120,566 elapsed=112.8s

  [6277/17668] intraday_14795.csv.gz  in=286,869,619 out=70,121,807 elapsed=112.8s

  [6278/17668] intraday_14797.csv.gz  in=286,870,633 out=70,122,821 elapsed=112.8s

  [6279/17668] intraday_14799.csv.gz  in=286,871,001 out=70,123,189 elapsed=112.8s

  [6280/17668] intraday_14801.csv.gz  in=286,871,175 out=70,123,363 elapsed=112.8s

  [6281/17668] intraday_14800.csv.gz  in=286,871,375 out=70,123,563 elapsed=112.8s

  [6282/17668] intraday_14802.csv.gz  in=286,871,860 out=70,124,048 elapsed=112.8s

  [6283/17668] intraday_14803.csv.gz  in=286,872,138 out=70,124,326 elapsed=112.8s

  [6284/17668] intraday_1480.csv.gz  in=286,885,541 out=70,124,326 elapsed=112.8s

  [6285/17668] intraday_14805.csv.gz  in=286,886,008 out=70,124,793 elapsed=112.8s

  [6286/17668] intraday_14804.csv.gz  in=286,886,412 out=70,125,197 elapsed=112.8s

  [6287/17668] intraday_14806.csv.gz  in=286,887,059 out=70,125,844 elapsed=112.8s

  [6288/17668] intraday_14807.csv.gz  in=286,887,355 out=70,126,140 elapsed=112.8s

  [6289/17668] intraday_14808.csv.gz  in=286,887,815 out=70,126,600 elapsed=112.8s

  [6290/17668] intraday_14809.csv.gz  in=286,888,188 out=70,126,973 elapsed=112.8s

  [6291/17668] intraday_14810.csv.gz  in=286,888,945 out=70,127,730 elapsed=112.8s

  [6292/17668] intraday_14813.csv.gz  in=286,889,472 out=70,128,257 elapsed=112.9s

  [6293/17668] intraday_14811.csv.gz  in=286,889,783 out=70,128,568 elapsed=112.9s

  [6294/17668] intraday_14812.csv.gz  in=286,890,037 out=70,128,822 elapsed=112.9s

  [6295/17668] intraday_1481.csv.gz  in=286,903,035 out=70,128,822 elapsed=112.9s

  [6296/17668] intraday_14814.csv.gz  in=286,903,370 out=70,129,157 elapsed=112.9s

  [6297/17668] intraday_14815.csv.gz  in=286,903,595 out=70,129,382 elapsed=112.9s

  [6298/17668] intraday_14816.csv.gz  in=286,904,425 out=70,130,212 elapsed=112.9s

  [6299/17668] intraday_14817.csv.gz  in=286,904,759 out=70,130,546 elapsed=112.9s

  [6300/17668] intraday_14818.csv.gz  in=286,904,955 out=70,130,742 elapsed=112.9s

  [6301/17668] intraday_14819.csv.gz  in=286,905,516 out=70,131,303 elapsed=112.9s

  [6302/17668] intraday_14820.csv.gz  in=286,906,094 out=70,131,881 elapsed=112.9s

  [6303/17668] intraday_14821.csv.gz  in=286,906,626 out=70,132,413 elapsed=112.9s

  [6304/17668] intraday_14822.csv.gz  in=286,906,898 out=70,132,685 elapsed=112.9s

  [6305/17668] intraday_14823.csv.gz  in=286,906,952 out=70,132,739 elapsed=112.9s

  [6306/17668] intraday_1482.csv.gz  in=286,921,335 out=70,132,739 elapsed=112.9s

  [6307/17668] intraday_14824.csv.gz  in=286,936,296 out=70,147,700 elapsed=113.0s

  [6308/17668] intraday_14825.csv.gz  in=286,947,323 out=70,158,727 elapsed=113.0s

  [6309/17668] intraday_14826.csv.gz  in=286,961,107 out=70,172,511 elapsed=113.0s

  [6310/17668] intraday_14827.csv.gz  in=286,971,628 out=70,183,032 elapsed=113.0s

  [6311/17668] intraday_14828.csv.gz  in=286,983,703 out=70,195,107 elapsed=113.0s

  [6312/17668] intraday_1483.csv.gz  in=286,998,757 out=70,195,107 elapsed=113.0s

  [6313/17668] intraday_14829.csv.gz  in=287,011,371 out=70,207,721 elapsed=113.0s

  [6314/17668] intraday_14831.csv.gz  in=287,022,784 out=70,219,134 elapsed=113.1s

  [6315/17668] intraday_14830.csv.gz  in=287,035,869 out=70,232,219 elapsed=113.1s

  [6316/17668] intraday_14832.csv.gz  in=287,047,638 out=70,243,988 elapsed=113.1s

  [6317/17668] intraday_14834.csv.gz  in=287,058,240 out=70,254,590 elapsed=113.1s

  [6318/17668] intraday_14833.csv.gz  in=287,070,435 out=70,266,785 elapsed=113.1s

  [6319/17668] intraday_14835.csv.gz  in=287,081,838 out=70,278,188 elapsed=113.2s

  [6320/17668] intraday_14836.csv.gz  in=287,093,146 out=70,289,496 elapsed=113.2s

  [6321/17668] intraday_14837.csv.gz  in=287,106,011 out=70,302,361 elapsed=113.2s

  [6322/17668] intraday_14839.csv.gz  in=287,114,394 out=70,310,744 elapsed=113.2s

  [6323/17668] intraday_14838.csv.gz  in=287,124,545 out=70,320,895 elapsed=113.2s

  [6324/17668] intraday_1484.csv.gz  in=287,139,130 out=70,320,895 elapsed=113.2s

  [6325/17668] intraday_14840.csv.gz  in=287,153,534 out=70,335,299 elapsed=113.2s

  [6326/17668] intraday_14841.csv.gz  in=287,166,153 out=70,347,918 elapsed=113.2s

  [6327/17668] intraday_14843.csv.gz  in=287,176,434 out=70,358,199 elapsed=113.3s

  [6328/17668] intraday_14842.csv.gz  in=287,188,383 out=70,370,148 elapsed=113.3s

  [6329/17668] intraday_14844.csv.gz  in=287,201,625 out=70,383,390 elapsed=113.3s

  [6330/17668] intraday_14845.csv.gz  in=287,213,009 out=70,394,774 elapsed=113.3s

  [6331/17668] intraday_14846.csv.gz  in=287,225,644 out=70,407,409 elapsed=113.3s

  [6332/17668] intraday_14847.csv.gz  in=287,237,530 out=70,419,295 elapsed=113.3s

  [6333/17668] intraday_14848.csv.gz  in=287,250,350 out=70,432,115 elapsed=113.3s

  [6334/17668] intraday_1485.csv.gz  in=287,264,088 out=70,432,115 elapsed=113.3s

  [6335/17668] intraday_14849.csv.gz  in=287,276,322 out=70,444,349 elapsed=113.3s

  [6336/17668] intraday_14850.csv.gz  in=287,286,721 out=70,454,616 elapsed=113.4s

  [6337/17668] intraday_14851.csv.gz  in=287,298,233 out=70,466,128 elapsed=113.4s

  [6338/17668] intraday_14853.csv.gz  in=287,311,920 out=70,479,815 elapsed=113.4s

  [6339/17668] intraday_14852.csv.gz  in=287,322,768 out=70,490,663 elapsed=113.4s

  [6340/17668] intraday_14854.csv.gz  in=287,338,298 out=70,506,193 elapsed=113.4s

  [6341/17668] intraday_14855.csv.gz  in=287,350,163 out=70,518,058 elapsed=113.4s

  [6342/17668] intraday_14856.csv.gz  in=287,361,146 out=70,529,041 elapsed=113.4s

  [6343/17668] intraday_14857.csv.gz  in=287,373,169 out=70,541,064 elapsed=113.5s

  [6344/17668] intraday_14859.csv.gz  in=287,384,775 out=70,552,670 elapsed=113.5s

  [6345/17668] intraday_1486.csv.gz  in=287,399,463 out=70,552,670 elapsed=113.5s

  [6346/17668] intraday_14858.csv.gz  in=287,411,783 out=70,564,990 elapsed=113.5s

  [6347/17668] intraday_14860.csv.gz  in=287,424,394 out=70,577,601 elapsed=113.5s

  [6348/17668] intraday_14861.csv.gz  in=287,434,265 out=70,587,472 elapsed=113.5s

  [6349/17668] intraday_14862.csv.gz  in=287,446,148 out=70,599,355 elapsed=113.5s

  [6350/17668] intraday_14863.csv.gz  in=287,455,003 out=70,608,210 elapsed=113.5s

  [6351/17668] intraday_14864.csv.gz  in=287,466,465 out=70,619,672 elapsed=113.5s

  [6352/17668] intraday_14865.csv.gz  in=287,478,371 out=70,631,578 elapsed=113.6s

  [6353/17668] intraday_14866.csv.gz  in=287,492,063 out=70,645,270 elapsed=113.6s

  [6354/17668] intraday_14869.csv.gz  in=287,502,357 out=70,655,564 elapsed=113.6s

  [6355/17668] intraday_14868.csv.gz  in=287,515,604 out=70,668,811 elapsed=113.6s

  [6356/17668] intraday_14867.csv.gz  in=287,527,410 out=70,680,617 elapsed=113.6s

  [6357/17668] intraday_1487.csv.gz  in=287,540,376 out=70,680,617 elapsed=113.6s

  [6358/17668] intraday_14870.csv.gz  in=287,551,547 out=70,691,788 elapsed=113.6s

  [6359/17668] intraday_14871.csv.gz  in=287,564,668 out=70,704,909 elapsed=113.6s

  [6360/17668] intraday_14873.csv.gz  in=287,575,490 out=70,715,731 elapsed=113.6s

  [6361/17668] intraday_14874.csv.gz  in=287,586,804 out=70,727,045 elapsed=113.7s

  [6362/17668] intraday_14872.csv.gz  in=287,605,711 out=70,745,034 elapsed=113.7s

  [6363/17668] intraday_14875.csv.gz  in=287,615,838 out=70,755,161 elapsed=113.7s

  [6364/17668] intraday_14876.csv.gz  in=287,629,464 out=70,768,787 elapsed=113.7s

  [6365/17668] intraday_14877.csv.gz  in=287,642,288 out=70,781,611 elapsed=113.7s

  [6366/17668] intraday_14878.csv.gz  in=287,653,631 out=70,792,954 elapsed=113.7s

  [6367/17668] intraday_1488.csv.gz  in=287,669,789 out=70,792,954 elapsed=113.7s

  [6368/17668] intraday_14879.csv.gz  in=287,682,382 out=70,805,547 elapsed=113.8s

  [6369/17668] intraday_14880.csv.gz  in=287,692,978 out=70,816,143 elapsed=113.8s

  [6370/17668] intraday_14881.csv.gz  in=287,703,352 out=70,826,517 elapsed=113.8s

  [6371/17668] intraday_14882.csv.gz  in=287,713,773 out=70,836,938 elapsed=113.8s

  [6372/17668] intraday_14883.csv.gz  in=287,726,074 out=70,849,239 elapsed=113.8s

  [6373/17668] intraday_14884.csv.gz  in=287,737,003 out=70,860,168 elapsed=113.8s

  [6374/17668] intraday_14887.csv.gz  in=287,747,801 out=70,870,966 elapsed=113.8s

  [6375/17668] intraday_14886.csv.gz  in=287,758,368 out=70,881,533 elapsed=113.8s

  [6376/17668] intraday_14885.csv.gz  in=287,769,924 out=70,893,089 elapsed=113.9s

  [6377/17668] intraday_14888.csv.gz  in=287,779,786 out=70,902,951 elapsed=113.9s

  [6378/17668] intraday_1489.csv.gz  in=287,792,203 out=70,902,951 elapsed=113.9s

  [6379/17668] intraday_14889.csv.gz  in=287,805,877 out=70,916,625 elapsed=113.9s

  [6380/17668] intraday_14891.csv.gz  in=287,819,076 out=70,929,824 elapsed=113.9s

  [6381/17668] intraday_14890.csv.gz  in=287,830,982 out=70,941,730 elapsed=113.9s

  [6382/17668] intraday_14892.csv.gz  in=287,842,752 out=70,953,500 elapsed=113.9s

  [6383/17668] intraday_14893.csv.gz  in=287,853,851 out=70,964,599 elapsed=114.0s

  [6384/17668] intraday_14895.csv.gz  in=287,865,752 out=70,976,500 elapsed=114.0s

  [6385/17668] intraday_14894.csv.gz  in=287,877,315 out=70,988,063 elapsed=114.0s

  [6386/17668] intraday_14896.csv.gz  in=287,888,802 out=70,999,550 elapsed=114.0s

  [6387/17668] intraday_14897.csv.gz  in=287,900,282 out=71,011,030 elapsed=114.0s

  [6388/17668] intraday_14898.csv.gz  in=287,912,740 out=71,023,488 elapsed=114.0s

  [6389/17668] intraday_1490.csv.gz  in=287,927,153 out=71,023,488 elapsed=114.0s

  [6390/17668] intraday_14899.csv.gz  in=287,936,906 out=71,033,241 elapsed=114.0s

  [6391/17668] intraday_14900.csv.gz  in=287,946,337 out=71,042,672 elapsed=114.1s

  [6392/17668] intraday_14901.csv.gz  in=287,959,102 out=71,055,437 elapsed=114.1s

  [6393/17668] intraday_14902.csv.gz  in=287,969,738 out=71,066,073 elapsed=114.1s

  [6394/17668] intraday_14903.csv.gz  in=287,981,819 out=71,078,154 elapsed=114.1s

  [6395/17668] intraday_14904.csv.gz  in=287,992,152 out=71,088,396 elapsed=114.1s

  [6396/17668] intraday_14905.csv.gz  in=288,001,814 out=71,098,058 elapsed=114.1s

  [6397/17668] intraday_14906.csv.gz  in=288,014,413 out=71,110,657 elapsed=114.1s

  [6398/17668] intraday_14907.csv.gz  in=288,026,560 out=71,122,804 elapsed=114.1s

  [6399/17668] intraday_14908.csv.gz  in=288,043,071 out=71,139,315 elapsed=114.1s

  [6400/17668] intraday_1491.csv.gz  in=288,059,543 out=71,139,315 elapsed=114.2s

  [6401/17668] intraday_14909.csv.gz  in=288,072,631 out=71,152,403 elapsed=114.2s

  [6402/17668] intraday_14910.csv.gz  in=288,085,463 out=71,165,235 elapsed=114.2s

  [6403/17668] intraday_14911.csv.gz  in=288,096,039 out=71,175,811 elapsed=114.2s

  [6404/17668] intraday_14913.csv.gz  in=288,108,209 out=71,187,981 elapsed=114.2s

  [6405/17668] intraday_14912.csv.gz  in=288,119,848 out=71,199,620 elapsed=114.2s

  [6406/17668] intraday_14914.csv.gz  in=288,131,845 out=71,211,617 elapsed=114.2s

  [6407/17668] intraday_14915.csv.gz  in=288,142,446 out=71,222,218 elapsed=114.2s

  [6408/17668] intraday_14916.csv.gz  in=288,156,020 out=71,235,792 elapsed=114.3s

  [6409/17668] intraday_14917.csv.gz  in=288,166,191 out=71,245,963 elapsed=114.3s

  [6410/17668] intraday_14918.csv.gz  in=288,176,476 out=71,256,248 elapsed=114.3s

  [6411/17668] intraday_14919.csv.gz  in=288,190,283 out=71,270,055 elapsed=114.3s

  [6412/17668] intraday_1492.csv.gz  in=288,203,948 out=71,270,055 elapsed=114.3s

  [6413/17668] intraday_14921.csv.gz  in=288,216,493 out=71,282,600 elapsed=114.3s

  [6414/17668] intraday_14920.csv.gz  in=288,228,498 out=71,294,605 elapsed=114.3s

  [6415/17668] intraday_14922.csv.gz  in=288,239,330 out=71,305,437 elapsed=114.3s

  [6416/17668] intraday_14923.csv.gz  in=288,249,892 out=71,315,999 elapsed=114.3s

  [6417/17668] intraday_14924.csv.gz  in=288,261,502 out=71,327,609 elapsed=114.4s

  [6418/17668] intraday_14926.csv.gz  in=288,274,524 out=71,340,631 elapsed=114.4s

  [6419/17668] intraday_14925.csv.gz  in=288,287,206 out=71,353,313 elapsed=114.4s

  [6420/17668] intraday_14928.csv.gz  in=288,298,301 out=71,364,408 elapsed=114.4s

  [6421/17668] intraday_14929.csv.gz  in=288,309,730 out=71,375,837 elapsed=114.4s

  [6422/17668] intraday_1493.csv.gz  in=288,323,764 out=71,375,837 elapsed=114.4s

  [6423/17668] intraday_14927.csv.gz  in=288,335,228 out=71,387,301 elapsed=114.4s

  [6424/17668] intraday_14930.csv.gz  in=288,346,912 out=71,398,985 elapsed=114.4s

  [6425/17668] intraday_14931.csv.gz  in=288,359,724 out=71,411,797 elapsed=114.5s

  [6426/17668] intraday_14932.csv.gz  in=288,370,190 out=71,422,263 elapsed=114.5s

  [6427/17668] intraday_14933.csv.gz  in=288,383,947 out=71,436,020 elapsed=114.5s

  [6428/17668] intraday_14935.csv.gz  in=288,395,778 out=71,447,851 elapsed=114.6s

  [6429/17668] intraday_14936.csv.gz  in=288,407,247 out=71,459,320 elapsed=114.6s

  [6430/17668] intraday_14934.csv.gz  in=288,420,208 out=71,472,281 elapsed=114.6s

  [6431/17668] intraday_14937.csv.gz  in=288,432,651 out=71,484,724 elapsed=114.6s

  [6432/17668] intraday_14938.csv.gz  in=288,445,570 out=71,497,643 elapsed=114.6s

  [6433/17668] intraday_14939.csv.gz  in=288,457,961 out=71,510,034 elapsed=114.6s

  [6434/17668] intraday_1494.csv.gz  in=288,473,628 out=71,510,034 elapsed=114.6s

  [6435/17668] intraday_14940.csv.gz  in=288,487,158 out=71,523,564 elapsed=114.6s

  [6436/17668] intraday_14941.csv.gz  in=288,504,067 out=71,540,473 elapsed=114.6s

  [6437/17668] intraday_14942.csv.gz  in=288,516,721 out=71,553,127 elapsed=114.7s

  [6438/17668] intraday_14944.csv.gz  in=288,526,884 out=71,563,290 elapsed=114.7s

  [6439/17668] intraday_14943.csv.gz  in=288,543,116 out=71,579,522 elapsed=114.7s

  [6440/17668] intraday_14945.csv.gz  in=288,555,812 out=71,592,218 elapsed=114.7s

  [6441/17668] intraday_14946.csv.gz  in=288,566,611 out=71,603,017 elapsed=114.7s

  [6442/17668] intraday_14947.csv.gz  in=288,578,723 out=71,615,129 elapsed=114.7s

  [6443/17668] intraday_14948.csv.gz  in=288,589,667 out=71,626,073 elapsed=114.7s

  [6444/17668] intraday_1495.csv.gz  in=288,600,843 out=71,626,073 elapsed=114.7s

  [6445/17668] intraday_14949.csv.gz  in=288,613,095 out=71,638,325 elapsed=114.7s

  [6446/17668] intraday_14950.csv.gz  in=288,624,309 out=71,649,539 elapsed=114.8s

  [6447/17668] intraday_14952.csv.gz  in=288,633,803 out=71,659,033 elapsed=114.8s

  [6448/17668] intraday_14951.csv.gz  in=288,650,609 out=71,675,839 elapsed=114.8s

  [6449/17668] intraday_14953.csv.gz  in=288,661,213 out=71,686,443 elapsed=114.8s

  [6450/17668] intraday_14954.csv.gz  in=288,673,110 out=71,698,340 elapsed=114.8s

  [6451/17668] intraday_14955.csv.gz  in=288,684,141 out=71,709,371 elapsed=114.8s

  [6452/17668] intraday_14956.csv.gz  in=288,696,369 out=71,721,599 elapsed=114.8s

  [6453/17668] intraday_14957.csv.gz  in=288,709,357 out=71,734,587 elapsed=114.8s

  [6454/17668] intraday_14959.csv.gz  in=288,722,789 out=71,748,019 elapsed=114.9s

  [6455/17668] intraday_1496.csv.gz  in=288,735,178 out=71,748,019 elapsed=114.9s

  [6456/17668] intraday_14958.csv.gz  in=288,753,685 out=71,765,669 elapsed=114.9s

  [6457/17668] intraday_14960.csv.gz  in=288,769,669 out=71,780,998 elapsed=114.9s

  [6458/17668] intraday_14961.csv.gz  in=288,782,306 out=71,793,635 elapsed=114.9s

  [6459/17668] intraday_14962.csv.gz  in=288,796,014 out=71,807,343 elapsed=114.9s

  [6460/17668] intraday_14963.csv.gz  in=288,808,504 out=71,819,833 elapsed=114.9s

  [6461/17668] intraday_14964.csv.gz  in=288,819,021 out=71,830,350 elapsed=115.0s

  [6462/17668] intraday_14965.csv.gz  in=288,830,974 out=71,842,303 elapsed=115.0s

  [6463/17668] intraday_14967.csv.gz  in=288,839,397 out=71,850,726 elapsed=115.0s

  [6464/17668] intraday_14966.csv.gz  in=288,849,474 out=71,860,803 elapsed=115.0s

  [6465/17668] intraday_14969.csv.gz  in=288,850,752 out=71,862,081 elapsed=115.0s

  [6466/17668] intraday_14968.csv.gz  in=288,863,838 out=71,875,167 elapsed=115.0s

  [6467/17668] intraday_1497.csv.gz  in=288,888,432 out=71,875,167 elapsed=115.0s

  [6468/17668] intraday_14971.csv.gz  in=288,900,350 out=71,887,085 elapsed=115.0s

  [6469/17668] intraday_14970.csv.gz  in=288,915,086 out=71,901,821 elapsed=115.0s

  [6470/17668] intraday_14972.csv.gz  in=288,927,580 out=71,914,315 elapsed=115.1s

  [6471/17668] intraday_14973.csv.gz  in=288,939,627 out=71,926,362 elapsed=115.1s

  [6472/17668] intraday_14974.csv.gz  in=288,950,719 out=71,937,454 elapsed=115.1s

  [6473/17668] intraday_14975.csv.gz  in=288,966,076 out=71,952,811 elapsed=115.1s

  [6474/17668] intraday_14977.csv.gz  in=288,977,459 out=71,964,194 elapsed=115.1s

  [6475/17668] intraday_14978.csv.gz  in=288,989,979 out=71,976,714 elapsed=115.1s

  [6476/17668] intraday_14976.csv.gz  in=289,002,676 out=71,989,411 elapsed=115.1s

  [6477/17668] intraday_14979.csv.gz  in=289,014,932 out=72,001,667 elapsed=115.1s

  [6478/17668] intraday_1498.csv.gz  in=289,030,210 out=72,001,667 elapsed=115.1s

  [6479/17668] intraday_14981.csv.gz  in=289,042,998 out=72,014,455 elapsed=115.2s

  [6480/17668] intraday_14980.csv.gz  in=289,053,992 out=72,025,449 elapsed=115.2s

  [6481/17668] intraday_14982.csv.gz  in=289,066,165 out=72,037,622 elapsed=115.2s

  [6482/17668] intraday_14983.csv.gz  in=289,079,177 out=72,050,634 elapsed=115.2s

  [6483/17668] intraday_14984.csv.gz  in=289,090,310 out=72,061,767 elapsed=115.2s

  [6484/17668] intraday_14985.csv.gz  in=289,099,698 out=72,071,155 elapsed=115.2s

  [6485/17668] intraday_14986.csv.gz  in=289,115,354 out=72,086,811 elapsed=115.2s

  [6486/17668] intraday_14987.csv.gz  in=289,128,797 out=72,100,254 elapsed=115.2s

  [6487/17668] intraday_14988.csv.gz  in=289,139,710 out=72,111,167 elapsed=115.2s

  [6488/17668] intraday_1499.csv.gz  in=289,155,883 out=72,111,167 elapsed=115.2s

  [6489/17668] intraday_14989.csv.gz  in=289,166,913 out=72,122,197 elapsed=115.2s

  [6490/17668] intraday_14990.csv.gz  in=289,180,609 out=72,135,893 elapsed=115.3s

  [6491/17668] intraday_14991.csv.gz  in=289,192,620 out=72,147,904 elapsed=115.3s

  [6492/17668] intraday_14993.csv.gz  in=289,204,865 out=72,160,149 elapsed=115.3s

  [6493/17668] intraday_14992.csv.gz  in=289,217,978 out=72,173,262 elapsed=115.3s

  [6494/17668] intraday_14994.csv.gz  in=289,230,612 out=72,185,896 elapsed=115.3s

  [6495/17668] intraday_14995.csv.gz  in=289,241,329 out=72,196,613 elapsed=115.3s

  [6496/17668] intraday_14996.csv.gz  in=289,253,070 out=72,208,354 elapsed=115.4s

  [6497/17668] intraday_14998.csv.gz  in=289,265,411 out=72,220,695 elapsed=115.4s

  [6498/17668] intraday_14997.csv.gz  in=289,276,968 out=72,232,252 elapsed=115.4s

  [6499/17668] intraday_1500.csv.gz  in=289,291,828 out=72,232,252 elapsed=115.4s

  [6500/17668] intraday_14999.csv.gz  in=289,304,598 out=72,245,022 elapsed=115.4s

  [6501/17668] intraday_15000.csv.gz  in=289,320,718 out=72,261,142 elapsed=115.4s

  [6502/17668] intraday_15003.csv.gz  in=289,334,191 out=72,274,615 elapsed=115.4s

  [6503/17668] intraday_15002.csv.gz  in=289,344,701 out=72,285,125 elapsed=115.4s

  [6504/17668] intraday_15001.csv.gz  in=289,357,877 out=72,298,301 elapsed=115.4s

  [6505/17668] intraday_15004.csv.gz  in=289,371,081 out=72,311,505 elapsed=115.5s

  [6506/17668] intraday_15005.csv.gz  in=289,383,442 out=72,323,866 elapsed=115.5s

  [6507/17668] intraday_15008.csv.gz  in=289,395,504 out=72,335,928 elapsed=115.5s

  [6508/17668] intraday_15007.csv.gz  in=289,404,819 out=72,345,243 elapsed=115.5s

  [6509/17668] intraday_15006.csv.gz  in=289,417,980 out=72,358,404 elapsed=115.5s

  [6510/17668] intraday_15009.csv.gz  in=289,427,509 out=72,367,933 elapsed=115.5s

  [6511/17668] intraday_1501.csv.gz  in=289,442,595 out=72,367,933 elapsed=115.5s

  [6512/17668] intraday_15010.csv.gz  in=289,454,481 out=72,379,819 elapsed=115.5s

  [6513/17668] intraday_15011.csv.gz  in=289,466,304 out=72,391,642 elapsed=115.6s

  [6514/17668] intraday_15012.csv.gz  in=289,481,462 out=72,406,800 elapsed=115.6s

  [6515/17668] intraday_15013.csv.gz  in=289,493,038 out=72,418,376 elapsed=115.6s

  [6516/17668] intraday_15015.csv.gz  in=289,503,585 out=72,428,923 elapsed=115.6s

  [6517/17668] intraday_15014.csv.gz  in=289,517,790 out=72,443,128 elapsed=115.6s

  [6518/17668] intraday_15016.csv.gz  in=289,528,841 out=72,454,179 elapsed=115.6s

  [6519/17668] intraday_15017.csv.gz  in=289,541,569 out=72,466,907 elapsed=115.6s

  [6520/17668] intraday_15018.csv.gz  in=289,554,244 out=72,479,582 elapsed=115.7s

  [6521/17668] intraday_1502.csv.gz  in=289,569,348 out=72,479,582 elapsed=115.7s

  [6522/17668] intraday_15019.csv.gz  in=289,581,263 out=72,491,497 elapsed=115.7s

  [6523/17668] intraday_15020.csv.gz  in=289,592,181 out=72,502,415 elapsed=115.7s

  [6524/17668] intraday_15021.csv.gz  in=289,605,357 out=72,515,591 elapsed=115.7s

  [6525/17668] intraday_15023.csv.gz  in=289,617,826 out=72,528,060 elapsed=115.7s

  [6526/17668] intraday_15024.csv.gz  in=289,630,493 out=72,540,727 elapsed=115.7s

  [6527/17668] intraday_15022.csv.gz  in=289,642,575 out=72,552,809 elapsed=115.7s

  [6528/17668] intraday_15025.csv.gz  in=289,655,510 out=72,565,744 elapsed=115.8s

  [6529/17668] intraday_15027.csv.gz  in=289,664,858 out=72,575,092 elapsed=115.8s

  [6530/17668] intraday_15026.csv.gz  in=289,677,040 out=72,587,274 elapsed=115.8s

  [6531/17668] intraday_15028.csv.gz  in=289,690,362 out=72,600,596 elapsed=115.8s

  [6532/17668] intraday_1503.csv.gz  in=289,705,412 out=72,600,596 elapsed=115.8s

  [6533/17668] intraday_15030.csv.gz  in=289,716,354 out=72,611,538 elapsed=115.8s

  [6534/17668] intraday_15031.csv.gz  in=289,728,690 out=72,623,874 elapsed=115.9s

  [6535/17668] intraday_15029.csv.gz  in=289,762,448 out=72,651,823 elapsed=115.9s

  [6536/17668] intraday_15032.csv.gz  in=289,773,620 out=72,662,995 elapsed=115.9s

  [6537/17668] intraday_15033.csv.gz  in=289,783,766 out=72,673,141 elapsed=115.9s

  [6538/17668] intraday_15034.csv.gz  in=289,795,008 out=72,684,383 elapsed=115.9s

  [6539/17668] intraday_15035.csv.gz  in=289,808,418 out=72,697,793 elapsed=115.9s

  [6540/17668] intraday_15036.csv.gz  in=289,821,104 out=72,710,479 elapsed=115.9s

  [6541/17668] intraday_15038.csv.gz  in=289,833,951 out=72,723,326 elapsed=115.9s

  [6542/17668] intraday_15037.csv.gz  in=289,847,190 out=72,736,565 elapsed=115.9s

  [6543/17668] intraday_15039.csv.gz  in=289,857,869 out=72,747,244 elapsed=115.9s

  [6544/17668] intraday_1504.csv.gz  in=289,871,840 out=72,747,244 elapsed=115.9s

  [6545/17668] intraday_15041.csv.gz  in=289,885,523 out=72,760,927 elapsed=116.0s

  [6546/17668] intraday_15040.csv.gz  in=289,896,124 out=72,771,528 elapsed=116.0s

  [6547/17668] intraday_15042.csv.gz  in=289,906,851 out=72,782,255 elapsed=116.0s

  [6548/17668] intraday_15045.csv.gz  in=289,916,555 out=72,791,959 elapsed=116.0s

  [6549/17668] intraday_15043.csv.gz  in=289,930,178 out=72,805,582 elapsed=116.0s

  [6550/17668] intraday_15044.csv.gz  in=289,941,572 out=72,816,976 elapsed=116.0s

  [6551/17668] intraday_15046.csv.gz  in=289,951,728 out=72,827,132 elapsed=116.0s

  [6552/17668] intraday_15047.csv.gz  in=289,965,174 out=72,840,578 elapsed=116.1s

  [6553/17668] intraday_15048.csv.gz  in=289,975,908 out=72,851,312 elapsed=116.1s

  [6554/17668] intraday_1505.csv.gz  in=289,992,423 out=72,851,312 elapsed=116.1s

  [6555/17668] intraday_15049.csv.gz  in=290,005,098 out=72,863,987 elapsed=116.1s

  [6556/17668] intraday_15050.csv.gz  in=290,015,315 out=72,874,204 elapsed=116.1s

  [6557/17668] intraday_15051.csv.gz  in=290,025,601 out=72,884,490 elapsed=116.1s

  [6558/17668] intraday_15052.csv.gz  in=290,039,524 out=72,898,413 elapsed=116.2s

  [6559/17668] intraday_15053.csv.gz  in=290,052,901 out=72,911,790 elapsed=116.2s

  [6560/17668] intraday_15055.csv.gz  in=290,065,681 out=72,924,570 elapsed=116.2s

  [6561/17668] intraday_15054.csv.gz  in=290,080,504 out=72,939,393 elapsed=116.2s

  [6562/17668] intraday_15056.csv.gz  in=290,093,217 out=72,952,106 elapsed=116.2s

  [6563/17668] intraday_15057.csv.gz  in=290,105,451 out=72,964,340 elapsed=116.2s

  [6564/17668] intraday_15058.csv.gz  in=290,116,263 out=72,975,152 elapsed=116.2s

  [6565/17668] intraday_15059.csv.gz  in=290,130,544 out=72,989,433 elapsed=116.2s

  [6566/17668] intraday_1506.csv.gz  in=290,146,802 out=72,989,433 elapsed=116.2s

  [6567/17668] intraday_15060.csv.gz  in=290,158,156 out=73,000,787 elapsed=116.2s

  [6568/17668] intraday_15061.csv.gz  in=290,169,048 out=73,011,679 elapsed=116.3s

  [6569/17668] intraday_15062.csv.gz  in=290,182,508 out=73,025,139 elapsed=116.3s

  [6570/17668] intraday_15063.csv.gz  in=290,193,561 out=73,036,192 elapsed=116.3s

  [6571/17668] intraday_15064.csv.gz  in=290,205,400 out=73,048,031 elapsed=116.3s

  [6572/17668] intraday_15065.csv.gz  in=290,219,584 out=73,062,215 elapsed=116.3s

  [6573/17668] intraday_15068.csv.gz  in=290,231,800 out=73,074,431 elapsed=116.3s

  [6574/17668] intraday_15067.csv.gz  in=290,243,654 out=73,086,285 elapsed=116.3s

  [6575/17668] intraday_15066.csv.gz  in=290,256,867 out=73,099,498 elapsed=116.3s

  [6576/17668] intraday_1507.csv.gz  in=290,270,221 out=73,099,498 elapsed=116.4s

  [6577/17668] intraday_15071.csv.gz  in=290,284,000 out=73,113,277 elapsed=116.4s

  [6578/17668] intraday_15070.csv.gz  in=290,295,938 out=73,125,215 elapsed=116.4s

  [6579/17668] intraday_15069.csv.gz  in=290,307,497 out=73,136,774 elapsed=116.4s

  [6580/17668] intraday_15072.csv.gz  in=290,319,144 out=73,148,421 elapsed=116.4s

  [6581/17668] intraday_15073.csv.gz  in=290,331,745 out=73,161,022 elapsed=116.4s

  [6582/17668] intraday_15075.csv.gz  in=290,342,135 out=73,171,412 elapsed=116.4s

  [6583/17668] intraday_15074.csv.gz  in=290,355,798 out=73,185,075 elapsed=116.4s

  [6584/17668] intraday_15076.csv.gz  in=290,371,203 out=73,200,480 elapsed=116.5s

  [6585/17668] intraday_15077.csv.gz  in=290,381,787 out=73,211,064 elapsed=116.5s

  [6586/17668] intraday_15078.csv.gz  in=290,393,484 out=73,222,761 elapsed=116.5s

  [6587/17668] intraday_15079.csv.gz  in=290,406,744 out=73,236,021 elapsed=116.5s

  [6588/17668] intraday_1508.csv.gz  in=290,422,248 out=73,236,021 elapsed=116.5s

  [6589/17668] intraday_15080.csv.gz  in=290,437,252 out=73,251,025 elapsed=116.5s

  [6590/17668] intraday_15082.csv.gz  in=290,452,005 out=73,265,778 elapsed=116.5s

  [6591/17668] intraday_15081.csv.gz  in=290,462,181 out=73,275,954 elapsed=116.5s

  [6592/17668] intraday_15084.csv.gz  in=290,474,327 out=73,288,100 elapsed=116.6s

  [6593/17668] intraday_15083.csv.gz  in=290,488,262 out=73,302,035 elapsed=116.6s

  [6594/17668] intraday_15085.csv.gz  in=290,500,238 out=73,314,011 elapsed=116.6s

  [6595/17668] intraday_15086.csv.gz  in=290,517,258 out=73,331,031 elapsed=116.6s

  [6596/17668] intraday_15088.csv.gz  in=290,532,670 out=73,346,443 elapsed=116.6s

  [6597/17668] intraday_15087.csv.gz  in=290,549,590 out=73,363,363 elapsed=116.6s

  [6598/17668] intraday_15089.csv.gz  in=290,564,234 out=73,378,007 elapsed=116.6s

  [6599/17668] intraday_1509.csv.gz  in=290,575,953 out=73,378,007 elapsed=116.6s

  [6600/17668] intraday_15090.csv.gz  in=290,587,264 out=73,389,318 elapsed=116.6s

  [6601/17668] intraday_15091.csv.gz  in=290,599,482 out=73,401,536 elapsed=116.7s

  [6602/17668] intraday_15093.csv.gz  in=290,612,745 out=73,414,799 elapsed=116.7s

  [6603/17668] intraday_15094.csv.gz  in=290,623,779 out=73,425,833 elapsed=116.7s

  [6604/17668] intraday_15092.csv.gz  in=290,633,791 out=73,435,845 elapsed=116.7s

  [6605/17668] intraday_15095.csv.gz  in=290,646,220 out=73,448,274 elapsed=116.7s

  [6606/17668] intraday_15097.csv.gz  in=290,660,056 out=73,462,110 elapsed=116.7s

  [6607/17668] intraday_15096.csv.gz  in=290,672,741 out=73,474,795 elapsed=116.8s

  [6608/17668] intraday_15098.csv.gz  in=290,683,605 out=73,485,659 elapsed=116.8s

  [6609/17668] intraday_15099.csv.gz  in=290,695,252 out=73,497,306 elapsed=116.8s

  [6610/17668] intraday_1510.csv.gz  in=290,706,651 out=73,497,306 elapsed=116.8s

  [6611/17668] intraday_15100.csv.gz  in=290,719,304 out=73,509,959 elapsed=116.8s

  [6612/17668] intraday_15102.csv.gz  in=290,731,084 out=73,521,739 elapsed=116.8s

  [6613/17668] intraday_15101.csv.gz  in=290,744,719 out=73,535,374 elapsed=116.8s

  [6614/17668] intraday_15103.csv.gz  in=290,758,363 out=73,549,018 elapsed=116.8s

  [6615/17668] intraday_15105.csv.gz  in=290,770,499 out=73,561,154 elapsed=116.9s

  [6616/17668] intraday_15106.csv.gz  in=290,786,350 out=73,577,005 elapsed=116.9s

  [6617/17668] intraday_15104.csv.gz  in=290,801,026 out=73,591,681 elapsed=116.9s

  [6618/17668] intraday_15107.csv.gz  in=290,812,105 out=73,602,760 elapsed=116.9s

  [6619/17668] intraday_15108.csv.gz  in=290,825,919 out=73,616,574 elapsed=116.9s

  [6620/17668] intraday_15109.csv.gz  in=290,838,112 out=73,628,767 elapsed=116.9s

  [6621/17668] intraday_1511.csv.gz  in=290,852,745 out=73,628,767 elapsed=116.9s

  [6622/17668] intraday_15110.csv.gz  in=290,862,727 out=73,638,749 elapsed=116.9s

  [6623/17668] intraday_15111.csv.gz  in=290,875,473 out=73,651,495 elapsed=117.0s

  [6624/17668] intraday_15112.csv.gz  in=290,882,904 out=73,658,926 elapsed=117.0s

  [6625/17668] intraday_15114.csv.gz  in=290,896,294 out=73,670,871 elapsed=117.0s

  [6626/17668] intraday_15115.csv.gz  in=290,910,501 out=73,685,078 elapsed=117.0s

  [6627/17668] intraday_15116.csv.gz  in=290,923,357 out=73,697,934 elapsed=117.0s

  [6628/17668] intraday_15113.csv.gz  in=290,976,227 out=73,729,893 elapsed=117.0s

  [6629/17668] intraday_15118.csv.gz  in=290,988,193 out=73,741,859 elapsed=117.1s

  [6630/17668] intraday_15119.csv.gz  in=290,999,380 out=73,753,046 elapsed=117.1s

  [6631/17668] intraday_15117.csv.gz  in=291,011,341 out=73,765,007 elapsed=117.1s

  [6632/17668] intraday_1512.csv.gz  in=291,023,998 out=73,765,007 elapsed=117.1s

  [6633/17668] intraday_15120.csv.gz  in=291,038,942 out=73,779,951 elapsed=117.1s

  [6634/17668] intraday_15121.csv.gz  in=291,052,297 out=73,793,306 elapsed=117.1s

  [6635/17668] intraday_15122.csv.gz  in=291,062,749 out=73,803,758 elapsed=117.1s

  [6636/17668] intraday_15123.csv.gz  in=291,074,086 out=73,815,095 elapsed=117.1s

  [6637/17668] intraday_15125.csv.gz  in=291,084,823 out=73,825,832 elapsed=117.2s

  [6638/17668] intraday_15124.csv.gz  in=291,096,717 out=73,837,726 elapsed=117.2s

  [6639/17668] intraday_15126.csv.gz  in=291,110,570 out=73,851,579 elapsed=117.2s

  [6640/17668] intraday_15127.csv.gz  in=291,122,907 out=73,863,916 elapsed=117.2s

  [6641/17668] intraday_15128.csv.gz  in=291,135,581 out=73,876,590 elapsed=117.2s

  [6642/17668] intraday_15129.csv.gz  in=291,145,528 out=73,886,537 elapsed=117.2s

  [6643/17668] intraday_1513.csv.gz  in=291,156,408 out=73,886,537 elapsed=117.2s

  [6644/17668] intraday_15130.csv.gz  in=291,165,425 out=73,895,554 elapsed=117.2s

  [6645/17668] intraday_15131.csv.gz  in=291,181,163 out=73,911,292 elapsed=117.3s

  [6646/17668] intraday_15134.csv.gz  in=291,193,842 out=73,923,971 elapsed=117.3s

  [6647/17668] intraday_15132.csv.gz  in=291,205,932 out=73,936,061 elapsed=117.3s

  [6648/17668] intraday_15135.csv.gz  in=291,218,054 out=73,948,183 elapsed=117.3s

  [6649/17668] intraday_15133.csv.gz  in=291,228,025 out=73,958,154 elapsed=117.3s

  [6650/17668] intraday_15137.csv.gz  in=291,240,143 out=73,970,272 elapsed=117.3s

  [6651/17668] intraday_15136.csv.gz  in=291,253,273 out=73,983,402 elapsed=117.3s

  [6652/17668] intraday_15138.csv.gz  in=291,265,822 out=73,995,951 elapsed=117.3s

  [6653/17668] intraday_15139.csv.gz  in=291,281,992 out=74,011,039 elapsed=117.4s

  [6654/17668] intraday_1514.csv.gz  in=291,290,839 out=74,011,039 elapsed=117.4s

  [6655/17668] intraday_15140.csv.gz  in=291,301,579 out=74,021,779 elapsed=117.4s

  [6656/17668] intraday_15142.csv.gz  in=291,312,649 out=74,032,849 elapsed=117.4s

  [6657/17668] intraday_15143.csv.gz  in=291,324,913 out=74,045,113 elapsed=117.4s

  [6658/17668] intraday_15141.csv.gz  in=291,336,206 out=74,056,406 elapsed=117.4s

  [6659/17668] intraday_15144.csv.gz  in=291,348,658 out=74,068,858 elapsed=117.4s

  [6660/17668] intraday_15145.csv.gz  in=291,364,158 out=74,084,358 elapsed=117.4s

  [6661/17668] intraday_15146.csv.gz  in=291,376,235 out=74,096,435 elapsed=117.5s

  [6662/17668] intraday_15148.csv.gz  in=291,389,155 out=74,109,355 elapsed=117.5s

  [6663/17668] intraday_15149.csv.gz  in=291,402,298 out=74,122,498 elapsed=117.5s

  [6664/17668] intraday_1515.csv.gz  in=291,413,157 out=74,122,498 elapsed=117.5s

  [6665/17668] intraday_15147.csv.gz  in=291,423,609 out=74,132,950 elapsed=117.5s

  [6666/17668] intraday_15150.csv.gz  in=291,435,952 out=74,145,293 elapsed=117.5s

  [6667/17668] intraday_15152.csv.gz  in=291,447,156 out=74,156,497 elapsed=117.5s

  [6668/17668] intraday_15153.csv.gz  in=291,456,563 out=74,165,904 elapsed=117.5s

  [6669/17668] intraday_15154.csv.gz  in=291,466,733 out=74,176,074 elapsed=117.5s

  [6670/17668] intraday_15151.csv.gz  in=291,479,468 out=74,188,809 elapsed=117.5s

  [6671/17668] intraday_15155.csv.gz  in=291,490,813 out=74,200,154 elapsed=117.6s

  [6672/17668] intraday_15157.csv.gz  in=291,504,219 out=74,213,560 elapsed=117.6s

  [6673/17668] intraday_15158.csv.gz  in=291,517,405 out=74,226,746 elapsed=117.6s

  [6674/17668] intraday_15156.csv.gz  in=291,529,763 out=74,239,104 elapsed=117.6s

  [6675/17668] intraday_15159.csv.gz  in=291,542,643 out=74,251,984 elapsed=117.6s

  [6676/17668] intraday_1516.csv.gz  in=291,548,709 out=74,251,984 elapsed=117.6s

  [6677/17668] intraday_15160.csv.gz  in=291,559,834 out=74,263,109 elapsed=117.7s

  [6678/17668] intraday_15161.csv.gz  in=291,571,455 out=74,274,730 elapsed=117.7s

  [6679/17668] intraday_15162.csv.gz  in=291,584,335 out=74,287,610 elapsed=117.7s

  [6680/17668] intraday_15163.csv.gz  in=291,594,994 out=74,298,269 elapsed=117.7s

  [6681/17668] intraday_15164.csv.gz  in=291,607,002 out=74,310,277 elapsed=117.7s

  [6682/17668] intraday_15165.csv.gz  in=291,616,940 out=74,320,215 elapsed=117.7s

  [6683/17668] intraday_15167.csv.gz  in=291,628,972 out=74,332,247 elapsed=117.8s

  [6684/17668] intraday_15166.csv.gz  in=291,643,946 out=74,347,221 elapsed=117.8s

  [6685/17668] intraday_15168.csv.gz  in=291,655,082 out=74,358,357 elapsed=117.8s

  [6686/17668] intraday_15169.csv.gz  in=291,669,244 out=74,372,519 elapsed=117.8s

  [6687/17668] intraday_1517.csv.gz  in=291,684,496 out=74,372,519 elapsed=117.8s

  [6688/17668] intraday_15170.csv.gz  in=291,695,813 out=74,383,836 elapsed=117.8s

  [6689/17668] intraday_15172.csv.gz  in=291,707,354 out=74,395,377 elapsed=117.8s

  [6690/17668] intraday_15171.csv.gz  in=291,719,301 out=74,407,324 elapsed=117.8s

  [6691/17668] intraday_15173.csv.gz  in=291,730,996 out=74,419,019 elapsed=117.8s

  [6692/17668] intraday_15174.csv.gz  in=291,744,347 out=74,432,370 elapsed=117.9s

  [6693/17668] intraday_15176.csv.gz  in=291,754,042 out=74,442,065 elapsed=117.9s

  [6694/17668] intraday_15175.csv.gz  in=291,765,560 out=74,453,583 elapsed=117.9s

  [6695/17668] intraday_15177.csv.gz  in=291,777,832 out=74,465,855 elapsed=117.9s

  [6696/17668] intraday_15178.csv.gz  in=291,786,885 out=74,474,908 elapsed=117.9s

  [6697/17668] intraday_1518.csv.gz  in=291,800,999 out=74,474,908 elapsed=117.9s

  [6698/17668] intraday_15179.csv.gz  in=291,813,880 out=74,487,789 elapsed=117.9s

  [6699/17668] intraday_15180.csv.gz  in=291,827,876 out=74,501,785 elapsed=118.0s

  [6700/17668] intraday_15181.csv.gz  in=291,839,846 out=74,513,755 elapsed=118.0s

  [6701/17668] intraday_15182.csv.gz  in=291,851,662 out=74,525,571 elapsed=118.0s

  [6702/17668] intraday_15183.csv.gz  in=291,865,027 out=74,538,936 elapsed=118.0s

  [6703/17668] intraday_15184.csv.gz  in=291,873,532 out=74,547,441 elapsed=118.0s

  [6704/17668] intraday_15185.csv.gz  in=291,886,664 out=74,560,573 elapsed=118.0s

  [6705/17668] intraday_15187.csv.gz  in=291,898,981 out=74,572,890 elapsed=118.0s

  [6706/17668] intraday_15186.csv.gz  in=291,910,298 out=74,584,207 elapsed=118.0s

  [6707/17668] intraday_15188.csv.gz  in=291,919,938 out=74,593,847 elapsed=118.0s

  [6708/17668] intraday_15189.csv.gz  in=291,933,077 out=74,606,986 elapsed=118.1s

  [6709/17668] intraday_1519.csv.gz  in=291,945,008 out=74,606,986 elapsed=118.1s

  [6710/17668] intraday_15190.csv.gz  in=291,953,943 out=74,615,921 elapsed=118.1s

  [6711/17668] intraday_15191.csv.gz  in=291,965,858 out=74,627,836 elapsed=118.1s

  [6712/17668] intraday_15194.csv.gz  in=291,977,191 out=74,639,169 elapsed=118.1s

  [6713/17668] intraday_15192.csv.gz  in=291,989,564 out=74,651,542 elapsed=118.1s

  [6714/17668] intraday_15195.csv.gz  in=291,999,430 out=74,661,408 elapsed=118.1s

  [6715/17668] intraday_15193.csv.gz  in=292,010,654 out=74,672,632 elapsed=118.1s

  [6716/17668] intraday_15196.csv.gz  in=292,022,145 out=74,684,123 elapsed=118.1s

  [6717/17668] intraday_15197.csv.gz  in=292,034,145 out=74,696,123 elapsed=118.2s

  [6718/17668] intraday_15198.csv.gz  in=292,050,794 out=74,712,772 elapsed=118.2s

  [6719/17668] intraday_15199.csv.gz  in=292,062,342 out=74,724,320 elapsed=118.2s

  [6720/17668] intraday_1520.csv.gz  in=292,074,435 out=74,724,320 elapsed=118.2s

  [6721/17668] intraday_15200.csv.gz  in=292,088,774 out=74,738,659 elapsed=118.2s

  [6722/17668] intraday_15201.csv.gz  in=292,099,542 out=74,749,427 elapsed=118.2s

  [6723/17668] intraday_15203.csv.gz  in=292,109,741 out=74,759,626 elapsed=118.2s

  [6724/17668] intraday_15202.csv.gz  in=292,123,328 out=74,773,213 elapsed=118.2s

  [6725/17668] intraday_15205.csv.gz  in=292,133,146 out=74,783,031 elapsed=118.2s

  [6726/17668] intraday_15204.csv.gz  in=292,148,002 out=74,797,887 elapsed=118.2s

  [6727/17668] intraday_15206.csv.gz  in=292,160,561 out=74,810,446 elapsed=118.2s

  [6728/17668] intraday_15207.csv.gz  in=292,173,296 out=74,823,042 elapsed=118.3s

  [6729/17668] intraday_15208.csv.gz  in=292,183,919 out=74,833,665 elapsed=118.3s

  [6730/17668] intraday_1521.csv.gz  in=292,197,530 out=74,833,665 elapsed=118.3s

  [6731/17668] intraday_15209.csv.gz  in=292,210,724 out=74,846,859 elapsed=118.3s

  [6732/17668] intraday_15210.csv.gz  in=292,223,116 out=74,859,251 elapsed=118.3s

  [6733/17668] intraday_15213.csv.gz  in=292,234,853 out=74,870,988 elapsed=118.3s

  [6734/17668] intraday_15212.csv.gz  in=292,245,325 out=74,881,460 elapsed=118.3s

  [6735/17668] intraday_15211.csv.gz  in=292,258,239 out=74,894,374 elapsed=118.4s

  [6736/17668] intraday_15214.csv.gz  in=292,271,402 out=74,907,537 elapsed=118.4s

  [6737/17668] intraday_15215.csv.gz  in=292,284,126 out=74,920,261 elapsed=118.4s

  [6738/17668] intraday_15217.csv.gz  in=292,295,795 out=74,931,930 elapsed=118.4s

  [6739/17668] intraday_15218.csv.gz  in=292,307,886 out=74,944,021 elapsed=118.4s

  [6740/17668] intraday_15216.csv.gz  in=292,320,643 out=74,956,778 elapsed=118.4s

  [6741/17668] intraday_15219.csv.gz  in=292,332,212 out=74,968,347 elapsed=118.5s

  [6742/17668] intraday_1522.csv.gz  in=292,345,791 out=74,968,347 elapsed=118.5s

  [6743/17668] intraday_15220.csv.gz  in=292,358,465 out=74,981,021 elapsed=118.5s

  [6744/17668] intraday_15221.csv.gz  in=292,372,498 out=74,995,054 elapsed=118.5s

  [6745/17668] intraday_15222.csv.gz  in=292,383,934 out=75,006,490 elapsed=118.5s

  [6746/17668] intraday_15223.csv.gz  in=292,396,937 out=75,019,493 elapsed=118.5s

  [6747/17668] intraday_15225.csv.gz  in=292,409,536 out=75,032,092 elapsed=118.5s

  [6748/17668] intraday_15224.csv.gz  in=292,421,966 out=75,044,522 elapsed=118.5s

  [6749/17668] intraday_15226.csv.gz  in=292,436,900 out=75,058,987 elapsed=118.6s

  [6750/17668] intraday_15227.csv.gz  in=292,449,769 out=75,071,856 elapsed=118.6s

  [6751/17668] intraday_15229.csv.gz  in=292,461,527 out=75,083,614 elapsed=118.6s

  [6752/17668] intraday_1523.csv.gz  in=292,474,051 out=75,083,614 elapsed=118.6s

  [6753/17668] intraday_15228.csv.gz  in=292,487,894 out=75,097,457 elapsed=118.6s

  [6754/17668] intraday_15230.csv.gz  in=292,500,855 out=75,110,418 elapsed=118.6s

  [6755/17668] intraday_15232.csv.gz  in=292,513,742 out=75,123,305 elapsed=118.6s

  [6756/17668] intraday_15231.csv.gz  in=292,530,991 out=75,140,554 elapsed=118.7s

  [6757/17668] intraday_15233.csv.gz  in=292,547,527 out=75,157,090 elapsed=118.7s

  [6758/17668] intraday_15235.csv.gz  in=292,560,262 out=75,169,825 elapsed=118.7s

  [6759/17668] intraday_15234.csv.gz  in=292,570,940 out=75,180,503 elapsed=118.7s

  [6760/17668] intraday_15236.csv.gz  in=292,581,299 out=75,190,862 elapsed=118.7s

  [6761/17668] intraday_15238.csv.gz  in=292,591,742 out=75,201,305 elapsed=118.7s

  [6762/17668] intraday_15237.csv.gz  in=292,603,686 out=75,213,249 elapsed=118.7s

  [6763/17668] intraday_1524.csv.gz  in=292,616,079 out=75,213,249 elapsed=118.7s

  [6764/17668] intraday_15239.csv.gz  in=292,628,730 out=75,225,900 elapsed=118.8s

  [6765/17668] intraday_15240.csv.gz  in=292,640,124 out=75,237,294 elapsed=118.8s

  [6766/17668] intraday_15241.csv.gz  in=292,655,220 out=75,252,390 elapsed=118.8s

  [6767/17668] intraday_15242.csv.gz  in=292,664,935 out=75,262,105 elapsed=118.8s

  [6768/17668] intraday_15243.csv.gz  in=292,675,905 out=75,273,075 elapsed=118.8s

  [6769/17668] intraday_15244.csv.gz  in=292,687,819 out=75,284,989 elapsed=118.8s

  [6770/17668] intraday_15245.csv.gz  in=292,701,410 out=75,298,580 elapsed=118.8s

  [6771/17668] intraday_15247.csv.gz  in=292,714,331 out=75,311,501 elapsed=118.8s

  [6772/17668] intraday_15246.csv.gz  in=292,724,466 out=75,321,636 elapsed=118.9s

  [6773/17668] intraday_15248.csv.gz  in=292,739,880 out=75,337,050 elapsed=118.9s

  [6774/17668] intraday_1525.csv.gz  in=292,753,361 out=75,337,050 elapsed=118.9s

  [6775/17668] intraday_15249.csv.gz  in=292,767,171 out=75,350,860 elapsed=118.9s

  [6776/17668] intraday_15250.csv.gz  in=292,780,536 out=75,364,225 elapsed=118.9s

  [6777/17668] intraday_15252.csv.gz  in=292,791,782 out=75,375,471 elapsed=118.9s

  [6778/17668] intraday_15251.csv.gz  in=292,804,254 out=75,387,943 elapsed=118.9s

  [6779/17668] intraday_15253.csv.gz  in=292,816,428 out=75,400,117 elapsed=118.9s

  [6780/17668] intraday_15254.csv.gz  in=292,826,628 out=75,410,317 elapsed=118.9s

  [6781/17668] intraday_15255.csv.gz  in=292,838,481 out=75,422,170 elapsed=118.9s

  [6782/17668] intraday_15256.csv.gz  in=292,847,950 out=75,431,639 elapsed=119.0s

  [6783/17668] intraday_15257.csv.gz  in=292,856,504 out=75,440,193 elapsed=119.0s

  [6784/17668] intraday_15258.csv.gz  in=292,868,464 out=75,452,153 elapsed=119.0s

  [6785/17668] intraday_15259.csv.gz  in=292,883,292 out=75,466,981 elapsed=119.0s

  [6786/17668] intraday_1526.csv.gz  in=292,897,250 out=75,466,981 elapsed=119.0s

  [6787/17668] intraday_15260.csv.gz  in=292,909,628 out=75,479,359 elapsed=119.0s

  [6788/17668] intraday_15262.csv.gz  in=292,922,175 out=75,491,906 elapsed=119.0s

  [6789/17668] intraday_15263.csv.gz  in=292,933,723 out=75,503,454 elapsed=119.1s

  [6790/17668] intraday_15264.csv.gz  in=292,948,919 out=75,518,650 elapsed=119.1s

  [6791/17668] intraday_15261.csv.gz  in=292,961,825 out=75,531,556 elapsed=119.1s

  [6792/17668] intraday_15265.csv.gz  in=292,974,443 out=75,544,174 elapsed=119.1s

  [6793/17668] intraday_15266.csv.gz  in=292,985,806 out=75,555,537 elapsed=119.1s

  [6794/17668] intraday_15268.csv.gz  in=292,997,900 out=75,567,631 elapsed=119.1s

  [6795/17668] intraday_15267.csv.gz  in=293,010,149 out=75,579,880 elapsed=119.1s

  [6796/17668] intraday_15269.csv.gz  in=293,020,903 out=75,590,634 elapsed=119.1s

  [6797/17668] intraday_1527.csv.gz  in=293,029,941 out=75,590,634 elapsed=119.1s

  [6798/17668] intraday_15270.csv.gz  in=293,043,783 out=75,604,476 elapsed=119.2s

  [6799/17668] intraday_15271.csv.gz  in=293,057,875 out=75,618,568 elapsed=119.2s

  [6800/17668] intraday_15273.csv.gz  in=293,067,896 out=75,628,589 elapsed=119.2s

  [6801/17668] intraday_15272.csv.gz  in=293,080,290 out=75,640,983 elapsed=119.2s

  [6802/17668] intraday_15274.csv.gz  in=293,089,944 out=75,650,637 elapsed=119.2s

  [6803/17668] intraday_15276.csv.gz  in=293,103,360 out=75,664,053 elapsed=119.2s

  [6804/17668] intraday_15275.csv.gz  in=293,118,541 out=75,679,234 elapsed=119.2s

  [6805/17668] intraday_15278.csv.gz  in=293,131,363 out=75,692,056 elapsed=119.2s

  [6806/17668] intraday_15277.csv.gz  in=293,141,144 out=75,701,837 elapsed=119.2s

  [6807/17668] intraday_1528.csv.gz  in=293,152,902 out=75,701,837 elapsed=119.3s

  [6808/17668] intraday_15279.csv.gz  in=293,165,414 out=75,714,349 elapsed=119.3s

  [6809/17668] intraday_15280.csv.gz  in=293,178,903 out=75,727,838 elapsed=119.3s

  [6810/17668] intraday_15281.csv.gz  in=293,190,467 out=75,739,402 elapsed=119.3s

  [6811/17668] intraday_15282.csv.gz  in=293,202,486 out=75,751,421 elapsed=119.3s

  [6812/17668] intraday_15283.csv.gz  in=293,214,020 out=75,762,955 elapsed=119.3s

  [6813/17668] intraday_15285.csv.gz  in=293,225,279 out=75,774,214 elapsed=119.3s

  [6814/17668] intraday_15284.csv.gz  in=293,237,651 out=75,786,586 elapsed=119.4s

  [6815/17668] intraday_15286.csv.gz  in=293,248,211 out=75,797,146 elapsed=119.4s

  [6816/17668] intraday_15288.csv.gz  in=293,261,808 out=75,810,743 elapsed=119.4s

  [6817/17668] intraday_15287.csv.gz  in=293,273,374 out=75,822,309 elapsed=119.4s

  [6818/17668] intraday_1529.csv.gz  in=293,287,596 out=75,822,309 elapsed=119.4s

  [6819/17668] intraday_15289.csv.gz  in=293,305,261 out=75,839,835 elapsed=119.4s

  [6820/17668] intraday_15291.csv.gz  in=293,316,484 out=75,851,058 elapsed=119.5s

  [6821/17668] intraday_15290.csv.gz  in=293,326,773 out=75,861,347 elapsed=119.5s

  [6822/17668] intraday_15292.csv.gz  in=293,339,365 out=75,873,939 elapsed=119.5s

  [6823/17668] intraday_15294.csv.gz  in=293,350,974 out=75,885,548 elapsed=119.5s

  [6824/17668] intraday_15296.csv.gz  in=293,362,679 out=75,897,253 elapsed=119.5s

  [6825/17668] intraday_15295.csv.gz  in=293,375,689 out=75,910,263 elapsed=119.5s

  [6826/17668] intraday_15293.csv.gz  in=293,406,847 out=75,936,554 elapsed=119.5s

  [6827/17668] intraday_1530.csv.gz  in=293,417,712 out=75,936,554 elapsed=119.6s

  [6828/17668] intraday_15297.csv.gz  in=293,427,828 out=75,946,670 elapsed=119.6s

  [6829/17668] intraday_15298.csv.gz  in=293,437,234 out=75,956,076 elapsed=119.6s

  [6830/17668] intraday_15299.csv.gz  in=293,447,874 out=75,966,716 elapsed=119.6s

  [6831/17668] intraday_15300.csv.gz  in=293,459,680 out=75,978,522 elapsed=119.6s

  [6832/17668] intraday_15301.csv.gz  in=293,473,612 out=75,992,454 elapsed=119.6s

  [6833/17668] intraday_15302.csv.gz  in=293,486,434 out=76,005,276 elapsed=119.6s

  [6834/17668] intraday_15303.csv.gz  in=293,499,647 out=76,018,489 elapsed=119.7s

  [6835/17668] intraday_15304.csv.gz  in=293,510,771 out=76,029,613 elapsed=119.7s

  [6836/17668] intraday_15305.csv.gz  in=293,522,168 out=76,041,010 elapsed=119.7s

  [6837/17668] intraday_15306.csv.gz  in=293,535,237 out=76,054,079 elapsed=119.7s

  [6838/17668] intraday_15307.csv.gz  in=293,546,293 out=76,065,135 elapsed=119.7s

  [6839/17668] intraday_15308.csv.gz  in=293,557,641 out=76,076,483 elapsed=119.7s

  [6840/17668] intraday_15309.csv.gz  in=293,567,883 out=76,086,725 elapsed=119.7s

  [6841/17668] intraday_1531.csv.gz  in=293,577,707 out=76,086,725 elapsed=119.7s

  [6842/17668] intraday_15311.csv.gz  in=293,589,693 out=76,098,711 elapsed=119.8s

  [6843/17668] intraday_15310.csv.gz  in=293,604,731 out=76,113,749 elapsed=119.8s

  [6844/17668] intraday_15313.csv.gz  in=293,619,558 out=76,128,576 elapsed=119.8s

  [6845/17668] intraday_15312.csv.gz  in=293,631,754 out=76,140,772 elapsed=119.8s

  [6846/17668] intraday_15314.csv.gz  in=293,643,928 out=76,152,946 elapsed=119.8s

  [6847/17668] intraday_15315.csv.gz  in=293,654,723 out=76,163,741 elapsed=119.8s

  [6848/17668] intraday_15316.csv.gz  in=293,666,619 out=76,175,637 elapsed=119.8s

  [6849/17668] intraday_15317.csv.gz  in=293,679,875 out=76,188,893 elapsed=119.9s

  [6850/17668] intraday_15318.csv.gz  in=293,692,723 out=76,201,741 elapsed=119.9s

  [6851/17668] intraday_1532.csv.gz  in=293,706,427 out=76,201,741 elapsed=119.9s

  [6852/17668] intraday_15319.csv.gz  in=293,717,456 out=76,212,770 elapsed=119.9s

  [6853/17668] intraday_15320.csv.gz  in=293,727,728 out=76,223,042 elapsed=119.9s

  [6854/17668] intraday_15321.csv.gz  in=293,739,939 out=76,235,253 elapsed=119.9s

  [6855/17668] intraday_15323.csv.gz  in=293,754,108 out=76,249,422 elapsed=119.9s

  [6856/17668] intraday_15322.csv.gz  in=293,763,836 out=76,259,150 elapsed=119.9s

  [6857/17668] intraday_15324.csv.gz  in=293,776,744 out=76,272,058 elapsed=119.9s

  [6858/17668] intraday_15325.csv.gz  in=293,789,169 out=76,284,483 elapsed=119.9s

  [6859/17668] intraday_15326.csv.gz  in=293,801,111 out=76,296,425 elapsed=119.9s

  [6860/17668] intraday_15328.csv.gz  in=293,809,846 out=76,305,160 elapsed=120.0s

  [6861/17668] intraday_15329.csv.gz  in=293,822,371 out=76,317,685 elapsed=120.0s

  [6862/17668] intraday_15327.csv.gz  in=293,834,043 out=76,329,357 elapsed=120.0s

  [6863/17668] intraday_1533.csv.gz  in=293,845,496 out=76,329,357 elapsed=120.0s

  [6864/17668] intraday_15330.csv.gz  in=293,856,834 out=76,340,695 elapsed=120.0s

  [6865/17668] intraday_15332.csv.gz  in=293,867,023 out=76,350,884 elapsed=120.0s

  [6866/17668] intraday_15331.csv.gz  in=293,879,347 out=76,363,208 elapsed=120.1s

  [6867/17668] intraday_15333.csv.gz  in=293,891,960 out=76,375,821 elapsed=120.1s

  [6868/17668] intraday_15334.csv.gz  in=293,905,103 out=76,388,964 elapsed=120.1s

  [6869/17668] intraday_15335.csv.gz  in=293,916,846 out=76,400,707 elapsed=120.1s

  [6870/17668] intraday_15339.csv.gz  in=293,927,795 out=76,411,656 elapsed=120.1s

  [6871/17668] intraday_15338.csv.gz  in=293,939,145 out=76,423,006 elapsed=120.2s

  [6872/17668] intraday_15336.csv.gz  in=293,952,203 out=76,436,064 elapsed=120.2s

  [6873/17668] intraday_15337.csv.gz  in=293,963,918 out=76,447,779 elapsed=120.2s

  [6874/17668] intraday_1534.csv.gz  in=293,976,122 out=76,447,779 elapsed=120.2s

  [6875/17668] intraday_15340.csv.gz  in=293,987,214 out=76,458,871 elapsed=120.2s

  [6876/17668] intraday_15341.csv.gz  in=293,999,342 out=76,470,999 elapsed=120.2s

  [6877/17668] intraday_15343.csv.gz  in=294,010,783 out=76,482,440 elapsed=120.2s

  [6878/17668] intraday_15342.csv.gz  in=294,028,638 out=76,500,295 elapsed=120.2s

  [6879/17668] intraday_15345.csv.gz  in=294,039,001 out=76,510,658 elapsed=120.3s

  [6880/17668] intraday_15344.csv.gz  in=294,055,456 out=76,527,113 elapsed=120.3s

  [6881/17668] intraday_15347.csv.gz  in=294,065,516 out=76,537,173 elapsed=120.3s

  [6882/17668] intraday_15346.csv.gz  in=294,078,480 out=76,550,137 elapsed=120.3s

  [6883/17668] intraday_15348.csv.gz  in=294,094,114 out=76,565,771 elapsed=120.3s

  [6884/17668] intraday_15349.csv.gz  in=294,104,710 out=76,576,367 elapsed=120.3s

  [6885/17668] intraday_1535.csv.gz  in=294,116,566 out=76,576,367 elapsed=120.3s

  [6886/17668] intraday_15351.csv.gz  in=294,127,029 out=76,586,830 elapsed=120.3s

  [6887/17668] intraday_15350.csv.gz  in=294,138,874 out=76,598,675 elapsed=120.3s

  [6888/17668] intraday_15352.csv.gz  in=294,150,611 out=76,610,412 elapsed=120.3s

  [6889/17668] intraday_15354.csv.gz  in=294,166,440 out=76,626,241 elapsed=120.4s

  [6890/17668] intraday_15353.csv.gz  in=294,179,097 out=76,638,898 elapsed=120.4s

  [6891/17668] intraday_15356.csv.gz  in=294,189,768 out=76,649,569 elapsed=120.4s

  [6892/17668] intraday_15355.csv.gz  in=294,201,840 out=76,661,641 elapsed=120.4s

  [6893/17668] intraday_15357.csv.gz  in=294,213,164 out=76,672,965 elapsed=120.4s

  [6894/17668] intraday_15358.csv.gz  in=294,225,260 out=76,685,061 elapsed=120.4s

  [6895/17668] intraday_1536.csv.gz  in=294,236,685 out=76,685,061 elapsed=120.4s

  [6896/17668] intraday_15360.csv.gz  in=294,249,950 out=76,698,326 elapsed=120.4s

  [6897/17668] intraday_15359.csv.gz  in=294,262,789 out=76,711,165 elapsed=120.4s

  [6898/17668] intraday_15361.csv.gz  in=294,273,901 out=76,722,277 elapsed=120.4s

  [6899/17668] intraday_15362.csv.gz  in=294,286,210 out=76,734,586 elapsed=120.5s

  [6900/17668] intraday_15363.csv.gz  in=294,296,387 out=76,744,763 elapsed=120.5s

  [6901/17668] intraday_15365.csv.gz  in=294,307,935 out=76,756,311 elapsed=120.5s

  [6902/17668] intraday_15364.csv.gz  in=294,321,556 out=76,769,932 elapsed=120.5s

  [6903/17668] intraday_15366.csv.gz  in=294,332,966 out=76,781,342 elapsed=120.5s

  [6904/17668] intraday_15367.csv.gz  in=294,346,118 out=76,794,494 elapsed=120.5s

  [6905/17668] intraday_1537.csv.gz  in=294,358,152 out=76,794,494 elapsed=120.5s

  [6906/17668] intraday_15368.csv.gz  in=294,370,970 out=76,807,312 elapsed=120.6s

  [6907/17668] intraday_15369.csv.gz  in=294,383,551 out=76,819,893 elapsed=120.6s

  [6908/17668] intraday_15371.csv.gz  in=294,396,183 out=76,832,525 elapsed=120.6s

  [6909/17668] intraday_15370.csv.gz  in=294,421,904 out=76,856,455 elapsed=120.6s

  [6910/17668] intraday_15372.csv.gz  in=294,435,361 out=76,869,912 elapsed=120.6s

  [6911/17668] intraday_15373.csv.gz  in=294,447,637 out=76,882,188 elapsed=120.6s

  [6912/17668] intraday_15376.csv.gz  in=294,459,363 out=76,893,914 elapsed=120.7s

  [6913/17668] intraday_15374.csv.gz  in=294,472,902 out=76,907,453 elapsed=120.7s

  [6914/17668] intraday_15377.csv.gz  in=294,489,520 out=76,924,071 elapsed=120.7s

  [6915/17668] intraday_15375.csv.gz  in=294,508,593 out=76,943,144 elapsed=120.7s

  [6916/17668] intraday_15378.csv.gz  in=294,520,082 out=76,954,633 elapsed=120.7s

  [6917/17668] intraday_15379.csv.gz  in=294,532,749 out=76,967,300 elapsed=120.7s

  [6918/17668] intraday_1538.csv.gz  in=294,544,619 out=76,967,300 elapsed=120.7s

  [6919/17668] intraday_15380.csv.gz  in=294,554,889 out=76,977,570 elapsed=120.7s

  [6920/17668] intraday_15381.csv.gz  in=294,567,238 out=76,989,919 elapsed=120.7s

  [6921/17668] intraday_15383.csv.gz  in=294,580,352 out=77,003,033 elapsed=120.7s

  [6922/17668] intraday_15382.csv.gz  in=294,590,902 out=77,013,583 elapsed=120.8s

  [6923/17668] intraday_15384.csv.gz  in=294,601,900 out=77,024,581 elapsed=120.8s

  [6924/17668] intraday_15385.csv.gz  in=294,618,232 out=77,040,913 elapsed=120.8s

  [6925/17668] intraday_15387.csv.gz  in=294,629,459 out=77,052,140 elapsed=120.8s

  [6926/17668] intraday_15386.csv.gz  in=294,640,051 out=77,062,732 elapsed=120.8s

  [6927/17668] intraday_15388.csv.gz  in=294,651,400 out=77,074,081 elapsed=120.8s

  [6928/17668] intraday_15389.csv.gz  in=294,664,857 out=77,087,538 elapsed=120.8s

  [6929/17668] intraday_1539.csv.gz  in=294,677,034 out=77,087,538 elapsed=120.8s

  [6930/17668] intraday_15390.csv.gz  in=294,687,129 out=77,097,633 elapsed=120.8s

  [6931/17668] intraday_15391.csv.gz  in=294,699,391 out=77,109,895 elapsed=120.9s

  [6932/17668] intraday_15393.csv.gz  in=294,712,387 out=77,122,891 elapsed=120.9s

  [6933/17668] intraday_15392.csv.gz  in=294,726,648 out=77,137,152 elapsed=120.9s

  [6934/17668] intraday_15395.csv.gz  in=294,738,660 out=77,149,164 elapsed=120.9s

  [6935/17668] intraday_15394.csv.gz  in=294,752,658 out=77,163,162 elapsed=120.9s

  [6936/17668] intraday_15396.csv.gz  in=294,763,771 out=77,174,275 elapsed=120.9s

  [6937/17668] intraday_15397.csv.gz  in=294,776,252 out=77,186,756 elapsed=120.9s

  [6938/17668] intraday_15398.csv.gz  in=294,786,086 out=77,196,590 elapsed=120.9s

  [6939/17668] intraday_15399.csv.gz  in=294,798,334 out=77,208,838 elapsed=120.9s

  [6940/17668] intraday_1540.csv.gz  in=294,812,419 out=77,208,838 elapsed=120.9s

  [6941/17668] intraday_15400.csv.gz  in=294,822,585 out=77,219,004 elapsed=121.0s

  [6942/17668] intraday_15401.csv.gz  in=294,829,868 out=77,226,287 elapsed=121.0s

  [6943/17668] intraday_15402.csv.gz  in=294,841,600 out=77,238,019 elapsed=121.0s

  [6944/17668] intraday_15403.csv.gz  in=294,856,539 out=77,252,958 elapsed=121.0s

  [6945/17668] intraday_15404.csv.gz  in=294,868,939 out=77,265,358 elapsed=121.0s

  [6946/17668] intraday_15405.csv.gz  in=294,881,381 out=77,277,800 elapsed=121.0s

  [6947/17668] intraday_15406.csv.gz  in=294,891,890 out=77,288,294 elapsed=121.0s

  [6948/17668] intraday_1541.csv.gz  in=294,902,716 out=77,288,294 elapsed=121.0s

  [6949/17668] intraday_15408.csv.gz  in=294,917,421 out=77,302,999 elapsed=121.1s

  [6950/17668] intraday_15407.csv.gz  in=294,930,684 out=77,316,262 elapsed=121.1s

  [6951/17668] intraday_15409.csv.gz  in=294,942,373 out=77,327,951 elapsed=121.1s

  [6952/17668] intraday_15410.csv.gz  in=294,954,351 out=77,339,929 elapsed=121.1s

  [6953/17668] intraday_15411.csv.gz  in=294,965,779 out=77,351,357 elapsed=121.1s

  [6954/17668] intraday_15413.csv.gz  in=294,976,870 out=77,362,448 elapsed=121.1s

  [6955/17668] intraday_15414.csv.gz  in=294,989,474 out=77,375,052 elapsed=121.1s

  [6956/17668] intraday_15415.csv.gz  in=295,002,150 out=77,387,728 elapsed=121.1s

  [6957/17668] intraday_15412.csv.gz  in=295,013,413 out=77,398,991 elapsed=121.1s

  [6958/17668] intraday_15416.csv.gz  in=295,027,425 out=77,412,907 elapsed=121.1s

  [6959/17668] intraday_15417.csv.gz  in=295,036,432 out=77,421,914 elapsed=121.2s

  [6960/17668] intraday_15418.csv.gz  in=295,046,755 out=77,432,237 elapsed=121.2s

  [6961/17668] intraday_15419.csv.gz  in=295,060,690 out=77,446,172 elapsed=121.2s

  [6962/17668] intraday_1542.csv.gz  in=295,070,980 out=77,446,172 elapsed=121.2s

  [6963/17668] intraday_15420.csv.gz  in=295,083,549 out=77,458,741 elapsed=121.2s

  [6964/17668] intraday_15421.csv.gz  in=295,092,907 out=77,468,099 elapsed=121.2s

  [6965/17668] intraday_15422.csv.gz  in=295,106,069 out=77,481,261 elapsed=121.2s

  [6966/17668] intraday_15423.csv.gz  in=295,117,235 out=77,492,427 elapsed=121.2s

  [6967/17668] intraday_15424.csv.gz  in=295,129,547 out=77,504,739 elapsed=121.3s

  [6968/17668] intraday_15425.csv.gz  in=295,142,083 out=77,517,275 elapsed=121.3s

  [6969/17668] intraday_15426.csv.gz  in=295,153,050 out=77,528,242 elapsed=121.3s

  [6970/17668] intraday_15427.csv.gz  in=295,165,271 out=77,540,463 elapsed=121.3s

  [6971/17668] intraday_15428.csv.gz  in=295,175,868 out=77,551,060 elapsed=121.3s

  [6972/17668] intraday_15429.csv.gz  in=295,186,458 out=77,561,650 elapsed=121.3s

  [6973/17668] intraday_1543.csv.gz  in=295,200,109 out=77,561,650 elapsed=121.3s

  [6974/17668] intraday_15430.csv.gz  in=295,210,571 out=77,572,112 elapsed=121.3s

  [6975/17668] intraday_15431.csv.gz  in=295,223,635 out=77,585,176 elapsed=121.4s

  [6976/17668] intraday_15433.csv.gz  in=295,237,437 out=77,598,978 elapsed=121.4s

  [6977/17668] intraday_15432.csv.gz  in=295,249,753 out=77,611,294 elapsed=121.4s

  [6978/17668] intraday_15435.csv.gz  in=295,260,274 out=77,621,815 elapsed=121.4s

  [6979/17668] intraday_15434.csv.gz  in=295,270,406 out=77,631,947 elapsed=121.4s

  [6980/17668] intraday_15436.csv.gz  in=295,282,349 out=77,643,890 elapsed=121.4s

  [6981/17668] intraday_15437.csv.gz  in=295,302,102 out=77,662,214 elapsed=121.4s

  [6982/17668] intraday_15439.csv.gz  in=295,314,559 out=77,674,671 elapsed=121.4s

  [6983/17668] intraday_15438.csv.gz  in=295,325,603 out=77,685,715 elapsed=121.4s

  [6984/17668] intraday_1544.csv.gz  in=295,338,717 out=77,685,715 elapsed=121.4s

  [6985/17668] intraday_15440.csv.gz  in=295,349,626 out=77,696,624 elapsed=121.5s

  [6986/17668] intraday_15441.csv.gz  in=295,359,530 out=77,706,528 elapsed=121.5s

  [6987/17668] intraday_15443.csv.gz  in=295,370,506 out=77,717,504 elapsed=121.5s

  [6988/17668] intraday_15442.csv.gz  in=295,380,328 out=77,727,326 elapsed=121.5s

  [6989/17668] intraday_15444.csv.gz  in=295,392,083 out=77,739,081 elapsed=121.5s

  [6990/17668] intraday_15445.csv.gz  in=295,405,209 out=77,752,207 elapsed=121.5s

  [6991/17668] intraday_15447.csv.gz  in=295,416,025 out=77,763,023 elapsed=121.5s

  [6992/17668] intraday_15446.csv.gz  in=295,428,854 out=77,775,852 elapsed=121.5s

  [6993/17668] intraday_15448.csv.gz  in=295,440,281 out=77,787,279 elapsed=121.6s

  [6994/17668] intraday_15449.csv.gz  in=295,451,433 out=77,798,431 elapsed=121.6s

  [6995/17668] intraday_1545.csv.gz  in=295,466,259 out=77,798,431 elapsed=121.6s

  [6996/17668] intraday_15451.csv.gz  in=295,476,758 out=77,808,930 elapsed=121.6s

  [6997/17668] intraday_15450.csv.gz  in=295,489,284 out=77,821,456 elapsed=121.6s

  [6998/17668] intraday_15452.csv.gz  in=295,500,256 out=77,832,428 elapsed=121.6s

  [6999/17668] intraday_15453.csv.gz  in=295,509,758 out=77,841,930 elapsed=121.6s

  [7000/17668] intraday_15454.csv.gz  in=295,523,641 out=77,855,813 elapsed=121.7s

  [7001/17668] intraday_15456.csv.gz  in=295,534,407 out=77,866,579 elapsed=121.7s

  [7002/17668] intraday_15455.csv.gz  in=295,545,592 out=77,877,764 elapsed=121.7s

  [7003/17668] intraday_15457.csv.gz  in=295,559,892 out=77,892,064 elapsed=121.7s

  [7004/17668] intraday_15458.csv.gz  in=295,570,817 out=77,902,989 elapsed=121.7s

  [7005/17668] intraday_15459.csv.gz  in=295,581,624 out=77,913,796 elapsed=121.7s

  [7006/17668] intraday_1546.csv.gz  in=295,595,973 out=77,913,796 elapsed=121.7s

  [7007/17668] intraday_15460.csv.gz  in=295,606,913 out=77,924,736 elapsed=121.7s

  [7008/17668] intraday_15461.csv.gz  in=295,617,475 out=77,935,298 elapsed=121.7s

  [7009/17668] intraday_15462.csv.gz  in=295,629,563 out=77,947,386 elapsed=121.7s

  [7010/17668] intraday_15464.csv.gz  in=295,639,848 out=77,957,671 elapsed=121.8s

  [7011/17668] intraday_15463.csv.gz  in=295,670,539 out=77,984,936 elapsed=121.8s

  [7012/17668] intraday_15465.csv.gz  in=295,681,089 out=77,995,486 elapsed=121.8s

  [7013/17668] intraday_15466.csv.gz  in=295,690,661 out=78,005,058 elapsed=121.8s

  [7014/17668] intraday_15467.csv.gz  in=295,704,284 out=78,018,681 elapsed=121.8s

  [7015/17668] intraday_15468.csv.gz  in=295,715,093 out=78,029,490 elapsed=121.8s

  [7016/17668] intraday_15469.csv.gz  in=295,727,762 out=78,042,159 elapsed=121.8s

  [7017/17668] intraday_1547.csv.gz  in=295,739,689 out=78,042,159 elapsed=121.8s

  [7018/17668] intraday_15470.csv.gz  in=295,751,062 out=78,053,532 elapsed=121.9s

  [7019/17668] intraday_15471.csv.gz  in=295,762,205 out=78,064,675 elapsed=121.9s

  [7020/17668] intraday_15472.csv.gz  in=295,770,350 out=78,072,820 elapsed=121.9s

  [7021/17668] intraday_15474.csv.gz  in=295,781,667 out=78,084,137 elapsed=121.9s

  [7022/17668] intraday_15473.csv.gz  in=295,794,151 out=78,096,621 elapsed=121.9s

  [7023/17668] intraday_15476.csv.gz  in=295,803,420 out=78,105,882 elapsed=121.9s

  [7024/17668] intraday_15475.csv.gz  in=295,814,284 out=78,116,746 elapsed=121.9s

  [7025/17668] intraday_15478.csv.gz  in=295,822,811 out=78,125,273 elapsed=122.0s

  [7026/17668] intraday_15477.csv.gz  in=295,832,935 out=78,135,397 elapsed=122.0s

  [7027/17668] intraday_15479.csv.gz  in=295,846,859 out=78,149,321 elapsed=122.0s

  [7028/17668] intraday_1548.csv.gz  in=295,858,895 out=78,149,321 elapsed=122.0s

  [7029/17668] intraday_15480.csv.gz  in=295,870,349 out=78,160,775 elapsed=122.0s

  [7030/17668] intraday_15481.csv.gz  in=295,886,162 out=78,175,528 elapsed=122.0s

  [7031/17668] intraday_15483.csv.gz  in=295,896,561 out=78,185,927 elapsed=122.0s

  [7032/17668] intraday_15482.csv.gz  in=295,906,974 out=78,196,340 elapsed=122.0s

  [7033/17668] intraday_15484.csv.gz  in=295,917,638 out=78,207,004 elapsed=122.0s

  [7034/17668] intraday_15485.csv.gz  in=295,928,961 out=78,218,327 elapsed=122.0s

  [7035/17668] intraday_15486.csv.gz  in=295,944,813 out=78,234,179 elapsed=122.1s

  [7036/17668] intraday_15487.csv.gz  in=295,956,431 out=78,245,797 elapsed=122.1s

  [7037/17668] intraday_15488.csv.gz  in=295,969,775 out=78,259,141 elapsed=122.1s

  [7038/17668] intraday_1549.csv.gz  in=295,981,373 out=78,259,141 elapsed=122.1s

  [7039/17668] intraday_15489.csv.gz  in=295,992,768 out=78,270,536 elapsed=122.1s

  [7040/17668] intraday_15490.csv.gz  in=296,004,762 out=78,282,530 elapsed=122.1s

  [7041/17668] intraday_15491.csv.gz  in=296,016,739 out=78,294,507 elapsed=122.1s

  [7042/17668] intraday_15494.csv.gz  in=296,028,905 out=78,306,673 elapsed=122.2s

  [7043/17668] intraday_15492.csv.gz  in=296,042,083 out=78,319,851 elapsed=122.2s

  [7044/17668] intraday_15493.csv.gz  in=296,052,294 out=78,330,062 elapsed=122.2s

  [7045/17668] intraday_15495.csv.gz  in=296,063,280 out=78,341,048 elapsed=122.2s

  [7046/17668] intraday_15496.csv.gz  in=296,073,691 out=78,351,459 elapsed=122.2s

  [7047/17668] intraday_15497.csv.gz  in=296,086,404 out=78,364,172 elapsed=122.2s

  [7048/17668] intraday_15498.csv.gz  in=296,097,191 out=78,374,959 elapsed=122.2s

  [7049/17668] intraday_15499.csv.gz  in=296,108,617 out=78,386,385 elapsed=122.2s

  [7050/17668] intraday_15501.csv.gz  in=296,119,310 out=78,397,078 elapsed=122.3s

  [7051/17668] intraday_15502.csv.gz  in=296,130,349 out=78,408,112 elapsed=122.3s

  [7052/17668] intraday_1550.csv.gz  in=296,164,572 out=78,408,112 elapsed=122.3s

  [7053/17668] intraday_15500.csv.gz  in=296,175,578 out=78,419,118 elapsed=122.3s

  [7054/17668] intraday_15503.csv.gz  in=296,187,633 out=78,431,173 elapsed=122.3s

  [7055/17668] intraday_15506.csv.gz  in=296,199,244 out=78,442,784 elapsed=122.3s

  [7056/17668] intraday_15507.csv.gz  in=296,208,213 out=78,451,753 elapsed=122.4s

  [7057/17668] intraday_15505.csv.gz  in=296,219,148 out=78,462,688 elapsed=122.4s

  [7058/17668] intraday_15504.csv.gz  in=296,230,980 out=78,474,520 elapsed=122.4s

  [7059/17668] intraday_1551.csv.gz  in=296,241,893 out=78,474,520 elapsed=122.4s

  [7060/17668] intraday_15509.csv.gz  in=296,251,089 out=78,483,716 elapsed=122.4s

  [7061/17668] intraday_15508.csv.gz  in=296,265,973 out=78,498,600 elapsed=122.4s

  [7062/17668] intraday_15513.csv.gz  in=296,275,997 out=78,508,624 elapsed=122.4s

  [7063/17668] intraday_15510.csv.gz  in=296,290,585 out=78,522,404 elapsed=122.4s

  [7064/17668] intraday_15512.csv.gz  in=296,304,197 out=78,536,016 elapsed=122.4s

  [7065/17668] intraday_15511.csv.gz  in=296,316,584 out=78,548,403 elapsed=122.4s

  [7066/17668] intraday_15514.csv.gz  in=296,333,473 out=78,562,750 elapsed=122.5s

  [7067/17668] intraday_15515.csv.gz  in=296,346,390 out=78,575,667 elapsed=122.5s

  [7068/17668] intraday_15516.csv.gz  in=296,357,463 out=78,586,740 elapsed=122.5s

  [7069/17668] intraday_15517.csv.gz  in=296,369,953 out=78,599,230 elapsed=122.5s

  [7070/17668] intraday_1552.csv.gz  in=296,382,424 out=78,599,230 elapsed=122.6s

  [7071/17668] intraday_15520.csv.gz  in=296,395,996 out=78,612,802 elapsed=122.6s

  [7072/17668] intraday_15518.csv.gz  in=296,409,776 out=78,626,582 elapsed=122.6s

  [7073/17668] intraday_15519.csv.gz  in=296,427,039 out=78,643,845 elapsed=122.6s

  [7074/17668] intraday_15521.csv.gz  in=296,440,473 out=78,657,279 elapsed=122.6s

  [7075/17668] intraday_15522.csv.gz  in=296,451,097 out=78,667,903 elapsed=122.6s

  [7076/17668] intraday_15523.csv.gz  in=296,462,871 out=78,679,677 elapsed=122.6s

  [7077/17668] intraday_15524.csv.gz  in=296,471,353 out=78,688,159 elapsed=122.6s

  [7078/17668] intraday_15525.csv.gz  in=296,484,010 out=78,700,816 elapsed=122.6s

  [7079/17668] intraday_15528.csv.gz  in=296,496,079 out=78,712,885 elapsed=122.7s

  [7080/17668] intraday_15526.csv.gz  in=296,505,962 out=78,722,768 elapsed=122.7s

  [7081/17668] intraday_15527.csv.gz  in=296,517,667 out=78,734,473 elapsed=122.7s

  [7082/17668] intraday_15529.csv.gz  in=296,532,142 out=78,748,948 elapsed=122.7s

  [7083/17668] intraday_1553.csv.gz  in=296,543,955 out=78,748,948 elapsed=122.7s

  [7084/17668] intraday_15531.csv.gz  in=296,554,445 out=78,759,438 elapsed=122.7s

  [7085/17668] intraday_15530.csv.gz  in=296,565,497 out=78,770,490 elapsed=122.7s

  [7086/17668] intraday_15532.csv.gz  in=296,576,215 out=78,781,208 elapsed=122.7s

  [7087/17668] intraday_15533.csv.gz  in=296,588,541 out=78,793,534 elapsed=122.8s

  [7088/17668] intraday_15535.csv.gz  in=296,600,935 out=78,805,928 elapsed=122.8s

  [7089/17668] intraday_15534.csv.gz  in=296,611,538 out=78,816,531 elapsed=122.8s

  [7090/17668] intraday_15537.csv.gz  in=296,622,914 out=78,827,907 elapsed=122.8s

  [7091/17668] intraday_15536.csv.gz  in=296,636,450 out=78,841,443 elapsed=122.8s

  [7092/17668] intraday_15538.csv.gz  in=296,651,390 out=78,856,383 elapsed=122.8s

  [7093/17668] intraday_1554.csv.gz  in=296,663,188 out=78,856,383 elapsed=122.9s

  [7094/17668] intraday_15540.csv.gz  in=296,674,561 out=78,867,756 elapsed=122.9s

  [7095/17668] intraday_15539.csv.gz  in=296,683,872 out=78,877,067 elapsed=122.9s

  [7096/17668] intraday_15541.csv.gz  in=296,696,458 out=78,889,653 elapsed=122.9s

  [7097/17668] intraday_15542.csv.gz  in=296,713,780 out=78,904,975 elapsed=122.9s

  [7098/17668] intraday_15543.csv.gz  in=296,724,742 out=78,915,937 elapsed=122.9s

  [7099/17668] intraday_15545.csv.gz  in=296,734,708 out=78,925,903 elapsed=122.9s

  [7100/17668] intraday_15544.csv.gz  in=296,742,016 out=78,933,211 elapsed=122.9s

  [7101/17668] intraday_15546.csv.gz  in=296,750,049 out=78,941,244 elapsed=122.9s

  [7102/17668] intraday_15547.csv.gz  in=296,766,143 out=78,957,338 elapsed=123.0s

  [7103/17668] intraday_15548.csv.gz  in=296,778,406 out=78,969,601 elapsed=123.0s

  [7104/17668] intraday_15549.csv.gz  in=296,791,172 out=78,982,367 elapsed=123.0s

  [7105/17668] intraday_1555.csv.gz  in=296,803,987 out=78,982,367 elapsed=123.0s

  [7106/17668] intraday_15553.csv.gz  in=296,817,465 out=78,995,845 elapsed=123.1s

  [7107/17668] intraday_15550.csv.gz  in=296,828,551 out=79,006,931 elapsed=123.1s

  [7108/17668] intraday_15551.csv.gz  in=296,840,616 out=79,018,996 elapsed=123.1s

  [7109/17668] intraday_15552.csv.gz  in=296,854,867 out=79,033,247 elapsed=123.1s

  [7110/17668] intraday_15557.csv.gz  in=296,866,053 out=79,044,433 elapsed=123.1s

  [7111/17668] intraday_15555.csv.gz  in=296,881,101 out=79,059,481 elapsed=123.1s

  [7112/17668] intraday_15556.csv.gz  in=296,893,636 out=79,072,016 elapsed=123.1s

  [7113/17668] intraday_15554.csv.gz  in=296,904,679 out=79,083,059 elapsed=123.1s

  [7114/17668] intraday_15558.csv.gz  in=296,917,344 out=79,095,724 elapsed=123.1s

  [7115/17668] intraday_1556.csv.gz  in=296,929,355 out=79,095,724 elapsed=123.1s

  [7116/17668] intraday_15559.csv.gz  in=296,945,125 out=79,110,978 elapsed=123.2s

  [7117/17668] intraday_15560.csv.gz  in=296,958,115 out=79,123,968 elapsed=123.2s

  [7118/17668] intraday_15561.csv.gz  in=296,968,825 out=79,134,678 elapsed=123.2s

  [7119/17668] intraday_15562.csv.gz  in=296,979,327 out=79,145,180 elapsed=123.2s

  [7120/17668] intraday_15563.csv.gz  in=296,994,568 out=79,160,421 elapsed=123.2s

  [7121/17668] intraday_15565.csv.gz  in=297,005,845 out=79,171,698 elapsed=123.2s

  [7122/17668] intraday_15564.csv.gz  in=297,020,328 out=79,186,181 elapsed=123.2s

  [7123/17668] intraday_15566.csv.gz  in=297,032,071 out=79,197,924 elapsed=123.2s

  [7124/17668] intraday_15569.csv.gz  in=297,045,533 out=79,211,386 elapsed=123.3s

  [7125/17668] intraday_1557.csv.gz  in=297,058,530 out=79,211,386 elapsed=123.3s

  [7126/17668] intraday_15568.csv.gz  in=297,070,825 out=79,223,681 elapsed=123.3s

  [7127/17668] intraday_15567.csv.gz  in=297,103,849 out=79,253,533 elapsed=123.3s

  [7128/17668] intraday_15571.csv.gz  in=297,116,199 out=79,265,883 elapsed=123.3s

  [7129/17668] intraday_15570.csv.gz  in=297,128,154 out=79,277,838 elapsed=123.3s

  [7130/17668] intraday_15572.csv.gz  in=297,139,999 out=79,289,683 elapsed=123.3s

  [7131/17668] intraday_15573.csv.gz  in=297,150,118 out=79,299,802 elapsed=123.3s

  [7132/17668] intraday_15574.csv.gz  in=297,161,939 out=79,311,623 elapsed=123.3s

  [7133/17668] intraday_15575.csv.gz  in=297,174,351 out=79,324,035 elapsed=123.4s

  [7134/17668] intraday_15576.csv.gz  in=297,188,418 out=79,338,102 elapsed=123.4s

  [7135/17668] intraday_15578.csv.gz  in=297,201,440 out=79,351,124 elapsed=123.4s

  [7136/17668] intraday_15577.csv.gz  in=297,216,771 out=79,366,455 elapsed=123.4s

  [7137/17668] intraday_1558.csv.gz  in=297,229,361 out=79,366,455 elapsed=123.4s

  [7138/17668] intraday_15579.csv.gz  in=297,240,157 out=79,377,251 elapsed=123.4s

  [7139/17668] intraday_15580.csv.gz  in=297,252,356 out=79,389,450 elapsed=123.4s

  [7140/17668] intraday_15582.csv.gz  in=297,264,562 out=79,401,656 elapsed=123.5s

  [7141/17668] intraday_15583.csv.gz  in=297,277,436 out=79,414,530 elapsed=123.5s

  [7142/17668] intraday_15584.csv.gz  in=297,286,598 out=79,423,692 elapsed=123.5s

  [7143/17668] intraday_15585.csv.gz  in=297,298,670 out=79,435,764 elapsed=123.5s

  [7144/17668] intraday_15581.csv.gz  in=297,311,884 out=79,448,978 elapsed=123.5s

  [7145/17668] intraday_15586.csv.gz  in=297,321,045 out=79,458,139 elapsed=123.5s

  [7146/17668] intraday_15587.csv.gz  in=297,332,509 out=79,469,603 elapsed=123.5s

  [7147/17668] intraday_15589.csv.gz  in=297,346,985 out=79,484,079 elapsed=123.5s

  [7148/17668] intraday_15588.csv.gz  in=297,358,880 out=79,495,974 elapsed=123.5s

  [7149/17668] intraday_1559.csv.gz  in=297,373,983 out=79,495,974 elapsed=123.5s

  [7150/17668] intraday_15590.csv.gz  in=297,385,194 out=79,507,185 elapsed=123.5s

  [7151/17668] intraday_15592.csv.gz  in=297,397,494 out=79,519,485 elapsed=123.6s

  [7152/17668] intraday_15591.csv.gz  in=297,412,930 out=79,534,921 elapsed=123.6s

  [7153/17668] intraday_15594.csv.gz  in=297,424,875 out=79,546,866 elapsed=123.6s

  [7154/17668] intraday_15593.csv.gz  in=297,436,543 out=79,558,534 elapsed=123.6s

  [7155/17668] intraday_15595.csv.gz  in=297,448,550 out=79,570,541 elapsed=123.6s

  [7156/17668] intraday_15597.csv.gz  in=297,458,311 out=79,580,302 elapsed=123.6s

  [7157/17668] intraday_15596.csv.gz  in=297,469,976 out=79,591,967 elapsed=123.6s

  [7158/17668] intraday_15598.csv.gz  in=297,482,559 out=79,604,550 elapsed=123.6s

  [7159/17668] intraday_15599.csv.gz  in=297,495,618 out=79,617,609 elapsed=123.7s

  [7160/17668] intraday_1560.csv.gz  in=297,506,766 out=79,617,609 elapsed=123.7s

  [7161/17668] intraday_15601.csv.gz  in=297,518,980 out=79,629,823 elapsed=123.7s

  [7162/17668] intraday_15600.csv.gz  in=297,532,618 out=79,643,461 elapsed=123.7s

  [7163/17668] intraday_15602.csv.gz  in=297,546,059 out=79,656,902 elapsed=123.7s

  [7164/17668] intraday_15603.csv.gz  in=297,557,269 out=79,668,112 elapsed=123.7s

  [7165/17668] intraday_15606.csv.gz  in=297,570,812 out=79,681,655 elapsed=123.7s

  [7166/17668] intraday_15604.csv.gz  in=297,581,226 out=79,692,069 elapsed=123.7s

  [7167/17668] intraday_15605.csv.gz  in=297,592,545 out=79,703,388 elapsed=123.7s

  [7168/17668] intraday_15607.csv.gz  in=297,607,384 out=79,718,227 elapsed=123.8s

  [7169/17668] intraday_1561.csv.gz  in=297,621,219 out=79,718,227 elapsed=123.8s

  [7170/17668] intraday_15609.csv.gz  in=297,632,794 out=79,729,802 elapsed=123.8s

  [7171/17668] intraday_15610.csv.gz  in=297,643,944 out=79,740,952 elapsed=123.8s

  [7172/17668] intraday_15608.csv.gz  in=297,655,541 out=79,752,549 elapsed=123.8s

  [7173/17668] intraday_15611.csv.gz  in=297,668,812 out=79,765,820 elapsed=123.8s

  [7174/17668] intraday_15612.csv.gz  in=297,682,125 out=79,779,133 elapsed=123.8s

  [7175/17668] intraday_15614.csv.gz  in=297,694,384 out=79,791,392 elapsed=123.9s

  [7176/17668] intraday_15615.csv.gz  in=297,706,908 out=79,803,916 elapsed=123.9s

  [7177/17668] intraday_15613.csv.gz  in=297,720,656 out=79,817,664 elapsed=123.9s

  [7178/17668] intraday_15616.csv.gz  in=297,733,228 out=79,830,165 elapsed=123.9s

  [7179/17668] intraday_15618.csv.gz  in=297,746,175 out=79,843,112 elapsed=123.9s

  [7180/17668] intraday_15617.csv.gz  in=297,757,888 out=79,854,825 elapsed=123.9s

  [7181/17668] intraday_15619.csv.gz  in=297,769,502 out=79,866,439 elapsed=123.9s

  [7182/17668] intraday_1562.csv.gz  in=297,780,138 out=79,866,439 elapsed=123.9s

  [7183/17668] intraday_15620.csv.gz  in=297,791,383 out=79,877,684 elapsed=123.9s

  [7184/17668] intraday_15621.csv.gz  in=297,801,997 out=79,888,298 elapsed=124.0s

  [7185/17668] intraday_15623.csv.gz  in=297,814,279 out=79,900,580 elapsed=124.0s

  [7186/17668] intraday_15622.csv.gz  in=297,824,841 out=79,911,142 elapsed=124.0s

  [7187/17668] intraday_15624.csv.gz  in=297,839,035 out=79,925,336 elapsed=124.0s

  [7188/17668] intraday_15625.csv.gz  in=297,850,239 out=79,936,540 elapsed=124.0s

  [7189/17668] intraday_15626.csv.gz  in=297,861,286 out=79,947,587 elapsed=124.0s

  [7190/17668] intraday_15627.csv.gz  in=297,870,724 out=79,957,025 elapsed=124.0s

  [7191/17668] intraday_15628.csv.gz  in=297,882,311 out=79,968,612 elapsed=124.1s

  [7192/17668] intraday_15629.csv.gz  in=297,894,750 out=79,981,051 elapsed=124.1s

  [7193/17668] intraday_1563.csv.gz  in=297,906,799 out=79,981,051 elapsed=124.1s

  [7194/17668] intraday_15631.csv.gz  in=297,920,776 out=79,995,028 elapsed=124.1s

  [7195/17668] intraday_15630.csv.gz  in=297,934,565 out=80,008,817 elapsed=124.1s

  [7196/17668] intraday_15632.csv.gz  in=297,947,813 out=80,022,065 elapsed=124.1s

  [7197/17668] intraday_15633.csv.gz  in=297,959,750 out=80,034,002 elapsed=124.1s

  [7198/17668] intraday_15634.csv.gz  in=297,972,038 out=80,046,290 elapsed=124.1s

  [7199/17668] intraday_15635.csv.gz  in=297,984,305 out=80,058,557 elapsed=124.1s

  [7200/17668] intraday_15636.csv.gz  in=297,999,648 out=80,073,900 elapsed=124.2s

  [7201/17668] intraday_15637.csv.gz  in=298,012,371 out=80,086,623 elapsed=124.2s

  [7202/17668] intraday_15638.csv.gz  in=298,023,905 out=80,098,157 elapsed=124.2s

  [7203/17668] intraday_15639.csv.gz  in=298,036,733 out=80,110,985 elapsed=124.2s

  [7204/17668] intraday_1564.csv.gz  in=298,049,340 out=80,110,985 elapsed=124.2s

  [7205/17668] intraday_15641.csv.gz  in=298,061,724 out=80,123,369 elapsed=124.2s

  [7206/17668] intraday_15640.csv.gz  in=298,073,710 out=80,135,355 elapsed=124.2s

  [7207/17668] intraday_15643.csv.gz  in=298,086,477 out=80,148,122 elapsed=124.2s

  [7208/17668] intraday_15642.csv.gz  in=298,099,389 out=80,161,034 elapsed=124.3s

  [7209/17668] intraday_15644.csv.gz  in=298,110,577 out=80,172,222 elapsed=124.3s

  [7210/17668] intraday_15645.csv.gz  in=298,122,504 out=80,184,149 elapsed=124.3s

  [7211/17668] intraday_15647.csv.gz  in=298,133,937 out=80,195,582 elapsed=124.3s

  [7212/17668] intraday_15646.csv.gz  in=298,145,395 out=80,207,040 elapsed=124.3s

  [7213/17668] intraday_15648.csv.gz  in=298,160,472 out=80,222,117 elapsed=124.3s

  [7214/17668] intraday_1565.csv.gz  in=298,170,752 out=80,222,117 elapsed=124.3s

  [7215/17668] intraday_15649.csv.gz  in=298,184,752 out=80,236,117 elapsed=124.4s

  [7216/17668] intraday_15650.csv.gz  in=298,196,632 out=80,247,997 elapsed=124.4s

  [7217/17668] intraday_15651.csv.gz  in=298,208,388 out=80,259,753 elapsed=124.4s

  [7218/17668] intraday_15652.csv.gz  in=298,218,345 out=80,269,710 elapsed=124.4s

  [7219/17668] intraday_15653.csv.gz  in=298,234,006 out=80,285,371 elapsed=124.4s

  [7220/17668] intraday_15655.csv.gz  in=298,246,586 out=80,297,951 elapsed=124.4s

  [7221/17668] intraday_15654.csv.gz  in=298,257,523 out=80,308,888 elapsed=124.5s

  [7222/17668] intraday_15656.csv.gz  in=298,269,357 out=80,320,722 elapsed=124.5s

  [7223/17668] intraday_15657.csv.gz  in=298,283,328 out=80,334,693 elapsed=124.5s

  [7224/17668] intraday_1566.csv.gz  in=298,296,677 out=80,334,693 elapsed=124.5s

  [7225/17668] intraday_15658.csv.gz  in=298,308,760 out=80,346,776 elapsed=124.5s

  [7226/17668] intraday_15659.csv.gz  in=298,323,754 out=80,361,770 elapsed=124.5s

  [7227/17668] intraday_15660.csv.gz  in=298,337,866 out=80,375,882 elapsed=124.5s

  [7228/17668] intraday_15661.csv.gz  in=298,347,951 out=80,385,967 elapsed=124.5s

  [7229/17668] intraday_15662.csv.gz  in=298,362,117 out=80,400,133 elapsed=124.5s

  [7230/17668] intraday_15663.csv.gz  in=298,378,489 out=80,416,505 elapsed=124.5s

  [7231/17668] intraday_15665.csv.gz  in=298,393,450 out=80,431,466 elapsed=124.6s

  [7232/17668] intraday_15664.csv.gz  in=298,408,906 out=80,446,922 elapsed=124.6s

  [7233/17668] intraday_15667.csv.gz  in=298,421,216 out=80,459,232 elapsed=124.6s

  [7234/17668] intraday_15666.csv.gz  in=298,433,107 out=80,471,123 elapsed=124.6s

  [7235/17668] intraday_15668.csv.gz  in=298,445,145 out=80,483,161 elapsed=124.6s

  [7236/17668] intraday_15669.csv.gz  in=298,455,495 out=80,493,511 elapsed=124.6s

  [7237/17668] intraday_1567.csv.gz  in=298,470,681 out=80,493,511 elapsed=124.6s

  [7238/17668] intraday_15670.csv.gz  in=298,482,595 out=80,505,425 elapsed=124.6s

  [7239/17668] intraday_15671.csv.gz  in=298,493,400 out=80,516,230 elapsed=124.6s

  [7240/17668] intraday_15672.csv.gz  in=298,508,227 out=80,531,057 elapsed=124.7s

  [7241/17668] intraday_15674.csv.gz  in=298,522,067 out=80,544,897 elapsed=124.7s

  [7242/17668] intraday_15673.csv.gz  in=298,534,402 out=80,557,232 elapsed=124.7s

  [7243/17668] intraday_15675.csv.gz  in=298,545,714 out=80,568,544 elapsed=124.7s

  [7244/17668] intraday_15676.csv.gz  in=298,556,789 out=80,579,619 elapsed=124.7s

  [7245/17668] intraday_15678.csv.gz  in=298,568,380 out=80,591,210 elapsed=124.7s

  [7246/17668] intraday_15679.csv.gz  in=298,580,654 out=80,603,484 elapsed=124.7s

  [7247/17668] intraday_15677.csv.gz  in=298,593,932 out=80,616,762 elapsed=124.7s

  [7248/17668] intraday_1568.csv.gz  in=298,605,987 out=80,616,762 elapsed=124.7s

  [7249/17668] intraday_15681.csv.gz  in=298,619,435 out=80,630,210 elapsed=124.8s

  [7250/17668] intraday_15680.csv.gz  in=298,632,828 out=80,643,603 elapsed=124.8s

  [7251/17668] intraday_15682.csv.gz  in=298,645,398 out=80,656,173 elapsed=124.8s

  [7252/17668] intraday_15683.csv.gz  in=298,659,464 out=80,670,239 elapsed=124.8s

  [7253/17668] intraday_15687.csv.gz  in=298,671,020 out=80,681,795 elapsed=124.8s

  [7254/17668] intraday_15685.csv.gz  in=298,683,035 out=80,693,810 elapsed=124.8s

  [7255/17668] intraday_15684.csv.gz  in=298,696,038 out=80,706,813 elapsed=124.8s

  [7256/17668] intraday_15686.csv.gz  in=298,708,557 out=80,719,332 elapsed=124.8s

  [7257/17668] intraday_15688.csv.gz  in=298,718,649 out=80,729,424 elapsed=124.8s

  [7258/17668] intraday_1569.csv.gz  in=298,730,338 out=80,729,424 elapsed=124.9s

  [7259/17668] intraday_15689.csv.gz  in=298,739,453 out=80,738,539 elapsed=124.9s

  [7260/17668] intraday_15690.csv.gz  in=298,749,252 out=80,748,338 elapsed=124.9s

  [7261/17668] intraday_15691.csv.gz  in=298,754,613 out=80,753,699 elapsed=124.9s

  [7262/17668] intraday_15692.csv.gz  in=298,770,319 out=80,765,643 elapsed=124.9s

  [7263/17668] intraday_15693.csv.gz  in=298,786,712 out=80,782,036 elapsed=124.9s

  [7264/17668] intraday_15695.csv.gz  in=298,798,839 out=80,794,163 elapsed=125.0s

  [7265/17668] intraday_15694.csv.gz  in=298,813,227 out=80,808,551 elapsed=125.0s

  [7266/17668] intraday_15696.csv.gz  in=298,824,905 out=80,820,229 elapsed=125.0s

  [7267/17668] intraday_15697.csv.gz  in=298,836,557 out=80,831,881 elapsed=125.0s

  [7268/17668] intraday_15698.csv.gz  in=298,850,996 out=80,846,320 elapsed=125.0s

  [7269/17668] intraday_15699.csv.gz  in=298,863,642 out=80,858,966 elapsed=125.0s

  [7270/17668] intraday_1570.csv.gz  in=298,876,349 out=80,858,966 elapsed=125.0s

  [7271/17668] intraday_15700.csv.gz  in=298,887,229 out=80,869,846 elapsed=125.0s

  [7272/17668] intraday_15701.csv.gz  in=298,899,242 out=80,881,859 elapsed=125.1s

  [7273/17668] intraday_15703.csv.gz  in=298,910,457 out=80,893,074 elapsed=125.1s

  [7274/17668] intraday_15702.csv.gz  in=298,923,042 out=80,905,659 elapsed=125.1s

  [7275/17668] intraday_15704.csv.gz  in=298,938,602 out=80,920,464 elapsed=125.1s

  [7276/17668] intraday_15705.csv.gz  in=298,951,874 out=80,933,736 elapsed=125.1s

  [7277/17668] intraday_15706.csv.gz  in=298,964,081 out=80,945,943 elapsed=125.1s

  [7278/17668] intraday_1571.csv.gz  in=298,976,564 out=80,945,943 elapsed=125.2s

  [7279/17668] intraday_15707.csv.gz  in=298,986,498 out=80,955,877 elapsed=125.2s

  [7280/17668] intraday_15708.csv.gz  in=298,996,045 out=80,965,424 elapsed=125.2s

  [7281/17668] intraday_15709.csv.gz  in=299,011,772 out=80,981,151 elapsed=125.2s

  [7282/17668] intraday_15710.csv.gz  in=299,025,104 out=80,994,483 elapsed=125.2s

  [7283/17668] intraday_15712.csv.gz  in=299,037,477 out=81,006,750 elapsed=125.2s

  [7284/17668] intraday_15711.csv.gz  in=299,048,379 out=81,017,652 elapsed=125.2s

  [7285/17668] intraday_15713.csv.gz  in=299,059,452 out=81,028,725 elapsed=125.2s

  [7286/17668] intraday_15714.csv.gz  in=299,071,664 out=81,040,937 elapsed=125.3s

  [7287/17668] intraday_15715.csv.gz  in=299,086,788 out=81,055,615 elapsed=125.3s

  [7288/17668] intraday_15716.csv.gz  in=299,098,770 out=81,067,597 elapsed=125.3s

  [7289/17668] intraday_15718.csv.gz  in=299,110,024 out=81,078,851 elapsed=125.3s

  [7290/17668] intraday_15717.csv.gz  in=299,122,564 out=81,091,391 elapsed=125.3s

  [7291/17668] intraday_15719.csv.gz  in=299,132,328 out=81,101,155 elapsed=125.3s

  [7292/17668] intraday_1572.csv.gz  in=299,143,858 out=81,101,155 elapsed=125.3s

  [7293/17668] intraday_15721.csv.gz  in=299,156,660 out=81,113,957 elapsed=125.4s

  [7294/17668] intraday_15720.csv.gz  in=299,167,876 out=81,125,173 elapsed=125.4s

  [7295/17668] intraday_15722.csv.gz  in=299,179,483 out=81,136,780 elapsed=125.4s

  [7296/17668] intraday_15723.csv.gz  in=299,195,575 out=81,152,872 elapsed=125.4s

  [7297/17668] intraday_15725.csv.gz  in=299,205,643 out=81,162,940 elapsed=125.4s

  [7298/17668] intraday_15726.csv.gz  in=299,217,550 out=81,174,847 elapsed=125.4s

  [7299/17668] intraday_15724.csv.gz  in=299,230,252 out=81,187,549 elapsed=125.4s

  [7300/17668] intraday_15727.csv.gz  in=299,242,593 out=81,199,890 elapsed=125.5s

  [7301/17668] intraday_15728.csv.gz  in=299,254,548 out=81,211,845 elapsed=125.5s

  [7302/17668] intraday_15729.csv.gz  in=299,268,247 out=81,225,544 elapsed=125.5s

  [7303/17668] intraday_1573.csv.gz  in=299,281,089 out=81,225,544 elapsed=125.5s

  [7304/17668] intraday_15730.csv.gz  in=299,290,131 out=81,234,586 elapsed=125.5s

  [7305/17668] intraday_15731.csv.gz  in=299,301,711 out=81,246,166 elapsed=125.5s

  [7306/17668] intraday_15733.csv.gz  in=299,312,653 out=81,257,108 elapsed=125.5s

  [7307/17668] intraday_15732.csv.gz  in=299,321,552 out=81,266,007 elapsed=125.5s

  [7308/17668] intraday_15735.csv.gz  in=299,335,197 out=81,279,652 elapsed=125.5s

  [7309/17668] intraday_15734.csv.gz  in=299,352,659 out=81,295,598 elapsed=125.6s

  [7310/17668] intraday_15736.csv.gz  in=299,364,904 out=81,307,843 elapsed=125.6s

  [7311/17668] intraday_15737.csv.gz  in=299,378,408 out=81,321,347 elapsed=125.6s

  [7312/17668] intraday_15738.csv.gz  in=299,389,583 out=81,332,522 elapsed=125.6s

  [7313/17668] intraday_1574.csv.gz  in=299,402,455 out=81,332,522 elapsed=125.6s

  [7314/17668] intraday_15739.csv.gz  in=299,413,982 out=81,344,049 elapsed=125.6s

  [7315/17668] intraday_15740.csv.gz  in=299,424,930 out=81,354,997 elapsed=125.6s

  [7316/17668] intraday_15741.csv.gz  in=299,436,073 out=81,366,140 elapsed=125.6s

  [7317/17668] intraday_15742.csv.gz  in=299,447,438 out=81,377,505 elapsed=125.7s

  [7318/17668] intraday_15743.csv.gz  in=299,458,802 out=81,388,869 elapsed=125.7s

  [7319/17668] intraday_15744.csv.gz  in=299,471,934 out=81,402,001 elapsed=125.7s

  [7320/17668] intraday_15745.csv.gz  in=299,484,408 out=81,414,475 elapsed=125.7s

  [7321/17668] intraday_15747.csv.gz  in=299,497,808 out=81,427,875 elapsed=125.7s

  [7322/17668] intraday_15746.csv.gz  in=299,511,126 out=81,441,193 elapsed=125.7s

  [7323/17668] intraday_15749.csv.gz  in=299,522,190 out=81,452,257 elapsed=125.7s

  [7324/17668] intraday_15748.csv.gz  in=299,534,657 out=81,464,724 elapsed=125.7s

  [7325/17668] intraday_1575.csv.gz  in=299,561,592 out=81,464,724 elapsed=125.8s

  [7326/17668] intraday_15750.csv.gz  in=299,590,681 out=81,490,263 elapsed=125.8s

  [7327/17668] intraday_15751.csv.gz  in=299,602,920 out=81,502,502 elapsed=125.8s

  [7328/17668] intraday_15752.csv.gz  in=299,616,168 out=81,515,750 elapsed=125.8s

  [7329/17668] intraday_15753.csv.gz  in=299,627,094 out=81,526,676 elapsed=125.8s

  [7330/17668] intraday_15754.csv.gz  in=299,638,980 out=81,538,562 elapsed=125.8s

  [7331/17668] intraday_15756.csv.gz  in=299,649,605 out=81,549,187 elapsed=125.9s

  [7332/17668] intraday_15757.csv.gz  in=299,662,447 out=81,562,029 elapsed=125.9s

  [7333/17668] intraday_15755.csv.gz  in=299,673,569 out=81,573,151 elapsed=125.9s

  [7334/17668] intraday_15758.csv.gz  in=299,689,025 out=81,588,607 elapsed=125.9s

  [7335/17668] intraday_1576.csv.gz  in=299,701,691 out=81,588,607 elapsed=125.9s

  [7336/17668] intraday_15759.csv.gz  in=299,714,271 out=81,601,187 elapsed=125.9s

  [7337/17668] intraday_15760.csv.gz  in=299,726,462 out=81,613,378 elapsed=125.9s

  [7338/17668] intraday_15762.csv.gz  in=299,734,986 out=81,621,902 elapsed=125.9s

  [7339/17668] intraday_15763.csv.gz  in=299,746,323 out=81,633,239 elapsed=126.0s

  [7340/17668] intraday_15761.csv.gz  in=299,763,068 out=81,649,341 elapsed=126.0s

  [7341/17668] intraday_15764.csv.gz  in=299,775,950 out=81,662,223 elapsed=126.0s

  [7342/17668] intraday_15765.csv.gz  in=299,786,536 out=81,672,809 elapsed=126.0s

  [7343/17668] intraday_15767.csv.gz  in=299,798,575 out=81,684,848 elapsed=126.0s

  [7344/17668] intraday_15766.csv.gz  in=299,810,198 out=81,696,471 elapsed=126.0s

  [7345/17668] intraday_15768.csv.gz  in=299,820,541 out=81,706,814 elapsed=126.0s

  [7346/17668] intraday_15769.csv.gz  in=299,831,604 out=81,717,877 elapsed=126.0s

  [7347/17668] intraday_15771.csv.gz  in=299,842,343 out=81,728,616 elapsed=126.1s

  [7348/17668] intraday_1577.csv.gz  in=299,854,660 out=81,728,616 elapsed=126.1s

  [7349/17668] intraday_15772.csv.gz  in=299,867,183 out=81,741,139 elapsed=126.1s

  [7350/17668] intraday_15770.csv.gz  in=299,880,854 out=81,754,810 elapsed=126.1s

  [7351/17668] intraday_15773.csv.gz  in=299,891,019 out=81,764,975 elapsed=126.1s

  [7352/17668] intraday_15774.csv.gz  in=299,902,622 out=81,776,578 elapsed=126.1s

  [7353/17668] intraday_15775.csv.gz  in=299,915,044 out=81,789,000 elapsed=126.1s

  [7354/17668] intraday_15776.csv.gz  in=299,928,941 out=81,802,897 elapsed=126.1s

  [7355/17668] intraday_15778.csv.gz  in=299,942,221 out=81,816,177 elapsed=126.1s

  [7356/17668] intraday_15777.csv.gz  in=299,956,661 out=81,830,617 elapsed=126.1s

  [7357/17668] intraday_15779.csv.gz  in=299,968,997 out=81,842,953 elapsed=126.2s

  [7358/17668] intraday_1578.csv.gz  in=299,978,410 out=81,842,953 elapsed=126.2s

  [7359/17668] intraday_15780.csv.gz  in=299,990,646 out=81,855,189 elapsed=126.2s

  [7360/17668] intraday_15781.csv.gz  in=300,002,158 out=81,866,701 elapsed=126.2s

  [7361/17668] intraday_15782.csv.gz  in=300,016,545 out=81,881,063 elapsed=126.2s

  [7362/17668] intraday_15783.csv.gz  in=300,027,272 out=81,891,790 elapsed=126.2s

  [7363/17668] intraday_15785.csv.gz  in=300,041,127 out=81,905,645 elapsed=126.2s

  [7364/17668] intraday_15784.csv.gz  in=300,053,142 out=81,917,660 elapsed=126.3s

  [7365/17668] intraday_15786.csv.gz  in=300,065,025 out=81,929,543 elapsed=126.3s

  [7366/17668] intraday_15787.csv.gz  in=300,076,970 out=81,941,488 elapsed=126.3s

  [7367/17668] intraday_15788.csv.gz  in=300,088,654 out=81,953,172 elapsed=126.3s

  [7368/17668] intraday_15789.csv.gz  in=300,102,037 out=81,966,555 elapsed=126.3s

  [7369/17668] intraday_1579.csv.gz  in=300,114,268 out=81,966,555 elapsed=126.3s

  [7370/17668] intraday_15790.csv.gz  in=300,125,592 out=81,977,879 elapsed=126.3s

  [7371/17668] intraday_15791.csv.gz  in=300,137,049 out=81,989,336 elapsed=126.3s

  [7372/17668] intraday_15792.csv.gz  in=300,148,122 out=82,000,409 elapsed=126.4s

  [7373/17668] intraday_15793.csv.gz  in=300,159,957 out=82,012,244 elapsed=126.4s

  [7374/17668] intraday_15795.csv.gz  in=300,172,796 out=82,025,083 elapsed=126.4s

  [7375/17668] intraday_15794.csv.gz  in=300,187,010 out=82,039,297 elapsed=126.4s

  [7376/17668] intraday_15796.csv.gz  in=300,199,265 out=82,051,552 elapsed=126.4s

  [7377/17668] intraday_15797.csv.gz  in=300,211,504 out=82,063,791 elapsed=126.4s

  [7378/17668] intraday_15798.csv.gz  in=300,221,173 out=82,073,460 elapsed=126.4s

  [7379/17668] intraday_15799.csv.gz  in=300,236,914 out=82,089,201 elapsed=126.4s

  [7380/17668] intraday_1580.csv.gz  in=300,250,520 out=82,089,201 elapsed=126.4s

  [7381/17668] intraday_15800.csv.gz  in=300,261,451 out=82,100,132 elapsed=126.4s

  [7382/17668] intraday_15801.csv.gz  in=300,273,200 out=82,111,881 elapsed=126.5s

  [7383/17668] intraday_15804.csv.gz  in=300,284,221 out=82,122,902 elapsed=126.5s

  [7384/17668] intraday_15802.csv.gz  in=300,296,972 out=82,135,653 elapsed=126.5s

  [7385/17668] intraday_15803.csv.gz  in=300,311,235 out=82,149,916 elapsed=126.6s

  [7386/17668] intraday_15805.csv.gz  in=300,326,211 out=82,164,892 elapsed=126.6s

  [7387/17668] intraday_15806.csv.gz  in=300,339,440 out=82,178,121 elapsed=126.6s

  [7388/17668] intraday_15808.csv.gz  in=300,351,810 out=82,190,491 elapsed=126.6s

  [7389/17668] intraday_15807.csv.gz  in=300,364,770 out=82,203,451 elapsed=126.6s

  [7390/17668] intraday_1581.csv.gz  in=300,375,332 out=82,203,451 elapsed=126.6s

  [7391/17668] intraday_15809.csv.gz  in=300,391,515 out=82,219,634 elapsed=126.6s

  [7392/17668] intraday_15810.csv.gz  in=300,408,568 out=82,236,687 elapsed=126.6s

  [7393/17668] intraday_15812.csv.gz  in=300,421,469 out=82,249,588 elapsed=126.7s

  [7394/17668] intraday_15813.csv.gz  in=300,434,509 out=82,262,628 elapsed=126.7s

  [7395/17668] intraday_15811.csv.gz  in=300,448,750 out=82,276,869 elapsed=126.7s

  [7396/17668] intraday_15814.csv.gz  in=300,461,993 out=82,290,112 elapsed=126.7s

  [7397/17668] intraday_15815.csv.gz  in=300,471,193 out=82,299,312 elapsed=126.7s

  [7398/17668] intraday_15817.csv.gz  in=300,481,862 out=82,309,981 elapsed=126.7s

  [7399/17668] intraday_15816.csv.gz  in=300,494,225 out=82,322,344 elapsed=126.7s

  [7400/17668] intraday_15818.csv.gz  in=300,506,600 out=82,334,719 elapsed=126.7s

  [7401/17668] intraday_15819.csv.gz  in=300,519,724 out=82,347,843 elapsed=126.8s

  [7402/17668] intraday_1582.csv.gz  in=300,533,718 out=82,347,843 elapsed=126.8s

  [7403/17668] intraday_15820.csv.gz  in=300,547,598 out=82,361,723 elapsed=126.8s

  [7404/17668] intraday_15821.csv.gz  in=300,557,773 out=82,371,898 elapsed=126.8s

  [7405/17668] intraday_15822.csv.gz  in=300,570,898 out=82,385,023 elapsed=126.8s

  [7406/17668] intraday_15823.csv.gz  in=300,583,157 out=82,397,282 elapsed=126.8s

  [7407/17668] intraday_15824.csv.gz  in=300,595,713 out=82,409,838 elapsed=126.8s

  [7408/17668] intraday_15825.csv.gz  in=300,607,227 out=82,421,352 elapsed=126.8s

  [7409/17668] intraday_15826.csv.gz  in=300,619,829 out=82,433,954 elapsed=126.8s

  [7410/17668] intraday_15827.csv.gz  in=300,632,872 out=82,446,997 elapsed=126.8s

  [7411/17668] intraday_15828.csv.gz  in=300,646,012 out=82,460,137 elapsed=126.9s

  [7412/17668] intraday_15829.csv.gz  in=300,660,678 out=82,474,803 elapsed=126.9s

  [7413/17668] intraday_1583.csv.gz  in=300,674,340 out=82,474,803 elapsed=126.9s

  [7414/17668] intraday_15830.csv.gz  in=300,685,574 out=82,486,037 elapsed=126.9s

  [7415/17668] intraday_15831.csv.gz  in=300,697,609 out=82,498,072 elapsed=126.9s

  [7416/17668] intraday_15832.csv.gz  in=300,709,296 out=82,509,759 elapsed=126.9s

  [7417/17668] intraday_15834.csv.gz  in=300,720,142 out=82,520,605 elapsed=126.9s

  [7418/17668] intraday_15833.csv.gz  in=300,731,380 out=82,531,843 elapsed=126.9s

  [7419/17668] intraday_15835.csv.gz  in=300,739,495 out=82,539,958 elapsed=127.0s

  [7420/17668] intraday_15836.csv.gz  in=300,751,112 out=82,551,575 elapsed=127.0s

  [7421/17668] intraday_15837.csv.gz  in=300,757,464 out=82,557,927 elapsed=127.0s

  [7422/17668] intraday_1584.csv.gz  in=300,771,380 out=82,557,927 elapsed=127.0s

  [7423/17668] intraday_15839.csv.gz  in=300,785,448 out=82,571,995 elapsed=127.0s

  [7424/17668] intraday_15838.csv.gz  in=300,801,918 out=82,588,465 elapsed=127.0s

  [7425/17668] intraday_15840.csv.gz  in=300,814,706 out=82,601,253 elapsed=127.0s

  [7426/17668] intraday_15841.csv.gz  in=300,827,726 out=82,614,273 elapsed=127.1s

  [7427/17668] intraday_15842.csv.gz  in=300,839,132 out=82,625,679 elapsed=127.1s

  [7428/17668] intraday_15844.csv.gz  in=300,851,116 out=82,637,663 elapsed=127.1s

  [7429/17668] intraday_15843.csv.gz  in=300,864,315 out=82,650,862 elapsed=127.1s

  [7430/17668] intraday_15845.csv.gz  in=300,876,091 out=82,662,638 elapsed=127.1s

  [7431/17668] intraday_15846.csv.gz  in=300,888,939 out=82,675,486 elapsed=127.1s

  [7432/17668] intraday_15847.csv.gz  in=300,901,047 out=82,687,594 elapsed=127.1s

  [7433/17668] intraday_15849.csv.gz  in=300,914,383 out=82,700,930 elapsed=127.1s

  [7434/17668] intraday_15848.csv.gz  in=300,925,088 out=82,711,635 elapsed=127.1s

  [7435/17668] intraday_1585.csv.gz  in=300,936,257 out=82,711,635 elapsed=127.1s

  [7436/17668] intraday_15850.csv.gz  in=300,949,090 out=82,724,468 elapsed=127.2s

  [7437/17668] intraday_15851.csv.gz  in=300,963,121 out=82,738,499 elapsed=127.2s

  [7438/17668] intraday_15852.csv.gz  in=300,972,633 out=82,748,011 elapsed=127.2s

  [7439/17668] intraday_15853.csv.gz  in=300,981,684 out=82,757,062 elapsed=127.2s

  [7440/17668] intraday_15854.csv.gz  in=300,997,549 out=82,772,927 elapsed=127.2s

  [7441/17668] intraday_15855.csv.gz  in=301,009,946 out=82,785,324 elapsed=127.2s

  [7442/17668] intraday_15856.csv.gz  in=301,020,790 out=82,796,168 elapsed=127.2s

  [7443/17668] intraday_15857.csv.gz  in=301,032,395 out=82,807,773 elapsed=127.2s

  [7444/17668] intraday_15858.csv.gz  in=301,043,986 out=82,819,364 elapsed=127.3s

  [7445/17668] intraday_15859.csv.gz  in=301,056,941 out=82,832,319 elapsed=127.3s

  [7446/17668] intraday_1586.csv.gz  in=301,069,312 out=82,832,319 elapsed=127.3s

  [7447/17668] intraday_15860.csv.gz  in=301,081,355 out=82,844,362 elapsed=127.3s

  [7448/17668] intraday_15861.csv.gz  in=301,093,514 out=82,856,521 elapsed=127.3s

  [7449/17668] intraday_15862.csv.gz  in=301,105,996 out=82,869,003 elapsed=127.3s

  [7450/17668] intraday_15863.csv.gz  in=301,117,059 out=82,880,066 elapsed=127.3s

  [7451/17668] intraday_15864.csv.gz  in=301,127,544 out=82,890,551 elapsed=127.3s

  [7452/17668] intraday_15866.csv.gz  in=301,140,493 out=82,903,500 elapsed=127.4s

  [7453/17668] intraday_15865.csv.gz  in=301,152,682 out=82,915,689 elapsed=127.4s

  [7454/17668] intraday_15867.csv.gz  in=301,164,842 out=82,927,849 elapsed=127.4s

  [7455/17668] intraday_15868.csv.gz  in=301,180,633 out=82,943,640 elapsed=127.4s

  [7456/17668] intraday_15869.csv.gz  in=301,191,590 out=82,954,597 elapsed=127.4s

  [7457/17668] intraday_1587.csv.gz  in=301,204,196 out=82,954,597 elapsed=127.4s

  [7458/17668] intraday_15870.csv.gz  in=301,214,422 out=82,964,823 elapsed=127.4s

  [7459/17668] intraday_15871.csv.gz  in=301,227,055 out=82,977,456 elapsed=127.4s

  [7460/17668] intraday_15873.csv.gz  in=301,238,570 out=82,988,971 elapsed=127.4s

  [7461/17668] intraday_15874.csv.gz  in=301,252,044 out=83,002,445 elapsed=127.5s

  [7462/17668] intraday_15872.csv.gz  in=301,276,131 out=83,026,532 elapsed=127.5s

  [7463/17668] intraday_15875.csv.gz  in=301,286,130 out=83,036,531 elapsed=127.5s

  [7464/17668] intraday_15876.csv.gz  in=301,296,725 out=83,047,126 elapsed=127.5s

  [7465/17668] intraday_15877.csv.gz  in=301,306,281 out=83,056,682 elapsed=127.5s

  [7466/17668] intraday_15878.csv.gz  in=301,318,871 out=83,069,272 elapsed=127.5s

  [7467/17668] intraday_1588.csv.gz  in=301,330,265 out=83,069,272 elapsed=127.5s

  [7468/17668] intraday_15879.csv.gz  in=301,342,230 out=83,081,237 elapsed=127.5s

  [7469/17668] intraday_15880.csv.gz  in=301,356,133 out=83,095,140 elapsed=127.5s

  [7470/17668] intraday_15881.csv.gz  in=301,366,768 out=83,105,775 elapsed=127.6s

  [7471/17668] intraday_15882.csv.gz  in=301,380,445 out=83,119,452 elapsed=127.6s

  [7472/17668] intraday_15883.csv.gz  in=301,395,953 out=83,134,192 elapsed=127.6s

  [7473/17668] intraday_15884.csv.gz  in=301,407,690 out=83,145,929 elapsed=127.6s

  [7474/17668] intraday_15886.csv.gz  in=301,418,425 out=83,156,664 elapsed=127.6s

  [7475/17668] intraday_15885.csv.gz  in=301,430,014 out=83,168,253 elapsed=127.6s

  [7476/17668] intraday_15887.csv.gz  in=301,442,429 out=83,180,668 elapsed=127.6s

  [7477/17668] intraday_1589.csv.gz  in=301,453,951 out=83,180,668 elapsed=127.7s

  [7478/17668] intraday_15888.csv.gz  in=301,466,460 out=83,192,777 elapsed=127.7s

  [7479/17668] intraday_15889.csv.gz  in=301,481,117 out=83,207,434 elapsed=127.7s

  [7480/17668] intraday_15890.csv.gz  in=301,500,528 out=83,225,492 elapsed=127.7s

  [7481/17668] intraday_15892.csv.gz  in=301,513,449 out=83,238,413 elapsed=127.7s

  [7482/17668] intraday_15891.csv.gz  in=301,526,170 out=83,251,134 elapsed=127.7s

  [7483/17668] intraday_15893.csv.gz  in=301,539,248 out=83,264,212 elapsed=127.7s

  [7484/17668] intraday_15894.csv.gz  in=301,549,747 out=83,274,711 elapsed=127.7s

  [7485/17668] intraday_15895.csv.gz  in=301,560,911 out=83,285,875 elapsed=127.8s

  [7486/17668] intraday_15897.csv.gz  in=301,572,790 out=83,297,754 elapsed=127.8s

  [7487/17668] intraday_15898.csv.gz  in=301,584,712 out=83,309,676 elapsed=127.8s

  [7488/17668] intraday_15896.csv.gz  in=301,618,384 out=83,340,382 elapsed=127.8s

  [7489/17668] intraday_1590.csv.gz  in=301,629,880 out=83,340,382 elapsed=127.8s

  [7490/17668] intraday_15899.csv.gz  in=301,646,909 out=83,356,475 elapsed=127.8s

  [7491/17668] intraday_15900.csv.gz  in=301,659,531 out=83,369,097 elapsed=127.8s

  [7492/17668] intraday_15901.csv.gz  in=301,670,613 out=83,380,179 elapsed=127.9s

  [7493/17668] intraday_15902.csv.gz  in=301,681,880 out=83,391,446 elapsed=127.9s

  [7494/17668] intraday_15903.csv.gz  in=301,695,766 out=83,405,332 elapsed=127.9s

  [7495/17668] intraday_15904.csv.gz  in=301,709,363 out=83,418,929 elapsed=127.9s

  [7496/17668] intraday_15905.csv.gz  in=301,722,119 out=83,431,685 elapsed=127.9s

  [7497/17668] intraday_15907.csv.gz  in=301,732,629 out=83,442,195 elapsed=127.9s

  [7498/17668] intraday_15908.csv.gz  in=301,743,084 out=83,452,650 elapsed=128.0s

  [7499/17668] intraday_15906.csv.gz  in=301,764,774 out=83,472,766 elapsed=128.0s

  [7500/17668] intraday_1591.csv.gz  in=301,776,794 out=83,472,766 elapsed=128.0s

  [7501/17668] intraday_15909.csv.gz  in=301,789,822 out=83,485,794 elapsed=128.0s

  [7502/17668] intraday_15910.csv.gz  in=301,799,723 out=83,495,695 elapsed=128.0s

  [7503/17668] intraday_15911.csv.gz  in=301,812,212 out=83,508,184 elapsed=128.0s

  [7504/17668] intraday_15913.csv.gz  in=301,822,116 out=83,518,088 elapsed=128.0s

  [7505/17668] intraday_15912.csv.gz  in=301,832,929 out=83,528,901 elapsed=128.0s

  [7506/17668] intraday_15914.csv.gz  in=301,843,661 out=83,539,633 elapsed=128.0s

  [7507/17668] intraday_15915.csv.gz  in=301,857,458 out=83,553,430 elapsed=128.1s

  [7508/17668] intraday_15916.csv.gz  in=301,868,974 out=83,564,946 elapsed=128.1s

  [7509/17668] intraday_15917.csv.gz  in=301,881,359 out=83,577,331 elapsed=128.1s

  [7510/17668] intraday_15918.csv.gz  in=301,892,188 out=83,588,160 elapsed=128.1s

  [7511/17668] intraday_15919.csv.gz  in=301,902,630 out=83,598,602 elapsed=128.1s

  [7512/17668] intraday_1592.csv.gz  in=301,914,067 out=83,598,602 elapsed=128.1s

  [7513/17668] intraday_15920.csv.gz  in=301,926,619 out=83,611,154 elapsed=128.1s

  [7514/17668] intraday_15921.csv.gz  in=301,940,634 out=83,625,169 elapsed=128.1s

  [7515/17668] intraday_15922.csv.gz  in=301,954,751 out=83,639,286 elapsed=128.2s

  [7516/17668] intraday_15923.csv.gz  in=301,967,185 out=83,651,720 elapsed=128.2s

  [7517/17668] intraday_15924.csv.gz  in=301,978,964 out=83,663,499 elapsed=128.2s

  [7518/17668] intraday_15925.csv.gz  in=301,990,743 out=83,675,278 elapsed=128.2s

  [7519/17668] intraday_15926.csv.gz  in=302,001,386 out=83,685,921 elapsed=128.2s

  [7520/17668] intraday_15928.csv.gz  in=302,013,210 out=83,697,745 elapsed=128.2s

  [7521/17668] intraday_15927.csv.gz  in=302,027,027 out=83,711,562 elapsed=128.2s

  [7522/17668] intraday_1593.csv.gz  in=302,038,946 out=83,711,562 elapsed=128.2s

  [7523/17668] intraday_15929.csv.gz  in=302,050,725 out=83,723,341 elapsed=128.2s

  [7524/17668] intraday_15931.csv.gz  in=302,063,458 out=83,736,074 elapsed=128.3s

  [7525/17668] intraday_15933.csv.gz  in=302,075,860 out=83,748,476 elapsed=128.3s

  [7526/17668] intraday_15930.csv.gz  in=302,114,428 out=83,782,577 elapsed=128.3s

  [7527/17668] intraday_15934.csv.gz  in=302,127,831 out=83,795,980 elapsed=128.3s

  [7528/17668] intraday_15932.csv.gz  in=302,139,755 out=83,807,904 elapsed=128.3s

  [7529/17668] intraday_15935.csv.gz  in=302,152,320 out=83,820,469 elapsed=128.4s

  [7530/17668] intraday_15938.csv.gz  in=302,163,428 out=83,831,577 elapsed=128.4s

  [7531/17668] intraday_15937.csv.gz  in=302,174,026 out=83,842,175 elapsed=128.4s

  [7532/17668] intraday_15939.csv.gz  in=302,186,412 out=83,854,561 elapsed=128.4s

  [7533/17668] intraday_15936.csv.gz  in=302,197,721 out=83,865,870 elapsed=128.4s

  [7534/17668] intraday_1594.csv.gz  in=302,208,956 out=83,865,870 elapsed=128.4s

  [7535/17668] intraday_15940.csv.gz  in=302,228,038 out=83,883,989 elapsed=128.5s

  [7536/17668] intraday_15941.csv.gz  in=302,240,218 out=83,896,169 elapsed=128.5s

  [7537/17668] intraday_15942.csv.gz  in=302,251,852 out=83,907,803 elapsed=128.5s

  [7538/17668] intraday_15943.csv.gz  in=302,262,966 out=83,918,917 elapsed=128.5s

  [7539/17668] intraday_15944.csv.gz  in=302,277,682 out=83,933,633 elapsed=128.5s

  [7540/17668] intraday_15945.csv.gz  in=302,288,069 out=83,944,020 elapsed=128.5s

  [7541/17668] intraday_15947.csv.gz  in=302,301,117 out=83,957,068 elapsed=128.5s

  [7542/17668] intraday_15946.csv.gz  in=302,312,407 out=83,968,358 elapsed=128.5s

  [7543/17668] intraday_15948.csv.gz  in=302,325,788 out=83,981,739 elapsed=128.6s

  [7544/17668] intraday_15949.csv.gz  in=302,336,944 out=83,992,895 elapsed=128.6s

  [7545/17668] intraday_1595.csv.gz  in=302,347,093 out=83,992,895 elapsed=128.6s

  [7546/17668] intraday_15950.csv.gz  in=302,361,038 out=84,006,840 elapsed=128.6s

  [7547/17668] intraday_15951.csv.gz  in=302,375,134 out=84,020,936 elapsed=128.6s

  [7548/17668] intraday_15953.csv.gz  in=302,387,682 out=84,033,484 elapsed=128.6s

  [7549/17668] intraday_15952.csv.gz  in=302,401,839 out=84,047,641 elapsed=128.6s

  [7550/17668] intraday_15955.csv.gz  in=302,419,398 out=84,065,200 elapsed=128.7s

  [7551/17668] intraday_15954.csv.gz  in=302,436,283 out=84,082,085 elapsed=128.7s

  [7552/17668] intraday_15956.csv.gz  in=302,450,096 out=84,095,898 elapsed=128.7s

  [7553/17668] intraday_15957.csv.gz  in=302,463,638 out=84,109,440 elapsed=128.7s

  [7554/17668] intraday_15958.csv.gz  in=302,474,617 out=84,120,419 elapsed=128.7s

  [7555/17668] intraday_15959.csv.gz  in=302,489,582 out=84,135,384 elapsed=128.7s

  [7556/17668] intraday_15960.csv.gz  in=302,500,411 out=84,146,213 elapsed=128.7s

  [7557/17668] intraday_1596.csv.gz  in=302,512,160 out=84,146,213 elapsed=128.7s

  [7558/17668] intraday_15962.csv.gz  in=302,521,992 out=84,156,045 elapsed=128.7s

  [7559/17668] intraday_15961.csv.gz  in=302,538,023 out=84,171,495 elapsed=128.8s

  [7560/17668] intraday_15964.csv.gz  in=302,550,404 out=84,183,876 elapsed=128.8s

  [7561/17668] intraday_15963.csv.gz  in=302,564,279 out=84,197,751 elapsed=128.8s

  [7562/17668] intraday_15965.csv.gz  in=302,577,490 out=84,210,962 elapsed=128.8s

  [7563/17668] intraday_15966.csv.gz  in=302,588,438 out=84,221,910 elapsed=128.8s

  [7564/17668] intraday_15967.csv.gz  in=302,601,003 out=84,234,475 elapsed=128.8s

  [7565/17668] intraday_15968.csv.gz  in=302,613,216 out=84,246,688 elapsed=128.8s

  [7566/17668] intraday_1597.csv.gz  in=302,625,347 out=84,246,688 elapsed=128.8s

  [7567/17668] intraday_15969.csv.gz  in=302,638,087 out=84,259,428 elapsed=128.8s

  [7568/17668] intraday_15970.csv.gz  in=302,653,401 out=84,274,209 elapsed=128.9s

  [7569/17668] intraday_15971.csv.gz  in=302,667,028 out=84,287,836 elapsed=128.9s

  [7570/17668] intraday_15973.csv.gz  in=302,678,813 out=84,299,621 elapsed=128.9s

  [7571/17668] intraday_15972.csv.gz  in=302,693,127 out=84,313,935 elapsed=128.9s

  [7572/17668] intraday_15974.csv.gz  in=302,709,071 out=84,329,879 elapsed=128.9s

  [7573/17668] intraday_15975.csv.gz  in=302,719,101 out=84,339,909 elapsed=128.9s

  [7574/17668] intraday_15976.csv.gz  in=302,730,751 out=84,351,559 elapsed=128.9s

  [7575/17668] intraday_15977.csv.gz  in=302,743,047 out=84,363,855 elapsed=128.9s

  [7576/17668] intraday_15978.csv.gz  in=302,753,146 out=84,373,954 elapsed=128.9s

  [7577/17668] intraday_15979.csv.gz  in=302,765,145 out=84,385,953 elapsed=129.0s

  [7578/17668] intraday_1598.csv.gz  in=302,780,735 out=84,385,953 elapsed=129.0s

  [7579/17668] intraday_15980.csv.gz  in=302,789,705 out=84,394,923 elapsed=129.0s

  [7580/17668] intraday_15981.csv.gz  in=302,799,756 out=84,404,974 elapsed=129.0s

  [7581/17668] intraday_15982.csv.gz  in=302,808,437 out=84,413,655 elapsed=129.0s

  [7582/17668] intraday_15983.csv.gz  in=302,824,012 out=84,429,230 elapsed=129.0s

  [7583/17668] intraday_15985.csv.gz  in=302,838,641 out=84,443,859 elapsed=129.1s

  [7584/17668] intraday_15986.csv.gz  in=302,850,510 out=84,455,728 elapsed=129.1s

  [7585/17668] intraday_15987.csv.gz  in=302,865,049 out=84,470,267 elapsed=129.1s

  [7586/17668] intraday_15984.csv.gz  in=302,878,036 out=84,483,254 elapsed=129.1s

  [7587/17668] intraday_15989.csv.gz  in=302,890,398 out=84,495,616 elapsed=129.1s

  [7588/17668] intraday_15988.csv.gz  in=302,905,150 out=84,510,368 elapsed=129.1s

  [7589/17668] intraday_1599.csv.gz  in=302,930,932 out=84,510,368 elapsed=129.1s

  [7590/17668] intraday_15990.csv.gz  in=302,942,588 out=84,522,024 elapsed=129.1s

  [7591/17668] intraday_15991.csv.gz  in=302,953,717 out=84,533,153 elapsed=129.2s

  [7592/17668] intraday_15992.csv.gz  in=302,969,189 out=84,548,511 elapsed=129.2s

  [7593/17668] intraday_15993.csv.gz  in=302,978,986 out=84,558,308 elapsed=129.2s

  [7594/17668] intraday_15994.csv.gz  in=302,991,541 out=84,570,863 elapsed=129.2s

  [7595/17668] intraday_15995.csv.gz  in=303,004,769 out=84,584,091 elapsed=129.2s

  [7596/17668] intraday_15996.csv.gz  in=303,017,027 out=84,596,349 elapsed=129.2s

  [7597/17668] intraday_15997.csv.gz  in=303,027,159 out=84,606,481 elapsed=129.2s

  [7598/17668] intraday_1600.csv.gz  in=303,037,244 out=84,606,481 elapsed=129.2s

  [7599/17668] intraday_15998.csv.gz  in=303,048,184 out=84,617,421 elapsed=129.2s

  [7600/17668] intraday_15999.csv.gz  in=303,062,288 out=84,631,525 elapsed=129.2s

  [7601/17668] intraday_16000.csv.gz  in=303,074,895 out=84,644,132 elapsed=129.3s

  [7602/17668] intraday_16001.csv.gz  in=303,085,816 out=84,655,053 elapsed=129.3s

  [7603/17668] intraday_16003.csv.gz  in=303,097,644 out=84,666,881 elapsed=129.3s

  [7604/17668] intraday_16002.csv.gz  in=303,107,856 out=84,677,093 elapsed=129.3s

  [7605/17668] intraday_16004.csv.gz  in=303,120,045 out=84,689,282 elapsed=129.3s

  [7606/17668] intraday_16005.csv.gz  in=303,131,784 out=84,701,021 elapsed=129.3s

  [7607/17668] intraday_16006.csv.gz  in=303,144,372 out=84,713,609 elapsed=129.3s

  [7608/17668] intraday_16007.csv.gz  in=303,156,656 out=84,725,893 elapsed=129.3s

  [7609/17668] intraday_16009.csv.gz  in=303,166,413 out=84,735,650 elapsed=129.3s

  [7610/17668] intraday_1601.csv.gz  in=303,177,780 out=84,735,650 elapsed=129.4s

  [7611/17668] intraday_16010.csv.gz  in=303,189,575 out=84,747,445 elapsed=129.4s

  [7612/17668] intraday_16011.csv.gz  in=303,202,393 out=84,760,263 elapsed=129.4s

  [7613/17668] intraday_16008.csv.gz  in=303,235,808 out=84,790,771 elapsed=129.4s

  [7614/17668] intraday_16012.csv.gz  in=303,248,050 out=84,803,013 elapsed=129.4s

  [7615/17668] intraday_16013.csv.gz  in=303,263,884 out=84,818,790 elapsed=129.4s

  [7616/17668] intraday_16015.csv.gz  in=303,274,305 out=84,829,211 elapsed=129.5s

  [7617/17668] intraday_16014.csv.gz  in=303,286,909 out=84,841,815 elapsed=129.5s

  [7618/17668] intraday_16016.csv.gz  in=303,299,776 out=84,854,682 elapsed=129.5s

  [7619/17668] intraday_16019.csv.gz  in=303,312,020 out=84,866,926 elapsed=129.5s

  [7620/17668] intraday_16017.csv.gz  in=303,335,762 out=84,890,668 elapsed=129.5s

  [7621/17668] intraday_1602.csv.gz  in=303,348,047 out=84,890,668 elapsed=129.5s

  [7622/17668] intraday_16018.csv.gz  in=303,360,316 out=84,902,937 elapsed=129.5s

  [7623/17668] intraday_16020.csv.gz  in=303,371,319 out=84,913,940 elapsed=129.5s

  [7624/17668] intraday_16021.csv.gz  in=303,381,348 out=84,923,969 elapsed=129.5s

  [7625/17668] intraday_16022.csv.gz  in=303,390,903 out=84,933,524 elapsed=129.6s

  [7626/17668] intraday_16024.csv.gz  in=303,402,485 out=84,945,106 elapsed=129.6s

  [7627/17668] intraday_16023.csv.gz  in=303,413,027 out=84,955,648 elapsed=129.6s

  [7628/17668] intraday_16025.csv.gz  in=303,427,719 out=84,970,340 elapsed=129.6s

  [7629/17668] intraday_16026.csv.gz  in=303,442,934 out=84,985,555 elapsed=129.6s

  [7630/17668] intraday_16028.csv.gz  in=303,452,605 out=84,995,226 elapsed=129.6s

  [7631/17668] intraday_16027.csv.gz  in=303,465,558 out=85,008,179 elapsed=129.6s

  [7632/17668] intraday_16029.csv.gz  in=303,478,387 out=85,021,008 elapsed=129.6s

  [7633/17668] intraday_1603.csv.gz  in=303,493,613 out=85,021,008 elapsed=129.6s

  [7634/17668] intraday_16030.csv.gz  in=303,506,762 out=85,034,157 elapsed=129.7s

  [7635/17668] intraday_16033.csv.gz  in=303,517,219 out=85,044,614 elapsed=129.7s

  [7636/17668] intraday_16032.csv.gz  in=303,529,731 out=85,057,126 elapsed=129.7s

  [7637/17668] intraday_16031.csv.gz  in=303,548,236 out=85,074,582 elapsed=129.7s

  [7638/17668] intraday_16035.csv.gz  in=303,559,996 out=85,086,342 elapsed=129.7s

  [7639/17668] intraday_16034.csv.gz  in=303,573,716 out=85,100,062 elapsed=129.7s

  [7640/17668] intraday_16039.csv.gz  in=303,584,050 out=85,110,396 elapsed=129.8s

  [7641/17668] intraday_16036.csv.gz  in=303,596,397 out=85,122,743 elapsed=129.8s

  [7642/17668] intraday_16038.csv.gz  in=303,609,552 out=85,135,898 elapsed=129.8s

  [7643/17668] intraday_1604.csv.gz  in=303,621,954 out=85,135,898 elapsed=129.8s

  [7644/17668] intraday_16037.csv.gz  in=303,634,100 out=85,148,044 elapsed=129.8s

  [7645/17668] intraday_16040.csv.gz  in=303,647,205 out=85,160,715 elapsed=129.8s

  [7646/17668] intraday_16042.csv.gz  in=303,660,131 out=85,173,641 elapsed=129.9s

  [7647/17668] intraday_16041.csv.gz  in=303,675,263 out=85,188,773 elapsed=129.9s

  [7648/17668] intraday_16044.csv.gz  in=303,686,963 out=85,200,473 elapsed=129.9s

  [7649/17668] intraday_16043.csv.gz  in=303,697,565 out=85,211,075 elapsed=129.9s

  [7650/17668] intraday_16045.csv.gz  in=303,708,506 out=85,222,016 elapsed=129.9s

  [7651/17668] intraday_16046.csv.gz  in=303,719,265 out=85,232,775 elapsed=129.9s

  [7652/17668] intraday_16047.csv.gz  in=303,731,836 out=85,245,346 elapsed=129.9s

  [7653/17668] intraday_16048.csv.gz  in=303,747,015 out=85,260,525 elapsed=129.9s

  [7654/17668] intraday_16049.csv.gz  in=303,757,533 out=85,271,043 elapsed=129.9s

  [7655/17668] intraday_1605.csv.gz  in=303,771,315 out=85,271,043 elapsed=130.0s

  [7656/17668] intraday_16050.csv.gz  in=303,783,666 out=85,283,394 elapsed=130.0s

  [7657/17668] intraday_16052.csv.gz  in=303,798,671 out=85,297,490 elapsed=130.0s

  [7658/17668] intraday_16053.csv.gz  in=303,810,540 out=85,309,359 elapsed=130.0s

  [7659/17668] intraday_16051.csv.gz  in=303,851,828 out=85,346,754 elapsed=130.0s

  [7660/17668] intraday_16054.csv.gz  in=303,864,857 out=85,359,783 elapsed=130.0s

  [7661/17668] intraday_16055.csv.gz  in=303,875,986 out=85,370,912 elapsed=130.0s

  [7662/17668] intraday_16056.csv.gz  in=303,890,424 out=85,385,350 elapsed=130.1s

  [7663/17668] intraday_16057.csv.gz  in=303,901,792 out=85,396,002 elapsed=130.1s

  [7664/17668] intraday_16058.csv.gz  in=303,911,517 out=85,405,727 elapsed=130.1s

  [7665/17668] intraday_1606.csv.gz  in=303,924,502 out=85,405,727 elapsed=130.1s

  [7666/17668] intraday_16059.csv.gz  in=303,935,895 out=85,417,120 elapsed=130.1s

  [7667/17668] intraday_16060.csv.gz  in=303,949,655 out=85,430,880 elapsed=130.1s

  [7668/17668] intraday_16061.csv.gz  in=303,960,736 out=85,441,961 elapsed=130.1s

  [7669/17668] intraday_16062.csv.gz  in=303,971,987 out=85,453,212 elapsed=130.1s

  [7670/17668] intraday_16063.csv.gz  in=303,981,970 out=85,463,195 elapsed=130.1s

  [7671/17668] intraday_16064.csv.gz  in=303,992,743 out=85,473,968 elapsed=130.2s

  [7672/17668] intraday_16065.csv.gz  in=304,004,523 out=85,485,748 elapsed=130.2s

  [7673/17668] intraday_16066.csv.gz  in=304,019,297 out=85,500,522 elapsed=130.2s

  [7674/17668] intraday_16067.csv.gz  in=304,033,693 out=85,514,918 elapsed=130.2s

  [7675/17668] intraday_16068.csv.gz  in=304,047,757 out=85,528,982 elapsed=130.2s

  [7676/17668] intraday_16069.csv.gz  in=304,058,446 out=85,539,671 elapsed=130.2s

  [7677/17668] intraday_1607.csv.gz  in=304,072,659 out=85,539,671 elapsed=130.2s

  [7678/17668] intraday_16071.csv.gz  in=304,082,705 out=85,549,717 elapsed=130.3s

  [7679/17668] intraday_16070.csv.gz  in=304,099,116 out=85,566,128 elapsed=130.3s

  [7680/17668] intraday_16072.csv.gz  in=304,113,867 out=85,580,879 elapsed=130.3s

  [7681/17668] intraday_16073.csv.gz  in=304,123,697 out=85,590,709 elapsed=130.3s

  [7682/17668] intraday_16074.csv.gz  in=304,135,995 out=85,603,007 elapsed=130.3s

  [7683/17668] intraday_16075.csv.gz  in=304,147,274 out=85,614,286 elapsed=130.3s

  [7684/17668] intraday_16076.csv.gz  in=304,160,309 out=85,627,321 elapsed=130.4s

  [7685/17668] intraday_16079.csv.gz  in=304,172,325 out=85,639,337 elapsed=130.4s

  [7686/17668] intraday_16077.csv.gz  in=304,184,691 out=85,651,703 elapsed=130.4s

  [7687/17668] intraday_16078.csv.gz  in=304,197,395 out=85,664,407 elapsed=130.4s

  [7688/17668] intraday_1608.csv.gz  in=304,211,456 out=85,664,407 elapsed=130.4s

  [7689/17668] intraday_16080.csv.gz  in=304,222,135 out=85,675,086 elapsed=130.4s

  [7690/17668] intraday_16081.csv.gz  in=304,233,845 out=85,686,796 elapsed=130.4s

  [7691/17668] intraday_16082.csv.gz  in=304,245,569 out=85,698,520 elapsed=130.4s

  [7692/17668] intraday_16084.csv.gz  in=304,256,953 out=85,709,904 elapsed=130.4s

  [7693/17668] intraday_16083.csv.gz  in=304,268,090 out=85,721,041 elapsed=130.5s

  [7694/17668] intraday_16085.csv.gz  in=304,281,123 out=85,734,074 elapsed=130.5s

  [7695/17668] intraday_16086.csv.gz  in=304,293,203 out=85,746,154 elapsed=130.5s

  [7696/17668] intraday_16087.csv.gz  in=304,304,669 out=85,757,620 elapsed=130.5s

  [7697/17668] intraday_16088.csv.gz  in=304,315,638 out=85,768,589 elapsed=130.5s

  [7698/17668] intraday_16089.csv.gz  in=304,328,777 out=85,781,728 elapsed=130.5s

  [7699/17668] intraday_1609.csv.gz  in=304,341,894 out=85,781,728 elapsed=130.5s

  [7700/17668] intraday_16090.csv.gz  in=304,353,466 out=85,793,300 elapsed=130.5s

  [7701/17668] intraday_16091.csv.gz  in=304,365,156 out=85,804,990 elapsed=130.5s

  [7702/17668] intraday_16093.csv.gz  in=304,378,765 out=85,818,599 elapsed=130.6s

  [7703/17668] intraday_16092.csv.gz  in=304,390,886 out=85,830,720 elapsed=130.6s

  [7704/17668] intraday_16094.csv.gz  in=304,402,375 out=85,842,209 elapsed=130.6s

  [7705/17668] intraday_16098.csv.gz  in=304,414,941 out=85,854,775 elapsed=130.6s

  [7706/17668] intraday_16096.csv.gz  in=304,427,637 out=85,867,471 elapsed=130.6s

  [7707/17668] intraday_16095.csv.gz  in=304,442,351 out=85,882,185 elapsed=130.6s

  [7708/17668] intraday_16097.csv.gz  in=304,456,555 out=85,896,389 elapsed=130.6s

  [7709/17668] intraday_1610.csv.gz  in=304,469,454 out=85,896,389 elapsed=130.6s

  [7710/17668] intraday_16099.csv.gz  in=304,488,755 out=85,915,690 elapsed=130.6s

  [7711/17668] intraday_16100.csv.gz  in=304,503,290 out=85,930,225 elapsed=130.7s

  [7712/17668] intraday_16101.csv.gz  in=304,519,224 out=85,946,159 elapsed=130.7s

  [7713/17668] intraday_16102.csv.gz  in=304,530,516 out=85,957,451 elapsed=130.7s

  [7714/17668] intraday_16103.csv.gz  in=304,545,308 out=85,972,243 elapsed=130.7s

  [7715/17668] intraday_16104.csv.gz  in=304,557,717 out=85,984,652 elapsed=130.7s

  [7716/17668] intraday_16105.csv.gz  in=304,567,574 out=85,994,509 elapsed=130.7s

  [7717/17668] intraday_16107.csv.gz  in=304,579,868 out=86,006,803 elapsed=130.7s

  [7718/17668] intraday_16106.csv.gz  in=304,591,927 out=86,018,862 elapsed=130.7s

  [7719/17668] intraday_16108.csv.gz  in=304,603,735 out=86,030,670 elapsed=130.7s

  [7720/17668] intraday_16109.csv.gz  in=304,617,249 out=86,044,184 elapsed=130.8s

  [7721/17668] intraday_1611.csv.gz  in=304,628,913 out=86,044,184 elapsed=130.8s

  [7722/17668] intraday_16110.csv.gz  in=304,642,114 out=86,057,381 elapsed=130.8s

  [7723/17668] intraday_16111.csv.gz  in=304,653,381 out=86,068,648 elapsed=130.8s

  [7724/17668] intraday_16112.csv.gz  in=304,664,579 out=86,079,846 elapsed=130.8s

  [7725/17668] intraday_16113.csv.gz  in=304,678,062 out=86,093,329 elapsed=130.8s

  [7726/17668] intraday_16114.csv.gz  in=304,690,972 out=86,106,239 elapsed=130.8s

  [7727/17668] intraday_16115.csv.gz  in=304,702,470 out=86,117,737 elapsed=130.8s

  [7728/17668] intraday_16116.csv.gz  in=304,716,858 out=86,132,125 elapsed=130.9s

  [7729/17668] intraday_16118.csv.gz  in=304,729,114 out=86,144,381 elapsed=130.9s

  [7730/17668] intraday_16117.csv.gz  in=304,756,155 out=86,169,848 elapsed=130.9s

  [7731/17668] intraday_16119.csv.gz  in=304,769,238 out=86,182,931 elapsed=130.9s

  [7732/17668] intraday_1612.csv.gz  in=304,780,340 out=86,182,931 elapsed=130.9s

  [7733/17668] intraday_16120.csv.gz  in=304,792,004 out=86,194,595 elapsed=130.9s

  [7734/17668] intraday_16122.csv.gz  in=304,802,443 out=86,205,034 elapsed=130.9s

  [7735/17668] intraday_16121.csv.gz  in=304,815,799 out=86,218,390 elapsed=131.0s

  [7736/17668] intraday_16124.csv.gz  in=304,826,518 out=86,229,109 elapsed=131.0s

  [7737/17668] intraday_16123.csv.gz  in=304,838,372 out=86,240,963 elapsed=131.0s

  [7738/17668] intraday_16125.csv.gz  in=304,848,071 out=86,250,470 elapsed=131.0s

  [7739/17668] intraday_16126.csv.gz  in=304,858,825 out=86,261,224 elapsed=131.0s

  [7740/17668] intraday_16127.csv.gz  in=304,862,533 out=86,264,932 elapsed=131.0s

  [7741/17668] intraday_16128.csv.gz  in=304,878,591 out=86,280,990 elapsed=131.0s

  [7742/17668] intraday_16129.csv.gz  in=304,893,053 out=86,295,452 elapsed=131.0s

  [7743/17668] intraday_16130.csv.gz  in=304,907,097 out=86,309,496 elapsed=131.0s

  [7744/17668] intraday_16131.csv.gz  in=304,918,872 out=86,321,271 elapsed=131.0s

  [7745/17668] intraday_1613.csv.gz  in=304,934,182 out=86,321,271 elapsed=131.0s

  [7746/17668] intraday_16132.csv.gz  in=304,947,274 out=86,334,363 elapsed=131.0s

  [7747/17668] intraday_16133.csv.gz  in=304,961,669 out=86,348,758 elapsed=131.1s

  [7748/17668] intraday_16135.csv.gz  in=304,973,831 out=86,360,920 elapsed=131.1s

  [7749/17668] intraday_16134.csv.gz  in=304,986,777 out=86,373,866 elapsed=131.1s

  [7750/17668] intraday_16136.csv.gz  in=304,999,367 out=86,386,456 elapsed=131.1s

  [7751/17668] intraday_16138.csv.gz  in=305,009,426 out=86,396,515 elapsed=131.2s

  [7752/17668] intraday_16137.csv.gz  in=305,022,957 out=86,410,046 elapsed=131.2s

  [7753/17668] intraday_16139.csv.gz  in=305,036,558 out=86,423,647 elapsed=131.2s

  [7754/17668] intraday_1614.csv.gz  in=305,050,850 out=86,423,647 elapsed=131.2s

  [7755/17668] intraday_16140.csv.gz  in=305,065,378 out=86,438,175 elapsed=131.2s

  [7756/17668] intraday_16141.csv.gz  in=305,077,181 out=86,449,978 elapsed=131.2s

  [7757/17668] intraday_16142.csv.gz  in=305,088,369 out=86,461,166 elapsed=131.2s

  [7758/17668] intraday_16143.csv.gz  in=305,099,607 out=86,472,404 elapsed=131.2s

  [7759/17668] intraday_16144.csv.gz  in=305,114,382 out=86,487,179 elapsed=131.3s

  [7760/17668] intraday_16145.csv.gz  in=305,129,199 out=86,501,996 elapsed=131.3s

  [7761/17668] intraday_16147.csv.gz  in=305,140,106 out=86,512,903 elapsed=131.3s

  [7762/17668] intraday_16146.csv.gz  in=305,151,142 out=86,523,939 elapsed=131.3s

  [7763/17668] intraday_16148.csv.gz  in=305,163,680 out=86,536,477 elapsed=131.3s

  [7764/17668] intraday_16149.csv.gz  in=305,175,893 out=86,548,690 elapsed=131.3s

  [7765/17668] intraday_1615.csv.gz  in=305,187,270 out=86,548,690 elapsed=131.3s

  [7766/17668] intraday_16151.csv.gz  in=305,200,007 out=86,561,427 elapsed=131.4s

  [7767/17668] intraday_16150.csv.gz  in=305,212,954 out=86,574,374 elapsed=131.4s

  [7768/17668] intraday_16153.csv.gz  in=305,224,143 out=86,585,563 elapsed=131.4s

  [7769/17668] intraday_16152.csv.gz  in=305,236,058 out=86,597,478 elapsed=131.4s

  [7770/17668] intraday_16155.csv.gz  in=305,247,052 out=86,608,472 elapsed=131.4s

  [7771/17668] intraday_16154.csv.gz  in=305,258,925 out=86,620,345 elapsed=131.4s

  [7772/17668] intraday_16157.csv.gz  in=305,273,285 out=86,634,705 elapsed=131.4s

  [7773/17668] intraday_16156.csv.gz  in=305,288,420 out=86,649,840 elapsed=131.5s

  [7774/17668] intraday_16159.csv.gz  in=305,300,237 out=86,661,657 elapsed=131.5s

  [7775/17668] intraday_16158.csv.gz  in=305,316,593 out=86,678,013 elapsed=131.5s

  [7776/17668] intraday_1616.csv.gz  in=305,328,884 out=86,678,013 elapsed=131.5s

  [7777/17668] intraday_16160.csv.gz  in=305,339,788 out=86,688,917 elapsed=131.5s

  [7778/17668] intraday_16161.csv.gz  in=305,352,928 out=86,702,057 elapsed=131.5s

  [7779/17668] intraday_16162.csv.gz  in=305,366,006 out=86,715,135 elapsed=131.5s

  [7780/17668] intraday_16163.csv.gz  in=305,378,428 out=86,727,557 elapsed=131.6s

  [7781/17668] intraday_16164.csv.gz  in=305,391,637 out=86,740,766 elapsed=131.6s

  [7782/17668] intraday_16165.csv.gz  in=305,402,950 out=86,752,079 elapsed=131.6s

  [7783/17668] intraday_16166.csv.gz  in=305,413,412 out=86,762,541 elapsed=131.6s

  [7784/17668] intraday_16167.csv.gz  in=305,424,065 out=86,773,194 elapsed=131.6s

  [7785/17668] intraday_16168.csv.gz  in=305,436,001 out=86,785,130 elapsed=131.6s

  [7786/17668] intraday_16169.csv.gz  in=305,448,142 out=86,797,271 elapsed=131.6s

  [7787/17668] intraday_1617.csv.gz  in=305,460,388 out=86,797,271 elapsed=131.6s

  [7788/17668] intraday_16170.csv.gz  in=305,475,233 out=86,812,116 elapsed=131.7s

  [7789/17668] intraday_16171.csv.gz  in=305,488,671 out=86,825,554 elapsed=131.7s

  [7790/17668] intraday_16172.csv.gz  in=305,501,101 out=86,837,984 elapsed=131.7s

  [7791/17668] intraday_16173.csv.gz  in=305,512,410 out=86,849,293 elapsed=131.7s

  [7792/17668] intraday_16174.csv.gz  in=305,524,626 out=86,861,509 elapsed=131.7s

  [7793/17668] intraday_16175.csv.gz  in=305,536,566 out=86,873,449 elapsed=131.7s

  [7794/17668] intraday_16176.csv.gz  in=305,548,078 out=86,884,961 elapsed=131.7s

  [7795/17668] intraday_16178.csv.gz  in=305,558,126 out=86,895,009 elapsed=131.7s

  [7796/17668] intraday_16177.csv.gz  in=305,571,101 out=86,907,984 elapsed=131.7s

  [7797/17668] intraday_1618.csv.gz  in=305,583,268 out=86,907,984 elapsed=131.7s

  [7798/17668] intraday_16179.csv.gz  in=305,597,632 out=86,922,348 elapsed=131.8s

  [7799/17668] intraday_16180.csv.gz  in=305,608,961 out=86,933,677 elapsed=131.8s

  [7800/17668] intraday_16181.csv.gz  in=305,621,352 out=86,946,068 elapsed=131.8s

  [7801/17668] intraday_16182.csv.gz  in=305,635,753 out=86,960,469 elapsed=131.8s

  [7802/17668] intraday_16183.csv.gz  in=305,648,148 out=86,972,864 elapsed=131.8s

  [7803/17668] intraday_16184.csv.gz  in=305,659,865 out=86,984,581 elapsed=131.8s

  [7804/17668] intraday_16185.csv.gz  in=305,671,494 out=86,996,210 elapsed=131.8s

  [7805/17668] intraday_16186.csv.gz  in=305,685,579 out=87,010,295 elapsed=131.9s

  [7806/17668] intraday_16187.csv.gz  in=305,697,695 out=87,022,411 elapsed=131.9s

  [7807/17668] intraday_16189.csv.gz  in=305,707,341 out=87,032,057 elapsed=131.9s

  [7808/17668] intraday_1619.csv.gz  in=305,719,783 out=87,032,057 elapsed=131.9s

  [7809/17668] intraday_16188.csv.gz  in=305,733,320 out=87,045,594 elapsed=131.9s

  [7810/17668] intraday_16190.csv.gz  in=305,745,558 out=87,057,832 elapsed=131.9s

  [7811/17668] intraday_16191.csv.gz  in=305,756,296 out=87,068,570 elapsed=131.9s

  [7812/17668] intraday_16192.csv.gz  in=305,769,823 out=87,082,097 elapsed=131.9s

  [7813/17668] intraday_16193.csv.gz  in=305,782,773 out=87,095,047 elapsed=132.0s

  [7814/17668] intraday_16194.csv.gz  in=305,796,583 out=87,108,857 elapsed=132.0s

  [7815/17668] intraday_16195.csv.gz  in=305,808,722 out=87,120,996 elapsed=132.0s

  [7816/17668] intraday_16196.csv.gz  in=305,820,914 out=87,133,188 elapsed=132.0s

  [7817/17668] intraday_16197.csv.gz  in=305,828,935 out=87,141,209 elapsed=132.0s

  [7818/17668] intraday_16198.csv.gz  in=305,841,587 out=87,153,861 elapsed=132.0s

  [7819/17668] intraday_1620.csv.gz  in=305,853,833 out=87,153,861 elapsed=132.1s

  [7820/17668] intraday_16200.csv.gz  in=305,865,928 out=87,165,956 elapsed=132.1s

  [7821/17668] intraday_16199.csv.gz  in=305,879,190 out=87,179,218 elapsed=132.1s

  [7822/17668] intraday_16201.csv.gz  in=305,889,034 out=87,189,062 elapsed=132.1s

  [7823/17668] intraday_16202.csv.gz  in=305,901,667 out=87,201,695 elapsed=132.1s

  [7824/17668] intraday_16203.csv.gz  in=305,910,590 out=87,210,618 elapsed=132.1s

  [7825/17668] intraday_16204.csv.gz  in=305,923,003 out=87,223,031 elapsed=132.1s

  [7826/17668] intraday_16205.csv.gz  in=305,936,516 out=87,236,544 elapsed=132.1s

  [7827/17668] intraday_16206.csv.gz  in=305,948,427 out=87,248,455 elapsed=132.1s

  [7828/17668] intraday_16207.csv.gz  in=305,960,086 out=87,260,114 elapsed=132.2s

  [7829/17668] intraday_16208.csv.gz  in=305,969,938 out=87,269,966 elapsed=132.2s

  [7830/17668] intraday_16209.csv.gz  in=305,980,968 out=87,280,996 elapsed=132.2s

  [7831/17668] intraday_1621.csv.gz  in=305,994,135 out=87,280,996 elapsed=132.2s

  [7832/17668] intraday_16210.csv.gz  in=306,007,165 out=87,294,026 elapsed=132.2s

  [7833/17668] intraday_16212.csv.gz  in=306,021,497 out=87,308,358 elapsed=132.2s

  [7834/17668] intraday_16213.csv.gz  in=306,035,481 out=87,322,342 elapsed=132.2s

  [7835/17668] intraday_16211.csv.gz  in=306,052,864 out=87,339,725 elapsed=132.3s

  [7836/17668] intraday_16214.csv.gz  in=306,064,537 out=87,351,398 elapsed=132.3s

  [7837/17668] intraday_16216.csv.gz  in=306,075,421 out=87,362,282 elapsed=132.3s

  [7838/17668] intraday_16218.csv.gz  in=306,085,641 out=87,372,502 elapsed=132.3s

  [7839/17668] intraday_16215.csv.gz  in=306,099,827 out=87,386,688 elapsed=132.3s

  [7840/17668] intraday_16217.csv.gz  in=306,115,183 out=87,402,044 elapsed=132.3s

  [7841/17668] intraday_16219.csv.gz  in=306,128,252 out=87,415,113 elapsed=132.3s

  [7842/17668] intraday_1622.csv.gz  in=306,141,246 out=87,415,113 elapsed=132.3s

  [7843/17668] intraday_16220.csv.gz  in=306,152,870 out=87,426,737 elapsed=132.3s

  [7844/17668] intraday_16221.csv.gz  in=306,166,269 out=87,440,136 elapsed=132.4s

  [7845/17668] intraday_16223.csv.gz  in=306,179,014 out=87,452,881 elapsed=132.4s

  [7846/17668] intraday_16224.csv.gz  in=306,193,357 out=87,467,224 elapsed=132.4s

  [7847/17668] intraday_16222.csv.gz  in=306,206,042 out=87,479,909 elapsed=132.4s

  [7848/17668] intraday_16225.csv.gz  in=306,216,329 out=87,490,196 elapsed=132.4s

  [7849/17668] intraday_16226.csv.gz  in=306,228,025 out=87,501,892 elapsed=132.4s

  [7850/17668] intraday_16227.csv.gz  in=306,240,696 out=87,514,563 elapsed=132.4s

  [7851/17668] intraday_16228.csv.gz  in=306,252,964 out=87,526,831 elapsed=132.5s

  [7852/17668] intraday_16229.csv.gz  in=306,265,928 out=87,539,795 elapsed=132.5s

  [7853/17668] intraday_1623.csv.gz  in=306,280,598 out=87,539,795 elapsed=132.5s

  [7854/17668] intraday_16230.csv.gz  in=306,294,335 out=87,553,532 elapsed=132.5s

  [7855/17668] intraday_16231.csv.gz  in=306,308,026 out=87,567,223 elapsed=132.5s

  [7856/17668] intraday_16233.csv.gz  in=306,321,288 out=87,580,485 elapsed=132.5s

  [7857/17668] intraday_16232.csv.gz  in=306,332,027 out=87,591,224 elapsed=132.5s

  [7858/17668] intraday_16234.csv.gz  in=306,343,656 out=87,602,853 elapsed=132.5s

  [7859/17668] intraday_16235.csv.gz  in=306,356,251 out=87,615,448 elapsed=132.6s

  [7860/17668] intraday_16236.csv.gz  in=306,370,161 out=87,629,358 elapsed=132.6s

  [7861/17668] intraday_16238.csv.gz  in=306,383,597 out=87,642,794 elapsed=132.6s

  [7862/17668] intraday_16237.csv.gz  in=306,396,755 out=87,655,952 elapsed=132.6s

  [7863/17668] intraday_16239.csv.gz  in=306,408,594 out=87,667,791 elapsed=132.6s

  [7864/17668] intraday_1624.csv.gz  in=306,420,044 out=87,667,791 elapsed=132.6s

  [7865/17668] intraday_16240.csv.gz  in=306,434,294 out=87,682,041 elapsed=132.7s

  [7866/17668] intraday_16241.csv.gz  in=306,449,034 out=87,696,781 elapsed=132.7s

  [7867/17668] intraday_16243.csv.gz  in=306,463,837 out=87,711,584 elapsed=132.7s

  [7868/17668] intraday_16244.csv.gz  in=306,483,615 out=87,731,362 elapsed=132.7s

  [7869/17668] intraday_16242.csv.gz  in=306,498,249 out=87,745,996 elapsed=132.7s

  [7870/17668] intraday_16245.csv.gz  in=306,510,245 out=87,757,992 elapsed=132.7s

  [7871/17668] intraday_16246.csv.gz  in=306,526,980 out=87,774,727 elapsed=132.7s

  [7872/17668] intraday_16247.csv.gz  in=306,538,835 out=87,786,582 elapsed=132.7s

  [7873/17668] intraday_16249.csv.gz  in=306,549,702 out=87,797,449 elapsed=132.7s

  [7874/17668] intraday_16248.csv.gz  in=306,564,449 out=87,812,196 elapsed=132.8s

  [7875/17668] intraday_1625.csv.gz  in=306,578,724 out=87,812,196 elapsed=132.8s

  [7876/17668] intraday_16250.csv.gz  in=306,591,228 out=87,824,700 elapsed=132.8s

  [7877/17668] intraday_16251.csv.gz  in=306,602,042 out=87,835,514 elapsed=132.8s

  [7878/17668] intraday_16253.csv.gz  in=306,613,385 out=87,846,857 elapsed=132.8s

  [7879/17668] intraday_16252.csv.gz  in=306,628,306 out=87,861,778 elapsed=132.8s

  [7880/17668] intraday_16254.csv.gz  in=306,643,919 out=87,877,391 elapsed=132.8s

  [7881/17668] intraday_16255.csv.gz  in=306,654,662 out=87,888,134 elapsed=132.8s

  [7882/17668] intraday_16256.csv.gz  in=306,667,061 out=87,900,533 elapsed=132.9s

  [7883/17668] intraday_16257.csv.gz  in=306,677,684 out=87,911,156 elapsed=132.9s

  [7884/17668] intraday_16258.csv.gz  in=306,691,297 out=87,924,769 elapsed=132.9s

  [7885/17668] intraday_16259.csv.gz  in=306,704,400 out=87,937,872 elapsed=132.9s

  [7886/17668] intraday_1626.csv.gz  in=306,717,996 out=87,937,872 elapsed=132.9s

  [7887/17668] intraday_16260.csv.gz  in=306,732,960 out=87,952,836 elapsed=132.9s

  [7888/17668] intraday_16261.csv.gz  in=306,746,842 out=87,966,718 elapsed=132.9s

  [7889/17668] intraday_16264.csv.gz  in=306,758,844 out=87,978,720 elapsed=133.0s

  [7890/17668] intraday_16265.csv.gz  in=306,770,867 out=87,990,743 elapsed=133.0s

  [7891/17668] intraday_16262.csv.gz  in=306,785,058 out=88,004,934 elapsed=133.0s

  [7892/17668] intraday_16263.csv.gz  in=306,800,318 out=88,020,194 elapsed=133.0s

  [7893/17668] intraday_16266.csv.gz  in=306,813,265 out=88,033,141 elapsed=133.0s

  [7894/17668] intraday_16267.csv.gz  in=306,822,913 out=88,042,789 elapsed=133.0s

  [7895/17668] intraday_16268.csv.gz  in=306,836,270 out=88,056,146 elapsed=133.0s

  [7896/17668] intraday_16269.csv.gz  in=306,845,814 out=88,065,690 elapsed=133.0s

  [7897/17668] intraday_16270.csv.gz  in=306,854,289 out=88,074,165 elapsed=133.1s

  [7898/17668] intraday_1627.csv.gz  in=306,871,678 out=88,074,165 elapsed=133.1s

  [7899/17668] intraday_16271.csv.gz  in=306,882,502 out=88,084,989 elapsed=133.1s

  [7900/17668] intraday_16272.csv.gz  in=306,897,747 out=88,100,234 elapsed=133.1s

  [7901/17668] intraday_16274.csv.gz  in=306,910,867 out=88,113,354 elapsed=133.1s

  [7902/17668] intraday_16273.csv.gz  in=306,924,861 out=88,127,348 elapsed=133.1s

  [7903/17668] intraday_16275.csv.gz  in=306,935,594 out=88,138,081 elapsed=133.1s

  [7904/17668] intraday_16276.csv.gz  in=306,947,791 out=88,150,278 elapsed=133.1s

  [7905/17668] intraday_16277.csv.gz  in=306,961,007 out=88,163,494 elapsed=133.1s

  [7906/17668] intraday_16278.csv.gz  in=306,973,381 out=88,175,868 elapsed=133.2s

  [7907/17668] intraday_16279.csv.gz  in=306,984,877 out=88,187,364 elapsed=133.2s

  [7908/17668] intraday_1628.csv.gz  in=306,996,105 out=88,187,364 elapsed=133.2s

  [7909/17668] intraday_16280.csv.gz  in=307,007,957 out=88,199,216 elapsed=133.2s

  [7910/17668] intraday_16283.csv.gz  in=307,011,312 out=88,202,571 elapsed=133.2s

  [7911/17668] intraday_16282.csv.gz  in=307,020,729 out=88,211,988 elapsed=133.2s

  [7912/17668] intraday_16281.csv.gz  in=307,034,028 out=88,225,287 elapsed=133.2s

  [7913/17668] intraday_16284.csv.gz  in=307,041,673 out=88,232,932 elapsed=133.2s

  [7914/17668] intraday_16285.csv.gz  in=307,056,556 out=88,247,815 elapsed=133.3s

  [7915/17668] intraday_16286.csv.gz  in=307,070,230 out=88,261,489 elapsed=133.3s

  [7916/17668] intraday_16288.csv.gz  in=307,080,591 out=88,271,850 elapsed=133.3s

  [7917/17668] intraday_16287.csv.gz  in=307,093,365 out=88,284,624 elapsed=133.3s

  [7918/17668] intraday_1629.csv.gz  in=307,106,772 out=88,284,624 elapsed=133.3s

  [7919/17668] intraday_16289.csv.gz  in=307,119,756 out=88,297,608 elapsed=133.3s

  [7920/17668] intraday_16291.csv.gz  in=307,134,250 out=88,311,819 elapsed=133.3s

  [7921/17668] intraday_16290.csv.gz  in=307,146,882 out=88,324,451 elapsed=133.3s

  [7922/17668] intraday_16292.csv.gz  in=307,159,559 out=88,337,128 elapsed=133.3s

  [7923/17668] intraday_16293.csv.gz  in=307,172,747 out=88,350,260 elapsed=133.3s

  [7924/17668] intraday_16294.csv.gz  in=307,184,675 out=88,362,188 elapsed=133.4s

  [7925/17668] intraday_16296.csv.gz  in=307,196,633 out=88,374,146 elapsed=133.4s

  [7926/17668] intraday_16295.csv.gz  in=307,206,837 out=88,384,350 elapsed=133.4s

  [7927/17668] intraday_16297.csv.gz  in=307,219,590 out=88,397,103 elapsed=133.4s

  [7928/17668] intraday_16298.csv.gz  in=307,231,744 out=88,409,257 elapsed=133.4s

  [7929/17668] intraday_16299.csv.gz  in=307,247,211 out=88,424,724 elapsed=133.4s

  [7930/17668] intraday_1630.csv.gz  in=307,263,200 out=88,424,724 elapsed=133.4s

  [7931/17668] intraday_16300.csv.gz  in=307,277,684 out=88,439,208 elapsed=133.4s

  [7932/17668] intraday_16302.csv.gz  in=307,279,294 out=88,440,818 elapsed=133.4s

  [7933/17668] intraday_16301.csv.gz  in=307,290,198 out=88,451,722 elapsed=133.5s

  [7934/17668] intraday_16303.csv.gz  in=307,290,668 out=88,452,192 elapsed=133.5s

  [7935/17668] intraday_16304.csv.gz  in=307,300,360 out=88,461,884 elapsed=133.5s

  [7936/17668] intraday_16305.csv.gz  in=307,311,450 out=88,472,974 elapsed=133.5s

  [7937/17668] intraday_16306.csv.gz  in=307,321,348 out=88,482,872 elapsed=133.5s

  [7938/17668] intraday_16308.csv.gz  in=307,333,575 out=88,495,099 elapsed=133.5s

  [7939/17668] intraday_16307.csv.gz  in=307,345,606 out=88,507,130 elapsed=133.5s

  [7940/17668] intraday_16309.csv.gz  in=307,360,588 out=88,522,112 elapsed=133.5s

  [7941/17668] intraday_1631.csv.gz  in=307,373,327 out=88,522,112 elapsed=133.5s

  [7942/17668] intraday_16310.csv.gz  in=307,384,414 out=88,533,199 elapsed=133.5s

  [7943/17668] intraday_16311.csv.gz  in=307,398,808 out=88,547,593 elapsed=133.6s

  [7944/17668] intraday_16312.csv.gz  in=307,409,220 out=88,558,005 elapsed=133.6s

  [7945/17668] intraday_16313.csv.gz  in=307,421,311 out=88,570,096 elapsed=133.6s

  [7946/17668] intraday_16314.csv.gz  in=307,432,559 out=88,581,344 elapsed=133.6s

  [7947/17668] intraday_16315.csv.gz  in=307,444,272 out=88,593,057 elapsed=133.6s

  [7948/17668] intraday_16316.csv.gz  in=307,456,958 out=88,605,743 elapsed=133.6s

  [7949/17668] intraday_16317.csv.gz  in=307,467,498 out=88,616,283 elapsed=133.6s

  [7950/17668] intraday_16318.csv.gz  in=307,477,415 out=88,626,200 elapsed=133.6s

  [7951/17668] intraday_16319.csv.gz  in=307,483,177 out=88,631,962 elapsed=133.7s

  [7952/17668] intraday_1632.csv.gz  in=307,496,220 out=88,631,962 elapsed=133.7s

  [7953/17668] intraday_16320.csv.gz  in=307,508,506 out=88,644,248 elapsed=133.7s

  [7954/17668] intraday_16321.csv.gz  in=307,520,363 out=88,656,105 elapsed=133.7s

  [7955/17668] intraday_16323.csv.gz  in=307,533,639 out=88,669,381 elapsed=133.7s

  [7956/17668] intraday_16322.csv.gz  in=307,544,304 out=88,680,046 elapsed=133.7s

  [7957/17668] intraday_16325.csv.gz  in=307,556,400 out=88,692,142 elapsed=133.7s

  [7958/17668] intraday_16324.csv.gz  in=307,569,445 out=88,705,187 elapsed=133.7s

  [7959/17668] intraday_16327.csv.gz  in=307,581,623 out=88,717,365 elapsed=133.8s

  [7960/17668] intraday_16326.csv.gz  in=307,592,108 out=88,727,850 elapsed=133.8s

  [7961/17668] intraday_16328.csv.gz  in=307,607,108 out=88,742,219 elapsed=133.8s

  [7962/17668] intraday_1633.csv.gz  in=307,621,981 out=88,742,219 elapsed=133.8s

  [7963/17668] intraday_16329.csv.gz  in=307,635,103 out=88,755,341 elapsed=133.8s

  [7964/17668] intraday_16330.csv.gz  in=307,648,833 out=88,769,071 elapsed=133.8s

  [7965/17668] intraday_16331.csv.gz  in=307,660,060 out=88,780,298 elapsed=133.8s

  [7966/17668] intraday_16332.csv.gz  in=307,673,495 out=88,793,733 elapsed=133.8s

  [7967/17668] intraday_16334.csv.gz  in=307,674,811 out=88,795,049 elapsed=133.8s

  [7968/17668] intraday_16333.csv.gz  in=307,688,623 out=88,808,861 elapsed=133.8s

  [7969/17668] intraday_16335.csv.gz  in=307,700,282 out=88,820,520 elapsed=133.9s

  [7970/17668] intraday_16337.csv.gz  in=307,710,878 out=88,831,116 elapsed=133.9s

  [7971/17668] intraday_16336.csv.gz  in=307,722,983 out=88,843,221 elapsed=133.9s

  [7972/17668] intraday_16338.csv.gz  in=307,732,539 out=88,852,777 elapsed=133.9s

  [7973/17668] intraday_1634.csv.gz  in=307,743,180 out=88,852,777 elapsed=133.9s

  [7974/17668] intraday_16339.csv.gz  in=307,754,419 out=88,864,016 elapsed=133.9s

  [7975/17668] intraday_16340.csv.gz  in=307,767,974 out=88,877,571 elapsed=133.9s

  [7976/17668] intraday_16341.csv.gz  in=307,779,294 out=88,888,891 elapsed=134.0s

  [7977/17668] intraday_16342.csv.gz  in=307,792,223 out=88,901,820 elapsed=134.0s

  [7978/17668] intraday_16343.csv.gz  in=307,801,738 out=88,911,335 elapsed=134.0s

  [7979/17668] intraday_16344.csv.gz  in=307,813,308 out=88,922,905 elapsed=134.0s

  [7980/17668] intraday_16345.csv.gz  in=307,824,885 out=88,934,482 elapsed=134.0s

  [7981/17668] intraday_16346.csv.gz  in=307,840,520 out=88,950,117 elapsed=134.0s

  [7982/17668] intraday_16347.csv.gz  in=307,854,713 out=88,964,310 elapsed=134.0s

  [7983/17668] intraday_16349.csv.gz  in=307,867,363 out=88,976,960 elapsed=134.0s

  [7984/17668] intraday_16348.csv.gz  in=307,882,193 out=88,991,790 elapsed=134.0s

  [7985/17668] intraday_1635.csv.gz  in=307,894,116 out=88,991,790 elapsed=134.1s

  [7986/17668] intraday_16350.csv.gz  in=307,908,402 out=89,006,076 elapsed=134.1s

  [7987/17668] intraday_16351.csv.gz  in=307,919,125 out=89,016,799 elapsed=134.1s

  [7988/17668] intraday_16352.csv.gz  in=307,932,980 out=89,030,654 elapsed=134.1s

  [7989/17668] intraday_16353.csv.gz  in=307,943,170 out=89,040,844 elapsed=134.1s

  [7990/17668] intraday_16354.csv.gz  in=307,954,536 out=89,052,210 elapsed=134.1s

  [7991/17668] intraday_16355.csv.gz  in=307,966,408 out=89,064,082 elapsed=134.1s

  [7992/17668] intraday_16356.csv.gz  in=307,971,177 out=89,068,851 elapsed=134.1s

  [7993/17668] intraday_16357.csv.gz  in=307,978,228 out=89,075,902 elapsed=134.2s

  [7994/17668] intraday_16358.csv.gz  in=307,988,959 out=89,086,633 elapsed=134.2s

  [7995/17668] intraday_1636.csv.gz  in=308,001,505 out=89,086,633 elapsed=134.2s

  [7996/17668] intraday_16359.csv.gz  in=308,013,549 out=89,098,677 elapsed=134.2s

  [7997/17668] intraday_16360.csv.gz  in=308,024,829 out=89,109,957 elapsed=134.2s

  [7998/17668] intraday_16361.csv.gz  in=308,044,785 out=89,128,565 elapsed=134.2s

  [7999/17668] intraday_16362.csv.gz  in=308,057,212 out=89,140,992 elapsed=134.2s

  [8000/17668] intraday_16363.csv.gz  in=308,069,467 out=89,153,247 elapsed=134.2s

  [8001/17668] intraday_16364.csv.gz  in=308,082,086 out=89,165,866 elapsed=134.2s

  [8002/17668] intraday_16366.csv.gz  in=308,094,092 out=89,177,872 elapsed=134.2s

  [8003/17668] intraday_16365.csv.gz  in=308,106,235 out=89,190,015 elapsed=134.2s

  [8004/17668] intraday_16368.csv.gz  in=308,117,106 out=89,200,886 elapsed=134.3s

  [8005/17668] intraday_16369.csv.gz  in=308,128,672 out=89,212,452 elapsed=134.3s

  [8006/17668] intraday_16367.csv.gz  in=308,144,904 out=89,228,684 elapsed=134.3s

  [8007/17668] intraday_1637.csv.gz  in=308,159,104 out=89,228,684 elapsed=134.3s

  [8008/17668] intraday_16370.csv.gz  in=308,171,777 out=89,241,357 elapsed=134.3s

  [8009/17668] intraday_16372.csv.gz  in=308,183,154 out=89,252,734 elapsed=134.3s

  [8010/17668] intraday_16371.csv.gz  in=308,198,291 out=89,267,871 elapsed=134.3s

  [8011/17668] intraday_16374.csv.gz  in=308,211,359 out=89,280,939 elapsed=134.4s

  [8012/17668] intraday_16373.csv.gz  in=308,224,587 out=89,294,167 elapsed=134.4s

  [8013/17668] intraday_16375.csv.gz  in=308,237,267 out=89,306,847 elapsed=134.4s

  [8014/17668] intraday_16376.csv.gz  in=308,250,030 out=89,319,610 elapsed=134.4s

  [8015/17668] intraday_16377.csv.gz  in=308,268,010 out=89,337,590 elapsed=134.4s

  [8016/17668] intraday_16379.csv.gz  in=308,283,380 out=89,352,960 elapsed=134.4s

  [8017/17668] intraday_16378.csv.gz  in=308,301,435 out=89,370,725 elapsed=134.4s

  [8018/17668] intraday_1638.csv.gz  in=308,317,016 out=89,370,725 elapsed=134.4s

  [8019/17668] intraday_16380.csv.gz  in=308,333,166 out=89,386,875 elapsed=134.5s

  [8020/17668] intraday_16381.csv.gz  in=308,345,870 out=89,399,579 elapsed=134.5s

  [8021/17668] intraday_16383.csv.gz  in=308,355,746 out=89,409,455 elapsed=134.5s

  [8022/17668] intraday_16385.csv.gz  in=308,367,051 out=89,420,760 elapsed=134.5s

  [8023/17668] intraday_16382.csv.gz  in=308,380,540 out=89,434,249 elapsed=134.5s

  [8024/17668] intraday_16384.csv.gz  in=308,393,137 out=89,446,846 elapsed=134.5s

  [8025/17668] intraday_16386.csv.gz  in=308,405,817 out=89,459,526 elapsed=134.5s

  [8026/17668] intraday_16387.csv.gz  in=308,419,794 out=89,473,503 elapsed=134.5s

  [8027/17668] intraday_16389.csv.gz  in=308,429,795 out=89,483,504 elapsed=134.5s

  [8028/17668] intraday_16388.csv.gz  in=308,443,088 out=89,496,797 elapsed=134.6s

  [8029/17668] intraday_1639.csv.gz  in=308,456,316 out=89,496,797 elapsed=134.6s

  [8030/17668] intraday_16390.csv.gz  in=308,467,966 out=89,508,447 elapsed=134.6s

  [8031/17668] intraday_16394.csv.gz  in=308,469,246 out=89,509,727 elapsed=134.6s

  [8032/17668] intraday_16391.csv.gz  in=308,481,813 out=89,522,294 elapsed=134.6s

  [8033/17668] intraday_16392.csv.gz  in=308,494,183 out=89,534,664 elapsed=134.6s

  [8034/17668] intraday_16393.csv.gz  in=308,505,850 out=89,546,331 elapsed=134.6s

  [8035/17668] intraday_16396.csv.gz  in=308,517,350 out=89,557,831 elapsed=134.7s

  [8036/17668] intraday_16398.csv.gz  in=308,529,404 out=89,569,885 elapsed=134.7s

  [8037/17668] intraday_16397.csv.gz  in=308,541,648 out=89,582,129 elapsed=134.7s

  [8038/17668] intraday_16395.csv.gz  in=308,555,955 out=89,596,436 elapsed=134.7s

  [8039/17668] intraday_16399.csv.gz  in=308,566,684 out=89,607,165 elapsed=134.7s

  [8040/17668] intraday_16400.csv.gz  in=308,578,680 out=89,619,161 elapsed=134.8s

  [8041/17668] intraday_16401.csv.gz  in=308,586,440 out=89,626,921 elapsed=134.8s

  [8042/17668] intraday_16402.csv.gz  in=308,596,319 out=89,636,800 elapsed=134.8s

  [8043/17668] intraday_1640.csv.gz  in=308,610,259 out=89,636,800 elapsed=134.8s

  [8044/17668] intraday_16404.csv.gz  in=308,625,988 out=89,652,529 elapsed=134.8s

  [8045/17668] intraday_16403.csv.gz  in=308,631,973 out=89,658,514 elapsed=134.8s

  [8046/17668] intraday_16405.csv.gz  in=308,646,202 out=89,672,743 elapsed=134.8s

  [8047/17668] intraday_16406.csv.gz  in=308,662,240 out=89,688,781 elapsed=134.8s

  [8048/17668] intraday_16407.csv.gz  in=308,672,650 out=89,699,191 elapsed=134.9s

  [8049/17668] intraday_16408.csv.gz  in=308,684,839 out=89,711,380 elapsed=134.9s

  [8050/17668] intraday_16409.csv.gz  in=308,699,853 out=89,726,394 elapsed=134.9s

  [8051/17668] intraday_1641.csv.gz  in=308,713,953 out=89,726,394 elapsed=134.9s

  [8052/17668] intraday_16410.csv.gz  in=308,724,587 out=89,737,028 elapsed=134.9s

  [8053/17668] intraday_16411.csv.gz  in=308,724,625 out=89,737,066 elapsed=134.9s

  [8054/17668] intraday_16412.csv.gz  in=308,728,634 out=89,741,075 elapsed=134.9s

  [8055/17668] intraday_16413.csv.gz  in=308,741,017 out=89,753,458 elapsed=134.9s

  [8056/17668] intraday_16415.csv.gz  in=308,753,244 out=89,765,685 elapsed=134.9s

  [8057/17668] intraday_16414.csv.gz  in=308,767,422 out=89,779,863 elapsed=135.0s

  [8058/17668] intraday_16417.csv.gz  in=308,780,058 out=89,792,499 elapsed=135.0s

  [8059/17668] intraday_16416.csv.gz  in=308,790,298 out=89,802,739 elapsed=135.0s

  [8060/17668] intraday_16419.csv.gz  in=308,803,896 out=89,816,337 elapsed=135.0s

  [8061/17668] intraday_16418.csv.gz  in=308,818,580 out=89,831,021 elapsed=135.0s

  [8062/17668] intraday_16420.csv.gz  in=308,829,492 out=89,841,933 elapsed=135.0s

  [8063/17668] intraday_1642.csv.gz  in=308,842,666 out=89,841,933 elapsed=135.0s

  [8064/17668] intraday_16421.csv.gz  in=308,853,260 out=89,852,527 elapsed=135.0s

  [8065/17668] intraday_16422.csv.gz  in=308,865,716 out=89,864,983 elapsed=135.1s

  [8066/17668] intraday_16423.csv.gz  in=308,878,680 out=89,877,947 elapsed=135.1s

  [8067/17668] intraday_16425.csv.gz  in=308,891,276 out=89,890,543 elapsed=135.1s

  [8068/17668] intraday_16424.csv.gz  in=308,903,961 out=89,903,228 elapsed=135.1s

  [8069/17668] intraday_16426.csv.gz  in=308,915,572 out=89,914,839 elapsed=135.1s

  [8070/17668] intraday_16427.csv.gz  in=308,927,018 out=89,926,285 elapsed=135.1s

  [8071/17668] intraday_16428.csv.gz  in=308,938,011 out=89,937,278 elapsed=135.1s

  [8072/17668] intraday_1643.csv.gz  in=308,950,415 out=89,937,278 elapsed=135.1s

  [8073/17668] intraday_16429.csv.gz  in=308,961,975 out=89,948,838 elapsed=135.2s

  [8074/17668] intraday_16431.csv.gz  in=308,971,147 out=89,958,010 elapsed=135.2s

  [8075/17668] intraday_16430.csv.gz  in=308,972,386 out=89,959,249 elapsed=135.2s

  [8076/17668] intraday_16432.csv.gz  in=308,984,960 out=89,971,823 elapsed=135.2s

  [8077/17668] intraday_16433.csv.gz  in=308,998,443 out=89,985,306 elapsed=135.2s

  [8078/17668] intraday_16435.csv.gz  in=309,010,999 out=89,997,862 elapsed=135.2s

  [8079/17668] intraday_16434.csv.gz  in=309,024,239 out=90,011,102 elapsed=135.2s

  [8080/17668] intraday_16437.csv.gz  in=309,035,072 out=90,021,935 elapsed=135.3s

  [8081/17668] intraday_16438.csv.gz  in=309,045,070 out=90,031,933 elapsed=135.3s

  [8082/17668] intraday_16436.csv.gz  in=309,070,141 out=90,054,925 elapsed=135.3s

  [8083/17668] intraday_16439.csv.gz  in=309,082,468 out=90,067,252 elapsed=135.3s

  [8084/17668] intraday_1644.csv.gz  in=309,098,526 out=90,067,252 elapsed=135.3s

  [8085/17668] intraday_16441.csv.gz  in=309,112,166 out=90,080,892 elapsed=135.3s

  [8086/17668] intraday_16440.csv.gz  in=309,124,490 out=90,093,216 elapsed=135.3s

  [8087/17668] intraday_16443.csv.gz  in=309,137,230 out=90,105,956 elapsed=135.3s

  [8088/17668] intraday_16442.csv.gz  in=309,150,540 out=90,119,266 elapsed=135.3s

  [8089/17668] intraday_16444.csv.gz  in=309,161,612 out=90,130,338 elapsed=135.4s

  [8090/17668] intraday_16445.csv.gz  in=309,173,321 out=90,142,047 elapsed=135.4s

  [8091/17668] intraday_16446.csv.gz  in=309,186,350 out=90,155,076 elapsed=135.4s

  [8092/17668] intraday_16447.csv.gz  in=309,198,607 out=90,167,333 elapsed=135.4s

  [8093/17668] intraday_16448.csv.gz  in=309,211,242 out=90,179,968 elapsed=135.4s

  [8094/17668] intraday_16449.csv.gz  in=309,222,305 out=90,191,031 elapsed=135.4s

  [8095/17668] intraday_16450.csv.gz  in=309,236,459 out=90,205,185 elapsed=135.4s

  [8096/17668] intraday_1645.csv.gz  in=309,251,892 out=90,205,185 elapsed=135.5s

  [8097/17668] intraday_16451.csv.gz  in=309,263,574 out=90,216,867 elapsed=135.5s

  [8098/17668] intraday_16452.csv.gz  in=309,278,157 out=90,231,450 elapsed=135.5s

  [8099/17668] intraday_16454.csv.gz  in=309,290,265 out=90,243,558 elapsed=135.5s

  [8100/17668] intraday_16453.csv.gz  in=309,303,080 out=90,256,373 elapsed=135.5s

  [8101/17668] intraday_16455.csv.gz  in=309,314,675 out=90,267,968 elapsed=135.5s

  [8102/17668] intraday_16456.csv.gz  in=309,327,030 out=90,280,323 elapsed=135.5s

  [8103/17668] intraday_16457.csv.gz  in=309,340,169 out=90,293,462 elapsed=135.5s

  [8104/17668] intraday_16458.csv.gz  in=309,352,078 out=90,305,371 elapsed=135.6s

  [8105/17668] intraday_16459.csv.gz  in=309,364,909 out=90,318,202 elapsed=135.6s

  [8106/17668] intraday_1646.csv.gz  in=309,377,216 out=90,318,202 elapsed=135.6s

  [8107/17668] intraday_16460.csv.gz  in=309,384,564 out=90,325,550 elapsed=135.6s

  [8108/17668] intraday_16461.csv.gz  in=309,397,323 out=90,338,309 elapsed=135.6s

  [8109/17668] intraday_16463.csv.gz  in=309,409,923 out=90,350,909 elapsed=135.6s

  [8110/17668] intraday_16462.csv.gz  in=309,423,638 out=90,364,624 elapsed=135.6s

  [8111/17668] intraday_16464.csv.gz  in=309,435,232 out=90,376,218 elapsed=135.6s

  [8112/17668] intraday_16465.csv.gz  in=309,444,858 out=90,385,844 elapsed=135.6s

  [8113/17668] intraday_16466.csv.gz  in=309,456,328 out=90,397,314 elapsed=135.6s

  [8114/17668] intraday_16467.csv.gz  in=309,469,666 out=90,410,652 elapsed=135.6s

  [8115/17668] intraday_16469.csv.gz  in=309,480,837 out=90,421,823 elapsed=135.7s

  [8116/17668] intraday_16468.csv.gz  in=309,493,312 out=90,434,298 elapsed=135.7s

  [8117/17668] intraday_1647.csv.gz  in=309,508,252 out=90,434,298 elapsed=135.7s

  [8118/17668] intraday_16471.csv.gz  in=309,517,174 out=90,443,220 elapsed=135.7s

  [8119/17668] intraday_16470.csv.gz  in=309,530,081 out=90,456,127 elapsed=135.7s

  [8120/17668] intraday_16473.csv.gz  in=309,542,958 out=90,469,004 elapsed=135.7s

  [8121/17668] intraday_16472.csv.gz  in=309,556,798 out=90,482,844 elapsed=135.7s

  [8122/17668] intraday_16474.csv.gz  in=309,569,015 out=90,495,061 elapsed=135.7s

  [8123/17668] intraday_16475.csv.gz  in=309,580,579 out=90,506,625 elapsed=135.8s

  [8124/17668] intraday_16477.csv.gz  in=309,591,252 out=90,517,298 elapsed=135.8s

  [8125/17668] intraday_16476.csv.gz  in=309,601,842 out=90,527,888 elapsed=135.8s

  [8126/17668] intraday_16478.csv.gz  in=309,613,922 out=90,539,968 elapsed=135.8s

  [8127/17668] intraday_16480.csv.gz  in=309,622,775 out=90,548,821 elapsed=135.8s

  [8128/17668] intraday_1648.csv.gz  in=309,633,667 out=90,548,821 elapsed=135.8s

  [8129/17668] intraday_16481.csv.gz  in=309,643,097 out=90,558,251 elapsed=135.8s

  [8130/17668] intraday_16479.csv.gz  in=309,661,916 out=90,577,070 elapsed=135.8s

  [8131/17668] intraday_16483.csv.gz  in=309,672,268 out=90,587,422 elapsed=135.9s

  [8132/17668] intraday_16484.csv.gz  in=309,684,924 out=90,600,078 elapsed=135.9s

  [8133/17668] intraday_16482.csv.gz  in=309,702,738 out=90,617,892 elapsed=135.9s

  [8134/17668] intraday_16485.csv.gz  in=309,714,126 out=90,629,280 elapsed=135.9s

  [8135/17668] intraday_16486.csv.gz  in=309,726,280 out=90,641,434 elapsed=135.9s

  [8136/17668] intraday_16487.csv.gz  in=309,739,261 out=90,654,415 elapsed=135.9s

  [8137/17668] intraday_16488.csv.gz  in=309,753,456 out=90,668,012 elapsed=135.9s

  [8138/17668] intraday_1649.csv.gz  in=309,764,922 out=90,668,012 elapsed=135.9s

  [8139/17668] intraday_16489.csv.gz  in=309,779,549 out=90,682,639 elapsed=136.0s

  [8140/17668] intraday_16490.csv.gz  in=309,790,185 out=90,693,275 elapsed=136.0s

  [8141/17668] intraday_16491.csv.gz  in=309,800,756 out=90,703,846 elapsed=136.0s

  [8142/17668] intraday_16492.csv.gz  in=309,813,798 out=90,716,888 elapsed=136.0s

  [8143/17668] intraday_16494.csv.gz  in=309,826,315 out=90,729,405 elapsed=136.0s

  [8144/17668] intraday_16493.csv.gz  in=309,838,975 out=90,742,065 elapsed=136.0s

  [8145/17668] intraday_16496.csv.gz  in=309,851,970 out=90,755,060 elapsed=136.1s

  [8146/17668] intraday_16495.csv.gz  in=309,865,511 out=90,768,601 elapsed=136.1s

  [8147/17668] intraday_16497.csv.gz  in=309,876,415 out=90,779,505 elapsed=136.1s

  [8148/17668] intraday_16498.csv.gz  in=309,890,997 out=90,794,087 elapsed=136.1s

  [8149/17668] intraday_1650.csv.gz  in=309,903,194 out=90,794,087 elapsed=136.1s

  [8150/17668] intraday_16500.csv.gz  in=309,914,896 out=90,805,789 elapsed=136.1s

  [8151/17668] intraday_16501.csv.gz  in=309,927,648 out=90,818,541 elapsed=136.2s

  [8152/17668] intraday_16499.csv.gz  in=309,981,005 out=90,870,505 elapsed=136.2s

  [8153/17668] intraday_16502.csv.gz  in=309,995,009 out=90,884,509 elapsed=136.2s

  [8154/17668] intraday_16504.csv.gz  in=310,007,040 out=90,896,540 elapsed=136.2s

  [8155/17668] intraday_16503.csv.gz  in=310,019,934 out=90,909,434 elapsed=136.2s

  [8156/17668] intraday_16505.csv.gz  in=310,033,411 out=90,922,911 elapsed=136.2s

  [8157/17668] intraday_16506.csv.gz  in=310,047,580 out=90,937,080 elapsed=136.2s

  [8158/17668] intraday_16507.csv.gz  in=310,062,300 out=90,951,800 elapsed=136.2s

  [8159/17668] intraday_16508.csv.gz  in=310,077,263 out=90,966,763 elapsed=136.3s

  [8160/17668] intraday_1651.csv.gz  in=310,088,892 out=90,966,763 elapsed=136.3s

  [8161/17668] intraday_16509.csv.gz  in=310,106,927 out=90,984,798 elapsed=136.3s

  [8162/17668] intraday_16510.csv.gz  in=310,120,670 out=90,998,541 elapsed=136.3s

  [8163/17668] intraday_16513.csv.gz  in=310,122,453 out=91,000,324 elapsed=136.3s

  [8164/17668] intraday_16512.csv.gz  in=310,134,347 out=91,012,218 elapsed=136.3s

  [8165/17668] intraday_16511.csv.gz  in=310,150,000 out=91,027,871 elapsed=136.3s

  [8166/17668] intraday_16514.csv.gz  in=310,157,058 out=91,034,929 elapsed=136.3s

  [8167/17668] intraday_16515.csv.gz  in=310,170,568 out=91,048,439 elapsed=136.3s

  [8168/17668] intraday_16517.csv.gz  in=310,186,661 out=91,064,532 elapsed=136.3s

  [8169/17668] intraday_16516.csv.gz  in=310,199,871 out=91,077,742 elapsed=136.4s

  [8170/17668] intraday_16518.csv.gz  in=310,210,816 out=91,088,687 elapsed=136.4s

  [8171/17668] intraday_16519.csv.gz  in=310,223,406 out=91,101,277 elapsed=136.4s

  [8172/17668] intraday_1652.csv.gz  in=310,233,102 out=91,101,277 elapsed=136.4s

  [8173/17668] intraday_16520.csv.gz  in=310,244,413 out=91,112,588 elapsed=136.4s

  [8174/17668] intraday_16521.csv.gz  in=310,257,599 out=91,125,774 elapsed=136.4s

  [8175/17668] intraday_16522.csv.gz  in=310,269,859 out=91,138,034 elapsed=136.4s

  [8176/17668] intraday_16523.csv.gz  in=310,283,899 out=91,152,074 elapsed=136.4s

  [8177/17668] intraday_16524.csv.gz  in=310,298,209 out=91,166,384 elapsed=136.4s

  [8178/17668] intraday_16525.csv.gz  in=310,312,703 out=91,180,878 elapsed=136.5s

  [8179/17668] intraday_16526.csv.gz  in=310,327,303 out=91,195,478 elapsed=136.5s

  [8180/17668] intraday_16527.csv.gz  in=310,340,160 out=91,208,335 elapsed=136.5s

  [8181/17668] intraday_16528.csv.gz  in=310,352,608 out=91,220,783 elapsed=136.5s

  [8182/17668] intraday_16529.csv.gz  in=310,365,365 out=91,233,540 elapsed=136.5s

  [8183/17668] intraday_1653.csv.gz  in=310,373,679 out=91,233,540 elapsed=136.5s

  [8184/17668] intraday_16530.csv.gz  in=310,384,269 out=91,244,130 elapsed=136.5s

  [8185/17668] intraday_16531.csv.gz  in=310,396,946 out=91,256,807 elapsed=136.5s

  [8186/17668] intraday_16532.csv.gz  in=310,405,711 out=91,265,572 elapsed=136.5s

  [8187/17668] intraday_16534.csv.gz  in=310,416,079 out=91,275,940 elapsed=136.6s

  [8188/17668] intraday_16533.csv.gz  in=310,426,624 out=91,286,485 elapsed=136.6s

  [8189/17668] intraday_16535.csv.gz  in=310,442,474 out=91,302,335 elapsed=136.6s

  [8190/17668] intraday_16538.csv.gz  in=310,454,148 out=91,314,009 elapsed=136.6s

  [8191/17668] intraday_16536.csv.gz  in=310,468,017 out=91,327,878 elapsed=136.6s

  [8192/17668] intraday_16539.csv.gz  in=310,479,323 out=91,339,184 elapsed=136.6s

  [8193/17668] intraday_1654.csv.gz  in=310,490,280 out=91,339,184 elapsed=136.6s

  [8194/17668] intraday_16537.csv.gz  in=310,504,182 out=91,353,086 elapsed=136.6s

  [8195/17668] intraday_16541.csv.gz  in=310,512,171 out=91,361,075 elapsed=136.7s

  [8196/17668] intraday_16543.csv.gz  in=310,524,400 out=91,373,304 elapsed=136.7s

  [8197/17668] intraday_16540.csv.gz  in=310,538,855 out=91,387,759 elapsed=136.7s

  [8198/17668] intraday_16542.csv.gz  in=310,548,541 out=91,397,445 elapsed=136.7s

  [8199/17668] intraday_16544.csv.gz  in=310,562,006 out=91,410,910 elapsed=136.7s

  [8200/17668] intraday_16545.csv.gz  in=310,574,791 out=91,423,695 elapsed=136.7s

  [8201/17668] intraday_16546.csv.gz  in=310,585,370 out=91,434,274 elapsed=136.8s

  [8202/17668] intraday_16547.csv.gz  in=310,596,432 out=91,445,336 elapsed=136.8s

  [8203/17668] intraday_16548.csv.gz  in=310,610,840 out=91,459,744 elapsed=136.8s

  [8204/17668] intraday_16549.csv.gz  in=310,624,180 out=91,473,084 elapsed=136.8s

  [8205/17668] intraday_1655.csv.gz  in=310,628,260 out=91,473,084 elapsed=136.8s

  [8206/17668] intraday_16550.csv.gz  in=310,639,579 out=91,484,403 elapsed=136.8s

  [8207/17668] intraday_16551.csv.gz  in=310,649,946 out=91,494,770 elapsed=136.8s

  [8208/17668] intraday_16553.csv.gz  in=310,661,815 out=91,506,639 elapsed=136.9s

  [8209/17668] intraday_16554.csv.gz  in=310,674,012 out=91,518,836 elapsed=136.9s

  [8210/17668] intraday_16552.csv.gz  in=310,687,192 out=91,532,016 elapsed=136.9s

  [8211/17668] intraday_16555.csv.gz  in=310,699,152 out=91,543,976 elapsed=136.9s

  [8212/17668] intraday_16556.csv.gz  in=310,711,176 out=91,556,000 elapsed=136.9s

  [8213/17668] intraday_16557.csv.gz  in=310,722,112 out=91,566,936 elapsed=136.9s

  [8214/17668] intraday_16559.csv.gz  in=310,725,118 out=91,569,942 elapsed=136.9s

  [8215/17668] intraday_16558.csv.gz  in=310,736,177 out=91,581,001 elapsed=136.9s

  [8216/17668] intraday_16560.csv.gz  in=310,745,791 out=91,590,615 elapsed=136.9s

  [8217/17668] intraday_1656.csv.gz  in=310,760,243 out=91,590,615 elapsed=137.0s

  [8218/17668] intraday_16562.csv.gz  in=310,770,583 out=91,600,955 elapsed=137.0s

  [8219/17668] intraday_16561.csv.gz  in=310,792,382 out=91,622,147 elapsed=137.0s

  [8220/17668] intraday_16563.csv.gz  in=310,806,481 out=91,636,246 elapsed=137.0s

  [8221/17668] intraday_16564.csv.gz  in=310,829,076 out=91,658,023 elapsed=137.0s

  [8222/17668] intraday_16565.csv.gz  in=310,842,050 out=91,670,997 elapsed=137.0s

  [8223/17668] intraday_16568.csv.gz  in=310,852,470 out=91,681,417 elapsed=137.0s

  [8224/17668] intraday_16566.csv.gz  in=310,866,329 out=91,695,276 elapsed=137.0s

  [8225/17668] intraday_16567.csv.gz  in=310,878,472 out=91,707,419 elapsed=137.0s

  [8226/17668] intraday_16569.csv.gz  in=310,887,674 out=91,716,621 elapsed=137.1s

  [8227/17668] intraday_1657.csv.gz  in=310,901,805 out=91,716,621 elapsed=137.1s

  [8228/17668] intraday_16570.csv.gz  in=310,913,798 out=91,728,614 elapsed=137.1s

  [8229/17668] intraday_16572.csv.gz  in=310,927,490 out=91,742,306 elapsed=137.1s

  [8230/17668] intraday_16571.csv.gz  in=310,939,515 out=91,754,331 elapsed=137.1s

  [8231/17668] intraday_16573.csv.gz  in=310,952,311 out=91,767,127 elapsed=137.1s

  [8232/17668] intraday_16575.csv.gz  in=310,962,407 out=91,777,223 elapsed=137.1s

  [8233/17668] intraday_16576.csv.gz  in=310,974,175 out=91,788,991 elapsed=137.1s

  [8234/17668] intraday_16574.csv.gz  in=310,987,060 out=91,801,876 elapsed=137.2s

  [8235/17668] intraday_16577.csv.gz  in=310,999,641 out=91,814,457 elapsed=137.2s

  [8236/17668] intraday_16578.csv.gz  in=311,010,535 out=91,825,351 elapsed=137.2s

  [8237/17668] intraday_1658.csv.gz  in=311,022,401 out=91,825,351 elapsed=137.2s

  [8238/17668] intraday_16579.csv.gz  in=311,035,757 out=91,838,707 elapsed=137.2s

  [8239/17668] intraday_16580.csv.gz  in=311,045,518 out=91,848,468 elapsed=137.2s

  [8240/17668] intraday_16582.csv.gz  in=311,058,285 out=91,861,235 elapsed=137.2s

  [8241/17668] intraday_16583.csv.gz  in=311,072,270 out=91,875,220 elapsed=137.3s

  [8242/17668] intraday_16581.csv.gz  in=311,085,688 out=91,888,638 elapsed=137.3s

  [8243/17668] intraday_16585.csv.gz  in=311,097,315 out=91,900,265 elapsed=137.3s

  [8244/17668] intraday_16584.csv.gz  in=311,111,657 out=91,914,607 elapsed=137.3s

  [8245/17668] intraday_16586.csv.gz  in=311,122,207 out=91,925,157 elapsed=137.3s

  [8246/17668] intraday_16588.csv.gz  in=311,124,562 out=91,927,512 elapsed=137.3s

  [8247/17668] intraday_16589.csv.gz  in=311,128,097 out=91,931,047 elapsed=137.3s

  [8248/17668] intraday_16587.csv.gz  in=311,139,908 out=91,942,858 elapsed=137.3s

  [8249/17668] intraday_1659.csv.gz  in=311,151,199 out=91,942,858 elapsed=137.3s

  [8250/17668] intraday_16590.csv.gz  in=311,162,899 out=91,954,558 elapsed=137.4s

  [8251/17668] intraday_16591.csv.gz  in=311,172,597 out=91,964,256 elapsed=137.4s

  [8252/17668] intraday_16593.csv.gz  in=311,185,522 out=91,977,181 elapsed=137.4s

  [8253/17668] intraday_16592.csv.gz  in=311,201,003 out=91,992,662 elapsed=137.4s

  [8254/17668] intraday_16594.csv.gz  in=311,214,029 out=92,005,688 elapsed=137.4s

  [8255/17668] intraday_16595.csv.gz  in=311,226,869 out=92,018,528 elapsed=137.4s

  [8256/17668] intraday_16596.csv.gz  in=311,238,119 out=92,029,778 elapsed=137.4s

  [8257/17668] intraday_16597.csv.gz  in=311,247,570 out=92,039,229 elapsed=137.4s

  [8258/17668] intraday_16598.csv.gz  in=311,259,262 out=92,050,921 elapsed=137.4s

  [8259/17668] intraday_16599.csv.gz  in=311,272,533 out=92,064,192 elapsed=137.4s

  [8260/17668] intraday_1660.csv.gz  in=311,286,085 out=92,064,192 elapsed=137.5s

  [8261/17668] intraday_16601.csv.gz  in=311,296,269 out=92,074,376 elapsed=137.5s

  [8262/17668] intraday_16600.csv.gz  in=311,309,542 out=92,087,649 elapsed=137.5s

  [8263/17668] intraday_16603.csv.gz  in=311,319,213 out=92,097,320 elapsed=137.5s

  [8264/17668] intraday_16604.csv.gz  in=311,333,067 out=92,111,174 elapsed=137.5s

  [8265/17668] intraday_16605.csv.gz  in=311,346,067 out=92,124,174 elapsed=137.5s

  [8266/17668] intraday_16606.csv.gz  in=311,357,530 out=92,135,637 elapsed=137.5s

  [8267/17668] intraday_16602.csv.gz  in=311,370,111 out=92,148,218 elapsed=137.5s

  [8268/17668] intraday_16607.csv.gz  in=311,382,251 out=92,160,358 elapsed=137.6s

  [8269/17668] intraday_1661.csv.gz  in=311,395,962 out=92,160,358 elapsed=137.6s

  [8270/17668] intraday_16608.csv.gz  in=311,405,908 out=92,170,304 elapsed=137.6s

  [8271/17668] intraday_16610.csv.gz  in=311,411,097 out=92,175,493 elapsed=137.6s

  [8272/17668] intraday_16609.csv.gz  in=311,423,080 out=92,187,476 elapsed=137.6s

  [8273/17668] intraday_16611.csv.gz  in=311,428,886 out=92,193,282 elapsed=137.6s

  [8274/17668] intraday_16613.csv.gz  in=311,441,532 out=92,205,928 elapsed=137.6s

  [8275/17668] intraday_16612.csv.gz  in=311,453,852 out=92,218,248 elapsed=137.6s

  [8276/17668] intraday_16614.csv.gz  in=311,467,177 out=92,231,573 elapsed=137.7s

  [8277/17668] intraday_16615.csv.gz  in=311,480,558 out=92,244,954 elapsed=137.7s

  [8278/17668] intraday_16616.csv.gz  in=311,490,643 out=92,255,039 elapsed=137.7s

  [8279/17668] intraday_16617.csv.gz  in=311,502,730 out=92,267,126 elapsed=137.7s

  [8280/17668] intraday_16618.csv.gz  in=311,513,035 out=92,277,431 elapsed=137.7s

  [8281/17668] intraday_16619.csv.gz  in=311,525,866 out=92,290,262 elapsed=137.7s

  [8282/17668] intraday_16620.csv.gz  in=311,537,598 out=92,301,994 elapsed=137.7s

  [8283/17668] intraday_1662.csv.gz  in=311,549,955 out=92,301,994 elapsed=137.7s

  [8284/17668] intraday_16621.csv.gz  in=311,561,660 out=92,313,699 elapsed=137.8s

  [8285/17668] intraday_16622.csv.gz  in=311,575,244 out=92,327,283 elapsed=137.8s

  [8286/17668] intraday_16624.csv.gz  in=311,585,183 out=92,337,222 elapsed=137.8s

  [8287/17668] intraday_16623.csv.gz  in=311,596,262 out=92,348,301 elapsed=137.8s

  [8288/17668] intraday_16626.csv.gz  in=311,608,320 out=92,360,359 elapsed=137.8s

  [8289/17668] intraday_16628.csv.gz  in=311,621,513 out=92,373,552 elapsed=137.8s

  [8290/17668] intraday_16625.csv.gz  in=311,634,909 out=92,386,948 elapsed=137.8s

  [8291/17668] intraday_16627.csv.gz  in=311,674,170 out=92,423,660 elapsed=137.8s

  [8292/17668] intraday_16629.csv.gz  in=311,687,317 out=92,436,807 elapsed=137.8s

  [8293/17668] intraday_1663.csv.gz  in=311,699,372 out=92,436,807 elapsed=137.8s

  [8294/17668] intraday_16630.csv.gz  in=311,710,842 out=92,448,277 elapsed=137.9s

  [8295/17668] intraday_16632.csv.gz  in=311,723,556 out=92,460,991 elapsed=137.9s

  [8296/17668] intraday_16631.csv.gz  in=311,736,982 out=92,474,417 elapsed=137.9s

  [8297/17668] intraday_16634.csv.gz  in=311,750,666 out=92,488,101 elapsed=137.9s

  [8298/17668] intraday_16633.csv.gz  in=311,761,753 out=92,499,188 elapsed=137.9s

  [8299/17668] intraday_16635.csv.gz  in=311,775,175 out=92,512,610 elapsed=137.9s

  [8300/17668] intraday_16637.csv.gz  in=311,782,186 out=92,519,621 elapsed=137.9s

  [8301/17668] intraday_16636.csv.gz  in=311,795,505 out=92,532,940 elapsed=138.0s

  [8302/17668] intraday_16638.csv.gz  in=311,807,427 out=92,544,862 elapsed=138.0s

  [8303/17668] intraday_16640.csv.gz  in=311,820,096 out=92,557,531 elapsed=138.0s

  [8304/17668] intraday_1664.csv.gz  in=311,833,961 out=92,557,531 elapsed=138.0s

  [8305/17668] intraday_16641.csv.gz  in=311,850,478 out=92,574,048 elapsed=138.0s

  [8306/17668] intraday_16639.csv.gz  in=311,889,145 out=92,611,743 elapsed=138.0s

  [8307/17668] intraday_16642.csv.gz  in=311,901,598 out=92,624,196 elapsed=138.0s

  [8308/17668] intraday_16644.csv.gz  in=311,912,107 out=92,634,705 elapsed=138.0s

  [8309/17668] intraday_16643.csv.gz  in=311,925,540 out=92,648,138 elapsed=138.0s

  [8310/17668] intraday_16645.csv.gz  in=311,938,072 out=92,660,670 elapsed=138.1s

  [8311/17668] intraday_16646.csv.gz  in=311,949,189 out=92,671,787 elapsed=138.1s

  [8312/17668] intraday_16647.csv.gz  in=311,961,771 out=92,684,369 elapsed=138.1s

  [8313/17668] intraday_16648.csv.gz  in=311,974,529 out=92,697,127 elapsed=138.1s

  [8314/17668] intraday_16649.csv.gz  in=311,990,963 out=92,713,561 elapsed=138.1s

  [8315/17668] intraday_1665.csv.gz  in=312,005,175 out=92,713,561 elapsed=138.1s

  [8316/17668] intraday_16650.csv.gz  in=312,014,951 out=92,723,337 elapsed=138.1s

  [8317/17668] intraday_16651.csv.gz  in=312,027,720 out=92,736,106 elapsed=138.2s

  [8318/17668] intraday_16652.csv.gz  in=312,040,086 out=92,748,472 elapsed=138.2s

  [8319/17668] intraday_16653.csv.gz  in=312,053,794 out=92,762,180 elapsed=138.2s

  [8320/17668] intraday_16654.csv.gz  in=312,065,248 out=92,773,634 elapsed=138.2s

  [8321/17668] intraday_16655.csv.gz  in=312,078,704 out=92,787,090 elapsed=138.2s

  [8322/17668] intraday_16656.csv.gz  in=312,092,496 out=92,800,882 elapsed=138.2s

  [8323/17668] intraday_16658.csv.gz  in=312,106,889 out=92,815,275 elapsed=138.2s

  [8324/17668] intraday_16657.csv.gz  in=312,120,951 out=92,829,337 elapsed=138.2s

  [8325/17668] intraday_16659.csv.gz  in=312,132,315 out=92,840,701 elapsed=138.3s

  [8326/17668] intraday_1666.csv.gz  in=312,141,605 out=92,840,701 elapsed=138.3s

  [8327/17668] intraday_16660.csv.gz  in=312,154,638 out=92,853,734 elapsed=138.3s

  [8328/17668] intraday_16661.csv.gz  in=312,166,749 out=92,865,845 elapsed=138.3s

  [8329/17668] intraday_16662.csv.gz  in=312,177,118 out=92,876,214 elapsed=138.3s

  [8330/17668] intraday_16663.csv.gz  in=312,189,940 out=92,889,036 elapsed=138.3s

  [8331/17668] intraday_16664.csv.gz  in=312,199,081 out=92,898,177 elapsed=138.3s

  [8332/17668] intraday_16665.csv.gz  in=312,207,545 out=92,906,641 elapsed=138.3s

  [8333/17668] intraday_16666.csv.gz  in=312,219,826 out=92,918,922 elapsed=138.4s

  [8334/17668] intraday_16667.csv.gz  in=312,235,563 out=92,934,659 elapsed=138.4s

  [8335/17668] intraday_16669.csv.gz  in=312,248,555 out=92,947,651 elapsed=138.4s

  [8336/17668] intraday_16668.csv.gz  in=312,261,592 out=92,960,688 elapsed=138.4s

  [8337/17668] intraday_1667.csv.gz  in=312,273,308 out=92,960,688 elapsed=138.4s

  [8338/17668] intraday_16670.csv.gz  in=312,284,171 out=92,971,551 elapsed=138.4s

  [8339/17668] intraday_16671.csv.gz  in=312,296,511 out=92,983,891 elapsed=138.4s

  [8340/17668] intraday_16672.csv.gz  in=312,311,129 out=92,998,509 elapsed=138.4s

  [8341/17668] intraday_16673.csv.gz  in=312,323,782 out=93,011,162 elapsed=138.4s

  [8342/17668] intraday_16674.csv.gz  in=312,334,827 out=93,022,207 elapsed=138.5s

  [8343/17668] intraday_16675.csv.gz  in=312,346,615 out=93,033,995 elapsed=138.5s

  [8344/17668] intraday_16676.csv.gz  in=312,359,078 out=93,046,458 elapsed=138.5s

  [8345/17668] intraday_16677.csv.gz  in=312,368,969 out=93,056,349 elapsed=138.5s

  [8346/17668] intraday_16678.csv.gz  in=312,380,604 out=93,067,984 elapsed=138.5s

  [8347/17668] intraday_16679.csv.gz  in=312,393,428 out=93,080,808 elapsed=138.5s

  [8348/17668] intraday_1668.csv.gz  in=312,412,483 out=93,080,808 elapsed=138.5s

  [8349/17668] intraday_16680.csv.gz  in=312,424,053 out=93,092,378 elapsed=138.5s

  [8350/17668] intraday_16681.csv.gz  in=312,434,490 out=93,102,815 elapsed=138.6s

  [8351/17668] intraday_16682.csv.gz  in=312,445,012 out=93,113,337 elapsed=138.6s

  [8352/17668] intraday_16684.csv.gz  in=312,457,908 out=93,126,233 elapsed=138.6s

  [8353/17668] intraday_16683.csv.gz  in=312,473,592 out=93,141,917 elapsed=138.6s

  [8354/17668] intraday_16685.csv.gz  in=312,484,566 out=93,152,891 elapsed=138.6s

  [8355/17668] intraday_16687.csv.gz  in=312,498,483 out=93,166,808 elapsed=138.6s

  [8356/17668] intraday_16686.csv.gz  in=312,508,942 out=93,177,267 elapsed=138.6s

  [8357/17668] intraday_16688.csv.gz  in=312,521,319 out=93,189,644 elapsed=138.7s

  [8358/17668] intraday_16690.csv.gz  in=312,523,515 out=93,191,840 elapsed=138.7s

  [8359/17668] intraday_16689.csv.gz  in=312,531,808 out=93,200,133 elapsed=138.7s

  [8360/17668] intraday_1669.csv.gz  in=312,542,658 out=93,200,133 elapsed=138.7s

  [8361/17668] intraday_16691.csv.gz  in=312,553,709 out=93,211,184 elapsed=138.7s

  [8362/17668] intraday_16692.csv.gz  in=312,567,645 out=93,225,120 elapsed=138.7s

  [8363/17668] intraday_16693.csv.gz  in=312,580,193 out=93,237,668 elapsed=138.7s

  [8364/17668] intraday_16694.csv.gz  in=312,595,703 out=93,253,178 elapsed=138.7s

  [8365/17668] intraday_16695.csv.gz  in=312,608,436 out=93,265,911 elapsed=138.7s

  [8366/17668] intraday_16696.csv.gz  in=312,618,488 out=93,275,963 elapsed=138.7s

  [8367/17668] intraday_1670.csv.gz  in=312,628,092 out=93,275,963 elapsed=138.8s

  [8368/17668] intraday_16699.csv.gz  in=312,640,401 out=93,288,272 elapsed=138.8s

  [8369/17668] intraday_16698.csv.gz  in=312,653,681 out=93,301,552 elapsed=138.8s

  [8370/17668] intraday_16701.csv.gz  in=312,665,281 out=93,313,152 elapsed=138.8s

  [8371/17668] intraday_16700.csv.gz  in=312,678,424 out=93,326,295 elapsed=138.8s

  [8372/17668] intraday_16697.csv.gz  in=312,709,215 out=93,355,617 elapsed=138.8s

  [8373/17668] intraday_16702.csv.gz  in=312,718,699 out=93,365,101 elapsed=138.8s

  [8374/17668] intraday_16703.csv.gz  in=312,728,958 out=93,375,360 elapsed=138.8s

  [8375/17668] intraday_16704.csv.gz  in=312,739,971 out=93,386,373 elapsed=138.8s

  [8376/17668] intraday_16706.csv.gz  in=312,753,620 out=93,400,022 elapsed=138.9s

  [8377/17668] intraday_16707.csv.gz  in=312,766,242 out=93,412,644 elapsed=138.9s

  [8378/17668] intraday_16705.csv.gz  in=312,777,756 out=93,424,158 elapsed=138.9s

  [8379/17668] intraday_16708.csv.gz  in=312,789,637 out=93,436,039 elapsed=138.9s

  [8380/17668] intraday_16709.csv.gz  in=312,800,714 out=93,447,116 elapsed=138.9s

  [8381/17668] intraday_16710.csv.gz  in=312,812,210 out=93,458,612 elapsed=138.9s

  [8382/17668] intraday_1671.csv.gz  in=312,825,769 out=93,458,612 elapsed=138.9s

  [8383/17668] intraday_16711.csv.gz  in=312,837,930 out=93,470,773 elapsed=138.9s

  [8384/17668] intraday_16714.csv.gz  in=312,848,107 out=93,480,950 elapsed=138.9s

  [8385/17668] intraday_16712.csv.gz  in=312,860,157 out=93,493,000 elapsed=138.9s

  [8386/17668] intraday_16713.csv.gz  in=312,872,394 out=93,505,237 elapsed=138.9s

  [8387/17668] intraday_16715.csv.gz  in=312,886,921 out=93,519,764 elapsed=139.0s

  [8388/17668] intraday_16716.csv.gz  in=312,899,358 out=93,532,201 elapsed=139.0s

  [8389/17668] intraday_16718.csv.gz  in=312,911,970 out=93,544,813 elapsed=139.0s

  [8390/17668] intraday_16717.csv.gz  in=312,925,612 out=93,558,455 elapsed=139.0s

  [8391/17668] intraday_16719.csv.gz  in=312,937,096 out=93,569,939 elapsed=139.0s

  [8392/17668] intraday_1672.csv.gz  in=312,948,476 out=93,569,939 elapsed=139.0s

  [8393/17668] intraday_16720.csv.gz  in=312,959,158 out=93,580,621 elapsed=139.1s

  [8394/17668] intraday_16723.csv.gz  in=312,971,447 out=93,592,910 elapsed=139.1s

  [8395/17668] intraday_16721.csv.gz  in=312,982,988 out=93,604,451 elapsed=139.1s

  [8396/17668] intraday_16722.csv.gz  in=312,995,437 out=93,616,900 elapsed=139.1s

  [8397/17668] intraday_16724.csv.gz  in=313,010,001 out=93,631,443 elapsed=139.1s

  [8398/17668] intraday_16725.csv.gz  in=313,018,728 out=93,640,170 elapsed=139.1s

  [8399/17668] intraday_16726.csv.gz  in=313,030,263 out=93,651,705 elapsed=139.1s

  [8400/17668] intraday_16727.csv.gz  in=313,040,514 out=93,661,956 elapsed=139.1s

  [8401/17668] intraday_16729.csv.gz  in=313,052,506 out=93,673,948 elapsed=139.1s

  [8402/17668] intraday_16728.csv.gz  in=313,066,971 out=93,688,413 elapsed=139.2s

  [8403/17668] intraday_1673.csv.gz  in=313,079,092 out=93,688,413 elapsed=139.2s

  [8404/17668] intraday_16730.csv.gz  in=313,092,321 out=93,701,642 elapsed=139.2s

  [8405/17668] intraday_16731.csv.gz  in=313,104,221 out=93,713,542 elapsed=139.2s

  [8406/17668] intraday_16733.csv.gz  in=313,112,386 out=93,721,707 elapsed=139.2s

  [8407/17668] intraday_16732.csv.gz  in=313,124,711 out=93,734,032 elapsed=139.2s

  [8408/17668] intraday_16734.csv.gz  in=313,136,664 out=93,745,985 elapsed=139.2s

  [8409/17668] intraday_16735.csv.gz  in=313,149,282 out=93,758,603 elapsed=139.2s

  [8410/17668] intraday_16736.csv.gz  in=313,161,819 out=93,771,140 elapsed=139.2s

  [8411/17668] intraday_16737.csv.gz  in=313,171,519 out=93,780,840 elapsed=139.2s

  [8412/17668] intraday_16739.csv.gz  in=313,180,997 out=93,790,318 elapsed=139.3s

  [8413/17668] intraday_16738.csv.gz  in=313,192,286 out=93,801,607 elapsed=139.3s

  [8414/17668] intraday_1674.csv.gz  in=313,203,932 out=93,801,607 elapsed=139.3s

  [8415/17668] intraday_16740.csv.gz  in=313,216,664 out=93,814,339 elapsed=139.3s

  [8416/17668] intraday_16741.csv.gz  in=313,229,667 out=93,827,342 elapsed=139.3s

  [8417/17668] intraday_16742.csv.gz  in=313,241,424 out=93,839,099 elapsed=139.3s

  [8418/17668] intraday_16743.csv.gz  in=313,253,403 out=93,851,078 elapsed=139.3s

  [8419/17668] intraday_16744.csv.gz  in=313,263,534 out=93,861,209 elapsed=139.3s

  [8420/17668] intraday_16746.csv.gz  in=313,276,131 out=93,873,806 elapsed=139.4s

  [8421/17668] intraday_16745.csv.gz  in=313,286,994 out=93,884,669 elapsed=139.4s

  [8422/17668] intraday_16747.csv.gz  in=313,304,692 out=93,902,367 elapsed=139.4s

  [8423/17668] intraday_16748.csv.gz  in=313,315,962 out=93,913,637 elapsed=139.4s

  [8424/17668] intraday_16749.csv.gz  in=313,327,936 out=93,925,611 elapsed=139.4s

  [8425/17668] intraday_1675.csv.gz  in=313,339,818 out=93,925,611 elapsed=139.4s

  [8426/17668] intraday_16750.csv.gz  in=313,352,098 out=93,937,891 elapsed=139.4s

  [8427/17668] intraday_16751.csv.gz  in=313,364,874 out=93,950,075 elapsed=139.4s

  [8428/17668] intraday_16752.csv.gz  in=313,376,242 out=93,961,443 elapsed=139.5s

  [8429/17668] intraday_16753.csv.gz  in=313,389,393 out=93,974,594 elapsed=139.5s

  [8430/17668] intraday_16754.csv.gz  in=313,399,332 out=93,984,533 elapsed=139.5s

  [8431/17668] intraday_16755.csv.gz  in=313,411,464 out=93,996,665 elapsed=139.5s

  [8432/17668] intraday_16756.csv.gz  in=313,421,773 out=94,006,974 elapsed=139.5s

  [8433/17668] intraday_1676.csv.gz  in=313,435,104 out=94,006,974 elapsed=139.5s

  [8434/17668] intraday_16758.csv.gz  in=313,447,242 out=94,019,112 elapsed=139.5s

  [8435/17668] intraday_16757.csv.gz  in=313,458,636 out=94,030,506 elapsed=139.5s

  [8436/17668] intraday_16759.csv.gz  in=313,470,567 out=94,042,437 elapsed=139.5s

  [8437/17668] intraday_16760.csv.gz  in=313,482,841 out=94,054,711 elapsed=139.5s

  [8438/17668] intraday_16761.csv.gz  in=313,492,516 out=94,064,386 elapsed=139.5s

  [8439/17668] intraday_16762.csv.gz  in=313,502,532 out=94,074,402 elapsed=139.6s

  [8440/17668] intraday_16763.csv.gz  in=313,514,327 out=94,086,197 elapsed=139.6s

  [8441/17668] intraday_16764.csv.gz  in=313,527,072 out=94,098,942 elapsed=139.6s

  [8442/17668] intraday_16766.csv.gz  in=313,538,608 out=94,110,478 elapsed=139.6s

  [8443/17668] intraday_16765.csv.gz  in=313,550,789 out=94,122,659 elapsed=139.6s

  [8444/17668] intraday_16768.csv.gz  in=313,562,067 out=94,133,937 elapsed=139.6s

  [8445/17668] intraday_16767.csv.gz  in=313,574,499 out=94,146,369 elapsed=139.6s

  [8446/17668] intraday_1677.csv.gz  in=313,586,250 out=94,146,369 elapsed=139.6s

  [8447/17668] intraday_16769.csv.gz  in=313,598,354 out=94,158,473 elapsed=139.6s

  [8448/17668] intraday_16771.csv.gz  in=313,609,783 out=94,169,902 elapsed=139.7s

  [8449/17668] intraday_16770.csv.gz  in=313,621,939 out=94,182,058 elapsed=139.7s

  [8450/17668] intraday_16772.csv.gz  in=313,636,311 out=94,196,430 elapsed=139.7s

  [8451/17668] intraday_16773.csv.gz  in=313,650,047 out=94,210,166 elapsed=139.7s

  [8452/17668] intraday_16774.csv.gz  in=313,661,579 out=94,221,698 elapsed=139.7s

  [8453/17668] intraday_16776.csv.gz  in=313,675,086 out=94,235,205 elapsed=139.7s

  [8454/17668] intraday_16775.csv.gz  in=313,687,435 out=94,247,554 elapsed=139.8s

  [8455/17668] intraday_16777.csv.gz  in=313,699,297 out=94,259,416 elapsed=139.8s

  [8456/17668] intraday_16778.csv.gz  in=313,713,288 out=94,273,407 elapsed=139.8s

  [8457/17668] intraday_16779.csv.gz  in=313,728,308 out=94,288,427 elapsed=139.8s

  [8458/17668] intraday_1678.csv.gz  in=313,740,962 out=94,288,427 elapsed=139.8s

  [8459/17668] intraday_16780.csv.gz  in=313,757,916 out=94,305,381 elapsed=139.8s

  [8460/17668] intraday_16781.csv.gz  in=313,770,070 out=94,317,535 elapsed=139.8s

  [8461/17668] intraday_16783.csv.gz  in=313,782,248 out=94,329,713 elapsed=139.8s

  [8462/17668] intraday_16782.csv.gz  in=313,798,019 out=94,345,484 elapsed=139.8s

  [8463/17668] intraday_16784.csv.gz  in=313,810,718 out=94,358,183 elapsed=139.8s

  [8464/17668] intraday_16786.csv.gz  in=313,823,087 out=94,370,552 elapsed=139.9s

  [8465/17668] intraday_16787.csv.gz  in=313,832,889 out=94,380,354 elapsed=139.9s

  [8466/17668] intraday_16788.csv.gz  in=313,845,515 out=94,392,980 elapsed=139.9s

  [8467/17668] intraday_16785.csv.gz  in=313,856,018 out=94,403,483 elapsed=139.9s

  [8468/17668] intraday_16789.csv.gz  in=313,867,953 out=94,415,418 elapsed=139.9s

  [8469/17668] intraday_16791.csv.gz  in=313,879,453 out=94,426,918 elapsed=140.0s

  [8470/17668] intraday_16790.csv.gz  in=313,893,320 out=94,440,785 elapsed=140.0s

  [8471/17668] intraday_1679.csv.gz  in=313,916,683 out=94,440,785 elapsed=140.0s

  [8472/17668] intraday_16792.csv.gz  in=313,927,322 out=94,451,424 elapsed=140.0s

  [8473/17668] intraday_16793.csv.gz  in=313,939,340 out=94,463,442 elapsed=140.0s

  [8474/17668] intraday_16795.csv.gz  in=313,950,165 out=94,474,267 elapsed=140.0s

  [8475/17668] intraday_16794.csv.gz  in=313,964,623 out=94,488,725 elapsed=140.0s

  [8476/17668] intraday_16796.csv.gz  in=313,983,288 out=94,507,082 elapsed=140.0s

  [8477/17668] intraday_16797.csv.gz  in=313,996,005 out=94,519,799 elapsed=140.1s

  [8478/17668] intraday_16798.csv.gz  in=314,009,437 out=94,533,231 elapsed=140.1s

  [8479/17668] intraday_16799.csv.gz  in=314,024,526 out=94,548,320 elapsed=140.1s

  [8480/17668] intraday_1680.csv.gz  in=314,035,656 out=94,548,320 elapsed=140.1s

  [8481/17668] intraday_16800.csv.gz  in=314,046,326 out=94,558,990 elapsed=140.1s

  [8482/17668] intraday_16801.csv.gz  in=314,058,793 out=94,571,457 elapsed=140.1s

  [8483/17668] intraday_16802.csv.gz  in=314,070,387 out=94,583,051 elapsed=140.1s

  [8484/17668] intraday_16805.csv.gz  in=314,079,624 out=94,592,288 elapsed=140.2s

  [8485/17668] intraday_16803.csv.gz  in=314,090,819 out=94,603,483 elapsed=140.2s

  [8486/17668] intraday_16804.csv.gz  in=314,101,489 out=94,614,153 elapsed=140.2s

  [8487/17668] intraday_16806.csv.gz  in=314,110,914 out=94,623,578 elapsed=140.2s

  [8488/17668] intraday_16808.csv.gz  in=314,111,390 out=94,624,021 elapsed=140.2s

  [8489/17668] intraday_16807.csv.gz  in=314,119,685 out=94,632,316 elapsed=140.2s

  [8490/17668] intraday_16809.csv.gz  in=314,119,741 out=94,632,316 elapsed=140.2s

  [8491/17668] intraday_16810.csv.gz  in=314,120,672 out=94,633,247 elapsed=140.2s

  [8492/17668] intraday_1681.csv.gz  in=314,130,482 out=94,633,247 elapsed=140.2s

  [8493/17668] intraday_16812.csv.gz  in=314,130,983 out=94,633,748 elapsed=140.2s

  [8494/17668] intraday_16811.csv.gz  in=314,131,460 out=94,634,225 elapsed=140.2s

  [8495/17668] intraday_16813.csv.gz  in=314,131,814 out=94,634,579 elapsed=140.2s

  [8496/17668] intraday_16815.csv.gz  in=314,132,810 out=94,635,575 elapsed=140.2s

  [8497/17668] intraday_16816.csv.gz  in=314,133,372 out=94,636,137 elapsed=140.2s

  [8498/17668] intraday_16814.csv.gz  in=314,133,747 out=94,636,512 elapsed=140.2s

  [8499/17668] intraday_16817.csv.gz  in=314,134,046 out=94,636,811 elapsed=140.3s

  [8500/17668] intraday_16818.csv.gz  in=314,134,491 out=94,637,256 elapsed=140.3s

  [8501/17668] intraday_16819.csv.gz  in=314,135,225 out=94,637,990 elapsed=140.3s

  [8502/17668] intraday_16820.csv.gz  in=314,135,700 out=94,638,465 elapsed=140.3s

  [8503/17668] intraday_16821.csv.gz  in=314,136,227 out=94,638,992 elapsed=140.3s

  [8504/17668] intraday_1682.csv.gz  in=314,148,947 out=94,638,992 elapsed=140.3s

  [8505/17668] intraday_16822.csv.gz  in=314,149,723 out=94,639,768 elapsed=140.3s

  [8506/17668] intraday_16823.csv.gz  in=314,150,026 out=94,640,071 elapsed=140.3s

  [8507/17668] intraday_16824.csv.gz  in=314,150,516 out=94,640,561 elapsed=140.3s

  [8508/17668] intraday_16827.csv.gz  in=314,151,344 out=94,641,389 elapsed=140.3s

  [8509/17668] intraday_16826.csv.gz  in=314,152,118 out=94,642,163 elapsed=140.3s

  [8510/17668] intraday_16825.csv.gz  in=314,152,462 out=94,642,507 elapsed=140.3s

  [8511/17668] intraday_16829.csv.gz  in=314,152,871 out=94,642,916 elapsed=140.3s

  [8512/17668] intraday_16828.csv.gz  in=314,153,216 out=94,643,261 elapsed=140.3s

  [8513/17668] intraday_16831.csv.gz  in=314,153,426 out=94,643,471 elapsed=140.3s

  [8514/17668] intraday_16830.csv.gz  in=314,154,179 out=94,644,224 elapsed=140.3s

  [8515/17668] intraday_1683.csv.gz  in=314,166,722 out=94,644,224 elapsed=140.3s

  [8516/17668] intraday_16832.csv.gz  in=314,167,011 out=94,644,513 elapsed=140.3s

  [8517/17668] intraday_16833.csv.gz  in=314,167,483 out=94,644,985 elapsed=140.3s

  [8518/17668] intraday_16834.csv.gz  in=314,167,564 out=94,645,066 elapsed=140.4s

  [8519/17668] intraday_16836.csv.gz  in=314,167,835 out=94,645,337 elapsed=140.4s

  [8520/17668] intraday_16835.csv.gz  in=314,168,246 out=94,645,748 elapsed=140.4s

  [8521/17668] intraday_16837.csv.gz  in=314,168,306 out=94,645,808 elapsed=140.4s

  [8522/17668] intraday_16839.csv.gz  in=314,169,414 out=94,646,916 elapsed=140.4s

  [8523/17668] intraday_16838.csv.gz  in=314,170,526 out=94,648,028 elapsed=140.4s

  [8524/17668] intraday_16840.csv.gz  in=314,171,552 out=94,649,054 elapsed=140.4s

  [8525/17668] intraday_16842.csv.gz  in=314,171,996 out=94,649,498 elapsed=140.4s

  [8526/17668] intraday_16843.csv.gz  in=314,172,640 out=94,650,142 elapsed=140.4s

  [8527/17668] intraday_16844.csv.gz  in=314,172,979 out=94,650,481 elapsed=140.4s

  [8528/17668] intraday_1684.csv.gz  in=314,192,978 out=94,650,481 elapsed=140.4s

  [8529/17668] intraday_16845.csv.gz  in=314,193,452 out=94,650,955 elapsed=140.4s

  [8530/17668] intraday_16841.csv.gz  in=314,212,102 out=94,668,521 elapsed=140.4s

  [8531/17668] intraday_16846.csv.gz  in=314,212,389 out=94,668,808 elapsed=140.4s

  [8532/17668] intraday_16847.csv.gz  in=314,212,659 out=94,669,078 elapsed=140.4s

  [8533/17668] intraday_16848.csv.gz  in=314,212,804 out=94,669,223 elapsed=140.4s

  [8534/17668] intraday_16849.csv.gz  in=314,213,027 out=94,669,446 elapsed=140.5s

  [8535/17668] intraday_16851.csv.gz  in=314,213,108 out=94,669,527 elapsed=140.5s

  [8536/17668] intraday_16850.csv.gz  in=314,213,323 out=94,669,742 elapsed=140.5s

  [8537/17668] intraday_16854.csv.gz  in=314,213,561 out=94,669,980 elapsed=140.5s

  [8538/17668] intraday_16853.csv.gz  in=314,213,809 out=94,670,228 elapsed=140.5s

  [8539/17668] intraday_1685.csv.gz  in=314,227,511 out=94,670,228 elapsed=140.5s

  [8540/17668] intraday_16852.csv.gz  in=314,228,396 out=94,671,113 elapsed=140.5s

  [8541/17668] intraday_16856.csv.gz  in=314,228,629 out=94,671,346 elapsed=140.5s

  [8542/17668] intraday_16857.csv.gz  in=314,228,817 out=94,671,534 elapsed=140.5s

  [8543/17668] intraday_16855.csv.gz  in=314,228,933 out=94,671,650 elapsed=140.5s

  [8544/17668] intraday_16858.csv.gz  in=314,229,191 out=94,671,908 elapsed=140.5s

  [8545/17668] intraday_16859.csv.gz  in=314,229,364 out=94,672,081 elapsed=140.5s

  [8546/17668] intraday_16861.csv.gz  in=314,230,151 out=94,672,868 elapsed=140.5s

  [8547/17668] intraday_16860.csv.gz  in=314,230,345 out=94,673,062 elapsed=140.5s

  [8548/17668] intraday_16863.csv.gz  in=314,231,215 out=94,673,932 elapsed=140.5s

  [8549/17668] intraday_16862.csv.gz  in=314,232,348 out=94,675,065 elapsed=140.5s

  [8550/17668] intraday_16864.csv.gz  in=314,232,924 out=94,675,641 elapsed=140.5s

  [8551/17668] intraday_1686.csv.gz  in=314,244,571 out=94,675,641 elapsed=140.5s

  [8552/17668] intraday_16865.csv.gz  in=314,244,698 out=94,675,768 elapsed=140.5s

  [8553/17668] intraday_16866.csv.gz  in=314,244,809 out=94,675,879 elapsed=140.5s

  [8554/17668] intraday_16867.csv.gz  in=314,245,037 out=94,676,107 elapsed=140.5s

  [8555/17668] intraday_16868.csv.gz  in=314,245,540 out=94,676,610 elapsed=140.5s

  [8556/17668] intraday_16869.csv.gz  in=314,245,852 out=94,676,922 elapsed=140.6s

  [8557/17668] intraday_16870.csv.gz  in=314,246,381 out=94,677,451 elapsed=140.6s

  [8558/17668] intraday_16871.csv.gz  in=314,246,479 out=94,677,549 elapsed=140.6s

  [8559/17668] intraday_16873.csv.gz  in=314,246,709 out=94,677,779 elapsed=140.6s

  [8560/17668] intraday_16872.csv.gz  in=314,247,007 out=94,678,077 elapsed=140.6s

  [8561/17668] intraday_16875.csv.gz  in=314,247,637 out=94,678,707 elapsed=140.6s

  [8562/17668] intraday_1687.csv.gz  in=314,267,727 out=94,678,707 elapsed=140.6s

  [8563/17668] intraday_16876.csv.gz  in=314,267,966 out=94,678,946 elapsed=140.6s

  [8564/17668] intraday_16874.csv.gz  in=314,268,886 out=94,679,866 elapsed=140.6s

  [8565/17668] intraday_16877.csv.gz  in=314,269,396 out=94,680,376 elapsed=140.6s

  [8566/17668] intraday_16878.csv.gz  in=314,269,673 out=94,680,653 elapsed=140.6s

  [8567/17668] intraday_16879.csv.gz  in=314,269,860 out=94,680,840 elapsed=140.6s

  [8568/17668] intraday_16880.csv.gz  in=314,270,665 out=94,681,645 elapsed=140.6s

  [8569/17668] intraday_16881.csv.gz  in=314,270,853 out=94,681,833 elapsed=140.6s

  [8570/17668] intraday_16882.csv.gz  in=314,271,105 out=94,682,085 elapsed=140.6s

  [8571/17668] intraday_1688.csv.gz  in=314,282,574 out=94,682,085 elapsed=140.6s

  [8572/17668] intraday_16884.csv.gz  in=314,283,369 out=94,682,880 elapsed=140.6s

  [8573/17668] intraday_16885.csv.gz  in=314,283,673 out=94,683,184 elapsed=140.7s

  [8574/17668] intraday_16883.csv.gz  in=314,283,991 out=94,683,502 elapsed=140.7s

  [8575/17668] intraday_16886.csv.gz  in=314,284,350 out=94,683,861 elapsed=140.7s

  [8576/17668] intraday_16887.csv.gz  in=314,284,842 out=94,684,353 elapsed=140.7s

  [8577/17668] intraday_16888.csv.gz  in=314,285,445 out=94,684,956 elapsed=140.7s

  [8578/17668] intraday_16889.csv.gz  in=314,285,500 out=94,685,011 elapsed=140.7s

  [8579/17668] intraday_16890.csv.gz  in=314,285,768 out=94,685,279 elapsed=140.7s

  [8580/17668] intraday_16891.csv.gz  in=314,286,891 out=94,686,402 elapsed=140.7s

  [8581/17668] intraday_1689.csv.gz  in=314,299,791 out=94,686,402 elapsed=140.7s

  [8582/17668] intraday_16893.csv.gz  in=314,300,935 out=94,687,546 elapsed=140.7s

  [8583/17668] intraday_16892.csv.gz  in=314,302,121 out=94,688,732 elapsed=140.7s

  [8584/17668] intraday_16894.csv.gz  in=314,302,919 out=94,689,530 elapsed=140.7s

  [8585/17668] intraday_16895.csv.gz  in=314,303,494 out=94,690,105 elapsed=140.7s

  [8586/17668] intraday_16896.csv.gz  in=314,304,101 out=94,690,712 elapsed=140.7s

  [8587/17668] intraday_16899.csv.gz  in=314,304,406 out=94,691,017 elapsed=140.7s

  [8588/17668] intraday_16897.csv.gz  in=314,304,564 out=94,691,175 elapsed=140.7s

  [8589/17668] intraday_16898.csv.gz  in=314,305,581 out=94,692,192 elapsed=140.7s

  [8590/17668] intraday_16901.csv.gz  in=314,306,212 out=94,692,823 elapsed=140.8s

  [8591/17668] intraday_16902.csv.gz  in=314,306,633 out=94,693,244 elapsed=140.8s

  [8592/17668] intraday_16900.csv.gz  in=314,306,902 out=94,693,513 elapsed=140.8s

  [8593/17668] intraday_1690.csv.gz  in=314,317,452 out=94,693,513 elapsed=140.8s

  [8594/17668] intraday_16903.csv.gz  in=314,317,864 out=94,693,925 elapsed=140.8s

  [8595/17668] intraday_16905.csv.gz  in=314,318,289 out=94,694,350 elapsed=140.8s

  [8596/17668] intraday_16904.csv.gz  in=314,318,593 out=94,694,654 elapsed=140.8s

  [8597/17668] intraday_16906.csv.gz  in=314,318,681 out=94,694,742 elapsed=140.8s

  [8598/17668] intraday_16907.csv.gz  in=314,319,229 out=94,695,290 elapsed=140.8s

  [8599/17668] intraday_16909.csv.gz  in=314,319,422 out=94,695,483 elapsed=140.8s

  [8600/17668] intraday_16908.csv.gz  in=314,319,613 out=94,695,674 elapsed=140.8s

  [8601/17668] intraday_16910.csv.gz  in=314,320,219 out=94,696,280 elapsed=140.8s

  [8602/17668] intraday_16911.csv.gz  in=314,321,671 out=94,697,732 elapsed=140.8s

  [8603/17668] intraday_16912.csv.gz  in=314,322,312 out=94,698,373 elapsed=140.8s

  [8604/17668] intraday_16913.csv.gz  in=314,322,938 out=94,698,999 elapsed=140.8s

  [8605/17668] intraday_1691.csv.gz  in=314,335,760 out=94,698,999 elapsed=140.8s

  [8606/17668] intraday_16914.csv.gz  in=314,336,239 out=94,699,478 elapsed=140.8s

  [8607/17668] intraday_16915.csv.gz  in=314,336,812 out=94,700,051 elapsed=140.8s

  [8608/17668] intraday_16916.csv.gz  in=314,336,937 out=94,700,176 elapsed=140.8s

  [8609/17668] intraday_16917.csv.gz  in=314,337,294 out=94,700,533 elapsed=140.8s

  [8610/17668] intraday_16918.csv.gz  in=314,337,649 out=94,700,888 elapsed=140.9s

  [8611/17668] intraday_16920.csv.gz  in=314,338,140 out=94,701,379 elapsed=140.9s

  [8612/17668] intraday_16919.csv.gz  in=314,338,869 out=94,702,108 elapsed=140.9s

  [8613/17668] intraday_16921.csv.gz  in=314,339,097 out=94,702,336 elapsed=140.9s

  [8614/17668] intraday_16922.csv.gz  in=314,340,061 out=94,703,300 elapsed=140.9s

  [8615/17668] intraday_1692.csv.gz  in=314,352,132 out=94,703,300 elapsed=140.9s

  [8616/17668] intraday_16923.csv.gz  in=314,353,065 out=94,704,233 elapsed=140.9s

  [8617/17668] intraday_16924.csv.gz  in=314,354,430 out=94,705,598 elapsed=140.9s

  [8618/17668] intraday_16925.csv.gz  in=314,356,196 out=94,707,364 elapsed=140.9s

  [8619/17668] intraday_16927.csv.gz  in=314,357,259 out=94,708,427 elapsed=140.9s

  [8620/17668] intraday_16926.csv.gz  in=314,357,522 out=94,708,690 elapsed=140.9s

  [8621/17668] intraday_16928.csv.gz  in=314,357,811 out=94,708,979 elapsed=140.9s

  [8622/17668] intraday_16929.csv.gz  in=314,358,219 out=94,709,387 elapsed=140.9s

  [8623/17668] intraday_16930.csv.gz  in=314,358,307 out=94,709,475 elapsed=140.9s

  [8624/17668] intraday_16931.csv.gz  in=314,358,874 out=94,710,042 elapsed=140.9s

  [8625/17668] intraday_16932.csv.gz  in=314,358,953 out=94,710,121 elapsed=140.9s

  [8626/17668] intraday_1693.csv.gz  in=314,369,784 out=94,710,121 elapsed=140.9s

  [8627/17668] intraday_16934.csv.gz  in=314,370,267 out=94,710,604 elapsed=140.9s

  [8628/17668] intraday_16933.csv.gz  in=314,370,763 out=94,711,100 elapsed=140.9s

  [8629/17668] intraday_16935.csv.gz  in=314,371,866 out=94,712,203 elapsed=140.9s

  [8630/17668] intraday_16936.csv.gz  in=314,372,129 out=94,712,466 elapsed=140.9s

  [8631/17668] intraday_16937.csv.gz  in=314,372,611 out=94,712,948 elapsed=140.9s

  [8632/17668] intraday_16938.csv.gz  in=314,373,148 out=94,713,485 elapsed=141.0s

  [8633/17668] intraday_16939.csv.gz  in=314,374,023 out=94,714,360 elapsed=141.0s

  [8634/17668] intraday_16940.csv.gz  in=314,374,277 out=94,714,614 elapsed=141.0s

  [8635/17668] intraday_16941.csv.gz  in=314,374,755 out=94,715,092 elapsed=141.0s

  [8636/17668] intraday_16942.csv.gz  in=314,374,978 out=94,715,315 elapsed=141.0s

  [8637/17668] intraday_16943.csv.gz  in=314,375,564 out=94,715,901 elapsed=141.0s

  [8638/17668] intraday_1694.csv.gz  in=314,398,833 out=94,715,901 elapsed=141.0s

  [8639/17668] intraday_16944.csv.gz  in=314,399,199 out=94,716,267 elapsed=141.0s

  [8640/17668] intraday_16945.csv.gz  in=314,399,647 out=94,716,715 elapsed=141.0s

  [8641/17668] intraday_16947.csv.gz  in=314,399,866 out=94,716,934 elapsed=141.0s

  [8642/17668] intraday_16946.csv.gz  in=314,400,303 out=94,717,371 elapsed=141.0s

  [8643/17668] intraday_16948.csv.gz  in=314,400,548 out=94,717,616 elapsed=141.0s

  [8644/17668] intraday_16949.csv.gz  in=314,401,003 out=94,718,071 elapsed=141.0s

  [8645/17668] intraday_16950.csv.gz  in=314,401,425 out=94,718,493 elapsed=141.0s

  [8646/17668] intraday_16951.csv.gz  in=314,401,766 out=94,718,834 elapsed=141.0s

  [8647/17668] intraday_1695.csv.gz  in=314,416,866 out=94,718,834 elapsed=141.0s

  [8648/17668] intraday_16952.csv.gz  in=314,417,211 out=94,719,179 elapsed=141.1s

  [8649/17668] intraday_16954.csv.gz  in=314,430,887 out=94,732,855 elapsed=141.1s

  [8650/17668] intraday_16953.csv.gz  in=314,447,828 out=94,749,796 elapsed=141.1s

  [8651/17668] intraday_16955.csv.gz  in=314,460,518 out=94,762,486 elapsed=141.1s

  [8652/17668] intraday_16956.csv.gz  in=314,471,545 out=94,773,513 elapsed=141.1s

  [8653/17668] intraday_16957.csv.gz  in=314,484,437 out=94,786,405 elapsed=141.1s

  [8654/17668] intraday_16959.csv.gz  in=314,497,532 out=94,799,500 elapsed=141.2s

  [8655/17668] intraday_16958.csv.gz  in=314,514,114 out=94,816,082 elapsed=141.2s

  [8656/17668] intraday_1696.csv.gz  in=314,526,998 out=94,816,082 elapsed=141.2s

  [8657/17668] intraday_16960.csv.gz  in=314,538,823 out=94,827,907 elapsed=141.2s

  [8658/17668] intraday_16961.csv.gz  in=314,551,869 out=94,840,953 elapsed=141.2s

  [8659/17668] intraday_16962.csv.gz  in=314,565,749 out=94,854,833 elapsed=141.2s

  [8660/17668] intraday_16964.csv.gz  in=314,579,690 out=94,868,774 elapsed=141.2s

  [8661/17668] intraday_16963.csv.gz  in=314,590,309 out=94,879,393 elapsed=141.2s

  [8662/17668] intraday_16965.csv.gz  in=314,604,306 out=94,893,390 elapsed=141.3s

  [8663/17668] intraday_16966.csv.gz  in=314,616,474 out=94,905,558 elapsed=141.3s

  [8664/17668] intraday_16968.csv.gz  in=314,627,062 out=94,916,146 elapsed=141.3s

  [8665/17668] intraday_16967.csv.gz  in=314,637,813 out=94,926,897 elapsed=141.3s

  [8666/17668] intraday_1697.csv.gz  in=314,649,799 out=94,926,897 elapsed=141.3s

  [8667/17668] intraday_16969.csv.gz  in=314,666,048 out=94,943,146 elapsed=141.3s

  [8668/17668] intraday_16970.csv.gz  in=314,680,535 out=94,957,633 elapsed=141.3s

  [8669/17668] intraday_16972.csv.gz  in=314,691,864 out=94,968,962 elapsed=141.3s

  [8670/17668] intraday_16971.csv.gz  in=314,703,633 out=94,980,731 elapsed=141.4s

  [8671/17668] intraday_16973.csv.gz  in=314,719,149 out=94,996,247 elapsed=141.4s

  [8672/17668] intraday_16975.csv.gz  in=314,731,264 out=95,008,362 elapsed=141.4s

  [8673/17668] intraday_16974.csv.gz  in=314,743,899 out=95,020,997 elapsed=141.4s

  [8674/17668] intraday_16976.csv.gz  in=314,756,580 out=95,033,678 elapsed=141.4s

  [8675/17668] intraday_16978.csv.gz  in=314,768,166 out=95,045,264 elapsed=141.4s

  [8676/17668] intraday_16977.csv.gz  in=314,780,368 out=95,057,466 elapsed=141.4s

  [8677/17668] intraday_16979.csv.gz  in=314,792,465 out=95,069,563 elapsed=141.4s

  [8678/17668] intraday_1698.csv.gz  in=314,807,588 out=95,069,563 elapsed=141.4s

  [8679/17668] intraday_16980.csv.gz  in=314,818,979 out=95,080,954 elapsed=141.5s

  [8680/17668] intraday_16982.csv.gz  in=314,831,882 out=95,093,857 elapsed=141.5s

  [8681/17668] intraday_16983.csv.gz  in=314,850,111 out=95,112,086 elapsed=141.5s

  [8682/17668] intraday_16981.csv.gz  in=314,864,453 out=95,126,428 elapsed=141.6s

  [8683/17668] intraday_16984.csv.gz  in=314,877,640 out=95,139,615 elapsed=141.6s

  [8684/17668] intraday_16985.csv.gz  in=314,889,874 out=95,151,849 elapsed=141.6s

  [8685/17668] intraday_16986.csv.gz  in=314,903,053 out=95,165,028 elapsed=141.6s

  [8686/17668] intraday_16987.csv.gz  in=314,917,782 out=95,179,757 elapsed=141.6s

  [8687/17668] intraday_16989.csv.gz  in=314,931,669 out=95,193,644 elapsed=141.6s

  [8688/17668] intraday_16988.csv.gz  in=314,945,351 out=95,207,326 elapsed=141.6s

  [8689/17668] intraday_1699.csv.gz  in=314,957,360 out=95,207,326 elapsed=141.6s

  [8690/17668] intraday_16990.csv.gz  in=314,968,781 out=95,218,747 elapsed=141.6s

  [8691/17668] intraday_16992.csv.gz  in=314,983,199 out=95,233,165 elapsed=141.7s

  [8692/17668] intraday_16991.csv.gz  in=314,993,867 out=95,243,833 elapsed=141.7s

  [8693/17668] intraday_16994.csv.gz  in=315,005,570 out=95,255,536 elapsed=141.7s

  [8694/17668] intraday_16993.csv.gz  in=315,018,274 out=95,268,240 elapsed=141.7s

  [8695/17668] intraday_16995.csv.gz  in=315,037,906 out=95,287,655 elapsed=141.7s

  [8696/17668] intraday_16996.csv.gz  in=315,050,497 out=95,300,246 elapsed=141.7s

  [8697/17668] intraday_16997.csv.gz  in=315,063,842 out=95,313,591 elapsed=141.7s

  [8698/17668] intraday_16998.csv.gz  in=315,074,911 out=95,324,660 elapsed=141.7s

  [8699/17668] intraday_16999.csv.gz  in=315,086,981 out=95,336,730 elapsed=141.8s

  [8700/17668] intraday_17000.csv.gz  in=315,099,747 out=95,349,496 elapsed=141.8s

  [8701/17668] intraday_1700.csv.gz  in=315,126,388 out=95,349,496 elapsed=141.8s

  [8702/17668] intraday_17001.csv.gz  in=315,138,092 out=95,361,200 elapsed=141.8s

  [8703/17668] intraday_17002.csv.gz  in=315,151,105 out=95,374,213 elapsed=141.8s

  [8704/17668] intraday_17003.csv.gz  in=315,166,206 out=95,389,103 elapsed=141.8s

  [8705/17668] intraday_17004.csv.gz  in=315,182,419 out=95,404,990 elapsed=141.9s

  [8706/17668] intraday_17005.csv.gz  in=315,195,946 out=95,418,517 elapsed=141.9s

  [8707/17668] intraday_17006.csv.gz  in=315,209,694 out=95,432,265 elapsed=141.9s

  [8708/17668] intraday_17007.csv.gz  in=315,225,131 out=95,447,702 elapsed=141.9s

  [8709/17668] intraday_17009.csv.gz  in=315,234,988 out=95,457,559 elapsed=141.9s

  [8710/17668] intraday_17008.csv.gz  in=315,248,204 out=95,470,775 elapsed=141.9s

  [8711/17668] intraday_1701.csv.gz  in=315,259,395 out=95,470,775 elapsed=141.9s

  [8712/17668] intraday_17010.csv.gz  in=315,271,321 out=95,482,701 elapsed=141.9s

  [8713/17668] intraday_17013.csv.gz  in=315,283,558 out=95,494,938 elapsed=142.0s

  [8714/17668] intraday_17014.csv.gz  in=315,294,272 out=95,505,652 elapsed=142.0s

  [8715/17668] intraday_17011.csv.gz  in=315,307,163 out=95,518,543 elapsed=142.0s

  [8716/17668] intraday_17012.csv.gz  in=315,321,143 out=95,532,523 elapsed=142.0s

  [8717/17668] intraday_17015.csv.gz  in=315,333,440 out=95,544,820 elapsed=142.1s

  [8718/17668] intraday_17016.csv.gz  in=315,343,880 out=95,555,260 elapsed=142.1s

  [8719/17668] intraday_17017.csv.gz  in=315,361,636 out=95,573,016 elapsed=142.1s

  [8720/17668] intraday_17019.csv.gz  in=315,373,754 out=95,585,134 elapsed=142.1s

  [8721/17668] intraday_17018.csv.gz  in=315,388,048 out=95,599,428 elapsed=142.1s

  [8722/17668] intraday_1702.csv.gz  in=315,400,213 out=95,599,428 elapsed=142.1s

  [8723/17668] intraday_17020.csv.gz  in=315,413,401 out=95,612,616 elapsed=142.1s

  [8724/17668] intraday_17022.csv.gz  in=315,421,655 out=95,620,870 elapsed=142.1s

  [8725/17668] intraday_17023.csv.gz  in=315,434,632 out=95,633,847 elapsed=142.2s

  [8726/17668] intraday_17021.csv.gz  in=315,446,526 out=95,645,741 elapsed=142.2s

  [8727/17668] intraday_17024.csv.gz  in=315,460,020 out=95,659,235 elapsed=142.2s

  [8728/17668] intraday_17025.csv.gz  in=315,472,848 out=95,672,063 elapsed=142.2s

  [8729/17668] intraday_17026.csv.gz  in=315,483,587 out=95,682,802 elapsed=142.2s

  [8730/17668] intraday_17027.csv.gz  in=315,496,301 out=95,695,516 elapsed=142.2s

  [8731/17668] intraday_17028.csv.gz  in=315,506,556 out=95,705,771 elapsed=142.2s

  [8732/17668] intraday_17029.csv.gz  in=315,518,225 out=95,717,440 elapsed=142.3s

  [8733/17668] intraday_1703.csv.gz  in=315,530,255 out=95,717,440 elapsed=142.3s

  [8734/17668] intraday_17030.csv.gz  in=315,544,293 out=95,731,478 elapsed=142.3s

  [8735/17668] intraday_17031.csv.gz  in=315,557,394 out=95,744,579 elapsed=142.3s

  [8736/17668] intraday_17033.csv.gz  in=315,567,211 out=95,754,396 elapsed=142.3s

  [8737/17668] intraday_17032.csv.gz  in=315,581,182 out=95,768,367 elapsed=142.3s

  [8738/17668] intraday_17034.csv.gz  in=315,592,588 out=95,779,773 elapsed=142.3s

  [8739/17668] intraday_17035.csv.gz  in=315,607,058 out=95,794,243 elapsed=142.3s

  [8740/17668] intraday_17037.csv.gz  in=315,619,534 out=95,806,719 elapsed=142.3s

  [8741/17668] intraday_17036.csv.gz  in=315,638,425 out=95,825,610 elapsed=142.4s

  [8742/17668] intraday_17039.csv.gz  in=315,651,014 out=95,838,199 elapsed=142.4s

  [8743/17668] intraday_1704.csv.gz  in=315,661,451 out=95,838,199 elapsed=142.4s

  [8744/17668] intraday_17038.csv.gz  in=315,676,394 out=95,853,142 elapsed=142.4s

  [8745/17668] intraday_17040.csv.gz  in=315,690,079 out=95,866,827 elapsed=142.4s

  [8746/17668] intraday_17041.csv.gz  in=315,700,906 out=95,877,654 elapsed=142.4s

  [8747/17668] intraday_17043.csv.gz  in=315,711,484 out=95,888,232 elapsed=142.4s

  [8748/17668] intraday_17042.csv.gz  in=315,727,054 out=95,903,802 elapsed=142.5s

  [8749/17668] intraday_17045.csv.gz  in=315,738,631 out=95,915,379 elapsed=142.5s

  [8750/17668] intraday_17046.csv.gz  in=315,750,601 out=95,927,349 elapsed=142.5s

  [8751/17668] intraday_17044.csv.gz  in=315,763,788 out=95,940,536 elapsed=142.5s

  [8752/17668] intraday_17048.csv.gz  in=315,775,200 out=95,951,948 elapsed=142.5s

  [8753/17668] intraday_17047.csv.gz  in=315,789,540 out=95,966,218 elapsed=142.5s

  [8754/17668] intraday_17049.csv.gz  in=315,803,294 out=95,979,972 elapsed=142.5s

  [8755/17668] intraday_1705.csv.gz  in=315,812,907 out=95,979,972 elapsed=142.5s

  [8756/17668] intraday_17050.csv.gz  in=315,826,586 out=95,993,651 elapsed=142.5s

  [8757/17668] intraday_17051.csv.gz  in=315,836,499 out=96,003,564 elapsed=142.6s

  [8758/17668] intraday_17053.csv.gz  in=315,848,567 out=96,015,632 elapsed=142.6s

  [8759/17668] intraday_17052.csv.gz  in=315,860,789 out=96,027,854 elapsed=142.6s

  [8760/17668] intraday_17054.csv.gz  in=315,873,791 out=96,040,856 elapsed=142.6s

  [8761/17668] intraday_17055.csv.gz  in=315,889,999 out=96,057,064 elapsed=142.6s

  [8762/17668] intraday_17056.csv.gz  in=315,903,681 out=96,070,746 elapsed=142.6s

  [8763/17668] intraday_17057.csv.gz  in=315,915,240 out=96,082,305 elapsed=142.6s

  [8764/17668] intraday_17058.csv.gz  in=315,929,940 out=96,097,005 elapsed=142.6s

  [8765/17668] intraday_1706.csv.gz  in=315,944,794 out=96,097,005 elapsed=142.6s

  [8766/17668] intraday_17059.csv.gz  in=315,957,241 out=96,109,452 elapsed=142.6s

  [8767/17668] intraday_17060.csv.gz  in=315,968,993 out=96,121,204 elapsed=142.7s

  [8768/17668] intraday_17061.csv.gz  in=315,982,713 out=96,134,924 elapsed=142.7s

  [8769/17668] intraday_17062.csv.gz  in=315,997,153 out=96,149,364 elapsed=142.7s

  [8770/17668] intraday_17064.csv.gz  in=316,008,279 out=96,160,490 elapsed=142.7s

  [8771/17668] intraday_17063.csv.gz  in=316,022,928 out=96,175,139 elapsed=142.7s

  [8772/17668] intraday_17065.csv.gz  in=316,036,842 out=96,189,053 elapsed=142.7s

  [8773/17668] intraday_17066.csv.gz  in=316,050,603 out=96,202,814 elapsed=142.7s

  [8774/17668] intraday_17068.csv.gz  in=316,066,511 out=96,218,722 elapsed=142.8s

  [8775/17668] intraday_17069.csv.gz  in=316,091,565 out=96,243,776 elapsed=142.8s

  [8776/17668] intraday_1707.csv.gz  in=316,102,723 out=96,243,776 elapsed=142.8s

  [8777/17668] intraday_17067.csv.gz  in=316,117,937 out=96,258,990 elapsed=142.8s

  [8778/17668] intraday_17070.csv.gz  in=316,130,367 out=96,271,420 elapsed=142.8s

  [8779/17668] intraday_17074.csv.gz  in=316,140,685 out=96,281,738 elapsed=142.9s

  [8780/17668] intraday_17072.csv.gz  in=316,153,049 out=96,294,102 elapsed=142.9s

  [8781/17668] intraday_17071.csv.gz  in=316,170,816 out=96,311,869 elapsed=142.9s

  [8782/17668] intraday_17073.csv.gz  in=316,200,768 out=96,340,687 elapsed=142.9s

  [8783/17668] intraday_17075.csv.gz  in=316,213,982 out=96,353,901 elapsed=142.9s

  [8784/17668] intraday_17076.csv.gz  in=316,225,021 out=96,364,940 elapsed=142.9s

  [8785/17668] intraday_17077.csv.gz  in=316,237,939 out=96,377,858 elapsed=142.9s

  [8786/17668] intraday_17078.csv.gz  in=316,250,525 out=96,390,444 elapsed=143.0s

  [8787/17668] intraday_17079.csv.gz  in=316,266,200 out=96,406,119 elapsed=143.0s

  [8788/17668] intraday_1708.csv.gz  in=316,277,653 out=96,406,119 elapsed=143.0s

  [8789/17668] intraday_17081.csv.gz  in=316,289,619 out=96,418,085 elapsed=143.0s

  [8790/17668] intraday_17080.csv.gz  in=316,300,832 out=96,429,298 elapsed=143.0s

  [8791/17668] intraday_17082.csv.gz  in=316,312,140 out=96,440,606 elapsed=143.0s

  [8792/17668] intraday_17083.csv.gz  in=316,326,827 out=96,455,293 elapsed=143.0s

  [8793/17668] intraday_17085.csv.gz  in=316,342,711 out=96,471,177 elapsed=143.1s

  [8794/17668] intraday_17084.csv.gz  in=316,354,713 out=96,483,179 elapsed=143.1s

  [8795/17668] intraday_17086.csv.gz  in=316,368,493 out=96,496,959 elapsed=143.1s

  [8796/17668] intraday_17087.csv.gz  in=316,383,707 out=96,512,173 elapsed=143.1s

  [8797/17668] intraday_1709.csv.gz  in=316,395,540 out=96,512,173 elapsed=143.1s

  [8798/17668] intraday_17088.csv.gz  in=316,410,404 out=96,527,037 elapsed=143.1s

  [8799/17668] intraday_17089.csv.gz  in=316,422,121 out=96,538,754 elapsed=143.1s

  [8800/17668] intraday_17090.csv.gz  in=316,435,065 out=96,551,698 elapsed=143.1s

  [8801/17668] intraday_17091.csv.gz  in=316,447,568 out=96,564,201 elapsed=143.1s

  [8802/17668] intraday_17093.csv.gz  in=316,460,498 out=96,577,131 elapsed=143.2s

  [8803/17668] intraday_17094.csv.gz  in=316,470,789 out=96,587,422 elapsed=143.2s

  [8804/17668] intraday_17095.csv.gz  in=316,480,279 out=96,596,912 elapsed=143.2s

  [8805/17668] intraday_17092.csv.gz  in=316,490,271 out=96,606,904 elapsed=143.2s

  [8806/17668] intraday_17096.csv.gz  in=316,501,184 out=96,617,817 elapsed=143.2s

  [8807/17668] intraday_17097.csv.gz  in=316,517,280 out=96,633,913 elapsed=143.2s

  [8808/17668] intraday_17098.csv.gz  in=316,530,376 out=96,647,009 elapsed=143.3s

  [8809/17668] intraday_17099.csv.gz  in=316,544,204 out=96,660,837 elapsed=143.3s

  [8810/17668] intraday_1710.csv.gz  in=316,556,889 out=96,660,837 elapsed=143.3s

  [8811/17668] intraday_17100.csv.gz  in=316,567,183 out=96,671,131 elapsed=143.3s

  [8812/17668] intraday_17101.csv.gz  in=316,580,467 out=96,684,415 elapsed=143.3s

  [8813/17668] intraday_17103.csv.gz  in=316,593,613 out=96,697,561 elapsed=143.3s

  [8814/17668] intraday_17102.csv.gz  in=316,609,362 out=96,713,310 elapsed=143.3s

  [8815/17668] intraday_17105.csv.gz  in=316,621,590 out=96,725,538 elapsed=143.3s

  [8816/17668] intraday_17104.csv.gz  in=316,633,356 out=96,737,304 elapsed=143.6s

  [8817/17668] intraday_17106.csv.gz  in=316,647,113 out=96,751,061 elapsed=143.6s

  [8818/17668] intraday_17107.csv.gz  in=316,657,682 out=96,761,630 elapsed=143.6s

  [8819/17668] intraday_17108.csv.gz  in=316,670,789 out=96,774,737 elapsed=143.6s

  [8820/17668] intraday_1711.csv.gz  in=316,690,214 out=96,774,737 elapsed=143.6s

  [8821/17668] intraday_17109.csv.gz  in=316,704,239 out=96,788,762 elapsed=143.6s

  [8822/17668] intraday_17111.csv.gz  in=316,714,952 out=96,799,475 elapsed=143.6s

  [8823/17668] intraday_17110.csv.gz  in=316,727,692 out=96,812,215 elapsed=143.6s

  [8824/17668] intraday_17113.csv.gz  in=316,742,994 out=96,827,517 elapsed=143.7s

  [8825/17668] intraday_17112.csv.gz  in=316,755,073 out=96,839,596 elapsed=143.7s

  [8826/17668] intraday_17115.csv.gz  in=316,766,371 out=96,850,894 elapsed=143.7s

  [8827/17668] intraday_17114.csv.gz  in=316,780,754 out=96,865,277 elapsed=143.7s

  [8828/17668] intraday_17116.csv.gz  in=316,791,377 out=96,875,900 elapsed=143.7s

  [8829/17668] intraday_17118.csv.gz  in=316,804,128 out=96,888,651 elapsed=143.7s

  [8830/17668] intraday_1712.csv.gz  in=316,816,040 out=96,888,651 elapsed=143.8s

  [8831/17668] intraday_17117.csv.gz  in=316,830,109 out=96,902,720 elapsed=143.8s

  [8832/17668] intraday_17119.csv.gz  in=316,842,569 out=96,915,180 elapsed=143.8s

  [8833/17668] intraday_17121.csv.gz  in=316,854,664 out=96,927,275 elapsed=143.8s

  [8834/17668] intraday_17123.csv.gz  in=316,866,930 out=96,939,541 elapsed=143.8s

  [8835/17668] intraday_17120.csv.gz  in=316,879,653 out=96,952,264 elapsed=143.8s

  [8836/17668] intraday_17122.csv.gz  in=316,891,303 out=96,963,914 elapsed=143.8s

  [8837/17668] intraday_17124.csv.gz  in=316,902,471 out=96,975,082 elapsed=143.8s

  [8838/17668] intraday_17125.csv.gz  in=316,917,247 out=96,989,858 elapsed=143.9s

  [8839/17668] intraday_17126.csv.gz  in=316,932,390 out=97,005,001 elapsed=143.9s

  [8840/17668] intraday_17128.csv.gz  in=316,945,268 out=97,017,879 elapsed=143.9s

  [8841/17668] intraday_17129.csv.gz  in=316,957,288 out=97,029,899 elapsed=143.9s

  [8842/17668] intraday_17127.csv.gz  in=316,971,662 out=97,044,273 elapsed=143.9s

  [8843/17668] intraday_1713.csv.gz  in=316,984,613 out=97,044,273 elapsed=143.9s

  [8844/17668] intraday_17130.csv.gz  in=316,999,622 out=97,059,282 elapsed=144.0s

  [8845/17668] intraday_17131.csv.gz  in=317,013,275 out=97,072,935 elapsed=144.0s

  [8846/17668] intraday_17133.csv.gz  in=317,025,921 out=97,085,581 elapsed=144.0s

  [8847/17668] intraday_17134.csv.gz  in=317,036,892 out=97,096,552 elapsed=144.0s

  [8848/17668] intraday_17132.csv.gz  in=317,050,786 out=97,110,446 elapsed=144.0s

  [8849/17668] intraday_17135.csv.gz  in=317,061,575 out=97,121,235 elapsed=144.0s

  [8850/17668] intraday_17136.csv.gz  in=317,072,651 out=97,132,311 elapsed=144.0s

  [8851/17668] intraday_17138.csv.gz  in=317,085,748 out=97,145,408 elapsed=144.0s

  [8852/17668] intraday_17137.csv.gz  in=317,097,631 out=97,157,291 elapsed=144.0s

  [8853/17668] intraday_1714.csv.gz  in=317,108,567 out=97,157,291 elapsed=144.0s

  [8854/17668] intraday_17139.csv.gz  in=317,122,947 out=97,171,671 elapsed=144.1s

  [8855/17668] intraday_17140.csv.gz  in=317,136,553 out=97,185,277 elapsed=144.1s

  [8856/17668] intraday_17142.csv.gz  in=317,147,772 out=97,196,496 elapsed=144.1s

  [8857/17668] intraday_17141.csv.gz  in=317,162,114 out=97,210,838 elapsed=144.1s

  [8858/17668] intraday_17143.csv.gz  in=317,174,161 out=97,222,885 elapsed=144.1s

  [8859/17668] intraday_17144.csv.gz  in=317,187,456 out=97,236,180 elapsed=144.1s

  [8860/17668] intraday_17145.csv.gz  in=317,199,121 out=97,247,845 elapsed=144.1s

  [8861/17668] intraday_17146.csv.gz  in=317,211,293 out=97,260,017 elapsed=144.2s

  [8862/17668] intraday_17147.csv.gz  in=317,222,898 out=97,271,622 elapsed=144.2s

  [8863/17668] intraday_17148.csv.gz  in=317,237,622 out=97,286,346 elapsed=144.2s

  [8864/17668] intraday_17149.csv.gz  in=317,250,662 out=97,299,386 elapsed=144.2s

  [8865/17668] intraday_1715.csv.gz  in=317,263,920 out=97,299,386 elapsed=144.2s

  [8866/17668] intraday_17152.csv.gz  in=317,276,320 out=97,311,786 elapsed=144.2s

  [8867/17668] intraday_17150.csv.gz  in=317,289,919 out=97,325,385 elapsed=144.3s

  [8868/17668] intraday_17153.csv.gz  in=317,302,132 out=97,337,598 elapsed=144.3s

  [8869/17668] intraday_17151.csv.gz  in=317,317,348 out=97,352,814 elapsed=144.3s

  [8870/17668] intraday_17154.csv.gz  in=317,329,170 out=97,364,636 elapsed=144.3s

  [8871/17668] intraday_17155.csv.gz  in=317,341,875 out=97,377,341 elapsed=144.3s

  [8872/17668] intraday_17158.csv.gz  in=317,352,667 out=97,388,133 elapsed=144.3s

  [8873/17668] intraday_17157.csv.gz  in=317,366,058 out=97,401,524 elapsed=144.3s

  [8874/17668] intraday_17156.csv.gz  in=317,377,975 out=97,413,441 elapsed=144.3s

  [8875/17668] intraday_17159.csv.gz  in=317,390,342 out=97,425,808 elapsed=144.4s

  [8876/17668] intraday_1716.csv.gz  in=317,401,618 out=97,425,808 elapsed=144.4s

  [8877/17668] intraday_17160.csv.gz  in=317,412,332 out=97,436,522 elapsed=144.4s

  [8878/17668] intraday_17161.csv.gz  in=317,428,130 out=97,452,320 elapsed=144.4s

  [8879/17668] intraday_17162.csv.gz  in=317,440,582 out=97,464,772 elapsed=144.4s

  [8880/17668] intraday_17163.csv.gz  in=317,454,534 out=97,478,724 elapsed=144.4s

  [8881/17668] intraday_17164.csv.gz  in=317,467,686 out=97,491,876 elapsed=144.4s

  [8882/17668] intraday_17165.csv.gz  in=317,478,877 out=97,503,067 elapsed=144.5s

  [8883/17668] intraday_17166.csv.gz  in=317,488,664 out=97,512,854 elapsed=144.5s

  [8884/17668] intraday_17167.csv.gz  in=317,500,716 out=97,524,906 elapsed=144.5s

  [8885/17668] intraday_17168.csv.gz  in=317,514,596 out=97,538,786 elapsed=144.5s

  [8886/17668] intraday_17169.csv.gz  in=317,526,929 out=97,551,119 elapsed=144.5s

  [8887/17668] intraday_1717.csv.gz  in=317,537,307 out=97,551,119 elapsed=144.5s

  [8888/17668] intraday_17170.csv.gz  in=317,548,954 out=97,562,766 elapsed=144.5s

  [8889/17668] intraday_17171.csv.gz  in=317,560,944 out=97,574,756 elapsed=144.6s

  [8890/17668] intraday_17173.csv.gz  in=317,575,439 out=97,589,251 elapsed=144.6s

  [8891/17668] intraday_17172.csv.gz  in=317,585,580 out=97,599,392 elapsed=144.6s

  [8892/17668] intraday_17174.csv.gz  in=317,599,739 out=97,613,551 elapsed=144.6s

  [8893/17668] intraday_17175.csv.gz  in=317,613,417 out=97,627,229 elapsed=144.6s

  [8894/17668] intraday_17176.csv.gz  in=317,623,742 out=97,637,554 elapsed=144.6s

  [8895/17668] intraday_17177.csv.gz  in=317,634,855 out=97,648,667 elapsed=144.6s

  [8896/17668] intraday_17178.csv.gz  in=317,649,089 out=97,662,901 elapsed=144.6s

  [8897/17668] intraday_17179.csv.gz  in=317,664,069 out=97,677,881 elapsed=144.7s

  [8898/17668] intraday_1718.csv.gz  in=317,679,569 out=97,677,881 elapsed=144.7s

  [8899/17668] intraday_17180.csv.gz  in=317,695,120 out=97,693,432 elapsed=144.7s

  [8900/17668] intraday_17181.csv.gz  in=317,708,439 out=97,706,751 elapsed=144.7s

  [8901/17668] intraday_17183.csv.gz  in=317,721,107 out=97,719,419 elapsed=144.7s

  [8902/17668] intraday_17182.csv.gz  in=317,734,308 out=97,732,620 elapsed=144.7s

  [8903/17668] intraday_17184.csv.gz  in=317,746,072 out=97,744,384 elapsed=144.7s

  [8904/17668] intraday_17185.csv.gz  in=317,762,004 out=97,760,316 elapsed=144.7s

  [8905/17668] intraday_17186.csv.gz  in=317,773,942 out=97,772,254 elapsed=144.7s

  [8906/17668] intraday_17187.csv.gz  in=317,785,583 out=97,783,895 elapsed=144.7s

  [8907/17668] intraday_17188.csv.gz  in=317,799,690 out=97,798,002 elapsed=144.7s

  [8908/17668] intraday_17189.csv.gz  in=317,811,298 out=97,809,610 elapsed=144.8s

  [8909/17668] intraday_1719.csv.gz  in=317,824,437 out=97,809,610 elapsed=144.8s

  [8910/17668] intraday_17190.csv.gz  in=317,837,802 out=97,822,975 elapsed=144.8s

  [8911/17668] intraday_17191.csv.gz  in=317,850,540 out=97,835,713 elapsed=144.8s

  [8912/17668] intraday_17192.csv.gz  in=317,863,517 out=97,848,690 elapsed=144.8s

  [8913/17668] intraday_17193.csv.gz  in=317,875,864 out=97,861,037 elapsed=144.8s

  [8914/17668] intraday_17195.csv.gz  in=317,887,127 out=97,872,300 elapsed=144.9s

  [8915/17668] intraday_17194.csv.gz  in=317,898,108 out=97,883,281 elapsed=144.9s

  [8916/17668] intraday_17196.csv.gz  in=317,909,814 out=97,894,987 elapsed=144.9s

  [8917/17668] intraday_17197.csv.gz  in=317,922,822 out=97,907,995 elapsed=144.9s

  [8918/17668] intraday_17198.csv.gz  in=317,937,085 out=97,922,258 elapsed=144.9s

  [8919/17668] intraday_1720.csv.gz  in=317,949,659 out=97,922,258 elapsed=144.9s

  [8920/17668] intraday_17199.csv.gz  in=317,964,967 out=97,937,566 elapsed=144.9s

  [8921/17668] intraday_17200.csv.gz  in=317,977,315 out=97,949,914 elapsed=144.9s

  [8922/17668] intraday_17201.csv.gz  in=317,990,702 out=97,963,301 elapsed=145.0s

  [8923/17668] intraday_17203.csv.gz  in=318,001,970 out=97,974,569 elapsed=145.0s

  [8924/17668] intraday_17202.csv.gz  in=318,015,552 out=97,988,151 elapsed=145.0s

  [8925/17668] intraday_17204.csv.gz  in=318,028,843 out=98,001,442 elapsed=145.0s

  [8926/17668] intraday_17205.csv.gz  in=318,042,004 out=98,014,603 elapsed=145.0s

  [8927/17668] intraday_17206.csv.gz  in=318,057,449 out=98,030,048 elapsed=145.0s

  [8928/17668] intraday_17207.csv.gz  in=318,069,507 out=98,042,106 elapsed=145.0s

  [8929/17668] intraday_17208.csv.gz  in=318,083,831 out=98,056,430 elapsed=145.1s

  [8930/17668] intraday_17209.csv.gz  in=318,098,106 out=98,070,705 elapsed=145.1s

  [8931/17668] intraday_1721.csv.gz  in=318,112,321 out=98,070,705 elapsed=145.1s

  [8932/17668] intraday_17210.csv.gz  in=318,125,678 out=98,084,062 elapsed=145.1s

  [8933/17668] intraday_17213.csv.gz  in=318,139,689 out=98,098,073 elapsed=145.1s

  [8934/17668] intraday_17211.csv.gz  in=318,154,819 out=98,113,203 elapsed=145.1s

  [8935/17668] intraday_17212.csv.gz  in=318,172,458 out=98,130,842 elapsed=145.1s

  [8936/17668] intraday_17214.csv.gz  in=318,188,995 out=98,147,379 elapsed=145.1s

  [8937/17668] intraday_17216.csv.gz  in=318,201,525 out=98,159,909 elapsed=145.1s

  [8938/17668] intraday_17215.csv.gz  in=318,215,645 out=98,174,029 elapsed=145.2s

  [8939/17668] intraday_17217.csv.gz  in=318,227,850 out=98,186,234 elapsed=145.2s

  [8940/17668] intraday_17218.csv.gz  in=318,239,015 out=98,197,399 elapsed=145.2s

  [8941/17668] intraday_1722.csv.gz  in=318,252,251 out=98,197,399 elapsed=145.2s

  [8942/17668] intraday_17219.csv.gz  in=318,264,232 out=98,209,380 elapsed=145.2s

  [8943/17668] intraday_17220.csv.gz  in=318,276,355 out=98,221,503 elapsed=145.2s

  [8944/17668] intraday_17221.csv.gz  in=318,290,113 out=98,235,261 elapsed=145.2s

  [8945/17668] intraday_17222.csv.gz  in=318,304,545 out=98,249,693 elapsed=145.2s

  [8946/17668] intraday_17223.csv.gz  in=318,317,549 out=98,262,697 elapsed=145.3s

  [8947/17668] intraday_17225.csv.gz  in=318,329,873 out=98,275,021 elapsed=145.3s

  [8948/17668] intraday_17224.csv.gz  in=318,342,112 out=98,287,260 elapsed=145.3s

  [8949/17668] intraday_17227.csv.gz  in=318,354,423 out=98,299,571 elapsed=145.3s

  [8950/17668] intraday_17226.csv.gz  in=318,366,795 out=98,311,943 elapsed=145.3s

  [8951/17668] intraday_17228.csv.gz  in=318,380,963 out=98,326,111 elapsed=145.3s

  [8952/17668] intraday_17229.csv.gz  in=318,395,799 out=98,340,947 elapsed=145.3s

  [8953/17668] intraday_1723.csv.gz  in=318,404,945 out=98,340,947 elapsed=145.3s

  [8954/17668] intraday_17230.csv.gz  in=318,419,676 out=98,355,678 elapsed=145.3s

  [8955/17668] intraday_17231.csv.gz  in=318,433,812 out=98,369,814 elapsed=145.4s

  [8956/17668] intraday_17232.csv.gz  in=318,445,565 out=98,381,567 elapsed=145.4s

  [8957/17668] intraday_17233.csv.gz  in=318,458,882 out=98,394,884 elapsed=145.4s

  [8958/17668] intraday_17234.csv.gz  in=318,471,393 out=98,407,395 elapsed=145.4s

  [8959/17668] intraday_17235.csv.gz  in=318,481,841 out=98,417,843 elapsed=145.4s

  [8960/17668] intraday_17236.csv.gz  in=318,495,344 out=98,431,346 elapsed=145.4s

  [8961/17668] intraday_17238.csv.gz  in=318,504,340 out=98,440,342 elapsed=145.4s

  [8962/17668] intraday_17237.csv.gz  in=318,514,788 out=98,450,790 elapsed=145.4s

  [8963/17668] intraday_17239.csv.gz  in=318,528,575 out=98,464,577 elapsed=145.4s

  [8964/17668] intraday_1724.csv.gz  in=318,540,677 out=98,464,577 elapsed=145.4s

  [8965/17668] intraday_17240.csv.gz  in=318,556,376 out=98,480,276 elapsed=145.5s

  [8966/17668] intraday_17241.csv.gz  in=318,571,111 out=98,495,011 elapsed=145.5s

  [8967/17668] intraday_17243.csv.gz  in=318,581,465 out=98,505,365 elapsed=145.5s

  [8968/17668] intraday_17244.csv.gz  in=318,595,111 out=98,519,011 elapsed=145.5s

  [8969/17668] intraday_17242.csv.gz  in=318,606,594 out=98,530,494 elapsed=145.5s

  [8970/17668] intraday_17245.csv.gz  in=318,621,182 out=98,545,082 elapsed=145.5s

  [8971/17668] intraday_17246.csv.gz  in=318,633,657 out=98,557,557 elapsed=145.5s

  [8972/17668] intraday_17247.csv.gz  in=318,646,178 out=98,570,078 elapsed=145.6s

  [8973/17668] intraday_17248.csv.gz  in=318,658,260 out=98,582,160 elapsed=145.6s

  [8974/17668] intraday_17249.csv.gz  in=318,672,515 out=98,596,415 elapsed=145.6s

  [8975/17668] intraday_1725.csv.gz  in=318,684,501 out=98,596,415 elapsed=145.6s

  [8976/17668] intraday_17250.csv.gz  in=318,693,971 out=98,605,885 elapsed=145.6s

  [8977/17668] intraday_17251.csv.gz  in=318,707,827 out=98,619,741 elapsed=145.6s

  [8978/17668] intraday_17252.csv.gz  in=318,722,776 out=98,634,690 elapsed=145.7s

  [8979/17668] intraday_17255.csv.gz  in=318,734,297 out=98,646,211 elapsed=145.7s

  [8980/17668] intraday_17254.csv.gz  in=318,744,840 out=98,656,754 elapsed=145.7s

  [8981/17668] intraday_17253.csv.gz  in=318,756,116 out=98,668,030 elapsed=145.7s

  [8982/17668] intraday_17256.csv.gz  in=318,772,071 out=98,683,985 elapsed=145.7s

  [8983/17668] intraday_17259.csv.gz  in=318,782,183 out=98,694,097 elapsed=145.7s

  [8984/17668] intraday_17257.csv.gz  in=318,795,844 out=98,707,758 elapsed=145.7s

  [8985/17668] intraday_1726.csv.gz  in=318,808,390 out=98,707,758 elapsed=145.7s

  [8986/17668] intraday_17258.csv.gz  in=318,819,009 out=98,718,377 elapsed=145.7s

  [8987/17668] intraday_17260.csv.gz  in=318,832,177 out=98,731,545 elapsed=145.7s

  [8988/17668] intraday_17262.csv.gz  in=318,845,500 out=98,744,868 elapsed=145.8s

  [8989/17668] intraday_17261.csv.gz  in=318,858,122 out=98,757,490 elapsed=145.8s

  [8990/17668] intraday_17263.csv.gz  in=318,871,667 out=98,770,914 elapsed=145.8s

  [8991/17668] intraday_17264.csv.gz  in=318,883,521 out=98,782,768 elapsed=145.8s

  [8992/17668] intraday_17265.csv.gz  in=318,894,546 out=98,793,793 elapsed=145.8s

  [8993/17668] intraday_17266.csv.gz  in=318,907,242 out=98,806,489 elapsed=145.8s

  [8994/17668] intraday_17267.csv.gz  in=318,917,546 out=98,816,793 elapsed=145.8s

  [8995/17668] intraday_17268.csv.gz  in=318,932,267 out=98,831,514 elapsed=145.8s

  [8996/17668] intraday_17269.csv.gz  in=318,945,589 out=98,844,836 elapsed=145.8s

  [8997/17668] intraday_1727.csv.gz  in=318,957,486 out=98,844,836 elapsed=145.8s

  [8998/17668] intraday_17270.csv.gz  in=318,971,947 out=98,859,297 elapsed=145.9s

  [8999/17668] intraday_17271.csv.gz  in=318,984,619 out=98,871,969 elapsed=145.9s

  [9000/17668] intraday_17273.csv.gz  in=318,999,366 out=98,886,716 elapsed=145.9s

  [9001/17668] intraday_17272.csv.gz  in=319,021,820 out=98,908,676 elapsed=145.9s

  [9002/17668] intraday_17274.csv.gz  in=319,035,769 out=98,922,625 elapsed=145.9s

  [9003/17668] intraday_17276.csv.gz  in=319,047,841 out=98,934,697 elapsed=145.9s

  [9004/17668] intraday_17277.csv.gz  in=319,059,128 out=98,945,984 elapsed=146.0s

  [9005/17668] intraday_17275.csv.gz  in=319,071,980 out=98,958,836 elapsed=146.0s

  [9006/17668] intraday_17278.csv.gz  in=319,082,118 out=98,968,974 elapsed=146.0s

  [9007/17668] intraday_17279.csv.gz  in=319,093,760 out=98,980,616 elapsed=146.0s

  [9008/17668] intraday_1728.csv.gz  in=319,104,456 out=98,980,616 elapsed=146.0s

  [9009/17668] intraday_17280.csv.gz  in=319,115,916 out=98,992,076 elapsed=146.0s

  [9010/17668] intraday_17281.csv.gz  in=319,128,553 out=99,004,713 elapsed=146.0s

  [9011/17668] intraday_17282.csv.gz  in=319,142,507 out=99,018,667 elapsed=146.0s

  [9012/17668] intraday_17283.csv.gz  in=319,157,027 out=99,033,187 elapsed=146.0s

  [9013/17668] intraday_17284.csv.gz  in=319,170,078 out=99,046,238 elapsed=146.1s

  [9014/17668] intraday_17285.csv.gz  in=319,181,225 out=99,057,385 elapsed=146.1s

  [9015/17668] intraday_17286.csv.gz  in=319,192,422 out=99,068,582 elapsed=146.1s

  [9016/17668] intraday_17287.csv.gz  in=319,205,602 out=99,081,762 elapsed=146.1s

  [9017/17668] intraday_17288.csv.gz  in=319,217,117 out=99,093,277 elapsed=146.1s

  [9018/17668] intraday_17289.csv.gz  in=319,229,622 out=99,105,782 elapsed=146.1s

  [9019/17668] intraday_1729.csv.gz  in=319,241,738 out=99,105,782 elapsed=146.1s

  [9020/17668] intraday_17290.csv.gz  in=319,253,382 out=99,117,426 elapsed=146.1s

  [9021/17668] intraday_17292.csv.gz  in=319,265,972 out=99,130,016 elapsed=146.2s

  [9022/17668] intraday_17291.csv.gz  in=319,281,368 out=99,145,412 elapsed=146.2s

  [9023/17668] intraday_17293.csv.gz  in=319,294,725 out=99,158,769 elapsed=146.2s

  [9024/17668] intraday_17295.csv.gz  in=319,306,906 out=99,170,950 elapsed=146.2s

  [9025/17668] intraday_17294.csv.gz  in=319,322,118 out=99,186,162 elapsed=146.2s

  [9026/17668] intraday_17297.csv.gz  in=319,333,523 out=99,197,567 elapsed=146.2s

  [9027/17668] intraday_17296.csv.gz  in=319,346,230 out=99,210,274 elapsed=146.2s

  [9028/17668] intraday_17298.csv.gz  in=319,359,250 out=99,223,294 elapsed=146.2s

  [9029/17668] intraday_1730.csv.gz  in=319,370,526 out=99,223,294 elapsed=146.2s

  [9030/17668] intraday_17299.csv.gz  in=319,403,896 out=99,255,404 elapsed=146.3s

  [9031/17668] intraday_17300.csv.gz  in=319,417,836 out=99,269,344 elapsed=146.3s

  [9032/17668] intraday_17302.csv.gz  in=319,430,490 out=99,281,998 elapsed=146.3s

  [9033/17668] intraday_17301.csv.gz  in=319,441,234 out=99,292,742 elapsed=146.3s

  [9034/17668] intraday_17303.csv.gz  in=319,452,026 out=99,303,534 elapsed=146.3s

  [9035/17668] intraday_17304.csv.gz  in=319,468,414 out=99,319,922 elapsed=146.3s

  [9036/17668] intraday_17305.csv.gz  in=319,480,571 out=99,332,079 elapsed=146.3s

  [9037/17668] intraday_17306.csv.gz  in=319,494,753 out=99,346,261 elapsed=146.3s

  [9038/17668] intraday_17307.csv.gz  in=319,509,531 out=99,361,039 elapsed=146.4s

  [9039/17668] intraday_1731.csv.gz  in=319,520,935 out=99,361,039 elapsed=146.4s

  [9040/17668] intraday_17309.csv.gz  in=319,530,812 out=99,370,916 elapsed=146.4s

  [9041/17668] intraday_17308.csv.gz  in=319,544,720 out=99,384,760 elapsed=146.4s

  [9042/17668] intraday_17310.csv.gz  in=319,558,325 out=99,398,365 elapsed=146.4s

  [9043/17668] intraday_17311.csv.gz  in=319,571,574 out=99,411,614 elapsed=146.4s

  [9044/17668] intraday_17312.csv.gz  in=319,583,374 out=99,423,414 elapsed=146.4s

  [9045/17668] intraday_17313.csv.gz  in=319,594,538 out=99,434,578 elapsed=146.4s

  [9046/17668] intraday_17314.csv.gz  in=319,605,226 out=99,445,266 elapsed=146.5s

  [9047/17668] intraday_17315.csv.gz  in=319,615,285 out=99,455,325 elapsed=146.5s

  [9048/17668] intraday_17317.csv.gz  in=319,627,574 out=99,467,614 elapsed=146.5s

  [9049/17668] intraday_17316.csv.gz  in=319,642,407 out=99,482,447 elapsed=146.5s

  [9050/17668] intraday_17318.csv.gz  in=319,655,941 out=99,495,981 elapsed=146.5s

  [9051/17668] intraday_17319.csv.gz  in=319,666,486 out=99,506,526 elapsed=146.5s

  [9052/17668] intraday_1732.csv.gz  in=319,678,589 out=99,506,526 elapsed=146.5s

  [9053/17668] intraday_17320.csv.gz  in=319,689,734 out=99,517,671 elapsed=146.5s

  [9054/17668] intraday_17321.csv.gz  in=319,702,815 out=99,530,752 elapsed=146.5s

  [9055/17668] intraday_17322.csv.gz  in=319,718,835 out=99,546,772 elapsed=146.5s

  [9056/17668] intraday_17323.csv.gz  in=319,733,648 out=99,561,585 elapsed=146.6s

  [9057/17668] intraday_17324.csv.gz  in=319,746,649 out=99,574,586 elapsed=146.6s

  [9058/17668] intraday_17325.csv.gz  in=319,759,290 out=99,587,227 elapsed=146.6s

  [9059/17668] intraday_17326.csv.gz  in=319,774,554 out=99,602,491 elapsed=146.6s

  [9060/17668] intraday_17327.csv.gz  in=319,783,884 out=99,611,821 elapsed=146.6s

  [9061/17668] intraday_17328.csv.gz  in=319,798,617 out=99,626,554 elapsed=146.6s

  [9062/17668] intraday_1733.csv.gz  in=319,811,604 out=99,626,554 elapsed=146.6s

  [9063/17668] intraday_17329.csv.gz  in=319,821,859 out=99,636,809 elapsed=146.6s

  [9064/17668] intraday_17330.csv.gz  in=319,834,203 out=99,649,153 elapsed=146.7s

  [9065/17668] intraday_17331.csv.gz  in=319,848,686 out=99,663,622 elapsed=146.7s

  [9066/17668] intraday_17332.csv.gz  in=319,859,609 out=99,674,545 elapsed=146.7s

  [9067/17668] intraday_17334.csv.gz  in=319,872,170 out=99,687,106 elapsed=146.7s

  [9068/17668] intraday_17333.csv.gz  in=319,885,635 out=99,700,571 elapsed=146.7s

  [9069/17668] intraday_17335.csv.gz  in=319,898,347 out=99,713,283 elapsed=146.7s

  [9070/17668] intraday_17337.csv.gz  in=319,909,168 out=99,724,104 elapsed=146.8s

  [9071/17668] intraday_17336.csv.gz  in=319,921,697 out=99,736,633 elapsed=146.8s

  [9072/17668] intraday_17339.csv.gz  in=319,932,972 out=99,747,908 elapsed=146.8s

  [9073/17668] intraday_17338.csv.gz  in=319,945,547 out=99,760,483 elapsed=146.8s

  [9074/17668] intraday_1734.csv.gz  in=319,955,637 out=99,760,483 elapsed=146.8s

  [9075/17668] intraday_17341.csv.gz  in=319,969,880 out=99,774,726 elapsed=146.8s

  [9076/17668] intraday_17340.csv.gz  in=319,983,306 out=99,788,152 elapsed=146.8s

  [9077/17668] intraday_17342.csv.gz  in=319,997,509 out=99,802,355 elapsed=146.8s

  [9078/17668] intraday_17343.csv.gz  in=320,008,994 out=99,813,840 elapsed=146.8s

  [9079/17668] intraday_17345.csv.gz  in=320,023,138 out=99,827,984 elapsed=146.8s

  [9080/17668] intraday_17344.csv.gz  in=320,037,084 out=99,841,930 elapsed=146.9s

  [9081/17668] intraday_17346.csv.gz  in=320,049,115 out=99,853,961 elapsed=146.9s

  [9082/17668] intraday_17347.csv.gz  in=320,062,498 out=99,867,344 elapsed=146.9s

  [9083/17668] intraday_17348.csv.gz  in=320,076,363 out=99,881,209 elapsed=146.9s

  [9084/17668] intraday_17349.csv.gz  in=320,090,761 out=99,895,607 elapsed=146.9s

  [9085/17668] intraday_1735.csv.gz  in=320,101,967 out=99,895,607 elapsed=146.9s

  [9086/17668] intraday_17350.csv.gz  in=320,113,299 out=99,906,939 elapsed=146.9s

  [9087/17668] intraday_17352.csv.gz  in=320,126,372 out=99,920,012 elapsed=147.0s

  [9088/17668] intraday_17353.csv.gz  in=320,140,459 out=99,934,099 elapsed=147.0s

  [9089/17668] intraday_17354.csv.gz  in=320,156,782 out=99,950,422 elapsed=147.0s

  [9090/17668] intraday_17351.csv.gz  in=320,170,766 out=99,964,406 elapsed=147.0s

  [9091/17668] intraday_17356.csv.gz  in=320,183,803 out=99,977,443 elapsed=147.0s

  [9092/17668] intraday_17355.csv.gz  in=320,202,709 out=99,996,349 elapsed=147.0s

  [9093/17668] intraday_17357.csv.gz  in=320,220,009 out=100,013,649 elapsed=147.0s

  [9094/17668] intraday_17358.csv.gz  in=320,232,020 out=100,025,660 elapsed=147.0s

  [9095/17668] intraday_1736.csv.gz  in=320,243,620 out=100,025,660 elapsed=147.0s

  [9096/17668] intraday_17359.csv.gz  in=320,256,641 out=100,038,681 elapsed=147.0s

  [9097/17668] intraday_17360.csv.gz  in=320,267,435 out=100,049,475 elapsed=147.1s

  [9098/17668] intraday_17361.csv.gz  in=320,280,397 out=100,062,437 elapsed=147.1s

  [9099/17668] intraday_17363.csv.gz  in=320,294,864 out=100,076,904 elapsed=147.1s

  [9100/17668] intraday_17362.csv.gz  in=320,305,055 out=100,087,095 elapsed=147.1s

  [9101/17668] intraday_17364.csv.gz  in=320,318,375 out=100,100,415 elapsed=147.1s

  [9102/17668] intraday_17365.csv.gz  in=320,332,597 out=100,114,637 elapsed=147.1s

  [9103/17668] intraday_17366.csv.gz  in=320,344,533 out=100,126,573 elapsed=147.2s

  [9104/17668] intraday_17367.csv.gz  in=320,356,239 out=100,138,279 elapsed=147.2s

  [9105/17668] intraday_17368.csv.gz  in=320,369,261 out=100,151,301 elapsed=147.2s

  [9106/17668] intraday_17369.csv.gz  in=320,382,841 out=100,164,881 elapsed=147.2s

  [9107/17668] intraday_1737.csv.gz  in=320,398,570 out=100,164,881 elapsed=147.2s

  [9108/17668] intraday_17370.csv.gz  in=320,409,851 out=100,176,162 elapsed=147.2s

  [9109/17668] intraday_17371.csv.gz  in=320,423,874 out=100,190,185 elapsed=147.2s

  [9110/17668] intraday_17372.csv.gz  in=320,438,526 out=100,204,837 elapsed=147.2s

  [9111/17668] intraday_17373.csv.gz  in=320,452,783 out=100,219,094 elapsed=147.2s

  [9112/17668] intraday_17375.csv.gz  in=320,463,365 out=100,229,676 elapsed=147.2s

  [9113/17668] intraday_17374.csv.gz  in=320,479,748 out=100,246,059 elapsed=147.2s

  [9114/17668] intraday_17377.csv.gz  in=320,491,699 out=100,258,010 elapsed=147.3s

  [9115/17668] intraday_17376.csv.gz  in=320,506,201 out=100,272,512 elapsed=147.3s

  [9116/17668] intraday_17378.csv.gz  in=320,516,915 out=100,283,226 elapsed=147.3s

  [9117/17668] intraday_17379.csv.gz  in=320,530,323 out=100,296,634 elapsed=147.3s

  [9118/17668] intraday_1738.csv.gz  in=320,541,375 out=100,296,634 elapsed=147.3s

  [9119/17668] intraday_17380.csv.gz  in=320,549,877 out=100,305,136 elapsed=147.3s

  [9120/17668] intraday_17382.csv.gz  in=320,556,940 out=100,312,199 elapsed=147.3s

  [9121/17668] intraday_17381.csv.gz  in=320,568,999 out=100,324,258 elapsed=147.4s

  [9122/17668] intraday_17384.csv.gz  in=320,583,285 out=100,338,544 elapsed=147.4s

  [9123/17668] intraday_17383.csv.gz  in=320,599,054 out=100,354,313 elapsed=147.4s

  [9124/17668] intraday_17386.csv.gz  in=320,609,913 out=100,365,172 elapsed=147.4s

  [9125/17668] intraday_17385.csv.gz  in=320,621,848 out=100,377,107 elapsed=147.4s

  [9126/17668] intraday_17387.csv.gz  in=320,635,176 out=100,390,435 elapsed=147.4s

  [9127/17668] intraday_1739.csv.gz  in=320,644,749 out=100,390,435 elapsed=147.4s

  [9128/17668] intraday_17389.csv.gz  in=320,657,787 out=100,403,473 elapsed=147.4s

  [9129/17668] intraday_17388.csv.gz  in=320,673,268 out=100,418,954 elapsed=147.5s

  [9130/17668] intraday_17390.csv.gz  in=320,684,652 out=100,430,338 elapsed=147.5s

  [9131/17668] intraday_17391.csv.gz  in=320,697,712 out=100,443,398 elapsed=147.5s

  [9132/17668] intraday_17392.csv.gz  in=320,712,122 out=100,457,808 elapsed=147.5s

  [9133/17668] intraday_17393.csv.gz  in=320,723,027 out=100,468,713 elapsed=147.5s

  [9134/17668] intraday_17394.csv.gz  in=320,740,608 out=100,486,197 elapsed=147.5s

  [9135/17668] intraday_17395.csv.gz  in=320,754,043 out=100,499,632 elapsed=147.5s

  [9136/17668] intraday_17397.csv.gz  in=320,765,423 out=100,511,012 elapsed=147.6s

  [9137/17668] intraday_17396.csv.gz  in=320,777,523 out=100,523,112 elapsed=147.6s

  [9138/17668] intraday_17398.csv.gz  in=320,789,313 out=100,534,902 elapsed=147.6s

  [9139/17668] intraday_1740.csv.gz  in=320,800,130 out=100,534,902 elapsed=147.6s

  [9140/17668] intraday_17399.csv.gz  in=320,815,518 out=100,550,290 elapsed=147.6s

  [9141/17668] intraday_17400.csv.gz  in=320,829,149 out=100,563,921 elapsed=147.6s

  [9142/17668] intraday_17401.csv.gz  in=320,839,647 out=100,574,419 elapsed=147.6s

  [9143/17668] intraday_17403.csv.gz  in=320,852,658 out=100,587,430 elapsed=147.6s

  [9144/17668] intraday_17402.csv.gz  in=320,863,573 out=100,598,345 elapsed=147.6s

  [9145/17668] intraday_17405.csv.gz  in=320,875,224 out=100,609,996 elapsed=147.7s

  [9146/17668] intraday_17404.csv.gz  in=320,887,819 out=100,622,591 elapsed=147.7s

  [9147/17668] intraday_17406.csv.gz  in=320,900,283 out=100,635,055 elapsed=147.7s

  [9148/17668] intraday_17408.csv.gz  in=320,911,540 out=100,646,312 elapsed=147.7s

  [9149/17668] intraday_17407.csv.gz  in=320,932,214 out=100,666,986 elapsed=147.7s

  [9150/17668] intraday_17409.csv.gz  in=320,944,119 out=100,678,891 elapsed=147.7s

  [9151/17668] intraday_1741.csv.gz  in=320,956,639 out=100,678,891 elapsed=147.8s

  [9152/17668] intraday_17410.csv.gz  in=320,966,851 out=100,689,103 elapsed=147.8s

  [9153/17668] intraday_17411.csv.gz  in=320,981,941 out=100,704,193 elapsed=147.8s

  [9154/17668] intraday_17413.csv.gz  in=320,995,042 out=100,717,294 elapsed=147.8s

  [9155/17668] intraday_17412.csv.gz  in=321,008,761 out=100,731,013 elapsed=147.8s

  [9156/17668] intraday_17414.csv.gz  in=321,021,154 out=100,743,406 elapsed=147.8s

  [9157/17668] intraday_17415.csv.gz  in=321,032,456 out=100,754,708 elapsed=147.8s

  [9158/17668] intraday_17416.csv.gz  in=321,047,608 out=100,769,860 elapsed=147.9s

  [9159/17668] intraday_17417.csv.gz  in=321,061,776 out=100,784,028 elapsed=147.9s

  [9160/17668] intraday_17419.csv.gz  in=321,073,019 out=100,795,271 elapsed=147.9s

  [9161/17668] intraday_17418.csv.gz  in=321,086,766 out=100,809,018 elapsed=147.9s

  [9162/17668] intraday_1742.csv.gz  in=321,103,446 out=100,809,018 elapsed=147.9s

  [9163/17668] intraday_17421.csv.gz  in=321,113,486 out=100,819,058 elapsed=147.9s

  [9164/17668] intraday_17420.csv.gz  in=321,124,338 out=100,829,910 elapsed=147.9s

  [9165/17668] intraday_17423.csv.gz  in=321,136,814 out=100,842,386 elapsed=147.9s

  [9166/17668] intraday_17422.csv.gz  in=321,147,964 out=100,853,536 elapsed=147.9s

  [9167/17668] intraday_17424.csv.gz  in=321,159,760 out=100,865,332 elapsed=147.9s

  [9168/17668] intraday_17425.csv.gz  in=321,173,350 out=100,878,922 elapsed=148.0s

  [9169/17668] intraday_17426.csv.gz  in=321,187,172 out=100,892,744 elapsed=148.0s

  [9170/17668] intraday_17427.csv.gz  in=321,200,496 out=100,906,068 elapsed=148.0s

  [9171/17668] intraday_17428.csv.gz  in=321,211,625 out=100,917,197 elapsed=148.0s

  [9172/17668] intraday_1743.csv.gz  in=321,225,218 out=100,917,197 elapsed=148.0s

  [9173/17668] intraday_17429.csv.gz  in=321,236,728 out=100,928,707 elapsed=148.0s

  [9174/17668] intraday_17431.csv.gz  in=321,249,490 out=100,941,469 elapsed=148.0s

  [9175/17668] intraday_17430.csv.gz  in=321,262,571 out=100,954,550 elapsed=148.1s

  [9176/17668] intraday_17432.csv.gz  in=321,275,653 out=100,967,632 elapsed=148.1s

  [9177/17668] intraday_17433.csv.gz  in=321,288,082 out=100,980,061 elapsed=148.1s

  [9178/17668] intraday_17434.csv.gz  in=321,302,777 out=100,994,756 elapsed=148.1s

  [9179/17668] intraday_17435.csv.gz  in=321,316,235 out=101,008,214 elapsed=148.1s

  [9180/17668] intraday_17436.csv.gz  in=321,328,754 out=101,020,733 elapsed=148.1s

  [9181/17668] intraday_17437.csv.gz  in=321,343,132 out=101,035,111 elapsed=148.1s

  [9182/17668] intraday_17438.csv.gz  in=321,355,162 out=101,047,141 elapsed=148.1s

  [9183/17668] intraday_17439.csv.gz  in=321,367,749 out=101,059,728 elapsed=148.1s

  [9184/17668] intraday_1744.csv.gz  in=321,380,547 out=101,059,728 elapsed=148.2s

  [9185/17668] intraday_17441.csv.gz  in=321,393,350 out=101,072,531 elapsed=148.2s

  [9186/17668] intraday_17440.csv.gz  in=321,405,878 out=101,085,059 elapsed=148.2s

  [9187/17668] intraday_17442.csv.gz  in=321,416,996 out=101,096,177 elapsed=148.2s

  [9188/17668] intraday_17443.csv.gz  in=321,429,597 out=101,108,778 elapsed=148.2s

  [9189/17668] intraday_17444.csv.gz  in=321,441,621 out=101,120,802 elapsed=148.2s

  [9190/17668] intraday_17445.csv.gz  in=321,452,897 out=101,132,078 elapsed=148.2s

  [9191/17668] intraday_17446.csv.gz  in=321,464,694 out=101,143,875 elapsed=148.2s

  [9192/17668] intraday_17447.csv.gz  in=321,479,472 out=101,158,653 elapsed=148.2s

  [9193/17668] intraday_17448.csv.gz  in=321,492,475 out=101,171,656 elapsed=148.3s

  [9194/17668] intraday_1745.csv.gz  in=321,505,410 out=101,171,656 elapsed=148.3s

  [9195/17668] intraday_17449.csv.gz  in=321,519,064 out=101,185,310 elapsed=148.3s

  [9196/17668] intraday_17452.csv.gz  in=321,529,666 out=101,195,912 elapsed=148.3s

  [9197/17668] intraday_17450.csv.gz  in=321,545,681 out=101,211,898 elapsed=148.3s

  [9198/17668] intraday_17453.csv.gz  in=321,559,055 out=101,225,272 elapsed=148.3s

  [9199/17668] intraday_17451.csv.gz  in=321,569,782 out=101,235,999 elapsed=148.3s

  [9200/17668] intraday_17456.csv.gz  in=321,580,160 out=101,246,377 elapsed=148.4s

  [9201/17668] intraday_17455.csv.gz  in=321,592,255 out=101,258,472 elapsed=148.4s

  [9202/17668] intraday_17454.csv.gz  in=321,605,349 out=101,271,566 elapsed=148.4s

  [9203/17668] intraday_17457.csv.gz  in=321,616,099 out=101,282,316 elapsed=148.4s

  [9204/17668] intraday_17458.csv.gz  in=321,626,741 out=101,292,958 elapsed=148.4s

  [9205/17668] intraday_1746.csv.gz  in=321,640,573 out=101,292,958 elapsed=148.5s

  [9206/17668] intraday_17460.csv.gz  in=321,653,261 out=101,305,646 elapsed=148.5s

  [9207/17668] intraday_17459.csv.gz  in=321,667,894 out=101,320,279 elapsed=148.5s

  [9208/17668] intraday_17461.csv.gz  in=321,682,765 out=101,335,150 elapsed=148.5s

  [9209/17668] intraday_17462.csv.gz  in=321,692,704 out=101,345,089 elapsed=148.5s

  [9210/17668] intraday_17464.csv.gz  in=321,706,192 out=101,358,577 elapsed=148.5s

  [9211/17668] intraday_17463.csv.gz  in=321,717,875 out=101,370,260 elapsed=148.6s

  [9212/17668] intraday_17466.csv.gz  in=321,732,973 out=101,385,358 elapsed=148.6s

  [9213/17668] intraday_17465.csv.gz  in=321,747,442 out=101,399,827 elapsed=148.6s

  [9214/17668] intraday_17467.csv.gz  in=321,762,073 out=101,414,458 elapsed=148.6s

  [9215/17668] intraday_17468.csv.gz  in=321,772,309 out=101,424,694 elapsed=148.6s

  [9216/17668] intraday_17469.csv.gz  in=321,787,472 out=101,439,857 elapsed=148.6s

  [9217/17668] intraday_1747.csv.gz  in=321,801,108 out=101,439,857 elapsed=148.6s

  [9218/17668] intraday_17470.csv.gz  in=321,812,386 out=101,451,135 elapsed=148.6s

  [9219/17668] intraday_17471.csv.gz  in=321,825,756 out=101,464,505 elapsed=148.7s

  [9220/17668] intraday_17472.csv.gz  in=321,836,256 out=101,475,005 elapsed=148.7s

  [9221/17668] intraday_17473.csv.gz  in=321,848,722 out=101,487,471 elapsed=148.7s

  [9222/17668] intraday_17474.csv.gz  in=321,861,151 out=101,499,900 elapsed=148.7s

  [9223/17668] intraday_17475.csv.gz  in=321,873,765 out=101,512,514 elapsed=148.7s

  [9224/17668] intraday_17476.csv.gz  in=321,887,022 out=101,525,771 elapsed=148.7s

  [9225/17668] intraday_17477.csv.gz  in=321,899,402 out=101,538,151 elapsed=148.7s

  [9226/17668] intraday_17478.csv.gz  in=321,913,773 out=101,552,522 elapsed=148.7s

  [9227/17668] intraday_1748.csv.gz  in=321,927,765 out=101,552,522 elapsed=148.8s

  [9228/17668] intraday_17479.csv.gz  in=321,939,129 out=101,563,886 elapsed=148.8s

  [9229/17668] intraday_17480.csv.gz  in=321,950,817 out=101,575,574 elapsed=148.8s

  [9230/17668] intraday_17481.csv.gz  in=321,963,560 out=101,588,317 elapsed=148.8s

  [9231/17668] intraday_17483.csv.gz  in=321,977,255 out=101,602,012 elapsed=148.8s

  [9232/17668] intraday_17482.csv.gz  in=321,989,625 out=101,614,382 elapsed=148.8s

  [9233/17668] intraday_17484.csv.gz  in=322,003,150 out=101,627,907 elapsed=148.8s

  [9234/17668] intraday_17485.csv.gz  in=322,016,352 out=101,640,977 elapsed=148.8s

  [9235/17668] intraday_17486.csv.gz  in=322,027,619 out=101,652,244 elapsed=148.9s

  [9236/17668] intraday_17487.csv.gz  in=322,041,192 out=101,665,817 elapsed=148.9s

  [9237/17668] intraday_17489.csv.gz  in=322,054,108 out=101,678,733 elapsed=148.9s

  [9238/17668] intraday_17488.csv.gz  in=322,067,556 out=101,692,181 elapsed=148.9s

  [9239/17668] intraday_1749.csv.gz  in=322,086,869 out=101,692,181 elapsed=148.9s

  [9240/17668] intraday_17490.csv.gz  in=322,099,894 out=101,705,206 elapsed=148.9s

  [9241/17668] intraday_17491.csv.gz  in=322,113,592 out=101,718,904 elapsed=148.9s

  [9242/17668] intraday_17493.csv.gz  in=322,125,648 out=101,730,960 elapsed=149.0s

  [9243/17668] intraday_17492.csv.gz  in=322,140,998 out=101,746,310 elapsed=149.0s

  [9244/17668] intraday_17494.csv.gz  in=322,154,135 out=101,759,447 elapsed=149.0s

  [9245/17668] intraday_17495.csv.gz  in=322,167,975 out=101,773,287 elapsed=149.0s

  [9246/17668] intraday_17496.csv.gz  in=322,189,392 out=101,794,517 elapsed=149.0s

  [9247/17668] intraday_17497.csv.gz  in=322,205,924 out=101,811,049 elapsed=149.0s

  [9248/17668] intraday_17498.csv.gz  in=322,225,309 out=101,830,434 elapsed=149.0s

  [9249/17668] intraday_17499.csv.gz  in=322,240,302 out=101,845,427 elapsed=149.0s

  [9250/17668] intraday_1750.csv.gz  in=322,250,825 out=101,845,427 elapsed=149.0s

  [9251/17668] intraday_17500.csv.gz  in=322,266,575 out=101,861,177 elapsed=149.1s

  [9252/17668] intraday_17501.csv.gz  in=322,279,716 out=101,874,318 elapsed=149.1s

  [9253/17668] intraday_17503.csv.gz  in=322,290,309 out=101,884,911 elapsed=149.1s

  [9254/17668] intraday_17502.csv.gz  in=322,303,175 out=101,897,777 elapsed=149.1s

  [9255/17668] intraday_17504.csv.gz  in=322,316,068 out=101,910,670 elapsed=149.1s

  [9256/17668] intraday_17505.csv.gz  in=322,327,100 out=101,921,702 elapsed=149.1s

  [9257/17668] intraday_17506.csv.gz  in=322,340,653 out=101,935,255 elapsed=149.1s

  [9258/17668] intraday_17507.csv.gz  in=322,355,257 out=101,949,859 elapsed=149.1s

  [9259/17668] intraday_17508.csv.gz  in=322,369,167 out=101,963,769 elapsed=149.2s

  [9260/17668] intraday_17509.csv.gz  in=322,381,561 out=101,976,163 elapsed=149.2s

  [9261/17668] intraday_1751.csv.gz  in=322,393,121 out=101,976,163 elapsed=149.2s

  [9262/17668] intraday_17510.csv.gz  in=322,405,921 out=101,988,963 elapsed=149.2s

  [9263/17668] intraday_17511.csv.gz  in=322,418,564 out=102,001,606 elapsed=149.2s

  [9264/17668] intraday_17513.csv.gz  in=322,431,917 out=102,014,959 elapsed=149.2s

  [9265/17668] intraday_17512.csv.gz  in=322,445,150 out=102,028,192 elapsed=149.2s

  [9266/17668] intraday_17515.csv.gz  in=322,459,932 out=102,042,974 elapsed=149.2s

  [9267/17668] intraday_17514.csv.gz  in=322,473,664 out=102,056,706 elapsed=149.2s

  [9268/17668] intraday_17517.csv.gz  in=322,488,089 out=102,071,131 elapsed=149.3s

  [9269/17668] intraday_17516.csv.gz  in=322,502,686 out=102,085,728 elapsed=149.3s

  [9270/17668] intraday_17518.csv.gz  in=322,514,398 out=102,097,440 elapsed=149.3s

  [9271/17668] intraday_1752.csv.gz  in=322,525,831 out=102,097,440 elapsed=149.3s

  [9272/17668] intraday_17519.csv.gz  in=322,539,772 out=102,111,381 elapsed=149.3s

  [9273/17668] intraday_17520.csv.gz  in=322,551,371 out=102,122,980 elapsed=149.3s

  [9274/17668] intraday_17523.csv.gz  in=322,560,423 out=102,132,032 elapsed=149.3s

  [9275/17668] intraday_17522.csv.gz  in=322,571,196 out=102,142,805 elapsed=149.3s

  [9276/17668] intraday_17524.csv.gz  in=322,583,641 out=102,155,250 elapsed=149.4s

  [9277/17668] intraday_17525.csv.gz  in=322,587,886 out=102,159,495 elapsed=149.4s

  [9278/17668] intraday_17521.csv.gz  in=322,600,209 out=102,171,818 elapsed=149.4s

  [9279/17668] intraday_17526.csv.gz  in=322,615,024 out=102,186,633 elapsed=149.4s

  [9280/17668] intraday_17528.csv.gz  in=322,626,790 out=102,198,399 elapsed=149.4s

  [9281/17668] intraday_17527.csv.gz  in=322,640,104 out=102,211,713 elapsed=149.4s

  [9282/17668] intraday_17529.csv.gz  in=322,651,350 out=102,222,959 elapsed=149.4s

  [9283/17668] intraday_1753.csv.gz  in=322,664,998 out=102,222,959 elapsed=149.4s

  [9284/17668] intraday_17530.csv.gz  in=322,678,107 out=102,236,068 elapsed=149.4s

  [9285/17668] intraday_17532.csv.gz  in=322,690,398 out=102,248,359 elapsed=149.5s

  [9286/17668] intraday_17531.csv.gz  in=322,704,102 out=102,262,063 elapsed=149.5s

  [9287/17668] intraday_17534.csv.gz  in=322,718,333 out=102,276,294 elapsed=149.5s

  [9288/17668] intraday_17535.csv.gz  in=322,730,007 out=102,287,968 elapsed=149.5s

  [9289/17668] intraday_17536.csv.gz  in=322,740,298 out=102,298,259 elapsed=149.5s

  [9290/17668] intraday_17533.csv.gz  in=322,750,279 out=102,308,240 elapsed=149.5s

  [9291/17668] intraday_17537.csv.gz  in=322,762,076 out=102,320,037 elapsed=149.5s

  [9292/17668] intraday_17538.csv.gz  in=322,774,570 out=102,332,531 elapsed=149.5s

  [9293/17668] intraday_17539.csv.gz  in=322,786,136 out=102,344,097 elapsed=149.5s

  [9294/17668] intraday_1754.csv.gz  in=322,796,734 out=102,344,097 elapsed=149.5s

  [9295/17668] intraday_17540.csv.gz  in=322,807,692 out=102,355,055 elapsed=149.5s

  [9296/17668] intraday_17541.csv.gz  in=322,818,096 out=102,365,459 elapsed=149.6s

  [9297/17668] intraday_17542.csv.gz  in=322,832,459 out=102,379,822 elapsed=149.6s

  [9298/17668] intraday_17544.csv.gz  in=322,842,410 out=102,389,773 elapsed=149.6s

  [9299/17668] intraday_17545.csv.gz  in=322,853,247 out=102,400,610 elapsed=149.6s

  [9300/17668] intraday_17546.csv.gz  in=322,864,804 out=102,412,167 elapsed=149.6s

  [9301/17668] intraday_17543.csv.gz  in=322,877,342 out=102,424,705 elapsed=149.6s

  [9302/17668] intraday_17547.csv.gz  in=322,890,384 out=102,437,747 elapsed=149.6s

  [9303/17668] intraday_17548.csv.gz  in=322,901,853 out=102,449,216 elapsed=149.6s

  [9304/17668] intraday_17549.csv.gz  in=322,913,470 out=102,460,833 elapsed=149.7s

  [9305/17668] intraday_17550.csv.gz  in=322,926,159 out=102,473,522 elapsed=149.7s

  [9306/17668] intraday_17551.csv.gz  in=322,936,985 out=102,484,348 elapsed=149.7s

  [9307/17668] intraday_17552.csv.gz  in=322,949,126 out=102,496,489 elapsed=149.7s

  [9308/17668] intraday_1755.csv.gz  in=322,961,679 out=102,496,489 elapsed=149.7s

  [9309/17668] intraday_17553.csv.gz  in=322,972,722 out=102,507,532 elapsed=149.7s

  [9310/17668] intraday_17554.csv.gz  in=322,986,349 out=102,521,159 elapsed=149.7s

  [9311/17668] intraday_17555.csv.gz  in=322,999,785 out=102,534,595 elapsed=149.7s

  [9312/17668] intraday_17557.csv.gz  in=323,011,899 out=102,546,709 elapsed=149.7s

  [9313/17668] intraday_17556.csv.gz  in=323,023,534 out=102,558,344 elapsed=149.7s

  [9314/17668] intraday_17558.csv.gz  in=323,034,820 out=102,569,630 elapsed=149.7s

  [9315/17668] intraday_17559.csv.gz  in=323,047,559 out=102,582,369 elapsed=149.7s

  [9316/17668] intraday_17560.csv.gz  in=323,061,259 out=102,596,069 elapsed=149.8s

  [9317/17668] intraday_1756.csv.gz  in=323,073,117 out=102,596,069 elapsed=149.8s

  [9318/17668] intraday_17562.csv.gz  in=323,084,134 out=102,607,086 elapsed=149.8s

  [9319/17668] intraday_17561.csv.gz  in=323,106,751 out=102,629,703 elapsed=149.8s

  [9320/17668] intraday_17564.csv.gz  in=323,117,557 out=102,640,509 elapsed=149.8s

  [9321/17668] intraday_17563.csv.gz  in=323,127,640 out=102,650,592 elapsed=149.8s

  [9322/17668] intraday_17565.csv.gz  in=323,137,866 out=102,660,818 elapsed=149.8s

  [9323/17668] intraday_17567.csv.gz  in=323,149,428 out=102,672,380 elapsed=149.9s

  [9324/17668] intraday_17566.csv.gz  in=323,161,668 out=102,684,620 elapsed=149.9s

  [9325/17668] intraday_17568.csv.gz  in=323,173,867 out=102,696,819 elapsed=149.9s

  [9326/17668] intraday_17569.csv.gz  in=323,187,495 out=102,710,447 elapsed=149.9s

  [9327/17668] intraday_1757.csv.gz  in=323,198,891 out=102,710,447 elapsed=149.9s

  [9328/17668] intraday_17571.csv.gz  in=323,209,953 out=102,721,509 elapsed=149.9s

  [9329/17668] intraday_17573.csv.gz  in=323,221,881 out=102,733,437 elapsed=149.9s

  [9330/17668] intraday_17570.csv.gz  in=323,234,117 out=102,745,673 elapsed=149.9s

  [9331/17668] intraday_17572.csv.gz  in=323,245,137 out=102,756,693 elapsed=149.9s

  [9332/17668] intraday_17574.csv.gz  in=323,257,391 out=102,768,947 elapsed=150.0s

  [9333/17668] intraday_17575.csv.gz  in=323,270,563 out=102,782,119 elapsed=150.0s

  [9334/17668] intraday_17576.csv.gz  in=323,286,474 out=102,798,030 elapsed=150.0s

  [9335/17668] intraday_17577.csv.gz  in=323,300,524 out=102,812,080 elapsed=150.0s

  [9336/17668] intraday_17578.csv.gz  in=323,313,975 out=102,825,531 elapsed=150.0s

  [9337/17668] intraday_17579.csv.gz  in=323,324,886 out=102,836,442 elapsed=150.0s

  [9338/17668] intraday_1758.csv.gz  in=323,339,557 out=102,836,442 elapsed=150.0s

  [9339/17668] intraday_17580.csv.gz  in=323,352,913 out=102,849,798 elapsed=150.0s

  [9340/17668] intraday_17581.csv.gz  in=323,364,320 out=102,861,205 elapsed=150.0s

  [9341/17668] intraday_17582.csv.gz  in=323,375,919 out=102,872,804 elapsed=150.0s

  [9342/17668] intraday_17583.csv.gz  in=323,386,540 out=102,883,425 elapsed=150.1s

  [9343/17668] intraday_17584.csv.gz  in=323,399,490 out=102,896,375 elapsed=150.1s

  [9344/17668] intraday_17585.csv.gz  in=323,410,203 out=102,907,088 elapsed=150.1s

  [9345/17668] intraday_17586.csv.gz  in=323,421,908 out=102,918,793 elapsed=150.1s

  [9346/17668] intraday_17587.csv.gz  in=323,433,421 out=102,930,306 elapsed=150.1s

  [9347/17668] intraday_17589.csv.gz  in=323,445,680 out=102,942,565 elapsed=150.1s

  [9348/17668] intraday_17588.csv.gz  in=323,466,554 out=102,963,439 elapsed=150.1s

  [9349/17668] intraday_17590.csv.gz  in=323,483,987 out=102,980,872 elapsed=150.1s

  [9350/17668] intraday_1759.csv.gz  in=323,495,211 out=102,980,872 elapsed=150.1s

  [9351/17668] intraday_17591.csv.gz  in=323,508,002 out=102,993,663 elapsed=150.2s

  [9352/17668] intraday_17592.csv.gz  in=323,520,913 out=103,006,574 elapsed=150.2s

  [9353/17668] intraday_17593.csv.gz  in=323,533,597 out=103,019,258 elapsed=150.2s

  [9354/17668] intraday_17594.csv.gz  in=323,544,829 out=103,030,490 elapsed=150.2s

  [9355/17668] intraday_17595.csv.gz  in=323,554,346 out=103,040,007 elapsed=150.2s

  [9356/17668] intraday_17596.csv.gz  in=323,566,865 out=103,052,526 elapsed=150.2s

  [9357/17668] intraday_17597.csv.gz  in=323,583,582 out=103,069,243 elapsed=150.2s

  [9358/17668] intraday_17598.csv.gz  in=323,595,357 out=103,081,018 elapsed=150.2s

  [9359/17668] intraday_17599.csv.gz  in=323,605,534 out=103,091,195 elapsed=150.2s

  [9360/17668] intraday_1760.csv.gz  in=323,622,741 out=103,091,195 elapsed=150.3s

  [9361/17668] intraday_17600.csv.gz  in=323,633,737 out=103,102,191 elapsed=150.3s

  [9362/17668] intraday_17602.csv.gz  in=323,646,980 out=103,115,434 elapsed=150.3s

  [9363/17668] intraday_17601.csv.gz  in=323,656,991 out=103,125,445 elapsed=150.3s

  [9364/17668] intraday_17603.csv.gz  in=323,669,639 out=103,138,093 elapsed=150.3s

  [9365/17668] intraday_17605.csv.gz  in=323,679,466 out=103,147,920 elapsed=150.3s

  [9366/17668] intraday_17606.csv.gz  in=323,690,470 out=103,158,924 elapsed=150.3s

  [9367/17668] intraday_17604.csv.gz  in=323,703,077 out=103,171,531 elapsed=150.3s

  [9368/17668] intraday_17607.csv.gz  in=323,715,931 out=103,184,385 elapsed=150.3s

  [9369/17668] intraday_17608.csv.gz  in=323,730,147 out=103,198,601 elapsed=150.3s

  [9370/17668] intraday_17609.csv.gz  in=323,743,534 out=103,211,988 elapsed=150.3s

  [9371/17668] intraday_1761.csv.gz  in=323,757,537 out=103,211,988 elapsed=150.3s

  [9372/17668] intraday_17610.csv.gz  in=323,770,844 out=103,225,295 elapsed=150.4s

  [9373/17668] intraday_17611.csv.gz  in=323,781,520 out=103,235,971 elapsed=150.4s

  [9374/17668] intraday_17612.csv.gz  in=323,796,146 out=103,250,597 elapsed=150.4s

  [9375/17668] intraday_17613.csv.gz  in=323,806,134 out=103,260,585 elapsed=150.4s

  [9376/17668] intraday_17615.csv.gz  in=323,816,314 out=103,270,765 elapsed=150.4s

  [9377/17668] intraday_17614.csv.gz  in=323,828,708 out=103,283,159 elapsed=150.4s

  [9378/17668] intraday_17616.csv.gz  in=323,840,364 out=103,294,815 elapsed=150.4s

  [9379/17668] intraday_17617.csv.gz  in=323,852,563 out=103,307,014 elapsed=150.4s

  [9380/17668] intraday_17618.csv.gz  in=323,870,880 out=103,325,331 elapsed=150.4s

  [9381/17668] intraday_1762.csv.gz  in=323,884,379 out=103,325,331 elapsed=150.5s

  [9382/17668] intraday_17619.csv.gz  in=323,897,437 out=103,338,389 elapsed=150.5s

  [9383/17668] intraday_17620.csv.gz  in=323,909,257 out=103,350,209 elapsed=150.5s

  [9384/17668] intraday_17623.csv.gz  in=323,919,601 out=103,360,553 elapsed=150.5s

  [9385/17668] intraday_17621.csv.gz  in=323,933,116 out=103,374,068 elapsed=150.5s

  [9386/17668] intraday_17622.csv.gz  in=323,944,990 out=103,385,942 elapsed=150.5s

  [9387/17668] intraday_17624.csv.gz  in=323,956,932 out=103,397,884 elapsed=150.5s

  [9388/17668] intraday_17625.csv.gz  in=323,968,670 out=103,409,622 elapsed=150.5s

  [9389/17668] intraday_17626.csv.gz  in=323,983,577 out=103,424,529 elapsed=150.5s

  [9390/17668] intraday_17627.csv.gz  in=323,996,639 out=103,437,591 elapsed=150.6s

  [9391/17668] intraday_17628.csv.gz  in=324,008,105 out=103,449,057 elapsed=150.6s

  [9392/17668] intraday_17629.csv.gz  in=324,019,096 out=103,460,048 elapsed=150.6s

  [9393/17668] intraday_17630.csv.gz  in=324,032,236 out=103,473,188 elapsed=150.6s

  [9394/17668] intraday_17631.csv.gz  in=324,044,103 out=103,485,055 elapsed=150.6s

  [9395/17668] intraday_17632.csv.gz  in=324,055,742 out=103,496,694 elapsed=150.6s

  [9396/17668] intraday_1763.csv.gz  in=324,090,344 out=103,496,694 elapsed=150.6s

  [9397/17668] intraday_17633.csv.gz  in=324,102,398 out=103,508,748 elapsed=150.6s

  [9398/17668] intraday_17634.csv.gz  in=324,115,719 out=103,522,069 elapsed=150.6s

  [9399/17668] intraday_17636.csv.gz  in=324,127,758 out=103,534,108 elapsed=150.7s

  [9400/17668] intraday_17635.csv.gz  in=324,142,233 out=103,548,583 elapsed=150.7s

  [9401/17668] intraday_17637.csv.gz  in=324,154,490 out=103,560,840 elapsed=150.7s

  [9402/17668] intraday_17638.csv.gz  in=324,166,378 out=103,572,728 elapsed=150.7s

  [9403/17668] intraday_1764.csv.gz  in=324,180,231 out=103,572,728 elapsed=150.7s

  [9404/17668] intraday_17639.csv.gz  in=324,193,547 out=103,586,044 elapsed=150.7s

  [9405/17668] intraday_17640.csv.gz  in=324,207,136 out=103,599,633 elapsed=150.7s

  [9406/17668] intraday_17641.csv.gz  in=324,224,126 out=103,616,623 elapsed=150.7s

  [9407/17668] intraday_17642.csv.gz  in=324,238,302 out=103,630,799 elapsed=150.7s

  [9408/17668] intraday_17644.csv.gz  in=324,250,159 out=103,642,656 elapsed=150.7s

  [9409/17668] intraday_17645.csv.gz  in=324,264,947 out=103,657,444 elapsed=150.7s

  [9410/17668] intraday_17643.csv.gz  in=324,279,802 out=103,672,299 elapsed=150.7s

  [9411/17668] intraday_17646.csv.gz  in=324,290,365 out=103,682,862 elapsed=150.7s

  [9412/17668] intraday_17647.csv.gz  in=324,303,848 out=103,696,345 elapsed=150.8s

  [9413/17668] intraday_17648.csv.gz  in=324,316,128 out=103,708,625 elapsed=150.8s

  [9414/17668] intraday_17649.csv.gz  in=324,328,882 out=103,721,379 elapsed=150.8s

  [9415/17668] intraday_1765.csv.gz  in=324,341,121 out=103,721,379 elapsed=150.8s

  [9416/17668] intraday_17650.csv.gz  in=324,353,142 out=103,733,400 elapsed=150.8s

  [9417/17668] intraday_17651.csv.gz  in=324,367,343 out=103,747,601 elapsed=150.8s

  [9418/17668] intraday_17653.csv.gz  in=324,378,002 out=103,758,260 elapsed=150.8s

  [9419/17668] intraday_17652.csv.gz  in=324,389,784 out=103,770,042 elapsed=150.8s

  [9420/17668] intraday_17654.csv.gz  in=324,401,673 out=103,781,931 elapsed=150.8s

  [9421/17668] intraday_17655.csv.gz  in=324,414,244 out=103,794,502 elapsed=150.8s

  [9422/17668] intraday_17656.csv.gz  in=324,426,515 out=103,806,773 elapsed=150.9s

  [9423/17668] intraday_17657.csv.gz  in=324,440,259 out=103,820,517 elapsed=150.9s

  [9424/17668] intraday_17658.csv.gz  in=324,453,547 out=103,833,805 elapsed=150.9s

  [9425/17668] intraday_17659.csv.gz  in=324,466,054 out=103,846,312 elapsed=150.9s

  [9426/17668] intraday_1766.csv.gz  in=324,478,987 out=103,846,312 elapsed=150.9s

  [9427/17668] intraday_17661.csv.gz  in=324,488,800 out=103,856,125 elapsed=150.9s

  [9428/17668] intraday_17662.csv.gz  in=324,500,974 out=103,868,299 elapsed=150.9s

  [9429/17668] intraday_17663.csv.gz  in=324,514,637 out=103,881,962 elapsed=150.9s

  [9430/17668] intraday_17664.csv.gz  in=324,524,875 out=103,892,200 elapsed=150.9s

  [9431/17668] intraday_17660.csv.gz  in=324,540,285 out=103,907,610 elapsed=150.9s

  [9432/17668] intraday_17665.csv.gz  in=324,551,473 out=103,918,798 elapsed=151.0s

  [9433/17668] intraday_17666.csv.gz  in=324,559,670 out=103,926,995 elapsed=151.0s

  [9434/17668] intraday_17667.csv.gz  in=324,569,893 out=103,937,218 elapsed=151.0s

  [9435/17668] intraday_1767.csv.gz  in=324,580,681 out=103,937,218 elapsed=151.0s

  [9436/17668] intraday_17668.csv.gz  in=324,588,783 out=103,945,320 elapsed=151.0s

  [9437/17668] intraday_1768.csv.gz  in=324,602,098 out=103,945,320 elapsed=151.0s

  [9438/17668] intraday_1769.csv.gz  in=324,614,427 out=103,945,320 elapsed=151.0s

  [9439/17668] intraday_1772.csv.gz  in=324,627,401 out=103,945,320 elapsed=151.0s

  [9440/17668] intraday_1770.csv.gz  in=324,645,522 out=103,945,320 elapsed=151.0s

  [9441/17668] intraday_1771.csv.gz  in=324,657,934 out=103,945,320 elapsed=151.0s

  [9442/17668] intraday_1775.csv.gz  in=324,668,291 out=103,945,320 elapsed=151.1s

  [9443/17668] intraday_1773.csv.gz  in=324,680,440 out=103,945,320 elapsed=151.1s

  [9444/17668] intraday_1774.csv.gz  in=324,693,427 out=103,945,320 elapsed=151.1s

  [9445/17668] intraday_1776.csv.gz  in=324,710,240 out=103,945,320 elapsed=151.1s

  [9446/17668] intraday_1777.csv.gz  in=324,724,181 out=103,945,320 elapsed=151.1s

  [9447/17668] intraday_1778.csv.gz  in=324,739,601 out=103,945,320 elapsed=151.1s

  [9448/17668] intraday_1780.csv.gz  in=324,753,470 out=103,945,320 elapsed=151.1s

  [9449/17668] intraday_1779.csv.gz  in=324,773,350 out=103,945,320 elapsed=151.1s

  [9450/17668] intraday_1781.csv.gz  in=324,786,805 out=103,945,320 elapsed=151.1s

  [9451/17668] intraday_1783.csv.gz  in=324,800,019 out=103,945,320 elapsed=151.2s

  [9452/17668] intraday_1782.csv.gz  in=324,818,530 out=103,945,320 elapsed=151.2s

  [9453/17668] intraday_1785.csv.gz  in=324,831,826 out=103,945,320 elapsed=151.2s

  [9454/17668] intraday_1784.csv.gz  in=324,848,165 out=103,945,320 elapsed=151.2s

  [9455/17668] intraday_1786.csv.gz  in=324,860,285 out=103,945,320 elapsed=151.2s

  [9456/17668] intraday_1787.csv.gz  in=324,873,362 out=103,945,320 elapsed=151.2s

  [9457/17668] intraday_1789.csv.gz  in=324,886,356 out=103,945,320 elapsed=151.2s

  [9458/17668] intraday_1788.csv.gz  in=324,896,356 out=103,945,320 elapsed=151.2s

  [9459/17668] intraday_1790.csv.gz  in=324,907,081 out=103,945,320 elapsed=151.2s

  [9460/17668] intraday_1791.csv.gz  in=324,918,687 out=103,945,320 elapsed=151.2s

  [9461/17668] intraday_1792.csv.gz  in=324,926,240 out=103,945,320 elapsed=151.2s

  [9462/17668] intraday_1794.csv.gz  in=324,932,624 out=103,945,320 elapsed=151.2s

  [9463/17668] intraday_1793.csv.gz  in=324,943,356 out=103,945,320 elapsed=151.2s

  [9464/17668] intraday_1796.csv.gz  in=324,956,597 out=103,945,320 elapsed=151.3s

  [9465/17668] intraday_1795.csv.gz  in=324,971,463 out=103,945,320 elapsed=151.3s

  [9466/17668] intraday_1797.csv.gz  in=324,983,642 out=103,945,320 elapsed=151.3s

  [9467/17668] intraday_1798.csv.gz  in=324,995,041 out=103,945,320 elapsed=151.3s

  [9468/17668] intraday_1799.csv.gz  in=325,007,903 out=103,945,320 elapsed=151.3s

  [9469/17668] intraday_1800.csv.gz  in=325,022,516 out=103,945,320 elapsed=151.3s

  [9470/17668] intraday_1802.csv.gz  in=325,034,697 out=103,945,320 elapsed=151.3s

  [9471/17668] intraday_1801.csv.gz  in=325,046,990 out=103,945,320 elapsed=151.3s

  [9472/17668] intraday_1805.csv.gz  in=325,055,907 out=103,945,320 elapsed=151.3s

  [9473/17668] intraday_1803.csv.gz  in=325,069,508 out=103,945,320 elapsed=151.3s

  [9474/17668] intraday_1804.csv.gz  in=325,083,857 out=103,945,320 elapsed=151.3s

  [9475/17668] intraday_1806.csv.gz  in=325,095,998 out=103,945,320 elapsed=151.4s

  [9476/17668] intraday_1807.csv.gz  in=325,109,212 out=103,945,320 elapsed=151.4s

  [9477/17668] intraday_1809.csv.gz  in=325,119,427 out=103,945,320 elapsed=151.4s

  [9478/17668] intraday_1808.csv.gz  in=325,129,935 out=103,945,320 elapsed=151.4s

  [9479/17668] intraday_1810.csv.gz  in=325,142,219 out=103,945,320 elapsed=151.4s

  [9480/17668] intraday_1811.csv.gz  in=325,154,723 out=103,945,320 elapsed=151.4s

  [9481/17668] intraday_1813.csv.gz  in=325,166,449 out=103,945,320 elapsed=151.4s

  [9482/17668] intraday_1812.csv.gz  in=325,178,370 out=103,945,320 elapsed=151.4s

  [9483/17668] intraday_1814.csv.gz  in=325,190,188 out=103,945,320 elapsed=151.4s

  [9484/17668] intraday_1815.csv.gz  in=325,209,316 out=103,945,320 elapsed=151.4s

  [9485/17668] intraday_1816.csv.gz  in=325,229,284 out=103,945,320 elapsed=151.4s

  [9486/17668] intraday_1817.csv.gz  in=325,243,109 out=103,945,320 elapsed=151.4s

  [9487/17668] intraday_1818.csv.gz  in=325,255,774 out=103,945,320 elapsed=151.5s

  [9488/17668] intraday_1820.csv.gz  in=325,264,617 out=103,945,320 elapsed=151.5s

  [9489/17668] intraday_1819.csv.gz  in=325,277,096 out=103,945,320 elapsed=151.5s

  [9490/17668] intraday_1821.csv.gz  in=325,289,383 out=103,945,320 elapsed=151.5s

  [9491/17668] intraday_1822.csv.gz  in=325,301,060 out=103,945,320 elapsed=151.5s

  [9492/17668] intraday_1823.csv.gz  in=325,313,925 out=103,945,320 elapsed=151.5s

  [9493/17668] intraday_1824.csv.gz  in=325,329,083 out=103,945,320 elapsed=151.5s

  [9494/17668] intraday_1825.csv.gz  in=325,341,421 out=103,945,320 elapsed=151.5s

  [9495/17668] intraday_1826.csv.gz  in=325,351,983 out=103,945,320 elapsed=151.5s

  [9496/17668] intraday_1827.csv.gz  in=325,366,466 out=103,945,320 elapsed=151.5s

  [9497/17668] intraday_1828.csv.gz  in=325,378,775 out=103,945,320 elapsed=151.5s

  [9498/17668] intraday_1829.csv.gz  in=325,389,715 out=103,945,320 elapsed=151.6s

  [9499/17668] intraday_1830.csv.gz  in=325,401,952 out=103,945,320 elapsed=151.6s

  [9500/17668] intraday_1831.csv.gz  in=325,413,276 out=103,945,320 elapsed=151.6s

  [9501/17668] intraday_1832.csv.gz  in=325,424,957 out=103,945,320 elapsed=151.6s

  [9502/17668] intraday_1833.csv.gz  in=325,437,155 out=103,945,320 elapsed=151.6s

  [9503/17668] intraday_1835.csv.gz  in=325,451,368 out=103,945,320 elapsed=151.6s

  [9504/17668] intraday_1834.csv.gz  in=325,461,734 out=103,945,320 elapsed=151.6s

  [9505/17668] intraday_1836.csv.gz  in=325,474,035 out=103,945,320 elapsed=151.6s

  [9506/17668] intraday_1838.csv.gz  in=325,486,176 out=103,945,320 elapsed=151.6s

  [9507/17668] intraday_1837.csv.gz  in=325,499,520 out=103,945,320 elapsed=151.6s

  [9508/17668] intraday_1839.csv.gz  in=325,523,536 out=103,945,320 elapsed=151.6s

  [9509/17668] intraday_1840.csv.gz  in=325,536,471 out=103,945,320 elapsed=151.7s

  [9510/17668] intraday_1841.csv.gz  in=325,547,217 out=103,945,320 elapsed=151.7s

  [9511/17668] intraday_1843.csv.gz  in=325,558,624 out=103,945,320 elapsed=151.7s

  [9512/17668] intraday_1842.csv.gz  in=325,571,027 out=103,945,320 elapsed=151.7s

  [9513/17668] intraday_1844.csv.gz  in=325,585,255 out=103,945,320 elapsed=151.7s

  [9514/17668] intraday_1845.csv.gz  in=325,600,452 out=103,945,320 elapsed=151.7s

  [9515/17668] intraday_1847.csv.gz  in=325,610,858 out=103,945,320 elapsed=151.7s

  [9516/17668] intraday_1846.csv.gz  in=325,625,441 out=103,945,320 elapsed=151.7s

  [9517/17668] intraday_1848.csv.gz  in=325,638,607 out=103,945,320 elapsed=151.7s

  [9518/17668] intraday_1849.csv.gz  in=325,651,432 out=103,945,320 elapsed=151.7s

  [9519/17668] intraday_1851.csv.gz  in=325,661,962 out=103,945,320 elapsed=151.7s

  [9520/17668] intraday_1852.csv.gz  in=325,674,525 out=103,945,320 elapsed=151.8s

  [9521/17668] intraday_1850.csv.gz  in=325,686,549 out=103,945,320 elapsed=151.8s

  [9522/17668] intraday_1853.csv.gz  in=325,698,716 out=103,945,320 elapsed=151.8s

  [9523/17668] intraday_1855.csv.gz  in=325,710,328 out=103,945,320 elapsed=151.8s

  [9524/17668] intraday_1854.csv.gz  in=325,735,371 out=103,945,320 elapsed=151.8s

  [9525/17668] intraday_1856.csv.gz  in=325,755,635 out=103,945,320 elapsed=151.8s

  [9526/17668] intraday_1857.csv.gz  in=325,767,103 out=103,945,320 elapsed=151.8s

  [9527/17668] intraday_1858.csv.gz  in=325,779,912 out=103,945,320 elapsed=151.8s

  [9528/17668] intraday_1859.csv.gz  in=325,792,441 out=103,945,320 elapsed=151.8s

  [9529/17668] intraday_1860.csv.gz  in=325,806,836 out=103,945,320 elapsed=151.8s

  [9530/17668] intraday_1861.csv.gz  in=325,819,811 out=103,945,320 elapsed=151.8s

  [9531/17668] intraday_1862.csv.gz  in=325,831,815 out=103,945,320 elapsed=151.9s

  [9532/17668] intraday_1863.csv.gz  in=325,842,195 out=103,945,320 elapsed=151.9s

  [9533/17668] intraday_1864.csv.gz  in=325,854,222 out=103,945,320 elapsed=151.9s

  [9534/17668] intraday_1865.csv.gz  in=325,865,511 out=103,945,320 elapsed=151.9s

  [9535/17668] intraday_1866.csv.gz  in=325,889,770 out=103,945,320 elapsed=151.9s

  [9536/17668] intraday_1868.csv.gz  in=325,901,249 out=103,945,320 elapsed=151.9s

  [9537/17668] intraday_1867.csv.gz  in=325,911,097 out=103,945,320 elapsed=151.9s

  [9538/17668] intraday_1869.csv.gz  in=325,921,799 out=103,945,320 elapsed=151.9s

  [9539/17668] intraday_1870.csv.gz  in=325,934,953 out=103,945,320 elapsed=151.9s

  [9540/17668] intraday_1871.csv.gz  in=325,945,544 out=103,945,320 elapsed=151.9s

  [9541/17668] intraday_1872.csv.gz  in=325,958,730 out=103,945,320 elapsed=152.0s

  [9542/17668] intraday_1873.csv.gz  in=325,969,454 out=103,945,320 elapsed=152.0s

  [9543/17668] intraday_1874.csv.gz  in=325,980,753 out=103,945,320 elapsed=152.0s

  [9544/17668] intraday_1875.csv.gz  in=325,992,164 out=103,945,320 elapsed=152.0s

  [9545/17668] intraday_1876.csv.gz  in=326,005,328 out=103,945,320 elapsed=152.0s

  [9546/17668] intraday_1877.csv.gz  in=326,017,191 out=103,945,320 elapsed=152.0s

  [9547/17668] intraday_1878.csv.gz  in=326,028,847 out=103,945,320 elapsed=152.0s

  [9548/17668] intraday_1879.csv.gz  in=326,038,536 out=103,945,320 elapsed=152.0s

  [9549/17668] intraday_1880.csv.gz  in=326,056,375 out=103,945,320 elapsed=152.0s

  [9550/17668] intraday_1883.csv.gz  in=326,068,092 out=103,945,320 elapsed=152.0s

  [9551/17668] intraday_1881.csv.gz  in=326,079,991 out=103,945,320 elapsed=152.0s

  [9552/17668] intraday_1882.csv.gz  in=326,094,700 out=103,945,320 elapsed=152.1s

  [9553/17668] intraday_1885.csv.gz  in=326,108,244 out=103,945,320 elapsed=152.1s

  [9554/17668] intraday_1887.csv.gz  in=326,120,991 out=103,945,320 elapsed=152.1s

  [9555/17668] intraday_1884.csv.gz  in=326,134,866 out=103,945,320 elapsed=152.1s

  [9556/17668] intraday_1886.csv.gz  in=326,147,880 out=103,945,320 elapsed=152.1s

  [9557/17668] intraday_1888.csv.gz  in=326,160,124 out=103,945,320 elapsed=152.1s

  [9558/17668] intraday_1890.csv.gz  in=326,170,974 out=103,945,320 elapsed=152.1s

  [9559/17668] intraday_1891.csv.gz  in=326,182,603 out=103,945,320 elapsed=152.1s

  [9560/17668] intraday_1889.csv.gz  in=326,193,925 out=103,945,320 elapsed=152.1s

  [9561/17668] intraday_1892.csv.gz  in=326,206,448 out=103,945,320 elapsed=152.1s

  [9562/17668] intraday_1895.csv.gz  in=326,218,680 out=103,945,320 elapsed=152.1s

  [9563/17668] intraday_1893.csv.gz  in=326,229,923 out=103,945,320 elapsed=152.1s

  [9564/17668] intraday_1894.csv.gz  in=326,241,724 out=103,945,320 elapsed=152.2s

  [9565/17668] intraday_1897.csv.gz  in=326,254,071 out=103,945,320 elapsed=152.2s

  [9566/17668] intraday_1896.csv.gz  in=326,265,940 out=103,945,320 elapsed=152.2s

  [9567/17668] intraday_1898.csv.gz  in=326,278,121 out=103,945,320 elapsed=152.2s

  [9568/17668] intraday_1899.csv.gz  in=326,303,845 out=103,945,320 elapsed=152.2s

  [9569/17668] intraday_1901.csv.gz  in=326,318,675 out=103,945,320 elapsed=152.2s

  [9570/17668] intraday_1900.csv.gz  in=326,332,307 out=103,945,320 elapsed=152.2s

  [9571/17668] intraday_1902.csv.gz  in=326,344,061 out=103,945,320 elapsed=152.2s

  [9572/17668] intraday_1903.csv.gz  in=326,367,428 out=103,945,320 elapsed=152.2s

  [9573/17668] intraday_1904.csv.gz  in=326,380,098 out=103,945,320 elapsed=152.3s

  [9574/17668] intraday_1905.csv.gz  in=326,400,346 out=103,945,320 elapsed=152.3s

  [9575/17668] intraday_1907.csv.gz  in=326,412,848 out=103,945,320 elapsed=152.3s

  [9576/17668] intraday_1906.csv.gz  in=326,425,816 out=103,945,320 elapsed=152.3s

  [9577/17668] intraday_1908.csv.gz  in=326,439,136 out=103,945,320 elapsed=152.3s

  [9578/17668] intraday_1909.csv.gz  in=326,456,149 out=103,945,320 elapsed=152.3s

  [9579/17668] intraday_1910.csv.gz  in=326,468,033 out=103,945,320 elapsed=152.3s

  [9580/17668] intraday_1911.csv.gz  in=326,481,177 out=103,945,320 elapsed=152.3s

  [9581/17668] intraday_1912.csv.gz  in=326,494,291 out=103,945,320 elapsed=152.3s

  [9582/17668] intraday_1913.csv.gz  in=326,505,729 out=103,945,320 elapsed=152.3s

  [9583/17668] intraday_1914.csv.gz  in=326,516,255 out=103,945,320 elapsed=152.3s

  [9584/17668] intraday_1915.csv.gz  in=326,530,159 out=103,945,320 elapsed=152.4s

  [9585/17668] intraday_1916.csv.gz  in=326,543,212 out=103,945,320 elapsed=152.4s

  [9586/17668] intraday_1918.csv.gz  in=326,555,663 out=103,945,320 elapsed=152.4s

  [9587/17668] intraday_1917.csv.gz  in=326,577,686 out=103,945,320 elapsed=152.4s

  [9588/17668] intraday_1919.csv.gz  in=326,593,266 out=103,945,320 elapsed=152.4s

  [9589/17668] intraday_1921.csv.gz  in=326,606,354 out=103,945,320 elapsed=152.4s

  [9590/17668] intraday_1920.csv.gz  in=326,619,961 out=103,945,320 elapsed=152.4s

  [9591/17668] intraday_1922.csv.gz  in=326,639,736 out=103,945,320 elapsed=152.4s

  [9592/17668] intraday_1923.csv.gz  in=326,655,047 out=103,945,320 elapsed=152.4s

  [9593/17668] intraday_1924.csv.gz  in=326,670,081 out=103,945,320 elapsed=152.4s

  [9594/17668] intraday_1926.csv.gz  in=326,684,948 out=103,945,320 elapsed=152.5s

  [9595/17668] intraday_1925.csv.gz  in=326,698,894 out=103,945,320 elapsed=152.5s

  [9596/17668] intraday_1927.csv.gz  in=326,709,794 out=103,945,320 elapsed=152.5s

  [9597/17668] intraday_1930.csv.gz  in=326,721,462 out=103,945,320 elapsed=152.5s

  [9598/17668] intraday_1928.csv.gz  in=326,732,485 out=103,945,320 elapsed=152.5s

  [9599/17668] intraday_1931.csv.gz  in=326,741,897 out=103,945,320 elapsed=152.5s

  [9600/17668] intraday_1929.csv.gz  in=326,754,656 out=103,945,320 elapsed=152.5s

  [9601/17668] intraday_1934.csv.gz  in=326,759,247 out=103,945,320 elapsed=152.5s

  [9602/17668] intraday_1932.csv.gz  in=326,768,224 out=103,945,320 elapsed=152.5s

  [9603/17668] intraday_1933.csv.gz  in=326,778,126 out=103,945,320 elapsed=152.5s

  [9604/17668] intraday_1936.csv.gz  in=326,791,975 out=103,945,320 elapsed=152.5s

  [9605/17668] intraday_1935.csv.gz  in=326,806,851 out=103,945,320 elapsed=152.6s

  [9606/17668] intraday_1937.csv.gz  in=326,818,890 out=103,945,320 elapsed=152.6s

  [9607/17668] intraday_1938.csv.gz  in=326,830,476 out=103,945,320 elapsed=152.6s

  [9608/17668] intraday_1939.csv.gz  in=326,843,794 out=103,945,320 elapsed=152.6s

  [9609/17668] intraday_1940.csv.gz  in=326,858,322 out=103,945,320 elapsed=152.6s

  [9610/17668] intraday_1941.csv.gz  in=326,870,661 out=103,945,320 elapsed=152.6s

  [9611/17668] intraday_1942.csv.gz  in=326,882,847 out=103,945,320 elapsed=152.6s

  [9612/17668] intraday_1943.csv.gz  in=326,896,908 out=103,945,320 elapsed=152.6s

  [9613/17668] intraday_1944.csv.gz  in=326,912,626 out=103,945,320 elapsed=152.6s

  [9614/17668] intraday_1945.csv.gz  in=326,921,571 out=103,945,320 elapsed=152.6s

  [9615/17668] intraday_1946.csv.gz  in=326,938,876 out=103,945,320 elapsed=152.7s

  [9616/17668] intraday_1947.csv.gz  in=326,952,594 out=103,945,320 elapsed=152.7s

  [9617/17668] intraday_1950.csv.gz  in=326,965,636 out=103,945,320 elapsed=152.7s

  [9618/17668] intraday_1949.csv.gz  in=326,976,303 out=103,945,320 elapsed=152.7s

  [9619/17668] intraday_1948.csv.gz  in=326,991,703 out=103,945,320 elapsed=152.7s

  [9620/17668] intraday_1951.csv.gz  in=327,010,481 out=103,945,320 elapsed=152.7s

  [9621/17668] intraday_1952.csv.gz  in=327,022,975 out=103,945,320 elapsed=152.7s

  [9622/17668] intraday_1953.csv.gz  in=327,036,897 out=103,945,320 elapsed=152.7s

  [9623/17668] intraday_1954.csv.gz  in=327,049,233 out=103,945,320 elapsed=152.7s

  [9624/17668] intraday_1956.csv.gz  in=327,060,971 out=103,945,320 elapsed=152.8s

  [9625/17668] intraday_1955.csv.gz  in=327,074,342 out=103,945,320 elapsed=152.8s

  [9626/17668] intraday_1957.csv.gz  in=327,089,337 out=103,945,320 elapsed=152.8s

  [9627/17668] intraday_1958.csv.gz  in=327,107,001 out=103,945,320 elapsed=152.8s

  [9628/17668] intraday_1960.csv.gz  in=327,117,638 out=103,945,320 elapsed=152.8s

  [9629/17668] intraday_1961.csv.gz  in=327,129,789 out=103,945,320 elapsed=152.8s

  [9630/17668] intraday_1959.csv.gz  in=327,142,079 out=103,945,320 elapsed=152.8s

  [9631/17668] intraday_1962.csv.gz  in=327,153,827 out=103,945,320 elapsed=152.8s

  [9632/17668] intraday_1964.csv.gz  in=327,168,508 out=103,945,320 elapsed=152.8s

  [9633/17668] intraday_1963.csv.gz  in=327,181,362 out=103,945,320 elapsed=152.8s

  [9634/17668] intraday_1966.csv.gz  in=327,192,597 out=103,945,320 elapsed=152.8s

  [9635/17668] intraday_1965.csv.gz  in=327,206,352 out=103,945,320 elapsed=152.8s

  [9636/17668] intraday_1967.csv.gz  in=327,217,666 out=103,945,320 elapsed=152.9s

  [9637/17668] intraday_1968.csv.gz  in=327,231,088 out=103,945,320 elapsed=152.9s

  [9638/17668] intraday_1969.csv.gz  in=327,242,017 out=103,945,320 elapsed=152.9s

  [9639/17668] intraday_1970.csv.gz  in=327,254,977 out=103,945,320 elapsed=152.9s

  [9640/17668] intraday_1971.csv.gz  in=327,265,417 out=103,945,320 elapsed=152.9s

  [9641/17668] intraday_1972.csv.gz  in=327,276,815 out=103,945,320 elapsed=152.9s

  [9642/17668] intraday_1974.csv.gz  in=327,287,693 out=103,945,320 elapsed=152.9s

  [9643/17668] intraday_1973.csv.gz  in=327,301,304 out=103,945,320 elapsed=152.9s

  [9644/17668] intraday_1975.csv.gz  in=327,316,385 out=103,945,320 elapsed=152.9s

  [9645/17668] intraday_1978.csv.gz  in=327,329,281 out=103,945,320 elapsed=152.9s

  [9646/17668] intraday_1977.csv.gz  in=327,341,360 out=103,945,320 elapsed=152.9s

  [9647/17668] intraday_1976.csv.gz  in=327,354,090 out=103,945,320 elapsed=152.9s

  [9648/17668] intraday_1979.csv.gz  in=327,366,784 out=103,945,320 elapsed=153.0s

  [9649/17668] intraday_1980.csv.gz  in=327,379,748 out=103,945,320 elapsed=153.0s

  [9650/17668] intraday_1981.csv.gz  in=327,390,766 out=103,945,320 elapsed=153.0s

  [9651/17668] intraday_1982.csv.gz  in=327,423,482 out=103,945,320 elapsed=153.0s

  [9652/17668] intraday_1983.csv.gz  in=327,435,960 out=103,945,320 elapsed=153.0s

  [9653/17668] intraday_1984.csv.gz  in=327,450,611 out=103,945,320 elapsed=153.0s

  [9654/17668] intraday_1985.csv.gz  in=327,462,594 out=103,945,320 elapsed=153.0s

  [9655/17668] intraday_1988.csv.gz  in=327,475,887 out=103,945,320 elapsed=153.1s

  [9656/17668] intraday_1986.csv.gz  in=327,488,431 out=103,945,320 elapsed=153.1s

  [9657/17668] intraday_1987.csv.gz  in=327,500,733 out=103,945,320 elapsed=153.1s

  [9658/17668] intraday_1989.csv.gz  in=327,513,179 out=103,945,320 elapsed=153.1s

  [9659/17668] intraday_1992.csv.gz  in=327,526,237 out=103,945,320 elapsed=153.1s

  [9660/17668] intraday_1991.csv.gz  in=327,537,278 out=103,945,320 elapsed=153.1s

  [9661/17668] intraday_1990.csv.gz  in=327,549,731 out=103,945,320 elapsed=153.1s

  [9662/17668] intraday_1993.csv.gz  in=327,562,763 out=103,945,320 elapsed=153.1s

  [9663/17668] intraday_1995.csv.gz  in=327,574,202 out=103,945,320 elapsed=153.1s

  [9664/17668] intraday_1994.csv.gz  in=327,586,617 out=103,945,320 elapsed=153.1s

  [9665/17668] intraday_1996.csv.gz  in=327,597,344 out=103,945,320 elapsed=153.1s

  [9666/17668] intraday_1997.csv.gz  in=327,607,410 out=103,945,320 elapsed=153.1s

  [9667/17668] intraday_1998.csv.gz  in=327,621,124 out=103,945,320 elapsed=153.1s

  [9668/17668] intraday_2000.csv.gz  in=327,634,801 out=103,945,320 elapsed=153.2s

  [9669/17668] intraday_2001.csv.gz  in=327,648,449 out=103,945,320 elapsed=153.2s

  [9670/17668] intraday_1999.csv.gz  in=327,660,184 out=103,945,320 elapsed=153.2s

  [9671/17668] intraday_2003.csv.gz  in=327,670,082 out=103,945,320 elapsed=153.2s

  [9672/17668] intraday_2002.csv.gz  in=327,686,994 out=103,945,320 elapsed=153.2s

  [9673/17668] intraday_2004.csv.gz  in=327,699,962 out=103,945,320 elapsed=153.2s

  [9674/17668] intraday_2005.csv.gz  in=327,711,451 out=103,945,320 elapsed=153.2s

  [9675/17668] intraday_2007.csv.gz  in=327,721,332 out=103,945,320 elapsed=153.2s

  [9676/17668] intraday_2006.csv.gz  in=327,734,191 out=103,945,320 elapsed=153.2s

  [9677/17668] intraday_2009.csv.gz  in=327,745,068 out=103,945,320 elapsed=153.2s

  [9678/17668] intraday_2008.csv.gz  in=327,757,410 out=103,945,320 elapsed=153.2s

  [9679/17668] intraday_2010.csv.gz  in=327,769,669 out=103,945,320 elapsed=153.3s

  [9680/17668] intraday_2011.csv.gz  in=327,780,631 out=103,945,320 elapsed=153.3s

  [9681/17668] intraday_2013.csv.gz  in=327,792,048 out=103,945,320 elapsed=153.3s

  [9682/17668] intraday_2012.csv.gz  in=327,805,588 out=103,945,320 elapsed=153.3s

  [9683/17668] intraday_2014.csv.gz  in=327,816,606 out=103,945,320 elapsed=153.3s

  [9684/17668] intraday_2015.csv.gz  in=327,827,741 out=103,945,320 elapsed=153.3s

  [9685/17668] intraday_2017.csv.gz  in=327,839,131 out=103,945,320 elapsed=153.3s

  [9686/17668] intraday_2016.csv.gz  in=327,854,138 out=103,945,320 elapsed=153.3s

  [9687/17668] intraday_2018.csv.gz  in=327,866,104 out=103,945,320 elapsed=153.3s

  [9688/17668] intraday_2019.csv.gz  in=327,877,111 out=103,945,320 elapsed=153.3s

  [9689/17668] intraday_2020.csv.gz  in=327,888,928 out=103,945,320 elapsed=153.3s

  [9690/17668] intraday_2021.csv.gz  in=327,901,235 out=103,945,320 elapsed=153.4s

  [9691/17668] intraday_2023.csv.gz  in=327,912,319 out=103,945,320 elapsed=153.4s

  [9692/17668] intraday_2022.csv.gz  in=327,927,848 out=103,945,320 elapsed=153.4s

  [9693/17668] intraday_2024.csv.gz  in=327,942,386 out=103,945,320 elapsed=153.4s

  [9694/17668] intraday_2025.csv.gz  in=327,957,447 out=103,945,320 elapsed=153.4s

  [9695/17668] intraday_2026.csv.gz  in=327,971,595 out=103,945,320 elapsed=153.4s

  [9696/17668] intraday_2027.csv.gz  in=327,985,820 out=103,945,320 elapsed=153.4s

  [9697/17668] intraday_2029.csv.gz  in=327,997,865 out=103,945,320 elapsed=153.4s

  [9698/17668] intraday_2028.csv.gz  in=328,011,383 out=103,945,320 elapsed=153.4s

  [9699/17668] intraday_2030.csv.gz  in=328,023,654 out=103,945,320 elapsed=153.5s

  [9700/17668] intraday_2033.csv.gz  in=328,035,167 out=103,945,320 elapsed=153.5s

  [9701/17668] intraday_2031.csv.gz  in=328,045,890 out=103,945,320 elapsed=153.5s

  [9702/17668] intraday_2032.csv.gz  in=328,057,730 out=103,945,320 elapsed=153.5s

  [9703/17668] intraday_2035.csv.gz  in=328,068,666 out=103,945,320 elapsed=153.5s

  [9704/17668] intraday_2034.csv.gz  in=328,082,776 out=103,945,320 elapsed=153.5s

  [9705/17668] intraday_2036.csv.gz  in=328,095,659 out=103,945,320 elapsed=153.5s

  [9706/17668] intraday_2037.csv.gz  in=328,108,049 out=103,945,320 elapsed=153.5s

  [9707/17668] intraday_2038.csv.gz  in=328,121,439 out=103,945,320 elapsed=153.5s

  [9708/17668] intraday_2040.csv.gz  in=328,135,406 out=103,945,320 elapsed=153.5s

  [9709/17668] intraday_2039.csv.gz  in=328,153,627 out=103,945,320 elapsed=153.5s

  [9710/17668] intraday_2042.csv.gz  in=328,167,024 out=103,945,320 elapsed=153.6s

  [9711/17668] intraday_2041.csv.gz  in=328,181,858 out=103,945,320 elapsed=153.6s

  [9712/17668] intraday_2043.csv.gz  in=328,194,282 out=103,945,320 elapsed=153.6s

  [9713/17668] intraday_2044.csv.gz  in=328,207,654 out=103,945,320 elapsed=153.6s

  [9714/17668] intraday_2046.csv.gz  in=328,220,612 out=103,945,320 elapsed=153.6s

  [9715/17668] intraday_2045.csv.gz  in=328,232,392 out=103,945,320 elapsed=153.6s

  [9716/17668] intraday_2047.csv.gz  in=328,244,944 out=103,945,320 elapsed=153.6s

  [9717/17668] intraday_2048.csv.gz  in=328,260,020 out=103,945,320 elapsed=153.6s

  [9718/17668] intraday_2050.csv.gz  in=328,272,838 out=103,945,320 elapsed=153.6s

  [9719/17668] intraday_2049.csv.gz  in=328,288,588 out=103,945,320 elapsed=153.6s

  [9720/17668] intraday_2051.csv.gz  in=328,301,134 out=103,945,320 elapsed=153.6s

  [9721/17668] intraday_2052.csv.gz  in=328,322,111 out=103,945,320 elapsed=153.7s

  [9722/17668] intraday_2053.csv.gz  in=328,333,142 out=103,945,320 elapsed=153.7s

  [9723/17668] intraday_2054.csv.gz  in=328,345,137 out=103,945,320 elapsed=153.7s

  [9724/17668] intraday_2055.csv.gz  in=328,356,798 out=103,945,320 elapsed=153.7s

  [9725/17668] intraday_2056.csv.gz  in=328,372,111 out=103,945,320 elapsed=153.7s

  [9726/17668] intraday_2057.csv.gz  in=328,385,168 out=103,945,320 elapsed=153.7s

  [9727/17668] intraday_2059.csv.gz  in=328,397,565 out=103,945,320 elapsed=153.7s

  [9728/17668] intraday_2058.csv.gz  in=328,412,881 out=103,945,320 elapsed=153.7s

  [9729/17668] intraday_2060.csv.gz  in=328,426,248 out=103,945,320 elapsed=153.8s

  [9730/17668] intraday_2062.csv.gz  in=328,438,759 out=103,945,320 elapsed=153.8s

  [9731/17668] intraday_2061.csv.gz  in=328,453,173 out=103,945,320 elapsed=153.8s

  [9732/17668] intraday_2063.csv.gz  in=328,467,694 out=103,945,320 elapsed=153.8s

  [9733/17668] intraday_2064.csv.gz  in=328,482,726 out=103,945,320 elapsed=153.8s

  [9734/17668] intraday_2065.csv.gz  in=328,497,913 out=103,945,320 elapsed=153.8s

  [9735/17668] intraday_2066.csv.gz  in=328,511,382 out=103,945,320 elapsed=153.8s

  [9736/17668] intraday_2067.csv.gz  in=328,523,354 out=103,945,320 elapsed=153.8s

  [9737/17668] intraday_2068.csv.gz  in=328,539,516 out=103,945,320 elapsed=153.8s

  [9738/17668] intraday_2070.csv.gz  in=328,551,894 out=103,945,320 elapsed=153.8s

  [9739/17668] intraday_2069.csv.gz  in=328,565,032 out=103,945,320 elapsed=153.8s

  [9740/17668] intraday_2072.csv.gz  in=328,572,659 out=103,945,320 elapsed=153.9s

  [9741/17668] intraday_2071.csv.gz  in=328,588,039 out=103,945,320 elapsed=153.9s

  [9742/17668] intraday_2073.csv.gz  in=328,599,004 out=103,945,320 elapsed=153.9s

  [9743/17668] intraday_2074.csv.gz  in=328,605,121 out=103,945,320 elapsed=153.9s

  [9744/17668] intraday_2075.csv.gz  in=328,619,913 out=103,945,320 elapsed=153.9s

  [9745/17668] intraday_2076.csv.gz  in=328,634,469 out=103,945,320 elapsed=153.9s

  [9746/17668] intraday_2077.csv.gz  in=328,646,451 out=103,945,320 elapsed=153.9s

  [9747/17668] intraday_2078.csv.gz  in=328,657,309 out=103,945,320 elapsed=153.9s

  [9748/17668] intraday_2081.csv.gz  in=328,669,552 out=103,945,320 elapsed=153.9s

  [9749/17668] intraday_2079.csv.gz  in=328,683,629 out=103,945,320 elapsed=153.9s

  [9750/17668] intraday_2080.csv.gz  in=328,698,024 out=103,945,320 elapsed=153.9s

  [9751/17668] intraday_2082.csv.gz  in=328,710,875 out=103,945,320 elapsed=153.9s

  [9752/17668] intraday_2086.csv.gz  in=328,722,666 out=103,945,320 elapsed=154.0s

  [9753/17668] intraday_2085.csv.gz  in=328,732,584 out=103,945,320 elapsed=154.0s

  [9754/17668] intraday_2083.csv.gz  in=328,747,004 out=103,945,320 elapsed=154.0s

  [9755/17668] intraday_2084.csv.gz  in=328,762,320 out=103,945,320 elapsed=154.0s

  [9756/17668] intraday_2087.csv.gz  in=328,776,056 out=103,945,320 elapsed=154.0s

  [9757/17668] intraday_2089.csv.gz  in=328,787,302 out=103,945,320 elapsed=154.0s

  [9758/17668] intraday_2088.csv.gz  in=328,798,571 out=103,945,320 elapsed=154.0s

  [9759/17668] intraday_2090.csv.gz  in=328,811,177 out=103,945,320 elapsed=154.0s

  [9760/17668] intraday_2092.csv.gz  in=328,823,908 out=103,945,320 elapsed=154.0s

  [9761/17668] intraday_2091.csv.gz  in=328,836,479 out=103,945,320 elapsed=154.1s

  [9762/17668] intraday_2093.csv.gz  in=328,848,659 out=103,945,320 elapsed=154.1s

  [9763/17668] intraday_2094.csv.gz  in=328,860,884 out=103,945,320 elapsed=154.1s

  [9764/17668] intraday_2095.csv.gz  in=328,874,386 out=103,945,320 elapsed=154.1s

  [9765/17668] intraday_2097.csv.gz  in=328,886,772 out=103,945,320 elapsed=154.1s

  [9766/17668] intraday_2096.csv.gz  in=328,899,097 out=103,945,320 elapsed=154.1s

  [9767/17668] intraday_2098.csv.gz  in=328,911,603 out=103,945,320 elapsed=154.1s

  [9768/17668] intraday_2100.csv.gz  in=328,920,859 out=103,945,320 elapsed=154.1s

  [9769/17668] intraday_2101.csv.gz  in=328,933,088 out=103,945,320 elapsed=154.1s

  [9770/17668] intraday_2102.csv.gz  in=328,945,635 out=103,945,320 elapsed=154.1s

  [9771/17668] intraday_2099.csv.gz  in=328,958,126 out=103,945,320 elapsed=154.2s

  [9772/17668] intraday_2103.csv.gz  in=328,971,647 out=103,945,320 elapsed=154.2s

  [9773/17668] intraday_2104.csv.gz  in=328,986,619 out=103,945,320 elapsed=154.2s

  [9774/17668] intraday_2106.csv.gz  in=328,998,293 out=103,945,320 elapsed=154.2s

  [9775/17668] intraday_2107.csv.gz  in=329,010,589 out=103,945,320 elapsed=154.2s

  [9776/17668] intraday_2105.csv.gz  in=329,022,926 out=103,945,320 elapsed=154.2s

  [9777/17668] intraday_2109.csv.gz  in=329,034,043 out=103,945,320 elapsed=154.2s

  [9778/17668] intraday_2108.csv.gz  in=329,046,910 out=103,945,320 elapsed=154.2s

  [9779/17668] intraday_2110.csv.gz  in=329,059,928 out=103,945,320 elapsed=154.2s

  [9780/17668] intraday_2111.csv.gz  in=329,071,293 out=103,945,320 elapsed=154.2s

  [9781/17668] intraday_2112.csv.gz  in=329,082,480 out=103,945,320 elapsed=154.2s

  [9782/17668] intraday_2113.csv.gz  in=329,095,253 out=103,945,320 elapsed=154.2s

  [9783/17668] intraday_2114.csv.gz  in=329,107,202 out=103,945,320 elapsed=154.3s

  [9784/17668] intraday_2116.csv.gz  in=329,119,273 out=103,945,320 elapsed=154.3s

  [9785/17668] intraday_2117.csv.gz  in=329,133,449 out=103,945,320 elapsed=154.3s

  [9786/17668] intraday_2115.csv.gz  in=329,148,190 out=103,945,320 elapsed=154.3s

  [9787/17668] intraday_2118.csv.gz  in=329,160,966 out=103,945,320 elapsed=154.3s

  [9788/17668] intraday_2120.csv.gz  in=329,173,994 out=103,945,320 elapsed=154.3s

  [9789/17668] intraday_2119.csv.gz  in=329,186,767 out=103,945,320 elapsed=154.3s

  [9790/17668] intraday_2121.csv.gz  in=329,197,870 out=103,945,320 elapsed=154.3s

  [9791/17668] intraday_2122.csv.gz  in=329,210,270 out=103,945,320 elapsed=154.3s

  [9792/17668] intraday_2124.csv.gz  in=329,220,829 out=103,945,320 elapsed=154.4s

  [9793/17668] intraday_2126.csv.gz  in=329,232,932 out=103,945,320 elapsed=154.4s

  [9794/17668] intraday_2123.csv.gz  in=329,245,274 out=103,945,320 elapsed=154.4s

  [9795/17668] intraday_2125.csv.gz  in=329,258,784 out=103,945,320 elapsed=154.4s

  [9796/17668] intraday_2127.csv.gz  in=329,269,818 out=103,945,320 elapsed=154.4s

  [9797/17668] intraday_2128.csv.gz  in=329,282,268 out=103,945,320 elapsed=154.4s

  [9798/17668] intraday_2129.csv.gz  in=329,296,228 out=103,945,320 elapsed=154.4s

  [9799/17668] intraday_2130.csv.gz  in=329,308,037 out=103,945,320 elapsed=154.4s

  [9800/17668] intraday_2131.csv.gz  in=329,319,719 out=103,945,320 elapsed=154.4s

  [9801/17668] intraday_2132.csv.gz  in=329,333,749 out=103,945,320 elapsed=154.4s

  [9802/17668] intraday_2134.csv.gz  in=329,346,606 out=103,945,320 elapsed=154.5s

  [9803/17668] intraday_2133.csv.gz  in=329,358,386 out=103,945,320 elapsed=154.5s

  [9804/17668] intraday_2135.csv.gz  in=329,370,937 out=103,945,320 elapsed=154.5s

  [9805/17668] intraday_2137.csv.gz  in=329,381,552 out=103,945,320 elapsed=154.5s

  [9806/17668] intraday_2136.csv.gz  in=329,392,415 out=103,945,320 elapsed=154.5s

  [9807/17668] intraday_2138.csv.gz  in=329,405,780 out=103,945,320 elapsed=154.5s

  [9808/17668] intraday_2139.csv.gz  in=329,419,593 out=103,945,320 elapsed=154.5s

  [9809/17668] intraday_2142.csv.gz  in=329,430,201 out=103,945,320 elapsed=154.5s

  [9810/17668] intraday_2140.csv.gz  in=329,444,973 out=103,945,320 elapsed=154.5s

  [9811/17668] intraday_2141.csv.gz  in=329,459,372 out=103,945,320 elapsed=154.5s

  [9812/17668] intraday_2143.csv.gz  in=329,471,263 out=103,945,320 elapsed=154.5s

  [9813/17668] intraday_2144.csv.gz  in=329,482,752 out=103,945,320 elapsed=154.6s

  [9814/17668] intraday_2146.csv.gz  in=329,496,745 out=103,945,320 elapsed=154.6s

  [9815/17668] intraday_2145.csv.gz  in=329,509,174 out=103,945,320 elapsed=154.6s

  [9816/17668] intraday_2147.csv.gz  in=329,520,598 out=103,945,320 elapsed=154.6s

  [9817/17668] intraday_2148.csv.gz  in=329,532,006 out=103,945,320 elapsed=154.6s

  [9818/17668] intraday_2151.csv.gz  in=329,543,399 out=103,945,320 elapsed=154.6s

  [9819/17668] intraday_2149.csv.gz  in=329,555,246 out=103,945,320 elapsed=154.6s

  [9820/17668] intraday_2150.csv.gz  in=329,568,138 out=103,945,320 elapsed=154.6s

  [9821/17668] intraday_2154.csv.gz  in=329,579,840 out=103,945,320 elapsed=154.6s

  [9822/17668] intraday_2153.csv.gz  in=329,590,745 out=103,945,320 elapsed=154.6s

  [9823/17668] intraday_2152.csv.gz  in=329,603,753 out=103,945,320 elapsed=154.7s

  [9824/17668] intraday_2155.csv.gz  in=329,615,913 out=103,945,320 elapsed=154.7s

  [9825/17668] intraday_2156.csv.gz  in=329,631,703 out=103,945,320 elapsed=154.7s

  [9826/17668] intraday_2157.csv.gz  in=329,642,310 out=103,945,320 elapsed=154.7s

  [9827/17668] intraday_2158.csv.gz  in=329,654,409 out=103,945,320 elapsed=154.7s

  [9828/17668] intraday_2159.csv.gz  in=329,664,200 out=103,945,320 elapsed=154.7s

  [9829/17668] intraday_2160.csv.gz  in=329,678,586 out=103,945,320 elapsed=154.7s

  [9830/17668] intraday_2161.csv.gz  in=329,690,263 out=103,945,320 elapsed=154.7s

  [9831/17668] intraday_2162.csv.gz  in=329,706,315 out=103,945,320 elapsed=154.7s

  [9832/17668] intraday_2163.csv.gz  in=329,718,609 out=103,945,320 elapsed=154.7s

  [9833/17668] intraday_2164.csv.gz  in=329,733,359 out=103,945,320 elapsed=154.7s

  [9834/17668] intraday_2165.csv.gz  in=329,746,788 out=103,945,320 elapsed=154.8s

  [9835/17668] intraday_2167.csv.gz  in=329,760,427 out=103,945,320 elapsed=154.8s

  [9836/17668] intraday_2166.csv.gz  in=329,775,037 out=103,945,320 elapsed=154.8s

  [9837/17668] intraday_2168.csv.gz  in=329,787,468 out=103,945,320 elapsed=154.8s

  [9838/17668] intraday_2169.csv.gz  in=329,799,818 out=103,945,320 elapsed=154.8s

  [9839/17668] intraday_2170.csv.gz  in=329,811,868 out=103,945,320 elapsed=154.8s

  [9840/17668] intraday_2171.csv.gz  in=329,824,768 out=103,945,320 elapsed=154.8s

  [9841/17668] intraday_2172.csv.gz  in=329,837,392 out=103,945,320 elapsed=154.8s

  [9842/17668] intraday_2173.csv.gz  in=329,848,822 out=103,945,320 elapsed=154.8s

  [9843/17668] intraday_2175.csv.gz  in=329,861,102 out=103,945,320 elapsed=154.8s

  [9844/17668] intraday_2174.csv.gz  in=329,875,960 out=103,945,320 elapsed=154.9s

  [9845/17668] intraday_2176.csv.gz  in=329,887,548 out=103,945,320 elapsed=154.9s

  [9846/17668] intraday_2177.csv.gz  in=329,902,969 out=103,945,320 elapsed=154.9s

  [9847/17668] intraday_2178.csv.gz  in=329,913,294 out=103,945,320 elapsed=154.9s

  [9848/17668] intraday_2179.csv.gz  in=329,926,300 out=103,945,320 elapsed=154.9s

  [9849/17668] intraday_2180.csv.gz  in=329,940,696 out=103,945,320 elapsed=154.9s

  [9850/17668] intraday_2181.csv.gz  in=329,955,674 out=103,945,320 elapsed=154.9s

  [9851/17668] intraday_2182.csv.gz  in=329,968,572 out=103,945,320 elapsed=154.9s

  [9852/17668] intraday_2185.csv.gz  in=329,981,646 out=103,945,320 elapsed=154.9s

  [9853/17668] intraday_2184.csv.gz  in=329,993,639 out=103,945,320 elapsed=154.9s

  [9854/17668] intraday_2183.csv.gz  in=330,007,160 out=103,945,320 elapsed=154.9s

  [9855/17668] intraday_2186.csv.gz  in=330,019,305 out=103,945,320 elapsed=154.9s

  [9856/17668] intraday_2190.csv.gz  in=330,031,727 out=103,945,320 elapsed=155.0s

  [9857/17668] intraday_2188.csv.gz  in=330,043,561 out=103,945,320 elapsed=155.0s

  [9858/17668] intraday_2187.csv.gz  in=330,057,778 out=103,945,320 elapsed=155.0s

  [9859/17668] intraday_2189.csv.gz  in=330,074,420 out=103,945,320 elapsed=155.0s

  [9860/17668] intraday_2191.csv.gz  in=330,088,896 out=103,945,320 elapsed=155.0s

  [9861/17668] intraday_2192.csv.gz  in=330,101,020 out=103,945,320 elapsed=155.0s

  [9862/17668] intraday_2194.csv.gz  in=330,111,916 out=103,945,320 elapsed=155.0s

  [9863/17668] intraday_2193.csv.gz  in=330,124,594 out=103,945,320 elapsed=155.0s

  [9864/17668] intraday_2196.csv.gz  in=330,137,867 out=103,945,320 elapsed=155.0s

  [9865/17668] intraday_2197.csv.gz  in=330,153,439 out=103,945,320 elapsed=155.1s

  [9866/17668] intraday_2198.csv.gz  in=330,165,699 out=103,945,320 elapsed=155.1s

  [9867/17668] intraday_2195.csv.gz  in=330,180,388 out=103,945,320 elapsed=155.1s

  [9868/17668] intraday_2199.csv.gz  in=330,195,224 out=103,945,320 elapsed=155.1s

  [9869/17668] intraday_2200.csv.gz  in=330,208,474 out=103,945,320 elapsed=155.1s

  [9870/17668] intraday_2201.csv.gz  in=330,221,883 out=103,945,320 elapsed=155.1s

  [9871/17668] intraday_2204.csv.gz  in=330,236,146 out=103,945,320 elapsed=155.1s

  [9872/17668] intraday_2203.csv.gz  in=330,251,685 out=103,945,320 elapsed=155.1s

  [9873/17668] intraday_2202.csv.gz  in=330,266,051 out=103,945,320 elapsed=155.1s

  [9874/17668] intraday_2207.csv.gz  in=330,277,722 out=103,945,320 elapsed=155.2s

  [9875/17668] intraday_2208.csv.gz  in=330,290,420 out=103,945,320 elapsed=155.2s

  [9876/17668] intraday_2206.csv.gz  in=330,304,353 out=103,945,320 elapsed=155.2s

  [9877/17668] intraday_2205.csv.gz  in=330,318,492 out=103,945,320 elapsed=155.2s

  [9878/17668] intraday_2209.csv.gz  in=330,329,079 out=103,945,320 elapsed=155.2s

  [9879/17668] intraday_2210.csv.gz  in=330,343,774 out=103,945,320 elapsed=155.2s

  [9880/17668] intraday_2211.csv.gz  in=330,351,907 out=103,945,320 elapsed=155.2s

  [9881/17668] intraday_2212.csv.gz  in=330,361,492 out=103,945,320 elapsed=155.2s

  [9882/17668] intraday_2214.csv.gz  in=330,376,769 out=103,945,320 elapsed=155.2s

  [9883/17668] intraday_2215.csv.gz  in=330,390,615 out=103,945,320 elapsed=155.2s

  [9884/17668] intraday_2213.csv.gz  in=330,400,583 out=103,945,320 elapsed=155.3s

  [9885/17668] intraday_2216.csv.gz  in=330,412,856 out=103,945,320 elapsed=155.3s

  [9886/17668] intraday_2217.csv.gz  in=330,423,994 out=103,945,320 elapsed=155.3s

  [9887/17668] intraday_2218.csv.gz  in=330,437,800 out=103,945,320 elapsed=155.3s

  [9888/17668] intraday_2219.csv.gz  in=330,452,111 out=103,945,320 elapsed=155.3s

  [9889/17668] intraday_2220.csv.gz  in=330,464,843 out=103,945,320 elapsed=155.3s

  [9890/17668] intraday_2222.csv.gz  in=330,479,156 out=103,945,320 elapsed=155.3s

  [9891/17668] intraday_2221.csv.gz  in=330,491,937 out=103,945,320 elapsed=155.3s

  [9892/17668] intraday_2224.csv.gz  in=330,501,484 out=103,945,320 elapsed=155.3s

  [9893/17668] intraday_2223.csv.gz  in=330,516,484 out=103,945,320 elapsed=155.3s

  [9894/17668] intraday_2225.csv.gz  in=330,528,238 out=103,945,320 elapsed=155.4s

  [9895/17668] intraday_2226.csv.gz  in=330,542,489 out=103,945,320 elapsed=155.4s

  [9896/17668] intraday_2228.csv.gz  in=330,554,364 out=103,945,320 elapsed=155.4s

  [9897/17668] intraday_2227.csv.gz  in=330,572,001 out=103,945,320 elapsed=155.4s

  [9898/17668] intraday_2229.csv.gz  in=330,584,623 out=103,945,320 elapsed=155.4s

  [9899/17668] intraday_2230.csv.gz  in=330,597,971 out=103,945,320 elapsed=155.4s

  [9900/17668] intraday_2231.csv.gz  in=330,610,555 out=103,945,320 elapsed=155.4s

  [9901/17668] intraday_2232.csv.gz  in=330,630,532 out=103,945,320 elapsed=155.4s

  [9902/17668] intraday_2233.csv.gz  in=330,643,006 out=103,945,320 elapsed=155.4s

  [9903/17668] intraday_2234.csv.gz  in=330,656,293 out=103,945,320 elapsed=155.4s

  [9904/17668] intraday_2235.csv.gz  in=330,668,890 out=103,945,320 elapsed=155.5s

  [9905/17668] intraday_2236.csv.gz  in=330,681,571 out=103,945,320 elapsed=155.5s

  [9906/17668] intraday_2237.csv.gz  in=330,694,917 out=103,945,320 elapsed=155.5s

  [9907/17668] intraday_2238.csv.gz  in=330,707,576 out=103,945,320 elapsed=155.5s

  [9908/17668] intraday_2239.csv.gz  in=330,716,664 out=103,945,320 elapsed=155.5s

  [9909/17668] intraday_2240.csv.gz  in=330,729,674 out=103,945,320 elapsed=155.5s

  [9910/17668] intraday_2242.csv.gz  in=330,741,639 out=103,945,320 elapsed=155.5s

  [9911/17668] intraday_2241.csv.gz  in=330,758,743 out=103,945,320 elapsed=155.5s

  [9912/17668] intraday_2243.csv.gz  in=330,773,290 out=103,945,320 elapsed=155.5s

  [9913/17668] intraday_2244.csv.gz  in=330,787,875 out=103,945,320 elapsed=155.5s

  [9914/17668] intraday_2246.csv.gz  in=330,800,882 out=103,945,320 elapsed=155.6s

  [9915/17668] intraday_2247.csv.gz  in=330,814,115 out=103,945,320 elapsed=155.6s

  [9916/17668] intraday_2245.csv.gz  in=330,826,449 out=103,945,320 elapsed=155.6s

  [9917/17668] intraday_2248.csv.gz  in=330,837,620 out=103,945,320 elapsed=155.6s

  [9918/17668] intraday_2249.csv.gz  in=330,850,780 out=103,945,320 elapsed=155.6s

  [9919/17668] intraday_2250.csv.gz  in=330,862,360 out=103,945,320 elapsed=155.6s

  [9920/17668] intraday_2251.csv.gz  in=330,873,460 out=103,945,320 elapsed=155.6s

  [9921/17668] intraday_2252.csv.gz  in=330,888,588 out=103,945,320 elapsed=155.6s

  [9922/17668] intraday_2253.csv.gz  in=330,899,260 out=103,945,320 elapsed=155.6s

  [9923/17668] intraday_2255.csv.gz  in=330,912,061 out=103,945,320 elapsed=155.6s

  [9924/17668] intraday_2254.csv.gz  in=330,926,668 out=103,945,320 elapsed=155.6s

  [9925/17668] intraday_2258.csv.gz  in=330,939,125 out=103,945,320 elapsed=155.6s

  [9926/17668] intraday_2257.csv.gz  in=330,951,741 out=103,945,320 elapsed=155.7s

  [9927/17668] intraday_2256.csv.gz  in=330,965,786 out=103,945,320 elapsed=155.7s

  [9928/17668] intraday_2259.csv.gz  in=330,979,178 out=103,945,320 elapsed=155.7s

  [9929/17668] intraday_2260.csv.gz  in=330,990,285 out=103,945,320 elapsed=155.7s

  [9930/17668] intraday_2263.csv.gz  in=331,001,087 out=103,945,320 elapsed=155.7s

  [9931/17668] intraday_2261.csv.gz  in=331,013,752 out=103,945,320 elapsed=155.7s

  [9932/17668] intraday_2262.csv.gz  in=331,030,296 out=103,945,320 elapsed=155.7s

  [9933/17668] intraday_2267.csv.gz  in=331,043,611 out=103,945,320 elapsed=155.7s

  [9934/17668] intraday_2264.csv.gz  in=331,056,214 out=103,945,320 elapsed=155.7s

  [9935/17668] intraday_2265.csv.gz  in=331,068,092 out=103,945,320 elapsed=155.7s

  [9936/17668] intraday_2266.csv.gz  in=331,079,195 out=103,945,320 elapsed=155.7s

  [9937/17668] intraday_2269.csv.gz  in=331,090,459 out=103,945,320 elapsed=155.8s

  [9938/17668] intraday_2268.csv.gz  in=331,104,534 out=103,945,320 elapsed=155.8s

  [9939/17668] intraday_2270.csv.gz  in=331,115,734 out=103,945,320 elapsed=155.8s

  [9940/17668] intraday_2271.csv.gz  in=331,128,915 out=103,945,320 elapsed=155.8s

  [9941/17668] intraday_2272.csv.gz  in=331,141,960 out=103,945,320 elapsed=155.8s

  [9942/17668] intraday_2273.csv.gz  in=331,155,083 out=103,945,320 elapsed=155.8s

  [9943/17668] intraday_2275.csv.gz  in=331,166,874 out=103,945,320 elapsed=155.8s

  [9944/17668] intraday_2274.csv.gz  in=331,178,996 out=103,945,320 elapsed=155.8s

  [9945/17668] intraday_2278.csv.gz  in=331,191,599 out=103,945,320 elapsed=155.8s

  [9946/17668] intraday_2276.csv.gz  in=331,201,835 out=103,945,320 elapsed=155.8s

  [9947/17668] intraday_2277.csv.gz  in=331,216,058 out=103,945,320 elapsed=155.9s

  [9948/17668] intraday_2279.csv.gz  in=331,232,064 out=103,945,320 elapsed=155.9s

  [9949/17668] intraday_2281.csv.gz  in=331,243,211 out=103,945,320 elapsed=155.9s

  [9950/17668] intraday_2282.csv.gz  in=331,255,145 out=103,945,320 elapsed=155.9s

  [9951/17668] intraday_2280.csv.gz  in=331,269,992 out=103,945,320 elapsed=155.9s

  [9952/17668] intraday_2283.csv.gz  in=331,282,028 out=103,945,320 elapsed=155.9s

  [9953/17668] intraday_2284.csv.gz  in=331,294,777 out=103,945,320 elapsed=155.9s

  [9954/17668] intraday_2286.csv.gz  in=331,305,582 out=103,945,320 elapsed=155.9s

  [9955/17668] intraday_2287.csv.gz  in=331,321,186 out=103,945,320 elapsed=155.9s

  [9956/17668] intraday_2285.csv.gz  in=331,336,226 out=103,945,320 elapsed=156.0s

  [9957/17668] intraday_2288.csv.gz  in=331,347,928 out=103,945,320 elapsed=156.0s

  [9958/17668] intraday_2289.csv.gz  in=331,362,140 out=103,945,320 elapsed=156.0s

  [9959/17668] intraday_2290.csv.gz  in=331,373,548 out=103,945,320 elapsed=156.0s

  [9960/17668] intraday_2292.csv.gz  in=331,383,961 out=103,945,320 elapsed=156.0s

  [9961/17668] intraday_2291.csv.gz  in=331,397,324 out=103,945,320 elapsed=156.0s

  [9962/17668] intraday_2294.csv.gz  in=331,409,709 out=103,945,320 elapsed=156.0s

  [9963/17668] intraday_2293.csv.gz  in=331,421,476 out=103,945,320 elapsed=156.0s

  [9964/17668] intraday_2295.csv.gz  in=331,435,118 out=103,945,320 elapsed=156.0s

  [9965/17668] intraday_2297.csv.gz  in=331,448,367 out=103,945,320 elapsed=156.0s

  [9966/17668] intraday_2296.csv.gz  in=331,461,529 out=103,945,320 elapsed=156.0s

  [9967/17668] intraday_2298.csv.gz  in=331,471,517 out=103,945,320 elapsed=156.0s

  [9968/17668] intraday_2300.csv.gz  in=331,483,402 out=103,945,320 elapsed=156.1s

  [9969/17668] intraday_2299.csv.gz  in=331,505,329 out=103,945,320 elapsed=156.1s

  [9970/17668] intraday_2301.csv.gz  in=331,521,207 out=103,945,320 elapsed=156.1s

  [9971/17668] intraday_2303.csv.gz  in=331,536,806 out=103,945,320 elapsed=156.1s

  [9972/17668] intraday_2302.csv.gz  in=331,557,689 out=103,945,320 elapsed=156.1s

  [9973/17668] intraday_2305.csv.gz  in=331,571,850 out=103,945,320 elapsed=156.1s

  [9974/17668] intraday_2304.csv.gz  in=331,584,329 out=103,945,320 elapsed=156.1s

  [9975/17668] intraday_2306.csv.gz  in=331,597,688 out=103,945,320 elapsed=156.1s

  [9976/17668] intraday_2307.csv.gz  in=331,612,478 out=103,945,320 elapsed=156.1s

  [9977/17668] intraday_2309.csv.gz  in=331,625,158 out=103,945,320 elapsed=156.2s

  [9978/17668] intraday_2308.csv.gz  in=331,637,280 out=103,945,320 elapsed=156.2s

  [9979/17668] intraday_2310.csv.gz  in=331,650,712 out=103,945,320 elapsed=156.2s

  [9980/17668] intraday_2311.csv.gz  in=331,664,132 out=103,945,320 elapsed=156.2s

  [9981/17668] intraday_2312.csv.gz  in=331,675,887 out=103,945,320 elapsed=156.2s

  [9982/17668] intraday_2313.csv.gz  in=331,689,136 out=103,945,320 elapsed=156.2s

  [9983/17668] intraday_2314.csv.gz  in=331,704,525 out=103,945,320 elapsed=156.2s

  [9984/17668] intraday_2315.csv.gz  in=331,716,431 out=103,945,320 elapsed=156.2s

  [9985/17668] intraday_2316.csv.gz  in=331,729,522 out=103,945,320 elapsed=156.2s

  [9986/17668] intraday_2317.csv.gz  in=331,741,984 out=103,945,320 elapsed=156.2s

  [9987/17668] intraday_2318.csv.gz  in=331,754,145 out=103,945,320 elapsed=156.2s

  [9988/17668] intraday_2319.csv.gz  in=331,768,773 out=103,945,320 elapsed=156.3s

  [9989/17668] intraday_2320.csv.gz  in=331,784,340 out=103,945,320 elapsed=156.3s

  [9990/17668] intraday_2322.csv.gz  in=331,797,577 out=103,945,320 elapsed=156.3s

  [9991/17668] intraday_2321.csv.gz  in=331,810,602 out=103,945,320 elapsed=156.3s

  [9992/17668] intraday_2323.csv.gz  in=331,823,974 out=103,945,320 elapsed=156.3s

  [9993/17668] intraday_2324.csv.gz  in=331,836,272 out=103,945,320 elapsed=156.3s

  [9994/17668] intraday_2326.csv.gz  in=331,849,613 out=103,945,320 elapsed=156.3s

  [9995/17668] intraday_2325.csv.gz  in=331,862,135 out=103,945,320 elapsed=156.3s

  [9996/17668] intraday_2327.csv.gz  in=331,877,213 out=103,945,320 elapsed=156.3s

  [9997/17668] intraday_2330.csv.gz  in=331,891,019 out=103,945,320 elapsed=156.3s

  [9998/17668] intraday_2329.csv.gz  in=331,903,705 out=103,945,320 elapsed=156.3s

  [9999/17668] intraday_2331.csv.gz  in=331,916,694 out=103,945,320 elapsed=156.4s

  [10000/17668] intraday_2328.csv.gz  in=331,933,182 out=103,945,320 elapsed=156.4s

  [10001/17668] intraday_2332.csv.gz  in=331,945,225 out=103,945,320 elapsed=156.4s

  [10002/17668] intraday_2333.csv.gz  in=331,957,040 out=103,945,320 elapsed=156.4s

  [10003/17668] intraday_2337.csv.gz  in=331,968,147 out=103,945,320 elapsed=156.4s

  [10004/17668] intraday_2335.csv.gz  in=331,980,771 out=103,945,320 elapsed=156.4s

  [10005/17668] intraday_2336.csv.gz  in=331,997,438 out=103,945,320 elapsed=156.4s

  [10006/17668] intraday_2334.csv.gz  in=332,015,453 out=103,945,320 elapsed=156.4s

  [10007/17668] intraday_2338.csv.gz  in=332,030,745 out=103,945,320 elapsed=156.4s

  [10008/17668] intraday_2341.csv.gz  in=332,044,084 out=103,945,320 elapsed=156.4s

  [10009/17668] intraday_2340.csv.gz  in=332,058,467 out=103,945,320 elapsed=156.4s

  [10010/17668] intraday_2339.csv.gz  in=332,070,867 out=103,945,320 elapsed=156.4s

  [10011/17668] intraday_2343.csv.gz  in=332,085,384 out=103,945,320 elapsed=156.5s

  [10012/17668] intraday_2342.csv.gz  in=332,106,601 out=103,945,320 elapsed=156.5s

  [10013/17668] intraday_2344.csv.gz  in=332,120,564 out=103,945,320 elapsed=156.5s

  [10014/17668] intraday_2345.csv.gz  in=332,135,507 out=103,945,320 elapsed=156.5s

  [10015/17668] intraday_2349.csv.gz  in=332,149,353 out=103,945,320 elapsed=156.5s

  [10016/17668] intraday_2346.csv.gz  in=332,160,951 out=103,945,320 elapsed=156.6s

  [10017/17668] intraday_2347.csv.gz  in=332,172,576 out=103,945,320 elapsed=156.6s

  [10018/17668] intraday_2348.csv.gz  in=332,186,142 out=103,945,320 elapsed=156.6s

  [10019/17668] intraday_2350.csv.gz  in=332,195,208 out=103,945,320 elapsed=156.6s

  [10020/17668] intraday_2351.csv.gz  in=332,204,155 out=103,945,320 elapsed=156.6s

  [10021/17668] intraday_2352.csv.gz  in=332,216,018 out=103,945,320 elapsed=156.6s

  [10022/17668] intraday_2353.csv.gz  in=332,217,427 out=103,945,320 elapsed=156.6s

  [10023/17668] intraday_2354.csv.gz  in=332,233,794 out=103,945,320 elapsed=156.6s

  [10024/17668] intraday_2355.csv.gz  in=332,247,888 out=103,945,320 elapsed=156.6s

  [10025/17668] intraday_2357.csv.gz  in=332,259,139 out=103,945,320 elapsed=156.6s

  [10026/17668] intraday_2356.csv.gz  in=332,271,701 out=103,945,320 elapsed=156.6s

  [10027/17668] intraday_2358.csv.gz  in=332,286,750 out=103,945,320 elapsed=156.6s

  [10028/17668] intraday_2359.csv.gz  in=332,308,553 out=103,945,320 elapsed=156.6s

  [10029/17668] intraday_2361.csv.gz  in=332,321,243 out=103,945,320 elapsed=156.7s

  [10030/17668] intraday_2362.csv.gz  in=332,339,012 out=103,945,320 elapsed=156.7s

  [10031/17668] intraday_2360.csv.gz  in=332,351,980 out=103,945,320 elapsed=156.7s

  [10032/17668] intraday_2364.csv.gz  in=332,361,795 out=103,945,320 elapsed=156.7s

  [10033/17668] intraday_2363.csv.gz  in=332,376,872 out=103,945,320 elapsed=156.7s

  [10034/17668] intraday_2366.csv.gz  in=332,390,799 out=103,945,320 elapsed=156.7s

  [10035/17668] intraday_2365.csv.gz  in=332,403,446 out=103,945,320 elapsed=156.7s

  [10036/17668] intraday_2367.csv.gz  in=332,414,111 out=103,945,320 elapsed=156.7s

  [10037/17668] intraday_2368.csv.gz  in=332,425,574 out=103,945,320 elapsed=156.7s

  [10038/17668] intraday_2370.csv.gz  in=332,438,632 out=103,945,320 elapsed=156.7s

  [10039/17668] intraday_2372.csv.gz  in=332,449,547 out=103,945,320 elapsed=156.7s

  [10040/17668] intraday_2371.csv.gz  in=332,462,100 out=103,945,320 elapsed=156.8s

  [10041/17668] intraday_2369.csv.gz  in=332,474,661 out=103,945,320 elapsed=156.8s

  [10042/17668] intraday_2373.csv.gz  in=332,486,727 out=103,945,320 elapsed=156.8s

  [10043/17668] intraday_2374.csv.gz  in=332,500,792 out=103,945,320 elapsed=156.8s

  [10044/17668] intraday_2375.csv.gz  in=332,512,824 out=103,945,320 elapsed=156.8s

  [10045/17668] intraday_2376.csv.gz  in=332,525,203 out=103,945,320 elapsed=156.8s

  [10046/17668] intraday_2380.csv.gz  in=332,537,565 out=103,945,320 elapsed=156.8s

  [10047/17668] intraday_2379.csv.gz  in=332,547,050 out=103,945,320 elapsed=156.8s

  [10048/17668] intraday_2378.csv.gz  in=332,559,976 out=103,945,320 elapsed=156.8s

  [10049/17668] intraday_2377.csv.gz  in=332,578,255 out=103,945,320 elapsed=156.8s

  [10050/17668] intraday_2384.csv.gz  in=332,592,772 out=103,945,320 elapsed=156.9s

  [10051/17668] intraday_2382.csv.gz  in=332,606,237 out=103,945,320 elapsed=156.9s

  [10052/17668] intraday_2383.csv.gz  in=332,621,562 out=103,945,320 elapsed=156.9s

  [10053/17668] intraday_2381.csv.gz  in=332,637,695 out=103,945,320 elapsed=156.9s

  [10054/17668] intraday_2386.csv.gz  in=332,649,997 out=103,945,320 elapsed=156.9s

  [10055/17668] intraday_2388.csv.gz  in=332,661,624 out=103,945,320 elapsed=156.9s

  [10056/17668] intraday_2385.csv.gz  in=332,673,682 out=103,945,320 elapsed=156.9s

  [10057/17668] intraday_2389.csv.gz  in=332,685,979 out=103,945,320 elapsed=156.9s

  [10058/17668] intraday_2387.csv.gz  in=332,709,255 out=103,945,320 elapsed=156.9s

  [10059/17668] intraday_2390.csv.gz  in=332,720,951 out=103,945,320 elapsed=157.0s

  [10060/17668] intraday_2391.csv.gz  in=332,732,348 out=103,945,320 elapsed=157.0s

  [10061/17668] intraday_2393.csv.gz  in=332,744,294 out=103,945,320 elapsed=157.0s

  [10062/17668] intraday_2392.csv.gz  in=332,755,973 out=103,945,320 elapsed=157.0s

  [10063/17668] intraday_2394.csv.gz  in=332,770,355 out=103,945,320 elapsed=157.0s

  [10064/17668] intraday_2395.csv.gz  in=332,784,355 out=103,945,320 elapsed=157.0s

  [10065/17668] intraday_2397.csv.gz  in=332,798,029 out=103,945,320 elapsed=157.0s

  [10066/17668] intraday_2396.csv.gz  in=332,810,266 out=103,945,320 elapsed=157.0s

  [10067/17668] intraday_2398.csv.gz  in=332,825,624 out=103,945,320 elapsed=157.0s

  [10068/17668] intraday_2399.csv.gz  in=332,839,304 out=103,945,320 elapsed=157.0s

  [10069/17668] intraday_2401.csv.gz  in=332,859,848 out=103,945,320 elapsed=157.0s

  [10070/17668] intraday_2400.csv.gz  in=332,877,133 out=103,945,320 elapsed=157.0s

  [10071/17668] intraday_2402.csv.gz  in=332,889,233 out=103,945,320 elapsed=157.0s

  [10072/17668] intraday_2403.csv.gz  in=332,901,440 out=103,945,320 elapsed=157.1s

  [10073/17668] intraday_2405.csv.gz  in=332,913,618 out=103,945,320 elapsed=157.1s

  [10074/17668] intraday_2404.csv.gz  in=332,933,982 out=103,945,320 elapsed=157.1s

  [10075/17668] intraday_2406.csv.gz  in=332,945,773 out=103,945,320 elapsed=157.1s

  [10076/17668] intraday_2408.csv.gz  in=332,961,943 out=103,945,320 elapsed=157.1s

  [10077/17668] intraday_2407.csv.gz  in=332,975,584 out=103,945,320 elapsed=157.1s

  [10078/17668] intraday_2409.csv.gz  in=332,988,884 out=103,945,320 elapsed=157.1s

  [10079/17668] intraday_2411.csv.gz  in=333,002,591 out=103,945,320 elapsed=157.1s

  [10080/17668] intraday_2412.csv.gz  in=333,015,224 out=103,945,320 elapsed=157.1s

  [10081/17668] intraday_2410.csv.gz  in=333,035,362 out=103,945,320 elapsed=157.2s

  [10082/17668] intraday_2413.csv.gz  in=333,048,762 out=103,945,320 elapsed=157.2s

  [10083/17668] intraday_2415.csv.gz  in=333,061,299 out=103,945,320 elapsed=157.2s

  [10084/17668] intraday_2414.csv.gz  in=333,076,336 out=103,945,320 elapsed=157.2s

  [10085/17668] intraday_2416.csv.gz  in=333,096,589 out=103,945,320 elapsed=157.2s

  [10086/17668] intraday_2418.csv.gz  in=333,110,775 out=103,945,320 elapsed=157.2s

  [10087/17668] intraday_2417.csv.gz  in=333,139,294 out=103,945,320 elapsed=157.2s

  [10088/17668] intraday_2419.csv.gz  in=333,153,674 out=103,945,320 elapsed=157.2s

  [10089/17668] intraday_2422.csv.gz  in=333,163,644 out=103,945,320 elapsed=157.2s

  [10090/17668] intraday_2420.csv.gz  in=333,178,099 out=103,945,320 elapsed=157.2s

  [10091/17668] intraday_2421.csv.gz  in=333,193,726 out=103,945,320 elapsed=157.3s

  [10092/17668] intraday_2423.csv.gz  in=333,205,705 out=103,945,320 elapsed=157.3s

  [10093/17668] intraday_2425.csv.gz  in=333,220,352 out=103,945,320 elapsed=157.3s

  [10094/17668] intraday_2427.csv.gz  in=333,232,817 out=103,945,320 elapsed=157.3s

  [10095/17668] intraday_2424.csv.gz  in=333,245,428 out=103,945,320 elapsed=157.3s

  [10096/17668] intraday_2426.csv.gz  in=333,254,961 out=103,945,320 elapsed=157.3s

  [10097/17668] intraday_2428.csv.gz  in=333,265,774 out=103,945,320 elapsed=157.3s

  [10098/17668] intraday_2429.csv.gz  in=333,282,360 out=103,945,320 elapsed=157.3s

  [10099/17668] intraday_2431.csv.gz  in=333,294,733 out=103,945,320 elapsed=157.3s

  [10100/17668] intraday_2430.csv.gz  in=333,306,877 out=103,945,320 elapsed=157.3s

  [10101/17668] intraday_2432.csv.gz  in=333,318,451 out=103,945,320 elapsed=157.3s

  [10102/17668] intraday_2433.csv.gz  in=333,329,187 out=103,945,320 elapsed=157.4s

  [10103/17668] intraday_2434.csv.gz  in=333,340,537 out=103,945,320 elapsed=157.4s

  [10104/17668] intraday_2435.csv.gz  in=333,355,187 out=103,945,320 elapsed=157.4s

  [10105/17668] intraday_2436.csv.gz  in=333,380,476 out=103,945,320 elapsed=157.4s

  [10106/17668] intraday_2437.csv.gz  in=333,393,129 out=103,945,320 elapsed=157.4s

  [10107/17668] intraday_2438.csv.gz  in=333,405,470 out=103,945,320 elapsed=157.4s

  [10108/17668] intraday_2439.csv.gz  in=333,416,823 out=103,945,320 elapsed=157.4s

  [10109/17668] intraday_2440.csv.gz  in=333,429,172 out=103,945,320 elapsed=157.4s

  [10110/17668] intraday_2441.csv.gz  in=333,443,905 out=103,945,320 elapsed=157.4s

  [10111/17668] intraday_2442.csv.gz  in=333,456,659 out=103,945,320 elapsed=157.4s

  [10112/17668] intraday_2443.csv.gz  in=333,470,391 out=103,945,320 elapsed=157.5s

  [10113/17668] intraday_2446.csv.gz  in=333,484,389 out=103,945,320 elapsed=157.5s

  [10114/17668] intraday_2444.csv.gz  in=333,497,247 out=103,945,320 elapsed=157.5s

  [10115/17668] intraday_2445.csv.gz  in=333,511,680 out=103,945,320 elapsed=157.5s

  [10116/17668] intraday_2447.csv.gz  in=333,526,312 out=103,945,320 elapsed=157.5s

  [10117/17668] intraday_2449.csv.gz  in=333,537,713 out=103,945,320 elapsed=157.5s

  [10118/17668] intraday_2448.csv.gz  in=333,551,618 out=103,945,320 elapsed=157.5s

  [10119/17668] intraday_2450.csv.gz  in=333,564,267 out=103,945,320 elapsed=157.5s

  [10120/17668] intraday_2451.csv.gz  in=333,578,183 out=103,945,320 elapsed=157.5s

  [10121/17668] intraday_2452.csv.gz  in=333,591,486 out=103,945,320 elapsed=157.5s

  [10122/17668] intraday_2453.csv.gz  in=333,602,776 out=103,945,320 elapsed=157.5s

  [10123/17668] intraday_2454.csv.gz  in=333,616,614 out=103,945,320 elapsed=157.6s

  [10124/17668] intraday_2455.csv.gz  in=333,631,741 out=103,945,320 elapsed=157.6s

  [10125/17668] intraday_2459.csv.gz  in=333,644,508 out=103,945,320 elapsed=157.6s

  [10126/17668] intraday_2458.csv.gz  in=333,654,742 out=103,945,320 elapsed=157.6s

  [10127/17668] intraday_2456.csv.gz  in=333,669,697 out=103,945,320 elapsed=157.6s

  [10128/17668] intraday_2457.csv.gz  in=333,685,960 out=103,945,320 elapsed=157.6s

  [10129/17668] intraday_2460.csv.gz  in=333,700,120 out=103,945,320 elapsed=157.7s

  [10130/17668] intraday_2461.csv.gz  in=333,715,056 out=103,945,320 elapsed=157.7s

  [10131/17668] intraday_2462.csv.gz  in=333,728,436 out=103,945,320 elapsed=157.7s

  [10132/17668] intraday_2463.csv.gz  in=333,742,869 out=103,945,320 elapsed=157.7s

  [10133/17668] intraday_2464.csv.gz  in=333,755,048 out=103,945,320 elapsed=157.7s

  [10134/17668] intraday_2465.csv.gz  in=333,768,480 out=103,945,320 elapsed=157.7s

  [10135/17668] intraday_2468.csv.gz  in=333,780,300 out=103,945,320 elapsed=157.7s

  [10136/17668] intraday_2466.csv.gz  in=333,793,349 out=103,945,320 elapsed=157.7s

  [10137/17668] intraday_2467.csv.gz  in=333,807,678 out=103,945,320 elapsed=157.7s

  [10138/17668] intraday_2469.csv.gz  in=333,824,906 out=103,945,320 elapsed=157.7s

  [10139/17668] intraday_2470.csv.gz  in=333,837,374 out=103,945,320 elapsed=157.8s

  [10140/17668] intraday_2471.csv.gz  in=333,851,587 out=103,945,320 elapsed=157.8s

  [10141/17668] intraday_2472.csv.gz  in=333,867,212 out=103,945,320 elapsed=157.8s

  [10142/17668] intraday_2473.csv.gz  in=333,880,319 out=103,945,320 elapsed=157.8s

  [10143/17668] intraday_2474.csv.gz  in=333,891,278 out=103,945,320 elapsed=157.8s

  [10144/17668] intraday_2476.csv.gz  in=333,904,642 out=103,945,320 elapsed=157.8s

  [10145/17668] intraday_2475.csv.gz  in=333,919,140 out=103,945,320 elapsed=157.8s

  [10146/17668] intraday_2477.csv.gz  in=333,935,274 out=103,945,320 elapsed=157.8s

  [10147/17668] intraday_2478.csv.gz  in=333,947,220 out=103,945,320 elapsed=157.9s

  [10148/17668] intraday_2480.csv.gz  in=333,961,201 out=103,945,320 elapsed=157.9s

  [10149/17668] intraday_2479.csv.gz  in=333,975,303 out=103,945,320 elapsed=157.9s

  [10150/17668] intraday_2481.csv.gz  in=333,990,837 out=103,945,320 elapsed=157.9s

  [10151/17668] intraday_2482.csv.gz  in=334,005,121 out=103,945,320 elapsed=157.9s

  [10152/17668] intraday_2483.csv.gz  in=334,020,023 out=103,945,320 elapsed=157.9s

  [10153/17668] intraday_2484.csv.gz  in=334,035,835 out=103,945,320 elapsed=157.9s

  [10154/17668] intraday_2485.csv.gz  in=334,049,210 out=103,945,320 elapsed=157.9s

  [10155/17668] intraday_2486.csv.gz  in=334,063,567 out=103,945,320 elapsed=157.9s

  [10156/17668] intraday_2487.csv.gz  in=334,075,356 out=103,945,320 elapsed=157.9s

  [10157/17668] intraday_2489.csv.gz  in=334,087,161 out=103,945,320 elapsed=158.0s

  [10158/17668] intraday_2488.csv.gz  in=334,099,377 out=103,945,320 elapsed=158.0s

  [10159/17668] intraday_2490.csv.gz  in=334,114,052 out=103,945,320 elapsed=158.0s

  [10160/17668] intraday_2492.csv.gz  in=334,122,114 out=103,945,320 elapsed=158.0s

  [10161/17668] intraday_2491.csv.gz  in=334,130,831 out=103,945,320 elapsed=158.0s

  [10162/17668] intraday_2493.csv.gz  in=334,142,320 out=103,945,320 elapsed=158.0s

  [10163/17668] intraday_2494.csv.gz  in=334,157,617 out=103,945,320 elapsed=158.0s

  [10164/17668] intraday_2495.csv.gz  in=334,171,532 out=103,945,320 elapsed=158.0s

  [10165/17668] intraday_2496.csv.gz  in=334,183,345 out=103,945,320 elapsed=158.0s

  [10166/17668] intraday_2497.csv.gz  in=334,194,334 out=103,945,320 elapsed=158.0s

  [10167/17668] intraday_2498.csv.gz  in=334,209,078 out=103,945,320 elapsed=158.0s

  [10168/17668] intraday_2499.csv.gz  in=334,222,981 out=103,945,320 elapsed=158.1s

  [10169/17668] intraday_2501.csv.gz  in=334,234,841 out=103,945,320 elapsed=158.1s

  [10170/17668] intraday_2500.csv.gz  in=334,247,291 out=103,945,320 elapsed=158.1s

  [10171/17668] intraday_2502.csv.gz  in=334,260,650 out=103,945,320 elapsed=158.1s

  [10172/17668] intraday_2503.csv.gz  in=334,275,074 out=103,945,320 elapsed=158.1s

  [10173/17668] intraday_2504.csv.gz  in=334,284,163 out=103,945,320 elapsed=158.1s

  [10174/17668] intraday_2505.csv.gz  in=334,295,329 out=103,945,320 elapsed=158.1s

  [10175/17668] intraday_2506.csv.gz  in=334,308,263 out=103,945,320 elapsed=158.1s

  [10176/17668] intraday_2507.csv.gz  in=334,319,003 out=103,945,320 elapsed=158.1s

  [10177/17668] intraday_2508.csv.gz  in=334,330,339 out=103,945,320 elapsed=158.1s

  [10178/17668] intraday_2509.csv.gz  in=334,342,224 out=103,945,320 elapsed=158.2s

  [10179/17668] intraday_2510.csv.gz  in=334,354,350 out=103,945,320 elapsed=158.2s

  [10180/17668] intraday_2511.csv.gz  in=334,366,359 out=103,945,320 elapsed=158.2s

  [10181/17668] intraday_2512.csv.gz  in=334,378,115 out=103,945,320 elapsed=158.2s

  [10182/17668] intraday_2513.csv.gz  in=334,389,392 out=103,945,320 elapsed=158.2s

  [10183/17668] intraday_2515.csv.gz  in=334,401,123 out=103,945,320 elapsed=158.2s

  [10184/17668] intraday_2516.csv.gz  in=334,413,254 out=103,945,320 elapsed=158.2s

  [10185/17668] intraday_2514.csv.gz  in=334,426,300 out=103,945,320 elapsed=158.2s

  [10186/17668] intraday_2517.csv.gz  in=334,438,886 out=103,945,320 elapsed=158.2s

  [10187/17668] intraday_2518.csv.gz  in=334,450,781 out=103,945,320 elapsed=158.2s

  [10188/17668] intraday_2520.csv.gz  in=334,462,617 out=103,945,320 elapsed=158.2s

  [10189/17668] intraday_2519.csv.gz  in=334,471,434 out=103,945,320 elapsed=158.2s

  [10190/17668] intraday_2521.csv.gz  in=334,484,905 out=103,945,320 elapsed=158.3s

  [10191/17668] intraday_2522.csv.gz  in=334,497,304 out=103,945,320 elapsed=158.3s

  [10192/17668] intraday_2524.csv.gz  in=334,510,675 out=103,945,320 elapsed=158.3s

  [10193/17668] intraday_2523.csv.gz  in=334,525,150 out=103,945,320 elapsed=158.3s

  [10194/17668] intraday_2525.csv.gz  in=334,536,521 out=103,945,320 elapsed=158.3s

  [10195/17668] intraday_2526.csv.gz  in=334,549,186 out=103,945,320 elapsed=158.3s

  [10196/17668] intraday_2528.csv.gz  in=334,560,306 out=103,945,320 elapsed=158.3s

  [10197/17668] intraday_2529.csv.gz  in=334,573,392 out=103,945,320 elapsed=158.3s

  [10198/17668] intraday_2527.csv.gz  in=334,586,223 out=103,945,320 elapsed=158.3s

  [10199/17668] intraday_2530.csv.gz  in=334,597,775 out=103,945,320 elapsed=158.3s

  [10200/17668] intraday_2531.csv.gz  in=334,608,152 out=103,945,320 elapsed=158.3s

  [10201/17668] intraday_2533.csv.gz  in=334,618,105 out=103,945,320 elapsed=158.4s

  [10202/17668] intraday_2532.csv.gz  in=334,630,378 out=103,945,320 elapsed=158.4s

  [10203/17668] intraday_2535.csv.gz  in=334,642,531 out=103,945,320 elapsed=158.4s

  [10204/17668] intraday_2534.csv.gz  in=334,657,593 out=103,945,320 elapsed=158.4s

  [10205/17668] intraday_2538.csv.gz  in=334,669,878 out=103,945,320 elapsed=158.4s

  [10206/17668] intraday_2536.csv.gz  in=334,684,224 out=103,945,320 elapsed=158.4s

  [10207/17668] intraday_2537.csv.gz  in=334,696,009 out=103,945,320 elapsed=158.4s

  [10208/17668] intraday_2539.csv.gz  in=334,708,062 out=103,945,320 elapsed=158.4s

  [10209/17668] intraday_2540.csv.gz  in=334,718,321 out=103,945,320 elapsed=158.4s

  [10210/17668] intraday_2542.csv.gz  in=334,730,418 out=103,945,320 elapsed=158.4s

  [10211/17668] intraday_2541.csv.gz  in=334,742,527 out=103,945,320 elapsed=158.5s

  [10212/17668] intraday_2544.csv.gz  in=334,755,562 out=103,945,320 elapsed=158.5s

  [10213/17668] intraday_2543.csv.gz  in=334,765,762 out=103,945,320 elapsed=158.5s

  [10214/17668] intraday_2545.csv.gz  in=334,776,672 out=103,945,320 elapsed=158.5s

  [10215/17668] intraday_2546.csv.gz  in=334,788,036 out=103,945,320 elapsed=158.5s

  [10216/17668] intraday_2547.csv.gz  in=334,801,647 out=103,945,320 elapsed=158.5s

  [10217/17668] intraday_2548.csv.gz  in=334,815,643 out=103,945,320 elapsed=158.5s

  [10218/17668] intraday_2549.csv.gz  in=334,826,550 out=103,945,320 elapsed=158.5s

  [10219/17668] intraday_2551.csv.gz  in=334,839,952 out=103,945,320 elapsed=158.5s

  [10220/17668] intraday_2552.csv.gz  in=334,853,491 out=103,945,320 elapsed=158.5s

  [10221/17668] intraday_2550.csv.gz  in=334,864,494 out=103,945,320 elapsed=158.5s

  [10222/17668] intraday_2553.csv.gz  in=334,876,938 out=103,945,320 elapsed=158.5s

  [10223/17668] intraday_2554.csv.gz  in=334,887,702 out=103,945,320 elapsed=158.6s

  [10224/17668] intraday_2555.csv.gz  in=334,898,637 out=103,945,320 elapsed=158.6s

  [10225/17668] intraday_2558.csv.gz  in=334,910,458 out=103,945,320 elapsed=158.6s

  [10226/17668] intraday_2556.csv.gz  in=334,920,344 out=103,945,320 elapsed=158.6s

  [10227/17668] intraday_2557.csv.gz  in=334,934,800 out=103,945,320 elapsed=158.6s

  [10228/17668] intraday_2559.csv.gz  in=334,947,879 out=103,945,320 elapsed=158.6s

  [10229/17668] intraday_2560.csv.gz  in=334,960,870 out=103,945,320 elapsed=158.6s

  [10230/17668] intraday_2561.csv.gz  in=334,972,326 out=103,945,320 elapsed=158.6s

  [10231/17668] intraday_2562.csv.gz  in=334,983,947 out=103,945,320 elapsed=158.6s

  [10232/17668] intraday_2563.csv.gz  in=334,996,483 out=103,945,320 elapsed=158.6s

  [10233/17668] intraday_2564.csv.gz  in=335,007,064 out=103,945,320 elapsed=158.7s

  [10234/17668] intraday_2565.csv.gz  in=335,019,713 out=103,945,320 elapsed=158.7s

  [10235/17668] intraday_2567.csv.gz  in=335,031,358 out=103,945,320 elapsed=158.7s

  [10236/17668] intraday_2566.csv.gz  in=335,041,068 out=103,945,320 elapsed=158.7s

  [10237/17668] intraday_2568.csv.gz  in=335,053,366 out=103,945,320 elapsed=158.7s

  [10238/17668] intraday_2570.csv.gz  in=335,065,045 out=103,945,320 elapsed=158.7s

  [10239/17668] intraday_2569.csv.gz  in=335,076,731 out=103,945,320 elapsed=158.7s

  [10240/17668] intraday_2571.csv.gz  in=335,088,922 out=103,945,320 elapsed=158.7s

  [10241/17668] intraday_2572.csv.gz  in=335,099,250 out=103,945,320 elapsed=158.7s

  [10242/17668] intraday_2574.csv.gz  in=335,111,036 out=103,945,320 elapsed=158.7s

  [10243/17668] intraday_2573.csv.gz  in=335,122,203 out=103,945,320 elapsed=158.8s

  [10244/17668] intraday_2575.csv.gz  in=335,136,670 out=103,945,320 elapsed=158.8s

  [10245/17668] intraday_2576.csv.gz  in=335,148,417 out=103,945,320 elapsed=158.8s

  [10246/17668] intraday_2577.csv.gz  in=335,160,804 out=103,945,320 elapsed=158.8s

  [10247/17668] intraday_2578.csv.gz  in=335,173,332 out=103,945,320 elapsed=158.8s

  [10248/17668] intraday_2580.csv.gz  in=335,185,749 out=103,945,320 elapsed=158.8s

  [10249/17668] intraday_2579.csv.gz  in=335,197,486 out=103,945,320 elapsed=158.8s

  [10250/17668] intraday_2581.csv.gz  in=335,212,770 out=103,945,320 elapsed=158.8s

  [10251/17668] intraday_2582.csv.gz  in=335,223,418 out=103,945,320 elapsed=158.8s

  [10252/17668] intraday_2583.csv.gz  in=335,237,885 out=103,945,320 elapsed=158.8s

  [10253/17668] intraday_2584.csv.gz  in=335,250,534 out=103,945,320 elapsed=158.8s

  [10254/17668] intraday_2585.csv.gz  in=335,263,961 out=103,945,320 elapsed=158.9s

  [10255/17668] intraday_2586.csv.gz  in=335,277,681 out=103,945,320 elapsed=158.9s

  [10256/17668] intraday_2587.csv.gz  in=335,290,500 out=103,945,320 elapsed=158.9s

  [10257/17668] intraday_2589.csv.gz  in=335,302,949 out=103,945,320 elapsed=158.9s

  [10258/17668] intraday_2590.csv.gz  in=335,313,501 out=103,945,320 elapsed=158.9s

  [10259/17668] intraday_2588.csv.gz  in=335,325,630 out=103,945,320 elapsed=158.9s

  [10260/17668] intraday_2591.csv.gz  in=335,337,156 out=103,945,320 elapsed=158.9s

  [10261/17668] intraday_2592.csv.gz  in=335,348,226 out=103,945,320 elapsed=158.9s

  [10262/17668] intraday_2593.csv.gz  in=335,361,508 out=103,945,320 elapsed=158.9s

  [10263/17668] intraday_2594.csv.gz  in=335,372,559 out=103,945,320 elapsed=158.9s

  [10264/17668] intraday_2595.csv.gz  in=335,385,703 out=103,945,320 elapsed=159.0s

  [10265/17668] intraday_2596.csv.gz  in=335,397,902 out=103,945,320 elapsed=159.0s

  [10266/17668] intraday_2597.csv.gz  in=335,411,414 out=103,945,320 elapsed=159.0s

  [10267/17668] intraday_2598.csv.gz  in=335,422,512 out=103,945,320 elapsed=159.0s

  [10268/17668] intraday_2599.csv.gz  in=335,435,405 out=103,945,320 elapsed=159.0s

  [10269/17668] intraday_2600.csv.gz  in=335,450,177 out=103,945,320 elapsed=159.0s

  [10270/17668] intraday_2602.csv.gz  in=335,463,450 out=103,945,320 elapsed=159.0s

  [10271/17668] intraday_2604.csv.gz  in=335,475,367 out=103,945,320 elapsed=159.0s

  [10272/17668] intraday_2603.csv.gz  in=335,488,930 out=103,945,320 elapsed=159.0s

  [10273/17668] intraday_2601.csv.gz  in=335,502,681 out=103,945,320 elapsed=159.0s

  [10274/17668] intraday_2607.csv.gz  in=335,515,253 out=103,945,320 elapsed=159.1s

  [10275/17668] intraday_2606.csv.gz  in=335,528,467 out=103,945,320 elapsed=159.1s

  [10276/17668] intraday_2605.csv.gz  in=335,541,066 out=103,945,320 elapsed=159.1s

  [10277/17668] intraday_2608.csv.gz  in=335,556,818 out=103,945,320 elapsed=159.1s

  [10278/17668] intraday_2609.csv.gz  in=335,570,437 out=103,945,320 elapsed=159.1s

  [10279/17668] intraday_2610.csv.gz  in=335,583,162 out=103,945,320 elapsed=159.1s

  [10280/17668] intraday_2612.csv.gz  in=335,593,013 out=103,945,320 elapsed=159.1s

  [10281/17668] intraday_2611.csv.gz  in=335,607,046 out=103,945,320 elapsed=159.1s

  [10282/17668] intraday_2613.csv.gz  in=335,619,642 out=103,945,320 elapsed=159.1s

  [10283/17668] intraday_2614.csv.gz  in=335,630,450 out=103,945,320 elapsed=159.2s

  [10284/17668] intraday_2616.csv.gz  in=335,644,236 out=103,945,320 elapsed=159.2s

  [10285/17668] intraday_2615.csv.gz  in=335,658,677 out=103,945,320 elapsed=159.2s

  [10286/17668] intraday_2618.csv.gz  in=335,670,618 out=103,945,320 elapsed=159.2s

  [10287/17668] intraday_2617.csv.gz  in=335,686,744 out=103,945,320 elapsed=159.2s

  [10288/17668] intraday_2619.csv.gz  in=335,700,685 out=103,945,320 elapsed=159.2s

  [10289/17668] intraday_2620.csv.gz  in=335,714,285 out=103,945,320 elapsed=159.2s

  [10290/17668] intraday_2621.csv.gz  in=335,727,901 out=103,945,320 elapsed=159.2s

  [10291/17668] intraday_2622.csv.gz  in=335,740,995 out=103,945,320 elapsed=159.2s

  [10292/17668] intraday_2624.csv.gz  in=335,755,336 out=103,945,320 elapsed=159.2s

  [10293/17668] intraday_2623.csv.gz  in=335,770,930 out=103,945,320 elapsed=159.2s

  [10294/17668] intraday_2625.csv.gz  in=335,784,523 out=103,945,320 elapsed=159.2s

  [10295/17668] intraday_2627.csv.gz  in=335,794,428 out=103,945,320 elapsed=159.3s

  [10296/17668] intraday_2626.csv.gz  in=335,807,282 out=103,945,320 elapsed=159.3s

  [10297/17668] intraday_2628.csv.gz  in=335,820,099 out=103,945,320 elapsed=159.3s

  [10298/17668] intraday_2629.csv.gz  in=335,832,255 out=103,945,320 elapsed=159.3s

  [10299/17668] intraday_2630.csv.gz  in=335,844,132 out=103,945,320 elapsed=159.3s

  [10300/17668] intraday_2631.csv.gz  in=335,851,203 out=103,945,320 elapsed=159.3s

  [10301/17668] intraday_2634.csv.gz  in=335,853,404 out=103,945,320 elapsed=159.3s

  [10302/17668] intraday_2632.csv.gz  in=335,863,667 out=103,945,320 elapsed=159.3s

  [10303/17668] intraday_2633.csv.gz  in=335,869,690 out=103,945,320 elapsed=159.3s

  [10304/17668] intraday_2635.csv.gz  in=335,869,815 out=103,945,320 elapsed=159.3s

  [10305/17668] intraday_2638.csv.gz  in=335,869,896 out=103,945,320 elapsed=159.3s

  [10306/17668] intraday_2637.csv.gz  in=335,870,120 out=103,945,320 elapsed=159.4s

  [10307/17668] intraday_2639.csv.gz  in=335,870,231 out=103,945,320 elapsed=159.4s

  [10308/17668] intraday_2636.csv.gz  in=335,882,693 out=103,945,320 elapsed=159.4s

  [10309/17668] intraday_2641.csv.gz  in=335,882,726 out=103,945,320 elapsed=159.4s

  [10310/17668] intraday_2643.csv.gz  in=335,882,738 out=103,945,320 elapsed=159.4s

  [10311/17668] intraday_2642.csv.gz  in=335,882,749 out=103,945,320 elapsed=159.4s

  [10312/17668] intraday_2640.csv.gz  in=335,889,238 out=103,945,320 elapsed=159.4s

  [10313/17668] intraday_2644.csv.gz  in=335,889,280 out=103,945,320 elapsed=159.4s

  [10314/17668] intraday_2646.csv.gz  in=335,889,351 out=103,945,320 elapsed=159.4s

  [10315/17668] intraday_2645.csv.gz  in=335,890,127 out=103,945,320 elapsed=159.4s

  [10316/17668] intraday_2647.csv.gz  in=335,901,270 out=103,945,320 elapsed=159.4s

  [10317/17668] intraday_2648.csv.gz  in=335,901,314 out=103,945,320 elapsed=159.4s

  [10318/17668] intraday_2651.csv.gz  in=335,901,401 out=103,945,320 elapsed=159.4s

  [10319/17668] intraday_2649.csv.gz  in=335,901,430 out=103,945,320 elapsed=159.4s

  [10320/17668] intraday_2650.csv.gz  in=335,916,090 out=103,945,320 elapsed=159.5s

  [10321/17668] intraday_2652.csv.gz  in=335,916,105 out=103,945,320 elapsed=159.5s

  [10322/17668] intraday_2654.csv.gz  in=335,916,436 out=103,945,320 elapsed=159.5s

  [10323/17668] intraday_2655.csv.gz  in=335,916,602 out=103,945,320 elapsed=159.5s

  [10324/17668] intraday_2653.csv.gz  in=335,922,456 out=103,945,320 elapsed=159.5s

  [10325/17668] intraday_2656.csv.gz  in=335,924,401 out=103,945,320 elapsed=159.5s

  [10326/17668] intraday_2657.csv.gz  in=335,927,601 out=103,945,320 elapsed=159.5s

  [10327/17668] intraday_2659.csv.gz  in=335,927,624 out=103,945,320 elapsed=159.5s

  [10328/17668] intraday_2658.csv.gz  in=335,931,784 out=103,945,320 elapsed=159.5s

  [10329/17668] intraday_2660.csv.gz  in=335,935,262 out=103,945,320 elapsed=159.5s

  [10330/17668] intraday_2663.csv.gz  in=335,935,422 out=103,945,320 elapsed=159.5s

  [10331/17668] intraday_2661.csv.gz  in=335,944,097 out=103,945,320 elapsed=159.5s

  [10332/17668] intraday_2662.csv.gz  in=335,944,140 out=103,945,320 elapsed=159.5s

  [10333/17668] intraday_2664.csv.gz  in=335,944,228 out=103,945,320 elapsed=159.5s

  [10334/17668] intraday_2667.csv.gz  in=335,956,680 out=103,945,320 elapsed=159.6s

  [10335/17668] intraday_2668.csv.gz  in=335,966,981 out=103,945,320 elapsed=159.6s

  [10336/17668] intraday_2666.csv.gz  in=335,980,283 out=103,945,320 elapsed=159.6s

  [10337/17668] intraday_2665.csv.gz  in=335,995,117 out=103,945,320 elapsed=159.6s

  [10338/17668] intraday_2669.csv.gz  in=336,009,022 out=103,945,320 elapsed=159.6s

  [10339/17668] intraday_2671.csv.gz  in=336,020,465 out=103,945,320 elapsed=159.6s

  [10340/17668] intraday_2670.csv.gz  in=336,033,694 out=103,945,320 elapsed=159.6s

  [10341/17668] intraday_2672.csv.gz  in=336,047,731 out=103,945,320 elapsed=159.6s

  [10342/17668] intraday_2673.csv.gz  in=336,060,497 out=103,945,320 elapsed=159.6s

  [10343/17668] intraday_2676.csv.gz  in=336,071,959 out=103,945,320 elapsed=159.6s

  [10344/17668] intraday_2675.csv.gz  in=336,080,637 out=103,945,320 elapsed=159.7s

  [10345/17668] intraday_2674.csv.gz  in=336,093,854 out=103,945,320 elapsed=159.7s

  [10346/17668] intraday_2680.csv.gz  in=336,103,727 out=103,945,320 elapsed=159.7s

  [10347/17668] intraday_2677.csv.gz  in=336,114,730 out=103,945,320 elapsed=159.7s

  [10348/17668] intraday_2678.csv.gz  in=336,131,592 out=103,945,320 elapsed=159.7s

  [10349/17668] intraday_2679.csv.gz  in=336,142,132 out=103,945,320 elapsed=159.7s

  [10350/17668] intraday_2681.csv.gz  in=336,154,456 out=103,945,320 elapsed=159.7s

  [10351/17668] intraday_2682.csv.gz  in=336,166,142 out=103,945,320 elapsed=159.7s

  [10352/17668] intraday_2683.csv.gz  in=336,176,400 out=103,945,320 elapsed=159.7s

  [10353/17668] intraday_2685.csv.gz  in=336,188,323 out=103,945,320 elapsed=159.8s

  [10354/17668] intraday_2684.csv.gz  in=336,201,313 out=103,945,320 elapsed=159.8s

  [10355/17668] intraday_2686.csv.gz  in=336,213,668 out=103,945,320 elapsed=159.8s

  [10356/17668] intraday_2689.csv.gz  in=336,224,913 out=103,945,320 elapsed=159.8s

  [10357/17668] intraday_2688.csv.gz  in=336,235,880 out=103,945,320 elapsed=159.8s

  [10358/17668] intraday_2687.csv.gz  in=336,247,202 out=103,945,320 elapsed=159.8s

  [10359/17668] intraday_2690.csv.gz  in=336,256,699 out=103,945,320 elapsed=159.8s

  [10360/17668] intraday_2691.csv.gz  in=336,268,489 out=103,945,320 elapsed=159.8s

  [10361/17668] intraday_2693.csv.gz  in=336,280,720 out=103,945,320 elapsed=159.8s

  [10362/17668] intraday_2692.csv.gz  in=336,292,508 out=103,945,320 elapsed=159.8s

  [10363/17668] intraday_2694.csv.gz  in=336,306,159 out=103,945,320 elapsed=159.9s

  [10364/17668] intraday_2696.csv.gz  in=336,316,905 out=103,945,320 elapsed=159.9s

  [10365/17668] intraday_2695.csv.gz  in=336,329,553 out=103,945,320 elapsed=159.9s

  [10366/17668] intraday_2697.csv.gz  in=336,341,380 out=103,945,320 elapsed=159.9s

  [10367/17668] intraday_2698.csv.gz  in=336,354,066 out=103,945,320 elapsed=159.9s

  [10368/17668] intraday_2700.csv.gz  in=336,367,472 out=103,945,320 elapsed=159.9s

  [10369/17668] intraday_2701.csv.gz  in=336,376,373 out=103,945,320 elapsed=159.9s

  [10370/17668] intraday_2699.csv.gz  in=336,387,182 out=103,945,320 elapsed=159.9s

  [10371/17668] intraday_2702.csv.gz  in=336,398,498 out=103,945,320 elapsed=159.9s

  [10372/17668] intraday_2703.csv.gz  in=336,408,136 out=103,945,320 elapsed=159.9s

  [10373/17668] intraday_2705.csv.gz  in=336,420,640 out=103,945,320 elapsed=159.9s

  [10374/17668] intraday_2704.csv.gz  in=336,431,835 out=103,945,320 elapsed=159.9s

  [10375/17668] intraday_2707.csv.gz  in=336,447,807 out=103,945,320 elapsed=159.9s

  [10376/17668] intraday_2706.csv.gz  in=336,461,121 out=103,945,320 elapsed=160.0s

  [10377/17668] intraday_2709.csv.gz  in=336,472,286 out=103,945,320 elapsed=160.0s

  [10378/17668] intraday_2708.csv.gz  in=336,485,129 out=103,945,320 elapsed=160.0s

  [10379/17668] intraday_2710.csv.gz  in=336,495,969 out=103,945,320 elapsed=160.0s

  [10380/17668] intraday_2711.csv.gz  in=336,507,462 out=103,945,320 elapsed=160.0s

  [10381/17668] intraday_2714.csv.gz  in=336,517,162 out=103,945,320 elapsed=160.0s

  [10382/17668] intraday_2715.csv.gz  in=336,528,341 out=103,945,320 elapsed=160.0s

  [10383/17668] intraday_2713.csv.gz  in=336,539,673 out=103,945,320 elapsed=160.0s

  [10384/17668] intraday_2712.csv.gz  in=336,566,676 out=103,945,320 elapsed=160.0s

  [10385/17668] intraday_2716.csv.gz  in=336,576,620 out=103,945,320 elapsed=160.1s

  [10386/17668] intraday_2718.csv.gz  in=336,587,011 out=103,945,320 elapsed=160.1s

  [10387/17668] intraday_2717.csv.gz  in=336,601,634 out=103,945,320 elapsed=160.1s

  [10388/17668] intraday_2719.csv.gz  in=336,614,171 out=103,945,320 elapsed=160.1s

  [10389/17668] intraday_2720.csv.gz  in=336,626,114 out=103,945,320 elapsed=160.1s

  [10390/17668] intraday_2722.csv.gz  in=336,638,518 out=103,945,320 elapsed=160.1s

  [10391/17668] intraday_2723.csv.gz  in=336,650,189 out=103,945,320 elapsed=160.1s

  [10392/17668] intraday_2721.csv.gz  in=336,659,105 out=103,945,320 elapsed=160.1s

  [10393/17668] intraday_2725.csv.gz  in=336,670,143 out=103,945,320 elapsed=160.1s

  [10394/17668] intraday_2724.csv.gz  in=336,684,473 out=103,945,320 elapsed=160.1s

  [10395/17668] intraday_2726.csv.gz  in=336,695,881 out=103,945,320 elapsed=160.2s

  [10396/17668] intraday_2727.csv.gz  in=336,705,293 out=103,945,320 elapsed=160.2s

  [10397/17668] intraday_2728.csv.gz  in=336,717,033 out=103,945,320 elapsed=160.2s

  [10398/17668] intraday_2729.csv.gz  in=336,731,240 out=103,945,320 elapsed=160.2s

  [10399/17668] intraday_2730.csv.gz  in=336,740,846 out=103,945,320 elapsed=160.2s

  [10400/17668] intraday_2731.csv.gz  in=336,754,227 out=103,945,320 elapsed=160.2s

  [10401/17668] intraday_2732.csv.gz  in=336,766,836 out=103,945,320 elapsed=160.2s

  [10402/17668] intraday_2733.csv.gz  in=336,776,067 out=103,945,320 elapsed=160.2s

  [10403/17668] intraday_2735.csv.gz  in=336,787,286 out=103,945,320 elapsed=160.2s

  [10404/17668] intraday_2736.csv.gz  in=336,799,402 out=103,945,320 elapsed=160.2s

  [10405/17668] intraday_2737.csv.gz  in=336,809,110 out=103,945,320 elapsed=160.2s

  [10406/17668] intraday_2734.csv.gz  in=336,832,327 out=103,945,320 elapsed=160.2s

  [10407/17668] intraday_2739.csv.gz  in=336,843,404 out=103,945,320 elapsed=160.3s

  [10408/17668] intraday_2738.csv.gz  in=336,853,978 out=103,945,320 elapsed=160.3s

  [10409/17668] intraday_2741.csv.gz  in=336,865,645 out=103,945,320 elapsed=160.3s

  [10410/17668] intraday_2740.csv.gz  in=336,876,698 out=103,945,320 elapsed=160.3s

  [10411/17668] intraday_2742.csv.gz  in=336,888,132 out=103,945,320 elapsed=160.3s

  [10412/17668] intraday_2743.csv.gz  in=336,899,810 out=103,945,320 elapsed=160.3s

  [10413/17668] intraday_2744.csv.gz  in=336,910,026 out=103,945,320 elapsed=160.3s

  [10414/17668] intraday_2745.csv.gz  in=336,920,394 out=103,945,320 elapsed=160.3s

  [10415/17668] intraday_2747.csv.gz  in=336,935,076 out=103,945,320 elapsed=160.3s

  [10416/17668] intraday_2746.csv.gz  in=336,947,921 out=103,945,320 elapsed=160.4s

  [10417/17668] intraday_2748.csv.gz  in=336,958,936 out=103,945,320 elapsed=160.4s

  [10418/17668] intraday_2749.csv.gz  in=336,967,727 out=103,945,320 elapsed=160.4s

  [10419/17668] intraday_2751.csv.gz  in=336,979,522 out=103,945,320 elapsed=160.4s

  [10420/17668] intraday_2750.csv.gz  in=336,989,928 out=103,945,320 elapsed=160.4s

  [10421/17668] intraday_2752.csv.gz  in=337,001,933 out=103,945,320 elapsed=160.4s

  [10422/17668] intraday_2753.csv.gz  in=337,015,565 out=103,945,320 elapsed=160.4s

  [10423/17668] intraday_2754.csv.gz  in=337,027,033 out=103,945,320 elapsed=160.4s

  [10424/17668] intraday_2756.csv.gz  in=337,039,083 out=103,945,320 elapsed=160.4s

  [10425/17668] intraday_2755.csv.gz  in=337,051,661 out=103,945,320 elapsed=160.4s

  [10426/17668] intraday_2757.csv.gz  in=337,064,600 out=103,945,320 elapsed=160.4s

  [10427/17668] intraday_2758.csv.gz  in=337,076,387 out=103,945,320 elapsed=160.4s

  [10428/17668] intraday_2760.csv.gz  in=337,088,552 out=103,945,320 elapsed=160.5s

  [10429/17668] intraday_2761.csv.gz  in=337,099,654 out=103,945,320 elapsed=160.5s

  [10430/17668] intraday_2759.csv.gz  in=337,111,254 out=103,945,320 elapsed=160.5s

  [10431/17668] intraday_2762.csv.gz  in=337,123,102 out=103,945,320 elapsed=160.5s

  [10432/17668] intraday_2764.csv.gz  in=337,133,046 out=103,945,320 elapsed=160.5s

  [10433/17668] intraday_2763.csv.gz  in=337,144,737 out=103,945,320 elapsed=160.5s

  [10434/17668] intraday_2765.csv.gz  in=337,156,795 out=103,945,320 elapsed=160.5s

  [10435/17668] intraday_2766.csv.gz  in=337,167,343 out=103,945,320 elapsed=160.5s

  [10436/17668] intraday_2767.csv.gz  in=337,178,793 out=103,945,320 elapsed=160.5s

  [10437/17668] intraday_2768.csv.gz  in=337,192,342 out=103,945,320 elapsed=160.5s

  [10438/17668] intraday_2769.csv.gz  in=337,201,701 out=103,945,320 elapsed=160.5s

  [10439/17668] intraday_2772.csv.gz  in=337,215,515 out=103,945,320 elapsed=160.6s

  [10440/17668] intraday_2770.csv.gz  in=337,231,161 out=103,945,320 elapsed=160.6s

  [10441/17668] intraday_2771.csv.gz  in=337,245,580 out=103,945,320 elapsed=160.6s

  [10442/17668] intraday_2773.csv.gz  in=337,258,143 out=103,945,320 elapsed=160.6s

  [10443/17668] intraday_2774.csv.gz  in=337,270,289 out=103,945,320 elapsed=160.6s

  [10444/17668] intraday_2775.csv.gz  in=337,282,072 out=103,945,320 elapsed=160.6s

  [10445/17668] intraday_2776.csv.gz  in=337,294,783 out=103,945,320 elapsed=160.6s

  [10446/17668] intraday_2777.csv.gz  in=337,316,225 out=103,945,320 elapsed=160.6s

  [10447/17668] intraday_2778.csv.gz  in=337,327,170 out=103,945,320 elapsed=160.6s

  [10448/17668] intraday_2780.csv.gz  in=337,342,679 out=103,945,320 elapsed=160.7s

  [10449/17668] intraday_2779.csv.gz  in=337,355,622 out=103,945,320 elapsed=160.7s

  [10450/17668] intraday_2781.csv.gz  in=337,367,663 out=103,945,320 elapsed=160.7s

  [10451/17668] intraday_2782.csv.gz  in=337,380,571 out=103,945,320 elapsed=160.7s

  [10452/17668] intraday_2783.csv.gz  in=337,391,913 out=103,945,320 elapsed=160.7s

  [10453/17668] intraday_2784.csv.gz  in=337,403,513 out=103,945,320 elapsed=160.7s

  [10454/17668] intraday_2785.csv.gz  in=337,415,157 out=103,945,320 elapsed=160.7s

  [10455/17668] intraday_2786.csv.gz  in=337,428,437 out=103,945,320 elapsed=160.7s

  [10456/17668] intraday_2787.csv.gz  in=337,440,670 out=103,945,320 elapsed=160.7s

  [10457/17668] intraday_2789.csv.gz  in=337,451,189 out=103,945,320 elapsed=160.8s

  [10458/17668] intraday_2788.csv.gz  in=337,467,061 out=103,945,320 elapsed=160.8s

  [10459/17668] intraday_2790.csv.gz  in=337,479,498 out=103,945,320 elapsed=160.8s

  [10460/17668] intraday_2791.csv.gz  in=337,491,492 out=103,945,320 elapsed=160.8s

  [10461/17668] intraday_2792.csv.gz  in=337,504,421 out=103,945,320 elapsed=160.8s

  [10462/17668] intraday_2793.csv.gz  in=337,515,627 out=103,945,320 elapsed=160.8s

  [10463/17668] intraday_2794.csv.gz  in=337,530,762 out=103,945,320 elapsed=160.8s

  [10464/17668] intraday_2795.csv.gz  in=337,547,566 out=103,945,320 elapsed=160.8s

  [10465/17668] intraday_2796.csv.gz  in=337,560,672 out=103,945,320 elapsed=160.8s

  [10466/17668] intraday_2797.csv.gz  in=337,574,218 out=103,945,320 elapsed=160.8s

  [10467/17668] intraday_2799.csv.gz  in=337,584,297 out=103,945,320 elapsed=160.9s

  [10468/17668] intraday_2798.csv.gz  in=337,595,264 out=103,945,320 elapsed=160.9s

  [10469/17668] intraday_2800.csv.gz  in=337,607,113 out=103,945,320 elapsed=160.9s

  [10470/17668] intraday_2801.csv.gz  in=337,619,168 out=103,945,320 elapsed=160.9s

  [10471/17668] intraday_2802.csv.gz  in=337,627,109 out=103,945,320 elapsed=160.9s

  [10472/17668] intraday_2805.csv.gz  in=337,629,372 out=103,945,320 elapsed=160.9s

  [10473/17668] intraday_2803.csv.gz  in=337,637,680 out=103,945,320 elapsed=160.9s

  [10474/17668] intraday_2804.csv.gz  in=337,648,623 out=103,945,320 elapsed=160.9s

  [10475/17668] intraday_2806.csv.gz  in=337,664,192 out=103,945,320 elapsed=160.9s

  [10476/17668] intraday_2807.csv.gz  in=337,679,058 out=103,945,320 elapsed=160.9s

  [10477/17668] intraday_2808.csv.gz  in=337,692,192 out=103,945,320 elapsed=160.9s

  [10478/17668] intraday_2809.csv.gz  in=337,702,973 out=103,945,320 elapsed=161.0s

  [10479/17668] intraday_2810.csv.gz  in=337,717,792 out=103,945,320 elapsed=161.0s

  [10480/17668] intraday_2811.csv.gz  in=337,731,529 out=103,945,320 elapsed=161.0s

  [10481/17668] intraday_2812.csv.gz  in=337,744,113 out=103,945,320 elapsed=161.0s

  [10482/17668] intraday_2813.csv.gz  in=337,756,145 out=103,945,320 elapsed=161.0s

  [10483/17668] intraday_2814.csv.gz  in=337,770,166 out=103,945,320 elapsed=161.0s

  [10484/17668] intraday_2815.csv.gz  in=337,784,119 out=103,945,320 elapsed=161.0s

  [10485/17668] intraday_2817.csv.gz  in=337,797,257 out=103,945,320 elapsed=161.0s

  [10486/17668] intraday_2816.csv.gz  in=337,806,237 out=103,945,320 elapsed=161.0s

  [10487/17668] intraday_2818.csv.gz  in=337,818,524 out=103,945,320 elapsed=161.1s

  [10488/17668] intraday_2819.csv.gz  in=337,829,566 out=103,945,320 elapsed=161.1s

  [10489/17668] intraday_2820.csv.gz  in=337,840,588 out=103,945,320 elapsed=161.1s

  [10490/17668] intraday_2821.csv.gz  in=337,851,729 out=103,945,320 elapsed=161.1s

  [10491/17668] intraday_2822.csv.gz  in=337,864,610 out=103,945,320 elapsed=161.1s

  [10492/17668] intraday_2823.csv.gz  in=337,876,910 out=103,945,320 elapsed=161.1s

  [10493/17668] intraday_2825.csv.gz  in=337,889,755 out=103,945,320 elapsed=161.1s

  [10494/17668] intraday_2824.csv.gz  in=337,900,512 out=103,945,320 elapsed=161.1s

  [10495/17668] intraday_2829.csv.gz  in=337,913,414 out=103,945,320 elapsed=161.1s

  [10496/17668] intraday_2826.csv.gz  in=337,926,267 out=103,945,320 elapsed=161.1s

  [10497/17668] intraday_2828.csv.gz  in=337,938,794 out=103,945,320 elapsed=161.1s

  [10498/17668] intraday_2827.csv.gz  in=337,950,706 out=103,945,320 elapsed=161.1s

  [10499/17668] intraday_2832.csv.gz  in=337,962,615 out=103,945,320 elapsed=161.2s

  [10500/17668] intraday_2831.csv.gz  in=337,972,395 out=103,945,320 elapsed=161.2s

  [10501/17668] intraday_2833.csv.gz  in=337,984,622 out=103,945,320 elapsed=161.2s

  [10502/17668] intraday_2830.csv.gz  in=338,005,794 out=103,945,320 elapsed=161.2s

  [10503/17668] intraday_2836.csv.gz  in=338,019,248 out=103,945,320 elapsed=161.2s

  [10504/17668] intraday_2835.csv.gz  in=338,033,440 out=103,945,320 elapsed=161.2s

  [10505/17668] intraday_2834.csv.gz  in=338,052,432 out=103,945,320 elapsed=161.2s

  [10506/17668] intraday_2837.csv.gz  in=338,065,759 out=103,945,320 elapsed=161.3s

  [10507/17668] intraday_2838.csv.gz  in=338,078,604 out=103,945,320 elapsed=161.3s

  [10508/17668] intraday_2839.csv.gz  in=338,091,641 out=103,945,320 elapsed=161.3s

  [10509/17668] intraday_2841.csv.gz  in=338,104,332 out=103,945,320 elapsed=161.3s

  [10510/17668] intraday_2840.csv.gz  in=338,133,512 out=103,945,320 elapsed=161.3s

  [10511/17668] intraday_2842.csv.gz  in=338,143,832 out=103,945,320 elapsed=161.3s

  [10512/17668] intraday_2844.csv.gz  in=338,154,800 out=103,945,320 elapsed=161.3s

  [10513/17668] intraday_2843.csv.gz  in=338,165,321 out=103,945,320 elapsed=161.3s

  [10514/17668] intraday_2845.csv.gz  in=338,176,128 out=103,945,320 elapsed=161.3s

  [10515/17668] intraday_2846.csv.gz  in=338,190,334 out=103,945,320 elapsed=161.3s

  [10516/17668] intraday_2847.csv.gz  in=338,203,831 out=103,945,320 elapsed=161.3s

  [10517/17668] intraday_2848.csv.gz  in=338,215,806 out=103,945,320 elapsed=161.4s

  [10518/17668] intraday_2849.csv.gz  in=338,229,725 out=103,945,320 elapsed=161.4s

  [10519/17668] intraday_2851.csv.gz  in=338,246,329 out=103,945,320 elapsed=161.4s

  [10520/17668] intraday_2852.csv.gz  in=338,257,392 out=103,945,320 elapsed=161.4s

  [10521/17668] intraday_2853.csv.gz  in=338,268,775 out=103,945,320 elapsed=161.4s

  [10522/17668] intraday_2850.csv.gz  in=338,296,176 out=103,945,320 elapsed=161.4s

  [10523/17668] intraday_2855.csv.gz  in=338,306,798 out=103,945,320 elapsed=161.4s

  [10524/17668] intraday_2857.csv.gz  in=338,317,411 out=103,945,320 elapsed=161.4s

  [10525/17668] intraday_2854.csv.gz  in=338,329,671 out=103,945,320 elapsed=161.4s

  [10526/17668] intraday_2856.csv.gz  in=338,341,737 out=103,945,320 elapsed=161.4s

  [10527/17668] intraday_2859.csv.gz  in=338,352,921 out=103,945,320 elapsed=161.5s

  [10528/17668] intraday_2858.csv.gz  in=338,372,353 out=103,945,320 elapsed=161.5s

  [10529/17668] intraday_2861.csv.gz  in=338,384,266 out=103,945,320 elapsed=161.5s

  [10530/17668] intraday_2860.csv.gz  in=338,396,898 out=103,945,320 elapsed=161.5s

  [10531/17668] intraday_2862.csv.gz  in=338,406,742 out=103,945,320 elapsed=161.5s

  [10532/17668] intraday_2863.csv.gz  in=338,419,446 out=103,945,320 elapsed=161.5s

  [10533/17668] intraday_2864.csv.gz  in=338,432,069 out=103,945,320 elapsed=161.5s

  [10534/17668] intraday_2865.csv.gz  in=338,445,048 out=103,945,320 elapsed=161.5s

  [10535/17668] intraday_2866.csv.gz  in=338,457,511 out=103,945,320 elapsed=161.6s

  [10536/17668] intraday_2867.csv.gz  in=338,468,904 out=103,945,320 elapsed=161.6s

  [10537/17668] intraday_2868.csv.gz  in=338,478,476 out=103,945,320 elapsed=161.6s

  [10538/17668] intraday_2869.csv.gz  in=338,490,958 out=103,945,320 elapsed=161.6s

  [10539/17668] intraday_2871.csv.gz  in=338,501,200 out=103,945,320 elapsed=161.6s

  [10540/17668] intraday_2870.csv.gz  in=338,516,469 out=103,945,320 elapsed=161.6s

  [10541/17668] intraday_2872.csv.gz  in=338,530,440 out=103,945,320 elapsed=161.6s

  [10542/17668] intraday_2873.csv.gz  in=338,545,776 out=103,945,320 elapsed=161.6s

  [10543/17668] intraday_2874.csv.gz  in=338,555,677 out=103,945,320 elapsed=161.6s

  [10544/17668] intraday_2875.csv.gz  in=338,567,995 out=103,945,320 elapsed=161.6s

  [10545/17668] intraday_2876.csv.gz  in=338,581,177 out=103,945,320 elapsed=161.6s

  [10546/17668] intraday_2877.csv.gz  in=338,593,784 out=103,945,320 elapsed=161.6s

  [10547/17668] intraday_2879.csv.gz  in=338,605,014 out=103,945,320 elapsed=161.7s

  [10548/17668] intraday_2878.csv.gz  in=338,615,572 out=103,945,320 elapsed=161.7s

  [10549/17668] intraday_2880.csv.gz  in=338,632,294 out=103,945,320 elapsed=161.7s

  [10550/17668] intraday_2883.csv.gz  in=338,644,312 out=103,945,320 elapsed=161.7s

  [10551/17668] intraday_2881.csv.gz  in=338,656,489 out=103,945,320 elapsed=161.7s

  [10552/17668] intraday_2882.csv.gz  in=338,668,498 out=103,945,320 elapsed=161.7s

  [10553/17668] intraday_2884.csv.gz  in=338,681,457 out=103,945,320 elapsed=161.7s

  [10554/17668] intraday_2887.csv.gz  in=338,693,964 out=103,945,320 elapsed=161.7s

  [10555/17668] intraday_2886.csv.gz  in=338,704,638 out=103,945,320 elapsed=161.7s

  [10556/17668] intraday_2885.csv.gz  in=338,715,209 out=103,945,320 elapsed=161.7s

  [10557/17668] intraday_2888.csv.gz  in=338,731,955 out=103,945,320 elapsed=161.8s

  [10558/17668] intraday_2889.csv.gz  in=338,742,461 out=103,945,320 elapsed=161.8s

  [10559/17668] intraday_2890.csv.gz  in=338,753,098 out=103,945,320 elapsed=161.8s

  [10560/17668] intraday_2891.csv.gz  in=338,763,579 out=103,945,320 elapsed=161.8s

  [10561/17668] intraday_2893.csv.gz  in=338,774,914 out=103,945,320 elapsed=161.8s

  [10562/17668] intraday_2892.csv.gz  in=338,787,432 out=103,945,320 elapsed=161.8s

  [10563/17668] intraday_2895.csv.gz  in=338,798,688 out=103,945,320 elapsed=161.8s

  [10564/17668] intraday_2894.csv.gz  in=338,814,240 out=103,945,320 elapsed=161.8s

  [10565/17668] intraday_2896.csv.gz  in=338,827,450 out=103,945,320 elapsed=161.8s

  [10566/17668] intraday_2897.csv.gz  in=338,840,895 out=103,945,320 elapsed=161.8s

  [10567/17668] intraday_2899.csv.gz  in=338,852,997 out=103,945,320 elapsed=161.9s

  [10568/17668] intraday_2900.csv.gz  in=338,865,403 out=103,945,320 elapsed=161.9s

  [10569/17668] intraday_2898.csv.gz  in=338,892,596 out=103,945,320 elapsed=161.9s

  [10570/17668] intraday_2902.csv.gz  in=338,907,337 out=103,945,320 elapsed=161.9s

  [10571/17668] intraday_2903.csv.gz  in=338,920,043 out=103,945,320 elapsed=161.9s

  [10572/17668] intraday_2901.csv.gz  in=338,944,352 out=103,945,320 elapsed=161.9s

  [10573/17668] intraday_2904.csv.gz  in=338,958,365 out=103,945,320 elapsed=161.9s

  [10574/17668] intraday_2905.csv.gz  in=338,969,172 out=103,945,320 elapsed=161.9s

  [10575/17668] intraday_2906.csv.gz  in=338,981,636 out=103,945,320 elapsed=161.9s

  [10576/17668] intraday_2907.csv.gz  in=338,993,518 out=103,945,320 elapsed=161.9s

  [10577/17668] intraday_2909.csv.gz  in=339,006,776 out=103,945,320 elapsed=162.0s

  [10578/17668] intraday_2908.csv.gz  in=339,031,500 out=103,945,320 elapsed=162.0s

  [10579/17668] intraday_2910.csv.gz  in=339,042,163 out=103,945,320 elapsed=162.0s

  [10580/17668] intraday_2911.csv.gz  in=339,053,384 out=103,945,320 elapsed=162.0s

  [10581/17668] intraday_2912.csv.gz  in=339,067,544 out=103,945,320 elapsed=162.0s

  [10582/17668] intraday_2914.csv.gz  in=339,080,377 out=103,945,320 elapsed=162.0s

  [10583/17668] intraday_2915.csv.gz  in=339,093,048 out=103,945,320 elapsed=162.0s

  [10584/17668] intraday_2913.csv.gz  in=339,108,208 out=103,945,320 elapsed=162.0s

  [10585/17668] intraday_2916.csv.gz  in=339,122,196 out=103,945,320 elapsed=162.0s

  [10586/17668] intraday_2917.csv.gz  in=339,135,553 out=103,945,320 elapsed=162.0s

  [10587/17668] intraday_2919.csv.gz  in=339,147,791 out=103,945,320 elapsed=162.0s

  [10588/17668] intraday_2918.csv.gz  in=339,161,099 out=103,945,320 elapsed=162.1s

  [10589/17668] intraday_2920.csv.gz  in=339,175,535 out=103,945,320 elapsed=162.1s

  [10590/17668] intraday_2921.csv.gz  in=339,196,933 out=103,945,320 elapsed=162.1s

  [10591/17668] intraday_2922.csv.gz  in=339,209,718 out=103,945,320 elapsed=162.1s

  [10592/17668] intraday_2924.csv.gz  in=339,222,141 out=103,945,320 elapsed=162.1s

  [10593/17668] intraday_2925.csv.gz  in=339,234,637 out=103,945,320 elapsed=162.1s

  [10594/17668] intraday_2923.csv.gz  in=339,247,765 out=103,945,320 elapsed=162.1s

  [10595/17668] intraday_2926.csv.gz  in=339,259,101 out=103,945,320 elapsed=162.1s

  [10596/17668] intraday_2927.csv.gz  in=339,272,943 out=103,945,320 elapsed=162.1s

  [10597/17668] intraday_2930.csv.gz  in=339,285,321 out=103,945,320 elapsed=162.2s

  [10598/17668] intraday_2928.csv.gz  in=339,298,330 out=103,945,320 elapsed=162.2s

  [10599/17668] intraday_2929.csv.gz  in=339,314,979 out=103,945,320 elapsed=162.2s

  [10600/17668] intraday_2931.csv.gz  in=339,328,844 out=103,945,320 elapsed=162.2s

  [10601/17668] intraday_2932.csv.gz  in=339,342,530 out=103,945,320 elapsed=162.2s

  [10602/17668] intraday_2934.csv.gz  in=339,355,415 out=103,945,320 elapsed=162.2s

  [10603/17668] intraday_2933.csv.gz  in=339,367,860 out=103,945,320 elapsed=162.2s

  [10604/17668] intraday_2935.csv.gz  in=339,389,971 out=103,945,320 elapsed=162.2s

  [10605/17668] intraday_2936.csv.gz  in=339,405,099 out=103,945,320 elapsed=162.2s

  [10606/17668] intraday_2937.csv.gz  in=339,418,519 out=103,945,320 elapsed=162.2s

  [10607/17668] intraday_2938.csv.gz  in=339,433,046 out=103,945,320 elapsed=162.3s

  [10608/17668] intraday_2939.csv.gz  in=339,444,052 out=103,945,320 elapsed=162.3s

  [10609/17668] intraday_2942.csv.gz  in=339,455,980 out=103,945,320 elapsed=162.3s

  [10610/17668] intraday_2943.csv.gz  in=339,466,927 out=103,945,320 elapsed=162.3s

  [10611/17668] intraday_2940.csv.gz  in=339,478,153 out=103,945,320 elapsed=162.3s

  [10612/17668] intraday_2941.csv.gz  in=339,491,095 out=103,945,320 elapsed=162.3s

  [10613/17668] intraday_2945.csv.gz  in=339,500,592 out=103,945,320 elapsed=162.3s

  [10614/17668] intraday_2944.csv.gz  in=339,508,051 out=103,945,320 elapsed=162.3s

  [10615/17668] intraday_2946.csv.gz  in=339,514,202 out=103,945,320 elapsed=162.3s

  [10616/17668] intraday_2947.csv.gz  in=339,530,956 out=103,945,320 elapsed=162.3s

  [10617/17668] intraday_2950.csv.gz  in=339,541,997 out=103,945,320 elapsed=162.3s

  [10618/17668] intraday_2948.csv.gz  in=339,557,127 out=103,945,320 elapsed=162.4s

  [10619/17668] intraday_2949.csv.gz  in=339,571,066 out=103,945,320 elapsed=162.4s

  [10620/17668] intraday_2951.csv.gz  in=339,586,148 out=103,945,320 elapsed=162.4s

  [10621/17668] intraday_2952.csv.gz  in=339,601,032 out=103,945,320 elapsed=162.4s

  [10622/17668] intraday_2954.csv.gz  in=339,614,260 out=103,945,320 elapsed=162.4s

  [10623/17668] intraday_2953.csv.gz  in=339,627,398 out=103,945,320 elapsed=162.4s

  [10624/17668] intraday_2955.csv.gz  in=339,642,268 out=103,945,320 elapsed=162.4s

  [10625/17668] intraday_2956.csv.gz  in=339,656,838 out=103,945,320 elapsed=162.4s

  [10626/17668] intraday_2957.csv.gz  in=339,666,815 out=103,945,320 elapsed=162.4s

  [10627/17668] intraday_2959.csv.gz  in=339,680,504 out=103,945,320 elapsed=162.4s

  [10628/17668] intraday_2958.csv.gz  in=339,694,479 out=103,945,320 elapsed=162.4s

  [10629/17668] intraday_2961.csv.gz  in=339,705,922 out=103,945,320 elapsed=162.5s

  [10630/17668] intraday_2962.csv.gz  in=339,717,315 out=103,945,320 elapsed=162.5s

  [10631/17668] intraday_2960.csv.gz  in=339,729,786 out=103,945,320 elapsed=162.5s

  [10632/17668] intraday_2963.csv.gz  in=339,743,885 out=103,945,320 elapsed=162.5s

  [10633/17668] intraday_2964.csv.gz  in=339,756,843 out=103,945,320 elapsed=162.5s

  [10634/17668] intraday_2967.csv.gz  in=339,770,885 out=103,945,320 elapsed=162.5s

  [10635/17668] intraday_2965.csv.gz  in=339,782,080 out=103,945,320 elapsed=162.5s

  [10636/17668] intraday_2966.csv.gz  in=339,795,129 out=103,945,320 elapsed=162.5s

  [10637/17668] intraday_2968.csv.gz  in=339,807,372 out=103,945,320 elapsed=162.5s

  [10638/17668] intraday_2969.csv.gz  in=339,820,064 out=103,945,320 elapsed=162.5s

  [10639/17668] intraday_2970.csv.gz  in=339,838,301 out=103,945,320 elapsed=162.6s

  [10640/17668] intraday_2971.csv.gz  in=339,850,802 out=103,945,320 elapsed=162.6s

  [10641/17668] intraday_2972.csv.gz  in=339,861,360 out=103,945,320 elapsed=162.6s

  [10642/17668] intraday_2973.csv.gz  in=339,874,451 out=103,945,320 elapsed=162.6s

  [10643/17668] intraday_2976.csv.gz  in=339,890,327 out=103,945,320 elapsed=162.6s

  [10644/17668] intraday_2974.csv.gz  in=339,903,048 out=103,945,320 elapsed=162.6s

  [10645/17668] intraday_2975.csv.gz  in=339,916,637 out=103,945,320 elapsed=162.6s

  [10646/17668] intraday_2978.csv.gz  in=339,930,299 out=103,945,320 elapsed=162.6s

  [10647/17668] intraday_2977.csv.gz  in=339,944,383 out=103,945,320 elapsed=162.6s

  [10648/17668] intraday_2979.csv.gz  in=339,959,341 out=103,945,320 elapsed=162.6s

  [10649/17668] intraday_2980.csv.gz  in=339,990,299 out=103,945,320 elapsed=162.6s

  [10650/17668] intraday_2981.csv.gz  in=340,006,184 out=103,945,320 elapsed=162.7s

  [10651/17668] intraday_2983.csv.gz  in=340,016,766 out=103,945,320 elapsed=162.7s

  [10652/17668] intraday_2982.csv.gz  in=340,034,441 out=103,945,320 elapsed=162.7s

  [10653/17668] intraday_2984.csv.gz  in=340,047,291 out=103,945,320 elapsed=162.7s

  [10654/17668] intraday_2985.csv.gz  in=340,059,590 out=103,945,320 elapsed=162.7s

  [10655/17668] intraday_2986.csv.gz  in=340,072,060 out=103,945,320 elapsed=162.7s

  [10656/17668] intraday_2987.csv.gz  in=340,086,591 out=103,945,320 elapsed=162.7s

  [10657/17668] intraday_2988.csv.gz  in=340,100,684 out=103,945,320 elapsed=162.7s

  [10658/17668] intraday_2989.csv.gz  in=340,112,857 out=103,945,320 elapsed=162.7s

  [10659/17668] intraday_2992.csv.gz  in=340,126,185 out=103,945,320 elapsed=162.7s

  [10660/17668] intraday_2990.csv.gz  in=340,140,728 out=103,945,320 elapsed=162.8s

  [10661/17668] intraday_2993.csv.gz  in=340,152,956 out=103,945,320 elapsed=162.8s

  [10662/17668] intraday_2991.csv.gz  in=340,164,645 out=103,945,320 elapsed=162.8s

  [10663/17668] intraday_2996.csv.gz  in=340,176,252 out=103,945,320 elapsed=162.8s

  [10664/17668] intraday_2994.csv.gz  in=340,188,376 out=103,945,320 elapsed=162.8s

  [10665/17668] intraday_2997.csv.gz  in=340,201,382 out=103,945,320 elapsed=162.8s

  [10666/17668] intraday_2995.csv.gz  in=340,213,962 out=103,945,320 elapsed=162.8s

  [10667/17668] intraday_2998.csv.gz  in=340,226,242 out=103,945,320 elapsed=162.8s

  [10668/17668] intraday_3000.csv.gz  in=340,238,313 out=103,945,320 elapsed=162.8s

  [10669/17668] intraday_2999.csv.gz  in=340,250,895 out=103,945,320 elapsed=162.8s

  [10670/17668] intraday_3001.csv.gz  in=340,264,771 out=103,945,320 elapsed=162.8s

  [10671/17668] intraday_3003.csv.gz  in=340,275,750 out=103,945,320 elapsed=162.9s

  [10672/17668] intraday_3002.csv.gz  in=340,288,289 out=103,945,320 elapsed=162.9s

  [10673/17668] intraday_3004.csv.gz  in=340,302,313 out=103,945,320 elapsed=162.9s

  [10674/17668] intraday_3005.csv.gz  in=340,316,283 out=103,945,320 elapsed=162.9s

  [10675/17668] intraday_3006.csv.gz  in=340,329,056 out=103,945,320 elapsed=162.9s

  [10676/17668] intraday_3007.csv.gz  in=340,341,738 out=103,945,320 elapsed=162.9s

  [10677/17668] intraday_3008.csv.gz  in=340,354,073 out=103,945,320 elapsed=162.9s

  [10678/17668] intraday_3009.csv.gz  in=340,364,201 out=103,945,320 elapsed=162.9s

  [10679/17668] intraday_3012.csv.gz  in=340,375,198 out=103,945,320 elapsed=162.9s

  [10680/17668] intraday_3011.csv.gz  in=340,391,735 out=103,945,320 elapsed=162.9s

  [10681/17668] intraday_3010.csv.gz  in=340,404,782 out=103,945,320 elapsed=162.9s

  [10682/17668] intraday_3013.csv.gz  in=340,418,523 out=103,945,320 elapsed=163.0s

  [10683/17668] intraday_3015.csv.gz  in=340,427,891 out=103,945,320 elapsed=163.0s

  [10684/17668] intraday_3016.csv.gz  in=340,441,719 out=103,945,320 elapsed=163.0s

  [10685/17668] intraday_3017.csv.gz  in=340,455,104 out=103,945,320 elapsed=163.0s

  [10686/17668] intraday_3014.csv.gz  in=340,469,918 out=103,945,320 elapsed=163.0s

  [10687/17668] intraday_3018.csv.gz  in=340,484,117 out=103,945,320 elapsed=163.0s

  [10688/17668] intraday_3020.csv.gz  in=340,495,630 out=103,945,320 elapsed=163.0s

  [10689/17668] intraday_3021.csv.gz  in=340,507,715 out=103,945,320 elapsed=163.0s

  [10690/17668] intraday_3019.csv.gz  in=340,518,585 out=103,945,320 elapsed=163.0s

  [10691/17668] intraday_3022.csv.gz  in=340,531,577 out=103,945,320 elapsed=163.0s

  [10692/17668] intraday_3023.csv.gz  in=340,545,062 out=103,945,320 elapsed=163.0s

  [10693/17668] intraday_3025.csv.gz  in=340,559,011 out=103,945,320 elapsed=163.0s

  [10694/17668] intraday_3024.csv.gz  in=340,571,177 out=103,945,320 elapsed=163.0s

  [10695/17668] intraday_3026.csv.gz  in=340,581,986 out=103,945,320 elapsed=163.1s

  [10696/17668] intraday_3028.csv.gz  in=340,595,687 out=103,945,320 elapsed=163.1s

  [10697/17668] intraday_3027.csv.gz  in=340,606,655 out=103,945,320 elapsed=163.1s

  [10698/17668] intraday_3030.csv.gz  in=340,617,773 out=103,945,320 elapsed=163.1s

  [10699/17668] intraday_3029.csv.gz  in=340,635,150 out=103,945,320 elapsed=163.1s

  [10700/17668] intraday_3031.csv.gz  in=340,646,893 out=103,945,320 elapsed=163.1s

  [10701/17668] intraday_3032.csv.gz  in=340,657,451 out=103,945,320 elapsed=163.1s

  [10702/17668] intraday_3033.csv.gz  in=340,671,268 out=103,945,320 elapsed=163.1s

  [10703/17668] intraday_3034.csv.gz  in=340,683,578 out=103,945,320 elapsed=163.1s

  [10704/17668] intraday_3036.csv.gz  in=340,707,239 out=103,945,320 elapsed=163.2s

  [10705/17668] intraday_3035.csv.gz  in=340,737,356 out=103,945,320 elapsed=163.2s

  [10706/17668] intraday_3038.csv.gz  in=340,750,896 out=103,945,320 elapsed=163.2s

  [10707/17668] intraday_3037.csv.gz  in=340,767,308 out=103,945,320 elapsed=163.2s

  [10708/17668] intraday_3039.csv.gz  in=340,782,269 out=103,945,320 elapsed=163.2s

  [10709/17668] intraday_3040.csv.gz  in=340,795,546 out=103,945,320 elapsed=163.2s

  [10710/17668] intraday_3041.csv.gz  in=340,808,873 out=103,945,320 elapsed=163.2s

  [10711/17668] intraday_3043.csv.gz  in=340,821,598 out=103,945,320 elapsed=163.2s

  [10712/17668] intraday_3044.csv.gz  in=340,834,647 out=103,945,320 elapsed=163.2s

  [10713/17668] intraday_3042.csv.gz  in=340,849,460 out=103,945,320 elapsed=163.2s

  [10714/17668] intraday_3045.csv.gz  in=340,862,528 out=103,945,320 elapsed=163.3s

  [10715/17668] intraday_3047.csv.gz  in=340,875,002 out=103,945,320 elapsed=163.3s

  [10716/17668] intraday_3046.csv.gz  in=340,887,817 out=103,945,320 elapsed=163.3s

  [10717/17668] intraday_3048.csv.gz  in=340,900,867 out=103,945,320 elapsed=163.3s

  [10718/17668] intraday_3049.csv.gz  in=340,913,991 out=103,945,320 elapsed=163.3s

  [10719/17668] intraday_3050.csv.gz  in=340,927,569 out=103,945,320 elapsed=163.3s

  [10720/17668] intraday_3052.csv.gz  in=340,939,696 out=103,945,320 elapsed=163.3s

  [10721/17668] intraday_3051.csv.gz  in=340,952,163 out=103,945,320 elapsed=163.3s

  [10722/17668] intraday_3053.csv.gz  in=340,967,388 out=103,945,320 elapsed=163.3s

  [10723/17668] intraday_3056.csv.gz  in=340,980,605 out=103,945,320 elapsed=163.3s

  [10724/17668] intraday_3055.csv.gz  in=340,997,841 out=103,945,320 elapsed=163.3s

  [10725/17668] intraday_3054.csv.gz  in=341,013,196 out=103,945,320 elapsed=163.3s

  [10726/17668] intraday_3057.csv.gz  in=341,027,665 out=103,945,320 elapsed=163.4s

  [10727/17668] intraday_3059.csv.gz  in=341,041,515 out=103,945,320 elapsed=163.4s

  [10728/17668] intraday_3058.csv.gz  in=341,055,690 out=103,945,320 elapsed=163.4s

  [10729/17668] intraday_3060.csv.gz  in=341,069,235 out=103,945,320 elapsed=163.4s

  [10730/17668] intraday_3061.csv.gz  in=341,083,518 out=103,945,320 elapsed=163.4s

  [10731/17668] intraday_3063.csv.gz  in=341,096,388 out=103,945,320 elapsed=163.4s

  [10732/17668] intraday_3064.csv.gz  in=341,111,212 out=103,945,320 elapsed=163.4s

  [10733/17668] intraday_3062.csv.gz  in=341,128,114 out=103,945,320 elapsed=163.4s

  [10734/17668] intraday_3066.csv.gz  in=341,141,715 out=103,945,320 elapsed=163.5s

  [10735/17668] intraday_3065.csv.gz  in=341,155,348 out=103,945,320 elapsed=163.5s

  [10736/17668] intraday_3067.csv.gz  in=341,167,067 out=103,945,320 elapsed=163.5s

  [10737/17668] intraday_3068.csv.gz  in=341,180,201 out=103,945,320 elapsed=163.5s

  [10738/17668] intraday_3070.csv.gz  in=341,196,095 out=103,945,320 elapsed=163.5s

  [10739/17668] intraday_3069.csv.gz  in=341,212,525 out=103,945,320 elapsed=163.5s

  [10740/17668] intraday_3071.csv.gz  in=341,227,179 out=103,945,320 elapsed=163.5s

  [10741/17668] intraday_3072.csv.gz  in=341,240,811 out=103,945,320 elapsed=163.5s

  [10742/17668] intraday_3073.csv.gz  in=341,255,772 out=103,945,320 elapsed=163.5s

  [10743/17668] intraday_3075.csv.gz  in=341,269,206 out=103,945,320 elapsed=163.5s

  [10744/17668] intraday_3074.csv.gz  in=341,283,770 out=103,945,320 elapsed=163.5s

  [10745/17668] intraday_3077.csv.gz  in=341,299,308 out=103,945,320 elapsed=163.6s

  [10746/17668] intraday_3076.csv.gz  in=341,313,991 out=103,945,320 elapsed=163.6s

  [10747/17668] intraday_3079.csv.gz  in=341,330,864 out=103,945,320 elapsed=163.6s

  [10748/17668] intraday_3078.csv.gz  in=341,345,952 out=103,945,320 elapsed=163.6s

  [10749/17668] intraday_3080.csv.gz  in=341,358,903 out=103,945,320 elapsed=163.6s

  [10750/17668] intraday_3081.csv.gz  in=341,369,631 out=103,945,320 elapsed=163.6s

  [10751/17668] intraday_3083.csv.gz  in=341,381,843 out=103,945,320 elapsed=163.6s

  [10752/17668] intraday_3082.csv.gz  in=341,395,297 out=103,945,320 elapsed=163.6s

  [10753/17668] intraday_3087.csv.gz  in=341,402,259 out=103,945,320 elapsed=163.6s

  [10754/17668] intraday_3085.csv.gz  in=341,410,392 out=103,945,320 elapsed=163.6s

  [10755/17668] intraday_3084.csv.gz  in=341,422,884 out=103,945,320 elapsed=163.6s

  [10756/17668] intraday_3086.csv.gz  in=341,433,559 out=103,945,320 elapsed=163.6s

  [10757/17668] intraday_3088.csv.gz  in=341,447,886 out=103,945,320 elapsed=163.7s

  [10758/17668] intraday_3089.csv.gz  in=341,462,119 out=103,945,320 elapsed=163.7s

  [10759/17668] intraday_3090.csv.gz  in=341,474,431 out=103,945,320 elapsed=163.7s

  [10760/17668] intraday_3091.csv.gz  in=341,484,678 out=103,945,320 elapsed=163.7s

  [10761/17668] intraday_3092.csv.gz  in=341,501,375 out=103,945,320 elapsed=163.7s

  [10762/17668] intraday_3095.csv.gz  in=341,513,519 out=103,945,320 elapsed=163.7s

  [10763/17668] intraday_3093.csv.gz  in=341,527,801 out=103,945,320 elapsed=163.7s

  [10764/17668] intraday_3094.csv.gz  in=341,540,289 out=103,945,320 elapsed=163.7s

  [10765/17668] intraday_3096.csv.gz  in=341,553,671 out=103,945,320 elapsed=163.7s

  [10766/17668] intraday_3097.csv.gz  in=341,567,027 out=103,945,320 elapsed=163.7s

  [10767/17668] intraday_3099.csv.gz  in=341,579,050 out=103,945,320 elapsed=163.7s

  [10768/17668] intraday_3098.csv.gz  in=341,588,787 out=103,945,320 elapsed=163.7s

  [10769/17668] intraday_3101.csv.gz  in=341,600,962 out=103,945,320 elapsed=163.7s

  [10770/17668] intraday_3100.csv.gz  in=341,613,451 out=103,945,320 elapsed=163.8s

  [10771/17668] intraday_3102.csv.gz  in=341,624,552 out=103,945,320 elapsed=163.8s

  [10772/17668] intraday_3103.csv.gz  in=341,634,629 out=103,945,320 elapsed=163.8s

  [10773/17668] intraday_3104.csv.gz  in=341,647,923 out=103,945,320 elapsed=163.8s

  [10774/17668] intraday_3105.csv.gz  in=341,659,817 out=103,945,320 elapsed=163.8s

  [10775/17668] intraday_3106.csv.gz  in=341,670,309 out=103,945,320 elapsed=163.8s

  [10776/17668] intraday_3108.csv.gz  in=341,683,457 out=103,945,320 elapsed=163.8s

  [10777/17668] intraday_3107.csv.gz  in=341,695,154 out=103,945,320 elapsed=163.8s

  [10778/17668] intraday_3109.csv.gz  in=341,706,254 out=103,945,320 elapsed=163.8s

  [10779/17668] intraday_3110.csv.gz  in=341,719,075 out=103,945,320 elapsed=163.9s

  [10780/17668] intraday_3111.csv.gz  in=341,732,099 out=103,945,320 elapsed=163.9s

  [10781/17668] intraday_3112.csv.gz  in=341,744,659 out=103,945,320 elapsed=163.9s

  [10782/17668] intraday_3113.csv.gz  in=341,754,666 out=103,945,320 elapsed=163.9s

  [10783/17668] intraday_3114.csv.gz  in=341,766,588 out=103,945,320 elapsed=163.9s

  [10784/17668] intraday_3115.csv.gz  in=341,779,130 out=103,945,320 elapsed=163.9s

  [10785/17668] intraday_3116.csv.gz  in=341,791,108 out=103,945,320 elapsed=163.9s

  [10786/17668] intraday_3117.csv.gz  in=341,805,363 out=103,945,320 elapsed=163.9s

  [10787/17668] intraday_3118.csv.gz  in=341,818,698 out=103,945,320 elapsed=163.9s

  [10788/17668] intraday_3119.csv.gz  in=341,831,517 out=103,945,320 elapsed=163.9s

  [10789/17668] intraday_3120.csv.gz  in=341,843,375 out=103,945,320 elapsed=163.9s

  [10790/17668] intraday_3121.csv.gz  in=341,856,353 out=103,945,320 elapsed=163.9s

  [10791/17668] intraday_3122.csv.gz  in=341,868,523 out=103,945,320 elapsed=164.0s

  [10792/17668] intraday_3123.csv.gz  in=341,881,429 out=103,945,320 elapsed=164.0s

  [10793/17668] intraday_3125.csv.gz  in=341,892,242 out=103,945,320 elapsed=164.0s

  [10794/17668] intraday_3124.csv.gz  in=341,902,735 out=103,945,320 elapsed=164.0s

  [10795/17668] intraday_3126.csv.gz  in=341,913,189 out=103,945,320 elapsed=164.0s

  [10796/17668] intraday_3128.csv.gz  in=341,926,570 out=103,945,320 elapsed=164.0s

  [10797/17668] intraday_3127.csv.gz  in=341,943,883 out=103,945,320 elapsed=164.0s

  [10798/17668] intraday_3129.csv.gz  in=341,957,224 out=103,945,320 elapsed=164.0s

  [10799/17668] intraday_3130.csv.gz  in=341,968,712 out=103,945,320 elapsed=164.0s

  [10800/17668] intraday_3131.csv.gz  in=341,981,618 out=103,945,320 elapsed=164.0s

  [10801/17668] intraday_3132.csv.gz  in=341,992,532 out=103,945,320 elapsed=164.0s

  [10802/17668] intraday_3134.csv.gz  in=342,004,395 out=103,945,320 elapsed=164.1s

  [10803/17668] intraday_3133.csv.gz  in=342,016,711 out=103,945,320 elapsed=164.1s

  [10804/17668] intraday_3135.csv.gz  in=342,027,520 out=103,945,320 elapsed=164.1s

  [10805/17668] intraday_3136.csv.gz  in=342,039,657 out=103,945,320 elapsed=164.1s

  [10806/17668] intraday_3137.csv.gz  in=342,050,428 out=103,945,320 elapsed=164.1s

  [10807/17668] intraday_3138.csv.gz  in=342,062,607 out=103,945,320 elapsed=164.1s

  [10808/17668] intraday_3139.csv.gz  in=342,073,148 out=103,945,320 elapsed=164.1s

  [10809/17668] intraday_3140.csv.gz  in=342,087,154 out=103,945,320 elapsed=164.1s

  [10810/17668] intraday_3141.csv.gz  in=342,097,142 out=103,945,320 elapsed=164.1s

  [10811/17668] intraday_3142.csv.gz  in=342,110,186 out=103,945,320 elapsed=164.1s

  [10812/17668] intraday_3143.csv.gz  in=342,122,991 out=103,945,320 elapsed=164.2s

  [10813/17668] intraday_3144.csv.gz  in=342,133,923 out=103,945,320 elapsed=164.2s

  [10814/17668] intraday_3145.csv.gz  in=342,145,909 out=103,945,320 elapsed=164.2s

  [10815/17668] intraday_3146.csv.gz  in=342,157,956 out=103,945,320 elapsed=164.2s

  [10816/17668] intraday_3147.csv.gz  in=342,169,526 out=103,945,320 elapsed=164.2s

  [10817/17668] intraday_3148.csv.gz  in=342,181,116 out=103,945,320 elapsed=164.2s

  [10818/17668] intraday_3150.csv.gz  in=342,190,724 out=103,945,320 elapsed=164.2s

  [10819/17668] intraday_3149.csv.gz  in=342,202,951 out=103,945,320 elapsed=164.2s

  [10820/17668] intraday_3151.csv.gz  in=342,214,996 out=103,945,320 elapsed=164.2s

  [10821/17668] intraday_3153.csv.gz  in=342,226,087 out=103,945,320 elapsed=164.3s

  [10822/17668] intraday_3154.csv.gz  in=342,239,766 out=103,945,320 elapsed=164.3s

  [10823/17668] intraday_3152.csv.gz  in=342,253,496 out=103,945,320 elapsed=164.3s

  [10824/17668] intraday_3155.csv.gz  in=342,266,611 out=103,945,320 elapsed=164.3s

  [10825/17668] intraday_3157.csv.gz  in=342,279,492 out=103,945,320 elapsed=164.3s

  [10826/17668] intraday_3156.csv.gz  in=342,287,928 out=103,945,320 elapsed=164.3s

  [10827/17668] intraday_3158.csv.gz  in=342,299,919 out=103,945,320 elapsed=164.3s

  [10828/17668] intraday_3159.csv.gz  in=342,311,793 out=103,945,320 elapsed=164.3s

  [10829/17668] intraday_3161.csv.gz  in=342,322,419 out=103,945,320 elapsed=164.3s

  [10830/17668] intraday_3162.csv.gz  in=342,332,932 out=103,945,320 elapsed=164.3s

  [10831/17668] intraday_3160.csv.gz  in=342,343,829 out=103,945,320 elapsed=164.3s

  [10832/17668] intraday_3163.csv.gz  in=342,354,405 out=103,945,320 elapsed=164.4s

  [10833/17668] intraday_3165.csv.gz  in=342,365,869 out=103,945,320 elapsed=164.4s

  [10834/17668] intraday_3164.csv.gz  in=342,378,450 out=103,945,320 elapsed=164.4s

  [10835/17668] intraday_3167.csv.gz  in=342,389,404 out=103,945,320 elapsed=164.4s

  [10836/17668] intraday_3166.csv.gz  in=342,401,719 out=103,945,320 elapsed=164.4s

  [10837/17668] intraday_3168.csv.gz  in=342,412,019 out=103,945,320 elapsed=164.4s

  [10838/17668] intraday_3169.csv.gz  in=342,425,516 out=103,945,320 elapsed=164.4s

  [10839/17668] intraday_3171.csv.gz  in=342,434,819 out=103,945,320 elapsed=164.4s

  [10840/17668] intraday_3170.csv.gz  in=342,450,447 out=103,945,320 elapsed=164.4s

  [10841/17668] intraday_3173.csv.gz  in=342,460,169 out=103,945,320 elapsed=164.4s

  [10842/17668] intraday_3175.csv.gz  in=342,471,077 out=103,945,320 elapsed=164.5s

  [10843/17668] intraday_3172.csv.gz  in=342,483,490 out=103,945,320 elapsed=164.5s

  [10844/17668] intraday_3174.csv.gz  in=342,499,187 out=103,945,320 elapsed=164.5s

  [10845/17668] intraday_3177.csv.gz  in=342,510,539 out=103,945,320 elapsed=164.5s

  [10846/17668] intraday_3176.csv.gz  in=342,524,852 out=103,945,320 elapsed=164.5s

  [10847/17668] intraday_3179.csv.gz  in=342,536,719 out=103,945,320 elapsed=164.5s

  [10848/17668] intraday_3178.csv.gz  in=342,552,044 out=103,945,320 elapsed=164.5s

  [10849/17668] intraday_3181.csv.gz  in=342,564,430 out=103,945,320 elapsed=164.5s

  [10850/17668] intraday_3180.csv.gz  in=342,578,069 out=103,945,320 elapsed=164.5s

  [10851/17668] intraday_3183.csv.gz  in=342,590,217 out=103,945,320 elapsed=164.6s

  [10852/17668] intraday_3182.csv.gz  in=342,601,528 out=103,945,320 elapsed=164.6s

  [10853/17668] intraday_3185.csv.gz  in=342,612,892 out=103,945,320 elapsed=164.6s

  [10854/17668] intraday_3184.csv.gz  in=342,626,555 out=103,945,320 elapsed=164.6s

  [10855/17668] intraday_3186.csv.gz  in=342,638,385 out=103,945,320 elapsed=164.6s

  [10856/17668] intraday_3188.csv.gz  in=342,650,282 out=103,945,320 elapsed=164.6s

  [10857/17668] intraday_3187.csv.gz  in=342,662,080 out=103,945,320 elapsed=164.6s

  [10858/17668] intraday_3189.csv.gz  in=342,673,018 out=103,945,320 elapsed=164.6s

  [10859/17668] intraday_3190.csv.gz  in=342,685,738 out=103,945,320 elapsed=164.6s

  [10860/17668] intraday_3191.csv.gz  in=342,698,166 out=103,945,320 elapsed=164.6s

  [10861/17668] intraday_3192.csv.gz  in=342,718,698 out=103,945,320 elapsed=164.7s

  [10862/17668] intraday_3193.csv.gz  in=342,730,095 out=103,945,320 elapsed=164.7s

  [10863/17668] intraday_3195.csv.gz  in=342,744,019 out=103,945,320 elapsed=164.7s

  [10864/17668] intraday_3194.csv.gz  in=342,757,480 out=103,945,320 elapsed=164.7s

  [10865/17668] intraday_3196.csv.gz  in=342,769,161 out=103,945,320 elapsed=164.7s

  [10866/17668] intraday_3197.csv.gz  in=342,781,773 out=103,945,320 elapsed=164.7s

  [10867/17668] intraday_3198.csv.gz  in=342,794,741 out=103,945,320 elapsed=164.7s

  [10868/17668] intraday_3199.csv.gz  in=342,806,450 out=103,945,320 elapsed=164.7s

  [10869/17668] intraday_3200.csv.gz  in=342,819,385 out=103,945,320 elapsed=164.7s

  [10870/17668] intraday_3202.csv.gz  in=342,832,805 out=103,945,320 elapsed=164.7s

  [10871/17668] intraday_3201.csv.gz  in=342,845,496 out=103,945,320 elapsed=164.7s

  [10872/17668] intraday_3203.csv.gz  in=342,860,365 out=103,945,320 elapsed=164.7s

  [10873/17668] intraday_3204.csv.gz  in=342,873,899 out=103,945,320 elapsed=164.7s

  [10874/17668] intraday_3206.csv.gz  in=342,886,593 out=103,945,320 elapsed=164.8s

  [10875/17668] intraday_3205.csv.gz  in=342,898,258 out=103,945,320 elapsed=164.8s

  [10876/17668] intraday_3207.csv.gz  in=342,909,910 out=103,945,320 elapsed=164.8s

  [10877/17668] intraday_3208.csv.gz  in=342,921,326 out=103,945,320 elapsed=164.8s

  [10878/17668] intraday_3209.csv.gz  in=342,933,003 out=103,945,320 elapsed=164.8s

  [10879/17668] intraday_3210.csv.gz  in=342,956,997 out=103,945,320 elapsed=164.8s

  [10880/17668] intraday_3211.csv.gz  in=342,970,338 out=103,945,320 elapsed=164.8s

  [10881/17668] intraday_3212.csv.gz  in=342,985,089 out=103,945,320 elapsed=164.8s

  [10882/17668] intraday_3213.csv.gz  in=342,996,247 out=103,945,320 elapsed=164.8s

  [10883/17668] intraday_3214.csv.gz  in=343,009,211 out=103,945,320 elapsed=164.9s

  [10884/17668] intraday_3216.csv.gz  in=343,021,626 out=103,945,320 elapsed=164.9s

  [10885/17668] intraday_3215.csv.gz  in=343,034,348 out=103,945,320 elapsed=164.9s

  [10886/17668] intraday_3217.csv.gz  in=343,047,383 out=103,945,320 elapsed=164.9s

  [10887/17668] intraday_3218.csv.gz  in=343,062,710 out=103,945,320 elapsed=164.9s

  [10888/17668] intraday_3219.csv.gz  in=343,076,210 out=103,945,320 elapsed=164.9s

  [10889/17668] intraday_3220.csv.gz  in=343,089,453 out=103,945,320 elapsed=164.9s

  [10890/17668] intraday_3221.csv.gz  in=343,102,135 out=103,945,320 elapsed=164.9s

  [10891/17668] intraday_3222.csv.gz  in=343,113,401 out=103,945,320 elapsed=164.9s

  [10892/17668] intraday_3224.csv.gz  in=343,123,207 out=103,945,320 elapsed=164.9s

  [10893/17668] intraday_3223.csv.gz  in=343,135,665 out=103,945,320 elapsed=165.0s

  [10894/17668] intraday_3225.csv.gz  in=343,149,407 out=103,945,320 elapsed=165.0s

  [10895/17668] intraday_3226.csv.gz  in=343,155,998 out=103,945,320 elapsed=165.0s

  [10896/17668] intraday_3227.csv.gz  in=343,166,339 out=103,945,320 elapsed=165.0s

  [10897/17668] intraday_3228.csv.gz  in=343,174,758 out=103,945,320 elapsed=165.0s

  [10898/17668] intraday_3229.csv.gz  in=343,189,112 out=103,945,320 elapsed=165.0s

  [10899/17668] intraday_3230.csv.gz  in=343,202,597 out=103,945,320 elapsed=165.0s

  [10900/17668] intraday_3232.csv.gz  in=343,212,494 out=103,945,320 elapsed=165.0s

  [10901/17668] intraday_3231.csv.gz  in=343,224,159 out=103,945,320 elapsed=165.0s

  [10902/17668] intraday_3233.csv.gz  in=343,238,186 out=103,945,320 elapsed=165.0s

  [10903/17668] intraday_3234.csv.gz  in=343,252,162 out=103,945,320 elapsed=165.0s

  [10904/17668] intraday_3235.csv.gz  in=343,264,593 out=103,945,320 elapsed=165.1s

  [10905/17668] intraday_3236.csv.gz  in=343,276,386 out=103,945,320 elapsed=165.1s

  [10906/17668] intraday_3238.csv.gz  in=343,289,027 out=103,945,320 elapsed=165.1s

  [10907/17668] intraday_3237.csv.gz  in=343,301,976 out=103,945,320 elapsed=165.1s

  [10908/17668] intraday_3239.csv.gz  in=343,311,436 out=103,945,320 elapsed=165.1s

  [10909/17668] intraday_3240.csv.gz  in=343,323,604 out=103,945,320 elapsed=165.1s

  [10910/17668] intraday_3241.csv.gz  in=343,335,530 out=103,945,320 elapsed=165.1s

  [10911/17668] intraday_3243.csv.gz  in=343,346,789 out=103,945,320 elapsed=165.1s

  [10912/17668] intraday_3242.csv.gz  in=343,358,393 out=103,945,320 elapsed=165.1s

  [10913/17668] intraday_3244.csv.gz  in=343,374,416 out=103,945,320 elapsed=165.1s

  [10914/17668] intraday_3247.csv.gz  in=343,384,577 out=103,945,320 elapsed=165.1s

  [10915/17668] intraday_3248.csv.gz  in=343,395,958 out=103,945,320 elapsed=165.2s

  [10916/17668] intraday_3245.csv.gz  in=343,408,806 out=103,945,320 elapsed=165.2s

  [10917/17668] intraday_3246.csv.gz  in=343,420,046 out=103,945,320 elapsed=165.2s

  [10918/17668] intraday_3252.csv.gz  in=343,432,407 out=103,945,320 elapsed=165.2s

  [10919/17668] intraday_3250.csv.gz  in=343,443,590 out=103,945,320 elapsed=165.2s

  [10920/17668] intraday_3249.csv.gz  in=343,456,439 out=103,945,320 elapsed=165.2s

  [10921/17668] intraday_3251.csv.gz  in=343,468,152 out=103,945,320 elapsed=165.2s

  [10922/17668] intraday_3254.csv.gz  in=343,482,207 out=103,945,320 elapsed=165.2s

  [10923/17668] intraday_3253.csv.gz  in=343,494,265 out=103,945,320 elapsed=165.2s

  [10924/17668] intraday_3255.csv.gz  in=343,506,235 out=103,945,320 elapsed=165.2s

  [10925/17668] intraday_3256.csv.gz  in=343,519,138 out=103,945,320 elapsed=165.2s

  [10926/17668] intraday_3258.csv.gz  in=343,534,050 out=103,945,320 elapsed=165.3s

  [10927/17668] intraday_3259.csv.gz  in=343,547,803 out=103,945,320 elapsed=165.3s

  [10928/17668] intraday_3257.csv.gz  in=343,559,143 out=103,945,320 elapsed=165.3s

  [10929/17668] intraday_3260.csv.gz  in=343,572,242 out=103,945,320 elapsed=165.3s

  [10930/17668] intraday_3261.csv.gz  in=343,582,900 out=103,945,320 elapsed=165.3s

  [10931/17668] intraday_3262.csv.gz  in=343,594,843 out=103,945,320 elapsed=165.3s

  [10932/17668] intraday_3264.csv.gz  in=343,607,392 out=103,945,320 elapsed=165.3s

  [10933/17668] intraday_3263.csv.gz  in=343,619,564 out=103,945,320 elapsed=165.3s

  [10934/17668] intraday_3265.csv.gz  in=343,633,955 out=103,945,320 elapsed=165.4s

  [10935/17668] intraday_3266.csv.gz  in=343,644,759 out=103,945,320 elapsed=165.4s

  [10936/17668] intraday_3267.csv.gz  in=343,660,358 out=103,945,320 elapsed=165.4s

  [10937/17668] intraday_3268.csv.gz  in=343,671,004 out=103,945,320 elapsed=165.4s

  [10938/17668] intraday_3269.csv.gz  in=343,684,541 out=103,945,320 elapsed=165.4s

  [10939/17668] intraday_3270.csv.gz  in=343,697,003 out=103,945,320 elapsed=165.4s

  [10940/17668] intraday_3271.csv.gz  in=343,707,520 out=103,945,320 elapsed=165.4s

  [10941/17668] intraday_3272.csv.gz  in=343,720,135 out=103,945,320 elapsed=165.4s

  [10942/17668] intraday_3274.csv.gz  in=343,731,353 out=103,945,320 elapsed=165.4s

  [10943/17668] intraday_3273.csv.gz  in=343,741,492 out=103,945,320 elapsed=165.4s

  [10944/17668] intraday_3275.csv.gz  in=343,753,273 out=103,945,320 elapsed=165.4s

  [10945/17668] intraday_3276.csv.gz  in=343,763,748 out=103,945,320 elapsed=165.4s

  [10946/17668] intraday_3278.csv.gz  in=343,774,654 out=103,945,320 elapsed=165.5s

  [10947/17668] intraday_3277.csv.gz  in=343,792,058 out=103,945,320 elapsed=165.5s

  [10948/17668] intraday_3279.csv.gz  in=343,803,022 out=103,945,320 elapsed=165.5s

  [10949/17668] intraday_3280.csv.gz  in=343,813,800 out=103,945,320 elapsed=165.5s

  [10950/17668] intraday_3281.csv.gz  in=343,826,466 out=103,945,320 elapsed=165.5s

  [10951/17668] intraday_3284.csv.gz  in=343,837,000 out=103,945,320 elapsed=165.5s

  [10952/17668] intraday_3283.csv.gz  in=343,851,475 out=103,945,320 elapsed=165.5s

  [10953/17668] intraday_3282.csv.gz  in=343,860,948 out=103,945,320 elapsed=165.5s

  [10954/17668] intraday_3285.csv.gz  in=343,870,795 out=103,945,320 elapsed=165.5s

  [10955/17668] intraday_3286.csv.gz  in=343,882,209 out=103,945,320 elapsed=165.5s

  [10956/17668] intraday_3288.csv.gz  in=343,892,995 out=103,945,320 elapsed=165.5s

  [10957/17668] intraday_3287.csv.gz  in=343,904,808 out=103,945,320 elapsed=165.5s

  [10958/17668] intraday_3289.csv.gz  in=343,927,873 out=103,945,320 elapsed=165.6s

  [10959/17668] intraday_3290.csv.gz  in=343,939,068 out=103,945,320 elapsed=165.6s

  [10960/17668] intraday_3291.csv.gz  in=343,948,627 out=103,945,320 elapsed=165.6s

  [10961/17668] intraday_3292.csv.gz  in=343,960,667 out=103,945,320 elapsed=165.6s

  [10962/17668] intraday_3293.csv.gz  in=343,973,847 out=103,945,320 elapsed=165.6s

  [10963/17668] intraday_3295.csv.gz  in=343,986,556 out=103,945,320 elapsed=165.6s

  [10964/17668] intraday_3294.csv.gz  in=344,004,058 out=103,945,320 elapsed=165.6s

  [10965/17668] intraday_3296.csv.gz  in=344,017,068 out=103,945,320 elapsed=165.6s

  [10966/17668] intraday_3297.csv.gz  in=344,026,509 out=103,945,320 elapsed=165.6s

  [10967/17668] intraday_3298.csv.gz  in=344,038,025 out=103,945,320 elapsed=165.6s

  [10968/17668] intraday_3300.csv.gz  in=344,049,577 out=103,945,320 elapsed=165.7s

  [10969/17668] intraday_3299.csv.gz  in=344,060,336 out=103,945,320 elapsed=165.7s

  [10970/17668] intraday_3304.csv.gz  in=344,071,441 out=103,945,320 elapsed=165.7s

  [10971/17668] intraday_3301.csv.gz  in=344,082,848 out=103,945,320 elapsed=165.7s

  [10972/17668] intraday_3302.csv.gz  in=344,094,192 out=103,945,320 elapsed=165.7s

  [10973/17668] intraday_3303.csv.gz  in=344,104,038 out=103,945,320 elapsed=165.7s

  [10974/17668] intraday_3305.csv.gz  in=344,116,720 out=103,945,320 elapsed=165.7s

  [10975/17668] intraday_3307.csv.gz  in=344,128,643 out=103,945,320 elapsed=165.7s

  [10976/17668] intraday_3308.csv.gz  in=344,138,028 out=103,945,320 elapsed=165.7s

  [10977/17668] intraday_3306.csv.gz  in=344,149,126 out=103,945,320 elapsed=165.7s

  [10978/17668] intraday_3309.csv.gz  in=344,159,705 out=103,945,320 elapsed=165.7s

  [10979/17668] intraday_3312.csv.gz  in=344,169,834 out=103,945,320 elapsed=165.7s

  [10980/17668] intraday_3311.csv.gz  in=344,183,941 out=103,945,320 elapsed=165.7s

  [10981/17668] intraday_3310.csv.gz  in=344,196,619 out=103,945,320 elapsed=165.8s

  [10982/17668] intraday_3313.csv.gz  in=344,207,874 out=103,945,320 elapsed=165.8s

  [10983/17668] intraday_3314.csv.gz  in=344,217,210 out=103,945,320 elapsed=165.8s

  [10984/17668] intraday_3315.csv.gz  in=344,230,485 out=103,945,320 elapsed=165.8s

  [10985/17668] intraday_3316.csv.gz  in=344,241,956 out=103,945,320 elapsed=165.8s

  [10986/17668] intraday_3318.csv.gz  in=344,253,014 out=103,945,320 elapsed=165.8s

  [10987/17668] intraday_3320.csv.gz  in=344,265,980 out=103,945,320 elapsed=165.8s

  [10988/17668] intraday_3319.csv.gz  in=344,280,450 out=103,945,320 elapsed=165.8s

  [10989/17668] intraday_3317.csv.gz  in=344,295,119 out=103,945,320 elapsed=165.8s

  [10990/17668] intraday_3321.csv.gz  in=344,307,820 out=103,945,320 elapsed=165.9s

  [10991/17668] intraday_3322.csv.gz  in=344,320,530 out=103,945,320 elapsed=165.9s

  [10992/17668] intraday_3323.csv.gz  in=344,330,857 out=103,945,320 elapsed=165.9s

  [10993/17668] intraday_3324.csv.gz  in=344,342,365 out=103,945,320 elapsed=165.9s

  [10994/17668] intraday_3325.csv.gz  in=344,356,740 out=103,945,320 elapsed=165.9s

  [10995/17668] intraday_3326.csv.gz  in=344,367,516 out=103,945,320 elapsed=165.9s

  [10996/17668] intraday_3327.csv.gz  in=344,378,173 out=103,945,320 elapsed=165.9s

  [10997/17668] intraday_3328.csv.gz  in=344,389,752 out=103,945,320 elapsed=165.9s

  [10998/17668] intraday_3329.csv.gz  in=344,402,132 out=103,945,320 elapsed=165.9s

  [10999/17668] intraday_3330.csv.gz  in=344,413,944 out=103,945,320 elapsed=165.9s

  [11000/17668] intraday_3331.csv.gz  in=344,425,774 out=103,945,320 elapsed=165.9s

  [11001/17668] intraday_3332.csv.gz  in=344,437,419 out=103,945,320 elapsed=166.0s

  [11002/17668] intraday_3333.csv.gz  in=344,448,951 out=103,945,320 elapsed=166.0s

  [11003/17668] intraday_3334.csv.gz  in=344,459,607 out=103,945,320 elapsed=166.0s

  [11004/17668] intraday_3335.csv.gz  in=344,473,386 out=103,945,320 elapsed=166.0s

  [11005/17668] intraday_3337.csv.gz  in=344,484,819 out=103,945,320 elapsed=166.0s

  [11006/17668] intraday_3336.csv.gz  in=344,498,236 out=103,945,320 elapsed=166.0s

  [11007/17668] intraday_3338.csv.gz  in=344,510,301 out=103,945,320 elapsed=166.0s

  [11008/17668] intraday_3340.csv.gz  in=344,521,549 out=103,945,320 elapsed=166.0s

  [11009/17668] intraday_3339.csv.gz  in=344,537,925 out=103,945,320 elapsed=166.0s

  [11010/17668] intraday_3341.csv.gz  in=344,550,350 out=103,945,320 elapsed=166.1s

  [11011/17668] intraday_3342.csv.gz  in=344,563,638 out=103,945,320 elapsed=166.1s

  [11012/17668] intraday_3343.csv.gz  in=344,576,024 out=103,945,320 elapsed=166.1s

  [11013/17668] intraday_3344.csv.gz  in=344,590,889 out=103,945,320 elapsed=166.1s

  [11014/17668] intraday_3346.csv.gz  in=344,602,876 out=103,945,320 elapsed=166.1s

  [11015/17668] intraday_3345.csv.gz  in=344,616,775 out=103,945,320 elapsed=166.1s

  [11016/17668] intraday_3347.csv.gz  in=344,629,409 out=103,945,320 elapsed=166.1s

  [11017/17668] intraday_3348.csv.gz  in=344,642,271 out=103,945,320 elapsed=166.1s

  [11018/17668] intraday_3350.csv.gz  in=344,652,285 out=103,945,320 elapsed=166.1s

  [11019/17668] intraday_3349.csv.gz  in=344,670,993 out=103,945,320 elapsed=166.1s

  [11020/17668] intraday_3352.csv.gz  in=344,683,506 out=103,945,320 elapsed=166.1s

  [11021/17668] intraday_3351.csv.gz  in=344,696,853 out=103,945,320 elapsed=166.1s

  [11022/17668] intraday_3354.csv.gz  in=344,708,307 out=103,945,320 elapsed=166.1s

  [11023/17668] intraday_3353.csv.gz  in=344,724,210 out=103,945,320 elapsed=166.1s

  [11024/17668] intraday_3355.csv.gz  in=344,735,717 out=103,945,320 elapsed=166.2s

  [11025/17668] intraday_3356.csv.gz  in=344,748,546 out=103,945,320 elapsed=166.2s

  [11026/17668] intraday_3357.csv.gz  in=344,761,083 out=103,945,320 elapsed=166.2s

  [11027/17668] intraday_3361.csv.gz  in=344,773,699 out=103,945,320 elapsed=166.2s

  [11028/17668] intraday_3358.csv.gz  in=344,786,001 out=103,945,320 elapsed=166.2s

  [11029/17668] intraday_3360.csv.gz  in=344,798,794 out=103,945,320 elapsed=166.2s

  [11030/17668] intraday_3359.csv.gz  in=344,813,558 out=103,945,320 elapsed=166.2s

  [11031/17668] intraday_3362.csv.gz  in=344,826,514 out=103,945,320 elapsed=166.2s

  [11032/17668] intraday_3365.csv.gz  in=344,836,146 out=103,945,320 elapsed=166.2s

  [11033/17668] intraday_3363.csv.gz  in=344,846,948 out=103,945,320 elapsed=166.2s

  [11034/17668] intraday_3364.csv.gz  in=344,863,162 out=103,945,320 elapsed=166.2s

  [11035/17668] intraday_3367.csv.gz  in=344,869,839 out=103,945,320 elapsed=166.3s

  [11036/17668] intraday_3366.csv.gz  in=344,883,045 out=103,945,320 elapsed=166.3s

  [11037/17668] intraday_3369.csv.gz  in=344,893,413 out=103,945,320 elapsed=166.3s

  [11038/17668] intraday_3368.csv.gz  in=344,902,986 out=103,945,320 elapsed=166.3s

  [11039/17668] intraday_3371.csv.gz  in=344,916,765 out=103,945,320 elapsed=166.3s

  [11040/17668] intraday_3372.csv.gz  in=344,928,332 out=103,945,320 elapsed=166.3s

  [11041/17668] intraday_3373.csv.gz  in=344,938,676 out=103,945,320 elapsed=166.3s

  [11042/17668] intraday_3370.csv.gz  in=344,953,544 out=103,945,320 elapsed=166.3s

  [11043/17668] intraday_3374.csv.gz  in=344,968,125 out=103,945,320 elapsed=166.3s

  [11044/17668] intraday_3375.csv.gz  in=344,982,711 out=103,945,320 elapsed=166.4s

  [11045/17668] intraday_3376.csv.gz  in=344,995,478 out=103,945,320 elapsed=166.4s

  [11046/17668] intraday_3377.csv.gz  in=345,007,645 out=103,945,320 elapsed=166.4s

  [11047/17668] intraday_3378.csv.gz  in=345,021,328 out=103,945,320 elapsed=166.4s

  [11048/17668] intraday_3379.csv.gz  in=345,034,877 out=103,945,320 elapsed=166.4s

  [11049/17668] intraday_3381.csv.gz  in=345,046,737 out=103,945,320 elapsed=166.4s

  [11050/17668] intraday_3380.csv.gz  in=345,056,324 out=103,945,320 elapsed=166.4s

  [11051/17668] intraday_3382.csv.gz  in=345,069,119 out=103,945,320 elapsed=166.4s

  [11052/17668] intraday_3383.csv.gz  in=345,079,303 out=103,945,320 elapsed=166.4s

  [11053/17668] intraday_3384.csv.gz  in=345,091,069 out=103,945,320 elapsed=166.4s

  [11054/17668] intraday_3385.csv.gz  in=345,102,400 out=103,945,320 elapsed=166.4s

  [11055/17668] intraday_3386.csv.gz  in=345,114,889 out=103,945,320 elapsed=166.4s

  [11056/17668] intraday_3387.csv.gz  in=345,127,044 out=103,945,320 elapsed=166.5s

  [11057/17668] intraday_3388.csv.gz  in=345,138,612 out=103,945,320 elapsed=166.5s

  [11058/17668] intraday_3389.csv.gz  in=345,151,008 out=103,945,320 elapsed=166.5s

  [11059/17668] intraday_3390.csv.gz  in=345,163,791 out=103,945,320 elapsed=166.5s

  [11060/17668] intraday_3391.csv.gz  in=345,175,161 out=103,945,320 elapsed=166.5s

  [11061/17668] intraday_3393.csv.gz  in=345,187,887 out=103,945,320 elapsed=166.5s

  [11062/17668] intraday_3392.csv.gz  in=345,200,039 out=103,945,320 elapsed=166.5s

  [11063/17668] intraday_3394.csv.gz  in=345,211,950 out=103,945,320 elapsed=166.5s

  [11064/17668] intraday_3395.csv.gz  in=345,223,105 out=103,945,320 elapsed=166.5s

  [11065/17668] intraday_3396.csv.gz  in=345,234,783 out=103,945,320 elapsed=166.5s

  [11066/17668] intraday_3397.csv.gz  in=345,247,574 out=103,945,320 elapsed=166.6s

  [11067/17668] intraday_3398.csv.gz  in=345,261,647 out=103,945,320 elapsed=166.6s

  [11068/17668] intraday_3399.csv.gz  in=345,277,975 out=103,945,320 elapsed=166.6s

  [11069/17668] intraday_3400.csv.gz  in=345,290,339 out=103,945,320 elapsed=166.6s

  [11070/17668] intraday_3402.csv.gz  in=345,302,206 out=103,945,320 elapsed=166.6s

  [11071/17668] intraday_3401.csv.gz  in=345,314,783 out=103,945,320 elapsed=166.6s

  [11072/17668] intraday_3403.csv.gz  in=345,327,893 out=103,945,320 elapsed=166.6s

  [11073/17668] intraday_3405.csv.gz  in=345,340,121 out=103,945,320 elapsed=166.6s

  [11074/17668] intraday_3404.csv.gz  in=345,352,836 out=103,945,320 elapsed=166.6s

  [11075/17668] intraday_3407.csv.gz  in=345,362,642 out=103,945,320 elapsed=166.6s

  [11076/17668] intraday_3406.csv.gz  in=345,373,607 out=103,945,320 elapsed=166.7s

  [11077/17668] intraday_3409.csv.gz  in=345,383,182 out=103,945,320 elapsed=166.7s

  [11078/17668] intraday_3408.csv.gz  in=345,394,801 out=103,945,320 elapsed=166.7s

  [11079/17668] intraday_3410.csv.gz  in=345,409,291 out=103,945,320 elapsed=166.7s

  [11080/17668] intraday_3411.csv.gz  in=345,421,885 out=103,945,320 elapsed=166.7s

  [11081/17668] intraday_3414.csv.gz  in=345,432,532 out=103,945,320 elapsed=166.7s

  [11082/17668] intraday_3412.csv.gz  in=345,445,160 out=103,945,320 elapsed=166.7s

  [11083/17668] intraday_3413.csv.gz  in=345,456,592 out=103,945,320 elapsed=166.7s

  [11084/17668] intraday_3415.csv.gz  in=345,469,543 out=103,945,320 elapsed=166.7s

  [11085/17668] intraday_3417.csv.gz  in=345,480,056 out=103,945,320 elapsed=166.7s

  [11086/17668] intraday_3418.csv.gz  in=345,491,993 out=103,945,320 elapsed=166.8s

  [11087/17668] intraday_3416.csv.gz  in=345,502,561 out=103,945,320 elapsed=166.8s

  [11088/17668] intraday_3420.csv.gz  in=345,513,899 out=103,945,320 elapsed=166.8s

  [11089/17668] intraday_3422.csv.gz  in=345,523,532 out=103,945,320 elapsed=166.8s

  [11090/17668] intraday_3419.csv.gz  in=345,535,082 out=103,945,320 elapsed=166.8s

  [11091/17668] intraday_3421.csv.gz  in=345,547,048 out=103,945,320 elapsed=166.8s

  [11092/17668] intraday_3426.csv.gz  in=345,556,940 out=103,945,320 elapsed=166.8s

  [11093/17668] intraday_3425.csv.gz  in=345,567,553 out=103,945,320 elapsed=166.8s

  [11094/17668] intraday_3424.csv.gz  in=345,579,203 out=103,945,320 elapsed=166.8s

  [11095/17668] intraday_3423.csv.gz  in=345,592,665 out=103,945,320 elapsed=166.8s

  [11096/17668] intraday_3427.csv.gz  in=345,604,808 out=103,945,320 elapsed=166.8s

  [11097/17668] intraday_3430.csv.gz  in=345,615,977 out=103,945,320 elapsed=166.8s

  [11098/17668] intraday_3429.csv.gz  in=345,627,202 out=103,945,320 elapsed=166.8s

  [11099/17668] intraday_3428.csv.gz  in=345,640,215 out=103,945,320 elapsed=166.9s

  [11100/17668] intraday_3432.csv.gz  in=345,649,746 out=103,945,320 elapsed=166.9s

  [11101/17668] intraday_3431.csv.gz  in=345,662,281 out=103,945,320 elapsed=166.9s

  [11102/17668] intraday_3433.csv.gz  in=345,676,231 out=103,945,320 elapsed=166.9s

  [11103/17668] intraday_3434.csv.gz  in=345,690,230 out=103,945,320 elapsed=166.9s

  [11104/17668] intraday_3435.csv.gz  in=345,700,673 out=103,945,320 elapsed=166.9s

  [11105/17668] intraday_3436.csv.gz  in=345,713,910 out=103,945,320 elapsed=166.9s

  [11106/17668] intraday_3437.csv.gz  in=345,727,118 out=103,945,320 elapsed=166.9s

  [11107/17668] intraday_3438.csv.gz  in=345,736,552 out=103,945,320 elapsed=166.9s

  [11108/17668] intraday_3440.csv.gz  in=345,748,103 out=103,945,320 elapsed=166.9s

  [11109/17668] intraday_3439.csv.gz  in=345,759,313 out=103,945,320 elapsed=167.0s

  [11110/17668] intraday_3442.csv.gz  in=345,768,388 out=103,945,320 elapsed=167.0s

  [11111/17668] intraday_3441.csv.gz  in=345,781,828 out=103,945,320 elapsed=167.0s

  [11112/17668] intraday_3443.csv.gz  in=345,793,184 out=103,945,320 elapsed=167.0s

  [11113/17668] intraday_3444.csv.gz  in=345,804,268 out=103,945,320 elapsed=167.0s

  [11114/17668] intraday_3445.csv.gz  in=345,816,442 out=103,945,320 elapsed=167.0s

  [11115/17668] intraday_3446.csv.gz  in=345,828,592 out=103,945,320 elapsed=167.0s

  [11116/17668] intraday_3447.csv.gz  in=345,841,247 out=103,945,320 elapsed=167.0s

  [11117/17668] intraday_3449.csv.gz  in=345,850,732 out=103,945,320 elapsed=167.0s

  [11118/17668] intraday_3448.csv.gz  in=345,861,246 out=103,945,320 elapsed=167.0s

  [11119/17668] intraday_3450.csv.gz  in=345,871,986 out=103,945,320 elapsed=167.0s

  [11120/17668] intraday_3451.csv.gz  in=345,887,926 out=103,945,320 elapsed=167.1s

  [11121/17668] intraday_3453.csv.gz  in=345,899,360 out=103,945,320 elapsed=167.1s

  [11122/17668] intraday_3452.csv.gz  in=345,912,114 out=103,945,320 elapsed=167.1s

  [11123/17668] intraday_3454.csv.gz  in=345,922,670 out=103,945,320 elapsed=167.1s

  [11124/17668] intraday_3455.csv.gz  in=345,933,137 out=103,945,320 elapsed=167.1s

  [11125/17668] intraday_3457.csv.gz  in=345,946,910 out=103,945,320 elapsed=167.1s

  [11126/17668] intraday_3456.csv.gz  in=345,959,203 out=103,945,320 elapsed=167.1s

  [11127/17668] intraday_3458.csv.gz  in=345,971,701 out=103,945,320 elapsed=167.1s

  [11128/17668] intraday_3460.csv.gz  in=345,985,870 out=103,945,320 elapsed=167.1s

  [11129/17668] intraday_3459.csv.gz  in=345,998,622 out=103,945,320 elapsed=167.1s

  [11130/17668] intraday_3461.csv.gz  in=346,012,154 out=103,945,320 elapsed=167.1s

  [11131/17668] intraday_3462.csv.gz  in=346,025,496 out=103,945,320 elapsed=167.1s

  [11132/17668] intraday_3465.csv.gz  in=346,036,048 out=103,945,320 elapsed=167.2s

  [11133/17668] intraday_3463.csv.gz  in=346,047,845 out=103,945,320 elapsed=167.2s

  [11134/17668] intraday_3464.csv.gz  in=346,060,451 out=103,945,320 elapsed=167.2s

  [11135/17668] intraday_3466.csv.gz  in=346,073,869 out=103,945,320 elapsed=167.2s

  [11136/17668] intraday_3467.csv.gz  in=346,085,586 out=103,945,320 elapsed=167.2s

  [11137/17668] intraday_3468.csv.gz  in=346,098,306 out=103,945,320 elapsed=167.2s

  [11138/17668] intraday_3469.csv.gz  in=346,108,517 out=103,945,320 elapsed=167.2s

  [11139/17668] intraday_3470.csv.gz  in=346,121,363 out=103,945,320 elapsed=167.2s

  [11140/17668] intraday_3471.csv.gz  in=346,133,715 out=103,945,320 elapsed=167.2s

  [11141/17668] intraday_3472.csv.gz  in=346,146,429 out=103,945,320 elapsed=167.3s

  [11142/17668] intraday_3473.csv.gz  in=346,160,515 out=103,945,320 elapsed=167.3s

  [11143/17668] intraday_3474.csv.gz  in=346,171,869 out=103,945,320 elapsed=167.3s

  [11144/17668] intraday_3475.csv.gz  in=346,183,912 out=103,945,320 elapsed=167.3s

  [11145/17668] intraday_3477.csv.gz  in=346,197,854 out=103,945,320 elapsed=167.3s

  [11146/17668] intraday_3476.csv.gz  in=346,212,840 out=103,945,320 elapsed=167.3s

  [11147/17668] intraday_3478.csv.gz  in=346,225,040 out=103,945,320 elapsed=167.3s

  [11148/17668] intraday_3479.csv.gz  in=346,237,703 out=103,945,320 elapsed=167.3s

  [11149/17668] intraday_3480.csv.gz  in=346,250,101 out=103,945,320 elapsed=167.3s

  [11150/17668] intraday_3481.csv.gz  in=346,262,517 out=103,945,320 elapsed=167.3s

  [11151/17668] intraday_3484.csv.gz  in=346,274,281 out=103,945,320 elapsed=167.3s

  [11152/17668] intraday_3482.csv.gz  in=346,287,864 out=103,945,320 elapsed=167.3s

  [11153/17668] intraday_3485.csv.gz  in=346,304,094 out=103,945,320 elapsed=167.4s

  [11154/17668] intraday_3483.csv.gz  in=346,318,949 out=103,945,320 elapsed=167.4s

  [11155/17668] intraday_3486.csv.gz  in=346,330,959 out=103,945,320 elapsed=167.4s

  [11156/17668] intraday_3489.csv.gz  in=346,343,946 out=103,945,320 elapsed=167.4s

  [11157/17668] intraday_3487.csv.gz  in=346,356,404 out=103,945,320 elapsed=167.4s

  [11158/17668] intraday_3488.csv.gz  in=346,367,514 out=103,945,320 elapsed=167.4s

  [11159/17668] intraday_3490.csv.gz  in=346,377,712 out=103,945,320 elapsed=167.4s

  [11160/17668] intraday_3491.csv.gz  in=346,392,480 out=103,945,320 elapsed=167.4s

  [11161/17668] intraday_3492.csv.gz  in=346,405,029 out=103,945,320 elapsed=167.4s

  [11162/17668] intraday_3493.csv.gz  in=346,419,513 out=103,945,320 elapsed=167.4s

  [11163/17668] intraday_3494.csv.gz  in=346,431,977 out=103,945,320 elapsed=167.4s

  [11164/17668] intraday_3495.csv.gz  in=346,444,976 out=103,945,320 elapsed=167.5s

  [11165/17668] intraday_3496.csv.gz  in=346,457,413 out=103,945,320 elapsed=167.5s

  [11166/17668] intraday_3497.csv.gz  in=346,470,543 out=103,945,320 elapsed=167.5s

  [11167/17668] intraday_3498.csv.gz  in=346,483,184 out=103,945,320 elapsed=167.5s

  [11168/17668] intraday_3500.csv.gz  in=346,497,774 out=103,945,320 elapsed=167.5s

  [11169/17668] intraday_3499.csv.gz  in=346,512,355 out=103,945,320 elapsed=167.5s

  [11170/17668] intraday_3502.csv.gz  in=346,525,722 out=103,945,320 elapsed=167.5s

  [11171/17668] intraday_3501.csv.gz  in=346,538,868 out=103,945,320 elapsed=167.5s

  [11172/17668] intraday_3503.csv.gz  in=346,550,598 out=103,945,320 elapsed=167.5s

  [11173/17668] intraday_3504.csv.gz  in=346,561,276 out=103,945,320 elapsed=167.5s

  [11174/17668] intraday_3506.csv.gz  in=346,574,387 out=103,945,320 elapsed=167.5s

  [11175/17668] intraday_3507.csv.gz  in=346,582,773 out=103,945,320 elapsed=167.5s

  [11176/17668] intraday_3505.csv.gz  in=346,594,612 out=103,945,320 elapsed=167.5s

  [11177/17668] intraday_3508.csv.gz  in=346,603,351 out=103,945,320 elapsed=167.6s

  [11178/17668] intraday_3510.csv.gz  in=346,617,558 out=103,945,320 elapsed=167.6s

  [11179/17668] intraday_3509.csv.gz  in=346,630,079 out=103,945,320 elapsed=167.6s

  [11180/17668] intraday_3511.csv.gz  in=346,643,476 out=103,945,320 elapsed=167.6s

  [11181/17668] intraday_3512.csv.gz  in=346,655,770 out=103,945,320 elapsed=167.6s

  [11182/17668] intraday_3515.csv.gz  in=346,669,368 out=103,945,320 elapsed=167.6s

  [11183/17668] intraday_3514.csv.gz  in=346,682,882 out=103,945,320 elapsed=167.6s

  [11184/17668] intraday_3513.csv.gz  in=346,692,870 out=103,945,320 elapsed=167.6s

  [11185/17668] intraday_3516.csv.gz  in=346,705,466 out=103,945,320 elapsed=167.6s

  [11186/17668] intraday_3517.csv.gz  in=346,717,495 out=103,945,320 elapsed=167.7s

  [11187/17668] intraday_3520.csv.gz  in=346,726,739 out=103,945,320 elapsed=167.7s

  [11188/17668] intraday_3519.csv.gz  in=346,740,089 out=103,945,320 elapsed=167.7s

  [11189/17668] intraday_3518.csv.gz  in=346,754,377 out=103,945,320 elapsed=167.7s

  [11190/17668] intraday_3521.csv.gz  in=346,766,814 out=103,945,320 elapsed=167.7s

  [11191/17668] intraday_3523.csv.gz  in=346,777,319 out=103,945,320 elapsed=167.7s

  [11192/17668] intraday_3522.csv.gz  in=346,789,494 out=103,945,320 elapsed=167.7s

  [11193/17668] intraday_3524.csv.gz  in=346,801,399 out=103,945,320 elapsed=167.7s

  [11194/17668] intraday_3525.csv.gz  in=346,812,733 out=103,945,320 elapsed=167.7s

  [11195/17668] intraday_3527.csv.gz  in=346,825,094 out=103,945,320 elapsed=167.7s

  [11196/17668] intraday_3526.csv.gz  in=346,837,789 out=103,945,320 elapsed=167.7s

  [11197/17668] intraday_3528.csv.gz  in=346,849,511 out=103,945,320 elapsed=167.7s

  [11198/17668] intraday_3529.csv.gz  in=346,862,625 out=103,945,320 elapsed=167.7s

  [11199/17668] intraday_3530.csv.gz  in=346,875,550 out=103,945,320 elapsed=167.8s

  [11200/17668] intraday_3531.csv.gz  in=346,886,930 out=103,945,320 elapsed=167.8s

  [11201/17668] intraday_3532.csv.gz  in=346,898,280 out=103,945,320 elapsed=167.8s

  [11202/17668] intraday_3534.csv.gz  in=346,910,683 out=103,945,320 elapsed=167.8s

  [11203/17668] intraday_3533.csv.gz  in=346,923,667 out=103,945,320 elapsed=167.8s

  [11204/17668] intraday_3535.csv.gz  in=346,934,272 out=103,945,320 elapsed=167.8s

  [11205/17668] intraday_3536.csv.gz  in=346,946,482 out=103,945,320 elapsed=167.8s

  [11206/17668] intraday_3538.csv.gz  in=346,960,624 out=103,945,320 elapsed=167.8s

  [11207/17668] intraday_3537.csv.gz  in=346,972,956 out=103,945,320 elapsed=167.8s

  [11208/17668] intraday_3539.csv.gz  in=346,987,232 out=103,945,320 elapsed=167.8s

  [11209/17668] intraday_3540.csv.gz  in=347,000,303 out=103,945,320 elapsed=167.8s

  [11210/17668] intraday_3542.csv.gz  in=347,011,753 out=103,945,320 elapsed=167.9s

  [11211/17668] intraday_3541.csv.gz  in=347,023,327 out=103,945,320 elapsed=167.9s

  [11212/17668] intraday_3544.csv.gz  in=347,034,846 out=103,945,320 elapsed=167.9s

  [11213/17668] intraday_3543.csv.gz  in=347,047,435 out=103,945,320 elapsed=167.9s

  [11214/17668] intraday_3545.csv.gz  in=347,059,759 out=103,945,320 elapsed=167.9s

  [11215/17668] intraday_3546.csv.gz  in=347,070,628 out=103,945,320 elapsed=167.9s

  [11216/17668] intraday_3547.csv.gz  in=347,081,315 out=103,945,320 elapsed=167.9s

  [11217/17668] intraday_3548.csv.gz  in=347,092,285 out=103,945,320 elapsed=167.9s

  [11218/17668] intraday_3550.csv.gz  in=347,106,158 out=103,945,320 elapsed=167.9s

  [11219/17668] intraday_3549.csv.gz  in=347,116,476 out=103,945,320 elapsed=167.9s

  [11220/17668] intraday_3551.csv.gz  in=347,128,742 out=103,945,320 elapsed=167.9s

  [11221/17668] intraday_3552.csv.gz  in=347,142,312 out=103,945,320 elapsed=167.9s

  [11222/17668] intraday_3554.csv.gz  in=347,153,649 out=103,945,320 elapsed=168.0s

  [11223/17668] intraday_3553.csv.gz  in=347,164,930 out=103,945,320 elapsed=168.0s

  [11224/17668] intraday_3555.csv.gz  in=347,177,584 out=103,945,320 elapsed=168.0s

  [11225/17668] intraday_3556.csv.gz  in=347,187,776 out=103,945,320 elapsed=168.0s

  [11226/17668] intraday_3557.csv.gz  in=347,199,560 out=103,945,320 elapsed=168.0s

  [11227/17668] intraday_3558.csv.gz  in=347,211,406 out=103,945,320 elapsed=168.0s

  [11228/17668] intraday_3560.csv.gz  in=347,222,833 out=103,945,320 elapsed=168.0s

  [11229/17668] intraday_3559.csv.gz  in=347,233,214 out=103,945,320 elapsed=168.0s

  [11230/17668] intraday_3562.csv.gz  in=347,243,627 out=103,945,320 elapsed=168.0s

  [11231/17668] intraday_3561.csv.gz  in=347,254,523 out=103,945,320 elapsed=168.0s

  [11232/17668] intraday_3564.csv.gz  in=347,266,847 out=103,945,320 elapsed=168.0s

  [11233/17668] intraday_3565.csv.gz  in=347,277,283 out=103,945,320 elapsed=168.1s

  [11234/17668] intraday_3563.csv.gz  in=347,290,125 out=103,945,320 elapsed=168.1s

  [11235/17668] intraday_3566.csv.gz  in=347,299,634 out=103,945,320 elapsed=168.1s

  [11236/17668] intraday_3567.csv.gz  in=347,313,422 out=103,945,320 elapsed=168.1s

  [11237/17668] intraday_3568.csv.gz  in=347,326,721 out=103,945,320 elapsed=168.1s

  [11238/17668] intraday_3569.csv.gz  in=347,337,903 out=103,945,320 elapsed=168.1s

  [11239/17668] intraday_3570.csv.gz  in=347,350,011 out=103,945,320 elapsed=168.1s

  [11240/17668] intraday_3572.csv.gz  in=347,360,335 out=103,945,320 elapsed=168.1s

  [11241/17668] intraday_3571.csv.gz  in=347,371,747 out=103,945,320 elapsed=168.1s

  [11242/17668] intraday_3573.csv.gz  in=347,385,109 out=103,945,320 elapsed=168.2s

  [11243/17668] intraday_3574.csv.gz  in=347,397,944 out=103,945,320 elapsed=168.2s

  [11244/17668] intraday_3575.csv.gz  in=347,410,476 out=103,945,320 elapsed=168.2s

  [11245/17668] intraday_3576.csv.gz  in=347,423,168 out=103,945,320 elapsed=168.2s

  [11246/17668] intraday_3577.csv.gz  in=347,433,687 out=103,945,320 elapsed=168.2s

  [11247/17668] intraday_3578.csv.gz  in=347,443,978 out=103,945,320 elapsed=168.2s

  [11248/17668] intraday_3579.csv.gz  in=347,455,813 out=103,945,320 elapsed=168.2s

  [11249/17668] intraday_3580.csv.gz  in=347,466,670 out=103,945,320 elapsed=168.2s

  [11250/17668] intraday_3581.csv.gz  in=347,479,962 out=103,945,320 elapsed=168.2s

  [11251/17668] intraday_3583.csv.gz  in=347,489,695 out=103,945,320 elapsed=168.2s

  [11252/17668] intraday_3582.csv.gz  in=347,499,951 out=103,945,320 elapsed=168.2s

  [11253/17668] intraday_3584.csv.gz  in=347,510,641 out=103,945,320 elapsed=168.2s

  [11254/17668] intraday_3585.csv.gz  in=347,523,366 out=103,945,320 elapsed=168.3s

  [11255/17668] intraday_3586.csv.gz  in=347,535,250 out=103,945,320 elapsed=168.3s

  [11256/17668] intraday_3587.csv.gz  in=347,548,051 out=103,945,320 elapsed=168.3s

  [11257/17668] intraday_3588.csv.gz  in=347,559,476 out=103,945,320 elapsed=168.3s

  [11258/17668] intraday_3589.csv.gz  in=347,570,984 out=103,945,320 elapsed=168.3s

  [11259/17668] intraday_3590.csv.gz  in=347,582,200 out=103,945,320 elapsed=168.3s

  [11260/17668] intraday_3591.csv.gz  in=347,595,880 out=103,945,320 elapsed=168.3s

  [11261/17668] intraday_3593.csv.gz  in=347,606,739 out=103,945,320 elapsed=168.3s

  [11262/17668] intraday_3592.csv.gz  in=347,619,138 out=103,945,320 elapsed=168.3s

  [11263/17668] intraday_3594.csv.gz  in=347,629,473 out=103,945,320 elapsed=168.3s

  [11264/17668] intraday_3596.csv.gz  in=347,641,857 out=103,945,320 elapsed=168.3s

  [11265/17668] intraday_3595.csv.gz  in=347,653,859 out=103,945,320 elapsed=168.4s

  [11266/17668] intraday_3597.csv.gz  in=347,668,969 out=103,945,320 elapsed=168.4s

  [11267/17668] intraday_3598.csv.gz  in=347,679,698 out=103,945,320 elapsed=168.4s

  [11268/17668] intraday_3599.csv.gz  in=347,697,006 out=103,945,320 elapsed=168.4s

  [11269/17668] intraday_3601.csv.gz  in=347,711,277 out=103,945,320 elapsed=168.4s

  [11270/17668] intraday_3602.csv.gz  in=347,724,277 out=103,945,320 elapsed=168.4s

  [11271/17668] intraday_3600.csv.gz  in=347,737,437 out=103,945,320 elapsed=168.4s

  [11272/17668] intraday_3605.csv.gz  in=347,749,684 out=103,945,320 elapsed=168.4s

  [11273/17668] intraday_3603.csv.gz  in=347,761,066 out=103,945,320 elapsed=168.4s

  [11274/17668] intraday_3604.csv.gz  in=347,772,528 out=103,945,320 elapsed=168.5s

  [11275/17668] intraday_3606.csv.gz  in=347,791,202 out=103,945,320 elapsed=168.5s

  [11276/17668] intraday_3608.csv.gz  in=347,803,278 out=103,945,320 elapsed=168.5s

  [11277/17668] intraday_3609.csv.gz  in=347,815,953 out=103,945,320 elapsed=168.5s

  [11278/17668] intraday_3607.csv.gz  in=347,827,175 out=103,945,320 elapsed=168.5s

  [11279/17668] intraday_3610.csv.gz  in=347,838,303 out=103,945,320 elapsed=168.5s

  [11280/17668] intraday_3611.csv.gz  in=347,852,153 out=103,945,320 elapsed=168.5s

  [11281/17668] intraday_3612.csv.gz  in=347,864,285 out=103,945,320 elapsed=168.5s

  [11282/17668] intraday_3614.csv.gz  in=347,876,945 out=103,945,320 elapsed=168.5s

  [11283/17668] intraday_3613.csv.gz  in=347,890,178 out=103,945,320 elapsed=168.6s

  [11284/17668] intraday_3616.csv.gz  in=347,904,302 out=103,945,320 elapsed=168.6s

  [11285/17668] intraday_3615.csv.gz  in=347,916,903 out=103,945,320 elapsed=168.6s

  [11286/17668] intraday_3617.csv.gz  in=347,929,870 out=103,945,320 elapsed=168.6s

  [11287/17668] intraday_3618.csv.gz  in=347,941,240 out=103,945,320 elapsed=168.6s

  [11288/17668] intraday_3619.csv.gz  in=347,954,746 out=103,945,320 elapsed=168.6s

  [11289/17668] intraday_3620.csv.gz  in=347,966,549 out=103,945,320 elapsed=168.6s

  [11290/17668] intraday_3621.csv.gz  in=347,979,182 out=103,945,320 elapsed=168.6s

  [11291/17668] intraday_3623.csv.gz  in=347,992,772 out=103,945,320 elapsed=168.6s

  [11292/17668] intraday_3622.csv.gz  in=348,006,871 out=103,945,320 elapsed=168.6s

  [11293/17668] intraday_3624.csv.gz  in=348,020,397 out=103,945,320 elapsed=168.6s

  [11294/17668] intraday_3625.csv.gz  in=348,034,296 out=103,945,320 elapsed=168.6s

  [11295/17668] intraday_3628.csv.gz  in=348,045,143 out=103,945,320 elapsed=168.7s

  [11296/17668] intraday_3627.csv.gz  in=348,057,109 out=103,945,320 elapsed=168.7s

  [11297/17668] intraday_3626.csv.gz  in=348,069,643 out=103,945,320 elapsed=168.7s

  [11298/17668] intraday_3629.csv.gz  in=348,082,323 out=103,945,320 elapsed=168.7s

  [11299/17668] intraday_3630.csv.gz  in=348,091,938 out=103,945,320 elapsed=168.7s

  [11300/17668] intraday_3631.csv.gz  in=348,104,822 out=103,945,320 elapsed=168.7s

  [11301/17668] intraday_3632.csv.gz  in=348,117,668 out=103,945,320 elapsed=168.7s

  [11302/17668] intraday_3633.csv.gz  in=348,136,178 out=103,945,320 elapsed=168.7s

  [11303/17668] intraday_3634.csv.gz  in=348,147,231 out=103,945,320 elapsed=168.8s

  [11304/17668] intraday_3637.csv.gz  in=348,158,999 out=103,945,320 elapsed=168.8s

  [11305/17668] intraday_3636.csv.gz  in=348,171,739 out=103,945,320 elapsed=168.8s

  [11306/17668] intraday_3635.csv.gz  in=348,184,639 out=103,945,320 elapsed=168.8s

  [11307/17668] intraday_3638.csv.gz  in=348,198,216 out=103,945,320 elapsed=168.8s

  [11308/17668] intraday_3640.csv.gz  in=348,212,269 out=103,945,320 elapsed=168.8s

  [11309/17668] intraday_3641.csv.gz  in=348,225,029 out=103,945,320 elapsed=168.8s

  [11310/17668] intraday_3639.csv.gz  in=348,242,899 out=103,945,320 elapsed=168.8s

  [11311/17668] intraday_3642.csv.gz  in=348,255,562 out=103,945,320 elapsed=168.9s

  [11312/17668] intraday_3645.csv.gz  in=348,266,611 out=103,945,320 elapsed=168.9s

  [11313/17668] intraday_3643.csv.gz  in=348,277,827 out=103,945,320 elapsed=168.9s

  [11314/17668] intraday_3644.csv.gz  in=348,289,329 out=103,945,320 elapsed=168.9s

  [11315/17668] intraday_3646.csv.gz  in=348,302,908 out=103,945,320 elapsed=168.9s

  [11316/17668] intraday_3647.csv.gz  in=348,311,775 out=103,945,320 elapsed=168.9s

  [11317/17668] intraday_3648.csv.gz  in=348,320,240 out=103,945,320 elapsed=168.9s

  [11318/17668] intraday_3649.csv.gz  in=348,330,314 out=103,945,320 elapsed=168.9s

  [11319/17668] intraday_3650.csv.gz  in=348,345,512 out=103,945,320 elapsed=168.9s

  [11320/17668] intraday_3652.csv.gz  in=348,358,851 out=103,945,320 elapsed=168.9s

  [11321/17668] intraday_3651.csv.gz  in=348,373,027 out=103,945,320 elapsed=168.9s

  [11322/17668] intraday_3654.csv.gz  in=348,387,750 out=103,945,320 elapsed=168.9s

  [11323/17668] intraday_3653.csv.gz  in=348,398,151 out=103,945,320 elapsed=168.9s

  [11324/17668] intraday_3655.csv.gz  in=348,412,580 out=103,945,320 elapsed=169.0s

  [11325/17668] intraday_3658.csv.gz  in=348,426,638 out=103,945,320 elapsed=169.0s

  [11326/17668] intraday_3656.csv.gz  in=348,442,700 out=103,945,320 elapsed=169.0s

  [11327/17668] intraday_3657.csv.gz  in=348,455,283 out=103,945,320 elapsed=169.0s

  [11328/17668] intraday_3660.csv.gz  in=348,464,974 out=103,945,320 elapsed=169.0s

  [11329/17668] intraday_3662.csv.gz  in=348,477,928 out=103,945,320 elapsed=169.0s

  [11330/17668] intraday_3659.csv.gz  in=348,493,036 out=103,945,320 elapsed=169.0s

  [11331/17668] intraday_3663.csv.gz  in=348,503,770 out=103,945,320 elapsed=169.0s

  [11332/17668] intraday_3661.csv.gz  in=348,516,340 out=103,945,320 elapsed=169.0s

  [11333/17668] intraday_3664.csv.gz  in=348,528,288 out=103,945,320 elapsed=169.1s

  [11334/17668] intraday_3665.csv.gz  in=348,539,896 out=103,945,320 elapsed=169.1s

  [11335/17668] intraday_3667.csv.gz  in=348,552,881 out=103,945,320 elapsed=169.1s

  [11336/17668] intraday_3666.csv.gz  in=348,565,761 out=103,945,320 elapsed=169.1s

  [11337/17668] intraday_3669.csv.gz  in=348,579,022 out=103,945,320 elapsed=169.1s

  [11338/17668] intraday_3668.csv.gz  in=348,589,825 out=103,945,320 elapsed=169.1s

  [11339/17668] intraday_3671.csv.gz  in=348,601,152 out=103,945,320 elapsed=169.1s

  [11340/17668] intraday_3672.csv.gz  in=348,613,456 out=103,945,320 elapsed=169.1s

  [11341/17668] intraday_3673.csv.gz  in=348,625,635 out=103,945,320 elapsed=169.1s

  [11342/17668] intraday_3674.csv.gz  in=348,638,136 out=103,945,320 elapsed=169.2s

  [11343/17668] intraday_3670.csv.gz  in=348,652,185 out=103,945,320 elapsed=169.2s

  [11344/17668] intraday_3675.csv.gz  in=348,663,166 out=103,945,320 elapsed=169.2s

  [11345/17668] intraday_3676.csv.gz  in=348,675,778 out=103,945,320 elapsed=169.2s

  [11346/17668] intraday_3677.csv.gz  in=348,688,548 out=103,945,320 elapsed=169.2s

  [11347/17668] intraday_3678.csv.gz  in=348,702,877 out=103,945,320 elapsed=169.2s

  [11348/17668] intraday_3679.csv.gz  in=348,719,360 out=103,945,320 elapsed=169.2s

  [11349/17668] intraday_3680.csv.gz  in=348,735,798 out=103,945,320 elapsed=169.2s

  [11350/17668] intraday_3683.csv.gz  in=348,748,415 out=103,945,320 elapsed=169.2s

  [11351/17668] intraday_3682.csv.gz  in=348,759,975 out=103,945,320 elapsed=169.2s

  [11352/17668] intraday_3681.csv.gz  in=348,770,948 out=103,945,320 elapsed=169.2s

  [11353/17668] intraday_3684.csv.gz  in=348,782,724 out=103,945,320 elapsed=169.3s

  [11354/17668] intraday_3687.csv.gz  in=348,792,430 out=103,945,320 elapsed=169.3s

  [11355/17668] intraday_3686.csv.gz  in=348,807,068 out=103,945,320 elapsed=169.3s

  [11356/17668] intraday_3685.csv.gz  in=348,820,124 out=103,945,320 elapsed=169.3s

  [11357/17668] intraday_3688.csv.gz  in=348,833,441 out=103,945,320 elapsed=169.3s

  [11358/17668] intraday_3690.csv.gz  in=348,847,176 out=103,945,320 elapsed=169.3s

  [11359/17668] intraday_3691.csv.gz  in=348,859,517 out=103,945,320 elapsed=169.3s

  [11360/17668] intraday_3689.csv.gz  in=348,869,943 out=103,945,320 elapsed=169.3s

  [11361/17668] intraday_3692.csv.gz  in=348,881,955 out=103,945,320 elapsed=169.3s

  [11362/17668] intraday_3693.csv.gz  in=348,893,633 out=103,945,320 elapsed=169.3s

  [11363/17668] intraday_3694.csv.gz  in=348,904,876 out=103,945,320 elapsed=169.3s

  [11364/17668] intraday_3695.csv.gz  in=348,918,134 out=103,945,320 elapsed=169.3s

  [11365/17668] intraday_3696.csv.gz  in=348,928,953 out=103,945,320 elapsed=169.4s

  [11366/17668] intraday_3697.csv.gz  in=348,941,113 out=103,945,320 elapsed=169.4s

  [11367/17668] intraday_3698.csv.gz  in=348,953,223 out=103,945,320 elapsed=169.4s

  [11368/17668] intraday_3700.csv.gz  in=348,965,173 out=103,945,320 elapsed=169.4s

  [11369/17668] intraday_3699.csv.gz  in=348,976,437 out=103,945,320 elapsed=169.4s

  [11370/17668] intraday_3701.csv.gz  in=348,991,016 out=103,945,320 elapsed=169.4s

  [11371/17668] intraday_3704.csv.gz  in=349,002,628 out=103,945,320 elapsed=169.4s

  [11372/17668] intraday_3702.csv.gz  in=349,012,537 out=103,945,320 elapsed=169.4s

  [11373/17668] intraday_3703.csv.gz  in=349,026,187 out=103,945,320 elapsed=169.4s

  [11374/17668] intraday_3705.csv.gz  in=349,037,049 out=103,945,320 elapsed=169.5s

  [11375/17668] intraday_3706.csv.gz  in=349,047,927 out=103,945,320 elapsed=169.5s

  [11376/17668] intraday_3707.csv.gz  in=349,062,692 out=103,945,320 elapsed=169.5s

  [11377/17668] intraday_3708.csv.gz  in=349,075,992 out=103,945,320 elapsed=169.5s

  [11378/17668] intraday_3710.csv.gz  in=349,087,005 out=103,945,320 elapsed=169.5s

  [11379/17668] intraday_3709.csv.gz  in=349,098,800 out=103,945,320 elapsed=169.5s

  [11380/17668] intraday_3714.csv.gz  in=349,112,138 out=103,945,320 elapsed=169.5s

  [11381/17668] intraday_3711.csv.gz  in=349,134,633 out=103,945,320 elapsed=169.5s

  [11382/17668] intraday_3712.csv.gz  in=349,144,779 out=103,945,320 elapsed=169.5s

  [11383/17668] intraday_3713.csv.gz  in=349,161,502 out=103,945,320 elapsed=169.5s

  [11384/17668] intraday_3717.csv.gz  in=349,177,248 out=103,945,320 elapsed=169.6s

  [11385/17668] intraday_3718.csv.gz  in=349,187,144 out=103,945,320 elapsed=169.6s

  [11386/17668] intraday_3715.csv.gz  in=349,199,647 out=103,945,320 elapsed=169.6s

  [11387/17668] intraday_3716.csv.gz  in=349,211,819 out=103,945,320 elapsed=169.6s

  [11388/17668] intraday_3720.csv.gz  in=349,223,619 out=103,945,320 elapsed=169.6s

  [11389/17668] intraday_3721.csv.gz  in=349,236,911 out=103,945,320 elapsed=169.6s

  [11390/17668] intraday_3722.csv.gz  in=349,247,342 out=103,945,320 elapsed=169.6s

  [11391/17668] intraday_3719.csv.gz  in=349,259,387 out=103,945,320 elapsed=169.6s

  [11392/17668] intraday_3723.csv.gz  in=349,271,539 out=103,945,320 elapsed=169.6s

  [11393/17668] intraday_3724.csv.gz  in=349,283,507 out=103,945,320 elapsed=169.6s

  [11394/17668] intraday_3726.csv.gz  in=349,295,961 out=103,945,320 elapsed=169.6s

  [11395/17668] intraday_3725.csv.gz  in=349,308,861 out=103,945,320 elapsed=169.6s

  [11396/17668] intraday_3727.csv.gz  in=349,322,484 out=103,945,320 elapsed=169.7s

  [11397/17668] intraday_3728.csv.gz  in=349,334,893 out=103,945,320 elapsed=169.7s

  [11398/17668] intraday_3730.csv.gz  in=349,345,307 out=103,945,320 elapsed=169.7s

  [11399/17668] intraday_3729.csv.gz  in=349,358,798 out=103,945,320 elapsed=169.7s

  [11400/17668] intraday_3732.csv.gz  in=349,371,296 out=103,945,320 elapsed=169.7s

  [11401/17668] intraday_3731.csv.gz  in=349,387,801 out=103,945,320 elapsed=169.7s

  [11402/17668] intraday_3733.csv.gz  in=349,399,895 out=103,945,320 elapsed=169.7s

  [11403/17668] intraday_3735.csv.gz  in=349,411,829 out=103,945,320 elapsed=169.7s

  [11404/17668] intraday_3734.csv.gz  in=349,422,629 out=103,945,320 elapsed=169.7s

  [11405/17668] intraday_3736.csv.gz  in=349,436,614 out=103,945,320 elapsed=169.7s

  [11406/17668] intraday_3737.csv.gz  in=349,451,375 out=103,945,320 elapsed=169.7s

  [11407/17668] intraday_3738.csv.gz  in=349,465,436 out=103,945,320 elapsed=169.8s

  [11408/17668] intraday_3739.csv.gz  in=349,476,228 out=103,945,320 elapsed=169.8s

  [11409/17668] intraday_3740.csv.gz  in=349,492,036 out=103,945,320 elapsed=169.8s

  [11410/17668] intraday_3741.csv.gz  in=349,506,284 out=103,945,320 elapsed=169.8s

  [11411/17668] intraday_3742.csv.gz  in=349,520,347 out=103,945,320 elapsed=169.8s

  [11412/17668] intraday_3745.csv.gz  in=349,532,135 out=103,945,320 elapsed=169.8s

  [11413/17668] intraday_3743.csv.gz  in=349,543,958 out=103,945,320 elapsed=169.8s

  [11414/17668] intraday_3744.csv.gz  in=349,556,709 out=103,945,320 elapsed=169.8s

  [11415/17668] intraday_3746.csv.gz  in=349,569,932 out=103,945,320 elapsed=169.8s

  [11416/17668] intraday_3748.csv.gz  in=349,581,882 out=103,945,320 elapsed=169.8s

  [11417/17668] intraday_3747.csv.gz  in=349,594,341 out=103,945,320 elapsed=169.9s

  [11418/17668] intraday_3749.csv.gz  in=349,609,607 out=103,945,320 elapsed=169.9s

  [11419/17668] intraday_3750.csv.gz  in=349,623,131 out=103,945,320 elapsed=169.9s

  [11420/17668] intraday_3751.csv.gz  in=349,636,656 out=103,945,320 elapsed=169.9s

  [11421/17668] intraday_3752.csv.gz  in=349,649,560 out=103,945,320 elapsed=169.9s

  [11422/17668] intraday_3753.csv.gz  in=349,665,360 out=103,945,320 elapsed=169.9s

  [11423/17668] intraday_3754.csv.gz  in=349,677,266 out=103,945,320 elapsed=169.9s

  [11424/17668] intraday_3755.csv.gz  in=349,691,319 out=103,945,320 elapsed=169.9s

  [11425/17668] intraday_3756.csv.gz  in=349,706,146 out=103,945,320 elapsed=169.9s

  [11426/17668] intraday_3758.csv.gz  in=349,718,678 out=103,945,320 elapsed=169.9s

  [11427/17668] intraday_3757.csv.gz  in=349,732,838 out=103,945,320 elapsed=170.0s

  [11428/17668] intraday_3759.csv.gz  in=349,745,255 out=103,945,320 elapsed=170.0s

  [11429/17668] intraday_3761.csv.gz  in=349,757,770 out=103,945,320 elapsed=170.0s

  [11430/17668] intraday_3760.csv.gz  in=349,781,632 out=103,945,320 elapsed=170.0s

  [11431/17668] intraday_3763.csv.gz  in=349,798,827 out=103,945,320 elapsed=170.0s

  [11432/17668] intraday_3762.csv.gz  in=349,814,355 out=103,945,320 elapsed=170.0s

  [11433/17668] intraday_3764.csv.gz  in=349,828,674 out=103,945,320 elapsed=170.0s

  [11434/17668] intraday_3765.csv.gz  in=349,844,072 out=103,945,320 elapsed=170.0s

  [11435/17668] intraday_3767.csv.gz  in=349,857,730 out=103,945,320 elapsed=170.0s

  [11436/17668] intraday_3766.csv.gz  in=349,877,088 out=103,945,320 elapsed=170.0s

  [11437/17668] intraday_3768.csv.gz  in=349,889,220 out=103,945,320 elapsed=170.0s

  [11438/17668] intraday_3769.csv.gz  in=349,906,869 out=103,945,320 elapsed=170.0s

  [11439/17668] intraday_3770.csv.gz  in=349,918,213 out=103,945,320 elapsed=170.1s

  [11440/17668] intraday_3771.csv.gz  in=349,930,762 out=103,945,320 elapsed=170.1s

  [11441/17668] intraday_3772.csv.gz  in=349,943,837 out=103,945,320 elapsed=170.1s

  [11442/17668] intraday_3773.csv.gz  in=349,956,604 out=103,945,320 elapsed=170.1s

  [11443/17668] intraday_3774.csv.gz  in=349,972,025 out=103,945,320 elapsed=170.1s

  [11444/17668] intraday_3775.csv.gz  in=349,984,170 out=103,945,320 elapsed=170.1s

  [11445/17668] intraday_3776.csv.gz  in=349,996,595 out=103,945,320 elapsed=170.1s

  [11446/17668] intraday_3777.csv.gz  in=350,010,333 out=103,945,320 elapsed=170.1s

  [11447/17668] intraday_3778.csv.gz  in=350,022,627 out=103,945,320 elapsed=170.1s

  [11448/17668] intraday_3779.csv.gz  in=350,035,335 out=103,945,320 elapsed=170.1s

  [11449/17668] intraday_3781.csv.gz  in=350,049,220 out=103,945,320 elapsed=170.2s

  [11450/17668] intraday_3780.csv.gz  in=350,063,896 out=103,945,320 elapsed=170.2s

  [11451/17668] intraday_3782.csv.gz  in=350,077,445 out=103,945,320 elapsed=170.2s

  [11452/17668] intraday_3783.csv.gz  in=350,090,106 out=103,945,320 elapsed=170.2s

  [11453/17668] intraday_3784.csv.gz  in=350,101,626 out=103,945,320 elapsed=170.2s

  [11454/17668] intraday_3785.csv.gz  in=350,113,371 out=103,945,320 elapsed=170.2s

  [11455/17668] intraday_3786.csv.gz  in=350,124,597 out=103,945,320 elapsed=170.2s

  [11456/17668] intraday_3787.csv.gz  in=350,138,778 out=103,945,320 elapsed=170.2s

  [11457/17668] intraday_3788.csv.gz  in=350,146,013 out=103,945,320 elapsed=170.2s

  [11458/17668] intraday_3790.csv.gz  in=350,154,392 out=103,945,320 elapsed=170.2s

  [11459/17668] intraday_3789.csv.gz  in=350,165,964 out=103,945,320 elapsed=170.2s

  [11460/17668] intraday_3791.csv.gz  in=350,181,452 out=103,945,320 elapsed=170.3s

  [11461/17668] intraday_3792.csv.gz  in=350,196,645 out=103,945,320 elapsed=170.3s

  [11462/17668] intraday_3793.csv.gz  in=350,209,438 out=103,945,320 elapsed=170.3s

  [11463/17668] intraday_3794.csv.gz  in=350,219,601 out=103,945,320 elapsed=170.3s

  [11464/17668] intraday_3796.csv.gz  in=350,234,059 out=103,945,320 elapsed=170.3s

  [11465/17668] intraday_3795.csv.gz  in=350,250,045 out=103,945,320 elapsed=170.3s

  [11466/17668] intraday_3797.csv.gz  in=350,262,472 out=103,945,320 elapsed=170.3s

  [11467/17668] intraday_3799.csv.gz  in=350,277,262 out=103,945,320 elapsed=170.3s

  [11468/17668] intraday_3798.csv.gz  in=350,289,186 out=103,945,320 elapsed=170.3s

  [11469/17668] intraday_3801.csv.gz  in=350,299,032 out=103,945,320 elapsed=170.3s

  [11470/17668] intraday_3800.csv.gz  in=350,314,446 out=103,945,320 elapsed=170.3s

  [11471/17668] intraday_3803.csv.gz  in=350,327,607 out=103,945,320 elapsed=170.4s

  [11472/17668] intraday_3802.csv.gz  in=350,339,364 out=103,945,320 elapsed=170.4s

  [11473/17668] intraday_3804.csv.gz  in=350,349,771 out=103,945,320 elapsed=170.4s

  [11474/17668] intraday_3805.csv.gz  in=350,361,163 out=103,945,320 elapsed=170.4s

  [11475/17668] intraday_3806.csv.gz  in=350,372,724 out=103,945,320 elapsed=170.4s

  [11476/17668] intraday_3807.csv.gz  in=350,385,793 out=103,945,320 elapsed=170.4s

  [11477/17668] intraday_3808.csv.gz  in=350,399,001 out=103,945,320 elapsed=170.4s

  [11478/17668] intraday_3809.csv.gz  in=350,409,558 out=103,945,320 elapsed=170.4s

  [11479/17668] intraday_3810.csv.gz  in=350,422,524 out=103,945,320 elapsed=170.4s

  [11480/17668] intraday_3811.csv.gz  in=350,436,977 out=103,945,320 elapsed=170.4s

  [11481/17668] intraday_3812.csv.gz  in=350,448,881 out=103,945,320 elapsed=170.5s

  [11482/17668] intraday_3813.csv.gz  in=350,461,020 out=103,945,320 elapsed=170.5s

  [11483/17668] intraday_3814.csv.gz  in=350,473,140 out=103,945,320 elapsed=170.5s

  [11484/17668] intraday_3815.csv.gz  in=350,485,583 out=103,945,320 elapsed=170.5s

  [11485/17668] intraday_3816.csv.gz  in=350,495,146 out=103,945,320 elapsed=170.5s

  [11486/17668] intraday_3817.csv.gz  in=350,508,136 out=103,945,320 elapsed=170.5s

  [11487/17668] intraday_3818.csv.gz  in=350,520,980 out=103,945,320 elapsed=170.5s

  [11488/17668] intraday_3819.csv.gz  in=350,540,624 out=103,945,320 elapsed=170.5s

  [11489/17668] intraday_3820.csv.gz  in=350,555,487 out=103,945,320 elapsed=170.5s

  [11490/17668] intraday_3822.csv.gz  in=350,567,396 out=103,945,320 elapsed=170.5s

  [11491/17668] intraday_3821.csv.gz  in=350,582,473 out=103,945,320 elapsed=170.5s

  [11492/17668] intraday_3823.csv.gz  in=350,594,718 out=103,945,320 elapsed=170.6s

  [11493/17668] intraday_3824.csv.gz  in=350,608,065 out=103,945,320 elapsed=170.6s

  [11494/17668] intraday_3825.csv.gz  in=350,619,686 out=103,945,320 elapsed=170.6s

  [11495/17668] intraday_3826.csv.gz  in=350,633,252 out=103,945,320 elapsed=170.6s

  [11496/17668] intraday_3829.csv.gz  in=350,644,688 out=103,945,320 elapsed=170.6s

  [11497/17668] intraday_3827.csv.gz  in=350,655,066 out=103,945,320 elapsed=170.6s

  [11498/17668] intraday_3830.csv.gz  in=350,665,083 out=103,945,320 elapsed=170.6s

  [11499/17668] intraday_3828.csv.gz  in=350,675,681 out=103,945,320 elapsed=170.6s

  [11500/17668] intraday_3831.csv.gz  in=350,690,352 out=103,945,320 elapsed=170.6s

  [11501/17668] intraday_3832.csv.gz  in=350,702,521 out=103,945,320 elapsed=170.7s

  [11502/17668] intraday_3834.csv.gz  in=350,714,376 out=103,945,320 elapsed=170.7s

  [11503/17668] intraday_3833.csv.gz  in=350,736,397 out=103,945,320 elapsed=170.7s

  [11504/17668] intraday_3836.csv.gz  in=350,749,526 out=103,945,320 elapsed=170.7s

  [11505/17668] intraday_3835.csv.gz  in=350,760,683 out=103,945,320 elapsed=170.7s

  [11506/17668] intraday_3837.csv.gz  in=350,771,879 out=103,945,320 elapsed=170.7s

  [11507/17668] intraday_3840.csv.gz  in=350,782,984 out=103,945,320 elapsed=170.7s

  [11508/17668] intraday_3838.csv.gz  in=350,795,262 out=103,945,320 elapsed=170.7s

  [11509/17668] intraday_3839.csv.gz  in=350,810,612 out=103,945,320 elapsed=170.7s

  [11510/17668] intraday_3841.csv.gz  in=350,821,698 out=103,945,320 elapsed=170.7s

  [11511/17668] intraday_3843.csv.gz  in=350,832,513 out=103,945,320 elapsed=170.7s

  [11512/17668] intraday_3842.csv.gz  in=350,844,343 out=103,945,320 elapsed=170.7s

  [11513/17668] intraday_3844.csv.gz  in=350,856,411 out=103,945,320 elapsed=170.8s

  [11514/17668] intraday_3845.csv.gz  in=350,869,363 out=103,945,320 elapsed=170.8s

  [11515/17668] intraday_3847.csv.gz  in=350,879,909 out=103,945,320 elapsed=170.8s

  [11516/17668] intraday_3848.csv.gz  in=350,893,794 out=103,945,320 elapsed=170.8s

  [11517/17668] intraday_3846.csv.gz  in=350,905,175 out=103,945,320 elapsed=170.8s

  [11518/17668] intraday_3849.csv.gz  in=350,918,875 out=103,945,320 elapsed=170.8s

  [11519/17668] intraday_3850.csv.gz  in=350,936,341 out=103,945,320 elapsed=170.8s

  [11520/17668] intraday_3851.csv.gz  in=350,947,417 out=103,945,320 elapsed=170.8s

  [11521/17668] intraday_3853.csv.gz  in=350,958,992 out=103,945,320 elapsed=170.8s

  [11522/17668] intraday_3852.csv.gz  in=350,971,761 out=103,945,320 elapsed=170.8s

  [11523/17668] intraday_3854.csv.gz  in=350,986,441 out=103,945,320 elapsed=170.8s

  [11524/17668] intraday_3856.csv.gz  in=350,997,746 out=103,945,320 elapsed=170.9s

  [11525/17668] intraday_3855.csv.gz  in=351,013,411 out=103,945,320 elapsed=170.9s

  [11526/17668] intraday_3857.csv.gz  in=351,026,680 out=103,945,320 elapsed=170.9s

  [11527/17668] intraday_3858.csv.gz  in=351,039,788 out=103,945,320 elapsed=170.9s

  [11528/17668] intraday_3859.csv.gz  in=351,050,125 out=103,945,320 elapsed=170.9s

  [11529/17668] intraday_3862.csv.gz  in=351,063,672 out=103,945,320 elapsed=170.9s

  [11530/17668] intraday_3860.csv.gz  in=351,074,961 out=103,945,320 elapsed=170.9s

  [11531/17668] intraday_3861.csv.gz  in=351,086,459 out=103,945,320 elapsed=170.9s

  [11532/17668] intraday_3863.csv.gz  in=351,096,507 out=103,945,320 elapsed=170.9s

  [11533/17668] intraday_3864.csv.gz  in=351,108,968 out=103,945,320 elapsed=171.0s

  [11534/17668] intraday_3865.csv.gz  in=351,120,384 out=103,945,320 elapsed=171.0s

  [11535/17668] intraday_3866.csv.gz  in=351,133,255 out=103,945,320 elapsed=171.0s

  [11536/17668] intraday_3867.csv.gz  in=351,146,516 out=103,945,320 elapsed=171.0s

  [11537/17668] intraday_3868.csv.gz  in=351,159,641 out=103,945,320 elapsed=171.0s

  [11538/17668] intraday_3869.csv.gz  in=351,171,350 out=103,945,320 elapsed=171.0s

  [11539/17668] intraday_3870.csv.gz  in=351,182,423 out=103,945,320 elapsed=171.0s

  [11540/17668] intraday_3871.csv.gz  in=351,192,934 out=103,945,320 elapsed=171.0s

  [11541/17668] intraday_3874.csv.gz  in=351,205,373 out=103,945,320 elapsed=171.0s

  [11542/17668] intraday_3875.csv.gz  in=351,215,817 out=103,945,320 elapsed=171.0s

  [11543/17668] intraday_3872.csv.gz  in=351,233,184 out=103,945,320 elapsed=171.0s

  [11544/17668] intraday_3873.csv.gz  in=351,252,964 out=103,945,320 elapsed=171.1s

  [11545/17668] intraday_3876.csv.gz  in=351,265,796 out=103,945,320 elapsed=171.1s

  [11546/17668] intraday_3877.csv.gz  in=351,279,529 out=103,945,320 elapsed=171.1s

  [11547/17668] intraday_3878.csv.gz  in=351,294,135 out=103,945,320 elapsed=171.1s

  [11548/17668] intraday_3879.csv.gz  in=351,307,837 out=103,945,320 elapsed=171.1s

  [11549/17668] intraday_3880.csv.gz  in=351,318,853 out=103,945,320 elapsed=171.1s

  [11550/17668] intraday_3882.csv.gz  in=351,333,708 out=103,945,320 elapsed=171.1s

  [11551/17668] intraday_3881.csv.gz  in=351,355,479 out=103,945,320 elapsed=171.1s

  [11552/17668] intraday_3883.csv.gz  in=351,371,665 out=103,945,320 elapsed=171.1s

  [11553/17668] intraday_3884.csv.gz  in=351,383,699 out=103,945,320 elapsed=171.1s

  [11554/17668] intraday_3886.csv.gz  in=351,395,421 out=103,945,320 elapsed=171.1s

  [11555/17668] intraday_3885.csv.gz  in=351,407,574 out=103,945,320 elapsed=171.1s

  [11556/17668] intraday_3887.csv.gz  in=351,421,026 out=103,945,320 elapsed=171.1s

  [11557/17668] intraday_3888.csv.gz  in=351,433,205 out=103,945,320 elapsed=171.2s

  [11558/17668] intraday_3889.csv.gz  in=351,445,707 out=103,945,320 elapsed=171.2s

  [11559/17668] intraday_3891.csv.gz  in=351,459,903 out=103,945,320 elapsed=171.2s

  [11560/17668] intraday_3890.csv.gz  in=351,472,647 out=103,945,320 elapsed=171.2s

  [11561/17668] intraday_3892.csv.gz  in=351,487,188 out=103,945,320 elapsed=171.2s

  [11562/17668] intraday_3893.csv.gz  in=351,500,707 out=103,945,320 elapsed=171.2s

  [11563/17668] intraday_3895.csv.gz  in=351,512,182 out=103,945,320 elapsed=171.2s

  [11564/17668] intraday_3896.csv.gz  in=351,524,347 out=103,945,320 elapsed=171.2s

  [11565/17668] intraday_3894.csv.gz  in=351,540,965 out=103,945,320 elapsed=171.2s

  [11566/17668] intraday_3897.csv.gz  in=351,556,220 out=103,945,320 elapsed=171.2s

  [11567/17668] intraday_3898.csv.gz  in=351,570,920 out=103,945,320 elapsed=171.3s

  [11568/17668] intraday_3899.csv.gz  in=351,581,904 out=103,945,320 elapsed=171.3s

  [11569/17668] intraday_3901.csv.gz  in=351,594,442 out=103,945,320 elapsed=171.3s

  [11570/17668] intraday_3900.csv.gz  in=351,608,727 out=103,945,320 elapsed=171.3s

  [11571/17668] intraday_3902.csv.gz  in=351,621,650 out=103,945,320 elapsed=171.3s

  [11572/17668] intraday_3903.csv.gz  in=351,636,611 out=103,945,320 elapsed=171.3s

  [11573/17668] intraday_3904.csv.gz  in=351,650,711 out=103,945,320 elapsed=171.3s

  [11574/17668] intraday_3907.csv.gz  in=351,662,115 out=103,945,320 elapsed=171.3s

  [11575/17668] intraday_3905.csv.gz  in=351,679,160 out=103,945,320 elapsed=171.3s

  [11576/17668] intraday_3906.csv.gz  in=351,694,615 out=103,945,320 elapsed=171.3s

  [11577/17668] intraday_3910.csv.gz  in=351,706,437 out=103,945,320 elapsed=171.4s

  [11578/17668] intraday_3909.csv.gz  in=351,718,949 out=103,945,320 elapsed=171.4s

  [11579/17668] intraday_3908.csv.gz  in=351,732,334 out=103,945,320 elapsed=171.4s

  [11580/17668] intraday_3911.csv.gz  in=351,743,484 out=103,945,320 elapsed=171.4s

  [11581/17668] intraday_3912.csv.gz  in=351,755,299 out=103,945,320 elapsed=171.4s

  [11582/17668] intraday_3914.csv.gz  in=351,767,964 out=103,945,320 elapsed=171.4s

  [11583/17668] intraday_3913.csv.gz  in=351,781,724 out=103,945,320 elapsed=171.4s

  [11584/17668] intraday_3915.csv.gz  in=351,798,421 out=103,945,320 elapsed=171.4s

  [11585/17668] intraday_3917.csv.gz  in=351,810,803 out=103,945,320 elapsed=171.4s

  [11586/17668] intraday_3916.csv.gz  in=351,822,580 out=103,945,320 elapsed=171.4s

  [11587/17668] intraday_3918.csv.gz  in=351,835,874 out=103,945,320 elapsed=171.4s

  [11588/17668] intraday_3919.csv.gz  in=351,847,732 out=103,945,320 elapsed=171.4s

  [11589/17668] intraday_3920.csv.gz  in=351,860,145 out=103,945,320 elapsed=171.5s

  [11590/17668] intraday_3921.csv.gz  in=351,874,894 out=103,945,320 elapsed=171.5s

  [11591/17668] intraday_3922.csv.gz  in=351,888,384 out=103,945,320 elapsed=171.5s

  [11592/17668] intraday_3923.csv.gz  in=351,902,055 out=103,945,320 elapsed=171.5s

  [11593/17668] intraday_3924.csv.gz  in=351,915,274 out=103,945,320 elapsed=171.5s

  [11594/17668] intraday_3925.csv.gz  in=351,927,038 out=103,945,320 elapsed=171.5s

  [11595/17668] intraday_3926.csv.gz  in=351,940,322 out=103,945,320 elapsed=171.5s

  [11596/17668] intraday_3927.csv.gz  in=351,950,900 out=103,945,320 elapsed=171.5s

  [11597/17668] intraday_3928.csv.gz  in=351,964,848 out=103,945,320 elapsed=171.6s

  [11598/17668] intraday_3929.csv.gz  in=351,973,317 out=103,945,320 elapsed=171.6s

  [11599/17668] intraday_3930.csv.gz  in=351,982,797 out=103,945,320 elapsed=171.6s

  [11600/17668] intraday_3931.csv.gz  in=351,993,741 out=103,945,320 elapsed=171.6s

  [11601/17668] intraday_3932.csv.gz  in=352,010,060 out=103,945,320 elapsed=171.6s

  [11602/17668] intraday_3934.csv.gz  in=352,023,031 out=103,945,320 elapsed=171.6s

  [11603/17668] intraday_3933.csv.gz  in=352,037,690 out=103,945,320 elapsed=171.6s

  [11604/17668] intraday_3935.csv.gz  in=352,048,362 out=103,945,320 elapsed=171.6s

  [11605/17668] intraday_3937.csv.gz  in=352,063,185 out=103,945,320 elapsed=171.6s

  [11606/17668] intraday_3938.csv.gz  in=352,075,990 out=103,945,320 elapsed=171.6s

  [11607/17668] intraday_3936.csv.gz  in=352,091,180 out=103,945,320 elapsed=171.6s

  [11608/17668] intraday_3939.csv.gz  in=352,104,127 out=103,945,320 elapsed=171.7s

  [11609/17668] intraday_3940.csv.gz  in=352,119,028 out=103,945,320 elapsed=171.7s

  [11610/17668] intraday_3942.csv.gz  in=352,129,011 out=103,945,320 elapsed=171.7s

  [11611/17668] intraday_3941.csv.gz  in=352,145,020 out=103,945,320 elapsed=171.7s

  [11612/17668] intraday_3943.csv.gz  in=352,158,627 out=103,945,320 elapsed=171.7s

  [11613/17668] intraday_3945.csv.gz  in=352,170,646 out=103,945,320 elapsed=171.7s

  [11614/17668] intraday_3946.csv.gz  in=352,181,793 out=103,945,320 elapsed=171.7s

  [11615/17668] intraday_3944.csv.gz  in=352,195,116 out=103,945,320 elapsed=171.7s

  [11616/17668] intraday_3947.csv.gz  in=352,208,325 out=103,945,320 elapsed=171.7s

  [11617/17668] intraday_3948.csv.gz  in=352,220,582 out=103,945,320 elapsed=171.8s

  [11618/17668] intraday_3949.csv.gz  in=352,234,004 out=103,945,320 elapsed=171.8s

  [11619/17668] intraday_3950.csv.gz  in=352,246,188 out=103,945,320 elapsed=171.8s

  [11620/17668] intraday_3951.csv.gz  in=352,260,524 out=103,945,320 elapsed=171.8s

  [11621/17668] intraday_3952.csv.gz  in=352,274,439 out=103,945,320 elapsed=171.8s

  [11622/17668] intraday_3953.csv.gz  in=352,287,691 out=103,945,320 elapsed=171.8s

  [11623/17668] intraday_3954.csv.gz  in=352,300,283 out=103,945,320 elapsed=171.8s

  [11624/17668] intraday_3956.csv.gz  in=352,312,586 out=103,945,320 elapsed=171.8s

  [11625/17668] intraday_3955.csv.gz  in=352,325,678 out=103,945,320 elapsed=171.8s

  [11626/17668] intraday_3957.csv.gz  in=352,336,295 out=103,945,320 elapsed=171.9s

  [11627/17668] intraday_3958.csv.gz  in=352,349,218 out=103,945,320 elapsed=171.9s

  [11628/17668] intraday_3959.csv.gz  in=352,363,088 out=103,945,320 elapsed=171.9s

  [11629/17668] intraday_3960.csv.gz  in=352,377,676 out=103,945,320 elapsed=171.9s

  [11630/17668] intraday_3962.csv.gz  in=352,391,266 out=103,945,320 elapsed=171.9s

  [11631/17668] intraday_3963.csv.gz  in=352,403,392 out=103,945,320 elapsed=171.9s

  [11632/17668] intraday_3961.csv.gz  in=352,419,107 out=103,945,320 elapsed=171.9s

  [11633/17668] intraday_3964.csv.gz  in=352,432,357 out=103,945,320 elapsed=171.9s

  [11634/17668] intraday_3965.csv.gz  in=352,447,058 out=103,945,320 elapsed=172.0s

  [11635/17668] intraday_3967.csv.gz  in=352,460,397 out=103,945,320 elapsed=172.0s

  [11636/17668] intraday_3966.csv.gz  in=352,472,125 out=103,945,320 elapsed=172.0s

  [11637/17668] intraday_3968.csv.gz  in=352,483,820 out=103,945,320 elapsed=172.0s

  [11638/17668] intraday_3969.csv.gz  in=352,495,020 out=103,945,320 elapsed=172.0s

  [11639/17668] intraday_3972.csv.gz  in=352,507,992 out=103,945,320 elapsed=172.0s

  [11640/17668] intraday_3971.csv.gz  in=352,521,178 out=103,945,320 elapsed=172.0s

  [11641/17668] intraday_3970.csv.gz  in=352,533,021 out=103,945,320 elapsed=172.0s

  [11642/17668] intraday_3973.csv.gz  in=352,546,002 out=103,945,320 elapsed=172.0s

  [11643/17668] intraday_3975.csv.gz  in=352,558,008 out=103,945,320 elapsed=172.1s

  [11644/17668] intraday_3974.csv.gz  in=352,571,799 out=103,945,320 elapsed=172.1s

  [11645/17668] intraday_3976.csv.gz  in=352,584,877 out=103,945,320 elapsed=172.1s

  [11646/17668] intraday_3977.csv.gz  in=352,597,460 out=103,945,320 elapsed=172.1s

  [11647/17668] intraday_3978.csv.gz  in=352,609,137 out=103,945,320 elapsed=172.1s

  [11648/17668] intraday_3980.csv.gz  in=352,621,032 out=103,945,320 elapsed=172.1s

  [11649/17668] intraday_3979.csv.gz  in=352,633,853 out=103,945,320 elapsed=172.1s

  [11650/17668] intraday_3981.csv.gz  in=352,644,508 out=103,945,320 elapsed=172.1s

  [11651/17668] intraday_3982.csv.gz  in=352,658,195 out=103,945,320 elapsed=172.1s

  [11652/17668] intraday_3983.csv.gz  in=352,668,874 out=103,945,320 elapsed=172.1s

  [11653/17668] intraday_3985.csv.gz  in=352,682,991 out=103,945,320 elapsed=172.2s

  [11654/17668] intraday_3986.csv.gz  in=352,695,279 out=103,945,320 elapsed=172.2s

  [11655/17668] intraday_3984.csv.gz  in=352,706,318 out=103,945,320 elapsed=172.2s

  [11656/17668] intraday_3987.csv.gz  in=352,718,589 out=103,945,320 elapsed=172.2s

  [11657/17668] intraday_3988.csv.gz  in=352,729,602 out=103,945,320 elapsed=172.2s

  [11658/17668] intraday_3990.csv.gz  in=352,742,128 out=103,945,320 elapsed=172.2s

  [11659/17668] intraday_3989.csv.gz  in=352,757,297 out=103,945,320 elapsed=172.2s

  [11660/17668] intraday_3991.csv.gz  in=352,769,775 out=103,945,320 elapsed=172.2s

  [11661/17668] intraday_3993.csv.gz  in=352,782,755 out=103,945,320 elapsed=172.2s

  [11662/17668] intraday_3992.csv.gz  in=352,795,721 out=103,945,320 elapsed=172.2s

  [11663/17668] intraday_3994.csv.gz  in=352,807,705 out=103,945,320 elapsed=172.2s

  [11664/17668] intraday_3997.csv.gz  in=352,821,117 out=103,945,320 elapsed=172.3s

  [11665/17668] intraday_3996.csv.gz  in=352,835,413 out=103,945,320 elapsed=172.3s

  [11666/17668] intraday_3998.csv.gz  in=352,848,885 out=103,945,320 elapsed=172.3s

  [11667/17668] intraday_3995.csv.gz  in=352,863,819 out=103,945,320 elapsed=172.3s

  [11668/17668] intraday_3999.csv.gz  in=352,874,556 out=103,945,320 elapsed=172.3s

  [11669/17668] intraday_4001.csv.gz  in=352,885,994 out=103,945,320 elapsed=172.3s

  [11670/17668] intraday_4000.csv.gz  in=352,898,710 out=103,945,320 elapsed=172.3s

  [11671/17668] intraday_4002.csv.gz  in=352,911,516 out=103,945,320 elapsed=172.3s

  [11672/17668] intraday_4003.csv.gz  in=352,925,756 out=103,945,320 elapsed=172.3s

  [11673/17668] intraday_4004.csv.gz  in=352,938,004 out=103,945,320 elapsed=172.3s

  [11674/17668] intraday_4005.csv.gz  in=352,947,865 out=103,945,320 elapsed=172.4s

  [11675/17668] intraday_4006.csv.gz  in=352,960,272 out=103,945,320 elapsed=172.4s

  [11676/17668] intraday_4009.csv.gz  in=352,972,722 out=103,945,320 elapsed=172.4s

  [11677/17668] intraday_4008.csv.gz  in=352,984,758 out=103,945,320 elapsed=172.4s

  [11678/17668] intraday_4010.csv.gz  in=352,996,109 out=103,945,320 elapsed=172.4s

  [11679/17668] intraday_4007.csv.gz  in=353,011,777 out=103,945,320 elapsed=172.4s

  [11680/17668] intraday_4011.csv.gz  in=353,023,772 out=103,945,320 elapsed=172.4s

  [11681/17668] intraday_4014.csv.gz  in=353,035,843 out=103,945,320 elapsed=172.4s

  [11682/17668] intraday_4013.csv.gz  in=353,051,836 out=103,945,320 elapsed=172.4s

  [11683/17668] intraday_4012.csv.gz  in=353,065,851 out=103,945,320 elapsed=172.4s

  [11684/17668] intraday_4015.csv.gz  in=353,077,756 out=103,945,320 elapsed=172.5s

  [11685/17668] intraday_4018.csv.gz  in=353,092,448 out=103,945,320 elapsed=172.5s

  [11686/17668] intraday_4016.csv.gz  in=353,104,170 out=103,945,320 elapsed=172.5s

  [11687/17668] intraday_4017.csv.gz  in=353,118,267 out=103,945,320 elapsed=172.5s

  [11688/17668] intraday_4019.csv.gz  in=353,133,153 out=103,945,320 elapsed=172.5s

  [11689/17668] intraday_4020.csv.gz  in=353,144,143 out=103,945,320 elapsed=172.5s

  [11690/17668] intraday_4021.csv.gz  in=353,158,687 out=103,945,320 elapsed=172.5s

  [11691/17668] intraday_4022.csv.gz  in=353,175,010 out=103,945,320 elapsed=172.5s

  [11692/17668] intraday_4023.csv.gz  in=353,188,836 out=103,945,320 elapsed=172.5s

  [11693/17668] intraday_4024.csv.gz  in=353,203,834 out=103,945,320 elapsed=172.5s

  [11694/17668] intraday_4025.csv.gz  in=353,215,961 out=103,945,320 elapsed=172.6s

  [11695/17668] intraday_4026.csv.gz  in=353,228,298 out=103,945,320 elapsed=172.6s

  [11696/17668] intraday_4027.csv.gz  in=353,241,549 out=103,945,320 elapsed=172.6s

  [11697/17668] intraday_4028.csv.gz  in=353,253,514 out=103,945,320 elapsed=172.6s

  [11698/17668] intraday_4030.csv.gz  in=353,265,121 out=103,945,320 elapsed=172.6s

  [11699/17668] intraday_4031.csv.gz  in=353,279,076 out=103,945,320 elapsed=172.6s

  [11700/17668] intraday_4029.csv.gz  in=353,291,259 out=103,945,320 elapsed=172.6s

  [11701/17668] intraday_4032.csv.gz  in=353,305,234 out=103,945,320 elapsed=172.6s

  [11702/17668] intraday_4036.csv.gz  in=353,318,687 out=103,945,320 elapsed=172.6s

  [11703/17668] intraday_4033.csv.gz  in=353,332,033 out=103,945,320 elapsed=172.6s

  [11704/17668] intraday_4034.csv.gz  in=353,344,971 out=103,945,320 elapsed=172.6s

  [11705/17668] intraday_4035.csv.gz  in=353,358,878 out=103,945,320 elapsed=172.6s

  [11706/17668] intraday_4037.csv.gz  in=353,372,130 out=103,945,320 elapsed=172.7s

  [11707/17668] intraday_4040.csv.gz  in=353,384,063 out=103,945,320 elapsed=172.7s

  [11708/17668] intraday_4039.csv.gz  in=353,398,259 out=103,945,320 elapsed=172.7s

  [11709/17668] intraday_4038.csv.gz  in=353,412,866 out=103,945,320 elapsed=172.7s

  [11710/17668] intraday_4041.csv.gz  in=353,427,211 out=103,945,320 elapsed=172.7s

  [11711/17668] intraday_4043.csv.gz  in=353,441,139 out=103,945,320 elapsed=172.7s

  [11712/17668] intraday_4044.csv.gz  in=353,457,345 out=103,945,320 elapsed=172.7s

  [11713/17668] intraday_4042.csv.gz  in=353,469,692 out=103,945,320 elapsed=172.7s

  [11714/17668] intraday_4045.csv.gz  in=353,484,653 out=103,945,320 elapsed=172.8s

  [11715/17668] intraday_4046.csv.gz  in=353,498,076 out=103,945,320 elapsed=172.8s

  [11716/17668] intraday_4047.csv.gz  in=353,514,125 out=103,945,320 elapsed=172.8s

  [11717/17668] intraday_4048.csv.gz  in=353,526,383 out=103,945,320 elapsed=172.8s

  [11718/17668] intraday_4050.csv.gz  in=353,537,470 out=103,945,320 elapsed=172.8s

  [11719/17668] intraday_4049.csv.gz  in=353,550,440 out=103,945,320 elapsed=172.8s

  [11720/17668] intraday_4051.csv.gz  in=353,564,673 out=103,945,320 elapsed=172.8s

  [11721/17668] intraday_4052.csv.gz  in=353,575,200 out=103,945,320 elapsed=172.8s

  [11722/17668] intraday_4053.csv.gz  in=353,588,757 out=103,945,320 elapsed=172.8s

  [11723/17668] intraday_4055.csv.gz  in=353,605,434 out=103,945,320 elapsed=172.8s

  [11724/17668] intraday_4054.csv.gz  in=353,618,976 out=103,945,320 elapsed=172.8s

  [11725/17668] intraday_4056.csv.gz  in=353,630,510 out=103,945,320 elapsed=172.9s

  [11726/17668] intraday_4059.csv.gz  in=353,642,975 out=103,945,320 elapsed=172.9s

  [11727/17668] intraday_4057.csv.gz  in=353,656,410 out=103,945,320 elapsed=172.9s

  [11728/17668] intraday_4058.csv.gz  in=353,669,802 out=103,945,320 elapsed=172.9s

  [11729/17668] intraday_4060.csv.gz  in=353,684,151 out=103,945,320 elapsed=172.9s

  [11730/17668] intraday_4062.csv.gz  in=353,698,973 out=103,945,320 elapsed=172.9s

  [11731/17668] intraday_4061.csv.gz  in=353,713,838 out=103,945,320 elapsed=172.9s

  [11732/17668] intraday_4063.csv.gz  in=353,726,930 out=103,945,320 elapsed=172.9s

  [11733/17668] intraday_4065.csv.gz  in=353,738,452 out=103,945,320 elapsed=172.9s

  [11734/17668] intraday_4064.csv.gz  in=353,752,067 out=103,945,320 elapsed=172.9s

  [11735/17668] intraday_4067.csv.gz  in=353,764,829 out=103,945,320 elapsed=172.9s

  [11736/17668] intraday_4066.csv.gz  in=353,777,220 out=103,945,320 elapsed=173.0s

  [11737/17668] intraday_4068.csv.gz  in=353,791,914 out=103,945,320 elapsed=173.0s

  [11738/17668] intraday_4071.csv.gz  in=353,803,783 out=103,945,320 elapsed=173.0s

  [11739/17668] intraday_4070.csv.gz  in=353,812,543 out=103,945,320 elapsed=173.0s

  [11740/17668] intraday_4069.csv.gz  in=353,822,215 out=103,945,320 elapsed=173.0s

  [11741/17668] intraday_4072.csv.gz  in=353,822,288 out=103,945,320 elapsed=173.0s

  [11742/17668] intraday_4074.csv.gz  in=353,822,326 out=103,945,320 elapsed=173.0s

  [11743/17668] intraday_4073.csv.gz  in=353,823,371 out=103,945,320 elapsed=173.0s

  [11744/17668] intraday_4075.csv.gz  in=353,823,499 out=103,945,320 elapsed=173.0s

  [11745/17668] intraday_4077.csv.gz  in=353,824,108 out=103,945,320 elapsed=173.0s

  [11746/17668] intraday_4076.csv.gz  in=353,824,139 out=103,945,320 elapsed=173.0s

  [11747/17668] intraday_4080.csv.gz  in=353,824,168 out=103,945,320 elapsed=173.0s

  [11748/17668] intraday_4078.csv.gz  in=353,824,320 out=103,945,320 elapsed=173.0s

  [11749/17668] intraday_4079.csv.gz  in=353,824,399 out=103,945,320 elapsed=173.0s

  [11750/17668] intraday_4081.csv.gz  in=353,825,427 out=103,945,320 elapsed=173.1s

  [11751/17668] intraday_4082.csv.gz  in=353,825,439 out=103,945,320 elapsed=173.1s

  [11752/17668] intraday_4083.csv.gz  in=353,825,447 out=103,945,320 elapsed=173.1s

  [11753/17668] intraday_4084.csv.gz  in=353,826,172 out=103,945,320 elapsed=173.1s

  [11754/17668] intraday_4086.csv.gz  in=353,826,205 out=103,945,320 elapsed=173.1s

  [11755/17668] intraday_4085.csv.gz  in=353,826,308 out=103,945,320 elapsed=173.1s

  [11756/17668] intraday_4087.csv.gz  in=353,826,869 out=103,945,320 elapsed=173.1s

  [11757/17668] intraday_4088.csv.gz  in=353,831,197 out=103,945,320 elapsed=173.1s

  [11758/17668] intraday_4090.csv.gz  in=353,831,344 out=103,945,320 elapsed=173.1s

  [11759/17668] intraday_4089.csv.gz  in=353,840,224 out=103,945,320 elapsed=173.1s

  [11760/17668] intraday_4091.csv.gz  in=353,840,753 out=103,945,320 elapsed=173.1s

  [11761/17668] intraday_4092.csv.gz  in=353,840,830 out=103,945,320 elapsed=173.1s

  [11762/17668] intraday_4093.csv.gz  in=353,840,894 out=103,945,320 elapsed=173.1s

  [11763/17668] intraday_4094.csv.gz  in=353,842,092 out=103,945,320 elapsed=173.1s

  [11764/17668] intraday_4096.csv.gz  in=353,842,165 out=103,945,320 elapsed=173.1s

  [11765/17668] intraday_4095.csv.gz  in=353,842,278 out=103,945,320 elapsed=173.2s

  [11766/17668] intraday_4098.csv.gz  in=353,842,297 out=103,945,320 elapsed=173.2s

  [11767/17668] intraday_4097.csv.gz  in=353,848,743 out=103,945,320 elapsed=173.2s

  [11768/17668] intraday_4099.csv.gz  in=353,849,694 out=103,945,320 elapsed=173.2s

  [11769/17668] intraday_4100.csv.gz  in=353,856,128 out=103,945,320 elapsed=173.2s

  [11770/17668] intraday_4104.csv.gz  in=353,856,160 out=103,945,320 elapsed=173.2s

  [11771/17668] intraday_4101.csv.gz  in=353,856,316 out=103,945,320 elapsed=173.2s

  [11772/17668] intraday_4103.csv.gz  in=353,858,801 out=103,945,320 elapsed=173.2s

  [11773/17668] intraday_4102.csv.gz  in=353,859,597 out=103,945,320 elapsed=173.2s

  [11774/17668] intraday_4105.csv.gz  in=353,859,711 out=103,945,320 elapsed=173.2s

  [11775/17668] intraday_4106.csv.gz  in=353,859,750 out=103,945,320 elapsed=173.2s

  [11776/17668] intraday_4107.csv.gz  in=353,867,520 out=103,945,320 elapsed=173.2s

  [11777/17668] intraday_4109.csv.gz  in=353,867,656 out=103,945,320 elapsed=173.2s

  [11778/17668] intraday_4110.csv.gz  in=353,867,792 out=103,945,320 elapsed=173.2s

  [11779/17668] intraday_4108.csv.gz  in=353,868,205 out=103,945,320 elapsed=173.2s

  [11780/17668] intraday_4112.csv.gz  in=353,868,468 out=103,945,320 elapsed=173.2s

  [11781/17668] intraday_4113.csv.gz  in=353,868,607 out=103,945,320 elapsed=173.2s

  [11782/17668] intraday_4111.csv.gz  in=353,868,702 out=103,945,320 elapsed=173.3s

  [11783/17668] intraday_4114.csv.gz  in=353,868,770 out=103,945,320 elapsed=173.3s

  [11784/17668] intraday_4116.csv.gz  in=353,883,661 out=103,945,320 elapsed=173.3s

  [11785/17668] intraday_4115.csv.gz  in=353,899,231 out=103,945,320 elapsed=173.3s

  [11786/17668] intraday_4117.csv.gz  in=353,912,204 out=103,945,320 elapsed=173.3s

  [11787/17668] intraday_4118.csv.gz  in=353,922,472 out=103,945,320 elapsed=173.3s

  [11788/17668] intraday_4120.csv.gz  in=353,936,922 out=103,945,320 elapsed=173.3s

  [11789/17668] intraday_4119.csv.gz  in=353,951,530 out=103,945,320 elapsed=173.3s

  [11790/17668] intraday_4121.csv.gz  in=353,963,703 out=103,945,320 elapsed=173.4s

  [11791/17668] intraday_4122.csv.gz  in=353,975,591 out=103,945,320 elapsed=173.4s

  [11792/17668] intraday_4123.csv.gz  in=353,989,884 out=103,945,320 elapsed=173.4s

  [11793/17668] intraday_4125.csv.gz  in=354,000,555 out=103,945,320 elapsed=173.4s

  [11794/17668] intraday_4126.csv.gz  in=354,014,572 out=103,945,320 elapsed=173.4s

  [11795/17668] intraday_4124.csv.gz  in=354,030,080 out=103,945,320 elapsed=173.4s

  [11796/17668] intraday_4127.csv.gz  in=354,041,621 out=103,945,320 elapsed=173.4s

  [11797/17668] intraday_4128.csv.gz  in=354,053,163 out=103,945,320 elapsed=173.4s

  [11798/17668] intraday_4130.csv.gz  in=354,064,530 out=103,945,320 elapsed=173.4s

  [11799/17668] intraday_4129.csv.gz  in=354,075,519 out=103,945,320 elapsed=173.4s

  [11800/17668] intraday_4132.csv.gz  in=354,089,487 out=103,945,320 elapsed=173.5s

  [11801/17668] intraday_4131.csv.gz  in=354,103,263 out=103,945,320 elapsed=173.5s

  [11802/17668] intraday_4134.csv.gz  in=354,115,986 out=103,945,320 elapsed=173.5s

  [11803/17668] intraday_4133.csv.gz  in=354,126,693 out=103,945,320 elapsed=173.5s

  [11804/17668] intraday_4135.csv.gz  in=354,140,854 out=103,945,320 elapsed=173.5s

  [11805/17668] intraday_4137.csv.gz  in=354,152,490 out=103,945,320 elapsed=173.5s

  [11806/17668] intraday_4136.csv.gz  in=354,164,907 out=103,945,320 elapsed=173.5s

  [11807/17668] intraday_4138.csv.gz  in=354,177,250 out=103,945,320 elapsed=173.5s

  [11808/17668] intraday_4140.csv.gz  in=354,187,054 out=103,945,320 elapsed=173.5s

  [11809/17668] intraday_4141.csv.gz  in=354,200,148 out=103,945,320 elapsed=173.5s

  [11810/17668] intraday_4139.csv.gz  in=354,211,698 out=103,945,320 elapsed=173.5s

  [11811/17668] intraday_4143.csv.gz  in=354,223,958 out=103,945,320 elapsed=173.5s

  [11812/17668] intraday_4142.csv.gz  in=354,236,606 out=103,945,320 elapsed=173.6s

  [11813/17668] intraday_4144.csv.gz  in=354,252,096 out=103,945,320 elapsed=173.6s

  [11814/17668] intraday_4145.csv.gz  in=354,266,708 out=103,945,320 elapsed=173.6s

  [11815/17668] intraday_4146.csv.gz  in=354,278,795 out=103,945,320 elapsed=173.6s

  [11816/17668] intraday_4147.csv.gz  in=354,290,742 out=103,945,320 elapsed=173.6s

  [11817/17668] intraday_4149.csv.gz  in=354,302,700 out=103,945,320 elapsed=173.6s

  [11818/17668] intraday_4148.csv.gz  in=354,315,867 out=103,945,320 elapsed=173.6s

  [11819/17668] intraday_4150.csv.gz  in=354,328,853 out=103,945,320 elapsed=173.6s

  [11820/17668] intraday_4151.csv.gz  in=354,339,025 out=103,945,320 elapsed=173.6s

  [11821/17668] intraday_4152.csv.gz  in=354,350,089 out=103,945,320 elapsed=173.7s

  [11822/17668] intraday_4154.csv.gz  in=354,359,823 out=103,945,320 elapsed=173.7s

  [11823/17668] intraday_4153.csv.gz  in=354,372,107 out=103,945,320 elapsed=173.7s

  [11824/17668] intraday_4155.csv.gz  in=354,386,604 out=103,945,320 elapsed=173.7s

  [11825/17668] intraday_4156.csv.gz  in=354,399,477 out=103,945,320 elapsed=173.7s

  [11826/17668] intraday_4157.csv.gz  in=354,411,584 out=103,945,320 elapsed=173.7s

  [11827/17668] intraday_4158.csv.gz  in=354,422,819 out=103,945,320 elapsed=173.7s

  [11828/17668] intraday_4159.csv.gz  in=354,434,412 out=103,945,320 elapsed=173.7s

  [11829/17668] intraday_4160.csv.gz  in=354,447,290 out=103,945,320 elapsed=173.7s

  [11830/17668] intraday_4162.csv.gz  in=354,459,252 out=103,945,320 elapsed=173.7s

  [11831/17668] intraday_4163.csv.gz  in=354,470,625 out=103,945,320 elapsed=173.8s

  [11832/17668] intraday_4161.csv.gz  in=354,481,470 out=103,945,320 elapsed=173.8s

  [11833/17668] intraday_4165.csv.gz  in=354,492,705 out=103,945,320 elapsed=173.8s

  [11834/17668] intraday_4164.csv.gz  in=354,503,431 out=103,945,320 elapsed=173.8s

  [11835/17668] intraday_4167.csv.gz  in=354,514,702 out=103,945,320 elapsed=173.8s

  [11836/17668] intraday_4166.csv.gz  in=354,526,071 out=103,945,320 elapsed=173.8s

  [11837/17668] intraday_4168.csv.gz  in=354,539,407 out=103,945,320 elapsed=173.8s

  [11838/17668] intraday_4169.csv.gz  in=354,551,715 out=103,945,320 elapsed=173.8s

  [11839/17668] intraday_4170.csv.gz  in=354,562,287 out=103,945,320 elapsed=173.8s

  [11840/17668] intraday_4171.csv.gz  in=354,572,804 out=103,945,320 elapsed=173.8s

  [11841/17668] intraday_4172.csv.gz  in=354,586,265 out=103,945,320 elapsed=173.9s

  [11842/17668] intraday_4174.csv.gz  in=354,597,579 out=103,945,320 elapsed=173.9s

  [11843/17668] intraday_4173.csv.gz  in=354,609,787 out=103,945,320 elapsed=173.9s

  [11844/17668] intraday_4175.csv.gz  in=354,621,206 out=103,945,320 elapsed=173.9s

  [11845/17668] intraday_4176.csv.gz  in=354,632,620 out=103,945,320 elapsed=173.9s

  [11846/17668] intraday_4177.csv.gz  in=354,644,368 out=103,945,320 elapsed=173.9s

  [11847/17668] intraday_4178.csv.gz  in=354,659,755 out=103,945,320 elapsed=173.9s

  [11848/17668] intraday_4179.csv.gz  in=354,672,815 out=103,945,320 elapsed=173.9s

  [11849/17668] intraday_4180.csv.gz  in=354,684,781 out=103,945,320 elapsed=173.9s

  [11850/17668] intraday_4182.csv.gz  in=354,697,088 out=103,945,320 elapsed=173.9s

  [11851/17668] intraday_4181.csv.gz  in=354,708,594 out=103,945,320 elapsed=173.9s

  [11852/17668] intraday_4183.csv.gz  in=354,718,592 out=103,945,320 elapsed=173.9s

  [11853/17668] intraday_4184.csv.gz  in=354,730,682 out=103,945,320 elapsed=174.0s

  [11854/17668] intraday_4187.csv.gz  in=354,740,466 out=103,945,320 elapsed=174.0s

  [11855/17668] intraday_4185.csv.gz  in=354,751,940 out=103,945,320 elapsed=174.0s

  [11856/17668] intraday_4186.csv.gz  in=354,765,496 out=103,945,320 elapsed=174.0s

  [11857/17668] intraday_4190.csv.gz  in=354,779,785 out=103,945,320 elapsed=174.0s

  [11858/17668] intraday_4189.csv.gz  in=354,789,992 out=103,945,320 elapsed=174.0s

  [11859/17668] intraday_4188.csv.gz  in=354,800,825 out=103,945,320 elapsed=174.0s

  [11860/17668] intraday_4194.csv.gz  in=354,811,587 out=103,945,320 elapsed=174.0s

  [11861/17668] intraday_4193.csv.gz  in=354,821,909 out=103,945,320 elapsed=174.1s

  [11862/17668] intraday_4191.csv.gz  in=354,833,715 out=103,945,320 elapsed=174.1s

  [11863/17668] intraday_4192.csv.gz  in=354,846,931 out=103,945,320 elapsed=174.1s

  [11864/17668] intraday_4195.csv.gz  in=354,858,803 out=103,945,320 elapsed=174.1s

  [11865/17668] intraday_4197.csv.gz  in=354,870,324 out=103,945,320 elapsed=174.1s

  [11866/17668] intraday_4198.csv.gz  in=354,881,695 out=103,945,320 elapsed=174.1s

  [11867/17668] intraday_4196.csv.gz  in=354,898,102 out=103,945,320 elapsed=174.1s

  [11868/17668] intraday_4200.csv.gz  in=354,908,781 out=103,945,320 elapsed=174.1s

  [11869/17668] intraday_4199.csv.gz  in=354,920,407 out=103,945,320 elapsed=174.1s

  [11870/17668] intraday_4202.csv.gz  in=354,935,454 out=103,945,320 elapsed=174.1s

  [11871/17668] intraday_4201.csv.gz  in=354,948,805 out=103,945,320 elapsed=174.1s

  [11872/17668] intraday_4205.csv.gz  in=354,961,969 out=103,945,320 elapsed=174.2s

  [11873/17668] intraday_4204.csv.gz  in=354,975,346 out=103,945,320 elapsed=174.2s

  [11874/17668] intraday_4203.csv.gz  in=354,987,186 out=103,945,320 elapsed=174.2s

  [11875/17668] intraday_4206.csv.gz  in=355,000,605 out=103,945,320 elapsed=174.2s

  [11876/17668] intraday_4209.csv.gz  in=355,012,438 out=103,945,320 elapsed=174.2s

  [11877/17668] intraday_4207.csv.gz  in=355,034,901 out=103,945,320 elapsed=174.2s

  [11878/17668] intraday_4208.csv.gz  in=355,047,953 out=103,945,320 elapsed=174.2s

  [11879/17668] intraday_4210.csv.gz  in=355,058,894 out=103,945,320 elapsed=174.2s

  [11880/17668] intraday_4211.csv.gz  in=355,070,821 out=103,945,320 elapsed=174.2s

  [11881/17668] intraday_4213.csv.gz  in=355,082,775 out=103,945,320 elapsed=174.3s

  [11882/17668] intraday_4214.csv.gz  in=355,094,407 out=103,945,320 elapsed=174.3s

  [11883/17668] intraday_4212.csv.gz  in=355,106,175 out=103,945,320 elapsed=174.3s

  [11884/17668] intraday_4215.csv.gz  in=355,119,461 out=103,945,320 elapsed=174.3s

  [11885/17668] intraday_4218.csv.gz  in=355,134,863 out=103,945,320 elapsed=174.3s

  [11886/17668] intraday_4216.csv.gz  in=355,146,844 out=103,945,320 elapsed=174.3s

  [11887/17668] intraday_4217.csv.gz  in=355,159,330 out=103,945,320 elapsed=174.3s

  [11888/17668] intraday_4220.csv.gz  in=355,170,188 out=103,945,320 elapsed=174.3s

  [11889/17668] intraday_4219.csv.gz  in=355,181,267 out=103,945,320 elapsed=174.3s

  [11890/17668] intraday_4222.csv.gz  in=355,195,985 out=103,945,320 elapsed=174.3s

  [11891/17668] intraday_4221.csv.gz  in=355,210,460 out=103,945,320 elapsed=174.4s

  [11892/17668] intraday_4224.csv.gz  in=355,223,444 out=103,945,320 elapsed=174.4s

  [11893/17668] intraday_4223.csv.gz  in=355,235,165 out=103,945,320 elapsed=174.4s

  [11894/17668] intraday_4225.csv.gz  in=355,248,553 out=103,945,320 elapsed=174.4s

  [11895/17668] intraday_4226.csv.gz  in=355,260,521 out=103,945,320 elapsed=174.4s

  [11896/17668] intraday_4227.csv.gz  in=355,276,034 out=103,945,320 elapsed=174.4s

  [11897/17668] intraday_4229.csv.gz  in=355,289,430 out=103,945,320 elapsed=174.4s

  [11898/17668] intraday_4228.csv.gz  in=355,302,821 out=103,945,320 elapsed=174.4s

  [11899/17668] intraday_4231.csv.gz  in=355,315,502 out=103,945,320 elapsed=174.5s

  [11900/17668] intraday_4230.csv.gz  in=355,331,885 out=103,945,320 elapsed=174.5s

  [11901/17668] intraday_4232.csv.gz  in=355,344,029 out=103,945,320 elapsed=174.5s

  [11902/17668] intraday_4233.csv.gz  in=355,355,020 out=103,945,320 elapsed=174.5s

  [11903/17668] intraday_4235.csv.gz  in=355,366,542 out=103,945,320 elapsed=174.5s

  [11904/17668] intraday_4236.csv.gz  in=355,379,558 out=103,945,320 elapsed=174.5s

  [11905/17668] intraday_4234.csv.gz  in=355,390,930 out=103,945,320 elapsed=174.5s

  [11906/17668] intraday_4237.csv.gz  in=355,403,220 out=103,945,320 elapsed=174.5s

  [11907/17668] intraday_4239.csv.gz  in=355,416,017 out=103,945,320 elapsed=174.5s

  [11908/17668] intraday_4241.csv.gz  in=355,428,507 out=103,945,320 elapsed=174.5s

  [11909/17668] intraday_4240.csv.gz  in=355,441,949 out=103,945,320 elapsed=174.5s

  [11910/17668] intraday_4238.csv.gz  in=355,457,498 out=103,945,320 elapsed=174.5s

  [11911/17668] intraday_4242.csv.gz  in=355,470,974 out=103,945,320 elapsed=174.6s

  [11912/17668] intraday_4243.csv.gz  in=355,482,876 out=103,945,320 elapsed=174.6s

  [11913/17668] intraday_4244.csv.gz  in=355,495,476 out=103,945,320 elapsed=174.6s

  [11914/17668] intraday_4245.csv.gz  in=355,509,850 out=103,945,320 elapsed=174.6s

  [11915/17668] intraday_4246.csv.gz  in=355,523,964 out=103,945,320 elapsed=174.6s

  [11916/17668] intraday_4247.csv.gz  in=355,537,093 out=103,945,320 elapsed=174.6s

  [11917/17668] intraday_4248.csv.gz  in=355,548,994 out=103,945,320 elapsed=174.6s

  [11918/17668] intraday_4249.csv.gz  in=355,559,300 out=103,945,320 elapsed=174.6s

  [11919/17668] intraday_4250.csv.gz  in=355,572,222 out=103,945,320 elapsed=174.6s

  [11920/17668] intraday_4251.csv.gz  in=355,583,629 out=103,945,320 elapsed=174.6s

  [11921/17668] intraday_4253.csv.gz  in=355,591,216 out=103,945,320 elapsed=174.6s

  [11922/17668] intraday_4252.csv.gz  in=355,603,683 out=103,945,320 elapsed=174.6s

  [11923/17668] intraday_4254.csv.gz  in=355,613,988 out=103,945,320 elapsed=174.7s

  [11924/17668] intraday_4255.csv.gz  in=355,621,247 out=103,945,320 elapsed=174.7s

  [11925/17668] intraday_4257.csv.gz  in=355,635,266 out=103,945,320 elapsed=174.7s

  [11926/17668] intraday_4256.csv.gz  in=355,651,049 out=103,945,320 elapsed=174.7s

  [11927/17668] intraday_4259.csv.gz  in=355,661,197 out=103,945,320 elapsed=174.7s

  [11928/17668] intraday_4258.csv.gz  in=355,673,660 out=103,945,320 elapsed=174.7s

  [11929/17668] intraday_4260.csv.gz  in=355,688,586 out=103,945,320 elapsed=174.7s

  [11930/17668] intraday_4262.csv.gz  in=355,701,106 out=103,945,320 elapsed=174.7s

  [11931/17668] intraday_4263.csv.gz  in=355,713,316 out=103,945,320 elapsed=174.7s

  [11932/17668] intraday_4261.csv.gz  in=355,727,715 out=103,945,320 elapsed=174.8s

  [11933/17668] intraday_4264.csv.gz  in=355,742,200 out=103,945,320 elapsed=174.8s

  [11934/17668] intraday_4266.csv.gz  in=355,753,388 out=103,945,320 elapsed=174.8s

  [11935/17668] intraday_4265.csv.gz  in=355,769,078 out=103,945,320 elapsed=174.8s

  [11936/17668] intraday_4267.csv.gz  in=355,782,155 out=103,945,320 elapsed=174.8s

  [11937/17668] intraday_4268.csv.gz  in=355,794,516 out=103,945,320 elapsed=174.8s

  [11938/17668] intraday_4269.csv.gz  in=355,806,528 out=103,945,320 elapsed=174.8s

  [11939/17668] intraday_4271.csv.gz  in=355,818,024 out=103,945,320 elapsed=174.8s

  [11940/17668] intraday_4270.csv.gz  in=355,829,286 out=103,945,320 elapsed=174.8s

  [11941/17668] intraday_4272.csv.gz  in=355,843,675 out=103,945,320 elapsed=174.8s

  [11942/17668] intraday_4273.csv.gz  in=355,856,860 out=103,945,320 elapsed=174.8s

  [11943/17668] intraday_4276.csv.gz  in=355,870,974 out=103,945,320 elapsed=174.9s

  [11944/17668] intraday_4274.csv.gz  in=355,881,310 out=103,945,320 elapsed=174.9s

  [11945/17668] intraday_4275.csv.gz  in=355,894,063 out=103,945,320 elapsed=174.9s

  [11946/17668] intraday_4277.csv.gz  in=355,906,980 out=103,945,320 elapsed=174.9s

  [11947/17668] intraday_4279.csv.gz  in=355,919,663 out=103,945,320 elapsed=174.9s

  [11948/17668] intraday_4280.csv.gz  in=355,932,039 out=103,945,320 elapsed=174.9s

  [11949/17668] intraday_4278.csv.gz  in=355,944,198 out=103,945,320 elapsed=174.9s

  [11950/17668] intraday_4281.csv.gz  in=355,955,379 out=103,945,320 elapsed=174.9s

  [11951/17668] intraday_4282.csv.gz  in=355,968,889 out=103,945,320 elapsed=174.9s

  [11952/17668] intraday_4283.csv.gz  in=355,981,979 out=103,945,320 elapsed=174.9s

  [11953/17668] intraday_4284.csv.gz  in=355,995,957 out=103,945,320 elapsed=174.9s

  [11954/17668] intraday_4285.csv.gz  in=356,010,347 out=103,945,320 elapsed=174.9s

  [11955/17668] intraday_4287.csv.gz  in=356,021,434 out=103,945,320 elapsed=174.9s

  [11956/17668] intraday_4288.csv.gz  in=356,033,681 out=103,945,320 elapsed=175.0s

  [11957/17668] intraday_4286.csv.gz  in=356,047,565 out=103,945,320 elapsed=175.0s

  [11958/17668] intraday_4289.csv.gz  in=356,060,781 out=103,945,320 elapsed=175.0s

  [11959/17668] intraday_4293.csv.gz  in=356,074,039 out=103,945,320 elapsed=175.0s

  [11960/17668] intraday_4290.csv.gz  in=356,085,901 out=103,945,320 elapsed=175.0s

  [11961/17668] intraday_4291.csv.gz  in=356,098,027 out=103,945,320 elapsed=175.0s

  [11962/17668] intraday_4292.csv.gz  in=356,109,657 out=103,945,320 elapsed=175.0s

  [11963/17668] intraday_4294.csv.gz  in=356,121,268 out=103,945,320 elapsed=175.0s

  [11964/17668] intraday_4297.csv.gz  in=356,132,436 out=103,945,320 elapsed=175.0s

  [11965/17668] intraday_4296.csv.gz  in=356,146,033 out=103,945,320 elapsed=175.0s

  [11966/17668] intraday_4295.csv.gz  in=356,157,548 out=103,945,320 elapsed=175.0s

  [11967/17668] intraday_4298.csv.gz  in=356,171,096 out=103,945,320 elapsed=175.1s

  [11968/17668] intraday_4299.csv.gz  in=356,182,405 out=103,945,320 elapsed=175.1s

  [11969/17668] intraday_4300.csv.gz  in=356,195,107 out=103,945,320 elapsed=175.1s

  [11970/17668] intraday_4301.csv.gz  in=356,207,714 out=103,945,320 elapsed=175.1s

  [11971/17668] intraday_4302.csv.gz  in=356,218,916 out=103,945,320 elapsed=175.1s

  [11972/17668] intraday_4305.csv.gz  in=356,228,444 out=103,945,320 elapsed=175.1s

  [11973/17668] intraday_4303.csv.gz  in=356,240,941 out=103,945,320 elapsed=175.1s

  [11974/17668] intraday_4304.csv.gz  in=356,252,211 out=103,945,320 elapsed=175.1s

  [11975/17668] intraday_4306.csv.gz  in=356,265,896 out=103,945,320 elapsed=175.1s

  [11976/17668] intraday_4307.csv.gz  in=356,277,140 out=103,945,320 elapsed=175.2s

  [11977/17668] intraday_4308.csv.gz  in=356,288,456 out=103,945,320 elapsed=175.2s

  [11978/17668] intraday_4309.csv.gz  in=356,301,465 out=103,945,320 elapsed=175.2s

  [11979/17668] intraday_4310.csv.gz  in=356,313,903 out=103,945,320 elapsed=175.2s

  [11980/17668] intraday_4311.csv.gz  in=356,324,817 out=103,945,320 elapsed=175.2s

  [11981/17668] intraday_4312.csv.gz  in=356,335,526 out=103,945,320 elapsed=175.2s

  [11982/17668] intraday_4313.csv.gz  in=356,349,834 out=103,945,320 elapsed=175.2s

  [11983/17668] intraday_4314.csv.gz  in=356,362,182 out=103,945,320 elapsed=175.2s

  [11984/17668] intraday_4318.csv.gz  in=356,373,380 out=103,945,320 elapsed=175.2s

  [11985/17668] intraday_4317.csv.gz  in=356,385,272 out=103,945,320 elapsed=175.2s

  [11986/17668] intraday_4316.csv.gz  in=356,396,208 out=103,945,320 elapsed=175.2s

  [11987/17668] intraday_4315.csv.gz  in=356,408,474 out=103,945,320 elapsed=175.2s

  [11988/17668] intraday_4320.csv.gz  in=356,421,087 out=103,945,320 elapsed=175.3s

  [11989/17668] intraday_4322.csv.gz  in=356,433,507 out=103,945,320 elapsed=175.3s

  [11990/17668] intraday_4321.csv.gz  in=356,446,687 out=103,945,320 elapsed=175.3s

  [11991/17668] intraday_4319.csv.gz  in=356,461,187 out=103,945,320 elapsed=175.3s

  [11992/17668] intraday_4323.csv.gz  in=356,477,865 out=103,945,320 elapsed=175.3s

  [11993/17668] intraday_4325.csv.gz  in=356,489,384 out=103,945,320 elapsed=175.3s

  [11994/17668] intraday_4324.csv.gz  in=356,500,519 out=103,945,320 elapsed=175.3s

  [11995/17668] intraday_4326.csv.gz  in=356,511,353 out=103,945,320 elapsed=175.3s

  [11996/17668] intraday_4329.csv.gz  in=356,521,843 out=103,945,320 elapsed=175.3s

  [11997/17668] intraday_4328.csv.gz  in=356,532,737 out=103,945,320 elapsed=175.4s

  [11998/17668] intraday_4327.csv.gz  in=356,546,409 out=103,945,320 elapsed=175.4s

  [11999/17668] intraday_4330.csv.gz  in=356,558,708 out=103,945,320 elapsed=175.4s

  [12000/17668] intraday_4333.csv.gz  in=356,570,621 out=103,945,320 elapsed=175.4s

  [12001/17668] intraday_4331.csv.gz  in=356,584,585 out=103,945,320 elapsed=175.4s

  [12002/17668] intraday_4332.csv.gz  in=356,595,646 out=103,945,320 elapsed=175.4s

  [12003/17668] intraday_4334.csv.gz  in=356,606,117 out=103,945,320 elapsed=175.4s

  [12004/17668] intraday_4336.csv.gz  in=356,619,174 out=103,945,320 elapsed=175.4s

  [12005/17668] intraday_4338.csv.gz  in=356,630,482 out=103,945,320 elapsed=175.4s

  [12006/17668] intraday_4337.csv.gz  in=356,645,589 out=103,945,320 elapsed=175.4s

  [12007/17668] intraday_4335.csv.gz  in=356,657,727 out=103,945,320 elapsed=175.4s

  [12008/17668] intraday_4339.csv.gz  in=356,668,614 out=103,945,320 elapsed=175.5s

  [12009/17668] intraday_4342.csv.gz  in=356,681,654 out=103,945,320 elapsed=175.5s

  [12010/17668] intraday_4341.csv.gz  in=356,694,792 out=103,945,320 elapsed=175.5s

  [12011/17668] intraday_4340.csv.gz  in=356,705,534 out=103,945,320 elapsed=175.5s

  [12012/17668] intraday_4343.csv.gz  in=356,720,590 out=103,945,320 elapsed=175.5s

  [12013/17668] intraday_4344.csv.gz  in=356,731,559 out=103,945,320 elapsed=175.5s

  [12014/17668] intraday_4346.csv.gz  in=356,745,236 out=103,945,320 elapsed=175.5s

  [12015/17668] intraday_4345.csv.gz  in=356,759,334 out=103,945,320 elapsed=175.5s

  [12016/17668] intraday_4347.csv.gz  in=356,773,915 out=103,945,320 elapsed=175.5s

  [12017/17668] intraday_4348.csv.gz  in=356,789,059 out=103,945,320 elapsed=175.6s

  [12018/17668] intraday_4350.csv.gz  in=356,800,581 out=103,945,320 elapsed=175.6s

  [12019/17668] intraday_4349.csv.gz  in=356,813,316 out=103,945,320 elapsed=175.6s

  [12020/17668] intraday_4351.csv.gz  in=356,825,875 out=103,945,320 elapsed=175.6s

  [12021/17668] intraday_4354.csv.gz  in=356,837,614 out=103,945,320 elapsed=175.6s

  [12022/17668] intraday_4353.csv.gz  in=356,848,655 out=103,945,320 elapsed=175.6s

  [12023/17668] intraday_4352.csv.gz  in=356,859,469 out=103,945,320 elapsed=175.6s

  [12024/17668] intraday_4355.csv.gz  in=356,872,530 out=103,945,320 elapsed=175.6s

  [12025/17668] intraday_4356.csv.gz  in=356,885,321 out=103,945,320 elapsed=175.6s

  [12026/17668] intraday_4357.csv.gz  in=356,897,394 out=103,945,320 elapsed=175.6s

  [12027/17668] intraday_4358.csv.gz  in=356,910,082 out=103,945,320 elapsed=175.6s

  [12028/17668] intraday_4359.csv.gz  in=356,923,426 out=103,945,320 elapsed=175.6s

  [12029/17668] intraday_4360.csv.gz  in=356,936,091 out=103,945,320 elapsed=175.7s

  [12030/17668] intraday_4361.csv.gz  in=356,948,997 out=103,945,320 elapsed=175.7s

  [12031/17668] intraday_4362.csv.gz  in=356,961,870 out=103,945,320 elapsed=175.7s

  [12032/17668] intraday_4363.csv.gz  in=356,975,828 out=103,945,320 elapsed=175.7s

  [12033/17668] intraday_4364.csv.gz  in=356,987,398 out=103,945,320 elapsed=175.7s

  [12034/17668] intraday_4366.csv.gz  in=356,999,834 out=103,945,320 elapsed=175.7s

  [12035/17668] intraday_4365.csv.gz  in=357,015,073 out=103,945,320 elapsed=175.7s

  [12036/17668] intraday_4367.csv.gz  in=357,028,618 out=103,945,320 elapsed=175.7s

  [12037/17668] intraday_4368.csv.gz  in=357,042,245 out=103,945,320 elapsed=175.7s

  [12038/17668] intraday_4369.csv.gz  in=357,056,503 out=103,945,320 elapsed=175.7s

  [12039/17668] intraday_4370.csv.gz  in=357,070,499 out=103,945,320 elapsed=175.7s

  [12040/17668] intraday_4372.csv.gz  in=357,090,950 out=103,945,320 elapsed=175.8s

  [12041/17668] intraday_4371.csv.gz  in=357,106,449 out=103,945,320 elapsed=175.8s

  [12042/17668] intraday_4373.csv.gz  in=357,118,245 out=103,945,320 elapsed=175.8s

  [12043/17668] intraday_4375.csv.gz  in=357,132,104 out=103,945,320 elapsed=175.8s

  [12044/17668] intraday_4374.csv.gz  in=357,142,654 out=103,945,320 elapsed=175.8s

  [12045/17668] intraday_4376.csv.gz  in=357,152,285 out=103,945,320 elapsed=175.8s

  [12046/17668] intraday_4377.csv.gz  in=357,165,626 out=103,945,320 elapsed=175.8s

  [12047/17668] intraday_4380.csv.gz  in=357,177,680 out=103,945,320 elapsed=175.8s

  [12048/17668] intraday_4381.csv.gz  in=357,190,531 out=103,945,320 elapsed=175.8s

  [12049/17668] intraday_4378.csv.gz  in=357,203,433 out=103,945,320 elapsed=175.9s

  [12050/17668] intraday_4379.csv.gz  in=357,218,221 out=103,945,320 elapsed=175.9s

  [12051/17668] intraday_4382.csv.gz  in=357,231,533 out=103,945,320 elapsed=175.9s

  [12052/17668] intraday_4383.csv.gz  in=357,244,744 out=103,945,320 elapsed=175.9s

  [12053/17668] intraday_4384.csv.gz  in=357,256,626 out=103,945,320 elapsed=175.9s

  [12054/17668] intraday_4385.csv.gz  in=357,271,048 out=103,945,320 elapsed=175.9s

  [12055/17668] intraday_4388.csv.gz  in=357,285,301 out=103,945,320 elapsed=175.9s

  [12056/17668] intraday_4389.csv.gz  in=357,296,343 out=103,945,320 elapsed=175.9s

  [12057/17668] intraday_4387.csv.gz  in=357,308,699 out=103,945,320 elapsed=175.9s

  [12058/17668] intraday_4386.csv.gz  in=357,323,681 out=103,945,320 elapsed=175.9s

  [12059/17668] intraday_4391.csv.gz  in=357,336,506 out=103,945,320 elapsed=176.0s

  [12060/17668] intraday_4393.csv.gz  in=357,345,384 out=103,945,320 elapsed=176.0s

  [12061/17668] intraday_4392.csv.gz  in=357,358,436 out=103,945,320 elapsed=176.0s

  [12062/17668] intraday_4390.csv.gz  in=357,369,679 out=103,945,320 elapsed=176.0s

  [12063/17668] intraday_4394.csv.gz  in=357,377,980 out=103,945,320 elapsed=176.0s

  [12064/17668] intraday_4396.csv.gz  in=357,379,302 out=103,945,320 elapsed=176.0s

  [12065/17668] intraday_4395.csv.gz  in=357,391,099 out=103,945,320 elapsed=176.0s

  [12066/17668] intraday_4397.csv.gz  in=357,406,013 out=103,945,320 elapsed=176.0s

  [12067/17668] intraday_4399.csv.gz  in=357,418,678 out=103,945,320 elapsed=176.0s

  [12068/17668] intraday_4398.csv.gz  in=357,433,527 out=103,945,320 elapsed=176.0s

  [12069/17668] intraday_4401.csv.gz  in=357,448,712 out=103,945,320 elapsed=176.0s

  [12070/17668] intraday_4400.csv.gz  in=357,459,403 out=103,945,320 elapsed=176.0s

  [12071/17668] intraday_4403.csv.gz  in=357,472,056 out=103,945,320 elapsed=176.1s

  [12072/17668] intraday_4404.csv.gz  in=357,483,310 out=103,945,320 elapsed=176.1s

  [12073/17668] intraday_4402.csv.gz  in=357,498,019 out=103,945,320 elapsed=176.1s

  [12074/17668] intraday_4405.csv.gz  in=357,511,773 out=103,945,320 elapsed=176.1s

  [12075/17668] intraday_4407.csv.gz  in=357,521,736 out=103,945,320 elapsed=176.1s

  [12076/17668] intraday_4406.csv.gz  in=357,537,419 out=103,945,320 elapsed=176.1s

  [12077/17668] intraday_4408.csv.gz  in=357,550,119 out=103,945,320 elapsed=176.1s

  [12078/17668] intraday_4409.csv.gz  in=357,564,336 out=103,945,320 elapsed=176.1s

  [12079/17668] intraday_4410.csv.gz  in=357,577,106 out=103,945,320 elapsed=176.1s

  [12080/17668] intraday_4411.csv.gz  in=357,588,046 out=103,945,320 elapsed=176.1s

  [12081/17668] intraday_4412.csv.gz  in=357,599,490 out=103,945,320 elapsed=176.1s

  [12082/17668] intraday_4413.csv.gz  in=357,612,743 out=103,945,320 elapsed=176.1s

  [12083/17668] intraday_4415.csv.gz  in=357,623,919 out=103,945,320 elapsed=176.2s

  [12084/17668] intraday_4416.csv.gz  in=357,637,217 out=103,945,320 elapsed=176.2s

  [12085/17668] intraday_4414.csv.gz  in=357,650,276 out=103,945,320 elapsed=176.2s

  [12086/17668] intraday_4417.csv.gz  in=357,663,735 out=103,945,320 elapsed=176.2s

  [12087/17668] intraday_4418.csv.gz  in=357,675,849 out=103,945,320 elapsed=176.2s

  [12088/17668] intraday_4419.csv.gz  in=357,687,483 out=103,945,320 elapsed=176.2s

  [12089/17668] intraday_4421.csv.gz  in=357,699,449 out=103,945,320 elapsed=176.2s

  [12090/17668] intraday_4420.csv.gz  in=357,712,149 out=103,945,320 elapsed=176.2s

  [12091/17668] intraday_4422.csv.gz  in=357,722,479 out=103,945,320 elapsed=176.3s

  [12092/17668] intraday_4423.csv.gz  in=357,735,394 out=103,945,320 elapsed=176.3s

  [12093/17668] intraday_4424.csv.gz  in=357,747,777 out=103,945,320 elapsed=176.3s

  [12094/17668] intraday_4425.csv.gz  in=357,762,026 out=103,945,320 elapsed=176.3s

  [12095/17668] intraday_4427.csv.gz  in=357,775,694 out=103,945,320 elapsed=176.3s

  [12096/17668] intraday_4426.csv.gz  in=357,791,193 out=103,945,320 elapsed=176.3s

  [12097/17668] intraday_4429.csv.gz  in=357,803,358 out=103,945,320 elapsed=176.3s

  [12098/17668] intraday_4428.csv.gz  in=357,814,932 out=103,945,320 elapsed=176.3s

  [12099/17668] intraday_4430.csv.gz  in=357,828,053 out=103,945,320 elapsed=176.3s

  [12100/17668] intraday_4431.csv.gz  in=357,839,498 out=103,945,320 elapsed=176.3s

  [12101/17668] intraday_4432.csv.gz  in=357,851,551 out=103,945,320 elapsed=176.3s

  [12102/17668] intraday_4433.csv.gz  in=357,862,395 out=103,945,320 elapsed=176.3s

  [12103/17668] intraday_4434.csv.gz  in=357,873,355 out=103,945,320 elapsed=176.3s

  [12104/17668] intraday_4437.csv.gz  in=357,891,968 out=103,945,320 elapsed=176.4s

  [12105/17668] intraday_4435.csv.gz  in=357,902,872 out=103,945,320 elapsed=176.4s

  [12106/17668] intraday_4436.csv.gz  in=357,915,131 out=103,945,320 elapsed=176.4s

  [12107/17668] intraday_4438.csv.gz  in=357,926,736 out=103,945,320 elapsed=176.4s

  [12108/17668] intraday_4441.csv.gz  in=357,938,609 out=103,945,320 elapsed=176.4s

  [12109/17668] intraday_4439.csv.gz  in=357,951,697 out=103,945,320 elapsed=176.4s

  [12110/17668] intraday_4440.csv.gz  in=357,962,670 out=103,945,320 elapsed=176.4s

  [12111/17668] intraday_4443.csv.gz  in=357,973,672 out=103,945,320 elapsed=176.4s

  [12112/17668] intraday_4442.csv.gz  in=357,986,393 out=103,945,320 elapsed=176.5s

  [12113/17668] intraday_4444.csv.gz  in=357,998,783 out=103,945,320 elapsed=176.5s

  [12114/17668] intraday_4445.csv.gz  in=358,012,661 out=103,945,320 elapsed=176.5s

  [12115/17668] intraday_4446.csv.gz  in=358,022,598 out=103,945,320 elapsed=176.5s

  [12116/17668] intraday_4447.csv.gz  in=358,035,800 out=103,945,320 elapsed=176.5s

  [12117/17668] intraday_4448.csv.gz  in=358,046,710 out=103,945,320 elapsed=176.5s

  [12118/17668] intraday_4449.csv.gz  in=358,057,769 out=103,945,320 elapsed=176.5s

  [12119/17668] intraday_4450.csv.gz  in=358,070,840 out=103,945,320 elapsed=176.5s

  [12120/17668] intraday_4451.csv.gz  in=358,083,705 out=103,945,320 elapsed=176.5s

  [12121/17668] intraday_4452.csv.gz  in=358,095,259 out=103,945,320 elapsed=176.5s

  [12122/17668] intraday_4453.csv.gz  in=358,105,384 out=103,945,320 elapsed=176.5s

  [12123/17668] intraday_4454.csv.gz  in=358,118,978 out=103,945,320 elapsed=176.5s

  [12124/17668] intraday_4456.csv.gz  in=358,131,059 out=103,945,320 elapsed=176.6s

  [12125/17668] intraday_4455.csv.gz  in=358,142,914 out=103,945,320 elapsed=176.6s

  [12126/17668] intraday_4458.csv.gz  in=358,154,718 out=103,945,320 elapsed=176.6s

  [12127/17668] intraday_4457.csv.gz  in=358,165,483 out=103,945,320 elapsed=176.6s

  [12128/17668] intraday_4459.csv.gz  in=358,176,575 out=103,945,320 elapsed=176.6s

  [12129/17668] intraday_4460.csv.gz  in=358,190,390 out=103,945,320 elapsed=176.6s

  [12130/17668] intraday_4461.csv.gz  in=358,203,246 out=103,945,320 elapsed=176.6s

  [12131/17668] intraday_4462.csv.gz  in=358,216,597 out=103,945,320 elapsed=176.6s

  [12132/17668] intraday_4463.csv.gz  in=358,228,825 out=103,945,320 elapsed=176.6s

  [12133/17668] intraday_4464.csv.gz  in=358,239,634 out=103,945,320 elapsed=176.6s

  [12134/17668] intraday_4465.csv.gz  in=358,251,093 out=103,945,320 elapsed=176.7s

  [12135/17668] intraday_4466.csv.gz  in=358,262,666 out=103,945,320 elapsed=176.7s

  [12136/17668] intraday_4467.csv.gz  in=358,274,033 out=103,945,320 elapsed=176.7s

  [12137/17668] intraday_4468.csv.gz  in=358,287,074 out=103,945,320 elapsed=176.7s

  [12138/17668] intraday_4469.csv.gz  in=358,298,009 out=103,945,320 elapsed=176.7s

  [12139/17668] intraday_4470.csv.gz  in=358,307,959 out=103,945,320 elapsed=176.7s

  [12140/17668] intraday_4471.csv.gz  in=358,320,131 out=103,945,320 elapsed=176.7s

  [12141/17668] intraday_4472.csv.gz  in=358,335,218 out=103,945,320 elapsed=176.7s

  [12142/17668] intraday_4473.csv.gz  in=358,345,719 out=103,945,320 elapsed=176.7s

  [12143/17668] intraday_4475.csv.gz  in=358,355,722 out=103,945,320 elapsed=176.7s

  [12144/17668] intraday_4476.csv.gz  in=358,367,079 out=103,945,320 elapsed=176.7s

  [12145/17668] intraday_4474.csv.gz  in=358,379,109 out=103,945,320 elapsed=176.7s

  [12146/17668] intraday_4477.csv.gz  in=358,392,389 out=103,945,320 elapsed=176.7s

  [12147/17668] intraday_4478.csv.gz  in=358,407,657 out=103,945,320 elapsed=176.8s

  [12148/17668] intraday_4479.csv.gz  in=358,418,910 out=103,945,320 elapsed=176.8s

  [12149/17668] intraday_4480.csv.gz  in=358,429,978 out=103,945,320 elapsed=176.8s

  [12150/17668] intraday_4482.csv.gz  in=358,443,295 out=103,945,320 elapsed=176.8s

  [12151/17668] intraday_4481.csv.gz  in=358,461,932 out=103,945,320 elapsed=176.8s

  [12152/17668] intraday_4484.csv.gz  in=358,476,880 out=103,945,320 elapsed=176.8s

  [12153/17668] intraday_4483.csv.gz  in=358,490,155 out=103,945,320 elapsed=176.8s

  [12154/17668] intraday_4485.csv.gz  in=358,500,700 out=103,945,320 elapsed=176.8s

  [12155/17668] intraday_4487.csv.gz  in=358,513,740 out=103,945,320 elapsed=176.8s

  [12156/17668] intraday_4486.csv.gz  in=358,528,358 out=103,945,320 elapsed=176.8s

  [12157/17668] intraday_4488.csv.gz  in=358,542,953 out=103,945,320 elapsed=176.9s

  [12158/17668] intraday_4489.csv.gz  in=358,555,972 out=103,945,320 elapsed=176.9s

  [12159/17668] intraday_4490.csv.gz  in=358,568,237 out=103,945,320 elapsed=176.9s

  [12160/17668] intraday_4491.csv.gz  in=358,579,725 out=103,945,320 elapsed=176.9s

  [12161/17668] intraday_4493.csv.gz  in=358,591,000 out=103,945,320 elapsed=176.9s

  [12162/17668] intraday_4492.csv.gz  in=358,602,750 out=103,945,320 elapsed=176.9s

  [12163/17668] intraday_4494.csv.gz  in=358,613,745 out=103,945,320 elapsed=176.9s

  [12164/17668] intraday_4495.csv.gz  in=358,625,748 out=103,945,320 elapsed=176.9s

  [12165/17668] intraday_4496.csv.gz  in=358,636,884 out=103,945,320 elapsed=177.0s

  [12166/17668] intraday_4497.csv.gz  in=358,650,090 out=103,945,320 elapsed=177.0s

  [12167/17668] intraday_4499.csv.gz  in=358,662,839 out=103,945,320 elapsed=177.0s

  [12168/17668] intraday_4498.csv.gz  in=358,674,910 out=103,945,320 elapsed=177.0s

  [12169/17668] intraday_4501.csv.gz  in=358,687,997 out=103,945,320 elapsed=177.0s

  [12170/17668] intraday_4500.csv.gz  in=358,700,994 out=103,945,320 elapsed=177.0s

  [12171/17668] intraday_4502.csv.gz  in=358,718,500 out=103,945,320 elapsed=177.0s

  [12172/17668] intraday_4503.csv.gz  in=358,731,593 out=103,945,320 elapsed=177.0s

  [12173/17668] intraday_4505.csv.gz  in=358,742,168 out=103,945,320 elapsed=177.0s

  [12174/17668] intraday_4504.csv.gz  in=358,756,298 out=103,945,320 elapsed=177.0s

  [12175/17668] intraday_4507.csv.gz  in=358,768,318 out=103,945,320 elapsed=177.0s

  [12176/17668] intraday_4506.csv.gz  in=358,783,128 out=103,945,320 elapsed=177.0s

  [12177/17668] intraday_4508.csv.gz  in=358,796,922 out=103,945,320 elapsed=177.0s

  [12178/17668] intraday_4509.csv.gz  in=358,810,574 out=103,945,320 elapsed=177.1s

  [12179/17668] intraday_4510.csv.gz  in=358,824,759 out=103,945,320 elapsed=177.1s

  [12180/17668] intraday_4511.csv.gz  in=358,837,422 out=103,945,320 elapsed=177.1s

  [12181/17668] intraday_4512.csv.gz  in=358,853,261 out=103,945,320 elapsed=177.1s

  [12182/17668] intraday_4513.csv.gz  in=358,866,019 out=103,945,320 elapsed=177.1s

  [12183/17668] intraday_4514.csv.gz  in=358,877,567 out=103,945,320 elapsed=177.1s

  [12184/17668] intraday_4515.csv.gz  in=358,888,831 out=103,945,320 elapsed=177.1s

  [12185/17668] intraday_4517.csv.gz  in=358,898,830 out=103,945,320 elapsed=177.1s

  [12186/17668] intraday_4516.csv.gz  in=358,913,034 out=103,945,320 elapsed=177.1s

  [12187/17668] intraday_4518.csv.gz  in=358,927,138 out=103,945,320 elapsed=177.1s

  [12188/17668] intraday_4519.csv.gz  in=358,941,064 out=103,945,320 elapsed=177.2s

  [12189/17668] intraday_4521.csv.gz  in=358,952,071 out=103,945,320 elapsed=177.2s

  [12190/17668] intraday_4520.csv.gz  in=358,968,763 out=103,945,320 elapsed=177.2s

  [12191/17668] intraday_4522.csv.gz  in=358,981,615 out=103,945,320 elapsed=177.2s

  [12192/17668] intraday_4523.csv.gz  in=358,994,846 out=103,945,320 elapsed=177.2s

  [12193/17668] intraday_4524.csv.gz  in=359,006,830 out=103,945,320 elapsed=177.2s

  [12194/17668] intraday_4525.csv.gz  in=359,018,578 out=103,945,320 elapsed=177.2s

  [12195/17668] intraday_4527.csv.gz  in=359,033,749 out=103,945,320 elapsed=177.2s

  [12196/17668] intraday_4526.csv.gz  in=359,048,188 out=103,945,320 elapsed=177.2s

  [12197/17668] intraday_4528.csv.gz  in=359,060,732 out=103,945,320 elapsed=177.3s

  [12198/17668] intraday_4529.csv.gz  in=359,074,486 out=103,945,320 elapsed=177.3s

  [12199/17668] intraday_4531.csv.gz  in=359,085,691 out=103,945,320 elapsed=177.3s

  [12200/17668] intraday_4530.csv.gz  in=359,096,891 out=103,945,320 elapsed=177.3s

  [12201/17668] intraday_4534.csv.gz  in=359,105,869 out=103,945,320 elapsed=177.3s

  [12202/17668] intraday_4533.csv.gz  in=359,118,619 out=103,945,320 elapsed=177.3s

  [12203/17668] intraday_4535.csv.gz  in=359,127,478 out=103,945,320 elapsed=177.3s

  [12204/17668] intraday_4532.csv.gz  in=359,139,806 out=103,945,320 elapsed=177.3s

  [12205/17668] intraday_4536.csv.gz  in=359,151,621 out=103,945,320 elapsed=177.3s

  [12206/17668] intraday_4537.csv.gz  in=359,151,930 out=103,945,320 elapsed=177.3s

  [12207/17668] intraday_4538.csv.gz  in=359,167,117 out=103,945,320 elapsed=177.3s

  [12208/17668] intraday_4539.csv.gz  in=359,181,006 out=103,945,320 elapsed=177.4s

  [12209/17668] intraday_4540.csv.gz  in=359,193,389 out=103,945,320 elapsed=177.4s

  [12210/17668] intraday_4541.csv.gz  in=359,203,935 out=103,945,320 elapsed=177.4s

  [12211/17668] intraday_4542.csv.gz  in=359,219,135 out=103,945,320 elapsed=177.4s

  [12212/17668] intraday_4545.csv.gz  in=359,231,869 out=103,945,320 elapsed=177.4s

  [12213/17668] intraday_4546.csv.gz  in=359,245,381 out=103,945,320 elapsed=177.4s

  [12214/17668] intraday_4544.csv.gz  in=359,259,353 out=103,945,320 elapsed=177.4s

  [12215/17668] intraday_4543.csv.gz  in=359,281,114 out=103,945,320 elapsed=177.4s

  [12216/17668] intraday_4548.csv.gz  in=359,291,600 out=103,945,320 elapsed=177.4s

  [12217/17668] intraday_4547.csv.gz  in=359,306,734 out=103,945,320 elapsed=177.4s

  [12218/17668] intraday_4550.csv.gz  in=359,319,311 out=103,945,320 elapsed=177.4s

  [12219/17668] intraday_4549.csv.gz  in=359,331,910 out=103,945,320 elapsed=177.4s

  [12220/17668] intraday_4552.csv.gz  in=359,342,689 out=103,945,320 elapsed=177.5s

  [12221/17668] intraday_4551.csv.gz  in=359,353,874 out=103,945,320 elapsed=177.5s

  [12222/17668] intraday_4553.csv.gz  in=359,364,843 out=103,945,320 elapsed=177.5s

  [12223/17668] intraday_4554.csv.gz  in=359,377,974 out=103,945,320 elapsed=177.5s

  [12224/17668] intraday_4555.csv.gz  in=359,390,688 out=103,945,320 elapsed=177.5s

  [12225/17668] intraday_4557.csv.gz  in=359,403,037 out=103,945,320 elapsed=177.5s

  [12226/17668] intraday_4556.csv.gz  in=359,413,745 out=103,945,320 elapsed=177.5s

  [12227/17668] intraday_4558.csv.gz  in=359,427,014 out=103,945,320 elapsed=177.5s

  [12228/17668] intraday_4560.csv.gz  in=359,439,295 out=103,945,320 elapsed=177.5s

  [12229/17668] intraday_4559.csv.gz  in=359,452,426 out=103,945,320 elapsed=177.5s

  [12230/17668] intraday_4561.csv.gz  in=359,466,922 out=103,945,320 elapsed=177.6s

  [12231/17668] intraday_4562.csv.gz  in=359,478,289 out=103,945,320 elapsed=177.6s

  [12232/17668] intraday_4563.csv.gz  in=359,489,055 out=103,945,320 elapsed=177.6s

  [12233/17668] intraday_4564.csv.gz  in=359,501,462 out=103,945,320 elapsed=177.6s

  [12234/17668] intraday_4565.csv.gz  in=359,513,897 out=103,945,320 elapsed=177.6s

  [12235/17668] intraday_4567.csv.gz  in=359,528,851 out=103,945,320 elapsed=177.6s

  [12236/17668] intraday_4566.csv.gz  in=359,543,195 out=103,945,320 elapsed=177.6s

  [12237/17668] intraday_4568.csv.gz  in=359,556,154 out=103,945,320 elapsed=177.6s

  [12238/17668] intraday_4569.csv.gz  in=359,567,617 out=103,945,320 elapsed=177.6s

  [12239/17668] intraday_4570.csv.gz  in=359,579,102 out=103,945,320 elapsed=177.6s

  [12240/17668] intraday_4572.csv.gz  in=359,589,685 out=103,945,320 elapsed=177.6s

  [12241/17668] intraday_4571.csv.gz  in=359,603,559 out=103,945,320 elapsed=177.6s

  [12242/17668] intraday_4573.csv.gz  in=359,616,504 out=103,945,320 elapsed=177.7s

  [12243/17668] intraday_4574.csv.gz  in=359,627,373 out=103,945,320 elapsed=177.7s

  [12244/17668] intraday_4575.csv.gz  in=359,637,946 out=103,945,320 elapsed=177.7s

  [12245/17668] intraday_4576.csv.gz  in=359,649,764 out=103,945,320 elapsed=177.7s

  [12246/17668] intraday_4577.csv.gz  in=359,661,822 out=103,945,320 elapsed=177.7s

  [12247/17668] intraday_4578.csv.gz  in=359,673,843 out=103,945,320 elapsed=177.7s

  [12248/17668] intraday_4579.csv.gz  in=359,686,728 out=103,945,320 elapsed=177.7s

  [12249/17668] intraday_4581.csv.gz  in=359,697,611 out=103,945,320 elapsed=177.7s

  [12250/17668] intraday_4580.csv.gz  in=359,711,476 out=103,945,320 elapsed=177.7s

  [12251/17668] intraday_4582.csv.gz  in=359,725,435 out=103,945,320 elapsed=177.7s

  [12252/17668] intraday_4583.csv.gz  in=359,737,140 out=103,945,320 elapsed=177.7s

  [12253/17668] intraday_4584.csv.gz  in=359,748,292 out=103,945,320 elapsed=177.8s

  [12254/17668] intraday_4585.csv.gz  in=359,760,376 out=103,945,320 elapsed=177.8s

  [12255/17668] intraday_4586.csv.gz  in=359,771,496 out=103,945,320 elapsed=177.8s

  [12256/17668] intraday_4587.csv.gz  in=359,781,104 out=103,945,320 elapsed=177.8s

  [12257/17668] intraday_4588.csv.gz  in=359,795,198 out=103,945,320 elapsed=177.8s

  [12258/17668] intraday_4589.csv.gz  in=359,805,022 out=103,945,320 elapsed=177.8s

  [12259/17668] intraday_4591.csv.gz  in=359,816,529 out=103,945,320 elapsed=177.8s

  [12260/17668] intraday_4593.csv.gz  in=359,828,139 out=103,945,320 elapsed=177.8s

  [12261/17668] intraday_4590.csv.gz  in=359,839,900 out=103,945,320 elapsed=177.8s

  [12262/17668] intraday_4592.csv.gz  in=359,851,834 out=103,945,320 elapsed=177.8s

  [12263/17668] intraday_4594.csv.gz  in=359,862,208 out=103,945,320 elapsed=177.8s

  [12264/17668] intraday_4595.csv.gz  in=359,878,146 out=103,945,320 elapsed=177.9s

  [12265/17668] intraday_4596.csv.gz  in=359,888,855 out=103,945,320 elapsed=177.9s

  [12266/17668] intraday_4597.csv.gz  in=359,901,194 out=103,945,320 elapsed=177.9s

  [12267/17668] intraday_4599.csv.gz  in=359,921,849 out=103,945,320 elapsed=177.9s

  [12268/17668] intraday_4598.csv.gz  in=359,933,023 out=103,945,320 elapsed=177.9s

  [12269/17668] intraday_4600.csv.gz  in=359,944,217 out=103,945,320 elapsed=177.9s

  [12270/17668] intraday_4601.csv.gz  in=359,958,186 out=103,945,320 elapsed=177.9s

  [12271/17668] intraday_4604.csv.gz  in=359,970,279 out=103,945,320 elapsed=177.9s

  [12272/17668] intraday_4603.csv.gz  in=359,983,838 out=103,945,320 elapsed=177.9s

  [12273/17668] intraday_4602.csv.gz  in=359,997,293 out=103,945,320 elapsed=177.9s

  [12274/17668] intraday_4605.csv.gz  in=360,007,045 out=103,945,320 elapsed=177.9s

  [12275/17668] intraday_4607.csv.gz  in=360,018,171 out=103,945,320 elapsed=178.0s

  [12276/17668] intraday_4608.csv.gz  in=360,030,446 out=103,945,320 elapsed=178.0s

  [12277/17668] intraday_4609.csv.gz  in=360,043,127 out=103,945,320 elapsed=178.0s

  [12278/17668] intraday_4610.csv.gz  in=360,054,824 out=103,945,320 elapsed=178.0s

  [12279/17668] intraday_4606.csv.gz  in=360,078,685 out=103,945,320 elapsed=178.0s

  [12280/17668] intraday_4611.csv.gz  in=360,088,697 out=103,945,320 elapsed=178.0s

  [12281/17668] intraday_4612.csv.gz  in=360,100,727 out=103,945,320 elapsed=178.0s

  [12282/17668] intraday_4613.csv.gz  in=360,115,130 out=103,945,320 elapsed=178.0s

  [12283/17668] intraday_4616.csv.gz  in=360,125,460 out=103,945,320 elapsed=178.0s

  [12284/17668] intraday_4614.csv.gz  in=360,136,940 out=103,945,320 elapsed=178.3s

  [12285/17668] intraday_4615.csv.gz  in=360,149,414 out=103,945,320 elapsed=178.3s

  [12286/17668] intraday_4617.csv.gz  in=360,160,861 out=103,945,320 elapsed=178.3s

  [12287/17668] intraday_4618.csv.gz  in=360,173,603 out=103,945,320 elapsed=178.3s

  [12288/17668] intraday_4619.csv.gz  in=360,190,634 out=103,945,320 elapsed=178.4s

  [12289/17668] intraday_4620.csv.gz  in=360,203,704 out=103,945,320 elapsed=178.4s

  [12290/17668] intraday_4622.csv.gz  in=360,214,147 out=103,945,320 elapsed=178.4s

  [12291/17668] intraday_4621.csv.gz  in=360,225,505 out=103,945,320 elapsed=178.4s

  [12292/17668] intraday_4623.csv.gz  in=360,239,538 out=103,945,320 elapsed=178.4s

  [12293/17668] intraday_4624.csv.gz  in=360,254,300 out=103,945,320 elapsed=178.4s

  [12294/17668] intraday_4625.csv.gz  in=360,268,739 out=103,945,320 elapsed=178.4s

  [12295/17668] intraday_4626.csv.gz  in=360,279,521 out=103,945,320 elapsed=178.4s

  [12296/17668] intraday_4628.csv.gz  in=360,293,445 out=103,945,320 elapsed=178.4s

  [12297/17668] intraday_4627.csv.gz  in=360,310,102 out=103,945,320 elapsed=178.4s

  [12298/17668] intraday_4629.csv.gz  in=360,327,578 out=103,945,320 elapsed=178.4s

  [12299/17668] intraday_4630.csv.gz  in=360,341,642 out=103,945,320 elapsed=178.4s

  [12300/17668] intraday_4631.csv.gz  in=360,353,669 out=103,945,320 elapsed=178.4s

  [12301/17668] intraday_4632.csv.gz  in=360,365,224 out=103,945,320 elapsed=178.5s

  [12302/17668] intraday_4633.csv.gz  in=360,377,407 out=103,945,320 elapsed=178.5s

  [12303/17668] intraday_4635.csv.gz  in=360,388,796 out=103,945,320 elapsed=178.5s

  [12304/17668] intraday_4634.csv.gz  in=360,400,017 out=103,945,320 elapsed=178.5s

  [12305/17668] intraday_4636.csv.gz  in=360,411,383 out=103,945,320 elapsed=178.5s

  [12306/17668] intraday_4637.csv.gz  in=360,423,695 out=103,945,320 elapsed=178.5s

  [12307/17668] intraday_4639.csv.gz  in=360,435,862 out=103,945,320 elapsed=178.5s

  [12308/17668] intraday_4638.csv.gz  in=360,452,293 out=103,945,320 elapsed=178.5s

  [12309/17668] intraday_4640.csv.gz  in=360,465,967 out=103,945,320 elapsed=178.5s

  [12310/17668] intraday_4641.csv.gz  in=360,478,739 out=103,945,320 elapsed=178.5s

  [12311/17668] intraday_4642.csv.gz  in=360,491,287 out=103,945,320 elapsed=178.6s

  [12312/17668] intraday_4645.csv.gz  in=360,504,342 out=103,945,320 elapsed=178.6s

  [12313/17668] intraday_4644.csv.gz  in=360,518,175 out=103,945,320 elapsed=178.6s

  [12314/17668] intraday_4643.csv.gz  in=360,530,680 out=103,945,320 elapsed=178.6s

  [12315/17668] intraday_4646.csv.gz  in=360,542,205 out=103,945,320 elapsed=178.6s

  [12316/17668] intraday_4648.csv.gz  in=360,555,447 out=103,945,320 elapsed=178.6s

  [12317/17668] intraday_4647.csv.gz  in=360,569,619 out=103,945,320 elapsed=178.6s

  [12318/17668] intraday_4649.csv.gz  in=360,584,414 out=103,945,320 elapsed=178.6s

  [12319/17668] intraday_4650.csv.gz  in=360,598,798 out=103,945,320 elapsed=178.6s

  [12320/17668] intraday_4653.csv.gz  in=360,613,166 out=103,945,320 elapsed=178.7s

  [12321/17668] intraday_4652.csv.gz  in=360,627,847 out=103,945,320 elapsed=178.7s

  [12322/17668] intraday_4651.csv.gz  in=360,640,850 out=103,945,320 elapsed=178.7s

  [12323/17668] intraday_4654.csv.gz  in=360,653,839 out=103,945,320 elapsed=178.7s

  [12324/17668] intraday_4655.csv.gz  in=360,665,446 out=103,945,320 elapsed=178.7s

  [12325/17668] intraday_4656.csv.gz  in=360,675,797 out=103,945,320 elapsed=178.7s

  [12326/17668] intraday_4658.csv.gz  in=360,687,244 out=103,945,320 elapsed=178.7s

  [12327/17668] intraday_4657.csv.gz  in=360,700,244 out=103,945,320 elapsed=178.7s

  [12328/17668] intraday_4659.csv.gz  in=360,714,744 out=103,945,320 elapsed=178.7s

  [12329/17668] intraday_4660.csv.gz  in=360,728,384 out=103,945,320 elapsed=178.7s

  [12330/17668] intraday_4662.csv.gz  in=360,740,493 out=103,945,320 elapsed=178.7s

  [12331/17668] intraday_4661.csv.gz  in=360,757,922 out=103,945,320 elapsed=178.8s

  [12332/17668] intraday_4663.csv.gz  in=360,771,491 out=103,945,320 elapsed=178.8s

  [12333/17668] intraday_4664.csv.gz  in=360,784,933 out=103,945,320 elapsed=178.8s

  [12334/17668] intraday_4665.csv.gz  in=360,796,315 out=103,945,320 elapsed=178.8s

  [12335/17668] intraday_4666.csv.gz  in=360,809,120 out=103,945,320 elapsed=178.8s

  [12336/17668] intraday_4667.csv.gz  in=360,824,169 out=103,945,320 elapsed=178.8s

  [12337/17668] intraday_4668.csv.gz  in=360,838,356 out=103,945,320 elapsed=178.8s

  [12338/17668] intraday_4669.csv.gz  in=360,851,031 out=103,945,320 elapsed=178.8s

  [12339/17668] intraday_4670.csv.gz  in=360,867,598 out=103,945,320 elapsed=178.8s

  [12340/17668] intraday_4671.csv.gz  in=360,878,457 out=103,945,320 elapsed=178.8s

  [12341/17668] intraday_4672.csv.gz  in=360,889,797 out=103,945,320 elapsed=178.9s

  [12342/17668] intraday_4675.csv.gz  in=360,898,996 out=103,945,320 elapsed=178.9s

  [12343/17668] intraday_4673.csv.gz  in=360,910,591 out=103,945,320 elapsed=178.9s

  [12344/17668] intraday_4674.csv.gz  in=360,923,999 out=103,945,320 elapsed=178.9s

  [12345/17668] intraday_4678.csv.gz  in=360,924,271 out=103,945,320 elapsed=178.9s

  [12346/17668] intraday_4676.csv.gz  in=360,938,556 out=103,945,320 elapsed=178.9s

  [12347/17668] intraday_4677.csv.gz  in=360,950,019 out=103,945,320 elapsed=178.9s

  [12348/17668] intraday_4679.csv.gz  in=360,964,322 out=103,945,320 elapsed=178.9s

  [12349/17668] intraday_4680.csv.gz  in=360,978,089 out=103,945,320 elapsed=178.9s

  [12350/17668] intraday_4682.csv.gz  in=360,987,892 out=103,945,320 elapsed=178.9s

  [12351/17668] intraday_4681.csv.gz  in=360,999,705 out=103,945,320 elapsed=179.0s

  [12352/17668] intraday_4684.csv.gz  in=361,015,881 out=103,945,320 elapsed=179.0s

  [12353/17668] intraday_4683.csv.gz  in=361,030,836 out=103,945,320 elapsed=179.0s

  [12354/17668] intraday_4686.csv.gz  in=361,043,150 out=103,945,320 elapsed=179.0s

  [12355/17668] intraday_4685.csv.gz  in=361,055,280 out=103,945,320 elapsed=179.0s

  [12356/17668] intraday_4687.csv.gz  in=361,068,830 out=103,945,320 elapsed=179.0s

  [12357/17668] intraday_4689.csv.gz  in=361,079,478 out=103,945,320 elapsed=179.0s

  [12358/17668] intraday_4688.csv.gz  in=361,093,439 out=103,945,320 elapsed=179.0s

  [12359/17668] intraday_4691.csv.gz  in=361,106,550 out=103,945,320 elapsed=179.0s

  [12360/17668] intraday_4690.csv.gz  in=361,118,373 out=103,945,320 elapsed=179.0s

  [12361/17668] intraday_4693.csv.gz  in=361,129,002 out=103,945,320 elapsed=179.1s

  [12362/17668] intraday_4692.csv.gz  in=361,139,129 out=103,945,320 elapsed=179.1s

  [12363/17668] intraday_4695.csv.gz  in=361,152,186 out=103,945,320 elapsed=179.1s

  [12364/17668] intraday_4694.csv.gz  in=361,162,099 out=103,945,320 elapsed=179.1s

  [12365/17668] intraday_4697.csv.gz  in=361,172,071 out=103,945,320 elapsed=179.1s

  [12366/17668] intraday_4696.csv.gz  in=361,184,266 out=103,945,320 elapsed=179.1s

  [12367/17668] intraday_4699.csv.gz  in=361,197,152 out=103,945,320 elapsed=179.1s

  [12368/17668] intraday_4698.csv.gz  in=361,209,102 out=103,945,320 elapsed=179.1s

  [12369/17668] intraday_4700.csv.gz  in=361,222,345 out=103,945,320 elapsed=179.1s

  [12370/17668] intraday_4701.csv.gz  in=361,236,303 out=103,945,320 elapsed=179.1s

  [12371/17668] intraday_4703.csv.gz  in=361,248,127 out=103,945,320 elapsed=179.1s

  [12372/17668] intraday_4702.csv.gz  in=361,259,924 out=103,945,320 elapsed=179.2s

  [12373/17668] intraday_4705.csv.gz  in=361,272,060 out=103,945,320 elapsed=179.2s

  [12374/17668] intraday_4704.csv.gz  in=361,282,069 out=103,945,320 elapsed=179.2s

  [12375/17668] intraday_4706.csv.gz  in=361,298,128 out=103,945,320 elapsed=179.2s

  [12376/17668] intraday_4707.csv.gz  in=361,310,702 out=103,945,320 elapsed=179.2s

  [12377/17668] intraday_4708.csv.gz  in=361,324,539 out=103,945,320 elapsed=179.2s

  [12378/17668] intraday_4709.csv.gz  in=361,339,329 out=103,945,320 elapsed=179.2s

  [12379/17668] intraday_4710.csv.gz  in=361,350,279 out=103,945,320 elapsed=179.2s

  [12380/17668] intraday_4711.csv.gz  in=361,361,091 out=103,945,320 elapsed=179.2s

  [12381/17668] intraday_4712.csv.gz  in=361,373,714 out=103,945,320 elapsed=179.3s

  [12382/17668] intraday_4715.csv.gz  in=361,383,794 out=103,945,320 elapsed=179.3s

  [12383/17668] intraday_4713.csv.gz  in=361,409,853 out=103,945,320 elapsed=179.3s

  [12384/17668] intraday_4714.csv.gz  in=361,422,151 out=103,945,320 elapsed=179.3s

  [12385/17668] intraday_4716.csv.gz  in=361,432,867 out=103,945,320 elapsed=179.3s

  [12386/17668] intraday_4718.csv.gz  in=361,444,371 out=103,945,320 elapsed=179.3s

  [12387/17668] intraday_4719.csv.gz  in=361,457,903 out=103,945,320 elapsed=179.3s

  [12388/17668] intraday_4717.csv.gz  in=361,488,251 out=103,945,320 elapsed=179.3s

  [12389/17668] intraday_4720.csv.gz  in=361,509,717 out=103,945,320 elapsed=179.3s

  [12390/17668] intraday_4722.csv.gz  in=361,520,736 out=103,945,320 elapsed=179.3s

  [12391/17668] intraday_4723.csv.gz  in=361,532,080 out=103,945,320 elapsed=179.4s

  [12392/17668] intraday_4724.csv.gz  in=361,544,973 out=103,945,320 elapsed=179.4s

  [12393/17668] intraday_4721.csv.gz  in=361,557,028 out=103,945,320 elapsed=179.4s

  [12394/17668] intraday_4725.csv.gz  in=361,567,083 out=103,945,320 elapsed=179.4s

  [12395/17668] intraday_4727.csv.gz  in=361,578,346 out=103,945,320 elapsed=179.4s

  [12396/17668] intraday_4726.csv.gz  in=361,589,781 out=103,945,320 elapsed=179.4s

  [12397/17668] intraday_4728.csv.gz  in=361,599,313 out=103,945,320 elapsed=179.4s

  [12398/17668] intraday_4729.csv.gz  in=361,610,472 out=103,945,320 elapsed=179.4s

  [12399/17668] intraday_4730.csv.gz  in=361,621,911 out=103,945,320 elapsed=179.4s

  [12400/17668] intraday_4733.csv.gz  in=361,633,968 out=103,945,320 elapsed=179.4s

  [12401/17668] intraday_4732.csv.gz  in=361,646,470 out=103,945,320 elapsed=179.4s

  [12402/17668] intraday_4731.csv.gz  in=361,662,185 out=103,945,320 elapsed=179.4s

  [12403/17668] intraday_4734.csv.gz  in=361,671,866 out=103,945,320 elapsed=179.5s

  [12404/17668] intraday_4735.csv.gz  in=361,682,680 out=103,945,320 elapsed=179.5s

  [12405/17668] intraday_4736.csv.gz  in=361,694,625 out=103,945,320 elapsed=179.5s

  [12406/17668] intraday_4737.csv.gz  in=361,707,097 out=103,945,320 elapsed=179.5s

  [12407/17668] intraday_4738.csv.gz  in=361,718,897 out=103,945,320 elapsed=179.5s

  [12408/17668] intraday_4739.csv.gz  in=361,731,187 out=103,945,320 elapsed=179.5s

  [12409/17668] intraday_4740.csv.gz  in=361,743,223 out=103,945,320 elapsed=179.5s

  [12410/17668] intraday_4741.csv.gz  in=361,753,646 out=103,945,320 elapsed=179.5s

  [12411/17668] intraday_4743.csv.gz  in=361,766,855 out=103,945,320 elapsed=179.5s

  [12412/17668] intraday_4745.csv.gz  in=361,777,877 out=103,945,320 elapsed=179.5s

  [12413/17668] intraday_4744.csv.gz  in=361,791,153 out=103,945,320 elapsed=179.6s

  [12414/17668] intraday_4742.csv.gz  in=361,806,717 out=103,945,320 elapsed=179.6s

  [12415/17668] intraday_4746.csv.gz  in=361,818,203 out=103,945,320 elapsed=179.6s

  [12416/17668] intraday_4747.csv.gz  in=361,827,699 out=103,945,320 elapsed=179.6s

  [12417/17668] intraday_4748.csv.gz  in=361,839,913 out=103,945,320 elapsed=179.6s

  [12418/17668] intraday_4749.csv.gz  in=361,851,224 out=103,945,320 elapsed=179.6s

  [12419/17668] intraday_4750.csv.gz  in=361,864,541 out=103,945,320 elapsed=179.6s

  [12420/17668] intraday_4752.csv.gz  in=361,875,601 out=103,945,320 elapsed=179.6s

  [12421/17668] intraday_4751.csv.gz  in=361,886,193 out=103,945,320 elapsed=179.6s

  [12422/17668] intraday_4753.csv.gz  in=361,896,638 out=103,945,320 elapsed=179.6s

  [12423/17668] intraday_4755.csv.gz  in=361,908,527 out=103,945,320 elapsed=179.6s

  [12424/17668] intraday_4757.csv.gz  in=361,918,755 out=103,945,320 elapsed=179.7s

  [12425/17668] intraday_4754.csv.gz  in=361,932,262 out=103,945,320 elapsed=179.7s

  [12426/17668] intraday_4756.csv.gz  in=361,945,052 out=103,945,320 elapsed=179.7s

  [12427/17668] intraday_4758.csv.gz  in=361,954,927 out=103,945,320 elapsed=179.7s

  [12428/17668] intraday_4759.csv.gz  in=361,966,165 out=103,945,320 elapsed=179.7s

  [12429/17668] intraday_4761.csv.gz  in=361,980,452 out=103,945,320 elapsed=179.7s

  [12430/17668] intraday_4760.csv.gz  in=361,996,348 out=103,945,320 elapsed=179.7s

  [12431/17668] intraday_4762.csv.gz  in=362,007,765 out=103,945,320 elapsed=179.7s

  [12432/17668] intraday_4763.csv.gz  in=362,018,752 out=103,945,320 elapsed=179.7s

  [12433/17668] intraday_4765.csv.gz  in=362,031,931 out=103,945,320 elapsed=179.7s

  [12434/17668] intraday_4764.csv.gz  in=362,042,019 out=103,945,320 elapsed=179.7s

  [12435/17668] intraday_4766.csv.gz  in=362,057,640 out=103,945,320 elapsed=179.8s

  [12436/17668] intraday_4768.csv.gz  in=362,071,450 out=103,945,320 elapsed=179.8s

  [12437/17668] intraday_4769.csv.gz  in=362,084,135 out=103,945,320 elapsed=179.8s

  [12438/17668] intraday_4767.csv.gz  in=362,096,254 out=103,945,320 elapsed=179.8s

  [12439/17668] intraday_4770.csv.gz  in=362,109,356 out=103,945,320 elapsed=179.8s

  [12440/17668] intraday_4772.csv.gz  in=362,121,584 out=103,945,320 elapsed=179.8s

  [12441/17668] intraday_4771.csv.gz  in=362,138,603 out=103,945,320 elapsed=179.8s

  [12442/17668] intraday_4773.csv.gz  in=362,158,260 out=103,945,320 elapsed=179.8s

  [12443/17668] intraday_4774.csv.gz  in=362,168,936 out=103,945,320 elapsed=179.8s

  [12444/17668] intraday_4776.csv.gz  in=362,181,165 out=103,945,320 elapsed=179.8s

  [12445/17668] intraday_4775.csv.gz  in=362,192,095 out=103,945,320 elapsed=179.8s

  [12446/17668] intraday_4778.csv.gz  in=362,203,786 out=103,945,320 elapsed=179.9s

  [12447/17668] intraday_4777.csv.gz  in=362,215,017 out=103,945,320 elapsed=179.9s

  [12448/17668] intraday_4779.csv.gz  in=362,229,075 out=103,945,320 elapsed=179.9s

  [12449/17668] intraday_4780.csv.gz  in=362,251,072 out=103,945,320 elapsed=179.9s

  [12450/17668] intraday_4782.csv.gz  in=362,265,719 out=103,945,320 elapsed=179.9s

  [12451/17668] intraday_4783.csv.gz  in=362,276,152 out=103,945,320 elapsed=179.9s

  [12452/17668] intraday_4784.csv.gz  in=362,288,076 out=103,945,320 elapsed=179.9s

  [12453/17668] intraday_4781.csv.gz  in=362,316,714 out=103,945,320 elapsed=179.9s

  [12454/17668] intraday_4785.csv.gz  in=362,329,583 out=103,945,320 elapsed=179.9s

  [12455/17668] intraday_4786.csv.gz  in=362,343,880 out=103,945,320 elapsed=179.9s

  [12456/17668] intraday_4787.csv.gz  in=362,355,851 out=103,945,320 elapsed=179.9s

  [12457/17668] intraday_4788.csv.gz  in=362,368,733 out=103,945,320 elapsed=179.9s

  [12458/17668] intraday_4790.csv.gz  in=362,382,462 out=103,945,320 elapsed=180.0s

  [12459/17668] intraday_4789.csv.gz  in=362,395,419 out=103,945,320 elapsed=180.0s

  [12460/17668] intraday_4791.csv.gz  in=362,410,355 out=103,945,320 elapsed=180.0s

  [12461/17668] intraday_4792.csv.gz  in=362,424,085 out=103,945,320 elapsed=180.0s

  [12462/17668] intraday_4793.csv.gz  in=362,434,952 out=103,945,320 elapsed=180.0s

  [12463/17668] intraday_4795.csv.gz  in=362,447,200 out=103,945,320 elapsed=180.0s

  [12464/17668] intraday_4796.csv.gz  in=362,458,926 out=103,945,320 elapsed=180.0s

  [12465/17668] intraday_4794.csv.gz  in=362,474,730 out=103,945,320 elapsed=180.0s

  [12466/17668] intraday_4797.csv.gz  in=362,485,262 out=103,945,320 elapsed=180.0s

  [12467/17668] intraday_4798.csv.gz  in=362,497,115 out=103,945,320 elapsed=180.0s

  [12468/17668] intraday_4799.csv.gz  in=362,511,095 out=103,945,320 elapsed=180.1s

  [12469/17668] intraday_4800.csv.gz  in=362,524,684 out=103,945,320 elapsed=180.1s

  [12470/17668] intraday_4801.csv.gz  in=362,551,644 out=103,945,320 elapsed=180.1s

  [12471/17668] intraday_4802.csv.gz  in=362,569,033 out=103,945,320 elapsed=180.1s

  [12472/17668] intraday_4803.csv.gz  in=362,580,407 out=103,945,320 elapsed=180.1s

  [12473/17668] intraday_4804.csv.gz  in=362,593,269 out=103,945,320 elapsed=180.1s

  [12474/17668] intraday_4805.csv.gz  in=362,604,233 out=103,945,320 elapsed=180.1s

  [12475/17668] intraday_4806.csv.gz  in=362,617,131 out=103,945,320 elapsed=180.1s

  [12476/17668] intraday_4807.csv.gz  in=362,627,569 out=103,945,320 elapsed=180.1s

  [12477/17668] intraday_4808.csv.gz  in=362,640,525 out=103,945,320 elapsed=180.1s

  [12478/17668] intraday_4810.csv.gz  in=362,653,681 out=103,945,320 elapsed=180.2s

  [12479/17668] intraday_4809.csv.gz  in=362,667,988 out=103,945,320 elapsed=180.2s

  [12480/17668] intraday_4811.csv.gz  in=362,681,311 out=103,945,320 elapsed=180.2s

  [12481/17668] intraday_4812.csv.gz  in=362,692,416 out=103,945,320 elapsed=180.2s

  [12482/17668] intraday_4813.csv.gz  in=362,704,223 out=103,945,320 elapsed=180.2s

  [12483/17668] intraday_4814.csv.gz  in=362,716,390 out=103,945,320 elapsed=180.2s

  [12484/17668] intraday_4815.csv.gz  in=362,727,758 out=103,945,320 elapsed=180.2s

  [12485/17668] intraday_4816.csv.gz  in=362,738,879 out=103,945,320 elapsed=180.2s

  [12486/17668] intraday_4817.csv.gz  in=362,746,741 out=103,945,320 elapsed=180.2s

  [12487/17668] intraday_4818.csv.gz  in=362,756,347 out=103,945,320 elapsed=180.2s

  [12488/17668] intraday_4819.csv.gz  in=362,770,113 out=103,945,320 elapsed=180.2s

  [12489/17668] intraday_4820.csv.gz  in=362,785,669 out=103,945,320 elapsed=180.3s

  [12490/17668] intraday_4821.csv.gz  in=362,799,841 out=103,945,320 elapsed=180.3s

  [12491/17668] intraday_4823.csv.gz  in=362,809,299 out=103,945,320 elapsed=180.3s

  [12492/17668] intraday_4822.csv.gz  in=362,821,774 out=103,945,320 elapsed=180.3s

  [12493/17668] intraday_4826.csv.gz  in=362,834,095 out=103,945,320 elapsed=180.3s

  [12494/17668] intraday_4824.csv.gz  in=362,848,928 out=103,945,320 elapsed=180.3s

  [12495/17668] intraday_4825.csv.gz  in=362,865,023 out=103,945,320 elapsed=180.3s

  [12496/17668] intraday_4827.csv.gz  in=362,876,414 out=103,945,320 elapsed=180.3s

  [12497/17668] intraday_4829.csv.gz  in=362,890,121 out=103,945,320 elapsed=180.3s

  [12498/17668] intraday_4830.csv.gz  in=362,900,646 out=103,945,320 elapsed=180.3s

  [12499/17668] intraday_4828.csv.gz  in=362,914,966 out=103,945,320 elapsed=180.3s

  [12500/17668] intraday_4831.csv.gz  in=362,927,057 out=103,945,320 elapsed=180.3s

  [12501/17668] intraday_4832.csv.gz  in=362,939,299 out=103,945,320 elapsed=180.4s

  [12502/17668] intraday_4833.csv.gz  in=362,953,075 out=103,945,320 elapsed=180.4s

  [12503/17668] intraday_4834.csv.gz  in=362,963,837 out=103,945,320 elapsed=180.4s

  [12504/17668] intraday_4835.csv.gz  in=362,974,189 out=103,945,320 elapsed=180.4s

  [12505/17668] intraday_4839.csv.gz  in=362,985,807 out=103,945,320 elapsed=180.4s

  [12506/17668] intraday_4837.csv.gz  in=362,997,779 out=103,945,320 elapsed=180.4s

  [12507/17668] intraday_4836.csv.gz  in=363,010,859 out=103,945,320 elapsed=180.4s

  [12508/17668] intraday_4838.csv.gz  in=363,021,040 out=103,945,320 elapsed=180.4s

  [12509/17668] intraday_4841.csv.gz  in=363,034,136 out=103,945,320 elapsed=180.5s

  [12510/17668] intraday_4840.csv.gz  in=363,047,356 out=103,945,320 elapsed=180.5s

  [12511/17668] intraday_4842.csv.gz  in=363,058,720 out=103,945,320 elapsed=180.5s

  [12512/17668] intraday_4843.csv.gz  in=363,071,049 out=103,945,320 elapsed=180.5s

  [12513/17668] intraday_4845.csv.gz  in=363,080,718 out=103,945,320 elapsed=180.5s

  [12514/17668] intraday_4846.csv.gz  in=363,093,711 out=103,945,320 elapsed=180.5s

  [12515/17668] intraday_4848.csv.gz  in=363,105,869 out=103,945,320 elapsed=180.5s

  [12516/17668] intraday_4847.csv.gz  in=363,117,515 out=103,945,320 elapsed=180.5s

  [12517/17668] intraday_4844.csv.gz  in=363,149,770 out=103,945,320 elapsed=180.5s

  [12518/17668] intraday_4850.csv.gz  in=363,164,432 out=103,945,320 elapsed=180.5s

  [12519/17668] intraday_4849.csv.gz  in=363,179,513 out=103,945,320 elapsed=180.5s

  [12520/17668] intraday_4851.csv.gz  in=363,190,659 out=103,945,320 elapsed=180.6s

  [12521/17668] intraday_4852.csv.gz  in=363,201,756 out=103,945,320 elapsed=180.6s

  [12522/17668] intraday_4853.csv.gz  in=363,214,086 out=103,945,320 elapsed=180.6s

  [12523/17668] intraday_4854.csv.gz  in=363,226,369 out=103,945,320 elapsed=180.6s

  [12524/17668] intraday_4855.csv.gz  in=363,251,169 out=103,945,320 elapsed=180.6s

  [12525/17668] intraday_4856.csv.gz  in=363,260,833 out=103,945,320 elapsed=180.6s

  [12526/17668] intraday_4857.csv.gz  in=363,271,981 out=103,945,320 elapsed=180.6s

  [12527/17668] intraday_4858.csv.gz  in=363,283,277 out=103,945,320 elapsed=180.6s

  [12528/17668] intraday_4859.csv.gz  in=363,294,280 out=103,945,320 elapsed=180.6s

  [12529/17668] intraday_4860.csv.gz  in=363,308,302 out=103,945,320 elapsed=180.6s

  [12530/17668] intraday_4861.csv.gz  in=363,320,616 out=103,945,320 elapsed=180.6s

  [12531/17668] intraday_4864.csv.gz  in=363,331,958 out=103,945,320 elapsed=180.7s

  [12532/17668] intraday_4863.csv.gz  in=363,342,915 out=103,945,320 elapsed=180.7s

  [12533/17668] intraday_4862.csv.gz  in=363,354,526 out=103,945,320 elapsed=180.7s

  [12534/17668] intraday_4865.csv.gz  in=363,373,748 out=103,945,320 elapsed=180.7s

  [12535/17668] intraday_4867.csv.gz  in=363,384,478 out=103,945,320 elapsed=180.7s

  [12536/17668] intraday_4868.csv.gz  in=363,396,488 out=103,945,320 elapsed=180.7s

  [12537/17668] intraday_4866.csv.gz  in=363,406,434 out=103,945,320 elapsed=180.7s

  [12538/17668] intraday_4870.csv.gz  in=363,417,912 out=103,945,320 elapsed=180.7s

  [12539/17668] intraday_4869.csv.gz  in=363,427,227 out=103,945,320 elapsed=180.7s

  [12540/17668] intraday_4871.csv.gz  in=363,437,987 out=103,945,320 elapsed=180.7s

  [12541/17668] intraday_4872.csv.gz  in=363,453,458 out=103,945,320 elapsed=180.7s

  [12542/17668] intraday_4875.csv.gz  in=363,463,340 out=103,945,320 elapsed=180.8s

  [12543/17668] intraday_4873.csv.gz  in=363,477,374 out=103,945,320 elapsed=180.8s

  [12544/17668] intraday_4876.csv.gz  in=363,488,085 out=103,945,320 elapsed=180.8s

  [12545/17668] intraday_4874.csv.gz  in=363,499,762 out=103,945,320 elapsed=180.8s

  [12546/17668] intraday_4877.csv.gz  in=363,512,671 out=103,945,320 elapsed=180.8s

  [12547/17668] intraday_4878.csv.gz  in=363,525,477 out=103,945,320 elapsed=180.8s

  [12548/17668] intraday_4880.csv.gz  in=363,536,311 out=103,945,320 elapsed=180.8s

  [12549/17668] intraday_4879.csv.gz  in=363,547,719 out=103,945,320 elapsed=180.8s

  [12550/17668] intraday_4881.csv.gz  in=363,558,884 out=103,945,320 elapsed=180.8s

  [12551/17668] intraday_4882.csv.gz  in=363,573,369 out=103,945,320 elapsed=180.9s

  [12552/17668] intraday_4884.csv.gz  in=363,586,464 out=103,945,320 elapsed=180.9s

  [12553/17668] intraday_4883.csv.gz  in=363,601,262 out=103,945,320 elapsed=180.9s

  [12554/17668] intraday_4885.csv.gz  in=363,613,660 out=103,945,320 elapsed=180.9s

  [12555/17668] intraday_4888.csv.gz  in=363,624,923 out=103,945,320 elapsed=180.9s

  [12556/17668] intraday_4887.csv.gz  in=363,636,102 out=103,945,320 elapsed=180.9s

  [12557/17668] intraday_4886.csv.gz  in=363,647,533 out=103,945,320 elapsed=180.9s

  [12558/17668] intraday_4892.csv.gz  in=363,658,234 out=103,945,320 elapsed=180.9s

  [12559/17668] intraday_4890.csv.gz  in=363,669,796 out=103,945,320 elapsed=180.9s

  [12560/17668] intraday_4889.csv.gz  in=363,682,081 out=103,945,320 elapsed=180.9s

  [12561/17668] intraday_4891.csv.gz  in=363,695,435 out=103,945,320 elapsed=180.9s

  [12562/17668] intraday_4893.csv.gz  in=363,706,945 out=103,945,320 elapsed=181.0s

  [12563/17668] intraday_4894.csv.gz  in=363,717,414 out=103,945,320 elapsed=181.0s

  [12564/17668] intraday_4896.csv.gz  in=363,728,833 out=103,945,320 elapsed=181.0s

  [12565/17668] intraday_4895.csv.gz  in=363,742,321 out=103,945,320 elapsed=181.0s

  [12566/17668] intraday_4898.csv.gz  in=363,752,971 out=103,945,320 elapsed=181.0s

  [12567/17668] intraday_4900.csv.gz  in=363,764,540 out=103,945,320 elapsed=181.0s

  [12568/17668] intraday_4897.csv.gz  in=363,776,673 out=103,945,320 elapsed=181.0s

  [12569/17668] intraday_4899.csv.gz  in=363,787,353 out=103,945,320 elapsed=181.0s

  [12570/17668] intraday_4901.csv.gz  in=363,803,102 out=103,945,320 elapsed=181.0s

  [12571/17668] intraday_4903.csv.gz  in=363,814,015 out=103,945,320 elapsed=181.0s

  [12572/17668] intraday_4902.csv.gz  in=363,826,948 out=103,945,320 elapsed=181.0s

  [12573/17668] intraday_4904.csv.gz  in=363,838,225 out=103,945,320 elapsed=181.0s

  [12574/17668] intraday_4905.csv.gz  in=363,849,567 out=103,945,320 elapsed=181.0s

  [12575/17668] intraday_4906.csv.gz  in=363,863,848 out=103,945,320 elapsed=181.1s

  [12576/17668] intraday_4908.csv.gz  in=363,875,140 out=103,945,320 elapsed=181.1s

  [12577/17668] intraday_4907.csv.gz  in=363,890,945 out=103,945,320 elapsed=181.1s

  [12578/17668] intraday_4909.csv.gz  in=363,905,250 out=103,945,320 elapsed=181.1s

  [12579/17668] intraday_4910.csv.gz  in=363,919,488 out=103,945,320 elapsed=181.1s

  [12580/17668] intraday_4911.csv.gz  in=363,933,806 out=103,945,320 elapsed=181.1s

  [12581/17668] intraday_4912.csv.gz  in=363,946,466 out=103,945,320 elapsed=181.1s

  [12582/17668] intraday_4913.csv.gz  in=363,958,378 out=103,945,320 elapsed=181.1s

  [12583/17668] intraday_4914.csv.gz  in=363,970,677 out=103,945,320 elapsed=181.1s

  [12584/17668] intraday_4915.csv.gz  in=363,980,531 out=103,945,320 elapsed=181.1s

  [12585/17668] intraday_4917.csv.gz  in=363,991,171 out=103,945,320 elapsed=181.2s

  [12586/17668] intraday_4916.csv.gz  in=364,004,179 out=103,945,320 elapsed=181.2s

  [12587/17668] intraday_4918.csv.gz  in=364,015,952 out=103,945,320 elapsed=181.2s

  [12588/17668] intraday_4919.csv.gz  in=364,029,260 out=103,945,320 elapsed=181.2s

  [12589/17668] intraday_4920.csv.gz  in=364,041,988 out=103,945,320 elapsed=181.2s

  [12590/17668] intraday_4921.csv.gz  in=364,058,096 out=103,945,320 elapsed=181.2s

  [12591/17668] intraday_4922.csv.gz  in=364,069,031 out=103,945,320 elapsed=181.2s

  [12592/17668] intraday_4923.csv.gz  in=364,084,507 out=103,945,320 elapsed=181.2s

  [12593/17668] intraday_4924.csv.gz  in=364,095,624 out=103,945,320 elapsed=181.2s

  [12594/17668] intraday_4925.csv.gz  in=364,107,623 out=103,945,320 elapsed=181.3s

  [12595/17668] intraday_4927.csv.gz  in=364,121,706 out=103,945,320 elapsed=181.3s

  [12596/17668] intraday_4926.csv.gz  in=364,135,232 out=103,945,320 elapsed=181.3s

  [12597/17668] intraday_4931.csv.gz  in=364,148,516 out=103,945,320 elapsed=181.3s

  [12598/17668] intraday_4928.csv.gz  in=364,160,413 out=103,945,320 elapsed=181.3s

  [12599/17668] intraday_4930.csv.gz  in=364,173,886 out=103,945,320 elapsed=181.3s

  [12600/17668] intraday_4929.csv.gz  in=364,187,810 out=103,945,320 elapsed=181.3s

  [12601/17668] intraday_4934.csv.gz  in=364,199,383 out=103,945,320 elapsed=181.3s

  [12602/17668] intraday_4933.csv.gz  in=364,213,995 out=103,945,320 elapsed=181.3s

  [12603/17668] intraday_4935.csv.gz  in=364,229,565 out=103,945,320 elapsed=181.3s

  [12604/17668] intraday_4932.csv.gz  in=364,251,427 out=103,945,320 elapsed=181.3s

  [12605/17668] intraday_4936.csv.gz  in=364,263,080 out=103,945,320 elapsed=181.4s

  [12606/17668] intraday_4937.csv.gz  in=364,274,829 out=103,945,320 elapsed=181.4s

  [12607/17668] intraday_4938.csv.gz  in=364,285,294 out=103,945,320 elapsed=181.4s

  [12608/17668] intraday_4939.csv.gz  in=364,298,269 out=103,945,320 elapsed=181.4s

  [12609/17668] intraday_4940.csv.gz  in=364,309,017 out=103,945,320 elapsed=181.4s

  [12610/17668] intraday_4942.csv.gz  in=364,321,724 out=103,945,320 elapsed=181.4s

  [12611/17668] intraday_4943.csv.gz  in=364,338,215 out=103,945,320 elapsed=181.4s

  [12612/17668] intraday_4941.csv.gz  in=364,351,715 out=103,945,320 elapsed=181.4s

  [12613/17668] intraday_4944.csv.gz  in=364,363,046 out=103,945,320 elapsed=181.4s

  [12614/17668] intraday_4945.csv.gz  in=364,375,363 out=103,945,320 elapsed=181.4s

  [12615/17668] intraday_4947.csv.gz  in=364,389,529 out=103,945,320 elapsed=181.5s

  [12616/17668] intraday_4948.csv.gz  in=364,400,422 out=103,945,320 elapsed=181.5s

  [12617/17668] intraday_4946.csv.gz  in=364,425,435 out=103,945,320 elapsed=181.5s

  [12618/17668] intraday_4949.csv.gz  in=364,439,181 out=103,945,320 elapsed=181.5s

  [12619/17668] intraday_4951.csv.gz  in=364,452,308 out=103,945,320 elapsed=181.5s

  [12620/17668] intraday_4950.csv.gz  in=364,467,400 out=103,945,320 elapsed=181.5s

  [12621/17668] intraday_4953.csv.gz  in=364,478,020 out=103,945,320 elapsed=181.5s

  [12622/17668] intraday_4952.csv.gz  in=364,492,285 out=103,945,320 elapsed=181.5s

  [12623/17668] intraday_4954.csv.gz  in=364,504,007 out=103,945,320 elapsed=181.5s

  [12624/17668] intraday_4955.csv.gz  in=364,517,303 out=103,945,320 elapsed=181.5s

  [12625/17668] intraday_4957.csv.gz  in=364,526,858 out=103,945,320 elapsed=181.5s

  [12626/17668] intraday_4956.csv.gz  in=364,540,093 out=103,945,320 elapsed=181.6s

  [12627/17668] intraday_4959.csv.gz  in=364,550,492 out=103,945,320 elapsed=181.6s

  [12628/17668] intraday_4958.csv.gz  in=364,559,638 out=103,945,320 elapsed=181.6s

  [12629/17668] intraday_4960.csv.gz  in=364,566,317 out=103,945,320 elapsed=181.6s

  [12630/17668] intraday_4964.csv.gz  in=364,739,012 out=103,945,320 elapsed=181.7s

  [12631/17668] intraday_4962.csv.gz  in=364,908,901 out=103,945,320 elapsed=181.7s

  [12632/17668] intraday_4963.csv.gz  in=365,072,461 out=103,945,320 elapsed=181.7s

  [12633/17668] intraday_4961.csv.gz  in=365,275,461 out=103,945,320 elapsed=181.7s

  [12634/17668] intraday_4968.csv.gz  in=365,430,384 out=103,945,320 elapsed=181.9s

  [12635/17668] intraday_4965.csv.gz  in=365,617,263 out=103,945,320 elapsed=181.9s

  [12636/17668] intraday_4967.csv.gz  in=365,803,069 out=103,945,320 elapsed=181.9s

  [12637/17668] intraday_4966.csv.gz  in=366,009,397 out=103,945,320 elapsed=181.9s

  [12638/17668] intraday_4969.csv.gz  in=366,189,540 out=103,945,320 elapsed=182.0s

  [12639/17668] intraday_4971.csv.gz  in=366,366,149 out=103,945,320 elapsed=182.0s

  [12640/17668] intraday_4970.csv.gz  in=366,538,386 out=103,945,320 elapsed=182.0s

  [12641/17668] intraday_4972.csv.gz  in=366,696,075 out=103,945,320 elapsed=182.0s

  [12642/17668] intraday_4973.csv.gz  in=366,854,192 out=103,945,320 elapsed=182.1s

  [12643/17668] intraday_4976.csv.gz  in=366,972,448 out=103,945,320 elapsed=182.2s

  [12644/17668] intraday_4975.csv.gz  in=367,105,020 out=103,945,320 elapsed=182.2s

  [12645/17668] intraday_4974.csv.gz  in=367,252,866 out=103,945,320 elapsed=182.2s

  [12646/17668] intraday_4979.csv.gz  in=367,384,249 out=103,945,320 elapsed=182.3s

  [12647/17668] intraday_4978.csv.gz  in=367,556,302 out=103,945,320 elapsed=182.3s

  [12648/17668] intraday_4977.csv.gz  in=367,747,093 out=103,945,320 elapsed=182.3s

  [12649/17668] intraday_4980.csv.gz  in=367,910,977 out=103,945,320 elapsed=182.4s

  [12650/17668] intraday_4981.csv.gz  in=368,058,099 out=103,945,320 elapsed=182.4s

  [12651/17668] intraday_4983.csv.gz  in=368,197,211 out=103,945,320 elapsed=182.4s

  [12652/17668] intraday_4984.csv.gz  in=368,348,645 out=103,945,320 elapsed=182.5s

  [12653/17668] intraday_4982.csv.gz  in=368,524,996 out=103,945,320 elapsed=182.5s

  [12654/17668] intraday_4985.csv.gz  in=368,686,743 out=103,945,320 elapsed=182.5s

  [12655/17668] intraday_4986.csv.gz  in=368,833,519 out=103,945,320 elapsed=182.6s

  [12656/17668] intraday_4987.csv.gz  in=368,994,019 out=103,945,320 elapsed=182.6s

  [12657/17668] intraday_4988.csv.gz  in=369,140,013 out=103,945,320 elapsed=182.6s

  [12658/17668] intraday_4989.csv.gz  in=369,322,485 out=103,945,320 elapsed=182.7s

  [12659/17668] intraday_4990.csv.gz  in=369,514,638 out=103,945,320 elapsed=182.7s

  [12660/17668] intraday_4992.csv.gz  in=369,666,263 out=103,945,320 elapsed=182.7s

  [12661/17668] intraday_4993.csv.gz  in=369,817,761 out=103,945,320 elapsed=182.8s

  [12662/17668] intraday_4991.csv.gz  in=370,012,009 out=103,945,320 elapsed=182.8s

  [12663/17668] intraday_4994.csv.gz  in=370,160,842 out=103,945,320 elapsed=182.8s

  [12664/17668] intraday_4995.csv.gz  in=370,339,613 out=103,945,320 elapsed=182.9s

  [12665/17668] intraday_4996.csv.gz  in=370,480,499 out=103,945,320 elapsed=182.9s

  [12666/17668] intraday_4998.csv.gz  in=370,634,643 out=103,945,320 elapsed=182.9s

  [12667/17668] intraday_4997.csv.gz  in=370,792,596 out=103,945,320 elapsed=182.9s

  [12668/17668] intraday_4999.csv.gz  in=370,919,986 out=103,945,320 elapsed=183.0s

  [12669/17668] intraday_5000.csv.gz  in=371,059,548 out=103,945,320 elapsed=183.1s

  [12670/17668] intraday_5002.csv.gz  in=371,212,063 out=103,945,320 elapsed=183.1s

  [12671/17668] intraday_5001.csv.gz  in=371,373,244 out=103,945,320 elapsed=183.1s

  [12672/17668] intraday_5003.csv.gz  in=371,530,194 out=103,945,320 elapsed=183.2s

  [12673/17668] intraday_5004.csv.gz  in=371,702,755 out=103,945,320 elapsed=183.2s

  [12674/17668] intraday_5006.csv.gz  in=371,859,104 out=103,945,320 elapsed=183.2s

  [12675/17668] intraday_5005.csv.gz  in=372,025,037 out=103,945,320 elapsed=183.2s

  [12676/17668] intraday_5007.csv.gz  in=372,164,616 out=103,945,320 elapsed=183.3s

  [12677/17668] intraday_5008.csv.gz  in=372,308,856 out=103,945,320 elapsed=183.3s

  [12678/17668] intraday_5010.csv.gz  in=372,441,855 out=103,945,320 elapsed=183.3s

  [12679/17668] intraday_5009.csv.gz  in=372,601,574 out=103,945,320 elapsed=183.4s

  [12680/17668] intraday_5011.csv.gz  in=372,741,763 out=103,945,320 elapsed=183.4s

  [12681/17668] intraday_5013.csv.gz  in=372,872,912 out=103,945,320 elapsed=183.4s

  [12682/17668] intraday_5012.csv.gz  in=373,075,951 out=103,945,320 elapsed=183.5s

  [12683/17668] intraday_5014.csv.gz  in=373,231,645 out=103,945,320 elapsed=183.5s

  [12684/17668] intraday_5015.csv.gz  in=373,394,962 out=103,945,320 elapsed=183.6s

  [12685/17668] intraday_5016.csv.gz  in=373,554,347 out=103,945,320 elapsed=183.6s

  [12686/17668] intraday_5017.csv.gz  in=373,696,763 out=103,945,320 elapsed=183.6s

  [12687/17668] intraday_5018.csv.gz  in=373,848,990 out=103,945,320 elapsed=183.7s

  [12688/17668] intraday_5019.csv.gz  in=374,022,721 out=103,945,320 elapsed=183.7s

  [12689/17668] intraday_5020.csv.gz  in=374,168,891 out=103,945,320 elapsed=183.7s

  [12690/17668] intraday_5021.csv.gz  in=374,331,528 out=103,945,320 elapsed=183.8s

  [12691/17668] intraday_5022.csv.gz  in=374,475,406 out=103,945,320 elapsed=183.8s

  [12692/17668] intraday_5023.csv.gz  in=374,612,993 out=103,945,320 elapsed=183.8s

  [12693/17668] intraday_5024.csv.gz  in=374,746,221 out=103,945,320 elapsed=183.8s

  [12694/17668] intraday_5025.csv.gz  in=374,937,889 out=103,945,320 elapsed=183.9s

  [12695/17668] intraday_5026.csv.gz  in=375,107,366 out=103,945,320 elapsed=184.0s

  [12696/17668] intraday_5028.csv.gz  in=375,259,236 out=103,945,320 elapsed=184.0s

  [12697/17668] intraday_5027.csv.gz  in=375,430,279 out=103,945,320 elapsed=184.0s

  [12698/17668] intraday_5029.csv.gz  in=375,580,541 out=103,945,320 elapsed=184.0s

  [12699/17668] intraday_5030.csv.gz  in=375,732,168 out=103,945,320 elapsed=184.1s

  [12700/17668] intraday_5032.csv.gz  in=375,870,918 out=103,945,320 elapsed=184.1s

  [12701/17668] intraday_5031.csv.gz  in=376,023,251 out=103,945,320 elapsed=184.1s

  [12702/17668] intraday_5033.csv.gz  in=376,194,268 out=103,945,320 elapsed=184.2s

  [12703/17668] intraday_5034.csv.gz  in=376,334,575 out=103,945,320 elapsed=184.3s

  [12704/17668] intraday_5035.csv.gz  in=376,494,499 out=103,945,320 elapsed=184.3s

  [12705/17668] intraday_5036.csv.gz  in=376,637,613 out=103,945,320 elapsed=184.3s

  [12706/17668] intraday_5037.csv.gz  in=376,794,216 out=103,945,320 elapsed=184.4s

  [12707/17668] intraday_5040.csv.gz  in=376,916,358 out=103,945,320 elapsed=184.4s

  [12708/17668] intraday_5038.csv.gz  in=377,065,873 out=103,945,320 elapsed=184.4s

  [12709/17668] intraday_5039.csv.gz  in=377,231,420 out=103,945,320 elapsed=184.4s

  [12710/17668] intraday_5041.csv.gz  in=377,377,917 out=103,945,320 elapsed=184.5s

  [12711/17668] intraday_5042.csv.gz  in=377,528,264 out=103,945,320 elapsed=184.5s

  [12712/17668] intraday_5043.csv.gz  in=377,735,779 out=103,945,320 elapsed=184.6s

  [12713/17668] intraday_5044.csv.gz  in=377,915,301 out=103,945,320 elapsed=184.6s

  [12714/17668] intraday_5046.csv.gz  in=378,065,739 out=103,945,320 elapsed=184.7s

  [12715/17668] intraday_5045.csv.gz  in=378,228,905 out=103,945,320 elapsed=184.7s

  [12716/17668] intraday_5048.csv.gz  in=378,407,332 out=103,945,320 elapsed=184.7s

  [12717/17668] intraday_5047.csv.gz  in=378,552,986 out=103,945,320 elapsed=184.7s

  [12718/17668] intraday_5050.csv.gz  in=378,695,772 out=103,945,320 elapsed=184.8s

  [12719/17668] intraday_5052.csv.gz  in=378,869,941 out=103,945,320 elapsed=184.9s

  [12720/17668] intraday_5051.csv.gz  in=379,043,120 out=103,945,320 elapsed=184.9s

  [12721/17668] intraday_5049.csv.gz  in=379,253,400 out=103,945,320 elapsed=184.9s

  [12722/17668] intraday_5053.csv.gz  in=379,433,355 out=103,945,320 elapsed=185.0s

  [12723/17668] intraday_5054.csv.gz  in=379,604,689 out=103,945,320 elapsed=185.0s

  [12724/17668] intraday_5055.csv.gz  in=379,758,369 out=103,945,320 elapsed=185.0s

  [12725/17668] intraday_5056.csv.gz  in=379,918,954 out=103,945,320 elapsed=185.0s

  [12726/17668] intraday_5057.csv.gz  in=380,057,860 out=103,945,320 elapsed=185.1s

  [12727/17668] intraday_5059.csv.gz  in=380,208,475 out=103,945,320 elapsed=185.2s

  [12728/17668] intraday_5058.csv.gz  in=380,399,645 out=103,945,320 elapsed=185.2s

  [12729/17668] intraday_5060.csv.gz  in=380,564,724 out=103,945,320 elapsed=185.2s

  [12730/17668] intraday_5061.csv.gz  in=380,735,536 out=103,945,320 elapsed=185.2s

  [12731/17668] intraday_5062.csv.gz  in=380,915,141 out=103,945,320 elapsed=185.3s

  [12732/17668] intraday_5063.csv.gz  in=381,056,472 out=103,945,320 elapsed=185.3s

  [12733/17668] intraday_5064.csv.gz  in=381,216,927 out=103,945,320 elapsed=185.3s

  [12734/17668] intraday_5065.csv.gz  in=381,415,362 out=103,945,320 elapsed=185.4s

  [12735/17668] intraday_5066.csv.gz  in=381,557,129 out=103,945,320 elapsed=185.4s

  [12736/17668] intraday_5067.csv.gz  in=381,707,090 out=103,945,320 elapsed=185.4s

  [12737/17668] intraday_5068.csv.gz  in=381,907,773 out=103,945,320 elapsed=185.5s

  [12738/17668] intraday_5070.csv.gz  in=382,053,423 out=103,945,320 elapsed=185.5s

  [12739/17668] intraday_5069.csv.gz  in=382,230,129 out=103,945,320 elapsed=185.5s

  [12740/17668] intraday_5071.csv.gz  in=382,397,127 out=103,945,320 elapsed=185.6s

  [12741/17668] intraday_5072.csv.gz  in=382,570,818 out=103,945,320 elapsed=185.6s

  [12742/17668] intraday_5073.csv.gz  in=382,732,442 out=103,945,320 elapsed=185.6s

  [12743/17668] intraday_5074.csv.gz  in=382,950,515 out=103,945,320 elapsed=185.7s

  [12744/17668] intraday_5075.csv.gz  in=383,121,537 out=103,945,320 elapsed=185.7s

  [12745/17668] intraday_5076.csv.gz  in=383,312,091 out=103,945,320 elapsed=185.7s

  [12746/17668] intraday_5077.csv.gz  in=383,514,560 out=103,945,320 elapsed=185.8s

  [12747/17668] intraday_5078.csv.gz  in=383,683,977 out=103,945,320 elapsed=185.8s

  [12748/17668] intraday_5079.csv.gz  in=383,840,278 out=103,945,320 elapsed=185.8s

  [12749/17668] intraday_5080.csv.gz  in=383,983,849 out=103,945,320 elapsed=185.9s

  [12750/17668] intraday_5081.csv.gz  in=384,140,351 out=103,945,320 elapsed=185.9s

  [12751/17668] intraday_5082.csv.gz  in=384,282,851 out=103,945,320 elapsed=186.0s

  [12752/17668] intraday_5084.csv.gz  in=384,448,554 out=103,945,320 elapsed=186.0s

  [12753/17668] intraday_5083.csv.gz  in=384,607,797 out=103,945,320 elapsed=186.0s

  [12754/17668] intraday_5085.csv.gz  in=384,782,692 out=103,945,320 elapsed=186.1s

  [12755/17668] intraday_5086.csv.gz  in=384,971,882 out=103,945,320 elapsed=186.1s

  [12756/17668] intraday_5087.csv.gz  in=385,129,384 out=103,945,320 elapsed=186.2s

  [12757/17668] intraday_5088.csv.gz  in=385,286,544 out=103,945,320 elapsed=186.2s

  [12758/17668] intraday_5089.csv.gz  in=385,457,551 out=103,945,320 elapsed=186.2s

  [12759/17668] intraday_5090.csv.gz  in=385,617,016 out=103,945,320 elapsed=186.3s

  [12760/17668] intraday_5091.csv.gz  in=385,777,421 out=103,945,320 elapsed=186.3s

  [12761/17668] intraday_5092.csv.gz  in=385,963,010 out=103,945,320 elapsed=186.3s

  [12762/17668] intraday_5093.csv.gz  in=386,126,091 out=103,945,320 elapsed=186.4s

  [12763/17668] intraday_5094.csv.gz  in=386,298,678 out=103,945,320 elapsed=186.4s

  [12764/17668] intraday_5096.csv.gz  in=386,433,380 out=103,945,320 elapsed=186.5s

  [12765/17668] intraday_5095.csv.gz  in=386,596,881 out=103,945,320 elapsed=186.5s

  [12766/17668] intraday_5097.csv.gz  in=386,744,396 out=103,945,320 elapsed=186.5s

  [12767/17668] intraday_5100.csv.gz  in=386,853,171 out=103,945,320 elapsed=186.6s

  [12768/17668] intraday_5098.csv.gz  in=387,000,861 out=103,945,320 elapsed=186.6s

  [12769/17668] intraday_5099.csv.gz  in=387,180,815 out=103,945,320 elapsed=186.6s

  [12770/17668] intraday_5103.csv.gz  in=387,196,193 out=103,945,320 elapsed=186.6s

  [12771/17668] intraday_5101.csv.gz  in=387,310,154 out=103,945,320 elapsed=186.6s

  [12772/17668] intraday_5104.csv.gz  in=387,322,474 out=103,945,320 elapsed=186.6s

  [12773/17668] intraday_5105.csv.gz  in=387,336,339 out=103,945,320 elapsed=186.6s

  [12774/17668] intraday_5106.csv.gz  in=387,347,512 out=103,945,320 elapsed=186.6s

  [12775/17668] intraday_5107.csv.gz  in=387,360,904 out=103,945,320 elapsed=186.7s

  [12776/17668] intraday_5108.csv.gz  in=387,377,570 out=103,945,320 elapsed=186.7s

  [12777/17668] intraday_5109.csv.gz  in=387,391,270 out=103,945,320 elapsed=186.7s

  [12778/17668] intraday_5102.csv.gz  in=387,504,059 out=103,945,320 elapsed=186.7s

  [12779/17668] intraday_5110.csv.gz  in=387,515,700 out=103,945,320 elapsed=186.7s

  [12780/17668] intraday_5111.csv.gz  in=387,529,598 out=103,945,320 elapsed=186.7s

  [12781/17668] intraday_5112.csv.gz  in=387,542,940 out=103,945,320 elapsed=186.7s

  [12782/17668] intraday_5113.csv.gz  in=387,556,872 out=103,945,320 elapsed=186.7s

  [12783/17668] intraday_5114.csv.gz  in=387,570,009 out=103,945,320 elapsed=186.7s

  [12784/17668] intraday_5115.csv.gz  in=387,582,992 out=103,945,320 elapsed=186.7s

  [12785/17668] intraday_5116.csv.gz  in=387,594,008 out=103,945,320 elapsed=186.8s

  [12786/17668] intraday_5117.csv.gz  in=387,604,107 out=103,945,320 elapsed=186.8s

  [12787/17668] intraday_5118.csv.gz  in=387,613,515 out=103,945,320 elapsed=186.8s

  [12788/17668] intraday_5119.csv.gz  in=387,633,747 out=103,945,320 elapsed=186.8s

  [12789/17668] intraday_5120.csv.gz  in=387,647,028 out=103,945,320 elapsed=186.8s

  [12790/17668] intraday_5121.csv.gz  in=387,659,639 out=103,945,320 elapsed=186.8s

  [12791/17668] intraday_5122.csv.gz  in=387,671,529 out=103,945,320 elapsed=186.8s

  [12792/17668] intraday_5123.csv.gz  in=387,692,952 out=103,945,320 elapsed=186.8s

  [12793/17668] intraday_5125.csv.gz  in=387,704,040 out=103,945,320 elapsed=186.8s

  [12794/17668] intraday_5124.csv.gz  in=387,717,891 out=103,945,320 elapsed=186.8s

  [12795/17668] intraday_5126.csv.gz  in=387,729,979 out=103,945,320 elapsed=186.8s

  [12796/17668] intraday_5127.csv.gz  in=387,743,098 out=103,945,320 elapsed=186.9s

  [12797/17668] intraday_5129.csv.gz  in=387,755,421 out=103,945,320 elapsed=186.9s

  [12798/17668] intraday_5128.csv.gz  in=387,766,721 out=103,945,320 elapsed=186.9s

  [12799/17668] intraday_5130.csv.gz  in=387,778,746 out=103,945,320 elapsed=186.9s

  [12800/17668] intraday_5132.csv.gz  in=387,793,754 out=103,945,320 elapsed=186.9s

  [12801/17668] intraday_5134.csv.gz  in=387,804,668 out=103,945,320 elapsed=186.9s

  [12802/17668] intraday_5131.csv.gz  in=387,818,576 out=103,945,320 elapsed=186.9s

  [12803/17668] intraday_5133.csv.gz  in=387,834,644 out=103,945,320 elapsed=186.9s

  [12804/17668] intraday_5135.csv.gz  in=387,846,980 out=103,945,320 elapsed=187.0s

  [12805/17668] intraday_5136.csv.gz  in=387,859,113 out=103,945,320 elapsed=187.0s

  [12806/17668] intraday_5137.csv.gz  in=387,874,383 out=103,945,320 elapsed=187.0s

  [12807/17668] intraday_5139.csv.gz  in=387,887,117 out=103,945,320 elapsed=187.0s

  [12808/17668] intraday_5138.csv.gz  in=387,898,008 out=103,945,320 elapsed=187.0s

  [12809/17668] intraday_5140.csv.gz  in=387,910,909 out=103,945,320 elapsed=187.0s

  [12810/17668] intraday_5142.csv.gz  in=387,923,552 out=103,945,320 elapsed=187.0s

  [12811/17668] intraday_5141.csv.gz  in=387,946,375 out=103,945,320 elapsed=187.0s

  [12812/17668] intraday_5143.csv.gz  in=387,959,258 out=103,945,320 elapsed=187.0s

  [12813/17668] intraday_5144.csv.gz  in=387,971,204 out=103,945,320 elapsed=187.0s

  [12814/17668] intraday_5145.csv.gz  in=387,984,490 out=103,945,320 elapsed=187.0s

  [12815/17668] intraday_5146.csv.gz  in=387,997,301 out=103,945,320 elapsed=187.0s

  [12816/17668] intraday_5148.csv.gz  in=388,010,346 out=103,945,320 elapsed=187.0s

  [12817/17668] intraday_5147.csv.gz  in=388,023,919 out=103,945,320 elapsed=187.1s

  [12818/17668] intraday_5149.csv.gz  in=388,035,718 out=103,945,320 elapsed=187.1s

  [12819/17668] intraday_5152.csv.gz  in=388,046,620 out=103,945,320 elapsed=187.1s

  [12820/17668] intraday_5153.csv.gz  in=388,058,038 out=103,945,320 elapsed=187.1s

  [12821/17668] intraday_5150.csv.gz  in=388,070,052 out=103,945,320 elapsed=187.1s

  [12822/17668] intraday_5151.csv.gz  in=388,083,813 out=103,945,320 elapsed=187.1s

  [12823/17668] intraday_5155.csv.gz  in=388,094,453 out=103,945,320 elapsed=187.1s

  [12824/17668] intraday_5154.csv.gz  in=388,108,440 out=103,945,320 elapsed=187.1s

  [12825/17668] intraday_5156.csv.gz  in=388,120,531 out=103,945,320 elapsed=187.1s

  [12826/17668] intraday_5157.csv.gz  in=388,133,919 out=103,945,320 elapsed=187.1s

  [12827/17668] intraday_5160.csv.gz  in=388,146,066 out=103,945,320 elapsed=187.2s

  [12828/17668] intraday_5159.csv.gz  in=388,159,471 out=103,945,320 elapsed=187.2s

  [12829/17668] intraday_5158.csv.gz  in=388,173,229 out=103,945,320 elapsed=187.2s

  [12830/17668] intraday_5161.csv.gz  in=388,186,846 out=103,945,320 elapsed=187.2s

  [12831/17668] intraday_5163.csv.gz  in=388,199,808 out=103,945,320 elapsed=187.2s

  [12832/17668] intraday_5165.csv.gz  in=388,210,542 out=103,945,320 elapsed=187.2s

  [12833/17668] intraday_5164.csv.gz  in=388,221,964 out=103,945,320 elapsed=187.2s

  [12834/17668] intraday_5162.csv.gz  in=388,233,895 out=103,945,320 elapsed=187.2s

  [12835/17668] intraday_5166.csv.gz  in=388,245,079 out=103,945,320 elapsed=187.3s

  [12836/17668] intraday_5167.csv.gz  in=388,261,538 out=103,945,320 elapsed=187.3s

  [12837/17668] intraday_5168.csv.gz  in=388,274,152 out=103,945,320 elapsed=187.3s

  [12838/17668] intraday_5169.csv.gz  in=388,287,924 out=103,945,320 elapsed=187.3s

  [12839/17668] intraday_5171.csv.gz  in=388,297,817 out=103,945,320 elapsed=187.3s

  [12840/17668] intraday_5170.csv.gz  in=388,309,755 out=103,945,320 elapsed=187.3s

  [12841/17668] intraday_5172.csv.gz  in=388,321,390 out=103,945,320 elapsed=187.3s

  [12842/17668] intraday_5173.csv.gz  in=388,333,577 out=103,945,320 elapsed=187.3s

  [12843/17668] intraday_5174.csv.gz  in=388,346,055 out=103,945,320 elapsed=187.3s

  [12844/17668] intraday_5175.csv.gz  in=388,359,551 out=103,945,320 elapsed=187.3s

  [12845/17668] intraday_5176.csv.gz  in=388,372,357 out=103,945,320 elapsed=187.3s

  [12846/17668] intraday_5177.csv.gz  in=388,385,452 out=103,945,320 elapsed=187.3s

  [12847/17668] intraday_5178.csv.gz  in=388,400,237 out=103,945,320 elapsed=187.4s

  [12848/17668] intraday_5180.csv.gz  in=388,411,926 out=103,945,320 elapsed=187.4s

  [12849/17668] intraday_5179.csv.gz  in=388,425,052 out=103,945,320 elapsed=187.4s

  [12850/17668] intraday_5181.csv.gz  in=388,437,992 out=103,945,320 elapsed=187.4s

  [12851/17668] intraday_5183.csv.gz  in=388,450,085 out=103,945,320 elapsed=187.4s

  [12852/17668] intraday_5182.csv.gz  in=388,460,242 out=103,945,320 elapsed=187.4s

  [12853/17668] intraday_5184.csv.gz  in=388,472,825 out=103,945,320 elapsed=187.4s

  [12854/17668] intraday_5185.csv.gz  in=388,488,134 out=103,945,320 elapsed=187.4s

  [12855/17668] intraday_5186.csv.gz  in=388,501,875 out=103,945,320 elapsed=187.4s

  [12856/17668] intraday_5187.csv.gz  in=388,514,312 out=103,945,320 elapsed=187.4s

  [12857/17668] intraday_5188.csv.gz  in=388,525,875 out=103,945,320 elapsed=187.5s

  [12858/17668] intraday_5189.csv.gz  in=388,537,029 out=103,945,320 elapsed=187.5s

  [12859/17668] intraday_5190.csv.gz  in=388,550,850 out=103,945,320 elapsed=187.5s

  [12860/17668] intraday_5192.csv.gz  in=388,562,272 out=103,945,320 elapsed=187.5s

  [12861/17668] intraday_5193.csv.gz  in=388,576,027 out=103,945,320 elapsed=187.5s

  [12862/17668] intraday_5191.csv.gz  in=388,593,429 out=103,945,320 elapsed=187.5s

  [12863/17668] intraday_5194.csv.gz  in=388,607,065 out=103,945,320 elapsed=187.5s

  [12864/17668] intraday_5195.csv.gz  in=388,621,487 out=103,945,320 elapsed=187.5s

  [12865/17668] intraday_5196.csv.gz  in=388,634,878 out=103,945,320 elapsed=187.5s

  [12866/17668] intraday_5198.csv.gz  in=388,647,786 out=103,945,320 elapsed=187.6s

  [12867/17668] intraday_5197.csv.gz  in=388,664,299 out=103,945,320 elapsed=187.6s

  [12868/17668] intraday_5199.csv.gz  in=388,674,609 out=103,945,320 elapsed=187.6s

  [12869/17668] intraday_5200.csv.gz  in=388,688,762 out=103,945,320 elapsed=187.6s

  [12870/17668] intraday_5202.csv.gz  in=388,701,567 out=103,945,320 elapsed=187.6s

  [12871/17668] intraday_5201.csv.gz  in=388,714,563 out=103,945,320 elapsed=187.6s

  [12872/17668] intraday_5203.csv.gz  in=388,727,728 out=103,945,320 elapsed=187.6s

  [12873/17668] intraday_5204.csv.gz  in=388,742,929 out=103,945,320 elapsed=187.6s

  [12874/17668] intraday_5205.csv.gz  in=388,753,676 out=103,945,320 elapsed=187.6s

  [12875/17668] intraday_5206.csv.gz  in=388,766,788 out=103,945,320 elapsed=187.6s

  [12876/17668] intraday_5207.csv.gz  in=388,784,139 out=103,945,320 elapsed=187.6s

  [12877/17668] intraday_5208.csv.gz  in=388,794,227 out=103,945,320 elapsed=187.7s

  [12878/17668] intraday_5209.csv.gz  in=388,806,471 out=103,945,320 elapsed=187.7s

  [12879/17668] intraday_5210.csv.gz  in=388,821,777 out=103,945,320 elapsed=187.7s

  [12880/17668] intraday_5211.csv.gz  in=388,835,842 out=103,945,320 elapsed=187.7s

  [12881/17668] intraday_5212.csv.gz  in=388,847,202 out=103,945,320 elapsed=187.7s

  [12882/17668] intraday_5214.csv.gz  in=388,860,290 out=103,945,320 elapsed=187.7s

  [12883/17668] intraday_5213.csv.gz  in=388,872,977 out=103,945,320 elapsed=187.7s

  [12884/17668] intraday_5215.csv.gz  in=388,885,713 out=103,945,320 elapsed=187.7s

  [12885/17668] intraday_5216.csv.gz  in=388,902,768 out=103,945,320 elapsed=187.7s

  [12886/17668] intraday_5217.csv.gz  in=388,915,691 out=103,945,320 elapsed=187.7s

  [12887/17668] intraday_5219.csv.gz  in=388,931,285 out=103,945,320 elapsed=187.7s

  [12888/17668] intraday_5218.csv.gz  in=388,945,700 out=103,945,320 elapsed=187.7s

  [12889/17668] intraday_5220.csv.gz  in=388,959,907 out=103,945,320 elapsed=187.8s

  [12890/17668] intraday_5221.csv.gz  in=388,971,725 out=103,945,320 elapsed=187.8s

  [12891/17668] intraday_5222.csv.gz  in=388,983,133 out=103,945,320 elapsed=187.8s

  [12892/17668] intraday_5223.csv.gz  in=388,995,340 out=103,945,320 elapsed=187.8s

  [12893/17668] intraday_5224.csv.gz  in=389,006,148 out=103,945,320 elapsed=187.8s

  [12894/17668] intraday_5225.csv.gz  in=389,018,852 out=103,945,320 elapsed=187.8s

  [12895/17668] intraday_5226.csv.gz  in=389,031,695 out=103,945,320 elapsed=187.8s

  [12896/17668] intraday_5228.csv.gz  in=389,047,282 out=103,945,320 elapsed=187.8s

  [12897/17668] intraday_5227.csv.gz  in=389,066,933 out=103,945,320 elapsed=187.9s

  [12898/17668] intraday_5230.csv.gz  in=389,078,758 out=103,945,320 elapsed=187.9s

  [12899/17668] intraday_5229.csv.gz  in=389,090,410 out=103,945,320 elapsed=187.9s

  [12900/17668] intraday_5232.csv.gz  in=389,102,442 out=103,945,320 elapsed=187.9s

  [12901/17668] intraday_5231.csv.gz  in=389,116,185 out=103,945,320 elapsed=187.9s

  [12902/17668] intraday_5234.csv.gz  in=389,131,599 out=103,945,320 elapsed=187.9s

  [12903/17668] intraday_5233.csv.gz  in=389,143,851 out=103,945,320 elapsed=187.9s

  [12904/17668] intraday_5235.csv.gz  in=389,157,110 out=103,945,320 elapsed=187.9s

  [12905/17668] intraday_5238.csv.gz  in=389,170,433 out=103,945,320 elapsed=187.9s

  [12906/17668] intraday_5237.csv.gz  in=389,182,804 out=103,945,320 elapsed=187.9s

  [12907/17668] intraday_5236.csv.gz  in=389,196,911 out=103,945,320 elapsed=187.9s

  [12908/17668] intraday_5239.csv.gz  in=389,210,501 out=103,945,320 elapsed=188.0s

  [12909/17668] intraday_5242.csv.gz  in=389,219,339 out=103,945,320 elapsed=188.0s

  [12910/17668] intraday_5240.csv.gz  in=389,231,262 out=103,945,320 elapsed=188.0s

  [12911/17668] intraday_5243.csv.gz  in=389,243,045 out=103,945,320 elapsed=188.0s

  [12912/17668] intraday_5241.csv.gz  in=389,257,530 out=103,945,320 elapsed=188.0s

  [12913/17668] intraday_5244.csv.gz  in=389,266,533 out=103,945,320 elapsed=188.0s

  [12914/17668] intraday_5245.csv.gz  in=389,282,768 out=103,945,320 elapsed=188.0s

  [12915/17668] intraday_5247.csv.gz  in=389,297,426 out=103,945,320 elapsed=188.0s

  [12916/17668] intraday_5246.csv.gz  in=389,310,595 out=103,945,320 elapsed=188.0s

  [12917/17668] intraday_5249.csv.gz  in=389,323,923 out=103,945,320 elapsed=188.0s

  [12918/17668] intraday_5251.csv.gz  in=389,338,066 out=103,945,320 elapsed=188.0s

  [12919/17668] intraday_5248.csv.gz  in=389,349,319 out=103,945,320 elapsed=188.0s

  [12920/17668] intraday_5250.csv.gz  in=389,366,354 out=103,945,320 elapsed=188.1s

  [12921/17668] intraday_5252.csv.gz  in=389,378,476 out=103,945,320 elapsed=188.1s

  [12922/17668] intraday_5253.csv.gz  in=389,392,813 out=103,945,320 elapsed=188.1s

  [12923/17668] intraday_5255.csv.gz  in=389,406,606 out=103,945,320 elapsed=188.1s

  [12924/17668] intraday_5254.csv.gz  in=389,420,390 out=103,945,320 elapsed=188.1s

  [12925/17668] intraday_5256.csv.gz  in=389,434,189 out=103,945,320 elapsed=188.1s

  [12926/17668] intraday_5257.csv.gz  in=389,447,398 out=103,945,320 elapsed=188.1s

  [12927/17668] intraday_5258.csv.gz  in=389,459,559 out=103,945,320 elapsed=188.1s

  [12928/17668] intraday_5260.csv.gz  in=389,469,466 out=103,945,320 elapsed=188.1s

  [12929/17668] intraday_5259.csv.gz  in=389,480,774 out=103,945,320 elapsed=188.1s

  [12930/17668] intraday_5261.csv.gz  in=389,496,259 out=103,945,320 elapsed=188.2s

  [12931/17668] intraday_5263.csv.gz  in=389,507,969 out=103,945,320 elapsed=188.2s

  [12932/17668] intraday_5262.csv.gz  in=389,521,411 out=103,945,320 elapsed=188.2s

  [12933/17668] intraday_5265.csv.gz  in=389,533,896 out=103,945,320 elapsed=188.2s

  [12934/17668] intraday_5264.csv.gz  in=389,546,278 out=103,945,320 elapsed=188.2s

  [12935/17668] intraday_5267.csv.gz  in=389,557,973 out=103,945,320 elapsed=188.2s

  [12936/17668] intraday_5266.csv.gz  in=389,572,003 out=103,945,320 elapsed=188.2s

  [12937/17668] intraday_5268.csv.gz  in=389,584,606 out=103,945,320 elapsed=188.2s

  [12938/17668] intraday_5269.csv.gz  in=389,597,742 out=103,945,320 elapsed=188.2s

  [12939/17668] intraday_5270.csv.gz  in=389,609,013 out=103,945,320 elapsed=188.3s

  [12940/17668] intraday_5272.csv.gz  in=389,620,102 out=103,945,320 elapsed=188.3s

  [12941/17668] intraday_5271.csv.gz  in=389,632,272 out=103,945,320 elapsed=188.3s

  [12942/17668] intraday_5273.csv.gz  in=389,647,451 out=103,945,320 elapsed=188.3s

  [12943/17668] intraday_5274.csv.gz  in=389,662,268 out=103,945,320 elapsed=188.3s

  [12944/17668] intraday_5276.csv.gz  in=389,673,589 out=103,945,320 elapsed=188.3s

  [12945/17668] intraday_5275.csv.gz  in=389,690,199 out=103,945,320 elapsed=188.3s

  [12946/17668] intraday_5277.csv.gz  in=389,702,416 out=103,945,320 elapsed=188.3s

  [12947/17668] intraday_5278.csv.gz  in=389,714,725 out=103,945,320 elapsed=188.3s

  [12948/17668] intraday_5279.csv.gz  in=389,729,755 out=103,945,320 elapsed=188.3s

  [12949/17668] intraday_5281.csv.gz  in=389,742,441 out=103,945,320 elapsed=188.3s

  [12950/17668] intraday_5280.csv.gz  in=389,753,419 out=103,945,320 elapsed=188.3s

  [12951/17668] intraday_5282.csv.gz  in=389,766,618 out=103,945,320 elapsed=188.4s

  [12952/17668] intraday_5284.csv.gz  in=389,778,557 out=103,945,320 elapsed=188.4s

  [12953/17668] intraday_5283.csv.gz  in=389,789,576 out=103,945,320 elapsed=188.4s

  [12954/17668] intraday_5285.csv.gz  in=389,802,590 out=103,945,320 elapsed=188.4s

  [12955/17668] intraday_5286.csv.gz  in=389,815,137 out=103,945,320 elapsed=188.4s

  [12956/17668] intraday_5289.csv.gz  in=389,828,362 out=103,945,320 elapsed=188.4s

  [12957/17668] intraday_5288.csv.gz  in=389,841,948 out=103,945,320 elapsed=188.4s

  [12958/17668] intraday_5287.csv.gz  in=389,855,693 out=103,945,320 elapsed=188.4s

  [12959/17668] intraday_5291.csv.gz  in=389,868,239 out=103,945,320 elapsed=188.4s

  [12960/17668] intraday_5290.csv.gz  in=389,881,567 out=103,945,320 elapsed=188.5s

  [12961/17668] intraday_5292.csv.gz  in=389,893,808 out=103,945,320 elapsed=188.5s

  [12962/17668] intraday_5293.csv.gz  in=389,907,335 out=103,945,320 elapsed=188.5s

  [12963/17668] intraday_5294.csv.gz  in=389,918,417 out=103,945,320 elapsed=188.5s

  [12964/17668] intraday_5295.csv.gz  in=389,930,506 out=103,945,320 elapsed=188.5s

  [12965/17668] intraday_5296.csv.gz  in=389,947,049 out=103,945,320 elapsed=188.5s

  [12966/17668] intraday_5297.csv.gz  in=389,956,700 out=103,945,320 elapsed=188.5s

  [12967/17668] intraday_5298.csv.gz  in=389,968,315 out=103,945,320 elapsed=188.5s

  [12968/17668] intraday_5299.csv.gz  in=389,981,937 out=103,945,320 elapsed=188.5s

  [12969/17668] intraday_5300.csv.gz  in=389,995,199 out=103,945,320 elapsed=188.5s

  [12970/17668] intraday_5301.csv.gz  in=390,009,416 out=103,945,320 elapsed=188.6s

  [12971/17668] intraday_5302.csv.gz  in=390,021,285 out=103,945,320 elapsed=188.6s

  [12972/17668] intraday_5303.csv.gz  in=390,034,983 out=103,945,320 elapsed=188.6s

  [12973/17668] intraday_5304.csv.gz  in=390,046,933 out=103,945,320 elapsed=188.6s

  [12974/17668] intraday_5306.csv.gz  in=390,058,934 out=103,945,320 elapsed=188.6s

  [12975/17668] intraday_5307.csv.gz  in=390,070,233 out=103,945,320 elapsed=188.6s

  [12976/17668] intraday_5305.csv.gz  in=390,082,903 out=103,945,320 elapsed=188.6s

  [12977/17668] intraday_5308.csv.gz  in=390,093,520 out=103,945,320 elapsed=188.6s

  [12978/17668] intraday_5312.csv.gz  in=390,105,577 out=103,945,320 elapsed=188.6s

  [12979/17668] intraday_5310.csv.gz  in=390,119,343 out=103,945,320 elapsed=188.7s

  [12980/17668] intraday_5309.csv.gz  in=390,135,395 out=103,945,320 elapsed=188.7s

  [12981/17668] intraday_5311.csv.gz  in=390,149,584 out=103,945,320 elapsed=188.7s

  [12982/17668] intraday_5316.csv.gz  in=390,161,474 out=103,945,320 elapsed=188.7s

  [12983/17668] intraday_5313.csv.gz  in=390,172,083 out=103,945,320 elapsed=188.7s

  [12984/17668] intraday_5314.csv.gz  in=390,184,178 out=103,945,320 elapsed=188.7s

  [12985/17668] intraday_5315.csv.gz  in=390,196,832 out=103,945,320 elapsed=188.7s

  [12986/17668] intraday_5319.csv.gz  in=390,209,737 out=103,945,320 elapsed=188.7s

  [12987/17668] intraday_5318.csv.gz  in=390,222,092 out=103,945,320 elapsed=188.7s

  [12988/17668] intraday_5320.csv.gz  in=390,233,239 out=103,945,320 elapsed=188.7s

  [12989/17668] intraday_5317.csv.gz  in=390,246,490 out=103,945,320 elapsed=188.7s

  [12990/17668] intraday_5322.csv.gz  in=390,258,090 out=103,945,320 elapsed=188.7s

  [12991/17668] intraday_5321.csv.gz  in=390,272,144 out=103,945,320 elapsed=188.7s

  [12992/17668] intraday_5323.csv.gz  in=390,285,063 out=103,945,320 elapsed=188.7s

  [12993/17668] intraday_5324.csv.gz  in=390,295,625 out=103,945,320 elapsed=188.8s

  [12994/17668] intraday_5325.csv.gz  in=390,308,687 out=103,945,320 elapsed=188.8s

  [12995/17668] intraday_5326.csv.gz  in=390,321,769 out=103,945,320 elapsed=188.8s

  [12996/17668] intraday_5328.csv.gz  in=390,336,072 out=103,945,320 elapsed=188.8s

  [12997/17668] intraday_5327.csv.gz  in=390,352,218 out=103,945,320 elapsed=188.8s

  [12998/17668] intraday_5329.csv.gz  in=390,365,225 out=103,945,320 elapsed=188.8s

  [12999/17668] intraday_5330.csv.gz  in=390,376,974 out=103,945,320 elapsed=188.8s

  [13000/17668] intraday_5332.csv.gz  in=390,391,032 out=103,945,320 elapsed=188.8s

  [13001/17668] intraday_5331.csv.gz  in=390,402,731 out=103,945,320 elapsed=188.8s

  [13002/17668] intraday_5333.csv.gz  in=390,420,739 out=103,945,320 elapsed=188.8s

  [13003/17668] intraday_5334.csv.gz  in=390,432,625 out=103,945,320 elapsed=188.9s

  [13004/17668] intraday_5335.csv.gz  in=390,446,404 out=103,945,320 elapsed=188.9s

  [13005/17668] intraday_5336.csv.gz  in=390,459,154 out=103,945,320 elapsed=188.9s

  [13006/17668] intraday_5337.csv.gz  in=390,473,786 out=103,945,320 elapsed=188.9s

  [13007/17668] intraday_5338.csv.gz  in=390,488,045 out=103,945,320 elapsed=188.9s

  [13008/17668] intraday_5339.csv.gz  in=390,500,451 out=103,945,320 elapsed=188.9s

  [13009/17668] intraday_5340.csv.gz  in=390,514,018 out=103,945,320 elapsed=188.9s

  [13010/17668] intraday_5341.csv.gz  in=390,525,797 out=103,945,320 elapsed=188.9s

  [13011/17668] intraday_5345.csv.gz  in=390,539,048 out=103,945,320 elapsed=188.9s

  [13012/17668] intraday_5343.csv.gz  in=390,551,882 out=103,945,320 elapsed=189.0s

  [13013/17668] intraday_5344.csv.gz  in=390,564,872 out=103,945,320 elapsed=189.0s

  [13014/17668] intraday_5342.csv.gz  in=390,579,110 out=103,945,320 elapsed=189.0s

  [13015/17668] intraday_5347.csv.gz  in=390,590,420 out=103,945,320 elapsed=189.0s

  [13016/17668] intraday_5346.csv.gz  in=390,606,201 out=103,945,320 elapsed=189.0s

  [13017/17668] intraday_5348.csv.gz  in=390,619,433 out=103,945,320 elapsed=189.0s

  [13018/17668] intraday_5349.csv.gz  in=390,635,861 out=103,945,320 elapsed=189.0s

  [13019/17668] intraday_5350.csv.gz  in=390,646,767 out=103,945,320 elapsed=189.0s

  [13020/17668] intraday_5351.csv.gz  in=390,658,933 out=103,945,320 elapsed=189.0s

  [13021/17668] intraday_5352.csv.gz  in=390,674,439 out=103,945,320 elapsed=189.0s

  [13022/17668] intraday_5353.csv.gz  in=390,689,327 out=103,945,320 elapsed=189.1s

  [13023/17668] intraday_5354.csv.gz  in=390,701,702 out=103,945,320 elapsed=189.1s

  [13024/17668] intraday_5356.csv.gz  in=390,715,980 out=103,945,320 elapsed=189.1s

  [13025/17668] intraday_5355.csv.gz  in=390,729,557 out=103,945,320 elapsed=189.1s

  [13026/17668] intraday_5357.csv.gz  in=390,744,599 out=103,945,320 elapsed=189.1s

  [13027/17668] intraday_5358.csv.gz  in=390,760,503 out=103,945,320 elapsed=189.1s

  [13028/17668] intraday_5359.csv.gz  in=390,775,019 out=103,945,320 elapsed=189.1s

  [13029/17668] intraday_5360.csv.gz  in=390,789,134 out=103,945,320 elapsed=189.1s

  [13030/17668] intraday_5362.csv.gz  in=390,803,130 out=103,945,320 elapsed=189.1s

  [13031/17668] intraday_5361.csv.gz  in=390,820,088 out=103,945,320 elapsed=189.1s

  [13032/17668] intraday_5363.csv.gz  in=390,832,950 out=103,945,320 elapsed=189.1s

  [13033/17668] intraday_5364.csv.gz  in=390,844,916 out=103,945,320 elapsed=189.2s

  [13034/17668] intraday_5366.csv.gz  in=390,856,046 out=103,945,320 elapsed=189.2s

  [13035/17668] intraday_5365.csv.gz  in=390,869,349 out=103,945,320 elapsed=189.2s

  [13036/17668] intraday_5368.csv.gz  in=390,883,071 out=103,945,320 elapsed=189.2s

  [13037/17668] intraday_5369.csv.gz  in=390,897,415 out=103,945,320 elapsed=189.2s

  [13038/17668] intraday_5367.csv.gz  in=390,911,179 out=103,945,320 elapsed=189.2s

  [13039/17668] intraday_5370.csv.gz  in=390,927,260 out=103,945,320 elapsed=189.2s

  [13040/17668] intraday_5371.csv.gz  in=390,939,940 out=103,945,320 elapsed=189.2s

  [13041/17668] intraday_5372.csv.gz  in=390,952,164 out=103,945,320 elapsed=189.2s

  [13042/17668] intraday_5374.csv.gz  in=390,964,900 out=103,945,320 elapsed=189.2s

  [13043/17668] intraday_5373.csv.gz  in=390,979,507 out=103,945,320 elapsed=189.2s

  [13044/17668] intraday_5375.csv.gz  in=390,992,024 out=103,945,320 elapsed=189.3s

  [13045/17668] intraday_5379.csv.gz  in=391,004,936 out=103,945,320 elapsed=189.3s

  [13046/17668] intraday_5377.csv.gz  in=391,019,066 out=103,945,320 elapsed=189.3s

  [13047/17668] intraday_5376.csv.gz  in=391,034,912 out=103,945,320 elapsed=189.3s

  [13048/17668] intraday_5378.csv.gz  in=391,048,481 out=103,945,320 elapsed=189.3s

  [13049/17668] intraday_5380.csv.gz  in=391,059,431 out=103,945,320 elapsed=189.3s

  [13050/17668] intraday_5381.csv.gz  in=391,073,132 out=103,945,320 elapsed=189.3s

  [13051/17668] intraday_5382.csv.gz  in=391,084,788 out=103,945,320 elapsed=189.3s

  [13052/17668] intraday_5383.csv.gz  in=391,099,241 out=103,945,320 elapsed=189.3s

  [13053/17668] intraday_5384.csv.gz  in=391,108,113 out=103,945,320 elapsed=189.3s

  [13054/17668] intraday_5387.csv.gz  in=391,108,668 out=103,945,320 elapsed=189.3s

  [13055/17668] intraday_5386.csv.gz  in=391,118,226 out=103,945,320 elapsed=189.3s

  [13056/17668] intraday_5385.csv.gz  in=391,129,746 out=103,945,320 elapsed=189.4s

  [13057/17668] intraday_5390.csv.gz  in=391,130,350 out=103,945,320 elapsed=189.4s

  [13058/17668] intraday_5388.csv.gz  in=391,131,150 out=103,945,320 elapsed=189.4s

  [13059/17668] intraday_5389.csv.gz  in=391,132,924 out=103,945,320 elapsed=189.4s

  [13060/17668] intraday_5391.csv.gz  in=391,133,091 out=103,945,320 elapsed=189.4s

  [13061/17668] intraday_5393.csv.gz  in=391,133,446 out=103,945,320 elapsed=189.4s

  [13062/17668] intraday_5392.csv.gz  in=391,134,204 out=103,945,320 elapsed=189.4s

  [13063/17668] intraday_5394.csv.gz  in=391,134,597 out=103,945,320 elapsed=189.4s

  [13064/17668] intraday_5395.csv.gz  in=391,134,627 out=103,945,320 elapsed=189.4s

  [13065/17668] intraday_5396.csv.gz  in=391,134,661 out=103,945,320 elapsed=189.4s

  [13066/17668] intraday_5398.csv.gz  in=391,147,840 out=103,945,320 elapsed=189.4s

  [13067/17668] intraday_5397.csv.gz  in=391,163,586 out=103,945,320 elapsed=189.5s

  [13068/17668] intraday_5399.csv.gz  in=391,177,012 out=103,945,320 elapsed=189.5s

  [13069/17668] intraday_5400.csv.gz  in=391,189,280 out=103,945,320 elapsed=189.5s

  [13070/17668] intraday_5401.csv.gz  in=391,202,067 out=103,945,320 elapsed=189.5s

  [13071/17668] intraday_5402.csv.gz  in=391,217,335 out=103,945,320 elapsed=189.5s

  [13072/17668] intraday_5403.csv.gz  in=391,231,782 out=103,945,320 elapsed=189.5s

  [13073/17668] intraday_5404.csv.gz  in=391,243,564 out=103,945,320 elapsed=189.5s

  [13074/17668] intraday_5405.csv.gz  in=391,257,577 out=103,945,320 elapsed=189.5s

  [13075/17668] intraday_5407.csv.gz  in=391,271,833 out=103,945,320 elapsed=189.5s

  [13076/17668] intraday_5406.csv.gz  in=391,286,423 out=103,945,320 elapsed=189.5s

  [13077/17668] intraday_5408.csv.gz  in=391,300,158 out=103,945,320 elapsed=189.5s

  [13078/17668] intraday_5411.csv.gz  in=391,310,772 out=103,945,320 elapsed=189.5s

  [13079/17668] intraday_5410.csv.gz  in=391,323,059 out=103,945,320 elapsed=189.5s

  [13080/17668] intraday_5409.csv.gz  in=391,335,137 out=103,945,320 elapsed=189.5s

  [13081/17668] intraday_5412.csv.gz  in=391,344,596 out=103,945,320 elapsed=189.5s

  [13082/17668] intraday_5413.csv.gz  in=391,360,053 out=103,945,320 elapsed=189.6s

  [13083/17668] intraday_5415.csv.gz  in=391,371,673 out=103,945,320 elapsed=189.6s

  [13084/17668] intraday_5414.csv.gz  in=391,385,381 out=103,945,320 elapsed=189.6s

  [13085/17668] intraday_5416.csv.gz  in=391,397,486 out=103,945,320 elapsed=189.6s

  [13086/17668] intraday_5418.csv.gz  in=391,411,110 out=103,945,320 elapsed=189.6s

  [13087/17668] intraday_5417.csv.gz  in=391,424,346 out=103,945,320 elapsed=189.6s

  [13088/17668] intraday_5420.csv.gz  in=391,436,796 out=103,945,320 elapsed=189.6s

  [13089/17668] intraday_5419.csv.gz  in=391,450,079 out=103,945,320 elapsed=189.6s

  [13090/17668] intraday_5421.csv.gz  in=391,463,575 out=103,945,320 elapsed=189.6s

  [13091/17668] intraday_5422.csv.gz  in=391,474,735 out=103,945,320 elapsed=189.7s

  [13092/17668] intraday_5423.csv.gz  in=391,487,198 out=103,945,320 elapsed=189.7s

  [13093/17668] intraday_5424.csv.gz  in=391,498,638 out=103,945,320 elapsed=189.7s

  [13094/17668] intraday_5425.csv.gz  in=391,513,046 out=103,945,320 elapsed=189.7s

  [13095/17668] intraday_5428.csv.gz  in=391,524,625 out=103,945,320 elapsed=189.7s

  [13096/17668] intraday_5427.csv.gz  in=391,540,009 out=103,945,320 elapsed=189.7s

  [13097/17668] intraday_5426.csv.gz  in=391,555,162 out=103,945,320 elapsed=189.7s

  [13098/17668] intraday_5429.csv.gz  in=391,567,113 out=103,945,320 elapsed=189.7s

  [13099/17668] intraday_5431.csv.gz  in=391,581,605 out=103,945,320 elapsed=189.7s

  [13100/17668] intraday_5432.csv.gz  in=391,592,524 out=103,945,320 elapsed=189.7s

  [13101/17668] intraday_5430.csv.gz  in=391,604,911 out=103,945,320 elapsed=189.7s

  [13102/17668] intraday_5433.csv.gz  in=391,617,541 out=103,945,320 elapsed=189.8s

  [13103/17668] intraday_5435.csv.gz  in=391,628,438 out=103,945,320 elapsed=189.8s

  [13104/17668] intraday_5434.csv.gz  in=391,641,526 out=103,945,320 elapsed=189.8s

  [13105/17668] intraday_5436.csv.gz  in=391,652,594 out=103,945,320 elapsed=189.8s

  [13106/17668] intraday_5437.csv.gz  in=391,665,759 out=103,945,320 elapsed=189.8s

  [13107/17668] intraday_5438.csv.gz  in=391,678,840 out=103,945,320 elapsed=189.8s

  [13108/17668] intraday_5439.csv.gz  in=391,692,593 out=103,945,320 elapsed=189.8s

  [13109/17668] intraday_5440.csv.gz  in=391,705,942 out=103,945,320 elapsed=189.8s

  [13110/17668] intraday_5441.csv.gz  in=391,719,580 out=103,945,320 elapsed=189.8s

  [13111/17668] intraday_5442.csv.gz  in=391,731,929 out=103,945,320 elapsed=189.9s

  [13112/17668] intraday_5443.csv.gz  in=391,744,162 out=103,945,320 elapsed=189.9s

  [13113/17668] intraday_5444.csv.gz  in=391,755,794 out=103,945,320 elapsed=189.9s

  [13114/17668] intraday_5445.csv.gz  in=391,768,397 out=103,945,320 elapsed=189.9s

  [13115/17668] intraday_5446.csv.gz  in=391,779,617 out=103,945,320 elapsed=189.9s

  [13116/17668] intraday_5447.csv.gz  in=391,791,576 out=103,945,320 elapsed=189.9s

  [13117/17668] intraday_5448.csv.gz  in=391,806,751 out=103,945,320 elapsed=189.9s

  [13118/17668] intraday_5449.csv.gz  in=391,816,473 out=103,945,320 elapsed=189.9s

  [13119/17668] intraday_5450.csv.gz  in=391,828,215 out=103,945,320 elapsed=189.9s

  [13120/17668] intraday_5451.csv.gz  in=391,842,495 out=103,945,320 elapsed=189.9s

  [13121/17668] intraday_5453.csv.gz  in=391,857,430 out=103,945,320 elapsed=190.0s

  [13122/17668] intraday_5454.csv.gz  in=391,869,812 out=103,945,320 elapsed=190.0s

  [13123/17668] intraday_5455.csv.gz  in=391,883,065 out=103,945,320 elapsed=190.0s

  [13124/17668] intraday_5452.csv.gz  in=391,904,962 out=103,945,320 elapsed=190.0s

  [13125/17668] intraday_5456.csv.gz  in=391,917,947 out=103,945,320 elapsed=190.0s

  [13126/17668] intraday_5457.csv.gz  in=391,930,994 out=103,945,320 elapsed=190.0s

  [13127/17668] intraday_5459.csv.gz  in=391,941,772 out=103,945,320 elapsed=190.0s

  [13128/17668] intraday_5458.csv.gz  in=391,953,447 out=103,945,320 elapsed=190.0s

  [13129/17668] intraday_5460.csv.gz  in=391,963,854 out=103,945,320 elapsed=190.0s

  [13130/17668] intraday_5461.csv.gz  in=391,979,009 out=103,945,320 elapsed=190.0s

  [13131/17668] intraday_5462.csv.gz  in=391,992,453 out=103,945,320 elapsed=190.0s

  [13132/17668] intraday_5464.csv.gz  in=392,004,339 out=103,945,320 elapsed=190.0s

  [13133/17668] intraday_5465.csv.gz  in=392,014,499 out=103,945,320 elapsed=190.1s

  [13134/17668] intraday_5463.csv.gz  in=392,029,011 out=103,945,320 elapsed=190.1s

  [13135/17668] intraday_5466.csv.gz  in=392,040,751 out=103,945,320 elapsed=190.1s

  [13136/17668] intraday_5467.csv.gz  in=392,053,201 out=103,945,320 elapsed=190.1s

  [13137/17668] intraday_5468.csv.gz  in=392,065,120 out=103,945,320 elapsed=190.1s

  [13138/17668] intraday_5469.csv.gz  in=392,079,045 out=103,945,320 elapsed=190.1s

  [13139/17668] intraday_5470.csv.gz  in=392,090,705 out=103,945,320 elapsed=190.1s

  [13140/17668] intraday_5472.csv.gz  in=392,102,464 out=103,945,320 elapsed=190.1s

  [13141/17668] intraday_5471.csv.gz  in=392,114,095 out=103,945,320 elapsed=190.1s

  [13142/17668] intraday_5473.csv.gz  in=392,127,702 out=103,945,320 elapsed=190.1s

  [13143/17668] intraday_5474.csv.gz  in=392,139,136 out=103,945,320 elapsed=190.2s

  [13144/17668] intraday_5475.csv.gz  in=392,152,405 out=103,945,320 elapsed=190.2s

  [13145/17668] intraday_5476.csv.gz  in=392,162,456 out=103,945,320 elapsed=190.2s

  [13146/17668] intraday_5478.csv.gz  in=392,174,498 out=103,945,320 elapsed=190.2s

  [13147/17668] intraday_5477.csv.gz  in=392,187,657 out=103,945,320 elapsed=190.2s

  [13148/17668] intraday_5479.csv.gz  in=392,203,842 out=103,945,320 elapsed=190.2s

  [13149/17668] intraday_5482.csv.gz  in=392,215,539 out=103,945,320 elapsed=190.2s

  [13150/17668] intraday_5480.csv.gz  in=392,229,163 out=103,945,320 elapsed=190.2s

  [13151/17668] intraday_5481.csv.gz  in=392,241,517 out=103,945,320 elapsed=190.2s

  [13152/17668] intraday_5484.csv.gz  in=392,255,675 out=103,945,320 elapsed=190.2s

  [13153/17668] intraday_5483.csv.gz  in=392,267,359 out=103,945,320 elapsed=190.2s

  [13154/17668] intraday_5485.csv.gz  in=392,286,639 out=103,945,320 elapsed=190.3s

  [13155/17668] intraday_5486.csv.gz  in=392,298,775 out=103,945,320 elapsed=190.3s

  [13156/17668] intraday_5488.csv.gz  in=392,311,997 out=103,945,320 elapsed=190.3s

  [13157/17668] intraday_5489.csv.gz  in=392,326,133 out=103,945,320 elapsed=190.3s

  [13158/17668] intraday_5487.csv.gz  in=392,339,692 out=103,945,320 elapsed=190.3s

  [13159/17668] intraday_5490.csv.gz  in=392,353,458 out=103,945,320 elapsed=190.3s

  [13160/17668] intraday_5491.csv.gz  in=392,365,797 out=103,945,320 elapsed=190.3s

  [13161/17668] intraday_5492.csv.gz  in=392,379,041 out=103,945,320 elapsed=190.3s

  [13162/17668] intraday_5493.csv.gz  in=392,390,443 out=103,945,320 elapsed=190.3s

  [13163/17668] intraday_5494.csv.gz  in=392,404,909 out=103,945,320 elapsed=190.3s

  [13164/17668] intraday_5495.csv.gz  in=392,417,432 out=103,945,320 elapsed=190.3s

  [13165/17668] intraday_5497.csv.gz  in=392,448,159 out=103,945,320 elapsed=190.3s

  [13166/17668] intraday_5496.csv.gz  in=392,461,507 out=103,945,320 elapsed=190.4s

  [13167/17668] intraday_5498.csv.gz  in=392,476,771 out=103,945,320 elapsed=190.4s

  [13168/17668] intraday_5499.csv.gz  in=392,488,277 out=103,945,320 elapsed=190.4s

  [13169/17668] intraday_5501.csv.gz  in=392,504,805 out=103,945,320 elapsed=190.4s

  [13170/17668] intraday_5500.csv.gz  in=392,517,924 out=103,945,320 elapsed=190.4s

  [13171/17668] intraday_5502.csv.gz  in=392,529,028 out=103,945,320 elapsed=190.4s

  [13172/17668] intraday_5503.csv.gz  in=392,541,262 out=103,945,320 elapsed=190.4s

  [13173/17668] intraday_5504.csv.gz  in=392,557,544 out=103,945,320 elapsed=190.4s

  [13174/17668] intraday_5505.csv.gz  in=392,572,333 out=103,945,320 elapsed=190.4s

  [13175/17668] intraday_5506.csv.gz  in=392,584,678 out=103,945,320 elapsed=190.4s

  [13176/17668] intraday_5507.csv.gz  in=392,598,286 out=103,945,320 elapsed=190.5s

  [13177/17668] intraday_5509.csv.gz  in=392,611,281 out=103,945,320 elapsed=190.5s

  [13178/17668] intraday_5508.csv.gz  in=392,624,922 out=103,945,320 elapsed=190.5s

  [13179/17668] intraday_5510.csv.gz  in=392,641,315 out=103,945,320 elapsed=190.5s

  [13180/17668] intraday_5511.csv.gz  in=392,654,254 out=103,945,320 elapsed=190.5s

  [13181/17668] intraday_5513.csv.gz  in=392,670,599 out=103,945,320 elapsed=190.5s

  [13182/17668] intraday_5512.csv.gz  in=392,685,528 out=103,945,320 elapsed=190.5s

  [13183/17668] intraday_5514.csv.gz  in=392,699,516 out=103,945,320 elapsed=190.5s

  [13184/17668] intraday_5515.csv.gz  in=392,711,673 out=103,945,320 elapsed=190.5s

  [13185/17668] intraday_5516.csv.gz  in=392,722,713 out=103,945,320 elapsed=190.6s

  [13186/17668] intraday_5517.csv.gz  in=392,737,265 out=103,945,320 elapsed=190.6s

  [13187/17668] intraday_5518.csv.gz  in=392,748,187 out=103,945,320 elapsed=190.6s

  [13188/17668] intraday_5519.csv.gz  in=392,761,629 out=103,945,320 elapsed=190.6s

  [13189/17668] intraday_5520.csv.gz  in=392,774,515 out=103,945,320 elapsed=190.6s

  [13190/17668] intraday_5523.csv.gz  in=392,787,266 out=103,945,320 elapsed=190.6s

  [13191/17668] intraday_5521.csv.gz  in=392,803,736 out=103,945,320 elapsed=190.6s

  [13192/17668] intraday_5522.csv.gz  in=392,816,786 out=103,945,320 elapsed=190.6s

  [13193/17668] intraday_5524.csv.gz  in=392,829,935 out=103,945,320 elapsed=190.6s

  [13194/17668] intraday_5525.csv.gz  in=392,843,522 out=103,945,320 elapsed=190.6s

  [13195/17668] intraday_5526.csv.gz  in=392,858,944 out=103,945,320 elapsed=190.6s

  [13196/17668] intraday_5527.csv.gz  in=392,872,025 out=103,945,320 elapsed=190.7s

  [13197/17668] intraday_5528.csv.gz  in=392,886,871 out=103,945,320 elapsed=190.7s

  [13198/17668] intraday_5529.csv.gz  in=392,901,726 out=103,945,320 elapsed=190.7s

  [13199/17668] intraday_5531.csv.gz  in=392,913,022 out=103,945,320 elapsed=190.7s

  [13200/17668] intraday_5530.csv.gz  in=392,928,229 out=103,945,320 elapsed=190.7s

  [13201/17668] intraday_5532.csv.gz  in=392,940,008 out=103,945,320 elapsed=190.7s

  [13202/17668] intraday_5533.csv.gz  in=392,953,776 out=103,945,320 elapsed=190.7s

  [13203/17668] intraday_5534.csv.gz  in=392,965,956 out=103,945,320 elapsed=190.7s

  [13204/17668] intraday_5536.csv.gz  in=392,973,571 out=103,945,320 elapsed=190.7s

  [13205/17668] intraday_5535.csv.gz  in=393,007,253 out=103,945,320 elapsed=190.8s

  [13206/17668] intraday_5537.csv.gz  in=393,018,874 out=103,945,320 elapsed=190.8s

  [13207/17668] intraday_5538.csv.gz  in=393,027,492 out=103,945,320 elapsed=190.8s

  [13208/17668] intraday_5539.csv.gz  in=393,041,919 out=103,945,320 elapsed=190.8s

  [13209/17668] intraday_5541.csv.gz  in=393,054,314 out=103,945,320 elapsed=190.8s

  [13210/17668] intraday_5543.csv.gz  in=393,066,630 out=103,945,320 elapsed=190.8s

  [13211/17668] intraday_5540.csv.gz  in=393,079,916 out=103,945,320 elapsed=190.8s

  [13212/17668] intraday_5542.csv.gz  in=393,091,499 out=103,945,320 elapsed=190.8s

  [13213/17668] intraday_5546.csv.gz  in=393,103,025 out=103,945,320 elapsed=190.8s

  [13214/17668] intraday_5547.csv.gz  in=393,115,871 out=103,945,320 elapsed=190.9s

  [13215/17668] intraday_5545.csv.gz  in=393,131,295 out=103,945,320 elapsed=190.9s

  [13216/17668] intraday_5544.csv.gz  in=393,146,490 out=103,945,320 elapsed=190.9s

  [13217/17668] intraday_5548.csv.gz  in=393,160,061 out=103,945,320 elapsed=190.9s

  [13218/17668] intraday_5550.csv.gz  in=393,177,008 out=103,945,320 elapsed=190.9s

  [13219/17668] intraday_5551.csv.gz  in=393,188,976 out=103,945,320 elapsed=190.9s

  [13220/17668] intraday_5549.csv.gz  in=393,202,322 out=103,945,320 elapsed=190.9s

  [13221/17668] intraday_5552.csv.gz  in=393,213,841 out=103,945,320 elapsed=190.9s

  [13222/17668] intraday_5554.csv.gz  in=393,222,834 out=103,945,320 elapsed=190.9s

  [13223/17668] intraday_5553.csv.gz  in=393,233,003 out=103,945,320 elapsed=190.9s

  [13224/17668] intraday_5555.csv.gz  in=393,247,307 out=103,945,320 elapsed=190.9s

  [13225/17668] intraday_5556.csv.gz  in=393,260,824 out=103,945,320 elapsed=191.0s

  [13226/17668] intraday_5557.csv.gz  in=393,271,062 out=103,945,320 elapsed=191.0s

  [13227/17668] intraday_5559.csv.gz  in=393,283,090 out=103,945,320 elapsed=191.0s

  [13228/17668] intraday_5558.csv.gz  in=393,294,311 out=103,945,320 elapsed=191.0s

  [13229/17668] intraday_5560.csv.gz  in=393,308,071 out=103,945,320 elapsed=191.0s

  [13230/17668] intraday_5561.csv.gz  in=393,320,600 out=103,945,320 elapsed=191.0s

  [13231/17668] intraday_5563.csv.gz  in=393,334,312 out=103,945,320 elapsed=191.0s

  [13232/17668] intraday_5562.csv.gz  in=393,346,642 out=103,945,320 elapsed=191.0s

  [13233/17668] intraday_5564.csv.gz  in=393,357,706 out=103,945,320 elapsed=191.0s

  [13234/17668] intraday_5566.csv.gz  in=393,369,232 out=103,945,320 elapsed=191.0s

  [13235/17668] intraday_5565.csv.gz  in=393,381,626 out=103,945,320 elapsed=191.0s

  [13236/17668] intraday_5567.csv.gz  in=393,394,652 out=103,945,320 elapsed=191.0s

  [13237/17668] intraday_5570.csv.gz  in=393,405,386 out=103,945,320 elapsed=191.1s

  [13238/17668] intraday_5568.csv.gz  in=393,420,260 out=103,945,320 elapsed=191.1s

  [13239/17668] intraday_5571.csv.gz  in=393,431,910 out=103,945,320 elapsed=191.1s

  [13240/17668] intraday_5569.csv.gz  in=393,446,813 out=103,945,320 elapsed=191.1s

  [13241/17668] intraday_5572.csv.gz  in=393,458,895 out=103,945,320 elapsed=191.1s

  [13242/17668] intraday_5573.csv.gz  in=393,472,743 out=103,945,320 elapsed=191.1s

  [13243/17668] intraday_5575.csv.gz  in=393,484,522 out=103,945,320 elapsed=191.1s

  [13244/17668] intraday_5574.csv.gz  in=393,506,175 out=103,945,320 elapsed=191.1s

  [13245/17668] intraday_5577.csv.gz  in=393,516,841 out=103,945,320 elapsed=191.1s

  [13246/17668] intraday_5578.csv.gz  in=393,527,895 out=103,945,320 elapsed=191.2s

  [13247/17668] intraday_5576.csv.gz  in=393,539,579 out=103,945,320 elapsed=191.2s

  [13248/17668] intraday_5580.csv.gz  in=393,551,942 out=103,945,320 elapsed=191.2s

  [13249/17668] intraday_5579.csv.gz  in=393,568,497 out=103,945,320 elapsed=191.2s

  [13250/17668] intraday_5582.csv.gz  in=393,582,292 out=103,945,320 elapsed=191.2s

  [13251/17668] intraday_5581.csv.gz  in=393,594,500 out=103,945,320 elapsed=191.2s

  [13252/17668] intraday_5584.csv.gz  in=393,606,389 out=103,945,320 elapsed=191.2s

  [13253/17668] intraday_5583.csv.gz  in=393,619,048 out=103,945,320 elapsed=191.2s

  [13254/17668] intraday_5585.csv.gz  in=393,630,873 out=103,945,320 elapsed=191.2s

  [13255/17668] intraday_5586.csv.gz  in=393,642,235 out=103,945,320 elapsed=191.2s

  [13256/17668] intraday_5587.csv.gz  in=393,654,290 out=103,945,320 elapsed=191.3s

  [13257/17668] intraday_5589.csv.gz  in=393,665,610 out=103,945,320 elapsed=191.3s

  [13258/17668] intraday_5588.csv.gz  in=393,676,779 out=103,945,320 elapsed=191.3s

  [13259/17668] intraday_5590.csv.gz  in=393,690,700 out=103,945,320 elapsed=191.3s

  [13260/17668] intraday_5592.csv.gz  in=393,700,740 out=103,945,320 elapsed=191.3s

  [13261/17668] intraday_5591.csv.gz  in=393,710,926 out=103,945,320 elapsed=191.3s

  [13262/17668] intraday_5593.csv.gz  in=393,725,328 out=103,945,320 elapsed=191.3s

  [13263/17668] intraday_5594.csv.gz  in=393,737,558 out=103,945,320 elapsed=191.3s

  [13264/17668] intraday_5596.csv.gz  in=393,749,347 out=103,945,320 elapsed=191.3s

  [13265/17668] intraday_5595.csv.gz  in=393,763,476 out=103,945,320 elapsed=191.3s

  [13266/17668] intraday_5597.csv.gz  in=393,776,227 out=103,945,320 elapsed=191.4s

  [13267/17668] intraday_5598.csv.gz  in=393,788,514 out=103,945,320 elapsed=191.4s

  [13268/17668] intraday_5600.csv.gz  in=393,800,013 out=103,945,320 elapsed=191.4s

  [13269/17668] intraday_5599.csv.gz  in=393,812,603 out=103,945,320 elapsed=191.4s

  [13270/17668] intraday_5602.csv.gz  in=393,823,325 out=103,945,320 elapsed=191.4s

  [13271/17668] intraday_5601.csv.gz  in=393,834,063 out=103,945,320 elapsed=191.4s

  [13272/17668] intraday_5606.csv.gz  in=393,846,184 out=103,945,320 elapsed=191.4s

  [13273/17668] intraday_5604.csv.gz  in=393,859,227 out=103,945,320 elapsed=191.4s

  [13274/17668] intraday_5603.csv.gz  in=393,873,777 out=103,945,320 elapsed=191.4s

  [13275/17668] intraday_5605.csv.gz  in=393,887,821 out=103,945,320 elapsed=191.4s

  [13276/17668] intraday_5607.csv.gz  in=393,897,497 out=103,945,320 elapsed=191.5s

  [13277/17668] intraday_5608.csv.gz  in=393,909,012 out=103,945,320 elapsed=191.5s

  [13278/17668] intraday_5610.csv.gz  in=393,921,119 out=103,945,320 elapsed=191.5s

  [13279/17668] intraday_5609.csv.gz  in=393,932,817 out=103,945,320 elapsed=191.5s

  [13280/17668] intraday_5611.csv.gz  in=393,946,249 out=103,945,320 elapsed=191.5s

  [13281/17668] intraday_5612.csv.gz  in=393,957,323 out=103,945,320 elapsed=191.5s

  [13282/17668] intraday_5613.csv.gz  in=393,968,920 out=103,945,320 elapsed=191.5s

  [13283/17668] intraday_5614.csv.gz  in=393,979,350 out=103,945,320 elapsed=191.5s

  [13284/17668] intraday_5616.csv.gz  in=393,990,258 out=103,945,320 elapsed=191.5s

  [13285/17668] intraday_5617.csv.gz  in=394,002,892 out=103,945,320 elapsed=191.5s

  [13286/17668] intraday_5618.csv.gz  in=394,013,524 out=103,945,320 elapsed=191.5s

  [13287/17668] intraday_5615.csv.gz  in=394,026,892 out=103,945,320 elapsed=191.5s

  [13288/17668] intraday_5619.csv.gz  in=394,038,533 out=103,945,320 elapsed=191.5s

  [13289/17668] intraday_5620.csv.gz  in=394,049,943 out=103,945,320 elapsed=191.6s

  [13290/17668] intraday_5622.csv.gz  in=394,064,054 out=103,945,320 elapsed=191.6s

  [13291/17668] intraday_5621.csv.gz  in=394,079,062 out=103,945,320 elapsed=191.6s

  [13292/17668] intraday_5623.csv.gz  in=394,091,028 out=103,945,320 elapsed=191.6s

  [13293/17668] intraday_5624.csv.gz  in=394,102,985 out=103,945,320 elapsed=191.6s

  [13294/17668] intraday_5625.csv.gz  in=394,114,099 out=103,945,320 elapsed=191.6s

  [13295/17668] intraday_5626.csv.gz  in=394,127,726 out=103,945,320 elapsed=191.6s

  [13296/17668] intraday_5627.csv.gz  in=394,143,734 out=103,945,320 elapsed=191.6s

  [13297/17668] intraday_5628.csv.gz  in=394,155,677 out=103,945,320 elapsed=191.6s

  [13298/17668] intraday_5630.csv.gz  in=394,168,692 out=103,945,320 elapsed=191.6s

  [13299/17668] intraday_5629.csv.gz  in=394,181,901 out=103,945,320 elapsed=191.6s

  [13300/17668] intraday_5631.csv.gz  in=394,195,450 out=103,945,320 elapsed=191.7s

  [13301/17668] intraday_5632.csv.gz  in=394,209,756 out=103,945,320 elapsed=191.7s

  [13302/17668] intraday_5633.csv.gz  in=394,222,158 out=103,945,320 elapsed=191.7s

  [13303/17668] intraday_5635.csv.gz  in=394,233,711 out=103,945,320 elapsed=191.7s

  [13304/17668] intraday_5634.csv.gz  in=394,246,691 out=103,945,320 elapsed=191.7s

  [13305/17668] intraday_5638.csv.gz  in=394,259,404 out=103,945,320 elapsed=191.7s

  [13306/17668] intraday_5636.csv.gz  in=394,273,392 out=103,945,320 elapsed=191.7s

  [13307/17668] intraday_5637.csv.gz  in=394,301,102 out=103,945,320 elapsed=191.7s

  [13308/17668] intraday_5639.csv.gz  in=394,313,079 out=103,945,320 elapsed=191.7s

  [13309/17668] intraday_5640.csv.gz  in=394,327,695 out=103,945,320 elapsed=191.8s

  [13310/17668] intraday_5641.csv.gz  in=394,338,641 out=103,945,320 elapsed=191.8s

  [13311/17668] intraday_5643.csv.gz  in=394,355,049 out=103,945,320 elapsed=191.8s

  [13312/17668] intraday_5642.csv.gz  in=394,367,417 out=103,945,320 elapsed=191.8s

  [13313/17668] intraday_5644.csv.gz  in=394,378,114 out=103,945,320 elapsed=191.8s

  [13314/17668] intraday_5645.csv.gz  in=394,391,819 out=103,945,320 elapsed=191.8s

  [13315/17668] intraday_5646.csv.gz  in=394,407,752 out=103,945,320 elapsed=191.8s

  [13316/17668] intraday_5647.csv.gz  in=394,422,691 out=103,945,320 elapsed=191.8s

  [13317/17668] intraday_5650.csv.gz  in=394,436,132 out=103,945,320 elapsed=191.8s

  [13318/17668] intraday_5649.csv.gz  in=394,449,278 out=103,945,320 elapsed=191.9s

  [13319/17668] intraday_5648.csv.gz  in=394,461,377 out=103,945,320 elapsed=191.9s

  [13320/17668] intraday_5651.csv.gz  in=394,474,164 out=103,945,320 elapsed=191.9s

  [13321/17668] intraday_5652.csv.gz  in=394,489,913 out=103,945,320 elapsed=191.9s

  [13322/17668] intraday_5653.csv.gz  in=394,502,794 out=103,945,320 elapsed=191.9s

  [13323/17668] intraday_5655.csv.gz  in=394,518,370 out=103,945,320 elapsed=191.9s

  [13324/17668] intraday_5654.csv.gz  in=394,531,694 out=103,945,320 elapsed=191.9s

  [13325/17668] intraday_5656.csv.gz  in=394,545,040 out=103,945,320 elapsed=191.9s

  [13326/17668] intraday_5657.csv.gz  in=394,557,053 out=103,945,320 elapsed=191.9s

  [13327/17668] intraday_5659.csv.gz  in=394,571,107 out=103,945,320 elapsed=191.9s

  [13328/17668] intraday_5658.csv.gz  in=394,582,226 out=103,945,320 elapsed=191.9s

  [13329/17668] intraday_5660.csv.gz  in=394,593,368 out=103,945,320 elapsed=191.9s

  [13330/17668] intraday_5661.csv.gz  in=394,606,688 out=103,945,320 elapsed=191.9s

  [13331/17668] intraday_5662.csv.gz  in=394,618,856 out=103,945,320 elapsed=192.0s

  [13332/17668] intraday_5665.csv.gz  in=394,631,454 out=103,945,320 elapsed=192.0s

  [13333/17668] intraday_5663.csv.gz  in=394,648,325 out=103,945,320 elapsed=192.0s

  [13334/17668] intraday_5664.csv.gz  in=394,660,570 out=103,945,320 elapsed=192.0s

  [13335/17668] intraday_5666.csv.gz  in=394,672,515 out=103,945,320 elapsed=192.0s

  [13336/17668] intraday_5667.csv.gz  in=394,684,925 out=103,945,320 elapsed=192.0s

  [13337/17668] intraday_5668.csv.gz  in=394,696,514 out=103,945,320 elapsed=192.0s

  [13338/17668] intraday_5669.csv.gz  in=394,710,202 out=103,945,320 elapsed=192.0s

  [13339/17668] intraday_5670.csv.gz  in=394,724,207 out=103,945,320 elapsed=192.0s

  [13340/17668] intraday_5671.csv.gz  in=394,739,745 out=103,945,320 elapsed=192.1s

  [13341/17668] intraday_5672.csv.gz  in=394,753,556 out=103,945,320 elapsed=192.1s

  [13342/17668] intraday_5673.csv.gz  in=394,764,533 out=103,945,320 elapsed=192.1s

  [13343/17668] intraday_5674.csv.gz  in=394,776,326 out=103,945,320 elapsed=192.1s

  [13344/17668] intraday_5676.csv.gz  in=394,788,536 out=103,945,320 elapsed=192.1s

  [13345/17668] intraday_5678.csv.gz  in=394,795,915 out=103,945,320 elapsed=192.1s

  [13346/17668] intraday_5675.csv.gz  in=394,809,531 out=103,945,320 elapsed=192.1s

  [13347/17668] intraday_5677.csv.gz  in=394,835,229 out=103,945,320 elapsed=192.1s

  [13348/17668] intraday_5679.csv.gz  in=394,846,440 out=103,945,320 elapsed=192.1s

  [13349/17668] intraday_5680.csv.gz  in=394,854,145 out=103,945,320 elapsed=192.2s

  [13350/17668] intraday_5681.csv.gz  in=394,869,641 out=103,945,320 elapsed=192.2s

  [13351/17668] intraday_5682.csv.gz  in=394,882,772 out=103,945,320 elapsed=192.2s

  [13352/17668] intraday_5683.csv.gz  in=394,895,010 out=103,945,320 elapsed=192.2s

  [13353/17668] intraday_5684.csv.gz  in=394,905,593 out=103,945,320 elapsed=192.2s

  [13354/17668] intraday_5685.csv.gz  in=394,917,978 out=103,945,320 elapsed=192.2s

  [13355/17668] intraday_5686.csv.gz  in=394,933,385 out=103,945,320 elapsed=192.2s

  [13356/17668] intraday_5687.csv.gz  in=394,949,101 out=103,945,320 elapsed=192.2s

  [13357/17668] intraday_5688.csv.gz  in=394,960,788 out=103,945,320 elapsed=192.2s

  [13358/17668] intraday_5689.csv.gz  in=394,974,423 out=103,945,320 elapsed=192.2s

  [13359/17668] intraday_5690.csv.gz  in=394,988,513 out=103,945,320 elapsed=192.2s

  [13360/17668] intraday_5691.csv.gz  in=395,001,191 out=103,945,320 elapsed=192.2s

  [13361/17668] intraday_5692.csv.gz  in=395,014,625 out=103,945,320 elapsed=192.3s

  [13362/17668] intraday_5695.csv.gz  in=395,025,285 out=103,945,320 elapsed=192.3s

  [13363/17668] intraday_5694.csv.gz  in=395,036,966 out=103,945,320 elapsed=192.3s

  [13364/17668] intraday_5693.csv.gz  in=395,051,148 out=103,945,320 elapsed=192.3s

  [13365/17668] intraday_5696.csv.gz  in=395,060,757 out=103,945,320 elapsed=192.3s

  [13366/17668] intraday_5697.csv.gz  in=395,074,537 out=103,945,320 elapsed=192.3s

  [13367/17668] intraday_5700.csv.gz  in=395,086,597 out=103,945,320 elapsed=192.3s

  [13368/17668] intraday_5698.csv.gz  in=395,099,548 out=103,945,320 elapsed=192.3s

  [13369/17668] intraday_5699.csv.gz  in=395,112,920 out=103,945,320 elapsed=192.3s

  [13370/17668] intraday_5703.csv.gz  in=395,126,048 out=103,945,320 elapsed=192.3s

  [13371/17668] intraday_5701.csv.gz  in=395,137,905 out=103,945,320 elapsed=192.3s

  [13372/17668] intraday_5702.csv.gz  in=395,150,863 out=103,945,320 elapsed=192.3s

  [13373/17668] intraday_5704.csv.gz  in=395,163,717 out=103,945,320 elapsed=192.4s

  [13374/17668] intraday_5706.csv.gz  in=395,174,580 out=103,945,320 elapsed=192.4s

  [13375/17668] intraday_5705.csv.gz  in=395,187,586 out=103,945,320 elapsed=192.4s

  [13376/17668] intraday_5707.csv.gz  in=395,199,476 out=103,945,320 elapsed=192.4s

  [13377/17668] intraday_5708.csv.gz  in=395,211,511 out=103,945,320 elapsed=192.4s

  [13378/17668] intraday_5709.csv.gz  in=395,225,743 out=103,945,320 elapsed=192.4s

  [13379/17668] intraday_5710.csv.gz  in=395,240,771 out=103,945,320 elapsed=192.4s

  [13380/17668] intraday_5711.csv.gz  in=395,256,191 out=103,945,320 elapsed=192.4s

  [13381/17668] intraday_5712.csv.gz  in=395,272,481 out=103,945,320 elapsed=192.4s

  [13382/17668] intraday_5713.csv.gz  in=395,284,505 out=103,945,320 elapsed=192.5s

  [13383/17668] intraday_5716.csv.gz  in=395,294,018 out=103,945,320 elapsed=192.5s

  [13384/17668] intraday_5714.csv.gz  in=395,306,040 out=103,945,320 elapsed=192.5s

  [13385/17668] intraday_5717.csv.gz  in=395,319,798 out=103,945,320 elapsed=192.5s

  [13386/17668] intraday_5715.csv.gz  in=395,351,779 out=103,945,320 elapsed=192.5s

  [13387/17668] intraday_5718.csv.gz  in=395,362,658 out=103,945,320 elapsed=192.5s

  [13388/17668] intraday_5719.csv.gz  in=395,372,964 out=103,945,320 elapsed=192.5s

  [13389/17668] intraday_5720.csv.gz  in=395,384,065 out=103,945,320 elapsed=192.5s

  [13390/17668] intraday_5721.csv.gz  in=395,396,603 out=103,945,320 elapsed=192.5s

  [13391/17668] intraday_5722.csv.gz  in=395,409,968 out=103,945,320 elapsed=192.5s

  [13392/17668] intraday_5724.csv.gz  in=395,423,445 out=103,945,320 elapsed=192.6s

  [13393/17668] intraday_5723.csv.gz  in=395,435,057 out=103,945,320 elapsed=192.6s

  [13394/17668] intraday_5725.csv.gz  in=395,447,647 out=103,945,320 elapsed=192.6s

  [13395/17668] intraday_5726.csv.gz  in=395,459,609 out=103,945,320 elapsed=192.6s

  [13396/17668] intraday_5727.csv.gz  in=395,471,016 out=103,945,320 elapsed=192.6s

  [13397/17668] intraday_5728.csv.gz  in=395,483,316 out=103,945,320 elapsed=192.6s

  [13398/17668] intraday_5729.csv.gz  in=395,493,864 out=103,945,320 elapsed=192.6s

  [13399/17668] intraday_5730.csv.gz  in=395,507,548 out=103,945,320 elapsed=192.6s

  [13400/17668] intraday_5731.csv.gz  in=395,517,893 out=103,945,320 elapsed=192.6s

  [13401/17668] intraday_5733.csv.gz  in=395,528,993 out=103,945,320 elapsed=192.6s

  [13402/17668] intraday_5734.csv.gz  in=395,539,611 out=103,945,320 elapsed=192.7s

  [13403/17668] intraday_5732.csv.gz  in=395,554,824 out=103,945,320 elapsed=192.7s

  [13404/17668] intraday_5736.csv.gz  in=395,567,834 out=103,945,320 elapsed=192.7s

  [13405/17668] intraday_5735.csv.gz  in=395,582,305 out=103,945,320 elapsed=192.7s

  [13406/17668] intraday_5737.csv.gz  in=395,595,572 out=103,945,320 elapsed=192.7s

  [13407/17668] intraday_5738.csv.gz  in=395,606,490 out=103,945,320 elapsed=192.7s

  [13408/17668] intraday_5739.csv.gz  in=395,619,619 out=103,945,320 elapsed=192.7s

  [13409/17668] intraday_5742.csv.gz  in=395,630,792 out=103,945,320 elapsed=192.7s

  [13410/17668] intraday_5741.csv.gz  in=395,643,875 out=103,945,320 elapsed=192.7s

  [13411/17668] intraday_5740.csv.gz  in=395,656,268 out=103,945,320 elapsed=192.7s

  [13412/17668] intraday_5743.csv.gz  in=395,670,694 out=103,945,320 elapsed=192.8s

  [13413/17668] intraday_5744.csv.gz  in=395,681,325 out=103,945,320 elapsed=192.8s

  [13414/17668] intraday_5745.csv.gz  in=395,697,163 out=103,945,320 elapsed=192.8s

  [13415/17668] intraday_5746.csv.gz  in=395,710,038 out=103,945,320 elapsed=192.8s

  [13416/17668] intraday_5747.csv.gz  in=395,723,527 out=103,945,320 elapsed=192.8s

  [13417/17668] intraday_5748.csv.gz  in=395,736,938 out=103,945,320 elapsed=192.8s

  [13418/17668] intraday_5750.csv.gz  in=395,748,549 out=103,945,320 elapsed=192.8s

  [13419/17668] intraday_5749.csv.gz  in=395,760,014 out=103,945,320 elapsed=192.8s

  [13420/17668] intraday_5751.csv.gz  in=395,771,973 out=103,945,320 elapsed=192.8s

  [13421/17668] intraday_5752.csv.gz  in=395,784,517 out=103,945,320 elapsed=192.8s

  [13422/17668] intraday_5753.csv.gz  in=395,797,484 out=103,945,320 elapsed=192.8s

  [13423/17668] intraday_5754.csv.gz  in=395,808,601 out=103,945,320 elapsed=192.8s

  [13424/17668] intraday_5755.csv.gz  in=395,820,186 out=103,945,320 elapsed=192.9s

  [13425/17668] intraday_5756.csv.gz  in=395,832,926 out=103,945,320 elapsed=192.9s

  [13426/17668] intraday_5758.csv.gz  in=395,843,594 out=103,945,320 elapsed=192.9s

  [13427/17668] intraday_5757.csv.gz  in=395,856,691 out=103,945,320 elapsed=192.9s

  [13428/17668] intraday_5759.csv.gz  in=395,870,304 out=103,945,320 elapsed=192.9s

  [13429/17668] intraday_5760.csv.gz  in=395,880,343 out=103,945,320 elapsed=192.9s

  [13430/17668] intraday_5761.csv.gz  in=395,892,405 out=103,945,320 elapsed=192.9s

  [13431/17668] intraday_5763.csv.gz  in=395,906,493 out=103,945,320 elapsed=192.9s

  [13432/17668] intraday_5764.csv.gz  in=395,922,193 out=103,945,320 elapsed=192.9s

  [13433/17668] intraday_5762.csv.gz  in=395,934,785 out=103,945,320 elapsed=192.9s

  [13434/17668] intraday_5765.csv.gz  in=395,947,920 out=103,945,320 elapsed=192.9s

  [13435/17668] intraday_5767.csv.gz  in=395,959,402 out=103,945,320 elapsed=192.9s

  [13436/17668] intraday_5768.csv.gz  in=395,973,140 out=103,945,320 elapsed=193.0s

  [13437/17668] intraday_5766.csv.gz  in=395,984,629 out=103,945,320 elapsed=193.0s

  [13438/17668] intraday_5769.csv.gz  in=396,001,255 out=103,945,320 elapsed=193.0s

  [13439/17668] intraday_5770.csv.gz  in=396,013,897 out=103,945,320 elapsed=193.0s

  [13440/17668] intraday_5771.csv.gz  in=396,030,497 out=103,945,320 elapsed=193.0s

  [13441/17668] intraday_5773.csv.gz  in=396,043,977 out=103,945,320 elapsed=193.0s

  [13442/17668] intraday_5772.csv.gz  in=396,056,762 out=103,945,320 elapsed=193.0s

  [13443/17668] intraday_5774.csv.gz  in=396,070,266 out=103,945,320 elapsed=193.0s

  [13444/17668] intraday_5775.csv.gz  in=396,082,620 out=103,945,320 elapsed=193.0s

  [13445/17668] intraday_5777.csv.gz  in=396,095,590 out=103,945,320 elapsed=193.1s

  [13446/17668] intraday_5776.csv.gz  in=396,107,704 out=103,945,320 elapsed=193.1s

  [13447/17668] intraday_5778.csv.gz  in=396,119,884 out=103,945,320 elapsed=193.1s

  [13448/17668] intraday_5780.csv.gz  in=396,131,682 out=103,945,320 elapsed=193.1s

  [13449/17668] intraday_5779.csv.gz  in=396,145,591 out=103,945,320 elapsed=193.1s

  [13450/17668] intraday_5781.csv.gz  in=396,158,698 out=103,945,320 elapsed=193.1s

  [13451/17668] intraday_5782.csv.gz  in=396,177,589 out=103,945,320 elapsed=193.1s

  [13452/17668] intraday_5783.csv.gz  in=396,190,283 out=103,945,320 elapsed=193.1s

  [13453/17668] intraday_5784.csv.gz  in=396,203,109 out=103,945,320 elapsed=193.1s

  [13454/17668] intraday_5785.csv.gz  in=396,218,859 out=103,945,320 elapsed=193.1s

  [13455/17668] intraday_5786.csv.gz  in=396,230,063 out=103,945,320 elapsed=193.2s

  [13456/17668] intraday_5787.csv.gz  in=396,243,823 out=103,945,320 elapsed=193.2s

  [13457/17668] intraday_5788.csv.gz  in=396,258,336 out=103,945,320 elapsed=193.2s

  [13458/17668] intraday_5789.csv.gz  in=396,273,902 out=103,945,320 elapsed=193.2s

  [13459/17668] intraday_5791.csv.gz  in=396,286,236 out=103,945,320 elapsed=193.2s

  [13460/17668] intraday_5790.csv.gz  in=396,303,896 out=103,945,320 elapsed=193.2s

  [13461/17668] intraday_5792.csv.gz  in=396,317,529 out=103,945,320 elapsed=193.2s

  [13462/17668] intraday_5794.csv.gz  in=396,331,310 out=103,945,320 elapsed=193.2s

  [13463/17668] intraday_5793.csv.gz  in=396,344,041 out=103,945,320 elapsed=193.2s

  [13464/17668] intraday_5796.csv.gz  in=396,358,019 out=103,945,320 elapsed=193.2s

  [13465/17668] intraday_5795.csv.gz  in=396,372,723 out=103,945,320 elapsed=193.3s

  [13466/17668] intraday_5797.csv.gz  in=396,387,557 out=103,945,320 elapsed=193.3s

  [13467/17668] intraday_5798.csv.gz  in=396,401,144 out=103,945,320 elapsed=193.3s

  [13468/17668] intraday_5800.csv.gz  in=396,413,321 out=103,945,320 elapsed=193.3s

  [13469/17668] intraday_5799.csv.gz  in=396,425,569 out=103,945,320 elapsed=193.3s

  [13470/17668] intraday_5801.csv.gz  in=396,438,607 out=103,945,320 elapsed=193.3s

  [13471/17668] intraday_5802.csv.gz  in=396,449,694 out=103,945,320 elapsed=193.3s

  [13472/17668] intraday_5803.csv.gz  in=396,462,639 out=103,945,320 elapsed=193.3s

  [13473/17668] intraday_5805.csv.gz  in=396,477,216 out=103,945,320 elapsed=193.3s

  [13474/17668] intraday_5804.csv.gz  in=396,489,651 out=103,945,320 elapsed=193.3s

  [13475/17668] intraday_5806.csv.gz  in=396,503,355 out=103,945,320 elapsed=193.3s

  [13476/17668] intraday_5808.csv.gz  in=396,514,869 out=103,945,320 elapsed=193.4s

  [13477/17668] intraday_5807.csv.gz  in=396,527,053 out=103,945,320 elapsed=193.4s

  [13478/17668] intraday_5809.csv.gz  in=396,540,763 out=103,945,320 elapsed=193.4s

  [13479/17668] intraday_5810.csv.gz  in=396,552,319 out=103,945,320 elapsed=193.4s

  [13480/17668] intraday_5811.csv.gz  in=396,564,551 out=103,945,320 elapsed=193.4s

  [13481/17668] intraday_5812.csv.gz  in=396,580,100 out=103,945,320 elapsed=193.4s

  [13482/17668] intraday_5813.csv.gz  in=396,594,307 out=103,945,320 elapsed=193.4s

  [13483/17668] intraday_5814.csv.gz  in=396,609,046 out=103,945,320 elapsed=193.4s

  [13484/17668] intraday_5816.csv.gz  in=396,620,464 out=103,945,320 elapsed=193.4s

  [13485/17668] intraday_5815.csv.gz  in=396,633,149 out=103,945,320 elapsed=193.4s

  [13486/17668] intraday_5818.csv.gz  in=396,644,066 out=103,945,320 elapsed=193.5s

  [13487/17668] intraday_5817.csv.gz  in=396,657,864 out=103,945,320 elapsed=193.5s

  [13488/17668] intraday_5820.csv.gz  in=396,665,310 out=103,945,320 elapsed=193.5s

  [13489/17668] intraday_5819.csv.gz  in=396,679,771 out=103,945,320 elapsed=193.5s

  [13490/17668] intraday_5821.csv.gz  in=396,688,904 out=103,945,320 elapsed=193.5s

  [13491/17668] intraday_5822.csv.gz  in=396,699,174 out=103,945,320 elapsed=193.5s

  [13492/17668] intraday_5823.csv.gz  in=396,715,210 out=103,945,320 elapsed=193.5s

  [13493/17668] intraday_5824.csv.gz  in=396,728,618 out=103,945,320 elapsed=193.5s

  [13494/17668] intraday_5825.csv.gz  in=396,740,279 out=103,945,320 elapsed=193.5s

  [13495/17668] intraday_5826.csv.gz  in=396,751,018 out=103,945,320 elapsed=193.5s

  [13496/17668] intraday_5828.csv.gz  in=396,766,812 out=103,945,320 elapsed=193.6s

  [13497/17668] intraday_5827.csv.gz  in=396,780,287 out=103,945,320 elapsed=193.6s

  [13498/17668] intraday_5829.csv.gz  in=396,794,384 out=103,945,320 elapsed=193.6s

  [13499/17668] intraday_5830.csv.gz  in=396,805,976 out=103,945,320 elapsed=193.6s

  [13500/17668] intraday_5831.csv.gz  in=396,819,329 out=103,945,320 elapsed=193.6s

  [13501/17668] intraday_5832.csv.gz  in=396,832,800 out=103,945,320 elapsed=193.6s

  [13502/17668] intraday_5834.csv.gz  in=396,846,483 out=103,945,320 elapsed=193.6s

  [13503/17668] intraday_5833.csv.gz  in=396,860,959 out=103,945,320 elapsed=193.6s

  [13504/17668] intraday_5836.csv.gz  in=396,872,932 out=103,945,320 elapsed=193.6s

  [13505/17668] intraday_5835.csv.gz  in=396,885,048 out=103,945,320 elapsed=193.6s

  [13506/17668] intraday_5837.csv.gz  in=396,895,096 out=103,945,320 elapsed=193.6s

  [13507/17668] intraday_5838.csv.gz  in=396,911,651 out=103,945,320 elapsed=193.6s

  [13508/17668] intraday_5839.csv.gz  in=396,925,646 out=103,945,320 elapsed=193.6s

  [13509/17668] intraday_5840.csv.gz  in=396,938,890 out=103,945,320 elapsed=193.7s

  [13510/17668] intraday_5842.csv.gz  in=396,950,232 out=103,945,320 elapsed=193.7s

  [13511/17668] intraday_5841.csv.gz  in=396,968,165 out=103,945,320 elapsed=193.7s

  [13512/17668] intraday_5843.csv.gz  in=396,980,551 out=103,945,320 elapsed=193.7s

  [13513/17668] intraday_5844.csv.gz  in=396,993,818 out=103,945,320 elapsed=193.7s

  [13514/17668] intraday_5845.csv.gz  in=397,006,329 out=103,945,320 elapsed=193.7s

  [13515/17668] intraday_5846.csv.gz  in=397,018,485 out=103,945,320 elapsed=193.7s

  [13516/17668] intraday_5847.csv.gz  in=397,031,357 out=103,945,320 elapsed=193.7s

  [13517/17668] intraday_5848.csv.gz  in=397,042,412 out=103,945,320 elapsed=193.7s

  [13518/17668] intraday_5849.csv.gz  in=397,054,152 out=103,945,320 elapsed=193.7s

  [13519/17668] intraday_5850.csv.gz  in=397,066,064 out=103,945,320 elapsed=193.7s

  [13520/17668] intraday_5851.csv.gz  in=397,079,202 out=103,945,320 elapsed=193.8s

  [13521/17668] intraday_5852.csv.gz  in=397,093,177 out=103,945,320 elapsed=193.8s

  [13522/17668] intraday_5854.csv.gz  in=397,105,757 out=103,945,320 elapsed=193.8s

  [13523/17668] intraday_5853.csv.gz  in=397,120,906 out=103,945,320 elapsed=193.8s

  [13524/17668] intraday_5855.csv.gz  in=397,133,026 out=103,945,320 elapsed=193.8s

  [13525/17668] intraday_5856.csv.gz  in=397,145,422 out=103,945,320 elapsed=193.8s

  [13526/17668] intraday_5857.csv.gz  in=397,159,510 out=103,945,320 elapsed=193.8s

  [13527/17668] intraday_5858.csv.gz  in=397,170,035 out=103,945,320 elapsed=193.8s

  [13528/17668] intraday_5859.csv.gz  in=397,182,192 out=103,945,320 elapsed=193.8s

  [13529/17668] intraday_5860.csv.gz  in=397,193,761 out=103,945,320 elapsed=193.8s

  [13530/17668] intraday_5861.csv.gz  in=397,204,514 out=103,945,320 elapsed=193.9s

  [13531/17668] intraday_5862.csv.gz  in=397,215,562 out=103,945,320 elapsed=193.9s

  [13532/17668] intraday_5863.csv.gz  in=397,228,309 out=103,945,320 elapsed=193.9s

  [13533/17668] intraday_5864.csv.gz  in=397,240,207 out=103,945,320 elapsed=193.9s

  [13534/17668] intraday_5865.csv.gz  in=397,252,966 out=103,945,320 elapsed=193.9s

  [13535/17668] intraday_5866.csv.gz  in=397,266,429 out=103,945,320 elapsed=193.9s

  [13536/17668] intraday_5867.csv.gz  in=397,278,917 out=103,945,320 elapsed=193.9s

  [13537/17668] intraday_5868.csv.gz  in=397,291,138 out=103,945,320 elapsed=193.9s

  [13538/17668] intraday_5869.csv.gz  in=397,301,834 out=103,945,320 elapsed=193.9s

  [13539/17668] intraday_5871.csv.gz  in=397,313,356 out=103,945,320 elapsed=193.9s

  [13540/17668] intraday_5870.csv.gz  in=397,324,909 out=103,945,320 elapsed=193.9s

  [13541/17668] intraday_5872.csv.gz  in=397,335,930 out=103,945,320 elapsed=193.9s

  [13542/17668] intraday_5875.csv.gz  in=397,346,373 out=103,945,320 elapsed=194.0s

  [13543/17668] intraday_5873.csv.gz  in=397,357,388 out=103,945,320 elapsed=194.0s

  [13544/17668] intraday_5874.csv.gz  in=397,371,877 out=103,945,320 elapsed=194.0s

  [13545/17668] intraday_5876.csv.gz  in=397,382,634 out=103,945,320 elapsed=194.0s

  [13546/17668] intraday_5878.csv.gz  in=397,395,517 out=103,945,320 elapsed=194.0s

  [13547/17668] intraday_5879.csv.gz  in=397,408,505 out=103,945,320 elapsed=194.0s

  [13548/17668] intraday_5877.csv.gz  in=397,422,957 out=103,945,320 elapsed=194.0s

  [13549/17668] intraday_5880.csv.gz  in=397,434,718 out=103,945,320 elapsed=194.0s

  [13550/17668] intraday_5881.csv.gz  in=397,447,375 out=103,945,320 elapsed=194.0s

  [13551/17668] intraday_5883.csv.gz  in=397,461,138 out=103,945,320 elapsed=194.0s

  [13552/17668] intraday_5882.csv.gz  in=397,473,718 out=103,945,320 elapsed=194.1s

  [13553/17668] intraday_5884.csv.gz  in=397,484,960 out=103,945,320 elapsed=194.1s

  [13554/17668] intraday_5885.csv.gz  in=397,495,304 out=103,945,320 elapsed=194.1s

  [13555/17668] intraday_5886.csv.gz  in=397,506,661 out=103,945,320 elapsed=194.1s

  [13556/17668] intraday_5888.csv.gz  in=397,520,025 out=103,945,320 elapsed=194.1s

  [13557/17668] intraday_5889.csv.gz  in=397,533,472 out=103,945,320 elapsed=194.1s

  [13558/17668] intraday_5887.csv.gz  in=397,549,040 out=103,945,320 elapsed=194.1s

  [13559/17668] intraday_5893.csv.gz  in=397,560,643 out=103,945,320 elapsed=194.1s

  [13560/17668] intraday_5890.csv.gz  in=397,573,129 out=103,945,320 elapsed=194.1s

  [13561/17668] intraday_5891.csv.gz  in=397,601,644 out=103,945,320 elapsed=194.1s

  [13562/17668] intraday_5892.csv.gz  in=397,621,372 out=103,945,320 elapsed=194.2s

  [13563/17668] intraday_5895.csv.gz  in=397,634,947 out=103,945,320 elapsed=194.2s

  [13564/17668] intraday_5894.csv.gz  in=397,646,824 out=103,945,320 elapsed=194.2s

  [13565/17668] intraday_5897.csv.gz  in=397,658,526 out=103,945,320 elapsed=194.2s

  [13566/17668] intraday_5896.csv.gz  in=397,671,271 out=103,945,320 elapsed=194.2s

  [13567/17668] intraday_5899.csv.gz  in=397,684,995 out=103,945,320 elapsed=194.2s

  [13568/17668] intraday_5898.csv.gz  in=397,695,440 out=103,945,320 elapsed=194.2s

  [13569/17668] intraday_5900.csv.gz  in=397,706,496 out=103,945,320 elapsed=194.2s

  [13570/17668] intraday_5901.csv.gz  in=397,728,923 out=103,945,320 elapsed=194.2s

  [13571/17668] intraday_5902.csv.gz  in=397,738,266 out=103,945,320 elapsed=194.3s

  [13572/17668] intraday_5903.csv.gz  in=397,750,055 out=103,945,320 elapsed=194.3s

  [13573/17668] intraday_5904.csv.gz  in=397,762,573 out=103,945,320 elapsed=194.3s

  [13574/17668] intraday_5905.csv.gz  in=397,777,335 out=103,945,320 elapsed=194.3s

  [13575/17668] intraday_5906.csv.gz  in=397,792,102 out=103,945,320 elapsed=194.3s

  [13576/17668] intraday_5907.csv.gz  in=397,806,128 out=103,945,320 elapsed=194.3s

  [13577/17668] intraday_5908.csv.gz  in=397,817,549 out=103,945,320 elapsed=194.3s

  [13578/17668] intraday_5910.csv.gz  in=397,831,088 out=103,945,320 elapsed=194.3s

  [13579/17668] intraday_5909.csv.gz  in=397,843,415 out=103,945,320 elapsed=194.3s

  [13580/17668] intraday_5912.csv.gz  in=397,856,531 out=103,945,320 elapsed=194.3s

  [13581/17668] intraday_5911.csv.gz  in=397,872,949 out=103,945,320 elapsed=194.3s

  [13582/17668] intraday_5913.csv.gz  in=397,886,107 out=103,945,320 elapsed=194.3s

  [13583/17668] intraday_5914.csv.gz  in=397,899,296 out=103,945,320 elapsed=194.3s

  [13584/17668] intraday_5915.csv.gz  in=397,913,813 out=103,945,320 elapsed=194.4s

  [13585/17668] intraday_5916.csv.gz  in=397,927,314 out=103,945,320 elapsed=194.4s

  [13586/17668] intraday_5918.csv.gz  in=397,939,766 out=103,945,320 elapsed=194.4s

  [13587/17668] intraday_5917.csv.gz  in=397,954,959 out=103,945,320 elapsed=194.4s

  [13588/17668] intraday_5919.csv.gz  in=397,967,903 out=103,945,320 elapsed=194.4s

  [13589/17668] intraday_5920.csv.gz  in=397,979,875 out=103,945,320 elapsed=194.4s

  [13590/17668] intraday_5922.csv.gz  in=397,992,054 out=103,945,320 elapsed=194.4s

  [13591/17668] intraday_5921.csv.gz  in=398,006,598 out=103,945,320 elapsed=194.4s

  [13592/17668] intraday_5924.csv.gz  in=398,019,718 out=103,945,320 elapsed=194.4s

  [13593/17668] intraday_5923.csv.gz  in=398,033,932 out=103,945,320 elapsed=194.4s

  [13594/17668] intraday_5926.csv.gz  in=398,051,127 out=103,945,320 elapsed=194.5s

  [13595/17668] intraday_5925.csv.gz  in=398,064,635 out=103,945,320 elapsed=194.5s

  [13596/17668] intraday_5927.csv.gz  in=398,079,271 out=103,945,320 elapsed=194.5s

  [13597/17668] intraday_5928.csv.gz  in=398,092,905 out=103,945,320 elapsed=194.5s

  [13598/17668] intraday_5930.csv.gz  in=398,106,509 out=103,945,320 elapsed=194.5s

  [13599/17668] intraday_5929.csv.gz  in=398,119,125 out=103,945,320 elapsed=194.5s

  [13600/17668] intraday_5931.csv.gz  in=398,136,544 out=103,945,320 elapsed=194.5s

  [13601/17668] intraday_5932.csv.gz  in=398,148,321 out=103,945,320 elapsed=194.5s

  [13602/17668] intraday_5933.csv.gz  in=398,160,432 out=103,945,320 elapsed=194.5s

  [13603/17668] intraday_5934.csv.gz  in=398,173,817 out=103,945,320 elapsed=194.5s

  [13604/17668] intraday_5935.csv.gz  in=398,185,928 out=103,945,320 elapsed=194.6s

  [13605/17668] intraday_5936.csv.gz  in=398,199,875 out=103,945,320 elapsed=194.6s

  [13606/17668] intraday_5938.csv.gz  in=398,214,244 out=103,945,320 elapsed=194.6s

  [13607/17668] intraday_5937.csv.gz  in=398,228,690 out=103,945,320 elapsed=194.6s

  [13608/17668] intraday_5939.csv.gz  in=398,243,638 out=103,945,320 elapsed=194.6s

  [13609/17668] intraday_5940.csv.gz  in=398,258,005 out=103,945,320 elapsed=194.6s

  [13610/17668] intraday_5941.csv.gz  in=398,269,768 out=103,945,320 elapsed=194.6s

  [13611/17668] intraday_5942.csv.gz  in=398,282,641 out=103,945,320 elapsed=194.6s

  [13612/17668] intraday_5943.csv.gz  in=398,294,549 out=103,945,320 elapsed=194.6s

  [13613/17668] intraday_5945.csv.gz  in=398,306,598 out=103,945,320 elapsed=194.6s

  [13614/17668] intraday_5944.csv.gz  in=398,318,519 out=103,945,320 elapsed=194.6s

  [13615/17668] intraday_5946.csv.gz  in=398,331,032 out=103,945,320 elapsed=194.6s

  [13616/17668] intraday_5947.csv.gz  in=398,344,537 out=103,945,320 elapsed=194.7s

  [13617/17668] intraday_5949.csv.gz  in=398,355,918 out=103,945,320 elapsed=194.7s

  [13618/17668] intraday_5948.csv.gz  in=398,371,714 out=103,945,320 elapsed=194.7s

  [13619/17668] intraday_5951.csv.gz  in=398,385,615 out=103,945,320 elapsed=194.7s

  [13620/17668] intraday_5953.csv.gz  in=398,397,969 out=103,945,320 elapsed=194.7s

  [13621/17668] intraday_5950.csv.gz  in=398,409,755 out=103,945,320 elapsed=194.7s

  [13622/17668] intraday_5952.csv.gz  in=398,422,259 out=103,945,320 elapsed=194.7s

  [13623/17668] intraday_5954.csv.gz  in=398,439,294 out=103,945,320 elapsed=194.7s

  [13624/17668] intraday_5956.csv.gz  in=398,453,265 out=103,945,320 elapsed=194.7s

  [13625/17668] intraday_5955.csv.gz  in=398,466,978 out=103,945,320 elapsed=194.7s

  [13626/17668] intraday_5957.csv.gz  in=398,479,425 out=103,945,320 elapsed=194.8s

  [13627/17668] intraday_5958.csv.gz  in=398,491,437 out=103,945,320 elapsed=194.8s

  [13628/17668] intraday_5959.csv.gz  in=398,505,889 out=103,945,320 elapsed=194.8s

  [13629/17668] intraday_5961.csv.gz  in=398,519,900 out=103,945,320 elapsed=194.8s

  [13630/17668] intraday_5960.csv.gz  in=398,530,843 out=103,945,320 elapsed=194.8s

  [13631/17668] intraday_5962.csv.gz  in=398,539,711 out=103,945,320 elapsed=194.8s

  [13632/17668] intraday_5963.csv.gz  in=398,548,148 out=103,945,320 elapsed=194.8s

  [13633/17668] intraday_5964.csv.gz  in=398,558,962 out=103,945,320 elapsed=194.8s

  [13634/17668] intraday_5965.csv.gz  in=398,574,299 out=103,945,320 elapsed=194.8s

  [13635/17668] intraday_5967.csv.gz  in=398,587,818 out=103,945,320 elapsed=194.8s

  [13636/17668] intraday_5966.csv.gz  in=398,606,470 out=103,945,320 elapsed=194.9s

  [13637/17668] intraday_5968.csv.gz  in=398,616,580 out=103,945,320 elapsed=194.9s

  [13638/17668] intraday_5969.csv.gz  in=398,629,753 out=103,945,320 elapsed=194.9s

  [13639/17668] intraday_5971.csv.gz  in=398,644,303 out=103,945,320 elapsed=194.9s

  [13640/17668] intraday_5970.csv.gz  in=398,658,515 out=103,945,320 elapsed=194.9s

  [13641/17668] intraday_5972.csv.gz  in=398,668,803 out=103,945,320 elapsed=194.9s

  [13642/17668] intraday_5973.csv.gz  in=398,681,743 out=103,945,320 elapsed=194.9s

  [13643/17668] intraday_5976.csv.gz  in=398,694,346 out=103,945,320 elapsed=194.9s

  [13644/17668] intraday_5975.csv.gz  in=398,708,422 out=103,945,320 elapsed=194.9s

  [13645/17668] intraday_5974.csv.gz  in=398,722,879 out=103,945,320 elapsed=194.9s

  [13646/17668] intraday_5977.csv.gz  in=398,737,836 out=103,945,320 elapsed=194.9s

  [13647/17668] intraday_5979.csv.gz  in=398,748,731 out=103,945,320 elapsed=195.0s

  [13648/17668] intraday_5978.csv.gz  in=398,760,832 out=103,945,320 elapsed=195.0s

  [13649/17668] intraday_5980.csv.gz  in=398,769,768 out=103,945,320 elapsed=195.0s

  [13650/17668] intraday_5981.csv.gz  in=398,783,823 out=103,945,320 elapsed=195.0s

  [13651/17668] intraday_5982.csv.gz  in=398,796,604 out=103,945,320 elapsed=195.0s

  [13652/17668] intraday_5983.csv.gz  in=398,806,691 out=103,945,320 elapsed=195.0s

  [13653/17668] intraday_5984.csv.gz  in=398,825,371 out=103,945,320 elapsed=195.0s

  [13654/17668] intraday_5985.csv.gz  in=398,838,208 out=103,945,320 elapsed=195.0s

  [13655/17668] intraday_5986.csv.gz  in=398,851,541 out=103,945,320 elapsed=195.0s

  [13656/17668] intraday_5987.csv.gz  in=398,867,408 out=103,945,320 elapsed=195.1s

  [13657/17668] intraday_5989.csv.gz  in=398,879,400 out=103,945,320 elapsed=195.1s

  [13658/17668] intraday_5990.csv.gz  in=398,891,041 out=103,945,320 elapsed=195.1s

  [13659/17668] intraday_5988.csv.gz  in=398,903,969 out=103,945,320 elapsed=195.1s

  [13660/17668] intraday_5991.csv.gz  in=398,914,840 out=103,945,320 elapsed=195.1s

  [13661/17668] intraday_5992.csv.gz  in=398,927,135 out=103,945,320 elapsed=195.1s

  [13662/17668] intraday_5994.csv.gz  in=398,938,900 out=103,945,320 elapsed=195.1s

  [13663/17668] intraday_5993.csv.gz  in=398,950,921 out=103,945,320 elapsed=195.1s

  [13664/17668] intraday_5995.csv.gz  in=398,966,754 out=103,945,320 elapsed=195.1s

  [13665/17668] intraday_5996.csv.gz  in=398,978,696 out=103,945,320 elapsed=195.1s

  [13666/17668] intraday_5997.csv.gz  in=398,989,618 out=103,945,320 elapsed=195.1s

  [13667/17668] intraday_5998.csv.gz  in=399,002,033 out=103,945,320 elapsed=195.1s

  [13668/17668] intraday_5999.csv.gz  in=399,014,711 out=103,945,320 elapsed=195.2s

  [13669/17668] intraday_6000.csv.gz  in=399,025,399 out=103,945,320 elapsed=195.2s

  [13670/17668] intraday_6002.csv.gz  in=399,034,490 out=103,945,320 elapsed=195.2s

  [13671/17668] intraday_6001.csv.gz  in=399,057,840 out=103,945,320 elapsed=195.2s

  [13672/17668] intraday_6003.csv.gz  in=399,069,668 out=103,945,320 elapsed=195.2s

  [13673/17668] intraday_6004.csv.gz  in=399,079,522 out=103,945,320 elapsed=195.2s

  [13674/17668] intraday_6006.csv.gz  in=399,092,555 out=103,945,320 elapsed=195.2s

  [13675/17668] intraday_6007.csv.gz  in=399,104,384 out=103,945,320 elapsed=195.2s

  [13676/17668] intraday_6005.csv.gz  in=399,115,623 out=103,945,320 elapsed=195.2s

  [13677/17668] intraday_6008.csv.gz  in=399,129,467 out=103,945,320 elapsed=195.2s

  [13678/17668] intraday_6009.csv.gz  in=399,148,705 out=103,945,320 elapsed=195.2s

  [13679/17668] intraday_6011.csv.gz  in=399,160,835 out=103,945,320 elapsed=195.2s

  [13680/17668] intraday_6010.csv.gz  in=399,171,429 out=103,945,320 elapsed=195.2s

  [13681/17668] intraday_6013.csv.gz  in=399,184,631 out=103,945,320 elapsed=195.3s

  [13682/17668] intraday_6014.csv.gz  in=399,197,302 out=103,945,320 elapsed=195.3s

  [13683/17668] intraday_6012.csv.gz  in=399,210,731 out=103,945,320 elapsed=195.3s

  [13684/17668] intraday_6015.csv.gz  in=399,222,317 out=103,945,320 elapsed=195.3s

  [13685/17668] intraday_6016.csv.gz  in=399,235,135 out=103,945,320 elapsed=195.3s

  [13686/17668] intraday_6017.csv.gz  in=399,247,554 out=103,945,320 elapsed=195.3s

  [13687/17668] intraday_6019.csv.gz  in=399,260,280 out=103,945,320 elapsed=195.3s

  [13688/17668] intraday_6018.csv.gz  in=399,271,844 out=103,945,320 elapsed=195.3s

  [13689/17668] intraday_6020.csv.gz  in=399,284,441 out=103,945,320 elapsed=195.3s

  [13690/17668] intraday_6022.csv.gz  in=399,297,608 out=103,945,320 elapsed=195.4s

  [13691/17668] intraday_6021.csv.gz  in=399,309,902 out=103,945,320 elapsed=195.4s

  [13692/17668] intraday_6023.csv.gz  in=399,335,771 out=103,945,320 elapsed=195.4s

  [13693/17668] intraday_6024.csv.gz  in=399,348,207 out=103,945,320 elapsed=195.4s

  [13694/17668] intraday_6025.csv.gz  in=399,359,967 out=103,945,320 elapsed=195.4s

  [13695/17668] intraday_6027.csv.gz  in=399,372,535 out=103,945,320 elapsed=195.4s

  [13696/17668] intraday_6026.csv.gz  in=399,385,582 out=103,945,320 elapsed=195.4s

  [13697/17668] intraday_6028.csv.gz  in=399,395,035 out=103,945,320 elapsed=195.4s

  [13698/17668] intraday_6029.csv.gz  in=399,409,520 out=103,945,320 elapsed=195.4s

  [13699/17668] intraday_6031.csv.gz  in=399,419,395 out=103,945,320 elapsed=195.5s

  [13700/17668] intraday_6030.csv.gz  in=399,435,454 out=103,945,320 elapsed=195.5s

  [13701/17668] intraday_6032.csv.gz  in=399,448,026 out=103,945,320 elapsed=195.5s

  [13702/17668] intraday_6033.csv.gz  in=399,460,423 out=103,945,320 elapsed=195.5s

  [13703/17668] intraday_6034.csv.gz  in=399,471,071 out=103,945,320 elapsed=195.5s

  [13704/17668] intraday_6035.csv.gz  in=399,482,885 out=103,945,320 elapsed=195.5s

  [13705/17668] intraday_6036.csv.gz  in=399,493,972 out=103,945,320 elapsed=195.5s

  [13706/17668] intraday_6039.csv.gz  in=399,507,050 out=103,945,320 elapsed=195.5s

  [13707/17668] intraday_6038.csv.gz  in=399,518,935 out=103,945,320 elapsed=195.5s

  [13708/17668] intraday_6037.csv.gz  in=399,532,558 out=103,945,320 elapsed=195.5s

  [13709/17668] intraday_6040.csv.gz  in=399,541,760 out=103,945,320 elapsed=195.5s

  [13710/17668] intraday_6041.csv.gz  in=399,554,195 out=103,945,320 elapsed=195.6s

  [13711/17668] intraday_6042.csv.gz  in=399,566,128 out=103,945,320 elapsed=195.6s

  [13712/17668] intraday_6043.csv.gz  in=399,576,484 out=103,945,320 elapsed=195.6s

  [13713/17668] intraday_6044.csv.gz  in=399,588,306 out=103,945,320 elapsed=195.6s

  [13714/17668] intraday_6045.csv.gz  in=399,597,397 out=103,945,320 elapsed=195.6s

  [13715/17668] intraday_6046.csv.gz  in=399,607,950 out=103,945,320 elapsed=195.6s

  [13716/17668] intraday_6047.csv.gz  in=399,622,045 out=103,945,320 elapsed=195.6s

  [13717/17668] intraday_6049.csv.gz  in=399,633,551 out=103,945,320 elapsed=195.6s

  [13718/17668] intraday_6048.csv.gz  in=399,651,136 out=103,945,320 elapsed=195.6s

  [13719/17668] intraday_6050.csv.gz  in=399,663,254 out=103,945,320 elapsed=195.6s

  [13720/17668] intraday_6051.csv.gz  in=399,673,566 out=103,945,320 elapsed=195.6s

  [13721/17668] intraday_6052.csv.gz  in=399,689,191 out=103,945,320 elapsed=195.7s

  [13722/17668] intraday_6053.csv.gz  in=399,700,453 out=103,945,320 elapsed=195.7s

  [13723/17668] intraday_6055.csv.gz  in=399,712,216 out=103,945,320 elapsed=195.7s

  [13724/17668] intraday_6054.csv.gz  in=399,727,997 out=103,945,320 elapsed=195.7s

  [13725/17668] intraday_6057.csv.gz  in=399,741,182 out=103,945,320 elapsed=195.7s

  [13726/17668] intraday_6056.csv.gz  in=399,753,884 out=103,945,320 elapsed=195.7s

  [13727/17668] intraday_6059.csv.gz  in=399,765,936 out=103,945,320 elapsed=195.7s

  [13728/17668] intraday_6060.csv.gz  in=399,778,663 out=103,945,320 elapsed=195.7s

  [13729/17668] intraday_6058.csv.gz  in=399,799,578 out=103,945,320 elapsed=195.7s

  [13730/17668] intraday_6061.csv.gz  in=399,812,739 out=103,945,320 elapsed=195.7s

  [13731/17668] intraday_6062.csv.gz  in=399,824,404 out=103,945,320 elapsed=195.8s

  [13732/17668] intraday_6064.csv.gz  in=399,837,178 out=103,945,320 elapsed=195.8s

  [13733/17668] intraday_6063.csv.gz  in=399,850,576 out=103,945,320 elapsed=195.8s

  [13734/17668] intraday_6065.csv.gz  in=399,863,373 out=103,945,320 elapsed=195.8s

  [13735/17668] intraday_6066.csv.gz  in=399,878,424 out=103,945,320 elapsed=195.8s

  [13736/17668] intraday_6068.csv.gz  in=399,888,811 out=103,945,320 elapsed=195.8s

  [13737/17668] intraday_6067.csv.gz  in=399,904,633 out=103,945,320 elapsed=195.8s

  [13738/17668] intraday_6070.csv.gz  in=399,923,026 out=103,945,320 elapsed=195.8s

  [13739/17668] intraday_6071.csv.gz  in=399,932,970 out=103,945,320 elapsed=195.9s

  [13740/17668] intraday_6069.csv.gz  in=399,945,030 out=103,945,320 elapsed=195.9s

  [13741/17668] intraday_6072.csv.gz  in=399,956,163 out=103,945,320 elapsed=195.9s

  [13742/17668] intraday_6074.csv.gz  in=399,969,539 out=103,945,320 elapsed=195.9s

  [13743/17668] intraday_6073.csv.gz  in=399,985,080 out=103,945,320 elapsed=195.9s

  [13744/17668] intraday_6075.csv.gz  in=399,998,412 out=103,945,320 elapsed=195.9s

  [13745/17668] intraday_6076.csv.gz  in=400,011,022 out=103,945,320 elapsed=195.9s

  [13746/17668] intraday_6077.csv.gz  in=400,023,182 out=103,945,320 elapsed=195.9s

  [13747/17668] intraday_6078.csv.gz  in=400,035,446 out=103,945,320 elapsed=195.9s

  [13748/17668] intraday_6079.csv.gz  in=400,050,162 out=103,945,320 elapsed=195.9s

  [13749/17668] intraday_6080.csv.gz  in=400,061,858 out=103,945,320 elapsed=195.9s

  [13750/17668] intraday_6081.csv.gz  in=400,075,885 out=103,945,320 elapsed=196.0s

  [13751/17668] intraday_6083.csv.gz  in=400,088,501 out=103,945,320 elapsed=196.0s

  [13752/17668] intraday_6084.csv.gz  in=400,099,563 out=103,945,320 elapsed=196.0s

  [13753/17668] intraday_6082.csv.gz  in=400,115,486 out=103,945,320 elapsed=196.0s

  [13754/17668] intraday_6085.csv.gz  in=400,126,866 out=103,945,320 elapsed=196.0s

  [13755/17668] intraday_6087.csv.gz  in=400,137,996 out=103,945,320 elapsed=196.0s

  [13756/17668] intraday_6086.csv.gz  in=400,151,455 out=103,945,320 elapsed=196.0s

  [13757/17668] intraday_6088.csv.gz  in=400,164,879 out=103,945,320 elapsed=196.0s

  [13758/17668] intraday_6090.csv.gz  in=400,180,621 out=103,945,320 elapsed=196.1s

  [13759/17668] intraday_6091.csv.gz  in=400,193,161 out=103,945,320 elapsed=196.1s

  [13760/17668] intraday_6089.csv.gz  in=400,211,166 out=103,945,320 elapsed=196.1s

  [13761/17668] intraday_6092.csv.gz  in=400,222,700 out=103,945,320 elapsed=196.1s

  [13762/17668] intraday_6094.csv.gz  in=400,234,331 out=103,945,320 elapsed=196.1s

  [13763/17668] intraday_6093.csv.gz  in=400,246,425 out=103,945,320 elapsed=196.1s

  [13764/17668] intraday_6095.csv.gz  in=400,258,751 out=103,945,320 elapsed=196.1s

  [13765/17668] intraday_6096.csv.gz  in=400,270,901 out=103,945,320 elapsed=196.1s

  [13766/17668] intraday_6098.csv.gz  in=400,284,886 out=103,945,320 elapsed=196.1s

  [13767/17668] intraday_6097.csv.gz  in=400,303,671 out=103,945,320 elapsed=196.1s

  [13768/17668] intraday_6100.csv.gz  in=400,315,869 out=103,945,320 elapsed=196.1s

  [13769/17668] intraday_6099.csv.gz  in=400,328,829 out=103,945,320 elapsed=196.1s

  [13770/17668] intraday_6102.csv.gz  in=400,342,215 out=103,945,320 elapsed=196.2s

  [13771/17668] intraday_6101.csv.gz  in=400,354,013 out=103,945,320 elapsed=196.2s

  [13772/17668] intraday_6103.csv.gz  in=400,365,050 out=103,945,320 elapsed=196.2s

  [13773/17668] intraday_6104.csv.gz  in=400,379,644 out=103,945,320 elapsed=196.2s

  [13774/17668] intraday_6105.csv.gz  in=400,387,977 out=103,945,320 elapsed=196.2s

  [13775/17668] intraday_6107.csv.gz  in=400,396,885 out=103,945,320 elapsed=196.2s

  [13776/17668] intraday_6106.csv.gz  in=400,406,119 out=103,945,320 elapsed=196.2s

  [13777/17668] intraday_6109.csv.gz  in=400,406,139 out=103,945,320 elapsed=196.2s

  [13778/17668] intraday_6108.csv.gz  in=400,406,217 out=103,945,320 elapsed=196.2s

  [13779/17668] intraday_6111.csv.gz  in=400,406,232 out=103,945,320 elapsed=196.2s

  [13780/17668] intraday_6110.csv.gz  in=400,406,249 out=103,945,320 elapsed=196.2s

  [13781/17668] intraday_6112.csv.gz  in=400,409,431 out=103,945,320 elapsed=196.2s

  [13782/17668] intraday_6113.csv.gz  in=400,413,061 out=103,945,320 elapsed=196.2s

  [13783/17668] intraday_6116.csv.gz  in=400,414,408 out=103,945,320 elapsed=196.3s

  [13784/17668] intraday_6114.csv.gz  in=400,426,747 out=103,945,320 elapsed=196.3s

  [13785/17668] intraday_6115.csv.gz  in=400,432,239 out=103,945,320 elapsed=196.3s

  [13786/17668] intraday_6117.csv.gz  in=400,433,178 out=103,945,320 elapsed=196.3s

  [13787/17668] intraday_6118.csv.gz  in=400,434,447 out=103,945,320 elapsed=196.3s

  [13788/17668] intraday_6120.csv.gz  in=400,435,802 out=103,945,320 elapsed=196.3s

  [13789/17668] intraday_6119.csv.gz  in=400,443,894 out=103,945,320 elapsed=196.3s

  [13790/17668] intraday_6121.csv.gz  in=400,444,215 out=103,945,320 elapsed=196.3s

  [13791/17668] intraday_6122.csv.gz  in=400,444,256 out=103,945,320 elapsed=196.3s

  [13792/17668] intraday_6124.csv.gz  in=400,444,277 out=103,945,320 elapsed=196.3s

  [13793/17668] intraday_6123.csv.gz  in=400,446,625 out=103,945,320 elapsed=196.3s

  [13794/17668] intraday_6126.csv.gz  in=400,446,739 out=103,945,320 elapsed=196.3s

  [13795/17668] intraday_6127.csv.gz  in=400,455,968 out=103,945,320 elapsed=196.3s

  [13796/17668] intraday_6125.csv.gz  in=400,456,518 out=103,945,320 elapsed=196.3s

  [13797/17668] intraday_6128.csv.gz  in=400,473,152 out=103,945,320 elapsed=196.4s

  [13798/17668] intraday_6129.csv.gz  in=400,485,969 out=103,945,320 elapsed=196.4s

  [13799/17668] intraday_6131.csv.gz  in=400,497,394 out=103,945,320 elapsed=196.4s

  [13800/17668] intraday_6130.csv.gz  in=400,511,735 out=103,945,320 elapsed=196.4s

  [13801/17668] intraday_6132.csv.gz  in=400,524,765 out=103,945,320 elapsed=196.4s

  [13802/17668] intraday_6134.csv.gz  in=400,541,704 out=103,945,320 elapsed=196.4s

  [13803/17668] intraday_6135.csv.gz  in=400,553,022 out=103,945,320 elapsed=196.4s

  [13804/17668] intraday_6133.csv.gz  in=400,568,207 out=103,945,320 elapsed=196.4s

  [13805/17668] intraday_6136.csv.gz  in=400,582,279 out=103,945,320 elapsed=196.4s

  [13806/17668] intraday_6139.csv.gz  in=400,595,683 out=103,945,320 elapsed=196.5s

  [13807/17668] intraday_6138.csv.gz  in=400,610,541 out=103,945,320 elapsed=196.5s

  [13808/17668] intraday_6140.csv.gz  in=400,623,379 out=103,945,320 elapsed=196.5s

  [13809/17668] intraday_6137.csv.gz  in=400,639,320 out=103,945,320 elapsed=196.5s

  [13810/17668] intraday_6141.csv.gz  in=400,651,822 out=103,945,320 elapsed=196.5s

  [13811/17668] intraday_6142.csv.gz  in=400,661,906 out=103,945,320 elapsed=196.5s

  [13812/17668] intraday_6143.csv.gz  in=400,670,863 out=103,945,320 elapsed=196.5s

  [13813/17668] intraday_6144.csv.gz  in=400,685,307 out=103,945,320 elapsed=196.5s

  [13814/17668] intraday_6146.csv.gz  in=400,696,392 out=103,945,320 elapsed=196.5s

  [13815/17668] intraday_6145.csv.gz  in=400,710,416 out=103,945,320 elapsed=196.5s

  [13816/17668] intraday_6147.csv.gz  in=400,722,738 out=103,945,320 elapsed=196.6s

  [13817/17668] intraday_6148.csv.gz  in=400,751,145 out=103,945,320 elapsed=196.6s

  [13818/17668] intraday_6150.csv.gz  in=400,764,766 out=103,945,320 elapsed=196.6s

  [13819/17668] intraday_6149.csv.gz  in=400,778,234 out=103,945,320 elapsed=196.6s

  [13820/17668] intraday_6151.csv.gz  in=400,791,561 out=103,945,320 elapsed=196.6s

  [13821/17668] intraday_6153.csv.gz  in=400,803,363 out=103,945,320 elapsed=196.6s

  [13822/17668] intraday_6152.csv.gz  in=400,816,232 out=103,945,320 elapsed=196.6s

  [13823/17668] intraday_6154.csv.gz  in=400,827,054 out=103,945,320 elapsed=196.6s

  [13824/17668] intraday_6155.csv.gz  in=400,839,417 out=103,945,320 elapsed=196.6s

  [13825/17668] intraday_6156.csv.gz  in=400,853,609 out=103,945,320 elapsed=196.6s

  [13826/17668] intraday_6157.csv.gz  in=400,869,060 out=103,945,320 elapsed=196.6s

  [13827/17668] intraday_6158.csv.gz  in=400,884,389 out=103,945,320 elapsed=196.6s

  [13828/17668] intraday_6159.csv.gz  in=400,895,706 out=103,945,320 elapsed=196.7s

  [13829/17668] intraday_6161.csv.gz  in=400,908,463 out=103,945,320 elapsed=196.7s

  [13830/17668] intraday_6160.csv.gz  in=400,920,248 out=103,945,320 elapsed=196.7s

  [13831/17668] intraday_6162.csv.gz  in=400,935,084 out=103,945,320 elapsed=196.7s

  [13832/17668] intraday_6165.csv.gz  in=400,945,949 out=103,945,320 elapsed=196.7s

  [13833/17668] intraday_6164.csv.gz  in=400,958,836 out=103,945,320 elapsed=196.7s

  [13834/17668] intraday_6163.csv.gz  in=400,970,209 out=103,945,320 elapsed=196.7s

  [13835/17668] intraday_6166.csv.gz  in=400,982,047 out=103,945,320 elapsed=196.7s

  [13836/17668] intraday_6167.csv.gz  in=400,992,816 out=103,945,320 elapsed=196.7s

  [13837/17668] intraday_6168.csv.gz  in=401,005,089 out=103,945,320 elapsed=196.7s

  [13838/17668] intraday_6170.csv.gz  in=401,017,420 out=103,945,320 elapsed=196.8s

  [13839/17668] intraday_6169.csv.gz  in=401,030,623 out=103,945,320 elapsed=196.8s

  [13840/17668] intraday_6172.csv.gz  in=401,043,624 out=103,945,320 elapsed=196.8s

  [13841/17668] intraday_6173.csv.gz  in=401,055,486 out=103,945,320 elapsed=196.8s

  [13842/17668] intraday_6171.csv.gz  in=401,068,997 out=103,945,320 elapsed=196.8s

  [13843/17668] intraday_6174.csv.gz  in=401,081,739 out=103,945,320 elapsed=196.8s

  [13844/17668] intraday_6175.csv.gz  in=401,094,421 out=103,945,320 elapsed=196.8s

  [13845/17668] intraday_6177.csv.gz  in=401,106,904 out=103,945,320 elapsed=196.8s

  [13846/17668] intraday_6176.csv.gz  in=401,117,672 out=103,945,320 elapsed=196.8s

  [13847/17668] intraday_6178.csv.gz  in=401,129,586 out=103,945,320 elapsed=196.8s

  [13848/17668] intraday_6179.csv.gz  in=401,143,195 out=103,945,320 elapsed=196.8s

  [13849/17668] intraday_6181.csv.gz  in=401,154,975 out=103,945,320 elapsed=196.9s

  [13850/17668] intraday_6182.csv.gz  in=401,169,424 out=103,945,320 elapsed=196.9s

  [13851/17668] intraday_6180.csv.gz  in=401,182,881 out=103,945,320 elapsed=196.9s

  [13852/17668] intraday_6183.csv.gz  in=401,195,845 out=103,945,320 elapsed=196.9s

  [13853/17668] intraday_6185.csv.gz  in=401,209,131 out=103,945,320 elapsed=196.9s

  [13854/17668] intraday_6184.csv.gz  in=401,221,895 out=103,945,320 elapsed=196.9s

  [13855/17668] intraday_6186.csv.gz  in=401,236,164 out=103,945,320 elapsed=196.9s

  [13856/17668] intraday_6187.csv.gz  in=401,249,977 out=103,945,320 elapsed=196.9s

  [13857/17668] intraday_6188.csv.gz  in=401,262,285 out=103,945,320 elapsed=196.9s

  [13858/17668] intraday_6189.csv.gz  in=401,274,863 out=103,945,320 elapsed=196.9s

  [13859/17668] intraday_6191.csv.gz  in=401,285,383 out=103,945,320 elapsed=196.9s

  [13860/17668] intraday_6190.csv.gz  in=401,297,705 out=103,945,320 elapsed=196.9s

  [13861/17668] intraday_6192.csv.gz  in=401,312,951 out=103,945,320 elapsed=197.0s

  [13862/17668] intraday_6193.csv.gz  in=401,327,868 out=103,945,320 elapsed=197.0s

  [13863/17668] intraday_6195.csv.gz  in=401,340,455 out=103,945,320 elapsed=197.0s

  [13864/17668] intraday_6194.csv.gz  in=401,353,099 out=103,945,320 elapsed=197.0s

  [13865/17668] intraday_6196.csv.gz  in=401,365,761 out=103,945,320 elapsed=197.0s

  [13866/17668] intraday_6197.csv.gz  in=401,376,166 out=103,945,320 elapsed=197.0s

  [13867/17668] intraday_6198.csv.gz  in=401,388,629 out=103,945,320 elapsed=197.0s

  [13868/17668] intraday_6199.csv.gz  in=401,401,521 out=103,945,320 elapsed=197.0s

  [13869/17668] intraday_6200.csv.gz  in=401,415,676 out=103,945,320 elapsed=197.0s

  [13870/17668] intraday_6202.csv.gz  in=401,429,169 out=103,945,320 elapsed=197.1s

  [13871/17668] intraday_6201.csv.gz  in=401,440,292 out=103,945,320 elapsed=197.1s

  [13872/17668] intraday_6203.csv.gz  in=401,450,645 out=103,945,320 elapsed=197.1s

  [13873/17668] intraday_6204.csv.gz  in=401,465,280 out=103,945,320 elapsed=197.1s

  [13874/17668] intraday_6205.csv.gz  in=401,476,579 out=103,945,320 elapsed=197.1s

  [13875/17668] intraday_6206.csv.gz  in=401,491,229 out=103,945,320 elapsed=197.1s

  [13876/17668] intraday_6208.csv.gz  in=401,502,761 out=103,945,320 elapsed=197.1s

  [13877/17668] intraday_6207.csv.gz  in=401,512,632 out=103,945,320 elapsed=197.1s

  [13878/17668] intraday_6209.csv.gz  in=401,524,995 out=103,945,320 elapsed=197.1s

  [13879/17668] intraday_6211.csv.gz  in=401,541,639 out=103,945,320 elapsed=197.2s

  [13880/17668] intraday_6210.csv.gz  in=401,557,815 out=103,945,320 elapsed=197.2s

  [13881/17668] intraday_6212.csv.gz  in=401,570,547 out=103,945,320 elapsed=197.2s

  [13882/17668] intraday_6213.csv.gz  in=401,582,914 out=103,945,320 elapsed=197.2s

  [13883/17668] intraday_6214.csv.gz  in=401,594,849 out=103,945,320 elapsed=197.2s

  [13884/17668] intraday_6215.csv.gz  in=401,609,058 out=103,945,320 elapsed=197.2s

  [13885/17668] intraday_6216.csv.gz  in=401,624,007 out=103,945,320 elapsed=197.2s

  [13886/17668] intraday_6217.csv.gz  in=401,638,220 out=103,945,320 elapsed=197.2s

  [13887/17668] intraday_6218.csv.gz  in=401,650,243 out=103,945,320 elapsed=197.2s

  [13888/17668] intraday_6219.csv.gz  in=401,664,551 out=103,945,320 elapsed=197.2s

  [13889/17668] intraday_6220.csv.gz  in=401,678,247 out=103,945,320 elapsed=197.2s

  [13890/17668] intraday_6221.csv.gz  in=401,692,018 out=103,945,320 elapsed=197.3s

  [13891/17668] intraday_6222.csv.gz  in=401,704,551 out=103,945,320 elapsed=197.3s

  [13892/17668] intraday_6223.csv.gz  in=401,717,656 out=103,945,320 elapsed=197.3s

  [13893/17668] intraday_6224.csv.gz  in=401,730,885 out=103,945,320 elapsed=197.3s

  [13894/17668] intraday_6225.csv.gz  in=401,744,313 out=103,945,320 elapsed=197.3s

  [13895/17668] intraday_6226.csv.gz  in=401,758,376 out=103,945,320 elapsed=197.3s

  [13896/17668] intraday_6228.csv.gz  in=401,769,879 out=103,945,320 elapsed=197.3s

  [13897/17668] intraday_6227.csv.gz  in=401,781,472 out=103,945,320 elapsed=197.3s

  [13898/17668] intraday_6229.csv.gz  in=401,798,986 out=103,945,320 elapsed=197.3s

  [13899/17668] intraday_6230.csv.gz  in=401,812,674 out=103,945,320 elapsed=197.3s

  [13900/17668] intraday_6232.csv.gz  in=401,827,348 out=103,945,320 elapsed=197.3s

  [13901/17668] intraday_6231.csv.gz  in=401,840,412 out=103,945,320 elapsed=197.3s

  [13902/17668] intraday_6234.csv.gz  in=401,853,795 out=103,945,320 elapsed=197.3s

  [13903/17668] intraday_6233.csv.gz  in=401,868,616 out=103,945,320 elapsed=197.4s

  [13904/17668] intraday_6235.csv.gz  in=401,882,182 out=103,945,320 elapsed=197.4s

  [13905/17668] intraday_6236.csv.gz  in=401,897,079 out=103,945,320 elapsed=197.4s

  [13906/17668] intraday_6238.csv.gz  in=401,908,714 out=103,945,320 elapsed=197.4s

  [13907/17668] intraday_6237.csv.gz  in=401,923,375 out=103,945,320 elapsed=197.4s

  [13908/17668] intraday_6239.csv.gz  in=401,938,727 out=103,945,320 elapsed=197.4s

  [13909/17668] intraday_6241.csv.gz  in=401,952,888 out=103,945,320 elapsed=197.4s

  [13910/17668] intraday_6242.csv.gz  in=401,967,990 out=103,945,320 elapsed=197.4s

  [13911/17668] intraday_6240.csv.gz  in=401,980,826 out=103,945,320 elapsed=197.4s

  [13912/17668] intraday_6243.csv.gz  in=401,996,132 out=103,945,320 elapsed=197.4s

  [13913/17668] intraday_6245.csv.gz  in=402,010,387 out=103,945,320 elapsed=197.5s

  [13914/17668] intraday_6247.csv.gz  in=402,022,818 out=103,945,320 elapsed=197.5s

  [13915/17668] intraday_6244.csv.gz  in=402,037,091 out=103,945,320 elapsed=197.5s

  [13916/17668] intraday_6246.csv.gz  in=402,049,649 out=103,945,320 elapsed=197.5s

  [13917/17668] intraday_6250.csv.gz  in=402,060,755 out=103,945,320 elapsed=197.5s

  [13918/17668] intraday_6248.csv.gz  in=402,071,611 out=103,945,320 elapsed=197.5s

  [13919/17668] intraday_6251.csv.gz  in=402,085,392 out=103,945,320 elapsed=197.5s

  [13920/17668] intraday_6249.csv.gz  in=402,100,885 out=103,945,320 elapsed=197.5s

  [13921/17668] intraday_6252.csv.gz  in=402,114,373 out=103,945,320 elapsed=197.5s

  [13922/17668] intraday_6254.csv.gz  in=402,125,783 out=103,945,320 elapsed=197.5s

  [13923/17668] intraday_6253.csv.gz  in=402,141,447 out=103,945,320 elapsed=197.6s

  [13924/17668] intraday_6255.csv.gz  in=402,154,993 out=103,945,320 elapsed=197.6s

  [13925/17668] intraday_6256.csv.gz  in=402,168,007 out=103,945,320 elapsed=197.6s

  [13926/17668] intraday_6257.csv.gz  in=402,180,840 out=103,945,320 elapsed=197.6s

  [13927/17668] intraday_6258.csv.gz  in=402,195,117 out=103,945,320 elapsed=197.6s

  [13928/17668] intraday_6259.csv.gz  in=402,210,120 out=103,945,320 elapsed=197.6s

  [13929/17668] intraday_6263.csv.gz  in=402,221,449 out=103,945,320 elapsed=197.6s

  [13930/17668] intraday_6260.csv.gz  in=402,236,519 out=103,945,320 elapsed=197.6s

  [13931/17668] intraday_6262.csv.gz  in=402,250,800 out=103,945,320 elapsed=197.6s

  [13932/17668] intraday_6261.csv.gz  in=402,264,888 out=103,945,320 elapsed=197.6s

  [13933/17668] intraday_6265.csv.gz  in=402,277,264 out=103,945,320 elapsed=197.7s

  [13934/17668] intraday_6264.csv.gz  in=402,291,211 out=103,945,320 elapsed=197.7s

  [13935/17668] intraday_6266.csv.gz  in=402,304,892 out=103,945,320 elapsed=197.7s

  [13936/17668] intraday_6267.csv.gz  in=402,315,647 out=103,945,320 elapsed=197.7s

  [13937/17668] intraday_6268.csv.gz  in=402,324,971 out=103,945,320 elapsed=197.7s

  [13938/17668] intraday_6270.csv.gz  in=402,327,618 out=103,945,320 elapsed=197.7s

  [13939/17668] intraday_6269.csv.gz  in=402,339,493 out=103,945,320 elapsed=197.7s

  [13940/17668] intraday_6272.csv.gz  in=402,352,984 out=103,945,320 elapsed=197.7s

  [13941/17668] intraday_6271.csv.gz  in=402,368,581 out=103,945,320 elapsed=197.7s

  [13942/17668] intraday_6273.csv.gz  in=402,390,368 out=103,945,320 elapsed=197.7s

  [13943/17668] intraday_6276.csv.gz  in=402,404,967 out=103,945,320 elapsed=197.8s

  [13944/17668] intraday_6275.csv.gz  in=402,418,086 out=103,945,320 elapsed=197.8s

  [13945/17668] intraday_6274.csv.gz  in=402,445,715 out=103,945,320 elapsed=197.8s

  [13946/17668] intraday_6277.csv.gz  in=402,463,230 out=103,945,320 elapsed=197.8s

  [13947/17668] intraday_6278.csv.gz  in=402,474,045 out=103,945,320 elapsed=197.8s

  [13948/17668] intraday_6279.csv.gz  in=402,488,973 out=103,945,320 elapsed=197.8s

  [13949/17668] intraday_6280.csv.gz  in=402,503,921 out=103,945,320 elapsed=197.8s

  [13950/17668] intraday_6281.csv.gz  in=402,520,496 out=103,945,320 elapsed=197.8s

  [13951/17668] intraday_6284.csv.gz  in=402,533,899 out=103,945,320 elapsed=197.8s

  [13952/17668] intraday_6282.csv.gz  in=402,547,135 out=103,945,320 elapsed=197.9s

  [13953/17668] intraday_6283.csv.gz  in=402,559,662 out=103,945,320 elapsed=197.9s

  [13954/17668] intraday_6285.csv.gz  in=402,569,088 out=103,945,320 elapsed=197.9s

  [13955/17668] intraday_6286.csv.gz  in=402,578,566 out=103,945,320 elapsed=197.9s

  [13956/17668] intraday_6288.csv.gz  in=402,591,566 out=103,945,320 elapsed=197.9s

  [13957/17668] intraday_6287.csv.gz  in=402,605,482 out=103,945,320 elapsed=197.9s

  [13958/17668] intraday_6289.csv.gz  in=402,616,550 out=103,945,320 elapsed=197.9s

  [13959/17668] intraday_6290.csv.gz  in=402,630,241 out=103,945,320 elapsed=197.9s

  [13960/17668] intraday_6291.csv.gz  in=402,642,889 out=103,945,320 elapsed=197.9s

  [13961/17668] intraday_6292.csv.gz  in=402,654,968 out=103,945,320 elapsed=197.9s

  [13962/17668] intraday_6293.csv.gz  in=402,668,900 out=103,945,320 elapsed=197.9s

  [13963/17668] intraday_6294.csv.gz  in=402,683,216 out=103,945,320 elapsed=198.0s

  [13964/17668] intraday_6295.csv.gz  in=402,696,294 out=103,945,320 elapsed=198.0s

  [13965/17668] intraday_6296.csv.gz  in=402,708,258 out=103,945,320 elapsed=198.0s

  [13966/17668] intraday_6297.csv.gz  in=402,719,864 out=103,945,320 elapsed=198.0s

  [13967/17668] intraday_6298.csv.gz  in=402,733,936 out=103,945,320 elapsed=198.0s

  [13968/17668] intraday_6299.csv.gz  in=402,746,834 out=103,945,320 elapsed=198.0s

  [13969/17668] intraday_6300.csv.gz  in=402,770,816 out=103,945,320 elapsed=198.0s

  [13970/17668] intraday_6302.csv.gz  in=402,783,674 out=103,945,320 elapsed=198.0s

  [13971/17668] intraday_6301.csv.gz  in=402,800,635 out=103,945,320 elapsed=198.0s

  [13972/17668] intraday_6303.csv.gz  in=402,810,981 out=103,945,320 elapsed=198.0s

  [13973/17668] intraday_6304.csv.gz  in=402,823,811 out=103,945,320 elapsed=198.0s

  [13974/17668] intraday_6307.csv.gz  in=402,835,687 out=103,945,320 elapsed=198.1s

  [13975/17668] intraday_6308.csv.gz  in=402,846,185 out=103,945,320 elapsed=198.1s

  [13976/17668] intraday_6306.csv.gz  in=402,858,065 out=103,945,320 elapsed=198.1s

  [13977/17668] intraday_6305.csv.gz  in=402,881,365 out=103,945,320 elapsed=198.1s

  [13978/17668] intraday_6309.csv.gz  in=402,894,025 out=103,945,320 elapsed=198.1s

  [13979/17668] intraday_6311.csv.gz  in=402,904,705 out=103,945,320 elapsed=198.1s

  [13980/17668] intraday_6312.csv.gz  in=402,921,771 out=103,945,320 elapsed=198.1s

  [13981/17668] intraday_6310.csv.gz  in=402,943,667 out=103,945,320 elapsed=198.1s

  [13982/17668] intraday_6313.csv.gz  in=402,957,875 out=103,945,320 elapsed=198.2s

  [13983/17668] intraday_6315.csv.gz  in=402,971,531 out=103,945,320 elapsed=198.2s

  [13984/17668] intraday_6314.csv.gz  in=402,982,241 out=103,945,320 elapsed=198.2s

  [13985/17668] intraday_6316.csv.gz  in=402,992,699 out=103,945,320 elapsed=198.2s

  [13986/17668] intraday_6317.csv.gz  in=403,007,460 out=103,945,320 elapsed=198.2s

  [13987/17668] intraday_6319.csv.gz  in=403,021,876 out=103,945,320 elapsed=198.2s

  [13988/17668] intraday_6318.csv.gz  in=403,035,346 out=103,945,320 elapsed=198.2s

  [13989/17668] intraday_6320.csv.gz  in=403,056,422 out=103,945,320 elapsed=198.2s

  [13990/17668] intraday_6321.csv.gz  in=403,068,182 out=103,945,320 elapsed=198.2s

  [13991/17668] intraday_6322.csv.gz  in=403,078,562 out=103,945,320 elapsed=198.2s

  [13992/17668] intraday_6323.csv.gz  in=403,092,853 out=103,945,320 elapsed=198.2s

  [13993/17668] intraday_6324.csv.gz  in=403,103,328 out=103,945,320 elapsed=198.2s

  [13994/17668] intraday_6326.csv.gz  in=403,116,641 out=103,945,320 elapsed=198.3s

  [13995/17668] intraday_6325.csv.gz  in=403,131,096 out=103,945,320 elapsed=198.3s

  [13996/17668] intraday_6327.csv.gz  in=403,143,732 out=103,945,320 elapsed=198.3s

  [13997/17668] intraday_6328.csv.gz  in=403,159,303 out=103,945,320 elapsed=198.3s

  [13998/17668] intraday_6329.csv.gz  in=403,172,185 out=103,945,320 elapsed=198.3s

  [13999/17668] intraday_6331.csv.gz  in=403,183,885 out=103,945,320 elapsed=198.3s

  [14000/17668] intraday_6332.csv.gz  in=403,198,111 out=103,945,320 elapsed=198.3s

  [14001/17668] intraday_6330.csv.gz  in=403,212,491 out=103,945,320 elapsed=198.3s

  [14002/17668] intraday_6334.csv.gz  in=403,222,316 out=103,945,320 elapsed=198.3s

  [14003/17668] intraday_6335.csv.gz  in=403,234,090 out=103,945,320 elapsed=198.4s

  [14004/17668] intraday_6333.csv.gz  in=403,245,726 out=103,945,320 elapsed=198.4s

  [14005/17668] intraday_6336.csv.gz  in=403,260,034 out=103,945,320 elapsed=198.4s

  [14006/17668] intraday_6337.csv.gz  in=403,274,990 out=103,945,320 elapsed=198.4s

  [14007/17668] intraday_6339.csv.gz  in=403,287,682 out=103,945,320 elapsed=198.4s

  [14008/17668] intraday_6340.csv.gz  in=403,299,055 out=103,945,320 elapsed=198.4s

  [14009/17668] intraday_6338.csv.gz  in=403,312,910 out=103,945,320 elapsed=198.4s

  [14010/17668] intraday_6341.csv.gz  in=403,324,623 out=103,945,320 elapsed=198.4s

  [14011/17668] intraday_6342.csv.gz  in=403,336,432 out=103,945,320 elapsed=198.4s

  [14012/17668] intraday_6344.csv.gz  in=403,349,670 out=103,945,320 elapsed=198.4s

  [14013/17668] intraday_6343.csv.gz  in=403,361,928 out=103,945,320 elapsed=198.4s

  [14014/17668] intraday_6345.csv.gz  in=403,374,722 out=103,945,320 elapsed=198.5s

  [14015/17668] intraday_6348.csv.gz  in=403,388,767 out=103,945,320 elapsed=198.5s

  [14016/17668] intraday_6346.csv.gz  in=403,400,456 out=103,945,320 elapsed=198.5s

  [14017/17668] intraday_6347.csv.gz  in=403,410,979 out=103,945,320 elapsed=198.5s

  [14018/17668] intraday_6349.csv.gz  in=403,422,480 out=103,945,320 elapsed=198.5s

  [14019/17668] intraday_6352.csv.gz  in=403,434,884 out=103,945,320 elapsed=198.5s

  [14020/17668] intraday_6350.csv.gz  in=403,448,283 out=103,945,320 elapsed=198.5s

  [14021/17668] intraday_6351.csv.gz  in=403,457,957 out=103,945,320 elapsed=198.5s

  [14022/17668] intraday_6353.csv.gz  in=403,471,220 out=103,945,320 elapsed=198.6s

  [14023/17668] intraday_6354.csv.gz  in=403,486,300 out=103,945,320 elapsed=198.6s

  [14024/17668] intraday_6356.csv.gz  in=403,501,963 out=103,945,320 elapsed=198.6s

  [14025/17668] intraday_6355.csv.gz  in=403,517,560 out=103,945,320 elapsed=198.6s

  [14026/17668] intraday_6357.csv.gz  in=403,529,022 out=103,945,320 elapsed=198.6s

  [14027/17668] intraday_6359.csv.gz  in=403,542,549 out=103,945,320 elapsed=198.6s

  [14028/17668] intraday_6358.csv.gz  in=403,555,523 out=103,945,320 elapsed=198.6s

  [14029/17668] intraday_6360.csv.gz  in=403,571,900 out=103,945,320 elapsed=198.6s

  [14030/17668] intraday_6361.csv.gz  in=403,593,260 out=103,945,320 elapsed=198.6s

  [14031/17668] intraday_6363.csv.gz  in=403,606,552 out=103,945,320 elapsed=198.6s

  [14032/17668] intraday_6362.csv.gz  in=403,619,647 out=103,945,320 elapsed=198.6s

  [14033/17668] intraday_6364.csv.gz  in=403,633,516 out=103,945,320 elapsed=198.6s

  [14034/17668] intraday_6365.csv.gz  in=403,648,126 out=103,945,320 elapsed=198.7s

  [14035/17668] intraday_6367.csv.gz  in=403,661,070 out=103,945,320 elapsed=198.7s

  [14036/17668] intraday_6366.csv.gz  in=403,673,475 out=103,945,320 elapsed=198.7s

  [14037/17668] intraday_6369.csv.gz  in=403,685,867 out=103,945,320 elapsed=198.7s

  [14038/17668] intraday_6368.csv.gz  in=403,699,094 out=103,945,320 elapsed=198.7s

  [14039/17668] intraday_6371.csv.gz  in=403,710,980 out=103,945,320 elapsed=198.7s

  [14040/17668] intraday_6372.csv.gz  in=403,729,435 out=103,945,320 elapsed=198.7s

  [14041/17668] intraday_6373.csv.gz  in=403,744,090 out=103,945,320 elapsed=198.7s

  [14042/17668] intraday_6370.csv.gz  in=403,758,209 out=103,945,320 elapsed=198.7s

  [14043/17668] intraday_6374.csv.gz  in=403,771,797 out=103,945,320 elapsed=198.8s

  [14044/17668] intraday_6376.csv.gz  in=403,786,168 out=103,945,320 elapsed=198.8s

  [14045/17668] intraday_6375.csv.gz  in=403,799,280 out=103,945,320 elapsed=198.8s

  [14046/17668] intraday_6377.csv.gz  in=403,813,779 out=103,945,320 elapsed=198.8s

  [14047/17668] intraday_6378.csv.gz  in=403,826,412 out=103,945,320 elapsed=198.8s

  [14048/17668] intraday_6381.csv.gz  in=403,839,742 out=103,945,320 elapsed=198.8s

  [14049/17668] intraday_6379.csv.gz  in=403,853,243 out=103,945,320 elapsed=198.8s

  [14050/17668] intraday_6380.csv.gz  in=403,868,753 out=103,945,320 elapsed=198.8s

  [14051/17668] intraday_6382.csv.gz  in=403,880,521 out=103,945,320 elapsed=198.8s

  [14052/17668] intraday_6383.csv.gz  in=403,894,854 out=103,945,320 elapsed=198.8s

  [14053/17668] intraday_6384.csv.gz  in=403,906,688 out=103,945,320 elapsed=198.9s

  [14054/17668] intraday_6385.csv.gz  in=403,921,031 out=103,945,320 elapsed=198.9s

  [14055/17668] intraday_6386.csv.gz  in=403,936,958 out=103,945,320 elapsed=198.9s

  [14056/17668] intraday_6387.csv.gz  in=403,951,713 out=103,945,320 elapsed=198.9s

  [14057/17668] intraday_6389.csv.gz  in=403,964,669 out=103,945,320 elapsed=198.9s

  [14058/17668] intraday_6388.csv.gz  in=403,979,362 out=103,945,320 elapsed=198.9s

  [14059/17668] intraday_6390.csv.gz  in=403,996,588 out=103,945,320 elapsed=198.9s

  [14060/17668] intraday_6392.csv.gz  in=404,007,602 out=103,945,320 elapsed=198.9s

  [14061/17668] intraday_6391.csv.gz  in=404,020,391 out=103,945,320 elapsed=198.9s

  [14062/17668] intraday_6394.csv.gz  in=404,032,130 out=103,945,320 elapsed=198.9s

  [14063/17668] intraday_6393.csv.gz  in=404,045,932 out=103,945,320 elapsed=198.9s

  [14064/17668] intraday_6395.csv.gz  in=404,058,357 out=103,945,320 elapsed=198.9s

  [14065/17668] intraday_6398.csv.gz  in=404,070,009 out=103,945,320 elapsed=199.0s

  [14066/17668] intraday_6399.csv.gz  in=404,082,080 out=103,945,320 elapsed=199.0s

  [14067/17668] intraday_6396.csv.gz  in=404,096,041 out=103,945,320 elapsed=199.0s

  [14068/17668] intraday_6397.csv.gz  in=404,122,551 out=103,945,320 elapsed=199.0s

  [14069/17668] intraday_6400.csv.gz  in=404,135,852 out=103,945,320 elapsed=199.0s

  [14070/17668] intraday_6401.csv.gz  in=404,147,578 out=103,945,320 elapsed=199.0s

  [14071/17668] intraday_6402.csv.gz  in=404,163,293 out=103,945,320 elapsed=199.0s

  [14072/17668] intraday_6403.csv.gz  in=404,177,467 out=103,945,320 elapsed=199.0s

  [14073/17668] intraday_6404.csv.gz  in=404,192,206 out=103,945,320 elapsed=199.0s

  [14074/17668] intraday_6407.csv.gz  in=404,203,678 out=103,945,320 elapsed=199.0s

  [14075/17668] intraday_6406.csv.gz  in=404,217,673 out=103,945,320 elapsed=199.1s

  [14076/17668] intraday_6405.csv.gz  in=404,232,320 out=103,945,320 elapsed=199.1s

  [14077/17668] intraday_6408.csv.gz  in=404,245,124 out=103,945,320 elapsed=199.1s

  [14078/17668] intraday_6410.csv.gz  in=404,258,108 out=103,945,320 elapsed=199.1s

  [14079/17668] intraday_6409.csv.gz  in=404,270,550 out=103,945,320 elapsed=199.1s

  [14080/17668] intraday_6411.csv.gz  in=404,280,790 out=103,945,320 elapsed=199.1s

  [14081/17668] intraday_6412.csv.gz  in=404,289,698 out=103,945,320 elapsed=199.1s

  [14082/17668] intraday_6414.csv.gz  in=404,292,381 out=103,945,320 elapsed=199.1s

  [14083/17668] intraday_6413.csv.gz  in=404,304,952 out=103,945,320 elapsed=199.1s

  [14084/17668] intraday_6415.csv.gz  in=404,321,281 out=103,945,320 elapsed=199.1s

  [14085/17668] intraday_6416.csv.gz  in=404,334,182 out=103,945,320 elapsed=199.2s

  [14086/17668] intraday_6417.csv.gz  in=404,348,169 out=103,945,320 elapsed=199.2s

  [14087/17668] intraday_6418.csv.gz  in=404,359,412 out=103,945,320 elapsed=199.2s

  [14088/17668] intraday_6419.csv.gz  in=404,372,283 out=103,945,320 elapsed=199.2s

  [14089/17668] intraday_6420.csv.gz  in=404,386,561 out=103,945,320 elapsed=199.2s

  [14090/17668] intraday_6422.csv.gz  in=404,399,270 out=103,945,320 elapsed=199.2s

  [14091/17668] intraday_6421.csv.gz  in=404,414,304 out=103,945,320 elapsed=199.2s

  [14092/17668] intraday_6423.csv.gz  in=404,428,257 out=103,945,320 elapsed=199.2s

  [14093/17668] intraday_6424.csv.gz  in=404,442,754 out=103,945,320 elapsed=199.2s

  [14094/17668] intraday_6425.csv.gz  in=404,458,744 out=103,945,320 elapsed=199.2s

  [14095/17668] intraday_6426.csv.gz  in=404,472,594 out=103,945,320 elapsed=199.2s

  [14096/17668] intraday_6427.csv.gz  in=404,486,312 out=103,945,320 elapsed=199.2s

  [14097/17668] intraday_6429.csv.gz  in=404,497,204 out=103,945,320 elapsed=199.3s

  [14098/17668] intraday_6428.csv.gz  in=404,509,689 out=103,945,320 elapsed=199.3s

  [14099/17668] intraday_6430.csv.gz  in=404,519,324 out=103,945,320 elapsed=199.3s

  [14100/17668] intraday_6431.csv.gz  in=404,533,107 out=103,945,320 elapsed=199.3s

  [14101/17668] intraday_6433.csv.gz  in=404,543,525 out=103,945,320 elapsed=199.3s

  [14102/17668] intraday_6432.csv.gz  in=404,557,466 out=103,945,320 elapsed=199.3s

  [14103/17668] intraday_6435.csv.gz  in=404,569,851 out=103,945,320 elapsed=199.3s

  [14104/17668] intraday_6434.csv.gz  in=404,583,212 out=103,945,320 elapsed=199.3s

  [14105/17668] intraday_6436.csv.gz  in=404,596,123 out=103,945,320 elapsed=199.3s

  [14106/17668] intraday_6437.csv.gz  in=404,608,365 out=103,945,320 elapsed=199.3s

  [14107/17668] intraday_6438.csv.gz  in=404,621,788 out=103,945,320 elapsed=199.4s

  [14108/17668] intraday_6439.csv.gz  in=404,634,121 out=103,945,320 elapsed=199.4s

  [14109/17668] intraday_6440.csv.gz  in=404,645,505 out=103,945,320 elapsed=199.4s

  [14110/17668] intraday_6441.csv.gz  in=404,656,957 out=103,945,320 elapsed=199.4s

  [14111/17668] intraday_6442.csv.gz  in=404,668,791 out=103,945,320 elapsed=199.4s

  [14112/17668] intraday_6443.csv.gz  in=404,681,592 out=103,945,320 elapsed=199.4s

  [14113/17668] intraday_6444.csv.gz  in=404,696,073 out=103,945,320 elapsed=199.4s

  [14114/17668] intraday_6445.csv.gz  in=404,713,377 out=103,945,320 elapsed=199.4s

  [14115/17668] intraday_6446.csv.gz  in=404,724,227 out=103,945,320 elapsed=199.4s

  [14116/17668] intraday_6448.csv.gz  in=404,737,332 out=103,945,320 elapsed=199.4s

  [14117/17668] intraday_6447.csv.gz  in=404,748,057 out=103,945,320 elapsed=199.4s

  [14118/17668] intraday_6451.csv.gz  in=404,761,740 out=103,945,320 elapsed=199.5s

  [14119/17668] intraday_6449.csv.gz  in=404,776,663 out=103,945,320 elapsed=199.5s

  [14120/17668] intraday_6452.csv.gz  in=404,787,150 out=103,945,320 elapsed=199.5s

  [14121/17668] intraday_6450.csv.gz  in=404,799,093 out=103,945,320 elapsed=199.5s

  [14122/17668] intraday_6454.csv.gz  in=404,810,229 out=103,945,320 elapsed=199.5s

  [14123/17668] intraday_6453.csv.gz  in=404,822,632 out=103,945,320 elapsed=199.5s

  [14124/17668] intraday_6456.csv.gz  in=404,835,843 out=103,945,320 elapsed=199.5s

  [14125/17668] intraday_6455.csv.gz  in=404,847,803 out=103,945,320 elapsed=199.5s

  [14126/17668] intraday_6457.csv.gz  in=404,861,060 out=103,945,320 elapsed=199.5s

  [14127/17668] intraday_6459.csv.gz  in=404,874,081 out=103,945,320 elapsed=199.6s

  [14128/17668] intraday_6458.csv.gz  in=404,887,612 out=103,945,320 elapsed=199.6s

  [14129/17668] intraday_6460.csv.gz  in=404,898,639 out=103,945,320 elapsed=199.6s

  [14130/17668] intraday_6461.csv.gz  in=404,911,715 out=103,945,320 elapsed=199.6s

  [14131/17668] intraday_6463.csv.gz  in=404,922,727 out=103,945,320 elapsed=199.6s

  [14132/17668] intraday_6462.csv.gz  in=404,934,333 out=103,945,320 elapsed=199.6s

  [14133/17668] intraday_6465.csv.gz  in=404,946,273 out=103,945,320 elapsed=199.6s

  [14134/17668] intraday_6464.csv.gz  in=404,957,993 out=103,945,320 elapsed=199.6s

  [14135/17668] intraday_6468.csv.gz  in=404,969,736 out=103,945,320 elapsed=199.6s

  [14136/17668] intraday_6466.csv.gz  in=404,982,691 out=103,945,320 elapsed=199.6s

  [14137/17668] intraday_6467.csv.gz  in=404,995,373 out=103,945,320 elapsed=199.6s

  [14138/17668] intraday_6469.csv.gz  in=405,010,369 out=103,945,320 elapsed=199.6s

  [14139/17668] intraday_6470.csv.gz  in=405,023,410 out=103,945,320 elapsed=199.7s

  [14140/17668] intraday_6471.csv.gz  in=405,035,334 out=103,945,320 elapsed=199.7s

  [14141/17668] intraday_6472.csv.gz  in=405,046,323 out=103,945,320 elapsed=199.7s

  [14142/17668] intraday_6473.csv.gz  in=405,060,411 out=103,945,320 elapsed=199.7s

  [14143/17668] intraday_6474.csv.gz  in=405,074,949 out=103,945,320 elapsed=199.7s

  [14144/17668] intraday_6477.csv.gz  in=405,087,227 out=103,945,320 elapsed=199.7s

  [14145/17668] intraday_6476.csv.gz  in=405,099,233 out=103,945,320 elapsed=199.7s

  [14146/17668] intraday_6475.csv.gz  in=405,111,476 out=103,945,320 elapsed=199.7s

  [14147/17668] intraday_6478.csv.gz  in=405,122,473 out=103,945,320 elapsed=199.7s

  [14148/17668] intraday_6479.csv.gz  in=405,136,546 out=103,945,320 elapsed=199.8s

  [14149/17668] intraday_6481.csv.gz  in=405,148,080 out=103,945,320 elapsed=199.8s

  [14150/17668] intraday_6480.csv.gz  in=405,164,422 out=103,945,320 elapsed=199.8s

  [14151/17668] intraday_6485.csv.gz  in=405,175,748 out=103,945,320 elapsed=199.8s

  [14152/17668] intraday_6483.csv.gz  in=405,188,934 out=103,945,320 elapsed=199.8s

  [14153/17668] intraday_6484.csv.gz  in=405,199,512 out=103,945,320 elapsed=199.8s

  [14154/17668] intraday_6482.csv.gz  in=405,212,021 out=103,945,320 elapsed=199.8s

  [14155/17668] intraday_6486.csv.gz  in=405,223,902 out=103,945,320 elapsed=199.8s

  [14156/17668] intraday_6488.csv.gz  in=405,235,025 out=103,945,320 elapsed=199.8s

  [14157/17668] intraday_6487.csv.gz  in=405,249,849 out=103,945,320 elapsed=199.8s

  [14158/17668] intraday_6489.csv.gz  in=405,262,843 out=103,945,320 elapsed=199.8s

  [14159/17668] intraday_6490.csv.gz  in=405,273,239 out=103,945,320 elapsed=199.9s

  [14160/17668] intraday_6491.csv.gz  in=405,287,370 out=103,945,320 elapsed=199.9s

  [14161/17668] intraday_6492.csv.gz  in=405,299,778 out=103,945,320 elapsed=199.9s

  [14162/17668] intraday_6493.csv.gz  in=405,313,665 out=103,945,320 elapsed=199.9s

  [14163/17668] intraday_6494.csv.gz  in=405,324,432 out=103,945,320 elapsed=199.9s

  [14164/17668] intraday_6495.csv.gz  in=405,335,074 out=103,945,320 elapsed=199.9s

  [14165/17668] intraday_6496.csv.gz  in=405,347,426 out=103,945,320 elapsed=199.9s

  [14166/17668] intraday_6497.csv.gz  in=405,363,621 out=103,945,320 elapsed=199.9s

  [14167/17668] intraday_6500.csv.gz  in=405,376,937 out=103,945,320 elapsed=199.9s

  [14168/17668] intraday_6499.csv.gz  in=405,390,928 out=103,945,320 elapsed=199.9s

  [14169/17668] intraday_6498.csv.gz  in=405,407,410 out=103,945,320 elapsed=199.9s

  [14170/17668] intraday_6501.csv.gz  in=405,418,878 out=103,945,320 elapsed=200.0s

  [14171/17668] intraday_6502.csv.gz  in=405,433,390 out=103,945,320 elapsed=200.0s

  [14172/17668] intraday_6503.csv.gz  in=405,447,645 out=103,945,320 elapsed=200.0s

  [14173/17668] intraday_6504.csv.gz  in=405,462,173 out=103,945,320 elapsed=200.0s

  [14174/17668] intraday_6505.csv.gz  in=405,474,245 out=103,945,320 elapsed=200.0s

  [14175/17668] intraday_6506.csv.gz  in=405,490,878 out=103,945,320 elapsed=200.0s

  [14176/17668] intraday_6507.csv.gz  in=405,505,021 out=103,945,320 elapsed=200.0s

  [14177/17668] intraday_6508.csv.gz  in=405,518,722 out=103,945,320 elapsed=200.0s

  [14178/17668] intraday_6509.csv.gz  in=405,531,292 out=103,945,320 elapsed=200.0s

  [14179/17668] intraday_6510.csv.gz  in=405,544,680 out=103,945,320 elapsed=200.0s

  [14180/17668] intraday_6513.csv.gz  in=405,557,233 out=103,945,320 elapsed=200.1s

  [14181/17668] intraday_6512.csv.gz  in=405,571,798 out=103,945,320 elapsed=200.1s

  [14182/17668] intraday_6511.csv.gz  in=405,584,107 out=103,945,320 elapsed=200.1s

  [14183/17668] intraday_6514.csv.gz  in=405,597,021 out=103,945,320 elapsed=200.1s

  [14184/17668] intraday_6517.csv.gz  in=405,612,271 out=103,945,320 elapsed=200.2s

  [14185/17668] intraday_6515.csv.gz  in=405,624,366 out=103,945,320 elapsed=200.2s

  [14186/17668] intraday_6516.csv.gz  in=405,639,422 out=103,945,320 elapsed=200.2s

  [14187/17668] intraday_6518.csv.gz  in=405,653,362 out=103,945,320 elapsed=200.2s

  [14188/17668] intraday_6521.csv.gz  in=405,666,090 out=103,945,320 elapsed=200.2s

  [14189/17668] intraday_6519.csv.gz  in=405,676,920 out=103,945,320 elapsed=200.2s

  [14190/17668] intraday_6520.csv.gz  in=405,709,996 out=103,945,320 elapsed=200.2s

  [14191/17668] intraday_6524.csv.gz  in=405,723,314 out=103,945,320 elapsed=200.2s

  [14192/17668] intraday_6522.csv.gz  in=405,734,901 out=103,945,320 elapsed=200.2s

  [14193/17668] intraday_6523.csv.gz  in=405,749,868 out=103,945,320 elapsed=200.2s

  [14194/17668] intraday_6525.csv.gz  in=405,761,840 out=103,945,320 elapsed=200.2s

  [14195/17668] intraday_6528.csv.gz  in=405,775,385 out=103,945,320 elapsed=200.3s

  [14196/17668] intraday_6527.csv.gz  in=405,797,769 out=103,945,320 elapsed=200.3s

  [14197/17668] intraday_6529.csv.gz  in=405,813,739 out=103,945,320 elapsed=200.3s

  [14198/17668] intraday_6526.csv.gz  in=405,828,588 out=103,945,320 elapsed=200.3s

  [14199/17668] intraday_6530.csv.gz  in=405,845,322 out=103,945,320 elapsed=200.3s

  [14200/17668] intraday_6533.csv.gz  in=405,856,978 out=103,945,320 elapsed=200.3s

  [14201/17668] intraday_6532.csv.gz  in=405,872,881 out=103,945,320 elapsed=200.3s

  [14202/17668] intraday_6531.csv.gz  in=405,885,380 out=103,945,320 elapsed=200.3s

  [14203/17668] intraday_6534.csv.gz  in=405,898,496 out=103,945,320 elapsed=200.3s

  [14204/17668] intraday_6535.csv.gz  in=405,909,781 out=103,945,320 elapsed=200.4s

  [14205/17668] intraday_6536.csv.gz  in=405,924,291 out=103,945,320 elapsed=200.4s

  [14206/17668] intraday_6537.csv.gz  in=405,935,542 out=103,945,320 elapsed=200.4s

  [14207/17668] intraday_6539.csv.gz  in=405,947,859 out=103,945,320 elapsed=200.4s

  [14208/17668] intraday_6541.csv.gz  in=405,961,069 out=103,945,320 elapsed=200.4s

  [14209/17668] intraday_6538.csv.gz  in=405,975,179 out=103,945,320 elapsed=200.4s

  [14210/17668] intraday_6540.csv.gz  in=405,990,518 out=103,945,320 elapsed=200.4s

  [14211/17668] intraday_6542.csv.gz  in=406,003,258 out=103,945,320 elapsed=200.4s

  [14212/17668] intraday_6543.csv.gz  in=406,016,329 out=103,945,320 elapsed=200.4s

  [14213/17668] intraday_6544.csv.gz  in=406,028,740 out=103,945,320 elapsed=200.4s

  [14214/17668] intraday_6545.csv.gz  in=406,041,932 out=103,945,320 elapsed=200.4s

  [14215/17668] intraday_6546.csv.gz  in=406,056,482 out=103,945,320 elapsed=200.5s

  [14216/17668] intraday_6547.csv.gz  in=406,070,003 out=103,945,320 elapsed=200.5s

  [14217/17668] intraday_6548.csv.gz  in=406,084,996 out=103,945,320 elapsed=200.5s

  [14218/17668] intraday_6549.csv.gz  in=406,098,841 out=103,945,320 elapsed=200.5s

  [14219/17668] intraday_6550.csv.gz  in=406,109,627 out=103,945,320 elapsed=200.5s

  [14220/17668] intraday_6553.csv.gz  in=406,121,395 out=103,945,320 elapsed=200.5s

  [14221/17668] intraday_6551.csv.gz  in=406,135,048 out=103,945,320 elapsed=200.5s

  [14222/17668] intraday_6552.csv.gz  in=406,147,818 out=103,945,320 elapsed=200.5s

  [14223/17668] intraday_6554.csv.gz  in=406,159,609 out=103,945,320 elapsed=200.5s

  [14224/17668] intraday_6555.csv.gz  in=406,168,149 out=103,945,320 elapsed=200.5s

  [14225/17668] intraday_6557.csv.gz  in=406,173,399 out=103,945,320 elapsed=200.5s

  [14226/17668] intraday_6556.csv.gz  in=406,185,985 out=103,945,320 elapsed=200.5s

  [14227/17668] intraday_6559.csv.gz  in=406,199,360 out=103,945,320 elapsed=200.6s

  [14228/17668] intraday_6558.csv.gz  in=406,218,636 out=103,945,320 elapsed=200.6s

  [14229/17668] intraday_6560.csv.gz  in=406,231,602 out=103,945,320 elapsed=200.6s

  [14230/17668] intraday_6561.csv.gz  in=406,243,090 out=103,945,320 elapsed=200.6s

  [14231/17668] intraday_6562.csv.gz  in=406,255,874 out=103,945,320 elapsed=200.6s

  [14232/17668] intraday_6564.csv.gz  in=406,270,213 out=103,945,320 elapsed=200.6s

  [14233/17668] intraday_6563.csv.gz  in=406,285,594 out=103,945,320 elapsed=200.6s

  [14234/17668] intraday_6565.csv.gz  in=406,297,646 out=103,945,320 elapsed=200.6s

  [14235/17668] intraday_6566.csv.gz  in=406,315,090 out=103,945,320 elapsed=200.6s

  [14236/17668] intraday_6567.csv.gz  in=406,328,923 out=103,945,320 elapsed=200.6s

  [14237/17668] intraday_6569.csv.gz  in=406,342,651 out=103,945,320 elapsed=200.7s

  [14238/17668] intraday_6568.csv.gz  in=406,359,084 out=103,945,320 elapsed=200.7s

  [14239/17668] intraday_6570.csv.gz  in=406,373,260 out=103,945,320 elapsed=200.7s

  [14240/17668] intraday_6572.csv.gz  in=406,383,687 out=103,945,320 elapsed=200.7s

  [14241/17668] intraday_6571.csv.gz  in=406,396,016 out=103,945,320 elapsed=200.7s

  [14242/17668] intraday_6573.csv.gz  in=406,405,232 out=103,945,320 elapsed=200.7s

  [14243/17668] intraday_6574.csv.gz  in=406,419,486 out=103,945,320 elapsed=200.7s

  [14244/17668] intraday_6575.csv.gz  in=406,432,689 out=103,945,320 elapsed=200.7s

  [14245/17668] intraday_6576.csv.gz  in=406,444,781 out=103,945,320 elapsed=200.7s

  [14246/17668] intraday_6577.csv.gz  in=406,457,519 out=103,945,320 elapsed=200.7s

  [14247/17668] intraday_6578.csv.gz  in=406,469,874 out=103,945,320 elapsed=200.8s

  [14248/17668] intraday_6580.csv.gz  in=406,481,896 out=103,945,320 elapsed=200.8s

  [14249/17668] intraday_6579.csv.gz  in=406,494,356 out=103,945,320 elapsed=200.8s

  [14250/17668] intraday_6581.csv.gz  in=406,507,930 out=103,945,320 elapsed=200.8s

  [14251/17668] intraday_6582.csv.gz  in=406,521,794 out=103,945,320 elapsed=200.8s

  [14252/17668] intraday_6584.csv.gz  in=406,533,354 out=103,945,320 elapsed=200.8s

  [14253/17668] intraday_6585.csv.gz  in=406,545,555 out=103,945,320 elapsed=200.8s

  [14254/17668] intraday_6583.csv.gz  in=406,566,561 out=103,945,320 elapsed=200.8s

  [14255/17668] intraday_6586.csv.gz  in=406,578,982 out=103,945,320 elapsed=200.8s

  [14256/17668] intraday_6587.csv.gz  in=406,591,567 out=103,945,320 elapsed=200.8s

  [14257/17668] intraday_6588.csv.gz  in=406,609,217 out=103,945,320 elapsed=200.8s

  [14258/17668] intraday_6589.csv.gz  in=406,621,979 out=103,945,320 elapsed=200.8s

  [14259/17668] intraday_6591.csv.gz  in=406,634,883 out=103,945,320 elapsed=200.9s

  [14260/17668] intraday_6590.csv.gz  in=406,646,559 out=103,945,320 elapsed=200.9s

  [14261/17668] intraday_6593.csv.gz  in=406,658,169 out=103,945,320 elapsed=200.9s

  [14262/17668] intraday_6594.csv.gz  in=406,672,966 out=103,945,320 elapsed=200.9s

  [14263/17668] intraday_6592.csv.gz  in=406,686,774 out=103,945,320 elapsed=200.9s

  [14264/17668] intraday_6595.csv.gz  in=406,697,989 out=103,945,320 elapsed=200.9s

  [14265/17668] intraday_6596.csv.gz  in=406,712,082 out=103,945,320 elapsed=200.9s

  [14266/17668] intraday_6597.csv.gz  in=406,724,295 out=103,945,320 elapsed=200.9s

  [14267/17668] intraday_6598.csv.gz  in=406,736,788 out=103,945,320 elapsed=200.9s

  [14268/17668] intraday_6599.csv.gz  in=406,753,377 out=103,945,320 elapsed=200.9s

  [14269/17668] intraday_6600.csv.gz  in=406,766,716 out=103,945,320 elapsed=200.9s

  [14270/17668] intraday_6601.csv.gz  in=406,777,985 out=103,945,320 elapsed=201.0s

  [14271/17668] intraday_6602.csv.gz  in=406,791,821 out=103,945,320 elapsed=201.0s

  [14272/17668] intraday_6603.csv.gz  in=406,802,947 out=103,945,320 elapsed=201.0s

  [14273/17668] intraday_6604.csv.gz  in=406,815,322 out=103,945,320 elapsed=201.0s

  [14274/17668] intraday_6606.csv.gz  in=406,826,032 out=103,945,320 elapsed=201.0s

  [14275/17668] intraday_6605.csv.gz  in=406,839,429 out=103,945,320 elapsed=201.0s

  [14276/17668] intraday_6607.csv.gz  in=406,850,978 out=103,945,320 elapsed=201.0s

  [14277/17668] intraday_6608.csv.gz  in=406,862,766 out=103,945,320 elapsed=201.0s

  [14278/17668] intraday_6609.csv.gz  in=406,875,160 out=103,945,320 elapsed=201.0s

  [14279/17668] intraday_6610.csv.gz  in=406,887,848 out=103,945,320 elapsed=201.0s

  [14280/17668] intraday_6611.csv.gz  in=406,900,203 out=103,945,320 elapsed=201.0s

  [14281/17668] intraday_6612.csv.gz  in=406,915,071 out=103,945,320 elapsed=201.1s

  [14282/17668] intraday_6613.csv.gz  in=406,929,010 out=103,945,320 elapsed=201.1s

  [14283/17668] intraday_6615.csv.gz  in=406,940,395 out=103,945,320 elapsed=201.1s

  [14284/17668] intraday_6614.csv.gz  in=406,953,283 out=103,945,320 elapsed=201.1s

  [14285/17668] intraday_6617.csv.gz  in=406,968,072 out=103,945,320 elapsed=201.1s

  [14286/17668] intraday_6618.csv.gz  in=406,981,236 out=103,945,320 elapsed=201.1s

  [14287/17668] intraday_6616.csv.gz  in=406,995,266 out=103,945,320 elapsed=201.1s

  [14288/17668] intraday_6619.csv.gz  in=407,008,948 out=103,945,320 elapsed=201.1s

  [14289/17668] intraday_6621.csv.gz  in=407,020,632 out=103,945,320 elapsed=201.2s

  [14290/17668] intraday_6620.csv.gz  in=407,032,315 out=103,945,320 elapsed=201.2s

  [14291/17668] intraday_6622.csv.gz  in=407,048,986 out=103,945,320 elapsed=201.2s

  [14292/17668] intraday_6623.csv.gz  in=407,064,735 out=103,945,320 elapsed=201.2s

  [14293/17668] intraday_6625.csv.gz  in=407,077,973 out=103,945,320 elapsed=201.2s

  [14294/17668] intraday_6627.csv.gz  in=407,089,416 out=103,945,320 elapsed=201.2s

  [14295/17668] intraday_6624.csv.gz  in=407,102,563 out=103,945,320 elapsed=201.2s

  [14296/17668] intraday_6626.csv.gz  in=407,115,276 out=103,945,320 elapsed=201.2s

  [14297/17668] intraday_6628.csv.gz  in=407,127,540 out=103,945,320 elapsed=201.2s

  [14298/17668] intraday_6630.csv.gz  in=407,142,041 out=103,945,320 elapsed=201.2s

  [14299/17668] intraday_6629.csv.gz  in=407,153,026 out=103,945,320 elapsed=201.2s

  [14300/17668] intraday_6631.csv.gz  in=407,166,039 out=103,945,320 elapsed=201.2s

  [14301/17668] intraday_6632.csv.gz  in=407,178,091 out=103,945,320 elapsed=201.2s

  [14302/17668] intraday_6635.csv.gz  in=407,189,963 out=103,945,320 elapsed=201.2s

  [14303/17668] intraday_6633.csv.gz  in=407,200,295 out=103,945,320 elapsed=201.3s

  [14304/17668] intraday_6634.csv.gz  in=407,213,581 out=103,945,320 elapsed=201.3s

  [14305/17668] intraday_6636.csv.gz  in=407,225,743 out=103,945,320 elapsed=201.3s

  [14306/17668] intraday_6639.csv.gz  in=407,237,946 out=103,945,320 elapsed=201.3s

  [14307/17668] intraday_6638.csv.gz  in=407,247,677 out=103,945,320 elapsed=201.3s

  [14308/17668] intraday_6637.csv.gz  in=407,264,401 out=103,945,320 elapsed=201.3s

  [14309/17668] intraday_6640.csv.gz  in=407,277,052 out=103,945,320 elapsed=201.3s

  [14310/17668] intraday_6643.csv.gz  in=407,290,473 out=103,945,320 elapsed=201.3s

  [14311/17668] intraday_6641.csv.gz  in=407,306,217 out=103,945,320 elapsed=201.3s

  [14312/17668] intraday_6644.csv.gz  in=407,318,625 out=103,945,320 elapsed=201.3s

  [14313/17668] intraday_6642.csv.gz  in=407,333,352 out=103,945,320 elapsed=201.3s

  [14314/17668] intraday_6646.csv.gz  in=407,346,671 out=103,945,320 elapsed=201.4s

  [14315/17668] intraday_6648.csv.gz  in=407,361,622 out=103,945,320 elapsed=201.4s

  [14316/17668] intraday_6645.csv.gz  in=407,375,753 out=103,945,320 elapsed=201.4s

  [14317/17668] intraday_6647.csv.gz  in=407,392,010 out=103,945,320 elapsed=201.4s

  [14318/17668] intraday_6651.csv.gz  in=407,406,372 out=103,945,320 elapsed=201.4s

  [14319/17668] intraday_6650.csv.gz  in=407,420,607 out=103,945,320 elapsed=201.4s

  [14320/17668] intraday_6649.csv.gz  in=407,437,975 out=103,945,320 elapsed=201.4s

  [14321/17668] intraday_6652.csv.gz  in=407,451,732 out=103,945,320 elapsed=201.4s

  [14322/17668] intraday_6654.csv.gz  in=407,464,278 out=103,945,320 elapsed=201.5s

  [14323/17668] intraday_6656.csv.gz  in=407,478,452 out=103,945,320 elapsed=201.5s

  [14324/17668] intraday_6653.csv.gz  in=407,491,510 out=103,945,320 elapsed=201.5s

  [14325/17668] intraday_6655.csv.gz  in=407,504,662 out=103,945,320 elapsed=201.5s

  [14326/17668] intraday_6657.csv.gz  in=407,518,904 out=103,945,320 elapsed=201.5s

  [14327/17668] intraday_6658.csv.gz  in=407,531,313 out=103,945,320 elapsed=201.5s

  [14328/17668] intraday_6660.csv.gz  in=407,546,015 out=103,945,320 elapsed=201.5s

  [14329/17668] intraday_6661.csv.gz  in=407,560,107 out=103,945,320 elapsed=201.5s

  [14330/17668] intraday_6659.csv.gz  in=407,573,791 out=103,945,320 elapsed=201.5s

  [14331/17668] intraday_6662.csv.gz  in=407,586,722 out=103,945,320 elapsed=201.5s

  [14332/17668] intraday_6663.csv.gz  in=407,601,464 out=103,945,320 elapsed=201.5s

  [14333/17668] intraday_6666.csv.gz  in=407,615,191 out=103,945,320 elapsed=201.5s

  [14334/17668] intraday_6665.csv.gz  in=407,627,413 out=103,945,320 elapsed=201.6s

  [14335/17668] intraday_6664.csv.gz  in=407,642,996 out=103,945,320 elapsed=201.6s

  [14336/17668] intraday_6667.csv.gz  in=407,658,378 out=103,945,320 elapsed=201.6s

  [14337/17668] intraday_6668.csv.gz  in=407,671,433 out=103,945,320 elapsed=201.6s

  [14338/17668] intraday_6669.csv.gz  in=407,682,412 out=103,945,320 elapsed=201.6s

  [14339/17668] intraday_6670.csv.gz  in=407,697,142 out=103,945,320 elapsed=201.6s

  [14340/17668] intraday_6671.csv.gz  in=407,708,858 out=103,945,320 elapsed=201.6s

  [14341/17668] intraday_6672.csv.gz  in=407,723,968 out=103,945,320 elapsed=201.6s

  [14342/17668] intraday_6673.csv.gz  in=407,739,560 out=103,945,320 elapsed=201.6s

  [14343/17668] intraday_6674.csv.gz  in=407,756,116 out=103,945,320 elapsed=201.6s

  [14344/17668] intraday_6675.csv.gz  in=407,771,224 out=103,945,320 elapsed=201.7s

  [14345/17668] intraday_6676.csv.gz  in=407,783,653 out=103,945,320 elapsed=201.7s

  [14346/17668] intraday_6677.csv.gz  in=407,795,922 out=103,945,320 elapsed=201.7s

  [14347/17668] intraday_6678.csv.gz  in=407,807,930 out=103,945,320 elapsed=201.7s

  [14348/17668] intraday_6679.csv.gz  in=407,819,087 out=103,945,320 elapsed=201.7s

  [14349/17668] intraday_6680.csv.gz  in=407,834,008 out=103,945,320 elapsed=201.7s

  [14350/17668] intraday_6682.csv.gz  in=407,847,131 out=103,945,320 elapsed=201.7s

  [14351/17668] intraday_6681.csv.gz  in=407,857,960 out=103,945,320 elapsed=201.7s

  [14352/17668] intraday_6683.csv.gz  in=407,870,835 out=103,945,320 elapsed=201.7s

  [14353/17668] intraday_6684.csv.gz  in=407,886,626 out=103,945,320 elapsed=201.8s

  [14354/17668] intraday_6686.csv.gz  in=407,899,363 out=103,945,320 elapsed=201.8s

  [14355/17668] intraday_6685.csv.gz  in=407,915,900 out=103,945,320 elapsed=201.8s

  [14356/17668] intraday_6687.csv.gz  in=407,929,530 out=103,945,320 elapsed=201.8s

  [14357/17668] intraday_6688.csv.gz  in=407,943,478 out=103,945,320 elapsed=201.8s

  [14358/17668] intraday_6689.csv.gz  in=407,956,289 out=103,945,320 elapsed=201.8s

  [14359/17668] intraday_6690.csv.gz  in=407,970,566 out=103,945,320 elapsed=201.8s

  [14360/17668] intraday_6691.csv.gz  in=407,984,970 out=103,945,320 elapsed=201.8s

  [14361/17668] intraday_6692.csv.gz  in=407,998,636 out=103,945,320 elapsed=201.8s

  [14362/17668] intraday_6693.csv.gz  in=408,012,163 out=103,945,320 elapsed=201.8s

  [14363/17668] intraday_6694.csv.gz  in=408,023,669 out=103,945,320 elapsed=201.8s

  [14364/17668] intraday_6695.csv.gz  in=408,037,421 out=103,945,320 elapsed=201.8s

  [14365/17668] intraday_6696.csv.gz  in=408,049,334 out=103,945,320 elapsed=201.9s

  [14366/17668] intraday_6699.csv.gz  in=408,057,532 out=103,945,320 elapsed=201.9s

  [14367/17668] intraday_6697.csv.gz  in=408,069,689 out=103,945,320 elapsed=201.9s

  [14368/17668] intraday_6698.csv.gz  in=408,081,032 out=103,945,320 elapsed=201.9s

  [14369/17668] intraday_6700.csv.gz  in=408,094,078 out=103,945,320 elapsed=201.9s

  [14370/17668] intraday_6701.csv.gz  in=408,097,850 out=103,945,320 elapsed=201.9s

  [14371/17668] intraday_6702.csv.gz  in=408,097,886 out=103,945,320 elapsed=201.9s

  [14372/17668] intraday_6703.csv.gz  in=408,098,095 out=103,945,320 elapsed=201.9s

  [14373/17668] intraday_6706.csv.gz  in=408,098,105 out=103,945,320 elapsed=201.9s

  [14374/17668] intraday_6704.csv.gz  in=408,098,800 out=103,945,320 elapsed=201.9s

  [14375/17668] intraday_6705.csv.gz  in=408,098,824 out=103,945,320 elapsed=201.9s

  [14376/17668] intraday_6709.csv.gz  in=408,098,827 out=103,945,320 elapsed=201.9s

  [14377/17668] intraday_6707.csv.gz  in=408,098,848 out=103,945,320 elapsed=201.9s

  [14378/17668] intraday_6708.csv.gz  in=408,099,176 out=103,945,320 elapsed=201.9s

  [14379/17668] intraday_6710.csv.gz  in=408,099,201 out=103,945,320 elapsed=201.9s

  [14380/17668] intraday_6712.csv.gz  in=408,113,038 out=103,945,320 elapsed=202.0s

  [14381/17668] intraday_6711.csv.gz  in=408,130,746 out=103,945,320 elapsed=202.0s

  [14382/17668] intraday_6713.csv.gz  in=408,144,641 out=103,945,320 elapsed=202.0s

  [14383/17668] intraday_6714.csv.gz  in=408,157,386 out=103,945,320 elapsed=202.0s

  [14384/17668] intraday_6715.csv.gz  in=408,169,511 out=103,945,320 elapsed=202.0s

  [14385/17668] intraday_6717.csv.gz  in=408,185,878 out=103,945,320 elapsed=202.0s

  [14386/17668] intraday_6718.csv.gz  in=408,198,667 out=103,945,320 elapsed=202.0s

  [14387/17668] intraday_6716.csv.gz  in=408,214,249 out=103,945,320 elapsed=202.0s

  [14388/17668] intraday_6719.csv.gz  in=408,228,531 out=103,945,320 elapsed=202.0s

  [14389/17668] intraday_6721.csv.gz  in=408,244,486 out=103,945,320 elapsed=202.1s

  [14390/17668] intraday_6720.csv.gz  in=408,259,304 out=103,945,320 elapsed=202.1s

  [14391/17668] intraday_6722.csv.gz  in=408,274,303 out=103,945,320 elapsed=202.1s

  [14392/17668] intraday_6723.csv.gz  in=408,287,938 out=103,945,320 elapsed=202.1s

  [14393/17668] intraday_6725.csv.gz  in=408,299,130 out=103,945,320 elapsed=202.1s

  [14394/17668] intraday_6724.csv.gz  in=408,312,875 out=103,945,320 elapsed=202.1s

  [14395/17668] intraday_6726.csv.gz  in=408,325,794 out=103,945,320 elapsed=202.1s

  [14396/17668] intraday_6727.csv.gz  in=408,340,629 out=103,945,320 elapsed=202.1s

  [14397/17668] intraday_6728.csv.gz  in=408,355,111 out=103,945,320 elapsed=202.1s

  [14398/17668] intraday_6729.csv.gz  in=408,366,764 out=103,945,320 elapsed=202.1s

  [14399/17668] intraday_6731.csv.gz  in=408,379,027 out=103,945,320 elapsed=202.2s

  [14400/17668] intraday_6730.csv.gz  in=408,392,231 out=103,945,320 elapsed=202.2s

  [14401/17668] intraday_6732.csv.gz  in=408,405,521 out=103,945,320 elapsed=202.2s

  [14402/17668] intraday_6733.csv.gz  in=408,418,023 out=103,945,320 elapsed=202.2s

  [14403/17668] intraday_6734.csv.gz  in=408,432,153 out=103,945,320 elapsed=202.2s

  [14404/17668] intraday_6735.csv.gz  in=408,446,303 out=103,945,320 elapsed=202.2s

  [14405/17668] intraday_6737.csv.gz  in=408,457,589 out=103,945,320 elapsed=202.2s

  [14406/17668] intraday_6736.csv.gz  in=408,471,259 out=103,945,320 elapsed=202.2s

  [14407/17668] intraday_6738.csv.gz  in=408,484,839 out=103,945,320 elapsed=202.2s

  [14408/17668] intraday_6739.csv.gz  in=408,497,628 out=103,945,320 elapsed=202.2s

  [14409/17668] intraday_6743.csv.gz  in=408,508,175 out=103,945,320 elapsed=202.3s

  [14410/17668] intraday_6740.csv.gz  in=408,522,075 out=103,945,320 elapsed=202.3s

  [14411/17668] intraday_6741.csv.gz  in=408,541,114 out=103,945,320 elapsed=202.3s

  [14412/17668] intraday_6742.csv.gz  in=408,556,144 out=103,945,320 elapsed=202.3s

  [14413/17668] intraday_6744.csv.gz  in=408,569,788 out=103,945,320 elapsed=202.3s

  [14414/17668] intraday_6745.csv.gz  in=408,585,386 out=103,945,320 elapsed=202.3s

  [14415/17668] intraday_6747.csv.gz  in=408,599,385 out=103,945,320 elapsed=202.3s

  [14416/17668] intraday_6746.csv.gz  in=408,619,922 out=103,945,320 elapsed=202.3s

  [14417/17668] intraday_6748.csv.gz  in=408,632,218 out=103,945,320 elapsed=202.3s

  [14418/17668] intraday_6750.csv.gz  in=408,643,622 out=103,945,320 elapsed=202.3s

  [14419/17668] intraday_6749.csv.gz  in=408,656,957 out=103,945,320 elapsed=202.4s

  [14420/17668] intraday_6751.csv.gz  in=408,668,901 out=103,945,320 elapsed=202.4s

  [14421/17668] intraday_6752.csv.gz  in=408,681,792 out=103,945,320 elapsed=202.4s

  [14422/17668] intraday_6753.csv.gz  in=408,695,612 out=103,945,320 elapsed=202.4s

  [14423/17668] intraday_6756.csv.gz  in=408,708,505 out=103,945,320 elapsed=202.4s

  [14424/17668] intraday_6754.csv.gz  in=408,732,319 out=103,945,320 elapsed=202.4s

  [14425/17668] intraday_6755.csv.gz  in=408,745,919 out=103,945,320 elapsed=202.4s

  [14426/17668] intraday_6757.csv.gz  in=408,758,840 out=103,945,320 elapsed=202.4s

  [14427/17668] intraday_6759.csv.gz  in=408,771,106 out=103,945,320 elapsed=202.4s

  [14428/17668] intraday_6758.csv.gz  in=408,785,960 out=103,945,320 elapsed=202.4s

  [14429/17668] intraday_6760.csv.gz  in=408,799,489 out=103,945,320 elapsed=202.5s

  [14430/17668] intraday_6761.csv.gz  in=408,811,159 out=103,945,320 elapsed=202.5s

  [14431/17668] intraday_6762.csv.gz  in=408,822,851 out=103,945,320 elapsed=202.5s

  [14432/17668] intraday_6763.csv.gz  in=408,838,173 out=103,945,320 elapsed=202.5s

  [14433/17668] intraday_6764.csv.gz  in=408,848,307 out=103,945,320 elapsed=202.5s

  [14434/17668] intraday_6765.csv.gz  in=408,865,032 out=103,945,320 elapsed=202.5s

  [14435/17668] intraday_6766.csv.gz  in=408,879,111 out=103,945,320 elapsed=202.5s

  [14436/17668] intraday_6767.csv.gz  in=408,892,725 out=103,945,320 elapsed=202.5s

  [14437/17668] intraday_6768.csv.gz  in=408,906,601 out=103,945,320 elapsed=202.5s

  [14438/17668] intraday_6769.csv.gz  in=408,920,338 out=103,945,320 elapsed=202.5s

  [14439/17668] intraday_6771.csv.gz  in=408,933,756 out=103,945,320 elapsed=202.5s

  [14440/17668] intraday_6770.csv.gz  in=408,967,206 out=103,945,320 elapsed=202.6s

  [14441/17668] intraday_6773.csv.gz  in=408,978,889 out=103,945,320 elapsed=202.6s

  [14442/17668] intraday_6774.csv.gz  in=408,990,646 out=103,945,320 elapsed=202.6s

  [14443/17668] intraday_6775.csv.gz  in=409,002,615 out=103,945,320 elapsed=202.6s

  [14444/17668] intraday_6772.csv.gz  in=409,037,515 out=103,945,320 elapsed=202.6s

  [14445/17668] intraday_6776.csv.gz  in=409,053,997 out=103,945,320 elapsed=202.6s

  [14446/17668] intraday_6777.csv.gz  in=409,067,112 out=103,945,320 elapsed=202.6s

  [14447/17668] intraday_6779.csv.gz  in=409,080,153 out=103,945,320 elapsed=202.6s

  [14448/17668] intraday_6778.csv.gz  in=409,094,795 out=103,945,320 elapsed=202.6s

  [14449/17668] intraday_6780.csv.gz  in=409,106,648 out=103,945,320 elapsed=202.6s

  [14450/17668] intraday_6781.csv.gz  in=409,118,359 out=103,945,320 elapsed=202.6s

  [14451/17668] intraday_6782.csv.gz  in=409,131,504 out=103,945,320 elapsed=202.7s

  [14452/17668] intraday_6783.csv.gz  in=409,144,362 out=103,945,320 elapsed=202.7s

  [14453/17668] intraday_6785.csv.gz  in=409,156,207 out=103,945,320 elapsed=202.7s

  [14454/17668] intraday_6784.csv.gz  in=409,169,565 out=103,945,320 elapsed=202.7s

  [14455/17668] intraday_6786.csv.gz  in=409,182,869 out=103,945,320 elapsed=202.7s

  [14456/17668] intraday_6787.csv.gz  in=409,193,674 out=103,945,320 elapsed=202.7s

  [14457/17668] intraday_6788.csv.gz  in=409,207,518 out=103,945,320 elapsed=202.7s

  [14458/17668] intraday_6790.csv.gz  in=409,222,632 out=103,945,320 elapsed=202.7s

  [14459/17668] intraday_6789.csv.gz  in=409,234,776 out=103,945,320 elapsed=202.7s

  [14460/17668] intraday_6791.csv.gz  in=409,245,001 out=103,945,320 elapsed=202.7s

  [14461/17668] intraday_6792.csv.gz  in=409,256,631 out=103,945,320 elapsed=202.8s

  [14462/17668] intraday_6793.csv.gz  in=409,268,851 out=103,945,320 elapsed=202.8s

  [14463/17668] intraday_6794.csv.gz  in=409,288,694 out=103,945,320 elapsed=202.8s

  [14464/17668] intraday_6795.csv.gz  in=409,304,737 out=103,945,320 elapsed=202.8s

  [14465/17668] intraday_6796.csv.gz  in=409,319,915 out=103,945,320 elapsed=202.8s

  [14466/17668] intraday_6797.csv.gz  in=409,333,133 out=103,945,320 elapsed=202.8s

  [14467/17668] intraday_6799.csv.gz  in=409,347,719 out=103,945,320 elapsed=202.8s

  [14468/17668] intraday_6798.csv.gz  in=409,361,544 out=103,945,320 elapsed=202.8s

  [14469/17668] intraday_6800.csv.gz  in=409,377,931 out=103,945,320 elapsed=202.8s

  [14470/17668] intraday_6802.csv.gz  in=409,390,400 out=103,945,320 elapsed=202.9s

  [14471/17668] intraday_6803.csv.gz  in=409,406,912 out=103,945,320 elapsed=202.9s

  [14472/17668] intraday_6801.csv.gz  in=409,420,815 out=103,945,320 elapsed=202.9s

  [14473/17668] intraday_6804.csv.gz  in=409,436,311 out=103,945,320 elapsed=202.9s

  [14474/17668] intraday_6808.csv.gz  in=409,449,301 out=103,945,320 elapsed=202.9s

  [14475/17668] intraday_6806.csv.gz  in=409,463,550 out=103,945,320 elapsed=202.9s

  [14476/17668] intraday_6807.csv.gz  in=409,476,470 out=103,945,320 elapsed=202.9s

  [14477/17668] intraday_6805.csv.gz  in=409,490,110 out=103,945,320 elapsed=202.9s

  [14478/17668] intraday_6811.csv.gz  in=409,503,558 out=103,945,320 elapsed=202.9s

  [14479/17668] intraday_6812.csv.gz  in=409,517,093 out=103,945,320 elapsed=202.9s

  [14480/17668] intraday_6809.csv.gz  in=409,532,211 out=103,945,320 elapsed=203.0s

  [14481/17668] intraday_6810.csv.gz  in=409,546,282 out=103,945,320 elapsed=203.0s

  [14482/17668] intraday_6813.csv.gz  in=409,562,958 out=103,945,320 elapsed=203.0s

  [14483/17668] intraday_6815.csv.gz  in=409,577,334 out=103,945,320 elapsed=203.0s

  [14484/17668] intraday_6814.csv.gz  in=409,591,373 out=103,945,320 elapsed=203.0s

  [14485/17668] intraday_6816.csv.gz  in=409,603,118 out=103,945,320 elapsed=203.0s

  [14486/17668] intraday_6818.csv.gz  in=409,615,998 out=103,945,320 elapsed=203.0s

  [14487/17668] intraday_6820.csv.gz  in=409,632,017 out=103,945,320 elapsed=203.0s

  [14488/17668] intraday_6819.csv.gz  in=409,644,996 out=103,945,320 elapsed=203.0s

  [14489/17668] intraday_6817.csv.gz  in=409,663,711 out=103,945,320 elapsed=203.0s

  [14490/17668] intraday_6821.csv.gz  in=409,677,174 out=103,945,320 elapsed=203.1s

  [14491/17668] intraday_6822.csv.gz  in=409,689,917 out=103,945,320 elapsed=203.1s

  [14492/17668] intraday_6823.csv.gz  in=409,704,347 out=103,945,320 elapsed=203.1s

  [14493/17668] intraday_6824.csv.gz  in=409,717,474 out=103,945,320 elapsed=203.1s

  [14494/17668] intraday_6825.csv.gz  in=409,731,879 out=103,945,320 elapsed=203.1s

  [14495/17668] intraday_6826.csv.gz  in=409,749,214 out=103,945,320 elapsed=203.1s

  [14496/17668] intraday_6828.csv.gz  in=409,762,820 out=103,945,320 elapsed=203.1s

  [14497/17668] intraday_6827.csv.gz  in=409,779,034 out=103,945,320 elapsed=203.1s

  [14498/17668] intraday_6829.csv.gz  in=409,795,930 out=103,945,320 elapsed=203.1s

  [14499/17668] intraday_6830.csv.gz  in=409,811,294 out=103,945,320 elapsed=203.2s

  [14500/17668] intraday_6831.csv.gz  in=409,824,168 out=103,945,320 elapsed=203.2s

  [14501/17668] intraday_6832.csv.gz  in=409,835,879 out=103,945,320 elapsed=203.2s

  [14502/17668] intraday_6833.csv.gz  in=409,850,662 out=103,945,320 elapsed=203.2s

  [14503/17668] intraday_6834.csv.gz  in=409,862,136 out=103,945,320 elapsed=203.2s

  [14504/17668] intraday_6835.csv.gz  in=409,879,418 out=103,945,320 elapsed=203.2s

  [14505/17668] intraday_6836.csv.gz  in=409,891,556 out=103,945,320 elapsed=203.2s

  [14506/17668] intraday_6837.csv.gz  in=409,908,547 out=103,945,320 elapsed=203.2s

  [14507/17668] intraday_6838.csv.gz  in=409,922,051 out=103,945,320 elapsed=203.2s

  [14508/17668] intraday_6839.csv.gz  in=409,935,057 out=103,945,320 elapsed=203.2s

  [14509/17668] intraday_6842.csv.gz  in=409,947,673 out=103,945,320 elapsed=203.2s

  [14510/17668] intraday_6840.csv.gz  in=409,960,826 out=103,945,320 elapsed=203.3s

  [14511/17668] intraday_6841.csv.gz  in=409,973,364 out=103,945,320 elapsed=203.3s

  [14512/17668] intraday_6843.csv.gz  in=409,990,272 out=103,945,320 elapsed=203.3s

  [14513/17668] intraday_6844.csv.gz  in=410,005,749 out=103,945,320 elapsed=203.3s

  [14514/17668] intraday_6845.csv.gz  in=410,020,779 out=103,945,320 elapsed=203.3s

  [14515/17668] intraday_6847.csv.gz  in=410,035,132 out=103,945,320 elapsed=203.3s

  [14516/17668] intraday_6846.csv.gz  in=410,056,817 out=103,945,320 elapsed=203.3s

  [14517/17668] intraday_6849.csv.gz  in=410,071,241 out=103,945,320 elapsed=203.3s

  [14518/17668] intraday_6848.csv.gz  in=410,082,401 out=103,945,320 elapsed=203.3s

  [14519/17668] intraday_6850.csv.gz  in=410,093,773 out=103,945,320 elapsed=203.3s

  [14520/17668] intraday_6851.csv.gz  in=410,108,871 out=103,945,320 elapsed=203.3s

  [14521/17668] intraday_6852.csv.gz  in=410,118,398 out=103,945,320 elapsed=203.4s

  [14522/17668] intraday_6853.csv.gz  in=410,128,620 out=103,945,320 elapsed=203.4s

  [14523/17668] intraday_6854.csv.gz  in=410,141,023 out=103,945,320 elapsed=203.4s

  [14524/17668] intraday_6856.csv.gz  in=410,154,034 out=103,945,320 elapsed=203.4s

  [14525/17668] intraday_6858.csv.gz  in=410,164,736 out=103,945,320 elapsed=203.4s

  [14526/17668] intraday_6857.csv.gz  in=410,177,977 out=103,945,320 elapsed=203.4s

  [14527/17668] intraday_6855.csv.gz  in=410,225,376 out=103,945,320 elapsed=203.4s

  [14528/17668] intraday_6859.csv.gz  in=410,239,285 out=103,945,320 elapsed=203.4s

  [14529/17668] intraday_6861.csv.gz  in=410,255,701 out=103,945,320 elapsed=203.4s

  [14530/17668] intraday_6860.csv.gz  in=410,270,003 out=103,945,320 elapsed=203.4s

  [14531/17668] intraday_6862.csv.gz  in=410,282,623 out=103,945,320 elapsed=203.4s

  [14532/17668] intraday_6863.csv.gz  in=410,295,374 out=103,945,320 elapsed=203.5s

  [14533/17668] intraday_6864.csv.gz  in=410,310,312 out=103,945,320 elapsed=203.5s

  [14534/17668] intraday_6866.csv.gz  in=410,325,226 out=103,945,320 elapsed=203.5s

  [14535/17668] intraday_6865.csv.gz  in=410,340,717 out=103,945,320 elapsed=203.5s

  [14536/17668] intraday_6868.csv.gz  in=410,354,177 out=103,945,320 elapsed=203.5s

  [14537/17668] intraday_6867.csv.gz  in=410,367,978 out=103,945,320 elapsed=203.5s

  [14538/17668] intraday_6870.csv.gz  in=410,377,577 out=103,945,320 elapsed=203.5s

  [14539/17668] intraday_6869.csv.gz  in=410,387,939 out=103,945,320 elapsed=203.5s

  [14540/17668] intraday_6873.csv.gz  in=410,398,648 out=103,945,320 elapsed=203.5s

  [14541/17668] intraday_6874.csv.gz  in=410,410,430 out=103,945,320 elapsed=203.5s

  [14542/17668] intraday_6872.csv.gz  in=410,424,617 out=103,945,320 elapsed=203.6s

  [14543/17668] intraday_6871.csv.gz  in=410,440,237 out=103,945,320 elapsed=203.6s

  [14544/17668] intraday_6875.csv.gz  in=410,453,485 out=103,945,320 elapsed=203.6s

  [14545/17668] intraday_6878.csv.gz  in=410,466,959 out=103,945,320 elapsed=203.6s

  [14546/17668] intraday_6876.csv.gz  in=410,479,436 out=103,945,320 elapsed=203.6s

  [14547/17668] intraday_6877.csv.gz  in=410,490,481 out=103,945,320 elapsed=203.6s

  [14548/17668] intraday_6879.csv.gz  in=410,504,081 out=103,945,320 elapsed=203.6s

  [14549/17668] intraday_6880.csv.gz  in=410,516,643 out=103,945,320 elapsed=203.6s

  [14550/17668] intraday_6881.csv.gz  in=410,528,629 out=103,945,320 elapsed=203.6s

  [14551/17668] intraday_6882.csv.gz  in=410,540,769 out=103,945,320 elapsed=203.7s

  [14552/17668] intraday_6883.csv.gz  in=410,553,647 out=103,945,320 elapsed=203.7s

  [14553/17668] intraday_6884.csv.gz  in=410,567,697 out=103,945,320 elapsed=203.7s

  [14554/17668] intraday_6887.csv.gz  in=410,578,115 out=103,945,320 elapsed=203.7s

  [14555/17668] intraday_6885.csv.gz  in=410,595,880 out=103,945,320 elapsed=203.7s

  [14556/17668] intraday_6886.csv.gz  in=410,611,189 out=103,945,320 elapsed=203.7s

  [14557/17668] intraday_6888.csv.gz  in=410,625,702 out=103,945,320 elapsed=203.7s

  [14558/17668] intraday_6889.csv.gz  in=410,640,587 out=103,945,320 elapsed=203.7s

  [14559/17668] intraday_6890.csv.gz  in=410,652,852 out=103,945,320 elapsed=203.7s

  [14560/17668] intraday_6891.csv.gz  in=410,666,049 out=103,945,320 elapsed=203.7s

  [14561/17668] intraday_6892.csv.gz  in=410,676,905 out=103,945,320 elapsed=203.7s

  [14562/17668] intraday_6893.csv.gz  in=410,690,429 out=103,945,320 elapsed=203.8s

  [14563/17668] intraday_6894.csv.gz  in=410,701,334 out=103,945,320 elapsed=203.8s

  [14564/17668] intraday_6895.csv.gz  in=410,712,432 out=103,945,320 elapsed=203.8s

  [14565/17668] intraday_6896.csv.gz  in=410,724,741 out=103,945,320 elapsed=203.8s

  [14566/17668] intraday_6898.csv.gz  in=410,737,831 out=103,945,320 elapsed=203.8s

  [14567/17668] intraday_6900.csv.gz  in=410,750,005 out=103,945,320 elapsed=203.8s

  [14568/17668] intraday_6897.csv.gz  in=410,764,106 out=103,945,320 elapsed=203.8s

  [14569/17668] intraday_6899.csv.gz  in=410,777,448 out=103,945,320 elapsed=203.8s

  [14570/17668] intraday_6901.csv.gz  in=410,789,131 out=103,945,320 elapsed=203.9s

  [14571/17668] intraday_6902.csv.gz  in=410,803,275 out=103,945,320 elapsed=203.9s

  [14572/17668] intraday_6903.csv.gz  in=410,815,107 out=103,945,320 elapsed=203.9s

  [14573/17668] intraday_6904.csv.gz  in=410,827,989 out=103,945,320 elapsed=203.9s

  [14574/17668] intraday_6906.csv.gz  in=410,838,308 out=103,945,320 elapsed=203.9s

  [14575/17668] intraday_6907.csv.gz  in=410,854,952 out=103,945,320 elapsed=203.9s

  [14576/17668] intraday_6908.csv.gz  in=410,864,488 out=103,945,320 elapsed=203.9s

  [14577/17668] intraday_6905.csv.gz  in=410,875,814 out=103,945,320 elapsed=203.9s

  [14578/17668] intraday_6909.csv.gz  in=410,892,610 out=103,945,320 elapsed=203.9s

  [14579/17668] intraday_6911.csv.gz  in=410,906,544 out=103,945,320 elapsed=203.9s

  [14580/17668] intraday_6912.csv.gz  in=410,918,670 out=103,945,320 elapsed=203.9s

  [14581/17668] intraday_6910.csv.gz  in=410,932,311 out=103,945,320 elapsed=203.9s

  [14582/17668] intraday_6913.csv.gz  in=410,946,055 out=103,945,320 elapsed=204.0s

  [14583/17668] intraday_6914.csv.gz  in=410,959,975 out=103,945,320 elapsed=204.0s

  [14584/17668] intraday_6915.csv.gz  in=410,973,413 out=103,945,320 elapsed=204.0s

  [14585/17668] intraday_6916.csv.gz  in=410,988,361 out=103,945,320 elapsed=204.0s

  [14586/17668] intraday_6918.csv.gz  in=410,999,485 out=103,945,320 elapsed=204.0s

  [14587/17668] intraday_6917.csv.gz  in=411,010,936 out=103,945,320 elapsed=204.0s

  [14588/17668] intraday_6919.csv.gz  in=411,022,172 out=103,945,320 elapsed=204.0s

  [14589/17668] intraday_6921.csv.gz  in=411,035,233 out=103,945,320 elapsed=204.0s

  [14590/17668] intraday_6920.csv.gz  in=411,050,317 out=103,945,320 elapsed=204.0s

  [14591/17668] intraday_6923.csv.gz  in=411,062,591 out=103,945,320 elapsed=204.0s

  [14592/17668] intraday_6922.csv.gz  in=411,076,881 out=103,945,320 elapsed=204.1s

  [14593/17668] intraday_6924.csv.gz  in=411,088,370 out=103,945,320 elapsed=204.1s

  [14594/17668] intraday_6925.csv.gz  in=411,101,335 out=103,945,320 elapsed=204.1s

  [14595/17668] intraday_6927.csv.gz  in=411,113,831 out=103,945,320 elapsed=204.1s

  [14596/17668] intraday_6926.csv.gz  in=411,126,304 out=103,945,320 elapsed=204.1s

  [14597/17668] intraday_6929.csv.gz  in=411,138,233 out=103,945,320 elapsed=204.1s

  [14598/17668] intraday_6928.csv.gz  in=411,152,680 out=103,945,320 elapsed=204.1s

  [14599/17668] intraday_6930.csv.gz  in=411,165,645 out=103,945,320 elapsed=204.1s

  [14600/17668] intraday_6932.csv.gz  in=411,179,615 out=103,945,320 elapsed=204.1s

  [14601/17668] intraday_6931.csv.gz  in=411,190,628 out=103,945,320 elapsed=204.2s

  [14602/17668] intraday_6933.csv.gz  in=411,202,650 out=103,945,320 elapsed=204.2s

  [14603/17668] intraday_6935.csv.gz  in=411,212,349 out=103,945,320 elapsed=204.2s

  [14604/17668] intraday_6934.csv.gz  in=411,226,230 out=103,945,320 elapsed=204.2s

  [14605/17668] intraday_6936.csv.gz  in=411,237,930 out=103,945,320 elapsed=204.2s

  [14606/17668] intraday_6937.csv.gz  in=411,251,272 out=103,945,320 elapsed=204.2s

  [14607/17668] intraday_6940.csv.gz  in=411,265,029 out=103,945,320 elapsed=204.2s

  [14608/17668] intraday_6938.csv.gz  in=411,281,752 out=103,945,320 elapsed=204.2s

  [14609/17668] intraday_6939.csv.gz  in=411,297,371 out=103,945,320 elapsed=204.2s

  [14610/17668] intraday_6941.csv.gz  in=411,310,388 out=103,945,320 elapsed=204.2s

  [14611/17668] intraday_6942.csv.gz  in=411,322,192 out=103,945,320 elapsed=204.2s

  [14612/17668] intraday_6944.csv.gz  in=411,339,754 out=103,945,320 elapsed=204.3s

  [14613/17668] intraday_6943.csv.gz  in=411,354,094 out=103,945,320 elapsed=204.3s

  [14614/17668] intraday_6946.csv.gz  in=411,365,765 out=103,945,320 elapsed=204.3s

  [14615/17668] intraday_6945.csv.gz  in=411,397,277 out=103,945,320 elapsed=204.3s

  [14616/17668] intraday_6947.csv.gz  in=411,412,733 out=103,945,320 elapsed=204.3s

  [14617/17668] intraday_6948.csv.gz  in=411,427,954 out=103,945,320 elapsed=204.3s

  [14618/17668] intraday_6949.csv.gz  in=411,442,433 out=103,945,320 elapsed=204.3s

  [14619/17668] intraday_6950.csv.gz  in=411,456,003 out=103,945,320 elapsed=204.3s

  [14620/17668] intraday_6953.csv.gz  in=411,470,273 out=103,945,320 elapsed=204.3s

  [14621/17668] intraday_6951.csv.gz  in=411,483,358 out=103,945,320 elapsed=204.4s

  [14622/17668] intraday_6952.csv.gz  in=411,495,675 out=103,945,320 elapsed=204.4s

  [14623/17668] intraday_6956.csv.gz  in=411,508,795 out=103,945,320 elapsed=204.4s

  [14624/17668] intraday_6955.csv.gz  in=411,520,031 out=103,945,320 elapsed=204.4s

  [14625/17668] intraday_6954.csv.gz  in=411,534,305 out=103,945,320 elapsed=204.4s

  [14626/17668] intraday_6957.csv.gz  in=411,550,038 out=103,945,320 elapsed=204.4s

  [14627/17668] intraday_6958.csv.gz  in=411,563,957 out=103,945,320 elapsed=204.4s

  [14628/17668] intraday_6959.csv.gz  in=411,577,856 out=103,945,320 elapsed=204.4s

  [14629/17668] intraday_6960.csv.gz  in=411,591,639 out=103,945,320 elapsed=204.4s

  [14630/17668] intraday_6961.csv.gz  in=411,607,752 out=103,945,320 elapsed=204.4s

  [14631/17668] intraday_6963.csv.gz  in=411,620,773 out=103,945,320 elapsed=204.4s

  [14632/17668] intraday_6962.csv.gz  in=411,633,406 out=103,945,320 elapsed=204.5s

  [14633/17668] intraday_6964.csv.gz  in=411,648,817 out=103,945,320 elapsed=204.5s

  [14634/17668] intraday_6965.csv.gz  in=411,662,866 out=103,945,320 elapsed=204.5s

  [14635/17668] intraday_6966.csv.gz  in=411,673,833 out=103,945,320 elapsed=204.5s

  [14636/17668] intraday_6967.csv.gz  in=411,689,030 out=103,945,320 elapsed=204.5s

  [14637/17668] intraday_6968.csv.gz  in=411,701,411 out=103,945,320 elapsed=204.5s

  [14638/17668] intraday_6969.csv.gz  in=411,715,394 out=103,945,320 elapsed=204.5s

  [14639/17668] intraday_6970.csv.gz  in=411,731,112 out=103,945,320 elapsed=204.5s

  [14640/17668] intraday_6972.csv.gz  in=411,746,323 out=103,945,320 elapsed=204.5s

  [14641/17668] intraday_6974.csv.gz  in=411,759,001 out=103,945,320 elapsed=204.5s

  [14642/17668] intraday_6973.csv.gz  in=411,773,105 out=103,945,320 elapsed=204.5s

  [14643/17668] intraday_6971.csv.gz  in=411,789,577 out=103,945,320 elapsed=204.5s

  [14644/17668] intraday_6976.csv.gz  in=411,800,329 out=103,945,320 elapsed=204.6s

  [14645/17668] intraday_6977.csv.gz  in=411,815,365 out=103,945,320 elapsed=204.6s

  [14646/17668] intraday_6978.csv.gz  in=411,826,967 out=103,945,320 elapsed=204.6s

  [14647/17668] intraday_6975.csv.gz  in=411,839,851 out=103,945,320 elapsed=204.6s

  [14648/17668] intraday_6979.csv.gz  in=411,853,643 out=103,945,320 elapsed=204.6s

  [14649/17668] intraday_6980.csv.gz  in=411,866,233 out=103,945,320 elapsed=204.6s

  [14650/17668] intraday_6982.csv.gz  in=411,878,509 out=103,945,320 elapsed=204.6s

  [14651/17668] intraday_6981.csv.gz  in=411,893,998 out=103,945,320 elapsed=204.6s

  [14652/17668] intraday_6983.csv.gz  in=411,905,947 out=103,945,320 elapsed=204.6s

  [14653/17668] intraday_6984.csv.gz  in=411,918,245 out=103,945,320 elapsed=204.6s

  [14654/17668] intraday_6986.csv.gz  in=411,929,438 out=103,945,320 elapsed=204.6s

  [14655/17668] intraday_6985.csv.gz  in=411,942,812 out=103,945,320 elapsed=204.7s

  [14656/17668] intraday_6988.csv.gz  in=411,957,242 out=103,945,320 elapsed=204.7s

  [14657/17668] intraday_6987.csv.gz  in=411,972,798 out=103,945,320 elapsed=204.7s

  [14658/17668] intraday_6989.csv.gz  in=411,987,719 out=103,945,320 elapsed=204.7s

  [14659/17668] intraday_6992.csv.gz  in=411,999,629 out=103,945,320 elapsed=204.7s

  [14660/17668] intraday_6991.csv.gz  in=412,010,931 out=103,945,320 elapsed=204.7s

  [14661/17668] intraday_6990.csv.gz  in=412,050,502 out=103,945,320 elapsed=204.7s

  [14662/17668] intraday_6993.csv.gz  in=412,064,117 out=103,945,320 elapsed=204.7s

  [14663/17668] intraday_6994.csv.gz  in=412,076,500 out=103,945,320 elapsed=204.7s

  [14664/17668] intraday_6995.csv.gz  in=412,088,667 out=103,945,320 elapsed=204.7s

  [14665/17668] intraday_6996.csv.gz  in=412,098,333 out=103,945,320 elapsed=204.8s

  [14666/17668] intraday_6998.csv.gz  in=412,105,626 out=103,945,320 elapsed=204.8s

  [14667/17668] intraday_6997.csv.gz  in=412,118,982 out=103,945,320 elapsed=204.8s

  [14668/17668] intraday_7000.csv.gz  in=412,131,311 out=103,945,320 elapsed=204.8s

  [14669/17668] intraday_6999.csv.gz  in=412,147,850 out=103,945,320 elapsed=204.8s

  [14670/17668] intraday_7001.csv.gz  in=412,161,427 out=103,945,320 elapsed=204.8s

  [14671/17668] intraday_7002.csv.gz  in=412,171,859 out=103,945,320 elapsed=204.8s

  [14672/17668] intraday_7003.csv.gz  in=412,185,519 out=103,945,320 elapsed=204.8s

  [14673/17668] intraday_7004.csv.gz  in=412,200,671 out=103,945,320 elapsed=204.8s

  [14674/17668] intraday_7005.csv.gz  in=412,217,527 out=103,945,320 elapsed=204.8s

  [14675/17668] intraday_7006.csv.gz  in=412,229,395 out=103,945,320 elapsed=204.8s

  [14676/17668] intraday_7007.csv.gz  in=412,242,895 out=103,945,320 elapsed=204.8s

  [14677/17668] intraday_7008.csv.gz  in=412,257,108 out=103,945,320 elapsed=204.9s

  [14678/17668] intraday_7011.csv.gz  in=412,269,739 out=103,945,320 elapsed=204.9s

  [14679/17668] intraday_7009.csv.gz  in=412,286,067 out=103,945,320 elapsed=204.9s

  [14680/17668] intraday_7010.csv.gz  in=412,301,302 out=103,945,320 elapsed=204.9s

  [14681/17668] intraday_7012.csv.gz  in=412,315,209 out=103,945,320 elapsed=204.9s

  [14682/17668] intraday_7013.csv.gz  in=412,324,695 out=103,945,320 elapsed=204.9s

  [14683/17668] intraday_7014.csv.gz  in=412,334,809 out=103,945,320 elapsed=204.9s

  [14684/17668] intraday_7015.csv.gz  in=412,350,037 out=103,945,320 elapsed=204.9s

  [14685/17668] intraday_7018.csv.gz  in=412,361,346 out=103,945,320 elapsed=204.9s

  [14686/17668] intraday_7016.csv.gz  in=412,375,396 out=103,945,320 elapsed=205.0s

  [14687/17668] intraday_7019.csv.gz  in=412,387,562 out=103,945,320 elapsed=205.0s

  [14688/17668] intraday_7017.csv.gz  in=412,399,667 out=103,945,320 elapsed=205.0s

  [14689/17668] intraday_7023.csv.gz  in=412,413,003 out=103,945,320 elapsed=205.0s

  [14690/17668] intraday_7021.csv.gz  in=412,424,943 out=103,945,320 elapsed=205.0s

  [14691/17668] intraday_7020.csv.gz  in=412,437,602 out=103,945,320 elapsed=205.0s

  [14692/17668] intraday_7022.csv.gz  in=412,450,798 out=103,945,320 elapsed=205.0s

  [14693/17668] intraday_7024.csv.gz  in=412,464,909 out=103,945,320 elapsed=205.0s

  [14694/17668] intraday_7025.csv.gz  in=412,476,455 out=103,945,320 elapsed=205.0s

  [14695/17668] intraday_7026.csv.gz  in=412,489,432 out=103,945,320 elapsed=205.0s

  [14696/17668] intraday_7027.csv.gz  in=412,500,717 out=103,945,320 elapsed=205.0s

  [14697/17668] intraday_7028.csv.gz  in=412,515,270 out=103,945,320 elapsed=205.1s

  [14698/17668] intraday_7029.csv.gz  in=412,533,473 out=103,945,320 elapsed=205.1s

  [14699/17668] intraday_7031.csv.gz  in=412,544,464 out=103,945,320 elapsed=205.1s

  [14700/17668] intraday_7030.csv.gz  in=412,559,229 out=103,945,320 elapsed=205.1s

  [14701/17668] intraday_7032.csv.gz  in=412,574,917 out=103,945,320 elapsed=205.1s

  [14702/17668] intraday_7034.csv.gz  in=412,587,354 out=103,945,320 elapsed=205.1s

  [14703/17668] intraday_7033.csv.gz  in=412,602,484 out=103,945,320 elapsed=205.1s

  [14704/17668] intraday_7035.csv.gz  in=412,614,958 out=103,945,320 elapsed=205.1s

  [14705/17668] intraday_7036.csv.gz  in=412,626,542 out=103,945,320 elapsed=205.2s

  [14706/17668] intraday_7037.csv.gz  in=412,639,380 out=103,945,320 elapsed=205.2s

  [14707/17668] intraday_7039.csv.gz  in=412,650,841 out=103,945,320 elapsed=205.2s

  [14708/17668] intraday_7038.csv.gz  in=412,661,261 out=103,945,320 elapsed=205.2s

  [14709/17668] intraday_7042.csv.gz  in=412,674,940 out=103,945,320 elapsed=205.2s

  [14710/17668] intraday_7043.csv.gz  in=412,688,285 out=103,945,320 elapsed=205.2s

  [14711/17668] intraday_7040.csv.gz  in=412,700,592 out=103,945,320 elapsed=205.2s

  [14712/17668] intraday_7041.csv.gz  in=412,713,347 out=103,945,320 elapsed=205.2s

  [14713/17668] intraday_7044.csv.gz  in=412,726,072 out=103,945,320 elapsed=205.2s

  [14714/17668] intraday_7045.csv.gz  in=412,738,327 out=103,945,320 elapsed=205.2s

  [14715/17668] intraday_7046.csv.gz  in=412,750,644 out=103,945,320 elapsed=205.2s

  [14716/17668] intraday_7047.csv.gz  in=412,764,604 out=103,945,320 elapsed=205.2s

  [14717/17668] intraday_7049.csv.gz  in=412,776,173 out=103,945,320 elapsed=205.3s

  [14718/17668] intraday_7050.csv.gz  in=412,786,308 out=103,945,320 elapsed=205.3s

  [14719/17668] intraday_7048.csv.gz  in=412,798,804 out=103,945,320 elapsed=205.3s

  [14720/17668] intraday_7051.csv.gz  in=412,814,174 out=103,945,320 elapsed=205.3s

  [14721/17668] intraday_7052.csv.gz  in=412,824,081 out=103,945,320 elapsed=205.3s

  [14722/17668] intraday_7053.csv.gz  in=412,838,819 out=103,945,320 elapsed=205.3s

  [14723/17668] intraday_7055.csv.gz  in=412,852,026 out=103,945,320 elapsed=205.3s

  [14724/17668] intraday_7054.csv.gz  in=412,867,181 out=103,945,320 elapsed=205.3s

  [14725/17668] intraday_7056.csv.gz  in=412,880,077 out=103,945,320 elapsed=205.3s

  [14726/17668] intraday_7057.csv.gz  in=412,893,086 out=103,945,320 elapsed=205.3s

  [14727/17668] intraday_7058.csv.gz  in=412,906,925 out=103,945,320 elapsed=205.3s

  [14728/17668] intraday_7059.csv.gz  in=412,920,867 out=103,945,320 elapsed=205.3s

  [14729/17668] intraday_7060.csv.gz  in=412,934,383 out=103,945,320 elapsed=205.4s

  [14730/17668] intraday_7062.csv.gz  in=412,946,061 out=103,945,320 elapsed=205.4s

  [14731/17668] intraday_7061.csv.gz  in=412,958,163 out=103,945,320 elapsed=205.4s

  [14732/17668] intraday_7063.csv.gz  in=412,969,482 out=103,945,320 elapsed=205.4s

  [14733/17668] intraday_7065.csv.gz  in=412,982,420 out=103,945,320 elapsed=205.4s

  [14734/17668] intraday_7064.csv.gz  in=412,997,515 out=103,945,320 elapsed=205.4s

  [14735/17668] intraday_7066.csv.gz  in=413,011,617 out=103,945,320 elapsed=205.4s

  [14736/17668] intraday_7067.csv.gz  in=413,025,247 out=103,945,320 elapsed=205.4s

  [14737/17668] intraday_7069.csv.gz  in=413,036,717 out=103,945,320 elapsed=205.4s

  [14738/17668] intraday_7070.csv.gz  in=413,049,589 out=103,945,320 elapsed=205.5s

  [14739/17668] intraday_7068.csv.gz  in=413,070,701 out=103,945,320 elapsed=205.5s

  [14740/17668] intraday_7071.csv.gz  in=413,083,607 out=103,945,320 elapsed=205.5s

  [14741/17668] intraday_7072.csv.gz  in=413,098,134 out=103,945,320 elapsed=205.5s

  [14742/17668] intraday_7073.csv.gz  in=413,109,523 out=103,945,320 elapsed=205.5s

  [14743/17668] intraday_7075.csv.gz  in=413,120,276 out=103,945,320 elapsed=205.5s

  [14744/17668] intraday_7074.csv.gz  in=413,133,400 out=103,945,320 elapsed=205.5s

  [14745/17668] intraday_7076.csv.gz  in=413,147,289 out=103,945,320 elapsed=205.5s

  [14746/17668] intraday_7078.csv.gz  in=413,159,900 out=103,945,320 elapsed=205.5s

  [14747/17668] intraday_7077.csv.gz  in=413,182,561 out=103,945,320 elapsed=205.5s

  [14748/17668] intraday_7079.csv.gz  in=413,198,195 out=103,945,320 elapsed=205.5s

  [14749/17668] intraday_7081.csv.gz  in=413,209,636 out=103,945,320 elapsed=205.5s

  [14750/17668] intraday_7080.csv.gz  in=413,231,532 out=103,945,320 elapsed=205.6s

  [14751/17668] intraday_7082.csv.gz  in=413,249,111 out=103,945,320 elapsed=205.6s

  [14752/17668] intraday_7083.csv.gz  in=413,266,018 out=103,945,320 elapsed=205.6s

  [14753/17668] intraday_7084.csv.gz  in=413,280,423 out=103,945,320 elapsed=205.6s

  [14754/17668] intraday_7087.csv.gz  in=413,295,944 out=103,945,320 elapsed=205.6s

  [14755/17668] intraday_7086.csv.gz  in=413,307,423 out=103,945,320 elapsed=205.6s

  [14756/17668] intraday_7085.csv.gz  in=413,319,433 out=103,945,320 elapsed=205.6s

  [14757/17668] intraday_7088.csv.gz  in=413,332,411 out=103,945,320 elapsed=205.6s

  [14758/17668] intraday_7089.csv.gz  in=413,348,432 out=103,945,320 elapsed=205.6s

  [14759/17668] intraday_7090.csv.gz  in=413,361,316 out=103,945,320 elapsed=205.6s

  [14760/17668] intraday_7091.csv.gz  in=413,375,924 out=103,945,320 elapsed=205.6s

  [14761/17668] intraday_7092.csv.gz  in=413,391,070 out=103,945,320 elapsed=205.7s

  [14762/17668] intraday_7093.csv.gz  in=413,404,127 out=103,945,320 elapsed=205.7s

  [14763/17668] intraday_7094.csv.gz  in=413,419,710 out=103,945,320 elapsed=205.7s

  [14764/17668] intraday_7095.csv.gz  in=413,445,952 out=103,945,320 elapsed=205.7s

  [14765/17668] intraday_7096.csv.gz  in=413,459,764 out=103,945,320 elapsed=205.7s

  [14766/17668] intraday_7097.csv.gz  in=413,473,669 out=103,945,320 elapsed=205.7s

  [14767/17668] intraday_7098.csv.gz  in=413,487,161 out=103,945,320 elapsed=205.7s

  [14768/17668] intraday_7099.csv.gz  in=413,499,354 out=103,945,320 elapsed=205.8s

  [14769/17668] intraday_7100.csv.gz  in=413,513,188 out=103,945,320 elapsed=205.8s

  [14770/17668] intraday_7101.csv.gz  in=413,530,127 out=103,945,320 elapsed=205.8s

  [14771/17668] intraday_7103.csv.gz  in=413,541,715 out=103,945,320 elapsed=205.8s

  [14772/17668] intraday_7104.csv.gz  in=413,554,640 out=103,945,320 elapsed=205.8s

  [14773/17668] intraday_7102.csv.gz  in=413,570,366 out=103,945,320 elapsed=205.8s

  [14774/17668] intraday_7106.csv.gz  in=413,582,198 out=103,945,320 elapsed=205.8s

  [14775/17668] intraday_7107.csv.gz  in=413,594,440 out=103,945,320 elapsed=205.8s

  [14776/17668] intraday_7105.csv.gz  in=413,612,585 out=103,945,320 elapsed=205.8s

  [14777/17668] intraday_7108.csv.gz  in=413,628,502 out=103,945,320 elapsed=205.8s

  [14778/17668] intraday_7110.csv.gz  in=413,641,246 out=103,945,320 elapsed=205.8s

  [14779/17668] intraday_7112.csv.gz  in=413,653,877 out=103,945,320 elapsed=205.9s

  [14780/17668] intraday_7111.csv.gz  in=413,666,965 out=103,945,320 elapsed=205.9s

  [14781/17668] intraday_7109.csv.gz  in=413,682,022 out=103,945,320 elapsed=205.9s

  [14782/17668] intraday_7113.csv.gz  in=413,693,974 out=103,945,320 elapsed=205.9s

  [14783/17668] intraday_7114.csv.gz  in=413,711,764 out=103,945,320 elapsed=205.9s

  [14784/17668] intraday_7115.csv.gz  in=413,726,048 out=103,945,320 elapsed=205.9s

  [14785/17668] intraday_7116.csv.gz  in=413,741,263 out=103,945,320 elapsed=205.9s

  [14786/17668] intraday_7118.csv.gz  in=413,755,057 out=103,945,320 elapsed=205.9s

  [14787/17668] intraday_7117.csv.gz  in=413,771,213 out=103,945,320 elapsed=205.9s

  [14788/17668] intraday_7119.csv.gz  in=413,783,219 out=103,945,320 elapsed=205.9s

  [14789/17668] intraday_7120.csv.gz  in=413,795,659 out=103,945,320 elapsed=205.9s

  [14790/17668] intraday_7121.csv.gz  in=413,808,920 out=103,945,320 elapsed=205.9s

  [14791/17668] intraday_7122.csv.gz  in=413,820,779 out=103,945,320 elapsed=206.0s

  [14792/17668] intraday_7124.csv.gz  in=413,834,211 out=103,945,320 elapsed=206.0s

  [14793/17668] intraday_7125.csv.gz  in=413,848,241 out=103,945,320 elapsed=206.0s

  [14794/17668] intraday_7126.csv.gz  in=413,863,195 out=103,945,320 elapsed=206.0s

  [14795/17668] intraday_7123.csv.gz  in=413,898,667 out=103,945,320 elapsed=206.0s

  [14796/17668] intraday_7127.csv.gz  in=413,911,401 out=103,945,320 elapsed=206.0s

  [14797/17668] intraday_7128.csv.gz  in=413,923,334 out=103,945,320 elapsed=206.0s

  [14798/17668] intraday_7130.csv.gz  in=413,935,753 out=103,945,320 elapsed=206.0s

  [14799/17668] intraday_7129.csv.gz  in=413,949,716 out=103,945,320 elapsed=206.0s

  [14800/17668] intraday_7134.csv.gz  in=413,964,368 out=103,945,320 elapsed=206.1s

  [14801/17668] intraday_7131.csv.gz  in=413,976,674 out=103,945,320 elapsed=206.1s

  [14802/17668] intraday_7132.csv.gz  in=413,991,447 out=103,945,320 elapsed=206.1s

  [14803/17668] intraday_7133.csv.gz  in=414,006,745 out=103,945,320 elapsed=206.1s

  [14804/17668] intraday_7136.csv.gz  in=414,017,781 out=103,945,320 elapsed=206.1s

  [14805/17668] intraday_7138.csv.gz  in=414,029,796 out=103,945,320 elapsed=206.1s

  [14806/17668] intraday_7135.csv.gz  in=414,043,592 out=103,945,320 elapsed=206.1s

  [14807/17668] intraday_7137.csv.gz  in=414,057,187 out=103,945,320 elapsed=206.1s

  [14808/17668] intraday_7140.csv.gz  in=414,066,869 out=103,945,320 elapsed=206.1s

  [14809/17668] intraday_7139.csv.gz  in=414,081,879 out=103,945,320 elapsed=206.1s

  [14810/17668] intraday_7141.csv.gz  in=414,091,589 out=103,945,320 elapsed=206.2s

  [14811/17668] intraday_7142.csv.gz  in=414,105,345 out=103,945,320 elapsed=206.2s

  [14812/17668] intraday_7143.csv.gz  in=414,105,986 out=103,945,320 elapsed=206.2s

  [14813/17668] intraday_7144.csv.gz  in=414,122,863 out=103,945,320 elapsed=206.2s

  [14814/17668] intraday_7145.csv.gz  in=414,137,354 out=103,945,320 elapsed=206.2s

  [14815/17668] intraday_7146.csv.gz  in=414,150,448 out=103,945,320 elapsed=206.2s

  [14816/17668] intraday_7147.csv.gz  in=414,161,742 out=103,945,320 elapsed=206.2s

  [14817/17668] intraday_7148.csv.gz  in=414,173,364 out=103,945,320 elapsed=206.2s

  [14818/17668] intraday_7150.csv.gz  in=414,188,663 out=103,945,320 elapsed=206.2s

  [14819/17668] intraday_7151.csv.gz  in=414,200,656 out=103,945,320 elapsed=206.2s

  [14820/17668] intraday_7149.csv.gz  in=414,215,222 out=103,945,320 elapsed=206.2s

  [14821/17668] intraday_7152.csv.gz  in=414,228,445 out=103,945,320 elapsed=206.2s

  [14822/17668] intraday_7153.csv.gz  in=414,241,919 out=103,945,320 elapsed=206.2s

  [14823/17668] intraday_7154.csv.gz  in=414,261,731 out=103,945,320 elapsed=206.3s

  [14824/17668] intraday_7156.csv.gz  in=414,274,708 out=103,945,320 elapsed=206.3s

  [14825/17668] intraday_7155.csv.gz  in=414,290,697 out=103,945,320 elapsed=206.3s

  [14826/17668] intraday_7157.csv.gz  in=414,303,653 out=103,945,320 elapsed=206.3s

  [14827/17668] intraday_7158.csv.gz  in=414,313,356 out=103,945,320 elapsed=206.3s

  [14828/17668] intraday_7160.csv.gz  in=414,328,285 out=103,945,320 elapsed=206.3s

  [14829/17668] intraday_7159.csv.gz  in=414,337,178 out=103,945,320 elapsed=206.3s

  [14830/17668] intraday_7162.csv.gz  in=414,349,633 out=103,945,320 elapsed=206.3s

  [14831/17668] intraday_7161.csv.gz  in=414,362,970 out=103,945,320 elapsed=206.3s

  [14832/17668] intraday_7163.csv.gz  in=414,373,508 out=103,945,320 elapsed=206.3s

  [14833/17668] intraday_7164.csv.gz  in=414,386,415 out=103,945,320 elapsed=206.3s

  [14834/17668] intraday_7165.csv.gz  in=414,400,073 out=103,945,320 elapsed=206.4s

  [14835/17668] intraday_7166.csv.gz  in=414,410,745 out=103,945,320 elapsed=206.4s

  [14836/17668] intraday_7167.csv.gz  in=414,423,286 out=103,945,320 elapsed=206.4s

  [14837/17668] intraday_7168.csv.gz  in=414,436,339 out=103,945,320 elapsed=206.4s

  [14838/17668] intraday_7170.csv.gz  in=414,446,921 out=103,945,320 elapsed=206.4s

  [14839/17668] intraday_7169.csv.gz  in=414,460,318 out=103,945,320 elapsed=206.4s

  [14840/17668] intraday_7171.csv.gz  in=414,475,301 out=103,945,320 elapsed=206.4s

  [14841/17668] intraday_7174.csv.gz  in=414,491,605 out=103,945,320 elapsed=206.4s

  [14842/17668] intraday_7172.csv.gz  in=414,502,902 out=103,945,320 elapsed=206.4s

  [14843/17668] intraday_7173.csv.gz  in=414,516,230 out=103,945,320 elapsed=206.4s

  [14844/17668] intraday_7175.csv.gz  in=414,529,798 out=103,945,320 elapsed=206.5s

  [14845/17668] intraday_7176.csv.gz  in=414,541,441 out=103,945,320 elapsed=206.5s

  [14846/17668] intraday_7178.csv.gz  in=414,555,414 out=103,945,320 elapsed=206.5s

  [14847/17668] intraday_7179.csv.gz  in=414,566,482 out=103,945,320 elapsed=206.5s

  [14848/17668] intraday_7177.csv.gz  in=414,578,139 out=103,945,320 elapsed=206.5s

  [14849/17668] intraday_7180.csv.gz  in=414,592,418 out=103,945,320 elapsed=206.5s

  [14850/17668] intraday_7181.csv.gz  in=414,602,177 out=103,945,320 elapsed=206.5s

  [14851/17668] intraday_7182.csv.gz  in=414,613,999 out=103,945,320 elapsed=206.5s

  [14852/17668] intraday_7184.csv.gz  in=414,625,321 out=103,945,320 elapsed=206.5s

  [14853/17668] intraday_7183.csv.gz  in=414,636,345 out=103,945,320 elapsed=206.5s

  [14854/17668] intraday_7185.csv.gz  in=414,648,732 out=103,945,320 elapsed=206.6s

  [14855/17668] intraday_7187.csv.gz  in=414,660,135 out=103,945,320 elapsed=206.6s

  [14856/17668] intraday_7188.csv.gz  in=414,674,376 out=103,945,320 elapsed=206.6s

  [14857/17668] intraday_7186.csv.gz  in=414,689,393 out=103,945,320 elapsed=206.6s

  [14858/17668] intraday_7189.csv.gz  in=414,702,045 out=103,945,320 elapsed=206.6s

  [14859/17668] intraday_7190.csv.gz  in=414,712,848 out=103,945,320 elapsed=206.6s

  [14860/17668] intraday_7192.csv.gz  in=414,725,020 out=103,945,320 elapsed=206.6s

  [14861/17668] intraday_7191.csv.gz  in=414,738,560 out=103,945,320 elapsed=206.6s

  [14862/17668] intraday_7193.csv.gz  in=414,750,282 out=103,945,320 elapsed=206.6s

  [14863/17668] intraday_7194.csv.gz  in=414,760,638 out=103,945,320 elapsed=206.6s

  [14864/17668] intraday_7195.csv.gz  in=414,771,677 out=103,945,320 elapsed=206.6s

  [14865/17668] intraday_7197.csv.gz  in=414,782,999 out=103,945,320 elapsed=206.7s

  [14866/17668] intraday_7196.csv.gz  in=414,796,624 out=103,945,320 elapsed=206.7s

  [14867/17668] intraday_7198.csv.gz  in=414,810,995 out=103,945,320 elapsed=206.7s

  [14868/17668] intraday_7199.csv.gz  in=414,824,743 out=103,945,320 elapsed=206.7s

  [14869/17668] intraday_7200.csv.gz  in=414,837,939 out=103,945,320 elapsed=206.7s

  [14870/17668] intraday_7201.csv.gz  in=414,848,616 out=103,945,320 elapsed=206.7s

  [14871/17668] intraday_7202.csv.gz  in=414,860,761 out=103,945,320 elapsed=206.7s

  [14872/17668] intraday_7203.csv.gz  in=414,875,241 out=103,945,320 elapsed=206.7s

  [14873/17668] intraday_7204.csv.gz  in=414,888,330 out=103,945,320 elapsed=206.7s

  [14874/17668] intraday_7205.csv.gz  in=414,901,109 out=103,945,320 elapsed=206.7s

  [14875/17668] intraday_7206.csv.gz  in=414,912,521 out=103,945,320 elapsed=206.8s

  [14876/17668] intraday_7207.csv.gz  in=414,922,307 out=103,945,320 elapsed=206.8s

  [14877/17668] intraday_7208.csv.gz  in=414,933,080 out=103,945,320 elapsed=206.8s

  [14878/17668] intraday_7209.csv.gz  in=414,948,956 out=103,945,320 elapsed=206.8s

  [14879/17668] intraday_7212.csv.gz  in=414,961,215 out=103,945,320 elapsed=206.8s

  [14880/17668] intraday_7210.csv.gz  in=414,974,361 out=103,945,320 elapsed=206.8s

  [14881/17668] intraday_7211.csv.gz  in=414,987,715 out=103,945,320 elapsed=206.8s

  [14882/17668] intraday_7215.csv.gz  in=414,999,431 out=103,945,320 elapsed=206.8s

  [14883/17668] intraday_7213.csv.gz  in=415,016,767 out=103,945,320 elapsed=206.8s

  [14884/17668] intraday_7216.csv.gz  in=415,028,233 out=103,945,320 elapsed=206.8s

  [14885/17668] intraday_7214.csv.gz  in=415,040,944 out=103,945,320 elapsed=206.8s

  [14886/17668] intraday_7217.csv.gz  in=415,054,237 out=103,945,320 elapsed=206.9s

  [14887/17668] intraday_7220.csv.gz  in=415,067,413 out=103,945,320 elapsed=206.9s

  [14888/17668] intraday_7218.csv.gz  in=415,079,120 out=103,945,320 elapsed=206.9s

  [14889/17668] intraday_7219.csv.gz  in=415,092,699 out=103,945,320 elapsed=206.9s

  [14890/17668] intraday_7221.csv.gz  in=415,104,957 out=103,945,320 elapsed=206.9s

  [14891/17668] intraday_7222.csv.gz  in=415,115,586 out=103,945,320 elapsed=206.9s

  [14892/17668] intraday_7223.csv.gz  in=415,128,699 out=103,945,320 elapsed=206.9s

  [14893/17668] intraday_7224.csv.gz  in=415,139,425 out=103,945,320 elapsed=206.9s

  [14894/17668] intraday_7226.csv.gz  in=415,152,333 out=103,945,320 elapsed=206.9s

  [14895/17668] intraday_7225.csv.gz  in=415,164,283 out=103,945,320 elapsed=206.9s

  [14896/17668] intraday_7229.csv.gz  in=415,177,824 out=103,945,320 elapsed=207.0s

  [14897/17668] intraday_7230.csv.gz  in=415,190,335 out=103,945,320 elapsed=207.0s

  [14898/17668] intraday_7228.csv.gz  in=415,204,775 out=103,945,320 elapsed=207.0s

  [14899/17668] intraday_7227.csv.gz  in=415,221,015 out=103,945,320 elapsed=207.0s

  [14900/17668] intraday_7231.csv.gz  in=415,232,496 out=103,945,320 elapsed=207.0s

  [14901/17668] intraday_7232.csv.gz  in=415,245,149 out=103,945,320 elapsed=207.0s

  [14902/17668] intraday_7234.csv.gz  in=415,256,917 out=103,945,320 elapsed=207.0s

  [14903/17668] intraday_7233.csv.gz  in=415,273,830 out=103,945,320 elapsed=207.0s

  [14904/17668] intraday_7238.csv.gz  in=415,287,220 out=103,945,320 elapsed=207.0s

  [14905/17668] intraday_7237.csv.gz  in=415,300,587 out=103,945,320 elapsed=207.0s

  [14906/17668] intraday_7236.csv.gz  in=415,314,279 out=103,945,320 elapsed=207.0s

  [14907/17668] intraday_7235.csv.gz  in=415,325,807 out=103,945,320 elapsed=207.0s

  [14908/17668] intraday_7240.csv.gz  in=415,338,368 out=103,945,320 elapsed=207.1s

  [14909/17668] intraday_7239.csv.gz  in=415,350,758 out=103,945,320 elapsed=207.1s

  [14910/17668] intraday_7241.csv.gz  in=415,362,118 out=103,945,320 elapsed=207.1s

  [14911/17668] intraday_7242.csv.gz  in=415,376,516 out=103,945,320 elapsed=207.1s

  [14912/17668] intraday_7244.csv.gz  in=415,386,714 out=103,945,320 elapsed=207.1s

  [14913/17668] intraday_7243.csv.gz  in=415,422,615 out=103,945,320 elapsed=207.1s

  [14914/17668] intraday_7245.csv.gz  in=415,435,194 out=103,945,320 elapsed=207.1s

  [14915/17668] intraday_7246.csv.gz  in=415,449,629 out=103,945,320 elapsed=207.1s

  [14916/17668] intraday_7247.csv.gz  in=415,462,501 out=103,945,320 elapsed=207.2s

  [14917/17668] intraday_7248.csv.gz  in=415,477,672 out=103,945,320 elapsed=207.2s

  [14918/17668] intraday_7249.csv.gz  in=415,490,148 out=103,945,320 elapsed=207.2s

  [14919/17668] intraday_7250.csv.gz  in=415,506,139 out=103,945,320 elapsed=207.2s

  [14920/17668] intraday_7251.csv.gz  in=415,519,263 out=103,945,320 elapsed=207.2s

  [14921/17668] intraday_7252.csv.gz  in=415,532,291 out=103,945,320 elapsed=207.2s

  [14922/17668] intraday_7254.csv.gz  in=415,546,800 out=103,945,320 elapsed=207.2s

  [14923/17668] intraday_7255.csv.gz  in=415,557,126 out=103,945,320 elapsed=207.2s

  [14924/17668] intraday_7253.csv.gz  in=415,572,700 out=103,945,320 elapsed=207.2s

  [14925/17668] intraday_7257.csv.gz  in=415,583,116 out=103,945,320 elapsed=207.3s

  [14926/17668] intraday_7256.csv.gz  in=415,598,203 out=103,945,320 elapsed=207.3s

  [14927/17668] intraday_7258.csv.gz  in=415,612,867 out=103,945,320 elapsed=207.3s

  [14928/17668] intraday_7259.csv.gz  in=415,628,976 out=103,945,320 elapsed=207.3s

  [14929/17668] intraday_7260.csv.gz  in=415,645,411 out=103,945,320 elapsed=207.3s

  [14930/17668] intraday_7261.csv.gz  in=415,659,950 out=103,945,320 elapsed=207.3s

  [14931/17668] intraday_7262.csv.gz  in=415,674,993 out=103,945,320 elapsed=207.3s

  [14932/17668] intraday_7264.csv.gz  in=415,686,143 out=103,945,320 elapsed=207.3s

  [14933/17668] intraday_7263.csv.gz  in=415,699,685 out=103,945,320 elapsed=207.3s

  [14934/17668] intraday_7266.csv.gz  in=415,713,972 out=103,945,320 elapsed=207.3s

  [14935/17668] intraday_7265.csv.gz  in=415,724,609 out=103,945,320 elapsed=207.3s

  [14936/17668] intraday_7267.csv.gz  in=415,735,708 out=103,945,320 elapsed=207.3s

  [14937/17668] intraday_7268.csv.gz  in=415,748,932 out=103,945,320 elapsed=207.3s

  [14938/17668] intraday_7270.csv.gz  in=415,764,186 out=103,945,320 elapsed=207.4s

  [14939/17668] intraday_7271.csv.gz  in=415,776,992 out=103,945,320 elapsed=207.4s

  [14940/17668] intraday_7269.csv.gz  in=415,789,464 out=103,945,320 elapsed=207.4s

  [14941/17668] intraday_7272.csv.gz  in=415,801,962 out=103,945,320 elapsed=207.4s

  [14942/17668] intraday_7273.csv.gz  in=415,813,769 out=103,945,320 elapsed=207.4s

  [14943/17668] intraday_7274.csv.gz  in=415,826,331 out=103,945,320 elapsed=207.4s

  [14944/17668] intraday_7275.csv.gz  in=415,838,188 out=103,945,320 elapsed=207.4s

  [14945/17668] intraday_7277.csv.gz  in=415,852,250 out=103,945,320 elapsed=207.4s

  [14946/17668] intraday_7276.csv.gz  in=415,868,756 out=103,945,320 elapsed=207.4s

  [14947/17668] intraday_7278.csv.gz  in=415,882,586 out=103,945,320 elapsed=207.5s

  [14948/17668] intraday_7279.csv.gz  in=415,897,159 out=103,945,320 elapsed=207.5s

  [14949/17668] intraday_7280.csv.gz  in=415,908,828 out=103,945,320 elapsed=207.5s

  [14950/17668] intraday_7281.csv.gz  in=415,920,193 out=103,945,320 elapsed=207.5s

  [14951/17668] intraday_7283.csv.gz  in=415,932,106 out=103,945,320 elapsed=207.5s

  [14952/17668] intraday_7282.csv.gz  in=415,945,772 out=103,945,320 elapsed=207.5s

  [14953/17668] intraday_7284.csv.gz  in=415,958,432 out=103,945,320 elapsed=207.5s

  [14954/17668] intraday_7285.csv.gz  in=415,966,328 out=103,945,320 elapsed=207.5s

  [14955/17668] intraday_7287.csv.gz  in=415,973,079 out=103,945,320 elapsed=207.5s

  [14956/17668] intraday_7288.csv.gz  in=415,989,475 out=103,945,320 elapsed=207.5s

  [14957/17668] intraday_7286.csv.gz  in=416,002,033 out=103,945,320 elapsed=207.6s

  [14958/17668] intraday_7289.csv.gz  in=416,017,375 out=103,945,320 elapsed=207.6s

  [14959/17668] intraday_7290.csv.gz  in=416,030,245 out=103,945,320 elapsed=207.6s

  [14960/17668] intraday_7291.csv.gz  in=416,041,968 out=103,945,320 elapsed=207.6s

  [14961/17668] intraday_7293.csv.gz  in=416,056,162 out=103,945,320 elapsed=207.6s

  [14962/17668] intraday_7292.csv.gz  in=416,068,486 out=103,945,320 elapsed=207.6s

  [14963/17668] intraday_7296.csv.gz  in=416,082,474 out=103,945,320 elapsed=207.6s

  [14964/17668] intraday_7295.csv.gz  in=416,094,005 out=103,945,320 elapsed=207.6s

  [14965/17668] intraday_7294.csv.gz  in=416,110,400 out=103,945,320 elapsed=207.6s

  [14966/17668] intraday_7297.csv.gz  in=416,125,003 out=103,945,320 elapsed=207.6s

  [14967/17668] intraday_7298.csv.gz  in=416,141,550 out=103,945,320 elapsed=207.6s

  [14968/17668] intraday_7299.csv.gz  in=416,156,652 out=103,945,320 elapsed=207.6s

  [14969/17668] intraday_7300.csv.gz  in=416,169,508 out=103,945,320 elapsed=207.7s

  [14970/17668] intraday_7301.csv.gz  in=416,186,481 out=103,945,320 elapsed=207.7s

  [14971/17668] intraday_7303.csv.gz  in=416,198,125 out=103,945,320 elapsed=207.7s

  [14972/17668] intraday_7302.csv.gz  in=416,208,616 out=103,945,320 elapsed=207.7s

  [14973/17668] intraday_7304.csv.gz  in=416,223,719 out=103,945,320 elapsed=207.7s

  [14974/17668] intraday_7305.csv.gz  in=416,236,947 out=103,945,320 elapsed=207.7s

  [14975/17668] intraday_7307.csv.gz  in=416,249,487 out=103,945,320 elapsed=207.7s

  [14976/17668] intraday_7306.csv.gz  in=416,262,145 out=103,945,320 elapsed=207.7s

  [14977/17668] intraday_7308.csv.gz  in=416,275,102 out=103,945,320 elapsed=207.8s

  [14978/17668] intraday_7311.csv.gz  in=416,287,697 out=103,945,320 elapsed=207.8s

  [14979/17668] intraday_7310.csv.gz  in=416,300,426 out=103,945,320 elapsed=207.8s

  [14980/17668] intraday_7309.csv.gz  in=416,313,437 out=103,945,320 elapsed=207.8s

  [14981/17668] intraday_7314.csv.gz  in=416,324,275 out=103,945,320 elapsed=207.8s

  [14982/17668] intraday_7315.csv.gz  in=416,336,799 out=103,945,320 elapsed=207.8s

  [14983/17668] intraday_7313.csv.gz  in=416,350,326 out=103,945,320 elapsed=207.8s

  [14984/17668] intraday_7312.csv.gz  in=416,364,030 out=103,945,320 elapsed=207.8s

  [14985/17668] intraday_7316.csv.gz  in=416,376,041 out=103,945,320 elapsed=207.8s

  [14986/17668] intraday_7317.csv.gz  in=416,390,236 out=103,945,320 elapsed=207.8s

  [14987/17668] intraday_7318.csv.gz  in=416,406,600 out=103,945,320 elapsed=207.8s

  [14988/17668] intraday_7319.csv.gz  in=416,420,641 out=103,945,320 elapsed=207.8s

  [14989/17668] intraday_7320.csv.gz  in=416,430,634 out=103,945,320 elapsed=207.9s

  [14990/17668] intraday_7321.csv.gz  in=416,445,188 out=103,945,320 elapsed=207.9s

  [14991/17668] intraday_7323.csv.gz  in=416,458,027 out=103,945,320 elapsed=207.9s

  [14992/17668] intraday_7322.csv.gz  in=416,472,024 out=103,945,320 elapsed=207.9s

  [14993/17668] intraday_7324.csv.gz  in=416,484,552 out=103,945,320 elapsed=207.9s

  [14994/17668] intraday_7325.csv.gz  in=416,496,161 out=103,945,320 elapsed=207.9s

  [14995/17668] intraday_7326.csv.gz  in=416,509,809 out=103,945,320 elapsed=207.9s

  [14996/17668] intraday_7327.csv.gz  in=416,522,290 out=103,945,320 elapsed=207.9s

  [14997/17668] intraday_7328.csv.gz  in=416,533,861 out=103,945,320 elapsed=207.9s

  [14998/17668] intraday_7329.csv.gz  in=416,546,440 out=103,945,320 elapsed=207.9s

  [14999/17668] intraday_7330.csv.gz  in=416,559,389 out=103,945,320 elapsed=207.9s

  [15000/17668] intraday_7331.csv.gz  in=416,573,849 out=103,945,320 elapsed=207.9s

  [15001/17668] intraday_7333.csv.gz  in=416,585,968 out=103,945,320 elapsed=208.0s

  [15002/17668] intraday_7332.csv.gz  in=416,600,923 out=103,945,320 elapsed=208.0s

  [15003/17668] intraday_7334.csv.gz  in=416,613,194 out=103,945,320 elapsed=208.0s

  [15004/17668] intraday_7337.csv.gz  in=416,625,923 out=103,945,320 elapsed=208.0s

  [15005/17668] intraday_7335.csv.gz  in=416,639,526 out=103,945,320 elapsed=208.0s

  [15006/17668] intraday_7336.csv.gz  in=416,651,953 out=103,945,320 elapsed=208.0s

  [15007/17668] intraday_7338.csv.gz  in=416,662,896 out=103,945,320 elapsed=208.0s

  [15008/17668] intraday_7339.csv.gz  in=416,674,700 out=103,945,320 elapsed=208.0s

  [15009/17668] intraday_7340.csv.gz  in=416,689,541 out=103,945,320 elapsed=208.0s

  [15010/17668] intraday_7341.csv.gz  in=416,699,751 out=103,945,320 elapsed=208.0s

  [15011/17668] intraday_7342.csv.gz  in=416,715,326 out=103,945,320 elapsed=208.0s

  [15012/17668] intraday_7344.csv.gz  in=416,730,674 out=103,945,320 elapsed=208.1s

  [15013/17668] intraday_7343.csv.gz  in=416,743,737 out=103,945,320 elapsed=208.1s

  [15014/17668] intraday_7345.csv.gz  in=416,755,787 out=103,945,320 elapsed=208.1s

  [15015/17668] intraday_7346.csv.gz  in=416,768,791 out=103,945,320 elapsed=208.1s

  [15016/17668] intraday_7347.csv.gz  in=416,782,082 out=103,945,320 elapsed=208.1s

  [15017/17668] intraday_7348.csv.gz  in=416,795,094 out=103,945,320 elapsed=208.1s

  [15018/17668] intraday_7349.csv.gz  in=416,809,076 out=103,945,320 elapsed=208.1s

  [15019/17668] intraday_7350.csv.gz  in=416,820,959 out=103,945,320 elapsed=208.1s

  [15020/17668] intraday_7351.csv.gz  in=416,832,126 out=103,945,320 elapsed=208.1s

  [15021/17668] intraday_7354.csv.gz  in=416,845,530 out=103,945,320 elapsed=208.1s

  [15022/17668] intraday_7353.csv.gz  in=416,860,750 out=103,945,320 elapsed=208.1s

  [15023/17668] intraday_7352.csv.gz  in=416,872,167 out=103,945,320 elapsed=208.1s

  [15024/17668] intraday_7357.csv.gz  in=416,884,837 out=103,945,320 elapsed=208.2s

  [15025/17668] intraday_7356.csv.gz  in=416,897,313 out=103,945,320 elapsed=208.2s

  [15026/17668] intraday_7355.csv.gz  in=416,912,280 out=103,945,320 elapsed=208.2s

  [15027/17668] intraday_7358.csv.gz  in=416,923,475 out=103,945,320 elapsed=208.2s

  [15028/17668] intraday_7359.csv.gz  in=416,935,498 out=103,945,320 elapsed=208.2s

  [15029/17668] intraday_7361.csv.gz  in=416,949,445 out=103,945,320 elapsed=208.2s

  [15030/17668] intraday_7360.csv.gz  in=416,962,183 out=103,945,320 elapsed=208.2s

  [15031/17668] intraday_7362.csv.gz  in=416,974,123 out=103,945,320 elapsed=208.2s

  [15032/17668] intraday_7364.csv.gz  in=416,984,118 out=103,945,320 elapsed=208.2s

  [15033/17668] intraday_7363.csv.gz  in=416,996,053 out=103,945,320 elapsed=208.3s

  [15034/17668] intraday_7365.csv.gz  in=417,011,017 out=103,945,320 elapsed=208.3s

  [15035/17668] intraday_7367.csv.gz  in=417,023,095 out=103,945,320 elapsed=208.3s

  [15036/17668] intraday_7366.csv.gz  in=417,034,864 out=103,945,320 elapsed=208.3s

  [15037/17668] intraday_7368.csv.gz  in=417,045,763 out=103,945,320 elapsed=208.3s

  [15038/17668] intraday_7370.csv.gz  in=417,057,896 out=103,945,320 elapsed=208.3s

  [15039/17668] intraday_7369.csv.gz  in=417,067,464 out=103,945,320 elapsed=208.3s

  [15040/17668] intraday_7372.csv.gz  in=417,085,243 out=103,945,320 elapsed=208.3s

  [15041/17668] intraday_7371.csv.gz  in=417,103,179 out=103,945,320 elapsed=208.3s

  [15042/17668] intraday_7373.csv.gz  in=417,116,992 out=103,945,320 elapsed=208.4s

  [15043/17668] intraday_7374.csv.gz  in=417,127,539 out=103,945,320 elapsed=208.4s

  [15044/17668] intraday_7375.csv.gz  in=417,140,356 out=103,945,320 elapsed=208.4s

  [15045/17668] intraday_7376.csv.gz  in=417,155,662 out=103,945,320 elapsed=208.4s

  [15046/17668] intraday_7378.csv.gz  in=417,170,601 out=103,945,320 elapsed=208.4s

  [15047/17668] intraday_7377.csv.gz  in=417,184,687 out=103,945,320 elapsed=208.4s

  [15048/17668] intraday_7379.csv.gz  in=417,199,329 out=103,945,320 elapsed=208.4s

  [15049/17668] intraday_7380.csv.gz  in=417,212,830 out=103,945,320 elapsed=208.4s

  [15050/17668] intraday_7382.csv.gz  in=417,226,461 out=103,945,320 elapsed=208.4s

  [15051/17668] intraday_7383.csv.gz  in=417,240,203 out=103,945,320 elapsed=208.4s

  [15052/17668] intraday_7381.csv.gz  in=417,253,931 out=103,945,320 elapsed=208.5s

  [15053/17668] intraday_7384.csv.gz  in=417,265,238 out=103,945,320 elapsed=208.5s

  [15054/17668] intraday_7385.csv.gz  in=417,279,001 out=103,945,320 elapsed=208.5s

  [15055/17668] intraday_7388.csv.gz  in=417,290,912 out=103,945,320 elapsed=208.5s

  [15056/17668] intraday_7386.csv.gz  in=417,304,473 out=103,945,320 elapsed=208.5s

  [15057/17668] intraday_7387.csv.gz  in=417,317,939 out=103,945,320 elapsed=208.5s

  [15058/17668] intraday_7390.csv.gz  in=417,330,679 out=103,945,320 elapsed=208.5s

  [15059/17668] intraday_7392.csv.gz  in=417,342,745 out=103,945,320 elapsed=208.5s

  [15060/17668] intraday_7391.csv.gz  in=417,359,101 out=103,945,320 elapsed=208.5s

  [15061/17668] intraday_7389.csv.gz  in=417,373,521 out=103,945,320 elapsed=208.5s

  [15062/17668] intraday_7394.csv.gz  in=417,390,775 out=103,945,320 elapsed=208.6s

  [15063/17668] intraday_7396.csv.gz  in=417,402,747 out=103,945,320 elapsed=208.6s

  [15064/17668] intraday_7395.csv.gz  in=417,415,887 out=103,945,320 elapsed=208.6s

  [15065/17668] intraday_7393.csv.gz  in=417,428,532 out=103,945,320 elapsed=208.6s

  [15066/17668] intraday_7398.csv.gz  in=417,444,440 out=103,945,320 elapsed=208.6s

  [15067/17668] intraday_7397.csv.gz  in=417,460,489 out=103,945,320 elapsed=208.6s

  [15068/17668] intraday_7400.csv.gz  in=417,473,832 out=103,945,320 elapsed=208.6s

  [15069/17668] intraday_7399.csv.gz  in=417,486,399 out=103,945,320 elapsed=208.6s

  [15070/17668] intraday_7402.csv.gz  in=417,498,934 out=103,945,320 elapsed=208.6s

  [15071/17668] intraday_7404.csv.gz  in=417,513,508 out=103,945,320 elapsed=208.6s

  [15072/17668] intraday_7401.csv.gz  in=417,527,193 out=103,945,320 elapsed=208.7s

  [15073/17668] intraday_7403.csv.gz  in=417,546,231 out=103,945,320 elapsed=208.7s

  [15074/17668] intraday_7405.csv.gz  in=417,561,467 out=103,945,320 elapsed=208.7s

  [15075/17668] intraday_7407.csv.gz  in=417,576,406 out=103,945,320 elapsed=208.7s

  [15076/17668] intraday_7406.csv.gz  in=417,593,816 out=103,945,320 elapsed=208.7s

  [15077/17668] intraday_7408.csv.gz  in=417,606,824 out=103,945,320 elapsed=208.7s

  [15078/17668] intraday_7409.csv.gz  in=417,618,972 out=103,945,320 elapsed=208.7s

  [15079/17668] intraday_7410.csv.gz  in=417,632,294 out=103,945,320 elapsed=208.7s

  [15080/17668] intraday_7411.csv.gz  in=417,643,788 out=103,945,320 elapsed=208.7s

  [15081/17668] intraday_7412.csv.gz  in=417,657,899 out=103,945,320 elapsed=208.7s

  [15082/17668] intraday_7413.csv.gz  in=417,670,590 out=103,945,320 elapsed=208.7s

  [15083/17668] intraday_7416.csv.gz  in=417,684,179 out=103,945,320 elapsed=208.8s

  [15084/17668] intraday_7415.csv.gz  in=417,698,348 out=103,945,320 elapsed=208.8s

  [15085/17668] intraday_7414.csv.gz  in=417,714,344 out=103,945,320 elapsed=208.8s

  [15086/17668] intraday_7417.csv.gz  in=417,726,150 out=103,945,320 elapsed=208.8s

  [15087/17668] intraday_7418.csv.gz  in=417,740,623 out=103,945,320 elapsed=208.8s

  [15088/17668] intraday_7419.csv.gz  in=417,752,721 out=103,945,320 elapsed=208.8s

  [15089/17668] intraday_7420.csv.gz  in=417,765,586 out=103,945,320 elapsed=208.8s

  [15090/17668] intraday_7421.csv.gz  in=417,781,397 out=103,945,320 elapsed=208.8s

  [15091/17668] intraday_7425.csv.gz  in=417,794,378 out=103,945,320 elapsed=208.8s

  [15092/17668] intraday_7422.csv.gz  in=417,809,359 out=103,945,320 elapsed=208.9s

  [15093/17668] intraday_7424.csv.gz  in=417,823,978 out=103,945,320 elapsed=208.9s

  [15094/17668] intraday_7423.csv.gz  in=417,844,089 out=103,945,320 elapsed=208.9s

  [15095/17668] intraday_7427.csv.gz  in=417,854,790 out=103,945,320 elapsed=208.9s

  [15096/17668] intraday_7426.csv.gz  in=417,868,398 out=103,945,320 elapsed=208.9s

  [15097/17668] intraday_7429.csv.gz  in=417,879,310 out=103,945,320 elapsed=208.9s

  [15098/17668] intraday_7428.csv.gz  in=417,893,922 out=103,945,320 elapsed=208.9s

  [15099/17668] intraday_7430.csv.gz  in=417,903,184 out=103,945,320 elapsed=208.9s

  [15100/17668] intraday_7433.csv.gz  in=417,903,292 out=103,945,320 elapsed=208.9s

  [15101/17668] intraday_7434.csv.gz  in=417,903,327 out=103,945,320 elapsed=208.9s

  [15102/17668] intraday_7432.csv.gz  in=417,905,420 out=103,945,320 elapsed=208.9s

  [15103/17668] intraday_7431.csv.gz  in=417,918,939 out=103,945,320 elapsed=208.9s

  [15104/17668] intraday_7435.csv.gz  in=417,918,961 out=103,945,320 elapsed=208.9s

  [15105/17668] intraday_7438.csv.gz  in=417,919,004 out=103,945,320 elapsed=208.9s

  [15106/17668] intraday_7437.csv.gz  in=417,921,516 out=103,945,320 elapsed=208.9s

  [15107/17668] intraday_7436.csv.gz  in=417,929,399 out=103,945,320 elapsed=209.0s

  [15108/17668] intraday_7440.csv.gz  in=417,929,575 out=103,945,320 elapsed=209.0s

  [15109/17668] intraday_7439.csv.gz  in=417,931,394 out=103,945,320 elapsed=209.0s

  [15110/17668] intraday_7442.csv.gz  in=417,931,528 out=103,945,320 elapsed=209.0s

  [15111/17668] intraday_7441.csv.gz  in=417,936,385 out=103,945,320 elapsed=209.0s

  [15112/17668] intraday_7443.csv.gz  in=417,937,541 out=103,945,320 elapsed=209.0s

  [15113/17668] intraday_7444.csv.gz  in=417,937,554 out=103,945,320 elapsed=209.0s

  [15114/17668] intraday_7446.csv.gz  in=417,937,656 out=103,945,320 elapsed=209.0s

  [15115/17668] intraday_7445.csv.gz  in=417,937,679 out=103,945,320 elapsed=209.0s

  [15116/17668] intraday_7448.csv.gz  in=417,938,578 out=103,945,320 elapsed=209.0s

  [15117/17668] intraday_7447.csv.gz  in=417,939,496 out=103,945,320 elapsed=209.0s

  [15118/17668] intraday_7449.csv.gz  in=417,939,659 out=103,945,320 elapsed=209.0s

  [15119/17668] intraday_7450.csv.gz  in=417,939,667 out=103,945,320 elapsed=209.0s

  [15120/17668] intraday_7451.csv.gz  in=417,939,712 out=103,945,320 elapsed=209.0s

  [15121/17668] intraday_7452.csv.gz  in=417,941,048 out=103,945,320 elapsed=209.0s

  [15122/17668] intraday_7454.csv.gz  in=417,945,333 out=103,945,320 elapsed=209.0s

  [15123/17668] intraday_7453.csv.gz  in=417,949,789 out=103,945,320 elapsed=209.0s

  [15124/17668] intraday_7455.csv.gz  in=417,950,509 out=103,945,320 elapsed=209.1s

  [15125/17668] intraday_7458.csv.gz  in=417,950,532 out=103,945,320 elapsed=209.1s

  [15126/17668] intraday_7457.csv.gz  in=417,954,755 out=103,945,320 elapsed=209.1s

  [15127/17668] intraday_7456.csv.gz  in=417,955,072 out=103,945,320 elapsed=209.1s

  [15128/17668] intraday_7459.csv.gz  in=417,955,203 out=103,945,320 elapsed=209.1s

  [15129/17668] intraday_7460.csv.gz  in=417,955,414 out=103,945,320 elapsed=209.1s

  [15130/17668] intraday_7461.csv.gz  in=417,955,720 out=103,945,320 elapsed=209.1s

  [15131/17668] intraday_7463.csv.gz  in=417,959,202 out=103,945,320 elapsed=209.1s

  [15132/17668] intraday_7465.csv.gz  in=417,961,615 out=103,945,320 elapsed=209.1s

  [15133/17668] intraday_7464.csv.gz  in=417,964,436 out=103,945,320 elapsed=209.1s

  [15134/17668] intraday_7462.csv.gz  in=417,996,179 out=103,945,320 elapsed=209.1s

  [15135/17668] intraday_7466.csv.gz  in=417,998,672 out=103,945,320 elapsed=209.1s

  [15136/17668] intraday_7468.csv.gz  in=418,001,711 out=103,945,320 elapsed=209.1s

  [15137/17668] intraday_7467.csv.gz  in=418,004,152 out=103,945,320 elapsed=209.2s

  [15138/17668] intraday_7470.csv.gz  in=418,006,391 out=103,945,320 elapsed=209.2s

  [15139/17668] intraday_7469.csv.gz  in=418,010,421 out=103,945,320 elapsed=209.2s

  [15140/17668] intraday_7471.csv.gz  in=418,013,115 out=103,945,320 elapsed=209.2s

  [15141/17668] intraday_7472.csv.gz  in=418,016,148 out=103,945,320 elapsed=209.2s

  [15142/17668] intraday_7474.csv.gz  in=418,019,843 out=103,945,320 elapsed=209.2s

  [15143/17668] intraday_7473.csv.gz  in=418,024,111 out=103,945,320 elapsed=209.2s

  [15144/17668] intraday_7477.csv.gz  in=418,026,564 out=103,945,320 elapsed=209.2s

  [15145/17668] intraday_7476.csv.gz  in=418,029,603 out=103,945,320 elapsed=209.2s

  [15146/17668] intraday_7475.csv.gz  in=418,032,614 out=103,945,320 elapsed=209.2s

  [15147/17668] intraday_7478.csv.gz  in=418,034,702 out=103,945,320 elapsed=209.2s

  [15148/17668] intraday_7481.csv.gz  in=418,036,753 out=103,945,320 elapsed=209.2s

  [15149/17668] intraday_7480.csv.gz  in=418,039,429 out=103,945,320 elapsed=209.2s

  [15150/17668] intraday_7479.csv.gz  in=418,042,705 out=103,945,320 elapsed=209.2s

  [15151/17668] intraday_7482.csv.gz  in=418,044,820 out=103,945,320 elapsed=209.2s

  [15152/17668] intraday_7483.csv.gz  in=418,047,593 out=103,945,320 elapsed=209.2s

  [15153/17668] intraday_7485.csv.gz  in=418,049,285 out=103,945,320 elapsed=209.3s

  [15154/17668] intraday_7486.csv.gz  in=418,051,936 out=103,945,320 elapsed=209.3s

  [15155/17668] intraday_7484.csv.gz  in=418,055,162 out=103,945,320 elapsed=209.3s

  [15156/17668] intraday_7487.csv.gz  in=418,057,455 out=103,945,320 elapsed=209.3s

  [15157/17668] intraday_7489.csv.gz  in=418,059,890 out=103,945,320 elapsed=209.3s

  [15158/17668] intraday_7488.csv.gz  in=418,063,099 out=103,945,320 elapsed=209.3s

  [15159/17668] intraday_7490.csv.gz  in=418,065,681 out=103,945,320 elapsed=209.3s

  [15160/17668] intraday_7491.csv.gz  in=418,068,252 out=103,945,320 elapsed=209.3s

  [15161/17668] intraday_7492.csv.gz  in=418,071,492 out=103,945,320 elapsed=209.3s

  [15162/17668] intraday_7494.csv.gz  in=418,073,943 out=103,945,320 elapsed=209.3s

  [15163/17668] intraday_7493.csv.gz  in=418,077,901 out=103,945,320 elapsed=209.3s

  [15164/17668] intraday_7495.csv.gz  in=418,079,324 out=103,945,320 elapsed=209.3s

  [15165/17668] intraday_7496.csv.gz  in=418,082,370 out=103,945,320 elapsed=209.3s

  [15166/17668] intraday_7497.csv.gz  in=418,084,831 out=103,945,320 elapsed=209.3s

  [15167/17668] intraday_7498.csv.gz  in=418,087,040 out=103,945,320 elapsed=209.3s

  [15168/17668] intraday_7499.csv.gz  in=418,089,330 out=103,945,320 elapsed=209.4s

  [15169/17668] intraday_7500.csv.gz  in=418,091,516 out=103,945,320 elapsed=209.4s

  [15170/17668] intraday_7502.csv.gz  in=418,093,501 out=103,945,320 elapsed=209.4s

  [15171/17668] intraday_7501.csv.gz  in=418,095,937 out=103,945,320 elapsed=209.4s

  [15172/17668] intraday_7503.csv.gz  in=418,098,587 out=103,945,320 elapsed=209.4s

  [15173/17668] intraday_7504.csv.gz  in=418,100,961 out=103,945,320 elapsed=209.4s

  [15174/17668] intraday_7507.csv.gz  in=418,103,212 out=103,945,320 elapsed=209.4s

  [15175/17668] intraday_7505.csv.gz  in=418,106,092 out=103,945,320 elapsed=209.4s

  [15176/17668] intraday_7506.csv.gz  in=418,108,787 out=103,945,320 elapsed=209.4s

  [15177/17668] intraday_7508.csv.gz  in=418,110,933 out=103,945,320 elapsed=209.4s

  [15178/17668] intraday_7509.csv.gz  in=418,112,334 out=103,945,320 elapsed=209.4s

  [15179/17668] intraday_7511.csv.gz  in=418,114,355 out=103,945,320 elapsed=209.4s

  [15180/17668] intraday_7510.csv.gz  in=418,116,552 out=103,945,320 elapsed=209.4s

  [15181/17668] intraday_7512.csv.gz  in=418,120,088 out=103,945,320 elapsed=209.4s

  [15182/17668] intraday_7513.csv.gz  in=418,122,087 out=103,945,320 elapsed=209.4s

  [15183/17668] intraday_7514.csv.gz  in=418,123,995 out=103,945,320 elapsed=209.4s

  [15184/17668] intraday_7516.csv.gz  in=418,126,369 out=103,945,320 elapsed=209.4s

  [15185/17668] intraday_7515.csv.gz  in=418,130,589 out=103,945,320 elapsed=209.4s

  [15186/17668] intraday_7519.csv.gz  in=418,133,030 out=103,945,320 elapsed=209.4s

  [15187/17668] intraday_7518.csv.gz  in=418,136,915 out=103,945,320 elapsed=209.5s

  [15188/17668] intraday_7520.csv.gz  in=418,138,559 out=103,945,320 elapsed=209.5s

  [15189/17668] intraday_7517.csv.gz  in=418,145,460 out=103,945,320 elapsed=209.5s

  [15190/17668] intraday_7521.csv.gz  in=418,148,049 out=103,945,320 elapsed=209.5s

  [15191/17668] intraday_7523.csv.gz  in=418,149,750 out=103,945,320 elapsed=209.5s

  [15192/17668] intraday_7522.csv.gz  in=418,152,404 out=103,945,320 elapsed=209.5s

  [15193/17668] intraday_7526.csv.gz  in=418,154,061 out=103,945,320 elapsed=209.5s

  [15194/17668] intraday_7524.csv.gz  in=418,157,187 out=103,945,320 elapsed=209.5s

  [15195/17668] intraday_7525.csv.gz  in=418,158,973 out=103,945,320 elapsed=209.5s

  [15196/17668] intraday_7527.csv.gz  in=418,161,216 out=103,945,320 elapsed=209.5s

  [15197/17668] intraday_7528.csv.gz  in=418,164,977 out=103,945,320 elapsed=209.5s

  [15198/17668] intraday_7530.csv.gz  in=418,167,462 out=103,945,320 elapsed=209.5s

  [15199/17668] intraday_7529.csv.gz  in=418,171,075 out=103,945,320 elapsed=209.5s

  [15200/17668] intraday_7532.csv.gz  in=418,173,540 out=103,945,320 elapsed=209.5s

  [15201/17668] intraday_7531.csv.gz  in=418,176,178 out=103,945,320 elapsed=209.6s

  [15202/17668] intraday_7534.csv.gz  in=418,178,641 out=103,945,320 elapsed=209.6s

  [15203/17668] intraday_7533.csv.gz  in=418,181,075 out=103,945,320 elapsed=209.6s

  [15204/17668] intraday_7535.csv.gz  in=418,183,529 out=103,945,320 elapsed=209.6s

  [15205/17668] intraday_7538.csv.gz  in=418,186,629 out=103,945,320 elapsed=209.6s

  [15206/17668] intraday_7537.csv.gz  in=418,188,578 out=103,945,320 elapsed=209.6s

  [15207/17668] intraday_7536.csv.gz  in=418,191,739 out=103,945,320 elapsed=209.6s

  [15208/17668] intraday_7540.csv.gz  in=418,194,493 out=103,945,320 elapsed=209.6s

  [15209/17668] intraday_7539.csv.gz  in=418,196,409 out=103,945,320 elapsed=209.6s

  [15210/17668] intraday_7542.csv.gz  in=418,198,576 out=103,945,320 elapsed=209.6s

  [15211/17668] intraday_7541.csv.gz  in=418,200,680 out=103,945,320 elapsed=209.6s

  [15212/17668] intraday_7544.csv.gz  in=418,202,051 out=103,945,320 elapsed=209.6s

  [15213/17668] intraday_7543.csv.gz  in=418,204,206 out=103,945,320 elapsed=209.6s

  [15214/17668] intraday_7545.csv.gz  in=418,206,981 out=103,945,320 elapsed=209.6s

  [15215/17668] intraday_7547.csv.gz  in=418,212,614 out=103,945,320 elapsed=209.6s

  [15216/17668] intraday_7546.csv.gz  in=418,217,868 out=103,945,320 elapsed=209.6s

  [15217/17668] intraday_7548.csv.gz  in=418,221,388 out=103,945,320 elapsed=209.7s

  [15218/17668] intraday_7549.csv.gz  in=418,223,996 out=103,945,320 elapsed=209.7s

  [15219/17668] intraday_7550.csv.gz  in=418,226,663 out=103,945,320 elapsed=209.7s

  [15220/17668] intraday_7552.csv.gz  in=418,229,704 out=103,945,320 elapsed=209.7s

  [15221/17668] intraday_7551.csv.gz  in=418,233,835 out=103,945,320 elapsed=209.7s

  [15222/17668] intraday_7553.csv.gz  in=418,238,653 out=103,945,320 elapsed=209.7s

  [15223/17668] intraday_7554.csv.gz  in=418,240,861 out=103,945,320 elapsed=209.7s

  [15224/17668] intraday_7555.csv.gz  in=418,243,356 out=103,945,320 elapsed=209.7s

  [15225/17668] intraday_7558.csv.gz  in=418,245,792 out=103,945,320 elapsed=209.7s

  [15226/17668] intraday_7556.csv.gz  in=418,248,906 out=103,945,320 elapsed=209.7s

  [15227/17668] intraday_7557.csv.gz  in=418,251,902 out=103,945,320 elapsed=209.7s

  [15228/17668] intraday_7561.csv.gz  in=418,254,790 out=103,945,320 elapsed=209.7s

  [15229/17668] intraday_7560.csv.gz  in=418,257,321 out=103,945,320 elapsed=209.7s

  [15230/17668] intraday_7562.csv.gz  in=418,261,550 out=103,945,320 elapsed=209.7s

  [15231/17668] intraday_7559.csv.gz  in=418,263,743 out=103,945,320 elapsed=209.7s

  [15232/17668] intraday_7564.csv.gz  in=418,265,927 out=103,945,320 elapsed=209.7s

  [15233/17668] intraday_7563.csv.gz  in=418,267,313 out=103,945,320 elapsed=209.7s

  [15234/17668] intraday_7565.csv.gz  in=418,271,091 out=103,945,320 elapsed=209.7s

  [15235/17668] intraday_7566.csv.gz  in=418,275,804 out=103,945,320 elapsed=209.7s

  [15236/17668] intraday_7567.csv.gz  in=418,277,920 out=103,945,320 elapsed=209.7s

  [15237/17668] intraday_7568.csv.gz  in=418,280,692 out=103,945,320 elapsed=209.8s

  [15238/17668] intraday_7569.csv.gz  in=418,285,183 out=103,945,320 elapsed=209.8s

  [15239/17668] intraday_7571.csv.gz  in=418,287,321 out=103,945,320 elapsed=209.8s

  [15240/17668] intraday_7570.csv.gz  in=418,293,349 out=103,945,320 elapsed=209.8s

  [15241/17668] intraday_7572.csv.gz  in=418,296,870 out=103,945,320 elapsed=209.8s

  [15242/17668] intraday_7573.csv.gz  in=418,301,231 out=103,945,320 elapsed=209.8s

  [15243/17668] intraday_7574.csv.gz  in=418,303,662 out=103,945,320 elapsed=209.8s

  [15244/17668] intraday_7575.csv.gz  in=418,306,157 out=103,945,320 elapsed=209.8s

  [15245/17668] intraday_7577.csv.gz  in=418,308,817 out=103,945,320 elapsed=209.8s

  [15246/17668] intraday_7576.csv.gz  in=418,316,335 out=103,945,320 elapsed=209.8s

  [15247/17668] intraday_7578.csv.gz  in=418,322,833 out=103,945,320 elapsed=209.8s

  [15248/17668] intraday_7579.csv.gz  in=418,326,079 out=103,945,320 elapsed=209.8s

  [15249/17668] intraday_7581.csv.gz  in=418,330,443 out=103,945,320 elapsed=209.8s

  [15250/17668] intraday_7583.csv.gz  in=418,333,614 out=103,945,320 elapsed=209.8s

  [15251/17668] intraday_7580.csv.gz  in=418,338,047 out=103,945,320 elapsed=209.8s

  [15252/17668] intraday_7582.csv.gz  in=418,340,897 out=103,945,320 elapsed=209.8s

  [15253/17668] intraday_7584.csv.gz  in=418,343,019 out=103,945,320 elapsed=209.9s

  [15254/17668] intraday_7586.csv.gz  in=418,345,622 out=103,945,320 elapsed=209.9s

  [15255/17668] intraday_7585.csv.gz  in=418,348,017 out=103,945,320 elapsed=209.9s

  [15256/17668] intraday_7587.csv.gz  in=418,350,107 out=103,945,320 elapsed=209.9s

  [15257/17668] intraday_7589.csv.gz  in=418,354,062 out=103,945,320 elapsed=209.9s

  [15258/17668] intraday_7588.csv.gz  in=418,359,597 out=103,945,320 elapsed=209.9s

  [15259/17668] intraday_7590.csv.gz  in=418,363,943 out=103,945,320 elapsed=209.9s

  [15260/17668] intraday_7591.csv.gz  in=418,369,218 out=103,945,320 elapsed=209.9s

  [15261/17668] intraday_7592.csv.gz  in=418,371,160 out=103,945,320 elapsed=209.9s

  [15262/17668] intraday_7593.csv.gz  in=418,374,299 out=103,945,320 elapsed=209.9s

  [15263/17668] intraday_7594.csv.gz  in=418,377,066 out=103,945,320 elapsed=209.9s

  [15264/17668] intraday_7596.csv.gz  in=418,379,985 out=103,945,320 elapsed=209.9s

  [15265/17668] intraday_7595.csv.gz  in=418,382,509 out=103,945,320 elapsed=209.9s

  [15266/17668] intraday_7597.csv.gz  in=418,385,311 out=103,945,320 elapsed=209.9s

  [15267/17668] intraday_7598.csv.gz  in=418,387,940 out=103,945,320 elapsed=209.9s

  [15268/17668] intraday_7599.csv.gz  in=418,390,346 out=103,945,320 elapsed=210.0s

  [15269/17668] intraday_7601.csv.gz  in=418,393,494 out=103,945,320 elapsed=210.0s

  [15270/17668] intraday_7600.csv.gz  in=418,395,345 out=103,945,320 elapsed=210.0s

  [15271/17668] intraday_7602.csv.gz  in=418,397,396 out=103,945,320 elapsed=210.0s

  [15272/17668] intraday_7603.csv.gz  in=418,400,012 out=103,945,320 elapsed=210.0s

  [15273/17668] intraday_7604.csv.gz  in=418,402,949 out=103,945,320 elapsed=210.0s

  [15274/17668] intraday_7605.csv.gz  in=418,404,942 out=103,945,320 elapsed=210.0s

  [15275/17668] intraday_7608.csv.gz  in=418,404,947 out=103,945,320 elapsed=210.0s

  [15276/17668] intraday_7607.csv.gz  in=418,406,079 out=103,945,320 elapsed=210.0s

  [15277/17668] intraday_7606.csv.gz  in=418,408,952 out=103,945,320 elapsed=210.0s

  [15278/17668] intraday_7609.csv.gz  in=418,426,820 out=103,945,320 elapsed=210.0s

  [15279/17668] intraday_7612.csv.gz  in=418,438,544 out=103,945,320 elapsed=210.0s

  [15280/17668] intraday_7611.csv.gz  in=418,451,921 out=103,945,320 elapsed=210.0s

  [15281/17668] intraday_7610.csv.gz  in=418,464,599 out=103,945,320 elapsed=210.0s

  [15282/17668] intraday_7615.csv.gz  in=418,478,256 out=103,945,320 elapsed=210.1s

  [15283/17668] intraday_7614.csv.gz  in=418,494,040 out=103,945,320 elapsed=210.1s

  [15284/17668] intraday_7613.csv.gz  in=418,508,875 out=103,945,320 elapsed=210.1s

  [15285/17668] intraday_7616.csv.gz  in=418,522,555 out=103,945,320 elapsed=210.1s

  [15286/17668] intraday_7617.csv.gz  in=418,535,814 out=103,945,320 elapsed=210.1s

  [15287/17668] intraday_7618.csv.gz  in=418,549,943 out=103,945,320 elapsed=210.1s

  [15288/17668] intraday_7619.csv.gz  in=418,564,161 out=103,945,320 elapsed=210.1s

  [15289/17668] intraday_7620.csv.gz  in=418,579,494 out=103,945,320 elapsed=210.1s

  [15290/17668] intraday_7623.csv.gz  in=418,590,647 out=103,945,320 elapsed=210.1s

  [15291/17668] intraday_7621.csv.gz  in=418,603,928 out=103,945,320 elapsed=210.1s

  [15292/17668] intraday_7622.csv.gz  in=418,617,351 out=103,945,320 elapsed=210.1s

  [15293/17668] intraday_7624.csv.gz  in=418,628,111 out=103,945,320 elapsed=210.2s

  [15294/17668] intraday_7626.csv.gz  in=418,641,696 out=103,945,320 elapsed=210.2s

  [15295/17668] intraday_7625.csv.gz  in=418,656,017 out=103,945,320 elapsed=210.2s

  [15296/17668] intraday_7627.csv.gz  in=418,668,611 out=103,945,320 elapsed=210.2s

  [15297/17668] intraday_7629.csv.gz  in=418,681,944 out=103,945,320 elapsed=210.2s

  [15298/17668] intraday_7628.csv.gz  in=418,692,482 out=103,945,320 elapsed=210.2s

  [15299/17668] intraday_7630.csv.gz  in=418,706,584 out=103,945,320 elapsed=210.2s

  [15300/17668] intraday_7631.csv.gz  in=418,718,031 out=103,945,320 elapsed=210.2s

  [15301/17668] intraday_7632.csv.gz  in=418,732,931 out=103,945,320 elapsed=210.2s

  [15302/17668] intraday_7633.csv.gz  in=418,746,610 out=103,945,320 elapsed=210.3s

  [15303/17668] intraday_7635.csv.gz  in=418,760,148 out=103,945,320 elapsed=210.3s

  [15304/17668] intraday_7634.csv.gz  in=418,773,672 out=103,945,320 elapsed=210.3s

  [15305/17668] intraday_7638.csv.gz  in=418,786,641 out=103,945,320 elapsed=210.3s

  [15306/17668] intraday_7637.csv.gz  in=418,799,153 out=103,945,320 elapsed=210.3s

  [15307/17668] intraday_7636.csv.gz  in=418,812,007 out=103,945,320 elapsed=210.3s

  [15308/17668] intraday_7639.csv.gz  in=418,827,206 out=103,945,320 elapsed=210.3s

  [15309/17668] intraday_7640.csv.gz  in=418,840,260 out=103,945,320 elapsed=210.3s

  [15310/17668] intraday_7642.csv.gz  in=418,854,893 out=103,945,320 elapsed=210.3s

  [15311/17668] intraday_7643.csv.gz  in=418,869,281 out=103,945,320 elapsed=210.3s

  [15312/17668] intraday_7641.csv.gz  in=418,880,435 out=103,945,320 elapsed=210.4s

  [15313/17668] intraday_7644.csv.gz  in=418,892,877 out=103,945,320 elapsed=210.4s

  [15314/17668] intraday_7645.csv.gz  in=418,907,039 out=103,945,320 elapsed=210.4s

  [15315/17668] intraday_7646.csv.gz  in=418,918,764 out=103,945,320 elapsed=210.4s

  [15316/17668] intraday_7647.csv.gz  in=418,931,115 out=103,945,320 elapsed=210.4s

  [15317/17668] intraday_7648.csv.gz  in=418,941,679 out=103,945,320 elapsed=210.4s

  [15318/17668] intraday_7649.csv.gz  in=418,954,717 out=103,945,320 elapsed=210.4s

  [15319/17668] intraday_7650.csv.gz  in=418,969,744 out=103,945,320 elapsed=210.4s

  [15320/17668] intraday_7652.csv.gz  in=418,982,045 out=103,945,320 elapsed=210.4s

  [15321/17668] intraday_7651.csv.gz  in=418,994,978 out=103,945,320 elapsed=210.4s

  [15322/17668] intraday_7653.csv.gz  in=419,011,251 out=103,945,320 elapsed=210.4s

  [15323/17668] intraday_7655.csv.gz  in=419,023,988 out=103,945,320 elapsed=210.4s

  [15324/17668] intraday_7654.csv.gz  in=419,036,658 out=103,945,320 elapsed=210.5s

  [15325/17668] intraday_7656.csv.gz  in=419,049,105 out=103,945,320 elapsed=210.5s

  [15326/17668] intraday_7657.csv.gz  in=419,061,476 out=103,945,320 elapsed=210.5s

  [15327/17668] intraday_7659.csv.gz  in=419,073,200 out=103,945,320 elapsed=210.5s

  [15328/17668] intraday_7660.csv.gz  in=419,086,437 out=103,945,320 elapsed=210.5s

  [15329/17668] intraday_7658.csv.gz  in=419,098,475 out=103,945,320 elapsed=210.5s

  [15330/17668] intraday_7661.csv.gz  in=419,111,158 out=103,945,320 elapsed=210.5s

  [15331/17668] intraday_7662.csv.gz  in=419,126,270 out=103,945,320 elapsed=210.5s

  [15332/17668] intraday_7665.csv.gz  in=419,139,939 out=103,945,320 elapsed=210.5s

  [15333/17668] intraday_7664.csv.gz  in=419,152,580 out=103,945,320 elapsed=210.5s

  [15334/17668] intraday_7663.csv.gz  in=419,167,721 out=103,945,320 elapsed=210.6s

  [15335/17668] intraday_7668.csv.gz  in=419,181,733 out=103,945,320 elapsed=210.6s

  [15336/17668] intraday_7666.csv.gz  in=419,192,236 out=103,945,320 elapsed=210.6s

  [15337/17668] intraday_7667.csv.gz  in=419,206,382 out=103,945,320 elapsed=210.6s

  [15338/17668] intraday_7669.csv.gz  in=419,218,307 out=103,945,320 elapsed=210.6s

  [15339/17668] intraday_7670.csv.gz  in=419,232,000 out=103,945,320 elapsed=210.6s

  [15340/17668] intraday_7672.csv.gz  in=419,243,225 out=103,945,320 elapsed=210.6s

  [15341/17668] intraday_7671.csv.gz  in=419,255,851 out=103,945,320 elapsed=210.6s

  [15342/17668] intraday_7673.csv.gz  in=419,268,956 out=103,945,320 elapsed=210.6s

  [15343/17668] intraday_7674.csv.gz  in=419,282,792 out=103,945,320 elapsed=210.7s

  [15344/17668] intraday_7677.csv.gz  in=419,296,555 out=103,945,320 elapsed=210.7s

  [15345/17668] intraday_7676.csv.gz  in=419,311,858 out=103,945,320 elapsed=210.7s

  [15346/17668] intraday_7675.csv.gz  in=419,327,567 out=103,945,320 elapsed=210.7s

  [15347/17668] intraday_7678.csv.gz  in=419,339,566 out=103,945,320 elapsed=210.7s

  [15348/17668] intraday_7679.csv.gz  in=419,351,537 out=103,945,320 elapsed=210.7s

  [15349/17668] intraday_7680.csv.gz  in=419,363,722 out=103,945,320 elapsed=210.7s

  [15350/17668] intraday_7681.csv.gz  in=419,376,395 out=103,945,320 elapsed=210.7s

  [15351/17668] intraday_7683.csv.gz  in=419,389,268 out=103,945,320 elapsed=210.7s

  [15352/17668] intraday_7682.csv.gz  in=419,403,321 out=103,945,320 elapsed=210.7s

  [15353/17668] intraday_7685.csv.gz  in=419,415,068 out=103,945,320 elapsed=210.7s

  [15354/17668] intraday_7684.csv.gz  in=419,425,483 out=103,945,320 elapsed=210.8s

  [15355/17668] intraday_7686.csv.gz  in=419,439,445 out=103,945,320 elapsed=210.8s

  [15356/17668] intraday_7689.csv.gz  in=419,450,349 out=103,945,320 elapsed=210.8s

  [15357/17668] intraday_7687.csv.gz  in=419,461,381 out=103,945,320 elapsed=210.8s

  [15358/17668] intraday_7688.csv.gz  in=419,473,796 out=103,945,320 elapsed=210.8s

  [15359/17668] intraday_7691.csv.gz  in=419,486,974 out=103,945,320 elapsed=210.8s

  [15360/17668] intraday_7690.csv.gz  in=419,499,449 out=103,945,320 elapsed=210.8s

  [15361/17668] intraday_7692.csv.gz  in=419,517,235 out=103,945,320 elapsed=210.8s

  [15362/17668] intraday_7693.csv.gz  in=419,532,831 out=103,945,320 elapsed=210.8s

  [15363/17668] intraday_7694.csv.gz  in=419,546,511 out=103,945,320 elapsed=210.8s

  [15364/17668] intraday_7695.csv.gz  in=419,558,228 out=103,945,320 elapsed=210.8s

  [15365/17668] intraday_7697.csv.gz  in=419,574,740 out=103,945,320 elapsed=210.9s

  [15366/17668] intraday_7696.csv.gz  in=419,588,457 out=103,945,320 elapsed=210.9s

  [15367/17668] intraday_7699.csv.gz  in=419,602,151 out=103,945,320 elapsed=210.9s

  [15368/17668] intraday_7698.csv.gz  in=419,618,729 out=103,945,320 elapsed=210.9s

  [15369/17668] intraday_7702.csv.gz  in=419,632,044 out=103,945,320 elapsed=210.9s

  [15370/17668] intraday_7701.csv.gz  in=419,645,933 out=103,945,320 elapsed=210.9s

  [15371/17668] intraday_7700.csv.gz  in=419,659,679 out=103,945,320 elapsed=210.9s

  [15372/17668] intraday_7703.csv.gz  in=419,673,672 out=103,945,320 elapsed=210.9s

  [15373/17668] intraday_7707.csv.gz  in=419,687,448 out=103,945,320 elapsed=210.9s

  [15374/17668] intraday_7704.csv.gz  in=419,701,010 out=103,945,320 elapsed=210.9s

  [15375/17668] intraday_7706.csv.gz  in=419,713,714 out=103,945,320 elapsed=211.0s

  [15376/17668] intraday_7705.csv.gz  in=419,726,533 out=103,945,320 elapsed=211.0s

  [15377/17668] intraday_7708.csv.gz  in=419,740,311 out=103,945,320 elapsed=211.0s

  [15378/17668] intraday_7710.csv.gz  in=419,753,174 out=103,945,320 elapsed=211.0s

  [15379/17668] intraday_7709.csv.gz  in=419,763,597 out=103,945,320 elapsed=211.0s

  [15380/17668] intraday_7711.csv.gz  in=419,779,390 out=103,945,320 elapsed=211.0s

  [15381/17668] intraday_7714.csv.gz  in=419,791,563 out=103,945,320 elapsed=211.0s

  [15382/17668] intraday_7713.csv.gz  in=419,805,775 out=103,945,320 elapsed=211.0s

  [15383/17668] intraday_7712.csv.gz  in=419,819,606 out=103,945,320 elapsed=211.0s

  [15384/17668] intraday_7715.csv.gz  in=419,836,099 out=103,945,320 elapsed=211.0s

  [15385/17668] intraday_7717.csv.gz  in=419,850,553 out=103,945,320 elapsed=211.0s

  [15386/17668] intraday_7716.csv.gz  in=419,864,788 out=103,945,320 elapsed=211.1s

  [15387/17668] intraday_7719.csv.gz  in=419,879,119 out=103,945,320 elapsed=211.1s

  [15388/17668] intraday_7718.csv.gz  in=419,894,196 out=103,945,320 elapsed=211.1s

  [15389/17668] intraday_7721.csv.gz  in=419,909,109 out=103,945,320 elapsed=211.1s

  [15390/17668] intraday_7720.csv.gz  in=419,920,381 out=103,945,320 elapsed=211.1s

  [15391/17668] intraday_7722.csv.gz  in=419,933,559 out=103,945,320 elapsed=211.1s

  [15392/17668] intraday_7723.csv.gz  in=419,947,173 out=103,945,320 elapsed=211.1s

  [15393/17668] intraday_7725.csv.gz  in=419,962,897 out=103,945,320 elapsed=211.1s

  [15394/17668] intraday_7724.csv.gz  in=419,980,026 out=103,945,320 elapsed=211.1s

  [15395/17668] intraday_7727.csv.gz  in=419,995,188 out=103,945,320 elapsed=211.1s

  [15396/17668] intraday_7726.csv.gz  in=420,010,773 out=103,945,320 elapsed=211.1s

  [15397/17668] intraday_7728.csv.gz  in=420,022,804 out=103,945,320 elapsed=211.2s

  [15398/17668] intraday_7729.csv.gz  in=420,037,139 out=103,945,320 elapsed=211.2s

  [15399/17668] intraday_7730.csv.gz  in=420,048,655 out=103,945,320 elapsed=211.2s

  [15400/17668] intraday_7731.csv.gz  in=420,064,098 out=103,945,320 elapsed=211.2s

  [15401/17668] intraday_7732.csv.gz  in=420,074,982 out=103,945,320 elapsed=211.2s

  [15402/17668] intraday_7734.csv.gz  in=420,087,947 out=103,945,320 elapsed=211.2s

  [15403/17668] intraday_7733.csv.gz  in=420,103,124 out=103,945,320 elapsed=211.2s

  [15404/17668] intraday_7735.csv.gz  in=420,118,734 out=103,945,320 elapsed=211.2s

  [15405/17668] intraday_7736.csv.gz  in=420,130,553 out=103,945,320 elapsed=211.2s

  [15406/17668] intraday_7738.csv.gz  in=420,143,903 out=103,945,320 elapsed=211.2s

  [15407/17668] intraday_7737.csv.gz  in=420,157,573 out=103,945,320 elapsed=211.2s

  [15408/17668] intraday_7740.csv.gz  in=420,170,642 out=103,945,320 elapsed=211.3s

  [15409/17668] intraday_7739.csv.gz  in=420,182,629 out=103,945,320 elapsed=211.3s

  [15410/17668] intraday_7741.csv.gz  in=420,197,481 out=103,945,320 elapsed=211.3s

  [15411/17668] intraday_7743.csv.gz  in=420,212,244 out=103,945,320 elapsed=211.3s

  [15412/17668] intraday_7742.csv.gz  in=420,226,985 out=103,945,320 elapsed=211.3s

  [15413/17668] intraday_7744.csv.gz  in=420,241,410 out=103,945,320 elapsed=211.3s

  [15414/17668] intraday_7745.csv.gz  in=420,253,121 out=103,945,320 elapsed=211.3s

  [15415/17668] intraday_7746.csv.gz  in=420,265,363 out=103,945,320 elapsed=211.3s

  [15416/17668] intraday_7750.csv.gz  in=420,274,605 out=103,945,320 elapsed=211.3s

  [15417/17668] intraday_7747.csv.gz  in=420,288,978 out=103,945,320 elapsed=211.4s

  [15418/17668] intraday_7749.csv.gz  in=420,301,504 out=103,945,320 elapsed=211.4s

  [15419/17668] intraday_7748.csv.gz  in=420,314,305 out=103,945,320 elapsed=211.4s

  [15420/17668] intraday_7752.csv.gz  in=420,322,773 out=103,945,320 elapsed=211.4s

  [15421/17668] intraday_7751.csv.gz  in=420,335,265 out=103,945,320 elapsed=211.4s

  [15422/17668] intraday_7754.csv.gz  in=420,348,807 out=103,945,320 elapsed=211.4s

  [15423/17668] intraday_7753.csv.gz  in=420,364,550 out=103,945,320 elapsed=211.4s

  [15424/17668] intraday_7755.csv.gz  in=420,376,705 out=103,945,320 elapsed=211.4s

  [15425/17668] intraday_7756.csv.gz  in=420,389,845 out=103,945,320 elapsed=211.4s

  [15426/17668] intraday_7757.csv.gz  in=420,401,071 out=103,945,320 elapsed=211.4s

  [15427/17668] intraday_7759.csv.gz  in=420,418,437 out=103,945,320 elapsed=211.4s

  [15428/17668] intraday_7760.csv.gz  in=420,429,224 out=103,945,320 elapsed=211.4s

  [15429/17668] intraday_7758.csv.gz  in=420,443,215 out=103,945,320 elapsed=211.4s

  [15430/17668] intraday_7761.csv.gz  in=420,456,521 out=103,945,320 elapsed=211.4s

  [15431/17668] intraday_7762.csv.gz  in=420,470,267 out=103,945,320 elapsed=211.5s

  [15432/17668] intraday_7764.csv.gz  in=420,482,138 out=103,945,320 elapsed=211.5s

  [15433/17668] intraday_7763.csv.gz  in=420,497,088 out=103,945,320 elapsed=211.5s

  [15434/17668] intraday_7765.csv.gz  in=420,511,092 out=103,945,320 elapsed=211.5s

  [15435/17668] intraday_7766.csv.gz  in=420,524,054 out=103,945,320 elapsed=211.5s

  [15436/17668] intraday_7768.csv.gz  in=420,536,450 out=103,945,320 elapsed=211.5s

  [15437/17668] intraday_7767.csv.gz  in=420,546,574 out=103,945,320 elapsed=211.5s

  [15438/17668] intraday_7769.csv.gz  in=420,560,955 out=103,945,320 elapsed=211.5s

  [15439/17668] intraday_7770.csv.gz  in=420,575,205 out=103,945,320 elapsed=211.5s

  [15440/17668] intraday_7772.csv.gz  in=420,587,380 out=103,945,320 elapsed=211.5s

  [15441/17668] intraday_7771.csv.gz  in=420,598,193 out=103,945,320 elapsed=211.5s

  [15442/17668] intraday_7773.csv.gz  in=420,610,115 out=103,945,320 elapsed=211.5s

  [15443/17668] intraday_7774.csv.gz  in=420,623,388 out=103,945,320 elapsed=211.5s

  [15444/17668] intraday_7777.csv.gz  in=420,636,370 out=103,945,320 elapsed=211.6s

  [15445/17668] intraday_7775.csv.gz  in=420,647,578 out=103,945,320 elapsed=211.6s

  [15446/17668] intraday_7776.csv.gz  in=420,662,819 out=103,945,320 elapsed=211.6s

  [15447/17668] intraday_7778.csv.gz  in=420,679,070 out=103,945,320 elapsed=211.6s

  [15448/17668] intraday_7779.csv.gz  in=420,690,658 out=103,945,320 elapsed=211.6s

  [15449/17668] intraday_7781.csv.gz  in=420,703,903 out=103,945,320 elapsed=211.6s

  [15450/17668] intraday_7780.csv.gz  in=420,716,862 out=103,945,320 elapsed=211.6s

  [15451/17668] intraday_7782.csv.gz  in=420,729,237 out=103,945,320 elapsed=211.6s

  [15452/17668] intraday_7783.csv.gz  in=420,745,171 out=103,945,320 elapsed=211.6s

  [15453/17668] intraday_7785.csv.gz  in=420,755,665 out=103,945,320 elapsed=211.6s

  [15454/17668] intraday_7784.csv.gz  in=420,769,115 out=103,945,320 elapsed=211.6s

  [15455/17668] intraday_7786.csv.gz  in=420,782,128 out=103,945,320 elapsed=211.7s

  [15456/17668] intraday_7788.csv.gz  in=420,794,678 out=103,945,320 elapsed=211.7s

  [15457/17668] intraday_7787.csv.gz  in=420,808,526 out=103,945,320 elapsed=211.7s

  [15458/17668] intraday_7790.csv.gz  in=420,820,662 out=103,945,320 elapsed=211.7s

  [15459/17668] intraday_7789.csv.gz  in=420,834,582 out=103,945,320 elapsed=211.7s

  [15460/17668] intraday_7792.csv.gz  in=420,845,679 out=103,945,320 elapsed=211.7s

  [15461/17668] intraday_7791.csv.gz  in=420,858,356 out=103,945,320 elapsed=211.7s

  [15462/17668] intraday_7794.csv.gz  in=420,872,247 out=103,945,320 elapsed=211.7s

  [15463/17668] intraday_7793.csv.gz  in=420,884,408 out=103,945,320 elapsed=211.7s

  [15464/17668] intraday_7796.csv.gz  in=420,895,229 out=103,945,320 elapsed=211.7s

  [15465/17668] intraday_7795.csv.gz  in=420,909,392 out=103,945,320 elapsed=211.7s

  [15466/17668] intraday_7798.csv.gz  in=420,921,254 out=103,945,320 elapsed=211.8s

  [15467/17668] intraday_7797.csv.gz  in=420,936,965 out=103,945,320 elapsed=211.8s

  [15468/17668] intraday_7800.csv.gz  in=420,950,693 out=103,945,320 elapsed=211.8s

  [15469/17668] intraday_7799.csv.gz  in=420,962,813 out=103,945,320 elapsed=211.8s

  [15470/17668] intraday_7801.csv.gz  in=420,974,016 out=103,945,320 elapsed=211.8s

  [15471/17668] intraday_7802.csv.gz  in=420,986,048 out=103,945,320 elapsed=211.8s

  [15472/17668] intraday_7804.csv.gz  in=420,997,493 out=103,945,320 elapsed=211.8s

  [15473/17668] intraday_7806.csv.gz  in=421,010,970 out=103,945,320 elapsed=211.8s

  [15474/17668] intraday_7803.csv.gz  in=421,022,842 out=103,945,320 elapsed=211.8s

  [15475/17668] intraday_7805.csv.gz  in=421,037,729 out=103,945,320 elapsed=211.8s

  [15476/17668] intraday_7807.csv.gz  in=421,051,561 out=103,945,320 elapsed=211.9s

  [15477/17668] intraday_7808.csv.gz  in=421,065,487 out=103,945,320 elapsed=211.9s

  [15478/17668] intraday_7809.csv.gz  in=421,078,775 out=103,945,320 elapsed=211.9s

  [15479/17668] intraday_7810.csv.gz  in=421,090,888 out=103,945,320 elapsed=211.9s

  [15480/17668] intraday_7811.csv.gz  in=421,105,872 out=103,945,320 elapsed=211.9s

  [15481/17668] intraday_7812.csv.gz  in=421,117,643 out=103,945,320 elapsed=211.9s

  [15482/17668] intraday_7814.csv.gz  in=421,130,705 out=103,945,320 elapsed=211.9s

  [15483/17668] intraday_7815.csv.gz  in=421,141,991 out=103,945,320 elapsed=211.9s

  [15484/17668] intraday_7813.csv.gz  in=421,157,428 out=103,945,320 elapsed=211.9s

  [15485/17668] intraday_7816.csv.gz  in=421,169,620 out=103,945,320 elapsed=211.9s

  [15486/17668] intraday_7818.csv.gz  in=421,183,388 out=103,945,320 elapsed=211.9s

  [15487/17668] intraday_7817.csv.gz  in=421,194,247 out=103,945,320 elapsed=211.9s

  [15488/17668] intraday_7820.csv.gz  in=421,209,509 out=103,945,320 elapsed=212.0s

  [15489/17668] intraday_7819.csv.gz  in=421,224,207 out=103,945,320 elapsed=212.0s

  [15490/17668] intraday_7822.csv.gz  in=421,235,782 out=103,945,320 elapsed=212.0s

  [15491/17668] intraday_7821.csv.gz  in=421,248,532 out=103,945,320 elapsed=212.0s

  [15492/17668] intraday_7823.csv.gz  in=421,261,053 out=103,945,320 elapsed=212.0s

  [15493/17668] intraday_7825.csv.gz  in=421,274,420 out=103,945,320 elapsed=212.0s

  [15494/17668] intraday_7824.csv.gz  in=421,286,022 out=103,945,320 elapsed=212.0s

  [15495/17668] intraday_7827.csv.gz  in=421,297,628 out=103,945,320 elapsed=212.0s

  [15496/17668] intraday_7826.csv.gz  in=421,311,467 out=103,945,320 elapsed=212.0s

  [15497/17668] intraday_7828.csv.gz  in=421,323,232 out=103,945,320 elapsed=212.1s

  [15498/17668] intraday_7829.csv.gz  in=421,334,334 out=103,945,320 elapsed=212.1s

  [15499/17668] intraday_7830.csv.gz  in=421,347,525 out=103,945,320 elapsed=212.1s

  [15500/17668] intraday_7831.csv.gz  in=421,358,161 out=103,945,320 elapsed=212.1s

  [15501/17668] intraday_7832.csv.gz  in=421,369,910 out=103,945,320 elapsed=212.1s

  [15502/17668] intraday_7833.csv.gz  in=421,380,679 out=103,945,320 elapsed=212.1s

  [15503/17668] intraday_7834.csv.gz  in=421,393,926 out=103,945,320 elapsed=212.1s

  [15504/17668] intraday_7835.csv.gz  in=421,406,067 out=103,945,320 elapsed=212.1s

  [15505/17668] intraday_7837.csv.gz  in=421,422,419 out=103,945,320 elapsed=212.2s

  [15506/17668] intraday_7838.csv.gz  in=421,435,355 out=103,945,320 elapsed=212.2s

  [15507/17668] intraday_7839.csv.gz  in=421,447,191 out=103,945,320 elapsed=212.2s

  [15508/17668] intraday_7836.csv.gz  in=421,465,962 out=103,945,320 elapsed=212.2s

  [15509/17668] intraday_7840.csv.gz  in=421,477,423 out=103,945,320 elapsed=212.2s

  [15510/17668] intraday_7842.csv.gz  in=421,491,786 out=103,945,320 elapsed=212.2s

  [15511/17668] intraday_7841.csv.gz  in=421,507,778 out=103,945,320 elapsed=212.2s

  [15512/17668] intraday_7844.csv.gz  in=421,519,499 out=103,945,320 elapsed=212.2s

  [15513/17668] intraday_7843.csv.gz  in=421,534,787 out=103,945,320 elapsed=212.2s

  [15514/17668] intraday_7845.csv.gz  in=421,549,723 out=103,945,320 elapsed=212.2s

  [15515/17668] intraday_7846.csv.gz  in=421,564,539 out=103,945,320 elapsed=212.2s

  [15516/17668] intraday_7847.csv.gz  in=421,576,583 out=103,945,320 elapsed=212.3s

  [15517/17668] intraday_7849.csv.gz  in=421,588,286 out=103,945,320 elapsed=212.3s

  [15518/17668] intraday_7848.csv.gz  in=421,603,097 out=103,945,320 elapsed=212.3s

  [15519/17668] intraday_7850.csv.gz  in=421,615,800 out=103,945,320 elapsed=212.3s

  [15520/17668] intraday_7851.csv.gz  in=421,629,024 out=103,945,320 elapsed=212.3s

  [15521/17668] intraday_7852.csv.gz  in=421,641,564 out=103,945,320 elapsed=212.3s

  [15522/17668] intraday_7853.csv.gz  in=421,653,357 out=103,945,320 elapsed=212.3s

  [15523/17668] intraday_7854.csv.gz  in=421,668,152 out=103,945,320 elapsed=212.3s

  [15524/17668] intraday_7855.csv.gz  in=421,680,119 out=103,945,320 elapsed=212.3s

  [15525/17668] intraday_7857.csv.gz  in=421,691,700 out=103,945,320 elapsed=212.3s

  [15526/17668] intraday_7856.csv.gz  in=421,708,131 out=103,945,320 elapsed=212.3s

  [15527/17668] intraday_7858.csv.gz  in=421,720,513 out=103,945,320 elapsed=212.4s

  [15528/17668] intraday_7860.csv.gz  in=421,735,696 out=103,945,320 elapsed=212.4s

  [15529/17668] intraday_7859.csv.gz  in=421,752,455 out=103,945,320 elapsed=212.4s

  [15530/17668] intraday_7861.csv.gz  in=421,764,706 out=103,945,320 elapsed=212.4s

  [15531/17668] intraday_7862.csv.gz  in=421,780,454 out=103,945,320 elapsed=212.4s

  [15532/17668] intraday_7863.csv.gz  in=421,795,085 out=103,945,320 elapsed=212.4s

  [15533/17668] intraday_7864.csv.gz  in=421,805,287 out=103,945,320 elapsed=212.4s

  [15534/17668] intraday_7865.csv.gz  in=421,818,698 out=103,945,320 elapsed=212.4s

  [15535/17668] intraday_7866.csv.gz  in=421,832,021 out=103,945,320 elapsed=212.4s

  [15536/17668] intraday_7867.csv.gz  in=421,846,692 out=103,945,320 elapsed=212.4s

  [15537/17668] intraday_7869.csv.gz  in=421,862,419 out=103,945,320 elapsed=212.5s

  [15538/17668] intraday_7868.csv.gz  in=421,882,027 out=103,945,320 elapsed=212.5s

  [15539/17668] intraday_7870.csv.gz  in=421,895,085 out=103,945,320 elapsed=212.5s

  [15540/17668] intraday_7874.csv.gz  in=421,907,459 out=103,945,320 elapsed=212.5s

  [15541/17668] intraday_7872.csv.gz  in=421,920,850 out=103,945,320 elapsed=212.5s

  [15542/17668] intraday_7873.csv.gz  in=421,932,693 out=103,945,320 elapsed=212.5s

  [15543/17668] intraday_7871.csv.gz  in=421,949,549 out=103,945,320 elapsed=212.5s

  [15544/17668] intraday_7876.csv.gz  in=421,960,933 out=103,945,320 elapsed=212.5s

  [15545/17668] intraday_7878.csv.gz  in=421,973,370 out=103,945,320 elapsed=212.5s

  [15546/17668] intraday_7875.csv.gz  in=421,987,384 out=103,945,320 elapsed=212.5s

  [15547/17668] intraday_7877.csv.gz  in=422,001,441 out=103,945,320 elapsed=212.5s

  [15548/17668] intraday_7879.csv.gz  in=422,015,165 out=103,945,320 elapsed=212.6s

  [15549/17668] intraday_7881.csv.gz  in=422,026,749 out=103,945,320 elapsed=212.6s

  [15550/17668] intraday_7880.csv.gz  in=422,041,664 out=103,945,320 elapsed=212.6s

  [15551/17668] intraday_7882.csv.gz  in=422,055,567 out=103,945,320 elapsed=212.6s

  [15552/17668] intraday_7884.csv.gz  in=422,068,012 out=103,945,320 elapsed=212.6s

  [15553/17668] intraday_7883.csv.gz  in=422,080,741 out=103,945,320 elapsed=212.6s

  [15554/17668] intraday_7885.csv.gz  in=422,093,190 out=103,945,320 elapsed=212.6s

  [15555/17668] intraday_7886.csv.gz  in=422,108,356 out=103,945,320 elapsed=212.6s

  [15556/17668] intraday_7887.csv.gz  in=422,122,008 out=103,945,320 elapsed=212.6s

  [15557/17668] intraday_7890.csv.gz  in=422,133,334 out=103,945,320 elapsed=212.6s

  [15558/17668] intraday_7888.csv.gz  in=422,145,548 out=103,945,320 elapsed=212.6s

  [15559/17668] intraday_7891.csv.gz  in=422,158,705 out=103,945,320 elapsed=212.6s

  [15560/17668] intraday_7889.csv.gz  in=422,173,652 out=103,945,320 elapsed=212.7s

  [15561/17668] intraday_7892.csv.gz  in=422,185,004 out=103,945,320 elapsed=212.7s

  [15562/17668] intraday_7894.csv.gz  in=422,195,248 out=103,945,320 elapsed=212.7s

  [15563/17668] intraday_7893.csv.gz  in=422,209,643 out=103,945,320 elapsed=212.7s

  [15564/17668] intraday_7895.csv.gz  in=422,220,288 out=103,945,320 elapsed=212.7s

  [15565/17668] intraday_7897.csv.gz  in=422,221,949 out=103,945,320 elapsed=212.7s

  [15566/17668] intraday_7896.csv.gz  in=422,235,686 out=103,945,320 elapsed=212.7s

  [15567/17668] intraday_7898.csv.gz  in=422,252,619 out=103,945,320 elapsed=212.7s

  [15568/17668] intraday_7899.csv.gz  in=422,268,779 out=103,945,320 elapsed=212.7s

  [15569/17668] intraday_7900.csv.gz  in=422,284,158 out=103,945,320 elapsed=212.7s

  [15570/17668] intraday_7901.csv.gz  in=422,297,414 out=103,945,320 elapsed=212.7s

  [15571/17668] intraday_7902.csv.gz  in=422,308,845 out=103,945,320 elapsed=212.8s

  [15572/17668] intraday_7903.csv.gz  in=422,319,434 out=103,945,320 elapsed=212.8s

  [15573/17668] intraday_7904.csv.gz  in=422,333,687 out=103,945,320 elapsed=212.8s

  [15574/17668] intraday_7906.csv.gz  in=422,345,319 out=103,945,320 elapsed=212.8s

  [15575/17668] intraday_7905.csv.gz  in=422,360,943 out=103,945,320 elapsed=212.8s

  [15576/17668] intraday_7907.csv.gz  in=422,374,720 out=103,945,320 elapsed=212.8s

  [15577/17668] intraday_7908.csv.gz  in=422,388,724 out=103,945,320 elapsed=212.8s

  [15578/17668] intraday_7910.csv.gz  in=422,401,620 out=103,945,320 elapsed=212.8s

  [15579/17668] intraday_7909.csv.gz  in=422,417,025 out=103,945,320 elapsed=212.8s

  [15580/17668] intraday_7911.csv.gz  in=422,430,542 out=103,945,320 elapsed=212.8s

  [15581/17668] intraday_7912.csv.gz  in=422,445,868 out=103,945,320 elapsed=212.8s

  [15582/17668] intraday_7913.csv.gz  in=422,456,980 out=103,945,320 elapsed=212.9s

  [15583/17668] intraday_7914.csv.gz  in=422,466,917 out=103,945,320 elapsed=212.9s

  [15584/17668] intraday_7915.csv.gz  in=422,481,179 out=103,945,320 elapsed=212.9s

  [15585/17668] intraday_7916.csv.gz  in=422,494,350 out=103,945,320 elapsed=212.9s

  [15586/17668] intraday_7917.csv.gz  in=422,505,156 out=103,945,320 elapsed=212.9s

  [15587/17668] intraday_7918.csv.gz  in=422,516,588 out=103,945,320 elapsed=212.9s

  [15588/17668] intraday_7920.csv.gz  in=422,530,398 out=103,945,320 elapsed=212.9s

  [15589/17668] intraday_7919.csv.gz  in=422,541,511 out=103,945,320 elapsed=212.9s

  [15590/17668] intraday_7922.csv.gz  in=422,556,228 out=103,945,320 elapsed=212.9s

  [15591/17668] intraday_7921.csv.gz  in=422,568,338 out=103,945,320 elapsed=212.9s

  [15592/17668] intraday_7923.csv.gz  in=422,582,629 out=103,945,320 elapsed=212.9s

  [15593/17668] intraday_7924.csv.gz  in=422,596,390 out=103,945,320 elapsed=212.9s

  [15594/17668] intraday_7926.csv.gz  in=422,607,840 out=103,945,320 elapsed=213.0s

  [15595/17668] intraday_7925.csv.gz  in=422,621,154 out=103,945,320 elapsed=213.0s

  [15596/17668] intraday_7927.csv.gz  in=422,633,284 out=103,945,320 elapsed=213.0s

  [15597/17668] intraday_7928.csv.gz  in=422,647,535 out=103,945,320 elapsed=213.0s

  [15598/17668] intraday_7930.csv.gz  in=422,660,578 out=103,945,320 elapsed=213.0s

  [15599/17668] intraday_7929.csv.gz  in=422,676,503 out=103,945,320 elapsed=213.0s

  [15600/17668] intraday_7931.csv.gz  in=422,686,315 out=103,945,320 elapsed=213.0s

  [15601/17668] intraday_7932.csv.gz  in=422,700,804 out=103,945,320 elapsed=213.0s

  [15602/17668] intraday_7933.csv.gz  in=422,714,738 out=103,945,320 elapsed=213.0s

  [15603/17668] intraday_7935.csv.gz  in=422,727,881 out=103,945,320 elapsed=213.0s

  [15604/17668] intraday_7934.csv.gz  in=422,739,610 out=103,945,320 elapsed=213.1s

  [15605/17668] intraday_7936.csv.gz  in=422,752,957 out=103,945,320 elapsed=213.1s

  [15606/17668] intraday_7937.csv.gz  in=422,766,090 out=103,945,320 elapsed=213.1s

  [15607/17668] intraday_7938.csv.gz  in=422,776,790 out=103,945,320 elapsed=213.1s

  [15608/17668] intraday_7939.csv.gz  in=422,789,071 out=103,945,320 elapsed=213.1s

  [15609/17668] intraday_7940.csv.gz  in=422,801,269 out=103,945,320 elapsed=213.1s

  [15610/17668] intraday_7942.csv.gz  in=422,813,307 out=103,945,320 elapsed=213.1s

  [15611/17668] intraday_7943.csv.gz  in=422,828,012 out=103,945,320 elapsed=213.1s

  [15612/17668] intraday_7941.csv.gz  in=422,842,586 out=103,945,320 elapsed=213.1s

  [15613/17668] intraday_7944.csv.gz  in=422,854,530 out=103,945,320 elapsed=213.1s

  [15614/17668] intraday_7946.csv.gz  in=422,869,163 out=103,945,320 elapsed=213.1s

  [15615/17668] intraday_7945.csv.gz  in=422,880,421 out=103,945,320 elapsed=213.2s

  [15616/17668] intraday_7947.csv.gz  in=422,892,885 out=103,945,320 elapsed=213.2s

  [15617/17668] intraday_7948.csv.gz  in=422,904,736 out=103,945,320 elapsed=213.2s

  [15618/17668] intraday_7950.csv.gz  in=422,917,404 out=103,945,320 elapsed=213.2s

  [15619/17668] intraday_7951.csv.gz  in=422,931,152 out=103,945,320 elapsed=213.2s

  [15620/17668] intraday_7952.csv.gz  in=422,944,928 out=103,945,320 elapsed=213.2s

  [15621/17668] intraday_7949.csv.gz  in=422,957,952 out=103,945,320 elapsed=213.2s

  [15622/17668] intraday_7953.csv.gz  in=422,972,758 out=103,945,320 elapsed=213.2s

  [15623/17668] intraday_7956.csv.gz  in=422,983,684 out=103,945,320 elapsed=213.2s

  [15624/17668] intraday_7955.csv.gz  in=422,995,832 out=103,945,320 elapsed=213.2s

  [15625/17668] intraday_7954.csv.gz  in=423,008,634 out=103,945,320 elapsed=213.2s

  [15626/17668] intraday_7957.csv.gz  in=423,022,941 out=103,945,320 elapsed=213.3s

  [15627/17668] intraday_7958.csv.gz  in=423,036,699 out=103,945,320 elapsed=213.3s

  [15628/17668] intraday_7960.csv.gz  in=423,049,901 out=103,945,320 elapsed=213.3s

  [15629/17668] intraday_7959.csv.gz  in=423,062,788 out=103,945,320 elapsed=213.3s

  [15630/17668] intraday_7961.csv.gz  in=423,074,792 out=103,945,320 elapsed=213.3s

  [15631/17668] intraday_7964.csv.gz  in=423,089,080 out=103,945,320 elapsed=213.3s

  [15632/17668] intraday_7962.csv.gz  in=423,100,522 out=103,945,320 elapsed=213.3s

  [15633/17668] intraday_7963.csv.gz  in=423,112,043 out=103,945,320 elapsed=213.3s

  [15634/17668] intraday_7965.csv.gz  in=423,125,698 out=103,945,320 elapsed=213.3s

  [15635/17668] intraday_7966.csv.gz  in=423,139,396 out=103,945,320 elapsed=213.3s

  [15636/17668] intraday_7968.csv.gz  in=423,150,598 out=103,945,320 elapsed=213.3s

  [15637/17668] intraday_7967.csv.gz  in=423,165,863 out=103,945,320 elapsed=213.3s

  [15638/17668] intraday_7969.csv.gz  in=423,178,525 out=103,945,320 elapsed=213.4s

  [15639/17668] intraday_7971.csv.gz  in=423,190,789 out=103,945,320 elapsed=213.4s

  [15640/17668] intraday_7970.csv.gz  in=423,203,302 out=103,945,320 elapsed=213.4s

  [15641/17668] intraday_7972.csv.gz  in=423,217,305 out=103,945,320 elapsed=213.4s

  [15642/17668] intraday_7974.csv.gz  in=423,227,487 out=103,945,320 elapsed=213.4s

  [15643/17668] intraday_7973.csv.gz  in=423,239,641 out=103,945,320 elapsed=213.4s

  [15644/17668] intraday_7975.csv.gz  in=423,253,547 out=103,945,320 elapsed=213.4s

  [15645/17668] intraday_7976.csv.gz  in=423,265,446 out=103,945,320 elapsed=213.4s

  [15646/17668] intraday_7977.csv.gz  in=423,276,648 out=103,945,320 elapsed=213.4s

  [15647/17668] intraday_7978.csv.gz  in=423,292,512 out=103,945,320 elapsed=213.4s

  [15648/17668] intraday_7979.csv.gz  in=423,303,378 out=103,945,320 elapsed=213.4s

  [15649/17668] intraday_7981.csv.gz  in=423,316,524 out=103,945,320 elapsed=213.5s

  [15650/17668] intraday_7980.csv.gz  in=423,328,381 out=103,945,320 elapsed=213.5s

  [15651/17668] intraday_7983.csv.gz  in=423,344,550 out=103,945,320 elapsed=213.5s

  [15652/17668] intraday_7984.csv.gz  in=423,357,532 out=103,945,320 elapsed=213.5s

  [15653/17668] intraday_7982.csv.gz  in=423,373,960 out=103,945,320 elapsed=213.5s

  [15654/17668] intraday_7985.csv.gz  in=423,386,918 out=103,945,320 elapsed=213.5s

  [15655/17668] intraday_7986.csv.gz  in=423,399,217 out=103,945,320 elapsed=213.5s

  [15656/17668] intraday_7987.csv.gz  in=423,412,055 out=103,945,320 elapsed=213.5s

  [15657/17668] intraday_7988.csv.gz  in=423,428,205 out=103,945,320 elapsed=213.5s

  [15658/17668] intraday_7989.csv.gz  in=423,440,480 out=103,945,320 elapsed=213.5s

  [15659/17668] intraday_7990.csv.gz  in=423,452,981 out=103,945,320 elapsed=213.5s

  [15660/17668] intraday_7991.csv.gz  in=423,466,835 out=103,945,320 elapsed=213.6s

  [15661/17668] intraday_7993.csv.gz  in=423,482,108 out=103,945,320 elapsed=213.6s

  [15662/17668] intraday_7992.csv.gz  in=423,496,867 out=103,945,320 elapsed=213.6s

  [15663/17668] intraday_7994.csv.gz  in=423,511,128 out=103,945,320 elapsed=213.6s

  [15664/17668] intraday_7995.csv.gz  in=423,522,924 out=103,945,320 elapsed=213.6s

  [15665/17668] intraday_7996.csv.gz  in=423,535,756 out=103,945,320 elapsed=213.6s

  [15666/17668] intraday_7999.csv.gz  in=423,548,085 out=103,945,320 elapsed=213.6s

  [15667/17668] intraday_7997.csv.gz  in=423,561,293 out=103,945,320 elapsed=213.6s

  [15668/17668] intraday_7998.csv.gz  in=423,576,106 out=103,945,320 elapsed=213.6s

  [15669/17668] intraday_8000.csv.gz  in=423,586,406 out=103,945,320 elapsed=213.6s

  [15670/17668] intraday_8001.csv.gz  in=423,602,460 out=103,945,320 elapsed=213.6s

  [15671/17668] intraday_8003.csv.gz  in=423,617,431 out=103,945,320 elapsed=213.7s

  [15672/17668] intraday_8004.csv.gz  in=423,629,647 out=103,945,320 elapsed=213.7s

  [15673/17668] intraday_8002.csv.gz  in=423,642,870 out=103,945,320 elapsed=213.7s

  [15674/17668] intraday_8005.csv.gz  in=423,661,689 out=103,945,320 elapsed=213.7s

  [15675/17668] intraday_8006.csv.gz  in=423,674,811 out=103,945,320 elapsed=213.7s

  [15676/17668] intraday_8007.csv.gz  in=423,687,921 out=103,945,320 elapsed=213.7s

  [15677/17668] intraday_8008.csv.gz  in=423,702,652 out=103,945,320 elapsed=213.7s

  [15678/17668] intraday_8009.csv.gz  in=423,717,060 out=103,945,320 elapsed=213.7s

  [15679/17668] intraday_8012.csv.gz  in=423,731,487 out=103,945,320 elapsed=213.7s

  [15680/17668] intraday_8011.csv.gz  in=423,746,974 out=103,945,320 elapsed=213.7s

  [15681/17668] intraday_8010.csv.gz  in=423,758,542 out=103,945,320 elapsed=213.8s

  [15682/17668] intraday_8013.csv.gz  in=423,773,490 out=103,945,320 elapsed=213.8s

  [15683/17668] intraday_8014.csv.gz  in=423,789,333 out=103,945,320 elapsed=213.8s

  [15684/17668] intraday_8015.csv.gz  in=423,804,547 out=103,945,320 elapsed=213.8s

  [15685/17668] intraday_8016.csv.gz  in=423,817,517 out=103,945,320 elapsed=213.8s

  [15686/17668] intraday_8017.csv.gz  in=423,836,174 out=103,945,320 elapsed=213.8s

  [15687/17668] intraday_8018.csv.gz  in=423,848,084 out=103,945,320 elapsed=213.8s

  [15688/17668] intraday_8019.csv.gz  in=423,861,699 out=103,945,320 elapsed=213.8s

  [15689/17668] intraday_8020.csv.gz  in=423,874,653 out=103,945,320 elapsed=213.8s

  [15690/17668] intraday_8022.csv.gz  in=423,885,866 out=103,945,320 elapsed=213.9s

  [15691/17668] intraday_8021.csv.gz  in=423,899,524 out=103,945,320 elapsed=213.9s

  [15692/17668] intraday_8023.csv.gz  in=423,914,589 out=103,945,320 elapsed=213.9s

  [15693/17668] intraday_8024.csv.gz  in=423,934,581 out=103,945,320 elapsed=213.9s

  [15694/17668] intraday_8026.csv.gz  in=423,946,385 out=103,945,320 elapsed=213.9s

  [15695/17668] intraday_8027.csv.gz  in=423,960,155 out=103,945,320 elapsed=213.9s

  [15696/17668] intraday_8025.csv.gz  in=423,976,544 out=103,945,320 elapsed=213.9s

  [15697/17668] intraday_8028.csv.gz  in=423,988,906 out=103,945,320 elapsed=213.9s

  [15698/17668] intraday_8029.csv.gz  in=424,002,396 out=103,945,320 elapsed=213.9s

  [15699/17668] intraday_8031.csv.gz  in=424,016,641 out=103,945,320 elapsed=213.9s

  [15700/17668] intraday_8030.csv.gz  in=424,028,448 out=103,945,320 elapsed=213.9s

  [15701/17668] intraday_8032.csv.gz  in=424,043,179 out=103,945,320 elapsed=213.9s

  [15702/17668] intraday_8034.csv.gz  in=424,058,718 out=103,945,320 elapsed=214.0s

  [15703/17668] intraday_8033.csv.gz  in=424,072,792 out=103,945,320 elapsed=214.0s

  [15704/17668] intraday_8035.csv.gz  in=424,087,574 out=103,945,320 elapsed=214.0s

  [15705/17668] intraday_8036.csv.gz  in=424,097,859 out=103,945,320 elapsed=214.0s

  [15706/17668] intraday_8037.csv.gz  in=424,111,547 out=103,945,320 elapsed=214.0s

  [15707/17668] intraday_8038.csv.gz  in=424,123,297 out=103,945,320 elapsed=214.0s

  [15708/17668] intraday_8040.csv.gz  in=424,131,641 out=103,945,320 elapsed=214.0s

  [15709/17668] intraday_8039.csv.gz  in=424,147,050 out=103,945,320 elapsed=214.0s

  [15710/17668] intraday_8042.csv.gz  in=424,158,388 out=103,945,320 elapsed=214.1s

  [15711/17668] intraday_8041.csv.gz  in=424,170,637 out=103,945,320 elapsed=214.1s

  [15712/17668] intraday_8043.csv.gz  in=424,180,634 out=103,945,320 elapsed=214.1s

  [15713/17668] intraday_8044.csv.gz  in=424,195,734 out=103,945,320 elapsed=214.1s

  [15714/17668] intraday_8047.csv.gz  in=424,206,991 out=103,945,320 elapsed=214.1s

  [15715/17668] intraday_8046.csv.gz  in=424,219,899 out=103,945,320 elapsed=214.1s

  [15716/17668] intraday_8048.csv.gz  in=424,231,094 out=103,945,320 elapsed=214.1s

  [15717/17668] intraday_8045.csv.gz  in=424,245,396 out=103,945,320 elapsed=214.1s

  [15718/17668] intraday_8052.csv.gz  in=424,258,825 out=103,945,320 elapsed=214.1s

  [15719/17668] intraday_8051.csv.gz  in=424,271,301 out=103,945,320 elapsed=214.1s

  [15720/17668] intraday_8049.csv.gz  in=424,286,045 out=103,945,320 elapsed=214.1s

  [15721/17668] intraday_8050.csv.gz  in=424,300,113 out=103,945,320 elapsed=214.1s

  [15722/17668] intraday_8054.csv.gz  in=424,314,431 out=103,945,320 elapsed=214.2s

  [15723/17668] intraday_8055.csv.gz  in=424,327,618 out=103,945,320 elapsed=214.2s

  [15724/17668] intraday_8056.csv.gz  in=424,340,850 out=103,945,320 elapsed=214.2s

  [15725/17668] intraday_8053.csv.gz  in=424,356,363 out=103,945,320 elapsed=214.2s

  [15726/17668] intraday_8059.csv.gz  in=424,366,399 out=103,945,320 elapsed=214.2s

  [15727/17668] intraday_8057.csv.gz  in=424,379,677 out=103,945,320 elapsed=214.2s

  [15728/17668] intraday_8058.csv.gz  in=424,389,133 out=103,945,320 elapsed=214.2s

  [15729/17668] intraday_8060.csv.gz  in=424,402,483 out=103,945,320 elapsed=214.2s

  [15730/17668] intraday_8061.csv.gz  in=424,414,878 out=103,945,320 elapsed=214.2s

  [15731/17668] intraday_8062.csv.gz  in=424,425,606 out=103,945,320 elapsed=214.2s

  [15732/17668] intraday_8063.csv.gz  in=424,437,766 out=103,945,320 elapsed=214.3s

  [15733/17668] intraday_8064.csv.gz  in=424,449,789 out=103,945,320 elapsed=214.3s

  [15734/17668] intraday_8065.csv.gz  in=424,462,342 out=103,945,320 elapsed=214.3s

  [15735/17668] intraday_8066.csv.gz  in=424,474,929 out=103,945,320 elapsed=214.3s

  [15736/17668] intraday_8068.csv.gz  in=424,488,114 out=103,945,320 elapsed=214.3s

  [15737/17668] intraday_8069.csv.gz  in=424,501,715 out=103,945,320 elapsed=214.3s

  [15738/17668] intraday_8067.csv.gz  in=424,514,942 out=103,945,320 elapsed=214.3s

  [15739/17668] intraday_8071.csv.gz  in=424,526,512 out=103,945,320 elapsed=214.3s

  [15740/17668] intraday_8073.csv.gz  in=424,540,842 out=103,945,320 elapsed=214.3s

  [15741/17668] intraday_8070.csv.gz  in=424,562,382 out=103,945,320 elapsed=214.3s

  [15742/17668] intraday_8072.csv.gz  in=424,572,894 out=103,945,320 elapsed=214.3s

  [15743/17668] intraday_8076.csv.gz  in=424,583,480 out=103,945,320 elapsed=214.4s

  [15744/17668] intraday_8077.csv.gz  in=424,596,491 out=103,945,320 elapsed=214.4s

  [15745/17668] intraday_8074.csv.gz  in=424,612,681 out=103,945,320 elapsed=214.4s

  [15746/17668] intraday_8075.csv.gz  in=424,625,394 out=103,945,320 elapsed=214.4s

  [15747/17668] intraday_8079.csv.gz  in=424,637,876 out=103,945,320 elapsed=214.4s

  [15748/17668] intraday_8078.csv.gz  in=424,657,504 out=103,945,320 elapsed=214.4s

  [15749/17668] intraday_8080.csv.gz  in=424,670,136 out=103,945,320 elapsed=214.4s

  [15750/17668] intraday_8081.csv.gz  in=424,682,499 out=103,945,320 elapsed=214.4s

  [15751/17668] intraday_8082.csv.gz  in=424,695,277 out=103,945,320 elapsed=214.4s

  [15752/17668] intraday_8084.csv.gz  in=424,706,510 out=103,945,320 elapsed=214.5s

  [15753/17668] intraday_8083.csv.gz  in=424,717,783 out=103,945,320 elapsed=214.5s

  [15754/17668] intraday_8085.csv.gz  in=424,729,854 out=103,945,320 elapsed=214.5s

  [15755/17668] intraday_8086.csv.gz  in=424,742,472 out=103,945,320 elapsed=214.5s

  [15756/17668] intraday_8087.csv.gz  in=424,753,880 out=103,945,320 elapsed=214.5s

  [15757/17668] intraday_8089.csv.gz  in=424,765,126 out=103,945,320 elapsed=214.5s

  [15758/17668] intraday_8088.csv.gz  in=424,778,770 out=103,945,320 elapsed=214.5s

  [15759/17668] intraday_8090.csv.gz  in=424,790,471 out=103,945,320 elapsed=214.5s

  [15760/17668] intraday_8091.csv.gz  in=424,803,843 out=103,945,320 elapsed=214.5s

  [15761/17668] intraday_8092.csv.gz  in=424,816,215 out=103,945,320 elapsed=214.5s

  [15762/17668] intraday_8093.csv.gz  in=424,828,452 out=103,945,320 elapsed=214.5s

  [15763/17668] intraday_8094.csv.gz  in=424,840,261 out=103,945,320 elapsed=214.6s

  [15764/17668] intraday_8095.csv.gz  in=424,851,031 out=103,945,320 elapsed=214.6s

  [15765/17668] intraday_8097.csv.gz  in=424,862,504 out=103,945,320 elapsed=214.6s

  [15766/17668] intraday_8096.csv.gz  in=424,878,241 out=103,945,320 elapsed=214.6s

  [15767/17668] intraday_8098.csv.gz  in=424,893,182 out=103,945,320 elapsed=214.6s

  [15768/17668] intraday_8099.csv.gz  in=424,905,332 out=103,945,320 elapsed=214.6s

  [15769/17668] intraday_8100.csv.gz  in=424,919,853 out=103,945,320 elapsed=214.6s

  [15770/17668] intraday_8101.csv.gz  in=424,930,417 out=103,945,320 elapsed=214.6s

  [15771/17668] intraday_8102.csv.gz  in=424,942,903 out=103,945,320 elapsed=214.6s

  [15772/17668] intraday_8103.csv.gz  in=424,955,174 out=103,945,320 elapsed=214.6s

  [15773/17668] intraday_8104.csv.gz  in=424,966,964 out=103,945,320 elapsed=214.6s

  [15774/17668] intraday_8105.csv.gz  in=424,979,071 out=103,945,320 elapsed=214.7s

  [15775/17668] intraday_8106.csv.gz  in=424,990,901 out=103,945,320 elapsed=214.7s

  [15776/17668] intraday_8107.csv.gz  in=425,007,354 out=103,945,320 elapsed=214.7s

  [15777/17668] intraday_8109.csv.gz  in=425,020,780 out=103,945,320 elapsed=214.7s

  [15778/17668] intraday_8108.csv.gz  in=425,031,601 out=103,945,320 elapsed=214.7s

  [15779/17668] intraday_8110.csv.gz  in=425,045,257 out=103,945,320 elapsed=214.7s

  [15780/17668] intraday_8111.csv.gz  in=425,058,730 out=103,945,320 elapsed=214.7s

  [15781/17668] intraday_8112.csv.gz  in=425,071,428 out=103,945,320 elapsed=214.7s

  [15782/17668] intraday_8113.csv.gz  in=425,083,284 out=103,945,320 elapsed=214.7s

  [15783/17668] intraday_8114.csv.gz  in=425,096,287 out=103,945,320 elapsed=214.7s

  [15784/17668] intraday_8115.csv.gz  in=425,109,262 out=103,945,320 elapsed=214.7s

  [15785/17668] intraday_8116.csv.gz  in=425,121,604 out=103,945,320 elapsed=214.7s

  [15786/17668] intraday_8117.csv.gz  in=425,134,750 out=103,945,320 elapsed=214.8s

  [15787/17668] intraday_8118.csv.gz  in=425,146,144 out=103,945,320 elapsed=214.8s

  [15788/17668] intraday_8119.csv.gz  in=425,160,292 out=103,945,320 elapsed=214.8s

  [15789/17668] intraday_8120.csv.gz  in=425,170,607 out=103,945,320 elapsed=214.8s

  [15790/17668] intraday_8122.csv.gz  in=425,181,953 out=103,945,320 elapsed=214.8s

  [15791/17668] intraday_8121.csv.gz  in=425,194,884 out=103,945,320 elapsed=214.8s

  [15792/17668] intraday_8123.csv.gz  in=425,206,550 out=103,945,320 elapsed=214.8s

  [15793/17668] intraday_8124.csv.gz  in=425,216,850 out=103,945,320 elapsed=214.8s

  [15794/17668] intraday_8125.csv.gz  in=425,227,447 out=103,945,320 elapsed=214.8s

  [15795/17668] intraday_8126.csv.gz  in=425,239,350 out=103,945,320 elapsed=214.8s

  [15796/17668] intraday_8127.csv.gz  in=425,253,578 out=103,945,320 elapsed=214.8s

  [15797/17668] intraday_8128.csv.gz  in=425,271,370 out=103,945,320 elapsed=214.9s

  [15798/17668] intraday_8129.csv.gz  in=425,284,947 out=103,945,320 elapsed=214.9s

  [15799/17668] intraday_8130.csv.gz  in=425,296,809 out=103,945,320 elapsed=214.9s

  [15800/17668] intraday_8131.csv.gz  in=425,308,180 out=103,945,320 elapsed=214.9s

  [15801/17668] intraday_8132.csv.gz  in=425,321,446 out=103,945,320 elapsed=214.9s

  [15802/17668] intraday_8133.csv.gz  in=425,334,981 out=103,945,320 elapsed=214.9s

  [15803/17668] intraday_8135.csv.gz  in=425,347,449 out=103,945,320 elapsed=214.9s

  [15804/17668] intraday_8134.csv.gz  in=425,363,971 out=103,945,320 elapsed=214.9s

  [15805/17668] intraday_8136.csv.gz  in=425,376,411 out=103,945,320 elapsed=214.9s

  [15806/17668] intraday_8137.csv.gz  in=425,388,694 out=103,945,320 elapsed=214.9s

  [15807/17668] intraday_8138.csv.gz  in=425,402,825 out=103,945,320 elapsed=214.9s

  [15808/17668] intraday_8140.csv.gz  in=425,413,914 out=103,945,320 elapsed=215.0s

  [15809/17668] intraday_8139.csv.gz  in=425,428,859 out=103,945,320 elapsed=215.0s

  [15810/17668] intraday_8141.csv.gz  in=425,444,752 out=103,945,320 elapsed=215.0s

  [15811/17668] intraday_8142.csv.gz  in=425,456,432 out=103,945,320 elapsed=215.0s

  [15812/17668] intraday_8144.csv.gz  in=425,468,980 out=103,945,320 elapsed=215.0s

  [15813/17668] intraday_8143.csv.gz  in=425,483,258 out=103,945,320 elapsed=215.0s

  [15814/17668] intraday_8145.csv.gz  in=425,495,121 out=103,945,320 elapsed=215.0s

  [15815/17668] intraday_8146.csv.gz  in=425,508,149 out=103,945,320 elapsed=215.0s

  [15816/17668] intraday_8148.csv.gz  in=425,520,222 out=103,945,320 elapsed=215.0s

  [15817/17668] intraday_8147.csv.gz  in=425,534,225 out=103,945,320 elapsed=215.1s

  [15818/17668] intraday_8149.csv.gz  in=425,546,793 out=103,945,320 elapsed=215.1s

  [15819/17668] intraday_8150.csv.gz  in=425,561,116 out=103,945,320 elapsed=215.1s

  [15820/17668] intraday_8151.csv.gz  in=425,575,748 out=103,945,320 elapsed=215.1s

  [15821/17668] intraday_8152.csv.gz  in=425,589,632 out=103,945,320 elapsed=215.1s

  [15822/17668] intraday_8153.csv.gz  in=425,603,464 out=103,945,320 elapsed=215.1s

  [15823/17668] intraday_8154.csv.gz  in=425,619,816 out=103,945,320 elapsed=215.1s

  [15824/17668] intraday_8155.csv.gz  in=425,631,452 out=103,945,320 elapsed=215.1s

  [15825/17668] intraday_8156.csv.gz  in=425,644,829 out=103,945,320 elapsed=215.1s

  [15826/17668] intraday_8158.csv.gz  in=425,656,840 out=103,945,320 elapsed=215.1s

  [15827/17668] intraday_8157.csv.gz  in=425,670,893 out=103,945,320 elapsed=215.1s

  [15828/17668] intraday_8159.csv.gz  in=425,684,571 out=103,945,320 elapsed=215.1s

  [15829/17668] intraday_8162.csv.gz  in=425,699,708 out=103,945,320 elapsed=215.2s

  [15830/17668] intraday_8161.csv.gz  in=425,716,364 out=103,945,320 elapsed=215.2s

  [15831/17668] intraday_8160.csv.gz  in=425,731,899 out=103,945,320 elapsed=215.2s

  [15832/17668] intraday_8163.csv.gz  in=425,744,825 out=103,945,320 elapsed=215.2s

  [15833/17668] intraday_8166.csv.gz  in=425,755,989 out=103,945,320 elapsed=215.2s

  [15834/17668] intraday_8164.csv.gz  in=425,768,841 out=103,945,320 elapsed=215.2s

  [15835/17668] intraday_8165.csv.gz  in=425,784,314 out=103,945,320 elapsed=215.2s

  [15836/17668] intraday_8167.csv.gz  in=425,798,877 out=103,945,320 elapsed=215.2s

  [15837/17668] intraday_8168.csv.gz  in=425,809,688 out=103,945,320 elapsed=215.2s

  [15838/17668] intraday_8169.csv.gz  in=425,823,965 out=103,945,320 elapsed=215.3s

  [15839/17668] intraday_8170.csv.gz  in=425,837,734 out=103,945,320 elapsed=215.3s

  [15840/17668] intraday_8171.csv.gz  in=425,853,052 out=103,945,320 elapsed=215.3s

  [15841/17668] intraday_8174.csv.gz  in=425,866,994 out=103,945,320 elapsed=215.3s

  [15842/17668] intraday_8172.csv.gz  in=425,883,156 out=103,945,320 elapsed=215.3s

  [15843/17668] intraday_8173.csv.gz  in=425,895,477 out=103,945,320 elapsed=215.3s

  [15844/17668] intraday_8175.csv.gz  in=425,907,121 out=103,945,320 elapsed=215.3s

  [15845/17668] intraday_8176.csv.gz  in=425,920,150 out=103,945,320 elapsed=215.3s

  [15846/17668] intraday_8177.csv.gz  in=425,934,059 out=103,945,320 elapsed=215.3s

  [15847/17668] intraday_8178.csv.gz  in=425,948,929 out=103,945,320 elapsed=215.3s

  [15848/17668] intraday_8179.csv.gz  in=425,962,640 out=103,945,320 elapsed=215.3s

  [15849/17668] intraday_8180.csv.gz  in=425,976,163 out=103,945,320 elapsed=215.4s

  [15850/17668] intraday_8183.csv.gz  in=425,989,256 out=103,945,320 elapsed=215.4s

  [15851/17668] intraday_8181.csv.gz  in=426,001,845 out=103,945,320 elapsed=215.4s

  [15852/17668] intraday_8182.csv.gz  in=426,014,069 out=103,945,320 elapsed=215.4s

  [15853/17668] intraday_8184.csv.gz  in=426,025,572 out=103,945,320 elapsed=215.4s

  [15854/17668] intraday_8185.csv.gz  in=426,036,941 out=103,945,320 elapsed=215.4s

  [15855/17668] intraday_8186.csv.gz  in=426,044,385 out=103,945,320 elapsed=215.4s

  [15856/17668] intraday_8187.csv.gz  in=426,056,668 out=103,945,320 elapsed=215.4s

  [15857/17668] intraday_8189.csv.gz  in=426,056,707 out=103,945,320 elapsed=215.4s

  [15858/17668] intraday_8188.csv.gz  in=426,063,387 out=103,945,320 elapsed=215.4s

  [15859/17668] intraday_8191.csv.gz  in=426,065,875 out=103,945,320 elapsed=215.4s

  [15860/17668] intraday_8192.csv.gz  in=426,066,890 out=103,945,320 elapsed=215.4s

  [15861/17668] intraday_8190.csv.gz  in=426,070,987 out=103,945,320 elapsed=215.5s

  [15862/17668] intraday_8193.csv.gz  in=426,071,924 out=103,945,320 elapsed=215.5s

  [15863/17668] intraday_8194.csv.gz  in=426,072,554 out=103,945,320 elapsed=215.5s

  [15864/17668] intraday_8196.csv.gz  in=426,072,620 out=103,945,320 elapsed=215.5s

  [15865/17668] intraday_8195.csv.gz  in=426,072,705 out=103,945,320 elapsed=215.5s

  [15866/17668] intraday_8197.csv.gz  in=426,075,513 out=103,945,320 elapsed=215.5s

  [15867/17668] intraday_8198.csv.gz  in=426,075,867 out=103,945,320 elapsed=215.5s

  [15868/17668] intraday_8200.csv.gz  in=426,076,027 out=103,945,320 elapsed=215.5s

  [15869/17668] intraday_8199.csv.gz  in=426,080,639 out=103,945,320 elapsed=215.5s

  [15870/17668] intraday_8202.csv.gz  in=426,081,962 out=103,945,320 elapsed=215.5s

  [15871/17668] intraday_8203.csv.gz  in=426,082,212 out=103,945,320 elapsed=215.5s

  [15872/17668] intraday_8201.csv.gz  in=426,086,980 out=103,945,320 elapsed=215.5s

  [15873/17668] intraday_8204.csv.gz  in=426,087,020 out=103,945,320 elapsed=215.5s

  [15874/17668] intraday_8206.csv.gz  in=426,087,021 out=103,945,320 elapsed=215.5s

  [15875/17668] intraday_8207.csv.gz  in=426,091,804 out=103,945,320 elapsed=215.6s

  [15876/17668] intraday_8208.csv.gz  in=426,100,256 out=103,945,320 elapsed=215.6s

  [15877/17668] intraday_8205.csv.gz  in=426,110,979 out=103,945,320 elapsed=215.6s

  [15878/17668] intraday_8209.csv.gz  in=426,111,562 out=103,945,320 elapsed=215.6s

  [15879/17668] intraday_8210.csv.gz  in=426,111,680 out=103,945,320 elapsed=215.6s

  [15880/17668] intraday_8213.csv.gz  in=426,111,903 out=103,945,320 elapsed=215.6s

  [15881/17668] intraday_8214.csv.gz  in=426,113,518 out=103,945,320 elapsed=215.6s

  [15882/17668] intraday_8211.csv.gz  in=426,114,496 out=103,945,320 elapsed=215.6s

  [15883/17668] intraday_8215.csv.gz  in=426,115,062 out=103,945,320 elapsed=215.6s

  [15884/17668] intraday_8216.csv.gz  in=426,115,882 out=103,945,320 elapsed=215.6s

  [15885/17668] intraday_8217.csv.gz  in=426,116,451 out=103,945,320 elapsed=215.6s

  [15886/17668] intraday_8218.csv.gz  in=426,117,536 out=103,945,320 elapsed=215.6s

  [15887/17668] intraday_8212.csv.gz  in=426,131,432 out=103,945,320 elapsed=215.6s

  [15888/17668] intraday_8221.csv.gz  in=426,132,110 out=103,945,320 elapsed=215.6s

  [15889/17668] intraday_8219.csv.gz  in=426,132,888 out=103,945,320 elapsed=215.6s

  [15890/17668] intraday_8220.csv.gz  in=426,134,146 out=103,945,320 elapsed=215.6s

  [15891/17668] intraday_8222.csv.gz  in=426,134,827 out=103,945,320 elapsed=215.6s

  [15892/17668] intraday_8223.csv.gz  in=426,135,816 out=103,945,320 elapsed=215.6s

  [15893/17668] intraday_8224.csv.gz  in=426,137,177 out=103,945,320 elapsed=215.6s

  [15894/17668] intraday_8225.csv.gz  in=426,138,017 out=103,945,320 elapsed=215.7s

  [15895/17668] intraday_8226.csv.gz  in=426,138,855 out=103,945,320 elapsed=215.7s

  [15896/17668] intraday_8227.csv.gz  in=426,139,919 out=103,945,320 elapsed=215.7s

  [15897/17668] intraday_8228.csv.gz  in=426,140,180 out=103,945,320 elapsed=215.7s

  [15898/17668] intraday_8231.csv.gz  in=426,140,993 out=103,945,320 elapsed=215.7s

  [15899/17668] intraday_8230.csv.gz  in=426,141,795 out=103,945,320 elapsed=215.7s

  [15900/17668] intraday_8229.csv.gz  in=426,142,135 out=103,945,320 elapsed=215.7s

  [15901/17668] intraday_8232.csv.gz  in=426,142,697 out=103,945,320 elapsed=215.7s

  [15902/17668] intraday_8235.csv.gz  in=426,143,340 out=103,945,320 elapsed=215.7s

  [15903/17668] intraday_8233.csv.gz  in=426,143,725 out=103,945,320 elapsed=215.7s

  [15904/17668] intraday_8234.csv.gz  in=426,144,397 out=103,945,320 elapsed=215.7s

  [15905/17668] intraday_8236.csv.gz  in=426,144,786 out=103,945,320 elapsed=215.7s

  [15906/17668] intraday_8237.csv.gz  in=426,145,684 out=103,945,320 elapsed=215.7s

  [15907/17668] intraday_8240.csv.gz  in=426,146,259 out=103,945,320 elapsed=215.7s

  [15908/17668] intraday_8239.csv.gz  in=426,147,227 out=103,945,320 elapsed=215.7s

  [15909/17668] intraday_8238.csv.gz  in=426,147,668 out=103,945,320 elapsed=215.7s

  [15910/17668] intraday_8241.csv.gz  in=426,147,863 out=103,945,320 elapsed=215.7s

  [15911/17668] intraday_8242.csv.gz  in=426,148,846 out=103,945,320 elapsed=215.7s

  [15912/17668] intraday_8243.csv.gz  in=426,149,936 out=103,945,320 elapsed=215.7s

  [15913/17668] intraday_8245.csv.gz  in=426,150,899 out=103,945,320 elapsed=215.7s

  [15914/17668] intraday_8244.csv.gz  in=426,152,365 out=103,945,320 elapsed=215.7s

  [15915/17668] intraday_8247.csv.gz  in=426,152,942 out=103,945,320 elapsed=215.7s

  [15916/17668] intraday_8246.csv.gz  in=426,153,492 out=103,945,320 elapsed=215.7s

  [15917/17668] intraday_8249.csv.gz  in=426,154,225 out=103,945,320 elapsed=215.8s

  [15918/17668] intraday_8248.csv.gz  in=426,154,669 out=103,945,320 elapsed=215.8s

  [15919/17668] intraday_8250.csv.gz  in=426,155,073 out=103,945,320 elapsed=215.8s

  [15920/17668] intraday_8251.csv.gz  in=426,155,734 out=103,945,320 elapsed=215.8s

  [15921/17668] intraday_8253.csv.gz  in=426,156,065 out=103,945,320 elapsed=215.8s

  [15922/17668] intraday_8254.csv.gz  in=426,156,402 out=103,945,320 elapsed=215.8s

  [15923/17668] intraday_8252.csv.gz  in=426,156,953 out=103,945,320 elapsed=215.8s

  [15924/17668] intraday_8255.csv.gz  in=426,157,443 out=103,945,320 elapsed=215.8s

  [15925/17668] intraday_8256.csv.gz  in=426,157,821 out=103,945,320 elapsed=215.8s

  [15926/17668] intraday_8257.csv.gz  in=426,158,317 out=103,945,320 elapsed=215.8s

  [15927/17668] intraday_8258.csv.gz  in=426,158,882 out=103,945,320 elapsed=215.8s

  [15928/17668] intraday_8259.csv.gz  in=426,159,492 out=103,945,320 elapsed=215.8s

  [15929/17668] intraday_8260.csv.gz  in=426,159,710 out=103,945,320 elapsed=215.8s

  [15930/17668] intraday_8262.csv.gz  in=426,160,339 out=103,945,320 elapsed=215.8s

  [15931/17668] intraday_8261.csv.gz  in=426,160,858 out=103,945,320 elapsed=215.8s

  [15932/17668] intraday_8263.csv.gz  in=426,161,139 out=103,945,320 elapsed=215.8s

  [15933/17668] intraday_8264.csv.gz  in=426,161,466 out=103,945,320 elapsed=215.8s

  [15934/17668] intraday_8265.csv.gz  in=426,161,989 out=103,945,320 elapsed=215.8s

  [15935/17668] intraday_8266.csv.gz  in=426,163,111 out=103,945,320 elapsed=215.8s

  [15936/17668] intraday_8267.csv.gz  in=426,164,277 out=103,945,320 elapsed=215.8s

  [15937/17668] intraday_8268.csv.gz  in=426,165,189 out=103,945,320 elapsed=215.8s

  [15938/17668] intraday_8269.csv.gz  in=426,165,762 out=103,945,320 elapsed=215.8s

  [15939/17668] intraday_8271.csv.gz  in=426,165,967 out=103,945,320 elapsed=215.8s

  [15940/17668] intraday_8272.csv.gz  in=426,166,938 out=103,945,320 elapsed=215.8s

  [15941/17668] intraday_8273.csv.gz  in=426,167,793 out=103,945,320 elapsed=215.8s

  [15942/17668] intraday_8270.csv.gz  in=426,168,008 out=103,945,320 elapsed=215.8s

  [15943/17668] intraday_8274.csv.gz  in=426,168,275 out=103,945,320 elapsed=215.8s

  [15944/17668] intraday_8275.csv.gz  in=426,169,242 out=103,945,320 elapsed=215.8s

  [15945/17668] intraday_8277.csv.gz  in=426,169,439 out=103,945,320 elapsed=215.9s

  [15946/17668] intraday_8276.csv.gz  in=426,169,567 out=103,945,320 elapsed=215.9s

  [15947/17668] intraday_8278.csv.gz  in=426,170,071 out=103,945,320 elapsed=215.9s

  [15948/17668] intraday_8280.csv.gz  in=426,171,198 out=103,945,320 elapsed=215.9s

  [15949/17668] intraday_8279.csv.gz  in=426,172,674 out=103,945,320 elapsed=215.9s

  [15950/17668] intraday_8281.csv.gz  in=426,173,021 out=103,945,320 elapsed=215.9s

  [15951/17668] intraday_8282.csv.gz  in=426,173,676 out=103,945,320 elapsed=215.9s

  [15952/17668] intraday_8285.csv.gz  in=426,174,727 out=103,945,320 elapsed=215.9s

  [15953/17668] intraday_8286.csv.gz  in=426,175,100 out=103,945,320 elapsed=215.9s

  [15954/17668] intraday_8283.csv.gz  in=426,175,626 out=103,945,320 elapsed=215.9s

  [15955/17668] intraday_8284.csv.gz  in=426,176,070 out=103,945,320 elapsed=215.9s

  [15956/17668] intraday_8289.csv.gz  in=426,177,105 out=103,945,320 elapsed=215.9s

  [15957/17668] intraday_8288.csv.gz  in=426,177,494 out=103,945,320 elapsed=215.9s

  [15958/17668] intraday_8287.csv.gz  in=426,178,103 out=103,945,320 elapsed=215.9s

  [15959/17668] intraday_8290.csv.gz  in=426,178,618 out=103,945,320 elapsed=215.9s

  [15960/17668] intraday_8291.csv.gz  in=426,179,371 out=103,945,320 elapsed=215.9s

  [15961/17668] intraday_8293.csv.gz  in=426,180,072 out=103,945,320 elapsed=215.9s

  [15962/17668] intraday_8292.csv.gz  in=426,180,727 out=103,945,320 elapsed=215.9s

  [15963/17668] intraday_8296.csv.gz  in=426,181,372 out=103,945,320 elapsed=215.9s

  [15964/17668] intraday_8295.csv.gz  in=426,181,735 out=103,945,320 elapsed=215.9s

  [15965/17668] intraday_8294.csv.gz  in=426,181,833 out=103,945,320 elapsed=215.9s

  [15966/17668] intraday_8297.csv.gz  in=426,184,163 out=103,945,320 elapsed=215.9s

  [15967/17668] intraday_8299.csv.gz  in=426,185,303 out=103,945,320 elapsed=215.9s

  [15968/17668] intraday_8301.csv.gz  in=426,185,778 out=103,945,320 elapsed=215.9s

  [15969/17668] intraday_8298.csv.gz  in=426,187,244 out=103,945,320 elapsed=215.9s

  [15970/17668] intraday_8300.csv.gz  in=426,188,210 out=103,945,320 elapsed=216.0s

  [15971/17668] intraday_8302.csv.gz  in=426,189,126 out=103,945,320 elapsed=216.0s

  [15972/17668] intraday_8303.csv.gz  in=426,190,236 out=103,945,320 elapsed=216.0s

  [15973/17668] intraday_8304.csv.gz  in=426,191,568 out=103,945,320 elapsed=216.0s

  [15974/17668] intraday_8305.csv.gz  in=426,191,841 out=103,945,320 elapsed=216.0s

  [15975/17668] intraday_8307.csv.gz  in=426,193,052 out=103,945,320 elapsed=216.0s

  [15976/17668] intraday_8308.csv.gz  in=426,193,633 out=103,945,320 elapsed=216.0s

  [15977/17668] intraday_8306.csv.gz  in=426,194,457 out=103,945,320 elapsed=216.0s

  [15978/17668] intraday_8311.csv.gz  in=426,194,795 out=103,945,320 elapsed=216.0s

  [15979/17668] intraday_8309.csv.gz  in=426,195,558 out=103,945,320 elapsed=216.0s

  [15980/17668] intraday_8310.csv.gz  in=426,196,044 out=103,945,320 elapsed=216.0s

  [15981/17668] intraday_8312.csv.gz  in=426,200,309 out=103,945,320 elapsed=216.0s

  [15982/17668] intraday_8314.csv.gz  in=426,200,494 out=103,945,320 elapsed=216.0s

  [15983/17668] intraday_8313.csv.gz  in=426,201,476 out=103,945,320 elapsed=216.0s

  [15984/17668] intraday_8315.csv.gz  in=426,202,207 out=103,945,320 elapsed=216.0s

  [15985/17668] intraday_8317.csv.gz  in=426,203,938 out=103,945,320 elapsed=216.0s

  [15986/17668] intraday_8318.csv.gz  in=426,204,784 out=103,945,320 elapsed=216.0s

  [15987/17668] intraday_8319.csv.gz  in=426,205,124 out=103,945,320 elapsed=216.0s

  [15988/17668] intraday_8316.csv.gz  in=426,206,690 out=103,945,320 elapsed=216.0s

  [15989/17668] intraday_8320.csv.gz  in=426,208,528 out=103,945,320 elapsed=216.0s

  [15990/17668] intraday_8323.csv.gz  in=426,209,524 out=103,945,320 elapsed=216.0s

  [15991/17668] intraday_8322.csv.gz  in=426,210,039 out=103,945,320 elapsed=216.0s

  [15992/17668] intraday_8321.csv.gz  in=426,210,536 out=103,945,320 elapsed=216.0s

  [15993/17668] intraday_8324.csv.gz  in=426,211,140 out=103,945,320 elapsed=216.0s

  [15994/17668] intraday_8325.csv.gz  in=426,211,926 out=103,945,320 elapsed=216.1s

  [15995/17668] intraday_8327.csv.gz  in=426,212,675 out=103,945,320 elapsed=216.1s

  [15996/17668] intraday_8326.csv.gz  in=426,213,472 out=103,945,320 elapsed=216.1s

  [15997/17668] intraday_8330.csv.gz  in=426,214,932 out=103,945,320 elapsed=216.1s

  [15998/17668] intraday_8328.csv.gz  in=426,216,034 out=103,945,320 elapsed=216.1s

  [15999/17668] intraday_8329.csv.gz  in=426,218,219 out=103,945,320 elapsed=216.1s

  [16000/17668] intraday_8333.csv.gz  in=426,219,091 out=103,945,320 elapsed=216.1s

  [16001/17668] intraday_8331.csv.gz  in=426,219,794 out=103,945,320 elapsed=216.1s

  [16002/17668] intraday_8332.csv.gz  in=426,221,176 out=103,945,320 elapsed=216.1s

  [16003/17668] intraday_8335.csv.gz  in=426,221,403 out=103,945,320 elapsed=216.1s

  [16004/17668] intraday_8334.csv.gz  in=426,221,855 out=103,945,320 elapsed=216.1s

  [16005/17668] intraday_8336.csv.gz  in=426,222,378 out=103,945,320 elapsed=216.1s

  [16006/17668] intraday_8337.csv.gz  in=426,222,818 out=103,945,320 elapsed=216.1s

  [16007/17668] intraday_8338.csv.gz  in=426,223,437 out=103,945,320 elapsed=216.1s

  [16008/17668] intraday_8339.csv.gz  in=426,224,197 out=103,945,320 elapsed=216.1s

  [16009/17668] intraday_8340.csv.gz  in=426,225,178 out=103,945,320 elapsed=216.1s

  [16010/17668] intraday_8341.csv.gz  in=426,226,289 out=103,945,320 elapsed=216.1s

  [16011/17668] intraday_8342.csv.gz  in=426,226,929 out=103,945,320 elapsed=216.1s

  [16012/17668] intraday_8344.csv.gz  in=426,227,848 out=103,945,320 elapsed=216.1s

  [16013/17668] intraday_8343.csv.gz  in=426,228,850 out=103,945,320 elapsed=216.1s

  [16014/17668] intraday_8345.csv.gz  in=426,229,715 out=103,945,320 elapsed=216.1s

  [16015/17668] intraday_8347.csv.gz  in=426,230,215 out=103,945,320 elapsed=216.1s

  [16016/17668] intraday_8348.csv.gz  in=426,230,633 out=103,945,320 elapsed=216.1s

  [16017/17668] intraday_8346.csv.gz  in=426,231,093 out=103,945,320 elapsed=216.1s

  [16018/17668] intraday_8349.csv.gz  in=426,232,337 out=103,945,320 elapsed=216.1s

  [16019/17668] intraday_8350.csv.gz  in=426,232,971 out=103,945,320 elapsed=216.1s

  [16020/17668] intraday_8352.csv.gz  in=426,233,772 out=103,945,320 elapsed=216.1s

  [16021/17668] intraday_8351.csv.gz  in=426,234,136 out=103,945,320 elapsed=216.2s

  [16022/17668] intraday_8354.csv.gz  in=426,235,381 out=103,945,320 elapsed=216.2s

  [16023/17668] intraday_8353.csv.gz  in=426,235,734 out=103,945,320 elapsed=216.2s

  [16024/17668] intraday_8356.csv.gz  in=426,236,116 out=103,945,320 elapsed=216.2s

  [16025/17668] intraday_8355.csv.gz  in=426,236,514 out=103,945,320 elapsed=216.2s

  [16026/17668] intraday_8358.csv.gz  in=426,236,523 out=103,945,320 elapsed=216.2s

  [16027/17668] intraday_8357.csv.gz  in=426,237,525 out=103,945,320 elapsed=216.2s

  [16028/17668] intraday_8359.csv.gz  in=426,253,024 out=103,945,320 elapsed=216.2s

  [16029/17668] intraday_8360.csv.gz  in=426,265,512 out=103,945,320 elapsed=216.2s

  [16030/17668] intraday_8362.csv.gz  in=426,277,975 out=103,945,320 elapsed=216.2s

  [16031/17668] intraday_8361.csv.gz  in=426,291,865 out=103,945,320 elapsed=216.2s

  [16032/17668] intraday_8363.csv.gz  in=426,304,992 out=103,945,320 elapsed=216.3s

  [16033/17668] intraday_8364.csv.gz  in=426,319,547 out=103,945,320 elapsed=216.3s

  [16034/17668] intraday_8365.csv.gz  in=426,334,941 out=103,945,320 elapsed=216.3s

  [16035/17668] intraday_8366.csv.gz  in=426,347,370 out=103,945,320 elapsed=216.3s

  [16036/17668] intraday_8367.csv.gz  in=426,360,591 out=103,945,320 elapsed=216.3s

  [16037/17668] intraday_8368.csv.gz  in=426,376,183 out=103,945,320 elapsed=216.3s

  [16038/17668] intraday_8370.csv.gz  in=426,389,813 out=103,945,320 elapsed=216.3s

  [16039/17668] intraday_8369.csv.gz  in=426,404,798 out=103,945,320 elapsed=216.3s

  [16040/17668] intraday_8371.csv.gz  in=426,419,371 out=103,945,320 elapsed=216.3s

  [16041/17668] intraday_8372.csv.gz  in=426,432,517 out=103,945,320 elapsed=216.3s

  [16042/17668] intraday_8373.csv.gz  in=426,442,225 out=103,945,320 elapsed=216.3s

  [16043/17668] intraday_8374.csv.gz  in=426,452,910 out=103,945,320 elapsed=216.3s

  [16044/17668] intraday_8375.csv.gz  in=426,466,709 out=103,945,320 elapsed=216.4s

  [16045/17668] intraday_8377.csv.gz  in=426,478,163 out=103,945,320 elapsed=216.4s

  [16046/17668] intraday_8376.csv.gz  in=426,491,783 out=103,945,320 elapsed=216.4s

  [16047/17668] intraday_8378.csv.gz  in=426,503,825 out=103,945,320 elapsed=216.4s

  [16048/17668] intraday_8379.csv.gz  in=426,516,405 out=103,945,320 elapsed=216.4s

  [16049/17668] intraday_8380.csv.gz  in=426,529,549 out=103,945,320 elapsed=216.4s

  [16050/17668] intraday_8382.csv.gz  in=426,544,000 out=103,945,320 elapsed=216.4s

  [16051/17668] intraday_8381.csv.gz  in=426,556,754 out=103,945,320 elapsed=216.4s

  [16052/17668] intraday_8383.csv.gz  in=426,570,612 out=103,945,320 elapsed=216.4s

  [16053/17668] intraday_8386.csv.gz  in=426,583,540 out=103,945,320 elapsed=216.5s

  [16054/17668] intraday_8385.csv.gz  in=426,595,706 out=103,945,320 elapsed=216.5s

  [16055/17668] intraday_8387.csv.gz  in=426,607,702 out=103,945,320 elapsed=216.5s

  [16056/17668] intraday_8384.csv.gz  in=426,620,887 out=103,945,320 elapsed=216.5s

  [16057/17668] intraday_8388.csv.gz  in=426,635,903 out=103,945,320 elapsed=216.5s

  [16058/17668] intraday_8390.csv.gz  in=426,649,202 out=103,945,320 elapsed=216.5s

  [16059/17668] intraday_8391.csv.gz  in=426,661,006 out=103,945,320 elapsed=216.5s

  [16060/17668] intraday_8389.csv.gz  in=426,677,863 out=103,945,320 elapsed=216.5s

  [16061/17668] intraday_8393.csv.gz  in=426,692,253 out=103,945,320 elapsed=216.5s

  [16062/17668] intraday_8392.csv.gz  in=426,704,775 out=103,945,320 elapsed=216.5s

  [16063/17668] intraday_8394.csv.gz  in=426,717,144 out=103,945,320 elapsed=216.5s

  [16064/17668] intraday_8395.csv.gz  in=426,729,591 out=103,945,320 elapsed=216.5s

  [16065/17668] intraday_8396.csv.gz  in=426,741,196 out=103,945,320 elapsed=216.5s

  [16066/17668] intraday_8398.csv.gz  in=426,751,639 out=103,945,320 elapsed=216.6s

  [16067/17668] intraday_8399.csv.gz  in=426,763,961 out=103,945,320 elapsed=216.6s

  [16068/17668] intraday_8397.csv.gz  in=426,777,419 out=103,945,320 elapsed=216.6s

  [16069/17668] intraday_8401.csv.gz  in=426,791,332 out=103,945,320 elapsed=216.6s

  [16070/17668] intraday_8400.csv.gz  in=426,803,915 out=103,945,320 elapsed=216.6s

  [16071/17668] intraday_8402.csv.gz  in=426,816,541 out=103,945,320 elapsed=216.6s

  [16072/17668] intraday_8403.csv.gz  in=426,830,586 out=103,945,320 elapsed=216.6s

  [16073/17668] intraday_8404.csv.gz  in=426,841,900 out=103,945,320 elapsed=216.6s

  [16074/17668] intraday_8405.csv.gz  in=426,853,736 out=103,945,320 elapsed=216.6s

  [16075/17668] intraday_8407.csv.gz  in=426,865,378 out=103,945,320 elapsed=216.6s

  [16076/17668] intraday_8406.csv.gz  in=426,879,192 out=103,945,320 elapsed=216.6s

  [16077/17668] intraday_8408.csv.gz  in=426,892,158 out=103,945,320 elapsed=216.7s

  [16078/17668] intraday_8410.csv.gz  in=426,904,380 out=103,945,320 elapsed=216.7s

  [16079/17668] intraday_8409.csv.gz  in=426,916,253 out=103,945,320 elapsed=216.7s

  [16080/17668] intraday_8411.csv.gz  in=426,931,218 out=103,945,320 elapsed=216.7s

  [16081/17668] intraday_8414.csv.gz  in=426,944,916 out=103,945,320 elapsed=216.7s

  [16082/17668] intraday_8412.csv.gz  in=426,957,635 out=103,945,320 elapsed=216.7s

  [16083/17668] intraday_8413.csv.gz  in=426,972,268 out=103,945,320 elapsed=216.7s

  [16084/17668] intraday_8415.csv.gz  in=426,984,040 out=103,945,320 elapsed=216.7s

  [16085/17668] intraday_8416.csv.gz  in=426,994,703 out=103,945,320 elapsed=216.7s

  [16086/17668] intraday_8417.csv.gz  in=427,009,819 out=103,945,320 elapsed=216.8s

  [16087/17668] intraday_8419.csv.gz  in=427,021,643 out=103,945,320 elapsed=216.8s

  [16088/17668] intraday_8418.csv.gz  in=427,035,375 out=103,945,320 elapsed=216.8s

  [16089/17668] intraday_8420.csv.gz  in=427,049,606 out=103,945,320 elapsed=216.8s

  [16090/17668] intraday_8421.csv.gz  in=427,061,019 out=103,945,320 elapsed=216.8s

  [16091/17668] intraday_8422.csv.gz  in=427,072,063 out=103,945,320 elapsed=216.8s

  [16092/17668] intraday_8423.csv.gz  in=427,083,206 out=103,945,320 elapsed=216.8s

  [16093/17668] intraday_8425.csv.gz  in=427,095,956 out=103,945,320 elapsed=216.8s

  [16094/17668] intraday_8426.csv.gz  in=427,111,044 out=103,945,320 elapsed=216.8s

  [16095/17668] intraday_8427.csv.gz  in=427,123,802 out=103,945,320 elapsed=216.8s

  [16096/17668] intraday_8424.csv.gz  in=427,138,221 out=103,945,320 elapsed=216.8s

  [16097/17668] intraday_8428.csv.gz  in=427,149,673 out=103,945,320 elapsed=216.8s

  [16098/17668] intraday_8429.csv.gz  in=427,161,146 out=103,945,320 elapsed=216.9s

  [16099/17668] intraday_8430.csv.gz  in=427,174,243 out=103,945,320 elapsed=216.9s

  [16100/17668] intraday_8432.csv.gz  in=427,188,580 out=103,945,320 elapsed=216.9s

  [16101/17668] intraday_8431.csv.gz  in=427,201,304 out=103,945,320 elapsed=216.9s

  [16102/17668] intraday_8433.csv.gz  in=427,213,080 out=103,945,320 elapsed=216.9s

  [16103/17668] intraday_8434.csv.gz  in=427,223,444 out=103,945,320 elapsed=216.9s

  [16104/17668] intraday_8435.csv.gz  in=427,234,510 out=103,945,320 elapsed=216.9s

  [16105/17668] intraday_8436.csv.gz  in=427,248,398 out=103,945,320 elapsed=216.9s

  [16106/17668] intraday_8437.csv.gz  in=427,259,261 out=103,945,320 elapsed=216.9s

  [16107/17668] intraday_8438.csv.gz  in=427,271,937 out=103,945,320 elapsed=217.0s

  [16108/17668] intraday_8439.csv.gz  in=427,282,141 out=103,945,320 elapsed=217.0s

  [16109/17668] intraday_8441.csv.gz  in=427,294,617 out=103,945,320 elapsed=217.0s

  [16110/17668] intraday_8440.csv.gz  in=427,305,976 out=103,945,320 elapsed=217.0s

  [16111/17668] intraday_8442.csv.gz  in=427,321,791 out=103,945,320 elapsed=217.0s

  [16112/17668] intraday_8443.csv.gz  in=427,338,818 out=103,945,320 elapsed=217.0s

  [16113/17668] intraday_8444.csv.gz  in=427,352,410 out=103,945,320 elapsed=217.0s

  [16114/17668] intraday_8445.csv.gz  in=427,364,209 out=103,945,320 elapsed=217.0s

  [16115/17668] intraday_8446.csv.gz  in=427,376,024 out=103,945,320 elapsed=217.0s

  [16116/17668] intraday_8447.csv.gz  in=427,390,579 out=103,945,320 elapsed=217.0s

  [16117/17668] intraday_8448.csv.gz  in=427,404,593 out=103,945,320 elapsed=217.0s

  [16118/17668] intraday_8449.csv.gz  in=427,419,375 out=103,945,320 elapsed=217.1s

  [16119/17668] intraday_8451.csv.gz  in=427,433,750 out=103,945,320 elapsed=217.1s

  [16120/17668] intraday_8450.csv.gz  in=427,445,446 out=103,945,320 elapsed=217.1s

  [16121/17668] intraday_8452.csv.gz  in=427,459,722 out=103,945,320 elapsed=217.1s

  [16122/17668] intraday_8453.csv.gz  in=427,473,193 out=103,945,320 elapsed=217.1s

  [16123/17668] intraday_8454.csv.gz  in=427,487,446 out=103,945,320 elapsed=217.1s

  [16124/17668] intraday_8456.csv.gz  in=427,499,416 out=103,945,320 elapsed=217.1s

  [16125/17668] intraday_8457.csv.gz  in=427,512,268 out=103,945,320 elapsed=217.1s

  [16126/17668] intraday_8455.csv.gz  in=427,524,614 out=103,945,320 elapsed=217.1s

  [16127/17668] intraday_8458.csv.gz  in=427,538,873 out=103,945,320 elapsed=217.1s

  [16128/17668] intraday_8459.csv.gz  in=427,551,817 out=103,945,320 elapsed=217.2s

  [16129/17668] intraday_8460.csv.gz  in=427,565,238 out=103,945,320 elapsed=217.2s

  [16130/17668] intraday_8461.csv.gz  in=427,580,394 out=103,945,320 elapsed=217.2s

  [16131/17668] intraday_8464.csv.gz  in=427,592,666 out=103,945,320 elapsed=217.2s

  [16132/17668] intraday_8462.csv.gz  in=427,606,486 out=103,945,320 elapsed=217.2s

  [16133/17668] intraday_8463.csv.gz  in=427,619,163 out=103,945,320 elapsed=217.2s

  [16134/17668] intraday_8465.csv.gz  in=427,638,207 out=103,945,320 elapsed=217.2s

  [16135/17668] intraday_8466.csv.gz  in=427,651,037 out=103,945,320 elapsed=217.2s

  [16136/17668] intraday_8467.csv.gz  in=427,664,554 out=103,945,320 elapsed=217.2s

  [16137/17668] intraday_8469.csv.gz  in=427,678,368 out=103,945,320 elapsed=217.2s

  [16138/17668] intraday_8468.csv.gz  in=427,695,106 out=103,945,320 elapsed=217.2s

  [16139/17668] intraday_8470.csv.gz  in=427,707,107 out=103,945,320 elapsed=217.2s

  [16140/17668] intraday_8473.csv.gz  in=427,720,540 out=103,945,320 elapsed=217.3s

  [16141/17668] intraday_8471.csv.gz  in=427,734,856 out=103,945,320 elapsed=217.3s

  [16142/17668] intraday_8472.csv.gz  in=427,747,836 out=103,945,320 elapsed=217.3s

  [16143/17668] intraday_8474.csv.gz  in=427,767,228 out=103,945,320 elapsed=217.3s

  [16144/17668] intraday_8475.csv.gz  in=427,781,142 out=103,945,320 elapsed=217.3s

  [16145/17668] intraday_8476.csv.gz  in=427,794,916 out=103,945,320 elapsed=217.3s

  [16146/17668] intraday_8477.csv.gz  in=427,811,343 out=103,945,320 elapsed=217.3s

  [16147/17668] intraday_8481.csv.gz  in=427,824,527 out=103,945,320 elapsed=217.3s

  [16148/17668] intraday_8478.csv.gz  in=427,837,838 out=103,945,320 elapsed=217.3s

  [16149/17668] intraday_8479.csv.gz  in=427,849,681 out=103,945,320 elapsed=217.3s

  [16150/17668] intraday_8480.csv.gz  in=427,861,794 out=103,945,320 elapsed=217.4s

  [16151/17668] intraday_8482.csv.gz  in=427,873,135 out=103,945,320 elapsed=217.4s

  [16152/17668] intraday_8483.csv.gz  in=427,885,715 out=103,945,320 elapsed=217.4s

  [16153/17668] intraday_8485.csv.gz  in=427,901,842 out=103,945,320 elapsed=217.4s

  [16154/17668] intraday_8484.csv.gz  in=427,915,831 out=103,945,320 elapsed=217.4s

  [16155/17668] intraday_8486.csv.gz  in=427,927,482 out=103,945,320 elapsed=217.4s

  [16156/17668] intraday_8487.csv.gz  in=427,941,092 out=103,945,320 elapsed=217.4s

  [16157/17668] intraday_8488.csv.gz  in=427,952,254 out=103,945,320 elapsed=217.4s

  [16158/17668] intraday_8489.csv.gz  in=427,967,520 out=103,945,320 elapsed=217.4s

  [16159/17668] intraday_8490.csv.gz  in=427,978,854 out=103,945,320 elapsed=217.5s

  [16160/17668] intraday_8492.csv.gz  in=427,993,508 out=103,945,320 elapsed=217.5s

  [16161/17668] intraday_8491.csv.gz  in=428,007,083 out=103,945,320 elapsed=217.5s

  [16162/17668] intraday_8493.csv.gz  in=428,021,629 out=103,945,320 elapsed=217.5s

  [16163/17668] intraday_8494.csv.gz  in=428,036,006 out=103,945,320 elapsed=217.5s

  [16164/17668] intraday_8495.csv.gz  in=428,050,141 out=103,945,320 elapsed=217.5s

  [16165/17668] intraday_8496.csv.gz  in=428,062,137 out=103,945,320 elapsed=217.5s

  [16166/17668] intraday_8498.csv.gz  in=428,073,697 out=103,945,320 elapsed=217.5s

  [16167/17668] intraday_8497.csv.gz  in=428,087,944 out=103,945,320 elapsed=217.5s

  [16168/17668] intraday_8501.csv.gz  in=428,096,622 out=103,945,320 elapsed=217.5s

  [16169/17668] intraday_8499.csv.gz  in=428,111,312 out=103,945,320 elapsed=217.6s

  [16170/17668] intraday_8500.csv.gz  in=428,121,732 out=103,945,320 elapsed=217.6s

  [16171/17668] intraday_8502.csv.gz  in=428,135,613 out=103,945,320 elapsed=217.6s

  [16172/17668] intraday_8503.csv.gz  in=428,136,804 out=103,945,320 elapsed=217.6s

  [16173/17668] intraday_8507.csv.gz  in=428,148,780 out=103,945,320 elapsed=217.6s

  [16174/17668] intraday_8506.csv.gz  in=428,163,651 out=103,945,320 elapsed=217.6s

  [16175/17668] intraday_8505.csv.gz  in=428,177,814 out=103,945,320 elapsed=217.6s

  [16176/17668] intraday_8508.csv.gz  in=428,190,743 out=103,945,320 elapsed=217.6s

  [16177/17668] intraday_8504.csv.gz  in=428,237,464 out=103,945,320 elapsed=217.6s

  [16178/17668] intraday_8509.csv.gz  in=428,248,433 out=103,945,320 elapsed=217.6s

  [16179/17668] intraday_8510.csv.gz  in=428,261,437 out=103,945,320 elapsed=217.6s

  [16180/17668] intraday_8513.csv.gz  in=428,274,166 out=103,945,320 elapsed=217.7s

  [16181/17668] intraday_8511.csv.gz  in=428,288,929 out=103,945,320 elapsed=217.7s

  [16182/17668] intraday_8512.csv.gz  in=428,302,370 out=103,945,320 elapsed=217.7s

  [16183/17668] intraday_8514.csv.gz  in=428,314,048 out=103,945,320 elapsed=217.7s

  [16184/17668] intraday_8515.csv.gz  in=428,328,516 out=103,945,320 elapsed=217.7s

  [16185/17668] intraday_8516.csv.gz  in=428,341,432 out=103,945,320 elapsed=217.7s

  [16186/17668] intraday_8517.csv.gz  in=428,354,643 out=103,945,320 elapsed=217.7s

  [16187/17668] intraday_8518.csv.gz  in=428,367,553 out=103,945,320 elapsed=217.7s

  [16188/17668] intraday_8520.csv.gz  in=428,377,042 out=103,945,320 elapsed=217.7s

  [16189/17668] intraday_8519.csv.gz  in=428,389,786 out=103,945,320 elapsed=217.7s

  [16190/17668] intraday_8521.csv.gz  in=428,400,085 out=103,945,320 elapsed=217.7s

  [16191/17668] intraday_8524.csv.gz  in=428,410,588 out=103,945,320 elapsed=217.8s

  [16192/17668] intraday_8523.csv.gz  in=428,422,857 out=103,945,320 elapsed=217.8s

  [16193/17668] intraday_8522.csv.gz  in=428,436,781 out=103,945,320 elapsed=217.8s

  [16194/17668] intraday_8525.csv.gz  in=428,447,448 out=103,945,320 elapsed=217.8s

  [16195/17668] intraday_8526.csv.gz  in=428,459,620 out=103,945,320 elapsed=217.8s

  [16196/17668] intraday_8527.csv.gz  in=428,472,274 out=103,945,320 elapsed=217.8s

  [16197/17668] intraday_8528.csv.gz  in=428,484,101 out=103,945,320 elapsed=217.8s

  [16198/17668] intraday_8529.csv.gz  in=428,497,532 out=103,945,320 elapsed=217.8s

  [16199/17668] intraday_8530.csv.gz  in=428,510,544 out=103,945,320 elapsed=217.8s

  [16200/17668] intraday_8531.csv.gz  in=428,523,985 out=103,945,320 elapsed=217.9s

  [16201/17668] intraday_8532.csv.gz  in=428,535,304 out=103,945,320 elapsed=217.9s

  [16202/17668] intraday_8533.csv.gz  in=428,546,986 out=103,945,320 elapsed=217.9s

  [16203/17668] intraday_8534.csv.gz  in=428,558,952 out=103,945,320 elapsed=217.9s

  [16204/17668] intraday_8535.csv.gz  in=428,572,363 out=103,945,320 elapsed=217.9s

  [16205/17668] intraday_8537.csv.gz  in=428,586,435 out=103,945,320 elapsed=217.9s

  [16206/17668] intraday_8538.csv.gz  in=428,597,063 out=103,945,320 elapsed=217.9s

  [16207/17668] intraday_8536.csv.gz  in=428,612,614 out=103,945,320 elapsed=217.9s

  [16208/17668] intraday_8540.csv.gz  in=428,625,247 out=103,945,320 elapsed=217.9s

  [16209/17668] intraday_8542.csv.gz  in=428,636,670 out=103,945,320 elapsed=217.9s

  [16210/17668] intraday_8541.csv.gz  in=428,648,185 out=103,945,320 elapsed=217.9s

  [16211/17668] intraday_8539.csv.gz  in=428,660,406 out=103,945,320 elapsed=217.9s

  [16212/17668] intraday_8543.csv.gz  in=428,670,656 out=103,945,320 elapsed=218.0s

  [16213/17668] intraday_8544.csv.gz  in=428,683,142 out=103,945,320 elapsed=218.0s

  [16214/17668] intraday_8546.csv.gz  in=428,694,430 out=103,945,320 elapsed=218.0s

  [16215/17668] intraday_8545.csv.gz  in=428,704,358 out=103,945,320 elapsed=218.0s

  [16216/17668] intraday_8547.csv.gz  in=428,716,241 out=103,945,320 elapsed=218.0s

  [16217/17668] intraday_8548.csv.gz  in=428,729,183 out=103,945,320 elapsed=218.0s

  [16218/17668] intraday_8549.csv.gz  in=428,740,776 out=103,945,320 elapsed=218.0s

  [16219/17668] intraday_8550.csv.gz  in=428,753,960 out=103,945,320 elapsed=218.0s

  [16220/17668] intraday_8551.csv.gz  in=428,764,371 out=103,945,320 elapsed=218.0s

  [16221/17668] intraday_8552.csv.gz  in=428,775,561 out=103,945,320 elapsed=218.0s

  [16222/17668] intraday_8553.csv.gz  in=428,788,251 out=103,945,320 elapsed=218.1s

  [16223/17668] intraday_8554.csv.gz  in=428,799,981 out=103,945,320 elapsed=218.1s

  [16224/17668] intraday_8555.csv.gz  in=428,811,296 out=103,945,320 elapsed=218.1s

  [16225/17668] intraday_8557.csv.gz  in=428,822,372 out=103,945,320 elapsed=218.1s

  [16226/17668] intraday_8558.csv.gz  in=428,836,119 out=103,945,320 elapsed=218.1s

  [16227/17668] intraday_8556.csv.gz  in=428,847,920 out=103,945,320 elapsed=218.1s

  [16228/17668] intraday_8559.csv.gz  in=428,857,867 out=103,945,320 elapsed=218.1s

  [16229/17668] intraday_8560.csv.gz  in=428,870,928 out=103,945,320 elapsed=218.1s

  [16230/17668] intraday_8561.csv.gz  in=428,884,150 out=103,945,320 elapsed=218.1s

  [16231/17668] intraday_8563.csv.gz  in=428,894,807 out=103,945,320 elapsed=218.1s

  [16232/17668] intraday_8562.csv.gz  in=428,906,553 out=103,945,320 elapsed=218.2s

  [16233/17668] intraday_8564.csv.gz  in=428,919,988 out=103,945,320 elapsed=218.2s

  [16234/17668] intraday_8565.csv.gz  in=428,931,856 out=103,945,320 elapsed=218.2s

  [16235/17668] intraday_8567.csv.gz  in=428,943,255 out=103,945,320 elapsed=218.2s

  [16236/17668] intraday_8566.csv.gz  in=428,955,886 out=103,945,320 elapsed=218.2s

  [16237/17668] intraday_8568.csv.gz  in=428,967,274 out=103,945,320 elapsed=218.2s

  [16238/17668] intraday_8569.csv.gz  in=428,978,246 out=103,945,320 elapsed=218.2s

  [16239/17668] intraday_8570.csv.gz  in=428,989,563 out=103,945,320 elapsed=218.2s

  [16240/17668] intraday_8571.csv.gz  in=429,002,301 out=103,945,320 elapsed=218.2s

  [16241/17668] intraday_8573.csv.gz  in=429,017,346 out=103,945,320 elapsed=218.2s

  [16242/17668] intraday_8572.csv.gz  in=429,029,885 out=103,945,320 elapsed=218.2s

  [16243/17668] intraday_8574.csv.gz  in=429,041,441 out=103,945,320 elapsed=218.3s

  [16244/17668] intraday_8575.csv.gz  in=429,053,013 out=103,945,320 elapsed=218.3s

  [16245/17668] intraday_8576.csv.gz  in=429,062,792 out=103,945,320 elapsed=218.3s

  [16246/17668] intraday_8577.csv.gz  in=429,075,430 out=103,945,320 elapsed=218.3s

  [16247/17668] intraday_8579.csv.gz  in=429,089,014 out=103,945,320 elapsed=218.3s

  [16248/17668] intraday_8578.csv.gz  in=429,100,712 out=103,945,320 elapsed=218.3s

  [16249/17668] intraday_8580.csv.gz  in=429,111,133 out=103,945,320 elapsed=218.3s

  [16250/17668] intraday_8582.csv.gz  in=429,122,549 out=103,945,320 elapsed=218.3s

  [16251/17668] intraday_8581.csv.gz  in=429,133,932 out=103,945,320 elapsed=218.3s

  [16252/17668] intraday_8583.csv.gz  in=429,146,838 out=103,945,320 elapsed=218.3s

  [16253/17668] intraday_8584.csv.gz  in=429,158,190 out=103,945,320 elapsed=218.3s

  [16254/17668] intraday_8585.csv.gz  in=429,168,675 out=103,945,320 elapsed=218.4s

  [16255/17668] intraday_8586.csv.gz  in=429,179,132 out=103,945,320 elapsed=218.4s

  [16256/17668] intraday_8587.csv.gz  in=429,189,631 out=103,945,320 elapsed=218.4s

  [16257/17668] intraday_8588.csv.gz  in=429,199,472 out=103,945,320 elapsed=218.4s

  [16258/17668] intraday_8589.csv.gz  in=429,213,980 out=103,945,320 elapsed=218.4s

  [16259/17668] intraday_8590.csv.gz  in=429,231,754 out=103,945,320 elapsed=218.4s

  [16260/17668] intraday_8591.csv.gz  in=429,245,492 out=103,945,320 elapsed=218.4s

  [16261/17668] intraday_8593.csv.gz  in=429,257,125 out=103,945,320 elapsed=218.4s

  [16262/17668] intraday_8592.csv.gz  in=429,267,495 out=103,945,320 elapsed=218.4s

  [16263/17668] intraday_8594.csv.gz  in=429,281,819 out=103,945,320 elapsed=218.4s

  [16264/17668] intraday_8595.csv.gz  in=429,293,404 out=103,945,320 elapsed=218.4s

  [16265/17668] intraday_8597.csv.gz  in=429,305,060 out=103,945,320 elapsed=218.5s

  [16266/17668] intraday_8596.csv.gz  in=429,320,180 out=103,945,320 elapsed=218.5s

  [16267/17668] intraday_8598.csv.gz  in=429,332,977 out=103,945,320 elapsed=218.5s

  [16268/17668] intraday_8599.csv.gz  in=429,344,822 out=103,945,320 elapsed=218.5s

  [16269/17668] intraday_8600.csv.gz  in=429,359,107 out=103,945,320 elapsed=218.5s

  [16270/17668] intraday_8601.csv.gz  in=429,372,685 out=103,945,320 elapsed=218.5s

  [16271/17668] intraday_8603.csv.gz  in=429,385,063 out=103,945,320 elapsed=218.5s

  [16272/17668] intraday_8602.csv.gz  in=429,397,850 out=103,945,320 elapsed=218.5s

  [16273/17668] intraday_8604.csv.gz  in=429,408,561 out=103,945,320 elapsed=218.5s

  [16274/17668] intraday_8605.csv.gz  in=429,421,849 out=103,945,320 elapsed=218.5s

  [16275/17668] intraday_8606.csv.gz  in=429,434,187 out=103,945,320 elapsed=218.6s

  [16276/17668] intraday_8608.csv.gz  in=429,446,613 out=103,945,320 elapsed=218.6s

  [16277/17668] intraday_8607.csv.gz  in=429,458,739 out=103,945,320 elapsed=218.6s

  [16278/17668] intraday_8609.csv.gz  in=429,473,097 out=103,945,320 elapsed=218.6s

  [16279/17668] intraday_8610.csv.gz  in=429,484,513 out=103,945,320 elapsed=218.6s

  [16280/17668] intraday_8612.csv.gz  in=429,500,487 out=103,945,320 elapsed=218.6s

  [16281/17668] intraday_8611.csv.gz  in=429,512,702 out=103,945,320 elapsed=218.6s

  [16282/17668] intraday_8613.csv.gz  in=429,524,687 out=103,945,320 elapsed=218.6s

  [16283/17668] intraday_8614.csv.gz  in=429,538,118 out=103,945,320 elapsed=218.6s

  [16284/17668] intraday_8616.csv.gz  in=429,553,760 out=103,945,320 elapsed=218.6s

  [16285/17668] intraday_8617.csv.gz  in=429,564,056 out=103,945,320 elapsed=218.7s

  [16286/17668] intraday_8618.csv.gz  in=429,576,559 out=103,945,320 elapsed=218.7s

  [16287/17668] intraday_8615.csv.gz  in=429,590,494 out=103,945,320 elapsed=218.7s

  [16288/17668] intraday_8619.csv.gz  in=429,603,297 out=103,945,320 elapsed=218.7s

  [16289/17668] intraday_8620.csv.gz  in=429,616,354 out=103,945,320 elapsed=218.7s

  [16290/17668] intraday_8621.csv.gz  in=429,630,792 out=103,945,320 elapsed=218.7s

  [16291/17668] intraday_8622.csv.gz  in=429,647,234 out=103,945,320 elapsed=218.7s

  [16292/17668] intraday_8623.csv.gz  in=429,676,218 out=103,945,320 elapsed=218.7s

  [16293/17668] intraday_8625.csv.gz  in=429,691,808 out=103,945,320 elapsed=218.7s

  [16294/17668] intraday_8624.csv.gz  in=429,705,632 out=103,945,320 elapsed=218.7s

  [16295/17668] intraday_8626.csv.gz  in=429,718,091 out=103,945,320 elapsed=218.7s

  [16296/17668] intraday_8627.csv.gz  in=429,731,504 out=103,945,320 elapsed=218.8s

  [16297/17668] intraday_8628.csv.gz  in=429,741,310 out=103,945,320 elapsed=218.8s

  [16298/17668] intraday_8630.csv.gz  in=429,751,068 out=103,945,320 elapsed=218.8s

  [16299/17668] intraday_8629.csv.gz  in=429,765,659 out=103,945,320 elapsed=218.8s

  [16300/17668] intraday_8631.csv.gz  in=429,778,532 out=103,945,320 elapsed=218.8s

  [16301/17668] intraday_8634.csv.gz  in=429,789,705 out=103,945,320 elapsed=218.8s

  [16302/17668] intraday_8633.csv.gz  in=429,804,504 out=103,945,320 elapsed=218.8s

  [16303/17668] intraday_8632.csv.gz  in=429,817,628 out=103,945,320 elapsed=218.8s

  [16304/17668] intraday_8635.csv.gz  in=429,829,724 out=103,945,320 elapsed=218.8s

  [16305/17668] intraday_8637.csv.gz  in=429,841,897 out=103,945,320 elapsed=218.9s

  [16306/17668] intraday_8636.csv.gz  in=429,853,507 out=103,945,320 elapsed=218.9s

  [16307/17668] intraday_8638.csv.gz  in=429,864,500 out=103,945,320 elapsed=218.9s

  [16308/17668] intraday_8640.csv.gz  in=429,879,141 out=103,945,320 elapsed=218.9s

  [16309/17668] intraday_8641.csv.gz  in=429,891,782 out=103,945,320 elapsed=218.9s

  [16310/17668] intraday_8639.csv.gz  in=429,906,173 out=103,945,320 elapsed=218.9s

  [16311/17668] intraday_8642.csv.gz  in=429,921,202 out=103,945,320 elapsed=218.9s

  [16312/17668] intraday_8643.csv.gz  in=429,933,891 out=103,945,320 elapsed=218.9s

  [16313/17668] intraday_8645.csv.gz  in=429,947,640 out=103,945,320 elapsed=218.9s

  [16314/17668] intraday_8644.csv.gz  in=429,959,770 out=103,945,320 elapsed=218.9s

  [16315/17668] intraday_8646.csv.gz  in=429,970,756 out=103,945,320 elapsed=219.0s

  [16316/17668] intraday_8647.csv.gz  in=429,982,062 out=103,945,320 elapsed=219.0s

  [16317/17668] intraday_8648.csv.gz  in=429,989,051 out=103,945,320 elapsed=219.0s

  [16318/17668] intraday_8649.csv.gz  in=430,000,302 out=103,945,320 elapsed=219.0s

  [16319/17668] intraday_8650.csv.gz  in=430,008,088 out=103,945,320 elapsed=219.0s

  [16320/17668] intraday_8651.csv.gz  in=430,023,368 out=103,945,320 elapsed=219.0s

  [16321/17668] intraday_8653.csv.gz  in=430,035,770 out=103,945,320 elapsed=219.0s

  [16322/17668] intraday_8652.csv.gz  in=430,051,241 out=103,945,320 elapsed=219.0s

  [16323/17668] intraday_8654.csv.gz  in=430,064,170 out=103,945,320 elapsed=219.0s

  [16324/17668] intraday_8655.csv.gz  in=430,076,537 out=103,945,320 elapsed=219.0s

  [16325/17668] intraday_8656.csv.gz  in=430,088,228 out=103,945,320 elapsed=219.0s

  [16326/17668] intraday_8657.csv.gz  in=430,103,312 out=103,945,320 elapsed=219.0s

  [16327/17668] intraday_8658.csv.gz  in=430,118,133 out=103,945,320 elapsed=219.1s

  [16328/17668] intraday_8659.csv.gz  in=430,130,011 out=103,945,320 elapsed=219.1s

  [16329/17668] intraday_8660.csv.gz  in=430,142,949 out=103,945,320 elapsed=219.1s

  [16330/17668] intraday_8662.csv.gz  in=430,157,041 out=103,945,320 elapsed=219.1s

  [16331/17668] intraday_8663.csv.gz  in=430,170,159 out=103,945,320 elapsed=219.1s

  [16332/17668] intraday_8661.csv.gz  in=430,184,352 out=103,945,320 elapsed=219.1s

  [16333/17668] intraday_8665.csv.gz  in=430,198,382 out=103,945,320 elapsed=219.1s

  [16334/17668] intraday_8664.csv.gz  in=430,212,563 out=103,945,320 elapsed=219.1s

  [16335/17668] intraday_8667.csv.gz  in=430,224,451 out=103,945,320 elapsed=219.1s

  [16336/17668] intraday_8666.csv.gz  in=430,234,012 out=103,945,320 elapsed=219.1s

  [16337/17668] intraday_8669.csv.gz  in=430,247,701 out=103,945,320 elapsed=219.2s

  [16338/17668] intraday_8668.csv.gz  in=430,261,324 out=103,945,320 elapsed=219.2s

  [16339/17668] intraday_8671.csv.gz  in=430,272,966 out=103,945,320 elapsed=219.2s

  [16340/17668] intraday_8670.csv.gz  in=430,284,648 out=103,945,320 elapsed=219.2s

  [16341/17668] intraday_8672.csv.gz  in=430,295,537 out=103,945,320 elapsed=219.2s

  [16342/17668] intraday_8673.csv.gz  in=430,310,229 out=103,945,320 elapsed=219.2s

  [16343/17668] intraday_8675.csv.gz  in=430,323,366 out=103,945,320 elapsed=219.2s

  [16344/17668] intraday_8674.csv.gz  in=430,335,657 out=103,945,320 elapsed=219.2s

  [16345/17668] intraday_8677.csv.gz  in=430,348,203 out=103,945,320 elapsed=219.2s

  [16346/17668] intraday_8676.csv.gz  in=430,361,839 out=103,945,320 elapsed=219.2s

  [16347/17668] intraday_8678.csv.gz  in=430,374,773 out=103,945,320 elapsed=219.2s

  [16348/17668] intraday_8679.csv.gz  in=430,386,220 out=103,945,320 elapsed=219.3s

  [16349/17668] intraday_8680.csv.gz  in=430,398,294 out=103,945,320 elapsed=219.3s

  [16350/17668] intraday_8681.csv.gz  in=430,411,599 out=103,945,320 elapsed=219.3s

  [16351/17668] intraday_8682.csv.gz  in=430,428,719 out=103,945,320 elapsed=219.3s

  [16352/17668] intraday_8685.csv.gz  in=430,440,907 out=103,945,320 elapsed=219.3s

  [16353/17668] intraday_8684.csv.gz  in=430,451,280 out=103,945,320 elapsed=219.3s

  [16354/17668] intraday_8683.csv.gz  in=430,465,807 out=103,945,320 elapsed=219.3s

  [16355/17668] intraday_8686.csv.gz  in=430,479,302 out=103,945,320 elapsed=219.3s

  [16356/17668] intraday_8687.csv.gz  in=430,490,473 out=103,945,320 elapsed=219.3s

  [16357/17668] intraday_8689.csv.gz  in=430,501,212 out=103,945,320 elapsed=219.3s

  [16358/17668] intraday_8688.csv.gz  in=430,513,512 out=103,945,320 elapsed=219.4s

  [16359/17668] intraday_8692.csv.gz  in=430,525,464 out=103,945,320 elapsed=219.4s

  [16360/17668] intraday_8691.csv.gz  in=430,536,105 out=103,945,320 elapsed=219.4s

  [16361/17668] intraday_8690.csv.gz  in=430,548,842 out=103,945,320 elapsed=219.4s

  [16362/17668] intraday_8693.csv.gz  in=430,560,769 out=103,945,320 elapsed=219.4s

  [16363/17668] intraday_8694.csv.gz  in=430,574,383 out=103,945,320 elapsed=219.4s

  [16364/17668] intraday_8697.csv.gz  in=430,585,251 out=103,945,320 elapsed=219.4s

  [16365/17668] intraday_8695.csv.gz  in=430,597,284 out=103,945,320 elapsed=219.4s

  [16366/17668] intraday_8696.csv.gz  in=430,611,840 out=103,945,320 elapsed=219.4s

  [16367/17668] intraday_8698.csv.gz  in=430,623,867 out=103,945,320 elapsed=219.4s

  [16368/17668] intraday_8699.csv.gz  in=430,637,218 out=103,945,320 elapsed=219.5s

  [16369/17668] intraday_8702.csv.gz  in=430,649,417 out=103,945,320 elapsed=219.5s

  [16370/17668] intraday_8700.csv.gz  in=430,660,783 out=103,945,320 elapsed=219.5s

  [16371/17668] intraday_8701.csv.gz  in=430,672,224 out=103,945,320 elapsed=219.5s

  [16372/17668] intraday_8703.csv.gz  in=430,683,062 out=103,945,320 elapsed=219.5s

  [16373/17668] intraday_8706.csv.gz  in=430,695,974 out=103,945,320 elapsed=219.5s

  [16374/17668] intraday_8704.csv.gz  in=430,711,435 out=103,945,320 elapsed=219.5s

  [16375/17668] intraday_8705.csv.gz  in=430,722,939 out=103,945,320 elapsed=219.5s

  [16376/17668] intraday_8707.csv.gz  in=430,736,139 out=103,945,320 elapsed=219.5s

  [16377/17668] intraday_8710.csv.gz  in=430,749,912 out=103,945,320 elapsed=219.5s

  [16378/17668] intraday_8709.csv.gz  in=430,760,615 out=103,945,320 elapsed=219.5s

  [16379/17668] intraday_8708.csv.gz  in=430,772,428 out=103,945,320 elapsed=219.5s

  [16380/17668] intraday_8711.csv.gz  in=430,785,737 out=103,945,320 elapsed=219.6s

  [16381/17668] intraday_8712.csv.gz  in=430,797,224 out=103,945,320 elapsed=219.6s

  [16382/17668] intraday_8714.csv.gz  in=430,808,602 out=103,945,320 elapsed=219.6s

  [16383/17668] intraday_8713.csv.gz  in=430,821,918 out=103,945,320 elapsed=219.6s

  [16384/17668] intraday_8715.csv.gz  in=430,834,581 out=103,945,320 elapsed=219.6s

  [16385/17668] intraday_8716.csv.gz  in=430,845,241 out=103,945,320 elapsed=219.6s

  [16386/17668] intraday_8718.csv.gz  in=430,858,212 out=103,945,320 elapsed=219.6s

  [16387/17668] intraday_8719.csv.gz  in=430,875,967 out=103,945,320 elapsed=219.6s

  [16388/17668] intraday_8717.csv.gz  in=430,891,077 out=103,945,320 elapsed=219.6s

  [16389/17668] intraday_8721.csv.gz  in=430,902,502 out=103,945,320 elapsed=219.7s

  [16390/17668] intraday_8720.csv.gz  in=430,914,313 out=103,945,320 elapsed=219.7s

  [16391/17668] intraday_8722.csv.gz  in=430,924,893 out=103,945,320 elapsed=219.7s

  [16392/17668] intraday_8723.csv.gz  in=430,937,959 out=103,945,320 elapsed=219.7s

  [16393/17668] intraday_8724.csv.gz  in=430,950,361 out=103,945,320 elapsed=219.7s

  [16394/17668] intraday_8726.csv.gz  in=430,961,181 out=103,945,320 elapsed=219.7s

  [16395/17668] intraday_8725.csv.gz  in=430,975,285 out=103,945,320 elapsed=219.7s

  [16396/17668] intraday_8727.csv.gz  in=430,987,899 out=103,945,320 elapsed=219.7s

  [16397/17668] intraday_8728.csv.gz  in=430,999,062 out=103,945,320 elapsed=219.7s

  [16398/17668] intraday_8729.csv.gz  in=431,013,088 out=103,945,320 elapsed=219.7s

  [16399/17668] intraday_8732.csv.gz  in=431,024,290 out=103,945,320 elapsed=219.7s

  [16400/17668] intraday_8731.csv.gz  in=431,035,960 out=103,945,320 elapsed=219.8s

  [16401/17668] intraday_8730.csv.gz  in=431,046,313 out=103,945,320 elapsed=219.8s

  [16402/17668] intraday_8733.csv.gz  in=431,056,715 out=103,945,320 elapsed=219.8s

  [16403/17668] intraday_8737.csv.gz  in=431,069,957 out=103,945,320 elapsed=219.8s

  [16404/17668] intraday_8736.csv.gz  in=431,086,044 out=103,945,320 elapsed=219.8s

  [16405/17668] intraday_8734.csv.gz  in=431,097,142 out=103,945,320 elapsed=219.8s

  [16406/17668] intraday_8735.csv.gz  in=431,113,243 out=103,945,320 elapsed=219.8s

  [16407/17668] intraday_8738.csv.gz  in=431,124,580 out=103,945,320 elapsed=219.8s

  [16408/17668] intraday_8739.csv.gz  in=431,137,216 out=103,945,320 elapsed=219.8s

  [16409/17668] intraday_8741.csv.gz  in=431,149,290 out=103,945,320 elapsed=219.9s

  [16410/17668] intraday_8740.csv.gz  in=431,163,056 out=103,945,320 elapsed=219.9s

  [16411/17668] intraday_8743.csv.gz  in=431,175,240 out=103,945,320 elapsed=219.9s

  [16412/17668] intraday_8742.csv.gz  in=431,190,223 out=103,945,320 elapsed=219.9s

  [16413/17668] intraday_8744.csv.gz  in=431,204,835 out=103,945,320 elapsed=219.9s

  [16414/17668] intraday_8745.csv.gz  in=431,217,996 out=103,945,320 elapsed=219.9s

  [16415/17668] intraday_8746.csv.gz  in=431,231,018 out=103,945,320 elapsed=219.9s

  [16416/17668] intraday_8747.csv.gz  in=431,244,641 out=103,945,320 elapsed=219.9s

  [16417/17668] intraday_8748.csv.gz  in=431,256,743 out=103,945,320 elapsed=219.9s

  [16418/17668] intraday_8749.csv.gz  in=431,275,020 out=103,945,320 elapsed=219.9s

  [16419/17668] intraday_8750.csv.gz  in=431,287,043 out=103,945,320 elapsed=219.9s

  [16420/17668] intraday_8751.csv.gz  in=431,299,941 out=103,945,320 elapsed=220.0s

  [16421/17668] intraday_8752.csv.gz  in=431,311,383 out=103,945,320 elapsed=220.0s

  [16422/17668] intraday_8753.csv.gz  in=431,325,091 out=103,945,320 elapsed=220.0s

  [16423/17668] intraday_8754.csv.gz  in=431,337,399 out=103,945,320 elapsed=220.0s

  [16424/17668] intraday_8755.csv.gz  in=431,354,702 out=103,945,320 elapsed=220.0s

  [16425/17668] intraday_8757.csv.gz  in=431,367,295 out=103,945,320 elapsed=220.0s

  [16426/17668] intraday_8756.csv.gz  in=431,378,885 out=103,945,320 elapsed=220.0s

  [16427/17668] intraday_8758.csv.gz  in=431,394,693 out=103,945,320 elapsed=220.0s

  [16428/17668] intraday_8759.csv.gz  in=431,407,272 out=103,945,320 elapsed=220.0s

  [16429/17668] intraday_8760.csv.gz  in=431,419,824 out=103,945,320 elapsed=220.1s

  [16430/17668] intraday_8763.csv.gz  in=431,430,743 out=103,945,320 elapsed=220.1s

  [16431/17668] intraday_8762.csv.gz  in=431,445,969 out=103,945,320 elapsed=220.1s

  [16432/17668] intraday_8761.csv.gz  in=431,461,099 out=103,945,320 elapsed=220.1s

  [16433/17668] intraday_8765.csv.gz  in=431,474,011 out=103,945,320 elapsed=220.1s

  [16434/17668] intraday_8766.csv.gz  in=431,486,474 out=103,945,320 elapsed=220.1s

  [16435/17668] intraday_8764.csv.gz  in=431,499,593 out=103,945,320 elapsed=220.1s

  [16436/17668] intraday_8767.csv.gz  in=431,514,908 out=103,945,320 elapsed=220.1s

  [16437/17668] intraday_8768.csv.gz  in=431,530,516 out=103,945,320 elapsed=220.1s

  [16438/17668] intraday_8769.csv.gz  in=431,552,108 out=103,945,320 elapsed=220.1s

  [16439/17668] intraday_8770.csv.gz  in=431,567,465 out=103,945,320 elapsed=220.1s

  [16440/17668] intraday_8771.csv.gz  in=431,581,835 out=103,945,320 elapsed=220.2s

  [16441/17668] intraday_8773.csv.gz  in=431,594,287 out=103,945,320 elapsed=220.2s

  [16442/17668] intraday_8772.csv.gz  in=431,606,890 out=103,945,320 elapsed=220.2s

  [16443/17668] intraday_8774.csv.gz  in=431,617,523 out=103,945,320 elapsed=220.2s

  [16444/17668] intraday_8775.csv.gz  in=431,632,147 out=103,945,320 elapsed=220.2s

  [16445/17668] intraday_8776.csv.gz  in=431,643,194 out=103,945,320 elapsed=220.2s

  [16446/17668] intraday_8777.csv.gz  in=431,655,992 out=103,945,320 elapsed=220.2s

  [16447/17668] intraday_8778.csv.gz  in=431,669,855 out=103,945,320 elapsed=220.2s

  [16448/17668] intraday_8779.csv.gz  in=431,684,389 out=103,945,320 elapsed=220.2s

  [16449/17668] intraday_8780.csv.gz  in=431,695,552 out=103,945,320 elapsed=220.2s

  [16450/17668] intraday_8781.csv.gz  in=431,707,398 out=103,945,320 elapsed=220.3s

  [16451/17668] intraday_8782.csv.gz  in=431,719,372 out=103,945,320 elapsed=220.3s

  [16452/17668] intraday_8783.csv.gz  in=431,731,627 out=103,945,320 elapsed=220.3s

  [16453/17668] intraday_8784.csv.gz  in=431,743,215 out=103,945,320 elapsed=220.3s

  [16454/17668] intraday_8787.csv.gz  in=431,756,913 out=103,945,320 elapsed=220.3s

  [16455/17668] intraday_8786.csv.gz  in=431,771,793 out=103,945,320 elapsed=220.3s

  [16456/17668] intraday_8789.csv.gz  in=431,784,065 out=103,945,320 elapsed=220.3s

  [16457/17668] intraday_8785.csv.gz  in=431,798,150 out=103,945,320 elapsed=220.3s

  [16458/17668] intraday_8788.csv.gz  in=431,812,901 out=103,945,320 elapsed=220.3s

  [16459/17668] intraday_8790.csv.gz  in=431,824,770 out=103,945,320 elapsed=220.4s

  [16460/17668] intraday_8792.csv.gz  in=431,836,013 out=103,945,320 elapsed=220.4s

  [16461/17668] intraday_8791.csv.gz  in=431,850,242 out=103,945,320 elapsed=220.4s

  [16462/17668] intraday_8794.csv.gz  in=431,856,847 out=103,945,320 elapsed=220.4s

  [16463/17668] intraday_8793.csv.gz  in=431,868,480 out=103,945,320 elapsed=220.4s

  [16464/17668] intraday_8795.csv.gz  in=431,881,415 out=103,945,320 elapsed=220.4s

  [16465/17668] intraday_8796.csv.gz  in=431,888,073 out=103,945,320 elapsed=220.4s

  [16466/17668] intraday_8797.csv.gz  in=431,903,465 out=103,945,320 elapsed=220.4s

  [16467/17668] intraday_8798.csv.gz  in=431,915,331 out=103,945,320 elapsed=220.4s

  [16468/17668] intraday_8799.csv.gz  in=431,929,669 out=103,945,320 elapsed=220.4s

  [16469/17668] intraday_8800.csv.gz  in=431,940,067 out=103,945,320 elapsed=220.4s

  [16470/17668] intraday_8803.csv.gz  in=431,954,250 out=103,945,320 elapsed=220.5s

  [16471/17668] intraday_8802.csv.gz  in=431,969,809 out=103,945,320 elapsed=220.5s

  [16472/17668] intraday_8801.csv.gz  in=431,982,044 out=103,945,320 elapsed=220.5s

  [16473/17668] intraday_8804.csv.gz  in=431,993,643 out=103,945,320 elapsed=220.5s

  [16474/17668] intraday_8806.csv.gz  in=432,008,375 out=103,945,320 elapsed=220.5s

  [16475/17668] intraday_8807.csv.gz  in=432,022,640 out=103,945,320 elapsed=220.5s

  [16476/17668] intraday_8805.csv.gz  in=432,035,122 out=103,945,320 elapsed=220.5s

  [16477/17668] intraday_8808.csv.gz  in=432,049,048 out=103,945,320 elapsed=220.5s

  [16478/17668] intraday_8811.csv.gz  in=432,058,942 out=103,945,320 elapsed=220.5s

  [16479/17668] intraday_8809.csv.gz  in=432,072,416 out=103,945,320 elapsed=220.5s

  [16480/17668] intraday_8812.csv.gz  in=432,084,254 out=103,945,320 elapsed=220.5s

  [16481/17668] intraday_8810.csv.gz  in=432,098,569 out=103,945,320 elapsed=220.5s

  [16482/17668] intraday_8813.csv.gz  in=432,112,483 out=103,945,320 elapsed=220.6s

  [16483/17668] intraday_8815.csv.gz  in=432,124,744 out=103,945,320 elapsed=220.6s

  [16484/17668] intraday_8816.csv.gz  in=432,135,940 out=103,945,320 elapsed=220.6s

  [16485/17668] intraday_8814.csv.gz  in=432,148,185 out=103,945,320 elapsed=220.6s

  [16486/17668] intraday_8817.csv.gz  in=432,160,318 out=103,945,320 elapsed=220.6s

  [16487/17668] intraday_8819.csv.gz  in=432,173,092 out=103,945,320 elapsed=220.6s

  [16488/17668] intraday_8818.csv.gz  in=432,187,229 out=103,945,320 elapsed=220.6s

  [16489/17668] intraday_8820.csv.gz  in=432,200,865 out=103,945,320 elapsed=220.6s

  [16490/17668] intraday_8823.csv.gz  in=432,213,259 out=103,945,320 elapsed=220.6s

  [16491/17668] intraday_8822.csv.gz  in=432,226,563 out=103,945,320 elapsed=220.6s

  [16492/17668] intraday_8821.csv.gz  in=432,239,986 out=103,945,320 elapsed=220.7s

  [16493/17668] intraday_8824.csv.gz  in=432,251,976 out=103,945,320 elapsed=220.7s

  [16494/17668] intraday_8826.csv.gz  in=432,266,028 out=103,945,320 elapsed=220.7s

  [16495/17668] intraday_8825.csv.gz  in=432,283,000 out=103,945,320 elapsed=220.7s

  [16496/17668] intraday_8827.csv.gz  in=432,298,810 out=103,945,320 elapsed=220.7s

  [16497/17668] intraday_8828.csv.gz  in=432,312,352 out=103,945,320 elapsed=220.7s

  [16498/17668] intraday_8829.csv.gz  in=432,323,792 out=103,945,320 elapsed=220.7s

  [16499/17668] intraday_8830.csv.gz  in=432,336,227 out=103,945,320 elapsed=220.7s

  [16500/17668] intraday_8831.csv.gz  in=432,349,146 out=103,945,320 elapsed=220.7s

  [16501/17668] intraday_8832.csv.gz  in=432,360,107 out=103,945,320 elapsed=220.7s

  [16502/17668] intraday_8834.csv.gz  in=432,370,785 out=103,945,320 elapsed=220.8s

  [16503/17668] intraday_8836.csv.gz  in=432,381,838 out=103,945,320 elapsed=220.8s

  [16504/17668] intraday_8835.csv.gz  in=432,394,104 out=103,945,320 elapsed=220.8s

  [16505/17668] intraday_8833.csv.gz  in=432,406,971 out=103,945,320 elapsed=220.8s

  [16506/17668] intraday_8837.csv.gz  in=432,418,798 out=103,945,320 elapsed=220.8s

  [16507/17668] intraday_8838.csv.gz  in=432,431,148 out=103,945,320 elapsed=220.8s

  [16508/17668] intraday_8840.csv.gz  in=432,443,245 out=103,945,320 elapsed=220.8s

  [16509/17668] intraday_8839.csv.gz  in=432,456,988 out=103,945,320 elapsed=220.8s

  [16510/17668] intraday_8842.csv.gz  in=432,468,143 out=103,945,320 elapsed=220.8s

  [16511/17668] intraday_8841.csv.gz  in=432,481,921 out=103,945,320 elapsed=220.8s

  [16512/17668] intraday_8843.csv.gz  in=432,493,034 out=103,945,320 elapsed=220.8s

  [16513/17668] intraday_8845.csv.gz  in=432,503,545 out=103,945,320 elapsed=220.8s

  [16514/17668] intraday_8844.csv.gz  in=432,517,179 out=103,945,320 elapsed=220.8s

  [16515/17668] intraday_8846.csv.gz  in=432,528,933 out=103,945,320 elapsed=220.9s

  [16516/17668] intraday_8847.csv.gz  in=432,540,970 out=103,945,320 elapsed=220.9s

  [16517/17668] intraday_8848.csv.gz  in=432,552,387 out=103,945,320 elapsed=220.9s

  [16518/17668] intraday_8849.csv.gz  in=432,568,269 out=103,945,320 elapsed=220.9s

  [16519/17668] intraday_8850.csv.gz  in=432,581,693 out=103,945,320 elapsed=220.9s

  [16520/17668] intraday_8851.csv.gz  in=432,595,080 out=103,945,320 elapsed=220.9s

  [16521/17668] intraday_8852.csv.gz  in=432,614,615 out=103,945,320 elapsed=220.9s

  [16522/17668] intraday_8853.csv.gz  in=432,628,693 out=103,945,320 elapsed=220.9s

  [16523/17668] intraday_8854.csv.gz  in=432,639,825 out=103,945,320 elapsed=220.9s

  [16524/17668] intraday_8855.csv.gz  in=432,652,033 out=103,945,320 elapsed=220.9s

  [16525/17668] intraday_8856.csv.gz  in=432,664,731 out=103,945,320 elapsed=221.0s

  [16526/17668] intraday_8857.csv.gz  in=432,677,165 out=103,945,320 elapsed=221.0s

  [16527/17668] intraday_8858.csv.gz  in=432,694,126 out=103,945,320 elapsed=221.0s

  [16528/17668] intraday_8859.csv.gz  in=432,705,186 out=103,945,320 elapsed=221.0s

  [16529/17668] intraday_8860.csv.gz  in=432,717,948 out=103,945,320 elapsed=221.0s

  [16530/17668] intraday_8861.csv.gz  in=432,728,819 out=103,945,320 elapsed=221.0s

  [16531/17668] intraday_8862.csv.gz  in=432,744,196 out=103,945,320 elapsed=221.0s

  [16532/17668] intraday_8863.csv.gz  in=432,756,255 out=103,945,320 elapsed=221.0s

  [16533/17668] intraday_8864.csv.gz  in=432,770,238 out=103,945,320 elapsed=221.0s

  [16534/17668] intraday_8865.csv.gz  in=432,783,868 out=103,945,320 elapsed=221.0s

  [16535/17668] intraday_8866.csv.gz  in=432,795,015 out=103,945,320 elapsed=221.0s

  [16536/17668] intraday_8867.csv.gz  in=432,804,292 out=103,945,320 elapsed=221.1s

  [16537/17668] intraday_8868.csv.gz  in=432,816,288 out=103,945,320 elapsed=221.1s

  [16538/17668] intraday_8870.csv.gz  in=432,830,095 out=103,945,320 elapsed=221.1s

  [16539/17668] intraday_8869.csv.gz  in=432,843,185 out=103,945,320 elapsed=221.1s

  [16540/17668] intraday_8871.csv.gz  in=432,857,718 out=103,945,320 elapsed=221.1s

  [16541/17668] intraday_8872.csv.gz  in=432,870,456 out=103,945,320 elapsed=221.1s

  [16542/17668] intraday_8873.csv.gz  in=432,883,667 out=103,945,320 elapsed=221.1s

  [16543/17668] intraday_8874.csv.gz  in=432,897,324 out=103,945,320 elapsed=221.1s

  [16544/17668] intraday_8875.csv.gz  in=432,908,034 out=103,945,320 elapsed=221.1s

  [16545/17668] intraday_8876.csv.gz  in=432,919,749 out=103,945,320 elapsed=221.1s

  [16546/17668] intraday_8877.csv.gz  in=432,935,789 out=103,945,320 elapsed=221.1s

  [16547/17668] intraday_8878.csv.gz  in=432,947,109 out=103,945,320 elapsed=221.1s

  [16548/17668] intraday_8879.csv.gz  in=432,958,502 out=103,945,320 elapsed=221.2s

  [16549/17668] intraday_8881.csv.gz  in=432,976,846 out=103,945,320 elapsed=221.2s

  [16550/17668] intraday_8880.csv.gz  in=432,990,420 out=103,945,320 elapsed=221.2s

  [16551/17668] intraday_8882.csv.gz  in=433,003,286 out=103,945,320 elapsed=221.2s

  [16552/17668] intraday_8883.csv.gz  in=433,014,936 out=103,945,320 elapsed=221.2s

  [16553/17668] intraday_8884.csv.gz  in=433,027,471 out=103,945,320 elapsed=221.2s

  [16554/17668] intraday_8885.csv.gz  in=433,042,026 out=103,945,320 elapsed=221.2s

  [16555/17668] intraday_8886.csv.gz  in=433,054,563 out=103,945,320 elapsed=221.2s

  [16556/17668] intraday_8887.csv.gz  in=433,069,798 out=103,945,320 elapsed=221.2s

  [16557/17668] intraday_8888.csv.gz  in=433,083,426 out=103,945,320 elapsed=221.3s

  [16558/17668] intraday_8889.csv.gz  in=433,096,292 out=103,945,320 elapsed=221.3s

  [16559/17668] intraday_8890.csv.gz  in=433,108,928 out=103,945,320 elapsed=221.3s

  [16560/17668] intraday_8891.csv.gz  in=433,122,277 out=103,945,320 elapsed=221.3s

  [16561/17668] intraday_8892.csv.gz  in=433,136,682 out=103,945,320 elapsed=221.3s

  [16562/17668] intraday_8894.csv.gz  in=433,150,322 out=103,945,320 elapsed=221.3s

  [16563/17668] intraday_8895.csv.gz  in=433,161,427 out=103,945,320 elapsed=221.3s

  [16564/17668] intraday_8893.csv.gz  in=433,174,777 out=103,945,320 elapsed=221.3s

  [16565/17668] intraday_8896.csv.gz  in=433,199,751 out=103,945,320 elapsed=221.3s

  [16566/17668] intraday_8897.csv.gz  in=433,213,110 out=103,945,320 elapsed=221.4s

  [16567/17668] intraday_8898.csv.gz  in=433,224,532 out=103,945,320 elapsed=221.4s

  [16568/17668] intraday_8899.csv.gz  in=433,239,330 out=103,945,320 elapsed=221.4s

  [16569/17668] intraday_8900.csv.gz  in=433,252,705 out=103,945,320 elapsed=221.4s

  [16570/17668] intraday_8902.csv.gz  in=433,264,944 out=103,945,320 elapsed=221.4s

  [16571/17668] intraday_8901.csv.gz  in=433,278,883 out=103,945,320 elapsed=221.4s

  [16572/17668] intraday_8903.csv.gz  in=433,292,484 out=103,945,320 elapsed=221.4s

  [16573/17668] intraday_8904.csv.gz  in=433,305,715 out=103,945,320 elapsed=221.4s

  [16574/17668] intraday_8905.csv.gz  in=433,318,107 out=103,945,320 elapsed=221.4s

  [16575/17668] intraday_8906.csv.gz  in=433,333,593 out=103,945,320 elapsed=221.4s

  [16576/17668] intraday_8907.csv.gz  in=433,348,573 out=103,945,320 elapsed=221.4s

  [16577/17668] intraday_8908.csv.gz  in=433,360,352 out=103,945,320 elapsed=221.8s

  [16578/17668] intraday_8910.csv.gz  in=433,374,851 out=103,945,320 elapsed=221.8s

  [16579/17668] intraday_8909.csv.gz  in=433,387,031 out=103,945,320 elapsed=221.8s

  [16580/17668] intraday_8911.csv.gz  in=433,398,382 out=103,945,320 elapsed=221.8s

  [16581/17668] intraday_8912.csv.gz  in=433,413,623 out=103,945,320 elapsed=221.8s

  [16582/17668] intraday_8913.csv.gz  in=433,429,893 out=103,945,320 elapsed=221.8s

  [16583/17668] intraday_8915.csv.gz  in=433,443,444 out=103,945,320 elapsed=221.8s

  [16584/17668] intraday_8914.csv.gz  in=433,466,203 out=103,945,320 elapsed=221.8s

  [16585/17668] intraday_8916.csv.gz  in=433,482,937 out=103,945,320 elapsed=221.9s

  [16586/17668] intraday_8918.csv.gz  in=433,496,298 out=103,945,320 elapsed=221.9s

  [16587/17668] intraday_8917.csv.gz  in=433,508,147 out=103,945,320 elapsed=221.9s

  [16588/17668] intraday_8919.csv.gz  in=433,519,458 out=103,945,320 elapsed=221.9s

  [16589/17668] intraday_8921.csv.gz  in=433,530,615 out=103,945,320 elapsed=221.9s

  [16590/17668] intraday_8920.csv.gz  in=433,543,928 out=103,945,320 elapsed=221.9s

  [16591/17668] intraday_8923.csv.gz  in=433,556,354 out=103,945,320 elapsed=221.9s

  [16592/17668] intraday_8922.csv.gz  in=433,570,067 out=103,945,320 elapsed=221.9s

  [16593/17668] intraday_8926.csv.gz  in=433,582,613 out=103,945,320 elapsed=221.9s

  [16594/17668] intraday_8927.csv.gz  in=433,593,510 out=103,945,320 elapsed=221.9s

  [16595/17668] intraday_8924.csv.gz  in=433,609,510 out=103,945,320 elapsed=221.9s

  [16596/17668] intraday_8925.csv.gz  in=433,620,459 out=103,945,320 elapsed=221.9s

  [16597/17668] intraday_8928.csv.gz  in=433,633,626 out=103,945,320 elapsed=222.0s

  [16598/17668] intraday_8929.csv.gz  in=433,645,600 out=103,945,320 elapsed=222.0s

  [16599/17668] intraday_8931.csv.gz  in=433,660,099 out=103,945,320 elapsed=222.0s

  [16600/17668] intraday_8930.csv.gz  in=433,674,256 out=103,945,320 elapsed=222.0s

  [16601/17668] intraday_8932.csv.gz  in=433,687,600 out=103,945,320 elapsed=222.0s

  [16602/17668] intraday_8934.csv.gz  in=433,700,496 out=103,945,320 elapsed=222.0s

  [16603/17668] intraday_8933.csv.gz  in=433,715,039 out=103,945,320 elapsed=222.0s

  [16604/17668] intraday_8935.csv.gz  in=433,726,872 out=103,945,320 elapsed=222.0s

  [16605/17668] intraday_8939.csv.gz  in=433,734,278 out=103,945,320 elapsed=222.1s

  [16606/17668] intraday_8937.csv.gz  in=433,744,884 out=103,945,320 elapsed=222.1s

  [16607/17668] intraday_8936.csv.gz  in=433,757,981 out=103,945,320 elapsed=222.1s

  [16608/17668] intraday_8938.csv.gz  in=433,771,731 out=103,945,320 elapsed=222.1s

  [16609/17668] intraday_8940.csv.gz  in=433,782,532 out=103,945,320 elapsed=222.1s

  [16610/17668] intraday_8942.csv.gz  in=433,785,191 out=103,945,320 elapsed=222.1s

  [16611/17668] intraday_8943.csv.gz  in=433,787,488 out=103,945,320 elapsed=222.1s

  [16612/17668] intraday_8944.csv.gz  in=433,788,361 out=103,945,320 elapsed=222.1s

  [16613/17668] intraday_8941.csv.gz  in=433,798,932 out=103,945,320 elapsed=222.1s

  [16614/17668] intraday_8945.csv.gz  in=433,799,220 out=103,945,320 elapsed=222.1s

  [16615/17668] intraday_8946.csv.gz  in=433,799,391 out=103,945,320 elapsed=222.1s

  [16616/17668] intraday_8948.csv.gz  in=433,799,468 out=103,945,320 elapsed=222.1s

  [16617/17668] intraday_8947.csv.gz  in=433,805,979 out=103,945,320 elapsed=222.1s

  [16618/17668] intraday_8949.csv.gz  in=433,806,048 out=103,945,320 elapsed=222.1s

  [16619/17668] intraday_8952.csv.gz  in=433,806,388 out=103,945,320 elapsed=222.2s

  [16620/17668] intraday_8953.csv.gz  in=433,806,629 out=103,945,320 elapsed=222.2s

  [16621/17668] intraday_8950.csv.gz  in=433,807,069 out=103,945,320 elapsed=222.2s

  [16622/17668] intraday_8951.csv.gz  in=433,821,026 out=103,945,320 elapsed=222.2s

  [16623/17668] intraday_8955.csv.gz  in=433,821,870 out=103,945,320 elapsed=222.2s

  [16624/17668] intraday_8954.csv.gz  in=433,821,880 out=103,945,320 elapsed=222.2s

  [16625/17668] intraday_8956.csv.gz  in=433,821,948 out=103,945,320 elapsed=222.2s

  [16626/17668] intraday_8957.csv.gz  in=433,821,967 out=103,945,320 elapsed=222.2s

  [16627/17668] intraday_8958.csv.gz  in=433,822,005 out=103,945,320 elapsed=222.2s

  [16628/17668] intraday_8959.csv.gz  in=433,824,030 out=103,945,320 elapsed=222.2s

  [16629/17668] intraday_8960.csv.gz  in=433,827,560 out=103,945,320 elapsed=222.2s

  [16630/17668] intraday_8961.csv.gz  in=433,828,071 out=103,945,320 elapsed=222.2s

  [16631/17668] intraday_8962.csv.gz  in=433,832,836 out=103,945,320 elapsed=222.2s

  [16632/17668] intraday_8964.csv.gz  in=433,832,849 out=103,945,320 elapsed=222.2s

  [16633/17668] intraday_8963.csv.gz  in=433,833,054 out=103,945,320 elapsed=222.2s

  [16634/17668] intraday_8966.csv.gz  in=433,833,359 out=103,945,320 elapsed=222.3s

  [16635/17668] intraday_8967.csv.gz  in=433,836,465 out=103,945,320 elapsed=222.3s

  [16636/17668] intraday_8965.csv.gz  in=433,840,227 out=103,945,320 elapsed=222.3s

  [16637/17668] intraday_8968.csv.gz  in=433,840,490 out=103,945,320 elapsed=222.3s

  [16638/17668] intraday_8969.csv.gz  in=433,840,521 out=103,945,320 elapsed=222.3s

  [16639/17668] intraday_8972.csv.gz  in=433,842,419 out=103,945,320 elapsed=222.3s

  [16640/17668] intraday_8970.csv.gz  in=433,847,202 out=103,945,320 elapsed=222.3s

  [16641/17668] intraday_8973.csv.gz  in=433,862,543 out=103,945,320 elapsed=222.3s

  [16642/17668] intraday_8971.csv.gz  in=433,893,611 out=103,945,320 elapsed=222.3s

  [16643/17668] intraday_8974.csv.gz  in=433,905,354 out=103,945,320 elapsed=222.3s

  [16644/17668] intraday_8975.csv.gz  in=433,919,151 out=103,945,320 elapsed=222.3s

  [16645/17668] intraday_8976.csv.gz  in=433,929,833 out=103,945,320 elapsed=222.3s

  [16646/17668] intraday_8977.csv.gz  in=433,943,167 out=103,945,320 elapsed=222.4s

  [16647/17668] intraday_8978.csv.gz  in=433,957,329 out=103,945,320 elapsed=222.4s

  [16648/17668] intraday_8980.csv.gz  in=433,969,855 out=103,945,320 elapsed=222.4s

  [16649/17668] intraday_8979.csv.gz  in=433,984,986 out=103,945,320 elapsed=222.4s

  [16650/17668] intraday_8981.csv.gz  in=433,997,731 out=103,945,320 elapsed=222.4s

  [16651/17668] intraday_8982.csv.gz  in=434,011,563 out=103,945,320 elapsed=222.4s

  [16652/17668] intraday_8984.csv.gz  in=434,024,661 out=103,945,320 elapsed=222.4s

  [16653/17668] intraday_8983.csv.gz  in=434,039,155 out=103,945,320 elapsed=222.4s

  [16654/17668] intraday_8985.csv.gz  in=434,054,869 out=103,945,320 elapsed=222.4s

  [16655/17668] intraday_8986.csv.gz  in=434,066,863 out=103,945,320 elapsed=222.4s

  [16656/17668] intraday_8989.csv.gz  in=434,080,150 out=103,945,320 elapsed=222.5s

  [16657/17668] intraday_8988.csv.gz  in=434,091,840 out=103,945,320 elapsed=222.5s

  [16658/17668] intraday_8990.csv.gz  in=434,104,836 out=103,945,320 elapsed=222.5s

  [16659/17668] intraday_8987.csv.gz  in=434,114,685 out=103,945,320 elapsed=222.5s

  [16660/17668] intraday_8991.csv.gz  in=434,125,302 out=103,945,320 elapsed=222.5s

  [16661/17668] intraday_8992.csv.gz  in=434,136,992 out=103,945,320 elapsed=222.5s

  [16662/17668] intraday_8993.csv.gz  in=434,148,416 out=103,945,320 elapsed=222.5s

  [16663/17668] intraday_8994.csv.gz  in=434,161,370 out=103,945,320 elapsed=222.5s

  [16664/17668] intraday_8995.csv.gz  in=434,175,174 out=103,945,320 elapsed=222.5s

  [16665/17668] intraday_8998.csv.gz  in=434,188,143 out=103,945,320 elapsed=222.5s

  [16666/17668] intraday_8996.csv.gz  in=434,200,881 out=103,945,320 elapsed=222.5s

  [16667/17668] intraday_8999.csv.gz  in=434,212,664 out=103,945,320 elapsed=222.6s

  [16668/17668] intraday_9000.csv.gz  in=434,224,318 out=103,945,320 elapsed=222.6s

  [16669/17668] intraday_8997.csv.gz  in=434,238,512 out=103,945,320 elapsed=222.6s

  [16670/17668] intraday_9001.csv.gz  in=434,250,389 out=103,945,320 elapsed=222.6s

  [16671/17668] intraday_9002.csv.gz  in=434,263,063 out=103,945,320 elapsed=222.6s

  [16672/17668] intraday_9003.csv.gz  in=434,279,203 out=103,945,320 elapsed=222.6s

  [16673/17668] intraday_9004.csv.gz  in=434,292,460 out=103,945,320 elapsed=222.6s

  [16674/17668] intraday_9005.csv.gz  in=434,303,389 out=103,945,320 elapsed=222.6s

  [16675/17668] intraday_9007.csv.gz  in=434,315,865 out=103,945,320 elapsed=222.6s

  [16676/17668] intraday_9006.csv.gz  in=434,327,409 out=103,945,320 elapsed=222.7s

  [16677/17668] intraday_9009.csv.gz  in=434,339,462 out=103,945,320 elapsed=222.7s

  [16678/17668] intraday_9008.csv.gz  in=434,351,905 out=103,945,320 elapsed=222.7s

  [16679/17668] intraday_9011.csv.gz  in=434,363,389 out=103,945,320 elapsed=222.7s

  [16680/17668] intraday_9010.csv.gz  in=434,374,520 out=103,945,320 elapsed=222.7s

  [16681/17668] intraday_9013.csv.gz  in=434,386,739 out=103,945,320 elapsed=222.7s

  [16682/17668] intraday_9012.csv.gz  in=434,397,595 out=103,945,320 elapsed=222.7s

  [16683/17668] intraday_9014.csv.gz  in=434,409,933 out=103,945,320 elapsed=222.7s

  [16684/17668] intraday_9016.csv.gz  in=434,422,680 out=103,945,320 elapsed=222.7s

  [16685/17668] intraday_9015.csv.gz  in=434,434,581 out=103,945,320 elapsed=222.7s

  [16686/17668] intraday_9017.csv.gz  in=434,448,969 out=103,945,320 elapsed=222.7s

  [16687/17668] intraday_9018.csv.gz  in=434,459,367 out=103,945,320 elapsed=222.8s

  [16688/17668] intraday_9019.csv.gz  in=434,471,441 out=103,945,320 elapsed=222.8s

  [16689/17668] intraday_9021.csv.gz  in=434,482,891 out=103,945,320 elapsed=222.8s

  [16690/17668] intraday_9022.csv.gz  in=434,495,129 out=103,945,320 elapsed=222.8s

  [16691/17668] intraday_9020.csv.gz  in=434,507,648 out=103,945,320 elapsed=222.8s

  [16692/17668] intraday_9023.csv.gz  in=434,520,764 out=103,945,320 elapsed=222.8s

  [16693/17668] intraday_9025.csv.gz  in=434,536,249 out=103,945,320 elapsed=222.8s

  [16694/17668] intraday_9024.csv.gz  in=434,546,272 out=103,945,320 elapsed=222.8s

  [16695/17668] intraday_9026.csv.gz  in=434,557,645 out=103,945,320 elapsed=222.8s

  [16696/17668] intraday_9027.csv.gz  in=434,570,474 out=103,945,320 elapsed=222.9s

  [16697/17668] intraday_9030.csv.gz  in=434,581,293 out=103,945,320 elapsed=222.9s

  [16698/17668] intraday_9028.csv.gz  in=434,595,598 out=103,945,320 elapsed=222.9s

  [16699/17668] intraday_9029.csv.gz  in=434,607,845 out=103,945,320 elapsed=222.9s

  [16700/17668] intraday_9031.csv.gz  in=434,618,522 out=103,945,320 elapsed=222.9s

  [16701/17668] intraday_9032.csv.gz  in=434,631,366 out=103,945,320 elapsed=222.9s

  [16702/17668] intraday_9035.csv.gz  in=434,644,321 out=103,945,320 elapsed=222.9s

  [16703/17668] intraday_9033.csv.gz  in=434,657,396 out=103,945,320 elapsed=222.9s

  [16704/17668] intraday_9034.csv.gz  in=434,668,527 out=103,945,320 elapsed=222.9s

  [16705/17668] intraday_9036.csv.gz  in=434,681,334 out=103,945,320 elapsed=222.9s

  [16706/17668] intraday_9037.csv.gz  in=434,691,511 out=103,945,320 elapsed=222.9s

  [16707/17668] intraday_9038.csv.gz  in=434,705,512 out=103,945,320 elapsed=222.9s

  [16708/17668] intraday_9040.csv.gz  in=434,717,210 out=103,945,320 elapsed=222.9s

  [16709/17668] intraday_9039.csv.gz  in=434,731,988 out=103,945,320 elapsed=223.0s

  [16710/17668] intraday_9041.csv.gz  in=434,745,282 out=103,945,320 elapsed=223.0s

  [16711/17668] intraday_9042.csv.gz  in=434,756,842 out=103,945,320 elapsed=223.0s

  [16712/17668] intraday_9043.csv.gz  in=434,766,205 out=103,945,320 elapsed=223.0s

  [16713/17668] intraday_9044.csv.gz  in=434,779,130 out=103,945,320 elapsed=223.0s

  [16714/17668] intraday_9047.csv.gz  in=434,791,637 out=103,945,320 elapsed=223.0s

  [16715/17668] intraday_9045.csv.gz  in=434,804,149 out=103,945,320 elapsed=223.0s

  [16716/17668] intraday_9046.csv.gz  in=434,817,105 out=103,945,320 elapsed=223.0s

  [16717/17668] intraday_9048.csv.gz  in=434,830,189 out=103,945,320 elapsed=223.0s

  [16718/17668] intraday_9049.csv.gz  in=434,841,492 out=103,945,320 elapsed=223.1s

  [16719/17668] intraday_9051.csv.gz  in=434,854,353 out=103,945,320 elapsed=223.1s

  [16720/17668] intraday_9050.csv.gz  in=434,867,074 out=103,945,320 elapsed=223.1s

  [16721/17668] intraday_9053.csv.gz  in=434,879,203 out=103,945,320 elapsed=223.1s

  [16722/17668] intraday_9052.csv.gz  in=434,889,501 out=103,945,320 elapsed=223.1s

  [16723/17668] intraday_9054.csv.gz  in=434,898,409 out=103,945,320 elapsed=223.1s

  [16724/17668] intraday_9055.csv.gz  in=434,909,973 out=103,945,320 elapsed=223.1s

  [16725/17668] intraday_9056.csv.gz  in=434,922,169 out=103,945,320 elapsed=223.1s

  [16726/17668] intraday_9057.csv.gz  in=434,938,292 out=103,945,320 elapsed=223.1s

  [16727/17668] intraday_9058.csv.gz  in=434,953,591 out=103,945,320 elapsed=223.2s

  [16728/17668] intraday_9059.csv.gz  in=434,964,660 out=103,945,320 elapsed=223.2s

  [16729/17668] intraday_9060.csv.gz  in=434,977,192 out=103,945,320 elapsed=223.2s

  [16730/17668] intraday_9061.csv.gz  in=434,990,943 out=103,945,320 elapsed=223.2s

  [16731/17668] intraday_9062.csv.gz  in=435,002,998 out=103,945,320 elapsed=223.2s

  [16732/17668] intraday_9063.csv.gz  in=435,017,449 out=103,945,320 elapsed=223.2s

  [16733/17668] intraday_9064.csv.gz  in=435,031,134 out=103,945,320 elapsed=223.2s

  [16734/17668] intraday_9065.csv.gz  in=435,042,963 out=103,945,320 elapsed=223.2s

  [16735/17668] intraday_9066.csv.gz  in=435,057,628 out=103,945,320 elapsed=223.2s

  [16736/17668] intraday_9067.csv.gz  in=435,070,605 out=103,945,320 elapsed=223.2s

  [16737/17668] intraday_9068.csv.gz  in=435,083,415 out=103,945,320 elapsed=223.2s

  [16738/17668] intraday_9069.csv.gz  in=435,096,479 out=103,945,320 elapsed=223.2s

  [16739/17668] intraday_9073.csv.gz  in=435,108,065 out=103,945,320 elapsed=223.3s

  [16740/17668] intraday_9072.csv.gz  in=435,121,797 out=103,945,320 elapsed=223.3s

  [16741/17668] intraday_9070.csv.gz  in=435,133,520 out=103,945,320 elapsed=223.3s

  [16742/17668] intraday_9071.csv.gz  in=435,145,818 out=103,945,320 elapsed=223.3s

  [16743/17668] intraday_9074.csv.gz  in=435,156,900 out=103,945,320 elapsed=223.3s

  [16744/17668] intraday_9075.csv.gz  in=435,169,393 out=103,945,320 elapsed=223.3s

  [16745/17668] intraday_9076.csv.gz  in=435,185,020 out=103,945,320 elapsed=223.3s

  [16746/17668] intraday_9078.csv.gz  in=435,197,162 out=103,945,320 elapsed=223.3s

  [16747/17668] intraday_9077.csv.gz  in=435,210,985 out=103,945,320 elapsed=223.3s

  [16748/17668] intraday_9080.csv.gz  in=435,227,080 out=103,945,320 elapsed=223.4s

  [16749/17668] intraday_9081.csv.gz  in=435,238,672 out=103,945,320 elapsed=223.4s

  [16750/17668] intraday_9079.csv.gz  in=435,250,971 out=103,945,320 elapsed=223.4s

  [16751/17668] intraday_9082.csv.gz  in=435,264,116 out=103,945,320 elapsed=223.4s

  [16752/17668] intraday_9085.csv.gz  in=435,274,177 out=103,945,320 elapsed=223.4s

  [16753/17668] intraday_9084.csv.gz  in=435,287,445 out=103,945,320 elapsed=223.4s

  [16754/17668] intraday_9083.csv.gz  in=435,302,231 out=103,945,320 elapsed=223.4s

  [16755/17668] intraday_9086.csv.gz  in=435,315,780 out=103,945,320 elapsed=223.4s

  [16756/17668] intraday_9087.csv.gz  in=435,327,606 out=103,945,320 elapsed=223.4s

  [16757/17668] intraday_9088.csv.gz  in=435,340,020 out=103,945,320 elapsed=223.4s

  [16758/17668] intraday_9090.csv.gz  in=435,353,394 out=103,945,320 elapsed=223.4s

  [16759/17668] intraday_9089.csv.gz  in=435,371,775 out=103,945,320 elapsed=223.4s

  [16760/17668] intraday_9091.csv.gz  in=435,392,289 out=103,945,320 elapsed=223.5s

  [16761/17668] intraday_9093.csv.gz  in=435,405,322 out=103,945,320 elapsed=223.5s

  [16762/17668] intraday_9092.csv.gz  in=435,421,436 out=103,945,320 elapsed=223.5s

  [16763/17668] intraday_9094.csv.gz  in=435,433,825 out=103,945,320 elapsed=223.5s

  [16764/17668] intraday_9096.csv.gz  in=435,444,357 out=103,945,320 elapsed=223.5s

  [16765/17668] intraday_9097.csv.gz  in=435,457,933 out=103,945,320 elapsed=223.5s

  [16766/17668] intraday_9098.csv.gz  in=435,467,825 out=103,945,320 elapsed=223.5s

  [16767/17668] intraday_9095.csv.gz  in=435,480,762 out=103,945,320 elapsed=223.5s

  [16768/17668] intraday_9101.csv.gz  in=435,495,883 out=103,945,320 elapsed=223.5s

  [16769/17668] intraday_9102.csv.gz  in=435,507,022 out=103,945,320 elapsed=223.6s

  [16770/17668] intraday_9100.csv.gz  in=435,520,076 out=103,945,320 elapsed=223.6s

  [16771/17668] intraday_9099.csv.gz  in=435,534,964 out=103,945,320 elapsed=223.6s

  [16772/17668] intraday_9103.csv.gz  in=435,547,101 out=103,945,320 elapsed=223.6s

  [16773/17668] intraday_9106.csv.gz  in=435,559,421 out=103,945,320 elapsed=223.6s

  [16774/17668] intraday_9104.csv.gz  in=435,572,142 out=103,945,320 elapsed=223.6s

  [16775/17668] intraday_9105.csv.gz  in=435,583,529 out=103,945,320 elapsed=223.6s

  [16776/17668] intraday_9107.csv.gz  in=435,597,613 out=103,945,320 elapsed=223.6s

  [16777/17668] intraday_9108.csv.gz  in=435,613,240 out=103,945,320 elapsed=223.6s

  [16778/17668] intraday_9110.csv.gz  in=435,627,311 out=103,945,320 elapsed=223.6s

  [16779/17668] intraday_9109.csv.gz  in=435,640,176 out=103,945,320 elapsed=223.6s

  [16780/17668] intraday_9111.csv.gz  in=435,652,830 out=103,945,320 elapsed=223.6s

  [16781/17668] intraday_9113.csv.gz  in=435,665,947 out=103,945,320 elapsed=223.7s

  [16782/17668] intraday_9114.csv.gz  in=435,676,884 out=103,945,320 elapsed=223.7s

  [16783/17668] intraday_9112.csv.gz  in=435,690,624 out=103,945,320 elapsed=223.7s

  [16784/17668] intraday_9115.csv.gz  in=435,702,189 out=103,945,320 elapsed=223.7s

  [16785/17668] intraday_9117.csv.gz  in=435,713,393 out=103,945,320 elapsed=223.7s

  [16786/17668] intraday_9116.csv.gz  in=435,720,588 out=103,945,320 elapsed=223.7s

  [16787/17668] intraday_9118.csv.gz  in=435,726,360 out=103,945,320 elapsed=223.7s

  [16788/17668] intraday_9119.csv.gz  in=435,751,632 out=103,945,320 elapsed=223.7s

  [16789/17668] intraday_9120.csv.gz  in=435,767,550 out=103,945,320 elapsed=223.7s

  [16790/17668] intraday_9121.csv.gz  in=435,779,886 out=103,945,320 elapsed=223.8s

  [16791/17668] intraday_9122.csv.gz  in=435,793,152 out=103,945,320 elapsed=223.8s

  [16792/17668] intraday_9124.csv.gz  in=435,805,662 out=103,945,320 elapsed=223.8s

  [16793/17668] intraday_9123.csv.gz  in=435,815,573 out=103,945,320 elapsed=223.8s

  [16794/17668] intraday_9125.csv.gz  in=435,831,050 out=103,945,320 elapsed=223.8s

  [16795/17668] intraday_9126.csv.gz  in=435,846,117 out=103,945,320 elapsed=223.8s

  [16796/17668] intraday_9129.csv.gz  in=435,860,826 out=103,945,320 elapsed=223.8s

  [16797/17668] intraday_9127.csv.gz  in=435,872,808 out=103,945,320 elapsed=223.8s

  [16798/17668] intraday_9130.csv.gz  in=435,887,762 out=103,945,320 elapsed=223.8s

  [16799/17668] intraday_9128.csv.gz  in=435,900,356 out=103,945,320 elapsed=223.9s

  [16800/17668] intraday_9132.csv.gz  in=435,914,381 out=103,945,320 elapsed=223.9s

  [16801/17668] intraday_9131.csv.gz  in=435,926,875 out=103,945,320 elapsed=223.9s

  [16802/17668] intraday_9134.csv.gz  in=435,936,106 out=103,945,320 elapsed=223.9s

  [16803/17668] intraday_9133.csv.gz  in=435,950,504 out=103,945,320 elapsed=223.9s

  [16804/17668] intraday_9135.csv.gz  in=435,962,359 out=103,945,320 elapsed=223.9s

  [16805/17668] intraday_9137.csv.gz  in=435,975,466 out=103,945,320 elapsed=223.9s

  [16806/17668] intraday_9136.csv.gz  in=435,989,975 out=103,945,320 elapsed=223.9s

  [16807/17668] intraday_9138.csv.gz  in=436,002,114 out=103,945,320 elapsed=223.9s

  [16808/17668] intraday_9139.csv.gz  in=436,012,517 out=103,945,320 elapsed=223.9s

  [16809/17668] intraday_9140.csv.gz  in=436,023,905 out=103,945,320 elapsed=224.0s

  [16810/17668] intraday_9141.csv.gz  in=436,037,517 out=103,945,320 elapsed=224.0s

  [16811/17668] intraday_9143.csv.gz  in=436,051,321 out=103,945,320 elapsed=224.0s

  [16812/17668] intraday_9142.csv.gz  in=436,063,980 out=103,945,320 elapsed=224.0s

  [16813/17668] intraday_9144.csv.gz  in=436,079,638 out=103,945,320 elapsed=224.0s

  [16814/17668] intraday_9145.csv.gz  in=436,092,309 out=103,945,320 elapsed=224.0s

  [16815/17668] intraday_9146.csv.gz  in=436,105,075 out=103,945,320 elapsed=224.0s

  [16816/17668] intraday_9147.csv.gz  in=436,116,982 out=103,945,320 elapsed=224.0s

  [16817/17668] intraday_9148.csv.gz  in=436,128,061 out=103,945,320 elapsed=224.0s

  [16818/17668] intraday_9149.csv.gz  in=436,141,310 out=103,945,320 elapsed=224.0s

  [16819/17668] intraday_9150.csv.gz  in=436,157,898 out=103,945,320 elapsed=224.0s

  [16820/17668] intraday_9152.csv.gz  in=436,167,570 out=103,945,320 elapsed=224.0s

  [16821/17668] intraday_9151.csv.gz  in=436,182,649 out=103,945,320 elapsed=224.1s

  [16822/17668] intraday_9155.csv.gz  in=436,197,175 out=103,945,320 elapsed=224.1s

  [16823/17668] intraday_9153.csv.gz  in=436,209,219 out=103,945,320 elapsed=224.1s

  [16824/17668] intraday_9154.csv.gz  in=436,221,788 out=103,945,320 elapsed=224.1s

  [16825/17668] intraday_9157.csv.gz  in=436,233,867 out=103,945,320 elapsed=224.1s

  [16826/17668] intraday_9156.csv.gz  in=436,245,056 out=103,945,320 elapsed=224.1s

  [16827/17668] intraday_9159.csv.gz  in=436,255,624 out=103,945,320 elapsed=224.1s

  [16828/17668] intraday_9158.csv.gz  in=436,272,175 out=103,945,320 elapsed=224.1s

  [16829/17668] intraday_9160.csv.gz  in=436,285,505 out=103,945,320 elapsed=224.1s

  [16830/17668] intraday_9161.csv.gz  in=436,299,017 out=103,945,320 elapsed=224.1s

  [16831/17668] intraday_9162.csv.gz  in=436,310,551 out=103,945,320 elapsed=224.2s

  [16832/17668] intraday_9163.csv.gz  in=436,323,344 out=103,945,320 elapsed=224.2s

  [16833/17668] intraday_9165.csv.gz  in=436,335,925 out=103,945,320 elapsed=224.2s

  [16834/17668] intraday_9164.csv.gz  in=436,349,986 out=103,945,320 elapsed=224.2s

  [16835/17668] intraday_9166.csv.gz  in=436,362,724 out=103,945,320 elapsed=224.2s

  [16836/17668] intraday_9167.csv.gz  in=436,373,825 out=103,945,320 elapsed=224.2s

  [16837/17668] intraday_9168.csv.gz  in=436,386,359 out=103,945,320 elapsed=224.2s

  [16838/17668] intraday_9169.csv.gz  in=436,398,974 out=103,945,320 elapsed=224.2s

  [16839/17668] intraday_9170.csv.gz  in=436,410,920 out=103,945,320 elapsed=224.2s

  [16840/17668] intraday_9171.csv.gz  in=436,421,945 out=103,945,320 elapsed=224.2s

  [16841/17668] intraday_9172.csv.gz  in=436,434,994 out=103,945,320 elapsed=224.3s

  [16842/17668] intraday_9173.csv.gz  in=436,449,770 out=103,945,320 elapsed=224.3s

  [16843/17668] intraday_9174.csv.gz  in=436,463,462 out=103,945,320 elapsed=224.3s

  [16844/17668] intraday_9175.csv.gz  in=436,476,681 out=103,945,320 elapsed=224.3s

  [16845/17668] intraday_9178.csv.gz  in=436,486,193 out=103,945,320 elapsed=224.3s

  [16846/17668] intraday_9179.csv.gz  in=436,499,576 out=103,945,320 elapsed=224.3s

  [16847/17668] intraday_9176.csv.gz  in=436,512,259 out=103,945,320 elapsed=224.3s

  [16848/17668] intraday_9177.csv.gz  in=436,524,122 out=103,945,320 elapsed=224.3s

  [16849/17668] intraday_9181.csv.gz  in=436,536,452 out=103,945,320 elapsed=224.3s

  [16850/17668] intraday_9180.csv.gz  in=436,550,155 out=103,945,320 elapsed=224.3s

  [16851/17668] intraday_9183.csv.gz  in=436,561,872 out=103,945,320 elapsed=224.3s

  [16852/17668] intraday_9182.csv.gz  in=436,575,525 out=103,945,320 elapsed=224.3s

  [16853/17668] intraday_9184.csv.gz  in=436,585,936 out=103,945,320 elapsed=224.3s

  [16854/17668] intraday_9185.csv.gz  in=436,599,411 out=103,945,320 elapsed=224.4s

  [16855/17668] intraday_9186.csv.gz  in=436,614,349 out=103,945,320 elapsed=224.4s

  [16856/17668] intraday_9187.csv.gz  in=436,626,092 out=103,945,320 elapsed=224.4s

  [16857/17668] intraday_9188.csv.gz  in=436,640,159 out=103,945,320 elapsed=224.4s

  [16858/17668] intraday_9191.csv.gz  in=436,651,932 out=103,945,320 elapsed=224.4s

  [16859/17668] intraday_9190.csv.gz  in=436,662,863 out=103,945,320 elapsed=224.4s

  [16860/17668] intraday_9189.csv.gz  in=436,675,146 out=103,945,320 elapsed=224.4s

  [16861/17668] intraday_9192.csv.gz  in=436,688,770 out=103,945,320 elapsed=224.4s

  [16862/17668] intraday_9193.csv.gz  in=436,700,204 out=103,945,320 elapsed=224.4s

  [16863/17668] intraday_9195.csv.gz  in=436,711,956 out=103,945,320 elapsed=224.4s

  [16864/17668] intraday_9194.csv.gz  in=436,725,546 out=103,945,320 elapsed=224.5s

  [16865/17668] intraday_9196.csv.gz  in=436,737,923 out=103,945,320 elapsed=224.5s

  [16866/17668] intraday_9197.csv.gz  in=436,749,192 out=103,945,320 elapsed=224.5s

  [16867/17668] intraday_9199.csv.gz  in=436,760,188 out=103,945,320 elapsed=224.5s

  [16868/17668] intraday_9198.csv.gz  in=436,774,233 out=103,945,320 elapsed=224.5s

  [16869/17668] intraday_9200.csv.gz  in=436,786,358 out=103,945,320 elapsed=224.5s

  [16870/17668] intraday_9201.csv.gz  in=436,797,617 out=103,945,320 elapsed=224.5s

  [16871/17668] intraday_9202.csv.gz  in=436,808,557 out=103,945,320 elapsed=224.5s

  [16872/17668] intraday_9203.csv.gz  in=436,820,060 out=103,945,320 elapsed=224.5s

  [16873/17668] intraday_9204.csv.gz  in=436,836,902 out=103,945,320 elapsed=224.5s

  [16874/17668] intraday_9208.csv.gz  in=436,848,758 out=103,945,320 elapsed=224.6s

  [16875/17668] intraday_9205.csv.gz  in=436,865,045 out=103,945,320 elapsed=224.6s

  [16876/17668] intraday_9206.csv.gz  in=436,880,537 out=103,945,320 elapsed=224.6s

  [16877/17668] intraday_9207.csv.gz  in=436,891,166 out=103,945,320 elapsed=224.6s

  [16878/17668] intraday_9210.csv.gz  in=436,909,462 out=103,945,320 elapsed=224.6s

  [16879/17668] intraday_9211.csv.gz  in=436,925,398 out=103,945,320 elapsed=224.6s

  [16880/17668] intraday_9209.csv.gz  in=436,939,856 out=103,945,320 elapsed=224.6s

  [16881/17668] intraday_9212.csv.gz  in=436,951,983 out=103,945,320 elapsed=224.6s

  [16882/17668] intraday_9213.csv.gz  in=436,965,678 out=103,945,320 elapsed=224.6s

  [16883/17668] intraday_9214.csv.gz  in=436,977,974 out=103,945,320 elapsed=224.6s

  [16884/17668] intraday_9216.csv.gz  in=436,991,750 out=103,945,320 elapsed=224.6s

  [16885/17668] intraday_9215.csv.gz  in=437,006,462 out=103,945,320 elapsed=224.7s

  [16886/17668] intraday_9217.csv.gz  in=437,017,685 out=103,945,320 elapsed=224.7s

  [16887/17668] intraday_9219.csv.gz  in=437,029,253 out=103,945,320 elapsed=224.7s

  [16888/17668] intraday_9218.csv.gz  in=437,042,106 out=103,945,320 elapsed=224.7s

  [16889/17668] intraday_9220.csv.gz  in=437,054,855 out=103,945,320 elapsed=224.7s

  [16890/17668] intraday_9221.csv.gz  in=437,067,632 out=103,945,320 elapsed=224.7s

  [16891/17668] intraday_9222.csv.gz  in=437,079,302 out=103,945,320 elapsed=224.7s

  [16892/17668] intraday_9223.csv.gz  in=437,094,258 out=103,945,320 elapsed=224.7s

  [16893/17668] intraday_9224.csv.gz  in=437,109,985 out=103,945,320 elapsed=224.7s

  [16894/17668] intraday_9225.csv.gz  in=437,122,601 out=103,945,320 elapsed=224.7s

  [16895/17668] intraday_9226.csv.gz  in=437,135,437 out=103,945,320 elapsed=224.8s

  [16896/17668] intraday_9228.csv.gz  in=437,148,995 out=103,945,320 elapsed=224.8s

  [16897/17668] intraday_9227.csv.gz  in=437,162,192 out=103,945,320 elapsed=224.8s

  [16898/17668] intraday_9229.csv.gz  in=437,175,282 out=103,945,320 elapsed=224.8s

  [16899/17668] intraday_9230.csv.gz  in=437,189,264 out=103,945,320 elapsed=224.8s

  [16900/17668] intraday_9232.csv.gz  in=437,201,060 out=103,945,320 elapsed=224.8s

  [16901/17668] intraday_9231.csv.gz  in=437,216,301 out=103,945,320 elapsed=224.8s

  [16902/17668] intraday_9233.csv.gz  in=437,227,331 out=103,945,320 elapsed=224.8s

  [16903/17668] intraday_9234.csv.gz  in=437,242,016 out=103,945,320 elapsed=224.8s

  [16904/17668] intraday_9236.csv.gz  in=437,258,315 out=103,945,320 elapsed=224.8s

  [16905/17668] intraday_9235.csv.gz  in=437,269,387 out=103,945,320 elapsed=224.8s

  [16906/17668] intraday_9239.csv.gz  in=437,282,277 out=103,945,320 elapsed=224.9s

  [16907/17668] intraday_9237.csv.gz  in=437,297,627 out=103,945,320 elapsed=224.9s

  [16908/17668] intraday_9240.csv.gz  in=437,314,608 out=103,945,320 elapsed=224.9s

  [16909/17668] intraday_9238.csv.gz  in=437,335,111 out=103,945,320 elapsed=224.9s

  [16910/17668] intraday_9242.csv.gz  in=437,349,385 out=103,945,320 elapsed=224.9s

  [16911/17668] intraday_9243.csv.gz  in=437,360,658 out=103,945,320 elapsed=224.9s

  [16912/17668] intraday_9241.csv.gz  in=437,377,202 out=103,945,320 elapsed=224.9s

  [16913/17668] intraday_9244.csv.gz  in=437,390,434 out=103,945,320 elapsed=224.9s

  [16914/17668] intraday_9245.csv.gz  in=437,402,486 out=103,945,320 elapsed=224.9s

  [16915/17668] intraday_9246.csv.gz  in=437,415,540 out=103,945,320 elapsed=224.9s

  [16916/17668] intraday_9247.csv.gz  in=437,429,558 out=103,945,320 elapsed=224.9s

  [16917/17668] intraday_9248.csv.gz  in=437,446,405 out=103,945,320 elapsed=225.0s

  [16918/17668] intraday_9251.csv.gz  in=437,458,155 out=103,945,320 elapsed=225.0s

  [16919/17668] intraday_9250.csv.gz  in=437,470,137 out=103,945,320 elapsed=225.0s

  [16920/17668] intraday_9249.csv.gz  in=437,481,484 out=103,945,320 elapsed=225.0s

  [16921/17668] intraday_9252.csv.gz  in=437,493,930 out=103,945,320 elapsed=225.0s

  [16922/17668] intraday_9253.csv.gz  in=437,506,052 out=103,945,320 elapsed=225.0s

  [16923/17668] intraday_9254.csv.gz  in=437,518,948 out=103,945,320 elapsed=225.0s

  [16924/17668] intraday_9255.csv.gz  in=437,534,148 out=103,945,320 elapsed=225.0s

  [16925/17668] intraday_9256.csv.gz  in=437,547,582 out=103,945,320 elapsed=225.0s

  [16926/17668] intraday_9259.csv.gz  in=437,558,533 out=103,945,320 elapsed=225.0s

  [16927/17668] intraday_9260.csv.gz  in=437,572,716 out=103,945,320 elapsed=225.1s

  [16928/17668] intraday_9258.csv.gz  in=437,586,145 out=103,945,320 elapsed=225.1s

  [16929/17668] intraday_9257.csv.gz  in=437,602,489 out=103,945,320 elapsed=225.1s

  [16930/17668] intraday_9261.csv.gz  in=437,613,275 out=103,945,320 elapsed=225.1s

  [16931/17668] intraday_9264.csv.gz  in=437,621,688 out=103,945,320 elapsed=225.1s

  [16932/17668] intraday_9263.csv.gz  in=437,629,829 out=103,945,320 elapsed=225.1s

  [16933/17668] intraday_9262.csv.gz  in=437,643,852 out=103,945,320 elapsed=225.1s

  [16934/17668] intraday_9266.csv.gz  in=437,645,134 out=103,945,320 elapsed=225.1s

  [16935/17668] intraday_9265.csv.gz  in=437,657,750 out=103,945,320 elapsed=225.1s

  [16936/17668] intraday_9268.csv.gz  in=437,673,694 out=103,945,320 elapsed=225.1s

  [16937/17668] intraday_9269.csv.gz  in=437,686,607 out=103,945,320 elapsed=225.1s

  [16938/17668] intraday_9270.csv.gz  in=437,699,212 out=103,945,320 elapsed=225.1s

  [16939/17668] intraday_9272.csv.gz  in=437,712,171 out=103,945,320 elapsed=225.2s

  [16940/17668] intraday_9271.csv.gz  in=437,722,856 out=103,945,320 elapsed=225.2s

  [16941/17668] intraday_9267.csv.gz  in=437,782,131 out=103,945,320 elapsed=225.2s

  [16942/17668] intraday_9274.csv.gz  in=437,796,873 out=103,945,320 elapsed=225.2s

  [16943/17668] intraday_9273.csv.gz  in=437,811,656 out=103,945,320 elapsed=225.2s

  [16944/17668] intraday_9275.csv.gz  in=437,824,711 out=103,945,320 elapsed=225.2s

  [16945/17668] intraday_9276.csv.gz  in=437,836,970 out=103,945,320 elapsed=225.2s

  [16946/17668] intraday_9277.csv.gz  in=437,851,506 out=103,945,320 elapsed=225.2s

  [16947/17668] intraday_9278.csv.gz  in=437,866,033 out=103,945,320 elapsed=225.3s

  [16948/17668] intraday_9279.csv.gz  in=437,879,485 out=103,945,320 elapsed=225.3s

  [16949/17668] intraday_9280.csv.gz  in=437,893,070 out=103,945,320 elapsed=225.3s

  [16950/17668] intraday_9281.csv.gz  in=437,907,119 out=103,945,320 elapsed=225.3s

  [16951/17668] intraday_9282.csv.gz  in=437,917,576 out=103,945,320 elapsed=225.3s

  [16952/17668] intraday_9283.csv.gz  in=437,928,114 out=103,945,320 elapsed=225.3s

  [16953/17668] intraday_9284.csv.gz  in=437,941,677 out=103,945,320 elapsed=225.3s

  [16954/17668] intraday_9286.csv.gz  in=437,954,559 out=103,945,320 elapsed=225.3s

  [16955/17668] intraday_9285.csv.gz  in=437,967,861 out=103,945,320 elapsed=225.3s

  [16956/17668] intraday_9287.csv.gz  in=437,979,151 out=103,945,320 elapsed=225.3s

  [16957/17668] intraday_9288.csv.gz  in=437,990,590 out=103,945,320 elapsed=225.3s

  [16958/17668] intraday_9290.csv.gz  in=438,003,397 out=103,945,320 elapsed=225.4s

  [16959/17668] intraday_9289.csv.gz  in=438,017,127 out=103,945,320 elapsed=225.4s

  [16960/17668] intraday_9292.csv.gz  in=438,031,098 out=103,945,320 elapsed=225.4s

  [16961/17668] intraday_9291.csv.gz  in=438,045,334 out=103,945,320 elapsed=225.4s

  [16962/17668] intraday_9293.csv.gz  in=438,057,990 out=103,945,320 elapsed=225.4s

  [16963/17668] intraday_9294.csv.gz  in=438,070,779 out=103,945,320 elapsed=225.4s

  [16964/17668] intraday_9297.csv.gz  in=438,084,253 out=103,945,320 elapsed=225.4s

  [16965/17668] intraday_9296.csv.gz  in=438,095,616 out=103,945,320 elapsed=225.4s

  [16966/17668] intraday_9295.csv.gz  in=438,107,644 out=103,945,320 elapsed=225.4s

  [16967/17668] intraday_9298.csv.gz  in=438,123,156 out=103,945,320 elapsed=225.4s

  [16968/17668] intraday_9299.csv.gz  in=438,136,744 out=103,945,320 elapsed=225.4s

  [16969/17668] intraday_9300.csv.gz  in=438,147,935 out=103,945,320 elapsed=225.4s

  [16970/17668] intraday_9301.csv.gz  in=438,160,176 out=103,945,320 elapsed=225.5s

  [16971/17668] intraday_9302.csv.gz  in=438,173,221 out=103,945,320 elapsed=225.5s

  [16972/17668] intraday_9304.csv.gz  in=438,185,261 out=103,945,320 elapsed=225.5s

  [16973/17668] intraday_9303.csv.gz  in=438,197,092 out=103,945,320 elapsed=225.5s

  [16974/17668] intraday_9305.csv.gz  in=438,208,805 out=103,945,320 elapsed=225.5s

  [16975/17668] intraday_9306.csv.gz  in=438,221,052 out=103,945,320 elapsed=225.5s

  [16976/17668] intraday_9308.csv.gz  in=438,233,157 out=103,945,320 elapsed=225.5s

  [16977/17668] intraday_9307.csv.gz  in=438,244,191 out=103,945,320 elapsed=225.5s

  [16978/17668] intraday_9309.csv.gz  in=438,257,035 out=103,945,320 elapsed=225.5s

  [16979/17668] intraday_9310.csv.gz  in=438,270,522 out=103,945,320 elapsed=225.6s

  [16980/17668] intraday_9312.csv.gz  in=438,284,192 out=103,945,320 elapsed=225.6s

  [16981/17668] intraday_9313.csv.gz  in=438,295,437 out=103,945,320 elapsed=225.6s

  [16982/17668] intraday_9311.csv.gz  in=438,309,060 out=103,945,320 elapsed=225.6s

  [16983/17668] intraday_9314.csv.gz  in=438,321,334 out=103,945,320 elapsed=225.6s

  [16984/17668] intraday_9316.csv.gz  in=438,332,800 out=103,945,320 elapsed=225.6s

  [16985/17668] intraday_9317.csv.gz  in=438,345,373 out=103,945,320 elapsed=225.6s

  [16986/17668] intraday_9315.csv.gz  in=438,358,695 out=103,945,320 elapsed=225.6s

  [16987/17668] intraday_9318.csv.gz  in=438,370,272 out=103,945,320 elapsed=225.6s

  [16988/17668] intraday_9321.csv.gz  in=438,381,825 out=103,945,320 elapsed=225.7s

  [16989/17668] intraday_9319.csv.gz  in=438,392,570 out=103,945,320 elapsed=225.7s

  [16990/17668] intraday_9320.csv.gz  in=438,409,883 out=103,945,320 elapsed=225.7s

  [16991/17668] intraday_9322.csv.gz  in=438,422,806 out=103,945,320 elapsed=225.7s

  [16992/17668] intraday_9323.csv.gz  in=438,435,720 out=103,945,320 elapsed=225.7s

  [16993/17668] intraday_9324.csv.gz  in=438,448,637 out=103,945,320 elapsed=225.7s

  [16994/17668] intraday_9325.csv.gz  in=438,460,136 out=103,945,320 elapsed=225.7s

  [16995/17668] intraday_9326.csv.gz  in=438,471,512 out=103,945,320 elapsed=225.7s

  [16996/17668] intraday_9327.csv.gz  in=438,485,033 out=103,945,320 elapsed=225.7s

  [16997/17668] intraday_9329.csv.gz  in=438,496,658 out=103,945,320 elapsed=225.7s

  [16998/17668] intraday_9328.csv.gz  in=438,509,721 out=103,945,320 elapsed=225.7s

  [16999/17668] intraday_9330.csv.gz  in=438,523,195 out=103,945,320 elapsed=225.7s

  [17000/17668] intraday_9331.csv.gz  in=438,535,426 out=103,945,320 elapsed=225.7s

  [17001/17668] intraday_9332.csv.gz  in=438,546,039 out=103,945,320 elapsed=225.7s

  [17002/17668] intraday_9333.csv.gz  in=438,561,162 out=103,945,320 elapsed=225.8s

  [17003/17668] intraday_9334.csv.gz  in=438,574,156 out=103,945,320 elapsed=225.8s

  [17004/17668] intraday_9335.csv.gz  in=438,587,735 out=103,945,320 elapsed=225.8s

  [17005/17668] intraday_9336.csv.gz  in=438,600,383 out=103,945,320 elapsed=225.8s

  [17006/17668] intraday_9337.csv.gz  in=438,612,646 out=103,945,320 elapsed=225.8s

  [17007/17668] intraday_9338.csv.gz  in=438,622,881 out=103,945,320 elapsed=225.8s

  [17008/17668] intraday_9339.csv.gz  in=438,634,249 out=103,945,320 elapsed=225.8s

  [17009/17668] intraday_9342.csv.gz  in=438,646,370 out=103,945,320 elapsed=225.8s

  [17010/17668] intraday_9343.csv.gz  in=438,659,148 out=103,945,320 elapsed=225.8s

  [17011/17668] intraday_9341.csv.gz  in=438,672,704 out=103,945,320 elapsed=225.8s

  [17012/17668] intraday_9340.csv.gz  in=438,685,766 out=103,945,320 elapsed=225.8s

  [17013/17668] intraday_9344.csv.gz  in=438,696,658 out=103,945,320 elapsed=225.9s

  [17014/17668] intraday_9347.csv.gz  in=438,707,903 out=103,945,320 elapsed=225.9s

  [17015/17668] intraday_9346.csv.gz  in=438,720,008 out=103,945,320 elapsed=225.9s

  [17016/17668] intraday_9345.csv.gz  in=438,733,507 out=103,945,320 elapsed=225.9s

  [17017/17668] intraday_9348.csv.gz  in=438,745,831 out=103,945,320 elapsed=225.9s

  [17018/17668] intraday_9349.csv.gz  in=438,755,064 out=103,945,320 elapsed=225.9s

  [17019/17668] intraday_9350.csv.gz  in=438,767,692 out=103,945,320 elapsed=225.9s

  [17020/17668] intraday_9351.csv.gz  in=438,780,987 out=103,945,320 elapsed=225.9s

  [17021/17668] intraday_9352.csv.gz  in=438,796,160 out=103,945,320 elapsed=225.9s

  [17022/17668] intraday_9353.csv.gz  in=438,810,813 out=103,945,320 elapsed=225.9s

  [17023/17668] intraday_9354.csv.gz  in=438,823,549 out=103,945,320 elapsed=226.0s

  [17024/17668] intraday_9355.csv.gz  in=438,835,620 out=103,945,320 elapsed=226.0s

  [17025/17668] intraday_9356.csv.gz  in=438,850,127 out=103,945,320 elapsed=226.0s

  [17026/17668] intraday_9359.csv.gz  in=438,862,474 out=103,945,320 elapsed=226.0s

  [17027/17668] intraday_9357.csv.gz  in=438,873,375 out=103,945,320 elapsed=226.0s

  [17028/17668] intraday_9358.csv.gz  in=438,890,131 out=103,945,320 elapsed=226.0s

  [17029/17668] intraday_9360.csv.gz  in=438,903,331 out=103,945,320 elapsed=226.0s

  [17030/17668] intraday_9361.csv.gz  in=438,917,002 out=103,945,320 elapsed=226.0s

  [17031/17668] intraday_9363.csv.gz  in=438,930,246 out=103,945,320 elapsed=226.0s

  [17032/17668] intraday_9364.csv.gz  in=438,943,018 out=103,945,320 elapsed=226.0s

  [17033/17668] intraday_9362.csv.gz  in=438,955,777 out=103,945,320 elapsed=226.0s

  [17034/17668] intraday_9365.csv.gz  in=438,968,294 out=103,945,320 elapsed=226.1s

  [17035/17668] intraday_9368.csv.gz  in=438,981,358 out=103,945,320 elapsed=226.1s

  [17036/17668] intraday_9367.csv.gz  in=438,993,858 out=103,945,320 elapsed=226.1s

  [17037/17668] intraday_9366.csv.gz  in=439,006,544 out=103,945,320 elapsed=226.1s

  [17038/17668] intraday_9369.csv.gz  in=439,017,579 out=103,945,320 elapsed=226.1s

  [17039/17668] intraday_9370.csv.gz  in=439,030,073 out=103,945,320 elapsed=226.1s

  [17040/17668] intraday_9371.csv.gz  in=439,047,103 out=103,945,320 elapsed=226.1s

  [17041/17668] intraday_9372.csv.gz  in=439,060,117 out=103,945,320 elapsed=226.1s

  [17042/17668] intraday_9373.csv.gz  in=439,073,475 out=103,945,320 elapsed=226.1s

  [17043/17668] intraday_9374.csv.gz  in=439,085,548 out=103,945,320 elapsed=226.1s

  [17044/17668] intraday_9376.csv.gz  in=439,098,016 out=103,945,320 elapsed=226.2s

  [17045/17668] intraday_9375.csv.gz  in=439,112,529 out=103,945,320 elapsed=226.2s

  [17046/17668] intraday_9377.csv.gz  in=439,125,509 out=103,945,320 elapsed=226.2s

  [17047/17668] intraday_9379.csv.gz  in=439,139,041 out=103,945,320 elapsed=226.2s

  [17048/17668] intraday_9378.csv.gz  in=439,153,931 out=103,945,320 elapsed=226.2s

  [17049/17668] intraday_9380.csv.gz  in=439,164,552 out=103,945,320 elapsed=226.2s

  [17050/17668] intraday_9381.csv.gz  in=439,178,049 out=103,945,320 elapsed=226.2s

  [17051/17668] intraday_9383.csv.gz  in=439,191,768 out=103,945,320 elapsed=226.2s

  [17052/17668] intraday_9382.csv.gz  in=439,204,577 out=103,945,320 elapsed=226.2s

  [17053/17668] intraday_9384.csv.gz  in=439,220,842 out=103,945,320 elapsed=226.2s

  [17054/17668] intraday_9385.csv.gz  in=439,235,538 out=103,945,320 elapsed=226.2s

  [17055/17668] intraday_9386.csv.gz  in=439,253,586 out=103,945,320 elapsed=226.3s

  [17056/17668] intraday_9387.csv.gz  in=439,268,768 out=103,945,320 elapsed=226.3s

  [17057/17668] intraday_9388.csv.gz  in=439,280,908 out=103,945,320 elapsed=226.3s

  [17058/17668] intraday_9389.csv.gz  in=439,293,548 out=103,945,320 elapsed=226.3s

  [17059/17668] intraday_9390.csv.gz  in=439,306,104 out=103,945,320 elapsed=226.3s

  [17060/17668] intraday_9391.csv.gz  in=439,317,117 out=103,945,320 elapsed=226.3s

  [17061/17668] intraday_9392.csv.gz  in=439,330,563 out=103,945,320 elapsed=226.3s

  [17062/17668] intraday_9393.csv.gz  in=439,340,917 out=103,945,320 elapsed=226.3s

  [17063/17668] intraday_9394.csv.gz  in=439,355,526 out=103,945,320 elapsed=226.3s

  [17064/17668] intraday_9395.csv.gz  in=439,369,124 out=103,945,320 elapsed=226.3s

  [17065/17668] intraday_9396.csv.gz  in=439,384,116 out=103,945,320 elapsed=226.4s

  [17066/17668] intraday_9397.csv.gz  in=439,395,686 out=103,945,320 elapsed=226.4s

  [17067/17668] intraday_9399.csv.gz  in=439,409,298 out=103,945,320 elapsed=226.4s

  [17068/17668] intraday_9398.csv.gz  in=439,420,061 out=103,945,320 elapsed=226.4s

  [17069/17668] intraday_9401.csv.gz  in=439,432,427 out=103,945,320 elapsed=226.4s

  [17070/17668] intraday_9400.csv.gz  in=439,443,890 out=103,945,320 elapsed=226.4s

  [17071/17668] intraday_9404.csv.gz  in=439,457,231 out=103,945,320 elapsed=226.4s

  [17072/17668] intraday_9402.csv.gz  in=439,472,103 out=103,945,320 elapsed=226.4s

  [17073/17668] intraday_9405.csv.gz  in=439,486,841 out=103,945,320 elapsed=226.4s

  [17074/17668] intraday_9403.csv.gz  in=439,501,789 out=103,945,320 elapsed=226.4s

  [17075/17668] intraday_9407.csv.gz  in=439,515,285 out=103,945,320 elapsed=226.5s

  [17076/17668] intraday_9408.csv.gz  in=439,527,554 out=103,945,320 elapsed=226.5s

  [17077/17668] intraday_9406.csv.gz  in=439,540,156 out=103,945,320 elapsed=226.5s

  [17078/17668] intraday_9409.csv.gz  in=439,553,007 out=103,945,320 elapsed=226.5s

  [17079/17668] intraday_9410.csv.gz  in=439,562,740 out=103,945,320 elapsed=226.5s

  [17080/17668] intraday_9413.csv.gz  in=439,567,794 out=103,945,320 elapsed=226.5s

  [17081/17668] intraday_9411.csv.gz  in=439,576,027 out=103,945,320 elapsed=226.5s

  [17082/17668] intraday_9412.csv.gz  in=439,586,417 out=103,945,320 elapsed=226.5s

  [17083/17668] intraday_9416.csv.gz  in=439,599,354 out=103,945,320 elapsed=226.5s

  [17084/17668] intraday_9417.csv.gz  in=439,610,102 out=103,945,320 elapsed=226.5s

  [17085/17668] intraday_9415.csv.gz  in=439,626,186 out=103,945,320 elapsed=226.6s

  [17086/17668] intraday_9418.csv.gz  in=439,636,958 out=103,945,320 elapsed=226.6s

  [17087/17668] intraday_9414.csv.gz  in=439,665,316 out=103,945,320 elapsed=226.6s

  [17088/17668] intraday_9419.csv.gz  in=439,677,577 out=103,945,320 elapsed=226.6s

  [17089/17668] intraday_9420.csv.gz  in=439,693,059 out=103,945,320 elapsed=226.6s

  [17090/17668] intraday_9421.csv.gz  in=439,707,085 out=103,945,320 elapsed=226.6s

  [17091/17668] intraday_9422.csv.gz  in=439,719,488 out=103,945,320 elapsed=226.6s

  [17092/17668] intraday_9423.csv.gz  in=439,731,364 out=103,945,320 elapsed=226.6s

  [17093/17668] intraday_9425.csv.gz  in=439,746,044 out=103,945,320 elapsed=226.6s

  [17094/17668] intraday_9424.csv.gz  in=439,760,671 out=103,945,320 elapsed=226.6s

  [17095/17668] intraday_9426.csv.gz  in=439,772,414 out=103,945,320 elapsed=226.6s

  [17096/17668] intraday_9427.csv.gz  in=439,786,848 out=103,945,320 elapsed=226.7s

  [17097/17668] intraday_9428.csv.gz  in=439,800,362 out=103,945,320 elapsed=226.7s

  [17098/17668] intraday_9429.csv.gz  in=439,811,170 out=103,945,320 elapsed=226.7s

  [17099/17668] intraday_9430.csv.gz  in=439,822,479 out=103,945,320 elapsed=226.7s

  [17100/17668] intraday_9432.csv.gz  in=439,834,835 out=103,945,320 elapsed=226.7s

  [17101/17668] intraday_9431.csv.gz  in=439,848,041 out=103,945,320 elapsed=226.7s

  [17102/17668] intraday_9433.csv.gz  in=439,860,444 out=103,945,320 elapsed=226.7s

  [17103/17668] intraday_9434.csv.gz  in=439,871,792 out=103,945,320 elapsed=226.7s

  [17104/17668] intraday_9435.csv.gz  in=439,883,437 out=103,945,320 elapsed=226.7s

  [17105/17668] intraday_9437.csv.gz  in=439,896,209 out=103,945,320 elapsed=226.7s

  [17106/17668] intraday_9436.csv.gz  in=439,908,663 out=103,945,320 elapsed=226.8s

  [17107/17668] intraday_9438.csv.gz  in=439,920,928 out=103,945,320 elapsed=226.8s

  [17108/17668] intraday_9440.csv.gz  in=439,933,196 out=103,945,320 elapsed=226.8s

  [17109/17668] intraday_9441.csv.gz  in=439,944,772 out=103,945,320 elapsed=226.8s

  [17110/17668] intraday_9439.csv.gz  in=439,958,788 out=103,945,320 elapsed=226.8s

  [17111/17668] intraday_9442.csv.gz  in=439,970,423 out=103,945,320 elapsed=226.8s

  [17112/17668] intraday_9445.csv.gz  in=439,985,416 out=103,945,320 elapsed=226.8s

  [17113/17668] intraday_9443.csv.gz  in=439,997,019 out=103,945,320 elapsed=226.8s

  [17114/17668] intraday_9444.csv.gz  in=440,009,509 out=103,945,320 elapsed=226.8s

  [17115/17668] intraday_9446.csv.gz  in=440,022,729 out=103,945,320 elapsed=226.8s

  [17116/17668] intraday_9447.csv.gz  in=440,032,973 out=103,945,320 elapsed=226.9s

  [17117/17668] intraday_9448.csv.gz  in=440,044,796 out=103,945,320 elapsed=226.9s

  [17118/17668] intraday_9450.csv.gz  in=440,057,408 out=103,945,320 elapsed=226.9s

  [17119/17668] intraday_9449.csv.gz  in=440,069,661 out=103,945,320 elapsed=226.9s

  [17120/17668] intraday_9451.csv.gz  in=440,081,515 out=103,945,320 elapsed=226.9s

  [17121/17668] intraday_9452.csv.gz  in=440,093,838 out=103,945,320 elapsed=226.9s

  [17122/17668] intraday_9453.csv.gz  in=440,105,000 out=103,945,320 elapsed=226.9s

  [17123/17668] intraday_9454.csv.gz  in=440,115,610 out=103,945,320 elapsed=226.9s

  [17124/17668] intraday_9455.csv.gz  in=440,127,404 out=103,945,320 elapsed=226.9s

  [17125/17668] intraday_9456.csv.gz  in=440,139,887 out=103,945,320 elapsed=227.0s

  [17126/17668] intraday_9458.csv.gz  in=440,153,157 out=103,945,320 elapsed=227.0s

  [17127/17668] intraday_9457.csv.gz  in=440,165,471 out=103,945,320 elapsed=227.0s

  [17128/17668] intraday_9459.csv.gz  in=440,179,063 out=103,945,320 elapsed=227.0s

  [17129/17668] intraday_9460.csv.gz  in=440,190,572 out=103,945,320 elapsed=227.0s

  [17130/17668] intraday_9462.csv.gz  in=440,202,498 out=103,945,320 elapsed=227.0s

  [17131/17668] intraday_9461.csv.gz  in=440,214,885 out=103,945,320 elapsed=227.0s

  [17132/17668] intraday_9464.csv.gz  in=440,225,131 out=103,945,320 elapsed=227.0s

  [17133/17668] intraday_9465.csv.gz  in=440,237,748 out=103,945,320 elapsed=227.0s

  [17134/17668] intraday_9466.csv.gz  in=440,248,695 out=103,945,320 elapsed=227.0s

  [17135/17668] intraday_9463.csv.gz  in=440,262,227 out=103,945,320 elapsed=227.0s

  [17136/17668] intraday_9468.csv.gz  in=440,274,588 out=103,945,320 elapsed=227.1s

  [17137/17668] intraday_9469.csv.gz  in=440,287,833 out=103,945,320 elapsed=227.1s

  [17138/17668] intraday_9467.csv.gz  in=440,300,731 out=103,945,320 elapsed=227.1s

  [17139/17668] intraday_9470.csv.gz  in=440,314,978 out=103,945,320 elapsed=227.1s

  [17140/17668] intraday_9473.csv.gz  in=440,325,227 out=103,945,320 elapsed=227.1s

  [17141/17668] intraday_9472.csv.gz  in=440,336,707 out=103,945,320 elapsed=227.1s

  [17142/17668] intraday_9471.csv.gz  in=440,348,265 out=103,945,320 elapsed=227.1s

  [17143/17668] intraday_9474.csv.gz  in=440,361,279 out=103,945,320 elapsed=227.1s

  [17144/17668] intraday_9475.csv.gz  in=440,373,654 out=103,945,320 elapsed=227.1s

  [17145/17668] intraday_9476.csv.gz  in=440,385,512 out=103,945,320 elapsed=227.1s

  [17146/17668] intraday_9477.csv.gz  in=440,398,836 out=103,945,320 elapsed=227.1s

  [17147/17668] intraday_9478.csv.gz  in=440,411,859 out=103,945,320 elapsed=227.1s

  [17148/17668] intraday_9479.csv.gz  in=440,422,406 out=103,945,320 elapsed=227.1s

  [17149/17668] intraday_9480.csv.gz  in=440,436,488 out=103,945,320 elapsed=227.2s

  [17150/17668] intraday_9481.csv.gz  in=440,452,671 out=103,945,320 elapsed=227.2s

  [17151/17668] intraday_9482.csv.gz  in=440,463,170 out=103,945,320 elapsed=227.2s

  [17152/17668] intraday_9483.csv.gz  in=440,477,678 out=103,945,320 elapsed=227.2s

  [17153/17668] intraday_9484.csv.gz  in=440,489,055 out=103,945,320 elapsed=227.2s

  [17154/17668] intraday_9486.csv.gz  in=440,501,537 out=103,945,320 elapsed=227.2s

  [17155/17668] intraday_9485.csv.gz  in=440,511,880 out=103,945,320 elapsed=227.2s

  [17156/17668] intraday_9487.csv.gz  in=440,524,947 out=103,945,320 elapsed=227.2s

  [17157/17668] intraday_9488.csv.gz  in=440,537,926 out=103,945,320 elapsed=227.2s

  [17158/17668] intraday_9490.csv.gz  in=440,550,527 out=103,945,320 elapsed=227.2s

  [17159/17668] intraday_9489.csv.gz  in=440,563,090 out=103,945,320 elapsed=227.3s

  [17160/17668] intraday_9491.csv.gz  in=440,572,720 out=103,945,320 elapsed=227.3s

  [17161/17668] intraday_9492.csv.gz  in=440,584,672 out=103,945,320 elapsed=227.3s

  [17162/17668] intraday_9494.csv.gz  in=440,596,077 out=103,945,320 elapsed=227.3s

  [17163/17668] intraday_9493.csv.gz  in=440,609,210 out=103,945,320 elapsed=227.3s

  [17164/17668] intraday_9495.csv.gz  in=440,620,929 out=103,945,320 elapsed=227.3s

  [17165/17668] intraday_9496.csv.gz  in=440,631,828 out=103,945,320 elapsed=227.3s

  [17166/17668] intraday_9497.csv.gz  in=440,643,387 out=103,945,320 elapsed=227.3s

  [17167/17668] intraday_9498.csv.gz  in=440,655,792 out=103,945,320 elapsed=227.3s

  [17168/17668] intraday_9499.csv.gz  in=440,671,571 out=103,945,320 elapsed=227.3s

  [17169/17668] intraday_9502.csv.gz  in=440,684,081 out=103,945,320 elapsed=227.4s

  [17170/17668] intraday_9501.csv.gz  in=440,695,256 out=103,945,320 elapsed=227.4s

  [17171/17668] intraday_9500.csv.gz  in=440,711,197 out=103,945,320 elapsed=227.4s

  [17172/17668] intraday_9503.csv.gz  in=440,723,927 out=103,945,320 elapsed=227.4s

  [17173/17668] intraday_9504.csv.gz  in=440,737,097 out=103,945,320 elapsed=227.4s

  [17174/17668] intraday_9506.csv.gz  in=440,748,999 out=103,945,320 elapsed=227.4s

  [17175/17668] intraday_9505.csv.gz  in=440,764,617 out=103,945,320 elapsed=227.4s

  [17176/17668] intraday_9507.csv.gz  in=440,776,831 out=103,945,320 elapsed=227.4s

  [17177/17668] intraday_9508.csv.gz  in=440,790,583 out=103,945,320 elapsed=227.4s

  [17178/17668] intraday_9509.csv.gz  in=440,804,016 out=103,945,320 elapsed=227.4s

  [17179/17668] intraday_9510.csv.gz  in=440,817,017 out=103,945,320 elapsed=227.4s

  [17180/17668] intraday_9511.csv.gz  in=440,829,582 out=103,945,320 elapsed=227.4s

  [17181/17668] intraday_9512.csv.gz  in=440,842,588 out=103,945,320 elapsed=227.4s

  [17182/17668] intraday_9513.csv.gz  in=440,855,516 out=103,945,320 elapsed=227.5s

  [17183/17668] intraday_9515.csv.gz  in=440,866,100 out=103,945,320 elapsed=227.5s

  [17184/17668] intraday_9516.csv.gz  in=440,878,593 out=103,945,320 elapsed=227.5s

  [17185/17668] intraday_9514.csv.gz  in=440,891,971 out=103,945,320 elapsed=227.5s

  [17186/17668] intraday_9517.csv.gz  in=440,905,756 out=103,945,320 elapsed=227.5s

  [17187/17668] intraday_9519.csv.gz  in=440,919,047 out=103,945,320 elapsed=227.5s

  [17188/17668] intraday_9518.csv.gz  in=440,933,470 out=103,945,320 elapsed=227.5s

  [17189/17668] intraday_9520.csv.gz  in=440,945,639 out=103,945,320 elapsed=227.5s

  [17190/17668] intraday_9521.csv.gz  in=440,958,655 out=103,945,320 elapsed=227.5s

  [17191/17668] intraday_9522.csv.gz  in=440,973,899 out=103,945,320 elapsed=227.5s

  [17192/17668] intraday_9523.csv.gz  in=440,985,847 out=103,945,320 elapsed=227.6s

  [17193/17668] intraday_9525.csv.gz  in=441,000,966 out=103,945,320 elapsed=227.6s

  [17194/17668] intraday_9524.csv.gz  in=441,013,248 out=103,945,320 elapsed=227.6s

  [17195/17668] intraday_9526.csv.gz  in=441,028,244 out=103,945,320 elapsed=227.6s

  [17196/17668] intraday_9527.csv.gz  in=441,037,597 out=103,945,320 elapsed=227.6s

  [17197/17668] intraday_9528.csv.gz  in=441,050,519 out=103,945,320 elapsed=227.6s

  [17198/17668] intraday_9529.csv.gz  in=441,064,153 out=103,945,320 elapsed=227.6s

  [17199/17668] intraday_9530.csv.gz  in=441,076,119 out=103,945,320 elapsed=227.6s

  [17200/17668] intraday_9531.csv.gz  in=441,089,850 out=103,945,320 elapsed=227.6s

  [17201/17668] intraday_9532.csv.gz  in=441,105,327 out=103,945,320 elapsed=227.6s

  [17202/17668] intraday_9534.csv.gz  in=441,120,846 out=103,945,320 elapsed=227.7s

  [17203/17668] intraday_9533.csv.gz  in=441,139,064 out=103,945,320 elapsed=227.7s

  [17204/17668] intraday_9535.csv.gz  in=441,152,498 out=103,945,320 elapsed=227.7s

  [17205/17668] intraday_9536.csv.gz  in=441,164,451 out=103,945,320 elapsed=227.7s

  [17206/17668] intraday_9537.csv.gz  in=441,177,334 out=103,945,320 elapsed=227.7s

  [17207/17668] intraday_9538.csv.gz  in=441,187,452 out=103,945,320 elapsed=227.7s

  [17208/17668] intraday_9539.csv.gz  in=441,201,223 out=103,945,320 elapsed=227.7s

  [17209/17668] intraday_9540.csv.gz  in=441,211,976 out=103,945,320 elapsed=227.7s

  [17210/17668] intraday_9541.csv.gz  in=441,225,241 out=103,945,320 elapsed=227.7s

  [17211/17668] intraday_9544.csv.gz  in=441,236,275 out=103,945,320 elapsed=227.8s

  [17212/17668] intraday_9542.csv.gz  in=441,249,027 out=103,945,320 elapsed=227.8s

  [17213/17668] intraday_9543.csv.gz  in=441,264,760 out=103,945,320 elapsed=227.8s

  [17214/17668] intraday_9545.csv.gz  in=441,276,987 out=103,945,320 elapsed=227.8s

  [17215/17668] intraday_9548.csv.gz  in=441,288,245 out=103,945,320 elapsed=227.8s

  [17216/17668] intraday_9547.csv.gz  in=441,300,661 out=103,945,320 elapsed=227.8s

  [17217/17668] intraday_9546.csv.gz  in=441,312,164 out=103,945,320 elapsed=227.8s

  [17218/17668] intraday_9549.csv.gz  in=441,325,693 out=103,945,320 elapsed=227.8s

  [17219/17668] intraday_9551.csv.gz  in=441,339,508 out=103,945,320 elapsed=227.8s

  [17220/17668] intraday_9552.csv.gz  in=441,354,448 out=103,945,320 elapsed=227.8s

  [17221/17668] intraday_9553.csv.gz  in=441,367,355 out=103,945,320 elapsed=227.8s

  [17222/17668] intraday_9550.csv.gz  in=441,382,376 out=103,945,320 elapsed=227.8s

  [17223/17668] intraday_9554.csv.gz  in=441,394,231 out=103,945,320 elapsed=227.9s

  [17224/17668] intraday_9555.csv.gz  in=441,407,631 out=103,945,320 elapsed=227.9s

  [17225/17668] intraday_9556.csv.gz  in=441,419,462 out=103,945,320 elapsed=227.9s

  [17226/17668] intraday_9557.csv.gz  in=441,433,164 out=103,945,320 elapsed=227.9s

  [17227/17668] intraday_9558.csv.gz  in=441,440,547 out=103,945,320 elapsed=227.9s

  [17228/17668] intraday_9559.csv.gz  in=441,450,090 out=103,945,320 elapsed=227.9s

  [17229/17668] intraday_9560.csv.gz  in=441,461,055 out=103,945,320 elapsed=227.9s

  [17230/17668] intraday_9562.csv.gz  in=441,473,121 out=103,957,382 elapsed=227.9s

  [17231/17668] intraday_9561.csv.gz  in=441,489,598 out=103,973,324 elapsed=228.0s

  [17232/17668] intraday_9564.csv.gz  in=441,499,640 out=103,983,366 elapsed=228.0s

  [17233/17668] intraday_9563.csv.gz  in=441,512,190 out=103,995,916 elapsed=228.0s

  [17234/17668] intraday_9565.csv.gz  in=441,524,766 out=104,008,492 elapsed=228.0s

  [17235/17668] intraday_9566.csv.gz  in=441,538,291 out=104,021,864 elapsed=228.0s

  [17236/17668] intraday_9568.csv.gz  in=441,550,702 out=104,033,647 elapsed=228.0s

  [17237/17668] intraday_9569.csv.gz  in=441,563,169 out=104,046,114 elapsed=228.0s

  [17238/17668] intraday_9567.csv.gz  in=441,577,901 out=104,060,846 elapsed=228.0s

  [17239/17668] intraday_9571.csv.gz  in=441,591,374 out=104,074,319 elapsed=228.0s

  [17240/17668] intraday_9570.csv.gz  in=441,605,775 out=104,088,720 elapsed=228.1s

  [17241/17668] intraday_9572.csv.gz  in=441,618,917 out=104,101,862 elapsed=228.1s

  [17242/17668] intraday_9573.csv.gz  in=441,632,420 out=104,115,365 elapsed=228.1s

  [17243/17668] intraday_9575.csv.gz  in=441,642,945 out=104,125,890 elapsed=228.1s

  [17244/17668] intraday_9574.csv.gz  in=441,657,453 out=104,140,398 elapsed=228.1s

  [17245/17668] intraday_9576.csv.gz  in=441,668,552 out=104,151,497 elapsed=228.1s

  [17246/17668] intraday_9577.csv.gz  in=441,681,892 out=104,164,837 elapsed=228.1s

  [17247/17668] intraday_9578.csv.gz  in=441,694,620 out=104,177,565 elapsed=228.1s

  [17248/17668] intraday_9579.csv.gz  in=441,706,576 out=104,189,521 elapsed=228.1s

  [17249/17668] intraday_9580.csv.gz  in=441,717,419 out=104,200,364 elapsed=228.1s

  [17250/17668] intraday_9581.csv.gz  in=441,729,118 out=104,212,063 elapsed=228.1s

  [17251/17668] intraday_9582.csv.gz  in=441,743,930 out=104,225,008 elapsed=228.2s

  [17252/17668] intraday_9583.csv.gz  in=441,757,206 out=104,238,284 elapsed=228.2s

  [17253/17668] intraday_9585.csv.gz  in=441,769,978 out=104,251,056 elapsed=228.2s

  [17254/17668] intraday_9584.csv.gz  in=441,782,204 out=104,263,282 elapsed=228.2s

  [17255/17668] intraday_9586.csv.gz  in=441,794,339 out=104,275,417 elapsed=228.2s

  [17256/17668] intraday_9587.csv.gz  in=441,811,140 out=104,286,877 elapsed=228.2s

  [17257/17668] intraday_9589.csv.gz  in=441,823,632 out=104,299,360 elapsed=228.3s

  [17258/17668] intraday_9588.csv.gz  in=441,839,837 out=104,310,798 elapsed=228.3s

  [17259/17668] intraday_9591.csv.gz  in=441,855,230 out=104,326,191 elapsed=228.3s

  [17260/17668] intraday_9590.csv.gz  in=441,867,161 out=104,338,122 elapsed=228.3s

  [17261/17668] intraday_9592.csv.gz  in=441,880,453 out=104,351,414 elapsed=228.3s

  [17262/17668] intraday_9593.csv.gz  in=441,890,708 out=104,361,669 elapsed=228.3s

  [17263/17668] intraday_9594.csv.gz  in=441,901,074 out=104,372,035 elapsed=228.3s

  [17264/17668] intraday_9595.csv.gz  in=441,914,682 out=104,385,643 elapsed=228.3s

  [17265/17668] intraday_9596.csv.gz  in=441,926,679 out=104,397,033 elapsed=228.3s

  [17266/17668] intraday_9599.csv.gz  in=441,937,705 out=104,408,059 elapsed=228.4s

  [17267/17668] intraday_9597.csv.gz  in=441,949,778 out=104,420,132 elapsed=228.4s

  [17268/17668] intraday_9598.csv.gz  in=441,965,621 out=104,431,622 elapsed=228.4s

  [17269/17668] intraday_9600.csv.gz  in=441,977,110 out=104,441,243 elapsed=228.4s

  [17270/17668] intraday_9601.csv.gz  in=441,988,675 out=104,452,808 elapsed=228.4s

  [17271/17668] intraday_9602.csv.gz  in=442,002,445 out=104,464,778 elapsed=228.4s

  [17272/17668] intraday_9603.csv.gz  in=442,014,800 out=104,477,133 elapsed=228.4s

  [17273/17668] intraday_9605.csv.gz  in=442,030,380 out=104,490,798 elapsed=228.5s

  [17274/17668] intraday_9604.csv.gz  in=442,043,569 out=104,503,987 elapsed=228.5s

  [17275/17668] intraday_9606.csv.gz  in=442,059,738 out=104,515,338 elapsed=228.5s

  [17276/17668] intraday_9607.csv.gz  in=442,074,323 out=104,527,127 elapsed=228.5s

  [17277/17668] intraday_9608.csv.gz  in=442,085,704 out=104,538,508 elapsed=228.5s

  [17278/17668] intraday_9609.csv.gz  in=442,097,799 out=104,550,603 elapsed=228.5s

  [17279/17668] intraday_9610.csv.gz  in=442,107,780 out=104,560,584 elapsed=228.5s

  [17280/17668] intraday_9612.csv.gz  in=442,120,210 out=104,572,804 elapsed=228.5s

  [17281/17668] intraday_9611.csv.gz  in=442,132,232 out=104,584,826 elapsed=228.6s

  [17282/17668] intraday_9614.csv.gz  in=442,145,419 out=104,598,013 elapsed=228.6s

  [17283/17668] intraday_9613.csv.gz  in=442,156,744 out=104,609,338 elapsed=228.6s

  [17284/17668] intraday_9616.csv.gz  in=442,168,475 out=104,621,069 elapsed=228.6s

  [17285/17668] intraday_9615.csv.gz  in=442,180,625 out=104,633,219 elapsed=228.6s

  [17286/17668] intraday_9617.csv.gz  in=442,193,821 out=104,646,415 elapsed=228.6s

  [17287/17668] intraday_9618.csv.gz  in=442,205,423 out=104,658,017 elapsed=228.6s

  [17288/17668] intraday_9619.csv.gz  in=442,216,646 out=104,669,184 elapsed=228.6s

  [17289/17668] intraday_9621.csv.gz  in=442,229,421 out=104,681,959 elapsed=228.7s

  [17290/17668] intraday_9620.csv.gz  in=442,242,451 out=104,694,989 elapsed=228.7s

  [17291/17668] intraday_9623.csv.gz  in=442,255,025 out=104,707,563 elapsed=228.7s

  [17292/17668] intraday_9622.csv.gz  in=442,272,128 out=104,718,055 elapsed=228.7s

  [17293/17668] intraday_9624.csv.gz  in=442,283,777 out=104,729,704 elapsed=228.7s

  [17294/17668] intraday_9625.csv.gz  in=442,296,038 out=104,741,965 elapsed=228.8s

  [17295/17668] intraday_9628.csv.gz  in=442,309,512 out=104,754,346 elapsed=228.8s

  [17296/17668] intraday_9626.csv.gz  in=442,321,209 out=104,766,043 elapsed=228.8s

  [17297/17668] intraday_9627.csv.gz  in=442,336,399 out=104,781,233 elapsed=228.8s

  [17298/17668] intraday_9629.csv.gz  in=442,350,919 out=104,795,703 elapsed=228.8s

  [17299/17668] intraday_9632.csv.gz  in=442,361,910 out=104,806,694 elapsed=228.8s

  [17300/17668] intraday_9631.csv.gz  in=442,373,018 out=104,817,802 elapsed=228.8s

  [17301/17668] intraday_9630.csv.gz  in=442,394,956 out=104,829,935 elapsed=228.8s

  [17302/17668] intraday_9633.csv.gz  in=442,407,083 out=104,842,062 elapsed=228.9s

  [17303/17668] intraday_9634.csv.gz  in=442,419,715 out=104,854,694 elapsed=228.9s

  [17304/17668] intraday_9635.csv.gz  in=442,434,976 out=104,867,679 elapsed=228.9s

  [17305/17668] intraday_9636.csv.gz  in=442,447,497 out=104,880,200 elapsed=228.9s

  [17306/17668] intraday_9637.csv.gz  in=442,458,824 out=104,891,527 elapsed=228.9s

  [17307/17668] intraday_9638.csv.gz  in=442,469,839 out=104,902,542 elapsed=228.9s

  [17308/17668] intraday_9639.csv.gz  in=442,482,738 out=104,915,441 elapsed=228.9s

  [17309/17668] intraday_9641.csv.gz  in=442,495,265 out=104,927,968 elapsed=229.0s

  [17310/17668] intraday_9642.csv.gz  in=442,505,343 out=104,938,046 elapsed=229.0s

  [17311/17668] intraday_9640.csv.gz  in=442,517,231 out=104,949,934 elapsed=229.0s

  [17312/17668] intraday_9643.csv.gz  in=442,527,800 out=104,960,503 elapsed=229.0s

  [17313/17668] intraday_9644.csv.gz  in=442,539,074 out=104,971,777 elapsed=229.0s

  [17314/17668] intraday_9645.csv.gz  in=442,557,006 out=104,989,709 elapsed=229.0s

  [17315/17668] intraday_9646.csv.gz  in=442,573,228 out=105,005,931 elapsed=229.0s

  [17316/17668] intraday_9648.csv.gz  in=442,584,577 out=105,017,280 elapsed=229.1s

  [17317/17668] intraday_9647.csv.gz  in=442,596,762 out=105,029,465 elapsed=229.1s

  [17318/17668] intraday_9650.csv.gz  in=442,611,591 out=105,044,294 elapsed=229.1s

  [17319/17668] intraday_9649.csv.gz  in=442,623,683 out=105,056,386 elapsed=229.1s

  [17320/17668] intraday_9651.csv.gz  in=442,635,885 out=105,068,231 elapsed=229.1s

  [17321/17668] intraday_9653.csv.gz  in=442,646,430 out=105,078,776 elapsed=229.1s

  [17322/17668] intraday_9652.csv.gz  in=442,662,302 out=105,094,648 elapsed=229.1s

  [17323/17668] intraday_9654.csv.gz  in=442,675,560 out=105,107,906 elapsed=229.1s

  [17324/17668] intraday_9655.csv.gz  in=442,688,787 out=105,121,133 elapsed=229.2s

  [17325/17668] intraday_9656.csv.gz  in=442,701,443 out=105,133,789 elapsed=229.2s

  [17326/17668] intraday_9658.csv.gz  in=442,714,036 out=105,146,317 elapsed=229.2s

  [17327/17668] intraday_9657.csv.gz  in=442,727,637 out=105,159,918 elapsed=229.2s

  [17328/17668] intraday_9659.csv.gz  in=442,741,001 out=105,173,282 elapsed=229.2s

  [17329/17668] intraday_9660.csv.gz  in=442,752,897 out=105,185,178 elapsed=229.2s

  [17330/17668] intraday_9661.csv.gz  in=442,765,289 out=105,197,570 elapsed=229.2s

  [17331/17668] intraday_9662.csv.gz  in=442,777,856 out=105,210,137 elapsed=229.2s

  [17332/17668] intraday_9663.csv.gz  in=442,789,669 out=105,221,950 elapsed=229.2s

  [17333/17668] intraday_9664.csv.gz  in=442,804,448 out=105,235,139 elapsed=229.2s

  [17334/17668] intraday_9665.csv.gz  in=442,819,525 out=105,250,074 elapsed=229.3s

  [17335/17668] intraday_9668.csv.gz  in=442,832,321 out=105,262,870 elapsed=229.3s

  [17336/17668] intraday_9667.csv.gz  in=442,845,663 out=105,275,624 elapsed=229.3s

  [17337/17668] intraday_9666.csv.gz  in=442,861,437 out=105,289,104 elapsed=229.3s

  [17338/17668] intraday_9669.csv.gz  in=442,874,958 out=105,302,625 elapsed=229.3s

  [17339/17668] intraday_9670.csv.gz  in=442,886,001 out=105,313,646 elapsed=229.3s

  [17340/17668] intraday_9671.csv.gz  in=442,901,303 out=105,328,948 elapsed=229.3s

  [17341/17668] intraday_9674.csv.gz  in=442,912,365 out=105,340,010 elapsed=229.4s

  [17342/17668] intraday_9673.csv.gz  in=442,925,714 out=105,352,231 elapsed=229.4s

  [17343/17668] intraday_9672.csv.gz  in=442,940,040 out=105,366,557 elapsed=229.4s

  [17344/17668] intraday_9675.csv.gz  in=442,954,953 out=105,381,457 elapsed=229.4s

  [17345/17668] intraday_9676.csv.gz  in=442,967,212 out=105,393,716 elapsed=229.4s

  [17346/17668] intraday_9677.csv.gz  in=442,981,375 out=105,407,879 elapsed=229.4s

  [17347/17668] intraday_9678.csv.gz  in=442,995,737 out=105,422,241 elapsed=229.4s

  [17348/17668] intraday_9680.csv.gz  in=443,008,520 out=105,435,024 elapsed=229.5s

  [17349/17668] intraday_9679.csv.gz  in=443,026,133 out=105,452,637 elapsed=229.5s

  [17350/17668] intraday_9682.csv.gz  in=443,037,609 out=105,464,113 elapsed=229.5s

  [17351/17668] intraday_9681.csv.gz  in=443,054,482 out=105,480,986 elapsed=229.5s

  [17352/17668] intraday_9683.csv.gz  in=443,067,775 out=105,494,279 elapsed=229.5s

  [17353/17668] intraday_9685.csv.gz  in=443,080,193 out=105,506,697 elapsed=229.5s

  [17354/17668] intraday_9684.csv.gz  in=443,091,902 out=105,518,406 elapsed=229.5s

  [17355/17668] intraday_9686.csv.gz  in=443,102,880 out=105,529,384 elapsed=229.5s

  [17356/17668] intraday_9687.csv.gz  in=443,115,615 out=105,542,119 elapsed=229.5s

  [17357/17668] intraday_9688.csv.gz  in=443,129,162 out=105,554,951 elapsed=229.6s

  [17358/17668] intraday_9690.csv.gz  in=443,140,518 out=105,566,307 elapsed=229.6s

  [17359/17668] intraday_9691.csv.gz  in=443,152,821 out=105,578,610 elapsed=229.6s

  [17360/17668] intraday_9692.csv.gz  in=443,165,532 out=105,590,427 elapsed=229.6s

  [17361/17668] intraday_9689.csv.gz  in=443,181,759 out=105,606,654 elapsed=229.6s

  [17362/17668] intraday_9693.csv.gz  in=443,194,556 out=105,619,451 elapsed=229.6s

  [17363/17668] intraday_9694.csv.gz  in=443,205,748 out=105,630,623 elapsed=229.6s

  [17364/17668] intraday_9696.csv.gz  in=443,220,092 out=105,644,967 elapsed=229.7s

  [17365/17668] intraday_9697.csv.gz  in=443,234,055 out=105,658,930 elapsed=229.7s

  [17366/17668] intraday_9695.csv.gz  in=443,246,897 out=105,671,772 elapsed=229.7s

  [17367/17668] intraday_9698.csv.gz  in=443,261,524 out=105,686,399 elapsed=229.7s

  [17368/17668] intraday_9699.csv.gz  in=443,274,937 out=105,699,812 elapsed=229.7s

  [17369/17668] intraday_9700.csv.gz  in=443,287,188 out=105,712,063 elapsed=229.8s

  [17370/17668] intraday_9701.csv.gz  in=443,300,717 out=105,725,592 elapsed=229.8s

  [17371/17668] intraday_9703.csv.gz  in=443,314,169 out=105,739,044 elapsed=229.8s

  [17372/17668] intraday_9702.csv.gz  in=443,326,113 out=105,750,988 elapsed=229.8s

  [17373/17668] intraday_9704.csv.gz  in=443,334,458 out=105,759,280 elapsed=229.8s

  [17374/17668] intraday_9705.csv.gz  in=443,341,946 out=105,766,768 elapsed=229.8s

  [17375/17668] intraday_9707.csv.gz  in=443,343,593 out=105,768,415 elapsed=229.8s

  [17376/17668] intraday_9706.csv.gz  in=443,356,157 out=105,780,979 elapsed=229.8s

  [17377/17668] intraday_9708.csv.gz  in=443,356,178 out=105,780,990 elapsed=229.8s

  [17378/17668] intraday_9709.csv.gz  in=443,356,196 out=105,780,997 elapsed=229.8s

  [17379/17668] intraday_9711.csv.gz  in=443,360,335 out=105,781,167 elapsed=229.9s

  [17380/17668] intraday_9710.csv.gz  in=443,360,596 out=105,781,273 elapsed=229.9s

  [17381/17668] intraday_9712.csv.gz  in=443,360,701 out=105,781,378 elapsed=229.9s

  [17382/17668] intraday_9713.csv.gz  in=443,362,199 out=105,781,404 elapsed=229.9s

  [17383/17668] intraday_9714.csv.gz  in=443,362,251 out=105,781,431 elapsed=229.9s

  [17384/17668] intraday_9715.csv.gz  in=443,362,689 out=105,781,448 elapsed=229.9s

  [17385/17668] intraday_9717.csv.gz  in=443,362,805 out=105,781,564 elapsed=229.9s

  [17386/17668] intraday_9716.csv.gz  in=443,363,314 out=105,781,786 elapsed=229.9s

  [17387/17668] intraday_9718.csv.gz  in=443,364,708 out=105,781,815 elapsed=229.9s

  [17388/17668] intraday_9719.csv.gz  in=443,364,807 out=105,781,914 elapsed=229.9s

  [17389/17668] intraday_9720.csv.gz  in=443,369,934 out=105,782,099 elapsed=229.9s

  [17390/17668] intraday_9721.csv.gz  in=443,371,916 out=105,782,336 elapsed=229.9s

  [17391/17668] intraday_9722.csv.gz  in=443,372,142 out=105,782,427 elapsed=229.9s

  [17392/17668] intraday_9723.csv.gz  in=443,372,155 out=105,782,440 elapsed=229.9s

  [17393/17668] intraday_9725.csv.gz  in=443,372,199 out=105,782,450 elapsed=229.9s

  [17394/17668] intraday_9726.csv.gz  in=443,373,739 out=105,782,606 elapsed=229.9s

  [17395/17668] intraday_9724.csv.gz  in=443,384,139 out=105,782,611 elapsed=230.0s

  [17396/17668] intraday_9727.csv.gz  in=443,385,343 out=105,782,641 elapsed=230.0s

  [17397/17668] intraday_9728.csv.gz  in=443,386,173 out=105,782,659 elapsed=230.0s

  [17398/17668] intraday_9732.csv.gz  in=443,386,277 out=105,782,763 elapsed=230.0s

  [17399/17668] intraday_9730.csv.gz  in=443,386,323 out=105,782,809 elapsed=230.0s

  [17400/17668] intraday_9729.csv.gz  in=443,387,619 out=105,782,835 elapsed=230.0s

  [17401/17668] intraday_9731.csv.gz  in=443,387,728 out=105,782,902 elapsed=230.0s

  [17402/17668] intraday_9733.csv.gz  in=443,390,118 out=105,783,078 elapsed=230.0s

  [17403/17668] intraday_9734.csv.gz  in=443,391,326 out=105,783,167 elapsed=230.0s

  [17404/17668] intraday_9735.csv.gz  in=443,392,072 out=105,783,215 elapsed=230.0s

  [17405/17668] intraday_9738.csv.gz  in=443,392,075 out=105,783,218 elapsed=230.1s

  [17406/17668] intraday_9736.csv.gz  in=443,392,501 out=105,783,300 elapsed=230.1s

  [17407/17668] intraday_9737.csv.gz  in=443,392,935 out=105,783,366 elapsed=230.1s

  [17408/17668] intraday_9739.csv.gz  in=443,403,387 out=105,784,335 elapsed=230.1s

  [17409/17668] intraday_9741.csv.gz  in=443,416,161 out=105,797,109 elapsed=230.1s

  [17410/17668] intraday_9742.csv.gz  in=443,428,578 out=105,809,526 elapsed=230.1s

  [17411/17668] intraday_9743.csv.gz  in=443,437,801 out=105,818,749 elapsed=230.1s

  [17412/17668] intraday_9740.csv.gz  in=443,452,854 out=105,833,802 elapsed=230.1s

  [17413/17668] intraday_9744.csv.gz  in=443,464,698 out=105,845,646 elapsed=230.2s

  [17414/17668] intraday_9747.csv.gz  in=443,475,911 out=105,856,859 elapsed=230.2s

  [17415/17668] intraday_9746.csv.gz  in=443,490,074 out=105,871,022 elapsed=230.2s

  [17416/17668] intraday_9748.csv.gz  in=443,502,491 out=105,883,439 elapsed=230.2s

  [17417/17668] intraday_9745.csv.gz  in=443,518,047 out=105,898,995 elapsed=230.2s

  [17418/17668] intraday_9749.csv.gz  in=443,533,085 out=105,914,033 elapsed=230.2s

  [17419/17668] intraday_9751.csv.gz  in=443,545,533 out=105,926,481 elapsed=230.3s

  [17420/17668] intraday_9750.csv.gz  in=443,560,847 out=105,941,795 elapsed=230.3s

  [17421/17668] intraday_9752.csv.gz  in=443,573,989 out=105,954,937 elapsed=230.3s

  [17422/17668] intraday_9753.csv.gz  in=443,589,508 out=105,970,456 elapsed=230.3s

  [17423/17668] intraday_9754.csv.gz  in=443,599,235 out=105,980,183 elapsed=230.3s

  [17424/17668] intraday_9755.csv.gz  in=443,610,992 out=105,991,940 elapsed=230.3s

  [17425/17668] intraday_9756.csv.gz  in=443,623,262 out=106,004,210 elapsed=230.3s

  [17426/17668] intraday_9758.csv.gz  in=443,634,522 out=106,015,470 elapsed=230.3s

  [17427/17668] intraday_9757.csv.gz  in=443,648,718 out=106,029,666 elapsed=230.4s

  [17428/17668] intraday_9759.csv.gz  in=443,659,729 out=106,040,677 elapsed=230.4s

  [17429/17668] intraday_9760.csv.gz  in=443,671,603 out=106,052,551 elapsed=230.4s

  [17430/17668] intraday_9761.csv.gz  in=443,685,630 out=106,066,578 elapsed=230.4s

  [17431/17668] intraday_9762.csv.gz  in=443,697,973 out=106,078,921 elapsed=230.4s

  [17432/17668] intraday_9764.csv.gz  in=443,711,177 out=106,092,125 elapsed=230.4s

  [17433/17668] intraday_9763.csv.gz  in=443,723,958 out=106,104,906 elapsed=230.4s

  [17434/17668] intraday_9766.csv.gz  in=443,736,435 out=106,117,383 elapsed=230.4s

  [17435/17668] intraday_9767.csv.gz  in=443,748,157 out=106,129,105 elapsed=230.5s

  [17436/17668] intraday_9765.csv.gz  in=443,760,378 out=106,141,326 elapsed=230.5s

  [17437/17668] intraday_9769.csv.gz  in=443,773,196 out=106,154,144 elapsed=230.5s

  [17438/17668] intraday_9768.csv.gz  in=443,784,213 out=106,165,161 elapsed=230.5s

  [17439/17668] intraday_9770.csv.gz  in=443,798,392 out=106,179,340 elapsed=230.5s

  [17440/17668] intraday_9771.csv.gz  in=443,813,100 out=106,194,048 elapsed=230.5s

  [17441/17668] intraday_9773.csv.gz  in=443,823,973 out=106,204,921 elapsed=230.6s

  [17442/17668] intraday_9772.csv.gz  in=443,834,774 out=106,215,722 elapsed=230.6s

  [17443/17668] intraday_9774.csv.gz  in=443,848,081 out=106,229,029 elapsed=230.6s

  [17444/17668] intraday_9775.csv.gz  in=443,861,654 out=106,242,602 elapsed=230.6s

  [17445/17668] intraday_9776.csv.gz  in=443,872,148 out=106,253,096 elapsed=230.6s

  [17446/17668] intraday_9778.csv.gz  in=443,882,371 out=106,263,319 elapsed=230.6s

  [17447/17668] intraday_9777.csv.gz  in=443,894,897 out=106,275,845 elapsed=230.6s

  [17448/17668] intraday_9779.csv.gz  in=443,905,216 out=106,286,164 elapsed=230.6s

  [17449/17668] intraday_9780.csv.gz  in=443,916,048 out=106,296,996 elapsed=230.6s

  [17450/17668] intraday_9781.csv.gz  in=443,927,126 out=106,308,074 elapsed=230.6s

  [17451/17668] intraday_9782.csv.gz  in=443,940,074 out=106,321,022 elapsed=230.7s

  [17452/17668] intraday_9784.csv.gz  in=443,952,905 out=106,333,853 elapsed=230.7s

  [17453/17668] intraday_9785.csv.gz  in=443,966,004 out=106,346,952 elapsed=230.7s

  [17454/17668] intraday_9786.csv.gz  in=443,977,526 out=106,358,474 elapsed=230.7s

  [17455/17668] intraday_9783.csv.gz  in=443,990,249 out=106,371,197 elapsed=230.7s

  [17456/17668] intraday_9787.csv.gz  in=444,001,514 out=106,382,462 elapsed=230.7s

  [17457/17668] intraday_9788.csv.gz  in=444,014,354 out=106,395,302 elapsed=230.7s

  [17458/17668] intraday_9789.csv.gz  in=444,025,044 out=106,405,992 elapsed=230.8s

  [17459/17668] intraday_9790.csv.gz  in=444,036,365 out=106,417,313 elapsed=230.8s

  [17460/17668] intraday_9791.csv.gz  in=444,047,858 out=106,428,806 elapsed=230.8s

  [17461/17668] intraday_9792.csv.gz  in=444,058,622 out=106,439,570 elapsed=230.8s

  [17462/17668] intraday_9793.csv.gz  in=444,071,981 out=106,452,929 elapsed=230.8s

  [17463/17668] intraday_9794.csv.gz  in=444,082,587 out=106,463,535 elapsed=230.8s

  [17464/17668] intraday_9795.csv.gz  in=444,095,912 out=106,476,860 elapsed=230.8s

  [17465/17668] intraday_9796.csv.gz  in=444,108,231 out=106,489,179 elapsed=230.8s

  [17466/17668] intraday_9797.csv.gz  in=444,120,622 out=106,501,570 elapsed=230.9s

  [17467/17668] intraday_9798.csv.gz  in=444,132,421 out=106,513,369 elapsed=230.9s

  [17468/17668] intraday_9799.csv.gz  in=444,144,663 out=106,525,611 elapsed=230.9s

  [17469/17668] intraday_9800.csv.gz  in=444,156,337 out=106,537,285 elapsed=230.9s

  [17470/17668] intraday_9801.csv.gz  in=444,169,425 out=106,550,373 elapsed=230.9s

  [17471/17668] intraday_9802.csv.gz  in=444,180,431 out=106,561,379 elapsed=230.9s

  [17472/17668] intraday_9803.csv.gz  in=444,193,100 out=106,574,048 elapsed=230.9s

  [17473/17668] intraday_9805.csv.gz  in=444,204,335 out=106,585,283 elapsed=230.9s

  [17474/17668] intraday_9804.csv.gz  in=444,216,677 out=106,597,625 elapsed=230.9s

  [17475/17668] intraday_9806.csv.gz  in=444,231,769 out=106,612,717 elapsed=231.0s

  [17476/17668] intraday_9807.csv.gz  in=444,244,462 out=106,625,410 elapsed=231.0s

  [17477/17668] intraday_9808.csv.gz  in=444,259,214 out=106,640,162 elapsed=231.0s

  [17478/17668] intraday_9809.csv.gz  in=444,271,564 out=106,652,512 elapsed=231.0s

  [17479/17668] intraday_9810.csv.gz  in=444,284,057 out=106,665,005 elapsed=231.0s

  [17480/17668] intraday_9812.csv.gz  in=444,296,397 out=106,677,345 elapsed=231.0s

  [17481/17668] intraday_9813.csv.gz  in=444,309,254 out=106,690,202 elapsed=231.0s

  [17482/17668] intraday_9811.csv.gz  in=444,319,833 out=106,700,781 elapsed=231.0s

  [17483/17668] intraday_9814.csv.gz  in=444,334,041 out=106,714,989 elapsed=231.0s

  [17484/17668] intraday_9815.csv.gz  in=444,346,221 out=106,727,169 elapsed=231.0s

  [17485/17668] intraday_9817.csv.gz  in=444,356,343 out=106,737,291 elapsed=231.1s

  [17486/17668] intraday_9816.csv.gz  in=444,370,274 out=106,751,222 elapsed=231.1s

  [17487/17668] intraday_9819.csv.gz  in=444,383,166 out=106,764,114 elapsed=231.1s

  [17488/17668] intraday_9818.csv.gz  in=444,396,599 out=106,777,547 elapsed=231.1s

  [17489/17668] intraday_9821.csv.gz  in=444,408,374 out=106,789,322 elapsed=231.1s

  [17490/17668] intraday_9820.csv.gz  in=444,419,674 out=106,800,622 elapsed=231.1s

  [17491/17668] intraday_9822.csv.gz  in=444,430,065 out=106,811,013 elapsed=231.1s

  [17492/17668] intraday_9823.csv.gz  in=444,441,457 out=106,822,405 elapsed=231.2s

  [17493/17668] intraday_9824.csv.gz  in=444,453,257 out=106,834,205 elapsed=231.2s

  [17494/17668] intraday_9826.csv.gz  in=444,469,349 out=106,850,297 elapsed=231.2s

  [17495/17668] intraday_9825.csv.gz  in=444,485,915 out=106,866,863 elapsed=231.2s

  [17496/17668] intraday_9827.csv.gz  in=444,497,098 out=106,878,046 elapsed=231.2s

  [17497/17668] intraday_9828.csv.gz  in=444,510,184 out=106,891,132 elapsed=231.2s

  [17498/17668] intraday_9829.csv.gz  in=444,524,816 out=106,905,764 elapsed=231.2s

  [17499/17668] intraday_9831.csv.gz  in=444,539,528 out=106,920,476 elapsed=231.2s

  [17500/17668] intraday_9830.csv.gz  in=444,552,438 out=106,933,386 elapsed=231.2s

  [17501/17668] intraday_9832.csv.gz  in=444,564,033 out=106,944,981 elapsed=231.3s

  [17502/17668] intraday_9833.csv.gz  in=444,576,391 out=106,957,339 elapsed=231.3s

  [17503/17668] intraday_9834.csv.gz  in=444,590,018 out=106,970,966 elapsed=231.3s

  [17504/17668] intraday_9835.csv.gz  in=444,602,891 out=106,983,839 elapsed=231.3s

  [17505/17668] intraday_9836.csv.gz  in=444,616,431 out=106,997,379 elapsed=231.3s

  [17506/17668] intraday_9837.csv.gz  in=444,629,470 out=107,010,418 elapsed=231.3s

  [17507/17668] intraday_9838.csv.gz  in=444,641,815 out=107,022,763 elapsed=231.3s

  [17508/17668] intraday_9839.csv.gz  in=444,654,590 out=107,035,538 elapsed=231.4s

  [17509/17668] intraday_9840.csv.gz  in=444,668,144 out=107,049,092 elapsed=231.4s

  [17510/17668] intraday_9841.csv.gz  in=444,680,025 out=107,060,973 elapsed=231.4s

  [17511/17668] intraday_9842.csv.gz  in=444,691,228 out=107,072,176 elapsed=231.4s

  [17512/17668] intraday_9843.csv.gz  in=444,704,894 out=107,085,842 elapsed=231.4s

  [17513/17668] intraday_9844.csv.gz  in=444,719,631 out=107,100,579 elapsed=231.4s

  [17514/17668] intraday_9845.csv.gz  in=444,733,565 out=107,114,513 elapsed=231.4s

  [17515/17668] intraday_9846.csv.gz  in=444,746,696 out=107,127,644 elapsed=231.4s

  [17516/17668] intraday_9847.csv.gz  in=444,759,506 out=107,140,454 elapsed=231.5s

  [17517/17668] intraday_9848.csv.gz  in=444,775,882 out=107,156,830 elapsed=231.5s

  [17518/17668] intraday_9849.csv.gz  in=444,787,000 out=107,167,948 elapsed=231.5s

  [17519/17668] intraday_9850.csv.gz  in=444,799,333 out=107,180,281 elapsed=231.5s

  [17520/17668] intraday_9851.csv.gz  in=444,813,904 out=107,194,852 elapsed=231.5s

  [17521/17668] intraday_9852.csv.gz  in=444,828,388 out=107,209,336 elapsed=231.5s

  [17522/17668] intraday_9853.csv.gz  in=444,838,457 out=107,219,405 elapsed=231.5s

  [17523/17668] intraday_9855.csv.gz  in=444,850,882 out=107,231,830 elapsed=231.5s

  [17524/17668] intraday_9854.csv.gz  in=444,864,358 out=107,245,306 elapsed=231.5s

  [17525/17668] intraday_9856.csv.gz  in=444,877,313 out=107,258,261 elapsed=231.5s

  [17526/17668] intraday_9857.csv.gz  in=444,892,530 out=107,273,478 elapsed=231.6s

  [17527/17668] intraday_9858.csv.gz  in=444,907,981 out=107,288,929 elapsed=231.6s

  [17528/17668] intraday_9859.csv.gz  in=444,925,267 out=107,306,215 elapsed=231.6s

  [17529/17668] intraday_9861.csv.gz  in=444,937,315 out=107,318,263 elapsed=231.6s

  [17530/17668] intraday_9860.csv.gz  in=444,953,060 out=107,334,008 elapsed=231.6s

  [17531/17668] intraday_9862.csv.gz  in=444,966,124 out=107,347,072 elapsed=231.6s

  [17532/17668] intraday_9863.csv.gz  in=444,978,652 out=107,359,600 elapsed=231.6s

  [17533/17668] intraday_9864.csv.gz  in=444,989,049 out=107,369,997 elapsed=231.6s

  [17534/17668] intraday_9865.csv.gz  in=445,002,442 out=107,383,390 elapsed=231.7s

  [17535/17668] intraday_9866.csv.gz  in=445,013,389 out=107,394,337 elapsed=231.7s

  [17536/17668] intraday_9867.csv.gz  in=445,028,396 out=107,409,344 elapsed=231.7s

  [17537/17668] intraday_9869.csv.gz  in=445,043,680 out=107,424,628 elapsed=231.7s

  [17538/17668] intraday_9868.csv.gz  in=445,056,971 out=107,437,919 elapsed=231.7s

  [17539/17668] intraday_9871.csv.gz  in=445,067,991 out=107,448,939 elapsed=231.7s

  [17540/17668] intraday_9870.csv.gz  in=445,081,054 out=107,462,002 elapsed=231.7s

  [17541/17668] intraday_9872.csv.gz  in=445,092,826 out=107,473,774 elapsed=231.7s

  [17542/17668] intraday_9873.csv.gz  in=445,106,833 out=107,487,781 elapsed=231.8s

  [17543/17668] intraday_9874.csv.gz  in=445,117,339 out=107,498,287 elapsed=231.8s

  [17544/17668] intraday_9875.csv.gz  in=445,131,642 out=107,512,590 elapsed=231.8s

  [17545/17668] intraday_9876.csv.gz  in=445,146,023 out=107,526,971 elapsed=231.8s

  [17546/17668] intraday_9877.csv.gz  in=445,159,964 out=107,540,912 elapsed=231.8s

  [17547/17668] intraday_9879.csv.gz  in=445,172,169 out=107,553,117 elapsed=231.8s

  [17548/17668] intraday_9880.csv.gz  in=445,184,557 out=107,565,505 elapsed=231.8s

  [17549/17668] intraday_9878.csv.gz  in=445,198,986 out=107,579,934 elapsed=231.9s

  [17550/17668] intraday_9881.csv.gz  in=445,213,151 out=107,594,099 elapsed=231.9s

  [17551/17668] intraday_9882.csv.gz  in=445,224,005 out=107,604,953 elapsed=231.9s

  [17552/17668] intraday_9883.csv.gz  in=445,237,314 out=107,618,262 elapsed=231.9s

  [17553/17668] intraday_9884.csv.gz  in=445,244,318 out=107,625,266 elapsed=231.9s

  [17554/17668] intraday_9886.csv.gz  in=445,254,904 out=107,635,852 elapsed=231.9s

  [17555/17668] intraday_9885.csv.gz  in=445,263,278 out=107,644,226 elapsed=231.9s

  [17556/17668] intraday_9887.csv.gz  in=445,277,873 out=107,658,821 elapsed=232.0s

  [17557/17668] intraday_9889.csv.gz  in=445,289,495 out=107,670,443 elapsed=232.0s

  [17558/17668] intraday_9888.csv.gz  in=445,301,762 out=107,682,710 elapsed=232.0s

  [17559/17668] intraday_9890.csv.gz  in=445,312,050 out=107,692,998 elapsed=232.0s

  [17560/17668] intraday_9891.csv.gz  in=445,323,614 out=107,704,562 elapsed=232.0s

  [17561/17668] intraday_9892.csv.gz  in=445,338,473 out=107,719,421 elapsed=232.0s

  [17562/17668] intraday_9893.csv.gz  in=445,352,950 out=107,733,898 elapsed=232.0s

  [17563/17668] intraday_9894.csv.gz  in=445,363,581 out=107,744,529 elapsed=232.0s

  [17564/17668] intraday_9895.csv.gz  in=445,375,461 out=107,756,409 elapsed=232.0s

  [17565/17668] intraday_9896.csv.gz  in=445,390,157 out=107,771,105 elapsed=232.1s

  [17566/17668] intraday_9897.csv.gz  in=445,404,010 out=107,784,958 elapsed=232.1s

  [17567/17668] intraday_9898.csv.gz  in=445,416,005 out=107,796,953 elapsed=232.1s

  [17568/17668] intraday_9899.csv.gz  in=445,429,847 out=107,810,795 elapsed=232.1s

  [17569/17668] intraday_9901.csv.gz  in=445,440,401 out=107,821,349 elapsed=232.1s

  [17570/17668] intraday_9900.csv.gz  in=445,455,934 out=107,834,386 elapsed=232.1s

  [17571/17668] intraday_9903.csv.gz  in=445,469,129 out=107,845,555 elapsed=232.1s

  [17572/17668] intraday_9902.csv.gz  in=445,482,171 out=107,858,597 elapsed=232.1s

  [17573/17668] intraday_9904.csv.gz  in=445,498,719 out=107,875,145 elapsed=232.2s

  [17574/17668] intraday_9905.csv.gz  in=445,511,441 out=107,887,867 elapsed=232.2s

  [17575/17668] intraday_9906.csv.gz  in=445,522,188 out=107,898,614 elapsed=232.2s

  [17576/17668] intraday_9907.csv.gz  in=445,537,105 out=107,913,531 elapsed=232.2s

  [17577/17668] intraday_9908.csv.gz  in=445,550,809 out=107,927,235 elapsed=232.2s

  [17578/17668] intraday_9909.csv.gz  in=445,565,244 out=107,940,358 elapsed=232.2s

  [17579/17668] intraday_9910.csv.gz  in=445,578,799 out=107,953,422 elapsed=232.3s

  [17580/17668] intraday_9911.csv.gz  in=445,591,517 out=107,966,140 elapsed=232.3s

  [17581/17668] intraday_9912.csv.gz  in=445,603,690 out=107,978,313 elapsed=232.3s

  [17582/17668] intraday_9913.csv.gz  in=445,614,830 out=107,989,453 elapsed=232.3s

  [17583/17668] intraday_9914.csv.gz  in=445,626,596 out=108,001,219 elapsed=232.3s

  [17584/17668] intraday_9915.csv.gz  in=445,636,701 out=108,011,324 elapsed=232.3s

  [17585/17668] intraday_9918.csv.gz  in=445,649,783 out=108,024,406 elapsed=232.3s

  [17586/17668] intraday_9917.csv.gz  in=445,665,713 out=108,040,336 elapsed=232.4s

  [17587/17668] intraday_9916.csv.gz  in=445,680,461 out=108,055,008 elapsed=232.4s

  [17588/17668] intraday_9919.csv.gz  in=445,691,760 out=108,066,307 elapsed=232.4s

  [17589/17668] intraday_9920.csv.gz  in=445,702,882 out=108,077,429 elapsed=232.4s

  [17590/17668] intraday_9921.csv.gz  in=445,715,033 out=108,089,580 elapsed=232.4s

  [17591/17668] intraday_9922.csv.gz  in=445,729,211 out=108,103,758 elapsed=232.4s

  [17592/17668] intraday_9923.csv.gz  in=445,740,300 out=108,114,847 elapsed=232.4s

  [17593/17668] intraday_9924.csv.gz  in=445,752,985 out=108,127,532 elapsed=232.4s

  [17594/17668] intraday_9925.csv.gz  in=445,763,947 out=108,138,494 elapsed=232.4s

  [17595/17668] intraday_9927.csv.gz  in=445,775,173 out=108,149,720 elapsed=232.5s

  [17596/17668] intraday_9926.csv.gz  in=445,801,748 out=108,160,733 elapsed=232.5s

  [17597/17668] intraday_9928.csv.gz  in=445,812,926 out=108,171,911 elapsed=232.5s

  [17598/17668] intraday_9929.csv.gz  in=445,826,329 out=108,185,314 elapsed=232.5s

  [17599/17668] intraday_9930.csv.gz  in=445,837,926 out=108,196,911 elapsed=232.5s

  [17600/17668] intraday_9931.csv.gz  in=445,851,878 out=108,210,863 elapsed=232.5s

  [17601/17668] intraday_9932.csv.gz  in=445,864,594 out=108,223,579 elapsed=232.6s

  [17602/17668] intraday_9933.csv.gz  in=445,875,327 out=108,234,312 elapsed=232.6s

  [17603/17668] intraday_9934.csv.gz  in=445,887,304 out=108,246,289 elapsed=232.6s

  [17604/17668] intraday_9935.csv.gz  in=445,899,031 out=108,257,856 elapsed=232.6s

  [17605/17668] intraday_9936.csv.gz  in=445,909,817 out=108,268,642 elapsed=232.6s

  [17606/17668] intraday_9938.csv.gz  in=445,920,787 out=108,279,612 elapsed=232.6s

  [17607/17668] intraday_9939.csv.gz  in=445,932,736 out=108,291,561 elapsed=232.6s

  [17608/17668] intraday_9937.csv.gz  in=445,943,744 out=108,302,569 elapsed=232.6s

  [17609/17668] intraday_9940.csv.gz  in=445,957,331 out=108,316,156 elapsed=232.7s

  [17610/17668] intraday_9941.csv.gz  in=445,969,328 out=108,328,153 elapsed=232.7s

  [17611/17668] intraday_9942.csv.gz  in=445,983,788 out=108,340,686 elapsed=232.7s

  [17612/17668] intraday_9943.csv.gz  in=445,997,265 out=108,354,163 elapsed=232.7s

  [17613/17668] intraday_9944.csv.gz  in=446,009,822 out=108,366,720 elapsed=232.7s

  [17614/17668] intraday_9945.csv.gz  in=446,020,803 out=108,377,701 elapsed=232.7s

  [17615/17668] intraday_9946.csv.gz  in=446,032,679 out=108,389,577 elapsed=232.7s

  [17616/17668] intraday_9947.csv.gz  in=446,044,971 out=108,401,869 elapsed=232.7s

  [17617/17668] intraday_9948.csv.gz  in=446,059,034 out=108,414,056 elapsed=232.7s

  [17618/17668] intraday_9949.csv.gz  in=446,071,532 out=108,426,554 elapsed=232.7s

  [17619/17668] intraday_9950.csv.gz  in=446,082,919 out=108,437,941 elapsed=232.8s

  [17620/17668] intraday_9952.csv.gz  in=446,092,753 out=108,447,775 elapsed=232.8s

  [17621/17668] intraday_9951.csv.gz  in=446,104,412 out=108,459,434 elapsed=232.8s

  [17622/17668] intraday_9953.csv.gz  in=446,123,623 out=108,476,260 elapsed=232.8s

  [17623/17668] intraday_9954.csv.gz  in=446,136,656 out=108,489,293 elapsed=232.8s

  [17624/17668] intraday_9956.csv.gz  in=446,150,073 out=108,502,710 elapsed=232.8s

  [17625/17668] intraday_9955.csv.gz  in=446,164,946 out=108,517,583 elapsed=232.8s

  [17626/17668] intraday_9957.csv.gz  in=446,177,367 out=108,530,004 elapsed=232.8s

  [17627/17668] intraday_9958.csv.gz  in=446,187,163 out=108,539,800 elapsed=232.9s

  [17628/17668] intraday_9959.csv.gz  in=446,200,121 out=108,552,758 elapsed=232.9s

  [17629/17668] intraday_9960.csv.gz  in=446,212,957 out=108,565,594 elapsed=232.9s

  [17630/17668] intraday_9961.csv.gz  in=446,227,086 out=108,579,723 elapsed=232.9s

  [17631/17668] intraday_9962.csv.gz  in=446,239,484 out=108,592,121 elapsed=232.9s

  [17632/17668] intraday_9963.csv.gz  in=446,252,203 out=108,604,840 elapsed=232.9s

  [17633/17668] intraday_9964.csv.gz  in=446,263,342 out=108,615,979 elapsed=232.9s

  [17634/17668] intraday_9965.csv.gz  in=446,276,992 out=108,629,629 elapsed=232.9s

  [17635/17668] intraday_9966.csv.gz  in=446,288,040 out=108,640,677 elapsed=233.0s

  [17636/17668] intraday_9967.csv.gz  in=446,299,996 out=108,652,633 elapsed=233.0s

  [17637/17668] intraday_9968.csv.gz  in=446,311,555 out=108,664,192 elapsed=233.0s

  [17638/17668] intraday_9969.csv.gz  in=446,320,710 out=108,673,347 elapsed=233.0s

  [17639/17668] intraday_9970.csv.gz  in=446,331,263 out=108,683,900 elapsed=233.0s

  [17640/17668] intraday_9971.csv.gz  in=446,358,471 out=108,699,249 elapsed=233.0s

  [17641/17668] intraday_9973.csv.gz  in=446,372,923 out=108,713,701 elapsed=233.0s

  [17642/17668] intraday_9974.csv.gz  in=446,384,841 out=108,725,619 elapsed=233.1s

  [17643/17668] intraday_9975.csv.gz  in=446,395,802 out=108,736,580 elapsed=233.1s

  [17644/17668] intraday_9972.csv.gz  in=446,413,712 out=108,754,490 elapsed=233.1s

  [17645/17668] intraday_9976.csv.gz  in=446,429,938 out=108,770,716 elapsed=233.1s

  [17646/17668] intraday_9979.csv.gz  in=446,440,824 out=108,781,602 elapsed=233.1s

  [17647/17668] intraday_9978.csv.gz  in=446,456,992 out=108,797,770 elapsed=233.1s

  [17648/17668] intraday_9980.csv.gz  in=446,468,643 out=108,809,421 elapsed=233.1s

  [17649/17668] intraday_9977.csv.gz  in=446,488,842 out=108,821,565 elapsed=233.1s

  [17650/17668] intraday_9981.csv.gz  in=446,502,158 out=108,834,881 elapsed=233.1s

  [17651/17668] intraday_9982.csv.gz  in=446,515,478 out=108,848,201 elapsed=233.1s

  [17652/17668] intraday_9983.csv.gz  in=446,527,885 out=108,860,608 elapsed=233.2s

  [17653/17668] intraday_9985.csv.gz  in=446,540,247 out=108,872,970 elapsed=233.2s

  [17654/17668] intraday_9984.csv.gz  in=446,553,932 out=108,886,655 elapsed=233.2s

  [17655/17668] intraday_9986.csv.gz  in=446,565,540 out=108,898,263 elapsed=233.2s

  [17656/17668] intraday_9987.csv.gz  in=446,578,729 out=108,911,452 elapsed=233.2s

  [17657/17668] intraday_9988.csv.gz  in=446,590,281 out=108,923,004 elapsed=233.2s

  [17658/17668] intraday_9989.csv.gz  in=446,601,303 out=108,934,026 elapsed=233.2s

  [17659/17668] intraday_9990.csv.gz  in=446,613,680 out=108,946,403 elapsed=233.2s

  [17660/17668] intraday_9992.csv.gz  in=446,626,306 out=108,959,029 elapsed=233.3s

  [17661/17668] intraday_9991.csv.gz  in=446,643,022 out=108,975,745 elapsed=233.3s

  [17662/17668] intraday_9993.csv.gz  in=446,657,514 out=108,990,237 elapsed=233.3s

  [17663/17668] intraday_9994.csv.gz  in=446,668,126 out=109,000,812 elapsed=233.3s

  [17664/17668] intraday_9995.csv.gz  in=446,684,011 out=109,016,687 elapsed=233.3s

  [17665/17668] intraday_9996.csv.gz  in=446,695,677 out=109,028,353 elapsed=233.3s

  [17666/17668] intraday_9998.csv.gz  in=446,709,008 out=109,041,684 elapsed=233.4s

  [17667/17668] intraday_9997.csv.gz  in=446,721,407 out=109,054,083 elapsed=233.4s

  [17668/17668] intraday_9999.csv.gz  in=446,736,490 out=109,067,647 elapsed=233.4s

✅ DONE  in=446,736,490 → out=109,067,647  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 243.4s

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [20]:
def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,      # лишено для сумісності виклику
    *,
    max_workers: int = 4,
) -> pd.DataFrame:
    """Денні open (перший бар 09:30–09:35) і close (останній бар 15:55–15:59).

    Раніше кожен відібраний рядок проходив через itertuples + оновлення python-словника;
    тепер редукція повністю векторна (sort + drop_duplicates у pyarrow/pandas).
    Клітинка 19 уже рахує це за один прохід — ця функція лишається як самостійний шлях.
    """
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    open_parts, close_parts = [], []
    lock = threading.Lock()

    def _handle(path):
        reader = _open_intraday_csv(path, 64 << 20)
        lo, lc = [], []
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            o_df, c_df = _oc_from_table(pa.Table.from_batches([rb]))
            if len(o_df):
                lo.append(o_df)
            if len(c_df):
                lc.append(c_df)
        with lock:
            open_parts.extend(lo)
            close_parts.extend(lc)

    if max_workers and max_workers > 1:
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            list(ex.map(_handle, files))
    else:
        for p in files:
            _handle(p)

    out = _finalize_oc(open_parts, close_parts)

    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)
    return out

In [21]:
# oc.parquet уже побудовано в клітинці 19 (той самий прохід по файлах).
# Перебудовуємо лише якщо його немає.
_oc_path = str(WORK_DIR / "oc.parquet")
if os.path.exists(_oc_path):
    df_oc = pd.read_parquet(_oc_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(BATCH_DIR), out_path=_oc_path)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [22]:
import os
import gc
import time
import pandas as pd
import numpy as np

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def _prep_oc_prev_close(df_oc: pd.DataFrame) -> pd.DataFrame:
    """['ticker','date','open','prev_close','same_day_close'], date — звичайний рядок 'YYYY-MM-DD'.

    'prev_close' — close ПОПЕРЕДНЬОГО торгового дня (до 16:01).
    'same_day_close' — close ЦЬОГО Ж дня (від 16:01, коли сесія вже
    закрилась о 16:00 і референс-клоуз має перерахуватись на
    сьогоднішній)."""
    oc = df_oc[["ticker", "date", "open", "close"]].copy()
    oc["ticker"] = oc["ticker"].astype(str)
    oc["date"] = oc["date"].astype(str).str.slice(0, 10)
    oc = oc.sort_values(["ticker", "date"], kind="stable")
    oc["prev_close"] = oc.groupby("ticker", sort=False)["close"].shift(1)
    oc = oc.rename(columns={"close": "same_day_close"})
    return oc[["ticker", "date", "open", "prev_close", "same_day_close"]].reset_index(drop=True)


def _rebase_prev_close_after_session_close(df: pd.DataFrame,
                                           dt_col: str = "dt",
                                           prev_close_col: str = "prev_close",
                                           same_day_close_col: str = "same_day_close",
                                           close_boundary: str = "16:01") -> "pd.Series":
    """Від close_boundary (16:01, бо сесія закривається о 16:00) референс-клоуз
    кожного стака перераховується на клоуз ЦЬОГО Ж дня замість
    вчорашнього (інакше з 16:01 до півночі все й далі рахувалось би
    відносно вчорашнього клоуза). Час береться зрізом рядка 'dt'
    (без парсингу дат, як і решта пайплайну)."""
    time_str = df[dt_col].astype(str).str.slice(11, 16)
    after_close = time_str >= close_boundary
    return np.where(after_close, df[same_day_close_col], df[prev_close_col])


def _date_from_dt(s: pd.Series) -> pd.Series:
    """'YYYY-MM-DD' з 'dt'. Для рядкового dt це зріз (C-рівень), без парсингу дат."""
    if pd.api.types.is_string_dtype(s) or s.dtype == object:
        return s.astype(str).str.slice(0, 10)
    return s.dt.strftime("%Y-%m-%d")


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame,
                                        _oc_prepared: Optional[pd.DataFrame] = None,
                                        sort_out: bool = False) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' — референс-клоуз,
    відносно якого рахується Stack%.
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']

    Референс-клоуз перераховується о 16:01: до цього часу — клоуз попереднього
    дня, від 16:01 (сесія вже закрилась о 16:00) — клоуз ЦЬОГО Ж дня. Інакше з
    16:01 до півночі рядки й далі рахувались б відносно вчорашнього клоуза.

    Прискорення проти попередньої версії:
      - 'dt' лишається рядком: ні pd.to_datetime, ні .dt.date (це були python-об'єкти
        на кожен рядок — найдорожча операція в усьому пайплайні);
      - prev_close рахується ОДИН раз (передається через _oc_prepared), а не на кожен батч;
      - без per-batch sort_values (фінальне сортування робить клітинка 47).
    """
    right = _oc_prepared if _oc_prepared is not None else _prep_oc_prev_close(df_oc)
    out = df_intraday
    out = out[out["dt"].notna()]
    out = out.assign(date=_date_from_dt(out["dt"]))
    out = out.merge(right, on=["ticker", "date"], how="left")
    out["prev_close"] = _rebase_prev_close_after_session_close(out)
    out = out.drop(columns=["same_day_close"])
    if sort_out:
        out = out.sort_values(["ticker", "dt"], kind="stable").reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    sort_out: bool = False,
):
    """
    Читає великий Parquet батчами і мерджить денні open/prev_close з oc.parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    df_oc = pd.read_parquet(oc_parquet_path)
    missing = {"ticker", "date", "open", "close"} - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")
    oc_prepared = _prep_oc_prev_close(df_oc)      # рахуємо ОДИН раз, не на кожен батч

    if os.path.exists(out_path):
        os.remove(out_path)
    if not out_path.endswith((".csv", ".gz", ".parquet")):
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0

    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}", flush=True)

    for batch_idx, batch in enumerate(pf.iter_batches(batch_size=batch_rows, columns=cols), 1):
        df_batch = batch.to_pandas()
        df_enriched = enrich_with_day_open_and_prev_close(
            df_batch, None, _oc_prepared=oc_prepared, sort_out=sort_out)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched, preserve_index=False)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            df_enriched.to_csv(
                out_path, index=False, mode="a", header=(total_rows == 0),
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_enriched)
        if batch_idx % log_every_batches == 0:
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s", flush=True)


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [23]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
# print("Результат у файлі:", out_path)

In [24]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    Обчислення в numpy (без проміжних pandas-Series і .replace), без gc на кожен батч.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  "
          f"batch_rows≈{batch_rows:,}  using={value_col}", flush=True)

    for batches, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for c in ("prev_close", value_col):
            if c not in df.columns:
                raise KeyError(f"У вхідному файлі немає колонки '{c}'.")

        num = pd.to_numeric(df[value_col], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0   # 0 → NaN, без ділення на 0
        if round_to is not None:
            pct = np.round(pct, int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s", flush=True)
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [25]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
# print("Готово:", out_path)

In [26]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [27]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [28]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    df = pq.read_table(path).to_pandas()
    inv = {c.strip().lower(): c for c in df.columns}

    has_api = ("x_ticker" in inv) and ("y_ticker" in inv)
    has_direct = ("ticker" in inv) and ("bench" in inv)
    if not (has_api or has_direct):
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={inv["x_ticker"]: "ticker", inv["y_ticker"]: "bench"})
    else:
        df = df.rename(columns={inv["ticker"]: "ticker", inv["bench"]: "bench"})

    for c in ("corr", "beta"):
        if c in inv:
            df = df.rename(columns={inv[c]: c})
        else:
            df[c] = pd.NA

    df = df[["ticker", "bench", "corr", "beta"]].copy()
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"] = df["bench"].astype(str).str.strip().str.upper()
    df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    return (df.sort_values(["ticker", "corr"], ascending=[True, False])
              .drop_duplicates(subset=["ticker"], keep="first")
              .reset_index(drop=True))


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), додає 'bench','corr','beta' по 'ticker'.

    Замість merge на кожен батч (+ strip/upper над мільйонами рядків) нормалізація і
    пошук у мапі йдуть по унікальних тікерах, а результат розгортається за кодами.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка — "
            "інакше bench/corr/beta були б null у всіх рядках."
        )

    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        # dtype="string" тримає bench рядковим і в батчі без жодного збігу: інакше
        # суцільний None дає pyarrow-тип null і схема розійдеться з першим батчем
        df["bench"] = pd.array(_map_by_ticker(codes, cats, m_bench, numeric=False), dtype="string")
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        cols = [c for c in df.columns if c not in ("bench", "corr", "beta")]
        if insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]]
        else:
            df = df[cols + ["bench", "corr", "beta"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path


# опціональний аліас під старе ім'я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [29]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = attach_bench_corr_beta_parquet(
#     input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
#     corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
#     out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     batch_rows=2_000_000,
#     round_decimals=4,
#     insert_before="pct_vs_prev_close",
#     compression="snappy",
# )
# print("Готово:", out_path)

In [30]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [31]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Проміжного premarket_rows_final.parquet більше не існує: bench/corr/beta
# додаються за той самий прохід, що й решта. Готовий файл — у комірці 47.

In [32]:
# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [33]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=12,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 28 тікерів (пропущено 0 по старому маніфесту) | 2026-06-26 00:00:00 → 2026-09-26 23:59:59 | interval=1 | next batch #0132 | run=870e7022

   workers: tickers=12, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-06-26 → 2026-09-24 (91 днів)

   📈 обробляються дні: 2026-09-25 → 2026-09-26 (2 днів)

   psutil · старт · 🧠 RAM: 655.5 MB

[10/28] ✓ FCX: 456 рядків |  35.71% | ETA 00:01

[20/28] ✓ XBI: 450 рядків |  71.43% | ETA 00:00

[28/28] ✓ XLV: 417 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 667.8 MB

💾 batch 132 → 16,847 рядків (всього 16,847 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\ETF\intraday_0132.csv.gz

   ✅ після flush · 🧠 RAM: 674.3 MB

   🔚 фінал · 🧠 RAM: 674.3 MB

🏁 Готово. Нових рядків: 16,847 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:02

In [34]:
# Один прохід по ETF-батчах: premarket-рядки + денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc_etf.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    build_oc=True,
    max_workers=4,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  files=132 workers=4

  [1/132] intraday_0004.csv.gz  in=1,760 out=1,760 elapsed=0.0s

  [2/132] intraday_0003.csv.gz  in=10,518 out=10,518 elapsed=0.1s

  [3/132] intraday_0002.csv.gz  in=20,691 out=20,691 elapsed=0.1s

  [4/132] intraday_0005.csv.gz  in=31,264 out=31,264 elapsed=0.1s

  [5/132] intraday_0007.csv.gz  in=41,411 out=41,411 elapsed=0.1s

  [6/132] intraday_0006.csv.gz  in=51,502 out=51,502 elapsed=0.1s

  [7/132] intraday_0010.csv.gz  in=52,949 out=52,949 elapsed=0.2s

  [8/132] intraday_0009.csv.gz  in=61,523 out=61,523 elapsed=0.2s

  [9/132] intraday_0008.csv.gz  in=72,207 out=72,207 elapsed=0.2s

  [10/132] intraday_0011.csv.gz  in=81,941 out=81,941 elapsed=0.2s

  [11/132] intraday_0012.csv.gz  in=91,152 out=91,152 elapsed=0.2s

  [12/132] intraday_0013.csv.gz  in=100,754 out=100,754 elapsed=0.2s

  [13/132] intraday_0014.csv.gz  in=110,387 out=110,387 elapsed=0.2s

  [14/132] intraday_0016.csv.gz  in=111,758 out=111,758 elapsed=0.2s

  [15/132] intraday_0015.csv.gz  in=120,035 out=120,035 elapsed=0.2s

  [16/132] intraday_0017.csv.gz  in=129,351 out=129,351 elapsed=0.3s

  [17/132] intraday_0019.csv.gz  in=138,847 out=138,847 elapsed=0.3s

  [18/132] intraday_0018.csv.gz  in=148,074 out=148,074 elapsed=0.3s

  [19/132] intraday_0021.csv.gz  in=149,677 out=149,677 elapsed=0.3s

  [20/132] intraday_0020.csv.gz  in=157,847 out=157,847 elapsed=0.3s

  [21/132] intraday_0023.csv.gz  in=167,662 out=167,662 elapsed=0.3s

  [22/132] intraday_0022.csv.gz  in=196,862 out=196,862 elapsed=0.4s

  [23/132] intraday_0024.csv.gz  in=218,002 out=218,002 elapsed=0.4s

  [24/132] intraday_0026.csv.gz  in=226,279 out=226,279 elapsed=0.4s

  [25/132] intraday_0027.csv.gz  in=235,077 out=235,077 elapsed=0.4s

  [26/132] intraday_0028.csv.gz  in=244,053 out=244,053 elapsed=0.4s

  [27/132] intraday_0029.csv.gz  in=252,994 out=252,994 elapsed=0.4s

  [28/132] intraday_0030.csv.gz  in=262,243 out=262,243 elapsed=0.4s

  [29/132] intraday_0025.csv.gz  in=366,685 out=366,685 elapsed=0.5s

  [30/132] intraday_0032.csv.gz  in=375,464 out=375,464 elapsed=0.5s

  [31/132] intraday_0031.csv.gz  in=384,366 out=384,366 elapsed=0.5s

  [32/132] intraday_0034.csv.gz  in=393,019 out=393,019 elapsed=0.5s

  [33/132] intraday_0035.csv.gz  in=401,731 out=401,731 elapsed=0.5s

  [34/132] intraday_0033.csv.gz  in=410,508 out=410,508 elapsed=0.5s

  [35/132] intraday_0036.csv.gz  in=419,433 out=419,433 elapsed=0.5s

  [36/132] intraday_0001.csv.gz  in=1,006,353 out=1,006,353 elapsed=0.7s

  [37/132] intraday_0038.csv.gz  in=1,015,235 out=1,015,235 elapsed=0.7s

  [38/132] intraday_0037.csv.gz  in=1,024,157 out=1,024,157 elapsed=0.7s

  [39/132] intraday_0039.csv.gz  in=1,032,246 out=1,032,246 elapsed=0.7s

  [40/132] intraday_0040.csv.gz  in=1,040,839 out=1,040,839 elapsed=0.7s

  [41/132] intraday_0041.csv.gz  in=1,050,147 out=1,050,147 elapsed=0.7s

  [42/132] intraday_0042.csv.gz  in=1,058,326 out=1,058,326 elapsed=0.8s

  [43/132] intraday_0043.csv.gz  in=1,066,321 out=1,066,321 elapsed=0.8s

  [44/132] intraday_0044.csv.gz  in=1,074,838 out=1,074,838 elapsed=0.8s

  [45/132] intraday_0045.csv.gz  in=1,082,019 out=1,082,019 elapsed=0.8s

  [46/132] intraday_0046.csv.gz  in=1,090,385 out=1,090,385 elapsed=0.8s

  [47/132] intraday_0047.csv.gz  in=1,098,733 out=1,098,733 elapsed=0.8s

  [48/132] intraday_0048.csv.gz  in=1,107,041 out=1,107,041 elapsed=0.8s

  [49/132] intraday_0049.csv.gz  in=1,115,603 out=1,115,603 elapsed=0.8s

  [50/132] intraday_0050.csv.gz  in=1,123,880 out=1,123,880 elapsed=0.8s

  [51/132] intraday_0051.csv.gz  in=1,132,076 out=1,132,076 elapsed=0.9s

  [52/132] intraday_0052.csv.gz  in=1,140,350 out=1,140,350 elapsed=0.9s

  [53/132] intraday_0053.csv.gz  in=1,148,364 out=1,148,364 elapsed=0.9s

  [54/132] intraday_0054.csv.gz  in=1,156,344 out=1,156,344 elapsed=0.9s

  [55/132] intraday_0056.csv.gz  in=1,164,562 out=1,164,562 elapsed=0.9s

  [56/132] intraday_0057.csv.gz  in=1,173,385 out=1,173,385 elapsed=0.9s

  [57/132] intraday_0058.csv.gz  in=1,181,781 out=1,181,781 elapsed=0.9s

  [58/132] intraday_0059.csv.gz  in=1,189,748 out=1,189,748 elapsed=0.9s

  [59/132] intraday_0060.csv.gz  in=1,197,814 out=1,197,814 elapsed=0.9s

  [60/132] intraday_0061.csv.gz  in=1,206,064 out=1,206,064 elapsed=1.0s

  [61/132] intraday_0062.csv.gz  in=1,214,193 out=1,214,193 elapsed=1.0s

  [62/132] intraday_0063.csv.gz  in=1,222,519 out=1,222,519 elapsed=1.0s

  [63/132] intraday_0065.csv.gz  in=1,230,884 out=1,230,884 elapsed=1.0s

  [64/132] intraday_0064.csv.gz  in=1,239,106 out=1,239,106 elapsed=1.0s

  [65/132] intraday_0066.csv.gz  in=1,246,888 out=1,246,888 elapsed=1.0s

  [66/132] intraday_0055.csv.gz  in=1,360,697 out=1,360,697 elapsed=1.0s

  [67/132] intraday_0067.csv.gz  in=1,368,954 out=1,368,954 elapsed=1.1s

  [68/132] intraday_0068.csv.gz  in=1,377,472 out=1,377,472 elapsed=1.1s

  [69/132] intraday_0070.csv.gz  in=1,395,056 out=1,395,056 elapsed=1.1s

  [70/132] intraday_0071.csv.gz  in=1,412,694 out=1,412,694 elapsed=1.1s

  [71/132] intraday_0072.csv.gz  in=1,430,041 out=1,430,041 elapsed=1.1s

  [72/132] intraday_0073.csv.gz  in=1,447,121 out=1,447,121 elapsed=1.1s

  [73/132] intraday_0074.csv.gz  in=1,464,856 out=1,464,856 elapsed=1.2s

  [74/132] intraday_0075.csv.gz  in=1,482,239 out=1,482,239 elapsed=1.2s

  [75/132] intraday_0077.csv.gz  in=1,484,607 out=1,484,607 elapsed=1.2s

  [76/132] intraday_0076.csv.gz  in=1,501,364 out=1,501,364 elapsed=1.2s

  [77/132] intraday_0078.csv.gz  in=1,518,960 out=1,518,960 elapsed=1.2s

  [78/132] intraday_0080.csv.gz  in=1,535,897 out=1,535,897 elapsed=1.2s

  [79/132] intraday_0079.csv.gz  in=1,552,382 out=1,552,382 elapsed=1.2s

  [80/132] intraday_0081.csv.gz  in=1,569,544 out=1,569,544 elapsed=1.2s

  [81/132] intraday_0082.csv.gz  in=1,586,413 out=1,586,413 elapsed=1.3s

  [82/132] intraday_0083.csv.gz  in=1,604,362 out=1,604,362 elapsed=1.3s

  [83/132] intraday_0084.csv.gz  in=1,621,662 out=1,621,662 elapsed=1.3s

  [84/132] intraday_0085.csv.gz  in=1,638,586 out=1,638,586 elapsed=1.3s

  [85/132] intraday_0086.csv.gz  in=1,655,557 out=1,655,557 elapsed=1.3s

  [86/132] intraday_0088.csv.gz  in=1,673,298 out=1,673,298 elapsed=1.4s

  [87/132] intraday_0087.csv.gz  in=1,690,115 out=1,690,115 elapsed=1.4s

  [88/132] intraday_0091.csv.gz  in=1,707,230 out=1,707,230 elapsed=1.4s

  [89/132] intraday_0090.csv.gz  in=1,723,628 out=1,723,628 elapsed=1.4s

  [90/132] intraday_0093.csv.gz  in=1,723,637 out=1,723,637 elapsed=1.4s

  [91/132] intraday_0092.csv.gz  in=1,739,852 out=1,739,852 elapsed=1.4s

  [92/132] intraday_0094.csv.gz  in=1,758,814 out=1,758,814 elapsed=1.5s

  [93/132] intraday_0089.csv.gz  in=1,886,373 out=1,886,373 elapsed=1.5s

  [94/132] intraday_0095.csv.gz  in=1,902,926 out=1,902,926 elapsed=1.5s

  [95/132] intraday_0096.csv.gz  in=1,920,844 out=1,920,844 elapsed=1.5s

  [96/132] intraday_0099.csv.gz  in=1,922,454 out=1,922,454 elapsed=1.5s

  [97/132] intraday_0097.csv.gz  in=1,938,616 out=1,938,616 elapsed=1.6s

  [98/132] intraday_0098.csv.gz  in=1,954,305 out=1,954,305 elapsed=1.6s

  [99/132] intraday_0100.csv.gz  in=1,970,821 out=1,970,821 elapsed=1.6s

  [100/132] intraday_0101.csv.gz  in=1,987,634 out=1,987,634 elapsed=1.6s

  [101/132] intraday_0103.csv.gz  in=2,006,707 out=2,006,707 elapsed=1.7s

  [102/132] intraday_0105.csv.gz  in=2,025,920 out=2,025,920 elapsed=1.7s

  [103/132] intraday_0106.csv.gz  in=2,045,930 out=2,045,930 elapsed=1.7s

  [104/132] intraday_0107.csv.gz  in=2,065,797 out=2,065,797 elapsed=1.8s

  [105/132] intraday_0069.csv.gz  in=2,811,050 out=2,811,050 elapsed=2.1s

  [106/132] intraday_0108.csv.gz  in=2,830,090 out=2,830,090 elapsed=2.1s

  [107/132] intraday_0102.csv.gz  in=3,062,175 out=3,062,175 elapsed=2.1s

  [108/132] intraday_0109.csv.gz  in=3,079,631 out=3,079,631 elapsed=2.1s

  [109/132] intraday_0112.csv.gz  in=3,081,800 out=3,081,800 elapsed=2.1s

  [110/132] intraday_0110.csv.gz  in=3,101,522 out=3,101,522 elapsed=2.1s

  [111/132] intraday_0113.csv.gz  in=3,120,377 out=3,120,377 elapsed=2.1s

  [112/132] intraday_0104.csv.gz  in=3,706,603 out=3,706,603 elapsed=2.4s

  [113/132] intraday_0114.csv.gz  in=3,726,346 out=3,726,346 elapsed=2.4s

  [114/132] intraday_0115.csv.gz  in=3,745,321 out=3,745,321 elapsed=2.4s

  [115/132] intraday_0111.csv.gz  in=4,013,505 out=4,013,505 elapsed=2.4s

  [116/132] intraday_0117.csv.gz  in=4,030,681 out=4,030,681 elapsed=2.4s

  [117/132] intraday_0119.csv.gz  in=4,049,514 out=4,049,514 elapsed=2.4s

  [118/132] intraday_0118.csv.gz  in=4,067,848 out=4,067,848 elapsed=2.4s

  [119/132] intraday_0120.csv.gz  in=4,087,330 out=4,087,330 elapsed=2.5s

  [120/132] intraday_0116.csv.gz  in=4,106,177 out=4,106,177 elapsed=2.5s

  [121/132] intraday_0122.csv.gz  in=4,125,905 out=4,125,905 elapsed=2.5s

  [122/132] intraday_0121.csv.gz  in=4,145,198 out=4,145,198 elapsed=2.5s

  [123/132] intraday_0124.csv.gz  in=4,164,271 out=4,164,271 elapsed=2.5s

  [124/132] intraday_0123.csv.gz  in=4,182,997 out=4,182,997 elapsed=2.6s

  [125/132] intraday_0127.csv.gz  in=4,185,145 out=4,185,145 elapsed=2.6s

  [126/132] intraday_0125.csv.gz  in=4,204,144 out=4,204,144 elapsed=2.6s

  [127/132] intraday_0126.csv.gz  in=4,221,902 out=4,221,902 elapsed=2.6s

  [128/132] intraday_0128.csv.gz  in=4,242,000 out=4,242,000 elapsed=2.6s

  [129/132] intraday_0130.csv.gz  in=4,261,073 out=4,261,073 elapsed=2.7s

  [130/132] intraday_0131.csv.gz  in=4,279,897 out=4,279,897 elapsed=2.7s

  [131/132] intraday_0129.csv.gz  in=4,299,863 out=4,299,863 elapsed=2.7s

  [132/132] intraday_0132.csv.gz  in=4,316,710 out=4,316,710 elapsed=2.7s

✅ DONE  in=4,316,710 → out=4,316,710  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 2.7s

In [35]:
# oc_etf.parquet уже побудовано в клітинці 34 (той самий прохід по файлах).
_oc_etf_path = str(WORK_DIR / "oc_etf.parquet")
if os.path.exists(_oc_etf_path):
    df_oc = pd.read_parquet(_oc_etf_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(ETF_DIR), out_path=_oc_etf_path)
print(df_oc.head())

  ticker        date   open  close
0   ARKK  2026-05-01  75.85  76.84
1   ARKK  2026-05-04  77.24  78.21
2   ARKK  2026-05-05  78.40  76.62
3   ARKK  2026-05-06  77.33  79.54
4   ARKK  2026-05-07  79.40  78.09

In [36]:
# Ті самі оптимізовані функції, що й у клітинці 22 — тут лише інші дефолти обгортки
# (ETF-файли замість акційних).
def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [37]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=4,316,710  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 6.7s

Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [38]:
# Та сама оптимізована add_pct_vs_prev_close_parquet із клітинки 24 —
# тут лише інші дефолти обгортки (ETF-файли, колонка Bench%).
def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",              # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [39]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=4,316,710  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 3.5s

Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [40]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий по ключах ('bench'↔'ticker', 'dt').

    Прискорення: ETF-мапа читається одним pq.read_table (лише 3 потрібні колонки)
    замість iter_batches + concat + gc; ключ 'dt' лишається рядком —
    лексикографічний порядок 'YYYY-MM-DD HH:MM:SS' збігається з хронологічним,
    тож per-row парсинг дат не потрібен (крім align_to_minute=True).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    t0 = time.time()

    # ---------- 1) Мапа з ETF-файла: (bench, dt) -> Bench% ----------
    etf_names = [f.name for f in pq.ParquetFile(etf_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    for col in ("ticker", "dt"):
        if col not in cl:
            raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    if val_col is None:
        raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

    etf_map = pq.read_table(etf_path, columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    _dt_is_str = (etf_map["dt"].dtype == object) or pd.api.types.is_string_dtype(etf_map["dt"])
    if align_to_minute or not _dt_is_str:
        etf_map["dt"] = pd.to_datetime(etf_map["dt"], errors="coerce")
        if align_to_minute:
            etf_map["dt"] = etf_map["dt"].dt.floor("T")
    else:
        etf_map["dt"] = etf_map["dt"].astype(str)

    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    # ---------- 2) Потоково проходимо базовий файл ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_path}", flush=True)
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        codes, cats = _ticker_codes(df["bench"])
        df["bench"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)

        _base_dt_is_str = (df["dt"].dtype == object) or pd.api.types.is_string_dtype(df["dt"])
        if align_to_minute or not _base_dt_is_str:
            df["dt"] = pd.to_datetime(df["dt"], errors="coerce")
            if align_to_minute:
                df["dt"] = df["dt"].dt.floor("T")
        else:
            df["dt"] = df["dt"].astype(str)

        merged = df.merge(etf_map, on=["bench", "dt"], how="left")

        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = [c for c in merged.columns if c != "Bench%"]
            pos = cols.index(insert_before)
            merged = merged[cols[:pos] + ["Bench%"] + cols[pos:]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [41]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# merge_bench_pct_from_etf(
#     base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
#     out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
#     batch_rows=2_000_000,
#     align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
#     round_decimals=2,
#     insert_before=None,          # або, наприклад, "pct_vs_prev_close"
#     compression="snappy",
# )

In [42]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


_REPORT_FAILS = {"n": 0}
_GAP_FAILS = {"n": 0}


def _datum_request_retry(endpoint, params, *, max_retries=6, backoff=0.5):
    """Повторює запит при 429/мережевих збоях з наростаючою паузою.
    Вичерпавши спроби — кидає останній виняток."""
    import random, time
    for attempt in range(max_retries + 1):
        try:
            return DatumApi.data_request(endpoint, params)
        except Exception:
            if attempt == max_retries:
                raise
            time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }
        reports_df = _datum_request_retry("/reports", params)
        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)
    except Exception as e:
        _REPORT_FAILS["n"] += 1
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20,
                            max_workers=8, max_fail_ratio=0.15):
    # 16 потоків без пауз давали суцільні 429; з retry вистачає меншого числа
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []
    _REPORT_FAILS["n"] = 0

    # Ті самі репорти вже завантажила комірка 11. Беремо їх лише коли вікно,
    # last_n_reports і набір тикерів збігаються; інакше — звичайний фетч.
    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    if (_c.get("window") == (str(start_date)[:10], str(end_date)[:10])
            and _c.get("last_n_reports") == int(last_n_reports)
            and set(tickers) <= _c.get("tickers", set())):
        _r = _c["reports"].rename(columns={"date": "report_date"})
        _r = (_r[_r["ticker"].isin(tickers)]
                .drop_duplicates(["ticker", "report_date"]).reset_index(drop=True))
        print(f"Reports: узято з кешу комірки 11 ({len(_r)} рядків), фетч пропущено")
        return _r, _r.groupby("ticker")["report_date"].apply(set).to_dict()

    def fetch(t):
        return get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Reports"):
            rep = f.result()
            if rep is not None and not rep.empty:
                parts.append(rep)

    if tickers and _REPORT_FAILS["n"] / len(tickers) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_REPORT_FAILS['n']} з {len(tickers)} тикерів "
            f"({_REPORT_FAILS['n'] / len(tickers) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Репорти вийшли б неповними."
        )

    if not parts:
        return pd.DataFrame(columns=["ticker", "report_date"]), {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map,
                                           max_workers=8, max_fail_ratio=0.15):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    _GAP_FAILS["n"] = 0

    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    if (_c.get("window") == (str(start_date)[:10], str(end_date)[:10])
            and set(tickers) <= _c.get("tickers", set())):
        _g = _c["gaps"]
        _g = _g[_g["ticker"].isin(tickers)].copy()
        _rep = pd.DataFrame([(t, d) for t, ds in (report_days_map or {}).items() for d in ds],
                            columns=["ticker", "date"])
        if len(_rep):
            _g = _g.merge(_rep.assign(_r=1), on=["ticker", "date"], how="left")
            _g = _g[_g["_r"].isna()].drop(columns="_r")
        print(f"Gaps: узято з кешу комірки 11 ({len(_g)} рядків), фетч пропущено")
        return _g.reset_index(drop=True)

    def fetch(t):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }
        try:
            df_gap = _datum_request_retry("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                return None

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                return None

            out = df_gap.copy()
            out["ticker"] = out["ticker"].astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            return out if not out.empty else None
        except Exception as e:
            _GAP_FAILS["n"] += 1
            print(f"Gap fetch failed for {t}: {e}")
            return None

    all_results = []
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Gaps (ex-reports)"):
            result = f.result()
            if result is not None:
                all_results.append(result)

    if tickers and _GAP_FAILS["n"] / len(tickers) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_GAP_FAILS['n']} з {len(tickers)} тикерів "
            f"({_GAP_FAILS['n'] / len(tickers) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Гепи вийшли б неповними."
        )

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=None,
):
    """Rolling std по попередньому вікну з обрізанням хвостів на квантилі cap_q.

    Раніше це був rolling(...).apply(python_func) — окремий виклик Python на кожне
    вікно кожного тікера. Тепер вікна будуються через sliding_window_view і квантиль/
    clip/std рахуються одразу по всій матриці вікон групи (чисто numpy).
    Результат збігається з попередньою реалізацією до 1e-12.
    """
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col], kind="stable").copy()
    col = f"{value_col}_sigma_{window}d_cap"

    # Рідкісний випадок min_periods != window має іншу семантику (часткові вікна) —
    # там лишаємо стару, повільну, але точну реалізацію.
    if min_periods != window:
        def compute_sigma(s):
            x = s.shift(1)

            def f(arr):
                arr = arr[~np.isnan(arr)]
                if len(arr) < min_periods:
                    return np.nan
                cap = np.quantile(np.abs(arr), cap_q)
                arr_capped = np.clip(arr, -cap, cap)
                return np.std(arr_capped, ddof=1)

            return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

        out[col] = out.groupby(group_col)[value_col].transform(compute_sigma)
        return out

    vals = pd.to_numeric(out[value_col], errors="coerce").to_numpy(dtype="float64")
    codes, _ = pd.factorize(out[group_col], sort=False)
    res = np.full(vals.shape, np.nan)

    order = np.argsort(codes, kind="stable")
    bounds = np.flatnonzero(np.diff(codes[order])) + 1
    for sl in np.split(order, bounds):
        n = sl.size
        if n <= window:
            continue
        x = vals[sl]
        # вікно з ПОПЕРЕДНІХ значень (еквівалент shift(1) у старій версії)
        w = np.lib.stride_tricks.sliding_window_view(x[:-1], window)   # (n-window, window)
        cap = np.quantile(np.abs(w), cap_q, axis=1, keepdims=True)
        res[sl[window:]] = np.clip(w, -cap, cap).std(axis=1, ddof=1)

    out[col] = res
    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

# 3) Rolling sigma
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

print("Tickers with sigma:", len(std_by_ticker))
std_by_ticker.head()

Reports: узято з кешу комірки 11 (4131 рядків), фетч пропущено
Report rows: 4131

Gaps: узято з кешу комірки 11 (442247 рядків), фетч пропущено
Rows in gaps (without report days): 442247

Tickers with sigma: 7038

  ticker     sigma
0      A  0.831820
1     AA  1.443626
2   AAAU  1.090026
3   AACG  2.276865
4   AADX  1.066091

In [43]:
std_by_ticker

     ticker     sigma
0         A  0.831820
1        AA  1.443626
2      AAAU  1.090026
3      AACG  2.276865
4      AADX  1.066091
...     ...       ...
7033   ZVOL  0.444821
7034   ZVRA  0.868490
7035    ZWS  0.779834
7036   ZYBT  1.525784
7037   ZYME  0.817867

[7038 rows x 2 columns]

In [44]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"] = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet.

    Як і в клітинці 28: нормалізація тікера і пошук у мапі йдуть по унікальних
    значеннях, а не по кожному з мільйонів рядків; per-batch merge не потрібен.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)
    sd = dict(zip(sigma_map["ticker"], sigma_map["sigma"]))

    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}", flush=True)
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["sigma"] = _map_by_ticker(codes, cats, sd, numeric=True)

        cols = [c for c in df.columns if c != "sigma"]
        if insert_before and insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["sigma"] + cols[idx:]]
        else:
            df = df[cols + ["sigma"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [45]:
def build_final_in_one_pass(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    corrbeta_parquet_path: str,
    etf_parquet_path: str,
    out_parquet_path: str,
    *,
    sigma_df=None,
    sigma_path=None,
    batch_rows: int = 2_000_000,
    round_decimals=4,
    stack_round_to=None,
    bench_round_decimals=2,
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """Один потоковий прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta
    → Bench% → sigma. Замінює merge_intraday_and_oc_to_file +
    add_pct_vs_prev_close_parquet + attach_bench_corr_beta_parquet +
    merge_bench_pct_from_etf + add_sigma_by_ticker_to_parquet.

    Результат побайтово збігається з ланцюжком; економія — у тому, що ~3 ГБ
    читаються й пишуться один раз, а не шість.
    """
    t0 = time.time()

    # ---------- side-входи: готуються ОДИН раз ----------
    oc_prepared = _prep_oc_prev_close(pq.read_table(oc_parquet_path).to_pandas())

    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка."
        )
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)
    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    etf_names = [f.name for f in pq.ParquetFile(etf_parquet_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    etf_map = pq.read_table(etf_parquet_path,
                            columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if bench_round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(bench_round_decimals)
    etf_map["dt"] = etf_map["dt"].astype(str)
    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    sig = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    m_sigma = dict(zip(sig["ticker"], sig["sigma"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    ORDER = ["ticker", "dt", "o", "h", "l", "c", "v", "date", "open", "prev_close",
             "Stack%", "bench", "corr", "beta", "Bench%", "sigma"]

    pf = pq.ParquetFile(intraday_parquet_path)
    writer = None
    total_rows = 0
    print(f"▶️ START one-pass → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # 1) день + open/prev_close (ключ — сирий ticker, як у ланцюжку)
        df = df[df["dt"].notna()]
        df = df.assign(date=_date_from_dt(df["dt"]))
        df = df.merge(oc_prepared, on=["ticker", "date"], how="left")
        df["prev_close"] = _rebase_prev_close_after_session_close(df)

        # 2) Stack%
        num = pd.to_numeric(df["o"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0
        if stack_round_to is not None:
            pct = np.round(pct, int(stack_round_to))
        df["Stack%"] = pct

        # 3) bench/corr/beta (тут ticker нормалізується — як у ланцюжку)
        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["bench"] = _map_by_ticker(codes, cats, m_bench, numeric=False)
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        # 4) sigma — теж по codes/cats, тому рахуємо ДО мерджа
        df["sigma"] = _map_by_ticker(codes, cats, m_sigma, numeric=True)

        # 5) Bench% по (bench, dt); bench лишається object для мерджа
        df["dt"] = df["dt"].astype(str)
        df = df.merge(etf_map, on=["bench", "dt"], how="left")

        # string-dtype один раз наприкінці: тримає тип bench стабільним між батчами
        df["bench"] = pd.array(df["bench"], dtype="string")

        df = df[[c for c in ORDER if c in df.columns]]
        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,} elapsed={time.time()-t0:,.1f}s", flush=True)
        del df, table, batch
        gc.collect()

    if writer is not None:
        writer.close()
    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path} in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path

In [46]:
# std_by_ticker columns: ['ticker', 'sigma']
# Один прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta → Bench% → sigma.
# Замінює комірки 23, 25, 29, 41 і колишній add_sigma_by_ticker_to_parquet.
sigma_out_path = build_final_in_one_pass(
    intraday_parquet_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_parquet_path=str(WORK_DIR / "oc.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    etf_parquet_path=str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    sigma_df=std_by_ticker,
    batch_rows=2_000_000,
    round_decimals=4,
    bench_round_decimals=2,
    compression="snappy",
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START one-pass → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000 elapsed=39.6s

[batch   10] rows=20,000,000 elapsed=71.6s

[batch   15] rows=30,000,000 elapsed=103.4s

[batch   20] rows=40,000,000 elapsed=135.4s

[batch   25] rows=50,000,000 elapsed=167.0s

[batch   30] rows=60,000,000 elapsed=199.6s

[batch   35] rows=70,000,000 elapsed=231.6s

[batch   40] rows=80,000,000 elapsed=263.9s

[batch   45] rows=90,000,000 elapsed=296.9s

[batch   50] rows=100,000,000 elapsed=329.1s

[batch   55] rows=109,067,647 elapsed=358.8s

✅ DONE rows=109,067,647 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet in 358.9s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 7038
tickers checked in parquet: 7036
max |file_sigma - expected_sigma|: 0.0

In [47]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 109,067,647
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 390/21150
NaN у 'corr' (у прев'ю): 390/21150
NaN у 'beta' (у прев'ю): 390/21150

Перші рядки:

      ticker                   dt           o           h           l           c          v        date    open  prev_close        Stack% bench    corr    beta  Bench%     sigma
0        SCO  2026-06-30 00:23:00   34.900002   34.900002   34.900002   34.900002        8.0  2026-06-30   34.13       34.82  2.297574e-01   IWM  0.6078  2.1137     NaN  1.860730
1        SCO  2026-06-30 00:26:00   34.939999   34.939999   34.939999   34.939999        1.0  2026-06-30   34.13       34.82  3.446256e-01   IWM  0.6078  2.1137     NaN  1.860730
2        SCO  2026-06-30 00:28:00   35.000000   35.009998   35.000000   35.009998      205.0  2026-06-30   34.13       34.82  5.169443e-01   IWM  0.6078  2.1137     NaN  1.860730
3        SCO  2026-06-30 00:31:00   35.009998   35.009998   35.009998   35.009998       12.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.6078  2.1137     NaN  1.860730
4        SCO  2026-06-30 00:34:00   34.990002   34.990002   34.990002   34.990002       11.0  2026-06-30   34.13       34.82  4.882300e-01   IWM  0.6078  2.1137     NaN  1.860730
5        SCO  2026-06-30 00:35:00   35.020000   35.020000   35.020000   35.020000        1.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.6078  2.1137    0.15  1.860730
6        SCO  2026-06-30 00:40:00   35.020000   35.020000   35.020000   35.020000        1.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.6078  2.1137     NaN  1.860730
7        SCO  2026-06-30 00:43:00   35.049999   35.049999   35.049999   35.049999      100.0  2026-06-30   34.13       34.82  6.605377e-01   IWM  0.6078  2.1137     NaN  1.860730
8        SCO  2026-06-30 00:45:00   35.029999   35.029999   35.029999   35.029999       21.0  2026-06-30   34.13       34.82  6.030982e-01   IWM  0.6078  2.1137     NaN  1.860730
9        SCO  2026-06-30 00:47:00   35.029999   35.029999   35.029999   35.029999      100.0  2026-06-30   34.13       34.82  6.030982e-01   IWM  0.6078  2.1137    0.12  1.860730
10       SCO  2026-06-30 01:00:00   35.060001   35.099998   35.060001   35.099998      519.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.6078  2.1137    0.12  1.860730
11       SCO  2026-06-30 01:01:00   35.150002   35.200001   35.150002   35.200001      832.0  2026-06-30   34.13       34.82  9.477356e-01   IWM  0.6078  2.1137     NaN  1.860730
12       SCO  2026-06-30 01:02:00   35.200001   35.200001   35.200001   35.200001      100.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.6078  2.1137     NaN  1.860730
13       SCO  2026-06-30 01:04:00   35.200001   35.200001   35.200001   35.200001        5.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.6078  2.1137    0.17  1.860730
14       SCO  2026-06-30 01:08:00   35.200001   35.200001   35.189999   35.189999      230.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.6078  2.1137    0.17  1.860730
15       SCO  2026-06-30 01:11:00   35.150002   35.150002   35.150002   35.150002        5.0  2026-06-30   34.13       34.82  9.477356e-01   IWM  0.6078  2.1137     NaN  1.860730
16       SCO  2026-06-30 01:12:00   35.130001   35.130001   35.130001   35.130001        1.0  2026-06-30   34.13       34.82  8.902960e-01   IWM  0.6078  2.1137     NaN  1.860730
17       SCO  2026-06-30 01:16:00   35.119999   35.130001   35.119999   35.130001       13.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.6078  2.1137    0.15  1.860730
18       SCO  2026-06-30 01:18:00   35.139999   35.139999   35.139999   35.139999       10.0  2026-06-30   34.13       34.82  9.190103e-01   IWM  0.6078  2.1137    0.12  1.860730
19       SCO  2026-06-30 01:19:00   35.130001   35.130001   35.110001   35.110001       37.0  2026-06-30   34.13       34.82  8.902960e-01   IWM  0.6078  2.1137     NaN  1.860730
20       SCO  2026-06-30 01:20:00   35.099998   35.099998   35.099998   35.099998       60.0  2026-06-30   34.13       34.82  8.041312e-01   IWM  0.6078  2.1137     NaN  1.860730
21       SCO  2026-06-30 01:21:00   35.119999   35.119999   35.119999   35.119999       20.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.6078  2.1137     NaN  1.860730
22       SCO  2026-06-30 01:26:00   35.090000   35.090000   35.090000   35.090000      150.0  2026-06-30   34.13       34.82  7.754169e-01   IWM  0.6078  2.1137    0.11  1.860730
23       SCO  2026-06-30 01:30:00   35.080002   35.180000   35.070000   35.180000      172.0  2026-06-30   34.13       34.82  7.467026e-01   IWM  0.6078  2.1137    0.09  1.860730
24       SCO  2026-06-30 01:31:00   35.160000   35.160000   35.160000   35.160000        2.0  2026-06-30   34.13       34.82  9.764499e-01   IWM  0.6078  2.1137     NaN  1.860730
25       SCO  2026-06-30 01:38:00   35.060001   35.060001   35.020000   35.020000       27.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.6078  2.1137     NaN  1.860730
26       SCO  2026-06-30 01:40:00   35.040001   35.040001   35.029999   35.029999       20.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.6078  2.1137     NaN  1.860730
27       SCO  2026-06-30 01:41:00   35.020000   35.020000   35.020000   35.020000        2.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.6078  2.1137     NaN  1.860730
28       SCO  2026-06-30 01:42:00   35.040001   35.040001   35.020000   35.020000       35.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.6078  2.1137     NaN  1.860730
29       SCO  2026-06-30 01:44:00   35.020000   35.020000   35.020000   35.020000        4.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.6078  2.1137     NaN  1.860730
30       SCO  2026-06-30 01:45:00   35.009998   35.009998   35.000000   35.009998       25.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.6078  2.1137     NaN  1.860730
31       SCO  2026-06-30 01:50:00   35.119999   35.119999   35.119999   35.119999       60.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.6078  2.1137     NaN  1.860730
32       SCO  2026-06-30 01:53:00   35.119999   35.130001   35.119999   35.130001       17.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.6078  2.1137     NaN  1.860730
33       SCO  2026-06-30 01:59:00   35.160000   35.160000   35.160000   35.160000       10.0  2026-06-30   34.13       34.82  9.764499e-01   IWM  0.6078  2.1137    0.11  1.860730
34       SCO  2026-06-30 02:01:00   35.220001   35.230000   35.220001   35.230000        6.0  2026-06-30   34.13       34.82  1.148769e+00   IWM  0.6078  2.1137     NaN  1.860730
35       SCO  2026-06-30 02:04:00   35.230000   35.259998   35.230000   35.250000      201.0  2026-06-30   34.13       34.82  1.177483e+00   IWM  0.6078  2.1137     NaN  1.860730
36       SCO  2026-06-30 02:05:00   35.240002   35.240002   35.240002   35.240002        1.0  2026-06-30   34.13       34.82  1.206208e+00   IWM  0.6078  2.1137     NaN  1.860730
37       SCO  2026-06-30 02:07:00   35.209999   35.209999   35.209999   35.209999       10.0  2026-06-30   34.13       34.82  1.120043e+00   IWM  0.6078  2.1137    0.11  1.860730
38       SCO  2026-06-30 02:08:00   35.200001   35.200001   35.200001   35.200001       10.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.6078  2.1137     NaN  1.860730
39       SCO  2026-06-30 02:12:00   35.200001   35.200001   35.200001   35.200001       40.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.6078  2.1137     NaN  1.860730
40       SCO  2026-06-30 02:13:00   35.240002   35.240002   35.240002   35.240002      102.0  2026-06-30   34.13       34.82  1.206208e+00   IWM  0.6078  2.1137     NaN  1.860730
41       SCO  2026-06-30 02:17:00   35.250000   35.259998   35.250000   35.259998      118.0  2026-06-30   34.13       34.82  1.234922e+00   IWM  0.6078  2.1137     NaN  1.860730
42       SCO  2026-06-30 02:19:00   35.270000   35.270000   35.270000   35.270000        1.0  2026-06-30   34.13       34.82  1.292362e+00   IWM  0.6078  2.1137     NaN  1.860730
43       SCO  2026-06-30 02:20:00   35.279999   35.279999   35.279999   35.279999        1.0  2026-06-30   34.13       34.82  1.321076e+00   IWM  0.6078  2.1137    0.06  1.860730
44       SCO  2026-06-30 02:21:00   35.299999   35.299999   35.299999   35.299999      155.0  2026-06-30   34.13       34.82  1.378516e+00   IWM  0.6078  2.1137     NaN  1.860730
45       SCO  2026-06-30 02:23:00   35.320000   35.360001   35.320000   35.360001     1061.0  2026-06-30   34.13       34.82  1.435955e+00   IWM  0.6078  2.1137    0.05  1.860730
46       SCO  2026-06-30 02:24:00   35.330002   35.330002   35.330002   35.330002     2903.0  2026-06-30   34.13       34.82  1.464681e+00   IWM  0.6078  2.1137     NaN  1.860730
47       SCO  2026-06-30 02:25:00   35.330002   35.330002   35.330002   35.330002       97.0  2026-06-30   34.13       34.82  1.464681e+00   IWM  0.6078  2.1137    0.03  1.860730
48       SCO  2026-06-30 02:28:00   35.299999   35.299999   35.299999   35.299999       10.0  2026-06-30   34.13       34.82  1.378516e+00   IWM  0.6078  2.1137     NaN  1.860730
49       SCO  2026-06-30 02:30:00   35.360001   35.360001   35.360001   35.360001        5.0  2026-06-30   34.13       34.82  1.550835e+00   IWM  0.6078  2.1137     NaN  1.860730
50       SCO  2026-06-30 02:33:00   35.259998   35.259998   35.240002   35.240002        5.0  2026-06-30   34.13       34.82  1.263637e+00   IWM  0.6078  2.1137     NaN  1.860730
51       SCO  2026-06-30 02:34:00   35.240002   35.240002   35.240002   35.240002      244.0  2026-06-30   34.13       34.82  1.206208e+00   IWM  0.6078  2.1137    0.02  1.860730
52       SCO  2026-06-30 02:38:00   35.320000   35.320000   35.320000   35.320000        3.0  2026-06-30   34.13       34.82  1.435955e+00   IWM  0.6078  2.1137    0.05  1.860730
53       SCO  2026-06-30 02:40:00   35.310001   35.310001   35.310001   35.310001      193.0  2026-06-30   34.13       34.82  1.407241e+00   IWM  0.6078  2.1137     NaN  1.860730
54       SCO  2026-06-30 02:42:00   35.299999   35.299999   35.299999   35.299999      235.0  2026-06-30   34.13       34.82  1.378516e+00   IWM  0.6078  2.1137     NaN  1.860730
55       SCO  2026-06-30 02:45:00   35.209999   35.209999   35.209999   35.209999      200.0  2026-06-30   34.13       34.82  1.120043e+00   IWM  0.6078  2.1137    0.02  1.860730
56       SCO  2026-06-30 02:48:00   35.200001   35.200001   35.189999   35.189999     1601.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.6078  2.1137     NaN  1.860730
57       SCO  2026-06-30 02:51:00   35.110001   35.110001   35.110001   35.110001       10.0  2026-06-30   34.13       34.82  8.328564e-01   IWM  0.6078  2.1137     NaN  1.860730
58       SCO  2026-06-30 02:52:00   35.110001   35.110001   35.110001   35.110001        1.0  2026-06-30   34.13       34.82  8.328564e-01   IWM  0.6078  2.1137    0.07  1.860730
59       SCO  2026-06-30 02:54:00   35.110001   35.110001   35.110001   35.110001      175.0  2026-06-30   34.13       34.82  8.328564e-01   IWM  0.6078  2.1137     NaN  1.860730
60       SCO  2026-06-30 03:00:00   35.049999   35.049999   35.040001   35.040001       69.0  2026-06-30   34.13       34.82  6.605377e-01   IWM  0.6078  2.1137     NaN  1.860730
61       SCO  2026-06-30 03:06:00   35.040001   35.040001   35.040001   35.040001        8.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.6078  2.1137    0.17  1.860730
62       SCO  2026-06-30 03:12:00   35.040001   35.040001   35.040001   35.040001       70.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.6078  2.1137     NaN  1.860730
63       SCO  2026-06-30 03:13:00   35.000000   35.000000   34.980000   34.980000       20.0  2026-06-30   34.13       34.82  5.169443e-01   IWM  0.6078  2.1137     NaN  1.860730
64       SCO  2026-06-30 03:15:00   34.980000   34.980000   34.980000   34.980000      160.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.6078  2.1137     NaN  1.860730
65       SCO  2026-06-30 03:16:00   34.980000   34.980000   34.980000   34.980000        2.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.6078  2.1137     NaN  1.860730
66       SCO  2026-06-30 03:22:00   34.980000   34.980000   34.950001   34.950001      215.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.6078  2.1137     NaN  1.860730
67       SCO  2026-06-30 03:26:00   34.980000   34.980000   34.980000   34.980000      200.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.6078  2.1137     NaN  1.860730
68       SCO  2026-06-30 03:31:00   34.939999   34.939999   34.900002   34.900002       27.0  2026-06-30   34.13       34.82  3.446256e-01   IWM  0.6078  2.1137     NaN  1.860730
69       SCO  2026-06-30 03:40:00   34.980000   34.980000   34.980000   34.980000        1.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.6078  2.1137     NaN  1.860730
70       SCO  2026-06-30 03:45:00   34.959999   34.970001   34.959999   34.970001     1234.0  2026-06-30   34.13       34.82  4.020651e-01   IWM  0.6078  2.1137     NaN  1.860730
71       SCO  2026-06-30 03:56:00   35.009998   35.060001   35.009998   35.060001     4327.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.6078  2.1137    0.02  1.860730
72       SCO  2026-06-30 04:00:00   35.060001   35.189999   35.009998   35.009998     2013.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.6078  2.1137    0.04  1.860730
73       SCO  2026-06-30 04:02:00   35.009998   35.200001   35.009998   35.189999     1586.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.6078  2.1137    0.00  1.860730
74       SCO  2026-06-30 04:03:00   35.200001   35.360001   34.959999   34.980000     8144.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.6078  2.1137    0.15  1.860730
75       SCO  2026-06-30 04:04:00   35.060001   35.060001   34.970001   35.009998     4659.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.6078  2.1137    0.02  1.860730
76       SCO  2026-06-30 04:12:00   34.880001   34.880001   34.880001   34.880001      200.0  2026-06-30   34.13       34.82  1.723178e-01   IWM  0.6078  2.1137    0.03  1.860730
77       SCO  2026-06-30 04:14:00   34.730000   34.740002   34.700001   34.700001     1020.0  2026-06-30   34.13       34.82 -2.584735e-01   IWM  0.6078  2.1137    0.02  1.860730
78       SCO  2026-06-30 04:19:00   34.732601   34.732601   34.732601   34.732601      471.0  2026-06-30   34.13       34.82 -2.510018e-01   IWM  0.6078  2.1137   -0.00  1.860730
79       SCO  2026-06-30 04:20:00   34.770000   34.770000   34.770000   34.770000      160.0  2026-06-30   34.13       34.82 -1.435943e-01   IWM  0.6078  2.1137    0.01  1.860730
80       SCO  2026-06-30 04:21:00   34.820000   34.820000   34.820000   34.820000      364.0  2026-06-30   34.13       34.82 -8.764382e-07   IWM  0.6078  2.1137    0.02  1.860730
81       SCO  2026-06-30 04:28:00   34.770000   34.799999   34.770000   34.799999      260.0  2026-06-30   34.13       34.82 -1.435943e-01   IWM  0.6078  2.1137    0.05  1.860730
82       SCO  2026-06-30 04:29:00   34.779999   34.779999   34.770000   34.770000      260.0  2026-06-30   34.13       34.82 -1.148800e-01   IWM  0.6078  2.1137    0.05  1.860730
83       SCO  2026-06-30 04:32:00   34.700001   34.700001   34.700001   34.700001      100.0  2026-06-30   34.13       34.82 -3.446273e-01   IWM  0.6078  2.1137     NaN  1.860730
84       SCO  2026-06-30 04:34:00   34.599998   34.639999   34.599998   34.639999      252.0  2026-06-30   34.13       34.82 -6.318252e-01   IWM  0.6078  2.1137     NaN  1.860730
85       SCO  2026-06-30 04:39:00   34.630001   34.630001   34.630001   34.630001      160.0  2026-06-30   34.13       34.82 -5.456603e-01   IWM  0.6078  2.1137   -0.11  1.860730
86       SCO  2026-06-30 04:40:00   34.660000   34.669998   34.660000   34.669998      640.0  2026-06-30   34.13       34.82 -4.595065e-01   IWM  0.6078  2.1137   -0.13  1.860730
87       SCO  2026-06-30 04:42:00   34.599998   34.599998   34.599998   34.599998      200.0  2026-06-30   34.13       34.82 -6.318252e-01   IWM  0.6078  2.1137   -0.13  1.860730
88       SCO  2026-06-30 04:46:00   34.593899   34.593899   34.593899   34.593899      150.0  2026-06-30   34.13       34.82 -6.493430e-01   IWM  0.6078  2.1137   -0.10  1.860730
89       SCO  2026-06-30 04:47:00   34.680000   34.680000   34.669998   34.669998      530.0  2026-06-30   34.13       34.82 -4.020669e-01   IWM  0.6078  2.1137   -0.10  1.860730
90       SCO  2026-06-30 04:51:00   34.639999   34.639999   34.639999   34.639999      200.0  2026-06-30   34.13       34.82 -5.169460e-01   IWM  0.6078  2.1137     NaN  1.860730
91       SCO  2026-06-30 04:56:00   34.830002   34.939999   34.830002   34.939999      300.0  2026-06-30   34.13       34.82  2.872439e-02   IWM  0.6078  2.1137   -0.03  1.860730
92       SCO  2026-06-30 04:57:00   34.869999   34.869999   34.869999   34.869999      250.0  2026-06-30   34.13       34.82  1.435926e-01   IWM  0.6078  2.1137     NaN  1.860730
93       SCO  2026-06-30 04:59:00   34.869999   34.869999   34.869999   34.869999      100.0  2026-06-30   34.13       34.82  1.435926e-01   IWM  0.6078  2.1137   -0.02  1.860730
94       SCO  2026-06-30 05:06:00   34.860001   34.860001   34.840000   34.840000      500.0  2026-06-30   34.13       34.82  1.148783e-01   IWM  0.6078  2.1137    0.01  1.860730
95       SCO  2026-06-30 05:24:00   34.660000   34.660000   34.660000   34.660000     6000.0  2026-06-30   34.13       34.82 -4.595065e-01   IWM  0.6078  2.1137     NaN  1.860730
96       SCO  2026-06-30 05:25:00   34.759998   34.759998   34.759998   34.759998      320.0  2026-06-30   34.13       34.82 -1.723196e-01   IWM  0.6078  2.1137    0.05  1.860730
97       SCO  2026-06-30 05:27:00   34.830002   34.830002   34.830002   34.830002      808.0  2026-06-30   34.13       34.82  2.872439e-02   IWM  0.6078  2.1137    0.04  1.860730
98       SCO  2026-06-30 05:30:00   34.680000   34.680000   34.590000   34.619999     1000.0  2026-06-30   34.13       34.82 -4.020669e-01   IWM  0.6078  2.1137     NaN  1.860730
99       SCO  2026-06-30 05:31:00   34.599998   34.599998   34.549999   34.549999     1298.0  2026-06-30   34.13       34.82 -6.318252e-01   IWM  0.6078  2.1137   -0.02  1.860730
100      SCO  2026-06-30 05:34:00   34.609402   34.609402   34.560001   34.560001     1513.0  2026-06-30   34.13       34.82 -6.048199e-01   IWM  0.6078  2.1137     NaN  1.860730
101      SCO  2026-06-30 05:36:00   34.529999   34.529999   34.529999   34.529999      160.0  2026-06-30   34.13       34.82 -8.328582e-01   IWM  0.6078  2.1137   -0.02  1.860730
102      SCO  2026-06-30 05:44:00   34.560001   34.560001   34.540001   34.540001      260.0  2026-06-30   34.13       34.82 -7.466934e-01   IWM  0.6078  2.1137    0.07  1.860730
103      SCO  2026-06-30 05:50:00   34.549999   34.549999   34.549999   34.549999      160.0  2026-06-30   34.13       34.82 -7.754186e-01   IWM  0.6078  2.1137     NaN  1.860730
104      SCO  2026-06-30 05:54:00   34.560001   34.560001   34.560001   34.560001      100.0  2026-06-30   34.13       34.82 -7.466934e-01   IWM  0.6078  2.1137    0.13  1.860730
105      SCO  2026-06-30 05:57:00   34.500000   34.500000   34.490002   34.490002     1508.0  2026-06-30   34.13       34.82 -9.190121e-01   IWM  0.6078  2.1137    0.13  1.860730
106      SCO  2026-06-30 05:58:00   34.459999   34.459999   34.459999   34.459999      500.0  2026-06-30   34.13       34.82 -1.033891e+00   IWM  0.6078  2.1137     NaN  1.860730
107      SCO  2026-06-30 06:01:00   34.389999   34.389999   34.389999   34.389999      100.0  2026-06-30   34.13       34.82 -1.234924e+00   IWM  0.6078  2.1137    0.12  1.860730
108      SCO  2026-06-30 06:02:00   34.380001   34.384701   34.380001   34.384701      530.0  2026-06-30   34.13       34.82 -1.263639e+00   IWM  0.6078  2.1137    0.11  1.860730
109      SCO  2026-06-30 06:03:00   34.419998   34.419998   34.419998   34.419998      160.0  2026-06-30   34.13       34.82 -1.148770e+00   IWM  0.6078  2.1137    0.11  1.860730

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,SCO,2026-06-30 00:23:00,34.900002,34.900002,34.900002,34.900002,8.0,2026-06-30,34.13,34.82,0.229757,IWM,0.6078,2.1137,NaN,1.860730
1,SCO,2026-06-30 00:26:00,34.939999,34.939999,34.939999,34.939999,1.0,2026-06-30,34.13,34.82,0.344626,IWM,0.6078,2.1137,NaN,1.860730
2,SCO,2026-06-30 00:28:00,35.000000,35.009998,35.000000,35.009998,205.0,2026-06-30,34.13,34.82,0.516944,IWM,0.6078,2.1137,NaN,1.860730
3,SCO,2026-06-30 00:31:00,35.009998,35.009998,35.009998,35.009998,12.0,2026-06-30,34.13,34.82,0.545659,IWM,0.6078,2.1137,NaN,1.860730
4,SCO,2026-06-30 00:34:00,34.990002,34.990002,34.990002,34.990002,11.0,2026-06-30,34.13,34.82,0.488230,IWM,0.6078,2.1137,NaN,1.860730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,SHIP,2026-06-30 15:32:00,13.460000,13.470000,13.440000,13.470000,1319.0,2026-06-30,13.61,13.62,-1.174743,SPY,-0.0460,-0.0486,0.87,0.631341
21146,SHIP,2026-06-30 15:34:00,13.455000,13.455000,13.455000,13.455000,100.0,2026-06-30,13.61,13.62,-1.211454,SPY,-0.0460,-0.0486,0.87,0.631341
21147,SHIP,2026-06-30 15:37:00,13.460000,13.460000,13.460000,13.460000,300.0,2026-06-30,13.61,13.62,-1.174743,SPY,-0.0460,-0.0486,0.81,0.631341
21148,SHIP,2026-06-30 15:38:00,13.455000,13.469100,13.450000,13.469100,681.0,2026-06-30,13.61,13.62,-1.211454,SPY,-0.0460,-0.0486,0.80,0.631341
21149,SHIP,2026-06-30 15:39:00,13.470000,13.505000,13.470000,13.485000,1000.0,2026-06-30,13.61,13.62,-1.101320,SPY,-0.0460,-0.0486,0.80,0.631341

In [48]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional, List

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
    import pyarrow.compute as pc
except Exception:
    pa = pq = ds = pc = None


def _as_f64(col):
    """ChunkedArray -> float64 без походу в pandas (fallback лише для нечислових типів)."""
    if pa.types.is_floating(col.type) or pa.types.is_integer(col.type):
        return col.cast(pa.float64()) if col.type != pa.float64() else col
    if pa.types.is_decimal(col.type):
        return col.cast(pa.float64())
    return pa.chunked_array([pa.array(
        pd.to_numeric(col.to_pandas(), errors="coerce").to_numpy(dtype="float64"))])


def _round_like_numpy(col, ndigits):
    """np.round над Arrow-колонкою + NaN -> null (як робив pa.Table.from_pandas)."""
    if len(col) == 0:
        return col
    v = col.to_numpy(zero_copy_only=False)   # може бути read-only zero-copy view
    if ndigits is not None:
        v = np.round(v, int(ndigits))
    return pa.array(v, from_pandas=True)


def _add_tp_deviation_devsig(table, *, round_tp_dev=2, round_devsig=6, dt_as_timestamp=False):
    """t_p / deviation / dev_sig як арифметика Arrow над колонками таблиці.

    Раніше кожен батч ходив у pandas і назад (batch.to_pandas() +
    pa.Table.from_pandas()). Для рядкових колонок ticker/dt/date/bench це означало
    матеріалізацію мільйонів python-об'єктів str на кожному батчі й повне
    перезбирання Arrow-масивів — найдорожча частина того циклу. Тут таблиця
    лишається в Arrow від читання до запису.
    """
    names = {n.strip().lower(): n for n in table.column_names}
    stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
    bench_col = names.get("bench%")
    beta_col = names.get("beta")
    sigma_col = names.get("sigma")

    need = {
        "stack%/pct_vs_prev_close": stack_col,
        "bench%": bench_col,
        "beta": beta_col,
        "sigma": sigma_col,
    }
    missing = [k for k, v in need.items() if v is None]
    if missing:
        raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

    drop = [c for c in ("t_p", "deviation", "dev_sig") if c in table.column_names]
    if drop:
        table = table.drop_columns(drop) if hasattr(table, "drop_columns") else table.drop(drop)

    stack = _as_f64(table[stack_col])
    beta = _as_f64(table[beta_col])
    bench = _as_f64(table[bench_col])
    sigma = _as_f64(table[sigma_col])

    tp = pc.multiply(stack, beta)
    dev = pc.subtract(tp, bench)
    denom = pc.if_else(pc.equal(sigma, 0), pa.scalar(None, pa.float64()), sigma)  # sigma 0 -> NaN
    dsg = pc.divide(dev, denom)

    # Округлення саме через np.round, а не pc.round: на значеннях, які вже округлені
    # вище по пайплайну (Stack% до 2 знаків, beta до 4), добуток лягає впритул до
    # межі .005, і pc.round подекуди дає результат на 1 ULP інший за np.round.
    # np.round тут ще й трохи швидший, а pa.array(..., from_pandas=True) відтворює
    # ту саму семантику NaN -> null, що давав старий pa.Table.from_pandas().
    tp = _round_like_numpy(tp, round_tp_dev)
    dev = _round_like_numpy(dev, round_tp_dev)
    dsg = _round_like_numpy(dsg, round_devsig)

    if dt_as_timestamp and "dt" in table.column_names and pa.types.is_string(table["dt"].type):
        i = table.column_names.index("dt")
        table = table.set_column(i, "dt", pc.strptime(table["dt"], format="%Y-%m-%d %H:%M:%S",
                                                      unit="ns", error_is_null=True))

    return (table.append_column("t_p", tp)
                 .append_column("deviation", dev)
                 .append_column("dev_sig", dsg))


def _sort_keys(schema_names):
    keys = [("ticker", "ascending")]
    if "date" in schema_names:
        keys.append(("date", "ascending"))
    if "dt" in schema_names:
        keys.append(("dt", "ascending"))
    return keys


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # batch_rows для потокового режиму / бакетування
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,
    max_rows_in_memory: int = 20_000_000,
    dt_as_timestamp: bool = False,
    row_group_size: int = 2_000_000,
) -> str:
    """
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.

    Якщо sort_final_by_ticker=True, output_path фізично відсортований:
    ticker A→Z, всередині тикера date,dt.

    Що змінилось проти попередньої версії:
      1. Обчислення і сортування — ОДИН прохід. Раніше спершу писався повний
         tmp_unsorted, потім він читався назад і переписувався відсортованим:
         3 читання + 3 записи всього файла. Тепер 1 читання + 1 запис
         (або 2+2, якщо файл не влазить у пам'ять і потрібні бакети).
      2. Уся арифметика в Arrow — без batch.to_pandas()/pa.Table.from_pandas()
         на кожному батчі (це матеріалізувало рядкові колонки як python-об'єкти).
      3. Сортування ПЕРЕД додаванням t_p/deviation/dev_sig — take() переставляє
         на 3 float64-колонки менше.
      4. Бакетування по тикерах — через pc.index_in замість pandas .map по рядках.
      5. row_group_size=2M замість дефолтного 1M: менше row-груп → швидший запис,
         трохи менший файл, і стратегії-споживачі (вони читають
         iter_batches(batch_size=1_000_000)) теж читають його швидше.
    """
    if pq is None or pa is None or ds is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet, pyarrow.dataset).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    total_rows = dataset.count_rows()

    tmp_out = output_path + f".tmp_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    def _finish(rows, mode):
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_out, output_path)
        print(f"✅ DONE ({mode}): {rows:,} rows → {output_path} | "
              f"total_time={time.time()-t0:,.1f}s", flush=True)
        return output_path

    # ---------- 1) без сортування: чистий стрім, один прохід ----------
    if not sort_final_by_ticker:
        print(f"▶ START (stream): {input_path} → {output_path} | "
              f"rows={total_rows:,} batch={chunksize:,}", flush=True)
        writer = None
        written = 0
        try:
            for bi, rb in enumerate(dataset.to_batches(batch_size=chunksize), 1):
                if rb.num_rows == 0:
                    continue
                tbl = _add_tp_deviation_devsig(
                    pa.Table.from_batches([rb]), round_tp_dev=round_tp_dev,
                    round_devsig=round_devsig, dt_as_timestamp=dt_as_timestamp)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl, row_group_size=row_group_size)
                written += tbl.num_rows
                if bi % 5 == 0:
                    print(f"[batch {bi:>4}] rows={written:,}  "
                          f"elapsed={time.time()-t0:,.1f}s", flush=True)
        finally:
            if writer is not None:
                writer.close()
        return _finish(written, "stream")

    keys = _sort_keys(schema_names)
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    # ---------- 2) влазить у пам'ять: читання → сорт → рахунок → запис ----------
    if total_rows <= max_rows_in_memory:
        print(f"▶ START (in-memory sort): {input_path} → {output_path} | "
              f"rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        table = _add_tp_deviation_devsig(
            table, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
            dt_as_timestamp=dt_as_timestamp)
        pq.write_table(table, tmp_out, compression=compression,
                       row_group_size=row_group_size)
        written = table.num_rows
        del table
        gc.collect()
        return _finish(written, "in-memory sort")

    # ---------- 3) не влазить: один прохід у бакети, далі сорт кожного ----------
    n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
    tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
    tickers = sorted(str(t) for t in tickers if t is not None)
    # суміжні діапазони тикерів → порядок бакетів = порядок тикерів
    edges = np.array_split(np.arange(len(tickers)), n_buckets)
    rank_to_bucket = np.zeros(len(tickers), dtype="int32")
    for b, idxs in enumerate(edges):
        rank_to_bucket[idxs] = b
    ticker_set = pa.array(tickers, type=pa.string())
    rank_to_bucket_arr = pa.array(rank_to_bucket)

    print(f"▶ START (bucketed sort): {input_path} → {output_path} | rows={total_rows:,} "
          f"tickers={len(tickers):,} buckets={n_buckets}", flush=True)

    bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
    bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
    try:
        for rb in dataset.to_batches(batch_size=chunksize):
            if rb.num_rows == 0:
                continue
            tbl = pa.Table.from_batches([rb])
            # ранг тикера в відсортованому списку → номер бакета, повністю в Arrow
            ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
            bidx = pc.take(rank_to_bucket_arr, ranks)
            for b in range(n_buckets):
                mask = pc.equal(bidx, b)
                if not pc.any(mask).as_py():
                    continue
                part = tbl.filter(mask)
                if part.num_rows == 0:
                    continue
                if bwriters[b] is None:
                    bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                   compression=compression)
                bwriters[b].write_table(part)
    finally:
        for w in bwriters:
            if w is not None:
                w.close()

    writer = None
    written = 0
    try:
        for b, bp in enumerate(bucket_paths):
            if not os.path.exists(bp):
                continue
            tbl = pq.read_table(bp).sort_by(keys)
            tbl = _add_tp_deviation_devsig(
                tbl, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
                dt_as_timestamp=dt_as_timestamp)
            if writer is None:
                writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
            writer.write_table(tbl, row_group_size=row_group_size)
            written += tbl.num_rows
            del tbl
            gc.collect()
            print(f"  bucket {b+1}/{n_buckets}  written={written:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)
    finally:
        if writer is not None:
            writer.close()
        for bp in bucket_paths:
            if os.path.exists(bp):
                os.remove(bp)

    return _finish(written, "bucketed sort")


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    max_rows_in_memory: int = 20_000_000,
    log_every: int = 200,            # лишено для сумісності виклику
    roundtrip_pandas: bool = True,   # лишено для сумісності виклику
):
    """Лише сортування parquet: ticker A→Z, всередині тикера (date, dt).

    Обчислення t_p/deviation/dev_sig тепер робить сам recompute_tp_deviation_devsig
    у тому ж проході, тож окремо ця функція потрібна лише якщо треба відсортувати
    вже готовий файл.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")
    keys = _sort_keys(schema_names)

    total_rows = dataset.count_rows()
    t0 = time.time()
    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    if total_rows <= max_rows_in_memory:
        print(f"▶ SORT (in-memory): rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        pq.write_table(table, tmp_out, compression=compression)
        written = table.num_rows
        del table
        gc.collect()
    else:
        n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
        tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
        tickers = sorted(str(t) for t in tickers if t is not None)
        rank_to_bucket = np.zeros(len(tickers), dtype="int32")
        for b, idxs in enumerate(np.array_split(np.arange(len(tickers)), n_buckets)):
            rank_to_bucket[idxs] = b
        ticker_set = pa.array(tickers, type=pa.string())
        rank_to_bucket_arr = pa.array(rank_to_bucket)
        print(f"▶ SORT (bucketed): rows={total_rows:,} tickers={len(tickers):,} "
              f"buckets={n_buckets}", flush=True)

        bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
        bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
        try:
            for rb in dataset.to_batches():
                if rb.num_rows == 0:
                    continue
                tbl = pa.Table.from_batches([rb])
                ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
                bidx = pc.take(rank_to_bucket_arr, ranks)
                for b in range(n_buckets):
                    mask = pc.equal(bidx, b)
                    if not pc.any(mask).as_py():
                        continue
                    part = tbl.filter(mask)
                    if part.num_rows == 0:
                        continue
                    if bwriters[b] is None:
                        bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                       compression=compression)
                    bwriters[b].write_table(part)
        finally:
            for w in bwriters:
                if w is not None:
                    w.close()

        writer = None
        written = 0
        try:
            for b, bp in enumerate(bucket_paths):
                if not os.path.exists(bp):
                    continue
                tbl = pq.read_table(bp).sort_by(keys)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl)
                written += tbl.num_rows
                del tbl
                gc.collect()
        finally:
            if writer is not None:
                writer.close()
            for bp in bucket_paths:
                if os.path.exists(bp):
                    os.remove(bp)

    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)
    print(f"✅ SORT DONE: {written:,} rows → {output_path} | time={time.time()-t0:,.1f}s", flush=True)
    return output_path

In [49]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (bucketed sort): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | rows=109,067,647 tickers=7,853 buckets=6

  bucket 1/6  written=18,105,794  elapsed=83.2s

  bucket 2/6  written=35,904,138  elapsed=101.2s

  bucket 3/6  written=53,015,598  elapsed=118.5s

  bucket 4/6  written=71,438,462  elapsed=137.1s

  bucket 5/6  written=91,039,290  elapsed=157.9s

  bucket 6/6  written=109,067,647  elapsed=176.2s

✅ DONE (bucketed sort): 109,067,647 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=176.4s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'