In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=2)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 2, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-04-28 00:00:00
end   = 2026-06-28 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-04-28
end_date_str   = 2026-06-28

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    53647.16
1     AA  1514050.29
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 13221

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,343 рядків

  ticker       value                         lvl3  market_cap
0      A    53647.16  Medical Equipment & Devices     37515.0
1     AA  1514050.29              Metals & Mining     14110.0
2   AAAU   387243.60                          NaN         NaN
3   AACG       25.65                     Software        41.0
4   AADX    75350.51          Aerospace & Defense      3539.0

In [7]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [8]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 59 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Elec & Gas Marketing & Trading',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [9]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "IBIT"],
    "Banking": ["KRE", "XLF", "SPY", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "SPY", "IBIT"],
    "Insurance": ["XLF", "SPY", "IBIT"],
    "Specialty Finance": ["XLF", "SPY", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV", "QQQ", "IWM", "SPY"],  
    "IT Services": ["IGV", "QQQ", "IWM", "SPY"],
    "Semiconductors": ["DRAM", "SMH", "SOXX", "QQQ", "IWM", "SPY"],  # + DRAM
    "Technology Hardware": ["DRAM", "XLK", "QQQ", "SOXX", "IWM", "SPY"],  # + DRAM
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["ITA", "XLI", "IWM", "SPY"], 
    "Diversified Industrials": ["XLI", "SPY", "IWM"],
    "Industrial Intermediate Prod": ["XLI", "IWM", "SPY"],
    "Industrial Support Services": ["XLI", "IWM", "SPY"],
    "Engineering & Construction": ["XLI", "IWM", "SPY"],
    "Machinery": ["XLI", "IWM", "SPY"],
    "Transportation & Logistics": ["XTN", "XLI", "IWM", "SPY"],  
    "Transportation Equipment": ["XLI", "IWM", "SPY"],
    "Commercial Support Services": ["XLI", "IWM", "SPY"],
    "Containers & Packaging": ["XLI", "IWM", "SPY"],
    "Electrical Equipment": ["XLI", "QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["OIH", "XLE", "IWM", "SPY"],  
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLU", "XLE", "IWM", "SPY"],         
    "Gas & Water Utilities": ["XLU", "IWM", "SPY"],
    "Renewable Energy": ["ICLN", "XLE", "IWM", "SPY"],           
    "Chemicals": ["XLB", "XLE", "IWM", "SPY"],                  
    "Metals & Mining": ["GDX", "XLB", "IWM", "SPY"],
    "Steel": ["SLX", "GDX", "XLB", "IWM", "SPY"],             
    "Construction Materials": ["XLB", "IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["IBB", "XBI", "QQQ", "IWM", "SPY"], 
    "Medical Equipment & Devices": ["IHI", "XLV", "IWM", "SPY"], 
    "Health Care Facilities & Svcs": ["IHF", "XLV", "IWM", "SPY"], 

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP", "SPY", "IWM"],
    "Beverages": ["XLP", "SPY", "IWM"],
    "Household Products": ["XLP", "SPY", "IWM"],
    "Tobacco & Cannabis": ["XLP", "SPY", "IWM"],
    "Retail - Consumer Staples": ["XLP", "SPY", "IWM"],
    "Wholesale - Consumer Staples": ["XLP", "SPY", "IWM"],

    "Retail - Discretionary": ["XRT", "XLY", "SPY", "IWM"], 
    "Wholesale - Discretionary": ["XLY", "SPY", "IWM"],
    "Consumer Services": ["XLY", "SPY", "IWM"],
    "Leisure Facilities & Services": ["XLY", "SPY", "IWM"],
    "Leisure Products": ["XLY", "SPY", "IWM"],
    "Apparel & Textile Products": ["XLY", "SPY", "IWM", "QQQ"],
    "Automotive": ["XLY", "SPY", "IWM", "QQQ"],
    "Home & Office Products": ["XLY", "SPY", "IWM"],
    "Home Construction": ["XHB", "IWM", "SPY"],          

    # --- Real Estate ---
    "REIT": ["VNQ", "IWM", "SPY"], 
    "Real Estate Owners & Developers": ["VNQ", "IWM", "SPY"],
    "Real Estate Services": ["VNQ", "IWM", "SPY"],
}

In [10]:
# ------------------------------------------------

In [11]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [12]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
):
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    def _fetch_gap(t):
        try:
            dfg = DatumApi.data_request("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = DatumApi.data_request("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(64, len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [13]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7343 etfs=32 window=2026-04-28..2026-06-28

DONE pairs: 7128 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 7128 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: UNKNOWN

  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.247855  0.243180  Advertising & Marketing         39
1      ADV     KWEB  0.151935  0.103544  Advertising & Marketing         39
2      ADV      IWM  0.300493  0.412284  Advertising & Marketing         39
3      ADV      SPY  0.282711  0.534664  Advertising & Marketing         39
4     AEHL      QQQ  0.193802  0.952887  Advertising & Marketing         39
Rows in raw stock-etf pairs: 25816
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           IWM   0.300493        0.412284  Advertising & Marketing
1     AEHL          KWEB   0.359318        1.258499  Advertising & Marketing
2      APP           SPY   0.231560        0.579882  Advertising & Marketing
3     AREN           IWM   0.183290        0.505711  Advertising & Marketing
4     BAOS           QQQ   0.121844        0.297036  Advertising & Marketing

   n_overlap
0         39
1         39
2         39
3         39
4         39
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [14]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [15]:
TICKERS

     ticker       value                         lvl3  market_cap
0         A    53647.16  Medical Equipment & Devices     37515.0
1        AA  1514050.29              Metals & Mining     14110.0
2      AAAU   387243.60                          NaN         NaN
3      AACG       25.65                     Software        41.0
4      AADX    75350.51          Aerospace & Defense      3539.0
...     ...         ...                          ...         ...
7338   ZVOL     1070.46                          NaN         NaN
7339   ZVRA    27003.08             Biotech & Pharma       828.0
7340    ZWS     2152.79                    Machinery      8330.0
7341   ZYBT       80.99             Biotech & Pharma        20.0
7342   ZYME    60755.87             Biotech & Pharma      1773.0

[7343 rows x 4 columns]

In [16]:
import pandas as pd

# список тикерів
tickers = [
    'SPY', 'IWM', 'GDX', 'XLF', 'QQQ', 'XLE', 'KRE', 'IBIT', 'KWEB', 'XLP', 'SOXX',
    'IGV', 'SMH', 'XLK', 'ITA', 'XLI', 'XTN', 'OIH', 'XLU', 'ICLN', 'XLB', 'SLX',
    'IBB', 'XBI', 'IHI', 'XLV', 'IHF', 'XRT', 'XLY', 'XHB', 'VNQ',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0     SPY
1     IWM
2     GDX
3     XLF
4     QQQ
5     XLE
6     KRE
7    IBIT
8    KWEB
9     XLP
10   SOXX
11    IGV
12    SMH
13    XLK
14    ITA
15    XLI
16    XTN
17    OIH
18    XLU
19   ICLN
20    XLB
21    SLX
22    IBB
23    XBI
24    IHI
25    XLV
26    IHF
27    XRT
28    XLY
29    XHB
30    VNQ

In [17]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=16,
    parallel_tickers=True,
    max_workers_tickers=16,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 56 тікерів (пропущено 0 по старому маніфесту) | 2026-04-28 00:00:00 → 2026-06-28 23:59:59 | interval=1 | next batch #9739 | run=59168f0f

   workers: tickers=16, chunks=16 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 7287

   📉 пропущені дні (в межах window): 2026-04-28 → 2026-06-28 (62 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 261.4 MB

[10/56] – ASMH: empty |  17.86% | ETA 00:08

[20/56] – IIPR/PA: empty |  35.71% | ETA 00:05

[30/56] – NVNO: empty |  53.57% | ETA 00:03

[40/56] – RHLD: empty |  71.43% | ETA 00:01

[50/56] – TAFI: empty |  89.29% | ETA 00:00

   • RAM · 🧠 RAM: 282.0 MB

   ⏳ перед flush · 🧠 RAM: 281.8 MB

💾 batch 9739 → 10,452 рядків (всього 10,452 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_9739.csv.gz

   ✅ після flush · 🧠 RAM: 286.5 MB

[56/56] – TBX: empty | 100.00% | ETA 00:00

   🔚 фінал · 🧠 RAM: 270.0 MB

🏁 Готово. Нових рядків: 10,452 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 00:06

In [18]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [19]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2026-04-28..2026-06-28]

✅ DONE  in=302,324,785 → out=77,717,692  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 1,729.9s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [20]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [21]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [22]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [23]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=93.4s

[batch   10] rows=20,000,000  elapsed=183.1s

[batch   15] rows=30,000,000  elapsed=278.6s

[batch   20] rows=40,000,000  elapsed=372.6s

[batch   25] rows=50,000,000  elapsed=466.8s

[batch   30] rows=60,000,000  elapsed=563.9s

[batch   35] rows=70,000,000  elapsed=658.7s

✅ DONE  rows=77,717,692  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 734.0s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [24]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [25]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=10.5s

[batch   10] rows=20,000,000  elapsed=21.6s

[batch   15] rows=30,000,000  elapsed=30.4s

[batch   20] rows=40,000,000  elapsed=40.1s

[batch   25] rows=50,000,000  elapsed=51.5s

[batch   30] rows=60,000,000  elapsed=63.0s

[batch   35] rows=70,000,000  elapsed=72.2s

✅ DONE  rows=77,717,692  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 81.6s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [26]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [27]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [28]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [29]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=21.6s

[batch   10] rows=20,000,000  elapsed=46.0s

[batch   15] rows=30,000,000  elapsed=68.4s

[batch   20] rows=40,000,000  elapsed=90.5s

[batch   25] rows=50,000,000  elapsed=114.9s

[batch   30] rows=60,000,000  elapsed=136.3s

[batch   35] rows=70,000,000  elapsed=160.4s

✅ DONE rows=77,717,692 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 180.0s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [30]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [31]:
peek_parquet(str(WORK_DIR / "premarket_rows_final.parquet"), n=620)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet
Рядків (meta): 77,717,692
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:

    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench    corr   beta
0        A 2026-04-28 00:00:00  116.320000  116.320000  116.320000  116.320000      10.0  2026-04-28  116.23      115.61    0.61   XLV  0.5579  0.812
1        A 2026-04-28 09:29:00  116.430000  116.440002  116.430000  116.440002     200.0  2026-04-28  116.23      115.61    0.71   XLV  0.5579  0.812
2        A 2026-04-28 09:30:00  116.230003  116.635002  115.970001  116.279999   18280.0  2026-04-28  116.23      115.61    0.54   XLV  0.5579  0.812
3        A 2026-04-28 09:31:00  116.459999  116.459999  116.230003  116.230003     200.0  2026-04-28  116.23      115.61    0.74   XLV  0.5579  0.812
4        A 2026-04-28 09:32:00  116.275002  116.540001  116.250000  116.540001    1000.0  2026-04-28  116.23      115.61    0.58   XLV  0.5579  0.812
5        A 2026-04-28 09:33:00  116.275002  116.275002  116.275002  116.275002     100.0  2026-04-28  116.23      115.61    0.58   XLV  0.5579  0.812
6        A 2026-04-28 09:34:00  116.570000  116.620003  116.154999  116.154999    4509.0  2026-04-28  116.23      115.61    0.83   XLV  0.5579  0.812
7        A 2026-04-28 09:35:00  116.154999  116.290001  115.949997  116.099998    1909.0  2026-04-28  116.23      115.61    0.47   XLV  0.5579  0.812
8        A 2026-04-28 09:36:00  115.959999  116.105003  115.875000  115.949997    1490.0  2026-04-28  116.23      115.61    0.30   XLV  0.5579  0.812
9        A 2026-04-28 09:37:00  115.949997  116.209999  115.820000  116.209999    7862.0  2026-04-28  116.23      115.61    0.29   XLV  0.5579  0.812
10       A 2026-04-28 09:38:00  116.129997  116.290001  115.900002  116.110001    3835.0  2026-04-28  116.23      115.61    0.45   XLV  0.5579  0.812
11       A 2026-04-28 09:39:00  116.120003  116.120003  116.120003  116.120003     100.0  2026-04-28  116.23      115.61    0.44   XLV  0.5579  0.812
12       A 2026-04-28 09:40:00  115.919998  116.360001  115.915001  116.000000    5120.0  2026-04-28  116.23      115.61    0.27   XLV  0.5579  0.812
13       A 2026-04-28 09:41:00  116.114998  116.250000  116.000000  116.025002    2301.0  2026-04-28  116.23      115.61    0.44   XLV  0.5579  0.812
14       A 2026-04-28 09:42:00  116.139999  116.180000  116.059998  116.165001    3244.0  2026-04-28  116.23      115.61    0.46   XLV  0.5579  0.812
15       A 2026-04-28 09:43:00  116.165001  116.165001  115.650002  115.824997   20094.0  2026-04-28  116.23      115.61    0.48   XLV  0.5579  0.812
16       A 2026-04-28 09:44:00  115.824997  116.019997  115.824997  115.970001     505.0  2026-04-28  116.23      115.61    0.19   XLV  0.5579  0.812
17       A 2026-04-28 09:45:00  116.010002  116.199997  115.989998  116.099998    3811.0  2026-04-28  116.23      115.61    0.35   XLV  0.5579  0.812
18       A 2026-04-28 09:46:00  116.019997  116.040001  115.529999  115.620003   12822.0  2026-04-28  116.23      115.61    0.35   XLV  0.5579  0.812
19       A 2026-04-28 09:47:00  115.769997  115.839996  115.540001  115.540001    2159.0  2026-04-28  116.23      115.61    0.14   XLV  0.5579  0.812
20       A 2026-04-28 09:48:00  115.360001  115.360001  114.884598  114.884598     992.0  2026-04-28  116.23      115.61   -0.22   XLV  0.5579  0.812
21       A 2026-04-28 09:49:00  115.110001  115.110001  114.879997  114.879997    1160.0  2026-04-28  116.23      115.61   -0.43   XLV  0.5579  0.812
22       A 2026-04-28 09:50:00  115.025002  115.169998  114.879997  115.045670    9298.0  2026-04-28  116.23      115.61   -0.51   XLV  0.5579  0.812
23       A 2026-04-28 09:51:00  115.169998  115.400002  115.169998  115.400002    1500.0  2026-04-28  116.23      115.61   -0.38   XLV  0.5579  0.812
24       A 2026-04-28 09:52:00  115.285004  115.410004  115.269997  115.400002     900.0  2026-04-28  116.23      115.61   -0.28   XLV  0.5579  0.812
25       A 2026-04-28 09:53:00  115.230003  115.300003  115.139999  115.169998   16146.0  2026-04-28  116.23      115.61   -0.33   XLV  0.5579  0.812
26       A 2026-04-28 09:54:00  115.305000  115.305000  115.305000  115.305000     600.0  2026-04-28  116.23      115.61   -0.26   XLV  0.5579  0.812
27       A 2026-04-28 09:55:00  115.305000  115.309998  114.980003  114.980003    5607.0  2026-04-28  116.23      115.61   -0.26   XLV  0.5579  0.812
28       A 2026-04-28 09:56:00  115.095001  115.250000  114.980003  115.095001    5800.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.812
29       A 2026-04-28 09:57:00  115.095001  115.095001  115.000000  115.089996    1347.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.812
30       A 2026-04-28 09:58:00  115.080002  115.080002  114.760002  114.760002    2638.0  2026-04-28  116.23      115.61   -0.46   XLV  0.5579  0.812
31       A 2026-04-28 09:59:00  114.760002  114.839996  114.480003  114.480003    3730.0  2026-04-28  116.23      115.61   -0.74   XLV  0.5579  0.812
32       A 2026-04-28 10:00:00  114.480003  114.660004  114.260002  114.639999    6586.0  2026-04-28  116.23      115.61   -0.98   XLV  0.5579  0.812
33       A 2026-04-28 10:01:00  114.635002  114.870003  114.610001  114.870003    3617.0  2026-04-28  116.23      115.61   -0.84   XLV  0.5579  0.812
34       A 2026-04-28 10:02:00  114.739998  114.959999  114.739998  114.775002   11826.0  2026-04-28  116.23      115.61   -0.75   XLV  0.5579  0.812
35       A 2026-04-28 10:03:00  114.775002  114.775002  114.769997  114.769997     306.0  2026-04-28  116.23      115.61   -0.72   XLV  0.5579  0.812
36       A 2026-04-28 10:04:00  114.769997  115.129997  114.769997  114.970001    6825.0  2026-04-28  116.23      115.61   -0.73   XLV  0.5579  0.812
37       A 2026-04-28 10:05:00  114.970001  115.129997  114.800003  115.120003   11839.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.812
38       A 2026-04-28 10:06:00  115.105003  115.129997  115.080002  115.120003    3696.0  2026-04-28  116.23      115.61   -0.44   XLV  0.5579  0.812
39       A 2026-04-28 10:07:00  115.160004  115.250000  115.080002  115.080002    1389.0  2026-04-28  116.23      115.61   -0.39   XLV  0.5579  0.812
40       A 2026-04-28 10:08:00  115.080002  115.199501  115.070000  115.199501    1081.0  2026-04-28  116.23      115.61   -0.46   XLV  0.5579  0.812
41       A 2026-04-28 10:09:00  115.070000  115.154999  115.070000  115.154999    1130.0  2026-04-28  116.23      115.61   -0.47   XLV  0.5579  0.812
42       A 2026-04-28 10:10:00  115.154999  115.154999  115.070000  115.070000     319.0  2026-04-28  116.23      115.61   -0.39   XLV  0.5579  0.812
43       A 2026-04-28 10:11:00  115.129997  115.169998  114.900002  115.019997    2200.0  2026-04-28  116.23      115.61   -0.42   XLV  0.5579  0.812
44       A 2026-04-28 10:12:00  114.889999  115.000000  114.889999  115.000000     300.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.812
45       A 2026-04-28 10:13:00  114.889999  115.025002  114.889999  115.019997    2799.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.812
46       A 2026-04-28 10:14:00  114.830002  114.879997  114.830002  114.879997     300.0  2026-04-28  116.23      115.61   -0.67   XLV  0.5579  0.812
47       A 2026-04-28 10:15:00  114.809998  115.000000  114.449997  114.470001   61813.0  2026-04-28  116.23      115.61   -0.69   XLV  0.5579  0.812
48       A 2026-04-28 10:16:00  114.434998  114.434998  114.434998  114.434998     100.0  2026-04-28  116.23      115.61   -1.02   XLV  0.5579  0.812
49       A 2026-04-28 10:17:00  114.419998  114.540001  114.300003  114.315002    3963.0  2026-04-28  116.23      115.61   -1.03   XLV  0.5579  0.812
50       A 2026-04-28 10:18:00  114.239998  114.300003  114.099998  114.254997    1580.0  2026-04-28  116.23      115.61   -1.19   XLV  0.5579  0.812
51       A 2026-04-28 10:19:00  114.254997  114.419998  114.209999  114.419998    1800.0  2026-04-28  116.23      115.61   -1.17   XLV  0.5579  0.812
52       A 2026-04-28 10:20:00  114.519997  114.739998  114.519997  114.639999    2310.0  2026-04-28  116.23      115.61   -0.94   XLV  0.5579  0.812
53       A 2026-04-28 10:21:00  114.709999  114.709999  114.709999  114.709999     100.0  2026-04-28  116.23      115.61   -0.78   XLV  0.5579  0.812
54       A 2026-04-28 10:22:00  114.675003  114.675003  114.550003  114.550003     200.0  2026-04-28  116.23      115.61   -0.81   XLV  0.5579  0.812
55       A 2026-04-28 10:23:00  114.589996  114.605003  114.559998  114.605003     500.0  2026-04-28  116.23      115.61   -0.88   XLV  0.5579  0.812
56       A 2026-04-28 10:24:00  114.790001  114.809998  114.790001  114.800003    2440.0  2026-04-28  116.23      115.61   -0.71   XLV  0.5579  0.812
57       A 2026-04-28 10:26:00  114.760002  114.830002  114.760002  114.764999     800.0  2026-04-28  116.23      115.61   -0.74   XLV  0.5579  0.812
58       A 2026-04-28 10:27:00  114.639999  114.750000  114.639999  114.730675    1295.0  2026-04-28  116.23      115.61   -0.84   XLV  0.5579  0.812
59       A 2026-04-28 10:28:00  114.762497  114.762497  114.745003  114.745003     200.0  2026-04-28  116.23      115.61   -0.73   XLV  0.5579  0.812
60       A 2026-04-28 10:29:00  114.745003  114.745003  114.570000  114.625000    3553.0  2026-04-28  116.23      115.61   -0.75   XLV  0.5579  0.812
61       A 2026-04-28 10:30:00  114.625000  114.625000  114.625000  114.625000     500.0  2026-04-28  116.23      115.61   -0.85   XLV  0.5579  0.812
62       A 2026-04-28 10:31:00  114.620003  114.887901  114.620003  114.887901    3143.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.812
63       A 2026-04-28 10:32:00  114.809998  114.809998  114.610001  114.610001    1005.0  2026-04-28  116.23      115.61   -0.69   XLV  0.5579  0.812
64       A 2026-04-28 10:33:00  114.620003  114.625000  114.599998  114.620003     700.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.812
65       A 2026-04-28 10:34:00  114.620003  114.620003  114.480003  114.480003     700.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.812
66       A 2026-04-28 10:35:00  114.620003  114.620003  114.455002  114.614998     748.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.812
67       A 2026-04-28 10:36:00  114.654999  114.654999  114.654999  114.654999     300.0  2026-04-28  116.23      115.61   -0.83   XLV  0.5579  0.812
68       A 2026-04-28 10:37:00  114.705002  114.705002  114.705002  114.705002     600.0  2026-04-28  116.23      115.61   -0.78   XLV  0.5579  0.812
69       A 2026-04-28 10:38:00  114.610001  114.705002  114.610001  114.635002    1100.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.812
70       A 2026-04-28 10:39:00  114.692497  114.772797  114.510002  114.772797    6167.0  2026-04-28  116.23      115.61   -0.79   XLV  0.5579  0.812
71       A 2026-04-28 10:40:00  114.889999  114.900002  114.889999  114.900002     200.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.812
72       A 2026-04-28 10:41:00  114.910004  115.040001  114.910004  115.040001    2160.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.812
73       A 2026-04-28 10:42:00  114.985001  115.080002  114.919998  115.080002    5331.0  2026-04-28  116.23      115.61   -0.54   XLV  0.5579  0.812
74       A 2026-04-28 10:43:00  114.959999  114.989998  114.930000  114.930000    1155.0  2026-04-28  116.23      115.61   -0.56   XLV  0.5579  0.812
75       A 2026-04-28 10:44:00  114.860001  114.879997  114.849998  114.879997     806.0  2026-04-28  116.23      115.61   -0.65   XLV  0.5579  0.812
76       A 2026-04-28 10:45:00  114.879997  114.879997  114.779999  114.875000    1272.0  2026-04-28  116.23      115.61   -0.63   XLV  0.5579  0.812
77       A 2026-04-28 10:46:00  114.779999  114.779999  114.750000  114.760002    1196.0  2026-04-28  116.23      115.61   -0.72   XLV  0.5579  0.812
78       A 2026-04-28 10:47:00  114.760002  114.959999  114.760002  114.879997    2600.0  2026-04-28  116.23      115.61   -0.74   XLV  0.5579  0.812
79       A 2026-04-28 10:50:00  114.879997  114.919998  114.879997  114.879997     800.0  2026-04-28  116.23      115.61   -0.63   XLV  0.5579  0.812
80       A 2026-04-28 10:51:00  114.879997  114.970001  114.870003  114.904999    2113.0  2026-04-28  116.23      115.61   -0.63   XLV  0.5579  0.812
81       A 2026-04-28 10:52:00  114.989998  115.059998  114.989998  115.059998     500.0  2026-04-28  116.23      115.61   -0.54   XLV  0.5579  0.812
82       A 2026-04-28 10:53:00  114.980003  115.089996  114.980003  115.040001    1701.0  2026-04-28  116.23      115.61   -0.54   XLV  0.5579  0.812
83       A 2026-04-28 10:54:00  115.144997  115.190002  115.095001  115.095001     800.0  2026-04-28  116.23      115.61   -0.40   XLV  0.5579  0.812
84       A 2026-04-28 10:55:00  115.099998  115.099998  114.980003  115.040001    2981.0  2026-04-28  116.23      115.61   -0.44   XLV  0.5579  0.812
85       A 2026-04-28 10:56:00  115.080002  115.139999  115.050003  115.139999    1362.0  2026-04-28  116.23      115.61   -0.46   XLV  0.5579  0.812
86       A 2026-04-28 10:57:00  114.995003  115.089996  114.989998  114.989998     400.0  2026-04-28  116.23      115.61   -0.53   XLV  0.5579  0.812
87       A 2026-04-28 10:58:00  115.089996  115.089996  114.889999  114.889999    2652.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.812
88       A 2026-04-28 10:59:00  114.834999  114.949997  114.834999  114.949997    1713.0  2026-04-28  116.23      115.61   -0.67   XLV  0.5579  0.812
89       A 2026-04-28 11:00:00  114.959999  114.995003  114.910004  114.995003    2488.0  2026-04-28  116.23      115.61   -0.56   XLV  0.5579  0.812
90       A 2026-04-28 11:01:00  115.050003  115.089996  114.970001  115.055000    3614.0  2026-04-28  116.23      115.61   -0.48   XLV  0.5579  0.812
91       A 2026-04-28 11:02:00  115.019997  115.190002  115.000000  115.000000    6092.0  2026-04-28  116.23      115.61   -0.51   XLV  0.5579  0.812
92       A 2026-04-28 11:03:00  115.000000  115.004997  114.864998  114.867500   18016.0  2026-04-28  116.23      115.61   -0.53   XLV  0.5579  0.812
93       A 2026-04-28 11:04:00  114.864998  115.019997  114.855003  115.019997    7097.0  2026-04-28  116.23      115.61   -0.64   XLV  0.5579  0.812
94       A 2026-04-28 11:05:00  114.970001  115.000000  114.970001  114.980003     813.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.812
95       A 2026-04-28 11:06:00  115.050003  115.050003  114.944000  114.989998    1535.0  2026-04-28  116.23      115.61   -0.48   XLV  0.5579  0.812
96       A 2026-04-28 11:07:00  114.974998  114.974998  114.970001  114.970001     429.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.812
97       A 2026-04-28 11:08:00  114.970001  115.059998  114.970001  115.000000     728.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.812
98       A 2026-04-28 11:09:00  115.010002  115.139999  115.010002  115.139999    1148.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.812
99       A 2026-04-28 11:10:00  115.169998  115.169998  115.074997  115.129997     569.0  2026-04-28  116.23      115.61   -0.38   XLV  0.5579  0.812
100      A 2026-04-28 11:11:00  115.084999  115.160004  115.084999  115.120003     684.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.812
101      A 2026-04-28 11:12:00  115.084999  115.084999  114.905899  114.919998    3529.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.812
102      A 2026-04-28 11:13:00  114.949997  115.019997  114.949997  115.019997     800.0  2026-04-28  116.23      115.61   -0.57   XLV  0.5579  0.812
103      A 2026-04-28 11:14:00  115.004997  115.004997  114.989998  114.989998     400.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.812
104      A 2026-04-28 11:15:00  115.010002  115.010002  115.010002  115.010002    1518.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.812
105      A 2026-04-28 11:16:00  115.010002  115.010002  115.010002  115.010002     700.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.812
106      A 2026-04-28 11:17:00  115.010002  115.010002  114.989998  114.989998     400.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.812
107      A 2026-04-28 11:18:00  115.010002  115.010002  114.910004  114.910004     300.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.812
108      A 2026-04-28 11:19:00  114.910004  114.910004  114.904999  114.904999     600.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.812
109      A 2026-04-28 11:20:00  114.904999  115.010002  114.904999  114.930000     868.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.812
110      A 2026-04-28 11:21:00  114.900002  115.019997  114.900002  115.019997     500.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.812
111      A 2026-04-28 11:22:00  114.940002  115.029999  114.900002  114.940002    4867.0  2026-04-28  116.23      115.61   -0.58   XLV  0.5579  0.812
112      A 2026-04-28 11:23:00  114.940002  114.940002  114.889999  114.919998    3073.0  2026-04-28  116.23      115.61   -0.58   XLV  0.5579  0.812
113      A 2026-04-28 11:24:00  114.919998  114.940002  114.870003  114.870003    2421.0  2026-04-28  116.23      115.61   -0.60   XLV  0.5579  0.812
114      A 2026-04-28 11:25:00  114.900002  114.980003  114.860001  114.900002   34497.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.812
115      A 2026-04-28 11:26:00  114.864998  114.900002  114.864998  114.900002     428.0  2026-04-28  116.23      115.61   -0.64   XLV  0.5579  0.812
116      A 2026-04-28 11:27:00  114.860001  114.894997  114.849998  114.894997    1174.0  2026-04-28  116.23      115.61   -0.65   XLV  0.5579  0.812
117      A 2026-04-28 11:28:00  114.894997  114.940002  114.849998  114.940002    1592.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.812
118      A 2026-04-28 11:29:00  114.894997  114.894997  114.830002  114.839996    3036.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.812
119      A 2026-04-28 11:30:00  114.860001  114.860001  114.800003  114.800003    1699.0  2026-04-28  116.23      115.61   -0.65   XLV  0.5579  0.812
120      A 2026-04-28 11:31:00  114.834999  114.870003  114.809998  114.809998    2027.0  2026-04-28  116.23      115.61   -0.67   XLV  0.5579  0.812
121      A 2026-04-28 11:32:00  114.834999  114.870003  114.834999  114.834999     300.0  2026-04-28  116.23      115.61   -0.67   XLV  0.5579  0.812
122      A 2026-04-28 11:33:00  114.870003  115.010002  114.870003  114.980003    3447.0  2026-04-28  116.23      115.61   -0.64   XLV  0.5579  0.812
123      A 2026-04-28 11:34:00  115.019997  115.019997  114.830002  114.830002    2900.0  2026-04-28  116.23      115.61   -0.51   XLV  0.5579  0.812
124      A 2026-04-28 11:35:00  114.824997  114.824997  114.824997  114.824997     413.0  2026-04-28  116.23      115.61   -0.68   XLV  0.5579  0.812
125      A 2026-04-28 11:36:00  114.824997  114.824997  114.794998  114.794998    2399.0  2026-04-28  116.23      115.61   -0.68   XLV  0.5579  0.812
126      A 2026-04-28 11:37:00  114.870003  114.930000  114.860001  114.875000    1905.0  2026-04-28  116.23      115.61   -0.64   XLV  0.5579  0.812
127      A 2026-04-28 11:38:00  114.839996  114.879997  114.839996  114.845001     704.0  2026-04-28  116.23      115.61   -0.67   XLV  0.5579  0.812
128      A 2026-04-28 11:39:00  114.805000  114.805000  114.805000  114.805000     637.0  2026-04-28  116.23      115.61   -0.70   XLV  0.5579  0.812
129      A 2026-04-28 11:40:00  114.849998  114.849998  114.839996  114.839996    1100.0  2026-04-28  116.23      115.61   -0.66   XLV  0.5579  0.812
130      A 2026-04-28 11:41:00  114.870003  114.870003  114.802498  114.805000     400.0  2026-04-28  116.23      115.61   -0.64   XLV  0.5579  0.812
131      A 2026-04-28 11:42:00  114.805000  114.889999  114.805000  114.889999    1005.0  2026-04-28  116.23      115.61   -0.70   XLV  0.5579  0.812

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2026-04-28 00:00:00,116.320000,116.320000,116.320000,116.320000,10.0,2026-04-28,116.23,115.61,0.61,XLV,0.5579,0.812
1,A,2026-04-28 09:29:00,116.430000,116.440002,116.430000,116.440002,200.0,2026-04-28,116.23,115.61,0.71,XLV,0.5579,0.812
2,A,2026-04-28 09:30:00,116.230003,116.635002,115.970001,116.279999,18280.0,2026-04-28,116.23,115.61,0.54,XLV,0.5579,0.812
3,A,2026-04-28 09:31:00,116.459999,116.459999,116.230003,116.230003,200.0,2026-04-28,116.23,115.61,0.74,XLV,0.5579,0.812
4,A,2026-04-28 09:32:00,116.275002,116.540001,116.250000,116.540001,1000.0,2026-04-28,116.23,115.61,0.58,XLV,0.5579,0.812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2026-04-29 13:40:00,111.205002,111.205002,111.129997,111.129997,411.0,2026-04-29,114.19,114.86,-3.18,XLV,0.5579,0.812
616,A,2026-04-29 13:41:00,111.129997,111.209999,110.974998,110.974998,5733.0,2026-04-29,114.19,114.86,-3.25,XLV,0.5579,0.812
617,A,2026-04-29 13:42:00,110.900002,110.989998,110.900002,110.910004,1443.0,2026-04-29,114.19,114.86,-3.45,XLV,0.5579,0.812
618,A,2026-04-29 13:43:00,110.910004,110.910004,110.910004,110.910004,424.0,2026-04-29,114.19,114.86,-3.44,XLV,0.5579,0.812
619,A,2026-04-29 13:44:00,110.910004,110.910004,110.910004,110.910004,600.0,2026-04-29,114.19,114.86,-3.44,XLV,0.5579,0.812

In [32]:
# список тикерів
tickers = [
    'SPY', 'IWM', 'GDX', 'XLF', 'QQQ', 'XLE', 'KRE', 'IBIT', 'KWEB', 'XLP', 'SOXX',
    'IGV', 'SMH', 'XLK', 'ITA', 'XLI', 'XTN', 'OIH', 'XLU', 'ICLN', 'XLB', 'SLX',
    'IBB', 'XBI', 'IHI', 'XLV', 'IHF', 'XRT', 'XLY', 'XHB', 'VNQ',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [33]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=12,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 0 тікерів (пропущено 0 по старому маніфесту) | 2026-04-28 00:00:00 → 2026-06-28 23:59:59 | interval=1 | next batch #0087 | run=e3b48003

   workers: tickers=12, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 31

   📉 пропущені дні (в межах window): 2026-04-28 → 2026-06-28 (62 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 1,419.2 MB

   🔚 фінал · 🧠 RAM: 1,419.3 MB

🏁 Готово. Нових рядків: 0 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:00

In [34]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

  [69/86] intraday_0069.csv.gz chunk 5  in=2,122,725  out=2,122,725  elapsed=21.5s

✅ DONE  in=2,400,810 → out=2,400,810  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 23.6s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [35]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [36]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [37]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=2,400,810  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 11.3s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [38]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [39]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=2,400,810  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 1.9s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [40]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [41]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=27.6s

[batch   10] rows=20,000,000  elapsed=56.2s

[batch   15] rows=30,000,000  elapsed=83.6s

[batch   20] rows=40,000,000  elapsed=113.3s

[batch   25] rows=50,000,000  elapsed=141.8s

[batch   30] rows=60,000,000  elapsed=170.1s

[batch   35] rows=70,000,000  elapsed=198.1s

✅ DONE rows=77,717,692 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 219.5s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [42]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }
        reports_df = DatumApi.data_request("/reports", params)
        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)
    except Exception as e:
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20, max_workers=16):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []

    def fetch(t):
        return get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Reports"):
            rep = f.result()
            if rep is not None and not rep.empty:
                parts.append(rep)

    if not parts:
        return pd.DataFrame(columns=["ticker", "report_date"]), {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map, max_workers=16):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()

    def fetch(t):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }
        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                return None

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                return None

            out = df_gap.copy()
            out["ticker"] = out["ticker"].astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            return out if not out.empty else None
        except Exception as e:
            print(f"Gap fetch failed for {t}: {e}")
            return None

    all_results = []
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Gaps (ex-reports)"):
            result = f.result()
            if result is not None:
                all_results.append(result)

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=None,
):
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col]).copy()

    def compute_sigma(s):
        x = s.shift(1)

        def f(arr):
            arr = arr[~np.isnan(arr)]
            if len(arr) < min_periods:
                return np.nan
            cap = np.quantile(np.abs(arr), cap_q)
            arr_capped = np.clip(arr, -cap, cap)
            return np.std(arr_capped, ddof=1)

        return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

    out[f"{value_col}_sigma_{window}d_cap"] = (
        out.groupby(group_col)[value_col].transform(compute_sigma)
    )
    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    max_workers=16,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
    max_workers=16,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

# 3) Rolling sigma
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

print("Tickers with sigma:", len(std_by_ticker))
std_by_ticker.head()

Reports:   0%|          | 0/7343 [00:00<?, ?it/s]

Reports:   0%|          | 1/7343 [00:00<42:41,  2.87it/s]

Reports:   0%|          | 12/7343 [00:00<03:40, 33.21it/s]

Reports:   0%|          | 19/7343 [00:00<03:03, 39.81it/s]

Reports:   0%|          | 25/7343 [00:00<02:49, 43.07it/s]

Reports:   0%|          | 33/7343 [00:00<02:30, 48.42it/s]

Reports:   1%|          | 41/7343 [00:00<02:09, 56.49it/s]

Reports:   1%|          | 48/7343 [00:01<02:19, 52.16it/s]

Reports:   1%|          | 55/7343 [00:01<02:20, 52.04it/s]

Reports:   1%|          | 61/7343 [00:01<02:17, 53.03it/s]

Reports:   1%|          | 69/7343 [00:01<02:05, 58.07it/s]

Reports:   1%|          | 76/7343 [00:01<02:13, 54.50it/s]

Reports:   1%|          | 84/7343 [00:01<02:00, 60.40it/s]

Reports:   1%|          | 91/7343 [00:01<01:56, 62.19it/s]

Reports:   1%|▏         | 98/7343 [00:01<01:55, 62.60it/s]

Reports:   1%|▏         | 105/7343 [00:02<02:04, 58.27it/s]

Reports:   2%|▏         | 115/7343 [00:02<01:45, 68.53it/s]

Reports:   2%|▏         | 123/7343 [00:02<01:54, 63.00it/s]

Reports:   2%|▏         | 130/7343 [00:02<01:55, 62.69it/s]

Reports:   2%|▏         | 141/7343 [00:02<01:36, 74.81it/s]

Reports:   2%|▏         | 149/7343 [00:02<01:52, 63.73it/s]

Reports:   2%|▏         | 159/7343 [00:02<01:48, 66.32it/s]

Reports:   2%|▏         | 166/7343 [00:02<01:52, 63.59it/s]

Reports:   2%|▏         | 173/7343 [00:03<01:56, 61.71it/s]

Reports:   2%|▏         | 180/7343 [00:03<02:00, 59.62it/s]

Reports:   3%|▎         | 190/7343 [00:03<01:44, 68.28it/s]

Reports:   3%|▎         | 198/7343 [00:03<01:54, 62.28it/s]

Reports:   3%|▎         | 209/7343 [00:03<01:48, 65.84it/s]

Reports:   3%|▎         | 217/7343 [00:03<01:45, 67.53it/s]

Reports:   3%|▎         | 224/7343 [00:03<01:49, 64.94it/s]

Reports:   3%|▎         | 232/7343 [00:03<01:46, 66.49it/s]

Reports:   3%|▎         | 239/7343 [00:04<01:52, 63.27it/s]

Reports:   3%|▎         | 250/7343 [00:04<01:34, 75.13it/s]

Reports:   4%|▎         | 258/7343 [00:04<02:05, 56.30it/s]

Reports:   4%|▎         | 269/7343 [00:04<01:43, 68.05it/s]

Reports:   4%|▍         | 277/7343 [00:04<01:58, 59.45it/s]

Reports:   4%|▍         | 285/7343 [00:04<02:01, 58.14it/s]

Reports:   4%|▍         | 292/7343 [00:05<02:07, 55.21it/s]

Reports:   4%|▍         | 302/7343 [00:05<01:50, 63.95it/s]

Reports:   4%|▍         | 309/7343 [00:05<01:57, 59.99it/s]

Reports:   4%|▍         | 316/7343 [00:05<02:08, 54.70it/s]

Reports:   4%|▍         | 324/7343 [00:05<01:59, 58.59it/s]

Reports:   5%|▍         | 332/7343 [00:05<01:51, 62.76it/s]

Reports:   5%|▍         | 339/7343 [00:05<02:00, 58.10it/s]

Reports:   5%|▍         | 350/7343 [00:05<01:51, 62.91it/s]

Reports:   5%|▍         | 357/7343 [00:06<02:05, 55.46it/s]

Reports:   5%|▍         | 366/7343 [00:06<01:53, 61.63it/s]

Reports:   5%|▌         | 373/7343 [00:06<01:50, 63.25it/s]

Reports:   5%|▌         | 380/7343 [00:06<01:54, 60.69it/s]

Reports:   5%|▌         | 389/7343 [00:06<01:53, 61.07it/s]

Reports:   5%|▌         | 396/7343 [00:06<01:57, 59.25it/s]

Reports:   6%|▌         | 404/7343 [00:06<01:51, 61.98it/s]

Reports:   6%|▌         | 413/7343 [00:06<01:40, 68.99it/s]

Reports:   6%|▌         | 421/7343 [00:07<01:41, 68.24it/s]

Reports:   6%|▌         | 428/7343 [00:07<01:59, 58.06it/s]

Reports:   6%|▌         | 435/7343 [00:07<02:00, 57.16it/s]

Reports:   6%|▌         | 441/7343 [00:07<01:59, 57.60it/s]

Reports:   6%|▌         | 448/7343 [00:07<01:54, 60.13it/s]

Reports:   6%|▌         | 457/7343 [00:07<01:47, 64.19it/s]

Reports:   6%|▋         | 464/7343 [00:07<02:00, 56.96it/s]

Reports:   6%|▋         | 473/7343 [00:07<01:48, 63.46it/s]

Reports:   7%|▋         | 480/7343 [00:08<01:56, 59.07it/s]

Reports:   7%|▋         | 487/7343 [00:08<02:06, 54.32it/s]

Reports:   7%|▋         | 496/7343 [00:08<01:54, 59.97it/s]

Reports:   7%|▋         | 503/7343 [00:08<01:57, 58.22it/s]

Reports:   7%|▋         | 512/7343 [00:08<01:45, 65.03it/s]

Reports:   7%|▋         | 519/7343 [00:08<01:56, 58.81it/s]

Reports:   7%|▋         | 527/7343 [00:08<01:56, 58.39it/s]

Reports:   7%|▋         | 533/7343 [00:09<02:05, 54.35it/s]

Reports:   7%|▋         | 539/7343 [00:09<02:34, 44.14it/s]

Reports:   7%|▋         | 548/7343 [00:09<02:06, 53.85it/s]

Reports:   8%|▊         | 554/7343 [00:09<02:03, 54.77it/s]

Reports:   8%|▊         | 563/7343 [00:09<02:08, 52.64it/s]

Reports:   8%|▊         | 569/7343 [00:09<02:06, 53.43it/s]

Reports:   8%|▊         | 575/7343 [00:09<02:17, 49.37it/s]

Reports:   8%|▊         | 581/7343 [00:09<02:16, 49.67it/s]

Reports:   8%|▊         | 590/7343 [00:10<02:02, 55.17it/s]

Reports:   8%|▊         | 596/7343 [00:10<02:06, 53.21it/s]

Reports:   8%|▊         | 602/7343 [00:10<02:11, 51.17it/s]

Reports:   8%|▊         | 608/7343 [00:10<02:06, 53.17it/s]

Reports:   8%|▊         | 616/7343 [00:10<02:12, 50.74it/s]

Reports:   9%|▊         | 626/7343 [00:10<01:59, 56.27it/s]

Reports:   9%|▊         | 633/7343 [00:10<02:07, 52.71it/s]

Reports:   9%|▊         | 639/7343 [00:11<02:11, 51.15it/s]

Reports:   9%|▉         | 648/7343 [00:11<02:01, 55.15it/s]

Reports:   9%|▉         | 654/7343 [00:11<02:17, 48.78it/s]

Reports:   9%|▉         | 662/7343 [00:11<02:14, 49.62it/s]

Reports:   9%|▉         | 668/7343 [00:11<02:26, 45.60it/s]

Reports:   9%|▉         | 675/7343 [00:11<02:14, 49.56it/s]

Reports:   9%|▉         | 683/7343 [00:11<01:57, 56.49it/s]

Reports:   9%|▉         | 689/7343 [00:12<02:03, 53.78it/s]

Reports:   9%|▉         | 695/7343 [00:12<02:08, 51.56it/s]

Reports:  10%|▉         | 701/7343 [00:12<02:04, 53.51it/s]

Reports:  10%|▉         | 710/7343 [00:12<01:53, 58.67it/s]

Reports:  10%|▉         | 716/7343 [00:12<02:12, 49.90it/s]

Reports:  10%|▉         | 726/7343 [00:12<01:59, 55.30it/s]

Reports:  10%|▉         | 732/7343 [00:12<02:07, 51.87it/s]

Reports:  10%|█         | 742/7343 [00:12<01:49, 60.53it/s]

Reports:  10%|█         | 749/7343 [00:13<01:54, 57.37it/s]

Reports:  10%|█         | 757/7343 [00:13<01:57, 55.84it/s]

Reports:  10%|█         | 763/7343 [00:13<01:57, 55.87it/s]

Reports:  10%|█         | 769/7343 [00:13<02:04, 52.66it/s]

Reports:  11%|█         | 777/7343 [00:13<01:54, 57.46it/s]

Reports:  11%|█         | 783/7343 [00:13<02:06, 51.74it/s]

Reports:  11%|█         | 789/7343 [00:13<02:11, 49.68it/s]

Reports:  11%|█         | 797/7343 [00:14<02:01, 53.84it/s]

Reports:  11%|█         | 805/7343 [00:14<01:53, 57.70it/s]

Reports:  11%|█         | 812/7343 [00:14<01:48, 60.28it/s]

Reports:  11%|█         | 820/7343 [00:14<01:41, 64.11it/s]

Reports:  11%|█▏        | 827/7343 [00:14<01:43, 62.73it/s]

Reports:  11%|█▏        | 834/7343 [00:14<01:49, 59.61it/s]

Reports:  11%|█▏        | 843/7343 [00:14<01:40, 64.79it/s]

Reports:  12%|█▏        | 850/7343 [00:14<01:39, 65.33it/s]

Reports:  12%|█▏        | 857/7343 [00:14<01:46, 60.69it/s]

Reports:  12%|█▏        | 866/7343 [00:15<01:37, 66.75it/s]

Reports:  12%|█▏        | 873/7343 [00:15<01:45, 61.31it/s]

Reports:  12%|█▏        | 880/7343 [00:15<01:48, 59.52it/s]

Reports:  12%|█▏        | 887/7343 [00:15<02:10, 49.55it/s]

Reports:  12%|█▏        | 896/7343 [00:15<01:56, 55.43it/s]

Reports:  12%|█▏        | 902/7343 [00:15<01:54, 56.26it/s]

Reports:  12%|█▏        | 910/7343 [00:15<01:47, 59.64it/s]

Reports:  12%|█▏        | 917/7343 [00:16<02:02, 52.36it/s]

Reports:  13%|█▎        | 926/7343 [00:16<01:47, 59.76it/s]

Reports:  13%|█▎        | 933/7343 [00:16<01:49, 58.73it/s]

Reports:  13%|█▎        | 940/7343 [00:16<01:53, 56.28it/s]

Reports:  13%|█▎        | 946/7343 [00:16<02:00, 53.30it/s]

Reports:  13%|█▎        | 957/7343 [00:16<01:48, 58.96it/s]

Reports:  13%|█▎        | 965/7343 [00:16<01:41, 62.91it/s]

Reports:  13%|█▎        | 972/7343 [00:16<01:40, 63.24it/s]

Reports:  13%|█▎        | 979/7343 [00:17<01:41, 62.61it/s]

Reports:  13%|█▎        | 986/7343 [00:17<01:51, 57.17it/s]

Reports:  14%|█▎        | 995/7343 [00:17<01:47, 58.81it/s]

Reports:  14%|█▎        | 1001/7343 [00:17<01:52, 56.15it/s]

Reports:  14%|█▎        | 1008/7343 [00:17<01:55, 54.95it/s]

Reports:  14%|█▍        | 1014/7343 [00:17<01:52, 56.05it/s]

Reports:  14%|█▍        | 1021/7343 [00:17<01:51, 56.89it/s]

Reports:  14%|█▍        | 1027/7343 [00:17<01:56, 54.39it/s]

Reports:  14%|█▍        | 1034/7343 [00:18<01:49, 57.63it/s]

Reports:  14%|█▍        | 1040/7343 [00:18<01:53, 55.54it/s]

Reports:  14%|█▍        | 1047/7343 [00:18<01:58, 52.96it/s]

Reports:  14%|█▍        | 1053/7343 [00:18<01:56, 54.10it/s]

Reports:  14%|█▍        | 1061/7343 [00:18<01:47, 58.43it/s]

Reports:  15%|█▍        | 1069/7343 [00:18<01:47, 58.10it/s]

Reports:  15%|█▍        | 1075/7343 [00:18<01:54, 54.72it/s]

Reports:  15%|█▍        | 1081/7343 [00:18<01:54, 54.64it/s]

Reports:  15%|█▍        | 1089/7343 [00:19<01:44, 59.99it/s]

Reports:  15%|█▍        | 1096/7343 [00:19<01:42, 61.07it/s]

Reports:  15%|█▌        | 1103/7343 [00:19<01:59, 52.17it/s]

Reports:  15%|█▌        | 1113/7343 [00:19<01:38, 63.53it/s]

Reports:  15%|█▌        | 1120/7343 [00:19<01:43, 59.97it/s]

Reports:  15%|█▌        | 1127/7343 [00:19<01:51, 55.61it/s]

Reports:  15%|█▌        | 1136/7343 [00:19<01:37, 63.89it/s]

Reports:  16%|█▌        | 1143/7343 [00:19<01:38, 62.72it/s]

Reports:  16%|█▌        | 1150/7343 [00:20<01:40, 61.86it/s]

Reports:  16%|█▌        | 1157/7343 [00:20<01:44, 59.07it/s]

Reports:  16%|█▌        | 1164/7343 [00:20<01:53, 54.29it/s]

Reports:  16%|█▌        | 1173/7343 [00:20<01:40, 61.60it/s]

Reports:  16%|█▌        | 1180/7343 [00:20<01:39, 61.65it/s]

Reports:  16%|█▌        | 1187/7343 [00:20<01:47, 57.00it/s]

Reports:  16%|█▋        | 1197/7343 [00:20<01:38, 62.23it/s]

Reports:  16%|█▋        | 1204/7343 [00:20<01:45, 58.44it/s]

Reports:  16%|█▋        | 1210/7343 [00:21<01:48, 56.73it/s]

Reports:  17%|█▋        | 1216/7343 [00:21<01:57, 52.36it/s]

Reports:  17%|█▋        | 1224/7343 [00:21<01:44, 58.32it/s]

Reports:  17%|█▋        | 1230/7343 [00:21<01:48, 56.57it/s]

Reports:  17%|█▋        | 1237/7343 [00:21<01:50, 55.04it/s]

Reports:  17%|█▋        | 1246/7343 [00:21<01:41, 60.11it/s]

Reports:  17%|█▋        | 1254/7343 [00:21<01:37, 62.22it/s]

Reports:  17%|█▋        | 1261/7343 [00:21<01:41, 59.92it/s]

Reports:  17%|█▋        | 1268/7343 [00:22<01:42, 59.32it/s]

Reports:  17%|█▋        | 1274/7343 [00:22<01:53, 53.65it/s]

Reports:  17%|█▋        | 1282/7343 [00:22<01:43, 58.38it/s]

Reports:  18%|█▊        | 1289/7343 [00:22<01:43, 58.48it/s]

Reports:  18%|█▊        | 1295/7343 [00:22<01:47, 56.03it/s]

Reports:  18%|█▊        | 1305/7343 [00:22<01:32, 65.58it/s]

Reports:  18%|█▊        | 1312/7343 [00:22<01:42, 58.86it/s]

Reports:  18%|█▊        | 1319/7343 [00:22<01:38, 61.24it/s]

Reports:  18%|█▊        | 1328/7343 [00:23<01:33, 64.03it/s]

Reports:  18%|█▊        | 1335/7343 [00:23<01:34, 63.48it/s]

Reports:  18%|█▊        | 1342/7343 [00:23<01:36, 62.25it/s]

Reports:  18%|█▊        | 1349/7343 [00:23<01:39, 60.40it/s]

Reports:  18%|█▊        | 1357/7343 [00:23<01:39, 60.09it/s]

Reports:  19%|█▊        | 1367/7343 [00:23<01:27, 68.65it/s]

Reports:  19%|█▊        | 1374/7343 [00:23<01:40, 59.14it/s]

Reports:  19%|█▉        | 1381/7343 [00:23<01:38, 60.31it/s]

Reports:  19%|█▉        | 1388/7343 [00:24<01:48, 54.98it/s]

Reports:  19%|█▉        | 1394/7343 [00:24<01:48, 55.00it/s]

Reports:  19%|█▉        | 1401/7343 [00:24<01:46, 56.03it/s]

Reports:  19%|█▉        | 1408/7343 [00:24<01:47, 55.30it/s]

Reports:  19%|█▉        | 1414/7343 [00:24<01:53, 52.20it/s]

Reports:  19%|█▉        | 1425/7343 [00:24<01:44, 56.51it/s]

Reports:  19%|█▉        | 1431/7343 [00:24<01:47, 55.09it/s]

Reports:  20%|█▉        | 1439/7343 [00:24<01:40, 58.66it/s]

Reports:  20%|█▉        | 1445/7343 [00:25<01:45, 56.11it/s]

Reports:  20%|█▉        | 1452/7343 [00:25<01:51, 53.07it/s]

Reports:  20%|█▉        | 1459/7343 [00:25<01:46, 55.48it/s]

Reports:  20%|█▉        | 1467/7343 [00:25<01:44, 56.14it/s]

Reports:  20%|██        | 1473/7343 [00:25<01:44, 56.42it/s]

Reports:  20%|██        | 1479/7343 [00:25<01:44, 55.96it/s]

Reports:  20%|██        | 1487/7343 [00:25<01:40, 58.48it/s]

Reports:  20%|██        | 1494/7343 [00:25<01:43, 56.68it/s]

Reports:  20%|██        | 1502/7343 [00:26<01:35, 61.12it/s]

Reports:  21%|██        | 1509/7343 [00:26<01:43, 56.50it/s]

Reports:  21%|██        | 1516/7343 [00:26<01:52, 51.69it/s]

Reports:  21%|██        | 1524/7343 [00:26<01:42, 56.77it/s]

Reports:  21%|██        | 1531/7343 [00:26<01:44, 55.84it/s]

Reports:  21%|██        | 1537/7343 [00:26<01:44, 55.72it/s]

Reports:  21%|██        | 1546/7343 [00:26<01:30, 63.73it/s]

Reports:  21%|██        | 1553/7343 [00:26<01:39, 58.23it/s]

Reports:  21%|██        | 1560/7343 [00:27<01:35, 60.38it/s]

Reports:  21%|██▏       | 1567/7343 [00:27<01:39, 58.30it/s]

Reports:  21%|██▏       | 1575/7343 [00:27<01:31, 62.79it/s]

Reports:  22%|██▏       | 1583/7343 [00:27<01:27, 65.76it/s]

Reports:  22%|██▏       | 1590/7343 [00:27<01:26, 66.22it/s]

Reports:  22%|██▏       | 1597/7343 [00:27<01:50, 52.15it/s]

Reports:  22%|██▏       | 1608/7343 [00:27<01:29, 63.87it/s]

Reports:  22%|██▏       | 1615/7343 [00:27<01:32, 61.71it/s]

Reports:  22%|██▏       | 1624/7343 [00:28<01:28, 64.69it/s]

Reports:  22%|██▏       | 1634/7343 [00:28<01:24, 67.47it/s]

Reports:  22%|██▏       | 1641/7343 [00:28<01:36, 59.00it/s]

Reports:  22%|██▏       | 1651/7343 [00:28<01:41, 56.18it/s]

Reports:  23%|██▎       | 1662/7343 [00:28<01:30, 62.55it/s]

Reports:  23%|██▎       | 1669/7343 [00:28<01:31, 62.26it/s]

Reports:  23%|██▎       | 1676/7343 [00:28<01:30, 62.29it/s]

Reports:  23%|██▎       | 1686/7343 [00:29<01:33, 60.27it/s]

Reports:  23%|██▎       | 1693/7343 [00:29<01:33, 60.54it/s]

Reports:  23%|██▎       | 1700/7343 [00:29<01:40, 56.20it/s]

Reports:  23%|██▎       | 1708/7343 [00:29<01:31, 61.56it/s]

Reports:  23%|██▎       | 1715/7343 [00:29<01:30, 61.96it/s]

Reports:  23%|██▎       | 1722/7343 [00:29<01:32, 60.58it/s]

Reports:  24%|██▎       | 1730/7343 [00:29<01:25, 65.49it/s]

Reports:  24%|██▎       | 1737/7343 [00:30<01:43, 53.97it/s]

Reports:  24%|██▍       | 1747/7343 [00:30<01:27, 63.90it/s]

Reports:  24%|██▍       | 1754/7343 [00:30<01:29, 62.58it/s]

Reports:  24%|██▍       | 1761/7343 [00:30<01:31, 60.96it/s]

Reports:  24%|██▍       | 1768/7343 [00:30<01:31, 60.98it/s]

Reports:  24%|██▍       | 1776/7343 [00:30<01:29, 61.91it/s]

Reports:  24%|██▍       | 1783/7343 [00:30<01:37, 56.82it/s]

Reports:  24%|██▍       | 1792/7343 [00:30<01:28, 62.62it/s]

Reports:  24%|██▍       | 1799/7343 [00:31<01:33, 59.28it/s]

Reports:  25%|██▍       | 1806/7343 [00:31<01:38, 55.96it/s]

Reports:  25%|██▍       | 1816/7343 [00:31<01:34, 58.73it/s]

Reports:  25%|██▍       | 1823/7343 [00:31<01:31, 60.40it/s]

Reports:  25%|██▍       | 1830/7343 [00:31<01:34, 58.48it/s]

Reports:  25%|██▌       | 1839/7343 [00:31<01:30, 60.55it/s]

Reports:  25%|██▌       | 1846/7343 [00:31<01:28, 62.00it/s]

Reports:  25%|██▌       | 1853/7343 [00:31<01:28, 61.89it/s]

Reports:  25%|██▌       | 1863/7343 [00:32<01:18, 69.50it/s]

Reports:  25%|██▌       | 1871/7343 [00:32<01:34, 58.20it/s]

Reports:  26%|██▌       | 1883/7343 [00:32<01:16, 71.43it/s]

Reports:  26%|██▌       | 1891/7343 [00:32<01:31, 59.41it/s]

Reports:  26%|██▌       | 1901/7343 [00:32<01:22, 65.82it/s]

Reports:  26%|██▌       | 1909/7343 [00:32<01:30, 59.77it/s]

Reports:  26%|██▌       | 1917/7343 [00:32<01:24, 64.28it/s]

Reports:  26%|██▌       | 1924/7343 [00:33<01:24, 64.14it/s]

Reports:  26%|██▋       | 1931/7343 [00:33<01:25, 62.97it/s]

Reports:  26%|██▋       | 1938/7343 [00:33<01:25, 63.37it/s]

Reports:  26%|██▋       | 1945/7343 [00:33<01:22, 65.10it/s]

Reports:  27%|██▋       | 1952/7343 [00:33<01:25, 63.07it/s]

Reports:  27%|██▋       | 1960/7343 [00:33<01:21, 66.31it/s]

Reports:  27%|██▋       | 1967/7343 [00:33<01:24, 63.72it/s]

Reports:  27%|██▋       | 1975/7343 [00:33<01:22, 64.87it/s]

Reports:  27%|██▋       | 1982/7343 [00:33<01:25, 62.38it/s]

Reports:  27%|██▋       | 1989/7343 [00:34<01:23, 64.36it/s]

Reports:  27%|██▋       | 1996/7343 [00:34<01:33, 57.04it/s]

Reports:  27%|██▋       | 2004/7343 [00:34<01:26, 62.02it/s]

Reports:  27%|██▋       | 2011/7343 [00:34<01:23, 63.57it/s]

Reports:  27%|██▋       | 2018/7343 [00:34<01:22, 64.32it/s]

Reports:  28%|██▊       | 2025/7343 [00:34<01:22, 64.14it/s]

Reports:  28%|██▊       | 2032/7343 [00:34<01:28, 59.90it/s]

Reports:  28%|██▊       | 2039/7343 [00:34<01:30, 58.30it/s]

Reports:  28%|██▊       | 2046/7343 [00:35<01:35, 55.64it/s]

Reports:  28%|██▊       | 2054/7343 [00:35<01:26, 61.15it/s]

Reports:  28%|██▊       | 2061/7343 [00:35<01:24, 62.78it/s]

Reports:  28%|██▊       | 2068/7343 [00:35<01:22, 63.80it/s]

Reports:  28%|██▊       | 2075/7343 [00:35<01:23, 63.46it/s]

Reports:  28%|██▊       | 2082/7343 [00:35<01:22, 63.57it/s]

Reports:  28%|██▊       | 2089/7343 [00:35<01:22, 63.51it/s]

Reports:  29%|██▊       | 2098/7343 [00:35<01:15, 69.09it/s]

Reports:  29%|██▊       | 2105/7343 [00:35<01:25, 61.59it/s]

Reports:  29%|██▉       | 2114/7343 [00:36<01:15, 68.82it/s]

Reports:  29%|██▉       | 2122/7343 [00:36<01:26, 60.19it/s]

Reports:  29%|██▉       | 2132/7343 [00:36<01:21, 63.60it/s]

Reports:  29%|██▉       | 2139/7343 [00:36<01:24, 61.62it/s]

Reports:  29%|██▉       | 2148/7343 [00:36<01:23, 62.55it/s]

Reports:  29%|██▉       | 2155/7343 [00:36<01:36, 53.73it/s]

Reports:  29%|██▉       | 2163/7343 [00:36<01:32, 56.00it/s]

Reports:  30%|██▉       | 2169/7343 [00:37<01:34, 54.70it/s]

Reports:  30%|██▉       | 2177/7343 [00:37<01:34, 54.94it/s]

Reports:  30%|██▉       | 2184/7343 [00:37<01:30, 57.22it/s]

Reports:  30%|██▉       | 2191/7343 [00:37<01:31, 56.51it/s]

Reports:  30%|██▉       | 2200/7343 [00:37<01:23, 61.36it/s]

Reports:  30%|███       | 2208/7343 [00:37<01:20, 63.83it/s]

Reports:  30%|███       | 2215/7343 [00:37<01:29, 57.47it/s]

Reports:  30%|███       | 2222/7343 [00:37<01:25, 60.01it/s]

Reports:  30%|███       | 2230/7343 [00:37<01:18, 64.86it/s]

Reports:  30%|███       | 2237/7343 [00:38<01:23, 61.32it/s]

Reports:  31%|███       | 2245/7343 [00:38<01:17, 65.67it/s]

Reports:  31%|███       | 2252/7343 [00:38<01:20, 62.94it/s]

Reports:  31%|███       | 2259/7343 [00:38<01:24, 60.51it/s]

Reports:  31%|███       | 2267/7343 [00:38<01:19, 64.21it/s]

Reports:  31%|███       | 2274/7343 [00:38<01:18, 64.96it/s]

Reports:  31%|███       | 2281/7343 [00:38<01:21, 61.88it/s]

Reports:  31%|███       | 2289/7343 [00:38<01:16, 66.45it/s]

Reports:  31%|███▏      | 2296/7343 [00:39<01:28, 57.25it/s]

Reports:  31%|███▏      | 2306/7343 [00:39<01:17, 64.85it/s]

Reports:  31%|███▏      | 2313/7343 [00:39<01:27, 57.33it/s]

Reports:  32%|███▏      | 2320/7343 [00:39<01:30, 55.33it/s]

Reports:  32%|███▏      | 2327/7343 [00:39<01:26, 58.07it/s]

Reports:  32%|███▏      | 2335/7343 [00:39<01:26, 58.01it/s]

Reports:  32%|███▏      | 2343/7343 [00:39<01:19, 62.63it/s]

Reports:  32%|███▏      | 2350/7343 [00:39<01:21, 61.05it/s]

Reports:  32%|███▏      | 2358/7343 [00:40<01:19, 62.57it/s]

Reports:  32%|███▏      | 2367/7343 [00:40<01:11, 69.50it/s]

Reports:  32%|███▏      | 2375/7343 [00:40<01:18, 62.93it/s]

Reports:  32%|███▏      | 2382/7343 [00:40<01:19, 62.39it/s]

Reports:  33%|███▎      | 2392/7343 [00:40<01:11, 69.03it/s]

Reports:  33%|███▎      | 2400/7343 [00:40<01:16, 64.78it/s]

Reports:  33%|███▎      | 2408/7343 [00:40<01:18, 63.07it/s]

Reports:  33%|███▎      | 2415/7343 [00:40<01:17, 63.59it/s]

Reports:  33%|███▎      | 2425/7343 [00:41<01:11, 68.84it/s]

Reports:  33%|███▎      | 2432/7343 [00:41<01:12, 67.49it/s]

Reports:  33%|███▎      | 2439/7343 [00:41<01:20, 60.75it/s]

Reports:  33%|███▎      | 2447/7343 [00:41<01:14, 65.50it/s]

Reports:  33%|███▎      | 2455/7343 [00:41<01:22, 59.32it/s]

Reports:  34%|███▎      | 2465/7343 [00:41<01:11, 68.32it/s]

Reports:  34%|███▎      | 2473/7343 [00:41<01:23, 58.11it/s]

Reports:  34%|███▍      | 2480/7343 [00:41<01:20, 60.56it/s]

Reports:  34%|███▍      | 2489/7343 [00:42<01:13, 65.60it/s]

Reports:  34%|███▍      | 2496/7343 [00:42<01:14, 64.64it/s]

Reports:  34%|███▍      | 2506/7343 [00:42<01:11, 67.43it/s]

Reports:  34%|███▍      | 2513/7343 [00:42<01:13, 65.89it/s]

Reports:  34%|███▍      | 2520/7343 [00:42<01:19, 61.01it/s]

Reports:  34%|███▍      | 2528/7343 [00:42<01:14, 64.25it/s]

Reports:  35%|███▍      | 2536/7343 [00:42<01:12, 66.74it/s]

Reports:  35%|███▍      | 2543/7343 [00:43<01:29, 53.53it/s]

Reports:  35%|███▍      | 2550/7343 [00:43<01:23, 57.18it/s]

Reports:  35%|███▍      | 2560/7343 [00:43<01:12, 66.38it/s]

Reports:  35%|███▍      | 2568/7343 [00:43<01:18, 61.21it/s]

Reports:  35%|███▌      | 2578/7343 [00:43<01:07, 70.35it/s]

Reports:  35%|███▌      | 2586/7343 [00:43<01:10, 67.70it/s]

Reports:  35%|███▌      | 2594/7343 [00:43<01:20, 59.35it/s]

Reports:  35%|███▌      | 2602/7343 [00:43<01:16, 61.97it/s]

Reports:  36%|███▌      | 2609/7343 [00:44<01:15, 62.70it/s]

Reports:  36%|███▌      | 2616/7343 [00:44<01:16, 61.66it/s]

Reports:  36%|███▌      | 2624/7343 [00:44<01:12, 64.88it/s]

Reports:  36%|███▌      | 2631/7343 [00:44<01:16, 61.88it/s]

Reports:  36%|███▌      | 2638/7343 [00:44<01:20, 58.34it/s]

Reports:  36%|███▌      | 2645/7343 [00:44<01:19, 58.95it/s]

Reports:  36%|███▌      | 2652/7343 [00:44<01:16, 61.44it/s]

Reports:  36%|███▌      | 2660/7343 [00:44<01:11, 65.78it/s]

Reports:  36%|███▋      | 2667/7343 [00:44<01:21, 57.05it/s]

Reports:  36%|███▋      | 2679/7343 [00:45<01:12, 64.25it/s]

Reports:  37%|███▋      | 2686/7343 [00:45<01:20, 57.87it/s]

Reports:  37%|███▋      | 2693/7343 [00:45<01:17, 59.86it/s]

Reports:  37%|███▋      | 2701/7343 [00:45<01:13, 63.27it/s]

Reports:  37%|███▋      | 2708/7343 [00:45<01:24, 54.95it/s]

Reports:  37%|███▋      | 2719/7343 [00:45<01:15, 61.26it/s]

Reports:  37%|███▋      | 2726/7343 [00:45<01:13, 62.58it/s]

Reports:  37%|███▋      | 2733/7343 [00:46<01:21, 56.29it/s]

Reports:  37%|███▋      | 2742/7343 [00:46<01:12, 63.60it/s]

Reports:  37%|███▋      | 2749/7343 [00:46<01:19, 57.70it/s]

Reports:  38%|███▊      | 2758/7343 [00:46<01:12, 63.62it/s]

Reports:  38%|███▊      | 2765/7343 [00:46<01:16, 59.49it/s]

Reports:  38%|███▊      | 2772/7343 [00:46<01:20, 56.98it/s]

Reports:  38%|███▊      | 2783/7343 [00:46<01:13, 62.40it/s]

Reports:  38%|███▊      | 2790/7343 [00:47<01:17, 58.46it/s]

Reports:  38%|███▊      | 2801/7343 [00:47<01:05, 69.02it/s]

Reports:  38%|███▊      | 2809/7343 [00:47<01:13, 62.04it/s]

Reports:  38%|███▊      | 2817/7343 [00:47<01:13, 61.40it/s]

Reports:  38%|███▊      | 2825/7343 [00:47<01:10, 64.29it/s]

Reports:  39%|███▊      | 2832/7343 [00:47<01:10, 64.07it/s]

Reports:  39%|███▊      | 2839/7343 [00:47<01:12, 62.44it/s]

Reports:  39%|███▉      | 2846/7343 [00:47<01:20, 55.86it/s]

Reports:  39%|███▉      | 2856/7343 [00:48<01:17, 57.99it/s]

Reports:  39%|███▉      | 2862/7343 [00:48<01:23, 53.41it/s]

Reports:  39%|███▉      | 2871/7343 [00:48<01:13, 61.18it/s]

Reports:  39%|███▉      | 2878/7343 [00:48<01:20, 55.67it/s]

Reports:  39%|███▉      | 2889/7343 [00:48<01:09, 64.40it/s]

Reports:  39%|███▉      | 2896/7343 [00:48<01:13, 60.16it/s]

Reports:  40%|███▉      | 2903/7343 [00:48<01:13, 60.07it/s]

Reports:  40%|███▉      | 2910/7343 [00:49<01:13, 60.21it/s]

Reports:  40%|███▉      | 2917/7343 [00:49<01:17, 56.99it/s]

Reports:  40%|███▉      | 2923/7343 [00:49<01:17, 57.35it/s]

Reports:  40%|███▉      | 2930/7343 [00:49<01:25, 51.90it/s]

Reports:  40%|███▉      | 2936/7343 [00:49<01:24, 52.13it/s]

Reports:  40%|████      | 2945/7343 [00:49<01:13, 60.20it/s]

Reports:  40%|████      | 2952/7343 [00:49<01:21, 53.83it/s]

Reports:  40%|████      | 2959/7343 [00:49<01:16, 57.17it/s]

Reports:  40%|████      | 2965/7343 [00:50<01:17, 56.30it/s]

Reports:  41%|████      | 2975/7343 [00:50<01:12, 60.26it/s]

Reports:  41%|████      | 2982/7343 [00:50<01:26, 50.64it/s]

Reports:  41%|████      | 2995/7343 [00:50<01:04, 66.96it/s]

Reports:  41%|████      | 3003/7343 [00:50<01:25, 50.57it/s]

Reports:  41%|████      | 3014/7343 [00:50<01:16, 56.70it/s]

Reports:  41%|████      | 3021/7343 [00:51<01:26, 49.94it/s]

Reports:  41%|████▏     | 3030/7343 [00:51<01:15, 57.14it/s]

Reports:  41%|████▏     | 3037/7343 [00:51<01:24, 50.77it/s]

Reports:  41%|████▏     | 3043/7343 [00:51<01:31, 46.97it/s]

Reports:  42%|████▏     | 3050/7343 [00:51<01:27, 49.04it/s]

Reports:  42%|████▏     | 3060/7343 [00:51<01:15, 56.41it/s]

Reports:  42%|████▏     | 3066/7343 [00:51<01:21, 52.48it/s]

Reports:  42%|████▏     | 3074/7343 [00:52<01:12, 58.75it/s]

Reports:  42%|████▏     | 3081/7343 [00:52<01:15, 56.68it/s]

Reports:  42%|████▏     | 3087/7343 [00:52<01:16, 55.48it/s]

Reports:  42%|████▏     | 3094/7343 [00:52<01:11, 59.08it/s]

Reports:  42%|████▏     | 3101/7343 [00:52<01:18, 54.02it/s]

Reports:  42%|████▏     | 3107/7343 [00:52<01:27, 48.50it/s]

Reports:  42%|████▏     | 3113/7343 [00:52<01:27, 48.58it/s]

Reports:  43%|████▎     | 3122/7343 [00:52<01:13, 57.78it/s]

Reports:  43%|████▎     | 3129/7343 [00:53<01:24, 50.02it/s]

Reports:  43%|████▎     | 3135/7343 [00:53<01:22, 51.08it/s]

Reports:  43%|████▎     | 3141/7343 [00:53<01:21, 51.73it/s]

Reports:  43%|████▎     | 3150/7343 [00:53<01:18, 53.18it/s]

Reports:  43%|████▎     | 3157/7343 [00:53<01:14, 56.47it/s]

Reports:  43%|████▎     | 3163/7343 [00:53<01:17, 54.20it/s]

Reports:  43%|████▎     | 3169/7343 [00:53<01:26, 48.52it/s]

Reports:  43%|████▎     | 3176/7343 [00:53<01:18, 53.15it/s]

Reports:  43%|████▎     | 3183/7343 [00:54<01:14, 55.78it/s]

Reports:  43%|████▎     | 3189/7343 [00:54<01:17, 53.67it/s]

Reports:  44%|████▎     | 3198/7343 [00:54<01:07, 61.62it/s]

Reports:  44%|████▎     | 3205/7343 [00:54<01:20, 51.20it/s]

Reports:  44%|████▎     | 3211/7343 [00:54<01:18, 52.55it/s]

Reports:  44%|████▍     | 3220/7343 [00:54<01:09, 59.47it/s]

Reports:  44%|████▍     | 3227/7343 [00:54<01:11, 57.77it/s]

Reports:  44%|████▍     | 3233/7343 [00:54<01:11, 57.65it/s]

Reports:  44%|████▍     | 3239/7343 [00:55<01:20, 51.06it/s]

Reports:  44%|████▍     | 3245/7343 [00:55<01:17, 53.00it/s]

Reports:  44%|████▍     | 3253/7343 [00:55<01:12, 56.28it/s]

Reports:  44%|████▍     | 3259/7343 [00:55<01:16, 53.62it/s]

Reports:  44%|████▍     | 3266/7343 [00:55<01:19, 51.31it/s]

Reports:  45%|████▍     | 3272/7343 [00:55<01:33, 43.77it/s]

Reports:  45%|████▍     | 3280/7343 [00:55<01:24, 48.19it/s]

Reports:  45%|████▍     | 3288/7343 [00:56<01:15, 54.06it/s]

Reports:  45%|████▍     | 3294/7343 [00:56<01:21, 49.97it/s]

Reports:  45%|████▍     | 3303/7343 [00:56<01:13, 54.74it/s]

Reports:  45%|████▌     | 3309/7343 [00:56<01:18, 51.55it/s]

Reports:  45%|████▌     | 3317/7343 [00:56<01:12, 55.25it/s]

Reports:  45%|████▌     | 3323/7343 [00:56<01:15, 53.20it/s]

Reports:  45%|████▌     | 3329/7343 [00:56<01:22, 48.75it/s]

Reports:  45%|████▌     | 3336/7343 [00:56<01:18, 50.79it/s]

Reports:  46%|████▌     | 3343/7343 [00:57<01:13, 54.07it/s]

Reports:  46%|████▌     | 3349/7343 [00:57<01:12, 55.46it/s]

Reports:  46%|████▌     | 3355/7343 [00:57<01:33, 42.81it/s]

Reports:  46%|████▌     | 3362/7343 [00:57<01:24, 47.03it/s]

Reports:  46%|████▌     | 3369/7343 [00:57<01:20, 49.10it/s]

Reports:  46%|████▌     | 3376/7343 [00:57<01:14, 53.55it/s]

Reports:  46%|████▌     | 3382/7343 [00:57<01:12, 54.62it/s]

Reports:  46%|████▌     | 3388/7343 [00:57<01:13, 53.88it/s]

Reports:  46%|████▌     | 3394/7343 [00:58<01:11, 54.89it/s]

Reports:  46%|████▋     | 3400/7343 [00:58<01:18, 50.18it/s]

Reports:  46%|████▋     | 3406/7343 [00:58<01:20, 49.00it/s]

Reports:  46%|████▋     | 3414/7343 [00:58<01:11, 55.12it/s]

Reports:  47%|████▋     | 3420/7343 [00:58<01:17, 50.57it/s]

Reports:  47%|████▋     | 3426/7343 [00:58<01:17, 50.39it/s]

Reports:  47%|████▋     | 3433/7343 [00:58<01:28, 44.25it/s]

Reports:  47%|████▋     | 3444/7343 [00:59<01:07, 57.87it/s]

Reports:  47%|████▋     | 3451/7343 [00:59<01:10, 55.51it/s]

Reports:  47%|████▋     | 3457/7343 [00:59<01:10, 54.77it/s]

Reports:  47%|████▋     | 3463/7343 [00:59<01:12, 53.51it/s]

Reports:  47%|████▋     | 3469/7343 [00:59<01:18, 49.61it/s]

Reports:  47%|████▋     | 3476/7343 [00:59<01:13, 52.32it/s]

Reports:  47%|████▋     | 3482/7343 [00:59<01:16, 50.52it/s]

Reports:  48%|████▊     | 3489/7343 [00:59<01:15, 50.86it/s]

Reports:  48%|████▊     | 3497/7343 [01:00<01:19, 48.58it/s]

Reports:  48%|████▊     | 3503/7343 [01:00<01:15, 51.15it/s]

Reports:  48%|████▊     | 3511/7343 [01:00<01:07, 56.65it/s]

Reports:  48%|████▊     | 3517/7343 [01:00<01:11, 53.36it/s]

Reports:  48%|████▊     | 3523/7343 [01:00<01:14, 51.36it/s]

Reports:  48%|████▊     | 3530/7343 [01:00<01:10, 53.99it/s]

Reports:  48%|████▊     | 3537/7343 [01:00<01:07, 56.48it/s]

Reports:  48%|████▊     | 3544/7343 [01:00<01:06, 57.47it/s]

Reports:  48%|████▊     | 3550/7343 [01:01<01:17, 48.67it/s]

Reports:  48%|████▊     | 3557/7343 [01:01<01:16, 49.33it/s]

Reports:  49%|████▊     | 3565/7343 [01:01<01:10, 53.33it/s]

Reports:  49%|████▊     | 3571/7343 [01:01<01:13, 51.58it/s]

Reports:  49%|████▉     | 3580/7343 [01:01<01:04, 58.46it/s]

Reports:  49%|████▉     | 3586/7343 [01:01<01:14, 50.34it/s]

Reports:  49%|████▉     | 3592/7343 [01:01<01:17, 48.59it/s]

Reports:  49%|████▉     | 3600/7343 [01:02<01:06, 55.94it/s]

Reports:  49%|████▉     | 3606/7343 [01:02<01:13, 50.60it/s]

Reports:  49%|████▉     | 3612/7343 [01:02<01:12, 51.72it/s]

Reports:  49%|████▉     | 3618/7343 [01:02<01:15, 49.65it/s]

Reports:  49%|████▉     | 3624/7343 [01:02<01:15, 49.52it/s]

Reports:  49%|████▉     | 3633/7343 [01:02<01:03, 58.60it/s]

Reports:  50%|████▉     | 3640/7343 [01:02<01:17, 47.88it/s]

Reports:  50%|████▉     | 3646/7343 [01:02<01:15, 49.11it/s]

Reports:  50%|████▉     | 3652/7343 [01:03<01:11, 51.27it/s]

Reports:  50%|████▉     | 3659/7343 [01:03<01:06, 55.66it/s]

Reports:  50%|████▉     | 3665/7343 [01:03<01:10, 52.37it/s]

Reports:  50%|████▉     | 3671/7343 [01:03<01:14, 49.30it/s]

Reports:  50%|█████     | 3677/7343 [01:03<01:17, 47.11it/s]

Reports:  50%|█████     | 3682/7343 [01:03<01:18, 46.64it/s]

Reports:  50%|█████     | 3690/7343 [01:03<01:07, 54.17it/s]

Reports:  50%|█████     | 3696/7343 [01:03<01:07, 54.35it/s]

Reports:  50%|█████     | 3702/7343 [01:04<01:09, 52.19it/s]

Reports:  50%|█████     | 3708/7343 [01:04<01:15, 48.13it/s]

Reports:  51%|█████     | 3713/7343 [01:04<01:25, 42.66it/s]

Reports:  51%|█████     | 3720/7343 [01:04<01:16, 47.56it/s]

Reports:  51%|█████     | 3727/7343 [01:04<01:10, 51.58it/s]

Reports:  51%|█████     | 3733/7343 [01:04<01:10, 51.24it/s]

Reports:  51%|█████     | 3739/7343 [01:04<01:12, 49.88it/s]

Reports:  51%|█████     | 3745/7343 [01:04<01:14, 48.26it/s]

Reports:  51%|█████     | 3751/7343 [01:05<01:16, 47.01it/s]

Reports:  51%|█████     | 3757/7343 [01:05<01:23, 43.13it/s]

Reports:  51%|█████▏    | 3764/7343 [01:05<01:13, 48.46it/s]

Reports:  51%|█████▏    | 3770/7343 [01:05<01:19, 44.86it/s]

Reports:  51%|█████▏    | 3778/7343 [01:05<01:10, 50.26it/s]

Reports:  52%|█████▏    | 3784/7343 [01:05<01:08, 51.68it/s]

Reports:  52%|█████▏    | 3790/7343 [01:05<01:11, 49.55it/s]

Reports:  52%|█████▏    | 3796/7343 [01:06<01:18, 45.20it/s]

Reports:  52%|█████▏    | 3803/7343 [01:06<01:12, 48.91it/s]

Reports:  52%|█████▏    | 3812/7343 [01:06<01:00, 58.44it/s]

Reports:  52%|█████▏    | 3819/7343 [01:06<01:14, 47.56it/s]

Reports:  52%|█████▏    | 3826/7343 [01:06<01:09, 50.25it/s]

Reports:  52%|█████▏    | 3832/7343 [01:06<01:09, 50.48it/s]

Reports:  52%|█████▏    | 3839/7343 [01:06<01:05, 53.61it/s]

Reports:  52%|█████▏    | 3845/7343 [01:06<01:08, 51.27it/s]

Reports:  52%|█████▏    | 3851/7343 [01:07<01:08, 50.79it/s]

Reports:  53%|█████▎    | 3860/7343 [01:07<01:01, 56.27it/s]

Reports:  53%|█████▎    | 3866/7343 [01:07<01:13, 47.08it/s]

Reports:  53%|█████▎    | 3871/7343 [01:07<01:14, 46.52it/s]

Reports:  53%|█████▎    | 3876/7343 [01:07<01:32, 37.57it/s]

Reports:  53%|█████▎    | 3884/7343 [01:07<01:32, 37.32it/s]

Reports:  53%|█████▎    | 3897/7343 [01:08<01:04, 53.13it/s]

Reports:  53%|█████▎    | 3903/7343 [01:08<01:12, 47.36it/s]

Reports:  53%|█████▎    | 3909/7343 [01:08<01:19, 43.14it/s]

Reports:  53%|█████▎    | 3919/7343 [01:08<01:18, 43.66it/s]

Reports:  53%|█████▎    | 3926/7343 [01:08<01:14, 45.81it/s]

Reports:  54%|█████▎    | 3932/7343 [01:08<01:12, 47.23it/s]

Reports:  54%|█████▎    | 3937/7343 [01:08<01:11, 47.67it/s]

Reports:  54%|█████▎    | 3944/7343 [01:09<01:11, 47.27it/s]

Reports:  54%|█████▍    | 3949/7343 [01:09<01:13, 46.18it/s]

Reports:  54%|█████▍    | 3954/7343 [01:09<01:31, 37.10it/s]

Reports:  54%|█████▍    | 3960/7343 [01:09<01:29, 37.67it/s]

Reports:  54%|█████▍    | 3966/7343 [01:09<01:20, 42.08it/s]

Reports:  54%|█████▍    | 3973/7343 [01:09<01:10, 47.65it/s]

Reports:  54%|█████▍    | 3979/7343 [01:09<01:14, 45.20it/s]

Reports:  54%|█████▍    | 3985/7343 [01:10<01:16, 43.88it/s]

Reports:  54%|█████▍    | 3990/7343 [01:10<01:23, 39.96it/s]

Reports:  54%|█████▍    | 3996/7343 [01:10<01:18, 42.65it/s]

Reports:  55%|█████▍    | 4004/7343 [01:10<01:05, 50.89it/s]

Reports:  55%|█████▍    | 4010/7343 [01:10<01:19, 42.04it/s]

Reports:  55%|█████▍    | 4017/7343 [01:10<01:19, 41.66it/s]

Reports:  55%|█████▍    | 4022/7343 [01:11<01:21, 40.98it/s]

Reports:  55%|█████▍    | 4032/7343 [01:11<01:04, 51.02it/s]

Reports:  55%|█████▍    | 4038/7343 [01:11<01:15, 43.73it/s]

Reports:  55%|█████▌    | 4045/7343 [01:11<01:18, 42.10it/s]

Reports:  55%|█████▌    | 4055/7343 [01:11<01:02, 52.41it/s]

Reports:  55%|█████▌    | 4062/7343 [01:11<01:04, 50.66it/s]

Reports:  55%|█████▌    | 4070/7343 [01:11<01:06, 48.95it/s]

Reports:  56%|█████▌    | 4076/7343 [01:12<01:05, 50.10it/s]

Reports:  56%|█████▌    | 4082/7343 [01:12<01:04, 50.57it/s]

Reports:  56%|█████▌    | 4088/7343 [01:12<01:04, 50.30it/s]

Reports:  56%|█████▌    | 4094/7343 [01:12<01:03, 51.42it/s]

Reports:  56%|█████▌    | 4102/7343 [01:12<01:00, 53.98it/s]

Reports:  56%|█████▌    | 4109/7343 [01:12<01:02, 52.11it/s]

Reports:  56%|█████▌    | 4120/7343 [01:12<00:53, 60.70it/s]

Reports:  56%|█████▌    | 4127/7343 [01:13<01:10, 45.73it/s]

Reports:  56%|█████▋    | 4137/7343 [01:13<00:56, 56.31it/s]

Reports:  56%|█████▋    | 4144/7343 [01:13<01:12, 44.31it/s]

Reports:  57%|█████▋    | 4151/7343 [01:13<01:06, 48.05it/s]

Reports:  57%|█████▋    | 4159/7343 [01:13<01:02, 51.29it/s]

Reports:  57%|█████▋    | 4167/7343 [01:13<00:55, 57.32it/s]

Reports:  57%|█████▋    | 4174/7343 [01:13<01:00, 52.05it/s]

Reports:  57%|█████▋    | 4180/7343 [01:14<01:03, 49.52it/s]

Reports:  57%|█████▋    | 4188/7343 [01:14<00:56, 55.56it/s]

Reports:  57%|█████▋    | 4194/7343 [01:14<00:58, 53.58it/s]

Reports:  57%|█████▋    | 4200/7343 [01:14<01:01, 50.95it/s]

Reports:  57%|█████▋    | 4209/7343 [01:14<00:55, 56.93it/s]

Reports:  57%|█████▋    | 4215/7343 [01:14<00:55, 56.43it/s]

Reports:  57%|█████▋    | 4221/7343 [01:14<00:55, 56.06it/s]

Reports:  58%|█████▊    | 4227/7343 [01:14<00:55, 56.13it/s]

Reports:  58%|█████▊    | 4233/7343 [01:15<00:59, 51.91it/s]

Reports:  58%|█████▊    | 4241/7343 [01:15<00:57, 53.90it/s]

Reports:  58%|█████▊    | 4249/7343 [01:15<00:53, 58.26it/s]

Reports:  58%|█████▊    | 4255/7343 [01:15<00:54, 56.98it/s]

Reports:  58%|█████▊    | 4261/7343 [01:15<01:00, 50.60it/s]

Reports:  58%|█████▊    | 4267/7343 [01:15<01:07, 45.75it/s]

Reports:  58%|█████▊    | 4275/7343 [01:15<01:02, 49.17it/s]

Reports:  58%|█████▊    | 4284/7343 [01:16<00:54, 55.72it/s]

Reports:  58%|█████▊    | 4290/7343 [01:16<00:56, 54.28it/s]

Reports:  59%|█████▊    | 4296/7343 [01:16<00:58, 51.73it/s]

Reports:  59%|█████▊    | 4302/7343 [01:16<01:05, 46.30it/s]

Reports:  59%|█████▊    | 4308/7343 [01:16<01:09, 43.91it/s]

Reports:  59%|█████▉    | 4317/7343 [01:16<00:57, 53.00it/s]

Reports:  59%|█████▉    | 4323/7343 [01:16<00:55, 54.52it/s]

Reports:  59%|█████▉    | 4329/7343 [01:16<01:05, 46.19it/s]

Reports:  59%|█████▉    | 4337/7343 [01:17<00:55, 53.71it/s]

Reports:  59%|█████▉    | 4343/7343 [01:17<00:57, 51.94it/s]

Reports:  59%|█████▉    | 4351/7343 [01:17<00:54, 55.35it/s]

Reports:  59%|█████▉    | 4358/7343 [01:17<00:52, 57.08it/s]

Reports:  59%|█████▉    | 4365/7343 [01:17<00:50, 59.24it/s]

Reports:  60%|█████▉    | 4372/7343 [01:17<00:56, 52.27it/s]

Reports:  60%|█████▉    | 4382/7343 [01:17<00:50, 58.80it/s]

Reports:  60%|█████▉    | 4389/7343 [01:17<00:48, 60.93it/s]

Reports:  60%|█████▉    | 4397/7343 [01:18<00:53, 55.42it/s]

Reports:  60%|█████▉    | 4403/7343 [01:18<00:52, 55.75it/s]

Reports:  60%|██████    | 4409/7343 [01:18<00:54, 53.90it/s]

Reports:  60%|██████    | 4418/7343 [01:18<00:48, 60.41it/s]

Reports:  60%|██████    | 4425/7343 [01:18<00:57, 51.06it/s]

Reports:  60%|██████    | 4434/7343 [01:18<00:54, 53.57it/s]

Reports:  61%|██████    | 4444/7343 [01:18<00:49, 58.60it/s]

Reports:  61%|██████    | 4451/7343 [01:19<00:48, 59.35it/s]

Reports:  61%|██████    | 4458/7343 [01:19<00:54, 53.36it/s]

Reports:  61%|██████    | 4467/7343 [01:19<00:49, 57.89it/s]

Reports:  61%|██████    | 4473/7343 [01:19<00:54, 52.51it/s]

Reports:  61%|██████    | 4479/7343 [01:19<00:58, 49.04it/s]

Reports:  61%|██████    | 4488/7343 [01:19<00:50, 55.98it/s]

Reports:  61%|██████    | 4494/7343 [01:19<00:51, 55.26it/s]

Reports:  61%|██████▏   | 4502/7343 [01:20<00:49, 57.66it/s]

Reports:  61%|██████▏   | 4509/7343 [01:20<00:48, 58.77it/s]

Reports:  61%|██████▏   | 4515/7343 [01:20<00:54, 51.62it/s]

Reports:  62%|██████▏   | 4521/7343 [01:20<00:57, 49.28it/s]

Reports:  62%|██████▏   | 4532/7343 [01:20<00:45, 61.42it/s]

Reports:  62%|██████▏   | 4539/7343 [01:20<00:51, 54.95it/s]

Reports:  62%|██████▏   | 4546/7343 [01:20<00:52, 52.92it/s]

Reports:  62%|██████▏   | 4552/7343 [01:20<00:52, 52.97it/s]

Reports:  62%|██████▏   | 4562/7343 [01:21<00:46, 59.43it/s]

Reports:  62%|██████▏   | 4569/7343 [01:21<00:51, 54.26it/s]

Reports:  62%|██████▏   | 4576/7343 [01:21<00:48, 57.18it/s]

Reports:  62%|██████▏   | 4582/7343 [01:21<00:51, 53.96it/s]

Reports:  63%|██████▎   | 4592/7343 [01:21<00:44, 61.75it/s]

Reports:  63%|██████▎   | 4599/7343 [01:21<00:54, 50.49it/s]

Reports:  63%|██████▎   | 4610/7343 [01:21<00:46, 58.64it/s]

Reports:  63%|██████▎   | 4617/7343 [01:22<00:52, 51.85it/s]

Reports:  63%|██████▎   | 4623/7343 [01:22<00:54, 50.34it/s]

Reports:  63%|██████▎   | 4630/7343 [01:22<00:54, 49.63it/s]

Reports:  63%|██████▎   | 4638/7343 [01:22<00:49, 54.59it/s]

Reports:  63%|██████▎   | 4644/7343 [01:22<00:56, 47.82it/s]

Reports:  63%|██████▎   | 4652/7343 [01:22<00:49, 54.20it/s]

Reports:  63%|██████▎   | 4658/7343 [01:22<00:49, 54.47it/s]

Reports:  64%|██████▎   | 4665/7343 [01:23<00:45, 58.26it/s]

Reports:  64%|██████▎   | 4672/7343 [01:23<00:51, 52.01it/s]

Reports:  64%|██████▎   | 4678/7343 [01:23<00:56, 46.95it/s]

Reports:  64%|██████▍   | 4687/7343 [01:23<00:53, 49.42it/s]

Reports:  64%|██████▍   | 4693/7343 [01:23<00:55, 47.64it/s]

Reports:  64%|██████▍   | 4699/7343 [01:23<00:52, 50.32it/s]

Reports:  64%|██████▍   | 4705/7343 [01:23<00:59, 44.29it/s]

Reports:  64%|██████▍   | 4712/7343 [01:24<01:06, 39.79it/s]

Reports:  64%|██████▍   | 4725/7343 [01:24<00:49, 53.35it/s]

Reports:  64%|██████▍   | 4731/7343 [01:24<00:52, 49.39it/s]

Reports:  65%|██████▍   | 4737/7343 [01:24<00:55, 46.55it/s]

Reports:  65%|██████▍   | 4743/7343 [01:24<01:00, 43.18it/s]

Reports:  65%|██████▍   | 4752/7343 [01:24<00:50, 51.61it/s]

Reports:  65%|██████▍   | 4758/7343 [01:25<00:55, 46.90it/s]

Reports:  65%|██████▍   | 4770/7343 [01:25<00:52, 48.99it/s]

Reports:  65%|██████▌   | 4777/7343 [01:25<00:50, 50.83it/s]

Reports:  65%|██████▌   | 4788/7343 [01:25<00:41, 61.40it/s]

Reports:  65%|██████▌   | 4795/7343 [01:25<00:46, 54.46it/s]

Reports:  65%|██████▌   | 4802/7343 [01:25<00:46, 54.30it/s]

Reports:  65%|██████▌   | 4808/7343 [01:25<00:49, 51.03it/s]

Reports:  66%|██████▌   | 4815/7343 [01:26<00:51, 48.90it/s]

Reports:  66%|██████▌   | 4826/7343 [01:26<00:40, 61.76it/s]

Reports:  66%|██████▌   | 4833/7343 [01:26<00:45, 55.31it/s]

Reports:  66%|██████▌   | 4839/7343 [01:26<00:49, 50.53it/s]

Reports:  66%|██████▌   | 4845/7343 [01:26<00:53, 46.75it/s]

Reports:  66%|██████▌   | 4852/7343 [01:26<00:48, 51.64it/s]

Reports:  66%|██████▌   | 4858/7343 [01:26<00:52, 47.41it/s]

Reports:  66%|██████▋   | 4865/7343 [01:27<00:50, 49.31it/s]

Reports:  66%|██████▋   | 4871/7343 [01:27<00:52, 46.90it/s]

Reports:  66%|██████▋   | 4876/7343 [01:27<00:55, 44.79it/s]

Reports:  66%|██████▋   | 4881/7343 [01:27<00:57, 42.74it/s]

Reports:  67%|██████▋   | 4891/7343 [01:27<00:52, 46.89it/s]

Reports:  67%|██████▋   | 4896/7343 [01:27<00:57, 42.60it/s]

Reports:  67%|██████▋   | 4901/7343 [01:27<00:56, 42.85it/s]

Reports:  67%|██████▋   | 4906/7343 [01:28<00:59, 41.21it/s]

Reports:  67%|██████▋   | 4915/7343 [01:28<00:46, 52.46it/s]

Reports:  67%|██████▋   | 4921/7343 [01:28<00:51, 47.15it/s]

Reports:  67%|██████▋   | 4926/7343 [01:28<01:03, 37.78it/s]

Reports:  67%|██████▋   | 4933/7343 [01:28<00:55, 43.61it/s]

Reports:  67%|██████▋   | 4941/7343 [01:28<00:47, 50.30it/s]

Reports:  67%|██████▋   | 4947/7343 [01:28<00:51, 46.51it/s]

Reports:  68%|██████▊   | 4957/7343 [01:29<00:42, 56.05it/s]

Reports:  68%|██████▊   | 4963/7343 [01:29<00:47, 49.81it/s]

Reports:  68%|██████▊   | 4969/7343 [01:29<00:46, 50.85it/s]

Reports:  68%|██████▊   | 4975/7343 [01:29<00:45, 52.00it/s]

Reports:  68%|██████▊   | 4982/7343 [01:29<00:45, 51.40it/s]

Reports:  68%|██████▊   | 4988/7343 [01:29<00:46, 50.11it/s]

Reports:  68%|██████▊   | 4994/7343 [01:29<00:49, 47.90it/s]

Reports:  68%|██████▊   | 5000/7343 [01:29<00:52, 44.81it/s]

Reports:  68%|██████▊   | 5010/7343 [01:30<00:42, 55.46it/s]

Reports:  68%|██████▊   | 5016/7343 [01:30<00:43, 53.80it/s]

Reports:  68%|██████▊   | 5022/7343 [01:30<00:44, 51.89it/s]

Reports:  69%|██████▊   | 5032/7343 [01:30<00:39, 57.95it/s]

Reports:  69%|██████▊   | 5040/7343 [01:30<00:38, 59.90it/s]

Reports:  69%|██████▊   | 5047/7343 [01:30<00:43, 52.30it/s]

Reports:  69%|██████▉   | 5053/7343 [01:30<00:43, 52.25it/s]

Reports:  69%|██████▉   | 5059/7343 [01:31<00:45, 50.67it/s]

Reports:  69%|██████▉   | 5069/7343 [01:31<00:37, 60.60it/s]

Reports:  69%|██████▉   | 5076/7343 [01:31<00:41, 54.98it/s]

Reports:  69%|██████▉   | 5082/7343 [01:31<00:42, 53.23it/s]

Reports:  69%|██████▉   | 5088/7343 [01:31<00:41, 54.73it/s]

Reports:  69%|██████▉   | 5094/7343 [01:31<00:40, 55.53it/s]

Reports:  69%|██████▉   | 5100/7343 [01:31<00:44, 50.66it/s]

Reports:  70%|██████▉   | 5110/7343 [01:31<00:35, 62.57it/s]

Reports:  70%|██████▉   | 5117/7343 [01:32<00:41, 54.14it/s]

Reports:  70%|██████▉   | 5123/7343 [01:32<00:44, 49.95it/s]

Reports:  70%|██████▉   | 5129/7343 [01:32<00:47, 46.94it/s]

Reports:  70%|███████   | 5141/7343 [01:32<00:38, 57.19it/s]

Reports:  70%|███████   | 5147/7343 [01:32<00:40, 54.76it/s]

Reports:  70%|███████   | 5153/7343 [01:32<00:49, 44.08it/s]

Reports:  70%|███████   | 5162/7343 [01:32<00:46, 47.22it/s]

Reports:  70%|███████   | 5167/7343 [01:33<00:47, 45.69it/s]

Reports:  70%|███████   | 5176/7343 [01:33<00:42, 50.85it/s]

Reports:  71%|███████   | 5183/7343 [01:33<00:41, 52.65it/s]

Reports:  71%|███████   | 5189/7343 [01:33<00:43, 49.77it/s]

Reports:  71%|███████   | 5196/7343 [01:33<00:43, 49.01it/s]

Reports:  71%|███████   | 5201/7343 [01:33<00:44, 48.21it/s]

Reports:  71%|███████   | 5206/7343 [01:33<00:48, 43.75it/s]

Reports:  71%|███████   | 5212/7343 [01:34<00:48, 44.23it/s]

Reports:  71%|███████   | 5222/7343 [01:34<00:37, 57.26it/s]

Reports:  71%|███████   | 5229/7343 [01:34<00:42, 49.74it/s]

Reports:  71%|███████▏  | 5235/7343 [01:34<00:50, 41.81it/s]

Reports:  71%|███████▏  | 5247/7343 [01:34<00:43, 48.53it/s]

Reports:  72%|███████▏  | 5255/7343 [01:34<00:39, 53.26it/s]

Reports:  72%|███████▏  | 5261/7343 [01:35<00:44, 47.13it/s]

Reports:  72%|███████▏  | 5272/7343 [01:35<00:38, 54.13it/s]

Reports:  72%|███████▏  | 5278/7343 [01:35<00:41, 50.24it/s]

Reports:  72%|███████▏  | 5285/7343 [01:35<00:37, 54.40it/s]

Reports:  72%|███████▏  | 5291/7343 [01:35<00:39, 51.31it/s]

Reports:  72%|███████▏  | 5297/7343 [01:35<00:43, 46.57it/s]

Reports:  72%|███████▏  | 5302/7343 [01:35<00:45, 45.29it/s]

Reports:  72%|███████▏  | 5308/7343 [01:35<00:42, 47.49it/s]

Reports:  72%|███████▏  | 5314/7343 [01:36<00:40, 49.74it/s]

Reports:  72%|███████▏  | 5320/7343 [01:36<00:49, 40.80it/s]

Reports:  73%|███████▎  | 5330/7343 [01:36<00:38, 52.60it/s]

Reports:  73%|███████▎  | 5336/7343 [01:36<00:43, 46.65it/s]

Reports:  73%|███████▎  | 5342/7343 [01:36<00:45, 43.63it/s]

Reports:  73%|███████▎  | 5348/7343 [01:36<00:43, 46.07it/s]

Reports:  73%|███████▎  | 5355/7343 [01:36<00:38, 51.58it/s]

Reports:  73%|███████▎  | 5362/7343 [01:37<00:38, 51.20it/s]

Reports:  73%|███████▎  | 5368/7343 [01:37<00:41, 47.42it/s]

Reports:  73%|███████▎  | 5373/7343 [01:37<00:45, 43.12it/s]

Reports:  73%|███████▎  | 5385/7343 [01:37<00:35, 55.69it/s]

Reports:  73%|███████▎  | 5391/7343 [01:37<00:36, 53.73it/s]

Reports:  74%|███████▎  | 5400/7343 [01:37<00:36, 53.40it/s]

Reports:  74%|███████▎  | 5406/7343 [01:37<00:36, 53.39it/s]

Reports:  74%|███████▎  | 5412/7343 [01:38<00:35, 54.30it/s]

Reports:  74%|███████▍  | 5418/7343 [01:38<00:34, 55.62it/s]

Reports:  74%|███████▍  | 5424/7343 [01:38<00:38, 49.44it/s]

Reports:  74%|███████▍  | 5431/7343 [01:38<00:35, 53.52it/s]

Reports:  74%|███████▍  | 5439/7343 [01:38<00:31, 59.54it/s]

Reports:  74%|███████▍  | 5446/7343 [01:38<00:35, 53.24it/s]

Reports:  74%|███████▍  | 5452/7343 [01:38<00:38, 48.76it/s]

Reports:  74%|███████▍  | 5458/7343 [01:38<00:39, 47.90it/s]

Reports:  74%|███████▍  | 5467/7343 [01:39<00:33, 56.13it/s]

Reports:  75%|███████▍  | 5473/7343 [01:39<00:33, 56.03it/s]

Reports:  75%|███████▍  | 5481/7343 [01:39<00:33, 55.00it/s]

Reports:  75%|███████▍  | 5489/7343 [01:39<00:35, 51.96it/s]

Reports:  75%|███████▍  | 5499/7343 [01:39<00:30, 60.66it/s]

Reports:  75%|███████▍  | 5506/7343 [01:39<00:33, 54.07it/s]

Reports:  75%|███████▌  | 5513/7343 [01:39<00:32, 56.58it/s]

Reports:  75%|███████▌  | 5520/7343 [01:40<00:31, 57.28it/s]

Reports:  75%|███████▌  | 5526/7343 [01:40<00:31, 57.22it/s]

Reports:  75%|███████▌  | 5535/7343 [01:40<00:28, 63.64it/s]

Reports:  75%|███████▌  | 5542/7343 [01:40<00:33, 53.22it/s]

Reports:  76%|███████▌  | 5550/7343 [01:40<00:32, 54.60it/s]

Reports:  76%|███████▌  | 5557/7343 [01:40<00:31, 56.54it/s]

Reports:  76%|███████▌  | 5564/7343 [01:40<00:30, 57.76it/s]

Reports:  76%|███████▌  | 5570/7343 [01:40<00:31, 55.96it/s]

Reports:  76%|███████▌  | 5578/7343 [01:41<00:35, 49.62it/s]

Reports:  76%|███████▌  | 5585/7343 [01:41<00:33, 53.17it/s]

Reports:  76%|███████▌  | 5591/7343 [01:41<00:34, 51.13it/s]

Reports:  76%|███████▋  | 5601/7343 [01:41<00:35, 49.73it/s]

Reports:  76%|███████▋  | 5608/7343 [01:41<00:32, 53.48it/s]

Reports:  76%|███████▋  | 5614/7343 [01:41<00:35, 48.11it/s]

Reports:  77%|███████▋  | 5620/7343 [01:41<00:41, 41.98it/s]

Reports:  77%|███████▋  | 5627/7343 [01:42<00:40, 42.76it/s]

Reports:  77%|███████▋  | 5637/7343 [01:42<00:33, 51.61it/s]

Reports:  77%|███████▋  | 5643/7343 [01:42<00:32, 51.79it/s]

Reports:  77%|███████▋  | 5649/7343 [01:42<00:39, 43.10it/s]

Reports:  77%|███████▋  | 5654/7343 [01:42<00:38, 43.98it/s]

Reports:  77%|███████▋  | 5659/7343 [01:42<00:38, 43.55it/s]

Reports:  77%|███████▋  | 5667/7343 [01:42<00:32, 51.67it/s]

Reports:  77%|███████▋  | 5673/7343 [01:43<00:35, 46.77it/s]

Reports:  77%|███████▋  | 5679/7343 [01:43<00:33, 49.48it/s]

Reports:  77%|███████▋  | 5686/7343 [01:43<00:30, 53.96it/s]

Reports:  78%|███████▊  | 5693/7343 [01:43<00:28, 57.32it/s]

Reports:  78%|███████▊  | 5701/7343 [01:43<00:28, 58.32it/s]

Reports:  78%|███████▊  | 5707/7343 [01:43<00:28, 56.70it/s]

Reports:  78%|███████▊  | 5714/7343 [01:43<00:29, 56.11it/s]

Reports:  78%|███████▊  | 5720/7343 [01:43<00:29, 54.38it/s]

Reports:  78%|███████▊  | 5726/7343 [01:44<00:31, 50.74it/s]

Reports:  78%|███████▊  | 5733/7343 [01:44<00:30, 53.34it/s]

Reports:  78%|███████▊  | 5739/7343 [01:44<00:30, 52.41it/s]

Reports:  78%|███████▊  | 5747/7343 [01:44<00:26, 59.52it/s]

Reports:  78%|███████▊  | 5754/7343 [01:44<00:28, 56.10it/s]

Reports:  78%|███████▊  | 5761/7343 [01:44<00:26, 59.23it/s]

Reports:  79%|███████▊  | 5768/7343 [01:44<00:27, 57.30it/s]

Reports:  79%|███████▊  | 5776/7343 [01:44<00:24, 63.04it/s]

Reports:  79%|███████▉  | 5783/7343 [01:44<00:25, 61.90it/s]

Reports:  79%|███████▉  | 5790/7343 [01:45<00:25, 61.26it/s]

Reports:  79%|███████▉  | 5797/7343 [01:45<00:27, 56.27it/s]

Reports:  79%|███████▉  | 5804/7343 [01:45<00:28, 53.62it/s]

Reports:  79%|███████▉  | 5812/7343 [01:45<00:28, 53.65it/s]

Reports:  79%|███████▉  | 5818/7343 [01:45<00:29, 51.84it/s]

Reports:  79%|███████▉  | 5824/7343 [01:45<00:33, 44.83it/s]

Reports:  79%|███████▉  | 5832/7343 [01:45<00:30, 49.56it/s]

Reports:  80%|███████▉  | 5838/7343 [01:46<00:30, 49.87it/s]

Reports:  80%|███████▉  | 5846/7343 [01:46<00:27, 54.49it/s]

Reports:  80%|███████▉  | 5855/7343 [01:46<00:24, 61.04it/s]

Reports:  80%|███████▉  | 5862/7343 [01:46<00:25, 58.32it/s]

Reports:  80%|███████▉  | 5868/7343 [01:46<00:26, 54.69it/s]

Reports:  80%|███████▉  | 5874/7343 [01:46<00:28, 52.38it/s]

Reports:  80%|████████  | 5882/7343 [01:46<00:24, 58.64it/s]

Reports:  80%|████████  | 5889/7343 [01:46<00:24, 58.39it/s]

Reports:  80%|████████  | 5899/7343 [01:47<00:23, 62.42it/s]

Reports:  80%|████████  | 5906/7343 [01:47<00:23, 61.20it/s]

Reports:  81%|████████  | 5913/7343 [01:47<00:22, 62.42it/s]

Reports:  81%|████████  | 5920/7343 [01:47<00:24, 57.55it/s]

Reports:  81%|████████  | 5927/7343 [01:47<00:23, 60.19it/s]

Reports:  81%|████████  | 5934/7343 [01:47<00:23, 60.01it/s]

Reports:  81%|████████  | 5941/7343 [01:47<00:23, 60.47it/s]

Reports:  81%|████████  | 5948/7343 [01:47<00:28, 48.69it/s]

Reports:  81%|████████  | 5958/7343 [01:48<00:23, 59.04it/s]

Reports:  81%|████████  | 5965/7343 [01:48<00:24, 56.43it/s]

Reports:  81%|████████▏ | 5972/7343 [01:48<00:22, 59.65it/s]

Reports:  81%|████████▏ | 5979/7343 [01:48<00:24, 55.41it/s]

Reports:  82%|████████▏ | 5988/7343 [01:48<00:23, 57.18it/s]

Reports:  82%|████████▏ | 5994/7343 [01:48<00:27, 48.67it/s]

Reports:  82%|████████▏ | 6004/7343 [01:48<00:22, 60.01it/s]

Reports:  82%|████████▏ | 6011/7343 [01:49<00:23, 57.15it/s]

Reports:  82%|████████▏ | 6018/7343 [01:49<00:23, 57.17it/s]

Reports:  82%|████████▏ | 6026/7343 [01:49<00:22, 58.94it/s]

Reports:  82%|████████▏ | 6033/7343 [01:49<00:22, 57.33it/s]

Reports:  82%|████████▏ | 6041/7343 [01:49<00:24, 53.17it/s]

Reports:  82%|████████▏ | 6048/7343 [01:49<00:22, 56.96it/s]

Reports:  82%|████████▏ | 6057/7343 [01:49<00:20, 62.71it/s]

Reports:  83%|████████▎ | 6064/7343 [01:50<00:24, 52.61it/s]

Reports:  83%|████████▎ | 6076/7343 [01:50<00:20, 61.32it/s]

Reports:  83%|████████▎ | 6083/7343 [01:50<00:21, 59.63it/s]

Reports:  83%|████████▎ | 6090/7343 [01:50<00:21, 58.44it/s]

Reports:  83%|████████▎ | 6099/7343 [01:50<00:20, 60.81it/s]

Reports:  83%|████████▎ | 6106/7343 [01:50<00:19, 62.39it/s]

Reports:  83%|████████▎ | 6113/7343 [01:50<00:20, 59.97it/s]

Reports:  83%|████████▎ | 6120/7343 [01:50<00:21, 55.91it/s]

Reports:  83%|████████▎ | 6126/7343 [01:51<00:22, 54.76it/s]

Reports:  84%|████████▎ | 6134/7343 [01:51<00:20, 60.12it/s]

Reports:  84%|████████▎ | 6141/7343 [01:51<00:20, 59.62it/s]

Reports:  84%|████████▎ | 6148/7343 [01:51<00:21, 55.74it/s]

Reports:  84%|████████▍ | 6155/7343 [01:51<00:21, 55.86it/s]

Reports:  84%|████████▍ | 6162/7343 [01:51<00:20, 58.30it/s]

Reports:  84%|████████▍ | 6168/7343 [01:51<00:20, 57.69it/s]

Reports:  84%|████████▍ | 6174/7343 [01:51<00:20, 56.65it/s]

Reports:  84%|████████▍ | 6183/7343 [01:51<00:18, 62.77it/s]

Reports:  84%|████████▍ | 6190/7343 [01:52<00:19, 57.66it/s]

Reports:  84%|████████▍ | 6196/7343 [01:52<00:21, 54.37it/s]

Reports:  85%|████████▍ | 6205/7343 [01:52<00:18, 61.28it/s]

Reports:  85%|████████▍ | 6212/7343 [01:52<00:20, 56.41it/s]

Reports:  85%|████████▍ | 6220/7343 [01:52<00:18, 61.04it/s]

Reports:  85%|████████▍ | 6227/7343 [01:52<00:18, 58.98it/s]

Reports:  85%|████████▍ | 6236/7343 [01:52<00:16, 66.06it/s]

Reports:  85%|████████▌ | 6243/7343 [01:53<00:19, 56.11it/s]

Reports:  85%|████████▌ | 6249/7343 [01:53<00:19, 55.40it/s]

Reports:  85%|████████▌ | 6257/7343 [01:53<00:18, 60.14it/s]

Reports:  85%|████████▌ | 6264/7343 [01:53<00:22, 48.55it/s]

Reports:  85%|████████▌ | 6274/7343 [01:53<00:18, 57.99it/s]

Reports:  86%|████████▌ | 6281/7343 [01:53<00:18, 58.33it/s]

Reports:  86%|████████▌ | 6288/7343 [01:53<00:17, 59.81it/s]

Reports:  86%|████████▌ | 6295/7343 [01:53<00:19, 53.62it/s]

Reports:  86%|████████▌ | 6302/7343 [01:54<00:19, 54.42it/s]

Reports:  86%|████████▌ | 6309/7343 [01:54<00:17, 57.68it/s]

Reports:  86%|████████▌ | 6317/7343 [01:54<00:19, 53.63it/s]

Reports:  86%|████████▌ | 6324/7343 [01:54<00:18, 56.34it/s]

Reports:  86%|████████▌ | 6330/7343 [01:54<00:20, 49.46it/s]

Reports:  86%|████████▋ | 6336/7343 [01:54<00:20, 48.96it/s]

Reports:  86%|████████▋ | 6345/7343 [01:54<00:18, 54.57it/s]

Reports:  86%|████████▋ | 6351/7343 [01:55<00:19, 50.64it/s]

Reports:  87%|████████▋ | 6358/7343 [01:55<00:20, 48.78it/s]

Reports:  87%|████████▋ | 6364/7343 [01:55<00:21, 45.83it/s]

Reports:  87%|████████▋ | 6374/7343 [01:55<00:18, 52.76it/s]

Reports:  87%|████████▋ | 6380/7343 [01:55<00:17, 54.29it/s]

Reports:  87%|████████▋ | 6386/7343 [01:55<00:18, 51.20it/s]

Reports:  87%|████████▋ | 6398/7343 [01:55<00:17, 54.32it/s]

Reports:  87%|████████▋ | 6404/7343 [01:56<00:17, 54.70it/s]

Reports:  87%|████████▋ | 6410/7343 [01:56<00:17, 54.27it/s]

Reports:  87%|████████▋ | 6416/7343 [01:56<00:18, 50.56it/s]

Reports:  87%|████████▋ | 6422/7343 [01:56<00:17, 52.17it/s]

Reports:  88%|████████▊ | 6428/7343 [01:56<00:17, 51.05it/s]

Reports:  88%|████████▊ | 6434/7343 [01:56<00:19, 46.44it/s]

Reports:  88%|████████▊ | 6444/7343 [01:56<00:16, 53.91it/s]

Reports:  88%|████████▊ | 6450/7343 [01:56<00:16, 54.70it/s]

Reports:  88%|████████▊ | 6456/7343 [01:57<00:16, 55.21it/s]

Reports:  88%|████████▊ | 6462/7343 [01:57<00:17, 50.38it/s]

Reports:  88%|████████▊ | 6468/7343 [01:57<00:17, 50.33it/s]

Reports:  88%|████████▊ | 6474/7343 [01:57<00:18, 47.86it/s]

Reports:  88%|████████▊ | 6482/7343 [01:57<00:15, 55.46it/s]

Reports:  88%|████████▊ | 6488/7343 [01:57<00:16, 52.14it/s]

Reports:  88%|████████▊ | 6495/7343 [01:57<00:15, 55.49it/s]

Reports:  89%|████████▊ | 6501/7343 [01:57<00:14, 56.42it/s]

Reports:  89%|████████▊ | 6509/7343 [01:58<00:13, 61.33it/s]

Reports:  89%|████████▊ | 6516/7343 [01:58<00:13, 62.77it/s]

Reports:  89%|████████▉ | 6523/7343 [01:58<00:12, 64.23it/s]

Reports:  89%|████████▉ | 6530/7343 [01:58<00:15, 53.57it/s]

Reports:  89%|████████▉ | 6540/7343 [01:58<00:12, 62.51it/s]

Reports:  89%|████████▉ | 6547/7343 [01:58<00:13, 56.88it/s]

Reports:  89%|████████▉ | 6554/7343 [01:58<00:16, 48.03it/s]

Reports:  89%|████████▉ | 6569/7343 [01:58<00:11, 69.80it/s]

Reports:  90%|████████▉ | 6578/7343 [01:59<00:14, 51.51it/s]

Reports:  90%|████████▉ | 6587/7343 [01:59<00:12, 58.36it/s]

Reports:  90%|████████▉ | 6595/7343 [01:59<00:13, 55.08it/s]

Reports:  90%|████████▉ | 6603/7343 [01:59<00:13, 56.74it/s]

Reports:  90%|█████████ | 6610/7343 [01:59<00:15, 48.36it/s]

Reports:  90%|█████████ | 6622/7343 [01:59<00:11, 62.41it/s]

Reports:  90%|█████████ | 6630/7343 [02:00<00:12, 54.95it/s]

Reports:  90%|█████████ | 6637/7343 [02:00<00:12, 54.63it/s]

Reports:  90%|█████████ | 6644/7343 [02:00<00:13, 50.87it/s]

Reports:  91%|█████████ | 6652/7343 [02:00<00:12, 55.18it/s]

Reports:  91%|█████████ | 6658/7343 [02:00<00:12, 55.34it/s]

Reports:  91%|█████████ | 6664/7343 [02:00<00:12, 55.74it/s]

Reports:  91%|█████████ | 6670/7343 [02:00<00:12, 53.47it/s]

Reports:  91%|█████████ | 6681/7343 [02:01<00:09, 66.81it/s]

Reports:  91%|█████████ | 6688/7343 [02:01<00:12, 53.78it/s]

Reports:  91%|█████████ | 6697/7343 [02:01<00:11, 58.39it/s]

Reports:  91%|█████████▏| 6704/7343 [02:01<00:11, 53.91it/s]

Reports:  91%|█████████▏| 6715/7343 [02:01<00:09, 65.31it/s]

Reports:  92%|█████████▏| 6723/7343 [02:01<00:10, 57.05it/s]

Reports:  92%|█████████▏| 6730/7343 [02:01<00:10, 59.02it/s]

Reports:  92%|█████████▏| 6739/7343 [02:02<00:10, 59.36it/s]

Reports:  92%|█████████▏| 6746/7343 [02:02<00:09, 61.70it/s]

Reports:  92%|█████████▏| 6753/7343 [02:02<00:11, 52.25it/s]

Reports:  92%|█████████▏| 6764/7343 [02:02<00:09, 62.71it/s]

Reports:  92%|█████████▏| 6771/7343 [02:02<00:10, 57.10it/s]

Reports:  92%|█████████▏| 6781/7343 [02:02<00:08, 63.05it/s]

Reports:  92%|█████████▏| 6788/7343 [02:02<00:09, 60.44it/s]

Reports:  93%|█████████▎| 6795/7343 [02:02<00:09, 60.33it/s]

Reports:  93%|█████████▎| 6802/7343 [02:03<00:08, 61.77it/s]

Reports:  93%|█████████▎| 6809/7343 [02:03<00:09, 57.20it/s]

Reports:  93%|█████████▎| 6816/7343 [02:03<00:08, 60.05it/s]

Reports:  93%|█████████▎| 6823/7343 [02:03<00:08, 58.84it/s]

Reports:  93%|█████████▎| 6829/7343 [02:03<00:09, 54.61it/s]

Reports:  93%|█████████▎| 6835/7343 [02:03<00:09, 55.33it/s]

Reports:  93%|█████████▎| 6843/7343 [02:03<00:08, 57.62it/s]

Reports:  93%|█████████▎| 6849/7343 [02:03<00:09, 54.30it/s]

Reports:  93%|█████████▎| 6858/7343 [02:04<00:08, 57.40it/s]

Reports:  93%|█████████▎| 6864/7343 [02:04<00:08, 55.30it/s]

Reports:  94%|█████████▎| 6872/7343 [02:04<00:07, 60.86it/s]

Reports:  94%|█████████▎| 6879/7343 [02:04<00:08, 55.93it/s]

Reports:  94%|█████████▍| 6885/7343 [02:04<00:08, 53.19it/s]

Reports:  94%|█████████▍| 6893/7343 [02:04<00:07, 58.66it/s]

Reports:  94%|█████████▍| 6899/7343 [02:04<00:08, 54.91it/s]

Reports:  94%|█████████▍| 6905/7343 [02:04<00:08, 51.15it/s]

Reports:  94%|█████████▍| 6916/7343 [02:05<00:06, 61.28it/s]

Reports:  94%|█████████▍| 6923/7343 [02:05<00:07, 59.90it/s]

Reports:  94%|█████████▍| 6930/7343 [02:05<00:06, 62.00it/s]

Reports:  94%|█████████▍| 6937/7343 [02:05<00:06, 61.15it/s]

Reports:  95%|█████████▍| 6945/7343 [02:05<00:06, 60.96it/s]

Reports:  95%|█████████▍| 6952/7343 [02:05<00:06, 58.20it/s]

Reports:  95%|█████████▍| 6961/7343 [02:05<00:07, 52.76it/s]

Reports:  95%|█████████▍| 6970/7343 [02:06<00:06, 60.64it/s]

Reports:  95%|█████████▌| 6977/7343 [02:06<00:06, 53.03it/s]

Reports:  95%|█████████▌| 6987/7343 [02:06<00:06, 55.15it/s]

Reports:  95%|█████████▌| 6995/7343 [02:06<00:06, 55.62it/s]

Reports:  95%|█████████▌| 7001/7343 [02:06<00:07, 48.01it/s]

Reports:  95%|█████████▌| 7010/7343 [02:06<00:05, 56.49it/s]

Reports:  96%|█████████▌| 7017/7343 [02:06<00:05, 57.32it/s]

Reports:  96%|█████████▌| 7025/7343 [02:07<00:05, 59.63it/s]

Reports:  96%|█████████▌| 7034/7343 [02:07<00:04, 65.82it/s]

Reports:  96%|█████████▌| 7041/7343 [02:07<00:05, 57.32it/s]

Reports:  96%|█████████▌| 7048/7343 [02:07<00:04, 59.94it/s]

Reports:  96%|█████████▌| 7055/7343 [02:07<00:05, 55.56it/s]

Reports:  96%|█████████▌| 7063/7343 [02:07<00:04, 57.63it/s]

Reports:  96%|█████████▋| 7073/7343 [02:07<00:04, 65.64it/s]

Reports:  96%|█████████▋| 7080/7343 [02:07<00:04, 59.79it/s]

Reports:  97%|█████████▋| 7093/7343 [02:08<00:03, 66.95it/s]

Reports:  97%|█████████▋| 7100/7343 [02:08<00:03, 62.71it/s]

Reports:  97%|█████████▋| 7110/7343 [02:08<00:03, 62.87it/s]

Reports:  97%|█████████▋| 7118/7343 [02:08<00:03, 58.01it/s]

Reports:  97%|█████████▋| 7127/7343 [02:08<00:03, 59.81it/s]

Reports:  97%|█████████▋| 7134/7343 [02:08<00:03, 53.55it/s]

Reports:  97%|█████████▋| 7142/7343 [02:09<00:03, 56.93it/s]

Reports:  97%|█████████▋| 7148/7343 [02:09<00:03, 55.56it/s]

Reports:  97%|█████████▋| 7156/7343 [02:09<00:03, 58.68it/s]

Reports:  98%|█████████▊| 7162/7343 [02:09<00:03, 55.72it/s]

Reports:  98%|█████████▊| 7168/7343 [02:09<00:03, 54.91it/s]

Reports:  98%|█████████▊| 7178/7343 [02:09<00:02, 63.70it/s]

Reports:  98%|█████████▊| 7185/7343 [02:09<00:02, 53.86it/s]

Reports:  98%|█████████▊| 7198/7343 [02:09<00:02, 61.92it/s]

Reports:  98%|█████████▊| 7205/7343 [02:10<00:02, 57.13it/s]

Reports:  98%|█████████▊| 7211/7343 [02:10<00:02, 55.94it/s]

Reports:  98%|█████████▊| 7217/7343 [02:10<00:02, 54.22it/s]

Reports:  98%|█████████▊| 7226/7343 [02:10<00:01, 61.77it/s]

Reports:  99%|█████████▊| 7233/7343 [02:10<00:01, 60.87it/s]

Reports:  99%|█████████▊| 7241/7343 [02:10<00:01, 53.77it/s]

Reports:  99%|█████████▉| 7252/7343 [02:10<00:01, 65.63it/s]

Reports:  99%|█████████▉| 7259/7343 [02:11<00:01, 55.23it/s]

Reports:  99%|█████████▉| 7268/7343 [02:11<00:01, 56.03it/s]

Reports:  99%|█████████▉| 7274/7343 [02:11<00:01, 55.52it/s]

Reports:  99%|█████████▉| 7280/7343 [02:11<00:01, 53.99it/s]

Reports:  99%|█████████▉| 7289/7343 [02:11<00:00, 56.60it/s]

Reports:  99%|█████████▉| 7295/7343 [02:11<00:00, 49.84it/s]

Reports:  99%|█████████▉| 7306/7343 [02:11<00:00, 58.42it/s]

Reports: 100%|█████████▉| 7312/7343 [02:12<00:00, 53.55it/s]

Reports: 100%|█████████▉| 7320/7343 [02:12<00:00, 59.66it/s]

Reports: 100%|█████████▉| 7327/7343 [02:12<00:00, 48.28it/s]

Reports: 100%|█████████▉| 7334/7343 [02:12<00:00, 49.68it/s]

Reports: 100%|█████████▉| 7340/7343 [02:12<00:00, 29.99it/s]

Reports: 100%|██████████| 7343/7343 [02:12<00:00, 55.25it/s]

Report rows: 3650

Gaps (ex-reports):   0%|          | 0/7343 [00:00<?, ?it/s]

Gaps (ex-reports):   0%|          | 4/7343 [00:00<03:17, 37.18it/s]

Gaps (ex-reports):   0%|          | 13/7343 [00:00<02:02, 60.04it/s]

Gaps (ex-reports):   0%|          | 19/7343 [00:00<02:25, 50.35it/s]

Gaps (ex-reports):   0%|          | 25/7343 [00:00<02:16, 53.58it/s]

Gaps (ex-reports):   0%|          | 35/7343 [00:00<01:48, 67.47it/s]

Gaps (ex-reports):   1%|          | 42/7343 [00:00<02:01, 59.90it/s]

Gaps (ex-reports):   1%|          | 49/7343 [00:00<02:16, 53.27it/s]

Gaps (ex-reports):   1%|          | 58/7343 [00:00<02:00, 60.70it/s]

Gaps (ex-reports):   1%|          | 65/7343 [00:01<02:11, 55.29it/s]

Gaps (ex-reports):   1%|          | 73/7343 [00:01<02:02, 59.13it/s]

Gaps (ex-reports):   1%|          | 81/7343 [00:01<02:12, 54.95it/s]

Gaps (ex-reports):   1%|          | 88/7343 [00:01<02:08, 56.68it/s]

Gaps (ex-reports):   1%|▏         | 94/7343 [00:01<02:07, 56.72it/s]

Gaps (ex-reports):   1%|▏         | 100/7343 [00:01<02:23, 50.53it/s]

Gaps (ex-reports):   1%|▏         | 108/7343 [00:01<02:05, 57.66it/s]

Gaps (ex-reports):   2%|▏         | 115/7343 [00:02<02:14, 53.72it/s]

Gaps (ex-reports):   2%|▏         | 125/7343 [00:02<01:55, 62.28it/s]

Gaps (ex-reports):   2%|▏         | 132/7343 [00:02<02:08, 55.95it/s]

Gaps (ex-reports):   2%|▏         | 140/7343 [00:02<02:09, 55.82it/s]

Gaps (ex-reports):   2%|▏         | 146/7343 [00:02<02:09, 55.51it/s]

Gaps (ex-reports):   2%|▏         | 157/7343 [00:02<01:51, 64.22it/s]

Gaps (ex-reports):   2%|▏         | 164/7343 [00:02<01:54, 62.81it/s]

Gaps (ex-reports):   2%|▏         | 171/7343 [00:02<02:00, 59.29it/s]

Gaps (ex-reports):   2%|▏         | 177/7343 [00:03<02:02, 58.28it/s]

Gaps (ex-reports):   2%|▏         | 183/7343 [00:03<02:02, 58.52it/s]

Gaps (ex-reports):   3%|▎         | 192/7343 [00:03<01:52, 63.60it/s]

Gaps (ex-reports):   3%|▎         | 199/7343 [00:03<01:59, 60.00it/s]

Gaps (ex-reports):   3%|▎         | 206/7343 [00:03<02:19, 51.08it/s]

Gaps (ex-reports):   3%|▎         | 213/7343 [00:03<02:12, 53.62it/s]

Gaps (ex-reports):   3%|▎         | 223/7343 [00:03<01:55, 61.89it/s]

Gaps (ex-reports):   3%|▎         | 230/7343 [00:03<01:57, 60.35it/s]

Gaps (ex-reports):   3%|▎         | 237/7343 [00:04<02:13, 53.40it/s]

Gaps (ex-reports):   3%|▎         | 245/7343 [00:04<02:00, 58.84it/s]

Gaps (ex-reports):   3%|▎         | 252/7343 [00:04<02:07, 55.41it/s]

Gaps (ex-reports):   4%|▎         | 261/7343 [00:04<02:05, 56.24it/s]

Gaps (ex-reports):   4%|▎         | 267/7343 [00:04<02:14, 52.57it/s]

Gaps (ex-reports):   4%|▎         | 273/7343 [00:04<02:22, 49.62it/s]

Gaps (ex-reports):   4%|▍         | 283/7343 [00:04<01:58, 59.43it/s]

Gaps (ex-reports):   4%|▍         | 290/7343 [00:05<02:04, 56.76it/s]

Gaps (ex-reports):   4%|▍         | 296/7343 [00:05<02:11, 53.71it/s]

Gaps (ex-reports):   4%|▍         | 302/7343 [00:05<02:10, 53.91it/s]

Gaps (ex-reports):   4%|▍         | 308/7343 [00:05<02:08, 54.60it/s]

Gaps (ex-reports):   4%|▍         | 319/7343 [00:05<01:57, 59.91it/s]

Gaps (ex-reports):   4%|▍         | 326/7343 [00:05<02:05, 55.97it/s]

Gaps (ex-reports):   5%|▍         | 332/7343 [00:05<02:09, 54.34it/s]

Gaps (ex-reports):   5%|▍         | 338/7343 [00:05<02:07, 55.14it/s]

Gaps (ex-reports):   5%|▍         | 347/7343 [00:06<01:52, 62.46it/s]

Gaps (ex-reports):   5%|▍         | 354/7343 [00:06<01:57, 59.29it/s]

Gaps (ex-reports):   5%|▍         | 360/7343 [00:06<02:02, 56.80it/s]

Gaps (ex-reports):   5%|▌         | 370/7343 [00:06<01:49, 63.68it/s]

Gaps (ex-reports):   5%|▌         | 377/7343 [00:06<01:47, 64.69it/s]

Gaps (ex-reports):   5%|▌         | 385/7343 [00:06<01:51, 62.34it/s]

Gaps (ex-reports):   5%|▌         | 392/7343 [00:06<02:07, 54.72it/s]

Gaps (ex-reports):   5%|▌         | 401/7343 [00:07<02:05, 55.14it/s]

Gaps (ex-reports):   6%|▌         | 410/7343 [00:07<01:50, 62.85it/s]

Gaps (ex-reports):   6%|▌         | 417/7343 [00:07<02:25, 47.44it/s]

Gaps (ex-reports):   6%|▌         | 425/7343 [00:07<02:13, 51.89it/s]

Gaps (ex-reports):   6%|▌         | 431/7343 [00:07<02:09, 53.45it/s]

Gaps (ex-reports):   6%|▌         | 437/7343 [00:07<02:06, 54.62it/s]

Gaps (ex-reports):   6%|▌         | 443/7343 [00:07<02:03, 55.75it/s]

Gaps (ex-reports):   6%|▌         | 449/7343 [00:07<02:16, 50.58it/s]

Gaps (ex-reports):   6%|▌         | 457/7343 [00:08<02:05, 54.86it/s]

Gaps (ex-reports):   6%|▋         | 464/7343 [00:08<01:58, 58.15it/s]

Gaps (ex-reports):   6%|▋         | 471/7343 [00:08<02:08, 53.40it/s]

Gaps (ex-reports):   6%|▋         | 477/7343 [00:08<02:11, 52.39it/s]

Gaps (ex-reports):   7%|▋         | 486/7343 [00:08<01:55, 59.55it/s]

Gaps (ex-reports):   7%|▋         | 494/7343 [00:08<01:47, 63.78it/s]

Gaps (ex-reports):   7%|▋         | 501/7343 [00:08<01:51, 61.61it/s]

Gaps (ex-reports):   7%|▋         | 508/7343 [00:08<02:02, 55.68it/s]

Gaps (ex-reports):   7%|▋         | 515/7343 [00:09<01:57, 57.93it/s]

Gaps (ex-reports):   7%|▋         | 523/7343 [00:09<01:47, 63.39it/s]

Gaps (ex-reports):   7%|▋         | 530/7343 [00:09<02:03, 55.32it/s]

Gaps (ex-reports):   7%|▋         | 536/7343 [00:09<02:05, 54.40it/s]

Gaps (ex-reports):   7%|▋         | 546/7343 [00:09<01:43, 65.65it/s]

Gaps (ex-reports):   8%|▊         | 553/7343 [00:09<01:49, 61.87it/s]

Gaps (ex-reports):   8%|▊         | 560/7343 [00:09<01:52, 60.41it/s]

Gaps (ex-reports):   8%|▊         | 567/7343 [00:09<01:47, 62.76it/s]

Gaps (ex-reports):   8%|▊         | 574/7343 [00:10<01:50, 61.24it/s]

Gaps (ex-reports):   8%|▊         | 581/7343 [00:10<01:49, 61.86it/s]

Gaps (ex-reports):   8%|▊         | 589/7343 [00:10<01:55, 58.64it/s]

Gaps (ex-reports):   8%|▊         | 595/7343 [00:10<02:01, 55.36it/s]

Gaps (ex-reports):   8%|▊         | 604/7343 [00:10<01:54, 58.64it/s]

Gaps (ex-reports):   8%|▊         | 611/7343 [00:10<01:52, 60.02it/s]

Gaps (ex-reports):   8%|▊         | 618/7343 [00:10<01:56, 57.53it/s]

Gaps (ex-reports):   9%|▊         | 626/7343 [00:10<01:51, 60.32it/s]

Gaps (ex-reports):   9%|▊         | 633/7343 [00:11<01:52, 59.90it/s]

Gaps (ex-reports):   9%|▊         | 640/7343 [00:11<02:05, 53.29it/s]

Gaps (ex-reports):   9%|▉         | 648/7343 [00:11<01:54, 58.59it/s]

Gaps (ex-reports):   9%|▉         | 655/7343 [00:11<02:08, 52.12it/s]

Gaps (ex-reports):   9%|▉         | 661/7343 [00:11<02:07, 52.35it/s]

Gaps (ex-reports):   9%|▉         | 670/7343 [00:11<02:02, 54.61it/s]

Gaps (ex-reports):   9%|▉         | 679/7343 [00:11<01:51, 59.90it/s]

Gaps (ex-reports):   9%|▉         | 686/7343 [00:11<01:48, 61.33it/s]

Gaps (ex-reports):   9%|▉         | 693/7343 [00:12<01:56, 57.28it/s]

Gaps (ex-reports):  10%|▉         | 699/7343 [00:12<01:56, 57.27it/s]

Gaps (ex-reports):  10%|▉         | 705/7343 [00:12<02:00, 54.90it/s]

Gaps (ex-reports):  10%|▉         | 713/7343 [00:12<01:50, 60.12it/s]

Gaps (ex-reports):  10%|▉         | 720/7343 [00:12<02:00, 54.75it/s]

Gaps (ex-reports):  10%|▉         | 726/7343 [00:12<01:58, 56.01it/s]

Gaps (ex-reports):  10%|▉         | 733/7343 [00:12<02:04, 53.23it/s]

Gaps (ex-reports):  10%|█         | 741/7343 [00:12<01:51, 59.09it/s]

Gaps (ex-reports):  10%|█         | 748/7343 [00:13<02:10, 50.66it/s]

Gaps (ex-reports):  10%|█         | 757/7343 [00:13<01:54, 57.52it/s]

Gaps (ex-reports):  10%|█         | 766/7343 [00:13<01:47, 61.43it/s]

Gaps (ex-reports):  11%|█         | 774/7343 [00:13<01:41, 64.52it/s]

Gaps (ex-reports):  11%|█         | 781/7343 [00:13<02:04, 52.88it/s]

Gaps (ex-reports):  11%|█         | 787/7343 [00:13<02:18, 47.49it/s]

Gaps (ex-reports):  11%|█         | 799/7343 [00:14<01:57, 55.47it/s]

Gaps (ex-reports):  11%|█         | 805/7343 [00:14<02:10, 50.11it/s]

Gaps (ex-reports):  11%|█         | 812/7343 [00:14<02:00, 54.25it/s]

Gaps (ex-reports):  11%|█         | 819/7343 [00:14<02:05, 52.02it/s]

Gaps (ex-reports):  11%|█▏        | 827/7343 [00:14<01:51, 58.31it/s]

Gaps (ex-reports):  11%|█▏        | 834/7343 [00:14<02:00, 53.82it/s]

Gaps (ex-reports):  11%|█▏        | 841/7343 [00:14<01:59, 54.44it/s]

Gaps (ex-reports):  12%|█▏        | 848/7343 [00:14<01:55, 56.19it/s]

Gaps (ex-reports):  12%|█▏        | 854/7343 [00:15<01:58, 54.93it/s]

Gaps (ex-reports):  12%|█▏        | 866/7343 [00:15<01:37, 66.77it/s]

Gaps (ex-reports):  12%|█▏        | 873/7343 [00:15<02:00, 53.80it/s]

Gaps (ex-reports):  12%|█▏        | 879/7343 [00:15<01:57, 55.09it/s]

Gaps (ex-reports):  12%|█▏        | 886/7343 [00:15<01:53, 56.94it/s]

Gaps (ex-reports):  12%|█▏        | 894/7343 [00:15<01:44, 61.61it/s]

Gaps (ex-reports):  12%|█▏        | 901/7343 [00:15<01:41, 63.52it/s]

Gaps (ex-reports):  12%|█▏        | 908/7343 [00:15<01:56, 55.15it/s]

Gaps (ex-reports):  12%|█▏        | 916/7343 [00:16<01:44, 61.24it/s]

Gaps (ex-reports):  13%|█▎        | 924/7343 [00:16<01:39, 64.33it/s]

Gaps (ex-reports):  13%|█▎        | 931/7343 [00:16<01:39, 64.63it/s]

Gaps (ex-reports):  13%|█▎        | 938/7343 [00:16<01:53, 56.62it/s]

Gaps (ex-reports):  13%|█▎        | 944/7343 [00:16<02:02, 52.10it/s]

Gaps (ex-reports):  13%|█▎        | 954/7343 [00:16<02:26, 43.70it/s]

Gaps (ex-reports):  13%|█▎        | 968/7343 [00:16<01:47, 59.26it/s]

Gaps (ex-reports):  13%|█▎        | 975/7343 [00:17<01:54, 55.57it/s]

Gaps (ex-reports):  13%|█▎        | 982/7343 [00:17<02:03, 51.35it/s]

Gaps (ex-reports):  13%|█▎        | 988/7343 [00:17<02:01, 52.12it/s]

Gaps (ex-reports):  14%|█▎        | 994/7343 [00:17<02:06, 50.22it/s]

Gaps (ex-reports):  14%|█▎        | 1000/7343 [00:17<02:09, 49.16it/s]

Gaps (ex-reports):  14%|█▍        | 1010/7343 [00:17<02:02, 51.75it/s]

Gaps (ex-reports):  14%|█▍        | 1016/7343 [00:17<02:01, 52.11it/s]

Gaps (ex-reports):  14%|█▍        | 1027/7343 [00:18<01:41, 61.95it/s]

Gaps (ex-reports):  14%|█▍        | 1034/7343 [00:18<01:47, 58.72it/s]

Gaps (ex-reports):  14%|█▍        | 1043/7343 [00:18<01:51, 56.38it/s]

Gaps (ex-reports):  14%|█▍        | 1049/7343 [00:18<01:51, 56.57it/s]

Gaps (ex-reports):  14%|█▍        | 1055/7343 [00:18<01:52, 55.84it/s]

Gaps (ex-reports):  14%|█▍        | 1062/7343 [00:18<01:45, 59.38it/s]

Gaps (ex-reports):  15%|█▍        | 1071/7343 [00:18<01:39, 63.23it/s]

Gaps (ex-reports):  15%|█▍        | 1078/7343 [00:18<01:37, 64.19it/s]

Gaps (ex-reports):  15%|█▍        | 1085/7343 [00:19<01:46, 58.67it/s]

Gaps (ex-reports):  15%|█▍        | 1095/7343 [00:19<01:34, 66.44it/s]

Gaps (ex-reports):  15%|█▌        | 1102/7343 [00:19<01:51, 56.04it/s]

Gaps (ex-reports):  15%|█▌        | 1112/7343 [00:19<01:37, 64.08it/s]

Gaps (ex-reports):  15%|█▌        | 1119/7343 [00:19<01:37, 64.11it/s]

Gaps (ex-reports):  15%|█▌        | 1127/7343 [00:19<01:42, 60.57it/s]

Gaps (ex-reports):  15%|█▌        | 1135/7343 [00:19<01:38, 62.96it/s]

Gaps (ex-reports):  16%|█▌        | 1144/7343 [00:20<01:35, 64.88it/s]

Gaps (ex-reports):  16%|█▌        | 1151/7343 [00:20<01:48, 56.82it/s]

Gaps (ex-reports):  16%|█▌        | 1157/7343 [00:20<01:50, 55.78it/s]

Gaps (ex-reports):  16%|█▌        | 1163/7343 [00:20<01:49, 56.69it/s]

Gaps (ex-reports):  16%|█▌        | 1170/7343 [00:20<01:44, 59.12it/s]

Gaps (ex-reports):  16%|█▌        | 1177/7343 [00:20<01:39, 61.80it/s]

Gaps (ex-reports):  16%|█▌        | 1184/7343 [00:20<01:40, 61.23it/s]

Gaps (ex-reports):  16%|█▌        | 1191/7343 [00:20<01:38, 62.24it/s]

Gaps (ex-reports):  16%|█▋        | 1198/7343 [00:20<01:37, 62.78it/s]

Gaps (ex-reports):  16%|█▋        | 1206/7343 [00:21<01:34, 64.71it/s]

Gaps (ex-reports):  17%|█▋        | 1214/7343 [00:21<01:29, 68.42it/s]

Gaps (ex-reports):  17%|█▋        | 1221/7343 [00:21<01:41, 60.10it/s]

Gaps (ex-reports):  17%|█▋        | 1228/7343 [00:21<01:51, 54.99it/s]

Gaps (ex-reports):  17%|█▋        | 1237/7343 [00:21<01:38, 62.10it/s]

Gaps (ex-reports):  17%|█▋        | 1244/7343 [00:21<01:43, 59.12it/s]

Gaps (ex-reports):  17%|█▋        | 1252/7343 [00:21<01:39, 61.35it/s]

Gaps (ex-reports):  17%|█▋        | 1259/7343 [00:21<01:37, 62.42it/s]

Gaps (ex-reports):  17%|█▋        | 1266/7343 [00:22<01:52, 53.93it/s]

Gaps (ex-reports):  17%|█▋        | 1276/7343 [00:22<01:34, 64.06it/s]

Gaps (ex-reports):  17%|█▋        | 1283/7343 [00:22<01:40, 60.26it/s]

Gaps (ex-reports):  18%|█▊        | 1292/7343 [00:22<01:30, 66.73it/s]

Gaps (ex-reports):  18%|█▊        | 1299/7343 [00:22<01:40, 60.35it/s]

Gaps (ex-reports):  18%|█▊        | 1306/7343 [00:22<01:49, 55.04it/s]

Gaps (ex-reports):  18%|█▊        | 1312/7343 [00:22<01:49, 55.01it/s]

Gaps (ex-reports):  18%|█▊        | 1318/7343 [00:22<01:50, 54.65it/s]

Gaps (ex-reports):  18%|█▊        | 1326/7343 [00:23<01:39, 60.42it/s]

Gaps (ex-reports):  18%|█▊        | 1333/7343 [00:23<01:54, 52.35it/s]

Gaps (ex-reports):  18%|█▊        | 1339/7343 [00:23<01:52, 53.42it/s]

Gaps (ex-reports):  18%|█▊        | 1346/7343 [00:23<01:47, 55.80it/s]

Gaps (ex-reports):  18%|█▊        | 1352/7343 [00:23<01:46, 56.18it/s]

Gaps (ex-reports):  19%|█▊        | 1359/7343 [00:23<01:43, 57.72it/s]

Gaps (ex-reports):  19%|█▊        | 1365/7343 [00:23<01:52, 52.97it/s]

Gaps (ex-reports):  19%|█▊        | 1372/7343 [00:23<01:45, 56.49it/s]

Gaps (ex-reports):  19%|█▉        | 1379/7343 [00:24<01:41, 58.84it/s]

Gaps (ex-reports):  19%|█▉        | 1385/7343 [00:24<01:40, 59.06it/s]

Gaps (ex-reports):  19%|█▉        | 1391/7343 [00:24<01:43, 57.47it/s]

Gaps (ex-reports):  19%|█▉        | 1398/7343 [00:24<01:45, 56.48it/s]

Gaps (ex-reports):  19%|█▉        | 1404/7343 [00:24<01:43, 57.39it/s]

Gaps (ex-reports):  19%|█▉        | 1411/7343 [00:24<01:46, 55.50it/s]

Gaps (ex-reports):  19%|█▉        | 1417/7343 [00:24<02:13, 44.25it/s]

Gaps (ex-reports):  19%|█▉        | 1425/7343 [00:25<02:13, 44.28it/s]

Gaps (ex-reports):  20%|█▉        | 1433/7343 [00:25<01:53, 51.95it/s]

Gaps (ex-reports):  20%|█▉        | 1439/7343 [00:25<02:00, 48.81it/s]

Gaps (ex-reports):  20%|█▉        | 1450/7343 [00:25<01:34, 62.57it/s]

Gaps (ex-reports):  20%|█▉        | 1457/7343 [00:25<01:56, 50.53it/s]

Gaps (ex-reports):  20%|█▉        | 1467/7343 [00:25<01:42, 57.19it/s]

Gaps (ex-reports):  20%|██        | 1474/7343 [00:25<01:50, 53.10it/s]

Gaps (ex-reports):  20%|██        | 1482/7343 [00:26<01:55, 50.81it/s]

Gaps (ex-reports):  20%|██        | 1488/7343 [00:26<01:53, 51.63it/s]

Gaps (ex-reports):  20%|██        | 1496/7343 [00:26<01:42, 56.80it/s]

Gaps (ex-reports):  20%|██        | 1504/7343 [00:26<01:36, 60.68it/s]

Gaps (ex-reports):  21%|██        | 1511/7343 [00:26<01:48, 53.90it/s]

Gaps (ex-reports):  21%|██        | 1517/7343 [00:26<01:45, 55.08it/s]

Gaps (ex-reports):  21%|██        | 1525/7343 [00:26<01:38, 59.25it/s]

Gaps (ex-reports):  21%|██        | 1532/7343 [00:26<01:41, 57.23it/s]

Gaps (ex-reports):  21%|██        | 1539/7343 [00:26<01:36, 60.13it/s]

Gaps (ex-reports):  21%|██        | 1546/7343 [00:27<01:46, 54.32it/s]

Gaps (ex-reports):  21%|██        | 1552/7343 [00:27<01:48, 53.34it/s]

Gaps (ex-reports):  21%|██        | 1558/7343 [00:27<02:07, 45.53it/s]

Gaps (ex-reports):  21%|██▏       | 1564/7343 [00:27<02:01, 47.74it/s]

Gaps (ex-reports):  21%|██▏       | 1572/7343 [00:27<01:44, 55.48it/s]

Gaps (ex-reports):  21%|██▏       | 1578/7343 [00:27<01:51, 51.69it/s]

Gaps (ex-reports):  22%|██▏       | 1587/7343 [00:27<01:43, 55.82it/s]

Gaps (ex-reports):  22%|██▏       | 1593/7343 [00:28<01:43, 55.61it/s]

Gaps (ex-reports):  22%|██▏       | 1601/7343 [00:28<01:33, 61.31it/s]

Gaps (ex-reports):  22%|██▏       | 1608/7343 [00:28<01:36, 59.32it/s]

Gaps (ex-reports):  22%|██▏       | 1615/7343 [00:28<01:35, 60.27it/s]

Gaps (ex-reports):  22%|██▏       | 1622/7343 [00:28<01:34, 60.58it/s]

Gaps (ex-reports):  22%|██▏       | 1630/7343 [00:28<01:35, 59.70it/s]

Gaps (ex-reports):  22%|██▏       | 1639/7343 [00:28<01:26, 65.92it/s]

Gaps (ex-reports):  22%|██▏       | 1646/7343 [00:28<01:48, 52.48it/s]

Gaps (ex-reports):  23%|██▎       | 1653/7343 [00:29<01:49, 51.80it/s]

Gaps (ex-reports):  23%|██▎       | 1663/7343 [00:29<01:31, 62.25it/s]

Gaps (ex-reports):  23%|██▎       | 1670/7343 [00:29<01:47, 53.00it/s]

Gaps (ex-reports):  23%|██▎       | 1677/7343 [00:29<01:55, 49.11it/s]

Gaps (ex-reports):  23%|██▎       | 1684/7343 [00:29<01:48, 52.35it/s]

Gaps (ex-reports):  23%|██▎       | 1692/7343 [00:29<01:39, 56.82it/s]

Gaps (ex-reports):  23%|██▎       | 1699/7343 [00:29<01:37, 57.66it/s]

Gaps (ex-reports):  23%|██▎       | 1706/7343 [00:30<01:49, 51.34it/s]

Gaps (ex-reports):  23%|██▎       | 1713/7343 [00:30<01:44, 53.78it/s]

Gaps (ex-reports):  23%|██▎       | 1720/7343 [00:30<01:39, 56.33it/s]

Gaps (ex-reports):  24%|██▎       | 1726/7343 [00:30<01:45, 53.09it/s]

Gaps (ex-reports):  24%|██▎       | 1732/7343 [00:30<01:43, 54.35it/s]

Gaps (ex-reports):  24%|██▎       | 1739/7343 [00:30<01:37, 57.47it/s]

Gaps (ex-reports):  24%|██▍       | 1745/7343 [00:30<01:46, 52.79it/s]

Gaps (ex-reports):  24%|██▍       | 1752/7343 [00:30<01:40, 55.70it/s]

Gaps (ex-reports):  24%|██▍       | 1758/7343 [00:30<01:39, 56.04it/s]

Gaps (ex-reports):  24%|██▍       | 1766/7343 [00:31<01:34, 59.09it/s]

Gaps (ex-reports):  24%|██▍       | 1772/7343 [00:31<01:34, 59.06it/s]

Gaps (ex-reports):  24%|██▍       | 1778/7343 [00:31<02:10, 42.74it/s]

Gaps (ex-reports):  24%|██▍       | 1788/7343 [00:31<02:00, 46.06it/s]

Gaps (ex-reports):  24%|██▍       | 1798/7343 [00:31<01:42, 53.85it/s]

Gaps (ex-reports):  25%|██▍       | 1804/7343 [00:31<01:51, 49.57it/s]

Gaps (ex-reports):  25%|██▍       | 1813/7343 [00:32<01:46, 51.91it/s]

Gaps (ex-reports):  25%|██▍       | 1819/7343 [00:32<01:56, 47.48it/s]

Gaps (ex-reports):  25%|██▍       | 1828/7343 [00:32<01:40, 55.12it/s]

Gaps (ex-reports):  25%|██▍       | 1834/7343 [00:32<01:51, 49.30it/s]

Gaps (ex-reports):  25%|██▌       | 1841/7343 [00:32<01:48, 50.83it/s]

Gaps (ex-reports):  25%|██▌       | 1847/7343 [00:32<01:49, 50.36it/s]

Gaps (ex-reports):  25%|██▌       | 1853/7343 [00:32<01:49, 50.18it/s]

Gaps (ex-reports):  25%|██▌       | 1859/7343 [00:32<01:45, 51.95it/s]

Gaps (ex-reports):  25%|██▌       | 1865/7343 [00:33<01:54, 47.69it/s]

Gaps (ex-reports):  25%|██▌       | 1871/7343 [00:33<01:58, 46.36it/s]

Gaps (ex-reports):  26%|██▌       | 1877/7343 [00:33<01:50, 49.38it/s]

Gaps (ex-reports):  26%|██▌       | 1884/7343 [00:33<01:42, 53.42it/s]

Gaps (ex-reports):  26%|██▌       | 1890/7343 [00:33<01:44, 52.26it/s]

Gaps (ex-reports):  26%|██▌       | 1896/7343 [00:33<02:00, 45.13it/s]

Gaps (ex-reports):  26%|██▌       | 1901/7343 [00:33<01:58, 45.83it/s]

Gaps (ex-reports):  26%|██▌       | 1907/7343 [00:33<01:50, 49.22it/s]

Gaps (ex-reports):  26%|██▌       | 1913/7343 [00:34<02:03, 43.85it/s]

Gaps (ex-reports):  26%|██▌       | 1921/7343 [00:34<01:45, 51.59it/s]

Gaps (ex-reports):  26%|██▋       | 1928/7343 [00:34<01:40, 53.94it/s]

Gaps (ex-reports):  26%|██▋       | 1934/7343 [00:34<01:40, 53.81it/s]

Gaps (ex-reports):  26%|██▋       | 1940/7343 [00:34<01:52, 48.10it/s]

Gaps (ex-reports):  27%|██▋       | 1947/7343 [00:34<01:43, 52.14it/s]

Gaps (ex-reports):  27%|██▋       | 1953/7343 [00:34<01:45, 51.30it/s]

Gaps (ex-reports):  27%|██▋       | 1959/7343 [00:35<01:54, 47.06it/s]

Gaps (ex-reports):  27%|██▋       | 1964/7343 [00:35<01:59, 44.91it/s]

Gaps (ex-reports):  27%|██▋       | 1969/7343 [00:35<02:13, 40.27it/s]

Gaps (ex-reports):  27%|██▋       | 1978/7343 [00:35<01:47, 49.83it/s]

Gaps (ex-reports):  27%|██▋       | 1984/7343 [00:35<01:46, 50.51it/s]

Gaps (ex-reports):  27%|██▋       | 1990/7343 [00:35<01:41, 52.65it/s]

Gaps (ex-reports):  27%|██▋       | 1996/7343 [00:35<01:43, 51.82it/s]

Gaps (ex-reports):  27%|██▋       | 2002/7343 [00:35<01:39, 53.65it/s]

Gaps (ex-reports):  27%|██▋       | 2009/7343 [00:35<01:35, 55.96it/s]

Gaps (ex-reports):  27%|██▋       | 2015/7343 [00:36<01:35, 55.50it/s]

Gaps (ex-reports):  28%|██▊       | 2021/7343 [00:36<01:40, 52.87it/s]

Gaps (ex-reports):  28%|██▊       | 2027/7343 [00:36<01:44, 50.78it/s]

Gaps (ex-reports):  28%|██▊       | 2035/7343 [00:36<01:48, 49.01it/s]

Gaps (ex-reports):  28%|██▊       | 2045/7343 [00:36<01:28, 59.78it/s]

Gaps (ex-reports):  28%|██▊       | 2052/7343 [00:36<01:33, 56.29it/s]

Gaps (ex-reports):  28%|██▊       | 2058/7343 [00:36<01:45, 50.29it/s]

Gaps (ex-reports):  28%|██▊       | 2065/7343 [00:37<01:39, 53.05it/s]

Gaps (ex-reports):  28%|██▊       | 2072/7343 [00:37<01:33, 56.22it/s]

Gaps (ex-reports):  28%|██▊       | 2079/7343 [00:37<01:29, 58.94it/s]

Gaps (ex-reports):  28%|██▊       | 2086/7343 [00:37<01:31, 57.61it/s]

Gaps (ex-reports):  28%|██▊       | 2092/7343 [00:37<01:45, 49.65it/s]

Gaps (ex-reports):  29%|██▊       | 2098/7343 [00:37<01:42, 51.01it/s]

Gaps (ex-reports):  29%|██▊       | 2104/7343 [00:37<01:41, 51.67it/s]

Gaps (ex-reports):  29%|██▊       | 2110/7343 [00:37<01:42, 51.04it/s]

Gaps (ex-reports):  29%|██▉       | 2117/7343 [00:38<01:36, 54.25it/s]

Gaps (ex-reports):  29%|██▉       | 2123/7343 [00:38<01:42, 50.69it/s]

Gaps (ex-reports):  29%|██▉       | 2133/7343 [00:38<01:30, 57.71it/s]

Gaps (ex-reports):  29%|██▉       | 2139/7343 [00:38<01:34, 55.35it/s]

Gaps (ex-reports):  29%|██▉       | 2147/7343 [00:38<01:31, 56.54it/s]

Gaps (ex-reports):  29%|██▉       | 2153/7343 [00:38<01:42, 50.64it/s]

Gaps (ex-reports):  29%|██▉       | 2162/7343 [00:38<01:26, 60.04it/s]

Gaps (ex-reports):  30%|██▉       | 2169/7343 [00:38<01:35, 54.12it/s]

Gaps (ex-reports):  30%|██▉       | 2175/7343 [00:39<01:46, 48.39it/s]

Gaps (ex-reports):  30%|██▉       | 2184/7343 [00:39<01:31, 56.47it/s]

Gaps (ex-reports):  30%|██▉       | 2190/7343 [00:39<01:38, 52.37it/s]

Gaps (ex-reports):  30%|██▉       | 2199/7343 [00:39<01:24, 60.65it/s]

Gaps (ex-reports):  30%|███       | 2206/7343 [00:39<01:29, 57.16it/s]

Gaps (ex-reports):  30%|███       | 2213/7343 [00:39<01:31, 56.20it/s]

Gaps (ex-reports):  30%|███       | 2219/7343 [00:39<01:40, 51.18it/s]

Gaps (ex-reports):  30%|███       | 2228/7343 [00:40<01:29, 57.35it/s]

Gaps (ex-reports):  30%|███       | 2234/7343 [00:40<01:42, 49.80it/s]

Gaps (ex-reports):  31%|███       | 2242/7343 [00:40<01:41, 50.20it/s]

Gaps (ex-reports):  31%|███       | 2251/7343 [00:40<01:26, 59.19it/s]

Gaps (ex-reports):  31%|███       | 2258/7343 [00:40<01:34, 53.87it/s]

Gaps (ex-reports):  31%|███       | 2265/7343 [00:40<01:31, 55.64it/s]

Gaps (ex-reports):  31%|███       | 2271/7343 [00:40<01:34, 53.57it/s]

Gaps (ex-reports):  31%|███       | 2280/7343 [00:40<01:21, 62.32it/s]

Gaps (ex-reports):  31%|███       | 2287/7343 [00:41<01:32, 54.71it/s]

Gaps (ex-reports):  31%|███▏      | 2296/7343 [00:41<01:21, 61.62it/s]

Gaps (ex-reports):  31%|███▏      | 2303/7343 [00:41<01:31, 55.09it/s]

Gaps (ex-reports):  31%|███▏      | 2312/7343 [00:41<01:36, 52.14it/s]

Gaps (ex-reports):  32%|███▏      | 2318/7343 [00:41<01:41, 49.55it/s]

Gaps (ex-reports):  32%|███▏      | 2324/7343 [00:41<01:41, 49.26it/s]

Gaps (ex-reports):  32%|███▏      | 2332/7343 [00:41<01:33, 53.37it/s]

Gaps (ex-reports):  32%|███▏      | 2338/7343 [00:42<01:39, 50.40it/s]

Gaps (ex-reports):  32%|███▏      | 2344/7343 [00:42<01:35, 52.55it/s]

Gaps (ex-reports):  32%|███▏      | 2350/7343 [00:42<01:35, 52.31it/s]

Gaps (ex-reports):  32%|███▏      | 2358/7343 [00:42<01:26, 57.78it/s]

Gaps (ex-reports):  32%|███▏      | 2364/7343 [00:42<01:46, 46.88it/s]

Gaps (ex-reports):  32%|███▏      | 2371/7343 [00:42<01:48, 45.92it/s]

Gaps (ex-reports):  32%|███▏      | 2376/7343 [00:42<01:47, 46.12it/s]

Gaps (ex-reports):  32%|███▏      | 2382/7343 [00:43<01:40, 49.12it/s]

Gaps (ex-reports):  33%|███▎      | 2388/7343 [00:43<01:44, 47.47it/s]

Gaps (ex-reports):  33%|███▎      | 2395/7343 [00:43<01:41, 48.81it/s]

Gaps (ex-reports):  33%|███▎      | 2402/7343 [00:43<01:34, 52.50it/s]

Gaps (ex-reports):  33%|███▎      | 2408/7343 [00:43<01:33, 52.55it/s]

Gaps (ex-reports):  33%|███▎      | 2416/7343 [00:43<01:24, 58.45it/s]

Gaps (ex-reports):  33%|███▎      | 2422/7343 [00:43<01:33, 52.44it/s]

Gaps (ex-reports):  33%|███▎      | 2429/7343 [00:43<01:26, 56.73it/s]

Gaps (ex-reports):  33%|███▎      | 2435/7343 [00:43<01:30, 54.16it/s]

Gaps (ex-reports):  33%|███▎      | 2441/7343 [00:44<01:31, 53.66it/s]

Gaps (ex-reports):  33%|███▎      | 2447/7343 [00:44<01:35, 51.39it/s]

Gaps (ex-reports):  33%|███▎      | 2454/7343 [00:44<01:29, 54.34it/s]

Gaps (ex-reports):  34%|███▎      | 2460/7343 [00:44<01:29, 54.83it/s]

Gaps (ex-reports):  34%|███▎      | 2466/7343 [00:44<01:31, 53.59it/s]

Gaps (ex-reports):  34%|███▎      | 2472/7343 [00:44<01:32, 52.44it/s]

Gaps (ex-reports):  34%|███▎      | 2478/7343 [00:44<01:35, 50.79it/s]

Gaps (ex-reports):  34%|███▍      | 2486/7343 [00:44<01:23, 58.44it/s]

Gaps (ex-reports):  34%|███▍      | 2492/7343 [00:45<01:33, 51.80it/s]

Gaps (ex-reports):  34%|███▍      | 2501/7343 [00:45<01:20, 59.88it/s]

Gaps (ex-reports):  34%|███▍      | 2508/7343 [00:45<01:40, 47.89it/s]

Gaps (ex-reports):  34%|███▍      | 2514/7343 [00:45<01:56, 41.33it/s]

Gaps (ex-reports):  34%|███▍      | 2523/7343 [00:45<01:40, 47.81it/s]

Gaps (ex-reports):  34%|███▍      | 2529/7343 [00:45<01:40, 47.84it/s]

Gaps (ex-reports):  35%|███▍      | 2535/7343 [00:45<01:36, 49.74it/s]

Gaps (ex-reports):  35%|███▍      | 2541/7343 [00:46<01:50, 43.61it/s]

Gaps (ex-reports):  35%|███▍      | 2548/7343 [00:46<01:43, 46.38it/s]

Gaps (ex-reports):  35%|███▍      | 2553/7343 [00:46<01:44, 45.79it/s]

Gaps (ex-reports):  35%|███▍      | 2560/7343 [00:46<01:34, 50.57it/s]

Gaps (ex-reports):  35%|███▍      | 2566/7343 [00:46<01:35, 50.28it/s]

Gaps (ex-reports):  35%|███▌      | 2572/7343 [00:46<01:32, 51.39it/s]

Gaps (ex-reports):  35%|███▌      | 2578/7343 [00:46<01:36, 49.19it/s]

Gaps (ex-reports):  35%|███▌      | 2585/7343 [00:46<01:28, 53.93it/s]

Gaps (ex-reports):  35%|███▌      | 2591/7343 [00:47<01:35, 49.87it/s]

Gaps (ex-reports):  35%|███▌      | 2598/7343 [00:47<01:32, 51.49it/s]

Gaps (ex-reports):  35%|███▌      | 2604/7343 [00:47<01:29, 52.76it/s]

Gaps (ex-reports):  36%|███▌      | 2610/7343 [00:47<01:29, 52.97it/s]

Gaps (ex-reports):  36%|███▌      | 2616/7343 [00:47<01:33, 50.32it/s]

Gaps (ex-reports):  36%|███▌      | 2622/7343 [00:47<01:47, 43.75it/s]

Gaps (ex-reports):  36%|███▌      | 2629/7343 [00:48<02:10, 36.15it/s]

Gaps (ex-reports):  36%|███▌      | 2640/7343 [00:48<01:56, 40.47it/s]

Gaps (ex-reports):  36%|███▌      | 2649/7343 [00:48<01:54, 40.97it/s]

Gaps (ex-reports):  36%|███▌      | 2657/7343 [00:48<02:00, 38.79it/s]

Gaps (ex-reports):  36%|███▋      | 2668/7343 [00:48<01:50, 42.46it/s]

Gaps (ex-reports):  36%|███▋      | 2676/7343 [00:49<01:50, 42.14it/s]

Gaps (ex-reports):  37%|███▋      | 2683/7343 [00:49<01:40, 46.46it/s]

Gaps (ex-reports):  37%|███▋      | 2688/7343 [00:49<01:54, 40.78it/s]

Gaps (ex-reports):  37%|███▋      | 2693/7343 [00:49<01:56, 39.87it/s]

Gaps (ex-reports):  37%|███▋      | 2700/7343 [00:49<01:49, 42.41it/s]

Gaps (ex-reports):  37%|███▋      | 2705/7343 [00:49<01:59, 38.80it/s]

Gaps (ex-reports):  37%|███▋      | 2709/7343 [00:49<02:00, 38.45it/s]

Gaps (ex-reports):  37%|███▋      | 2714/7343 [00:50<01:54, 40.39it/s]

Gaps (ex-reports):  37%|███▋      | 2720/7343 [00:50<01:44, 44.17it/s]

Gaps (ex-reports):  37%|███▋      | 2725/7343 [00:50<01:54, 40.17it/s]

Gaps (ex-reports):  37%|███▋      | 2732/7343 [00:50<01:49, 41.97it/s]

Gaps (ex-reports):  37%|███▋      | 2738/7343 [00:50<01:42, 44.94it/s]

Gaps (ex-reports):  37%|███▋      | 2745/7343 [00:50<01:42, 44.84it/s]

Gaps (ex-reports):  37%|███▋      | 2751/7343 [00:50<01:35, 48.04it/s]

Gaps (ex-reports):  38%|███▊      | 2757/7343 [00:50<01:37, 47.27it/s]

Gaps (ex-reports):  38%|███▊      | 2763/7343 [00:51<01:45, 43.27it/s]

Gaps (ex-reports):  38%|███▊      | 2769/7343 [00:51<01:37, 47.10it/s]

Gaps (ex-reports):  38%|███▊      | 2775/7343 [00:51<01:47, 42.45it/s]

Gaps (ex-reports):  38%|███▊      | 2782/7343 [00:51<01:42, 44.53it/s]

Gaps (ex-reports):  38%|███▊      | 2789/7343 [00:51<01:39, 45.75it/s]

Gaps (ex-reports):  38%|███▊      | 2794/7343 [00:51<01:41, 44.69it/s]

Gaps (ex-reports):  38%|███▊      | 2799/7343 [00:51<01:45, 42.89it/s]

Gaps (ex-reports):  38%|███▊      | 2807/7343 [00:52<01:27, 51.71it/s]

Gaps (ex-reports):  38%|███▊      | 2813/7343 [00:52<01:45, 43.04it/s]

Gaps (ex-reports):  38%|███▊      | 2820/7343 [00:52<01:37, 46.28it/s]

Gaps (ex-reports):  38%|███▊      | 2827/7343 [00:52<01:32, 48.85it/s]

Gaps (ex-reports):  39%|███▊      | 2834/7343 [00:52<01:29, 50.25it/s]

Gaps (ex-reports):  39%|███▊      | 2840/7343 [00:52<01:31, 49.15it/s]

Gaps (ex-reports):  39%|███▉      | 2847/7343 [00:52<01:25, 52.62it/s]

Gaps (ex-reports):  39%|███▉      | 2853/7343 [00:52<01:25, 52.43it/s]

Gaps (ex-reports):  39%|███▉      | 2859/7343 [00:53<01:39, 44.93it/s]

Gaps (ex-reports):  39%|███▉      | 2866/7343 [00:53<01:31, 48.93it/s]

Gaps (ex-reports):  39%|███▉      | 2872/7343 [00:53<01:47, 41.55it/s]

Gaps (ex-reports):  39%|███▉      | 2879/7343 [00:53<01:35, 46.97it/s]

Gaps (ex-reports):  39%|███▉      | 2885/7343 [00:53<01:36, 46.07it/s]

Gaps (ex-reports):  39%|███▉      | 2891/7343 [00:53<01:48, 40.89it/s]

Gaps (ex-reports):  39%|███▉      | 2899/7343 [00:54<01:31, 48.52it/s]

Gaps (ex-reports):  40%|███▉      | 2905/7343 [00:54<01:33, 47.67it/s]

Gaps (ex-reports):  40%|███▉      | 2912/7343 [00:54<01:25, 51.78it/s]

Gaps (ex-reports):  40%|███▉      | 2918/7343 [00:54<01:31, 48.11it/s]

Gaps (ex-reports):  40%|███▉      | 2924/7343 [00:54<01:34, 46.82it/s]

Gaps (ex-reports):  40%|███▉      | 2930/7343 [00:54<01:34, 46.46it/s]

Gaps (ex-reports):  40%|███▉      | 2936/7343 [00:54<01:28, 49.72it/s]

Gaps (ex-reports):  40%|████      | 2942/7343 [00:54<01:26, 50.83it/s]

Gaps (ex-reports):  40%|████      | 2948/7343 [00:55<01:42, 42.70it/s]

Gaps (ex-reports):  40%|████      | 2957/7343 [00:55<01:35, 45.94it/s]

Gaps (ex-reports):  40%|████      | 2962/7343 [00:55<01:34, 46.36it/s]

Gaps (ex-reports):  40%|████      | 2969/7343 [00:55<01:24, 51.85it/s]

Gaps (ex-reports):  41%|████      | 2975/7343 [00:55<01:38, 44.44it/s]

Gaps (ex-reports):  41%|████      | 2982/7343 [00:55<01:27, 49.66it/s]

Gaps (ex-reports):  41%|████      | 2988/7343 [00:55<01:31, 47.36it/s]

Gaps (ex-reports):  41%|████      | 2995/7343 [00:56<01:24, 51.40it/s]

Gaps (ex-reports):  41%|████      | 3001/7343 [00:56<01:32, 47.08it/s]

Gaps (ex-reports):  41%|████      | 3007/7343 [00:56<01:27, 49.72it/s]

Gaps (ex-reports):  41%|████      | 3013/7343 [00:56<01:35, 45.21it/s]

Gaps (ex-reports):  41%|████      | 3023/7343 [00:56<01:25, 50.23it/s]

Gaps (ex-reports):  41%|████▏     | 3029/7343 [00:56<01:22, 52.03it/s]

Gaps (ex-reports):  41%|████▏     | 3036/7343 [00:56<01:19, 54.10it/s]

Gaps (ex-reports):  41%|████▏     | 3042/7343 [00:56<01:24, 51.03it/s]

Gaps (ex-reports):  42%|████▏     | 3049/7343 [00:57<01:19, 54.04it/s]

Gaps (ex-reports):  42%|████▏     | 3055/7343 [00:57<01:27, 49.17it/s]

Gaps (ex-reports):  42%|████▏     | 3063/7343 [00:57<01:17, 55.46it/s]

Gaps (ex-reports):  42%|████▏     | 3069/7343 [00:57<01:19, 53.45it/s]

Gaps (ex-reports):  42%|████▏     | 3077/7343 [00:57<01:11, 59.67it/s]

Gaps (ex-reports):  42%|████▏     | 3084/7343 [00:57<01:22, 51.85it/s]

Gaps (ex-reports):  42%|████▏     | 3091/7343 [00:57<01:17, 54.54it/s]

Gaps (ex-reports):  42%|████▏     | 3097/7343 [00:57<01:16, 55.75it/s]

Gaps (ex-reports):  42%|████▏     | 3104/7343 [00:58<01:17, 54.39it/s]

Gaps (ex-reports):  42%|████▏     | 3110/7343 [00:58<01:24, 49.89it/s]

Gaps (ex-reports):  42%|████▏     | 3118/7343 [00:58<01:19, 53.08it/s]

Gaps (ex-reports):  43%|████▎     | 3124/7343 [00:58<01:17, 54.25it/s]

Gaps (ex-reports):  43%|████▎     | 3130/7343 [00:58<01:16, 55.12it/s]

Gaps (ex-reports):  43%|████▎     | 3136/7343 [00:58<01:15, 55.39it/s]

Gaps (ex-reports):  43%|████▎     | 3142/7343 [00:58<01:22, 50.65it/s]

Gaps (ex-reports):  43%|████▎     | 3150/7343 [00:58<01:14, 56.43it/s]

Gaps (ex-reports):  43%|████▎     | 3156/7343 [00:59<01:29, 46.83it/s]

Gaps (ex-reports):  43%|████▎     | 3163/7343 [00:59<01:23, 50.13it/s]

Gaps (ex-reports):  43%|████▎     | 3169/7343 [00:59<01:20, 51.71it/s]

Gaps (ex-reports):  43%|████▎     | 3176/7343 [00:59<01:15, 54.83it/s]

Gaps (ex-reports):  43%|████▎     | 3182/7343 [00:59<01:26, 47.95it/s]

Gaps (ex-reports):  43%|████▎     | 3191/7343 [00:59<01:16, 54.53it/s]

Gaps (ex-reports):  44%|████▎     | 3197/7343 [00:59<01:19, 52.26it/s]

Gaps (ex-reports):  44%|████▎     | 3203/7343 [01:00<01:21, 50.53it/s]

Gaps (ex-reports):  44%|████▎     | 3209/7343 [01:00<01:21, 50.55it/s]

Gaps (ex-reports):  44%|████▍     | 3215/7343 [01:00<01:27, 47.06it/s]

Gaps (ex-reports):  44%|████▍     | 3221/7343 [01:00<01:22, 50.06it/s]

Gaps (ex-reports):  44%|████▍     | 3229/7343 [01:00<01:14, 54.92it/s]

Gaps (ex-reports):  44%|████▍     | 3235/7343 [01:00<01:26, 47.64it/s]

Gaps (ex-reports):  44%|████▍     | 3244/7343 [01:00<01:16, 53.65it/s]

Gaps (ex-reports):  44%|████▍     | 3250/7343 [01:00<01:18, 52.10it/s]

Gaps (ex-reports):  44%|████▍     | 3257/7343 [01:01<01:12, 56.10it/s]

Gaps (ex-reports):  44%|████▍     | 3263/7343 [01:01<01:17, 52.61it/s]

Gaps (ex-reports):  45%|████▍     | 3270/7343 [01:01<01:13, 55.10it/s]

Gaps (ex-reports):  45%|████▍     | 3276/7343 [01:01<01:16, 53.01it/s]

Gaps (ex-reports):  45%|████▍     | 3282/7343 [01:01<01:19, 50.84it/s]

Gaps (ex-reports):  45%|████▍     | 3289/7343 [01:01<01:14, 54.70it/s]

Gaps (ex-reports):  45%|████▍     | 3295/7343 [01:01<01:14, 54.51it/s]

Gaps (ex-reports):  45%|████▍     | 3304/7343 [01:01<01:06, 60.91it/s]

Gaps (ex-reports):  45%|████▌     | 3311/7343 [01:02<01:13, 54.69it/s]

Gaps (ex-reports):  45%|████▌     | 3318/7343 [01:02<01:10, 56.90it/s]

Gaps (ex-reports):  45%|████▌     | 3324/7343 [01:02<01:16, 52.60it/s]

Gaps (ex-reports):  45%|████▌     | 3331/7343 [01:02<01:14, 54.03it/s]

Gaps (ex-reports):  45%|████▌     | 3338/7343 [01:02<01:10, 57.12it/s]

Gaps (ex-reports):  46%|████▌     | 3344/7343 [01:02<01:10, 56.90it/s]

Gaps (ex-reports):  46%|████▌     | 3350/7343 [01:02<01:10, 56.52it/s]

Gaps (ex-reports):  46%|████▌     | 3356/7343 [01:02<01:16, 51.87it/s]

Gaps (ex-reports):  46%|████▌     | 3364/7343 [01:02<01:11, 55.87it/s]

Gaps (ex-reports):  46%|████▌     | 3371/7343 [01:03<01:08, 58.20it/s]

Gaps (ex-reports):  46%|████▌     | 3377/7343 [01:03<01:08, 57.86it/s]

Gaps (ex-reports):  46%|████▌     | 3383/7343 [01:03<01:11, 55.17it/s]

Gaps (ex-reports):  46%|████▌     | 3389/7343 [01:03<01:13, 54.04it/s]

Gaps (ex-reports):  46%|████▌     | 3396/7343 [01:03<01:08, 57.84it/s]

Gaps (ex-reports):  46%|████▋     | 3402/7343 [01:03<01:14, 53.03it/s]

Gaps (ex-reports):  46%|████▋     | 3409/7343 [01:03<01:17, 50.63it/s]

Gaps (ex-reports):  47%|████▋     | 3418/7343 [01:03<01:07, 58.30it/s]

Gaps (ex-reports):  47%|████▋     | 3424/7343 [01:04<01:12, 54.15it/s]

Gaps (ex-reports):  47%|████▋     | 3430/7343 [01:04<01:16, 51.48it/s]

Gaps (ex-reports):  47%|████▋     | 3436/7343 [01:04<01:14, 52.20it/s]

Gaps (ex-reports):  47%|████▋     | 3442/7343 [01:04<01:14, 52.16it/s]

Gaps (ex-reports):  47%|████▋     | 3449/7343 [01:04<01:14, 52.17it/s]

Gaps (ex-reports):  47%|████▋     | 3455/7343 [01:04<01:20, 48.26it/s]

Gaps (ex-reports):  47%|████▋     | 3460/7343 [01:04<01:28, 43.77it/s]

Gaps (ex-reports):  47%|████▋     | 3466/7343 [01:04<01:23, 46.70it/s]

Gaps (ex-reports):  47%|████▋     | 3475/7343 [01:05<01:13, 52.38it/s]

Gaps (ex-reports):  47%|████▋     | 3481/7343 [01:05<01:16, 50.47it/s]

Gaps (ex-reports):  47%|████▋     | 3487/7343 [01:05<01:20, 47.93it/s]

Gaps (ex-reports):  48%|████▊     | 3493/7343 [01:05<01:16, 50.28it/s]

Gaps (ex-reports):  48%|████▊     | 3500/7343 [01:05<01:11, 53.73it/s]

Gaps (ex-reports):  48%|████▊     | 3506/7343 [01:05<01:12, 53.16it/s]

Gaps (ex-reports):  48%|████▊     | 3513/7343 [01:05<01:09, 55.39it/s]

Gaps (ex-reports):  48%|████▊     | 3521/7343 [01:06<01:15, 50.39it/s]

Gaps (ex-reports):  48%|████▊     | 3532/7343 [01:06<00:59, 64.34it/s]

Gaps (ex-reports):  48%|████▊     | 3539/7343 [01:06<01:10, 53.88it/s]

Gaps (ex-reports):  48%|████▊     | 3548/7343 [01:06<01:01, 61.45it/s]

Gaps (ex-reports):  48%|████▊     | 3555/7343 [01:06<01:04, 58.67it/s]

Gaps (ex-reports):  49%|████▊     | 3562/7343 [01:06<01:06, 56.58it/s]

Gaps (ex-reports):  49%|████▊     | 3568/7343 [01:06<01:05, 57.28it/s]

Gaps (ex-reports):  49%|████▊     | 3574/7343 [01:06<01:05, 57.84it/s]

Gaps (ex-reports):  49%|████▉     | 3580/7343 [01:06<01:06, 56.68it/s]

Gaps (ex-reports):  49%|████▉     | 3586/7343 [01:07<01:09, 54.12it/s]

Gaps (ex-reports):  49%|████▉     | 3595/7343 [01:07<01:00, 61.52it/s]

Gaps (ex-reports):  49%|████▉     | 3602/7343 [01:07<01:04, 57.71it/s]

Gaps (ex-reports):  49%|████▉     | 3608/7343 [01:07<01:14, 49.85it/s]

Gaps (ex-reports):  49%|████▉     | 3620/7343 [01:07<00:59, 62.96it/s]

Gaps (ex-reports):  49%|████▉     | 3627/7343 [01:07<01:04, 57.28it/s]

Gaps (ex-reports):  50%|████▉     | 3635/7343 [01:07<01:09, 53.16it/s]

Gaps (ex-reports):  50%|████▉     | 3643/7343 [01:08<01:07, 55.12it/s]

Gaps (ex-reports):  50%|████▉     | 3651/7343 [01:08<01:03, 58.00it/s]

Gaps (ex-reports):  50%|████▉     | 3659/7343 [01:08<00:58, 62.96it/s]

Gaps (ex-reports):  50%|████▉     | 3666/7343 [01:08<01:05, 56.06it/s]

Gaps (ex-reports):  50%|█████     | 3674/7343 [01:08<01:00, 60.98it/s]

Gaps (ex-reports):  50%|█████     | 3682/7343 [01:08<01:02, 58.68it/s]

Gaps (ex-reports):  50%|█████     | 3689/7343 [01:08<00:59, 60.96it/s]

Gaps (ex-reports):  50%|█████     | 3696/7343 [01:08<01:00, 59.99it/s]

Gaps (ex-reports):  50%|█████     | 3703/7343 [01:09<00:58, 62.40it/s]

Gaps (ex-reports):  51%|█████     | 3710/7343 [01:09<00:58, 61.73it/s]

Gaps (ex-reports):  51%|█████     | 3717/7343 [01:09<01:03, 56.79it/s]

Gaps (ex-reports):  51%|█████     | 3723/7343 [01:09<01:03, 57.44it/s]

Gaps (ex-reports):  51%|█████     | 3730/7343 [01:09<01:03, 56.46it/s]

Gaps (ex-reports):  51%|█████     | 3736/7343 [01:09<01:04, 55.74it/s]

Gaps (ex-reports):  51%|█████     | 3744/7343 [01:09<00:59, 60.91it/s]

Gaps (ex-reports):  51%|█████     | 3752/7343 [01:09<00:57, 62.10it/s]

Gaps (ex-reports):  51%|█████     | 3759/7343 [01:10<00:59, 60.60it/s]

Gaps (ex-reports):  51%|█████▏    | 3766/7343 [01:10<01:01, 58.30it/s]

Gaps (ex-reports):  51%|█████▏    | 3774/7343 [01:10<00:57, 62.38it/s]

Gaps (ex-reports):  51%|█████▏    | 3781/7343 [01:10<01:03, 56.13it/s]

Gaps (ex-reports):  52%|█████▏    | 3787/7343 [01:10<01:03, 56.29it/s]

Gaps (ex-reports):  52%|█████▏    | 3793/7343 [01:10<01:05, 54.37it/s]

Gaps (ex-reports):  52%|█████▏    | 3799/7343 [01:10<01:08, 51.72it/s]

Gaps (ex-reports):  52%|█████▏    | 3807/7343 [01:10<01:08, 51.36it/s]

Gaps (ex-reports):  52%|█████▏    | 3813/7343 [01:11<01:08, 51.24it/s]

Gaps (ex-reports):  52%|█████▏    | 3820/7343 [01:11<01:05, 54.14it/s]

Gaps (ex-reports):  52%|█████▏    | 3826/7343 [01:11<01:08, 50.99it/s]

Gaps (ex-reports):  52%|█████▏    | 3833/7343 [01:11<01:07, 52.19it/s]

Gaps (ex-reports):  52%|█████▏    | 3841/7343 [01:11<01:00, 57.51it/s]

Gaps (ex-reports):  52%|█████▏    | 3847/7343 [01:11<01:06, 52.48it/s]

Gaps (ex-reports):  53%|█████▎    | 3857/7343 [01:11<00:56, 62.18it/s]

Gaps (ex-reports):  53%|█████▎    | 3864/7343 [01:11<01:01, 56.13it/s]

Gaps (ex-reports):  53%|█████▎    | 3870/7343 [01:12<01:08, 50.66it/s]

Gaps (ex-reports):  53%|█████▎    | 3881/7343 [01:12<00:55, 62.10it/s]

Gaps (ex-reports):  53%|█████▎    | 3888/7343 [01:12<01:03, 54.42it/s]

Gaps (ex-reports):  53%|█████▎    | 3897/7343 [01:12<00:57, 60.19it/s]

Gaps (ex-reports):  53%|█████▎    | 3904/7343 [01:12<01:13, 47.10it/s]

Gaps (ex-reports):  53%|█████▎    | 3916/7343 [01:12<00:56, 60.92it/s]

Gaps (ex-reports):  53%|█████▎    | 3924/7343 [01:13<01:07, 50.35it/s]

Gaps (ex-reports):  54%|█████▎    | 3931/7343 [01:13<01:07, 50.87it/s]

Gaps (ex-reports):  54%|█████▎    | 3937/7343 [01:13<01:05, 51.98it/s]

Gaps (ex-reports):  54%|█████▎    | 3944/7343 [01:13<01:00, 55.91it/s]

Gaps (ex-reports):  54%|█████▍    | 3951/7343 [01:13<01:01, 55.04it/s]

Gaps (ex-reports):  54%|█████▍    | 3957/7343 [01:13<01:01, 55.34it/s]

Gaps (ex-reports):  54%|█████▍    | 3965/7343 [01:13<00:55, 61.04it/s]

Gaps (ex-reports):  54%|█████▍    | 3972/7343 [01:13<01:00, 55.96it/s]

Gaps (ex-reports):  54%|█████▍    | 3979/7343 [01:14<00:59, 56.26it/s]

Gaps (ex-reports):  54%|█████▍    | 3986/7343 [01:14<00:58, 56.93it/s]

Gaps (ex-reports):  54%|█████▍    | 3992/7343 [01:14<00:59, 56.26it/s]

Gaps (ex-reports):  54%|█████▍    | 3999/7343 [01:14<00:57, 58.65it/s]

Gaps (ex-reports):  55%|█████▍    | 4005/7343 [01:14<01:00, 55.28it/s]

Gaps (ex-reports):  55%|█████▍    | 4011/7343 [01:14<00:59, 56.11it/s]

Gaps (ex-reports):  55%|█████▍    | 4018/7343 [01:14<00:56, 58.44it/s]

Gaps (ex-reports):  55%|█████▍    | 4025/7343 [01:14<00:54, 60.63it/s]

Gaps (ex-reports):  55%|█████▍    | 4032/7343 [01:14<00:53, 61.92it/s]

Gaps (ex-reports):  55%|█████▌    | 4039/7343 [01:15<00:56, 58.75it/s]

Gaps (ex-reports):  55%|█████▌    | 4046/7343 [01:15<00:54, 60.70it/s]

Gaps (ex-reports):  55%|█████▌    | 4053/7343 [01:15<00:53, 61.13it/s]

Gaps (ex-reports):  55%|█████▌    | 4060/7343 [01:15<00:55, 58.93it/s]

Gaps (ex-reports):  55%|█████▌    | 4069/7343 [01:15<00:49, 65.51it/s]

Gaps (ex-reports):  56%|█████▌    | 4076/7343 [01:15<01:06, 49.41it/s]

Gaps (ex-reports):  56%|█████▌    | 4084/7343 [01:15<00:58, 55.63it/s]

Gaps (ex-reports):  56%|█████▌    | 4092/7343 [01:15<00:55, 58.92it/s]

Gaps (ex-reports):  56%|█████▌    | 4101/7343 [01:16<00:50, 63.64it/s]

Gaps (ex-reports):  56%|█████▌    | 4108/7343 [01:16<00:57, 56.43it/s]

Gaps (ex-reports):  56%|█████▌    | 4117/7343 [01:16<00:57, 55.74it/s]

Gaps (ex-reports):  56%|█████▌    | 4125/7343 [01:16<00:52, 60.74it/s]

Gaps (ex-reports):  56%|█████▋    | 4133/7343 [01:16<00:49, 64.55it/s]

Gaps (ex-reports):  56%|█████▋    | 4140/7343 [01:16<00:59, 53.71it/s]

Gaps (ex-reports):  56%|█████▋    | 4146/7343 [01:16<00:58, 55.05it/s]

Gaps (ex-reports):  57%|█████▋    | 4152/7343 [01:17<01:03, 50.37it/s]

Gaps (ex-reports):  57%|█████▋    | 4164/7343 [01:17<00:52, 60.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4172/7343 [01:17<00:53, 59.45it/s]

Gaps (ex-reports):  57%|█████▋    | 4180/7343 [01:17<00:51, 60.85it/s]

Gaps (ex-reports):  57%|█████▋    | 4187/7343 [01:17<00:59, 53.07it/s]

Gaps (ex-reports):  57%|█████▋    | 4194/7343 [01:17<00:59, 53.22it/s]

Gaps (ex-reports):  57%|█████▋    | 4200/7343 [01:17<01:00, 51.78it/s]

Gaps (ex-reports):  57%|█████▋    | 4207/7343 [01:18<01:02, 50.15it/s]

Gaps (ex-reports):  57%|█████▋    | 4214/7343 [01:18<01:01, 50.48it/s]

Gaps (ex-reports):  58%|█████▊    | 4223/7343 [01:18<00:52, 59.50it/s]

Gaps (ex-reports):  58%|█████▊    | 4230/7343 [01:18<00:58, 53.11it/s]

Gaps (ex-reports):  58%|█████▊    | 4237/7343 [01:18<00:56, 54.79it/s]

Gaps (ex-reports):  58%|█████▊    | 4246/7343 [01:18<00:50, 61.36it/s]

Gaps (ex-reports):  58%|█████▊    | 4253/7343 [01:18<00:58, 52.47it/s]

Gaps (ex-reports):  58%|█████▊    | 4262/7343 [01:19<00:51, 59.28it/s]

Gaps (ex-reports):  58%|█████▊    | 4269/7343 [01:19<00:54, 55.94it/s]

Gaps (ex-reports):  58%|█████▊    | 4275/7343 [01:19<00:57, 52.94it/s]

Gaps (ex-reports):  58%|█████▊    | 4284/7343 [01:19<00:55, 55.02it/s]

Gaps (ex-reports):  58%|█████▊    | 4290/7343 [01:19<00:56, 54.37it/s]

Gaps (ex-reports):  59%|█████▊    | 4298/7343 [01:19<00:54, 55.83it/s]

Gaps (ex-reports):  59%|█████▊    | 4304/7343 [01:19<01:03, 48.23it/s]

Gaps (ex-reports):  59%|█████▊    | 4314/7343 [01:19<00:54, 56.06it/s]

Gaps (ex-reports):  59%|█████▉    | 4320/7343 [01:20<00:55, 54.31it/s]

Gaps (ex-reports):  59%|█████▉    | 4329/7343 [01:20<00:57, 52.37it/s]

Gaps (ex-reports):  59%|█████▉    | 4335/7343 [01:20<00:55, 53.86it/s]

Gaps (ex-reports):  59%|█████▉    | 4345/7343 [01:20<00:47, 62.70it/s]

Gaps (ex-reports):  59%|█████▉    | 4352/7343 [01:20<00:49, 60.78it/s]

Gaps (ex-reports):  59%|█████▉    | 4359/7343 [01:20<00:49, 60.11it/s]

Gaps (ex-reports):  59%|█████▉    | 4366/7343 [01:20<00:53, 55.95it/s]

Gaps (ex-reports):  60%|█████▉    | 4373/7343 [01:21<00:52, 56.73it/s]

Gaps (ex-reports):  60%|█████▉    | 4379/7343 [01:21<00:51, 57.41it/s]

Gaps (ex-reports):  60%|█████▉    | 4385/7343 [01:21<00:55, 53.75it/s]

Gaps (ex-reports):  60%|█████▉    | 4393/7343 [01:21<00:53, 54.68it/s]

Gaps (ex-reports):  60%|█████▉    | 4399/7343 [01:21<00:57, 50.96it/s]

Gaps (ex-reports):  60%|█████▉    | 4405/7343 [01:21<00:56, 52.10it/s]

Gaps (ex-reports):  60%|██████    | 4413/7343 [01:21<00:50, 57.81it/s]

Gaps (ex-reports):  60%|██████    | 4419/7343 [01:21<00:56, 51.64it/s]

Gaps (ex-reports):  60%|██████    | 4428/7343 [01:21<00:47, 61.10it/s]

Gaps (ex-reports):  60%|██████    | 4435/7343 [01:22<00:52, 54.98it/s]

Gaps (ex-reports):  60%|██████    | 4441/7343 [01:22<00:53, 54.64it/s]

Gaps (ex-reports):  61%|██████    | 4448/7343 [01:22<00:50, 57.77it/s]

Gaps (ex-reports):  61%|██████    | 4454/7343 [01:22<00:51, 55.69it/s]

Gaps (ex-reports):  61%|██████    | 4460/7343 [01:22<00:59, 48.37it/s]

Gaps (ex-reports):  61%|██████    | 4469/7343 [01:22<00:51, 55.43it/s]

Gaps (ex-reports):  61%|██████    | 4475/7343 [01:22<00:52, 54.18it/s]

Gaps (ex-reports):  61%|██████    | 4482/7343 [01:23<00:50, 56.64it/s]

Gaps (ex-reports):  61%|██████    | 4490/7343 [01:23<00:45, 62.31it/s]

Gaps (ex-reports):  61%|██████    | 4497/7343 [01:23<00:51, 54.92it/s]

Gaps (ex-reports):  61%|██████▏   | 4507/7343 [01:23<00:49, 57.61it/s]

Gaps (ex-reports):  62%|██████▏   | 4516/7343 [01:23<00:44, 63.35it/s]

Gaps (ex-reports):  62%|██████▏   | 4524/7343 [01:23<00:46, 60.37it/s]

Gaps (ex-reports):  62%|██████▏   | 4531/7343 [01:23<00:48, 57.84it/s]

Gaps (ex-reports):  62%|██████▏   | 4537/7343 [01:23<00:51, 54.86it/s]

Gaps (ex-reports):  62%|██████▏   | 4543/7343 [01:24<00:50, 55.29it/s]

Gaps (ex-reports):  62%|██████▏   | 4550/7343 [01:24<00:47, 58.21it/s]

Gaps (ex-reports):  62%|██████▏   | 4557/7343 [01:24<00:47, 58.40it/s]

Gaps (ex-reports):  62%|██████▏   | 4563/7343 [01:24<00:47, 58.48it/s]

Gaps (ex-reports):  62%|██████▏   | 4572/7343 [01:24<00:44, 62.71it/s]

Gaps (ex-reports):  62%|██████▏   | 4580/7343 [01:24<00:42, 64.67it/s]

Gaps (ex-reports):  62%|██████▏   | 4588/7343 [01:24<00:41, 66.26it/s]

Gaps (ex-reports):  63%|██████▎   | 4595/7343 [01:24<00:50, 54.45it/s]

Gaps (ex-reports):  63%|██████▎   | 4603/7343 [01:25<00:49, 55.10it/s]

Gaps (ex-reports):  63%|██████▎   | 4611/7343 [01:25<00:47, 57.92it/s]

Gaps (ex-reports):  63%|██████▎   | 4617/7343 [01:25<00:54, 50.24it/s]

Gaps (ex-reports):  63%|██████▎   | 4623/7343 [01:25<00:55, 49.36it/s]

Gaps (ex-reports):  63%|██████▎   | 4632/7343 [01:25<00:46, 58.54it/s]

Gaps (ex-reports):  63%|██████▎   | 4639/7343 [01:25<00:50, 53.97it/s]

Gaps (ex-reports):  63%|██████▎   | 4645/7343 [01:25<00:51, 52.73it/s]

Gaps (ex-reports):  63%|██████▎   | 4656/7343 [01:25<00:43, 62.17it/s]

Gaps (ex-reports):  64%|██████▎   | 4663/7343 [01:26<00:50, 53.47it/s]

Gaps (ex-reports):  64%|██████▎   | 4669/7343 [01:26<00:51, 52.12it/s]

Gaps (ex-reports):  64%|██████▎   | 4679/7343 [01:26<00:43, 61.15it/s]

Gaps (ex-reports):  64%|██████▍   | 4686/7343 [01:26<00:43, 61.57it/s]

Gaps (ex-reports):  64%|██████▍   | 4693/7343 [01:26<00:41, 63.43it/s]

Gaps (ex-reports):  64%|██████▍   | 4701/7343 [01:26<00:41, 63.87it/s]

Gaps (ex-reports):  64%|██████▍   | 4708/7343 [01:26<00:46, 56.66it/s]

Gaps (ex-reports):  64%|██████▍   | 4717/7343 [01:27<00:40, 64.27it/s]

Gaps (ex-reports):  64%|██████▍   | 4724/7343 [01:27<00:41, 63.59it/s]

Gaps (ex-reports):  64%|██████▍   | 4731/7343 [01:27<00:52, 49.44it/s]

Gaps (ex-reports):  65%|██████▍   | 4738/7343 [01:27<00:48, 53.97it/s]

Gaps (ex-reports):  65%|██████▍   | 4746/7343 [01:27<00:45, 56.93it/s]

Gaps (ex-reports):  65%|██████▍   | 4753/7343 [01:27<00:50, 50.97it/s]

Gaps (ex-reports):  65%|██████▍   | 4761/7343 [01:27<00:47, 54.80it/s]

Gaps (ex-reports):  65%|██████▍   | 4767/7343 [01:28<00:51, 50.43it/s]

Gaps (ex-reports):  65%|██████▌   | 4775/7343 [01:28<00:46, 54.70it/s]

Gaps (ex-reports):  65%|██████▌   | 4784/7343 [01:28<00:42, 60.51it/s]

Gaps (ex-reports):  65%|██████▌   | 4791/7343 [01:28<00:43, 58.79it/s]

Gaps (ex-reports):  65%|██████▌   | 4798/7343 [01:28<00:42, 60.52it/s]

Gaps (ex-reports):  65%|██████▌   | 4805/7343 [01:28<00:50, 50.59it/s]

Gaps (ex-reports):  66%|██████▌   | 4811/7343 [01:28<00:52, 48.63it/s]

Gaps (ex-reports):  66%|██████▌   | 4821/7343 [01:28<00:44, 56.64it/s]

Gaps (ex-reports):  66%|██████▌   | 4827/7343 [01:29<00:46, 54.25it/s]

Gaps (ex-reports):  66%|██████▌   | 4833/7343 [01:29<00:46, 53.53it/s]

Gaps (ex-reports):  66%|██████▌   | 4842/7343 [01:29<00:41, 59.76it/s]

Gaps (ex-reports):  66%|██████▌   | 4849/7343 [01:29<00:47, 52.56it/s]

Gaps (ex-reports):  66%|██████▌   | 4860/7343 [01:29<00:37, 65.91it/s]

Gaps (ex-reports):  66%|██████▋   | 4868/7343 [01:29<00:42, 58.58it/s]

Gaps (ex-reports):  66%|██████▋   | 4875/7343 [01:29<00:43, 56.37it/s]

Gaps (ex-reports):  67%|██████▋   | 4884/7343 [01:30<00:38, 63.95it/s]

Gaps (ex-reports):  67%|██████▋   | 4891/7343 [01:30<00:47, 51.37it/s]

Gaps (ex-reports):  67%|██████▋   | 4901/7343 [01:30<00:40, 60.76it/s]

Gaps (ex-reports):  67%|██████▋   | 4908/7343 [01:30<00:43, 55.71it/s]

Gaps (ex-reports):  67%|██████▋   | 4916/7343 [01:30<00:42, 56.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4923/7343 [01:30<00:45, 53.56it/s]

Gaps (ex-reports):  67%|██████▋   | 4934/7343 [01:30<00:40, 58.80it/s]

Gaps (ex-reports):  67%|██████▋   | 4941/7343 [01:31<00:40, 59.60it/s]

Gaps (ex-reports):  67%|██████▋   | 4948/7343 [01:31<00:42, 56.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4954/7343 [01:31<00:46, 50.94it/s]

Gaps (ex-reports):  68%|██████▊   | 4964/7343 [01:31<00:39, 60.83it/s]

Gaps (ex-reports):  68%|██████▊   | 4971/7343 [01:31<00:38, 61.50it/s]

Gaps (ex-reports):  68%|██████▊   | 4979/7343 [01:31<00:36, 64.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4986/7343 [01:31<00:38, 60.92it/s]

Gaps (ex-reports):  68%|██████▊   | 4993/7343 [01:31<00:44, 52.46it/s]

Gaps (ex-reports):  68%|██████▊   | 5001/7343 [01:32<00:43, 53.72it/s]

Gaps (ex-reports):  68%|██████▊   | 5009/7343 [01:32<00:39, 58.57it/s]

Gaps (ex-reports):  68%|██████▊   | 5018/7343 [01:32<00:42, 55.20it/s]

Gaps (ex-reports):  68%|██████▊   | 5024/7343 [01:32<00:42, 55.05it/s]

Gaps (ex-reports):  69%|██████▊   | 5030/7343 [01:32<00:41, 55.08it/s]

Gaps (ex-reports):  69%|██████▊   | 5040/7343 [01:32<00:35, 64.50it/s]

Gaps (ex-reports):  69%|██████▊   | 5047/7343 [01:32<00:41, 54.70it/s]

Gaps (ex-reports):  69%|██████▉   | 5053/7343 [01:33<00:41, 54.66it/s]

Gaps (ex-reports):  69%|██████▉   | 5059/7343 [01:33<00:41, 55.71it/s]

Gaps (ex-reports):  69%|██████▉   | 5067/7343 [01:33<00:38, 58.82it/s]

Gaps (ex-reports):  69%|██████▉   | 5074/7343 [01:33<00:38, 59.41it/s]

Gaps (ex-reports):  69%|██████▉   | 5081/7343 [01:33<00:38, 58.76it/s]

Gaps (ex-reports):  69%|██████▉   | 5087/7343 [01:33<00:46, 48.11it/s]

Gaps (ex-reports):  69%|██████▉   | 5099/7343 [01:33<00:35, 63.67it/s]

Gaps (ex-reports):  70%|██████▉   | 5106/7343 [01:33<00:44, 50.79it/s]

Gaps (ex-reports):  70%|██████▉   | 5112/7343 [01:34<00:44, 50.70it/s]

Gaps (ex-reports):  70%|██████▉   | 5118/7343 [01:34<00:45, 49.11it/s]

Gaps (ex-reports):  70%|██████▉   | 5124/7343 [01:34<00:43, 51.17it/s]

Gaps (ex-reports):  70%|██████▉   | 5133/7343 [01:34<00:38, 57.03it/s]

Gaps (ex-reports):  70%|██████▉   | 5139/7343 [01:34<00:41, 53.03it/s]

Gaps (ex-reports):  70%|███████   | 5146/7343 [01:34<00:41, 52.71it/s]

Gaps (ex-reports):  70%|███████   | 5156/7343 [01:34<00:35, 62.42it/s]

Gaps (ex-reports):  70%|███████   | 5163/7343 [01:34<00:35, 61.93it/s]

Gaps (ex-reports):  70%|███████   | 5170/7343 [01:35<00:34, 62.23it/s]

Gaps (ex-reports):  71%|███████   | 5177/7343 [01:35<00:34, 63.52it/s]

Gaps (ex-reports):  71%|███████   | 5184/7343 [01:35<00:36, 59.04it/s]

Gaps (ex-reports):  71%|███████   | 5193/7343 [01:35<00:33, 64.83it/s]

Gaps (ex-reports):  71%|███████   | 5200/7343 [01:35<00:34, 62.17it/s]

Gaps (ex-reports):  71%|███████   | 5207/7343 [01:35<00:37, 56.67it/s]

Gaps (ex-reports):  71%|███████   | 5216/7343 [01:35<00:33, 63.86it/s]

Gaps (ex-reports):  71%|███████   | 5223/7343 [01:35<00:34, 62.11it/s]

Gaps (ex-reports):  71%|███████   | 5230/7343 [01:36<00:33, 63.87it/s]

Gaps (ex-reports):  71%|███████▏  | 5237/7343 [01:36<00:37, 56.25it/s]

Gaps (ex-reports):  71%|███████▏  | 5246/7343 [01:36<00:33, 63.36it/s]

Gaps (ex-reports):  72%|███████▏  | 5253/7343 [01:36<00:38, 54.40it/s]

Gaps (ex-reports):  72%|███████▏  | 5260/7343 [01:36<00:37, 55.59it/s]

Gaps (ex-reports):  72%|███████▏  | 5266/7343 [01:36<00:37, 55.46it/s]

Gaps (ex-reports):  72%|███████▏  | 5272/7343 [01:36<00:40, 51.48it/s]

Gaps (ex-reports):  72%|███████▏  | 5278/7343 [01:36<00:40, 50.63it/s]

Gaps (ex-reports):  72%|███████▏  | 5284/7343 [01:37<00:39, 52.13it/s]

Gaps (ex-reports):  72%|███████▏  | 5291/7343 [01:37<00:37, 54.39it/s]

Gaps (ex-reports):  72%|███████▏  | 5297/7343 [01:37<00:51, 39.52it/s]

Gaps (ex-reports):  72%|███████▏  | 5310/7343 [01:37<00:39, 50.94it/s]

Gaps (ex-reports):  72%|███████▏  | 5316/7343 [01:37<00:42, 47.63it/s]

Gaps (ex-reports):  72%|███████▏  | 5322/7343 [01:37<00:42, 48.08it/s]

Gaps (ex-reports):  73%|███████▎  | 5331/7343 [01:38<00:36, 55.18it/s]

Gaps (ex-reports):  73%|███████▎  | 5337/7343 [01:38<00:40, 49.59it/s]

Gaps (ex-reports):  73%|███████▎  | 5346/7343 [01:38<00:35, 56.36it/s]

Gaps (ex-reports):  73%|███████▎  | 5352/7343 [01:38<00:37, 53.23it/s]

Gaps (ex-reports):  73%|███████▎  | 5361/7343 [01:38<00:32, 61.27it/s]

Gaps (ex-reports):  73%|███████▎  | 5368/7343 [01:38<00:35, 55.85it/s]

Gaps (ex-reports):  73%|███████▎  | 5376/7343 [01:38<00:38, 51.43it/s]

Gaps (ex-reports):  73%|███████▎  | 5384/7343 [01:38<00:34, 56.76it/s]

Gaps (ex-reports):  73%|███████▎  | 5391/7343 [01:39<00:36, 53.37it/s]

Gaps (ex-reports):  74%|███████▎  | 5398/7343 [01:39<00:36, 53.81it/s]

Gaps (ex-reports):  74%|███████▎  | 5404/7343 [01:39<00:37, 51.22it/s]

Gaps (ex-reports):  74%|███████▎  | 5411/7343 [01:39<00:35, 54.09it/s]

Gaps (ex-reports):  74%|███████▍  | 5417/7343 [01:39<00:34, 55.36it/s]

Gaps (ex-reports):  74%|███████▍  | 5423/7343 [01:39<00:42, 44.73it/s]

Gaps (ex-reports):  74%|███████▍  | 5433/7343 [01:39<00:38, 49.79it/s]

Gaps (ex-reports):  74%|███████▍  | 5440/7343 [01:40<00:37, 50.59it/s]

Gaps (ex-reports):  74%|███████▍  | 5447/7343 [01:40<00:36, 52.36it/s]

Gaps (ex-reports):  74%|███████▍  | 5453/7343 [01:40<00:38, 49.70it/s]

Gaps (ex-reports):  74%|███████▍  | 5459/7343 [01:40<00:42, 44.23it/s]

Gaps (ex-reports):  74%|███████▍  | 5468/7343 [01:40<00:34, 53.61it/s]

Gaps (ex-reports):  75%|███████▍  | 5474/7343 [01:40<00:36, 51.55it/s]

Gaps (ex-reports):  75%|███████▍  | 5480/7343 [01:40<00:38, 47.98it/s]

Gaps (ex-reports):  75%|███████▍  | 5485/7343 [01:41<00:40, 45.78it/s]

Gaps (ex-reports):  75%|███████▍  | 5491/7343 [01:41<00:38, 47.85it/s]

Gaps (ex-reports):  75%|███████▍  | 5498/7343 [01:41<00:35, 52.27it/s]

Gaps (ex-reports):  75%|███████▍  | 5504/7343 [01:41<00:38, 48.26it/s]

Gaps (ex-reports):  75%|███████▌  | 5509/7343 [01:41<00:38, 47.82it/s]

Gaps (ex-reports):  75%|███████▌  | 5515/7343 [01:41<00:36, 49.49it/s]

Gaps (ex-reports):  75%|███████▌  | 5521/7343 [01:41<00:38, 46.83it/s]

Gaps (ex-reports):  75%|███████▌  | 5526/7343 [01:41<00:39, 46.25it/s]

Gaps (ex-reports):  75%|███████▌  | 5533/7343 [01:42<00:37, 47.95it/s]

Gaps (ex-reports):  75%|███████▌  | 5539/7343 [01:42<00:36, 49.12it/s]

Gaps (ex-reports):  76%|███████▌  | 5544/7343 [01:42<00:36, 49.07it/s]

Gaps (ex-reports):  76%|███████▌  | 5549/7343 [01:42<00:38, 46.11it/s]

Gaps (ex-reports):  76%|███████▌  | 5556/7343 [01:42<00:39, 45.01it/s]

Gaps (ex-reports):  76%|███████▌  | 5562/7343 [01:42<00:41, 43.14it/s]

Gaps (ex-reports):  76%|███████▌  | 5570/7343 [01:42<00:36, 48.90it/s]

Gaps (ex-reports):  76%|███████▌  | 5575/7343 [01:42<00:39, 45.15it/s]

Gaps (ex-reports):  76%|███████▌  | 5580/7343 [01:43<00:40, 43.37it/s]

Gaps (ex-reports):  76%|███████▌  | 5585/7343 [01:43<00:41, 42.08it/s]

Gaps (ex-reports):  76%|███████▌  | 5590/7343 [01:43<00:43, 40.12it/s]

Gaps (ex-reports):  76%|███████▋  | 5600/7343 [01:43<00:36, 47.70it/s]

Gaps (ex-reports):  76%|███████▋  | 5606/7343 [01:43<00:40, 42.94it/s]

Gaps (ex-reports):  76%|███████▋  | 5614/7343 [01:43<00:34, 49.72it/s]

Gaps (ex-reports):  77%|███████▋  | 5620/7343 [01:43<00:33, 50.97it/s]

Gaps (ex-reports):  77%|███████▋  | 5626/7343 [01:44<00:43, 39.45it/s]

Gaps (ex-reports):  77%|███████▋  | 5632/7343 [01:44<00:42, 40.42it/s]

Gaps (ex-reports):  77%|███████▋  | 5640/7343 [01:44<00:36, 46.18it/s]

Gaps (ex-reports):  77%|███████▋  | 5647/7343 [01:44<00:33, 51.30it/s]

Gaps (ex-reports):  77%|███████▋  | 5653/7343 [01:44<00:34, 48.84it/s]

Gaps (ex-reports):  77%|███████▋  | 5659/7343 [01:44<00:33, 49.81it/s]

Gaps (ex-reports):  77%|███████▋  | 5665/7343 [01:44<00:33, 50.33it/s]

Gaps (ex-reports):  77%|███████▋  | 5674/7343 [01:45<00:30, 54.68it/s]

Gaps (ex-reports):  77%|███████▋  | 5681/7343 [01:45<00:28, 58.08it/s]

Gaps (ex-reports):  77%|███████▋  | 5689/7343 [01:45<00:28, 57.88it/s]

Gaps (ex-reports):  78%|███████▊  | 5695/7343 [01:45<00:28, 58.40it/s]

Gaps (ex-reports):  78%|███████▊  | 5701/7343 [01:45<00:29, 55.75it/s]

Gaps (ex-reports):  78%|███████▊  | 5709/7343 [01:45<00:26, 61.15it/s]

Gaps (ex-reports):  78%|███████▊  | 5716/7343 [01:45<00:31, 50.90it/s]

Gaps (ex-reports):  78%|███████▊  | 5725/7343 [01:45<00:27, 58.45it/s]

Gaps (ex-reports):  78%|███████▊  | 5732/7343 [01:46<00:34, 46.34it/s]

Gaps (ex-reports):  78%|███████▊  | 5742/7343 [01:46<00:31, 50.26it/s]

Gaps (ex-reports):  78%|███████▊  | 5749/7343 [01:46<00:29, 53.33it/s]

Gaps (ex-reports):  78%|███████▊  | 5755/7343 [01:46<00:29, 53.16it/s]

Gaps (ex-reports):  78%|███████▊  | 5761/7343 [01:46<00:30, 52.17it/s]

Gaps (ex-reports):  79%|███████▊  | 5768/7343 [01:46<00:30, 50.86it/s]

Gaps (ex-reports):  79%|███████▊  | 5775/7343 [01:46<00:29, 52.39it/s]

Gaps (ex-reports):  79%|███████▊  | 5781/7343 [01:47<00:29, 53.62it/s]

Gaps (ex-reports):  79%|███████▉  | 5787/7343 [01:47<00:32, 47.94it/s]

Gaps (ex-reports):  79%|███████▉  | 5792/7343 [01:47<00:32, 47.79it/s]

Gaps (ex-reports):  79%|███████▉  | 5797/7343 [01:47<00:33, 46.80it/s]

Gaps (ex-reports):  79%|███████▉  | 5806/7343 [01:47<00:28, 54.14it/s]

Gaps (ex-reports):  79%|███████▉  | 5812/7343 [01:47<00:36, 42.51it/s]

Gaps (ex-reports):  79%|███████▉  | 5821/7343 [01:47<00:29, 51.58it/s]

Gaps (ex-reports):  79%|███████▉  | 5828/7343 [01:47<00:28, 53.06it/s]

Gaps (ex-reports):  79%|███████▉  | 5836/7343 [01:48<00:27, 54.88it/s]

Gaps (ex-reports):  80%|███████▉  | 5842/7343 [01:48<00:29, 51.33it/s]

Gaps (ex-reports):  80%|███████▉  | 5850/7343 [01:48<00:26, 55.41it/s]

Gaps (ex-reports):  80%|███████▉  | 5856/7343 [01:48<00:27, 54.38it/s]

Gaps (ex-reports):  80%|███████▉  | 5862/7343 [01:48<00:30, 49.31it/s]

Gaps (ex-reports):  80%|███████▉  | 5868/7343 [01:48<00:35, 42.14it/s]

Gaps (ex-reports):  80%|████████  | 5877/7343 [01:48<00:27, 52.54it/s]

Gaps (ex-reports):  80%|████████  | 5883/7343 [01:49<00:31, 45.76it/s]

Gaps (ex-reports):  80%|████████  | 5890/7343 [01:49<00:31, 45.47it/s]

Gaps (ex-reports):  80%|████████  | 5896/7343 [01:49<00:30, 46.68it/s]

Gaps (ex-reports):  80%|████████  | 5901/7343 [01:49<00:30, 47.31it/s]

Gaps (ex-reports):  80%|████████  | 5907/7343 [01:49<00:29, 48.34it/s]

Gaps (ex-reports):  81%|████████  | 5912/7343 [01:49<00:31, 44.83it/s]

Gaps (ex-reports):  81%|████████  | 5921/7343 [01:49<00:26, 53.43it/s]

Gaps (ex-reports):  81%|████████  | 5927/7343 [01:50<00:29, 47.27it/s]

Gaps (ex-reports):  81%|████████  | 5934/7343 [01:50<00:27, 50.76it/s]

Gaps (ex-reports):  81%|████████  | 5940/7343 [01:50<00:29, 47.02it/s]

Gaps (ex-reports):  81%|████████  | 5946/7343 [01:50<00:27, 50.03it/s]

Gaps (ex-reports):  81%|████████  | 5952/7343 [01:50<00:29, 46.99it/s]

Gaps (ex-reports):  81%|████████  | 5959/7343 [01:50<00:26, 51.73it/s]

Gaps (ex-reports):  81%|████████  | 5965/7343 [01:50<00:31, 43.87it/s]

Gaps (ex-reports):  81%|████████▏ | 5973/7343 [01:50<00:26, 52.06it/s]

Gaps (ex-reports):  81%|████████▏ | 5979/7343 [01:51<00:27, 49.20it/s]

Gaps (ex-reports):  82%|████████▏ | 5985/7343 [01:51<00:30, 44.03it/s]

Gaps (ex-reports):  82%|████████▏ | 5991/7343 [01:51<00:30, 45.01it/s]

Gaps (ex-reports):  82%|████████▏ | 5999/7343 [01:51<00:25, 52.91it/s]

Gaps (ex-reports):  82%|████████▏ | 6005/7343 [01:51<00:26, 50.75it/s]

Gaps (ex-reports):  82%|████████▏ | 6012/7343 [01:51<00:24, 54.29it/s]

Gaps (ex-reports):  82%|████████▏ | 6018/7343 [01:51<00:27, 48.41it/s]

Gaps (ex-reports):  82%|████████▏ | 6027/7343 [01:52<00:24, 53.18it/s]

Gaps (ex-reports):  82%|████████▏ | 6033/7343 [01:52<00:24, 54.45it/s]

Gaps (ex-reports):  82%|████████▏ | 6039/7343 [01:52<00:25, 51.71it/s]

Gaps (ex-reports):  82%|████████▏ | 6045/7343 [01:52<00:30, 42.91it/s]

Gaps (ex-reports):  82%|████████▏ | 6050/7343 [01:52<00:30, 42.43it/s]

Gaps (ex-reports):  83%|████████▎ | 6058/7343 [01:52<00:26, 48.60it/s]

Gaps (ex-reports):  83%|████████▎ | 6064/7343 [01:52<00:26, 47.84it/s]

Gaps (ex-reports):  83%|████████▎ | 6069/7343 [01:53<00:31, 40.12it/s]

Gaps (ex-reports):  83%|████████▎ | 6076/7343 [01:53<00:28, 44.77it/s]

Gaps (ex-reports):  83%|████████▎ | 6082/7343 [01:53<00:28, 44.82it/s]

Gaps (ex-reports):  83%|████████▎ | 6087/7343 [01:53<00:27, 45.88it/s]

Gaps (ex-reports):  83%|████████▎ | 6092/7343 [01:53<00:28, 43.60it/s]

Gaps (ex-reports):  83%|████████▎ | 6098/7343 [01:53<00:28, 43.67it/s]

Gaps (ex-reports):  83%|████████▎ | 6103/7343 [01:53<00:27, 44.65it/s]

Gaps (ex-reports):  83%|████████▎ | 6112/7343 [01:53<00:26, 46.17it/s]

Gaps (ex-reports):  83%|████████▎ | 6119/7343 [01:54<00:23, 51.09it/s]

Gaps (ex-reports):  83%|████████▎ | 6125/7343 [01:54<00:26, 46.61it/s]

Gaps (ex-reports):  84%|████████▎ | 6132/7343 [01:54<00:23, 50.69it/s]

Gaps (ex-reports):  84%|████████▎ | 6138/7343 [01:54<00:26, 45.28it/s]

Gaps (ex-reports):  84%|████████▎ | 6144/7343 [01:54<00:24, 48.42it/s]

Gaps (ex-reports):  84%|████████▍ | 6150/7343 [01:54<00:26, 44.22it/s]

Gaps (ex-reports):  84%|████████▍ | 6156/7343 [01:54<00:28, 42.02it/s]

Gaps (ex-reports):  84%|████████▍ | 6161/7343 [01:55<00:27, 42.87it/s]

Gaps (ex-reports):  84%|████████▍ | 6166/7343 [01:55<00:28, 41.49it/s]

Gaps (ex-reports):  84%|████████▍ | 6171/7343 [01:55<00:27, 42.67it/s]

Gaps (ex-reports):  84%|████████▍ | 6176/7343 [01:55<00:29, 40.13it/s]

Gaps (ex-reports):  84%|████████▍ | 6184/7343 [01:55<00:23, 48.77it/s]

Gaps (ex-reports):  84%|████████▍ | 6190/7343 [01:55<00:27, 41.26it/s]

Gaps (ex-reports):  84%|████████▍ | 6197/7343 [01:55<00:24, 46.56it/s]

Gaps (ex-reports):  84%|████████▍ | 6202/7343 [01:55<00:24, 46.37it/s]

Gaps (ex-reports):  85%|████████▍ | 6207/7343 [01:56<00:24, 46.89it/s]

Gaps (ex-reports):  85%|████████▍ | 6212/7343 [01:56<00:25, 43.96it/s]

Gaps (ex-reports):  85%|████████▍ | 6217/7343 [01:56<00:25, 44.38it/s]

Gaps (ex-reports):  85%|████████▍ | 6223/7343 [01:56<00:24, 46.67it/s]

Gaps (ex-reports):  85%|████████▍ | 6228/7343 [01:56<00:23, 46.68it/s]

Gaps (ex-reports):  85%|████████▍ | 6234/7343 [01:56<00:24, 45.86it/s]

Gaps (ex-reports):  85%|████████▍ | 6240/7343 [01:56<00:22, 48.96it/s]

Gaps (ex-reports):  85%|████████▌ | 6246/7343 [01:56<00:22, 47.72it/s]

Gaps (ex-reports):  85%|████████▌ | 6251/7343 [01:56<00:24, 45.01it/s]

Gaps (ex-reports):  85%|████████▌ | 6259/7343 [01:57<00:21, 50.39it/s]

Gaps (ex-reports):  85%|████████▌ | 6265/7343 [01:57<00:21, 51.11it/s]

Gaps (ex-reports):  85%|████████▌ | 6271/7343 [01:57<00:25, 41.81it/s]

Gaps (ex-reports):  85%|████████▌ | 6276/7343 [01:57<00:24, 42.79it/s]

Gaps (ex-reports):  86%|████████▌ | 6281/7343 [01:57<00:23, 44.32it/s]

Gaps (ex-reports):  86%|████████▌ | 6288/7343 [01:57<00:21, 48.61it/s]

Gaps (ex-reports):  86%|████████▌ | 6295/7343 [01:57<00:20, 51.51it/s]

Gaps (ex-reports):  86%|████████▌ | 6301/7343 [01:58<00:20, 50.85it/s]

Gaps (ex-reports):  86%|████████▌ | 6307/7343 [01:58<00:21, 49.24it/s]

Gaps (ex-reports):  86%|████████▌ | 6314/7343 [01:58<00:20, 51.20it/s]

Gaps (ex-reports):  86%|████████▌ | 6320/7343 [01:58<00:21, 47.79it/s]

Gaps (ex-reports):  86%|████████▌ | 6326/7343 [01:58<00:20, 50.46it/s]

Gaps (ex-reports):  86%|████████▌ | 6332/7343 [01:58<00:19, 50.59it/s]

Gaps (ex-reports):  86%|████████▋ | 6338/7343 [01:58<00:19, 50.41it/s]

Gaps (ex-reports):  86%|████████▋ | 6344/7343 [01:58<00:19, 50.37it/s]

Gaps (ex-reports):  86%|████████▋ | 6350/7343 [01:58<00:19, 50.41it/s]

Gaps (ex-reports):  87%|████████▋ | 6356/7343 [01:59<00:19, 50.05it/s]

Gaps (ex-reports):  87%|████████▋ | 6364/7343 [01:59<00:17, 55.67it/s]

Gaps (ex-reports):  87%|████████▋ | 6370/7343 [01:59<00:17, 56.66it/s]

Gaps (ex-reports):  87%|████████▋ | 6376/7343 [01:59<00:17, 54.72it/s]

Gaps (ex-reports):  87%|████████▋ | 6384/7343 [01:59<00:16, 56.98it/s]

Gaps (ex-reports):  87%|████████▋ | 6390/7343 [01:59<00:18, 50.81it/s]

Gaps (ex-reports):  87%|████████▋ | 6399/7343 [01:59<00:15, 59.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6406/7343 [02:00<00:17, 52.33it/s]

Gaps (ex-reports):  87%|████████▋ | 6417/7343 [02:00<00:14, 64.05it/s]

Gaps (ex-reports):  87%|████████▋ | 6424/7343 [02:00<00:15, 60.95it/s]

Gaps (ex-reports):  88%|████████▊ | 6432/7343 [02:00<00:15, 60.20it/s]

Gaps (ex-reports):  88%|████████▊ | 6439/7343 [02:00<00:15, 57.63it/s]

Gaps (ex-reports):  88%|████████▊ | 6445/7343 [02:00<00:15, 56.74it/s]

Gaps (ex-reports):  88%|████████▊ | 6451/7343 [02:00<00:15, 56.45it/s]

Gaps (ex-reports):  88%|████████▊ | 6457/7343 [02:00<00:16, 53.76it/s]

Gaps (ex-reports):  88%|████████▊ | 6463/7343 [02:00<00:16, 53.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6469/7343 [02:01<00:15, 54.71it/s]

Gaps (ex-reports):  88%|████████▊ | 6475/7343 [02:01<00:15, 54.90it/s]

Gaps (ex-reports):  88%|████████▊ | 6481/7343 [02:01<00:16, 51.87it/s]

Gaps (ex-reports):  88%|████████▊ | 6490/7343 [02:01<00:16, 51.75it/s]

Gaps (ex-reports):  88%|████████▊ | 6497/7343 [02:01<00:15, 55.59it/s]

Gaps (ex-reports):  89%|████████▊ | 6503/7343 [02:01<00:15, 55.16it/s]

Gaps (ex-reports):  89%|████████▊ | 6510/7343 [02:01<00:15, 55.24it/s]

Gaps (ex-reports):  89%|████████▊ | 6516/7343 [02:01<00:15, 54.64it/s]

Gaps (ex-reports):  89%|████████▉ | 6522/7343 [02:02<00:14, 56.01it/s]

Gaps (ex-reports):  89%|████████▉ | 6528/7343 [02:02<00:16, 50.45it/s]

Gaps (ex-reports):  89%|████████▉ | 6536/7343 [02:02<00:14, 55.50it/s]

Gaps (ex-reports):  89%|████████▉ | 6542/7343 [02:02<00:15, 51.63it/s]

Gaps (ex-reports):  89%|████████▉ | 6549/7343 [02:02<00:14, 54.11it/s]

Gaps (ex-reports):  89%|████████▉ | 6555/7343 [02:02<00:14, 53.97it/s]

Gaps (ex-reports):  89%|████████▉ | 6561/7343 [02:02<00:14, 52.64it/s]

Gaps (ex-reports):  89%|████████▉ | 6570/7343 [02:02<00:12, 62.15it/s]

Gaps (ex-reports):  90%|████████▉ | 6577/7343 [02:03<00:14, 52.37it/s]

Gaps (ex-reports):  90%|████████▉ | 6583/7343 [02:03<00:14, 52.18it/s]

Gaps (ex-reports):  90%|████████▉ | 6590/7343 [02:03<00:13, 54.64it/s]

Gaps (ex-reports):  90%|████████▉ | 6596/7343 [02:03<00:13, 55.33it/s]

Gaps (ex-reports):  90%|████████▉ | 6602/7343 [02:03<00:13, 56.20it/s]

Gaps (ex-reports):  90%|█████████ | 6609/7343 [02:03<00:12, 56.56it/s]

Gaps (ex-reports):  90%|█████████ | 6615/7343 [02:03<00:13, 55.53it/s]

Gaps (ex-reports):  90%|█████████ | 6622/7343 [02:03<00:12, 56.81it/s]

Gaps (ex-reports):  90%|█████████ | 6629/7343 [02:04<00:12, 57.48it/s]

Gaps (ex-reports):  90%|█████████ | 6635/7343 [02:04<00:12, 54.60it/s]

Gaps (ex-reports):  90%|█████████ | 6642/7343 [02:04<00:12, 54.80it/s]

Gaps (ex-reports):  91%|█████████ | 6649/7343 [02:04<00:11, 58.43it/s]

Gaps (ex-reports):  91%|█████████ | 6655/7343 [02:04<00:13, 49.92it/s]

Gaps (ex-reports):  91%|█████████ | 6663/7343 [02:04<00:13, 51.05it/s]

Gaps (ex-reports):  91%|█████████ | 6669/7343 [02:04<00:12, 52.78it/s]

Gaps (ex-reports):  91%|█████████ | 6675/7343 [02:04<00:12, 52.76it/s]

Gaps (ex-reports):  91%|█████████ | 6681/7343 [02:05<00:12, 52.80it/s]

Gaps (ex-reports):  91%|█████████ | 6690/7343 [02:05<00:11, 58.19it/s]

Gaps (ex-reports):  91%|█████████ | 6696/7343 [02:05<00:11, 56.14it/s]

Gaps (ex-reports):  91%|█████████▏| 6705/7343 [02:05<00:10, 58.09it/s]

Gaps (ex-reports):  91%|█████████▏| 6711/7343 [02:05<00:10, 57.77it/s]

Gaps (ex-reports):  92%|█████████▏| 6719/7343 [02:05<00:09, 62.74it/s]

Gaps (ex-reports):  92%|█████████▏| 6726/7343 [02:05<00:10, 57.35it/s]

Gaps (ex-reports):  92%|█████████▏| 6733/7343 [02:05<00:11, 53.22it/s]

Gaps (ex-reports):  92%|█████████▏| 6740/7343 [02:06<00:11, 51.45it/s]

Gaps (ex-reports):  92%|█████████▏| 6749/7343 [02:06<00:10, 57.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6755/7343 [02:06<00:10, 55.63it/s]

Gaps (ex-reports):  92%|█████████▏| 6761/7343 [02:06<00:11, 52.58it/s]

Gaps (ex-reports):  92%|█████████▏| 6767/7343 [02:06<00:11, 51.72it/s]

Gaps (ex-reports):  92%|█████████▏| 6776/7343 [02:06<00:09, 58.19it/s]

Gaps (ex-reports):  92%|█████████▏| 6782/7343 [02:06<00:10, 54.19it/s]

Gaps (ex-reports):  92%|█████████▏| 6791/7343 [02:06<00:08, 62.77it/s]

Gaps (ex-reports):  93%|█████████▎| 6798/7343 [02:07<00:09, 55.45it/s]

Gaps (ex-reports):  93%|█████████▎| 6805/7343 [02:07<00:09, 55.45it/s]

Gaps (ex-reports):  93%|█████████▎| 6811/7343 [02:07<00:09, 54.45it/s]

Gaps (ex-reports):  93%|█████████▎| 6817/7343 [02:07<00:10, 52.34it/s]

Gaps (ex-reports):  93%|█████████▎| 6823/7343 [02:07<00:09, 52.52it/s]

Gaps (ex-reports):  93%|█████████▎| 6831/7343 [02:07<00:08, 58.51it/s]

Gaps (ex-reports):  93%|█████████▎| 6838/7343 [02:07<00:08, 59.54it/s]

Gaps (ex-reports):  93%|█████████▎| 6845/7343 [02:07<00:09, 54.08it/s]

Gaps (ex-reports):  93%|█████████▎| 6853/7343 [02:08<00:08, 58.10it/s]

Gaps (ex-reports):  93%|█████████▎| 6859/7343 [02:08<00:09, 51.39it/s]

Gaps (ex-reports):  94%|█████████▎| 6870/7343 [02:08<00:07, 63.16it/s]

Gaps (ex-reports):  94%|█████████▎| 6877/7343 [02:08<00:08, 56.18it/s]

Gaps (ex-reports):  94%|█████████▎| 6883/7343 [02:08<00:08, 52.84it/s]

Gaps (ex-reports):  94%|█████████▍| 6890/7343 [02:08<00:08, 56.13it/s]

Gaps (ex-reports):  94%|█████████▍| 6896/7343 [02:08<00:08, 51.76it/s]

Gaps (ex-reports):  94%|█████████▍| 6904/7343 [02:08<00:07, 57.43it/s]

Gaps (ex-reports):  94%|█████████▍| 6910/7343 [02:09<00:08, 48.49it/s]

Gaps (ex-reports):  94%|█████████▍| 6916/7343 [02:09<00:08, 49.77it/s]

Gaps (ex-reports):  94%|█████████▍| 6924/7343 [02:09<00:07, 56.81it/s]

Gaps (ex-reports):  94%|█████████▍| 6930/7343 [02:09<00:07, 55.15it/s]

Gaps (ex-reports):  94%|█████████▍| 6936/7343 [02:09<00:07, 55.18it/s]

Gaps (ex-reports):  95%|█████████▍| 6942/7343 [02:09<00:07, 56.16it/s]

Gaps (ex-reports):  95%|█████████▍| 6948/7343 [02:09<00:07, 53.85it/s]

Gaps (ex-reports):  95%|█████████▍| 6955/7343 [02:09<00:07, 55.39it/s]

Gaps (ex-reports):  95%|█████████▍| 6962/7343 [02:10<00:06, 57.63it/s]

Gaps (ex-reports):  95%|█████████▍| 6968/7343 [02:10<00:06, 55.59it/s]

Gaps (ex-reports):  95%|█████████▌| 6976/7343 [02:10<00:06, 57.02it/s]

Gaps (ex-reports):  95%|█████████▌| 6982/7343 [02:10<00:06, 57.51it/s]

Gaps (ex-reports):  95%|█████████▌| 6990/7343 [02:10<00:06, 58.00it/s]

Gaps (ex-reports):  95%|█████████▌| 6996/7343 [02:10<00:06, 55.69it/s]

Gaps (ex-reports):  95%|█████████▌| 7002/7343 [02:10<00:06, 55.39it/s]

Gaps (ex-reports):  95%|█████████▌| 7011/7343 [02:10<00:05, 57.56it/s]

Gaps (ex-reports):  96%|█████████▌| 7017/7343 [02:11<00:05, 55.04it/s]

Gaps (ex-reports):  96%|█████████▌| 7023/7343 [02:11<00:06, 50.76it/s]

Gaps (ex-reports):  96%|█████████▌| 7031/7343 [02:11<00:05, 54.17it/s]

Gaps (ex-reports):  96%|█████████▌| 7039/7343 [02:11<00:05, 60.49it/s]

Gaps (ex-reports):  96%|█████████▌| 7046/7343 [02:11<00:05, 56.81it/s]

Gaps (ex-reports):  96%|█████████▌| 7056/7343 [02:11<00:04, 62.60it/s]

Gaps (ex-reports):  96%|█████████▌| 7063/7343 [02:11<00:05, 54.52it/s]

Gaps (ex-reports):  96%|█████████▋| 7069/7343 [02:11<00:04, 55.23it/s]

Gaps (ex-reports):  96%|█████████▋| 7076/7343 [02:12<00:04, 57.16it/s]

Gaps (ex-reports):  96%|█████████▋| 7083/7343 [02:12<00:04, 58.26it/s]

Gaps (ex-reports):  97%|█████████▋| 7090/7343 [02:12<00:04, 60.40it/s]

Gaps (ex-reports):  97%|█████████▋| 7097/7343 [02:12<00:04, 58.92it/s]

Gaps (ex-reports):  97%|█████████▋| 7103/7343 [02:12<00:04, 55.17it/s]

Gaps (ex-reports):  97%|█████████▋| 7111/7343 [02:12<00:03, 61.34it/s]

Gaps (ex-reports):  97%|█████████▋| 7118/7343 [02:12<00:03, 58.50it/s]

Gaps (ex-reports):  97%|█████████▋| 7124/7343 [02:12<00:03, 56.64it/s]

Gaps (ex-reports):  97%|█████████▋| 7131/7343 [02:12<00:03, 59.30it/s]

Gaps (ex-reports):  97%|█████████▋| 7138/7343 [02:13<00:03, 59.14it/s]

Gaps (ex-reports):  97%|█████████▋| 7144/7343 [02:13<00:03, 56.54it/s]

Gaps (ex-reports):  97%|█████████▋| 7152/7343 [02:13<00:03, 60.92it/s]

Gaps (ex-reports):  97%|█████████▋| 7159/7343 [02:13<00:03, 52.16it/s]

Gaps (ex-reports):  98%|█████████▊| 7167/7343 [02:13<00:03, 55.84it/s]

Gaps (ex-reports):  98%|█████████▊| 7174/7343 [02:13<00:02, 57.94it/s]

Gaps (ex-reports):  98%|█████████▊| 7180/7343 [02:13<00:03, 51.60it/s]

Gaps (ex-reports):  98%|█████████▊| 7188/7343 [02:14<00:02, 56.96it/s]

Gaps (ex-reports):  98%|█████████▊| 7196/7343 [02:14<00:02, 61.74it/s]

Gaps (ex-reports):  98%|█████████▊| 7203/7343 [02:14<00:02, 59.25it/s]

Gaps (ex-reports):  98%|█████████▊| 7210/7343 [02:14<00:02, 61.21it/s]

Gaps (ex-reports):  98%|█████████▊| 7217/7343 [02:14<00:02, 59.22it/s]

Gaps (ex-reports):  98%|█████████▊| 7224/7343 [02:14<00:01, 60.20it/s]

Gaps (ex-reports):  98%|█████████▊| 7231/7343 [02:14<00:01, 59.83it/s]

Gaps (ex-reports):  99%|█████████▊| 7238/7343 [02:14<00:01, 60.28it/s]

Gaps (ex-reports):  99%|█████████▊| 7246/7343 [02:14<00:01, 64.98it/s]

Gaps (ex-reports):  99%|█████████▉| 7253/7343 [02:15<00:01, 63.97it/s]

Gaps (ex-reports):  99%|█████████▉| 7260/7343 [02:15<00:01, 64.99it/s]

Gaps (ex-reports):  99%|█████████▉| 7267/7343 [02:15<00:01, 59.72it/s]

Gaps (ex-reports):  99%|█████████▉| 7276/7343 [02:15<00:01, 62.24it/s]

Gaps (ex-reports):  99%|█████████▉| 7283/7343 [02:15<00:00, 60.99it/s]

Gaps (ex-reports):  99%|█████████▉| 7291/7343 [02:15<00:00, 65.60it/s]

Gaps (ex-reports):  99%|█████████▉| 7298/7343 [02:15<00:00, 56.58it/s]

Gaps (ex-reports): 100%|█████████▉| 7308/7343 [02:15<00:00, 65.96it/s]

Gaps (ex-reports): 100%|█████████▉| 7315/7343 [02:16<00:00, 59.41it/s]

Gaps (ex-reports): 100%|█████████▉| 7322/7343 [02:16<00:00, 58.14it/s]

Gaps (ex-reports): 100%|█████████▉| 7331/7343 [02:16<00:00, 58.86it/s]

Gaps (ex-reports): 100%|█████████▉| 7340/7343 [02:16<00:00, 65.12it/s]

Gaps (ex-reports): 100%|█████████▉| 7340/7343 [02:26<00:00, 65.12it/s]

Gaps (ex-reports): 100%|██████████| 7343/7343 [02:28<00:00,  1.86it/s]

Gaps (ex-reports): 100%|██████████| 7343/7343 [02:28<00:00, 49.56it/s]

Rows in gaps (without report days): 295661

Tickers with sigma: 7128

  ticker     sigma
0      A  0.941716
1     AA  2.044939
2   AAAU  1.485682
3   AACG  3.401429
4    AAL  1.746507

In [43]:
std_by_ticker

     ticker     sigma
0         A  0.941716
1        AA  2.044939
2      AAAU  1.485682
3      AACG  3.401429
4       AAL  1.746507
...     ...       ...
7123   ZVOL  0.871778
7124   ZVRA  0.939471
7125    ZWS  0.957572
7126   ZYBT  3.535419
7127   ZYME  0.890252

[7128 rows x 2 columns]

In [44]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [45]:
# std_by_ticker columns: ['ticker', 'sigma']
sigma_out_path = add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,
    insert_before=None,
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=24.3s

[batch   10] rows=20,000,000  elapsed=47.8s

[batch   15] rows=30,000,000  elapsed=71.2s

[batch   20] rows=40,000,000  elapsed=94.1s

[batch   25] rows=50,000,000  elapsed=117.4s

[batch   30] rows=60,000,000  elapsed=141.7s

[batch   35] rows=70,000,000  elapsed=163.6s

✅ DONE rows=77,717,692 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 183.1s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 7128
tickers checked in parquet: 7121
max |file_sigma - expected_sigma|: 4.999776517244925e-07

In [46]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 77,717,692
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 0/21150
NaN у 'beta' (у прев'ю): 0/21150

Перші рядки:

      ticker                  dt           o           h           l           c          v        date    open  prev_close  Stack% bench    corr    beta  Bench%     sigma
0          A 2026-04-28 00:00:00  116.320000  116.320000  116.320000  116.320000       10.0  2026-04-28  116.23      115.61    0.61   XLV  0.5579  0.8120     NaN  0.941716
1          A 2026-04-28 09:29:00  116.430000  116.440002  116.430000  116.440002      200.0  2026-04-28  116.23      115.61    0.71   XLV  0.5579  0.8120    0.71  0.941716
2          A 2026-04-28 09:30:00  116.230003  116.635002  115.970001  116.279999    18280.0  2026-04-28  116.23      115.61    0.54   XLV  0.5579  0.8120    0.78  0.941716
3          A 2026-04-28 09:31:00  116.459999  116.459999  116.230003  116.230003      200.0  2026-04-28  116.23      115.61    0.74   XLV  0.5579  0.8120    0.77  0.941716
4          A 2026-04-28 09:32:00  116.275002  116.540001  116.250000  116.540001     1000.0  2026-04-28  116.23      115.61    0.58   XLV  0.5579  0.8120    0.84  0.941716
5          A 2026-04-28 09:33:00  116.275002  116.275002  116.275002  116.275002      100.0  2026-04-28  116.23      115.61    0.58   XLV  0.5579  0.8120    0.78  0.941716
6          A 2026-04-28 09:34:00  116.570000  116.620003  116.154999  116.154999     4509.0  2026-04-28  116.23      115.61    0.83   XLV  0.5579  0.8120    0.88  0.941716
7          A 2026-04-28 09:35:00  116.154999  116.290001  115.949997  116.099998     1909.0  2026-04-28  116.23      115.61    0.47   XLV  0.5579  0.8120    0.67  0.941716
8          A 2026-04-28 09:36:00  115.959999  116.105003  115.875000  115.949997     1490.0  2026-04-28  116.23      115.61    0.30   XLV  0.5579  0.8120    0.68  0.941716
9          A 2026-04-28 09:37:00  115.949997  116.209999  115.820000  116.209999     7862.0  2026-04-28  116.23      115.61    0.29   XLV  0.5579  0.8120    0.72  0.941716
10         A 2026-04-28 09:38:00  116.129997  116.290001  115.900002  116.110001     3835.0  2026-04-28  116.23      115.61    0.45   XLV  0.5579  0.8120    0.67  0.941716
11         A 2026-04-28 09:39:00  116.120003  116.120003  116.120003  116.120003      100.0  2026-04-28  116.23      115.61    0.44   XLV  0.5579  0.8120    0.62  0.941716
12         A 2026-04-28 09:40:00  115.919998  116.360001  115.915001  116.000000     5120.0  2026-04-28  116.23      115.61    0.27   XLV  0.5579  0.8120    0.49  0.941716
13         A 2026-04-28 09:41:00  116.114998  116.250000  116.000000  116.025002     2301.0  2026-04-28  116.23      115.61    0.44   XLV  0.5579  0.8120    0.46  0.941716
14         A 2026-04-28 09:42:00  116.139999  116.180000  116.059998  116.165001     3244.0  2026-04-28  116.23      115.61    0.46   XLV  0.5579  0.8120    0.56  0.941716
15         A 2026-04-28 09:43:00  116.165001  116.165001  115.650002  115.824997    20094.0  2026-04-28  116.23      115.61    0.48   XLV  0.5579  0.8120    0.54  0.941716
16         A 2026-04-28 09:44:00  115.824997  116.019997  115.824997  115.970001      505.0  2026-04-28  116.23      115.61    0.19   XLV  0.5579  0.8120    0.47  0.941716
17         A 2026-04-28 09:45:00  116.010002  116.199997  115.989998  116.099998     3811.0  2026-04-28  116.23      115.61    0.35   XLV  0.5579  0.8120    0.50  0.941716
18         A 2026-04-28 09:46:00  116.019997  116.040001  115.529999  115.620003    12822.0  2026-04-28  116.23      115.61    0.35   XLV  0.5579  0.8120    0.62  0.941716
19         A 2026-04-28 09:47:00  115.769997  115.839996  115.540001  115.540001     2159.0  2026-04-28  116.23      115.61    0.14   XLV  0.5579  0.8120    0.65  0.941716
20         A 2026-04-28 09:48:00  115.360001  115.360001  114.884598  114.884598      992.0  2026-04-28  116.23      115.61   -0.22   XLV  0.5579  0.8120    0.56  0.941716
21         A 2026-04-28 09:49:00  115.110001  115.110001  114.879997  114.879997     1160.0  2026-04-28  116.23      115.61   -0.43   XLV  0.5579  0.8120    0.49  0.941716
22         A 2026-04-28 09:50:00  115.025002  115.169998  114.879997  115.045670     9298.0  2026-04-28  116.23      115.61   -0.51   XLV  0.5579  0.8120    0.52  0.941716
23         A 2026-04-28 09:51:00  115.169998  115.400002  115.169998  115.400002     1500.0  2026-04-28  116.23      115.61   -0.38   XLV  0.5579  0.8120    0.56  0.941716
24         A 2026-04-28 09:52:00  115.285004  115.410004  115.269997  115.400002      900.0  2026-04-28  116.23      115.61   -0.28   XLV  0.5579  0.8120    0.56  0.941716
25         A 2026-04-28 09:53:00  115.230003  115.300003  115.139999  115.169998    16146.0  2026-04-28  116.23      115.61   -0.33   XLV  0.5579  0.8120    0.58  0.941716
26         A 2026-04-28 09:54:00  115.305000  115.305000  115.305000  115.305000      600.0  2026-04-28  116.23      115.61   -0.26   XLV  0.5579  0.8120    0.65  0.941716
27         A 2026-04-28 09:55:00  115.305000  115.309998  114.980003  114.980003     5607.0  2026-04-28  116.23      115.61   -0.26   XLV  0.5579  0.8120    0.59  0.941716
28         A 2026-04-28 09:56:00  115.095001  115.250000  114.980003  115.095001     5800.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.8120    0.63  0.941716
29         A 2026-04-28 09:57:00  115.095001  115.095001  115.000000  115.089996     1347.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.8120    0.59  0.941716
30         A 2026-04-28 09:58:00  115.080002  115.080002  114.760002  114.760002     2638.0  2026-04-28  116.23      115.61   -0.46   XLV  0.5579  0.8120    0.56  0.941716
31         A 2026-04-28 09:59:00  114.760002  114.839996  114.480003  114.480003     3730.0  2026-04-28  116.23      115.61   -0.74   XLV  0.5579  0.8120    0.47  0.941716
32         A 2026-04-28 10:00:00  114.480003  114.660004  114.260002  114.639999     6586.0  2026-04-28  116.23      115.61   -0.98   XLV  0.5579  0.8120    0.46  0.941716
33         A 2026-04-28 10:01:00  114.635002  114.870003  114.610001  114.870003     3617.0  2026-04-28  116.23      115.61   -0.84   XLV  0.5579  0.8120    0.45  0.941716
34         A 2026-04-28 10:02:00  114.739998  114.959999  114.739998  114.775002    11826.0  2026-04-28  116.23      115.61   -0.75   XLV  0.5579  0.8120    0.43  0.941716
35         A 2026-04-28 10:03:00  114.775002  114.775002  114.769997  114.769997      306.0  2026-04-28  116.23      115.61   -0.72   XLV  0.5579  0.8120    0.46  0.941716
36         A 2026-04-28 10:04:00  114.769997  115.129997  114.769997  114.970001     6825.0  2026-04-28  116.23      115.61   -0.73   XLV  0.5579  0.8120    0.46  0.941716
37         A 2026-04-28 10:05:00  114.970001  115.129997  114.800003  115.120003    11839.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.8120    0.49  0.941716
38         A 2026-04-28 10:06:00  115.105003  115.129997  115.080002  115.120003     3696.0  2026-04-28  116.23      115.61   -0.44   XLV  0.5579  0.8120    0.49  0.941716
39         A 2026-04-28 10:07:00  115.160004  115.250000  115.080002  115.080002     1389.0  2026-04-28  116.23      115.61   -0.39   XLV  0.5579  0.8120    0.52  0.941716
40         A 2026-04-28 10:08:00  115.080002  115.199501  115.070000  115.199501     1081.0  2026-04-28  116.23      115.61   -0.46   XLV  0.5579  0.8120    0.52  0.941716
41         A 2026-04-28 10:09:00  115.070000  115.154999  115.070000  115.154999     1130.0  2026-04-28  116.23      115.61   -0.47   XLV  0.5579  0.8120    0.44  0.941716
42         A 2026-04-28 10:10:00  115.154999  115.154999  115.070000  115.070000      319.0  2026-04-28  116.23      115.61   -0.39   XLV  0.5579  0.8120    0.47  0.941716
43         A 2026-04-28 10:11:00  115.129997  115.169998  114.900002  115.019997     2200.0  2026-04-28  116.23      115.61   -0.42   XLV  0.5579  0.8120    0.51  0.941716
44         A 2026-04-28 10:12:00  114.889999  115.000000  114.889999  115.000000      300.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.8120    0.48  0.941716
45         A 2026-04-28 10:13:00  114.889999  115.025002  114.889999  115.019997     2799.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.8120    0.43  0.941716
46         A 2026-04-28 10:14:00  114.830002  114.879997  114.830002  114.879997      300.0  2026-04-28  116.23      115.61   -0.67   XLV  0.5579  0.8120    0.38  0.941716
47         A 2026-04-28 10:15:00  114.809998  115.000000  114.449997  114.470001    61813.0  2026-04-28  116.23      115.61   -0.69   XLV  0.5579  0.8120    0.38  0.941716
48         A 2026-04-28 10:16:00  114.434998  114.434998  114.434998  114.434998      100.0  2026-04-28  116.23      115.61   -1.02   XLV  0.5579  0.8120    0.36  0.941716
49         A 2026-04-28 10:17:00  114.419998  114.540001  114.300003  114.315002     3963.0  2026-04-28  116.23      115.61   -1.03   XLV  0.5579  0.8120    0.40  0.941716
50         A 2026-04-28 10:18:00  114.239998  114.300003  114.099998  114.254997     1580.0  2026-04-28  116.23      115.61   -1.19   XLV  0.5579  0.8120    0.41  0.941716
51         A 2026-04-28 10:19:00  114.254997  114.419998  114.209999  114.419998     1800.0  2026-04-28  116.23      115.61   -1.17   XLV  0.5579  0.8120    0.32  0.941716
52         A 2026-04-28 10:20:00  114.519997  114.739998  114.519997  114.639999     2310.0  2026-04-28  116.23      115.61   -0.94   XLV  0.5579  0.8120    0.34  0.941716
53         A 2026-04-28 10:21:00  114.709999  114.709999  114.709999  114.709999      100.0  2026-04-28  116.23      115.61   -0.78   XLV  0.5579  0.8120    0.40  0.941716
54         A 2026-04-28 10:22:00  114.675003  114.675003  114.550003  114.550003      200.0  2026-04-28  116.23      115.61   -0.81   XLV  0.5579  0.8120    0.34  0.941716
55         A 2026-04-28 10:23:00  114.589996  114.605003  114.559998  114.605003      500.0  2026-04-28  116.23      115.61   -0.88   XLV  0.5579  0.8120    0.30  0.941716
56         A 2026-04-28 10:24:00  114.790001  114.809998  114.790001  114.800003     2440.0  2026-04-28  116.23      115.61   -0.71   XLV  0.5579  0.8120    0.35  0.941716
57         A 2026-04-28 10:26:00  114.760002  114.830002  114.760002  114.764999      800.0  2026-04-28  116.23      115.61   -0.74   XLV  0.5579  0.8120    0.41  0.941716
58         A 2026-04-28 10:27:00  114.639999  114.750000  114.639999  114.730675     1295.0  2026-04-28  116.23      115.61   -0.84   XLV  0.5579  0.8120    0.37  0.941716
59         A 2026-04-28 10:28:00  114.762497  114.762497  114.745003  114.745003      200.0  2026-04-28  116.23      115.61   -0.73   XLV  0.5579  0.8120    0.36  0.941716
60         A 2026-04-28 10:29:00  114.745003  114.745003  114.570000  114.625000     3553.0  2026-04-28  116.23      115.61   -0.75   XLV  0.5579  0.8120    0.30  0.941716
61         A 2026-04-28 10:30:00  114.625000  114.625000  114.625000  114.625000      500.0  2026-04-28  116.23      115.61   -0.85   XLV  0.5579  0.8120    0.24  0.941716
62         A 2026-04-28 10:31:00  114.620003  114.887901  114.620003  114.887901     3143.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.8120    0.24  0.941716
63         A 2026-04-28 10:32:00  114.809998  114.809998  114.610001  114.610001     1005.0  2026-04-28  116.23      115.61   -0.69   XLV  0.5579  0.8120    0.33  0.941716
64         A 2026-04-28 10:33:00  114.620003  114.625000  114.599998  114.620003      700.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.8120    0.26  0.941716
65         A 2026-04-28 10:34:00  114.620003  114.620003  114.480003  114.480003      700.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.8120    0.30  0.941716
66         A 2026-04-28 10:35:00  114.620003  114.620003  114.455002  114.614998      748.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.8120    0.28  0.941716
67         A 2026-04-28 10:36:00  114.654999  114.654999  114.654999  114.654999      300.0  2026-04-28  116.23      115.61   -0.83   XLV  0.5579  0.8120    0.40  0.941716
68         A 2026-04-28 10:37:00  114.705002  114.705002  114.705002  114.705002      600.0  2026-04-28  116.23      115.61   -0.78   XLV  0.5579  0.8120    0.38  0.941716
69         A 2026-04-28 10:38:00  114.610001  114.705002  114.610001  114.635002     1100.0  2026-04-28  116.23      115.61   -0.86   XLV  0.5579  0.8120    0.46  0.941716
70         A 2026-04-28 10:39:00  114.692497  114.772797  114.510002  114.772797     6167.0  2026-04-28  116.23      115.61   -0.79   XLV  0.5579  0.8120    0.47  0.941716
71         A 2026-04-28 10:40:00  114.889999  114.900002  114.889999  114.900002      200.0  2026-04-28  116.23      115.61   -0.62   XLV  0.5579  0.8120    0.43  0.941716
72         A 2026-04-28 10:41:00  114.910004  115.040001  114.910004  115.040001     2160.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.8120    0.54  0.941716
73         A 2026-04-28 10:42:00  114.985001  115.080002  114.919998  115.080002     5331.0  2026-04-28  116.23      115.61   -0.54   XLV  0.5579  0.8120    0.61  0.941716
74         A 2026-04-28 10:43:00  114.959999  114.989998  114.930000  114.930000     1155.0  2026-04-28  116.23      115.61   -0.56   XLV  0.5579  0.8120    0.56  0.941716
75         A 2026-04-28 10:44:00  114.860001  114.879997  114.849998  114.879997      806.0  2026-04-28  116.23      115.61   -0.65   XLV  0.5579  0.8120    0.56  0.941716
76         A 2026-04-28 10:45:00  114.879997  114.879997  114.779999  114.875000     1272.0  2026-04-28  116.23      115.61   -0.63   XLV  0.5579  0.8120    0.53  0.941716
77         A 2026-04-28 10:46:00  114.779999  114.779999  114.750000  114.760002     1196.0  2026-04-28  116.23      115.61   -0.72   XLV  0.5579  0.8120    0.52  0.941716
78         A 2026-04-28 10:47:00  114.760002  114.959999  114.760002  114.879997     2600.0  2026-04-28  116.23      115.61   -0.74   XLV  0.5579  0.8120    0.54  0.941716
79         A 2026-04-28 10:50:00  114.879997  114.919998  114.879997  114.879997      800.0  2026-04-28  116.23      115.61   -0.63   XLV  0.5579  0.8120    0.73  0.941716
80         A 2026-04-28 10:51:00  114.879997  114.970001  114.870003  114.904999     2113.0  2026-04-28  116.23      115.61   -0.63   XLV  0.5579  0.8120    0.72  0.941716
81         A 2026-04-28 10:52:00  114.989998  115.059998  114.989998  115.059998      500.0  2026-04-28  116.23      115.61   -0.54   XLV  0.5579  0.8120    0.72  0.941716
82         A 2026-04-28 10:53:00  114.980003  115.089996  114.980003  115.040001     1701.0  2026-04-28  116.23      115.61   -0.54   XLV  0.5579  0.8120    0.75  0.941716
83         A 2026-04-28 10:54:00  115.144997  115.190002  115.095001  115.095001      800.0  2026-04-28  116.23      115.61   -0.40   XLV  0.5579  0.8120    0.77  0.941716
84         A 2026-04-28 10:55:00  115.099998  115.099998  114.980003  115.040001     2981.0  2026-04-28  116.23      115.61   -0.44   XLV  0.5579  0.8120    0.77  0.941716
85         A 2026-04-28 10:56:00  115.080002  115.139999  115.050003  115.139999     1362.0  2026-04-28  116.23      115.61   -0.46   XLV  0.5579  0.8120    0.70  0.941716
86         A 2026-04-28 10:57:00  114.995003  115.089996  114.989998  114.989998      400.0  2026-04-28  116.23      115.61   -0.53   XLV  0.5579  0.8120    0.70  0.941716
87         A 2026-04-28 10:58:00  115.089996  115.089996  114.889999  114.889999     2652.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.8120    0.67  0.941716
88         A 2026-04-28 10:59:00  114.834999  114.949997  114.834999  114.949997     1713.0  2026-04-28  116.23      115.61   -0.67   XLV  0.5579  0.8120    0.66  0.941716
89         A 2026-04-28 11:00:00  114.959999  114.995003  114.910004  114.995003     2488.0  2026-04-28  116.23      115.61   -0.56   XLV  0.5579  0.8120    0.63  0.941716
90         A 2026-04-28 11:01:00  115.050003  115.089996  114.970001  115.055000     3614.0  2026-04-28  116.23      115.61   -0.48   XLV  0.5579  0.8120    0.65  0.941716
91         A 2026-04-28 11:02:00  115.019997  115.190002  115.000000  115.000000     6092.0  2026-04-28  116.23      115.61   -0.51   XLV  0.5579  0.8120    0.71  0.941716
92         A 2026-04-28 11:03:00  115.000000  115.004997  114.864998  114.867500    18016.0  2026-04-28  116.23      115.61   -0.53   XLV  0.5579  0.8120    0.72  0.941716
93         A 2026-04-28 11:04:00  114.864998  115.019997  114.855003  115.019997     7097.0  2026-04-28  116.23      115.61   -0.64   XLV  0.5579  0.8120    0.63  0.941716
94         A 2026-04-28 11:05:00  114.970001  115.000000  114.970001  114.980003      813.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.8120    0.70  0.941716
95         A 2026-04-28 11:06:00  115.050003  115.050003  114.944000  114.989998     1535.0  2026-04-28  116.23      115.61   -0.48   XLV  0.5579  0.8120    0.70  0.941716
96         A 2026-04-28 11:07:00  114.974998  114.974998  114.970001  114.970001      429.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.8120    0.70  0.941716
97         A 2026-04-28 11:08:00  114.970001  115.059998  114.970001  115.000000      728.0  2026-04-28  116.23      115.61   -0.55   XLV  0.5579  0.8120    0.68  0.941716
98         A 2026-04-28 11:09:00  115.010002  115.139999  115.010002  115.139999     1148.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.8120    0.68  0.941716
99         A 2026-04-28 11:10:00  115.169998  115.169998  115.074997  115.129997      569.0  2026-04-28  116.23      115.61   -0.38   XLV  0.5579  0.8120    0.68  0.941716
100        A 2026-04-28 11:11:00  115.084999  115.160004  115.084999  115.120003      684.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.8120    0.69  0.941716
101        A 2026-04-28 11:12:00  115.084999  115.084999  114.905899  114.919998     3529.0  2026-04-28  116.23      115.61   -0.45   XLV  0.5579  0.8120    0.68  0.941716
102        A 2026-04-28 11:13:00  114.949997  115.019997  114.949997  115.019997      800.0  2026-04-28  116.23      115.61   -0.57   XLV  0.5579  0.8120    0.61  0.941716
103        A 2026-04-28 11:14:00  115.004997  115.004997  114.989998  114.989998      400.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.8120    0.65  0.941716
104        A 2026-04-28 11:15:00  115.010002  115.010002  115.010002  115.010002     1518.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.8120    0.56  0.941716
105        A 2026-04-28 11:16:00  115.010002  115.010002  115.010002  115.010002      700.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.8120    0.60  0.941716
106        A 2026-04-28 11:17:00  115.010002  115.010002  114.989998  114.989998      400.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.8120    0.59  0.941716
107        A 2026-04-28 11:18:00  115.010002  115.010002  114.910004  114.910004      300.0  2026-04-28  116.23      115.61   -0.52   XLV  0.5579  0.8120    0.60  0.941716
108        A 2026-04-28 11:19:00  114.910004  114.910004  114.904999  114.904999      600.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.8120    0.60  0.941716
109        A 2026-04-28 11:20:00  114.904999  115.010002  114.904999  114.930000      868.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.8120    0.56  0.941716
110        A 2026-04-28 11:21:00  114.900002  115.019997  114.900002  115.019997      500.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.8120    0.58  0.941716
111        A 2026-04-28 11:22:00  114.940002  115.029999  114.900002  114.940002     4867.0  2026-04-28  116.23      115.61   -0.58   XLV  0.5579  0.8120    0.66  0.941716
112        A 2026-04-28 11:23:00  114.940002  114.940002  114.889999  114.919998     3073.0  2026-04-28  116.23      115.61   -0.58   XLV  0.5579  0.8120    0.65  0.941716
113        A 2026-04-28 11:24:00  114.919998  114.940002  114.870003  114.870003     2421.0  2026-04-28  116.23      115.61   -0.60   XLV  0.5579  0.8120    0.63  0.941716
114        A 2026-04-28 11:25:00  114.900002  114.980003  114.860001  114.900002    34497.0  2026-04-28  116.23      115.61   -0.61   XLV  0.5579  0.8120    0.64  0.941716

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2026-04-28 00:00:00,116.320000,116.320000,116.320000,116.320000,10.0,2026-04-28,116.23,115.61,0.61,XLV,0.5579,0.812,NaN,0.941716
1,A,2026-04-28 09:29:00,116.430000,116.440002,116.430000,116.440002,200.0,2026-04-28,116.23,115.61,0.71,XLV,0.5579,0.812,0.71,0.941716
2,A,2026-04-28 09:30:00,116.230003,116.635002,115.970001,116.279999,18280.0,2026-04-28,116.23,115.61,0.54,XLV,0.5579,0.812,0.78,0.941716
3,A,2026-04-28 09:31:00,116.459999,116.459999,116.230003,116.230003,200.0,2026-04-28,116.23,115.61,0.74,XLV,0.5579,0.812,0.77,0.941716
4,A,2026-04-28 09:32:00,116.275002,116.540001,116.250000,116.540001,1000.0,2026-04-28,116.23,115.61,0.58,XLV,0.5579,0.812,0.84,0.941716
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AAL,2026-05-07 04:10:00,13.080000,13.080000,13.070000,13.070000,240.0,2026-05-07,13.14,12.94,1.08,XTN,0.7726,1.536,NaN,1.746507
21146,AAL,2026-05-07 04:12:00,13.070000,13.070000,13.070000,13.070000,1420.0,2026-05-07,13.14,12.94,1.00,XTN,0.7726,1.536,NaN,1.746507
21147,AAL,2026-05-07 04:13:00,13.060000,13.060000,13.060000,13.060000,500.0,2026-05-07,13.14,12.94,0.93,XTN,0.7726,1.536,NaN,1.746507
21148,AAL,2026-05-07 04:15:00,13.050000,13.060000,13.050000,13.050000,12540.0,2026-05-07,13.14,12.94,0.85,XTN,0.7726,1.536,NaN,1.746507
21149,AAL,2026-05-07 04:16:00,13.050000,13.050000,13.000000,13.020000,10155.0,2026-05-07,13.14,12.94,0.85,XTN,0.7726,1.536,NaN,1.746507

In [47]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [48]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=13.5s

[batch   10] rows=20,000,000  elapsed=25.6s

[batch   15] rows=30,000,000  elapsed=40.0s

[batch   20] rows=40,000,000  elapsed=54.0s

[batch   25] rows=50,000,000  elapsed=67.9s

[batch   30] rows=60,000,000  elapsed=79.6s

[batch   35] rows=70,000,000  elapsed=93.6s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_23932_1782784367 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=7,527 | has_date=True has_dt=True

  [   200/7,527] AIBZ  written=2,121,275  elapsed=202.6s

  [   400/7,527] AOM  written=4,333,670  elapsed=406.4s

  [   600/7,527] AVAT  written=6,546,624  elapsed=612.5s

  [   800/7,527] BF.A  written=8,578,644  elapsed=820.1s

  [  1000/7,527] BREZU  written=10,593,795  elapsed=1,031.5s

  [  1200/7,527] CBSH  written=12,565,627  elapsed=1,240.2s

  [  1400/7,527] CLW  written=14,608,505  elapsed=1,447.3s

  [  1600/7,527] CRPT  written=16,829,924  elapsed=1,659.1s

  [  1800/7,527] DFAI  written=18,919,261  elapsed=1,867.0s

  [  2000/7,527] EAF  written=20,867,986  elapsed=2,073.2s

  [  2200/7,527] ERX  written=22,744,374  elapsed=2,283.8s

  [  2400/7,527] FDS  written=24,755,819  elapsed=2,495.5s

  [  2600/7,527] FSM  written=26,677,015  elapsed=2,702.3s

  [  2800/7,527] GLGG  written=28,587,866  elapsed=2,911.4s

  [  3000/7,527] HBNC  written=30,660,673  elapsed=3,122.7s

  [  3200/7,527] HYPD  written=32,639,370  elapsed=3,328.9s

  [  3400/7,527] INLF  written=34,481,009  elapsed=3,537.2s

  [  3600/7,527] JEF  written=36,704,506  elapsed=3,747.0s

  [  3800/7,527] KRRO  written=38,528,710  elapsed=3,942.1s

  [  4000/7,527] LPG  written=40,486,892  elapsed=4,135.9s

  [  4200/7,527] MGIH  written=42,516,281  elapsed=4,316.6s

  [  4400/7,527] MTNB  written=44,616,659  elapsed=4,487.7s

  [  4600/7,527] NNNN  written=46,785,620  elapsed=4,652.3s

  [  4800/7,527] OGS  written=48,946,132  elapsed=4,814.9s

  [  5000/7,527] PBF  written=51,171,212  elapsed=4,980.0s

  [  5200/7,527] POET  written=53,164,026  elapsed=5,143.8s

  [  5400/7,527] QQQU  written=55,226,094  elapsed=5,302.6s

  [  5600/7,527] RMSG  written=57,444,488  elapsed=5,464.4s

  [  5800/7,527] SCNX  written=59,581,583  elapsed=5,637.6s

  [  6000/7,527] SLXN  written=61,666,435  elapsed=5,812.4s

  [  6200/7,527] SPYX  written=64,191,547  elapsed=5,988.1s

  [  6400/7,527] TCBX  written=66,137,987  elapsed=6,169.8s

  [  6600/7,527] TRIP  written=68,206,311  elapsed=6,344.7s

  [  6800/7,527] UMC  written=70,346,738  elapsed=6,518.4s

  [  7000/7,527] VITL  written=72,426,232  elapsed=6,691.4s

  [  7200/7,527] WGMI  written=74,626,386  elapsed=6,865.8s

  [  7400/7,527] XSD  written=76,658,789  elapsed=7,046.9s

✅ SORT DONE: 77,717,692 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=7,154.9s
✅ DONE: 77,717,692 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=7,270.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'