In [1]:
# Parameters
run_date = "2026-02-22"
output_dir = "C:\\datum-api-examples-main\\OriON\\signals"

In [2]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [3]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [4]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [5]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2025-11-21 00:00:00
end   = 2026-02-21 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2025-11-21
end_date_str   = 2026-02-21

In [6]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    61531.01
1     AA  1528436.53
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 12646

In [7]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,country,exchange,market_cap',
    'active': True,
    'us_exchange': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
top1500 = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(top1500):,} рядків")
top1500.head()

Після фільтрації залишилось: 6,717 рядків

,ticker,value,lvl3,country,exchange,market_cap
0,A,61531.01,Medical Equipment & Devices,UNITED STATES,New York,34760.0
1,AA,1528436.53,Metals & Mining,UNITED STATES,New York,15664.0
2,AAAU,1143065.63,NaN,NaN,NaN,NaN
3,AACG,11.34,Software,UNITED STATES,NASDAQ CM,29.0
4,AACOU,10682.86,NaN,NaN,NaN,NaN

In [8]:
top1500[top1500["ticker"] == "JD"]

,ticker,value,lvl3,country,exchange,market_cap
3212,JD,2480223.49,E-Commerce Discretionary,UNITED STATES,NASDAQ GS,37306.0

In [9]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [10]:
unique_lvl2 = get_unique_lvl2(top1500)
unique_lvl2

🔹 Знайдено 58 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [11]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "BITO"],
    "Banking": ["KRE", "XLF", "SPY", "BITO"],
    "Institutional Financial Svcs": ["XLF", "SPY", "BITO"],
    "Insurance": ["XLF", "SPY", "BITO"],
    "Specialty Finance": ["XLF", "SPY", "BITO"],

    # --- Tech / Internet / Growth ---
    "Software": ["QQQ", "IWM", "SPY"],
    "IT Services": ["QQQ", "IWM", "SPY"],
    "Semiconductors": ["SOXL", "QQQ", "IWM", "SPY"],
    "Technology Hardware": ["QQQ", "SOXL", "IWM", "SPY"],
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["IWM", "SPY", "QQQ"],
    "Diversified Industrials": ["SPY", "IWM"],
    "Industrial Intermediate Prod": ["IWM", "SPY"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["IWM", "SPY"],
    "Machinery": ["IWM", "SPY"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["IWM", "SPY"],
    "Electrical Equipment": ["QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XLE", "IWM", "SPY"],
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLE", "IWM", "SPY"],
    "Gas & Water Utilities": ["XLE", "IWM", "SPY"],
    "Renewable Energy": ["XLE", "IWM", "SPY"],
    "Chemicals": ["XLE", "IWM", "SPY"],
    "Metals & Mining": ["GDX", "IWM", "SPY"],
    "Steel": ["GDX", "IWM", "SPY"],
    "Construction Materials": ["IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["QQQ", "IWM", "SPY"],
    "Medical Equipment & Devices": ["QQQ", "IWM", "SPY"],
    "Health Care Facilities & Svcs": ["QQQ", "IWM", "SPY"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["SPY", "IWM"],
    "Beverages": ["SPY", "IWM"],
    "Household Products": ["SPY", "IWM"],
    "Tobacco & Cannabis": ["SPY", "IWM"],
    "Retail - Consumer Staples": ["SPY", "IWM"],
    "Wholesale - Consumer Staples": ["SPY", "IWM"],

    "Retail - Discretionary": ["SPY", "IWM", "QQQ"],
    "Wholesale - Discretionary": ["SPY", "IWM", "QQQ"],
    "Consumer Services": ["SPY", "IWM"],
    "Leisure Facilities & Services": ["SPY", "IWM"],
    "Leisure Products": ["SPY", "IWM"],
    "Apparel & Textile Products": ["SPY", "IWM", "QQQ"],
    "Automotive": ["SPY", "IWM", "QQQ"],
    "Home & Office Products": ["SPY", "IWM"],
    "Home Construction": ["IWM", "SPY"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [12]:
# ------------------------------------------------

In [13]:
import time
import math
import pandas as pd

def corr_beta_best_match_batched(
    x_tickers,
    y_tickers,
    period="6 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path=None,          # 🔹 тепер дефолт = None
):
    """
    Викликає /calculations/corr_beta/v2 батчами, об'єднує результати в один DataFrame,
    для кожного X-тікера знаходить Y з максимальною кореляцією.

    Повертає (df_all, df_pairs):
      - df_all   : сирий об'єднаний датафрейм з API
      - df_pairs : мапінг X -> найкращий Y
    """
    # --- валідації ---
    if not x_tickers:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return pd.DataFrame(), empty_pairs

    if not y_tickers:
        raise ValueError("y_tickers не може бути порожнім")

    # --- батчинг (індексний підхід, щоб не губити/дублювати X) ---
    y_str = ",".join(map(str, y_tickers))
    results = []
    i = 0
    n = len(x_tickers)
    bs = max(1, int(batch_size))

    while i < n:
        xs = list(map(str, x_tickers[i : i + bs]))
        x_str = ",".join(xs)

        params = {
            "x_tickers": x_str,
            "y_tickers": y_str,
            "period": period,
            "as_pivot": as_pivot,
            "format": fmt,
        }

        attempt = 0
        while True:
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)

                # підстраховка типів
                if df_chunk is None:
                    fetched_ok = False
                elif isinstance(df_chunk, pd.DataFrame):
                    fetched_ok = not df_chunk.empty
                else:
                    df_chunk = pd.DataFrame(df_chunk)
                    fetched_ok = not df_chunk.empty

                if fetched_ok:
                    results.append(df_chunk)

                i += len(xs)
                print(f"[{i}/{n}] fetched batch of {len(xs)} X тикерів")
                time.sleep(pause)
                break

            except Exception as e:
                msg = str(e).lower()
                attempt += 1

                if "414" in msg or "uri too large" in msg or "request-uri too large" in msg:
                    new_bs = max(1, bs // 2)
                    if new_bs == bs:
                        if attempt >= max_retries:
                            print(
                                f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                                f"після {max_retries} 414-помилок. Помилка: {e}"
                            )
                            i += len(xs)
                            break
                    else:
                        print(
                            f"⚠️  414 на i={i}. Зменшую batch_size {bs} → {new_bs} "
                            f"і формую партію заново."
                        )
                        bs = new_bs
                        break
                else:
                    if attempt >= max_retries:
                        print(
                            f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                            f"після {max_retries} спроб. Помилка: {e}"
                        )
                        i += len(xs)
                        break
                    time.sleep(0.5 * attempt)

    df_all = pd.concat(results, ignore_index=True) if results else pd.DataFrame()

    # --- нормалізація назв колонок ---
    def _col(options, cols_lower):
        for c in options:
            if c.lower() in cols_lower:
                return next(cc for cc in df_all.columns if cc.lower() == c.lower())
        return None

    if df_all.empty:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return df_all, empty_pairs

    cols_lower = {c.lower() for c in df_all.columns}

    x_col    = _col(["x_ticker", "x", "ticker_x", "subject", "symbol_x"], cols_lower)
    y_col    = _col(["y_ticker", "y", "ticker_y", "benchmark", "symbol_y"], cols_lower)
    corr_col = _col(["corr", "correlation", "pearson_corr"], cols_lower)
    beta_col = _col(["beta", "beta_coeff"], cols_lower)

    missing = [
        name
        for name, val in [("x_ticker", x_col), ("y_ticker", y_col), ("corr", corr_col)]
        if val is None
    ]
    if missing:
        raise ValueError(
            f"Від API бракує очікуваних колонок: {', '.join(missing)}. "
            f"Є колонки: {list(df_all.columns)}"
        )

    # --- вибір найкращого Y для кожного X за corr ---
    df_sorted = df_all.sort_values(by=corr_col, ascending=False)
    idx_best = df_sorted.groupby(x_col, as_index=False)[corr_col].idxmax()[corr_col]
    df_best = df_sorted.loc[
        idx_best, [x_col, y_col, corr_col] + ([beta_col] if beta_col else [])
    ].copy()

    rename_map = {
        x_col: "x_ticker",
        y_col: "best_y_ticker",
        corr_col: "best_corr",
    }
    if beta_col:
        rename_map[beta_col] = "beta_with_best"
    df_pairs = df_best.rename(columns=rename_map)

    if "beta_with_best" not in df_pairs.columns:
        df_pairs["beta_with_best"] = pd.NA

    df_pairs = df_pairs[["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]]

    if output_path:
        df_pairs.to_csv(output_path, index=False)
        print(f"✅ Збережено {len(df_pairs)} пар у файл: {output_path}")

    return df_all, df_pairs

In [14]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    period="6 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
):
    """
    Створює два файли:
      1) output_path (за замовчуванням x_to_best_etf_by_lvl3.csv):
         x_ticker, best_y_ticker, best_corr, beta_with_best, lvl3

      2) bench_path (за замовчуванням ticker_bench.csv):
         ticker, benchmark

    Логіка:
      - Для кожного lvl3-сектора збираємо X-список тікерів.
      - Y-список ETF-ів беремо з sector_to_etf[lvl3].
      - Якщо сектору немає в мапі або список порожній → використовуємо fallback_etfs
        (за замовчуванням ["SPY", "QQQ", "IWM"]).
      - Для кожного тикера залишаємо ETF з максимальною кореляцією.
      - Тікери без lvl3 (NaN) обробляються як сектор 'UNKNOWN' з fallback ETF-ами.
    """

    import pandas as pd  # на випадок, якщо не імпортнуто вище

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]

    if sector_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{sector_col}'")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{ticker_col}'")

    # Беремо лише тикер і сектор, але НЕ дропаємо NaN — замінимо їх на 'UNKNOWN'
    df_clean = (
        tickers_df[[ticker_col, sector_col]]
        .drop_duplicates()
        .copy()
    )

    # 🔥 Тікери без сектора → 'UNKNOWN'
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)
    df_clean[ticker_col] = df_clean[ticker_col].astype(str)

    all_sectors = sorted(df_clean[sector_col].unique().tolist())

    all_chunks = []
    all_pairs = []
    sectors_with_fallback = []

    for sector in all_sectors:
        etfs = sector_to_etf.get(sector)

        if not etfs:
            etfs = list(fallback_etfs)
            sectors_with_fallback.append(sector)
            print(
                f"⚠️  Для сектора '{sector}' немає ETF-ів у sector_to_etf — "
                f"використовую fallback: {etfs}"
            )
        else:
            print(f"✅ lvl3: {sector} → ETF-и з мапи: {etfs}")

        x_tickers = (
            df_clean.loc[df_clean[sector_col] == sector, ticker_col]
            .astype(str)
            .unique()
            .tolist()
        )
        if not x_tickers:
            continue

        print(f"\n=== lvl3: {sector} | X-тикерів: {len(x_tickers)} | ETF-и: {etfs} ===")

        df_all_sec, df_pairs_sec = corr_beta_best_match_batched(
            x_tickers=x_tickers,
            y_tickers=etfs,
            period=period,
            as_pivot=as_pivot,
            fmt=fmt,
            batch_size=batch_size,
            pause=pause,
            max_retries=max_retries,
            output_path=None,   # тут не пишемо окремі файли
        )

        if not df_all_sec.empty:
            df_all_sec = df_all_sec.copy()
            df_all_sec[sector_col] = sector
            all_chunks.append(df_all_sec)

        if not df_pairs_sec.empty:
            df_pairs_sec = df_pairs_sec.copy()
            df_pairs_sec[sector_col] = sector
            all_pairs.append(df_pairs_sec)

    df_all = pd.concat(all_chunks, ignore_index=True) if all_chunks else pd.DataFrame()

    if all_pairs:
        df_pairs = pd.concat(all_pairs, ignore_index=True)

        # на випадок дублів по x_ticker — лишаємо найбільшу кореляцію
        df_pairs_sorted = df_pairs.sort_values(by="best_corr", ascending=False)
        idx_best = (
            df_pairs_sorted.groupby("x_ticker", as_index=False)["best_corr"]
            .idxmax()["best_corr"]
        )
        df_pairs = df_pairs_sorted.loc[idx_best].reset_index(drop=True)

        # ⚙️ детальний файл
        df_pairs.to_csv(output_path, index=False)
        print(f"\n✅ Збережено {len(df_pairs)} X→ETF пар у файл: {output_path}")

        # ⚙️ спрощений файл вигляду ticker,benchmark
        df_bench = df_pairs.rename(
            columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"}
        )[["ticker", "benchmark"]]

        df_bench.to_csv(bench_path, index=False)
        print(f"✅ Збережено {len(df_bench)} записів у файл: {bench_path}")

    else:
        df_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", sector_col]
        )
        df_pairs.to_csv(output_path, index=False)
        pd.DataFrame(columns=["ticker", "benchmark"]).to_csv(bench_path, index=False)
        print("\n⚠️ Не вдалося знайти жодної пари X→ETF. Створено порожні файли.")

    if sectors_with_fallback:
        print("\n⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):")
        for s in sectors_with_fallback:
            print("   -", s)

    return df_all, df_pairs

In [15]:
# нове: працюємо напряму з таблицею top1500 (ticker + lvl3)
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=top1500,          # DataFrame з колонками ticker, lvl3, ...
    sector_to_etf=sector_to_etf, # мапа lvl3 -> список ETF-ів
    sector_col="lvl3",           # Yазва колонки сектора в top1500
    ticker_col="ticker",         # назва колонки з тикером
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.1,
    max_retries=3,
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",  # детальна інфа
    bench_path=str(WORK_DIR / "ticker_bench_.csv")
            # простий файл ticker,benchmark
)

print(df_all.head())
print("Рядків у сирих даних:", len(df_all))
print(df_pairs.head())

✅ lvl3: Advertising & Marketing → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Advertising & Marketing | X-тикерів: 35 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[35/35] fetched batch of 35 X тикерів
✅ lvl3: Aerospace & Defense → ETF-и з мапи: ['IWM', 'SPY', 'QQQ']

=== lvl3: Aerospace & Defense | X-тикерів: 72 | ETF-и: ['IWM', 'SPY', 'QQQ'] ===

[72/72] fetched batch of 72 X тикерів
✅ lvl3: Apparel & Textile Products → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Apparel & Textile Products | X-тикерів: 34 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[34/34] fetched batch of 34 X тикерів
✅ lvl3: Asset Management → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Asset Management | X-тикерів: 193 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/193] fetched batch of 150 X тикерів

[193/193] fetched batch of 43 X тикерів
✅ lvl3: Automotive → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Automotive | X-тикерів: 72 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[72/72] fetched batch of 72 X тикерів
✅ lvl3: Banking → ETF-и з мапи: ['KRE', 'XLF', 'SPY', 'BITO']

=== lvl3: Banking | X-тикерів: 198 | ETF-и: ['KRE', 'XLF', 'SPY', 'BITO'] ===

[150/198] fetched batch of 150 X тикерів

[198/198] fetched batch of 48 X тикерів
✅ lvl3: Beverages → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Beverages | X-тикерів: 37 | ETF-и: ['SPY', 'IWM'] ===

[37/37] fetched batch of 37 X тикерів
✅ lvl3: Biotech & Pharma → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Biotech & Pharma | X-тикерів: 668 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/668] fetched batch of 150 X тикерів

[300/668] fetched batch of 150 X тикерів

[450/668] fetched batch of 150 X тикерів

[600/668] fetched batch of 150 X тикерів

[668/668] fetched batch of 68 X тикерів
✅ lvl3: Cable & Satellite → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Cable & Satellite | X-тикерів: 12 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[12/12] fetched batch of 12 X тикерів
✅ lvl3: Chemicals → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Chemicals | X-тикерів: 86 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[86/86] fetched batch of 86 X тикерів
✅ lvl3: Commercial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Commercial Support Services | X-тикерів: 109 | ETF-и: ['IWM', 'SPY'] ===

[109/109] fetched batch of 109 X тикерів
✅ lvl3: Construction Materials → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Construction Materials | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Consumer Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Consumer Services | X-тикерів: 39 | ETF-и: ['SPY', 'IWM'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: Containers & Packaging → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Containers & Packaging | X-тикерів: 19 | ETF-и: ['IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Diversified Industrials → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Diversified Industrials | X-тикерів: 7 | ETF-и: ['SPY', 'IWM'] ===

[7/7] fetched batch of 7 X тикерів
✅ lvl3: E-Commerce Discretionary → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: E-Commerce Discretionary | X-тикерів: 49 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[49/49] fetched batch of 49 X тикерів
✅ lvl3: Electric Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Electric Utilities | X-тикерів: 68 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[68/68] fetched batch of 68 X тикерів
✅ lvl3: Electrical Equipment → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Electrical Equipment | X-тикерів: 92 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[92/92] fetched batch of 92 X тикерів
✅ lvl3: Engineering & Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Engineering & Construction | X-тикерів: 52 | ETF-и: ['IWM', 'SPY'] ===

[52/52] fetched batch of 52 X тикерів
✅ lvl3: Entertainment Content → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Entertainment Content | X-тикерів: 43 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[43/43] fetched batch of 43 X тикерів
✅ lvl3: Food → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Food | X-тикерів: 68 | ETF-и: ['SPY', 'IWM'] ===

[68/68] fetched batch of 68 X тикерів
✅ lvl3: Forestry, Paper & Wood Products → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Forestry, Paper & Wood Products | X-тикерів: 10 | ETF-и: ['IWM', 'SPY'] ===

[10/10] fetched batch of 10 X тикерів
✅ lvl3: Gas & Water Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Gas & Water Utilities | X-тикерів: 23 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[23/23] fetched batch of 23 X тикерів
✅ lvl3: Health Care Facilities & Svcs → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Health Care Facilities & Svcs | X-тикерів: 98 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[98/98] fetched batch of 98 X тикерів
✅ lvl3: Home & Office Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Home & Office Products | X-тикерів: 20 | ETF-и: ['SPY', 'IWM'] ===

[20/20] fetched batch of 20 X тикерів
✅ lvl3: Home Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Home Construction | X-тикерів: 34 | ETF-и: ['IWM', 'SPY'] ===

[34/34] fetched batch of 34 X тикерів
✅ lvl3: Household Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Household Products | X-тикерів: 39 | ETF-и: ['SPY', 'IWM'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: IT Services → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: IT Services | X-тикерів: 67 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[67/67] fetched batch of 67 X тикерів
✅ lvl3: Industrial Intermediate Prod → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Intermediate Prod | X-тикерів: 20 | ETF-и: ['IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
✅ lvl3: Industrial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Support Services | X-тикерів: 29 | ETF-и: ['IWM', 'SPY'] ===

[29/29] fetched batch of 29 X тикерів
✅ lvl3: Institutional Financial Svcs → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Institutional Financial Svcs | X-тикерів: 39 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: Insurance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Insurance | X-тикерів: 86 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[86/86] fetched batch of 86 X тикерів
✅ lvl3: Internet Media & Services → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Internet Media & Services | X-тикерів: 107 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[107/107] fetched batch of 107 X тикерів
✅ lvl3: Leisure Facilities & Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Facilities & Services | X-тикерів: 112 | ETF-и: ['SPY', 'IWM'] ===

[112/112] fetched batch of 112 X тикерів
✅ lvl3: Leisure Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Products | X-тикерів: 32 | ETF-и: ['SPY', 'IWM'] ===

[32/32] fetched batch of 32 X тикерів
✅ lvl3: Machinery → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Machinery | X-тикерів: 77 | ETF-и: ['IWM', 'SPY'] ===

[77/77] fetched batch of 77 X тикерів
✅ lvl3: Medical Equipment & Devices → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Medical Equipment & Devices | X-тикерів: 203 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/203] fetched batch of 150 X тикерів

[203/203] fetched batch of 53 X тикерів
✅ lvl3: Metals & Mining → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Metals & Mining | X-тикерів: 150 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[150/150] fetched batch of 150 X тикерів
✅ lvl3: Oil & Gas Services & Equip → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Services & Equip | X-тикерів: 56 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[56/56] fetched batch of 56 X тикерів
✅ lvl3: Oil & Gas Supply Chain → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Supply Chain | X-тикерів: 139 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[139/139] fetched batch of 139 X тикерів
✅ lvl3: Publishing & Broadcasting → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Publishing & Broadcasting | X-тикерів: 19 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: REIT → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: REIT | X-тикерів: 133 | ETF-и: ['IWM', 'SPY'] ===

[133/133] fetched batch of 133 X тикерів
✅ lvl3: Real Estate Owners & Developers → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Owners & Developers | X-тикерів: 13 | ETF-и: ['IWM', 'SPY'] ===

[13/13] fetched batch of 13 X тикерів
✅ lvl3: Real Estate Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Services | X-тикерів: 18 | ETF-и: ['IWM', 'SPY'] ===

[18/18] fetched batch of 18 X тикерів
✅ lvl3: Renewable Energy → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Renewable Energy | X-тикерів: 57 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[57/57] fetched batch of 57 X тикерів
✅ lvl3: Retail - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Retail - Consumer Staples | X-тикерів: 25 | ETF-и: ['SPY', 'IWM'] ===

[25/25] fetched batch of 25 X тикерів
✅ lvl3: Retail - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Retail - Discretionary | X-тикерів: 101 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[101/101] fetched batch of 101 X тикерів
✅ lvl3: Semiconductors → ETF-и з мапи: ['SOXL', 'QQQ', 'IWM', 'SPY']

=== lvl3: Semiconductors | X-тикерів: 103 | ETF-и: ['SOXL', 'QQQ', 'IWM', 'SPY'] ===

[103/103] fetched batch of 103 X тикерів
✅ lvl3: Software → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Software | X-тикерів: 323 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/323] fetched batch of 150 X тикерів

[300/323] fetched batch of 150 X тикерів

[323/323] fetched batch of 23 X тикерів
✅ lvl3: Specialty Finance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Specialty Finance | X-тикерів: 172 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/172] fetched batch of 150 X тикерів

[172/172] fetched batch of 22 X тикерів
✅ lvl3: Steel → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Steel | X-тикерів: 19 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Technology Hardware → ETF-и з мапи: ['QQQ', 'SOXL', 'IWM', 'SPY']

=== lvl3: Technology Hardware | X-тикерів: 136 | ETF-и: ['QQQ', 'SOXL', 'IWM', 'SPY'] ===

[136/136] fetched batch of 136 X тикерів
✅ lvl3: Telecommunications → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Telecommunications | X-тикерів: 41 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[41/41] fetched batch of 41 X тикерів
✅ lvl3: Tobacco & Cannabis → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Tobacco & Cannabis | X-тикерів: 19 | ETF-и: ['SPY', 'IWM'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Transportation & Logistics → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation & Logistics | X-тикерів: 124 | ETF-и: ['IWM', 'SPY'] ===

[124/124] fetched batch of 124 X тикерів
✅ lvl3: Transportation Equipment → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation Equipment | X-тикерів: 20 | ETF-и: ['IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
⚠️  Для сектора 'UNKNOWN' немає ETF-ів у sector_to_etf — використовую fallback: ['SPY', 'QQQ', 'IWM']

=== lvl3: UNKNOWN | X-тикерів: 2052 | ETF-и: ['SPY', 'QQQ', 'IWM'] ===

[150/2052] fetched batch of 150 X тикерів

[300/2052] fetched batch of 150 X тикерів

[450/2052] fetched batch of 150 X тикерів

[600/2052] fetched batch of 150 X тикерів

[750/2052] fetched batch of 150 X тикерів

[900/2052] fetched batch of 150 X тикерів

[1050/2052] fetched batch of 150 X тикерів

[1200/2052] fetched batch of 150 X тикерів

[1350/2052] fetched batch of 150 X тикерів

[1500/2052] fetched batch of 150 X тикерів

[1650/2052] fetched batch of 150 X тикерів

[1800/2052] fetched batch of 150 X тикерів

[1950/2052] fetched batch of 150 X тикерів

[2052/2052] fetched batch of 102 X тикерів
✅ lvl3: Wholesale - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Wholesale - Consumer Staples | X-тикерів: 13 | ETF-и: ['SPY', 'IWM'] ===

[13/13] fetched batch of 13 X тикерів
✅ lvl3: Wholesale - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Wholesale - Discretionary | X-тикерів: 14 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[14/14] fetched batch of 14 X тикерів

✅ Збережено 6538 X→ETF пар у файл: CRACEN/work/x_to_best_etf_by_lvl3.csv
✅ Збережено 6538 записів у файл: C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv

⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):
   - UNKNOWN
  x_ticker y_ticker  corr  beta                     lvl3
0      ADV      SPY  0.68  0.84  Advertising & Marketing
1      ADV      IWM  0.57  0.41  Advertising & Marketing
2      ADV      QQQ  0.45  0.02  Advertising & Marketing
3      ADV     KWEB -0.04  0.00  Advertising & Marketing
4      APP      SPY  0.88  2.55  Advertising & Marketing
Рядків у сирих даних: 19251
  x_ticker best_y_ticker  best_corr  beta_with_best  \
0        A           SPY       0.67            0.64
1       AA           GDX       0.80            0.58
2     AAAU           IWM       0.33            0.89
3     AACG           QQQ       0.04           -0.40
4      AAL           SPY       0.83            1.57

                          lvl3
0  Medical Equipment & Devices
1              Metals & Mining
2                      UNKNOWN
3                     Software
4   Transportation & Logistics

In [16]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [17]:
top1500

,ticker,value,lvl3,country,exchange,market_cap
0,A,61531.01,Medical Equipment & Devices,UNITED STATES,New York,34760.0
1,AA,1528436.53,Metals & Mining,UNITED STATES,New York,15664.0
2,AAAU,1143065.63,NaN,NaN,NaN,NaN
3,AACG,11.34,Software,UNITED STATES,NASDAQ CM,29.0
4,AACOU,10682.86,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
6712,ZWS,230.95,Machinery,UNITED STATES,New York,8481.0
6713,ZYBT,40.80,Biotech & Pharma,UNITED STATES,NASDAQ CM,41.0
6714,ZYME,33950.80,Biotech & Pharma,UNITED STATES,NASDAQ GS,1713.0
6715,ZYXI,9329.50,NaN,NaN,NaN,NaN
6716,ZYXIQ,9329.50,NaN,NaN,NaN,NaN

In [18]:
import pandas as pd

# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

  ticker
0    SPY
1    IWM
2    GDX
3    XLF
4    QQQ
5    XLE
6    KRE
7   BITO
8   KWEB
9   SOXL

In [19]:
# keep = ["ticker","dt","o","h","l","c","v"]

# errs = fetch_intraday_v3_for_all_tickers(
#     tickers_df=top1500,
#     start= start,
#     end= end,
#     interval=1,
#     chunk_days=30,
#     parallel_chunks=True,
#     max_workers_chunks=6,
#     parallel_tickers=True,
#     max_workers_tickers=1,
#     save_every=50,
#     out_dir=str(BATCH_DIR),
#     out_prefix="intraday",
#     gzip=True,
#     keep_columns=keep,
#     verbose=True,
#     include_blue_ocean=True,
# )

In [20]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [21]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2025-11-21..2026-02-21]

  [1/268] intraday_0001.csv.gz chunk 5  in=750,000  out=518,785  elapsed=1.4s

  [2/268] intraday_0002.csv.gz chunk 5  in=1,725,827  out=1,217,150  elapsed=3.0s

  [3/268] intraday_0003.csv.gz chunk 5  in=2,590,424  out=1,840,686  elapsed=4.2s

  [4/268] intraday_0004.csv.gz chunk 5  in=3,333,452  out=2,372,423  elapsed=5.4s

  [5/268] intraday_0005.csv.gz chunk 5  in=4,083,452  out=2,899,234  elapsed=6.4s

  [6/268] intraday_0006.csv.gz chunk 5  in=4,957,443  out=3,509,024  elapsed=7.7s

  [7/268] intraday_0007.csv.gz chunk 5  in=5,912,526  out=4,175,719  elapsed=9.0s

  [8/268] intraday_0008.csv.gz chunk 5  in=6,673,107  out=4,708,466  elapsed=10.1s

  [9/268] intraday_0009.csv.gz chunk 5  in=7,482,671  out=5,268,150  elapsed=11.3s

  [10/268] intraday_0010.csv.gz chunk 5  in=8,422,497  out=5,935,561  elapsed=12.6s

  [11/268] intraday_0011.csv.gz chunk 5  in=9,348,724  out=6,611,855  elapsed=14.0s

  [12/268] intraday_0012.csv.gz chunk 5  in=10,098,724  out=7,151,207  elapsed=15.1s

  [13/268] intraday_0013.csv.gz chunk 5  in=10,952,410  out=7,749,826  elapsed=16.3s

  [14/268] intraday_0014.csv.gz chunk 5  in=11,729,573  out=8,305,460  elapsed=17.4s

  [15/268] intraday_0015.csv.gz chunk 5  in=12,333,647  out=8,737,048  elapsed=18.3s

  [16/268] intraday_0016.csv.gz chunk 5  in=13,083,647  out=9,260,873  elapsed=19.4s

  [17/268] intraday_0017.csv.gz chunk 5  in=14,119,434  out=9,972,395  elapsed=20.8s

  [18/268] intraday_0018.csv.gz chunk 5  in=14,987,474  out=10,619,529  elapsed=22.1s

  [19/268] intraday_0019.csv.gz chunk 5  in=15,723,943  out=11,129,824  elapsed=23.1s

  [20/268] intraday_0020.csv.gz chunk 5  in=16,473,943  out=11,647,051  elapsed=24.2s

  [21/268] intraday_0021.csv.gz chunk 5  in=17,305,781  out=12,233,642  elapsed=25.4s

  [22/268] intraday_0022.csv.gz chunk 5  in=18,114,555  out=12,804,378  elapsed=26.5s

  [23/268] intraday_0023.csv.gz chunk 5  in=18,864,555  out=13,324,313  elapsed=27.6s

  [24/268] intraday_0024.csv.gz chunk 5  in=19,645,557  out=13,887,073  elapsed=28.7s

  [25/268] intraday_0025.csv.gz chunk 5  in=20,416,242  out=14,424,223  elapsed=29.8s

  [26/268] intraday_0026.csv.gz chunk 5  in=21,166,242  out=14,938,375  elapsed=30.9s

  [27/268] intraday_0027.csv.gz chunk 5  in=21,935,669  out=15,484,806  elapsed=32.0s

  [28/268] intraday_0028.csv.gz chunk 5  in=22,685,669  out=16,014,929  elapsed=33.1s

  [29/268] intraday_0029.csv.gz chunk 5  in=23,693,087  out=16,732,571  elapsed=34.5s

  [30/268] intraday_0030.csv.gz chunk 5  in=24,639,604  out=17,395,912  elapsed=35.9s

  [31/268] intraday_0031.csv.gz chunk 5  in=25,543,444  out=18,031,759  elapsed=37.2s

  [32/268] intraday_0032.csv.gz chunk 5  in=26,293,444  out=18,555,213  elapsed=38.2s

  [33/268] intraday_0033.csv.gz chunk 5  in=27,109,346  out=19,120,258  elapsed=39.3s

  [34/268] intraday_0034.csv.gz chunk 5  in=27,922,589  out=19,691,735  elapsed=40.5s

  [35/268] intraday_0035.csv.gz chunk 5  in=28,672,589  out=20,220,420  elapsed=41.5s

  [36/268] intraday_0036.csv.gz chunk 5  in=29,491,745  out=20,810,129  elapsed=42.7s

  [37/268] intraday_0037.csv.gz chunk 5  in=30,234,721  out=21,329,686  elapsed=43.8s

  [38/268] intraday_0038.csv.gz chunk 5  in=30,924,778  out=21,818,574  elapsed=44.8s

  [39/268] intraday_0039.csv.gz chunk 5  in=31,674,778  out=22,338,957  elapsed=45.8s

  [40/268] intraday_0040.csv.gz chunk 5  in=32,407,718  out=22,841,279  elapsed=46.8s

  [41/268] intraday_0041.csv.gz chunk 5  in=33,157,718  out=23,355,405  elapsed=47.9s

  [42/268] intraday_0042.csv.gz chunk 5  in=34,051,794  out=23,995,359  elapsed=49.1s

  [43/268] intraday_0043.csv.gz chunk 5  in=34,960,739  out=24,633,971  elapsed=50.4s

  [44/268] intraday_0044.csv.gz chunk 5  in=35,710,739  out=25,160,101  elapsed=51.5s

  [45/268] intraday_0045.csv.gz chunk 5  in=36,516,274  out=25,719,397  elapsed=52.7s

  [46/268] intraday_0046.csv.gz chunk 5  in=37,318,713  out=26,278,000  elapsed=53.8s

  [47/268] intraday_0047.csv.gz chunk 5  in=38,133,804  out=26,850,397  elapsed=55.0s

  [48/268] intraday_0048.csv.gz chunk 5  in=38,906,436  out=27,397,918  elapsed=56.1s

  [49/268] intraday_0049.csv.gz chunk 5  in=39,656,436  out=27,932,649  elapsed=57.2s

  [50/268] intraday_0050.csv.gz chunk 5  in=40,601,960  out=28,599,210  elapsed=58.6s

  [51/268] intraday_0051.csv.gz chunk 5  in=41,414,383  out=29,179,475  elapsed=59.8s

  [52/268] intraday_0052.csv.gz chunk 5  in=42,164,383  out=29,704,468  elapsed=60.8s

  [53/268] intraday_0053.csv.gz chunk 5  in=42,998,896  out=30,295,846  elapsed=62.0s

  [54/268] intraday_0054.csv.gz chunk 5  in=43,729,514  out=30,805,945  elapsed=63.1s

  [55/268] intraday_0055.csv.gz chunk 5  in=44,479,514  out=31,321,047  elapsed=64.1s

  [56/268] intraday_0056.csv.gz chunk 5  in=45,292,383  out=31,887,964  elapsed=65.3s

  [57/268] intraday_0057.csv.gz chunk 5  in=46,110,329  out=32,471,223  elapsed=66.5s

  [58/268] intraday_0058.csv.gz chunk 5  in=46,830,377  out=32,988,512  elapsed=67.6s

  [59/268] intraday_0059.csv.gz chunk 5  in=47,580,377  out=33,520,550  elapsed=68.6s

  [60/268] intraday_0060.csv.gz chunk 5  in=48,264,439  out=34,008,280  elapsed=69.6s

  [61/268] intraday_0061.csv.gz chunk 5  in=49,014,439  out=34,537,099  elapsed=70.8s

  [62/268] intraday_0062.csv.gz chunk 5  in=50,022,323  out=35,249,473  elapsed=72.2s

  [63/268] intraday_0063.csv.gz chunk 5  in=50,772,323  out=35,794,451  elapsed=73.3s

  [64/268] intraday_0064.csv.gz chunk 5  in=51,725,856  out=36,470,814  elapsed=74.7s

  [65/268] intraday_0065.csv.gz chunk 5  in=52,611,073  out=37,108,343  elapsed=76.0s

  [66/268] intraday_0066.csv.gz chunk 5  in=53,344,110  out=37,629,210  elapsed=77.1s

  [67/268] intraday_0067.csv.gz chunk 5  in=54,094,110  out=38,161,889  elapsed=78.2s

  [68/268] intraday_0068.csv.gz chunk 5  in=54,864,222  out=38,709,165  elapsed=79.3s

  [69/268] intraday_0069.csv.gz chunk 5  in=55,688,820  out=39,281,345  elapsed=80.5s

  [70/268] intraday_0070.csv.gz chunk 5  in=56,497,048  out=39,851,838  elapsed=81.7s

  [71/268] intraday_0071.csv.gz chunk 5  in=57,135,058  out=40,286,512  elapsed=82.6s

  [72/268] intraday_0072.csv.gz chunk 5  in=57,879,667  out=40,808,464  elapsed=83.6s

  [73/268] intraday_0073.csv.gz chunk 5  in=58,629,667  out=41,341,937  elapsed=84.7s

  [74/268] intraday_0074.csv.gz chunk 5  in=59,409,405  out=41,887,925  elapsed=85.9s

  [75/268] intraday_0075.csv.gz chunk 5  in=60,159,405  out=42,409,547  elapsed=86.9s

  [76/268] intraday_0076.csv.gz chunk 5  in=60,866,670  out=42,914,796  elapsed=88.0s

  [77/268] intraday_0077.csv.gz chunk 5  in=61,616,670  out=43,441,097  elapsed=89.1s

  [78/268] intraday_0078.csv.gz chunk 5  in=62,426,095  out=43,988,186  elapsed=90.2s

  [79/268] intraday_0079.csv.gz chunk 5  in=63,486,689  out=44,730,412  elapsed=91.8s

  [80/268] intraday_0080.csv.gz chunk 5  in=64,355,814  out=45,350,621  elapsed=93.1s

  [81/268] intraday_0081.csv.gz chunk 5  in=65,105,814  out=45,884,325  elapsed=94.2s

  [82/268] intraday_0082.csv.gz chunk 5  in=65,923,353  out=46,459,034  elapsed=95.4s

  [83/268] intraday_0083.csv.gz chunk 5  in=66,712,271  out=47,011,829  elapsed=96.5s

  [84/268] intraday_0084.csv.gz chunk 5  in=67,498,390  out=47,550,064  elapsed=97.7s

  [85/268] intraday_0085.csv.gz chunk 5  in=68,668,886  out=48,374,941  elapsed=99.4s

  [86/268] intraday_0086.csv.gz chunk 5  in=69,443,048  out=48,931,542  elapsed=100.6s

  [87/268] intraday_0087.csv.gz chunk 5  in=70,370,846  out=49,596,127  elapsed=101.9s

  [88/268] intraday_0088.csv.gz chunk 5  in=71,314,187  out=50,279,677  elapsed=103.3s

  [89/268] intraday_0089.csv.gz chunk 5  in=72,147,243  out=50,885,260  elapsed=104.5s

  [90/268] intraday_0090.csv.gz chunk 5  in=73,031,904  out=51,515,853  elapsed=105.8s

  [91/268] intraday_0091.csv.gz chunk 5  in=73,819,473  out=52,069,802  elapsed=106.9s

  [92/268] intraday_0092.csv.gz chunk 5  in=74,749,201  out=52,724,851  elapsed=108.3s

  [93/268] intraday_0093.csv.gz chunk 5  in=75,581,839  out=53,310,083  elapsed=109.5s

  [94/268] intraday_0094.csv.gz chunk 5  in=76,397,498  out=53,879,630  elapsed=110.6s

  [95/268] intraday_0095.csv.gz chunk 5  in=77,278,738  out=54,490,845  elapsed=111.9s

  [96/268] intraday_0096.csv.gz chunk 5  in=78,128,774  out=55,077,981  elapsed=113.1s

  [97/268] intraday_0097.csv.gz chunk 5  in=79,010,543  out=55,681,968  elapsed=114.4s

  [98/268] intraday_0098.csv.gz chunk 5  in=79,782,923  out=56,235,066  elapsed=115.5s

  [99/268] intraday_0099.csv.gz chunk 5  in=80,552,827  out=56,775,404  elapsed=116.7s

  [100/268] intraday_0100.csv.gz chunk 5  in=81,613,945  out=57,536,103  elapsed=118.2s

  [101/268] intraday_0101.csv.gz chunk 5  in=82,411,660  out=58,089,167  elapsed=119.4s

  [102/268] intraday_0102.csv.gz chunk 5  in=83,343,388  out=58,760,755  elapsed=120.7s

  [103/268] intraday_0103.csv.gz chunk 5  in=84,277,121  out=59,413,450  elapsed=122.1s

  [104/268] intraday_0104.csv.gz chunk 5  in=85,067,945  out=59,970,430  elapsed=123.2s

  [105/268] intraday_0105.csv.gz chunk 5  in=85,909,844  out=60,581,741  elapsed=124.5s

  [106/268] intraday_0106.csv.gz chunk 5  in=86,782,104  out=61,199,276  elapsed=125.7s

  [107/268] intraday_0107.csv.gz chunk 5  in=87,571,848  out=61,758,432  elapsed=126.9s

  [108/268] intraday_0108.csv.gz chunk 5  in=88,635,246  out=62,512,109  elapsed=128.5s

  [109/268] intraday_0109.csv.gz chunk 5  in=89,429,847  out=63,056,244  elapsed=129.7s

  [110/268] intraday_0110.csv.gz chunk 5  in=90,369,231  out=63,718,623  elapsed=131.1s

  [111/268] intraday_0111.csv.gz chunk 5  in=91,390,909  out=64,417,455  elapsed=132.5s

  [112/268] intraday_0112.csv.gz chunk 5  in=92,177,941  out=64,978,651  elapsed=133.7s

  [113/268] intraday_0113.csv.gz chunk 5  in=93,009,949  out=65,564,727  elapsed=134.8s

  [114/268] intraday_0114.csv.gz chunk 5  in=93,772,660  out=66,099,107  elapsed=135.9s

  [115/268] intraday_0115.csv.gz chunk 5  in=94,609,984  out=66,693,347  elapsed=137.1s

  [116/268] intraday_0116.csv.gz chunk 5  in=95,366,153  out=67,225,976  elapsed=138.3s

  [117/268] intraday_0117.csv.gz chunk 5  in=96,314,921  out=67,901,991  elapsed=139.6s

  [118/268] intraday_0118.csv.gz chunk 5  in=97,100,237  out=68,453,117  elapsed=140.8s

  [119/268] intraday_0119.csv.gz chunk 5  in=98,245,742  out=69,267,088  elapsed=142.5s

  [120/268] intraday_0120.csv.gz chunk 5  in=98,995,742  out=69,799,474  elapsed=143.6s

  [121/268] intraday_0121.csv.gz chunk 5  in=99,855,343  out=70,388,255  elapsed=144.8s

  [122/268] intraday_0122.csv.gz chunk 5  in=100,900,376  out=71,124,022  elapsed=146.3s

  [123/268] intraday_0123.csv.gz chunk 5  in=101,688,876  out=71,683,494  elapsed=147.4s

  [124/268] intraday_0124.csv.gz chunk 5  in=102,540,604  out=72,281,307  elapsed=148.6s

  [125/268] intraday_0125.csv.gz chunk 5  in=103,517,055  out=72,976,356  elapsed=150.0s

  [126/268] intraday_0126.csv.gz chunk 5  in=104,398,833  out=73,598,302  elapsed=151.3s

  [127/268] intraday_0127.csv.gz chunk 5  in=105,314,012  out=74,249,753  elapsed=152.7s

  [128/268] intraday_0128.csv.gz chunk 5  in=106,064,012  out=74,778,532  elapsed=153.7s

  [129/268] intraday_0129.csv.gz chunk 5  in=106,816,285  out=75,291,509  elapsed=154.8s

  [130/268] intraday_0130.csv.gz chunk 5  in=107,676,182  out=75,894,551  elapsed=156.0s

  [131/268] intraday_0131.csv.gz chunk 5  in=108,498,465  out=76,488,243  elapsed=157.2s

  [132/268] intraday_0132.csv.gz chunk 5  in=109,165,533  out=76,937,658  elapsed=158.2s

  [133/268] intraday_0133.csv.gz chunk 5  in=109,915,533  out=77,463,344  elapsed=159.3s

✅ DONE  in=111,978,303 → out=79,478,082  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 165.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [22]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [23]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [24]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [25]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=26.0s

[batch   10] rows=20,000,000  elapsed=51.8s

[batch   15] rows=30,000,000  elapsed=77.8s

[batch   20] rows=40,000,000  elapsed=104.1s

[batch   25] rows=50,000,000  elapsed=130.8s

[batch   30] rows=60,000,000  elapsed=157.5s

[batch   35] rows=70,000,000  elapsed=184.2s

[batch   40] rows=79,478,082  elapsed=210.0s
✅ DONE  rows=79,478,082  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 210.1s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [26]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [27]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=4.7s

[batch   10] rows=20,000,000  elapsed=9.3s

[batch   15] rows=30,000,000  elapsed=14.1s

[batch   20] rows=40,000,000  elapsed=18.8s

[batch   25] rows=50,000,000  elapsed=23.4s

[batch   30] rows=60,000,000  elapsed=28.1s

[batch   35] rows=70,000,000  elapsed=32.9s

[batch   40] rows=79,478,082  elapsed=37.3s
✅ DONE  rows=79,478,082  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 37.3s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [28]:
import os, re, time, math
import pandas as pd
from typing import Dict, List, Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


# ---------- НАДІЙНЕ ЧИТАННЯ МАПІНГУ (ticker, bench) ----------

def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Читає файл з відповідностями тікер↔бенч. Підтримка:
      - CSV (роздільник ; або , або \t), з/без заголовка
      - XLSX
      - Випадок "все в одній колонці": 'AAPL;SPY' / 'AAPL,SPY'
    Повертає DF: ['ticker','bench'] (UPPER, без дублікатів).
    """
    p = mapping_path
    ext = os.path.splitext(p)[1].lower()

    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(p)
    else:
        # 1) спроба autodetect
        try:
            df = pd.read_csv(p, sep=None, engine="python")
        except Exception:
            # 2) спроби з явними роздільниками
            for sep_try in (";", ",", "\t", "|"):
                try:
                    df = pd.read_csv(p, sep=sep_try, engine="python")
                    break
                except Exception:
                    df = None
            if df is None:
                # 3) можливо, файл без заголовка
                try:
                    df = pd.read_csv(p, header=None, sep=None, engine="python")
                except Exception:
                    # 4) остання спроба — явні сепаратори без заголовка
                    for sep_try in (";", ",", "\t", "|"):
                        try:
                            df = pd.read_csv(p, header=None, sep=sep_try, engine="python")
                            break
                        except Exception:
                            df = None
                    if df is None:
                        raise

    # Якщо одна колонка і виглядає як "AAPL;SPY" — сплітимо
    if df.shape[1] == 1:
        col = df.columns[0]
        # намагаємось розбити за ; або , або \t
        s = df[col].astype(str)
        if s.str.contains(";").any():
            parts = s.str.split(";", n=1, expand=True)
        elif s.str.contains(",").any():
            parts = s.str.split(",", n=1, expand=True)
        elif s.str.contains("\t").any():
            parts = s.str.split("\t", n=1, expand=True)
        else:
            raise KeyError("Не можу знайти роздільник між 'ticker' і 'bench'.")
        df = pd.DataFrame({"ticker": parts[0], "bench": parts[1]})

    # Вгадуємо назви колонок
    cols = {c.lower(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol")
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf")

    # Якщо заголовків нема, але 2 колонки — приймаємо їх як ticker/bench
    if tcol is None or bcol is None:
        if df.shape[1] >= 2:
            tcol = df.columns[0]
            bcol = df.columns[1]
        else:
            raise KeyError("Потрібні колонки 'ticker' і 'bench' у mapping-файлі.")

    out = (
        df[[tcol, bcol]]
        .rename(columns={tcol: "ticker", bcol: "bench"})
        .dropna()
    )
    out["ticker"] = out["ticker"].astype(str).str.strip().str.upper()
    out["bench"]  = out["bench"].astype(str).str.strip().str.upper()
    out = out[out["ticker"] != ""]
    out = out[out["bench"]  != ""]
    return out.drop_duplicates(ignore_index=True)


# ---------- ВИТЯГ corr/beta ДЛЯ ПАР (X, ФІКСОВАНИЙ BENCH) ----------

def _fetch_corr_beta_pairs(
    x_list: List[str],
    bench: str,
    *,
    period: str = "6 months",
    fmt: str = "json_records",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> pd.DataFrame:
    results: List[pd.DataFrame] = []
    i, n = 0, len(x_list)
    b = bench

    while i < n:
        cur_bs = min(batch_size, n - i)
        attempt = 0
        while True:
            xs = x_list[i : i + cur_bs]
            params = {
                "x_tickers": ",".join(xs),
                "y_tickers": b,
                "period": period,
                "as_pivot": False,
                "format": fmt,
            }
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)
                if df_chunk is not None and not df_chunk.empty:
                    # лишаємо тільки рядки для потрібного bench (на випадок, якщо API поверне зайве)
                    if "y_ticker" in df_chunk.columns:
                        df_chunk = df_chunk[df_chunk["y_ticker"].astype(str).str.upper() == b]
                    results.append(df_chunk)
                i += len(xs)
                time.sleep(pause)  # пауза тільки після успішного батча
                break
            except Exception as e:
                msg = str(e).lower()
                # 414: зменшуємо ЛИШЕ поточний батч
                if "414" in msg or "uri too large" in msg:
                    if cur_bs <= min_batch_size:
                        print(f"⚠️ 414 навіть при batch={cur_bs}. Пропускаю X[{i}:{i+cur_bs}] для {b}.")
                        i += cur_bs
                        break
                    new_bs = max(min_batch_size, cur_bs // 2)
                    print(f"⚠️ 414 → shrink {cur_bs} → {new_bs} для {b} і повторюю.")
                    cur_bs = new_bs
                    continue

                attempt += 1
                if attempt > max_retries:
                    print(f"⚠️  Пропуск X[{i}:{i+cur_bs}] для {b} після {max_reTRIES} ретраїв. Помилка: {e}")
                    i += cur_bs
                    break
                sleep_s = retry_backoff * (2 ** (attempt - 1))
                print(f"⚠️  {e} → retry {attempt}/{max_retries} через {sleep_s:.1f}s")
                time.sleep(sleep_s)

    return pd.concat(results, ignore_index=True) if results else pd.DataFrame()


# ---------- ГОЛОВНА ФУНКЦІЯ ----------

def corr_beta_from_mapping_to_parquet(
    mapping_path: str,
    out_parquet_path: str,
    *,
    period: str = "3 months",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> str:
    """
    Читає mapping (ticker, bench) будь-якого адекватного формату,
    групує тікери по бенчу, витягує corr/beta для кожної групи
    і потоково пише результат у Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для запису .parquet")

    map_df = _read_mapping(mapping_path)

    groups: Dict[str, List[str]] = (
        map_df.groupby("bench")["ticker"].apply(lambda s: sorted(set(s.tolist()))).to_dict()
    )

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    writer: Optional[pq.ParquetWriter] = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START corr/beta → {out_parquet_path} | період={period} | бенчів={len(groups)}")

    for b, xs in sorted(groups.items()):
        if not xs:
            continue
        print(f"— Bench {b}: {len(xs)} тикерів")
        df_b = _fetch_corr_beta_pairs(
            xs, b,
            period=period,
            batch_size=batch_size,
            min_batch_size=min_batch_size,
            pause=pause,
            max_retries=max_retries,
            retry_backoff=retry_backoff,
        )
        if df_b is None or df_b.empty:
            continue

        # типи
        for col in ("corr", "beta"):
            if col in df_b.columns:
                df_b[col] = pd.to_numeric(df_b[col], errors="coerce")

        table = pa.Table.from_pandas(df_b, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression="snappy")
        writer.write_table(table)
        total_rows += len(df_b)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path

In [29]:
out_path = corr_beta_from_mapping_to_parquet(
    mapping_path=str(WORK_DIR / "ticker_bench_.csv"),
    out_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    period="3 months",
    batch_size=150,
    pause=0.15,
)
print("Результат:", out_path)

▶️ START corr/beta → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet | період=3 months | бенчів=10
— Bench BITO: 60 тикерів

— Bench GDX: 124 тикерів

— Bench IWM: 2421 тикерів

— Bench KRE: 133 тикерів

— Bench KWEB: 47 тикерів

— Bench QQQ: 543 тикерів

— Bench SOXL: 33 тикерів

— Bench SPY: 2740 тикерів

— Bench XLE: 179 тикерів

— Bench XLF: 257 тикерів

✅ DONE rows=6,537 → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet  in 18.5s
Результат: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [30]:

y_list = ["SPY", "IWM", "GDX", "XLF", "QQQ", "XLE", "KRE", "BITO", "SOXL"]

In [31]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [32]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=9.2s

[batch   10] rows=20,000,000  elapsed=18.3s

[batch   15] rows=30,000,000  elapsed=27.4s

[batch   20] rows=40,000,000  elapsed=36.6s

[batch   25] rows=50,000,000  elapsed=45.8s

[batch   30] rows=60,000,000  elapsed=54.9s

[batch   35] rows=70,000,000  elapsed=64.1s

[batch   40] rows=79,478,082  elapsed=72.8s
✅ DONE rows=79,478,082 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 72.8s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [33]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [34]:
peek_parquet("CRACEN/work/premarket_rows_final.parquet", n=620)

Файл: CRACEN/work/premarket_rows_final.parquet
Рядків (meta): 79,478,082
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:
    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench  corr  beta
0        A 2025-11-21 00:45:00  145.830002  145.830002  145.830002  145.830002       9.0  2025-11-21  144.47      145.06    0.53   SPY  0.67  0.64
1        A 2025-11-21 01:50:00  145.800003  145.800003  145.800003  145.800003       5.0  2025-11-21  144.47      145.06    0.51   SPY  0.67  0.64
2        A 2025-11-21 02:00:00  145.809998  145.809998  145.809998  145.809998       5.0  2025-11-21  144.47      145.06    0.52   SPY  0.67  0.64
3        A 2025-11-21 09:30:00  144.470001  145.375000  144.470001  144.645004   84953.0  2025-11-21  144.47      145.06   -0.41   SPY  0.67  0.64
4        A 2025-11-21 09:31:00  144.645004  144.645004  144.645004  144.645004    2500.0  2025-11-21  144.47      145.06   -0.29   SPY  0.67  0.64
5        A 2025-11-21 09:32:00  145.000000  145.410004  144.949997  145.054993     891.0  2025-11-21  144.47      145.06   -0.04   SPY  0.67  0.64
6        A 2025-11-21 09:34:00  145.820007  146.050003  145.630005  146.039993   41022.0  2025-11-21  144.47      145.06    0.52   SPY  0.67  0.64
7        A 2025-11-21 09:35:00  145.889999  145.910004  145.679993  145.679993    1039.0  2025-11-21  144.47      145.06    0.57   SPY  0.67  0.64
8        A 2025-11-21 09:36:00  145.639999  146.130005  145.559998  146.130005    1206.0  2025-11-21  144.47      145.06    0.40   SPY  0.67  0.64
9        A 2025-11-21 09:37:00  146.100006  146.360001  146.100006  146.360001     500.0  2025-11-21  144.47      145.06    0.72   SPY  0.67  0.64
10       A 2025-11-21 09:39:00  146.330002  146.360001  145.940002  145.979996   12264.0  2025-11-21  144.47      145.06    0.88   SPY  0.67  0.64
11       A 2025-11-21 09:40:00  145.929993  145.929993  145.830002  145.830002     300.0  2025-11-21  144.47      145.06    0.60   SPY  0.67  0.64
12       A 2025-11-21 09:41:00  145.990005  145.990005  145.990005  145.990005     100.0  2025-11-21  144.47      145.06    0.64   SPY  0.67  0.64
13       A 2025-11-21 09:42:00  145.979996  146.039993  145.809998  145.910004    2181.0  2025-11-21  144.47      145.06    0.63   SPY  0.67  0.64
14       A 2025-11-21 09:43:00  146.039993  146.039993  145.919998  145.919998     813.0  2025-11-21  144.47      145.06    0.68   SPY  0.67  0.64
15       A 2025-11-21 09:44:00  145.860001  146.119995  145.860001  146.080002    2827.0  2025-11-21  144.47      145.06    0.55   SPY  0.67  0.64
16       A 2025-11-21 09:45:00  146.130005  146.270004  146.095001  146.270004    1216.0  2025-11-21  144.47      145.06    0.74   SPY  0.67  0.64
17       A 2025-11-21 09:46:00  146.279999  146.360001  146.080002  146.214996    3905.0  2025-11-21  144.47      145.06    0.84   SPY  0.67  0.64
18       A 2025-11-21 09:47:00  146.255005  146.259995  145.979996  146.229996   20366.0  2025-11-21  144.47      145.06    0.82   SPY  0.67  0.64
19       A 2025-11-21 09:48:00  146.479996  146.820007  146.470001  146.514999    1940.0  2025-11-21  144.47      145.06    0.98   SPY  0.67  0.64
20       A 2025-11-21 09:49:00  146.520004  146.520004  146.309998  146.429993     496.0  2025-11-21  144.47      145.06    1.01   SPY  0.67  0.64
21       A 2025-11-21 09:50:00  146.384995  146.500000  146.315002  146.470001    1400.0  2025-11-21  144.47      145.06    0.91   SPY  0.67  0.64
22       A 2025-11-21 09:51:00  146.380005  146.380005  146.274994  146.274994     700.0  2025-11-21  144.47      145.06    0.91   SPY  0.67  0.64
23       A 2025-11-21 09:52:00  146.199997  146.479996  146.164993  146.360001    2367.0  2025-11-21  144.47      145.06    0.79   SPY  0.67  0.64
24       A 2025-11-21 09:53:00  146.360001  146.360001  146.360001  146.360001     100.0  2025-11-21  144.47      145.06    0.90   SPY  0.67  0.64
25       A 2025-11-21 09:54:00  146.354996  146.559998  146.354996  146.419998    6216.0  2025-11-21  144.47      145.06    0.89   SPY  0.67  0.64
26       A 2025-11-21 09:55:00  146.509995  146.789993  146.509995  146.679993    5026.0  2025-11-21  144.47      145.06    1.00   SPY  0.67  0.64
27       A 2025-11-21 09:56:00  146.639999  146.819901  146.630005  146.710007     600.0  2025-11-21  144.47      145.06    1.09   SPY  0.67  0.64
28       A 2025-11-21 09:57:00  146.710007  146.919998  146.710007  146.740005    1056.0  2025-11-21  144.47      145.06    1.14   SPY  0.67  0.64
29       A 2025-11-21 09:58:00  146.899994  147.130005  146.899994  147.130005     650.0  2025-11-21  144.47      145.06    1.27   SPY  0.67  0.64
30       A 2025-11-21 09:59:00  147.059998  147.100006  146.850006  146.850006    2911.0  2025-11-21  144.47      145.06    1.38   SPY  0.67  0.64
31       A 2025-11-21 10:00:00  147.000000  147.259995  146.870102  147.110001     600.0  2025-11-21  144.47      145.06    1.34   SPY  0.67  0.64
32       A 2025-11-21 10:01:00  147.100006  147.240005  147.089996  147.169998    1116.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64
33       A 2025-11-21 10:02:00  147.107498  147.107498  146.889999  146.979996    1461.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64
34       A 2025-11-21 10:03:00  147.100006  147.139999  146.927505  147.139999     400.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64
35       A 2025-11-21 10:04:00  146.940002  147.009995  146.830002  146.889999     600.0  2025-11-21  144.47      145.06    1.30   SPY  0.67  0.64
36       A 2025-11-21 10:05:00  147.050003  147.059998  146.830002  147.050003     400.0  2025-11-21  144.47      145.06    1.37   SPY  0.67  0.64
37       A 2025-11-21 10:06:00  146.970001  147.130005  146.910004  146.990005     500.0  2025-11-21  144.47      145.06    1.32   SPY  0.67  0.64
38       A 2025-11-21 10:07:00  146.994995  147.009995  146.630005  146.847900    6211.0  2025-11-21  144.47      145.06    1.33   SPY  0.67  0.64
39       A 2025-11-21 10:08:00  146.875000  146.875000  146.645004  146.860001    1100.0  2025-11-21  144.47      145.06    1.25   SPY  0.67  0.64
40       A 2025-11-21 10:09:00  146.789993  147.210007  146.714996  147.199997    1217.0  2025-11-21  144.47      145.06    1.19   SPY  0.67  0.64
41       A 2025-11-21 10:10:00  147.070007  147.440002  147.070007  147.399994    2757.0  2025-11-21  144.47      145.06    1.39   SPY  0.67  0.64
42       A 2025-11-21 10:11:00  147.429993  147.440002  147.169998  147.360001    2479.0  2025-11-21  144.47      145.06    1.63   SPY  0.67  0.64
43       A 2025-11-21 10:12:00  147.102997  147.190002  146.960007  147.149994    1154.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64
44       A 2025-11-21 10:13:00  147.289993  147.289993  146.979996  147.040100    3236.0  2025-11-21  144.47      145.06    1.54   SPY  0.67  0.64
45       A 2025-11-21 10:14:00  147.039993  147.059998  146.960007  147.059998     600.0  2025-11-21  144.47      145.06    1.36   SPY  0.67  0.64
46       A 2025-11-21 10:15:00  147.229996  147.279999  147.184998  147.279999    1300.0  2025-11-21  144.47      145.06    1.50   SPY  0.67  0.64
47       A 2025-11-21 10:16:00  147.350006  147.410004  147.320007  147.320007     501.0  2025-11-21  144.47      145.06    1.58   SPY  0.67  0.64
48       A 2025-11-21 10:17:00  147.380005  147.449997  147.380005  147.449997     300.0  2025-11-21  144.47      145.06    1.60   SPY  0.67  0.64
49       A 2025-11-21 10:18:00  147.339996  147.449997  147.294998  147.389999    1400.0  2025-11-21  144.47      145.06    1.57   SPY  0.67  0.64
50       A 2025-11-21 10:19:00  147.365005  147.369995  147.220001  147.320007    1800.0  2025-11-21  144.47      145.06    1.59   SPY  0.67  0.64
51       A 2025-11-21 10:20:00  147.285004  147.339996  147.000000  147.080002    2866.0  2025-11-21  144.47      145.06    1.53   SPY  0.67  0.64
52       A 2025-11-21 10:21:00  147.044998  147.139999  146.964996  147.139999     700.0  2025-11-21  144.47      145.06    1.37   SPY  0.67  0.64
53       A 2025-11-21 10:22:00  147.289993  147.580002  147.119995  147.440002    2814.0  2025-11-21  144.47      145.06    1.54   SPY  0.67  0.64
54       A 2025-11-21 10:23:00  147.419998  147.570007  147.139999  147.369995    4902.0  2025-11-21  144.47      145.06    1.63   SPY  0.67  0.64
55       A 2025-11-21 10:24:00  147.380005  147.550003  147.179993  147.550003    2549.0  2025-11-21  144.47      145.06    1.60   SPY  0.67  0.64
56       A 2025-11-21 10:25:00  147.570007  147.839996  147.539993  147.710007    1360.0  2025-11-21  144.47      145.06    1.73   SPY  0.67  0.64
57       A 2025-11-21 10:26:00  147.690002  147.690002  147.690002  147.690002     100.0  2025-11-21  144.47      145.06    1.81   SPY  0.67  0.64
58       A 2025-11-21 10:27:00  147.610001  147.779999  147.470001  147.580002    4519.0  2025-11-21  144.47      145.06    1.76   SPY  0.67  0.64
59       A 2025-11-21 10:28:00  147.544998  147.710007  147.324997  147.710007    2794.0  2025-11-21  144.47      145.06    1.71   SPY  0.67  0.64
60       A 2025-11-21 10:29:00  147.574997  147.710007  147.479996  147.649994    2554.0  2025-11-21  144.47      145.06    1.73   SPY  0.67  0.64
61       A 2025-11-21 10:30:00  147.600006  148.089996  147.565002  148.074997    5928.0  2025-11-21  144.47      145.06    1.75   SPY  0.67  0.64
62       A 2025-11-21 10:31:00  148.119995  148.210007  148.020004  148.210007    3057.0  2025-11-21  144.47      145.06    2.11   SPY  0.67  0.64
63       A 2025-11-21 10:32:00  148.009995  148.210007  147.929993  147.945007    1920.0  2025-11-21  144.47      145.06    2.03   SPY  0.67  0.64
64       A 2025-11-21 10:33:00  147.990005  148.225006  147.990005  148.160004    1105.0  2025-11-21  144.47      145.06    2.02   SPY  0.67  0.64
65       A 2025-11-21 10:34:00  148.089996  148.089996  147.949997  147.949997     900.0  2025-11-21  144.47      145.06    2.09   SPY  0.67  0.64
66       A 2025-11-21 10:35:00  147.945007  147.945007  147.945007  147.945007    1150.0  2025-11-21  144.47      145.06    1.99   SPY  0.67  0.64
67       A 2025-11-21 10:36:00  147.850006  147.850006  147.839996  147.839996    1146.0  2025-11-21  144.47      145.06    1.92   SPY  0.67  0.64
68       A 2025-11-21 10:37:00  147.770004  147.949997  147.710007  147.919998    1278.0  2025-11-21  144.47      145.06    1.87   SPY  0.67  0.64
69       A 2025-11-21 10:38:00  148.020004  148.220001  147.934998  148.220001    4351.0  2025-11-21  144.47      145.06    2.04   SPY  0.67  0.64
70       A 2025-11-21 10:39:00  148.210007  148.380005  148.130005  148.324997    2147.0  2025-11-21  144.47      145.06    2.17   SPY  0.67  0.64
71       A 2025-11-21 10:40:00  148.324997  148.600006  148.259995  148.380005    4528.0  2025-11-21  144.47      145.06    2.25   SPY  0.67  0.64
72       A 2025-11-21 10:41:00  148.419998  148.475006  148.250000  148.380005    6518.0  2025-11-21  144.47      145.06    2.32   SPY  0.67  0.64
73       A 2025-11-21 10:42:00  148.289993  148.289993  148.057495  148.059998    2306.0  2025-11-21  144.47      145.06    2.23   SPY  0.67  0.64
74       A 2025-11-21 10:43:00  148.149994  148.160004  147.949997  147.960007    1800.0  2025-11-21  144.47      145.06    2.13   SPY  0.67  0.64
75       A 2025-11-21 10:44:00  147.985001  148.149994  147.970001  148.020004    1700.0  2025-11-21  144.47      145.06    2.02   SPY  0.67  0.64
76       A 2025-11-21 10:45:00  148.039993  148.149994  148.039993  148.149994     200.0  2025-11-21  144.47      145.06    2.05   SPY  0.67  0.64
77       A 2025-11-21 10:46:00  148.070007  148.255005  147.919998  148.024994    9335.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64
78       A 2025-11-21 10:47:00  148.024994  148.205002  148.024994  148.205002    4372.0  2025-11-21  144.47      145.06    2.04   SPY  0.67  0.64
79       A 2025-11-21 10:48:00  148.190002  148.190002  147.910004  148.100006    1973.0  2025-11-21  144.47      145.06    2.16   SPY  0.67  0.64
80       A 2025-11-21 10:49:00  148.050003  148.339996  148.050003  148.244995    1300.0  2025-11-21  144.47      145.06    2.06   SPY  0.67  0.64
81       A 2025-11-21 10:50:00  148.139999  148.139999  148.119995  148.125000     500.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64
82       A 2025-11-21 10:51:00  148.154999  148.154999  148.070007  148.139999    2134.0  2025-11-21  144.47      145.06    2.13   SPY  0.67  0.64
83       A 2025-11-21 10:52:00  148.149994  148.350006  148.149994  148.220001    4799.0  2025-11-21  144.47      145.06    2.13   SPY  0.67  0.64
84       A 2025-11-21 10:53:00  148.220001  148.300003  148.199997  148.199997    1252.0  2025-11-21  144.47      145.06    2.18   SPY  0.67  0.64
85       A 2025-11-21 10:54:00  148.205002  148.300003  148.205002  148.259995    2546.0  2025-11-21  144.47      145.06    2.17   SPY  0.67  0.64
86       A 2025-11-21 10:55:00  148.250000  148.460007  148.240005  148.460007    1382.0  2025-11-21  144.47      145.06    2.20   SPY  0.67  0.64
87       A 2025-11-21 10:56:00  148.449997  148.615005  148.449997  148.600006    1000.0  2025-11-21  144.47      145.06    2.34   SPY  0.67  0.64
88       A 2025-11-21 10:57:00  148.589996  148.630005  148.535004  148.535004    1451.0  2025-11-21  144.47      145.06    2.43   SPY  0.67  0.64
89       A 2025-11-21 10:58:00  148.535004  148.559998  148.440002  148.449997    1705.0  2025-11-21  144.47      145.06    2.40   SPY  0.67  0.64
90       A 2025-11-21 10:59:00  148.475006  148.475006  148.259995  148.259995    1879.0  2025-11-21  144.47      145.06    2.35   SPY  0.67  0.64
91       A 2025-11-21 11:00:00  148.259995  148.274994  148.179993  148.179993    3917.0  2025-11-21  144.47      145.06    2.21   SPY  0.67  0.64
92       A 2025-11-21 11:01:00  148.169998  148.279999  148.119995  148.205002    4528.0  2025-11-21  144.47      145.06    2.14   SPY  0.67  0.64
93       A 2025-11-21 11:02:00  148.130005  148.240005  148.089996  148.190002    3124.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64
94       A 2025-11-21 11:03:00  148.110001  148.154999  148.080002  148.125000    1438.0  2025-11-21  144.47      145.06    2.10   SPY  0.67  0.64
95       A 2025-11-21 11:04:00  148.130005  148.130005  148.050003  148.089996    1780.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64
96       A 2025-11-21 11:05:00  148.050003  148.070007  147.919998  148.005005    3155.0  2025-11-21  144.47      145.06    2.06   SPY  0.67  0.64
97       A 2025-11-21 11:06:00  148.089996  148.089996  148.039993  148.039993    1000.0  2025-11-21  144.47      145.06    2.09   SPY  0.67  0.64
98       A 2025-11-21 11:07:00  148.160004  148.160004  148.039993  148.130005    1884.0  2025-11-21  144.47      145.06    2.14   SPY  0.67  0.64
99       A 2025-11-21 11:08:00  148.080002  148.179993  148.054993  148.125000    5563.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64
100      A 2025-11-21 11:09:00  148.070007  148.149994  148.059998  148.149994    1144.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64
101      A 2025-11-21 11:10:00  148.089996  148.169998  148.050003  148.050003    2200.0  2025-11-21  144.47      145.06    2.09   SPY  0.67  0.64
102      A 2025-11-21 11:11:00  148.074997  148.074997  147.714996  147.725006    2000.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64
103      A 2025-11-21 11:12:00  147.727493  147.860001  147.725006  147.860001    2099.0  2025-11-21  144.47      145.06    1.84   SPY  0.67  0.64
104      A 2025-11-21 11:13:00  147.860001  148.039993  147.860001  148.000000    4579.0  2025-11-21  144.47      145.06    1.93   SPY  0.67  0.64
105      A 2025-11-21 11:14:00  147.949997  147.985001  147.949997  147.985001    2142.0  2025-11-21  144.47      145.06    1.99   SPY  0.67  0.64
106      A 2025-11-21 11:15:00  148.050003  148.097504  148.044998  148.097504    1301.0  2025-11-21  144.47      145.06    2.06   SPY  0.67  0.64
107      A 2025-11-21 11:16:00  148.139999  148.139999  147.949997  148.070007    2892.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64
108      A 2025-11-21 11:17:00  148.070007  148.070007  147.994995  148.039993    1100.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64
109      A 2025-11-21 11:18:00  148.009995  148.009995  147.744995  147.744995    2756.0  2025-11-21  144.47      145.06    2.03   SPY  0.67  0.64
110      A 2025-11-21 11:19:00  147.779999  147.860001  147.744995  147.744995    2736.0  2025-11-21  144.47      145.06    1.88   SPY  0.67  0.64
111      A 2025-11-21 11:20:00  147.779999  148.070007  147.779999  148.005005    2400.0  2025-11-21  144.47      145.06    1.88   SPY  0.67  0.64
112      A 2025-11-21 11:21:00  148.002502  148.179993  148.002502  148.179993     500.0  2025-11-21  144.47      145.06    2.03   SPY  0.67  0.64
113      A 2025-11-21 11:22:00  148.179993  148.309998  148.179993  148.304993    1600.0  2025-11-21  144.47      145.06    2.15   SPY  0.67  0.64
114      A 2025-11-21 11:23:00  148.354996  148.494995  148.354996  148.445007    1400.0  2025-11-21  144.47      145.06    2.27   SPY  0.67  0.64
115      A 2025-11-21 11:24:00  148.500000  148.615005  148.500000  148.554993    1772.0  2025-11-21  144.47      145.06    2.37   SPY  0.67  0.64
116      A 2025-11-21 11:25:00  148.630005  148.689896  148.570007  148.570007     750.0  2025-11-21  144.47      145.06    2.46   SPY  0.67  0.64
117      A 2025-11-21 11:26:00  148.604996  148.669998  148.529999  148.654999    1161.0  2025-11-21  144.47      145.06    2.44   SPY  0.67  0.64
118      A 2025-11-21 11:27:00  148.699997  148.880005  148.699997  148.770004    2304.0  2025-11-21  144.47      145.06    2.51   SPY  0.67  0.64
119      A 2025-11-21 11:28:00  148.770004  148.850006  148.770004  148.850006     300.0  2025-11-21  144.47      145.06    2.56   SPY  0.67  0.64
120      A 2025-11-21 11:29:00  148.889999  148.897507  148.839996  148.884995     800.0  2025-11-21  144.47      145.06    2.64   SPY  0.67  0.64
121      A 2025-11-21 11:30:00  148.960007  149.350006  148.960007  149.169998    9667.0  2025-11-21  144.47      145.06    2.69   SPY  0.67  0.64
122      A 2025-11-21 11:31:00  149.172501  149.287704  148.979996  149.024994    4558.0  2025-11-21  144.47      145.06    2.84   SPY  0.67  0.64
123      A 2025-11-21 11:32:00  148.970001  149.145004  148.824997  149.113403    3500.0  2025-11-21  144.47      145.06    2.70   SPY  0.67  0.64
124      A 2025-11-21 11:33:00  149.175003  149.229996  149.169998  149.169998    1374.0  2025-11-21  144.47      145.06    2.84   SPY  0.67  0.64
125      A 2025-11-21 11:34:00  149.160004  149.160004  149.070007  149.110001    1319.0  2025-11-21  144.47      145.06    2.83   SPY  0.67  0.64
126      A 2025-11-21 11:35:00  149.039993  149.074997  149.009995  149.070007    1813.0  2025-11-21  144.47      145.06    2.74   SPY  0.67  0.64
127      A 2025-11-21 11:36:00  149.139999  149.350006  149.095001  149.274994    1046.0  2025-11-21  144.47      145.06    2.81   SPY  0.67  0.64
128      A 2025-11-21 11:37:00  149.279999  149.289993  149.029999  149.065002     800.0  2025-11-21  144.47      145.06    2.91   SPY  0.67  0.64
129      A 2025-11-21 11:38:00  149.065002  149.179993  149.039993  149.179993    1022.0  2025-11-21  144.47      145.06    2.76   SPY  0.67  0.64
130      A 2025-11-21 11:39:00  149.149994  149.179993  149.110001  149.110001     546.0  2025-11-21  144.47      145.06    2.82   SPY  0.67  0.64
131      A 2025-11-21 11:40:00  149.119995  149.119995  149.089996  149.115005     900.0  2025-11-21  144.47      145.06    2.80   SPY  0.67  0.64
132      A 2025-11-21 11:41:00  149.059998  149.059998  148.960007  149.029999   18608.0  2025-11-21  144.47      145.06    2.76   SPY  0.67  0.64

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2025-11-21 00:45:00,145.830002,145.830002,145.830002,145.830002,9.0,2025-11-21,144.47,145.06,0.53,SPY,0.67,0.64
1,A,2025-11-21 01:50:00,145.800003,145.800003,145.800003,145.800003,5.0,2025-11-21,144.47,145.06,0.51,SPY,0.67,0.64
2,A,2025-11-21 02:00:00,145.809998,145.809998,145.809998,145.809998,5.0,2025-11-21,144.47,145.06,0.52,SPY,0.67,0.64
3,A,2025-11-21 09:30:00,144.470001,145.375000,144.470001,144.645004,84953.0,2025-11-21,144.47,145.06,-0.41,SPY,0.67,0.64
4,A,2025-11-21 09:31:00,144.645004,144.645004,144.645004,144.645004,2500.0,2025-11-21,144.47,145.06,-0.29,SPY,0.67,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2025-11-24 12:57:00,152.860001,152.899994,152.850006,152.899994,2574.0,2025-11-24,151.90,151.26,1.06,SPY,0.67,0.64
616,A,2025-11-24 12:58:00,152.929993,152.979996,152.914993,152.929993,1466.0,2025-11-24,151.90,151.26,1.10,SPY,0.67,0.64
617,A,2025-11-24 12:59:00,153.009995,153.009995,152.949997,152.970795,850.0,2025-11-24,151.90,151.26,1.16,SPY,0.67,0.64
618,A,2025-11-24 13:00:00,152.945007,152.945007,152.945007,152.945007,926.0,2025-11-24,151.90,151.26,1.11,SPY,0.67,0.64
619,A,2025-11-24 13:01:00,152.904999,152.939896,152.815002,152.839996,1429.0,2025-11-24,151.90,151.26,1.09,SPY,0.67,0.64

In [35]:
# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [36]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=6,
    parallel_tickers=True,
    max_workers_tickers=1,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,   # ⬅️ додай це
)

▶ Починаємо: 10 тікерів (пропущено 0 по старому маніфесту) | 2025-11-21 00:00:00 → 2026-02-21 23:59:59 | interval=1 | next batch #0021 | run=ebd06b4b

   workers: tickers=1, chunks=6 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2025-11-21 → 2026-02-20 (92 днів)

   📈 обробляються дні: 2026-02-21 → 2026-02-21 (1 днів)

   psutil · старт · 🧠 RAM: 2,472.1 MB

[10/10] – SOXL: empty | 100.00% | ETA 00:00

   🔚 фінал · 🧠 RAM: 2,471.5 MB

🏁 Готово. Нових рядків: 0 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:04

In [37]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

✅ DONE  in=743,164 → out=743,164  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 1.6s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [38]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [39]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [40]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=743,164  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 1.3s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [41]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [42]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=743,164  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 0.4s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [43]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [44]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=10.0s

[batch   10] rows=20,000,000  elapsed=20.2s

[batch   15] rows=30,000,000  elapsed=30.2s

[batch   20] rows=40,000,000  elapsed=40.4s

[batch   25] rows=50,000,000  elapsed=50.5s

[batch   30] rows=60,000,000  elapsed=60.5s

[batch   35] rows=70,000,000  elapsed=70.6s

[batch   40] rows=79,478,082  elapsed=80.2s
✅ DONE rows=79,478,082 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 80.2s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [45]:
import pandas as pd
from tqdm import tqdm   # прогрес-бар

def get_gaps_for_tickers(tickers_df, start_date, end_date):
    """
    Отримує гепи для всіх тикерів із DataFrame tickers_df (колонка 'ticker').
    Використовує ендпоінт /daily/gaps і об’єднує всі результати у один DataFrame.
    """
    all_results = []

    tickers = tickers_df["ticker"].dropna().astype(str).unique().tolist()

    for t in tqdm(tickers, desc="Processing tickers"):
        params = {
            "ticker": t,
            "start_date": start_date,
            "end_date": end_date,
            "format": "json_records"
        }

        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is not None and not df_gap.empty:
                all_results.append(df_gap)
        except Exception as e:
            print(f"⚠️ Проблема з {t}: {e}")

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    else:
        return pd.DataFrame()

# === приклад використання ===
df_gaps_all = get_gaps_for_tickers(top1500, start_date = start_date_str, end_date = end_date_str)

print(df_gaps_all.head())
print("Загалом рядків:", len(df_gaps_all))

Processing tickers:   0%|          | 0/6717 [00:00<?, ?it/s]

Processing tickers:   0%|          | 1/6717 [00:00<23:46,  4.71it/s]

Processing tickers:   0%|          | 2/6717 [00:00<23:35,  4.74it/s]

Processing tickers:   0%|          | 3/6717 [00:00<23:04,  4.85it/s]

Processing tickers:   0%|          | 4/6717 [00:00<22:44,  4.92it/s]

Processing tickers:   0%|          | 5/6717 [00:01<22:34,  4.96it/s]

Processing tickers:   0%|          | 6/6717 [00:01<22:27,  4.98it/s]

Processing tickers:   0%|          | 7/6717 [00:01<22:23,  4.99it/s]

Processing tickers:   0%|          | 8/6717 [00:01<22:17,  5.02it/s]

Processing tickers:   0%|          | 9/6717 [00:01<22:20,  5.00it/s]

Processing tickers:   0%|          | 10/6717 [00:02<22:28,  4.97it/s]

Processing tickers:   0%|          | 11/6717 [00:02<22:26,  4.98it/s]

Processing tickers:   0%|          | 12/6717 [00:02<22:36,  4.94it/s]

Processing tickers:   0%|          | 13/6717 [00:02<22:35,  4.95it/s]

Processing tickers:   0%|          | 14/6717 [00:02<22:34,  4.95it/s]

Processing tickers:   0%|          | 15/6717 [00:03<22:34,  4.95it/s]

Processing tickers:   0%|          | 16/6717 [00:03<22:34,  4.95it/s]

Processing tickers:   0%|          | 17/6717 [00:03<22:31,  4.96it/s]

Processing tickers:   0%|          | 18/6717 [00:03<22:39,  4.93it/s]

Processing tickers:   0%|          | 19/6717 [00:03<22:32,  4.95it/s]

Processing tickers:   0%|          | 20/6717 [00:04<22:33,  4.95it/s]

Processing tickers:   0%|          | 21/6717 [00:04<22:29,  4.96it/s]

Processing tickers:   0%|          | 22/6717 [00:04<22:19,  5.00it/s]

Processing tickers:   0%|          | 23/6717 [00:04<22:23,  4.98it/s]

Processing tickers:   0%|          | 24/6717 [00:04<22:49,  4.89it/s]

Processing tickers:   0%|          | 25/6717 [00:05<23:02,  4.84it/s]

Processing tickers:   0%|          | 26/6717 [00:05<23:03,  4.84it/s]

Processing tickers:   0%|          | 27/6717 [00:05<23:37,  4.72it/s]

Processing tickers:   0%|          | 28/6717 [00:05<23:20,  4.78it/s]

Processing tickers:   0%|          | 29/6717 [00:05<23:34,  4.73it/s]

Processing tickers:   0%|          | 30/6717 [00:06<23:19,  4.78it/s]

Processing tickers:   0%|          | 31/6717 [00:06<23:02,  4.84it/s]

Processing tickers:   0%|          | 32/6717 [00:06<22:55,  4.86it/s]

Processing tickers:   0%|          | 33/6717 [00:06<22:48,  4.88it/s]

Processing tickers:   1%|          | 34/6717 [00:06<22:42,  4.91it/s]

Processing tickers:   1%|          | 35/6717 [00:07<22:40,  4.91it/s]

Processing tickers:   1%|          | 36/6717 [00:07<22:30,  4.95it/s]

Processing tickers:   1%|          | 37/6717 [00:07<22:41,  4.91it/s]

Processing tickers:   1%|          | 38/6717 [00:07<22:38,  4.92it/s]

Processing tickers:   1%|          | 39/6717 [00:07<22:45,  4.89it/s]

Processing tickers:   1%|          | 40/6717 [00:08<22:37,  4.92it/s]

Processing tickers:   1%|          | 41/6717 [00:08<22:28,  4.95it/s]

Processing tickers:   1%|          | 42/6717 [00:08<22:29,  4.94it/s]

Processing tickers:   1%|          | 43/6717 [00:08<22:25,  4.96it/s]

Processing tickers:   1%|          | 44/6717 [00:08<22:25,  4.96it/s]

Processing tickers:   1%|          | 45/6717 [00:09<22:19,  4.98it/s]

Processing tickers:   1%|          | 46/6717 [00:09<22:25,  4.96it/s]

Processing tickers:   1%|          | 47/6717 [00:09<22:25,  4.96it/s]

Processing tickers:   1%|          | 48/6717 [00:09<22:27,  4.95it/s]

Processing tickers:   1%|          | 49/6717 [00:09<22:27,  4.95it/s]

Processing tickers:   1%|          | 50/6717 [00:10<22:18,  4.98it/s]

Processing tickers:   1%|          | 51/6717 [00:10<22:14,  5.00it/s]

Processing tickers:   1%|          | 52/6717 [00:10<22:15,  4.99it/s]

Processing tickers:   1%|          | 53/6717 [00:10<22:13,  5.00it/s]

Processing tickers:   1%|          | 54/6717 [00:10<23:09,  4.79it/s]

Processing tickers:   1%|          | 55/6717 [00:11<22:47,  4.87it/s]

Processing tickers:   1%|          | 56/6717 [00:11<23:18,  4.76it/s]

Processing tickers:   1%|          | 57/6717 [00:11<23:00,  4.82it/s]

Processing tickers:   1%|          | 58/6717 [00:11<22:46,  4.87it/s]

Processing tickers:   1%|          | 59/6717 [00:12<22:37,  4.90it/s]

Processing tickers:   1%|          | 60/6717 [00:12<22:32,  4.92it/s]

Processing tickers:   1%|          | 61/6717 [00:12<22:25,  4.95it/s]

Processing tickers:   1%|          | 62/6717 [00:12<22:35,  4.91it/s]

Processing tickers:   1%|          | 63/6717 [00:12<22:32,  4.92it/s]

Processing tickers:   1%|          | 64/6717 [00:13<22:31,  4.92it/s]

Processing tickers:   1%|          | 65/6717 [00:13<22:34,  4.91it/s]

Processing tickers:   1%|          | 66/6717 [00:13<22:25,  4.94it/s]

Processing tickers:   1%|          | 67/6717 [00:13<22:20,  4.96it/s]

Processing tickers:   1%|          | 68/6717 [00:13<22:49,  4.85it/s]

Processing tickers:   1%|          | 69/6717 [00:14<22:36,  4.90it/s]

Processing tickers:   1%|          | 70/6717 [00:14<22:33,  4.91it/s]

Processing tickers:   1%|          | 71/6717 [00:14<22:21,  4.95it/s]

Processing tickers:   1%|          | 72/6717 [00:14<22:24,  4.94it/s]

Processing tickers:   1%|          | 73/6717 [00:14<22:23,  4.95it/s]

Processing tickers:   1%|          | 74/6717 [00:15<22:23,  4.95it/s]

Processing tickers:   1%|          | 75/6717 [00:15<22:21,  4.95it/s]

Processing tickers:   1%|          | 76/6717 [00:15<22:11,  4.99it/s]

Processing tickers:   1%|          | 77/6717 [00:15<22:25,  4.93it/s]

Processing tickers:   1%|          | 78/6717 [00:15<22:34,  4.90it/s]

Processing tickers:   1%|          | 79/6717 [00:16<22:31,  4.91it/s]

Processing tickers:   1%|          | 80/6717 [00:16<22:21,  4.95it/s]

Processing tickers:   1%|          | 81/6717 [00:16<22:16,  4.96it/s]

Processing tickers:   1%|          | 82/6717 [00:16<22:10,  4.99it/s]

Processing tickers:   1%|          | 83/6717 [00:16<22:08,  4.99it/s]

Processing tickers:   1%|▏         | 84/6717 [00:17<22:07,  5.00it/s]

Processing tickers:   1%|▏         | 85/6717 [00:17<22:06,  5.00it/s]

Processing tickers:   1%|▏         | 86/6717 [00:17<22:06,  5.00it/s]

Processing tickers:   1%|▏         | 87/6717 [00:17<22:22,  4.94it/s]

Processing tickers:   1%|▏         | 88/6717 [00:17<22:17,  4.96it/s]

Processing tickers:   1%|▏         | 89/6717 [00:18<22:14,  4.97it/s]

Processing tickers:   1%|▏         | 90/6717 [00:18<22:30,  4.91it/s]

Processing tickers:   1%|▏         | 91/6717 [00:18<22:49,  4.84it/s]

Processing tickers:   1%|▏         | 92/6717 [00:18<22:56,  4.81it/s]

Processing tickers:   1%|▏         | 93/6717 [00:18<22:43,  4.86it/s]

Processing tickers:   1%|▏         | 94/6717 [00:19<22:38,  4.88it/s]

Processing tickers:   1%|▏         | 95/6717 [00:19<22:52,  4.82it/s]

Processing tickers:   1%|▏         | 96/6717 [00:19<22:51,  4.83it/s]

Processing tickers:   1%|▏         | 97/6717 [00:19<22:37,  4.88it/s]

Processing tickers:   1%|▏         | 98/6717 [00:19<22:47,  4.84it/s]

Processing tickers:   1%|▏         | 99/6717 [00:20<22:34,  4.89it/s]

Processing tickers:   1%|▏         | 100/6717 [00:20<22:20,  4.94it/s]

Processing tickers:   2%|▏         | 101/6717 [00:20<22:19,  4.94it/s]

Processing tickers:   2%|▏         | 102/6717 [00:20<22:19,  4.94it/s]

Processing tickers:   2%|▏         | 103/6717 [00:20<22:23,  4.92it/s]

Processing tickers:   2%|▏         | 104/6717 [00:21<22:27,  4.91it/s]

Processing tickers:   2%|▏         | 105/6717 [00:21<22:23,  4.92it/s]

Processing tickers:   2%|▏         | 106/6717 [00:21<22:19,  4.94it/s]

Processing tickers:   2%|▏         | 107/6717 [00:21<22:10,  4.97it/s]

Processing tickers:   2%|▏         | 108/6717 [00:21<22:33,  4.88it/s]

Processing tickers:   2%|▏         | 109/6717 [00:22<22:21,  4.93it/s]

Processing tickers:   2%|▏         | 110/6717 [00:22<22:15,  4.95it/s]

Processing tickers:   2%|▏         | 111/6717 [00:22<22:13,  4.95it/s]

Processing tickers:   2%|▏         | 112/6717 [00:22<22:15,  4.95it/s]

Processing tickers:   2%|▏         | 113/6717 [00:22<22:05,  4.98it/s]

Processing tickers:   2%|▏         | 114/6717 [00:23<22:00,  5.00it/s]

Processing tickers:   2%|▏         | 115/6717 [00:23<22:07,  4.97it/s]

Processing tickers:   2%|▏         | 116/6717 [00:23<22:23,  4.91it/s]

Processing tickers:   2%|▏         | 117/6717 [00:23<22:19,  4.93it/s]

Processing tickers:   2%|▏         | 118/6717 [00:23<22:21,  4.92it/s]

Processing tickers:   2%|▏         | 119/6717 [00:24<22:21,  4.92it/s]

Processing tickers:   2%|▏         | 120/6717 [00:24<22:20,  4.92it/s]

Processing tickers:   2%|▏         | 121/6717 [00:24<22:21,  4.92it/s]

Processing tickers:   2%|▏         | 122/6717 [00:24<22:33,  4.87it/s]

Processing tickers:   2%|▏         | 123/6717 [00:25<22:33,  4.87it/s]

Processing tickers:   2%|▏         | 124/6717 [00:25<22:36,  4.86it/s]

Processing tickers:   2%|▏         | 125/6717 [00:25<22:26,  4.90it/s]

Processing tickers:   2%|▏         | 126/6717 [00:25<22:21,  4.91it/s]

Processing tickers:   2%|▏         | 127/6717 [00:25<22:20,  4.92it/s]

Processing tickers:   2%|▏         | 128/6717 [00:26<22:11,  4.95it/s]

Processing tickers:   2%|▏         | 129/6717 [00:26<22:14,  4.94it/s]

Processing tickers:   2%|▏         | 130/6717 [00:26<22:13,  4.94it/s]

Processing tickers:   2%|▏         | 131/6717 [00:26<22:12,  4.94it/s]

Processing tickers:   2%|▏         | 132/6717 [00:26<22:10,  4.95it/s]

Processing tickers:   2%|▏         | 133/6717 [00:27<22:16,  4.93it/s]

Processing tickers:   2%|▏         | 134/6717 [00:27<22:31,  4.87it/s]

Processing tickers:   2%|▏         | 135/6717 [00:27<22:29,  4.88it/s]

Processing tickers:   2%|▏         | 136/6717 [00:27<22:22,  4.90it/s]

Processing tickers:   2%|▏         | 137/6717 [00:27<22:15,  4.93it/s]

Processing tickers:   2%|▏         | 138/6717 [00:28<22:13,  4.93it/s]

Processing tickers:   2%|▏         | 139/6717 [00:28<22:04,  4.97it/s]

Processing tickers:   2%|▏         | 140/6717 [00:28<22:03,  4.97it/s]

Processing tickers:   2%|▏         | 141/6717 [00:28<21:59,  4.98it/s]

Processing tickers:   2%|▏         | 142/6717 [00:28<21:57,  4.99it/s]

Processing tickers:   2%|▏         | 143/6717 [00:29<22:01,  4.97it/s]

Processing tickers:   2%|▏         | 144/6717 [00:29<22:19,  4.91it/s]

Processing tickers:   2%|▏         | 145/6717 [00:29<22:19,  4.91it/s]

Processing tickers:   2%|▏         | 146/6717 [00:29<22:13,  4.93it/s]

Processing tickers:   2%|▏         | 147/6717 [00:29<22:12,  4.93it/s]

Processing tickers:   2%|▏         | 148/6717 [00:30<22:22,  4.89it/s]

Processing tickers:   2%|▏         | 149/6717 [00:30<22:15,  4.92it/s]

Processing tickers:   2%|▏         | 150/6717 [00:30<22:20,  4.90it/s]

Processing tickers:   2%|▏         | 151/6717 [00:30<22:15,  4.92it/s]

Processing tickers:   2%|▏         | 152/6717 [00:30<22:15,  4.92it/s]

Processing tickers:   2%|▏         | 153/6717 [00:31<22:15,  4.92it/s]

Processing tickers:   2%|▏         | 154/6717 [00:31<22:06,  4.95it/s]

Processing tickers:   2%|▏         | 155/6717 [00:31<22:25,  4.88it/s]

Processing tickers:   2%|▏         | 156/6717 [00:31<22:15,  4.91it/s]

Processing tickers:   2%|▏         | 157/6717 [00:31<22:29,  4.86it/s]

Processing tickers:   2%|▏         | 158/6717 [00:32<22:22,  4.88it/s]

Processing tickers:   2%|▏         | 159/6717 [00:32<22:13,  4.92it/s]

Processing tickers:   2%|▏         | 160/6717 [00:32<22:11,  4.92it/s]

Processing tickers:   2%|▏         | 161/6717 [00:32<22:13,  4.92it/s]

Processing tickers:   2%|▏         | 162/6717 [00:32<22:06,  4.94it/s]

Processing tickers:   2%|▏         | 163/6717 [00:33<22:11,  4.92it/s]

Processing tickers:   2%|▏         | 164/6717 [00:33<22:28,  4.86it/s]

Processing tickers:   2%|▏         | 165/6717 [00:33<22:14,  4.91it/s]

Processing tickers:   2%|▏         | 166/6717 [00:33<22:17,  4.90it/s]

Processing tickers:   2%|▏         | 167/6717 [00:33<22:09,  4.93it/s]

Processing tickers:   3%|▎         | 168/6717 [00:34<22:04,  4.94it/s]

Processing tickers:   3%|▎         | 169/6717 [00:34<22:04,  4.95it/s]

Processing tickers:   3%|▎         | 170/6717 [00:34<22:02,  4.95it/s]

Processing tickers:   3%|▎         | 171/6717 [00:34<22:04,  4.94it/s]

Processing tickers:   3%|▎         | 172/6717 [00:34<22:02,  4.95it/s]

Processing tickers:   3%|▎         | 173/6717 [00:35<22:03,  4.95it/s]

Processing tickers:   3%|▎         | 174/6717 [00:35<21:56,  4.97it/s]

Processing tickers:   3%|▎         | 175/6717 [00:35<21:53,  4.98it/s]

Processing tickers:   3%|▎         | 176/6717 [00:35<22:35,  4.82it/s]

Processing tickers:   3%|▎         | 177/6717 [00:35<22:28,  4.85it/s]

Processing tickers:   3%|▎         | 178/6717 [00:36<22:21,  4.87it/s]

Processing tickers:   3%|▎         | 179/6717 [00:36<22:17,  4.89it/s]

Processing tickers:   3%|▎         | 180/6717 [00:36<22:08,  4.92it/s]

Processing tickers:   3%|▎         | 181/6717 [00:36<22:01,  4.94it/s]

Processing tickers:   3%|▎         | 182/6717 [00:36<22:00,  4.95it/s]

Processing tickers:   3%|▎         | 183/6717 [00:37<21:58,  4.96it/s]

Processing tickers:   3%|▎         | 184/6717 [00:37<22:00,  4.95it/s]

Processing tickers:   3%|▎         | 185/6717 [00:37<21:58,  4.95it/s]

Processing tickers:   3%|▎         | 186/6717 [00:37<21:55,  4.96it/s]

Processing tickers:   3%|▎         | 187/6717 [00:37<21:54,  4.97it/s]

Processing tickers:   3%|▎         | 188/6717 [00:38<22:04,  4.93it/s]

Processing tickers:   3%|▎         | 189/6717 [00:38<22:37,  4.81it/s]

Processing tickers:   3%|▎         | 190/6717 [00:38<22:24,  4.86it/s]

Processing tickers:   3%|▎         | 191/6717 [00:38<22:31,  4.83it/s]

Processing tickers:   3%|▎         | 192/6717 [00:39<22:09,  4.91it/s]

Processing tickers:   3%|▎         | 193/6717 [00:39<22:06,  4.92it/s]

Processing tickers:   3%|▎         | 194/6717 [00:39<22:04,  4.93it/s]

Processing tickers:   3%|▎         | 195/6717 [00:39<22:13,  4.89it/s]

Processing tickers:   3%|▎         | 196/6717 [00:39<22:08,  4.91it/s]

Processing tickers:   3%|▎         | 197/6717 [00:40<22:03,  4.93it/s]

Processing tickers:   3%|▎         | 198/6717 [00:40<22:04,  4.92it/s]

Processing tickers:   3%|▎         | 199/6717 [00:40<22:14,  4.88it/s]

Processing tickers:   3%|▎         | 200/6717 [00:40<22:11,  4.89it/s]

Processing tickers:   3%|▎         | 201/6717 [00:40<22:35,  4.81it/s]

Processing tickers:   3%|▎         | 202/6717 [00:41<22:29,  4.83it/s]

Processing tickers:   3%|▎         | 203/6717 [00:41<22:16,  4.87it/s]

Processing tickers:   3%|▎         | 204/6717 [00:41<22:15,  4.88it/s]

Processing tickers:   3%|▎         | 205/6717 [00:41<22:03,  4.92it/s]

Processing tickers:   3%|▎         | 206/6717 [00:41<22:01,  4.93it/s]

Processing tickers:   3%|▎         | 207/6717 [00:42<21:54,  4.95it/s]

Processing tickers:   3%|▎         | 208/6717 [00:42<22:03,  4.92it/s]

Processing tickers:   3%|▎         | 209/6717 [00:42<22:07,  4.90it/s]

Processing tickers:   3%|▎         | 210/6717 [00:42<21:57,  4.94it/s]

Processing tickers:   3%|▎         | 211/6717 [00:42<21:49,  4.97it/s]

Processing tickers:   3%|▎         | 212/6717 [00:43<21:43,  4.99it/s]

Processing tickers:   3%|▎         | 213/6717 [00:43<21:52,  4.95it/s]

Processing tickers:   3%|▎         | 214/6717 [00:43<22:11,  4.88it/s]

Processing tickers:   3%|▎         | 215/6717 [00:43<22:03,  4.91it/s]

Processing tickers:   3%|▎         | 216/6717 [00:43<22:01,  4.92it/s]

Processing tickers:   3%|▎         | 217/6717 [00:44<22:04,  4.91it/s]

Processing tickers:   3%|▎         | 218/6717 [00:44<21:55,  4.94it/s]

Processing tickers:   3%|▎         | 219/6717 [00:44<22:00,  4.92it/s]

Processing tickers:   3%|▎         | 220/6717 [00:44<22:00,  4.92it/s]

Processing tickers:   3%|▎         | 221/6717 [00:44<21:59,  4.92it/s]

Processing tickers:   3%|▎         | 222/6717 [00:45<21:59,  4.92it/s]

Processing tickers:   3%|▎         | 223/6717 [00:45<22:22,  4.84it/s]

Processing tickers:   3%|▎         | 224/6717 [00:45<22:13,  4.87it/s]

Processing tickers:   3%|▎         | 225/6717 [00:45<22:03,  4.90it/s]

Processing tickers:   3%|▎         | 226/6717 [00:45<22:05,  4.90it/s]

Processing tickers:   3%|▎         | 227/6717 [00:46<22:00,  4.92it/s]

Processing tickers:   3%|▎         | 228/6717 [00:46<22:12,  4.87it/s]

Processing tickers:   3%|▎         | 229/6717 [00:46<22:10,  4.88it/s]

Processing tickers:   3%|▎         | 230/6717 [00:46<22:03,  4.90it/s]

Processing tickers:   3%|▎         | 231/6717 [00:46<21:55,  4.93it/s]

Processing tickers:   3%|▎         | 232/6717 [00:47<21:47,  4.96it/s]

Processing tickers:   3%|▎         | 233/6717 [00:47<21:46,  4.96it/s]

Processing tickers:   3%|▎         | 234/6717 [00:47<22:38,  4.77it/s]

Processing tickers:   3%|▎         | 235/6717 [00:47<22:24,  4.82it/s]

Processing tickers:   4%|▎         | 236/6717 [00:48<22:21,  4.83it/s]

Processing tickers:   4%|▎         | 237/6717 [00:48<22:09,  4.87it/s]

Processing tickers:   4%|▎         | 238/6717 [00:48<22:01,  4.90it/s]

Processing tickers:   4%|▎         | 239/6717 [00:48<23:02,  4.69it/s]

Processing tickers:   4%|▎         | 240/6717 [00:48<22:56,  4.71it/s]

Processing tickers:   4%|▎         | 241/6717 [00:49<22:45,  4.74it/s]

Processing tickers:   4%|▎         | 242/6717 [00:49<22:24,  4.82it/s]

Processing tickers:   4%|▎         | 243/6717 [00:49<22:04,  4.89it/s]

Processing tickers:   4%|▎         | 244/6717 [00:49<22:41,  4.75it/s]

Processing tickers:   4%|▎         | 245/6717 [00:49<22:35,  4.77it/s]

Processing tickers:   4%|▎         | 246/6717 [00:50<22:14,  4.85it/s]

Processing tickers:   4%|▎         | 247/6717 [00:50<21:57,  4.91it/s]

Processing tickers:   4%|▎         | 248/6717 [00:50<22:03,  4.89it/s]

Processing tickers:   4%|▎         | 249/6717 [00:50<21:56,  4.91it/s]

Processing tickers:   4%|▎         | 250/6717 [00:50<22:05,  4.88it/s]

Processing tickers:   4%|▎         | 251/6717 [00:51<21:58,  4.90it/s]

Processing tickers:   4%|▍         | 252/6717 [00:51<21:51,  4.93it/s]

Processing tickers:   4%|▍         | 253/6717 [00:51<22:02,  4.89it/s]

Processing tickers:   4%|▍         | 254/6717 [00:51<21:52,  4.92it/s]

Processing tickers:   4%|▍         | 255/6717 [00:51<21:56,  4.91it/s]

Processing tickers:   4%|▍         | 256/6717 [00:52<21:57,  4.90it/s]

Processing tickers:   4%|▍         | 257/6717 [00:52<21:55,  4.91it/s]

Processing tickers:   4%|▍         | 258/6717 [00:52<21:49,  4.93it/s]

Processing tickers:   4%|▍         | 259/6717 [00:52<21:50,  4.93it/s]

Processing tickers:   4%|▍         | 260/6717 [00:52<21:49,  4.93it/s]

Processing tickers:   4%|▍         | 261/6717 [00:53<21:56,  4.91it/s]

Processing tickers:   4%|▍         | 262/6717 [00:53<22:10,  4.85it/s]

Processing tickers:   4%|▍         | 263/6717 [00:53<22:05,  4.87it/s]

Processing tickers:   4%|▍         | 264/6717 [00:53<21:57,  4.90it/s]

Processing tickers:   4%|▍         | 265/6717 [00:53<21:59,  4.89it/s]

Processing tickers:   4%|▍         | 266/6717 [00:54<21:51,  4.92it/s]

Processing tickers:   4%|▍         | 267/6717 [00:54<21:43,  4.95it/s]

Processing tickers:   4%|▍         | 268/6717 [00:54<22:40,  4.74it/s]

Processing tickers:   4%|▍         | 269/6717 [00:54<22:22,  4.80it/s]

Processing tickers:   4%|▍         | 270/6717 [00:55<22:53,  4.70it/s]

Processing tickers:   4%|▍         | 271/6717 [00:55<22:54,  4.69it/s]

Processing tickers:   4%|▍         | 272/6717 [00:55<22:31,  4.77it/s]

Processing tickers:   4%|▍         | 273/6717 [00:55<22:31,  4.77it/s]

Processing tickers:   4%|▍         | 274/6717 [00:55<22:15,  4.82it/s]

Processing tickers:   4%|▍         | 275/6717 [00:56<22:02,  4.87it/s]

Processing tickers:   4%|▍         | 276/6717 [00:56<21:58,  4.88it/s]

Processing tickers:   4%|▍         | 277/6717 [00:56<21:59,  4.88it/s]

Processing tickers:   4%|▍         | 278/6717 [00:56<21:50,  4.91it/s]

Processing tickers:   4%|▍         | 279/6717 [00:56<21:46,  4.93it/s]

Processing tickers:   4%|▍         | 280/6717 [00:57<21:42,  4.94it/s]

Processing tickers:   4%|▍         | 281/6717 [00:57<21:40,  4.95it/s]

Processing tickers:   4%|▍         | 282/6717 [00:57<21:39,  4.95it/s]

Processing tickers:   4%|▍         | 283/6717 [00:57<21:44,  4.93it/s]

Processing tickers:   4%|▍         | 284/6717 [00:57<21:44,  4.93it/s]

Processing tickers:   4%|▍         | 285/6717 [00:58<22:09,  4.84it/s]

Processing tickers:   4%|▍         | 286/6717 [00:58<22:05,  4.85it/s]

Processing tickers:   4%|▍         | 287/6717 [00:58<22:15,  4.81it/s]

Processing tickers:   4%|▍         | 288/6717 [00:58<22:00,  4.87it/s]

Processing tickers:   4%|▍         | 289/6717 [00:58<21:53,  4.89it/s]

Processing tickers:   4%|▍         | 290/6717 [00:59<21:57,  4.88it/s]

Processing tickers:   4%|▍         | 291/6717 [00:59<21:56,  4.88it/s]

Processing tickers:   4%|▍         | 292/6717 [00:59<21:52,  4.90it/s]

Processing tickers:   4%|▍         | 293/6717 [00:59<21:51,  4.90it/s]

Processing tickers:   4%|▍         | 294/6717 [00:59<21:59,  4.87it/s]

Processing tickers:   4%|▍         | 295/6717 [01:00<22:06,  4.84it/s]

Processing tickers:   4%|▍         | 296/6717 [01:00<22:48,  4.69it/s]

Processing tickers:   4%|▍         | 297/6717 [01:00<22:55,  4.67it/s]

Processing tickers:   4%|▍         | 298/6717 [01:00<22:31,  4.75it/s]

Processing tickers:   4%|▍         | 299/6717 [01:00<22:08,  4.83it/s]

Processing tickers:   4%|▍         | 300/6717 [01:01<21:59,  4.86it/s]

Processing tickers:   4%|▍         | 301/6717 [01:01<22:06,  4.84it/s]

Processing tickers:   4%|▍         | 302/6717 [01:01<22:12,  4.82it/s]

Processing tickers:   5%|▍         | 303/6717 [01:01<22:19,  4.79it/s]

Processing tickers:   5%|▍         | 304/6717 [01:02<22:18,  4.79it/s]

Processing tickers:   5%|▍         | 305/6717 [01:02<22:05,  4.84it/s]

Processing tickers:   5%|▍         | 306/6717 [01:02<21:55,  4.87it/s]

Processing tickers:   5%|▍         | 307/6717 [01:02<21:48,  4.90it/s]

Processing tickers:   5%|▍         | 308/6717 [01:02<21:44,  4.91it/s]

Processing tickers:   5%|▍         | 309/6717 [01:03<21:51,  4.89it/s]

Processing tickers:   5%|▍         | 310/6717 [01:03<22:12,  4.81it/s]

Processing tickers:   5%|▍         | 311/6717 [01:03<22:00,  4.85it/s]

Processing tickers:   5%|▍         | 312/6717 [01:03<21:54,  4.87it/s]

Processing tickers:   5%|▍         | 313/6717 [01:03<21:56,  4.86it/s]

Processing tickers:   5%|▍         | 314/6717 [01:04<21:48,  4.89it/s]

Processing tickers:   5%|▍         | 315/6717 [01:04<21:45,  4.91it/s]

Processing tickers:   5%|▍         | 316/6717 [01:04<22:02,  4.84it/s]

Processing tickers:   5%|▍         | 317/6717 [01:04<21:47,  4.89it/s]

Processing tickers:   5%|▍         | 318/6717 [01:04<22:10,  4.81it/s]

Processing tickers:   5%|▍         | 319/6717 [01:05<21:55,  4.86it/s]

Processing tickers:   5%|▍         | 320/6717 [01:05<21:38,  4.93it/s]

Processing tickers:   5%|▍         | 321/6717 [01:05<22:04,  4.83it/s]

Processing tickers:   5%|▍         | 322/6717 [01:05<21:52,  4.87it/s]

Processing tickers:   5%|▍         | 323/6717 [01:05<21:50,  4.88it/s]

Processing tickers:   5%|▍         | 324/6717 [01:06<22:20,  4.77it/s]

Processing tickers:   5%|▍         | 325/6717 [01:06<22:08,  4.81it/s]

Processing tickers:   5%|▍         | 326/6717 [01:06<21:58,  4.85it/s]

Processing tickers:   5%|▍         | 327/6717 [01:06<22:00,  4.84it/s]

Processing tickers:   5%|▍         | 328/6717 [01:06<21:47,  4.89it/s]

Processing tickers:   5%|▍         | 329/6717 [01:07<21:42,  4.90it/s]

Processing tickers:   5%|▍         | 330/6717 [01:07<21:38,  4.92it/s]

Processing tickers:   5%|▍         | 331/6717 [01:07<21:37,  4.92it/s]

Processing tickers:   5%|▍         | 332/6717 [01:07<21:30,  4.95it/s]

Processing tickers:   5%|▍         | 333/6717 [01:07<21:37,  4.92it/s]

Processing tickers:   5%|▍         | 334/6717 [01:08<21:35,  4.93it/s]

Processing tickers:   5%|▍         | 335/6717 [01:08<21:40,  4.91it/s]

Processing tickers:   5%|▌         | 336/6717 [01:08<22:00,  4.83it/s]

Processing tickers:   5%|▌         | 337/6717 [01:08<21:52,  4.86it/s]

Processing tickers:   5%|▌         | 338/6717 [01:08<21:45,  4.89it/s]

Processing tickers:   5%|▌         | 339/6717 [01:09<22:31,  4.72it/s]

Processing tickers:   5%|▌         | 340/6717 [01:09<22:07,  4.80it/s]

Processing tickers:   5%|▌         | 341/6717 [01:09<22:32,  4.71it/s]

Processing tickers:   5%|▌         | 342/6717 [01:09<22:04,  4.81it/s]

Processing tickers:   5%|▌         | 343/6717 [01:10<21:51,  4.86it/s]

Processing tickers:   5%|▌         | 344/6717 [01:10<21:40,  4.90it/s]

Processing tickers:   5%|▌         | 345/6717 [01:10<21:34,  4.92it/s]

Processing tickers:   5%|▌         | 346/6717 [01:10<21:25,  4.96it/s]

Processing tickers:   5%|▌         | 347/6717 [01:10<21:34,  4.92it/s]

Processing tickers:   5%|▌         | 348/6717 [01:11<21:28,  4.94it/s]

Processing tickers:   5%|▌         | 349/6717 [01:11<21:27,  4.95it/s]

Processing tickers:   5%|▌         | 350/6717 [01:11<22:07,  4.80it/s]

Processing tickers:   5%|▌         | 351/6717 [01:11<22:05,  4.80it/s]

Processing tickers:   5%|▌         | 352/6717 [01:11<22:18,  4.75it/s]

Processing tickers:   5%|▌         | 353/6717 [01:12<22:03,  4.81it/s]

Processing tickers:   5%|▌         | 354/6717 [01:12<22:18,  4.75it/s]

Processing tickers:   5%|▌         | 355/6717 [01:12<21:55,  4.83it/s]

Processing tickers:   5%|▌         | 356/6717 [01:12<21:50,  4.85it/s]

Processing tickers:   5%|▌         | 357/6717 [01:12<21:42,  4.88it/s]

Processing tickers:   5%|▌         | 358/6717 [01:13<21:33,  4.92it/s]

Processing tickers:   5%|▌         | 359/6717 [01:13<21:31,  4.92it/s]

Processing tickers:   5%|▌         | 360/6717 [01:13<21:24,  4.95it/s]

Processing tickers:   5%|▌         | 361/6717 [01:13<21:25,  4.94it/s]

Processing tickers:   5%|▌         | 362/6717 [01:13<21:17,  4.98it/s]

Processing tickers:   5%|▌         | 363/6717 [01:14<21:11,  5.00it/s]

Processing tickers:   5%|▌         | 364/6717 [01:14<21:12,  4.99it/s]

Processing tickers:   5%|▌         | 365/6717 [01:14<21:12,  4.99it/s]

Processing tickers:   5%|▌         | 366/6717 [01:14<21:11,  5.00it/s]

Processing tickers:   5%|▌         | 367/6717 [01:14<21:17,  4.97it/s]

Processing tickers:   5%|▌         | 368/6717 [01:15<21:23,  4.95it/s]

Processing tickers:   5%|▌         | 369/6717 [01:15<21:29,  4.92it/s]

Processing tickers:   6%|▌         | 370/6717 [01:15<21:34,  4.90it/s]

Processing tickers:   6%|▌         | 371/6717 [01:15<21:27,  4.93it/s]

Processing tickers:   6%|▌         | 372/6717 [01:15<21:56,  4.82it/s]

Processing tickers:   6%|▌         | 373/6717 [01:16<21:41,  4.87it/s]

Processing tickers:   6%|▌         | 374/6717 [01:16<21:52,  4.83it/s]

Processing tickers:   6%|▌         | 375/6717 [01:16<21:47,  4.85it/s]

Processing tickers:   6%|▌         | 376/6717 [01:16<21:50,  4.84it/s]

Processing tickers:   6%|▌         | 377/6717 [01:16<21:51,  4.84it/s]

Processing tickers:   6%|▌         | 378/6717 [01:17<21:37,  4.89it/s]

Processing tickers:   6%|▌         | 379/6717 [01:17<21:31,  4.91it/s]

Processing tickers:   6%|▌         | 380/6717 [01:17<21:57,  4.81it/s]

Processing tickers:   6%|▌         | 381/6717 [01:17<21:48,  4.84it/s]

Processing tickers:   6%|▌         | 382/6717 [01:18<21:41,  4.87it/s]

Processing tickers:   6%|▌         | 383/6717 [01:18<21:57,  4.81it/s]

Processing tickers:   6%|▌         | 384/6717 [01:18<21:58,  4.80it/s]

Processing tickers:   6%|▌         | 385/6717 [01:18<22:30,  4.69it/s]

Processing tickers:   6%|▌         | 386/6717 [01:18<22:15,  4.74it/s]

Processing tickers:   6%|▌         | 387/6717 [01:19<21:50,  4.83it/s]

Processing tickers:   6%|▌         | 388/6717 [01:19<21:51,  4.83it/s]

Processing tickers:   6%|▌         | 389/6717 [01:19<22:05,  4.78it/s]

Processing tickers:   6%|▌         | 390/6717 [01:19<21:48,  4.84it/s]

Processing tickers:   6%|▌         | 391/6717 [01:19<21:57,  4.80it/s]

Processing tickers:   6%|▌         | 392/6717 [01:20<21:42,  4.86it/s]

Processing tickers:   6%|▌         | 393/6717 [01:20<21:34,  4.89it/s]

Processing tickers:   6%|▌         | 394/6717 [01:20<22:00,  4.79it/s]

Processing tickers:   6%|▌         | 395/6717 [01:20<21:43,  4.85it/s]

Processing tickers:   6%|▌         | 396/6717 [01:20<21:33,  4.88it/s]

Processing tickers:   6%|▌         | 397/6717 [01:21<21:38,  4.87it/s]

Processing tickers:   6%|▌         | 398/6717 [01:21<21:28,  4.90it/s]

Processing tickers:   6%|▌         | 399/6717 [01:21<21:27,  4.91it/s]

Processing tickers:   6%|▌         | 400/6717 [01:21<21:21,  4.93it/s]

Processing tickers:   6%|▌         | 401/6717 [01:21<21:14,  4.95it/s]

Processing tickers:   6%|▌         | 402/6717 [01:22<21:12,  4.96it/s]

Processing tickers:   6%|▌         | 403/6717 [01:22<21:28,  4.90it/s]

Processing tickers:   6%|▌         | 404/6717 [01:22<21:30,  4.89it/s]

Processing tickers:   6%|▌         | 405/6717 [01:22<21:18,  4.94it/s]

Processing tickers:   6%|▌         | 406/6717 [01:22<21:14,  4.95it/s]

Processing tickers:   6%|▌         | 407/6717 [01:23<21:24,  4.91it/s]

Processing tickers:   6%|▌         | 408/6717 [01:23<21:19,  4.93it/s]

Processing tickers:   6%|▌         | 409/6717 [01:23<21:56,  4.79it/s]

Processing tickers:   6%|▌         | 410/6717 [01:23<21:45,  4.83it/s]

Processing tickers:   6%|▌         | 411/6717 [01:23<21:30,  4.88it/s]

Processing tickers:   6%|▌         | 412/6717 [01:24<21:31,  4.88it/s]

Processing tickers:   6%|▌         | 413/6717 [01:24<21:32,  4.88it/s]

Processing tickers:   6%|▌         | 414/6717 [01:24<21:29,  4.89it/s]

Processing tickers:   6%|▌         | 415/6717 [01:24<21:22,  4.91it/s]

Processing tickers:   6%|▌         | 416/6717 [01:25<21:18,  4.93it/s]

Processing tickers:   6%|▌         | 417/6717 [01:25<21:21,  4.92it/s]

Processing tickers:   6%|▌         | 418/6717 [01:25<21:17,  4.93it/s]

Processing tickers:   6%|▌         | 419/6717 [01:25<21:15,  4.94it/s]

Processing tickers:   6%|▋         | 420/6717 [01:25<21:11,  4.95it/s]

Processing tickers:   6%|▋         | 421/6717 [01:26<21:07,  4.97it/s]

Processing tickers:   6%|▋         | 422/6717 [01:26<21:07,  4.97it/s]

Processing tickers:   6%|▋         | 423/6717 [01:26<21:07,  4.97it/s]

Processing tickers:   6%|▋         | 424/6717 [01:26<21:04,  4.98it/s]

Processing tickers:   6%|▋         | 425/6717 [01:26<21:06,  4.97it/s]

Processing tickers:   6%|▋         | 426/6717 [01:27<21:26,  4.89it/s]

Processing tickers:   6%|▋         | 427/6717 [01:27<21:26,  4.89it/s]

Processing tickers:   6%|▋         | 428/6717 [01:27<21:24,  4.90it/s]

Processing tickers:   6%|▋         | 429/6717 [01:27<21:19,  4.91it/s]

Processing tickers:   6%|▋         | 430/6717 [01:27<21:43,  4.82it/s]

Processing tickers:   6%|▋         | 431/6717 [01:28<21:33,  4.86it/s]

Processing tickers:   6%|▋         | 432/6717 [01:28<21:33,  4.86it/s]

Processing tickers:   6%|▋         | 433/6717 [01:28<21:37,  4.84it/s]

Processing tickers:   6%|▋         | 434/6717 [01:28<21:28,  4.88it/s]

Processing tickers:   6%|▋         | 435/6717 [01:28<21:24,  4.89it/s]

Processing tickers:   6%|▋         | 436/6717 [01:29<21:15,  4.92it/s]

Processing tickers:   7%|▋         | 437/6717 [01:29<21:08,  4.95it/s]

Processing tickers:   7%|▋         | 438/6717 [01:29<21:26,  4.88it/s]

Processing tickers:   7%|▋         | 439/6717 [01:29<21:37,  4.84it/s]

Processing tickers:   7%|▋         | 440/6717 [01:29<21:37,  4.84it/s]

Processing tickers:   7%|▋         | 441/6717 [01:30<21:28,  4.87it/s]

Processing tickers:   7%|▋         | 442/6717 [01:30<21:30,  4.86it/s]

Processing tickers:   7%|▋         | 443/6717 [01:30<21:45,  4.80it/s]

Processing tickers:   7%|▋         | 444/6717 [01:30<21:47,  4.80it/s]

Processing tickers:   7%|▋         | 445/6717 [01:30<21:37,  4.83it/s]

Processing tickers:   7%|▋         | 446/6717 [01:31<21:32,  4.85it/s]

Processing tickers:   7%|▋         | 447/6717 [01:31<21:22,  4.89it/s]

Processing tickers:   7%|▋         | 448/6717 [01:31<21:21,  4.89it/s]

Processing tickers:   7%|▋         | 449/6717 [01:31<21:13,  4.92it/s]

Processing tickers:   7%|▋         | 450/6717 [01:31<21:11,  4.93it/s]

Processing tickers:   7%|▋         | 451/6717 [01:32<21:10,  4.93it/s]

Processing tickers:   7%|▋         | 452/6717 [01:32<21:01,  4.97it/s]

Processing tickers:   7%|▋         | 453/6717 [01:32<21:04,  4.95it/s]

Processing tickers:   7%|▋         | 454/6717 [01:32<21:02,  4.96it/s]

Processing tickers:   7%|▋         | 455/6717 [01:32<20:57,  4.98it/s]

Processing tickers:   7%|▋         | 456/6717 [01:33<20:57,  4.98it/s]

Processing tickers:   7%|▋         | 457/6717 [01:33<21:05,  4.95it/s]

Processing tickers:   7%|▋         | 458/6717 [01:33<21:07,  4.94it/s]

Processing tickers:   7%|▋         | 459/6717 [01:33<21:04,  4.95it/s]

Processing tickers:   7%|▋         | 460/6717 [01:33<21:06,  4.94it/s]

Processing tickers:   7%|▋         | 461/6717 [01:34<21:12,  4.92it/s]

Processing tickers:   7%|▋         | 462/6717 [01:34<21:20,  4.88it/s]

Processing tickers:   7%|▋         | 463/6717 [01:34<21:18,  4.89it/s]

Processing tickers:   7%|▋         | 464/6717 [01:34<21:39,  4.81it/s]

Processing tickers:   7%|▋         | 465/6717 [01:35<21:26,  4.86it/s]

Processing tickers:   7%|▋         | 466/6717 [01:35<21:15,  4.90it/s]

Processing tickers:   7%|▋         | 467/6717 [01:35<21:09,  4.92it/s]

Processing tickers:   7%|▋         | 468/6717 [01:35<21:05,  4.94it/s]

Processing tickers:   7%|▋         | 469/6717 [01:35<21:06,  4.93it/s]

Processing tickers:   7%|▋         | 470/6717 [01:36<21:08,  4.92it/s]

Processing tickers:   7%|▋         | 471/6717 [01:36<21:06,  4.93it/s]

Processing tickers:   7%|▋         | 472/6717 [01:36<21:50,  4.76it/s]

Processing tickers:   7%|▋         | 473/6717 [01:36<21:34,  4.82it/s]

Processing tickers:   7%|▋         | 474/6717 [01:36<21:25,  4.86it/s]

Processing tickers:   7%|▋         | 475/6717 [01:37<21:12,  4.91it/s]

Processing tickers:   7%|▋         | 476/6717 [01:37<21:05,  4.93it/s]

Processing tickers:   7%|▋         | 477/6717 [01:37<21:06,  4.93it/s]

Processing tickers:   7%|▋         | 478/6717 [01:37<21:28,  4.84it/s]

Processing tickers:   7%|▋         | 479/6717 [01:37<21:20,  4.87it/s]

Processing tickers:   7%|▋         | 480/6717 [01:38<21:16,  4.89it/s]

Processing tickers:   7%|▋         | 481/6717 [01:38<21:11,  4.90it/s]

Processing tickers:   7%|▋         | 482/6717 [01:38<21:03,  4.94it/s]

Processing tickers:   7%|▋         | 483/6717 [01:38<21:02,  4.94it/s]

Processing tickers:   7%|▋         | 484/6717 [01:38<20:57,  4.96it/s]

Processing tickers:   7%|▋         | 485/6717 [01:39<21:03,  4.93it/s]

Processing tickers:   7%|▋         | 486/6717 [01:39<21:19,  4.87it/s]

Processing tickers:   7%|▋         | 487/6717 [01:39<21:11,  4.90it/s]

Processing tickers:   7%|▋         | 488/6717 [01:39<21:03,  4.93it/s]

Processing tickers:   7%|▋         | 489/6717 [01:39<21:01,  4.94it/s]

Processing tickers:   7%|▋         | 490/6717 [01:40<21:04,  4.93it/s]

Processing tickers:   7%|▋         | 491/6717 [01:40<21:08,  4.91it/s]

Processing tickers:   7%|▋         | 492/6717 [01:40<21:21,  4.86it/s]

Processing tickers:   7%|▋         | 493/6717 [01:40<21:08,  4.91it/s]

Processing tickers:   7%|▋         | 494/6717 [01:40<21:13,  4.89it/s]

Processing tickers:   7%|▋         | 495/6717 [01:41<21:12,  4.89it/s]

Processing tickers:   7%|▋         | 496/6717 [01:41<21:05,  4.92it/s]

Processing tickers:   7%|▋         | 497/6717 [01:41<21:03,  4.92it/s]

Processing tickers:   7%|▋         | 498/6717 [01:41<21:19,  4.86it/s]

Processing tickers:   7%|▋         | 499/6717 [01:41<21:39,  4.79it/s]

Processing tickers:   7%|▋         | 500/6717 [01:42<21:21,  4.85it/s]

Processing tickers:   7%|▋         | 501/6717 [01:42<21:26,  4.83it/s]

Processing tickers:   7%|▋         | 502/6717 [01:42<21:27,  4.83it/s]

Processing tickers:   7%|▋         | 503/6717 [01:42<21:20,  4.85it/s]

Processing tickers:   8%|▊         | 504/6717 [01:42<21:15,  4.87it/s]

Processing tickers:   8%|▊         | 505/6717 [01:43<21:01,  4.93it/s]

Processing tickers:   8%|▊         | 506/6717 [01:43<21:08,  4.89it/s]

Processing tickers:   8%|▊         | 507/6717 [01:43<21:19,  4.85it/s]

Processing tickers:   8%|▊         | 508/6717 [01:43<21:07,  4.90it/s]

Processing tickers:   8%|▊         | 509/6717 [01:43<21:02,  4.92it/s]

Processing tickers:   8%|▊         | 510/6717 [01:44<20:55,  4.94it/s]

Processing tickers:   8%|▊         | 511/6717 [01:44<20:56,  4.94it/s]

Processing tickers:   8%|▊         | 512/6717 [01:44<20:53,  4.95it/s]

Processing tickers:   8%|▊         | 513/6717 [01:44<20:52,  4.95it/s]

Processing tickers:   8%|▊         | 514/6717 [01:45<21:06,  4.90it/s]

Processing tickers:   8%|▊         | 515/6717 [01:45<21:04,  4.90it/s]

Processing tickers:   8%|▊         | 516/6717 [01:45<21:48,  4.74it/s]

Processing tickers:   8%|▊         | 517/6717 [01:45<21:26,  4.82it/s]

Processing tickers:   8%|▊         | 518/6717 [01:45<21:09,  4.88it/s]

Processing tickers:   8%|▊         | 519/6717 [01:46<22:02,  4.69it/s]

Processing tickers:   8%|▊         | 520/6717 [01:46<21:41,  4.76it/s]

Processing tickers:   8%|▊         | 521/6717 [01:46<21:27,  4.81it/s]

Processing tickers:   8%|▊         | 522/6717 [01:46<21:18,  4.85it/s]

Processing tickers:   8%|▊         | 523/6717 [01:46<21:17,  4.85it/s]

Processing tickers:   8%|▊         | 524/6717 [01:47<21:26,  4.81it/s]

Processing tickers:   8%|▊         | 525/6717 [01:47<21:20,  4.84it/s]

Processing tickers:   8%|▊         | 526/6717 [01:47<21:26,  4.81it/s]

Processing tickers:   8%|▊         | 527/6717 [01:47<21:10,  4.87it/s]

Processing tickers:   8%|▊         | 528/6717 [01:47<21:12,  4.86it/s]

Processing tickers:   8%|▊         | 529/6717 [01:48<21:02,  4.90it/s]

Processing tickers:   8%|▊         | 530/6717 [01:48<21:13,  4.86it/s]

Processing tickers:   8%|▊         | 531/6717 [01:48<21:12,  4.86it/s]

Processing tickers:   8%|▊         | 532/6717 [01:48<21:18,  4.84it/s]

Processing tickers:   8%|▊         | 533/6717 [01:48<21:05,  4.89it/s]

Processing tickers:   8%|▊         | 534/6717 [01:49<21:05,  4.89it/s]

Processing tickers:   8%|▊         | 535/6717 [01:49<21:00,  4.90it/s]

Processing tickers:   8%|▊         | 536/6717 [01:49<20:52,  4.94it/s]

Processing tickers:   8%|▊         | 537/6717 [01:49<20:50,  4.94it/s]

Processing tickers:   8%|▊         | 538/6717 [01:49<20:48,  4.95it/s]

Processing tickers:   8%|▊         | 539/6717 [01:50<20:40,  4.98it/s]

Processing tickers:   8%|▊         | 540/6717 [01:50<20:43,  4.97it/s]

Processing tickers:   8%|▊         | 541/6717 [01:50<20:36,  4.99it/s]

Processing tickers:   8%|▊         | 542/6717 [01:50<20:39,  4.98it/s]

Processing tickers:   8%|▊         | 543/6717 [01:50<20:42,  4.97it/s]

Processing tickers:   8%|▊         | 544/6717 [01:51<20:58,  4.91it/s]

Processing tickers:   8%|▊         | 545/6717 [01:51<20:46,  4.95it/s]

Processing tickers:   8%|▊         | 546/6717 [01:51<20:42,  4.97it/s]

Processing tickers:   8%|▊         | 547/6717 [01:51<20:51,  4.93it/s]

Processing tickers:   8%|▊         | 548/6717 [01:51<21:02,  4.89it/s]

Processing tickers:   8%|▊         | 549/6717 [01:52<20:59,  4.90it/s]

Processing tickers:   8%|▊         | 550/6717 [01:52<21:11,  4.85it/s]

Processing tickers:   8%|▊         | 551/6717 [01:52<21:08,  4.86it/s]

Processing tickers:   8%|▊         | 552/6717 [01:52<21:00,  4.89it/s]

Processing tickers:   8%|▊         | 553/6717 [01:53<21:07,  4.86it/s]

Processing tickers:   8%|▊         | 554/6717 [01:53<21:01,  4.88it/s]

Processing tickers:   8%|▊         | 555/6717 [01:53<21:13,  4.84it/s]

Processing tickers:   8%|▊         | 556/6717 [01:53<21:00,  4.89it/s]

Processing tickers:   8%|▊         | 557/6717 [01:53<20:53,  4.91it/s]

Processing tickers:   8%|▊         | 558/6717 [01:54<20:50,  4.92it/s]

Processing tickers:   8%|▊         | 559/6717 [01:54<20:50,  4.92it/s]

Processing tickers:   8%|▊         | 560/6717 [01:54<21:15,  4.83it/s]

Processing tickers:   8%|▊         | 561/6717 [01:54<21:06,  4.86it/s]

Processing tickers:   8%|▊         | 562/6717 [01:54<20:58,  4.89it/s]

Processing tickers:   8%|▊         | 563/6717 [01:55<20:54,  4.90it/s]

Processing tickers:   8%|▊         | 564/6717 [01:55<21:02,  4.87it/s]

Processing tickers:   8%|▊         | 565/6717 [01:55<20:51,  4.92it/s]

Processing tickers:   8%|▊         | 566/6717 [01:55<20:49,  4.92it/s]

Processing tickers:   8%|▊         | 567/6717 [01:55<20:43,  4.95it/s]

Processing tickers:   8%|▊         | 568/6717 [01:56<20:39,  4.96it/s]

Processing tickers:   8%|▊         | 569/6717 [01:56<20:38,  4.96it/s]

Processing tickers:   8%|▊         | 570/6717 [01:56<20:36,  4.97it/s]

Processing tickers:   9%|▊         | 571/6717 [01:56<20:43,  4.94it/s]

Processing tickers:   9%|▊         | 572/6717 [01:56<20:47,  4.93it/s]

Processing tickers:   9%|▊         | 573/6717 [01:57<20:44,  4.94it/s]

Processing tickers:   9%|▊         | 574/6717 [01:57<20:39,  4.96it/s]

Processing tickers:   9%|▊         | 575/6717 [01:57<20:33,  4.98it/s]

Processing tickers:   9%|▊         | 576/6717 [01:57<20:39,  4.95it/s]

Processing tickers:   9%|▊         | 577/6717 [01:57<20:39,  4.95it/s]

Processing tickers:   9%|▊         | 578/6717 [01:58<20:40,  4.95it/s]

Processing tickers:   9%|▊         | 579/6717 [01:58<20:47,  4.92it/s]

Processing tickers:   9%|▊         | 580/6717 [01:58<21:00,  4.87it/s]

Processing tickers:   9%|▊         | 581/6717 [01:58<21:05,  4.85it/s]

Processing tickers:   9%|▊         | 582/6717 [01:58<21:21,  4.79it/s]

Processing tickers:   9%|▊         | 583/6717 [01:59<21:15,  4.81it/s]

Processing tickers:   9%|▊         | 584/6717 [01:59<21:04,  4.85it/s]

Processing tickers:   9%|▊         | 585/6717 [01:59<21:14,  4.81it/s]

Processing tickers:   9%|▊         | 586/6717 [01:59<20:57,  4.87it/s]

Processing tickers:   9%|▊         | 587/6717 [01:59<21:00,  4.86it/s]

Processing tickers:   9%|▉         | 588/6717 [02:00<20:48,  4.91it/s]

Processing tickers:   9%|▉         | 589/6717 [02:00<20:44,  4.92it/s]

Processing tickers:   9%|▉         | 590/6717 [02:00<21:40,  4.71it/s]

Processing tickers:   9%|▉         | 591/6717 [02:00<21:52,  4.67it/s]

Processing tickers:   9%|▉         | 592/6717 [02:00<21:21,  4.78it/s]

Processing tickers:   9%|▉         | 593/6717 [02:01<21:06,  4.84it/s]

Processing tickers:   9%|▉         | 594/6717 [02:01<20:51,  4.89it/s]

Processing tickers:   9%|▉         | 595/6717 [02:01<20:39,  4.94it/s]

Processing tickers:   9%|▉         | 596/6717 [02:01<20:30,  4.97it/s]

Processing tickers:   9%|▉         | 597/6717 [02:01<20:32,  4.97it/s]

Processing tickers:   9%|▉         | 598/6717 [02:02<20:33,  4.96it/s]

Processing tickers:   9%|▉         | 599/6717 [02:02<20:44,  4.92it/s]

Processing tickers:   9%|▉         | 600/6717 [02:02<20:38,  4.94it/s]

Processing tickers:   9%|▉         | 601/6717 [02:02<20:37,  4.94it/s]

Processing tickers:   9%|▉         | 602/6717 [02:03<20:33,  4.96it/s]

Processing tickers:   9%|▉         | 603/6717 [02:03<20:22,  5.00it/s]

Processing tickers:   9%|▉         | 604/6717 [02:03<20:18,  5.02it/s]

Processing tickers:   9%|▉         | 605/6717 [02:03<20:32,  4.96it/s]

Processing tickers:   9%|▉         | 606/6717 [02:03<21:04,  4.83it/s]

Processing tickers:   9%|▉         | 607/6717 [02:04<20:51,  4.88it/s]

Processing tickers:   9%|▉         | 608/6717 [02:04<20:42,  4.92it/s]

Processing tickers:   9%|▉         | 609/6717 [02:04<20:36,  4.94it/s]

Processing tickers:   9%|▉         | 610/6717 [02:04<20:34,  4.95it/s]

Processing tickers:   9%|▉         | 611/6717 [02:04<20:32,  4.96it/s]

Processing tickers:   9%|▉         | 612/6717 [02:05<20:30,  4.96it/s]

Processing tickers:   9%|▉         | 613/6717 [02:05<20:29,  4.96it/s]

Processing tickers:   9%|▉         | 614/6717 [02:05<20:50,  4.88it/s]

Processing tickers:   9%|▉         | 615/6717 [02:05<20:43,  4.91it/s]

Processing tickers:   9%|▉         | 616/6717 [02:05<20:40,  4.92it/s]

Processing tickers:   9%|▉         | 617/6717 [02:06<20:32,  4.95it/s]

Processing tickers:   9%|▉         | 618/6717 [02:06<20:47,  4.89it/s]

Processing tickers:   9%|▉         | 619/6717 [02:06<20:38,  4.92it/s]

Processing tickers:   9%|▉         | 620/6717 [02:06<20:30,  4.96it/s]

Processing tickers:   9%|▉         | 621/6717 [02:06<20:28,  4.96it/s]

Processing tickers:   9%|▉         | 622/6717 [02:07<20:53,  4.86it/s]

Processing tickers:   9%|▉         | 623/6717 [02:07<20:41,  4.91it/s]

Processing tickers:   9%|▉         | 624/6717 [02:07<20:35,  4.93it/s]

Processing tickers:   9%|▉         | 625/6717 [02:07<20:28,  4.96it/s]

Processing tickers:   9%|▉         | 626/6717 [02:07<20:28,  4.96it/s]

Processing tickers:   9%|▉         | 627/6717 [02:08<20:29,  4.95it/s]

Processing tickers:   9%|▉         | 628/6717 [02:08<20:50,  4.87it/s]

Processing tickers:   9%|▉         | 629/6717 [02:08<21:06,  4.81it/s]

Processing tickers:   9%|▉         | 630/6717 [02:08<20:53,  4.86it/s]

Processing tickers:   9%|▉         | 631/6717 [02:08<20:56,  4.85it/s]

Processing tickers:   9%|▉         | 632/6717 [02:09<20:51,  4.86it/s]

Processing tickers:   9%|▉         | 633/6717 [02:09<20:48,  4.87it/s]

Processing tickers:   9%|▉         | 634/6717 [02:09<21:01,  4.82it/s]

Processing tickers:   9%|▉         | 635/6717 [02:09<20:56,  4.84it/s]

Processing tickers:   9%|▉         | 636/6717 [02:09<21:02,  4.82it/s]

Processing tickers:   9%|▉         | 637/6717 [02:10<20:51,  4.86it/s]

Processing tickers:   9%|▉         | 638/6717 [02:10<20:43,  4.89it/s]

Processing tickers:  10%|▉         | 639/6717 [02:10<20:33,  4.93it/s]

Processing tickers:  10%|▉         | 640/6717 [02:10<20:30,  4.94it/s]

Processing tickers:  10%|▉         | 641/6717 [02:10<20:36,  4.91it/s]

Processing tickers:  10%|▉         | 642/6717 [02:11<21:11,  4.78it/s]

Processing tickers:  10%|▉         | 643/6717 [02:11<20:52,  4.85it/s]

Processing tickers:  10%|▉         | 644/6717 [02:11<21:10,  4.78it/s]

Processing tickers:  10%|▉         | 645/6717 [02:11<20:58,  4.83it/s]

Processing tickers:  10%|▉         | 646/6717 [02:11<20:47,  4.86it/s]

Processing tickers:  10%|▉         | 647/6717 [02:12<20:43,  4.88it/s]

Processing tickers:  10%|▉         | 648/6717 [02:12<20:33,  4.92it/s]

Processing tickers:  10%|▉         | 649/6717 [02:12<20:33,  4.92it/s]

Processing tickers:  10%|▉         | 650/6717 [02:12<20:39,  4.90it/s]

Processing tickers:  10%|▉         | 651/6717 [02:13<20:39,  4.90it/s]

Processing tickers:  10%|▉         | 652/6717 [02:13<20:53,  4.84it/s]

Processing tickers:  10%|▉         | 653/6717 [02:13<20:51,  4.84it/s]

Processing tickers:  10%|▉         | 654/6717 [02:13<20:41,  4.88it/s]

Processing tickers:  10%|▉         | 655/6717 [02:13<20:32,  4.92it/s]

Processing tickers:  10%|▉         | 656/6717 [02:14<20:35,  4.90it/s]

Processing tickers:  10%|▉         | 657/6717 [02:14<21:00,  4.81it/s]

Processing tickers:  10%|▉         | 658/6717 [02:14<20:50,  4.85it/s]

Processing tickers:  10%|▉         | 659/6717 [02:14<20:43,  4.87it/s]

Processing tickers:  10%|▉         | 660/6717 [02:14<20:37,  4.89it/s]

Processing tickers:  10%|▉         | 661/6717 [02:15<20:33,  4.91it/s]

Processing tickers:  10%|▉         | 662/6717 [02:15<20:24,  4.95it/s]

Processing tickers:  10%|▉         | 663/6717 [02:15<20:18,  4.97it/s]

Processing tickers:  10%|▉         | 664/6717 [02:15<20:57,  4.81it/s]

Processing tickers:  10%|▉         | 665/6717 [02:15<20:42,  4.87it/s]

Processing tickers:  10%|▉         | 666/6717 [02:16<20:31,  4.91it/s]

Processing tickers:  10%|▉         | 667/6717 [02:16<20:31,  4.91it/s]

Processing tickers:  10%|▉         | 668/6717 [02:16<20:44,  4.86it/s]

Processing tickers:  10%|▉         | 669/6717 [02:16<20:44,  4.86it/s]

Processing tickers:  10%|▉         | 670/6717 [02:16<20:34,  4.90it/s]

Processing tickers:  10%|▉         | 671/6717 [02:17<20:27,  4.93it/s]

Processing tickers:  10%|█         | 672/6717 [02:17<20:26,  4.93it/s]

Processing tickers:  10%|█         | 673/6717 [02:17<20:42,  4.86it/s]

Processing tickers:  10%|█         | 674/6717 [02:17<20:58,  4.80it/s]

Processing tickers:  10%|█         | 675/6717 [02:17<20:49,  4.83it/s]

Processing tickers:  10%|█         | 676/6717 [02:18<20:56,  4.81it/s]

Processing tickers:  10%|█         | 677/6717 [02:18<21:04,  4.78it/s]

Processing tickers:  10%|█         | 678/6717 [02:18<20:55,  4.81it/s]

Processing tickers:  10%|█         | 679/6717 [02:18<20:41,  4.86it/s]

Processing tickers:  10%|█         | 680/6717 [02:18<20:59,  4.79it/s]

Processing tickers:  10%|█         | 681/6717 [02:19<20:46,  4.84it/s]

Processing tickers:  10%|█         | 682/6717 [02:19<20:57,  4.80it/s]

Processing tickers:  10%|█         | 683/6717 [02:19<20:41,  4.86it/s]

Processing tickers:  10%|█         | 684/6717 [02:19<20:38,  4.87it/s]

Processing tickers:  10%|█         | 685/6717 [02:20<20:36,  4.88it/s]

Processing tickers:  10%|█         | 686/6717 [02:20<20:29,  4.91it/s]

Processing tickers:  10%|█         | 687/6717 [02:20<20:24,  4.93it/s]

Processing tickers:  10%|█         | 688/6717 [02:20<20:21,  4.94it/s]

Processing tickers:  10%|█         | 689/6717 [02:20<20:26,  4.91it/s]

Processing tickers:  10%|█         | 690/6717 [02:21<20:20,  4.94it/s]

Processing tickers:  10%|█         | 691/6717 [02:21<20:22,  4.93it/s]

Processing tickers:  10%|█         | 692/6717 [02:21<20:42,  4.85it/s]

Processing tickers:  10%|█         | 693/6717 [02:21<20:31,  4.89it/s]

Processing tickers:  10%|█         | 694/6717 [02:21<20:26,  4.91it/s]

Processing tickers:  10%|█         | 695/6717 [02:22<20:15,  4.95it/s]

Processing tickers:  10%|█         | 696/6717 [02:22<20:16,  4.95it/s]

Processing tickers:  10%|█         | 697/6717 [02:22<20:13,  4.96it/s]

Processing tickers:  10%|█         | 698/6717 [02:22<20:11,  4.97it/s]

Processing tickers:  10%|█         | 699/6717 [02:22<20:18,  4.94it/s]

Processing tickers:  10%|█         | 700/6717 [02:23<20:16,  4.95it/s]

Processing tickers:  10%|█         | 701/6717 [02:23<20:13,  4.96it/s]

Processing tickers:  10%|█         | 702/6717 [02:23<20:24,  4.91it/s]

Processing tickers:  10%|█         | 703/6717 [02:23<20:27,  4.90it/s]

Processing tickers:  10%|█         | 704/6717 [02:23<20:39,  4.85it/s]

Processing tickers:  10%|█         | 705/6717 [02:24<20:27,  4.90it/s]

Processing tickers:  11%|█         | 706/6717 [02:24<20:24,  4.91it/s]

Processing tickers:  11%|█         | 707/6717 [02:24<20:22,  4.92it/s]

Processing tickers:  11%|█         | 708/6717 [02:24<20:14,  4.95it/s]

Processing tickers:  11%|█         | 709/6717 [02:24<20:18,  4.93it/s]

Processing tickers:  11%|█         | 710/6717 [02:25<20:17,  4.93it/s]

Processing tickers:  11%|█         | 711/6717 [02:25<20:14,  4.94it/s]

Processing tickers:  11%|█         | 712/6717 [02:25<20:37,  4.85it/s]

Processing tickers:  11%|█         | 713/6717 [02:25<20:28,  4.89it/s]

Processing tickers:  11%|█         | 714/6717 [02:25<20:27,  4.89it/s]

Processing tickers:  11%|█         | 715/6717 [02:26<21:00,  4.76it/s]

Processing tickers:  11%|█         | 716/6717 [02:26<20:48,  4.81it/s]

Processing tickers:  11%|█         | 717/6717 [02:26<20:42,  4.83it/s]

Processing tickers:  11%|█         | 718/6717 [02:26<20:42,  4.83it/s]

Processing tickers:  11%|█         | 719/6717 [02:26<20:37,  4.85it/s]

Processing tickers:  11%|█         | 720/6717 [02:27<20:25,  4.89it/s]

Processing tickers:  11%|█         | 721/6717 [02:27<20:22,  4.91it/s]

Processing tickers:  11%|█         | 722/6717 [02:27<20:16,  4.93it/s]

Processing tickers:  11%|█         | 723/6717 [02:27<20:22,  4.90it/s]

Processing tickers:  11%|█         | 724/6717 [02:27<20:24,  4.89it/s]

Processing tickers:  11%|█         | 725/6717 [02:28<20:19,  4.91it/s]

Processing tickers:  11%|█         | 726/6717 [02:28<20:13,  4.94it/s]

Processing tickers:  11%|█         | 727/6717 [02:28<20:08,  4.96it/s]

Processing tickers:  11%|█         | 728/6717 [02:28<20:06,  4.97it/s]

Processing tickers:  11%|█         | 729/6717 [02:28<20:18,  4.91it/s]

Processing tickers:  11%|█         | 730/6717 [02:29<20:17,  4.92it/s]

Processing tickers:  11%|█         | 731/6717 [02:29<20:15,  4.92it/s]

Processing tickers:  11%|█         | 732/6717 [02:29<20:37,  4.84it/s]

Processing tickers:  11%|█         | 733/6717 [02:29<20:43,  4.81it/s]

Processing tickers:  11%|█         | 734/6717 [02:30<20:42,  4.82it/s]

Processing tickers:  11%|█         | 735/6717 [02:30<20:25,  4.88it/s]

Processing tickers:  11%|█         | 736/6717 [02:30<20:21,  4.90it/s]

Processing tickers:  11%|█         | 737/6717 [02:30<20:27,  4.87it/s]

Processing tickers:  11%|█         | 738/6717 [02:30<20:23,  4.89it/s]

Processing tickers:  11%|█         | 739/6717 [02:31<20:21,  4.89it/s]

Processing tickers:  11%|█         | 740/6717 [02:31<20:26,  4.87it/s]

Processing tickers:  11%|█         | 741/6717 [02:31<21:03,  4.73it/s]

Processing tickers:  11%|█         | 742/6717 [02:31<20:55,  4.76it/s]

Processing tickers:  11%|█         | 743/6717 [02:31<20:43,  4.80it/s]

Processing tickers:  11%|█         | 744/6717 [02:32<20:28,  4.86it/s]

Processing tickers:  11%|█         | 745/6717 [02:32<20:19,  4.90it/s]

Processing tickers:  11%|█         | 746/6717 [02:32<20:09,  4.94it/s]

Processing tickers:  11%|█         | 747/6717 [02:32<20:04,  4.95it/s]

Processing tickers:  11%|█         | 748/6717 [02:32<20:05,  4.95it/s]

Processing tickers:  11%|█         | 749/6717 [02:33<20:10,  4.93it/s]

Processing tickers:  11%|█         | 750/6717 [02:33<20:19,  4.89it/s]

Processing tickers:  11%|█         | 751/6717 [02:33<20:32,  4.84it/s]

Processing tickers:  11%|█         | 752/6717 [02:33<20:21,  4.88it/s]

Processing tickers:  11%|█         | 753/6717 [02:33<20:17,  4.90it/s]

Processing tickers:  11%|█         | 754/6717 [02:34<20:13,  4.91it/s]

Processing tickers:  11%|█         | 755/6717 [02:34<20:28,  4.85it/s]

Processing tickers:  11%|█▏        | 756/6717 [02:34<20:47,  4.78it/s]

Processing tickers:  11%|█▏        | 757/6717 [02:34<20:46,  4.78it/s]

Processing tickers:  11%|█▏        | 758/6717 [02:34<20:46,  4.78it/s]

Processing tickers:  11%|█▏        | 759/6717 [02:35<20:30,  4.84it/s]

Processing tickers:  11%|█▏        | 760/6717 [02:35<20:23,  4.87it/s]

Processing tickers:  11%|█▏        | 761/6717 [02:35<20:25,  4.86it/s]

Processing tickers:  11%|█▏        | 762/6717 [02:35<20:18,  4.89it/s]

Processing tickers:  11%|█▏        | 763/6717 [02:35<20:09,  4.92it/s]

Processing tickers:  11%|█▏        | 764/6717 [02:36<20:06,  4.93it/s]

Processing tickers:  11%|█▏        | 765/6717 [02:36<20:04,  4.94it/s]

Processing tickers:  11%|█▏        | 766/6717 [02:36<20:02,  4.95it/s]

Processing tickers:  11%|█▏        | 767/6717 [02:36<20:01,  4.95it/s]

Processing tickers:  11%|█▏        | 768/6717 [02:36<20:06,  4.93it/s]

Processing tickers:  11%|█▏        | 769/6717 [02:37<20:00,  4.95it/s]

Processing tickers:  11%|█▏        | 770/6717 [02:37<19:59,  4.96it/s]

Processing tickers:  11%|█▏        | 771/6717 [02:37<19:59,  4.96it/s]

Processing tickers:  11%|█▏        | 772/6717 [02:37<19:56,  4.97it/s]

Processing tickers:  12%|█▏        | 773/6717 [02:37<20:05,  4.93it/s]

Processing tickers:  12%|█▏        | 774/6717 [02:38<19:57,  4.96it/s]

Processing tickers:  12%|█▏        | 775/6717 [02:38<19:56,  4.96it/s]

Processing tickers:  12%|█▏        | 776/6717 [02:38<20:02,  4.94it/s]

Processing tickers:  12%|█▏        | 777/6717 [02:38<20:38,  4.80it/s]

Processing tickers:  12%|█▏        | 778/6717 [02:39<20:30,  4.83it/s]

Processing tickers:  12%|█▏        | 779/6717 [02:39<20:15,  4.89it/s]

Processing tickers:  12%|█▏        | 780/6717 [02:39<20:25,  4.85it/s]

Processing tickers:  12%|█▏        | 781/6717 [02:39<20:22,  4.86it/s]

Processing tickers:  12%|█▏        | 782/6717 [02:39<20:18,  4.87it/s]

Processing tickers:  12%|█▏        | 783/6717 [02:40<20:12,  4.89it/s]

Processing tickers:  12%|█▏        | 784/6717 [02:40<20:07,  4.91it/s]

Processing tickers:  12%|█▏        | 785/6717 [02:40<20:17,  4.87it/s]

Processing tickers:  12%|█▏        | 786/6717 [02:40<20:42,  4.77it/s]

Processing tickers:  12%|█▏        | 787/6717 [02:40<20:28,  4.83it/s]

Processing tickers:  12%|█▏        | 788/6717 [02:41<20:24,  4.84it/s]

Processing tickers:  12%|█▏        | 789/6717 [02:41<20:15,  4.88it/s]

Processing tickers:  12%|█▏        | 790/6717 [02:41<20:14,  4.88it/s]

Processing tickers:  12%|█▏        | 791/6717 [02:41<20:09,  4.90it/s]

Processing tickers:  12%|█▏        | 792/6717 [02:41<20:00,  4.93it/s]

Processing tickers:  12%|█▏        | 793/6717 [02:42<19:58,  4.94it/s]

Processing tickers:  12%|█▏        | 794/6717 [02:42<19:56,  4.95it/s]

Processing tickers:  12%|█▏        | 795/6717 [02:42<20:47,  4.75it/s]

Processing tickers:  12%|█▏        | 796/6717 [02:42<20:47,  4.75it/s]

Processing tickers:  12%|█▏        | 797/6717 [02:42<21:23,  4.61it/s]

Processing tickers:  12%|█▏        | 798/6717 [02:43<20:55,  4.71it/s]

Processing tickers:  12%|█▏        | 799/6717 [02:43<20:32,  4.80it/s]

Processing tickers:  12%|█▏        | 800/6717 [02:43<20:19,  4.85it/s]

Processing tickers:  12%|█▏        | 801/6717 [02:43<20:15,  4.87it/s]

Processing tickers:  12%|█▏        | 802/6717 [02:43<20:10,  4.89it/s]

Processing tickers:  12%|█▏        | 803/6717 [02:44<20:03,  4.92it/s]

Processing tickers:  12%|█▏        | 804/6717 [02:44<20:01,  4.92it/s]

Processing tickers:  12%|█▏        | 805/6717 [02:44<20:20,  4.84it/s]

Processing tickers:  12%|█▏        | 806/6717 [02:44<20:11,  4.88it/s]

Processing tickers:  12%|█▏        | 807/6717 [02:44<20:05,  4.90it/s]

Processing tickers:  12%|█▏        | 808/6717 [02:45<19:57,  4.94it/s]

Processing tickers:  12%|█▏        | 809/6717 [02:45<20:01,  4.92it/s]

Processing tickers:  12%|█▏        | 810/6717 [02:45<20:04,  4.90it/s]

Processing tickers:  12%|█▏        | 811/6717 [02:45<20:00,  4.92it/s]

Processing tickers:  12%|█▏        | 812/6717 [02:45<20:14,  4.86it/s]

Processing tickers:  12%|█▏        | 813/6717 [02:46<20:03,  4.91it/s]

Processing tickers:  12%|█▏        | 814/6717 [02:46<20:15,  4.86it/s]

Processing tickers:  12%|█▏        | 815/6717 [02:46<20:38,  4.77it/s]

Processing tickers:  12%|█▏        | 816/6717 [02:46<20:17,  4.85it/s]

Processing tickers:  12%|█▏        | 817/6717 [02:47<20:10,  4.88it/s]

Processing tickers:  12%|█▏        | 818/6717 [02:47<20:00,  4.91it/s]

Processing tickers:  12%|█▏        | 819/6717 [02:47<19:58,  4.92it/s]

Processing tickers:  12%|█▏        | 820/6717 [02:47<19:56,  4.93it/s]

Processing tickers:  12%|█▏        | 821/6717 [02:47<20:07,  4.88it/s]

Processing tickers:  12%|█▏        | 822/6717 [02:48<19:54,  4.93it/s]

Processing tickers:  12%|█▏        | 823/6717 [02:48<20:13,  4.86it/s]

Processing tickers:  12%|█▏        | 824/6717 [02:48<20:10,  4.87it/s]

Processing tickers:  12%|█▏        | 825/6717 [02:48<20:04,  4.89it/s]

Processing tickers:  12%|█▏        | 826/6717 [02:48<20:05,  4.89it/s]

Processing tickers:  12%|█▏        | 827/6717 [02:49<20:08,  4.87it/s]

Processing tickers:  12%|█▏        | 828/6717 [02:49<20:06,  4.88it/s]

Processing tickers:  12%|█▏        | 829/6717 [02:49<20:02,  4.90it/s]

Processing tickers:  12%|█▏        | 830/6717 [02:49<20:22,  4.82it/s]

Processing tickers:  12%|█▏        | 831/6717 [02:49<20:42,  4.74it/s]

Processing tickers:  12%|█▏        | 832/6717 [02:50<20:28,  4.79it/s]

Processing tickers:  12%|█▏        | 833/6717 [02:50<20:14,  4.84it/s]

Processing tickers:  12%|█▏        | 834/6717 [02:50<20:26,  4.80it/s]

Processing tickers:  12%|█▏        | 835/6717 [02:50<20:08,  4.87it/s]

Processing tickers:  12%|█▏        | 836/6717 [02:50<20:22,  4.81it/s]

Processing tickers:  12%|█▏        | 837/6717 [02:51<20:09,  4.86it/s]

Processing tickers:  12%|█▏        | 838/6717 [02:51<20:07,  4.87it/s]

Processing tickers:  12%|█▏        | 839/6717 [02:51<19:56,  4.91it/s]

Processing tickers:  13%|█▎        | 840/6717 [02:51<19:58,  4.90it/s]

Processing tickers:  13%|█▎        | 841/6717 [02:51<19:51,  4.93it/s]

Processing tickers:  13%|█▎        | 842/6717 [02:52<19:51,  4.93it/s]

Processing tickers:  13%|█▎        | 843/6717 [02:52<19:49,  4.94it/s]

Processing tickers:  13%|█▎        | 844/6717 [02:52<19:43,  4.96it/s]

Processing tickers:  13%|█▎        | 845/6717 [02:52<19:46,  4.95it/s]

Processing tickers:  13%|█▎        | 846/6717 [02:52<19:47,  4.94it/s]

Processing tickers:  13%|█▎        | 847/6717 [02:53<19:51,  4.93it/s]

Processing tickers:  13%|█▎        | 848/6717 [02:53<19:45,  4.95it/s]

Processing tickers:  13%|█▎        | 849/6717 [02:53<19:57,  4.90it/s]

Processing tickers:  13%|█▎        | 850/6717 [02:53<19:55,  4.91it/s]

Processing tickers:  13%|█▎        | 851/6717 [02:53<20:04,  4.87it/s]

Processing tickers:  13%|█▎        | 852/6717 [02:54<19:54,  4.91it/s]

Processing tickers:  13%|█▎        | 853/6717 [02:54<20:09,  4.85it/s]

Processing tickers:  13%|█▎        | 854/6717 [02:54<20:08,  4.85it/s]

Processing tickers:  13%|█▎        | 855/6717 [02:54<20:17,  4.81it/s]

Processing tickers:  13%|█▎        | 856/6717 [02:55<20:38,  4.73it/s]

Processing tickers:  13%|█▎        | 857/6717 [02:55<20:22,  4.79it/s]

Processing tickers:  13%|█▎        | 858/6717 [02:55<20:09,  4.84it/s]

Processing tickers:  13%|█▎        | 859/6717 [02:55<20:04,  4.86it/s]

Processing tickers:  13%|█▎        | 860/6717 [02:55<20:01,  4.87it/s]

Processing tickers:  13%|█▎        | 861/6717 [02:56<20:01,  4.88it/s]

Processing tickers:  13%|█▎        | 862/6717 [02:56<20:14,  4.82it/s]

Processing tickers:  13%|█▎        | 863/6717 [02:56<20:01,  4.87it/s]

Processing tickers:  13%|█▎        | 864/6717 [02:56<19:57,  4.89it/s]

Processing tickers:  13%|█▎        | 865/6717 [02:56<19:49,  4.92it/s]

Processing tickers:  13%|█▎        | 866/6717 [02:57<19:51,  4.91it/s]

Processing tickers:  13%|█▎        | 867/6717 [02:57<19:55,  4.89it/s]

Processing tickers:  13%|█▎        | 868/6717 [02:57<20:07,  4.84it/s]

Processing tickers:  13%|█▎        | 869/6717 [02:57<20:01,  4.87it/s]

Processing tickers:  13%|█▎        | 870/6717 [02:57<19:51,  4.91it/s]

Processing tickers:  13%|█▎        | 871/6717 [02:58<19:46,  4.93it/s]

Processing tickers:  13%|█▎        | 872/6717 [02:58<19:55,  4.89it/s]

Processing tickers:  13%|█▎        | 873/6717 [02:58<20:05,  4.85it/s]

Processing tickers:  13%|█▎        | 874/6717 [02:58<19:52,  4.90it/s]

Processing tickers:  13%|█▎        | 875/6717 [02:58<20:02,  4.86it/s]

Processing tickers:  13%|█▎        | 876/6717 [02:59<19:59,  4.87it/s]

Processing tickers:  13%|█▎        | 877/6717 [02:59<19:52,  4.90it/s]

Processing tickers:  13%|█▎        | 878/6717 [02:59<20:10,  4.82it/s]

Processing tickers:  13%|█▎        | 879/6717 [02:59<20:06,  4.84it/s]

Processing tickers:  13%|█▎        | 880/6717 [02:59<20:04,  4.85it/s]

Processing tickers:  13%|█▎        | 881/6717 [03:00<19:54,  4.88it/s]

Processing tickers:  13%|█▎        | 882/6717 [03:00<19:43,  4.93it/s]

Processing tickers:  13%|█▎        | 883/6717 [03:00<19:40,  4.94it/s]

Processing tickers:  13%|█▎        | 884/6717 [03:00<19:36,  4.96it/s]

Processing tickers:  13%|█▎        | 885/6717 [03:00<19:43,  4.93it/s]

Processing tickers:  13%|█▎        | 886/6717 [03:01<19:35,  4.96it/s]

Processing tickers:  13%|█▎        | 887/6717 [03:01<19:47,  4.91it/s]

Processing tickers:  13%|█▎        | 888/6717 [03:01<20:11,  4.81it/s]

Processing tickers:  13%|█▎        | 889/6717 [03:01<20:01,  4.85it/s]

Processing tickers:  13%|█▎        | 890/6717 [03:01<19:59,  4.86it/s]

Processing tickers:  13%|█▎        | 891/6717 [03:02<19:46,  4.91it/s]

Processing tickers:  13%|█▎        | 892/6717 [03:02<19:47,  4.91it/s]

Processing tickers:  13%|█▎        | 893/6717 [03:02<19:42,  4.93it/s]

Processing tickers:  13%|█▎        | 894/6717 [03:02<19:40,  4.93it/s]

Processing tickers:  13%|█▎        | 895/6717 [03:02<19:36,  4.95it/s]

Processing tickers:  13%|█▎        | 896/6717 [03:03<19:35,  4.95it/s]

Processing tickers:  13%|█▎        | 897/6717 [03:03<19:35,  4.95it/s]

Processing tickers:  13%|█▎        | 898/6717 [03:03<19:36,  4.95it/s]

Processing tickers:  13%|█▎        | 899/6717 [03:03<19:42,  4.92it/s]

Processing tickers:  13%|█▎        | 900/6717 [03:04<19:36,  4.95it/s]

Processing tickers:  13%|█▎        | 901/6717 [03:04<19:42,  4.92it/s]

Processing tickers:  13%|█▎        | 902/6717 [03:04<19:38,  4.93it/s]

Processing tickers:  13%|█▎        | 903/6717 [03:04<19:34,  4.95it/s]

Processing tickers:  13%|█▎        | 904/6717 [03:04<19:42,  4.92it/s]

Processing tickers:  13%|█▎        | 905/6717 [03:05<19:40,  4.92it/s]

Processing tickers:  13%|█▎        | 906/6717 [03:05<19:43,  4.91it/s]

Processing tickers:  14%|█▎        | 907/6717 [03:05<19:49,  4.88it/s]

Processing tickers:  14%|█▎        | 908/6717 [03:05<19:40,  4.92it/s]

Processing tickers:  14%|█▎        | 909/6717 [03:05<19:34,  4.95it/s]

Processing tickers:  14%|█▎        | 910/6717 [03:06<19:31,  4.96it/s]

Processing tickers:  14%|█▎        | 911/6717 [03:06<19:32,  4.95it/s]

Processing tickers:  14%|█▎        | 912/6717 [03:06<19:32,  4.95it/s]

Processing tickers:  14%|█▎        | 913/6717 [03:06<19:26,  4.98it/s]

Processing tickers:  14%|█▎        | 914/6717 [03:06<19:59,  4.84it/s]

Processing tickers:  14%|█▎        | 915/6717 [03:07<19:48,  4.88it/s]

Processing tickers:  14%|█▎        | 916/6717 [03:07<19:43,  4.90it/s]

Processing tickers:  14%|█▎        | 917/6717 [03:07<19:48,  4.88it/s]

Processing tickers:  14%|█▎        | 918/6717 [03:07<19:44,  4.90it/s]

Processing tickers:  14%|█▎        | 919/6717 [03:07<19:39,  4.92it/s]

Processing tickers:  14%|█▎        | 920/6717 [03:08<19:31,  4.95it/s]

Processing tickers:  14%|█▎        | 921/6717 [03:08<19:33,  4.94it/s]

Processing tickers:  14%|█▎        | 922/6717 [03:08<19:52,  4.86it/s]

Processing tickers:  14%|█▎        | 923/6717 [03:08<19:36,  4.92it/s]

Processing tickers:  14%|█▍        | 924/6717 [03:08<19:40,  4.91it/s]

Processing tickers:  14%|█▍        | 925/6717 [03:09<19:34,  4.93it/s]

Processing tickers:  14%|█▍        | 926/6717 [03:09<19:32,  4.94it/s]

Processing tickers:  14%|█▍        | 927/6717 [03:09<19:47,  4.88it/s]

Processing tickers:  14%|█▍        | 928/6717 [03:09<20:04,  4.80it/s]

Processing tickers:  14%|█▍        | 929/6717 [03:09<19:51,  4.86it/s]

Processing tickers:  14%|█▍        | 930/6717 [03:10<19:49,  4.87it/s]

Processing tickers:  14%|█▍        | 931/6717 [03:10<19:37,  4.91it/s]

Processing tickers:  14%|█▍        | 932/6717 [03:10<19:39,  4.91it/s]

Processing tickers:  14%|█▍        | 933/6717 [03:10<19:35,  4.92it/s]

Processing tickers:  14%|█▍        | 934/6717 [03:10<19:21,  4.98it/s]

Processing tickers:  14%|█▍        | 935/6717 [03:11<19:18,  4.99it/s]

Processing tickers:  14%|█▍        | 936/6717 [03:11<19:23,  4.97it/s]

Processing tickers:  14%|█▍        | 937/6717 [03:11<19:19,  4.98it/s]

Processing tickers:  14%|█▍        | 938/6717 [03:11<19:17,  4.99it/s]

Processing tickers:  14%|█▍        | 939/6717 [03:11<19:16,  5.00it/s]

Processing tickers:  14%|█▍        | 940/6717 [03:12<19:12,  5.01it/s]

Processing tickers:  14%|█▍        | 941/6717 [03:12<19:21,  4.97it/s]

Processing tickers:  14%|█▍        | 942/6717 [03:12<19:29,  4.94it/s]

Processing tickers:  14%|█▍        | 943/6717 [03:12<19:25,  4.95it/s]

Processing tickers:  14%|█▍        | 944/6717 [03:12<19:55,  4.83it/s]

Processing tickers:  14%|█▍        | 945/6717 [03:13<19:49,  4.85it/s]

Processing tickers:  14%|█▍        | 946/6717 [03:13<19:42,  4.88it/s]

Processing tickers:  14%|█▍        | 947/6717 [03:13<19:36,  4.90it/s]

Processing tickers:  14%|█▍        | 948/6717 [03:13<19:42,  4.88it/s]

Processing tickers:  14%|█▍        | 949/6717 [03:13<19:37,  4.90it/s]

Processing tickers:  14%|█▍        | 950/6717 [03:14<19:35,  4.91it/s]

Processing tickers:  14%|█▍        | 951/6717 [03:14<19:32,  4.92it/s]

Processing tickers:  14%|█▍        | 952/6717 [03:14<19:27,  4.94it/s]

Processing tickers:  14%|█▍        | 953/6717 [03:14<19:31,  4.92it/s]

Processing tickers:  14%|█▍        | 954/6717 [03:14<19:31,  4.92it/s]

Processing tickers:  14%|█▍        | 955/6717 [03:15<19:23,  4.95it/s]

Processing tickers:  14%|█▍        | 956/6717 [03:15<19:25,  4.94it/s]

Processing tickers:  14%|█▍        | 957/6717 [03:15<20:00,  4.80it/s]

Processing tickers:  14%|█▍        | 958/6717 [03:15<19:57,  4.81it/s]

Processing tickers:  14%|█▍        | 959/6717 [03:16<19:44,  4.86it/s]

Processing tickers:  14%|█▍        | 960/6717 [03:16<19:42,  4.87it/s]

Processing tickers:  14%|█▍        | 961/6717 [03:16<19:33,  4.91it/s]

Processing tickers:  14%|█▍        | 962/6717 [03:16<19:27,  4.93it/s]

Processing tickers:  14%|█▍        | 963/6717 [03:16<19:21,  4.96it/s]

Processing tickers:  14%|█▍        | 964/6717 [03:17<19:18,  4.96it/s]

Processing tickers:  14%|█▍        | 965/6717 [03:17<19:19,  4.96it/s]

Processing tickers:  14%|█▍        | 966/6717 [03:17<19:15,  4.98it/s]

Processing tickers:  14%|█▍        | 967/6717 [03:17<19:20,  4.95it/s]

Processing tickers:  14%|█▍        | 968/6717 [03:17<19:10,  5.00it/s]

Processing tickers:  14%|█▍        | 969/6717 [03:18<19:11,  4.99it/s]

Processing tickers:  14%|█▍        | 970/6717 [03:18<19:12,  4.99it/s]

Processing tickers:  14%|█▍        | 971/6717 [03:18<19:54,  4.81it/s]

Processing tickers:  14%|█▍        | 972/6717 [03:18<19:41,  4.86it/s]

Processing tickers:  14%|█▍        | 973/6717 [03:18<19:32,  4.90it/s]

Processing tickers:  15%|█▍        | 974/6717 [03:19<19:35,  4.88it/s]

Processing tickers:  15%|█▍        | 975/6717 [03:19<19:32,  4.90it/s]

Processing tickers:  15%|█▍        | 976/6717 [03:19<21:33,  4.44it/s]

Processing tickers:  15%|█▍        | 977/6717 [03:19<21:00,  4.55it/s]

Processing tickers:  15%|█▍        | 978/6717 [03:19<20:43,  4.62it/s]

Processing tickers:  15%|█▍        | 979/6717 [03:20<20:42,  4.62it/s]

Processing tickers:  15%|█▍        | 980/6717 [03:20<20:13,  4.73it/s]

Processing tickers:  15%|█▍        | 981/6717 [03:20<19:57,  4.79it/s]

Processing tickers:  15%|█▍        | 982/6717 [03:20<19:50,  4.82it/s]

Processing tickers:  15%|█▍        | 983/6717 [03:20<19:39,  4.86it/s]

Processing tickers:  15%|█▍        | 984/6717 [03:21<19:29,  4.90it/s]

Processing tickers:  15%|█▍        | 985/6717 [03:21<19:26,  4.91it/s]

Processing tickers:  15%|█▍        | 986/6717 [03:21<19:31,  4.89it/s]

Processing tickers:  15%|█▍        | 987/6717 [03:21<19:27,  4.91it/s]

Processing tickers:  15%|█▍        | 988/6717 [03:21<19:29,  4.90it/s]

Processing tickers:  15%|█▍        | 989/6717 [03:22<19:37,  4.86it/s]

Processing tickers:  15%|█▍        | 990/6717 [03:22<19:23,  4.92it/s]

Processing tickers:  15%|█▍        | 991/6717 [03:22<19:16,  4.95it/s]

Processing tickers:  15%|█▍        | 992/6717 [03:22<19:17,  4.95it/s]

Processing tickers:  15%|█▍        | 993/6717 [03:23<19:42,  4.84it/s]

Processing tickers:  15%|█▍        | 994/6717 [03:23<19:28,  4.90it/s]

Processing tickers:  15%|█▍        | 995/6717 [03:23<19:24,  4.91it/s]

Processing tickers:  15%|█▍        | 996/6717 [03:23<19:21,  4.93it/s]

Processing tickers:  15%|█▍        | 997/6717 [03:23<19:15,  4.95it/s]

Processing tickers:  15%|█▍        | 998/6717 [03:24<19:16,  4.94it/s]

Processing tickers:  15%|█▍        | 999/6717 [03:24<19:11,  4.96it/s]

Processing tickers:  15%|█▍        | 1000/6717 [03:24<19:07,  4.98it/s]

Processing tickers:  15%|█▍        | 1001/6717 [03:24<19:13,  4.95it/s]

Processing tickers:  15%|█▍        | 1002/6717 [03:24<20:00,  4.76it/s]

Processing tickers:  15%|█▍        | 1003/6717 [03:25<19:52,  4.79it/s]

Processing tickers:  15%|█▍        | 1004/6717 [03:25<19:40,  4.84it/s]

Processing tickers:  15%|█▍        | 1005/6717 [03:25<21:29,  4.43it/s]

Processing tickers:  15%|█▍        | 1006/6717 [03:25<20:42,  4.60it/s]

Processing tickers:  15%|█▍        | 1007/6717 [03:25<20:14,  4.70it/s]

Processing tickers:  15%|█▌        | 1008/6717 [03:26<19:53,  4.78it/s]

Processing tickers:  15%|█▌        | 1009/6717 [03:26<19:37,  4.85it/s]

Processing tickers:  15%|█▌        | 1010/6717 [03:26<19:27,  4.89it/s]

Processing tickers:  15%|█▌        | 1011/6717 [03:26<19:20,  4.92it/s]

Processing tickers:  15%|█▌        | 1012/6717 [03:26<19:16,  4.93it/s]

Processing tickers:  15%|█▌        | 1013/6717 [03:27<19:20,  4.91it/s]

Processing tickers:  15%|█▌        | 1014/6717 [03:27<19:20,  4.91it/s]

Processing tickers:  15%|█▌        | 1015/6717 [03:27<19:51,  4.79it/s]

Processing tickers:  15%|█▌        | 1016/6717 [03:27<19:53,  4.77it/s]

Processing tickers:  15%|█▌        | 1017/6717 [03:27<19:46,  4.81it/s]

Processing tickers:  15%|█▌        | 1018/6717 [03:28<19:30,  4.87it/s]

Processing tickers:  15%|█▌        | 1019/6717 [03:28<19:23,  4.90it/s]

Processing tickers:  15%|█▌        | 1020/6717 [03:28<19:15,  4.93it/s]

Processing tickers:  15%|█▌        | 1021/6717 [03:28<19:16,  4.93it/s]

Processing tickers:  15%|█▌        | 1022/6717 [03:28<19:19,  4.91it/s]

Processing tickers:  15%|█▌        | 1023/6717 [03:29<19:17,  4.92it/s]

Processing tickers:  15%|█▌        | 1024/6717 [03:29<19:14,  4.93it/s]

Processing tickers:  15%|█▌        | 1025/6717 [03:29<19:13,  4.93it/s]

Processing tickers:  15%|█▌        | 1026/6717 [03:29<19:12,  4.94it/s]

Processing tickers:  15%|█▌        | 1027/6717 [03:30<19:12,  4.94it/s]

Processing tickers:  15%|█▌        | 1028/6717 [03:30<19:13,  4.93it/s]

Processing tickers:  15%|█▌        | 1029/6717 [03:30<19:05,  4.96it/s]

Processing tickers:  15%|█▌        | 1030/6717 [03:30<19:04,  4.97it/s]

Processing tickers:  15%|█▌        | 1031/6717 [03:30<19:10,  4.94it/s]

Processing tickers:  15%|█▌        | 1032/6717 [03:31<19:08,  4.95it/s]

Processing tickers:  15%|█▌        | 1033/6717 [03:31<19:24,  4.88it/s]

Processing tickers:  15%|█▌        | 1034/6717 [03:31<19:17,  4.91it/s]

Processing tickers:  15%|█▌        | 1035/6717 [03:31<19:23,  4.88it/s]

Processing tickers:  15%|█▌        | 1036/6717 [03:31<19:37,  4.83it/s]

Processing tickers:  15%|█▌        | 1037/6717 [03:32<19:37,  4.83it/s]

Processing tickers:  15%|█▌        | 1038/6717 [03:32<19:24,  4.88it/s]

Processing tickers:  15%|█▌        | 1039/6717 [03:32<19:31,  4.85it/s]

Processing tickers:  15%|█▌        | 1040/6717 [03:32<19:32,  4.84it/s]

Processing tickers:  15%|█▌        | 1041/6717 [03:32<19:29,  4.85it/s]

Processing tickers:  16%|█▌        | 1042/6717 [03:33<19:20,  4.89it/s]

Processing tickers:  16%|█▌        | 1043/6717 [03:33<19:11,  4.93it/s]

Processing tickers:  16%|█▌        | 1044/6717 [03:33<19:05,  4.95it/s]

Processing tickers:  16%|█▌        | 1045/6717 [03:33<19:10,  4.93it/s]

Processing tickers:  16%|█▌        | 1046/6717 [03:33<19:07,  4.94it/s]

Processing tickers:  16%|█▌        | 1047/6717 [03:34<19:11,  4.93it/s]

Processing tickers:  16%|█▌        | 1048/6717 [03:34<19:13,  4.92it/s]

Processing tickers:  16%|█▌        | 1049/6717 [03:34<19:26,  4.86it/s]

Processing tickers:  16%|█▌        | 1050/6717 [03:34<19:19,  4.89it/s]

Processing tickers:  16%|█▌        | 1051/6717 [03:34<19:08,  4.94it/s]

Processing tickers:  16%|█▌        | 1052/6717 [03:35<19:00,  4.97it/s]

Processing tickers:  16%|█▌        | 1053/6717 [03:35<18:58,  4.97it/s]

Processing tickers:  16%|█▌        | 1054/6717 [03:35<19:09,  4.93it/s]

Processing tickers:  16%|█▌        | 1055/6717 [03:35<19:10,  4.92it/s]

Processing tickers:  16%|█▌        | 1056/6717 [03:35<19:05,  4.94it/s]

Processing tickers:  16%|█▌        | 1057/6717 [03:36<19:02,  4.95it/s]

Processing tickers:  16%|█▌        | 1058/6717 [03:36<18:59,  4.96it/s]

Processing tickers:  16%|█▌        | 1059/6717 [03:36<19:11,  4.91it/s]

Processing tickers:  16%|█▌        | 1060/6717 [03:36<19:10,  4.92it/s]

Processing tickers:  16%|█▌        | 1061/6717 [03:36<19:07,  4.93it/s]

Processing tickers:  16%|█▌        | 1062/6717 [03:37<19:18,  4.88it/s]

Processing tickers:  16%|█▌        | 1063/6717 [03:37<19:14,  4.90it/s]

Processing tickers:  16%|█▌        | 1064/6717 [03:37<19:05,  4.94it/s]

Processing tickers:  16%|█▌        | 1065/6717 [03:37<19:06,  4.93it/s]

Processing tickers:  16%|█▌        | 1066/6717 [03:37<19:08,  4.92it/s]

Processing tickers:  16%|█▌        | 1067/6717 [03:38<19:01,  4.95it/s]

Processing tickers:  16%|█▌        | 1068/6717 [03:38<18:53,  4.98it/s]

Processing tickers:  16%|█▌        | 1069/6717 [03:38<18:54,  4.98it/s]

Processing tickers:  16%|█▌        | 1070/6717 [03:38<18:53,  4.98it/s]

Processing tickers:  16%|█▌        | 1071/6717 [03:38<18:51,  4.99it/s]

Processing tickers:  16%|█▌        | 1072/6717 [03:39<18:55,  4.97it/s]

Processing tickers:  16%|█▌        | 1073/6717 [03:39<18:53,  4.98it/s]

Processing tickers:  16%|█▌        | 1074/6717 [03:39<18:44,  5.02it/s]

Processing tickers:  16%|█▌        | 1075/6717 [03:39<18:42,  5.03it/s]

Processing tickers:  16%|█▌        | 1076/6717 [03:39<18:46,  5.01it/s]

Processing tickers:  16%|█▌        | 1077/6717 [03:40<18:42,  5.03it/s]

Processing tickers:  16%|█▌        | 1078/6717 [03:40<18:42,  5.02it/s]

Processing tickers:  16%|█▌        | 1079/6717 [03:40<19:05,  4.92it/s]

Processing tickers:  16%|█▌        | 1080/6717 [03:40<18:54,  4.97it/s]

Processing tickers:  16%|█▌        | 1081/6717 [03:40<18:53,  4.97it/s]

Processing tickers:  16%|█▌        | 1082/6717 [03:41<18:53,  4.97it/s]

Processing tickers:  16%|█▌        | 1083/6717 [03:41<18:49,  4.99it/s]

Processing tickers:  16%|█▌        | 1084/6717 [03:41<18:45,  5.00it/s]

Processing tickers:  16%|█▌        | 1085/6717 [03:41<18:45,  5.00it/s]

Processing tickers:  16%|█▌        | 1086/6717 [03:41<18:52,  4.97it/s]

Processing tickers:  16%|█▌        | 1087/6717 [03:42<18:52,  4.97it/s]

Processing tickers:  16%|█▌        | 1088/6717 [03:42<18:52,  4.97it/s]

Processing tickers:  16%|█▌        | 1089/6717 [03:42<18:51,  4.97it/s]

Processing tickers:  16%|█▌        | 1090/6717 [03:42<19:04,  4.92it/s]

Processing tickers:  16%|█▌        | 1091/6717 [03:42<19:07,  4.90it/s]

Processing tickers:  16%|█▋        | 1092/6717 [03:43<19:04,  4.91it/s]

Processing tickers:  16%|█▋        | 1093/6717 [03:43<18:58,  4.94it/s]

Processing tickers:  16%|█▋        | 1094/6717 [03:43<18:57,  4.94it/s]

Processing tickers:  16%|█▋        | 1095/6717 [03:43<18:53,  4.96it/s]

Processing tickers:  16%|█▋        | 1096/6717 [03:43<18:50,  4.97it/s]

Processing tickers:  16%|█▋        | 1097/6717 [03:44<18:49,  4.98it/s]

Processing tickers:  16%|█▋        | 1098/6717 [03:44<18:47,  4.98it/s]

Processing tickers:  16%|█▋        | 1099/6717 [03:44<18:52,  4.96it/s]

Processing tickers:  16%|█▋        | 1100/6717 [03:44<18:53,  4.96it/s]

Processing tickers:  16%|█▋        | 1101/6717 [03:44<18:49,  4.97it/s]

Processing tickers:  16%|█▋        | 1102/6717 [03:45<19:09,  4.89it/s]

Processing tickers:  16%|█▋        | 1103/6717 [03:45<19:06,  4.90it/s]

Processing tickers:  16%|█▋        | 1104/6717 [03:45<18:58,  4.93it/s]

Processing tickers:  16%|█▋        | 1105/6717 [03:45<18:51,  4.96it/s]

Processing tickers:  16%|█▋        | 1106/6717 [03:45<18:48,  4.97it/s]

Processing tickers:  16%|█▋        | 1107/6717 [03:46<18:47,  4.98it/s]

Processing tickers:  16%|█▋        | 1108/6717 [03:46<18:44,  4.99it/s]

Processing tickers:  17%|█▋        | 1109/6717 [03:46<18:43,  4.99it/s]

Processing tickers:  17%|█▋        | 1110/6717 [03:46<18:42,  5.00it/s]

Processing tickers:  17%|█▋        | 1111/6717 [03:46<18:51,  4.95it/s]

Processing tickers:  17%|█▋        | 1112/6717 [03:47<18:49,  4.96it/s]

Processing tickers:  17%|█▋        | 1113/6717 [03:47<18:43,  4.99it/s]

Processing tickers:  17%|█▋        | 1114/6717 [03:47<19:40,  4.75it/s]

Processing tickers:  17%|█▋        | 1115/6717 [03:47<19:53,  4.69it/s]

Processing tickers:  17%|█▋        | 1116/6717 [03:48<19:34,  4.77it/s]

Processing tickers:  17%|█▋        | 1117/6717 [03:48<19:23,  4.81it/s]

Processing tickers:  17%|█▋        | 1118/6717 [03:48<19:13,  4.85it/s]

Processing tickers:  17%|█▋        | 1119/6717 [03:48<19:47,  4.72it/s]

Processing tickers:  17%|█▋        | 1120/6717 [03:48<19:31,  4.78it/s]

Processing tickers:  17%|█▋        | 1121/6717 [03:49<19:17,  4.83it/s]

Processing tickers:  17%|█▋        | 1122/6717 [03:49<19:24,  4.80it/s]

Processing tickers:  17%|█▋        | 1123/6717 [03:49<19:25,  4.80it/s]

Processing tickers:  17%|█▋        | 1124/6717 [03:49<19:12,  4.85it/s]

Processing tickers:  17%|█▋        | 1125/6717 [03:49<19:03,  4.89it/s]

Processing tickers:  17%|█▋        | 1126/6717 [03:50<19:11,  4.86it/s]

Processing tickers:  17%|█▋        | 1127/6717 [03:50<19:00,  4.90it/s]

Processing tickers:  17%|█▋        | 1128/6717 [03:50<19:11,  4.85it/s]

Processing tickers:  17%|█▋        | 1129/6717 [03:50<19:08,  4.87it/s]

Processing tickers:  17%|█▋        | 1130/6717 [03:50<19:22,  4.81it/s]

Processing tickers:  17%|█▋        | 1131/6717 [03:51<19:10,  4.85it/s]

Processing tickers:  17%|█▋        | 1132/6717 [03:51<19:02,  4.89it/s]

Processing tickers:  17%|█▋        | 1133/6717 [03:51<18:53,  4.93it/s]

Processing tickers:  17%|█▋        | 1134/6717 [03:51<18:49,  4.94it/s]

Processing tickers:  17%|█▋        | 1135/6717 [03:51<18:51,  4.93it/s]

Processing tickers:  17%|█▋        | 1136/6717 [03:52<18:47,  4.95it/s]

Processing tickers:  17%|█▋        | 1137/6717 [03:52<18:42,  4.97it/s]

Processing tickers:  17%|█▋        | 1138/6717 [03:52<18:45,  4.96it/s]

Processing tickers:  17%|█▋        | 1139/6717 [03:52<18:49,  4.94it/s]

Processing tickers:  17%|█▋        | 1140/6717 [03:52<19:06,  4.87it/s]

Processing tickers:  17%|█▋        | 1141/6717 [03:53<19:21,  4.80it/s]

Processing tickers:  17%|█▋        | 1142/6717 [03:53<19:11,  4.84it/s]

Processing tickers:  17%|█▋        | 1143/6717 [03:53<19:33,  4.75it/s]

Processing tickers:  17%|█▋        | 1144/6717 [03:53<19:20,  4.80it/s]

Processing tickers:  17%|█▋        | 1145/6717 [03:54<19:07,  4.85it/s]

Processing tickers:  17%|█▋        | 1146/6717 [03:54<18:58,  4.89it/s]

Processing tickers:  17%|█▋        | 1147/6717 [03:54<18:55,  4.91it/s]

Processing tickers:  17%|█▋        | 1148/6717 [03:54<18:56,  4.90it/s]

Processing tickers:  17%|█▋        | 1149/6717 [03:54<18:47,  4.94it/s]

Processing tickers:  17%|█▋        | 1150/6717 [03:55<18:47,  4.94it/s]

Processing tickers:  17%|█▋        | 1151/6717 [03:55<18:47,  4.93it/s]

Processing tickers:  17%|█▋        | 1152/6717 [03:55<18:47,  4.93it/s]

Processing tickers:  17%|█▋        | 1153/6717 [03:55<18:45,  4.94it/s]

Processing tickers:  17%|█▋        | 1154/6717 [03:55<18:43,  4.95it/s]

Processing tickers:  17%|█▋        | 1155/6717 [03:56<19:01,  4.87it/s]

Processing tickers:  17%|█▋        | 1156/6717 [03:56<18:58,  4.88it/s]

Processing tickers:  17%|█▋        | 1157/6717 [03:56<19:01,  4.87it/s]

Processing tickers:  17%|█▋        | 1158/6717 [03:56<18:56,  4.89it/s]

Processing tickers:  17%|█▋        | 1159/6717 [03:56<18:48,  4.92it/s]

Processing tickers:  17%|█▋        | 1160/6717 [03:57<18:42,  4.95it/s]

Processing tickers:  17%|█▋        | 1161/6717 [03:57<18:42,  4.95it/s]

Processing tickers:  17%|█▋        | 1162/6717 [03:57<18:35,  4.98it/s]

Processing tickers:  17%|█▋        | 1163/6717 [03:57<18:31,  5.00it/s]

Processing tickers:  17%|█▋        | 1164/6717 [03:57<18:51,  4.91it/s]

Processing tickers:  17%|█▋        | 1165/6717 [03:58<18:42,  4.94it/s]

Processing tickers:  17%|█▋        | 1166/6717 [03:58<18:37,  4.97it/s]

Processing tickers:  17%|█▋        | 1167/6717 [03:58<18:35,  4.98it/s]

Processing tickers:  17%|█▋        | 1168/6717 [03:58<18:24,  5.02it/s]

Processing tickers:  17%|█▋        | 1169/6717 [03:58<18:21,  5.04it/s]

Processing tickers:  17%|█▋        | 1170/6717 [03:59<18:40,  4.95it/s]

Processing tickers:  17%|█▋        | 1171/6717 [03:59<18:33,  4.98it/s]

Processing tickers:  17%|█▋        | 1172/6717 [03:59<18:32,  4.99it/s]

Processing tickers:  17%|█▋        | 1173/6717 [03:59<18:33,  4.98it/s]

Processing tickers:  17%|█▋        | 1174/6717 [03:59<18:45,  4.93it/s]

Processing tickers:  17%|█▋        | 1175/6717 [04:00<18:44,  4.93it/s]

Processing tickers:  18%|█▊        | 1176/6717 [04:00<18:39,  4.95it/s]

Processing tickers:  18%|█▊        | 1177/6717 [04:00<18:41,  4.94it/s]

Processing tickers:  18%|█▊        | 1178/6717 [04:00<18:41,  4.94it/s]

Processing tickers:  18%|█▊        | 1179/6717 [04:00<18:56,  4.87it/s]

Processing tickers:  18%|█▊        | 1180/6717 [04:01<18:54,  4.88it/s]

Processing tickers:  18%|█▊        | 1181/6717 [04:01<18:51,  4.89it/s]

Processing tickers:  18%|█▊        | 1182/6717 [04:01<18:57,  4.87it/s]

Processing tickers:  18%|█▊        | 1183/6717 [04:01<18:52,  4.89it/s]

Processing tickers:  18%|█▊        | 1184/6717 [04:01<18:52,  4.89it/s]

Processing tickers:  18%|█▊        | 1185/6717 [04:02<18:50,  4.89it/s]

Processing tickers:  18%|█▊        | 1186/6717 [04:02<20:43,  4.45it/s]

Processing tickers:  18%|█▊        | 1187/6717 [04:02<20:06,  4.58it/s]

Processing tickers:  18%|█▊        | 1188/6717 [04:02<19:38,  4.69it/s]

Processing tickers:  18%|█▊        | 1189/6717 [04:02<19:21,  4.76it/s]

Processing tickers:  18%|█▊        | 1190/6717 [04:03<19:06,  4.82it/s]

Processing tickers:  18%|█▊        | 1191/6717 [04:03<18:56,  4.86it/s]

Processing tickers:  18%|█▊        | 1192/6717 [04:03<18:49,  4.89it/s]

Processing tickers:  18%|█▊        | 1193/6717 [04:03<18:39,  4.93it/s]

Processing tickers:  18%|█▊        | 1194/6717 [04:04<18:47,  4.90it/s]

Processing tickers:  18%|█▊        | 1195/6717 [04:04<18:51,  4.88it/s]

Processing tickers:  18%|█▊        | 1196/6717 [04:04<18:40,  4.93it/s]

Processing tickers:  18%|█▊        | 1197/6717 [04:04<18:39,  4.93it/s]

Processing tickers:  18%|█▊        | 1198/6717 [04:04<18:34,  4.95it/s]

Processing tickers:  18%|█▊        | 1199/6717 [04:05<18:36,  4.94it/s]

Processing tickers:  18%|█▊        | 1200/6717 [04:05<18:35,  4.95it/s]

Processing tickers:  18%|█▊        | 1201/6717 [04:05<18:43,  4.91it/s]

Processing tickers:  18%|█▊        | 1202/6717 [04:05<18:40,  4.92it/s]

Processing tickers:  18%|█▊        | 1203/6717 [04:05<18:39,  4.93it/s]

Processing tickers:  18%|█▊        | 1204/6717 [04:06<18:46,  4.90it/s]

Processing tickers:  18%|█▊        | 1205/6717 [04:06<18:49,  4.88it/s]

Processing tickers:  18%|█▊        | 1206/6717 [04:06<18:50,  4.87it/s]

Processing tickers:  18%|█▊        | 1207/6717 [04:06<19:00,  4.83it/s]

Processing tickers:  18%|█▊        | 1208/6717 [04:06<18:50,  4.87it/s]

Processing tickers:  18%|█▊        | 1209/6717 [04:07<18:40,  4.92it/s]

Processing tickers:  18%|█▊        | 1210/6717 [04:07<18:34,  4.94it/s]

Processing tickers:  18%|█▊        | 1211/6717 [04:07<18:30,  4.96it/s]

Processing tickers:  18%|█▊        | 1212/6717 [04:07<18:27,  4.97it/s]

Processing tickers:  18%|█▊        | 1213/6717 [04:07<18:27,  4.97it/s]

Processing tickers:  18%|█▊        | 1214/6717 [04:08<18:26,  4.98it/s]

Processing tickers:  18%|█▊        | 1215/6717 [04:08<18:27,  4.97it/s]

Processing tickers:  18%|█▊        | 1216/6717 [04:08<18:23,  4.99it/s]

Processing tickers:  18%|█▊        | 1217/6717 [04:08<18:23,  4.99it/s]

Processing tickers:  18%|█▊        | 1218/6717 [04:08<18:38,  4.92it/s]

Processing tickers:  18%|█▊        | 1219/6717 [04:09<18:35,  4.93it/s]

Processing tickers:  18%|█▊        | 1220/6717 [04:09<18:31,  4.95it/s]

Processing tickers:  18%|█▊        | 1221/6717 [04:09<18:55,  4.84it/s]

Processing tickers:  18%|█▊        | 1222/6717 [04:09<18:45,  4.88it/s]

Processing tickers:  18%|█▊        | 1223/6717 [04:09<18:37,  4.92it/s]

Processing tickers:  18%|█▊        | 1224/6717 [04:10<18:30,  4.95it/s]

Processing tickers:  18%|█▊        | 1225/6717 [04:10<18:56,  4.83it/s]

Processing tickers:  18%|█▊        | 1226/6717 [04:10<18:51,  4.85it/s]

Processing tickers:  18%|█▊        | 1227/6717 [04:10<18:38,  4.91it/s]

Processing tickers:  18%|█▊        | 1228/6717 [04:10<18:33,  4.93it/s]

Processing tickers:  18%|█▊        | 1229/6717 [04:11<18:28,  4.95it/s]

Processing tickers:  18%|█▊        | 1230/6717 [04:11<18:27,  4.95it/s]

Processing tickers:  18%|█▊        | 1231/6717 [04:11<18:31,  4.93it/s]

Processing tickers:  18%|█▊        | 1232/6717 [04:11<18:29,  4.95it/s]

Processing tickers:  18%|█▊        | 1233/6717 [04:11<18:27,  4.95it/s]

Processing tickers:  18%|█▊        | 1234/6717 [04:12<18:26,  4.95it/s]

Processing tickers:  18%|█▊        | 1235/6717 [04:12<18:34,  4.92it/s]

Processing tickers:  18%|█▊        | 1236/6717 [04:12<18:29,  4.94it/s]

Processing tickers:  18%|█▊        | 1237/6717 [04:12<19:13,  4.75it/s]

Processing tickers:  18%|█▊        | 1238/6717 [04:12<18:59,  4.81it/s]

Processing tickers:  18%|█▊        | 1239/6717 [04:13<18:44,  4.87it/s]

Processing tickers:  18%|█▊        | 1240/6717 [04:13<18:32,  4.92it/s]

Processing tickers:  18%|█▊        | 1241/6717 [04:13<19:06,  4.78it/s]

Processing tickers:  18%|█▊        | 1242/6717 [04:13<18:50,  4.84it/s]

Processing tickers:  19%|█▊        | 1243/6717 [04:13<18:40,  4.89it/s]

Processing tickers:  19%|█▊        | 1244/6717 [04:14<18:30,  4.93it/s]

Processing tickers:  19%|█▊        | 1245/6717 [04:14<18:27,  4.94it/s]

Processing tickers:  19%|█▊        | 1246/6717 [04:14<19:04,  4.78it/s]

Processing tickers:  19%|█▊        | 1247/6717 [04:14<18:52,  4.83it/s]

Processing tickers:  19%|█▊        | 1248/6717 [04:15<18:45,  4.86it/s]

Processing tickers:  19%|█▊        | 1249/6717 [04:15<18:37,  4.89it/s]

Processing tickers:  19%|█▊        | 1250/6717 [04:15<18:40,  4.88it/s]

Processing tickers:  19%|█▊        | 1251/6717 [04:15<19:02,  4.78it/s]

Processing tickers:  19%|█▊        | 1252/6717 [04:15<18:48,  4.84it/s]

Processing tickers:  19%|█▊        | 1253/6717 [04:16<18:42,  4.87it/s]

Processing tickers:  19%|█▊        | 1254/6717 [04:16<18:32,  4.91it/s]

Processing tickers:  19%|█▊        | 1255/6717 [04:16<18:31,  4.92it/s]

Processing tickers:  19%|█▊        | 1256/6717 [04:16<18:30,  4.92it/s]

Processing tickers:  19%|█▊        | 1257/6717 [04:16<18:24,  4.94it/s]

Processing tickers:  19%|█▊        | 1258/6717 [04:17<18:21,  4.96it/s]

Processing tickers:  19%|█▊        | 1259/6717 [04:17<18:34,  4.90it/s]

Processing tickers:  19%|█▉        | 1260/6717 [04:17<18:34,  4.90it/s]

Processing tickers:  19%|█▉        | 1261/6717 [04:17<18:33,  4.90it/s]

Processing tickers:  19%|█▉        | 1262/6717 [04:17<18:25,  4.93it/s]

Processing tickers:  19%|█▉        | 1263/6717 [04:18<18:19,  4.96it/s]

Processing tickers:  19%|█▉        | 1264/6717 [04:18<18:14,  4.98it/s]

Processing tickers:  19%|█▉        | 1265/6717 [04:18<18:12,  4.99it/s]

Processing tickers:  19%|█▉        | 1266/6717 [04:18<18:14,  4.98it/s]

Processing tickers:  19%|█▉        | 1267/6717 [04:18<18:16,  4.97it/s]

Processing tickers:  19%|█▉        | 1268/6717 [04:19<18:17,  4.96it/s]

Processing tickers:  19%|█▉        | 1269/6717 [04:19<18:19,  4.96it/s]

Processing tickers:  19%|█▉        | 1270/6717 [04:19<18:20,  4.95it/s]

Processing tickers:  19%|█▉        | 1271/6717 [04:19<18:11,  4.99it/s]

Processing tickers:  19%|█▉        | 1272/6717 [04:19<18:12,  4.98it/s]

Processing tickers:  19%|█▉        | 1273/6717 [04:20<18:07,  5.01it/s]

Processing tickers:  19%|█▉        | 1274/6717 [04:20<18:11,  4.99it/s]

Processing tickers:  19%|█▉        | 1275/6717 [04:20<18:11,  4.99it/s]

Processing tickers:  19%|█▉        | 1276/6717 [04:20<18:10,  4.99it/s]

Processing tickers:  19%|█▉        | 1277/6717 [04:20<18:07,  5.00it/s]

Processing tickers:  19%|█▉        | 1278/6717 [04:21<18:11,  4.98it/s]

Processing tickers:  19%|█▉        | 1279/6717 [04:21<18:16,  4.96it/s]

Processing tickers:  19%|█▉        | 1280/6717 [04:21<18:35,  4.88it/s]

Processing tickers:  19%|█▉        | 1281/6717 [04:21<18:25,  4.92it/s]

Processing tickers:  19%|█▉        | 1282/6717 [04:21<18:19,  4.94it/s]

Processing tickers:  19%|█▉        | 1283/6717 [04:22<18:32,  4.89it/s]

Processing tickers:  19%|█▉        | 1284/6717 [04:22<18:33,  4.88it/s]

Processing tickers:  19%|█▉        | 1285/6717 [04:22<18:41,  4.84it/s]

Processing tickers:  19%|█▉        | 1286/6717 [04:22<18:30,  4.89it/s]

Processing tickers:  19%|█▉        | 1287/6717 [04:22<18:43,  4.83it/s]

Processing tickers:  19%|█▉        | 1288/6717 [04:23<18:30,  4.89it/s]

Processing tickers:  19%|█▉        | 1289/6717 [04:23<18:34,  4.87it/s]

Processing tickers:  19%|█▉        | 1290/6717 [04:23<18:29,  4.89it/s]

Processing tickers:  19%|█▉        | 1291/6717 [04:23<18:28,  4.90it/s]

Processing tickers:  19%|█▉        | 1292/6717 [04:23<18:25,  4.91it/s]

Processing tickers:  19%|█▉        | 1293/6717 [04:24<18:22,  4.92it/s]

Processing tickers:  19%|█▉        | 1294/6717 [04:24<18:20,  4.93it/s]

Processing tickers:  19%|█▉        | 1295/6717 [04:24<18:12,  4.96it/s]

Processing tickers:  19%|█▉        | 1296/6717 [04:24<18:11,  4.97it/s]

Processing tickers:  19%|█▉        | 1297/6717 [04:24<18:11,  4.97it/s]

Processing tickers:  19%|█▉        | 1298/6717 [04:25<18:07,  4.98it/s]

Processing tickers:  19%|█▉        | 1299/6717 [04:25<18:11,  4.96it/s]

Processing tickers:  19%|█▉        | 1300/6717 [04:25<18:17,  4.94it/s]

Processing tickers:  19%|█▉        | 1301/6717 [04:25<18:14,  4.95it/s]

Processing tickers:  19%|█▉        | 1302/6717 [04:25<18:16,  4.94it/s]

Processing tickers:  19%|█▉        | 1303/6717 [04:26<18:23,  4.91it/s]

Processing tickers:  19%|█▉        | 1304/6717 [04:26<18:12,  4.96it/s]

Processing tickers:  19%|█▉        | 1305/6717 [04:26<18:14,  4.95it/s]

Processing tickers:  19%|█▉        | 1306/6717 [04:26<18:13,  4.95it/s]

Processing tickers:  19%|█▉        | 1307/6717 [04:26<18:15,  4.94it/s]

Processing tickers:  19%|█▉        | 1308/6717 [04:27<18:13,  4.95it/s]

Processing tickers:  19%|█▉        | 1309/6717 [04:27<18:40,  4.83it/s]

Processing tickers:  20%|█▉        | 1310/6717 [04:27<18:33,  4.86it/s]

Processing tickers:  20%|█▉        | 1311/6717 [04:27<18:39,  4.83it/s]

Processing tickers:  20%|█▉        | 1312/6717 [04:28<18:40,  4.82it/s]

Processing tickers:  20%|█▉        | 1313/6717 [04:28<18:37,  4.84it/s]

Processing tickers:  20%|█▉        | 1314/6717 [04:28<18:26,  4.88it/s]

Processing tickers:  20%|█▉        | 1315/6717 [04:28<18:36,  4.84it/s]

Processing tickers:  20%|█▉        | 1316/6717 [04:28<18:27,  4.88it/s]

Processing tickers:  20%|█▉        | 1317/6717 [04:29<18:24,  4.89it/s]

Processing tickers:  20%|█▉        | 1318/6717 [04:29<18:37,  4.83it/s]

Processing tickers:  20%|█▉        | 1319/6717 [04:29<18:30,  4.86it/s]

Processing tickers:  20%|█▉        | 1320/6717 [04:29<18:56,  4.75it/s]

Processing tickers:  20%|█▉        | 1321/6717 [04:29<18:54,  4.76it/s]

Processing tickers:  20%|█▉        | 1322/6717 [04:30<18:39,  4.82it/s]

Processing tickers:  20%|█▉        | 1323/6717 [04:30<18:27,  4.87it/s]

Processing tickers:  20%|█▉        | 1324/6717 [04:30<18:36,  4.83it/s]

Processing tickers:  20%|█▉        | 1325/6717 [04:30<18:28,  4.87it/s]

Processing tickers:  20%|█▉        | 1326/6717 [04:30<18:26,  4.87it/s]

Processing tickers:  20%|█▉        | 1327/6717 [04:31<18:32,  4.84it/s]

Processing tickers:  20%|█▉        | 1328/6717 [04:31<18:26,  4.87it/s]

Processing tickers:  20%|█▉        | 1329/6717 [04:31<18:32,  4.84it/s]

Processing tickers:  20%|█▉        | 1330/6717 [04:31<18:20,  4.89it/s]

Processing tickers:  20%|█▉        | 1331/6717 [04:31<18:14,  4.92it/s]

Processing tickers:  20%|█▉        | 1332/6717 [04:32<18:23,  4.88it/s]

Processing tickers:  20%|█▉        | 1333/6717 [04:32<18:49,  4.77it/s]

Processing tickers:  20%|█▉        | 1334/6717 [04:32<18:34,  4.83it/s]

Processing tickers:  20%|█▉        | 1335/6717 [04:32<18:28,  4.85it/s]

Processing tickers:  20%|█▉        | 1336/6717 [04:32<18:20,  4.89it/s]

Processing tickers:  20%|█▉        | 1337/6717 [04:33<18:13,  4.92it/s]

Processing tickers:  20%|█▉        | 1338/6717 [04:33<18:15,  4.91it/s]

Processing tickers:  20%|█▉        | 1339/6717 [04:33<18:13,  4.92it/s]

Processing tickers:  20%|█▉        | 1340/6717 [04:33<18:29,  4.85it/s]

Processing tickers:  20%|█▉        | 1341/6717 [04:33<18:17,  4.90it/s]

Processing tickers:  20%|█▉        | 1342/6717 [04:34<18:06,  4.94it/s]

Processing tickers:  20%|█▉        | 1343/6717 [04:34<18:03,  4.96it/s]

Processing tickers:  20%|██        | 1344/6717 [04:34<18:27,  4.85it/s]

Processing tickers:  20%|██        | 1345/6717 [04:34<18:20,  4.88it/s]

Processing tickers:  20%|██        | 1346/6717 [04:34<18:14,  4.91it/s]

Processing tickers:  20%|██        | 1347/6717 [04:35<18:06,  4.94it/s]

Processing tickers:  20%|██        | 1348/6717 [04:35<18:02,  4.96it/s]

Processing tickers:  20%|██        | 1349/6717 [04:35<18:01,  4.96it/s]

Processing tickers:  20%|██        | 1350/6717 [04:35<18:04,  4.95it/s]

Processing tickers:  20%|██        | 1351/6717 [04:36<18:06,  4.94it/s]

Processing tickers:  20%|██        | 1352/6717 [04:36<18:07,  4.93it/s]

Processing tickers:  20%|██        | 1353/6717 [04:36<18:01,  4.96it/s]

Processing tickers:  20%|██        | 1354/6717 [04:36<18:00,  4.96it/s]

Processing tickers:  20%|██        | 1355/6717 [04:36<18:10,  4.92it/s]

Processing tickers:  20%|██        | 1356/6717 [04:37<18:16,  4.89it/s]

Processing tickers:  20%|██        | 1357/6717 [04:37<18:10,  4.92it/s]

Processing tickers:  20%|██        | 1358/6717 [04:37<18:06,  4.93it/s]

Processing tickers:  20%|██        | 1359/6717 [04:37<18:11,  4.91it/s]

Processing tickers:  20%|██        | 1360/6717 [04:37<18:05,  4.93it/s]

Processing tickers:  20%|██        | 1361/6717 [04:38<18:13,  4.90it/s]

Processing tickers:  20%|██        | 1362/6717 [04:38<18:12,  4.90it/s]

Processing tickers:  20%|██        | 1363/6717 [04:38<18:10,  4.91it/s]

Processing tickers:  20%|██        | 1364/6717 [04:38<18:04,  4.94it/s]

Processing tickers:  20%|██        | 1365/6717 [04:38<18:00,  4.95it/s]

Processing tickers:  20%|██        | 1366/6717 [04:39<18:22,  4.86it/s]

Processing tickers:  20%|██        | 1367/6717 [04:39<18:11,  4.90it/s]

Processing tickers:  20%|██        | 1368/6717 [04:39<18:06,  4.92it/s]

Processing tickers:  20%|██        | 1369/6717 [04:39<18:02,  4.94it/s]

Processing tickers:  20%|██        | 1370/6717 [04:39<18:36,  4.79it/s]

Processing tickers:  20%|██        | 1371/6717 [04:40<18:21,  4.85it/s]

Processing tickers:  20%|██        | 1372/6717 [04:40<18:08,  4.91it/s]

Processing tickers:  20%|██        | 1373/6717 [04:40<18:20,  4.86it/s]

Processing tickers:  20%|██        | 1374/6717 [04:40<18:15,  4.88it/s]

Processing tickers:  20%|██        | 1375/6717 [04:40<18:14,  4.88it/s]

Processing tickers:  20%|██        | 1376/6717 [04:41<18:14,  4.88it/s]

Processing tickers:  21%|██        | 1377/6717 [04:41<18:05,  4.92it/s]

Processing tickers:  21%|██        | 1378/6717 [04:41<18:37,  4.78it/s]

Processing tickers:  21%|██        | 1379/6717 [04:41<18:27,  4.82it/s]

Processing tickers:  21%|██        | 1380/6717 [04:41<18:46,  4.74it/s]

Processing tickers:  21%|██        | 1381/6717 [04:42<18:34,  4.79it/s]

Processing tickers:  21%|██        | 1382/6717 [04:42<18:21,  4.84it/s]

Processing tickers:  21%|██        | 1383/6717 [04:42<18:13,  4.88it/s]

Processing tickers:  21%|██        | 1384/6717 [04:42<18:05,  4.91it/s]

Processing tickers:  21%|██        | 1385/6717 [04:42<17:59,  4.94it/s]

Processing tickers:  21%|██        | 1386/6717 [04:43<17:59,  4.94it/s]

Processing tickers:  21%|██        | 1387/6717 [04:43<18:00,  4.93it/s]

Processing tickers:  21%|██        | 1388/6717 [04:43<18:09,  4.89it/s]

Processing tickers:  21%|██        | 1389/6717 [04:43<18:02,  4.92it/s]

Processing tickers:  21%|██        | 1390/6717 [04:43<18:03,  4.92it/s]

Processing tickers:  21%|██        | 1391/6717 [04:44<18:01,  4.92it/s]

Processing tickers:  21%|██        | 1392/6717 [04:44<18:06,  4.90it/s]

Processing tickers:  21%|██        | 1393/6717 [04:44<18:13,  4.87it/s]

Processing tickers:  21%|██        | 1394/6717 [04:44<18:08,  4.89it/s]

Processing tickers:  21%|██        | 1395/6717 [04:45<18:59,  4.67it/s]

Processing tickers:  21%|██        | 1396/6717 [04:45<18:38,  4.76it/s]

Processing tickers:  21%|██        | 1397/6717 [04:45<18:23,  4.82it/s]

Processing tickers:  21%|██        | 1398/6717 [04:45<18:13,  4.87it/s]

Processing tickers:  21%|██        | 1399/6717 [04:45<18:07,  4.89it/s]

Processing tickers:  21%|██        | 1400/6717 [04:46<18:02,  4.91it/s]

Processing tickers:  21%|██        | 1401/6717 [04:46<18:05,  4.90it/s]

Processing tickers:  21%|██        | 1402/6717 [04:46<18:11,  4.87it/s]

Processing tickers:  21%|██        | 1403/6717 [04:46<18:05,  4.90it/s]

Processing tickers:  21%|██        | 1404/6717 [04:46<18:05,  4.90it/s]

Processing tickers:  21%|██        | 1405/6717 [04:47<17:56,  4.93it/s]

Processing tickers:  21%|██        | 1406/6717 [04:47<17:55,  4.94it/s]

Processing tickers:  21%|██        | 1407/6717 [04:47<17:54,  4.94it/s]

Processing tickers:  21%|██        | 1408/6717 [04:47<17:52,  4.95it/s]

Processing tickers:  21%|██        | 1409/6717 [04:47<17:49,  4.96it/s]

Processing tickers:  21%|██        | 1410/6717 [04:48<17:49,  4.96it/s]

Processing tickers:  21%|██        | 1411/6717 [04:48<17:58,  4.92it/s]

Processing tickers:  21%|██        | 1412/6717 [04:48<17:58,  4.92it/s]

Processing tickers:  21%|██        | 1413/6717 [04:48<17:53,  4.94it/s]

Processing tickers:  21%|██        | 1414/6717 [04:48<17:49,  4.96it/s]

Processing tickers:  21%|██        | 1415/6717 [04:49<17:51,  4.95it/s]

Processing tickers:  21%|██        | 1416/6717 [04:49<17:47,  4.96it/s]

Processing tickers:  21%|██        | 1417/6717 [04:49<18:09,  4.86it/s]

Processing tickers:  21%|██        | 1418/6717 [04:49<18:05,  4.88it/s]

Processing tickers:  21%|██        | 1419/6717 [04:49<17:54,  4.93it/s]

Processing tickers:  21%|██        | 1420/6717 [04:50<17:59,  4.91it/s]

Processing tickers:  21%|██        | 1421/6717 [04:50<17:57,  4.92it/s]

Processing tickers:  21%|██        | 1422/6717 [04:50<18:07,  4.87it/s]

Processing tickers:  21%|██        | 1423/6717 [04:50<18:05,  4.88it/s]

Processing tickers:  21%|██        | 1424/6717 [04:50<17:59,  4.90it/s]

Processing tickers:  21%|██        | 1425/6717 [04:51<17:58,  4.91it/s]

Processing tickers:  21%|██        | 1426/6717 [04:51<17:57,  4.91it/s]

Processing tickers:  21%|██        | 1427/6717 [04:51<18:05,  4.87it/s]

Processing tickers:  21%|██▏       | 1428/6717 [04:51<18:03,  4.88it/s]

Processing tickers:  21%|██▏       | 1429/6717 [04:51<18:02,  4.88it/s]

Processing tickers:  21%|██▏       | 1430/6717 [04:52<18:02,  4.89it/s]

Processing tickers:  21%|██▏       | 1431/6717 [04:52<17:57,  4.91it/s]

Processing tickers:  21%|██▏       | 1432/6717 [04:52<17:52,  4.93it/s]

Processing tickers:  21%|██▏       | 1433/6717 [04:52<17:51,  4.93it/s]

Processing tickers:  21%|██▏       | 1434/6717 [04:52<17:53,  4.92it/s]

Processing tickers:  21%|██▏       | 1435/6717 [04:53<17:48,  4.94it/s]

Processing tickers:  21%|██▏       | 1436/6717 [04:53<17:53,  4.92it/s]

Processing tickers:  21%|██▏       | 1437/6717 [04:53<18:13,  4.83it/s]

Processing tickers:  21%|██▏       | 1438/6717 [04:53<18:01,  4.88it/s]

Processing tickers:  21%|██▏       | 1439/6717 [04:53<17:54,  4.91it/s]

Processing tickers:  21%|██▏       | 1440/6717 [04:54<17:51,  4.92it/s]

Processing tickers:  21%|██▏       | 1441/6717 [04:54<17:46,  4.95it/s]

Processing tickers:  21%|██▏       | 1442/6717 [04:54<17:49,  4.93it/s]

Processing tickers:  21%|██▏       | 1443/6717 [04:54<17:50,  4.93it/s]

Processing tickers:  21%|██▏       | 1444/6717 [04:54<17:51,  4.92it/s]

Processing tickers:  22%|██▏       | 1445/6717 [04:55<17:54,  4.91it/s]

Processing tickers:  22%|██▏       | 1446/6717 [04:55<18:00,  4.88it/s]

Processing tickers:  22%|██▏       | 1447/6717 [04:55<17:58,  4.89it/s]

Processing tickers:  22%|██▏       | 1448/6717 [04:55<17:57,  4.89it/s]

Processing tickers:  22%|██▏       | 1449/6717 [04:56<18:00,  4.88it/s]

Processing tickers:  22%|██▏       | 1450/6717 [04:56<18:08,  4.84it/s]

Processing tickers:  22%|██▏       | 1451/6717 [04:56<18:08,  4.84it/s]

Processing tickers:  22%|██▏       | 1452/6717 [04:56<18:29,  4.75it/s]

Processing tickers:  22%|██▏       | 1453/6717 [04:56<18:39,  4.70it/s]

Processing tickers:  22%|██▏       | 1454/6717 [04:57<18:17,  4.80it/s]

Processing tickers:  22%|██▏       | 1455/6717 [04:57<18:05,  4.85it/s]

Processing tickers:  22%|██▏       | 1456/6717 [04:57<17:54,  4.90it/s]

Processing tickers:  22%|██▏       | 1457/6717 [04:57<17:51,  4.91it/s]

Processing tickers:  22%|██▏       | 1458/6717 [04:57<17:49,  4.92it/s]

Processing tickers:  22%|██▏       | 1459/6717 [04:58<17:45,  4.94it/s]

Processing tickers:  22%|██▏       | 1460/6717 [04:58<17:46,  4.93it/s]

Processing tickers:  22%|██▏       | 1461/6717 [04:58<18:00,  4.87it/s]

Processing tickers:  22%|██▏       | 1462/6717 [04:58<17:52,  4.90it/s]

Processing tickers:  22%|██▏       | 1463/6717 [04:58<18:25,  4.75it/s]

Processing tickers:  22%|██▏       | 1464/6717 [04:59<18:09,  4.82it/s]

Processing tickers:  22%|██▏       | 1465/6717 [04:59<18:01,  4.85it/s]

Processing tickers:  22%|██▏       | 1466/6717 [04:59<18:09,  4.82it/s]

Processing tickers:  22%|██▏       | 1467/6717 [04:59<17:55,  4.88it/s]

Processing tickers:  22%|██▏       | 1468/6717 [04:59<18:35,  4.71it/s]

Processing tickers:  22%|██▏       | 1469/6717 [05:00<18:12,  4.80it/s]

Processing tickers:  22%|██▏       | 1470/6717 [05:00<18:01,  4.85it/s]

Processing tickers:  22%|██▏       | 1471/6717 [05:00<17:58,  4.87it/s]

Processing tickers:  22%|██▏       | 1472/6717 [05:00<17:51,  4.89it/s]

Processing tickers:  22%|██▏       | 1473/6717 [05:00<17:52,  4.89it/s]

Processing tickers:  22%|██▏       | 1474/6717 [05:01<17:56,  4.87it/s]

Processing tickers:  22%|██▏       | 1475/6717 [05:01<18:08,  4.81it/s]

Processing tickers:  22%|██▏       | 1476/6717 [05:01<18:28,  4.73it/s]

Processing tickers:  22%|██▏       | 1477/6717 [05:01<18:13,  4.79it/s]

Processing tickers:  22%|██▏       | 1478/6717 [05:02<18:00,  4.85it/s]

Processing tickers:  22%|██▏       | 1479/6717 [05:02<17:59,  4.85it/s]

Processing tickers:  22%|██▏       | 1480/6717 [05:02<17:51,  4.89it/s]

Processing tickers:  22%|██▏       | 1481/6717 [05:02<17:57,  4.86it/s]

Processing tickers:  22%|██▏       | 1482/6717 [05:02<17:48,  4.90it/s]

Processing tickers:  22%|██▏       | 1483/6717 [05:03<17:46,  4.91it/s]

Processing tickers:  22%|██▏       | 1484/6717 [05:03<17:43,  4.92it/s]

Processing tickers:  22%|██▏       | 1485/6717 [05:03<17:41,  4.93it/s]

Processing tickers:  22%|██▏       | 1486/6717 [05:03<17:51,  4.88it/s]

Processing tickers:  22%|██▏       | 1487/6717 [05:03<17:51,  4.88it/s]

Processing tickers:  22%|██▏       | 1488/6717 [05:04<17:53,  4.87it/s]

Processing tickers:  22%|██▏       | 1489/6717 [05:04<17:51,  4.88it/s]

Processing tickers:  22%|██▏       | 1490/6717 [05:04<17:56,  4.85it/s]

Processing tickers:  22%|██▏       | 1491/6717 [05:04<17:51,  4.88it/s]

Processing tickers:  22%|██▏       | 1492/6717 [05:04<17:46,  4.90it/s]

Processing tickers:  22%|██▏       | 1493/6717 [05:05<17:40,  4.93it/s]

Processing tickers:  22%|██▏       | 1494/6717 [05:05<17:38,  4.94it/s]

Processing tickers:  22%|██▏       | 1495/6717 [05:05<17:57,  4.85it/s]

Processing tickers:  22%|██▏       | 1496/6717 [05:05<17:53,  4.86it/s]

Processing tickers:  22%|██▏       | 1497/6717 [05:05<17:48,  4.89it/s]

Processing tickers:  22%|██▏       | 1498/6717 [05:06<17:42,  4.91it/s]

Processing tickers:  22%|██▏       | 1499/6717 [05:06<17:43,  4.91it/s]

Processing tickers:  22%|██▏       | 1500/6717 [05:06<17:51,  4.87it/s]

Processing tickers:  22%|██▏       | 1501/6717 [05:06<17:42,  4.91it/s]

Processing tickers:  22%|██▏       | 1502/6717 [05:06<17:39,  4.92it/s]

Processing tickers:  22%|██▏       | 1503/6717 [05:07<17:40,  4.91it/s]

Processing tickers:  22%|██▏       | 1504/6717 [05:07<17:35,  4.94it/s]

Processing tickers:  22%|██▏       | 1505/6717 [05:07<17:34,  4.94it/s]

Processing tickers:  22%|██▏       | 1506/6717 [05:07<17:31,  4.95it/s]

Processing tickers:  22%|██▏       | 1507/6717 [05:07<17:30,  4.96it/s]

Processing tickers:  22%|██▏       | 1508/6717 [05:08<17:33,  4.95it/s]

Processing tickers:  22%|██▏       | 1509/6717 [05:08<17:30,  4.96it/s]

Processing tickers:  22%|██▏       | 1510/6717 [05:08<17:26,  4.97it/s]

Processing tickers:  22%|██▏       | 1511/6717 [05:08<17:35,  4.93it/s]

Processing tickers:  23%|██▎       | 1512/6717 [05:08<17:40,  4.91it/s]

Processing tickers:  23%|██▎       | 1513/6717 [05:09<17:38,  4.92it/s]

Processing tickers:  23%|██▎       | 1514/6717 [05:09<18:01,  4.81it/s]

Processing tickers:  23%|██▎       | 1515/6717 [05:09<18:01,  4.81it/s]

Processing tickers:  23%|██▎       | 1516/6717 [05:09<17:51,  4.85it/s]

Processing tickers:  23%|██▎       | 1517/6717 [05:09<17:45,  4.88it/s]

Processing tickers:  23%|██▎       | 1518/6717 [05:10<17:33,  4.93it/s]

Processing tickers:  23%|██▎       | 1519/6717 [05:10<17:37,  4.92it/s]

Processing tickers:  23%|██▎       | 1520/6717 [05:10<17:44,  4.88it/s]

Processing tickers:  23%|██▎       | 1521/6717 [05:10<17:34,  4.93it/s]

Processing tickers:  23%|██▎       | 1522/6717 [05:10<17:34,  4.93it/s]

Processing tickers:  23%|██▎       | 1523/6717 [05:11<18:04,  4.79it/s]

Processing tickers:  23%|██▎       | 1524/6717 [05:11<17:47,  4.87it/s]

Processing tickers:  23%|██▎       | 1525/6717 [05:11<17:37,  4.91it/s]

Processing tickers:  23%|██▎       | 1526/6717 [05:11<17:35,  4.92it/s]

Processing tickers:  23%|██▎       | 1527/6717 [05:12<17:23,  4.97it/s]

Processing tickers:  23%|██▎       | 1528/6717 [05:12<17:20,  4.99it/s]

Processing tickers:  23%|██▎       | 1529/6717 [05:12<17:14,  5.02it/s]

Processing tickers:  23%|██▎       | 1530/6717 [05:12<17:48,  4.85it/s]

Processing tickers:  23%|██▎       | 1531/6717 [05:12<17:48,  4.85it/s]

Processing tickers:  23%|██▎       | 1532/6717 [05:13<17:41,  4.88it/s]

Processing tickers:  23%|██▎       | 1533/6717 [05:13<17:35,  4.91it/s]

Processing tickers:  23%|██▎       | 1534/6717 [05:13<17:39,  4.89it/s]

Processing tickers:  23%|██▎       | 1535/6717 [05:13<17:39,  4.89it/s]

Processing tickers:  23%|██▎       | 1536/6717 [05:13<17:36,  4.90it/s]

Processing tickers:  23%|██▎       | 1537/6717 [05:14<17:33,  4.92it/s]

Processing tickers:  23%|██▎       | 1538/6717 [05:14<17:43,  4.87it/s]

Processing tickers:  23%|██▎       | 1539/6717 [05:14<17:32,  4.92it/s]

Processing tickers:  23%|██▎       | 1540/6717 [05:14<17:33,  4.92it/s]

Processing tickers:  23%|██▎       | 1541/6717 [05:14<17:32,  4.92it/s]

Processing tickers:  23%|██▎       | 1542/6717 [05:15<17:36,  4.90it/s]

Processing tickers:  23%|██▎       | 1543/6717 [05:15<17:34,  4.91it/s]

Processing tickers:  23%|██▎       | 1544/6717 [05:15<17:38,  4.89it/s]

Processing tickers:  23%|██▎       | 1545/6717 [05:15<17:31,  4.92it/s]

Processing tickers:  23%|██▎       | 1546/6717 [05:15<17:35,  4.90it/s]

Processing tickers:  23%|██▎       | 1547/6717 [05:16<17:41,  4.87it/s]

Processing tickers:  23%|██▎       | 1548/6717 [05:16<18:16,  4.71it/s]

Processing tickers:  23%|██▎       | 1549/6717 [05:16<17:59,  4.79it/s]

Processing tickers:  23%|██▎       | 1550/6717 [05:16<17:46,  4.84it/s]

Processing tickers:  23%|██▎       | 1551/6717 [05:16<17:39,  4.87it/s]

Processing tickers:  23%|██▎       | 1552/6717 [05:17<17:32,  4.91it/s]

Processing tickers:  23%|██▎       | 1553/6717 [05:17<17:25,  4.94it/s]

Processing tickers:  23%|██▎       | 1554/6717 [05:17<17:33,  4.90it/s]

Processing tickers:  23%|██▎       | 1555/6717 [05:17<17:28,  4.93it/s]

Processing tickers:  23%|██▎       | 1556/6717 [05:17<17:27,  4.93it/s]

Processing tickers:  23%|██▎       | 1557/6717 [05:18<17:26,  4.93it/s]

Processing tickers:  23%|██▎       | 1558/6717 [05:18<17:23,  4.94it/s]

Processing tickers:  23%|██▎       | 1559/6717 [05:18<17:24,  4.94it/s]

Processing tickers:  23%|██▎       | 1560/6717 [05:18<17:23,  4.94it/s]

Processing tickers:  23%|██▎       | 1561/6717 [05:18<17:22,  4.94it/s]

Processing tickers:  23%|██▎       | 1562/6717 [05:19<17:30,  4.91it/s]

Processing tickers:  23%|██▎       | 1563/6717 [05:19<17:28,  4.92it/s]

Processing tickers:  23%|██▎       | 1564/6717 [05:19<17:20,  4.95it/s]

Processing tickers:  23%|██▎       | 1565/6717 [05:19<17:19,  4.96it/s]

Processing tickers:  23%|██▎       | 1566/6717 [05:19<17:25,  4.93it/s]

Processing tickers:  23%|██▎       | 1567/6717 [05:20<17:19,  4.95it/s]

Processing tickers:  23%|██▎       | 1568/6717 [05:20<17:21,  4.94it/s]

Processing tickers:  23%|██▎       | 1569/6717 [05:20<17:18,  4.96it/s]

Processing tickers:  23%|██▎       | 1570/6717 [05:20<17:19,  4.95it/s]

Processing tickers:  23%|██▎       | 1571/6717 [05:20<17:16,  4.97it/s]

Processing tickers:  23%|██▎       | 1572/6717 [05:21<17:12,  4.99it/s]

Processing tickers:  23%|██▎       | 1573/6717 [05:21<17:20,  4.94it/s]

Processing tickers:  23%|██▎       | 1574/6717 [05:21<17:19,  4.95it/s]

Processing tickers:  23%|██▎       | 1575/6717 [05:21<17:15,  4.97it/s]

Processing tickers:  23%|██▎       | 1576/6717 [05:21<17:27,  4.91it/s]

Processing tickers:  23%|██▎       | 1577/6717 [05:22<17:23,  4.93it/s]

Processing tickers:  23%|██▎       | 1578/6717 [05:22<17:17,  4.95it/s]

Processing tickers:  24%|██▎       | 1579/6717 [05:22<17:20,  4.94it/s]

Processing tickers:  24%|██▎       | 1580/6717 [05:22<17:17,  4.95it/s]

Processing tickers:  24%|██▎       | 1581/6717 [05:22<17:22,  4.93it/s]

Processing tickers:  24%|██▎       | 1582/6717 [05:23<17:20,  4.93it/s]

Processing tickers:  24%|██▎       | 1583/6717 [05:23<17:22,  4.92it/s]

Processing tickers:  24%|██▎       | 1584/6717 [05:23<17:22,  4.92it/s]

Processing tickers:  24%|██▎       | 1585/6717 [05:23<17:19,  4.94it/s]

Processing tickers:  24%|██▎       | 1586/6717 [05:24<18:05,  4.73it/s]

Processing tickers:  24%|██▎       | 1587/6717 [05:24<17:49,  4.80it/s]

Processing tickers:  24%|██▎       | 1588/6717 [05:24<17:34,  4.86it/s]

Processing tickers:  24%|██▎       | 1589/6717 [05:24<17:28,  4.89it/s]

Processing tickers:  24%|██▎       | 1590/6717 [05:24<17:33,  4.87it/s]

Processing tickers:  24%|██▎       | 1591/6717 [05:25<17:30,  4.88it/s]

Processing tickers:  24%|██▎       | 1592/6717 [05:25<17:26,  4.90it/s]

Processing tickers:  24%|██▎       | 1593/6717 [05:25<17:26,  4.89it/s]

Processing tickers:  24%|██▎       | 1594/6717 [05:25<17:21,  4.92it/s]

Processing tickers:  24%|██▎       | 1595/6717 [05:25<17:42,  4.82it/s]

Processing tickers:  24%|██▍       | 1596/6717 [05:26<17:32,  4.87it/s]

Processing tickers:  24%|██▍       | 1597/6717 [05:26<17:56,  4.76it/s]

Processing tickers:  24%|██▍       | 1598/6717 [05:26<17:57,  4.75it/s]

Processing tickers:  24%|██▍       | 1599/6717 [05:26<17:40,  4.82it/s]

Processing tickers:  24%|██▍       | 1600/6717 [05:26<17:35,  4.85it/s]

Processing tickers:  24%|██▍       | 1601/6717 [05:27<17:29,  4.88it/s]

Processing tickers:  24%|██▍       | 1602/6717 [05:27<17:34,  4.85it/s]

Processing tickers:  24%|██▍       | 1603/6717 [05:27<17:33,  4.85it/s]

Processing tickers:  24%|██▍       | 1604/6717 [05:27<17:32,  4.86it/s]

Processing tickers:  24%|██▍       | 1605/6717 [05:27<17:25,  4.89it/s]

Processing tickers:  24%|██▍       | 1606/6717 [05:28<17:21,  4.91it/s]

Processing tickers:  24%|██▍       | 1607/6717 [05:28<17:37,  4.83it/s]

Processing tickers:  24%|██▍       | 1608/6717 [05:28<17:31,  4.86it/s]

Processing tickers:  24%|██▍       | 1609/6717 [05:28<17:23,  4.90it/s]

Processing tickers:  24%|██▍       | 1610/6717 [05:28<17:16,  4.93it/s]

Processing tickers:  24%|██▍       | 1611/6717 [05:29<17:16,  4.93it/s]

Processing tickers:  24%|██▍       | 1612/6717 [05:29<17:09,  4.96it/s]

Processing tickers:  24%|██▍       | 1613/6717 [05:29<17:25,  4.88it/s]

Processing tickers:  24%|██▍       | 1614/6717 [05:29<17:17,  4.92it/s]

Processing tickers:  24%|██▍       | 1615/6717 [05:29<17:43,  4.80it/s]

Processing tickers:  24%|██▍       | 1616/6717 [05:30<17:31,  4.85it/s]

Processing tickers:  24%|██▍       | 1617/6717 [05:30<17:31,  4.85it/s]

Processing tickers:  24%|██▍       | 1618/6717 [05:30<17:22,  4.89it/s]

Processing tickers:  24%|██▍       | 1619/6717 [05:30<17:18,  4.91it/s]

Processing tickers:  24%|██▍       | 1620/6717 [05:31<17:50,  4.76it/s]

Processing tickers:  24%|██▍       | 1621/6717 [05:31<18:17,  4.64it/s]

Processing tickers:  24%|██▍       | 1622/6717 [05:31<17:56,  4.73it/s]

Processing tickers:  24%|██▍       | 1623/6717 [05:31<17:41,  4.80it/s]

Processing tickers:  24%|██▍       | 1624/6717 [05:31<17:40,  4.80it/s]

Processing tickers:  24%|██▍       | 1625/6717 [05:32<17:34,  4.83it/s]

Processing tickers:  24%|██▍       | 1626/6717 [05:32<17:29,  4.85it/s]

Processing tickers:  24%|██▍       | 1627/6717 [05:32<17:20,  4.89it/s]

Processing tickers:  24%|██▍       | 1628/6717 [05:32<17:15,  4.91it/s]

Processing tickers:  24%|██▍       | 1629/6717 [05:32<17:29,  4.85it/s]

Processing tickers:  24%|██▍       | 1630/6717 [05:33<17:34,  4.82it/s]

Processing tickers:  24%|██▍       | 1631/6717 [05:33<17:21,  4.88it/s]

Processing tickers:  24%|██▍       | 1632/6717 [05:33<17:54,  4.73it/s]

Processing tickers:  24%|██▍       | 1633/6717 [05:33<17:38,  4.80it/s]

Processing tickers:  24%|██▍       | 1634/6717 [05:33<17:27,  4.85it/s]

Processing tickers:  24%|██▍       | 1635/6717 [05:34<17:18,  4.89it/s]

Processing tickers:  24%|██▍       | 1636/6717 [05:34<17:09,  4.93it/s]

Processing tickers:  24%|██▍       | 1637/6717 [05:34<17:23,  4.87it/s]

Processing tickers:  24%|██▍       | 1638/6717 [05:34<17:14,  4.91it/s]

Processing tickers:  24%|██▍       | 1639/6717 [05:34<17:05,  4.95it/s]

Processing tickers:  24%|██▍       | 1640/6717 [05:35<17:03,  4.96it/s]

Processing tickers:  24%|██▍       | 1641/6717 [05:35<17:01,  4.97it/s]

Processing tickers:  24%|██▍       | 1642/6717 [05:35<17:07,  4.94it/s]

Processing tickers:  24%|██▍       | 1643/6717 [05:35<17:08,  4.94it/s]

Processing tickers:  24%|██▍       | 1644/6717 [05:35<17:17,  4.89it/s]

Processing tickers:  24%|██▍       | 1645/6717 [05:36<17:08,  4.93it/s]

Processing tickers:  25%|██▍       | 1646/6717 [05:36<17:08,  4.93it/s]

Processing tickers:  25%|██▍       | 1647/6717 [05:36<17:09,  4.92it/s]

Processing tickers:  25%|██▍       | 1648/6717 [05:36<17:13,  4.90it/s]

Processing tickers:  25%|██▍       | 1649/6717 [05:36<17:16,  4.89it/s]

Processing tickers:  25%|██▍       | 1650/6717 [05:37<17:18,  4.88it/s]

Processing tickers:  25%|██▍       | 1651/6717 [05:37<17:13,  4.90it/s]

Processing tickers:  25%|██▍       | 1652/6717 [05:37<17:13,  4.90it/s]

Processing tickers:  25%|██▍       | 1653/6717 [05:37<17:18,  4.87it/s]

Processing tickers:  25%|██▍       | 1654/6717 [05:37<17:11,  4.91it/s]

Processing tickers:  25%|██▍       | 1655/6717 [05:38<17:10,  4.91it/s]

Processing tickers:  25%|██▍       | 1656/6717 [05:38<17:07,  4.93it/s]

Processing tickers:  25%|██▍       | 1657/6717 [05:38<17:21,  4.86it/s]

Processing tickers:  25%|██▍       | 1658/6717 [05:38<17:16,  4.88it/s]

Processing tickers:  25%|██▍       | 1659/6717 [05:39<17:11,  4.90it/s]

Processing tickers:  25%|██▍       | 1660/6717 [05:39<17:08,  4.92it/s]

Processing tickers:  25%|██▍       | 1661/6717 [05:39<17:04,  4.93it/s]

Processing tickers:  25%|██▍       | 1662/6717 [05:39<17:05,  4.93it/s]

Processing tickers:  25%|██▍       | 1663/6717 [05:39<17:10,  4.91it/s]

Processing tickers:  25%|██▍       | 1664/6717 [05:40<17:13,  4.89it/s]

Processing tickers:  25%|██▍       | 1665/6717 [05:40<17:17,  4.87it/s]

Processing tickers:  25%|██▍       | 1666/6717 [05:40<17:10,  4.90it/s]

Processing tickers:  25%|██▍       | 1667/6717 [05:40<17:06,  4.92it/s]

Processing tickers:  25%|██▍       | 1668/6717 [05:40<17:06,  4.92it/s]

Processing tickers:  25%|██▍       | 1669/6717 [05:41<17:01,  4.94it/s]

Processing tickers:  25%|██▍       | 1670/6717 [05:41<17:00,  4.94it/s]

Processing tickers:  25%|██▍       | 1671/6717 [05:41<17:05,  4.92it/s]

Processing tickers:  25%|██▍       | 1672/6717 [05:41<17:00,  4.94it/s]

Processing tickers:  25%|██▍       | 1673/6717 [05:41<17:03,  4.93it/s]

Processing tickers:  25%|██▍       | 1674/6717 [05:42<17:09,  4.90it/s]

Processing tickers:  25%|██▍       | 1675/6717 [05:42<17:09,  4.90it/s]

Processing tickers:  25%|██▍       | 1676/6717 [05:42<17:07,  4.91it/s]

Processing tickers:  25%|██▍       | 1677/6717 [05:42<17:08,  4.90it/s]

Processing tickers:  25%|██▍       | 1678/6717 [05:42<17:05,  4.91it/s]

Processing tickers:  25%|██▍       | 1679/6717 [05:43<17:01,  4.93it/s]

Processing tickers:  25%|██▌       | 1680/6717 [05:43<16:55,  4.96it/s]

Processing tickers:  25%|██▌       | 1681/6717 [05:43<17:12,  4.88it/s]

Processing tickers:  25%|██▌       | 1682/6717 [05:43<17:07,  4.90it/s]

Processing tickers:  25%|██▌       | 1683/6717 [05:43<17:00,  4.93it/s]

Processing tickers:  25%|██▌       | 1684/6717 [05:44<17:00,  4.93it/s]

Processing tickers:  25%|██▌       | 1685/6717 [05:44<16:58,  4.94it/s]

Processing tickers:  25%|██▌       | 1686/6717 [05:44<17:10,  4.88it/s]

Processing tickers:  25%|██▌       | 1687/6717 [05:44<17:05,  4.91it/s]

Processing tickers:  25%|██▌       | 1688/6717 [05:44<17:49,  4.70it/s]

Processing tickers:  25%|██▌       | 1689/6717 [05:45<17:28,  4.80it/s]

Processing tickers:  25%|██▌       | 1690/6717 [05:45<17:18,  4.84it/s]

Processing tickers:  25%|██▌       | 1691/6717 [05:45<17:13,  4.86it/s]

Processing tickers:  25%|██▌       | 1692/6717 [05:45<17:15,  4.85it/s]

Processing tickers:  25%|██▌       | 1693/6717 [05:45<17:28,  4.79it/s]

Processing tickers:  25%|██▌       | 1694/6717 [05:46<17:15,  4.85it/s]

Processing tickers:  25%|██▌       | 1695/6717 [05:46<17:05,  4.90it/s]

Processing tickers:  25%|██▌       | 1696/6717 [05:46<17:08,  4.88it/s]

Processing tickers:  25%|██▌       | 1697/6717 [05:46<17:01,  4.91it/s]

Processing tickers:  25%|██▌       | 1698/6717 [05:46<17:14,  4.85it/s]

Processing tickers:  25%|██▌       | 1699/6717 [05:47<17:11,  4.87it/s]

Processing tickers:  25%|██▌       | 1700/6717 [05:47<17:03,  4.90it/s]

Processing tickers:  25%|██▌       | 1701/6717 [05:47<17:00,  4.92it/s]

Processing tickers:  25%|██▌       | 1702/6717 [05:47<16:54,  4.94it/s]

Processing tickers:  25%|██▌       | 1703/6717 [05:47<16:56,  4.93it/s]

Processing tickers:  25%|██▌       | 1704/6717 [05:48<16:53,  4.95it/s]

Processing tickers:  25%|██▌       | 1705/6717 [05:48<16:50,  4.96it/s]

Processing tickers:  25%|██▌       | 1706/6717 [05:48<17:29,  4.77it/s]

Processing tickers:  25%|██▌       | 1707/6717 [05:48<17:20,  4.82it/s]

Processing tickers:  25%|██▌       | 1708/6717 [05:49<17:14,  4.84it/s]

Processing tickers:  25%|██▌       | 1709/6717 [05:49<17:05,  4.89it/s]

Processing tickers:  25%|██▌       | 1710/6717 [05:49<16:56,  4.93it/s]

Processing tickers:  25%|██▌       | 1711/6717 [05:49<16:57,  4.92it/s]

Processing tickers:  25%|██▌       | 1712/6717 [05:49<16:59,  4.91it/s]

Processing tickers:  26%|██▌       | 1713/6717 [05:50<16:59,  4.91it/s]

Processing tickers:  26%|██▌       | 1714/6717 [05:50<17:02,  4.89it/s]

Processing tickers:  26%|██▌       | 1715/6717 [05:50<16:57,  4.91it/s]

Processing tickers:  26%|██▌       | 1716/6717 [05:50<16:59,  4.91it/s]

Processing tickers:  26%|██▌       | 1717/6717 [05:50<17:01,  4.90it/s]

Processing tickers:  26%|██▌       | 1718/6717 [05:51<16:58,  4.91it/s]

Processing tickers:  26%|██▌       | 1719/6717 [05:51<17:04,  4.88it/s]

Processing tickers:  26%|██▌       | 1720/6717 [05:51<16:54,  4.93it/s]

Processing tickers:  26%|██▌       | 1721/6717 [05:51<17:15,  4.82it/s]

Processing tickers:  26%|██▌       | 1722/6717 [05:51<17:02,  4.89it/s]

Processing tickers:  26%|██▌       | 1723/6717 [05:52<17:04,  4.88it/s]

Processing tickers:  26%|██▌       | 1724/6717 [05:52<16:51,  4.94it/s]

Processing tickers:  26%|██▌       | 1725/6717 [05:52<17:00,  4.89it/s]

Processing tickers:  26%|██▌       | 1726/6717 [05:52<16:59,  4.89it/s]

Processing tickers:  26%|██▌       | 1727/6717 [05:52<16:55,  4.91it/s]

Processing tickers:  26%|██▌       | 1728/6717 [05:53<16:51,  4.93it/s]

Processing tickers:  26%|██▌       | 1729/6717 [05:53<16:48,  4.95it/s]

Processing tickers:  26%|██▌       | 1730/6717 [05:53<17:00,  4.89it/s]

Processing tickers:  26%|██▌       | 1731/6717 [05:53<17:01,  4.88it/s]

Processing tickers:  26%|██▌       | 1732/6717 [05:53<17:03,  4.87it/s]

Processing tickers:  26%|██▌       | 1733/6717 [05:54<16:53,  4.92it/s]

Processing tickers:  26%|██▌       | 1734/6717 [05:54<16:52,  4.92it/s]

Processing tickers:  26%|██▌       | 1735/6717 [05:54<16:51,  4.93it/s]

Processing tickers:  26%|██▌       | 1736/6717 [05:54<16:56,  4.90it/s]

Processing tickers:  26%|██▌       | 1737/6717 [05:54<16:54,  4.91it/s]

Processing tickers:  26%|██▌       | 1738/6717 [05:55<17:05,  4.86it/s]

Processing tickers:  26%|██▌       | 1739/6717 [05:55<16:53,  4.91it/s]

Processing tickers:  26%|██▌       | 1740/6717 [05:55<16:46,  4.94it/s]

Processing tickers:  26%|██▌       | 1741/6717 [05:55<17:04,  4.86it/s]

Processing tickers:  26%|██▌       | 1742/6717 [05:55<16:58,  4.89it/s]

Processing tickers:  26%|██▌       | 1743/6717 [05:56<16:54,  4.91it/s]

Processing tickers:  26%|██▌       | 1744/6717 [05:56<17:10,  4.83it/s]

Processing tickers:  26%|██▌       | 1745/6717 [05:56<17:00,  4.87it/s]

Processing tickers:  26%|██▌       | 1746/6717 [05:56<17:13,  4.81it/s]

Processing tickers:  26%|██▌       | 1747/6717 [05:56<17:05,  4.85it/s]

Processing tickers:  26%|██▌       | 1748/6717 [05:57<16:56,  4.89it/s]

Processing tickers:  26%|██▌       | 1749/6717 [05:57<16:44,  4.95it/s]

Processing tickers:  26%|██▌       | 1750/6717 [05:57<16:41,  4.96it/s]

Processing tickers:  26%|██▌       | 1751/6717 [05:57<16:40,  4.96it/s]

Processing tickers:  26%|██▌       | 1752/6717 [05:57<16:43,  4.95it/s]

Processing tickers:  26%|██▌       | 1753/6717 [05:58<16:43,  4.95it/s]

Processing tickers:  26%|██▌       | 1754/6717 [05:58<16:39,  4.97it/s]

Processing tickers:  26%|██▌       | 1755/6717 [05:58<16:31,  5.01it/s]

Processing tickers:  26%|██▌       | 1756/6717 [05:58<16:38,  4.97it/s]

Processing tickers:  26%|██▌       | 1757/6717 [05:59<16:39,  4.96it/s]

Processing tickers:  26%|██▌       | 1758/6717 [05:59<16:40,  4.96it/s]

Processing tickers:  26%|██▌       | 1759/6717 [05:59<16:53,  4.89it/s]

Processing tickers:  26%|██▌       | 1760/6717 [05:59<16:43,  4.94it/s]

Processing tickers:  26%|██▌       | 1761/6717 [05:59<16:51,  4.90it/s]

Processing tickers:  26%|██▌       | 1762/6717 [06:00<16:46,  4.92it/s]

Processing tickers:  26%|██▌       | 1763/6717 [06:00<16:39,  4.95it/s]

Processing tickers:  26%|██▋       | 1764/6717 [06:00<16:40,  4.95it/s]

Processing tickers:  26%|██▋       | 1765/6717 [06:00<16:35,  4.97it/s]

Processing tickers:  26%|██▋       | 1766/6717 [06:00<16:36,  4.97it/s]

Processing tickers:  26%|██▋       | 1767/6717 [06:01<16:33,  4.98it/s]

Processing tickers:  26%|██▋       | 1768/6717 [06:01<16:44,  4.93it/s]

Processing tickers:  26%|██▋       | 1769/6717 [06:01<17:05,  4.83it/s]

Processing tickers:  26%|██▋       | 1770/6717 [06:01<16:57,  4.86it/s]

Processing tickers:  26%|██▋       | 1771/6717 [06:01<16:51,  4.89it/s]

Processing tickers:  26%|██▋       | 1772/6717 [06:02<16:48,  4.90it/s]

Processing tickers:  26%|██▋       | 1773/6717 [06:02<16:50,  4.89it/s]

Processing tickers:  26%|██▋       | 1774/6717 [06:02<16:45,  4.92it/s]

Processing tickers:  26%|██▋       | 1775/6717 [06:02<16:38,  4.95it/s]

Processing tickers:  26%|██▋       | 1776/6717 [06:02<16:54,  4.87it/s]

Processing tickers:  26%|██▋       | 1777/6717 [06:03<16:58,  4.85it/s]

Processing tickers:  26%|██▋       | 1778/6717 [06:03<16:46,  4.91it/s]

Processing tickers:  26%|██▋       | 1779/6717 [06:03<16:52,  4.88it/s]

Processing tickers:  26%|██▋       | 1780/6717 [06:03<16:48,  4.90it/s]

Processing tickers:  27%|██▋       | 1781/6717 [06:03<17:02,  4.83it/s]

Processing tickers:  27%|██▋       | 1782/6717 [06:04<16:58,  4.85it/s]

Processing tickers:  27%|██▋       | 1783/6717 [06:04<17:00,  4.83it/s]

Processing tickers:  27%|██▋       | 1784/6717 [06:04<17:06,  4.81it/s]

Processing tickers:  27%|██▋       | 1785/6717 [06:04<16:58,  4.84it/s]

Processing tickers:  27%|██▋       | 1786/6717 [06:04<16:55,  4.86it/s]

Processing tickers:  27%|██▋       | 1787/6717 [06:05<16:54,  4.86it/s]

Processing tickers:  27%|██▋       | 1788/6717 [06:05<16:44,  4.91it/s]

Processing tickers:  27%|██▋       | 1789/6717 [06:05<16:44,  4.90it/s]

Processing tickers:  27%|██▋       | 1790/6717 [06:05<16:37,  4.94it/s]

Processing tickers:  27%|██▋       | 1791/6717 [06:05<16:33,  4.96it/s]

Processing tickers:  27%|██▋       | 1792/6717 [06:06<16:33,  4.96it/s]

Processing tickers:  27%|██▋       | 1793/6717 [06:06<17:06,  4.79it/s]

Processing tickers:  27%|██▋       | 1794/6717 [06:06<16:57,  4.84it/s]

Processing tickers:  27%|██▋       | 1795/6717 [06:06<16:46,  4.89it/s]

Processing tickers:  27%|██▋       | 1796/6717 [06:06<16:46,  4.89it/s]

Processing tickers:  27%|██▋       | 1797/6717 [06:07<16:40,  4.92it/s]

Processing tickers:  27%|██▋       | 1798/6717 [06:07<16:41,  4.91it/s]

Processing tickers:  27%|██▋       | 1799/6717 [06:07<16:54,  4.85it/s]

Processing tickers:  27%|██▋       | 1800/6717 [06:07<16:54,  4.85it/s]

Processing tickers:  27%|██▋       | 1801/6717 [06:08<16:45,  4.89it/s]

Processing tickers:  27%|██▋       | 1802/6717 [06:08<16:37,  4.93it/s]

Processing tickers:  27%|██▋       | 1803/6717 [06:08<16:42,  4.90it/s]

Processing tickers:  27%|██▋       | 1804/6717 [06:08<16:37,  4.93it/s]

Processing tickers:  27%|██▋       | 1805/6717 [06:08<16:30,  4.96it/s]

Processing tickers:  27%|██▋       | 1806/6717 [06:09<16:34,  4.94it/s]

Processing tickers:  27%|██▋       | 1807/6717 [06:09<16:35,  4.93it/s]

Processing tickers:  27%|██▋       | 1808/6717 [06:09<16:32,  4.95it/s]

Processing tickers:  27%|██▋       | 1809/6717 [06:09<16:28,  4.96it/s]

Processing tickers:  27%|██▋       | 1810/6717 [06:09<16:33,  4.94it/s]

Processing tickers:  27%|██▋       | 1811/6717 [06:10<16:30,  4.95it/s]

Processing tickers:  27%|██▋       | 1812/6717 [06:10<16:29,  4.96it/s]

Processing tickers:  27%|██▋       | 1813/6717 [06:10<16:30,  4.95it/s]

Processing tickers:  27%|██▋       | 1814/6717 [06:10<16:35,  4.93it/s]

Processing tickers:  27%|██▋       | 1815/6717 [06:10<16:29,  4.95it/s]

Processing tickers:  27%|██▋       | 1816/6717 [06:11<16:22,  4.99it/s]

Processing tickers:  27%|██▋       | 1817/6717 [06:11<16:25,  4.97it/s]

Processing tickers:  27%|██▋       | 1818/6717 [06:11<16:21,  4.99it/s]

Processing tickers:  27%|██▋       | 1819/6717 [06:11<16:20,  4.99it/s]

Processing tickers:  27%|██▋       | 1820/6717 [06:11<16:20,  4.99it/s]

Processing tickers:  27%|██▋       | 1821/6717 [06:12<16:30,  4.94it/s]

Processing tickers:  27%|██▋       | 1822/6717 [06:12<16:31,  4.94it/s]

Processing tickers:  27%|██▋       | 1823/6717 [06:12<16:28,  4.95it/s]

Processing tickers:  27%|██▋       | 1824/6717 [06:12<16:28,  4.95it/s]

Processing tickers:  27%|██▋       | 1825/6717 [06:12<16:26,  4.96it/s]

Processing tickers:  27%|██▋       | 1826/6717 [06:13<16:23,  4.97it/s]

Processing tickers:  27%|██▋       | 1827/6717 [06:13<16:33,  4.92it/s]

Processing tickers:  27%|██▋       | 1828/6717 [06:13<16:31,  4.93it/s]

Processing tickers:  27%|██▋       | 1829/6717 [06:13<16:29,  4.94it/s]

Processing tickers:  27%|██▋       | 1830/6717 [06:13<16:30,  4.93it/s]

Processing tickers:  27%|██▋       | 1831/6717 [06:14<16:52,  4.82it/s]

Processing tickers:  27%|██▋       | 1832/6717 [06:14<16:41,  4.88it/s]

Processing tickers:  27%|██▋       | 1833/6717 [06:14<16:32,  4.92it/s]

Processing tickers:  27%|██▋       | 1834/6717 [06:14<16:38,  4.89it/s]

Processing tickers:  27%|██▋       | 1835/6717 [06:14<16:36,  4.90it/s]

Processing tickers:  27%|██▋       | 1836/6717 [06:15<16:32,  4.92it/s]

Processing tickers:  27%|██▋       | 1837/6717 [06:15<16:25,  4.95it/s]

Processing tickers:  27%|██▋       | 1838/6717 [06:15<16:43,  4.86it/s]

Processing tickers:  27%|██▋       | 1839/6717 [06:15<16:33,  4.91it/s]

Processing tickers:  27%|██▋       | 1840/6717 [06:15<16:34,  4.90it/s]

Processing tickers:  27%|██▋       | 1841/6717 [06:16<16:51,  4.82it/s]

Processing tickers:  27%|██▋       | 1842/6717 [06:16<16:36,  4.89it/s]

Processing tickers:  27%|██▋       | 1843/6717 [06:16<16:43,  4.85it/s]

Processing tickers:  27%|██▋       | 1844/6717 [06:16<16:44,  4.85it/s]

Processing tickers:  27%|██▋       | 1845/6717 [06:16<16:30,  4.92it/s]

Processing tickers:  27%|██▋       | 1846/6717 [06:17<16:27,  4.93it/s]

Processing tickers:  27%|██▋       | 1847/6717 [06:17<16:21,  4.96it/s]

Processing tickers:  28%|██▊       | 1848/6717 [06:17<16:25,  4.94it/s]

Processing tickers:  28%|██▊       | 1849/6717 [06:17<16:23,  4.95it/s]

Processing tickers:  28%|██▊       | 1850/6717 [06:17<16:15,  4.99it/s]

Processing tickers:  28%|██▊       | 1851/6717 [06:18<16:15,  4.99it/s]

Processing tickers:  28%|██▊       | 1852/6717 [06:18<16:16,  4.98it/s]

Processing tickers:  28%|██▊       | 1853/6717 [06:18<16:12,  5.00it/s]

Processing tickers:  28%|██▊       | 1854/6717 [06:18<16:13,  4.99it/s]

Processing tickers:  28%|██▊       | 1855/6717 [06:18<16:17,  4.98it/s]

Processing tickers:  28%|██▊       | 1856/6717 [06:19<16:19,  4.96it/s]

Processing tickers:  28%|██▊       | 1857/6717 [06:19<16:16,  4.97it/s]

Processing tickers:  28%|██▊       | 1858/6717 [06:19<16:13,  4.99it/s]

Processing tickers:  28%|██▊       | 1859/6717 [06:19<16:20,  4.95it/s]

Processing tickers:  28%|██▊       | 1860/6717 [06:19<16:19,  4.96it/s]

Processing tickers:  28%|██▊       | 1861/6717 [06:20<16:19,  4.96it/s]

Processing tickers:  28%|██▊       | 1862/6717 [06:20<16:17,  4.97it/s]

Processing tickers:  28%|██▊       | 1863/6717 [06:20<16:44,  4.83it/s]

Processing tickers:  28%|██▊       | 1864/6717 [06:20<16:37,  4.86it/s]

Processing tickers:  28%|██▊       | 1865/6717 [06:20<16:30,  4.90it/s]

Processing tickers:  28%|██▊       | 1866/6717 [06:21<16:26,  4.91it/s]

Processing tickers:  28%|██▊       | 1867/6717 [06:21<16:21,  4.94it/s]

Processing tickers:  28%|██▊       | 1868/6717 [06:21<16:19,  4.95it/s]

Processing tickers:  28%|██▊       | 1869/6717 [06:21<16:25,  4.92it/s]

Processing tickers:  28%|██▊       | 1870/6717 [06:21<16:24,  4.92it/s]

Processing tickers:  28%|██▊       | 1871/6717 [06:22<16:30,  4.89it/s]

Processing tickers:  28%|██▊       | 1872/6717 [06:22<16:28,  4.90it/s]

Processing tickers:  28%|██▊       | 1873/6717 [06:22<16:22,  4.93it/s]

Processing tickers:  28%|██▊       | 1874/6717 [06:22<16:22,  4.93it/s]

Processing tickers:  28%|██▊       | 1875/6717 [06:23<16:42,  4.83it/s]

Processing tickers:  28%|██▊       | 1876/6717 [06:23<16:34,  4.87it/s]

Processing tickers:  28%|██▊       | 1877/6717 [06:23<16:34,  4.87it/s]

Processing tickers:  28%|██▊       | 1878/6717 [06:23<16:28,  4.90it/s]

Processing tickers:  28%|██▊       | 1879/6717 [06:23<16:51,  4.78it/s]

Processing tickers:  28%|██▊       | 1880/6717 [06:24<16:37,  4.85it/s]

Processing tickers:  28%|██▊       | 1881/6717 [06:24<16:29,  4.88it/s]

Processing tickers:  28%|██▊       | 1882/6717 [06:24<16:30,  4.88it/s]

Processing tickers:  28%|██▊       | 1883/6717 [06:24<16:32,  4.87it/s]

Processing tickers:  28%|██▊       | 1884/6717 [06:24<16:27,  4.89it/s]

Processing tickers:  28%|██▊       | 1885/6717 [06:25<16:20,  4.93it/s]

Processing tickers:  28%|██▊       | 1886/6717 [06:25<16:30,  4.88it/s]

Processing tickers:  28%|██▊       | 1887/6717 [06:25<16:19,  4.93it/s]

Processing tickers:  28%|██▊       | 1888/6717 [06:25<16:20,  4.93it/s]

Processing tickers:  28%|██▊       | 1889/6717 [06:25<16:21,  4.92it/s]

Processing tickers:  28%|██▊       | 1890/6717 [06:26<16:38,  4.84it/s]

Processing tickers:  28%|██▊       | 1891/6717 [06:26<16:27,  4.89it/s]

Processing tickers:  28%|██▊       | 1892/6717 [06:26<16:40,  4.82it/s]

Processing tickers:  28%|██▊       | 1893/6717 [06:26<16:39,  4.82it/s]

Processing tickers:  28%|██▊       | 1894/6717 [06:26<16:34,  4.85it/s]

Processing tickers:  28%|██▊       | 1895/6717 [06:27<16:37,  4.84it/s]

Processing tickers:  28%|██▊       | 1896/6717 [06:27<16:30,  4.87it/s]

Processing tickers:  28%|██▊       | 1897/6717 [06:27<16:33,  4.85it/s]

Processing tickers:  28%|██▊       | 1898/6717 [06:27<16:29,  4.87it/s]

Processing tickers:  28%|██▊       | 1899/6717 [06:27<16:22,  4.90it/s]

Processing tickers:  28%|██▊       | 1900/6717 [06:28<16:24,  4.89it/s]

Processing tickers:  28%|██▊       | 1901/6717 [06:28<16:19,  4.91it/s]

Processing tickers:  28%|██▊       | 1902/6717 [06:28<16:21,  4.91it/s]

Processing tickers:  28%|██▊       | 1903/6717 [06:28<16:16,  4.93it/s]

Processing tickers:  28%|██▊       | 1904/6717 [06:28<16:24,  4.89it/s]

Processing tickers:  28%|██▊       | 1905/6717 [06:29<16:21,  4.90it/s]

Processing tickers:  28%|██▊       | 1906/6717 [06:29<16:16,  4.92it/s]

Processing tickers:  28%|██▊       | 1907/6717 [06:29<16:16,  4.92it/s]

Processing tickers:  28%|██▊       | 1908/6717 [06:29<16:19,  4.91it/s]

Processing tickers:  28%|██▊       | 1909/6717 [06:29<16:11,  4.95it/s]

Processing tickers:  28%|██▊       | 1910/6717 [06:30<16:36,  4.82it/s]

Processing tickers:  28%|██▊       | 1911/6717 [06:30<16:30,  4.85it/s]

Processing tickers:  28%|██▊       | 1912/6717 [06:30<16:27,  4.87it/s]

Processing tickers:  28%|██▊       | 1913/6717 [06:30<16:26,  4.87it/s]

Processing tickers:  28%|██▊       | 1914/6717 [06:30<16:13,  4.93it/s]

Processing tickers:  29%|██▊       | 1915/6717 [06:31<16:09,  4.95it/s]

Processing tickers:  29%|██▊       | 1916/6717 [06:31<16:08,  4.96it/s]

Processing tickers:  29%|██▊       | 1917/6717 [06:31<16:09,  4.95it/s]

Processing tickers:  29%|██▊       | 1918/6717 [06:31<16:06,  4.96it/s]

Processing tickers:  29%|██▊       | 1919/6717 [06:31<16:08,  4.96it/s]

Processing tickers:  29%|██▊       | 1920/6717 [06:32<16:05,  4.97it/s]

Processing tickers:  29%|██▊       | 1921/6717 [06:32<16:01,  4.99it/s]

Processing tickers:  29%|██▊       | 1922/6717 [06:32<16:13,  4.92it/s]

Processing tickers:  29%|██▊       | 1923/6717 [06:32<16:10,  4.94it/s]

Processing tickers:  29%|██▊       | 1924/6717 [06:33<16:07,  4.95it/s]

Processing tickers:  29%|██▊       | 1925/6717 [06:33<16:07,  4.95it/s]

Processing tickers:  29%|██▊       | 1926/6717 [06:33<16:17,  4.90it/s]

Processing tickers:  29%|██▊       | 1927/6717 [06:33<16:29,  4.84it/s]

Processing tickers:  29%|██▊       | 1928/6717 [06:33<16:25,  4.86it/s]

Processing tickers:  29%|██▊       | 1929/6717 [06:34<16:18,  4.89it/s]

Processing tickers:  29%|██▊       | 1930/6717 [06:34<16:11,  4.93it/s]

Processing tickers:  29%|██▊       | 1931/6717 [06:34<16:14,  4.91it/s]

Processing tickers:  29%|██▉       | 1932/6717 [06:34<16:14,  4.91it/s]

Processing tickers:  29%|██▉       | 1933/6717 [06:34<16:11,  4.92it/s]

Processing tickers:  29%|██▉       | 1934/6717 [06:35<16:10,  4.93it/s]

Processing tickers:  29%|██▉       | 1935/6717 [06:35<16:10,  4.93it/s]

Processing tickers:  29%|██▉       | 1936/6717 [06:35<16:10,  4.93it/s]

Processing tickers:  29%|██▉       | 1937/6717 [06:35<16:18,  4.89it/s]

Processing tickers:  29%|██▉       | 1938/6717 [06:35<16:17,  4.89it/s]

Processing tickers:  29%|██▉       | 1939/6717 [06:36<16:11,  4.92it/s]

Processing tickers:  29%|██▉       | 1940/6717 [06:36<16:12,  4.91it/s]

Processing tickers:  29%|██▉       | 1941/6717 [06:36<16:13,  4.90it/s]

Processing tickers:  29%|██▉       | 1942/6717 [06:36<16:09,  4.93it/s]

Processing tickers:  29%|██▉       | 1943/6717 [06:36<16:16,  4.89it/s]

Processing tickers:  29%|██▉       | 1944/6717 [06:37<16:08,  4.93it/s]

Processing tickers:  29%|██▉       | 1945/6717 [06:37<16:07,  4.93it/s]

Processing tickers:  29%|██▉       | 1946/6717 [06:37<16:22,  4.86it/s]

Processing tickers:  29%|██▉       | 1947/6717 [06:37<16:19,  4.87it/s]

Processing tickers:  29%|██▉       | 1948/6717 [06:37<16:10,  4.91it/s]

Processing tickers:  29%|██▉       | 1949/6717 [06:38<16:10,  4.91it/s]

Processing tickers:  29%|██▉       | 1950/6717 [06:38<16:07,  4.93it/s]

Processing tickers:  29%|██▉       | 1951/6717 [06:38<16:35,  4.79it/s]

Processing tickers:  29%|██▉       | 1952/6717 [06:38<16:35,  4.79it/s]

Processing tickers:  29%|██▉       | 1953/6717 [06:38<16:22,  4.85it/s]

Processing tickers:  29%|██▉       | 1954/6717 [06:39<16:21,  4.85it/s]

Processing tickers:  29%|██▉       | 1955/6717 [06:39<16:13,  4.89it/s]

Processing tickers:  29%|██▉       | 1956/6717 [06:39<16:04,  4.94it/s]

Processing tickers:  29%|██▉       | 1957/6717 [06:39<16:05,  4.93it/s]

Processing tickers:  29%|██▉       | 1958/6717 [06:39<16:10,  4.90it/s]

Processing tickers:  29%|██▉       | 1959/6717 [06:40<16:08,  4.91it/s]

Processing tickers:  29%|██▉       | 1960/6717 [06:40<16:05,  4.93it/s]

Processing tickers:  29%|██▉       | 1961/6717 [06:40<16:04,  4.93it/s]

Processing tickers:  29%|██▉       | 1962/6717 [06:40<16:00,  4.95it/s]

Processing tickers:  29%|██▉       | 1963/6717 [06:40<16:11,  4.89it/s]

Processing tickers:  29%|██▉       | 1964/6717 [06:41<16:07,  4.91it/s]

Processing tickers:  29%|██▉       | 1965/6717 [06:41<16:07,  4.91it/s]

Processing tickers:  29%|██▉       | 1966/6717 [06:41<16:01,  4.94it/s]

Processing tickers:  29%|██▉       | 1967/6717 [06:41<15:57,  4.96it/s]

Processing tickers:  29%|██▉       | 1968/6717 [06:41<16:14,  4.87it/s]

Processing tickers:  29%|██▉       | 1969/6717 [06:42<16:11,  4.89it/s]

Processing tickers:  29%|██▉       | 1970/6717 [06:42<16:21,  4.84it/s]

Processing tickers:  29%|██▉       | 1971/6717 [06:42<16:13,  4.87it/s]

Processing tickers:  29%|██▉       | 1972/6717 [06:42<16:15,  4.86it/s]

Processing tickers:  29%|██▉       | 1973/6717 [06:43<16:07,  4.90it/s]

Processing tickers:  29%|██▉       | 1974/6717 [06:43<16:05,  4.91it/s]

Processing tickers:  29%|██▉       | 1975/6717 [06:43<16:00,  4.94it/s]

Processing tickers:  29%|██▉       | 1976/6717 [06:43<16:02,  4.92it/s]

Processing tickers:  29%|██▉       | 1977/6717 [06:43<15:58,  4.94it/s]

Processing tickers:  29%|██▉       | 1978/6717 [06:44<15:54,  4.96it/s]

Processing tickers:  29%|██▉       | 1979/6717 [06:44<16:05,  4.91it/s]

Processing tickers:  29%|██▉       | 1980/6717 [06:44<16:05,  4.91it/s]

Processing tickers:  29%|██▉       | 1981/6717 [06:44<16:04,  4.91it/s]

Processing tickers:  30%|██▉       | 1982/6717 [06:44<15:59,  4.94it/s]

Processing tickers:  30%|██▉       | 1983/6717 [06:45<16:09,  4.89it/s]

Processing tickers:  30%|██▉       | 1984/6717 [06:45<16:05,  4.90it/s]

Processing tickers:  30%|██▉       | 1985/6717 [06:45<15:58,  4.94it/s]

Processing tickers:  30%|██▉       | 1986/6717 [06:45<15:55,  4.95it/s]

Processing tickers:  30%|██▉       | 1987/6717 [06:45<15:57,  4.94it/s]

Processing tickers:  30%|██▉       | 1988/6717 [06:46<15:55,  4.95it/s]

Processing tickers:  30%|██▉       | 1989/6717 [06:46<16:15,  4.85it/s]

Processing tickers:  30%|██▉       | 1990/6717 [06:46<16:10,  4.87it/s]

Processing tickers:  30%|██▉       | 1991/6717 [06:46<16:03,  4.90it/s]

Processing tickers:  30%|██▉       | 1992/6717 [06:46<15:57,  4.93it/s]

Processing tickers:  30%|██▉       | 1993/6717 [06:47<15:56,  4.94it/s]

Processing tickers:  30%|██▉       | 1994/6717 [06:47<15:55,  4.94it/s]

Processing tickers:  30%|██▉       | 1995/6717 [06:47<16:35,  4.74it/s]

Processing tickers:  30%|██▉       | 1996/6717 [06:47<16:20,  4.81it/s]

Processing tickers:  30%|██▉       | 1997/6717 [06:47<16:16,  4.83it/s]

Processing tickers:  30%|██▉       | 1998/6717 [06:48<16:07,  4.88it/s]

Processing tickers:  30%|██▉       | 1999/6717 [06:48<15:58,  4.92it/s]

Processing tickers:  30%|██▉       | 2000/6717 [06:48<16:14,  4.84it/s]

Processing tickers:  30%|██▉       | 2001/6717 [06:48<16:06,  4.88it/s]

Processing tickers:  30%|██▉       | 2002/6717 [06:48<16:00,  4.91it/s]

Processing tickers:  30%|██▉       | 2003/6717 [06:49<15:59,  4.91it/s]

Processing tickers:  30%|██▉       | 2004/6717 [06:49<15:57,  4.92it/s]

Processing tickers:  30%|██▉       | 2005/6717 [06:49<15:56,  4.93it/s]

Processing tickers:  30%|██▉       | 2006/6717 [06:49<16:17,  4.82it/s]

Processing tickers:  30%|██▉       | 2007/6717 [06:49<16:08,  4.86it/s]

Processing tickers:  30%|██▉       | 2008/6717 [06:50<15:59,  4.91it/s]

Processing tickers:  30%|██▉       | 2009/6717 [06:50<15:58,  4.91it/s]

Processing tickers:  30%|██▉       | 2010/6717 [06:50<15:55,  4.93it/s]

Processing tickers:  30%|██▉       | 2011/6717 [06:50<15:51,  4.95it/s]

Processing tickers:  30%|██▉       | 2012/6717 [06:50<15:51,  4.95it/s]

Processing tickers:  30%|██▉       | 2013/6717 [06:51<15:47,  4.96it/s]

Processing tickers:  30%|██▉       | 2014/6717 [06:51<15:49,  4.96it/s]

Processing tickers:  30%|██▉       | 2015/6717 [06:51<15:49,  4.95it/s]

Processing tickers:  30%|███       | 2016/6717 [06:51<15:54,  4.93it/s]

Processing tickers:  30%|███       | 2017/6717 [06:51<15:58,  4.90it/s]

Processing tickers:  30%|███       | 2018/6717 [06:52<15:57,  4.91it/s]

Processing tickers:  30%|███       | 2019/6717 [06:52<15:53,  4.93it/s]

Processing tickers:  30%|███       | 2020/6717 [06:52<15:50,  4.94it/s]

Processing tickers:  30%|███       | 2021/6717 [06:52<15:49,  4.95it/s]

Processing tickers:  30%|███       | 2022/6717 [06:52<15:49,  4.95it/s]

Processing tickers:  30%|███       | 2023/6717 [06:53<15:48,  4.95it/s]

Processing tickers:  30%|███       | 2024/6717 [06:53<15:43,  4.98it/s]

Processing tickers:  30%|███       | 2025/6717 [06:53<15:44,  4.97it/s]

Processing tickers:  30%|███       | 2026/6717 [06:53<15:51,  4.93it/s]

Processing tickers:  30%|███       | 2027/6717 [06:53<15:45,  4.96it/s]

Processing tickers:  30%|███       | 2028/6717 [06:54<15:43,  4.97it/s]

Processing tickers:  30%|███       | 2029/6717 [06:54<15:44,  4.96it/s]

Processing tickers:  30%|███       | 2030/6717 [06:54<15:47,  4.94it/s]

Processing tickers:  30%|███       | 2031/6717 [06:54<15:59,  4.89it/s]

Processing tickers:  30%|███       | 2032/6717 [06:55<15:55,  4.90it/s]

Processing tickers:  30%|███       | 2033/6717 [06:55<15:51,  4.92it/s]

Processing tickers:  30%|███       | 2034/6717 [06:55<16:04,  4.85it/s]

Processing tickers:  30%|███       | 2035/6717 [06:55<15:58,  4.88it/s]

Processing tickers:  30%|███       | 2036/6717 [06:55<15:55,  4.90it/s]

Processing tickers:  30%|███       | 2037/6717 [06:56<15:51,  4.92it/s]

Processing tickers:  30%|███       | 2038/6717 [06:56<15:44,  4.96it/s]

Processing tickers:  30%|███       | 2039/6717 [06:56<15:40,  4.97it/s]

Processing tickers:  30%|███       | 2040/6717 [06:56<15:47,  4.94it/s]

Processing tickers:  30%|███       | 2041/6717 [06:56<15:42,  4.96it/s]

Processing tickers:  30%|███       | 2042/6717 [06:57<15:46,  4.94it/s]

Processing tickers:  30%|███       | 2043/6717 [06:57<15:50,  4.92it/s]

Processing tickers:  30%|███       | 2044/6717 [06:57<16:12,  4.80it/s]

Processing tickers:  30%|███       | 2045/6717 [06:57<16:15,  4.79it/s]

Processing tickers:  30%|███       | 2046/6717 [06:57<16:03,  4.85it/s]

Processing tickers:  30%|███       | 2047/6717 [06:58<15:59,  4.87it/s]

Processing tickers:  30%|███       | 2048/6717 [06:58<15:48,  4.92it/s]

Processing tickers:  31%|███       | 2049/6717 [06:58<15:46,  4.93it/s]

Processing tickers:  31%|███       | 2050/6717 [06:58<15:46,  4.93it/s]

Processing tickers:  31%|███       | 2051/6717 [06:58<15:49,  4.91it/s]

Processing tickers:  31%|███       | 2052/6717 [06:59<15:44,  4.94it/s]

Processing tickers:  31%|███       | 2053/6717 [06:59<15:45,  4.93it/s]

Processing tickers:  31%|███       | 2054/6717 [06:59<15:52,  4.90it/s]

Processing tickers:  31%|███       | 2055/6717 [06:59<16:02,  4.84it/s]

Processing tickers:  31%|███       | 2056/6717 [06:59<16:14,  4.79it/s]

Processing tickers:  31%|███       | 2057/6717 [07:00<16:01,  4.85it/s]

Processing tickers:  31%|███       | 2058/6717 [07:00<15:58,  4.86it/s]

Processing tickers:  31%|███       | 2059/6717 [07:00<15:57,  4.87it/s]

Processing tickers:  31%|███       | 2060/6717 [07:00<15:52,  4.89it/s]

Processing tickers:  31%|███       | 2061/6717 [07:00<16:07,  4.81it/s]

Processing tickers:  31%|███       | 2062/6717 [07:01<16:11,  4.79it/s]

Processing tickers:  31%|███       | 2063/6717 [07:01<15:57,  4.86it/s]

Processing tickers:  31%|███       | 2064/6717 [07:01<15:53,  4.88it/s]

Processing tickers:  31%|███       | 2065/6717 [07:01<15:45,  4.92it/s]

Processing tickers:  31%|███       | 2066/6717 [07:01<15:40,  4.94it/s]

Processing tickers:  31%|███       | 2067/6717 [07:02<15:39,  4.95it/s]

Processing tickers:  31%|███       | 2068/6717 [07:02<17:21,  4.46it/s]

Processing tickers:  31%|███       | 2069/6717 [07:02<16:48,  4.61it/s]

Processing tickers:  31%|███       | 2070/6717 [07:02<16:31,  4.69it/s]

Processing tickers:  31%|███       | 2071/6717 [07:03<16:26,  4.71it/s]

Processing tickers:  31%|███       | 2072/6717 [07:03<16:10,  4.79it/s]

Processing tickers:  31%|███       | 2073/6717 [07:03<16:22,  4.73it/s]

Processing tickers:  31%|███       | 2074/6717 [07:03<16:05,  4.81it/s]

Processing tickers:  31%|███       | 2075/6717 [07:03<15:52,  4.87it/s]

Processing tickers:  31%|███       | 2076/6717 [07:04<15:48,  4.89it/s]

Processing tickers:  31%|███       | 2077/6717 [07:04<15:49,  4.89it/s]

Processing tickers:  31%|███       | 2078/6717 [07:04<15:45,  4.90it/s]

Processing tickers:  31%|███       | 2079/6717 [07:04<15:41,  4.93it/s]

Processing tickers:  31%|███       | 2080/6717 [07:04<15:35,  4.96it/s]

Processing tickers:  31%|███       | 2081/6717 [07:05<15:31,  4.98it/s]

Processing tickers:  31%|███       | 2082/6717 [07:05<15:34,  4.96it/s]

Processing tickers:  31%|███       | 2083/6717 [07:05<15:49,  4.88it/s]

Processing tickers:  31%|███       | 2084/6717 [07:05<15:40,  4.92it/s]

Processing tickers:  31%|███       | 2085/6717 [07:05<15:47,  4.89it/s]

Processing tickers:  31%|███       | 2086/6717 [07:06<15:46,  4.89it/s]

Processing tickers:  31%|███       | 2087/6717 [07:06<15:51,  4.86it/s]

Processing tickers:  31%|███       | 2088/6717 [07:06<15:47,  4.89it/s]

Processing tickers:  31%|███       | 2089/6717 [07:06<15:53,  4.85it/s]

Processing tickers:  31%|███       | 2090/6717 [07:06<15:50,  4.87it/s]

Processing tickers:  31%|███       | 2091/6717 [07:07<15:43,  4.91it/s]

Processing tickers:  31%|███       | 2092/6717 [07:07<15:43,  4.90it/s]

Processing tickers:  31%|███       | 2093/6717 [07:07<15:41,  4.91it/s]

Processing tickers:  31%|███       | 2094/6717 [07:07<15:41,  4.91it/s]

Processing tickers:  31%|███       | 2095/6717 [07:07<15:37,  4.93it/s]

Processing tickers:  31%|███       | 2096/6717 [07:08<15:36,  4.93it/s]

Processing tickers:  31%|███       | 2097/6717 [07:08<15:38,  4.92it/s]

Processing tickers:  31%|███       | 2098/6717 [07:08<15:50,  4.86it/s]

Processing tickers:  31%|███       | 2099/6717 [07:08<15:47,  4.88it/s]

Processing tickers:  31%|███▏      | 2100/6717 [07:08<15:43,  4.90it/s]

Processing tickers:  31%|███▏      | 2101/6717 [07:09<15:40,  4.91it/s]

Processing tickers:  31%|███▏      | 2102/6717 [07:09<15:40,  4.91it/s]

Processing tickers:  31%|███▏      | 2103/6717 [07:09<16:10,  4.75it/s]

Processing tickers:  31%|███▏      | 2104/6717 [07:09<15:59,  4.81it/s]

Processing tickers:  31%|███▏      | 2105/6717 [07:10<15:56,  4.82it/s]

Processing tickers:  31%|███▏      | 2106/6717 [07:10<15:51,  4.85it/s]

Processing tickers:  31%|███▏      | 2107/6717 [07:10<15:43,  4.89it/s]

Processing tickers:  31%|███▏      | 2108/6717 [07:10<16:30,  4.65it/s]

Processing tickers:  31%|███▏      | 2109/6717 [07:10<16:23,  4.69it/s]

Processing tickers:  31%|███▏      | 2110/6717 [07:11<16:13,  4.73it/s]

Processing tickers:  31%|███▏      | 2111/6717 [07:11<16:05,  4.77it/s]

Processing tickers:  31%|███▏      | 2112/6717 [07:11<16:31,  4.64it/s]

Processing tickers:  31%|███▏      | 2113/6717 [07:11<16:34,  4.63it/s]

Processing tickers:  31%|███▏      | 2114/6717 [07:11<16:17,  4.71it/s]

Processing tickers:  31%|███▏      | 2115/6717 [07:12<15:59,  4.80it/s]

Processing tickers:  32%|███▏      | 2116/6717 [07:12<15:45,  4.87it/s]

Processing tickers:  32%|███▏      | 2117/6717 [07:12<15:50,  4.84it/s]

Processing tickers:  32%|███▏      | 2118/6717 [07:12<15:40,  4.89it/s]

Processing tickers:  32%|███▏      | 2119/6717 [07:12<15:36,  4.91it/s]

Processing tickers:  32%|███▏      | 2120/6717 [07:13<15:29,  4.95it/s]

Processing tickers:  32%|███▏      | 2121/6717 [07:13<15:32,  4.93it/s]

Processing tickers:  32%|███▏      | 2122/6717 [07:13<15:34,  4.92it/s]

Processing tickers:  32%|███▏      | 2123/6717 [07:13<15:40,  4.89it/s]

Processing tickers:  32%|███▏      | 2124/6717 [07:13<15:37,  4.90it/s]

Processing tickers:  32%|███▏      | 2125/6717 [07:14<15:41,  4.88it/s]

Processing tickers:  32%|███▏      | 2126/6717 [07:14<15:37,  4.90it/s]

Processing tickers:  32%|███▏      | 2127/6717 [07:14<15:44,  4.86it/s]

Processing tickers:  32%|███▏      | 2128/6717 [07:14<15:41,  4.88it/s]

Processing tickers:  32%|███▏      | 2129/6717 [07:14<15:42,  4.87it/s]

Processing tickers:  32%|███▏      | 2130/6717 [07:15<15:38,  4.89it/s]

Processing tickers:  32%|███▏      | 2131/6717 [07:15<15:37,  4.89it/s]

Processing tickers:  32%|███▏      | 2132/6717 [07:15<15:30,  4.93it/s]

Processing tickers:  32%|███▏      | 2133/6717 [07:15<15:31,  4.92it/s]

Processing tickers:  32%|███▏      | 2134/6717 [07:15<15:25,  4.95it/s]

Processing tickers:  32%|███▏      | 2135/6717 [07:16<15:27,  4.94it/s]

Processing tickers:  32%|███▏      | 2136/6717 [07:16<15:24,  4.95it/s]

Processing tickers:  32%|███▏      | 2137/6717 [07:16<15:24,  4.95it/s]

Processing tickers:  32%|███▏      | 2138/6717 [07:16<15:22,  4.96it/s]

Processing tickers:  32%|███▏      | 2139/6717 [07:16<15:21,  4.97it/s]

Processing tickers:  32%|███▏      | 2140/6717 [07:17<15:26,  4.94it/s]

Processing tickers:  32%|███▏      | 2141/6717 [07:17<15:23,  4.96it/s]

Processing tickers:  32%|███▏      | 2142/6717 [07:17<15:25,  4.94it/s]

Processing tickers:  32%|███▏      | 2143/6717 [07:17<15:31,  4.91it/s]

Processing tickers:  32%|███▏      | 2144/6717 [07:18<15:46,  4.83it/s]

Processing tickers:  32%|███▏      | 2145/6717 [07:18<15:35,  4.89it/s]

Processing tickers:  32%|███▏      | 2146/6717 [07:18<15:28,  4.92it/s]

Processing tickers:  32%|███▏      | 2147/6717 [07:18<15:28,  4.92it/s]

Processing tickers:  32%|███▏      | 2148/6717 [07:18<15:28,  4.92it/s]

Processing tickers:  32%|███▏      | 2149/6717 [07:19<15:28,  4.92it/s]

Processing tickers:  32%|███▏      | 2150/6717 [07:19<15:25,  4.94it/s]

Processing tickers:  32%|███▏      | 2151/6717 [07:19<15:26,  4.93it/s]

Processing tickers:  32%|███▏      | 2152/6717 [07:19<15:55,  4.78it/s]

Processing tickers:  32%|███▏      | 2153/6717 [07:19<15:46,  4.82it/s]

Processing tickers:  32%|███▏      | 2154/6717 [07:20<15:37,  4.87it/s]

Processing tickers:  32%|███▏      | 2155/6717 [07:20<15:34,  4.88it/s]

Processing tickers:  32%|███▏      | 2156/6717 [07:20<15:28,  4.91it/s]

Processing tickers:  32%|███▏      | 2157/6717 [07:20<15:24,  4.93it/s]

Processing tickers:  32%|███▏      | 2158/6717 [07:20<15:25,  4.93it/s]

Processing tickers:  32%|███▏      | 2159/6717 [07:21<15:25,  4.92it/s]

Processing tickers:  32%|███▏      | 2160/6717 [07:21<15:19,  4.96it/s]

Processing tickers:  32%|███▏      | 2161/6717 [07:21<15:29,  4.90it/s]

Processing tickers:  32%|███▏      | 2162/6717 [07:21<15:24,  4.93it/s]

Processing tickers:  32%|███▏      | 2163/6717 [07:21<15:30,  4.90it/s]

Processing tickers:  32%|███▏      | 2164/6717 [07:22<15:24,  4.92it/s]

Processing tickers:  32%|███▏      | 2165/6717 [07:22<15:20,  4.94it/s]

Processing tickers:  32%|███▏      | 2166/6717 [07:22<15:29,  4.90it/s]

Processing tickers:  32%|███▏      | 2167/6717 [07:22<15:28,  4.90it/s]

Processing tickers:  32%|███▏      | 2168/6717 [07:22<15:43,  4.82it/s]

Processing tickers:  32%|███▏      | 2169/6717 [07:23<15:37,  4.85it/s]

Processing tickers:  32%|███▏      | 2170/6717 [07:23<15:33,  4.87it/s]

Processing tickers:  32%|███▏      | 2171/6717 [07:23<15:34,  4.87it/s]

Processing tickers:  32%|███▏      | 2172/6717 [07:23<15:32,  4.88it/s]

Processing tickers:  32%|███▏      | 2173/6717 [07:23<15:29,  4.89it/s]

Processing tickers:  32%|███▏      | 2174/6717 [07:24<15:22,  4.93it/s]

Processing tickers:  32%|███▏      | 2175/6717 [07:24<15:34,  4.86it/s]

Processing tickers:  32%|███▏      | 2176/6717 [07:24<15:35,  4.85it/s]

Processing tickers:  32%|███▏      | 2177/6717 [07:24<15:38,  4.84it/s]

Processing tickers:  32%|███▏      | 2178/6717 [07:24<15:29,  4.88it/s]

Processing tickers:  32%|███▏      | 2179/6717 [07:25<15:27,  4.89it/s]

Processing tickers:  32%|███▏      | 2180/6717 [07:25<15:29,  4.88it/s]

Processing tickers:  32%|███▏      | 2181/6717 [07:25<15:22,  4.92it/s]

Processing tickers:  32%|███▏      | 2182/6717 [07:25<15:18,  4.94it/s]

Processing tickers:  32%|███▏      | 2183/6717 [07:25<15:16,  4.95it/s]

Processing tickers:  33%|███▎      | 2184/6717 [07:26<15:12,  4.97it/s]

Processing tickers:  33%|███▎      | 2185/6717 [07:26<15:16,  4.95it/s]

Processing tickers:  33%|███▎      | 2186/6717 [07:26<15:13,  4.96it/s]

Processing tickers:  33%|███▎      | 2187/6717 [07:26<15:15,  4.95it/s]

Processing tickers:  33%|███▎      | 2188/6717 [07:26<15:17,  4.94it/s]

Processing tickers:  33%|███▎      | 2189/6717 [07:27<15:12,  4.96it/s]

Processing tickers:  33%|███▎      | 2190/6717 [07:27<15:11,  4.97it/s]

Processing tickers:  33%|███▎      | 2191/6717 [07:27<15:13,  4.95it/s]

Processing tickers:  33%|███▎      | 2192/6717 [07:27<15:21,  4.91it/s]

Processing tickers:  33%|███▎      | 2193/6717 [07:28<15:18,  4.92it/s]

Processing tickers:  33%|███▎      | 2194/6717 [07:28<15:14,  4.94it/s]

Processing tickers:  33%|███▎      | 2195/6717 [07:28<15:11,  4.96it/s]

Processing tickers:  33%|███▎      | 2196/6717 [07:28<15:10,  4.96it/s]

Processing tickers:  33%|███▎      | 2197/6717 [07:28<15:14,  4.94it/s]

Processing tickers:  33%|███▎      | 2198/6717 [07:29<15:22,  4.90it/s]

Processing tickers:  33%|███▎      | 2199/6717 [07:29<15:21,  4.90it/s]

Processing tickers:  33%|███▎      | 2200/6717 [07:29<15:19,  4.92it/s]

Processing tickers:  33%|███▎      | 2201/6717 [07:29<15:40,  4.80it/s]

Processing tickers:  33%|███▎      | 2202/6717 [07:29<15:29,  4.86it/s]

Processing tickers:  33%|███▎      | 2203/6717 [07:30<15:37,  4.81it/s]

Processing tickers:  33%|███▎      | 2204/6717 [07:30<15:28,  4.86it/s]

Processing tickers:  33%|███▎      | 2205/6717 [07:30<15:17,  4.92it/s]

Processing tickers:  33%|███▎      | 2206/6717 [07:30<15:14,  4.93it/s]

Processing tickers:  33%|███▎      | 2207/6717 [07:30<15:26,  4.87it/s]

Processing tickers:  33%|███▎      | 2208/6717 [07:31<15:36,  4.81it/s]

Processing tickers:  33%|███▎      | 2209/6717 [07:31<15:32,  4.84it/s]

Processing tickers:  33%|███▎      | 2210/6717 [07:31<15:36,  4.81it/s]

Processing tickers:  33%|███▎      | 2211/6717 [07:31<15:30,  4.84it/s]

Processing tickers:  33%|███▎      | 2212/6717 [07:31<15:48,  4.75it/s]

Processing tickers:  33%|███▎      | 2213/6717 [07:32<15:35,  4.81it/s]

Processing tickers:  33%|███▎      | 2214/6717 [07:32<15:36,  4.81it/s]

Processing tickers:  33%|███▎      | 2215/6717 [07:32<15:28,  4.85it/s]

Processing tickers:  33%|███▎      | 2216/6717 [07:32<15:21,  4.88it/s]

Processing tickers:  33%|███▎      | 2217/6717 [07:32<15:28,  4.85it/s]

Processing tickers:  33%|███▎      | 2218/6717 [07:33<15:27,  4.85it/s]

Processing tickers:  33%|███▎      | 2219/6717 [07:33<15:29,  4.84it/s]

Processing tickers:  33%|███▎      | 2220/6717 [07:33<15:25,  4.86it/s]

Processing tickers:  33%|███▎      | 2221/6717 [07:33<15:28,  4.84it/s]

Processing tickers:  33%|███▎      | 2222/6717 [07:33<15:36,  4.80it/s]

Processing tickers:  33%|███▎      | 2223/6717 [07:34<15:25,  4.86it/s]

Processing tickers:  33%|███▎      | 2224/6717 [07:34<15:18,  4.89it/s]

Processing tickers:  33%|███▎      | 2225/6717 [07:34<15:16,  4.90it/s]

Processing tickers:  33%|███▎      | 2226/6717 [07:34<15:11,  4.93it/s]

Processing tickers:  33%|███▎      | 2227/6717 [07:34<15:11,  4.93it/s]

Processing tickers:  33%|███▎      | 2228/6717 [07:35<15:09,  4.94it/s]

Processing tickers:  33%|███▎      | 2229/6717 [07:35<15:08,  4.94it/s]

Processing tickers:  33%|███▎      | 2230/6717 [07:35<15:07,  4.94it/s]

Processing tickers:  33%|███▎      | 2231/6717 [07:35<15:08,  4.94it/s]

Processing tickers:  33%|███▎      | 2232/6717 [07:36<15:19,  4.88it/s]

Processing tickers:  33%|███▎      | 2233/6717 [07:36<15:23,  4.86it/s]

Processing tickers:  33%|███▎      | 2234/6717 [07:36<15:28,  4.83it/s]

Processing tickers:  33%|███▎      | 2235/6717 [07:36<15:21,  4.86it/s]

Processing tickers:  33%|███▎      | 2236/6717 [07:36<15:28,  4.83it/s]

Processing tickers:  33%|███▎      | 2237/6717 [07:37<15:20,  4.87it/s]

Processing tickers:  33%|███▎      | 2238/6717 [07:37<15:37,  4.78it/s]

Processing tickers:  33%|███▎      | 2239/6717 [07:37<15:27,  4.83it/s]

Processing tickers:  33%|███▎      | 2240/6717 [07:37<15:19,  4.87it/s]

Processing tickers:  33%|███▎      | 2241/6717 [07:37<15:21,  4.85it/s]

Processing tickers:  33%|███▎      | 2242/6717 [07:38<15:22,  4.85it/s]

Processing tickers:  33%|███▎      | 2243/6717 [07:38<15:15,  4.89it/s]

Processing tickers:  33%|███▎      | 2244/6717 [07:38<15:25,  4.83it/s]

Processing tickers:  33%|███▎      | 2245/6717 [07:38<15:21,  4.85it/s]

Processing tickers:  33%|███▎      | 2246/6717 [07:38<15:16,  4.88it/s]

Processing tickers:  33%|███▎      | 2247/6717 [07:39<15:06,  4.93it/s]

Processing tickers:  33%|███▎      | 2248/6717 [07:39<15:03,  4.95it/s]

Processing tickers:  33%|███▎      | 2249/6717 [07:39<15:14,  4.89it/s]

Processing tickers:  33%|███▎      | 2250/6717 [07:39<15:13,  4.89it/s]

Processing tickers:  34%|███▎      | 2251/6717 [07:39<15:09,  4.91it/s]

Processing tickers:  34%|███▎      | 2252/6717 [07:40<15:06,  4.92it/s]

Processing tickers:  34%|███▎      | 2253/6717 [07:40<15:02,  4.95it/s]

Processing tickers:  34%|███▎      | 2254/6717 [07:40<15:18,  4.86it/s]

Processing tickers:  34%|███▎      | 2255/6717 [07:40<15:13,  4.89it/s]

Processing tickers:  34%|███▎      | 2256/6717 [07:40<15:06,  4.92it/s]

Processing tickers:  34%|███▎      | 2257/6717 [07:41<15:02,  4.94it/s]

Processing tickers:  34%|███▎      | 2258/6717 [07:41<15:00,  4.95it/s]

Processing tickers:  34%|███▎      | 2259/6717 [07:41<15:02,  4.94it/s]

Processing tickers:  34%|███▎      | 2260/6717 [07:41<15:01,  4.95it/s]

Processing tickers:  34%|███▎      | 2261/6717 [07:41<15:15,  4.87it/s]

Processing tickers:  34%|███▎      | 2262/6717 [07:42<15:09,  4.90it/s]

Processing tickers:  34%|███▎      | 2263/6717 [07:42<15:01,  4.94it/s]

Processing tickers:  34%|███▎      | 2264/6717 [07:42<14:59,  4.95it/s]

Processing tickers:  34%|███▎      | 2265/6717 [07:42<15:25,  4.81it/s]

Processing tickers:  34%|███▎      | 2266/6717 [07:42<15:21,  4.83it/s]

Processing tickers:  34%|███▍      | 2267/6717 [07:43<15:24,  4.81it/s]

Processing tickers:  34%|███▍      | 2268/6717 [07:43<15:15,  4.86it/s]

Processing tickers:  34%|███▍      | 2269/6717 [07:43<15:06,  4.91it/s]

Processing tickers:  34%|███▍      | 2270/6717 [07:43<15:13,  4.87it/s]

Processing tickers:  34%|███▍      | 2271/6717 [07:43<15:10,  4.89it/s]

Processing tickers:  34%|███▍      | 2272/6717 [07:44<15:05,  4.91it/s]

Processing tickers:  34%|███▍      | 2273/6717 [07:44<15:21,  4.82it/s]

Processing tickers:  34%|███▍      | 2274/6717 [07:44<15:12,  4.87it/s]

Processing tickers:  34%|███▍      | 2275/6717 [07:44<15:11,  4.87it/s]

Processing tickers:  34%|███▍      | 2276/6717 [07:45<15:06,  4.90it/s]

Processing tickers:  34%|███▍      | 2277/6717 [07:45<15:13,  4.86it/s]

Processing tickers:  34%|███▍      | 2278/6717 [07:45<15:11,  4.87it/s]

Processing tickers:  34%|███▍      | 2279/6717 [07:45<15:13,  4.86it/s]

Processing tickers:  34%|███▍      | 2280/6717 [07:45<15:13,  4.86it/s]

Processing tickers:  34%|███▍      | 2281/6717 [07:46<15:11,  4.86it/s]

Processing tickers:  34%|███▍      | 2282/6717 [07:46<15:23,  4.80it/s]

Processing tickers:  34%|███▍      | 2283/6717 [07:46<15:18,  4.83it/s]

Processing tickers:  34%|███▍      | 2284/6717 [07:46<15:08,  4.88it/s]

Processing tickers:  34%|███▍      | 2285/6717 [07:46<15:06,  4.89it/s]

Processing tickers:  34%|███▍      | 2286/6717 [07:47<14:58,  4.93it/s]

Processing tickers:  34%|███▍      | 2287/6717 [07:47<14:54,  4.95it/s]

Processing tickers:  34%|███▍      | 2288/6717 [07:47<15:05,  4.89it/s]

Processing tickers:  34%|███▍      | 2289/6717 [07:47<15:00,  4.92it/s]

Processing tickers:  34%|███▍      | 2290/6717 [07:47<14:55,  4.95it/s]

Processing tickers:  34%|███▍      | 2291/6717 [07:48<14:51,  4.97it/s]

Processing tickers:  34%|███▍      | 2292/6717 [07:48<14:48,  4.98it/s]

Processing tickers:  34%|███▍      | 2293/6717 [07:48<15:22,  4.79it/s]

Processing tickers:  34%|███▍      | 2294/6717 [07:48<15:27,  4.77it/s]

Processing tickers:  34%|███▍      | 2295/6717 [07:48<15:23,  4.79it/s]

Processing tickers:  34%|███▍      | 2296/6717 [07:49<15:11,  4.85it/s]

Processing tickers:  34%|███▍      | 2297/6717 [07:49<15:14,  4.83it/s]

Processing tickers:  34%|███▍      | 2298/6717 [07:49<15:03,  4.89it/s]

Processing tickers:  34%|███▍      | 2299/6717 [07:49<14:57,  4.92it/s]

Processing tickers:  34%|███▍      | 2300/6717 [07:49<14:52,  4.95it/s]

Processing tickers:  34%|███▍      | 2301/6717 [07:50<14:48,  4.97it/s]

Processing tickers:  34%|███▍      | 2302/6717 [07:50<14:45,  4.99it/s]

Processing tickers:  34%|███▍      | 2303/6717 [07:50<14:47,  4.97it/s]

Processing tickers:  34%|███▍      | 2304/6717 [07:50<14:54,  4.94it/s]

Processing tickers:  34%|███▍      | 2305/6717 [07:50<14:54,  4.93it/s]

Processing tickers:  34%|███▍      | 2306/6717 [07:51<14:53,  4.94it/s]

Processing tickers:  34%|███▍      | 2307/6717 [07:51<14:54,  4.93it/s]

Processing tickers:  34%|███▍      | 2308/6717 [07:51<14:54,  4.93it/s]

Processing tickers:  34%|███▍      | 2309/6717 [07:51<14:56,  4.92it/s]

Processing tickers:  34%|███▍      | 2310/6717 [07:51<14:51,  4.94it/s]

Processing tickers:  34%|███▍      | 2311/6717 [07:52<14:45,  4.98it/s]

Processing tickers:  34%|███▍      | 2312/6717 [07:52<14:43,  4.98it/s]

Processing tickers:  34%|███▍      | 2313/6717 [07:52<14:46,  4.97it/s]

Processing tickers:  34%|███▍      | 2314/6717 [07:52<14:42,  4.99it/s]

Processing tickers:  34%|███▍      | 2315/6717 [07:52<14:40,  5.00it/s]

Processing tickers:  34%|███▍      | 2316/6717 [07:53<14:49,  4.95it/s]

Processing tickers:  34%|███▍      | 2317/6717 [07:53<14:46,  4.96it/s]

Processing tickers:  35%|███▍      | 2318/6717 [07:53<15:00,  4.89it/s]

Processing tickers:  35%|███▍      | 2319/6717 [07:53<14:54,  4.92it/s]

Processing tickers:  35%|███▍      | 2320/6717 [07:53<14:50,  4.94it/s]

Processing tickers:  35%|███▍      | 2321/6717 [07:54<14:46,  4.96it/s]

Processing tickers:  35%|███▍      | 2322/6717 [07:54<14:40,  4.99it/s]

Processing tickers:  35%|███▍      | 2323/6717 [07:54<14:49,  4.94it/s]

Processing tickers:  35%|███▍      | 2324/6717 [07:54<15:09,  4.83it/s]

Processing tickers:  35%|███▍      | 2325/6717 [07:54<15:00,  4.88it/s]

Processing tickers:  35%|███▍      | 2326/6717 [07:55<14:54,  4.91it/s]

Processing tickers:  35%|███▍      | 2327/6717 [07:55<15:02,  4.86it/s]

Processing tickers:  35%|███▍      | 2328/6717 [07:55<15:01,  4.87it/s]

Processing tickers:  35%|███▍      | 2329/6717 [07:55<14:56,  4.90it/s]

Processing tickers:  35%|███▍      | 2330/6717 [07:56<14:50,  4.92it/s]

Processing tickers:  35%|███▍      | 2331/6717 [07:56<14:49,  4.93it/s]

Processing tickers:  35%|███▍      | 2332/6717 [07:56<14:48,  4.94it/s]

Processing tickers:  35%|███▍      | 2333/6717 [07:56<14:42,  4.97it/s]

Processing tickers:  35%|███▍      | 2334/6717 [07:56<14:43,  4.96it/s]

Processing tickers:  35%|███▍      | 2335/6717 [07:57<14:41,  4.97it/s]

Processing tickers:  35%|███▍      | 2336/6717 [07:57<14:38,  4.99it/s]

Processing tickers:  35%|███▍      | 2337/6717 [07:57<14:34,  5.01it/s]

Processing tickers:  35%|███▍      | 2338/6717 [07:57<14:35,  5.00it/s]

Processing tickers:  35%|███▍      | 2339/6717 [07:57<14:45,  4.94it/s]

Processing tickers:  35%|███▍      | 2340/6717 [07:58<14:43,  4.96it/s]

Processing tickers:  35%|███▍      | 2341/6717 [07:58<14:56,  4.88it/s]

Processing tickers:  35%|███▍      | 2342/6717 [07:58<14:47,  4.93it/s]

Processing tickers:  35%|███▍      | 2343/6717 [07:58<14:45,  4.94it/s]

Processing tickers:  35%|███▍      | 2344/6717 [07:58<14:48,  4.92it/s]

Processing tickers:  35%|███▍      | 2345/6717 [07:59<14:45,  4.94it/s]

Processing tickers:  35%|███▍      | 2346/6717 [07:59<14:42,  4.96it/s]

Processing tickers:  35%|███▍      | 2347/6717 [07:59<14:37,  4.98it/s]

Processing tickers:  35%|███▍      | 2348/6717 [07:59<14:40,  4.96it/s]

Processing tickers:  35%|███▍      | 2349/6717 [07:59<14:44,  4.94it/s]

Processing tickers:  35%|███▍      | 2350/6717 [08:00<14:58,  4.86it/s]

Processing tickers:  35%|███▌      | 2351/6717 [08:00<15:03,  4.83it/s]

Processing tickers:  35%|███▌      | 2352/6717 [08:00<15:16,  4.76it/s]

Processing tickers:  35%|███▌      | 2353/6717 [08:00<15:07,  4.81it/s]

Processing tickers:  35%|███▌      | 2354/6717 [08:00<15:01,  4.84it/s]

Processing tickers:  35%|███▌      | 2355/6717 [08:01<14:52,  4.89it/s]

Processing tickers:  35%|███▌      | 2356/6717 [08:01<14:48,  4.91it/s]

Processing tickers:  35%|███▌      | 2357/6717 [08:01<14:53,  4.88it/s]

Processing tickers:  35%|███▌      | 2358/6717 [08:01<14:48,  4.90it/s]

Processing tickers:  35%|███▌      | 2359/6717 [08:01<14:43,  4.93it/s]

Processing tickers:  35%|███▌      | 2360/6717 [08:02<15:02,  4.83it/s]

Processing tickers:  35%|███▌      | 2361/6717 [08:02<14:48,  4.90it/s]

Processing tickers:  35%|███▌      | 2362/6717 [08:02<14:49,  4.90it/s]

Processing tickers:  35%|███▌      | 2363/6717 [08:02<14:46,  4.91it/s]

Processing tickers:  35%|███▌      | 2364/6717 [08:02<14:43,  4.93it/s]

Processing tickers:  35%|███▌      | 2365/6717 [08:03<14:39,  4.95it/s]

Processing tickers:  35%|███▌      | 2366/6717 [08:03<14:44,  4.92it/s]

Processing tickers:  35%|███▌      | 2367/6717 [08:03<14:48,  4.90it/s]

Processing tickers:  35%|███▌      | 2368/6717 [08:03<14:45,  4.91it/s]

Processing tickers:  35%|███▌      | 2369/6717 [08:03<15:00,  4.83it/s]

Processing tickers:  35%|███▌      | 2370/6717 [08:04<14:53,  4.87it/s]

Processing tickers:  35%|███▌      | 2371/6717 [08:04<14:50,  4.88it/s]

Processing tickers:  35%|███▌      | 2372/6717 [08:04<14:53,  4.86it/s]

Processing tickers:  35%|███▌      | 2373/6717 [08:04<14:51,  4.87it/s]

Processing tickers:  35%|███▌      | 2374/6717 [08:04<14:44,  4.91it/s]

Processing tickers:  35%|███▌      | 2375/6717 [08:05<14:43,  4.91it/s]

Processing tickers:  35%|███▌      | 2376/6717 [08:05<14:40,  4.93it/s]

Processing tickers:  35%|███▌      | 2377/6717 [08:05<14:35,  4.96it/s]

Processing tickers:  35%|███▌      | 2378/6717 [08:05<14:30,  4.99it/s]

Processing tickers:  35%|███▌      | 2379/6717 [08:05<14:30,  4.98it/s]

Processing tickers:  35%|███▌      | 2380/6717 [08:06<14:31,  4.98it/s]

Processing tickers:  35%|███▌      | 2381/6717 [08:06<14:39,  4.93it/s]

Processing tickers:  35%|███▌      | 2382/6717 [08:06<14:37,  4.94it/s]

Processing tickers:  35%|███▌      | 2383/6717 [08:06<14:36,  4.94it/s]

Processing tickers:  35%|███▌      | 2384/6717 [08:07<14:49,  4.87it/s]

Processing tickers:  36%|███▌      | 2385/6717 [08:07<14:43,  4.90it/s]

Processing tickers:  36%|███▌      | 2386/6717 [08:07<14:42,  4.91it/s]

Processing tickers:  36%|███▌      | 2387/6717 [08:07<14:36,  4.94it/s]

Processing tickers:  36%|███▌      | 2388/6717 [08:07<14:34,  4.95it/s]

Processing tickers:  36%|███▌      | 2389/6717 [08:08<14:35,  4.95it/s]

Processing tickers:  36%|███▌      | 2390/6717 [08:08<14:29,  4.98it/s]

Processing tickers:  36%|███▌      | 2391/6717 [08:08<14:24,  5.00it/s]

Processing tickers:  36%|███▌      | 2392/6717 [08:08<14:53,  4.84it/s]

Processing tickers:  36%|███▌      | 2393/6717 [08:08<14:49,  4.86it/s]

Processing tickers:  36%|███▌      | 2394/6717 [08:09<14:48,  4.87it/s]

Processing tickers:  36%|███▌      | 2395/6717 [08:09<14:41,  4.90it/s]

Processing tickers:  36%|███▌      | 2396/6717 [08:09<14:41,  4.90it/s]

Processing tickers:  36%|███▌      | 2397/6717 [08:09<14:37,  4.93it/s]

Processing tickers:  36%|███▌      | 2398/6717 [08:09<14:36,  4.93it/s]

Processing tickers:  36%|███▌      | 2399/6717 [08:10<14:37,  4.92it/s]

Processing tickers:  36%|███▌      | 2400/6717 [08:10<14:41,  4.90it/s]

Processing tickers:  36%|███▌      | 2401/6717 [08:10<14:40,  4.90it/s]

Processing tickers:  36%|███▌      | 2402/6717 [08:10<15:03,  4.78it/s]

Processing tickers:  36%|███▌      | 2403/6717 [08:10<14:57,  4.80it/s]

Processing tickers:  36%|███▌      | 2404/6717 [08:11<14:51,  4.84it/s]

Processing tickers:  36%|███▌      | 2405/6717 [08:11<14:44,  4.87it/s]

Processing tickers:  36%|███▌      | 2406/6717 [08:11<14:50,  4.84it/s]

Processing tickers:  36%|███▌      | 2407/6717 [08:11<14:49,  4.84it/s]

Processing tickers:  36%|███▌      | 2408/6717 [08:11<14:50,  4.84it/s]

Processing tickers:  36%|███▌      | 2409/6717 [08:12<14:55,  4.81it/s]

Processing tickers:  36%|███▌      | 2410/6717 [08:12<14:50,  4.84it/s]

Processing tickers:  36%|███▌      | 2411/6717 [08:12<14:43,  4.87it/s]

Processing tickers:  36%|███▌      | 2412/6717 [08:12<14:36,  4.91it/s]

Processing tickers:  36%|███▌      | 2413/6717 [08:12<14:31,  4.94it/s]

Processing tickers:  36%|███▌      | 2414/6717 [08:13<14:30,  4.94it/s]

Processing tickers:  36%|███▌      | 2415/6717 [08:13<14:31,  4.94it/s]

Processing tickers:  36%|███▌      | 2416/6717 [08:13<14:28,  4.95it/s]

Processing tickers:  36%|███▌      | 2417/6717 [08:13<14:35,  4.91it/s]

Processing tickers:  36%|███▌      | 2418/6717 [08:13<14:44,  4.86it/s]

Processing tickers:  36%|███▌      | 2419/6717 [08:14<14:55,  4.80it/s]

Processing tickers:  36%|███▌      | 2420/6717 [08:14<14:46,  4.85it/s]

Processing tickers:  36%|███▌      | 2421/6717 [08:14<14:44,  4.86it/s]

Processing tickers:  36%|███▌      | 2422/6717 [08:14<14:42,  4.87it/s]

Processing tickers:  36%|███▌      | 2423/6717 [08:14<14:42,  4.87it/s]

Processing tickers:  36%|███▌      | 2424/6717 [08:15<14:36,  4.90it/s]

Processing tickers:  36%|███▌      | 2425/6717 [08:15<14:31,  4.92it/s]

Processing tickers:  36%|███▌      | 2426/6717 [08:15<14:25,  4.96it/s]

Processing tickers:  36%|███▌      | 2427/6717 [08:15<14:24,  4.96it/s]

Processing tickers:  36%|███▌      | 2428/6717 [08:15<14:21,  4.98it/s]

Processing tickers:  36%|███▌      | 2429/6717 [08:16<14:20,  4.98it/s]

Processing tickers:  36%|███▌      | 2430/6717 [08:16<14:21,  4.98it/s]

Processing tickers:  36%|███▌      | 2431/6717 [08:16<14:17,  5.00it/s]

Processing tickers:  36%|███▌      | 2432/6717 [08:16<14:15,  5.01it/s]

Processing tickers:  36%|███▌      | 2433/6717 [08:16<14:17,  5.00it/s]

Processing tickers:  36%|███▌      | 2434/6717 [08:17<14:17,  4.99it/s]

Processing tickers:  36%|███▋      | 2435/6717 [08:17<14:23,  4.96it/s]

Processing tickers:  36%|███▋      | 2436/6717 [08:17<14:26,  4.94it/s]

Processing tickers:  36%|███▋      | 2437/6717 [08:17<14:21,  4.97it/s]

Processing tickers:  36%|███▋      | 2438/6717 [08:17<14:18,  4.98it/s]

Processing tickers:  36%|███▋      | 2439/6717 [08:18<14:15,  5.00it/s]

Processing tickers:  36%|███▋      | 2440/6717 [08:18<14:16,  4.99it/s]

Processing tickers:  36%|███▋      | 2441/6717 [08:18<14:18,  4.98it/s]

Processing tickers:  36%|███▋      | 2442/6717 [08:18<14:21,  4.96it/s]

Processing tickers:  36%|███▋      | 2443/6717 [08:18<14:20,  4.97it/s]

Processing tickers:  36%|███▋      | 2444/6717 [08:19<14:26,  4.93it/s]

Processing tickers:  36%|███▋      | 2445/6717 [08:19<14:22,  4.95it/s]

Processing tickers:  36%|███▋      | 2446/6717 [08:19<14:28,  4.92it/s]

Processing tickers:  36%|███▋      | 2447/6717 [08:19<14:33,  4.89it/s]

Processing tickers:  36%|███▋      | 2448/6717 [08:20<14:31,  4.90it/s]

Processing tickers:  36%|███▋      | 2449/6717 [08:20<14:40,  4.85it/s]

Processing tickers:  36%|███▋      | 2450/6717 [08:20<14:37,  4.87it/s]

Processing tickers:  36%|███▋      | 2451/6717 [08:20<14:39,  4.85it/s]

Processing tickers:  37%|███▋      | 2452/6717 [08:20<14:38,  4.85it/s]

Processing tickers:  37%|███▋      | 2453/6717 [08:21<14:36,  4.87it/s]

Processing tickers:  37%|███▋      | 2454/6717 [08:21<14:30,  4.90it/s]

Processing tickers:  37%|███▋      | 2455/6717 [08:21<14:22,  4.94it/s]

Processing tickers:  37%|███▋      | 2456/6717 [08:21<14:22,  4.94it/s]

Processing tickers:  37%|███▋      | 2457/6717 [08:21<14:31,  4.89it/s]

Processing tickers:  37%|███▋      | 2458/6717 [08:22<14:28,  4.90it/s]

Processing tickers:  37%|███▋      | 2459/6717 [08:22<14:24,  4.92it/s]

Processing tickers:  37%|███▋      | 2460/6717 [08:22<14:22,  4.93it/s]

Processing tickers:  37%|███▋      | 2461/6717 [08:22<14:23,  4.93it/s]

Processing tickers:  37%|███▋      | 2462/6717 [08:22<14:20,  4.95it/s]

Processing tickers:  37%|███▋      | 2463/6717 [08:23<14:21,  4.94it/s]

Processing tickers:  37%|███▋      | 2464/6717 [08:23<14:25,  4.91it/s]

Processing tickers:  37%|███▋      | 2465/6717 [08:23<14:39,  4.84it/s]

Processing tickers:  37%|███▋      | 2466/6717 [08:23<14:35,  4.86it/s]

Processing tickers:  37%|███▋      | 2467/6717 [08:23<14:26,  4.91it/s]

Processing tickers:  37%|███▋      | 2468/6717 [08:24<14:22,  4.93it/s]

Processing tickers:  37%|███▋      | 2469/6717 [08:24<14:18,  4.95it/s]

Processing tickers:  37%|███▋      | 2470/6717 [08:24<14:37,  4.84it/s]

Processing tickers:  37%|███▋      | 2471/6717 [08:24<14:28,  4.89it/s]

Processing tickers:  37%|███▋      | 2472/6717 [08:24<14:31,  4.87it/s]

Processing tickers:  37%|███▋      | 2473/6717 [08:25<14:21,  4.93it/s]

Processing tickers:  37%|███▋      | 2474/6717 [08:25<15:05,  4.69it/s]

Processing tickers:  37%|███▋      | 2475/6717 [08:25<14:49,  4.77it/s]

Processing tickers:  37%|███▋      | 2476/6717 [08:25<14:36,  4.84it/s]

Processing tickers:  37%|███▋      | 2477/6717 [08:25<14:31,  4.87it/s]

Processing tickers:  37%|███▋      | 2478/6717 [08:26<14:36,  4.84it/s]

Processing tickers:  37%|███▋      | 2479/6717 [08:26<14:30,  4.87it/s]

Processing tickers:  37%|███▋      | 2480/6717 [08:26<14:26,  4.89it/s]

Processing tickers:  37%|███▋      | 2481/6717 [08:26<14:23,  4.91it/s]

Processing tickers:  37%|███▋      | 2482/6717 [08:26<14:21,  4.92it/s]

Processing tickers:  37%|███▋      | 2483/6717 [08:27<14:22,  4.91it/s]

Processing tickers:  37%|███▋      | 2484/6717 [08:27<14:20,  4.92it/s]

Processing tickers:  37%|███▋      | 2485/6717 [08:27<14:15,  4.95it/s]

Processing tickers:  37%|███▋      | 2486/6717 [08:27<14:24,  4.90it/s]

Processing tickers:  37%|███▋      | 2487/6717 [08:28<14:22,  4.90it/s]

Processing tickers:  37%|███▋      | 2488/6717 [08:28<14:16,  4.93it/s]

Processing tickers:  37%|███▋      | 2489/6717 [08:28<14:31,  4.85it/s]

Processing tickers:  37%|███▋      | 2490/6717 [08:28<14:27,  4.87it/s]

Processing tickers:  37%|███▋      | 2491/6717 [08:28<14:36,  4.82it/s]

Processing tickers:  37%|███▋      | 2492/6717 [08:29<14:31,  4.85it/s]

Processing tickers:  37%|███▋      | 2493/6717 [08:29<14:24,  4.88it/s]

Processing tickers:  37%|███▋      | 2494/6717 [08:29<14:20,  4.90it/s]

Processing tickers:  37%|███▋      | 2495/6717 [08:29<14:18,  4.92it/s]

Processing tickers:  37%|███▋      | 2496/6717 [08:29<14:20,  4.91it/s]

Processing tickers:  37%|███▋      | 2497/6717 [08:30<14:17,  4.92it/s]

Processing tickers:  37%|███▋      | 2498/6717 [08:30<14:12,  4.95it/s]

Processing tickers:  37%|███▋      | 2499/6717 [08:30<14:12,  4.95it/s]

Processing tickers:  37%|███▋      | 2500/6717 [08:30<14:10,  4.96it/s]

Processing tickers:  37%|███▋      | 2501/6717 [08:30<14:16,  4.92it/s]

Processing tickers:  37%|███▋      | 2502/6717 [08:31<14:19,  4.90it/s]

Processing tickers:  37%|███▋      | 2503/6717 [08:31<14:20,  4.90it/s]

Processing tickers:  37%|███▋      | 2504/6717 [08:31<14:22,  4.88it/s]

Processing tickers:  37%|███▋      | 2505/6717 [08:31<14:19,  4.90it/s]

Processing tickers:  37%|███▋      | 2506/6717 [08:31<14:17,  4.91it/s]

Processing tickers:  37%|███▋      | 2507/6717 [08:32<14:17,  4.91it/s]

Processing tickers:  37%|███▋      | 2508/6717 [08:32<14:38,  4.79it/s]

Processing tickers:  37%|███▋      | 2509/6717 [08:32<14:46,  4.75it/s]

Processing tickers:  37%|███▋      | 2510/6717 [08:32<14:35,  4.80it/s]

Processing tickers:  37%|███▋      | 2511/6717 [08:32<14:41,  4.77it/s]

Processing tickers:  37%|███▋      | 2512/6717 [08:33<14:42,  4.77it/s]

Processing tickers:  37%|███▋      | 2513/6717 [08:33<14:35,  4.80it/s]

Processing tickers:  37%|███▋      | 2514/6717 [08:33<14:23,  4.87it/s]

Processing tickers:  37%|███▋      | 2515/6717 [08:33<14:17,  4.90it/s]

Processing tickers:  37%|███▋      | 2516/6717 [08:33<14:13,  4.92it/s]

Processing tickers:  37%|███▋      | 2517/6717 [08:34<14:10,  4.94it/s]

Processing tickers:  37%|███▋      | 2518/6717 [08:34<14:13,  4.92it/s]

Processing tickers:  38%|███▊      | 2519/6717 [08:34<14:09,  4.94it/s]

Processing tickers:  38%|███▊      | 2520/6717 [08:34<14:07,  4.95it/s]

Processing tickers:  38%|███▊      | 2521/6717 [08:34<14:12,  4.92it/s]

Processing tickers:  38%|███▊      | 2522/6717 [08:35<14:12,  4.92it/s]

Processing tickers:  38%|███▊      | 2523/6717 [08:35<14:10,  4.93it/s]

Processing tickers:  38%|███▊      | 2524/6717 [08:35<14:06,  4.95it/s]

Processing tickers:  38%|███▊      | 2525/6717 [08:35<14:08,  4.94it/s]

Processing tickers:  38%|███▊      | 2526/6717 [08:35<14:13,  4.91it/s]

Processing tickers:  38%|███▊      | 2527/6717 [08:36<14:05,  4.95it/s]

Processing tickers:  38%|███▊      | 2528/6717 [08:36<14:07,  4.94it/s]

Processing tickers:  38%|███▊      | 2529/6717 [08:36<14:22,  4.85it/s]

Processing tickers:  38%|███▊      | 2530/6717 [08:36<14:16,  4.89it/s]

Processing tickers:  38%|███▊      | 2531/6717 [08:37<14:16,  4.89it/s]

Processing tickers:  38%|███▊      | 2532/6717 [08:37<14:16,  4.88it/s]

Processing tickers:  38%|███▊      | 2533/6717 [08:37<14:10,  4.92it/s]

Processing tickers:  38%|███▊      | 2534/6717 [08:37<14:09,  4.92it/s]

Processing tickers:  38%|███▊      | 2535/6717 [08:37<14:08,  4.93it/s]

Processing tickers:  38%|███▊      | 2536/6717 [08:38<14:06,  4.94it/s]

Processing tickers:  38%|███▊      | 2537/6717 [08:38<14:04,  4.95it/s]

Processing tickers:  38%|███▊      | 2538/6717 [08:38<14:03,  4.95it/s]

Processing tickers:  38%|███▊      | 2539/6717 [08:38<14:04,  4.95it/s]

Processing tickers:  38%|███▊      | 2540/6717 [08:38<14:02,  4.96it/s]

Processing tickers:  38%|███▊      | 2541/6717 [08:39<14:03,  4.95it/s]

Processing tickers:  38%|███▊      | 2542/6717 [08:39<14:11,  4.91it/s]

Processing tickers:  38%|███▊      | 2543/6717 [08:39<14:08,  4.92it/s]

Processing tickers:  38%|███▊      | 2544/6717 [08:39<14:43,  4.72it/s]

Processing tickers:  38%|███▊      | 2545/6717 [08:39<14:28,  4.80it/s]

Processing tickers:  38%|███▊      | 2546/6717 [08:40<14:24,  4.83it/s]

Processing tickers:  38%|███▊      | 2547/6717 [08:40<14:16,  4.87it/s]

Processing tickers:  38%|███▊      | 2548/6717 [08:40<14:10,  4.90it/s]

Processing tickers:  38%|███▊      | 2549/6717 [08:40<14:10,  4.90it/s]

Processing tickers:  38%|███▊      | 2550/6717 [08:40<14:06,  4.92it/s]

Processing tickers:  38%|███▊      | 2551/6717 [08:41<14:02,  4.95it/s]

Processing tickers:  38%|███▊      | 2552/6717 [08:41<14:02,  4.94it/s]

Processing tickers:  38%|███▊      | 2553/6717 [08:41<14:01,  4.95it/s]

Processing tickers:  38%|███▊      | 2554/6717 [08:41<14:03,  4.94it/s]

Processing tickers:  38%|███▊      | 2555/6717 [08:41<14:40,  4.73it/s]

Processing tickers:  38%|███▊      | 2556/6717 [08:42<14:30,  4.78it/s]

Processing tickers:  38%|███▊      | 2557/6717 [08:42<14:17,  4.85it/s]

Processing tickers:  38%|███▊      | 2558/6717 [08:42<14:21,  4.83it/s]

Processing tickers:  38%|███▊      | 2559/6717 [08:42<14:13,  4.87it/s]

Processing tickers:  38%|███▊      | 2560/6717 [08:42<14:15,  4.86it/s]

Processing tickers:  38%|███▊      | 2561/6717 [08:43<14:07,  4.91it/s]

Processing tickers:  38%|███▊      | 2562/6717 [08:43<14:06,  4.91it/s]

Processing tickers:  38%|███▊      | 2563/6717 [08:43<14:00,  4.94it/s]

Processing tickers:  38%|███▊      | 2564/6717 [08:43<13:55,  4.97it/s]

Processing tickers:  38%|███▊      | 2565/6717 [08:43<13:52,  4.98it/s]

Processing tickers:  38%|███▊      | 2566/6717 [08:44<14:00,  4.94it/s]

Processing tickers:  38%|███▊      | 2567/6717 [08:44<13:55,  4.97it/s]

Processing tickers:  38%|███▊      | 2568/6717 [08:44<13:58,  4.95it/s]

Processing tickers:  38%|███▊      | 2569/6717 [08:44<13:56,  4.96it/s]

Processing tickers:  38%|███▊      | 2570/6717 [08:44<14:15,  4.84it/s]

Processing tickers:  38%|███▊      | 2571/6717 [08:45<14:26,  4.79it/s]

Processing tickers:  38%|███▊      | 2572/6717 [08:45<14:18,  4.83it/s]

Processing tickers:  38%|███▊      | 2573/6717 [08:45<14:11,  4.87it/s]

Processing tickers:  38%|███▊      | 2574/6717 [08:45<14:05,  4.90it/s]

Processing tickers:  38%|███▊      | 2575/6717 [08:45<14:02,  4.92it/s]

Processing tickers:  38%|███▊      | 2576/6717 [08:46<14:06,  4.89it/s]

Processing tickers:  38%|███▊      | 2577/6717 [08:46<14:06,  4.89it/s]

Processing tickers:  38%|███▊      | 2578/6717 [08:46<14:46,  4.67it/s]

Processing tickers:  38%|███▊      | 2579/6717 [08:46<14:28,  4.76it/s]

Processing tickers:  38%|███▊      | 2580/6717 [08:47<14:16,  4.83it/s]

Processing tickers:  38%|███▊      | 2581/6717 [08:47<14:08,  4.88it/s]

Processing tickers:  38%|███▊      | 2582/6717 [08:47<14:05,  4.89it/s]

Processing tickers:  38%|███▊      | 2583/6717 [08:47<13:56,  4.94it/s]

Processing tickers:  38%|███▊      | 2584/6717 [08:47<13:59,  4.92it/s]

Processing tickers:  38%|███▊      | 2585/6717 [08:48<14:08,  4.87it/s]

Processing tickers:  38%|███▊      | 2586/6717 [08:48<14:06,  4.88it/s]

Processing tickers:  39%|███▊      | 2587/6717 [08:48<14:15,  4.83it/s]

Processing tickers:  39%|███▊      | 2588/6717 [08:48<14:36,  4.71it/s]

Processing tickers:  39%|███▊      | 2589/6717 [08:48<14:28,  4.75it/s]

Processing tickers:  39%|███▊      | 2590/6717 [08:49<14:18,  4.81it/s]

Processing tickers:  39%|███▊      | 2591/6717 [08:49<14:05,  4.88it/s]

Processing tickers:  39%|███▊      | 2592/6717 [08:49<14:13,  4.83it/s]

Processing tickers:  39%|███▊      | 2593/6717 [08:49<15:27,  4.45it/s]

Processing tickers:  39%|███▊      | 2594/6717 [08:49<14:58,  4.59it/s]

Processing tickers:  39%|███▊      | 2595/6717 [08:50<14:37,  4.70it/s]

Processing tickers:  39%|███▊      | 2596/6717 [08:50<14:25,  4.76it/s]

Processing tickers:  39%|███▊      | 2597/6717 [08:50<14:17,  4.81it/s]

Processing tickers:  39%|███▊      | 2598/6717 [08:50<14:09,  4.85it/s]

Processing tickers:  39%|███▊      | 2599/6717 [08:50<14:05,  4.87it/s]

Processing tickers:  39%|███▊      | 2600/6717 [08:51<13:58,  4.91it/s]

Processing tickers:  39%|███▊      | 2601/6717 [08:51<13:58,  4.91it/s]

Processing tickers:  39%|███▊      | 2602/6717 [08:51<13:52,  4.94it/s]

Processing tickers:  39%|███▉      | 2603/6717 [08:51<14:04,  4.87it/s]

Processing tickers:  39%|███▉      | 2604/6717 [08:52<13:59,  4.90it/s]

Processing tickers:  39%|███▉      | 2605/6717 [08:52<13:56,  4.91it/s]

Processing tickers:  39%|███▉      | 2606/6717 [08:52<13:52,  4.94it/s]

Processing tickers:  39%|███▉      | 2607/6717 [08:52<13:47,  4.96it/s]

Processing tickers:  39%|███▉      | 2608/6717 [08:52<13:56,  4.91it/s]

Processing tickers:  39%|███▉      | 2609/6717 [08:53<13:58,  4.90it/s]

Processing tickers:  39%|███▉      | 2610/6717 [08:53<13:57,  4.91it/s]

Processing tickers:  39%|███▉      | 2611/6717 [08:53<13:54,  4.92it/s]

Processing tickers:  39%|███▉      | 2612/6717 [08:53<14:01,  4.88it/s]

Processing tickers:  39%|███▉      | 2613/6717 [08:53<13:57,  4.90it/s]

Processing tickers:  39%|███▉      | 2614/6717 [08:54<13:56,  4.91it/s]

Processing tickers:  39%|███▉      | 2615/6717 [08:54<15:30,  4.41it/s]

Processing tickers:  39%|███▉      | 2616/6717 [08:54<15:04,  4.54it/s]

Processing tickers:  39%|███▉      | 2617/6717 [08:54<14:40,  4.66it/s]

Processing tickers:  39%|███▉      | 2618/6717 [08:54<14:23,  4.74it/s]

Processing tickers:  39%|███▉      | 2619/6717 [08:55<14:12,  4.81it/s]

Processing tickers:  39%|███▉      | 2620/6717 [08:55<14:02,  4.87it/s]

Processing tickers:  39%|███▉      | 2621/6717 [08:55<13:55,  4.90it/s]

Processing tickers:  39%|███▉      | 2622/6717 [08:55<13:50,  4.93it/s]

Processing tickers:  39%|███▉      | 2623/6717 [08:55<13:46,  4.95it/s]

Processing tickers:  39%|███▉      | 2624/6717 [08:56<13:44,  4.96it/s]

Processing tickers:  39%|███▉      | 2625/6717 [08:56<13:53,  4.91it/s]

Processing tickers:  39%|███▉      | 2626/6717 [08:56<14:14,  4.79it/s]

Processing tickers:  39%|███▉      | 2627/6717 [08:56<14:06,  4.83it/s]

Processing tickers:  39%|███▉      | 2628/6717 [08:56<14:10,  4.81it/s]

Processing tickers:  39%|███▉      | 2629/6717 [08:57<14:15,  4.78it/s]

Processing tickers:  39%|███▉      | 2630/6717 [08:57<14:05,  4.83it/s]

Processing tickers:  39%|███▉      | 2631/6717 [08:57<13:59,  4.87it/s]

Processing tickers:  39%|███▉      | 2632/6717 [08:57<13:53,  4.90it/s]

Processing tickers:  39%|███▉      | 2633/6717 [08:57<13:54,  4.90it/s]

Processing tickers:  39%|███▉      | 2634/6717 [08:58<13:50,  4.91it/s]

Processing tickers:  39%|███▉      | 2635/6717 [08:58<13:45,  4.95it/s]

Processing tickers:  39%|███▉      | 2636/6717 [08:58<13:53,  4.90it/s]

Processing tickers:  39%|███▉      | 2637/6717 [08:58<14:05,  4.82it/s]

Processing tickers:  39%|███▉      | 2638/6717 [08:59<13:56,  4.87it/s]

Processing tickers:  39%|███▉      | 2639/6717 [08:59<13:54,  4.89it/s]

Processing tickers:  39%|███▉      | 2640/6717 [08:59<13:53,  4.89it/s]

Processing tickers:  39%|███▉      | 2641/6717 [08:59<13:49,  4.91it/s]

Processing tickers:  39%|███▉      | 2642/6717 [08:59<13:56,  4.87it/s]

Processing tickers:  39%|███▉      | 2643/6717 [09:00<13:53,  4.89it/s]

Processing tickers:  39%|███▉      | 2644/6717 [09:00<13:45,  4.93it/s]

Processing tickers:  39%|███▉      | 2645/6717 [09:00<13:52,  4.89it/s]

Processing tickers:  39%|███▉      | 2646/6717 [09:00<13:49,  4.90it/s]

Processing tickers:  39%|███▉      | 2647/6717 [09:00<13:45,  4.93it/s]

Processing tickers:  39%|███▉      | 2648/6717 [09:01<13:49,  4.90it/s]

Processing tickers:  39%|███▉      | 2649/6717 [09:01<14:07,  4.80it/s]

Processing tickers:  39%|███▉      | 2650/6717 [09:01<13:55,  4.87it/s]

Processing tickers:  39%|███▉      | 2651/6717 [09:01<13:48,  4.91it/s]

Processing tickers:  39%|███▉      | 2652/6717 [09:01<13:49,  4.90it/s]

Processing tickers:  39%|███▉      | 2653/6717 [09:02<13:45,  4.93it/s]

Processing tickers:  40%|███▉      | 2654/6717 [09:02<13:43,  4.93it/s]

Processing tickers:  40%|███▉      | 2655/6717 [09:02<13:50,  4.89it/s]

Processing tickers:  40%|███▉      | 2656/6717 [09:02<13:49,  4.90it/s]

Processing tickers:  40%|███▉      | 2657/6717 [09:02<13:53,  4.87it/s]

Processing tickers:  40%|███▉      | 2658/6717 [09:03<13:50,  4.88it/s]

Processing tickers:  40%|███▉      | 2659/6717 [09:03<13:56,  4.85it/s]

Processing tickers:  40%|███▉      | 2660/6717 [09:03<13:58,  4.84it/s]

Processing tickers:  40%|███▉      | 2661/6717 [09:03<13:46,  4.91it/s]

Processing tickers:  40%|███▉      | 2662/6717 [09:03<13:45,  4.91it/s]

Processing tickers:  40%|███▉      | 2663/6717 [09:04<13:40,  4.94it/s]

Processing tickers:  40%|███▉      | 2664/6717 [09:04<13:37,  4.96it/s]

Processing tickers:  40%|███▉      | 2665/6717 [09:04<13:42,  4.93it/s]

Processing tickers:  40%|███▉      | 2666/6717 [09:04<13:36,  4.96it/s]

Processing tickers:  40%|███▉      | 2667/6717 [09:04<13:38,  4.95it/s]

Processing tickers:  40%|███▉      | 2668/6717 [09:05<13:40,  4.93it/s]

Processing tickers:  40%|███▉      | 2669/6717 [09:05<13:39,  4.94it/s]

Processing tickers:  40%|███▉      | 2670/6717 [09:05<13:44,  4.91it/s]

Processing tickers:  40%|███▉      | 2671/6717 [09:05<13:43,  4.91it/s]

Processing tickers:  40%|███▉      | 2672/6717 [09:05<13:44,  4.91it/s]

Processing tickers:  40%|███▉      | 2673/6717 [09:06<13:40,  4.93it/s]

Processing tickers:  40%|███▉      | 2674/6717 [09:06<13:44,  4.90it/s]

Processing tickers:  40%|███▉      | 2675/6717 [09:06<13:45,  4.90it/s]

Processing tickers:  40%|███▉      | 2676/6717 [09:06<14:00,  4.81it/s]

Processing tickers:  40%|███▉      | 2677/6717 [09:06<13:50,  4.86it/s]

Processing tickers:  40%|███▉      | 2678/6717 [09:07<13:47,  4.88it/s]

Processing tickers:  40%|███▉      | 2679/6717 [09:07<13:38,  4.93it/s]

Processing tickers:  40%|███▉      | 2680/6717 [09:07<13:41,  4.91it/s]

Processing tickers:  40%|███▉      | 2681/6717 [09:07<13:39,  4.93it/s]

Processing tickers:  40%|███▉      | 2682/6717 [09:07<13:39,  4.93it/s]

Processing tickers:  40%|███▉      | 2683/6717 [09:08<13:38,  4.93it/s]

Processing tickers:  40%|███▉      | 2684/6717 [09:08<13:38,  4.93it/s]

Processing tickers:  40%|███▉      | 2685/6717 [09:08<13:38,  4.93it/s]

Processing tickers:  40%|███▉      | 2686/6717 [09:08<13:40,  4.92it/s]

Processing tickers:  40%|████      | 2687/6717 [09:09<13:37,  4.93it/s]

Processing tickers:  40%|████      | 2688/6717 [09:09<13:35,  4.94it/s]

Processing tickers:  40%|████      | 2689/6717 [09:09<13:31,  4.96it/s]

Processing tickers:  40%|████      | 2690/6717 [09:09<13:30,  4.97it/s]

Processing tickers:  40%|████      | 2691/6717 [09:09<13:31,  4.96it/s]

Processing tickers:  40%|████      | 2692/6717 [09:10<13:33,  4.95it/s]

Processing tickers:  40%|████      | 2693/6717 [09:10<13:28,  4.98it/s]

Processing tickers:  40%|████      | 2694/6717 [09:10<13:26,  4.99it/s]

Processing tickers:  40%|████      | 2695/6717 [09:10<13:38,  4.91it/s]

Processing tickers:  40%|████      | 2696/6717 [09:10<13:34,  4.94it/s]

Processing tickers:  40%|████      | 2697/6717 [09:11<13:31,  4.96it/s]

Processing tickers:  40%|████      | 2698/6717 [09:11<13:29,  4.97it/s]

Processing tickers:  40%|████      | 2699/6717 [09:11<13:25,  4.99it/s]

Processing tickers:  40%|████      | 2700/6717 [09:11<13:32,  4.94it/s]

Processing tickers:  40%|████      | 2701/6717 [09:11<13:31,  4.95it/s]

Processing tickers:  40%|████      | 2702/6717 [09:12<13:32,  4.94it/s]

Processing tickers:  40%|████      | 2703/6717 [09:12<13:32,  4.94it/s]

Processing tickers:  40%|████      | 2704/6717 [09:12<13:39,  4.90it/s]

Processing tickers:  40%|████      | 2705/6717 [09:12<13:37,  4.91it/s]

Processing tickers:  40%|████      | 2706/6717 [09:12<13:32,  4.94it/s]

Processing tickers:  40%|████      | 2707/6717 [09:13<13:33,  4.93it/s]

Processing tickers:  40%|████      | 2708/6717 [09:13<13:34,  4.92it/s]

Processing tickers:  40%|████      | 2709/6717 [09:13<13:32,  4.93it/s]

Processing tickers:  40%|████      | 2710/6717 [09:13<13:30,  4.94it/s]

Processing tickers:  40%|████      | 2711/6717 [09:13<13:34,  4.92it/s]

Processing tickers:  40%|████      | 2712/6717 [09:14<13:32,  4.93it/s]

Processing tickers:  40%|████      | 2713/6717 [09:14<13:36,  4.91it/s]

Processing tickers:  40%|████      | 2714/6717 [09:14<13:39,  4.88it/s]

Processing tickers:  40%|████      | 2715/6717 [09:14<13:34,  4.91it/s]

Processing tickers:  40%|████      | 2716/6717 [09:14<13:31,  4.93it/s]

Processing tickers:  40%|████      | 2717/6717 [09:15<13:34,  4.91it/s]

Processing tickers:  40%|████      | 2718/6717 [09:15<13:48,  4.83it/s]

Processing tickers:  40%|████      | 2719/6717 [09:15<13:57,  4.78it/s]

Processing tickers:  40%|████      | 2720/6717 [09:15<13:43,  4.86it/s]

Processing tickers:  41%|████      | 2721/6717 [09:15<13:37,  4.89it/s]

Processing tickers:  41%|████      | 2722/6717 [09:16<13:31,  4.93it/s]

Processing tickers:  41%|████      | 2723/6717 [09:16<13:27,  4.95it/s]

Processing tickers:  41%|████      | 2724/6717 [09:16<13:33,  4.91it/s]

Processing tickers:  41%|████      | 2725/6717 [09:16<13:57,  4.76it/s]

Processing tickers:  41%|████      | 2726/6717 [09:16<13:47,  4.82it/s]

Processing tickers:  41%|████      | 2727/6717 [09:17<13:47,  4.82it/s]

Processing tickers:  41%|████      | 2728/6717 [09:17<13:37,  4.88it/s]

Processing tickers:  41%|████      | 2729/6717 [09:17<13:31,  4.91it/s]

Processing tickers:  41%|████      | 2730/6717 [09:17<13:26,  4.94it/s]

Processing tickers:  41%|████      | 2731/6717 [09:17<13:26,  4.95it/s]

Processing tickers:  41%|████      | 2732/6717 [09:18<13:24,  4.96it/s]

Processing tickers:  41%|████      | 2733/6717 [09:18<13:23,  4.96it/s]

Processing tickers:  41%|████      | 2734/6717 [09:18<13:23,  4.96it/s]

Processing tickers:  41%|████      | 2735/6717 [09:18<13:33,  4.89it/s]

Processing tickers:  41%|████      | 2736/6717 [09:18<13:26,  4.94it/s]

Processing tickers:  41%|████      | 2737/6717 [09:19<13:30,  4.91it/s]

Processing tickers:  41%|████      | 2738/6717 [09:19<13:27,  4.93it/s]

Processing tickers:  41%|████      | 2739/6717 [09:19<13:26,  4.93it/s]

Processing tickers:  41%|████      | 2740/6717 [09:19<13:34,  4.88it/s]

Processing tickers:  41%|████      | 2741/6717 [09:19<13:27,  4.92it/s]

Processing tickers:  41%|████      | 2742/6717 [09:20<13:25,  4.93it/s]

Processing tickers:  41%|████      | 2743/6717 [09:20<13:31,  4.90it/s]

Processing tickers:  41%|████      | 2744/6717 [09:20<13:46,  4.81it/s]

Processing tickers:  41%|████      | 2745/6717 [09:20<13:40,  4.84it/s]

Processing tickers:  41%|████      | 2746/6717 [09:21<13:36,  4.86it/s]

Processing tickers:  41%|████      | 2747/6717 [09:21<13:32,  4.89it/s]

Processing tickers:  41%|████      | 2748/6717 [09:21<13:32,  4.89it/s]

Processing tickers:  41%|████      | 2749/6717 [09:21<13:27,  4.91it/s]

Processing tickers:  41%|████      | 2750/6717 [09:21<13:40,  4.83it/s]

Processing tickers:  41%|████      | 2751/6717 [09:22<13:33,  4.88it/s]

Processing tickers:  41%|████      | 2752/6717 [09:22<13:27,  4.91it/s]

Processing tickers:  41%|████      | 2753/6717 [09:22<13:22,  4.94it/s]

Processing tickers:  41%|████      | 2754/6717 [09:22<13:21,  4.95it/s]

Processing tickers:  41%|████      | 2755/6717 [09:22<13:19,  4.96it/s]

Processing tickers:  41%|████      | 2756/6717 [09:23<13:31,  4.88it/s]

Processing tickers:  41%|████      | 2757/6717 [09:23<13:35,  4.86it/s]

Processing tickers:  41%|████      | 2758/6717 [09:23<13:30,  4.89it/s]

Processing tickers:  41%|████      | 2759/6717 [09:23<14:07,  4.67it/s]

Processing tickers:  41%|████      | 2760/6717 [09:23<13:53,  4.75it/s]

Processing tickers:  41%|████      | 2761/6717 [09:24<13:40,  4.82it/s]

Processing tickers:  41%|████      | 2762/6717 [09:24<13:31,  4.88it/s]

Processing tickers:  41%|████      | 2763/6717 [09:24<13:36,  4.84it/s]

Processing tickers:  41%|████      | 2764/6717 [09:24<13:25,  4.90it/s]

Processing tickers:  41%|████      | 2765/6717 [09:24<13:39,  4.82it/s]

Processing tickers:  41%|████      | 2766/6717 [09:25<13:36,  4.84it/s]

Processing tickers:  41%|████      | 2767/6717 [09:25<13:28,  4.89it/s]

Processing tickers:  41%|████      | 2768/6717 [09:25<13:35,  4.85it/s]

Processing tickers:  41%|████      | 2769/6717 [09:25<13:33,  4.86it/s]

Processing tickers:  41%|████      | 2770/6717 [09:25<13:25,  4.90it/s]

Processing tickers:  41%|████▏     | 2771/6717 [09:26<13:32,  4.86it/s]

Processing tickers:  41%|████▏     | 2772/6717 [09:26<13:30,  4.87it/s]

Processing tickers:  41%|████▏     | 2773/6717 [09:26<13:24,  4.90it/s]

Processing tickers:  41%|████▏     | 2774/6717 [09:26<13:42,  4.79it/s]

Processing tickers:  41%|████▏     | 2775/6717 [09:26<13:37,  4.82it/s]

Processing tickers:  41%|████▏     | 2776/6717 [09:27<13:34,  4.84it/s]

Processing tickers:  41%|████▏     | 2777/6717 [09:27<13:54,  4.72it/s]

Processing tickers:  41%|████▏     | 2778/6717 [09:27<13:42,  4.79it/s]

Processing tickers:  41%|████▏     | 2779/6717 [09:27<13:35,  4.83it/s]

Processing tickers:  41%|████▏     | 2780/6717 [09:28<13:34,  4.83it/s]

Processing tickers:  41%|████▏     | 2781/6717 [09:28<13:27,  4.88it/s]

Processing tickers:  41%|████▏     | 2782/6717 [09:28<13:21,  4.91it/s]

Processing tickers:  41%|████▏     | 2783/6717 [09:28<13:20,  4.92it/s]

Processing tickers:  41%|████▏     | 2784/6717 [09:28<13:19,  4.92it/s]

Processing tickers:  41%|████▏     | 2785/6717 [09:29<13:18,  4.92it/s]

Processing tickers:  41%|████▏     | 2786/6717 [09:29<13:17,  4.93it/s]

Processing tickers:  41%|████▏     | 2787/6717 [09:29<13:14,  4.95it/s]

Processing tickers:  42%|████▏     | 2788/6717 [09:29<13:09,  4.98it/s]

Processing tickers:  42%|████▏     | 2789/6717 [09:29<13:24,  4.88it/s]

Processing tickers:  42%|████▏     | 2790/6717 [09:30<13:17,  4.92it/s]

Processing tickers:  42%|████▏     | 2791/6717 [09:30<13:14,  4.94it/s]

Processing tickers:  42%|████▏     | 2792/6717 [09:30<13:19,  4.91it/s]

Processing tickers:  42%|████▏     | 2793/6717 [09:30<13:15,  4.93it/s]

Processing tickers:  42%|████▏     | 2794/6717 [09:30<13:17,  4.92it/s]

Processing tickers:  42%|████▏     | 2795/6717 [09:31<13:11,  4.96it/s]

Processing tickers:  42%|████▏     | 2796/6717 [09:31<13:08,  4.97it/s]

Processing tickers:  42%|████▏     | 2797/6717 [09:31<13:09,  4.96it/s]

Processing tickers:  42%|████▏     | 2798/6717 [09:31<13:08,  4.97it/s]

Processing tickers:  42%|████▏     | 2799/6717 [09:31<13:06,  4.98it/s]

Processing tickers:  42%|████▏     | 2800/6717 [09:32<13:04,  4.99it/s]

Processing tickers:  42%|████▏     | 2801/6717 [09:32<13:09,  4.96it/s]

Processing tickers:  42%|████▏     | 2802/6717 [09:32<13:07,  4.97it/s]

Processing tickers:  42%|████▏     | 2803/6717 [09:32<13:25,  4.86it/s]

Processing tickers:  42%|████▏     | 2804/6717 [09:32<13:19,  4.89it/s]

Processing tickers:  42%|████▏     | 2805/6717 [09:33<13:15,  4.92it/s]

Processing tickers:  42%|████▏     | 2806/6717 [09:33<13:12,  4.94it/s]

Processing tickers:  42%|████▏     | 2807/6717 [09:33<13:23,  4.87it/s]

Processing tickers:  42%|████▏     | 2808/6717 [09:33<13:15,  4.91it/s]

Processing tickers:  42%|████▏     | 2809/6717 [09:33<13:11,  4.94it/s]

Processing tickers:  42%|████▏     | 2810/6717 [09:34<13:04,  4.98it/s]

Processing tickers:  42%|████▏     | 2811/6717 [09:34<13:15,  4.91it/s]

Processing tickers:  42%|████▏     | 2812/6717 [09:34<13:30,  4.82it/s]

Processing tickers:  42%|████▏     | 2813/6717 [09:34<13:25,  4.85it/s]

Processing tickers:  42%|████▏     | 2814/6717 [09:34<13:26,  4.84it/s]

Processing tickers:  42%|████▏     | 2815/6717 [09:35<13:23,  4.85it/s]

Processing tickers:  42%|████▏     | 2816/6717 [09:35<13:17,  4.89it/s]

Processing tickers:  42%|████▏     | 2817/6717 [09:35<13:17,  4.89it/s]

Processing tickers:  42%|████▏     | 2818/6717 [09:35<13:09,  4.94it/s]

Processing tickers:  42%|████▏     | 2819/6717 [09:35<13:06,  4.96it/s]

Processing tickers:  42%|████▏     | 2820/6717 [09:36<13:04,  4.96it/s]

Processing tickers:  42%|████▏     | 2821/6717 [09:36<13:05,  4.96it/s]

Processing tickers:  42%|████▏     | 2822/6717 [09:36<13:05,  4.96it/s]

Processing tickers:  42%|████▏     | 2823/6717 [09:36<13:08,  4.94it/s]

Processing tickers:  42%|████▏     | 2824/6717 [09:36<13:21,  4.86it/s]

Processing tickers:  42%|████▏     | 2825/6717 [09:37<13:19,  4.87it/s]

Processing tickers:  42%|████▏     | 2826/6717 [09:37<13:14,  4.90it/s]

Processing tickers:  42%|████▏     | 2827/6717 [09:37<13:15,  4.89it/s]

Processing tickers:  42%|████▏     | 2828/6717 [09:39<47:41,  1.36it/s]

Processing tickers:  42%|████▏     | 2829/6717 [09:39<37:24,  1.73it/s]

Processing tickers:  42%|████▏     | 2830/6717 [09:39<30:08,  2.15it/s]

Processing tickers:  42%|████▏     | 2831/6717 [09:40<24:59,  2.59it/s]

Processing tickers:  42%|████▏     | 2832/6717 [09:40<21:28,  3.02it/s]

Processing tickers:  42%|████▏     | 2833/6717 [09:40<18:56,  3.42it/s]

Processing tickers:  42%|████▏     | 2834/6717 [09:40<17:08,  3.77it/s]

Processing tickers:  42%|████▏     | 2835/6717 [09:40<16:08,  4.01it/s]

Processing tickers:  42%|████▏     | 2836/6717 [09:41<15:17,  4.23it/s]

Processing tickers:  42%|████▏     | 2837/6717 [09:41<14:40,  4.41it/s]

Processing tickers:  42%|████▏     | 2838/6717 [09:41<14:30,  4.46it/s]

Processing tickers:  42%|████▏     | 2839/6717 [09:41<14:04,  4.59it/s]

Processing tickers:  42%|████▏     | 2840/6717 [09:42<13:44,  4.70it/s]

Processing tickers:  42%|████▏     | 2841/6717 [09:42<13:40,  4.72it/s]

Processing tickers:  42%|████▏     | 2842/6717 [09:42<13:27,  4.80it/s]

Processing tickers:  42%|████▏     | 2843/6717 [09:42<13:18,  4.85it/s]

Processing tickers:  42%|████▏     | 2844/6717 [09:42<13:10,  4.90it/s]

Processing tickers:  42%|████▏     | 2845/6717 [09:43<13:31,  4.77it/s]

Processing tickers:  42%|████▏     | 2846/6717 [09:43<13:30,  4.77it/s]

Processing tickers:  42%|████▏     | 2847/6717 [09:43<13:22,  4.82it/s]

Processing tickers:  42%|████▏     | 2848/6717 [09:43<13:12,  4.88it/s]

Processing tickers:  42%|████▏     | 2849/6717 [09:43<13:11,  4.88it/s]

Processing tickers:  42%|████▏     | 2850/6717 [09:44<13:15,  4.86it/s]

Processing tickers:  42%|████▏     | 2851/6717 [09:44<13:12,  4.88it/s]

Processing tickers:  42%|████▏     | 2852/6717 [09:44<13:36,  4.74it/s]

Processing tickers:  42%|████▏     | 2853/6717 [09:44<13:33,  4.75it/s]

Processing tickers:  42%|████▏     | 2854/6717 [09:44<13:42,  4.70it/s]

Processing tickers:  43%|████▎     | 2855/6717 [09:45<13:27,  4.78it/s]

Processing tickers:  43%|████▎     | 2856/6717 [09:45<13:18,  4.84it/s]

Processing tickers:  43%|████▎     | 2857/6717 [09:45<13:15,  4.85it/s]

Processing tickers:  43%|████▎     | 2858/6717 [09:45<13:14,  4.86it/s]

Processing tickers:  43%|████▎     | 2859/6717 [09:45<13:11,  4.87it/s]

Processing tickers:  43%|████▎     | 2860/6717 [09:46<13:07,  4.90it/s]

Processing tickers:  43%|████▎     | 2861/6717 [09:46<13:12,  4.87it/s]

Processing tickers:  43%|████▎     | 2862/6717 [09:46<13:01,  4.93it/s]

Processing tickers:  43%|████▎     | 2863/6717 [09:46<12:58,  4.95it/s]

Processing tickers:  43%|████▎     | 2864/6717 [09:46<12:56,  4.96it/s]

Processing tickers:  43%|████▎     | 2865/6717 [09:47<13:08,  4.88it/s]

Processing tickers:  43%|████▎     | 2866/6717 [09:47<13:15,  4.84it/s]

Processing tickers:  43%|████▎     | 2867/6717 [09:47<13:08,  4.89it/s]

Processing tickers:  43%|████▎     | 2868/6717 [09:47<13:03,  4.91it/s]

Processing tickers:  43%|████▎     | 2869/6717 [09:47<13:06,  4.89it/s]

Processing tickers:  43%|████▎     | 2870/6717 [09:48<13:16,  4.83it/s]

Processing tickers:  43%|████▎     | 2871/6717 [09:48<13:32,  4.74it/s]

Processing tickers:  43%|████▎     | 2872/6717 [09:48<13:32,  4.73it/s]

Processing tickers:  43%|████▎     | 2873/6717 [09:48<13:28,  4.76it/s]

Processing tickers:  43%|████▎     | 2874/6717 [09:49<13:16,  4.82it/s]

Processing tickers:  43%|████▎     | 2875/6717 [09:49<13:05,  4.89it/s]

Processing tickers:  43%|████▎     | 2876/6717 [09:49<13:07,  4.88it/s]

Processing tickers:  43%|████▎     | 2877/6717 [09:49<13:06,  4.88it/s]

Processing tickers:  43%|████▎     | 2878/6717 [09:49<13:13,  4.84it/s]

Processing tickers:  43%|████▎     | 2879/6717 [09:50<13:07,  4.87it/s]

Processing tickers:  43%|████▎     | 2880/6717 [09:50<13:01,  4.91it/s]

Processing tickers:  43%|████▎     | 2881/6717 [09:50<12:54,  4.96it/s]

Processing tickers:  43%|████▎     | 2882/6717 [09:50<12:49,  4.99it/s]

Processing tickers:  43%|████▎     | 2883/6717 [09:50<12:51,  4.97it/s]

Processing tickers:  43%|████▎     | 2884/6717 [09:51<12:52,  4.96it/s]

Processing tickers:  43%|████▎     | 2885/6717 [09:51<12:50,  4.97it/s]

Processing tickers:  43%|████▎     | 2886/6717 [09:51<13:16,  4.81it/s]

Processing tickers:  43%|████▎     | 2887/6717 [09:51<13:05,  4.87it/s]

Processing tickers:  43%|████▎     | 2888/6717 [09:51<13:05,  4.87it/s]

Processing tickers:  43%|████▎     | 2889/6717 [09:52<13:01,  4.90it/s]

Processing tickers:  43%|████▎     | 2890/6717 [09:52<13:23,  4.76it/s]

Processing tickers:  43%|████▎     | 2891/6717 [09:52<13:39,  4.67it/s]

Processing tickers:  43%|████▎     | 2892/6717 [09:52<13:20,  4.78it/s]

Processing tickers:  43%|████▎     | 2893/6717 [09:52<13:14,  4.82it/s]

Processing tickers:  43%|████▎     | 2894/6717 [09:53<13:28,  4.73it/s]

Processing tickers:  43%|████▎     | 2895/6717 [09:53<13:17,  4.79it/s]

Processing tickers:  43%|████▎     | 2896/6717 [09:53<13:12,  4.82it/s]

Processing tickers:  43%|████▎     | 2897/6717 [09:53<13:06,  4.86it/s]

Processing tickers:  43%|████▎     | 2898/6717 [09:53<13:07,  4.85it/s]

Processing tickers:  43%|████▎     | 2899/6717 [09:54<12:59,  4.90it/s]

Processing tickers:  43%|████▎     | 2900/6717 [09:54<12:57,  4.91it/s]

Processing tickers:  43%|████▎     | 2901/6717 [09:54<12:53,  4.93it/s]

Processing tickers:  43%|████▎     | 2902/6717 [09:54<12:55,  4.92it/s]

Processing tickers:  43%|████▎     | 2903/6717 [09:54<12:53,  4.93it/s]

Processing tickers:  43%|████▎     | 2904/6717 [09:55<12:49,  4.95it/s]

Processing tickers:  43%|████▎     | 2905/6717 [09:55<12:45,  4.98it/s]

Processing tickers:  43%|████▎     | 2906/6717 [09:55<12:45,  4.98it/s]

Processing tickers:  43%|████▎     | 2907/6717 [09:55<12:47,  4.96it/s]

Processing tickers:  43%|████▎     | 2908/6717 [09:55<12:44,  4.98it/s]

Processing tickers:  43%|████▎     | 2909/6717 [09:56<12:44,  4.98it/s]

Processing tickers:  43%|████▎     | 2910/6717 [09:56<12:43,  4.98it/s]

Processing tickers:  43%|████▎     | 2911/6717 [09:56<12:48,  4.95it/s]

Processing tickers:  43%|████▎     | 2912/6717 [09:56<12:53,  4.92it/s]

Processing tickers:  43%|████▎     | 2913/6717 [09:56<12:54,  4.91it/s]

Processing tickers:  43%|████▎     | 2914/6717 [09:57<12:46,  4.96it/s]

Processing tickers:  43%|████▎     | 2915/6717 [09:57<12:44,  4.97it/s]

Processing tickers:  43%|████▎     | 2916/6717 [09:57<12:45,  4.96it/s]

Processing tickers:  43%|████▎     | 2917/6717 [09:57<12:49,  4.94it/s]

Processing tickers:  43%|████▎     | 2918/6717 [09:57<12:46,  4.96it/s]

Processing tickers:  43%|████▎     | 2919/6717 [09:58<12:44,  4.97it/s]

Processing tickers:  43%|████▎     | 2920/6717 [09:58<12:43,  4.97it/s]

Processing tickers:  43%|████▎     | 2921/6717 [09:58<12:43,  4.97it/s]

Processing tickers:  44%|████▎     | 2922/6717 [09:58<12:42,  4.98it/s]

Processing tickers:  44%|████▎     | 2923/6717 [09:59<12:46,  4.95it/s]

Processing tickers:  44%|████▎     | 2924/6717 [09:59<12:49,  4.93it/s]

Processing tickers:  44%|████▎     | 2925/6717 [09:59<12:49,  4.93it/s]

Processing tickers:  44%|████▎     | 2926/6717 [09:59<12:46,  4.94it/s]

Processing tickers:  44%|████▎     | 2927/6717 [09:59<12:46,  4.94it/s]

Processing tickers:  44%|████▎     | 2928/6717 [10:00<12:44,  4.96it/s]

Processing tickers:  44%|████▎     | 2929/6717 [10:00<12:43,  4.96it/s]

Processing tickers:  44%|████▎     | 2930/6717 [10:00<12:52,  4.91it/s]

Processing tickers:  44%|████▎     | 2931/6717 [10:00<12:48,  4.92it/s]

Processing tickers:  44%|████▎     | 2932/6717 [10:00<12:56,  4.88it/s]

Processing tickers:  44%|████▎     | 2933/6717 [10:01<12:53,  4.89it/s]

Processing tickers:  44%|████▎     | 2934/6717 [10:01<13:08,  4.80it/s]

Processing tickers:  44%|████▎     | 2935/6717 [10:01<13:02,  4.83it/s]

Processing tickers:  44%|████▎     | 2936/6717 [10:01<12:55,  4.87it/s]

Processing tickers:  44%|████▎     | 2937/6717 [10:01<12:52,  4.89it/s]

Processing tickers:  44%|████▎     | 2938/6717 [10:02<12:50,  4.90it/s]

Processing tickers:  44%|████▍     | 2939/6717 [10:02<12:45,  4.94it/s]

Processing tickers:  44%|████▍     | 2940/6717 [10:02<12:53,  4.89it/s]

Processing tickers:  44%|████▍     | 2941/6717 [10:02<12:46,  4.93it/s]

Processing tickers:  44%|████▍     | 2942/6717 [10:02<12:45,  4.93it/s]

Processing tickers:  44%|████▍     | 2943/6717 [10:03<12:43,  4.94it/s]

Processing tickers:  44%|████▍     | 2944/6717 [10:03<12:46,  4.92it/s]

Processing tickers:  44%|████▍     | 2945/6717 [10:03<12:58,  4.85it/s]

Processing tickers:  44%|████▍     | 2946/6717 [10:03<13:17,  4.73it/s]

Processing tickers:  44%|████▍     | 2947/6717 [10:03<13:03,  4.81it/s]

Processing tickers:  44%|████▍     | 2948/6717 [10:04<12:55,  4.86it/s]

Processing tickers:  44%|████▍     | 2949/6717 [10:04<12:55,  4.86it/s]

Processing tickers:  44%|████▍     | 2950/6717 [10:04<12:57,  4.85it/s]

Processing tickers:  44%|████▍     | 2951/6717 [10:04<12:57,  4.84it/s]

Processing tickers:  44%|████▍     | 2952/6717 [10:04<12:56,  4.85it/s]

Processing tickers:  44%|████▍     | 2953/6717 [10:05<12:53,  4.87it/s]

Processing tickers:  44%|████▍     | 2954/6717 [10:05<12:45,  4.91it/s]

Processing tickers:  44%|████▍     | 2955/6717 [10:05<12:49,  4.89it/s]

Processing tickers:  44%|████▍     | 2956/6717 [10:05<12:47,  4.90it/s]

Processing tickers:  44%|████▍     | 2957/6717 [10:05<12:49,  4.89it/s]

Processing tickers:  44%|████▍     | 2958/6717 [10:06<12:42,  4.93it/s]

Processing tickers:  44%|████▍     | 2959/6717 [10:06<12:47,  4.89it/s]

Processing tickers:  44%|████▍     | 2960/6717 [10:06<12:48,  4.89it/s]

Processing tickers:  44%|████▍     | 2961/6717 [10:06<12:48,  4.89it/s]

Processing tickers:  44%|████▍     | 2962/6717 [10:06<12:44,  4.91it/s]

Processing tickers:  44%|████▍     | 2963/6717 [10:07<12:38,  4.95it/s]

Processing tickers:  44%|████▍     | 2964/6717 [10:07<12:36,  4.96it/s]

Processing tickers:  44%|████▍     | 2965/6717 [10:07<12:47,  4.89it/s]

Processing tickers:  44%|████▍     | 2966/6717 [10:07<12:52,  4.86it/s]

Processing tickers:  44%|████▍     | 2967/6717 [10:08<12:50,  4.87it/s]

Processing tickers:  44%|████▍     | 2968/6717 [10:08<12:42,  4.92it/s]

Processing tickers:  44%|████▍     | 2969/6717 [10:08<12:38,  4.94it/s]

Processing tickers:  44%|████▍     | 2970/6717 [10:08<12:32,  4.98it/s]

Processing tickers:  44%|████▍     | 2971/6717 [10:08<12:33,  4.97it/s]

Processing tickers:  44%|████▍     | 2972/6717 [10:09<12:35,  4.96it/s]

Processing tickers:  44%|████▍     | 2973/6717 [10:09<12:46,  4.88it/s]

Processing tickers:  44%|████▍     | 2974/6717 [10:09<13:02,  4.78it/s]

Processing tickers:  44%|████▍     | 2975/6717 [10:09<12:58,  4.80it/s]

Processing tickers:  44%|████▍     | 2976/6717 [10:09<12:52,  4.84it/s]

Processing tickers:  44%|████▍     | 2977/6717 [10:10<12:50,  4.85it/s]

Processing tickers:  44%|████▍     | 2978/6717 [10:10<12:44,  4.89it/s]

Processing tickers:  44%|████▍     | 2979/6717 [10:10<12:41,  4.91it/s]

Processing tickers:  44%|████▍     | 2980/6717 [10:10<12:48,  4.86it/s]

Processing tickers:  44%|████▍     | 2981/6717 [10:10<12:46,  4.87it/s]

Processing tickers:  44%|████▍     | 2982/6717 [10:11<12:40,  4.91it/s]

Processing tickers:  44%|████▍     | 2983/6717 [10:11<12:45,  4.88it/s]

Processing tickers:  44%|████▍     | 2984/6717 [10:11<12:37,  4.93it/s]

Processing tickers:  44%|████▍     | 2985/6717 [10:11<12:36,  4.94it/s]

Processing tickers:  44%|████▍     | 2986/6717 [10:11<12:35,  4.94it/s]

Processing tickers:  44%|████▍     | 2987/6717 [10:12<12:36,  4.93it/s]

Processing tickers:  44%|████▍     | 2988/6717 [10:12<12:42,  4.89it/s]

Processing tickers:  44%|████▍     | 2989/6717 [10:12<12:45,  4.87it/s]

Processing tickers:  45%|████▍     | 2990/6717 [10:12<12:39,  4.90it/s]

Processing tickers:  45%|████▍     | 2991/6717 [10:12<13:09,  4.72it/s]

Processing tickers:  45%|████▍     | 2992/6717 [10:13<12:57,  4.79it/s]

Processing tickers:  45%|████▍     | 2993/6717 [10:13<12:48,  4.85it/s]

Processing tickers:  45%|████▍     | 2994/6717 [10:13<12:45,  4.86it/s]

Processing tickers:  45%|████▍     | 2995/6717 [10:13<12:47,  4.85it/s]

Processing tickers:  45%|████▍     | 2996/6717 [10:13<12:46,  4.85it/s]

Processing tickers:  45%|████▍     | 2997/6717 [10:14<12:49,  4.83it/s]

Processing tickers:  45%|████▍     | 2998/6717 [10:14<12:42,  4.88it/s]

Processing tickers:  45%|████▍     | 2999/6717 [10:14<12:38,  4.90it/s]

Processing tickers:  45%|████▍     | 3000/6717 [10:14<12:42,  4.87it/s]

Processing tickers:  45%|████▍     | 3001/6717 [10:14<12:38,  4.90it/s]

Processing tickers:  45%|████▍     | 3002/6717 [10:15<12:32,  4.94it/s]

Processing tickers:  45%|████▍     | 3003/6717 [10:15<12:30,  4.95it/s]

Processing tickers:  45%|████▍     | 3004/6717 [10:15<12:41,  4.88it/s]

Processing tickers:  45%|████▍     | 3005/6717 [10:15<12:41,  4.88it/s]

Processing tickers:  45%|████▍     | 3006/6717 [10:15<12:39,  4.89it/s]

Processing tickers:  45%|████▍     | 3007/6717 [10:16<12:43,  4.86it/s]

Processing tickers:  45%|████▍     | 3008/6717 [10:16<12:36,  4.90it/s]

Processing tickers:  45%|████▍     | 3009/6717 [10:16<12:33,  4.92it/s]

Processing tickers:  45%|████▍     | 3010/6717 [10:16<12:33,  4.92it/s]

Processing tickers:  45%|████▍     | 3011/6717 [10:17<12:41,  4.87it/s]

Processing tickers:  45%|████▍     | 3012/6717 [10:17<12:33,  4.92it/s]

Processing tickers:  45%|████▍     | 3013/6717 [10:17<12:29,  4.94it/s]

Processing tickers:  45%|████▍     | 3014/6717 [10:17<12:28,  4.94it/s]

Processing tickers:  45%|████▍     | 3015/6717 [10:17<12:31,  4.93it/s]

Processing tickers:  45%|████▍     | 3016/6717 [10:18<12:29,  4.94it/s]

Processing tickers:  45%|████▍     | 3017/6717 [10:18<12:43,  4.85it/s]

Processing tickers:  45%|████▍     | 3018/6717 [10:18<12:33,  4.91it/s]

Processing tickers:  45%|████▍     | 3019/6717 [10:18<12:37,  4.88it/s]

Processing tickers:  45%|████▍     | 3020/6717 [10:18<12:44,  4.83it/s]

Processing tickers:  45%|████▍     | 3021/6717 [10:19<12:45,  4.83it/s]

Processing tickers:  45%|████▍     | 3022/6717 [10:19<12:41,  4.85it/s]

Processing tickers:  45%|████▌     | 3023/6717 [10:19<12:48,  4.81it/s]

Processing tickers:  45%|████▌     | 3024/6717 [10:19<12:47,  4.81it/s]

Processing tickers:  45%|████▌     | 3025/6717 [10:19<12:37,  4.87it/s]

Processing tickers:  45%|████▌     | 3026/6717 [10:20<12:37,  4.87it/s]

Processing tickers:  45%|████▌     | 3027/6717 [10:20<12:36,  4.88it/s]

Processing tickers:  45%|████▌     | 3028/6717 [10:20<12:40,  4.85it/s]

Processing tickers:  45%|████▌     | 3029/6717 [10:20<12:36,  4.88it/s]

Processing tickers:  45%|████▌     | 3030/6717 [10:20<12:40,  4.85it/s]

Processing tickers:  45%|████▌     | 3031/6717 [10:21<12:34,  4.89it/s]

Processing tickers:  45%|████▌     | 3032/6717 [10:21<12:34,  4.88it/s]

Processing tickers:  45%|████▌     | 3033/6717 [10:21<12:34,  4.88it/s]

Processing tickers:  45%|████▌     | 3034/6717 [10:21<12:32,  4.90it/s]

Processing tickers:  45%|████▌     | 3035/6717 [10:21<12:27,  4.92it/s]

Processing tickers:  45%|████▌     | 3036/6717 [10:22<12:25,  4.93it/s]

Processing tickers:  45%|████▌     | 3037/6717 [10:22<12:29,  4.91it/s]

Processing tickers:  45%|████▌     | 3038/6717 [10:22<12:20,  4.97it/s]

Processing tickers:  45%|████▌     | 3039/6717 [10:22<12:23,  4.95it/s]

Processing tickers:  45%|████▌     | 3040/6717 [10:22<12:33,  4.88it/s]

Processing tickers:  45%|████▌     | 3041/6717 [10:23<12:35,  4.87it/s]

Processing tickers:  45%|████▌     | 3042/6717 [10:23<12:30,  4.90it/s]

Processing tickers:  45%|████▌     | 3043/6717 [10:23<12:28,  4.91it/s]

Processing tickers:  45%|████▌     | 3044/6717 [10:23<12:30,  4.89it/s]

Processing tickers:  45%|████▌     | 3045/6717 [10:23<12:32,  4.88it/s]

Processing tickers:  45%|████▌     | 3046/6717 [10:24<12:26,  4.92it/s]

Processing tickers:  45%|████▌     | 3047/6717 [10:24<12:23,  4.94it/s]

Processing tickers:  45%|████▌     | 3048/6717 [10:24<12:25,  4.92it/s]

Processing tickers:  45%|████▌     | 3049/6717 [10:24<12:24,  4.93it/s]

Processing tickers:  45%|████▌     | 3050/6717 [10:24<12:34,  4.86it/s]

Processing tickers:  45%|████▌     | 3051/6717 [10:25<12:39,  4.83it/s]

Processing tickers:  45%|████▌     | 3052/6717 [10:25<12:32,  4.87it/s]

Processing tickers:  45%|████▌     | 3053/6717 [10:25<12:35,  4.85it/s]

Processing tickers:  45%|████▌     | 3054/6717 [10:25<12:31,  4.87it/s]

Processing tickers:  45%|████▌     | 3055/6717 [10:26<12:27,  4.90it/s]

Processing tickers:  45%|████▌     | 3056/6717 [10:26<12:23,  4.92it/s]

Processing tickers:  46%|████▌     | 3057/6717 [10:26<12:16,  4.97it/s]

Processing tickers:  46%|████▌     | 3058/6717 [10:26<12:26,  4.90it/s]

Processing tickers:  46%|████▌     | 3059/6717 [10:26<12:24,  4.92it/s]

Processing tickers:  46%|████▌     | 3060/6717 [10:27<12:26,  4.90it/s]

Processing tickers:  46%|████▌     | 3061/6717 [10:27<12:24,  4.91it/s]

Processing tickers:  46%|████▌     | 3062/6717 [10:27<12:29,  4.88it/s]

Processing tickers:  46%|████▌     | 3063/6717 [10:27<12:33,  4.85it/s]

Processing tickers:  46%|████▌     | 3064/6717 [10:27<12:26,  4.89it/s]

Processing tickers:  46%|████▌     | 3065/6717 [10:28<12:28,  4.88it/s]

Processing tickers:  46%|████▌     | 3066/6717 [10:28<12:37,  4.82it/s]

Processing tickers:  46%|████▌     | 3067/6717 [10:28<12:33,  4.85it/s]

Processing tickers:  46%|████▌     | 3068/6717 [10:28<12:31,  4.86it/s]

Processing tickers:  46%|████▌     | 3069/6717 [10:28<12:29,  4.87it/s]

Processing tickers:  46%|████▌     | 3070/6717 [10:29<12:26,  4.88it/s]

Processing tickers:  46%|████▌     | 3071/6717 [10:29<12:47,  4.75it/s]

Processing tickers:  46%|████▌     | 3072/6717 [10:29<12:49,  4.74it/s]

Processing tickers:  46%|████▌     | 3073/6717 [10:29<12:41,  4.78it/s]

Processing tickers:  46%|████▌     | 3074/6717 [10:29<12:31,  4.84it/s]

Processing tickers:  46%|████▌     | 3075/6717 [10:30<12:28,  4.86it/s]

Processing tickers:  46%|████▌     | 3076/6717 [10:30<12:50,  4.72it/s]

Processing tickers:  46%|████▌     | 3077/6717 [10:30<12:39,  4.79it/s]

Processing tickers:  46%|████▌     | 3078/6717 [10:30<12:32,  4.84it/s]

Processing tickers:  46%|████▌     | 3079/6717 [10:30<12:27,  4.87it/s]

Processing tickers:  46%|████▌     | 3080/6717 [10:31<12:21,  4.90it/s]

Processing tickers:  46%|████▌     | 3081/6717 [10:31<12:30,  4.84it/s]

Processing tickers:  46%|████▌     | 3082/6717 [10:31<12:28,  4.86it/s]

Processing tickers:  46%|████▌     | 3083/6717 [10:31<12:22,  4.90it/s]

Processing tickers:  46%|████▌     | 3084/6717 [10:31<12:21,  4.90it/s]

Processing tickers:  46%|████▌     | 3085/6717 [10:32<12:17,  4.93it/s]

Processing tickers:  46%|████▌     | 3086/6717 [10:32<12:40,  4.77it/s]

Processing tickers:  46%|████▌     | 3087/6717 [10:32<12:34,  4.81it/s]

Processing tickers:  46%|████▌     | 3088/6717 [10:32<12:25,  4.87it/s]

Processing tickers:  46%|████▌     | 3089/6717 [10:33<12:17,  4.92it/s]

Processing tickers:  46%|████▌     | 3090/6717 [10:33<12:15,  4.93it/s]

Processing tickers:  46%|████▌     | 3091/6717 [10:33<12:10,  4.96it/s]

Processing tickers:  46%|████▌     | 3092/6717 [10:33<12:22,  4.88it/s]

Processing tickers:  46%|████▌     | 3093/6717 [10:33<12:16,  4.92it/s]

Processing tickers:  46%|████▌     | 3094/6717 [10:34<12:17,  4.92it/s]

Processing tickers:  46%|████▌     | 3095/6717 [10:34<12:16,  4.91it/s]

Processing tickers:  46%|████▌     | 3096/6717 [10:34<12:24,  4.86it/s]

Processing tickers:  46%|████▌     | 3097/6717 [10:34<12:24,  4.87it/s]

Processing tickers:  46%|████▌     | 3098/6717 [10:34<12:21,  4.88it/s]

Processing tickers:  46%|████▌     | 3099/6717 [10:35<12:18,  4.90it/s]

Processing tickers:  46%|████▌     | 3100/6717 [10:35<12:16,  4.91it/s]

Processing tickers:  46%|████▌     | 3101/6717 [10:35<12:28,  4.83it/s]

Processing tickers:  46%|████▌     | 3102/6717 [10:35<12:19,  4.89it/s]

Processing tickers:  46%|████▌     | 3103/6717 [10:35<12:22,  4.86it/s]

Processing tickers:  46%|████▌     | 3104/6717 [10:36<12:20,  4.88it/s]

Processing tickers:  46%|████▌     | 3105/6717 [10:36<12:13,  4.92it/s]

Processing tickers:  46%|████▌     | 3106/6717 [10:36<12:25,  4.84it/s]

Processing tickers:  46%|████▋     | 3107/6717 [10:36<12:27,  4.83it/s]

Processing tickers:  46%|████▋     | 3108/6717 [10:36<12:25,  4.84it/s]

Processing tickers:  46%|████▋     | 3109/6717 [10:37<12:17,  4.89it/s]

Processing tickers:  46%|████▋     | 3110/6717 [10:37<12:15,  4.90it/s]

Processing tickers:  46%|████▋     | 3111/6717 [10:37<12:21,  4.86it/s]

Processing tickers:  46%|████▋     | 3112/6717 [10:37<12:20,  4.87it/s]

Processing tickers:  46%|████▋     | 3113/6717 [10:37<12:36,  4.77it/s]

Processing tickers:  46%|████▋     | 3114/6717 [10:38<12:45,  4.71it/s]

Processing tickers:  46%|████▋     | 3115/6717 [10:38<12:36,  4.76it/s]

Processing tickers:  46%|████▋     | 3116/6717 [10:38<12:31,  4.79it/s]

Processing tickers:  46%|████▋     | 3117/6717 [10:38<12:23,  4.84it/s]

Processing tickers:  46%|████▋     | 3118/6717 [10:38<12:17,  4.88it/s]

Processing tickers:  46%|████▋     | 3119/6717 [10:39<12:10,  4.93it/s]

Processing tickers:  46%|████▋     | 3120/6717 [10:39<12:06,  4.95it/s]

Processing tickers:  46%|████▋     | 3121/6717 [10:39<12:08,  4.94it/s]

Processing tickers:  46%|████▋     | 3122/6717 [10:39<12:07,  4.94it/s]

Processing tickers:  46%|████▋     | 3123/6717 [10:39<12:04,  4.96it/s]

Processing tickers:  47%|████▋     | 3124/6717 [10:40<12:07,  4.94it/s]

Processing tickers:  47%|████▋     | 3125/6717 [10:40<12:12,  4.90it/s]

Processing tickers:  47%|████▋     | 3126/6717 [10:40<12:36,  4.75it/s]

Processing tickers:  47%|████▋     | 3127/6717 [10:40<12:24,  4.82it/s]

Processing tickers:  47%|████▋     | 3128/6717 [10:41<12:18,  4.86it/s]

Processing tickers:  47%|████▋     | 3129/6717 [10:41<12:17,  4.87it/s]

Processing tickers:  47%|████▋     | 3130/6717 [10:41<12:09,  4.91it/s]

Processing tickers:  47%|████▋     | 3131/6717 [10:41<12:12,  4.90it/s]

Processing tickers:  47%|████▋     | 3132/6717 [10:41<12:12,  4.89it/s]

Processing tickers:  47%|████▋     | 3133/6717 [10:42<12:06,  4.94it/s]

Processing tickers:  47%|████▋     | 3134/6717 [10:42<12:03,  4.95it/s]

Processing tickers:  47%|████▋     | 3135/6717 [10:42<12:02,  4.96it/s]

Processing tickers:  47%|████▋     | 3136/6717 [10:42<12:03,  4.95it/s]

Processing tickers:  47%|████▋     | 3137/6717 [10:42<12:01,  4.96it/s]

Processing tickers:  47%|████▋     | 3138/6717 [10:43<12:00,  4.97it/s]

Processing tickers:  47%|████▋     | 3139/6717 [10:43<12:01,  4.96it/s]

Processing tickers:  47%|████▋     | 3140/6717 [10:43<12:03,  4.94it/s]

Processing tickers:  47%|████▋     | 3141/6717 [10:43<12:02,  4.95it/s]

Processing tickers:  47%|████▋     | 3142/6717 [10:43<12:00,  4.96it/s]

Processing tickers:  47%|████▋     | 3143/6717 [10:44<11:58,  4.97it/s]

Processing tickers:  47%|████▋     | 3144/6717 [10:44<12:04,  4.93it/s]

Processing tickers:  47%|████▋     | 3145/6717 [10:44<12:06,  4.92it/s]

Processing tickers:  47%|████▋     | 3146/6717 [10:44<12:02,  4.94it/s]

Processing tickers:  47%|████▋     | 3147/6717 [10:44<12:02,  4.94it/s]

Processing tickers:  47%|████▋     | 3148/6717 [10:45<11:59,  4.96it/s]

Processing tickers:  47%|████▋     | 3149/6717 [10:45<11:59,  4.96it/s]

Processing tickers:  47%|████▋     | 3150/6717 [10:45<12:00,  4.95it/s]

Processing tickers:  47%|████▋     | 3151/6717 [10:45<11:59,  4.96it/s]

Processing tickers:  47%|████▋     | 3152/6717 [10:45<12:00,  4.95it/s]

Processing tickers:  47%|████▋     | 3153/6717 [10:46<11:57,  4.97it/s]

Processing tickers:  47%|████▋     | 3154/6717 [10:46<11:53,  4.99it/s]

Processing tickers:  47%|████▋     | 3155/6717 [10:46<11:52,  5.00it/s]

Processing tickers:  47%|████▋     | 3156/6717 [10:46<12:16,  4.83it/s]

Processing tickers:  47%|████▋     | 3157/6717 [10:46<12:12,  4.86it/s]

Processing tickers:  47%|████▋     | 3158/6717 [10:47<12:07,  4.89it/s]

Processing tickers:  47%|████▋     | 3159/6717 [10:47<12:14,  4.84it/s]

Processing tickers:  47%|████▋     | 3160/6717 [10:47<12:18,  4.82it/s]

Processing tickers:  47%|████▋     | 3161/6717 [10:47<12:12,  4.86it/s]

Processing tickers:  47%|████▋     | 3162/6717 [10:47<12:06,  4.89it/s]

Processing tickers:  47%|████▋     | 3163/6717 [10:48<12:02,  4.92it/s]

Processing tickers:  47%|████▋     | 3164/6717 [10:48<12:05,  4.89it/s]

Processing tickers:  47%|████▋     | 3165/6717 [10:48<12:14,  4.84it/s]

Processing tickers:  47%|████▋     | 3166/6717 [10:48<12:07,  4.88it/s]

Processing tickers:  47%|████▋     | 3167/6717 [10:48<12:08,  4.88it/s]

Processing tickers:  47%|████▋     | 3168/6717 [10:49<12:05,  4.89it/s]

Processing tickers:  47%|████▋     | 3169/6717 [10:49<12:03,  4.90it/s]

Processing tickers:  47%|████▋     | 3170/6717 [10:49<12:02,  4.91it/s]

Processing tickers:  47%|████▋     | 3171/6717 [10:49<12:01,  4.92it/s]

Processing tickers:  47%|████▋     | 3172/6717 [10:49<11:58,  4.93it/s]

Processing tickers:  47%|████▋     | 3173/6717 [10:50<11:58,  4.93it/s]

Processing tickers:  47%|████▋     | 3174/6717 [10:50<12:03,  4.90it/s]

Processing tickers:  47%|████▋     | 3175/6717 [10:50<12:03,  4.90it/s]

Processing tickers:  47%|████▋     | 3176/6717 [10:50<12:02,  4.90it/s]

Processing tickers:  47%|████▋     | 3177/6717 [10:50<12:00,  4.91it/s]

Processing tickers:  47%|████▋     | 3178/6717 [10:51<11:56,  4.94it/s]

Processing tickers:  47%|████▋     | 3179/6717 [10:51<11:57,  4.93it/s]

Processing tickers:  47%|████▋     | 3180/6717 [10:51<11:55,  4.94it/s]

Processing tickers:  47%|████▋     | 3181/6717 [10:51<12:25,  4.74it/s]

Processing tickers:  47%|████▋     | 3182/6717 [10:52<12:24,  4.75it/s]

Processing tickers:  47%|████▋     | 3183/6717 [10:52<12:11,  4.83it/s]

Processing tickers:  47%|████▋     | 3184/6717 [10:52<12:06,  4.86it/s]

Processing tickers:  47%|████▋     | 3185/6717 [10:52<11:58,  4.92it/s]

Processing tickers:  47%|████▋     | 3186/6717 [10:52<11:54,  4.94it/s]

Processing tickers:  47%|████▋     | 3187/6717 [10:53<11:54,  4.94it/s]

Processing tickers:  47%|████▋     | 3188/6717 [10:53<11:54,  4.94it/s]

Processing tickers:  47%|████▋     | 3189/6717 [10:53<11:50,  4.96it/s]

Processing tickers:  47%|████▋     | 3190/6717 [10:53<11:51,  4.95it/s]

Processing tickers:  48%|████▊     | 3191/6717 [10:53<11:52,  4.95it/s]

Processing tickers:  48%|████▊     | 3192/6717 [10:54<11:49,  4.97it/s]

Processing tickers:  48%|████▊     | 3193/6717 [10:54<11:50,  4.96it/s]

Processing tickers:  48%|████▊     | 3194/6717 [10:54<12:01,  4.88it/s]

Processing tickers:  48%|████▊     | 3195/6717 [10:54<12:00,  4.89it/s]

Processing tickers:  48%|████▊     | 3196/6717 [10:54<12:06,  4.85it/s]

Processing tickers:  48%|████▊     | 3197/6717 [10:55<12:22,  4.74it/s]

Processing tickers:  48%|████▊     | 3198/6717 [10:55<12:08,  4.83it/s]

Processing tickers:  48%|████▊     | 3199/6717 [10:55<12:37,  4.64it/s]

Processing tickers:  48%|████▊     | 3200/6717 [10:55<12:23,  4.73it/s]

Processing tickers:  48%|████▊     | 3201/6717 [10:55<12:22,  4.73it/s]

Processing tickers:  48%|████▊     | 3202/6717 [10:56<12:11,  4.80it/s]

Processing tickers:  48%|████▊     | 3203/6717 [10:56<12:12,  4.80it/s]

Processing tickers:  48%|████▊     | 3204/6717 [10:56<12:07,  4.83it/s]

Processing tickers:  48%|████▊     | 3205/6717 [10:56<12:03,  4.85it/s]

Processing tickers:  48%|████▊     | 3206/6717 [10:56<11:57,  4.90it/s]

Processing tickers:  48%|████▊     | 3207/6717 [10:57<11:52,  4.93it/s]

Processing tickers:  48%|████▊     | 3208/6717 [10:57<11:50,  4.94it/s]

Processing tickers:  48%|████▊     | 3209/6717 [10:57<11:53,  4.92it/s]

Processing tickers:  48%|████▊     | 3210/6717 [10:57<11:49,  4.95it/s]

Processing tickers:  48%|████▊     | 3211/6717 [10:57<11:43,  4.98it/s]

Processing tickers:  48%|████▊     | 3212/6717 [10:58<11:42,  4.99it/s]

Processing tickers:  48%|████▊     | 3213/6717 [10:58<11:40,  5.00it/s]

Processing tickers:  48%|████▊     | 3214/6717 [10:58<11:40,  5.00it/s]

Processing tickers:  48%|████▊     | 3215/6717 [10:58<11:38,  5.01it/s]

Processing tickers:  48%|████▊     | 3216/6717 [10:58<11:42,  4.98it/s]

Processing tickers:  48%|████▊     | 3217/6717 [10:59<11:44,  4.97it/s]

Processing tickers:  48%|████▊     | 3218/6717 [10:59<11:40,  4.99it/s]

Processing tickers:  48%|████▊     | 3219/6717 [10:59<11:44,  4.97it/s]

Processing tickers:  48%|████▊     | 3220/6717 [10:59<11:44,  4.96it/s]

Processing tickers:  48%|████▊     | 3221/6717 [10:59<11:47,  4.94it/s]

Processing tickers:  48%|████▊     | 3222/6717 [11:00<11:48,  4.93it/s]

Processing tickers:  48%|████▊     | 3223/6717 [11:00<11:50,  4.92it/s]

Processing tickers:  48%|████▊     | 3224/6717 [11:00<11:46,  4.95it/s]

Processing tickers:  48%|████▊     | 3225/6717 [11:00<11:46,  4.94it/s]

Processing tickers:  48%|████▊     | 3226/6717 [11:00<11:47,  4.94it/s]

Processing tickers:  48%|████▊     | 3227/6717 [11:01<11:47,  4.93it/s]

Processing tickers:  48%|████▊     | 3228/6717 [11:01<11:47,  4.93it/s]

Processing tickers:  48%|████▊     | 3229/6717 [11:01<11:46,  4.94it/s]

Processing tickers:  48%|████▊     | 3230/6717 [11:01<11:44,  4.95it/s]

Processing tickers:  48%|████▊     | 3231/6717 [11:01<11:42,  4.96it/s]

Processing tickers:  48%|████▊     | 3232/6717 [11:02<11:44,  4.95it/s]

Processing tickers:  48%|████▊     | 3233/6717 [11:02<11:43,  4.95it/s]

Processing tickers:  48%|████▊     | 3234/6717 [11:02<11:42,  4.96it/s]

Processing tickers:  48%|████▊     | 3235/6717 [11:02<11:43,  4.95it/s]

Processing tickers:  48%|████▊     | 3236/6717 [11:02<11:40,  4.97it/s]

Processing tickers:  48%|████▊     | 3237/6717 [11:03<11:38,  4.98it/s]

Processing tickers:  48%|████▊     | 3238/6717 [11:03<11:55,  4.86it/s]

Processing tickers:  48%|████▊     | 3239/6717 [11:03<11:51,  4.89it/s]

Processing tickers:  48%|████▊     | 3240/6717 [11:03<11:48,  4.91it/s]

Processing tickers:  48%|████▊     | 3241/6717 [11:04<11:48,  4.90it/s]

Processing tickers:  48%|████▊     | 3242/6717 [11:04<12:08,  4.77it/s]

Processing tickers:  48%|████▊     | 3243/6717 [11:04<12:01,  4.81it/s]

Processing tickers:  48%|████▊     | 3244/6717 [11:04<11:58,  4.84it/s]

Processing tickers:  48%|████▊     | 3245/6717 [11:04<11:53,  4.86it/s]

Processing tickers:  48%|████▊     | 3246/6717 [11:05<11:51,  4.88it/s]

Processing tickers:  48%|████▊     | 3247/6717 [11:05<11:47,  4.90it/s]

Processing tickers:  48%|████▊     | 3248/6717 [11:05<11:44,  4.92it/s]

Processing tickers:  48%|████▊     | 3249/6717 [11:05<11:43,  4.93it/s]

Processing tickers:  48%|████▊     | 3250/6717 [11:05<11:46,  4.91it/s]

Processing tickers:  48%|████▊     | 3251/6717 [11:06<11:52,  4.86it/s]

Processing tickers:  48%|████▊     | 3252/6717 [11:06<11:50,  4.88it/s]

Processing tickers:  48%|████▊     | 3253/6717 [11:06<12:09,  4.75it/s]

Processing tickers:  48%|████▊     | 3254/6717 [11:06<12:01,  4.80it/s]

Processing tickers:  48%|████▊     | 3255/6717 [11:06<11:53,  4.85it/s]

Processing tickers:  48%|████▊     | 3256/6717 [11:07<11:59,  4.81it/s]

Processing tickers:  48%|████▊     | 3257/6717 [11:07<11:56,  4.83it/s]

Processing tickers:  49%|████▊     | 3258/6717 [11:07<12:05,  4.77it/s]

Processing tickers:  49%|████▊     | 3259/6717 [11:07<11:54,  4.84it/s]

Processing tickers:  49%|████▊     | 3260/6717 [11:07<11:49,  4.87it/s]

Processing tickers:  49%|████▊     | 3261/6717 [11:08<11:43,  4.91it/s]

Processing tickers:  49%|████▊     | 3262/6717 [11:08<11:47,  4.88it/s]

Processing tickers:  49%|████▊     | 3263/6717 [11:08<11:41,  4.93it/s]

Processing tickers:  49%|████▊     | 3264/6717 [11:08<11:39,  4.93it/s]

Processing tickers:  49%|████▊     | 3265/6717 [11:08<11:35,  4.96it/s]

Processing tickers:  49%|████▊     | 3266/6717 [11:09<11:38,  4.94it/s]

Processing tickers:  49%|████▊     | 3267/6717 [11:09<11:37,  4.95it/s]

Processing tickers:  49%|████▊     | 3268/6717 [11:09<11:35,  4.96it/s]

Processing tickers:  49%|████▊     | 3269/6717 [11:09<11:33,  4.97it/s]

Processing tickers:  49%|████▊     | 3270/6717 [11:09<11:34,  4.97it/s]

Processing tickers:  49%|████▊     | 3271/6717 [11:10<11:32,  4.98it/s]

Processing tickers:  49%|████▊     | 3272/6717 [11:10<11:35,  4.95it/s]

Processing tickers:  49%|████▊     | 3273/6717 [11:10<11:35,  4.95it/s]

Processing tickers:  49%|████▊     | 3274/6717 [11:10<11:30,  4.99it/s]

Processing tickers:  49%|████▉     | 3275/6717 [11:10<11:39,  4.92it/s]

Processing tickers:  49%|████▉     | 3276/6717 [11:11<11:37,  4.93it/s]

Processing tickers:  49%|████▉     | 3277/6717 [11:11<11:33,  4.96it/s]

Processing tickers:  49%|████▉     | 3278/6717 [11:11<11:36,  4.94it/s]

Processing tickers:  49%|████▉     | 3279/6717 [11:11<11:39,  4.91it/s]

Processing tickers:  49%|████▉     | 3280/6717 [11:11<11:35,  4.94it/s]

Processing tickers:  49%|████▉     | 3281/6717 [11:12<11:44,  4.88it/s]

Processing tickers:  49%|████▉     | 3282/6717 [11:12<11:58,  4.78it/s]

Processing tickers:  49%|████▉     | 3283/6717 [11:12<11:50,  4.84it/s]

Processing tickers:  49%|████▉     | 3284/6717 [11:12<11:41,  4.89it/s]

Processing tickers:  49%|████▉     | 3285/6717 [11:13<11:37,  4.92it/s]

Processing tickers:  49%|████▉     | 3286/6717 [11:13<11:35,  4.93it/s]

Processing tickers:  49%|████▉     | 3287/6717 [11:13<11:31,  4.96it/s]

Processing tickers:  49%|████▉     | 3288/6717 [11:13<11:42,  4.88it/s]

Processing tickers:  49%|████▉     | 3289/6717 [11:13<11:41,  4.89it/s]

Processing tickers:  49%|████▉     | 3290/6717 [11:14<11:45,  4.86it/s]

Processing tickers:  49%|████▉     | 3291/6717 [11:14<11:39,  4.90it/s]

Processing tickers:  49%|████▉     | 3292/6717 [11:14<11:34,  4.93it/s]

Processing tickers:  49%|████▉     | 3293/6717 [11:14<11:46,  4.85it/s]

Processing tickers:  49%|████▉     | 3294/6717 [11:14<11:44,  4.86it/s]

Processing tickers:  49%|████▉     | 3295/6717 [11:15<11:43,  4.86it/s]

Processing tickers:  49%|████▉     | 3296/6717 [11:15<11:38,  4.90it/s]

Processing tickers:  49%|████▉     | 3297/6717 [11:15<11:33,  4.93it/s]

Processing tickers:  49%|████▉     | 3298/6717 [11:15<11:33,  4.93it/s]

Processing tickers:  49%|████▉     | 3299/6717 [11:15<11:31,  4.94it/s]

Processing tickers:  49%|████▉     | 3300/6717 [11:16<11:30,  4.95it/s]

Processing tickers:  49%|████▉     | 3301/6717 [11:16<11:29,  4.96it/s]

Processing tickers:  49%|████▉     | 3302/6717 [11:16<11:25,  4.98it/s]

Processing tickers:  49%|████▉     | 3303/6717 [11:16<11:27,  4.96it/s]

Processing tickers:  49%|████▉     | 3304/6717 [11:16<11:28,  4.96it/s]

Processing tickers:  49%|████▉     | 3305/6717 [11:17<11:24,  4.99it/s]

Processing tickers:  49%|████▉     | 3306/6717 [11:17<11:27,  4.96it/s]

Processing tickers:  49%|████▉     | 3307/6717 [11:17<11:28,  4.95it/s]

Processing tickers:  49%|████▉     | 3308/6717 [11:17<11:26,  4.96it/s]

Processing tickers:  49%|████▉     | 3309/6717 [11:17<11:27,  4.96it/s]

Processing tickers:  49%|████▉     | 3310/6717 [11:18<11:22,  4.99it/s]

Processing tickers:  49%|████▉     | 3311/6717 [11:18<11:35,  4.90it/s]

Processing tickers:  49%|████▉     | 3312/6717 [11:18<11:43,  4.84it/s]

Processing tickers:  49%|████▉     | 3313/6717 [11:18<11:38,  4.88it/s]

Processing tickers:  49%|████▉     | 3314/6717 [11:18<11:30,  4.93it/s]

Processing tickers:  49%|████▉     | 3315/6717 [11:19<11:30,  4.93it/s]

Processing tickers:  49%|████▉     | 3316/6717 [11:19<11:25,  4.96it/s]

Processing tickers:  49%|████▉     | 3317/6717 [11:19<11:39,  4.86it/s]

Processing tickers:  49%|████▉     | 3318/6717 [11:19<11:31,  4.92it/s]

Processing tickers:  49%|████▉     | 3319/6717 [11:19<11:25,  4.95it/s]

Processing tickers:  49%|████▉     | 3320/6717 [11:20<11:21,  4.98it/s]

Processing tickers:  49%|████▉     | 3321/6717 [11:20<11:31,  4.91it/s]

Processing tickers:  49%|████▉     | 3322/6717 [11:20<11:37,  4.87it/s]

Processing tickers:  49%|████▉     | 3323/6717 [11:20<11:44,  4.82it/s]

Processing tickers:  49%|████▉     | 3324/6717 [11:20<11:38,  4.86it/s]

Processing tickers:  50%|████▉     | 3325/6717 [11:21<11:33,  4.89it/s]

Processing tickers:  50%|████▉     | 3326/6717 [11:21<11:29,  4.92it/s]

Processing tickers:  50%|████▉     | 3327/6717 [11:21<11:26,  4.94it/s]

Processing tickers:  50%|████▉     | 3328/6717 [11:21<11:31,  4.90it/s]

Processing tickers:  50%|████▉     | 3329/6717 [11:21<11:29,  4.92it/s]

Processing tickers:  50%|████▉     | 3330/6717 [11:22<11:26,  4.93it/s]

Processing tickers:  50%|████▉     | 3331/6717 [11:22<11:28,  4.92it/s]

Processing tickers:  50%|████▉     | 3332/6717 [11:22<11:28,  4.91it/s]

Processing tickers:  50%|████▉     | 3333/6717 [11:22<11:27,  4.92it/s]

Processing tickers:  50%|████▉     | 3334/6717 [11:22<11:25,  4.93it/s]

Processing tickers:  50%|████▉     | 3335/6717 [11:23<11:26,  4.92it/s]

Processing tickers:  50%|████▉     | 3336/6717 [11:23<11:29,  4.90it/s]

Processing tickers:  50%|████▉     | 3337/6717 [11:23<11:34,  4.87it/s]

Processing tickers:  50%|████▉     | 3338/6717 [11:23<11:39,  4.83it/s]

Processing tickers:  50%|████▉     | 3339/6717 [11:23<11:37,  4.84it/s]

Processing tickers:  50%|████▉     | 3340/6717 [11:24<11:32,  4.88it/s]

Processing tickers:  50%|████▉     | 3341/6717 [11:24<11:28,  4.90it/s]

Processing tickers:  50%|████▉     | 3342/6717 [11:24<11:24,  4.93it/s]

Processing tickers:  50%|████▉     | 3343/6717 [11:24<11:23,  4.93it/s]

Processing tickers:  50%|████▉     | 3344/6717 [11:25<11:24,  4.93it/s]

Processing tickers:  50%|████▉     | 3345/6717 [11:25<11:20,  4.95it/s]

Processing tickers:  50%|████▉     | 3346/6717 [11:25<11:17,  4.97it/s]

Processing tickers:  50%|████▉     | 3347/6717 [11:25<11:23,  4.93it/s]

Processing tickers:  50%|████▉     | 3348/6717 [11:25<11:21,  4.94it/s]

Processing tickers:  50%|████▉     | 3349/6717 [11:26<11:20,  4.95it/s]

Processing tickers:  50%|████▉     | 3350/6717 [11:26<11:22,  4.93it/s]

Processing tickers:  50%|████▉     | 3351/6717 [11:26<11:20,  4.95it/s]

Processing tickers:  50%|████▉     | 3352/6717 [11:26<11:24,  4.91it/s]

Processing tickers:  50%|████▉     | 3353/6717 [11:26<11:20,  4.95it/s]

Processing tickers:  50%|████▉     | 3354/6717 [11:27<11:21,  4.94it/s]

Processing tickers:  50%|████▉     | 3355/6717 [11:27<11:20,  4.94it/s]

Processing tickers:  50%|████▉     | 3356/6717 [11:27<11:28,  4.88it/s]

Processing tickers:  50%|████▉     | 3357/6717 [11:27<11:34,  4.84it/s]

Processing tickers:  50%|████▉     | 3358/6717 [11:27<11:31,  4.86it/s]

Processing tickers:  50%|█████     | 3359/6717 [11:28<11:54,  4.70it/s]

Processing tickers:  50%|█████     | 3360/6717 [11:28<11:42,  4.78it/s]

Processing tickers:  50%|█████     | 3361/6717 [11:28<11:45,  4.76it/s]

Processing tickers:  50%|█████     | 3362/6717 [11:28<11:48,  4.74it/s]

Processing tickers:  50%|█████     | 3363/6717 [11:28<11:42,  4.77it/s]

Processing tickers:  50%|█████     | 3364/6717 [11:29<11:36,  4.81it/s]

Processing tickers:  50%|█████     | 3365/6717 [11:29<11:39,  4.79it/s]

Processing tickers:  50%|█████     | 3366/6717 [11:29<11:32,  4.84it/s]

Processing tickers:  50%|█████     | 3367/6717 [11:29<11:27,  4.87it/s]

Processing tickers:  50%|█████     | 3368/6717 [11:29<11:26,  4.88it/s]

Processing tickers:  50%|█████     | 3369/6717 [11:30<11:35,  4.82it/s]

Processing tickers:  50%|█████     | 3370/6717 [11:30<11:36,  4.81it/s]

Processing tickers:  50%|█████     | 3371/6717 [11:30<11:33,  4.83it/s]

Processing tickers:  50%|█████     | 3372/6717 [11:30<11:27,  4.86it/s]

Processing tickers:  50%|█████     | 3373/6717 [11:30<11:34,  4.82it/s]

Processing tickers:  50%|█████     | 3374/6717 [11:31<11:41,  4.77it/s]

Processing tickers:  50%|█████     | 3375/6717 [11:31<11:34,  4.81it/s]

Processing tickers:  50%|█████     | 3376/6717 [11:31<11:33,  4.82it/s]

Processing tickers:  50%|█████     | 3377/6717 [11:31<11:30,  4.84it/s]

Processing tickers:  50%|█████     | 3378/6717 [11:32<11:25,  4.87it/s]

Processing tickers:  50%|█████     | 3379/6717 [11:32<11:22,  4.89it/s]

Processing tickers:  50%|█████     | 3380/6717 [11:32<11:19,  4.91it/s]

Processing tickers:  50%|█████     | 3381/6717 [11:32<11:24,  4.87it/s]

Processing tickers:  50%|█████     | 3382/6717 [11:32<11:22,  4.89it/s]

Processing tickers:  50%|█████     | 3383/6717 [11:33<11:20,  4.90it/s]

Processing tickers:  50%|█████     | 3384/6717 [11:33<11:17,  4.92it/s]

Processing tickers:  50%|█████     | 3385/6717 [11:33<11:25,  4.86it/s]

Processing tickers:  50%|█████     | 3386/6717 [11:33<11:19,  4.90it/s]

Processing tickers:  50%|█████     | 3387/6717 [11:33<11:15,  4.93it/s]

Processing tickers:  50%|█████     | 3388/6717 [11:34<11:16,  4.92it/s]

Processing tickers:  50%|█████     | 3389/6717 [11:34<11:41,  4.75it/s]

Processing tickers:  50%|█████     | 3390/6717 [11:34<11:38,  4.76it/s]

Processing tickers:  50%|█████     | 3391/6717 [11:34<11:42,  4.74it/s]

Processing tickers:  50%|█████     | 3392/6717 [11:34<11:31,  4.81it/s]

Processing tickers:  51%|█████     | 3393/6717 [11:35<11:30,  4.81it/s]

Processing tickers:  51%|█████     | 3394/6717 [11:35<11:23,  4.86it/s]

Processing tickers:  51%|█████     | 3395/6717 [11:35<11:30,  4.81it/s]

Processing tickers:  51%|█████     | 3396/6717 [11:35<11:21,  4.88it/s]

Processing tickers:  51%|█████     | 3397/6717 [11:35<11:22,  4.86it/s]

Processing tickers:  51%|█████     | 3398/6717 [11:36<11:17,  4.90it/s]

Processing tickers:  51%|█████     | 3399/6717 [11:36<11:16,  4.90it/s]

Processing tickers:  51%|█████     | 3400/6717 [11:36<11:14,  4.92it/s]

Processing tickers:  51%|█████     | 3401/6717 [11:36<11:13,  4.92it/s]

Processing tickers:  51%|█████     | 3402/6717 [11:36<11:10,  4.95it/s]

Processing tickers:  51%|█████     | 3403/6717 [11:37<11:08,  4.96it/s]

Processing tickers:  51%|█████     | 3404/6717 [11:37<11:08,  4.96it/s]

Processing tickers:  51%|█████     | 3405/6717 [11:37<11:08,  4.96it/s]

Processing tickers:  51%|█████     | 3406/6717 [11:37<11:05,  4.97it/s]

Processing tickers:  51%|█████     | 3407/6717 [11:37<11:03,  4.99it/s]

Processing tickers:  51%|█████     | 3408/6717 [11:38<11:23,  4.84it/s]

Processing tickers:  51%|█████     | 3409/6717 [11:38<11:17,  4.88it/s]

Processing tickers:  51%|█████     | 3410/6717 [11:38<11:18,  4.87it/s]

Processing tickers:  51%|█████     | 3411/6717 [11:38<11:14,  4.90it/s]

Processing tickers:  51%|█████     | 3412/6717 [11:38<11:13,  4.91it/s]

Processing tickers:  51%|█████     | 3413/6717 [11:39<11:15,  4.89it/s]

Processing tickers:  51%|█████     | 3414/6717 [11:39<11:11,  4.92it/s]

Processing tickers:  51%|█████     | 3415/6717 [11:39<11:14,  4.89it/s]

Processing tickers:  51%|█████     | 3416/6717 [11:39<11:11,  4.92it/s]

Processing tickers:  51%|█████     | 3417/6717 [11:39<11:11,  4.91it/s]

Processing tickers:  51%|█████     | 3418/6717 [11:40<11:10,  4.92it/s]

Processing tickers:  51%|█████     | 3419/6717 [11:40<11:08,  4.93it/s]

Processing tickers:  51%|█████     | 3420/6717 [11:40<11:05,  4.95it/s]

Processing tickers:  51%|█████     | 3421/6717 [11:40<11:09,  4.92it/s]

Processing tickers:  51%|█████     | 3422/6717 [11:41<11:07,  4.93it/s]

Processing tickers:  51%|█████     | 3423/6717 [11:41<11:08,  4.93it/s]

Processing tickers:  51%|█████     | 3424/6717 [11:41<11:09,  4.92it/s]

Processing tickers:  51%|█████     | 3425/6717 [11:41<11:12,  4.89it/s]

Processing tickers:  51%|█████     | 3426/6717 [11:41<11:12,  4.90it/s]

Processing tickers:  51%|█████     | 3427/6717 [11:42<11:15,  4.87it/s]

Processing tickers:  51%|█████     | 3428/6717 [11:42<11:11,  4.90it/s]

Processing tickers:  51%|█████     | 3429/6717 [11:42<11:13,  4.88it/s]

Processing tickers:  51%|█████     | 3430/6717 [11:42<11:09,  4.91it/s]

Processing tickers:  51%|█████     | 3431/6717 [11:42<11:09,  4.91it/s]

Processing tickers:  51%|█████     | 3432/6717 [11:43<11:09,  4.91it/s]

Processing tickers:  51%|█████     | 3433/6717 [11:43<11:09,  4.91it/s]

Processing tickers:  51%|█████     | 3434/6717 [11:43<11:04,  4.94it/s]

Processing tickers:  51%|█████     | 3435/6717 [11:43<11:06,  4.92it/s]

Processing tickers:  51%|█████     | 3436/6717 [11:43<11:06,  4.92it/s]

Processing tickers:  51%|█████     | 3437/6717 [11:44<11:06,  4.92it/s]

Processing tickers:  51%|█████     | 3438/6717 [11:44<11:03,  4.94it/s]

Processing tickers:  51%|█████     | 3439/6717 [11:44<10:59,  4.97it/s]

Processing tickers:  51%|█████     | 3440/6717 [11:44<10:59,  4.97it/s]

Processing tickers:  51%|█████     | 3441/6717 [11:44<11:06,  4.91it/s]

Processing tickers:  51%|█████     | 3442/6717 [11:45<11:04,  4.93it/s]

Processing tickers:  51%|█████▏    | 3443/6717 [11:45<11:01,  4.95it/s]

Processing tickers:  51%|█████▏    | 3444/6717 [11:45<10:58,  4.97it/s]

Processing tickers:  51%|█████▏    | 3445/6717 [11:45<10:55,  4.99it/s]

Processing tickers:  51%|█████▏    | 3446/6717 [11:45<10:56,  4.98it/s]

Processing tickers:  51%|█████▏    | 3447/6717 [11:46<10:57,  4.97it/s]

Processing tickers:  51%|█████▏    | 3448/6717 [11:46<10:56,  4.98it/s]

Processing tickers:  51%|█████▏    | 3449/6717 [11:46<10:57,  4.97it/s]

Processing tickers:  51%|█████▏    | 3450/6717 [11:46<11:01,  4.94it/s]

Processing tickers:  51%|█████▏    | 3451/6717 [11:46<11:01,  4.94it/s]

Processing tickers:  51%|█████▏    | 3452/6717 [11:47<11:04,  4.92it/s]

Processing tickers:  51%|█████▏    | 3453/6717 [11:47<10:59,  4.95it/s]

Processing tickers:  51%|█████▏    | 3454/6717 [11:47<11:16,  4.82it/s]

Processing tickers:  51%|█████▏    | 3455/6717 [11:47<11:10,  4.86it/s]

Processing tickers:  51%|█████▏    | 3456/6717 [11:47<11:19,  4.80it/s]

Processing tickers:  51%|█████▏    | 3457/6717 [11:48<11:11,  4.85it/s]

Processing tickers:  51%|█████▏    | 3458/6717 [11:48<11:19,  4.79it/s]

Processing tickers:  51%|█████▏    | 3459/6717 [11:48<11:13,  4.84it/s]

Processing tickers:  52%|█████▏    | 3460/6717 [11:48<11:08,  4.87it/s]

Processing tickers:  52%|█████▏    | 3461/6717 [11:48<11:04,  4.90it/s]

Processing tickers:  52%|█████▏    | 3462/6717 [11:49<11:00,  4.93it/s]

Processing tickers:  52%|█████▏    | 3463/6717 [11:49<10:59,  4.93it/s]

Processing tickers:  52%|█████▏    | 3464/6717 [11:49<10:58,  4.94it/s]

Processing tickers:  52%|█████▏    | 3465/6717 [11:49<11:03,  4.90it/s]

Processing tickers:  52%|█████▏    | 3466/6717 [11:49<11:07,  4.87it/s]

Processing tickers:  52%|█████▏    | 3467/6717 [11:50<11:01,  4.91it/s]

Processing tickers:  52%|█████▏    | 3468/6717 [11:50<10:57,  4.95it/s]

Processing tickers:  52%|█████▏    | 3469/6717 [11:50<10:55,  4.96it/s]

Processing tickers:  52%|█████▏    | 3470/6717 [11:50<10:53,  4.97it/s]

Processing tickers:  52%|█████▏    | 3471/6717 [11:50<10:54,  4.96it/s]

Processing tickers:  52%|█████▏    | 3472/6717 [11:51<10:51,  4.98it/s]

Processing tickers:  52%|█████▏    | 3473/6717 [11:51<10:48,  5.00it/s]

Processing tickers:  52%|█████▏    | 3474/6717 [11:51<10:49,  5.00it/s]

Processing tickers:  52%|█████▏    | 3475/6717 [11:51<10:50,  4.99it/s]

Processing tickers:  52%|█████▏    | 3476/6717 [11:51<10:48,  5.00it/s]

Processing tickers:  52%|█████▏    | 3477/6717 [11:52<10:46,  5.01it/s]

Processing tickers:  52%|█████▏    | 3478/6717 [11:52<10:50,  4.98it/s]

Processing tickers:  52%|█████▏    | 3479/6717 [11:52<10:53,  4.96it/s]

Processing tickers:  52%|█████▏    | 3480/6717 [11:52<10:49,  4.98it/s]

Processing tickers:  52%|█████▏    | 3481/6717 [11:52<10:49,  4.98it/s]

Processing tickers:  52%|█████▏    | 3482/6717 [11:53<10:53,  4.95it/s]

Processing tickers:  52%|█████▏    | 3483/6717 [11:53<10:50,  4.97it/s]

Processing tickers:  52%|█████▏    | 3484/6717 [11:53<10:50,  4.97it/s]

Processing tickers:  52%|█████▏    | 3485/6717 [11:53<10:48,  4.99it/s]

Processing tickers:  52%|█████▏    | 3486/6717 [11:53<10:48,  4.98it/s]

Processing tickers:  52%|█████▏    | 3487/6717 [11:54<10:45,  5.01it/s]

Processing tickers:  52%|█████▏    | 3488/6717 [11:54<10:44,  5.01it/s]

Processing tickers:  52%|█████▏    | 3489/6717 [11:54<10:45,  5.00it/s]

Processing tickers:  52%|█████▏    | 3490/6717 [11:54<10:44,  5.01it/s]

Processing tickers:  52%|█████▏    | 3491/6717 [11:54<10:45,  5.00it/s]

Processing tickers:  52%|█████▏    | 3492/6717 [11:55<11:13,  4.79it/s]

Processing tickers:  52%|█████▏    | 3493/6717 [11:55<11:04,  4.86it/s]

Processing tickers:  52%|█████▏    | 3494/6717 [11:55<10:58,  4.90it/s]

Processing tickers:  52%|█████▏    | 3495/6717 [11:55<10:55,  4.92it/s]

Processing tickers:  52%|█████▏    | 3496/6717 [11:56<10:52,  4.93it/s]

Processing tickers:  52%|█████▏    | 3497/6717 [11:56<10:55,  4.91it/s]

Processing tickers:  52%|█████▏    | 3498/6717 [11:56<10:52,  4.93it/s]

Processing tickers:  52%|█████▏    | 3499/6717 [11:56<10:47,  4.97it/s]

Processing tickers:  52%|█████▏    | 3500/6717 [11:56<10:49,  4.96it/s]

Processing tickers:  52%|█████▏    | 3501/6717 [11:57<10:48,  4.96it/s]

Processing tickers:  52%|█████▏    | 3502/6717 [11:57<10:52,  4.92it/s]

Processing tickers:  52%|█████▏    | 3503/6717 [11:57<10:48,  4.96it/s]

Processing tickers:  52%|█████▏    | 3504/6717 [11:57<10:45,  4.98it/s]

Processing tickers:  52%|█████▏    | 3505/6717 [11:57<10:48,  4.95it/s]

Processing tickers:  52%|█████▏    | 3506/6717 [11:58<10:48,  4.95it/s]

Processing tickers:  52%|█████▏    | 3507/6717 [11:58<10:47,  4.96it/s]

Processing tickers:  52%|█████▏    | 3508/6717 [11:58<10:50,  4.94it/s]

Processing tickers:  52%|█████▏    | 3509/6717 [11:58<10:49,  4.94it/s]

Processing tickers:  52%|█████▏    | 3510/6717 [11:58<11:11,  4.78it/s]

Processing tickers:  52%|█████▏    | 3511/6717 [11:59<11:00,  4.85it/s]

Processing tickers:  52%|█████▏    | 3512/6717 [11:59<10:59,  4.86it/s]

Processing tickers:  52%|█████▏    | 3513/6717 [11:59<10:56,  4.88it/s]

Processing tickers:  52%|█████▏    | 3514/6717 [11:59<11:02,  4.84it/s]

Processing tickers:  52%|█████▏    | 3515/6717 [11:59<11:51,  4.50it/s]

Processing tickers:  52%|█████▏    | 3516/6717 [12:00<11:30,  4.64it/s]

Processing tickers:  52%|█████▏    | 3517/6717 [12:00<11:15,  4.74it/s]

Processing tickers:  52%|█████▏    | 3518/6717 [12:00<11:10,  4.77it/s]

Processing tickers:  52%|█████▏    | 3519/6717 [12:00<11:07,  4.79it/s]

Processing tickers:  52%|█████▏    | 3520/6717 [12:00<10:57,  4.86it/s]

Processing tickers:  52%|█████▏    | 3521/6717 [12:01<10:49,  4.92it/s]

Processing tickers:  52%|█████▏    | 3522/6717 [12:01<10:46,  4.94it/s]

Processing tickers:  52%|█████▏    | 3523/6717 [12:01<10:42,  4.97it/s]

Processing tickers:  52%|█████▏    | 3524/6717 [12:01<10:40,  4.99it/s]

Processing tickers:  52%|█████▏    | 3525/6717 [12:01<10:40,  4.99it/s]

Processing tickers:  52%|█████▏    | 3526/6717 [12:02<10:37,  5.00it/s]

Processing tickers:  53%|█████▎    | 3527/6717 [12:02<10:37,  5.00it/s]

Processing tickers:  53%|█████▎    | 3528/6717 [12:02<10:39,  4.99it/s]

Processing tickers:  53%|█████▎    | 3529/6717 [12:02<10:39,  4.98it/s]

Processing tickers:  53%|█████▎    | 3530/6717 [12:02<10:39,  4.98it/s]

Processing tickers:  53%|█████▎    | 3531/6717 [12:03<10:40,  4.97it/s]

Processing tickers:  53%|█████▎    | 3532/6717 [12:03<10:38,  4.99it/s]

Processing tickers:  53%|█████▎    | 3533/6717 [12:03<10:38,  4.99it/s]

Processing tickers:  53%|█████▎    | 3534/6717 [12:03<10:39,  4.98it/s]

Processing tickers:  53%|█████▎    | 3535/6717 [12:03<10:37,  4.99it/s]

Processing tickers:  53%|█████▎    | 3536/6717 [12:04<10:38,  4.99it/s]

Processing tickers:  53%|█████▎    | 3537/6717 [12:04<10:38,  4.98it/s]

Processing tickers:  53%|█████▎    | 3538/6717 [12:04<10:41,  4.95it/s]

Processing tickers:  53%|█████▎    | 3539/6717 [12:04<10:38,  4.98it/s]

Processing tickers:  53%|█████▎    | 3540/6717 [12:04<10:45,  4.92it/s]

Processing tickers:  53%|█████▎    | 3541/6717 [12:05<10:43,  4.94it/s]

Processing tickers:  53%|█████▎    | 3542/6717 [12:05<10:42,  4.94it/s]

Processing tickers:  53%|█████▎    | 3543/6717 [12:05<10:40,  4.96it/s]

Processing tickers:  53%|█████▎    | 3544/6717 [12:05<10:42,  4.94it/s]

Processing tickers:  53%|█████▎    | 3545/6717 [12:05<10:48,  4.89it/s]

Processing tickers:  53%|█████▎    | 3546/6717 [12:06<10:42,  4.93it/s]

Processing tickers:  53%|█████▎    | 3547/6717 [12:06<10:38,  4.96it/s]

Processing tickers:  53%|█████▎    | 3548/6717 [12:06<10:41,  4.94it/s]

Processing tickers:  53%|█████▎    | 3549/6717 [12:06<10:41,  4.94it/s]

Processing tickers:  53%|█████▎    | 3550/6717 [12:06<10:42,  4.93it/s]

Processing tickers:  53%|█████▎    | 3551/6717 [12:07<10:34,  4.99it/s]

Processing tickers:  53%|█████▎    | 3552/6717 [12:07<10:30,  5.02it/s]

Processing tickers:  53%|█████▎    | 3553/6717 [12:07<10:44,  4.91it/s]

Processing tickers:  53%|█████▎    | 3554/6717 [12:07<10:41,  4.93it/s]

Processing tickers:  53%|█████▎    | 3555/6717 [12:07<10:35,  4.98it/s]

Processing tickers:  53%|█████▎    | 3556/6717 [12:08<10:32,  5.00it/s]

Processing tickers:  53%|█████▎    | 3557/6717 [12:08<10:31,  5.00it/s]

Processing tickers:  53%|█████▎    | 3558/6717 [12:08<10:32,  4.99it/s]

Processing tickers:  53%|█████▎    | 3559/6717 [12:08<10:32,  5.00it/s]

Processing tickers:  53%|█████▎    | 3560/6717 [12:08<10:40,  4.93it/s]

Processing tickers:  53%|█████▎    | 3561/6717 [12:09<10:35,  4.97it/s]

Processing tickers:  53%|█████▎    | 3562/6717 [12:09<10:36,  4.96it/s]

Processing tickers:  53%|█████▎    | 3563/6717 [12:09<10:38,  4.94it/s]

Processing tickers:  53%|█████▎    | 3564/6717 [12:09<10:37,  4.94it/s]

Processing tickers:  53%|█████▎    | 3565/6717 [12:09<10:37,  4.94it/s]

Processing tickers:  53%|█████▎    | 3566/6717 [12:10<11:09,  4.71it/s]

Processing tickers:  53%|█████▎    | 3567/6717 [12:10<11:00,  4.77it/s]

Processing tickers:  53%|█████▎    | 3568/6717 [12:10<10:53,  4.82it/s]

Processing tickers:  53%|█████▎    | 3569/6717 [12:10<11:01,  4.76it/s]

Processing tickers:  53%|█████▎    | 3570/6717 [12:11<10:54,  4.81it/s]

Processing tickers:  53%|█████▎    | 3571/6717 [12:11<10:47,  4.86it/s]

Processing tickers:  53%|█████▎    | 3572/6717 [12:11<10:40,  4.91it/s]

Processing tickers:  53%|█████▎    | 3573/6717 [12:11<10:48,  4.85it/s]

Processing tickers:  53%|█████▎    | 3574/6717 [12:11<10:45,  4.87it/s]

Processing tickers:  53%|█████▎    | 3575/6717 [12:12<10:48,  4.85it/s]

Processing tickers:  53%|█████▎    | 3576/6717 [12:12<10:43,  4.88it/s]

Processing tickers:  53%|█████▎    | 3577/6717 [12:12<10:51,  4.82it/s]

Processing tickers:  53%|█████▎    | 3578/6717 [12:12<10:52,  4.81it/s]

Processing tickers:  53%|█████▎    | 3579/6717 [12:12<10:53,  4.80it/s]

Processing tickers:  53%|█████▎    | 3580/6717 [12:13<10:50,  4.82it/s]

Processing tickers:  53%|█████▎    | 3581/6717 [12:13<10:43,  4.88it/s]

Processing tickers:  53%|█████▎    | 3582/6717 [12:13<10:44,  4.87it/s]

Processing tickers:  53%|█████▎    | 3583/6717 [12:13<10:37,  4.91it/s]

Processing tickers:  53%|█████▎    | 3584/6717 [12:13<10:33,  4.95it/s]

Processing tickers:  53%|█████▎    | 3585/6717 [12:14<10:31,  4.96it/s]

Processing tickers:  53%|█████▎    | 3586/6717 [12:14<10:29,  4.97it/s]

Processing tickers:  53%|█████▎    | 3587/6717 [12:14<10:32,  4.95it/s]

Processing tickers:  53%|█████▎    | 3588/6717 [12:14<10:34,  4.93it/s]

Processing tickers:  53%|█████▎    | 3589/6717 [12:14<10:36,  4.91it/s]

Processing tickers:  53%|█████▎    | 3590/6717 [12:15<10:35,  4.92it/s]

Processing tickers:  53%|█████▎    | 3591/6717 [12:15<10:34,  4.93it/s]

Processing tickers:  53%|█████▎    | 3592/6717 [12:15<10:33,  4.93it/s]

Processing tickers:  53%|█████▎    | 3593/6717 [12:15<10:32,  4.94it/s]

Processing tickers:  54%|█████▎    | 3594/6717 [12:15<10:34,  4.92it/s]

Processing tickers:  54%|█████▎    | 3595/6717 [12:16<10:30,  4.95it/s]

Processing tickers:  54%|█████▎    | 3596/6717 [12:16<10:36,  4.91it/s]

Processing tickers:  54%|█████▎    | 3597/6717 [12:16<10:41,  4.87it/s]

Processing tickers:  54%|█████▎    | 3598/6717 [12:16<10:39,  4.88it/s]

Processing tickers:  54%|█████▎    | 3599/6717 [12:16<10:40,  4.87it/s]

Processing tickers:  54%|█████▎    | 3600/6717 [12:17<10:36,  4.89it/s]

Processing tickers:  54%|█████▎    | 3601/6717 [12:17<10:32,  4.93it/s]

Processing tickers:  54%|█████▎    | 3602/6717 [12:17<10:36,  4.90it/s]

Processing tickers:  54%|█████▎    | 3603/6717 [12:17<10:33,  4.92it/s]

Processing tickers:  54%|█████▎    | 3604/6717 [12:17<10:34,  4.90it/s]

Processing tickers:  54%|█████▎    | 3605/6717 [12:18<10:28,  4.95it/s]

Processing tickers:  54%|█████▎    | 3606/6717 [12:18<10:27,  4.96it/s]

Processing tickers:  54%|█████▎    | 3607/6717 [12:18<10:23,  4.99it/s]

Processing tickers:  54%|█████▎    | 3608/6717 [12:18<10:35,  4.89it/s]

Processing tickers:  54%|█████▎    | 3609/6717 [12:19<10:34,  4.90it/s]

Processing tickers:  54%|█████▎    | 3610/6717 [12:19<10:41,  4.84it/s]

Processing tickers:  54%|█████▍    | 3611/6717 [12:19<10:35,  4.89it/s]

Processing tickers:  54%|█████▍    | 3612/6717 [12:19<10:33,  4.90it/s]

Processing tickers:  54%|█████▍    | 3613/6717 [12:19<10:30,  4.92it/s]

Processing tickers:  54%|█████▍    | 3614/6717 [12:20<10:27,  4.94it/s]

Processing tickers:  54%|█████▍    | 3615/6717 [12:20<10:27,  4.94it/s]

Processing tickers:  54%|█████▍    | 3616/6717 [12:20<10:28,  4.93it/s]

Processing tickers:  54%|█████▍    | 3617/6717 [12:20<10:25,  4.95it/s]

Processing tickers:  54%|█████▍    | 3618/6717 [12:20<10:22,  4.97it/s]

Processing tickers:  54%|█████▍    | 3619/6717 [12:21<10:21,  4.99it/s]

Processing tickers:  54%|█████▍    | 3620/6717 [12:21<10:31,  4.90it/s]

Processing tickers:  54%|█████▍    | 3621/6717 [12:21<10:30,  4.91it/s]

Processing tickers:  54%|█████▍    | 3622/6717 [12:21<10:29,  4.92it/s]

Processing tickers:  54%|█████▍    | 3623/6717 [12:21<10:30,  4.91it/s]

Processing tickers:  54%|█████▍    | 3624/6717 [12:22<10:34,  4.88it/s]

Processing tickers:  54%|█████▍    | 3625/6717 [12:22<10:29,  4.91it/s]

Processing tickers:  54%|█████▍    | 3626/6717 [12:22<10:27,  4.92it/s]

Processing tickers:  54%|█████▍    | 3627/6717 [12:22<10:26,  4.93it/s]

Processing tickers:  54%|█████▍    | 3628/6717 [12:22<10:24,  4.95it/s]

Processing tickers:  54%|█████▍    | 3629/6717 [12:23<10:23,  4.95it/s]

Processing tickers:  54%|█████▍    | 3630/6717 [12:23<10:22,  4.96it/s]

Processing tickers:  54%|█████▍    | 3631/6717 [12:23<10:21,  4.96it/s]

Processing tickers:  54%|█████▍    | 3632/6717 [12:23<10:23,  4.95it/s]

Processing tickers:  54%|█████▍    | 3633/6717 [12:23<10:26,  4.92it/s]

Processing tickers:  54%|█████▍    | 3634/6717 [12:24<10:23,  4.95it/s]

Processing tickers:  54%|█████▍    | 3635/6717 [12:24<10:26,  4.92it/s]

Processing tickers:  54%|█████▍    | 3636/6717 [12:24<10:46,  4.77it/s]

Processing tickers:  54%|█████▍    | 3637/6717 [12:24<10:46,  4.77it/s]

Processing tickers:  54%|█████▍    | 3638/6717 [12:24<10:36,  4.83it/s]

Processing tickers:  54%|█████▍    | 3639/6717 [12:25<10:31,  4.87it/s]

Processing tickers:  54%|█████▍    | 3640/6717 [12:25<10:24,  4.92it/s]

Processing tickers:  54%|█████▍    | 3641/6717 [12:25<10:26,  4.91it/s]

Processing tickers:  54%|█████▍    | 3642/6717 [12:25<10:27,  4.90it/s]

Processing tickers:  54%|█████▍    | 3643/6717 [12:25<10:28,  4.89it/s]

Processing tickers:  54%|█████▍    | 3644/6717 [12:26<10:24,  4.92it/s]

Processing tickers:  54%|█████▍    | 3645/6717 [12:26<10:20,  4.95it/s]

Processing tickers:  54%|█████▍    | 3646/6717 [12:26<10:24,  4.91it/s]

Processing tickers:  54%|█████▍    | 3647/6717 [12:26<10:22,  4.93it/s]

Processing tickers:  54%|█████▍    | 3648/6717 [12:26<10:33,  4.84it/s]

Processing tickers:  54%|█████▍    | 3649/6717 [12:27<10:30,  4.87it/s]

Processing tickers:  54%|█████▍    | 3650/6717 [12:27<10:26,  4.89it/s]

Processing tickers:  54%|█████▍    | 3651/6717 [12:27<10:27,  4.89it/s]

Processing tickers:  54%|█████▍    | 3652/6717 [12:27<10:24,  4.91it/s]

Processing tickers:  54%|█████▍    | 3653/6717 [12:27<10:23,  4.92it/s]

Processing tickers:  54%|█████▍    | 3654/6717 [12:28<10:20,  4.94it/s]

Processing tickers:  54%|█████▍    | 3655/6717 [12:28<10:18,  4.95it/s]

Processing tickers:  54%|█████▍    | 3656/6717 [12:28<10:17,  4.96it/s]

Processing tickers:  54%|█████▍    | 3657/6717 [12:28<10:18,  4.95it/s]

Processing tickers:  54%|█████▍    | 3658/6717 [12:28<10:15,  4.97it/s]

Processing tickers:  54%|█████▍    | 3659/6717 [12:29<10:15,  4.97it/s]

Processing tickers:  54%|█████▍    | 3660/6717 [12:29<10:16,  4.96it/s]

Processing tickers:  55%|█████▍    | 3661/6717 [12:29<10:16,  4.96it/s]

Processing tickers:  55%|█████▍    | 3662/6717 [12:29<10:13,  4.98it/s]

Processing tickers:  55%|█████▍    | 3663/6717 [12:29<10:18,  4.94it/s]

Processing tickers:  55%|█████▍    | 3664/6717 [12:30<10:17,  4.95it/s]

Processing tickers:  55%|█████▍    | 3665/6717 [12:30<10:14,  4.96it/s]

Processing tickers:  55%|█████▍    | 3666/6717 [12:30<10:12,  4.98it/s]

Processing tickers:  55%|█████▍    | 3667/6717 [12:30<10:14,  4.96it/s]

Processing tickers:  55%|█████▍    | 3668/6717 [12:30<10:14,  4.97it/s]

Processing tickers:  55%|█████▍    | 3669/6717 [12:31<10:13,  4.97it/s]

Processing tickers:  55%|█████▍    | 3670/6717 [12:31<10:17,  4.93it/s]

Processing tickers:  55%|█████▍    | 3671/6717 [12:31<10:14,  4.96it/s]

Processing tickers:  55%|█████▍    | 3672/6717 [12:31<10:13,  4.97it/s]

Processing tickers:  55%|█████▍    | 3673/6717 [12:32<10:15,  4.94it/s]

Processing tickers:  55%|█████▍    | 3674/6717 [12:32<10:15,  4.95it/s]

Processing tickers:  55%|█████▍    | 3675/6717 [12:32<10:14,  4.95it/s]

Processing tickers:  55%|█████▍    | 3676/6717 [12:32<10:12,  4.96it/s]

Processing tickers:  55%|█████▍    | 3677/6717 [12:32<10:13,  4.95it/s]

Processing tickers:  55%|█████▍    | 3678/6717 [12:33<10:18,  4.91it/s]

Processing tickers:  55%|█████▍    | 3679/6717 [12:33<10:16,  4.92it/s]

Processing tickers:  55%|█████▍    | 3680/6717 [12:33<10:16,  4.93it/s]

Processing tickers:  55%|█████▍    | 3681/6717 [12:33<10:15,  4.93it/s]

Processing tickers:  55%|█████▍    | 3682/6717 [12:33<10:18,  4.91it/s]

Processing tickers:  55%|█████▍    | 3683/6717 [12:34<10:17,  4.92it/s]

Processing tickers:  55%|█████▍    | 3684/6717 [12:34<10:14,  4.93it/s]

Processing tickers:  55%|█████▍    | 3685/6717 [12:34<10:11,  4.96it/s]

Processing tickers:  55%|█████▍    | 3686/6717 [12:34<10:11,  4.96it/s]

Processing tickers:  55%|█████▍    | 3687/6717 [12:34<10:11,  4.95it/s]

Processing tickers:  55%|█████▍    | 3688/6717 [12:35<10:13,  4.94it/s]

Processing tickers:  55%|█████▍    | 3689/6717 [12:35<10:13,  4.94it/s]

Processing tickers:  55%|█████▍    | 3690/6717 [12:35<10:32,  4.79it/s]

Processing tickers:  55%|█████▍    | 3691/6717 [12:35<10:23,  4.85it/s]

Processing tickers:  55%|█████▍    | 3692/6717 [12:35<10:19,  4.88it/s]

Processing tickers:  55%|█████▍    | 3693/6717 [12:36<10:17,  4.90it/s]

Processing tickers:  55%|█████▍    | 3694/6717 [12:36<10:12,  4.93it/s]

Processing tickers:  55%|█████▌    | 3695/6717 [12:36<10:16,  4.90it/s]

Processing tickers:  55%|█████▌    | 3696/6717 [12:36<10:10,  4.95it/s]

Processing tickers:  55%|█████▌    | 3697/6717 [12:36<10:09,  4.96it/s]

Processing tickers:  55%|█████▌    | 3698/6717 [12:37<10:07,  4.97it/s]

Processing tickers:  55%|█████▌    | 3699/6717 [12:37<10:07,  4.97it/s]

Processing tickers:  55%|█████▌    | 3700/6717 [12:37<10:16,  4.89it/s]

Processing tickers:  55%|█████▌    | 3701/6717 [12:37<10:13,  4.92it/s]

Processing tickers:  55%|█████▌    | 3702/6717 [12:37<10:13,  4.92it/s]

Processing tickers:  55%|█████▌    | 3703/6717 [12:38<10:10,  4.94it/s]

Processing tickers:  55%|█████▌    | 3704/6717 [12:38<10:06,  4.97it/s]

Processing tickers:  55%|█████▌    | 3705/6717 [12:38<10:17,  4.87it/s]

Processing tickers:  55%|█████▌    | 3706/6717 [12:38<10:17,  4.87it/s]

Processing tickers:  55%|█████▌    | 3707/6717 [12:38<10:15,  4.89it/s]

Processing tickers:  55%|█████▌    | 3708/6717 [12:39<10:09,  4.93it/s]

Processing tickers:  55%|█████▌    | 3709/6717 [12:39<10:18,  4.87it/s]

Processing tickers:  55%|█████▌    | 3710/6717 [12:39<10:22,  4.83it/s]

Processing tickers:  55%|█████▌    | 3711/6717 [12:39<10:23,  4.82it/s]

Processing tickers:  55%|█████▌    | 3712/6717 [12:39<10:23,  4.82it/s]

Processing tickers:  55%|█████▌    | 3713/6717 [12:40<10:43,  4.67it/s]

Processing tickers:  55%|█████▌    | 3714/6717 [12:40<10:29,  4.77it/s]

Processing tickers:  55%|█████▌    | 3715/6717 [12:40<10:24,  4.80it/s]

Processing tickers:  55%|█████▌    | 3716/6717 [12:40<10:20,  4.84it/s]

Processing tickers:  55%|█████▌    | 3717/6717 [12:40<10:13,  4.89it/s]

Processing tickers:  55%|█████▌    | 3718/6717 [12:41<10:10,  4.92it/s]

Processing tickers:  55%|█████▌    | 3719/6717 [12:41<10:06,  4.94it/s]

Processing tickers:  55%|█████▌    | 3720/6717 [12:41<10:04,  4.96it/s]

Processing tickers:  55%|█████▌    | 3721/6717 [12:41<10:04,  4.95it/s]

Processing tickers:  55%|█████▌    | 3722/6717 [12:41<10:03,  4.96it/s]

Processing tickers:  55%|█████▌    | 3723/6717 [12:42<10:02,  4.97it/s]

Processing tickers:  55%|█████▌    | 3724/6717 [12:42<09:59,  4.99it/s]

Processing tickers:  55%|█████▌    | 3725/6717 [12:42<10:02,  4.97it/s]

Processing tickers:  55%|█████▌    | 3726/6717 [12:42<09:59,  4.99it/s]

Processing tickers:  55%|█████▌    | 3727/6717 [12:42<10:00,  4.98it/s]

Processing tickers:  56%|█████▌    | 3728/6717 [12:43<10:04,  4.95it/s]

Processing tickers:  56%|█████▌    | 3729/6717 [12:43<10:02,  4.96it/s]

Processing tickers:  56%|█████▌    | 3730/6717 [12:43<10:02,  4.96it/s]

Processing tickers:  56%|█████▌    | 3731/6717 [12:43<10:04,  4.94it/s]

Processing tickers:  56%|█████▌    | 3732/6717 [12:44<10:04,  4.94it/s]

Processing tickers:  56%|█████▌    | 3733/6717 [12:44<10:03,  4.94it/s]

Processing tickers:  56%|█████▌    | 3734/6717 [12:44<10:08,  4.90it/s]

Processing tickers:  56%|█████▌    | 3735/6717 [12:44<10:07,  4.90it/s]

Processing tickers:  56%|█████▌    | 3736/6717 [12:44<10:03,  4.94it/s]

Processing tickers:  56%|█████▌    | 3737/6717 [12:45<10:06,  4.91it/s]

Processing tickers:  56%|█████▌    | 3738/6717 [12:45<10:09,  4.89it/s]

Processing tickers:  56%|█████▌    | 3739/6717 [12:45<10:07,  4.90it/s]

Processing tickers:  56%|█████▌    | 3740/6717 [12:45<10:05,  4.91it/s]

Processing tickers:  56%|█████▌    | 3741/6717 [12:45<10:06,  4.91it/s]

Processing tickers:  56%|█████▌    | 3742/6717 [12:46<10:05,  4.92it/s]

Processing tickers:  56%|█████▌    | 3743/6717 [12:46<10:01,  4.95it/s]

Processing tickers:  56%|█████▌    | 3744/6717 [12:46<10:13,  4.85it/s]

Processing tickers:  56%|█████▌    | 3745/6717 [12:46<10:10,  4.87it/s]

Processing tickers:  56%|█████▌    | 3746/6717 [12:46<10:11,  4.86it/s]

Processing tickers:  56%|█████▌    | 3747/6717 [12:47<10:08,  4.88it/s]

Processing tickers:  56%|█████▌    | 3748/6717 [12:47<10:08,  4.88it/s]

Processing tickers:  56%|█████▌    | 3749/6717 [12:47<10:11,  4.85it/s]

Processing tickers:  56%|█████▌    | 3750/6717 [12:47<10:07,  4.89it/s]

Processing tickers:  56%|█████▌    | 3751/6717 [12:47<10:12,  4.84it/s]

Processing tickers:  56%|█████▌    | 3752/6717 [12:48<10:06,  4.89it/s]

Processing tickers:  56%|█████▌    | 3753/6717 [12:48<10:07,  4.88it/s]

Processing tickers:  56%|█████▌    | 3754/6717 [12:48<10:17,  4.80it/s]

Processing tickers:  56%|█████▌    | 3755/6717 [12:48<10:13,  4.83it/s]

Processing tickers:  56%|█████▌    | 3756/6717 [12:48<10:08,  4.86it/s]

Processing tickers:  56%|█████▌    | 3757/6717 [12:49<10:04,  4.90it/s]

Processing tickers:  56%|█████▌    | 3758/6717 [12:49<10:01,  4.92it/s]

Processing tickers:  56%|█████▌    | 3759/6717 [12:49<10:00,  4.93it/s]

Processing tickers:  56%|█████▌    | 3760/6717 [12:49<09:58,  4.94it/s]

Processing tickers:  56%|█████▌    | 3761/6717 [12:49<10:02,  4.91it/s]

Processing tickers:  56%|█████▌    | 3762/6717 [12:50<09:56,  4.95it/s]

Processing tickers:  56%|█████▌    | 3763/6717 [12:50<09:59,  4.93it/s]

Processing tickers:  56%|█████▌    | 3764/6717 [12:50<09:55,  4.96it/s]

Processing tickers:  56%|█████▌    | 3765/6717 [12:50<09:52,  4.98it/s]

Processing tickers:  56%|█████▌    | 3766/6717 [12:50<09:50,  4.99it/s]

Processing tickers:  56%|█████▌    | 3767/6717 [12:51<10:07,  4.86it/s]

Processing tickers:  56%|█████▌    | 3768/6717 [12:51<10:07,  4.86it/s]

Processing tickers:  56%|█████▌    | 3769/6717 [12:51<10:03,  4.89it/s]

Processing tickers:  56%|█████▌    | 3770/6717 [12:51<10:08,  4.84it/s]

Processing tickers:  56%|█████▌    | 3771/6717 [12:51<09:59,  4.91it/s]

Processing tickers:  56%|█████▌    | 3772/6717 [12:52<09:53,  4.96it/s]

Processing tickers:  56%|█████▌    | 3773/6717 [12:52<09:52,  4.97it/s]

Processing tickers:  56%|█████▌    | 3774/6717 [12:52<09:55,  4.94it/s]

Processing tickers:  56%|█████▌    | 3775/6717 [12:52<09:55,  4.94it/s]

Processing tickers:  56%|█████▌    | 3776/6717 [12:52<09:58,  4.91it/s]

Processing tickers:  56%|█████▌    | 3777/6717 [12:53<09:56,  4.93it/s]

Processing tickers:  56%|█████▌    | 3778/6717 [12:53<09:57,  4.92it/s]

Processing tickers:  56%|█████▋    | 3779/6717 [12:53<09:57,  4.92it/s]

Processing tickers:  56%|█████▋    | 3780/6717 [12:53<09:53,  4.95it/s]

Processing tickers:  56%|█████▋    | 3781/6717 [12:53<09:55,  4.93it/s]

Processing tickers:  56%|█████▋    | 3782/6717 [12:54<09:58,  4.91it/s]

Processing tickers:  56%|█████▋    | 3783/6717 [12:54<09:56,  4.92it/s]

Processing tickers:  56%|█████▋    | 3784/6717 [12:54<09:52,  4.95it/s]

Processing tickers:  56%|█████▋    | 3785/6717 [12:54<09:53,  4.94it/s]

Processing tickers:  56%|█████▋    | 3786/6717 [12:55<09:53,  4.93it/s]

Processing tickers:  56%|█████▋    | 3787/6717 [12:55<09:52,  4.94it/s]

Processing tickers:  56%|█████▋    | 3788/6717 [12:55<09:53,  4.93it/s]

Processing tickers:  56%|█████▋    | 3789/6717 [12:55<10:06,  4.83it/s]

Processing tickers:  56%|█████▋    | 3790/6717 [12:55<09:59,  4.88it/s]

Processing tickers:  56%|█████▋    | 3791/6717 [12:56<09:54,  4.93it/s]

Processing tickers:  56%|█████▋    | 3792/6717 [12:56<09:50,  4.96it/s]

Processing tickers:  56%|█████▋    | 3793/6717 [12:56<09:49,  4.96it/s]

Processing tickers:  56%|█████▋    | 3794/6717 [12:56<09:45,  4.99it/s]

Processing tickers:  56%|█████▋    | 3795/6717 [12:56<09:50,  4.95it/s]

Processing tickers:  57%|█████▋    | 3796/6717 [12:57<09:51,  4.94it/s]

Processing tickers:  57%|█████▋    | 3797/6717 [12:57<09:53,  4.92it/s]

Processing tickers:  57%|█████▋    | 3798/6717 [12:57<09:53,  4.92it/s]

Processing tickers:  57%|█████▋    | 3799/6717 [12:57<09:52,  4.93it/s]

Processing tickers:  57%|█████▋    | 3800/6717 [12:57<09:49,  4.95it/s]

Processing tickers:  57%|█████▋    | 3801/6717 [12:58<09:52,  4.92it/s]

Processing tickers:  57%|█████▋    | 3802/6717 [12:58<10:08,  4.79it/s]

Processing tickers:  57%|█████▋    | 3803/6717 [12:58<10:07,  4.79it/s]

Processing tickers:  57%|█████▋    | 3804/6717 [12:58<10:04,  4.82it/s]

Processing tickers:  57%|█████▋    | 3805/6717 [12:58<10:07,  4.79it/s]

Processing tickers:  57%|█████▋    | 3806/6717 [12:59<10:08,  4.78it/s]

Processing tickers:  57%|█████▋    | 3807/6717 [12:59<10:20,  4.69it/s]

Processing tickers:  57%|█████▋    | 3808/6717 [12:59<10:16,  4.72it/s]

Processing tickers:  57%|█████▋    | 3809/6717 [12:59<10:10,  4.77it/s]

Processing tickers:  57%|█████▋    | 3810/6717 [12:59<10:15,  4.72it/s]

Processing tickers:  57%|█████▋    | 3811/6717 [13:00<10:04,  4.81it/s]

Processing tickers:  57%|█████▋    | 3812/6717 [13:00<10:14,  4.73it/s]

Processing tickers:  57%|█████▋    | 3813/6717 [13:00<10:06,  4.79it/s]

Processing tickers:  57%|█████▋    | 3814/6717 [13:00<10:00,  4.83it/s]

Processing tickers:  57%|█████▋    | 3815/6717 [13:00<09:55,  4.87it/s]

Processing tickers:  57%|█████▋    | 3816/6717 [13:01<09:54,  4.88it/s]

Processing tickers:  57%|█████▋    | 3817/6717 [13:01<09:49,  4.92it/s]

Processing tickers:  57%|█████▋    | 3818/6717 [13:01<09:48,  4.93it/s]

Processing tickers:  57%|█████▋    | 3819/6717 [13:01<10:06,  4.78it/s]

Processing tickers:  57%|█████▋    | 3820/6717 [13:02<10:01,  4.81it/s]

Processing tickers:  57%|█████▋    | 3821/6717 [13:02<10:03,  4.80it/s]

Processing tickers:  57%|█████▋    | 3822/6717 [13:02<10:01,  4.81it/s]

Processing tickers:  57%|█████▋    | 3823/6717 [13:02<09:59,  4.82it/s]

Processing tickers:  57%|█████▋    | 3824/6717 [13:02<09:57,  4.84it/s]

Processing tickers:  57%|█████▋    | 3825/6717 [13:03<10:08,  4.75it/s]

Processing tickers:  57%|█████▋    | 3826/6717 [13:03<10:03,  4.79it/s]

Processing tickers:  57%|█████▋    | 3827/6717 [13:03<10:00,  4.81it/s]

Processing tickers:  57%|█████▋    | 3828/6717 [13:03<09:59,  4.82it/s]

Processing tickers:  57%|█████▋    | 3829/6717 [13:03<09:57,  4.83it/s]

Processing tickers:  57%|█████▋    | 3830/6717 [13:04<09:52,  4.87it/s]

Processing tickers:  57%|█████▋    | 3831/6717 [13:04<09:48,  4.91it/s]

Processing tickers:  57%|█████▋    | 3832/6717 [13:04<09:56,  4.83it/s]

Processing tickers:  57%|█████▋    | 3833/6717 [13:04<09:50,  4.89it/s]

Processing tickers:  57%|█████▋    | 3834/6717 [13:04<09:54,  4.85it/s]

Processing tickers:  57%|█████▋    | 3835/6717 [13:05<09:48,  4.89it/s]

Processing tickers:  57%|█████▋    | 3836/6717 [13:05<09:47,  4.90it/s]

Processing tickers:  57%|█████▋    | 3837/6717 [13:05<09:46,  4.91it/s]

Processing tickers:  57%|█████▋    | 3838/6717 [13:05<09:42,  4.95it/s]

Processing tickers:  57%|█████▋    | 3839/6717 [13:05<09:56,  4.82it/s]

Processing tickers:  57%|█████▋    | 3840/6717 [13:06<09:53,  4.84it/s]

Processing tickers:  57%|█████▋    | 3841/6717 [13:06<09:50,  4.87it/s]

Processing tickers:  57%|█████▋    | 3842/6717 [13:06<09:46,  4.90it/s]

Processing tickers:  57%|█████▋    | 3843/6717 [13:06<09:43,  4.92it/s]

Processing tickers:  57%|█████▋    | 3844/6717 [13:06<09:40,  4.95it/s]

Processing tickers:  57%|█████▋    | 3845/6717 [13:07<09:41,  4.94it/s]

Processing tickers:  57%|█████▋    | 3846/6717 [13:07<09:41,  4.94it/s]

Processing tickers:  57%|█████▋    | 3847/6717 [13:07<09:41,  4.94it/s]

Processing tickers:  57%|█████▋    | 3848/6717 [13:07<09:37,  4.97it/s]

Processing tickers:  57%|█████▋    | 3849/6717 [13:07<09:49,  4.87it/s]

Processing tickers:  57%|█████▋    | 3850/6717 [13:08<09:53,  4.83it/s]

Processing tickers:  57%|█████▋    | 3851/6717 [13:08<09:47,  4.88it/s]

Processing tickers:  57%|█████▋    | 3852/6717 [13:08<09:44,  4.90it/s]

Processing tickers:  57%|█████▋    | 3853/6717 [13:08<09:42,  4.91it/s]

Processing tickers:  57%|█████▋    | 3854/6717 [13:08<09:40,  4.93it/s]

Processing tickers:  57%|█████▋    | 3855/6717 [13:09<09:38,  4.95it/s]

Processing tickers:  57%|█████▋    | 3856/6717 [13:09<09:40,  4.93it/s]

Processing tickers:  57%|█████▋    | 3857/6717 [13:09<09:39,  4.94it/s]

Processing tickers:  57%|█████▋    | 3858/6717 [13:09<09:34,  4.98it/s]

Processing tickers:  57%|█████▋    | 3859/6717 [13:10<09:43,  4.90it/s]

Processing tickers:  57%|█████▋    | 3860/6717 [13:10<09:40,  4.92it/s]

Processing tickers:  57%|█████▋    | 3861/6717 [13:10<09:44,  4.88it/s]

Processing tickers:  57%|█████▋    | 3862/6717 [13:10<09:44,  4.89it/s]

Processing tickers:  58%|█████▊    | 3863/6717 [13:10<09:46,  4.86it/s]

Processing tickers:  58%|█████▊    | 3864/6717 [13:11<09:46,  4.86it/s]

Processing tickers:  58%|█████▊    | 3865/6717 [13:11<09:44,  4.88it/s]

Processing tickers:  58%|█████▊    | 3866/6717 [13:11<09:41,  4.91it/s]

Processing tickers:  58%|█████▊    | 3867/6717 [13:11<09:38,  4.93it/s]

Processing tickers:  58%|█████▊    | 3868/6717 [13:11<09:36,  4.94it/s]

Processing tickers:  58%|█████▊    | 3869/6717 [13:12<09:38,  4.92it/s]

Processing tickers:  58%|█████▊    | 3870/6717 [13:12<09:43,  4.88it/s]

Processing tickers:  58%|█████▊    | 3871/6717 [13:12<09:37,  4.93it/s]

Processing tickers:  58%|█████▊    | 3872/6717 [13:12<09:34,  4.96it/s]

Processing tickers:  58%|█████▊    | 3873/6717 [13:12<09:30,  4.99it/s]

Processing tickers:  58%|█████▊    | 3874/6717 [13:13<09:28,  5.00it/s]

Processing tickers:  58%|█████▊    | 3875/6717 [13:13<09:38,  4.91it/s]

Processing tickers:  58%|█████▊    | 3876/6717 [13:13<09:35,  4.94it/s]

Processing tickers:  58%|█████▊    | 3877/6717 [13:13<09:34,  4.95it/s]

Processing tickers:  58%|█████▊    | 3878/6717 [13:13<09:34,  4.94it/s]

Processing tickers:  58%|█████▊    | 3879/6717 [13:14<09:41,  4.88it/s]

Processing tickers:  58%|█████▊    | 3880/6717 [13:14<09:46,  4.84it/s]

Processing tickers:  58%|█████▊    | 3881/6717 [13:14<10:03,  4.70it/s]

Processing tickers:  58%|█████▊    | 3882/6717 [13:14<09:51,  4.79it/s]

Processing tickers:  58%|█████▊    | 3883/6717 [13:14<09:48,  4.82it/s]

Processing tickers:  58%|█████▊    | 3884/6717 [13:15<10:18,  4.58it/s]

Processing tickers:  58%|█████▊    | 3885/6717 [13:15<10:04,  4.68it/s]

Processing tickers:  58%|█████▊    | 3886/6717 [13:15<09:57,  4.74it/s]

Processing tickers:  58%|█████▊    | 3887/6717 [13:15<09:50,  4.79it/s]

Processing tickers:  58%|█████▊    | 3888/6717 [13:15<09:46,  4.83it/s]

Processing tickers:  58%|█████▊    | 3889/6717 [13:16<09:39,  4.88it/s]

Processing tickers:  58%|█████▊    | 3890/6717 [13:16<10:52,  4.33it/s]

Processing tickers:  58%|█████▊    | 3891/6717 [13:16<10:30,  4.48it/s]

Processing tickers:  58%|█████▊    | 3892/6717 [13:16<10:30,  4.48it/s]

Processing tickers:  58%|█████▊    | 3893/6717 [13:17<10:10,  4.62it/s]

Processing tickers:  58%|█████▊    | 3894/6717 [13:17<10:06,  4.65it/s]

Processing tickers:  58%|█████▊    | 3895/6717 [13:17<10:19,  4.56it/s]

Processing tickers:  58%|█████▊    | 3896/6717 [13:17<10:03,  4.68it/s]

Processing tickers:  58%|█████▊    | 3897/6717 [13:17<09:52,  4.76it/s]

Processing tickers:  58%|█████▊    | 3898/6717 [13:18<10:03,  4.67it/s]

Processing tickers:  58%|█████▊    | 3899/6717 [13:18<09:59,  4.70it/s]

Processing tickers:  58%|█████▊    | 3900/6717 [13:18<09:50,  4.77it/s]

Processing tickers:  58%|█████▊    | 3901/6717 [13:18<09:42,  4.83it/s]

Processing tickers:  58%|█████▊    | 3902/6717 [13:18<09:53,  4.74it/s]

Processing tickers:  58%|█████▊    | 3903/6717 [13:19<09:44,  4.82it/s]

Processing tickers:  58%|█████▊    | 3904/6717 [13:19<09:34,  4.89it/s]

Processing tickers:  58%|█████▊    | 3905/6717 [13:19<09:40,  4.85it/s]

Processing tickers:  58%|█████▊    | 3906/6717 [13:19<09:37,  4.87it/s]

Processing tickers:  58%|█████▊    | 3907/6717 [13:20<09:31,  4.92it/s]

Processing tickers:  58%|█████▊    | 3908/6717 [13:20<09:32,  4.90it/s]

Processing tickers:  58%|█████▊    | 3909/6717 [13:20<09:30,  4.93it/s]

Processing tickers:  58%|█████▊    | 3910/6717 [13:20<09:27,  4.95it/s]

Processing tickers:  58%|█████▊    | 3911/6717 [13:20<09:27,  4.94it/s]

Processing tickers:  58%|█████▊    | 3912/6717 [13:21<09:30,  4.92it/s]

Processing tickers:  58%|█████▊    | 3913/6717 [13:21<09:27,  4.94it/s]

Processing tickers:  58%|█████▊    | 3914/6717 [13:21<09:32,  4.89it/s]

Processing tickers:  58%|█████▊    | 3915/6717 [13:21<09:28,  4.93it/s]

Processing tickers:  58%|█████▊    | 3916/6717 [13:21<09:32,  4.89it/s]

Processing tickers:  58%|█████▊    | 3917/6717 [13:22<09:31,  4.90it/s]

Processing tickers:  58%|█████▊    | 3918/6717 [13:22<09:28,  4.92it/s]

Processing tickers:  58%|█████▊    | 3919/6717 [13:22<09:41,  4.81it/s]

Processing tickers:  58%|█████▊    | 3920/6717 [13:22<09:35,  4.86it/s]

Processing tickers:  58%|█████▊    | 3921/6717 [13:22<09:34,  4.86it/s]

Processing tickers:  58%|█████▊    | 3922/6717 [13:23<09:32,  4.89it/s]

Processing tickers:  58%|█████▊    | 3923/6717 [13:23<09:30,  4.90it/s]

Processing tickers:  58%|█████▊    | 3924/6717 [13:23<09:28,  4.91it/s]

Processing tickers:  58%|█████▊    | 3925/6717 [13:23<09:24,  4.94it/s]

Processing tickers:  58%|█████▊    | 3926/6717 [13:23<09:23,  4.95it/s]

Processing tickers:  58%|█████▊    | 3927/6717 [13:24<09:20,  4.98it/s]

Processing tickers:  58%|█████▊    | 3928/6717 [13:24<09:19,  4.99it/s]

Processing tickers:  58%|█████▊    | 3929/6717 [13:24<09:19,  4.98it/s]

Processing tickers:  59%|█████▊    | 3930/6717 [13:24<09:19,  4.98it/s]

Processing tickers:  59%|█████▊    | 3931/6717 [13:24<09:24,  4.94it/s]

Processing tickers:  59%|█████▊    | 3932/6717 [13:25<09:27,  4.91it/s]

Processing tickers:  59%|█████▊    | 3933/6717 [13:25<09:24,  4.93it/s]

Processing tickers:  59%|█████▊    | 3934/6717 [13:25<09:30,  4.88it/s]

Processing tickers:  59%|█████▊    | 3935/6717 [13:25<09:24,  4.93it/s]

Processing tickers:  59%|█████▊    | 3936/6717 [13:25<09:27,  4.90it/s]

Processing tickers:  59%|█████▊    | 3937/6717 [13:26<09:24,  4.92it/s]

Processing tickers:  59%|█████▊    | 3938/6717 [13:26<09:28,  4.89it/s]

Processing tickers:  59%|█████▊    | 3939/6717 [13:26<09:36,  4.82it/s]

Processing tickers:  59%|█████▊    | 3940/6717 [13:26<09:27,  4.90it/s]

Processing tickers:  59%|█████▊    | 3941/6717 [13:26<09:25,  4.91it/s]

Processing tickers:  59%|█████▊    | 3942/6717 [13:27<09:23,  4.92it/s]

Processing tickers:  59%|█████▊    | 3943/6717 [13:27<09:21,  4.94it/s]

Processing tickers:  59%|█████▊    | 3944/6717 [13:27<09:19,  4.96it/s]

Processing tickers:  59%|█████▊    | 3945/6717 [13:27<09:19,  4.96it/s]

Processing tickers:  59%|█████▊    | 3946/6717 [13:27<09:17,  4.97it/s]

Processing tickers:  59%|█████▉    | 3947/6717 [13:28<09:17,  4.97it/s]

Processing tickers:  59%|█████▉    | 3948/6717 [13:28<09:20,  4.94it/s]

Processing tickers:  59%|█████▉    | 3949/6717 [13:28<09:23,  4.91it/s]

Processing tickers:  59%|█████▉    | 3950/6717 [13:28<09:25,  4.90it/s]

Processing tickers:  59%|█████▉    | 3951/6717 [13:28<09:22,  4.92it/s]

Processing tickers:  59%|█████▉    | 3952/6717 [13:29<09:20,  4.94it/s]

Processing tickers:  59%|█████▉    | 3953/6717 [13:29<09:17,  4.95it/s]

Processing tickers:  59%|█████▉    | 3954/6717 [13:29<09:16,  4.97it/s]

Processing tickers:  59%|█████▉    | 3955/6717 [13:29<09:16,  4.96it/s]

Processing tickers:  59%|█████▉    | 3956/6717 [13:29<09:16,  4.96it/s]

Processing tickers:  59%|█████▉    | 3957/6717 [13:30<09:15,  4.97it/s]

Processing tickers:  59%|█████▉    | 3958/6717 [13:30<09:13,  4.99it/s]

Processing tickers:  59%|█████▉    | 3959/6717 [13:30<10:13,  4.50it/s]

Processing tickers:  59%|█████▉    | 3960/6717 [13:30<09:52,  4.65it/s]

Processing tickers:  59%|█████▉    | 3961/6717 [13:31<09:42,  4.73it/s]

Processing tickers:  59%|█████▉    | 3962/6717 [13:31<09:33,  4.81it/s]

Processing tickers:  59%|█████▉    | 3963/6717 [13:31<09:24,  4.88it/s]

Processing tickers:  59%|█████▉    | 3964/6717 [13:31<09:22,  4.90it/s]

Processing tickers:  59%|█████▉    | 3965/6717 [13:31<09:19,  4.92it/s]

Processing tickers:  59%|█████▉    | 3966/6717 [13:32<09:15,  4.95it/s]

Processing tickers:  59%|█████▉    | 3967/6717 [13:32<09:15,  4.95it/s]

Processing tickers:  59%|█████▉    | 3968/6717 [13:32<09:13,  4.97it/s]

Processing tickers:  59%|█████▉    | 3969/6717 [13:32<09:13,  4.96it/s]

Processing tickers:  59%|█████▉    | 3970/6717 [13:32<09:16,  4.93it/s]

Processing tickers:  59%|█████▉    | 3971/6717 [13:33<09:15,  4.95it/s]

Processing tickers:  59%|█████▉    | 3972/6717 [13:33<09:12,  4.96it/s]

Processing tickers:  59%|█████▉    | 3973/6717 [13:33<09:10,  4.99it/s]

Processing tickers:  59%|█████▉    | 3974/6717 [13:33<09:31,  4.80it/s]

Processing tickers:  59%|█████▉    | 3975/6717 [13:33<09:35,  4.76it/s]

Processing tickers:  59%|█████▉    | 3976/6717 [13:34<09:28,  4.82it/s]

Processing tickers:  59%|█████▉    | 3977/6717 [13:34<09:23,  4.87it/s]

Processing tickers:  59%|█████▉    | 3978/6717 [13:34<09:17,  4.91it/s]

Processing tickers:  59%|█████▉    | 3979/6717 [13:34<09:13,  4.94it/s]

Processing tickers:  59%|█████▉    | 3980/6717 [13:34<09:12,  4.95it/s]

Processing tickers:  59%|█████▉    | 3981/6717 [13:35<09:22,  4.86it/s]

Processing tickers:  59%|█████▉    | 3982/6717 [13:35<09:20,  4.88it/s]

Processing tickers:  59%|█████▉    | 3983/6717 [13:35<09:22,  4.86it/s]

Processing tickers:  59%|█████▉    | 3984/6717 [13:35<09:21,  4.86it/s]

Processing tickers:  59%|█████▉    | 3985/6717 [13:35<09:17,  4.90it/s]

Processing tickers:  59%|█████▉    | 3986/6717 [13:36<09:14,  4.92it/s]

Processing tickers:  59%|█████▉    | 3987/6717 [13:36<09:12,  4.94it/s]

Processing tickers:  59%|█████▉    | 3988/6717 [13:36<09:24,  4.83it/s]

Processing tickers:  59%|█████▉    | 3989/6717 [13:36<09:19,  4.88it/s]

Processing tickers:  59%|█████▉    | 3990/6717 [13:36<09:16,  4.90it/s]

Processing tickers:  59%|█████▉    | 3991/6717 [13:37<09:21,  4.86it/s]

Processing tickers:  59%|█████▉    | 3992/6717 [13:37<09:15,  4.90it/s]

Processing tickers:  59%|█████▉    | 3993/6717 [13:37<09:14,  4.92it/s]

Processing tickers:  59%|█████▉    | 3994/6717 [13:37<09:09,  4.96it/s]

Processing tickers:  59%|█████▉    | 3995/6717 [13:37<09:12,  4.93it/s]

Processing tickers:  59%|█████▉    | 3996/6717 [13:38<09:10,  4.94it/s]

Processing tickers:  60%|█████▉    | 3997/6717 [13:38<09:09,  4.95it/s]

Processing tickers:  60%|█████▉    | 3998/6717 [13:38<09:07,  4.97it/s]

Processing tickers:  60%|█████▉    | 3999/6717 [13:38<09:25,  4.81it/s]

Processing tickers:  60%|█████▉    | 4000/6717 [13:38<09:19,  4.86it/s]

Processing tickers:  60%|█████▉    | 4001/6717 [13:39<09:17,  4.87it/s]

Processing tickers:  60%|█████▉    | 4002/6717 [13:39<09:11,  4.93it/s]

Processing tickers:  60%|█████▉    | 4003/6717 [13:39<09:09,  4.94it/s]

Processing tickers:  60%|█████▉    | 4004/6717 [13:39<09:09,  4.93it/s]

Processing tickers:  60%|█████▉    | 4005/6717 [13:39<09:09,  4.94it/s]

Processing tickers:  60%|█████▉    | 4006/6717 [13:40<09:06,  4.96it/s]

Processing tickers:  60%|█████▉    | 4007/6717 [13:40<09:05,  4.97it/s]

Processing tickers:  60%|█████▉    | 4008/6717 [13:40<09:07,  4.95it/s]

Processing tickers:  60%|█████▉    | 4009/6717 [13:40<09:04,  4.97it/s]

Processing tickers:  60%|█████▉    | 4010/6717 [13:40<09:04,  4.97it/s]

Processing tickers:  60%|█████▉    | 4011/6717 [13:41<09:03,  4.97it/s]

Processing tickers:  60%|█████▉    | 4012/6717 [13:41<09:02,  4.99it/s]

Processing tickers:  60%|█████▉    | 4013/6717 [13:41<09:01,  4.99it/s]

Processing tickers:  60%|█████▉    | 4014/6717 [13:41<09:01,  4.99it/s]

Processing tickers:  60%|█████▉    | 4015/6717 [13:41<09:04,  4.97it/s]

Processing tickers:  60%|█████▉    | 4016/6717 [13:42<09:09,  4.92it/s]

Processing tickers:  60%|█████▉    | 4017/6717 [13:42<09:05,  4.95it/s]

Processing tickers:  60%|█████▉    | 4018/6717 [13:42<09:15,  4.86it/s]

Processing tickers:  60%|█████▉    | 4019/6717 [13:42<09:10,  4.90it/s]

Processing tickers:  60%|█████▉    | 4020/6717 [13:43<09:10,  4.90it/s]

Processing tickers:  60%|█████▉    | 4021/6717 [13:43<09:08,  4.91it/s]

Processing tickers:  60%|█████▉    | 4022/6717 [13:43<09:08,  4.91it/s]

Processing tickers:  60%|█████▉    | 4023/6717 [13:43<09:26,  4.76it/s]

Processing tickers:  60%|█████▉    | 4024/6717 [13:43<09:23,  4.78it/s]

Processing tickers:  60%|█████▉    | 4025/6717 [13:44<09:17,  4.83it/s]

Processing tickers:  60%|█████▉    | 4026/6717 [13:44<09:10,  4.89it/s]

Processing tickers:  60%|█████▉    | 4027/6717 [13:44<09:08,  4.91it/s]

Processing tickers:  60%|█████▉    | 4028/6717 [13:44<09:06,  4.92it/s]

Processing tickers:  60%|█████▉    | 4029/6717 [13:44<09:05,  4.93it/s]

Processing tickers:  60%|█████▉    | 4030/6717 [13:45<09:11,  4.87it/s]

Processing tickers:  60%|██████    | 4031/6717 [13:45<09:10,  4.88it/s]

Processing tickers:  60%|██████    | 4032/6717 [13:45<09:07,  4.91it/s]

Processing tickers:  60%|██████    | 4033/6717 [13:45<09:16,  4.83it/s]

Processing tickers:  60%|██████    | 4034/6717 [13:45<09:10,  4.88it/s]

Processing tickers:  60%|██████    | 4035/6717 [13:46<09:07,  4.90it/s]

Processing tickers:  60%|██████    | 4036/6717 [13:46<09:03,  4.93it/s]

Processing tickers:  60%|██████    | 4037/6717 [13:46<09:06,  4.90it/s]

Processing tickers:  60%|██████    | 4038/6717 [13:46<09:26,  4.73it/s]

Processing tickers:  60%|██████    | 4039/6717 [13:46<09:18,  4.79it/s]

Processing tickers:  60%|██████    | 4040/6717 [13:47<09:16,  4.81it/s]

Processing tickers:  60%|██████    | 4041/6717 [13:47<09:08,  4.88it/s]

Processing tickers:  60%|██████    | 4042/6717 [13:47<09:10,  4.86it/s]

Processing tickers:  60%|██████    | 4043/6717 [13:47<09:10,  4.86it/s]

Processing tickers:  60%|██████    | 4044/6717 [13:47<09:06,  4.89it/s]

Processing tickers:  60%|██████    | 4045/6717 [13:48<09:02,  4.93it/s]

Processing tickers:  60%|██████    | 4046/6717 [13:48<09:00,  4.94it/s]

Processing tickers:  60%|██████    | 4047/6717 [13:48<08:57,  4.97it/s]

Processing tickers:  60%|██████    | 4048/6717 [13:48<08:57,  4.97it/s]

Processing tickers:  60%|██████    | 4049/6717 [13:48<08:55,  4.98it/s]

Processing tickers:  60%|██████    | 4050/6717 [13:49<08:56,  4.97it/s]

Processing tickers:  60%|██████    | 4051/6717 [13:49<08:54,  4.99it/s]

Processing tickers:  60%|██████    | 4052/6717 [13:49<08:55,  4.98it/s]

Processing tickers:  60%|██████    | 4053/6717 [13:49<08:53,  5.00it/s]

Processing tickers:  60%|██████    | 4054/6717 [13:49<08:53,  4.99it/s]

Processing tickers:  60%|██████    | 4055/6717 [13:50<08:55,  4.97it/s]

Processing tickers:  60%|██████    | 4056/6717 [13:50<08:58,  4.95it/s]

Processing tickers:  60%|██████    | 4057/6717 [13:50<08:54,  4.98it/s]

Processing tickers:  60%|██████    | 4058/6717 [13:50<08:53,  4.99it/s]

Processing tickers:  60%|██████    | 4059/6717 [13:50<08:53,  4.98it/s]

Processing tickers:  60%|██████    | 4060/6717 [13:51<08:53,  4.98it/s]

Processing tickers:  60%|██████    | 4061/6717 [13:51<09:13,  4.80it/s]

Processing tickers:  60%|██████    | 4062/6717 [13:51<09:05,  4.87it/s]

Processing tickers:  60%|██████    | 4063/6717 [13:51<09:06,  4.85it/s]

Processing tickers:  61%|██████    | 4064/6717 [13:51<09:01,  4.90it/s]

Processing tickers:  61%|██████    | 4065/6717 [13:52<08:59,  4.91it/s]

Processing tickers:  61%|██████    | 4066/6717 [13:52<08:55,  4.95it/s]

Processing tickers:  61%|██████    | 4067/6717 [13:52<08:53,  4.97it/s]

Processing tickers:  61%|██████    | 4068/6717 [13:52<08:51,  4.99it/s]

Processing tickers:  61%|██████    | 4069/6717 [13:52<08:48,  5.01it/s]

Processing tickers:  61%|██████    | 4070/6717 [13:53<08:48,  5.01it/s]

Processing tickers:  61%|██████    | 4071/6717 [13:53<08:46,  5.02it/s]

Processing tickers:  61%|██████    | 4072/6717 [13:53<08:46,  5.02it/s]

Processing tickers:  61%|██████    | 4073/6717 [13:53<08:49,  5.00it/s]

Processing tickers:  61%|██████    | 4074/6717 [13:53<08:48,  5.00it/s]

Processing tickers:  61%|██████    | 4075/6717 [13:54<08:45,  5.03it/s]

Processing tickers:  61%|██████    | 4076/6717 [13:54<08:45,  5.02it/s]

Processing tickers:  61%|██████    | 4077/6717 [13:54<08:47,  5.00it/s]

Processing tickers:  61%|██████    | 4078/6717 [13:54<08:47,  5.00it/s]

Processing tickers:  61%|██████    | 4079/6717 [13:54<08:47,  5.00it/s]

Processing tickers:  61%|██████    | 4080/6717 [13:55<08:48,  4.99it/s]

Processing tickers:  61%|██████    | 4081/6717 [13:55<08:55,  4.92it/s]

Processing tickers:  61%|██████    | 4082/6717 [13:55<08:54,  4.93it/s]

Processing tickers:  61%|██████    | 4083/6717 [13:55<08:52,  4.95it/s]

Processing tickers:  61%|██████    | 4084/6717 [13:55<08:50,  4.97it/s]

Processing tickers:  61%|██████    | 4085/6717 [13:56<08:48,  4.98it/s]

Processing tickers:  61%|██████    | 4086/6717 [13:56<08:51,  4.95it/s]

Processing tickers:  61%|██████    | 4087/6717 [13:56<08:49,  4.97it/s]

Processing tickers:  61%|██████    | 4088/6717 [13:56<08:49,  4.96it/s]

Processing tickers:  61%|██████    | 4089/6717 [13:57<08:48,  4.98it/s]

Processing tickers:  61%|██████    | 4090/6717 [13:57<08:48,  4.98it/s]

Processing tickers:  61%|██████    | 4091/6717 [13:57<08:45,  4.99it/s]

Processing tickers:  61%|██████    | 4092/6717 [13:57<08:47,  4.98it/s]

Processing tickers:  61%|██████    | 4093/6717 [13:57<08:45,  4.99it/s]

Processing tickers:  61%|██████    | 4094/6717 [13:58<08:49,  4.95it/s]

Processing tickers:  61%|██████    | 4095/6717 [13:58<08:54,  4.91it/s]

Processing tickers:  61%|██████    | 4096/6717 [13:58<08:47,  4.97it/s]

Processing tickers:  61%|██████    | 4097/6717 [13:58<08:45,  4.98it/s]

Processing tickers:  61%|██████    | 4098/6717 [13:58<08:48,  4.96it/s]

Processing tickers:  61%|██████    | 4099/6717 [13:59<08:48,  4.96it/s]

Processing tickers:  61%|██████    | 4100/6717 [13:59<08:45,  4.98it/s]

Processing tickers:  61%|██████    | 4101/6717 [13:59<08:45,  4.98it/s]

Processing tickers:  61%|██████    | 4102/6717 [13:59<08:48,  4.95it/s]

Processing tickers:  61%|██████    | 4103/6717 [13:59<08:46,  4.97it/s]

Processing tickers:  61%|██████    | 4104/6717 [14:00<08:49,  4.94it/s]

Processing tickers:  61%|██████    | 4105/6717 [14:00<08:47,  4.95it/s]

Processing tickers:  61%|██████    | 4106/6717 [14:00<08:50,  4.93it/s]

Processing tickers:  61%|██████    | 4107/6717 [14:00<08:48,  4.94it/s]

Processing tickers:  61%|██████    | 4108/6717 [14:00<08:48,  4.94it/s]

Processing tickers:  61%|██████    | 4109/6717 [14:01<08:46,  4.95it/s]

Processing tickers:  61%|██████    | 4110/6717 [14:01<08:45,  4.96it/s]

Processing tickers:  61%|██████    | 4111/6717 [14:01<08:44,  4.97it/s]

Processing tickers:  61%|██████    | 4112/6717 [14:01<08:53,  4.89it/s]

Processing tickers:  61%|██████    | 4113/6717 [14:01<08:48,  4.93it/s]

Processing tickers:  61%|██████    | 4114/6717 [14:02<08:47,  4.94it/s]

Processing tickers:  61%|██████▏   | 4115/6717 [14:02<08:43,  4.97it/s]

Processing tickers:  61%|██████▏   | 4116/6717 [14:02<08:43,  4.97it/s]

Processing tickers:  61%|██████▏   | 4117/6717 [14:02<08:40,  4.99it/s]

Processing tickers:  61%|██████▏   | 4118/6717 [14:02<08:41,  4.99it/s]

Processing tickers:  61%|██████▏   | 4119/6717 [14:03<08:43,  4.97it/s]

Processing tickers:  61%|██████▏   | 4120/6717 [14:03<08:50,  4.89it/s]

Processing tickers:  61%|██████▏   | 4121/6717 [14:03<08:47,  4.92it/s]

Processing tickers:  61%|██████▏   | 4122/6717 [14:03<08:48,  4.91it/s]

Processing tickers:  61%|██████▏   | 4123/6717 [14:03<08:45,  4.94it/s]

Processing tickers:  61%|██████▏   | 4124/6717 [14:04<08:46,  4.92it/s]

Processing tickers:  61%|██████▏   | 4125/6717 [14:04<08:47,  4.92it/s]

Processing tickers:  61%|██████▏   | 4126/6717 [14:04<08:51,  4.87it/s]

Processing tickers:  61%|██████▏   | 4127/6717 [14:04<08:51,  4.88it/s]

Processing tickers:  61%|██████▏   | 4128/6717 [14:04<08:44,  4.93it/s]

Processing tickers:  61%|██████▏   | 4129/6717 [14:05<08:48,  4.90it/s]

Processing tickers:  61%|██████▏   | 4130/6717 [14:05<08:58,  4.80it/s]

Processing tickers:  62%|██████▏   | 4131/6717 [14:05<09:05,  4.74it/s]

Processing tickers:  62%|██████▏   | 4132/6717 [14:05<08:58,  4.80it/s]

Processing tickers:  62%|██████▏   | 4133/6717 [14:05<09:02,  4.77it/s]

Processing tickers:  62%|██████▏   | 4134/6717 [14:06<08:53,  4.84it/s]

Processing tickers:  62%|██████▏   | 4135/6717 [14:06<08:45,  4.91it/s]

Processing tickers:  62%|██████▏   | 4136/6717 [14:06<08:42,  4.94it/s]

Processing tickers:  62%|██████▏   | 4137/6717 [14:06<08:44,  4.92it/s]

Processing tickers:  62%|██████▏   | 4138/6717 [14:06<08:42,  4.94it/s]

Processing tickers:  62%|██████▏   | 4139/6717 [14:07<08:40,  4.96it/s]

Processing tickers:  62%|██████▏   | 4140/6717 [14:07<08:45,  4.91it/s]

Processing tickers:  62%|██████▏   | 4141/6717 [14:07<08:41,  4.94it/s]

Processing tickers:  62%|██████▏   | 4142/6717 [14:07<08:39,  4.95it/s]

Processing tickers:  62%|██████▏   | 4143/6717 [14:07<08:38,  4.97it/s]

Processing tickers:  62%|██████▏   | 4144/6717 [14:08<08:36,  4.98it/s]

Processing tickers:  62%|██████▏   | 4145/6717 [14:08<08:34,  5.00it/s]

Processing tickers:  62%|██████▏   | 4146/6717 [14:08<08:34,  5.00it/s]

Processing tickers:  62%|██████▏   | 4147/6717 [14:08<08:35,  4.99it/s]

Processing tickers:  62%|██████▏   | 4148/6717 [14:08<08:33,  5.00it/s]

Processing tickers:  62%|██████▏   | 4149/6717 [14:09<08:36,  4.97it/s]

Processing tickers:  62%|██████▏   | 4150/6717 [14:09<08:34,  4.99it/s]

Processing tickers:  62%|██████▏   | 4151/6717 [14:09<08:33,  4.99it/s]

Processing tickers:  62%|██████▏   | 4152/6717 [14:09<08:37,  4.95it/s]

Processing tickers:  62%|██████▏   | 4153/6717 [14:09<08:34,  4.98it/s]

Processing tickers:  62%|██████▏   | 4154/6717 [14:10<08:31,  5.01it/s]

Processing tickers:  62%|██████▏   | 4155/6717 [14:10<08:32,  5.00it/s]

Processing tickers:  62%|██████▏   | 4156/6717 [14:10<08:32,  5.00it/s]

Processing tickers:  62%|██████▏   | 4157/6717 [14:10<08:31,  5.01it/s]

Processing tickers:  62%|██████▏   | 4158/6717 [14:10<08:29,  5.02it/s]

Processing tickers:  62%|██████▏   | 4159/6717 [14:11<08:29,  5.02it/s]

Processing tickers:  62%|██████▏   | 4160/6717 [14:11<08:29,  5.02it/s]

Processing tickers:  62%|██████▏   | 4161/6717 [14:11<08:32,  4.99it/s]

Processing tickers:  62%|██████▏   | 4162/6717 [14:11<08:33,  4.97it/s]

Processing tickers:  62%|██████▏   | 4163/6717 [14:11<08:33,  4.97it/s]

Processing tickers:  62%|██████▏   | 4164/6717 [14:12<08:31,  5.00it/s]

Processing tickers:  62%|██████▏   | 4165/6717 [14:12<08:36,  4.94it/s]

Processing tickers:  62%|██████▏   | 4166/6717 [14:12<08:38,  4.92it/s]

Processing tickers:  62%|██████▏   | 4167/6717 [14:12<08:36,  4.93it/s]

Processing tickers:  62%|██████▏   | 4168/6717 [14:12<08:39,  4.90it/s]

Processing tickers:  62%|██████▏   | 4169/6717 [14:13<08:45,  4.85it/s]

Processing tickers:  62%|██████▏   | 4170/6717 [14:13<08:41,  4.88it/s]

Processing tickers:  62%|██████▏   | 4171/6717 [14:13<08:36,  4.93it/s]

Processing tickers:  62%|██████▏   | 4172/6717 [14:13<08:35,  4.94it/s]

Processing tickers:  62%|██████▏   | 4173/6717 [14:13<08:35,  4.94it/s]

Processing tickers:  62%|██████▏   | 4174/6717 [14:14<08:34,  4.94it/s]

Processing tickers:  62%|██████▏   | 4175/6717 [14:14<08:32,  4.96it/s]

Processing tickers:  62%|██████▏   | 4176/6717 [14:14<08:41,  4.87it/s]

Processing tickers:  62%|██████▏   | 4177/6717 [14:14<08:37,  4.90it/s]

Processing tickers:  62%|██████▏   | 4178/6717 [14:15<08:36,  4.92it/s]

Processing tickers:  62%|██████▏   | 4179/6717 [14:15<08:32,  4.95it/s]

Processing tickers:  62%|██████▏   | 4180/6717 [14:15<08:32,  4.95it/s]

Processing tickers:  62%|██████▏   | 4181/6717 [14:15<08:28,  4.98it/s]

Processing tickers:  62%|██████▏   | 4182/6717 [14:15<08:29,  4.98it/s]

Processing tickers:  62%|██████▏   | 4183/6717 [14:16<08:29,  4.98it/s]

Processing tickers:  62%|██████▏   | 4184/6717 [14:16<08:28,  4.99it/s]

Processing tickers:  62%|██████▏   | 4185/6717 [14:16<08:28,  4.98it/s]

Processing tickers:  62%|██████▏   | 4186/6717 [14:16<08:26,  5.00it/s]

Processing tickers:  62%|██████▏   | 4187/6717 [14:16<08:27,  4.98it/s]

Processing tickers:  62%|██████▏   | 4188/6717 [14:17<08:29,  4.96it/s]

Processing tickers:  62%|██████▏   | 4189/6717 [14:17<08:35,  4.91it/s]

Processing tickers:  62%|██████▏   | 4190/6717 [14:17<08:32,  4.94it/s]

Processing tickers:  62%|██████▏   | 4191/6717 [14:17<08:29,  4.96it/s]

Processing tickers:  62%|██████▏   | 4192/6717 [14:17<08:27,  4.97it/s]

Processing tickers:  62%|██████▏   | 4193/6717 [14:18<08:30,  4.94it/s]

Processing tickers:  62%|██████▏   | 4194/6717 [14:18<08:30,  4.94it/s]

Processing tickers:  62%|██████▏   | 4195/6717 [14:18<08:36,  4.88it/s]

Processing tickers:  62%|██████▏   | 4196/6717 [14:18<08:35,  4.89it/s]

Processing tickers:  62%|██████▏   | 4197/6717 [14:18<08:32,  4.92it/s]

Processing tickers:  62%|██████▏   | 4198/6717 [14:19<08:32,  4.92it/s]

Processing tickers:  63%|██████▎   | 4199/6717 [14:19<08:28,  4.95it/s]

Processing tickers:  63%|██████▎   | 4200/6717 [14:19<08:25,  4.98it/s]

Processing tickers:  63%|██████▎   | 4201/6717 [14:19<08:26,  4.96it/s]

Processing tickers:  63%|██████▎   | 4202/6717 [14:19<08:27,  4.96it/s]

Processing tickers:  63%|██████▎   | 4203/6717 [14:20<08:30,  4.92it/s]

Processing tickers:  63%|██████▎   | 4204/6717 [14:20<08:26,  4.96it/s]

Processing tickers:  63%|██████▎   | 4205/6717 [14:20<08:26,  4.96it/s]

Processing tickers:  63%|██████▎   | 4206/6717 [14:20<08:27,  4.95it/s]

Processing tickers:  63%|██████▎   | 4207/6717 [14:20<08:25,  4.96it/s]

Processing tickers:  63%|██████▎   | 4208/6717 [14:21<08:20,  5.01it/s]

Processing tickers:  63%|██████▎   | 4209/6717 [14:21<08:23,  4.98it/s]

Processing tickers:  63%|██████▎   | 4210/6717 [14:21<08:23,  4.98it/s]

Processing tickers:  63%|██████▎   | 4211/6717 [14:21<08:26,  4.95it/s]

Processing tickers:  63%|██████▎   | 4212/6717 [14:21<08:25,  4.95it/s]

Processing tickers:  63%|██████▎   | 4213/6717 [14:22<08:23,  4.98it/s]

Processing tickers:  63%|██████▎   | 4214/6717 [14:22<08:23,  4.97it/s]

Processing tickers:  63%|██████▎   | 4215/6717 [14:22<08:24,  4.96it/s]

Processing tickers:  63%|██████▎   | 4216/6717 [14:22<08:24,  4.96it/s]

Processing tickers:  63%|██████▎   | 4217/6717 [14:22<08:23,  4.97it/s]

Processing tickers:  63%|██████▎   | 4218/6717 [14:23<08:22,  4.97it/s]

Processing tickers:  63%|██████▎   | 4219/6717 [14:23<08:27,  4.93it/s]

Processing tickers:  63%|██████▎   | 4220/6717 [14:23<08:29,  4.91it/s]

Processing tickers:  63%|██████▎   | 4221/6717 [14:23<08:35,  4.84it/s]

Processing tickers:  63%|██████▎   | 4222/6717 [14:23<08:30,  4.89it/s]

Processing tickers:  63%|██████▎   | 4223/6717 [14:24<08:29,  4.90it/s]

Processing tickers:  63%|██████▎   | 4224/6717 [14:24<08:28,  4.90it/s]

Processing tickers:  63%|██████▎   | 4225/6717 [14:24<08:35,  4.84it/s]

Processing tickers:  63%|██████▎   | 4226/6717 [14:24<08:33,  4.86it/s]

Processing tickers:  63%|██████▎   | 4227/6717 [14:24<08:28,  4.89it/s]

Processing tickers:  63%|██████▎   | 4228/6717 [14:25<08:24,  4.93it/s]

Processing tickers:  63%|██████▎   | 4229/6717 [14:25<08:24,  4.93it/s]

Processing tickers:  63%|██████▎   | 4230/6717 [14:25<08:27,  4.90it/s]

Processing tickers:  63%|██████▎   | 4231/6717 [14:25<08:25,  4.92it/s]

Processing tickers:  63%|██████▎   | 4232/6717 [14:25<08:25,  4.92it/s]

Processing tickers:  63%|██████▎   | 4233/6717 [14:26<08:34,  4.83it/s]

Processing tickers:  63%|██████▎   | 4234/6717 [14:26<08:31,  4.85it/s]

Processing tickers:  63%|██████▎   | 4235/6717 [14:26<08:30,  4.87it/s]

Processing tickers:  63%|██████▎   | 4236/6717 [14:26<08:26,  4.90it/s]

Processing tickers:  63%|██████▎   | 4237/6717 [14:26<08:28,  4.88it/s]

Processing tickers:  63%|██████▎   | 4238/6717 [14:27<08:26,  4.89it/s]

Processing tickers:  63%|██████▎   | 4239/6717 [14:27<08:25,  4.91it/s]

Processing tickers:  63%|██████▎   | 4240/6717 [14:27<08:26,  4.89it/s]

Processing tickers:  63%|██████▎   | 4241/6717 [14:27<08:21,  4.93it/s]

Processing tickers:  63%|██████▎   | 4242/6717 [14:27<08:19,  4.95it/s]

Processing tickers:  63%|██████▎   | 4243/6717 [14:28<08:18,  4.96it/s]

Processing tickers:  63%|██████▎   | 4244/6717 [14:28<08:17,  4.97it/s]

Processing tickers:  63%|██████▎   | 4245/6717 [14:28<08:14,  5.00it/s]

Processing tickers:  63%|██████▎   | 4246/6717 [14:28<08:13,  5.00it/s]

Processing tickers:  63%|██████▎   | 4247/6717 [14:28<08:18,  4.95it/s]

Processing tickers:  63%|██████▎   | 4248/6717 [14:29<08:20,  4.93it/s]

Processing tickers:  63%|██████▎   | 4249/6717 [14:29<08:19,  4.94it/s]

Processing tickers:  63%|██████▎   | 4250/6717 [14:29<08:20,  4.93it/s]

Processing tickers:  63%|██████▎   | 4251/6717 [14:29<08:19,  4.94it/s]

Processing tickers:  63%|██████▎   | 4252/6717 [14:30<08:19,  4.93it/s]

Processing tickers:  63%|██████▎   | 4253/6717 [14:30<08:19,  4.93it/s]

Processing tickers:  63%|██████▎   | 4254/6717 [14:30<08:16,  4.96it/s]

Processing tickers:  63%|██████▎   | 4255/6717 [14:30<08:14,  4.98it/s]

Processing tickers:  63%|██████▎   | 4256/6717 [14:30<08:13,  4.98it/s]

Processing tickers:  63%|██████▎   | 4257/6717 [14:31<08:13,  4.99it/s]

Processing tickers:  63%|██████▎   | 4258/6717 [14:31<08:12,  4.99it/s]

Processing tickers:  63%|██████▎   | 4259/6717 [14:31<08:12,  4.99it/s]

Processing tickers:  63%|██████▎   | 4260/6717 [14:31<08:17,  4.94it/s]

Processing tickers:  63%|██████▎   | 4261/6717 [14:31<08:19,  4.92it/s]

Processing tickers:  63%|██████▎   | 4262/6717 [14:32<08:16,  4.94it/s]

Processing tickers:  63%|██████▎   | 4263/6717 [14:32<08:13,  4.98it/s]

Processing tickers:  63%|██████▎   | 4264/6717 [14:32<08:12,  4.98it/s]

Processing tickers:  63%|██████▎   | 4265/6717 [14:32<08:15,  4.95it/s]

Processing tickers:  64%|██████▎   | 4266/6717 [14:32<08:14,  4.96it/s]

Processing tickers:  64%|██████▎   | 4267/6717 [14:33<08:11,  4.98it/s]

Processing tickers:  64%|██████▎   | 4268/6717 [14:33<08:11,  4.98it/s]

Processing tickers:  64%|██████▎   | 4269/6717 [14:33<08:10,  4.99it/s]

Processing tickers:  64%|██████▎   | 4270/6717 [14:33<08:10,  4.98it/s]

Processing tickers:  64%|██████▎   | 4271/6717 [14:33<08:09,  4.99it/s]

Processing tickers:  64%|██████▎   | 4272/6717 [14:34<08:09,  4.99it/s]

Processing tickers:  64%|██████▎   | 4273/6717 [14:34<08:08,  5.00it/s]

Processing tickers:  64%|██████▎   | 4274/6717 [14:34<08:08,  5.01it/s]

Processing tickers:  64%|██████▎   | 4275/6717 [14:34<08:07,  5.01it/s]

Processing tickers:  64%|██████▎   | 4276/6717 [14:34<08:08,  5.00it/s]

Processing tickers:  64%|██████▎   | 4277/6717 [14:35<08:10,  4.97it/s]

Processing tickers:  64%|██████▎   | 4278/6717 [14:35<08:16,  4.91it/s]

Processing tickers:  64%|██████▎   | 4279/6717 [14:35<08:16,  4.91it/s]

Processing tickers:  64%|██████▎   | 4280/6717 [14:35<08:12,  4.95it/s]

Processing tickers:  64%|██████▎   | 4281/6717 [14:35<08:10,  4.96it/s]

Processing tickers:  64%|██████▎   | 4282/6717 [14:36<08:11,  4.96it/s]

Processing tickers:  64%|██████▍   | 4283/6717 [14:36<08:10,  4.96it/s]

Processing tickers:  64%|██████▍   | 4284/6717 [14:36<08:09,  4.97it/s]

Processing tickers:  64%|██████▍   | 4285/6717 [14:36<08:12,  4.93it/s]

Processing tickers:  64%|██████▍   | 4286/6717 [14:36<08:25,  4.81it/s]

Processing tickers:  64%|██████▍   | 4287/6717 [14:37<08:19,  4.87it/s]

Processing tickers:  64%|██████▍   | 4288/6717 [14:37<08:18,  4.87it/s]

Processing tickers:  64%|██████▍   | 4289/6717 [14:37<08:16,  4.89it/s]

Processing tickers:  64%|██████▍   | 4290/6717 [14:37<08:11,  4.94it/s]

Processing tickers:  64%|██████▍   | 4291/6717 [14:37<08:11,  4.94it/s]

Processing tickers:  64%|██████▍   | 4292/6717 [14:38<08:10,  4.95it/s]

Processing tickers:  64%|██████▍   | 4293/6717 [14:38<08:13,  4.91it/s]

Processing tickers:  64%|██████▍   | 4294/6717 [14:38<08:21,  4.83it/s]

Processing tickers:  64%|██████▍   | 4295/6717 [14:38<08:20,  4.84it/s]

Processing tickers:  64%|██████▍   | 4296/6717 [14:38<08:17,  4.87it/s]

Processing tickers:  64%|██████▍   | 4297/6717 [14:39<08:15,  4.89it/s]

Processing tickers:  64%|██████▍   | 4298/6717 [14:39<08:12,  4.91it/s]

Processing tickers:  64%|██████▍   | 4299/6717 [14:39<08:15,  4.88it/s]

Processing tickers:  64%|██████▍   | 4300/6717 [14:39<08:15,  4.88it/s]

Processing tickers:  64%|██████▍   | 4301/6717 [14:39<08:15,  4.88it/s]

Processing tickers:  64%|██████▍   | 4302/6717 [14:40<08:14,  4.88it/s]

Processing tickers:  64%|██████▍   | 4303/6717 [14:40<08:10,  4.92it/s]

Processing tickers:  64%|██████▍   | 4304/6717 [14:40<08:06,  4.96it/s]

Processing tickers:  64%|██████▍   | 4305/6717 [14:40<08:08,  4.94it/s]

Processing tickers:  64%|██████▍   | 4306/6717 [14:40<08:06,  4.96it/s]

Processing tickers:  64%|██████▍   | 4307/6717 [14:41<08:04,  4.97it/s]

Processing tickers:  64%|██████▍   | 4308/6717 [14:41<08:08,  4.93it/s]

Processing tickers:  64%|██████▍   | 4309/6717 [14:41<08:12,  4.89it/s]

Processing tickers:  64%|██████▍   | 4310/6717 [14:41<08:11,  4.89it/s]

Processing tickers:  64%|██████▍   | 4311/6717 [14:41<08:13,  4.87it/s]

Processing tickers:  64%|██████▍   | 4312/6717 [14:42<08:10,  4.90it/s]

Processing tickers:  64%|██████▍   | 4313/6717 [14:42<08:17,  4.84it/s]

Processing tickers:  64%|██████▍   | 4314/6717 [14:42<08:14,  4.86it/s]

Processing tickers:  64%|██████▍   | 4315/6717 [14:42<08:17,  4.83it/s]

Processing tickers:  64%|██████▍   | 4316/6717 [14:42<08:18,  4.82it/s]

Processing tickers:  64%|██████▍   | 4317/6717 [14:43<08:11,  4.88it/s]

Processing tickers:  64%|██████▍   | 4318/6717 [14:43<08:07,  4.92it/s]

Processing tickers:  64%|██████▍   | 4319/6717 [14:43<08:05,  4.94it/s]

Processing tickers:  64%|██████▍   | 4320/6717 [14:43<08:05,  4.94it/s]

Processing tickers:  64%|██████▍   | 4321/6717 [14:44<08:04,  4.94it/s]

Processing tickers:  64%|██████▍   | 4322/6717 [14:44<08:01,  4.97it/s]

Processing tickers:  64%|██████▍   | 4323/6717 [14:44<08:01,  4.97it/s]

Processing tickers:  64%|██████▍   | 4324/6717 [14:44<07:59,  4.99it/s]

Processing tickers:  64%|██████▍   | 4325/6717 [14:44<08:12,  4.86it/s]

Processing tickers:  64%|██████▍   | 4326/6717 [14:45<08:18,  4.80it/s]

Processing tickers:  64%|██████▍   | 4327/6717 [14:45<08:13,  4.84it/s]

Processing tickers:  64%|██████▍   | 4328/6717 [14:45<08:08,  4.89it/s]

Processing tickers:  64%|██████▍   | 4329/6717 [14:45<08:05,  4.91it/s]

Processing tickers:  64%|██████▍   | 4330/6717 [14:45<08:03,  4.94it/s]

Processing tickers:  64%|██████▍   | 4331/6717 [14:46<08:03,  4.93it/s]

Processing tickers:  64%|██████▍   | 4332/6717 [14:46<08:03,  4.94it/s]

Processing tickers:  65%|██████▍   | 4333/6717 [14:46<08:02,  4.94it/s]

Processing tickers:  65%|██████▍   | 4334/6717 [14:46<08:05,  4.91it/s]

Processing tickers:  65%|██████▍   | 4335/6717 [14:46<08:13,  4.83it/s]

Processing tickers:  65%|██████▍   | 4336/6717 [14:47<08:08,  4.87it/s]

Processing tickers:  65%|██████▍   | 4337/6717 [14:47<08:10,  4.85it/s]

Processing tickers:  65%|██████▍   | 4338/6717 [14:47<08:23,  4.73it/s]

Processing tickers:  65%|██████▍   | 4339/6717 [14:47<08:20,  4.75it/s]

Processing tickers:  65%|██████▍   | 4340/6717 [14:47<08:17,  4.78it/s]

Processing tickers:  65%|██████▍   | 4341/6717 [14:48<08:12,  4.82it/s]

Processing tickers:  65%|██████▍   | 4342/6717 [14:48<08:17,  4.78it/s]

Processing tickers:  65%|██████▍   | 4343/6717 [14:48<08:16,  4.78it/s]

Processing tickers:  65%|██████▍   | 4344/6717 [14:48<08:12,  4.82it/s]

Processing tickers:  65%|██████▍   | 4345/6717 [14:48<08:07,  4.87it/s]

Processing tickers:  65%|██████▍   | 4346/6717 [14:49<08:04,  4.90it/s]

Processing tickers:  65%|██████▍   | 4347/6717 [14:49<08:02,  4.91it/s]

Processing tickers:  65%|██████▍   | 4348/6717 [14:49<07:59,  4.94it/s]

Processing tickers:  65%|██████▍   | 4349/6717 [14:49<07:58,  4.95it/s]

Processing tickers:  65%|██████▍   | 4350/6717 [14:49<07:57,  4.96it/s]

Processing tickers:  65%|██████▍   | 4351/6717 [14:50<08:00,  4.92it/s]

Processing tickers:  65%|██████▍   | 4352/6717 [14:50<08:09,  4.83it/s]

Processing tickers:  65%|██████▍   | 4353/6717 [14:50<08:06,  4.86it/s]

Processing tickers:  65%|██████▍   | 4354/6717 [14:50<08:08,  4.84it/s]

Processing tickers:  65%|██████▍   | 4355/6717 [14:50<08:07,  4.85it/s]

Processing tickers:  65%|██████▍   | 4356/6717 [14:51<08:10,  4.81it/s]

Processing tickers:  65%|██████▍   | 4357/6717 [14:51<08:14,  4.78it/s]

Processing tickers:  65%|██████▍   | 4358/6717 [14:51<08:13,  4.78it/s]

Processing tickers:  65%|██████▍   | 4359/6717 [14:51<08:10,  4.81it/s]

Processing tickers:  65%|██████▍   | 4360/6717 [14:52<08:05,  4.85it/s]

Processing tickers:  65%|██████▍   | 4361/6717 [14:52<08:02,  4.88it/s]

Processing tickers:  65%|██████▍   | 4362/6717 [14:52<07:59,  4.91it/s]

Processing tickers:  65%|██████▍   | 4363/6717 [14:52<08:02,  4.87it/s]

Processing tickers:  65%|██████▍   | 4364/6717 [14:52<08:07,  4.83it/s]

Processing tickers:  65%|██████▍   | 4365/6717 [14:53<08:04,  4.85it/s]

Processing tickers:  65%|██████▍   | 4366/6717 [14:53<08:01,  4.88it/s]

Processing tickers:  65%|██████▌   | 4367/6717 [14:53<07:58,  4.91it/s]

Processing tickers:  65%|██████▌   | 4368/6717 [14:53<07:59,  4.90it/s]

Processing tickers:  65%|██████▌   | 4369/6717 [14:53<07:57,  4.92it/s]

Processing tickers:  65%|██████▌   | 4370/6717 [14:54<07:55,  4.94it/s]

Processing tickers:  65%|██████▌   | 4371/6717 [14:54<07:55,  4.94it/s]

Processing tickers:  65%|██████▌   | 4372/6717 [14:54<07:54,  4.94it/s]

Processing tickers:  65%|██████▌   | 4373/6717 [14:54<07:53,  4.95it/s]

Processing tickers:  65%|██████▌   | 4374/6717 [14:54<07:53,  4.95it/s]

Processing tickers:  65%|██████▌   | 4375/6717 [14:55<08:01,  4.87it/s]

Processing tickers:  65%|██████▌   | 4376/6717 [14:55<07:57,  4.90it/s]

Processing tickers:  65%|██████▌   | 4377/6717 [14:55<08:04,  4.83it/s]

Processing tickers:  65%|██████▌   | 4378/6717 [14:55<08:06,  4.81it/s]

Processing tickers:  65%|██████▌   | 4379/6717 [14:55<08:02,  4.85it/s]

Processing tickers:  65%|██████▌   | 4380/6717 [14:56<07:59,  4.87it/s]

Processing tickers:  65%|██████▌   | 4381/6717 [14:56<07:57,  4.89it/s]

Processing tickers:  65%|██████▌   | 4382/6717 [14:56<07:57,  4.89it/s]

Processing tickers:  65%|██████▌   | 4383/6717 [14:56<07:56,  4.90it/s]

Processing tickers:  65%|██████▌   | 4384/6717 [14:56<07:56,  4.90it/s]

Processing tickers:  65%|██████▌   | 4385/6717 [14:57<07:55,  4.91it/s]

Processing tickers:  65%|██████▌   | 4386/6717 [14:57<07:50,  4.95it/s]

Processing tickers:  65%|██████▌   | 4387/6717 [14:57<07:51,  4.95it/s]

Processing tickers:  65%|██████▌   | 4388/6717 [14:57<08:08,  4.77it/s]

Processing tickers:  65%|██████▌   | 4389/6717 [14:57<08:03,  4.82it/s]

Processing tickers:  65%|██████▌   | 4390/6717 [14:58<07:58,  4.86it/s]

Processing tickers:  65%|██████▌   | 4391/6717 [14:58<07:57,  4.88it/s]

Processing tickers:  65%|██████▌   | 4392/6717 [14:58<08:01,  4.83it/s]

Processing tickers:  65%|██████▌   | 4393/6717 [14:58<07:58,  4.86it/s]

Processing tickers:  65%|██████▌   | 4394/6717 [14:58<07:53,  4.90it/s]

Processing tickers:  65%|██████▌   | 4395/6717 [14:59<07:52,  4.92it/s]

Processing tickers:  65%|██████▌   | 4396/6717 [14:59<07:48,  4.95it/s]

Processing tickers:  65%|██████▌   | 4397/6717 [14:59<07:49,  4.94it/s]

Processing tickers:  65%|██████▌   | 4398/6717 [14:59<07:54,  4.89it/s]

Processing tickers:  65%|██████▌   | 4399/6717 [14:59<07:53,  4.90it/s]

Processing tickers:  66%|██████▌   | 4400/6717 [15:00<07:49,  4.94it/s]

Processing tickers:  66%|██████▌   | 4401/6717 [15:00<07:50,  4.93it/s]

Processing tickers:  66%|██████▌   | 4402/6717 [15:00<07:47,  4.95it/s]

Processing tickers:  66%|██████▌   | 4403/6717 [15:00<07:46,  4.96it/s]

Processing tickers:  66%|██████▌   | 4404/6717 [15:00<07:44,  4.98it/s]

Processing tickers:  66%|██████▌   | 4405/6717 [15:01<07:43,  4.99it/s]

Processing tickers:  66%|██████▌   | 4406/6717 [15:01<07:44,  4.98it/s]

Processing tickers:  66%|██████▌   | 4407/6717 [15:01<07:44,  4.97it/s]

Processing tickers:  66%|██████▌   | 4408/6717 [15:01<07:55,  4.86it/s]

Processing tickers:  66%|██████▌   | 4409/6717 [15:02<07:51,  4.90it/s]

Processing tickers:  66%|██████▌   | 4410/6717 [15:02<08:01,  4.80it/s]

Processing tickers:  66%|██████▌   | 4411/6717 [15:02<07:58,  4.82it/s]

Processing tickers:  66%|██████▌   | 4412/6717 [15:02<07:54,  4.86it/s]

Processing tickers:  66%|██████▌   | 4413/6717 [15:02<07:51,  4.89it/s]

Processing tickers:  66%|██████▌   | 4414/6717 [15:03<07:47,  4.92it/s]

Processing tickers:  66%|██████▌   | 4415/6717 [15:03<07:47,  4.92it/s]

Processing tickers:  66%|██████▌   | 4416/6717 [15:03<07:48,  4.91it/s]

Processing tickers:  66%|██████▌   | 4417/6717 [15:03<07:43,  4.96it/s]

Processing tickers:  66%|██████▌   | 4418/6717 [15:03<07:46,  4.93it/s]

Processing tickers:  66%|██████▌   | 4419/6717 [15:04<07:44,  4.95it/s]

Processing tickers:  66%|██████▌   | 4420/6717 [15:04<07:43,  4.96it/s]

Processing tickers:  66%|██████▌   | 4421/6717 [15:04<07:41,  4.98it/s]

Processing tickers:  66%|██████▌   | 4422/6717 [15:04<07:40,  4.98it/s]

Processing tickers:  66%|██████▌   | 4423/6717 [15:04<07:40,  4.98it/s]

Processing tickers:  66%|██████▌   | 4424/6717 [15:05<07:42,  4.96it/s]

Processing tickers:  66%|██████▌   | 4425/6717 [15:05<07:41,  4.97it/s]

Processing tickers:  66%|██████▌   | 4426/6717 [15:05<07:46,  4.91it/s]

Processing tickers:  66%|██████▌   | 4427/6717 [15:05<07:46,  4.91it/s]

Processing tickers:  66%|██████▌   | 4428/6717 [15:05<07:46,  4.91it/s]

Processing tickers:  66%|██████▌   | 4429/6717 [15:06<07:45,  4.92it/s]

Processing tickers:  66%|██████▌   | 4430/6717 [15:06<07:43,  4.93it/s]

Processing tickers:  66%|██████▌   | 4431/6717 [15:06<07:46,  4.90it/s]

Processing tickers:  66%|██████▌   | 4432/6717 [15:06<07:43,  4.93it/s]

Processing tickers:  66%|██████▌   | 4433/6717 [15:06<07:41,  4.95it/s]

Processing tickers:  66%|██████▌   | 4434/6717 [15:07<07:40,  4.96it/s]

Processing tickers:  66%|██████▌   | 4435/6717 [15:07<07:40,  4.96it/s]

Processing tickers:  66%|██████▌   | 4436/6717 [15:07<07:50,  4.85it/s]

Processing tickers:  66%|██████▌   | 4437/6717 [15:07<07:45,  4.90it/s]

Processing tickers:  66%|██████▌   | 4438/6717 [15:07<07:57,  4.77it/s]

Processing tickers:  66%|██████▌   | 4439/6717 [15:08<07:51,  4.84it/s]

Processing tickers:  66%|██████▌   | 4440/6717 [15:08<07:45,  4.89it/s]

Processing tickers:  66%|██████▌   | 4441/6717 [15:08<07:44,  4.90it/s]

Processing tickers:  66%|██████▌   | 4442/6717 [15:08<07:40,  4.94it/s]

Processing tickers:  66%|██████▌   | 4443/6717 [15:08<07:41,  4.93it/s]

Processing tickers:  66%|██████▌   | 4444/6717 [15:09<07:40,  4.94it/s]

Processing tickers:  66%|██████▌   | 4445/6717 [15:09<07:41,  4.92it/s]

Processing tickers:  66%|██████▌   | 4446/6717 [15:09<07:39,  4.94it/s]

Processing tickers:  66%|██████▌   | 4447/6717 [15:09<07:40,  4.93it/s]

Processing tickers:  66%|██████▌   | 4448/6717 [15:09<07:40,  4.92it/s]

Processing tickers:  66%|██████▌   | 4449/6717 [15:10<07:45,  4.87it/s]

Processing tickers:  66%|██████▌   | 4450/6717 [15:10<07:45,  4.87it/s]

Processing tickers:  66%|██████▋   | 4451/6717 [15:10<07:42,  4.90it/s]

Processing tickers:  66%|██████▋   | 4452/6717 [15:10<07:40,  4.92it/s]

Processing tickers:  66%|██████▋   | 4453/6717 [15:10<07:45,  4.86it/s]

Processing tickers:  66%|██████▋   | 4454/6717 [15:11<07:44,  4.88it/s]

Processing tickers:  66%|██████▋   | 4455/6717 [15:11<07:46,  4.85it/s]

Processing tickers:  66%|██████▋   | 4456/6717 [15:11<07:44,  4.87it/s]

Processing tickers:  66%|██████▋   | 4457/6717 [15:11<07:42,  4.89it/s]

Processing tickers:  66%|██████▋   | 4458/6717 [15:12<07:43,  4.87it/s]

Processing tickers:  66%|██████▋   | 4459/6717 [15:12<07:48,  4.82it/s]

Processing tickers:  66%|██████▋   | 4460/6717 [15:12<07:41,  4.89it/s]

Processing tickers:  66%|██████▋   | 4461/6717 [15:12<07:38,  4.92it/s]

Processing tickers:  66%|██████▋   | 4462/6717 [15:12<07:38,  4.92it/s]

Processing tickers:  66%|██████▋   | 4463/6717 [15:13<07:50,  4.79it/s]

Processing tickers:  66%|██████▋   | 4464/6717 [15:13<07:44,  4.85it/s]

Processing tickers:  66%|██████▋   | 4465/6717 [15:13<07:42,  4.87it/s]

Processing tickers:  66%|██████▋   | 4466/6717 [15:13<07:39,  4.90it/s]

Processing tickers:  67%|██████▋   | 4467/6717 [15:13<07:47,  4.81it/s]

Processing tickers:  67%|██████▋   | 4468/6717 [15:14<07:41,  4.87it/s]

Processing tickers:  67%|██████▋   | 4469/6717 [15:14<07:39,  4.89it/s]

Processing tickers:  67%|██████▋   | 4470/6717 [15:14<07:38,  4.91it/s]

Processing tickers:  67%|██████▋   | 4471/6717 [15:14<07:36,  4.92it/s]

Processing tickers:  67%|██████▋   | 4472/6717 [15:14<07:35,  4.93it/s]

Processing tickers:  67%|██████▋   | 4473/6717 [15:15<07:34,  4.93it/s]

Processing tickers:  67%|██████▋   | 4474/6717 [15:15<07:34,  4.94it/s]

Processing tickers:  67%|██████▋   | 4475/6717 [15:15<07:32,  4.95it/s]

Processing tickers:  67%|██████▋   | 4476/6717 [15:15<07:31,  4.96it/s]

Processing tickers:  67%|██████▋   | 4477/6717 [15:15<07:34,  4.93it/s]

Processing tickers:  67%|██████▋   | 4478/6717 [15:16<07:32,  4.95it/s]

Processing tickers:  67%|██████▋   | 4479/6717 [15:16<07:37,  4.89it/s]

Processing tickers:  67%|██████▋   | 4480/6717 [15:16<07:39,  4.87it/s]

Processing tickers:  67%|██████▋   | 4481/6717 [15:16<07:37,  4.89it/s]

Processing tickers:  67%|██████▋   | 4482/6717 [15:16<07:46,  4.80it/s]

Processing tickers:  67%|██████▋   | 4483/6717 [15:17<07:46,  4.79it/s]

Processing tickers:  67%|██████▋   | 4484/6717 [15:17<07:40,  4.85it/s]

Processing tickers:  67%|██████▋   | 4485/6717 [15:17<07:42,  4.83it/s]

Processing tickers:  67%|██████▋   | 4486/6717 [15:17<07:35,  4.89it/s]

Processing tickers:  67%|██████▋   | 4487/6717 [15:17<07:34,  4.90it/s]

Processing tickers:  67%|██████▋   | 4488/6717 [15:18<07:34,  4.90it/s]

Processing tickers:  67%|██████▋   | 4489/6717 [15:18<07:33,  4.91it/s]

Processing tickers:  67%|██████▋   | 4490/6717 [15:18<07:30,  4.95it/s]

Processing tickers:  67%|██████▋   | 4491/6717 [15:18<07:27,  4.97it/s]

Processing tickers:  67%|██████▋   | 4492/6717 [15:18<07:34,  4.89it/s]

Processing tickers:  67%|██████▋   | 4493/6717 [15:19<07:35,  4.88it/s]

Processing tickers:  67%|██████▋   | 4494/6717 [15:19<07:33,  4.90it/s]

Processing tickers:  67%|██████▋   | 4495/6717 [15:19<07:30,  4.93it/s]

Processing tickers:  67%|██████▋   | 4496/6717 [15:19<07:28,  4.95it/s]

Processing tickers:  67%|██████▋   | 4497/6717 [15:19<07:30,  4.93it/s]

Processing tickers:  67%|██████▋   | 4498/6717 [15:20<07:28,  4.95it/s]

Processing tickers:  67%|██████▋   | 4499/6717 [15:20<07:25,  4.98it/s]

Processing tickers:  67%|██████▋   | 4500/6717 [15:20<07:24,  4.99it/s]

Processing tickers:  67%|██████▋   | 4501/6717 [15:20<07:24,  4.99it/s]

Processing tickers:  67%|██████▋   | 4502/6717 [15:20<07:25,  4.97it/s]

Processing tickers:  67%|██████▋   | 4503/6717 [15:21<07:25,  4.97it/s]

Processing tickers:  67%|██████▋   | 4504/6717 [15:21<07:30,  4.91it/s]

Processing tickers:  67%|██████▋   | 4505/6717 [15:21<07:26,  4.96it/s]

Processing tickers:  67%|██████▋   | 4506/6717 [15:21<07:26,  4.95it/s]

Processing tickers:  67%|██████▋   | 4507/6717 [15:21<07:29,  4.92it/s]

Processing tickers:  67%|██████▋   | 4508/6717 [15:22<07:30,  4.90it/s]

Processing tickers:  67%|██████▋   | 4509/6717 [15:22<07:27,  4.94it/s]

Processing tickers:  67%|██████▋   | 4510/6717 [15:22<07:28,  4.92it/s]

Processing tickers:  67%|██████▋   | 4511/6717 [15:22<07:27,  4.93it/s]

Processing tickers:  67%|██████▋   | 4512/6717 [15:23<07:27,  4.93it/s]

Processing tickers:  67%|██████▋   | 4513/6717 [15:23<07:25,  4.95it/s]

Processing tickers:  67%|██████▋   | 4514/6717 [15:23<07:23,  4.97it/s]

Processing tickers:  67%|██████▋   | 4515/6717 [15:23<07:35,  4.83it/s]

Processing tickers:  67%|██████▋   | 4516/6717 [15:23<07:29,  4.90it/s]

Processing tickers:  67%|██████▋   | 4517/6717 [15:24<07:28,  4.90it/s]

Processing tickers:  67%|██████▋   | 4518/6717 [15:24<07:40,  4.77it/s]

Processing tickers:  67%|██████▋   | 4519/6717 [15:24<07:37,  4.81it/s]

Processing tickers:  67%|██████▋   | 4520/6717 [15:24<07:38,  4.79it/s]

Processing tickers:  67%|██████▋   | 4521/6717 [15:24<07:32,  4.86it/s]

Processing tickers:  67%|██████▋   | 4522/6717 [15:25<07:29,  4.88it/s]

Processing tickers:  67%|██████▋   | 4523/6717 [15:25<07:28,  4.89it/s]

Processing tickers:  67%|██████▋   | 4524/6717 [15:25<07:32,  4.85it/s]

Processing tickers:  67%|██████▋   | 4525/6717 [15:25<07:30,  4.86it/s]

Processing tickers:  67%|██████▋   | 4526/6717 [15:25<07:27,  4.90it/s]

Processing tickers:  67%|██████▋   | 4527/6717 [15:26<07:25,  4.91it/s]

Processing tickers:  67%|██████▋   | 4528/6717 [15:26<07:22,  4.95it/s]

Processing tickers:  67%|██████▋   | 4529/6717 [15:26<07:24,  4.92it/s]

Processing tickers:  67%|██████▋   | 4530/6717 [15:26<07:23,  4.93it/s]

Processing tickers:  67%|██████▋   | 4531/6717 [15:26<07:22,  4.94it/s]

Processing tickers:  67%|██████▋   | 4532/6717 [15:27<07:21,  4.95it/s]

Processing tickers:  67%|██████▋   | 4533/6717 [15:27<07:22,  4.94it/s]

Processing tickers:  68%|██████▊   | 4534/6717 [15:27<07:25,  4.90it/s]

Processing tickers:  68%|██████▊   | 4535/6717 [15:27<07:24,  4.91it/s]

Processing tickers:  68%|██████▊   | 4536/6717 [15:27<07:22,  4.92it/s]

Processing tickers:  68%|██████▊   | 4537/6717 [15:28<07:20,  4.94it/s]

Processing tickers:  68%|██████▊   | 4538/6717 [15:28<07:24,  4.90it/s]

Processing tickers:  68%|██████▊   | 4539/6717 [15:28<07:25,  4.89it/s]

Processing tickers:  68%|██████▊   | 4540/6717 [15:28<07:23,  4.91it/s]

Processing tickers:  68%|██████▊   | 4541/6717 [15:28<07:23,  4.91it/s]

Processing tickers:  68%|██████▊   | 4542/6717 [15:29<07:20,  4.93it/s]

Processing tickers:  68%|██████▊   | 4543/6717 [15:29<07:19,  4.95it/s]

Processing tickers:  68%|██████▊   | 4544/6717 [15:29<07:18,  4.95it/s]

Processing tickers:  68%|██████▊   | 4545/6717 [15:29<07:23,  4.90it/s]

Processing tickers:  68%|██████▊   | 4546/6717 [15:30<08:10,  4.43it/s]

Processing tickers:  68%|██████▊   | 4547/6717 [15:30<07:52,  4.60it/s]

Processing tickers:  68%|██████▊   | 4548/6717 [15:30<07:39,  4.72it/s]

Processing tickers:  68%|██████▊   | 4549/6717 [15:30<07:31,  4.80it/s]

Processing tickers:  68%|██████▊   | 4550/6717 [15:30<07:27,  4.85it/s]

Processing tickers:  68%|██████▊   | 4551/6717 [15:31<07:22,  4.89it/s]

Processing tickers:  68%|██████▊   | 4552/6717 [15:31<07:21,  4.91it/s]

Processing tickers:  68%|██████▊   | 4553/6717 [15:31<07:19,  4.92it/s]

Processing tickers:  68%|██████▊   | 4554/6717 [15:31<07:22,  4.89it/s]

Processing tickers:  68%|██████▊   | 4555/6717 [15:31<07:19,  4.92it/s]

Processing tickers:  68%|██████▊   | 4556/6717 [15:32<07:18,  4.92it/s]

Processing tickers:  68%|██████▊   | 4557/6717 [15:32<07:22,  4.88it/s]

Processing tickers:  68%|██████▊   | 4558/6717 [15:32<07:27,  4.83it/s]

Processing tickers:  68%|██████▊   | 4559/6717 [15:32<07:23,  4.87it/s]

Processing tickers:  68%|██████▊   | 4560/6717 [15:32<07:21,  4.88it/s]

Processing tickers:  68%|██████▊   | 4561/6717 [15:33<07:20,  4.89it/s]

Processing tickers:  68%|██████▊   | 4562/6717 [15:33<07:17,  4.92it/s]

Processing tickers:  68%|██████▊   | 4563/6717 [15:33<07:15,  4.95it/s]

Processing tickers:  68%|██████▊   | 4564/6717 [15:33<07:28,  4.81it/s]

Processing tickers:  68%|██████▊   | 4565/6717 [15:33<07:27,  4.80it/s]

Processing tickers:  68%|██████▊   | 4566/6717 [15:34<07:23,  4.85it/s]

Processing tickers:  68%|██████▊   | 4567/6717 [15:34<07:21,  4.87it/s]

Processing tickers:  68%|██████▊   | 4568/6717 [15:34<07:23,  4.84it/s]

Processing tickers:  68%|██████▊   | 4569/6717 [15:34<07:19,  4.88it/s]

Processing tickers:  68%|██████▊   | 4570/6717 [15:34<07:21,  4.87it/s]

Processing tickers:  68%|██████▊   | 4571/6717 [15:35<07:17,  4.90it/s]

Processing tickers:  68%|██████▊   | 4572/6717 [15:35<07:16,  4.92it/s]

Processing tickers:  68%|██████▊   | 4573/6717 [15:35<07:22,  4.85it/s]

Processing tickers:  68%|██████▊   | 4574/6717 [15:35<07:21,  4.86it/s]

Processing tickers:  68%|██████▊   | 4575/6717 [15:35<07:16,  4.90it/s]

Processing tickers:  68%|██████▊   | 4576/6717 [15:36<07:13,  4.94it/s]

Processing tickers:  68%|██████▊   | 4577/6717 [15:36<07:12,  4.94it/s]

Processing tickers:  68%|██████▊   | 4578/6717 [15:36<07:12,  4.95it/s]

Processing tickers:  68%|██████▊   | 4579/6717 [15:36<07:14,  4.92it/s]

Processing tickers:  68%|██████▊   | 4580/6717 [15:36<07:11,  4.95it/s]

Processing tickers:  68%|██████▊   | 4581/6717 [15:37<07:09,  4.97it/s]

Processing tickers:  68%|██████▊   | 4582/6717 [15:37<07:10,  4.95it/s]

Processing tickers:  68%|██████▊   | 4583/6717 [15:37<07:14,  4.92it/s]

Processing tickers:  68%|██████▊   | 4584/6717 [15:37<07:26,  4.78it/s]

Processing tickers:  68%|██████▊   | 4585/6717 [15:37<07:21,  4.83it/s]

Processing tickers:  68%|██████▊   | 4586/6717 [15:38<07:15,  4.89it/s]

Processing tickers:  68%|██████▊   | 4587/6717 [15:38<07:11,  4.93it/s]

Processing tickers:  68%|██████▊   | 4588/6717 [15:38<07:08,  4.97it/s]

Processing tickers:  68%|██████▊   | 4589/6717 [15:38<07:06,  4.98it/s]

Processing tickers:  68%|██████▊   | 4590/6717 [15:38<07:08,  4.96it/s]

Processing tickers:  68%|██████▊   | 4591/6717 [15:39<07:07,  4.97it/s]

Processing tickers:  68%|██████▊   | 4592/6717 [15:39<07:06,  4.99it/s]

Processing tickers:  68%|██████▊   | 4593/6717 [15:39<07:08,  4.95it/s]

Processing tickers:  68%|██████▊   | 4594/6717 [15:39<07:08,  4.96it/s]

Processing tickers:  68%|██████▊   | 4595/6717 [15:39<07:17,  4.85it/s]

Processing tickers:  68%|██████▊   | 4596/6717 [15:40<07:13,  4.89it/s]

Processing tickers:  68%|██████▊   | 4597/6717 [15:40<07:14,  4.88it/s]

Processing tickers:  68%|██████▊   | 4598/6717 [15:40<07:12,  4.90it/s]

Processing tickers:  68%|██████▊   | 4599/6717 [15:40<07:10,  4.92it/s]

Processing tickers:  68%|██████▊   | 4600/6717 [15:41<07:12,  4.89it/s]

Processing tickers:  68%|██████▊   | 4601/6717 [15:41<07:10,  4.92it/s]

Processing tickers:  69%|██████▊   | 4602/6717 [15:41<07:06,  4.96it/s]

Processing tickers:  69%|██████▊   | 4603/6717 [15:41<07:08,  4.93it/s]

Processing tickers:  69%|██████▊   | 4604/6717 [15:41<07:07,  4.94it/s]

Processing tickers:  69%|██████▊   | 4605/6717 [15:42<07:08,  4.92it/s]

Processing tickers:  69%|██████▊   | 4606/6717 [15:42<07:07,  4.94it/s]

Processing tickers:  69%|██████▊   | 4607/6717 [15:42<07:07,  4.93it/s]

Processing tickers:  69%|██████▊   | 4608/6717 [15:42<07:06,  4.94it/s]

Processing tickers:  69%|██████▊   | 4609/6717 [15:42<07:10,  4.90it/s]

Processing tickers:  69%|██████▊   | 4610/6717 [15:43<07:09,  4.91it/s]

Processing tickers:  69%|██████▊   | 4611/6717 [15:43<07:09,  4.91it/s]

Processing tickers:  69%|██████▊   | 4612/6717 [15:43<07:09,  4.90it/s]

Processing tickers:  69%|██████▊   | 4613/6717 [15:43<07:07,  4.92it/s]

Processing tickers:  69%|██████▊   | 4614/6717 [15:43<07:08,  4.91it/s]

Processing tickers:  69%|██████▊   | 4615/6717 [15:44<07:10,  4.88it/s]

Processing tickers:  69%|██████▊   | 4616/6717 [15:44<07:09,  4.89it/s]

Processing tickers:  69%|██████▊   | 4617/6717 [15:44<07:13,  4.85it/s]

Processing tickers:  69%|██████▉   | 4618/6717 [15:44<07:09,  4.88it/s]

Processing tickers:  69%|██████▉   | 4619/6717 [15:44<07:10,  4.87it/s]

Processing tickers:  69%|██████▉   | 4620/6717 [15:45<07:06,  4.91it/s]

Processing tickers:  69%|██████▉   | 4621/6717 [15:45<07:02,  4.96it/s]

Processing tickers:  69%|██████▉   | 4622/6717 [15:45<07:01,  4.97it/s]

Processing tickers:  69%|██████▉   | 4623/6717 [15:45<07:03,  4.94it/s]

Processing tickers:  69%|██████▉   | 4624/6717 [15:45<07:03,  4.95it/s]

Processing tickers:  69%|██████▉   | 4625/6717 [15:46<07:08,  4.88it/s]

Processing tickers:  69%|██████▉   | 4626/6717 [15:46<07:09,  4.87it/s]

Processing tickers:  69%|██████▉   | 4627/6717 [15:46<07:19,  4.76it/s]

Processing tickers:  69%|██████▉   | 4628/6717 [15:46<07:19,  4.76it/s]

Processing tickers:  69%|██████▉   | 4629/6717 [15:46<07:14,  4.81it/s]

Processing tickers:  69%|██████▉   | 4630/6717 [15:47<07:07,  4.88it/s]

Processing tickers:  69%|██████▉   | 4631/6717 [15:47<07:08,  4.87it/s]

Processing tickers:  69%|██████▉   | 4632/6717 [15:47<07:07,  4.88it/s]

Processing tickers:  69%|██████▉   | 4633/6717 [15:47<07:02,  4.93it/s]

Processing tickers:  69%|██████▉   | 4634/6717 [15:47<07:04,  4.91it/s]

Processing tickers:  69%|██████▉   | 4635/6717 [15:48<07:03,  4.92it/s]

Processing tickers:  69%|██████▉   | 4636/6717 [15:48<07:09,  4.84it/s]

Processing tickers:  69%|██████▉   | 4637/6717 [15:48<07:20,  4.72it/s]

Processing tickers:  69%|██████▉   | 4638/6717 [15:48<07:15,  4.78it/s]

Processing tickers:  69%|██████▉   | 4639/6717 [15:49<07:19,  4.73it/s]

Processing tickers:  69%|██████▉   | 4640/6717 [15:49<07:12,  4.80it/s]

Processing tickers:  69%|██████▉   | 4641/6717 [15:49<07:06,  4.86it/s]

Processing tickers:  69%|██████▉   | 4642/6717 [15:49<07:03,  4.90it/s]

Processing tickers:  69%|██████▉   | 4643/6717 [15:49<07:04,  4.88it/s]

Processing tickers:  69%|██████▉   | 4644/6717 [15:50<07:02,  4.91it/s]

Processing tickers:  69%|██████▉   | 4645/6717 [15:50<07:00,  4.93it/s]

Processing tickers:  69%|██████▉   | 4646/6717 [15:50<06:59,  4.93it/s]

Processing tickers:  69%|██████▉   | 4647/6717 [15:50<07:00,  4.93it/s]

Processing tickers:  69%|██████▉   | 4648/6717 [15:50<06:59,  4.94it/s]

Processing tickers:  69%|██████▉   | 4649/6717 [15:51<06:59,  4.93it/s]

Processing tickers:  69%|██████▉   | 4650/6717 [15:51<06:58,  4.94it/s]

Processing tickers:  69%|██████▉   | 4651/6717 [15:51<06:56,  4.97it/s]

Processing tickers:  69%|██████▉   | 4652/6717 [15:51<07:01,  4.90it/s]

Processing tickers:  69%|██████▉   | 4653/6717 [15:51<07:01,  4.89it/s]

Processing tickers:  69%|██████▉   | 4654/6717 [15:52<07:04,  4.86it/s]

Processing tickers:  69%|██████▉   | 4655/6717 [15:52<06:59,  4.91it/s]

Processing tickers:  69%|██████▉   | 4656/6717 [15:52<07:00,  4.91it/s]

Processing tickers:  69%|██████▉   | 4657/6717 [15:52<07:00,  4.90it/s]

Processing tickers:  69%|██████▉   | 4658/6717 [15:52<07:00,  4.90it/s]

Processing tickers:  69%|██████▉   | 4659/6717 [15:53<06:59,  4.91it/s]

Processing tickers:  69%|██████▉   | 4660/6717 [15:53<06:56,  4.93it/s]

Processing tickers:  69%|██████▉   | 4661/6717 [15:53<06:54,  4.96it/s]

Processing tickers:  69%|██████▉   | 4662/6717 [15:53<06:55,  4.94it/s]

Processing tickers:  69%|██████▉   | 4663/6717 [15:53<07:01,  4.87it/s]

Processing tickers:  69%|██████▉   | 4664/6717 [15:54<07:00,  4.88it/s]

Processing tickers:  69%|██████▉   | 4665/6717 [15:54<06:58,  4.91it/s]

Processing tickers:  69%|██████▉   | 4666/6717 [15:54<07:00,  4.88it/s]

Processing tickers:  69%|██████▉   | 4667/6717 [15:54<06:59,  4.89it/s]

Processing tickers:  69%|██████▉   | 4668/6717 [15:54<06:58,  4.90it/s]

Processing tickers:  70%|██████▉   | 4669/6717 [15:55<07:01,  4.86it/s]

Processing tickers:  70%|██████▉   | 4670/6717 [15:55<06:58,  4.90it/s]

Processing tickers:  70%|██████▉   | 4671/6717 [15:55<07:03,  4.84it/s]

Processing tickers:  70%|██████▉   | 4672/6717 [15:55<07:02,  4.84it/s]

Processing tickers:  70%|██████▉   | 4673/6717 [15:55<06:58,  4.89it/s]

Processing tickers:  70%|██████▉   | 4674/6717 [15:56<06:55,  4.92it/s]

Processing tickers:  70%|██████▉   | 4675/6717 [15:56<06:52,  4.95it/s]

Processing tickers:  70%|██████▉   | 4676/6717 [15:56<06:51,  4.96it/s]

Processing tickers:  70%|██████▉   | 4677/6717 [15:56<06:48,  4.99it/s]

Processing tickers:  70%|██████▉   | 4678/6717 [15:56<06:49,  4.98it/s]

Processing tickers:  70%|██████▉   | 4679/6717 [15:57<06:49,  4.98it/s]

Processing tickers:  70%|██████▉   | 4680/6717 [15:57<06:49,  4.97it/s]

Processing tickers:  70%|██████▉   | 4681/6717 [15:57<06:48,  4.98it/s]

Processing tickers:  70%|██████▉   | 4682/6717 [15:57<06:48,  4.98it/s]

Processing tickers:  70%|██████▉   | 4683/6717 [15:57<06:59,  4.85it/s]

Processing tickers:  70%|██████▉   | 4684/6717 [15:58<07:07,  4.76it/s]

Processing tickers:  70%|██████▉   | 4685/6717 [15:58<07:05,  4.78it/s]

Processing tickers:  70%|██████▉   | 4686/6717 [15:58<07:02,  4.81it/s]

Processing tickers:  70%|██████▉   | 4687/6717 [15:58<06:58,  4.85it/s]

Processing tickers:  70%|██████▉   | 4688/6717 [15:58<06:58,  4.84it/s]

Processing tickers:  70%|██████▉   | 4689/6717 [15:59<07:00,  4.82it/s]

Processing tickers:  70%|██████▉   | 4690/6717 [15:59<06:55,  4.87it/s]

Processing tickers:  70%|██████▉   | 4691/6717 [15:59<06:54,  4.89it/s]

Processing tickers:  70%|██████▉   | 4692/6717 [15:59<06:52,  4.90it/s]

Processing tickers:  70%|██████▉   | 4693/6717 [16:00<06:53,  4.89it/s]

Processing tickers:  70%|██████▉   | 4694/6717 [16:00<06:51,  4.92it/s]

Processing tickers:  70%|██████▉   | 4695/6717 [16:00<06:49,  4.94it/s]

Processing tickers:  70%|██████▉   | 4696/6717 [16:00<06:48,  4.95it/s]

Processing tickers:  70%|██████▉   | 4697/6717 [16:00<06:48,  4.95it/s]

Processing tickers:  70%|██████▉   | 4698/6717 [16:01<06:49,  4.94it/s]

Processing tickers:  70%|██████▉   | 4699/6717 [16:01<06:50,  4.91it/s]

Processing tickers:  70%|██████▉   | 4700/6717 [16:01<06:50,  4.92it/s]

Processing tickers:  70%|██████▉   | 4701/6717 [16:01<06:48,  4.94it/s]

Processing tickers:  70%|███████   | 4702/6717 [16:01<06:49,  4.92it/s]

Processing tickers:  70%|███████   | 4703/6717 [16:02<06:49,  4.92it/s]

Processing tickers:  70%|███████   | 4704/6717 [16:02<06:58,  4.81it/s]

Processing tickers:  70%|███████   | 4705/6717 [16:02<06:55,  4.85it/s]

Processing tickers:  70%|███████   | 4706/6717 [16:02<06:52,  4.87it/s]

Processing tickers:  70%|███████   | 4707/6717 [16:02<06:50,  4.90it/s]

Processing tickers:  70%|███████   | 4708/6717 [16:03<06:47,  4.93it/s]

Processing tickers:  70%|███████   | 4709/6717 [16:03<06:44,  4.96it/s]

Processing tickers:  70%|███████   | 4710/6717 [16:03<06:43,  4.97it/s]

Processing tickers:  70%|███████   | 4711/6717 [16:03<06:44,  4.96it/s]

Processing tickers:  70%|███████   | 4712/6717 [16:03<06:42,  4.98it/s]

Processing tickers:  70%|███████   | 4713/6717 [16:04<06:44,  4.96it/s]

Processing tickers:  70%|███████   | 4714/6717 [16:04<06:43,  4.96it/s]

Processing tickers:  70%|███████   | 4715/6717 [16:04<06:42,  4.97it/s]

Processing tickers:  70%|███████   | 4716/6717 [16:04<06:43,  4.97it/s]

Processing tickers:  70%|███████   | 4717/6717 [16:04<06:44,  4.94it/s]

Processing tickers:  70%|███████   | 4718/6717 [16:05<06:47,  4.91it/s]

Processing tickers:  70%|███████   | 4719/6717 [16:05<06:53,  4.83it/s]

Processing tickers:  70%|███████   | 4720/6717 [16:05<06:58,  4.77it/s]

Processing tickers:  70%|███████   | 4721/6717 [16:05<06:54,  4.81it/s]

Processing tickers:  70%|███████   | 4722/6717 [16:05<06:48,  4.88it/s]

Processing tickers:  70%|███████   | 4723/6717 [16:06<06:46,  4.90it/s]

Processing tickers:  70%|███████   | 4724/6717 [16:06<06:45,  4.92it/s]

Processing tickers:  70%|███████   | 4725/6717 [16:06<06:42,  4.95it/s]

Processing tickers:  70%|███████   | 4726/6717 [16:06<06:42,  4.95it/s]

Processing tickers:  70%|███████   | 4727/6717 [16:06<06:41,  4.96it/s]

Processing tickers:  70%|███████   | 4728/6717 [16:07<06:44,  4.91it/s]

Processing tickers:  70%|███████   | 4729/6717 [16:07<06:42,  4.94it/s]

Processing tickers:  70%|███████   | 4730/6717 [16:07<06:39,  4.97it/s]

Processing tickers:  70%|███████   | 4731/6717 [16:07<06:40,  4.96it/s]

Processing tickers:  70%|███████   | 4732/6717 [16:07<06:39,  4.97it/s]

Processing tickers:  70%|███████   | 4733/6717 [16:08<06:40,  4.95it/s]

Processing tickers:  70%|███████   | 4734/6717 [16:08<06:45,  4.89it/s]

Processing tickers:  70%|███████   | 4735/6717 [16:08<06:43,  4.91it/s]

Processing tickers:  71%|███████   | 4736/6717 [16:08<06:41,  4.93it/s]

Processing tickers:  71%|███████   | 4737/6717 [16:08<06:39,  4.96it/s]

Processing tickers:  71%|███████   | 4738/6717 [16:09<06:38,  4.96it/s]

Processing tickers:  71%|███████   | 4739/6717 [16:09<06:40,  4.93it/s]

Processing tickers:  71%|███████   | 4740/6717 [16:09<06:38,  4.95it/s]

Processing tickers:  71%|███████   | 4741/6717 [16:09<06:37,  4.97it/s]

Processing tickers:  71%|███████   | 4742/6717 [16:09<06:37,  4.97it/s]

Processing tickers:  71%|███████   | 4743/6717 [16:10<06:36,  4.97it/s]

Processing tickers:  71%|███████   | 4744/6717 [16:10<06:37,  4.97it/s]

Processing tickers:  71%|███████   | 4745/6717 [16:10<06:37,  4.96it/s]

Processing tickers:  71%|███████   | 4746/6717 [16:10<06:41,  4.91it/s]

Processing tickers:  71%|███████   | 4747/6717 [16:10<06:42,  4.89it/s]

Processing tickers:  71%|███████   | 4748/6717 [16:11<06:40,  4.91it/s]

Processing tickers:  71%|███████   | 4749/6717 [16:11<06:36,  4.97it/s]

Processing tickers:  71%|███████   | 4750/6717 [16:11<06:34,  4.98it/s]

Processing tickers:  71%|███████   | 4751/6717 [16:11<06:35,  4.97it/s]

Processing tickers:  71%|███████   | 4752/6717 [16:11<06:35,  4.97it/s]

Processing tickers:  71%|███████   | 4753/6717 [16:12<06:35,  4.97it/s]

Processing tickers:  71%|███████   | 4754/6717 [16:12<06:36,  4.95it/s]

Processing tickers:  71%|███████   | 4755/6717 [16:12<06:33,  4.99it/s]

Processing tickers:  71%|███████   | 4756/6717 [16:12<06:38,  4.92it/s]

Processing tickers:  71%|███████   | 4757/6717 [16:13<06:46,  4.82it/s]

Processing tickers:  71%|███████   | 4758/6717 [16:13<06:46,  4.82it/s]

Processing tickers:  71%|███████   | 4759/6717 [16:13<06:44,  4.84it/s]

Processing tickers:  71%|███████   | 4760/6717 [16:13<06:41,  4.87it/s]

Processing tickers:  71%|███████   | 4761/6717 [16:13<06:42,  4.86it/s]

Processing tickers:  71%|███████   | 4762/6717 [16:14<06:44,  4.83it/s]

Processing tickers:  71%|███████   | 4763/6717 [16:14<06:40,  4.87it/s]

Processing tickers:  71%|███████   | 4764/6717 [16:14<06:38,  4.91it/s]

Processing tickers:  71%|███████   | 4765/6717 [16:14<06:35,  4.93it/s]

Processing tickers:  71%|███████   | 4766/6717 [16:14<06:36,  4.93it/s]

Processing tickers:  71%|███████   | 4767/6717 [16:15<06:33,  4.95it/s]

Processing tickers:  71%|███████   | 4768/6717 [16:15<06:40,  4.87it/s]

Processing tickers:  71%|███████   | 4769/6717 [16:15<06:38,  4.89it/s]

Processing tickers:  71%|███████   | 4770/6717 [16:15<06:38,  4.89it/s]

Processing tickers:  71%|███████   | 4771/6717 [16:15<06:38,  4.88it/s]

Processing tickers:  71%|███████   | 4772/6717 [16:16<06:37,  4.89it/s]

Processing tickers:  71%|███████   | 4773/6717 [16:16<06:35,  4.92it/s]

Processing tickers:  71%|███████   | 4774/6717 [16:16<06:39,  4.86it/s]

Processing tickers:  71%|███████   | 4775/6717 [16:16<06:48,  4.75it/s]

Processing tickers:  71%|███████   | 4776/6717 [16:16<06:50,  4.73it/s]

Processing tickers:  71%|███████   | 4777/6717 [16:17<06:44,  4.80it/s]

Processing tickers:  71%|███████   | 4778/6717 [16:17<06:42,  4.82it/s]

Processing tickers:  71%|███████   | 4779/6717 [16:17<06:42,  4.81it/s]

Processing tickers:  71%|███████   | 4780/6717 [16:17<06:38,  4.86it/s]

Processing tickers:  71%|███████   | 4781/6717 [16:17<06:37,  4.87it/s]

Processing tickers:  71%|███████   | 4782/6717 [16:18<06:33,  4.92it/s]

Processing tickers:  71%|███████   | 4783/6717 [16:18<06:30,  4.96it/s]

Processing tickers:  71%|███████   | 4784/6717 [16:18<06:34,  4.90it/s]

Processing tickers:  71%|███████   | 4785/6717 [16:18<06:33,  4.91it/s]

Processing tickers:  71%|███████▏  | 4786/6717 [16:18<06:32,  4.91it/s]

Processing tickers:  71%|███████▏  | 4787/6717 [16:19<06:35,  4.88it/s]

Processing tickers:  71%|███████▏  | 4788/6717 [16:19<06:32,  4.92it/s]

Processing tickers:  71%|███████▏  | 4789/6717 [16:19<06:30,  4.93it/s]

Processing tickers:  71%|███████▏  | 4790/6717 [16:19<06:29,  4.95it/s]

Processing tickers:  71%|███████▏  | 4791/6717 [16:19<06:27,  4.97it/s]

Processing tickers:  71%|███████▏  | 4792/6717 [16:20<06:26,  4.98it/s]

Processing tickers:  71%|███████▏  | 4793/6717 [16:20<06:24,  5.00it/s]

Processing tickers:  71%|███████▏  | 4794/6717 [16:20<06:25,  4.99it/s]

Processing tickers:  71%|███████▏  | 4795/6717 [16:20<06:26,  4.97it/s]

Processing tickers:  71%|███████▏  | 4796/6717 [16:20<06:27,  4.95it/s]

Processing tickers:  71%|███████▏  | 4797/6717 [16:21<06:26,  4.96it/s]

Processing tickers:  71%|███████▏  | 4798/6717 [16:21<06:32,  4.89it/s]

Processing tickers:  71%|███████▏  | 4799/6717 [16:21<06:30,  4.91it/s]

Processing tickers:  71%|███████▏  | 4800/6717 [16:21<06:30,  4.91it/s]

Processing tickers:  71%|███████▏  | 4801/6717 [16:21<06:33,  4.86it/s]

Processing tickers:  71%|███████▏  | 4802/6717 [16:22<06:34,  4.86it/s]

Processing tickers:  72%|███████▏  | 4803/6717 [16:22<06:30,  4.90it/s]

Processing tickers:  72%|███████▏  | 4804/6717 [16:22<06:27,  4.94it/s]

Processing tickers:  72%|███████▏  | 4805/6717 [16:22<06:26,  4.95it/s]

Processing tickers:  72%|███████▏  | 4806/6717 [16:23<06:31,  4.88it/s]

Processing tickers:  72%|███████▏  | 4807/6717 [16:23<06:27,  4.93it/s]

Processing tickers:  72%|███████▏  | 4808/6717 [16:23<06:25,  4.95it/s]

Processing tickers:  72%|███████▏  | 4809/6717 [16:23<06:23,  4.97it/s]

Processing tickers:  72%|███████▏  | 4810/6717 [16:23<06:24,  4.96it/s]

Processing tickers:  72%|███████▏  | 4811/6717 [16:24<06:30,  4.88it/s]

Processing tickers:  72%|███████▏  | 4812/6717 [16:24<06:28,  4.91it/s]

Processing tickers:  72%|███████▏  | 4813/6717 [16:24<06:27,  4.91it/s]

Processing tickers:  72%|███████▏  | 4814/6717 [16:24<06:43,  4.71it/s]

Processing tickers:  72%|███████▏  | 4815/6717 [16:24<06:40,  4.74it/s]

Processing tickers:  72%|███████▏  | 4816/6717 [16:25<06:36,  4.79it/s]

Processing tickers:  72%|███████▏  | 4817/6717 [16:25<06:32,  4.84it/s]

Processing tickers:  72%|███████▏  | 4818/6717 [16:25<06:33,  4.83it/s]

Processing tickers:  72%|███████▏  | 4819/6717 [16:25<06:30,  4.86it/s]

Processing tickers:  72%|███████▏  | 4820/6717 [16:25<06:27,  4.90it/s]

Processing tickers:  72%|███████▏  | 4821/6717 [16:26<06:26,  4.91it/s]

Processing tickers:  72%|███████▏  | 4822/6717 [16:26<06:24,  4.93it/s]

Processing tickers:  72%|███████▏  | 4823/6717 [16:26<06:33,  4.82it/s]

Processing tickers:  72%|███████▏  | 4824/6717 [16:26<06:29,  4.87it/s]

Processing tickers:  72%|███████▏  | 4825/6717 [16:26<06:25,  4.91it/s]

Processing tickers:  72%|███████▏  | 4826/6717 [16:27<06:25,  4.91it/s]

Processing tickers:  72%|███████▏  | 4827/6717 [16:27<06:21,  4.95it/s]

Processing tickers:  72%|███████▏  | 4828/6717 [16:27<06:25,  4.90it/s]

Processing tickers:  72%|███████▏  | 4829/6717 [16:27<06:25,  4.89it/s]

Processing tickers:  72%|███████▏  | 4830/6717 [16:27<06:31,  4.81it/s]

Processing tickers:  72%|███████▏  | 4831/6717 [16:28<06:34,  4.78it/s]

Processing tickers:  72%|███████▏  | 4832/6717 [16:28<06:38,  4.73it/s]

Processing tickers:  72%|███████▏  | 4833/6717 [16:28<06:32,  4.79it/s]

Processing tickers:  72%|███████▏  | 4834/6717 [16:28<06:35,  4.77it/s]

Processing tickers:  72%|███████▏  | 4835/6717 [16:28<06:29,  4.83it/s]

Processing tickers:  72%|███████▏  | 4836/6717 [16:29<06:25,  4.89it/s]

Processing tickers:  72%|███████▏  | 4837/6717 [16:29<06:21,  4.92it/s]

Processing tickers:  72%|███████▏  | 4838/6717 [16:29<06:21,  4.92it/s]

Processing tickers:  72%|███████▏  | 4839/6717 [16:29<06:19,  4.94it/s]

Processing tickers:  72%|███████▏  | 4840/6717 [16:29<06:20,  4.93it/s]

Processing tickers:  72%|███████▏  | 4841/6717 [16:30<06:18,  4.96it/s]

Processing tickers:  72%|███████▏  | 4842/6717 [16:30<06:20,  4.93it/s]

Processing tickers:  72%|███████▏  | 4843/6717 [16:30<06:18,  4.95it/s]

Processing tickers:  72%|███████▏  | 4844/6717 [16:30<06:18,  4.94it/s]

Processing tickers:  72%|███████▏  | 4845/6717 [16:31<06:22,  4.89it/s]

Processing tickers:  72%|███████▏  | 4846/6717 [16:31<06:22,  4.89it/s]

Processing tickers:  72%|███████▏  | 4847/6717 [16:31<06:19,  4.92it/s]

Processing tickers:  72%|███████▏  | 4848/6717 [16:31<06:18,  4.94it/s]

Processing tickers:  72%|███████▏  | 4849/6717 [16:31<06:19,  4.92it/s]

Processing tickers:  72%|███████▏  | 4850/6717 [16:32<06:19,  4.92it/s]

Processing tickers:  72%|███████▏  | 4851/6717 [16:32<06:18,  4.93it/s]

Processing tickers:  72%|███████▏  | 4852/6717 [16:32<06:18,  4.92it/s]

Processing tickers:  72%|███████▏  | 4853/6717 [16:32<06:15,  4.96it/s]

Processing tickers:  72%|███████▏  | 4854/6717 [16:32<06:17,  4.93it/s]

Processing tickers:  72%|███████▏  | 4855/6717 [16:33<06:16,  4.94it/s]

Processing tickers:  72%|███████▏  | 4856/6717 [16:33<06:20,  4.89it/s]

Processing tickers:  72%|███████▏  | 4857/6717 [16:33<06:19,  4.90it/s]

Processing tickers:  72%|███████▏  | 4858/6717 [16:33<06:29,  4.77it/s]

Processing tickers:  72%|███████▏  | 4859/6717 [16:33<06:26,  4.80it/s]

Processing tickers:  72%|███████▏  | 4860/6717 [16:34<06:24,  4.83it/s]

Processing tickers:  72%|███████▏  | 4861/6717 [16:34<06:24,  4.83it/s]

Processing tickers:  72%|███████▏  | 4862/6717 [16:34<06:23,  4.84it/s]

Processing tickers:  72%|███████▏  | 4863/6717 [16:34<06:23,  4.84it/s]

Processing tickers:  72%|███████▏  | 4864/6717 [16:34<06:19,  4.89it/s]

Processing tickers:  72%|███████▏  | 4865/6717 [16:35<06:21,  4.86it/s]

Processing tickers:  72%|███████▏  | 4866/6717 [16:35<06:17,  4.91it/s]

Processing tickers:  72%|███████▏  | 4867/6717 [16:35<06:23,  4.82it/s]

Processing tickers:  72%|███████▏  | 4868/6717 [16:35<06:30,  4.73it/s]

Processing tickers:  72%|███████▏  | 4869/6717 [16:35<06:24,  4.80it/s]

Processing tickers:  73%|███████▎  | 4870/6717 [16:36<06:22,  4.82it/s]

Processing tickers:  73%|███████▎  | 4871/6717 [16:36<06:19,  4.87it/s]

Processing tickers:  73%|███████▎  | 4872/6717 [16:36<06:19,  4.86it/s]

Processing tickers:  73%|███████▎  | 4873/6717 [16:36<06:16,  4.89it/s]

Processing tickers:  73%|███████▎  | 4874/6717 [16:36<06:15,  4.91it/s]

Processing tickers:  73%|███████▎  | 4875/6717 [16:37<06:14,  4.92it/s]

Processing tickers:  73%|███████▎  | 4876/6717 [16:37<06:17,  4.87it/s]

Processing tickers:  73%|███████▎  | 4877/6717 [16:37<06:15,  4.89it/s]

Processing tickers:  73%|███████▎  | 4878/6717 [16:37<06:14,  4.91it/s]

Processing tickers:  73%|███████▎  | 4879/6717 [16:37<06:15,  4.89it/s]

Processing tickers:  73%|███████▎  | 4880/6717 [16:38<06:18,  4.86it/s]

Processing tickers:  73%|███████▎  | 4881/6717 [16:38<06:15,  4.89it/s]

Processing tickers:  73%|███████▎  | 4882/6717 [16:38<06:12,  4.93it/s]

Processing tickers:  73%|███████▎  | 4883/6717 [16:38<06:12,  4.93it/s]

Processing tickers:  73%|███████▎  | 4884/6717 [16:38<06:10,  4.94it/s]

Processing tickers:  73%|███████▎  | 4885/6717 [16:39<06:10,  4.95it/s]

Processing tickers:  73%|███████▎  | 4886/6717 [16:39<06:10,  4.94it/s]

Processing tickers:  73%|███████▎  | 4887/6717 [16:39<06:09,  4.95it/s]

Processing tickers:  73%|███████▎  | 4888/6717 [16:39<06:13,  4.89it/s]

Processing tickers:  73%|███████▎  | 4889/6717 [16:40<06:15,  4.87it/s]

Processing tickers:  73%|███████▎  | 4890/6717 [16:40<06:11,  4.91it/s]

Processing tickers:  73%|███████▎  | 4891/6717 [16:40<06:11,  4.91it/s]

Processing tickers:  73%|███████▎  | 4892/6717 [16:40<06:07,  4.96it/s]

Processing tickers:  73%|███████▎  | 4893/6717 [16:40<06:08,  4.94it/s]

Processing tickers:  73%|███████▎  | 4894/6717 [16:41<06:08,  4.94it/s]

Processing tickers:  73%|███████▎  | 4895/6717 [16:41<06:12,  4.89it/s]

Processing tickers:  73%|███████▎  | 4896/6717 [16:41<06:15,  4.85it/s]

Processing tickers:  73%|███████▎  | 4897/6717 [16:41<06:11,  4.89it/s]

Processing tickers:  73%|███████▎  | 4898/6717 [16:41<06:10,  4.91it/s]

Processing tickers:  73%|███████▎  | 4899/6717 [16:42<06:12,  4.89it/s]

Processing tickers:  73%|███████▎  | 4900/6717 [16:42<06:16,  4.82it/s]

Processing tickers:  73%|███████▎  | 4901/6717 [16:42<06:13,  4.87it/s]

Processing tickers:  73%|███████▎  | 4902/6717 [16:42<06:15,  4.83it/s]

Processing tickers:  73%|███████▎  | 4903/6717 [16:42<06:12,  4.88it/s]

Processing tickers:  73%|███████▎  | 4904/6717 [16:43<06:11,  4.89it/s]

Processing tickers:  73%|███████▎  | 4905/6717 [16:43<06:08,  4.91it/s]

Processing tickers:  73%|███████▎  | 4906/6717 [16:43<06:05,  4.96it/s]

Processing tickers:  73%|███████▎  | 4907/6717 [16:43<06:04,  4.96it/s]

Processing tickers:  73%|███████▎  | 4908/6717 [16:43<06:07,  4.92it/s]

Processing tickers:  73%|███████▎  | 4909/6717 [16:44<06:18,  4.78it/s]

Processing tickers:  73%|███████▎  | 4910/6717 [16:44<06:13,  4.84it/s]

Processing tickers:  73%|███████▎  | 4911/6717 [16:44<06:15,  4.81it/s]

Processing tickers:  73%|███████▎  | 4912/6717 [16:44<06:13,  4.84it/s]

Processing tickers:  73%|███████▎  | 4913/6717 [16:44<06:21,  4.72it/s]

Processing tickers:  73%|███████▎  | 4914/6717 [16:45<06:20,  4.74it/s]

Processing tickers:  73%|███████▎  | 4915/6717 [16:45<06:13,  4.82it/s]

Processing tickers:  73%|███████▎  | 4916/6717 [16:45<06:12,  4.84it/s]

Processing tickers:  73%|███████▎  | 4917/6717 [16:45<06:07,  4.89it/s]

Processing tickers:  73%|███████▎  | 4918/6717 [16:45<06:06,  4.91it/s]

Processing tickers:  73%|███████▎  | 4919/6717 [16:46<06:06,  4.90it/s]

Processing tickers:  73%|███████▎  | 4920/6717 [16:46<06:04,  4.93it/s]

Processing tickers:  73%|███████▎  | 4921/6717 [16:46<06:04,  4.93it/s]

Processing tickers:  73%|███████▎  | 4922/6717 [16:46<06:02,  4.95it/s]

Processing tickers:  73%|███████▎  | 4923/6717 [16:46<06:02,  4.95it/s]

Processing tickers:  73%|███████▎  | 4924/6717 [16:47<06:04,  4.93it/s]

Processing tickers:  73%|███████▎  | 4925/6717 [16:47<06:08,  4.87it/s]

Processing tickers:  73%|███████▎  | 4926/6717 [16:47<06:07,  4.87it/s]

Processing tickers:  73%|███████▎  | 4927/6717 [16:47<06:05,  4.90it/s]

Processing tickers:  73%|███████▎  | 4928/6717 [16:47<06:03,  4.91it/s]

Processing tickers:  73%|███████▎  | 4929/6717 [16:48<06:03,  4.92it/s]

Processing tickers:  73%|███████▎  | 4930/6717 [16:48<06:02,  4.92it/s]

Processing tickers:  73%|███████▎  | 4931/6717 [16:48<06:01,  4.94it/s]

Processing tickers:  73%|███████▎  | 4932/6717 [16:48<06:01,  4.94it/s]

Processing tickers:  73%|███████▎  | 4933/6717 [16:49<06:00,  4.95it/s]

Processing tickers:  73%|███████▎  | 4934/6717 [16:49<05:59,  4.96it/s]

Processing tickers:  73%|███████▎  | 4935/6717 [16:49<06:01,  4.93it/s]

Processing tickers:  73%|███████▎  | 4936/6717 [16:49<06:00,  4.95it/s]

Processing tickers:  74%|███████▎  | 4937/6717 [16:49<05:59,  4.95it/s]

Processing tickers:  74%|███████▎  | 4938/6717 [16:50<05:57,  4.98it/s]

Processing tickers:  74%|███████▎  | 4939/6717 [16:50<05:55,  5.00it/s]

Processing tickers:  74%|███████▎  | 4940/6717 [16:50<05:58,  4.96it/s]

Processing tickers:  74%|███████▎  | 4941/6717 [16:50<05:56,  4.99it/s]

Processing tickers:  74%|███████▎  | 4942/6717 [16:50<05:58,  4.96it/s]

Processing tickers:  74%|███████▎  | 4943/6717 [16:51<05:59,  4.94it/s]

Processing tickers:  74%|███████▎  | 4944/6717 [16:51<06:02,  4.89it/s]

Processing tickers:  74%|███████▎  | 4945/6717 [16:51<06:02,  4.89it/s]

Processing tickers:  74%|███████▎  | 4946/6717 [16:51<06:06,  4.83it/s]

Processing tickers:  74%|███████▎  | 4947/6717 [16:51<06:03,  4.87it/s]

Processing tickers:  74%|███████▎  | 4948/6717 [16:52<06:03,  4.86it/s]

Processing tickers:  74%|███████▎  | 4949/6717 [16:52<06:00,  4.91it/s]

Processing tickers:  74%|███████▎  | 4950/6717 [16:52<05:59,  4.91it/s]

Processing tickers:  74%|███████▎  | 4951/6717 [16:52<06:02,  4.87it/s]

Processing tickers:  74%|███████▎  | 4952/6717 [16:52<06:00,  4.90it/s]

Processing tickers:  74%|███████▎  | 4953/6717 [16:53<05:59,  4.91it/s]

Processing tickers:  74%|███████▍  | 4954/6717 [16:53<05:57,  4.93it/s]

Processing tickers:  74%|███████▍  | 4955/6717 [16:53<05:55,  4.96it/s]

Processing tickers:  74%|███████▍  | 4956/6717 [16:53<05:56,  4.94it/s]

Processing tickers:  74%|███████▍  | 4957/6717 [16:53<05:56,  4.93it/s]

Processing tickers:  74%|███████▍  | 4958/6717 [16:54<05:55,  4.95it/s]

Processing tickers:  74%|███████▍  | 4959/6717 [16:54<05:54,  4.97it/s]

Processing tickers:  74%|███████▍  | 4960/6717 [16:54<05:55,  4.95it/s]

Processing tickers:  74%|███████▍  | 4961/6717 [16:54<05:53,  4.97it/s]

Processing tickers:  74%|███████▍  | 4962/6717 [16:54<05:54,  4.95it/s]

Processing tickers:  74%|███████▍  | 4963/6717 [16:55<05:53,  4.97it/s]

Processing tickers:  74%|███████▍  | 4964/6717 [16:55<05:52,  4.97it/s]

Processing tickers:  74%|███████▍  | 4965/6717 [16:55<05:55,  4.93it/s]

Processing tickers:  74%|███████▍  | 4966/6717 [16:55<05:56,  4.91it/s]

Processing tickers:  74%|███████▍  | 4967/6717 [16:55<05:58,  4.88it/s]

Processing tickers:  74%|███████▍  | 4968/6717 [16:56<06:00,  4.85it/s]

Processing tickers:  74%|███████▍  | 4969/6717 [16:56<05:56,  4.91it/s]

Processing tickers:  74%|███████▍  | 4970/6717 [16:56<05:59,  4.86it/s]

Processing tickers:  74%|███████▍  | 4971/6717 [16:56<05:56,  4.89it/s]

Processing tickers:  74%|███████▍  | 4972/6717 [16:56<05:57,  4.89it/s]

Processing tickers:  74%|███████▍  | 4973/6717 [16:57<05:54,  4.92it/s]

Processing tickers:  74%|███████▍  | 4974/6717 [16:57<05:55,  4.90it/s]

Processing tickers:  74%|███████▍  | 4975/6717 [16:57<05:53,  4.93it/s]

Processing tickers:  74%|███████▍  | 4976/6717 [16:57<05:52,  4.93it/s]

Processing tickers:  74%|███████▍  | 4977/6717 [16:57<05:53,  4.93it/s]

Processing tickers:  74%|███████▍  | 4978/6717 [16:58<05:51,  4.95it/s]

Processing tickers:  74%|███████▍  | 4979/6717 [16:58<05:58,  4.85it/s]

Processing tickers:  74%|███████▍  | 4980/6717 [16:58<06:01,  4.81it/s]

Processing tickers:  74%|███████▍  | 4981/6717 [16:58<05:57,  4.85it/s]

Processing tickers:  74%|███████▍  | 4982/6717 [16:58<05:55,  4.88it/s]

Processing tickers:  74%|███████▍  | 4983/6717 [16:59<05:55,  4.88it/s]

Processing tickers:  74%|███████▍  | 4984/6717 [16:59<05:54,  4.90it/s]

Processing tickers:  74%|███████▍  | 4985/6717 [16:59<05:54,  4.89it/s]

Processing tickers:  74%|███████▍  | 4986/6717 [16:59<05:52,  4.91it/s]

Processing tickers:  74%|███████▍  | 4987/6717 [16:59<05:55,  4.87it/s]

Processing tickers:  74%|███████▍  | 4988/6717 [17:00<06:05,  4.73it/s]

Processing tickers:  74%|███████▍  | 4989/6717 [17:00<06:03,  4.75it/s]

Processing tickers:  74%|███████▍  | 4990/6717 [17:00<06:00,  4.78it/s]

Processing tickers:  74%|███████▍  | 4991/6717 [17:00<05:56,  4.84it/s]

Processing tickers:  74%|███████▍  | 4992/6717 [17:01<05:52,  4.89it/s]

Processing tickers:  74%|███████▍  | 4993/6717 [17:01<05:51,  4.90it/s]

Processing tickers:  74%|███████▍  | 4994/6717 [17:01<05:50,  4.91it/s]

Processing tickers:  74%|███████▍  | 4995/6717 [17:01<05:50,  4.91it/s]

Processing tickers:  74%|███████▍  | 4996/6717 [17:01<05:49,  4.93it/s]

Processing tickers:  74%|███████▍  | 4997/6717 [17:02<05:48,  4.94it/s]

Processing tickers:  74%|███████▍  | 4998/6717 [17:02<05:51,  4.89it/s]

Processing tickers:  74%|███████▍  | 4999/6717 [17:02<05:49,  4.92it/s]

Processing tickers:  74%|███████▍  | 5000/6717 [17:02<05:55,  4.83it/s]

Processing tickers:  74%|███████▍  | 5001/6717 [17:02<05:52,  4.87it/s]

Processing tickers:  74%|███████▍  | 5002/6717 [17:03<05:50,  4.89it/s]

Processing tickers:  74%|███████▍  | 5003/6717 [17:03<05:52,  4.87it/s]

Processing tickers:  74%|███████▍  | 5004/6717 [17:03<06:20,  4.50it/s]

Processing tickers:  75%|███████▍  | 5005/6717 [17:03<06:11,  4.61it/s]

Processing tickers:  75%|███████▍  | 5006/6717 [17:03<06:02,  4.72it/s]

Processing tickers:  75%|███████▍  | 5007/6717 [17:04<06:05,  4.67it/s]

Processing tickers:  75%|███████▍  | 5008/6717 [17:04<06:06,  4.67it/s]

Processing tickers:  75%|███████▍  | 5009/6717 [17:04<06:00,  4.74it/s]

Processing tickers:  75%|███████▍  | 5010/6717 [17:04<05:56,  4.79it/s]

Processing tickers:  75%|███████▍  | 5011/6717 [17:04<05:52,  4.83it/s]

Processing tickers:  75%|███████▍  | 5012/6717 [17:05<05:48,  4.89it/s]

Processing tickers:  75%|███████▍  | 5013/6717 [17:05<05:47,  4.91it/s]

Processing tickers:  75%|███████▍  | 5014/6717 [17:05<05:47,  4.90it/s]

Processing tickers:  75%|███████▍  | 5015/6717 [17:05<05:47,  4.89it/s]

Processing tickers:  75%|███████▍  | 5016/6717 [17:06<05:45,  4.92it/s]

Processing tickers:  75%|███████▍  | 5017/6717 [17:06<05:45,  4.91it/s]

Processing tickers:  75%|███████▍  | 5018/6717 [17:06<05:44,  4.93it/s]

Processing tickers:  75%|███████▍  | 5019/6717 [17:06<05:51,  4.83it/s]

Processing tickers:  75%|███████▍  | 5020/6717 [17:06<05:48,  4.86it/s]

Processing tickers:  75%|███████▍  | 5021/6717 [17:07<05:47,  4.88it/s]

Processing tickers:  75%|███████▍  | 5022/6717 [17:07<05:45,  4.90it/s]

Processing tickers:  75%|███████▍  | 5023/6717 [17:07<05:53,  4.79it/s]

Processing tickers:  75%|███████▍  | 5024/6717 [17:07<05:49,  4.85it/s]

Processing tickers:  75%|███████▍  | 5025/6717 [17:07<05:45,  4.89it/s]

Processing tickers:  75%|███████▍  | 5026/6717 [17:08<05:43,  4.92it/s]

Processing tickers:  75%|███████▍  | 5027/6717 [17:08<05:43,  4.92it/s]

Processing tickers:  75%|███████▍  | 5028/6717 [17:08<05:51,  4.80it/s]

Processing tickers:  75%|███████▍  | 5029/6717 [17:08<05:50,  4.82it/s]

Processing tickers:  75%|███████▍  | 5030/6717 [17:08<05:46,  4.86it/s]

Processing tickers:  75%|███████▍  | 5031/6717 [17:09<05:44,  4.89it/s]

Processing tickers:  75%|███████▍  | 5032/6717 [17:09<05:42,  4.92it/s]

Processing tickers:  75%|███████▍  | 5033/6717 [17:09<05:50,  4.80it/s]

Processing tickers:  75%|███████▍  | 5034/6717 [17:09<05:47,  4.84it/s]

Processing tickers:  75%|███████▍  | 5035/6717 [17:09<05:52,  4.78it/s]

Processing tickers:  75%|███████▍  | 5036/6717 [17:10<05:49,  4.80it/s]

Processing tickers:  75%|███████▍  | 5037/6717 [17:10<05:50,  4.79it/s]

Processing tickers:  75%|███████▌  | 5038/6717 [17:10<05:47,  4.83it/s]

Processing tickers:  75%|███████▌  | 5039/6717 [17:10<05:43,  4.88it/s]

Processing tickers:  75%|███████▌  | 5040/6717 [17:10<05:42,  4.90it/s]

Processing tickers:  75%|███████▌  | 5041/6717 [17:11<05:39,  4.93it/s]

Processing tickers:  75%|███████▌  | 5042/6717 [17:11<05:38,  4.95it/s]

Processing tickers:  75%|███████▌  | 5043/6717 [17:11<05:38,  4.95it/s]

Processing tickers:  75%|███████▌  | 5044/6717 [17:11<05:37,  4.96it/s]

Processing tickers:  75%|███████▌  | 5045/6717 [17:11<05:37,  4.95it/s]

Processing tickers:  75%|███████▌  | 5046/6717 [17:12<05:36,  4.96it/s]

Processing tickers:  75%|███████▌  | 5047/6717 [17:12<05:36,  4.96it/s]

Processing tickers:  75%|███████▌  | 5048/6717 [17:12<05:35,  4.98it/s]

Processing tickers:  75%|███████▌  | 5049/6717 [17:12<05:38,  4.93it/s]

Processing tickers:  75%|███████▌  | 5050/6717 [17:12<05:37,  4.93it/s]

Processing tickers:  75%|███████▌  | 5051/6717 [17:13<05:40,  4.89it/s]

Processing tickers:  75%|███████▌  | 5052/6717 [17:13<05:39,  4.91it/s]

Processing tickers:  75%|███████▌  | 5053/6717 [17:13<05:38,  4.92it/s]

Processing tickers:  75%|███████▌  | 5054/6717 [17:13<05:35,  4.95it/s]

Processing tickers:  75%|███████▌  | 5055/6717 [17:13<05:34,  4.96it/s]

Processing tickers:  75%|███████▌  | 5056/6717 [17:14<05:32,  4.99it/s]

Processing tickers:  75%|███████▌  | 5057/6717 [17:14<05:35,  4.95it/s]

Processing tickers:  75%|███████▌  | 5058/6717 [17:14<05:38,  4.89it/s]

Processing tickers:  75%|███████▌  | 5059/6717 [17:14<05:36,  4.93it/s]

Processing tickers:  75%|███████▌  | 5060/6717 [17:14<05:35,  4.93it/s]

Processing tickers:  75%|███████▌  | 5061/6717 [17:15<05:37,  4.90it/s]

Processing tickers:  75%|███████▌  | 5062/6717 [17:15<05:36,  4.91it/s]

Processing tickers:  75%|███████▌  | 5063/6717 [17:15<05:35,  4.93it/s]

Processing tickers:  75%|███████▌  | 5064/6717 [17:15<05:35,  4.93it/s]

Processing tickers:  75%|███████▌  | 5065/6717 [17:16<05:34,  4.94it/s]

Processing tickers:  75%|███████▌  | 5066/6717 [17:16<05:33,  4.95it/s]

Processing tickers:  75%|███████▌  | 5067/6717 [17:16<05:35,  4.91it/s]

Processing tickers:  75%|███████▌  | 5068/6717 [17:16<05:34,  4.94it/s]

Processing tickers:  75%|███████▌  | 5069/6717 [17:16<05:35,  4.92it/s]

Processing tickers:  75%|███████▌  | 5070/6717 [17:17<05:34,  4.93it/s]

Processing tickers:  75%|███████▌  | 5071/6717 [17:17<05:35,  4.91it/s]

Processing tickers:  76%|███████▌  | 5072/6717 [17:17<05:33,  4.93it/s]

Processing tickers:  76%|███████▌  | 5073/6717 [17:17<05:32,  4.95it/s]

Processing tickers:  76%|███████▌  | 5074/6717 [17:17<05:33,  4.93it/s]

Processing tickers:  76%|███████▌  | 5075/6717 [17:18<05:32,  4.93it/s]

Processing tickers:  76%|███████▌  | 5076/6717 [17:18<05:37,  4.87it/s]

Processing tickers:  76%|███████▌  | 5077/6717 [17:18<05:35,  4.90it/s]

Processing tickers:  76%|███████▌  | 5078/6717 [17:18<05:32,  4.93it/s]

Processing tickers:  76%|███████▌  | 5079/6717 [17:18<05:32,  4.93it/s]

Processing tickers:  76%|███████▌  | 5080/6717 [17:19<05:32,  4.93it/s]

Processing tickers:  76%|███████▌  | 5081/6717 [17:19<05:29,  4.96it/s]

Processing tickers:  76%|███████▌  | 5082/6717 [17:19<05:29,  4.96it/s]

Processing tickers:  76%|███████▌  | 5083/6717 [17:19<05:30,  4.95it/s]

Processing tickers:  76%|███████▌  | 5084/6717 [17:19<05:28,  4.98it/s]

Processing tickers:  76%|███████▌  | 5085/6717 [17:20<05:27,  4.98it/s]

Processing tickers:  76%|███████▌  | 5086/6717 [17:20<05:26,  4.99it/s]

Processing tickers:  76%|███████▌  | 5087/6717 [17:20<05:28,  4.97it/s]

Processing tickers:  76%|███████▌  | 5088/6717 [17:20<05:28,  4.96it/s]

Processing tickers:  76%|███████▌  | 5089/6717 [17:20<05:28,  4.96it/s]

Processing tickers:  76%|███████▌  | 5090/6717 [17:21<05:29,  4.94it/s]

Processing tickers:  76%|███████▌  | 5091/6717 [17:21<05:32,  4.89it/s]

Processing tickers:  76%|███████▌  | 5092/6717 [17:21<05:31,  4.90it/s]

Processing tickers:  76%|███████▌  | 5093/6717 [17:21<05:30,  4.92it/s]

Processing tickers:  76%|███████▌  | 5094/6717 [17:21<05:28,  4.94it/s]

Processing tickers:  76%|███████▌  | 5095/6717 [17:22<05:26,  4.96it/s]

Processing tickers:  76%|███████▌  | 5096/6717 [17:22<05:25,  4.98it/s]

Processing tickers:  76%|███████▌  | 5097/6717 [17:22<05:31,  4.89it/s]

Processing tickers:  76%|███████▌  | 5098/6717 [17:22<05:29,  4.92it/s]

Processing tickers:  76%|███████▌  | 5099/6717 [17:22<05:28,  4.93it/s]

Processing tickers:  76%|███████▌  | 5100/6717 [17:23<05:27,  4.93it/s]

Processing tickers:  76%|███████▌  | 5101/6717 [17:23<05:27,  4.94it/s]

Processing tickers:  76%|███████▌  | 5102/6717 [17:23<05:28,  4.92it/s]

Processing tickers:  76%|███████▌  | 5103/6717 [17:23<05:28,  4.91it/s]

Processing tickers:  76%|███████▌  | 5104/6717 [17:23<05:26,  4.94it/s]

Processing tickers:  76%|███████▌  | 5105/6717 [17:24<05:22,  4.99it/s]

Processing tickers:  76%|███████▌  | 5106/6717 [17:24<05:22,  5.00it/s]

Processing tickers:  76%|███████▌  | 5107/6717 [17:24<05:27,  4.91it/s]

Processing tickers:  76%|███████▌  | 5108/6717 [17:24<05:27,  4.92it/s]

Processing tickers:  76%|███████▌  | 5109/6717 [17:24<05:26,  4.93it/s]

Processing tickers:  76%|███████▌  | 5110/6717 [17:25<05:25,  4.94it/s]

Processing tickers:  76%|███████▌  | 5111/6717 [17:25<05:28,  4.89it/s]

Processing tickers:  76%|███████▌  | 5112/6717 [17:25<05:31,  4.85it/s]

Processing tickers:  76%|███████▌  | 5113/6717 [17:25<05:30,  4.86it/s]

Processing tickers:  76%|███████▌  | 5114/6717 [17:25<05:29,  4.86it/s]

Processing tickers:  76%|███████▌  | 5115/6717 [17:26<05:28,  4.88it/s]

Processing tickers:  76%|███████▌  | 5116/6717 [17:26<05:26,  4.90it/s]

Processing tickers:  76%|███████▌  | 5117/6717 [17:26<05:24,  4.92it/s]

Processing tickers:  76%|███████▌  | 5118/6717 [17:26<05:23,  4.94it/s]

Processing tickers:  76%|███████▌  | 5119/6717 [17:26<05:20,  4.98it/s]

Processing tickers:  76%|███████▌  | 5120/6717 [17:27<05:20,  4.98it/s]

Processing tickers:  76%|███████▌  | 5121/6717 [17:27<05:21,  4.97it/s]

Processing tickers:  76%|███████▋  | 5122/6717 [17:27<05:21,  4.96it/s]

Processing tickers:  76%|███████▋  | 5123/6717 [17:27<05:21,  4.96it/s]

Processing tickers:  76%|███████▋  | 5124/6717 [17:27<05:24,  4.91it/s]

Processing tickers:  76%|███████▋  | 5125/6717 [17:28<05:24,  4.91it/s]

Processing tickers:  76%|███████▋  | 5126/6717 [17:28<05:24,  4.91it/s]

Processing tickers:  76%|███████▋  | 5127/6717 [17:28<05:23,  4.91it/s]

Processing tickers:  76%|███████▋  | 5128/6717 [17:28<05:23,  4.91it/s]

Processing tickers:  76%|███████▋  | 5129/6717 [17:28<05:26,  4.86it/s]

Processing tickers:  76%|███████▋  | 5130/6717 [17:29<05:27,  4.85it/s]

Processing tickers:  76%|███████▋  | 5131/6717 [17:29<05:24,  4.89it/s]

Processing tickers:  76%|███████▋  | 5132/6717 [17:29<05:21,  4.93it/s]

Processing tickers:  76%|███████▋  | 5133/6717 [17:29<05:21,  4.93it/s]

Processing tickers:  76%|███████▋  | 5134/6717 [17:30<05:20,  4.94it/s]

Processing tickers:  76%|███████▋  | 5135/6717 [17:30<05:20,  4.93it/s]

Processing tickers:  76%|███████▋  | 5136/6717 [17:30<05:19,  4.95it/s]

Processing tickers:  76%|███████▋  | 5137/6717 [17:30<05:24,  4.87it/s]

Processing tickers:  76%|███████▋  | 5138/6717 [17:30<05:24,  4.86it/s]

Processing tickers:  77%|███████▋  | 5139/6717 [17:31<05:22,  4.89it/s]

Processing tickers:  77%|███████▋  | 5140/6717 [17:31<05:19,  4.93it/s]

Processing tickers:  77%|███████▋  | 5141/6717 [17:31<05:18,  4.95it/s]

Processing tickers:  77%|███████▋  | 5142/6717 [17:31<05:17,  4.96it/s]

Processing tickers:  77%|███████▋  | 5143/6717 [17:31<05:21,  4.90it/s]

Processing tickers:  77%|███████▋  | 5144/6717 [17:32<05:22,  4.88it/s]

Processing tickers:  77%|███████▋  | 5145/6717 [17:32<05:19,  4.92it/s]

Processing tickers:  77%|███████▋  | 5146/6717 [17:32<05:24,  4.85it/s]

Processing tickers:  77%|███████▋  | 5147/6717 [17:32<05:21,  4.88it/s]

Processing tickers:  77%|███████▋  | 5148/6717 [17:32<05:20,  4.90it/s]

Processing tickers:  77%|███████▋  | 5149/6717 [17:33<05:17,  4.94it/s]

Processing tickers:  77%|███████▋  | 5150/6717 [17:33<05:17,  4.94it/s]

Processing tickers:  77%|███████▋  | 5151/6717 [17:33<05:22,  4.86it/s]

Processing tickers:  77%|███████▋  | 5152/6717 [17:33<05:19,  4.89it/s]

Processing tickers:  77%|███████▋  | 5153/6717 [17:33<05:17,  4.92it/s]

Processing tickers:  77%|███████▋  | 5154/6717 [17:34<05:17,  4.92it/s]

Processing tickers:  77%|███████▋  | 5155/6717 [17:34<05:15,  4.95it/s]

Processing tickers:  77%|███████▋  | 5156/6717 [17:34<05:19,  4.89it/s]

Processing tickers:  77%|███████▋  | 5157/6717 [17:34<05:23,  4.82it/s]

Processing tickers:  77%|███████▋  | 5158/6717 [17:34<05:22,  4.84it/s]

Processing tickers:  77%|███████▋  | 5159/6717 [17:35<05:22,  4.83it/s]

Processing tickers:  77%|███████▋  | 5160/6717 [17:35<05:22,  4.82it/s]

Processing tickers:  77%|███████▋  | 5161/6717 [17:35<05:18,  4.88it/s]

Processing tickers:  77%|███████▋  | 5162/6717 [17:35<05:16,  4.91it/s]

Processing tickers:  77%|███████▋  | 5163/6717 [17:35<05:16,  4.91it/s]

Processing tickers:  77%|███████▋  | 5164/6717 [17:36<05:15,  4.93it/s]

Processing tickers:  77%|███████▋  | 5165/6717 [17:36<05:15,  4.91it/s]

Processing tickers:  77%|███████▋  | 5166/6717 [17:36<05:15,  4.91it/s]

Processing tickers:  77%|███████▋  | 5167/6717 [17:36<05:16,  4.90it/s]

Processing tickers:  77%|███████▋  | 5168/6717 [17:36<05:15,  4.90it/s]

Processing tickers:  77%|███████▋  | 5169/6717 [17:37<05:16,  4.89it/s]

Processing tickers:  77%|███████▋  | 5170/6717 [17:37<05:19,  4.84it/s]

Processing tickers:  77%|███████▋  | 5171/6717 [17:37<05:18,  4.85it/s]

Processing tickers:  77%|███████▋  | 5172/6717 [17:37<05:14,  4.91it/s]

Processing tickers:  77%|███████▋  | 5173/6717 [17:37<05:13,  4.93it/s]

Processing tickers:  77%|███████▋  | 5174/6717 [17:38<05:13,  4.92it/s]

Processing tickers:  77%|███████▋  | 5175/6717 [17:38<05:11,  4.95it/s]

Processing tickers:  77%|███████▋  | 5176/6717 [17:38<05:11,  4.95it/s]

Processing tickers:  77%|███████▋  | 5177/6717 [17:38<05:11,  4.95it/s]

Processing tickers:  77%|███████▋  | 5178/6717 [17:38<05:12,  4.93it/s]

Processing tickers:  77%|███████▋  | 5179/6717 [17:39<05:13,  4.91it/s]

Processing tickers:  77%|███████▋  | 5180/6717 [17:39<05:11,  4.93it/s]

Processing tickers:  77%|███████▋  | 5181/6717 [17:39<05:12,  4.91it/s]

Processing tickers:  77%|███████▋  | 5182/6717 [17:39<05:11,  4.92it/s]

Processing tickers:  77%|███████▋  | 5183/6717 [17:39<05:08,  4.97it/s]

Processing tickers:  77%|███████▋  | 5184/6717 [17:40<05:07,  4.98it/s]

Processing tickers:  77%|███████▋  | 5185/6717 [17:40<05:06,  5.00it/s]

Processing tickers:  77%|███████▋  | 5186/6717 [17:40<05:06,  4.99it/s]

Processing tickers:  77%|███████▋  | 5187/6717 [17:40<05:06,  4.99it/s]

Processing tickers:  77%|███████▋  | 5188/6717 [17:40<05:06,  5.00it/s]

Processing tickers:  77%|███████▋  | 5189/6717 [17:41<05:05,  5.00it/s]

Processing tickers:  77%|███████▋  | 5190/6717 [17:41<05:06,  4.99it/s]

Processing tickers:  77%|███████▋  | 5191/6717 [17:41<05:05,  4.99it/s]

Processing tickers:  77%|███████▋  | 5192/6717 [17:41<05:05,  5.00it/s]

Processing tickers:  77%|███████▋  | 5193/6717 [17:41<05:04,  5.00it/s]

Processing tickers:  77%|███████▋  | 5194/6717 [17:42<05:05,  4.99it/s]

Processing tickers:  77%|███████▋  | 5195/6717 [17:42<05:04,  5.00it/s]

Processing tickers:  77%|███████▋  | 5196/6717 [17:42<05:04,  5.00it/s]

Processing tickers:  77%|███████▋  | 5197/6717 [17:42<05:04,  4.99it/s]

Processing tickers:  77%|███████▋  | 5198/6717 [17:43<05:04,  4.99it/s]

Processing tickers:  77%|███████▋  | 5199/6717 [17:43<05:02,  5.02it/s]

Processing tickers:  77%|███████▋  | 5200/6717 [17:43<05:02,  5.01it/s]

Processing tickers:  77%|███████▋  | 5201/6717 [17:43<05:08,  4.91it/s]

Processing tickers:  77%|███████▋  | 5202/6717 [17:43<05:07,  4.92it/s]

Processing tickers:  77%|███████▋  | 5203/6717 [17:44<05:05,  4.95it/s]

Processing tickers:  77%|███████▋  | 5204/6717 [17:44<05:05,  4.95it/s]

Processing tickers:  77%|███████▋  | 5205/6717 [17:44<05:04,  4.96it/s]

Processing tickers:  78%|███████▊  | 5206/6717 [17:44<05:02,  4.99it/s]

Processing tickers:  78%|███████▊  | 5207/6717 [17:44<05:04,  4.95it/s]

Processing tickers:  78%|███████▊  | 5208/6717 [17:45<05:07,  4.91it/s]

Processing tickers:  78%|███████▊  | 5209/6717 [17:45<05:10,  4.85it/s]

Processing tickers:  78%|███████▊  | 5210/6717 [17:45<05:07,  4.90it/s]

Processing tickers:  78%|███████▊  | 5211/6717 [17:45<05:09,  4.86it/s]

Processing tickers:  78%|███████▊  | 5212/6717 [17:45<05:14,  4.79it/s]

Processing tickers:  78%|███████▊  | 5213/6717 [17:46<05:09,  4.86it/s]

Processing tickers:  78%|███████▊  | 5214/6717 [17:46<05:07,  4.89it/s]

Processing tickers:  78%|███████▊  | 5215/6717 [17:46<05:05,  4.92it/s]

Processing tickers:  78%|███████▊  | 5216/6717 [17:46<05:04,  4.93it/s]

Processing tickers:  78%|███████▊  | 5217/6717 [17:46<05:06,  4.90it/s]

Processing tickers:  78%|███████▊  | 5218/6717 [17:47<05:05,  4.91it/s]

Processing tickers:  78%|███████▊  | 5219/6717 [17:47<05:05,  4.90it/s]

Processing tickers:  78%|███████▊  | 5220/6717 [17:47<05:14,  4.77it/s]

Processing tickers:  78%|███████▊  | 5221/6717 [17:47<05:25,  4.60it/s]

Processing tickers:  78%|███████▊  | 5222/6717 [17:47<05:17,  4.71it/s]

Processing tickers:  78%|███████▊  | 5223/6717 [17:48<05:13,  4.76it/s]

Processing tickers:  78%|███████▊  | 5224/6717 [17:48<05:12,  4.77it/s]

Processing tickers:  78%|███████▊  | 5225/6717 [17:48<05:09,  4.82it/s]

Processing tickers:  78%|███████▊  | 5226/6717 [17:48<05:13,  4.75it/s]

Processing tickers:  78%|███████▊  | 5227/6717 [17:48<05:18,  4.67it/s]

Processing tickers:  78%|███████▊  | 5228/6717 [17:49<05:12,  4.76it/s]

Processing tickers:  78%|███████▊  | 5229/6717 [17:49<05:08,  4.83it/s]

Processing tickers:  78%|███████▊  | 5230/6717 [17:49<05:07,  4.84it/s]

Processing tickers:  78%|███████▊  | 5231/6717 [17:49<05:05,  4.86it/s]

Processing tickers:  78%|███████▊  | 5232/6717 [17:50<05:03,  4.90it/s]

Processing tickers:  78%|███████▊  | 5233/6717 [17:50<05:02,  4.90it/s]

Processing tickers:  78%|███████▊  | 5234/6717 [17:50<05:02,  4.90it/s]

Processing tickers:  78%|███████▊  | 5235/6717 [17:50<05:00,  4.93it/s]

Processing tickers:  78%|███████▊  | 5236/6717 [17:50<05:00,  4.94it/s]

Processing tickers:  78%|███████▊  | 5237/6717 [17:51<04:59,  4.94it/s]

Processing tickers:  78%|███████▊  | 5238/6717 [17:51<05:01,  4.90it/s]

Processing tickers:  78%|███████▊  | 5239/6717 [17:51<05:03,  4.87it/s]

Processing tickers:  78%|███████▊  | 5240/6717 [17:51<05:00,  4.92it/s]

Processing tickers:  78%|███████▊  | 5241/6717 [17:51<05:01,  4.90it/s]

Processing tickers:  78%|███████▊  | 5242/6717 [17:52<05:00,  4.90it/s]

Processing tickers:  78%|███████▊  | 5243/6717 [17:52<05:04,  4.85it/s]

Processing tickers:  78%|███████▊  | 5244/6717 [17:52<05:01,  4.88it/s]

Processing tickers:  78%|███████▊  | 5245/6717 [17:52<05:03,  4.85it/s]

Processing tickers:  78%|███████▊  | 5246/6717 [17:52<05:02,  4.86it/s]

Processing tickers:  78%|███████▊  | 5247/6717 [17:53<04:59,  4.90it/s]

Processing tickers:  78%|███████▊  | 5248/6717 [17:53<04:58,  4.92it/s]

Processing tickers:  78%|███████▊  | 5249/6717 [17:53<04:58,  4.92it/s]

Processing tickers:  78%|███████▊  | 5250/6717 [17:53<04:58,  4.92it/s]

Processing tickers:  78%|███████▊  | 5251/6717 [17:53<04:58,  4.92it/s]

Processing tickers:  78%|███████▊  | 5252/6717 [17:54<04:57,  4.93it/s]

Processing tickers:  78%|███████▊  | 5253/6717 [17:54<04:57,  4.93it/s]

Processing tickers:  78%|███████▊  | 5254/6717 [17:54<05:00,  4.87it/s]

Processing tickers:  78%|███████▊  | 5255/6717 [17:54<05:00,  4.86it/s]

Processing tickers:  78%|███████▊  | 5256/6717 [17:54<04:59,  4.88it/s]

Processing tickers:  78%|███████▊  | 5257/6717 [17:55<04:58,  4.90it/s]

Processing tickers:  78%|███████▊  | 5258/6717 [17:55<04:56,  4.91it/s]

Processing tickers:  78%|███████▊  | 5259/6717 [17:55<05:07,  4.74it/s]

Processing tickers:  78%|███████▊  | 5260/6717 [17:55<05:03,  4.81it/s]

Processing tickers:  78%|███████▊  | 5261/6717 [17:55<05:01,  4.83it/s]

Processing tickers:  78%|███████▊  | 5262/6717 [17:56<04:58,  4.88it/s]

Processing tickers:  78%|███████▊  | 5263/6717 [17:56<04:58,  4.87it/s]

Processing tickers:  78%|███████▊  | 5264/6717 [17:56<04:55,  4.92it/s]

Processing tickers:  78%|███████▊  | 5265/6717 [17:56<04:54,  4.93it/s]

Processing tickers:  78%|███████▊  | 5266/6717 [17:56<04:53,  4.95it/s]

Processing tickers:  78%|███████▊  | 5267/6717 [17:57<04:53,  4.95it/s]

Processing tickers:  78%|███████▊  | 5268/6717 [17:57<04:57,  4.87it/s]

Processing tickers:  78%|███████▊  | 5269/6717 [17:57<04:58,  4.85it/s]

Processing tickers:  78%|███████▊  | 5270/6717 [17:57<04:55,  4.89it/s]

Processing tickers:  78%|███████▊  | 5271/6717 [17:57<04:55,  4.89it/s]

Processing tickers:  78%|███████▊  | 5272/6717 [17:58<04:55,  4.90it/s]

Processing tickers:  79%|███████▊  | 5273/6717 [17:58<04:53,  4.92it/s]

Processing tickers:  79%|███████▊  | 5274/6717 [17:58<04:55,  4.88it/s]

Processing tickers:  79%|███████▊  | 5275/6717 [17:58<04:55,  4.89it/s]

Processing tickers:  79%|███████▊  | 5276/6717 [17:58<04:52,  4.93it/s]

Processing tickers:  79%|███████▊  | 5277/6717 [17:59<04:52,  4.93it/s]

Processing tickers:  79%|███████▊  | 5278/6717 [17:59<04:50,  4.95it/s]

Processing tickers:  79%|███████▊  | 5279/6717 [17:59<04:50,  4.95it/s]

Processing tickers:  79%|███████▊  | 5280/6717 [17:59<04:49,  4.97it/s]

Processing tickers:  79%|███████▊  | 5281/6717 [18:00<04:50,  4.94it/s]

Processing tickers:  79%|███████▊  | 5282/6717 [18:00<04:49,  4.96it/s]

Processing tickers:  79%|███████▊  | 5283/6717 [18:00<04:51,  4.91it/s]

Processing tickers:  79%|███████▊  | 5284/6717 [18:00<04:50,  4.93it/s]

Processing tickers:  79%|███████▊  | 5285/6717 [18:00<04:50,  4.93it/s]

Processing tickers:  79%|███████▊  | 5286/6717 [18:01<04:50,  4.93it/s]

Processing tickers:  79%|███████▊  | 5287/6717 [18:01<04:49,  4.93it/s]

Processing tickers:  79%|███████▊  | 5288/6717 [18:01<04:48,  4.94it/s]

Processing tickers:  79%|███████▊  | 5289/6717 [18:01<04:48,  4.95it/s]

Processing tickers:  79%|███████▉  | 5290/6717 [18:01<04:47,  4.96it/s]

Processing tickers:  79%|███████▉  | 5291/6717 [18:02<04:49,  4.92it/s]

Processing tickers:  79%|███████▉  | 5292/6717 [18:02<04:50,  4.91it/s]

Processing tickers:  79%|███████▉  | 5293/6717 [18:02<04:47,  4.96it/s]

Processing tickers:  79%|███████▉  | 5294/6717 [18:02<04:47,  4.95it/s]

Processing tickers:  79%|███████▉  | 5295/6717 [18:02<04:46,  4.96it/s]

Processing tickers:  79%|███████▉  | 5296/6717 [18:03<04:46,  4.97it/s]

Processing tickers:  79%|███████▉  | 5297/6717 [18:03<04:46,  4.95it/s]

Processing tickers:  79%|███████▉  | 5298/6717 [18:03<04:45,  4.97it/s]

Processing tickers:  79%|███████▉  | 5299/6717 [18:03<04:46,  4.95it/s]

Processing tickers:  79%|███████▉  | 5300/6717 [18:03<04:46,  4.95it/s]

Processing tickers:  79%|███████▉  | 5301/6717 [18:04<04:46,  4.95it/s]

Processing tickers:  79%|███████▉  | 5302/6717 [18:04<04:45,  4.96it/s]

Processing tickers:  79%|███████▉  | 5303/6717 [18:04<04:48,  4.90it/s]

Processing tickers:  79%|███████▉  | 5304/6717 [18:04<04:47,  4.92it/s]

Processing tickers:  79%|███████▉  | 5305/6717 [18:04<04:47,  4.91it/s]

Processing tickers:  79%|███████▉  | 5306/6717 [18:05<04:45,  4.95it/s]

Processing tickers:  79%|███████▉  | 5307/6717 [18:05<05:11,  4.52it/s]

Processing tickers:  79%|███████▉  | 5308/6717 [18:05<05:03,  4.64it/s]

Processing tickers:  79%|███████▉  | 5309/6717 [18:05<04:57,  4.74it/s]

Processing tickers:  79%|███████▉  | 5310/6717 [18:05<04:53,  4.80it/s]

Processing tickers:  79%|███████▉  | 5311/6717 [18:06<04:50,  4.85it/s]

Processing tickers:  79%|███████▉  | 5312/6717 [18:06<04:48,  4.87it/s]

Processing tickers:  79%|███████▉  | 5313/6717 [18:06<04:47,  4.88it/s]

Processing tickers:  79%|███████▉  | 5314/6717 [18:06<04:46,  4.89it/s]

Processing tickers:  79%|███████▉  | 5315/6717 [18:06<04:45,  4.91it/s]

Processing tickers:  79%|███████▉  | 5316/6717 [18:07<04:44,  4.93it/s]

Processing tickers:  79%|███████▉  | 5317/6717 [18:07<04:46,  4.88it/s]

Processing tickers:  79%|███████▉  | 5318/6717 [18:07<04:47,  4.86it/s]

Processing tickers:  79%|███████▉  | 5319/6717 [18:07<04:45,  4.89it/s]

Processing tickers:  79%|███████▉  | 5320/6717 [18:07<04:43,  4.92it/s]

Processing tickers:  79%|███████▉  | 5321/6717 [18:08<04:42,  4.95it/s]

Processing tickers:  79%|███████▉  | 5322/6717 [18:08<04:41,  4.96it/s]

Processing tickers:  79%|███████▉  | 5323/6717 [18:08<04:40,  4.96it/s]

Processing tickers:  79%|███████▉  | 5324/6717 [18:08<04:43,  4.92it/s]

Processing tickers:  79%|███████▉  | 5325/6717 [18:08<04:41,  4.95it/s]

Processing tickers:  79%|███████▉  | 5326/6717 [18:09<04:39,  4.97it/s]

Processing tickers:  79%|███████▉  | 5327/6717 [18:09<04:40,  4.96it/s]

Processing tickers:  79%|███████▉  | 5328/6717 [18:09<04:38,  4.99it/s]

Processing tickers:  79%|███████▉  | 5329/6717 [18:09<04:38,  4.98it/s]

Processing tickers:  79%|███████▉  | 5330/6717 [18:09<04:42,  4.92it/s]

Processing tickers:  79%|███████▉  | 5331/6717 [18:10<04:40,  4.94it/s]

Processing tickers:  79%|███████▉  | 5332/6717 [18:10<04:44,  4.87it/s]

Processing tickers:  79%|███████▉  | 5333/6717 [18:10<04:41,  4.91it/s]

Processing tickers:  79%|███████▉  | 5334/6717 [18:10<04:39,  4.95it/s]

Processing tickers:  79%|███████▉  | 5335/6717 [18:11<04:40,  4.93it/s]

Processing tickers:  79%|███████▉  | 5336/6717 [18:11<04:40,  4.92it/s]

Processing tickers:  79%|███████▉  | 5337/6717 [18:11<04:39,  4.94it/s]

Processing tickers:  79%|███████▉  | 5338/6717 [18:11<04:40,  4.92it/s]

Processing tickers:  79%|███████▉  | 5339/6717 [18:11<04:37,  4.97it/s]

Processing tickers:  79%|███████▉  | 5340/6717 [18:12<04:36,  4.97it/s]

Processing tickers:  80%|███████▉  | 5341/6717 [18:12<04:36,  4.97it/s]

Processing tickers:  80%|███████▉  | 5342/6717 [18:12<04:38,  4.93it/s]

Processing tickers:  80%|███████▉  | 5343/6717 [18:12<04:39,  4.92it/s]

Processing tickers:  80%|███████▉  | 5344/6717 [18:12<04:39,  4.92it/s]

Processing tickers:  80%|███████▉  | 5345/6717 [18:13<04:40,  4.90it/s]

Processing tickers:  80%|███████▉  | 5346/6717 [18:13<04:39,  4.91it/s]

Processing tickers:  80%|███████▉  | 5347/6717 [18:13<04:39,  4.90it/s]

Processing tickers:  80%|███████▉  | 5348/6717 [18:13<04:38,  4.91it/s]

Processing tickers:  80%|███████▉  | 5349/6717 [18:13<04:39,  4.90it/s]

Processing tickers:  80%|███████▉  | 5350/6717 [18:14<04:39,  4.88it/s]

Processing tickers:  80%|███████▉  | 5351/6717 [18:14<04:41,  4.86it/s]

Processing tickers:  80%|███████▉  | 5352/6717 [18:14<04:38,  4.90it/s]

Processing tickers:  80%|███████▉  | 5353/6717 [18:14<04:45,  4.78it/s]

Processing tickers:  80%|███████▉  | 5354/6717 [18:14<04:42,  4.83it/s]

Processing tickers:  80%|███████▉  | 5355/6717 [18:15<04:39,  4.87it/s]

Processing tickers:  80%|███████▉  | 5356/6717 [18:15<04:37,  4.90it/s]

Processing tickers:  80%|███████▉  | 5357/6717 [18:15<04:45,  4.76it/s]

Processing tickers:  80%|███████▉  | 5358/6717 [18:15<04:43,  4.80it/s]

Processing tickers:  80%|███████▉  | 5359/6717 [18:15<04:42,  4.82it/s]

Processing tickers:  80%|███████▉  | 5360/6717 [18:16<04:40,  4.84it/s]

Processing tickers:  80%|███████▉  | 5361/6717 [18:16<04:38,  4.87it/s]

Processing tickers:  80%|███████▉  | 5362/6717 [18:16<04:36,  4.90it/s]

Processing tickers:  80%|███████▉  | 5363/6717 [18:16<04:34,  4.93it/s]

Processing tickers:  80%|███████▉  | 5364/6717 [18:16<04:32,  4.97it/s]

Processing tickers:  80%|███████▉  | 5365/6717 [18:17<04:37,  4.88it/s]

Processing tickers:  80%|███████▉  | 5366/6717 [18:17<04:36,  4.89it/s]

Processing tickers:  80%|███████▉  | 5367/6717 [18:17<04:33,  4.93it/s]

Processing tickers:  80%|███████▉  | 5368/6717 [18:17<04:35,  4.89it/s]

Processing tickers:  80%|███████▉  | 5369/6717 [18:17<04:33,  4.92it/s]

Processing tickers:  80%|███████▉  | 5370/6717 [18:18<04:32,  4.94it/s]

Processing tickers:  80%|███████▉  | 5371/6717 [18:18<04:32,  4.94it/s]

Processing tickers:  80%|███████▉  | 5372/6717 [18:18<04:31,  4.95it/s]

Processing tickers:  80%|███████▉  | 5373/6717 [18:18<04:31,  4.95it/s]

Processing tickers:  80%|████████  | 5374/6717 [18:18<04:30,  4.97it/s]

Processing tickers:  80%|████████  | 5375/6717 [18:19<04:29,  4.97it/s]

Processing tickers:  80%|████████  | 5376/6717 [18:19<04:29,  4.97it/s]

Processing tickers:  80%|████████  | 5377/6717 [18:19<04:29,  4.97it/s]

Processing tickers:  80%|████████  | 5378/6717 [18:19<04:28,  4.98it/s]

Processing tickers:  80%|████████  | 5379/6717 [18:19<04:28,  4.99it/s]

Processing tickers:  80%|████████  | 5380/6717 [18:20<04:30,  4.95it/s]

Processing tickers:  80%|████████  | 5381/6717 [18:20<04:31,  4.92it/s]

Processing tickers:  80%|████████  | 5382/6717 [18:20<04:30,  4.94it/s]

Processing tickers:  80%|████████  | 5383/6717 [18:20<04:32,  4.90it/s]

Processing tickers:  80%|████████  | 5384/6717 [18:20<04:31,  4.92it/s]

Processing tickers:  80%|████████  | 5385/6717 [18:21<04:30,  4.93it/s]

Processing tickers:  80%|████████  | 5386/6717 [18:21<04:28,  4.95it/s]

Processing tickers:  80%|████████  | 5387/6717 [18:21<04:29,  4.93it/s]

Processing tickers:  80%|████████  | 5388/6717 [18:21<04:29,  4.93it/s]

Processing tickers:  80%|████████  | 5389/6717 [18:21<04:31,  4.90it/s]

Processing tickers:  80%|████████  | 5390/6717 [18:22<04:32,  4.88it/s]

Processing tickers:  80%|████████  | 5391/6717 [18:22<04:30,  4.89it/s]

Processing tickers:  80%|████████  | 5392/6717 [18:22<04:28,  4.93it/s]

Processing tickers:  80%|████████  | 5393/6717 [18:22<04:27,  4.94it/s]

Processing tickers:  80%|████████  | 5394/6717 [18:23<04:27,  4.94it/s]

Processing tickers:  80%|████████  | 5395/6717 [18:23<04:26,  4.96it/s]

Processing tickers:  80%|████████  | 5396/6717 [18:23<04:26,  4.95it/s]

Processing tickers:  80%|████████  | 5397/6717 [18:23<04:26,  4.96it/s]

Processing tickers:  80%|████████  | 5398/6717 [18:23<04:29,  4.90it/s]

Processing tickers:  80%|████████  | 5399/6717 [18:24<04:27,  4.92it/s]

Processing tickers:  80%|████████  | 5400/6717 [18:24<04:26,  4.94it/s]

Processing tickers:  80%|████████  | 5401/6717 [18:24<04:26,  4.93it/s]

Processing tickers:  80%|████████  | 5402/6717 [18:24<04:27,  4.92it/s]

Processing tickers:  80%|████████  | 5403/6717 [18:24<04:26,  4.92it/s]

Processing tickers:  80%|████████  | 5404/6717 [18:25<04:30,  4.85it/s]

Processing tickers:  80%|████████  | 5405/6717 [18:25<04:27,  4.90it/s]

Processing tickers:  80%|████████  | 5406/6717 [18:25<04:26,  4.92it/s]

Processing tickers:  80%|████████  | 5407/6717 [18:25<04:24,  4.95it/s]

Processing tickers:  81%|████████  | 5408/6717 [18:25<04:27,  4.90it/s]

Processing tickers:  81%|████████  | 5409/6717 [18:26<04:29,  4.85it/s]

Processing tickers:  81%|████████  | 5410/6717 [18:26<04:27,  4.89it/s]

Processing tickers:  81%|████████  | 5411/6717 [18:26<04:25,  4.92it/s]

Processing tickers:  81%|████████  | 5412/6717 [18:26<04:24,  4.94it/s]

Processing tickers:  81%|████████  | 5413/6717 [18:26<04:24,  4.94it/s]

Processing tickers:  81%|████████  | 5414/6717 [18:27<04:26,  4.89it/s]

Processing tickers:  81%|████████  | 5415/6717 [18:27<04:24,  4.92it/s]

Processing tickers:  81%|████████  | 5416/6717 [18:27<04:27,  4.86it/s]

Processing tickers:  81%|████████  | 5417/6717 [18:27<04:26,  4.87it/s]

Processing tickers:  81%|████████  | 5418/6717 [18:27<04:23,  4.92it/s]

Processing tickers:  81%|████████  | 5419/6717 [18:28<04:23,  4.92it/s]

Processing tickers:  81%|████████  | 5420/6717 [18:28<04:26,  4.86it/s]

Processing tickers:  81%|████████  | 5421/6717 [18:28<04:27,  4.84it/s]

Processing tickers:  81%|████████  | 5422/6717 [18:28<04:25,  4.89it/s]

Processing tickers:  81%|████████  | 5423/6717 [18:28<04:26,  4.86it/s]

Processing tickers:  81%|████████  | 5424/6717 [18:29<04:23,  4.91it/s]

Processing tickers:  81%|████████  | 5425/6717 [18:29<04:23,  4.91it/s]

Processing tickers:  81%|████████  | 5426/6717 [18:29<04:23,  4.90it/s]

Processing tickers:  81%|████████  | 5427/6717 [18:29<04:25,  4.87it/s]

Processing tickers:  81%|████████  | 5428/6717 [18:29<04:24,  4.87it/s]

Processing tickers:  81%|████████  | 5429/6717 [18:30<04:22,  4.90it/s]

Processing tickers:  81%|████████  | 5430/6717 [18:30<04:21,  4.91it/s]

Processing tickers:  81%|████████  | 5431/6717 [18:30<04:21,  4.91it/s]

Processing tickers:  81%|████████  | 5432/6717 [18:30<04:21,  4.92it/s]

Processing tickers:  81%|████████  | 5433/6717 [18:30<04:22,  4.89it/s]

Processing tickers:  81%|████████  | 5434/6717 [18:31<04:20,  4.93it/s]

Processing tickers:  81%|████████  | 5435/6717 [18:31<04:20,  4.92it/s]

Processing tickers:  81%|████████  | 5436/6717 [18:31<04:19,  4.94it/s]

Processing tickers:  81%|████████  | 5437/6717 [18:31<04:18,  4.96it/s]

Processing tickers:  81%|████████  | 5438/6717 [18:31<04:21,  4.90it/s]

Processing tickers:  81%|████████  | 5439/6717 [18:32<04:21,  4.89it/s]

Processing tickers:  81%|████████  | 5440/6717 [18:32<04:19,  4.92it/s]

Processing tickers:  81%|████████  | 5441/6717 [18:32<04:18,  4.94it/s]

Processing tickers:  81%|████████  | 5442/6717 [18:32<04:15,  4.99it/s]

Processing tickers:  81%|████████  | 5443/6717 [18:32<04:14,  5.00it/s]

Processing tickers:  81%|████████  | 5444/6717 [18:33<04:13,  5.03it/s]

Processing tickers:  81%|████████  | 5445/6717 [18:33<04:19,  4.90it/s]

Processing tickers:  81%|████████  | 5446/6717 [18:33<04:18,  4.91it/s]

Processing tickers:  81%|████████  | 5447/6717 [18:33<04:18,  4.92it/s]

Processing tickers:  81%|████████  | 5448/6717 [18:34<04:17,  4.92it/s]

Processing tickers:  81%|████████  | 5449/6717 [18:34<04:17,  4.92it/s]

Processing tickers:  81%|████████  | 5450/6717 [18:34<04:15,  4.95it/s]

Processing tickers:  81%|████████  | 5451/6717 [18:34<04:15,  4.95it/s]

Processing tickers:  81%|████████  | 5452/6717 [18:34<04:15,  4.95it/s]

Processing tickers:  81%|████████  | 5453/6717 [18:35<04:15,  4.95it/s]

Processing tickers:  81%|████████  | 5454/6717 [18:35<04:19,  4.87it/s]

Processing tickers:  81%|████████  | 5455/6717 [18:35<04:18,  4.88it/s]

Processing tickers:  81%|████████  | 5456/6717 [18:35<04:17,  4.89it/s]

Processing tickers:  81%|████████  | 5457/6717 [18:35<04:16,  4.91it/s]

Processing tickers:  81%|████████▏ | 5458/6717 [18:36<04:16,  4.91it/s]

Processing tickers:  81%|████████▏ | 5459/6717 [18:36<04:14,  4.94it/s]

Processing tickers:  81%|████████▏ | 5460/6717 [18:36<04:13,  4.96it/s]

Processing tickers:  81%|████████▏ | 5461/6717 [18:36<04:12,  4.97it/s]

Processing tickers:  81%|████████▏ | 5462/6717 [18:36<04:13,  4.96it/s]

Processing tickers:  81%|████████▏ | 5463/6717 [18:37<04:13,  4.95it/s]

Processing tickers:  81%|████████▏ | 5464/6717 [18:37<04:14,  4.92it/s]

Processing tickers:  81%|████████▏ | 5465/6717 [18:37<04:13,  4.94it/s]

Processing tickers:  81%|████████▏ | 5466/6717 [18:37<04:17,  4.86it/s]

Processing tickers:  81%|████████▏ | 5467/6717 [18:37<04:16,  4.87it/s]

Processing tickers:  81%|████████▏ | 5468/6717 [18:38<04:13,  4.92it/s]

Processing tickers:  81%|████████▏ | 5469/6717 [18:38<04:13,  4.93it/s]

Processing tickers:  81%|████████▏ | 5470/6717 [18:38<04:11,  4.95it/s]

Processing tickers:  81%|████████▏ | 5471/6717 [18:38<04:09,  4.99it/s]

Processing tickers:  81%|████████▏ | 5472/6717 [18:38<04:13,  4.92it/s]

Processing tickers:  81%|████████▏ | 5473/6717 [18:39<04:12,  4.92it/s]

Processing tickers:  81%|████████▏ | 5474/6717 [18:39<04:11,  4.94it/s]

Processing tickers:  82%|████████▏ | 5475/6717 [18:39<04:10,  4.96it/s]

Processing tickers:  82%|████████▏ | 5476/6717 [18:39<04:09,  4.98it/s]

Processing tickers:  82%|████████▏ | 5477/6717 [18:39<04:10,  4.95it/s]

Processing tickers:  82%|████████▏ | 5478/6717 [18:40<04:09,  4.96it/s]

Processing tickers:  82%|████████▏ | 5479/6717 [18:40<04:08,  4.98it/s]

Processing tickers:  82%|████████▏ | 5480/6717 [18:40<04:06,  5.01it/s]

Processing tickers:  82%|████████▏ | 5481/6717 [18:40<04:07,  4.99it/s]

Processing tickers:  82%|████████▏ | 5482/6717 [18:40<04:07,  4.98it/s]

Processing tickers:  82%|████████▏ | 5483/6717 [18:41<04:07,  5.00it/s]

Processing tickers:  82%|████████▏ | 5484/6717 [18:41<04:06,  4.99it/s]

Processing tickers:  82%|████████▏ | 5485/6717 [18:41<04:12,  4.89it/s]

Processing tickers:  82%|████████▏ | 5486/6717 [18:41<04:10,  4.91it/s]

Processing tickers:  82%|████████▏ | 5487/6717 [18:41<04:10,  4.91it/s]

Processing tickers:  82%|████████▏ | 5488/6717 [18:42<04:10,  4.91it/s]

Processing tickers:  82%|████████▏ | 5489/6717 [18:42<04:09,  4.92it/s]

Processing tickers:  82%|████████▏ | 5490/6717 [18:42<04:11,  4.89it/s]

Processing tickers:  82%|████████▏ | 5491/6717 [18:42<04:10,  4.89it/s]

Processing tickers:  82%|████████▏ | 5492/6717 [18:42<04:08,  4.94it/s]

Processing tickers:  82%|████████▏ | 5493/6717 [18:43<04:06,  4.97it/s]

Processing tickers:  82%|████████▏ | 5494/6717 [18:43<04:06,  4.96it/s]

Processing tickers:  82%|████████▏ | 5495/6717 [18:43<04:07,  4.93it/s]

Processing tickers:  82%|████████▏ | 5496/6717 [18:43<04:08,  4.91it/s]

Processing tickers:  82%|████████▏ | 5497/6717 [18:43<04:11,  4.86it/s]

Processing tickers:  82%|████████▏ | 5498/6717 [18:44<04:07,  4.93it/s]

Processing tickers:  82%|████████▏ | 5499/6717 [18:44<04:05,  4.96it/s]

Processing tickers:  82%|████████▏ | 5500/6717 [18:44<04:05,  4.95it/s]

Processing tickers:  82%|████████▏ | 5501/6717 [18:44<04:05,  4.95it/s]

Processing tickers:  82%|████████▏ | 5502/6717 [18:44<04:06,  4.93it/s]

Processing tickers:  82%|████████▏ | 5503/6717 [18:45<04:09,  4.86it/s]

Processing tickers:  82%|████████▏ | 5504/6717 [18:45<04:06,  4.92it/s]

Processing tickers:  82%|████████▏ | 5505/6717 [18:45<04:05,  4.94it/s]

Processing tickers:  82%|████████▏ | 5506/6717 [18:45<04:06,  4.92it/s]

Processing tickers:  82%|████████▏ | 5507/6717 [18:45<04:04,  4.94it/s]

Processing tickers:  82%|████████▏ | 5508/6717 [18:46<04:03,  4.96it/s]

Processing tickers:  82%|████████▏ | 5509/6717 [18:46<04:04,  4.93it/s]

Processing tickers:  82%|████████▏ | 5510/6717 [18:46<04:07,  4.88it/s]

Processing tickers:  82%|████████▏ | 5511/6717 [18:46<04:06,  4.89it/s]

Processing tickers:  82%|████████▏ | 5512/6717 [18:46<04:04,  4.93it/s]

Processing tickers:  82%|████████▏ | 5513/6717 [18:47<04:03,  4.94it/s]

Processing tickers:  82%|████████▏ | 5514/6717 [18:47<04:03,  4.94it/s]

Processing tickers:  82%|████████▏ | 5515/6717 [18:47<04:11,  4.78it/s]

Processing tickers:  82%|████████▏ | 5516/6717 [18:47<04:09,  4.82it/s]

Processing tickers:  82%|████████▏ | 5517/6717 [18:48<04:06,  4.87it/s]

Processing tickers:  82%|████████▏ | 5518/6717 [18:48<04:05,  4.88it/s]

Processing tickers:  82%|████████▏ | 5519/6717 [18:48<04:03,  4.91it/s]

Processing tickers:  82%|████████▏ | 5520/6717 [18:48<04:05,  4.88it/s]

Processing tickers:  82%|████████▏ | 5521/6717 [18:48<04:02,  4.92it/s]

Processing tickers:  82%|████████▏ | 5522/6717 [18:49<04:02,  4.92it/s]

Processing tickers:  82%|████████▏ | 5523/6717 [18:49<04:04,  4.89it/s]

Processing tickers:  82%|████████▏ | 5524/6717 [18:49<04:03,  4.91it/s]

Processing tickers:  82%|████████▏ | 5525/6717 [18:49<04:00,  4.95it/s]

Processing tickers:  82%|████████▏ | 5526/6717 [18:49<03:59,  4.97it/s]

Processing tickers:  82%|████████▏ | 5527/6717 [18:50<04:00,  4.95it/s]

Processing tickers:  82%|████████▏ | 5528/6717 [18:50<04:01,  4.93it/s]

Processing tickers:  82%|████████▏ | 5529/6717 [18:50<04:04,  4.85it/s]

Processing tickers:  82%|████████▏ | 5530/6717 [18:50<04:02,  4.89it/s]

Processing tickers:  82%|████████▏ | 5531/6717 [18:50<04:01,  4.90it/s]

Processing tickers:  82%|████████▏ | 5532/6717 [18:51<04:02,  4.88it/s]

Processing tickers:  82%|████████▏ | 5533/6717 [18:51<04:01,  4.91it/s]

Processing tickers:  82%|████████▏ | 5534/6717 [18:51<03:59,  4.94it/s]

Processing tickers:  82%|████████▏ | 5535/6717 [18:51<03:59,  4.93it/s]

Processing tickers:  82%|████████▏ | 5536/6717 [18:51<04:01,  4.89it/s]

Processing tickers:  82%|████████▏ | 5537/6717 [18:52<03:59,  4.92it/s]

Processing tickers:  82%|████████▏ | 5538/6717 [18:52<04:02,  4.86it/s]

Processing tickers:  82%|████████▏ | 5539/6717 [18:52<04:06,  4.79it/s]

Processing tickers:  82%|████████▏ | 5540/6717 [18:52<04:04,  4.82it/s]

Processing tickers:  82%|████████▏ | 5541/6717 [18:52<04:03,  4.83it/s]

Processing tickers:  83%|████████▎ | 5542/6717 [18:53<04:02,  4.84it/s]

Processing tickers:  83%|████████▎ | 5543/6717 [18:53<04:00,  4.88it/s]

Processing tickers:  83%|████████▎ | 5544/6717 [18:53<03:59,  4.89it/s]

Processing tickers:  83%|████████▎ | 5545/6717 [18:53<03:58,  4.91it/s]

Processing tickers:  83%|████████▎ | 5546/6717 [18:53<04:00,  4.87it/s]

Processing tickers:  83%|████████▎ | 5547/6717 [18:54<04:01,  4.85it/s]

Processing tickers:  83%|████████▎ | 5548/6717 [18:54<04:00,  4.87it/s]

Processing tickers:  83%|████████▎ | 5549/6717 [18:54<03:59,  4.88it/s]

Processing tickers:  83%|████████▎ | 5550/6717 [18:54<03:57,  4.91it/s]

Processing tickers:  83%|████████▎ | 5551/6717 [18:54<03:57,  4.90it/s]

Processing tickers:  83%|████████▎ | 5552/6717 [18:55<03:57,  4.90it/s]

Processing tickers:  83%|████████▎ | 5553/6717 [18:55<03:54,  4.95it/s]

Processing tickers:  83%|████████▎ | 5554/6717 [18:55<03:54,  4.97it/s]

Processing tickers:  83%|████████▎ | 5555/6717 [18:55<03:55,  4.93it/s]

Processing tickers:  83%|████████▎ | 5556/6717 [18:55<03:56,  4.90it/s]

Processing tickers:  83%|████████▎ | 5557/6717 [18:56<03:57,  4.88it/s]

Processing tickers:  83%|████████▎ | 5558/6717 [18:56<03:55,  4.92it/s]

Processing tickers:  83%|████████▎ | 5559/6717 [18:56<03:54,  4.93it/s]

Processing tickers:  83%|████████▎ | 5560/6717 [18:56<04:01,  4.79it/s]

Processing tickers:  83%|████████▎ | 5561/6717 [18:57<04:01,  4.78it/s]

Processing tickers:  83%|████████▎ | 5562/6717 [18:57<03:58,  4.84it/s]

Processing tickers:  83%|████████▎ | 5563/6717 [18:57<03:55,  4.90it/s]

Processing tickers:  83%|████████▎ | 5564/6717 [18:57<03:53,  4.93it/s]

Processing tickers:  83%|████████▎ | 5565/6717 [18:57<03:52,  4.96it/s]

Processing tickers:  83%|████████▎ | 5566/6717 [18:58<03:51,  4.97it/s]

Processing tickers:  83%|████████▎ | 5567/6717 [18:58<03:55,  4.89it/s]

Processing tickers:  83%|████████▎ | 5568/6717 [18:58<03:54,  4.90it/s]

Processing tickers:  83%|████████▎ | 5569/6717 [18:58<03:54,  4.90it/s]

Processing tickers:  83%|████████▎ | 5570/6717 [18:58<03:55,  4.87it/s]

Processing tickers:  83%|████████▎ | 5571/6717 [18:59<03:54,  4.89it/s]

Processing tickers:  83%|████████▎ | 5572/6717 [18:59<03:57,  4.83it/s]

Processing tickers:  83%|████████▎ | 5573/6717 [18:59<03:54,  4.87it/s]

Processing tickers:  83%|████████▎ | 5574/6717 [18:59<03:53,  4.90it/s]

Processing tickers:  83%|████████▎ | 5575/6717 [18:59<03:56,  4.82it/s]

Processing tickers:  83%|████████▎ | 5576/6717 [19:00<03:57,  4.81it/s]

Processing tickers:  83%|████████▎ | 5577/6717 [19:00<04:00,  4.73it/s]

Processing tickers:  83%|████████▎ | 5578/6717 [19:00<04:01,  4.71it/s]

Processing tickers:  83%|████████▎ | 5579/6717 [19:00<03:57,  4.80it/s]

Processing tickers:  83%|████████▎ | 5580/6717 [19:00<03:59,  4.75it/s]

Processing tickers:  83%|████████▎ | 5581/6717 [19:01<03:55,  4.83it/s]

Processing tickers:  83%|████████▎ | 5582/6717 [19:01<03:52,  4.88it/s]

Processing tickers:  83%|████████▎ | 5583/6717 [19:01<03:53,  4.85it/s]

Processing tickers:  83%|████████▎ | 5584/6717 [19:01<03:55,  4.81it/s]

Processing tickers:  83%|████████▎ | 5585/6717 [19:01<03:53,  4.85it/s]

Processing tickers:  83%|████████▎ | 5586/6717 [19:02<03:52,  4.87it/s]

Processing tickers:  83%|████████▎ | 5587/6717 [19:02<03:50,  4.91it/s]

Processing tickers:  83%|████████▎ | 5588/6717 [19:02<03:48,  4.95it/s]

Processing tickers:  83%|████████▎ | 5589/6717 [19:02<03:47,  4.95it/s]

Processing tickers:  83%|████████▎ | 5590/6717 [19:02<03:46,  4.97it/s]

Processing tickers:  83%|████████▎ | 5591/6717 [19:03<03:52,  4.85it/s]

Processing tickers:  83%|████████▎ | 5592/6717 [19:03<03:49,  4.89it/s]

Processing tickers:  83%|████████▎ | 5593/6717 [19:03<03:47,  4.93it/s]

Processing tickers:  83%|████████▎ | 5594/6717 [19:03<03:47,  4.94it/s]

Processing tickers:  83%|████████▎ | 5595/6717 [19:03<03:46,  4.95it/s]

Processing tickers:  83%|████████▎ | 5596/6717 [19:04<03:47,  4.93it/s]

Processing tickers:  83%|████████▎ | 5597/6717 [19:04<03:46,  4.95it/s]

Processing tickers:  83%|████████▎ | 5598/6717 [19:04<03:48,  4.91it/s]

Processing tickers:  83%|████████▎ | 5599/6717 [19:04<03:50,  4.86it/s]

Processing tickers:  83%|████████▎ | 5600/6717 [19:04<03:48,  4.89it/s]

Processing tickers:  83%|████████▎ | 5601/6717 [19:05<03:47,  4.91it/s]

Processing tickers:  83%|████████▎ | 5602/6717 [19:05<03:46,  4.92it/s]

Processing tickers:  83%|████████▎ | 5603/6717 [19:05<03:45,  4.94it/s]

Processing tickers:  83%|████████▎ | 5604/6717 [19:05<03:44,  4.95it/s]

Processing tickers:  83%|████████▎ | 5605/6717 [19:06<03:43,  4.97it/s]

Processing tickers:  83%|████████▎ | 5606/6717 [19:06<03:42,  4.98it/s]

Processing tickers:  83%|████████▎ | 5607/6717 [19:06<03:45,  4.93it/s]

Processing tickers:  83%|████████▎ | 5608/6717 [19:06<03:45,  4.92it/s]

Processing tickers:  84%|████████▎ | 5609/6717 [19:06<03:47,  4.88it/s]

Processing tickers:  84%|████████▎ | 5610/6717 [19:07<03:45,  4.90it/s]

Processing tickers:  84%|████████▎ | 5611/6717 [19:07<03:45,  4.91it/s]

Processing tickers:  84%|████████▎ | 5612/6717 [19:07<03:43,  4.94it/s]

Processing tickers:  84%|████████▎ | 5613/6717 [19:07<03:45,  4.90it/s]

Processing tickers:  84%|████████▎ | 5614/6717 [19:07<03:43,  4.94it/s]

Processing tickers:  84%|████████▎ | 5615/6717 [19:08<03:43,  4.93it/s]

Processing tickers:  84%|████████▎ | 5616/6717 [19:08<03:43,  4.94it/s]

Processing tickers:  84%|████████▎ | 5617/6717 [19:08<03:43,  4.93it/s]

Processing tickers:  84%|████████▎ | 5618/6717 [19:08<03:42,  4.95it/s]

Processing tickers:  84%|████████▎ | 5619/6717 [19:08<03:42,  4.93it/s]

Processing tickers:  84%|████████▎ | 5620/6717 [19:09<03:42,  4.92it/s]

Processing tickers:  84%|████████▎ | 5621/6717 [19:09<03:43,  4.90it/s]

Processing tickers:  84%|████████▎ | 5622/6717 [19:09<03:42,  4.92it/s]

Processing tickers:  84%|████████▎ | 5623/6717 [19:09<03:42,  4.91it/s]

Processing tickers:  84%|████████▎ | 5624/6717 [19:09<03:45,  4.84it/s]

Processing tickers:  84%|████████▎ | 5625/6717 [19:10<03:45,  4.84it/s]

Processing tickers:  84%|████████▍ | 5626/6717 [19:10<03:43,  4.88it/s]

Processing tickers:  84%|████████▍ | 5627/6717 [19:10<03:48,  4.77it/s]

Processing tickers:  84%|████████▍ | 5628/6717 [19:10<03:45,  4.82it/s]

Processing tickers:  84%|████████▍ | 5629/6717 [19:10<03:44,  4.86it/s]

Processing tickers:  84%|████████▍ | 5630/6717 [19:11<03:44,  4.85it/s]

Processing tickers:  84%|████████▍ | 5631/6717 [19:11<03:42,  4.89it/s]

Processing tickers:  84%|████████▍ | 5632/6717 [19:11<03:40,  4.92it/s]

Processing tickers:  84%|████████▍ | 5633/6717 [19:11<03:39,  4.93it/s]

Processing tickers:  84%|████████▍ | 5634/6717 [19:11<03:45,  4.81it/s]

Processing tickers:  84%|████████▍ | 5635/6717 [19:12<03:42,  4.85it/s]

Processing tickers:  84%|████████▍ | 5636/6717 [19:12<03:40,  4.89it/s]

Processing tickers:  84%|████████▍ | 5637/6717 [19:12<03:39,  4.93it/s]

Processing tickers:  84%|████████▍ | 5638/6717 [19:12<03:38,  4.94it/s]

Processing tickers:  84%|████████▍ | 5639/6717 [19:12<03:38,  4.94it/s]

Processing tickers:  84%|████████▍ | 5640/6717 [19:13<03:37,  4.96it/s]

Processing tickers:  84%|████████▍ | 5641/6717 [19:13<03:36,  4.97it/s]

Processing tickers:  84%|████████▍ | 5642/6717 [19:13<03:39,  4.91it/s]

Processing tickers:  84%|████████▍ | 5643/6717 [19:13<03:45,  4.77it/s]

Processing tickers:  84%|████████▍ | 5644/6717 [19:13<03:42,  4.81it/s]

Processing tickers:  84%|████████▍ | 5645/6717 [19:14<03:41,  4.84it/s]

Processing tickers:  84%|████████▍ | 5646/6717 [19:14<03:41,  4.84it/s]

Processing tickers:  84%|████████▍ | 5647/6717 [19:14<03:39,  4.87it/s]

Processing tickers:  84%|████████▍ | 5648/6717 [19:14<03:37,  4.90it/s]

Processing tickers:  84%|████████▍ | 5649/6717 [19:15<03:38,  4.89it/s]

Processing tickers:  84%|████████▍ | 5650/6717 [19:15<03:36,  4.92it/s]

Processing tickers:  84%|████████▍ | 5651/6717 [19:15<03:36,  4.93it/s]

Processing tickers:  84%|████████▍ | 5652/6717 [19:15<03:36,  4.93it/s]

Processing tickers:  84%|████████▍ | 5653/6717 [19:15<03:35,  4.94it/s]

Processing tickers:  84%|████████▍ | 5654/6717 [19:16<03:35,  4.93it/s]

Processing tickers:  84%|████████▍ | 5655/6717 [19:16<03:34,  4.94it/s]

Processing tickers:  84%|████████▍ | 5656/6717 [19:16<03:34,  4.95it/s]

Processing tickers:  84%|████████▍ | 5657/6717 [19:16<03:34,  4.94it/s]

Processing tickers:  84%|████████▍ | 5658/6717 [19:16<03:34,  4.95it/s]

Processing tickers:  84%|████████▍ | 5659/6717 [19:17<03:34,  4.93it/s]

Processing tickers:  84%|████████▍ | 5660/6717 [19:17<03:34,  4.93it/s]

Processing tickers:  84%|████████▍ | 5661/6717 [19:17<03:34,  4.92it/s]

Processing tickers:  84%|████████▍ | 5662/6717 [19:17<03:35,  4.89it/s]

Processing tickers:  84%|████████▍ | 5663/6717 [19:17<03:35,  4.89it/s]

Processing tickers:  84%|████████▍ | 5664/6717 [19:18<03:36,  4.86it/s]

Processing tickers:  84%|████████▍ | 5665/6717 [19:18<03:35,  4.88it/s]

Processing tickers:  84%|████████▍ | 5666/6717 [19:18<03:33,  4.91it/s]

Processing tickers:  84%|████████▍ | 5667/6717 [19:18<03:33,  4.91it/s]

Processing tickers:  84%|████████▍ | 5668/6717 [19:18<03:33,  4.91it/s]

Processing tickers:  84%|████████▍ | 5669/6717 [19:19<03:34,  4.88it/s]

Processing tickers:  84%|████████▍ | 5670/6717 [19:19<03:33,  4.90it/s]

Processing tickers:  84%|████████▍ | 5671/6717 [19:19<03:39,  4.77it/s]

Processing tickers:  84%|████████▍ | 5672/6717 [19:19<03:39,  4.76it/s]

Processing tickers:  84%|████████▍ | 5673/6717 [19:19<03:36,  4.82it/s]

Processing tickers:  84%|████████▍ | 5674/6717 [19:20<03:33,  4.88it/s]

Processing tickers:  84%|████████▍ | 5675/6717 [19:20<03:31,  4.92it/s]

Processing tickers:  85%|████████▍ | 5676/6717 [19:20<03:34,  4.85it/s]

Processing tickers:  85%|████████▍ | 5677/6717 [19:20<03:33,  4.88it/s]

Processing tickers:  85%|████████▍ | 5678/6717 [19:20<03:31,  4.91it/s]

Processing tickers:  85%|████████▍ | 5679/6717 [19:21<03:39,  4.74it/s]

Processing tickers:  85%|████████▍ | 5680/6717 [19:21<03:39,  4.71it/s]

Processing tickers:  85%|████████▍ | 5681/6717 [19:21<03:38,  4.75it/s]

Processing tickers:  85%|████████▍ | 5682/6717 [19:21<03:34,  4.83it/s]

Processing tickers:  85%|████████▍ | 5683/6717 [19:21<03:32,  4.86it/s]

Processing tickers:  85%|████████▍ | 5684/6717 [19:22<03:31,  4.88it/s]

Processing tickers:  85%|████████▍ | 5685/6717 [19:22<03:31,  4.89it/s]

Processing tickers:  85%|████████▍ | 5686/6717 [19:22<03:30,  4.89it/s]

Processing tickers:  85%|████████▍ | 5687/6717 [19:22<03:32,  4.84it/s]

Processing tickers:  85%|████████▍ | 5688/6717 [19:23<03:32,  4.84it/s]

Processing tickers:  85%|████████▍ | 5689/6717 [19:23<03:33,  4.81it/s]

Processing tickers:  85%|████████▍ | 5690/6717 [19:23<03:30,  4.88it/s]

Processing tickers:  85%|████████▍ | 5691/6717 [19:23<03:30,  4.87it/s]

Processing tickers:  85%|████████▍ | 5692/6717 [19:23<03:30,  4.88it/s]

Processing tickers:  85%|████████▍ | 5693/6717 [19:24<03:28,  4.92it/s]

Processing tickers:  85%|████████▍ | 5694/6717 [19:24<03:27,  4.92it/s]

Processing tickers:  85%|████████▍ | 5695/6717 [19:24<03:27,  4.92it/s]

Processing tickers:  85%|████████▍ | 5696/6717 [19:24<03:31,  4.82it/s]

Processing tickers:  85%|████████▍ | 5697/6717 [19:24<03:31,  4.81it/s]

Processing tickers:  85%|████████▍ | 5698/6717 [19:25<03:29,  4.86it/s]

Processing tickers:  85%|████████▍ | 5699/6717 [19:25<03:28,  4.89it/s]

Processing tickers:  85%|████████▍ | 5700/6717 [19:25<03:28,  4.87it/s]

Processing tickers:  85%|████████▍ | 5701/6717 [19:25<03:28,  4.88it/s]

Processing tickers:  85%|████████▍ | 5702/6717 [19:25<03:30,  4.82it/s]

Processing tickers:  85%|████████▍ | 5703/6717 [19:26<03:28,  4.87it/s]

Processing tickers:  85%|████████▍ | 5704/6717 [19:26<03:27,  4.89it/s]

Processing tickers:  85%|████████▍ | 5705/6717 [19:26<03:30,  4.81it/s]

Processing tickers:  85%|████████▍ | 5706/6717 [19:26<03:28,  4.84it/s]

Processing tickers:  85%|████████▍ | 5707/6717 [19:26<03:30,  4.80it/s]

Processing tickers:  85%|████████▍ | 5708/6717 [19:27<03:27,  4.85it/s]

Processing tickers:  85%|████████▍ | 5709/6717 [19:27<03:27,  4.85it/s]

Processing tickers:  85%|████████▌ | 5710/6717 [19:27<03:27,  4.85it/s]

Processing tickers:  85%|████████▌ | 5711/6717 [19:27<03:25,  4.89it/s]

Processing tickers:  85%|████████▌ | 5712/6717 [19:27<03:26,  4.86it/s]

Processing tickers:  85%|████████▌ | 5713/6717 [19:28<03:25,  4.89it/s]

Processing tickers:  85%|████████▌ | 5714/6717 [19:28<03:25,  4.87it/s]

Processing tickers:  85%|████████▌ | 5715/6717 [19:28<03:24,  4.91it/s]

Processing tickers:  85%|████████▌ | 5716/6717 [19:28<03:32,  4.72it/s]

Processing tickers:  85%|████████▌ | 5717/6717 [19:28<03:29,  4.78it/s]

Processing tickers:  85%|████████▌ | 5718/6717 [19:29<03:26,  4.83it/s]

Processing tickers:  85%|████████▌ | 5719/6717 [19:29<03:24,  4.89it/s]

Processing tickers:  85%|████████▌ | 5720/6717 [19:29<03:23,  4.90it/s]

Processing tickers:  85%|████████▌ | 5721/6717 [19:29<03:22,  4.91it/s]

Processing tickers:  85%|████████▌ | 5722/6717 [19:29<03:23,  4.88it/s]

Processing tickers:  85%|████████▌ | 5723/6717 [19:30<03:23,  4.89it/s]

Processing tickers:  85%|████████▌ | 5724/6717 [19:30<03:22,  4.91it/s]

Processing tickers:  85%|████████▌ | 5725/6717 [19:30<03:21,  4.92it/s]

Processing tickers:  85%|████████▌ | 5726/6717 [19:30<03:28,  4.76it/s]

Processing tickers:  85%|████████▌ | 5727/6717 [19:31<03:25,  4.82it/s]

Processing tickers:  85%|████████▌ | 5728/6717 [19:31<03:23,  4.87it/s]

Processing tickers:  85%|████████▌ | 5729/6717 [19:31<03:24,  4.84it/s]

Processing tickers:  85%|████████▌ | 5730/6717 [19:31<03:23,  4.85it/s]

Processing tickers:  85%|████████▌ | 5731/6717 [19:31<03:22,  4.88it/s]

Processing tickers:  85%|████████▌ | 5732/6717 [19:32<03:20,  4.92it/s]

Processing tickers:  85%|████████▌ | 5733/6717 [19:32<03:18,  4.95it/s]

Processing tickers:  85%|████████▌ | 5734/6717 [19:32<03:18,  4.94it/s]

Processing tickers:  85%|████████▌ | 5735/6717 [19:32<03:19,  4.92it/s]

Processing tickers:  85%|████████▌ | 5736/6717 [19:32<03:24,  4.79it/s]

Processing tickers:  85%|████████▌ | 5737/6717 [19:33<03:23,  4.82it/s]

Processing tickers:  85%|████████▌ | 5738/6717 [19:33<03:22,  4.84it/s]

Processing tickers:  85%|████████▌ | 5739/6717 [19:33<03:24,  4.79it/s]

Processing tickers:  85%|████████▌ | 5740/6717 [19:33<03:23,  4.81it/s]

Processing tickers:  85%|████████▌ | 5741/6717 [19:33<03:22,  4.83it/s]

Processing tickers:  85%|████████▌ | 5742/6717 [19:34<03:20,  4.87it/s]

Processing tickers:  85%|████████▌ | 5743/6717 [19:34<03:18,  4.91it/s]

Processing tickers:  86%|████████▌ | 5744/6717 [19:34<03:21,  4.84it/s]

Processing tickers:  86%|████████▌ | 5745/6717 [19:34<03:19,  4.87it/s]

Processing tickers:  86%|████████▌ | 5746/6717 [19:34<03:19,  4.88it/s]

Processing tickers:  86%|████████▌ | 5747/6717 [19:35<03:17,  4.91it/s]

Processing tickers:  86%|████████▌ | 5748/6717 [19:35<03:22,  4.78it/s]

Processing tickers:  86%|████████▌ | 5749/6717 [19:35<03:20,  4.83it/s]

Processing tickers:  86%|████████▌ | 5750/6717 [19:35<03:19,  4.84it/s]

Processing tickers:  86%|████████▌ | 5751/6717 [19:35<03:17,  4.89it/s]

Processing tickers:  86%|████████▌ | 5752/6717 [19:36<03:19,  4.85it/s]

Processing tickers:  86%|████████▌ | 5753/6717 [19:36<03:17,  4.89it/s]

Processing tickers:  86%|████████▌ | 5754/6717 [19:36<03:20,  4.81it/s]

Processing tickers:  86%|████████▌ | 5755/6717 [19:36<03:19,  4.82it/s]

Processing tickers:  86%|████████▌ | 5756/6717 [19:36<03:17,  4.87it/s]

Processing tickers:  86%|████████▌ | 5757/6717 [19:37<03:16,  4.89it/s]

Processing tickers:  86%|████████▌ | 5758/6717 [19:37<03:18,  4.84it/s]

Processing tickers:  86%|████████▌ | 5759/6717 [19:37<03:15,  4.90it/s]

Processing tickers:  86%|████████▌ | 5760/6717 [19:37<03:17,  4.85it/s]

Processing tickers:  86%|████████▌ | 5761/6717 [19:38<03:15,  4.89it/s]

Processing tickers:  86%|████████▌ | 5762/6717 [19:38<03:13,  4.94it/s]

Processing tickers:  86%|████████▌ | 5763/6717 [19:38<03:13,  4.93it/s]

Processing tickers:  86%|████████▌ | 5764/6717 [19:38<03:13,  4.94it/s]

Processing tickers:  86%|████████▌ | 5765/6717 [19:38<03:12,  4.94it/s]

Processing tickers:  86%|████████▌ | 5766/6717 [19:39<03:13,  4.91it/s]

Processing tickers:  86%|████████▌ | 5767/6717 [19:39<03:14,  4.89it/s]

Processing tickers:  86%|████████▌ | 5768/6717 [19:39<03:13,  4.92it/s]

Processing tickers:  86%|████████▌ | 5769/6717 [19:39<03:12,  4.94it/s]

Processing tickers:  86%|████████▌ | 5770/6717 [19:39<03:11,  4.94it/s]

Processing tickers:  86%|████████▌ | 5771/6717 [19:40<03:11,  4.93it/s]

Processing tickers:  86%|████████▌ | 5772/6717 [19:40<03:14,  4.87it/s]

Processing tickers:  86%|████████▌ | 5773/6717 [19:40<03:14,  4.84it/s]

Processing tickers:  86%|████████▌ | 5774/6717 [19:40<03:12,  4.89it/s]

Processing tickers:  86%|████████▌ | 5775/6717 [19:40<03:12,  4.90it/s]

Processing tickers:  86%|████████▌ | 5776/6717 [19:41<03:11,  4.90it/s]

Processing tickers:  86%|████████▌ | 5777/6717 [19:41<03:10,  4.93it/s]

Processing tickers:  86%|████████▌ | 5778/6717 [19:41<03:17,  4.74it/s]

Processing tickers:  86%|████████▌ | 5779/6717 [19:41<03:19,  4.71it/s]

Processing tickers:  86%|████████▌ | 5780/6717 [19:41<03:16,  4.77it/s]

Processing tickers:  86%|████████▌ | 5781/6717 [19:42<03:13,  4.85it/s]

Processing tickers:  86%|████████▌ | 5782/6717 [19:42<03:11,  4.89it/s]

Processing tickers:  86%|████████▌ | 5783/6717 [19:42<03:10,  4.91it/s]

Processing tickers:  86%|████████▌ | 5784/6717 [19:42<03:09,  4.93it/s]

Processing tickers:  86%|████████▌ | 5785/6717 [19:42<03:09,  4.93it/s]

Processing tickers:  86%|████████▌ | 5786/6717 [19:43<03:09,  4.90it/s]

Processing tickers:  86%|████████▌ | 5787/6717 [19:43<03:09,  4.91it/s]

Processing tickers:  86%|████████▌ | 5788/6717 [19:43<03:08,  4.92it/s]

Processing tickers:  86%|████████▌ | 5789/6717 [19:43<03:07,  4.95it/s]

Processing tickers:  86%|████████▌ | 5790/6717 [19:43<03:10,  4.86it/s]

Processing tickers:  86%|████████▌ | 5791/6717 [19:44<03:10,  4.87it/s]

Processing tickers:  86%|████████▌ | 5792/6717 [19:44<03:09,  4.88it/s]

Processing tickers:  86%|████████▌ | 5793/6717 [19:44<03:08,  4.91it/s]

Processing tickers:  86%|████████▋ | 5794/6717 [19:44<03:09,  4.87it/s]

Processing tickers:  86%|████████▋ | 5795/6717 [19:44<03:09,  4.86it/s]

Processing tickers:  86%|████████▋ | 5796/6717 [19:45<03:09,  4.87it/s]

Processing tickers:  86%|████████▋ | 5797/6717 [19:45<03:07,  4.91it/s]

Processing tickers:  86%|████████▋ | 5798/6717 [19:45<03:06,  4.93it/s]

Processing tickers:  86%|████████▋ | 5799/6717 [19:45<03:05,  4.95it/s]

Processing tickers:  86%|████████▋ | 5800/6717 [19:45<03:05,  4.93it/s]

Processing tickers:  86%|████████▋ | 5801/6717 [19:46<03:05,  4.94it/s]

Processing tickers:  86%|████████▋ | 5802/6717 [19:46<03:06,  4.89it/s]

Processing tickers:  86%|████████▋ | 5803/6717 [19:46<03:06,  4.91it/s]

Processing tickers:  86%|████████▋ | 5804/6717 [19:46<03:05,  4.92it/s]

Processing tickers:  86%|████████▋ | 5805/6717 [19:47<03:06,  4.88it/s]

Processing tickers:  86%|████████▋ | 5806/6717 [19:47<03:05,  4.91it/s]

Processing tickers:  86%|████████▋ | 5807/6717 [19:47<03:04,  4.93it/s]

Processing tickers:  86%|████████▋ | 5808/6717 [19:47<03:02,  4.97it/s]

Processing tickers:  86%|████████▋ | 5809/6717 [19:47<03:02,  4.96it/s]

Processing tickers:  86%|████████▋ | 5810/6717 [19:48<03:03,  4.94it/s]

Processing tickers:  87%|████████▋ | 5811/6717 [19:48<03:02,  4.97it/s]

Processing tickers:  87%|████████▋ | 5812/6717 [19:48<03:03,  4.92it/s]

Processing tickers:  87%|████████▋ | 5813/6717 [19:48<03:07,  4.81it/s]

Processing tickers:  87%|████████▋ | 5814/6717 [19:48<03:05,  4.88it/s]

Processing tickers:  87%|████████▋ | 5815/6717 [19:49<03:04,  4.89it/s]

Processing tickers:  87%|████████▋ | 5816/6717 [19:49<03:04,  4.88it/s]

Processing tickers:  87%|████████▋ | 5817/6717 [19:49<03:03,  4.90it/s]

Processing tickers:  87%|████████▋ | 5818/6717 [19:49<03:03,  4.91it/s]

Processing tickers:  87%|████████▋ | 5819/6717 [19:49<03:05,  4.83it/s]

Processing tickers:  87%|████████▋ | 5820/6717 [19:50<03:03,  4.89it/s]

Processing tickers:  87%|████████▋ | 5821/6717 [19:50<03:03,  4.90it/s]

Processing tickers:  87%|████████▋ | 5822/6717 [19:50<03:02,  4.89it/s]

Processing tickers:  87%|████████▋ | 5823/6717 [19:50<03:02,  4.91it/s]

Processing tickers:  87%|████████▋ | 5824/6717 [19:50<03:06,  4.79it/s]

Processing tickers:  87%|████████▋ | 5825/6717 [19:51<03:07,  4.76it/s]

Processing tickers:  87%|████████▋ | 5826/6717 [19:51<03:08,  4.73it/s]

Processing tickers:  87%|████████▋ | 5827/6717 [19:51<03:08,  4.72it/s]

Processing tickers:  87%|████████▋ | 5828/6717 [19:51<03:06,  4.77it/s]

Processing tickers:  87%|████████▋ | 5829/6717 [19:51<03:03,  4.84it/s]

Processing tickers:  87%|████████▋ | 5830/6717 [19:52<03:01,  4.88it/s]

Processing tickers:  87%|████████▋ | 5831/6717 [19:52<02:59,  4.95it/s]

Processing tickers:  87%|████████▋ | 5832/6717 [19:52<02:58,  4.97it/s]

Processing tickers:  87%|████████▋ | 5833/6717 [19:52<02:57,  4.99it/s]

Processing tickers:  87%|████████▋ | 5834/6717 [19:52<02:57,  4.97it/s]

Processing tickers:  87%|████████▋ | 5835/6717 [19:53<02:55,  5.02it/s]

Processing tickers:  87%|████████▋ | 5836/6717 [19:53<02:55,  5.01it/s]

Processing tickers:  87%|████████▋ | 5837/6717 [19:53<02:57,  4.97it/s]

Processing tickers:  87%|████████▋ | 5838/6717 [19:53<02:56,  4.98it/s]

Processing tickers:  87%|████████▋ | 5839/6717 [19:53<02:56,  4.98it/s]

Processing tickers:  87%|████████▋ | 5840/6717 [19:54<02:59,  4.89it/s]

Processing tickers:  87%|████████▋ | 5841/6717 [19:54<02:58,  4.90it/s]

Processing tickers:  87%|████████▋ | 5842/6717 [19:54<02:58,  4.90it/s]

Processing tickers:  87%|████████▋ | 5843/6717 [19:54<02:57,  4.93it/s]

Processing tickers:  87%|████████▋ | 5844/6717 [19:54<02:57,  4.93it/s]

Processing tickers:  87%|████████▋ | 5845/6717 [19:55<02:56,  4.94it/s]

Processing tickers:  87%|████████▋ | 5846/6717 [19:55<02:56,  4.93it/s]

Processing tickers:  87%|████████▋ | 5847/6717 [19:55<02:57,  4.89it/s]

Processing tickers:  87%|████████▋ | 5848/6717 [19:55<02:57,  4.90it/s]

Processing tickers:  87%|████████▋ | 5849/6717 [19:55<02:56,  4.91it/s]

Processing tickers:  87%|████████▋ | 5850/6717 [19:56<02:58,  4.86it/s]

Processing tickers:  87%|████████▋ | 5851/6717 [19:56<03:01,  4.76it/s]

Processing tickers:  87%|████████▋ | 5852/6717 [19:56<02:59,  4.81it/s]

Processing tickers:  87%|████████▋ | 5853/6717 [19:56<02:59,  4.82it/s]

Processing tickers:  87%|████████▋ | 5854/6717 [19:57<02:58,  4.82it/s]

Processing tickers:  87%|████████▋ | 5855/6717 [19:57<02:55,  4.90it/s]

Processing tickers:  87%|████████▋ | 5856/6717 [19:57<02:54,  4.93it/s]

Processing tickers:  87%|████████▋ | 5857/6717 [19:57<02:54,  4.94it/s]

Processing tickers:  87%|████████▋ | 5858/6717 [19:57<02:53,  4.95it/s]

Processing tickers:  87%|████████▋ | 5859/6717 [19:58<02:54,  4.92it/s]

Processing tickers:  87%|████████▋ | 5860/6717 [19:58<02:54,  4.90it/s]

Processing tickers:  87%|████████▋ | 5861/6717 [19:58<02:53,  4.95it/s]

Processing tickers:  87%|████████▋ | 5862/6717 [19:58<02:53,  4.94it/s]

Processing tickers:  87%|████████▋ | 5863/6717 [19:58<02:54,  4.91it/s]

Processing tickers:  87%|████████▋ | 5864/6717 [19:59<02:53,  4.92it/s]

Processing tickers:  87%|████████▋ | 5865/6717 [19:59<02:53,  4.92it/s]

Processing tickers:  87%|████████▋ | 5866/6717 [19:59<02:53,  4.92it/s]

Processing tickers:  87%|████████▋ | 5867/6717 [19:59<02:53,  4.89it/s]

Processing tickers:  87%|████████▋ | 5868/6717 [19:59<02:53,  4.88it/s]

Processing tickers:  87%|████████▋ | 5869/6717 [20:00<02:56,  4.80it/s]

Processing tickers:  87%|████████▋ | 5870/6717 [20:00<02:55,  4.82it/s]

Processing tickers:  87%|████████▋ | 5871/6717 [20:00<02:56,  4.79it/s]

Processing tickers:  87%|████████▋ | 5872/6717 [20:00<02:54,  4.83it/s]

Processing tickers:  87%|████████▋ | 5873/6717 [20:00<02:54,  4.85it/s]

Processing tickers:  87%|████████▋ | 5874/6717 [20:01<02:53,  4.86it/s]

Processing tickers:  87%|████████▋ | 5875/6717 [20:01<02:52,  4.90it/s]

Processing tickers:  87%|████████▋ | 5876/6717 [20:01<02:50,  4.92it/s]

Processing tickers:  87%|████████▋ | 5877/6717 [20:01<02:50,  4.93it/s]

Processing tickers:  88%|████████▊ | 5878/6717 [20:01<02:49,  4.95it/s]

Processing tickers:  88%|████████▊ | 5879/6717 [20:02<02:48,  4.97it/s]

Processing tickers:  88%|████████▊ | 5880/6717 [20:02<02:47,  4.98it/s]

Processing tickers:  88%|████████▊ | 5881/6717 [20:02<02:48,  4.95it/s]

Processing tickers:  88%|████████▊ | 5882/6717 [20:02<02:48,  4.94it/s]

Processing tickers:  88%|████████▊ | 5883/6717 [20:02<02:48,  4.96it/s]

Processing tickers:  88%|████████▊ | 5884/6717 [20:03<02:48,  4.96it/s]

Processing tickers:  88%|████████▊ | 5885/6717 [20:03<02:47,  4.97it/s]

Processing tickers:  88%|████████▊ | 5886/6717 [20:03<02:46,  4.98it/s]

Processing tickers:  88%|████████▊ | 5887/6717 [20:03<02:46,  4.97it/s]

Processing tickers:  88%|████████▊ | 5888/6717 [20:03<02:49,  4.88it/s]

Processing tickers:  88%|████████▊ | 5889/6717 [20:04<02:48,  4.91it/s]

Processing tickers:  88%|████████▊ | 5890/6717 [20:04<02:48,  4.91it/s]

Processing tickers:  88%|████████▊ | 5891/6717 [20:04<02:47,  4.93it/s]

Processing tickers:  88%|████████▊ | 5892/6717 [20:04<02:48,  4.91it/s]

Processing tickers:  88%|████████▊ | 5893/6717 [20:04<02:47,  4.92it/s]

Processing tickers:  88%|████████▊ | 5894/6717 [20:05<02:46,  4.93it/s]

Processing tickers:  88%|████████▊ | 5895/6717 [20:05<02:45,  4.96it/s]

Processing tickers:  88%|████████▊ | 5896/6717 [20:05<02:45,  4.97it/s]

Processing tickers:  88%|████████▊ | 5897/6717 [20:05<02:45,  4.97it/s]

Processing tickers:  88%|████████▊ | 5898/6717 [20:05<02:47,  4.90it/s]

Processing tickers:  88%|████████▊ | 5899/6717 [20:06<02:47,  4.88it/s]

Processing tickers:  88%|████████▊ | 5900/6717 [20:06<02:49,  4.83it/s]

Processing tickers:  88%|████████▊ | 5901/6717 [20:06<02:47,  4.87it/s]

Processing tickers:  88%|████████▊ | 5902/6717 [20:06<02:48,  4.85it/s]

Processing tickers:  88%|████████▊ | 5903/6717 [20:06<02:46,  4.90it/s]

Processing tickers:  88%|████████▊ | 5904/6717 [20:07<02:45,  4.90it/s]

Processing tickers:  88%|████████▊ | 5905/6717 [20:07<02:45,  4.90it/s]

Processing tickers:  88%|████████▊ | 5906/6717 [20:07<02:45,  4.89it/s]

Processing tickers:  88%|████████▊ | 5907/6717 [20:07<02:44,  4.92it/s]

Processing tickers:  88%|████████▊ | 5908/6717 [20:08<02:44,  4.93it/s]

Processing tickers:  88%|████████▊ | 5909/6717 [20:08<02:43,  4.93it/s]

Processing tickers:  88%|████████▊ | 5910/6717 [20:08<02:43,  4.95it/s]

Processing tickers:  88%|████████▊ | 5911/6717 [20:08<02:44,  4.91it/s]

Processing tickers:  88%|████████▊ | 5912/6717 [20:08<02:44,  4.91it/s]

Processing tickers:  88%|████████▊ | 5913/6717 [20:09<02:43,  4.93it/s]

Processing tickers:  88%|████████▊ | 5914/6717 [20:09<02:42,  4.93it/s]

Processing tickers:  88%|████████▊ | 5915/6717 [20:09<02:49,  4.74it/s]

Processing tickers:  88%|████████▊ | 5916/6717 [20:09<02:46,  4.81it/s]

Processing tickers:  88%|████████▊ | 5917/6717 [20:09<02:45,  4.82it/s]

Processing tickers:  88%|████████▊ | 5918/6717 [20:10<02:43,  4.88it/s]

Processing tickers:  88%|████████▊ | 5919/6717 [20:10<02:45,  4.84it/s]

Processing tickers:  88%|████████▊ | 5920/6717 [20:10<02:43,  4.86it/s]

Processing tickers:  88%|████████▊ | 5921/6717 [20:10<02:42,  4.89it/s]

Processing tickers:  88%|████████▊ | 5922/6717 [20:10<02:43,  4.88it/s]

Processing tickers:  88%|████████▊ | 5923/6717 [20:11<02:41,  4.90it/s]

Processing tickers:  88%|████████▊ | 5924/6717 [20:11<02:42,  4.89it/s]

Processing tickers:  88%|████████▊ | 5925/6717 [20:11<02:43,  4.84it/s]

Processing tickers:  88%|████████▊ | 5926/6717 [20:11<02:43,  4.85it/s]

Processing tickers:  88%|████████▊ | 5927/6717 [20:11<02:43,  4.83it/s]

Processing tickers:  88%|████████▊ | 5928/6717 [20:12<02:41,  4.90it/s]

Processing tickers:  88%|████████▊ | 5929/6717 [20:12<02:40,  4.90it/s]

Processing tickers:  88%|████████▊ | 5930/6717 [20:12<02:41,  4.87it/s]

Processing tickers:  88%|████████▊ | 5931/6717 [20:12<02:40,  4.90it/s]

Processing tickers:  88%|████████▊ | 5932/6717 [20:12<02:42,  4.83it/s]

Processing tickers:  88%|████████▊ | 5933/6717 [20:13<02:40,  4.89it/s]

Processing tickers:  88%|████████▊ | 5934/6717 [20:13<02:41,  4.84it/s]

Processing tickers:  88%|████████▊ | 5935/6717 [20:13<02:41,  4.86it/s]

Processing tickers:  88%|████████▊ | 5936/6717 [20:13<02:39,  4.89it/s]

Processing tickers:  88%|████████▊ | 5937/6717 [20:13<02:39,  4.89it/s]

Processing tickers:  88%|████████▊ | 5938/6717 [20:14<02:38,  4.91it/s]

Processing tickers:  88%|████████▊ | 5939/6717 [20:14<02:38,  4.91it/s]

Processing tickers:  88%|████████▊ | 5940/6717 [20:14<02:38,  4.91it/s]

Processing tickers:  88%|████████▊ | 5941/6717 [20:14<02:37,  4.92it/s]

Processing tickers:  88%|████████▊ | 5942/6717 [20:14<02:37,  4.91it/s]

Processing tickers:  88%|████████▊ | 5943/6717 [20:15<02:36,  4.94it/s]

Processing tickers:  88%|████████▊ | 5944/6717 [20:15<02:35,  4.98it/s]

Processing tickers:  89%|████████▊ | 5945/6717 [20:15<02:38,  4.86it/s]

Processing tickers:  89%|████████▊ | 5946/6717 [20:15<02:37,  4.89it/s]

Processing tickers:  89%|████████▊ | 5947/6717 [20:15<02:36,  4.93it/s]

Processing tickers:  89%|████████▊ | 5948/6717 [20:16<02:35,  4.94it/s]

Processing tickers:  89%|████████▊ | 5949/6717 [20:16<02:37,  4.89it/s]

Processing tickers:  89%|████████▊ | 5950/6717 [20:16<02:36,  4.90it/s]

Processing tickers:  89%|████████▊ | 5951/6717 [20:16<02:35,  4.92it/s]

Processing tickers:  89%|████████▊ | 5952/6717 [20:17<02:34,  4.96it/s]

Processing tickers:  89%|████████▊ | 5953/6717 [20:17<02:35,  4.90it/s]

Processing tickers:  89%|████████▊ | 5954/6717 [20:17<02:35,  4.91it/s]

Processing tickers:  89%|████████▊ | 5955/6717 [20:17<02:34,  4.92it/s]

Processing tickers:  89%|████████▊ | 5956/6717 [20:17<02:35,  4.91it/s]

Processing tickers:  89%|████████▊ | 5957/6717 [20:18<02:33,  4.94it/s]

Processing tickers:  89%|████████▊ | 5958/6717 [20:18<02:34,  4.91it/s]

Processing tickers:  89%|████████▊ | 5959/6717 [20:18<02:34,  4.90it/s]

Processing tickers:  89%|████████▊ | 5960/6717 [20:18<02:33,  4.92it/s]

Processing tickers:  89%|████████▊ | 5961/6717 [20:18<02:33,  4.92it/s]

Processing tickers:  89%|████████▉ | 5962/6717 [20:19<02:32,  4.95it/s]

Processing tickers:  89%|████████▉ | 5963/6717 [20:19<02:32,  4.93it/s]

Processing tickers:  89%|████████▉ | 5964/6717 [20:19<02:32,  4.92it/s]

Processing tickers:  89%|████████▉ | 5965/6717 [20:19<02:33,  4.90it/s]

Processing tickers:  89%|████████▉ | 5966/6717 [20:19<02:33,  4.90it/s]

Processing tickers:  89%|████████▉ | 5967/6717 [20:20<02:32,  4.91it/s]

Processing tickers:  89%|████████▉ | 5968/6717 [20:20<02:33,  4.87it/s]

Processing tickers:  89%|████████▉ | 5969/6717 [20:20<02:32,  4.91it/s]

Processing tickers:  89%|████████▉ | 5970/6717 [20:20<02:32,  4.91it/s]

Processing tickers:  89%|████████▉ | 5971/6717 [20:20<02:31,  4.93it/s]

Processing tickers:  89%|████████▉ | 5972/6717 [20:21<02:30,  4.96it/s]

Processing tickers:  89%|████████▉ | 5973/6717 [20:21<02:32,  4.88it/s]

Processing tickers:  89%|████████▉ | 5974/6717 [20:21<02:34,  4.81it/s]

Processing tickers:  89%|████████▉ | 5975/6717 [20:21<02:33,  4.85it/s]

Processing tickers:  89%|████████▉ | 5976/6717 [20:21<02:31,  4.89it/s]

Processing tickers:  89%|████████▉ | 5977/6717 [20:22<02:30,  4.92it/s]

Processing tickers:  89%|████████▉ | 5978/6717 [20:22<02:29,  4.93it/s]

Processing tickers:  89%|████████▉ | 5979/6717 [20:22<02:30,  4.89it/s]

Processing tickers:  89%|████████▉ | 5980/6717 [20:22<02:29,  4.91it/s]

Processing tickers:  89%|████████▉ | 5981/6717 [20:22<02:29,  4.92it/s]

Processing tickers:  89%|████████▉ | 5982/6717 [20:23<02:28,  4.94it/s]

Processing tickers:  89%|████████▉ | 5983/6717 [20:23<02:28,  4.96it/s]

Processing tickers:  89%|████████▉ | 5984/6717 [20:23<02:28,  4.95it/s]

Processing tickers:  89%|████████▉ | 5985/6717 [20:23<02:27,  4.95it/s]

Processing tickers:  89%|████████▉ | 5986/6717 [20:23<02:27,  4.94it/s]

Processing tickers:  89%|████████▉ | 5987/6717 [20:24<02:27,  4.95it/s]

Processing tickers:  89%|████████▉ | 5988/6717 [20:24<02:26,  4.99it/s]

Processing tickers:  89%|████████▉ | 5989/6717 [20:24<02:27,  4.94it/s]

Processing tickers:  89%|████████▉ | 5990/6717 [20:24<02:29,  4.86it/s]

Processing tickers:  89%|████████▉ | 5991/6717 [20:24<02:28,  4.89it/s]

Processing tickers:  89%|████████▉ | 5992/6717 [20:25<02:27,  4.92it/s]

Processing tickers:  89%|████████▉ | 5993/6717 [20:25<02:26,  4.94it/s]

Processing tickers:  89%|████████▉ | 5994/6717 [20:25<02:26,  4.93it/s]

Processing tickers:  89%|████████▉ | 5995/6717 [20:25<02:28,  4.86it/s]

Processing tickers:  89%|████████▉ | 5996/6717 [20:25<02:27,  4.90it/s]

Processing tickers:  89%|████████▉ | 5997/6717 [20:26<02:26,  4.91it/s]

Processing tickers:  89%|████████▉ | 5998/6717 [20:26<02:25,  4.93it/s]

Processing tickers:  89%|████████▉ | 5999/6717 [20:26<02:25,  4.94it/s]

Processing tickers:  89%|████████▉ | 6000/6717 [20:26<02:27,  4.86it/s]

Processing tickers:  89%|████████▉ | 6001/6717 [20:26<02:26,  4.87it/s]

Processing tickers:  89%|████████▉ | 6002/6717 [20:27<02:27,  4.86it/s]

Processing tickers:  89%|████████▉ | 6003/6717 [20:27<02:25,  4.90it/s]

Processing tickers:  89%|████████▉ | 6004/6717 [20:27<02:26,  4.88it/s]

Processing tickers:  89%|████████▉ | 6005/6717 [20:27<02:25,  4.90it/s]

Processing tickers:  89%|████████▉ | 6006/6717 [20:28<02:24,  4.92it/s]

Processing tickers:  89%|████████▉ | 6007/6717 [20:28<02:23,  4.93it/s]

Processing tickers:  89%|████████▉ | 6008/6717 [20:28<02:24,  4.90it/s]

Processing tickers:  89%|████████▉ | 6009/6717 [20:28<02:23,  4.92it/s]

Processing tickers:  89%|████████▉ | 6010/6717 [20:28<02:23,  4.92it/s]

Processing tickers:  89%|████████▉ | 6011/6717 [20:29<02:23,  4.91it/s]

Processing tickers:  90%|████████▉ | 6012/6717 [20:29<02:25,  4.86it/s]

Processing tickers:  90%|████████▉ | 6013/6717 [20:29<02:24,  4.87it/s]

Processing tickers:  90%|████████▉ | 6014/6717 [20:29<02:23,  4.89it/s]

Processing tickers:  90%|████████▉ | 6015/6717 [20:29<02:24,  4.85it/s]

Processing tickers:  90%|████████▉ | 6016/6717 [20:30<02:24,  4.85it/s]

Processing tickers:  90%|████████▉ | 6017/6717 [20:30<02:22,  4.90it/s]

Processing tickers:  90%|████████▉ | 6018/6717 [20:30<02:21,  4.93it/s]

Processing tickers:  90%|████████▉ | 6019/6717 [20:30<02:22,  4.89it/s]

Processing tickers:  90%|████████▉ | 6020/6717 [20:30<02:22,  4.88it/s]

Processing tickers:  90%|████████▉ | 6021/6717 [20:31<02:23,  4.87it/s]

Processing tickers:  90%|████████▉ | 6022/6717 [20:31<02:22,  4.89it/s]

Processing tickers:  90%|████████▉ | 6023/6717 [20:31<02:22,  4.87it/s]

Processing tickers:  90%|████████▉ | 6024/6717 [20:31<02:23,  4.84it/s]

Processing tickers:  90%|████████▉ | 6025/6717 [20:31<02:22,  4.84it/s]

Processing tickers:  90%|████████▉ | 6026/6717 [20:32<02:21,  4.88it/s]

Processing tickers:  90%|████████▉ | 6027/6717 [20:32<02:21,  4.87it/s]

Processing tickers:  90%|████████▉ | 6028/6717 [20:32<02:22,  4.85it/s]

Processing tickers:  90%|████████▉ | 6029/6717 [20:32<02:21,  4.88it/s]

Processing tickers:  90%|████████▉ | 6030/6717 [20:32<02:24,  4.75it/s]

Processing tickers:  90%|████████▉ | 6031/6717 [20:33<02:24,  4.74it/s]

Processing tickers:  90%|████████▉ | 6032/6717 [20:33<02:22,  4.80it/s]

Processing tickers:  90%|████████▉ | 6033/6717 [20:33<02:21,  4.83it/s]

Processing tickers:  90%|████████▉ | 6034/6717 [20:33<02:20,  4.87it/s]

Processing tickers:  90%|████████▉ | 6035/6717 [20:33<02:19,  4.89it/s]

Processing tickers:  90%|████████▉ | 6036/6717 [20:34<02:18,  4.93it/s]

Processing tickers:  90%|████████▉ | 6037/6717 [20:34<02:17,  4.95it/s]

Processing tickers:  90%|████████▉ | 6038/6717 [20:34<02:19,  4.87it/s]

Processing tickers:  90%|████████▉ | 6039/6717 [20:34<02:17,  4.92it/s]

Processing tickers:  90%|████████▉ | 6040/6717 [20:34<02:17,  4.94it/s]

Processing tickers:  90%|████████▉ | 6041/6717 [20:35<02:16,  4.95it/s]

Processing tickers:  90%|████████▉ | 6042/6717 [20:35<02:15,  4.99it/s]

Processing tickers:  90%|████████▉ | 6043/6717 [20:35<02:15,  4.97it/s]

Processing tickers:  90%|████████▉ | 6044/6717 [20:35<02:15,  4.95it/s]

Processing tickers:  90%|████████▉ | 6045/6717 [20:35<02:14,  4.98it/s]

Processing tickers:  90%|█████████ | 6046/6717 [20:36<02:14,  4.97it/s]

Processing tickers:  90%|█████████ | 6047/6717 [20:36<02:14,  4.97it/s]

Processing tickers:  90%|█████████ | 6048/6717 [20:36<02:15,  4.95it/s]

Processing tickers:  90%|█████████ | 6049/6717 [20:36<02:14,  4.96it/s]

Processing tickers:  90%|█████████ | 6050/6717 [20:36<02:14,  4.96it/s]

Processing tickers:  90%|█████████ | 6051/6717 [20:37<02:14,  4.96it/s]

Processing tickers:  90%|█████████ | 6052/6717 [20:37<02:14,  4.96it/s]

Processing tickers:  90%|█████████ | 6053/6717 [20:37<02:14,  4.94it/s]

Processing tickers:  90%|█████████ | 6054/6717 [20:37<02:15,  4.91it/s]

Processing tickers:  90%|█████████ | 6055/6717 [20:38<02:15,  4.90it/s]

Processing tickers:  90%|█████████ | 6056/6717 [20:38<02:16,  4.83it/s]

Processing tickers:  90%|█████████ | 6057/6717 [20:38<02:15,  4.88it/s]

Processing tickers:  90%|█████████ | 6058/6717 [20:38<02:14,  4.91it/s]

Processing tickers:  90%|█████████ | 6059/6717 [20:38<02:14,  4.91it/s]

Processing tickers:  90%|█████████ | 6060/6717 [20:39<02:15,  4.86it/s]

Processing tickers:  90%|█████████ | 6061/6717 [20:39<02:14,  4.87it/s]

Processing tickers:  90%|█████████ | 6062/6717 [20:39<02:13,  4.91it/s]

Processing tickers:  90%|█████████ | 6063/6717 [20:39<02:13,  4.91it/s]

Processing tickers:  90%|█████████ | 6064/6717 [20:39<02:12,  4.93it/s]

Processing tickers:  90%|█████████ | 6065/6717 [20:40<02:12,  4.93it/s]

Processing tickers:  90%|█████████ | 6066/6717 [20:40<02:11,  4.96it/s]

Processing tickers:  90%|█████████ | 6067/6717 [20:40<02:12,  4.91it/s]

Processing tickers:  90%|█████████ | 6068/6717 [20:40<02:11,  4.94it/s]

Processing tickers:  90%|█████████ | 6069/6717 [20:40<02:12,  4.90it/s]

Processing tickers:  90%|█████████ | 6070/6717 [20:41<02:12,  4.88it/s]

Processing tickers:  90%|█████████ | 6071/6717 [20:41<02:11,  4.90it/s]

Processing tickers:  90%|█████████ | 6072/6717 [20:41<02:10,  4.94it/s]

Processing tickers:  90%|█████████ | 6073/6717 [20:41<02:12,  4.88it/s]

Processing tickers:  90%|█████████ | 6074/6717 [20:41<02:11,  4.89it/s]

Processing tickers:  90%|█████████ | 6075/6717 [20:42<02:10,  4.92it/s]

Processing tickers:  90%|█████████ | 6076/6717 [20:42<02:09,  4.93it/s]

Processing tickers:  90%|█████████ | 6077/6717 [20:42<02:09,  4.93it/s]

Processing tickers:  90%|█████████ | 6078/6717 [20:42<02:09,  4.92it/s]

Processing tickers:  91%|█████████ | 6079/6717 [20:42<02:10,  4.90it/s]

Processing tickers:  91%|█████████ | 6080/6717 [20:43<02:09,  4.92it/s]

Processing tickers:  91%|█████████ | 6081/6717 [20:43<02:08,  4.94it/s]

Processing tickers:  91%|█████████ | 6082/6717 [20:43<02:10,  4.87it/s]

Processing tickers:  91%|█████████ | 6083/6717 [20:43<02:10,  4.86it/s]

Processing tickers:  91%|█████████ | 6084/6717 [20:43<02:09,  4.90it/s]

Processing tickers:  91%|█████████ | 6085/6717 [20:44<02:08,  4.90it/s]

Processing tickers:  91%|█████████ | 6086/6717 [20:44<02:09,  4.86it/s]

Processing tickers:  91%|█████████ | 6087/6717 [20:44<02:08,  4.88it/s]

Processing tickers:  91%|█████████ | 6088/6717 [20:44<02:08,  4.89it/s]

Processing tickers:  91%|█████████ | 6089/6717 [20:44<02:08,  4.89it/s]

Processing tickers:  91%|█████████ | 6090/6717 [20:45<02:07,  4.92it/s]

Processing tickers:  91%|█████████ | 6091/6717 [20:45<02:08,  4.87it/s]

Processing tickers:  91%|█████████ | 6092/6717 [20:45<02:07,  4.89it/s]

Processing tickers:  91%|█████████ | 6093/6717 [20:45<02:07,  4.90it/s]

Processing tickers:  91%|█████████ | 6094/6717 [20:45<02:08,  4.84it/s]

Processing tickers:  91%|█████████ | 6095/6717 [20:46<02:07,  4.88it/s]

Processing tickers:  91%|█████████ | 6096/6717 [20:46<02:09,  4.78it/s]

Processing tickers:  91%|█████████ | 6097/6717 [20:46<02:08,  4.82it/s]

Processing tickers:  91%|█████████ | 6098/6717 [20:46<02:09,  4.79it/s]

Processing tickers:  91%|█████████ | 6099/6717 [20:47<02:07,  4.84it/s]

Processing tickers:  91%|█████████ | 6100/6717 [20:47<02:06,  4.89it/s]

Processing tickers:  91%|█████████ | 6101/6717 [20:47<02:04,  4.96it/s]

Processing tickers:  91%|█████████ | 6102/6717 [20:47<02:03,  4.96it/s]

Processing tickers:  91%|█████████ | 6103/6717 [20:47<02:03,  4.95it/s]

Processing tickers:  91%|█████████ | 6104/6717 [20:48<02:04,  4.93it/s]

Processing tickers:  91%|█████████ | 6105/6717 [20:48<02:03,  4.94it/s]

Processing tickers:  91%|█████████ | 6106/6717 [20:48<02:03,  4.96it/s]

Processing tickers:  91%|█████████ | 6107/6717 [20:48<02:06,  4.81it/s]

Processing tickers:  91%|█████████ | 6108/6717 [20:48<02:05,  4.87it/s]

Processing tickers:  91%|█████████ | 6109/6717 [20:49<02:04,  4.88it/s]

Processing tickers:  91%|█████████ | 6110/6717 [20:49<02:04,  4.89it/s]

Processing tickers:  91%|█████████ | 6111/6717 [20:49<02:03,  4.92it/s]

Processing tickers:  91%|█████████ | 6112/6717 [20:49<02:03,  4.88it/s]

Processing tickers:  91%|█████████ | 6113/6717 [20:49<02:03,  4.88it/s]

Processing tickers:  91%|█████████ | 6114/6717 [20:50<02:02,  4.92it/s]

Processing tickers:  91%|█████████ | 6115/6717 [20:50<02:01,  4.95it/s]

Processing tickers:  91%|█████████ | 6116/6717 [20:50<02:02,  4.91it/s]

Processing tickers:  91%|█████████ | 6117/6717 [20:50<02:01,  4.92it/s]

Processing tickers:  91%|█████████ | 6118/6717 [20:50<02:01,  4.94it/s]

Processing tickers:  91%|█████████ | 6119/6717 [20:51<02:00,  4.96it/s]

Processing tickers:  91%|█████████ | 6120/6717 [20:51<02:00,  4.95it/s]

Processing tickers:  91%|█████████ | 6121/6717 [20:51<02:00,  4.96it/s]

Processing tickers:  91%|█████████ | 6122/6717 [20:51<01:59,  4.97it/s]

Processing tickers:  91%|█████████ | 6123/6717 [20:51<01:59,  4.97it/s]

Processing tickers:  91%|█████████ | 6124/6717 [20:52<01:59,  4.98it/s]

Processing tickers:  91%|█████████ | 6125/6717 [20:52<01:59,  4.96it/s]

Processing tickers:  91%|█████████ | 6126/6717 [20:52<02:02,  4.84it/s]

Processing tickers:  91%|█████████ | 6127/6717 [20:52<02:00,  4.88it/s]

Processing tickers:  91%|█████████ | 6128/6717 [20:52<01:59,  4.93it/s]

Processing tickers:  91%|█████████ | 6129/6717 [20:53<01:58,  4.96it/s]

Processing tickers:  91%|█████████▏| 6130/6717 [20:53<01:58,  4.95it/s]

Processing tickers:  91%|█████████▏| 6131/6717 [20:53<02:02,  4.79it/s]

Processing tickers:  91%|█████████▏| 6132/6717 [20:53<02:00,  4.84it/s]

Processing tickers:  91%|█████████▏| 6133/6717 [20:53<01:59,  4.87it/s]

Processing tickers:  91%|█████████▏| 6134/6717 [20:54<01:58,  4.91it/s]

Processing tickers:  91%|█████████▏| 6135/6717 [20:54<01:58,  4.91it/s]

Processing tickers:  91%|█████████▏| 6136/6717 [20:54<01:58,  4.90it/s]

Processing tickers:  91%|█████████▏| 6137/6717 [20:54<01:57,  4.93it/s]

Processing tickers:  91%|█████████▏| 6138/6717 [20:54<01:57,  4.94it/s]

Processing tickers:  91%|█████████▏| 6139/6717 [20:55<01:56,  4.95it/s]

Processing tickers:  91%|█████████▏| 6140/6717 [20:55<01:56,  4.94it/s]

Processing tickers:  91%|█████████▏| 6141/6717 [20:55<01:59,  4.84it/s]

Processing tickers:  91%|█████████▏| 6142/6717 [20:55<01:57,  4.88it/s]

Processing tickers:  91%|█████████▏| 6143/6717 [20:55<01:57,  4.90it/s]

Processing tickers:  91%|█████████▏| 6144/6717 [20:56<01:56,  4.91it/s]

Processing tickers:  91%|█████████▏| 6145/6717 [20:56<01:55,  4.94it/s]

Processing tickers:  91%|█████████▏| 6146/6717 [20:56<01:56,  4.92it/s]

Processing tickers:  92%|█████████▏| 6147/6717 [20:56<01:55,  4.95it/s]

Processing tickers:  92%|█████████▏| 6148/6717 [20:56<01:54,  4.99it/s]

Processing tickers:  92%|█████████▏| 6149/6717 [20:57<01:53,  4.99it/s]

Processing tickers:  92%|█████████▏| 6150/6717 [20:57<01:54,  4.96it/s]

Processing tickers:  92%|█████████▏| 6151/6717 [20:57<01:54,  4.95it/s]

Processing tickers:  92%|█████████▏| 6152/6717 [20:57<01:53,  4.98it/s]

Processing tickers:  92%|█████████▏| 6153/6717 [20:57<01:53,  4.97it/s]

Processing tickers:  92%|█████████▏| 6154/6717 [20:58<01:53,  4.98it/s]

Processing tickers:  92%|█████████▏| 6155/6717 [20:58<01:53,  4.96it/s]

Processing tickers:  92%|█████████▏| 6156/6717 [20:58<01:52,  4.98it/s]

Processing tickers:  92%|█████████▏| 6157/6717 [20:58<01:52,  4.98it/s]

Processing tickers:  92%|█████████▏| 6158/6717 [20:58<01:52,  4.96it/s]

Processing tickers:  92%|█████████▏| 6159/6717 [20:59<01:52,  4.96it/s]

Processing tickers:  92%|█████████▏| 6160/6717 [20:59<01:52,  4.96it/s]

Processing tickers:  92%|█████████▏| 6161/6717 [20:59<01:52,  4.95it/s]

Processing tickers:  92%|█████████▏| 6162/6717 [20:59<01:52,  4.94it/s]

Processing tickers:  92%|█████████▏| 6163/6717 [20:59<01:52,  4.93it/s]

Processing tickers:  92%|█████████▏| 6164/6717 [21:00<01:51,  4.94it/s]

Processing tickers:  92%|█████████▏| 6165/6717 [21:00<01:51,  4.94it/s]

Processing tickers:  92%|█████████▏| 6166/6717 [21:00<01:51,  4.95it/s]

Processing tickers:  92%|█████████▏| 6167/6717 [21:00<01:52,  4.88it/s]

Processing tickers:  92%|█████████▏| 6168/6717 [21:01<01:51,  4.91it/s]

Processing tickers:  92%|█████████▏| 6169/6717 [21:01<01:50,  4.94it/s]

Processing tickers:  92%|█████████▏| 6170/6717 [21:01<01:50,  4.95it/s]

Processing tickers:  92%|█████████▏| 6171/6717 [21:01<01:50,  4.93it/s]

Processing tickers:  92%|█████████▏| 6172/6717 [21:01<01:50,  4.95it/s]

Processing tickers:  92%|█████████▏| 6173/6717 [21:02<01:49,  4.96it/s]

Processing tickers:  92%|█████████▏| 6174/6717 [21:02<01:49,  4.96it/s]

Processing tickers:  92%|█████████▏| 6175/6717 [21:02<01:49,  4.95it/s]

Processing tickers:  92%|█████████▏| 6176/6717 [21:02<01:50,  4.92it/s]

Processing tickers:  92%|█████████▏| 6177/6717 [21:02<01:49,  4.94it/s]

Processing tickers:  92%|█████████▏| 6178/6717 [21:03<01:48,  4.96it/s]

Processing tickers:  92%|█████████▏| 6179/6717 [21:03<01:49,  4.90it/s]

Processing tickers:  92%|█████████▏| 6180/6717 [21:03<01:49,  4.91it/s]

Processing tickers:  92%|█████████▏| 6181/6717 [21:03<01:48,  4.95it/s]

Processing tickers:  92%|█████████▏| 6182/6717 [21:03<01:48,  4.94it/s]

Processing tickers:  92%|█████████▏| 6183/6717 [21:04<01:47,  4.95it/s]

Processing tickers:  92%|█████████▏| 6184/6717 [21:04<01:47,  4.94it/s]

Processing tickers:  92%|█████████▏| 6185/6717 [21:04<01:51,  4.77it/s]

Processing tickers:  92%|█████████▏| 6186/6717 [21:04<01:50,  4.83it/s]

Processing tickers:  92%|█████████▏| 6187/6717 [21:04<01:48,  4.87it/s]

Processing tickers:  92%|█████████▏| 6188/6717 [21:05<01:49,  4.84it/s]

Processing tickers:  92%|█████████▏| 6189/6717 [21:05<01:47,  4.89it/s]

Processing tickers:  92%|█████████▏| 6190/6717 [21:05<01:53,  4.63it/s]

Processing tickers:  92%|█████████▏| 6191/6717 [21:05<01:51,  4.71it/s]

Processing tickers:  92%|█████████▏| 6192/6717 [21:05<01:54,  4.60it/s]

Processing tickers:  92%|█████████▏| 6193/6717 [21:06<01:54,  4.57it/s]

Processing tickers:  92%|█████████▏| 6194/6717 [21:06<01:51,  4.71it/s]

Processing tickers:  92%|█████████▏| 6195/6717 [21:06<01:49,  4.78it/s]

Processing tickers:  92%|█████████▏| 6196/6717 [21:06<01:47,  4.86it/s]

Processing tickers:  92%|█████████▏| 6197/6717 [21:06<01:46,  4.89it/s]

Processing tickers:  92%|█████████▏| 6198/6717 [21:07<01:46,  4.87it/s]

Processing tickers:  92%|█████████▏| 6199/6717 [21:07<01:46,  4.88it/s]

Processing tickers:  92%|█████████▏| 6200/6717 [21:07<01:45,  4.91it/s]

Processing tickers:  92%|█████████▏| 6201/6717 [21:07<01:44,  4.92it/s]

Processing tickers:  92%|█████████▏| 6202/6717 [21:07<01:44,  4.93it/s]

Processing tickers:  92%|█████████▏| 6203/6717 [21:08<01:43,  4.96it/s]

Processing tickers:  92%|█████████▏| 6204/6717 [21:08<01:43,  4.96it/s]

Processing tickers:  92%|█████████▏| 6205/6717 [21:08<01:46,  4.80it/s]

Processing tickers:  92%|█████████▏| 6206/6717 [21:08<01:44,  4.87it/s]

Processing tickers:  92%|█████████▏| 6207/6717 [21:09<01:43,  4.92it/s]

Processing tickers:  92%|█████████▏| 6208/6717 [21:09<01:43,  4.93it/s]

Processing tickers:  92%|█████████▏| 6209/6717 [21:09<01:42,  4.94it/s]

Processing tickers:  92%|█████████▏| 6210/6717 [21:09<01:47,  4.73it/s]

Processing tickers:  92%|█████████▏| 6211/6717 [21:09<01:47,  4.73it/s]

Processing tickers:  92%|█████████▏| 6212/6717 [21:10<01:45,  4.78it/s]

Processing tickers:  92%|█████████▏| 6213/6717 [21:10<01:44,  4.84it/s]

Processing tickers:  93%|█████████▎| 6214/6717 [21:10<01:43,  4.88it/s]

Processing tickers:  93%|█████████▎| 6215/6717 [21:10<01:42,  4.88it/s]

Processing tickers:  93%|█████████▎| 6216/6717 [21:10<01:41,  4.95it/s]

Processing tickers:  93%|█████████▎| 6217/6717 [21:11<01:40,  4.95it/s]

Processing tickers:  93%|█████████▎| 6218/6717 [21:11<01:40,  4.98it/s]

Processing tickers:  93%|█████████▎| 6219/6717 [21:11<01:39,  4.99it/s]

Processing tickers:  93%|█████████▎| 6220/6717 [21:11<01:41,  4.89it/s]

Processing tickers:  93%|█████████▎| 6221/6717 [21:11<01:40,  4.93it/s]

Processing tickers:  93%|█████████▎| 6222/6717 [21:12<01:40,  4.94it/s]

Processing tickers:  93%|█████████▎| 6223/6717 [21:12<01:39,  4.94it/s]

Processing tickers:  93%|█████████▎| 6224/6717 [21:12<01:40,  4.88it/s]

Processing tickers:  93%|█████████▎| 6225/6717 [21:12<01:40,  4.90it/s]

Processing tickers:  93%|█████████▎| 6226/6717 [21:12<01:39,  4.95it/s]

Processing tickers:  93%|█████████▎| 6227/6717 [21:13<01:38,  4.97it/s]

Processing tickers:  93%|█████████▎| 6228/6717 [21:13<01:38,  4.95it/s]

Processing tickers:  93%|█████████▎| 6229/6717 [21:13<01:39,  4.92it/s]

Processing tickers:  93%|█████████▎| 6230/6717 [21:13<01:38,  4.93it/s]

Processing tickers:  93%|█████████▎| 6231/6717 [21:13<01:38,  4.92it/s]

Processing tickers:  93%|█████████▎| 6232/6717 [21:14<01:42,  4.73it/s]

Processing tickers:  93%|█████████▎| 6233/6717 [21:14<01:41,  4.78it/s]

Processing tickers:  93%|█████████▎| 6234/6717 [21:14<01:39,  4.85it/s]

Processing tickers:  93%|█████████▎| 6235/6717 [21:14<01:38,  4.87it/s]

Processing tickers:  93%|█████████▎| 6236/6717 [21:14<01:38,  4.87it/s]

Processing tickers:  93%|█████████▎| 6237/6717 [21:15<01:38,  4.88it/s]

Processing tickers:  93%|█████████▎| 6238/6717 [21:15<01:37,  4.92it/s]

Processing tickers:  93%|█████████▎| 6239/6717 [21:15<01:36,  4.93it/s]

Processing tickers:  93%|█████████▎| 6240/6717 [21:15<01:36,  4.92it/s]

Processing tickers:  93%|█████████▎| 6241/6717 [21:15<01:36,  4.92it/s]

Processing tickers:  93%|█████████▎| 6242/6717 [21:16<01:36,  4.92it/s]

Processing tickers:  93%|█████████▎| 6243/6717 [21:16<01:36,  4.93it/s]

Processing tickers:  93%|█████████▎| 6244/6717 [21:16<01:35,  4.95it/s]

Processing tickers:  93%|█████████▎| 6245/6717 [21:16<01:35,  4.95it/s]

Processing tickers:  93%|█████████▎| 6246/6717 [21:16<01:35,  4.94it/s]

Processing tickers:  93%|█████████▎| 6247/6717 [21:17<01:34,  4.96it/s]

Processing tickers:  93%|█████████▎| 6248/6717 [21:17<01:35,  4.93it/s]

Processing tickers:  93%|█████████▎| 6249/6717 [21:17<01:35,  4.91it/s]

Processing tickers:  93%|█████████▎| 6250/6717 [21:17<01:36,  4.83it/s]

Processing tickers:  93%|█████████▎| 6251/6717 [21:18<01:35,  4.88it/s]

Processing tickers:  93%|█████████▎| 6252/6717 [21:18<01:34,  4.92it/s]

Processing tickers:  93%|█████████▎| 6253/6717 [21:18<01:34,  4.90it/s]

Processing tickers:  93%|█████████▎| 6254/6717 [21:18<01:34,  4.91it/s]

Processing tickers:  93%|█████████▎| 6255/6717 [21:18<01:34,  4.90it/s]

Processing tickers:  93%|█████████▎| 6256/6717 [21:19<01:33,  4.92it/s]

Processing tickers:  93%|█████████▎| 6257/6717 [21:19<01:33,  4.93it/s]

Processing tickers:  93%|█████████▎| 6258/6717 [21:19<01:33,  4.94it/s]

Processing tickers:  93%|█████████▎| 6259/6717 [21:19<01:33,  4.89it/s]

Processing tickers:  93%|█████████▎| 6260/6717 [21:19<01:33,  4.90it/s]

Processing tickers:  93%|█████████▎| 6261/6717 [21:20<01:32,  4.92it/s]

Processing tickers:  93%|█████████▎| 6262/6717 [21:20<01:31,  4.95it/s]

Processing tickers:  93%|█████████▎| 6263/6717 [21:20<01:31,  4.95it/s]

Processing tickers:  93%|█████████▎| 6264/6717 [21:20<01:32,  4.88it/s]

Processing tickers:  93%|█████████▎| 6265/6717 [21:20<01:32,  4.90it/s]

Processing tickers:  93%|█████████▎| 6266/6717 [21:21<01:32,  4.88it/s]

Processing tickers:  93%|█████████▎| 6267/6717 [21:21<01:31,  4.91it/s]

Processing tickers:  93%|█████████▎| 6268/6717 [21:21<01:32,  4.87it/s]

Processing tickers:  93%|█████████▎| 6269/6717 [21:21<01:31,  4.90it/s]

Processing tickers:  93%|█████████▎| 6270/6717 [21:21<01:31,  4.86it/s]

Processing tickers:  93%|█████████▎| 6271/6717 [21:22<01:30,  4.91it/s]

Processing tickers:  93%|█████████▎| 6272/6717 [21:22<01:30,  4.94it/s]

Processing tickers:  93%|█████████▎| 6273/6717 [21:22<01:29,  4.95it/s]

Processing tickers:  93%|█████████▎| 6274/6717 [21:22<01:29,  4.93it/s]

Processing tickers:  93%|█████████▎| 6275/6717 [21:22<01:29,  4.96it/s]

Processing tickers:  93%|█████████▎| 6276/6717 [21:23<01:30,  4.89it/s]

Processing tickers:  93%|█████████▎| 6277/6717 [21:23<01:29,  4.90it/s]

Processing tickers:  93%|█████████▎| 6278/6717 [21:23<01:31,  4.81it/s]

Processing tickers:  93%|█████████▎| 6279/6717 [21:23<01:29,  4.88it/s]

Processing tickers:  93%|█████████▎| 6280/6717 [21:23<01:30,  4.82it/s]

Processing tickers:  94%|█████████▎| 6281/6717 [21:24<01:31,  4.76it/s]

Processing tickers:  94%|█████████▎| 6282/6717 [21:24<01:31,  4.76it/s]

Processing tickers:  94%|█████████▎| 6283/6717 [21:24<01:30,  4.82it/s]

Processing tickers:  94%|█████████▎| 6284/6717 [21:24<01:28,  4.87it/s]

Processing tickers:  94%|█████████▎| 6285/6717 [21:24<01:28,  4.89it/s]

Processing tickers:  94%|█████████▎| 6286/6717 [21:25<01:27,  4.92it/s]

Processing tickers:  94%|█████████▎| 6287/6717 [21:25<01:28,  4.88it/s]

Processing tickers:  94%|█████████▎| 6288/6717 [21:25<01:28,  4.85it/s]

Processing tickers:  94%|█████████▎| 6289/6717 [21:25<01:28,  4.84it/s]

Processing tickers:  94%|█████████▎| 6290/6717 [21:25<01:27,  4.88it/s]

Processing tickers:  94%|█████████▎| 6291/6717 [21:26<01:27,  4.87it/s]

Processing tickers:  94%|█████████▎| 6292/6717 [21:26<01:27,  4.85it/s]

Processing tickers:  94%|█████████▎| 6293/6717 [21:26<01:27,  4.87it/s]

Processing tickers:  94%|█████████▎| 6294/6717 [21:26<01:27,  4.85it/s]

Processing tickers:  94%|█████████▎| 6295/6717 [21:27<01:26,  4.88it/s]

Processing tickers:  94%|█████████▎| 6296/6717 [21:27<01:26,  4.88it/s]

Processing tickers:  94%|█████████▎| 6297/6717 [21:27<01:25,  4.92it/s]

Processing tickers:  94%|█████████▍| 6298/6717 [21:27<01:24,  4.94it/s]

Processing tickers:  94%|█████████▍| 6299/6717 [21:27<01:24,  4.96it/s]

Processing tickers:  94%|█████████▍| 6300/6717 [21:28<01:23,  4.97it/s]

Processing tickers:  94%|█████████▍| 6301/6717 [21:28<01:24,  4.95it/s]

Processing tickers:  94%|█████████▍| 6302/6717 [21:28<01:23,  4.97it/s]

Processing tickers:  94%|█████████▍| 6303/6717 [21:28<01:23,  4.94it/s]

Processing tickers:  94%|█████████▍| 6304/6717 [21:28<01:24,  4.90it/s]

Processing tickers:  94%|█████████▍| 6305/6717 [21:29<01:23,  4.91it/s]

Processing tickers:  94%|█████████▍| 6306/6717 [21:29<01:23,  4.92it/s]

Processing tickers:  94%|█████████▍| 6307/6717 [21:29<01:23,  4.94it/s]

Processing tickers:  94%|█████████▍| 6308/6717 [21:29<01:24,  4.83it/s]

Processing tickers:  94%|█████████▍| 6309/6717 [21:29<01:24,  4.84it/s]

Processing tickers:  94%|█████████▍| 6310/6717 [21:30<01:23,  4.87it/s]

Processing tickers:  94%|█████████▍| 6311/6717 [21:30<01:22,  4.90it/s]

Processing tickers:  94%|█████████▍| 6312/6717 [21:30<01:21,  4.95it/s]

Processing tickers:  94%|█████████▍| 6313/6717 [21:30<01:21,  4.95it/s]

Processing tickers:  94%|█████████▍| 6314/6717 [21:30<01:21,  4.96it/s]

Processing tickers:  94%|█████████▍| 6315/6717 [21:31<01:21,  4.96it/s]

Processing tickers:  94%|█████████▍| 6316/6717 [21:31<01:21,  4.95it/s]

Processing tickers:  94%|█████████▍| 6317/6717 [21:31<01:20,  4.96it/s]

Processing tickers:  94%|█████████▍| 6318/6717 [21:31<01:20,  4.99it/s]

Processing tickers:  94%|█████████▍| 6319/6717 [21:31<01:19,  4.98it/s]

Processing tickers:  94%|█████████▍| 6320/6717 [21:32<01:19,  4.98it/s]

Processing tickers:  94%|█████████▍| 6321/6717 [21:32<01:19,  4.98it/s]

Processing tickers:  94%|█████████▍| 6322/6717 [21:32<01:19,  4.98it/s]

Processing tickers:  94%|█████████▍| 6323/6717 [21:32<01:19,  4.97it/s]

Processing tickers:  94%|█████████▍| 6324/6717 [21:32<01:19,  4.95it/s]

Processing tickers:  94%|█████████▍| 6325/6717 [21:33<01:21,  4.83it/s]

Processing tickers:  94%|█████████▍| 6326/6717 [21:33<01:19,  4.89it/s]

Processing tickers:  94%|█████████▍| 6327/6717 [21:33<01:22,  4.75it/s]

Processing tickers:  94%|█████████▍| 6328/6717 [21:33<01:21,  4.76it/s]

Processing tickers:  94%|█████████▍| 6329/6717 [21:33<01:21,  4.77it/s]

Processing tickers:  94%|█████████▍| 6330/6717 [21:34<01:19,  4.84it/s]

Processing tickers:  94%|█████████▍| 6331/6717 [21:34<01:19,  4.83it/s]

Processing tickers:  94%|█████████▍| 6332/6717 [21:34<01:19,  4.83it/s]

Processing tickers:  94%|█████████▍| 6333/6717 [21:34<01:20,  4.80it/s]

Processing tickers:  94%|█████████▍| 6334/6717 [21:34<01:19,  4.84it/s]

Processing tickers:  94%|█████████▍| 6335/6717 [21:35<01:18,  4.86it/s]

Processing tickers:  94%|█████████▍| 6336/6717 [21:35<01:17,  4.89it/s]

Processing tickers:  94%|█████████▍| 6337/6717 [21:35<01:17,  4.90it/s]

Processing tickers:  94%|█████████▍| 6338/6717 [21:35<01:16,  4.93it/s]

Processing tickers:  94%|█████████▍| 6339/6717 [21:35<01:16,  4.94it/s]

Processing tickers:  94%|█████████▍| 6340/6717 [21:36<01:15,  4.96it/s]

Processing tickers:  94%|█████████▍| 6341/6717 [21:36<01:15,  4.98it/s]

Processing tickers:  94%|█████████▍| 6342/6717 [21:36<01:15,  4.97it/s]

Processing tickers:  94%|█████████▍| 6343/6717 [21:36<01:15,  4.98it/s]

Processing tickers:  94%|█████████▍| 6344/6717 [21:36<01:15,  4.97it/s]

Processing tickers:  94%|█████████▍| 6345/6717 [21:37<01:14,  4.98it/s]

Processing tickers:  94%|█████████▍| 6346/6717 [21:37<01:14,  5.00it/s]

Processing tickers:  94%|█████████▍| 6347/6717 [21:37<01:14,  4.96it/s]

Processing tickers:  95%|█████████▍| 6348/6717 [21:37<01:14,  4.95it/s]

Processing tickers:  95%|█████████▍| 6349/6717 [21:37<01:15,  4.85it/s]

Processing tickers:  95%|█████████▍| 6350/6717 [21:38<01:15,  4.86it/s]

Processing tickers:  95%|█████████▍| 6351/6717 [21:38<01:14,  4.89it/s]

Processing tickers:  95%|█████████▍| 6352/6717 [21:38<01:14,  4.90it/s]

Processing tickers:  95%|█████████▍| 6353/6717 [21:38<01:13,  4.93it/s]

Processing tickers:  95%|█████████▍| 6354/6717 [21:39<01:13,  4.94it/s]

Processing tickers:  95%|█████████▍| 6355/6717 [21:39<01:13,  4.95it/s]

Processing tickers:  95%|█████████▍| 6356/6717 [21:39<01:12,  4.99it/s]

Processing tickers:  95%|█████████▍| 6357/6717 [21:39<01:12,  4.97it/s]

Processing tickers:  95%|█████████▍| 6358/6717 [21:39<01:13,  4.91it/s]

Processing tickers:  95%|█████████▍| 6359/6717 [21:40<01:12,  4.92it/s]

Processing tickers:  95%|█████████▍| 6360/6717 [21:40<01:12,  4.93it/s]

Processing tickers:  95%|█████████▍| 6361/6717 [21:40<01:12,  4.94it/s]

Processing tickers:  95%|█████████▍| 6362/6717 [21:40<01:11,  4.94it/s]

Processing tickers:  95%|█████████▍| 6363/6717 [21:40<01:11,  4.96it/s]

Processing tickers:  95%|█████████▍| 6364/6717 [21:41<01:10,  4.99it/s]

Processing tickers:  95%|█████████▍| 6365/6717 [21:41<01:10,  5.00it/s]

Processing tickers:  95%|█████████▍| 6366/6717 [21:41<01:10,  5.00it/s]

Processing tickers:  95%|█████████▍| 6367/6717 [21:41<01:10,  4.98it/s]

Processing tickers:  95%|█████████▍| 6368/6717 [21:41<01:10,  4.98it/s]

Processing tickers:  95%|█████████▍| 6369/6717 [21:42<01:09,  4.98it/s]

Processing tickers:  95%|█████████▍| 6370/6717 [21:42<01:10,  4.92it/s]

Processing tickers:  95%|█████████▍| 6371/6717 [21:42<01:09,  4.95it/s]

Processing tickers:  95%|█████████▍| 6372/6717 [21:42<01:09,  4.95it/s]

Processing tickers:  95%|█████████▍| 6373/6717 [21:42<01:10,  4.91it/s]

Processing tickers:  95%|█████████▍| 6374/6717 [21:43<01:09,  4.91it/s]

Processing tickers:  95%|█████████▍| 6375/6717 [21:43<01:09,  4.89it/s]

Processing tickers:  95%|█████████▍| 6376/6717 [21:43<01:09,  4.92it/s]

Processing tickers:  95%|█████████▍| 6377/6717 [21:43<01:08,  4.94it/s]

Processing tickers:  95%|█████████▍| 6378/6717 [21:43<01:08,  4.95it/s]

Processing tickers:  95%|█████████▍| 6379/6717 [21:44<01:08,  4.94it/s]

Processing tickers:  95%|█████████▍| 6380/6717 [21:44<01:08,  4.95it/s]

Processing tickers:  95%|█████████▍| 6381/6717 [21:44<01:07,  4.98it/s]

Processing tickers:  95%|█████████▌| 6382/6717 [21:44<01:07,  4.98it/s]

Processing tickers:  95%|█████████▌| 6383/6717 [21:44<01:07,  4.94it/s]

Processing tickers:  95%|█████████▌| 6384/6717 [21:45<01:07,  4.97it/s]

Processing tickers:  95%|█████████▌| 6385/6717 [21:45<01:06,  4.98it/s]

Processing tickers:  95%|█████████▌| 6386/6717 [21:45<01:06,  4.99it/s]

Processing tickers:  95%|█████████▌| 6387/6717 [21:45<01:05,  5.00it/s]

Processing tickers:  95%|█████████▌| 6388/6717 [21:45<01:05,  4.99it/s]

Processing tickers:  95%|█████████▌| 6389/6717 [21:46<01:06,  4.90it/s]

Processing tickers:  95%|█████████▌| 6390/6717 [21:46<01:06,  4.90it/s]

Processing tickers:  95%|█████████▌| 6391/6717 [21:46<01:13,  4.46it/s]

Processing tickers:  95%|█████████▌| 6392/6717 [21:46<01:10,  4.61it/s]

Processing tickers:  95%|█████████▌| 6393/6717 [21:46<01:08,  4.72it/s]

Processing tickers:  95%|█████████▌| 6394/6717 [21:47<01:07,  4.80it/s]

Processing tickers:  95%|█████████▌| 6395/6717 [21:47<01:06,  4.86it/s]

Processing tickers:  95%|█████████▌| 6396/6717 [21:47<01:05,  4.90it/s]

Processing tickers:  95%|█████████▌| 6397/6717 [21:47<01:06,  4.78it/s]

Processing tickers:  95%|█████████▌| 6398/6717 [21:47<01:05,  4.85it/s]

Processing tickers:  95%|█████████▌| 6399/6717 [21:48<01:05,  4.84it/s]

Processing tickers:  95%|█████████▌| 6400/6717 [21:48<01:05,  4.87it/s]

Processing tickers:  95%|█████████▌| 6401/6717 [21:48<01:04,  4.91it/s]

Processing tickers:  95%|█████████▌| 6402/6717 [21:48<01:03,  4.95it/s]

Processing tickers:  95%|█████████▌| 6403/6717 [21:48<01:03,  4.92it/s]

Processing tickers:  95%|█████████▌| 6404/6717 [21:49<01:03,  4.91it/s]

Processing tickers:  95%|█████████▌| 6405/6717 [21:49<01:03,  4.92it/s]

Processing tickers:  95%|█████████▌| 6406/6717 [21:49<01:03,  4.92it/s]

Processing tickers:  95%|█████████▌| 6407/6717 [21:49<01:02,  4.95it/s]

Processing tickers:  95%|█████████▌| 6408/6717 [21:49<01:02,  4.95it/s]

Processing tickers:  95%|█████████▌| 6409/6717 [21:50<01:01,  4.97it/s]

Processing tickers:  95%|█████████▌| 6410/6717 [21:50<01:01,  5.00it/s]

Processing tickers:  95%|█████████▌| 6411/6717 [21:50<01:01,  5.00it/s]

Processing tickers:  95%|█████████▌| 6412/6717 [21:50<01:02,  4.90it/s]

Processing tickers:  95%|█████████▌| 6413/6717 [21:51<01:01,  4.93it/s]

Processing tickers:  95%|█████████▌| 6414/6717 [21:51<01:01,  4.93it/s]

Processing tickers:  96%|█████████▌| 6415/6717 [21:51<01:01,  4.94it/s]

Processing tickers:  96%|█████████▌| 6416/6717 [21:51<01:01,  4.92it/s]

Processing tickers:  96%|█████████▌| 6417/6717 [21:51<01:01,  4.91it/s]

Processing tickers:  96%|█████████▌| 6418/6717 [21:52<01:00,  4.92it/s]

Processing tickers:  96%|█████████▌| 6419/6717 [21:52<01:00,  4.93it/s]

Processing tickers:  96%|█████████▌| 6420/6717 [21:52<01:00,  4.92it/s]

Processing tickers:  96%|█████████▌| 6421/6717 [21:52<00:59,  4.95it/s]

Processing tickers:  96%|█████████▌| 6422/6717 [21:52<00:59,  4.96it/s]

Processing tickers:  96%|█████████▌| 6423/6717 [21:53<00:59,  4.98it/s]

Processing tickers:  96%|█████████▌| 6424/6717 [21:53<00:58,  4.99it/s]

Processing tickers:  96%|█████████▌| 6425/6717 [21:53<00:58,  5.02it/s]

Processing tickers:  96%|█████████▌| 6426/6717 [21:53<00:58,  4.99it/s]

Processing tickers:  96%|█████████▌| 6427/6717 [21:53<00:58,  4.98it/s]

Processing tickers:  96%|█████████▌| 6428/6717 [21:54<00:58,  4.97it/s]

Processing tickers:  96%|█████████▌| 6429/6717 [21:54<00:57,  4.97it/s]

Processing tickers:  96%|█████████▌| 6430/6717 [21:54<00:57,  4.96it/s]

Processing tickers:  96%|█████████▌| 6431/6717 [21:54<00:57,  4.97it/s]

Processing tickers:  96%|█████████▌| 6432/6717 [21:54<00:57,  4.95it/s]

Processing tickers:  96%|█████████▌| 6433/6717 [21:55<00:57,  4.91it/s]

Processing tickers:  96%|█████████▌| 6434/6717 [21:55<00:58,  4.87it/s]

Processing tickers:  96%|█████████▌| 6435/6717 [21:55<00:57,  4.94it/s]

Processing tickers:  96%|█████████▌| 6436/6717 [21:55<00:56,  4.94it/s]

Processing tickers:  96%|█████████▌| 6437/6717 [21:55<00:56,  4.95it/s]

Processing tickers:  96%|█████████▌| 6438/6717 [21:56<00:56,  4.96it/s]

Processing tickers:  96%|█████████▌| 6439/6717 [21:56<00:56,  4.96it/s]

Processing tickers:  96%|█████████▌| 6440/6717 [21:56<00:56,  4.93it/s]

Processing tickers:  96%|█████████▌| 6441/6717 [21:56<00:56,  4.92it/s]

Processing tickers:  96%|█████████▌| 6442/6717 [21:56<00:55,  4.92it/s]

Processing tickers:  96%|█████████▌| 6443/6717 [21:57<00:55,  4.94it/s]

Processing tickers:  96%|█████████▌| 6444/6717 [21:57<00:55,  4.90it/s]

Processing tickers:  96%|█████████▌| 6445/6717 [21:57<00:56,  4.80it/s]

Processing tickers:  96%|█████████▌| 6446/6717 [21:57<00:55,  4.85it/s]

Processing tickers:  96%|█████████▌| 6447/6717 [21:57<00:58,  4.62it/s]

Processing tickers:  96%|█████████▌| 6448/6717 [21:58<00:56,  4.73it/s]

Processing tickers:  96%|█████████▌| 6449/6717 [21:58<00:56,  4.77it/s]

Processing tickers:  96%|█████████▌| 6450/6717 [21:58<00:55,  4.84it/s]

Processing tickers:  96%|█████████▌| 6451/6717 [21:58<00:54,  4.88it/s]

Processing tickers:  96%|█████████▌| 6452/6717 [21:58<00:54,  4.89it/s]

Processing tickers:  96%|█████████▌| 6453/6717 [21:59<00:53,  4.92it/s]

Processing tickers:  96%|█████████▌| 6454/6717 [21:59<00:53,  4.95it/s]

Processing tickers:  96%|█████████▌| 6455/6717 [21:59<00:52,  4.98it/s]

Processing tickers:  96%|█████████▌| 6456/6717 [21:59<00:52,  4.99it/s]

Processing tickers:  96%|█████████▌| 6457/6717 [21:59<00:52,  4.97it/s]

Processing tickers:  96%|█████████▌| 6458/6717 [22:00<00:51,  4.99it/s]

Processing tickers:  96%|█████████▌| 6459/6717 [22:00<00:51,  5.00it/s]

Processing tickers:  96%|█████████▌| 6460/6717 [22:00<00:51,  4.96it/s]

Processing tickers:  96%|█████████▌| 6461/6717 [22:00<00:51,  4.97it/s]

Processing tickers:  96%|█████████▌| 6462/6717 [22:00<00:52,  4.88it/s]

Processing tickers:  96%|█████████▌| 6463/6717 [22:01<00:51,  4.92it/s]

Processing tickers:  96%|█████████▌| 6464/6717 [22:01<00:51,  4.93it/s]

Processing tickers:  96%|█████████▌| 6465/6717 [22:01<00:50,  4.96it/s]

Processing tickers:  96%|█████████▋| 6466/6717 [22:01<00:50,  4.97it/s]

Processing tickers:  96%|█████████▋| 6467/6717 [22:01<00:50,  4.97it/s]

Processing tickers:  96%|█████████▋| 6468/6717 [22:02<00:49,  4.99it/s]

Processing tickers:  96%|█████████▋| 6469/6717 [22:02<00:49,  5.00it/s]

Processing tickers:  96%|█████████▋| 6470/6717 [22:02<00:49,  4.98it/s]

Processing tickers:  96%|█████████▋| 6471/6717 [22:02<00:49,  4.97it/s]

Processing tickers:  96%|█████████▋| 6472/6717 [22:02<00:49,  4.95it/s]

Processing tickers:  96%|█████████▋| 6473/6717 [22:03<00:49,  4.95it/s]

Processing tickers:  96%|█████████▋| 6474/6717 [22:03<00:49,  4.94it/s]

Processing tickers:  96%|█████████▋| 6475/6717 [22:03<00:49,  4.90it/s]

Processing tickers:  96%|█████████▋| 6476/6717 [22:03<00:48,  4.94it/s]

Processing tickers:  96%|█████████▋| 6477/6717 [22:03<00:48,  4.94it/s]

Processing tickers:  96%|█████████▋| 6478/6717 [22:04<00:48,  4.97it/s]

Processing tickers:  96%|█████████▋| 6479/6717 [22:04<00:47,  5.01it/s]

Processing tickers:  96%|█████████▋| 6480/6717 [22:04<00:47,  4.99it/s]

Processing tickers:  96%|█████████▋| 6481/6717 [22:04<00:47,  5.02it/s]

Processing tickers:  97%|█████████▋| 6482/6717 [22:04<00:46,  5.03it/s]

Processing tickers:  97%|█████████▋| 6483/6717 [22:05<00:46,  4.98it/s]

Processing tickers:  97%|█████████▋| 6484/6717 [22:05<00:46,  4.99it/s]

Processing tickers:  97%|█████████▋| 6485/6717 [22:05<00:46,  5.01it/s]

Processing tickers:  97%|█████████▋| 6486/6717 [22:05<00:46,  4.93it/s]

Processing tickers:  97%|█████████▋| 6487/6717 [22:05<00:46,  4.94it/s]

Processing tickers:  97%|█████████▋| 6488/6717 [22:06<00:46,  4.96it/s]

Processing tickers:  97%|█████████▋| 6489/6717 [22:06<00:46,  4.93it/s]

Processing tickers:  97%|█████████▋| 6490/6717 [22:06<00:45,  4.94it/s]

Processing tickers:  97%|█████████▋| 6491/6717 [22:06<00:46,  4.86it/s]

Processing tickers:  97%|█████████▋| 6492/6717 [22:07<00:46,  4.87it/s]

Processing tickers:  97%|█████████▋| 6493/6717 [22:07<00:45,  4.91it/s]

Processing tickers:  97%|█████████▋| 6494/6717 [22:07<00:45,  4.91it/s]

Processing tickers:  97%|█████████▋| 6495/6717 [22:07<00:45,  4.90it/s]

Processing tickers:  97%|█████████▋| 6496/6717 [22:07<00:45,  4.90it/s]

Processing tickers:  97%|█████████▋| 6497/6717 [22:08<00:44,  4.90it/s]

Processing tickers:  97%|█████████▋| 6498/6717 [22:08<00:44,  4.89it/s]

Processing tickers:  97%|█████████▋| 6499/6717 [22:08<00:44,  4.93it/s]

Processing tickers:  97%|█████████▋| 6500/6717 [22:08<00:43,  4.95it/s]

Processing tickers:  97%|█████████▋| 6501/6717 [22:08<00:43,  4.91it/s]

Processing tickers:  97%|█████████▋| 6502/6717 [22:09<00:43,  4.94it/s]

Processing tickers:  97%|█████████▋| 6503/6717 [22:09<00:43,  4.90it/s]

Processing tickers:  97%|█████████▋| 6504/6717 [22:09<00:44,  4.84it/s]

Processing tickers:  97%|█████████▋| 6505/6717 [22:09<00:43,  4.87it/s]

Processing tickers:  97%|█████████▋| 6506/6717 [22:09<00:43,  4.85it/s]

Processing tickers:  97%|█████████▋| 6507/6717 [22:10<00:42,  4.89it/s]

Processing tickers:  97%|█████████▋| 6508/6717 [22:10<00:42,  4.94it/s]

Processing tickers:  97%|█████████▋| 6509/6717 [22:10<00:41,  4.96it/s]

Processing tickers:  97%|█████████▋| 6510/6717 [22:10<00:41,  4.98it/s]

Processing tickers:  97%|█████████▋| 6511/6717 [22:10<00:41,  4.98it/s]

Processing tickers:  97%|█████████▋| 6512/6717 [22:11<00:41,  4.98it/s]

Processing tickers:  97%|█████████▋| 6513/6717 [22:11<00:41,  4.97it/s]

Processing tickers:  97%|█████████▋| 6514/6717 [22:11<00:41,  4.95it/s]

Processing tickers:  97%|█████████▋| 6515/6717 [22:11<00:40,  4.94it/s]

Processing tickers:  97%|█████████▋| 6516/6717 [22:11<00:40,  4.96it/s]

Processing tickers:  97%|█████████▋| 6517/6717 [22:12<00:40,  4.97it/s]

Processing tickers:  97%|█████████▋| 6518/6717 [22:12<00:40,  4.97it/s]

Processing tickers:  97%|█████████▋| 6519/6717 [22:12<00:40,  4.91it/s]

Processing tickers:  97%|█████████▋| 6520/6717 [22:12<00:40,  4.91it/s]

Processing tickers:  97%|█████████▋| 6521/6717 [22:12<00:39,  4.92it/s]

Processing tickers:  97%|█████████▋| 6522/6717 [22:13<00:39,  4.90it/s]

Processing tickers:  97%|█████████▋| 6523/6717 [22:13<00:39,  4.93it/s]

Processing tickers:  97%|█████████▋| 6524/6717 [22:13<00:39,  4.88it/s]

Processing tickers:  97%|█████████▋| 6525/6717 [22:13<00:39,  4.91it/s]

Processing tickers:  97%|█████████▋| 6526/6717 [22:13<00:38,  4.93it/s]

Processing tickers:  97%|█████████▋| 6527/6717 [22:14<00:38,  4.95it/s]

Processing tickers:  97%|█████████▋| 6528/6717 [22:14<00:38,  4.96it/s]

Processing tickers:  97%|█████████▋| 6529/6717 [22:14<00:38,  4.89it/s]

Processing tickers:  97%|█████████▋| 6530/6717 [22:14<00:37,  4.94it/s]

Processing tickers:  97%|█████████▋| 6531/6717 [22:14<00:37,  4.95it/s]

Processing tickers:  97%|█████████▋| 6532/6717 [22:15<00:37,  4.96it/s]

Processing tickers:  97%|█████████▋| 6533/6717 [22:15<00:37,  4.96it/s]

Processing tickers:  97%|█████████▋| 6534/6717 [22:15<00:36,  4.95it/s]

Processing tickers:  97%|█████████▋| 6535/6717 [22:15<00:36,  4.96it/s]

Processing tickers:  97%|█████████▋| 6536/6717 [22:15<00:36,  4.98it/s]

Processing tickers:  97%|█████████▋| 6537/6717 [22:16<00:36,  4.99it/s]

Processing tickers:  97%|█████████▋| 6538/6717 [22:16<00:35,  4.99it/s]

Processing tickers:  97%|█████████▋| 6539/6717 [22:16<00:35,  4.98it/s]

Processing tickers:  97%|█████████▋| 6540/6717 [22:16<00:35,  5.00it/s]

Processing tickers:  97%|█████████▋| 6541/6717 [22:16<00:35,  4.99it/s]

Processing tickers:  97%|█████████▋| 6542/6717 [22:17<00:35,  4.98it/s]

Processing tickers:  97%|█████████▋| 6543/6717 [22:17<00:34,  4.99it/s]

Processing tickers:  97%|█████████▋| 6544/6717 [22:17<00:34,  4.99it/s]

Processing tickers:  97%|█████████▋| 6545/6717 [22:17<00:34,  4.99it/s]

Processing tickers:  97%|█████████▋| 6546/6717 [22:17<00:34,  5.00it/s]

Processing tickers:  97%|█████████▋| 6547/6717 [22:18<00:33,  5.00it/s]

Processing tickers:  97%|█████████▋| 6548/6717 [22:18<00:33,  4.98it/s]

Processing tickers:  97%|█████████▋| 6549/6717 [22:18<00:34,  4.93it/s]

Processing tickers:  98%|█████████▊| 6550/6717 [22:18<00:33,  4.96it/s]

Processing tickers:  98%|█████████▊| 6551/6717 [22:18<00:33,  4.93it/s]

Processing tickers:  98%|█████████▊| 6552/6717 [22:19<00:33,  4.93it/s]

Processing tickers:  98%|█████████▊| 6553/6717 [22:19<00:33,  4.96it/s]

Processing tickers:  98%|█████████▊| 6554/6717 [22:19<00:32,  4.96it/s]

Processing tickers:  98%|█████████▊| 6555/6717 [22:19<00:32,  4.92it/s]

Processing tickers:  98%|█████████▊| 6556/6717 [22:19<00:32,  4.95it/s]

Processing tickers:  98%|█████████▊| 6557/6717 [22:20<00:32,  4.94it/s]

Processing tickers:  98%|█████████▊| 6558/6717 [22:20<00:32,  4.94it/s]

Processing tickers:  98%|█████████▊| 6559/6717 [22:20<00:32,  4.92it/s]

Processing tickers:  98%|█████████▊| 6560/6717 [22:20<00:31,  4.91it/s]

Processing tickers:  98%|█████████▊| 6561/6717 [22:20<00:32,  4.85it/s]

Processing tickers:  98%|█████████▊| 6562/6717 [22:21<00:31,  4.86it/s]

Processing tickers:  98%|█████████▊| 6563/6717 [22:21<00:31,  4.89it/s]

Processing tickers:  98%|█████████▊| 6564/6717 [22:21<00:31,  4.90it/s]

Processing tickers:  98%|█████████▊| 6565/6717 [22:21<00:30,  4.93it/s]

Processing tickers:  98%|█████████▊| 6566/6717 [22:22<00:30,  4.92it/s]

Processing tickers:  98%|█████████▊| 6567/6717 [22:22<00:30,  4.91it/s]

Processing tickers:  98%|█████████▊| 6568/6717 [22:22<00:30,  4.94it/s]

Processing tickers:  98%|█████████▊| 6569/6717 [22:22<00:30,  4.92it/s]

Processing tickers:  98%|█████████▊| 6570/6717 [22:22<00:29,  4.91it/s]

Processing tickers:  98%|█████████▊| 6571/6717 [22:23<00:29,  4.92it/s]

Processing tickers:  98%|█████████▊| 6572/6717 [22:23<00:29,  4.93it/s]

Processing tickers:  98%|█████████▊| 6573/6717 [22:23<00:29,  4.96it/s]

Processing tickers:  98%|█████████▊| 6574/6717 [22:23<00:28,  4.97it/s]

Processing tickers:  98%|█████████▊| 6575/6717 [22:23<00:28,  4.95it/s]

Processing tickers:  98%|█████████▊| 6576/6717 [22:24<00:28,  4.96it/s]

Processing tickers:  98%|█████████▊| 6577/6717 [22:24<00:28,  4.96it/s]

Processing tickers:  98%|█████████▊| 6578/6717 [22:24<00:28,  4.96it/s]

Processing tickers:  98%|█████████▊| 6579/6717 [22:24<00:27,  4.95it/s]

Processing tickers:  98%|█████████▊| 6580/6717 [22:24<00:27,  4.90it/s]

Processing tickers:  98%|█████████▊| 6581/6717 [22:25<00:27,  4.91it/s]

Processing tickers:  98%|█████████▊| 6582/6717 [22:25<00:27,  4.86it/s]

Processing tickers:  98%|█████████▊| 6583/6717 [22:25<00:28,  4.77it/s]

Processing tickers:  98%|█████████▊| 6584/6717 [22:25<00:28,  4.74it/s]

Processing tickers:  98%|█████████▊| 6585/6717 [22:25<00:27,  4.81it/s]

Processing tickers:  98%|█████████▊| 6586/6717 [22:26<00:27,  4.81it/s]

Processing tickers:  98%|█████████▊| 6587/6717 [22:26<00:26,  4.84it/s]

Processing tickers:  98%|█████████▊| 6588/6717 [22:26<00:27,  4.74it/s]

Processing tickers:  98%|█████████▊| 6589/6717 [22:26<00:26,  4.79it/s]

Processing tickers:  98%|█████████▊| 6590/6717 [22:26<00:26,  4.76it/s]

Processing tickers:  98%|█████████▊| 6591/6717 [22:27<00:26,  4.82it/s]

Processing tickers:  98%|█████████▊| 6592/6717 [22:27<00:25,  4.84it/s]

Processing tickers:  98%|█████████▊| 6593/6717 [22:27<00:25,  4.84it/s]

Processing tickers:  98%|█████████▊| 6594/6717 [22:27<00:25,  4.79it/s]

Processing tickers:  98%|█████████▊| 6595/6717 [22:27<00:25,  4.84it/s]

Processing tickers:  98%|█████████▊| 6596/6717 [22:28<00:24,  4.87it/s]

Processing tickers:  98%|█████████▊| 6597/6717 [22:28<00:25,  4.75it/s]

Processing tickers:  98%|█████████▊| 6598/6717 [22:28<00:24,  4.80it/s]

Processing tickers:  98%|█████████▊| 6599/6717 [22:28<00:24,  4.84it/s]

Processing tickers:  98%|█████████▊| 6600/6717 [22:29<00:24,  4.81it/s]

Processing tickers:  98%|█████████▊| 6601/6717 [22:29<00:24,  4.81it/s]

Processing tickers:  98%|█████████▊| 6602/6717 [22:29<00:23,  4.87it/s]

Processing tickers:  98%|█████████▊| 6603/6717 [22:29<00:23,  4.89it/s]

Processing tickers:  98%|█████████▊| 6604/6717 [22:29<00:22,  4.93it/s]

Processing tickers:  98%|█████████▊| 6605/6717 [22:30<00:22,  4.95it/s]

Processing tickers:  98%|█████████▊| 6606/6717 [22:30<00:22,  4.96it/s]

Processing tickers:  98%|█████████▊| 6607/6717 [22:30<00:22,  4.98it/s]

Processing tickers:  98%|█████████▊| 6608/6717 [22:30<00:21,  4.98it/s]

Processing tickers:  98%|█████████▊| 6609/6717 [22:30<00:21,  4.99it/s]

Processing tickers:  98%|█████████▊| 6610/6717 [22:31<00:21,  4.97it/s]

Processing tickers:  98%|█████████▊| 6611/6717 [22:31<00:21,  4.98it/s]

Processing tickers:  98%|█████████▊| 6612/6717 [22:31<00:21,  4.98it/s]

Processing tickers:  98%|█████████▊| 6613/6717 [22:31<00:20,  4.98it/s]

Processing tickers:  98%|█████████▊| 6614/6717 [22:31<00:20,  4.93it/s]

Processing tickers:  98%|█████████▊| 6615/6717 [22:32<00:20,  4.96it/s]

Processing tickers:  98%|█████████▊| 6616/6717 [22:32<00:20,  4.88it/s]

Processing tickers:  99%|█████████▊| 6617/6717 [22:32<00:20,  4.93it/s]

Processing tickers:  99%|█████████▊| 6618/6717 [22:32<00:20,  4.94it/s]

Processing tickers:  99%|█████████▊| 6619/6717 [22:32<00:19,  4.92it/s]

Processing tickers:  99%|█████████▊| 6620/6717 [22:33<00:19,  4.94it/s]

Processing tickers:  99%|█████████▊| 6621/6717 [22:33<00:19,  4.93it/s]

Processing tickers:  99%|█████████▊| 6622/6717 [22:33<00:19,  4.93it/s]

Processing tickers:  99%|█████████▊| 6623/6717 [22:33<00:19,  4.91it/s]

Processing tickers:  99%|█████████▊| 6624/6717 [22:33<00:19,  4.89it/s]

Processing tickers:  99%|█████████▊| 6625/6717 [22:34<00:18,  4.94it/s]

Processing tickers:  99%|█████████▊| 6626/6717 [22:34<00:18,  4.94it/s]

Processing tickers:  99%|█████████▊| 6627/6717 [22:34<00:18,  4.93it/s]

Processing tickers:  99%|█████████▊| 6628/6717 [22:34<00:18,  4.94it/s]

Processing tickers:  99%|█████████▊| 6629/6717 [22:34<00:17,  4.95it/s]

Processing tickers:  99%|█████████▊| 6630/6717 [22:35<00:17,  4.94it/s]

Processing tickers:  99%|█████████▊| 6631/6717 [22:35<00:17,  4.96it/s]

Processing tickers:  99%|█████████▊| 6632/6717 [22:35<00:17,  4.95it/s]

Processing tickers:  99%|█████████▊| 6633/6717 [22:35<00:16,  4.94it/s]

Processing tickers:  99%|█████████▉| 6634/6717 [22:35<00:16,  4.96it/s]

Processing tickers:  99%|█████████▉| 6635/6717 [22:36<00:16,  4.98it/s]

Processing tickers:  99%|█████████▉| 6636/6717 [22:36<00:16,  4.97it/s]

Processing tickers:  99%|█████████▉| 6637/6717 [22:36<00:16,  4.98it/s]

Processing tickers:  99%|█████████▉| 6638/6717 [22:36<00:15,  4.96it/s]

Processing tickers:  99%|█████████▉| 6639/6717 [22:36<00:15,  4.95it/s]

Processing tickers:  99%|█████████▉| 6640/6717 [22:37<00:15,  4.94it/s]

Processing tickers:  99%|█████████▉| 6641/6717 [22:37<00:15,  4.91it/s]

Processing tickers:  99%|█████████▉| 6642/6717 [22:37<00:15,  4.83it/s]

Processing tickers:  99%|█████████▉| 6643/6717 [22:37<00:15,  4.88it/s]

Processing tickers:  99%|█████████▉| 6644/6717 [22:37<00:15,  4.85it/s]

Processing tickers:  99%|█████████▉| 6645/6717 [22:38<00:14,  4.87it/s]

Processing tickers:  99%|█████████▉| 6646/6717 [22:38<00:14,  4.87it/s]

Processing tickers:  99%|█████████▉| 6647/6717 [22:38<00:14,  4.86it/s]

Processing tickers:  99%|█████████▉| 6648/6717 [22:38<00:14,  4.89it/s]

Processing tickers:  99%|█████████▉| 6649/6717 [22:38<00:13,  4.90it/s]

Processing tickers:  99%|█████████▉| 6650/6717 [22:39<00:13,  4.91it/s]

Processing tickers:  99%|█████████▉| 6651/6717 [22:39<00:13,  4.87it/s]

Processing tickers:  99%|█████████▉| 6652/6717 [22:39<00:13,  4.88it/s]

Processing tickers:  99%|█████████▉| 6653/6717 [22:39<00:12,  4.92it/s]

Processing tickers:  99%|█████████▉| 6654/6717 [22:39<00:12,  4.92it/s]

Processing tickers:  99%|█████████▉| 6655/6717 [22:40<00:12,  4.93it/s]

Processing tickers:  99%|█████████▉| 6656/6717 [22:40<00:12,  4.95it/s]

Processing tickers:  99%|█████████▉| 6657/6717 [22:40<00:12,  4.95it/s]

Processing tickers:  99%|█████████▉| 6658/6717 [22:40<00:11,  4.98it/s]

Processing tickers:  99%|█████████▉| 6659/6717 [22:40<00:11,  4.99it/s]

Processing tickers:  99%|█████████▉| 6660/6717 [22:41<00:11,  4.98it/s]

Processing tickers:  99%|█████████▉| 6661/6717 [22:41<00:11,  5.00it/s]

Processing tickers:  99%|█████████▉| 6662/6717 [22:41<00:11,  4.99it/s]

Processing tickers:  99%|█████████▉| 6663/6717 [22:41<00:10,  4.98it/s]

Processing tickers:  99%|█████████▉| 6664/6717 [22:41<00:10,  4.96it/s]

Processing tickers:  99%|█████████▉| 6665/6717 [22:42<00:10,  4.91it/s]

Processing tickers:  99%|█████████▉| 6666/6717 [22:42<00:10,  4.94it/s]

Processing tickers:  99%|█████████▉| 6667/6717 [22:42<00:10,  4.95it/s]

Processing tickers:  99%|█████████▉| 6668/6717 [22:42<00:09,  4.94it/s]

Processing tickers:  99%|█████████▉| 6669/6717 [22:42<00:09,  4.96it/s]

Processing tickers:  99%|█████████▉| 6670/6717 [22:43<00:09,  4.96it/s]

Processing tickers:  99%|█████████▉| 6671/6717 [22:43<00:09,  4.96it/s]

Processing tickers:  99%|█████████▉| 6672/6717 [22:43<00:09,  4.94it/s]

Processing tickers:  99%|█████████▉| 6673/6717 [22:43<00:08,  4.93it/s]

Processing tickers:  99%|█████████▉| 6674/6717 [22:43<00:08,  4.94it/s]

Processing tickers:  99%|█████████▉| 6675/6717 [22:44<00:08,  4.96it/s]

Processing tickers:  99%|█████████▉| 6676/6717 [22:44<00:08,  4.91it/s]

Processing tickers:  99%|█████████▉| 6677/6717 [22:44<00:08,  4.92it/s]

Processing tickers:  99%|█████████▉| 6678/6717 [22:44<00:07,  4.91it/s]

Processing tickers:  99%|█████████▉| 6679/6717 [22:45<00:07,  4.90it/s]

Processing tickers:  99%|█████████▉| 6680/6717 [22:45<00:07,  4.86it/s]

Processing tickers:  99%|█████████▉| 6681/6717 [22:45<00:07,  4.91it/s]

Processing tickers:  99%|█████████▉| 6682/6717 [22:45<00:07,  4.87it/s]

Processing tickers:  99%|█████████▉| 6683/6717 [22:45<00:06,  4.87it/s]

Processing tickers: 100%|█████████▉| 6684/6717 [22:46<00:06,  4.82it/s]

Processing tickers: 100%|█████████▉| 6685/6717 [22:46<00:06,  4.87it/s]

Processing tickers: 100%|█████████▉| 6686/6717 [22:46<00:06,  4.89it/s]

Processing tickers: 100%|█████████▉| 6687/6717 [22:46<00:06,  4.93it/s]

Processing tickers: 100%|█████████▉| 6688/6717 [22:46<00:05,  4.94it/s]

Processing tickers: 100%|█████████▉| 6689/6717 [22:47<00:05,  4.95it/s]

Processing tickers: 100%|█████████▉| 6690/6717 [22:47<00:05,  4.94it/s]

Processing tickers: 100%|█████████▉| 6691/6717 [22:47<00:05,  4.97it/s]

Processing tickers: 100%|█████████▉| 6692/6717 [22:47<00:05,  4.99it/s]

Processing tickers: 100%|█████████▉| 6693/6717 [22:47<00:04,  4.98it/s]

Processing tickers: 100%|█████████▉| 6694/6717 [22:48<00:04,  4.82it/s]

Processing tickers: 100%|█████████▉| 6695/6717 [22:48<00:04,  4.80it/s]

Processing tickers: 100%|█████████▉| 6696/6717 [22:48<00:04,  4.70it/s]

Processing tickers: 100%|█████████▉| 6697/6717 [22:48<00:04,  4.78it/s]

Processing tickers: 100%|█████████▉| 6698/6717 [22:48<00:03,  4.78it/s]

Processing tickers: 100%|█████████▉| 6699/6717 [22:49<00:03,  4.85it/s]

Processing tickers: 100%|█████████▉| 6700/6717 [22:49<00:03,  4.90it/s]

Processing tickers: 100%|█████████▉| 6701/6717 [22:49<00:03,  4.86it/s]

Processing tickers: 100%|█████████▉| 6702/6717 [22:49<00:03,  4.90it/s]

Processing tickers: 100%|█████████▉| 6703/6717 [22:49<00:02,  4.92it/s]

Processing tickers: 100%|█████████▉| 6704/6717 [22:50<00:02,  4.86it/s]

Processing tickers: 100%|█████████▉| 6705/6717 [22:50<00:02,  4.89it/s]

Processing tickers: 100%|█████████▉| 6706/6717 [22:50<00:02,  4.90it/s]

Processing tickers: 100%|█████████▉| 6707/6717 [22:50<00:02,  4.89it/s]

Processing tickers: 100%|█████████▉| 6708/6717 [22:50<00:01,  4.92it/s]

Processing tickers: 100%|█████████▉| 6709/6717 [22:51<00:01,  4.93it/s]

Processing tickers: 100%|█████████▉| 6710/6717 [22:51<00:01,  4.96it/s]

Processing tickers: 100%|█████████▉| 6711/6717 [22:51<00:01,  4.85it/s]

Processing tickers: 100%|█████████▉| 6712/6717 [22:51<00:01,  4.89it/s]

Processing tickers: 100%|█████████▉| 6713/6717 [22:51<00:00,  4.92it/s]

Processing tickers: 100%|█████████▉| 6714/6717 [22:52<00:00,  4.94it/s]

Processing tickers: 100%|█████████▉| 6715/6717 [22:52<00:00,  4.87it/s]

Processing tickers: 100%|█████████▉| 6716/6717 [22:52<00:00,  4.93it/s]

Processing tickers: 100%|██████████| 6717/6717 [22:52<00:00,  4.94it/s]

Processing tickers: 100%|██████████| 6717/6717 [22:52<00:00,  4.89it/s]

         date ticker   gap
0  2025-11-21      A -0.41
1  2025-11-24      A  0.43
2  2025-11-25      A -1.84
3  2025-11-26      A -0.93
4  2025-11-28      A -0.17
Загалом рядків: 398829

In [46]:
std_by_ticker = (
    df_gaps_all.groupby("ticker")["gap"]
    .std()                 # std по групі (ddof=1)
    .round(2)              # округлення до 2 знаків
    .reset_index(name="sigma")
)

In [47]:
std_by_ticker

     ticker  sigma
0         A   0.60
1        AA   1.94
2      AAAU   1.65
3      AACG   3.80
4     AACOU    NaN
...     ...    ...
6712    ZWS   0.79
6713   ZYBT   3.46
6714   ZYME   1.13
6715   ZYXI  11.04
6716  ZYXIQ  13.05

[6717 rows x 2 columns]

In [48]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [49]:
# std_by_ticker має колонки: ['ticker','sigma']
add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,  # <- твій DF зі скріна
    # або sigma_path="CRACEN/std_by_ticker.parquet"/".csv"
    insert_before=None,      # або "Bench%" / "pct_vs_prev_close" — куди вставити
)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=9.6s

[batch   10] rows=20,000,000  elapsed=19.3s

[batch   15] rows=30,000,000  elapsed=28.9s

[batch   20] rows=40,000,000  elapsed=38.6s

[batch   25] rows=50,000,000  elapsed=48.4s

[batch   30] rows=60,000,000  elapsed=58.4s

[batch   35] rows=70,000,000  elapsed=68.2s

[batch   40] rows=79,478,082  elapsed=77.5s
✅ DONE rows=79,478,082 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 77.6s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct_with_sigma.parquet'

In [50]:
peek_parquet("CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet", n=21150)

Файл: CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 79,478,082
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 0/21150
NaN у 'beta' (у прев'ю): 0/21150

Перші рядки:

      ticker                  dt           o           h           l           c          v        date    open  prev_close  Stack% bench  corr  beta  Bench%  sigma
0          A 2025-11-21 00:45:00  145.830002  145.830002  145.830002  145.830002        9.0  2025-11-21  144.47      145.06    0.53   SPY  0.67  0.64    0.27   0.60
1          A 2025-11-21 01:50:00  145.800003  145.800003  145.800003  145.800003        5.0  2025-11-21  144.47      145.06    0.51   SPY  0.67  0.64    0.33   0.60
2          A 2025-11-21 02:00:00  145.809998  145.809998  145.809998  145.809998        5.0  2025-11-21  144.47      145.06    0.52   SPY  0.67  0.64    0.30   0.60
3          A 2025-11-21 09:30:00  144.470001  145.375000  144.470001  144.645004    84953.0  2025-11-21  144.47      145.06   -0.41   SPY  0.67  0.64    0.38   0.60
4          A 2025-11-21 09:31:00  144.645004  144.645004  144.645004  144.645004     2500.0  2025-11-21  144.47      145.06   -0.29   SPY  0.67  0.64    0.49   0.60
5          A 2025-11-21 09:32:00  145.000000  145.410004  144.949997  145.054993      891.0  2025-11-21  144.47      145.06   -0.04   SPY  0.67  0.64    0.33   0.60
6          A 2025-11-21 09:34:00  145.820007  146.050003  145.630005  146.039993    41022.0  2025-11-21  144.47      145.06    0.52   SPY  0.67  0.64    0.39   0.60
7          A 2025-11-21 09:35:00  145.889999  145.910004  145.679993  145.679993     1039.0  2025-11-21  144.47      145.06    0.57   SPY  0.67  0.64    0.45   0.60
8          A 2025-11-21 09:36:00  145.639999  146.130005  145.559998  146.130005     1206.0  2025-11-21  144.47      145.06    0.40   SPY  0.67  0.64    0.40   0.60
9          A 2025-11-21 09:37:00  146.100006  146.360001  146.100006  146.360001      500.0  2025-11-21  144.47      145.06    0.72   SPY  0.67  0.64    0.51   0.60
10         A 2025-11-21 09:39:00  146.330002  146.360001  145.940002  145.979996    12264.0  2025-11-21  144.47      145.06    0.88   SPY  0.67  0.64    0.35   0.60
11         A 2025-11-21 09:40:00  145.929993  145.929993  145.830002  145.830002      300.0  2025-11-21  144.47      145.06    0.60   SPY  0.67  0.64    0.32   0.60
12         A 2025-11-21 09:41:00  145.990005  145.990005  145.990005  145.990005      100.0  2025-11-21  144.47      145.06    0.64   SPY  0.67  0.64    0.42   0.60
13         A 2025-11-21 09:42:00  145.979996  146.039993  145.809998  145.910004     2181.0  2025-11-21  144.47      145.06    0.63   SPY  0.67  0.64    0.47   0.60
14         A 2025-11-21 09:43:00  146.039993  146.039993  145.919998  145.919998      813.0  2025-11-21  144.47      145.06    0.68   SPY  0.67  0.64    0.36   0.60
15         A 2025-11-21 09:44:00  145.860001  146.119995  145.860001  146.080002     2827.0  2025-11-21  144.47      145.06    0.55   SPY  0.67  0.64    0.30   0.60
16         A 2025-11-21 09:45:00  146.130005  146.270004  146.095001  146.270004     1216.0  2025-11-21  144.47      145.06    0.74   SPY  0.67  0.64    0.28   0.60
17         A 2025-11-21 09:46:00  146.279999  146.360001  146.080002  146.214996     3905.0  2025-11-21  144.47      145.06    0.84   SPY  0.67  0.64    0.20   0.60
18         A 2025-11-21 09:47:00  146.255005  146.259995  145.979996  146.229996    20366.0  2025-11-21  144.47      145.06    0.82   SPY  0.67  0.64    0.14   0.60
19         A 2025-11-21 09:48:00  146.479996  146.820007  146.470001  146.514999     1940.0  2025-11-21  144.47      145.06    0.98   SPY  0.67  0.64    0.18   0.60
20         A 2025-11-21 09:49:00  146.520004  146.520004  146.309998  146.429993      496.0  2025-11-21  144.47      145.06    1.01   SPY  0.67  0.64    0.42   0.60
21         A 2025-11-21 09:50:00  146.384995  146.500000  146.315002  146.470001     1400.0  2025-11-21  144.47      145.06    0.91   SPY  0.67  0.64    0.33   0.60
22         A 2025-11-21 09:51:00  146.380005  146.380005  146.274994  146.274994      700.0  2025-11-21  144.47      145.06    0.91   SPY  0.67  0.64    0.35   0.60
23         A 2025-11-21 09:52:00  146.199997  146.479996  146.164993  146.360001     2367.0  2025-11-21  144.47      145.06    0.79   SPY  0.67  0.64    0.34   0.60
24         A 2025-11-21 09:53:00  146.360001  146.360001  146.360001  146.360001      100.0  2025-11-21  144.47      145.06    0.90   SPY  0.67  0.64    0.46   0.60
25         A 2025-11-21 09:54:00  146.354996  146.559998  146.354996  146.419998     6216.0  2025-11-21  144.47      145.06    0.89   SPY  0.67  0.64    0.47   0.60
26         A 2025-11-21 09:55:00  146.509995  146.789993  146.509995  146.679993     5026.0  2025-11-21  144.47      145.06    1.00   SPY  0.67  0.64    0.55   0.60
27         A 2025-11-21 09:56:00  146.639999  146.819901  146.630005  146.710007      600.0  2025-11-21  144.47      145.06    1.09   SPY  0.67  0.64    0.52   0.60
28         A 2025-11-21 09:57:00  146.710007  146.919998  146.710007  146.740005     1056.0  2025-11-21  144.47      145.06    1.14   SPY  0.67  0.64    0.30   0.60
29         A 2025-11-21 09:58:00  146.899994  147.130005  146.899994  147.130005      650.0  2025-11-21  144.47      145.06    1.27   SPY  0.67  0.64    0.36   0.60
30         A 2025-11-21 09:59:00  147.059998  147.100006  146.850006  146.850006     2911.0  2025-11-21  144.47      145.06    1.38   SPY  0.67  0.64    0.39   0.60
31         A 2025-11-21 10:00:00  147.000000  147.259995  146.870102  147.110001      600.0  2025-11-21  144.47      145.06    1.34   SPY  0.67  0.64    0.32   0.60
32         A 2025-11-21 10:01:00  147.100006  147.240005  147.089996  147.169998     1116.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64    0.32   0.60
33         A 2025-11-21 10:02:00  147.107498  147.107498  146.889999  146.979996     1461.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64    0.24   0.60
34         A 2025-11-21 10:03:00  147.100006  147.139999  146.927505  147.139999      400.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64    0.14   0.60
35         A 2025-11-21 10:04:00  146.940002  147.009995  146.830002  146.889999      600.0  2025-11-21  144.47      145.06    1.30   SPY  0.67  0.64    0.21   0.60
36         A 2025-11-21 10:05:00  147.050003  147.059998  146.830002  147.050003      400.0  2025-11-21  144.47      145.06    1.37   SPY  0.67  0.64    0.21   0.60
37         A 2025-11-21 10:06:00  146.970001  147.130005  146.910004  146.990005      500.0  2025-11-21  144.47      145.06    1.32   SPY  0.67  0.64    0.34   0.60
38         A 2025-11-21 10:07:00  146.994995  147.009995  146.630005  146.847900     6211.0  2025-11-21  144.47      145.06    1.33   SPY  0.67  0.64    0.42   0.60
39         A 2025-11-21 10:08:00  146.875000  146.875000  146.645004  146.860001     1100.0  2025-11-21  144.47      145.06    1.25   SPY  0.67  0.64    0.30   0.60
40         A 2025-11-21 10:09:00  146.789993  147.210007  146.714996  147.199997     1217.0  2025-11-21  144.47      145.06    1.19   SPY  0.67  0.64    0.25   0.60
41         A 2025-11-21 10:10:00  147.070007  147.440002  147.070007  147.399994     2757.0  2025-11-21  144.47      145.06    1.39   SPY  0.67  0.64    0.27   0.60
42         A 2025-11-21 10:11:00  147.429993  147.440002  147.169998  147.360001     2479.0  2025-11-21  144.47      145.06    1.63   SPY  0.67  0.64    0.20   0.60
43         A 2025-11-21 10:12:00  147.102997  147.190002  146.960007  147.149994     1154.0  2025-11-21  144.47      145.06    1.41   SPY  0.67  0.64    0.21   0.60
44         A 2025-11-21 10:13:00  147.289993  147.289993  146.979996  147.040100     3236.0  2025-11-21  144.47      145.06    1.54   SPY  0.67  0.64    0.18   0.60
45         A 2025-11-21 10:14:00  147.039993  147.059998  146.960007  147.059998      600.0  2025-11-21  144.47      145.06    1.36   SPY  0.67  0.64    0.15   0.60
46         A 2025-11-21 10:15:00  147.229996  147.279999  147.184998  147.279999     1300.0  2025-11-21  144.47      145.06    1.50   SPY  0.67  0.64    0.18   0.60
47         A 2025-11-21 10:16:00  147.350006  147.410004  147.320007  147.320007      501.0  2025-11-21  144.47      145.06    1.58   SPY  0.67  0.64    0.18   0.60
48         A 2025-11-21 10:17:00  147.380005  147.449997  147.380005  147.449997      300.0  2025-11-21  144.47      145.06    1.60   SPY  0.67  0.64    0.17   0.60
49         A 2025-11-21 10:18:00  147.339996  147.449997  147.294998  147.389999     1400.0  2025-11-21  144.47      145.06    1.57   SPY  0.67  0.64    0.06   0.60
50         A 2025-11-21 10:19:00  147.365005  147.369995  147.220001  147.320007     1800.0  2025-11-21  144.47      145.06    1.59   SPY  0.67  0.64    0.21   0.60
51         A 2025-11-21 10:20:00  147.285004  147.339996  147.000000  147.080002     2866.0  2025-11-21  144.47      145.06    1.53   SPY  0.67  0.64    0.27   0.60
52         A 2025-11-21 10:21:00  147.044998  147.139999  146.964996  147.139999      700.0  2025-11-21  144.47      145.06    1.37   SPY  0.67  0.64    0.12   0.60
53         A 2025-11-21 10:22:00  147.289993  147.580002  147.119995  147.440002     2814.0  2025-11-21  144.47      145.06    1.54   SPY  0.67  0.64    0.02   0.60
54         A 2025-11-21 10:23:00  147.419998  147.570007  147.139999  147.369995     4902.0  2025-11-21  144.47      145.06    1.63   SPY  0.67  0.64    0.23   0.60
55         A 2025-11-21 10:24:00  147.380005  147.550003  147.179993  147.550003     2549.0  2025-11-21  144.47      145.06    1.60   SPY  0.67  0.64    0.26   0.60
56         A 2025-11-21 10:25:00  147.570007  147.839996  147.539993  147.710007     1360.0  2025-11-21  144.47      145.06    1.73   SPY  0.67  0.64    0.40   0.60
57         A 2025-11-21 10:26:00  147.690002  147.690002  147.690002  147.690002      100.0  2025-11-21  144.47      145.06    1.81   SPY  0.67  0.64    0.40   0.60
58         A 2025-11-21 10:27:00  147.610001  147.779999  147.470001  147.580002     4519.0  2025-11-21  144.47      145.06    1.76   SPY  0.67  0.64    0.29   0.60
59         A 2025-11-21 10:28:00  147.544998  147.710007  147.324997  147.710007     2794.0  2025-11-21  144.47      145.06    1.71   SPY  0.67  0.64    0.18   0.60
60         A 2025-11-21 10:29:00  147.574997  147.710007  147.479996  147.649994     2554.0  2025-11-21  144.47      145.06    1.73   SPY  0.67  0.64    0.07   0.60
61         A 2025-11-21 10:30:00  147.600006  148.089996  147.565002  148.074997     5928.0  2025-11-21  144.47      145.06    1.75   SPY  0.67  0.64    0.09   0.60
62         A 2025-11-21 10:31:00  148.119995  148.210007  148.020004  148.210007     3057.0  2025-11-21  144.47      145.06    2.11   SPY  0.67  0.64    0.14   0.60
63         A 2025-11-21 10:32:00  148.009995  148.210007  147.929993  147.945007     1920.0  2025-11-21  144.47      145.06    2.03   SPY  0.67  0.64    0.17   0.60
64         A 2025-11-21 10:33:00  147.990005  148.225006  147.990005  148.160004     1105.0  2025-11-21  144.47      145.06    2.02   SPY  0.67  0.64    0.17   0.60
65         A 2025-11-21 10:34:00  148.089996  148.089996  147.949997  147.949997      900.0  2025-11-21  144.47      145.06    2.09   SPY  0.67  0.64    0.04   0.60
66         A 2025-11-21 10:35:00  147.945007  147.945007  147.945007  147.945007     1150.0  2025-11-21  144.47      145.06    1.99   SPY  0.67  0.64    0.03   0.60
67         A 2025-11-21 10:36:00  147.850006  147.850006  147.839996  147.839996     1146.0  2025-11-21  144.47      145.06    1.92   SPY  0.67  0.64   -0.12   0.60
68         A 2025-11-21 10:37:00  147.770004  147.949997  147.710007  147.919998     1278.0  2025-11-21  144.47      145.06    1.87   SPY  0.67  0.64   -0.18   0.60
69         A 2025-11-21 10:38:00  148.020004  148.220001  147.934998  148.220001     4351.0  2025-11-21  144.47      145.06    2.04   SPY  0.67  0.64   -0.17   0.60
70         A 2025-11-21 10:39:00  148.210007  148.380005  148.130005  148.324997     2147.0  2025-11-21  144.47      145.06    2.17   SPY  0.67  0.64   -0.14   0.60
71         A 2025-11-21 10:40:00  148.324997  148.600006  148.259995  148.380005     4528.0  2025-11-21  144.47      145.06    2.25   SPY  0.67  0.64   -0.17   0.60
72         A 2025-11-21 10:41:00  148.419998  148.475006  148.250000  148.380005     6518.0  2025-11-21  144.47      145.06    2.32   SPY  0.67  0.64   -0.18   0.60
73         A 2025-11-21 10:42:00  148.289993  148.289993  148.057495  148.059998     2306.0  2025-11-21  144.47      145.06    2.23   SPY  0.67  0.64   -0.13   0.60
74         A 2025-11-21 10:43:00  148.149994  148.160004  147.949997  147.960007     1800.0  2025-11-21  144.47      145.06    2.13   SPY  0.67  0.64   -0.05   0.60
75         A 2025-11-21 10:44:00  147.985001  148.149994  147.970001  148.020004     1700.0  2025-11-21  144.47      145.06    2.02   SPY  0.67  0.64   -0.03   0.60
76         A 2025-11-21 10:45:00  148.039993  148.149994  148.039993  148.149994      200.0  2025-11-21  144.47      145.06    2.05   SPY  0.67  0.64    0.05   0.60
77         A 2025-11-21 10:46:00  148.070007  148.255005  147.919998  148.024994     9335.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64    0.11   0.60
78         A 2025-11-21 10:47:00  148.024994  148.205002  148.024994  148.205002     4372.0  2025-11-21  144.47      145.06    2.04   SPY  0.67  0.64    0.17   0.60
79         A 2025-11-21 10:48:00  148.190002  148.190002  147.910004  148.100006     1973.0  2025-11-21  144.47      145.06    2.16   SPY  0.67  0.64    0.21   0.60
80         A 2025-11-21 10:49:00  148.050003  148.339996  148.050003  148.244995     1300.0  2025-11-21  144.47      145.06    2.06   SPY  0.67  0.64    0.18   0.60
81         A 2025-11-21 10:50:00  148.139999  148.139999  148.119995  148.125000      500.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64    0.23   0.60
82         A 2025-11-21 10:51:00  148.154999  148.154999  148.070007  148.139999     2134.0  2025-11-21  144.47      145.06    2.13   SPY  0.67  0.64    0.21   0.60
83         A 2025-11-21 10:52:00  148.149994  148.350006  148.149994  148.220001     4799.0  2025-11-21  144.47      145.06    2.13   SPY  0.67  0.64    0.11   0.60
84         A 2025-11-21 10:53:00  148.220001  148.300003  148.199997  148.199997     1252.0  2025-11-21  144.47      145.06    2.18   SPY  0.67  0.64    0.05   0.60
85         A 2025-11-21 10:54:00  148.205002  148.300003  148.205002  148.259995     2546.0  2025-11-21  144.47      145.06    2.17   SPY  0.67  0.64    0.13   0.60
86         A 2025-11-21 10:55:00  148.250000  148.460007  148.240005  148.460007     1382.0  2025-11-21  144.47      145.06    2.20   SPY  0.67  0.64    0.25   0.60
87         A 2025-11-21 10:56:00  148.449997  148.615005  148.449997  148.600006     1000.0  2025-11-21  144.47      145.06    2.34   SPY  0.67  0.64    0.28   0.60
88         A 2025-11-21 10:57:00  148.589996  148.630005  148.535004  148.535004     1451.0  2025-11-21  144.47      145.06    2.43   SPY  0.67  0.64    0.26   0.60
89         A 2025-11-21 10:58:00  148.535004  148.559998  148.440002  148.449997     1705.0  2025-11-21  144.47      145.06    2.40   SPY  0.67  0.64    0.10   0.60
90         A 2025-11-21 10:59:00  148.475006  148.475006  148.259995  148.259995     1879.0  2025-11-21  144.47      145.06    2.35   SPY  0.67  0.64    0.13   0.60
91         A 2025-11-21 11:00:00  148.259995  148.274994  148.179993  148.179993     3917.0  2025-11-21  144.47      145.06    2.21   SPY  0.67  0.64    0.03   0.60
92         A 2025-11-21 11:01:00  148.169998  148.279999  148.119995  148.205002     4528.0  2025-11-21  144.47      145.06    2.14   SPY  0.67  0.64    0.06   0.60
93         A 2025-11-21 11:02:00  148.130005  148.240005  148.089996  148.190002     3124.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64    0.02   0.60
94         A 2025-11-21 11:03:00  148.110001  148.154999  148.080002  148.125000     1438.0  2025-11-21  144.47      145.06    2.10   SPY  0.67  0.64   -0.05   0.60
95         A 2025-11-21 11:04:00  148.130005  148.130005  148.050003  148.089996     1780.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64   -0.04   0.60
96         A 2025-11-21 11:05:00  148.050003  148.070007  147.919998  148.005005     3155.0  2025-11-21  144.47      145.06    2.06   SPY  0.67  0.64   -0.10   0.60
97         A 2025-11-21 11:06:00  148.089996  148.089996  148.039993  148.039993     1000.0  2025-11-21  144.47      145.06    2.09   SPY  0.67  0.64   -0.19   0.60
98         A 2025-11-21 11:07:00  148.160004  148.160004  148.039993  148.130005     1884.0  2025-11-21  144.47      145.06    2.14   SPY  0.67  0.64   -0.11   0.60
99         A 2025-11-21 11:08:00  148.080002  148.179993  148.054993  148.125000     5563.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64   -0.04   0.60
100        A 2025-11-21 11:09:00  148.070007  148.149994  148.059998  148.149994     1144.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64    0.02   0.60
101        A 2025-11-21 11:10:00  148.089996  148.169998  148.050003  148.050003     2200.0  2025-11-21  144.47      145.06    2.09   SPY  0.67  0.64    0.05   0.60
102        A 2025-11-21 11:11:00  148.074997  148.074997  147.714996  147.725006     2000.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64    0.07   0.60
103        A 2025-11-21 11:12:00  147.727493  147.860001  147.725006  147.860001     2099.0  2025-11-21  144.47      145.06    1.84   SPY  0.67  0.64    0.05   0.60
104        A 2025-11-21 11:13:00  147.860001  148.039993  147.860001  148.000000     4579.0  2025-11-21  144.47      145.06    1.93   SPY  0.67  0.64    0.07   0.60
105        A 2025-11-21 11:14:00  147.949997  147.985001  147.949997  147.985001     2142.0  2025-11-21  144.47      145.06    1.99   SPY  0.67  0.64    0.15   0.60
106        A 2025-11-21 11:15:00  148.050003  148.097504  148.044998  148.097504     1301.0  2025-11-21  144.47      145.06    2.06   SPY  0.67  0.64    0.12   0.60
107        A 2025-11-21 11:16:00  148.139999  148.139999  147.949997  148.070007     2892.0  2025-11-21  144.47      145.06    2.12   SPY  0.67  0.64    0.14   0.60
108        A 2025-11-21 11:17:00  148.070007  148.070007  147.994995  148.039993     1100.0  2025-11-21  144.47      145.06    2.08   SPY  0.67  0.64    0.18   0.60
109        A 2025-11-21 11:18:00  148.009995  148.009995  147.744995  147.744995     2756.0  2025-11-21  144.47      145.06    2.03   SPY  0.67  0.64    0.15   0.60
110        A 2025-11-21 11:19:00  147.779999  147.860001  147.744995  147.744995     2736.0  2025-11-21  144.47      145.06    1.88   SPY  0.67  0.64   -0.07   0.60
111        A 2025-11-21 11:20:00  147.779999  148.070007  147.779999  148.005005     2400.0  2025-11-21  144.47      145.06    1.88   SPY  0.67  0.64   -0.04   0.60
112        A 2025-11-21 11:21:00  148.002502  148.179993  148.002502  148.179993      500.0  2025-11-21  144.47      145.06    2.03   SPY  0.67  0.64    0.16   0.60
113        A 2025-11-21 11:22:00  148.179993  148.309998  148.179993  148.304993     1600.0  2025-11-21  144.47      145.06    2.15   SPY  0.67  0.64    0.27   0.60
114        A 2025-11-21 11:23:00  148.354996  148.494995  148.354996  148.445007     1400.0  2025-11-21  144.47      145.06    2.27   SPY  0.67  0.64    0.28   0.60
115        A 2025-11-21 11:24:00  148.500000  148.615005  148.500000  148.554993     1772.0  2025-11-21  144.47      145.06    2.37   SPY  0.67  0.64    0.26   0.60
116        A 2025-11-21 11:25:00  148.630005  148.689896  148.570007  148.570007      750.0  2025-11-21  144.47      145.06    2.46   SPY  0.67  0.64    0.35   0.60
117        A 2025-11-21 11:26:00  148.604996  148.669998  148.529999  148.654999     1161.0  2025-11-21  144.47      145.06    2.44   SPY  0.67  0.64    0.36   0.60
118        A 2025-11-21 11:27:00  148.699997  148.880005  148.699997  148.770004     2304.0  2025-11-21  144.47      145.06    2.51   SPY  0.67  0.64    0.36   0.60
119        A 2025-11-21 11:28:00  148.770004  148.850006  148.770004  148.850006      300.0  2025-11-21  144.47      145.06    2.56   SPY  0.67  0.64    0.38   0.60

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2025-11-21 00:45:00,145.830002,145.830002,145.830002,145.830002,9.0,2025-11-21,144.47,145.06,0.53,SPY,0.67,0.64,0.27,0.60
1,A,2025-11-21 01:50:00,145.800003,145.800003,145.800003,145.800003,5.0,2025-11-21,144.47,145.06,0.51,SPY,0.67,0.64,0.33,0.60
2,A,2025-11-21 02:00:00,145.809998,145.809998,145.809998,145.809998,5.0,2025-11-21,144.47,145.06,0.52,SPY,0.67,0.64,0.30,0.60
3,A,2025-11-21 09:30:00,144.470001,145.375000,144.470001,144.645004,84953.0,2025-11-21,144.47,145.06,-0.41,SPY,0.67,0.64,0.38,0.60
4,A,2025-11-21 09:31:00,144.645004,144.645004,144.645004,144.645004,2500.0,2025-11-21,144.47,145.06,-0.29,SPY,0.67,0.64,0.49,0.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AA,2025-12-05 14:32:00,43.915100,43.935001,43.900002,43.930698,5212.0,2025-12-05,44.25,44.00,-0.19,GDX,0.80,0.58,-0.39,1.94
21146,AA,2025-12-05 14:33:00,43.935001,43.939999,43.906601,43.910000,6096.0,2025-12-05,44.25,44.00,-0.15,GDX,0.80,0.58,-0.44,1.94
21147,AA,2025-12-05 14:34:00,43.910000,43.910999,43.900002,43.910000,9171.0,2025-12-05,44.25,44.00,-0.20,GDX,0.80,0.58,-0.37,1.94
21148,AA,2025-12-05 14:35:00,43.910000,43.939999,43.900002,43.900002,8176.0,2025-12-05,44.25,44.00,-0.20,GDX,0.80,0.58,-0.36,1.94
21149,AA,2025-12-05 14:36:00,43.900002,43.919998,43.900002,43.915600,8041.0,2025-12-05,44.25,44.00,-0.23,GDX,0.80,0.58,-0.36,1.94

In [51]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [52]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=7.0s

[batch   10] rows=20,000,000  elapsed=13.9s

[batch   15] rows=30,000,000  elapsed=20.8s

[batch   20] rows=40,000,000  elapsed=27.7s

[batch   25] rows=50,000,000  elapsed=34.6s

[batch   30] rows=60,000,000  elapsed=41.4s

[batch   35] rows=70,000,000  elapsed=48.3s

[batch   40] rows=79,478,082  elapsed=54.9s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_36624_1771803386 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=6,614 | has_date=True has_dt=True

  [   200/6,614] AKAN  written=2,507,897  elapsed=15.8s

  [   400/6,614] ARDT  written=4,973,686  elapsed=31.5s

  [   600/6,614] BABX  written=7,570,851  elapsed=47.7s

  [   800/6,614] BLCN  written=9,781,774  elapsed=63.1s

  [  1000/6,614] BWX  written=12,061,572  elapsed=78.6s

  [  1200/6,614] CIB  written=14,458,684  elapsed=94.2s

  [  1400/6,614] CRAK  written=16,716,918  elapsed=109.7s

  [  1600/6,614] DDC  written=19,206,771  elapsed=126.7s

  [  1800/6,614] EBON  written=21,535,177  elapsed=146.8s

  [  2000/6,614] ETN  written=23,784,432  elapsed=166.9s

  [  2200/6,614] FIVY  written=26,108,844  elapsed=187.0s

  [  2400/6,614] GEND  written=28,443,084  elapsed=207.2s

  [  2600/6,614] GV  written=30,854,789  elapsed=227.7s

  [  2800/6,614] HYLB  written=33,051,633  elapsed=248.2s

  [  3000/6,614] INV  written=35,283,707  elapsed=268.4s

  [  3200/6,614] JNK  written=37,851,900  elapsed=289.2s

  [  3400/6,614] LCFY  written=40,154,645  elapsed=309.5s

  [  3600/6,614] MANH  written=42,224,691  elapsed=329.7s

  [  3800/6,614] MPLX  written=44,428,294  elapsed=350.1s

  [  4000/6,614] NFG  written=46,927,586  elapsed=370.2s

  [  4200/6,614] OARK  written=49,495,494  elapsed=392.3s

  [  4400/6,614] PB  written=52,142,019  elapsed=414.4s

  [  4600/6,614] PRE  written=54,583,580  elapsed=436.1s

  [  4800/6,614] RCON  written=57,030,050  elapsed=457.4s

  [  5000/6,614] RZLV  written=59,593,163  elapsed=479.1s

  [  5200/6,614] SINT  written=62,086,376  elapsed=500.4s

  [  5400/6,614] SPHY  written=64,673,996  elapsed=517.9s

  [  5600/6,614] TATT  written=67,140,531  elapsed=535.3s

  [  5800/6,614] TRNS  written=69,519,133  elapsed=552.4s

  [  6000/6,614] URAN  written=72,228,149  elapsed=570.0s

  [  6200/6,614] VRNT  written=74,774,193  elapsed=587.6s

  [  6400/6,614] WTW  written=77,094,127  elapsed=604.8s

  [  6600/6,614] ZSPC  written=79,337,960  elapsed=619.4s

✅ SORT DONE: 79,478,082 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=620.4s
✅ DONE: 79,478,082 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=679.7s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'

In [53]:
import pyarrow.dataset as ds

path = str(FINAL_PATH)

ticker = "AAPL"

dataset = ds.dataset(path, format="parquet")

table = dataset.to_table(
    filter=(ds.field("ticker") == ticker)
)

df = table.to_pandas()

# якщо є date + dt — відсортуємо, щоб це були саме "перші" по часу
if {"date", "dt"}.issubset(df.columns):
    df = df.sort_values(["date", "dt"])

display(df)

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma,t_p,deviation,dev_sig
0,AAPL,2025-11-21 00:00:00,267.489990,267.540009,267.480011,267.540009,278.0,2025-11-21,265.94,266.38,0.42,SPY,0.62,0.35,0.35,0.52,0.15,-0.20,-0.390385
1,AAPL,2025-11-21 00:01:00,267.540009,267.890015,267.470001,267.670013,503.0,2025-11-21,265.94,266.38,0.44,SPY,0.62,0.35,0.40,0.52,0.15,-0.25,-0.473077
2,AAPL,2025-11-21 00:02:00,267.670013,267.670013,267.670013,267.670013,63.0,2025-11-21,265.94,266.38,0.48,SPY,0.62,0.35,0.43,0.52,0.17,-0.26,-0.503846
3,AAPL,2025-11-21 00:03:00,267.670013,267.670013,267.670013,267.670013,52.0,2025-11-21,265.94,266.38,0.48,SPY,0.62,0.35,0.38,0.52,0.17,-0.21,-0.407692
4,AAPL,2025-11-21 00:04:00,267.670013,267.670013,267.399994,267.399994,42.0,2025-11-21,265.94,266.38,0.48,SPY,0.62,0.35,0.37,0.52,0.17,-0.20,-0.388462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52087,AAPL,2026-01-29 19:55:00,259.690002,259.708710,259.690002,259.700012,9077.0,2026-01-29,258.00,256.44,1.27,SPY,0.62,0.35,-0.39,0.52,0.44,0.83,1.604808
52088,AAPL,2026-01-29 19:56:00,259.700012,260.000000,259.700012,259.809998,4182.0,2026-01-29,258.00,256.44,1.27,SPY,0.62,0.35,-0.38,0.52,0.44,0.82,1.585577
52089,AAPL,2026-01-29 19:57:00,259.809998,259.809998,259.747009,259.769989,5486.0,2026-01-29,258.00,256.44,1.31,SPY,0.62,0.35,-0.38,0.52,0.46,0.84,1.612500
52090,AAPL,2026-01-29 19:58:00,259.779999,259.799988,259.659302,259.746002,6043.0,2026-01-29,258.00,256.44,1.30,SPY,0.62,0.35,-0.37,0.52,0.45,0.82,1.586538
52091,AAPL,2026-01-29 19:59:00,259.720001,259.799988,259.652405,259.682190,8158.0,2026-01-29,258.00,256.44,1.28,SPY,0.62,0.35,-0.38,0.52,0.45,0.83,1.592308