In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-07-19 00:00:00
end   = 2026-10-19 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-07-19
end_date_str   = 2026-10-19

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    82189.37
1     AA  1011825.55
2    AAA        0.00
3   AAAA        0.00
4   AAAB        0.00
Рядків: 13643

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
# market_cap ніде далі не використовується (єдина згадка — у 'fields' вище),
# тому він не має відсіювати тикери: рядок викидаємо лише якщо бракує ticker або lvl3
tickers_df = tickers_df.dropna(subset=["ticker", "lvl3"])

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,081 рядків

  ticker       value                         lvl3  market_cap
0      A    82189.37  Medical Equipment & Devices     47899.0
1     AA  1011825.55              Metals & Mining     10997.0
2   AAAU   307011.36                          NaN         NaN
3   AACG        8.80                     Software        33.0
4   AADX    57701.33          Aerospace & Defense      1863.0

In [7]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [8]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 60 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Investment Management',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Other Financial Services',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [9]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "IBIT"],
    "Banking": ["XLF", "KRE", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "IBIT"],
    "Insurance": ["XLF"],
    "Specialty Finance": ["XLF", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV"],
    "IT Services": ["QQQ"],
    "Semiconductors": ["SOXX", "DRAM"],
    "Technology Hardware": ["QQQ", "SOXX"],
    "Internet Media & Services": ["QQQ", "KWEB", "FXI"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "XRT"],
    "Cable & Satellite": ["SPY", "IWM"],
    "Telecommunications": ["QQQ"],
    "Publishing & Broadcasting": ["QQQ"],
    "Entertainment Content": ["QQQ", "ARKK"],
    "Advertising & Marketing": ["QQQ"],

    # --- Industrials ---
    "Aerospace & Defense": ["NASA", "ITA"],
    "Diversified Industrials": ["XLB", "IWM"],
    "Industrial Intermediate Prod": ["XLB", "IWM"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["XLB", "IWM"],
    "Machinery": ["XLB", "IWM"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["XLB", "IWM"],
    "Electrical Equipment": ["QQQ", "XLB"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XOP", "XLE", "UNG"],
    "Oil & Gas Supply Chain": ["XOP", "XLE", "UNG"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE"],
    "Electric Utilities": ["XLU"],
    "Gas & Water Utilities": ["XLU"],
    "Renewable Energy": ["XLE", "ARKK"],
    "Chemicals": ["XLB", "URA"],
    "Metals & Mining": ["GDX", "FCX", "COPX", "URA", "SLV"],
    "Steel": ["XLB", "GDX"],
    "Construction Materials": ["XLB", "IWM"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM"],

    # --- Health Care ---
    "Biotech & Pharma": ["XBI"],
    "Medical Equipment & Devices": ["XLV"],
    "Health Care Facilities & Svcs": ["XLV", "IWM"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP"],
    "Beverages": ["XLP"],
    "Household Products": ["XLP"],
    "Tobacco & Cannabis": ["XLP"],
    "Retail - Consumer Staples": ["XLP", "XRT"],
    "Wholesale - Consumer Staples": ["XLP"],

    "Retail - Discretionary": ["XRT", "IWM", "SPY"],
    "Wholesale - Discretionary": ["XRT", "IWM"],
    "Consumer Services": ["IWM", "SPY"],
    "Leisure Facilities & Services": ["IWM", "SPY"],
    "Leisure Products": ["XRT", "IWM"],
    "Apparel & Textile Products": ["XRT", "IWM"],
    "Automotive": ["QQQ", "IWM"],
    "Home & Office Products": ["XRT", "IWM"],
    "Home Construction": ["XLB", "IWM"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [10]:
# ------------------------------------------------

In [11]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [12]:
# Кеш сирого фетчу. /daily/gaps і /reports тягнулись ДВІЧІ за прогін — тут і в
# комірці 42 — тобто ~14 500 зайвих запитів, і саме вони й провокували 429.
# Складаємо результат ДО відкидання викидів: комірка 42 рахує sigma на СИРИХ
# гепах, і підстановка вже обрізаних занизила б її.
CRACEN_FETCH_CACHE = {}


def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
    max_workers_net=8,        # 64 потоки без пауз давали суцільні 429
    max_fail_ratio=0.15,      # 4.4% остаточних відмов виміряно як НОРМУ для цього
                              # API навіть з retry; бар упритул до норми валив би
                              # прогін через раз. Ловить справжню відмову, не шум.
):
    import random
    import time
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    _fails = {"gaps": 0, "reports": 0}

    def _request_with_retry(endpoint, params, *, max_retries=6, backoff=0.5):
        """Повторює запит при 429/мережевих збоях з наростаючою паузою.
        Той самий підхід, що в /intraday/v3. Вичерпавши спроби — кидає
        останній виняток, який ловить виклик вище."""
        for attempt in range(max_retries + 1):
            try:
                return DatumApi.data_request(endpoint, params)
            except Exception:
                if attempt == max_retries:
                    raise
                time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))

    def _fetch_gap(t):
        try:
            dfg = _request_with_retry("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            _fails["gaps"] += 1
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = _request_with_retry("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            _fails["reports"] += 1
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(max_workers_net,
                                            len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    _total = len(gap_futs) + len(rep_futs)
    _failed = _fails["gaps"] + _fails["reports"]
    if _total and _failed / _total > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_failed} з {_total} запитів "
            f"({_failed / _total * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Далі вийшла б порожня або обрізана мапа bench/corr/beta."
        )

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    CRACEN_FETCH_CACHE.clear()
    CRACEN_FETCH_CACHE.update({
        "window": (s_date, e_date),
        "last_n_reports": int(last_n_reports),
        "tickers": set(stocks),
        "gaps": stock_gaps.copy(),      # сирі, до drop anomalies нижче
        "reports": reports.copy(),
    })

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [13]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7081 etfs=28 window=2026-07-19..2026-10-19

DONE pairs: 6982 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 6982 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: Investment Management, Other Financial Services, UNKNOWN
  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.021689  0.017864  Advertising & Marketing         51
1     AEHL      QQQ  0.058603  0.323705  Advertising & Marketing         52
2      APP      QQQ  0.138698  0.141347  Advertising & Marketing         51
3     BAOS      QQQ  0.022066  0.062201  Advertising & Marketing         52
4     CDLX      QQQ  0.229004  0.261438  Advertising & Marketing         51
Rows in raw stock-etf pairs: 15665
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           QQQ   0.021689        0.017864  Advertising & Marketing
1     AEHL           QQQ   0.058603        0.323705  Advertising & Marketing
2      APP           QQQ   0.138698        0.141347  Advertising & Marketing
3     BAOS           QQQ   0.022066        0.062201  Advertising & Marketing
4     CDLX           QQQ   0.229004        0.261438  Advertising & Marketing

   n_overlap
0         51
1         52
2         51
3         52
4         51
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [14]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [15]:
TICKERS

     ticker       value                         lvl3  market_cap
0         A    82189.37  Medical Equipment & Devices     47899.0
1        AA  1011825.55              Metals & Mining     10997.0
2      AAAU   307011.36                          NaN         NaN
3      AACG        8.80                     Software        33.0
4      AADX    57701.33          Aerospace & Defense      1863.0
...     ...         ...                          ...         ...
7076   ZVOL     5135.13                          NaN         NaN
7077   ZVRA     6265.09             Biotech & Pharma       603.0
7078    ZWS     1218.54                    Machinery      7815.0
7079   ZYBT     5320.26             Biotech & Pharma        43.0
7080   ZYME    42810.47             Biotech & Pharma      1826.0

[7081 rows x 4 columns]

In [16]:
import pandas as pd

# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0    ARKK
1    COPX
2    DRAM
3     FCX
4     FXI
5     GDX
6    IBIT
7     IGV
8     ITA
9     IWM
10    KRE
11   KWEB
12   NASA
13    QQQ
14    SLV
15   SOXX
16    SPY
17    UNG
18    URA
19    XBI
20    XLB
21    XLE
22    XLF
23    XLP
24    XLU
25    XLV
26    XOP
27    XRT

In [17]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=16,
    parallel_tickers=True,
    max_workers_tickers=16,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 7081 тікерів (пропущено 0 по старому маніфесту) | 2026-07-19 00:00:00 → 2026-10-19 23:59:59 | interval=1 | next batch #20378 | run=782c5022

   workers: tickers=16, chunks=16 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-07-19 → 2026-10-18 (92 днів)

   📈 обробляються дні: 2026-10-19 → 2026-10-19 (1 днів)

   psutil · старт · 🧠 RAM: 319.3 MB

[10/7081] ✓ AAOZ: 552 рядків |   0.14% | ETA 23:49

[20/7081] ✓ AAPG: 9 рядків |   0.28% | ETA 19:56

[30/7081] ✓ ABAT: 444 рядків |   0.42% | ETA 19:07

[40/7081] ✓ ABG: 249 рядків |   0.56% | ETA 18:52

[50/7081] ✓ ACAD: 382 рядків |   0.71% | ETA 18:37

   • RAM · 🧠 RAM: 345.6 MB

   ⏳ перед flush · 🧠 RAM: 345.6 MB

💾 batch 20378 → 17,263 рядків (всього 17,263 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20378.csv.gz

   ✅ після flush · 🧠 RAM: 351.8 MB

[60/7081] ✓ ACHC: 286 рядків |   0.85% | ETA 18:47

[70/7081] ✓ ACON: 21 рядків |   0.99% | ETA 19:30

[80/7081] ✓ ACT: 162 рядків |   1.13% | ETA 19:18

[90/7081] ✓ ADBG: 231 рядків |   1.27% | ETA 19:08

[100/7081] ✓ ADM: 399 рядків |   1.41% | ETA 18:51

   • RAM · 🧠 RAM: 350.6 MB

   ⏳ перед flush · 🧠 RAM: 350.6 MB

💾 batch 20379 → 12,092 рядків (всього 29,355 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20379.csv.gz

   ✅ після flush · 🧠 RAM: 355.1 MB

[110/7081] ✓ ADUR: 186 рядків |   1.55% | ETA 19:20

[120/7081] ✓ AEHG: 461 рядків |   1.69% | ETA 19:09

[130/7081] ✓ AEXA: 58 рядків |   1.84% | ETA 19:11

[140/7081] ✓ AFK: 19 рядків |   1.98% | ETA 19:03

[150/7081] ✓ AGIO: 381 рядків |   2.12% | ETA 18:53

   • RAM · 🧠 RAM: 357.0 MB

   ⏳ перед flush · 🧠 RAM: 357.0 MB

💾 batch 20380 → 13,124 рядків (всього 42,479 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20380.csv.gz

   ✅ після flush · 🧠 RAM: 359.4 MB

[160/7081] ✓ AGM: 74 рядків |   2.26% | ETA 18:50

[170/7081] ✓ AIB: 217 рядків |   2.40% | ETA 18:47

[180/7081] ✓ AIDX: 68 рядків |   2.54% | ETA 18:45

[190/7081] ✓ AIMD: 47 рядків |   2.68% | ETA 18:41

[200/7081] ✓ AIP: 275 рядків |   2.82% | ETA 18:41

   • RAM · 🧠 RAM: 358.6 MB

   ⏳ перед flush · 🧠 RAM: 358.6 MB

💾 batch 20381 → 9,373 рядків (всього 51,852 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20381.csv.gz

   ✅ після flush · 🧠 RAM: 361.2 MB

[210/7081] ✓ AIS: 299 рядків |   2.97% | ETA 18:42

[220/7081] ✓ AKBA: 391 рядків |   3.11% | ETA 18:41

[230/7081] ✓ ALB: 424 рядків |   3.25% | ETA 18:40

[240/7081] ✓ ALGS: 70 рядків |   3.39% | ETA 18:26

[250/7081] ✓ ALKT: 356 рядків |   3.53% | ETA 18:23

   • RAM · 🧠 RAM: 360.6 MB

   ⏳ перед flush · 🧠 RAM: 360.6 MB

💾 batch 20382 → 12,834 рядків (всього 64,686 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20382.csv.gz

   ✅ після flush · 🧠 RAM: 362.9 MB

[260/7081] ✓ ALOY: 445 рядків |   3.67% | ETA 18:29

[270/7081] ✓ ALTG: 130 рядків |   3.81% | ETA 18:26

[280/7081] ✓ AMAT: 894 рядків |   3.95% | ETA 18:14

[290/7081] ✓ AMCR: 397 рядків |   4.10% | ETA 18:09

[300/7081] ✓ AMLP: 388 рядків |   4.24% | ETA 18:07

   • RAM · 🧠 RAM: 364.2 MB

   ⏳ перед flush · 🧠 RAM: 364.2 MB

💾 batch 20383 → 14,447 рядків (всього 79,133 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20383.csv.gz

   ✅ після flush · 🧠 RAM: 364.9 MB

[310/7081] – AMPGR: empty |   4.38% | ETA 18:16

[320/7081] ✓ AMSF: 146 рядків |   4.52% | ETA 18:19

[330/7081] ✓ AMRZ: 411 рядків |   4.66% | ETA 18:11

[340/7081] ✓ AMZO: 34 рядків |   4.80% | ETA 18:08

[350/7081] ✓ ANF: 383 рядків |   4.94% | ETA 18:04

   • RAM · 🧠 RAM: 370.9 MB

   ⏳ перед flush · 🧠 RAM: 370.9 MB

💾 batch 20384 → 12,627 рядків (всього 91,760 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20384.csv.gz

   ✅ після flush · 🧠 RAM: 373.5 MB

[360/7081] ✓ ANGX: 364 рядків |   5.08% | ETA 18:09

[370/7081] ✓ ANTX: 144 рядків |   5.23% | ETA 18:07

[380/7081] ✓ AOSL: 351 рядків |   5.37% | ETA 18:05

[390/7081] – APGE: empty |   5.51% | ETA 18:02

[400/7081] ✓ APO: 384 рядків |   5.65% | ETA 17:57

   • RAM · 🧠 RAM: 375.1 MB

   ⏳ перед flush · 🧠 RAM: 375.1 MB

💾 batch 20385 → 11,403 рядків (всього 103,163 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20385.csv.gz

   ✅ після flush · 🧠 RAM: 376.1 MB

[410/7081] ✓ APRE: 86 рядків |   5.79% | ETA 18:00

[420/7081] ✓ AR: 401 рядків |   5.93% | ETA 17:58

[430/7081] ✓ ARCC: 419 рядків |   6.07% | ETA 17:55

[440/7081] ✓ ARKB: 369 рядків |   6.21% | ETA 17:57

[450/7081] ✓ ARKY: 43 рядків |   6.36% | ETA 17:59

   • RAM · 🧠 RAM: 377.7 MB

   ⏳ перед flush · 🧠 RAM: 377.7 MB

💾 batch 20386 → 12,271 рядків (всього 115,434 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20386.csv.gz

   ✅ після flush · 🧠 RAM: 379.1 MB

[460/7081] – ARQQW: empty |   6.50% | ETA 18:05

[470/7081] ✓ ARVN: 298 рядків |   6.64% | ETA 18:03

[480/7081] ✓ AS: 402 рядків |   6.78% | ETA 17:59

[490/7081] ✓ ASMG: 79 рядків |   6.92% | ETA 17:55

[500/7081] ✓ ASTC: 45 рядків |   7.06% | ETA 17:50

   • RAM · 🧠 RAM: 380.9 MB

   ⏳ перед flush · 🧠 RAM: 380.9 MB

💾 batch 20387 → 13,004 рядків (всього 128,438 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20387.csv.gz

   ✅ після flush · 🧠 RAM: 381.8 MB

[510/7081] ✓ ASTY: 138 рядків |   7.20% | ETA 17:52

[520/7081] ✓ ATEC: 390 рядків |   7.34% | ETA 17:48

[530/7081] ✓ ATHE: 31 рядків |   7.48% | ETA 17:46

[540/7081] ✓ ATOS: 64 рядків |   7.63% | ETA 17:42

[550/7081] ✓ AU: 423 рядків |   7.77% | ETA 17:38

   • RAM · 🧠 RAM: 383.5 MB

   ⏳ перед flush · 🧠 RAM: 383.5 MB

💾 batch 20388 → 9,019 рядків (всього 137,457 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20388.csv.gz

   ✅ після flush · 🧠 RAM: 384.4 MB

[560/7081] ✓ AUTL: 368 рядків |   7.91% | ETA 17:41

[570/7081] ✓ AVES: 96 рядків |   8.05% | ETA 17:36

[580/7081] ✓ AVGU: 134 рядків |   8.19% | ETA 17:34

[590/7081] ✓ AVMV: 61 рядків |   8.33% | ETA 17:32

[600/7081] ✓ AVTX: 373 рядків |   8.47% | ETA 17:31

   • RAM · 🧠 RAM: 385.9 MB

   ⏳ перед flush · 🧠 RAM: 385.9 MB

💾 batch 20389 → 11,541 рядків (всього 148,998 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20389.csv.gz

   ✅ після flush · 🧠 RAM: 396.5 MB

[610/7081] ✓ AVRE: 72 рядків |   8.61% | ETA 17:38

[620/7081] ✓ AXG: 533 рядків |   8.76% | ETA 17:37

[630/7081] ✓ AXTL: 435 рядків |   8.90% | ETA 17:36

[640/7081] ✓ AZTA: 301 рядків |   9.04% | ETA 17:33

[650/7081] ✓ BABA: 823 рядків |   9.18% | ETA 17:32

   • RAM · 🧠 RAM: 392.3 MB

   ⏳ перед flush · 🧠 RAM: 392.3 MB

💾 batch 20390 → 12,952 рядків (всього 161,950 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20390.csv.gz

   ✅ після flush · 🧠 RAM: 397.0 MB

[660/7081] ✓ BAM: 394 рядків |   9.32% | ETA 17:34

[670/7081] ✓ BANL: 48 рядків |   9.46% | ETA 17:31

[680/7081] ✓ BBC: 199 рядків |   9.60% | ETA 17:29

[690/7081] ✓ BBH: 28 рядків |   9.74% | ETA 17:26

[700/7081] ✓ BBT: 273 рядків |   9.89% | ETA 17:25

   • RAM · 🧠 RAM: 398.5 MB

   ⏳ перед flush · 🧠 RAM: 398.5 MB

💾 batch 20391 → 11,331 рядків (всього 173,281 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20391.csv.gz

   ✅ після flush · 🧠 RAM: 399.8 MB

[710/7081] ✓ BCAT: 282 рядків |  10.03% | ETA 17:26

[720/7081] ✓ BCIC: 53 рядків |  10.17% | ETA 17:23

[730/7081] ✓ BCYC: 312 рядків |  10.31% | ETA 17:22

[740/7081] ✓ BDVG: 4 рядків |  10.45% | ETA 17:21

[750/7081] ✓ BEAT: 247 рядків |  10.59% | ETA 17:20

   • RAM · 🧠 RAM: 401.5 MB

   ⏳ перед flush · 🧠 RAM: 401.5 MB

💾 batch 20392 → 10,430 рядків (всього 183,711 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20392.csv.gz

   ✅ після flush · 🧠 RAM: 401.7 MB

[760/7081] ✓ BERZ: 60 рядків |  10.73% | ETA 17:20

[770/7081] ✓ BFC: 34 рядків |  10.87% | ETA 17:19

[780/7081] ✓ BGL: 218 рядків |  11.02% | ETA 17:17

[790/7081] ✓ BHB: 63 рядків |  11.16% | ETA 17:16

[800/7081] ✓ BIB: 7 рядків |  11.30% | ETA 17:17

   • RAM · 🧠 RAM: 403.5 MB

   ⏳ перед flush · 🧠 RAM: 403.5 MB

💾 batch 20393 → 9,633 рядків (всього 193,344 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20393.csv.gz

   ✅ після flush · 🧠 RAM: 403.7 MB

[810/7081] ✓ BILS: 200 рядків |  11.44% | ETA 17:18

[820/7081] ✓ BITA: 35 рядків |  11.58% | ETA 17:17

[830/7081] ✓ BJDX: 59 рядків |  11.72% | ETA 17:17

[840/7081] ✓ BKIE: 89 рядків |  11.86% | ETA 17:13

[850/7081] ✓ BL: 328 рядків |  12.00% | ETA 17:13

   • RAM · 🧠 RAM: 405.1 MB

   ⏳ перед flush · 🧠 RAM: 405.1 MB

💾 batch 20394 → 13,785 рядків (всього 207,129 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20394.csv.gz

   ✅ після flush · 🧠 RAM: 405.4 MB

[860/7081] ✓ BLLN: 226 рядків |  12.15% | ETA 17:14

[870/7081] ✓ BLSG: 39 рядків |  12.29% | ETA 17:13

[880/7081] ✓ BMI: 198 рядків |  12.43% | ETA 17:11

[890/7081] ✓ BMNZ: 558 рядків |  12.57% | ETA 17:09

[900/7081] ✓ BN: 418 рядків |  12.71% | ETA 17:08

   • RAM · 🧠 RAM: 405.9 MB

   ⏳ перед flush · 🧠 RAM: 405.9 MB

💾 batch 20395 → 13,210 рядків (всього 220,339 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20395.csv.gz

   ✅ після flush · 🧠 RAM: 408.7 MB

[910/7081] ✓ BNO: 523 рядків |  12.85% | ETA 17:09

[920/7081] ✓ BON: 17 рядків |  12.99% | ETA 17:08

[930/7081] ✓ BOXL: 19 рядків |  13.13% | ETA 17:05

[940/7081] ✓ BRAI: 43 рядків |  13.27% | ETA 17:04

[950/7081] ✓ BRLS: 7 рядків |  13.42% | ETA 17:02

   • RAM · 🧠 RAM: 414.9 MB

   ⏳ перед flush · 🧠 RAM: 414.7 MB

💾 batch 20396 → 10,552 рядків (всього 230,891 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20396.csv.gz

   ✅ після flush · 🧠 RAM: 417.6 MB

[960/7081] ✓ BRSL: 386 рядків |  13.56% | ETA 17:03

[970/7081] ✓ BSEM: 151 рядків |  13.70% | ETA 17:01

[980/7081] ✓ BSRR: 44 рядків |  13.84% | ETA 16:59

[990/7081] ✓ BTCC: 23 рядків |  13.98% | ETA 16:57

[1000/7081] ✓ BTCS: 183 рядків |  14.12% | ETA 16:55

   • RAM · 🧠 RAM: 418.5 MB

   ⏳ перед flush · 🧠 RAM: 418.5 MB

💾 batch 20397 → 9,886 рядків (всього 240,777 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20397.csv.gz

   ✅ після flush · 🧠 RAM: 418.6 MB

[1010/7081] ✓ BTGO: 355 рядків |  14.26% | ETA 16:57

[1020/7081] ✓ BULG: 7 рядків |  14.40% | ETA 16:55

[1030/7081] ✓ BURU: 700 рядків |  14.55% | ETA 16:53

[1040/7081] ✓ BVS: 184 рядків |  14.69% | ETA 16:52

[1050/7081] ✓ BXBL: 64 рядків |  14.83% | ETA 16:52

   • RAM · 🧠 RAM: 417.1 MB

   ⏳ перед flush · 🧠 RAM: 417.1 MB

💾 batch 20398 → 12,130 рядків (всього 252,907 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20398.csv.gz

   ✅ після flush · 🧠 RAM: 418.4 MB

[1060/7081] ✓ BZFD: 77 рядків |  14.97% | ETA 16:53

[1070/7081] ✓ CABO: 329 рядків |  15.11% | ETA 16:51

[1080/7081] ✓ CAH: 352 рядків |  15.25% | ETA 16:50

[1090/7081] ✓ CANE: 163 рядків |  15.39% | ETA 16:48

[1100/7081] ✓ CARG: 334 рядків |  15.53% | ETA 16:47

   • RAM · 🧠 RAM: 409.5 MB

   ⏳ перед flush · 🧠 RAM: 409.5 MB

💾 batch 20399 → 12,685 рядків (всього 265,592 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20399.csv.gz

   ✅ після flush · 🧠 RAM: 409.8 MB

[1110/7081] ✓ CASS: 63 рядків |  15.68% | ETA 16:49

[1120/7081] ✓ CBIO: 155 рядків |  15.82% | ETA 16:47

[1130/7081] ✓ CBRE: 379 рядків |  15.96% | ETA 16:47

[1140/7081] ✓ CBZ: 338 рядків |  16.10% | ETA 16:48

[1150/7081] ✓ CCEP: 379 рядків |  16.24% | ETA 16:45

   • RAM · 🧠 RAM: 411.3 MB

   ⏳ перед flush · 🧠 RAM: 411.3 MB

💾 batch 20400 → 11,550 рядків (всього 277,142 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20400.csv.gz

   ✅ після flush · 🧠 RAM: 411.8 MB

[1160/7081] – CCO: empty |  16.38% | ETA 16:46

[1170/7081] ✓ CDLX: 59 рядків |  16.52% | ETA 16:45

[1180/7081] ✓ CDZI: 336 рядків |  16.66% | ETA 16:43

[1190/7081] ✓ CELH: 490 рядків |  16.81% | ETA 16:42

[1200/7081] ✓ CERY: 92 рядків |  16.95% | ETA 16:41

   • RAM · 🧠 RAM: 413.5 MB

   ⏳ перед flush · 🧠 RAM: 413.5 MB

💾 batch 20401 → 10,938 рядків (всього 288,080 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20401.csv.gz

   ✅ після flush · 🧠 RAM: 415.2 MB

[1210/7081] ✓ CGAU: 372 рядків |  17.09% | ETA 16:41

[1220/7081] ✓ CGDG: 314 рядків |  17.23% | ETA 16:39

[1230/7081] ✓ CGMS: 318 рядків |  17.37% | ETA 16:37

[1240/7081] ✓ CHAD: 38 рядків |  17.51% | ETA 16:36

[1250/7081] ✓ CHCT: 239 рядків |  17.65% | ETA 16:34

   • RAM · 🧠 RAM: 414.1 MB

   ⏳ перед flush · 🧠 RAM: 414.2 MB

💾 batch 20402 → 12,310 рядків (всього 300,390 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20402.csv.gz

   ✅ після flush · 🧠 RAM: 416.1 MB

[1260/7081] ✓ CHPT: 281 рядків |  17.79% | ETA 16:35

[1270/7081] ✓ CHSN: 54 рядків |  17.94% | ETA 16:33

[1280/7081] ✓ CIBR: 451 рядків |  18.08% | ETA 16:31

[1290/7081] ✓ CIM: 371 рядків |  18.22% | ETA 16:30

[1300/7081] ✓ CJMB: 42 рядків |  18.36% | ETA 16:28

   • RAM · 🧠 RAM: 409.9 MB

   ⏳ перед flush · 🧠 RAM: 409.9 MB

💾 batch 20403 → 11,624 рядків (всього 312,014 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20403.csv.gz

   ✅ після flush · 🧠 RAM: 414.1 MB

[1310/7081] ✓ CLF: 759 рядків |  18.50% | ETA 16:29

[1320/7081] ✓ CLM: 395 рядків |  18.64% | ETA 16:27

[1330/7081] ✓ CLWT: 60 рядків |  18.78% | ETA 16:25

[1340/7081] ✓ CMCL: 157 рядків |  18.92% | ETA 16:23

[1350/7081] ✓ CMRC: 180 рядків |  19.07% | ETA 16:22

   • RAM · 🧠 RAM: 415.2 MB

   ⏳ перед flush · 🧠 RAM: 415.2 MB

💾 batch 20404 → 11,961 рядків (всього 323,975 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20404.csv.gz

   ✅ після flush · 🧠 RAM: 416.3 MB

[1360/7081] ✓ CMG: 570 рядків |  19.21% | ETA 16:22

[1370/7081] ✓ CNH: 400 рядків |  19.35% | ETA 16:21

[1380/7081] ✓ CNR: 238 рядків |  19.49% | ETA 16:18

[1390/7081] ✓ CNTX: 286 рядків |  19.63% | ETA 16:17

[1400/7081] ✓ CODA: 63 рядків |  19.77% | ETA 16:15

   • RAM · 🧠 RAM: 417.1 MB

   ⏳ перед flush · 🧠 RAM: 417.1 MB

💾 batch 20405 → 10,540 рядків (всього 334,515 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20405.csv.gz

   ✅ після flush · 🧠 RAM: 418.2 MB

[1410/7081] ✓ COIG: 100 рядків |  19.91% | ETA 16:15

[1420/7081] ✓ COMP: 388 рядків |  20.05% | ETA 16:14

[1430/7081] ✓ COMT: 121 рядків |  20.19% | ETA 16:12

[1440/7081] ✓ COR: 391 рядків |  20.34% | ETA 16:11

[1450/7081] ✓ COYA: 111 рядків |  20.48% | ETA 16:10

   • RAM · 🧠 RAM: 408.0 MB

   ⏳ перед flush · 🧠 RAM: 408.0 MB

💾 batch 20406 → 14,908 рядків (всього 349,423 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20406.csv.gz

   ✅ після flush · 🧠 RAM: 407.9 MB

[1460/7081] ✓ CPER: 316 рядків |  20.62% | ETA 16:12

[1470/7081] ✓ CPT: 312 рядків |  20.76% | ETA 16:11

[1480/7081] ✓ CRAI: 73 рядків |  20.90% | ETA 16:10

[1490/7081] ✓ CRCL: 1,074 рядків |  21.04% | ETA 16:09

[1500/7081] ✓ CRF: 380 рядків |  21.18% | ETA 16:07

   • RAM · 🧠 RAM: 409.6 MB

   ⏳ перед flush · 🧠 RAM: 409.6 MB

💾 batch 20407 → 12,179 рядків (всього 361,602 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20407.csv.gz

   ✅ після flush · 🧠 RAM: 411.0 MB

[1510/7081] ✓ CRM: 513 рядків |  21.32% | ETA 16:08

[1520/7081] ✓ CRTO: 92 рядків |  21.47% | ETA 16:06

[1530/7081] ✓ CRVL: 104 рядків |  21.61% | ETA 16:05

[1540/7081] – CSAN: empty |  21.75% | ETA 16:03

[1550/7081] ✓ CSGP: 407 рядків |  21.89% | ETA 16:02

   • RAM · 🧠 RAM: 410.1 MB

   ⏳ перед flush · 🧠 RAM: 410.1 MB

💾 batch 20408 → 13,471 рядків (всього 375,073 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20408.csv.gz

   ✅ після flush · 🧠 RAM: 410.9 MB

[1560/7081] ✓ CSV: 145 рядків |  22.03% | ETA 16:01

[1570/7081] ✓ CTKB: 328 рядків |  22.17% | ETA 16:00

[1580/7081] ✓ CTRI: 355 рядків |  22.31% | ETA 15:59

[1590/7081] ✓ CURE: 61 рядків |  22.45% | ETA 15:58

[1600/7081] ✓ CVBF: 324 рядків |  22.60% | ETA 15:56

   • RAM · 🧠 RAM: 410.3 MB

   ⏳ перед flush · 🧠 RAM: 410.3 MB

💾 batch 20409 → 11,121 рядків (всього 386,194 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20409.csv.gz

   ✅ після flush · 🧠 RAM: 413.3 MB

[1610/7081] ✓ CWB: 220 рядків |  22.74% | ETA 15:55

[1620/7081] ✓ CWEB: 334 рядків |  22.88% | ETA 15:54

[1630/7081] ✓ CXSE: 7 рядків |  23.02% | ETA 15:53

[1640/7081] ✓ CZFS: 23 рядків |  23.16% | ETA 15:52

[1650/7081] ✓ D: 401 рядків |  23.30% | ETA 15:51

   • RAM · 🧠 RAM: 415.1 MB

   ⏳ перед flush · 🧠 RAM: 415.1 MB

💾 batch 20410 → 11,305 рядків (всього 397,499 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20410.csv.gz

   ✅ після flush · 🧠 RAM: 416.6 MB

[1660/7081] ✓ DAPP: 224 рядків |  23.44% | ETA 15:51

[1670/7081] ✓ DBI: 193 рядків |  23.58% | ETA 15:49

[1680/7081] ✓ DCI: 222 рядків |  23.73% | ETA 15:47

[1690/7081] ✓ DCX: 181 рядків |  23.87% | ETA 15:46

[1700/7081] ✓ DECK: 403 рядків |  24.01% | ETA 15:44

   • RAM · 🧠 RAM: 415.5 MB

   ⏳ перед flush · 🧠 RAM: 415.5 MB

💾 batch 20411 → 11,196 рядків (всього 408,695 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20411.csv.gz

   ✅ після flush · 🧠 RAM: 416.7 MB

[1710/7081] ✓ DERM: 148 рядків |  24.15% | ETA 15:44

[1720/7081] ✓ DFCF: 324 рядків |  24.29% | ETA 15:43

[1730/7081] ✓ DFIV: 360 рядків |  24.43% | ETA 15:41

[1740/7081] ✓ DFUS: 279 рядків |  24.57% | ETA 15:40

[1750/7081] ✓ DGRO: 416 рядків |  24.71% | ETA 15:39

   • RAM · 🧠 RAM: 415.7 MB

   ⏳ перед flush · 🧠 RAM: 415.7 MB

💾 batch 20412 → 12,341 рядків (всього 421,036 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20412.csv.gz

   ✅ після flush · 🧠 RAM: 417.8 MB

[1760/7081] ✓ DIV: 166 рядків |  24.86% | ETA 15:40

[1770/7081] ✓ DJD: 67 рядків |  25.00% | ETA 15:41

[1780/7081] ✓ DKS: 391 рядків |  25.14% | ETA 15:39

[1790/7081] ✓ DNOW: 393 рядків |  25.28% | ETA 15:38

[1800/7081] ✓ DON: 295 рядків |  25.42% | ETA 15:37

   • RAM · 🧠 RAM: 420.4 MB

   ⏳ перед flush · 🧠 RAM: 420.4 MB

💾 batch 20413 → 13,830 рядків (всього 434,866 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20413.csv.gz

   ✅ після flush · 🧠 RAM: 421.9 MB

[1810/7081] ✓ DORM: 108 рядків |  25.56% | ETA 15:37

[1820/7081] ✓ DOX: 280 рядків |  25.70% | ETA 15:37

[1830/7081] ✓ DRIV: 264 рядків |  25.84% | ETA 15:36

[1840/7081] ✓ DRMA: 354 рядків |  25.99% | ETA 15:34

[1850/7081] ✓ DSGN: 226 рядків |  26.13% | ETA 15:33

   • RAM · 🧠 RAM: 423.6 MB

   ⏳ перед flush · 🧠 RAM: 423.6 MB

💾 batch 20414 → 11,582 рядків (всього 446,448 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20414.csv.gz

   ✅ після flush · 🧠 RAM: 425.7 MB

[1860/7081] ✓ DTST: 9 рядків |  26.27% | ETA 15:33

[1870/7081] ✓ DUOT: 349 рядків |  26.41% | ETA 15:31

[1880/7081] ✓ DVN: 446 рядків |  26.55% | ETA 15:30

[1890/7081] ✓ DXD: 350 рядків |  26.69% | ETA 15:30

[1900/7081] ✓ EARN: 188 рядків |  26.83% | ETA 15:29

   • RAM · 🧠 RAM: 425.7 MB

   ⏳ перед flush · 🧠 RAM: 425.7 MB

💾 batch 20415 → 10,848 рядків (всього 457,296 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20415.csv.gz

   ✅ після flush · 🧠 RAM: 426.8 MB

[1910/7081] ✓ EBAY: 397 рядків |  26.97% | ETA 15:28

[1920/7081] ✓ ECHO: 410 рядків |  27.11% | ETA 15:27

[1930/7081] ✓ EDD: 264 рядків |  27.26% | ETA 15:27

[1940/7081] ✓ EEM: 459 рядків |  27.40% | ETA 15:27

[1950/7081] ✓ EFA: 416 рядків |  27.54% | ETA 15:26

   • RAM · 🧠 RAM: 426.9 MB

   ⏳ перед flush · 🧠 RAM: 427.0 MB

💾 batch 20416 → 10,049 рядків (всього 467,345 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20416.csv.gz

   ✅ після flush · 🧠 RAM: 428.4 MB

[1960/7081] ✓ EFX: 383 рядків |  27.68% | ETA 15:25

[1970/7081] ✓ EGY: 318 рядків |  27.82% | ETA 15:24

[1980/7081] ✓ EJH: 24 рядків |  27.96% | ETA 15:22

[1990/7081] ✓ ELIL: 49 рядків |  28.10% | ETA 15:20

[2000/7081] ✓ EMA: 287 рядків |  28.24% | ETA 15:19

   • RAM · 🧠 RAM: 418.1 MB

   ⏳ перед flush · 🧠 RAM: 418.1 MB

💾 batch 20417 → 10,307 рядків (всього 477,652 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20417.csv.gz

   ✅ після flush · 🧠 RAM: 417.1 MB

[2010/7081] ✓ EMEQ: 99 рядків |  28.39% | ETA 15:18

[2020/7081] ✓ EMQQ: 84 рядків |  28.53% | ETA 15:16

[2030/7081] ✓ ENOV: 373 рядків |  28.67% | ETA 15:15

[2040/7081] ✓ ENVX: 481 рядків |  28.81% | ETA 15:13

[2050/7081] ✓ EOSU: 342 рядків |  28.95% | ETA 15:12

   • RAM · 🧠 RAM: 415.9 MB

   ⏳ перед flush · 🧠 RAM: 415.9 MB

💾 batch 20418 → 11,788 рядків (всього 489,440 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20418.csv.gz

   ✅ після flush · 🧠 RAM: 417.9 MB

[2060/7081] ✓ EPSM: 43 рядків |  29.09% | ETA 15:12

[2070/7081] ✓ EQNR: 555 рядків |  29.23% | ETA 15:11

[2080/7081] ✓ ERNA: 39 рядків |  29.37% | ETA 15:10

[2090/7081] ✓ EROC: 427 рядків |  29.52% | ETA 15:08

[2100/7081] ✓ ESTC: 382 рядків |  29.66% | ETA 15:07

   • RAM · 🧠 RAM: 418.5 MB

   ⏳ перед flush · 🧠 RAM: 418.5 MB

💾 batch 20419 → 12,271 рядків (всього 501,711 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20419.csv.gz

   ✅ після flush · 🧠 RAM: 420.3 MB

[2110/7081] ✓ ETHW: 296 рядків |  29.80% | ETA 15:06

[2120/7081] ✓ ETS: 34 рядків |  29.94% | ETA 15:05

[2130/7081] ✓ EUO: 14 рядків |  30.08% | ETA 15:03

[2140/7081] – EVMU: empty |  30.22% | ETA 15:02

[2150/7081] ✓ EVTR: 343 рядків |  30.36% | ETA 15:01

   • RAM · 🧠 RAM: 423.2 MB

   ⏳ перед flush · 🧠 RAM: 423.2 MB

💾 batch 20420 → 13,098 рядків (всього 514,809 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20420.csv.gz

   ✅ після flush · 🧠 RAM: 424.3 MB

[2160/7081] ✓ EWM: 205 рядків |  30.50% | ETA 15:00

[2170/7081] ✓ EWW: 335 рядків |  30.65% | ETA 14:58

[2180/7081] ✓ EXLS: 382 рядків |  30.79% | ETA 14:57

[2190/7081] ✓ EYE: 332 рядків |  30.93% | ETA 14:56

[2200/7081] ✓ EZPW: 257 рядків |  31.07% | ETA 14:54

   • RAM · 🧠 RAM: 426.1 MB

   ⏳ перед flush · 🧠 RAM: 426.1 MB

💾 batch 20421 → 14,457 рядків (всього 529,266 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20421.csv.gz

   ✅ після flush · 🧠 RAM: 428.4 MB

[2210/7081] ✓ FANG: 379 рядків |  31.21% | ETA 14:54

[2220/7081] ✓ FBIN: 384 рядків |  31.35% | ETA 14:52

[2230/7081] ✓ FCBC: 85 рядків |  31.49% | ETA 14:51

[2240/7081] ✓ FCFS: 119 рядків |  31.63% | ETA 14:49

[2250/7081] ✓ FCX: 509 рядків |  31.78% | ETA 14:48

   • RAM · 🧠 RAM: 430.2 MB

   ⏳ перед flush · 🧠 RAM: 430.3 MB

💾 batch 20422 → 10,570 рядків (всього 539,836 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20422.csv.gz

   ✅ після flush · 🧠 RAM: 431.8 MB

[2260/7081] ✓ FDUS: 267 рядків |  31.92% | ETA 14:48

[2270/7081] ✓ FEM: 88 рядків |  32.06% | ETA 14:46

[2280/7081] ✓ FEPI: 206 рядків |  32.20% | ETA 14:44

[2290/7081] ✓ FFR: 180 рядків |  32.34% | ETA 14:43

[2300/7081] ✓ FHB: 381 рядків |  32.48% | ETA 14:41

   • RAM · 🧠 RAM: 433.6 MB

   ⏳ перед flush · 🧠 RAM: 433.6 MB

💾 batch 20423 → 10,706 рядків (всього 550,542 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20423.csv.gz

   ✅ після flush · 🧠 RAM: 435.5 MB

[2310/7081] ✓ FIDU: 180 рядків |  32.62% | ETA 14:39

[2320/7081] ✓ FISV: 414 рядків |  32.76% | ETA 14:37

[2330/7081] ✓ FJET: 342 рядків |  32.90% | ETA 14:34

[2340/7081] ✓ FLJH: 21 рядків |  33.05% | ETA 14:32

[2350/7081] ✓ FLOT: 380 рядків |  33.19% | ETA 14:30

   • RAM · 🧠 RAM: 437.5 MB

   ⏳ перед flush · 🧠 RAM: 437.5 MB

💾 batch 20424 → 12,145 рядків (всього 562,687 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20424.csv.gz

   ✅ після flush · 🧠 RAM: 439.0 MB

[2360/7081] – FLZH: empty |  33.33% | ETA 14:30

[2370/7081] ✓ FMC: 453 рядків |  33.47% | ETA 14:28

[2380/7081] ✓ FNDE: 365 рядків |  33.61% | ETA 14:27

[2390/7081] ✓ FNGR: 437 рядків |  33.75% | ETA 14:26

[2400/7081] ✓ FOXA: 397 рядків |  33.89% | ETA 14:24

   • RAM · 🧠 RAM: 441.2 MB

   ⏳ перед flush · 🧠 RAM: 441.2 MB

💾 batch 20425 → 11,342 рядків (всього 574,029 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20425.csv.gz

   ✅ після flush · 🧠 RAM: 443.5 MB

[2410/7081] ✓ FR: 325 рядків |  34.03% | ETA 14:23

[2420/7081] ✓ FRMI: 576 рядків |  34.18% | ETA 14:21

[2430/7081] ✓ FRT: 353 рядків |  34.32% | ETA 14:20

[2440/7081] ✓ FSLY: 467 рядків |  34.46% | ETA 14:19

[2450/7081] ✓ FTHM: 55 рядків |  34.60% | ETA 14:18

   • RAM · 🧠 RAM: 446.1 MB

   ⏳ перед flush · 🧠 RAM: 446.1 MB

💾 batch 20426 → 12,603 рядків (всього 586,632 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20426.csv.gz

   ✅ після flush · 🧠 RAM: 447.5 MB

[2460/7081] ✓ FTNT: 456 рядків |  34.74% | ETA 14:17

[2470/7081] ✓ FUBO: 352 рядків |  34.88% | ETA 14:15

[2480/7081] ✓ FVN: 12 рядків |  35.02% | ETA 14:14

[2490/7081] ✓ FWONK: 365 рядків |  35.16% | ETA 14:12

[2500/7081] ✓ FXNC: 16 рядків |  35.31% | ETA 14:11

   • RAM · 🧠 RAM: 449.6 MB

   ⏳ перед flush · 🧠 RAM: 449.6 MB

💾 batch 20427 → 11,246 рядків (всього 597,878 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20427.csv.gz

   ✅ після flush · 🧠 RAM: 451.0 MB

[2510/7081] ✓ GASS: 85 рядків |  35.45% | ETA 14:10

[2520/7081] ✓ GBIL: 261 рядків |  35.59% | ETA 14:08

[2530/7081] ✓ GCTK: 83 рядків |  35.73% | ETA 14:06

[2540/7081] ✓ GDTC: 9 рядків |  35.87% | ETA 14:05

[2550/7081] ✓ GDXU: 730 рядків |  36.01% | ETA 14:03

   • RAM · 🧠 RAM: 452.5 MB

   ⏳ перед flush · 🧠 RAM: 452.5 MB

💾 batch 20428 → 10,635 рядків (всього 608,513 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20428.csv.gz

   ✅ після flush · 🧠 RAM: 454.1 MB

[2560/7081] ✓ GEO: 388 рядків |  36.15% | ETA 14:02

[2570/7081] ✓ GEVG: 36 рядків |  36.29% | ETA 14:01

[2580/7081] – GGRP: empty |  36.44% | ETA 13:59

[2590/7081] ✓ GHM: 156 рядків |  36.58% | ETA 13:57

[2600/7081] ✓ GITS: 38 рядків |  36.72% | ETA 13:55

   • RAM · 🧠 RAM: 455.5 MB

   ⏳ перед flush · 🧠 RAM: 455.5 MB

💾 batch 20429 → 12,292 рядків (всього 620,805 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20429.csv.gz

   ✅ після flush · 🧠 RAM: 457.9 MB

[2610/7081] ✓ GLD: 933 рядків |  36.86% | ETA 13:55

[2620/7081] ✓ GLNG: 358 рядків |  37.00% | ETA 13:53

[2630/7081] ✓ GLW: 777 рядків |  37.14% | ETA 13:52

[2640/7081] ✓ GMED: 367 рядків |  37.28% | ETA 13:51

[2650/7081] ✓ GNK: 275 рядків |  37.42% | ETA 13:50

   • RAM · 🧠 RAM: 459.4 MB

   ⏳ перед flush · 🧠 RAM: 459.4 MB

💾 batch 20430 → 13,322 рядків (всього 634,127 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20430.csv.gz

   ✅ після flush · 🧠 RAM: 460.5 MB

[2660/7081] ✓ GNTA: 120 рядків |  37.57% | ETA 13:50

[2670/7081] ✓ GOLF: 158 рядків |  37.71% | ETA 13:48

[2680/7081] ✓ GORO: 253 рядків |  37.85% | ETA 13:46

[2690/7081] ✓ GOVX: 113 рядків |  37.99% | ETA 13:45

[2700/7081] ✓ GPCR: 356 рядків |  38.13% | ETA 13:43

   • RAM · 🧠 RAM: 462.3 MB

   ⏳ перед flush · 🧠 RAM: 462.3 MB

💾 batch 20431 → 11,923 рядків (всього 646,050 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20431.csv.gz

   ✅ після flush · 🧠 RAM: 464.7 MB

[2710/7081] ✓ GPZ: 126 рядків |  38.27% | ETA 13:42

[2720/7081] ✓ GREK: 46 рядків |  38.41% | ETA 13:40

[2730/7081] ✓ GRNQ: 67 рядків |  38.55% | ETA 13:39

[2740/7081] ✓ GRSD: 137 рядків |  38.70% | ETA 13:37

[2750/7081] ✓ GSK: 469 рядків |  38.84% | ETA 13:36

   • RAM · 🧠 RAM: 468.2 MB

   ⏳ перед flush · 🧠 RAM: 468.2 MB

💾 batch 20432 → 12,935 рядків (всього 658,985 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20432.csv.gz

   ✅ після flush · 🧠 RAM: 470.2 MB

[2760/7081] ✓ GUNR: 232 рядків |  38.98% | ETA 13:35

[2770/7081] ✓ GVA: 219 рядків |  39.12% | ETA 13:33

[2780/7081] ✓ GXO: 308 рядків |  39.26% | ETA 13:32

[2790/7081] ✓ HAP: 8 рядків |  39.40% | ETA 13:30

[2800/7081] ✓ HAYW: 376 рядків |  39.54% | ETA 13:28

   • RAM · 🧠 RAM: 471.9 MB

   ⏳ перед flush · 🧠 RAM: 471.9 MB

💾 batch 20433 → 10,492 рядків (всього 669,477 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20433.csv.gz

   ✅ після flush · 🧠 RAM: 472.1 MB

[2810/7081] ✓ HBT: 52 рядків |  39.68% | ETA 13:27

[2820/7081] ✓ HCKT: 122 рядків |  39.82% | ETA 13:26

[2830/7081] ✓ HELP: 381 рядків |  39.97% | ETA 13:24

[2840/7081] ✓ HGV: 264 рядків |  40.11% | ETA 13:23

[2850/7081] ✓ HIBL: 82 рядків |  40.25% | ETA 13:21

   • RAM · 🧠 RAM: 473.6 MB

   ⏳ перед flush · 🧠 RAM: 473.6 MB

💾 batch 20434 → 9,511 рядків (всього 678,988 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20434.csv.gz

   ✅ після flush · 🧠 RAM: 474.9 MB

[2860/7081] ✓ HIMZ: 214 рядків |  40.39% | ETA 13:19

[2870/7081] ✓ HITI: 165 рядків |  40.53% | ETA 13:18

[2880/7081] ✓ HLSQ: 62 рядків |  40.67% | ETA 13:16

[2890/7081] ✓ HODL: 272 рядків |  40.81% | ETA 13:14

[2900/7081] ✓ HOPE: 274 рядків |  40.95% | ETA 13:13

   • RAM · 🧠 RAM: 476.6 MB

   ⏳ перед flush · 🧠 RAM: 476.6 MB

💾 batch 20435 → 12,484 рядків (всього 691,472 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20435.csv.gz

   ✅ після flush · 🧠 RAM: 477.6 MB

[2910/7081] ✓ HP: 315 рядків |  41.10% | ETA 13:13

[2920/7081] ✓ HRB: 348 рядків |  41.24% | ETA 13:12

[2930/7081] ✓ HRZN: 282 рядків |  41.38% | ETA 13:10

[2940/7081] ✓ HTB: 98 рядків |  41.52% | ETA 13:08

[2950/7081] ✓ HTGC: 376 рядків |  41.66% | ETA 13:06

   • RAM · 🧠 RAM: 479.1 MB

   ⏳ перед flush · 🧠 RAM: 479.1 MB

💾 batch 20436 → 13,238 рядків (всього 704,710 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20436.csv.gz

   ✅ після flush · 🧠 RAM: 480.8 MB

[2960/7081] ✓ HUBB: 354 рядків |  41.80% | ETA 13:05

[2970/7081] ✓ HUYA: 160 рядків |  41.94% | ETA 13:03

[2980/7081] ✓ HXL: 337 рядків |  42.08% | ETA 13:02

[2990/7081] ✓ HYMC: 405 рядків |  42.23% | ETA 13:00

[3000/7081] ✓ IAK: 103 рядків |  42.37% | ETA 12:59

   • RAM · 🧠 RAM: 481.4 MB

   ⏳ перед flush · 🧠 RAM: 481.4 MB

💾 batch 20437 → 11,447 рядків (всього 716,157 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20437.csv.gz

   ✅ після flush · 🧠 RAM: 483.1 MB

[3010/7081] ✓ IAT: 204 рядків |  42.51% | ETA 12:58

[3020/7081] ✓ IBO: 26 рядків |  42.65% | ETA 12:56

[3030/7081] ✓ IBTL: 155 рядків |  42.79% | ETA 12:54

[3040/7081] ✓ ICG: 22 рядків |  42.93% | ETA 12:53

[3050/7081] ✓ ICSH: 316 рядків |  43.07% | ETA 12:51

   • RAM · 🧠 RAM: 481.3 MB

   ⏳ перед flush · 🧠 RAM: 481.3 MB

💾 batch 20438 → 11,792 рядків (всього 727,949 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20438.csv.gz

   ✅ після flush · 🧠 RAM: 483.1 MB

[3060/7081] ✓ IDN: 87 рядків |  43.21% | ETA 12:50

[3070/7081] ✓ IDU: 126 рядків |  43.36% | ETA 12:48

[3080/7081] ✓ IEP: 303 рядків |  43.50% | ETA 12:47

[3090/7081] ✓ IGF: 351 рядків |  43.64% | ETA 12:45

[3100/7081] ✓ IGM: 240 рядків |  43.78% | ETA 12:43

   • RAM · 🧠 RAM: 485.1 MB

   ⏳ перед flush · 🧠 RAM: 485.1 MB

💾 batch 20439 → 11,154 рядків (всього 739,103 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20439.csv.gz

   ✅ після flush · 🧠 RAM: 486.8 MB

[3110/7081] ✓ IHG: 183 рядків |  43.92% | ETA 12:43

[3120/7081] ✓ IJR: 394 рядків |  44.06% | ETA 12:41

[3130/7081] ✓ IMCR: 202 рядків |  44.20% | ETA 12:39

[3140/7081] ✓ IMPP: 204 рядків |  44.34% | ETA 12:37

[3150/7081] ✓ IMXI: 273 рядків |  44.49% | ETA 12:36

   • RAM · 🧠 RAM: 488.7 MB

   ⏳ перед flush · 🧠 RAM: 488.7 MB

💾 batch 20440 → 10,614 рядків (всього 749,717 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20440.csv.gz

   ✅ після flush · 🧠 RAM: 489.7 MB

[3160/7081] ✓ INCY: 363 рядків |  44.63% | ETA 12:35

[3170/7081] ✓ INFH: 81 рядків |  44.77% | ETA 12:33

[3180/7081] ✓ INGM: 299 рядків |  44.91% | ETA 12:32

[3190/7081] ✓ INR: 104 рядків |  45.05% | ETA 12:31

[3200/7081] ✓ INTW: 887 рядків |  45.19% | ETA 12:30

   • RAM · 🧠 RAM: 478.8 MB

   ⏳ перед flush · 🧠 RAM: 478.8 MB

💾 batch 20441 → 13,006 рядків (всього 762,723 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20441.csv.gz

   ✅ після flush · 🧠 RAM: 479.6 MB

[3210/7081] ✓ INVX: 222 рядків |  45.33% | ETA 12:29

[3220/7081] ✓ IOYY: 24 рядків |  45.47% | ETA 12:27

[3230/7081] ✓ IPAY: 12 рядків |  45.62% | ETA 12:26

[3240/7081] ✓ IPI: 151 рядків |  45.76% | ETA 12:24

[3250/7081] ✓ IQST: 104 рядків |  45.90% | ETA 12:23

   • RAM · 🧠 RAM: 466.9 MB

   ⏳ перед flush · 🧠 RAM: 467.1 MB

💾 batch 20442 → 12,310 рядків (всього 775,033 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20442.csv.gz

   ✅ після flush · 🧠 RAM: 478.0 MB

[3260/7081] ✓ IRMD: 73 рядків |  46.04% | ETA 12:22

[3270/7081] ✓ ISPC: 176 рядків |  46.18% | ETA 12:20

[3280/7081] ✓ ISTB: 234 рядків |  46.32% | ETA 12:18

[3290/7081] ✓ ITUB: 415 рядків |  46.46% | ETA 12:17

[3300/7081] ✓ IVEP: 8 рядків |  46.60% | ETA 12:15

   • RAM · 🧠 RAM: 468.1 MB

   ⏳ перед flush · 🧠 RAM: 468.1 MB

💾 batch 20443 → 14,040 рядків (всього 789,073 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20443.csv.gz

   ✅ після flush · 🧠 RAM: 468.9 MB

[3310/7081] ✓ IVOO: 117 рядків |  46.74% | ETA 12:14

[3320/7081] ✓ IWR: 371 рядків |  46.89% | ETA 12:12

[3330/7081] ✓ IYF: 176 рядків |  47.03% | ETA 12:11

[3340/7081] ✓ IYRI: 83 рядків |  47.17% | ETA 12:09

[3350/7081] ✓ JAAA: 437 рядків |  47.31% | ETA 12:07

   • RAM · 🧠 RAM: 454.1 MB

   ⏳ перед flush · 🧠 RAM: 454.1 MB

💾 batch 20444 → 13,714 рядків (всього 802,787 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20444.csv.gz

   ✅ після flush · 🧠 RAM: 455.0 MB

[3360/7081] ✓ JAGX: 340 рядків |  47.45% | ETA 12:06

[3370/7081] ✓ JCPB: 381 рядків |  47.59% | ETA 12:05

[3380/7081] ✓ JETD: 26 рядків |  47.73% | ETA 12:03

[3390/7081] ✓ JFU: 2 рядків |  47.87% | ETA 12:01

[3400/7081] ✓ JJSF: 131 рядків |  48.02% | ETA 12:00

   • RAM · 🧠 RAM: 446.7 MB

   ⏳ перед flush · 🧠 RAM: 446.7 MB

💾 batch 20445 → 12,778 рядків (всього 815,565 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20445.csv.gz

   ✅ після flush · 🧠 RAM: 447.5 MB

[3410/7081] ✓ JNJ: 482 рядків |  48.16% | ETA 11:59

[3420/7081] ✓ JOYY: 217 рядків |  48.30% | ETA 11:57

[3430/7081] ✓ JPRF: 114 рядків |  48.44% | ETA 11:56

[3440/7081] ✓ JUSA: 87 рядків |  48.58% | ETA 11:54

[3450/7081] ✓ KALU: 134 рядків |  48.72% | ETA 11:53

   • RAM · 🧠 RAM: 450.6 MB

   ⏳ перед flush · 🧠 RAM: 450.6 MB

💾 batch 20446 → 9,769 рядків (всього 825,334 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20446.csv.gz

   ✅ після flush · 🧠 RAM: 450.9 MB

[3460/7081] ✓ KBDC: 262 рядків |  48.86% | ETA 11:51

[3470/7081] ✓ KCOP: 13 рядків |  49.00% | ETA 11:50

[3480/7081] ✓ KEY: 396 рядків |  49.15% | ETA 11:48

[3490/7081] ✓ KGEI: 118 рядків |  49.29% | ETA 11:47

[3500/7081] ✓ KIDS: 113 рядків |  49.43% | ETA 11:45

   • RAM · 🧠 RAM: 453.3 MB

   ⏳ перед flush · 🧠 RAM: 453.3 MB

💾 batch 20447 → 11,008 рядків (всього 836,342 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20447.csv.gz

   ✅ після flush · 🧠 RAM: 456.0 MB

[3510/7081] ✓ KLTR: 95 рядків |  49.57% | ETA 11:44

[3520/7081] ✓ KN: 307 рядків |  49.71% | ETA 11:42

[3530/7081] ✓ KNSA: 279 рядків |  49.85% | ETA 11:40

[3540/7081] – KORE: empty |  49.99% | ETA 11:39

[3550/7081] ✓ KRG: 367 рядків |  50.13% | ETA 11:37

   • RAM · 🧠 RAM: 458.2 MB

   ⏳ перед flush · 🧠 RAM: 458.2 MB

💾 batch 20448 → 13,458 рядків (всього 849,800 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20448.csv.gz

   ✅ після flush · 🧠 RAM: 459.3 MB

[3560/7081] ✓ KRNY: 191 рядків |  50.28% | ETA 11:36

[3570/7081] ✓ KTB: 267 рядків |  50.42% | ETA 11:34

[3580/7081] ✓ KTOS: 530 рядків |  50.56% | ETA 11:32

[3590/7081] ✓ KWY: 28 рядків |  50.70% | ETA 11:30

[3600/7081] ✓ KYTX: 284 рядків |  50.84% | ETA 11:29

   • RAM · 🧠 RAM: 458.5 MB

   ⏳ перед flush · 🧠 RAM: 458.5 MB

💾 batch 20449 → 10,315 рядків (всього 860,115 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20449.csv.gz

   ✅ після flush · 🧠 RAM: 460.6 MB

[3610/7081] – LACG: empty |  50.98% | ETA 11:27

[3620/7081] ✓ LAW: 106 рядків |  51.12% | ETA 11:26

[3630/7081] ✓ LCFY: 10 рядків |  51.26% | ETA 11:24

[3640/7081] ✓ LEN: 470 рядків |  51.41% | ETA 11:22

[3650/7081] ✓ LEGN: 385 рядків |  51.55% | ETA 11:20

   • RAM · 🧠 RAM: 463.6 MB

   ⏳ перед flush · 🧠 RAM: 463.6 MB

💾 batch 20450 → 12,321 рядків (всього 872,436 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20450.csv.gz

   ✅ після flush · 🧠 RAM: 465.6 MB

[3660/7081] ✓ LFMD: 302 рядків |  51.69% | ETA 11:19

[3670/7081] ✓ LGN: 350 рядків |  51.83% | ETA 11:17

[3680/7081] ✓ LHX: 428 рядків |  51.97% | ETA 11:16

[3690/7081] ✓ LIME: 173 рядків |  52.11% | ETA 11:15

[3700/7081] ✓ LITG: 49 рядків |  52.25% | ETA 11:13

   • RAM · 🧠 RAM: 467.0 MB

   ⏳ перед flush · 🧠 RAM: 467.0 MB

💾 batch 20451 → 11,069 рядків (всього 883,505 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20451.csv.gz

   ✅ після flush · 🧠 RAM: 469.6 MB

[3710/7081] ✓ LKFT: 95 рядків |  52.39% | ETA 11:11

[3720/7081] ✓ LMRI: 156 рядків |  52.53% | ETA 11:09

[3730/7081] ✓ LNKS: 92 рядків |  52.68% | ETA 11:08

[3740/7081] ✓ LOMA: 205 рядків |  52.82% | ETA 11:06

[3750/7081] ✓ LOVE: 130 рядків |  52.96% | ETA 11:04

   • RAM · 🧠 RAM: 472.0 MB

   ⏳ перед flush · 🧠 RAM: 472.0 MB

💾 batch 20452 → 9,751 рядків (всього 893,256 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20452.csv.gz

   ✅ після flush · 🧠 RAM: 473.5 MB

[3760/7081] – LPRO: empty |  53.10% | ETA 11:03

[3770/7081] ✓ LRMR: 360 рядків |  53.24% | ETA 11:01

[3780/7081] ✓ LSTA: 51 рядків |  53.38% | ETA 10:59

[3790/7081] ✓ LULU: 493 рядків |  53.52% | ETA 10:58

[3800/7081] ✓ LULG: 146 рядків |  53.66% | ETA 10:56

   • RAM · 🧠 RAM: 471.2 MB

   ⏳ перед flush · 🧠 RAM: 471.2 MB

💾 batch 20453 → 10,805 рядків (всього 904,061 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20453.csv.gz

   ✅ після flush · 🧠 RAM: 472.7 MB

[3810/7081] ✓ LXFR: 104 рядків |  53.81% | ETA 10:54

[3820/7081] ✓ LYFT: 417 рядків |  53.95% | ETA 10:53

[3830/7081] ✓ MAA: 325 рядків |  54.09% | ETA 10:51

[3840/7081] ✓ MAKO: 104 рядків |  54.23% | ETA 10:49

[3850/7081] ✓ MATV: 190 рядків |  54.37% | ETA 10:48

   • RAM · 🧠 RAM: 475.5 MB

   ⏳ перед flush · 🧠 RAM: 475.5 MB

💾 batch 20454 → 14,066 рядків (всього 918,127 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20454.csv.gz

   ✅ після flush · 🧠 RAM: 477.8 MB

[3860/7081] ✓ MARA: 908 рядків |  54.51% | ETA 10:46

[3870/7081] ✓ MBWM: 83 рядків |  54.65% | ETA 10:45

[3880/7081] ✓ MCRI: 76 рядків |  54.79% | ETA 10:43

[3890/7081] ✓ MCY: 154 рядків |  54.94% | ETA 10:41

[3900/7081] ✓ MDT: 424 рядків |  55.08% | ETA 10:39

   • RAM · 🧠 RAM: 466.6 MB

   ⏳ перед flush · 🧠 RAM: 466.6 MB

💾 batch 20455 → 12,580 рядків (всього 930,707 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20455.csv.gz

   ✅ після flush · 🧠 RAM: 466.9 MB

[3910/7081] ✓ MEI: 241 рядків |  55.22% | ETA 10:38

[3920/7081] ✓ METD: 234 рядків |  55.36% | ETA 10:36

[3930/7081] ✓ MFA: 388 рядків |  55.50% | ETA 10:34

[3940/7081] ✓ MGEE: 108 рядків |  55.64% | ETA 10:33

[3950/7081] ✓ MH: 133 рядків |  55.78% | ETA 10:30

   • RAM · 🧠 RAM: 441.0 MB

   ⏳ перед flush · 🧠 RAM: 441.0 MB

💾 batch 20456 → 11,974 рядків (всього 942,681 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20456.csv.gz

   ✅ після flush · 🧠 RAM: 442.9 MB

[3960/7081] ✓ MIAX: 381 рядків |  55.92% | ETA 10:29

[3970/7081] ✓ MIRA: 40 рядків |  56.07% | ETA 10:26

[3980/7081] ✓ MKC: 408 рядків |  56.21% | ETA 10:24

[3990/7081] ✓ MLCO: 335 рядків |  56.35% | ETA 10:22

[4000/7081] ✓ MN: 43 рядків |  56.49% | ETA 10:20

   • RAM · 🧠 RAM: 438.0 MB

   ⏳ перед flush · 🧠 RAM: 438.0 MB

💾 batch 20457 → 9,607 рядків (всього 952,288 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20457.csv.gz

   ✅ після flush · 🧠 RAM: 438.3 MB

[4010/7081] ✓ MNGU: 9 рядків |  56.63% | ETA 10:18

[4020/7081] ✓ MNST: 440 рядків |  56.77% | ETA 10:16

[4030/7081] ✓ MOD: 408 рядків |  56.91% | ETA 10:14

[4040/7081] ✓ MPB: 88 рядків |  57.05% | ETA 10:12

[4050/7081] ✓ MPG: 191 рядків |  57.20% | ETA 10:10

   • RAM · 🧠 RAM: 439.1 MB

   ⏳ перед flush · 🧠 RAM: 439.1 MB

💾 batch 20458 → 11,770 рядків (всього 964,058 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20458.csv.gz

   ✅ після flush · 🧠 RAM: 439.6 MB

[4060/7081] ✓ MRKR: 300 рядків |  57.34% | ETA 10:08

[4070/7081] ✓ MRTN: 256 рядків |  57.48% | ETA 10:06

[4080/7081] ✓ MRVL: 1,219 рядків |  57.62% | ETA 10:04

[4090/7081] ✓ MSGM: 81 рядків |  57.76% | ETA 10:02

[4100/7081] ✓ MSOX: 322 рядків |  57.90% | ETA 10:00

   • RAM · 🧠 RAM: 440.5 MB

   ⏳ перед flush · 🧠 RAM: 440.5 MB

💾 batch 20459 → 13,644 рядків (всього 977,702 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20459.csv.gz

   ✅ після flush · 🧠 RAM: 441.0 MB

[4110/7081] ✓ MSTW: 394 рядків |  58.04% | ETA 09:58

[4120/7081] ✓ MTG: 374 рядків |  58.18% | ETA 09:56

[4130/7081] ✓ MTNB: 142 рядків |  58.33% | ETA 09:54

[4140/7081] ✓ MTZ: 395 рядків |  58.47% | ETA 09:52

[4150/7081] ✓ MUR: 380 рядків |  58.61% | ETA 09:50

   • RAM · 🧠 RAM: 440.0 MB

   ⏳ перед flush · 🧠 RAM: 440.0 MB

💾 batch 20460 → 15,321 рядків (всього 993,023 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20460.csv.gz

   ✅ після flush · 🧠 RAM: 440.5 MB

[4160/7081] ✓ MWC: 124 рядків |  58.75% | ETA 09:48

[4170/7081] ✓ MYFW: 46 рядків |  58.89% | ETA 09:46

[4180/7081] ✓ MZTI: 136 рядків |  59.03% | ETA 09:44

[4190/7081] ✓ NASA: 506 рядків |  59.17% | ETA 09:42

[4200/7081] ✓ NBIC: 28 рядків |  59.31% | ETA 09:39

   • RAM · 🧠 RAM: 439.7 MB

   ⏳ перед flush · 🧠 RAM: 439.7 MB

💾 batch 20461 → 13,312 рядків (всього 1,006,335 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20461.csv.gz

   ✅ після flush · 🧠 RAM: 440.1 MB

[4210/7081] ✓ NBSD: 160 рядків |  59.45% | ETA 09:38

[4220/7081] ✓ NCNO: 366 рядків |  59.60% | ETA 09:35

[4230/7081] ✓ NEA: 314 рядків |  59.74% | ETA 09:34

[4240/7081] ✓ NEON: 76 рядків |  59.88% | ETA 09:32

[4250/7081] ✓ NESR: 375 рядків |  60.02% | ETA 09:30

   • RAM · 🧠 RAM: 441.3 MB

   ⏳ перед flush · 🧠 RAM: 441.3 MB

💾 batch 20462 → 14,236 рядків (всього 1,020,571 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20462.csv.gz

   ✅ після flush · 🧠 RAM: 441.8 MB

[4260/7081] ✓ NFEGP: 28 рядків |  60.16% | ETA 09:28

[4270/7081] ✓ NGVC: 86 рядків |  60.30% | ETA 09:26

[4280/7081] ✓ NHTC: 34 рядків |  60.44% | ETA 09:24

[4290/7081] ✓ NIU: 59 рядків |  60.58% | ETA 09:22

[4300/7081] ✓ NLR: 317 рядків |  60.73% | ETA 09:20

   • RAM · 🧠 RAM: 440.5 MB

   ⏳ перед flush · 🧠 RAM: 440.5 MB

💾 batch 20463 → 11,546 рядків (всього 1,032,117 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20463.csv.gz

   ✅ після flush · 🧠 RAM: 440.9 MB

[4310/7081] ✓ NMTC: 24 рядків |  60.87% | ETA 09:18

[4320/7081] ✓ NNOX: 413 рядків |  61.01% | ETA 09:16

[4330/7081] ✓ NPT: 28 рядків |  61.15% | ETA 09:13

[4340/7081] ✓ NRGD: 54 рядків |  61.29% | ETA 09:11

[4350/7081] ✓ NRGV: 394 рядків |  61.43% | ETA 09:09

   • RAM · 🧠 RAM: 442.0 MB

   ⏳ перед flush · 🧠 RAM: 442.0 MB

💾 batch 20464 → 13,463 рядків (всього 1,045,580 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20464.csv.gz

   ✅ після flush · 🧠 RAM: 442.5 MB

[4360/7081] ✓ NSP: 208 рядків |  61.57% | ETA 09:07

[4370/7081] ✓ NTNX: 387 рядків |  61.71% | ETA 09:05

[4380/7081] ✓ NUGY: 6 рядків |  61.86% | ETA 09:03

[4390/7081] ✓ NUR: 64 рядків |  62.00% | ETA 09:01

[4400/7081] ✓ NVDA: 1,428 рядків |  62.14% | ETA 08:59

   • RAM · 🧠 RAM: 442.7 MB

   ⏳ перед flush · 🧠 RAM: 442.7 MB

💾 batch 20465 → 11,660 рядків (всього 1,057,240 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20465.csv.gz

   ✅ після flush · 🧠 RAM: 443.2 MB

[4410/7081] ✓ NVDY: 568 рядків |  62.28% | ETA 08:57

[4420/7081] ✓ NVMI: 252 рядків |  62.42% | ETA 08:55

[4430/7081] – NVVE: empty |  62.56% | ETA 08:53

[4440/7081] ✓ NWPX: 68 рядків |  62.70% | ETA 08:51

[4450/7081] ✓ NXPL: 44 рядків |  62.84% | ETA 08:49

   • RAM · 🧠 RAM: 439.4 MB

   ⏳ перед flush · 🧠 RAM: 439.4 MB

💾 batch 20466 → 12,991 рядків (всього 1,070,231 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20466.csv.gz

   ✅ після flush · 🧠 RAM: 439.9 MB

[4460/7081] ✓ NYT: 372 рядків |  62.99% | ETA 08:47

[4470/7081] ✓ O: 663 рядків |  63.13% | ETA 08:45

[4480/7081] ✓ OCCI: 137 рядків |  63.27% | ETA 08:43

[4490/7081] ✓ OESX: 65 рядків |  63.41% | ETA 08:41

[4500/7081] ✓ OGG: 292 рядків |  63.55% | ETA 08:39

   • RAM · 🧠 RAM: 440.1 MB

   ⏳ перед flush · 🧠 RAM: 440.1 MB

💾 batch 20467 → 10,060 рядків (всього 1,080,291 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20467.csv.gz

   ✅ після flush · 🧠 RAM: 441.2 MB

[4510/7081] ✓ OILD: 134 рядків |  63.69% | ETA 08:37

[4520/7081] ✓ OKLO: 886 рядків |  63.83% | ETA 08:35

[4530/7081] ✓ OLMA: 312 рядків |  63.97% | ETA 08:33

[4540/7081] ✓ OMER: 356 рядків |  64.12% | ETA 08:31

[4550/7081] ✓ ONEN: 138 рядків |  64.26% | ETA 08:29

   • RAM · 🧠 RAM: 436.7 MB

   ⏳ перед flush · 🧠 RAM: 436.7 MB

💾 batch 20468 → 13,481 рядків (всього 1,093,772 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20468.csv.gz

   ✅ після flush · 🧠 RAM: 437.3 MB

[4560/7081] ✓ ONT: 178 рядків |  64.40% | ETA 08:27

[4570/7081] ✓ OPEX: 76 рядків |  64.54% | ETA 08:25

[4580/7081] ✓ OPPJ: 48 рядків |  64.68% | ETA 08:23

[4590/7081] ✓ ORGO: 289 рядків |  64.82% | ETA 08:21

[4600/7081] ✓ ORCL: 1,113 рядків |  64.96% | ETA 08:19

   • RAM · 🧠 RAM: 428.4 MB

   ⏳ перед flush · 🧠 RAM: 428.4 MB

💾 batch 20469 → 11,501 рядків (всього 1,105,273 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20469.csv.gz

   ✅ після flush · 🧠 RAM: 425.9 MB

[4610/7081] ✓ OSPR: 2 рядків |  65.10% | ETA 08:17

[4620/7081] ✓ OTAI: 22 рядків |  65.25% | ETA 08:15

[4630/7081] ✓ OUSL: 76 рядків |  65.39% | ETA 08:13

[4640/7081] ✓ OXM: 210 рядків |  65.53% | ETA 08:11

[4650/7081] ✓ PAAS: 432 рядків |  65.67% | ETA 08:09

   • RAM · 🧠 RAM: 403.3 MB

   ⏳ перед flush · 🧠 RAM: 403.3 MB

💾 batch 20470 → 11,092 рядків (всього 1,116,365 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20470.csv.gz

   ✅ після flush · 🧠 RAM: 401.0 MB

[4660/7081] ✓ PACS: 262 рядків |  65.81% | ETA 08:07

[4670/7081] ✓ PAPL: 54 рядків |  65.95% | ETA 08:05

[4680/7081] ✓ PATH: 521 рядків |  66.09% | ETA 08:03

[4690/7081] ✓ PAYX: 414 рядків |  66.23% | ETA 08:01

[4700/7081] ✓ PBR.A: 455 рядків |  66.37% | ETA 07:59

   • RAM · 🧠 RAM: 394.8 MB

   ⏳ перед flush · 🧠 RAM: 394.8 MB

💾 batch 20471 → 12,694 рядків (всього 1,129,059 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20471.csv.gz

   ✅ після flush · 🧠 RAM: 395.4 MB

[4710/7081] ✓ PCG: 423 рядків |  66.52% | ETA 07:57

[4720/7081] ✓ PDBC: 379 рядків |  66.66% | ETA 07:55

[4730/7081] ✓ PDI: 396 рядків |  66.80% | ETA 07:53

[4740/7081] ✓ PENU: 82 рядків |  66.94% | ETA 07:51

[4750/7081] ✓ PERI: 194 рядків |  67.08% | ETA 07:49

   • RAM · 🧠 RAM: 396.3 MB

   ⏳ перед flush · 🧠 RAM: 396.3 MB

💾 batch 20472 → 11,721 рядків (всього 1,140,780 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20472.csv.gz

   ✅ після flush · 🧠 RAM: 396.9 MB

[4760/7081] ✓ PFF: 385 рядків |  67.22% | ETA 07:47

[4770/7081] ✓ PGC: 57 рядків |  67.36% | ETA 07:45

[4780/7081] – PHGE: empty |  67.50% | ETA 07:42

[4790/7081] ✓ PHK: 243 рядків |  67.65% | ETA 07:40

[4800/7081] ✓ PHVS: 288 рядків |  67.79% | ETA 07:38

   • RAM · 🧠 RAM: 395.5 MB

   ⏳ перед flush · 🧠 RAM: 395.5 MB

💾 batch 20473 → 11,724 рядків (всього 1,152,504 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20473.csv.gz

   ✅ після flush · 🧠 RAM: 396.1 MB

[4810/7081] ✓ PKOH: 36 рядків |  67.93% | ETA 07:36

[4820/7081] ✓ PLOW: 75 рядків |  68.07% | ETA 07:34

[4830/7081] ✓ PLTA: 17 рядків |  68.21% | ETA 07:33

[4840/7081] ✓ PLTW: 155 рядків |  68.35% | ETA 07:31

[4850/7081] ✓ PLYY: 6 рядків |  68.49% | ETA 07:29

   • RAM · 🧠 RAM: 392.4 MB

   ⏳ перед flush · 🧠 RAM: 392.4 MB

💾 batch 20474 → 12,126 рядків (всього 1,164,630 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20474.csv.gz

   ✅ після flush · 🧠 RAM: 393.9 MB

[4860/7081] ✓ PNBK: 112 рядків |  68.63% | ETA 07:27

[4870/7081] ✓ PNNT: 231 рядків |  68.78% | ETA 07:25

[4880/7081] ✓ POM: 66 рядків |  68.92% | ETA 07:22

[4890/7081] ✓ PPC: 326 рядків |  69.06% | ETA 07:20

[4900/7081] ✓ PPLT: 352 рядків |  69.20% | ETA 07:18

   • RAM · 🧠 RAM: 391.2 MB

   ⏳ перед flush · 🧠 RAM: 391.2 MB

💾 batch 20475 → 11,358 рядків (всього 1,175,988 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20475.csv.gz

   ✅ після flush · 🧠 RAM: 391.7 MB

[4910/7081] ✓ PRG: 208 рядків |  69.34% | ETA 07:16

[4920/7081] ✓ PRM: 334 рядків |  69.48% | ETA 07:14

[4930/7081] ✓ PRQR: 211 рядків |  69.62% | ETA 07:12

[4940/7081] ✓ PSEC: 466 рядків |  69.76% | ETA 07:10

[4950/7081] ✓ PSLV: 482 рядків |  69.91% | ETA 07:08

   • RAM · 🧠 RAM: 392.7 MB

   ⏳ перед flush · 🧠 RAM: 392.7 MB

💾 batch 20476 → 10,595 рядків (всього 1,186,583 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20476.csv.gz

   ✅ після flush · 🧠 RAM: 393.3 MB

[4960/7081] ✓ PSUS: 135 рядків |  70.05% | ETA 07:06

[4970/7081] ✓ PTLO: 355 рядків |  70.19% | ETA 07:04

[4980/7081] ✓ PUMP: 395 рядків |  70.33% | ETA 07:02

[4990/7081] ✓ PW: 6 рядків |  70.47% | ETA 07:00

[5000/7081] ✓ PXE: 41 рядків |  70.61% | ETA 06:58

   • RAM · 🧠 RAM: 390.2 MB

   ⏳ перед flush · 🧠 RAM: 390.2 MB

💾 batch 20477 → 11,781 рядків (всього 1,198,364 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20477.csv.gz

   ✅ після flush · 🧠 RAM: 390.7 MB

[5010/7081] ✓ PZA: 365 рядків |  70.75% | ETA 06:56

[5020/7081] ✓ QDEL: 340 рядків |  70.89% | ETA 06:54

[5030/7081] ✓ QETH: 7 рядків |  71.04% | ETA 06:52

[5040/7081] ✓ QMCO: 417 рядків |  71.18% | ETA 06:50

[5050/7081] ✓ QNST: 265 рядків |  71.32% | ETA 06:48

   • RAM · 🧠 RAM: 391.9 MB

   ⏳ перед flush · 🧠 RAM: 391.9 MB

💾 batch 20478 → 11,876 рядків (всього 1,210,240 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20478.csv.gz

   ✅ після flush · 🧠 RAM: 392.4 MB

[5060/7081] ✓ QQQS: 5 рядків |  71.46% | ETA 06:46

[5070/7081] ✓ QQQU: 27 рядків |  71.60% | ETA 06:44

[5080/7081] – QRVO: empty |  71.74% | ETA 06:42

[5090/7081] ✓ QXL: 59 рядків |  71.88% | ETA 06:40

[5100/7081] ✓ RA: 127 рядків |  72.02% | ETA 06:38

   • RAM · 🧠 RAM: 393.5 MB

   ⏳ перед flush · 🧠 RAM: 393.5 MB

💾 batch 20479 → 12,566 рядків (всього 1,222,806 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20479.csv.gz

   ✅ після flush · 🧠 RAM: 394.0 MB

[5110/7081] ✓ RAMP: 341 рядків |  72.16% | ETA 06:36

[5120/7081] ✓ RBLY: 14 рядків |  72.31% | ETA 06:34

[5130/7081] ✓ RCAT: 731 рядків |  72.45% | ETA 06:32

[5140/7081] ✓ RDTE: 122 рядків |  72.59% | ETA 06:30

[5150/7081] ✓ RDW: 795 рядків |  72.73% | ETA 06:28

   • RAM · 🧠 RAM: 387.9 MB

   ⏳ перед flush · 🧠 RAM: 387.9 MB

💾 batch 20480 → 12,903 рядків (всього 1,235,709 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20480.csv.gz

   ✅ після flush · 🧠 RAM: 388.4 MB

[5160/7081] – REAX_20260824: empty |  72.87% | ETA 06:26

[5170/7081] ✓ REK: 26 рядків |  73.01% | ETA 06:24

[5180/7081] ✓ RENT: 59 рядків |  73.15% | ETA 06:22

[5190/7081] ✓ RFAI: 6 рядків |  73.29% | ETA 06:20

[5200/7081] ✓ RGNT: 67 рядків |  73.44% | ETA 06:18

   • RAM · 🧠 RAM: 383.3 MB

   ⏳ перед flush · 🧠 RAM: 383.3 MB

💾 batch 20481 → 10,545 рядків (всього 1,246,254 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20481.csv.gz

   ✅ після flush · 🧠 RAM: 383.8 MB

[5210/7081] ✓ RH: 315 рядків |  73.58% | ETA 06:16

[5220/7081] ✓ RIO: 502 рядків |  73.72% | ETA 06:14

[5230/7081] ✓ RKDA: 175 рядків |  73.86% | ETA 06:12

[5240/7081] ✓ RKLX: 814 рядків |  74.00% | ETA 06:10

[5250/7081] ✓ RMBX: 17 рядків |  74.14% | ETA 06:08

   • RAM · 🧠 RAM: 379.2 MB

   ⏳ перед flush · 🧠 RAM: 379.2 MB

💾 batch 20482 → 14,324 рядків (всього 1,260,578 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20482.csv.gz

   ✅ після flush · 🧠 RAM: 379.8 MB

[5260/7081] ✓ RNAC: 120 рядків |  74.28% | ETA 06:06

[5270/7081] ✓ RNW: 194 рядків |  74.42% | ETA 06:04

[5280/7081] ✓ ROK: 363 рядків |  74.57% | ETA 06:02

[5290/7081] ✓ RPAY: 215 рядків |  74.71% | ETA 06:00

[5300/7081] ✓ RRBI: 43 рядків |  74.85% | ETA 05:58

   • RAM · 🧠 RAM: 368.2 MB

   ⏳ перед flush · 🧠 RAM: 368.2 MB

💾 batch 20483 → 10,113 рядків (всього 1,270,691 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20483.csv.gz

   ✅ після flush · 🧠 RAM: 368.6 MB

[5310/7081] ✓ RS: 286 рядків |  74.99% | ETA 05:56

[5320/7081] ✓ RTO: 389 рядків |  75.13% | ETA 05:54

[5330/7081] ✓ RUSHA: 206 рядків |  75.27% | ETA 05:52

[5340/7081] ✓ RWL: 265 рядків |  75.41% | ETA 05:50

[5350/7081] ✓ RY: 341 рядків |  75.55% | ETA 05:48

   • RAM · 🧠 RAM: 369.5 MB

   ⏳ перед flush · 🧠 RAM: 369.5 MB

💾 batch 20484 → 13,708 рядків (всього 1,284,399 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20484.csv.gz

   ✅ після flush · 🧠 RAM: 370.1 MB

[5360/7081] ✓ SAFE: 312 рядків |  75.70% | ETA 05:46

[5370/7081] ✓ SAFT: 67 рядків |  75.84% | ETA 05:44

[5380/7081] ✓ SAR: 105 рядків |  75.98% | ETA 05:42

[5390/7081] ✓ SBIT: 464 рядків |  76.12% | ETA 05:40

[5400/7081] ✓ SBLK: 380 рядків |  76.26% | ETA 05:38

   • RAM · 🧠 RAM: 370.3 MB

   ⏳ перед flush · 🧠 RAM: 370.3 MB

💾 batch 20485 → 15,059 рядків (всього 1,299,458 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20485.csv.gz

   ✅ після flush · 🧠 RAM: 371.6 MB

[5410/7081] ✓ SCCO: 345 рядків |  76.40% | ETA 05:36

[5420/7081] ✓ SCHP: 406 рядків |  76.54% | ETA 05:34

[5430/7081] ✓ SCHX: 408 рядків |  76.68% | ETA 05:32

[5440/7081] ✓ SCNI: 109 рядків |  76.83% | ETA 05:30

[5450/7081] ✓ SCSC: 126 рядків |  76.97% | ETA 05:28

   • RAM · 🧠 RAM: 373.6 MB

   ⏳ перед flush · 🧠 RAM: 373.6 MB

💾 batch 20486 → 13,478 рядків (всього 1,312,936 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20486.csv.gz

   ✅ після flush · 🧠 RAM: 374.2 MB

[5460/7081] ✓ SDY: 245 рядків |  77.11% | ETA 05:26

[5470/7081] ✓ SER: 23 рядків |  77.25% | ETA 05:24

[5480/7081] ✓ SERV: 510 рядків |  77.39% | ETA 05:22

[5490/7081] ✓ SFBS: 245 рядків |  77.53% | ETA 05:20

[5500/7081] ✓ SFWL: 1 рядків |  77.67% | ETA 05:18

   • RAM · 🧠 RAM: 375.3 MB

   ⏳ перед flush · 🧠 RAM: 375.3 MB

💾 batch 20487 → 13,907 рядків (всього 1,326,843 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20487.csv.gz

   ✅ після flush · 🧠 RAM: 375.8 MB

[5510/7081] ✓ SGLD: 37 рядків |  77.81% | ETA 05:16

[5520/7081] ✓ SHEN: 221 рядків |  77.96% | ETA 05:14

[5530/7081] ✓ SHMD: 341 рядків |  78.10% | ETA 05:12

[5540/7081] ✓ SID: 379 рядків |  78.24% | ETA 05:10

[5550/7081] ✓ SIL: 332 рядків |  78.38% | ETA 05:08

   • RAM · 🧠 RAM: 376.3 MB

   ⏳ перед flush · 🧠 RAM: 376.3 MB

💾 batch 20488 → 14,435 рядків (всього 1,341,278 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20488.csv.gz

   ✅ після flush · 🧠 RAM: 376.9 MB

[5560/7081] ✓ SION: 318 рядків |  78.52% | ETA 05:06

[5570/7081] ✓ SITC: 390 рядків |  78.66% | ETA 05:04

[5580/7081] ✓ SKHY: 1,324 рядків |  78.80% | ETA 05:02

[5590/7081] ✓ SKYA: 424 рядків |  78.94% | ETA 05:00

[5600/7081] – SKYT: empty |  79.08% | ETA 04:58

   • RAM · 🧠 RAM: 378.3 MB

   ⏳ перед flush · 🧠 RAM: 378.3 MB

💾 batch 20489 → 14,289 рядків (всього 1,355,567 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20489.csv.gz

   ✅ після flush · 🧠 RAM: 379.0 MB

[5610/7081] ✓ SLGL: 17 рядків |  79.23% | ETA 04:56

[5620/7081] ✓ SLNH: 582 рядків |  79.37% | ETA 04:53

[5630/7081] ✓ SLXN: 541 рядків |  79.51% | ETA 04:51

[5640/7081] ✓ SMC: 217 рядків |  79.65% | ETA 04:49

[5650/7081] ✓ SMH: 998 рядків |  79.79% | ETA 04:47

   • RAM · 🧠 RAM: 379.8 MB

   ⏳ перед flush · 🧠 RAM: 379.8 MB

💾 batch 20490 → 14,826 рядків (всього 1,370,393 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20490.csv.gz

   ✅ після flush · 🧠 RAM: 381.0 MB

[5660/7081] ✓ SMPL: 352 рядків |  79.93% | ETA 04:45

[5670/7081] ✓ SMWB: 190 рядків |  80.07% | ETA 04:43

[5680/7081] ✓ SNAP: 556 рядків |  80.21% | ETA 04:41

[5690/7081] ✓ SNDR: 314 рядків |  80.36% | ETA 04:39

[5700/7081] ✓ SNOU: 63 рядків |  80.50% | ETA 04:37

   • RAM · 🧠 RAM: 381.8 MB

   ⏳ перед flush · 🧠 RAM: 381.8 MB

💾 batch 20491 → 15,477 рядків (всього 1,385,870 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20491.csv.gz

   ✅ після flush · 🧠 RAM: 382.6 MB

[5710/7081] – SNYR: empty |  80.64% | ETA 04:35

[5720/7081] ✓ SOGP: 28 рядків |  80.78% | ETA 04:33

[5730/7081] ✓ SOLS: 368 рядків |  80.92% | ETA 04:32

[5740/7081] ✓ SOXL: 1,440 рядків |  81.06% | ETA 04:29

[5750/7081] ✓ SPB: 238 рядків |  81.20% | ETA 04:27

   • RAM · 🧠 RAM: 384.2 MB

   ⏳ перед flush · 🧠 RAM: 384.2 MB

💾 batch 20492 → 15,783 рядків (всього 1,401,653 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20492.csv.gz

   ✅ після flush · 🧠 RAM: 385.0 MB

[5760/7081] ✓ SPEM: 350 рядків |  81.34% | ETA 04:26

[5770/7081] ✓ SPMC: 26 рядків |  81.49% | ETA 04:23

[5780/7081] ✓ SPHQ: 393 рядків |  81.63% | ETA 04:21

[5790/7081] ✓ SPPL: 39 рядків |  81.77% | ETA 04:19

[5800/7081] ✓ SPSB: 340 рядків |  81.91% | ETA 04:17

   • RAM · 🧠 RAM: 386.5 MB

   ⏳ перед flush · 🧠 RAM: 386.5 MB

💾 batch 20493 → 14,393 рядків (всього 1,416,046 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20493.csv.gz

   ✅ після flush · 🧠 RAM: 387.7 MB

[5810/7081] ✓ SPUS: 309 рядків |  82.05% | ETA 04:15

[5820/7081] ✓ SPYU: 397 рядків |  82.19% | ETA 04:13

[5830/7081] ✓ SPYV: 389 рядків |  82.33% | ETA 04:11

[5840/7081] ✓ SR: 205 рядків |  82.47% | ETA 04:09

[5850/7081] ✓ SSMR: 249 рядків |  82.62% | ETA 04:07

   • RAM · 🧠 RAM: 389.3 MB

   ⏳ перед flush · 🧠 RAM: 389.3 MB

💾 batch 20494 → 16,132 рядків (всього 1,432,178 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20494.csv.gz

   ✅ після flush · 🧠 RAM: 390.1 MB

[5860/7081] ✓ SST: 140 рядків |  82.76% | ETA 04:05

[5870/7081] ✓ STCE: 159 рядків |  82.90% | ETA 04:03

[5880/7081] ✓ STEX: 229 рядків |  83.04% | ETA 04:01

[5890/7081] ✓ STLN: 314 рядків |  83.18% | ETA 03:59

[5900/7081] ✓ STRA: 170 рядків |  83.32% | ETA 03:57

   • RAM · 🧠 RAM: 389.7 MB

   ⏳ перед flush · 🧠 RAM: 389.7 MB

💾 batch 20495 → 11,918 рядків (всього 1,444,096 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20495.csv.gz

   ✅ після flush · 🧠 RAM: 390.3 MB

[5910/7081] ✓ STXS: 256 рядків |  83.46% | ETA 03:55

[5920/7081] ✓ STZ: 396 рядків |  83.60% | ETA 03:53

[5930/7081] ✓ SUZ: 361 рядків |  83.75% | ETA 03:51

[5940/7081] ✓ SVV: 307 рядків |  83.89% | ETA 03:49

[5950/7081] ✓ SWVL: 40 рядків |  84.03% | ETA 03:47

   • RAM · 🧠 RAM: 387.3 MB

   ⏳ перед flush · 🧠 RAM: 387.3 MB

💾 batch 20496 → 12,603 рядків (всього 1,456,699 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20496.csv.gz

   ✅ після flush · 🧠 RAM: 387.9 MB

[5960/7081] ✓ SYM: 424 рядків |  84.17% | ETA 03:45

[5970/7081] ✓ TAFM: 124 рядків |  84.31% | ETA 03:43

[5980/7081] ✓ TALO: 396 рядків |  84.45% | ETA 03:41

[5990/7081] ✓ TBF: 236 рядків |  84.59% | ETA 03:39

[6000/7081] ✓ TCAI: 63 рядків |  84.73% | ETA 03:37

   • RAM · 🧠 RAM: 382.8 MB

   ⏳ перед flush · 🧠 RAM: 382.8 MB

💾 batch 20497 → 11,112 рядків (всього 1,467,811 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20497.csv.gz

   ✅ після flush · 🧠 RAM: 382.6 MB

[6010/7081] ✓ TCOM: 419 рядків |  84.88% | ETA 03:35

[6020/7081] ✓ TDI: 58 рядків |  85.02% | ETA 03:33

[6030/7081] ✓ TDTH: 34 рядків |  85.16% | ETA 03:31

[6040/7081] ✓ TECK: 484 рядків |  85.30% | ETA 03:29

[6050/7081] ✓ TEO: 155 рядків |  85.44% | ETA 03:27

   • RAM · 🧠 RAM: 374.1 MB

   ⏳ перед flush · 🧠 RAM: 374.1 MB

💾 batch 20498 → 11,838 рядків (всього 1,479,649 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20498.csv.gz

   ✅ після flush · 🧠 RAM: 375.2 MB

[6060/7081] ✓ TFC: 396 рядків |  85.58% | ETA 03:25

[6070/7081] ✓ TGE: 301 рядків |  85.72% | ETA 03:23

[6080/7081] ✓ THFF: 88 рядків |  85.86% | ETA 03:21

[6090/7081] ✓ THNQ: 46 рядків |  86.00% | ETA 03:19

[6100/7081] ✓ TIP: 386 рядків |  86.15% | ETA 03:17

   • RAM · 🧠 RAM: 374.7 MB

   ⏳ перед flush · 🧠 RAM: 374.7 MB

💾 batch 20499 → 12,286 рядків (всього 1,491,935 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20499.csv.gz

   ✅ після flush · 🧠 RAM: 375.9 MB

[6110/7081] ✓ TLDR: 2 рядків |  86.29% | ETA 03:15

[6120/7081] ✓ TLX: 210 рядків |  86.43% | ETA 03:13

[6130/7081] ✓ TMCI: 100 рядків |  86.57% | ETA 03:11

[6140/7081] ✓ TMCR: 61 рядків |  86.71% | ETA 03:09

[6150/7081] ✓ TNGX: 373 рядків |  86.85% | ETA 03:07

   • RAM · 🧠 RAM: 375.7 MB

   ⏳ перед flush · 🧠 RAM: 375.7 MB

💾 batch 20500 → 11,991 рядків (всього 1,503,926 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20500.csv.gz

   ✅ після flush · 🧠 RAM: 376.3 MB

[6160/7081] ✓ TOPP: 156 рядків |  86.99% | ETA 03:05

[6170/7081] ✓ TPC: 183 рядків |  87.13% | ETA 03:03

[6180/7081] ✓ TRAW: 61 рядків |  87.28% | ETA 03:01

[6190/7081] ✓ TREX: 391 рядків |  87.42% | ETA 02:59

[6200/7081] ✓ TRN: 301 рядків |  87.56% | ETA 02:57

   • RAM · 🧠 RAM: 376.9 MB

   ⏳ перед flush · 🧠 RAM: 376.9 MB

💾 batch 20501 → 11,540 рядків (всього 1,515,466 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20501.csv.gz

   ✅ після flush · 🧠 RAM: 377.5 MB

[6210/7081] ✓ TROO: 113 рядків |  87.70% | ETA 02:55

[6220/7081] ✓ TRVG: 65 рядків |  87.84% | ETA 02:53

[6230/7081] ✓ TSHA: 392 рядків |  87.98% | ETA 02:51

[6240/7081] ✓ TSLW: 107 рядків |  88.12% | ETA 02:49

[6250/7081] ✓ TSMZ: 73 рядків |  88.26% | ETA 02:47

   • RAM · 🧠 RAM: 379.0 MB

   ⏳ перед flush · 🧠 RAM: 379.0 MB

💾 batch 20502 → 15,009 рядків (всього 1,530,475 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20502.csv.gz

   ✅ після flush · 🧠 RAM: 379.7 MB

[6260/7081] ✓ TSN: 402 рядків |  88.41% | ETA 02:45

[6270/7081] ✓ TT: 387 рядків |  88.55% | ETA 02:43

[6280/7081] ✓ TURB: 48 рядків |  88.69% | ETA 02:41

[6290/7081] ✓ TVRD: 65 рядків |  88.83% | ETA 02:39

[6300/7081] ✓ TWG: 1,065 рядків |  88.97% | ETA 02:37

   • RAM · 🧠 RAM: 380.0 MB

   ⏳ перед flush · 🧠 RAM: 380.0 MB

💾 batch 20503 → 11,100 рядків (всього 1,541,575 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20503.csv.gz

   ✅ після flush · 🧠 RAM: 380.6 MB

[6310/7081] ✓ TXT: 320 рядків |  89.11% | ETA 02:35

[6320/7081] ✓ TYO: 13 рядків |  89.25% | ETA 02:33

[6330/7081] ✓ UBEW: 4 рядків |  89.39% | ETA 02:31

[6340/7081] ✓ UCTT: 419 рядків |  89.54% | ETA 02:29

[6350/7081] ✓ UE: 313 рядків |  89.68% | ETA 02:27

   • RAM · 🧠 RAM: 380.8 MB

   ⏳ перед flush · 🧠 RAM: 380.8 MB

💾 batch 20504 → 11,367 рядків (всього 1,552,942 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20504.csv.gz

   ✅ після flush · 🧠 RAM: 381.3 MB

[6360/7081] ✓ UHT: 104 рядків |  89.82% | ETA 02:25

[6370/7081] ✓ ULH: 54 рядків |  89.96% | ETA 02:23

[6380/7081] ✓ UMMA: 77 рядків |  90.10% | ETA 02:21

[6390/7081] ✓ UNL: 26 рядків |  90.24% | ETA 02:19

[6400/7081] ✓ UPC: 17 рядків |  90.38% | ETA 02:17

   • RAM · 🧠 RAM: 381.8 MB

   ⏳ перед flush · 🧠 RAM: 381.8 MB

💾 batch 20505 → 11,112 рядків (всього 1,564,054 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20505.csv.gz

   ✅ після flush · 🧠 RAM: 382.4 MB

[6410/7081] ✓ URAA: 57 рядків |  90.52% | ETA 02:15

[6420/7081] – UROY_20260727: empty |  90.67% | ETA 02:13

[6430/7081] ✓ USB: 409 рядків |  90.81% | ETA 02:11

[6440/7081] ✓ USHY: 390 рядків |  90.95% | ETA 02:09

[6450/7081] ✓ USPH: 112 рядків |  91.09% | ETA 02:07

   • RAM · 🧠 RAM: 383.8 MB

   ⏳ перед flush · 🧠 RAM: 383.8 MB

💾 batch 20506 → 13,564 рядків (всього 1,577,618 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20506.csv.gz

   ✅ після flush · 🧠 RAM: 384.4 MB

[6460/7081] ✓ UTWO: 103 рядків |  91.23% | ETA 02:05

[6470/7081] ✓ UWMC: 412 рядків |  91.37% | ETA 02:03

[6480/7081] ✓ VABK: 18 рядків |  91.51% | ETA 02:01

[6490/7081] ✓ VAVX: 19 рядків |  91.65% | ETA 01:59

[6500/7081] ✓ VCR: 198 рядків |  91.79% | ETA 01:57

   • RAM · 🧠 RAM: 385.7 MB

   ⏳ перед flush · 🧠 RAM: 385.7 MB

💾 batch 20507 → 12,563 рядків (всього 1,590,181 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20507.csv.gz

   ✅ після flush · 🧠 RAM: 386.2 MB

[6510/7081] ✓ VCX: 314 рядків |  91.94% | ETA 01:55

[6520/7081] ✓ VERU: 98 рядків |  92.08% | ETA 01:53

[6530/7081] ✓ VFMO: 75 рядків |  92.22% | ETA 01:51

[6540/7081] ✓ VGZ: 308 рядків |  92.36% | ETA 01:48

[6550/7081] ✓ VHT: 354 рядків |  92.50% | ETA 01:46

   • RAM · 🧠 RAM: 386.1 MB

   ⏳ перед flush · 🧠 RAM: 386.1 MB

💾 batch 20508 → 13,308 рядків (всього 1,603,489 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20508.csv.gz

   ✅ після flush · 🧠 RAM: 387.2 MB

[6560/7081] ✓ VINP: 154 рядків |  92.64% | ETA 01:44

[6570/7081] ✓ VITL: 319 рядків |  92.78% | ETA 01:42

[6580/7081] ✓ VKTX: 505 рядків |  92.92% | ETA 01:40

[6590/7081] ✓ VNCE: 274 рядків |  93.07% | ETA 01:38

[6600/7081] ✓ VNOM: 390 рядків |  93.21% | ETA 01:36

   • RAM · 🧠 RAM: 387.8 MB

   ⏳ перед flush · 🧠 RAM: 387.8 MB

💾 batch 20509 → 13,560 рядків (всього 1,617,049 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20509.csv.gz

   ✅ після flush · 🧠 RAM: 388.4 MB

[6610/7081] ✓ VONG: 345 рядків |  93.35% | ETA 01:34

[6620/7081] ✓ VOYA: 262 рядків |  93.49% | ETA 01:32

[6630/7081] ✓ VRCA: 56 рядків |  93.63% | ETA 01:30

[6640/7081] ✓ VRTS: 144 рядків |  93.77% | ETA 01:28

[6650/7081] ✓ VSDA: 23 рядків |  93.91% | ETA 01:26

   • RAM · 🧠 RAM: 388.7 MB

   ⏳ перед flush · 🧠 RAM: 388.7 MB

💾 batch 20510 → 13,187 рядків (всього 1,630,236 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20510.csv.gz

   ✅ після flush · 🧠 RAM: 389.3 MB

[6660/7081] – VTAK: empty |  94.05% | ETA 01:24

[6670/7081] ✓ VTI: 541 рядків |  94.20% | ETA 01:22

[6680/7081] ✓ VTIP: 392 рядків |  94.34% | ETA 01:20

[6690/7081] ✓ VWO: 404 рядків |  94.48% | ETA 01:18

[6700/7081] ✓ WAB: 285 рядків |  94.62% | ETA 01:16

   • RAM · 🧠 RAM: 387.3 MB

   ⏳ перед flush · 🧠 RAM: 387.3 MB

💾 batch 20511 → 14,631 рядків (всього 1,644,867 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20511.csv.gz

   ✅ після flush · 🧠 RAM: 388.5 MB

[6710/7081] ✓ WAL: 364 рядків |  94.76% | ETA 01:14

[6720/7081] ✓ WB: 256 рядків |  94.90% | ETA 01:12

[6730/7081] ✓ WD: 221 рядків |  95.04% | ETA 01:10

[6740/7081] ✓ WEBS: 49 рядків |  95.18% | ETA 01:08

[6750/7081] ✓ WEAV: 339 рядків |  95.33% | ETA 01:06

   • RAM · 🧠 RAM: 371.3 MB

   ⏳ перед flush · 🧠 RAM: 371.3 MB

💾 batch 20512 → 10,449 рядків (всього 1,655,316 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20512.csv.gz

   ✅ після flush · 🧠 RAM: 371.8 MB

[6760/7081] ✓ WF: 108 рядків |  95.47% | ETA 01:04

[6770/7081] ✓ WH: 371 рядків |  95.61% | ETA 01:02

[6780/7081] ✓ WINA: 92 рядків |  95.75% | ETA 01:00

[6790/7081] ✓ WLDS: 62 рядків |  95.89% | ETA 00:58

[6800/7081] ✓ WOK: 102 рядків |  96.03% | ETA 00:56

   • RAM · 🧠 RAM: 368.0 MB

   ⏳ перед flush · 🧠 RAM: 368.0 MB

💾 batch 20513 → 13,044 рядків (всього 1,668,360 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20513.csv.gz

   ✅ після flush · 🧠 RAM: 368.6 MB

[6810/7081] ✓ WRAP: 170 рядків |  96.17% | ETA 00:54

[6820/7081] ✓ WSFS: 147 рядків |  96.31% | ETA 00:52

[6830/7081] ✓ WST: 249 рядків |  96.46% | ETA 00:50

[6840/7081] ✓ WTV: 225 рядків |  96.60% | ETA 00:48

[6850/7081] ✓ WWW: 253 рядків |  96.74% | ETA 00:46

   • RAM · 🧠 RAM: 369.9 MB

   ⏳ перед flush · 🧠 RAM: 369.9 MB

💾 batch 20514 → 13,881 рядків (всього 1,682,241 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20514.csv.gz

   ✅ після flush · 🧠 RAM: 370.6 MB

[6860/7081] ✓ XAIW: 14 рядків |  96.88% | ETA 00:44

[6870/7081] ✓ XBTY: 19 рядків |  97.02% | ETA 00:42

[6880/7081] ✓ XELB: 282 рядків |  97.16% | ETA 00:40

[6890/7081] ✓ XHR: 251 рядків |  97.30% | ETA 00:38

[6900/7081] ✓ XLE: 662 рядків |  97.44% | ETA 00:36

   • RAM · 🧠 RAM: 371.5 MB

   ⏳ перед flush · 🧠 RAM: 371.5 MB

💾 batch 20515 → 12,601 рядків (всього 1,694,842 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20515.csv.gz

   ✅ після flush · 🧠 RAM: 372.0 MB

[6910/7081] ✓ XLV: 454 рядків |  97.59% | ETA 00:34

[6920/7081] ✓ XNTK: 180 рядків |  97.73% | ETA 00:32

[6930/7081] ✓ XP: 412 рядків |  97.87% | ETA 00:30

[6940/7081] ✓ XPO: 282 рядків |  98.01% | ETA 00:28

[6950/7081] ✓ XSMO: 203 рядків |  98.15% | ETA 00:26

   • RAM · 🧠 RAM: 373.1 MB

   ⏳ перед flush · 🧠 RAM: 373.1 MB

💾 batch 20516 → 12,147 рядків (всього 1,706,989 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20516.csv.gz

   ✅ після flush · 🧠 RAM: 373.7 MB

[6960/7081] ✓ XSOE: 82 рядків |  98.29% | ETA 00:24

[6970/7081] ✓ XXI: 420 рядків |  98.43% | ETA 00:22

[6980/7081] ✓ XYLG: 46 рядків |  98.57% | ETA 00:20

[6990/7081] – YBMN: empty |  98.71% | ETA 00:18

[7000/7081] ✓ YLD: 158 рядків |  98.86% | ETA 00:16

   • RAM · 🧠 RAM: 372.6 MB

   ⏳ перед flush · 🧠 RAM: 372.6 MB

💾 batch 20517 → 7,735 рядків (всього 1,714,724 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20517.csv.gz

   ✅ після flush · 🧠 RAM: 373.0 MB

[7010/7081] ✓ YMT: 106 рядків |  99.00% | ETA 00:14

[7020/7081] ✓ YSPY: 12 рядків |  99.14% | ETA 00:12

[7030/7081] – YYGH: empty |  99.28% | ETA 00:10

[7040/7081] ✓ ZCSH: 366 рядків |  99.42% | ETA 00:08

[7050/7081] ✓ ZIM: 375 рядків |  99.56% | ETA 00:06

   • RAM · 🧠 RAM: 373.4 MB

   ⏳ перед flush · 🧠 RAM: 373.4 MB

💾 batch 20518 → 10,930 рядків (всього 1,725,654 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20518.csv.gz

   ✅ після flush · 🧠 RAM: 374.6 MB

[7060/7081] ✓ ZM: 403 рядків |  99.70% | ETA 00:04

[7070/7081] ✓ ZTO: 341 рядків |  99.84% | ETA 00:02

[7080/7081] ✓ ZYME: 263 рядків |  99.99% | ETA 00:00

[7081/7081] ✓ ZURA: 437 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 377.9 MB

💾 batch 20519 → 7,138 рядків (всього 1,732,792 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20519.csv.gz

   ✅ після flush · 🧠 RAM: 378.3 MB

   🔚 фінал · 🧠 RAM: 378.3 MB

🏁 Готово. Нових рядків: 1,732,792 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 23:48

In [18]:
# ================== FAST LOCAL POST-PROCESSING (no API calls) ==================
# Читання батчів робить pyarrow (нативний багатопотоковий CSV-парсер) замість
# pandas.read_csv, а premarket-фільтр і денні open/close рахуються за ОДИН прохід
# по gz-файлах замість двох.
import os, gc, glob, time, threading
from typing import Optional, List, Tuple

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.csv as pacsv
import pyarrow.compute as pc
import pyarrow.dataset as pads
from concurrent.futures import ThreadPoolExecutor

_INTRADAY_COLS = ["ticker", "dt", "o", "h", "l", "c", "v"]

# Парсимо у float64, щоб денні open/close збігалися з попередньою (pandas) реалізацією
# біт у біт; premarket-рядки перед записом кастимо назад у float32 — стара схема на диску.
_INTRADAY_TYPES = {
    "ticker": pa.string(), "dt": pa.string(),
    "o": pa.float64(), "h": pa.float64(), "l": pa.float64(),
    "c": pa.float64(), "v": pa.float64(),
}
_PREMARKET_SCHEMA = pa.schema([
    ("ticker", pa.string()), ("dt", pa.string()),
    ("o", pa.float32()), ("h", pa.float32()), ("l", pa.float32()),
    ("c", pa.float32()), ("v", pa.float32()),
])


# ---------- спільні хелпери для мерджів по тікеру (використовують клітинки 28/40/44) ----------
def _ticker_codes(s: pd.Series):
    """Факторизує колонку тікерів і нормалізує (strip+upper) ЛИШЕ унікальні значення.

    Повертає (codes, categories); codes[i] == -1 означає null. Сенс у тому, щоб
    strip/upper і словниковий пошук виконувались над ~10^3 унікальними тікерами,
    а не над ~10^6 рядками батча.
    """
    cat = s.astype("category")
    cats = pd.Index(cat.cat.categories.astype(str)).str.strip().str.upper()
    return cat.cat.codes.to_numpy(), cats


def _expand(values: np.ndarray, codes: np.ndarray, fill):
    """Розгортає масив «на категорію» назад «на рядок»; де codes == -1 ставить fill."""
    out = np.empty(codes.shape, dtype=values.dtype if values.dtype != object else object)
    valid = codes >= 0
    out[valid] = values[codes[valid]]
    if (~valid).any():
        out[~valid] = fill
    return out


def _map_by_ticker(codes: np.ndarray, cats: pd.Index, mapping: dict, numeric: bool):
    vals = cats.map(mapping)
    if numeric:
        vals = pd.to_numeric(pd.Series(vals), errors="coerce").to_numpy(dtype="float64")
        return _expand(vals, codes, np.nan)
    vals = np.asarray(pd.Series(vals).astype(object).to_numpy(), dtype=object)
    return _expand(vals, codes, None)


# ---------- читання intraday-батчів ----------
def _open_intraday_csv(path: str, block_size: int):
    return pacsv.open_csv(
        path,
        read_options=pacsv.ReadOptions(use_threads=True, block_size=block_size),
        convert_options=pacsv.ConvertOptions(
            include_columns=_INTRADAY_COLS, column_types=_INTRADAY_TYPES
        ),
    )


def _time_date_mask(dt_arr, start_time, end_time, date_min, date_max):
    t = pc.utf8_slice_codeunits(dt_arr, 11, 19)
    mask = pc.and_(pc.greater_equal(t, start_time), pc.less_equal(t, end_time))
    if date_min is not None or date_max is not None:
        d = pc.utf8_slice_codeunits(dt_arr, 0, 10)
        if date_min is not None:
            mask = pc.and_(mask, pc.greater_equal(d, date_min))
        if date_max is not None:
            mask = pc.and_(mask, pc.less_equal(d, date_max))
    return mask


def _oc_from_table(tbl: pa.Table) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Перший open у вікні 09:30–09:35 і останній close у 15:55–15:59 на (ticker, date)."""
    OPEN_FROM, OPEN_TO = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    hhmm = pc.utf8_slice_codeunits(tbl.column("dt"), 11, 16)
    m_o = pc.and_(pc.and_(pc.greater_equal(hhmm, OPEN_FROM), pc.less_equal(hhmm, OPEN_TO)),
                  pc.is_valid(tbl.column("o")))
    m_c = pc.and_(pc.and_(pc.greater_equal(hhmm, CLOSE_FROM), pc.less_equal(hhmm, CLOSE_TO)),
                  pc.is_valid(tbl.column("c")))

    def _reduce(mask, val_col, keep):
        sub = tbl.select(["ticker", "dt", val_col]).filter(mask)
        if sub.num_rows == 0:
            return pd.DataFrame(columns=["ticker", "date", "dt", val_col])
        d = sub.to_pandas()
        d["date"] = d["dt"].str.slice(0, 10)
        d = d.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep=keep)
        return d[["ticker", "date", "dt", val_col]]

    return _reduce(m_o, "o", "first"), _reduce(m_c, "c", "last")


def _finalize_oc(open_parts: List[pd.DataFrame], close_parts: List[pd.DataFrame]) -> pd.DataFrame:
    opens = (pd.concat(open_parts, ignore_index=True) if open_parts
             else pd.DataFrame(columns=["ticker", "date", "dt", "o"]))
    closes = (pd.concat(close_parts, ignore_index=True) if close_parts
              else pd.DataFrame(columns=["ticker", "date", "dt", "c"]))
    if len(opens):
        opens = opens.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="first")
    if len(closes):
        closes = closes.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="last")
    opens = opens[["ticker", "date", "o"]].rename(columns={"o": "open"})
    closes = closes[["ticker", "date", "c"]].rename(columns={"c": "close"})

    out = (opens.merge(closes, on=["ticker", "date"], how="outer")
                .sort_values(["ticker", "date"], kind="stable").reset_index(drop=True))
    out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)
    return out


def collect_premarket_and_oc(
    folder: str,
    out_path: str,
    oc_out_path: Optional[str] = None,
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    build_oc: bool = True,
    max_workers: int = 4,
    block_size: int = 64 << 20,
    compression: str = "snappy",
    sort_chunk: bool = True,
    verbose: bool = True,
):
    """ОДИН прохід по {folder}/{pattern}: пише відфільтровані рядки у out_path і
    (опційно) денні open/close у oc_out_path.

    Замінює пару collect_premarket_by_day_stream + build_oc_from_intraday_folder,
    які раніше читали й розтискали ті самі gz-файли двічі.

    Порядок рядків МІЖ файлами недетермінований (файли читаються паралельно).
    Це безпечно: усі наступні кроки — мерджі по ключах, а фінальний файл
    фізично сортується у клітинці 47. Для точного старого порядку — max_workers=1.
    """
    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    if os.path.exists(out_path):
        os.remove(out_path)

    t0 = time.time()
    lock = threading.Lock()
    state = {"writer": None, "in": 0, "out": 0, "files": 0}
    open_parts: List[pd.DataFrame] = []
    close_parts: List[pd.DataFrame] = []

    def _handle(path: str):
        reader = _open_intraday_csv(path, block_size)
        loc_open, loc_close = [], []
        n_in = n_out = 0
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            tbl = pa.Table.from_batches([rb])
            n_in += tbl.num_rows

            if build_oc:
                o_df, c_df = _oc_from_table(tbl)
                if len(o_df):
                    loc_open.append(o_df)
                if len(c_df):
                    loc_close.append(c_df)

            cut = tbl.filter(_time_date_mask(tbl.column("dt"), start_time, end_time,
                                             date_min, date_max))
            if cut.num_rows:
                cut = cut.cast(_PREMARKET_SCHEMA)
                if sort_chunk:
                    cut = cut.sort_by([("ticker", "ascending"), ("dt", "ascending")])
                n_out += cut.num_rows
                with lock:
                    if state["writer"] is None:
                        state["writer"] = pq.ParquetWriter(out_path, cut.schema,
                                                           compression=compression)
                    state["writer"].write_table(cut)

        with lock:
            state["in"] += n_in
            state["out"] += n_out
            state["files"] += 1
            open_parts.extend(loc_open)
            close_parts.extend(loc_close)
            if verbose:
                print(f"  [{state['files']}/{len(files)}] {os.path.basename(path)}  "
                      f"in={state['in']:,} out={state['out']:,} "
                      f"elapsed={time.time()-t0:,.1f}s", flush=True)

    rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]" if (date_min or date_max) else ""
    if verbose:
        print(f"▶️ START: {folder}/{pattern} → {out_path}  files={len(files)} "
              f"workers={max_workers}{rng_str}", flush=True)
    try:
        if max_workers and max_workers > 1:
            with ThreadPoolExecutor(max_workers=max_workers) as ex:
                list(ex.map(_handle, files))
        else:
            for p in files:
                _handle(p)
    finally:
        if state["writer"] is not None:
            state["writer"].close()

    df_oc = None
    if build_oc:
        df_oc = _finalize_oc(open_parts, close_parts)
        if oc_out_path:
            os.makedirs(os.path.dirname(oc_out_path) or ".", exist_ok=True)
            df_oc.to_parquet(oc_out_path, index=False)

    if verbose:
        print(f"✅ DONE  in={state['in']:,} → out={state['out']:,}  to {out_path}  "
              f"in {time.time()-t0:,.1f}s", flush=True)
    return out_path, df_oc


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,
    date_max: Optional[str] = None,
    aggregate: bool = False,
    chunksize: int = 200_000,          # лишено для сумісності виклику; pyarrow керує блоками сам
    compression: str = "snappy",
    log_every: int = 5,                # лишено для сумісності виклику
    sort_chunk: bool = True,
    max_workers: int = 4,
    verbose: bool = True,
):
    """Тонка обгортка над collect_premarket_and_oc (build_oc=False) — щоб старі
    виклики працювали без змін."""
    if aggregate:
        raise NotImplementedError("aggregate=True у цьому пайплайні не використовується")
    path, _ = collect_premarket_and_oc(
        folder, out_path, oc_out_path=None, pattern=pattern,
        start_time=start_time, end_time=end_time,
        date_min=date_min, date_max=date_max, build_oc=False,
        max_workers=max_workers, compression=compression,
        sort_chunk=sort_chunk, verbose=verbose,
    )
    return path

In [19]:
# Один прохід по gz-батчах: одразу і premarket-рядки, і денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,
    date_max=end_date_str,
    build_oc=True,
    max_workers=4,
)
print(df_oc.head())

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  files=20519 workers=4  date=[2026-07-19..2026-10-19]

  [1/20519] intraday_0003.csv.gz  in=727,885 out=0 elapsed=0.7s

  [2/20519] intraday_0004.csv.gz  in=1,470,913 out=0 elapsed=0.8s

  [3/20519] intraday_0001.csv.gz  in=2,446,740 out=0 elapsed=0.8s

  [4/20519] intraday_0002.csv.gz  in=3,333,452 out=0 elapsed=0.9s

  [5/20519] intraday_0007.csv.gz  in=4,094,033 out=0 elapsed=1.5s

  [6/20519] intraday_0005.csv.gz  in=4,968,024 out=0 elapsed=1.5s

  [7/20519] intraday_0006.csv.gz  in=5,923,107 out=0 elapsed=1.6s

  [8/20519] intraday_0008.csv.gz  in=6,732,671 out=0 elapsed=1.7s

  [9/20519] intraday_0011.csv.gz  in=7,471,310 out=0 elapsed=2.2s

  [10/20519] intraday_0009.csv.gz  in=8,411,136 out=0 elapsed=2.2s

  [11/20519] intraday_0010.csv.gz  in=9,348,724 out=0 elapsed=2.2s

  [12/20519] intraday_0012.csv.gz  in=10,202,410 out=0 elapsed=2.3s

  [13/20519] intraday_0015.csv.gz  in=10,806,484 out=0 elapsed=2.7s

  [14/20519] intraday_0014.csv.gz  in=11,471,803 out=0 elapsed=2.7s

  [15/20519] intraday_0013.csv.gz  in=12,333,647 out=0 elapsed=2.8s

  [16/20519] intraday_0016.csv.gz  in=13,369,434 out=0 elapsed=3.1s

  [17/20519] intraday_0018.csv.gz  in=14,058,532 out=0 elapsed=3.3s

  [18/20519] intraday_0019.csv.gz  in=14,795,001 out=0 elapsed=3.3s

  [19/20519] intraday_0017.csv.gz  in=15,723,943 out=0 elapsed=3.4s

  [20/20519] intraday_0020.csv.gz  in=16,555,781 out=0 elapsed=3.7s

  [21/20519] intraday_0022.csv.gz  in=17,287,747 out=0 elapsed=3.8s

  [22/20519] intraday_0021.csv.gz  in=18,114,555 out=0 elapsed=3.8s

  [23/20519] intraday_0023.csv.gz  in=18,895,557 out=0 elapsed=3.9s

  [24/20519] intraday_0024.csv.gz  in=19,686,597 out=0 elapsed=4.2s

  [25/20519] intraday_0025.csv.gz  in=20,416,242 out=0 elapsed=4.3s

  [26/20519] intraday_0027.csv.gz  in=21,080,210 out=0 elapsed=4.4s

  [27/20519] intraday_0026.csv.gz  in=21,935,669 out=0 elapsed=4.4s

  [28/20519] intraday_0028.csv.gz  in=22,943,087 out=0 elapsed=5.1s

  [29/20519] intraday_0031.csv.gz  in=23,677,097 out=0 elapsed=5.1s

  [30/20519] intraday_0029.csv.gz  in=24,623,614 out=0 elapsed=5.1s

  [31/20519] intraday_0030.csv.gz  in=25,543,444 out=0 elapsed=5.1s

  [32/20519] intraday_0034.csv.gz  in=26,230,726 out=0 elapsed=5.6s

  [33/20519] intraday_0032.csv.gz  in=27,046,628 out=0 elapsed=5.7s

  [34/20519] intraday_0035.csv.gz  in=27,865,784 out=0 elapsed=5.8s

  [35/20519] intraday_0033.csv.gz  in=28,741,745 out=0 elapsed=5.8s

  [36/20519] intraday_0037.csv.gz  in=29,414,856 out=0 elapsed=6.2s

  [37/20519] intraday_0036.csv.gz  in=30,234,721 out=0 elapsed=6.2s

  [38/20519] intraday_0038.csv.gz  in=30,924,778 out=0 elapsed=6.2s

  [39/20519] intraday_0039.csv.gz  in=31,684,289 out=0 elapsed=6.3s

  [40/20519] intraday_0040.csv.gz  in=32,407,718 out=0 elapsed=6.8s

  [41/20519] intraday_0043.csv.gz  in=33,119,568 out=0 elapsed=6.9s

  [42/20519] intraday_0041.csv.gz  in=34,013,644 out=0 elapsed=6.9s

  [43/20519] intraday_0042.csv.gz  in=34,960,739 out=0 elapsed=7.0s

  [44/20519] intraday_0046.csv.gz  in=35,775,830 out=0 elapsed=7.4s

  [45/20519] intraday_0044.csv.gz  in=36,581,365 out=0 elapsed=7.4s

  [46/20519] intraday_0045.csv.gz  in=37,383,804 out=0 elapsed=7.5s

  [47/20519] intraday_0047.csv.gz  in=38,250,311 out=0 elapsed=7.6s

  [48/20519] intraday_0048.csv.gz  in=38,906,436 out=0 elapsed=7.9s

  [49/20519] intraday_0050.csv.gz  in=39,739,068 out=0 elapsed=8.1s

  [50/20519] intraday_0049.csv.gz  in=40,684,592 out=0 elapsed=8.1s

  [51/20519] intraday_0051.csv.gz  in=41,414,383 out=0 elapsed=8.1s

  [52/20519] intraday_0052.csv.gz  in=42,279,351 out=0 elapsed=8.4s

  [53/20519] intraday_0053.csv.gz  in=42,998,896 out=0 elapsed=8.6s

  [54/20519] intraday_0054.csv.gz  in=43,729,514 out=0 elapsed=8.6s

  [55/20519] intraday_0055.csv.gz  in=44,542,383 out=0 elapsed=8.7s

  [56/20519] intraday_0056.csv.gz  in=45,360,329 out=0 elapsed=9.0s

  [57/20519] intraday_0057.csv.gz  in=46,118,655 out=0 elapsed=9.1s

  [58/20519] intraday_0058.csv.gz  in=46,830,377 out=0 elapsed=9.1s

  [59/20519] intraday_0059.csv.gz  in=47,587,522 out=0 elapsed=9.3s

  [60/20519] intraday_0060.csv.gz  in=48,264,439 out=0 elapsed=9.5s

  [61/20519] intraday_0062.csv.gz  in=49,011,023 out=0 elapsed=9.7s

  [62/20519] intraday_0061.csv.gz  in=50,022,323 out=0 elapsed=9.8s

  [63/20519] intraday_0063.csv.gz  in=50,975,856 out=0 elapsed=10.0s

  [64/20519] intraday_0064.csv.gz  in=51,861,073 out=0 elapsed=10.1s

  [65/20519] intraday_0065.csv.gz  in=52,657,022 out=0 elapsed=10.2s

  [66/20519] intraday_0066.csv.gz  in=53,344,110 out=0 elapsed=10.3s

  [67/20519] intraday_0067.csv.gz  in=54,114,222 out=0 elapsed=10.5s

  [68/20519] intraday_0068.csv.gz  in=54,938,820 out=0 elapsed=10.7s

  [69/20519] intraday_0070.csv.gz  in=55,597,571 out=0 elapsed=10.8s

  [70/20519] intraday_0069.csv.gz  in=56,497,048 out=0 elapsed=10.9s

  [71/20519] intraday_0071.csv.gz  in=57,135,058 out=0 elapsed=11.0s

  [72/20519] intraday_0072.csv.gz  in=57,879,667 out=0 elapsed=11.2s

  [73/20519] intraday_0073.csv.gz  in=58,674,810 out=0 elapsed=11.3s

  [74/20519] intraday_0074.csv.gz  in=59,409,405 out=0 elapsed=11.4s

  [75/20519] intraday_0075.csv.gz  in=60,167,330 out=0 elapsed=11.5s

  [76/20519] intraday_0076.csv.gz  in=60,866,670 out=0 elapsed=11.7s

  [77/20519] intraday_0077.csv.gz  in=61,676,095 out=0 elapsed=11.9s

  [78/20519] intraday_0078.csv.gz  in=62,736,689 out=0 elapsed=12.1s

  [79/20519] intraday_0079.csv.gz  in=63,655,294 out=0 elapsed=12.2s

  [80/20519] intraday_0080.csv.gz  in=64,355,814 out=0 elapsed=12.2s

  [81/20519] intraday_0081.csv.gz  in=65,173,353 out=0 elapsed=12.4s

  [82/20519] intraday_0082.csv.gz  in=65,962,271 out=0 elapsed=12.8s

  [83/20519] intraday_0083.csv.gz  in=66,748,390 out=0 elapsed=12.8s

  [84/20519] intraday_0085.csv.gz  in=67,522,552 out=0 elapsed=13.0s

  [85/20519] intraday_0084.csv.gz  in=68,693,048 out=0 elapsed=13.1s

  [86/20519] intraday_0086.csv.gz  in=69,620,846 out=0 elapsed=13.5s

  [87/20519] intraday_0087.csv.gz  in=70,564,187 out=0 elapsed=13.5s

  [88/20519] intraday_0088.csv.gz  in=71,397,243 out=0 elapsed=13.6s

  [89/20519] intraday_0089.csv.gz  in=72,281,904 out=0 elapsed=13.7s

  [90/20519] intraday_0090.csv.gz  in=73,069,473 out=0 elapsed=14.1s

  [91/20519] intraday_0093.csv.gz  in=73,885,132 out=0 elapsed=14.2s

  [92/20519] intraday_0091.csv.gz  in=74,814,860 out=0 elapsed=14.3s

  [93/20519] intraday_0092.csv.gz  in=75,647,498 out=0 elapsed=14.3s

  [94/20519] intraday_0094.csv.gz  in=76,528,738 out=0 elapsed=14.7s

  [95/20519] intraday_0095.csv.gz  in=77,378,774 out=0 elapsed=14.9s

  [96/20519] intraday_0096.csv.gz  in=78,260,543 out=0 elapsed=14.9s

  [97/20519] intraday_0097.csv.gz  in=79,032,923 out=0 elapsed=15.0s

  [98/20519] intraday_0098.csv.gz  in=79,802,827 out=0 elapsed=15.4s

  [99/20519] intraday_0100.csv.gz  in=80,600,542 out=0 elapsed=15.5s

  [100/20519] intraday_0101.csv.gz  in=81,532,270 out=0 elapsed=15.7s

  [101/20519] intraday_0099.csv.gz  in=82,593,388 out=0 elapsed=15.7s

  [102/20519] intraday_0102.csv.gz  in=83,527,121 out=0 elapsed=16.0s

  [103/20519] intraday_0103.csv.gz  in=84,317,945 out=0 elapsed=16.2s

  [104/20519] intraday_0104.csv.gz  in=85,159,844 out=0 elapsed=16.2s

  [105/20519] intraday_0105.csv.gz  in=86,032,104 out=0 elapsed=16.3s

  [106/20519] intraday_0106.csv.gz  in=86,821,848 out=0 elapsed=16.6s

  [107/20519] intraday_0108.csv.gz  in=87,616,449 out=0 elapsed=16.8s

  [108/20519] intraday_0107.csv.gz  in=88,679,847 out=0 elapsed=16.9s

  [109/20519] intraday_0109.csv.gz  in=89,619,231 out=0 elapsed=17.0s

  [110/20519] intraday_0110.csv.gz  in=90,640,909 out=0 elapsed=17.2s

  [111/20519] intraday_0111.csv.gz  in=91,427,941 out=0 elapsed=17.4s

  [112/20519] intraday_0113.csv.gz  in=92,190,652 out=0 elapsed=17.5s

  [113/20519] intraday_0112.csv.gz  in=93,022,660 out=0 elapsed=17.5s

  [114/20519] intraday_0114.csv.gz  in=93,859,984 out=0 elapsed=17.9s

  [115/20519] intraday_0115.csv.gz  in=94,616,153 out=0 elapsed=17.9s

  [116/20519] intraday_0117.csv.gz  in=95,401,469 out=0 elapsed=18.1s

  [117/20519] intraday_0116.csv.gz  in=96,350,237 out=0 elapsed=18.2s

  [118/20519] intraday_0119.csv.gz  in=97,075,034 out=0 elapsed=18.5s

  [119/20519] intraday_0118.csv.gz  in=98,245,742 out=0 elapsed=18.7s

  [120/20519] intraday_0120.csv.gz  in=99,105,343 out=0 elapsed=18.7s

  [121/20519] intraday_0121.csv.gz  in=100,150,376 out=0 elapsed=18.9s

  [122/20519] intraday_0122.csv.gz  in=100,938,876 out=0 elapsed=19.0s

  [123/20519] intraday_0123.csv.gz  in=101,790,604 out=0 elapsed=19.4s

  [124/20519] intraday_0124.csv.gz  in=102,767,055 out=0 elapsed=19.4s

  [125/20519] intraday_0125.csv.gz  in=103,648,833 out=0 elapsed=19.5s

  [126/20519] intraday_0126.csv.gz  in=104,596,744 out=0 elapsed=19.7s

  [127/20519] intraday_0127.csv.gz  in=105,314,012 out=0 elapsed=19.9s

  [128/20519] intraday_0128.csv.gz  in=106,066,285 out=0 elapsed=19.9s

  [129/20519] intraday_0129.csv.gz  in=106,926,182 out=0 elapsed=20.1s

  [130/20519] intraday_0130.csv.gz  in=107,748,465 out=0 elapsed=20.2s

  [131/20519] intraday_0134.csv.gz  in=107,796,616 out=0 elapsed=20.3s

  [132/20519] intraday_0135.csv.gz  in=107,812,974 out=0 elapsed=20.3s

  [133/20519] intraday_0136.csv.gz  in=107,831,664 out=0 elapsed=20.3s

  [134/20519] intraday_0137.csv.gz  in=107,843,715 out=0 elapsed=20.4s

  [135/20519] intraday_0138.csv.gz  in=107,856,245 out=0 elapsed=20.4s

  [136/20519] intraday_0139.csv.gz  in=107,869,929 out=0 elapsed=20.4s

  [137/20519] intraday_0140.csv.gz  in=107,884,836 out=0 elapsed=20.4s

  [138/20519] intraday_0131.csv.gz  in=108,639,628 out=0 elapsed=20.5s

  [139/20519] intraday_0141.csv.gz  in=108,652,214 out=0 elapsed=20.5s

  [140/20519] intraday_0132.csv.gz  in=109,314,490 out=0 elapsed=20.5s

  [141/20519] intraday_0142.csv.gz  in=109,328,468 out=0 elapsed=20.5s

  [142/20519] intraday_0143.csv.gz  in=109,343,799 out=0 elapsed=20.5s

  [143/20519] intraday_0145.csv.gz  in=109,359,005 out=0 elapsed=20.5s

  [144/20519] intraday_0144.csv.gz  in=109,391,725 out=0 elapsed=20.5s

  [145/20519] intraday_0146.csv.gz  in=109,423,506 out=0 elapsed=20.5s

  [146/20519] intraday_0147.csv.gz  in=109,438,479 out=0 elapsed=20.5s

  [147/20519] intraday_0148.csv.gz  in=109,449,779 out=0 elapsed=20.5s

  [148/20519] intraday_0149.csv.gz  in=109,461,076 out=0 elapsed=20.6s

  [149/20519] intraday_0150.csv.gz  in=109,477,550 out=0 elapsed=20.6s

  [150/20519] intraday_0151.csv.gz  in=109,493,543 out=0 elapsed=20.6s

  [151/20519] intraday_0152.csv.gz  in=109,505,698 out=0 elapsed=20.6s

  [152/20519] intraday_0154.csv.gz  in=109,520,522 out=0 elapsed=20.6s

  [153/20519] intraday_0153.csv.gz  in=109,532,249 out=0 elapsed=20.6s

  [154/20519] intraday_0155.csv.gz  in=109,547,829 out=0 elapsed=20.6s

  [155/20519] intraday_0156.csv.gz  in=109,561,190 out=0 elapsed=20.7s

  [156/20519] intraday_0157.csv.gz  in=109,573,389 out=0 elapsed=20.7s

  [157/20519] intraday_0133.csv.gz  in=110,354,290 out=0 elapsed=20.7s

  [158/20519] intraday_0159.csv.gz  in=110,365,902 out=0 elapsed=20.7s

  [159/20519] intraday_0158.csv.gz  in=110,395,835 out=0 elapsed=20.7s

  [160/20519] intraday_0160.csv.gz  in=110,408,274 out=0 elapsed=20.7s

  [161/20519] intraday_0161.csv.gz  in=110,420,588 out=0 elapsed=20.7s

  [162/20519] intraday_0162.csv.gz  in=110,437,874 out=0 elapsed=20.8s

  [163/20519] intraday_0163.csv.gz  in=110,455,080 out=0 elapsed=20.8s

  [164/20519] intraday_0164.csv.gz  in=110,470,271 out=0 elapsed=20.8s

  [165/20519] intraday_0165.csv.gz  in=110,482,894 out=0 elapsed=20.8s

  [166/20519] intraday_0166.csv.gz  in=110,496,504 out=0 elapsed=20.8s

  [167/20519] intraday_0168.csv.gz  in=110,507,361 out=0 elapsed=20.8s

  [168/20519] intraday_0169.csv.gz  in=110,521,692 out=0 elapsed=20.8s

  [169/20519] intraday_0170.csv.gz  in=110,537,232 out=0 elapsed=20.8s

  [170/20519] intraday_0167.csv.gz  in=110,558,073 out=0 elapsed=20.8s

  [171/20519] intraday_0171.csv.gz  in=110,569,494 out=0 elapsed=20.9s

  [172/20519] intraday_0172.csv.gz  in=110,580,228 out=0 elapsed=20.9s

  [173/20519] intraday_0174.csv.gz  in=110,593,032 out=0 elapsed=20.9s

  [174/20519] intraday_0173.csv.gz  in=110,605,870 out=0 elapsed=20.9s

  [175/20519] intraday_0175.csv.gz  in=110,620,244 out=0 elapsed=20.9s

  [176/20519] intraday_0176.csv.gz  in=110,637,126 out=0 elapsed=20.9s

  [177/20519] intraday_0178.csv.gz  in=110,651,069 out=0 elapsed=20.9s

  [178/20519] intraday_0177.csv.gz  in=110,666,020 out=0 elapsed=20.9s

  [179/20519] intraday_0179.csv.gz  in=110,679,724 out=0 elapsed=20.9s

  [180/20519] intraday_0180.csv.gz  in=110,693,457 out=0 elapsed=20.9s

  [181/20519] intraday_0182.csv.gz  in=110,705,949 out=0 elapsed=21.0s

  [182/20519] intraday_0181.csv.gz  in=110,736,763 out=0 elapsed=21.0s

  [183/20519] intraday_0183.csv.gz  in=110,754,307 out=0 elapsed=21.0s

  [184/20519] intraday_0185.csv.gz  in=110,768,360 out=0 elapsed=21.0s

  [185/20519] intraday_0184.csv.gz  in=110,784,589 out=0 elapsed=21.0s

  [186/20519] intraday_0186.csv.gz  in=110,799,047 out=0 elapsed=21.0s

  [187/20519] intraday_0188.csv.gz  in=110,822,516 out=0 elapsed=21.0s

  [188/20519] intraday_0187.csv.gz  in=110,836,242 out=0 elapsed=21.0s

  [189/20519] intraday_0189.csv.gz  in=110,849,387 out=0 elapsed=21.1s

  [190/20519] intraday_0191.csv.gz  in=110,863,852 out=0 elapsed=21.1s

  [191/20519] intraday_0190.csv.gz  in=110,877,560 out=0 elapsed=21.1s

  [192/20519] intraday_0192.csv.gz  in=110,889,613 out=0 elapsed=21.1s

  [193/20519] intraday_0193.csv.gz  in=110,901,524 out=0 elapsed=21.1s

  [194/20519] intraday_0195.csv.gz  in=110,916,175 out=0 elapsed=21.1s

  [195/20519] intraday_0194.csv.gz  in=110,926,310 out=0 elapsed=21.1s

  [196/20519] intraday_0197.csv.gz  in=110,940,802 out=0 elapsed=21.1s

  [197/20519] intraday_0198.csv.gz  in=110,956,224 out=0 elapsed=21.2s

  [198/20519] intraday_0199.csv.gz  in=110,971,004 out=0 elapsed=21.2s

  [199/20519] intraday_0200.csv.gz  in=110,982,427 out=0 elapsed=21.2s

  [200/20519] intraday_0196.csv.gz  in=110,995,048 out=0 elapsed=21.2s

  [201/20519] intraday_0201.csv.gz  in=111,008,704 out=0 elapsed=21.2s

  [202/20519] intraday_0202.csv.gz  in=111,023,231 out=0 elapsed=21.2s

  [203/20519] intraday_0203.csv.gz  in=111,036,171 out=0 elapsed=21.2s

  [204/20519] intraday_0204.csv.gz  in=111,047,240 out=0 elapsed=21.2s

  [205/20519] intraday_0205.csv.gz  in=111,057,791 out=0 elapsed=21.2s

  [206/20519] intraday_0207.csv.gz  in=111,071,387 out=0 elapsed=21.3s

  [207/20519] intraday_0206.csv.gz  in=111,084,627 out=0 elapsed=21.3s

  [208/20519] intraday_0208.csv.gz  in=111,096,777 out=0 elapsed=21.3s

  [209/20519] intraday_0209.csv.gz  in=111,109,213 out=0 elapsed=21.3s

  [210/20519] intraday_0213.csv.gz  in=111,123,683 out=0 elapsed=21.3s

  [211/20519] intraday_0211.csv.gz  in=111,139,144 out=0 elapsed=21.4s

  [212/20519] intraday_0210.csv.gz  in=111,150,494 out=0 elapsed=21.4s

  [213/20519] intraday_0212.csv.gz  in=111,170,551 out=0 elapsed=21.4s

  [214/20519] intraday_0214.csv.gz  in=111,183,384 out=0 elapsed=21.4s

  [215/20519] intraday_0215.csv.gz  in=111,197,300 out=0 elapsed=21.4s

  [216/20519] intraday_0218.csv.gz  in=111,216,309 out=0 elapsed=21.4s

  [217/20519] intraday_0216.csv.gz  in=111,230,577 out=0 elapsed=21.4s

  [218/20519] intraday_0217.csv.gz  in=111,244,102 out=0 elapsed=21.5s

  [219/20519] intraday_0220.csv.gz  in=111,259,305 out=0 elapsed=21.5s

  [220/20519] intraday_0219.csv.gz  in=111,271,333 out=0 elapsed=21.5s

  [221/20519] intraday_0221.csv.gz  in=111,288,427 out=0 elapsed=21.5s

  [222/20519] intraday_0222.csv.gz  in=111,302,939 out=0 elapsed=21.5s

  [223/20519] intraday_0224.csv.gz  in=111,316,587 out=0 elapsed=21.5s

  [224/20519] intraday_0225.csv.gz  in=111,331,028 out=0 elapsed=21.5s

  [225/20519] intraday_0223.csv.gz  in=111,345,732 out=0 elapsed=21.6s

  [226/20519] intraday_0226.csv.gz  in=111,358,887 out=0 elapsed=21.6s

  [227/20519] intraday_0227.csv.gz  in=111,373,404 out=0 elapsed=21.6s

  [228/20519] intraday_0228.csv.gz  in=111,389,838 out=0 elapsed=21.6s

  [229/20519] intraday_0229.csv.gz  in=111,403,698 out=0 elapsed=21.6s

  [230/20519] intraday_0230.csv.gz  in=111,418,264 out=0 elapsed=21.6s

  [231/20519] intraday_0231.csv.gz  in=111,430,225 out=0 elapsed=21.6s

  [232/20519] intraday_0232.csv.gz  in=111,444,220 out=0 elapsed=21.7s

  [233/20519] intraday_0234.csv.gz  in=111,459,020 out=0 elapsed=21.7s

  [234/20519] intraday_0233.csv.gz  in=111,476,182 out=0 elapsed=21.7s

  [235/20519] intraday_0235.csv.gz  in=111,490,802 out=0 elapsed=21.7s

  [236/20519] intraday_0236.csv.gz  in=111,507,721 out=0 elapsed=21.7s

  [237/20519] intraday_0237.csv.gz  in=111,520,281 out=0 elapsed=21.7s

  [238/20519] intraday_0238.csv.gz  in=111,537,182 out=0 elapsed=21.7s

  [239/20519] intraday_0240.csv.gz  in=111,551,572 out=0 elapsed=21.8s

  [240/20519] intraday_0239.csv.gz  in=111,568,283 out=0 elapsed=21.8s

  [241/20519] intraday_0241.csv.gz  in=111,584,827 out=0 elapsed=21.8s

  [242/20519] intraday_0245.csv.gz  in=111,597,123 out=0 elapsed=21.8s

  [243/20519] intraday_0242.csv.gz  in=111,610,695 out=0 elapsed=21.8s

  [244/20519] intraday_0244.csv.gz  in=111,627,351 out=0 elapsed=21.8s

  [245/20519] intraday_0243.csv.gz  in=111,654,087 out=0 elapsed=21.8s

  [246/20519] intraday_0246.csv.gz  in=111,669,545 out=0 elapsed=21.8s

  [247/20519] intraday_0248.csv.gz  in=111,683,104 out=0 elapsed=21.9s

  [248/20519] intraday_0247.csv.gz  in=111,697,128 out=0 elapsed=21.9s

  [249/20519] intraday_0249.csv.gz  in=111,712,496 out=0 elapsed=21.9s

  [250/20519] intraday_0250.csv.gz  in=111,728,198 out=0 elapsed=21.9s

  [251/20519] intraday_0253.csv.gz  in=111,741,545 out=0 elapsed=21.9s

  [252/20519] intraday_0251.csv.gz  in=111,754,681 out=0 elapsed=21.9s

  [253/20519] intraday_0252.csv.gz  in=111,775,789 out=0 elapsed=21.9s

  [254/20519] intraday_0256.csv.gz  in=111,791,494 out=0 elapsed=22.0s

  [255/20519] intraday_0257.csv.gz  in=111,806,747 out=0 elapsed=22.0s

  [256/20519] intraday_0254.csv.gz  in=111,821,168 out=0 elapsed=22.0s

  [257/20519] intraday_0258.csv.gz  in=111,837,314 out=0 elapsed=22.0s

  [258/20519] intraday_0255.csv.gz  in=111,855,418 out=0 elapsed=22.0s

  [259/20519] intraday_0260.csv.gz  in=111,871,653 out=0 elapsed=22.0s

  [260/20519] intraday_0259.csv.gz  in=111,886,263 out=0 elapsed=22.1s

  [261/20519] intraday_0261.csv.gz  in=111,900,357 out=0 elapsed=22.1s

  [262/20519] intraday_0262.csv.gz  in=111,912,297 out=0 elapsed=22.1s

  [263/20519] intraday_0263.csv.gz  in=111,926,807 out=0 elapsed=22.1s

  [264/20519] intraday_0264.csv.gz  in=111,940,725 out=0 elapsed=22.1s

  [265/20519] intraday_0265.csv.gz  in=111,955,763 out=0 elapsed=22.1s

  [266/20519] intraday_0267.csv.gz  in=111,969,026 out=0 elapsed=22.2s

  [267/20519] intraday_0266.csv.gz  in=111,977,949 out=0 elapsed=22.2s

  [268/20519] intraday_0268.csv.gz  in=111,978,303 out=0 elapsed=22.2s

  [269/20519] intraday_0271.csv.gz  in=112,194,521 out=0 elapsed=22.4s

  [270/20519] intraday_0272.csv.gz  in=112,427,225 out=0 elapsed=22.4s

  [271/20519] intraday_0270.csv.gz  in=112,691,292 out=0 elapsed=22.4s

  [272/20519] intraday_0269.csv.gz  in=112,987,663 out=0 elapsed=22.4s

  [273/20519] intraday_0273.csv.gz  in=113,246,304 out=0 elapsed=22.6s

  [274/20519] intraday_0275.csv.gz  in=113,479,352 out=0 elapsed=22.6s

  [275/20519] intraday_0276.csv.gz  in=113,730,868 out=0 elapsed=22.6s

  [276/20519] intraday_0274.csv.gz  in=114,011,989 out=0 elapsed=22.7s

  [277/20519] intraday_0278.csv.gz  in=114,258,113 out=0 elapsed=22.8s

  [278/20519] intraday_0279.csv.gz  in=114,500,722 out=0 elapsed=22.9s

  [279/20519] intraday_0277.csv.gz  in=114,801,886 out=0 elapsed=22.9s

  [280/20519] intraday_0280.csv.gz  in=115,056,079 out=0 elapsed=22.9s

  [281/20519] intraday_0282.csv.gz  in=115,248,860 out=0 elapsed=23.0s

  [282/20519] intraday_0283.csv.gz  in=115,448,136 out=0 elapsed=23.0s

  [283/20519] intraday_0286.csv.gz  in=115,486,870 out=0 elapsed=23.1s

  [284/20519] intraday_0281.csv.gz  in=115,748,047 out=0 elapsed=23.1s

  [285/20519] intraday_0284.csv.gz  in=116,043,246 out=0 elapsed=23.1s

  [286/20519] intraday_0285.csv.gz  in=116,298,084 out=0 elapsed=23.2s

  [287/20519] intraday_0288.csv.gz  in=116,518,901 out=0 elapsed=23.3s

  [288/20519] intraday_0287.csv.gz  in=116,746,745 out=0 elapsed=23.3s

  [289/20519] intraday_0289.csv.gz  in=116,965,439 out=0 elapsed=23.3s

  [290/20519] intraday_0290.csv.gz  in=117,225,315 out=0 elapsed=23.4s

  [291/20519] intraday_0291.csv.gz  in=117,445,345 out=0 elapsed=23.4s

  [292/20519] intraday_0292.csv.gz  in=117,685,256 out=0 elapsed=23.5s

  [293/20519] intraday_0293.csv.gz  in=117,927,992 out=0 elapsed=23.5s

  [294/20519] intraday_0294.csv.gz  in=118,143,729 out=0 elapsed=23.6s

  [295/20519] intraday_0295.csv.gz  in=118,357,943 out=0 elapsed=23.6s

  [296/20519] intraday_0296.csv.gz  in=118,563,185 out=0 elapsed=23.7s

  [297/20519] intraday_0297.csv.gz  in=118,843,298 out=0 elapsed=23.7s

  [298/20519] intraday_0298.csv.gz  in=119,126,473 out=0 elapsed=23.9s

  [299/20519] intraday_0300.csv.gz  in=119,350,117 out=0 elapsed=23.9s

  [300/20519] intraday_0299.csv.gz  in=119,612,107 out=0 elapsed=23.9s

  [301/20519] intraday_0302.csv.gz  in=119,667,069 out=0 elapsed=23.9s

  [302/20519] intraday_0301.csv.gz  in=119,886,957 out=0 elapsed=23.9s

  [303/20519] intraday_0304.csv.gz  in=120,123,356 out=0 elapsed=24.1s

  [304/20519] intraday_0305.csv.gz  in=120,358,027 out=0 elapsed=24.1s

  [305/20519] intraday_0306.csv.gz  in=120,604,925 out=0 elapsed=24.1s

  [306/20519] intraday_0303.csv.gz  in=120,902,289 out=0 elapsed=24.2s

  [307/20519] intraday_0307.csv.gz  in=121,125,738 out=0 elapsed=24.4s

  [308/20519] intraday_0308.csv.gz  in=121,351,202 out=0 elapsed=24.4s

  [309/20519] intraday_0309.csv.gz  in=121,589,830 out=0 elapsed=24.4s

  [310/20519] intraday_0310.csv.gz  in=121,811,036 out=0 elapsed=24.4s

  [311/20519] intraday_0311.csv.gz  in=122,090,746 out=0 elapsed=24.7s

  [312/20519] intraday_0313.csv.gz  in=122,328,043 out=0 elapsed=24.7s

  [313/20519] intraday_0312.csv.gz  in=122,629,607 out=0 elapsed=24.7s

  [314/20519] intraday_0314.csv.gz  in=122,890,640 out=0 elapsed=24.7s

  [315/20519] intraday_0316.csv.gz  in=123,139,424 out=0 elapsed=24.9s

  [316/20519] intraday_0315.csv.gz  in=123,403,821 out=0 elapsed=24.9s

  [317/20519] intraday_0318.csv.gz  in=123,637,922 out=0 elapsed=24.9s

  [318/20519] intraday_0317.csv.gz  in=123,900,660 out=0 elapsed=25.0s

  [319/20519] intraday_0320.csv.gz  in=124,140,879 out=0 elapsed=25.1s

  [320/20519] intraday_0319.csv.gz  in=124,416,353 out=0 elapsed=25.1s

  [321/20519] intraday_0321.csv.gz  in=124,669,219 out=0 elapsed=25.2s

  [322/20519] intraday_0322.csv.gz  in=124,909,648 out=0 elapsed=25.2s

  [323/20519] intraday_0323.csv.gz  in=125,155,264 out=0 elapsed=25.4s

  [324/20519] intraday_0324.csv.gz  in=125,389,255 out=0 elapsed=25.4s

  [325/20519] intraday_0325.csv.gz  in=125,649,135 out=0 elapsed=25.4s

  [326/20519] intraday_0326.csv.gz  in=125,911,356 out=0 elapsed=25.4s

  [327/20519] intraday_0327.csv.gz  in=126,118,825 out=0 elapsed=25.5s

  [328/20519] intraday_0330.csv.gz  in=126,315,329 out=0 elapsed=25.6s

  [329/20519] intraday_0328.csv.gz  in=126,570,754 out=0 elapsed=25.6s

  [330/20519] intraday_0329.csv.gz  in=126,779,582 out=0 elapsed=25.6s

  [331/20519] intraday_0331.csv.gz  in=127,046,519 out=0 elapsed=25.8s

  [332/20519] intraday_0333.csv.gz  in=127,253,545 out=0 elapsed=25.8s

  [333/20519] intraday_0332.csv.gz  in=127,538,683 out=0 elapsed=25.8s

  [334/20519] intraday_0334.csv.gz  in=127,816,232 out=0 elapsed=25.8s

  [335/20519] intraday_0336.csv.gz  in=128,018,952 out=0 elapsed=26.0s

  [336/20519] intraday_0335.csv.gz  in=128,295,496 out=0 elapsed=26.0s

  [337/20519] intraday_0337.csv.gz  in=128,525,452 out=0 elapsed=26.0s

  [338/20519] intraday_0338.csv.gz  in=128,783,286 out=0 elapsed=26.1s

  [339/20519] intraday_0340.csv.gz  in=128,981,471 out=0 elapsed=26.2s

  [340/20519] intraday_0341.csv.gz  in=129,199,442 out=0 elapsed=26.2s

  [341/20519] intraday_0339.csv.gz  in=129,458,823 out=0 elapsed=26.3s

  [342/20519] intraday_0342.csv.gz  in=129,667,620 out=0 elapsed=26.3s

  [343/20519] intraday_0346.csv.gz  in=129,849,968 out=0 elapsed=26.4s

  [344/20519] intraday_0343.csv.gz  in=130,081,697 out=0 elapsed=26.4s

  [345/20519] intraday_0344.csv.gz  in=130,320,714 out=0 elapsed=26.5s

  [346/20519] intraday_0345.csv.gz  in=130,559,285 out=0 elapsed=26.5s

  [347/20519] intraday_0347.csv.gz  in=130,772,959 out=0 elapsed=26.6s

  [348/20519] intraday_0348.csv.gz  in=131,024,833 out=0 elapsed=26.6s

  [349/20519] intraday_0350.csv.gz  in=131,261,296 out=0 elapsed=26.6s

  [350/20519] intraday_0349.csv.gz  in=131,570,921 out=0 elapsed=26.7s

  [351/20519] intraday_0351.csv.gz  in=131,797,285 out=0 elapsed=26.7s

  [352/20519] intraday_0352.csv.gz  in=132,033,883 out=0 elapsed=26.8s

  [353/20519] intraday_0353.csv.gz  in=132,292,867 out=0 elapsed=26.8s

  [354/20519] intraday_0354.csv.gz  in=132,523,180 out=0 elapsed=26.9s

  [355/20519] intraday_0355.csv.gz  in=132,836,273 out=0 elapsed=26.9s

  [356/20519] intraday_0356.csv.gz  in=133,077,260 out=0 elapsed=27.0s

  [357/20519] intraday_0357.csv.gz  in=133,365,265 out=0 elapsed=27.1s

  [358/20519] intraday_0358.csv.gz  in=133,649,154 out=0 elapsed=27.1s

  [359/20519] intraday_0359.csv.gz  in=133,915,035 out=0 elapsed=27.1s

  [360/20519] intraday_0360.csv.gz  in=134,168,226 out=0 elapsed=27.2s

  [361/20519] intraday_0361.csv.gz  in=134,407,423 out=0 elapsed=27.2s

  [362/20519] intraday_0362.csv.gz  in=134,663,024 out=0 elapsed=27.3s

  [363/20519] intraday_0363.csv.gz  in=134,908,995 out=0 elapsed=27.3s

  [364/20519] intraday_0364.csv.gz  in=135,155,263 out=0 elapsed=27.4s

  [365/20519] intraday_0365.csv.gz  in=135,380,830 out=0 elapsed=27.4s

  [366/20519] intraday_0366.csv.gz  in=135,644,767 out=0 elapsed=27.5s

  [367/20519] intraday_0367.csv.gz  in=135,928,713 out=0 elapsed=27.5s

  [368/20519] intraday_0368.csv.gz  in=136,162,187 out=0 elapsed=27.5s

  [369/20519] intraday_0369.csv.gz  in=136,435,160 out=0 elapsed=27.6s

  [370/20519] intraday_0370.csv.gz  in=136,756,824 out=0 elapsed=27.7s

  [371/20519] intraday_0372.csv.gz  in=137,023,680 out=0 elapsed=27.7s

  [372/20519] intraday_0371.csv.gz  in=137,296,332 out=0 elapsed=27.7s

  [373/20519] intraday_0373.csv.gz  in=137,544,174 out=0 elapsed=27.8s

  [374/20519] intraday_0375.csv.gz  in=137,747,513 out=0 elapsed=27.9s

  [375/20519] intraday_0374.csv.gz  in=138,017,550 out=0 elapsed=27.9s

  [376/20519] intraday_0376.csv.gz  in=138,328,425 out=0 elapsed=28.0s

  [377/20519] intraday_0377.csv.gz  in=138,565,665 out=0 elapsed=28.0s

  [378/20519] intraday_0378.csv.gz  in=138,834,795 out=0 elapsed=28.1s

  [379/20519] intraday_0379.csv.gz  in=139,087,787 out=0 elapsed=28.1s

  [380/20519] intraday_0380.csv.gz  in=139,374,542 out=0 elapsed=28.2s

  [381/20519] intraday_0381.csv.gz  in=139,648,162 out=0 elapsed=28.2s

  [382/20519] intraday_0382.csv.gz  in=139,904,999 out=0 elapsed=28.3s

  [383/20519] intraday_0383.csv.gz  in=140,179,278 out=0 elapsed=28.4s

  [384/20519] intraday_0384.csv.gz  in=140,428,102 out=0 elapsed=28.4s

  [385/20519] intraday_0385.csv.gz  in=140,640,779 out=0 elapsed=28.4s

  [386/20519] intraday_0386.csv.gz  in=140,878,294 out=0 elapsed=28.5s

  [387/20519] intraday_0387.csv.gz  in=141,147,253 out=0 elapsed=28.6s

  [388/20519] intraday_0388.csv.gz  in=141,399,520 out=0 elapsed=28.6s

  [389/20519] intraday_0389.csv.gz  in=141,725,055 out=0 elapsed=28.7s

  [390/20519] intraday_0390.csv.gz  in=141,949,153 out=0 elapsed=28.7s

  [391/20519] intraday_0391.csv.gz  in=142,203,569 out=0 elapsed=28.8s

  [392/20519] intraday_0392.csv.gz  in=142,457,409 out=0 elapsed=28.8s

  [393/20519] intraday_0393.csv.gz  in=142,721,977 out=0 elapsed=28.9s

  [394/20519] intraday_0394.csv.gz  in=142,966,664 out=0 elapsed=28.9s

  [395/20519] intraday_0395.csv.gz  in=143,253,685 out=0 elapsed=29.0s

  [396/20519] intraday_0396.csv.gz  in=143,532,614 out=0 elapsed=29.0s

  [397/20519] intraday_0397.csv.gz  in=143,777,948 out=0 elapsed=29.1s

  [398/20519] intraday_0398.csv.gz  in=144,034,957 out=0 elapsed=29.1s

  [399/20519] intraday_0399.csv.gz  in=144,258,829 out=0 elapsed=29.2s

  [400/20519] intraday_0400.csv.gz  in=144,480,592 out=0 elapsed=29.2s

  [401/20519] intraday_0401.csv.gz  in=144,678,165 out=0 elapsed=29.2s

  [402/20519] intraday_0402.csv.gz  in=144,938,220 out=0 elapsed=29.3s

  [403/20519] intraday_0404.csv.gz  in=145,099,518 out=0 elapsed=29.3s

  [404/20519] intraday_0406.csv.gz  in=145,114,230 out=0 elapsed=29.3s

  [405/20519] intraday_0403.csv.gz  in=145,327,551 out=0 elapsed=29.3s

  [406/20519] intraday_0408.csv.gz  in=145,339,818 out=0 elapsed=29.4s

  [407/20519] intraday_0407.csv.gz  in=145,364,245 out=0 elapsed=29.4s

  [408/20519] intraday_0409.csv.gz  in=145,377,611 out=0 elapsed=29.4s

  [409/20519] intraday_0410.csv.gz  in=145,392,730 out=0 elapsed=29.4s

  [410/20519] intraday_0411.csv.gz  in=145,408,587 out=0 elapsed=29.4s

  [411/20519] intraday_0412.csv.gz  in=145,419,651 out=0 elapsed=29.4s

  [412/20519] intraday_0413.csv.gz  in=145,432,635 out=0 elapsed=29.4s

  [413/20519] intraday_0405.csv.gz  in=145,657,039 out=0 elapsed=29.4s

  [414/20519] intraday_0414.csv.gz  in=145,671,610 out=0 elapsed=29.4s

  [415/20519] intraday_0415.csv.gz  in=145,684,409 out=0 elapsed=29.4s

  [416/20519] intraday_0417.csv.gz  in=145,697,884 out=0 elapsed=29.5s

  [417/20519] intraday_0418.csv.gz  in=145,712,190 out=0 elapsed=29.5s

  [418/20519] intraday_0416.csv.gz  in=145,723,588 out=0 elapsed=29.5s

  [419/20519] intraday_0419.csv.gz  in=145,734,865 out=0 elapsed=29.5s

  [420/20519] intraday_0420.csv.gz  in=145,746,540 out=0 elapsed=29.5s

  [421/20519] intraday_0421.csv.gz  in=145,761,843 out=0 elapsed=29.5s

  [422/20519] intraday_0422.csv.gz  in=145,775,162 out=0 elapsed=29.5s

  [423/20519] intraday_0424.csv.gz  in=145,786,361 out=0 elapsed=29.5s

  [424/20519] intraday_0423.csv.gz  in=145,797,862 out=0 elapsed=29.5s

  [425/20519] intraday_0426.csv.gz  in=145,809,862 out=0 elapsed=29.5s

  [426/20519] intraday_0425.csv.gz  in=145,821,626 out=0 elapsed=29.6s

  [427/20519] intraday_0427.csv.gz  in=145,833,678 out=0 elapsed=29.6s

  [428/20519] intraday_0428.csv.gz  in=145,846,867 out=0 elapsed=29.6s

  [429/20519] intraday_0429.csv.gz  in=145,859,925 out=0 elapsed=29.6s

  [430/20519] intraday_0430.csv.gz  in=145,870,744 out=0 elapsed=29.6s

  [431/20519] intraday_0431.csv.gz  in=145,882,155 out=0 elapsed=29.6s

  [432/20519] intraday_0432.csv.gz  in=145,893,068 out=0 elapsed=29.6s

  [433/20519] intraday_0436.csv.gz  in=145,905,375 out=0 elapsed=29.6s

  [434/20519] intraday_0433.csv.gz  in=145,919,951 out=0 elapsed=29.6s

  [435/20519] intraday_0434.csv.gz  in=145,935,727 out=0 elapsed=29.7s

  [436/20519] intraday_0435.csv.gz  in=145,951,958 out=0 elapsed=29.7s

  [437/20519] intraday_0438.csv.gz  in=145,964,938 out=0 elapsed=29.7s

  [438/20519] intraday_0437.csv.gz  in=145,976,928 out=0 elapsed=29.7s

  [439/20519] intraday_0440.csv.gz  in=145,989,184 out=0 elapsed=29.7s

  [440/20519] intraday_0439.csv.gz  in=146,007,004 out=0 elapsed=29.8s

  [441/20519] intraday_0441.csv.gz  in=146,018,926 out=0 elapsed=29.8s

  [442/20519] intraday_0443.csv.gz  in=146,030,660 out=0 elapsed=29.8s

  [443/20519] intraday_0442.csv.gz  in=146,044,273 out=0 elapsed=29.8s

  [444/20519] intraday_0444.csv.gz  in=146,056,615 out=0 elapsed=29.8s

  [445/20519] intraday_0445.csv.gz  in=146,071,013 out=0 elapsed=29.8s

  [446/20519] intraday_0448.csv.gz  in=146,084,529 out=0 elapsed=29.9s

  [447/20519] intraday_0446.csv.gz  in=146,098,093 out=0 elapsed=29.9s

  [448/20519] intraday_0447.csv.gz  in=146,112,265 out=0 elapsed=29.9s

  [449/20519] intraday_0449.csv.gz  in=146,149,966 out=0 elapsed=29.9s

  [450/20519] intraday_0451.csv.gz  in=146,162,551 out=0 elapsed=29.9s

  [451/20519] intraday_0450.csv.gz  in=146,175,913 out=0 elapsed=29.9s

  [452/20519] intraday_0452.csv.gz  in=146,194,390 out=0 elapsed=29.9s

  [453/20519] intraday_0453.csv.gz  in=146,206,987 out=0 elapsed=29.9s

  [454/20519] intraday_0454.csv.gz  in=146,219,751 out=0 elapsed=29.9s

  [455/20519] intraday_0455.csv.gz  in=146,243,311 out=0 elapsed=29.9s

  [456/20519] intraday_0456.csv.gz  in=146,255,603 out=0 elapsed=29.9s

  [457/20519] intraday_0457.csv.gz  in=146,269,716 out=0 elapsed=30.0s

  [458/20519] intraday_0458.csv.gz  in=146,282,797 out=0 elapsed=30.0s

  [459/20519] intraday_0460.csv.gz  in=146,298,542 out=0 elapsed=30.0s

  [460/20519] intraday_0459.csv.gz  in=146,311,892 out=0 elapsed=30.0s

  [461/20519] intraday_0461.csv.gz  in=146,324,208 out=0 elapsed=30.0s

  [462/20519] intraday_0463.csv.gz  in=146,336,696 out=0 elapsed=30.0s

  [463/20519] intraday_0462.csv.gz  in=146,350,280 out=0 elapsed=30.0s

  [464/20519] intraday_0464.csv.gz  in=146,362,048 out=0 elapsed=30.0s

  [465/20519] intraday_0465.csv.gz  in=146,387,954 out=0 elapsed=30.0s

  [466/20519] intraday_0468.csv.gz  in=146,399,917 out=0 elapsed=30.0s

  [467/20519] intraday_0467.csv.gz  in=146,417,186 out=0 elapsed=30.1s

  [468/20519] intraday_0466.csv.gz  in=146,429,806 out=0 elapsed=30.1s

  [469/20519] intraday_0469.csv.gz  in=146,444,443 out=0 elapsed=30.1s

  [470/20519] intraday_0470.csv.gz  in=146,459,130 out=0 elapsed=30.1s

  [471/20519] intraday_0471.csv.gz  in=146,471,756 out=0 elapsed=30.1s

  [472/20519] intraday_0472.csv.gz  in=146,483,702 out=0 elapsed=30.1s

  [473/20519] intraday_0473.csv.gz  in=146,495,640 out=0 elapsed=30.1s

  [474/20519] intraday_0474.csv.gz  in=146,508,636 out=0 elapsed=30.1s

  [475/20519] intraday_0477.csv.gz  in=146,517,892 out=0 elapsed=30.1s

  [476/20519] intraday_0475.csv.gz  in=146,530,984 out=0 elapsed=30.1s

  [477/20519] intraday_0476.csv.gz  in=146,542,494 out=0 elapsed=30.1s

  [478/20519] intraday_0478.csv.gz  in=146,554,934 out=0 elapsed=30.1s

  [479/20519] intraday_0479.csv.gz  in=146,567,951 out=0 elapsed=30.2s

  [480/20519] intraday_0481.csv.gz  in=146,580,204 out=0 elapsed=30.2s

  [481/20519] intraday_0480.csv.gz  in=146,591,926 out=0 elapsed=30.2s

  [482/20519] intraday_0482.csv.gz  in=146,603,171 out=0 elapsed=30.2s

  [483/20519] intraday_0483.csv.gz  in=146,613,850 out=0 elapsed=30.2s

  [484/20519] intraday_0485.csv.gz  in=146,631,235 out=0 elapsed=30.2s

  [485/20519] intraday_0484.csv.gz  in=146,643,216 out=0 elapsed=30.2s

  [486/20519] intraday_0486.csv.gz  in=146,655,077 out=0 elapsed=30.2s

  [487/20519] intraday_0487.csv.gz  in=146,665,512 out=0 elapsed=30.2s

  [488/20519] intraday_0488.csv.gz  in=146,679,315 out=0 elapsed=30.2s

  [489/20519] intraday_0489.csv.gz  in=146,691,816 out=0 elapsed=30.2s

  [490/20519] intraday_0490.csv.gz  in=146,709,671 out=0 elapsed=30.3s

  [491/20519] intraday_0491.csv.gz  in=146,724,538 out=0 elapsed=30.3s

  [492/20519] intraday_0492.csv.gz  in=146,738,727 out=0 elapsed=30.3s

  [493/20519] intraday_0495.csv.gz  in=146,752,304 out=0 elapsed=30.3s

  [494/20519] intraday_0494.csv.gz  in=146,767,084 out=0 elapsed=30.3s

  [495/20519] intraday_0493.csv.gz  in=146,781,319 out=0 elapsed=30.3s

  [496/20519] intraday_0496.csv.gz  in=146,796,225 out=0 elapsed=30.3s

  [497/20519] intraday_0497.csv.gz  in=146,815,798 out=0 elapsed=30.3s

  [498/20519] intraday_0498.csv.gz  in=146,828,986 out=0 elapsed=30.3s

  [499/20519] intraday_0499.csv.gz  in=146,840,301 out=0 elapsed=30.3s

  [500/20519] intraday_0500.csv.gz  in=146,860,626 out=0 elapsed=30.4s

  [501/20519] intraday_0502.csv.gz  in=146,877,748 out=0 elapsed=30.4s

  [502/20519] intraday_0503.csv.gz  in=146,891,386 out=0 elapsed=30.4s

  [503/20519] intraday_0501.csv.gz  in=146,910,524 out=0 elapsed=30.4s

  [504/20519] intraday_0504.csv.gz  in=146,923,190 out=0 elapsed=30.4s

  [505/20519] intraday_0505.csv.gz  in=146,938,528 out=0 elapsed=30.4s

  [506/20519] intraday_0507.csv.gz  in=146,954,063 out=0 elapsed=30.4s

  [507/20519] intraday_0508.csv.gz  in=146,983,208 out=0 elapsed=30.4s

  [508/20519] intraday_0509.csv.gz  in=146,999,268 out=0 elapsed=30.4s

  [509/20519] intraday_0506.csv.gz  in=147,035,549 out=0 elapsed=30.4s

  [510/20519] intraday_0511.csv.gz  in=147,049,308 out=0 elapsed=30.5s

  [511/20519] intraday_0510.csv.gz  in=147,060,675 out=0 elapsed=30.5s

  [512/20519] intraday_0513.csv.gz  in=147,073,349 out=0 elapsed=30.5s

  [513/20519] intraday_0512.csv.gz  in=147,090,371 out=0 elapsed=30.5s

  [514/20519] intraday_0515.csv.gz  in=147,105,173 out=0 elapsed=30.5s

  [515/20519] intraday_0514.csv.gz  in=147,122,880 out=0 elapsed=30.5s

  [516/20519] intraday_0517.csv.gz  in=147,139,540 out=0 elapsed=30.5s

  [517/20519] intraday_0516.csv.gz  in=147,154,561 out=0 elapsed=30.5s

  [518/20519] intraday_0519.csv.gz  in=147,168,169 out=0 elapsed=30.6s

  [519/20519] intraday_0518.csv.gz  in=147,180,329 out=0 elapsed=30.6s

  [520/20519] intraday_0521.csv.gz  in=147,193,289 out=0 elapsed=30.6s

  [521/20519] intraday_0520.csv.gz  in=147,204,598 out=0 elapsed=30.6s

  [522/20519] intraday_0523.csv.gz  in=147,219,410 out=0 elapsed=30.6s

  [523/20519] intraday_0522.csv.gz  in=147,232,671 out=0 elapsed=30.6s

  [524/20519] intraday_0524.csv.gz  in=147,245,780 out=0 elapsed=30.6s

  [525/20519] intraday_0525.csv.gz  in=147,261,573 out=0 elapsed=30.6s

  [526/20519] intraday_0526.csv.gz  in=147,274,492 out=0 elapsed=30.6s

  [527/20519] intraday_0527.csv.gz  in=147,287,469 out=0 elapsed=30.6s

  [528/20519] intraday_0529.csv.gz  in=147,299,814 out=0 elapsed=30.7s

  [529/20519] intraday_0528.csv.gz  in=147,316,770 out=0 elapsed=30.7s

  [530/20519] intraday_0530.csv.gz  in=147,331,059 out=0 elapsed=30.7s

  [531/20519] intraday_0531.csv.gz  in=147,347,109 out=0 elapsed=30.7s

  [532/20519] intraday_0532.csv.gz  in=147,361,302 out=0 elapsed=30.7s

  [533/20519] intraday_0534.csv.gz  in=147,375,725 out=0 elapsed=30.7s

  [534/20519] intraday_0533.csv.gz  in=147,390,514 out=0 elapsed=30.7s

  [535/20519] intraday_0535.csv.gz  in=147,401,061 out=0 elapsed=30.7s

  [536/20519] intraday_0536.csv.gz  in=147,412,623 out=0 elapsed=30.7s

  [537/20519] intraday_0537.csv.gz  in=147,423,684 out=0 elapsed=30.8s

  [538/20519] intraday_0539.csv.gz  in=147,434,680 out=0 elapsed=30.8s

  [539/20519] intraday_0538.csv.gz  in=147,448,480 out=0 elapsed=30.8s

  [540/20519] intraday_0540.csv.gz  in=147,458,505 out=0 elapsed=30.8s

  [541/20519] intraday_0541.csv.gz  in=147,466,999 out=0 elapsed=30.8s

  [542/20519] intraday_0542.csv.gz  in=147,508,845 out=0 elapsed=30.9s

  [543/20519] intraday_0544.csv.gz  in=147,535,726 out=0 elapsed=30.9s

  [544/20519] intraday_0543.csv.gz  in=147,565,316 out=0 elapsed=30.9s

  [545/20519] intraday_0545.csv.gz  in=147,606,543 out=0 elapsed=30.9s

  [546/20519] intraday_0549.csv.gz  in=147,634,133 out=0 elapsed=30.9s

  [547/20519] intraday_0548.csv.gz  in=147,658,073 out=0 elapsed=30.9s

  [548/20519] intraday_0546.csv.gz  in=147,689,491 out=0 elapsed=30.9s

  [549/20519] intraday_0547.csv.gz  in=147,723,194 out=0 elapsed=30.9s

  [550/20519] intraday_0551.csv.gz  in=147,750,728 out=0 elapsed=31.0s

  [551/20519] intraday_0552.csv.gz  in=147,774,767 out=0 elapsed=31.0s

  [552/20519] intraday_0550.csv.gz  in=147,804,284 out=0 elapsed=31.0s

  [553/20519] intraday_0553.csv.gz  in=147,832,832 out=0 elapsed=31.0s

  [554/20519] intraday_0555.csv.gz  in=147,855,311 out=0 elapsed=31.0s

  [555/20519] intraday_0556.csv.gz  in=147,879,085 out=0 elapsed=31.0s

  [556/20519] intraday_0554.csv.gz  in=147,910,090 out=0 elapsed=31.0s

  [557/20519] intraday_0557.csv.gz  in=147,941,618 out=0 elapsed=31.1s

  [558/20519] intraday_0558.csv.gz  in=147,970,209 out=0 elapsed=31.1s

  [559/20519] intraday_0560.csv.gz  in=147,994,077 out=0 elapsed=31.1s

  [560/20519] intraday_0559.csv.gz  in=148,020,950 out=0 elapsed=31.1s

  [561/20519] intraday_0561.csv.gz  in=148,048,023 out=0 elapsed=31.1s

  [562/20519] intraday_0562.csv.gz  in=148,073,086 out=0 elapsed=31.1s

  [563/20519] intraday_0565.csv.gz  in=148,100,339 out=0 elapsed=31.1s

  [564/20519] intraday_0563.csv.gz  in=148,125,108 out=0 elapsed=31.1s

  [565/20519] intraday_0564.csv.gz  in=148,152,228 out=0 elapsed=31.2s

  [566/20519] intraday_0567.csv.gz  in=148,175,399 out=0 elapsed=31.2s

  [567/20519] intraday_0566.csv.gz  in=148,198,952 out=0 elapsed=31.2s

  [568/20519] intraday_0568.csv.gz  in=148,219,961 out=0 elapsed=31.2s

  [569/20519] intraday_0569.csv.gz  in=148,251,292 out=0 elapsed=31.2s

  [570/20519] intraday_0570.csv.gz  in=148,284,544 out=0 elapsed=31.2s

  [571/20519] intraday_0571.csv.gz  in=148,316,989 out=0 elapsed=31.3s

  [572/20519] intraday_0572.csv.gz  in=148,341,303 out=0 elapsed=31.3s

  [573/20519] intraday_0573.csv.gz  in=148,367,608 out=0 elapsed=31.3s

  [574/20519] intraday_0574.csv.gz  in=148,395,071 out=0 elapsed=31.3s

  [575/20519] intraday_0575.csv.gz  in=148,428,911 out=0 elapsed=31.3s

  [576/20519] intraday_0576.csv.gz  in=148,459,676 out=0 elapsed=31.3s

  [577/20519] intraday_0578.csv.gz  in=148,491,700 out=0 elapsed=31.3s

  [578/20519] intraday_0577.csv.gz  in=148,517,233 out=0 elapsed=31.3s

  [579/20519] intraday_0580.csv.gz  in=148,543,926 out=0 elapsed=31.3s

  [580/20519] intraday_0581.csv.gz  in=148,576,672 out=0 elapsed=31.4s

  [581/20519] intraday_0582.csv.gz  in=148,607,706 out=0 elapsed=31.4s

  [582/20519] intraday_0579.csv.gz  in=148,659,685 out=0 elapsed=31.4s

  [583/20519] intraday_0583.csv.gz  in=148,688,678 out=0 elapsed=31.4s

  [584/20519] intraday_0585.csv.gz  in=148,714,730 out=0 elapsed=31.4s

  [585/20519] intraday_0584.csv.gz  in=148,745,268 out=0 elapsed=31.4s

  [586/20519] intraday_0586.csv.gz  in=148,772,890 out=0 elapsed=31.4s

  [587/20519] intraday_0587.csv.gz  in=148,798,828 out=0 elapsed=31.4s

  [588/20519] intraday_0589.csv.gz  in=148,827,976 out=0 elapsed=31.5s

  [589/20519] intraday_0588.csv.gz  in=148,879,943 out=0 elapsed=31.5s

  [590/20519] intraday_0590.csv.gz  in=148,910,881 out=0 elapsed=31.5s

  [591/20519] intraday_0591.csv.gz  in=148,938,696 out=0 elapsed=31.5s

  [592/20519] intraday_0592.csv.gz  in=148,966,176 out=0 elapsed=31.5s

  [593/20519] intraday_0594.csv.gz  in=148,992,313 out=0 elapsed=31.5s

  [594/20519] intraday_0595.csv.gz  in=149,019,311 out=0 elapsed=31.5s

  [595/20519] intraday_0596.csv.gz  in=149,044,484 out=0 elapsed=31.5s

  [596/20519] intraday_0593.csv.gz  in=149,080,692 out=0 elapsed=31.6s

  [597/20519] intraday_0597.csv.gz  in=149,107,419 out=0 elapsed=31.6s

  [598/20519] intraday_0598.csv.gz  in=149,135,059 out=0 elapsed=31.6s

  [599/20519] intraday_0600.csv.gz  in=149,159,346 out=0 elapsed=31.6s

  [600/20519] intraday_0599.csv.gz  in=149,185,832 out=0 elapsed=31.6s

  [601/20519] intraday_0602.csv.gz  in=149,208,272 out=0 elapsed=31.6s

  [602/20519] intraday_0601.csv.gz  in=149,232,632 out=0 elapsed=31.6s

  [603/20519] intraday_0603.csv.gz  in=149,266,332 out=0 elapsed=31.7s

  [604/20519] intraday_0604.csv.gz  in=149,292,076 out=0 elapsed=31.7s

  [605/20519] intraday_0605.csv.gz  in=149,320,593 out=0 elapsed=31.7s

  [606/20519] intraday_0608.csv.gz  in=149,343,387 out=0 elapsed=31.7s

  [607/20519] intraday_0606.csv.gz  in=149,375,298 out=0 elapsed=31.7s

  [608/20519] intraday_0607.csv.gz  in=149,423,867 out=0 elapsed=31.7s

  [609/20519] intraday_0609.csv.gz  in=149,449,906 out=0 elapsed=31.8s

  [610/20519] intraday_0610.csv.gz  in=149,475,762 out=0 elapsed=31.8s

  [611/20519] intraday_0611.csv.gz  in=149,505,510 out=0 elapsed=31.8s

  [612/20519] intraday_0612.csv.gz  in=149,528,210 out=0 elapsed=31.8s

  [613/20519] intraday_0613.csv.gz  in=149,549,726 out=0 elapsed=31.8s

  [614/20519] intraday_0614.csv.gz  in=149,575,053 out=0 elapsed=31.8s

  [615/20519] intraday_0615.csv.gz  in=149,609,820 out=0 elapsed=31.8s

  [616/20519] intraday_0617.csv.gz  in=149,639,185 out=0 elapsed=31.9s

  [617/20519] intraday_0616.csv.gz  in=149,663,849 out=0 elapsed=31.9s

  [618/20519] intraday_0618.csv.gz  in=149,684,038 out=0 elapsed=31.9s

  [619/20519] intraday_0619.csv.gz  in=149,706,447 out=0 elapsed=31.9s

  [620/20519] intraday_0620.csv.gz  in=149,741,936 out=0 elapsed=31.9s

  [621/20519] intraday_0622.csv.gz  in=149,768,779 out=0 elapsed=31.9s

  [622/20519] intraday_0621.csv.gz  in=149,803,181 out=0 elapsed=31.9s

  [623/20519] intraday_0623.csv.gz  in=149,829,559 out=0 elapsed=32.0s

  [624/20519] intraday_0624.csv.gz  in=149,859,203 out=0 elapsed=32.0s

  [625/20519] intraday_0625.csv.gz  in=149,888,290 out=0 elapsed=32.0s

  [626/20519] intraday_0626.csv.gz  in=149,918,669 out=0 elapsed=32.0s

  [627/20519] intraday_0627.csv.gz  in=149,952,541 out=0 elapsed=32.1s

  [628/20519] intraday_0629.csv.gz  in=149,986,473 out=0 elapsed=32.1s

  [629/20519] intraday_0628.csv.gz  in=150,021,198 out=0 elapsed=32.1s

  [630/20519] intraday_0630.csv.gz  in=150,051,815 out=0 elapsed=32.1s

  [631/20519] intraday_0631.csv.gz  in=150,082,344 out=0 elapsed=32.1s

  [632/20519] intraday_0633.csv.gz  in=150,110,623 out=0 elapsed=32.1s

  [633/20519] intraday_0632.csv.gz  in=150,137,613 out=0 elapsed=32.1s

  [634/20519] intraday_0634.csv.gz  in=150,170,587 out=0 elapsed=32.1s

  [635/20519] intraday_0636.csv.gz  in=150,195,227 out=0 elapsed=32.1s

  [636/20519] intraday_0635.csv.gz  in=150,223,517 out=0 elapsed=32.1s

  [637/20519] intraday_0638.csv.gz  in=150,257,083 out=0 elapsed=32.2s

  [638/20519] intraday_0637.csv.gz  in=150,287,667 out=0 elapsed=32.2s

  [639/20519] intraday_0639.csv.gz  in=150,316,577 out=0 elapsed=32.2s

  [640/20519] intraday_0640.csv.gz  in=150,344,888 out=0 elapsed=32.2s

  [641/20519] intraday_0642.csv.gz  in=150,376,509 out=0 elapsed=32.2s

  [642/20519] intraday_0641.csv.gz  in=150,406,279 out=0 elapsed=32.2s

  [643/20519] intraday_0643.csv.gz  in=150,440,063 out=0 elapsed=32.2s

  [644/20519] intraday_0646.csv.gz  in=150,466,121 out=0 elapsed=32.3s

  [645/20519] intraday_0644.csv.gz  in=150,497,193 out=0 elapsed=32.3s

  [646/20519] intraday_0645.csv.gz  in=150,530,150 out=0 elapsed=32.3s

  [647/20519] intraday_0647.csv.gz  in=150,559,265 out=0 elapsed=32.3s

  [648/20519] intraday_0650.csv.gz  in=150,590,404 out=0 elapsed=32.3s

  [649/20519] intraday_0648.csv.gz  in=150,619,570 out=0 elapsed=32.3s

  [650/20519] intraday_0649.csv.gz  in=150,647,955 out=0 elapsed=32.3s

  [651/20519] intraday_0651.csv.gz  in=150,672,868 out=0 elapsed=32.3s

  [652/20519] intraday_0653.csv.gz  in=150,707,869 out=0 elapsed=32.4s

  [653/20519] intraday_0654.csv.gz  in=150,735,041 out=0 elapsed=32.4s

  [654/20519] intraday_0655.csv.gz  in=150,763,620 out=0 elapsed=32.4s

  [655/20519] intraday_0652.csv.gz  in=150,796,374 out=0 elapsed=32.4s

  [656/20519] intraday_0656.csv.gz  in=150,827,694 out=0 elapsed=32.4s

  [657/20519] intraday_0658.csv.gz  in=150,853,274 out=0 elapsed=32.4s

  [658/20519] intraday_0657.csv.gz  in=150,880,261 out=0 elapsed=32.4s

  [659/20519] intraday_0659.csv.gz  in=150,912,920 out=0 elapsed=32.5s

  [660/20519] intraday_0660.csv.gz  in=150,940,951 out=0 elapsed=32.5s

  [661/20519] intraday_0662.csv.gz  in=150,967,623 out=0 elapsed=32.5s

  [662/20519] intraday_0661.csv.gz  in=151,019,866 out=0 elapsed=32.5s

  [663/20519] intraday_0664.csv.gz  in=151,052,104 out=0 elapsed=32.5s

  [664/20519] intraday_0663.csv.gz  in=151,082,311 out=0 elapsed=32.5s

  [665/20519] intraday_0665.csv.gz  in=151,112,109 out=0 elapsed=32.6s

  [666/20519] intraday_0666.csv.gz  in=151,145,019 out=0 elapsed=32.6s

  [667/20519] intraday_0667.csv.gz  in=151,180,660 out=0 elapsed=32.6s

  [668/20519] intraday_0668.csv.gz  in=151,209,545 out=0 elapsed=32.6s

  [669/20519] intraday_0669.csv.gz  in=151,238,489 out=0 elapsed=32.6s

  [670/20519] intraday_0671.csv.gz  in=151,271,212 out=0 elapsed=32.6s

  [671/20519] intraday_0672.csv.gz  in=151,300,892 out=0 elapsed=32.6s

  [672/20519] intraday_0670.csv.gz  in=151,330,979 out=0 elapsed=32.6s

  [673/20519] intraday_0673.csv.gz  in=151,354,334 out=0 elapsed=32.6s

  [674/20519] intraday_0675.csv.gz  in=151,374,813 out=0 elapsed=32.7s

  [675/20519] intraday_0674.csv.gz  in=151,406,524 out=0 elapsed=32.7s

  [676/20519] intraday_0676.csv.gz  in=151,429,101 out=0 elapsed=32.7s

  [677/20519] intraday_0677.csv.gz  in=151,447,334 out=0 elapsed=32.7s

  [678/20519] intraday_0681.csv.gz  in=151,566,858 out=0 elapsed=32.8s

  [679/20519] intraday_0680.csv.gz  in=151,694,372 out=0 elapsed=32.8s

  [680/20519] intraday_0679.csv.gz  in=151,854,187 out=0 elapsed=32.8s

  [681/20519] intraday_0678.csv.gz  in=152,035,572 out=0 elapsed=32.8s

  [682/20519] intraday_0684.csv.gz  in=152,155,614 out=0 elapsed=32.9s

  [683/20519] intraday_0682.csv.gz  in=152,303,931 out=0 elapsed=32.9s

  [684/20519] intraday_0683.csv.gz  in=152,464,695 out=0 elapsed=33.0s

  [685/20519] intraday_0685.csv.gz  in=152,597,012 out=0 elapsed=33.0s

  [686/20519] intraday_0686.csv.gz  in=152,741,778 out=0 elapsed=33.1s

  [687/20519] intraday_0687.csv.gz  in=152,884,704 out=0 elapsed=33.1s

  [688/20519] intraday_0689.csv.gz  in=153,026,645 out=0 elapsed=33.1s

  [689/20519] intraday_0688.csv.gz  in=153,154,517 out=0 elapsed=33.1s

  [690/20519] intraday_0692.csv.gz  in=153,255,887 out=0 elapsed=33.2s

  [691/20519] intraday_0691.csv.gz  in=153,383,278 out=0 elapsed=33.2s

  [692/20519] intraday_0690.csv.gz  in=153,542,476 out=0 elapsed=33.2s

  [693/20519] intraday_0693.csv.gz  in=153,725,767 out=0 elapsed=33.2s

  [694/20519] intraday_0694.csv.gz  in=153,864,268 out=0 elapsed=33.3s

  [695/20519] intraday_0695.csv.gz  in=153,997,703 out=0 elapsed=33.3s

  [696/20519] intraday_0696.csv.gz  in=154,134,404 out=0 elapsed=33.3s

  [697/20519] intraday_0697.csv.gz  in=154,268,443 out=0 elapsed=33.3s

  [698/20519] intraday_0698.csv.gz  in=154,406,877 out=0 elapsed=33.4s

  [699/20519] intraday_0699.csv.gz  in=154,540,161 out=0 elapsed=33.4s

  [700/20519] intraday_0700.csv.gz  in=154,667,673 out=0 elapsed=33.4s

  [701/20519] intraday_0701.csv.gz  in=154,856,762 out=0 elapsed=33.5s

  [702/20519] intraday_0702.csv.gz  in=154,996,117 out=0 elapsed=33.5s

  [703/20519] intraday_0703.csv.gz  in=155,122,287 out=0 elapsed=33.6s

  [704/20519] intraday_0704.csv.gz  in=155,240,129 out=0 elapsed=33.6s

  [705/20519] intraday_0708.csv.gz  in=155,360,634 out=0 elapsed=33.7s

  [706/20519] intraday_0705.csv.gz  in=155,522,748 out=0 elapsed=33.7s

  [707/20519] intraday_0707.csv.gz  in=155,681,342 out=0 elapsed=33.7s

  [708/20519] intraday_0706.csv.gz  in=155,861,235 out=0 elapsed=33.7s

  [709/20519] intraday_0709.csv.gz  in=155,997,571 out=0 elapsed=33.8s

  [710/20519] intraday_0710.csv.gz  in=156,136,449 out=0 elapsed=33.8s

  [711/20519] intraday_0712.csv.gz  in=156,273,222 out=0 elapsed=33.9s

  [712/20519] intraday_0713.csv.gz  in=156,396,389 out=0 elapsed=33.9s

  [713/20519] intraday_0711.csv.gz  in=156,619,873 out=0 elapsed=33.9s

  [714/20519] intraday_0715.csv.gz  in=156,754,514 out=0 elapsed=34.0s

  [715/20519] intraday_0714.csv.gz  in=156,903,093 out=0 elapsed=34.0s

  [716/20519] intraday_0716.csv.gz  in=157,041,253 out=0 elapsed=34.0s

  [717/20519] intraday_0717.csv.gz  in=157,196,573 out=0 elapsed=34.0s

  [718/20519] intraday_0718.csv.gz  in=157,344,926 out=0 elapsed=34.1s

  [719/20519] intraday_0719.csv.gz  in=157,478,345 out=0 elapsed=34.1s

  [720/20519] intraday_0722.csv.gz  in=157,600,387 out=0 elapsed=34.2s

  [721/20519] intraday_0721.csv.gz  in=157,724,517 out=0 elapsed=34.2s

  [722/20519] intraday_0720.csv.gz  in=157,888,287 out=0 elapsed=34.2s

  [723/20519] intraday_0723.csv.gz  in=158,046,991 out=0 elapsed=34.2s

  [724/20519] intraday_0724.csv.gz  in=158,185,787 out=0 elapsed=34.3s

  [725/20519] intraday_0726.csv.gz  in=158,327,091 out=0 elapsed=34.4s

  [726/20519] intraday_0725.csv.gz  in=158,468,376 out=0 elapsed=34.4s

  [727/20519] intraday_0727.csv.gz  in=158,616,553 out=0 elapsed=34.4s

  [728/20519] intraday_0730.csv.gz  in=158,652,357 out=0 elapsed=34.4s

  [729/20519] intraday_0728.csv.gz  in=158,785,668 out=0 elapsed=34.5s

  [730/20519] intraday_0729.csv.gz  in=158,897,969 out=0 elapsed=34.5s

  [731/20519] intraday_0731.csv.gz  in=159,046,471 out=0 elapsed=34.5s

  [732/20519] intraday_0732.csv.gz  in=159,182,736 out=0 elapsed=34.6s

  [733/20519] intraday_0733.csv.gz  in=159,312,419 out=0 elapsed=34.6s

  [734/20519] intraday_0734.csv.gz  in=159,445,206 out=0 elapsed=34.6s

  [735/20519] intraday_0736.csv.gz  in=159,565,824 out=0 elapsed=34.7s

  [736/20519] intraday_0735.csv.gz  in=159,729,226 out=0 elapsed=34.7s

  [737/20519] intraday_0737.csv.gz  in=159,875,249 out=0 elapsed=34.7s

  [738/20519] intraday_0738.csv.gz  in=159,994,738 out=0 elapsed=34.7s

  [739/20519] intraday_0739.csv.gz  in=160,108,715 out=0 elapsed=34.8s

  [740/20519] intraday_0740.csv.gz  in=160,251,867 out=0 elapsed=34.8s

  [741/20519] intraday_0741.csv.gz  in=160,398,732 out=0 elapsed=34.8s

  [742/20519] intraday_0742.csv.gz  in=160,541,414 out=0 elapsed=34.8s

  [743/20519] intraday_0743.csv.gz  in=160,694,567 out=0 elapsed=34.9s

  [744/20519] intraday_0744.csv.gz  in=160,847,878 out=0 elapsed=35.0s

  [745/20519] intraday_0745.csv.gz  in=161,001,002 out=0 elapsed=35.0s

  [746/20519] intraday_0746.csv.gz  in=161,134,735 out=0 elapsed=35.0s

  [747/20519] intraday_0747.csv.gz  in=161,275,438 out=0 elapsed=35.0s

  [748/20519] intraday_0749.csv.gz  in=161,392,280 out=0 elapsed=35.1s

  [749/20519] intraday_0748.csv.gz  in=161,530,783 out=0 elapsed=35.1s

  [750/20519] intraday_0750.csv.gz  in=161,658,304 out=0 elapsed=35.1s

  [751/20519] intraday_0751.csv.gz  in=161,769,784 out=0 elapsed=35.1s

  [752/20519] intraday_0752.csv.gz  in=161,904,477 out=0 elapsed=35.2s

  [753/20519] intraday_0753.csv.gz  in=162,036,013 out=0 elapsed=35.2s

  [754/20519] intraday_0755.csv.gz  in=162,159,711 out=0 elapsed=35.3s

  [755/20519] intraday_0754.csv.gz  in=162,296,789 out=0 elapsed=35.3s

  [756/20519] intraday_0756.csv.gz  in=162,402,013 out=0 elapsed=35.3s

  [757/20519] intraday_0757.csv.gz  in=162,533,048 out=0 elapsed=35.3s

  [758/20519] intraday_0758.csv.gz  in=162,707,166 out=0 elapsed=35.4s

  [759/20519] intraday_0759.csv.gz  in=162,866,044 out=0 elapsed=35.4s

  [760/20519] intraday_0760.csv.gz  in=162,999,521 out=0 elapsed=35.4s

  [761/20519] intraday_0761.csv.gz  in=163,114,446 out=0 elapsed=35.4s

  [762/20519] intraday_0762.csv.gz  in=163,249,987 out=0 elapsed=35.5s

  [763/20519] intraday_0763.csv.gz  in=163,397,708 out=0 elapsed=35.5s

  [764/20519] intraday_0765.csv.gz  in=163,533,935 out=0 elapsed=35.5s

  [765/20519] intraday_0764.csv.gz  in=163,688,782 out=0 elapsed=35.5s

  [766/20519] intraday_0766.csv.gz  in=163,846,217 out=0 elapsed=35.6s

  [767/20519] intraday_0767.csv.gz  in=163,993,651 out=0 elapsed=35.6s

  [768/20519] intraday_0768.csv.gz  in=164,150,804 out=0 elapsed=35.6s

  [769/20519] intraday_0769.csv.gz  in=164,303,234 out=0 elapsed=35.7s

  [770/20519] intraday_0770.csv.gz  in=164,436,536 out=0 elapsed=35.7s

  [771/20519] intraday_0771.csv.gz  in=164,570,092 out=0 elapsed=35.8s

  [772/20519] intraday_0773.csv.gz  in=164,700,589 out=0 elapsed=35.8s

  [773/20519] intraday_0772.csv.gz  in=164,847,419 out=0 elapsed=35.8s

  [774/20519] intraday_0774.csv.gz  in=164,988,419 out=0 elapsed=35.8s

  [775/20519] intraday_0775.csv.gz  in=165,118,612 out=0 elapsed=35.9s

  [776/20519] intraday_0777.csv.gz  in=165,255,747 out=0 elapsed=35.9s

  [777/20519] intraday_0776.csv.gz  in=165,422,237 out=0 elapsed=35.9s

  [778/20519] intraday_0778.csv.gz  in=165,571,124 out=0 elapsed=36.0s

  [779/20519] intraday_0780.csv.gz  in=165,702,180 out=0 elapsed=36.0s

  [780/20519] intraday_0779.csv.gz  in=165,861,510 out=0 elapsed=36.0s

  [781/20519] intraday_0781.csv.gz  in=165,998,218 out=0 elapsed=36.1s

  [782/20519] intraday_0782.csv.gz  in=166,166,029 out=0 elapsed=36.1s

  [783/20519] intraday_0783.csv.gz  in=166,322,779 out=0 elapsed=36.2s

  [784/20519] intraday_0784.csv.gz  in=166,461,856 out=0 elapsed=36.2s

  [785/20519] intraday_0785.csv.gz  in=166,594,735 out=0 elapsed=36.2s

  [786/20519] intraday_0789.csv.gz  in=166,659,088 out=0 elapsed=36.2s

  [787/20519] intraday_0786.csv.gz  in=166,797,967 out=0 elapsed=36.3s

  [788/20519] intraday_0787.csv.gz  in=166,929,889 out=0 elapsed=36.3s

  [789/20519] intraday_0788.csv.gz  in=167,078,657 out=0 elapsed=36.3s

  [790/20519] intraday_0790.csv.gz  in=167,244,773 out=0 elapsed=36.4s

  [791/20519] intraday_0793.csv.gz  in=167,384,105 out=0 elapsed=36.4s

  [792/20519] intraday_0792.csv.gz  in=167,549,744 out=0 elapsed=36.4s

  [793/20519] intraday_0791.csv.gz  in=167,710,769 out=0 elapsed=36.4s

  [794/20519] intraday_0794.csv.gz  in=167,861,533 out=0 elapsed=36.5s

  [795/20519] intraday_0796.csv.gz  in=167,986,152 out=0 elapsed=36.6s

  [796/20519] intraday_0795.csv.gz  in=168,118,552 out=0 elapsed=36.6s

  [797/20519] intraday_0797.csv.gz  in=168,273,090 out=0 elapsed=36.6s

  [798/20519] intraday_0798.csv.gz  in=168,419,998 out=0 elapsed=36.7s

  [799/20519] intraday_0800.csv.gz  in=168,564,380 out=0 elapsed=36.7s

  [800/20519] intraday_0799.csv.gz  in=168,732,695 out=0 elapsed=36.7s

  [801/20519] intraday_0801.csv.gz  in=168,875,476 out=0 elapsed=36.8s

  [802/20519] intraday_0802.csv.gz  in=169,018,762 out=0 elapsed=36.8s

  [803/20519] intraday_0804.csv.gz  in=169,159,481 out=0 elapsed=36.8s

  [804/20519] intraday_0803.csv.gz  in=169,326,594 out=0 elapsed=36.8s

  [805/20519] intraday_0805.csv.gz  in=169,500,098 out=0 elapsed=36.9s

  [806/20519] intraday_0806.csv.gz  in=169,648,754 out=0 elapsed=36.9s

  [807/20519] intraday_0807.csv.gz  in=169,786,706 out=0 elapsed=36.9s

  [808/20519] intraday_0808.csv.gz  in=169,941,973 out=0 elapsed=37.0s

  [809/20519] intraday_0809.csv.gz  in=170,069,026 out=0 elapsed=37.0s

  [810/20519] intraday_0810.csv.gz  in=170,199,485 out=0 elapsed=37.0s

  [811/20519] intraday_0811.csv.gz  in=170,333,352 out=0 elapsed=37.1s

  [812/20519] intraday_0813.csv.gz  in=170,436,393 out=0 elapsed=37.1s

  [813/20519] intraday_0812.csv.gz  in=170,569,218 out=0 elapsed=37.1s

  [814/20519] intraday_0817.csv.gz  in=170,583,417 out=0 elapsed=37.1s

  [815/20519] intraday_0814.csv.gz  in=170,680,726 out=0 elapsed=37.1s

  [816/20519] intraday_0816.csv.gz  in=170,719,341 out=0 elapsed=37.1s

  [817/20519] intraday_0818.csv.gz  in=170,733,336 out=0 elapsed=37.1s

  [818/20519] intraday_0819.csv.gz  in=170,745,538 out=0 elapsed=37.1s

  [819/20519] intraday_0820.csv.gz  in=170,761,937 out=0 elapsed=37.1s

  [820/20519] intraday_0821.csv.gz  in=170,776,861 out=0 elapsed=37.2s

  [821/20519] intraday_0822.csv.gz  in=170,790,908 out=0 elapsed=37.2s

  [822/20519] intraday_0823.csv.gz  in=170,801,724 out=0 elapsed=37.2s

  [823/20519] intraday_0815.csv.gz  in=170,912,904 out=0 elapsed=37.2s

  [824/20519] intraday_0825.csv.gz  in=170,930,229 out=0 elapsed=37.2s

  [825/20519] intraday_0827.csv.gz  in=170,939,850 out=0 elapsed=37.2s

  [826/20519] intraday_0826.csv.gz  in=170,953,237 out=0 elapsed=37.2s

  [827/20519] intraday_0824.csv.gz  in=170,974,625 out=0 elapsed=37.2s

  [828/20519] intraday_0829.csv.gz  in=170,987,981 out=0 elapsed=37.3s

  [829/20519] intraday_0828.csv.gz  in=171,014,970 out=0 elapsed=37.3s

  [830/20519] intraday_0830.csv.gz  in=171,025,124 out=0 elapsed=37.3s

  [831/20519] intraday_0831.csv.gz  in=171,034,647 out=0 elapsed=37.3s

  [832/20519] intraday_0832.csv.gz  in=171,048,427 out=0 elapsed=37.3s

  [833/20519] intraday_0833.csv.gz  in=171,060,905 out=0 elapsed=37.3s

  [834/20519] intraday_0835.csv.gz  in=171,072,226 out=0 elapsed=37.3s

  [835/20519] intraday_0834.csv.gz  in=171,085,053 out=0 elapsed=37.3s

  [836/20519] intraday_0836.csv.gz  in=171,100,482 out=0 elapsed=37.3s

  [837/20519] intraday_0837.csv.gz  in=171,113,243 out=0 elapsed=37.3s

  [838/20519] intraday_0839.csv.gz  in=171,125,104 out=0 elapsed=37.3s

  [839/20519] intraday_0838.csv.gz  in=171,138,213 out=0 elapsed=37.3s

  [840/20519] intraday_0840.csv.gz  in=171,150,913 out=0 elapsed=37.3s

  [841/20519] intraday_0842.csv.gz  in=171,161,481 out=0 elapsed=37.4s

  [842/20519] intraday_0841.csv.gz  in=171,181,810 out=0 elapsed=37.4s

  [843/20519] intraday_0843.csv.gz  in=171,194,078 out=0 elapsed=37.4s

  [844/20519] intraday_0844.csv.gz  in=171,207,678 out=0 elapsed=37.4s

  [845/20519] intraday_0845.csv.gz  in=171,222,799 out=0 elapsed=37.4s

  [846/20519] intraday_0847.csv.gz  in=171,235,133 out=0 elapsed=37.4s

  [847/20519] intraday_0848.csv.gz  in=171,248,277 out=0 elapsed=37.4s

  [848/20519] intraday_0846.csv.gz  in=171,262,538 out=0 elapsed=37.4s

  [849/20519] intraday_0851.csv.gz  in=171,274,106 out=0 elapsed=37.4s

  [850/20519] intraday_0852.csv.gz  in=171,296,850 out=0 elapsed=37.5s

  [851/20519] intraday_0849.csv.gz  in=171,309,346 out=0 elapsed=37.5s

  [852/20519] intraday_0850.csv.gz  in=171,321,977 out=0 elapsed=37.5s

  [853/20519] intraday_0854.csv.gz  in=171,333,049 out=0 elapsed=37.5s

  [854/20519] intraday_0853.csv.gz  in=171,344,863 out=0 elapsed=37.5s

  [855/20519] intraday_0856.csv.gz  in=171,357,530 out=0 elapsed=37.5s

  [856/20519] intraday_0855.csv.gz  in=171,379,672 out=0 elapsed=37.5s

  [857/20519] intraday_0858.csv.gz  in=171,392,152 out=0 elapsed=37.5s

  [858/20519] intraday_0857.csv.gz  in=171,405,058 out=0 elapsed=37.5s

  [859/20519] intraday_0860.csv.gz  in=171,417,169 out=0 elapsed=37.5s

  [860/20519] intraday_0859.csv.gz  in=171,431,803 out=0 elapsed=37.5s

  [861/20519] intraday_0862.csv.gz  in=171,443,869 out=0 elapsed=37.6s

  [862/20519] intraday_0863.csv.gz  in=171,456,272 out=0 elapsed=37.6s

  [863/20519] intraday_0861.csv.gz  in=171,468,222 out=0 elapsed=37.6s

  [864/20519] intraday_0864.csv.gz  in=171,482,017 out=0 elapsed=37.6s

  [865/20519] intraday_0868.csv.gz  in=171,491,699 out=0 elapsed=37.6s

  [866/20519] intraday_0866.csv.gz  in=171,503,374 out=0 elapsed=37.6s

  [867/20519] intraday_0865.csv.gz  in=171,520,177 out=0 elapsed=37.6s

  [868/20519] intraday_0867.csv.gz  in=171,535,560 out=0 elapsed=37.6s

  [869/20519] intraday_0870.csv.gz  in=171,547,321 out=0 elapsed=37.7s

  [870/20519] intraday_0869.csv.gz  in=171,560,121 out=0 elapsed=37.7s

  [871/20519] intraday_0871.csv.gz  in=171,570,872 out=0 elapsed=37.7s

  [872/20519] intraday_0872.csv.gz  in=171,582,750 out=0 elapsed=37.7s

  [873/20519] intraday_0873.csv.gz  in=171,595,221 out=0 elapsed=37.7s

  [874/20519] intraday_0874.csv.gz  in=171,608,084 out=0 elapsed=37.7s

  [875/20519] intraday_0875.csv.gz  in=171,620,028 out=0 elapsed=37.7s

  [876/20519] intraday_0876.csv.gz  in=171,630,652 out=0 elapsed=37.7s

  [877/20519] intraday_0877.csv.gz  in=171,640,867 out=0 elapsed=37.7s

  [878/20519] intraday_0878.csv.gz  in=171,651,507 out=0 elapsed=37.7s

  [879/20519] intraday_0879.csv.gz  in=171,664,546 out=0 elapsed=37.8s

  [880/20519] intraday_0880.csv.gz  in=171,677,195 out=0 elapsed=37.8s

  [881/20519] intraday_0881.csv.gz  in=171,692,003 out=0 elapsed=37.8s

  [882/20519] intraday_0882.csv.gz  in=171,705,429 out=0 elapsed=37.8s

  [883/20519] intraday_0883.csv.gz  in=171,716,945 out=0 elapsed=37.8s

  [884/20519] intraday_0884.csv.gz  in=171,727,599 out=0 elapsed=37.8s

  [885/20519] intraday_0885.csv.gz  in=171,739,848 out=0 elapsed=37.8s

  [886/20519] intraday_0886.csv.gz  in=171,751,580 out=0 elapsed=37.8s

  [887/20519] intraday_0888.csv.gz  in=171,764,334 out=0 elapsed=37.9s

  [888/20519] intraday_0887.csv.gz  in=171,777,220 out=0 elapsed=37.9s

  [889/20519] intraday_0889.csv.gz  in=171,788,961 out=0 elapsed=37.9s

  [890/20519] intraday_0890.csv.gz  in=171,800,237 out=0 elapsed=37.9s

  [891/20519] intraday_0891.csv.gz  in=171,812,341 out=0 elapsed=37.9s

  [892/20519] intraday_0894.csv.gz  in=171,822,102 out=0 elapsed=37.9s

  [893/20519] intraday_0892.csv.gz  in=171,833,566 out=0 elapsed=37.9s

  [894/20519] intraday_0893.csv.gz  in=171,844,703 out=0 elapsed=38.0s

  [895/20519] intraday_0895.csv.gz  in=171,855,495 out=0 elapsed=38.0s

  [896/20519] intraday_0896.csv.gz  in=171,866,627 out=0 elapsed=38.0s

  [897/20519] intraday_0899.csv.gz  in=171,877,805 out=0 elapsed=38.0s

  [898/20519] intraday_0897.csv.gz  in=171,893,861 out=0 elapsed=38.0s

  [899/20519] intraday_0898.csv.gz  in=171,906,820 out=0 elapsed=38.0s

  [900/20519] intraday_0900.csv.gz  in=171,918,523 out=0 elapsed=38.0s

  [901/20519] intraday_0901.csv.gz  in=171,931,030 out=0 elapsed=38.0s

  [902/20519] intraday_0902.csv.gz  in=171,943,634 out=0 elapsed=38.0s

  [903/20519] intraday_0904.csv.gz  in=171,956,075 out=0 elapsed=38.0s

  [904/20519] intraday_0903.csv.gz  in=171,970,669 out=0 elapsed=38.0s

  [905/20519] intraday_0905.csv.gz  in=171,985,253 out=0 elapsed=38.1s

  [906/20519] intraday_0907.csv.gz  in=171,997,646 out=0 elapsed=38.1s

  [907/20519] intraday_0906.csv.gz  in=172,011,979 out=0 elapsed=38.1s

  [908/20519] intraday_0908.csv.gz  in=172,025,210 out=0 elapsed=38.1s

  [909/20519] intraday_0909.csv.gz  in=172,037,663 out=0 elapsed=38.1s

  [910/20519] intraday_0911.csv.gz  in=172,049,827 out=0 elapsed=38.1s

  [911/20519] intraday_0910.csv.gz  in=172,062,369 out=0 elapsed=38.1s

  [912/20519] intraday_0913.csv.gz  in=172,075,517 out=0 elapsed=38.1s

  [913/20519] intraday_0912.csv.gz  in=172,087,236 out=0 elapsed=38.1s

  [914/20519] intraday_0914.csv.gz  in=172,098,538 out=0 elapsed=38.1s

  [915/20519] intraday_0916.csv.gz  in=172,109,680 out=0 elapsed=38.2s

  [916/20519] intraday_0915.csv.gz  in=172,121,855 out=0 elapsed=38.2s

  [917/20519] intraday_0917.csv.gz  in=172,134,361 out=0 elapsed=38.2s

  [918/20519] intraday_0918.csv.gz  in=172,146,865 out=0 elapsed=38.2s

  [919/20519] intraday_0920.csv.gz  in=172,159,869 out=0 elapsed=38.2s

  [920/20519] intraday_0919.csv.gz  in=172,171,440 out=0 elapsed=38.2s

  [921/20519] intraday_0922.csv.gz  in=172,184,391 out=0 elapsed=38.2s

  [922/20519] intraday_0921.csv.gz  in=172,198,803 out=0 elapsed=38.2s

  [923/20519] intraday_0923.csv.gz  in=172,209,928 out=0 elapsed=38.2s

  [924/20519] intraday_0924.csv.gz  in=172,222,572 out=0 elapsed=38.2s

  [925/20519] intraday_0925.csv.gz  in=172,236,557 out=0 elapsed=38.3s

  [926/20519] intraday_0926.csv.gz  in=172,248,876 out=0 elapsed=38.3s

  [927/20519] intraday_0927.csv.gz  in=172,260,868 out=0 elapsed=38.3s

  [928/20519] intraday_0928.csv.gz  in=172,274,527 out=0 elapsed=38.3s

  [929/20519] intraday_0929.csv.gz  in=172,288,263 out=0 elapsed=38.3s

  [930/20519] intraday_0930.csv.gz  in=172,300,820 out=0 elapsed=38.3s

  [931/20519] intraday_0931.csv.gz  in=172,314,019 out=0 elapsed=38.3s

  [932/20519] intraday_0933.csv.gz  in=172,324,770 out=0 elapsed=38.3s

  [933/20519] intraday_0932.csv.gz  in=172,337,937 out=0 elapsed=38.3s

  [934/20519] intraday_0934.csv.gz  in=172,348,617 out=0 elapsed=38.3s

  [935/20519] intraday_0935.csv.gz  in=172,363,031 out=0 elapsed=38.3s

  [936/20519] intraday_0938.csv.gz  in=172,375,084 out=0 elapsed=38.4s

  [937/20519] intraday_0937.csv.gz  in=172,390,534 out=0 elapsed=38.4s

  [938/20519] intraday_0936.csv.gz  in=172,403,487 out=0 elapsed=38.4s

  [939/20519] intraday_0939.csv.gz  in=172,417,191 out=0 elapsed=38.4s

  [940/20519] intraday_0940.csv.gz  in=172,428,760 out=0 elapsed=38.4s

  [941/20519] intraday_0942.csv.gz  in=172,443,152 out=0 elapsed=38.4s

  [942/20519] intraday_0941.csv.gz  in=172,456,071 out=0 elapsed=38.4s

  [943/20519] intraday_0944.csv.gz  in=172,470,100 out=0 elapsed=38.4s

  [944/20519] intraday_0945.csv.gz  in=172,482,097 out=0 elapsed=38.4s

  [945/20519] intraday_0943.csv.gz  in=172,503,363 out=0 elapsed=38.4s

  [946/20519] intraday_0947.csv.gz  in=172,513,830 out=0 elapsed=38.4s

  [947/20519] intraday_0946.csv.gz  in=172,527,681 out=0 elapsed=38.4s

  [948/20519] intraday_0950.csv.gz  in=172,539,547 out=0 elapsed=38.5s

  [949/20519] intraday_0948.csv.gz  in=172,551,496 out=0 elapsed=38.5s

  [950/20519] intraday_0949.csv.gz  in=172,563,487 out=0 elapsed=38.5s

  [951/20519] intraday_0951.csv.gz  in=172,571,876 out=0 elapsed=38.5s

  [952/20519] intraday_0953.csv.gz  in=172,583,445 out=0 elapsed=38.5s

  [953/20519] intraday_0954.csv.gz  in=172,585,685 out=0 elapsed=38.5s

  [954/20519] intraday_0952.csv.gz  in=172,594,176 out=0 elapsed=38.5s

  [955/20519] intraday_0955.csv.gz  in=172,609,257 out=0 elapsed=38.5s

  [956/20519] intraday_0957.csv.gz  in=172,620,944 out=0 elapsed=38.5s

  [957/20519] intraday_0959.csv.gz  in=172,635,675 out=0 elapsed=38.5s

  [958/20519] intraday_0956.csv.gz  in=172,649,942 out=0 elapsed=38.5s

  [959/20519] intraday_0958.csv.gz  in=172,672,377 out=0 elapsed=38.6s

  [960/20519] intraday_0960.csv.gz  in=172,686,888 out=0 elapsed=38.6s

  [961/20519] intraday_0961.csv.gz  in=172,703,954 out=0 elapsed=38.6s

  [962/20519] intraday_0962.csv.gz  in=172,716,282 out=0 elapsed=38.6s

  [963/20519] intraday_0963.csv.gz  in=172,729,667 out=0 elapsed=38.6s

  [964/20519] intraday_0966.csv.gz  in=172,751,777 out=0 elapsed=38.6s

  [965/20519] intraday_0964.csv.gz  in=172,766,649 out=0 elapsed=38.6s

  [966/20519] intraday_0967.csv.gz  in=172,780,627 out=0 elapsed=38.6s

  [967/20519] intraday_0965.csv.gz  in=172,794,415 out=0 elapsed=38.6s

  [968/20519] intraday_0968.csv.gz  in=172,806,586 out=0 elapsed=38.7s

  [969/20519] intraday_0969.csv.gz  in=172,816,729 out=0 elapsed=38.7s

  [970/20519] intraday_0971.csv.gz  in=172,828,749 out=0 elapsed=38.7s

  [971/20519] intraday_0970.csv.gz  in=172,842,612 out=0 elapsed=38.7s

  [972/20519] intraday_0972.csv.gz  in=172,856,089 out=0 elapsed=38.7s

  [973/20519] intraday_0973.csv.gz  in=172,876,609 out=0 elapsed=38.7s

  [974/20519] intraday_0974.csv.gz  in=172,888,244 out=0 elapsed=38.7s

  [975/20519] intraday_0976.csv.gz  in=172,900,541 out=0 elapsed=38.7s

  [976/20519] intraday_0975.csv.gz  in=172,926,040 out=0 elapsed=38.7s

  [977/20519] intraday_0978.csv.gz  in=172,939,218 out=0 elapsed=38.7s

  [978/20519] intraday_0977.csv.gz  in=172,951,142 out=0 elapsed=38.8s

  [979/20519] intraday_0980.csv.gz  in=172,961,989 out=0 elapsed=38.8s

  [980/20519] intraday_0981.csv.gz  in=172,975,120 out=0 elapsed=38.8s

  [981/20519] intraday_0983.csv.gz  in=172,990,895 out=0 elapsed=38.8s

  [982/20519] intraday_0982.csv.gz  in=173,004,062 out=0 elapsed=38.8s

  [983/20519] intraday_0979.csv.gz  in=173,052,965 out=0 elapsed=38.8s

  [984/20519] intraday_0985.csv.gz  in=173,065,457 out=0 elapsed=38.8s

  [985/20519] intraday_0986.csv.gz  in=173,077,697 out=0 elapsed=38.8s

  [986/20519] intraday_0984.csv.gz  in=173,092,348 out=0 elapsed=38.8s

  [987/20519] intraday_0988.csv.gz  in=173,105,709 out=0 elapsed=38.9s

  [988/20519] intraday_0990.csv.gz  in=173,117,326 out=0 elapsed=38.9s

  [989/20519] intraday_0989.csv.gz  in=173,129,002 out=0 elapsed=38.9s

  [990/20519] intraday_0987.csv.gz  in=173,161,035 out=0 elapsed=38.9s

  [991/20519] intraday_0992.csv.gz  in=173,171,820 out=0 elapsed=38.9s

  [992/20519] intraday_0993.csv.gz  in=173,183,210 out=0 elapsed=38.9s

  [993/20519] intraday_0994.csv.gz  in=173,196,961 out=0 elapsed=38.9s

  [994/20519] intraday_0996.csv.gz  in=173,210,689 out=0 elapsed=39.0s

  [995/20519] intraday_0991.csv.gz  in=173,223,798 out=0 elapsed=39.0s

  [996/20519] intraday_0995.csv.gz  in=173,235,726 out=0 elapsed=39.0s

  [997/20519] intraday_0998.csv.gz  in=173,246,623 out=0 elapsed=39.0s

  [998/20519] intraday_0997.csv.gz  in=173,262,519 out=0 elapsed=39.0s

  [999/20519] intraday_1000.csv.gz  in=173,274,824 out=0 elapsed=39.0s

  [1000/20519] intraday_0999.csv.gz  in=173,287,073 out=0 elapsed=39.0s

  [1001/20519] intraday_10000.csv.gz  in=173,298,407 out=0 elapsed=39.0s

  [1002/20519] intraday_10001.csv.gz  in=173,312,102 out=0 elapsed=39.0s

  [1003/20519] intraday_10002.csv.gz  in=173,324,401 out=0 elapsed=39.0s

  [1004/20519] intraday_10003.csv.gz  in=173,337,308 out=0 elapsed=39.0s

  [1005/20519] intraday_10004.csv.gz  in=173,354,361 out=0 elapsed=39.0s

  [1006/20519] intraday_10005.csv.gz  in=173,368,716 out=0 elapsed=39.0s

  [1007/20519] intraday_10006.csv.gz  in=173,387,818 out=0 elapsed=39.1s

  [1008/20519] intraday_10008.csv.gz  in=173,401,473 out=0 elapsed=39.1s

  [1009/20519] intraday_10007.csv.gz  in=173,416,844 out=0 elapsed=39.1s

  [1010/20519] intraday_10009.csv.gz  in=173,429,708 out=0 elapsed=39.1s

  [1011/20519] intraday_1001.csv.gz  in=173,445,201 out=0 elapsed=39.1s

  [1012/20519] intraday_10010.csv.gz  in=173,457,751 out=0 elapsed=39.1s

  [1013/20519] intraday_10011.csv.gz  in=173,468,274 out=0 elapsed=39.1s

  [1014/20519] intraday_10012.csv.gz  in=173,481,818 out=0 elapsed=39.1s

  [1015/20519] intraday_10013.csv.gz  in=173,492,257 out=0 elapsed=39.1s

  [1016/20519] intraday_10014.csv.gz  in=173,506,755 out=0 elapsed=39.1s

  [1017/20519] intraday_10017.csv.gz  in=173,517,983 out=0 elapsed=39.2s

  [1018/20519] intraday_10018.csv.gz  in=173,528,865 out=0 elapsed=39.2s

  [1019/20519] intraday_10015.csv.gz  in=173,542,743 out=0 elapsed=39.2s

  [1020/20519] intraday_10016.csv.gz  in=173,559,020 out=0 elapsed=39.2s

  [1021/20519] intraday_10019.csv.gz  in=173,572,270 out=0 elapsed=39.2s

  [1022/20519] intraday_10020.csv.gz  in=173,584,433 out=0 elapsed=39.2s

  [1023/20519] intraday_10021.csv.gz  in=173,594,825 out=0 elapsed=39.2s

  [1024/20519] intraday_1002.csv.gz  in=173,606,839 out=0 elapsed=39.2s

  [1025/20519] intraday_10023.csv.gz  in=173,621,192 out=0 elapsed=39.3s

  [1026/20519] intraday_10022.csv.gz  in=173,636,830 out=0 elapsed=39.3s

  [1027/20519] intraday_10024.csv.gz  in=173,650,340 out=0 elapsed=39.3s

  [1028/20519] intraday_10025.csv.gz  in=173,666,792 out=0 elapsed=39.3s

  [1029/20519] intraday_10026.csv.gz  in=173,678,186 out=0 elapsed=39.3s

  [1030/20519] intraday_10027.csv.gz  in=173,689,424 out=0 elapsed=39.3s

  [1031/20519] intraday_10028.csv.gz  in=173,702,370 out=0 elapsed=39.3s

  [1032/20519] intraday_10029.csv.gz  in=173,713,343 out=0 elapsed=39.3s

  [1033/20519] intraday_1003.csv.gz  in=173,724,417 out=0 elapsed=39.3s

  [1034/20519] intraday_10030.csv.gz  in=173,737,452 out=0 elapsed=39.3s

  [1035/20519] intraday_10032.csv.gz  in=173,748,633 out=0 elapsed=39.3s

  [1036/20519] intraday_10031.csv.gz  in=173,756,598 out=0 elapsed=39.3s

  [1037/20519] intraday_10034.csv.gz  in=173,771,382 out=0 elapsed=39.4s

  [1038/20519] intraday_10033.csv.gz  in=173,779,993 out=0 elapsed=39.4s

  [1039/20519] intraday_10035.csv.gz  in=173,791,702 out=0 elapsed=39.4s

  [1040/20519] intraday_10036.csv.gz  in=173,803,469 out=0 elapsed=39.4s

  [1041/20519] intraday_10037.csv.gz  in=173,813,914 out=0 elapsed=39.4s

  [1042/20519] intraday_1004.csv.gz  in=173,828,092 out=0 elapsed=39.4s

  [1043/20519] intraday_10038.csv.gz  in=173,840,091 out=0 elapsed=39.4s

  [1044/20519] intraday_10039.csv.gz  in=173,855,224 out=0 elapsed=39.4s

  [1045/20519] intraday_10040.csv.gz  in=173,870,194 out=0 elapsed=39.4s

  [1046/20519] intraday_10041.csv.gz  in=173,880,973 out=0 elapsed=39.5s

  [1047/20519] intraday_10042.csv.gz  in=173,895,383 out=0 elapsed=39.5s

  [1048/20519] intraday_10043.csv.gz  in=173,909,948 out=0 elapsed=39.5s

  [1049/20519] intraday_10045.csv.gz  in=173,921,938 out=0 elapsed=39.5s

  [1050/20519] intraday_10047.csv.gz  in=173,935,225 out=0 elapsed=39.5s

  [1051/20519] intraday_10044.csv.gz  in=173,948,255 out=0 elapsed=39.5s

  [1052/20519] intraday_10046.csv.gz  in=173,961,864 out=0 elapsed=39.5s

  [1053/20519] intraday_1005.csv.gz  in=173,973,995 out=0 elapsed=39.5s

  [1054/20519] intraday_10050.csv.gz  in=173,985,000 out=0 elapsed=39.5s

  [1055/20519] intraday_10048.csv.gz  in=173,995,425 out=0 elapsed=39.5s

  [1056/20519] intraday_10049.csv.gz  in=174,007,014 out=0 elapsed=39.6s

  [1057/20519] intraday_10051.csv.gz  in=174,022,551 out=0 elapsed=39.6s

  [1058/20519] intraday_10052.csv.gz  in=174,033,434 out=0 elapsed=39.6s

  [1059/20519] intraday_10053.csv.gz  in=174,044,240 out=0 elapsed=39.6s

  [1060/20519] intraday_10054.csv.gz  in=174,056,999 out=0 elapsed=39.6s

  [1061/20519] intraday_10055.csv.gz  in=174,070,268 out=0 elapsed=39.6s

  [1062/20519] intraday_10056.csv.gz  in=174,084,047 out=0 elapsed=39.6s

  [1063/20519] intraday_10057.csv.gz  in=174,096,010 out=0 elapsed=39.6s

  [1064/20519] intraday_10058.csv.gz  in=174,110,134 out=0 elapsed=39.6s

  [1065/20519] intraday_1006.csv.gz  in=174,121,727 out=0 elapsed=39.6s

  [1066/20519] intraday_10059.csv.gz  in=174,135,744 out=0 elapsed=39.6s

  [1067/20519] intraday_10060.csv.gz  in=174,147,864 out=0 elapsed=39.7s

  [1068/20519] intraday_10061.csv.gz  in=174,159,004 out=0 elapsed=39.7s

  [1069/20519] intraday_10062.csv.gz  in=174,169,216 out=0 elapsed=39.7s

  [1070/20519] intraday_10063.csv.gz  in=174,182,840 out=0 elapsed=39.7s

  [1071/20519] intraday_10064.csv.gz  in=174,196,788 out=0 elapsed=39.7s

  [1072/20519] intraday_10066.csv.gz  in=174,214,169 out=0 elapsed=39.7s

  [1073/20519] intraday_10065.csv.gz  in=174,228,926 out=0 elapsed=39.7s

  [1074/20519] intraday_10067.csv.gz  in=174,240,135 out=0 elapsed=39.7s

  [1075/20519] intraday_10068.csv.gz  in=174,251,887 out=0 elapsed=39.7s

  [1076/20519] intraday_10069.csv.gz  in=174,265,819 out=0 elapsed=39.7s

  [1077/20519] intraday_1007.csv.gz  in=174,277,560 out=0 elapsed=39.8s

  [1078/20519] intraday_10070.csv.gz  in=174,288,874 out=0 elapsed=39.8s

  [1079/20519] intraday_10071.csv.gz  in=174,302,221 out=0 elapsed=39.8s

  [1080/20519] intraday_10073.csv.gz  in=174,314,544 out=0 elapsed=39.8s

  [1081/20519] intraday_10072.csv.gz  in=174,325,425 out=0 elapsed=39.8s

  [1082/20519] intraday_10075.csv.gz  in=174,337,374 out=0 elapsed=39.8s

  [1083/20519] intraday_10074.csv.gz  in=174,349,131 out=0 elapsed=39.8s

  [1084/20519] intraday_10076.csv.gz  in=174,361,949 out=0 elapsed=39.9s

  [1085/20519] intraday_10077.csv.gz  in=174,374,462 out=0 elapsed=39.9s

  [1086/20519] intraday_10078.csv.gz  in=174,386,686 out=0 elapsed=39.9s

  [1087/20519] intraday_10079.csv.gz  in=174,400,188 out=0 elapsed=39.9s

  [1088/20519] intraday_1008.csv.gz  in=174,412,772 out=0 elapsed=39.9s

  [1089/20519] intraday_10080.csv.gz  in=174,424,526 out=0 elapsed=40.0s

  [1090/20519] intraday_10081.csv.gz  in=174,435,760 out=0 elapsed=40.0s

  [1091/20519] intraday_10082.csv.gz  in=174,448,352 out=0 elapsed=40.0s

  [1092/20519] intraday_10083.csv.gz  in=174,459,564 out=0 elapsed=40.0s

  [1093/20519] intraday_10085.csv.gz  in=174,470,901 out=0 elapsed=40.0s

  [1094/20519] intraday_10084.csv.gz  in=174,482,074 out=0 elapsed=40.0s

  [1095/20519] intraday_10086.csv.gz  in=174,495,205 out=0 elapsed=40.0s

  [1096/20519] intraday_10087.csv.gz  in=174,507,203 out=0 elapsed=40.0s

  [1097/20519] intraday_10089.csv.gz  in=174,518,956 out=0 elapsed=40.0s

  [1098/20519] intraday_10088.csv.gz  in=174,535,717 out=0 elapsed=40.1s

  [1099/20519] intraday_10090.csv.gz  in=174,548,018 out=0 elapsed=40.1s

  [1100/20519] intraday_1009.csv.gz  in=174,560,505 out=0 elapsed=40.1s

  [1101/20519] intraday_10091.csv.gz  in=174,579,580 out=0 elapsed=40.1s

  [1102/20519] intraday_10092.csv.gz  in=174,591,151 out=0 elapsed=40.1s

  [1103/20519] intraday_10093.csv.gz  in=174,602,807 out=0 elapsed=40.1s

  [1104/20519] intraday_10095.csv.gz  in=174,615,071 out=0 elapsed=40.1s

  [1105/20519] intraday_10094.csv.gz  in=174,627,995 out=0 elapsed=40.1s

  [1106/20519] intraday_10096.csv.gz  in=174,639,992 out=0 elapsed=40.1s

  [1107/20519] intraday_10097.csv.gz  in=174,652,795 out=0 elapsed=40.1s

  [1108/20519] intraday_10098.csv.gz  in=174,664,516 out=0 elapsed=40.2s

  [1109/20519] intraday_1010.csv.gz  in=174,675,875 out=0 elapsed=40.2s

  [1110/20519] intraday_10099.csv.gz  in=174,686,259 out=0 elapsed=40.2s

  [1111/20519] intraday_10100.csv.gz  in=174,701,061 out=0 elapsed=40.2s

  [1112/20519] intraday_10101.csv.gz  in=174,712,971 out=0 elapsed=40.2s

  [1113/20519] intraday_10104.csv.gz  in=174,725,889 out=0 elapsed=40.2s

  [1114/20519] intraday_10102.csv.gz  in=174,740,127 out=0 elapsed=40.2s

  [1115/20519] intraday_10103.csv.gz  in=174,757,104 out=0 elapsed=40.2s

  [1116/20519] intraday_10105.csv.gz  in=174,766,605 out=0 elapsed=40.2s

  [1117/20519] intraday_10106.csv.gz  in=174,779,150 out=0 elapsed=40.2s

  [1118/20519] intraday_10107.csv.gz  in=174,791,625 out=0 elapsed=40.3s

  [1119/20519] intraday_10108.csv.gz  in=174,805,362 out=0 elapsed=40.3s

  [1120/20519] intraday_1011.csv.gz  in=174,819,377 out=0 elapsed=40.3s

  [1121/20519] intraday_10110.csv.gz  in=174,832,683 out=0 elapsed=40.3s

  [1122/20519] intraday_10109.csv.gz  in=174,846,216 out=0 elapsed=40.3s

  [1123/20519] intraday_10111.csv.gz  in=174,856,747 out=0 elapsed=40.3s

  [1124/20519] intraday_10113.csv.gz  in=174,867,890 out=0 elapsed=40.3s

  [1125/20519] intraday_10112.csv.gz  in=174,880,777 out=0 elapsed=40.3s

  [1126/20519] intraday_10114.csv.gz  in=174,892,709 out=0 elapsed=40.3s

  [1127/20519] intraday_10115.csv.gz  in=174,904,120 out=0 elapsed=40.3s

  [1128/20519] intraday_10117.csv.gz  in=174,915,157 out=0 elapsed=40.4s

  [1129/20519] intraday_10116.csv.gz  in=174,924,577 out=0 elapsed=40.4s

  [1130/20519] intraday_10118.csv.gz  in=174,937,686 out=0 elapsed=40.4s

  [1131/20519] intraday_10119.csv.gz  in=174,955,152 out=0 elapsed=40.4s

  [1132/20519] intraday_1012.csv.gz  in=174,967,732 out=0 elapsed=40.4s

  [1133/20519] intraday_10120.csv.gz  in=174,980,833 out=0 elapsed=40.4s

  [1134/20519] intraday_10121.csv.gz  in=174,993,414 out=0 elapsed=40.4s

  [1135/20519] intraday_10124.csv.gz  in=175,005,537 out=0 elapsed=40.4s

  [1136/20519] intraday_10123.csv.gz  in=175,020,464 out=0 elapsed=40.4s

  [1137/20519] intraday_10122.csv.gz  in=175,035,241 out=0 elapsed=40.4s

  [1138/20519] intraday_10125.csv.gz  in=175,050,846 out=0 elapsed=40.4s

  [1139/20519] intraday_10126.csv.gz  in=175,061,503 out=0 elapsed=40.5s

  [1140/20519] intraday_10128.csv.gz  in=175,074,870 out=0 elapsed=40.5s

  [1141/20519] intraday_10127.csv.gz  in=175,086,727 out=0 elapsed=40.5s

  [1142/20519] intraday_10129.csv.gz  in=175,100,187 out=0 elapsed=40.5s

  [1143/20519] intraday_1013.csv.gz  in=175,111,971 out=0 elapsed=40.5s

  [1144/20519] intraday_10130.csv.gz  in=175,124,483 out=0 elapsed=40.5s

  [1145/20519] intraday_10131.csv.gz  in=175,136,810 out=0 elapsed=40.5s

  [1146/20519] intraday_10132.csv.gz  in=175,149,729 out=0 elapsed=40.5s

  [1147/20519] intraday_10133.csv.gz  in=175,161,959 out=0 elapsed=40.5s

  [1148/20519] intraday_10134.csv.gz  in=175,174,754 out=0 elapsed=40.5s

  [1149/20519] intraday_10136.csv.gz  in=175,185,634 out=0 elapsed=40.6s

  [1150/20519] intraday_10135.csv.gz  in=175,198,152 out=0 elapsed=40.6s

  [1151/20519] intraday_10138.csv.gz  in=175,211,869 out=0 elapsed=40.6s

  [1152/20519] intraday_10137.csv.gz  in=175,224,341 out=0 elapsed=40.6s

  [1153/20519] intraday_1014.csv.gz  in=175,236,763 out=0 elapsed=40.6s

  [1154/20519] intraday_10139.csv.gz  in=175,250,734 out=0 elapsed=40.6s

  [1155/20519] intraday_10141.csv.gz  in=175,261,936 out=0 elapsed=40.6s

  [1156/20519] intraday_10140.csv.gz  in=175,274,722 out=0 elapsed=40.6s

  [1157/20519] intraday_10144.csv.gz  in=175,277,323 out=0 elapsed=40.6s

  [1158/20519] intraday_10143.csv.gz  in=175,290,042 out=0 elapsed=40.7s

  [1159/20519] intraday_10142.csv.gz  in=175,304,744 out=0 elapsed=40.7s

  [1160/20519] intraday_10146.csv.gz  in=175,385,002 out=0 elapsed=40.7s

  [1161/20519] intraday_10148.csv.gz  in=175,452,998 out=0 elapsed=40.8s

  [1162/20519] intraday_10147.csv.gz  in=175,543,695 out=0 elapsed=40.8s

  [1163/20519] intraday_10145.csv.gz  in=175,646,836 out=0 elapsed=40.8s

  [1164/20519] intraday_1015.csv.gz  in=175,658,448 out=0 elapsed=40.8s

  [1165/20519] intraday_10149.csv.gz  in=175,742,690 out=0 elapsed=40.9s

  [1166/20519] intraday_10150.csv.gz  in=175,837,504 out=0 elapsed=40.9s

  [1167/20519] intraday_10152.csv.gz  in=175,919,447 out=0 elapsed=40.9s

  [1168/20519] intraday_10151.csv.gz  in=176,024,115 out=0 elapsed=40.9s

  [1169/20519] intraday_10153.csv.gz  in=176,106,851 out=0 elapsed=41.0s

  [1170/20519] intraday_10154.csv.gz  in=176,202,640 out=0 elapsed=41.0s

  [1171/20519] intraday_10156.csv.gz  in=176,279,426 out=0 elapsed=41.1s

  [1172/20519] intraday_10155.csv.gz  in=176,368,566 out=0 elapsed=41.1s

  [1173/20519] intraday_1016.csv.gz  in=176,378,774 out=0 elapsed=41.1s

  [1174/20519] intraday_10157.csv.gz  in=176,486,272 out=0 elapsed=41.1s

  [1175/20519] intraday_10159.csv.gz  in=176,565,652 out=0 elapsed=41.1s

  [1176/20519] intraday_10158.csv.gz  in=176,668,116 out=0 elapsed=41.2s

  [1177/20519] intraday_10160.csv.gz  in=176,745,607 out=0 elapsed=41.2s

  [1178/20519] intraday_10161.csv.gz  in=176,836,371 out=0 elapsed=41.3s

  [1179/20519] intraday_10163.csv.gz  in=176,919,966 out=0 elapsed=41.3s

  [1180/20519] intraday_10164.csv.gz  in=176,998,901 out=0 elapsed=41.3s

  [1181/20519] intraday_10162.csv.gz  in=177,097,805 out=0 elapsed=41.3s

  [1182/20519] intraday_10165.csv.gz  in=177,173,337 out=0 elapsed=41.3s

  [1183/20519] intraday_10167.csv.gz  in=177,262,478 out=0 elapsed=41.4s

  [1184/20519] intraday_10166.csv.gz  in=177,360,707 out=0 elapsed=41.4s

  [1185/20519] intraday_10168.csv.gz  in=177,450,851 out=0 elapsed=41.4s

  [1186/20519] intraday_1017.csv.gz  in=177,465,071 out=0 elapsed=41.4s

  [1187/20519] intraday_10169.csv.gz  in=177,556,583 out=0 elapsed=41.4s

  [1188/20519] intraday_10170.csv.gz  in=177,640,495 out=0 elapsed=41.5s

  [1189/20519] intraday_10173.csv.gz  in=177,710,106 out=0 elapsed=41.5s

  [1190/20519] intraday_10172.csv.gz  in=177,796,337 out=0 elapsed=41.5s

  [1191/20519] intraday_10171.csv.gz  in=177,892,985 out=0 elapsed=41.5s

  [1192/20519] intraday_10177.csv.gz  in=177,966,341 out=0 elapsed=41.6s

  [1193/20519] intraday_10174.csv.gz  in=178,060,406 out=0 elapsed=41.6s

  [1194/20519] intraday_10175.csv.gz  in=178,175,405 out=0 elapsed=41.6s

  [1195/20519] intraday_10176.csv.gz  in=178,273,362 out=0 elapsed=41.6s

  [1196/20519] intraday_1018.csv.gz  in=178,284,746 out=0 elapsed=41.6s

  [1197/20519] intraday_10179.csv.gz  in=178,369,299 out=0 elapsed=41.7s

  [1198/20519] intraday_10178.csv.gz  in=178,443,812 out=0 elapsed=41.7s

  [1199/20519] intraday_10181.csv.gz  in=178,522,111 out=0 elapsed=41.7s

  [1200/20519] intraday_10180.csv.gz  in=178,609,433 out=0 elapsed=41.7s

  [1201/20519] intraday_10182.csv.gz  in=178,706,787 out=0 elapsed=41.8s

  [1202/20519] intraday_10184.csv.gz  in=178,780,958 out=0 elapsed=41.8s

  [1203/20519] intraday_10183.csv.gz  in=178,856,302 out=0 elapsed=41.8s

  [1204/20519] intraday_10185.csv.gz  in=178,941,200 out=0 elapsed=41.8s

  [1205/20519] intraday_10186.csv.gz  in=179,030,280 out=0 elapsed=41.9s

  [1206/20519] intraday_1019.csv.gz  in=179,044,194 out=0 elapsed=41.9s

  [1207/20519] intraday_10187.csv.gz  in=179,132,835 out=0 elapsed=41.9s

  [1208/20519] intraday_10189.csv.gz  in=179,223,820 out=0 elapsed=41.9s

  [1209/20519] intraday_10188.csv.gz  in=179,306,094 out=0 elapsed=41.9s

  [1210/20519] intraday_10192.csv.gz  in=179,387,680 out=0 elapsed=42.0s

  [1211/20519] intraday_10191.csv.gz  in=179,460,656 out=0 elapsed=42.0s

  [1212/20519] intraday_10190.csv.gz  in=179,558,761 out=0 elapsed=42.1s

  [1213/20519] intraday_10193.csv.gz  in=179,641,608 out=0 elapsed=42.1s

  [1214/20519] intraday_10196.csv.gz  in=179,717,850 out=0 elapsed=42.1s

  [1215/20519] intraday_10194.csv.gz  in=179,790,420 out=0 elapsed=42.1s

  [1216/20519] intraday_10195.csv.gz  in=179,873,334 out=0 elapsed=42.1s

  [1217/20519] intraday_10197.csv.gz  in=179,953,755 out=0 elapsed=42.2s

  [1218/20519] intraday_1020.csv.gz  in=179,967,131 out=0 elapsed=42.2s

  [1219/20519] intraday_10198.csv.gz  in=180,063,082 out=0 elapsed=42.2s

  [1220/20519] intraday_10199.csv.gz  in=180,141,936 out=0 elapsed=42.2s

  [1221/20519] intraday_10200.csv.gz  in=180,219,078 out=0 elapsed=42.2s

  [1222/20519] intraday_10201.csv.gz  in=180,320,540 out=0 elapsed=42.2s

  [1223/20519] intraday_10202.csv.gz  in=180,404,680 out=0 elapsed=42.3s

  [1224/20519] intraday_10204.csv.gz  in=180,481,986 out=0 elapsed=42.3s

  [1225/20519] intraday_10203.csv.gz  in=180,560,584 out=0 elapsed=42.3s

  [1226/20519] intraday_10205.csv.gz  in=180,648,610 out=0 elapsed=42.3s

  [1227/20519] intraday_10207.csv.gz  in=180,721,650 out=0 elapsed=42.4s

  [1228/20519] intraday_10206.csv.gz  in=180,799,011 out=0 elapsed=42.4s

  [1229/20519] intraday_10208.csv.gz  in=180,886,618 out=0 elapsed=42.4s

  [1230/20519] intraday_1021.csv.gz  in=180,899,720 out=0 elapsed=42.4s

  [1231/20519] intraday_10209.csv.gz  in=180,978,301 out=0 elapsed=42.4s

  [1232/20519] intraday_10210.csv.gz  in=181,052,594 out=0 elapsed=42.5s

  [1233/20519] intraday_10212.csv.gz  in=181,146,612 out=0 elapsed=42.5s

  [1234/20519] intraday_10211.csv.gz  in=181,261,979 out=0 elapsed=42.5s

  [1235/20519] intraday_10214.csv.gz  in=181,341,598 out=0 elapsed=42.5s

  [1236/20519] intraday_10213.csv.gz  in=181,443,640 out=0 elapsed=42.5s

  [1237/20519] intraday_10215.csv.gz  in=181,538,956 out=0 elapsed=42.6s

  [1238/20519] intraday_10216.csv.gz  in=181,611,320 out=0 elapsed=42.6s

  [1239/20519] intraday_10218.csv.gz  in=181,692,504 out=0 elapsed=42.6s

  [1240/20519] intraday_1022.csv.gz  in=181,703,234 out=0 elapsed=42.6s

  [1241/20519] intraday_10217.csv.gz  in=181,795,908 out=0 elapsed=42.6s

  [1242/20519] intraday_10219.csv.gz  in=181,886,623 out=0 elapsed=42.7s

  [1243/20519] intraday_10220.csv.gz  in=181,961,528 out=0 elapsed=42.7s

  [1244/20519] intraday_10221.csv.gz  in=182,062,513 out=0 elapsed=42.7s

  [1245/20519] intraday_10222.csv.gz  in=182,145,905 out=0 elapsed=42.7s

  [1246/20519] intraday_10223.csv.gz  in=182,240,480 out=0 elapsed=42.8s

  [1247/20519] intraday_10224.csv.gz  in=182,318,621 out=0 elapsed=42.8s

  [1248/20519] intraday_10225.csv.gz  in=182,398,973 out=0 elapsed=42.8s

  [1249/20519] intraday_10226.csv.gz  in=182,475,893 out=0 elapsed=42.8s

  [1250/20519] intraday_1023.csv.gz  in=182,489,202 out=0 elapsed=42.8s

  [1251/20519] intraday_10227.csv.gz  in=182,551,497 out=0 elapsed=42.9s

  [1252/20519] intraday_10228.csv.gz  in=182,626,752 out=0 elapsed=42.9s

  [1253/20519] intraday_10229.csv.gz  in=182,716,973 out=0 elapsed=42.9s

  [1254/20519] intraday_10230.csv.gz  in=182,830,052 out=0 elapsed=42.9s

  [1255/20519] intraday_10232.csv.gz  in=182,921,418 out=0 elapsed=43.0s

  [1256/20519] intraday_10231.csv.gz  in=183,036,725 out=0 elapsed=43.0s

  [1257/20519] intraday_10233.csv.gz  in=183,109,757 out=0 elapsed=43.0s

  [1258/20519] intraday_10234.csv.gz  in=183,208,010 out=0 elapsed=43.1s

  [1259/20519] intraday_10237.csv.gz  in=183,288,361 out=0 elapsed=43.1s

  [1260/20519] intraday_10236.csv.gz  in=183,393,885 out=0 elapsed=43.1s

  [1261/20519] intraday_10235.csv.gz  in=183,482,340 out=0 elapsed=43.1s

  [1262/20519] intraday_1024.csv.gz  in=183,494,276 out=0 elapsed=43.1s

  [1263/20519] intraday_10238.csv.gz  in=183,575,279 out=0 elapsed=43.1s

  [1264/20519] intraday_10239.csv.gz  in=183,675,534 out=0 elapsed=43.2s

  [1265/20519] intraday_10240.csv.gz  in=183,764,000 out=0 elapsed=43.2s

  [1266/20519] intraday_10241.csv.gz  in=183,855,290 out=0 elapsed=43.2s

  [1267/20519] intraday_10242.csv.gz  in=183,939,998 out=0 elapsed=43.2s

  [1268/20519] intraday_10243.csv.gz  in=184,027,574 out=0 elapsed=43.2s

  [1269/20519] intraday_10244.csv.gz  in=184,116,987 out=0 elapsed=43.3s

  [1270/20519] intraday_10245.csv.gz  in=184,207,182 out=0 elapsed=43.3s

  [1271/20519] intraday_10246.csv.gz  in=184,301,232 out=0 elapsed=43.3s

  [1272/20519] intraday_10247.csv.gz  in=184,375,035 out=0 elapsed=43.3s

  [1273/20519] intraday_1025.csv.gz  in=184,409,739 out=0 elapsed=43.3s

  [1274/20519] intraday_10248.csv.gz  in=184,497,338 out=0 elapsed=43.3s

  [1275/20519] intraday_10249.csv.gz  in=184,588,888 out=0 elapsed=43.4s

  [1276/20519] intraday_10250.csv.gz  in=184,684,658 out=0 elapsed=43.4s

  [1277/20519] intraday_10252.csv.gz  in=184,767,329 out=0 elapsed=43.4s

  [1278/20519] intraday_10251.csv.gz  in=184,853,516 out=0 elapsed=43.4s

  [1279/20519] intraday_10253.csv.gz  in=184,964,671 out=0 elapsed=43.5s

  [1280/20519] intraday_10254.csv.gz  in=185,043,773 out=0 elapsed=43.5s

  [1281/20519] intraday_10255.csv.gz  in=185,128,272 out=0 elapsed=43.5s

  [1282/20519] intraday_10256.csv.gz  in=185,224,692 out=0 elapsed=43.5s

  [1283/20519] intraday_1026.csv.gz  in=185,236,273 out=0 elapsed=43.6s

  [1284/20519] intraday_10257.csv.gz  in=185,335,351 out=0 elapsed=43.6s

  [1285/20519] intraday_10258.csv.gz  in=185,423,611 out=0 elapsed=43.6s

  [1286/20519] intraday_10259.csv.gz  in=185,518,466 out=0 elapsed=43.6s

  [1287/20519] intraday_10260.csv.gz  in=185,601,650 out=0 elapsed=43.6s

  [1288/20519] intraday_10261.csv.gz  in=185,686,507 out=0 elapsed=43.6s

  [1289/20519] intraday_10262.csv.gz  in=185,785,713 out=0 elapsed=43.7s

  [1290/20519] intraday_10263.csv.gz  in=185,902,292 out=0 elapsed=43.7s

  [1291/20519] intraday_10265.csv.gz  in=186,005,934 out=0 elapsed=43.7s

  [1292/20519] intraday_10264.csv.gz  in=186,141,184 out=0 elapsed=43.8s

  [1293/20519] intraday_10266.csv.gz  in=186,239,622 out=0 elapsed=43.8s

  [1294/20519] intraday_1027.csv.gz  in=186,251,957 out=0 elapsed=43.8s

  [1295/20519] intraday_10267.csv.gz  in=186,327,889 out=0 elapsed=43.8s

  [1296/20519] intraday_10268.csv.gz  in=186,419,031 out=0 elapsed=43.8s

  [1297/20519] intraday_10269.csv.gz  in=186,494,597 out=0 elapsed=43.8s

  [1298/20519] intraday_10271.csv.gz  in=186,567,903 out=0 elapsed=43.9s

  [1299/20519] intraday_10270.csv.gz  in=186,670,937 out=0 elapsed=43.9s

  [1300/20519] intraday_10273.csv.gz  in=186,762,094 out=0 elapsed=43.9s

  [1301/20519] intraday_10272.csv.gz  in=186,856,537 out=0 elapsed=44.0s

  [1302/20519] intraday_10275.csv.gz  in=186,930,292 out=0 elapsed=44.0s

  [1303/20519] intraday_10274.csv.gz  in=187,041,830 out=0 elapsed=44.0s

  [1304/20519] intraday_10276.csv.gz  in=187,124,059 out=0 elapsed=44.0s

  [1305/20519] intraday_1028.csv.gz  in=187,135,831 out=0 elapsed=44.0s

  [1306/20519] intraday_10277.csv.gz  in=187,213,776 out=0 elapsed=44.1s

  [1307/20519] intraday_10278.csv.gz  in=187,304,715 out=0 elapsed=44.1s

  [1308/20519] intraday_10279.csv.gz  in=187,386,833 out=0 elapsed=44.1s

  [1309/20519] intraday_10281.csv.gz  in=187,497,582 out=0 elapsed=44.2s

  [1310/20519] intraday_10280.csv.gz  in=187,595,459 out=0 elapsed=44.2s

  [1311/20519] intraday_10282.csv.gz  in=187,689,067 out=0 elapsed=44.2s

  [1312/20519] intraday_10283.csv.gz  in=187,797,424 out=0 elapsed=44.2s

  [1313/20519] intraday_10284.csv.gz  in=187,871,229 out=0 elapsed=44.2s

  [1314/20519] intraday_10285.csv.gz  in=187,959,414 out=0 elapsed=44.3s

  [1315/20519] intraday_10287.csv.gz  in=188,035,902 out=0 elapsed=44.3s

  [1316/20519] intraday_10286.csv.gz  in=188,133,461 out=0 elapsed=44.3s

  [1317/20519] intraday_1029.csv.gz  in=188,145,189 out=0 elapsed=44.3s

  [1318/20519] intraday_10289.csv.gz  in=188,206,733 out=0 elapsed=44.3s

  [1319/20519] intraday_10292.csv.gz  in=188,220,797 out=0 elapsed=44.4s

  [1320/20519] intraday_10288.csv.gz  in=188,335,624 out=0 elapsed=44.4s

  [1321/20519] intraday_10290.csv.gz  in=188,415,794 out=0 elapsed=44.4s

  [1322/20519] intraday_10291.csv.gz  in=188,484,146 out=0 elapsed=44.4s

  [1323/20519] intraday_10293.csv.gz  in=188,496,204 out=0 elapsed=44.4s

  [1324/20519] intraday_10294.csv.gz  in=188,511,699 out=0 elapsed=44.4s

  [1325/20519] intraday_10295.csv.gz  in=188,521,614 out=0 elapsed=44.4s

  [1326/20519] intraday_10297.csv.gz  in=188,535,086 out=0 elapsed=44.4s

  [1327/20519] intraday_10296.csv.gz  in=188,546,660 out=0 elapsed=44.4s

  [1328/20519] intraday_10298.csv.gz  in=188,559,588 out=0 elapsed=44.4s

  [1329/20519] intraday_10299.csv.gz  in=188,569,850 out=0 elapsed=44.4s

  [1330/20519] intraday_1030.csv.gz  in=188,581,890 out=0 elapsed=44.4s

  [1331/20519] intraday_10301.csv.gz  in=188,595,562 out=0 elapsed=44.4s

  [1332/20519] intraday_10300.csv.gz  in=188,606,985 out=0 elapsed=44.4s

  [1333/20519] intraday_10302.csv.gz  in=188,618,654 out=0 elapsed=44.5s

  [1334/20519] intraday_10303.csv.gz  in=188,629,492 out=0 elapsed=44.5s

  [1335/20519] intraday_10304.csv.gz  in=188,641,915 out=0 elapsed=44.5s

  [1336/20519] intraday_10305.csv.gz  in=188,655,133 out=0 elapsed=44.5s

  [1337/20519] intraday_10306.csv.gz  in=188,664,538 out=0 elapsed=44.5s

  [1338/20519] intraday_10308.csv.gz  in=188,677,350 out=0 elapsed=44.5s

  [1339/20519] intraday_10307.csv.gz  in=188,688,056 out=0 elapsed=44.5s

  [1340/20519] intraday_10309.csv.gz  in=188,701,110 out=0 elapsed=44.5s

  [1341/20519] intraday_1031.csv.gz  in=188,721,100 out=0 elapsed=44.5s

  [1342/20519] intraday_10312.csv.gz  in=188,732,061 out=0 elapsed=44.6s

  [1343/20519] intraday_10311.csv.gz  in=188,743,045 out=0 elapsed=44.6s

  [1344/20519] intraday_10310.csv.gz  in=188,754,760 out=0 elapsed=44.6s

  [1345/20519] intraday_10313.csv.gz  in=188,768,189 out=0 elapsed=44.6s

  [1346/20519] intraday_10315.csv.gz  in=188,780,278 out=0 elapsed=44.6s

  [1347/20519] intraday_10314.csv.gz  in=188,792,750 out=0 elapsed=44.6s

  [1348/20519] intraday_10316.csv.gz  in=188,804,444 out=0 elapsed=44.6s

  [1349/20519] intraday_10317.csv.gz  in=188,815,229 out=0 elapsed=44.6s

  [1350/20519] intraday_10318.csv.gz  in=188,826,476 out=0 elapsed=44.6s

  [1351/20519] intraday_10319.csv.gz  in=188,837,841 out=0 elapsed=44.8s

  [1352/20519] intraday_1032.csv.gz  in=188,847,949 out=0 elapsed=44.8s

  [1353/20519] intraday_10320.csv.gz  in=188,858,824 out=0 elapsed=44.9s

  [1354/20519] intraday_10321.csv.gz  in=188,871,230 out=0 elapsed=44.9s

  [1355/20519] intraday_10322.csv.gz  in=188,885,572 out=0 elapsed=44.9s

  [1356/20519] intraday_10324.csv.gz  in=188,895,125 out=0 elapsed=44.9s

  [1357/20519] intraday_10323.csv.gz  in=188,909,570 out=0 elapsed=44.9s

  [1358/20519] intraday_10325.csv.gz  in=188,919,534 out=0 elapsed=44.9s

  [1359/20519] intraday_10326.csv.gz  in=188,930,923 out=0 elapsed=44.9s

  [1360/20519] intraday_10327.csv.gz  in=188,942,860 out=0 elapsed=45.0s

  [1361/20519] intraday_10328.csv.gz  in=188,953,908 out=0 elapsed=45.0s

  [1362/20519] intraday_10329.csv.gz  in=188,965,141 out=0 elapsed=45.0s

  [1363/20519] intraday_1033.csv.gz  in=188,976,686 out=0 elapsed=45.0s

  [1364/20519] intraday_10330.csv.gz  in=188,987,032 out=0 elapsed=45.0s

  [1365/20519] intraday_10331.csv.gz  in=188,996,876 out=0 elapsed=45.0s

  [1366/20519] intraday_10332.csv.gz  in=189,007,668 out=0 elapsed=45.0s

  [1367/20519] intraday_10333.csv.gz  in=189,019,146 out=0 elapsed=45.1s

  [1368/20519] intraday_10334.csv.gz  in=189,032,417 out=0 elapsed=45.1s

  [1369/20519] intraday_10335.csv.gz  in=189,043,121 out=0 elapsed=45.1s

  [1370/20519] intraday_10337.csv.gz  in=189,056,019 out=0 elapsed=45.1s

  [1371/20519] intraday_10336.csv.gz  in=189,069,169 out=0 elapsed=45.1s

  [1372/20519] intraday_10339.csv.gz  in=189,083,010 out=0 elapsed=45.1s

  [1373/20519] intraday_10338.csv.gz  in=189,093,158 out=0 elapsed=45.1s

  [1374/20519] intraday_10340.csv.gz  in=189,104,946 out=0 elapsed=45.1s

  [1375/20519] intraday_1034.csv.gz  in=189,116,343 out=0 elapsed=45.1s

  [1376/20519] intraday_10342.csv.gz  in=189,127,521 out=0 elapsed=45.1s

  [1377/20519] intraday_10343.csv.gz  in=189,138,231 out=0 elapsed=45.1s

  [1378/20519] intraday_10344.csv.gz  in=189,148,362 out=0 elapsed=45.2s

  [1379/20519] intraday_10341.csv.gz  in=189,158,176 out=0 elapsed=45.2s

  [1380/20519] intraday_10345.csv.gz  in=189,170,240 out=0 elapsed=45.2s

  [1381/20519] intraday_10346.csv.gz  in=189,181,511 out=0 elapsed=45.2s

  [1382/20519] intraday_10347.csv.gz  in=189,192,631 out=0 elapsed=45.2s

  [1383/20519] intraday_10348.csv.gz  in=189,204,668 out=0 elapsed=45.2s

  [1384/20519] intraday_10349.csv.gz  in=189,215,483 out=0 elapsed=45.2s

  [1385/20519] intraday_10350.csv.gz  in=189,226,788 out=0 elapsed=45.2s

  [1386/20519] intraday_10351.csv.gz  in=189,236,850 out=0 elapsed=45.3s

  [1387/20519] intraday_1035.csv.gz  in=189,252,102 out=0 elapsed=45.3s

  [1388/20519] intraday_10353.csv.gz  in=189,262,051 out=0 elapsed=45.3s

  [1389/20519] intraday_10352.csv.gz  in=189,273,565 out=0 elapsed=45.3s

  [1390/20519] intraday_10354.csv.gz  in=189,285,616 out=0 elapsed=45.3s

  [1391/20519] intraday_10356.csv.gz  in=189,296,147 out=0 elapsed=45.3s

  [1392/20519] intraday_10355.csv.gz  in=189,308,623 out=0 elapsed=45.3s

  [1393/20519] intraday_10357.csv.gz  in=189,326,487 out=0 elapsed=45.3s

  [1394/20519] intraday_10358.csv.gz  in=189,340,638 out=0 elapsed=45.3s

  [1395/20519] intraday_10359.csv.gz  in=189,353,256 out=0 elapsed=45.3s

  [1396/20519] intraday_10360.csv.gz  in=189,366,481 out=0 elapsed=45.4s

  [1397/20519] intraday_10361.csv.gz  in=189,378,006 out=0 elapsed=45.4s

  [1398/20519] intraday_1036.csv.gz  in=189,402,208 out=0 elapsed=45.4s

  [1399/20519] intraday_10363.csv.gz  in=189,412,105 out=0 elapsed=45.4s

  [1400/20519] intraday_10362.csv.gz  in=189,423,970 out=0 elapsed=45.4s

  [1401/20519] intraday_10365.csv.gz  in=189,435,852 out=0 elapsed=45.4s

  [1402/20519] intraday_10364.csv.gz  in=189,446,829 out=0 elapsed=45.4s

  [1403/20519] intraday_10366.csv.gz  in=189,458,931 out=0 elapsed=45.4s

  [1404/20519] intraday_10367.csv.gz  in=189,471,095 out=0 elapsed=45.4s

  [1405/20519] intraday_10369.csv.gz  in=189,480,979 out=0 elapsed=45.4s

  [1406/20519] intraday_10368.csv.gz  in=189,492,194 out=0 elapsed=45.4s

  [1407/20519] intraday_10370.csv.gz  in=189,504,425 out=0 elapsed=45.5s

  [1408/20519] intraday_1037.csv.gz  in=189,516,956 out=0 elapsed=45.5s

  [1409/20519] intraday_10371.csv.gz  in=189,527,614 out=0 elapsed=45.5s

  [1410/20519] intraday_10372.csv.gz  in=189,538,902 out=0 elapsed=45.5s

  [1411/20519] intraday_10374.csv.gz  in=189,547,698 out=0 elapsed=45.5s

  [1412/20519] intraday_10373.csv.gz  in=189,558,451 out=0 elapsed=45.5s

  [1413/20519] intraday_10375.csv.gz  in=189,568,565 out=0 elapsed=45.5s

  [1414/20519] intraday_10378.csv.gz  in=189,582,167 out=0 elapsed=45.5s

  [1415/20519] intraday_10376.csv.gz  in=189,594,050 out=0 elapsed=45.5s

  [1416/20519] intraday_10377.csv.gz  in=189,609,647 out=0 elapsed=45.5s

  [1417/20519] intraday_10379.csv.gz  in=189,621,410 out=0 elapsed=45.5s

  [1418/20519] intraday_1038.csv.gz  in=189,633,115 out=0 elapsed=45.6s

  [1419/20519] intraday_10380.csv.gz  in=189,642,668 out=0 elapsed=45.6s

  [1420/20519] intraday_10382.csv.gz  in=189,653,287 out=0 elapsed=45.6s

  [1421/20519] intraday_10381.csv.gz  in=189,667,056 out=0 elapsed=45.6s

  [1422/20519] intraday_10383.csv.gz  in=189,680,840 out=0 elapsed=45.6s

  [1423/20519] intraday_10385.csv.gz  in=189,691,780 out=0 elapsed=45.6s

  [1424/20519] intraday_10384.csv.gz  in=189,704,206 out=0 elapsed=45.6s

  [1425/20519] intraday_10387.csv.gz  in=189,717,062 out=0 elapsed=45.6s

  [1426/20519] intraday_10386.csv.gz  in=189,729,601 out=0 elapsed=45.6s

  [1427/20519] intraday_10388.csv.gz  in=189,742,115 out=0 elapsed=45.6s

  [1428/20519] intraday_10390.csv.gz  in=189,754,488 out=0 elapsed=45.7s

  [1429/20519] intraday_10389.csv.gz  in=189,766,363 out=0 elapsed=45.7s

  [1430/20519] intraday_1039.csv.gz  in=189,779,387 out=0 elapsed=45.7s

  [1431/20519] intraday_10391.csv.gz  in=189,790,465 out=0 elapsed=45.7s

  [1432/20519] intraday_10392.csv.gz  in=189,802,400 out=0 elapsed=45.7s

  [1433/20519] intraday_10393.csv.gz  in=189,815,004 out=0 elapsed=45.7s

  [1434/20519] intraday_10394.csv.gz  in=189,825,216 out=0 elapsed=45.7s

  [1435/20519] intraday_10395.csv.gz  in=189,836,666 out=0 elapsed=45.7s

  [1436/20519] intraday_10396.csv.gz  in=189,849,361 out=0 elapsed=45.7s

  [1437/20519] intraday_10397.csv.gz  in=189,860,975 out=0 elapsed=45.7s

  [1438/20519] intraday_10398.csv.gz  in=189,872,737 out=0 elapsed=45.8s

  [1439/20519] intraday_10399.csv.gz  in=189,883,013 out=0 elapsed=45.8s

  [1440/20519] intraday_1040.csv.gz  in=189,895,412 out=0 elapsed=45.8s

  [1441/20519] intraday_10400.csv.gz  in=189,910,843 out=0 elapsed=45.8s

  [1442/20519] intraday_10401.csv.gz  in=189,920,129 out=0 elapsed=45.8s

  [1443/20519] intraday_10403.csv.gz  in=189,940,449 out=0 elapsed=45.8s

  [1444/20519] intraday_10404.csv.gz  in=189,953,623 out=0 elapsed=45.8s

  [1445/20519] intraday_10405.csv.gz  in=189,963,683 out=0 elapsed=45.8s

  [1446/20519] intraday_10402.csv.gz  in=189,975,359 out=0 elapsed=45.8s

  [1447/20519] intraday_10408.csv.gz  in=189,986,938 out=0 elapsed=45.9s

  [1448/20519] intraday_10406.csv.gz  in=190,002,005 out=0 elapsed=45.9s

  [1449/20519] intraday_10409.csv.gz  in=190,017,121 out=0 elapsed=45.9s

  [1450/20519] intraday_10407.csv.gz  in=190,030,073 out=0 elapsed=45.9s

  [1451/20519] intraday_1041.csv.gz  in=190,045,358 out=0 elapsed=45.9s

  [1452/20519] intraday_10410.csv.gz  in=190,060,426 out=0 elapsed=45.9s

  [1453/20519] intraday_10411.csv.gz  in=190,077,193 out=0 elapsed=45.9s

  [1454/20519] intraday_10412.csv.gz  in=190,091,577 out=0 elapsed=45.9s

  [1455/20519] intraday_10415.csv.gz  in=190,103,098 out=0 elapsed=46.0s

  [1456/20519] intraday_10413.csv.gz  in=190,117,061 out=0 elapsed=46.0s

  [1457/20519] intraday_10414.csv.gz  in=190,127,352 out=0 elapsed=46.0s

  [1458/20519] intraday_10417.csv.gz  in=190,139,566 out=0 elapsed=46.0s

  [1459/20519] intraday_10416.csv.gz  in=190,150,246 out=0 elapsed=46.0s

  [1460/20519] intraday_10418.csv.gz  in=190,161,069 out=0 elapsed=46.0s

  [1461/20519] intraday_10419.csv.gz  in=190,173,715 out=0 elapsed=46.0s

  [1462/20519] intraday_1042.csv.gz  in=190,185,728 out=0 elapsed=46.0s

  [1463/20519] intraday_10422.csv.gz  in=190,196,306 out=0 elapsed=46.0s

  [1464/20519] intraday_10421.csv.gz  in=190,210,129 out=0 elapsed=46.0s

  [1465/20519] intraday_10420.csv.gz  in=190,223,133 out=0 elapsed=46.0s

  [1466/20519] intraday_10423.csv.gz  in=190,234,082 out=0 elapsed=46.1s

  [1467/20519] intraday_10425.csv.gz  in=190,245,396 out=0 elapsed=46.1s

  [1468/20519] intraday_10424.csv.gz  in=190,256,265 out=0 elapsed=46.1s

  [1469/20519] intraday_10426.csv.gz  in=190,267,065 out=0 elapsed=46.1s

  [1470/20519] intraday_10427.csv.gz  in=190,281,516 out=0 elapsed=46.1s

  [1471/20519] intraday_10429.csv.gz  in=190,294,215 out=0 elapsed=46.1s

  [1472/20519] intraday_10428.csv.gz  in=190,309,957 out=0 elapsed=46.1s

  [1473/20519] intraday_1043.csv.gz  in=190,326,010 out=0 elapsed=46.1s

  [1474/20519] intraday_10430.csv.gz  in=190,341,261 out=0 elapsed=46.1s

  [1475/20519] intraday_10431.csv.gz  in=190,352,365 out=0 elapsed=46.1s

  [1476/20519] intraday_10433.csv.gz  in=190,364,905 out=0 elapsed=46.1s

  [1477/20519] intraday_10432.csv.gz  in=190,375,823 out=0 elapsed=46.1s

  [1478/20519] intraday_10435.csv.gz  in=190,388,411 out=0 elapsed=46.1s

  [1479/20519] intraday_10434.csv.gz  in=190,398,422 out=0 elapsed=46.1s

  [1480/20519] intraday_10436.csv.gz  in=190,407,256 out=0 elapsed=46.1s

  [1481/20519] intraday_10437.csv.gz  in=190,417,986 out=0 elapsed=46.1s

  [1482/20519] intraday_10439.csv.gz  in=190,432,463 out=0 elapsed=46.2s

  [1483/20519] intraday_10438.csv.gz  in=190,440,829 out=0 elapsed=46.2s

  [1484/20519] intraday_10440.csv.gz  in=190,453,093 out=0 elapsed=46.2s

  [1485/20519] intraday_1044.csv.gz  in=190,467,263 out=0 elapsed=46.2s

  [1486/20519] intraday_10442.csv.gz  in=190,476,737 out=0 elapsed=46.2s

  [1487/20519] intraday_10441.csv.gz  in=190,489,830 out=0 elapsed=46.2s

  [1488/20519] intraday_10443.csv.gz  in=190,501,251 out=0 elapsed=46.2s

  [1489/20519] intraday_10444.csv.gz  in=190,515,555 out=0 elapsed=46.2s

  [1490/20519] intraday_10445.csv.gz  in=190,528,567 out=0 elapsed=46.2s

  [1491/20519] intraday_10446.csv.gz  in=190,540,326 out=0 elapsed=46.2s

  [1492/20519] intraday_10447.csv.gz  in=190,551,500 out=0 elapsed=46.2s

  [1493/20519] intraday_10448.csv.gz  in=190,564,926 out=0 elapsed=46.3s

  [1494/20519] intraday_10449.csv.gz  in=190,579,035 out=0 elapsed=46.3s

  [1495/20519] intraday_10450.csv.gz  in=190,590,743 out=0 elapsed=46.3s

  [1496/20519] intraday_1045.csv.gz  in=190,605,078 out=0 elapsed=46.3s

  [1497/20519] intraday_10452.csv.gz  in=190,619,233 out=0 elapsed=46.3s

  [1498/20519] intraday_10451.csv.gz  in=190,631,584 out=0 elapsed=46.3s

  [1499/20519] intraday_10454.csv.gz  in=190,641,987 out=0 elapsed=46.3s

  [1500/20519] intraday_10453.csv.gz  in=190,651,958 out=0 elapsed=46.3s

  [1501/20519] intraday_10457.csv.gz  in=190,663,585 out=0 elapsed=46.3s

  [1502/20519] intraday_10455.csv.gz  in=190,676,207 out=0 elapsed=46.3s

  [1503/20519] intraday_10456.csv.gz  in=190,690,050 out=0 elapsed=46.3s

  [1504/20519] intraday_10458.csv.gz  in=190,700,110 out=0 elapsed=46.4s

  [1505/20519] intraday_1046.csv.gz  in=190,712,832 out=0 elapsed=46.4s

  [1506/20519] intraday_10461.csv.gz  in=190,724,956 out=0 elapsed=46.4s

  [1507/20519] intraday_10459.csv.gz  in=190,735,845 out=0 elapsed=46.4s

  [1508/20519] intraday_10460.csv.gz  in=190,749,492 out=0 elapsed=46.4s

  [1509/20519] intraday_10462.csv.gz  in=190,761,623 out=0 elapsed=46.4s

  [1510/20519] intraday_10463.csv.gz  in=190,773,305 out=0 elapsed=46.4s

  [1511/20519] intraday_10464.csv.gz  in=190,784,570 out=0 elapsed=46.4s

  [1512/20519] intraday_10465.csv.gz  in=190,795,768 out=0 elapsed=46.4s

  [1513/20519] intraday_10466.csv.gz  in=190,807,446 out=0 elapsed=46.5s

  [1514/20519] intraday_10467.csv.gz  in=190,819,138 out=0 elapsed=46.5s

  [1515/20519] intraday_10469.csv.gz  in=190,834,254 out=0 elapsed=46.5s

  [1516/20519] intraday_10468.csv.gz  in=190,846,577 out=0 elapsed=46.5s

  [1517/20519] intraday_1047.csv.gz  in=190,862,993 out=0 elapsed=46.5s

  [1518/20519] intraday_10472.csv.gz  in=190,873,868 out=0 elapsed=46.5s

  [1519/20519] intraday_10470.csv.gz  in=190,885,909 out=0 elapsed=46.5s

  [1520/20519] intraday_10471.csv.gz  in=190,895,719 out=0 elapsed=46.5s

  [1521/20519] intraday_10474.csv.gz  in=190,908,942 out=0 elapsed=46.5s

  [1522/20519] intraday_10473.csv.gz  in=190,921,235 out=0 elapsed=46.5s

  [1523/20519] intraday_10476.csv.gz  in=190,934,238 out=0 elapsed=46.6s

  [1524/20519] intraday_10475.csv.gz  in=190,945,837 out=0 elapsed=46.6s

  [1525/20519] intraday_10477.csv.gz  in=190,955,640 out=0 elapsed=46.6s

  [1526/20519] intraday_10478.csv.gz  in=190,964,740 out=0 elapsed=46.6s

  [1527/20519] intraday_10479.csv.gz  in=190,975,521 out=0 elapsed=46.6s

  [1528/20519] intraday_1048.csv.gz  in=190,987,267 out=0 elapsed=46.6s

  [1529/20519] intraday_10480.csv.gz  in=190,999,633 out=0 elapsed=46.6s

  [1530/20519] intraday_10481.csv.gz  in=191,013,916 out=0 elapsed=46.6s

  [1531/20519] intraday_10482.csv.gz  in=191,025,722 out=0 elapsed=46.6s

  [1532/20519] intraday_10483.csv.gz  in=191,038,087 out=0 elapsed=46.6s

  [1533/20519] intraday_10484.csv.gz  in=191,051,320 out=0 elapsed=46.6s

  [1534/20519] intraday_10485.csv.gz  in=191,063,187 out=0 elapsed=46.6s

  [1535/20519] intraday_10487.csv.gz  in=191,074,211 out=0 elapsed=46.7s

  [1536/20519] intraday_10488.csv.gz  in=191,085,054 out=0 elapsed=46.7s

  [1537/20519] intraday_10486.csv.gz  in=191,097,044 out=0 elapsed=46.7s

  [1538/20519] intraday_10489.csv.gz  in=191,111,790 out=0 elapsed=46.7s

  [1539/20519] intraday_1049.csv.gz  in=191,124,073 out=0 elapsed=46.7s

  [1540/20519] intraday_10490.csv.gz  in=191,135,386 out=0 elapsed=46.7s

  [1541/20519] intraday_10492.csv.gz  in=191,146,647 out=0 elapsed=46.7s

  [1542/20519] intraday_10491.csv.gz  in=191,158,166 out=0 elapsed=46.7s

  [1543/20519] intraday_10493.csv.gz  in=191,170,388 out=0 elapsed=46.7s

  [1544/20519] intraday_10495.csv.gz  in=191,181,712 out=0 elapsed=46.8s

  [1545/20519] intraday_10494.csv.gz  in=191,195,455 out=0 elapsed=46.8s

  [1546/20519] intraday_10496.csv.gz  in=191,207,953 out=0 elapsed=46.8s

  [1547/20519] intraday_10497.csv.gz  in=191,219,335 out=0 elapsed=46.8s

  [1548/20519] intraday_10499.csv.gz  in=191,231,641 out=0 elapsed=46.8s

  [1549/20519] intraday_10498.csv.gz  in=191,242,310 out=0 elapsed=46.8s

  [1550/20519] intraday_1050.csv.gz  in=191,254,843 out=0 elapsed=46.8s

  [1551/20519] intraday_10500.csv.gz  in=191,265,624 out=0 elapsed=46.8s

  [1552/20519] intraday_10501.csv.gz  in=191,279,621 out=0 elapsed=46.8s

  [1553/20519] intraday_10503.csv.gz  in=191,290,713 out=0 elapsed=46.9s

  [1554/20519] intraday_10502.csv.gz  in=191,300,921 out=0 elapsed=46.9s

  [1555/20519] intraday_10505.csv.gz  in=191,316,248 out=0 elapsed=46.9s

  [1556/20519] intraday_10504.csv.gz  in=191,326,633 out=0 elapsed=46.9s

  [1557/20519] intraday_10506.csv.gz  in=191,339,959 out=0 elapsed=46.9s

  [1558/20519] intraday_10508.csv.gz  in=191,352,788 out=0 elapsed=47.0s

  [1559/20519] intraday_10507.csv.gz  in=191,366,201 out=0 elapsed=47.0s

  [1560/20519] intraday_10509.csv.gz  in=191,378,469 out=0 elapsed=47.0s

  [1561/20519] intraday_1051.csv.gz  in=191,391,399 out=0 elapsed=47.0s

  [1562/20519] intraday_10510.csv.gz  in=191,402,922 out=0 elapsed=47.0s

  [1563/20519] intraday_10511.csv.gz  in=191,414,362 out=0 elapsed=47.0s

  [1564/20519] intraday_10513.csv.gz  in=191,428,464 out=0 elapsed=47.0s

  [1565/20519] intraday_10512.csv.gz  in=191,441,197 out=0 elapsed=47.0s

  [1566/20519] intraday_10514.csv.gz  in=191,453,662 out=0 elapsed=47.1s

  [1567/20519] intraday_10516.csv.gz  in=191,464,104 out=0 elapsed=47.1s

  [1568/20519] intraday_10515.csv.gz  in=191,476,461 out=0 elapsed=47.1s

  [1569/20519] intraday_10517.csv.gz  in=191,489,616 out=0 elapsed=47.1s

  [1570/20519] intraday_10518.csv.gz  in=191,500,361 out=0 elapsed=47.1s

  [1571/20519] intraday_10520.csv.gz  in=191,511,438 out=0 elapsed=47.1s

  [1572/20519] intraday_10519.csv.gz  in=191,528,213 out=0 elapsed=47.1s

  [1573/20519] intraday_1052.csv.gz  in=191,539,553 out=0 elapsed=47.1s

  [1574/20519] intraday_10522.csv.gz  in=191,549,508 out=0 elapsed=47.1s

  [1575/20519] intraday_10521.csv.gz  in=191,558,748 out=0 elapsed=47.1s

  [1576/20519] intraday_10523.csv.gz  in=191,571,999 out=0 elapsed=47.2s

  [1577/20519] intraday_10524.csv.gz  in=191,588,880 out=0 elapsed=47.2s

  [1578/20519] intraday_10526.csv.gz  in=191,599,923 out=0 elapsed=47.2s

  [1579/20519] intraday_10525.csv.gz  in=191,613,474 out=0 elapsed=47.2s

  [1580/20519] intraday_10527.csv.gz  in=191,625,063 out=0 elapsed=47.2s

  [1581/20519] intraday_10528.csv.gz  in=191,637,417 out=0 elapsed=47.2s

  [1582/20519] intraday_10529.csv.gz  in=191,648,915 out=0 elapsed=47.2s

  [1583/20519] intraday_1053.csv.gz  in=191,674,376 out=0 elapsed=47.3s

  [1584/20519] intraday_10532.csv.gz  in=191,684,946 out=0 elapsed=47.3s

  [1585/20519] intraday_10530.csv.gz  in=191,700,286 out=0 elapsed=47.3s

  [1586/20519] intraday_10531.csv.gz  in=191,712,691 out=0 elapsed=47.3s

  [1587/20519] intraday_10533.csv.gz  in=191,724,144 out=0 elapsed=47.3s

  [1588/20519] intraday_10534.csv.gz  in=191,738,420 out=0 elapsed=47.3s

  [1589/20519] intraday_10535.csv.gz  in=191,750,756 out=0 elapsed=47.3s

  [1590/20519] intraday_10536.csv.gz  in=191,762,218 out=0 elapsed=47.3s

  [1591/20519] intraday_10537.csv.gz  in=191,774,898 out=0 elapsed=47.3s

  [1592/20519] intraday_10538.csv.gz  in=191,787,103 out=0 elapsed=47.3s

  [1593/20519] intraday_10539.csv.gz  in=191,799,226 out=0 elapsed=47.3s

  [1594/20519] intraday_10540.csv.gz  in=191,811,568 out=0 elapsed=47.3s

  [1595/20519] intraday_1054.csv.gz  in=191,823,346 out=0 elapsed=47.3s

  [1596/20519] intraday_10541.csv.gz  in=191,833,411 out=0 elapsed=47.3s

  [1597/20519] intraday_10542.csv.gz  in=191,847,106 out=0 elapsed=47.4s

  [1598/20519] intraday_10543.csv.gz  in=191,860,497 out=0 elapsed=47.4s

  [1599/20519] intraday_10544.csv.gz  in=191,873,765 out=0 elapsed=47.4s

  [1600/20519] intraday_10545.csv.gz  in=191,885,759 out=0 elapsed=47.4s

  [1601/20519] intraday_10546.csv.gz  in=191,895,529 out=0 elapsed=47.4s

  [1602/20519] intraday_10548.csv.gz  in=191,906,647 out=0 elapsed=47.4s

  [1603/20519] intraday_10547.csv.gz  in=191,922,325 out=0 elapsed=47.4s

  [1604/20519] intraday_10550.csv.gz  in=191,935,619 out=0 elapsed=47.4s

  [1605/20519] intraday_10549.csv.gz  in=191,947,314 out=0 elapsed=47.4s

  [1606/20519] intraday_1055.csv.gz  in=191,959,255 out=0 elapsed=47.4s

  [1607/20519] intraday_10551.csv.gz  in=191,972,675 out=0 elapsed=47.5s

  [1608/20519] intraday_10553.csv.gz  in=191,986,721 out=0 elapsed=47.5s

  [1609/20519] intraday_10552.csv.gz  in=191,997,209 out=0 elapsed=47.5s

  [1610/20519] intraday_10554.csv.gz  in=192,014,320 out=0 elapsed=47.5s

  [1611/20519] intraday_10557.csv.gz  in=192,028,715 out=0 elapsed=47.5s

  [1612/20519] intraday_10555.csv.gz  in=192,040,514 out=0 elapsed=47.5s

  [1613/20519] intraday_10556.csv.gz  in=192,055,721 out=0 elapsed=47.5s

  [1614/20519] intraday_10558.csv.gz  in=192,073,305 out=0 elapsed=47.5s

  [1615/20519] intraday_10559.csv.gz  in=192,087,964 out=0 elapsed=47.5s

  [1616/20519] intraday_1056.csv.gz  in=192,104,345 out=0 elapsed=47.5s

  [1617/20519] intraday_10562.csv.gz  in=192,116,161 out=0 elapsed=47.6s

  [1618/20519] intraday_10561.csv.gz  in=192,127,713 out=0 elapsed=47.6s

  [1619/20519] intraday_10560.csv.gz  in=192,144,919 out=0 elapsed=47.6s

  [1620/20519] intraday_10563.csv.gz  in=192,163,727 out=0 elapsed=47.6s

  [1621/20519] intraday_10566.csv.gz  in=192,175,661 out=0 elapsed=47.6s

  [1622/20519] intraday_10565.csv.gz  in=192,186,732 out=0 elapsed=47.6s

  [1623/20519] intraday_10564.csv.gz  in=192,200,124 out=0 elapsed=47.6s

  [1624/20519] intraday_10567.csv.gz  in=192,212,373 out=0 elapsed=47.6s

  [1625/20519] intraday_10569.csv.gz  in=192,222,452 out=0 elapsed=47.6s

  [1626/20519] intraday_1057.csv.gz  in=192,232,560 out=0 elapsed=47.7s

  [1627/20519] intraday_10568.csv.gz  in=192,247,988 out=0 elapsed=47.7s

  [1628/20519] intraday_10570.csv.gz  in=192,259,039 out=0 elapsed=47.7s

  [1629/20519] intraday_10571.csv.gz  in=192,271,326 out=0 elapsed=47.7s

  [1630/20519] intraday_10572.csv.gz  in=192,283,061 out=0 elapsed=47.7s

  [1631/20519] intraday_10573.csv.gz  in=192,294,038 out=0 elapsed=47.7s

  [1632/20519] intraday_10574.csv.gz  in=192,309,581 out=0 elapsed=47.7s

  [1633/20519] intraday_10575.csv.gz  in=192,325,550 out=0 elapsed=47.7s

  [1634/20519] intraday_10576.csv.gz  in=192,339,120 out=0 elapsed=47.7s

  [1635/20519] intraday_10578.csv.gz  in=192,350,428 out=0 elapsed=47.8s

  [1636/20519] intraday_10577.csv.gz  in=192,366,390 out=0 elapsed=47.8s

  [1637/20519] intraday_10579.csv.gz  in=192,377,295 out=0 elapsed=47.8s

  [1638/20519] intraday_1058.csv.gz  in=192,390,464 out=0 elapsed=47.8s

  [1639/20519] intraday_10580.csv.gz  in=192,403,154 out=0 elapsed=47.8s

  [1640/20519] intraday_10581.csv.gz  in=192,414,731 out=0 elapsed=47.8s

  [1641/20519] intraday_10582.csv.gz  in=192,424,495 out=0 elapsed=47.8s

  [1642/20519] intraday_10583.csv.gz  in=192,432,324 out=0 elapsed=47.8s

  [1643/20519] intraday_10584.csv.gz  in=192,442,942 out=0 elapsed=47.9s

  [1644/20519] intraday_10585.csv.gz  in=192,449,461 out=0 elapsed=47.9s

  [1645/20519] intraday_10587.csv.gz  in=192,462,067 out=0 elapsed=47.9s

  [1646/20519] intraday_10586.csv.gz  in=192,476,756 out=0 elapsed=47.9s

  [1647/20519] intraday_10589.csv.gz  in=192,486,243 out=0 elapsed=47.9s

  [1648/20519] intraday_10588.csv.gz  in=192,497,724 out=0 elapsed=47.9s

  [1649/20519] intraday_1059.csv.gz  in=192,520,541 out=0 elapsed=47.9s

  [1650/20519] intraday_10591.csv.gz  in=192,534,405 out=0 elapsed=47.9s

  [1651/20519] intraday_10590.csv.gz  in=192,546,024 out=0 elapsed=47.9s

  [1652/20519] intraday_10592.csv.gz  in=192,560,255 out=0 elapsed=48.0s

  [1653/20519] intraday_10593.csv.gz  in=192,571,033 out=0 elapsed=48.0s

  [1654/20519] intraday_10595.csv.gz  in=192,584,566 out=0 elapsed=48.0s

  [1655/20519] intraday_10596.csv.gz  in=192,598,654 out=0 elapsed=48.0s

  [1656/20519] intraday_10594.csv.gz  in=192,609,901 out=0 elapsed=48.0s

  [1657/20519] intraday_10597.csv.gz  in=192,621,978 out=0 elapsed=48.0s

  [1658/20519] intraday_10598.csv.gz  in=192,636,878 out=0 elapsed=48.0s

  [1659/20519] intraday_10599.csv.gz  in=192,649,921 out=0 elapsed=48.0s

  [1660/20519] intraday_10600.csv.gz  in=192,659,589 out=0 elapsed=48.0s

  [1661/20519] intraday_1060.csv.gz  in=192,674,486 out=0 elapsed=48.0s

  [1662/20519] intraday_10601.csv.gz  in=192,684,453 out=0 elapsed=48.1s

  [1663/20519] intraday_10604.csv.gz  in=192,695,525 out=0 elapsed=48.1s

  [1664/20519] intraday_10602.csv.gz  in=192,707,472 out=0 elapsed=48.1s

  [1665/20519] intraday_10603.csv.gz  in=192,720,002 out=0 elapsed=48.1s

  [1666/20519] intraday_10606.csv.gz  in=192,730,625 out=0 elapsed=48.1s

  [1667/20519] intraday_10605.csv.gz  in=192,741,091 out=0 elapsed=48.1s

  [1668/20519] intraday_10607.csv.gz  in=192,755,504 out=0 elapsed=48.2s

  [1669/20519] intraday_10608.csv.gz  in=192,768,018 out=0 elapsed=48.2s

  [1670/20519] intraday_10609.csv.gz  in=192,779,613 out=0 elapsed=48.2s

  [1671/20519] intraday_1061.csv.gz  in=192,791,539 out=0 elapsed=48.2s

  [1672/20519] intraday_10611.csv.gz  in=192,802,633 out=0 elapsed=48.2s

  [1673/20519] intraday_10612.csv.gz  in=192,814,800 out=0 elapsed=48.2s

  [1674/20519] intraday_10610.csv.gz  in=192,828,066 out=0 elapsed=48.2s

  [1675/20519] intraday_10613.csv.gz  in=192,839,907 out=0 elapsed=48.2s

  [1676/20519] intraday_10614.csv.gz  in=192,851,671 out=0 elapsed=48.2s

  [1677/20519] intraday_10615.csv.gz  in=192,863,475 out=0 elapsed=48.2s

  [1678/20519] intraday_10616.csv.gz  in=192,878,751 out=0 elapsed=48.3s

  [1679/20519] intraday_10617.csv.gz  in=192,890,648 out=0 elapsed=48.3s

  [1680/20519] intraday_10618.csv.gz  in=192,900,289 out=0 elapsed=48.3s

  [1681/20519] intraday_10619.csv.gz  in=192,911,489 out=0 elapsed=48.3s

  [1682/20519] intraday_10621.csv.gz  in=192,923,067 out=0 elapsed=48.3s

  [1683/20519] intraday_10620.csv.gz  in=192,934,757 out=0 elapsed=48.3s

  [1684/20519] intraday_1062.csv.gz  in=192,948,250 out=0 elapsed=48.3s

  [1685/20519] intraday_10622.csv.gz  in=192,960,101 out=0 elapsed=48.3s

  [1686/20519] intraday_10623.csv.gz  in=192,971,702 out=0 elapsed=48.3s

  [1687/20519] intraday_10624.csv.gz  in=192,982,758 out=0 elapsed=48.4s

  [1688/20519] intraday_10626.csv.gz  in=192,993,747 out=0 elapsed=48.4s

  [1689/20519] intraday_10627.csv.gz  in=193,005,920 out=0 elapsed=48.4s

  [1690/20519] intraday_10625.csv.gz  in=193,015,917 out=0 elapsed=48.4s

  [1691/20519] intraday_1063.csv.gz  in=193,028,163 out=0 elapsed=48.4s

  [1692/20519] intraday_10628.csv.gz  in=193,041,714 out=0 elapsed=48.4s

  [1693/20519] intraday_10629.csv.gz  in=193,053,148 out=0 elapsed=48.4s

  [1694/20519] intraday_10630.csv.gz  in=193,066,757 out=0 elapsed=48.4s

  [1695/20519] intraday_10632.csv.gz  in=193,076,948 out=0 elapsed=48.4s

  [1696/20519] intraday_10634.csv.gz  in=193,088,290 out=0 elapsed=48.4s

  [1697/20519] intraday_10633.csv.gz  in=193,100,137 out=0 elapsed=48.4s

  [1698/20519] intraday_10631.csv.gz  in=193,112,303 out=0 elapsed=48.4s

  [1699/20519] intraday_10635.csv.gz  in=193,122,352 out=0 elapsed=48.5s

  [1700/20519] intraday_10637.csv.gz  in=193,133,490 out=0 elapsed=48.5s

  [1701/20519] intraday_10636.csv.gz  in=193,144,518 out=0 elapsed=48.5s

  [1702/20519] intraday_10638.csv.gz  in=193,156,016 out=0 elapsed=48.5s

  [1703/20519] intraday_10639.csv.gz  in=193,168,091 out=0 elapsed=48.5s

  [1704/20519] intraday_10640.csv.gz  in=193,184,351 out=0 elapsed=48.5s

  [1705/20519] intraday_10641.csv.gz  in=193,194,479 out=0 elapsed=48.5s

  [1706/20519] intraday_10642.csv.gz  in=193,207,797 out=0 elapsed=48.5s

  [1707/20519] intraday_1064.csv.gz  in=193,220,454 out=0 elapsed=48.5s

  [1708/20519] intraday_10643.csv.gz  in=193,232,262 out=0 elapsed=48.5s

  [1709/20519] intraday_10644.csv.gz  in=193,242,564 out=0 elapsed=48.6s

  [1710/20519] intraday_10646.csv.gz  in=193,255,097 out=0 elapsed=48.6s

  [1711/20519] intraday_10645.csv.gz  in=193,266,745 out=0 elapsed=48.6s

  [1712/20519] intraday_10647.csv.gz  in=193,276,590 out=0 elapsed=48.6s

  [1713/20519] intraday_10649.csv.gz  in=193,287,056 out=0 elapsed=48.6s

  [1714/20519] intraday_10648.csv.gz  in=193,301,021 out=0 elapsed=48.6s

  [1715/20519] intraday_1065.csv.gz  in=193,312,841 out=0 elapsed=48.6s

  [1716/20519] intraday_10651.csv.gz  in=193,322,746 out=0 elapsed=48.6s

  [1717/20519] intraday_10650.csv.gz  in=193,334,023 out=0 elapsed=48.6s

  [1718/20519] intraday_10653.csv.gz  in=193,348,432 out=0 elapsed=48.6s

  [1719/20519] intraday_10655.csv.gz  in=193,359,584 out=0 elapsed=48.7s

  [1720/20519] intraday_10654.csv.gz  in=193,373,640 out=0 elapsed=48.7s

  [1721/20519] intraday_10652.csv.gz  in=193,387,402 out=0 elapsed=48.7s

  [1722/20519] intraday_10656.csv.gz  in=193,400,851 out=0 elapsed=48.7s

  [1723/20519] intraday_10657.csv.gz  in=193,413,663 out=0 elapsed=48.7s

  [1724/20519] intraday_10658.csv.gz  in=193,425,700 out=0 elapsed=48.7s

  [1725/20519] intraday_10659.csv.gz  in=193,438,500 out=0 elapsed=48.7s

  [1726/20519] intraday_10660.csv.gz  in=193,451,269 out=0 elapsed=48.7s

  [1727/20519] intraday_1066.csv.gz  in=193,465,948 out=0 elapsed=48.7s

  [1728/20519] intraday_10661.csv.gz  in=193,477,250 out=0 elapsed=48.8s

  [1729/20519] intraday_10662.csv.gz  in=193,488,414 out=0 elapsed=48.8s

  [1730/20519] intraday_10663.csv.gz  in=193,498,772 out=0 elapsed=48.8s

  [1731/20519] intraday_10667.csv.gz  in=193,508,659 out=0 elapsed=48.8s

  [1732/20519] intraday_10666.csv.gz  in=193,519,637 out=0 elapsed=48.8s

  [1733/20519] intraday_10665.csv.gz  in=193,530,788 out=0 elapsed=48.8s

  [1734/20519] intraday_10664.csv.gz  in=193,544,128 out=0 elapsed=48.8s

  [1735/20519] intraday_10668.csv.gz  in=193,552,954 out=0 elapsed=48.8s

  [1736/20519] intraday_10669.csv.gz  in=193,563,317 out=0 elapsed=48.8s

  [1737/20519] intraday_1067.csv.gz  in=193,575,117 out=0 elapsed=48.8s

  [1738/20519] intraday_10670.csv.gz  in=193,587,964 out=0 elapsed=48.8s

  [1739/20519] intraday_10671.csv.gz  in=193,605,199 out=0 elapsed=48.8s

  [1740/20519] intraday_10672.csv.gz  in=193,618,290 out=0 elapsed=48.8s

  [1741/20519] intraday_10674.csv.gz  in=193,629,480 out=0 elapsed=48.9s

  [1742/20519] intraday_10673.csv.gz  in=193,640,769 out=0 elapsed=48.9s

  [1743/20519] intraday_10675.csv.gz  in=193,653,839 out=0 elapsed=48.9s

  [1744/20519] intraday_10676.csv.gz  in=193,665,237 out=0 elapsed=48.9s

  [1745/20519] intraday_10679.csv.gz  in=193,677,178 out=0 elapsed=48.9s

  [1746/20519] intraday_1068.csv.gz  in=193,694,241 out=0 elapsed=48.9s

  [1747/20519] intraday_10678.csv.gz  in=193,705,112 out=0 elapsed=48.9s

  [1748/20519] intraday_10677.csv.gz  in=193,719,334 out=0 elapsed=48.9s

  [1749/20519] intraday_10681.csv.gz  in=193,732,470 out=0 elapsed=49.0s

  [1750/20519] intraday_10682.csv.gz  in=193,745,449 out=0 elapsed=49.0s

  [1751/20519] intraday_10680.csv.gz  in=193,756,656 out=0 elapsed=49.0s

  [1752/20519] intraday_10683.csv.gz  in=193,768,917 out=0 elapsed=49.0s

  [1753/20519] intraday_10684.csv.gz  in=193,781,291 out=0 elapsed=49.0s

  [1754/20519] intraday_10685.csv.gz  in=193,792,695 out=0 elapsed=49.0s

  [1755/20519] intraday_10687.csv.gz  in=193,805,200 out=0 elapsed=49.0s

  [1756/20519] intraday_10686.csv.gz  in=193,816,699 out=0 elapsed=49.1s

  [1757/20519] intraday_10688.csv.gz  in=193,827,508 out=0 elapsed=49.1s

  [1758/20519] intraday_10689.csv.gz  in=193,838,867 out=0 elapsed=49.1s

  [1759/20519] intraday_1069.csv.gz  in=193,851,802 out=0 elapsed=49.1s

  [1760/20519] intraday_10692.csv.gz  in=193,862,709 out=0 elapsed=49.1s

  [1761/20519] intraday_10691.csv.gz  in=193,875,750 out=0 elapsed=49.1s

  [1762/20519] intraday_10690.csv.gz  in=193,893,905 out=0 elapsed=49.1s

  [1763/20519] intraday_10693.csv.gz  in=193,905,003 out=0 elapsed=49.1s

  [1764/20519] intraday_10694.csv.gz  in=193,919,681 out=0 elapsed=49.1s

  [1765/20519] intraday_10695.csv.gz  in=193,930,799 out=0 elapsed=49.1s

  [1766/20519] intraday_10696.csv.gz  in=193,943,208 out=0 elapsed=49.1s

  [1767/20519] intraday_10697.csv.gz  in=193,955,324 out=0 elapsed=49.1s

  [1768/20519] intraday_10698.csv.gz  in=193,968,370 out=0 elapsed=49.2s

  [1769/20519] intraday_10699.csv.gz  in=193,978,838 out=0 elapsed=49.2s

  [1770/20519] intraday_1070.csv.gz  in=193,994,495 out=0 elapsed=49.2s

  [1771/20519] intraday_10700.csv.gz  in=194,009,802 out=0 elapsed=49.2s

  [1772/20519] intraday_10701.csv.gz  in=194,024,968 out=0 elapsed=49.2s

  [1773/20519] intraday_10702.csv.gz  in=194,037,499 out=0 elapsed=49.2s

  [1774/20519] intraday_10703.csv.gz  in=194,050,795 out=0 elapsed=49.2s

  [1775/20519] intraday_10704.csv.gz  in=194,066,351 out=0 elapsed=49.2s

  [1776/20519] intraday_10706.csv.gz  in=194,080,269 out=0 elapsed=49.2s

  [1777/20519] intraday_10705.csv.gz  in=194,097,466 out=0 elapsed=49.2s

  [1778/20519] intraday_10707.csv.gz  in=194,111,230 out=0 elapsed=49.3s

  [1779/20519] intraday_10708.csv.gz  in=194,123,170 out=0 elapsed=49.3s

  [1780/20519] intraday_1071.csv.gz  in=194,133,092 out=0 elapsed=49.3s

  [1781/20519] intraday_10709.csv.gz  in=194,144,395 out=0 elapsed=49.3s

  [1782/20519] intraday_10710.csv.gz  in=194,154,172 out=0 elapsed=49.3s

  [1783/20519] intraday_10711.csv.gz  in=194,166,657 out=0 elapsed=49.3s

  [1784/20519] intraday_10712.csv.gz  in=194,178,008 out=0 elapsed=49.3s

  [1785/20519] intraday_10713.csv.gz  in=194,190,629 out=0 elapsed=49.3s

  [1786/20519] intraday_10714.csv.gz  in=194,202,790 out=0 elapsed=49.3s

  [1787/20519] intraday_10716.csv.gz  in=194,213,367 out=0 elapsed=49.3s

  [1788/20519] intraday_10715.csv.gz  in=194,228,215 out=0 elapsed=49.3s

  [1789/20519] intraday_10718.csv.gz  in=194,240,784 out=0 elapsed=49.3s

  [1790/20519] intraday_10717.csv.gz  in=194,251,767 out=0 elapsed=49.3s

  [1791/20519] intraday_10719.csv.gz  in=194,263,025 out=0 elapsed=49.4s

  [1792/20519] intraday_10721.csv.gz  in=194,277,907 out=0 elapsed=49.4s

  [1793/20519] intraday_10720.csv.gz  in=194,289,543 out=0 elapsed=49.4s

  [1794/20519] intraday_1072.csv.gz  in=194,316,292 out=0 elapsed=49.4s

  [1795/20519] intraday_10722.csv.gz  in=194,331,243 out=0 elapsed=49.4s

  [1796/20519] intraday_10724.csv.gz  in=194,346,971 out=0 elapsed=49.4s

  [1797/20519] intraday_10723.csv.gz  in=194,361,273 out=0 elapsed=49.4s

  [1798/20519] intraday_10725.csv.gz  in=194,372,599 out=0 elapsed=49.4s

  [1799/20519] intraday_10726.csv.gz  in=194,383,023 out=0 elapsed=49.5s

  [1800/20519] intraday_10727.csv.gz  in=194,396,349 out=0 elapsed=49.5s

  [1801/20519] intraday_10728.csv.gz  in=194,407,066 out=0 elapsed=49.5s

  [1802/20519] intraday_10729.csv.gz  in=194,417,115 out=0 elapsed=49.5s

  [1803/20519] intraday_1073.csv.gz  in=194,428,206 out=0 elapsed=49.5s

  [1804/20519] intraday_10731.csv.gz  in=194,437,789 out=0 elapsed=49.5s

  [1805/20519] intraday_10730.csv.gz  in=194,444,008 out=0 elapsed=49.5s

  [1806/20519] intraday_10732.csv.gz  in=194,452,231 out=0 elapsed=49.5s

  [1807/20519] intraday_10734.csv.gz  in=194,452,232 out=0 elapsed=49.5s

  [1808/20519] intraday_10736.csv.gz  in=194,452,236 out=0 elapsed=49.5s

  [1809/20519] intraday_10733.csv.gz  in=194,452,242 out=0 elapsed=49.5s

  [1810/20519] intraday_10737.csv.gz  in=194,452,249 out=0 elapsed=49.5s

  [1811/20519] intraday_10735.csv.gz  in=194,452,252 out=0 elapsed=49.5s

  [1812/20519] intraday_10739.csv.gz  in=194,452,253 out=0 elapsed=49.5s

  [1813/20519] intraday_10738.csv.gz  in=194,452,255 out=0 elapsed=49.5s

  [1814/20519] intraday_10740.csv.gz  in=194,452,260 out=0 elapsed=49.5s

  [1815/20519] intraday_10741.csv.gz  in=194,452,263 out=0 elapsed=49.5s

  [1816/20519] intraday_10743.csv.gz  in=194,452,266 out=0 elapsed=49.6s

  [1817/20519] intraday_10742.csv.gz  in=194,452,269 out=0 elapsed=49.6s

  [1818/20519] intraday_10744.csv.gz  in=194,452,271 out=0 elapsed=49.6s

  [1819/20519] intraday_10747.csv.gz  in=194,452,273 out=0 elapsed=49.6s

  [1820/20519] intraday_10746.csv.gz  in=194,452,278 out=0 elapsed=49.6s

  [1821/20519] intraday_10745.csv.gz  in=194,454,534 out=0 elapsed=49.6s

  [1822/20519] intraday_1074.csv.gz  in=194,470,975 out=0 elapsed=49.6s

  [1823/20519] intraday_10748.csv.gz  in=194,470,976 out=0 elapsed=49.6s

  [1824/20519] intraday_10750.csv.gz  in=194,470,978 out=0 elapsed=49.6s

  [1825/20519] intraday_10749.csv.gz  in=194,470,980 out=0 elapsed=49.6s

  [1826/20519] intraday_10752.csv.gz  in=194,470,981 out=0 elapsed=49.6s

  [1827/20519] intraday_10751.csv.gz  in=194,470,984 out=0 elapsed=49.6s

  [1828/20519] intraday_1075.csv.gz  in=194,484,232 out=0 elapsed=49.6s

  [1829/20519] intraday_10755.csv.gz  in=194,484,233 out=0 elapsed=49.6s

  [1830/20519] intraday_10754.csv.gz  in=194,484,234 out=0 elapsed=49.6s

  [1831/20519] intraday_10753.csv.gz  in=194,484,402 out=0 elapsed=49.6s

  [1832/20519] intraday_10759.csv.gz  in=194,484,403 out=0 elapsed=49.6s

  [1833/20519] intraday_10756.csv.gz  in=194,484,405 out=0 elapsed=49.6s

  [1834/20519] intraday_10758.csv.gz  in=194,484,656 out=0 elapsed=49.6s

  [1835/20519] intraday_10757.csv.gz  in=194,484,659 out=0 elapsed=49.6s

  [1836/20519] intraday_10761.csv.gz  in=194,484,662 out=0 elapsed=49.6s

  [1837/20519] intraday_10760.csv.gz  in=194,484,663 out=0 elapsed=49.6s

  [1838/20519] intraday_10762.csv.gz  in=194,484,665 out=0 elapsed=49.6s

  [1839/20519] intraday_10763.csv.gz  in=194,484,666 out=0 elapsed=49.6s

  [1840/20519] intraday_10764.csv.gz  in=194,484,667 out=0 elapsed=49.7s

  [1841/20519] intraday_10765.csv.gz  in=194,484,668 out=0 elapsed=49.7s

  [1842/20519] intraday_10766.csv.gz  in=194,484,669 out=0 elapsed=49.7s

  [1843/20519] intraday_10767.csv.gz  in=194,484,671 out=0 elapsed=49.7s

  [1844/20519] intraday_1076.csv.gz  in=194,499,965 out=0 elapsed=49.7s

  [1845/20519] intraday_10768.csv.gz  in=194,499,985 out=0 elapsed=49.7s

  [1846/20519] intraday_10770.csv.gz  in=194,499,989 out=0 elapsed=49.7s

  [1847/20519] intraday_10769.csv.gz  in=194,503,042 out=0 elapsed=49.7s

  [1848/20519] intraday_10773.csv.gz  in=194,503,043 out=0 elapsed=49.7s

  [1849/20519] intraday_10771.csv.gz  in=194,503,044 out=0 elapsed=49.7s

  [1850/20519] intraday_1077.csv.gz  in=194,516,088 out=0 elapsed=49.7s

  [1851/20519] intraday_10772.csv.gz  in=194,516,089 out=0 elapsed=49.7s

  [1852/20519] intraday_10775.csv.gz  in=194,516,095 out=0 elapsed=49.7s

  [1853/20519] intraday_10778.csv.gz  in=194,516,099 out=0 elapsed=49.7s

  [1854/20519] intraday_10777.csv.gz  in=194,516,100 out=0 elapsed=49.7s

  [1855/20519] intraday_10774.csv.gz  in=194,516,101 out=0 elapsed=49.7s

  [1856/20519] intraday_10776.csv.gz  in=194,516,105 out=0 elapsed=49.7s

  [1857/20519] intraday_10779.csv.gz  in=194,516,107 out=0 elapsed=49.7s

  [1858/20519] intraday_10780.csv.gz  in=194,516,109 out=0 elapsed=49.7s

  [1859/20519] intraday_10781.csv.gz  in=194,516,110 out=0 elapsed=49.7s

  [1860/20519] intraday_10783.csv.gz  in=194,516,111 out=0 elapsed=49.7s

  [1861/20519] intraday_10782.csv.gz  in=194,516,115 out=0 elapsed=49.8s

  [1862/20519] intraday_10784.csv.gz  in=194,516,119 out=0 elapsed=49.8s

  [1863/20519] intraday_1078.csv.gz  in=194,528,841 out=0 elapsed=49.8s

  [1864/20519] intraday_10786.csv.gz  in=194,528,842 out=0 elapsed=49.8s

  [1865/20519] intraday_10785.csv.gz  in=194,528,843 out=0 elapsed=49.8s

  [1866/20519] intraday_10788.csv.gz  in=194,528,850 out=0 elapsed=49.8s

  [1867/20519] intraday_10789.csv.gz  in=194,528,854 out=0 elapsed=49.8s

  [1868/20519] intraday_10787.csv.gz  in=194,528,896 out=0 elapsed=49.8s

  [1869/20519] intraday_10791.csv.gz  in=194,528,901 out=0 elapsed=49.8s

  [1870/20519] intraday_10790.csv.gz  in=194,528,903 out=0 elapsed=49.8s

  [1871/20519] intraday_10793.csv.gz  in=194,528,904 out=0 elapsed=49.8s

  [1872/20519] intraday_10792.csv.gz  in=194,531,104 out=0 elapsed=49.8s

  [1873/20519] intraday_10794.csv.gz  in=194,531,107 out=0 elapsed=49.8s

  [1874/20519] intraday_10795.csv.gz  in=194,531,111 out=0 elapsed=49.8s

  [1875/20519] intraday_10796.csv.gz  in=194,531,112 out=0 elapsed=49.8s

  [1876/20519] intraday_1079.csv.gz  in=194,546,728 out=0 elapsed=49.8s

  [1877/20519] intraday_10797.csv.gz  in=194,546,729 out=0 elapsed=49.8s

  [1878/20519] intraday_10798.csv.gz  in=194,546,731 out=0 elapsed=49.8s

  [1879/20519] intraday_10800.csv.gz  in=194,546,733 out=0 elapsed=49.8s

  [1880/20519] intraday_10799.csv.gz  in=194,546,735 out=0 elapsed=49.8s

  [1881/20519] intraday_10801.csv.gz  in=194,546,737 out=0 elapsed=49.8s

  [1882/20519] intraday_10802.csv.gz  in=194,546,738 out=0 elapsed=49.9s

  [1883/20519] intraday_10803.csv.gz  in=194,546,741 out=0 elapsed=49.9s

  [1884/20519] intraday_10805.csv.gz  in=194,546,744 out=0 elapsed=49.9s

  [1885/20519] intraday_10804.csv.gz  in=194,546,845 out=0 elapsed=49.9s

  [1886/20519] intraday_1080.csv.gz  in=194,559,752 out=0 elapsed=49.9s

  [1887/20519] intraday_10806.csv.gz  in=194,559,755 out=0 elapsed=49.9s

  [1888/20519] intraday_10807.csv.gz  in=194,559,756 out=0 elapsed=49.9s

  [1889/20519] intraday_10808.csv.gz  in=194,559,759 out=0 elapsed=49.9s

  [1890/20519] intraday_10809.csv.gz  in=194,559,760 out=0 elapsed=49.9s

  [1891/20519] intraday_10811.csv.gz  in=194,559,763 out=0 elapsed=50.0s

  [1892/20519] intraday_10813.csv.gz  in=194,559,766 out=0 elapsed=50.0s

  [1893/20519] intraday_1081.csv.gz  in=194,572,972 out=0 elapsed=50.0s

  [1894/20519] intraday_10812.csv.gz  in=194,572,974 out=0 elapsed=50.0s

  [1895/20519] intraday_10810.csv.gz  in=194,579,661 out=0 elapsed=50.0s

  [1896/20519] intraday_10815.csv.gz  in=194,579,664 out=0 elapsed=50.0s

  [1897/20519] intraday_10818.csv.gz  in=194,579,667 out=0 elapsed=50.0s

  [1898/20519] intraday_10816.csv.gz  in=194,583,288 out=0 elapsed=50.0s

  [1899/20519] intraday_10814.csv.gz  in=194,583,600 out=0 elapsed=50.0s

  [1900/20519] intraday_10817.csv.gz  in=194,583,648 out=0 elapsed=50.0s

  [1901/20519] intraday_10819.csv.gz  in=194,583,656 out=0 elapsed=50.0s

  [1902/20519] intraday_10821.csv.gz  in=194,583,657 out=0 elapsed=50.1s

  [1903/20519] intraday_10820.csv.gz  in=194,583,658 out=0 elapsed=50.1s

  [1904/20519] intraday_10824.csv.gz  in=194,583,663 out=0 elapsed=50.1s

  [1905/20519] intraday_10823.csv.gz  in=194,583,666 out=0 elapsed=50.1s

  [1906/20519] intraday_1082.csv.gz  in=194,604,761 out=0 elapsed=50.1s

  [1907/20519] intraday_10825.csv.gz  in=194,604,768 out=0 elapsed=50.1s

  [1908/20519] intraday_10822.csv.gz  in=194,604,868 out=0 elapsed=50.1s

  [1909/20519] intraday_10826.csv.gz  in=194,604,881 out=0 elapsed=50.1s

  [1910/20519] intraday_10827.csv.gz  in=194,604,883 out=0 elapsed=50.1s

  [1911/20519] intraday_10830.csv.gz  in=194,604,890 out=0 elapsed=50.1s

  [1912/20519] intraday_10829.csv.gz  in=194,604,895 out=0 elapsed=50.1s

  [1913/20519] intraday_10828.csv.gz  in=194,604,933 out=0 elapsed=50.1s

  [1914/20519] intraday_10831.csv.gz  in=194,604,939 out=0 elapsed=50.1s

  [1915/20519] intraday_10832.csv.gz  in=194,604,943 out=0 elapsed=50.1s

  [1916/20519] intraday_1083.csv.gz  in=194,618,839 out=0 elapsed=50.1s

  [1917/20519] intraday_10833.csv.gz  in=194,618,847 out=0 elapsed=50.1s

  [1918/20519] intraday_10837.csv.gz  in=194,618,849 out=0 elapsed=50.1s

  [1919/20519] intraday_10836.csv.gz  in=194,618,852 out=0 elapsed=50.1s

  [1920/20519] intraday_10838.csv.gz  in=194,618,856 out=0 elapsed=50.1s

  [1921/20519] intraday_10835.csv.gz  in=194,619,117 out=0 elapsed=50.2s

  [1922/20519] intraday_10840.csv.gz  in=194,619,120 out=0 elapsed=50.2s

  [1923/20519] intraday_10839.csv.gz  in=194,619,153 out=0 elapsed=50.2s

  [1924/20519] intraday_10841.csv.gz  in=194,619,154 out=0 elapsed=50.2s

  [1925/20519] intraday_10842.csv.gz  in=194,619,163 out=0 elapsed=50.2s

  [1926/20519] intraday_10834.csv.gz  in=194,621,708 out=0 elapsed=50.2s

  [1927/20519] intraday_1084.csv.gz  in=194,634,901 out=0 elapsed=50.2s

  [1928/20519] intraday_10844.csv.gz  in=194,635,219 out=0 elapsed=50.2s

  [1929/20519] intraday_10843.csv.gz  in=194,635,221 out=0 elapsed=50.2s

  [1930/20519] intraday_10846.csv.gz  in=194,635,225 out=0 elapsed=50.2s

  [1931/20519] intraday_10845.csv.gz  in=194,635,230 out=0 elapsed=50.2s

  [1932/20519] intraday_10847.csv.gz  in=194,635,234 out=0 elapsed=50.2s

  [1933/20519] intraday_10850.csv.gz  in=194,635,237 out=0 elapsed=50.2s

  [1934/20519] intraday_10848.csv.gz  in=194,635,240 out=0 elapsed=50.2s

  [1935/20519] intraday_10849.csv.gz  in=194,635,243 out=0 elapsed=50.3s

  [1936/20519] intraday_10852.csv.gz  in=194,635,258 out=0 elapsed=50.3s

  [1937/20519] intraday_10851.csv.gz  in=194,635,261 out=0 elapsed=50.3s

  [1938/20519] intraday_1085.csv.gz  in=194,648,434 out=0 elapsed=50.3s

  [1939/20519] intraday_10856.csv.gz  in=194,648,436 out=0 elapsed=50.3s

  [1940/20519] intraday_10854.csv.gz  in=194,648,437 out=0 elapsed=50.3s

  [1941/20519] intraday_10853.csv.gz  in=194,648,441 out=0 elapsed=50.3s

  [1942/20519] intraday_10855.csv.gz  in=194,648,446 out=0 elapsed=50.3s

  [1943/20519] intraday_10858.csv.gz  in=194,648,447 out=0 elapsed=50.3s

  [1944/20519] intraday_10859.csv.gz  in=194,649,106 out=0 elapsed=50.3s

  [1945/20519] intraday_10857.csv.gz  in=194,649,682 out=0 elapsed=50.3s

  [1946/20519] intraday_10860.csv.gz  in=194,649,775 out=0 elapsed=50.3s

  [1947/20519] intraday_10862.csv.gz  in=194,649,790 out=0 elapsed=50.3s

  [1948/20519] intraday_1086.csv.gz  in=194,660,257 out=0 elapsed=50.3s

  [1949/20519] intraday_10861.csv.gz  in=194,660,557 out=0 elapsed=50.3s

  [1950/20519] intraday_10863.csv.gz  in=194,660,575 out=0 elapsed=50.3s

  [1951/20519] intraday_10865.csv.gz  in=194,660,716 out=0 elapsed=50.3s

  [1952/20519] intraday_10864.csv.gz  in=194,661,491 out=0 elapsed=50.3s

  [1953/20519] intraday_10866.csv.gz  in=194,662,583 out=0 elapsed=50.4s

  [1954/20519] intraday_10867.csv.gz  in=194,662,776 out=0 elapsed=50.4s

  [1955/20519] intraday_10868.csv.gz  in=194,665,010 out=0 elapsed=50.4s

  [1956/20519] intraday_10869.csv.gz  in=194,665,424 out=0 elapsed=50.4s

  [1957/20519] intraday_10870.csv.gz  in=194,678,321 out=0 elapsed=50.4s

  [1958/20519] intraday_1087.csv.gz  in=194,691,616 out=0 elapsed=50.4s

  [1959/20519] intraday_10871.csv.gz  in=194,691,858 out=0 elapsed=50.4s

  [1960/20519] intraday_10872.csv.gz  in=194,691,964 out=0 elapsed=50.4s

  [1961/20519] intraday_10874.csv.gz  in=194,692,569 out=0 elapsed=50.4s

  [1962/20519] intraday_10873.csv.gz  in=194,692,644 out=0 elapsed=50.4s

  [1963/20519] intraday_10875.csv.gz  in=194,692,653 out=0 elapsed=50.4s

  [1964/20519] intraday_10877.csv.gz  in=194,692,774 out=0 elapsed=50.4s

  [1965/20519] intraday_10876.csv.gz  in=194,696,469 out=0 elapsed=50.4s

  [1966/20519] intraday_10878.csv.gz  in=194,696,742 out=0 elapsed=50.5s

  [1967/20519] intraday_10879.csv.gz  in=194,696,835 out=0 elapsed=50.5s

  [1968/20519] intraday_10880.csv.gz  in=194,696,879 out=0 elapsed=50.5s

  [1969/20519] intraday_10881.csv.gz  in=194,698,156 out=0 elapsed=50.5s

  [1970/20519] intraday_10882.csv.gz  in=194,701,629 out=0 elapsed=50.5s

  [1971/20519] intraday_1088.csv.gz  in=194,713,834 out=0 elapsed=50.5s

  [1972/20519] intraday_10883.csv.gz  in=194,714,234 out=0 elapsed=50.5s

  [1973/20519] intraday_10884.csv.gz  in=194,714,253 out=0 elapsed=50.5s

  [1974/20519] intraday_10886.csv.gz  in=194,714,266 out=0 elapsed=50.5s

  [1975/20519] intraday_10887.csv.gz  in=194,714,367 out=0 elapsed=50.5s

  [1976/20519] intraday_10885.csv.gz  in=194,714,486 out=0 elapsed=50.5s

  [1977/20519] intraday_10888.csv.gz  in=194,715,047 out=0 elapsed=50.5s

  [1978/20519] intraday_10889.csv.gz  in=194,715,173 out=0 elapsed=50.5s

  [1979/20519] intraday_10890.csv.gz  in=194,715,315 out=0 elapsed=50.5s

  [1980/20519] intraday_1089.csv.gz  in=194,726,199 out=0 elapsed=50.6s

  [1981/20519] intraday_10891.csv.gz  in=194,726,510 out=0 elapsed=50.6s

  [1982/20519] intraday_10892.csv.gz  in=194,726,655 out=0 elapsed=50.6s

  [1983/20519] intraday_10893.csv.gz  in=194,726,791 out=0 elapsed=50.6s

  [1984/20519] intraday_10895.csv.gz  in=194,727,055 out=0 elapsed=50.6s

  [1985/20519] intraday_10894.csv.gz  in=194,727,146 out=0 elapsed=50.6s

  [1986/20519] intraday_10896.csv.gz  in=194,727,172 out=0 elapsed=50.6s

  [1987/20519] intraday_10897.csv.gz  in=194,727,316 out=0 elapsed=50.6s

  [1988/20519] intraday_10899.csv.gz  in=194,727,619 out=0 elapsed=50.6s

  [1989/20519] intraday_10898.csv.gz  in=194,729,450 out=0 elapsed=50.6s

  [1990/20519] intraday_1090.csv.gz  in=194,737,255 out=0 elapsed=50.6s

  [1991/20519] intraday_10900.csv.gz  in=194,737,289 out=0 elapsed=50.6s

  [1992/20519] intraday_10904.csv.gz  in=194,737,291 out=0 elapsed=50.6s

  [1993/20519] intraday_10903.csv.gz  in=194,737,303 out=0 elapsed=50.6s

  [1994/20519] intraday_10901.csv.gz  in=194,738,169 out=0 elapsed=50.6s

  [1995/20519] intraday_10902.csv.gz  in=194,738,199 out=0 elapsed=50.7s

  [1996/20519] intraday_10906.csv.gz  in=194,738,377 out=0 elapsed=50.7s

  [1997/20519] intraday_10905.csv.gz  in=194,738,386 out=0 elapsed=50.7s

  [1998/20519] intraday_10907.csv.gz  in=194,739,088 out=0 elapsed=50.7s

  [1999/20519] intraday_10909.csv.gz  in=194,739,097 out=0 elapsed=50.7s

  [2000/20519] intraday_10908.csv.gz  in=194,741,278 out=0 elapsed=50.7s

  [2001/20519] intraday_10910.csv.gz  in=194,741,333 out=0 elapsed=50.7s

  [2002/20519] intraday_1091.csv.gz  in=194,753,787 out=0 elapsed=50.7s

  [2003/20519] intraday_10912.csv.gz  in=194,765,449 out=11,662 elapsed=50.7s

  [2004/20519] intraday_10911.csv.gz  in=194,781,414 out=27,627 elapsed=50.7s

  [2005/20519] intraday_10914.csv.gz  in=194,791,616 out=37,829 elapsed=50.7s

  [2006/20519] intraday_10913.csv.gz  in=194,805,461 out=51,674 elapsed=50.7s

  [2007/20519] intraday_10915.csv.gz  in=194,817,387 out=63,600 elapsed=50.7s

  [2008/20519] intraday_10917.csv.gz  in=194,831,905 out=78,118 elapsed=50.8s

  [2009/20519] intraday_10916.csv.gz  in=194,845,796 out=91,758 elapsed=50.8s

  [2010/20519] intraday_10918.csv.gz  in=194,856,895 out=102,857 elapsed=50.8s

  [2011/20519] intraday_10919.csv.gz  in=194,867,997 out=113,959 elapsed=50.8s

  [2012/20519] intraday_10921.csv.gz  in=194,880,923 out=126,885 elapsed=50.8s

  [2013/20519] intraday_1092.csv.gz  in=194,887,234 out=126,885 elapsed=50.9s

  [2014/20519] intraday_10920.csv.gz  in=194,900,705 out=140,356 elapsed=50.9s

  [2015/20519] intraday_10922.csv.gz  in=194,911,528 out=151,179 elapsed=50.9s

  [2016/20519] intraday_10923.csv.gz  in=194,924,696 out=164,347 elapsed=50.9s

  [2017/20519] intraday_10926.csv.gz  in=194,934,846 out=174,497 elapsed=50.9s

  [2018/20519] intraday_10925.csv.gz  in=194,944,086 out=183,737 elapsed=50.9s

  [2019/20519] intraday_10924.csv.gz  in=194,959,164 out=198,815 elapsed=51.0s

  [2020/20519] intraday_10927.csv.gz  in=194,973,460 out=213,111 elapsed=51.0s

  [2021/20519] intraday_10928.csv.gz  in=194,987,891 out=227,542 elapsed=51.0s

  [2022/20519] intraday_10929.csv.gz  in=195,000,206 out=239,857 elapsed=51.0s

  [2023/20519] intraday_1093.csv.gz  in=195,015,075 out=239,857 elapsed=51.0s

  [2024/20519] intraday_10931.csv.gz  in=195,026,395 out=251,177 elapsed=51.0s

  [2025/20519] intraday_10932.csv.gz  in=195,043,041 out=263,990 elapsed=51.0s

  [2026/20519] intraday_10933.csv.gz  in=195,054,508 out=275,457 elapsed=51.1s

  [2027/20519] intraday_10930.csv.gz  in=195,064,852 out=285,801 elapsed=51.1s

  [2028/20519] intraday_10934.csv.gz  in=195,077,482 out=298,431 elapsed=51.1s

  [2029/20519] intraday_10936.csv.gz  in=195,088,143 out=309,092 elapsed=51.1s

  [2030/20519] intraday_10935.csv.gz  in=195,100,659 out=321,608 elapsed=51.1s

  [2031/20519] intraday_10937.csv.gz  in=195,123,385 out=334,524 elapsed=51.1s

  [2032/20519] intraday_10938.csv.gz  in=195,134,143 out=345,282 elapsed=51.1s

  [2033/20519] intraday_10939.csv.gz  in=195,144,607 out=355,746 elapsed=51.2s

  [2034/20519] intraday_1094.csv.gz  in=195,159,395 out=355,746 elapsed=51.2s

  [2035/20519] intraday_10940.csv.gz  in=195,172,591 out=368,942 elapsed=51.2s

  [2036/20519] intraday_10941.csv.gz  in=195,187,708 out=384,059 elapsed=51.2s

  [2037/20519] intraday_10943.csv.gz  in=195,196,894 out=393,124 elapsed=51.2s

  [2038/20519] intraday_10942.csv.gz  in=195,210,527 out=406,757 elapsed=51.2s

  [2039/20519] intraday_10944.csv.gz  in=195,221,468 out=417,698 elapsed=51.2s

  [2040/20519] intraday_10946.csv.gz  in=195,232,409 out=428,621 elapsed=51.3s

  [2041/20519] intraday_10945.csv.gz  in=195,246,024 out=442,236 elapsed=51.3s

  [2042/20519] intraday_10947.csv.gz  in=195,256,968 out=453,180 elapsed=51.3s

  [2043/20519] intraday_10948.csv.gz  in=195,268,883 out=465,095 elapsed=51.3s

  [2044/20519] intraday_10949.csv.gz  in=195,279,383 out=475,595 elapsed=51.3s

  [2045/20519] intraday_1095.csv.gz  in=195,291,322 out=475,595 elapsed=51.3s

  [2046/20519] intraday_10950.csv.gz  in=195,301,260 out=485,533 elapsed=51.3s

  [2047/20519] intraday_10953.csv.gz  in=195,314,521 out=498,794 elapsed=51.3s

  [2048/20519] intraday_10951.csv.gz  in=195,324,412 out=508,685 elapsed=51.4s

  [2049/20519] intraday_10952.csv.gz  in=195,335,037 out=519,310 elapsed=51.4s

  [2050/20519] intraday_10954.csv.gz  in=195,347,281 out=531,554 elapsed=51.4s

  [2051/20519] intraday_10955.csv.gz  in=195,361,557 out=545,830 elapsed=51.4s

  [2052/20519] intraday_10956.csv.gz  in=195,372,863 out=557,136 elapsed=51.4s

  [2053/20519] intraday_10957.csv.gz  in=195,383,173 out=567,446 elapsed=51.4s

  [2054/20519] intraday_10958.csv.gz  in=195,394,892 out=579,165 elapsed=51.4s

  [2055/20519] intraday_1096.csv.gz  in=195,406,466 out=579,165 elapsed=51.4s

  [2056/20519] intraday_10959.csv.gz  in=195,417,949 out=590,648 elapsed=51.4s

  [2057/20519] intraday_10960.csv.gz  in=195,427,571 out=600,270 elapsed=51.5s

  [2058/20519] intraday_10962.csv.gz  in=195,437,976 out=610,675 elapsed=51.5s

  [2059/20519] intraday_10963.csv.gz  in=195,449,622 out=622,321 elapsed=51.5s

  [2060/20519] intraday_10961.csv.gz  in=195,460,919 out=633,618 elapsed=51.5s

  [2061/20519] intraday_10964.csv.gz  in=195,472,037 out=644,736 elapsed=51.5s

  [2062/20519] intraday_10966.csv.gz  in=195,485,117 out=657,816 elapsed=51.6s

  [2063/20519] intraday_10965.csv.gz  in=195,498,683 out=671,382 elapsed=51.6s

  [2064/20519] intraday_10967.csv.gz  in=195,512,098 out=684,797 elapsed=51.6s

  [2065/20519] intraday_10969.csv.gz  in=195,521,625 out=694,324 elapsed=51.6s

  [2066/20519] intraday_10968.csv.gz  in=195,549,112 out=706,889 elapsed=51.6s

  [2067/20519] intraday_1097.csv.gz  in=195,564,167 out=706,889 elapsed=51.6s

  [2068/20519] intraday_10972.csv.gz  in=195,574,267 out=716,989 elapsed=51.6s

  [2069/20519] intraday_10971.csv.gz  in=195,586,947 out=729,669 elapsed=51.6s

  [2070/20519] intraday_10973.csv.gz  in=195,600,003 out=742,725 elapsed=51.7s

  [2071/20519] intraday_10970.csv.gz  in=195,612,234 out=754,956 elapsed=51.7s

  [2072/20519] intraday_10974.csv.gz  in=195,623,176 out=765,898 elapsed=51.7s

  [2073/20519] intraday_10975.csv.gz  in=195,633,783 out=776,505 elapsed=51.7s

  [2074/20519] intraday_10976.csv.gz  in=195,644,289 out=787,011 elapsed=51.7s

  [2075/20519] intraday_10978.csv.gz  in=195,660,866 out=803,588 elapsed=51.7s

  [2076/20519] intraday_10977.csv.gz  in=195,675,587 out=818,309 elapsed=51.8s

  [2077/20519] intraday_1098.csv.gz  in=195,690,131 out=818,309 elapsed=51.8s

  [2078/20519] intraday_10979.csv.gz  in=195,703,243 out=831,421 elapsed=51.8s

  [2079/20519] intraday_10980.csv.gz  in=195,715,464 out=843,642 elapsed=51.8s

  [2080/20519] intraday_10982.csv.gz  in=195,726,563 out=854,741 elapsed=51.8s

  [2081/20519] intraday_10981.csv.gz  in=195,738,435 out=866,613 elapsed=51.8s

  [2082/20519] intraday_10983.csv.gz  in=195,750,840 out=879,018 elapsed=51.8s

  [2083/20519] intraday_10985.csv.gz  in=195,763,224 out=891,402 elapsed=51.9s

  [2084/20519] intraday_10984.csv.gz  in=195,778,235 out=906,413 elapsed=51.9s

  [2085/20519] intraday_10987.csv.gz  in=195,791,041 out=919,219 elapsed=51.9s

  [2086/20519] intraday_10988.csv.gz  in=195,801,558 out=929,736 elapsed=51.9s

  [2087/20519] intraday_10986.csv.gz  in=195,812,223 out=940,355 elapsed=51.9s

  [2088/20519] intraday_10989.csv.gz  in=195,825,462 out=953,594 elapsed=51.9s

  [2089/20519] intraday_1099.csv.gz  in=195,837,318 out=953,594 elapsed=51.9s

  [2090/20519] intraday_10991.csv.gz  in=195,849,419 out=965,695 elapsed=52.0s

  [2091/20519] intraday_10992.csv.gz  in=195,866,313 out=973,921 elapsed=52.0s

  [2092/20519] intraday_10990.csv.gz  in=195,876,431 out=984,039 elapsed=52.0s

  [2093/20519] intraday_10993.csv.gz  in=195,885,108 out=992,716 elapsed=52.0s

  [2094/20519] intraday_10994.csv.gz  in=195,896,714 out=1,004,322 elapsed=52.0s

  [2095/20519] intraday_10996.csv.gz  in=195,918,828 out=1,026,436 elapsed=52.0s

  [2096/20519] intraday_10997.csv.gz  in=195,930,080 out=1,037,688 elapsed=52.1s

  [2097/20519] intraday_10995.csv.gz  in=195,943,151 out=1,050,759 elapsed=52.1s

  [2098/20519] intraday_10998.csv.gz  in=195,954,810 out=1,062,418 elapsed=52.1s

  [2099/20519] intraday_11001.csv.gz  in=195,965,685 out=1,073,293 elapsed=52.1s

  [2100/20519] intraday_1100.csv.gz  in=195,978,365 out=1,073,293 elapsed=52.1s

  [2101/20519] intraday_11000.csv.gz  in=195,991,945 out=1,086,873 elapsed=52.1s

  [2102/20519] intraday_10999.csv.gz  in=196,008,015 out=1,099,166 elapsed=52.1s

  [2103/20519] intraday_11003.csv.gz  in=196,019,187 out=1,110,338 elapsed=52.1s

  [2104/20519] intraday_11002.csv.gz  in=196,035,121 out=1,126,272 elapsed=52.1s

  [2105/20519] intraday_11005.csv.gz  in=196,047,874 out=1,139,025 elapsed=52.2s

  [2106/20519] intraday_11004.csv.gz  in=196,073,692 out=1,150,721 elapsed=52.2s

  [2107/20519] intraday_11007.csv.gz  in=196,086,615 out=1,163,644 elapsed=52.2s

  [2108/20519] intraday_11006.csv.gz  in=196,099,930 out=1,176,959 elapsed=52.2s

  [2109/20519] intraday_11008.csv.gz  in=196,111,150 out=1,188,179 elapsed=52.2s

  [2110/20519] intraday_11009.csv.gz  in=196,124,476 out=1,201,505 elapsed=52.2s

  [2111/20519] intraday_1101.csv.gz  in=196,138,657 out=1,201,505 elapsed=52.2s

  [2112/20519] intraday_11011.csv.gz  in=196,150,815 out=1,213,663 elapsed=52.3s

  [2113/20519] intraday_11010.csv.gz  in=196,162,485 out=1,225,333 elapsed=52.3s

  [2114/20519] intraday_11012.csv.gz  in=196,174,603 out=1,237,451 elapsed=52.3s

  [2115/20519] intraday_11013.csv.gz  in=196,185,727 out=1,248,575 elapsed=52.3s

  [2116/20519] intraday_11015.csv.gz  in=196,200,153 out=1,263,001 elapsed=52.3s

  [2117/20519] intraday_11016.csv.gz  in=196,212,488 out=1,275,336 elapsed=52.3s

  [2118/20519] intraday_11017.csv.gz  in=196,224,254 out=1,287,102 elapsed=52.3s

  [2119/20519] intraday_11014.csv.gz  in=196,236,357 out=1,299,205 elapsed=52.3s

  [2120/20519] intraday_11018.csv.gz  in=196,248,776 out=1,311,624 elapsed=52.4s

  [2121/20519] intraday_11019.csv.gz  in=196,262,463 out=1,325,311 elapsed=52.4s

  [2122/20519] intraday_1102.csv.gz  in=196,277,312 out=1,325,311 elapsed=52.4s

  [2123/20519] intraday_11020.csv.gz  in=196,289,202 out=1,337,201 elapsed=52.4s

  [2124/20519] intraday_11021.csv.gz  in=196,302,566 out=1,350,565 elapsed=52.4s

  [2125/20519] intraday_11022.csv.gz  in=196,313,213 out=1,361,212 elapsed=52.4s

  [2126/20519] intraday_11023.csv.gz  in=196,326,766 out=1,374,765 elapsed=52.4s

  [2127/20519] intraday_11024.csv.gz  in=196,338,716 out=1,386,715 elapsed=52.4s

  [2128/20519] intraday_11025.csv.gz  in=196,352,312 out=1,400,285 elapsed=52.4s

  [2129/20519] intraday_11026.csv.gz  in=196,373,880 out=1,418,743 elapsed=52.5s

  [2130/20519] intraday_11028.csv.gz  in=196,389,624 out=1,434,487 elapsed=52.5s

  [2131/20519] intraday_11029.csv.gz  in=196,404,872 out=1,449,735 elapsed=52.5s

  [2132/20519] intraday_1103.csv.gz  in=196,415,594 out=1,449,735 elapsed=52.5s

  [2133/20519] intraday_11027.csv.gz  in=196,431,363 out=1,465,504 elapsed=52.5s

  [2134/20519] intraday_11030.csv.gz  in=196,447,942 out=1,482,083 elapsed=52.5s

  [2135/20519] intraday_11031.csv.gz  in=196,465,034 out=1,499,175 elapsed=52.6s

  [2136/20519] intraday_11033.csv.gz  in=196,477,063 out=1,511,204 elapsed=52.6s

  [2137/20519] intraday_11032.csv.gz  in=196,490,462 out=1,524,603 elapsed=52.6s

  [2138/20519] intraday_11034.csv.gz  in=196,501,582 out=1,535,723 elapsed=52.6s

  [2139/20519] intraday_11035.csv.gz  in=196,511,987 out=1,546,128 elapsed=52.6s

  [2140/20519] intraday_11037.csv.gz  in=196,522,678 out=1,556,819 elapsed=52.6s

  [2141/20519] intraday_11038.csv.gz  in=196,535,668 out=1,569,809 elapsed=52.6s

  [2142/20519] intraday_11036.csv.gz  in=196,549,084 out=1,583,225 elapsed=52.6s

  [2143/20519] intraday_11039.csv.gz  in=196,562,519 out=1,596,660 elapsed=52.6s

  [2144/20519] intraday_1104.csv.gz  in=196,575,204 out=1,596,660 elapsed=52.7s

  [2145/20519] intraday_11041.csv.gz  in=196,585,432 out=1,606,888 elapsed=52.7s

  [2146/20519] intraday_11040.csv.gz  in=196,602,081 out=1,623,537 elapsed=52.7s

  [2147/20519] intraday_11042.csv.gz  in=196,612,316 out=1,633,772 elapsed=52.7s

  [2148/20519] intraday_11043.csv.gz  in=196,625,020 out=1,646,476 elapsed=52.7s

  [2149/20519] intraday_11044.csv.gz  in=196,636,694 out=1,658,150 elapsed=52.7s

  [2150/20519] intraday_11045.csv.gz  in=196,648,038 out=1,669,494 elapsed=52.7s

  [2151/20519] intraday_11048.csv.gz  in=196,661,623 out=1,683,079 elapsed=52.8s

  [2152/20519] intraday_11046.csv.gz  in=196,677,578 out=1,699,034 elapsed=52.8s

  [2153/20519] intraday_11047.csv.gz  in=196,693,462 out=1,714,918 elapsed=52.8s

  [2154/20519] intraday_11049.csv.gz  in=196,708,220 out=1,729,676 elapsed=52.8s

  [2155/20519] intraday_1105.csv.gz  in=196,723,537 out=1,729,676 elapsed=52.8s

  [2156/20519] intraday_11050.csv.gz  in=196,734,744 out=1,740,883 elapsed=52.8s

  [2157/20519] intraday_11051.csv.gz  in=196,746,548 out=1,752,687 elapsed=52.8s

  [2158/20519] intraday_11052.csv.gz  in=196,758,661 out=1,764,800 elapsed=52.9s

  [2159/20519] intraday_11053.csv.gz  in=196,771,048 out=1,777,187 elapsed=52.9s

  [2160/20519] intraday_11055.csv.gz  in=196,777,254 out=1,783,392 elapsed=52.9s

  [2161/20519] intraday_11054.csv.gz  in=196,787,001 out=1,793,086 elapsed=52.9s

  [2162/20519] intraday_11056.csv.gz  in=196,797,593 out=1,803,678 elapsed=52.9s

  [2163/20519] intraday_11057.csv.gz  in=196,803,809 out=1,809,894 elapsed=52.9s

  [2164/20519] intraday_11058.csv.gz  in=196,817,842 out=1,823,927 elapsed=52.9s

  [2165/20519] intraday_1106.csv.gz  in=196,829,220 out=1,823,927 elapsed=52.9s

  [2166/20519] intraday_11059.csv.gz  in=196,840,242 out=1,834,949 elapsed=52.9s

  [2167/20519] intraday_11060.csv.gz  in=196,854,438 out=1,849,145 elapsed=53.0s

  [2168/20519] intraday_11061.csv.gz  in=196,864,775 out=1,859,482 elapsed=53.0s

  [2169/20519] intraday_11063.csv.gz  in=196,877,408 out=1,872,115 elapsed=53.0s

  [2170/20519] intraday_11062.csv.gz  in=196,889,235 out=1,883,923 elapsed=53.0s

  [2171/20519] intraday_11064.csv.gz  in=196,902,658 out=1,897,346 elapsed=53.0s

  [2172/20519] intraday_11065.csv.gz  in=196,913,071 out=1,907,759 elapsed=53.0s

  [2173/20519] intraday_11066.csv.gz  in=196,924,369 out=1,919,057 elapsed=53.0s

  [2174/20519] intraday_11067.csv.gz  in=196,937,330 out=1,932,018 elapsed=53.0s

  [2175/20519] intraday_11068.csv.gz  in=196,949,839 out=1,944,527 elapsed=53.1s

  [2176/20519] intraday_1107.csv.gz  in=196,960,003 out=1,944,527 elapsed=53.1s

  [2177/20519] intraday_11069.csv.gz  in=196,970,341 out=1,954,865 elapsed=53.1s

  [2178/20519] intraday_11070.csv.gz  in=196,982,600 out=1,967,124 elapsed=53.1s

  [2179/20519] intraday_11072.csv.gz  in=196,993,109 out=1,977,633 elapsed=53.1s

  [2180/20519] intraday_11071.csv.gz  in=197,005,821 out=1,990,345 elapsed=53.2s

  [2181/20519] intraday_11073.csv.gz  in=197,016,252 out=2,000,776 elapsed=53.2s

  [2182/20519] intraday_11074.csv.gz  in=197,029,453 out=2,013,977 elapsed=53.2s

  [2183/20519] intraday_11075.csv.gz  in=197,041,762 out=2,026,286 elapsed=53.2s

  [2184/20519] intraday_11076.csv.gz  in=197,053,930 out=2,038,454 elapsed=53.2s

  [2185/20519] intraday_11077.csv.gz  in=197,063,688 out=2,048,212 elapsed=53.2s

  [2186/20519] intraday_11078.csv.gz  in=197,075,025 out=2,059,549 elapsed=53.3s

  [2187/20519] intraday_1108.csv.gz  in=197,088,079 out=2,059,549 elapsed=53.3s

  [2188/20519] intraday_11079.csv.gz  in=197,099,154 out=2,070,624 elapsed=53.3s

  [2189/20519] intraday_11080.csv.gz  in=197,111,362 out=2,082,832 elapsed=53.3s

  [2190/20519] intraday_11081.csv.gz  in=197,123,160 out=2,094,630 elapsed=53.3s

  [2191/20519] intraday_11082.csv.gz  in=197,136,111 out=2,107,581 elapsed=53.3s

  [2192/20519] intraday_11083.csv.gz  in=197,147,180 out=2,118,650 elapsed=53.3s

  [2193/20519] intraday_11084.csv.gz  in=197,160,403 out=2,130,662 elapsed=53.3s

  [2194/20519] intraday_11085.csv.gz  in=197,171,120 out=2,141,379 elapsed=53.4s

  [2195/20519] intraday_11086.csv.gz  in=197,181,362 out=2,151,621 elapsed=53.4s

  [2196/20519] intraday_11087.csv.gz  in=197,194,662 out=2,164,921 elapsed=53.4s

  [2197/20519] intraday_11088.csv.gz  in=197,209,464 out=2,179,723 elapsed=53.4s

  [2198/20519] intraday_1109.csv.gz  in=197,222,115 out=2,179,723 elapsed=53.4s

  [2199/20519] intraday_11090.csv.gz  in=197,231,444 out=2,189,052 elapsed=53.4s

  [2200/20519] intraday_11089.csv.gz  in=197,244,830 out=2,202,438 elapsed=53.4s

  [2201/20519] intraday_11091.csv.gz  in=197,254,308 out=2,211,916 elapsed=53.4s

  [2202/20519] intraday_11092.csv.gz  in=197,266,001 out=2,223,609 elapsed=53.5s

  [2203/20519] intraday_11094.csv.gz  in=197,276,168 out=2,233,776 elapsed=53.5s

  [2204/20519] intraday_11093.csv.gz  in=197,289,094 out=2,246,702 elapsed=53.5s

  [2205/20519] intraday_11096.csv.gz  in=197,300,241 out=2,257,849 elapsed=53.5s

  [2206/20519] intraday_11095.csv.gz  in=197,311,358 out=2,268,940 elapsed=53.5s

  [2207/20519] intraday_11098.csv.gz  in=197,321,349 out=2,278,931 elapsed=53.5s

  [2208/20519] intraday_11097.csv.gz  in=197,330,194 out=2,287,776 elapsed=53.6s

  [2209/20519] intraday_11099.csv.gz  in=197,340,712 out=2,298,294 elapsed=53.6s

  [2210/20519] intraday_1110.csv.gz  in=197,360,522 out=2,298,294 elapsed=53.6s

  [2211/20519] intraday_11100.csv.gz  in=197,373,711 out=2,311,483 elapsed=53.6s

  [2212/20519] intraday_11102.csv.gz  in=197,386,487 out=2,324,259 elapsed=53.6s

  [2213/20519] intraday_11101.csv.gz  in=197,399,364 out=2,335,227 elapsed=53.6s

  [2214/20519] intraday_11104.csv.gz  in=197,409,426 out=2,345,289 elapsed=53.6s

  [2215/20519] intraday_11103.csv.gz  in=197,421,528 out=2,357,391 elapsed=53.6s

  [2216/20519] intraday_11105.csv.gz  in=197,432,861 out=2,368,724 elapsed=53.7s

  [2217/20519] intraday_11106.csv.gz  in=197,445,117 out=2,380,980 elapsed=53.7s

  [2218/20519] intraday_11107.csv.gz  in=197,453,322 out=2,389,185 elapsed=53.7s

  [2219/20519] intraday_11109.csv.gz  in=197,463,931 out=2,399,794 elapsed=53.7s

  [2220/20519] intraday_1111.csv.gz  in=197,475,581 out=2,399,794 elapsed=53.7s

  [2221/20519] intraday_11108.csv.gz  in=197,487,097 out=2,411,310 elapsed=53.7s

  [2222/20519] intraday_11110.csv.gz  in=197,497,797 out=2,422,010 elapsed=53.7s

  [2223/20519] intraday_11111.csv.gz  in=197,509,990 out=2,434,203 elapsed=53.8s

  [2224/20519] intraday_11113.csv.gz  in=197,521,839 out=2,446,052 elapsed=53.8s

  [2225/20519] intraday_11112.csv.gz  in=197,534,155 out=2,458,368 elapsed=53.8s

  [2226/20519] intraday_11114.csv.gz  in=197,546,246 out=2,470,459 elapsed=53.8s

  [2227/20519] intraday_11115.csv.gz  in=197,558,988 out=2,483,201 elapsed=53.8s

  [2228/20519] intraday_11116.csv.gz  in=197,568,137 out=2,492,350 elapsed=53.8s

  [2229/20519] intraday_11118.csv.gz  in=197,579,765 out=2,503,978 elapsed=53.8s

  [2230/20519] intraday_11117.csv.gz  in=197,592,777 out=2,516,990 elapsed=53.9s

  [2231/20519] intraday_1112.csv.gz  in=197,603,991 out=2,516,990 elapsed=53.9s

  [2232/20519] intraday_11120.csv.gz  in=197,615,909 out=2,528,908 elapsed=53.9s

  [2233/20519] intraday_11119.csv.gz  in=197,626,390 out=2,539,389 elapsed=53.9s

  [2234/20519] intraday_11121.csv.gz  in=197,636,720 out=2,549,719 elapsed=53.9s

  [2235/20519] intraday_11122.csv.gz  in=197,646,271 out=2,559,270 elapsed=53.9s

  [2236/20519] intraday_11123.csv.gz  in=197,657,164 out=2,570,163 elapsed=54.0s

  [2237/20519] intraday_11125.csv.gz  in=197,669,814 out=2,582,813 elapsed=54.0s

  [2238/20519] intraday_11126.csv.gz  in=197,682,923 out=2,595,922 elapsed=54.0s

  [2239/20519] intraday_11127.csv.gz  in=197,694,377 out=2,607,376 elapsed=54.1s

  [2240/20519] intraday_11124.csv.gz  in=197,710,324 out=2,623,323 elapsed=54.1s

  [2241/20519] intraday_11128.csv.gz  in=197,721,748 out=2,634,747 elapsed=54.1s

  [2242/20519] intraday_11130.csv.gz  in=197,733,238 out=2,646,237 elapsed=54.1s

  [2243/20519] intraday_11129.csv.gz  in=197,744,328 out=2,657,327 elapsed=54.1s

  [2244/20519] intraday_1113.csv.gz  in=197,761,905 out=2,657,327 elapsed=54.1s

  [2245/20519] intraday_11131.csv.gz  in=197,774,871 out=2,670,293 elapsed=54.1s

  [2246/20519] intraday_11132.csv.gz  in=197,787,665 out=2,683,087 elapsed=54.2s

  [2247/20519] intraday_11133.csv.gz  in=197,798,214 out=2,693,636 elapsed=54.2s

  [2248/20519] intraday_11134.csv.gz  in=197,808,137 out=2,703,466 elapsed=54.2s

  [2249/20519] intraday_11135.csv.gz  in=197,819,243 out=2,714,572 elapsed=54.2s

  [2250/20519] intraday_11137.csv.gz  in=197,829,083 out=2,724,412 elapsed=54.2s

  [2251/20519] intraday_11136.csv.gz  in=197,842,332 out=2,737,661 elapsed=54.2s

  [2252/20519] intraday_11138.csv.gz  in=197,852,516 out=2,747,845 elapsed=54.2s

  [2253/20519] intraday_11139.csv.gz  in=197,860,994 out=2,756,323 elapsed=54.3s

  [2254/20519] intraday_1114.csv.gz  in=197,873,909 out=2,756,323 elapsed=54.3s

  [2255/20519] intraday_11140.csv.gz  in=197,883,166 out=2,765,580 elapsed=54.3s

  [2256/20519] intraday_11141.csv.gz  in=197,895,164 out=2,777,578 elapsed=54.3s

  [2257/20519] intraday_11144.csv.gz  in=197,907,321 out=2,789,735 elapsed=54.3s

  [2258/20519] intraday_11143.csv.gz  in=197,923,576 out=2,805,990 elapsed=54.4s

  [2259/20519] intraday_11142.csv.gz  in=197,938,141 out=2,820,555 elapsed=54.4s

  [2260/20519] intraday_11145.csv.gz  in=197,948,814 out=2,831,228 elapsed=54.4s

  [2261/20519] intraday_11146.csv.gz  in=197,960,120 out=2,842,534 elapsed=54.4s

  [2262/20519] intraday_11148.csv.gz  in=197,971,195 out=2,853,609 elapsed=54.4s

  [2263/20519] intraday_1115.csv.gz  in=197,984,149 out=2,853,609 elapsed=54.4s

  [2264/20519] intraday_11149.csv.gz  in=197,997,794 out=2,867,254 elapsed=54.4s

  [2265/20519] intraday_11150.csv.gz  in=198,008,500 out=2,877,960 elapsed=54.4s

  [2266/20519] intraday_11147.csv.gz  in=198,021,333 out=2,890,793 elapsed=54.4s

  [2267/20519] intraday_11153.csv.gz  in=198,033,465 out=2,902,897 elapsed=54.5s

  [2268/20519] intraday_11152.csv.gz  in=198,045,398 out=2,914,830 elapsed=54.5s

  [2269/20519] intraday_11154.csv.gz  in=198,058,029 out=2,927,461 elapsed=54.5s

  [2270/20519] intraday_11151.csv.gz  in=198,071,729 out=2,941,161 elapsed=54.5s

  [2271/20519] intraday_11156.csv.gz  in=198,084,723 out=2,954,155 elapsed=54.5s

  [2272/20519] intraday_11155.csv.gz  in=198,095,464 out=2,964,896 elapsed=54.5s

  [2273/20519] intraday_11157.csv.gz  in=198,105,741 out=2,975,173 elapsed=54.5s

  [2274/20519] intraday_11158.csv.gz  in=198,117,291 out=2,986,723 elapsed=54.6s

  [2275/20519] intraday_1116.csv.gz  in=198,130,266 out=2,986,723 elapsed=54.6s

  [2276/20519] intraday_11159.csv.gz  in=198,140,433 out=2,996,890 elapsed=54.6s

  [2277/20519] intraday_11160.csv.gz  in=198,152,310 out=3,008,767 elapsed=54.6s

  [2278/20519] intraday_11161.csv.gz  in=198,164,691 out=3,021,148 elapsed=54.6s

  [2279/20519] intraday_11162.csv.gz  in=198,177,083 out=3,033,540 elapsed=54.6s

  [2280/20519] intraday_11163.csv.gz  in=198,187,407 out=3,043,864 elapsed=54.6s

  [2281/20519] intraday_11164.csv.gz  in=198,200,380 out=3,056,837 elapsed=54.7s

  [2282/20519] intraday_11165.csv.gz  in=198,212,260 out=3,068,717 elapsed=54.7s

  [2283/20519] intraday_11166.csv.gz  in=198,225,196 out=3,081,653 elapsed=54.7s

  [2284/20519] intraday_11167.csv.gz  in=198,236,558 out=3,093,015 elapsed=54.7s

  [2285/20519] intraday_11168.csv.gz  in=198,248,886 out=3,105,343 elapsed=54.7s

  [2286/20519] intraday_11169.csv.gz  in=198,262,226 out=3,118,683 elapsed=54.7s

  [2287/20519] intraday_1117.csv.gz  in=198,274,251 out=3,118,683 elapsed=54.7s

  [2288/20519] intraday_11171.csv.gz  in=198,284,341 out=3,128,773 elapsed=54.7s

  [2289/20519] intraday_11172.csv.gz  in=198,297,306 out=3,141,738 elapsed=54.7s

  [2290/20519] intraday_11170.csv.gz  in=198,308,883 out=3,153,315 elapsed=54.8s

  [2291/20519] intraday_11173.csv.gz  in=198,326,343 out=3,170,775 elapsed=54.8s

  [2292/20519] intraday_11174.csv.gz  in=198,340,661 out=3,185,093 elapsed=54.8s

  [2293/20519] intraday_11175.csv.gz  in=198,354,758 out=3,199,190 elapsed=54.8s

  [2294/20519] intraday_11176.csv.gz  in=198,370,655 out=3,215,087 elapsed=54.8s

  [2295/20519] intraday_11178.csv.gz  in=198,384,579 out=3,229,011 elapsed=54.8s

  [2296/20519] intraday_11177.csv.gz  in=198,397,259 out=3,241,691 elapsed=54.8s

  [2297/20519] intraday_11179.csv.gz  in=198,409,613 out=3,254,045 elapsed=54.8s

  [2298/20519] intraday_1118.csv.gz  in=198,420,182 out=3,254,045 elapsed=54.8s

  [2299/20519] intraday_11182.csv.gz  in=198,431,366 out=3,265,229 elapsed=54.9s

  [2300/20519] intraday_11181.csv.gz  in=198,442,156 out=3,276,019 elapsed=54.9s

  [2301/20519] intraday_11180.csv.gz  in=198,454,224 out=3,288,087 elapsed=54.9s

  [2302/20519] intraday_11183.csv.gz  in=198,465,084 out=3,298,947 elapsed=54.9s

  [2303/20519] intraday_11185.csv.gz  in=198,476,626 out=3,310,489 elapsed=54.9s

  [2304/20519] intraday_11186.csv.gz  in=198,490,797 out=3,324,660 elapsed=55.0s

  [2305/20519] intraday_11184.csv.gz  in=198,502,953 out=3,336,816 elapsed=55.0s

  [2306/20519] intraday_11187.csv.gz  in=198,513,328 out=3,347,191 elapsed=55.0s

  [2307/20519] intraday_11188.csv.gz  in=198,523,867 out=3,357,730 elapsed=55.0s

  [2308/20519] intraday_1119.csv.gz  in=198,537,464 out=3,357,730 elapsed=55.0s

  [2309/20519] intraday_11189.csv.gz  in=198,548,301 out=3,368,567 elapsed=55.0s

  [2310/20519] intraday_11192.csv.gz  in=198,562,521 out=3,382,787 elapsed=55.1s

  [2311/20519] intraday_11193.csv.gz  in=198,577,530 out=3,397,796 elapsed=55.1s

  [2312/20519] intraday_11191.csv.gz  in=198,587,692 out=3,407,958 elapsed=55.1s

  [2313/20519] intraday_11194.csv.gz  in=198,601,564 out=3,421,830 elapsed=55.1s

  [2314/20519] intraday_11190.csv.gz  in=198,613,323 out=3,433,589 elapsed=55.1s

  [2315/20519] intraday_11196.csv.gz  in=198,626,396 out=3,446,662 elapsed=55.2s

  [2316/20519] intraday_11197.csv.gz  in=198,637,673 out=3,457,939 elapsed=55.2s

  [2317/20519] intraday_11198.csv.gz  in=198,649,715 out=3,469,981 elapsed=55.2s

  [2318/20519] intraday_11195.csv.gz  in=198,663,583 out=3,483,849 elapsed=55.2s

  [2319/20519] intraday_1120.csv.gz  in=198,677,432 out=3,483,849 elapsed=55.2s

  [2320/20519] intraday_11199.csv.gz  in=198,687,522 out=3,493,939 elapsed=55.2s

  [2321/20519] intraday_11201.csv.gz  in=198,694,594 out=3,501,011 elapsed=55.3s

  [2322/20519] intraday_11200.csv.gz  in=198,707,115 out=3,513,532 elapsed=55.3s

  [2323/20519] intraday_11202.csv.gz  in=198,713,776 out=3,520,193 elapsed=55.3s

  [2324/20519] intraday_11204.csv.gz  in=198,715,150 out=3,521,567 elapsed=55.3s

  [2325/20519] intraday_11203.csv.gz  in=198,727,577 out=3,533,994 elapsed=55.3s

  [2326/20519] intraday_11206.csv.gz  in=198,732,694 out=3,534,253 elapsed=55.3s

  [2327/20519] intraday_11205.csv.gz  in=198,741,356 out=3,534,925 elapsed=55.3s

  [2328/20519] intraday_11207.csv.gz  in=198,750,132 out=3,535,986 elapsed=55.3s

  [2329/20519] intraday_11209.csv.gz  in=198,760,555 out=3,546,409 elapsed=55.3s

  [2330/20519] intraday_1121.csv.gz  in=198,775,763 out=3,546,409 elapsed=55.3s

  [2331/20519] intraday_11208.csv.gz  in=198,789,454 out=3,560,100 elapsed=55.3s

  [2332/20519] intraday_11210.csv.gz  in=198,804,473 out=3,575,119 elapsed=55.4s

  [2333/20519] intraday_11211.csv.gz  in=198,814,040 out=3,584,686 elapsed=55.4s

  [2334/20519] intraday_11212.csv.gz  in=198,824,910 out=3,595,556 elapsed=55.4s

  [2335/20519] intraday_11213.csv.gz  in=198,837,255 out=3,607,901 elapsed=55.4s

  [2336/20519] intraday_11214.csv.gz  in=198,850,845 out=3,621,491 elapsed=55.4s

  [2337/20519] intraday_11215.csv.gz  in=198,859,905 out=3,630,551 elapsed=55.4s

  [2338/20519] intraday_11216.csv.gz  in=198,871,773 out=3,642,419 elapsed=55.4s

  [2339/20519] intraday_11217.csv.gz  in=198,884,449 out=3,655,095 elapsed=55.4s

  [2340/20519] intraday_11218.csv.gz  in=198,896,775 out=3,667,421 elapsed=55.5s

  [2341/20519] intraday_11219.csv.gz  in=198,906,602 out=3,677,248 elapsed=55.5s

  [2342/20519] intraday_1122.csv.gz  in=198,922,545 out=3,677,248 elapsed=55.5s

  [2343/20519] intraday_11220.csv.gz  in=198,938,367 out=3,690,208 elapsed=55.5s

  [2344/20519] intraday_11221.csv.gz  in=198,950,211 out=3,702,052 elapsed=55.5s

  [2345/20519] intraday_11223.csv.gz  in=198,961,181 out=3,713,022 elapsed=55.5s

  [2346/20519] intraday_11222.csv.gz  in=198,970,754 out=3,722,595 elapsed=55.5s

  [2347/20519] intraday_11224.csv.gz  in=198,981,854 out=3,733,695 elapsed=55.6s

  [2348/20519] intraday_11225.csv.gz  in=198,994,572 out=3,746,413 elapsed=55.6s

  [2349/20519] intraday_11227.csv.gz  in=199,004,248 out=3,756,089 elapsed=55.6s

  [2350/20519] intraday_11226.csv.gz  in=199,015,713 out=3,767,554 elapsed=55.6s

  [2351/20519] intraday_11228.csv.gz  in=199,031,597 out=3,777,689 elapsed=55.6s

  [2352/20519] intraday_11229.csv.gz  in=199,043,613 out=3,789,705 elapsed=55.6s

  [2353/20519] intraday_11230.csv.gz  in=199,056,155 out=3,802,247 elapsed=55.6s

  [2354/20519] intraday_1123.csv.gz  in=199,069,443 out=3,802,247 elapsed=55.6s

  [2355/20519] intraday_11231.csv.gz  in=199,081,360 out=3,814,164 elapsed=55.7s

  [2356/20519] intraday_11232.csv.gz  in=199,093,684 out=3,826,488 elapsed=55.7s

  [2357/20519] intraday_11233.csv.gz  in=199,105,785 out=3,838,589 elapsed=55.7s

  [2358/20519] intraday_11234.csv.gz  in=199,116,541 out=3,849,345 elapsed=55.7s

  [2359/20519] intraday_11235.csv.gz  in=199,127,031 out=3,859,835 elapsed=55.7s

  [2360/20519] intraday_11236.csv.gz  in=199,137,036 out=3,869,840 elapsed=55.7s

  [2361/20519] intraday_11238.csv.gz  in=199,151,727 out=3,884,531 elapsed=55.7s

  [2362/20519] intraday_11237.csv.gz  in=199,164,426 out=3,897,230 elapsed=55.8s

  [2363/20519] intraday_11239.csv.gz  in=199,176,970 out=3,909,774 elapsed=55.8s

  [2364/20519] intraday_1124.csv.gz  in=199,189,308 out=3,909,774 elapsed=55.8s

  [2365/20519] intraday_11240.csv.gz  in=199,198,766 out=3,919,232 elapsed=55.8s

  [2366/20519] intraday_11241.csv.gz  in=199,208,900 out=3,929,366 elapsed=55.8s

  [2367/20519] intraday_11242.csv.gz  in=199,220,902 out=3,941,368 elapsed=55.8s

  [2368/20519] intraday_11243.csv.gz  in=199,233,102 out=3,953,568 elapsed=55.8s

  [2369/20519] intraday_11245.csv.gz  in=199,244,546 out=3,965,012 elapsed=55.8s

  [2370/20519] intraday_11244.csv.gz  in=199,254,645 out=3,975,111 elapsed=55.8s

  [2371/20519] intraday_11246.csv.gz  in=199,265,767 out=3,986,233 elapsed=55.9s

  [2372/20519] intraday_11249.csv.gz  in=199,276,736 out=3,997,202 elapsed=55.9s

  [2373/20519] intraday_11247.csv.gz  in=199,286,631 out=4,007,097 elapsed=55.9s

  [2374/20519] intraday_11248.csv.gz  in=199,295,829 out=4,016,295 elapsed=55.9s

  [2375/20519] intraday_1125.csv.gz  in=199,308,498 out=4,016,295 elapsed=55.9s

  [2376/20519] intraday_11251.csv.gz  in=199,319,144 out=4,026,941 elapsed=55.9s

  [2377/20519] intraday_11253.csv.gz  in=199,330,933 out=4,038,730 elapsed=56.0s

  [2378/20519] intraday_11252.csv.gz  in=199,344,514 out=4,052,311 elapsed=56.0s

  [2379/20519] intraday_11250.csv.gz  in=199,356,958 out=4,064,755 elapsed=56.0s

  [2380/20519] intraday_11254.csv.gz  in=199,366,992 out=4,074,789 elapsed=56.0s

  [2381/20519] intraday_11255.csv.gz  in=199,377,720 out=4,085,517 elapsed=56.0s

  [2382/20519] intraday_11257.csv.gz  in=199,386,767 out=4,094,564 elapsed=56.0s

  [2383/20519] intraday_11256.csv.gz  in=199,398,383 out=4,106,180 elapsed=56.0s

  [2384/20519] intraday_11259.csv.gz  in=199,409,026 out=4,116,823 elapsed=56.1s

  [2385/20519] intraday_11258.csv.gz  in=199,424,364 out=4,128,515 elapsed=56.1s

  [2386/20519] intraday_1126.csv.gz  in=199,438,548 out=4,128,515 elapsed=56.1s

  [2387/20519] intraday_11260.csv.gz  in=199,449,933 out=4,139,900 elapsed=56.1s

  [2388/20519] intraday_11261.csv.gz  in=199,461,716 out=4,151,683 elapsed=56.1s

  [2389/20519] intraday_11263.csv.gz  in=199,475,508 out=4,165,475 elapsed=56.1s

  [2390/20519] intraday_11264.csv.gz  in=199,488,188 out=4,178,155 elapsed=56.2s

  [2391/20519] intraday_11262.csv.gz  in=199,499,031 out=4,188,998 elapsed=56.2s

  [2392/20519] intraday_11266.csv.gz  in=199,508,687 out=4,198,654 elapsed=56.2s

  [2393/20519] intraday_11265.csv.gz  in=199,520,596 out=4,210,563 elapsed=56.2s

  [2394/20519] intraday_11267.csv.gz  in=199,532,727 out=4,222,694 elapsed=56.2s

  [2395/20519] intraday_11269.csv.gz  in=199,542,786 out=4,232,753 elapsed=56.2s

  [2396/20519] intraday_11268.csv.gz  in=199,554,879 out=4,244,846 elapsed=56.2s

  [2397/20519] intraday_1127.csv.gz  in=199,566,819 out=4,244,846 elapsed=56.2s

  [2398/20519] intraday_11270.csv.gz  in=199,584,714 out=4,257,553 elapsed=56.2s

  [2399/20519] intraday_11272.csv.gz  in=199,594,329 out=4,267,168 elapsed=56.3s

  [2400/20519] intraday_11271.csv.gz  in=199,604,945 out=4,277,784 elapsed=56.3s

  [2401/20519] intraday_11274.csv.gz  in=199,618,885 out=4,291,724 elapsed=56.3s

  [2402/20519] intraday_11273.csv.gz  in=199,633,151 out=4,305,990 elapsed=56.3s

  [2403/20519] intraday_11275.csv.gz  in=199,643,474 out=4,316,313 elapsed=56.3s

  [2404/20519] intraday_11276.csv.gz  in=199,656,766 out=4,329,605 elapsed=56.3s

  [2405/20519] intraday_11277.csv.gz  in=199,668,218 out=4,341,057 elapsed=56.3s

  [2406/20519] intraday_1128.csv.gz  in=199,686,598 out=4,341,057 elapsed=56.4s

  [2407/20519] intraday_11279.csv.gz  in=199,699,217 out=4,353,676 elapsed=56.4s

  [2408/20519] intraday_11278.csv.gz  in=199,710,236 out=4,364,609 elapsed=56.4s

  [2409/20519] intraday_11282.csv.gz  in=199,723,826 out=4,378,199 elapsed=56.4s

  [2410/20519] intraday_11280.csv.gz  in=199,735,632 out=4,390,005 elapsed=56.4s

  [2411/20519] intraday_11283.csv.gz  in=199,747,147 out=4,401,520 elapsed=56.4s

  [2412/20519] intraday_11281.csv.gz  in=199,761,684 out=4,413,648 elapsed=56.4s

  [2413/20519] intraday_11284.csv.gz  in=199,771,606 out=4,423,570 elapsed=56.4s

  [2414/20519] intraday_11285.csv.gz  in=199,781,377 out=4,433,341 elapsed=56.5s

  [2415/20519] intraday_11287.csv.gz  in=199,791,247 out=4,443,211 elapsed=56.5s

  [2416/20519] intraday_11288.csv.gz  in=199,802,026 out=4,453,990 elapsed=56.5s

  [2417/20519] intraday_11289.csv.gz  in=199,810,382 out=4,462,346 elapsed=56.5s

  [2418/20519] intraday_1129.csv.gz  in=199,823,693 out=4,462,346 elapsed=56.5s

  [2419/20519] intraday_11286.csv.gz  in=199,836,881 out=4,475,534 elapsed=56.5s

  [2420/20519] intraday_11290.csv.gz  in=199,846,110 out=4,484,763 elapsed=56.5s

  [2421/20519] intraday_11291.csv.gz  in=199,856,929 out=4,495,582 elapsed=56.6s

  [2422/20519] intraday_11293.csv.gz  in=199,873,743 out=4,512,396 elapsed=56.6s

  [2423/20519] intraday_11292.csv.gz  in=199,887,807 out=4,526,460 elapsed=56.6s

  [2424/20519] intraday_11294.csv.gz  in=199,899,891 out=4,538,544 elapsed=56.6s

  [2425/20519] intraday_11295.csv.gz  in=199,910,077 out=4,548,730 elapsed=56.6s

  [2426/20519] intraday_11297.csv.gz  in=199,922,989 out=4,561,642 elapsed=56.6s

  [2427/20519] intraday_11296.csv.gz  in=199,934,169 out=4,572,822 elapsed=56.6s

  [2428/20519] intraday_11299.csv.gz  in=199,947,299 out=4,585,952 elapsed=56.7s

  [2429/20519] intraday_11298.csv.gz  in=199,958,397 out=4,597,050 elapsed=56.7s

  [2430/20519] intraday_1130.csv.gz  in=199,970,659 out=4,597,050 elapsed=56.7s

  [2431/20519] intraday_11300.csv.gz  in=199,980,618 out=4,607,009 elapsed=56.7s

  [2432/20519] intraday_11301.csv.gz  in=199,996,584 out=4,622,975 elapsed=56.7s

  [2433/20519] intraday_11302.csv.gz  in=200,007,425 out=4,633,816 elapsed=56.7s

  [2434/20519] intraday_11304.csv.gz  in=200,021,209 out=4,647,600 elapsed=56.7s

  [2435/20519] intraday_11303.csv.gz  in=200,032,318 out=4,658,709 elapsed=56.7s

  [2436/20519] intraday_11305.csv.gz  in=200,043,722 out=4,670,113 elapsed=56.7s

  [2437/20519] intraday_11306.csv.gz  in=200,055,491 out=4,681,882 elapsed=56.8s

  [2438/20519] intraday_11307.csv.gz  in=200,065,601 out=4,691,992 elapsed=56.8s

  [2439/20519] intraday_11308.csv.gz  in=200,077,649 out=4,704,040 elapsed=56.8s

  [2440/20519] intraday_11309.csv.gz  in=200,087,360 out=4,713,751 elapsed=56.8s

  [2441/20519] intraday_1131.csv.gz  in=200,099,058 out=4,713,751 elapsed=56.8s

  [2442/20519] intraday_11310.csv.gz  in=200,111,080 out=4,725,773 elapsed=56.8s

  [2443/20519] intraday_11311.csv.gz  in=200,122,395 out=4,737,088 elapsed=56.8s

  [2444/20519] intraday_11313.csv.gz  in=200,133,793 out=4,748,486 elapsed=56.8s

  [2445/20519] intraday_11312.csv.gz  in=200,146,772 out=4,761,465 elapsed=56.9s

  [2446/20519] intraday_11314.csv.gz  in=200,158,374 out=4,773,067 elapsed=56.9s

  [2447/20519] intraday_11315.csv.gz  in=200,171,150 out=4,785,843 elapsed=56.9s

  [2448/20519] intraday_11316.csv.gz  in=200,183,078 out=4,797,737 elapsed=56.9s

  [2449/20519] intraday_11317.csv.gz  in=200,194,226 out=4,808,885 elapsed=56.9s

  [2450/20519] intraday_11318.csv.gz  in=200,206,663 out=4,821,322 elapsed=56.9s

  [2451/20519] intraday_1132.csv.gz  in=200,220,380 out=4,821,322 elapsed=56.9s

  [2452/20519] intraday_11319.csv.gz  in=200,233,467 out=4,834,409 elapsed=57.0s

  [2453/20519] intraday_11321.csv.gz  in=200,243,924 out=4,844,866 elapsed=57.0s

  [2454/20519] intraday_11322.csv.gz  in=200,256,040 out=4,856,982 elapsed=57.0s

  [2455/20519] intraday_11320.csv.gz  in=200,267,330 out=4,868,272 elapsed=57.1s

  [2456/20519] intraday_11325.csv.gz  in=200,280,938 out=4,881,880 elapsed=57.1s

  [2457/20519] intraday_11323.csv.gz  in=200,297,868 out=4,898,810 elapsed=57.1s

  [2458/20519] intraday_11324.csv.gz  in=200,313,046 out=4,913,988 elapsed=57.1s

  [2459/20519] intraday_11327.csv.gz  in=200,325,038 out=4,925,980 elapsed=57.1s

  [2460/20519] intraday_11326.csv.gz  in=200,341,728 out=4,942,670 elapsed=57.1s

  [2461/20519] intraday_11329.csv.gz  in=200,353,145 out=4,954,087 elapsed=57.2s

  [2462/20519] intraday_1133.csv.gz  in=200,366,749 out=4,954,087 elapsed=57.2s

  [2463/20519] intraday_11328.csv.gz  in=200,382,000 out=4,969,338 elapsed=57.2s

  [2464/20519] intraday_11330.csv.gz  in=200,393,223 out=4,980,561 elapsed=57.2s

  [2465/20519] intraday_11332.csv.gz  in=200,405,977 out=4,993,315 elapsed=57.2s

  [2466/20519] intraday_11331.csv.gz  in=200,417,524 out=5,004,862 elapsed=57.2s

  [2467/20519] intraday_11333.csv.gz  in=200,428,181 out=5,015,519 elapsed=57.2s

  [2468/20519] intraday_11334.csv.gz  in=200,440,055 out=5,027,393 elapsed=57.2s

  [2469/20519] intraday_11335.csv.gz  in=200,451,370 out=5,038,708 elapsed=57.3s

  [2470/20519] intraday_11338.csv.gz  in=200,462,602 out=5,049,940 elapsed=57.3s

  [2471/20519] intraday_11336.csv.gz  in=200,477,050 out=5,064,388 elapsed=57.3s

  [2472/20519] intraday_11337.csv.gz  in=200,489,682 out=5,074,748 elapsed=57.3s

  [2473/20519] intraday_11339.csv.gz  in=200,500,490 out=5,085,556 elapsed=57.3s

  [2474/20519] intraday_1134.csv.gz  in=200,525,991 out=5,085,556 elapsed=57.3s

  [2475/20519] intraday_11340.csv.gz  in=200,537,858 out=5,097,423 elapsed=57.4s

  [2476/20519] intraday_11341.csv.gz  in=200,550,299 out=5,100,157 elapsed=57.4s

  [2477/20519] intraday_11342.csv.gz  in=200,562,875 out=5,112,733 elapsed=57.4s

  [2478/20519] intraday_11343.csv.gz  in=200,577,383 out=5,127,241 elapsed=57.4s

  [2479/20519] intraday_11344.csv.gz  in=200,596,659 out=5,142,891 elapsed=57.4s

  [2480/20519] intraday_11345.csv.gz  in=200,610,516 out=5,156,748 elapsed=57.4s

  [2481/20519] intraday_11346.csv.gz  in=200,625,843 out=5,172,075 elapsed=57.4s

  [2482/20519] intraday_11347.csv.gz  in=200,637,956 out=5,184,188 elapsed=57.4s

  [2483/20519] intraday_11348.csv.gz  in=200,649,124 out=5,195,356 elapsed=57.5s

  [2484/20519] intraday_1135.csv.gz  in=200,665,168 out=5,195,356 elapsed=57.5s

  [2485/20519] intraday_11349.csv.gz  in=200,678,499 out=5,208,687 elapsed=57.5s

  [2486/20519] intraday_11350.csv.gz  in=200,689,991 out=5,220,179 elapsed=57.5s

  [2487/20519] intraday_11351.csv.gz  in=200,699,837 out=5,230,025 elapsed=57.5s

  [2488/20519] intraday_11352.csv.gz  in=200,706,649 out=5,236,837 elapsed=57.5s

  [2489/20519] intraday_11353.csv.gz  in=200,717,771 out=5,247,959 elapsed=57.5s

  [2490/20519] intraday_11354.csv.gz  in=200,724,974 out=5,255,162 elapsed=57.5s

  [2491/20519] intraday_11355.csv.gz  in=200,738,706 out=5,268,894 elapsed=57.6s

  [2492/20519] intraday_11356.csv.gz  in=200,750,437 out=5,280,625 elapsed=57.6s

  [2493/20519] intraday_11357.csv.gz  in=200,764,208 out=5,294,396 elapsed=57.6s

  [2494/20519] intraday_11358.csv.gz  in=200,773,508 out=5,303,696 elapsed=57.6s

  [2495/20519] intraday_1136.csv.gz  in=200,784,961 out=5,303,696 elapsed=57.6s

  [2496/20519] intraday_11359.csv.gz  in=200,795,824 out=5,314,559 elapsed=57.6s

  [2497/20519] intraday_11360.csv.gz  in=200,808,903 out=5,327,638 elapsed=57.6s

  [2498/20519] intraday_11361.csv.gz  in=200,822,463 out=5,341,198 elapsed=57.7s

  [2499/20519] intraday_11362.csv.gz  in=200,833,184 out=5,351,919 elapsed=57.7s

  [2500/20519] intraday_11363.csv.gz  in=200,844,342 out=5,363,077 elapsed=57.7s

  [2501/20519] intraday_11364.csv.gz  in=200,857,222 out=5,375,957 elapsed=57.7s

  [2502/20519] intraday_11365.csv.gz  in=200,869,450 out=5,388,185 elapsed=57.7s

  [2503/20519] intraday_11366.csv.gz  in=200,879,663 out=5,398,398 elapsed=57.7s

  [2504/20519] intraday_11368.csv.gz  in=200,892,323 out=5,411,058 elapsed=57.8s

  [2505/20519] intraday_11367.csv.gz  in=200,905,034 out=5,423,769 elapsed=57.8s

  [2506/20519] intraday_11369.csv.gz  in=200,913,914 out=5,432,649 elapsed=57.8s

  [2507/20519] intraday_1137.csv.gz  in=200,927,677 out=5,432,649 elapsed=57.8s

  [2508/20519] intraday_11370.csv.gz  in=200,937,178 out=5,442,150 elapsed=57.8s

  [2509/20519] intraday_11372.csv.gz  in=200,950,151 out=5,455,123 elapsed=57.8s

  [2510/20519] intraday_11371.csv.gz  in=200,962,489 out=5,467,461 elapsed=57.8s

  [2511/20519] intraday_11373.csv.gz  in=200,973,129 out=5,478,101 elapsed=57.8s

  [2512/20519] intraday_11374.csv.gz  in=200,995,892 out=5,489,655 elapsed=57.9s

  [2513/20519] intraday_11376.csv.gz  in=201,008,455 out=5,502,218 elapsed=57.9s

  [2514/20519] intraday_11375.csv.gz  in=201,018,511 out=5,512,274 elapsed=57.9s

  [2515/20519] intraday_11378.csv.gz  in=201,029,617 out=5,523,380 elapsed=57.9s

  [2516/20519] intraday_11377.csv.gz  in=201,046,674 out=5,535,712 elapsed=57.9s

  [2517/20519] intraday_1138.csv.gz  in=201,058,122 out=5,535,712 elapsed=58.0s

  [2518/20519] intraday_11379.csv.gz  in=201,071,228 out=5,548,818 elapsed=58.0s

  [2519/20519] intraday_11380.csv.gz  in=201,083,055 out=5,560,645 elapsed=58.0s

  [2520/20519] intraday_11381.csv.gz  in=201,095,329 out=5,572,919 elapsed=58.0s

  [2521/20519] intraday_11382.csv.gz  in=201,106,002 out=5,583,592 elapsed=58.0s

  [2522/20519] intraday_11383.csv.gz  in=201,115,871 out=5,593,461 elapsed=58.0s

  [2523/20519] intraday_11384.csv.gz  in=201,128,016 out=5,605,606 elapsed=58.0s

  [2524/20519] intraday_11387.csv.gz  in=201,137,709 out=5,615,299 elapsed=58.1s

  [2525/20519] intraday_11385.csv.gz  in=201,152,673 out=5,630,263 elapsed=58.1s

  [2526/20519] intraday_11388.csv.gz  in=201,162,875 out=5,640,465 elapsed=58.1s

  [2527/20519] intraday_11386.csv.gz  in=201,176,107 out=5,653,697 elapsed=58.1s

  [2528/20519] intraday_1139.csv.gz  in=201,188,308 out=5,653,697 elapsed=58.2s

  [2529/20519] intraday_11390.csv.gz  in=201,199,746 out=5,665,135 elapsed=58.2s

  [2530/20519] intraday_11389.csv.gz  in=201,212,389 out=5,677,778 elapsed=58.2s

  [2531/20519] intraday_11391.csv.gz  in=201,223,291 out=5,688,680 elapsed=58.2s

  [2532/20519] intraday_11392.csv.gz  in=201,234,799 out=5,700,188 elapsed=58.2s

  [2533/20519] intraday_11394.csv.gz  in=201,244,601 out=5,709,990 elapsed=58.2s

  [2534/20519] intraday_11393.csv.gz  in=201,258,164 out=5,721,243 elapsed=58.2s

  [2535/20519] intraday_11395.csv.gz  in=201,269,868 out=5,732,947 elapsed=58.3s

  [2536/20519] intraday_11396.csv.gz  in=201,280,543 out=5,743,622 elapsed=58.3s

  [2537/20519] intraday_1140.csv.gz  in=201,293,700 out=5,743,622 elapsed=58.4s

  [2538/20519] intraday_11398.csv.gz  in=201,304,406 out=5,754,328 elapsed=58.4s

  [2539/20519] intraday_11397.csv.gz  in=201,317,138 out=5,767,060 elapsed=58.4s

  [2540/20519] intraday_11399.csv.gz  in=201,330,368 out=5,780,290 elapsed=58.4s

  [2541/20519] intraday_11400.csv.gz  in=201,342,686 out=5,792,608 elapsed=58.4s

  [2542/20519] intraday_11401.csv.gz  in=201,353,878 out=5,803,800 elapsed=58.4s

  [2543/20519] intraday_11402.csv.gz  in=201,364,612 out=5,814,534 elapsed=58.4s

  [2544/20519] intraday_11403.csv.gz  in=201,376,470 out=5,826,392 elapsed=58.4s

  [2545/20519] intraday_11404.csv.gz  in=201,385,438 out=5,835,360 elapsed=58.4s

  [2546/20519] intraday_11405.csv.gz  in=201,397,905 out=5,847,624 elapsed=58.5s

  [2547/20519] intraday_11407.csv.gz  in=201,408,276 out=5,857,995 elapsed=58.5s

  [2548/20519] intraday_11406.csv.gz  in=201,418,692 out=5,868,411 elapsed=58.5s

  [2549/20519] intraday_11409.csv.gz  in=201,429,552 out=5,879,271 elapsed=58.5s

  [2550/20519] intraday_11408.csv.gz  in=201,442,201 out=5,891,920 elapsed=58.5s

  [2551/20519] intraday_1141.csv.gz  in=201,452,998 out=5,891,920 elapsed=58.5s

  [2552/20519] intraday_11410.csv.gz  in=201,466,771 out=5,905,693 elapsed=58.5s

  [2553/20519] intraday_11411.csv.gz  in=201,479,295 out=5,918,217 elapsed=58.6s

  [2554/20519] intraday_11412.csv.gz  in=201,492,216 out=5,931,138 elapsed=58.6s

  [2555/20519] intraday_11413.csv.gz  in=201,502,593 out=5,941,515 elapsed=58.6s

  [2556/20519] intraday_11415.csv.gz  in=201,513,438 out=5,952,360 elapsed=58.6s

  [2557/20519] intraday_11416.csv.gz  in=201,524,419 out=5,963,341 elapsed=58.6s

  [2558/20519] intraday_11414.csv.gz  in=201,536,559 out=5,975,481 elapsed=58.6s

  [2559/20519] intraday_11417.csv.gz  in=201,548,569 out=5,987,491 elapsed=58.6s

  [2560/20519] intraday_11418.csv.gz  in=201,559,451 out=5,998,373 elapsed=58.7s

  [2561/20519] intraday_11419.csv.gz  in=201,569,016 out=6,007,938 elapsed=58.7s

  [2562/20519] intraday_1142.csv.gz  in=201,580,681 out=6,007,938 elapsed=58.7s

  [2563/20519] intraday_11420.csv.gz  in=201,593,507 out=6,020,764 elapsed=58.7s

  [2564/20519] intraday_11422.csv.gz  in=201,605,747 out=6,033,004 elapsed=58.7s

  [2565/20519] intraday_11423.csv.gz  in=201,618,959 out=6,046,216 elapsed=58.7s

  [2566/20519] intraday_11421.csv.gz  in=201,633,382 out=6,060,639 elapsed=58.7s

  [2567/20519] intraday_11424.csv.gz  in=201,646,136 out=6,073,393 elapsed=58.8s

  [2568/20519] intraday_11425.csv.gz  in=201,659,730 out=6,083,798 elapsed=58.8s

  [2569/20519] intraday_11426.csv.gz  in=201,671,472 out=6,095,540 elapsed=58.8s

  [2570/20519] intraday_11428.csv.gz  in=201,684,665 out=6,108,733 elapsed=58.8s

  [2571/20519] intraday_11429.csv.gz  in=201,697,843 out=6,121,911 elapsed=58.8s

  [2572/20519] intraday_1143.csv.gz  in=201,713,203 out=6,121,911 elapsed=58.8s

  [2573/20519] intraday_11427.csv.gz  in=201,725,093 out=6,133,801 elapsed=58.8s

  [2574/20519] intraday_11432.csv.gz  in=201,735,766 out=6,144,474 elapsed=58.9s

  [2575/20519] intraday_11431.csv.gz  in=201,746,642 out=6,155,350 elapsed=58.9s

  [2576/20519] intraday_11430.csv.gz  in=201,758,790 out=6,167,498 elapsed=58.9s

  [2577/20519] intraday_11433.csv.gz  in=201,772,399 out=6,181,107 elapsed=58.9s

  [2578/20519] intraday_11434.csv.gz  in=201,783,029 out=6,191,737 elapsed=58.9s

  [2579/20519] intraday_11435.csv.gz  in=201,793,928 out=6,202,636 elapsed=58.9s

  [2580/20519] intraday_11436.csv.gz  in=201,802,710 out=6,211,418 elapsed=58.9s

  [2581/20519] intraday_11438.csv.gz  in=201,813,259 out=6,221,967 elapsed=58.9s

  [2582/20519] intraday_11439.csv.gz  in=201,826,185 out=6,234,893 elapsed=59.0s

  [2583/20519] intraday_11437.csv.gz  in=201,835,523 out=6,244,231 elapsed=59.0s

  [2584/20519] intraday_1144.csv.gz  in=201,848,735 out=6,244,231 elapsed=59.0s

  [2585/20519] intraday_11440.csv.gz  in=201,869,665 out=6,262,639 elapsed=59.0s

  [2586/20519] intraday_11441.csv.gz  in=201,881,661 out=6,274,635 elapsed=59.0s

  [2587/20519] intraday_11442.csv.gz  in=201,892,430 out=6,285,404 elapsed=59.1s

  [2588/20519] intraday_11443.csv.gz  in=201,903,262 out=6,296,236 elapsed=59.1s

  [2589/20519] intraday_11444.csv.gz  in=201,916,965 out=6,309,939 elapsed=59.1s

  [2590/20519] intraday_11445.csv.gz  in=201,927,552 out=6,320,526 elapsed=59.1s

  [2591/20519] intraday_11446.csv.gz  in=201,942,379 out=6,335,353 elapsed=59.1s

  [2592/20519] intraday_11447.csv.gz  in=201,951,744 out=6,344,718 elapsed=59.2s

  [2593/20519] intraday_11448.csv.gz  in=201,965,193 out=6,358,167 elapsed=59.2s

  [2594/20519] intraday_11449.csv.gz  in=201,977,310 out=6,370,284 elapsed=59.2s

  [2595/20519] intraday_1145.csv.gz  in=201,988,099 out=6,370,284 elapsed=59.2s

  [2596/20519] intraday_11450.csv.gz  in=202,001,120 out=6,383,305 elapsed=59.2s

  [2597/20519] intraday_11452.csv.gz  in=202,012,216 out=6,394,401 elapsed=59.2s

  [2598/20519] intraday_11451.csv.gz  in=202,025,829 out=6,408,014 elapsed=59.2s

  [2599/20519] intraday_11453.csv.gz  in=202,041,826 out=6,421,530 elapsed=59.2s

  [2600/20519] intraday_11455.csv.gz  in=202,052,665 out=6,432,369 elapsed=59.3s

  [2601/20519] intraday_11454.csv.gz  in=202,063,933 out=6,443,637 elapsed=59.3s

  [2602/20519] intraday_11457.csv.gz  in=202,074,287 out=6,453,991 elapsed=59.3s

  [2603/20519] intraday_11456.csv.gz  in=202,085,999 out=6,465,703 elapsed=59.3s

  [2604/20519] intraday_11458.csv.gz  in=202,097,510 out=6,477,214 elapsed=59.3s

  [2605/20519] intraday_11459.csv.gz  in=202,110,611 out=6,490,315 elapsed=59.3s

  [2606/20519] intraday_1146.csv.gz  in=202,124,813 out=6,490,315 elapsed=59.4s

  [2607/20519] intraday_11461.csv.gz  in=202,136,048 out=6,501,550 elapsed=59.4s

  [2608/20519] intraday_11460.csv.gz  in=202,147,896 out=6,513,398 elapsed=59.4s

  [2609/20519] intraday_11462.csv.gz  in=202,160,321 out=6,525,823 elapsed=59.4s

  [2610/20519] intraday_11463.csv.gz  in=202,172,996 out=6,538,498 elapsed=59.4s

  [2611/20519] intraday_11464.csv.gz  in=202,184,814 out=6,550,316 elapsed=59.4s

  [2612/20519] intraday_11465.csv.gz  in=202,197,551 out=6,563,053 elapsed=59.4s

  [2613/20519] intraday_11466.csv.gz  in=202,210,098 out=6,575,600 elapsed=59.4s

  [2614/20519] intraday_11468.csv.gz  in=202,219,457 out=6,584,959 elapsed=59.5s

  [2615/20519] intraday_11467.csv.gz  in=202,232,160 out=6,597,662 elapsed=59.5s

  [2616/20519] intraday_11469.csv.gz  in=202,245,997 out=6,611,499 elapsed=59.5s

  [2617/20519] intraday_1147.csv.gz  in=202,257,708 out=6,611,499 elapsed=59.5s

  [2618/20519] intraday_11471.csv.gz  in=202,271,328 out=6,625,119 elapsed=59.5s

  [2619/20519] intraday_11472.csv.gz  in=202,285,516 out=6,639,132 elapsed=59.5s

  [2620/20519] intraday_11470.csv.gz  in=202,302,572 out=6,656,188 elapsed=59.5s

  [2621/20519] intraday_11473.csv.gz  in=202,317,686 out=6,671,302 elapsed=59.5s

  [2622/20519] intraday_11474.csv.gz  in=202,331,748 out=6,685,364 elapsed=59.6s

  [2623/20519] intraday_11475.csv.gz  in=202,346,810 out=6,700,426 elapsed=59.6s

  [2624/20519] intraday_11476.csv.gz  in=202,359,970 out=6,713,586 elapsed=59.6s

  [2625/20519] intraday_11477.csv.gz  in=202,371,554 out=6,725,170 elapsed=59.6s

  [2626/20519] intraday_11478.csv.gz  in=202,384,497 out=6,738,113 elapsed=59.6s

  [2627/20519] intraday_11479.csv.gz  in=202,396,068 out=6,749,684 elapsed=59.6s

  [2628/20519] intraday_1148.csv.gz  in=202,407,336 out=6,749,684 elapsed=59.6s

  [2629/20519] intraday_11481.csv.gz  in=202,419,361 out=6,761,709 elapsed=59.7s

  [2630/20519] intraday_11480.csv.gz  in=202,430,518 out=6,772,866 elapsed=59.7s

  [2631/20519] intraday_11482.csv.gz  in=202,443,347 out=6,785,695 elapsed=59.7s

  [2632/20519] intraday_11483.csv.gz  in=202,459,176 out=6,801,524 elapsed=59.7s

  [2633/20519] intraday_11485.csv.gz  in=202,470,432 out=6,812,780 elapsed=59.7s

  [2634/20519] intraday_11484.csv.gz  in=202,483,241 out=6,825,589 elapsed=59.7s

  [2635/20519] intraday_11487.csv.gz  in=202,496,097 out=6,838,445 elapsed=59.7s

  [2636/20519] intraday_11486.csv.gz  in=202,506,357 out=6,848,705 elapsed=59.7s

  [2637/20519] intraday_1149.csv.gz  in=202,520,540 out=6,848,705 elapsed=59.8s

  [2638/20519] intraday_11488.csv.gz  in=202,531,412 out=6,859,577 elapsed=59.8s

  [2639/20519] intraday_11490.csv.gz  in=202,546,664 out=6,874,829 elapsed=59.8s

  [2640/20519] intraday_11489.csv.gz  in=202,558,484 out=6,886,649 elapsed=59.8s

  [2641/20519] intraday_11491.csv.gz  in=202,571,507 out=6,899,672 elapsed=59.8s

  [2642/20519] intraday_11492.csv.gz  in=202,584,939 out=6,913,104 elapsed=59.8s

  [2643/20519] intraday_11494.csv.gz  in=202,596,280 out=6,924,445 elapsed=59.9s

  [2644/20519] intraday_11493.csv.gz  in=202,611,039 out=6,939,204 elapsed=59.9s

  [2645/20519] intraday_11495.csv.gz  in=202,624,106 out=6,952,271 elapsed=59.9s

  [2646/20519] intraday_11496.csv.gz  in=202,634,377 out=6,962,542 elapsed=59.9s

  [2647/20519] intraday_11498.csv.gz  in=202,641,792 out=6,969,957 elapsed=59.9s

  [2648/20519] intraday_11497.csv.gz  in=202,654,747 out=6,982,912 elapsed=59.9s

  [2649/20519] intraday_11499.csv.gz  in=202,661,856 out=6,990,021 elapsed=59.9s

  [2650/20519] intraday_1150.csv.gz  in=202,673,487 out=6,990,021 elapsed=59.9s

  [2651/20519] intraday_11501.csv.gz  in=202,676,521 out=6,993,055 elapsed=60.0s

  [2652/20519] intraday_11502.csv.gz  in=202,683,370 out=6,994,747 elapsed=60.0s

  [2653/20519] intraday_11500.csv.gz  in=202,695,424 out=7,006,801 elapsed=60.0s

  [2654/20519] intraday_11505.csv.gz  in=202,708,084 out=7,019,461 elapsed=60.0s

  [2655/20519] intraday_11504.csv.gz  in=202,720,067 out=7,031,444 elapsed=60.0s

  [2656/20519] intraday_11503.csv.gz  in=202,733,039 out=7,044,416 elapsed=60.0s

  [2657/20519] intraday_11507.csv.gz  in=202,744,082 out=7,055,459 elapsed=60.0s

  [2658/20519] intraday_11506.csv.gz  in=202,752,993 out=7,064,370 elapsed=60.0s

  [2659/20519] intraday_1151.csv.gz  in=202,766,021 out=7,064,370 elapsed=60.1s

  [2660/20519] intraday_11508.csv.gz  in=202,778,299 out=7,076,648 elapsed=60.1s

  [2661/20519] intraday_11510.csv.gz  in=202,789,429 out=7,087,778 elapsed=60.1s

  [2662/20519] intraday_11511.csv.gz  in=202,800,103 out=7,098,452 elapsed=60.1s

  [2663/20519] intraday_11509.csv.gz  in=202,814,077 out=7,112,426 elapsed=60.1s

  [2664/20519] intraday_11512.csv.gz  in=202,826,622 out=7,124,885 elapsed=60.1s

  [2665/20519] intraday_11514.csv.gz  in=202,838,070 out=7,136,333 elapsed=60.2s

  [2666/20519] intraday_11513.csv.gz  in=202,849,136 out=7,147,399 elapsed=60.2s

  [2667/20519] intraday_11515.csv.gz  in=202,860,917 out=7,159,180 elapsed=60.2s

  [2668/20519] intraday_11516.csv.gz  in=202,872,222 out=7,170,485 elapsed=60.2s

  [2669/20519] intraday_11517.csv.gz  in=202,881,177 out=7,179,440 elapsed=60.2s

  [2670/20519] intraday_11518.csv.gz  in=202,890,920 out=7,189,183 elapsed=60.2s

  [2671/20519] intraday_11519.csv.gz  in=202,902,934 out=7,201,196 elapsed=60.2s

  [2672/20519] intraday_11520.csv.gz  in=202,914,546 out=7,212,808 elapsed=60.2s

  [2673/20519] intraday_11521.csv.gz  in=202,925,893 out=7,224,155 elapsed=60.2s

  [2674/20519] intraday_1152.csv.gz  in=202,952,580 out=7,224,155 elapsed=60.2s

  [2675/20519] intraday_11522.csv.gz  in=202,962,377 out=7,233,952 elapsed=60.3s

  [2676/20519] intraday_11524.csv.gz  in=202,972,933 out=7,244,508 elapsed=60.3s

  [2677/20519] intraday_11523.csv.gz  in=202,984,245 out=7,255,820 elapsed=60.3s

  [2678/20519] intraday_11525.csv.gz  in=202,996,104 out=7,267,679 elapsed=60.3s

  [2679/20519] intraday_11527.csv.gz  in=203,008,323 out=7,279,898 elapsed=60.3s

  [2680/20519] intraday_11526.csv.gz  in=203,018,828 out=7,290,403 elapsed=60.3s

  [2681/20519] intraday_1153.csv.gz  in=203,031,436 out=7,290,403 elapsed=60.3s

  [2682/20519] intraday_11528.csv.gz  in=203,042,192 out=7,301,159 elapsed=60.3s

  [2683/20519] intraday_11529.csv.gz  in=203,054,126 out=7,313,093 elapsed=60.3s

  [2684/20519] intraday_11530.csv.gz  in=203,065,316 out=7,324,283 elapsed=60.4s

  [2685/20519] intraday_11531.csv.gz  in=203,074,600 out=7,333,567 elapsed=60.4s

  [2686/20519] intraday_11532.csv.gz  in=203,086,601 out=7,345,568 elapsed=60.4s

  [2687/20519] intraday_11533.csv.gz  in=203,100,616 out=7,359,583 elapsed=60.4s

  [2688/20519] intraday_11535.csv.gz  in=203,100,813 out=7,359,780 elapsed=60.4s

  [2689/20519] intraday_11534.csv.gz  in=203,112,346 out=7,371,313 elapsed=60.4s

  [2690/20519] intraday_11536.csv.gz  in=203,112,739 out=7,371,706 elapsed=60.4s

  [2691/20519] intraday_11537.csv.gz  in=203,112,810 out=7,371,777 elapsed=60.4s

  [2692/20519] intraday_11540.csv.gz  in=203,112,815 out=7,371,782 elapsed=60.4s

  [2693/20519] intraday_11538.csv.gz  in=203,112,850 out=7,371,817 elapsed=60.4s

  [2694/20519] intraday_11539.csv.gz  in=203,113,124 out=7,371,896 elapsed=60.4s

  [2695/20519] intraday_11541.csv.gz  in=203,113,152 out=7,371,924 elapsed=60.4s

  [2696/20519] intraday_11542.csv.gz  in=203,113,227 out=7,371,999 elapsed=60.5s

  [2697/20519] intraday_1154.csv.gz  in=203,123,775 out=7,371,999 elapsed=60.5s

  [2698/20519] intraday_11543.csv.gz  in=203,131,501 out=7,379,725 elapsed=60.5s

  [2699/20519] intraday_11545.csv.gz  in=203,143,060 out=7,391,284 elapsed=60.5s

  [2700/20519] intraday_11544.csv.gz  in=203,153,552 out=7,401,776 elapsed=60.5s

  [2701/20519] intraday_11547.csv.gz  in=203,163,665 out=7,411,889 elapsed=60.5s

  [2702/20519] intraday_11546.csv.gz  in=203,199,235 out=7,427,113 elapsed=60.5s

  [2703/20519] intraday_11549.csv.gz  in=203,208,241 out=7,436,119 elapsed=60.6s

  [2704/20519] intraday_11548.csv.gz  in=203,219,942 out=7,447,820 elapsed=60.6s

  [2705/20519] intraday_1155.csv.gz  in=203,233,284 out=7,447,820 elapsed=60.6s

  [2706/20519] intraday_11550.csv.gz  in=203,243,439 out=7,457,975 elapsed=60.6s

  [2707/20519] intraday_11551.csv.gz  in=203,254,109 out=7,468,645 elapsed=60.6s

  [2708/20519] intraday_11552.csv.gz  in=203,264,721 out=7,479,257 elapsed=60.6s

  [2709/20519] intraday_11553.csv.gz  in=203,277,146 out=7,491,682 elapsed=60.6s

  [2710/20519] intraday_11554.csv.gz  in=203,287,750 out=7,502,232 elapsed=60.6s

  [2711/20519] intraday_11555.csv.gz  in=203,298,843 out=7,513,325 elapsed=60.7s

  [2712/20519] intraday_11556.csv.gz  in=203,312,067 out=7,526,549 elapsed=60.7s

  [2713/20519] intraday_11558.csv.gz  in=203,322,517 out=7,536,999 elapsed=60.7s

  [2714/20519] intraday_11557.csv.gz  in=203,332,069 out=7,546,551 elapsed=60.7s

  [2715/20519] intraday_11559.csv.gz  in=203,343,553 out=7,558,035 elapsed=60.7s

  [2716/20519] intraday_1156.csv.gz  in=203,355,506 out=7,558,035 elapsed=60.7s

  [2717/20519] intraday_11560.csv.gz  in=203,365,654 out=7,568,183 elapsed=60.7s

  [2718/20519] intraday_11561.csv.gz  in=203,388,600 out=7,580,851 elapsed=60.7s

  [2719/20519] intraday_11563.csv.gz  in=203,397,326 out=7,589,577 elapsed=60.8s

  [2720/20519] intraday_11562.csv.gz  in=203,407,833 out=7,600,084 elapsed=60.8s

  [2721/20519] intraday_11564.csv.gz  in=203,419,383 out=7,611,634 elapsed=60.8s

  [2722/20519] intraday_11565.csv.gz  in=203,430,592 out=7,622,776 elapsed=60.8s

  [2723/20519] intraday_11566.csv.gz  in=203,441,222 out=7,633,406 elapsed=60.8s

  [2724/20519] intraday_11567.csv.gz  in=203,452,839 out=7,645,023 elapsed=60.8s

  [2725/20519] intraday_11568.csv.gz  in=203,464,580 out=7,656,764 elapsed=60.8s

  [2726/20519] intraday_1157.csv.gz  in=203,476,994 out=7,656,764 elapsed=60.9s

  [2727/20519] intraday_11569.csv.gz  in=203,487,488 out=7,667,258 elapsed=60.9s

  [2728/20519] intraday_11570.csv.gz  in=203,498,980 out=7,678,750 elapsed=60.9s

  [2729/20519] intraday_11571.csv.gz  in=203,511,019 out=7,690,789 elapsed=60.9s

  [2730/20519] intraday_11572.csv.gz  in=203,521,007 out=7,700,777 elapsed=60.9s

  [2731/20519] intraday_11573.csv.gz  in=203,533,189 out=7,712,959 elapsed=60.9s

  [2732/20519] intraday_11574.csv.gz  in=203,543,189 out=7,722,959 elapsed=60.9s

  [2733/20519] intraday_11576.csv.gz  in=203,552,735 out=7,732,505 elapsed=60.9s

  [2734/20519] intraday_11575.csv.gz  in=203,566,016 out=7,743,874 elapsed=60.9s

  [2735/20519] intraday_11577.csv.gz  in=203,579,564 out=7,757,422 elapsed=61.0s

  [2736/20519] intraday_11578.csv.gz  in=203,595,614 out=7,769,176 elapsed=61.0s

  [2737/20519] intraday_11579.csv.gz  in=203,609,234 out=7,782,796 elapsed=61.0s

  [2738/20519] intraday_11580.csv.gz  in=203,621,911 out=7,795,473 elapsed=61.0s

  [2739/20519] intraday_1158.csv.gz  in=203,639,094 out=7,795,473 elapsed=61.0s

  [2740/20519] intraday_11582.csv.gz  in=203,648,994 out=7,805,373 elapsed=61.0s

  [2741/20519] intraday_11581.csv.gz  in=203,660,737 out=7,817,116 elapsed=61.1s

  [2742/20519] intraday_11583.csv.gz  in=203,672,163 out=7,828,542 elapsed=61.1s

  [2743/20519] intraday_11584.csv.gz  in=203,683,971 out=7,840,350 elapsed=61.1s

  [2744/20519] intraday_11585.csv.gz  in=203,695,347 out=7,851,726 elapsed=61.1s

  [2745/20519] intraday_11587.csv.gz  in=203,706,006 out=7,862,385 elapsed=61.1s

  [2746/20519] intraday_11586.csv.gz  in=203,717,841 out=7,874,220 elapsed=61.2s

  [2747/20519] intraday_1159.csv.gz  in=203,733,502 out=7,874,220 elapsed=61.2s

  [2748/20519] intraday_11589.csv.gz  in=203,746,969 out=7,887,663 elapsed=61.2s

  [2749/20519] intraday_11588.csv.gz  in=203,756,646 out=7,897,340 elapsed=61.2s

  [2750/20519] intraday_11590.csv.gz  in=203,766,005 out=7,906,699 elapsed=61.2s

  [2751/20519] intraday_11592.csv.gz  in=203,775,683 out=7,916,377 elapsed=61.2s

  [2752/20519] intraday_11593.csv.gz  in=203,783,329 out=7,924,023 elapsed=61.3s

  [2753/20519] intraday_11591.csv.gz  in=203,794,340 out=7,935,034 elapsed=61.3s

  [2754/20519] intraday_11594.csv.gz  in=203,805,593 out=7,946,287 elapsed=61.3s

  [2755/20519] intraday_11595.csv.gz  in=203,816,659 out=7,957,353 elapsed=61.3s

  [2756/20519] intraday_11596.csv.gz  in=203,832,026 out=7,972,720 elapsed=61.3s

  [2757/20519] intraday_11597.csv.gz  in=203,844,927 out=7,985,621 elapsed=61.3s

  [2758/20519] intraday_11598.csv.gz  in=203,857,132 out=7,997,826 elapsed=61.3s

  [2759/20519] intraday_1160.csv.gz  in=203,866,668 out=7,997,826 elapsed=61.3s

  [2760/20519] intraday_11599.csv.gz  in=203,875,988 out=8,007,146 elapsed=61.3s

  [2761/20519] intraday_11600.csv.gz  in=203,889,570 out=8,020,728 elapsed=61.3s

  [2762/20519] intraday_11603.csv.gz  in=203,900,040 out=8,031,198 elapsed=61.3s

  [2763/20519] intraday_11601.csv.gz  in=203,910,117 out=8,041,275 elapsed=61.3s

  [2764/20519] intraday_11602.csv.gz  in=203,922,967 out=8,054,125 elapsed=61.4s

  [2765/20519] intraday_11605.csv.gz  in=203,933,932 out=8,065,090 elapsed=61.4s

  [2766/20519] intraday_11604.csv.gz  in=203,945,763 out=8,076,921 elapsed=61.4s

  [2767/20519] intraday_11607.csv.gz  in=203,957,697 out=8,088,498 elapsed=61.4s

  [2768/20519] intraday_11608.csv.gz  in=203,969,637 out=8,100,438 elapsed=61.4s

  [2769/20519] intraday_11606.csv.gz  in=203,982,327 out=8,113,128 elapsed=61.4s

  [2770/20519] intraday_11609.csv.gz  in=203,995,544 out=8,126,054 elapsed=61.4s

  [2771/20519] intraday_1161.csv.gz  in=204,007,668 out=8,126,054 elapsed=61.4s

  [2772/20519] intraday_11610.csv.gz  in=204,019,120 out=8,137,506 elapsed=61.4s

  [2773/20519] intraday_11611.csv.gz  in=204,028,816 out=8,147,202 elapsed=61.5s

  [2774/20519] intraday_11613.csv.gz  in=204,038,475 out=8,156,861 elapsed=61.5s

  [2775/20519] intraday_11612.csv.gz  in=204,049,673 out=8,168,059 elapsed=61.5s

  [2776/20519] intraday_11614.csv.gz  in=204,060,714 out=8,179,100 elapsed=61.5s

  [2777/20519] intraday_11615.csv.gz  in=204,074,412 out=8,191,903 elapsed=61.5s

  [2778/20519] intraday_11616.csv.gz  in=204,086,199 out=8,203,690 elapsed=61.5s

  [2779/20519] intraday_11617.csv.gz  in=204,097,073 out=8,214,564 elapsed=61.5s

  [2780/20519] intraday_11618.csv.gz  in=204,109,538 out=8,226,190 elapsed=61.5s

  [2781/20519] intraday_1162.csv.gz  in=204,122,967 out=8,226,190 elapsed=61.6s

  [2782/20519] intraday_11619.csv.gz  in=204,136,618 out=8,239,841 elapsed=61.6s

  [2783/20519] intraday_11621.csv.gz  in=204,147,665 out=8,250,888 elapsed=61.6s

  [2784/20519] intraday_11620.csv.gz  in=204,158,237 out=8,261,460 elapsed=61.6s

  [2785/20519] intraday_11622.csv.gz  in=204,170,614 out=8,273,837 elapsed=61.6s

  [2786/20519] intraday_11623.csv.gz  in=204,184,387 out=8,287,610 elapsed=61.6s

  [2787/20519] intraday_11624.csv.gz  in=204,193,968 out=8,297,191 elapsed=61.6s

  [2788/20519] intraday_11625.csv.gz  in=204,206,896 out=8,310,119 elapsed=61.6s

  [2789/20519] intraday_11626.csv.gz  in=204,221,751 out=8,324,974 elapsed=61.7s

  [2790/20519] intraday_11627.csv.gz  in=204,234,125 out=8,337,348 elapsed=61.7s

  [2791/20519] intraday_11629.csv.gz  in=204,248,146 out=8,351,361 elapsed=61.7s

  [2792/20519] intraday_1163.csv.gz  in=204,262,282 out=8,351,361 elapsed=61.7s

  [2793/20519] intraday_11628.csv.gz  in=204,274,917 out=8,363,996 elapsed=61.7s

  [2794/20519] intraday_11633.csv.gz  in=204,285,715 out=8,374,794 elapsed=61.8s

  [2795/20519] intraday_11632.csv.gz  in=204,298,594 out=8,387,673 elapsed=61.8s

  [2796/20519] intraday_11631.csv.gz  in=204,312,942 out=8,402,021 elapsed=61.8s

  [2797/20519] intraday_11630.csv.gz  in=204,329,270 out=8,418,349 elapsed=61.8s

  [2798/20519] intraday_11635.csv.gz  in=204,340,825 out=8,429,904 elapsed=61.8s

  [2799/20519] intraday_11634.csv.gz  in=204,352,498 out=8,441,577 elapsed=61.8s

  [2800/20519] intraday_11636.csv.gz  in=204,364,861 out=8,453,940 elapsed=61.8s

  [2801/20519] intraday_11637.csv.gz  in=204,375,226 out=8,463,134 elapsed=61.8s

  [2802/20519] intraday_11638.csv.gz  in=204,387,307 out=8,475,215 elapsed=61.8s

  [2803/20519] intraday_1164.csv.gz  in=204,397,915 out=8,475,215 elapsed=61.9s

  [2804/20519] intraday_11639.csv.gz  in=204,410,313 out=8,487,613 elapsed=61.9s

  [2805/20519] intraday_11640.csv.gz  in=204,425,058 out=8,502,358 elapsed=61.9s

  [2806/20519] intraday_11641.csv.gz  in=204,437,926 out=8,513,329 elapsed=61.9s

  [2807/20519] intraday_11643.csv.gz  in=204,448,815 out=8,524,218 elapsed=61.9s

  [2808/20519] intraday_11642.csv.gz  in=204,459,170 out=8,534,573 elapsed=61.9s

  [2809/20519] intraday_11645.csv.gz  in=204,470,144 out=8,545,547 elapsed=61.9s

  [2810/20519] intraday_11644.csv.gz  in=204,481,199 out=8,556,602 elapsed=61.9s

  [2811/20519] intraday_11646.csv.gz  in=204,494,750 out=8,570,153 elapsed=62.0s

  [2812/20519] intraday_11647.csv.gz  in=204,508,923 out=8,584,326 elapsed=62.0s

  [2813/20519] intraday_11648.csv.gz  in=204,521,157 out=8,596,560 elapsed=62.0s

  [2814/20519] intraday_1165.csv.gz  in=204,535,460 out=8,596,560 elapsed=62.0s

  [2815/20519] intraday_11649.csv.gz  in=204,551,221 out=8,612,321 elapsed=62.1s

  [2816/20519] intraday_11651.csv.gz  in=204,564,163 out=8,624,729 elapsed=62.1s

  [2817/20519] intraday_11650.csv.gz  in=204,575,570 out=8,636,136 elapsed=62.1s

  [2818/20519] intraday_11653.csv.gz  in=204,585,648 out=8,646,214 elapsed=62.1s

  [2819/20519] intraday_11652.csv.gz  in=204,602,620 out=8,658,976 elapsed=62.1s

  [2820/20519] intraday_11654.csv.gz  in=204,613,404 out=8,669,132 elapsed=62.1s

  [2821/20519] intraday_11658.csv.gz  in=204,613,533 out=8,669,261 elapsed=62.2s

  [2822/20519] intraday_11656.csv.gz  in=204,621,707 out=8,677,435 elapsed=62.2s

  [2823/20519] intraday_11655.csv.gz  in=204,630,574 out=8,683,789 elapsed=62.2s

  [2824/20519] intraday_11657.csv.gz  in=204,641,044 out=8,694,259 elapsed=62.2s

  [2825/20519] intraday_1166.csv.gz  in=204,652,093 out=8,694,259 elapsed=62.2s

  [2826/20519] intraday_11659.csv.gz  in=204,665,087 out=8,707,253 elapsed=62.2s

  [2827/20519] intraday_11660.csv.gz  in=204,677,000 out=8,719,166 elapsed=62.2s

  [2828/20519] intraday_11662.csv.gz  in=204,686,731 out=8,728,897 elapsed=62.2s

  [2829/20519] intraday_11661.csv.gz  in=204,700,113 out=8,742,279 elapsed=62.2s

  [2830/20519] intraday_11663.csv.gz  in=204,710,578 out=8,752,744 elapsed=62.3s

  [2831/20519] intraday_11664.csv.gz  in=204,723,544 out=8,765,710 elapsed=62.3s

  [2832/20519] intraday_11665.csv.gz  in=204,737,965 out=8,780,131 elapsed=62.3s

  [2833/20519] intraday_11666.csv.gz  in=204,748,893 out=8,791,059 elapsed=62.3s

  [2834/20519] intraday_11668.csv.gz  in=204,761,141 out=8,803,307 elapsed=62.3s

  [2835/20519] intraday_1167.csv.gz  in=204,773,481 out=8,803,307 elapsed=62.3s

  [2836/20519] intraday_11669.csv.gz  in=204,785,556 out=8,815,382 elapsed=62.3s

  [2837/20519] intraday_11667.csv.gz  in=204,796,897 out=8,826,723 elapsed=62.3s

  [2838/20519] intraday_11670.csv.gz  in=204,807,471 out=8,837,297 elapsed=62.4s

  [2839/20519] intraday_11671.csv.gz  in=204,819,655 out=8,849,481 elapsed=62.4s

  [2840/20519] intraday_11672.csv.gz  in=204,831,632 out=8,861,458 elapsed=62.4s

  [2841/20519] intraday_11673.csv.gz  in=204,841,581 out=8,871,407 elapsed=62.4s

  [2842/20519] intraday_11674.csv.gz  in=204,850,760 out=8,880,586 elapsed=62.4s

  [2843/20519] intraday_11675.csv.gz  in=204,862,625 out=8,892,451 elapsed=62.4s

  [2844/20519] intraday_11676.csv.gz  in=204,876,144 out=8,905,970 elapsed=62.4s

  [2845/20519] intraday_11677.csv.gz  in=204,887,774 out=8,917,600 elapsed=62.4s

  [2846/20519] intraday_11678.csv.gz  in=204,898,109 out=8,927,935 elapsed=62.4s

  [2847/20519] intraday_11679.csv.gz  in=204,908,803 out=8,938,629 elapsed=62.5s

  [2848/20519] intraday_1168.csv.gz  in=204,920,660 out=8,938,629 elapsed=62.5s

  [2849/20519] intraday_11680.csv.gz  in=204,932,563 out=8,950,532 elapsed=62.5s

  [2850/20519] intraday_11681.csv.gz  in=204,945,165 out=8,963,134 elapsed=62.5s

  [2851/20519] intraday_11682.csv.gz  in=204,956,781 out=8,974,750 elapsed=62.5s

  [2852/20519] intraday_11683.csv.gz  in=204,969,048 out=8,987,017 elapsed=62.5s

  [2853/20519] intraday_11685.csv.gz  in=204,981,250 out=8,999,219 elapsed=62.6s

  [2854/20519] intraday_11684.csv.gz  in=204,992,177 out=9,010,146 elapsed=62.6s

  [2855/20519] intraday_11686.csv.gz  in=205,002,566 out=9,020,535 elapsed=62.6s

  [2856/20519] intraday_11687.csv.gz  in=205,012,401 out=9,030,370 elapsed=62.6s

  [2857/20519] intraday_11688.csv.gz  in=205,024,885 out=9,042,854 elapsed=62.6s

  [2858/20519] intraday_11689.csv.gz  in=205,038,345 out=9,056,314 elapsed=62.6s

  [2859/20519] intraday_1169.csv.gz  in=205,052,164 out=9,056,314 elapsed=62.6s

  [2860/20519] intraday_11690.csv.gz  in=205,064,878 out=9,069,028 elapsed=62.6s

  [2861/20519] intraday_11691.csv.gz  in=205,074,611 out=9,078,761 elapsed=62.6s

  [2862/20519] intraday_11692.csv.gz  in=205,084,855 out=9,089,005 elapsed=62.6s

  [2863/20519] intraday_11693.csv.gz  in=205,096,725 out=9,100,875 elapsed=62.7s

  [2864/20519] intraday_11694.csv.gz  in=205,110,338 out=9,114,488 elapsed=62.7s

  [2865/20519] intraday_11696.csv.gz  in=205,121,689 out=9,125,839 elapsed=62.7s

  [2866/20519] intraday_11695.csv.gz  in=205,132,267 out=9,136,417 elapsed=62.7s

  [2867/20519] intraday_11697.csv.gz  in=205,142,059 out=9,146,209 elapsed=62.7s

  [2868/20519] intraday_11698.csv.gz  in=205,152,951 out=9,157,101 elapsed=62.7s

  [2869/20519] intraday_11699.csv.gz  in=205,163,186 out=9,167,336 elapsed=62.7s

  [2870/20519] intraday_1170.csv.gz  in=205,173,622 out=9,167,336 elapsed=62.8s

  [2871/20519] intraday_11700.csv.gz  in=205,184,912 out=9,178,626 elapsed=62.8s

  [2872/20519] intraday_11701.csv.gz  in=205,197,823 out=9,191,537 elapsed=62.8s

  [2873/20519] intraday_11703.csv.gz  in=205,209,544 out=9,203,258 elapsed=62.8s

  [2874/20519] intraday_11702.csv.gz  in=205,220,867 out=9,214,581 elapsed=62.8s

  [2875/20519] intraday_11704.csv.gz  in=205,233,598 out=9,227,312 elapsed=62.8s

  [2876/20519] intraday_11705.csv.gz  in=205,243,408 out=9,237,122 elapsed=62.8s

  [2877/20519] intraday_11706.csv.gz  in=205,255,228 out=9,248,942 elapsed=62.9s

  [2878/20519] intraday_11707.csv.gz  in=205,265,972 out=9,259,686 elapsed=62.9s

  [2879/20519] intraday_11708.csv.gz  in=205,276,530 out=9,270,244 elapsed=62.9s

  [2880/20519] intraday_11709.csv.gz  in=205,287,963 out=9,281,677 elapsed=62.9s

  [2881/20519] intraday_1171.csv.gz  in=205,298,689 out=9,281,677 elapsed=62.9s

  [2882/20519] intraday_11710.csv.gz  in=205,308,631 out=9,291,619 elapsed=62.9s

  [2883/20519] intraday_11711.csv.gz  in=205,318,441 out=9,301,429 elapsed=62.9s

  [2884/20519] intraday_11713.csv.gz  in=205,330,571 out=9,313,559 elapsed=63.0s

  [2885/20519] intraday_11712.csv.gz  in=205,342,699 out=9,325,687 elapsed=63.0s

  [2886/20519] intraday_11714.csv.gz  in=205,353,212 out=9,336,200 elapsed=63.0s

  [2887/20519] intraday_11715.csv.gz  in=205,365,162 out=9,348,150 elapsed=63.0s

  [2888/20519] intraday_11716.csv.gz  in=205,376,735 out=9,359,723 elapsed=63.0s

  [2889/20519] intraday_11717.csv.gz  in=205,387,339 out=9,370,327 elapsed=63.0s

  [2890/20519] intraday_11718.csv.gz  in=205,399,276 out=9,382,264 elapsed=63.0s

  [2891/20519] intraday_11719.csv.gz  in=205,411,298 out=9,394,286 elapsed=63.0s

  [2892/20519] intraday_1172.csv.gz  in=205,425,560 out=9,394,286 elapsed=63.0s

  [2893/20519] intraday_11720.csv.gz  in=205,437,078 out=9,405,804 elapsed=63.1s

  [2894/20519] intraday_11721.csv.gz  in=205,448,763 out=9,417,489 elapsed=63.1s

  [2895/20519] intraday_11722.csv.gz  in=205,459,331 out=9,428,057 elapsed=63.1s

  [2896/20519] intraday_11723.csv.gz  in=205,470,074 out=9,438,800 elapsed=63.1s

  [2897/20519] intraday_11725.csv.gz  in=205,484,067 out=9,452,793 elapsed=63.2s

  [2898/20519] intraday_11724.csv.gz  in=205,494,375 out=9,463,101 elapsed=63.2s

  [2899/20519] intraday_11727.csv.gz  in=205,508,402 out=9,477,128 elapsed=63.2s

  [2900/20519] intraday_11726.csv.gz  in=205,520,303 out=9,489,029 elapsed=63.2s

  [2901/20519] intraday_11728.csv.gz  in=205,532,378 out=9,501,104 elapsed=63.2s

  [2902/20519] intraday_1173.csv.gz  in=205,547,216 out=9,501,104 elapsed=63.2s

  [2903/20519] intraday_11729.csv.gz  in=205,557,891 out=9,511,779 elapsed=63.2s

  [2904/20519] intraday_11730.csv.gz  in=205,568,170 out=9,522,058 elapsed=63.3s

  [2905/20519] intraday_11731.csv.gz  in=205,579,775 out=9,533,663 elapsed=63.3s

  [2906/20519] intraday_11732.csv.gz  in=205,592,919 out=9,546,807 elapsed=63.3s

  [2907/20519] intraday_11733.csv.gz  in=205,605,977 out=9,559,865 elapsed=63.3s

  [2908/20519] intraday_11734.csv.gz  in=205,617,475 out=9,571,363 elapsed=63.3s

  [2909/20519] intraday_11735.csv.gz  in=205,628,769 out=9,582,657 elapsed=63.3s

  [2910/20519] intraday_11737.csv.gz  in=205,642,742 out=9,596,630 elapsed=63.4s

  [2911/20519] intraday_11736.csv.gz  in=205,652,717 out=9,606,605 elapsed=63.4s

  [2912/20519] intraday_11738.csv.gz  in=205,662,980 out=9,616,868 elapsed=63.4s

  [2913/20519] intraday_11739.csv.gz  in=205,673,508 out=9,627,396 elapsed=63.4s

  [2914/20519] intraday_1174.csv.gz  in=205,686,180 out=9,627,396 elapsed=63.4s

  [2915/20519] intraday_11740.csv.gz  in=205,696,158 out=9,637,374 elapsed=63.4s

  [2916/20519] intraday_11741.csv.gz  in=205,704,603 out=9,645,819 elapsed=63.4s

  [2917/20519] intraday_11742.csv.gz  in=205,715,704 out=9,656,920 elapsed=63.4s

  [2918/20519] intraday_11743.csv.gz  in=205,727,626 out=9,668,842 elapsed=63.5s

  [2919/20519] intraday_11744.csv.gz  in=205,744,890 out=9,686,106 elapsed=63.5s

  [2920/20519] intraday_11745.csv.gz  in=205,756,917 out=9,698,133 elapsed=63.5s

  [2921/20519] intraday_11746.csv.gz  in=205,769,035 out=9,710,251 elapsed=63.5s

  [2922/20519] intraday_11747.csv.gz  in=205,779,145 out=9,720,361 elapsed=63.5s

  [2923/20519] intraday_11748.csv.gz  in=205,792,939 out=9,734,155 elapsed=63.5s

  [2924/20519] intraday_1175.csv.gz  in=205,805,028 out=9,734,155 elapsed=63.5s

  [2925/20519] intraday_11749.csv.gz  in=205,814,556 out=9,743,683 elapsed=63.5s

  [2926/20519] intraday_11752.csv.gz  in=205,825,045 out=9,754,172 elapsed=63.6s

  [2927/20519] intraday_11753.csv.gz  in=205,836,837 out=9,765,964 elapsed=63.6s

  [2928/20519] intraday_11750.csv.gz  in=205,849,772 out=9,778,899 elapsed=63.6s

  [2929/20519] intraday_11751.csv.gz  in=205,861,050 out=9,790,177 elapsed=63.6s

  [2930/20519] intraday_11754.csv.gz  in=205,874,601 out=9,803,728 elapsed=63.6s

  [2931/20519] intraday_11755.csv.gz  in=205,887,365 out=9,816,492 elapsed=63.6s

  [2932/20519] intraday_11756.csv.gz  in=205,899,036 out=9,828,163 elapsed=63.6s

  [2933/20519] intraday_11758.csv.gz  in=205,910,417 out=9,839,544 elapsed=63.7s

  [2934/20519] intraday_11757.csv.gz  in=205,922,503 out=9,851,630 elapsed=63.7s

  [2935/20519] intraday_1176.csv.gz  in=205,935,541 out=9,851,630 elapsed=63.7s

  [2936/20519] intraday_11759.csv.gz  in=205,945,989 out=9,862,078 elapsed=63.7s

  [2937/20519] intraday_11761.csv.gz  in=205,955,503 out=9,871,592 elapsed=63.7s

  [2938/20519] intraday_11760.csv.gz  in=205,967,110 out=9,883,199 elapsed=63.7s

  [2939/20519] intraday_11762.csv.gz  in=205,978,895 out=9,894,984 elapsed=63.7s

  [2940/20519] intraday_11763.csv.gz  in=205,991,792 out=9,907,881 elapsed=63.7s

  [2941/20519] intraday_11764.csv.gz  in=206,004,054 out=9,920,143 elapsed=63.8s

  [2942/20519] intraday_11765.csv.gz  in=206,015,270 out=9,931,359 elapsed=63.8s

  [2943/20519] intraday_11766.csv.gz  in=206,025,292 out=9,941,381 elapsed=63.8s

  [2944/20519] intraday_11769.csv.gz  in=206,037,158 out=9,953,247 elapsed=63.8s

  [2945/20519] intraday_11767.csv.gz  in=206,051,242 out=9,967,331 elapsed=63.8s

  [2946/20519] intraday_11768.csv.gz  in=206,061,387 out=9,977,476 elapsed=63.8s

  [2947/20519] intraday_1177.csv.gz  in=206,073,460 out=9,977,476 elapsed=63.8s

  [2948/20519] intraday_11770.csv.gz  in=206,086,209 out=9,990,225 elapsed=63.9s

  [2949/20519] intraday_11772.csv.gz  in=206,096,679 out=10,000,695 elapsed=63.9s

  [2950/20519] intraday_11771.csv.gz  in=206,110,189 out=10,014,205 elapsed=63.9s

  [2951/20519] intraday_11773.csv.gz  in=206,123,426 out=10,027,442 elapsed=63.9s

  [2952/20519] intraday_11776.csv.gz  in=206,137,589 out=10,041,605 elapsed=63.9s

  [2953/20519] intraday_11774.csv.gz  in=206,153,203 out=10,057,219 elapsed=64.0s

  [2954/20519] intraday_11775.csv.gz  in=206,165,003 out=10,069,019 elapsed=64.0s

  [2955/20519] intraday_11777.csv.gz  in=206,178,339 out=10,082,355 elapsed=64.0s

  [2956/20519] intraday_1178.csv.gz  in=206,191,897 out=10,082,355 elapsed=64.0s

  [2957/20519] intraday_11778.csv.gz  in=206,208,000 out=10,098,458 elapsed=64.0s

  [2958/20519] intraday_11779.csv.gz  in=206,221,670 out=10,112,128 elapsed=64.0s

  [2959/20519] intraday_11780.csv.gz  in=206,236,141 out=10,126,599 elapsed=64.0s

  [2960/20519] intraday_11783.csv.gz  in=206,247,453 out=10,137,911 elapsed=64.1s

  [2961/20519] intraday_11781.csv.gz  in=206,258,183 out=10,148,641 elapsed=64.1s

  [2962/20519] intraday_11782.csv.gz  in=206,271,232 out=10,161,690 elapsed=64.1s

  [2963/20519] intraday_11784.csv.gz  in=206,283,195 out=10,173,653 elapsed=64.1s

  [2964/20519] intraday_11785.csv.gz  in=206,293,919 out=10,184,377 elapsed=64.1s

  [2965/20519] intraday_11786.csv.gz  in=206,304,757 out=10,195,215 elapsed=64.1s

  [2966/20519] intraday_11787.csv.gz  in=206,317,895 out=10,208,353 elapsed=64.1s

  [2967/20519] intraday_11788.csv.gz  in=206,331,616 out=10,222,074 elapsed=64.2s

  [2968/20519] intraday_1179.csv.gz  in=206,347,435 out=10,222,074 elapsed=64.2s

  [2969/20519] intraday_11789.csv.gz  in=206,357,908 out=10,232,547 elapsed=64.2s

  [2970/20519] intraday_11791.csv.gz  in=206,369,465 out=10,244,104 elapsed=64.2s

  [2971/20519] intraday_11790.csv.gz  in=206,380,249 out=10,254,888 elapsed=64.2s

  [2972/20519] intraday_11792.csv.gz  in=206,392,019 out=10,266,658 elapsed=64.2s

  [2973/20519] intraday_11793.csv.gz  in=206,402,094 out=10,276,733 elapsed=64.3s

  [2974/20519] intraday_11794.csv.gz  in=206,416,535 out=10,291,174 elapsed=64.3s

  [2975/20519] intraday_11795.csv.gz  in=206,431,598 out=10,306,237 elapsed=64.3s

  [2976/20519] intraday_11796.csv.gz  in=206,444,067 out=10,318,706 elapsed=64.3s

  [2977/20519] intraday_11798.csv.gz  in=206,455,079 out=10,329,718 elapsed=64.3s

  [2978/20519] intraday_11797.csv.gz  in=206,470,762 out=10,345,401 elapsed=64.3s

  [2979/20519] intraday_1180.csv.gz  in=206,490,380 out=10,345,401 elapsed=64.3s

  [2980/20519] intraday_11799.csv.gz  in=206,502,336 out=10,357,357 elapsed=64.4s

  [2981/20519] intraday_11800.csv.gz  in=206,515,151 out=10,370,172 elapsed=64.4s

  [2982/20519] intraday_11803.csv.gz  in=206,521,222 out=10,376,243 elapsed=64.4s

  [2983/20519] intraday_11802.csv.gz  in=206,532,852 out=10,387,873 elapsed=64.4s

  [2984/20519] intraday_11801.csv.gz  in=206,542,426 out=10,397,447 elapsed=64.4s

  [2985/20519] intraday_11804.csv.gz  in=206,552,067 out=10,407,088 elapsed=64.5s

  [2986/20519] intraday_11805.csv.gz  in=206,561,059 out=10,416,080 elapsed=64.5s

  [2987/20519] intraday_11807.csv.gz  in=206,575,053 out=10,430,074 elapsed=64.5s

  [2988/20519] intraday_11806.csv.gz  in=206,598,194 out=10,435,718 elapsed=64.5s

  [2989/20519] intraday_11808.csv.gz  in=206,611,332 out=10,448,856 elapsed=64.5s

  [2990/20519] intraday_11809.csv.gz  in=206,623,904 out=10,461,428 elapsed=64.5s

  [2991/20519] intraday_1181.csv.gz  in=206,638,444 out=10,461,428 elapsed=64.5s

  [2992/20519] intraday_11810.csv.gz  in=206,647,883 out=10,470,867 elapsed=64.6s

  [2993/20519] intraday_11811.csv.gz  in=206,659,431 out=10,482,415 elapsed=64.6s

  [2994/20519] intraday_11812.csv.gz  in=206,673,261 out=10,496,245 elapsed=64.6s

  [2995/20519] intraday_11813.csv.gz  in=206,687,528 out=10,510,512 elapsed=64.6s

  [2996/20519] intraday_11815.csv.gz  in=206,699,626 out=10,522,610 elapsed=64.6s

  [2997/20519] intraday_11814.csv.gz  in=206,711,354 out=10,534,338 elapsed=64.6s

  [2998/20519] intraday_11816.csv.gz  in=206,724,259 out=10,547,243 elapsed=64.6s

  [2999/20519] intraday_11817.csv.gz  in=206,736,833 out=10,559,817 elapsed=64.6s

  [3000/20519] intraday_11818.csv.gz  in=206,747,634 out=10,570,618 elapsed=64.7s

  [3001/20519] intraday_1182.csv.gz  in=206,762,290 out=10,570,618 elapsed=64.7s

  [3002/20519] intraday_11819.csv.gz  in=206,775,682 out=10,584,010 elapsed=64.7s

  [3003/20519] intraday_11820.csv.gz  in=206,788,427 out=10,596,755 elapsed=64.7s

  [3004/20519] intraday_11821.csv.gz  in=206,797,687 out=10,606,015 elapsed=64.7s

  [3005/20519] intraday_11822.csv.gz  in=206,809,059 out=10,617,387 elapsed=64.7s

  [3006/20519] intraday_11823.csv.gz  in=206,822,751 out=10,631,079 elapsed=64.7s

  [3007/20519] intraday_11824.csv.gz  in=206,837,460 out=10,645,788 elapsed=64.7s

  [3008/20519] intraday_11825.csv.gz  in=206,847,754 out=10,656,082 elapsed=64.7s

  [3009/20519] intraday_11826.csv.gz  in=206,858,040 out=10,666,368 elapsed=64.8s

  [3010/20519] intraday_11827.csv.gz  in=206,868,775 out=10,677,103 elapsed=64.8s

  [3011/20519] intraday_11828.csv.gz  in=206,881,265 out=10,689,593 elapsed=64.8s

  [3012/20519] intraday_11829.csv.gz  in=206,893,632 out=10,701,960 elapsed=64.8s

  [3013/20519] intraday_1183.csv.gz  in=206,908,635 out=10,701,960 elapsed=64.8s

  [3014/20519] intraday_11830.csv.gz  in=206,920,472 out=10,713,797 elapsed=64.8s

  [3015/20519] intraday_11831.csv.gz  in=206,933,754 out=10,727,079 elapsed=64.8s

  [3016/20519] intraday_11832.csv.gz  in=206,945,365 out=10,738,690 elapsed=64.8s

  [3017/20519] intraday_11833.csv.gz  in=206,957,134 out=10,750,459 elapsed=64.9s

  [3018/20519] intraday_11834.csv.gz  in=206,969,081 out=10,762,406 elapsed=64.9s

  [3019/20519] intraday_11836.csv.gz  in=206,981,832 out=10,775,157 elapsed=64.9s

  [3020/20519] intraday_11835.csv.gz  in=206,991,893 out=10,785,218 elapsed=64.9s

  [3021/20519] intraday_11837.csv.gz  in=207,005,542 out=10,798,867 elapsed=64.9s

  [3022/20519] intraday_11838.csv.gz  in=207,018,583 out=10,811,908 elapsed=64.9s

  [3023/20519] intraday_11839.csv.gz  in=207,028,889 out=10,822,214 elapsed=64.9s

  [3024/20519] intraday_1184.csv.gz  in=207,042,635 out=10,822,214 elapsed=64.9s

  [3025/20519] intraday_11841.csv.gz  in=207,055,109 out=10,834,688 elapsed=65.0s

  [3026/20519] intraday_11840.csv.gz  in=207,066,678 out=10,846,257 elapsed=65.0s

  [3027/20519] intraday_11842.csv.gz  in=207,079,655 out=10,859,234 elapsed=65.0s

  [3028/20519] intraday_11844.csv.gz  in=207,090,437 out=10,870,016 elapsed=65.0s

  [3029/20519] intraday_11846.csv.gz  in=207,101,287 out=10,880,866 elapsed=65.0s

  [3030/20519] intraday_11843.csv.gz  in=207,113,151 out=10,892,730 elapsed=65.0s

  [3031/20519] intraday_11845.csv.gz  in=207,123,881 out=10,903,460 elapsed=65.0s

  [3032/20519] intraday_11849.csv.gz  in=207,134,428 out=10,914,007 elapsed=65.0s

  [3033/20519] intraday_11847.csv.gz  in=207,146,007 out=10,925,586 elapsed=65.1s

  [3034/20519] intraday_1185.csv.gz  in=207,158,270 out=10,925,586 elapsed=65.1s

  [3035/20519] intraday_11850.csv.gz  in=207,170,742 out=10,938,058 elapsed=65.1s

  [3036/20519] intraday_11848.csv.gz  in=207,184,242 out=10,951,558 elapsed=65.1s

  [3037/20519] intraday_11851.csv.gz  in=207,198,308 out=10,965,624 elapsed=65.1s

  [3038/20519] intraday_11853.csv.gz  in=207,209,892 out=10,977,208 elapsed=65.1s

  [3039/20519] intraday_11852.csv.gz  in=207,221,755 out=10,989,071 elapsed=65.1s

  [3040/20519] intraday_11854.csv.gz  in=207,233,701 out=11,001,017 elapsed=65.2s

  [3041/20519] intraday_11856.csv.gz  in=207,244,034 out=11,011,350 elapsed=65.2s

  [3042/20519] intraday_11855.csv.gz  in=207,256,093 out=11,023,409 elapsed=65.2s

  [3043/20519] intraday_11859.csv.gz  in=207,267,127 out=11,034,443 elapsed=65.2s

  [3044/20519] intraday_11858.csv.gz  in=207,276,319 out=11,043,635 elapsed=65.2s

  [3045/20519] intraday_11857.csv.gz  in=207,288,385 out=11,055,701 elapsed=65.2s

  [3046/20519] intraday_11860.csv.gz  in=207,298,863 out=11,066,179 elapsed=65.2s

  [3047/20519] intraday_1186.csv.gz  in=207,320,425 out=11,066,179 elapsed=65.3s

  [3048/20519] intraday_11863.csv.gz  in=207,332,010 out=11,077,749 elapsed=65.3s

  [3049/20519] intraday_11864.csv.gz  in=207,344,345 out=11,090,084 elapsed=65.3s

  [3050/20519] intraday_11862.csv.gz  in=207,357,396 out=11,103,135 elapsed=65.3s

  [3051/20519] intraday_11861.csv.gz  in=207,370,894 out=11,116,633 elapsed=65.3s

  [3052/20519] intraday_11865.csv.gz  in=207,381,467 out=11,127,206 elapsed=65.3s

  [3053/20519] intraday_11868.csv.gz  in=207,392,064 out=11,137,803 elapsed=65.4s

  [3054/20519] intraday_11866.csv.gz  in=207,403,417 out=11,149,097 elapsed=65.4s

  [3055/20519] intraday_11869.csv.gz  in=207,414,685 out=11,160,365 elapsed=65.4s

  [3056/20519] intraday_11867.csv.gz  in=207,427,144 out=11,172,824 elapsed=65.4s

  [3057/20519] intraday_1187.csv.gz  in=207,441,249 out=11,172,824 elapsed=65.4s

  [3058/20519] intraday_11870.csv.gz  in=207,453,810 out=11,185,385 elapsed=65.4s

  [3059/20519] intraday_11871.csv.gz  in=207,463,234 out=11,194,809 elapsed=65.4s

  [3060/20519] intraday_11872.csv.gz  in=207,477,599 out=11,207,913 elapsed=65.4s

  [3061/20519] intraday_11873.csv.gz  in=207,492,255 out=11,222,569 elapsed=65.5s

  [3062/20519] intraday_11874.csv.gz  in=207,503,684 out=11,233,998 elapsed=65.5s

  [3063/20519] intraday_11875.csv.gz  in=207,517,434 out=11,247,748 elapsed=65.5s

  [3064/20519] intraday_11877.csv.gz  in=207,527,022 out=11,257,336 elapsed=65.5s

  [3065/20519] intraday_11876.csv.gz  in=207,537,462 out=11,267,776 elapsed=65.5s

  [3066/20519] intraday_11879.csv.gz  in=207,550,290 out=11,280,604 elapsed=65.5s

  [3067/20519] intraday_11878.csv.gz  in=207,563,983 out=11,294,297 elapsed=65.5s

  [3068/20519] intraday_1188.csv.gz  in=207,575,896 out=11,294,297 elapsed=65.5s

  [3069/20519] intraday_11880.csv.gz  in=207,587,509 out=11,305,910 elapsed=65.5s

  [3070/20519] intraday_11881.csv.gz  in=207,600,879 out=11,319,280 elapsed=65.6s

  [3071/20519] intraday_11883.csv.gz  in=207,610,398 out=11,328,799 elapsed=65.6s

  [3072/20519] intraday_11882.csv.gz  in=207,623,373 out=11,341,774 elapsed=65.6s

  [3073/20519] intraday_11884.csv.gz  in=207,635,088 out=11,353,489 elapsed=65.6s

  [3074/20519] intraday_11885.csv.gz  in=207,648,513 out=11,366,914 elapsed=65.6s

  [3075/20519] intraday_11887.csv.gz  in=207,658,079 out=11,376,480 elapsed=65.6s

  [3076/20519] intraday_11886.csv.gz  in=207,668,443 out=11,386,844 elapsed=65.6s

  [3077/20519] intraday_11888.csv.gz  in=207,677,133 out=11,395,534 elapsed=65.6s

  [3078/20519] intraday_11889.csv.gz  in=207,688,252 out=11,406,653 elapsed=65.7s

  [3079/20519] intraday_1189.csv.gz  in=207,701,405 out=11,406,653 elapsed=65.7s

  [3080/20519] intraday_11890.csv.gz  in=207,714,156 out=11,419,404 elapsed=65.7s

  [3081/20519] intraday_11891.csv.gz  in=207,728,226 out=11,433,474 elapsed=65.7s

  [3082/20519] intraday_11894.csv.gz  in=207,739,583 out=11,444,831 elapsed=65.7s

  [3083/20519] intraday_11893.csv.gz  in=207,751,704 out=11,456,952 elapsed=65.7s

  [3084/20519] intraday_11892.csv.gz  in=207,768,052 out=11,473,300 elapsed=65.7s

  [3085/20519] intraday_11896.csv.gz  in=207,780,312 out=11,485,560 elapsed=65.8s

  [3086/20519] intraday_11895.csv.gz  in=207,791,719 out=11,496,967 elapsed=65.8s

  [3087/20519] intraday_11897.csv.gz  in=207,805,722 out=11,510,970 elapsed=65.8s

  [3088/20519] intraday_11898.csv.gz  in=207,816,860 out=11,522,108 elapsed=65.8s

  [3089/20519] intraday_11899.csv.gz  in=207,827,878 out=11,533,126 elapsed=65.8s

  [3090/20519] intraday_1190.csv.gz  in=207,840,106 out=11,533,126 elapsed=65.8s

  [3091/20519] intraday_11900.csv.gz  in=207,853,968 out=11,546,988 elapsed=65.8s

  [3092/20519] intraday_11901.csv.gz  in=207,866,616 out=11,559,636 elapsed=65.8s

  [3093/20519] intraday_11902.csv.gz  in=207,879,134 out=11,572,154 elapsed=65.9s

  [3094/20519] intraday_11903.csv.gz  in=207,891,426 out=11,584,446 elapsed=65.9s

  [3095/20519] intraday_11904.csv.gz  in=207,903,186 out=11,596,206 elapsed=65.9s

  [3096/20519] intraday_11905.csv.gz  in=207,915,466 out=11,608,486 elapsed=65.9s

  [3097/20519] intraday_11906.csv.gz  in=207,927,459 out=11,620,479 elapsed=65.9s

  [3098/20519] intraday_11909.csv.gz  in=207,940,047 out=11,633,067 elapsed=65.9s

  [3099/20519] intraday_11907.csv.gz  in=207,952,632 out=11,645,652 elapsed=65.9s

  [3100/20519] intraday_1191.csv.gz  in=207,965,090 out=11,645,652 elapsed=66.0s

  [3101/20519] intraday_11908.csv.gz  in=207,976,089 out=11,656,651 elapsed=66.0s

  [3102/20519] intraday_11912.csv.gz  in=207,987,772 out=11,668,334 elapsed=66.0s

  [3103/20519] intraday_11911.csv.gz  in=207,999,587 out=11,680,149 elapsed=66.0s

  [3104/20519] intraday_11913.csv.gz  in=208,010,810 out=11,691,254 elapsed=66.0s

  [3105/20519] intraday_11910.csv.gz  in=208,024,274 out=11,704,718 elapsed=66.0s

  [3106/20519] intraday_11914.csv.gz  in=208,038,732 out=11,719,176 elapsed=66.0s

  [3107/20519] intraday_11916.csv.gz  in=208,050,142 out=11,730,586 elapsed=66.1s

  [3108/20519] intraday_11917.csv.gz  in=208,063,919 out=11,744,363 elapsed=66.1s

  [3109/20519] intraday_11915.csv.gz  in=208,074,172 out=11,754,616 elapsed=66.1s

  [3110/20519] intraday_11919.csv.gz  in=208,084,330 out=11,764,774 elapsed=66.1s

  [3111/20519] intraday_11918.csv.gz  in=208,097,958 out=11,778,402 elapsed=66.1s

  [3112/20519] intraday_1192.csv.gz  in=208,110,192 out=11,778,402 elapsed=66.1s

  [3113/20519] intraday_11920.csv.gz  in=208,122,993 out=11,791,203 elapsed=66.1s

  [3114/20519] intraday_11921.csv.gz  in=208,137,540 out=11,805,750 elapsed=66.2s

  [3115/20519] intraday_11924.csv.gz  in=208,152,330 out=11,820,540 elapsed=66.2s

  [3116/20519] intraday_11922.csv.gz  in=208,166,689 out=11,834,899 elapsed=66.2s

  [3117/20519] intraday_11923.csv.gz  in=208,179,512 out=11,847,722 elapsed=66.2s

  [3118/20519] intraday_11925.csv.gz  in=208,196,702 out=11,864,912 elapsed=66.2s

  [3119/20519] intraday_11928.csv.gz  in=208,208,524 out=11,876,734 elapsed=66.3s

  [3120/20519] intraday_11926.csv.gz  in=208,222,519 out=11,890,729 elapsed=66.3s

  [3121/20519] intraday_11929.csv.gz  in=208,235,152 out=11,903,362 elapsed=66.3s

  [3122/20519] intraday_11927.csv.gz  in=208,249,067 out=11,917,277 elapsed=66.3s

  [3123/20519] intraday_1193.csv.gz  in=208,261,050 out=11,917,277 elapsed=66.3s

  [3124/20519] intraday_11931.csv.gz  in=208,273,549 out=11,929,776 elapsed=66.3s

  [3125/20519] intraday_11930.csv.gz  in=208,286,106 out=11,942,333 elapsed=66.3s

  [3126/20519] intraday_11932.csv.gz  in=208,297,551 out=11,953,673 elapsed=66.3s

  [3127/20519] intraday_11933.csv.gz  in=208,310,433 out=11,966,555 elapsed=66.4s

  [3128/20519] intraday_11934.csv.gz  in=208,322,454 out=11,978,576 elapsed=66.4s

  [3129/20519] intraday_11936.csv.gz  in=208,332,661 out=11,988,783 elapsed=66.4s

  [3130/20519] intraday_11937.csv.gz  in=208,343,932 out=12,000,054 elapsed=66.4s

  [3131/20519] intraday_11938.csv.gz  in=208,355,237 out=12,011,359 elapsed=66.4s

  [3132/20519] intraday_11935.csv.gz  in=208,370,369 out=12,026,491 elapsed=66.5s

  [3133/20519] intraday_11939.csv.gz  in=208,382,149 out=12,038,271 elapsed=66.5s

  [3134/20519] intraday_1194.csv.gz  in=208,399,840 out=12,038,271 elapsed=66.5s

  [3135/20519] intraday_11941.csv.gz  in=208,412,982 out=12,051,413 elapsed=66.5s

  [3136/20519] intraday_11940.csv.gz  in=208,423,987 out=12,062,418 elapsed=66.5s

  [3137/20519] intraday_11942.csv.gz  in=208,438,901 out=12,077,332 elapsed=66.5s

  [3138/20519] intraday_11943.csv.gz  in=208,452,515 out=12,090,946 elapsed=66.5s

  [3139/20519] intraday_11944.csv.gz  in=208,468,146 out=12,106,577 elapsed=66.5s

  [3140/20519] intraday_11946.csv.gz  in=208,479,672 out=12,118,103 elapsed=66.6s

  [3141/20519] intraday_11945.csv.gz  in=208,492,025 out=12,130,456 elapsed=66.6s

  [3142/20519] intraday_11947.csv.gz  in=208,504,406 out=12,142,837 elapsed=66.6s

  [3143/20519] intraday_11948.csv.gz  in=208,515,163 out=12,153,594 elapsed=66.6s

  [3144/20519] intraday_11949.csv.gz  in=208,527,627 out=12,166,058 elapsed=66.6s

  [3145/20519] intraday_11950.csv.gz  in=208,534,164 out=12,172,595 elapsed=66.6s

  [3146/20519] intraday_1195.csv.gz  in=208,544,007 out=12,172,595 elapsed=66.6s

  [3147/20519] intraday_11952.csv.gz  in=208,555,077 out=12,183,665 elapsed=66.6s

  [3148/20519] intraday_11953.csv.gz  in=208,570,692 out=12,199,280 elapsed=66.7s

  [3149/20519] intraday_11951.csv.gz  in=208,583,248 out=12,208,412 elapsed=66.7s

  [3150/20519] intraday_11954.csv.gz  in=208,596,444 out=12,221,608 elapsed=66.7s

  [3151/20519] intraday_11955.csv.gz  in=208,609,551 out=12,233,971 elapsed=66.7s

  [3152/20519] intraday_11957.csv.gz  in=208,621,512 out=12,245,932 elapsed=66.7s

  [3153/20519] intraday_11956.csv.gz  in=208,632,610 out=12,257,030 elapsed=66.7s

  [3154/20519] intraday_11959.csv.gz  in=208,649,084 out=12,273,504 elapsed=66.7s

  [3155/20519] intraday_11958.csv.gz  in=208,663,748 out=12,288,168 elapsed=66.7s

  [3156/20519] intraday_1196.csv.gz  in=208,683,631 out=12,288,168 elapsed=66.7s

  [3157/20519] intraday_11960.csv.gz  in=208,695,078 out=12,299,615 elapsed=66.8s

  [3158/20519] intraday_11961.csv.gz  in=208,707,088 out=12,311,625 elapsed=66.8s

  [3159/20519] intraday_11962.csv.gz  in=208,720,958 out=12,325,495 elapsed=66.8s

  [3160/20519] intraday_11964.csv.gz  in=208,732,314 out=12,336,851 elapsed=66.8s

  [3161/20519] intraday_11963.csv.gz  in=208,745,424 out=12,349,961 elapsed=66.8s

  [3162/20519] intraday_11965.csv.gz  in=208,758,755 out=12,363,292 elapsed=66.8s

  [3163/20519] intraday_11966.csv.gz  in=208,771,297 out=12,375,834 elapsed=66.9s

  [3164/20519] intraday_11967.csv.gz  in=208,781,178 out=12,385,715 elapsed=66.9s

  [3165/20519] intraday_11968.csv.gz  in=208,792,487 out=12,397,024 elapsed=66.9s

  [3166/20519] intraday_11969.csv.gz  in=208,806,413 out=12,410,950 elapsed=66.9s

  [3167/20519] intraday_1197.csv.gz  in=208,821,601 out=12,410,950 elapsed=66.9s

  [3168/20519] intraday_11971.csv.gz  in=208,834,030 out=12,423,379 elapsed=66.9s

  [3169/20519] intraday_11970.csv.gz  in=208,847,263 out=12,436,612 elapsed=66.9s

  [3170/20519] intraday_11972.csv.gz  in=208,858,586 out=12,447,935 elapsed=67.0s

  [3171/20519] intraday_11974.csv.gz  in=208,870,697 out=12,460,046 elapsed=67.0s

  [3172/20519] intraday_11973.csv.gz  in=208,881,412 out=12,470,761 elapsed=67.0s

  [3173/20519] intraday_11975.csv.gz  in=208,894,418 out=12,483,767 elapsed=67.0s

  [3174/20519] intraday_11977.csv.gz  in=208,906,766 out=12,496,115 elapsed=67.0s

  [3175/20519] intraday_11976.csv.gz  in=208,919,831 out=12,509,180 elapsed=67.0s

  [3176/20519] intraday_11979.csv.gz  in=208,931,626 out=12,520,975 elapsed=67.0s

  [3177/20519] intraday_1198.csv.gz  in=208,947,078 out=12,520,975 elapsed=67.0s

  [3178/20519] intraday_11978.csv.gz  in=208,959,137 out=12,533,034 elapsed=67.0s

  [3179/20519] intraday_11980.csv.gz  in=208,978,174 out=12,546,071 elapsed=67.1s

  [3180/20519] intraday_11981.csv.gz  in=208,989,631 out=12,557,528 elapsed=67.1s

  [3181/20519] intraday_11983.csv.gz  in=209,004,029 out=12,571,926 elapsed=67.1s

  [3182/20519] intraday_11984.csv.gz  in=209,017,453 out=12,585,350 elapsed=67.2s

  [3183/20519] intraday_11985.csv.gz  in=209,027,738 out=12,595,635 elapsed=67.2s

  [3184/20519] intraday_11982.csv.gz  in=209,040,726 out=12,608,623 elapsed=67.2s

  [3185/20519] intraday_11986.csv.gz  in=209,053,209 out=12,621,106 elapsed=67.2s

  [3186/20519] intraday_11987.csv.gz  in=209,066,519 out=12,634,416 elapsed=67.2s

  [3187/20519] intraday_11988.csv.gz  in=209,080,089 out=12,647,986 elapsed=67.2s

  [3188/20519] intraday_1199.csv.gz  in=209,093,801 out=12,647,986 elapsed=67.2s

  [3189/20519] intraday_11989.csv.gz  in=209,106,154 out=12,660,339 elapsed=67.2s

  [3190/20519] intraday_11990.csv.gz  in=209,117,266 out=12,671,451 elapsed=67.2s

  [3191/20519] intraday_11991.csv.gz  in=209,128,652 out=12,682,837 elapsed=67.3s

  [3192/20519] intraday_11992.csv.gz  in=209,140,951 out=12,693,047 elapsed=67.3s

  [3193/20519] intraday_11993.csv.gz  in=209,152,242 out=12,704,338 elapsed=67.3s

  [3194/20519] intraday_11994.csv.gz  in=209,164,519 out=12,716,615 elapsed=67.3s

  [3195/20519] intraday_11995.csv.gz  in=209,178,046 out=12,730,142 elapsed=67.3s

  [3196/20519] intraday_11996.csv.gz  in=209,190,096 out=12,742,192 elapsed=67.3s

  [3197/20519] intraday_11997.csv.gz  in=209,206,682 out=12,755,908 elapsed=67.3s

  [3198/20519] intraday_11998.csv.gz  in=209,218,945 out=12,768,171 elapsed=67.3s

  [3199/20519] intraday_11999.csv.gz  in=209,230,846 out=12,780,072 elapsed=67.4s

  [3200/20519] intraday_1200.csv.gz  in=209,254,102 out=12,780,072 elapsed=67.4s

  [3201/20519] intraday_12000.csv.gz  in=209,266,589 out=12,792,559 elapsed=67.4s

  [3202/20519] intraday_12001.csv.gz  in=209,279,170 out=12,805,140 elapsed=67.4s

  [3203/20519] intraday_12003.csv.gz  in=209,291,821 out=12,817,791 elapsed=67.4s

  [3204/20519] intraday_12002.csv.gz  in=209,301,994 out=12,827,964 elapsed=67.4s

  [3205/20519] intraday_12004.csv.gz  in=209,312,779 out=12,838,749 elapsed=67.4s

  [3206/20519] intraday_12005.csv.gz  in=209,323,494 out=12,849,464 elapsed=67.4s

  [3207/20519] intraday_12006.csv.gz  in=209,336,323 out=12,862,293 elapsed=67.5s

  [3208/20519] intraday_12007.csv.gz  in=209,349,876 out=12,875,846 elapsed=67.5s

  [3209/20519] intraday_12008.csv.gz  in=209,362,220 out=12,888,190 elapsed=67.5s

  [3210/20519] intraday_12009.csv.gz  in=209,375,062 out=12,901,032 elapsed=67.5s

  [3211/20519] intraday_1201.csv.gz  in=209,388,192 out=12,901,032 elapsed=67.5s

  [3212/20519] intraday_12010.csv.gz  in=209,401,071 out=12,913,911 elapsed=67.5s

  [3213/20519] intraday_12011.csv.gz  in=209,411,445 out=12,924,285 elapsed=67.6s

  [3214/20519] intraday_12013.csv.gz  in=209,424,024 out=12,936,864 elapsed=67.6s

  [3215/20519] intraday_12012.csv.gz  in=209,436,059 out=12,948,899 elapsed=67.6s

  [3216/20519] intraday_12014.csv.gz  in=209,447,465 out=12,960,305 elapsed=67.6s

  [3217/20519] intraday_12016.csv.gz  in=209,459,365 out=12,972,205 elapsed=67.6s

  [3218/20519] intraday_12017.csv.gz  in=209,469,204 out=12,982,044 elapsed=67.6s

  [3219/20519] intraday_12015.csv.gz  in=209,481,183 out=12,994,023 elapsed=67.6s

  [3220/20519] intraday_12018.csv.gz  in=209,492,432 out=13,005,272 elapsed=67.6s

  [3221/20519] intraday_1202.csv.gz  in=209,505,942 out=13,005,272 elapsed=67.7s

  [3222/20519] intraday_12019.csv.gz  in=209,528,204 out=13,021,393 elapsed=67.7s

  [3223/20519] intraday_12020.csv.gz  in=209,541,855 out=13,035,044 elapsed=67.7s

  [3224/20519] intraday_12023.csv.gz  in=209,552,176 out=13,045,365 elapsed=67.7s

  [3225/20519] intraday_12021.csv.gz  in=209,566,373 out=13,059,562 elapsed=67.7s

  [3226/20519] intraday_12022.csv.gz  in=209,578,818 out=13,072,007 elapsed=67.7s

  [3227/20519] intraday_12024.csv.gz  in=209,590,705 out=13,083,894 elapsed=67.7s

  [3228/20519] intraday_12025.csv.gz  in=209,603,563 out=13,096,752 elapsed=67.8s

  [3229/20519] intraday_12027.csv.gz  in=209,617,699 out=13,110,888 elapsed=67.8s

  [3230/20519] intraday_12026.csv.gz  in=209,630,256 out=13,123,445 elapsed=67.8s

  [3231/20519] intraday_12028.csv.gz  in=209,642,574 out=13,135,763 elapsed=67.8s

  [3232/20519] intraday_12029.csv.gz  in=209,653,430 out=13,146,619 elapsed=67.8s

  [3233/20519] intraday_1203.csv.gz  in=209,666,902 out=13,146,619 elapsed=67.8s

  [3234/20519] intraday_12030.csv.gz  in=209,677,742 out=13,157,459 elapsed=67.8s

  [3235/20519] intraday_12031.csv.gz  in=209,691,451 out=13,171,168 elapsed=67.8s

  [3236/20519] intraday_12032.csv.gz  in=209,703,522 out=13,183,239 elapsed=67.9s

  [3237/20519] intraday_12033.csv.gz  in=209,715,339 out=13,195,056 elapsed=67.9s

  [3238/20519] intraday_12035.csv.gz  in=209,724,935 out=13,204,652 elapsed=67.9s

  [3239/20519] intraday_12036.csv.gz  in=209,736,972 out=13,216,689 elapsed=67.9s

  [3240/20519] intraday_12034.csv.gz  in=209,747,534 out=13,227,251 elapsed=67.9s

  [3241/20519] intraday_12037.csv.gz  in=209,763,158 out=13,242,875 elapsed=67.9s

  [3242/20519] intraday_12039.csv.gz  in=209,776,340 out=13,256,057 elapsed=68.0s

  [3243/20519] intraday_12038.csv.gz  in=209,794,995 out=13,274,712 elapsed=68.0s

  [3244/20519] intraday_1204.csv.gz  in=209,806,090 out=13,274,712 elapsed=68.0s

  [3245/20519] intraday_12040.csv.gz  in=209,817,883 out=13,286,505 elapsed=68.0s

  [3246/20519] intraday_12042.csv.gz  in=209,831,704 out=13,300,326 elapsed=68.0s

  [3247/20519] intraday_12041.csv.gz  in=209,842,147 out=13,310,769 elapsed=68.0s

  [3248/20519] intraday_12044.csv.gz  in=209,857,594 out=13,326,216 elapsed=68.0s

  [3249/20519] intraday_12045.csv.gz  in=209,867,905 out=13,336,527 elapsed=68.0s

  [3250/20519] intraday_12043.csv.gz  in=209,878,945 out=13,347,567 elapsed=68.0s

  [3251/20519] intraday_12046.csv.gz  in=209,890,853 out=13,359,475 elapsed=68.1s

  [3252/20519] intraday_1205.csv.gz  in=209,904,937 out=13,359,475 elapsed=68.1s

  [3253/20519] intraday_12049.csv.gz  in=209,917,573 out=13,372,111 elapsed=68.1s

  [3254/20519] intraday_12048.csv.gz  in=209,931,522 out=13,386,060 elapsed=68.1s

  [3255/20519] intraday_12047.csv.gz  in=209,945,820 out=13,400,358 elapsed=68.2s

  [3256/20519] intraday_12050.csv.gz  in=209,958,429 out=13,412,967 elapsed=68.2s

  [3257/20519] intraday_12052.csv.gz  in=209,969,408 out=13,423,946 elapsed=68.2s

  [3258/20519] intraday_12051.csv.gz  in=209,982,484 out=13,437,022 elapsed=68.2s

  [3259/20519] intraday_12054.csv.gz  in=209,995,861 out=13,450,399 elapsed=68.2s

  [3260/20519] intraday_12055.csv.gz  in=210,007,878 out=13,462,416 elapsed=68.2s

  [3261/20519] intraday_12053.csv.gz  in=210,018,871 out=13,473,409 elapsed=68.2s

  [3262/20519] intraday_12057.csv.gz  in=210,032,407 out=13,486,945 elapsed=68.3s

  [3263/20519] intraday_12056.csv.gz  in=210,044,646 out=13,499,184 elapsed=68.3s

  [3264/20519] intraday_12059.csv.gz  in=210,056,470 out=13,511,008 elapsed=68.3s

  [3265/20519] intraday_12058.csv.gz  in=210,068,904 out=13,523,442 elapsed=68.3s

  [3266/20519] intraday_1206.csv.gz  in=210,086,572 out=13,523,442 elapsed=68.3s

  [3267/20519] intraday_12060.csv.gz  in=210,099,628 out=13,536,498 elapsed=68.3s

  [3268/20519] intraday_12062.csv.gz  in=210,111,855 out=13,548,725 elapsed=68.3s

  [3269/20519] intraday_12063.csv.gz  in=210,124,182 out=13,561,052 elapsed=68.4s

  [3270/20519] intraday_12061.csv.gz  in=210,137,876 out=13,574,746 elapsed=68.4s

  [3271/20519] intraday_12064.csv.gz  in=210,151,299 out=13,588,169 elapsed=68.4s

  [3272/20519] intraday_12065.csv.gz  in=210,165,103 out=13,601,973 elapsed=68.4s

  [3273/20519] intraday_12066.csv.gz  in=210,175,978 out=13,612,848 elapsed=68.4s

  [3274/20519] intraday_12067.csv.gz  in=210,190,249 out=13,627,119 elapsed=68.4s

  [3275/20519] intraday_12068.csv.gz  in=210,208,436 out=13,645,306 elapsed=68.4s

  [3276/20519] intraday_1207.csv.gz  in=210,220,915 out=13,645,306 elapsed=68.4s

  [3277/20519] intraday_12069.csv.gz  in=210,234,461 out=13,658,852 elapsed=68.4s

  [3278/20519] intraday_12070.csv.gz  in=210,249,563 out=13,673,954 elapsed=68.5s

  [3279/20519] intraday_12072.csv.gz  in=210,264,450 out=13,688,841 elapsed=68.5s

  [3280/20519] intraday_12073.csv.gz  in=210,280,010 out=13,704,401 elapsed=68.5s

  [3281/20519] intraday_12071.csv.gz  in=210,296,936 out=13,721,327 elapsed=68.5s

  [3282/20519] intraday_12074.csv.gz  in=210,312,419 out=13,736,331 elapsed=68.6s

  [3283/20519] intraday_12075.csv.gz  in=210,324,773 out=13,748,685 elapsed=68.6s

  [3284/20519] intraday_12076.csv.gz  in=210,337,851 out=13,761,763 elapsed=68.6s

  [3285/20519] intraday_12077.csv.gz  in=210,349,982 out=13,773,894 elapsed=68.6s

  [3286/20519] intraday_12078.csv.gz  in=210,362,049 out=13,785,961 elapsed=68.6s

  [3287/20519] intraday_12079.csv.gz  in=210,373,950 out=13,797,862 elapsed=68.6s

  [3288/20519] intraday_1208.csv.gz  in=210,398,877 out=13,797,862 elapsed=68.6s

  [3289/20519] intraday_12080.csv.gz  in=210,411,414 out=13,810,399 elapsed=68.6s

  [3290/20519] intraday_12081.csv.gz  in=210,424,427 out=13,823,412 elapsed=68.6s

  [3291/20519] intraday_12082.csv.gz  in=210,439,637 out=13,838,622 elapsed=68.7s

  [3292/20519] intraday_12083.csv.gz  in=210,451,538 out=13,850,523 elapsed=68.7s

  [3293/20519] intraday_12084.csv.gz  in=210,462,154 out=13,861,139 elapsed=68.7s

  [3294/20519] intraday_12086.csv.gz  in=210,472,824 out=13,871,809 elapsed=68.7s

  [3295/20519] intraday_12085.csv.gz  in=210,485,895 out=13,884,880 elapsed=68.7s

  [3296/20519] intraday_12088.csv.gz  in=210,500,188 out=13,899,173 elapsed=68.7s

  [3297/20519] intraday_12089.csv.gz  in=210,515,823 out=13,914,808 elapsed=68.8s

  [3298/20519] intraday_1209.csv.gz  in=210,533,146 out=13,914,808 elapsed=68.8s

  [3299/20519] intraday_12087.csv.gz  in=210,545,934 out=13,927,596 elapsed=68.8s

  [3300/20519] intraday_12090.csv.gz  in=210,560,042 out=13,941,704 elapsed=68.8s

  [3301/20519] intraday_12092.csv.gz  in=210,572,127 out=13,953,789 elapsed=68.8s

  [3302/20519] intraday_12093.csv.gz  in=210,584,993 out=13,966,655 elapsed=68.8s

  [3303/20519] intraday_12091.csv.gz  in=210,599,329 out=13,980,991 elapsed=68.8s

  [3304/20519] intraday_12094.csv.gz  in=210,611,162 out=13,992,824 elapsed=68.8s

  [3305/20519] intraday_12095.csv.gz  in=210,626,795 out=14,006,471 elapsed=68.9s

  [3306/20519] intraday_12096.csv.gz  in=210,635,748 out=14,015,424 elapsed=68.9s

  [3307/20519] intraday_12097.csv.gz  in=210,642,871 out=14,022,547 elapsed=68.9s

  [3308/20519] intraday_12098.csv.gz  in=210,654,864 out=14,034,540 elapsed=68.9s

  [3309/20519] intraday_12099.csv.gz  in=210,660,731 out=14,040,407 elapsed=68.9s

  [3310/20519] intraday_1210.csv.gz  in=210,693,168 out=14,040,407 elapsed=68.9s

  [3311/20519] intraday_12101.csv.gz  in=210,952,363 out=14,062,898 elapsed=69.1s

  [3312/20519] intraday_12100.csv.gz  in=211,280,064 out=14,096,192 elapsed=69.2s

  [3313/20519] intraday_12103.csv.gz  in=211,520,049 out=14,116,908 elapsed=69.2s

  [3314/20519] intraday_12102.csv.gz  in=211,820,512 out=14,143,249 elapsed=69.2s

  [3315/20519] intraday_12104.csv.gz  in=212,141,509 out=14,168,044 elapsed=69.4s

  [3316/20519] intraday_12105.csv.gz  in=212,455,718 out=14,196,490 elapsed=69.4s

  [3317/20519] intraday_12107.csv.gz  in=212,725,299 out=14,220,697 elapsed=69.5s

  [3318/20519] intraday_1211.csv.gz  in=212,737,115 out=14,220,697 elapsed=69.5s

  [3319/20519] intraday_12106.csv.gz  in=213,064,749 out=14,251,567 elapsed=69.5s

  [3320/20519] intraday_12108.csv.gz  in=213,365,675 out=14,276,533 elapsed=69.6s

  [3321/20519] intraday_12109.csv.gz  in=213,663,648 out=14,301,223 elapsed=69.7s

  [3322/20519] intraday_12110.csv.gz  in=213,978,055 out=14,325,711 elapsed=69.8s

  [3323/20519] intraday_12111.csv.gz  in=214,254,888 out=14,349,872 elapsed=69.8s

  [3324/20519] intraday_12112.csv.gz  in=214,518,587 out=14,377,422 elapsed=69.8s

  [3325/20519] intraday_12113.csv.gz  in=214,805,837 out=14,403,869 elapsed=69.9s

  [3326/20519] intraday_12115.csv.gz  in=215,036,527 out=14,426,920 elapsed=70.0s

  [3327/20519] intraday_12114.csv.gz  in=215,251,420 out=14,446,834 elapsed=70.0s

  [3328/20519] intraday_12116.csv.gz  in=215,572,984 out=14,476,128 elapsed=70.1s

  [3329/20519] intraday_1212.csv.gz  in=215,588,821 out=14,476,128 elapsed=70.1s

  [3330/20519] intraday_12117.csv.gz  in=215,886,215 out=14,501,387 elapsed=70.2s

  [3331/20519] intraday_12119.csv.gz  in=216,111,151 out=14,521,814 elapsed=70.2s

  [3332/20519] intraday_12118.csv.gz  in=216,363,515 out=14,543,353 elapsed=70.2s

  [3333/20519] intraday_12120.csv.gz  in=216,642,107 out=14,566,183 elapsed=70.4s

  [3334/20519] intraday_12122.csv.gz  in=216,893,223 out=14,592,296 elapsed=70.5s

  [3335/20519] intraday_12121.csv.gz  in=217,160,061 out=14,616,521 elapsed=70.5s

  [3336/20519] intraday_12123.csv.gz  in=217,441,091 out=14,643,987 elapsed=70.5s

  [3337/20519] intraday_12124.csv.gz  in=217,720,659 out=14,669,924 elapsed=70.6s

  [3338/20519] intraday_12126.csv.gz  in=217,944,699 out=14,691,599 elapsed=70.7s

  [3339/20519] intraday_12125.csv.gz  in=218,194,535 out=14,714,820 elapsed=70.7s

  [3340/20519] intraday_1213.csv.gz  in=218,216,224 out=14,714,820 elapsed=70.7s

  [3341/20519] intraday_12127.csv.gz  in=218,481,451 out=14,738,778 elapsed=70.8s

  [3342/20519] intraday_12128.csv.gz  in=218,733,193 out=14,761,645 elapsed=70.9s

  [3343/20519] intraday_12129.csv.gz  in=219,025,493 out=14,787,639 elapsed=70.9s

  [3344/20519] intraday_12131.csv.gz  in=219,297,836 out=14,812,664 elapsed=71.0s

  [3345/20519] intraday_12130.csv.gz  in=219,683,536 out=14,842,911 elapsed=71.0s

  [3346/20519] intraday_12132.csv.gz  in=219,916,195 out=14,863,167 elapsed=71.0s

  [3347/20519] intraday_12133.csv.gz  in=220,214,766 out=14,889,913 elapsed=71.2s

  [3348/20519] intraday_12134.csv.gz  in=220,507,376 out=14,916,095 elapsed=71.3s

  [3349/20519] intraday_12135.csv.gz  in=220,761,145 out=14,940,769 elapsed=71.3s

  [3350/20519] intraday_12136.csv.gz  in=221,017,636 out=14,965,408 elapsed=71.3s

  [3351/20519] intraday_1214.csv.gz  in=221,033,314 out=14,965,408 elapsed=71.3s

  [3352/20519] intraday_12137.csv.gz  in=221,257,801 out=14,985,336 elapsed=71.4s

  [3353/20519] intraday_12139.csv.gz  in=221,484,570 out=15,007,435 elapsed=71.5s

  [3354/20519] intraday_12138.csv.gz  in=221,775,397 out=15,031,410 elapsed=71.5s

  [3355/20519] intraday_12140.csv.gz  in=222,020,234 out=15,052,862 elapsed=71.5s

  [3356/20519] intraday_12141.csv.gz  in=222,291,389 out=15,077,036 elapsed=71.6s

  [3357/20519] intraday_12142.csv.gz  in=222,558,052 out=15,101,354 elapsed=71.7s

  [3358/20519] intraday_12143.csv.gz  in=222,834,841 out=15,126,416 elapsed=71.7s

  [3359/20519] intraday_12144.csv.gz  in=223,139,207 out=15,153,977 elapsed=71.8s

  [3360/20519] intraday_12145.csv.gz  in=223,382,869 out=15,177,385 elapsed=71.8s

  [3361/20519] intraday_12146.csv.gz  in=223,626,012 out=15,199,443 elapsed=71.9s

  [3362/20519] intraday_1215.csv.gz  in=223,638,830 out=15,199,443 elapsed=71.9s

  [3363/20519] intraday_12147.csv.gz  in=223,928,735 out=15,225,539 elapsed=72.0s

  [3364/20519] intraday_12148.csv.gz  in=224,146,376 out=15,246,399 elapsed=72.0s

  [3365/20519] intraday_12149.csv.gz  in=224,385,444 out=15,269,432 elapsed=72.0s

  [3366/20519] intraday_12150.csv.gz  in=224,629,207 out=15,292,097 elapsed=72.2s

  [3367/20519] intraday_12151.csv.gz  in=224,849,074 out=15,312,380 elapsed=72.2s

  [3368/20519] intraday_12153.csv.gz  in=225,090,563 out=15,333,653 elapsed=72.3s

  [3369/20519] intraday_12152.csv.gz  in=225,427,243 out=15,361,676 elapsed=72.3s

  [3370/20519] intraday_12154.csv.gz  in=225,680,141 out=15,385,532 elapsed=72.4s

  [3371/20519] intraday_12155.csv.gz  in=225,987,689 out=15,413,688 elapsed=72.5s

  [3372/20519] intraday_12156.csv.gz  in=226,270,380 out=15,439,314 elapsed=72.5s

  [3373/20519] intraday_1216.csv.gz  in=226,284,799 out=15,439,314 elapsed=72.5s

  [3374/20519] intraday_12157.csv.gz  in=226,537,923 out=15,461,963 elapsed=72.5s

  [3375/20519] intraday_12158.csv.gz  in=226,807,839 out=15,485,561 elapsed=72.6s

  [3376/20519] intraday_12159.csv.gz  in=227,052,218 out=15,508,360 elapsed=72.7s

  [3377/20519] intraday_12161.csv.gz  in=227,290,102 out=15,530,774 elapsed=72.7s

  [3378/20519] intraday_12160.csv.gz  in=227,595,707 out=15,556,001 elapsed=72.7s

  [3379/20519] intraday_12162.csv.gz  in=227,847,719 out=15,579,016 elapsed=72.8s

  [3380/20519] intraday_12163.csv.gz  in=228,099,372 out=15,601,972 elapsed=72.9s

  [3381/20519] intraday_12164.csv.gz  in=228,320,836 out=15,622,018 elapsed=72.9s

  [3382/20519] intraday_12165.csv.gz  in=228,626,606 out=15,652,780 elapsed=73.0s

  [3383/20519] intraday_12166.csv.gz  in=228,930,578 out=15,680,962 elapsed=73.0s

  [3384/20519] intraday_1217.csv.gz  in=228,945,018 out=15,680,962 elapsed=73.1s

  [3385/20519] intraday_12168.csv.gz  in=229,213,729 out=15,706,358 elapsed=73.1s

  [3386/20519] intraday_12167.csv.gz  in=229,486,216 out=15,731,544 elapsed=73.1s

  [3387/20519] intraday_12169.csv.gz  in=229,750,975 out=15,755,743 elapsed=73.3s

  [3388/20519] intraday_12170.csv.gz  in=229,956,041 out=15,775,131 elapsed=73.3s

  [3389/20519] intraday_12172.csv.gz  in=230,213,790 out=15,800,613 elapsed=73.4s

  [3390/20519] intraday_12171.csv.gz  in=230,486,328 out=15,826,425 elapsed=73.4s

  [3391/20519] intraday_12173.csv.gz  in=230,760,392 out=15,853,657 elapsed=73.6s

  [3392/20519] intraday_12174.csv.gz  in=231,031,301 out=15,881,282 elapsed=73.6s

  [3393/20519] intraday_12176.csv.gz  in=231,280,190 out=15,901,542 elapsed=73.6s

  [3394/20519] intraday_12175.csv.gz  in=231,524,937 out=15,924,276 elapsed=73.7s

  [3395/20519] intraday_1218.csv.gz  in=231,547,219 out=15,924,276 elapsed=73.7s

  [3396/20519] intraday_12177.csv.gz  in=231,811,347 out=15,948,289 elapsed=73.8s

  [3397/20519] intraday_12178.csv.gz  in=232,081,654 out=15,973,042 elapsed=73.8s

  [3398/20519] intraday_12179.csv.gz  in=232,341,082 out=15,996,924 elapsed=73.8s

  [3399/20519] intraday_12180.csv.gz  in=232,613,557 out=16,020,890 elapsed=73.9s

  [3400/20519] intraday_12181.csv.gz  in=232,807,775 out=16,040,626 elapsed=74.0s

  [3401/20519] intraday_12182.csv.gz  in=233,053,758 out=16,061,805 elapsed=74.0s

  [3402/20519] intraday_12183.csv.gz  in=233,325,233 out=16,086,156 elapsed=74.1s

  [3403/20519] intraday_12185.csv.gz  in=233,652,829 out=16,120,899 elapsed=74.2s

  [3404/20519] intraday_12184.csv.gz  in=234,028,631 out=16,156,248 elapsed=74.3s

  [3405/20519] intraday_12186.csv.gz  in=234,317,159 out=16,184,153 elapsed=74.3s

  [3406/20519] intraday_12187.csv.gz  in=234,582,935 out=16,207,945 elapsed=74.3s

  [3407/20519] intraday_1219.csv.gz  in=234,596,994 out=16,207,945 elapsed=74.3s

  [3408/20519] intraday_12189.csv.gz  in=234,879,017 out=16,231,831 elapsed=74.5s

  [3409/20519] intraday_12188.csv.gz  in=235,149,352 out=16,255,342 elapsed=74.6s

  [3410/20519] intraday_12191.csv.gz  in=235,396,811 out=16,278,072 elapsed=74.6s

  [3411/20519] intraday_12190.csv.gz  in=235,746,650 out=16,308,481 elapsed=74.7s

  [3412/20519] intraday_12192.csv.gz  in=236,002,200 out=16,329,483 elapsed=74.7s

  [3413/20519] intraday_12193.csv.gz  in=236,303,666 out=16,356,835 elapsed=74.8s

  [3414/20519] intraday_12194.csv.gz  in=236,603,410 out=16,384,075 elapsed=74.9s

  [3415/20519] intraday_12195.csv.gz  in=236,903,274 out=16,410,317 elapsed=74.9s

  [3416/20519] intraday_12196.csv.gz  in=237,158,842 out=16,434,070 elapsed=74.9s

  [3417/20519] intraday_1220.csv.gz  in=237,179,804 out=16,434,070 elapsed=75.0s

  [3418/20519] intraday_12197.csv.gz  in=237,442,844 out=16,456,927 elapsed=75.0s

  [3419/20519] intraday_12198.csv.gz  in=237,713,074 out=16,481,683 elapsed=75.1s

  [3420/20519] intraday_12199.csv.gz  in=237,955,374 out=16,500,535 elapsed=75.1s

  [3421/20519] intraday_12200.csv.gz  in=238,290,213 out=16,528,320 elapsed=75.2s

  [3422/20519] intraday_12201.csv.gz  in=238,518,712 out=16,547,560 elapsed=75.2s

  [3423/20519] intraday_12202.csv.gz  in=238,805,947 out=16,573,192 elapsed=75.3s

  [3424/20519] intraday_12203.csv.gz  in=239,120,049 out=16,601,498 elapsed=75.4s

  [3425/20519] intraday_12205.csv.gz  in=239,351,960 out=16,628,045 elapsed=75.4s

  [3426/20519] intraday_12204.csv.gz  in=239,646,734 out=16,652,322 elapsed=75.4s

  [3427/20519] intraday_12206.csv.gz  in=239,920,235 out=16,676,961 elapsed=75.5s

  [3428/20519] intraday_1221.csv.gz  in=239,935,724 out=16,676,961 elapsed=75.5s

  [3429/20519] intraday_12207.csv.gz  in=240,268,815 out=16,707,318 elapsed=75.6s

  [3430/20519] intraday_12208.csv.gz  in=240,535,572 out=16,730,486 elapsed=75.7s

  [3431/20519] intraday_12209.csv.gz  in=240,788,048 out=16,752,420 elapsed=75.7s

  [3432/20519] intraday_12210.csv.gz  in=241,121,091 out=16,781,501 elapsed=75.8s

  [3433/20519] intraday_12212.csv.gz  in=241,387,749 out=16,804,296 elapsed=75.9s

  [3434/20519] intraday_12211.csv.gz  in=241,706,007 out=16,833,965 elapsed=75.9s

  [3435/20519] intraday_12213.csv.gz  in=241,982,222 out=16,859,708 elapsed=75.9s

  [3436/20519] intraday_12214.csv.gz  in=242,251,198 out=16,895,064 elapsed=76.0s

  [3437/20519] intraday_12215.csv.gz  in=242,491,876 out=16,918,473 elapsed=76.1s

  [3438/20519] intraday_12216.csv.gz  in=242,821,382 out=16,946,912 elapsed=76.2s

  [3439/20519] intraday_1222.csv.gz  in=242,833,510 out=16,946,912 elapsed=76.2s

  [3440/20519] intraday_12217.csv.gz  in=243,173,542 out=16,978,060 elapsed=76.2s

  [3441/20519] intraday_12218.csv.gz  in=243,467,450 out=17,013,131 elapsed=76.3s

  [3442/20519] intraday_12219.csv.gz  in=243,765,136 out=17,041,749 elapsed=76.3s

  [3443/20519] intraday_12221.csv.gz  in=243,995,494 out=17,067,030 elapsed=76.5s

  [3444/20519] intraday_12220.csv.gz  in=244,335,193 out=17,098,147 elapsed=76.5s

  [3445/20519] intraday_12223.csv.gz  in=244,565,889 out=17,120,066 elapsed=76.5s

  [3446/20519] intraday_12222.csv.gz  in=244,833,073 out=17,144,409 elapsed=76.6s

  [3447/20519] intraday_12225.csv.gz  in=245,067,482 out=17,165,560 elapsed=76.7s

  [3448/20519] intraday_12224.csv.gz  in=245,373,590 out=17,193,172 elapsed=76.7s

  [3449/20519] intraday_12226.csv.gz  in=245,683,492 out=17,221,109 elapsed=76.8s

  [3450/20519] intraday_12227.csv.gz  in=245,960,860 out=17,247,500 elapsed=76.8s

  [3451/20519] intraday_1223.csv.gz  in=245,974,321 out=17,247,500 elapsed=76.8s

  [3452/20519] intraday_12229.csv.gz  in=246,230,009 out=17,269,962 elapsed=77.0s

  [3453/20519] intraday_12228.csv.gz  in=246,568,706 out=17,299,507 elapsed=77.0s

  [3454/20519] intraday_12230.csv.gz  in=246,831,158 out=17,321,007 elapsed=77.0s

  [3455/20519] intraday_12231.csv.gz  in=247,093,409 out=17,343,869 elapsed=77.1s

  [3456/20519] intraday_12233.csv.gz  in=247,329,262 out=17,365,156 elapsed=77.2s

  [3457/20519] intraday_12232.csv.gz  in=247,648,535 out=17,391,041 elapsed=77.3s

  [3458/20519] intraday_12234.csv.gz  in=247,921,041 out=17,416,576 elapsed=77.3s

  [3459/20519] intraday_12235.csv.gz  in=248,242,467 out=17,448,500 elapsed=77.4s

  [3460/20519] intraday_12236.csv.gz  in=248,535,824 out=17,474,730 elapsed=77.5s

  [3461/20519] intraday_12238.csv.gz  in=248,791,316 out=17,498,820 elapsed=77.5s

  [3462/20519] intraday_1224.csv.gz  in=248,803,244 out=17,498,820 elapsed=77.5s

  [3463/20519] intraday_12237.csv.gz  in=249,126,005 out=17,529,973 elapsed=77.5s

  [3464/20519] intraday_12239.csv.gz  in=249,374,765 out=17,553,604 elapsed=77.6s

  [3465/20519] intraday_12241.csv.gz  in=249,625,485 out=17,576,621 elapsed=77.7s

  [3466/20519] intraday_12243.csv.gz  in=249,833,578 out=17,591,385 elapsed=77.8s

  [3467/20519] intraday_12240.csv.gz  in=250,111,178 out=17,614,774 elapsed=77.8s

  [3468/20519] intraday_12246.csv.gz  in=250,114,964 out=17,615,078 elapsed=77.8s

  [3469/20519] intraday_12242.csv.gz  in=250,410,235 out=17,639,347 elapsed=77.8s

  [3470/20519] intraday_12248.csv.gz  in=250,411,470 out=17,639,489 elapsed=77.8s

  [3471/20519] intraday_12247.csv.gz  in=250,413,885 out=17,640,007 elapsed=77.8s

  [3472/20519] intraday_12249.csv.gz  in=250,418,594 out=17,641,451 elapsed=77.9s

  [3473/20519] intraday_1225.csv.gz  in=250,431,435 out=17,641,451 elapsed=77.9s

  [3474/20519] intraday_12250.csv.gz  in=250,439,526 out=17,642,232 elapsed=77.9s

  [3475/20519] intraday_12251.csv.gz  in=250,440,045 out=17,642,298 elapsed=77.9s

  [3476/20519] intraday_12253.csv.gz  in=250,452,847 out=17,645,684 elapsed=77.9s

  [3477/20519] intraday_12252.csv.gz  in=250,453,842 out=17,645,944 elapsed=77.9s

  [3478/20519] intraday_12244.csv.gz  in=250,649,909 out=17,664,902 elapsed=77.9s

  [3479/20519] intraday_12254.csv.gz  in=250,652,969 out=17,665,189 elapsed=78.0s

  [3480/20519] intraday_12255.csv.gz  in=250,653,186 out=17,665,220 elapsed=78.0s

  [3481/20519] intraday_12256.csv.gz  in=250,654,836 out=17,665,741 elapsed=78.0s

  [3482/20519] intraday_12257.csv.gz  in=250,655,726 out=17,665,840 elapsed=78.0s

  [3483/20519] intraday_12258.csv.gz  in=250,658,148 out=17,666,068 elapsed=78.0s

  [3484/20519] intraday_12245.csv.gz  in=250,932,259 out=17,693,047 elapsed=78.0s

  [3485/20519] intraday_12260.csv.gz  in=250,932,524 out=17,693,179 elapsed=78.0s

  [3486/20519] intraday_12259.csv.gz  in=250,932,639 out=17,693,181 elapsed=78.0s

  [3487/20519] intraday_1226.csv.gz  in=250,943,267 out=17,693,181 elapsed=78.0s

  [3488/20519] intraday_12262.csv.gz  in=250,944,485 out=17,693,416 elapsed=78.0s

  [3489/20519] intraday_12263.csv.gz  in=250,950,872 out=17,695,581 elapsed=78.0s

  [3490/20519] intraday_12261.csv.gz  in=250,951,712 out=17,695,660 elapsed=78.0s

  [3491/20519] intraday_12264.csv.gz  in=250,951,802 out=17,695,673 elapsed=78.1s

  [3492/20519] intraday_12266.csv.gz  in=250,954,981 out=17,696,037 elapsed=78.1s

  [3493/20519] intraday_12265.csv.gz  in=250,956,829 out=17,696,481 elapsed=78.1s

  [3494/20519] intraday_12267.csv.gz  in=250,957,297 out=17,696,481 elapsed=78.1s

  [3495/20519] intraday_12268.csv.gz  in=250,960,177 out=17,696,765 elapsed=78.1s

  [3496/20519] intraday_12269.csv.gz  in=250,963,823 out=17,697,964 elapsed=78.1s

  [3497/20519] intraday_12270.csv.gz  in=250,965,549 out=17,698,198 elapsed=78.1s

  [3498/20519] intraday_1227.csv.gz  in=250,979,780 out=17,698,198 elapsed=78.1s

  [3499/20519] intraday_12273.csv.gz  in=250,984,639 out=17,698,198 elapsed=78.1s

  [3500/20519] intraday_12272.csv.gz  in=250,986,868 out=17,698,676 elapsed=78.1s

  [3501/20519] intraday_12271.csv.gz  in=250,993,699 out=17,699,886 elapsed=78.1s

  [3502/20519] intraday_12274.csv.gz  in=250,994,258 out=17,700,026 elapsed=78.1s

  [3503/20519] intraday_12275.csv.gz  in=250,994,745 out=17,700,084 elapsed=78.2s

  [3504/20519] intraday_12277.csv.gz  in=251,007,885 out=17,713,224 elapsed=78.2s

  [3505/20519] intraday_12276.csv.gz  in=251,024,319 out=17,729,658 elapsed=78.2s

  [3506/20519] intraday_12279.csv.gz  in=251,034,671 out=17,740,010 elapsed=78.2s

  [3507/20519] intraday_12278.csv.gz  in=251,047,083 out=17,752,422 elapsed=78.2s

  [3508/20519] intraday_1228.csv.gz  in=251,055,347 out=17,752,422 elapsed=78.3s

  [3509/20519] intraday_12281.csv.gz  in=251,070,538 out=17,767,613 elapsed=78.3s

  [3510/20519] intraday_12280.csv.gz  in=251,082,854 out=17,779,929 elapsed=78.3s

  [3511/20519] intraday_12282.csv.gz  in=251,097,079 out=17,794,154 elapsed=78.4s

  [3512/20519] intraday_12284.csv.gz  in=251,110,118 out=17,807,193 elapsed=78.4s

  [3513/20519] intraday_12285.csv.gz  in=251,123,088 out=17,820,163 elapsed=78.4s

  [3514/20519] intraday_12283.csv.gz  in=251,135,959 out=17,833,034 elapsed=78.4s

  [3515/20519] intraday_12286.csv.gz  in=251,148,219 out=17,845,294 elapsed=78.4s

  [3516/20519] intraday_12287.csv.gz  in=251,160,056 out=17,857,131 elapsed=78.4s

  [3517/20519] intraday_12288.csv.gz  in=251,174,256 out=17,871,331 elapsed=78.5s

  [3518/20519] intraday_12289.csv.gz  in=251,188,333 out=17,885,408 elapsed=78.5s

  [3519/20519] intraday_12290.csv.gz  in=251,198,850 out=17,895,925 elapsed=78.5s

  [3520/20519] intraday_1229.csv.gz  in=251,209,547 out=17,895,925 elapsed=78.5s

  [3521/20519] intraday_12291.csv.gz  in=251,219,712 out=17,906,090 elapsed=78.5s

  [3522/20519] intraday_12294.csv.gz  in=251,231,271 out=17,917,649 elapsed=78.5s

  [3523/20519] intraday_12292.csv.gz  in=251,245,604 out=17,931,982 elapsed=78.5s

  [3524/20519] intraday_12293.csv.gz  in=251,258,187 out=17,944,565 elapsed=78.5s

  [3525/20519] intraday_12295.csv.gz  in=251,269,475 out=17,955,853 elapsed=78.6s

  [3526/20519] intraday_12296.csv.gz  in=251,280,333 out=17,966,711 elapsed=78.6s

  [3527/20519] intraday_12297.csv.gz  in=251,292,955 out=17,979,333 elapsed=78.6s

  [3528/20519] intraday_12299.csv.gz  in=251,304,024 out=17,990,402 elapsed=78.6s

  [3529/20519] intraday_1230.csv.gz  in=251,315,620 out=17,990,402 elapsed=78.6s

  [3530/20519] intraday_12298.csv.gz  in=251,329,037 out=18,003,819 elapsed=78.6s

  [3531/20519] intraday_12300.csv.gz  in=251,341,564 out=18,016,346 elapsed=78.6s

  [3532/20519] intraday_12301.csv.gz  in=251,352,971 out=18,027,753 elapsed=78.7s

  [3533/20519] intraday_12303.csv.gz  in=251,364,600 out=18,039,382 elapsed=78.7s

  [3534/20519] intraday_12302.csv.gz  in=251,377,237 out=18,052,019 elapsed=78.7s

  [3535/20519] intraday_12304.csv.gz  in=251,389,006 out=18,063,788 elapsed=78.7s

  [3536/20519] intraday_12307.csv.gz  in=251,402,438 out=18,077,220 elapsed=78.7s

  [3537/20519] intraday_12305.csv.gz  in=251,415,600 out=18,090,382 elapsed=78.7s

  [3538/20519] intraday_12306.csv.gz  in=251,430,606 out=18,105,388 elapsed=78.8s

  [3539/20519] intraday_12308.csv.gz  in=251,440,822 out=18,115,604 elapsed=78.8s

  [3540/20519] intraday_12309.csv.gz  in=251,454,947 out=18,129,729 elapsed=78.8s

  [3541/20519] intraday_12310.csv.gz  in=251,468,243 out=18,143,025 elapsed=78.8s

  [3542/20519] intraday_1231.csv.gz  in=251,483,522 out=18,143,025 elapsed=78.8s

  [3543/20519] intraday_12311.csv.gz  in=251,497,114 out=18,156,617 elapsed=78.8s

  [3544/20519] intraday_12312.csv.gz  in=251,509,522 out=18,169,025 elapsed=78.8s

  [3545/20519] intraday_12314.csv.gz  in=251,522,075 out=18,181,578 elapsed=78.9s

  [3546/20519] intraday_12313.csv.gz  in=251,532,111 out=18,191,614 elapsed=78.9s

  [3547/20519] intraday_12315.csv.gz  in=251,541,659 out=18,201,162 elapsed=78.9s

  [3548/20519] intraday_12316.csv.gz  in=251,552,215 out=18,211,718 elapsed=78.9s

  [3549/20519] intraday_12317.csv.gz  in=251,565,546 out=18,225,049 elapsed=78.9s

  [3550/20519] intraday_1232.csv.gz  in=251,580,059 out=18,225,049 elapsed=78.9s

  [3551/20519] intraday_12319.csv.gz  in=251,592,042 out=18,237,032 elapsed=78.9s

  [3552/20519] intraday_12318.csv.gz  in=251,604,339 out=18,249,329 elapsed=78.9s

  [3553/20519] intraday_12320.csv.gz  in=251,617,915 out=18,262,905 elapsed=78.9s

  [3554/20519] intraday_12321.csv.gz  in=251,630,692 out=18,275,682 elapsed=79.0s

  [3555/20519] intraday_12323.csv.gz  in=251,643,079 out=18,288,069 elapsed=79.0s

  [3556/20519] intraday_12322.csv.gz  in=251,655,392 out=18,300,382 elapsed=79.0s

  [3557/20519] intraday_12324.csv.gz  in=251,670,015 out=18,315,005 elapsed=79.0s

  [3558/20519] intraday_12325.csv.gz  in=251,680,153 out=18,325,143 elapsed=79.0s

  [3559/20519] intraday_12326.csv.gz  in=251,692,034 out=18,337,024 elapsed=79.0s

  [3560/20519] intraday_12327.csv.gz  in=251,701,098 out=18,346,088 elapsed=79.0s

  [3561/20519] intraday_12328.csv.gz  in=251,714,856 out=18,359,846 elapsed=79.1s

  [3562/20519] intraday_12329.csv.gz  in=251,725,211 out=18,370,201 elapsed=79.1s

  [3563/20519] intraday_1233.csv.gz  in=251,736,412 out=18,370,201 elapsed=79.1s

  [3564/20519] intraday_12330.csv.gz  in=251,749,008 out=18,382,797 elapsed=79.1s

  [3565/20519] intraday_12331.csv.gz  in=251,763,356 out=18,397,145 elapsed=79.1s

  [3566/20519] intraday_12333.csv.gz  in=251,774,674 out=18,408,463 elapsed=79.2s

  [3567/20519] intraday_12334.csv.gz  in=251,785,425 out=18,419,214 elapsed=79.2s

  [3568/20519] intraday_12332.csv.gz  in=251,797,691 out=18,431,480 elapsed=79.2s

  [3569/20519] intraday_12335.csv.gz  in=251,809,789 out=18,443,578 elapsed=79.2s

  [3570/20519] intraday_12337.csv.gz  in=251,822,284 out=18,456,073 elapsed=79.2s

  [3571/20519] intraday_12336.csv.gz  in=251,834,168 out=18,467,957 elapsed=79.2s

  [3572/20519] intraday_12338.csv.gz  in=251,845,385 out=18,479,174 elapsed=79.2s

  [3573/20519] intraday_12339.csv.gz  in=251,857,849 out=18,491,638 elapsed=79.3s

  [3574/20519] intraday_1234.csv.gz  in=251,869,147 out=18,491,638 elapsed=79.3s

  [3575/20519] intraday_12340.csv.gz  in=251,878,482 out=18,500,973 elapsed=79.3s

  [3576/20519] intraday_12341.csv.gz  in=251,893,228 out=18,515,719 elapsed=79.3s

  [3577/20519] intraday_12342.csv.gz  in=251,908,653 out=18,531,144 elapsed=79.3s

  [3578/20519] intraday_12343.csv.gz  in=251,920,715 out=18,543,206 elapsed=79.3s

  [3579/20519] intraday_12344.csv.gz  in=251,934,528 out=18,557,019 elapsed=79.3s

  [3580/20519] intraday_12345.csv.gz  in=251,947,001 out=18,569,492 elapsed=79.3s

  [3581/20519] intraday_12346.csv.gz  in=251,957,117 out=18,579,608 elapsed=79.3s

  [3582/20519] intraday_12347.csv.gz  in=251,970,569 out=18,593,060 elapsed=79.3s

  [3583/20519] intraday_12348.csv.gz  in=251,983,478 out=18,605,969 elapsed=79.4s

  [3584/20519] intraday_12349.csv.gz  in=251,996,245 out=18,618,736 elapsed=79.4s

  [3585/20519] intraday_1235.csv.gz  in=252,010,748 out=18,618,736 elapsed=79.4s

  [3586/20519] intraday_12350.csv.gz  in=252,024,413 out=18,632,401 elapsed=79.4s

  [3587/20519] intraday_12351.csv.gz  in=252,036,277 out=18,644,265 elapsed=79.4s

  [3588/20519] intraday_12353.csv.gz  in=252,047,589 out=18,655,577 elapsed=79.5s

  [3589/20519] intraday_12352.csv.gz  in=252,058,814 out=18,666,802 elapsed=79.5s

  [3590/20519] intraday_12354.csv.gz  in=252,072,432 out=18,680,420 elapsed=79.5s

  [3591/20519] intraday_12355.csv.gz  in=252,084,647 out=18,692,635 elapsed=79.5s

  [3592/20519] intraday_12356.csv.gz  in=252,096,393 out=18,704,381 elapsed=79.5s

  [3593/20519] intraday_12357.csv.gz  in=252,107,947 out=18,715,935 elapsed=79.5s

  [3594/20519] intraday_12358.csv.gz  in=252,119,214 out=18,727,202 elapsed=79.5s

  [3595/20519] intraday_1236.csv.gz  in=252,133,267 out=18,727,202 elapsed=79.5s

  [3596/20519] intraday_12359.csv.gz  in=252,145,501 out=18,739,436 elapsed=79.5s

  [3597/20519] intraday_12360.csv.gz  in=252,161,250 out=18,755,185 elapsed=79.6s

  [3598/20519] intraday_12362.csv.gz  in=252,174,561 out=18,768,496 elapsed=79.6s

  [3599/20519] intraday_12361.csv.gz  in=252,191,950 out=18,785,885 elapsed=79.6s

  [3600/20519] intraday_12363.csv.gz  in=252,203,885 out=18,797,820 elapsed=79.6s

  [3601/20519] intraday_12364.csv.gz  in=252,215,396 out=18,809,331 elapsed=79.6s

  [3602/20519] intraday_12365.csv.gz  in=252,227,796 out=18,821,731 elapsed=79.7s

  [3603/20519] intraday_12366.csv.gz  in=252,242,564 out=18,836,499 elapsed=79.7s

  [3604/20519] intraday_12367.csv.gz  in=252,253,320 out=18,847,255 elapsed=79.7s

  [3605/20519] intraday_12368.csv.gz  in=252,264,312 out=18,858,247 elapsed=79.7s

  [3606/20519] intraday_12369.csv.gz  in=252,279,801 out=18,873,736 elapsed=79.7s

  [3607/20519] intraday_1237.csv.gz  in=252,292,116 out=18,873,736 elapsed=79.7s

  [3608/20519] intraday_12370.csv.gz  in=252,304,549 out=18,886,169 elapsed=79.7s

  [3609/20519] intraday_12371.csv.gz  in=252,317,065 out=18,898,685 elapsed=79.7s

  [3610/20519] intraday_12373.csv.gz  in=252,328,193 out=18,909,813 elapsed=79.7s

  [3611/20519] intraday_12372.csv.gz  in=252,341,092 out=18,922,712 elapsed=79.8s

  [3612/20519] intraday_12374.csv.gz  in=252,353,981 out=18,935,601 elapsed=79.8s

  [3613/20519] intraday_12375.csv.gz  in=252,367,447 out=18,949,067 elapsed=79.8s

  [3614/20519] intraday_12376.csv.gz  in=252,379,102 out=18,960,722 elapsed=79.8s

  [3615/20519] intraday_12377.csv.gz  in=252,390,012 out=18,971,632 elapsed=79.8s

  [3616/20519] intraday_12378.csv.gz  in=252,403,584 out=18,985,204 elapsed=79.8s

  [3617/20519] intraday_1238.csv.gz  in=252,415,684 out=18,985,204 elapsed=79.8s

  [3618/20519] intraday_12379.csv.gz  in=252,429,448 out=18,998,968 elapsed=79.8s

  [3619/20519] intraday_12380.csv.gz  in=252,444,168 out=19,012,117 elapsed=79.9s

  [3620/20519] intraday_12381.csv.gz  in=252,456,847 out=19,024,796 elapsed=79.9s

  [3621/20519] intraday_12382.csv.gz  in=252,469,865 out=19,037,814 elapsed=79.9s

  [3622/20519] intraday_12384.csv.gz  in=252,480,884 out=19,048,833 elapsed=79.9s

  [3623/20519] intraday_12383.csv.gz  in=252,496,233 out=19,064,182 elapsed=79.9s

  [3624/20519] intraday_12385.csv.gz  in=252,508,683 out=19,076,632 elapsed=79.9s

  [3625/20519] intraday_12386.csv.gz  in=252,522,842 out=19,090,791 elapsed=79.9s

  [3626/20519] intraday_12387.csv.gz  in=252,537,933 out=19,105,882 elapsed=79.9s

  [3627/20519] intraday_12388.csv.gz  in=252,549,718 out=19,117,667 elapsed=80.0s

  [3628/20519] intraday_1239.csv.gz  in=252,564,426 out=19,117,667 elapsed=80.0s

  [3629/20519] intraday_12389.csv.gz  in=252,577,723 out=19,130,964 elapsed=80.0s

  [3630/20519] intraday_12391.csv.gz  in=252,590,954 out=19,144,195 elapsed=80.0s

  [3631/20519] intraday_12392.csv.gz  in=252,604,962 out=19,158,203 elapsed=80.0s

  [3632/20519] intraday_12390.csv.gz  in=252,620,401 out=19,173,642 elapsed=80.0s

  [3633/20519] intraday_12393.csv.gz  in=252,636,731 out=19,189,972 elapsed=80.1s

  [3634/20519] intraday_12394.csv.gz  in=252,655,323 out=19,208,564 elapsed=80.1s

  [3635/20519] intraday_12395.csv.gz  in=252,668,907 out=19,222,148 elapsed=80.1s

  [3636/20519] intraday_12396.csv.gz  in=252,685,433 out=19,238,674 elapsed=80.1s

  [3637/20519] intraday_12399.csv.gz  in=252,698,025 out=19,251,266 elapsed=80.1s

  [3638/20519] intraday_12398.csv.gz  in=252,710,345 out=19,263,586 elapsed=80.1s

  [3639/20519] intraday_12397.csv.gz  in=252,744,865 out=19,279,345 elapsed=80.1s

  [3640/20519] intraday_12400.csv.gz  in=252,757,297 out=19,291,777 elapsed=80.1s

  [3641/20519] intraday_12401.csv.gz  in=252,768,175 out=19,302,655 elapsed=80.2s

  [3642/20519] intraday_1240.csv.gz  in=252,782,233 out=19,302,655 elapsed=80.2s

  [3643/20519] intraday_12402.csv.gz  in=252,795,345 out=19,315,767 elapsed=80.2s

  [3644/20519] intraday_12403.csv.gz  in=252,807,016 out=19,327,438 elapsed=80.2s

  [3645/20519] intraday_12405.csv.gz  in=252,817,577 out=19,337,999 elapsed=80.2s

  [3646/20519] intraday_12404.csv.gz  in=252,833,431 out=19,353,853 elapsed=80.2s

  [3647/20519] intraday_12406.csv.gz  in=252,844,692 out=19,365,114 elapsed=80.3s

  [3648/20519] intraday_12407.csv.gz  in=252,856,395 out=19,376,817 elapsed=80.3s

  [3649/20519] intraday_12409.csv.gz  in=252,866,993 out=19,387,415 elapsed=80.3s

  [3650/20519] intraday_1241.csv.gz  in=252,876,764 out=19,387,415 elapsed=80.3s

  [3651/20519] intraday_12408.csv.gz  in=252,891,080 out=19,401,731 elapsed=80.4s

  [3652/20519] intraday_12410.csv.gz  in=252,904,800 out=19,415,451 elapsed=80.4s

  [3653/20519] intraday_12411.csv.gz  in=252,919,435 out=19,430,086 elapsed=80.4s

  [3654/20519] intraday_12412.csv.gz  in=252,933,737 out=19,444,388 elapsed=80.4s

  [3655/20519] intraday_12414.csv.gz  in=252,947,982 out=19,458,633 elapsed=80.4s

  [3656/20519] intraday_12415.csv.gz  in=252,959,698 out=19,470,349 elapsed=80.4s

  [3657/20519] intraday_12413.csv.gz  in=252,973,648 out=19,484,299 elapsed=80.4s

  [3658/20519] intraday_12416.csv.gz  in=252,986,268 out=19,496,919 elapsed=80.5s

  [3659/20519] intraday_12417.csv.gz  in=252,996,602 out=19,507,253 elapsed=80.5s

  [3660/20519] intraday_12418.csv.gz  in=253,009,698 out=19,520,349 elapsed=80.5s

  [3661/20519] intraday_1242.csv.gz  in=253,024,684 out=19,520,349 elapsed=80.5s

  [3662/20519] intraday_12419.csv.gz  in=253,032,719 out=19,528,384 elapsed=80.5s

  [3663/20519] intraday_12422.csv.gz  in=253,036,332 out=19,531,997 elapsed=80.5s

  [3664/20519] intraday_12420.csv.gz  in=253,043,944 out=19,539,609 elapsed=80.5s

  [3665/20519] intraday_12421.csv.gz  in=253,057,505 out=19,553,170 elapsed=80.6s

  [3666/20519] intraday_12423.csv.gz  in=253,075,590 out=19,571,255 elapsed=80.6s

  [3667/20519] intraday_12424.csv.gz  in=253,088,474 out=19,584,139 elapsed=80.6s

  [3668/20519] intraday_12425.csv.gz  in=253,102,867 out=19,598,532 elapsed=80.6s

  [3669/20519] intraday_12427.csv.gz  in=253,115,147 out=19,610,812 elapsed=80.6s

  [3670/20519] intraday_12426.csv.gz  in=253,127,389 out=19,622,285 elapsed=80.6s

  [3671/20519] intraday_12428.csv.gz  in=253,142,244 out=19,637,140 elapsed=80.6s

  [3672/20519] intraday_12429.csv.gz  in=253,161,412 out=19,656,308 elapsed=80.6s

  [3673/20519] intraday_1243.csv.gz  in=253,176,682 out=19,656,308 elapsed=80.7s

  [3674/20519] intraday_12430.csv.gz  in=253,188,243 out=19,667,869 elapsed=80.7s

  [3675/20519] intraday_12431.csv.gz  in=253,202,184 out=19,681,810 elapsed=80.7s

  [3676/20519] intraday_12432.csv.gz  in=253,216,449 out=19,696,075 elapsed=80.7s

  [3677/20519] intraday_12434.csv.gz  in=253,229,539 out=19,709,165 elapsed=80.7s

  [3678/20519] intraday_12435.csv.gz  in=253,243,630 out=19,723,256 elapsed=80.7s

  [3679/20519] intraday_12433.csv.gz  in=253,257,019 out=19,736,645 elapsed=80.7s

  [3680/20519] intraday_12436.csv.gz  in=253,271,194 out=19,750,820 elapsed=80.7s

  [3681/20519] intraday_12437.csv.gz  in=253,293,466 out=19,763,305 elapsed=80.8s

  [3682/20519] intraday_1244.csv.gz  in=253,304,523 out=19,763,305 elapsed=80.8s

  [3683/20519] intraday_12438.csv.gz  in=253,317,398 out=19,775,210 elapsed=80.8s

  [3684/20519] intraday_12439.csv.gz  in=253,332,154 out=19,789,810 elapsed=80.8s

  [3685/20519] intraday_12442.csv.gz  in=253,342,794 out=19,800,450 elapsed=80.8s

  [3686/20519] intraday_12440.csv.gz  in=253,356,390 out=19,814,046 elapsed=80.9s

  [3687/20519] intraday_12441.csv.gz  in=253,367,214 out=19,824,870 elapsed=80.9s

  [3688/20519] intraday_12443.csv.gz  in=253,378,660 out=19,836,316 elapsed=80.9s

  [3689/20519] intraday_12445.csv.gz  in=253,391,223 out=19,848,879 elapsed=80.9s

  [3690/20519] intraday_12444.csv.gz  in=253,404,027 out=19,861,683 elapsed=80.9s

  [3691/20519] intraday_12446.csv.gz  in=253,416,350 out=19,874,006 elapsed=80.9s

  [3692/20519] intraday_12447.csv.gz  in=253,429,188 out=19,886,844 elapsed=80.9s

  [3693/20519] intraday_12448.csv.gz  in=253,441,019 out=19,898,675 elapsed=81.0s

  [3694/20519] intraday_12449.csv.gz  in=253,454,534 out=19,912,190 elapsed=81.0s

  [3695/20519] intraday_1245.csv.gz  in=253,465,215 out=19,912,190 elapsed=81.0s

  [3696/20519] intraday_12450.csv.gz  in=253,477,210 out=19,924,185 elapsed=81.0s

  [3697/20519] intraday_12452.csv.gz  in=253,490,641 out=19,937,616 elapsed=81.0s

  [3698/20519] intraday_12451.csv.gz  in=253,502,552 out=19,949,527 elapsed=81.0s

  [3699/20519] intraday_12453.csv.gz  in=253,518,670 out=19,965,645 elapsed=81.1s

  [3700/20519] intraday_12454.csv.gz  in=253,532,816 out=19,979,791 elapsed=81.1s

  [3701/20519] intraday_12455.csv.gz  in=253,543,320 out=19,990,295 elapsed=81.1s

  [3702/20519] intraday_12456.csv.gz  in=253,558,192 out=20,005,167 elapsed=81.1s

  [3703/20519] intraday_12458.csv.gz  in=253,572,479 out=20,019,454 elapsed=81.1s

  [3704/20519] intraday_12459.csv.gz  in=253,584,419 out=20,031,394 elapsed=81.1s

  [3705/20519] intraday_1246.csv.gz  in=253,595,950 out=20,031,394 elapsed=81.1s

  [3706/20519] intraday_12457.csv.gz  in=253,611,996 out=20,045,091 elapsed=81.1s

  [3707/20519] intraday_12460.csv.gz  in=253,623,532 out=20,056,627 elapsed=81.2s

  [3708/20519] intraday_12462.csv.gz  in=253,634,622 out=20,067,717 elapsed=81.2s

  [3709/20519] intraday_12461.csv.gz  in=253,647,032 out=20,080,127 elapsed=81.2s

  [3710/20519] intraday_12464.csv.gz  in=253,662,118 out=20,095,213 elapsed=81.2s

  [3711/20519] intraday_12463.csv.gz  in=253,673,500 out=20,106,595 elapsed=81.2s

  [3712/20519] intraday_12465.csv.gz  in=253,685,521 out=20,118,616 elapsed=81.2s

  [3713/20519] intraday_12466.csv.gz  in=253,698,613 out=20,131,708 elapsed=81.2s

  [3714/20519] intraday_12468.csv.gz  in=253,710,780 out=20,143,875 elapsed=81.3s

  [3715/20519] intraday_12469.csv.gz  in=253,723,586 out=20,156,681 elapsed=81.3s

  [3716/20519] intraday_1247.csv.gz  in=253,736,570 out=20,156,681 elapsed=81.3s

  [3717/20519] intraday_12467.csv.gz  in=253,751,964 out=20,172,075 elapsed=81.3s

  [3718/20519] intraday_12470.csv.gz  in=253,763,493 out=20,183,604 elapsed=81.3s

  [3719/20519] intraday_12472.csv.gz  in=253,779,075 out=20,195,681 elapsed=81.3s

  [3720/20519] intraday_12473.csv.gz  in=253,791,825 out=20,208,431 elapsed=81.4s

  [3721/20519] intraday_12474.csv.gz  in=253,802,391 out=20,218,997 elapsed=81.4s

  [3722/20519] intraday_12471.csv.gz  in=253,816,043 out=20,232,649 elapsed=81.4s

  [3723/20519] intraday_12475.csv.gz  in=253,828,892 out=20,245,498 elapsed=81.4s

  [3724/20519] intraday_12476.csv.gz  in=253,841,338 out=20,257,944 elapsed=81.4s

  [3725/20519] intraday_12477.csv.gz  in=253,853,884 out=20,270,490 elapsed=81.4s

  [3726/20519] intraday_1248.csv.gz  in=253,866,939 out=20,270,490 elapsed=81.5s

  [3727/20519] intraday_12478.csv.gz  in=253,881,700 out=20,285,251 elapsed=81.5s

  [3728/20519] intraday_12479.csv.gz  in=253,892,285 out=20,295,836 elapsed=81.5s

  [3729/20519] intraday_12480.csv.gz  in=253,903,872 out=20,307,423 elapsed=81.5s

  [3730/20519] intraday_12482.csv.gz  in=253,916,799 out=20,320,350 elapsed=81.5s

  [3731/20519] intraday_12481.csv.gz  in=253,927,871 out=20,331,422 elapsed=81.5s

  [3732/20519] intraday_12483.csv.gz  in=253,940,086 out=20,343,637 elapsed=81.5s

  [3733/20519] intraday_12485.csv.gz  in=253,953,212 out=20,356,763 elapsed=81.5s

  [3734/20519] intraday_12484.csv.gz  in=253,965,378 out=20,368,929 elapsed=81.6s

  [3735/20519] intraday_12486.csv.gz  in=253,977,481 out=20,381,032 elapsed=81.6s

  [3736/20519] intraday_12487.csv.gz  in=253,988,094 out=20,391,645 elapsed=81.6s

  [3737/20519] intraday_12488.csv.gz  in=254,001,546 out=20,405,097 elapsed=81.6s

  [3738/20519] intraday_1249.csv.gz  in=254,013,155 out=20,405,097 elapsed=81.6s

  [3739/20519] intraday_12490.csv.gz  in=254,027,013 out=20,418,955 elapsed=81.6s

  [3740/20519] intraday_12489.csv.gz  in=254,042,792 out=20,434,734 elapsed=81.6s

  [3741/20519] intraday_12491.csv.gz  in=254,057,384 out=20,449,326 elapsed=81.7s

  [3742/20519] intraday_12492.csv.gz  in=254,070,229 out=20,462,171 elapsed=81.7s

  [3743/20519] intraday_12494.csv.gz  in=254,082,325 out=20,474,267 elapsed=81.7s

  [3744/20519] intraday_12496.csv.gz  in=254,095,258 out=20,487,200 elapsed=81.7s

  [3745/20519] intraday_12493.csv.gz  in=254,106,682 out=20,498,624 elapsed=81.7s

  [3746/20519] intraday_12497.csv.gz  in=254,120,646 out=20,512,588 elapsed=81.8s

  [3747/20519] intraday_12495.csv.gz  in=254,134,660 out=20,526,602 elapsed=81.8s

  [3748/20519] intraday_12498.csv.gz  in=254,146,294 out=20,538,236 elapsed=81.8s

  [3749/20519] intraday_12499.csv.gz  in=254,159,308 out=20,551,250 elapsed=81.8s

  [3750/20519] intraday_1250.csv.gz  in=254,170,117 out=20,551,250 elapsed=81.8s

  [3751/20519] intraday_12500.csv.gz  in=254,181,636 out=20,562,769 elapsed=81.8s

  [3752/20519] intraday_12501.csv.gz  in=254,196,348 out=20,577,481 elapsed=81.8s

  [3753/20519] intraday_12502.csv.gz  in=254,208,103 out=20,589,236 elapsed=81.8s

  [3754/20519] intraday_12504.csv.gz  in=254,219,603 out=20,600,736 elapsed=81.8s

  [3755/20519] intraday_12503.csv.gz  in=254,232,313 out=20,613,446 elapsed=81.9s

  [3756/20519] intraday_12505.csv.gz  in=254,243,288 out=20,624,421 elapsed=81.9s

  [3757/20519] intraday_12506.csv.gz  in=254,256,149 out=20,637,282 elapsed=81.9s

  [3758/20519] intraday_12507.csv.gz  in=254,271,220 out=20,652,353 elapsed=81.9s

  [3759/20519] intraday_12508.csv.gz  in=254,289,210 out=20,670,343 elapsed=81.9s

  [3760/20519] intraday_1251.csv.gz  in=254,302,044 out=20,670,343 elapsed=81.9s

  [3761/20519] intraday_12509.csv.gz  in=254,316,285 out=20,684,584 elapsed=81.9s

  [3762/20519] intraday_12510.csv.gz  in=254,327,365 out=20,695,664 elapsed=81.9s

  [3763/20519] intraday_12512.csv.gz  in=254,340,663 out=20,708,962 elapsed=82.0s

  [3764/20519] intraday_12511.csv.gz  in=254,352,826 out=20,721,125 elapsed=82.0s

  [3765/20519] intraday_12513.csv.gz  in=254,364,821 out=20,733,120 elapsed=82.0s

  [3766/20519] intraday_12514.csv.gz  in=254,380,097 out=20,748,396 elapsed=82.0s

  [3767/20519] intraday_12517.csv.gz  in=254,394,459 out=20,762,758 elapsed=82.0s

  [3768/20519] intraday_12515.csv.gz  in=254,406,032 out=20,774,331 elapsed=82.0s

  [3769/20519] intraday_12516.csv.gz  in=254,421,788 out=20,790,087 elapsed=82.0s

  [3770/20519] intraday_12518.csv.gz  in=254,433,102 out=20,801,401 elapsed=82.0s

  [3771/20519] intraday_1252.csv.gz  in=254,445,070 out=20,801,401 elapsed=82.0s

  [3772/20519] intraday_12520.csv.gz  in=254,456,628 out=20,812,959 elapsed=82.1s

  [3773/20519] intraday_12519.csv.gz  in=254,469,947 out=20,826,278 elapsed=82.1s

  [3774/20519] intraday_12521.csv.gz  in=254,483,931 out=20,840,262 elapsed=82.1s

  [3775/20519] intraday_12522.csv.gz  in=254,495,181 out=20,851,512 elapsed=82.1s

  [3776/20519] intraday_12523.csv.gz  in=254,509,973 out=20,866,304 elapsed=82.1s

  [3777/20519] intraday_12524.csv.gz  in=254,522,162 out=20,878,493 elapsed=82.2s

  [3778/20519] intraday_12526.csv.gz  in=254,535,455 out=20,891,786 elapsed=82.2s

  [3779/20519] intraday_12527.csv.gz  in=254,550,309 out=20,906,640 elapsed=82.3s

  [3780/20519] intraday_12525.csv.gz  in=254,563,066 out=20,919,397 elapsed=82.3s

  [3781/20519] intraday_12528.csv.gz  in=254,577,617 out=20,933,948 elapsed=82.3s

  [3782/20519] intraday_12529.csv.gz  in=254,589,977 out=20,946,308 elapsed=82.3s

  [3783/20519] intraday_1253.csv.gz  in=254,602,758 out=20,946,308 elapsed=82.3s

  [3784/20519] intraday_12530.csv.gz  in=254,615,596 out=20,959,146 elapsed=82.3s

  [3785/20519] intraday_12532.csv.gz  in=254,627,595 out=20,971,145 elapsed=82.3s

  [3786/20519] intraday_12531.csv.gz  in=254,642,223 out=20,985,773 elapsed=82.3s

  [3787/20519] intraday_12533.csv.gz  in=254,656,539 out=21,000,089 elapsed=82.4s

  [3788/20519] intraday_12534.csv.gz  in=254,671,361 out=21,014,911 elapsed=82.4s

  [3789/20519] intraday_12535.csv.gz  in=254,684,241 out=21,027,791 elapsed=82.4s

  [3790/20519] intraday_12536.csv.gz  in=254,696,724 out=21,040,274 elapsed=82.4s

  [3791/20519] intraday_12537.csv.gz  in=254,710,772 out=21,054,322 elapsed=82.4s

  [3792/20519] intraday_12538.csv.gz  in=254,727,703 out=21,071,253 elapsed=82.4s

  [3793/20519] intraday_12539.csv.gz  in=254,740,585 out=21,084,135 elapsed=82.4s

  [3794/20519] intraday_1254.csv.gz  in=254,753,134 out=21,084,135 elapsed=82.5s

  [3795/20519] intraday_12540.csv.gz  in=254,769,143 out=21,100,144 elapsed=82.5s

  [3796/20519] intraday_12542.csv.gz  in=254,784,219 out=21,115,220 elapsed=82.5s

  [3797/20519] intraday_12544.csv.gz  in=254,797,251 out=21,128,252 elapsed=82.6s

  [3798/20519] intraday_12541.csv.gz  in=254,816,872 out=21,147,873 elapsed=82.6s

  [3799/20519] intraday_12545.csv.gz  in=254,829,130 out=21,160,131 elapsed=82.6s

  [3800/20519] intraday_12543.csv.gz  in=254,846,858 out=21,177,859 elapsed=82.6s

  [3801/20519] intraday_12546.csv.gz  in=254,859,642 out=21,190,643 elapsed=82.6s

  [3802/20519] intraday_12547.csv.gz  in=254,872,367 out=21,203,368 elapsed=82.6s

  [3803/20519] intraday_12548.csv.gz  in=254,884,548 out=21,215,549 elapsed=82.6s

  [3804/20519] intraday_12549.csv.gz  in=254,896,392 out=21,227,393 elapsed=82.6s

  [3805/20519] intraday_1255.csv.gz  in=254,908,885 out=21,227,393 elapsed=82.6s

  [3806/20519] intraday_12552.csv.gz  in=254,922,490 out=21,240,998 elapsed=82.7s

  [3807/20519] intraday_12551.csv.gz  in=254,937,345 out=21,255,853 elapsed=82.7s

  [3808/20519] intraday_12550.csv.gz  in=254,951,535 out=21,270,043 elapsed=82.7s

  [3809/20519] intraday_12553.csv.gz  in=254,963,285 out=21,281,793 elapsed=82.7s

  [3810/20519] intraday_12555.csv.gz  in=254,977,914 out=21,296,422 elapsed=82.7s

  [3811/20519] intraday_12554.csv.gz  in=254,989,202 out=21,307,710 elapsed=82.7s

  [3812/20519] intraday_12556.csv.gz  in=255,000,711 out=21,319,219 elapsed=82.7s

  [3813/20519] intraday_12557.csv.gz  in=255,013,693 out=21,332,201 elapsed=82.8s

  [3814/20519] intraday_12558.csv.gz  in=255,028,613 out=21,347,121 elapsed=82.8s

  [3815/20519] intraday_1256.csv.gz  in=255,048,177 out=21,347,121 elapsed=82.8s

  [3816/20519] intraday_12559.csv.gz  in=255,063,672 out=21,362,616 elapsed=82.8s

  [3817/20519] intraday_12560.csv.gz  in=255,077,606 out=21,376,550 elapsed=82.8s

  [3818/20519] intraday_12562.csv.gz  in=255,089,232 out=21,388,176 elapsed=82.8s

  [3819/20519] intraday_12561.csv.gz  in=255,105,323 out=21,404,267 elapsed=82.9s

  [3820/20519] intraday_12563.csv.gz  in=255,118,242 out=21,417,186 elapsed=82.9s

  [3821/20519] intraday_12565.csv.gz  in=255,130,241 out=21,429,185 elapsed=82.9s

  [3822/20519] intraday_12564.csv.gz  in=255,142,225 out=21,441,169 elapsed=82.9s

  [3823/20519] intraday_12566.csv.gz  in=255,152,359 out=21,451,303 elapsed=82.9s

  [3824/20519] intraday_12567.csv.gz  in=255,159,094 out=21,458,038 elapsed=82.9s

  [3825/20519] intraday_12568.csv.gz  in=255,173,207 out=21,472,151 elapsed=83.0s

  [3826/20519] intraday_1257.csv.gz  in=255,190,777 out=21,472,151 elapsed=83.0s

  [3827/20519] intraday_12569.csv.gz  in=255,196,915 out=21,478,289 elapsed=83.0s

  [3828/20519] intraday_12570.csv.gz  in=255,214,369 out=21,495,743 elapsed=83.0s

  [3829/20519] intraday_12571.csv.gz  in=255,227,260 out=21,508,634 elapsed=83.0s

  [3830/20519] intraday_12572.csv.gz  in=255,240,844 out=21,522,218 elapsed=83.0s

  [3831/20519] intraday_12574.csv.gz  in=255,252,478 out=21,533,852 elapsed=83.0s

  [3832/20519] intraday_12573.csv.gz  in=255,263,614 out=21,544,988 elapsed=83.0s

  [3833/20519] intraday_12575.csv.gz  in=255,277,869 out=21,559,243 elapsed=83.1s

  [3834/20519] intraday_12578.csv.gz  in=255,290,853 out=21,572,227 elapsed=83.1s

  [3835/20519] intraday_12576.csv.gz  in=255,307,898 out=21,589,268 elapsed=83.1s

  [3836/20519] intraday_12579.csv.gz  in=255,321,707 out=21,603,077 elapsed=83.1s

  [3837/20519] intraday_12577.csv.gz  in=255,334,555 out=21,615,925 elapsed=83.1s

  [3838/20519] intraday_1258.csv.gz  in=255,347,391 out=21,615,925 elapsed=83.2s

  [3839/20519] intraday_12580.csv.gz  in=255,360,628 out=21,629,162 elapsed=83.2s

  [3840/20519] intraday_12581.csv.gz  in=255,372,294 out=21,640,828 elapsed=83.2s

  [3841/20519] intraday_12582.csv.gz  in=255,387,063 out=21,655,597 elapsed=83.2s

  [3842/20519] intraday_12583.csv.gz  in=255,400,506 out=21,669,040 elapsed=83.2s

  [3843/20519] intraday_12584.csv.gz  in=255,410,286 out=21,678,820 elapsed=83.2s

  [3844/20519] intraday_12585.csv.gz  in=255,421,356 out=21,689,890 elapsed=83.2s

  [3845/20519] intraday_12586.csv.gz  in=255,436,400 out=21,704,934 elapsed=83.3s

  [3846/20519] intraday_12588.csv.gz  in=255,446,307 out=21,714,841 elapsed=83.3s

  [3847/20519] intraday_12589.csv.gz  in=255,456,872 out=21,725,406 elapsed=83.3s

  [3848/20519] intraday_12587.csv.gz  in=255,470,106 out=21,738,640 elapsed=83.3s

  [3849/20519] intraday_12590.csv.gz  in=255,481,161 out=21,749,695 elapsed=83.3s

  [3850/20519] intraday_1259.csv.gz  in=255,494,605 out=21,749,695 elapsed=83.3s

  [3851/20519] intraday_12591.csv.gz  in=255,506,950 out=21,762,040 elapsed=83.3s

  [3852/20519] intraday_12592.csv.gz  in=255,518,937 out=21,774,027 elapsed=83.3s

  [3853/20519] intraday_12593.csv.gz  in=255,530,958 out=21,786,048 elapsed=83.4s

  [3854/20519] intraday_12595.csv.gz  in=255,542,120 out=21,797,210 elapsed=83.4s

  [3855/20519] intraday_12594.csv.gz  in=255,556,185 out=21,811,275 elapsed=83.4s

  [3856/20519] intraday_12597.csv.gz  in=255,568,938 out=21,824,028 elapsed=83.4s

  [3857/20519] intraday_12596.csv.gz  in=255,580,813 out=21,835,903 elapsed=83.4s

  [3858/20519] intraday_12598.csv.gz  in=255,592,645 out=21,847,735 elapsed=83.4s

  [3859/20519] intraday_12599.csv.gz  in=255,605,875 out=21,860,965 elapsed=83.4s

  [3860/20519] intraday_12600.csv.gz  in=255,621,902 out=21,876,992 elapsed=83.5s

  [3861/20519] intraday_1260.csv.gz  in=255,637,099 out=21,876,992 elapsed=83.5s

  [3862/20519] intraday_12602.csv.gz  in=255,647,142 out=21,887,035 elapsed=83.5s

  [3863/20519] intraday_12603.csv.gz  in=255,660,354 out=21,900,247 elapsed=83.5s

  [3864/20519] intraday_12601.csv.gz  in=255,673,643 out=21,913,536 elapsed=83.5s

  [3865/20519] intraday_12604.csv.gz  in=255,686,580 out=21,926,473 elapsed=83.5s

  [3866/20519] intraday_12605.csv.gz  in=255,699,993 out=21,939,886 elapsed=83.5s

  [3867/20519] intraday_12606.csv.gz  in=255,712,617 out=21,952,510 elapsed=83.6s

  [3868/20519] intraday_12607.csv.gz  in=255,723,325 out=21,963,218 elapsed=83.6s

  [3869/20519] intraday_12609.csv.gz  in=255,733,848 out=21,973,053 elapsed=83.6s

  [3870/20519] intraday_1261.csv.gz  in=255,747,158 out=21,973,053 elapsed=83.6s

  [3871/20519] intraday_12608.csv.gz  in=255,763,546 out=21,985,967 elapsed=83.6s

  [3872/20519] intraday_12610.csv.gz  in=255,775,487 out=21,997,908 elapsed=83.6s

  [3873/20519] intraday_12611.csv.gz  in=255,789,638 out=22,012,059 elapsed=83.6s

  [3874/20519] intraday_12613.csv.gz  in=255,811,406 out=22,026,676 elapsed=83.6s

  [3875/20519] intraday_12612.csv.gz  in=255,822,549 out=22,037,819 elapsed=83.7s

  [3876/20519] intraday_12615.csv.gz  in=255,835,137 out=22,050,407 elapsed=83.7s

  [3877/20519] intraday_12614.csv.gz  in=255,849,330 out=22,064,600 elapsed=83.7s

  [3878/20519] intraday_12616.csv.gz  in=255,860,488 out=22,075,758 elapsed=83.7s

  [3879/20519] intraday_12617.csv.gz  in=255,872,070 out=22,087,340 elapsed=83.7s

  [3880/20519] intraday_12619.csv.gz  in=255,882,676 out=22,097,946 elapsed=83.7s

  [3881/20519] intraday_1262.csv.gz  in=255,894,752 out=22,097,946 elapsed=83.7s

  [3882/20519] intraday_12618.csv.gz  in=255,908,076 out=22,111,270 elapsed=83.7s

  [3883/20519] intraday_12621.csv.gz  in=255,918,143 out=22,121,337 elapsed=83.8s

  [3884/20519] intraday_12622.csv.gz  in=255,932,885 out=22,136,079 elapsed=83.8s

  [3885/20519] intraday_12620.csv.gz  in=255,965,767 out=22,151,909 elapsed=83.8s

  [3886/20519] intraday_12623.csv.gz  in=255,978,738 out=22,164,880 elapsed=83.8s

  [3887/20519] intraday_12624.csv.gz  in=255,991,024 out=22,177,166 elapsed=83.8s

  [3888/20519] intraday_12625.csv.gz  in=256,004,822 out=22,190,964 elapsed=83.8s

  [3889/20519] intraday_12626.csv.gz  in=256,016,120 out=22,202,262 elapsed=83.9s

  [3890/20519] intraday_12628.csv.gz  in=256,026,405 out=22,212,547 elapsed=83.9s

  [3891/20519] intraday_12629.csv.gz  in=256,040,622 out=22,225,773 elapsed=83.9s

  [3892/20519] intraday_1263.csv.gz  in=256,053,919 out=22,225,773 elapsed=83.9s

  [3893/20519] intraday_12627.csv.gz  in=256,065,592 out=22,237,446 elapsed=83.9s

  [3894/20519] intraday_12630.csv.gz  in=256,077,241 out=22,249,095 elapsed=83.9s

  [3895/20519] intraday_12631.csv.gz  in=256,090,591 out=22,261,308 elapsed=83.9s

  [3896/20519] intraday_12633.csv.gz  in=256,103,233 out=22,273,950 elapsed=83.9s

  [3897/20519] intraday_12634.csv.gz  in=256,112,434 out=22,283,151 elapsed=84.0s

  [3898/20519] intraday_12635.csv.gz  in=256,126,732 out=22,297,449 elapsed=84.0s

  [3899/20519] intraday_12632.csv.gz  in=256,148,863 out=22,311,891 elapsed=84.0s

  [3900/20519] intraday_12636.csv.gz  in=256,163,695 out=22,326,723 elapsed=84.0s

  [3901/20519] intraday_12637.csv.gz  in=256,176,925 out=22,339,953 elapsed=84.0s

  [3902/20519] intraday_12638.csv.gz  in=256,190,474 out=22,353,502 elapsed=84.0s

  [3903/20519] intraday_1264.csv.gz  in=256,205,048 out=22,353,502 elapsed=84.0s

  [3904/20519] intraday_12639.csv.gz  in=256,219,180 out=22,367,634 elapsed=84.1s

  [3905/20519] intraday_12640.csv.gz  in=256,229,495 out=22,377,949 elapsed=84.1s

  [3906/20519] intraday_12641.csv.gz  in=256,241,714 out=22,389,942 elapsed=84.1s

  [3907/20519] intraday_12642.csv.gz  in=256,255,362 out=22,403,590 elapsed=84.1s

  [3908/20519] intraday_12643.csv.gz  in=256,267,739 out=22,415,967 elapsed=84.1s

  [3909/20519] intraday_12645.csv.gz  in=256,278,689 out=22,426,917 elapsed=84.1s

  [3910/20519] intraday_12644.csv.gz  in=256,292,343 out=22,440,269 elapsed=84.1s

  [3911/20519] intraday_12646.csv.gz  in=256,304,644 out=22,452,570 elapsed=84.1s

  [3912/20519] intraday_12647.csv.gz  in=256,315,866 out=22,463,792 elapsed=84.2s

  [3913/20519] intraday_12648.csv.gz  in=256,329,381 out=22,477,307 elapsed=84.2s

  [3914/20519] intraday_12649.csv.gz  in=256,340,313 out=22,488,239 elapsed=84.2s

  [3915/20519] intraday_1265.csv.gz  in=256,351,909 out=22,488,239 elapsed=84.2s

  [3916/20519] intraday_12651.csv.gz  in=256,362,794 out=22,499,124 elapsed=84.2s

  [3917/20519] intraday_12650.csv.gz  in=256,375,588 out=22,511,918 elapsed=84.2s

  [3918/20519] intraday_12652.csv.gz  in=256,385,471 out=22,521,801 elapsed=84.2s

  [3919/20519] intraday_12653.csv.gz  in=256,399,431 out=22,535,761 elapsed=84.3s

  [3920/20519] intraday_12654.csv.gz  in=256,413,134 out=22,549,464 elapsed=84.3s

  [3921/20519] intraday_12655.csv.gz  in=256,428,977 out=22,565,307 elapsed=84.3s

  [3922/20519] intraday_12656.csv.gz  in=256,442,333 out=22,578,663 elapsed=84.3s

  [3923/20519] intraday_12658.csv.gz  in=256,453,432 out=22,589,762 elapsed=84.3s

  [3924/20519] intraday_12657.csv.gz  in=256,471,942 out=22,603,199 elapsed=84.3s

  [3925/20519] intraday_12659.csv.gz  in=256,485,334 out=22,616,591 elapsed=84.4s

  [3926/20519] intraday_1266.csv.gz  in=256,500,109 out=22,616,591 elapsed=84.4s

  [3927/20519] intraday_12661.csv.gz  in=256,513,505 out=22,629,987 elapsed=84.4s

  [3928/20519] intraday_12662.csv.gz  in=256,524,742 out=22,641,224 elapsed=84.4s

  [3929/20519] intraday_12663.csv.gz  in=256,540,149 out=22,656,631 elapsed=84.4s

  [3930/20519] intraday_12660.csv.gz  in=256,554,556 out=22,671,038 elapsed=84.4s

  [3931/20519] intraday_12664.csv.gz  in=256,568,300 out=22,684,782 elapsed=84.5s

  [3932/20519] intraday_12665.csv.gz  in=256,579,228 out=22,695,710 elapsed=84.5s

  [3933/20519] intraday_12666.csv.gz  in=256,593,054 out=22,709,536 elapsed=84.5s

  [3934/20519] intraday_12667.csv.gz  in=256,603,840 out=22,720,322 elapsed=84.5s

  [3935/20519] intraday_1267.csv.gz  in=256,616,160 out=22,720,322 elapsed=84.5s

  [3936/20519] intraday_12670.csv.gz  in=256,628,466 out=22,732,628 elapsed=84.5s

  [3937/20519] intraday_12669.csv.gz  in=256,639,920 out=22,744,082 elapsed=84.5s

  [3938/20519] intraday_12668.csv.gz  in=256,652,522 out=22,756,684 elapsed=84.5s

  [3939/20519] intraday_12671.csv.gz  in=256,664,717 out=22,768,879 elapsed=84.6s

  [3940/20519] intraday_12672.csv.gz  in=256,676,617 out=22,780,779 elapsed=84.6s

  [3941/20519] intraday_12673.csv.gz  in=256,690,876 out=22,795,038 elapsed=84.6s

  [3942/20519] intraday_12674.csv.gz  in=256,703,588 out=22,807,750 elapsed=84.6s

  [3943/20519] intraday_12677.csv.gz  in=256,717,906 out=22,822,068 elapsed=84.7s

  [3944/20519] intraday_12675.csv.gz  in=256,731,856 out=22,836,018 elapsed=84.7s

  [3945/20519] intraday_12678.csv.gz  in=256,744,741 out=22,848,903 elapsed=84.7s

  [3946/20519] intraday_12676.csv.gz  in=256,757,037 out=22,861,199 elapsed=84.7s

  [3947/20519] intraday_12679.csv.gz  in=256,768,460 out=22,872,622 elapsed=84.7s

  [3948/20519] intraday_1268.csv.gz  in=256,779,591 out=22,872,622 elapsed=84.7s

  [3949/20519] intraday_12680.csv.gz  in=256,793,627 out=22,886,658 elapsed=84.7s

  [3950/20519] intraday_12681.csv.gz  in=256,808,387 out=22,901,418 elapsed=84.7s

  [3951/20519] intraday_12682.csv.gz  in=256,821,252 out=22,914,283 elapsed=84.7s

  [3952/20519] intraday_12683.csv.gz  in=256,833,606 out=22,926,637 elapsed=84.7s

  [3953/20519] intraday_12684.csv.gz  in=256,848,725 out=22,941,756 elapsed=84.8s

  [3954/20519] intraday_12685.csv.gz  in=256,863,880 out=22,956,911 elapsed=84.8s

  [3955/20519] intraday_12686.csv.gz  in=256,877,607 out=22,970,638 elapsed=84.8s

  [3956/20519] intraday_12688.csv.gz  in=256,898,736 out=22,991,767 elapsed=84.8s

  [3957/20519] intraday_12687.csv.gz  in=256,915,074 out=23,008,105 elapsed=84.8s

  [3958/20519] intraday_12689.csv.gz  in=256,927,974 out=23,021,005 elapsed=84.8s

  [3959/20519] intraday_1269.csv.gz  in=256,939,211 out=23,021,005 elapsed=84.8s

  [3960/20519] intraday_12690.csv.gz  in=256,955,293 out=23,037,087 elapsed=84.9s

  [3961/20519] intraday_12692.csv.gz  in=256,967,744 out=23,049,538 elapsed=84.9s

  [3962/20519] intraday_12691.csv.gz  in=256,980,985 out=23,062,779 elapsed=84.9s

  [3963/20519] intraday_12694.csv.gz  in=256,993,306 out=23,075,100 elapsed=84.9s

  [3964/20519] intraday_12693.csv.gz  in=257,010,542 out=23,089,416 elapsed=85.0s

  [3965/20519] intraday_12695.csv.gz  in=257,022,489 out=23,101,363 elapsed=85.0s

  [3966/20519] intraday_12696.csv.gz  in=257,034,362 out=23,113,236 elapsed=85.0s

  [3967/20519] intraday_12697.csv.gz  in=257,046,913 out=23,125,787 elapsed=85.0s

  [3968/20519] intraday_12698.csv.gz  in=257,060,900 out=23,139,774 elapsed=85.0s

  [3969/20519] intraday_1270.csv.gz  in=257,071,656 out=23,139,774 elapsed=85.0s

  [3970/20519] intraday_12699.csv.gz  in=257,085,186 out=23,153,304 elapsed=85.0s

  [3971/20519] intraday_12700.csv.gz  in=257,097,410 out=23,165,528 elapsed=85.0s

  [3972/20519] intraday_12701.csv.gz  in=257,108,657 out=23,176,775 elapsed=85.0s

  [3973/20519] intraday_12702.csv.gz  in=257,122,295 out=23,190,413 elapsed=85.0s

  [3974/20519] intraday_12703.csv.gz  in=257,134,426 out=23,202,544 elapsed=85.1s

  [3975/20519] intraday_12704.csv.gz  in=257,146,273 out=23,214,391 elapsed=85.1s

  [3976/20519] intraday_12705.csv.gz  in=257,160,829 out=23,228,947 elapsed=85.1s

  [3977/20519] intraday_12706.csv.gz  in=257,177,201 out=23,245,319 elapsed=85.1s

  [3978/20519] intraday_12708.csv.gz  in=257,192,972 out=23,261,090 elapsed=85.1s

  [3979/20519] intraday_12707.csv.gz  in=257,206,698 out=23,274,816 elapsed=85.1s

  [3980/20519] intraday_12709.csv.gz  in=257,218,350 out=23,286,468 elapsed=85.1s

  [3981/20519] intraday_1271.csv.gz  in=257,241,901 out=23,286,468 elapsed=85.1s

  [3982/20519] intraday_12711.csv.gz  in=257,252,593 out=23,297,160 elapsed=85.2s

  [3983/20519] intraday_12710.csv.gz  in=257,264,947 out=23,309,514 elapsed=85.2s

  [3984/20519] intraday_12713.csv.gz  in=257,275,020 out=23,319,587 elapsed=85.2s

  [3985/20519] intraday_12712.csv.gz  in=257,287,594 out=23,332,161 elapsed=85.2s

  [3986/20519] intraday_12716.csv.gz  in=257,294,361 out=23,338,928 elapsed=85.3s

  [3987/20519] intraday_12714.csv.gz  in=257,300,474 out=23,345,041 elapsed=85.3s

  [3988/20519] intraday_12715.csv.gz  in=257,315,237 out=23,359,804 elapsed=85.3s

  [3989/20519] intraday_12717.csv.gz  in=257,331,616 out=23,376,183 elapsed=85.3s

  [3990/20519] intraday_12718.csv.gz  in=257,345,526 out=23,390,093 elapsed=85.3s

  [3991/20519] intraday_12719.csv.gz  in=257,358,261 out=23,402,828 elapsed=85.3s

  [3992/20519] intraday_1272.csv.gz  in=257,371,457 out=23,402,828 elapsed=85.3s

  [3993/20519] intraday_12720.csv.gz  in=257,381,395 out=23,412,766 elapsed=85.4s

  [3994/20519] intraday_12722.csv.gz  in=257,394,716 out=23,426,087 elapsed=85.4s

  [3995/20519] intraday_12721.csv.gz  in=257,407,190 out=23,438,561 elapsed=85.4s

  [3996/20519] intraday_12724.csv.gz  in=257,417,645 out=23,449,016 elapsed=85.4s

  [3997/20519] intraday_12723.csv.gz  in=257,433,045 out=23,464,416 elapsed=85.4s

  [3998/20519] intraday_12725.csv.gz  in=257,446,939 out=23,478,310 elapsed=85.4s

  [3999/20519] intraday_12727.csv.gz  in=257,459,385 out=23,490,756 elapsed=85.5s

  [4000/20519] intraday_12726.csv.gz  in=257,472,428 out=23,503,799 elapsed=85.5s

  [4001/20519] intraday_12728.csv.gz  in=257,484,066 out=23,515,437 elapsed=85.5s

  [4002/20519] intraday_1273.csv.gz  in=257,502,141 out=23,515,437 elapsed=85.5s

  [4003/20519] intraday_12729.csv.gz  in=257,528,383 out=23,532,164 elapsed=85.5s

  [4004/20519] intraday_12732.csv.gz  in=257,537,645 out=23,541,426 elapsed=85.5s

  [4005/20519] intraday_12730.csv.gz  in=257,550,585 out=23,554,366 elapsed=85.6s

  [4006/20519] intraday_12731.csv.gz  in=257,560,580 out=23,564,361 elapsed=85.6s

  [4007/20519] intraday_12733.csv.gz  in=257,574,909 out=23,578,690 elapsed=85.6s

  [4008/20519] intraday_12737.csv.gz  in=257,585,270 out=23,589,024 elapsed=85.6s

  [4009/20519] intraday_12736.csv.gz  in=257,596,351 out=23,600,105 elapsed=85.6s

  [4010/20519] intraday_12734.csv.gz  in=257,608,586 out=23,612,340 elapsed=85.6s

  [4011/20519] intraday_12735.csv.gz  in=257,618,764 out=23,622,518 elapsed=85.6s

  [4012/20519] intraday_12738.csv.gz  in=257,630,827 out=23,634,577 elapsed=85.7s

  [4013/20519] intraday_12739.csv.gz  in=257,643,134 out=23,646,884 elapsed=85.7s

  [4014/20519] intraday_1274.csv.gz  in=257,659,354 out=23,646,884 elapsed=85.7s

  [4015/20519] intraday_12740.csv.gz  in=257,670,784 out=23,658,314 elapsed=85.7s

  [4016/20519] intraday_12741.csv.gz  in=257,686,021 out=23,673,551 elapsed=85.7s

  [4017/20519] intraday_12743.csv.gz  in=257,698,769 out=23,686,299 elapsed=85.7s

  [4018/20519] intraday_12742.csv.gz  in=257,709,974 out=23,697,027 elapsed=85.7s

  [4019/20519] intraday_12744.csv.gz  in=257,722,772 out=23,709,825 elapsed=85.8s

  [4020/20519] intraday_12746.csv.gz  in=257,736,365 out=23,723,418 elapsed=85.8s

  [4021/20519] intraday_12745.csv.gz  in=257,748,046 out=23,735,099 elapsed=85.8s

  [4022/20519] intraday_12747.csv.gz  in=257,765,243 out=23,750,651 elapsed=85.8s

  [4023/20519] intraday_12748.csv.gz  in=257,778,566 out=23,763,974 elapsed=85.8s

  [4024/20519] intraday_12749.csv.gz  in=257,788,985 out=23,774,393 elapsed=85.8s

  [4025/20519] intraday_1275.csv.gz  in=257,800,535 out=23,774,393 elapsed=85.8s

  [4026/20519] intraday_12750.csv.gz  in=257,813,324 out=23,787,182 elapsed=85.8s

  [4027/20519] intraday_12751.csv.gz  in=257,826,405 out=23,800,263 elapsed=85.9s

  [4028/20519] intraday_12752.csv.gz  in=257,839,814 out=23,813,672 elapsed=85.9s

  [4029/20519] intraday_12753.csv.gz  in=257,852,515 out=23,826,373 elapsed=85.9s

  [4030/20519] intraday_12754.csv.gz  in=257,863,097 out=23,836,955 elapsed=85.9s

  [4031/20519] intraday_12756.csv.gz  in=257,873,128 out=23,846,986 elapsed=85.9s

  [4032/20519] intraday_12755.csv.gz  in=257,884,470 out=23,858,328 elapsed=85.9s

  [4033/20519] intraday_12757.csv.gz  in=257,895,133 out=23,868,991 elapsed=85.9s

  [4034/20519] intraday_12759.csv.gz  in=257,906,324 out=23,880,182 elapsed=86.0s

  [4035/20519] intraday_12758.csv.gz  in=257,919,724 out=23,893,582 elapsed=86.0s

  [4036/20519] intraday_1276.csv.gz  in=257,932,551 out=23,893,582 elapsed=86.0s

  [4037/20519] intraday_12760.csv.gz  in=257,944,926 out=23,905,957 elapsed=86.0s

  [4038/20519] intraday_12761.csv.gz  in=257,959,119 out=23,920,150 elapsed=86.0s

  [4039/20519] intraday_12763.csv.gz  in=257,970,338 out=23,931,369 elapsed=86.0s

  [4040/20519] intraday_12762.csv.gz  in=257,981,825 out=23,942,856 elapsed=86.0s

  [4041/20519] intraday_12765.csv.gz  in=257,994,103 out=23,955,134 elapsed=86.1s

  [4042/20519] intraday_12764.csv.gz  in=258,006,220 out=23,966,222 elapsed=86.1s

  [4043/20519] intraday_12766.csv.gz  in=258,016,683 out=23,976,685 elapsed=86.1s

  [4044/20519] intraday_12767.csv.gz  in=258,028,361 out=23,988,363 elapsed=86.1s

  [4045/20519] intraday_12768.csv.gz  in=258,039,354 out=23,999,356 elapsed=86.1s

  [4046/20519] intraday_12769.csv.gz  in=258,052,608 out=24,012,512 elapsed=86.1s

  [4047/20519] intraday_1277.csv.gz  in=258,064,537 out=24,012,512 elapsed=86.1s

  [4048/20519] intraday_12770.csv.gz  in=258,076,474 out=24,024,449 elapsed=86.1s

  [4049/20519] intraday_12771.csv.gz  in=258,088,231 out=24,036,206 elapsed=86.1s

  [4050/20519] intraday_12772.csv.gz  in=258,101,967 out=24,049,942 elapsed=86.2s

  [4051/20519] intraday_12773.csv.gz  in=258,112,774 out=24,060,749 elapsed=86.2s

  [4052/20519] intraday_12775.csv.gz  in=258,122,667 out=24,070,642 elapsed=86.2s

  [4053/20519] intraday_12774.csv.gz  in=258,134,757 out=24,082,732 elapsed=86.2s

  [4054/20519] intraday_12776.csv.gz  in=258,146,379 out=24,094,354 elapsed=86.2s

  [4055/20519] intraday_12777.csv.gz  in=258,159,841 out=24,107,816 elapsed=86.2s

  [4056/20519] intraday_12778.csv.gz  in=258,170,837 out=24,118,812 elapsed=86.2s

  [4057/20519] intraday_12779.csv.gz  in=258,182,611 out=24,130,586 elapsed=86.3s

  [4058/20519] intraday_1278.csv.gz  in=258,195,271 out=24,130,586 elapsed=86.3s

  [4059/20519] intraday_12781.csv.gz  in=258,204,167 out=24,139,482 elapsed=86.3s

  [4060/20519] intraday_12780.csv.gz  in=258,216,025 out=24,151,340 elapsed=86.3s

  [4061/20519] intraday_12782.csv.gz  in=258,229,491 out=24,164,806 elapsed=86.3s

  [4062/20519] intraday_12783.csv.gz  in=258,243,271 out=24,178,586 elapsed=86.4s

  [4063/20519] intraday_12784.csv.gz  in=258,256,496 out=24,191,811 elapsed=86.4s

  [4064/20519] intraday_12785.csv.gz  in=258,269,933 out=24,205,248 elapsed=86.4s

  [4065/20519] intraday_12786.csv.gz  in=258,285,875 out=24,218,181 elapsed=86.4s

  [4066/20519] intraday_12787.csv.gz  in=258,296,504 out=24,228,810 elapsed=86.4s

  [4067/20519] intraday_12788.csv.gz  in=258,308,339 out=24,240,645 elapsed=86.4s

  [4068/20519] intraday_12789.csv.gz  in=258,320,815 out=24,253,121 elapsed=86.4s

  [4069/20519] intraday_1279.csv.gz  in=258,332,726 out=24,253,121 elapsed=86.5s

  [4070/20519] intraday_12790.csv.gz  in=258,344,329 out=24,264,724 elapsed=86.5s

  [4071/20519] intraday_12791.csv.gz  in=258,357,843 out=24,278,238 elapsed=86.5s

  [4072/20519] intraday_12792.csv.gz  in=258,369,919 out=24,290,314 elapsed=86.5s

  [4073/20519] intraday_12793.csv.gz  in=258,386,376 out=24,302,850 elapsed=86.5s

  [4074/20519] intraday_12794.csv.gz  in=258,396,320 out=24,312,794 elapsed=86.5s

  [4075/20519] intraday_12795.csv.gz  in=258,409,744 out=24,326,218 elapsed=86.5s

  [4076/20519] intraday_12796.csv.gz  in=258,420,981 out=24,337,455 elapsed=86.5s

  [4077/20519] intraday_12798.csv.gz  in=258,432,508 out=24,348,982 elapsed=86.6s

  [4078/20519] intraday_12797.csv.gz  in=258,444,139 out=24,360,613 elapsed=86.6s

  [4079/20519] intraday_1280.csv.gz  in=258,454,940 out=24,360,613 elapsed=86.6s

  [4080/20519] intraday_12799.csv.gz  in=258,465,121 out=24,370,794 elapsed=86.6s

  [4081/20519] intraday_12800.csv.gz  in=258,478,137 out=24,383,810 elapsed=86.6s

  [4082/20519] intraday_12801.csv.gz  in=258,490,818 out=24,396,491 elapsed=86.6s

  [4083/20519] intraday_12803.csv.gz  in=258,504,528 out=24,410,201 elapsed=86.7s

  [4084/20519] intraday_12802.csv.gz  in=258,520,984 out=24,426,657 elapsed=86.7s

  [4085/20519] intraday_12804.csv.gz  in=258,532,974 out=24,438,647 elapsed=86.7s

  [4086/20519] intraday_12805.csv.gz  in=258,543,342 out=24,449,015 elapsed=86.7s

  [4087/20519] intraday_12806.csv.gz  in=258,555,732 out=24,461,405 elapsed=86.7s

  [4088/20519] intraday_12809.csv.gz  in=258,567,651 out=24,471,532 elapsed=86.7s

  [4089/20519] intraday_12807.csv.gz  in=258,580,242 out=24,484,123 elapsed=86.7s

  [4090/20519] intraday_12808.csv.gz  in=258,594,652 out=24,498,533 elapsed=86.7s

  [4091/20519] intraday_1281.csv.gz  in=258,609,273 out=24,498,533 elapsed=86.8s

  [4092/20519] intraday_12811.csv.gz  in=258,623,219 out=24,512,479 elapsed=86.8s

  [4093/20519] intraday_12812.csv.gz  in=258,635,242 out=24,524,474 elapsed=86.8s

  [4094/20519] intraday_12810.csv.gz  in=258,649,450 out=24,538,682 elapsed=86.8s

  [4095/20519] intraday_12813.csv.gz  in=258,676,756 out=24,553,750 elapsed=86.8s

  [4096/20519] intraday_12814.csv.gz  in=258,689,272 out=24,566,266 elapsed=86.8s

  [4097/20519] intraday_12815.csv.gz  in=258,702,662 out=24,579,656 elapsed=86.9s

  [4098/20519] intraday_12816.csv.gz  in=258,711,938 out=24,588,932 elapsed=86.9s

  [4099/20519] intraday_12817.csv.gz  in=258,724,262 out=24,601,256 elapsed=86.9s

  [4100/20519] intraday_1282.csv.gz  in=258,735,641 out=24,601,256 elapsed=86.9s

  [4101/20519] intraday_12819.csv.gz  in=258,748,048 out=24,613,663 elapsed=86.9s

  [4102/20519] intraday_12818.csv.gz  in=258,759,078 out=24,624,693 elapsed=86.9s

  [4103/20519] intraday_12820.csv.gz  in=258,773,222 out=24,638,837 elapsed=86.9s

  [4104/20519] intraday_12821.csv.gz  in=258,785,056 out=24,650,671 elapsed=86.9s

  [4105/20519] intraday_12822.csv.gz  in=258,799,640 out=24,665,255 elapsed=87.0s

  [4106/20519] intraday_12824.csv.gz  in=258,815,776 out=24,680,185 elapsed=87.0s

  [4107/20519] intraday_12823.csv.gz  in=258,828,385 out=24,692,794 elapsed=87.0s

  [4108/20519] intraday_12826.csv.gz  in=258,840,380 out=24,704,789 elapsed=87.0s

  [4109/20519] intraday_12825.csv.gz  in=258,852,525 out=24,716,934 elapsed=87.0s

  [4110/20519] intraday_12827.csv.gz  in=258,865,415 out=24,729,824 elapsed=87.0s

  [4111/20519] intraday_12829.csv.gz  in=258,877,536 out=24,741,945 elapsed=87.0s

  [4112/20519] intraday_12828.csv.gz  in=258,891,741 out=24,756,150 elapsed=87.0s

  [4113/20519] intraday_12830.csv.gz  in=258,904,526 out=24,768,935 elapsed=87.1s

  [4114/20519] intraday_1283.csv.gz  in=258,916,397 out=24,768,935 elapsed=87.1s

  [4115/20519] intraday_12831.csv.gz  in=258,930,479 out=24,783,017 elapsed=87.1s

  [4116/20519] intraday_12832.csv.gz  in=258,944,552 out=24,797,090 elapsed=87.1s

  [4117/20519] intraday_12834.csv.gz  in=258,959,819 out=24,812,357 elapsed=87.1s

  [4118/20519] intraday_12833.csv.gz  in=258,971,670 out=24,824,208 elapsed=87.1s

  [4119/20519] intraday_12836.csv.gz  in=258,984,593 out=24,837,131 elapsed=87.1s

  [4120/20519] intraday_12835.csv.gz  in=259,004,012 out=24,856,550 elapsed=87.1s

  [4121/20519] intraday_12838.csv.gz  in=259,016,290 out=24,868,828 elapsed=87.2s

  [4122/20519] intraday_12839.csv.gz  in=259,028,680 out=24,881,218 elapsed=87.2s

  [4123/20519] intraday_12837.csv.gz  in=259,043,801 out=24,896,339 elapsed=87.2s

  [4124/20519] intraday_1284.csv.gz  in=259,055,675 out=24,896,339 elapsed=87.2s

  [4125/20519] intraday_12840.csv.gz  in=259,068,620 out=24,909,284 elapsed=87.2s

  [4126/20519] intraday_12842.csv.gz  in=259,079,128 out=24,919,792 elapsed=87.3s

  [4127/20519] intraday_12844.csv.gz  in=259,091,329 out=24,931,993 elapsed=87.3s

  [4128/20519] intraday_12843.csv.gz  in=259,103,879 out=24,943,342 elapsed=87.3s

  [4129/20519] intraday_12841.csv.gz  in=259,116,572 out=24,956,035 elapsed=87.3s

  [4130/20519] intraday_12846.csv.gz  in=259,129,689 out=24,968,238 elapsed=87.3s

  [4131/20519] intraday_12847.csv.gz  in=259,140,733 out=24,979,282 elapsed=87.4s

  [4132/20519] intraday_12845.csv.gz  in=259,154,219 out=24,992,768 elapsed=87.4s

  [4133/20519] intraday_12848.csv.gz  in=259,165,084 out=25,003,633 elapsed=87.4s

  [4134/20519] intraday_12849.csv.gz  in=259,177,504 out=25,016,053 elapsed=87.4s

  [4135/20519] intraday_12850.csv.gz  in=259,187,969 out=25,026,518 elapsed=87.4s

  [4136/20519] intraday_1285.csv.gz  in=259,201,123 out=25,026,518 elapsed=87.4s

  [4137/20519] intraday_12851.csv.gz  in=259,214,030 out=25,039,425 elapsed=87.4s

  [4138/20519] intraday_12852.csv.gz  in=259,228,361 out=25,053,756 elapsed=87.4s

  [4139/20519] intraday_12853.csv.gz  in=259,243,583 out=25,068,978 elapsed=87.5s

  [4140/20519] intraday_12854.csv.gz  in=259,256,746 out=25,082,141 elapsed=87.5s

  [4141/20519] intraday_12855.csv.gz  in=259,269,888 out=25,095,283 elapsed=87.5s

  [4142/20519] intraday_12856.csv.gz  in=259,282,057 out=25,107,452 elapsed=87.5s

  [4143/20519] intraday_12857.csv.gz  in=259,296,700 out=25,120,277 elapsed=87.5s

  [4144/20519] intraday_12858.csv.gz  in=259,308,425 out=25,132,002 elapsed=87.5s

  [4145/20519] intraday_12860.csv.gz  in=259,317,866 out=25,141,443 elapsed=87.5s

  [4146/20519] intraday_1286.csv.gz  in=259,350,680 out=25,141,443 elapsed=87.5s

  [4147/20519] intraday_12859.csv.gz  in=259,364,023 out=25,154,786 elapsed=87.5s

  [4148/20519] intraday_12863.csv.gz  in=259,370,229 out=25,160,992 elapsed=87.6s

  [4149/20519] intraday_12861.csv.gz  in=259,377,395 out=25,168,158 elapsed=87.6s

  [4150/20519] intraday_12862.csv.gz  in=259,391,221 out=25,181,984 elapsed=87.6s

  [4151/20519] intraday_12865.csv.gz  in=259,403,869 out=25,194,632 elapsed=87.6s

  [4152/20519] intraday_12864.csv.gz  in=259,419,387 out=25,210,150 elapsed=87.6s

  [4153/20519] intraday_12866.csv.gz  in=259,431,351 out=25,222,114 elapsed=87.6s

  [4154/20519] intraday_12867.csv.gz  in=259,442,388 out=25,233,151 elapsed=87.6s

  [4155/20519] intraday_12868.csv.gz  in=259,453,896 out=25,244,659 elapsed=87.7s

  [4156/20519] intraday_12869.csv.gz  in=259,467,152 out=25,257,915 elapsed=87.7s

  [4157/20519] intraday_12870.csv.gz  in=259,479,902 out=25,270,665 elapsed=87.7s

  [4158/20519] intraday_1287.csv.gz  in=259,500,776 out=25,270,665 elapsed=87.7s

  [4159/20519] intraday_12871.csv.gz  in=259,511,346 out=25,281,235 elapsed=87.7s

  [4160/20519] intraday_12872.csv.gz  in=259,524,719 out=25,294,608 elapsed=87.7s

  [4161/20519] intraday_12874.csv.gz  in=259,536,280 out=25,306,169 elapsed=87.8s

  [4162/20519] intraday_12873.csv.gz  in=259,550,059 out=25,319,948 elapsed=87.8s

  [4163/20519] intraday_12875.csv.gz  in=259,561,968 out=25,331,857 elapsed=87.8s

  [4164/20519] intraday_12878.csv.gz  in=259,571,120 out=25,341,009 elapsed=87.8s

  [4165/20519] intraday_12879.csv.gz  in=259,581,186 out=25,351,075 elapsed=87.8s

  [4166/20519] intraday_12877.csv.gz  in=259,594,418 out=25,364,307 elapsed=87.8s

  [4167/20519] intraday_12876.csv.gz  in=259,630,114 out=25,381,982 elapsed=87.9s

  [4168/20519] intraday_1288.csv.gz  in=259,643,396 out=25,381,982 elapsed=87.9s

  [4169/20519] intraday_12880.csv.gz  in=259,656,616 out=25,395,202 elapsed=87.9s

  [4170/20519] intraday_12882.csv.gz  in=259,666,331 out=25,404,917 elapsed=87.9s

  [4171/20519] intraday_12881.csv.gz  in=259,679,585 out=25,418,171 elapsed=87.9s

  [4172/20519] intraday_12884.csv.gz  in=259,690,622 out=25,429,208 elapsed=87.9s

  [4173/20519] intraday_12885.csv.gz  in=259,702,629 out=25,441,215 elapsed=87.9s

  [4174/20519] intraday_12883.csv.gz  in=259,713,372 out=25,451,958 elapsed=87.9s

  [4175/20519] intraday_12886.csv.gz  in=259,725,200 out=25,463,786 elapsed=87.9s

  [4176/20519] intraday_12888.csv.gz  in=259,738,972 out=25,477,558 elapsed=88.0s

  [4177/20519] intraday_12887.csv.gz  in=259,750,522 out=25,489,108 elapsed=88.0s

  [4178/20519] intraday_1289.csv.gz  in=259,764,839 out=25,489,108 elapsed=88.0s

  [4179/20519] intraday_12889.csv.gz  in=259,783,445 out=25,501,106 elapsed=88.0s

  [4180/20519] intraday_12890.csv.gz  in=259,796,089 out=25,513,750 elapsed=88.0s

  [4181/20519] intraday_12891.csv.gz  in=259,808,568 out=25,526,229 elapsed=88.0s

  [4182/20519] intraday_12893.csv.gz  in=259,822,585 out=25,540,246 elapsed=88.0s

  [4183/20519] intraday_12892.csv.gz  in=259,832,044 out=25,549,705 elapsed=88.0s

  [4184/20519] intraday_12894.csv.gz  in=259,846,077 out=25,563,738 elapsed=88.1s

  [4185/20519] intraday_12895.csv.gz  in=259,859,072 out=25,576,733 elapsed=88.1s

  [4186/20519] intraday_12897.csv.gz  in=259,871,813 out=25,589,474 elapsed=88.1s

  [4187/20519] intraday_12896.csv.gz  in=259,881,636 out=25,599,297 elapsed=88.1s

  [4188/20519] intraday_12898.csv.gz  in=259,893,287 out=25,610,948 elapsed=88.1s

  [4189/20519] intraday_12899.csv.gz  in=259,906,218 out=25,623,879 elapsed=88.1s

  [4190/20519] intraday_12900.csv.gz  in=259,918,473 out=25,636,134 elapsed=88.1s

  [4191/20519] intraday_1290.csv.gz  in=259,932,415 out=25,636,134 elapsed=88.1s

  [4192/20519] intraday_12901.csv.gz  in=259,943,786 out=25,647,505 elapsed=88.1s

  [4193/20519] intraday_12902.csv.gz  in=259,954,516 out=25,658,235 elapsed=88.2s

  [4194/20519] intraday_12903.csv.gz  in=259,964,186 out=25,667,905 elapsed=88.2s

  [4195/20519] intraday_12905.csv.gz  in=259,976,573 out=25,680,292 elapsed=88.2s

  [4196/20519] intraday_12904.csv.gz  in=259,986,952 out=25,690,671 elapsed=88.2s

  [4197/20519] intraday_12906.csv.gz  in=259,998,664 out=25,702,383 elapsed=88.2s

  [4198/20519] intraday_12907.csv.gz  in=260,011,024 out=25,714,743 elapsed=88.2s

  [4199/20519] intraday_12909.csv.gz  in=260,021,658 out=25,725,377 elapsed=88.2s

  [4200/20519] intraday_12908.csv.gz  in=260,035,234 out=25,738,953 elapsed=88.3s

  [4201/20519] intraday_1291.csv.gz  in=260,054,730 out=25,738,953 elapsed=88.3s

  [4202/20519] intraday_12910.csv.gz  in=260,066,281 out=25,750,504 elapsed=88.3s

  [4203/20519] intraday_12911.csv.gz  in=260,077,040 out=25,761,263 elapsed=88.3s

  [4204/20519] intraday_12912.csv.gz  in=260,089,446 out=25,773,669 elapsed=88.3s

  [4205/20519] intraday_12913.csv.gz  in=260,099,764 out=25,783,987 elapsed=88.3s

  [4206/20519] intraday_12914.csv.gz  in=260,111,486 out=25,795,709 elapsed=88.3s

  [4207/20519] intraday_12917.csv.gz  in=260,122,731 out=25,806,674 elapsed=88.4s

  [4208/20519] intraday_12916.csv.gz  in=260,136,157 out=25,820,100 elapsed=88.4s

  [4209/20519] intraday_12915.csv.gz  in=260,146,539 out=25,830,482 elapsed=88.4s

  [4210/20519] intraday_12918.csv.gz  in=260,158,966 out=25,842,909 elapsed=88.5s

  [4211/20519] intraday_12919.csv.gz  in=260,171,695 out=25,855,638 elapsed=88.5s

  [4212/20519] intraday_1292.csv.gz  in=260,181,686 out=25,855,638 elapsed=88.5s

  [4213/20519] intraday_12920.csv.gz  in=260,192,288 out=25,866,240 elapsed=88.5s

  [4214/20519] intraday_12921.csv.gz  in=260,203,011 out=25,876,963 elapsed=88.5s

  [4215/20519] intraday_12923.csv.gz  in=260,214,776 out=25,888,728 elapsed=88.5s

  [4216/20519] intraday_12922.csv.gz  in=260,225,556 out=25,899,508 elapsed=88.5s

  [4217/20519] intraday_12924.csv.gz  in=260,237,122 out=25,911,074 elapsed=88.5s

  [4218/20519] intraday_12925.csv.gz  in=260,248,970 out=25,922,922 elapsed=88.5s

  [4219/20519] intraday_12926.csv.gz  in=260,260,390 out=25,934,342 elapsed=88.6s

  [4220/20519] intraday_12928.csv.gz  in=260,269,326 out=25,943,278 elapsed=88.6s

  [4221/20519] intraday_12927.csv.gz  in=260,281,230 out=25,955,182 elapsed=88.6s

  [4222/20519] intraday_1293.csv.gz  in=260,293,324 out=25,955,182 elapsed=88.6s

  [4223/20519] intraday_12929.csv.gz  in=260,305,936 out=25,967,794 elapsed=88.6s

  [4224/20519] intraday_12930.csv.gz  in=260,319,540 out=25,981,398 elapsed=88.6s

  [4225/20519] intraday_12932.csv.gz  in=260,332,515 out=25,994,373 elapsed=88.7s

  [4226/20519] intraday_12931.csv.gz  in=260,344,310 out=26,006,168 elapsed=88.7s

  [4227/20519] intraday_12933.csv.gz  in=260,355,849 out=26,017,707 elapsed=88.7s

  [4228/20519] intraday_12934.csv.gz  in=260,365,070 out=26,026,928 elapsed=88.7s

  [4229/20519] intraday_12935.csv.gz  in=260,377,042 out=26,038,900 elapsed=88.7s

  [4230/20519] intraday_12936.csv.gz  in=260,389,066 out=26,050,924 elapsed=88.7s

  [4231/20519] intraday_12937.csv.gz  in=260,400,977 out=26,062,835 elapsed=88.8s

  [4232/20519] intraday_12938.csv.gz  in=260,413,306 out=26,075,164 elapsed=88.8s

  [4233/20519] intraday_12939.csv.gz  in=260,425,283 out=26,087,141 elapsed=88.8s

  [4234/20519] intraday_1294.csv.gz  in=260,437,723 out=26,087,141 elapsed=88.8s

  [4235/20519] intraday_12940.csv.gz  in=260,447,053 out=26,096,471 elapsed=88.8s

  [4236/20519] intraday_12941.csv.gz  in=260,458,303 out=26,107,721 elapsed=88.8s

  [4237/20519] intraday_12943.csv.gz  in=260,470,209 out=26,119,627 elapsed=88.8s

  [4238/20519] intraday_12942.csv.gz  in=260,484,666 out=26,134,084 elapsed=88.8s

  [4239/20519] intraday_12944.csv.gz  in=260,495,937 out=26,145,355 elapsed=88.9s

  [4240/20519] intraday_12945.csv.gz  in=260,505,703 out=26,155,121 elapsed=88.9s

  [4241/20519] intraday_12946.csv.gz  in=260,516,376 out=26,165,794 elapsed=88.9s

  [4242/20519] intraday_12948.csv.gz  in=260,529,254 out=26,178,672 elapsed=88.9s

  [4243/20519] intraday_12947.csv.gz  in=260,541,405 out=26,190,823 elapsed=88.9s

  [4244/20519] intraday_1295.csv.gz  in=260,553,862 out=26,190,823 elapsed=88.9s

  [4245/20519] intraday_12951.csv.gz  in=260,565,506 out=26,202,467 elapsed=88.9s

  [4246/20519] intraday_12949.csv.gz  in=260,580,124 out=26,217,085 elapsed=88.9s

  [4247/20519] intraday_12952.csv.gz  in=260,591,596 out=26,228,557 elapsed=89.0s

  [4248/20519] intraday_12953.csv.gz  in=260,602,639 out=26,239,600 elapsed=89.0s

  [4249/20519] intraday_12954.csv.gz  in=260,616,555 out=26,253,516 elapsed=89.0s

  [4250/20519] intraday_12956.csv.gz  in=260,626,960 out=26,263,921 elapsed=89.0s

  [4251/20519] intraday_12955.csv.gz  in=260,638,891 out=26,275,852 elapsed=89.0s

  [4252/20519] intraday_12950.csv.gz  in=260,653,424 out=26,290,385 elapsed=89.0s

  [4253/20519] intraday_12957.csv.gz  in=260,669,165 out=26,306,126 elapsed=89.0s

  [4254/20519] intraday_12958.csv.gz  in=260,680,228 out=26,317,189 elapsed=89.1s

  [4255/20519] intraday_1296.csv.gz  in=260,697,066 out=26,317,189 elapsed=89.1s

  [4256/20519] intraday_12959.csv.gz  in=260,709,228 out=26,329,351 elapsed=89.1s

  [4257/20519] intraday_12960.csv.gz  in=260,721,439 out=26,341,562 elapsed=89.1s

  [4258/20519] intraday_12962.csv.gz  in=260,733,258 out=26,353,381 elapsed=89.1s

  [4259/20519] intraday_12961.csv.gz  in=260,745,110 out=26,365,233 elapsed=89.1s

  [4260/20519] intraday_12963.csv.gz  in=260,756,922 out=26,377,045 elapsed=89.1s

  [4261/20519] intraday_12965.csv.gz  in=260,767,882 out=26,388,005 elapsed=89.1s

  [4262/20519] intraday_12964.csv.gz  in=260,778,194 out=26,398,317 elapsed=89.2s

  [4263/20519] intraday_12967.csv.gz  in=260,790,024 out=26,410,147 elapsed=89.2s

  [4264/20519] intraday_12966.csv.gz  in=260,802,642 out=26,422,765 elapsed=89.2s

  [4265/20519] intraday_12968.csv.gz  in=260,813,730 out=26,433,853 elapsed=89.2s

  [4266/20519] intraday_1297.csv.gz  in=260,834,585 out=26,433,853 elapsed=89.2s

  [4267/20519] intraday_12969.csv.gz  in=260,848,514 out=26,447,782 elapsed=89.2s

  [4268/20519] intraday_12970.csv.gz  in=260,860,158 out=26,459,426 elapsed=89.2s

  [4269/20519] intraday_12971.csv.gz  in=260,875,435 out=26,474,703 elapsed=89.2s

  [4270/20519] intraday_12972.csv.gz  in=260,885,759 out=26,485,018 elapsed=89.3s

  [4271/20519] intraday_12975.csv.gz  in=260,900,010 out=26,499,269 elapsed=89.3s

  [4272/20519] intraday_12974.csv.gz  in=260,914,112 out=26,513,371 elapsed=89.3s

  [4273/20519] intraday_12973.csv.gz  in=260,930,822 out=26,525,852 elapsed=89.3s

  [4274/20519] intraday_12977.csv.gz  in=260,943,495 out=26,538,525 elapsed=89.3s

  [4275/20519] intraday_12976.csv.gz  in=260,954,017 out=26,549,047 elapsed=89.3s

  [4276/20519] intraday_12978.csv.gz  in=260,967,994 out=26,563,024 elapsed=89.4s

  [4277/20519] intraday_12980.csv.gz  in=260,980,617 out=26,575,647 elapsed=89.4s

  [4278/20519] intraday_1298.csv.gz  in=260,999,506 out=26,575,647 elapsed=89.4s

  [4279/20519] intraday_12979.csv.gz  in=261,013,580 out=26,589,721 elapsed=89.4s

  [4280/20519] intraday_12981.csv.gz  in=261,027,760 out=26,603,901 elapsed=89.4s

  [4281/20519] intraday_12983.csv.gz  in=261,039,687 out=26,615,828 elapsed=89.5s

  [4282/20519] intraday_12984.csv.gz  in=261,055,101 out=26,631,242 elapsed=89.5s

  [4283/20519] intraday_12982.csv.gz  in=261,073,462 out=26,649,603 elapsed=89.5s

  [4284/20519] intraday_12985.csv.gz  in=261,083,343 out=26,659,484 elapsed=89.5s

  [4285/20519] intraday_12986.csv.gz  in=261,096,897 out=26,673,038 elapsed=89.5s

  [4286/20519] intraday_12989.csv.gz  in=261,107,692 out=26,683,833 elapsed=89.5s

  [4287/20519] intraday_12987.csv.gz  in=261,119,722 out=26,695,863 elapsed=89.5s

  [4288/20519] intraday_12988.csv.gz  in=261,132,229 out=26,708,370 elapsed=89.5s

  [4289/20519] intraday_1299.csv.gz  in=261,146,837 out=26,708,370 elapsed=89.6s

  [4290/20519] intraday_12990.csv.gz  in=261,158,490 out=26,720,023 elapsed=89.6s

  [4291/20519] intraday_12991.csv.gz  in=261,170,068 out=26,731,601 elapsed=89.6s

  [4292/20519] intraday_12992.csv.gz  in=261,183,126 out=26,744,659 elapsed=89.6s

  [4293/20519] intraday_12993.csv.gz  in=261,194,811 out=26,756,344 elapsed=89.6s

  [4294/20519] intraday_12994.csv.gz  in=261,207,182 out=26,768,715 elapsed=89.7s

  [4295/20519] intraday_12995.csv.gz  in=261,217,194 out=26,778,727 elapsed=89.7s

  [4296/20519] intraday_12996.csv.gz  in=261,230,745 out=26,792,278 elapsed=89.7s

  [4297/20519] intraday_12997.csv.gz  in=261,240,907 out=26,802,440 elapsed=89.7s

  [4298/20519] intraday_1300.csv.gz  in=261,253,416 out=26,802,440 elapsed=89.7s

  [4299/20519] intraday_12999.csv.gz  in=261,267,255 out=26,816,279 elapsed=89.7s

  [4300/20519] intraday_12998.csv.gz  in=261,280,408 out=26,829,432 elapsed=89.7s

  [4301/20519] intraday_13000.csv.gz  in=261,294,911 out=26,843,935 elapsed=89.8s

  [4302/20519] intraday_13001.csv.gz  in=261,308,454 out=26,857,478 elapsed=89.8s

  [4303/20519] intraday_13002.csv.gz  in=261,321,789 out=26,870,813 elapsed=89.8s

  [4304/20519] intraday_13003.csv.gz  in=261,333,142 out=26,882,166 elapsed=89.8s

  [4305/20519] intraday_13004.csv.gz  in=261,345,560 out=26,894,584 elapsed=89.8s

  [4306/20519] intraday_13005.csv.gz  in=261,356,562 out=26,905,586 elapsed=89.8s

  [4307/20519] intraday_13006.csv.gz  in=261,369,897 out=26,918,921 elapsed=89.9s

  [4308/20519] intraday_13008.csv.gz  in=261,377,534 out=26,926,558 elapsed=89.9s

  [4309/20519] intraday_13009.csv.gz  in=261,391,283 out=26,940,307 elapsed=89.9s

  [4310/20519] intraday_13007.csv.gz  in=261,400,013 out=26,949,037 elapsed=89.9s

  [4311/20519] intraday_13010.csv.gz  in=261,403,887 out=26,952,911 elapsed=89.9s

  [4312/20519] intraday_1301.csv.gz  in=261,416,387 out=26,952,911 elapsed=89.9s

  [4313/20519] intraday_13011.csv.gz  in=261,417,107 out=26,952,911 elapsed=89.9s

  [4314/20519] intraday_13012.csv.gz  in=261,434,467 out=26,970,271 elapsed=89.9s

  [4315/20519] intraday_13014.csv.gz  in=261,447,196 out=26,983,000 elapsed=90.0s

  [4316/20519] intraday_13015.csv.gz  in=261,457,713 out=26,993,517 elapsed=90.0s

  [4317/20519] intraday_13013.csv.gz  in=261,470,746 out=27,006,550 elapsed=90.0s

  [4318/20519] intraday_13016.csv.gz  in=261,483,500 out=27,019,304 elapsed=90.0s

  [4319/20519] intraday_13017.csv.gz  in=261,498,074 out=27,033,878 elapsed=90.0s

  [4320/20519] intraday_13018.csv.gz  in=261,510,897 out=27,046,701 elapsed=90.0s

  [4321/20519] intraday_13019.csv.gz  in=261,522,950 out=27,058,754 elapsed=90.0s

  [4322/20519] intraday_1302.csv.gz  in=261,536,197 out=27,058,754 elapsed=90.0s

  [4323/20519] intraday_13021.csv.gz  in=261,548,829 out=27,071,386 elapsed=90.1s

  [4324/20519] intraday_13022.csv.gz  in=261,561,964 out=27,084,521 elapsed=90.1s

  [4325/20519] intraday_13020.csv.gz  in=261,575,903 out=27,098,460 elapsed=90.1s

  [4326/20519] intraday_13023.csv.gz  in=261,588,152 out=27,110,709 elapsed=90.1s

  [4327/20519] intraday_13024.csv.gz  in=261,602,772 out=27,125,329 elapsed=90.1s

  [4328/20519] intraday_13025.csv.gz  in=261,615,995 out=27,138,552 elapsed=90.4s

  [4329/20519] intraday_13026.csv.gz  in=261,625,781 out=27,148,338 elapsed=90.4s

  [4330/20519] intraday_13028.csv.gz  in=261,639,604 out=27,162,161 elapsed=90.4s

  [4331/20519] intraday_13027.csv.gz  in=261,649,646 out=27,172,203 elapsed=90.4s

  [4332/20519] intraday_1303.csv.gz  in=261,662,314 out=27,172,203 elapsed=90.4s

  [4333/20519] intraday_13029.csv.gz  in=261,676,137 out=27,186,026 elapsed=90.4s

  [4334/20519] intraday_13030.csv.gz  in=261,686,113 out=27,196,002 elapsed=90.4s

  [4335/20519] intraday_13031.csv.gz  in=261,696,615 out=27,206,504 elapsed=90.5s

  [4336/20519] intraday_13032.csv.gz  in=261,708,570 out=27,218,459 elapsed=90.5s

  [4337/20519] intraday_13033.csv.gz  in=261,720,496 out=27,230,385 elapsed=90.5s

  [4338/20519] intraday_13034.csv.gz  in=261,733,379 out=27,243,268 elapsed=90.5s

  [4339/20519] intraday_13035.csv.gz  in=261,745,952 out=27,255,841 elapsed=90.5s

  [4340/20519] intraday_13036.csv.gz  in=261,760,540 out=27,270,429 elapsed=90.5s

  [4341/20519] intraday_13038.csv.gz  in=261,772,774 out=27,282,663 elapsed=90.5s

  [4342/20519] intraday_13037.csv.gz  in=261,784,270 out=27,293,775 elapsed=90.5s

  [4343/20519] intraday_1304.csv.gz  in=261,795,444 out=27,293,775 elapsed=90.5s

  [4344/20519] intraday_13039.csv.gz  in=261,808,095 out=27,306,426 elapsed=90.5s

  [4345/20519] intraday_13040.csv.gz  in=261,819,577 out=27,317,908 elapsed=90.5s

  [4346/20519] intraday_13042.csv.gz  in=261,836,358 out=27,334,689 elapsed=90.6s

  [4347/20519] intraday_13041.csv.gz  in=261,849,024 out=27,347,355 elapsed=90.6s

  [4348/20519] intraday_13043.csv.gz  in=261,862,764 out=27,361,095 elapsed=90.6s

  [4349/20519] intraday_13044.csv.gz  in=261,873,298 out=27,371,629 elapsed=90.6s

  [4350/20519] intraday_13045.csv.gz  in=261,885,010 out=27,383,341 elapsed=90.6s

  [4351/20519] intraday_13046.csv.gz  in=261,897,522 out=27,395,853 elapsed=90.6s

  [4352/20519] intraday_13047.csv.gz  in=261,911,013 out=27,409,344 elapsed=90.6s

  [4353/20519] intraday_13048.csv.gz  in=261,923,476 out=27,421,807 elapsed=90.6s

  [4354/20519] intraday_13049.csv.gz  in=261,934,855 out=27,433,186 elapsed=90.7s

  [4355/20519] intraday_1305.csv.gz  in=261,946,629 out=27,433,186 elapsed=90.7s

  [4356/20519] intraday_13050.csv.gz  in=261,958,234 out=27,444,791 elapsed=90.7s

  [4357/20519] intraday_13051.csv.gz  in=261,967,429 out=27,453,986 elapsed=90.7s

  [4358/20519] intraday_13053.csv.gz  in=261,980,295 out=27,466,852 elapsed=90.7s

  [4359/20519] intraday_13052.csv.gz  in=261,991,258 out=27,477,815 elapsed=90.7s

  [4360/20519] intraday_13054.csv.gz  in=262,004,637 out=27,491,194 elapsed=90.7s

  [4361/20519] intraday_13055.csv.gz  in=262,016,856 out=27,503,413 elapsed=90.7s

  [4362/20519] intraday_13056.csv.gz  in=262,031,274 out=27,517,831 elapsed=90.8s

  [4363/20519] intraday_13057.csv.gz  in=262,041,643 out=27,528,200 elapsed=90.8s

  [4364/20519] intraday_13059.csv.gz  in=262,054,445 out=27,541,002 elapsed=90.8s

  [4365/20519] intraday_1306.csv.gz  in=262,066,304 out=27,541,002 elapsed=90.8s

  [4366/20519] intraday_13058.csv.gz  in=262,078,384 out=27,553,082 elapsed=90.8s

  [4367/20519] intraday_13060.csv.gz  in=262,088,724 out=27,563,422 elapsed=90.8s

  [4368/20519] intraday_13061.csv.gz  in=262,100,563 out=27,575,261 elapsed=90.8s

  [4369/20519] intraday_13064.csv.gz  in=262,115,024 out=27,589,722 elapsed=90.9s

  [4370/20519] intraday_13063.csv.gz  in=262,127,271 out=27,601,969 elapsed=90.9s

  [4371/20519] intraday_13062.csv.gz  in=262,137,844 out=27,612,542 elapsed=90.9s

  [4372/20519] intraday_13066.csv.gz  in=262,151,131 out=27,625,829 elapsed=90.9s

  [4373/20519] intraday_13065.csv.gz  in=262,162,828 out=27,637,526 elapsed=90.9s

  [4374/20519] intraday_13067.csv.gz  in=262,174,956 out=27,649,654 elapsed=90.9s

  [4375/20519] intraday_13068.csv.gz  in=262,187,111 out=27,661,809 elapsed=90.9s

  [4376/20519] intraday_13069.csv.gz  in=262,199,258 out=27,673,956 elapsed=91.0s

  [4377/20519] intraday_1307.csv.gz  in=262,211,373 out=27,673,956 elapsed=91.0s

  [4378/20519] intraday_13070.csv.gz  in=262,223,976 out=27,686,559 elapsed=91.0s

  [4379/20519] intraday_13072.csv.gz  in=262,238,717 out=27,701,300 elapsed=91.0s

  [4380/20519] intraday_13071.csv.gz  in=262,250,354 out=27,712,937 elapsed=91.0s

  [4381/20519] intraday_13073.csv.gz  in=262,264,107 out=27,726,690 elapsed=91.0s

  [4382/20519] intraday_13074.csv.gz  in=262,281,465 out=27,738,995 elapsed=91.0s

  [4383/20519] intraday_13075.csv.gz  in=262,292,452 out=27,749,982 elapsed=91.1s

  [4384/20519] intraday_13077.csv.gz  in=262,308,619 out=27,766,149 elapsed=91.1s

  [4385/20519] intraday_13078.csv.gz  in=262,320,654 out=27,778,184 elapsed=91.1s

  [4386/20519] intraday_13076.csv.gz  in=262,332,276 out=27,789,806 elapsed=91.1s

  [4387/20519] intraday_13079.csv.gz  in=262,346,109 out=27,803,639 elapsed=91.1s

  [4388/20519] intraday_1308.csv.gz  in=262,357,994 out=27,803,639 elapsed=91.1s

  [4389/20519] intraday_13082.csv.gz  in=262,367,408 out=27,813,053 elapsed=91.1s

  [4390/20519] intraday_13081.csv.gz  in=262,378,557 out=27,824,202 elapsed=91.1s

  [4391/20519] intraday_13083.csv.gz  in=262,391,644 out=27,837,289 elapsed=91.1s

  [4392/20519] intraday_13080.csv.gz  in=262,404,125 out=27,849,770 elapsed=91.1s

  [4393/20519] intraday_13084.csv.gz  in=262,417,650 out=27,863,295 elapsed=91.2s

  [4394/20519] intraday_13085.csv.gz  in=262,431,047 out=27,876,692 elapsed=91.2s

  [4395/20519] intraday_13086.csv.gz  in=262,441,825 out=27,887,470 elapsed=91.2s

  [4396/20519] intraday_13087.csv.gz  in=262,454,807 out=27,900,452 elapsed=91.2s

  [4397/20519] intraday_13089.csv.gz  in=262,470,377 out=27,916,022 elapsed=91.2s

  [4398/20519] intraday_13088.csv.gz  in=262,480,283 out=27,925,928 elapsed=91.2s

  [4399/20519] intraday_1309.csv.gz  in=262,491,015 out=27,925,928 elapsed=91.2s

  [4400/20519] intraday_13092.csv.gz  in=262,502,553 out=27,937,466 elapsed=91.2s

  [4401/20519] intraday_13090.csv.gz  in=262,515,271 out=27,950,184 elapsed=91.3s

  [4402/20519] intraday_13093.csv.gz  in=262,526,260 out=27,961,173 elapsed=91.3s

  [4403/20519] intraday_13091.csv.gz  in=262,537,161 out=27,972,074 elapsed=91.3s

  [4404/20519] intraday_13094.csv.gz  in=262,549,173 out=27,984,086 elapsed=91.3s

  [4405/20519] intraday_13095.csv.gz  in=262,561,064 out=27,995,977 elapsed=91.3s

  [4406/20519] intraday_13097.csv.gz  in=262,576,624 out=28,011,537 elapsed=91.3s

  [4407/20519] intraday_13096.csv.gz  in=262,595,150 out=28,030,063 elapsed=91.4s

  [4408/20519] intraday_13099.csv.gz  in=262,606,247 out=28,041,160 elapsed=91.4s

  [4409/20519] intraday_13098.csv.gz  in=262,617,714 out=28,052,627 elapsed=91.4s

  [4410/20519] intraday_1310.csv.gz  in=262,629,361 out=28,052,627 elapsed=91.4s

  [4411/20519] intraday_13100.csv.gz  in=262,642,507 out=28,065,773 elapsed=91.4s

  [4412/20519] intraday_13101.csv.gz  in=262,653,898 out=28,077,164 elapsed=91.4s

  [4413/20519] intraday_13103.csv.gz  in=262,664,746 out=28,088,012 elapsed=91.4s

  [4414/20519] intraday_13102.csv.gz  in=262,680,304 out=28,103,570 elapsed=91.4s

  [4415/20519] intraday_13104.csv.gz  in=262,693,759 out=28,117,025 elapsed=91.5s

  [4416/20519] intraday_13106.csv.gz  in=262,706,987 out=28,130,253 elapsed=91.5s

  [4417/20519] intraday_13105.csv.gz  in=262,720,438 out=28,143,704 elapsed=91.5s

  [4418/20519] intraday_13107.csv.gz  in=262,732,869 out=28,156,135 elapsed=91.5s

  [4419/20519] intraday_13108.csv.gz  in=262,745,201 out=28,168,467 elapsed=91.5s

  [4420/20519] intraday_1311.csv.gz  in=262,756,651 out=28,168,467 elapsed=91.5s

  [4421/20519] intraday_13109.csv.gz  in=262,769,513 out=28,181,329 elapsed=91.5s

  [4422/20519] intraday_13112.csv.gz  in=262,782,436 out=28,194,252 elapsed=91.6s

  [4423/20519] intraday_13110.csv.gz  in=262,794,689 out=28,206,475 elapsed=91.6s

  [4424/20519] intraday_13111.csv.gz  in=262,807,328 out=28,219,114 elapsed=91.6s

  [4425/20519] intraday_13113.csv.gz  in=262,818,992 out=28,230,778 elapsed=91.6s

  [4426/20519] intraday_13114.csv.gz  in=262,830,972 out=28,242,758 elapsed=91.6s

  [4427/20519] intraday_13116.csv.gz  in=262,843,431 out=28,255,217 elapsed=91.6s

  [4428/20519] intraday_13115.csv.gz  in=262,857,171 out=28,268,957 elapsed=91.6s

  [4429/20519] intraday_13118.csv.gz  in=262,869,703 out=28,281,489 elapsed=91.6s

  [4430/20519] intraday_13117.csv.gz  in=262,884,677 out=28,296,463 elapsed=91.6s

  [4431/20519] intraday_1312.csv.gz  in=262,901,921 out=28,296,463 elapsed=91.7s

  [4432/20519] intraday_13120.csv.gz  in=262,913,556 out=28,308,098 elapsed=91.7s

  [4433/20519] intraday_13121.csv.gz  in=262,926,684 out=28,321,226 elapsed=91.7s

  [4434/20519] intraday_13119.csv.gz  in=262,941,495 out=28,336,037 elapsed=91.7s

  [4435/20519] intraday_13122.csv.gz  in=262,954,329 out=28,348,871 elapsed=91.7s

  [4436/20519] intraday_13125.csv.gz  in=262,969,022 out=28,363,564 elapsed=91.7s

  [4437/20519] intraday_13123.csv.gz  in=262,982,685 out=28,377,227 elapsed=91.7s

  [4438/20519] intraday_13126.csv.gz  in=262,998,229 out=28,392,771 elapsed=91.8s

  [4439/20519] intraday_13124.csv.gz  in=263,009,099 out=28,403,641 elapsed=91.8s

  [4440/20519] intraday_13127.csv.gz  in=263,023,676 out=28,418,218 elapsed=91.8s

  [4441/20519] intraday_1313.csv.gz  in=263,034,972 out=28,418,218 elapsed=91.8s

  [4442/20519] intraday_13128.csv.gz  in=263,050,878 out=28,434,124 elapsed=91.8s

  [4443/20519] intraday_13129.csv.gz  in=263,069,143 out=28,452,389 elapsed=91.8s

  [4444/20519] intraday_13131.csv.gz  in=263,085,057 out=28,468,303 elapsed=91.8s

  [4445/20519] intraday_13132.csv.gz  in=263,099,566 out=28,482,812 elapsed=91.9s

  [4446/20519] intraday_13130.csv.gz  in=263,115,252 out=28,498,498 elapsed=91.9s

  [4447/20519] intraday_13133.csv.gz  in=263,127,694 out=28,510,940 elapsed=91.9s

  [4448/20519] intraday_13134.csv.gz  in=263,139,276 out=28,522,522 elapsed=91.9s

  [4449/20519] intraday_13135.csv.gz  in=263,150,508 out=28,533,754 elapsed=91.9s

  [4450/20519] intraday_13136.csv.gz  in=263,163,512 out=28,546,758 elapsed=91.9s

  [4451/20519] intraday_13137.csv.gz  in=263,174,365 out=28,557,611 elapsed=91.9s

  [4452/20519] intraday_13138.csv.gz  in=263,186,761 out=28,570,007 elapsed=92.0s

  [4453/20519] intraday_13139.csv.gz  in=263,199,632 out=28,582,878 elapsed=92.0s

  [4454/20519] intraday_1314.csv.gz  in=263,209,179 out=28,582,878 elapsed=92.0s

  [4455/20519] intraday_13140.csv.gz  in=263,228,144 out=28,598,150 elapsed=92.0s

  [4456/20519] intraday_13141.csv.gz  in=263,238,727 out=28,608,733 elapsed=92.0s

  [4457/20519] intraday_13142.csv.gz  in=263,250,351 out=28,620,357 elapsed=92.0s

  [4458/20519] intraday_13143.csv.gz  in=263,262,845 out=28,632,851 elapsed=92.1s

  [4459/20519] intraday_13144.csv.gz  in=263,274,462 out=28,644,468 elapsed=92.1s

  [4460/20519] intraday_13145.csv.gz  in=263,287,646 out=28,657,652 elapsed=92.1s

  [4461/20519] intraday_13146.csv.gz  in=263,302,326 out=28,672,332 elapsed=92.1s

  [4462/20519] intraday_13147.csv.gz  in=263,317,898 out=28,687,904 elapsed=92.1s

  [4463/20519] intraday_13148.csv.gz  in=263,331,805 out=28,701,811 elapsed=92.1s

  [4464/20519] intraday_1315.csv.gz  in=263,343,664 out=28,701,811 elapsed=92.1s

  [4465/20519] intraday_13149.csv.gz  in=263,357,792 out=28,715,939 elapsed=92.1s

  [4466/20519] intraday_13150.csv.gz  in=263,370,226 out=28,728,373 elapsed=92.1s

  [4467/20519] intraday_13151.csv.gz  in=263,383,016 out=28,741,163 elapsed=92.2s

  [4468/20519] intraday_13152.csv.gz  in=263,396,612 out=28,754,759 elapsed=92.2s

  [4469/20519] intraday_13154.csv.gz  in=263,405,909 out=28,764,056 elapsed=92.2s

  [4470/20519] intraday_13153.csv.gz  in=263,442,963 out=28,782,246 elapsed=92.2s

  [4471/20519] intraday_13156.csv.gz  in=263,458,386 out=28,797,669 elapsed=92.2s

  [4472/20519] intraday_13157.csv.gz  in=263,463,805 out=28,803,088 elapsed=92.3s

  [4473/20519] intraday_13155.csv.gz  in=263,471,788 out=28,811,071 elapsed=92.3s

  [4474/20519] intraday_1316.csv.gz  in=263,484,666 out=28,811,071 elapsed=92.3s

  [4475/20519] intraday_13159.csv.gz  in=263,523,611 out=28,850,016 elapsed=92.4s

  [4476/20519] intraday_13158.csv.gz  in=263,571,789 out=28,898,194 elapsed=92.4s

  [4477/20519] intraday_13161.csv.gz  in=263,582,747 out=28,909,152 elapsed=92.4s

  [4478/20519] intraday_13160.csv.gz  in=263,615,108 out=28,941,513 elapsed=92.4s

  [4479/20519] intraday_13162.csv.gz  in=263,621,166 out=28,947,571 elapsed=92.4s

  [4480/20519] intraday_13165.csv.gz  in=263,654,877 out=28,981,282 elapsed=92.5s

  [4481/20519] intraday_13163.csv.gz  in=263,696,432 out=29,022,320 elapsed=92.5s

  [4482/20519] intraday_13166.csv.gz  in=263,730,156 out=29,056,044 elapsed=92.5s

  [4483/20519] intraday_13164.csv.gz  in=263,770,469 out=29,096,357 elapsed=92.5s

  [4484/20519] intraday_13167.csv.gz  in=263,808,723 out=29,134,579 elapsed=92.5s

  [4485/20519] intraday_1317.csv.gz  in=263,823,739 out=29,134,579 elapsed=92.6s

  [4486/20519] intraday_13168.csv.gz  in=263,865,336 out=29,176,176 elapsed=92.6s

  [4487/20519] intraday_13169.csv.gz  in=263,882,815 out=29,193,655 elapsed=92.6s

  [4488/20519] intraday_13170.csv.gz  in=263,901,074 out=29,211,914 elapsed=92.6s

  [4489/20519] intraday_13171.csv.gz  in=263,945,556 out=29,248,218 elapsed=92.6s

  [4490/20519] intraday_13172.csv.gz  in=263,979,365 out=29,282,027 elapsed=92.7s

  [4491/20519] intraday_13174.csv.gz  in=264,017,342 out=29,320,004 elapsed=92.7s

  [4492/20519] intraday_13173.csv.gz  in=264,054,794 out=29,357,456 elapsed=92.7s

  [4493/20519] intraday_13175.csv.gz  in=264,091,109 out=29,393,771 elapsed=92.7s

  [4494/20519] intraday_13177.csv.gz  in=264,122,794 out=29,425,456 elapsed=92.8s

  [4495/20519] intraday_13178.csv.gz  in=264,151,430 out=29,454,092 elapsed=92.8s

  [4496/20519] intraday_13176.csv.gz  in=264,199,220 out=29,497,837 elapsed=92.8s

  [4497/20519] intraday_13179.csv.gz  in=264,227,721 out=29,526,338 elapsed=92.8s

  [4498/20519] intraday_1318.csv.gz  in=264,241,715 out=29,526,338 elapsed=92.8s

  [4499/20519] intraday_13183.csv.gz  in=264,277,347 out=29,561,970 elapsed=92.9s

  [4500/20519] intraday_13180.csv.gz  in=264,319,423 out=29,603,974 elapsed=92.9s

  [4501/20519] intraday_13181.csv.gz  in=264,351,541 out=29,636,092 elapsed=92.9s

  [4502/20519] intraday_13182.csv.gz  in=264,386,276 out=29,670,827 elapsed=92.9s

  [4503/20519] intraday_13185.csv.gz  in=264,417,282 out=29,701,833 elapsed=93.0s

  [4504/20519] intraday_13186.csv.gz  in=264,419,243 out=29,703,794 elapsed=93.0s

  [4505/20519] intraday_13187.csv.gz  in=264,448,698 out=29,733,249 elapsed=93.0s

  [4506/20519] intraday_13184.csv.gz  in=264,492,548 out=29,774,211 elapsed=93.0s

  [4507/20519] intraday_13188.csv.gz  in=264,529,538 out=29,811,201 elapsed=93.0s

  [4508/20519] intraday_1319.csv.gz  in=264,542,427 out=29,811,201 elapsed=93.0s

  [4509/20519] intraday_13189.csv.gz  in=264,577,925 out=29,846,699 elapsed=93.1s

  [4510/20519] intraday_13190.csv.gz  in=264,619,028 out=29,886,187 elapsed=93.1s

  [4511/20519] intraday_13192.csv.gz  in=264,651,702 out=29,918,861 elapsed=93.1s

  [4512/20519] intraday_13193.csv.gz  in=264,689,968 out=29,957,127 elapsed=93.2s

  [4513/20519] intraday_13191.csv.gz  in=264,731,246 out=29,998,405 elapsed=93.2s

  [4514/20519] intraday_13195.csv.gz  in=264,739,768 out=30,006,927 elapsed=93.2s

  [4515/20519] intraday_13194.csv.gz  in=264,777,284 out=30,044,443 elapsed=93.2s

  [4516/20519] intraday_13197.csv.gz  in=264,811,594 out=30,078,753 elapsed=93.2s

  [4517/20519] intraday_13198.csv.gz  in=264,850,517 out=30,117,676 elapsed=93.3s

  [4518/20519] intraday_1320.csv.gz  in=264,863,712 out=30,117,676 elapsed=93.3s

  [4519/20519] intraday_13196.csv.gz  in=264,904,272 out=30,158,236 elapsed=93.3s

  [4520/20519] intraday_13199.csv.gz  in=264,940,398 out=30,193,124 elapsed=93.3s

  [4521/20519] intraday_13200.csv.gz  in=264,977,558 out=30,230,284 elapsed=93.3s

  [4522/20519] intraday_13203.csv.gz  in=264,987,806 out=30,240,532 elapsed=93.4s

  [4523/20519] intraday_13201.csv.gz  in=265,020,814 out=30,273,540 elapsed=93.4s

  [4524/20519] intraday_13204.csv.gz  in=265,032,392 out=30,285,118 elapsed=93.4s

  [4525/20519] intraday_13202.csv.gz  in=265,069,662 out=30,322,388 elapsed=93.4s

  [4526/20519] intraday_13205.csv.gz  in=265,099,956 out=30,352,657 elapsed=93.5s

  [4527/20519] intraday_13206.csv.gz  in=265,128,063 out=30,380,764 elapsed=93.5s

  [4528/20519] intraday_13208.csv.gz  in=265,169,680 out=30,422,177 elapsed=93.5s

  [4529/20519] intraday_1321.csv.gz  in=265,183,552 out=30,422,177 elapsed=93.5s

  [4530/20519] intraday_13207.csv.gz  in=265,225,882 out=30,464,507 elapsed=93.6s

  [4531/20519] intraday_13209.csv.gz  in=265,264,231 out=30,502,856 elapsed=93.6s

  [4532/20519] intraday_13212.csv.gz  in=265,273,901 out=30,511,942 elapsed=93.6s

  [4533/20519] intraday_13210.csv.gz  in=265,310,646 out=30,546,975 elapsed=93.6s

  [4534/20519] intraday_13211.csv.gz  in=265,347,028 out=30,583,357 elapsed=93.6s

  [4535/20519] intraday_13213.csv.gz  in=265,361,900 out=30,598,229 elapsed=93.6s

  [4536/20519] intraday_13214.csv.gz  in=265,398,637 out=30,634,966 elapsed=93.6s

  [4537/20519] intraday_13216.csv.gz  in=265,425,360 out=30,661,689 elapsed=93.7s

  [4538/20519] intraday_13215.csv.gz  in=265,464,037 out=30,700,366 elapsed=93.7s

  [4539/20519] intraday_13217.csv.gz  in=265,504,220 out=30,740,549 elapsed=93.7s

  [4540/20519] intraday_13218.csv.gz  in=265,542,179 out=30,778,508 elapsed=93.7s

  [4541/20519] intraday_1322.csv.gz  in=265,555,718 out=30,778,508 elapsed=93.7s

  [4542/20519] intraday_13219.csv.gz  in=265,588,793 out=30,811,583 elapsed=93.8s

  [4543/20519] intraday_13221.csv.gz  in=265,613,731 out=30,836,521 elapsed=93.8s

  [4544/20519] intraday_13220.csv.gz  in=265,647,892 out=30,870,682 elapsed=93.8s

  [4545/20519] intraday_13222.csv.gz  in=265,675,339 out=30,898,129 elapsed=93.9s

  [4546/20519] intraday_13223.csv.gz  in=265,720,977 out=30,943,767 elapsed=93.9s

  [4547/20519] intraday_13224.csv.gz  in=265,752,100 out=30,974,890 elapsed=93.9s

  [4548/20519] intraday_13225.csv.gz  in=265,792,907 out=31,015,697 elapsed=93.9s

  [4549/20519] intraday_13226.csv.gz  in=265,825,526 out=31,048,316 elapsed=94.0s

  [4550/20519] intraday_13228.csv.gz  in=265,864,268 out=31,082,676 elapsed=94.0s

  [4551/20519] intraday_13227.csv.gz  in=265,905,892 out=31,124,300 elapsed=94.0s

  [4552/20519] intraday_1323.csv.gz  in=265,919,054 out=31,124,300 elapsed=94.0s

  [4553/20519] intraday_13231.csv.gz  in=265,920,544 out=31,125,790 elapsed=94.0s

  [4554/20519] intraday_13229.csv.gz  in=265,954,832 out=31,160,078 elapsed=94.0s

  [4555/20519] intraday_13230.csv.gz  in=265,987,237 out=31,192,483 elapsed=94.0s

  [4556/20519] intraday_13232.csv.gz  in=266,022,061 out=31,227,307 elapsed=94.1s

  [4557/20519] intraday_13234.csv.gz  in=266,062,417 out=31,267,663 elapsed=94.1s

  [4558/20519] intraday_13233.csv.gz  in=266,094,997 out=31,299,438 elapsed=94.1s

  [4559/20519] intraday_13235.csv.gz  in=266,130,174 out=31,334,615 elapsed=94.1s

  [4560/20519] intraday_13236.csv.gz  in=266,159,949 out=31,364,390 elapsed=94.2s

  [4561/20519] intraday_13239.csv.gz  in=266,172,330 out=31,376,771 elapsed=94.2s

  [4562/20519] intraday_1324.csv.gz  in=266,185,709 out=31,376,771 elapsed=94.2s

  [4563/20519] intraday_13237.csv.gz  in=266,220,840 out=31,411,902 elapsed=94.3s

  [4564/20519] intraday_13240.csv.gz  in=266,241,423 out=31,432,485 elapsed=94.3s

  [4565/20519] intraday_13238.csv.gz  in=266,277,332 out=31,468,394 elapsed=94.3s

  [4566/20519] intraday_13241.csv.gz  in=266,311,843 out=31,502,905 elapsed=94.3s

  [4567/20519] intraday_13243.csv.gz  in=266,350,437 out=31,541,499 elapsed=94.4s

  [4568/20519] intraday_13244.csv.gz  in=266,397,527 out=31,587,460 elapsed=94.4s

  [4569/20519] intraday_13242.csv.gz  in=266,439,153 out=31,624,053 elapsed=94.4s

  [4570/20519] intraday_13245.csv.gz  in=266,469,125 out=31,654,025 elapsed=94.4s

  [4571/20519] intraday_13248.csv.gz  in=266,503,362 out=31,688,262 elapsed=94.5s

  [4572/20519] intraday_13249.csv.gz  in=266,504,176 out=31,689,076 elapsed=94.5s

  [4573/20519] intraday_13247.csv.gz  in=266,549,674 out=31,734,574 elapsed=94.5s

  [4574/20519] intraday_1325.csv.gz  in=266,560,559 out=31,734,574 elapsed=94.5s

  [4575/20519] intraday_13246.csv.gz  in=266,605,146 out=31,776,514 elapsed=94.5s

  [4576/20519] intraday_13252.csv.gz  in=266,640,216 out=31,811,584 elapsed=94.6s

  [4577/20519] intraday_13253.csv.gz  in=266,675,996 out=31,847,364 elapsed=94.6s

  [4578/20519] intraday_13250.csv.gz  in=266,716,717 out=31,888,085 elapsed=94.7s

  [4579/20519] intraday_13251.csv.gz  in=266,753,758 out=31,925,126 elapsed=94.7s

  [4580/20519] intraday_13254.csv.gz  in=266,784,158 out=31,955,526 elapsed=94.7s

  [4581/20519] intraday_13255.csv.gz  in=266,826,806 out=31,997,121 elapsed=94.7s

  [4582/20519] intraday_13256.csv.gz  in=266,856,703 out=32,027,018 elapsed=94.7s

  [4583/20519] intraday_13259.csv.gz  in=266,857,417 out=32,027,732 elapsed=94.8s

  [4584/20519] intraday_13257.csv.gz  in=266,895,540 out=32,065,855 elapsed=94.8s

  [4585/20519] intraday_13258.csv.gz  in=266,926,338 out=32,096,653 elapsed=94.8s

  [4586/20519] intraday_13260.csv.gz  in=266,927,532 out=32,097,847 elapsed=94.8s

  [4587/20519] intraday_1326.csv.gz  in=266,939,768 out=32,097,847 elapsed=94.8s

  [4588/20519] intraday_13262.csv.gz  in=266,976,216 out=32,134,295 elapsed=94.8s

  [4589/20519] intraday_13263.csv.gz  in=267,011,566 out=32,169,645 elapsed=94.9s

  [4590/20519] intraday_13261.csv.gz  in=267,042,797 out=32,200,876 elapsed=94.9s

  [4591/20519] intraday_13264.csv.gz  in=267,084,855 out=32,242,934 elapsed=94.9s

  [4592/20519] intraday_13265.csv.gz  in=267,128,419 out=32,286,498 elapsed=94.9s

  [4593/20519] intraday_13266.csv.gz  in=267,167,539 out=32,325,618 elapsed=94.9s

  [4594/20519] intraday_13268.csv.gz  in=267,203,104 out=32,361,183 elapsed=95.0s

  [4595/20519] intraday_13267.csv.gz  in=267,245,554 out=32,403,633 elapsed=95.0s

  [4596/20519] intraday_1327.csv.gz  in=267,258,738 out=32,403,633 elapsed=95.0s

  [4597/20519] intraday_13269.csv.gz  in=267,291,563 out=32,436,458 elapsed=95.0s

  [4598/20519] intraday_13270.csv.gz  in=267,326,600 out=32,471,495 elapsed=95.0s

  [4599/20519] intraday_13272.csv.gz  in=267,329,374 out=32,474,269 elapsed=95.0s

  [4600/20519] intraday_13275.csv.gz  in=267,329,667 out=32,474,562 elapsed=95.0s

  [4601/20519] intraday_13271.csv.gz  in=267,360,088 out=32,504,983 elapsed=95.0s

  [4602/20519] intraday_13274.csv.gz  in=267,360,338 out=32,505,233 elapsed=95.1s

  [4603/20519] intraday_13273.csv.gz  in=267,392,950 out=32,537,845 elapsed=95.1s

  [4604/20519] intraday_13277.csv.gz  in=267,393,488 out=32,538,383 elapsed=95.1s

  [4605/20519] intraday_13278.csv.gz  in=267,393,897 out=32,538,792 elapsed=95.1s

  [4606/20519] intraday_13276.csv.gz  in=267,416,321 out=32,547,276 elapsed=95.1s

  [4607/20519] intraday_13280.csv.gz  in=267,417,140 out=32,548,095 elapsed=95.1s

  [4608/20519] intraday_13279.csv.gz  in=267,417,464 out=32,548,419 elapsed=95.1s

  [4609/20519] intraday_1328.csv.gz  in=267,431,120 out=32,548,419 elapsed=95.1s

  [4610/20519] intraday_13281.csv.gz  in=267,431,756 out=32,549,055 elapsed=95.1s

  [4611/20519] intraday_13282.csv.gz  in=267,432,031 out=32,549,330 elapsed=95.1s

  [4612/20519] intraday_13283.csv.gz  in=267,432,433 out=32,549,732 elapsed=95.1s

  [4613/20519] intraday_13284.csv.gz  in=267,433,025 out=32,550,324 elapsed=95.1s

  [4614/20519] intraday_13288.csv.gz  in=267,442,478 out=32,559,777 elapsed=95.2s

  [4615/20519] intraday_13287.csv.gz  in=267,454,786 out=32,572,085 elapsed=95.2s

  [4616/20519] intraday_13286.csv.gz  in=267,466,881 out=32,584,180 elapsed=95.2s

  [4617/20519] intraday_13285.csv.gz  in=267,481,872 out=32,599,096 elapsed=95.2s

  [4618/20519] intraday_13289.csv.gz  in=267,493,327 out=32,610,551 elapsed=95.2s

  [4619/20519] intraday_1329.csv.gz  in=267,504,290 out=32,610,551 elapsed=95.2s

  [4620/20519] intraday_13290.csv.gz  in=267,518,540 out=32,624,801 elapsed=95.3s

  [4621/20519] intraday_13291.csv.gz  in=267,532,884 out=32,639,145 elapsed=95.3s

  [4622/20519] intraday_13292.csv.gz  in=267,543,821 out=32,650,082 elapsed=95.3s

  [4623/20519] intraday_13293.csv.gz  in=267,555,773 out=32,662,034 elapsed=95.3s

  [4624/20519] intraday_13294.csv.gz  in=267,568,284 out=32,674,545 elapsed=95.3s

  [4625/20519] intraday_13295.csv.gz  in=267,578,720 out=32,684,981 elapsed=95.3s

  [4626/20519] intraday_13296.csv.gz  in=267,590,697 out=32,696,958 elapsed=95.3s

  [4627/20519] intraday_13299.csv.gz  in=267,593,444 out=32,699,705 elapsed=95.3s

  [4628/20519] intraday_13297.csv.gz  in=267,604,326 out=32,710,587 elapsed=95.3s

  [4629/20519] intraday_13298.csv.gz  in=267,618,481 out=32,724,742 elapsed=95.3s

  [4630/20519] intraday_13300.csv.gz  in=267,627,728 out=32,733,989 elapsed=95.3s

  [4631/20519] intraday_1330.csv.gz  in=267,640,810 out=32,733,989 elapsed=95.3s

  [4632/20519] intraday_13302.csv.gz  in=267,651,222 out=32,744,401 elapsed=95.3s

  [4633/20519] intraday_13301.csv.gz  in=267,662,177 out=32,755,356 elapsed=95.4s

  [4634/20519] intraday_13303.csv.gz  in=267,673,389 out=32,766,568 elapsed=95.4s

  [4635/20519] intraday_13304.csv.gz  in=267,686,027 out=32,779,206 elapsed=95.4s

  [4636/20519] intraday_13307.csv.gz  in=267,698,236 out=32,791,415 elapsed=95.4s

  [4637/20519] intraday_13305.csv.gz  in=267,710,820 out=32,803,999 elapsed=95.4s

  [4638/20519] intraday_13306.csv.gz  in=267,723,204 out=32,816,383 elapsed=95.4s

  [4639/20519] intraday_13308.csv.gz  in=267,733,438 out=32,826,617 elapsed=95.4s

  [4640/20519] intraday_13309.csv.gz  in=267,744,417 out=32,837,596 elapsed=95.5s

  [4641/20519] intraday_1331.csv.gz  in=267,763,460 out=32,837,596 elapsed=95.5s

  [4642/20519] intraday_13312.csv.gz  in=267,771,244 out=32,845,380 elapsed=95.5s

  [4643/20519] intraday_13311.csv.gz  in=267,781,188 out=32,855,324 elapsed=95.5s

  [4644/20519] intraday_13314.csv.gz  in=267,793,418 out=32,867,554 elapsed=95.6s

  [4645/20519] intraday_13310.csv.gz  in=267,804,801 out=32,878,937 elapsed=95.6s

  [4646/20519] intraday_13313.csv.gz  in=267,810,288 out=32,884,424 elapsed=95.6s

  [4647/20519] intraday_13315.csv.gz  in=267,821,573 out=32,895,709 elapsed=95.6s

  [4648/20519] intraday_13317.csv.gz  in=267,833,507 out=32,907,643 elapsed=95.6s

  [4649/20519] intraday_13316.csv.gz  in=267,847,915 out=32,922,051 elapsed=95.6s

  [4650/20519] intraday_13318.csv.gz  in=267,858,354 out=32,931,758 elapsed=95.6s

  [4651/20519] intraday_13319.csv.gz  in=267,869,384 out=32,942,788 elapsed=95.6s

  [4652/20519] intraday_1332.csv.gz  in=267,881,062 out=32,942,788 elapsed=95.6s

  [4653/20519] intraday_13321.csv.gz  in=267,890,635 out=32,952,361 elapsed=95.7s

  [4654/20519] intraday_13322.csv.gz  in=267,902,241 out=32,963,967 elapsed=95.7s

  [4655/20519] intraday_13320.csv.gz  in=267,911,022 out=32,972,748 elapsed=95.7s

  [4656/20519] intraday_13323.csv.gz  in=267,922,642 out=32,984,368 elapsed=95.7s

  [4657/20519] intraday_13325.csv.gz  in=267,927,999 out=32,989,725 elapsed=95.7s

  [4658/20519] intraday_13326.csv.gz  in=267,928,000 out=32,989,726 elapsed=95.7s

  [4659/20519] intraday_13324.csv.gz  in=267,943,138 out=33,003,407 elapsed=95.7s

  [4660/20519] intraday_13329.csv.gz  in=267,954,002 out=33,014,271 elapsed=95.7s

  [4661/20519] intraday_13327.csv.gz  in=267,962,960 out=33,023,229 elapsed=95.7s

  [4662/20519] intraday_13328.csv.gz  in=267,976,417 out=33,033,840 elapsed=95.8s

  [4663/20519] intraday_1333.csv.gz  in=267,991,594 out=33,033,840 elapsed=95.8s

  [4664/20519] intraday_13330.csv.gz  in=268,001,959 out=33,044,205 elapsed=95.8s

  [4665/20519] intraday_13331.csv.gz  in=268,011,890 out=33,054,136 elapsed=95.8s

  [4666/20519] intraday_13332.csv.gz  in=268,024,406 out=33,066,652 elapsed=95.8s

  [4667/20519] intraday_13334.csv.gz  in=268,035,273 out=33,077,519 elapsed=95.8s

  [4668/20519] intraday_13333.csv.gz  in=268,046,472 out=33,088,718 elapsed=95.8s

  [4669/20519] intraday_13336.csv.gz  in=268,057,147 out=33,099,393 elapsed=95.9s

  [4670/20519] intraday_13335.csv.gz  in=268,068,543 out=33,110,789 elapsed=95.9s

  [4671/20519] intraday_13337.csv.gz  in=268,080,545 out=33,122,791 elapsed=95.9s

  [4672/20519] intraday_13338.csv.gz  in=268,099,408 out=33,136,417 elapsed=95.9s

  [4673/20519] intraday_13339.csv.gz  in=268,101,232 out=33,138,241 elapsed=95.9s

  [4674/20519] intraday_13340.csv.gz  in=268,104,845 out=33,141,854 elapsed=95.9s

  [4675/20519] intraday_1334.csv.gz  in=268,117,058 out=33,141,854 elapsed=95.9s

  [4676/20519] intraday_13342.csv.gz  in=268,127,215 out=33,152,011 elapsed=95.9s

  [4677/20519] intraday_13341.csv.gz  in=268,144,089 out=33,163,851 elapsed=96.0s

  [4678/20519] intraday_13343.csv.gz  in=268,152,688 out=33,172,450 elapsed=96.0s

  [4679/20519] intraday_13344.csv.gz  in=268,166,595 out=33,186,357 elapsed=96.0s

  [4680/20519] intraday_13345.csv.gz  in=268,179,952 out=33,199,714 elapsed=96.0s

  [4681/20519] intraday_13347.csv.gz  in=268,191,890 out=33,211,652 elapsed=96.0s

  [4682/20519] intraday_13346.csv.gz  in=268,208,351 out=33,225,833 elapsed=96.0s

  [4683/20519] intraday_13349.csv.gz  in=268,216,528 out=33,234,010 elapsed=96.0s

  [4684/20519] intraday_13348.csv.gz  in=268,227,461 out=33,244,943 elapsed=96.0s

  [4685/20519] intraday_1335.csv.gz  in=268,239,487 out=33,244,943 elapsed=96.0s

  [4686/20519] intraday_13350.csv.gz  in=268,251,016 out=33,256,368 elapsed=96.1s

  [4687/20519] intraday_13354.csv.gz  in=268,251,696 out=33,257,048 elapsed=96.1s

  [4688/20519] intraday_13351.csv.gz  in=268,263,616 out=33,268,968 elapsed=96.1s

  [4689/20519] intraday_13352.csv.gz  in=268,276,662 out=33,282,014 elapsed=96.1s

  [4690/20519] intraday_13353.csv.gz  in=268,284,080 out=33,289,432 elapsed=96.1s

  [4691/20519] intraday_13358.csv.gz  in=268,295,524 out=33,300,876 elapsed=96.1s

  [4692/20519] intraday_13355.csv.gz  in=268,307,812 out=33,313,164 elapsed=96.1s

  [4693/20519] intraday_13357.csv.gz  in=268,319,750 out=33,325,102 elapsed=96.2s

  [4694/20519] intraday_13356.csv.gz  in=268,331,321 out=33,336,673 elapsed=96.2s

  [4695/20519] intraday_13359.csv.gz  in=268,340,501 out=33,345,853 elapsed=96.2s

  [4696/20519] intraday_13361.csv.gz  in=268,351,897 out=33,357,249 elapsed=96.2s

  [4697/20519] intraday_1336.csv.gz  in=268,365,876 out=33,357,249 elapsed=96.2s

  [4698/20519] intraday_13360.csv.gz  in=268,377,341 out=33,368,714 elapsed=96.2s

  [4699/20519] intraday_13362.csv.gz  in=268,390,956 out=33,382,329 elapsed=96.2s

  [4700/20519] intraday_13364.csv.gz  in=268,404,249 out=33,395,622 elapsed=96.2s

  [4701/20519] intraday_13363.csv.gz  in=268,417,915 out=33,409,288 elapsed=96.3s

  [4702/20519] intraday_13366.csv.gz  in=268,430,445 out=33,421,818 elapsed=96.3s

  [4703/20519] intraday_13365.csv.gz  in=268,441,239 out=33,432,612 elapsed=96.3s

  [4704/20519] intraday_13367.csv.gz  in=268,452,189 out=33,443,562 elapsed=96.3s

  [4705/20519] intraday_13368.csv.gz  in=268,464,069 out=33,455,442 elapsed=96.3s

  [4706/20519] intraday_1337.csv.gz  in=268,478,937 out=33,455,442 elapsed=96.3s

  [4707/20519] intraday_13369.csv.gz  in=268,495,082 out=33,469,357 elapsed=96.3s

  [4708/20519] intraday_13371.csv.gz  in=268,508,877 out=33,483,152 elapsed=96.4s

  [4709/20519] intraday_13372.csv.gz  in=268,520,981 out=33,495,256 elapsed=96.4s

  [4710/20519] intraday_13373.csv.gz  in=268,532,555 out=33,506,830 elapsed=96.4s

  [4711/20519] intraday_13370.csv.gz  in=268,543,707 out=33,517,982 elapsed=96.4s

  [4712/20519] intraday_13374.csv.gz  in=268,554,642 out=33,528,917 elapsed=96.4s

  [4713/20519] intraday_13375.csv.gz  in=268,567,030 out=33,541,305 elapsed=96.4s

  [4714/20519] intraday_13376.csv.gz  in=268,578,338 out=33,552,613 elapsed=96.5s

  [4715/20519] intraday_13377.csv.gz  in=268,587,787 out=33,562,024 elapsed=96.5s

  [4716/20519] intraday_13379.csv.gz  in=268,598,004 out=33,572,241 elapsed=96.5s

  [4717/20519] intraday_13378.csv.gz  in=268,609,843 out=33,584,080 elapsed=96.5s

  [4718/20519] intraday_1338.csv.gz  in=268,622,463 out=33,584,080 elapsed=96.5s

  [4719/20519] intraday_13380.csv.gz  in=268,634,424 out=33,596,041 elapsed=96.5s

  [4720/20519] intraday_13382.csv.gz  in=268,646,329 out=33,607,946 elapsed=96.6s

  [4721/20519] intraday_13381.csv.gz  in=268,657,396 out=33,619,013 elapsed=96.6s

  [4722/20519] intraday_13383.csv.gz  in=268,670,235 out=33,631,852 elapsed=96.6s

  [4723/20519] intraday_13384.csv.gz  in=268,681,075 out=33,642,692 elapsed=96.6s

  [4724/20519] intraday_13387.csv.gz  in=268,691,915 out=33,653,532 elapsed=96.6s

  [4725/20519] intraday_13386.csv.gz  in=268,702,868 out=33,664,485 elapsed=96.6s

  [4726/20519] intraday_13388.csv.gz  in=268,714,735 out=33,676,352 elapsed=96.6s

  [4727/20519] intraday_13385.csv.gz  in=268,728,984 out=33,690,601 elapsed=96.6s

  [4728/20519] intraday_1339.csv.gz  in=268,743,226 out=33,690,601 elapsed=96.6s

  [4729/20519] intraday_13389.csv.gz  in=268,756,871 out=33,704,246 elapsed=96.6s

  [4730/20519] intraday_13390.csv.gz  in=268,766,855 out=33,714,230 elapsed=96.6s

  [4731/20519] intraday_13391.csv.gz  in=268,779,495 out=33,726,870 elapsed=96.6s

  [4732/20519] intraday_13392.csv.gz  in=268,793,447 out=33,740,822 elapsed=96.7s

  [4733/20519] intraday_13393.csv.gz  in=268,805,741 out=33,753,116 elapsed=96.7s

  [4734/20519] intraday_13394.csv.gz  in=268,819,824 out=33,767,199 elapsed=96.7s

  [4735/20519] intraday_13395.csv.gz  in=268,834,092 out=33,781,467 elapsed=96.7s

  [4736/20519] intraday_13396.csv.gz  in=268,850,948 out=33,798,323 elapsed=96.7s

  [4737/20519] intraday_13397.csv.gz  in=268,864,335 out=33,811,710 elapsed=96.7s

  [4738/20519] intraday_1340.csv.gz  in=268,876,265 out=33,811,710 elapsed=96.7s

  [4739/20519] intraday_13399.csv.gz  in=268,888,827 out=33,824,272 elapsed=96.7s

  [4740/20519] intraday_13398.csv.gz  in=268,902,233 out=33,837,678 elapsed=96.7s

  [4741/20519] intraday_13400.csv.gz  in=268,914,052 out=33,849,497 elapsed=96.7s

  [4742/20519] intraday_13401.csv.gz  in=268,922,946 out=33,858,391 elapsed=96.8s

  [4743/20519] intraday_13402.csv.gz  in=268,935,562 out=33,871,007 elapsed=96.8s

  [4744/20519] intraday_13404.csv.gz  in=268,946,559 out=33,882,004 elapsed=96.8s

  [4745/20519] intraday_13403.csv.gz  in=268,956,579 out=33,892,024 elapsed=96.8s

  [4746/20519] intraday_13405.csv.gz  in=268,968,817 out=33,904,262 elapsed=96.8s

  [4747/20519] intraday_13406.csv.gz  in=268,982,527 out=33,917,972 elapsed=96.8s

  [4748/20519] intraday_13407.csv.gz  in=268,991,380 out=33,926,825 elapsed=96.9s

  [4749/20519] intraday_13408.csv.gz  in=269,001,814 out=33,937,259 elapsed=96.9s

  [4750/20519] intraday_13409.csv.gz  in=269,013,730 out=33,949,175 elapsed=96.9s

  [4751/20519] intraday_1341.csv.gz  in=269,029,890 out=33,949,175 elapsed=96.9s

  [4752/20519] intraday_13410.csv.gz  in=269,040,176 out=33,959,461 elapsed=96.9s

  [4753/20519] intraday_13411.csv.gz  in=269,052,707 out=33,971,992 elapsed=96.9s

  [4754/20519] intraday_13412.csv.gz  in=269,066,371 out=33,985,656 elapsed=96.9s

  [4755/20519] intraday_13413.csv.gz  in=269,079,688 out=33,998,973 elapsed=96.9s

  [4756/20519] intraday_13414.csv.gz  in=269,091,315 out=34,010,600 elapsed=96.9s

  [4757/20519] intraday_13415.csv.gz  in=269,106,060 out=34,025,345 elapsed=97.0s

  [4758/20519] intraday_13416.csv.gz  in=269,116,913 out=34,036,198 elapsed=97.0s

  [4759/20519] intraday_13417.csv.gz  in=269,127,581 out=34,046,866 elapsed=97.0s

  [4760/20519] intraday_13418.csv.gz  in=269,139,552 out=34,058,837 elapsed=97.0s

  [4761/20519] intraday_1342.csv.gz  in=269,151,050 out=34,058,837 elapsed=97.0s

  [4762/20519] intraday_13419.csv.gz  in=269,162,567 out=34,070,354 elapsed=97.0s

  [4763/20519] intraday_13420.csv.gz  in=269,172,314 out=34,080,101 elapsed=97.0s

  [4764/20519] intraday_13424.csv.gz  in=269,172,490 out=34,080,277 elapsed=97.1s

  [4765/20519] intraday_13423.csv.gz  in=269,180,080 out=34,087,867 elapsed=97.1s

  [4766/20519] intraday_13421.csv.gz  in=269,185,747 out=34,093,534 elapsed=97.1s

  [4767/20519] intraday_13422.csv.gz  in=269,197,781 out=34,105,568 elapsed=97.1s

  [4768/20519] intraday_13425.csv.gz  in=269,198,246 out=34,106,033 elapsed=97.1s

  [4769/20519] intraday_13427.csv.gz  in=269,198,951 out=34,106,738 elapsed=97.1s

  [4770/20519] intraday_13426.csv.gz  in=269,199,694 out=34,107,481 elapsed=97.1s

  [4771/20519] intraday_13429.csv.gz  in=269,200,101 out=34,107,888 elapsed=97.1s

  [4772/20519] intraday_13428.csv.gz  in=269,200,266 out=34,108,053 elapsed=97.1s

  [4773/20519] intraday_13430.csv.gz  in=269,200,659 out=34,108,446 elapsed=97.1s

  [4774/20519] intraday_13431.csv.gz  in=269,200,954 out=34,108,741 elapsed=97.1s

  [4775/20519] intraday_13432.csv.gz  in=269,201,437 out=34,109,224 elapsed=97.1s

  [4776/20519] intraday_1343.csv.gz  in=269,214,676 out=34,109,224 elapsed=97.1s

  [4777/20519] intraday_13433.csv.gz  in=269,215,236 out=34,109,784 elapsed=97.1s

  [4778/20519] intraday_13434.csv.gz  in=269,215,792 out=34,110,340 elapsed=97.1s

  [4779/20519] intraday_13437.csv.gz  in=269,216,481 out=34,111,029 elapsed=97.1s

  [4780/20519] intraday_13435.csv.gz  in=269,216,709 out=34,111,257 elapsed=97.1s

  [4781/20519] intraday_13438.csv.gz  in=269,217,004 out=34,111,552 elapsed=97.1s

  [4782/20519] intraday_13436.csv.gz  in=269,217,670 out=34,112,218 elapsed=97.1s

  [4783/20519] intraday_13439.csv.gz  in=269,217,963 out=34,112,511 elapsed=97.1s

  [4784/20519] intraday_13441.csv.gz  in=269,218,321 out=34,112,869 elapsed=97.2s

  [4785/20519] intraday_13440.csv.gz  in=269,218,593 out=34,113,141 elapsed=97.2s

  [4786/20519] intraday_13442.csv.gz  in=269,218,668 out=34,113,216 elapsed=97.2s

  [4787/20519] intraday_13443.csv.gz  in=269,218,841 out=34,113,389 elapsed=97.2s

  [4788/20519] intraday_1344.csv.gz  in=269,234,097 out=34,113,389 elapsed=97.2s

  [4789/20519] intraday_13445.csv.gz  in=269,234,832 out=34,114,018 elapsed=97.2s

  [4790/20519] intraday_13446.csv.gz  in=269,234,974 out=34,114,160 elapsed=97.2s

  [4791/20519] intraday_13447.csv.gz  in=269,235,543 out=34,114,729 elapsed=97.2s

  [4792/20519] intraday_13444.csv.gz  in=269,251,913 out=34,121,491 elapsed=97.2s

  [4793/20519] intraday_13448.csv.gz  in=269,252,364 out=34,121,942 elapsed=97.2s

  [4794/20519] intraday_13451.csv.gz  in=269,252,514 out=34,122,092 elapsed=97.2s

  [4795/20519] intraday_13452.csv.gz  in=269,252,903 out=34,122,481 elapsed=97.2s

  [4796/20519] intraday_13449.csv.gz  in=269,253,651 out=34,123,229 elapsed=97.2s

  [4797/20519] intraday_13450.csv.gz  in=269,254,331 out=34,123,909 elapsed=97.2s

  [4798/20519] intraday_13453.csv.gz  in=269,254,551 out=34,124,129 elapsed=97.3s

  [4799/20519] intraday_13456.csv.gz  in=269,255,000 out=34,124,578 elapsed=97.3s

  [4800/20519] intraday_13457.csv.gz  in=269,255,144 out=34,124,722 elapsed=97.3s

  [4801/20519] intraday_1345.csv.gz  in=269,269,488 out=34,124,722 elapsed=97.3s

  [4802/20519] intraday_13455.csv.gz  in=269,269,606 out=34,124,840 elapsed=97.3s

  [4803/20519] intraday_13454.csv.gz  in=269,271,866 out=34,127,100 elapsed=97.3s

  [4804/20519] intraday_13458.csv.gz  in=269,271,898 out=34,127,132 elapsed=97.3s

  [4805/20519] intraday_13459.csv.gz  in=269,272,050 out=34,127,284 elapsed=97.3s

  [4806/20519] intraday_13460.csv.gz  in=269,272,201 out=34,127,435 elapsed=97.3s

  [4807/20519] intraday_13461.csv.gz  in=269,272,570 out=34,127,765 elapsed=97.3s

  [4808/20519] intraday_1346.csv.gz  in=269,285,120 out=34,127,765 elapsed=97.3s

  [4809/20519] intraday_13462.csv.gz  in=269,285,382 out=34,128,027 elapsed=97.3s

  [4810/20519] intraday_13463.csv.gz  in=269,285,416 out=34,128,061 elapsed=97.3s

  [4811/20519] intraday_13465.csv.gz  in=269,285,569 out=34,128,214 elapsed=97.3s

  [4812/20519] intraday_13464.csv.gz  in=269,285,960 out=34,128,605 elapsed=97.3s

  [4813/20519] intraday_13467.csv.gz  in=269,286,136 out=34,128,781 elapsed=97.3s

  [4814/20519] intraday_13469.csv.gz  in=269,286,866 out=34,129,511 elapsed=97.3s

  [4815/20519] intraday_13468.csv.gz  in=269,286,992 out=34,129,637 elapsed=97.3s

  [4816/20519] intraday_13466.csv.gz  in=269,287,529 out=34,130,174 elapsed=97.3s

  [4817/20519] intraday_13471.csv.gz  in=269,288,085 out=34,130,730 elapsed=97.4s

  [4818/20519] intraday_13472.csv.gz  in=269,288,265 out=34,130,910 elapsed=97.4s

  [4819/20519] intraday_13470.csv.gz  in=269,289,102 out=34,131,747 elapsed=97.4s

  [4820/20519] intraday_13473.csv.gz  in=269,289,293 out=34,131,938 elapsed=97.4s

  [4821/20519] intraday_1347.csv.gz  in=269,304,661 out=34,131,938 elapsed=97.4s

  [4822/20519] intraday_13474.csv.gz  in=269,304,802 out=34,132,079 elapsed=97.4s

  [4823/20519] intraday_13476.csv.gz  in=269,305,126 out=34,132,403 elapsed=97.4s

  [4824/20519] intraday_13477.csv.gz  in=269,305,358 out=34,132,635 elapsed=97.4s

  [4825/20519] intraday_13479.csv.gz  in=269,305,512 out=34,132,789 elapsed=97.5s

  [4826/20519] intraday_13478.csv.gz  in=269,305,995 out=34,133,272 elapsed=97.5s

  [4827/20519] intraday_13475.csv.gz  in=269,315,441 out=34,136,743 elapsed=97.5s

  [4828/20519] intraday_13481.csv.gz  in=269,315,600 out=34,136,902 elapsed=97.5s

  [4829/20519] intraday_13482.csv.gz  in=269,316,655 out=34,137,957 elapsed=97.5s

  [4830/20519] intraday_13480.csv.gz  in=269,316,705 out=34,138,007 elapsed=97.5s

  [4831/20519] intraday_1348.csv.gz  in=269,327,583 out=34,138,007 elapsed=97.5s

  [4832/20519] intraday_13483.csv.gz  in=269,328,340 out=34,138,764 elapsed=97.5s

  [4833/20519] intraday_13484.csv.gz  in=269,328,784 out=34,139,208 elapsed=97.5s

  [4834/20519] intraday_13485.csv.gz  in=269,328,813 out=34,139,237 elapsed=97.5s

  [4835/20519] intraday_13488.csv.gz  in=269,329,230 out=34,139,654 elapsed=97.5s

  [4836/20519] intraday_13486.csv.gz  in=269,329,916 out=34,140,340 elapsed=97.5s

  [4837/20519] intraday_13489.csv.gz  in=269,330,391 out=34,140,815 elapsed=97.5s

  [4838/20519] intraday_13487.csv.gz  in=269,330,997 out=34,141,074 elapsed=97.5s

  [4839/20519] intraday_13490.csv.gz  in=269,331,334 out=34,141,411 elapsed=97.6s

  [4840/20519] intraday_13493.csv.gz  in=269,331,599 out=34,141,676 elapsed=97.6s

  [4841/20519] intraday_13492.csv.gz  in=269,332,161 out=34,142,238 elapsed=97.6s

  [4842/20519] intraday_13491.csv.gz  in=269,332,415 out=34,142,492 elapsed=97.6s

  [4843/20519] intraday_13495.csv.gz  in=269,332,650 out=34,142,727 elapsed=97.6s

  [4844/20519] intraday_1349.csv.gz  in=269,344,932 out=34,142,727 elapsed=97.6s

  [4845/20519] intraday_13494.csv.gz  in=269,345,152 out=34,142,947 elapsed=97.6s

  [4846/20519] intraday_13496.csv.gz  in=269,345,691 out=34,143,486 elapsed=97.6s

  [4847/20519] intraday_13497.csv.gz  in=269,346,107 out=34,143,902 elapsed=97.6s

  [4848/20519] intraday_13498.csv.gz  in=269,346,130 out=34,143,925 elapsed=97.6s

  [4849/20519] intraday_13500.csv.gz  in=269,346,712 out=34,144,507 elapsed=97.6s

  [4850/20519] intraday_13499.csv.gz  in=269,347,150 out=34,144,945 elapsed=97.6s

  [4851/20519] intraday_13501.csv.gz  in=269,348,639 out=34,146,258 elapsed=97.6s

  [4852/20519] intraday_1350.csv.gz  in=269,360,075 out=34,146,258 elapsed=97.6s

  [4853/20519] intraday_13503.csv.gz  in=269,360,961 out=34,147,144 elapsed=97.6s

  [4854/20519] intraday_13502.csv.gz  in=269,361,688 out=34,147,871 elapsed=97.6s

  [4855/20519] intraday_13506.csv.gz  in=269,361,971 out=34,148,154 elapsed=97.6s

  [4856/20519] intraday_13504.csv.gz  in=269,362,473 out=34,148,656 elapsed=97.6s

  [4857/20519] intraday_13505.csv.gz  in=269,362,816 out=34,148,999 elapsed=97.6s

  [4858/20519] intraday_13507.csv.gz  in=269,363,614 out=34,149,797 elapsed=97.7s

  [4859/20519] intraday_13509.csv.gz  in=269,363,889 out=34,150,072 elapsed=97.7s

  [4860/20519] intraday_13510.csv.gz  in=269,364,551 out=34,150,734 elapsed=97.7s

  [4861/20519] intraday_13511.csv.gz  in=269,364,960 out=34,151,143 elapsed=97.7s

  [4862/20519] intraday_1351.csv.gz  in=269,380,186 out=34,151,143 elapsed=97.7s

  [4863/20519] intraday_13508.csv.gz  in=269,405,024 out=34,159,480 elapsed=97.7s

  [4864/20519] intraday_13514.csv.gz  in=269,405,449 out=34,159,905 elapsed=97.7s

  [4865/20519] intraday_13513.csv.gz  in=269,405,621 out=34,160,077 elapsed=97.7s

  [4866/20519] intraday_13512.csv.gz  in=269,405,912 out=34,160,368 elapsed=97.7s

  [4867/20519] intraday_13515.csv.gz  in=269,406,176 out=34,160,632 elapsed=97.7s

  [4868/20519] intraday_13516.csv.gz  in=269,406,792 out=34,161,248 elapsed=97.7s

  [4869/20519] intraday_13517.csv.gz  in=269,406,913 out=34,161,369 elapsed=97.7s

  [4870/20519] intraday_13518.csv.gz  in=269,407,034 out=34,161,490 elapsed=97.7s

  [4871/20519] intraday_13519.csv.gz  in=269,407,413 out=34,161,869 elapsed=97.7s

  [4872/20519] intraday_13521.csv.gz  in=269,408,029 out=34,162,485 elapsed=97.7s

  [4873/20519] intraday_13520.csv.gz  in=269,409,134 out=34,163,590 elapsed=97.7s

  [4874/20519] intraday_13522.csv.gz  in=269,409,788 out=34,164,244 elapsed=97.8s

  [4875/20519] intraday_13524.csv.gz  in=269,410,289 out=34,164,745 elapsed=97.8s

  [4876/20519] intraday_1352.csv.gz  in=269,423,771 out=34,164,745 elapsed=97.8s

  [4877/20519] intraday_13523.csv.gz  in=269,424,045 out=34,165,019 elapsed=97.8s

  [4878/20519] intraday_13525.csv.gz  in=269,424,143 out=34,165,117 elapsed=97.8s

  [4879/20519] intraday_13527.csv.gz  in=269,424,362 out=34,165,336 elapsed=97.8s

  [4880/20519] intraday_13526.csv.gz  in=269,425,452 out=34,166,426 elapsed=97.8s

  [4881/20519] intraday_13529.csv.gz  in=269,425,625 out=34,166,599 elapsed=97.8s

  [4882/20519] intraday_13530.csv.gz  in=269,426,059 out=34,167,033 elapsed=97.8s

  [4883/20519] intraday_13528.csv.gz  in=269,426,423 out=34,167,397 elapsed=97.8s

  [4884/20519] intraday_13531.csv.gz  in=269,427,622 out=34,168,596 elapsed=97.8s

  [4885/20519] intraday_13533.csv.gz  in=269,428,908 out=34,169,882 elapsed=97.8s

  [4886/20519] intraday_13532.csv.gz  in=269,429,693 out=34,170,667 elapsed=97.8s

  [4887/20519] intraday_13534.csv.gz  in=269,430,635 out=34,171,609 elapsed=97.8s

  [4888/20519] intraday_1353.csv.gz  in=269,446,961 out=34,171,609 elapsed=97.8s

  [4889/20519] intraday_13537.csv.gz  in=269,447,383 out=34,172,031 elapsed=97.8s

  [4890/20519] intraday_13538.csv.gz  in=269,448,111 out=34,172,759 elapsed=97.8s

  [4891/20519] intraday_13536.csv.gz  in=269,448,879 out=34,173,527 elapsed=97.9s

  [4892/20519] intraday_13539.csv.gz  in=269,449,058 out=34,173,706 elapsed=97.9s

  [4893/20519] intraday_13540.csv.gz  in=269,449,266 out=34,173,914 elapsed=97.9s

  [4894/20519] intraday_13535.csv.gz  in=269,450,564 out=34,175,212 elapsed=97.9s

  [4895/20519] intraday_13542.csv.gz  in=269,450,745 out=34,175,393 elapsed=97.9s

  [4896/20519] intraday_13541.csv.gz  in=269,451,025 out=34,175,673 elapsed=97.9s

  [4897/20519] intraday_1354.csv.gz  in=269,464,345 out=34,175,673 elapsed=97.9s

  [4898/20519] intraday_13544.csv.gz  in=269,464,932 out=34,176,260 elapsed=97.9s

  [4899/20519] intraday_13543.csv.gz  in=269,465,102 out=34,176,430 elapsed=97.9s

  [4900/20519] intraday_13545.csv.gz  in=269,465,953 out=34,177,281 elapsed=97.9s

  [4901/20519] intraday_13546.csv.gz  in=269,466,135 out=34,177,463 elapsed=97.9s

  [4902/20519] intraday_13547.csv.gz  in=269,466,527 out=34,177,855 elapsed=97.9s

  [4903/20519] intraday_13549.csv.gz  in=269,466,900 out=34,178,228 elapsed=97.9s

  [4904/20519] intraday_13548.csv.gz  in=269,467,377 out=34,178,705 elapsed=97.9s

  [4905/20519] intraday_13550.csv.gz  in=269,467,971 out=34,179,299 elapsed=97.9s

  [4906/20519] intraday_13551.csv.gz  in=269,468,152 out=34,179,480 elapsed=97.9s

  [4907/20519] intraday_13552.csv.gz  in=269,468,347 out=34,179,675 elapsed=98.0s

  [4908/20519] intraday_13553.csv.gz  in=269,468,812 out=34,180,140 elapsed=98.0s

  [4909/20519] intraday_13554.csv.gz  in=269,469,051 out=34,180,379 elapsed=98.0s

  [4910/20519] intraday_13555.csv.gz  in=269,469,758 out=34,181,086 elapsed=98.0s

  [4911/20519] intraday_1355.csv.gz  in=269,482,263 out=34,181,086 elapsed=98.0s

  [4912/20519] intraday_13556.csv.gz  in=269,482,578 out=34,181,401 elapsed=98.0s

  [4913/20519] intraday_13558.csv.gz  in=269,482,909 out=34,181,732 elapsed=98.0s

  [4914/20519] intraday_13557.csv.gz  in=269,483,328 out=34,182,151 elapsed=98.0s

  [4915/20519] intraday_13559.csv.gz  in=269,483,845 out=34,182,668 elapsed=98.0s

  [4916/20519] intraday_13561.csv.gz  in=269,484,464 out=34,183,287 elapsed=98.0s

  [4917/20519] intraday_13562.csv.gz  in=269,484,547 out=34,183,370 elapsed=98.0s

  [4918/20519] intraday_13560.csv.gz  in=269,486,118 out=34,184,369 elapsed=98.0s

  [4919/20519] intraday_1356.csv.gz  in=269,501,306 out=34,184,369 elapsed=98.0s

  [4920/20519] intraday_13563.csv.gz  in=269,534,114 out=34,217,177 elapsed=98.1s

  [4921/20519] intraday_13565.csv.gz  in=269,558,776 out=34,241,839 elapsed=98.1s

  [4922/20519] intraday_13566.csv.gz  in=269,581,631 out=34,264,694 elapsed=98.1s

  [4923/20519] intraday_13567.csv.gz  in=269,606,935 out=34,289,998 elapsed=98.1s

  [4924/20519] intraday_13564.csv.gz  in=269,632,169 out=34,315,232 elapsed=98.1s

  [4925/20519] intraday_13568.csv.gz  in=269,663,499 out=34,346,562 elapsed=98.1s

  [4926/20519] intraday_13569.csv.gz  in=269,691,734 out=34,374,797 elapsed=98.2s

  [4927/20519] intraday_1357.csv.gz  in=269,705,114 out=34,374,797 elapsed=98.2s

  [4928/20519] intraday_13570.csv.gz  in=269,726,756 out=34,396,439 elapsed=98.2s

  [4929/20519] intraday_13571.csv.gz  in=269,739,224 out=34,408,907 elapsed=98.2s

  [4930/20519] intraday_13572.csv.gz  in=269,765,002 out=34,434,685 elapsed=98.2s

  [4931/20519] intraday_13574.csv.gz  in=269,782,605 out=34,452,288 elapsed=98.2s

  [4932/20519] intraday_13573.csv.gz  in=269,811,927 out=34,481,584 elapsed=98.3s

  [4933/20519] intraday_13575.csv.gz  in=269,840,393 out=34,507,509 elapsed=98.3s

  [4934/20519] intraday_13577.csv.gz  in=269,865,891 out=34,533,007 elapsed=98.3s

  [4935/20519] intraday_13576.csv.gz  in=269,893,083 out=34,560,199 elapsed=98.3s

  [4936/20519] intraday_13578.csv.gz  in=269,915,175 out=34,582,291 elapsed=98.4s

  [4937/20519] intraday_1358.csv.gz  in=269,928,483 out=34,582,291 elapsed=98.4s

  [4938/20519] intraday_13581.csv.gz  in=269,930,774 out=34,584,582 elapsed=98.4s

  [4939/20519] intraday_13579.csv.gz  in=269,952,158 out=34,605,966 elapsed=98.4s

  [4940/20519] intraday_13580.csv.gz  in=269,972,066 out=34,625,874 elapsed=98.4s

  [4941/20519] intraday_13582.csv.gz  in=269,996,061 out=34,649,869 elapsed=98.4s

  [4942/20519] intraday_13583.csv.gz  in=270,017,497 out=34,671,305 elapsed=98.5s

  [4943/20519] intraday_13585.csv.gz  in=270,039,862 out=34,693,670 elapsed=98.5s

  [4944/20519] intraday_13584.csv.gz  in=270,062,140 out=34,715,948 elapsed=98.5s

  [4945/20519] intraday_13586.csv.gz  in=270,086,384 out=34,740,192 elapsed=98.5s

  [4946/20519] intraday_13588.csv.gz  in=270,116,185 out=34,769,993 elapsed=98.5s

  [4947/20519] intraday_13587.csv.gz  in=270,143,047 out=34,796,855 elapsed=98.6s

  [4948/20519] intraday_1359.csv.gz  in=270,158,783 out=34,796,855 elapsed=98.6s

  [4949/20519] intraday_13589.csv.gz  in=270,187,049 out=34,825,121 elapsed=98.6s

  [4950/20519] intraday_13590.csv.gz  in=270,208,446 out=34,846,518 elapsed=98.6s

  [4951/20519] intraday_13591.csv.gz  in=270,230,015 out=34,868,087 elapsed=98.6s

  [4952/20519] intraday_13592.csv.gz  in=270,252,367 out=34,890,439 elapsed=98.6s

  [4953/20519] intraday_13593.csv.gz  in=270,275,433 out=34,913,505 elapsed=98.6s

  [4954/20519] intraday_13594.csv.gz  in=270,293,650 out=34,931,722 elapsed=98.6s

  [4955/20519] intraday_13595.csv.gz  in=270,316,332 out=34,953,442 elapsed=98.7s

  [4956/20519] intraday_13597.csv.gz  in=270,338,329 out=34,975,439 elapsed=98.7s

  [4957/20519] intraday_13596.csv.gz  in=270,364,205 out=35,001,315 elapsed=98.7s

  [4958/20519] intraday_13598.csv.gz  in=270,389,022 out=35,026,132 elapsed=98.7s

  [4959/20519] intraday_1360.csv.gz  in=270,403,396 out=35,026,132 elapsed=98.7s

  [4960/20519] intraday_13599.csv.gz  in=270,432,344 out=35,055,080 elapsed=98.7s

  [4961/20519] intraday_13603.csv.gz  in=270,432,346 out=35,055,082 elapsed=98.7s

  [4962/20519] intraday_13600.csv.gz  in=270,457,421 out=35,080,157 elapsed=98.7s

  [4963/20519] intraday_13601.csv.gz  in=270,479,583 out=35,102,319 elapsed=98.8s

  [4964/20519] intraday_13602.csv.gz  in=270,504,240 out=35,126,976 elapsed=98.8s

  [4965/20519] intraday_13604.csv.gz  in=270,522,378 out=35,145,114 elapsed=98.8s

  [4966/20519] intraday_13606.csv.gz  in=270,544,122 out=35,166,858 elapsed=98.8s

  [4967/20519] intraday_13605.csv.gz  in=270,573,004 out=35,195,740 elapsed=98.8s

  [4968/20519] intraday_13608.csv.gz  in=270,598,147 out=35,220,883 elapsed=98.9s

  [4969/20519] intraday_13607.csv.gz  in=270,620,893 out=35,243,629 elapsed=98.9s

  [4970/20519] intraday_13609.csv.gz  in=270,643,672 out=35,266,408 elapsed=98.9s

  [4971/20519] intraday_1361.csv.gz  in=270,658,117 out=35,266,408 elapsed=98.9s

  [4972/20519] intraday_13610.csv.gz  in=270,684,118 out=35,292,409 elapsed=98.9s

  [4973/20519] intraday_13612.csv.gz  in=270,705,767 out=35,314,058 elapsed=98.9s

  [4974/20519] intraday_13611.csv.gz  in=270,726,738 out=35,335,029 elapsed=99.0s

  [4975/20519] intraday_13613.csv.gz  in=270,752,665 out=35,360,956 elapsed=99.0s

  [4976/20519] intraday_13616.csv.gz  in=270,753,500 out=35,361,791 elapsed=99.0s

  [4977/20519] intraday_13614.csv.gz  in=270,789,590 out=35,387,841 elapsed=99.0s

  [4978/20519] intraday_13615.csv.gz  in=270,799,192 out=35,397,443 elapsed=99.0s

  [4979/20519] intraday_13617.csv.gz  in=270,823,037 out=35,421,288 elapsed=99.0s

  [4980/20519] intraday_13618.csv.gz  in=270,855,108 out=35,453,359 elapsed=99.1s

  [4981/20519] intraday_1362.csv.gz  in=270,867,528 out=35,453,359 elapsed=99.1s

  [4982/20519] intraday_13619.csv.gz  in=270,895,668 out=35,481,499 elapsed=99.1s

  [4983/20519] intraday_13620.csv.gz  in=270,922,431 out=35,508,262 elapsed=99.1s

  [4984/20519] intraday_13621.csv.gz  in=270,944,850 out=35,530,681 elapsed=99.2s

  [4985/20519] intraday_13622.csv.gz  in=270,962,541 out=35,548,372 elapsed=99.2s

  [4986/20519] intraday_13623.csv.gz  in=270,989,667 out=35,575,498 elapsed=99.2s

  [4987/20519] intraday_13624.csv.gz  in=271,015,137 out=35,600,968 elapsed=99.2s

  [4988/20519] intraday_13626.csv.gz  in=271,040,232 out=35,626,063 elapsed=99.2s

  [4989/20519] intraday_13625.csv.gz  in=271,065,923 out=35,651,754 elapsed=99.2s

  [4990/20519] intraday_13629.csv.gz  in=271,065,924 out=35,651,755 elapsed=99.2s

  [4991/20519] intraday_13627.csv.gz  in=271,089,332 out=35,675,163 elapsed=99.3s

  [4992/20519] intraday_1363.csv.gz  in=271,099,962 out=35,675,163 elapsed=99.3s

  [4993/20519] intraday_13628.csv.gz  in=271,111,118 out=35,686,319 elapsed=99.3s

  [4994/20519] intraday_13630.csv.gz  in=271,131,129 out=35,706,330 elapsed=99.3s

  [4995/20519] intraday_13631.csv.gz  in=271,155,129 out=35,730,330 elapsed=99.3s

  [4996/20519] intraday_13632.csv.gz  in=271,173,391 out=35,748,592 elapsed=99.4s

  [4997/20519] intraday_13633.csv.gz  in=271,197,120 out=35,772,321 elapsed=99.4s

  [4998/20519] intraday_13634.csv.gz  in=271,223,276 out=35,798,477 elapsed=99.4s

  [4999/20519] intraday_13635.csv.gz  in=271,251,663 out=35,826,864 elapsed=99.4s

  [5000/20519] intraday_13638.csv.gz  in=271,275,095 out=35,850,296 elapsed=99.4s

  [5001/20519] intraday_13636.csv.gz  in=271,306,748 out=35,881,614 elapsed=99.5s

  [5002/20519] intraday_1364.csv.gz  in=271,319,863 out=35,881,614 elapsed=99.5s

  [5003/20519] intraday_13637.csv.gz  in=271,350,345 out=35,912,096 elapsed=99.5s

  [5004/20519] intraday_13639.csv.gz  in=271,377,704 out=35,939,455 elapsed=99.5s

  [5005/20519] intraday_13641.csv.gz  in=271,378,548 out=35,940,299 elapsed=99.5s

  [5006/20519] intraday_13642.csv.gz  in=271,379,706 out=35,941,457 elapsed=99.5s

  [5007/20519] intraday_13640.csv.gz  in=271,401,706 out=35,963,457 elapsed=99.5s

  [5008/20519] intraday_13644.csv.gz  in=271,427,316 out=35,988,996 elapsed=99.6s

  [5009/20519] intraday_13643.csv.gz  in=271,454,367 out=36,016,047 elapsed=99.6s

  [5010/20519] intraday_13645.csv.gz  in=271,480,063 out=36,041,743 elapsed=99.6s

  [5011/20519] intraday_13646.csv.gz  in=271,504,341 out=36,066,021 elapsed=99.6s

  [5012/20519] intraday_1365.csv.gz  in=271,515,885 out=36,066,021 elapsed=99.6s

  [5013/20519] intraday_13647.csv.gz  in=271,539,675 out=36,089,811 elapsed=99.7s

  [5014/20519] intraday_13648.csv.gz  in=271,564,196 out=36,114,332 elapsed=99.7s

  [5015/20519] intraday_13649.csv.gz  in=271,588,842 out=36,138,978 elapsed=99.7s

  [5016/20519] intraday_13650.csv.gz  in=271,613,415 out=36,163,551 elapsed=99.7s

  [5017/20519] intraday_13651.csv.gz  in=271,634,834 out=36,184,970 elapsed=99.7s

  [5018/20519] intraday_13652.csv.gz  in=271,660,214 out=36,210,350 elapsed=99.7s

  [5019/20519] intraday_13654.csv.gz  in=271,686,689 out=36,236,825 elapsed=99.8s

  [5020/20519] intraday_13653.csv.gz  in=271,712,029 out=36,262,165 elapsed=99.8s

  [5021/20519] intraday_13657.csv.gz  in=271,722,449 out=36,272,585 elapsed=99.8s

  [5022/20519] intraday_13656.csv.gz  in=271,741,380 out=36,289,843 elapsed=99.8s

  [5023/20519] intraday_13655.csv.gz  in=271,768,051 out=36,316,514 elapsed=99.8s

  [5024/20519] intraday_13658.csv.gz  in=271,793,629 out=36,342,092 elapsed=99.8s

  [5025/20519] intraday_1366.csv.gz  in=271,805,887 out=36,342,092 elapsed=99.8s

  [5026/20519] intraday_13659.csv.gz  in=271,831,313 out=36,367,518 elapsed=99.9s

  [5027/20519] intraday_13660.csv.gz  in=271,854,706 out=36,390,911 elapsed=99.9s

  [5028/20519] intraday_13661.csv.gz  in=271,883,752 out=36,419,957 elapsed=99.9s

  [5029/20519] intraday_13662.csv.gz  in=271,916,434 out=36,452,639 elapsed=99.9s

  [5030/20519] intraday_13663.csv.gz  in=271,941,225 out=36,477,430 elapsed=99.9s

  [5031/20519] intraday_13667.csv.gz  in=271,944,463 out=36,480,668 elapsed=100.0s

  [5032/20519] intraday_13666.csv.gz  in=271,980,266 out=36,516,471 elapsed=100.0s

  [5033/20519] intraday_13664.csv.gz  in=272,010,596 out=36,546,801 elapsed=100.0s

  [5034/20519] intraday_13665.csv.gz  in=272,045,742 out=36,581,947 elapsed=100.0s

  [5035/20519] intraday_13668.csv.gz  in=272,057,374 out=36,593,579 elapsed=100.0s

  [5036/20519] intraday_1367.csv.gz  in=272,065,262 out=36,593,579 elapsed=100.0s

  [5037/20519] intraday_13670.csv.gz  in=272,082,966 out=36,611,283 elapsed=100.1s

  [5038/20519] intraday_13669.csv.gz  in=272,108,865 out=36,637,182 elapsed=100.1s

  [5039/20519] intraday_13671.csv.gz  in=272,136,916 out=36,665,233 elapsed=100.1s

  [5040/20519] intraday_13672.csv.gz  in=272,159,226 out=36,687,543 elapsed=100.1s

  [5041/20519] intraday_13673.csv.gz  in=272,181,905 out=36,710,222 elapsed=100.1s

  [5042/20519] intraday_13674.csv.gz  in=272,210,568 out=36,738,885 elapsed=100.2s

  [5043/20519] intraday_13675.csv.gz  in=272,238,649 out=36,766,966 elapsed=100.2s

  [5044/20519] intraday_13676.csv.gz  in=272,257,686 out=36,786,003 elapsed=100.2s

  [5045/20519] intraday_13677.csv.gz  in=272,282,908 out=36,811,225 elapsed=100.2s

  [5046/20519] intraday_1368.csv.gz  in=272,293,967 out=36,811,225 elapsed=100.2s

  [5047/20519] intraday_13679.csv.gz  in=272,308,724 out=36,825,982 elapsed=100.2s

  [5048/20519] intraday_13681.csv.gz  in=272,310,501 out=36,827,759 elapsed=100.2s

  [5049/20519] intraday_13678.csv.gz  in=272,334,454 out=36,851,712 elapsed=100.2s

  [5050/20519] intraday_13680.csv.gz  in=272,335,182 out=36,852,440 elapsed=100.2s

  [5051/20519] intraday_13683.csv.gz  in=272,359,623 out=36,876,881 elapsed=100.3s

  [5052/20519] intraday_13685.csv.gz  in=272,381,561 out=36,898,819 elapsed=100.3s

  [5053/20519] intraday_13682.csv.gz  in=272,436,075 out=36,935,107 elapsed=100.3s

  [5054/20519] intraday_13684.csv.gz  in=272,467,762 out=36,966,794 elapsed=100.3s

  [5055/20519] intraday_13687.csv.gz  in=272,493,847 out=36,992,879 elapsed=100.4s

  [5056/20519] intraday_13686.csv.gz  in=272,522,176 out=37,021,208 elapsed=100.4s

  [5057/20519] intraday_13689.csv.gz  in=272,545,704 out=37,044,736 elapsed=100.4s

  [5058/20519] intraday_1369.csv.gz  in=272,553,226 out=37,044,736 elapsed=100.4s

  [5059/20519] intraday_13688.csv.gz  in=272,576,446 out=37,067,956 elapsed=100.4s

  [5060/20519] intraday_13690.csv.gz  in=272,589,373 out=37,080,883 elapsed=100.4s

  [5061/20519] intraday_13692.csv.gz  in=272,602,999 out=37,094,509 elapsed=100.5s

  [5062/20519] intraday_13691.csv.gz  in=272,625,826 out=37,117,336 elapsed=100.5s

  [5063/20519] intraday_13693.csv.gz  in=272,658,751 out=37,150,261 elapsed=100.6s

  [5064/20519] intraday_13694.csv.gz  in=272,690,966 out=37,178,417 elapsed=100.6s

  [5065/20519] intraday_13696.csv.gz  in=272,714,439 out=37,201,890 elapsed=100.6s

  [5066/20519] intraday_13695.csv.gz  in=272,744,618 out=37,231,173 elapsed=100.6s

  [5067/20519] intraday_1370.csv.gz  in=272,744,670 out=37,231,173 elapsed=100.6s

  [5068/20519] intraday_13698.csv.gz  in=272,773,710 out=37,260,213 elapsed=100.7s

  [5069/20519] intraday_13697.csv.gz  in=272,796,195 out=37,282,698 elapsed=100.7s

  [5070/20519] intraday_13700.csv.gz  in=272,818,523 out=37,305,026 elapsed=100.7s

  [5071/20519] intraday_13699.csv.gz  in=272,849,040 out=37,335,543 elapsed=100.7s

  [5072/20519] intraday_13702.csv.gz  in=272,859,442 out=37,345,175 elapsed=100.7s

  [5073/20519] intraday_13701.csv.gz  in=272,884,519 out=37,370,252 elapsed=100.7s

  [5074/20519] intraday_13703.csv.gz  in=272,901,854 out=37,387,587 elapsed=100.7s

  [5075/20519] intraday_13705.csv.gz  in=272,920,453 out=37,406,186 elapsed=100.8s

  [5076/20519] intraday_13706.csv.gz  in=272,943,611 out=37,429,344 elapsed=100.8s

  [5077/20519] intraday_13704.csv.gz  in=272,972,500 out=37,458,233 elapsed=100.8s

  [5078/20519] intraday_1371.csv.gz  in=272,972,725 out=37,458,233 elapsed=100.8s

  [5079/20519] intraday_13708.csv.gz  in=272,997,124 out=37,482,632 elapsed=100.8s

  [5080/20519] intraday_13707.csv.gz  in=273,031,055 out=37,516,563 elapsed=100.8s

  [5081/20519] intraday_13709.csv.gz  in=273,055,941 out=37,541,449 elapsed=100.8s

  [5082/20519] intraday_13710.csv.gz  in=273,080,128 out=37,565,636 elapsed=100.9s

  [5083/20519] intraday_13712.csv.gz  in=273,103,425 out=37,588,933 elapsed=100.9s

  [5084/20519] intraday_13713.csv.gz  in=273,132,545 out=37,618,053 elapsed=100.9s

  [5085/20519] intraday_13714.csv.gz  in=273,158,791 out=37,644,299 elapsed=100.9s

  [5086/20519] intraday_13711.csv.gz  in=273,194,891 out=37,677,593 elapsed=100.9s

  [5087/20519] intraday_13715.csv.gz  in=273,203,624 out=37,686,326 elapsed=100.9s

  [5088/20519] intraday_13716.csv.gz  in=273,223,832 out=37,706,534 elapsed=101.0s

  [5089/20519] intraday_1372.csv.gz  in=273,223,850 out=37,706,534 elapsed=101.0s

  [5090/20519] intraday_13717.csv.gz  in=273,245,485 out=37,728,169 elapsed=101.0s

  [5091/20519] intraday_13719.csv.gz  in=273,277,352 out=37,760,036 elapsed=101.0s

  [5092/20519] intraday_13718.csv.gz  in=273,308,474 out=37,791,158 elapsed=101.0s

  [5093/20519] intraday_13721.csv.gz  in=273,329,843 out=37,812,527 elapsed=101.0s

  [5094/20519] intraday_13720.csv.gz  in=273,357,996 out=37,840,680 elapsed=101.1s

  [5095/20519] intraday_13722.csv.gz  in=273,382,857 out=37,865,541 elapsed=101.1s

  [5096/20519] intraday_13723.csv.gz  in=273,407,426 out=37,890,110 elapsed=101.1s

  [5097/20519] intraday_13726.csv.gz  in=273,429,318 out=37,912,002 elapsed=101.1s

  [5098/20519] intraday_13725.csv.gz  in=273,453,673 out=37,936,357 elapsed=101.1s

  [5099/20519] intraday_13724.csv.gz  in=273,499,511 out=37,969,497 elapsed=101.2s

  [5100/20519] intraday_13728.csv.gz  in=273,508,222 out=37,978,208 elapsed=101.2s

  [5101/20519] intraday_1373.csv.gz  in=273,508,268 out=37,978,208 elapsed=101.2s

  [5102/20519] intraday_13729.csv.gz  in=273,531,222 out=38,001,162 elapsed=101.2s

  [5103/20519] intraday_13727.csv.gz  in=273,550,239 out=38,020,179 elapsed=101.2s

  [5104/20519] intraday_13730.csv.gz  in=273,582,840 out=38,050,214 elapsed=101.2s

  [5105/20519] intraday_13731.csv.gz  in=273,612,279 out=38,079,653 elapsed=101.3s

  [5106/20519] intraday_13732.csv.gz  in=273,637,392 out=38,104,766 elapsed=101.3s

  [5107/20519] intraday_13734.csv.gz  in=273,664,513 out=38,131,887 elapsed=101.3s

  [5108/20519] intraday_13733.csv.gz  in=273,694,869 out=38,157,525 elapsed=101.3s

  [5109/20519] intraday_13735.csv.gz  in=273,715,929 out=38,178,585 elapsed=101.3s

  [5110/20519] intraday_13736.csv.gz  in=273,739,609 out=38,202,265 elapsed=101.3s

  [5111/20519] intraday_13737.csv.gz  in=273,762,757 out=38,225,413 elapsed=101.4s

  [5112/20519] intraday_1374.csv.gz  in=273,762,761 out=38,225,413 elapsed=101.4s

  [5113/20519] intraday_13738.csv.gz  in=273,784,052 out=38,246,704 elapsed=101.4s

  [5114/20519] intraday_13739.csv.gz  in=273,813,181 out=38,275,833 elapsed=101.4s

  [5115/20519] intraday_13740.csv.gz  in=273,828,568 out=38,291,220 elapsed=101.4s

  [5116/20519] intraday_13741.csv.gz  in=273,835,312 out=38,297,964 elapsed=101.4s

  [5117/20519] intraday_13742.csv.gz  in=273,859,205 out=38,321,857 elapsed=101.4s

  [5118/20519] intraday_13744.csv.gz  in=273,882,239 out=38,344,891 elapsed=101.5s

  [5119/20519] intraday_13743.csv.gz  in=273,917,856 out=38,373,592 elapsed=101.5s

  [5120/20519] intraday_13745.csv.gz  in=273,945,450 out=38,401,186 elapsed=101.5s

  [5121/20519] intraday_13747.csv.gz  in=273,967,865 out=38,423,601 elapsed=101.5s

  [5122/20519] intraday_1375.csv.gz  in=273,967,927 out=38,423,601 elapsed=101.6s

  [5123/20519] intraday_13746.csv.gz  in=274,003,099 out=38,453,339 elapsed=101.6s

  [5124/20519] intraday_13748.csv.gz  in=274,027,051 out=38,477,291 elapsed=101.6s

  [5125/20519] intraday_13749.csv.gz  in=274,054,134 out=38,500,456 elapsed=101.6s

  [5126/20519] intraday_13750.csv.gz  in=274,082,045 out=38,528,367 elapsed=101.6s

  [5127/20519] intraday_13751.csv.gz  in=274,112,879 out=38,559,201 elapsed=101.7s

  [5128/20519] intraday_13753.csv.gz  in=274,137,575 out=38,583,897 elapsed=101.7s

  [5129/20519] intraday_13752.csv.gz  in=274,171,186 out=38,615,586 elapsed=101.7s

  [5130/20519] intraday_13754.csv.gz  in=274,179,510 out=38,623,910 elapsed=101.7s

  [5131/20519] intraday_13756.csv.gz  in=274,205,848 out=38,650,248 elapsed=101.7s

  [5132/20519] intraday_13757.csv.gz  in=274,230,039 out=38,674,439 elapsed=101.8s

  [5133/20519] intraday_13758.csv.gz  in=274,256,104 out=38,700,504 elapsed=101.8s

  [5134/20519] intraday_1376.csv.gz  in=274,256,190 out=38,700,504 elapsed=101.8s

  [5135/20519] intraday_13759.csv.gz  in=274,275,812 out=38,720,126 elapsed=101.8s

  [5136/20519] intraday_13755.csv.gz  in=274,300,968 out=38,745,282 elapsed=101.8s

  [5137/20519] intraday_13761.csv.gz  in=274,329,274 out=38,773,588 elapsed=101.8s

  [5138/20519] intraday_13760.csv.gz  in=274,353,430 out=38,797,744 elapsed=101.8s

  [5139/20519] intraday_13762.csv.gz  in=274,376,998 out=38,821,312 elapsed=101.9s

  [5140/20519] intraday_13763.csv.gz  in=274,400,495 out=38,844,809 elapsed=101.9s

  [5141/20519] intraday_13764.csv.gz  in=274,419,065 out=38,863,379 elapsed=101.9s

  [5142/20519] intraday_13765.csv.gz  in=274,442,726 out=38,887,040 elapsed=101.9s

  [5143/20519] intraday_13767.csv.gz  in=274,443,311 out=38,887,625 elapsed=101.9s

  [5144/20519] intraday_13768.csv.gz  in=274,444,002 out=38,888,316 elapsed=101.9s

  [5145/20519] intraday_13766.csv.gz  in=274,475,071 out=38,919,385 elapsed=101.9s

  [5146/20519] intraday_1377.csv.gz  in=274,475,955 out=38,919,385 elapsed=101.9s

  [5147/20519] intraday_13769.csv.gz  in=274,497,328 out=38,940,758 elapsed=102.0s

  [5148/20519] intraday_13771.csv.gz  in=274,519,666 out=38,963,096 elapsed=102.0s

  [5149/20519] intraday_13770.csv.gz  in=274,544,868 out=38,988,298 elapsed=102.0s

  [5150/20519] intraday_13773.csv.gz  in=274,567,853 out=39,011,283 elapsed=102.0s

  [5151/20519] intraday_13774.csv.gz  in=274,591,573 out=39,035,003 elapsed=102.0s

  [5152/20519] intraday_13772.csv.gz  in=274,617,994 out=39,061,424 elapsed=102.1s

  [5153/20519] intraday_13775.csv.gz  in=274,645,017 out=39,088,447 elapsed=102.1s

  [5154/20519] intraday_13776.csv.gz  in=274,670,261 out=39,113,691 elapsed=102.1s

  [5155/20519] intraday_1378.csv.gz  in=274,686,643 out=39,113,691 elapsed=102.1s

  [5156/20519] intraday_13778.csv.gz  in=274,709,293 out=39,136,341 elapsed=102.1s

  [5157/20519] intraday_13777.csv.gz  in=274,734,532 out=39,161,580 elapsed=102.1s

  [5158/20519] intraday_13779.csv.gz  in=274,760,157 out=39,187,205 elapsed=102.1s

  [5159/20519] intraday_13783.csv.gz  in=274,760,164 out=39,187,212 elapsed=102.1s

  [5160/20519] intraday_13780.csv.gz  in=274,784,606 out=39,211,654 elapsed=102.2s

  [5161/20519] intraday_13781.csv.gz  in=274,809,632 out=39,235,607 elapsed=102.2s

  [5162/20519] intraday_13782.csv.gz  in=274,818,579 out=39,244,554 elapsed=102.2s

  [5163/20519] intraday_13785.csv.gz  in=274,843,742 out=39,269,717 elapsed=102.2s

  [5164/20519] intraday_13784.csv.gz  in=274,870,523 out=39,296,498 elapsed=102.3s

  [5165/20519] intraday_13786.csv.gz  in=274,898,264 out=39,324,239 elapsed=102.3s

  [5166/20519] intraday_13787.csv.gz  in=274,923,868 out=39,348,607 elapsed=102.3s

  [5167/20519] intraday_13789.csv.gz  in=274,945,054 out=39,369,793 elapsed=102.3s

  [5168/20519] intraday_13788.csv.gz  in=274,977,474 out=39,402,213 elapsed=102.3s

  [5169/20519] intraday_1379.csv.gz  in=274,992,088 out=39,402,213 elapsed=102.3s

  [5170/20519] intraday_13790.csv.gz  in=275,018,369 out=39,426,244 elapsed=102.3s

  [5171/20519] intraday_13794.csv.gz  in=275,021,823 out=39,429,698 elapsed=102.4s

  [5172/20519] intraday_13791.csv.gz  in=275,050,165 out=39,458,040 elapsed=102.4s

  [5173/20519] intraday_13793.csv.gz  in=275,064,949 out=39,472,824 elapsed=102.4s

  [5174/20519] intraday_13792.csv.gz  in=275,094,454 out=39,502,329 elapsed=102.4s

  [5175/20519] intraday_13795.csv.gz  in=275,122,520 out=39,530,395 elapsed=102.4s

  [5176/20519] intraday_13796.csv.gz  in=275,149,542 out=39,557,417 elapsed=102.5s

  [5177/20519] intraday_13797.csv.gz  in=275,183,870 out=39,591,745 elapsed=102.5s

  [5178/20519] intraday_13798.csv.gz  in=275,220,314 out=39,628,189 elapsed=102.5s

  [5179/20519] intraday_13799.csv.gz  in=275,249,325 out=39,656,060 elapsed=102.5s

  [5180/20519] intraday_1380.csv.gz  in=275,262,286 out=39,656,060 elapsed=102.5s

  [5181/20519] intraday_13801.csv.gz  in=275,284,448 out=39,678,222 elapsed=102.5s

  [5182/20519] intraday_13800.csv.gz  in=275,313,256 out=39,707,030 elapsed=102.5s

  [5183/20519] intraday_13802.csv.gz  in=275,339,297 out=39,733,071 elapsed=102.6s

  [5184/20519] intraday_13806.csv.gz  in=275,340,791 out=39,734,565 elapsed=102.6s

  [5185/20519] intraday_13803.csv.gz  in=275,360,784 out=39,754,558 elapsed=102.6s

  [5186/20519] intraday_13805.csv.gz  in=275,378,448 out=39,772,222 elapsed=102.6s

  [5187/20519] intraday_13804.csv.gz  in=275,405,510 out=39,799,284 elapsed=102.6s

  [5188/20519] intraday_13808.csv.gz  in=275,428,063 out=39,821,837 elapsed=102.6s

  [5189/20519] intraday_13809.csv.gz  in=275,451,809 out=39,845,583 elapsed=102.7s

  [5190/20519] intraday_13807.csv.gz  in=275,480,203 out=39,873,977 elapsed=102.7s

  [5191/20519] intraday_1381.csv.gz  in=275,495,109 out=39,873,977 elapsed=102.7s

  [5192/20519] intraday_13810.csv.gz  in=275,516,690 out=39,895,558 elapsed=102.7s

  [5193/20519] intraday_13813.csv.gz  in=275,542,752 out=39,921,620 elapsed=102.7s

  [5194/20519] intraday_13811.csv.gz  in=275,570,233 out=39,948,131 elapsed=102.7s

  [5195/20519] intraday_13812.csv.gz  in=275,594,376 out=39,972,274 elapsed=102.8s

  [5196/20519] intraday_13814.csv.gz  in=275,624,106 out=40,001,998 elapsed=102.8s

  [5197/20519] intraday_13816.csv.gz  in=275,651,315 out=40,029,207 elapsed=102.8s

  [5198/20519] intraday_13815.csv.gz  in=275,679,006 out=40,056,898 elapsed=102.8s

  [5199/20519] intraday_13818.csv.gz  in=275,680,811 out=40,058,703 elapsed=102.8s

  [5200/20519] intraday_13817.csv.gz  in=275,705,127 out=40,083,019 elapsed=102.9s

  [5201/20519] intraday_13819.csv.gz  in=275,714,226 out=40,092,118 elapsed=102.9s

  [5202/20519] intraday_1382.csv.gz  in=275,728,776 out=40,092,118 elapsed=102.9s

  [5203/20519] intraday_13821.csv.gz  in=275,747,718 out=40,111,060 elapsed=102.9s

  [5204/20519] intraday_13822.csv.gz  in=275,767,962 out=40,131,304 elapsed=102.9s

  [5205/20519] intraday_13823.csv.gz  in=275,795,816 out=40,159,158 elapsed=102.9s

  [5206/20519] intraday_13820.csv.gz  in=275,824,250 out=40,185,850 elapsed=103.0s

  [5207/20519] intraday_13825.csv.gz  in=275,835,882 out=40,197,482 elapsed=103.0s

  [5208/20519] intraday_13824.csv.gz  in=275,851,821 out=40,213,421 elapsed=103.0s

  [5209/20519] intraday_13826.csv.gz  in=275,863,889 out=40,225,489 elapsed=103.0s

  [5210/20519] intraday_13827.csv.gz  in=275,875,245 out=40,236,510 elapsed=103.0s

  [5211/20519] intraday_13829.csv.gz  in=275,888,762 out=40,250,027 elapsed=103.0s

  [5212/20519] intraday_1383.csv.gz  in=275,903,682 out=40,250,027 elapsed=103.0s

  [5213/20519] intraday_13828.csv.gz  in=275,914,898 out=40,261,243 elapsed=103.0s

  [5214/20519] intraday_13830.csv.gz  in=275,927,300 out=40,273,645 elapsed=103.1s

  [5215/20519] intraday_13832.csv.gz  in=275,931,144 out=40,277,489 elapsed=103.1s

  [5216/20519] intraday_13833.csv.gz  in=275,931,466 out=40,277,811 elapsed=103.1s

  [5217/20519] intraday_13831.csv.gz  in=275,942,678 out=40,289,023 elapsed=103.1s

  [5218/20519] intraday_13834.csv.gz  in=275,943,728 out=40,290,073 elapsed=103.1s

  [5219/20519] intraday_13837.csv.gz  in=275,952,822 out=40,299,167 elapsed=103.1s

  [5220/20519] intraday_13835.csv.gz  in=275,963,610 out=40,309,955 elapsed=103.1s

  [5221/20519] intraday_13836.csv.gz  in=275,977,682 out=40,324,027 elapsed=103.1s

  [5222/20519] intraday_13838.csv.gz  in=275,987,764 out=40,334,109 elapsed=103.1s

  [5223/20519] intraday_1384.csv.gz  in=276,001,240 out=40,334,109 elapsed=103.2s

  [5224/20519] intraday_13841.csv.gz  in=276,011,383 out=40,344,252 elapsed=103.2s

  [5225/20519] intraday_13839.csv.gz  in=276,028,306 out=40,361,175 elapsed=103.2s

  [5226/20519] intraday_13840.csv.gz  in=276,042,529 out=40,375,398 elapsed=103.2s

  [5227/20519] intraday_13842.csv.gz  in=276,054,437 out=40,387,306 elapsed=103.2s

  [5228/20519] intraday_13843.csv.gz  in=276,069,912 out=40,402,781 elapsed=103.2s

  [5229/20519] intraday_13846.csv.gz  in=276,076,320 out=40,409,189 elapsed=103.3s

  [5230/20519] intraday_13847.csv.gz  in=276,076,493 out=40,409,362 elapsed=103.3s

  [5231/20519] intraday_13844.csv.gz  in=276,087,827 out=40,420,696 elapsed=103.3s

  [5232/20519] intraday_13845.csv.gz  in=276,101,809 out=40,434,678 elapsed=103.3s

  [5233/20519] intraday_13849.csv.gz  in=276,113,737 out=40,446,606 elapsed=103.3s

  [5234/20519] intraday_1385.csv.gz  in=276,127,083 out=40,446,606 elapsed=103.3s

  [5235/20519] intraday_13848.csv.gz  in=276,136,314 out=40,455,837 elapsed=103.3s

  [5236/20519] intraday_13850.csv.gz  in=276,148,183 out=40,467,706 elapsed=103.3s

  [5237/20519] intraday_13851.csv.gz  in=276,161,608 out=40,481,131 elapsed=103.3s

  [5238/20519] intraday_13853.csv.gz  in=276,174,470 out=40,493,993 elapsed=103.3s

  [5239/20519] intraday_13852.csv.gz  in=276,189,821 out=40,509,344 elapsed=103.3s

  [5240/20519] intraday_13854.csv.gz  in=276,199,273 out=40,518,796 elapsed=103.3s

  [5241/20519] intraday_13855.csv.gz  in=276,212,046 out=40,531,569 elapsed=103.3s

  [5242/20519] intraday_13856.csv.gz  in=276,223,216 out=40,542,739 elapsed=103.4s

  [5243/20519] intraday_13858.csv.gz  in=276,234,548 out=40,554,071 elapsed=103.4s

  [5244/20519] intraday_1386.csv.gz  in=276,248,975 out=40,554,071 elapsed=103.4s

  [5245/20519] intraday_13857.csv.gz  in=276,260,712 out=40,565,808 elapsed=103.4s

  [5246/20519] intraday_13859.csv.gz  in=276,271,621 out=40,576,717 elapsed=103.4s

  [5247/20519] intraday_13860.csv.gz  in=276,282,715 out=40,587,811 elapsed=103.4s

  [5248/20519] intraday_13861.csv.gz  in=276,292,190 out=40,597,286 elapsed=103.5s

  [5249/20519] intraday_13862.csv.gz  in=276,303,042 out=40,608,138 elapsed=103.5s

  [5250/20519] intraday_13863.csv.gz  in=276,314,001 out=40,619,097 elapsed=103.5s

  [5251/20519] intraday_13864.csv.gz  in=276,329,153 out=40,634,249 elapsed=103.5s

  [5252/20519] intraday_13865.csv.gz  in=276,340,885 out=40,645,981 elapsed=103.5s

  [5253/20519] intraday_13866.csv.gz  in=276,355,009 out=40,660,105 elapsed=103.5s

  [5254/20519] intraday_13868.csv.gz  in=276,355,341 out=40,660,437 elapsed=103.5s

  [5255/20519] intraday_13867.csv.gz  in=276,364,483 out=40,669,576 elapsed=103.5s

  [5256/20519] intraday_13869.csv.gz  in=276,373,713 out=40,678,806 elapsed=103.6s

  [5257/20519] intraday_1387.csv.gz  in=276,389,020 out=40,678,806 elapsed=103.6s

  [5258/20519] intraday_13870.csv.gz  in=276,400,072 out=40,689,858 elapsed=103.6s

  [5259/20519] intraday_13871.csv.gz  in=276,411,122 out=40,700,908 elapsed=103.6s

  [5260/20519] intraday_13872.csv.gz  in=276,423,466 out=40,713,252 elapsed=103.6s

  [5261/20519] intraday_13873.csv.gz  in=276,435,947 out=40,725,733 elapsed=103.6s

  [5262/20519] intraday_13874.csv.gz  in=276,448,525 out=40,738,311 elapsed=103.6s

  [5263/20519] intraday_13876.csv.gz  in=276,458,950 out=40,748,736 elapsed=103.7s

  [5264/20519] intraday_13875.csv.gz  in=276,470,526 out=40,760,312 elapsed=103.7s

  [5265/20519] intraday_13877.csv.gz  in=276,482,608 out=40,772,394 elapsed=103.7s

  [5266/20519] intraday_13878.csv.gz  in=276,493,754 out=40,783,222 elapsed=103.7s

  [5267/20519] intraday_13879.csv.gz  in=276,505,344 out=40,794,812 elapsed=103.7s

  [5268/20519] intraday_1388.csv.gz  in=276,515,734 out=40,794,812 elapsed=103.7s

  [5269/20519] intraday_13881.csv.gz  in=276,521,311 out=40,800,389 elapsed=103.7s

  [5270/20519] intraday_13880.csv.gz  in=276,532,568 out=40,811,646 elapsed=103.7s

  [5271/20519] intraday_13882.csv.gz  in=276,542,970 out=40,822,048 elapsed=103.7s

  [5272/20519] intraday_13883.csv.gz  in=276,552,888 out=40,831,966 elapsed=103.8s

  [5273/20519] intraday_13884.csv.gz  in=276,566,280 out=40,845,358 elapsed=103.8s

  [5274/20519] intraday_13886.csv.gz  in=276,580,699 out=40,859,777 elapsed=103.8s

  [5275/20519] intraday_13885.csv.gz  in=276,593,559 out=40,872,637 elapsed=103.8s

  [5276/20519] intraday_13889.csv.gz  in=276,603,401 out=40,882,479 elapsed=103.8s

  [5277/20519] intraday_13887.csv.gz  in=276,614,887 out=40,893,946 elapsed=103.8s

  [5278/20519] intraday_1389.csv.gz  in=276,627,710 out=40,893,946 elapsed=103.8s

  [5279/20519] intraday_13890.csv.gz  in=276,640,626 out=40,906,862 elapsed=103.8s

  [5280/20519] intraday_13888.csv.gz  in=276,651,764 out=40,918,000 elapsed=103.8s

  [5281/20519] intraday_13892.csv.gz  in=276,652,838 out=40,919,074 elapsed=103.9s

  [5282/20519] intraday_13893.csv.gz  in=276,656,955 out=40,923,191 elapsed=103.9s

  [5283/20519] intraday_13891.csv.gz  in=276,668,829 out=40,935,065 elapsed=103.9s

  [5284/20519] intraday_13894.csv.gz  in=276,678,947 out=40,945,183 elapsed=103.9s

  [5285/20519] intraday_13895.csv.gz  in=276,692,465 out=40,958,701 elapsed=103.9s

  [5286/20519] intraday_13896.csv.gz  in=276,703,149 out=40,969,385 elapsed=103.9s

  [5287/20519] intraday_13897.csv.gz  in=276,714,285 out=40,980,521 elapsed=103.9s

  [5288/20519] intraday_13899.csv.gz  in=276,724,832 out=40,991,068 elapsed=103.9s

  [5289/20519] intraday_1390.csv.gz  in=276,740,282 out=40,991,068 elapsed=103.9s

  [5290/20519] intraday_13898.csv.gz  in=276,750,759 out=41,001,545 elapsed=104.0s

  [5291/20519] intraday_13900.csv.gz  in=276,762,791 out=41,013,577 elapsed=104.0s

  [5292/20519] intraday_13901.csv.gz  in=276,775,291 out=41,026,077 elapsed=104.0s

  [5293/20519] intraday_13903.csv.gz  in=276,787,832 out=41,038,618 elapsed=104.0s

  [5294/20519] intraday_13902.csv.gz  in=276,805,254 out=41,056,040 elapsed=104.0s

  [5295/20519] intraday_13904.csv.gz  in=276,816,521 out=41,067,307 elapsed=104.0s

  [5296/20519] intraday_13905.csv.gz  in=276,827,318 out=41,078,104 elapsed=104.1s

  [5297/20519] intraday_13907.csv.gz  in=276,839,775 out=41,090,561 elapsed=104.1s

  [5298/20519] intraday_13906.csv.gz  in=276,850,931 out=41,101,717 elapsed=104.1s

  [5299/20519] intraday_13908.csv.gz  in=276,862,653 out=41,113,439 elapsed=104.1s

  [5300/20519] intraday_13909.csv.gz  in=276,871,981 out=41,122,767 elapsed=104.1s

  [5301/20519] intraday_1391.csv.gz  in=276,883,694 out=41,122,767 elapsed=104.1s

  [5302/20519] intraday_13910.csv.gz  in=276,896,865 out=41,135,938 elapsed=104.1s

  [5303/20519] intraday_13911.csv.gz  in=276,907,721 out=41,146,794 elapsed=104.1s

  [5304/20519] intraday_13912.csv.gz  in=276,918,688 out=41,157,761 elapsed=104.1s

  [5305/20519] intraday_13913.csv.gz  in=276,931,015 out=41,170,088 elapsed=104.2s

  [5306/20519] intraday_13914.csv.gz  in=276,942,792 out=41,181,865 elapsed=104.2s

  [5307/20519] intraday_13915.csv.gz  in=276,954,695 out=41,193,768 elapsed=104.2s

  [5308/20519] intraday_13917.csv.gz  in=276,955,668 out=41,194,741 elapsed=104.2s

  [5309/20519] intraday_13916.csv.gz  in=276,962,247 out=41,201,320 elapsed=104.2s

  [5310/20519] intraday_13918.csv.gz  in=276,975,084 out=41,214,157 elapsed=104.2s

  [5311/20519] intraday_1392.csv.gz  in=276,986,035 out=41,214,157 elapsed=104.2s

  [5312/20519] intraday_13920.csv.gz  in=276,996,059 out=41,224,181 elapsed=104.3s

  [5313/20519] intraday_13919.csv.gz  in=277,008,683 out=41,236,805 elapsed=104.3s

  [5314/20519] intraday_13921.csv.gz  in=277,020,564 out=41,248,686 elapsed=104.3s

  [5315/20519] intraday_13922.csv.gz  in=277,031,671 out=41,259,793 elapsed=104.3s

  [5316/20519] intraday_13924.csv.gz  in=277,042,044 out=41,270,166 elapsed=104.3s

  [5317/20519] intraday_13923.csv.gz  in=277,057,003 out=41,285,125 elapsed=104.3s

  [5318/20519] intraday_13925.csv.gz  in=277,067,802 out=41,295,924 elapsed=104.3s

  [5319/20519] intraday_13926.csv.gz  in=277,080,558 out=41,308,680 elapsed=104.3s

  [5320/20519] intraday_13927.csv.gz  in=277,095,510 out=41,323,632 elapsed=104.4s

  [5321/20519] intraday_13928.csv.gz  in=277,107,552 out=41,335,674 elapsed=104.4s

  [5322/20519] intraday_13929.csv.gz  in=277,120,407 out=41,348,529 elapsed=104.4s

  [5323/20519] intraday_1393.csv.gz  in=277,134,671 out=41,348,529 elapsed=104.4s

  [5324/20519] intraday_13930.csv.gz  in=277,147,607 out=41,361,465 elapsed=104.4s

  [5325/20519] intraday_13931.csv.gz  in=277,160,615 out=41,374,473 elapsed=104.4s

  [5326/20519] intraday_13933.csv.gz  in=277,174,454 out=41,388,312 elapsed=104.4s

  [5327/20519] intraday_13932.csv.gz  in=277,187,053 out=41,400,911 elapsed=104.5s

  [5328/20519] intraday_13935.csv.gz  in=277,198,690 out=41,412,548 elapsed=104.5s

  [5329/20519] intraday_13934.csv.gz  in=277,216,411 out=41,430,269 elapsed=104.5s

  [5330/20519] intraday_13937.csv.gz  in=277,228,376 out=41,442,234 elapsed=104.5s

  [5331/20519] intraday_13938.csv.gz  in=277,241,899 out=41,455,757 elapsed=104.5s

  [5332/20519] intraday_13939.csv.gz  in=277,251,663 out=41,465,521 elapsed=104.5s

  [5333/20519] intraday_13936.csv.gz  in=277,265,911 out=41,479,769 elapsed=104.5s

  [5334/20519] intraday_1394.csv.gz  in=277,279,110 out=41,479,769 elapsed=104.5s

  [5335/20519] intraday_13941.csv.gz  in=277,291,358 out=41,492,017 elapsed=104.6s

  [5336/20519] intraday_13943.csv.gz  in=277,302,233 out=41,502,892 elapsed=104.6s

  [5337/20519] intraday_13940.csv.gz  in=277,313,570 out=41,514,229 elapsed=104.6s

  [5338/20519] intraday_13942.csv.gz  in=277,325,229 out=41,525,888 elapsed=104.6s

  [5339/20519] intraday_13944.csv.gz  in=277,339,940 out=41,540,599 elapsed=104.6s

  [5340/20519] intraday_13945.csv.gz  in=277,349,822 out=41,550,481 elapsed=104.6s

  [5341/20519] intraday_13946.csv.gz  in=277,361,994 out=41,562,653 elapsed=104.7s

  [5342/20519] intraday_13947.csv.gz  in=277,372,968 out=41,573,627 elapsed=104.7s

  [5343/20519] intraday_1395.csv.gz  in=277,386,599 out=41,573,627 elapsed=104.7s

  [5344/20519] intraday_13948.csv.gz  in=277,399,054 out=41,586,082 elapsed=104.7s

  [5345/20519] intraday_13950.csv.gz  in=277,411,675 out=41,598,703 elapsed=104.7s

  [5346/20519] intraday_13949.csv.gz  in=277,424,233 out=41,611,261 elapsed=104.7s

  [5347/20519] intraday_13951.csv.gz  in=277,437,739 out=41,624,767 elapsed=104.7s

  [5348/20519] intraday_13952.csv.gz  in=277,450,767 out=41,637,795 elapsed=104.7s

  [5349/20519] intraday_13953.csv.gz  in=277,462,764 out=41,649,792 elapsed=104.8s

  [5350/20519] intraday_13954.csv.gz  in=277,475,169 out=41,662,197 elapsed=104.8s

  [5351/20519] intraday_13955.csv.gz  in=277,485,974 out=41,673,002 elapsed=104.8s

  [5352/20519] intraday_13956.csv.gz  in=277,499,462 out=41,686,490 elapsed=104.8s

  [5353/20519] intraday_13957.csv.gz  in=277,510,147 out=41,697,175 elapsed=104.8s

  [5354/20519] intraday_13958.csv.gz  in=277,522,488 out=41,709,516 elapsed=104.8s

  [5355/20519] intraday_1396.csv.gz  in=277,535,234 out=41,709,516 elapsed=104.8s

  [5356/20519] intraday_13962.csv.gz  in=277,536,795 out=41,711,077 elapsed=104.9s

  [5357/20519] intraday_13959.csv.gz  in=277,547,937 out=41,722,219 elapsed=104.9s

  [5358/20519] intraday_13960.csv.gz  in=277,556,626 out=41,730,908 elapsed=104.9s

  [5359/20519] intraday_13963.csv.gz  in=277,558,281 out=41,731,219 elapsed=104.9s

  [5360/20519] intraday_13966.csv.gz  in=277,558,283 out=41,731,221 elapsed=104.9s

  [5361/20519] intraday_13961.csv.gz  in=277,571,816 out=41,744,754 elapsed=104.9s

  [5362/20519] intraday_13964.csv.gz  in=277,573,382 out=41,746,320 elapsed=104.9s

  [5363/20519] intraday_13965.csv.gz  in=277,573,542 out=41,746,480 elapsed=104.9s

  [5364/20519] intraday_13969.csv.gz  in=277,573,850 out=41,746,788 elapsed=104.9s

  [5365/20519] intraday_13968.csv.gz  in=277,573,984 out=41,746,922 elapsed=104.9s

  [5366/20519] intraday_13967.csv.gz  in=277,591,930 out=41,753,446 elapsed=104.9s

  [5367/20519] intraday_1397.csv.gz  in=277,603,652 out=41,753,446 elapsed=104.9s

  [5368/20519] intraday_13970.csv.gz  in=277,603,768 out=41,753,562 elapsed=105.0s

  [5369/20519] intraday_13971.csv.gz  in=277,604,856 out=41,754,177 elapsed=105.0s

  [5370/20519] intraday_13972.csv.gz  in=277,605,463 out=41,754,784 elapsed=105.0s

  [5371/20519] intraday_13973.csv.gz  in=277,605,667 out=41,754,988 elapsed=105.0s

  [5372/20519] intraday_13975.csv.gz  in=277,605,698 out=41,755,019 elapsed=105.0s

  [5373/20519] intraday_13976.csv.gz  in=277,608,961 out=41,756,653 elapsed=105.0s

  [5374/20519] intraday_13974.csv.gz  in=277,629,932 out=41,766,485 elapsed=105.0s

  [5375/20519] intraday_13977.csv.gz  in=277,633,847 out=41,769,258 elapsed=105.0s

  [5376/20519] intraday_13978.csv.gz  in=277,634,188 out=41,769,545 elapsed=105.0s

  [5377/20519] intraday_13979.csv.gz  in=277,634,234 out=41,769,591 elapsed=105.0s

  [5378/20519] intraday_13981.csv.gz  in=277,634,282 out=41,769,639 elapsed=105.0s

  [5379/20519] intraday_13982.csv.gz  in=277,635,166 out=41,770,523 elapsed=105.0s

  [5380/20519] intraday_13980.csv.gz  in=277,636,840 out=41,772,197 elapsed=105.0s

  [5381/20519] intraday_13983.csv.gz  in=277,636,865 out=41,772,222 elapsed=105.1s

  [5382/20519] intraday_1398.csv.gz  in=277,650,770 out=41,772,222 elapsed=105.1s

  [5383/20519] intraday_13984.csv.gz  in=277,650,801 out=41,772,253 elapsed=105.1s

  [5384/20519] intraday_13985.csv.gz  in=277,650,965 out=41,772,417 elapsed=105.1s

  [5385/20519] intraday_13986.csv.gz  in=277,653,765 out=41,774,195 elapsed=105.1s

  [5386/20519] intraday_13987.csv.gz  in=277,653,906 out=41,774,336 elapsed=105.1s

  [5387/20519] intraday_13988.csv.gz  in=277,654,033 out=41,774,463 elapsed=105.1s

  [5388/20519] intraday_1399.csv.gz  in=277,666,779 out=41,774,463 elapsed=105.1s

  [5389/20519] intraday_13990.csv.gz  in=277,682,101 out=41,789,785 elapsed=105.2s

  [5390/20519] intraday_13989.csv.gz  in=277,712,515 out=41,798,093 elapsed=105.2s

  [5391/20519] intraday_13991.csv.gz  in=277,725,064 out=41,810,642 elapsed=105.2s

  [5392/20519] intraday_13992.csv.gz  in=277,737,479 out=41,823,057 elapsed=105.2s

  [5393/20519] intraday_13993.csv.gz  in=277,748,274 out=41,833,852 elapsed=105.2s

  [5394/20519] intraday_13994.csv.gz  in=277,759,518 out=41,845,096 elapsed=105.2s

  [5395/20519] intraday_13996.csv.gz  in=277,771,834 out=41,857,412 elapsed=105.2s

  [5396/20519] intraday_13995.csv.gz  in=277,786,744 out=41,872,322 elapsed=105.2s

  [5397/20519] intraday_13997.csv.gz  in=277,798,175 out=41,883,753 elapsed=105.3s

  [5398/20519] intraday_13998.csv.gz  in=277,811,393 out=41,896,971 elapsed=105.3s

  [5399/20519] intraday_1400.csv.gz  in=277,830,800 out=41,896,971 elapsed=105.3s

  [5400/20519] intraday_13999.csv.gz  in=277,842,977 out=41,909,148 elapsed=105.3s

  [5401/20519] intraday_14000.csv.gz  in=277,854,611 out=41,920,782 elapsed=105.3s

  [5402/20519] intraday_14001.csv.gz  in=277,866,575 out=41,932,746 elapsed=105.3s

  [5403/20519] intraday_14002.csv.gz  in=277,878,006 out=41,944,177 elapsed=105.3s

  [5404/20519] intraday_14003.csv.gz  in=277,892,163 out=41,958,334 elapsed=105.3s

  [5405/20519] intraday_14005.csv.gz  in=277,900,325 out=41,966,496 elapsed=105.4s

  [5406/20519] intraday_14004.csv.gz  in=277,911,393 out=41,977,564 elapsed=105.4s

  [5407/20519] intraday_14007.csv.gz  in=277,922,597 out=41,988,768 elapsed=105.4s

  [5408/20519] intraday_14006.csv.gz  in=277,926,794 out=41,992,965 elapsed=105.4s

  [5409/20519] intraday_14008.csv.gz  in=277,942,109 out=42,008,280 elapsed=105.4s

  [5410/20519] intraday_14009.csv.gz  in=277,954,104 out=42,020,275 elapsed=105.5s

  [5411/20519] intraday_14010.csv.gz  in=277,968,037 out=42,034,208 elapsed=105.5s

  [5412/20519] intraday_14011.csv.gz  in=277,979,538 out=42,045,709 elapsed=105.5s

  [5413/20519] intraday_14012.csv.gz  in=277,992,677 out=42,058,848 elapsed=105.5s

  [5414/20519] intraday_1401.csv.gz  in=278,006,433 out=42,058,848 elapsed=105.5s

  [5415/20519] intraday_14013.csv.gz  in=278,016,110 out=42,068,525 elapsed=105.5s

  [5416/20519] intraday_14014.csv.gz  in=278,026,302 out=42,078,717 elapsed=105.5s

  [5417/20519] intraday_14015.csv.gz  in=278,039,190 out=42,090,797 elapsed=105.6s

  [5418/20519] intraday_14016.csv.gz  in=278,051,263 out=42,102,870 elapsed=105.6s

  [5419/20519] intraday_14017.csv.gz  in=278,064,761 out=42,116,368 elapsed=105.6s

  [5420/20519] intraday_14018.csv.gz  in=278,079,972 out=42,131,579 elapsed=105.6s

  [5421/20519] intraday_1402.csv.gz  in=278,092,892 out=42,131,579 elapsed=105.6s

  [5422/20519] intraday_14019.csv.gz  in=278,105,975 out=42,144,662 elapsed=105.6s

  [5423/20519] intraday_14020.csv.gz  in=278,115,375 out=42,154,062 elapsed=105.7s

  [5424/20519] intraday_14022.csv.gz  in=278,118,012 out=42,156,699 elapsed=105.7s

  [5425/20519] intraday_14021.csv.gz  in=278,131,075 out=42,169,762 elapsed=105.7s

  [5426/20519] intraday_14023.csv.gz  in=278,134,200 out=42,172,887 elapsed=105.7s

  [5427/20519] intraday_14024.csv.gz  in=278,145,438 out=42,184,125 elapsed=105.7s

  [5428/20519] intraday_14026.csv.gz  in=278,155,284 out=42,193,971 elapsed=105.7s

  [5429/20519] intraday_14025.csv.gz  in=278,167,458 out=42,206,145 elapsed=105.7s

  [5430/20519] intraday_14028.csv.gz  in=278,179,445 out=42,218,132 elapsed=105.7s

  [5431/20519] intraday_14027.csv.gz  in=278,190,159 out=42,228,846 elapsed=105.8s

  [5432/20519] intraday_1403.csv.gz  in=278,201,244 out=42,228,846 elapsed=105.8s

  [5433/20519] intraday_14029.csv.gz  in=278,215,817 out=42,243,419 elapsed=105.8s

  [5434/20519] intraday_14030.csv.gz  in=278,226,960 out=42,254,562 elapsed=105.8s

  [5435/20519] intraday_14032.csv.gz  in=278,238,847 out=42,266,449 elapsed=105.8s

  [5436/20519] intraday_14031.csv.gz  in=278,253,618 out=42,281,220 elapsed=105.8s

  [5437/20519] intraday_14033.csv.gz  in=278,264,529 out=42,292,131 elapsed=105.8s

  [5438/20519] intraday_14034.csv.gz  in=278,278,080 out=42,305,682 elapsed=105.8s

  [5439/20519] intraday_14035.csv.gz  in=278,288,274 out=42,315,876 elapsed=105.9s

  [5440/20519] intraday_14037.csv.gz  in=278,297,711 out=42,325,313 elapsed=105.9s

  [5441/20519] intraday_14036.csv.gz  in=278,308,444 out=42,336,046 elapsed=105.9s

  [5442/20519] intraday_14039.csv.gz  in=278,320,896 out=42,348,498 elapsed=105.9s

  [5443/20519] intraday_14038.csv.gz  in=278,329,098 out=42,356,700 elapsed=105.9s

  [5444/20519] intraday_1404.csv.gz  in=278,344,370 out=42,356,700 elapsed=105.9s

  [5445/20519] intraday_14040.csv.gz  in=278,355,387 out=42,367,717 elapsed=105.9s

  [5446/20519] intraday_14042.csv.gz  in=278,365,401 out=42,377,731 elapsed=106.0s

  [5447/20519] intraday_14043.csv.gz  in=278,377,102 out=42,389,432 elapsed=106.0s

  [5448/20519] intraday_14041.csv.gz  in=278,388,392 out=42,400,722 elapsed=106.0s

  [5449/20519] intraday_14044.csv.gz  in=278,401,595 out=42,413,925 elapsed=106.0s

  [5450/20519] intraday_14045.csv.gz  in=278,412,687 out=42,425,017 elapsed=106.0s

  [5451/20519] intraday_14046.csv.gz  in=278,425,881 out=42,438,211 elapsed=106.0s

  [5452/20519] intraday_14047.csv.gz  in=278,436,148 out=42,448,478 elapsed=106.0s

  [5453/20519] intraday_14048.csv.gz  in=278,447,149 out=42,459,479 elapsed=106.0s

  [5454/20519] intraday_14051.csv.gz  in=278,451,490 out=42,463,820 elapsed=106.1s

  [5455/20519] intraday_1405.csv.gz  in=278,468,433 out=42,463,820 elapsed=106.1s

  [5456/20519] intraday_14049.csv.gz  in=278,478,960 out=42,474,347 elapsed=106.1s

  [5457/20519] intraday_14050.csv.gz  in=278,493,291 out=42,488,678 elapsed=106.1s

  [5458/20519] intraday_14052.csv.gz  in=278,498,581 out=42,493,968 elapsed=106.1s

  [5459/20519] intraday_14054.csv.gz  in=278,509,464 out=42,504,851 elapsed=106.1s

  [5460/20519] intraday_14053.csv.gz  in=278,520,316 out=42,515,703 elapsed=106.1s

  [5461/20519] intraday_14055.csv.gz  in=278,532,435 out=42,527,822 elapsed=106.2s

  [5462/20519] intraday_14056.csv.gz  in=278,545,639 out=42,541,026 elapsed=106.2s

  [5463/20519] intraday_14057.csv.gz  in=278,557,087 out=42,552,474 elapsed=106.2s

  [5464/20519] intraday_14058.csv.gz  in=278,569,689 out=42,565,076 elapsed=106.2s

  [5465/20519] intraday_14059.csv.gz  in=278,580,254 out=42,575,641 elapsed=106.2s

  [5466/20519] intraday_1406.csv.gz  in=278,596,002 out=42,575,641 elapsed=106.2s

  [5467/20519] intraday_14060.csv.gz  in=278,606,530 out=42,586,169 elapsed=106.2s

  [5468/20519] intraday_14061.csv.gz  in=278,621,265 out=42,600,904 elapsed=106.2s

  [5469/20519] intraday_14062.csv.gz  in=278,632,494 out=42,612,133 elapsed=106.3s

  [5470/20519] intraday_14063.csv.gz  in=278,644,152 out=42,623,791 elapsed=106.3s

  [5471/20519] intraday_14064.csv.gz  in=278,651,578 out=42,631,217 elapsed=106.3s

  [5472/20519] intraday_14065.csv.gz  in=278,653,442 out=42,633,081 elapsed=106.3s

  [5473/20519] intraday_14066.csv.gz  in=278,666,847 out=42,646,486 elapsed=106.3s

  [5474/20519] intraday_14068.csv.gz  in=278,680,121 out=42,659,760 elapsed=106.3s

  [5475/20519] intraday_14069.csv.gz  in=278,691,341 out=42,670,980 elapsed=106.4s

  [5476/20519] intraday_1407.csv.gz  in=278,706,463 out=42,670,980 elapsed=106.4s

  [5477/20519] intraday_14067.csv.gz  in=278,721,634 out=42,686,151 elapsed=106.4s

  [5478/20519] intraday_14070.csv.gz  in=278,732,305 out=42,696,822 elapsed=106.4s

  [5479/20519] intraday_14071.csv.gz  in=278,743,889 out=42,708,406 elapsed=106.4s

  [5480/20519] intraday_14072.csv.gz  in=278,758,092 out=42,722,609 elapsed=106.4s

  [5481/20519] intraday_14073.csv.gz  in=278,770,415 out=42,734,932 elapsed=106.4s

  [5482/20519] intraday_14074.csv.gz  in=278,779,770 out=42,744,287 elapsed=106.4s

  [5483/20519] intraday_14076.csv.gz  in=278,790,693 out=42,755,210 elapsed=106.4s

  [5484/20519] intraday_14077.csv.gz  in=278,802,715 out=42,767,232 elapsed=106.5s

  [5485/20519] intraday_14078.csv.gz  in=278,814,189 out=42,778,706 elapsed=106.5s

  [5486/20519] intraday_14075.csv.gz  in=278,828,957 out=42,793,474 elapsed=106.5s

  [5487/20519] intraday_14079.csv.gz  in=278,840,500 out=42,805,017 elapsed=106.6s

  [5488/20519] intraday_14081.csv.gz  in=278,853,468 out=42,817,985 elapsed=106.6s

  [5489/20519] intraday_1408.csv.gz  in=278,867,060 out=42,817,985 elapsed=106.6s

  [5490/20519] intraday_14080.csv.gz  in=278,878,833 out=42,829,758 elapsed=106.6s

  [5491/20519] intraday_14082.csv.gz  in=278,889,694 out=42,840,619 elapsed=106.6s

  [5492/20519] intraday_14083.csv.gz  in=278,900,676 out=42,851,601 elapsed=106.6s

  [5493/20519] intraday_14084.csv.gz  in=278,914,304 out=42,865,229 elapsed=106.6s

  [5494/20519] intraday_14085.csv.gz  in=278,926,911 out=42,877,836 elapsed=106.7s

  [5495/20519] intraday_14086.csv.gz  in=278,939,200 out=42,890,125 elapsed=106.7s

  [5496/20519] intraday_14087.csv.gz  in=278,950,651 out=42,901,576 elapsed=106.7s

  [5497/20519] intraday_1409.csv.gz  in=278,963,311 out=42,901,576 elapsed=106.7s

  [5498/20519] intraday_14088.csv.gz  in=278,999,012 out=42,922,758 elapsed=106.7s

  [5499/20519] intraday_14089.csv.gz  in=279,014,512 out=42,938,258 elapsed=106.7s

  [5500/20519] intraday_14091.csv.gz  in=279,026,109 out=42,949,855 elapsed=106.7s

  [5501/20519] intraday_14090.csv.gz  in=279,036,653 out=42,960,399 elapsed=106.7s

  [5502/20519] intraday_14092.csv.gz  in=279,049,944 out=42,973,690 elapsed=106.7s

  [5503/20519] intraday_14094.csv.gz  in=279,062,617 out=42,986,363 elapsed=106.7s

  [5504/20519] intraday_14096.csv.gz  in=279,076,525 out=43,000,271 elapsed=106.8s

  [5505/20519] intraday_14095.csv.gz  in=279,090,405 out=43,014,151 elapsed=106.8s

  [5506/20519] intraday_14093.csv.gz  in=279,104,083 out=43,027,829 elapsed=106.8s

  [5507/20519] intraday_14097.csv.gz  in=279,116,619 out=43,040,365 elapsed=106.8s

  [5508/20519] intraday_14098.csv.gz  in=279,129,677 out=43,053,423 elapsed=106.8s

  [5509/20519] intraday_1410.csv.gz  in=279,142,877 out=43,053,423 elapsed=106.8s

  [5510/20519] intraday_14100.csv.gz  in=279,159,103 out=43,069,649 elapsed=106.8s

  [5511/20519] intraday_14099.csv.gz  in=279,175,492 out=43,086,038 elapsed=106.8s

  [5512/20519] intraday_14102.csv.gz  in=279,190,303 out=43,100,849 elapsed=106.9s

  [5513/20519] intraday_14101.csv.gz  in=279,203,752 out=43,114,298 elapsed=106.9s

  [5514/20519] intraday_14103.csv.gz  in=279,214,623 out=43,125,169 elapsed=106.9s

  [5515/20519] intraday_14104.csv.gz  in=279,227,661 out=43,138,207 elapsed=106.9s

  [5516/20519] intraday_14106.csv.gz  in=279,240,549 out=43,151,095 elapsed=106.9s

  [5517/20519] intraday_14105.csv.gz  in=279,250,440 out=43,160,986 elapsed=106.9s

  [5518/20519] intraday_14107.csv.gz  in=279,260,947 out=43,171,493 elapsed=106.9s

  [5519/20519] intraday_14108.csv.gz  in=279,274,118 out=43,184,664 elapsed=106.9s

  [5520/20519] intraday_1411.csv.gz  in=279,287,953 out=43,184,664 elapsed=106.9s

  [5521/20519] intraday_14109.csv.gz  in=279,298,226 out=43,194,937 elapsed=106.9s

  [5522/20519] intraday_14111.csv.gz  in=279,308,153 out=43,204,864 elapsed=107.0s

  [5523/20519] intraday_14110.csv.gz  in=279,324,437 out=43,221,148 elapsed=107.0s

  [5524/20519] intraday_14113.csv.gz  in=279,335,642 out=43,232,353 elapsed=107.0s

  [5525/20519] intraday_14114.csv.gz  in=279,349,239 out=43,245,950 elapsed=107.0s

  [5526/20519] intraday_14112.csv.gz  in=279,361,152 out=43,257,863 elapsed=107.0s

  [5527/20519] intraday_14116.csv.gz  in=279,374,931 out=43,271,642 elapsed=107.0s

  [5528/20519] intraday_14115.csv.gz  in=279,386,197 out=43,282,908 elapsed=107.0s

  [5529/20519] intraday_14117.csv.gz  in=279,401,048 out=43,297,759 elapsed=107.1s

  [5530/20519] intraday_14118.csv.gz  in=279,413,786 out=43,310,497 elapsed=107.1s

  [5531/20519] intraday_1412.csv.gz  in=279,425,790 out=43,310,497 elapsed=107.1s

  [5532/20519] intraday_14121.csv.gz  in=279,436,646 out=43,321,353 elapsed=107.1s

  [5533/20519] intraday_14119.csv.gz  in=279,449,531 out=43,334,238 elapsed=107.1s

  [5534/20519] intraday_14120.csv.gz  in=279,461,663 out=43,346,370 elapsed=107.1s

  [5535/20519] intraday_14122.csv.gz  in=279,473,633 out=43,358,340 elapsed=107.1s

  [5536/20519] intraday_14123.csv.gz  in=279,483,948 out=43,368,655 elapsed=107.1s

  [5537/20519] intraday_14124.csv.gz  in=279,495,956 out=43,380,663 elapsed=107.1s

  [5538/20519] intraday_14126.csv.gz  in=279,503,277 out=43,387,984 elapsed=107.2s

  [5539/20519] intraday_14125.csv.gz  in=279,514,626 out=43,399,333 elapsed=107.2s

  [5540/20519] intraday_14127.csv.gz  in=279,528,195 out=43,412,902 elapsed=107.2s

  [5541/20519] intraday_14128.csv.gz  in=279,544,340 out=43,429,047 elapsed=107.2s

  [5542/20519] intraday_14129.csv.gz  in=279,555,642 out=43,440,349 elapsed=107.2s

  [5543/20519] intraday_1413.csv.gz  in=279,569,384 out=43,440,349 elapsed=107.2s

  [5544/20519] intraday_14130.csv.gz  in=279,582,011 out=43,452,976 elapsed=107.2s

  [5545/20519] intraday_14131.csv.gz  in=279,593,879 out=43,464,844 elapsed=107.2s

  [5546/20519] intraday_14132.csv.gz  in=279,608,355 out=43,477,425 elapsed=107.3s

  [5547/20519] intraday_14133.csv.gz  in=279,622,589 out=43,491,659 elapsed=107.3s

  [5548/20519] intraday_14134.csv.gz  in=279,636,134 out=43,505,204 elapsed=107.3s

  [5549/20519] intraday_14136.csv.gz  in=279,648,605 out=43,517,675 elapsed=107.3s

  [5550/20519] intraday_14137.csv.gz  in=279,660,452 out=43,529,522 elapsed=107.3s

  [5551/20519] intraday_14135.csv.gz  in=279,671,352 out=43,540,422 elapsed=107.4s

  [5552/20519] intraday_14139.csv.gz  in=279,682,674 out=43,551,744 elapsed=107.4s

  [5553/20519] intraday_1414.csv.gz  in=279,695,735 out=43,551,744 elapsed=107.4s

  [5554/20519] intraday_14138.csv.gz  in=279,707,418 out=43,563,427 elapsed=107.4s

  [5555/20519] intraday_14140.csv.gz  in=279,722,587 out=43,576,333 elapsed=107.4s

  [5556/20519] intraday_14143.csv.gz  in=279,728,669 out=43,582,415 elapsed=107.4s

  [5557/20519] intraday_14144.csv.gz  in=279,739,639 out=43,593,385 elapsed=107.5s

  [5558/20519] intraday_14142.csv.gz  in=279,748,645 out=43,602,391 elapsed=107.5s

  [5559/20519] intraday_14145.csv.gz  in=279,759,615 out=43,613,361 elapsed=107.5s

  [5560/20519] intraday_14141.csv.gz  in=279,773,894 out=43,627,640 elapsed=107.5s

  [5561/20519] intraday_14147.csv.gz  in=279,785,320 out=43,639,066 elapsed=107.5s

  [5562/20519] intraday_14146.csv.gz  in=279,799,356 out=43,653,102 elapsed=107.5s

  [5563/20519] intraday_14148.csv.gz  in=279,811,826 out=43,665,572 elapsed=107.6s

  [5564/20519] intraday_14149.csv.gz  in=279,824,177 out=43,677,923 elapsed=107.6s

  [5565/20519] intraday_1415.csv.gz  in=279,836,356 out=43,677,923 elapsed=107.6s

  [5566/20519] intraday_14150.csv.gz  in=279,849,388 out=43,690,955 elapsed=107.6s

  [5567/20519] intraday_14151.csv.gz  in=279,859,141 out=43,700,708 elapsed=107.6s

  [5568/20519] intraday_14152.csv.gz  in=279,869,263 out=43,710,830 elapsed=107.6s

  [5569/20519] intraday_14153.csv.gz  in=279,880,471 out=43,722,038 elapsed=107.6s

  [5570/20519] intraday_14154.csv.gz  in=279,891,120 out=43,732,687 elapsed=107.7s

  [5571/20519] intraday_14155.csv.gz  in=279,905,276 out=43,746,843 elapsed=107.7s

  [5572/20519] intraday_14156.csv.gz  in=279,920,519 out=43,762,086 elapsed=107.7s

  [5573/20519] intraday_14158.csv.gz  in=279,930,239 out=43,771,806 elapsed=107.7s

  [5574/20519] intraday_14157.csv.gz  in=279,943,858 out=43,785,425 elapsed=107.7s

  [5575/20519] intraday_1416.csv.gz  in=279,955,678 out=43,785,425 elapsed=107.7s

  [5576/20519] intraday_14159.csv.gz  in=279,959,356 out=43,789,103 elapsed=107.7s

  [5577/20519] intraday_14160.csv.gz  in=279,961,359 out=43,791,106 elapsed=107.7s

  [5578/20519] intraday_14162.csv.gz  in=279,971,535 out=43,801,189 elapsed=107.8s

  [5579/20519] intraday_14161.csv.gz  in=279,984,003 out=43,813,657 elapsed=107.8s

  [5580/20519] intraday_14163.csv.gz  in=279,995,153 out=43,824,807 elapsed=107.8s

  [5581/20519] intraday_14164.csv.gz  in=280,004,942 out=43,834,596 elapsed=107.8s

  [5582/20519] intraday_14165.csv.gz  in=280,015,200 out=43,844,854 elapsed=107.8s

  [5583/20519] intraday_14166.csv.gz  in=280,027,603 out=43,857,257 elapsed=107.8s

  [5584/20519] intraday_14168.csv.gz  in=280,041,633 out=43,871,287 elapsed=107.9s

  [5585/20519] intraday_14167.csv.gz  in=280,051,848 out=43,881,502 elapsed=107.9s

  [5586/20519] intraday_1417.csv.gz  in=280,065,319 out=43,881,502 elapsed=107.9s

  [5587/20519] intraday_14169.csv.gz  in=280,079,050 out=43,895,233 elapsed=107.9s

  [5588/20519] intraday_14170.csv.gz  in=280,091,453 out=43,907,636 elapsed=107.9s

  [5589/20519] intraday_14171.csv.gz  in=280,103,250 out=43,919,433 elapsed=107.9s

  [5590/20519] intraday_14173.csv.gz  in=280,106,674 out=43,922,857 elapsed=107.9s

  [5591/20519] intraday_14174.csv.gz  in=280,109,991 out=43,926,174 elapsed=107.9s

  [5592/20519] intraday_14172.csv.gz  in=280,122,534 out=43,938,717 elapsed=107.9s

  [5593/20519] intraday_14175.csv.gz  in=280,132,350 out=43,948,533 elapsed=108.0s

  [5594/20519] intraday_14177.csv.gz  in=280,143,612 out=43,959,795 elapsed=108.0s

  [5595/20519] intraday_14178.csv.gz  in=280,153,927 out=43,970,110 elapsed=108.0s

  [5596/20519] intraday_14176.csv.gz  in=280,169,508 out=43,985,691 elapsed=108.0s

  [5597/20519] intraday_14179.csv.gz  in=280,183,859 out=44,000,042 elapsed=108.0s

  [5598/20519] intraday_14180.csv.gz  in=280,195,162 out=44,011,345 elapsed=108.0s

  [5599/20519] intraday_1418.csv.gz  in=280,209,650 out=44,011,345 elapsed=108.0s

  [5600/20519] intraday_14182.csv.gz  in=280,219,971 out=44,021,666 elapsed=108.1s

  [5601/20519] intraday_14181.csv.gz  in=280,231,276 out=44,032,971 elapsed=108.1s

  [5602/20519] intraday_14184.csv.gz  in=280,243,269 out=44,044,964 elapsed=108.1s

  [5603/20519] intraday_14183.csv.gz  in=280,255,082 out=44,056,777 elapsed=108.1s

  [5604/20519] intraday_14186.csv.gz  in=280,264,393 out=44,066,088 elapsed=108.1s

  [5605/20519] intraday_14187.csv.gz  in=280,268,245 out=44,069,940 elapsed=108.1s

  [5606/20519] intraday_14185.csv.gz  in=280,280,753 out=44,082,448 elapsed=108.1s

  [5607/20519] intraday_14188.csv.gz  in=280,286,941 out=44,088,636 elapsed=108.1s

  [5608/20519] intraday_1419.csv.gz  in=280,300,837 out=44,088,636 elapsed=108.1s

  [5609/20519] intraday_14189.csv.gz  in=280,313,922 out=44,101,721 elapsed=108.2s

  [5610/20519] intraday_14190.csv.gz  in=280,326,691 out=44,114,490 elapsed=108.2s

  [5611/20519] intraday_14191.csv.gz  in=280,337,770 out=44,125,569 elapsed=108.2s

  [5612/20519] intraday_14192.csv.gz  in=280,350,375 out=44,138,174 elapsed=108.2s

  [5613/20519] intraday_14193.csv.gz  in=280,359,730 out=44,147,529 elapsed=108.2s

  [5614/20519] intraday_14194.csv.gz  in=280,372,102 out=44,159,901 elapsed=108.2s

  [5615/20519] intraday_14196.csv.gz  in=280,384,695 out=44,172,494 elapsed=108.3s

  [5616/20519] intraday_14195.csv.gz  in=280,397,175 out=44,184,974 elapsed=108.3s

  [5617/20519] intraday_14197.csv.gz  in=280,408,854 out=44,196,653 elapsed=108.3s

  [5618/20519] intraday_14198.csv.gz  in=280,420,886 out=44,208,685 elapsed=108.3s

  [5619/20519] intraday_14199.csv.gz  in=280,430,820 out=44,218,619 elapsed=108.3s

  [5620/20519] intraday_1420.csv.gz  in=280,446,949 out=44,218,619 elapsed=108.3s

  [5621/20519] intraday_14200.csv.gz  in=280,459,893 out=44,231,563 elapsed=108.3s

  [5622/20519] intraday_14202.csv.gz  in=280,471,588 out=44,243,258 elapsed=108.4s

  [5623/20519] intraday_14203.csv.gz  in=280,482,448 out=44,254,118 elapsed=108.4s

  [5624/20519] intraday_14204.csv.gz  in=280,491,602 out=44,263,272 elapsed=108.4s

  [5625/20519] intraday_14201.csv.gz  in=280,504,203 out=44,275,873 elapsed=108.4s

  [5626/20519] intraday_14206.csv.gz  in=280,516,847 out=44,288,517 elapsed=108.4s

  [5627/20519] intraday_14205.csv.gz  in=280,527,165 out=44,298,835 elapsed=108.4s

  [5628/20519] intraday_14207.csv.gz  in=280,542,456 out=44,314,126 elapsed=108.4s

  [5629/20519] intraday_14208.csv.gz  in=280,557,039 out=44,328,709 elapsed=108.4s

  [5630/20519] intraday_14209.csv.gz  in=280,571,616 out=44,343,286 elapsed=108.5s

  [5631/20519] intraday_1421.csv.gz  in=280,583,739 out=44,343,286 elapsed=108.5s

  [5632/20519] intraday_14210.csv.gz  in=280,594,824 out=44,354,371 elapsed=108.5s

  [5633/20519] intraday_14211.csv.gz  in=280,606,999 out=44,366,546 elapsed=108.5s

  [5634/20519] intraday_14212.csv.gz  in=280,617,349 out=44,376,896 elapsed=108.6s

  [5635/20519] intraday_14214.csv.gz  in=280,627,193 out=44,386,740 elapsed=108.6s

  [5636/20519] intraday_14213.csv.gz  in=280,642,402 out=44,401,926 elapsed=108.6s

  [5637/20519] intraday_14215.csv.gz  in=280,654,776 out=44,414,300 elapsed=108.6s

  [5638/20519] intraday_14218.csv.gz  in=280,667,513 out=44,427,037 elapsed=108.7s

  [5639/20519] intraday_14219.csv.gz  in=280,678,409 out=44,437,933 elapsed=108.7s

  [5640/20519] intraday_14217.csv.gz  in=280,689,922 out=44,449,446 elapsed=108.7s

  [5641/20519] intraday_14216.csv.gz  in=280,702,430 out=44,461,954 elapsed=108.7s

  [5642/20519] intraday_1422.csv.gz  in=280,716,219 out=44,461,954 elapsed=108.7s

  [5643/20519] intraday_14220.csv.gz  in=280,728,438 out=44,474,173 elapsed=108.7s

  [5644/20519] intraday_14221.csv.gz  in=280,739,956 out=44,485,691 elapsed=108.7s

  [5645/20519] intraday_14223.csv.gz  in=280,751,571 out=44,497,306 elapsed=108.7s

  [5646/20519] intraday_14222.csv.gz  in=280,762,024 out=44,507,759 elapsed=108.7s

  [5647/20519] intraday_14224.csv.gz  in=280,774,298 out=44,520,033 elapsed=108.7s

  [5648/20519] intraday_14227.csv.gz  in=280,787,890 out=44,532,902 elapsed=108.8s

  [5649/20519] intraday_14225.csv.gz  in=280,800,264 out=44,545,276 elapsed=108.8s

  [5650/20519] intraday_14228.csv.gz  in=280,811,575 out=44,556,587 elapsed=108.8s

  [5651/20519] intraday_14226.csv.gz  in=280,823,837 out=44,568,849 elapsed=108.8s

  [5652/20519] intraday_14229.csv.gz  in=280,835,149 out=44,580,161 elapsed=108.8s

  [5653/20519] intraday_1423.csv.gz  in=280,850,228 out=44,580,161 elapsed=108.8s

  [5654/20519] intraday_14230.csv.gz  in=280,864,816 out=44,594,749 elapsed=108.9s

  [5655/20519] intraday_14231.csv.gz  in=280,876,372 out=44,606,305 elapsed=108.9s

  [5656/20519] intraday_14233.csv.gz  in=280,889,054 out=44,618,987 elapsed=108.9s

  [5657/20519] intraday_14232.csv.gz  in=280,900,483 out=44,630,416 elapsed=108.9s

  [5658/20519] intraday_14234.csv.gz  in=280,914,016 out=44,643,949 elapsed=108.9s

  [5659/20519] intraday_14237.csv.gz  in=280,927,205 out=44,657,138 elapsed=108.9s

  [5660/20519] intraday_14235.csv.gz  in=280,939,473 out=44,669,406 elapsed=108.9s

  [5661/20519] intraday_14236.csv.gz  in=280,953,299 out=44,683,232 elapsed=108.9s

  [5662/20519] intraday_14238.csv.gz  in=280,965,265 out=44,695,198 elapsed=109.0s

  [5663/20519] intraday_14239.csv.gz  in=280,980,834 out=44,710,767 elapsed=109.0s

  [5664/20519] intraday_1424.csv.gz  in=280,994,307 out=44,710,767 elapsed=109.0s

  [5665/20519] intraday_14242.csv.gz  in=281,007,725 out=44,724,185 elapsed=109.0s

  [5666/20519] intraday_14240.csv.gz  in=281,024,734 out=44,741,194 elapsed=109.0s

  [5667/20519] intraday_14243.csv.gz  in=281,036,827 out=44,753,287 elapsed=109.0s

  [5668/20519] intraday_14241.csv.gz  in=281,051,940 out=44,768,400 elapsed=109.0s

  [5669/20519] intraday_14246.csv.gz  in=281,060,821 out=44,777,281 elapsed=109.0s

  [5670/20519] intraday_14244.csv.gz  in=281,073,190 out=44,789,650 elapsed=109.1s

  [5671/20519] intraday_14245.csv.gz  in=281,085,402 out=44,801,862 elapsed=109.1s

  [5672/20519] intraday_14248.csv.gz  in=281,096,522 out=44,812,982 elapsed=109.1s

  [5673/20519] intraday_14249.csv.gz  in=281,108,555 out=44,825,015 elapsed=109.1s

  [5674/20519] intraday_14247.csv.gz  in=281,121,009 out=44,837,469 elapsed=109.1s

  [5675/20519] intraday_1425.csv.gz  in=281,134,529 out=44,837,469 elapsed=109.1s

  [5676/20519] intraday_14250.csv.gz  in=281,147,574 out=44,850,514 elapsed=109.1s

  [5677/20519] intraday_14252.csv.gz  in=281,157,504 out=44,860,444 elapsed=109.2s

  [5678/20519] intraday_14254.csv.gz  in=281,168,485 out=44,871,425 elapsed=109.2s

  [5679/20519] intraday_14251.csv.gz  in=281,181,663 out=44,884,603 elapsed=109.2s

  [5680/20519] intraday_14253.csv.gz  in=281,193,541 out=44,896,481 elapsed=109.2s

  [5681/20519] intraday_14255.csv.gz  in=281,207,931 out=44,910,871 elapsed=109.2s

  [5682/20519] intraday_14256.csv.gz  in=281,220,028 out=44,922,968 elapsed=109.2s

  [5683/20519] intraday_14257.csv.gz  in=281,233,300 out=44,936,240 elapsed=109.2s

  [5684/20519] intraday_14258.csv.gz  in=281,247,374 out=44,950,314 elapsed=109.2s

  [5685/20519] intraday_14259.csv.gz  in=281,259,067 out=44,962,007 elapsed=109.3s

  [5686/20519] intraday_1426.csv.gz  in=281,271,081 out=44,962,007 elapsed=109.3s

  [5687/20519] intraday_14260.csv.gz  in=281,285,268 out=44,976,194 elapsed=109.3s

  [5688/20519] intraday_14263.csv.gz  in=281,296,677 out=44,987,603 elapsed=109.3s

  [5689/20519] intraday_14262.csv.gz  in=281,309,148 out=45,000,074 elapsed=109.3s

  [5690/20519] intraday_14261.csv.gz  in=281,319,129 out=45,010,055 elapsed=109.3s

  [5691/20519] intraday_14264.csv.gz  in=281,329,117 out=45,020,043 elapsed=109.3s

  [5692/20519] intraday_14266.csv.gz  in=281,336,841 out=45,027,767 elapsed=109.3s

  [5693/20519] intraday_14265.csv.gz  in=281,349,446 out=45,040,372 elapsed=109.3s

  [5694/20519] intraday_14268.csv.gz  in=281,359,027 out=45,049,953 elapsed=109.3s

  [5695/20519] intraday_14267.csv.gz  in=281,369,847 out=45,060,773 elapsed=109.3s

  [5696/20519] intraday_14269.csv.gz  in=281,385,596 out=45,076,522 elapsed=109.4s

  [5697/20519] intraday_14270.csv.gz  in=281,397,998 out=45,088,924 elapsed=109.4s

  [5698/20519] intraday_1427.csv.gz  in=281,409,213 out=45,088,924 elapsed=109.4s

  [5699/20519] intraday_14271.csv.gz  in=281,422,242 out=45,101,953 elapsed=109.4s

  [5700/20519] intraday_14272.csv.gz  in=281,431,815 out=45,111,526 elapsed=109.4s

  [5701/20519] intraday_14274.csv.gz  in=281,445,528 out=45,125,239 elapsed=109.4s

  [5702/20519] intraday_14273.csv.gz  in=281,457,274 out=45,136,985 elapsed=109.5s

  [5703/20519] intraday_14275.csv.gz  in=281,471,725 out=45,151,436 elapsed=109.5s

  [5704/20519] intraday_14277.csv.gz  in=281,484,667 out=45,164,378 elapsed=109.5s

  [5705/20519] intraday_14276.csv.gz  in=281,494,202 out=45,173,913 elapsed=109.5s

  [5706/20519] intraday_14279.csv.gz  in=281,505,401 out=45,185,112 elapsed=109.5s

  [5707/20519] intraday_14278.csv.gz  in=281,517,646 out=45,197,357 elapsed=109.5s

  [5708/20519] intraday_1428.csv.gz  in=281,533,735 out=45,197,357 elapsed=109.5s

  [5709/20519] intraday_14283.csv.gz  in=281,542,259 out=45,205,881 elapsed=109.6s

  [5710/20519] intraday_14282.csv.gz  in=281,556,675 out=45,220,297 elapsed=109.6s

  [5711/20519] intraday_14280.csv.gz  in=281,566,904 out=45,230,526 elapsed=109.6s

  [5712/20519] intraday_14281.csv.gz  in=281,578,708 out=45,242,330 elapsed=109.6s

  [5713/20519] intraday_14284.csv.gz  in=281,581,741 out=45,245,363 elapsed=109.6s

  [5714/20519] intraday_14285.csv.gz  in=281,592,418 out=45,256,040 elapsed=109.6s

  [5715/20519] intraday_14286.csv.gz  in=281,603,701 out=45,267,323 elapsed=109.6s

  [5716/20519] intraday_14287.csv.gz  in=281,617,434 out=45,281,056 elapsed=109.7s

  [5717/20519] intraday_14289.csv.gz  in=281,630,169 out=45,293,791 elapsed=109.7s

  [5718/20519] intraday_14288.csv.gz  in=281,640,553 out=45,304,175 elapsed=109.7s

  [5719/20519] intraday_1429.csv.gz  in=281,660,463 out=45,304,175 elapsed=109.7s

  [5720/20519] intraday_14291.csv.gz  in=281,673,446 out=45,317,158 elapsed=109.7s

  [5721/20519] intraday_14293.csv.gz  in=281,683,475 out=45,327,187 elapsed=109.7s

  [5722/20519] intraday_14292.csv.gz  in=281,693,309 out=45,337,021 elapsed=109.7s

  [5723/20519] intraday_14290.csv.gz  in=281,705,465 out=45,349,177 elapsed=109.7s

  [5724/20519] intraday_14294.csv.gz  in=281,717,010 out=45,360,722 elapsed=109.7s

  [5725/20519] intraday_14295.csv.gz  in=281,728,084 out=45,371,796 elapsed=109.7s

  [5726/20519] intraday_14296.csv.gz  in=281,740,704 out=45,384,416 elapsed=109.8s

  [5727/20519] intraday_14297.csv.gz  in=281,757,718 out=45,401,430 elapsed=109.8s

  [5728/20519] intraday_14299.csv.gz  in=281,761,824 out=45,405,536 elapsed=109.8s

  [5729/20519] intraday_14298.csv.gz  in=281,773,922 out=45,417,634 elapsed=109.8s

  [5730/20519] intraday_1430.csv.gz  in=281,786,064 out=45,417,634 elapsed=109.8s

  [5731/20519] intraday_14301.csv.gz  in=281,798,866 out=45,430,436 elapsed=109.8s

  [5732/20519] intraday_14302.csv.gz  in=281,808,145 out=45,439,715 elapsed=109.8s

  [5733/20519] intraday_14300.csv.gz  in=281,819,821 out=45,451,391 elapsed=109.8s

  [5734/20519] intraday_14303.csv.gz  in=281,831,640 out=45,463,210 elapsed=109.8s

  [5735/20519] intraday_14304.csv.gz  in=281,840,530 out=45,472,100 elapsed=109.9s

  [5736/20519] intraday_14306.csv.gz  in=281,852,142 out=45,483,712 elapsed=109.9s

  [5737/20519] intraday_14305.csv.gz  in=281,862,637 out=45,494,207 elapsed=109.9s

  [5738/20519] intraday_14307.csv.gz  in=281,874,382 out=45,505,952 elapsed=109.9s

  [5739/20519] intraday_14309.csv.gz  in=281,888,263 out=45,519,833 elapsed=109.9s

  [5740/20519] intraday_1431.csv.gz  in=281,902,366 out=45,519,833 elapsed=109.9s

  [5741/20519] intraday_14308.csv.gz  in=281,914,922 out=45,532,389 elapsed=109.9s

  [5742/20519] intraday_14310.csv.gz  in=281,926,092 out=45,543,559 elapsed=110.0s

  [5743/20519] intraday_14313.csv.gz  in=281,936,305 out=45,553,772 elapsed=110.0s

  [5744/20519] intraday_14311.csv.gz  in=281,947,821 out=45,565,288 elapsed=110.0s

  [5745/20519] intraday_14314.csv.gz  in=281,958,911 out=45,576,378 elapsed=110.0s

  [5746/20519] intraday_14312.csv.gz  in=281,970,999 out=45,588,466 elapsed=110.0s

  [5747/20519] intraday_14315.csv.gz  in=281,980,610 out=45,598,077 elapsed=110.0s

  [5748/20519] intraday_14316.csv.gz  in=281,989,935 out=45,607,402 elapsed=110.0s

  [5749/20519] intraday_14317.csv.gz  in=281,996,321 out=45,613,788 elapsed=110.0s

  [5750/20519] intraday_1432.csv.gz  in=282,009,349 out=45,613,788 elapsed=110.1s

  [5751/20519] intraday_14320.csv.gz  in=282,019,500 out=45,623,939 elapsed=110.1s

  [5752/20519] intraday_14318.csv.gz  in=282,031,515 out=45,635,954 elapsed=110.1s

  [5753/20519] intraday_14319.csv.gz  in=282,042,290 out=45,646,729 elapsed=110.1s

  [5754/20519] intraday_14322.csv.gz  in=282,055,089 out=45,659,528 elapsed=110.1s

  [5755/20519] intraday_14321.csv.gz  in=282,065,852 out=45,670,291 elapsed=110.1s

  [5756/20519] intraday_14323.csv.gz  in=282,076,973 out=45,681,412 elapsed=110.1s

  [5757/20519] intraday_14324.csv.gz  in=282,088,047 out=45,692,486 elapsed=110.2s

  [5758/20519] intraday_14326.csv.gz  in=282,098,910 out=45,703,349 elapsed=110.2s

  [5759/20519] intraday_14325.csv.gz  in=282,108,810 out=45,713,249 elapsed=110.2s

  [5760/20519] intraday_14327.csv.gz  in=282,117,838 out=45,722,277 elapsed=110.2s

  [5761/20519] intraday_14328.csv.gz  in=282,132,721 out=45,737,160 elapsed=110.2s

  [5762/20519] intraday_14329.csv.gz  in=282,146,614 out=45,750,245 elapsed=110.2s

  [5763/20519] intraday_14330.csv.gz  in=282,159,856 out=45,763,487 elapsed=110.3s

  [5764/20519] intraday_14331.csv.gz  in=282,171,140 out=45,774,771 elapsed=110.3s

  [5765/20519] intraday_1433.csv.gz  in=282,182,782 out=45,774,771 elapsed=110.3s

  [5766/20519] intraday_14333.csv.gz  in=282,184,192 out=45,776,181 elapsed=110.3s

  [5767/20519] intraday_14332.csv.gz  in=282,195,181 out=45,787,170 elapsed=110.3s

  [5768/20519] intraday_14334.csv.gz  in=282,199,097 out=45,791,086 elapsed=110.3s

  [5769/20519] intraday_14335.csv.gz  in=282,210,602 out=45,802,591 elapsed=110.3s

  [5770/20519] intraday_14336.csv.gz  in=282,222,398 out=45,814,387 elapsed=110.3s

  [5771/20519] intraday_14337.csv.gz  in=282,234,000 out=45,825,989 elapsed=110.3s

  [5772/20519] intraday_14338.csv.gz  in=282,243,053 out=45,835,042 elapsed=110.3s

  [5773/20519] intraday_14339.csv.gz  in=282,257,651 out=45,849,640 elapsed=110.4s

  [5774/20519] intraday_1434.csv.gz  in=282,271,906 out=45,849,640 elapsed=110.4s

  [5775/20519] intraday_14340.csv.gz  in=282,282,194 out=45,859,928 elapsed=110.4s

  [5776/20519] intraday_14343.csv.gz  in=282,292,179 out=45,869,913 elapsed=110.4s

  [5777/20519] intraday_14341.csv.gz  in=282,304,590 out=45,882,324 elapsed=110.4s

  [5778/20519] intraday_14344.csv.gz  in=282,316,245 out=45,893,979 elapsed=110.4s

  [5779/20519] intraday_14342.csv.gz  in=282,326,400 out=45,904,134 elapsed=110.4s

  [5780/20519] intraday_14345.csv.gz  in=282,339,651 out=45,917,385 elapsed=110.4s

  [5781/20519] intraday_14348.csv.gz  in=282,352,748 out=45,930,482 elapsed=110.5s

  [5782/20519] intraday_14347.csv.gz  in=282,364,484 out=45,942,218 elapsed=110.5s

  [5783/20519] intraday_14346.csv.gz  in=282,382,461 out=45,960,195 elapsed=110.5s

  [5784/20519] intraday_14349.csv.gz  in=282,393,184 out=45,970,918 elapsed=110.5s

  [5785/20519] intraday_1435.csv.gz  in=282,406,938 out=45,970,918 elapsed=110.5s

  [5786/20519] intraday_14351.csv.gz  in=282,420,547 out=45,984,527 elapsed=110.5s

  [5787/20519] intraday_14350.csv.gz  in=282,432,388 out=45,996,368 elapsed=110.6s

  [5788/20519] intraday_14352.csv.gz  in=282,446,658 out=46,010,638 elapsed=110.6s

  [5789/20519] intraday_14355.csv.gz  in=282,457,624 out=46,021,604 elapsed=110.6s

  [5790/20519] intraday_14353.csv.gz  in=282,467,424 out=46,031,404 elapsed=110.6s

  [5791/20519] intraday_14354.csv.gz  in=282,482,580 out=46,046,560 elapsed=110.6s

  [5792/20519] intraday_14356.csv.gz  in=282,490,703 out=46,054,683 elapsed=110.7s

  [5793/20519] intraday_14358.csv.gz  in=282,503,289 out=46,067,269 elapsed=110.7s

  [5794/20519] intraday_14357.csv.gz  in=282,503,330 out=46,067,310 elapsed=110.7s

  [5795/20519] intraday_14359.csv.gz  in=282,513,602 out=46,077,582 elapsed=110.7s

  [5796/20519] intraday_1436.csv.gz  in=282,525,525 out=46,077,582 elapsed=110.7s

  [5797/20519] intraday_14361.csv.gz  in=282,536,458 out=46,088,515 elapsed=110.7s

  [5798/20519] intraday_14362.csv.gz  in=282,549,832 out=46,101,889 elapsed=110.7s

  [5799/20519] intraday_14363.csv.gz  in=282,563,227 out=46,115,284 elapsed=110.7s

  [5800/20519] intraday_14360.csv.gz  in=282,574,821 out=46,126,878 elapsed=110.7s

  [5801/20519] intraday_14364.csv.gz  in=282,586,288 out=46,138,345 elapsed=110.8s

  [5802/20519] intraday_14365.csv.gz  in=282,597,753 out=46,149,810 elapsed=110.8s

  [5803/20519] intraday_14366.csv.gz  in=282,607,927 out=46,159,984 elapsed=110.8s

  [5804/20519] intraday_14367.csv.gz  in=282,622,881 out=46,174,938 elapsed=110.8s

  [5805/20519] intraday_14368.csv.gz  in=282,632,851 out=46,184,908 elapsed=110.8s

  [5806/20519] intraday_1437.csv.gz  in=282,647,561 out=46,184,908 elapsed=110.8s

  [5807/20519] intraday_14369.csv.gz  in=282,658,980 out=46,196,327 elapsed=110.8s

  [5808/20519] intraday_14370.csv.gz  in=282,671,737 out=46,209,084 elapsed=110.8s

  [5809/20519] intraday_14371.csv.gz  in=282,686,317 out=46,223,664 elapsed=110.8s

  [5810/20519] intraday_14372.csv.gz  in=282,698,189 out=46,235,536 elapsed=110.8s

  [5811/20519] intraday_14373.csv.gz  in=282,709,979 out=46,247,326 elapsed=110.9s

  [5812/20519] intraday_14375.csv.gz  in=282,722,284 out=46,259,631 elapsed=110.9s

  [5813/20519] intraday_14374.csv.gz  in=282,734,804 out=46,272,151 elapsed=110.9s

  [5814/20519] intraday_14376.csv.gz  in=282,749,495 out=46,286,842 elapsed=110.9s

  [5815/20519] intraday_14377.csv.gz  in=282,764,590 out=46,301,937 elapsed=110.9s

  [5816/20519] intraday_14378.csv.gz  in=282,784,298 out=46,321,645 elapsed=110.9s

  [5817/20519] intraday_1438.csv.gz  in=282,797,208 out=46,321,645 elapsed=110.9s

  [5818/20519] intraday_14379.csv.gz  in=282,807,712 out=46,332,149 elapsed=111.0s

  [5819/20519] intraday_14380.csv.gz  in=282,823,133 out=46,347,570 elapsed=111.0s

  [5820/20519] intraday_14381.csv.gz  in=282,833,094 out=46,357,531 elapsed=111.0s

  [5821/20519] intraday_14382.csv.gz  in=282,846,103 out=46,370,540 elapsed=111.0s

  [5822/20519] intraday_14383.csv.gz  in=282,856,502 out=46,380,939 elapsed=111.0s

  [5823/20519] intraday_14384.csv.gz  in=282,868,544 out=46,392,981 elapsed=111.0s

  [5824/20519] intraday_14386.csv.gz  in=282,881,283 out=46,405,720 elapsed=111.1s

  [5825/20519] intraday_14385.csv.gz  in=282,891,267 out=46,415,704 elapsed=111.1s

  [5826/20519] intraday_14387.csv.gz  in=282,901,362 out=46,425,799 elapsed=111.1s

  [5827/20519] intraday_14388.csv.gz  in=282,917,970 out=46,442,407 elapsed=111.1s

  [5828/20519] intraday_14389.csv.gz  in=282,926,788 out=46,451,225 elapsed=111.1s

  [5829/20519] intraday_1439.csv.gz  in=282,936,795 out=46,451,225 elapsed=111.1s

  [5830/20519] intraday_14390.csv.gz  in=282,948,560 out=46,462,990 elapsed=111.1s

  [5831/20519] intraday_14391.csv.gz  in=282,959,431 out=46,473,861 elapsed=111.1s

  [5832/20519] intraday_14392.csv.gz  in=282,972,940 out=46,487,370 elapsed=111.2s

  [5833/20519] intraday_14394.csv.gz  in=282,990,974 out=46,504,342 elapsed=111.2s

  [5834/20519] intraday_14395.csv.gz  in=283,004,752 out=46,518,120 elapsed=111.2s

  [5835/20519] intraday_14393.csv.gz  in=283,015,031 out=46,528,399 elapsed=111.2s

  [5836/20519] intraday_14396.csv.gz  in=283,028,235 out=46,541,603 elapsed=111.2s

  [5837/20519] intraday_14397.csv.gz  in=283,041,941 out=46,555,309 elapsed=111.2s

  [5838/20519] intraday_14398.csv.gz  in=283,053,644 out=46,567,012 elapsed=111.2s

  [5839/20519] intraday_14399.csv.gz  in=283,064,072 out=46,577,440 elapsed=111.2s

  [5840/20519] intraday_14400.csv.gz  in=283,076,852 out=46,590,220 elapsed=111.2s

  [5841/20519] intraday_1440.csv.gz  in=283,090,766 out=46,590,220 elapsed=111.2s

  [5842/20519] intraday_14401.csv.gz  in=283,100,360 out=46,599,814 elapsed=111.3s

  [5843/20519] intraday_14402.csv.gz  in=283,113,089 out=46,612,543 elapsed=111.3s

  [5844/20519] intraday_14404.csv.gz  in=283,120,431 out=46,619,885 elapsed=111.3s

  [5845/20519] intraday_14403.csv.gz  in=283,130,883 out=46,630,337 elapsed=111.3s

  [5846/20519] intraday_14405.csv.gz  in=283,145,234 out=46,644,688 elapsed=111.3s

  [5847/20519] intraday_14406.csv.gz  in=283,145,915 out=46,645,369 elapsed=111.3s

  [5848/20519] intraday_14408.csv.gz  in=283,157,427 out=46,656,881 elapsed=111.3s

  [5849/20519] intraday_1441.csv.gz  in=283,171,965 out=46,656,881 elapsed=111.3s

  [5850/20519] intraday_14407.csv.gz  in=283,187,961 out=46,672,877 elapsed=111.3s

  [5851/20519] intraday_14409.csv.gz  in=283,201,213 out=46,686,129 elapsed=111.3s

  [5852/20519] intraday_14411.csv.gz  in=283,212,701 out=46,697,617 elapsed=111.3s

  [5853/20519] intraday_14410.csv.gz  in=283,223,823 out=46,708,739 elapsed=111.3s

  [5854/20519] intraday_14413.csv.gz  in=283,235,870 out=46,720,786 elapsed=111.3s

  [5855/20519] intraday_14412.csv.gz  in=283,250,747 out=46,735,663 elapsed=111.3s

  [5856/20519] intraday_14414.csv.gz  in=283,261,942 out=46,746,858 elapsed=111.3s

  [5857/20519] intraday_14415.csv.gz  in=283,274,483 out=46,759,399 elapsed=111.3s

  [5858/20519] intraday_14417.csv.gz  in=283,285,292 out=46,770,208 elapsed=111.3s

  [5859/20519] intraday_14416.csv.gz  in=283,298,195 out=46,783,111 elapsed=111.4s

  [5860/20519] intraday_14418.csv.gz  in=283,309,394 out=46,794,310 elapsed=111.4s

  [5861/20519] intraday_14419.csv.gz  in=283,321,313 out=46,806,229 elapsed=111.4s

  [5862/20519] intraday_14420.csv.gz  in=283,322,107 out=46,807,023 elapsed=111.4s

  [5863/20519] intraday_1442.csv.gz  in=283,333,527 out=46,807,023 elapsed=111.4s

  [5864/20519] intraday_14421.csv.gz  in=283,346,756 out=46,820,252 elapsed=111.4s

  [5865/20519] intraday_14424.csv.gz  in=283,358,329 out=46,831,825 elapsed=111.4s

  [5866/20519] intraday_14423.csv.gz  in=283,368,200 out=46,841,696 elapsed=111.4s

  [5867/20519] intraday_14422.csv.gz  in=283,382,057 out=46,855,553 elapsed=111.4s

  [5868/20519] intraday_14428.csv.gz  in=283,393,517 out=46,867,013 elapsed=111.5s

  [5869/20519] intraday_14425.csv.gz  in=283,407,752 out=46,881,248 elapsed=111.5s

  [5870/20519] intraday_14426.csv.gz  in=283,419,209 out=46,892,705 elapsed=111.5s

  [5871/20519] intraday_14427.csv.gz  in=283,433,256 out=46,906,752 elapsed=111.5s

  [5872/20519] intraday_14429.csv.gz  in=283,447,062 out=46,920,558 elapsed=111.5s

  [5873/20519] intraday_14432.csv.gz  in=283,455,049 out=46,928,545 elapsed=111.5s

  [5874/20519] intraday_14431.csv.gz  in=283,465,920 out=46,939,416 elapsed=111.6s

  [5875/20519] intraday_1443.csv.gz  in=283,480,879 out=46,939,416 elapsed=111.6s

  [5876/20519] intraday_14430.csv.gz  in=283,492,837 out=46,951,374 elapsed=111.6s

  [5877/20519] intraday_14433.csv.gz  in=283,497,769 out=46,956,306 elapsed=111.6s

  [5878/20519] intraday_14435.csv.gz  in=283,506,919 out=46,965,456 elapsed=111.6s

  [5879/20519] intraday_14434.csv.gz  in=283,519,946 out=46,978,483 elapsed=111.6s

  [5880/20519] intraday_14436.csv.gz  in=283,532,575 out=46,991,112 elapsed=111.6s

  [5881/20519] intraday_14437.csv.gz  in=283,545,008 out=47,003,545 elapsed=111.6s

  [5882/20519] intraday_14439.csv.gz  in=283,557,495 out=47,016,032 elapsed=111.7s

  [5883/20519] intraday_14438.csv.gz  in=283,570,379 out=47,028,916 elapsed=111.7s

  [5884/20519] intraday_14440.csv.gz  in=283,580,212 out=47,038,749 elapsed=111.7s

  [5885/20519] intraday_1444.csv.gz  in=283,594,323 out=47,038,749 elapsed=111.7s

  [5886/20519] intraday_14441.csv.gz  in=283,605,044 out=47,049,470 elapsed=111.7s

  [5887/20519] intraday_14442.csv.gz  in=283,613,952 out=47,058,378 elapsed=111.7s

  [5888/20519] intraday_14443.csv.gz  in=283,624,182 out=47,068,608 elapsed=111.8s

  [5889/20519] intraday_14444.csv.gz  in=283,636,478 out=47,080,904 elapsed=111.8s

  [5890/20519] intraday_14445.csv.gz  in=283,643,704 out=47,088,130 elapsed=111.8s

  [5891/20519] intraday_14446.csv.gz  in=283,650,103 out=47,094,529 elapsed=111.8s

  [5892/20519] intraday_14448.csv.gz  in=283,661,634 out=47,106,060 elapsed=111.8s

  [5893/20519] intraday_14447.csv.gz  in=283,673,684 out=47,118,110 elapsed=111.8s

  [5894/20519] intraday_14449.csv.gz  in=283,684,903 out=47,129,329 elapsed=111.8s

  [5895/20519] intraday_1445.csv.gz  in=283,695,594 out=47,129,329 elapsed=111.8s

  [5896/20519] intraday_14450.csv.gz  in=283,706,939 out=47,140,674 elapsed=111.8s

  [5897/20519] intraday_14451.csv.gz  in=283,716,926 out=47,150,661 elapsed=111.8s

  [5898/20519] intraday_14453.csv.gz  in=283,729,246 out=47,162,981 elapsed=111.9s

  [5899/20519] intraday_14455.csv.gz  in=283,741,701 out=47,175,436 elapsed=111.9s

  [5900/20519] intraday_14452.csv.gz  in=283,754,032 out=47,187,767 elapsed=111.9s

  [5901/20519] intraday_14454.csv.gz  in=283,766,487 out=47,200,222 elapsed=111.9s

  [5902/20519] intraday_14456.csv.gz  in=283,777,859 out=47,211,594 elapsed=111.9s

  [5903/20519] intraday_14458.csv.gz  in=283,787,590 out=47,221,325 elapsed=111.9s

  [5904/20519] intraday_14457.csv.gz  in=283,799,222 out=47,232,957 elapsed=112.0s

  [5905/20519] intraday_14459.csv.gz  in=283,810,962 out=47,244,697 elapsed=112.0s

  [5906/20519] intraday_14460.csv.gz  in=283,817,293 out=47,251,028 elapsed=112.0s

  [5907/20519] intraday_1446.csv.gz  in=283,829,913 out=47,251,028 elapsed=112.0s

  [5908/20519] intraday_14461.csv.gz  in=283,840,403 out=47,261,518 elapsed=112.0s

  [5909/20519] intraday_14462.csv.gz  in=283,850,729 out=47,271,844 elapsed=112.0s

  [5910/20519] intraday_14464.csv.gz  in=283,865,130 out=47,286,245 elapsed=112.1s

  [5911/20519] intraday_14463.csv.gz  in=283,875,134 out=47,296,249 elapsed=112.1s

  [5912/20519] intraday_14465.csv.gz  in=283,888,803 out=47,309,918 elapsed=112.1s

  [5913/20519] intraday_14466.csv.gz  in=283,901,260 out=47,322,375 elapsed=112.1s

  [5914/20519] intraday_14468.csv.gz  in=283,910,579 out=47,331,694 elapsed=112.1s

  [5915/20519] intraday_14467.csv.gz  in=283,923,718 out=47,344,833 elapsed=112.1s

  [5916/20519] intraday_1447.csv.gz  in=283,936,684 out=47,344,833 elapsed=112.1s

  [5917/20519] intraday_14469.csv.gz  in=283,947,950 out=47,356,099 elapsed=112.1s

  [5918/20519] intraday_14470.csv.gz  in=283,960,495 out=47,368,644 elapsed=112.1s

  [5919/20519] intraday_14473.csv.gz  in=283,963,704 out=47,371,853 elapsed=112.1s

  [5920/20519] intraday_14472.csv.gz  in=283,975,771 out=47,383,920 elapsed=112.2s

  [5921/20519] intraday_14471.csv.gz  in=283,986,817 out=47,394,966 elapsed=112.2s

  [5922/20519] intraday_14474.csv.gz  in=283,990,050 out=47,398,199 elapsed=112.2s

  [5923/20519] intraday_14475.csv.gz  in=284,003,748 out=47,411,897 elapsed=112.2s

  [5924/20519] intraday_14476.csv.gz  in=284,015,770 out=47,423,919 elapsed=112.2s

  [5925/20519] intraday_14477.csv.gz  in=284,028,811 out=47,436,960 elapsed=112.2s

  [5926/20519] intraday_14479.csv.gz  in=284,038,931 out=47,447,080 elapsed=112.3s

  [5927/20519] intraday_14478.csv.gz  in=284,049,203 out=47,457,352 elapsed=112.3s

  [5928/20519] intraday_1448.csv.gz  in=284,063,228 out=47,457,352 elapsed=112.3s

  [5929/20519] intraday_14480.csv.gz  in=284,076,326 out=47,470,450 elapsed=112.3s

  [5930/20519] intraday_14482.csv.gz  in=284,090,373 out=47,484,497 elapsed=112.3s

  [5931/20519] intraday_14481.csv.gz  in=284,106,173 out=47,500,297 elapsed=112.3s

  [5932/20519] intraday_14483.csv.gz  in=284,120,649 out=47,514,773 elapsed=112.3s

  [5933/20519] intraday_14484.csv.gz  in=284,138,098 out=47,531,495 elapsed=112.3s

  [5934/20519] intraday_14485.csv.gz  in=284,149,594 out=47,542,991 elapsed=112.3s

  [5935/20519] intraday_14486.csv.gz  in=284,161,837 out=47,554,996 elapsed=112.4s

  [5936/20519] intraday_14488.csv.gz  in=284,173,178 out=47,566,337 elapsed=112.4s

  [5937/20519] intraday_14487.csv.gz  in=284,190,378 out=47,583,537 elapsed=112.4s

  [5938/20519] intraday_1449.csv.gz  in=284,201,976 out=47,583,537 elapsed=112.4s

  [5939/20519] intraday_14489.csv.gz  in=284,212,910 out=47,594,471 elapsed=112.4s

  [5940/20519] intraday_14491.csv.gz  in=284,219,215 out=47,600,776 elapsed=112.4s

  [5941/20519] intraday_14492.csv.gz  in=284,219,374 out=47,600,935 elapsed=112.4s

  [5942/20519] intraday_14490.csv.gz  in=284,233,786 out=47,615,347 elapsed=112.5s

  [5943/20519] intraday_14495.csv.gz  in=284,245,736 out=47,627,297 elapsed=112.5s

  [5944/20519] intraday_14493.csv.gz  in=284,256,715 out=47,638,276 elapsed=112.5s

  [5945/20519] intraday_14494.csv.gz  in=284,268,601 out=47,650,162 elapsed=112.5s

  [5946/20519] intraday_14496.csv.gz  in=284,279,023 out=47,660,584 elapsed=112.5s

  [5947/20519] intraday_14497.csv.gz  in=284,290,949 out=47,672,510 elapsed=112.5s

  [5948/20519] intraday_14498.csv.gz  in=284,304,532 out=47,686,093 elapsed=112.5s

  [5949/20519] intraday_14499.csv.gz  in=284,318,167 out=47,699,728 elapsed=112.5s

  [5950/20519] intraday_1450.csv.gz  in=284,337,401 out=47,699,728 elapsed=112.5s

  [5951/20519] intraday_14500.csv.gz  in=284,349,247 out=47,711,574 elapsed=112.6s

  [5952/20519] intraday_14501.csv.gz  in=284,360,747 out=47,723,074 elapsed=112.6s

  [5953/20519] intraday_14502.csv.gz  in=284,371,252 out=47,733,579 elapsed=112.6s

  [5954/20519] intraday_14503.csv.gz  in=284,386,406 out=47,748,733 elapsed=112.6s

  [5955/20519] intraday_14504.csv.gz  in=284,396,043 out=47,758,370 elapsed=112.6s

  [5956/20519] intraday_14505.csv.gz  in=284,407,015 out=47,769,342 elapsed=112.6s

  [5957/20519] intraday_14508.csv.gz  in=284,417,244 out=47,779,571 elapsed=112.6s

  [5958/20519] intraday_14507.csv.gz  in=284,432,084 out=47,794,411 elapsed=112.7s

  [5959/20519] intraday_14506.csv.gz  in=284,445,748 out=47,808,075 elapsed=112.7s

  [5960/20519] intraday_1451.csv.gz  in=284,458,115 out=47,808,075 elapsed=112.7s

  [5961/20519] intraday_14509.csv.gz  in=284,477,805 out=47,826,013 elapsed=112.7s

  [5962/20519] intraday_14510.csv.gz  in=284,489,849 out=47,838,057 elapsed=112.7s

  [5963/20519] intraday_14512.csv.gz  in=284,503,592 out=47,851,800 elapsed=112.7s

  [5964/20519] intraday_14511.csv.gz  in=284,517,203 out=47,865,411 elapsed=112.7s

  [5965/20519] intraday_14513.csv.gz  in=284,534,650 out=47,882,858 elapsed=112.8s

  [5966/20519] intraday_14514.csv.gz  in=284,552,117 out=47,900,325 elapsed=112.8s

  [5967/20519] intraday_14515.csv.gz  in=284,565,547 out=47,913,755 elapsed=112.8s

  [5968/20519] intraday_14517.csv.gz  in=284,576,469 out=47,924,677 elapsed=112.8s

  [5969/20519] intraday_14516.csv.gz  in=284,589,513 out=47,937,721 elapsed=112.8s

  [5970/20519] intraday_14518.csv.gz  in=284,601,893 out=47,950,101 elapsed=112.8s

  [5971/20519] intraday_14519.csv.gz  in=284,611,216 out=47,959,424 elapsed=112.8s

  [5972/20519] intraday_1452.csv.gz  in=284,623,688 out=47,959,424 elapsed=112.8s

  [5973/20519] intraday_14520.csv.gz  in=284,636,862 out=47,972,598 elapsed=112.8s

  [5974/20519] intraday_14522.csv.gz  in=284,647,886 out=47,983,616 elapsed=112.9s

  [5975/20519] intraday_14521.csv.gz  in=284,657,997 out=47,993,727 elapsed=112.9s

  [5976/20519] intraday_14524.csv.gz  in=284,671,794 out=48,007,524 elapsed=112.9s

  [5977/20519] intraday_14523.csv.gz  in=284,684,011 out=48,019,741 elapsed=112.9s

  [5978/20519] intraday_14526.csv.gz  in=284,694,195 out=48,029,925 elapsed=112.9s

  [5979/20519] intraday_14525.csv.gz  in=284,705,082 out=48,040,812 elapsed=112.9s

  [5980/20519] intraday_14527.csv.gz  in=284,716,864 out=48,052,594 elapsed=112.9s

  [5981/20519] intraday_14528.csv.gz  in=284,730,048 out=48,065,778 elapsed=112.9s

  [5982/20519] intraday_1453.csv.gz  in=284,742,551 out=48,065,778 elapsed=112.9s

  [5983/20519] intraday_14529.csv.gz  in=284,754,171 out=48,077,398 elapsed=112.9s

  [5984/20519] intraday_14530.csv.gz  in=284,767,835 out=48,091,062 elapsed=113.0s

  [5985/20519] intraday_14531.csv.gz  in=284,781,446 out=48,104,673 elapsed=113.0s

  [5986/20519] intraday_14533.csv.gz  in=284,796,873 out=48,120,100 elapsed=113.0s

  [5987/20519] intraday_14532.csv.gz  in=284,810,045 out=48,133,272 elapsed=113.0s

  [5988/20519] intraday_14534.csv.gz  in=284,820,542 out=48,143,769 elapsed=113.0s

  [5989/20519] intraday_14535.csv.gz  in=284,834,170 out=48,157,397 elapsed=113.0s

  [5990/20519] intraday_14537.csv.gz  in=284,844,630 out=48,167,857 elapsed=113.0s

  [5991/20519] intraday_14536.csv.gz  in=284,858,085 out=48,181,312 elapsed=113.0s

  [5992/20519] intraday_14538.csv.gz  in=284,870,486 out=48,193,713 elapsed=113.0s

  [5993/20519] intraday_14539.csv.gz  in=284,879,362 out=48,202,589 elapsed=113.0s

  [5994/20519] intraday_1454.csv.gz  in=284,892,106 out=48,202,589 elapsed=113.0s

  [5995/20519] intraday_14541.csv.gz  in=284,900,833 out=48,211,316 elapsed=113.1s

  [5996/20519] intraday_14543.csv.gz  in=284,912,290 out=48,222,773 elapsed=113.1s

  [5997/20519] intraday_14540.csv.gz  in=284,923,894 out=48,234,377 elapsed=113.1s

  [5998/20519] intraday_14542.csv.gz  in=284,938,390 out=48,248,873 elapsed=113.1s

  [5999/20519] intraday_14545.csv.gz  in=284,949,504 out=48,259,987 elapsed=113.1s

  [6000/20519] intraday_14546.csv.gz  in=284,960,767 out=48,271,250 elapsed=113.1s

  [6001/20519] intraday_14544.csv.gz  in=284,975,380 out=48,285,857 elapsed=113.2s

  [6002/20519] intraday_14547.csv.gz  in=284,987,842 out=48,298,319 elapsed=113.2s

  [6003/20519] intraday_14548.csv.gz  in=285,000,327 out=48,310,804 elapsed=113.2s

  [6004/20519] intraday_1455.csv.gz  in=285,012,568 out=48,310,804 elapsed=113.2s

  [6005/20519] intraday_14549.csv.gz  in=285,024,169 out=48,322,405 elapsed=113.2s

  [6006/20519] intraday_14551.csv.gz  in=285,036,338 out=48,334,574 elapsed=113.2s

  [6007/20519] intraday_14553.csv.gz  in=285,046,673 out=48,344,909 elapsed=113.2s

  [6008/20519] intraday_14550.csv.gz  in=285,059,805 out=48,358,041 elapsed=113.2s

  [6009/20519] intraday_14554.csv.gz  in=285,071,027 out=48,369,263 elapsed=113.2s

  [6010/20519] intraday_14552.csv.gz  in=285,081,197 out=48,379,433 elapsed=113.3s

  [6011/20519] intraday_14555.csv.gz  in=285,082,363 out=48,380,599 elapsed=113.3s

  [6012/20519] intraday_14556.csv.gz  in=285,090,704 out=48,388,940 elapsed=113.3s

  [6013/20519] intraday_14557.csv.gz  in=285,108,670 out=48,404,384 elapsed=113.3s

  [6014/20519] intraday_14558.csv.gz  in=285,118,644 out=48,414,358 elapsed=113.3s

  [6015/20519] intraday_1456.csv.gz  in=285,129,752 out=48,414,358 elapsed=113.3s

  [6016/20519] intraday_14559.csv.gz  in=285,140,022 out=48,424,628 elapsed=113.3s

  [6017/20519] intraday_14560.csv.gz  in=285,154,573 out=48,439,179 elapsed=113.3s

  [6018/20519] intraday_14563.csv.gz  in=285,166,490 out=48,451,096 elapsed=113.4s

  [6019/20519] intraday_14562.csv.gz  in=285,178,718 out=48,463,324 elapsed=113.4s

  [6020/20519] intraday_14561.csv.gz  in=285,190,206 out=48,474,812 elapsed=113.4s

  [6021/20519] intraday_14564.csv.gz  in=285,203,232 out=48,487,838 elapsed=113.4s

  [6022/20519] intraday_14565.csv.gz  in=285,216,081 out=48,500,687 elapsed=113.4s

  [6023/20519] intraday_14566.csv.gz  in=285,225,882 out=48,510,488 elapsed=113.4s

  [6024/20519] intraday_14567.csv.gz  in=285,237,589 out=48,522,195 elapsed=113.4s

  [6025/20519] intraday_14568.csv.gz  in=285,247,925 out=48,532,531 elapsed=113.4s

  [6026/20519] intraday_14569.csv.gz  in=285,260,621 out=48,545,227 elapsed=113.4s

  [6027/20519] intraday_1457.csv.gz  in=285,273,184 out=48,545,227 elapsed=113.4s

  [6028/20519] intraday_14571.csv.gz  in=285,273,232 out=48,545,275 elapsed=113.4s

  [6029/20519] intraday_14570.csv.gz  in=285,285,100 out=48,557,143 elapsed=113.5s

  [6030/20519] intraday_14574.csv.gz  in=285,296,695 out=48,568,738 elapsed=113.5s

  [6031/20519] intraday_14573.csv.gz  in=285,308,729 out=48,580,772 elapsed=113.5s

  [6032/20519] intraday_14575.csv.gz  in=285,318,142 out=48,590,185 elapsed=113.5s

  [6033/20519] intraday_14572.csv.gz  in=285,335,313 out=48,604,032 elapsed=113.5s

  [6034/20519] intraday_14576.csv.gz  in=285,347,419 out=48,616,138 elapsed=113.5s

  [6035/20519] intraday_14577.csv.gz  in=285,355,692 out=48,624,346 elapsed=113.5s

  [6036/20519] intraday_14578.csv.gz  in=285,365,999 out=48,634,653 elapsed=113.5s

  [6037/20519] intraday_1458.csv.gz  in=285,378,881 out=48,634,653 elapsed=113.6s

  [6038/20519] intraday_14579.csv.gz  in=285,391,308 out=48,647,080 elapsed=113.6s

  [6039/20519] intraday_14581.csv.gz  in=285,403,838 out=48,659,610 elapsed=113.6s

  [6040/20519] intraday_14580.csv.gz  in=285,416,008 out=48,671,780 elapsed=113.6s

  [6041/20519] intraday_14584.csv.gz  in=285,422,943 out=48,678,715 elapsed=113.7s

  [6042/20519] intraday_14583.csv.gz  in=285,446,374 out=48,694,942 elapsed=113.7s

  [6043/20519] intraday_14585.csv.gz  in=285,448,558 out=48,697,126 elapsed=113.7s

  [6044/20519] intraday_14582.csv.gz  in=285,463,181 out=48,711,749 elapsed=113.7s

  [6045/20519] intraday_14586.csv.gz  in=285,473,297 out=48,721,865 elapsed=113.7s

  [6046/20519] intraday_14587.csv.gz  in=285,485,400 out=48,733,968 elapsed=113.7s

  [6047/20519] intraday_14588.csv.gz  in=285,500,150 out=48,748,529 elapsed=113.7s

  [6048/20519] intraday_14589.csv.gz  in=285,511,604 out=48,759,983 elapsed=113.7s

  [6049/20519] intraday_1459.csv.gz  in=285,528,660 out=48,759,983 elapsed=113.8s

  [6050/20519] intraday_14590.csv.gz  in=285,539,499 out=48,770,822 elapsed=113.8s

  [6051/20519] intraday_14592.csv.gz  in=285,551,036 out=48,782,359 elapsed=113.8s

  [6052/20519] intraday_14593.csv.gz  in=285,560,419 out=48,791,742 elapsed=113.8s

  [6053/20519] intraday_14591.csv.gz  in=285,572,440 out=48,803,763 elapsed=113.8s

  [6054/20519] intraday_14594.csv.gz  in=285,583,454 out=48,814,777 elapsed=113.8s

  [6055/20519] intraday_14596.csv.gz  in=285,593,864 out=48,825,187 elapsed=113.8s

  [6056/20519] intraday_14595.csv.gz  in=285,605,756 out=48,837,079 elapsed=113.9s

  [6057/20519] intraday_14598.csv.gz  in=285,612,304 out=48,843,627 elapsed=113.9s

  [6058/20519] intraday_14597.csv.gz  in=285,623,867 out=48,855,190 elapsed=113.9s

  [6059/20519] intraday_14599.csv.gz  in=285,632,133 out=48,863,456 elapsed=113.9s

  [6060/20519] intraday_1460.csv.gz  in=285,644,010 out=48,863,456 elapsed=113.9s

  [6061/20519] intraday_14600.csv.gz  in=285,657,237 out=48,876,683 elapsed=113.9s

  [6062/20519] intraday_14601.csv.gz  in=285,670,835 out=48,890,281 elapsed=113.9s

  [6063/20519] intraday_14603.csv.gz  in=285,680,977 out=48,900,423 elapsed=113.9s

  [6064/20519] intraday_14602.csv.gz  in=285,692,651 out=48,912,097 elapsed=113.9s

  [6065/20519] intraday_14604.csv.gz  in=285,702,836 out=48,922,282 elapsed=113.9s

  [6066/20519] intraday_14605.csv.gz  in=285,714,647 out=48,934,093 elapsed=114.0s

  [6067/20519] intraday_14606.csv.gz  in=285,726,841 out=48,945,533 elapsed=114.0s

  [6068/20519] intraday_14607.csv.gz  in=285,738,298 out=48,956,990 elapsed=114.0s

  [6069/20519] intraday_14608.csv.gz  in=285,750,531 out=48,969,223 elapsed=114.0s

  [6070/20519] intraday_14609.csv.gz  in=285,760,397 out=48,979,089 elapsed=114.0s

  [6071/20519] intraday_1461.csv.gz  in=285,771,947 out=48,979,089 elapsed=114.0s

  [6072/20519] intraday_14610.csv.gz  in=285,780,270 out=48,987,412 elapsed=114.0s

  [6073/20519] intraday_14613.csv.gz  in=285,782,952 out=48,990,094 elapsed=114.1s

  [6074/20519] intraday_14612.csv.gz  in=285,784,329 out=48,991,471 elapsed=114.1s

  [6075/20519] intraday_14614.csv.gz  in=285,793,876 out=49,001,018 elapsed=114.1s

  [6076/20519] intraday_14611.csv.gz  in=285,806,690 out=49,013,832 elapsed=114.1s

  [6077/20519] intraday_14615.csv.gz  in=285,817,800 out=49,024,942 elapsed=114.1s

  [6078/20519] intraday_14616.csv.gz  in=285,831,056 out=49,038,198 elapsed=114.1s

  [6079/20519] intraday_14617.csv.gz  in=285,847,022 out=49,054,164 elapsed=114.1s

  [6080/20519] intraday_14618.csv.gz  in=285,860,571 out=49,067,713 elapsed=114.1s

  [6081/20519] intraday_14619.csv.gz  in=285,872,284 out=49,079,426 elapsed=114.1s

  [6082/20519] intraday_1462.csv.gz  in=285,884,516 out=49,079,426 elapsed=114.2s

  [6083/20519] intraday_14620.csv.gz  in=285,894,974 out=49,089,884 elapsed=114.2s

  [6084/20519] intraday_14621.csv.gz  in=285,906,236 out=49,101,146 elapsed=114.2s

  [6085/20519] intraday_14622.csv.gz  in=285,919,973 out=49,114,883 elapsed=114.2s

  [6086/20519] intraday_14624.csv.gz  in=285,929,575 out=49,124,485 elapsed=114.2s

  [6087/20519] intraday_14623.csv.gz  in=285,941,485 out=49,136,395 elapsed=114.2s

  [6088/20519] intraday_14626.csv.gz  in=285,951,337 out=49,146,247 elapsed=114.2s

  [6089/20519] intraday_14627.csv.gz  in=285,961,916 out=49,156,826 elapsed=114.2s

  [6090/20519] intraday_14628.csv.gz  in=285,974,170 out=49,169,080 elapsed=114.2s

  [6091/20519] intraday_14625.csv.gz  in=285,988,205 out=49,183,115 elapsed=114.2s

  [6092/20519] intraday_1463.csv.gz  in=286,001,391 out=49,183,115 elapsed=114.3s

  [6093/20519] intraday_14629.csv.gz  in=286,012,636 out=49,194,360 elapsed=114.3s

  [6094/20519] intraday_14630.csv.gz  in=286,024,301 out=49,206,025 elapsed=114.3s

  [6095/20519] intraday_14631.csv.gz  in=286,034,453 out=49,216,177 elapsed=114.3s

  [6096/20519] intraday_14632.csv.gz  in=286,044,953 out=49,226,677 elapsed=114.3s

  [6097/20519] intraday_14633.csv.gz  in=286,057,323 out=49,239,047 elapsed=114.3s

  [6098/20519] intraday_14634.csv.gz  in=286,072,704 out=49,254,428 elapsed=114.3s

  [6099/20519] intraday_14636.csv.gz  in=286,084,430 out=49,266,154 elapsed=114.3s

  [6100/20519] intraday_14637.csv.gz  in=286,095,894 out=49,277,618 elapsed=114.4s

  [6101/20519] intraday_14635.csv.gz  in=286,108,672 out=49,290,396 elapsed=114.4s

  [6102/20519] intraday_14639.csv.gz  in=286,121,919 out=49,303,643 elapsed=114.4s

  [6103/20519] intraday_14638.csv.gz  in=286,131,692 out=49,313,416 elapsed=114.4s

  [6104/20519] intraday_1464.csv.gz  in=286,148,386 out=49,313,416 elapsed=114.4s

  [6105/20519] intraday_14640.csv.gz  in=286,159,431 out=49,324,461 elapsed=114.4s

  [6106/20519] intraday_14641.csv.gz  in=286,170,395 out=49,335,425 elapsed=114.4s

  [6107/20519] intraday_14642.csv.gz  in=286,183,978 out=49,349,008 elapsed=114.4s

  [6108/20519] intraday_14644.csv.gz  in=286,195,179 out=49,360,209 elapsed=114.5s

  [6109/20519] intraday_14643.csv.gz  in=286,209,029 out=49,374,059 elapsed=114.5s

  [6110/20519] intraday_14646.csv.gz  in=286,221,266 out=49,386,296 elapsed=114.5s

  [6111/20519] intraday_14647.csv.gz  in=286,232,582 out=49,397,612 elapsed=114.5s

  [6112/20519] intraday_14645.csv.gz  in=286,243,942 out=49,408,972 elapsed=114.5s

  [6113/20519] intraday_14648.csv.gz  in=286,257,568 out=49,422,598 elapsed=114.5s

  [6114/20519] intraday_14649.csv.gz  in=286,271,334 out=49,436,364 elapsed=114.6s

  [6115/20519] intraday_1465.csv.gz  in=286,284,667 out=49,436,364 elapsed=114.6s

  [6116/20519] intraday_14650.csv.gz  in=286,301,990 out=49,453,687 elapsed=114.6s

  [6117/20519] intraday_14651.csv.gz  in=286,313,781 out=49,465,478 elapsed=114.6s

  [6118/20519] intraday_14653.csv.gz  in=286,323,979 out=49,475,676 elapsed=114.6s

  [6119/20519] intraday_14652.csv.gz  in=286,338,258 out=49,489,955 elapsed=114.6s

  [6120/20519] intraday_14654.csv.gz  in=286,350,543 out=49,502,240 elapsed=114.7s

  [6121/20519] intraday_14656.csv.gz  in=286,362,396 out=49,514,000 elapsed=114.7s

  [6122/20519] intraday_14655.csv.gz  in=286,373,059 out=49,524,663 elapsed=114.7s

  [6123/20519] intraday_14657.csv.gz  in=286,383,324 out=49,534,928 elapsed=114.7s

  [6124/20519] intraday_14658.csv.gz  in=286,395,499 out=49,547,103 elapsed=114.7s

  [6125/20519] intraday_1466.csv.gz  in=286,409,848 out=49,547,103 elapsed=114.7s

  [6126/20519] intraday_14659.csv.gz  in=286,420,668 out=49,557,923 elapsed=114.7s

  [6127/20519] intraday_14660.csv.gz  in=286,434,748 out=49,572,003 elapsed=114.8s

  [6128/20519] intraday_14661.csv.gz  in=286,443,777 out=49,581,032 elapsed=114.8s

  [6129/20519] intraday_14662.csv.gz  in=286,454,159 out=49,591,414 elapsed=114.8s

  [6130/20519] intraday_14663.csv.gz  in=286,464,880 out=49,602,135 elapsed=114.8s

  [6131/20519] intraday_14664.csv.gz  in=286,478,052 out=49,615,307 elapsed=114.8s

  [6132/20519] intraday_14666.csv.gz  in=286,491,197 out=49,628,452 elapsed=114.8s

  [6133/20519] intraday_14665.csv.gz  in=286,503,991 out=49,640,656 elapsed=114.8s

  [6134/20519] intraday_14667.csv.gz  in=286,517,087 out=49,653,752 elapsed=114.8s

  [6135/20519] intraday_14668.csv.gz  in=286,530,780 out=49,667,445 elapsed=114.9s

  [6136/20519] intraday_14669.csv.gz  in=286,543,294 out=49,679,959 elapsed=114.9s

  [6137/20519] intraday_1467.csv.gz  in=286,558,612 out=49,679,959 elapsed=114.9s

  [6138/20519] intraday_14671.csv.gz  in=286,570,766 out=49,692,113 elapsed=114.9s

  [6139/20519] intraday_14670.csv.gz  in=286,582,366 out=49,703,713 elapsed=114.9s

  [6140/20519] intraday_14672.csv.gz  in=286,594,730 out=49,716,077 elapsed=114.9s

  [6141/20519] intraday_14673.csv.gz  in=286,604,831 out=49,726,178 elapsed=114.9s

  [6142/20519] intraday_14675.csv.gz  in=286,615,518 out=49,736,865 elapsed=114.9s

  [6143/20519] intraday_14676.csv.gz  in=286,624,231 out=49,745,578 elapsed=114.9s

  [6144/20519] intraday_14674.csv.gz  in=286,639,419 out=49,760,766 elapsed=115.0s

  [6145/20519] intraday_14678.csv.gz  in=286,639,651 out=49,760,998 elapsed=115.0s

  [6146/20519] intraday_14677.csv.gz  in=286,651,773 out=49,773,120 elapsed=115.0s

  [6147/20519] intraday_14680.csv.gz  in=286,651,926 out=49,773,273 elapsed=115.0s

  [6148/20519] intraday_14679.csv.gz  in=286,652,827 out=49,774,174 elapsed=115.0s

  [6149/20519] intraday_14681.csv.gz  in=286,653,345 out=49,774,692 elapsed=115.0s

  [6150/20519] intraday_14683.csv.gz  in=286,653,736 out=49,775,083 elapsed=115.0s

  [6151/20519] intraday_14684.csv.gz  in=286,654,292 out=49,775,639 elapsed=115.0s

  [6152/20519] intraday_14682.csv.gz  in=286,654,560 out=49,775,907 elapsed=115.0s

  [6153/20519] intraday_14685.csv.gz  in=286,655,132 out=49,776,479 elapsed=115.0s

  [6154/20519] intraday_1468.csv.gz  in=286,671,003 out=49,776,479 elapsed=115.0s

  [6155/20519] intraday_14688.csv.gz  in=286,671,227 out=49,776,703 elapsed=115.0s

  [6156/20519] intraday_14687.csv.gz  in=286,671,587 out=49,777,063 elapsed=115.0s

  [6157/20519] intraday_14686.csv.gz  in=286,671,810 out=49,777,286 elapsed=115.0s

  [6158/20519] intraday_14690.csv.gz  in=286,672,190 out=49,777,666 elapsed=115.0s

  [6159/20519] intraday_14691.csv.gz  in=286,672,618 out=49,778,094 elapsed=115.1s

  [6160/20519] intraday_14689.csv.gz  in=286,673,448 out=49,778,924 elapsed=115.1s

  [6161/20519] intraday_14693.csv.gz  in=286,673,816 out=49,779,292 elapsed=115.1s

  [6162/20519] intraday_14694.csv.gz  in=286,673,954 out=49,779,430 elapsed=115.1s

  [6163/20519] intraday_14692.csv.gz  in=286,674,588 out=49,780,064 elapsed=115.1s

  [6164/20519] intraday_1469.csv.gz  in=286,689,185 out=49,780,064 elapsed=115.1s

  [6165/20519] intraday_14695.csv.gz  in=286,689,935 out=49,780,814 elapsed=115.1s

  [6166/20519] intraday_14697.csv.gz  in=286,690,179 out=49,781,058 elapsed=115.1s

  [6167/20519] intraday_14698.csv.gz  in=286,690,507 out=49,781,386 elapsed=115.1s

  [6168/20519] intraday_14696.csv.gz  in=286,691,042 out=49,781,921 elapsed=115.1s

  [6169/20519] intraday_14699.csv.gz  in=286,691,613 out=49,782,492 elapsed=115.1s

  [6170/20519] intraday_14701.csv.gz  in=286,692,045 out=49,782,924 elapsed=115.1s

  [6171/20519] intraday_14700.csv.gz  in=286,692,177 out=49,783,056 elapsed=115.1s

  [6172/20519] intraday_14702.csv.gz  in=286,692,436 out=49,783,315 elapsed=115.1s

  [6173/20519] intraday_14703.csv.gz  in=286,692,793 out=49,783,672 elapsed=115.1s

  [6174/20519] intraday_1470.csv.gz  in=286,706,642 out=49,783,672 elapsed=115.1s

  [6175/20519] intraday_14704.csv.gz  in=286,706,950 out=49,783,980 elapsed=115.1s

  [6176/20519] intraday_14705.csv.gz  in=286,707,264 out=49,784,294 elapsed=115.1s

  [6177/20519] intraday_14708.csv.gz  in=286,707,866 out=49,784,896 elapsed=115.1s

  [6178/20519] intraday_14709.csv.gz  in=286,708,794 out=49,785,824 elapsed=115.2s

  [6179/20519] intraday_14706.csv.gz  in=286,708,849 out=49,785,879 elapsed=115.2s

  [6180/20519] intraday_14707.csv.gz  in=286,709,505 out=49,786,535 elapsed=115.2s

  [6181/20519] intraday_14710.csv.gz  in=286,709,801 out=49,786,831 elapsed=115.2s

  [6182/20519] intraday_14711.csv.gz  in=286,709,994 out=49,787,024 elapsed=115.2s

  [6183/20519] intraday_14712.csv.gz  in=286,710,341 out=49,787,371 elapsed=115.2s

  [6184/20519] intraday_1471.csv.gz  in=286,724,189 out=49,787,371 elapsed=115.2s

  [6185/20519] intraday_14713.csv.gz  in=286,724,380 out=49,787,562 elapsed=115.2s

  [6186/20519] intraday_14715.csv.gz  in=286,724,735 out=49,787,917 elapsed=115.2s

  [6187/20519] intraday_14716.csv.gz  in=286,725,091 out=49,788,273 elapsed=115.2s

  [6188/20519] intraday_14717.csv.gz  in=286,725,242 out=49,788,424 elapsed=115.2s

  [6189/20519] intraday_14714.csv.gz  in=286,725,553 out=49,788,735 elapsed=115.2s

  [6190/20519] intraday_14719.csv.gz  in=286,725,619 out=49,788,801 elapsed=115.2s

  [6191/20519] intraday_14718.csv.gz  in=286,725,683 out=49,788,865 elapsed=115.2s

  [6192/20519] intraday_14720.csv.gz  in=286,726,001 out=49,789,183 elapsed=115.2s

  [6193/20519] intraday_1472.csv.gz  in=286,739,316 out=49,789,183 elapsed=115.2s

  [6194/20519] intraday_14721.csv.gz  in=286,739,936 out=49,789,803 elapsed=115.3s

  [6195/20519] intraday_14722.csv.gz  in=286,739,999 out=49,789,866 elapsed=115.3s

  [6196/20519] intraday_14724.csv.gz  in=286,740,163 out=49,790,030 elapsed=115.3s

  [6197/20519] intraday_14725.csv.gz  in=286,740,486 out=49,790,353 elapsed=115.3s

  [6198/20519] intraday_14723.csv.gz  in=286,740,847 out=49,790,714 elapsed=115.3s

  [6199/20519] intraday_14726.csv.gz  in=286,741,037 out=49,790,904 elapsed=115.3s

  [6200/20519] intraday_14727.csv.gz  in=286,741,386 out=49,791,253 elapsed=115.3s

  [6201/20519] intraday_14729.csv.gz  in=286,741,515 out=49,791,382 elapsed=115.3s

  [6202/20519] intraday_14730.csv.gz  in=286,742,301 out=49,792,168 elapsed=115.3s

  [6203/20519] intraday_14728.csv.gz  in=286,742,447 out=49,792,314 elapsed=115.3s

  [6204/20519] intraday_14731.csv.gz  in=286,743,137 out=49,793,004 elapsed=115.3s

  [6205/20519] intraday_1473.csv.gz  in=286,754,784 out=49,793,004 elapsed=115.3s

  [6206/20519] intraday_14732.csv.gz  in=286,755,168 out=49,793,388 elapsed=115.3s

  [6207/20519] intraday_14733.csv.gz  in=286,755,902 out=49,794,122 elapsed=115.3s

  [6208/20519] intraday_14734.csv.gz  in=286,756,040 out=49,794,260 elapsed=115.3s

  [6209/20519] intraday_14736.csv.gz  in=286,756,229 out=49,794,449 elapsed=115.3s

  [6210/20519] intraday_14735.csv.gz  in=286,756,350 out=49,794,570 elapsed=115.3s

  [6211/20519] intraday_14739.csv.gz  in=286,756,511 out=49,794,731 elapsed=115.3s

  [6212/20519] intraday_14738.csv.gz  in=286,756,703 out=49,794,923 elapsed=115.3s

  [6213/20519] intraday_14737.csv.gz  in=286,757,069 out=49,795,289 elapsed=115.3s

  [6214/20519] intraday_14741.csv.gz  in=286,757,172 out=49,795,392 elapsed=115.3s

  [6215/20519] intraday_14740.csv.gz  in=286,757,641 out=49,795,861 elapsed=115.4s

  [6216/20519] intraday_14743.csv.gz  in=286,758,273 out=49,796,493 elapsed=115.4s

  [6217/20519] intraday_14744.csv.gz  in=286,759,202 out=49,797,422 elapsed=115.4s

  [6218/20519] intraday_14742.csv.gz  in=286,759,237 out=49,797,457 elapsed=115.4s

  [6219/20519] intraday_14745.csv.gz  in=286,759,319 out=49,797,539 elapsed=115.4s

  [6220/20519] intraday_1474.csv.gz  in=286,771,835 out=49,797,539 elapsed=115.4s

  [6221/20519] intraday_14746.csv.gz  in=286,772,036 out=49,797,740 elapsed=115.4s

  [6222/20519] intraday_14747.csv.gz  in=286,772,544 out=49,798,248 elapsed=115.4s

  [6223/20519] intraday_14749.csv.gz  in=286,772,832 out=49,798,536 elapsed=115.4s

  [6224/20519] intraday_14748.csv.gz  in=286,773,449 out=49,799,153 elapsed=115.4s

  [6225/20519] intraday_14750.csv.gz  in=286,773,992 out=49,799,696 elapsed=115.4s

  [6226/20519] intraday_14751.csv.gz  in=286,774,205 out=49,799,909 elapsed=115.4s

  [6227/20519] intraday_14752.csv.gz  in=286,774,404 out=49,800,108 elapsed=115.4s

  [6228/20519] intraday_1475.csv.gz  in=286,788,578 out=49,800,108 elapsed=115.4s

  [6229/20519] intraday_14754.csv.gz  in=286,788,771 out=49,800,301 elapsed=115.4s

  [6230/20519] intraday_14756.csv.gz  in=286,789,126 out=49,800,656 elapsed=115.4s

  [6231/20519] intraday_14757.csv.gz  in=286,789,316 out=49,800,846 elapsed=115.4s

  [6232/20519] intraday_14753.csv.gz  in=286,790,039 out=49,801,569 elapsed=115.4s

  [6233/20519] intraday_14755.csv.gz  in=286,790,331 out=49,801,861 elapsed=115.4s

  [6234/20519] intraday_14759.csv.gz  in=286,790,431 out=49,801,961 elapsed=115.5s

  [6235/20519] intraday_14760.csv.gz  in=286,790,817 out=49,802,347 elapsed=115.5s

  [6236/20519] intraday_14758.csv.gz  in=286,791,126 out=49,802,656 elapsed=115.5s

  [6237/20519] intraday_14761.csv.gz  in=286,791,833 out=49,803,363 elapsed=115.5s

  [6238/20519] intraday_14762.csv.gz  in=286,792,998 out=49,804,528 elapsed=115.5s

  [6239/20519] intraday_14764.csv.gz  in=286,793,885 out=49,805,415 elapsed=115.5s

  [6240/20519] intraday_14763.csv.gz  in=286,794,896 out=49,806,426 elapsed=115.5s

  [6241/20519] intraday_14765.csv.gz  in=286,795,380 out=49,806,910 elapsed=115.5s

  [6242/20519] intraday_1476.csv.gz  in=286,808,163 out=49,806,910 elapsed=115.5s

  [6243/20519] intraday_14766.csv.gz  in=286,808,782 out=49,807,529 elapsed=115.5s

  [6244/20519] intraday_14767.csv.gz  in=286,808,915 out=49,807,662 elapsed=115.5s

  [6245/20519] intraday_14769.csv.gz  in=286,809,086 out=49,807,813 elapsed=115.5s

  [6246/20519] intraday_14770.csv.gz  in=286,809,392 out=49,808,119 elapsed=115.5s

  [6247/20519] intraday_14768.csv.gz  in=286,810,521 out=49,809,248 elapsed=115.5s

  [6248/20519] intraday_14771.csv.gz  in=286,810,884 out=49,809,611 elapsed=115.5s

  [6249/20519] intraday_14772.csv.gz  in=286,811,217 out=49,809,944 elapsed=115.5s

  [6250/20519] intraday_1477.csv.gz  in=286,825,232 out=49,809,944 elapsed=115.6s

  [6251/20519] intraday_14774.csv.gz  in=286,825,441 out=49,810,153 elapsed=115.6s

  [6252/20519] intraday_14775.csv.gz  in=286,825,724 out=49,810,436 elapsed=115.6s

  [6253/20519] intraday_14776.csv.gz  in=286,825,984 out=49,810,696 elapsed=115.6s

  [6254/20519] intraday_14777.csv.gz  in=286,826,535 out=49,811,247 elapsed=115.6s

  [6255/20519] intraday_14778.csv.gz  in=286,826,779 out=49,811,491 elapsed=115.6s

  [6256/20519] intraday_14779.csv.gz  in=286,827,296 out=49,812,008 elapsed=115.6s

  [6257/20519] intraday_14773.csv.gz  in=286,832,856 out=49,814,667 elapsed=115.6s

  [6258/20519] intraday_14781.csv.gz  in=286,834,178 out=49,815,989 elapsed=115.6s

  [6259/20519] intraday_1478.csv.gz  in=286,846,714 out=49,815,989 elapsed=115.6s

  [6260/20519] intraday_14780.csv.gz  in=286,847,151 out=49,816,426 elapsed=115.7s

  [6261/20519] intraday_14784.csv.gz  in=286,847,368 out=49,816,643 elapsed=115.7s

  [6262/20519] intraday_14783.csv.gz  in=286,847,818 out=49,817,093 elapsed=115.7s

  [6263/20519] intraday_14782.csv.gz  in=286,848,999 out=49,817,753 elapsed=115.7s

  [6264/20519] intraday_14785.csv.gz  in=286,849,750 out=49,818,504 elapsed=115.7s

  [6265/20519] intraday_14787.csv.gz  in=286,850,145 out=49,818,899 elapsed=115.7s

  [6266/20519] intraday_14786.csv.gz  in=286,850,245 out=49,818,999 elapsed=115.7s

  [6267/20519] intraday_14789.csv.gz  in=286,850,681 out=49,819,435 elapsed=115.7s

  [6268/20519] intraday_14788.csv.gz  in=286,850,929 out=49,819,683 elapsed=115.7s

  [6269/20519] intraday_14790.csv.gz  in=286,851,270 out=49,820,024 elapsed=115.7s

  [6270/20519] intraday_14791.csv.gz  in=286,851,590 out=49,820,344 elapsed=115.7s

  [6271/20519] intraday_14792.csv.gz  in=286,852,547 out=49,821,301 elapsed=115.7s

  [6272/20519] intraday_14793.csv.gz  in=286,853,252 out=49,822,006 elapsed=115.7s

  [6273/20519] intraday_1479.csv.gz  in=286,866,210 out=49,822,006 elapsed=115.7s

  [6274/20519] intraday_14796.csv.gz  in=286,866,963 out=49,822,759 elapsed=115.8s

  [6275/20519] intraday_14794.csv.gz  in=286,868,163 out=49,823,959 elapsed=115.8s

  [6276/20519] intraday_14797.csv.gz  in=286,869,177 out=49,824,973 elapsed=115.8s

  [6277/20519] intraday_14798.csv.gz  in=286,869,392 out=49,825,188 elapsed=115.8s

  [6278/20519] intraday_14795.csv.gz  in=286,870,633 out=49,826,429 elapsed=115.8s

  [6279/20519] intraday_14799.csv.gz  in=286,871,001 out=49,826,797 elapsed=115.8s

  [6280/20519] intraday_14800.csv.gz  in=286,871,201 out=49,826,997 elapsed=115.8s

  [6281/20519] intraday_14801.csv.gz  in=286,871,375 out=49,827,171 elapsed=115.8s

  [6282/20519] intraday_14802.csv.gz  in=286,871,860 out=49,827,656 elapsed=115.8s

  [6283/20519] intraday_14803.csv.gz  in=286,872,138 out=49,827,934 elapsed=115.8s

  [6284/20519] intraday_1480.csv.gz  in=286,885,541 out=49,827,934 elapsed=115.8s

  [6285/20519] intraday_14805.csv.gz  in=286,886,008 out=49,828,401 elapsed=115.8s

  [6286/20519] intraday_14804.csv.gz  in=286,886,412 out=49,828,805 elapsed=115.8s

  [6287/20519] intraday_14806.csv.gz  in=286,887,059 out=49,829,452 elapsed=115.8s

  [6288/20519] intraday_14807.csv.gz  in=286,887,355 out=49,829,748 elapsed=115.8s

  [6289/20519] intraday_14809.csv.gz  in=286,887,728 out=49,830,121 elapsed=115.8s

  [6290/20519] intraday_14808.csv.gz  in=286,888,188 out=49,830,581 elapsed=115.8s

  [6291/20519] intraday_14810.csv.gz  in=286,888,945 out=49,831,338 elapsed=115.8s

  [6292/20519] intraday_14812.csv.gz  in=286,889,199 out=49,831,592 elapsed=115.8s

  [6293/20519] intraday_14811.csv.gz  in=286,889,510 out=49,831,903 elapsed=115.9s

  [6294/20519] intraday_1481.csv.gz  in=286,902,508 out=49,831,903 elapsed=115.9s

  [6295/20519] intraday_14813.csv.gz  in=286,903,035 out=49,832,430 elapsed=115.9s

  [6296/20519] intraday_14815.csv.gz  in=286,903,260 out=49,832,655 elapsed=115.9s

  [6297/20519] intraday_14816.csv.gz  in=286,904,090 out=49,833,485 elapsed=115.9s

  [6298/20519] intraday_14818.csv.gz  in=286,904,286 out=49,833,681 elapsed=115.9s

  [6299/20519] intraday_14817.csv.gz  in=286,904,620 out=49,834,015 elapsed=115.9s

  [6300/20519] intraday_14814.csv.gz  in=286,904,955 out=49,834,350 elapsed=115.9s

  [6301/20519] intraday_14820.csv.gz  in=286,905,533 out=49,834,928 elapsed=115.9s

  [6302/20519] intraday_14819.csv.gz  in=286,906,094 out=49,835,489 elapsed=115.9s

  [6303/20519] intraday_14822.csv.gz  in=286,906,366 out=49,835,761 elapsed=115.9s

  [6304/20519] intraday_14821.csv.gz  in=286,906,898 out=49,836,293 elapsed=115.9s

  [6305/20519] intraday_1482.csv.gz  in=286,921,281 out=49,836,293 elapsed=115.9s

  [6306/20519] intraday_14823.csv.gz  in=286,921,335 out=49,836,347 elapsed=115.9s

  [6307/20519] intraday_14824.csv.gz  in=286,936,296 out=49,851,308 elapsed=116.0s

  [6308/20519] intraday_14825.csv.gz  in=286,947,323 out=49,862,335 elapsed=116.0s

  [6309/20519] intraday_14827.csv.gz  in=286,957,844 out=49,872,856 elapsed=116.0s

  [6310/20519] intraday_14826.csv.gz  in=286,971,628 out=49,886,640 elapsed=116.0s

  [6311/20519] intraday_1483.csv.gz  in=286,986,682 out=49,886,640 elapsed=116.0s

  [6312/20519] intraday_14828.csv.gz  in=286,998,757 out=49,898,715 elapsed=116.0s

  [6313/20519] intraday_14829.csv.gz  in=287,011,371 out=49,911,329 elapsed=116.0s

  [6314/20519] intraday_14830.csv.gz  in=287,024,456 out=49,924,414 elapsed=116.0s

  [6315/20519] intraday_14831.csv.gz  in=287,035,869 out=49,935,827 elapsed=116.1s

  [6316/20519] intraday_14832.csv.gz  in=287,047,638 out=49,947,596 elapsed=116.1s

  [6317/20519] intraday_14834.csv.gz  in=287,058,240 out=49,958,198 elapsed=116.1s

  [6318/20519] intraday_14833.csv.gz  in=287,070,435 out=49,970,393 elapsed=116.1s

  [6319/20519] intraday_14835.csv.gz  in=287,081,838 out=49,981,796 elapsed=116.1s

  [6320/20519] intraday_14836.csv.gz  in=287,093,146 out=49,993,104 elapsed=116.1s

  [6321/20519] intraday_14838.csv.gz  in=287,103,297 out=50,003,255 elapsed=116.1s

  [6322/20519] intraday_14839.csv.gz  in=287,111,680 out=50,011,638 elapsed=116.2s

  [6323/20519] intraday_14837.csv.gz  in=287,124,545 out=50,024,503 elapsed=116.2s

  [6324/20519] intraday_1484.csv.gz  in=287,139,130 out=50,024,503 elapsed=116.2s

  [6325/20519] intraday_14840.csv.gz  in=287,153,534 out=50,038,907 elapsed=116.2s

  [6326/20519] intraday_14843.csv.gz  in=287,163,815 out=50,049,188 elapsed=116.2s

  [6327/20519] intraday_14842.csv.gz  in=287,175,764 out=50,061,137 elapsed=116.2s

  [6328/20519] intraday_14844.csv.gz  in=287,189,006 out=50,074,379 elapsed=116.2s

  [6329/20519] intraday_14841.csv.gz  in=287,201,625 out=50,086,998 elapsed=116.2s

  [6330/20519] intraday_14845.csv.gz  in=287,213,009 out=50,098,382 elapsed=116.2s

  [6331/20519] intraday_14846.csv.gz  in=287,225,644 out=50,111,017 elapsed=116.3s

  [6332/20519] intraday_14847.csv.gz  in=287,237,530 out=50,122,903 elapsed=116.3s

  [6333/20519] intraday_14849.csv.gz  in=287,249,764 out=50,135,137 elapsed=116.3s

  [6334/20519] intraday_14848.csv.gz  in=287,262,584 out=50,147,957 elapsed=116.3s

  [6335/20519] intraday_1485.csv.gz  in=287,276,322 out=50,147,957 elapsed=116.3s

  [6336/20519] intraday_14850.csv.gz  in=287,286,721 out=50,158,098 elapsed=116.3s

  [6337/20519] intraday_14852.csv.gz  in=287,297,569 out=50,168,946 elapsed=116.3s

  [6338/20519] intraday_14851.csv.gz  in=287,309,081 out=50,180,458 elapsed=116.4s

  [6339/20519] intraday_14853.csv.gz  in=287,322,768 out=50,194,145 elapsed=116.4s

  [6340/20519] intraday_14854.csv.gz  in=287,338,298 out=50,209,675 elapsed=116.4s

  [6341/20519] intraday_14857.csv.gz  in=287,350,321 out=50,221,698 elapsed=116.4s

  [6342/20519] intraday_14855.csv.gz  in=287,362,186 out=50,233,563 elapsed=116.4s

  [6343/20519] intraday_14856.csv.gz  in=287,373,169 out=50,244,546 elapsed=116.4s

  [6344/20519] intraday_14858.csv.gz  in=287,385,489 out=50,256,866 elapsed=116.5s

  [6345/20519] intraday_14859.csv.gz  in=287,397,095 out=50,268,472 elapsed=116.5s

  [6346/20519] intraday_1486.csv.gz  in=287,411,783 out=50,268,472 elapsed=116.5s

  [6347/20519] intraday_14860.csv.gz  in=287,424,394 out=50,281,083 elapsed=116.5s

  [6348/20519] intraday_14861.csv.gz  in=287,434,265 out=50,290,954 elapsed=116.5s

  [6349/20519] intraday_14863.csv.gz  in=287,443,120 out=50,299,809 elapsed=116.5s

  [6350/20519] intraday_14862.csv.gz  in=287,455,003 out=50,311,692 elapsed=116.5s

  [6351/20519] intraday_14864.csv.gz  in=287,466,465 out=50,323,154 elapsed=116.5s

  [6352/20519] intraday_14865.csv.gz  in=287,478,371 out=50,335,060 elapsed=116.5s

  [6353/20519] intraday_14866.csv.gz  in=287,492,063 out=50,348,752 elapsed=116.6s

  [6354/20519] intraday_14867.csv.gz  in=287,503,869 out=50,360,558 elapsed=116.6s

  [6355/20519] intraday_14869.csv.gz  in=287,514,163 out=50,370,852 elapsed=116.6s

  [6356/20519] intraday_14868.csv.gz  in=287,527,410 out=50,384,099 elapsed=116.6s

  [6357/20519] intraday_1487.csv.gz  in=287,540,376 out=50,384,099 elapsed=116.6s

  [6358/20519] intraday_14870.csv.gz  in=287,551,547 out=50,395,270 elapsed=116.6s

  [6359/20519] intraday_14871.csv.gz  in=287,564,668 out=50,408,391 elapsed=116.7s

  [6360/20519] intraday_14873.csv.gz  in=287,575,490 out=50,419,213 elapsed=116.7s

  [6361/20519] intraday_14872.csv.gz  in=287,594,397 out=50,435,040 elapsed=116.7s

  [6362/20519] intraday_14874.csv.gz  in=287,605,711 out=50,446,354 elapsed=116.7s

  [6363/20519] intraday_14875.csv.gz  in=287,615,838 out=50,456,481 elapsed=116.7s

  [6364/20519] intraday_14876.csv.gz  in=287,629,464 out=50,470,107 elapsed=116.7s

  [6365/20519] intraday_14878.csv.gz  in=287,640,807 out=50,481,450 elapsed=116.7s

  [6366/20519] intraday_1488.csv.gz  in=287,656,965 out=50,481,450 elapsed=116.7s

  [6367/20519] intraday_14877.csv.gz  in=287,669,789 out=50,494,274 elapsed=116.7s

  [6368/20519] intraday_14879.csv.gz  in=287,682,382 out=50,506,867 elapsed=116.8s

  [6369/20519] intraday_14880.csv.gz  in=287,692,978 out=50,517,463 elapsed=116.8s

  [6370/20519] intraday_14882.csv.gz  in=287,703,399 out=50,527,884 elapsed=116.8s

  [6371/20519] intraday_14881.csv.gz  in=287,713,773 out=50,538,258 elapsed=116.8s

  [6372/20519] intraday_14883.csv.gz  in=287,726,074 out=50,550,559 elapsed=116.8s

  [6373/20519] intraday_14884.csv.gz  in=287,737,003 out=50,561,488 elapsed=116.8s

  [6374/20519] intraday_14887.csv.gz  in=287,747,801 out=50,572,286 elapsed=116.9s

  [6375/20519] intraday_14885.csv.gz  in=287,759,357 out=50,583,842 elapsed=116.9s

  [6376/20519] intraday_14886.csv.gz  in=287,769,924 out=50,594,409 elapsed=116.9s

  [6377/20519] intraday_14888.csv.gz  in=287,779,786 out=50,604,271 elapsed=116.9s

  [6378/20519] intraday_14889.csv.gz  in=287,793,460 out=50,617,945 elapsed=116.9s

  [6379/20519] intraday_1489.csv.gz  in=287,805,877 out=50,617,945 elapsed=116.9s

  [6380/20519] intraday_14890.csv.gz  in=287,817,783 out=50,629,851 elapsed=116.9s

  [6381/20519] intraday_14891.csv.gz  in=287,830,982 out=50,643,050 elapsed=116.9s

  [6382/20519] intraday_14892.csv.gz  in=287,842,752 out=50,654,820 elapsed=117.0s

  [6383/20519] intraday_14894.csv.gz  in=287,854,315 out=50,666,383 elapsed=117.0s

  [6384/20519] intraday_14895.csv.gz  in=287,866,216 out=50,678,284 elapsed=117.0s

  [6385/20519] intraday_14893.csv.gz  in=287,877,315 out=50,689,383 elapsed=117.0s

  [6386/20519] intraday_14896.csv.gz  in=287,888,802 out=50,700,870 elapsed=117.0s

  [6387/20519] intraday_14897.csv.gz  in=287,900,282 out=50,712,350 elapsed=117.1s

  [6388/20519] intraday_14898.csv.gz  in=287,912,740 out=50,724,808 elapsed=117.1s

  [6389/20519] intraday_1490.csv.gz  in=287,927,153 out=50,724,808 elapsed=117.1s

  [6390/20519] intraday_14899.csv.gz  in=287,936,906 out=50,734,561 elapsed=117.1s

  [6391/20519] intraday_14900.csv.gz  in=287,946,337 out=50,743,992 elapsed=117.1s

  [6392/20519] intraday_14901.csv.gz  in=287,959,102 out=50,756,757 elapsed=117.1s

  [6393/20519] intraday_14902.csv.gz  in=287,969,738 out=50,767,393 elapsed=117.1s

  [6394/20519] intraday_14904.csv.gz  in=287,980,071 out=50,777,549 elapsed=117.1s

  [6395/20519] intraday_14903.csv.gz  in=287,992,152 out=50,789,630 elapsed=117.2s

  [6396/20519] intraday_14906.csv.gz  in=288,004,751 out=50,802,229 elapsed=117.2s

  [6397/20519] intraday_14905.csv.gz  in=288,014,413 out=50,811,891 elapsed=117.2s

  [6398/20519] intraday_14907.csv.gz  in=288,026,560 out=50,824,038 elapsed=117.2s

  [6399/20519] intraday_14908.csv.gz  in=288,043,071 out=50,840,549 elapsed=117.2s

  [6400/20519] intraday_14909.csv.gz  in=288,056,159 out=50,853,637 elapsed=117.2s

  [6401/20519] intraday_14910.csv.gz  in=288,068,991 out=50,866,469 elapsed=117.2s

  [6402/20519] intraday_14911.csv.gz  in=288,079,567 out=50,877,045 elapsed=117.2s

  [6403/20519] intraday_1491.csv.gz  in=288,096,039 out=50,877,045 elapsed=117.2s

  [6404/20519] intraday_14912.csv.gz  in=288,107,678 out=50,888,684 elapsed=117.3s

  [6405/20519] intraday_14913.csv.gz  in=288,119,848 out=50,900,854 elapsed=117.3s

  [6406/20519] intraday_14915.csv.gz  in=288,130,449 out=50,911,455 elapsed=117.3s

  [6407/20519] intraday_14914.csv.gz  in=288,142,446 out=50,923,452 elapsed=117.3s

  [6408/20519] intraday_14917.csv.gz  in=288,152,617 out=50,933,623 elapsed=117.3s

  [6409/20519] intraday_14916.csv.gz  in=288,166,191 out=50,947,197 elapsed=117.3s

  [6410/20519] intraday_14918.csv.gz  in=288,176,476 out=50,957,482 elapsed=117.3s

  [6411/20519] intraday_14919.csv.gz  in=288,190,283 out=50,971,289 elapsed=117.3s

  [6412/20519] intraday_1492.csv.gz  in=288,203,948 out=50,971,289 elapsed=117.3s

  [6413/20519] intraday_14920.csv.gz  in=288,215,953 out=50,983,294 elapsed=117.3s

  [6414/20519] intraday_14921.csv.gz  in=288,228,498 out=50,995,839 elapsed=117.4s

  [6415/20519] intraday_14923.csv.gz  in=288,239,060 out=51,006,401 elapsed=117.4s

  [6416/20519] intraday_14924.csv.gz  in=288,250,670 out=51,018,011 elapsed=117.4s

  [6417/20519] intraday_14925.csv.gz  in=288,263,352 out=51,030,693 elapsed=117.4s

  [6418/20519] intraday_14926.csv.gz  in=288,276,374 out=51,043,715 elapsed=117.4s

  [6419/20519] intraday_14927.csv.gz  in=288,287,838 out=51,055,179 elapsed=117.4s

  [6420/20519] intraday_14922.csv.gz  in=288,298,670 out=51,066,011 elapsed=117.4s

  [6421/20519] intraday_14929.csv.gz  in=288,310,099 out=51,077,440 elapsed=117.4s

  [6422/20519] intraday_14928.csv.gz  in=288,321,194 out=51,088,535 elapsed=117.5s

  [6423/20519] intraday_14930.csv.gz  in=288,332,878 out=51,100,219 elapsed=117.5s

  [6424/20519] intraday_14931.csv.gz  in=288,345,690 out=51,113,031 elapsed=117.5s

  [6425/20519] intraday_1493.csv.gz  in=288,359,724 out=51,113,031 elapsed=117.5s

  [6426/20519] intraday_14932.csv.gz  in=288,370,190 out=51,123,497 elapsed=117.5s

  [6427/20519] intraday_14933.csv.gz  in=288,383,947 out=51,137,254 elapsed=117.5s

  [6428/20519] intraday_14935.csv.gz  in=288,395,778 out=51,149,085 elapsed=117.5s

  [6429/20519] intraday_14934.csv.gz  in=288,408,739 out=51,162,046 elapsed=117.5s

  [6430/20519] intraday_14936.csv.gz  in=288,420,208 out=51,173,515 elapsed=117.6s

  [6431/20519] intraday_14937.csv.gz  in=288,432,651 out=51,185,958 elapsed=117.6s

  [6432/20519] intraday_14938.csv.gz  in=288,445,570 out=51,198,877 elapsed=117.6s

  [6433/20519] intraday_1494.csv.gz  in=288,461,237 out=51,198,877 elapsed=117.6s

  [6434/20519] intraday_14939.csv.gz  in=288,473,628 out=51,211,268 elapsed=117.7s

  [6435/20519] intraday_14940.csv.gz  in=288,487,158 out=51,224,798 elapsed=117.7s

  [6436/20519] intraday_14941.csv.gz  in=288,504,067 out=51,241,707 elapsed=117.7s

  [6437/20519] intraday_14942.csv.gz  in=288,516,721 out=51,254,361 elapsed=117.7s

  [6438/20519] intraday_14943.csv.gz  in=288,532,953 out=51,270,593 elapsed=117.7s

  [6439/20519] intraday_14944.csv.gz  in=288,543,116 out=51,280,756 elapsed=117.7s

  [6440/20519] intraday_14945.csv.gz  in=288,555,812 out=51,293,452 elapsed=117.8s

  [6441/20519] intraday_14946.csv.gz  in=288,566,611 out=51,304,251 elapsed=117.8s

  [6442/20519] intraday_14947.csv.gz  in=288,578,723 out=51,316,363 elapsed=117.8s

  [6443/20519] intraday_14948.csv.gz  in=288,589,667 out=51,327,307 elapsed=117.8s

  [6444/20519] intraday_14949.csv.gz  in=288,601,919 out=51,339,559 elapsed=117.8s

  [6445/20519] intraday_1495.csv.gz  in=288,613,095 out=51,339,559 elapsed=117.8s

  [6446/20519] intraday_14950.csv.gz  in=288,624,309 out=51,350,773 elapsed=117.8s

  [6447/20519] intraday_14951.csv.gz  in=288,641,115 out=51,367,579 elapsed=117.9s

  [6448/20519] intraday_14952.csv.gz  in=288,650,609 out=51,377,073 elapsed=117.9s

  [6449/20519] intraday_14953.csv.gz  in=288,661,213 out=51,387,677 elapsed=117.9s

  [6450/20519] intraday_14954.csv.gz  in=288,673,110 out=51,399,574 elapsed=117.9s

  [6451/20519] intraday_14956.csv.gz  in=288,685,338 out=51,411,802 elapsed=117.9s

  [6452/20519] intraday_14955.csv.gz  in=288,696,369 out=51,422,833 elapsed=117.9s

  [6453/20519] intraday_14957.csv.gz  in=288,709,357 out=51,435,821 elapsed=117.9s

  [6454/20519] intraday_14959.csv.gz  in=288,722,789 out=51,449,253 elapsed=118.0s

  [6455/20519] intraday_14958.csv.gz  in=288,741,296 out=51,465,332 elapsed=118.0s

  [6456/20519] intraday_1496.csv.gz  in=288,753,685 out=51,465,332 elapsed=118.0s

  [6457/20519] intraday_14960.csv.gz  in=288,769,669 out=51,480,028 elapsed=118.0s

  [6458/20519] intraday_14961.csv.gz  in=288,782,306 out=51,492,665 elapsed=118.0s

  [6459/20519] intraday_14962.csv.gz  in=288,796,014 out=51,506,373 elapsed=118.0s

  [6460/20519] intraday_14963.csv.gz  in=288,808,504 out=51,518,863 elapsed=118.0s

  [6461/20519] intraday_14965.csv.gz  in=288,820,457 out=51,530,816 elapsed=118.1s

  [6462/20519] intraday_14964.csv.gz  in=288,830,974 out=51,541,333 elapsed=118.1s

  [6463/20519] intraday_14966.csv.gz  in=288,841,051 out=51,551,410 elapsed=118.1s

  [6464/20519] intraday_14967.csv.gz  in=288,849,474 out=51,559,833 elapsed=118.1s

  [6465/20519] intraday_14968.csv.gz  in=288,862,560 out=51,572,919 elapsed=118.1s

  [6466/20519] intraday_14969.csv.gz  in=288,863,838 out=51,574,197 elapsed=118.1s

  [6467/20519] intraday_1497.csv.gz  in=288,888,432 out=51,574,197 elapsed=118.1s

  [6468/20519] intraday_14971.csv.gz  in=288,900,350 out=51,586,115 elapsed=118.1s

  [6469/20519] intraday_14970.csv.gz  in=288,915,086 out=51,600,851 elapsed=118.1s

  [6470/20519] intraday_14972.csv.gz  in=288,927,580 out=51,613,345 elapsed=118.1s

  [6471/20519] intraday_14973.csv.gz  in=288,939,627 out=51,625,392 elapsed=118.2s

  [6472/20519] intraday_14974.csv.gz  in=288,950,719 out=51,636,484 elapsed=118.2s

  [6473/20519] intraday_14975.csv.gz  in=288,966,076 out=51,651,841 elapsed=118.2s

  [6474/20519] intraday_14976.csv.gz  in=288,978,773 out=51,664,538 elapsed=118.2s

  [6475/20519] intraday_14977.csv.gz  in=288,990,156 out=51,675,921 elapsed=118.2s

  [6476/20519] intraday_14978.csv.gz  in=289,002,676 out=51,688,441 elapsed=118.2s

  [6477/20519] intraday_14979.csv.gz  in=289,014,932 out=51,700,697 elapsed=118.2s

  [6478/20519] intraday_14980.csv.gz  in=289,025,926 out=51,711,691 elapsed=118.2s

  [6479/20519] intraday_1498.csv.gz  in=289,041,204 out=51,711,691 elapsed=118.3s

  [6480/20519] intraday_14981.csv.gz  in=289,053,992 out=51,724,479 elapsed=118.3s

  [6481/20519] intraday_14982.csv.gz  in=289,066,165 out=51,736,652 elapsed=118.3s

  [6482/20519] intraday_14983.csv.gz  in=289,079,177 out=51,749,664 elapsed=118.3s

  [6483/20519] intraday_14984.csv.gz  in=289,090,310 out=51,760,797 elapsed=118.3s

  [6484/20519] intraday_14987.csv.gz  in=289,103,753 out=51,774,240 elapsed=118.4s

  [6485/20519] intraday_14985.csv.gz  in=289,113,141 out=51,783,628 elapsed=118.4s

  [6486/20519] intraday_14986.csv.gz  in=289,128,797 out=51,799,284 elapsed=118.4s

  [6487/20519] intraday_14988.csv.gz  in=289,139,710 out=51,810,197 elapsed=118.4s

  [6488/20519] intraday_14989.csv.gz  in=289,150,740 out=51,821,227 elapsed=118.4s

  [6489/20519] intraday_1499.csv.gz  in=289,166,913 out=51,821,227 elapsed=118.4s

  [6490/20519] intraday_14990.csv.gz  in=289,180,609 out=51,834,923 elapsed=118.4s

  [6491/20519] intraday_14992.csv.gz  in=289,193,722 out=51,848,036 elapsed=118.5s

  [6492/20519] intraday_14993.csv.gz  in=289,205,967 out=51,860,281 elapsed=118.5s

  [6493/20519] intraday_14991.csv.gz  in=289,217,978 out=51,872,292 elapsed=118.5s

  [6494/20519] intraday_14994.csv.gz  in=289,230,612 out=51,884,926 elapsed=118.5s

  [6495/20519] intraday_14995.csv.gz  in=289,241,329 out=51,895,643 elapsed=118.5s

  [6496/20519] intraday_14996.csv.gz  in=289,253,070 out=51,907,384 elapsed=118.5s

  [6497/20519] intraday_14998.csv.gz  in=289,265,411 out=51,919,725 elapsed=118.5s

  [6498/20519] intraday_14997.csv.gz  in=289,276,968 out=51,931,282 elapsed=118.6s

  [6499/20519] intraday_14999.csv.gz  in=289,289,738 out=51,944,052 elapsed=118.6s

  [6500/20519] intraday_1500.csv.gz  in=289,304,598 out=51,944,052 elapsed=118.6s

  [6501/20519] intraday_15001.csv.gz  in=289,317,774 out=51,957,228 elapsed=118.6s

  [6502/20519] intraday_15000.csv.gz  in=289,333,894 out=51,973,348 elapsed=118.6s

  [6503/20519] intraday_15002.csv.gz  in=289,344,404 out=51,983,858 elapsed=118.7s

  [6504/20519] intraday_15003.csv.gz  in=289,357,877 out=51,997,331 elapsed=118.7s

  [6505/20519] intraday_15004.csv.gz  in=289,371,081 out=52,010,535 elapsed=118.7s

  [6506/20519] intraday_15007.csv.gz  in=289,380,396 out=52,019,850 elapsed=118.7s

  [6507/20519] intraday_15005.csv.gz  in=289,392,757 out=52,032,211 elapsed=118.7s

  [6508/20519] intraday_15006.csv.gz  in=289,405,918 out=52,045,372 elapsed=118.7s

  [6509/20519] intraday_15008.csv.gz  in=289,417,980 out=52,057,434 elapsed=118.7s

  [6510/20519] intraday_15009.csv.gz  in=289,427,509 out=52,066,963 elapsed=118.8s

  [6511/20519] intraday_1501.csv.gz  in=289,442,595 out=52,066,963 elapsed=118.8s

  [6512/20519] intraday_15010.csv.gz  in=289,454,481 out=52,078,849 elapsed=118.8s

  [6513/20519] intraday_15012.csv.gz  in=289,469,639 out=52,094,007 elapsed=118.8s

  [6514/20519] intraday_15011.csv.gz  in=289,481,462 out=52,105,830 elapsed=118.8s

  [6515/20519] intraday_15014.csv.gz  in=289,495,667 out=52,120,035 elapsed=118.8s

  [6516/20519] intraday_15013.csv.gz  in=289,507,243 out=52,131,611 elapsed=118.8s

  [6517/20519] intraday_15015.csv.gz  in=289,517,790 out=52,142,158 elapsed=118.8s

  [6518/20519] intraday_15017.csv.gz  in=289,530,518 out=52,154,886 elapsed=118.9s

  [6519/20519] intraday_15016.csv.gz  in=289,541,569 out=52,165,937 elapsed=118.9s

  [6520/20519] intraday_15018.csv.gz  in=289,554,244 out=52,178,612 elapsed=118.9s

  [6521/20519] intraday_15019.csv.gz  in=289,566,159 out=52,190,527 elapsed=118.9s

  [6522/20519] intraday_1502.csv.gz  in=289,581,263 out=52,190,527 elapsed=118.9s

  [6523/20519] intraday_15020.csv.gz  in=289,592,181 out=52,201,445 elapsed=118.9s

  [6524/20519] intraday_15021.csv.gz  in=289,605,357 out=52,214,621 elapsed=118.9s

  [6525/20519] intraday_15022.csv.gz  in=289,617,439 out=52,226,703 elapsed=118.9s

  [6526/20519] intraday_15023.csv.gz  in=289,629,908 out=52,239,172 elapsed=119.0s

  [6527/20519] intraday_15024.csv.gz  in=289,642,575 out=52,251,839 elapsed=119.0s

  [6528/20519] intraday_15025.csv.gz  in=289,655,510 out=52,264,774 elapsed=119.0s

  [6529/20519] intraday_15026.csv.gz  in=289,667,692 out=52,276,956 elapsed=119.0s

  [6530/20519] intraday_15027.csv.gz  in=289,677,040 out=52,286,304 elapsed=119.0s

  [6531/20519] intraday_15028.csv.gz  in=289,690,362 out=52,299,626 elapsed=119.0s

  [6532/20519] intraday_15030.csv.gz  in=289,701,304 out=52,310,568 elapsed=119.0s

  [6533/20519] intraday_1503.csv.gz  in=289,716,354 out=52,310,568 elapsed=119.1s

  [6534/20519] intraday_15032.csv.gz  in=289,727,526 out=52,321,740 elapsed=119.1s

  [6535/20519] intraday_15029.csv.gz  in=289,761,284 out=52,344,982 elapsed=119.1s

  [6536/20519] intraday_15031.csv.gz  in=289,773,620 out=52,357,318 elapsed=119.1s

  [6537/20519] intraday_15033.csv.gz  in=289,783,766 out=52,367,464 elapsed=119.1s

  [6538/20519] intraday_15034.csv.gz  in=289,795,008 out=52,378,706 elapsed=119.2s

  [6539/20519] intraday_15035.csv.gz  in=289,808,418 out=52,392,116 elapsed=119.2s

  [6540/20519] intraday_15036.csv.gz  in=289,821,104 out=52,404,802 elapsed=119.2s

  [6541/20519] intraday_15037.csv.gz  in=289,834,343 out=52,418,041 elapsed=119.2s

  [6542/20519] intraday_15039.csv.gz  in=289,845,022 out=52,428,720 elapsed=119.2s

  [6543/20519] intraday_15040.csv.gz  in=289,855,623 out=52,439,321 elapsed=119.2s

  [6544/20519] intraday_1504.csv.gz  in=289,869,594 out=52,439,321 elapsed=119.2s

  [6545/20519] intraday_15038.csv.gz  in=289,882,441 out=52,452,168 elapsed=119.2s

  [6546/20519] intraday_15042.csv.gz  in=289,893,168 out=52,462,895 elapsed=119.3s

  [6547/20519] intraday_15043.csv.gz  in=289,906,791 out=52,476,518 elapsed=119.3s

  [6548/20519] intraday_15041.csv.gz  in=289,920,474 out=52,490,201 elapsed=119.3s

  [6549/20519] intraday_15045.csv.gz  in=289,930,178 out=52,499,905 elapsed=119.3s

  [6550/20519] intraday_15044.csv.gz  in=289,941,572 out=52,511,299 elapsed=119.3s

  [6551/20519] intraday_15046.csv.gz  in=289,951,728 out=52,521,455 elapsed=119.3s

  [6552/20519] intraday_15047.csv.gz  in=289,965,174 out=52,534,901 elapsed=119.4s

  [6553/20519] intraday_15048.csv.gz  in=289,975,908 out=52,545,635 elapsed=119.4s

  [6554/20519] intraday_15049.csv.gz  in=289,988,583 out=52,558,310 elapsed=119.4s

  [6555/20519] intraday_1505.csv.gz  in=290,005,098 out=52,558,310 elapsed=119.4s

  [6556/20519] intraday_15051.csv.gz  in=290,015,384 out=52,568,596 elapsed=119.4s

  [6557/20519] intraday_15053.csv.gz  in=290,028,761 out=52,581,973 elapsed=119.4s

  [6558/20519] intraday_15050.csv.gz  in=290,038,978 out=52,592,190 elapsed=119.4s

  [6559/20519] intraday_15052.csv.gz  in=290,052,901 out=52,606,113 elapsed=119.4s

  [6560/20519] intraday_15054.csv.gz  in=290,067,724 out=52,620,936 elapsed=119.4s

  [6561/20519] intraday_15055.csv.gz  in=290,080,504 out=52,633,716 elapsed=119.4s

  [6562/20519] intraday_15057.csv.gz  in=290,092,738 out=52,645,950 elapsed=119.5s

  [6563/20519] intraday_15056.csv.gz  in=290,105,451 out=52,658,663 elapsed=119.5s

  [6564/20519] intraday_15058.csv.gz  in=290,116,263 out=52,669,475 elapsed=119.5s

  [6565/20519] intraday_15059.csv.gz  in=290,130,544 out=52,683,756 elapsed=119.5s

  [6566/20519] intraday_1506.csv.gz  in=290,146,802 out=52,683,756 elapsed=119.5s

  [6567/20519] intraday_15060.csv.gz  in=290,158,156 out=52,695,110 elapsed=119.5s

  [6568/20519] intraday_15061.csv.gz  in=290,169,048 out=52,706,002 elapsed=119.5s

  [6569/20519] intraday_15062.csv.gz  in=290,182,508 out=52,719,462 elapsed=119.5s

  [6570/20519] intraday_15063.csv.gz  in=290,193,561 out=52,730,515 elapsed=119.5s

  [6571/20519] intraday_15064.csv.gz  in=290,205,400 out=52,742,354 elapsed=119.6s

  [6572/20519] intraday_15066.csv.gz  in=290,218,613 out=52,755,567 elapsed=119.6s

  [6573/20519] intraday_15067.csv.gz  in=290,230,467 out=52,767,421 elapsed=119.6s

  [6574/20519] intraday_15065.csv.gz  in=290,244,651 out=52,781,605 elapsed=119.6s

  [6575/20519] intraday_15068.csv.gz  in=290,256,867 out=52,793,821 elapsed=119.6s

  [6576/20519] intraday_1507.csv.gz  in=290,270,221 out=52,793,821 elapsed=119.6s

  [6577/20519] intraday_15069.csv.gz  in=290,281,780 out=52,805,380 elapsed=119.6s

  [6578/20519] intraday_15070.csv.gz  in=290,293,718 out=52,817,318 elapsed=119.7s

  [6579/20519] intraday_15071.csv.gz  in=290,307,497 out=52,831,097 elapsed=119.7s

  [6580/20519] intraday_15072.csv.gz  in=290,319,144 out=52,842,744 elapsed=119.7s

  [6581/20519] intraday_15073.csv.gz  in=290,331,745 out=52,855,345 elapsed=119.7s

  [6582/20519] intraday_15075.csv.gz  in=290,342,135 out=52,865,735 elapsed=119.7s

  [6583/20519] intraday_15074.csv.gz  in=290,355,798 out=52,879,398 elapsed=119.7s

  [6584/20519] intraday_15077.csv.gz  in=290,366,382 out=52,889,982 elapsed=119.8s

  [6585/20519] intraday_15076.csv.gz  in=290,381,787 out=52,905,387 elapsed=119.8s

  [6586/20519] intraday_15078.csv.gz  in=290,393,484 out=52,917,084 elapsed=119.8s

  [6587/20519] intraday_15079.csv.gz  in=290,406,744 out=52,930,344 elapsed=119.8s

  [6588/20519] intraday_1508.csv.gz  in=290,422,248 out=52,930,344 elapsed=119.8s

  [6589/20519] intraday_15080.csv.gz  in=290,437,252 out=52,945,348 elapsed=119.8s

  [6590/20519] intraday_15081.csv.gz  in=290,447,428 out=52,955,524 elapsed=119.9s

  [6591/20519] intraday_15082.csv.gz  in=290,462,181 out=52,970,277 elapsed=119.9s

  [6592/20519] intraday_15083.csv.gz  in=290,476,116 out=52,984,212 elapsed=119.9s

  [6593/20519] intraday_15084.csv.gz  in=290,488,262 out=52,996,358 elapsed=119.9s

  [6594/20519] intraday_15085.csv.gz  in=290,500,238 out=53,008,334 elapsed=119.9s

  [6595/20519] intraday_15086.csv.gz  in=290,517,258 out=53,025,354 elapsed=119.9s

  [6596/20519] intraday_15088.csv.gz  in=290,532,670 out=53,040,766 elapsed=120.0s

  [6597/20519] intraday_1509.csv.gz  in=290,544,389 out=53,040,766 elapsed=120.0s

  [6598/20519] intraday_15087.csv.gz  in=290,561,309 out=53,057,686 elapsed=120.0s

  [6599/20519] intraday_15089.csv.gz  in=290,575,953 out=53,072,330 elapsed=120.0s

  [6600/20519] intraday_15092.csv.gz  in=290,585,965 out=53,082,342 elapsed=120.0s

  [6601/20519] intraday_15090.csv.gz  in=290,597,276 out=53,093,653 elapsed=120.0s

  [6602/20519] intraday_15093.csv.gz  in=290,610,539 out=53,106,916 elapsed=120.0s

  [6603/20519] intraday_15091.csv.gz  in=290,622,757 out=53,119,134 elapsed=120.0s

  [6604/20519] intraday_15094.csv.gz  in=290,633,791 out=53,130,168 elapsed=120.1s

  [6605/20519] intraday_15095.csv.gz  in=290,646,220 out=53,142,597 elapsed=120.1s

  [6606/20519] intraday_15097.csv.gz  in=290,660,056 out=53,156,433 elapsed=120.1s

  [6607/20519] intraday_15096.csv.gz  in=290,672,741 out=53,169,118 elapsed=120.1s

  [6608/20519] intraday_15098.csv.gz  in=290,683,605 out=53,179,982 elapsed=120.1s

  [6609/20519] intraday_15099.csv.gz  in=290,695,252 out=53,191,629 elapsed=120.1s

  [6610/20519] intraday_1510.csv.gz  in=290,706,651 out=53,191,629 elapsed=120.1s

  [6611/20519] intraday_15101.csv.gz  in=290,720,286 out=53,205,264 elapsed=120.2s

  [6612/20519] intraday_15100.csv.gz  in=290,732,939 out=53,217,917 elapsed=120.2s

  [6613/20519] intraday_15102.csv.gz  in=290,744,719 out=53,229,697 elapsed=120.2s

  [6614/20519] intraday_15103.csv.gz  in=290,758,363 out=53,243,341 elapsed=120.2s

  [6615/20519] intraday_15105.csv.gz  in=290,770,499 out=53,255,477 elapsed=120.2s

  [6616/20519] intraday_15107.csv.gz  in=290,781,578 out=53,266,556 elapsed=120.2s

  [6617/20519] intraday_15104.csv.gz  in=290,796,254 out=53,281,232 elapsed=120.3s

  [6618/20519] intraday_15106.csv.gz  in=290,812,105 out=53,297,083 elapsed=120.3s

  [6619/20519] intraday_15108.csv.gz  in=290,825,919 out=53,310,897 elapsed=120.3s

  [6620/20519] intraday_15109.csv.gz  in=290,838,112 out=53,323,090 elapsed=120.3s

  [6621/20519] intraday_1511.csv.gz  in=290,852,745 out=53,323,090 elapsed=120.3s

  [6622/20519] intraday_15110.csv.gz  in=290,862,727 out=53,333,072 elapsed=120.3s

  [6623/20519] intraday_15112.csv.gz  in=290,870,158 out=53,340,503 elapsed=120.3s

  [6624/20519] intraday_15111.csv.gz  in=290,882,904 out=53,353,249 elapsed=120.3s

  [6625/20519] intraday_15115.csv.gz  in=290,897,111 out=53,367,456 elapsed=120.4s

  [6626/20519] intraday_15114.csv.gz  in=290,910,501 out=53,378,041 elapsed=120.4s

  [6627/20519] intraday_15116.csv.gz  in=290,923,357 out=53,390,897 elapsed=120.4s

  [6628/20519] intraday_15117.csv.gz  in=290,935,318 out=53,402,858 elapsed=120.4s

  [6629/20519] intraday_15113.csv.gz  in=290,988,188 out=53,427,553 elapsed=120.4s

  [6630/20519] intraday_15118.csv.gz  in=291,000,154 out=53,439,519 elapsed=120.4s

  [6631/20519] intraday_15119.csv.gz  in=291,011,341 out=53,450,706 elapsed=120.4s

  [6632/20519] intraday_1512.csv.gz  in=291,023,998 out=53,450,706 elapsed=120.4s

  [6633/20519] intraday_15120.csv.gz  in=291,038,942 out=53,465,650 elapsed=120.5s

  [6634/20519] intraday_15123.csv.gz  in=291,050,279 out=53,476,987 elapsed=120.5s

  [6635/20519] intraday_15122.csv.gz  in=291,060,731 out=53,487,439 elapsed=120.5s

  [6636/20519] intraday_15121.csv.gz  in=291,074,086 out=53,500,794 elapsed=120.5s

  [6637/20519] intraday_15124.csv.gz  in=291,085,980 out=53,512,688 elapsed=120.5s

  [6638/20519] intraday_15125.csv.gz  in=291,096,717 out=53,523,425 elapsed=120.5s

  [6639/20519] intraday_15126.csv.gz  in=291,110,570 out=53,537,278 elapsed=120.5s

  [6640/20519] intraday_15127.csv.gz  in=291,122,907 out=53,549,615 elapsed=120.5s

  [6641/20519] intraday_15128.csv.gz  in=291,135,581 out=53,562,289 elapsed=120.6s

  [6642/20519] intraday_15129.csv.gz  in=291,145,528 out=53,572,236 elapsed=120.6s

  [6643/20519] intraday_1513.csv.gz  in=291,156,408 out=53,572,236 elapsed=120.6s

  [6644/20519] intraday_15131.csv.gz  in=291,172,146 out=53,587,974 elapsed=120.7s

  [6645/20519] intraday_15132.csv.gz  in=291,184,236 out=53,600,064 elapsed=120.7s

  [6646/20519] intraday_15130.csv.gz  in=291,193,253 out=53,609,081 elapsed=120.7s

  [6647/20519] intraday_15134.csv.gz  in=291,205,932 out=53,621,760 elapsed=120.7s

  [6648/20519] intraday_15133.csv.gz  in=291,215,903 out=53,631,731 elapsed=120.7s

  [6649/20519] intraday_15135.csv.gz  in=291,228,025 out=53,643,853 elapsed=120.7s

  [6650/20519] intraday_15136.csv.gz  in=291,241,155 out=53,656,983 elapsed=120.7s

  [6651/20519] intraday_15138.csv.gz  in=291,253,704 out=53,669,532 elapsed=120.7s

  [6652/20519] intraday_15137.csv.gz  in=291,265,822 out=53,681,650 elapsed=120.7s

  [6653/20519] intraday_1514.csv.gz  in=291,274,669 out=53,681,650 elapsed=120.8s

  [6654/20519] intraday_15139.csv.gz  in=291,290,839 out=53,695,626 elapsed=120.8s

  [6655/20519] intraday_15140.csv.gz  in=291,301,579 out=53,706,366 elapsed=120.8s

  [6656/20519] intraday_15141.csv.gz  in=291,312,872 out=53,717,659 elapsed=120.8s

  [6657/20519] intraday_15142.csv.gz  in=291,323,942 out=53,728,729 elapsed=120.8s

  [6658/20519] intraday_15143.csv.gz  in=291,336,206 out=53,740,993 elapsed=120.8s

  [6659/20519] intraday_15144.csv.gz  in=291,348,658 out=53,753,445 elapsed=120.8s

  [6660/20519] intraday_15145.csv.gz  in=291,364,158 out=53,768,945 elapsed=120.8s

  [6661/20519] intraday_15147.csv.gz  in=291,374,610 out=53,779,397 elapsed=120.8s

  [6662/20519] intraday_15146.csv.gz  in=291,386,687 out=53,791,474 elapsed=120.8s

  [6663/20519] intraday_15148.csv.gz  in=291,399,607 out=53,804,394 elapsed=120.9s

  [6664/20519] intraday_1515.csv.gz  in=291,410,466 out=53,804,394 elapsed=120.9s

  [6665/20519] intraday_15149.csv.gz  in=291,423,609 out=53,817,537 elapsed=120.9s

  [6666/20519] intraday_15150.csv.gz  in=291,435,952 out=53,829,880 elapsed=120.9s

  [6667/20519] intraday_15151.csv.gz  in=291,448,687 out=53,842,615 elapsed=120.9s

  [6668/20519] intraday_15152.csv.gz  in=291,459,891 out=53,853,819 elapsed=120.9s

  [6669/20519] intraday_15154.csv.gz  in=291,470,061 out=53,863,989 elapsed=120.9s

  [6670/20519] intraday_15153.csv.gz  in=291,479,468 out=53,873,396 elapsed=121.0s

  [6671/20519] intraday_15155.csv.gz  in=291,490,813 out=53,884,741 elapsed=121.0s

  [6672/20519] intraday_15156.csv.gz  in=291,503,171 out=53,897,099 elapsed=121.0s

  [6673/20519] intraday_15157.csv.gz  in=291,516,577 out=53,910,505 elapsed=121.0s

  [6674/20519] intraday_1516.csv.gz  in=291,522,643 out=53,910,505 elapsed=121.0s

  [6675/20519] intraday_15159.csv.gz  in=291,535,523 out=53,923,385 elapsed=121.0s

  [6676/20519] intraday_15158.csv.gz  in=291,548,709 out=53,936,571 elapsed=121.0s

  [6677/20519] intraday_15160.csv.gz  in=291,559,834 out=53,947,696 elapsed=121.0s

  [6678/20519] intraday_15161.csv.gz  in=291,571,455 out=53,959,317 elapsed=121.0s

  [6679/20519] intraday_15162.csv.gz  in=291,584,335 out=53,972,197 elapsed=121.1s

  [6680/20519] intraday_15163.csv.gz  in=291,594,994 out=53,982,856 elapsed=121.1s

  [6681/20519] intraday_15164.csv.gz  in=291,607,002 out=53,994,864 elapsed=121.1s

  [6682/20519] intraday_15165.csv.gz  in=291,616,940 out=54,004,802 elapsed=121.1s

  [6683/20519] intraday_15166.csv.gz  in=291,631,914 out=54,019,776 elapsed=121.1s

  [6684/20519] intraday_15167.csv.gz  in=291,643,946 out=54,031,808 elapsed=121.1s

  [6685/20519] intraday_15169.csv.gz  in=291,658,108 out=54,045,970 elapsed=121.1s

  [6686/20519] intraday_15168.csv.gz  in=291,669,244 out=54,057,106 elapsed=121.1s

  [6687/20519] intraday_1517.csv.gz  in=291,684,496 out=54,057,106 elapsed=121.1s

  [6688/20519] intraday_15170.csv.gz  in=291,695,813 out=54,068,423 elapsed=121.2s

  [6689/20519] intraday_15172.csv.gz  in=291,707,354 out=54,079,964 elapsed=121.2s

  [6690/20519] intraday_15171.csv.gz  in=291,719,301 out=54,091,911 elapsed=121.2s

  [6691/20519] intraday_15173.csv.gz  in=291,730,996 out=54,103,606 elapsed=121.2s

  [6692/20519] intraday_15174.csv.gz  in=291,744,347 out=54,116,957 elapsed=121.2s

  [6693/20519] intraday_15175.csv.gz  in=291,755,865 out=54,128,475 elapsed=121.2s

  [6694/20519] intraday_15176.csv.gz  in=291,765,560 out=54,138,170 elapsed=121.2s

  [6695/20519] intraday_15177.csv.gz  in=291,777,832 out=54,150,442 elapsed=121.2s

  [6696/20519] intraday_15179.csv.gz  in=291,790,713 out=54,163,323 elapsed=121.2s

  [6697/20519] intraday_1518.csv.gz  in=291,804,827 out=54,163,323 elapsed=121.2s

  [6698/20519] intraday_15178.csv.gz  in=291,813,880 out=54,172,376 elapsed=121.2s

  [6699/20519] intraday_15181.csv.gz  in=291,825,850 out=54,184,346 elapsed=121.3s

  [6700/20519] intraday_15180.csv.gz  in=291,839,846 out=54,198,342 elapsed=121.3s

  [6701/20519] intraday_15182.csv.gz  in=291,851,662 out=54,210,158 elapsed=121.3s

  [6702/20519] intraday_15184.csv.gz  in=291,860,167 out=54,218,663 elapsed=121.3s

  [6703/20519] intraday_15183.csv.gz  in=291,873,532 out=54,232,028 elapsed=121.3s

  [6704/20519] intraday_15185.csv.gz  in=291,886,664 out=54,245,160 elapsed=121.3s

  [6705/20519] intraday_15187.csv.gz  in=291,898,981 out=54,257,477 elapsed=121.4s

  [6706/20519] intraday_15186.csv.gz  in=291,910,298 out=54,268,794 elapsed=121.4s

  [6707/20519] intraday_15188.csv.gz  in=291,919,938 out=54,278,434 elapsed=121.4s

  [6708/20519] intraday_15189.csv.gz  in=291,933,077 out=54,291,573 elapsed=121.4s

  [6709/20519] intraday_1519.csv.gz  in=291,945,008 out=54,291,573 elapsed=121.4s

  [6710/20519] intraday_15190.csv.gz  in=291,953,943 out=54,300,508 elapsed=121.4s

  [6711/20519] intraday_15191.csv.gz  in=291,965,858 out=54,312,423 elapsed=121.4s

  [6712/20519] intraday_15192.csv.gz  in=291,978,231 out=54,324,796 elapsed=121.4s

  [6713/20519] intraday_15193.csv.gz  in=291,989,455 out=54,336,020 elapsed=121.4s

  [6714/20519] intraday_15194.csv.gz  in=292,000,788 out=54,347,353 elapsed=121.5s

  [6715/20519] intraday_15196.csv.gz  in=292,012,279 out=54,358,844 elapsed=121.5s

  [6716/20519] intraday_15197.csv.gz  in=292,024,279 out=54,370,844 elapsed=121.5s

  [6717/20519] intraday_15195.csv.gz  in=292,034,145 out=54,380,710 elapsed=121.5s

  [6718/20519] intraday_1520.csv.gz  in=292,046,238 out=54,380,710 elapsed=121.5s

  [6719/20519] intraday_15198.csv.gz  in=292,062,887 out=54,397,359 elapsed=121.5s

  [6720/20519] intraday_15199.csv.gz  in=292,074,435 out=54,408,907 elapsed=121.5s

  [6721/20519] intraday_15200.csv.gz  in=292,088,774 out=54,423,246 elapsed=121.5s

  [6722/20519] intraday_15201.csv.gz  in=292,099,542 out=54,434,014 elapsed=121.6s

  [6723/20519] intraday_15202.csv.gz  in=292,113,129 out=54,447,601 elapsed=121.6s

  [6724/20519] intraday_15203.csv.gz  in=292,123,328 out=54,457,800 elapsed=121.6s

  [6725/20519] intraday_15204.csv.gz  in=292,138,184 out=54,472,656 elapsed=121.6s

  [6726/20519] intraday_15205.csv.gz  in=292,148,002 out=54,482,474 elapsed=121.6s

  [6727/20519] intraday_15207.csv.gz  in=292,160,737 out=54,494,626 elapsed=121.7s

  [6728/20519] intraday_15206.csv.gz  in=292,173,296 out=54,507,185 elapsed=121.7s

  [6729/20519] intraday_15208.csv.gz  in=292,183,919 out=54,517,808 elapsed=121.7s

  [6730/20519] intraday_15209.csv.gz  in=292,197,113 out=54,531,002 elapsed=121.7s

  [6731/20519] intraday_1521.csv.gz  in=292,210,724 out=54,531,002 elapsed=121.7s

  [6732/20519] intraday_15210.csv.gz  in=292,223,116 out=54,543,394 elapsed=121.7s

  [6733/20519] intraday_15211.csv.gz  in=292,236,030 out=54,556,308 elapsed=121.8s

  [6734/20519] intraday_15213.csv.gz  in=292,247,767 out=54,568,045 elapsed=121.8s

  [6735/20519] intraday_15212.csv.gz  in=292,258,239 out=54,578,517 elapsed=121.8s

  [6736/20519] intraday_15214.csv.gz  in=292,271,402 out=54,591,680 elapsed=121.8s

  [6737/20519] intraday_15215.csv.gz  in=292,284,126 out=54,604,404 elapsed=121.8s

  [6738/20519] intraday_15217.csv.gz  in=292,295,795 out=54,616,073 elapsed=121.8s

  [6739/20519] intraday_15216.csv.gz  in=292,308,552 out=54,628,830 elapsed=121.8s

  [6740/20519] intraday_15219.csv.gz  in=292,320,121 out=54,640,399 elapsed=121.9s

  [6741/20519] intraday_15218.csv.gz  in=292,332,212 out=54,652,490 elapsed=121.9s

  [6742/20519] intraday_1522.csv.gz  in=292,345,791 out=54,652,490 elapsed=121.9s

  [6743/20519] intraday_15220.csv.gz  in=292,358,465 out=54,665,164 elapsed=121.9s

  [6744/20519] intraday_15221.csv.gz  in=292,372,498 out=54,679,197 elapsed=121.9s

  [6745/20519] intraday_15222.csv.gz  in=292,383,934 out=54,690,633 elapsed=121.9s

  [6746/20519] intraday_15223.csv.gz  in=292,396,937 out=54,703,636 elapsed=121.9s

  [6747/20519] intraday_15224.csv.gz  in=292,409,367 out=54,716,066 elapsed=121.9s

  [6748/20519] intraday_15225.csv.gz  in=292,421,966 out=54,728,665 elapsed=121.9s

  [6749/20519] intraday_15226.csv.gz  in=292,436,900 out=54,743,006 elapsed=122.0s

  [6750/20519] intraday_15228.csv.gz  in=292,450,743 out=54,756,849 elapsed=122.0s

  [6751/20519] intraday_15229.csv.gz  in=292,462,501 out=54,768,607 elapsed=122.0s

  [6752/20519] intraday_15227.csv.gz  in=292,475,370 out=54,781,476 elapsed=122.0s

  [6753/20519] intraday_1523.csv.gz  in=292,487,894 out=54,781,476 elapsed=122.0s

  [6754/20519] intraday_15230.csv.gz  in=292,500,855 out=54,794,437 elapsed=122.0s

  [6755/20519] intraday_15232.csv.gz  in=292,513,742 out=54,807,324 elapsed=122.0s

  [6756/20519] intraday_15233.csv.gz  in=292,530,278 out=54,823,860 elapsed=122.1s

  [6757/20519] intraday_15234.csv.gz  in=292,540,956 out=54,834,538 elapsed=122.1s

  [6758/20519] intraday_15231.csv.gz  in=292,558,205 out=54,851,787 elapsed=122.1s

  [6759/20519] intraday_15235.csv.gz  in=292,570,940 out=54,864,522 elapsed=122.1s

  [6760/20519] intraday_15236.csv.gz  in=292,581,299 out=54,874,881 elapsed=122.1s

  [6761/20519] intraday_15237.csv.gz  in=292,593,243 out=54,886,825 elapsed=122.1s

  [6762/20519] intraday_15238.csv.gz  in=292,603,686 out=54,897,268 elapsed=122.2s

  [6763/20519] intraday_1524.csv.gz  in=292,616,079 out=54,897,268 elapsed=122.2s

  [6764/20519] intraday_15240.csv.gz  in=292,627,473 out=54,908,662 elapsed=122.2s

  [6765/20519] intraday_15239.csv.gz  in=292,640,124 out=54,921,313 elapsed=122.2s

  [6766/20519] intraday_15241.csv.gz  in=292,655,220 out=54,936,409 elapsed=122.2s

  [6767/20519] intraday_15242.csv.gz  in=292,664,935 out=54,946,124 elapsed=122.2s

  [6768/20519] intraday_15244.csv.gz  in=292,676,849 out=54,958,038 elapsed=122.2s

  [6769/20519] intraday_15245.csv.gz  in=292,690,440 out=54,971,629 elapsed=122.3s

  [6770/20519] intraday_15243.csv.gz  in=292,701,410 out=54,982,599 elapsed=122.3s

  [6771/20519] intraday_15246.csv.gz  in=292,711,545 out=54,992,734 elapsed=122.3s

  [6772/20519] intraday_15247.csv.gz  in=292,724,466 out=55,005,655 elapsed=122.3s

  [6773/20519] intraday_15248.csv.gz  in=292,739,880 out=55,021,069 elapsed=122.3s

  [6774/20519] intraday_15249.csv.gz  in=292,753,690 out=55,034,879 elapsed=122.3s

  [6775/20519] intraday_1525.csv.gz  in=292,767,171 out=55,034,879 elapsed=122.3s

  [6776/20519] intraday_15250.csv.gz  in=292,780,536 out=55,048,244 elapsed=122.3s

  [6777/20519] intraday_15251.csv.gz  in=292,793,008 out=55,060,716 elapsed=122.3s

  [6778/20519] intraday_15252.csv.gz  in=292,804,254 out=55,071,962 elapsed=122.3s

  [6779/20519] intraday_15253.csv.gz  in=292,816,428 out=55,084,136 elapsed=122.4s

  [6780/20519] intraday_15255.csv.gz  in=292,828,281 out=55,095,989 elapsed=122.4s

  [6781/20519] intraday_15256.csv.gz  in=292,837,750 out=55,105,458 elapsed=122.4s

  [6782/20519] intraday_15254.csv.gz  in=292,847,950 out=55,115,658 elapsed=122.4s

  [6783/20519] intraday_15257.csv.gz  in=292,856,504 out=55,124,212 elapsed=122.4s

  [6784/20519] intraday_15258.csv.gz  in=292,868,464 out=55,136,172 elapsed=122.4s

  [6785/20519] intraday_1526.csv.gz  in=292,882,422 out=55,136,172 elapsed=122.4s

  [6786/20519] intraday_15260.csv.gz  in=292,894,800 out=55,148,550 elapsed=122.5s

  [6787/20519] intraday_15259.csv.gz  in=292,909,628 out=55,163,378 elapsed=122.5s

  [6788/20519] intraday_15262.csv.gz  in=292,922,175 out=55,175,925 elapsed=122.5s

  [6789/20519] intraday_15261.csv.gz  in=292,935,081 out=55,188,831 elapsed=122.5s

  [6790/20519] intraday_15263.csv.gz  in=292,946,629 out=55,200,379 elapsed=122.5s

  [6791/20519] intraday_15264.csv.gz  in=292,961,825 out=55,215,575 elapsed=122.5s

  [6792/20519] intraday_15265.csv.gz  in=292,974,443 out=55,228,193 elapsed=122.6s

  [6793/20519] intraday_15268.csv.gz  in=292,986,537 out=55,240,287 elapsed=122.6s

  [6794/20519] intraday_15266.csv.gz  in=292,997,900 out=55,251,650 elapsed=122.6s

  [6795/20519] intraday_15267.csv.gz  in=293,010,149 out=55,263,899 elapsed=122.6s

  [6796/20519] intraday_15269.csv.gz  in=293,020,903 out=55,274,653 elapsed=122.6s

  [6797/20519] intraday_1527.csv.gz  in=293,029,941 out=55,274,653 elapsed=122.6s

  [6798/20519] intraday_15270.csv.gz  in=293,043,783 out=55,288,495 elapsed=122.6s

  [6799/20519] intraday_15271.csv.gz  in=293,057,875 out=55,302,587 elapsed=122.6s

  [6800/20519] intraday_15273.csv.gz  in=293,067,896 out=55,312,608 elapsed=122.7s

  [6801/20519] intraday_15272.csv.gz  in=293,080,290 out=55,325,002 elapsed=122.7s

  [6802/20519] intraday_15274.csv.gz  in=293,089,944 out=55,334,656 elapsed=122.7s

  [6803/20519] intraday_15275.csv.gz  in=293,105,125 out=55,349,837 elapsed=122.8s

  [6804/20519] intraday_15276.csv.gz  in=293,118,541 out=55,363,253 elapsed=122.8s

  [6805/20519] intraday_15277.csv.gz  in=293,128,322 out=55,373,034 elapsed=122.8s

  [6806/20519] intraday_15278.csv.gz  in=293,141,144 out=55,385,856 elapsed=122.8s

  [6807/20519] intraday_1528.csv.gz  in=293,152,902 out=55,385,856 elapsed=122.8s

  [6808/20519] intraday_15279.csv.gz  in=293,165,414 out=55,398,368 elapsed=122.8s

  [6809/20519] intraday_15280.csv.gz  in=293,178,903 out=55,411,857 elapsed=122.8s

  [6810/20519] intraday_15281.csv.gz  in=293,190,467 out=55,423,421 elapsed=122.8s

  [6811/20519] intraday_15282.csv.gz  in=293,202,486 out=55,435,440 elapsed=122.8s

  [6812/20519] intraday_15284.csv.gz  in=293,214,858 out=55,447,812 elapsed=122.8s

  [6813/20519] intraday_15283.csv.gz  in=293,226,392 out=55,459,346 elapsed=122.8s

  [6814/20519] intraday_15285.csv.gz  in=293,237,651 out=55,470,605 elapsed=122.9s

  [6815/20519] intraday_15286.csv.gz  in=293,248,211 out=55,481,165 elapsed=122.9s

  [6816/20519] intraday_15287.csv.gz  in=293,259,777 out=55,492,731 elapsed=122.9s

  [6817/20519] intraday_15288.csv.gz  in=293,273,374 out=55,506,328 elapsed=122.9s

  [6818/20519] intraday_1529.csv.gz  in=293,287,596 out=55,506,328 elapsed=122.9s

  [6819/20519] intraday_15289.csv.gz  in=293,305,261 out=55,523,726 elapsed=122.9s

  [6820/20519] intraday_15290.csv.gz  in=293,315,550 out=55,534,015 elapsed=122.9s

  [6821/20519] intraday_15291.csv.gz  in=293,326,773 out=55,545,238 elapsed=123.0s

  [6822/20519] intraday_15292.csv.gz  in=293,339,365 out=55,557,830 elapsed=123.0s

  [6823/20519] intraday_15294.csv.gz  in=293,350,974 out=55,569,439 elapsed=123.0s

  [6824/20519] intraday_15293.csv.gz  in=293,382,132 out=55,591,585 elapsed=123.0s

  [6825/20519] intraday_15296.csv.gz  in=293,393,837 out=55,603,290 elapsed=123.0s

  [6826/20519] intraday_15295.csv.gz  in=293,406,847 out=55,616,300 elapsed=123.0s

  [6827/20519] intraday_15298.csv.gz  in=293,416,253 out=55,625,706 elapsed=123.0s

  [6828/20519] intraday_15297.csv.gz  in=293,426,369 out=55,635,822 elapsed=123.0s

  [6829/20519] intraday_15299.csv.gz  in=293,437,009 out=55,646,462 elapsed=123.0s

  [6830/20519] intraday_1530.csv.gz  in=293,447,874 out=55,646,462 elapsed=123.0s

  [6831/20519] intraday_15301.csv.gz  in=293,461,806 out=55,660,394 elapsed=123.1s

  [6832/20519] intraday_15303.csv.gz  in=293,475,019 out=55,673,607 elapsed=123.1s

  [6833/20519] intraday_15300.csv.gz  in=293,486,825 out=55,685,413 elapsed=123.1s

  [6834/20519] intraday_15304.csv.gz  in=293,497,949 out=55,696,537 elapsed=123.1s

  [6835/20519] intraday_15302.csv.gz  in=293,510,771 out=55,709,359 elapsed=123.1s

  [6836/20519] intraday_15305.csv.gz  in=293,522,168 out=55,720,756 elapsed=123.1s

  [6837/20519] intraday_15306.csv.gz  in=293,535,237 out=55,733,825 elapsed=123.2s

  [6838/20519] intraday_15308.csv.gz  in=293,546,585 out=55,745,173 elapsed=123.2s

  [6839/20519] intraday_1531.csv.gz  in=293,556,409 out=55,745,173 elapsed=123.2s

  [6840/20519] intraday_15309.csv.gz  in=293,566,651 out=55,755,415 elapsed=123.2s

  [6841/20519] intraday_15307.csv.gz  in=293,577,707 out=55,766,471 elapsed=123.2s

  [6842/20519] intraday_15310.csv.gz  in=293,592,745 out=55,781,509 elapsed=123.2s

  [6843/20519] intraday_15312.csv.gz  in=293,604,941 out=55,793,705 elapsed=123.2s

  [6844/20519] intraday_15311.csv.gz  in=293,616,927 out=55,805,691 elapsed=123.3s

  [6845/20519] intraday_15314.csv.gz  in=293,629,101 out=55,817,865 elapsed=123.3s

  [6846/20519] intraday_15313.csv.gz  in=293,643,928 out=55,832,692 elapsed=123.3s

  [6847/20519] intraday_15315.csv.gz  in=293,654,723 out=55,843,487 elapsed=123.3s

  [6848/20519] intraday_15316.csv.gz  in=293,666,619 out=55,855,383 elapsed=123.3s

  [6849/20519] intraday_15317.csv.gz  in=293,679,875 out=55,868,639 elapsed=123.3s

  [6850/20519] intraday_15318.csv.gz  in=293,692,723 out=55,881,487 elapsed=123.3s

  [6851/20519] intraday_15319.csv.gz  in=293,703,752 out=55,892,516 elapsed=123.4s

  [6852/20519] intraday_1532.csv.gz  in=293,717,456 out=55,892,516 elapsed=123.4s

  [6853/20519] intraday_15320.csv.gz  in=293,727,728 out=55,902,788 elapsed=123.4s

  [6854/20519] intraday_15321.csv.gz  in=293,739,939 out=55,914,999 elapsed=123.4s

  [6855/20519] intraday_15322.csv.gz  in=293,749,667 out=55,924,727 elapsed=123.4s

  [6856/20519] intraday_15324.csv.gz  in=293,762,575 out=55,937,635 elapsed=123.4s

  [6857/20519] intraday_15323.csv.gz  in=293,776,744 out=55,951,804 elapsed=123.4s

  [6858/20519] intraday_15325.csv.gz  in=293,789,169 out=55,964,229 elapsed=123.5s

  [6859/20519] intraday_15326.csv.gz  in=293,801,111 out=55,976,171 elapsed=123.5s

  [6860/20519] intraday_15327.csv.gz  in=293,812,783 out=55,987,843 elapsed=123.5s

  [6861/20519] intraday_15328.csv.gz  in=293,821,518 out=55,996,578 elapsed=123.5s

  [6862/20519] intraday_1533.csv.gz  in=293,832,971 out=55,996,578 elapsed=123.5s

  [6863/20519] intraday_15329.csv.gz  in=293,845,496 out=56,009,103 elapsed=123.5s

  [6864/20519] intraday_15330.csv.gz  in=293,856,834 out=56,020,441 elapsed=123.5s

  [6865/20519] intraday_15332.csv.gz  in=293,867,023 out=56,030,630 elapsed=123.5s

  [6866/20519] intraday_15333.csv.gz  in=293,879,636 out=56,043,243 elapsed=123.6s

  [6867/20519] intraday_15334.csv.gz  in=293,892,779 out=56,055,974 elapsed=123.6s

  [6868/20519] intraday_15331.csv.gz  in=293,905,103 out=56,068,298 elapsed=123.6s

  [6869/20519] intraday_15335.csv.gz  in=293,916,846 out=56,080,041 elapsed=123.6s

  [6870/20519] intraday_15336.csv.gz  in=293,929,904 out=56,093,099 elapsed=123.6s

  [6871/20519] intraday_15338.csv.gz  in=293,941,254 out=56,104,449 elapsed=123.7s

  [6872/20519] intraday_1534.csv.gz  in=293,953,458 out=56,104,449 elapsed=123.7s

  [6873/20519] intraday_15337.csv.gz  in=293,965,173 out=56,116,164 elapsed=123.7s

  [6874/20519] intraday_15340.csv.gz  in=293,976,265 out=56,127,256 elapsed=123.7s

  [6875/20519] intraday_15339.csv.gz  in=293,987,214 out=56,138,205 elapsed=123.7s

  [6876/20519] intraday_15341.csv.gz  in=293,999,342 out=56,150,333 elapsed=123.8s

  [6877/20519] intraday_15343.csv.gz  in=294,010,783 out=56,161,774 elapsed=123.8s

  [6878/20519] intraday_15345.csv.gz  in=294,021,146 out=56,172,137 elapsed=123.8s

  [6879/20519] intraday_15342.csv.gz  in=294,039,001 out=56,189,992 elapsed=123.9s

  [6880/20519] intraday_15346.csv.gz  in=294,051,965 out=56,202,956 elapsed=123.9s

  [6881/20519] intraday_15344.csv.gz  in=294,068,420 out=56,219,411 elapsed=123.9s

  [6882/20519] intraday_15347.csv.gz  in=294,078,480 out=56,229,471 elapsed=123.9s

  [6883/20519] intraday_15348.csv.gz  in=294,094,114 out=56,245,105 elapsed=123.9s

  [6884/20519] intraday_1535.csv.gz  in=294,105,970 out=56,245,105 elapsed=123.9s

  [6885/20519] intraday_15349.csv.gz  in=294,116,566 out=56,255,701 elapsed=123.9s

  [6886/20519] intraday_15350.csv.gz  in=294,128,411 out=56,267,546 elapsed=123.9s

  [6887/20519] intraday_15352.csv.gz  in=294,140,148 out=56,279,283 elapsed=123.9s

  [6888/20519] intraday_15351.csv.gz  in=294,150,611 out=56,289,746 elapsed=123.9s

  [6889/20519] intraday_15353.csv.gz  in=294,163,268 out=56,302,403 elapsed=124.0s

  [6890/20519] intraday_15356.csv.gz  in=294,173,939 out=56,313,074 elapsed=124.0s

  [6891/20519] intraday_15354.csv.gz  in=294,189,768 out=56,328,020 elapsed=124.0s

  [6892/20519] intraday_15355.csv.gz  in=294,201,840 out=56,340,092 elapsed=124.0s

  [6893/20519] intraday_15357.csv.gz  in=294,213,164 out=56,351,416 elapsed=124.0s

  [6894/20519] intraday_1536.csv.gz  in=294,224,589 out=56,351,416 elapsed=124.0s

  [6895/20519] intraday_15358.csv.gz  in=294,236,685 out=56,363,512 elapsed=124.1s

  [6896/20519] intraday_15359.csv.gz  in=294,249,524 out=56,376,351 elapsed=124.1s

  [6897/20519] intraday_15360.csv.gz  in=294,262,789 out=56,389,616 elapsed=124.1s

  [6898/20519] intraday_15361.csv.gz  in=294,273,901 out=56,400,728 elapsed=124.1s

  [6899/20519] intraday_15363.csv.gz  in=294,284,078 out=56,410,905 elapsed=124.1s

  [6900/20519] intraday_15362.csv.gz  in=294,296,387 out=56,423,214 elapsed=124.1s

  [6901/20519] intraday_15364.csv.gz  in=294,310,008 out=56,436,835 elapsed=124.1s

  [6902/20519] intraday_15365.csv.gz  in=294,321,556 out=56,448,383 elapsed=124.2s

  [6903/20519] intraday_15366.csv.gz  in=294,332,966 out=56,459,793 elapsed=124.2s

  [6904/20519] intraday_15367.csv.gz  in=294,346,118 out=56,472,945 elapsed=124.2s

  [6905/20519] intraday_15368.csv.gz  in=294,358,936 out=56,485,763 elapsed=124.2s

  [6906/20519] intraday_15369.csv.gz  in=294,371,517 out=56,498,344 elapsed=124.2s

  [6907/20519] intraday_1537.csv.gz  in=294,383,551 out=56,498,344 elapsed=124.2s

  [6908/20519] intraday_15371.csv.gz  in=294,396,183 out=56,510,976 elapsed=124.2s

  [6909/20519] intraday_15370.csv.gz  in=294,421,904 out=56,529,085 elapsed=124.2s

  [6910/20519] intraday_15373.csv.gz  in=294,434,180 out=56,541,361 elapsed=124.3s

  [6911/20519] intraday_15372.csv.gz  in=294,447,637 out=56,554,818 elapsed=124.3s

  [6912/20519] intraday_15374.csv.gz  in=294,461,176 out=56,568,357 elapsed=124.3s

  [6913/20519] intraday_15376.csv.gz  in=294,472,902 out=56,580,083 elapsed=124.3s

  [6914/20519] intraday_15375.csv.gz  in=294,491,975 out=56,599,156 elapsed=124.3s

  [6915/20519] intraday_15377.csv.gz  in=294,508,593 out=56,615,774 elapsed=124.3s

  [6916/20519] intraday_15378.csv.gz  in=294,520,082 out=56,627,263 elapsed=124.3s

  [6917/20519] intraday_15379.csv.gz  in=294,532,749 out=56,639,930 elapsed=124.3s

  [6918/20519] intraday_1538.csv.gz  in=294,544,619 out=56,639,930 elapsed=124.4s

  [6919/20519] intraday_15381.csv.gz  in=294,556,968 out=56,652,279 elapsed=124.4s

  [6920/20519] intraday_15380.csv.gz  in=294,567,238 out=56,662,549 elapsed=124.4s

  [6921/20519] intraday_15382.csv.gz  in=294,577,788 out=56,673,099 elapsed=124.4s

  [6922/20519] intraday_15384.csv.gz  in=294,588,786 out=56,684,097 elapsed=124.4s

  [6923/20519] intraday_15383.csv.gz  in=294,601,900 out=56,697,211 elapsed=124.4s

  [6924/20519] intraday_15385.csv.gz  in=294,618,232 out=56,713,543 elapsed=124.4s

  [6925/20519] intraday_15386.csv.gz  in=294,628,824 out=56,724,135 elapsed=124.4s

  [6926/20519] intraday_15387.csv.gz  in=294,640,051 out=56,735,362 elapsed=124.5s

  [6927/20519] intraday_15388.csv.gz  in=294,651,400 out=56,746,711 elapsed=124.5s

  [6928/20519] intraday_15389.csv.gz  in=294,664,857 out=56,760,168 elapsed=124.5s

  [6929/20519] intraday_1539.csv.gz  in=294,677,034 out=56,760,168 elapsed=124.5s

  [6930/20519] intraday_15390.csv.gz  in=294,687,129 out=56,770,263 elapsed=124.5s

  [6931/20519] intraday_15391.csv.gz  in=294,699,391 out=56,782,525 elapsed=124.5s

  [6932/20519] intraday_15392.csv.gz  in=294,713,652 out=56,796,786 elapsed=124.5s

  [6933/20519] intraday_15394.csv.gz  in=294,727,650 out=56,810,784 elapsed=124.6s

  [6934/20519] intraday_15393.csv.gz  in=294,740,646 out=56,823,780 elapsed=124.6s

  [6935/20519] intraday_15395.csv.gz  in=294,752,658 out=56,835,792 elapsed=124.6s

  [6936/20519] intraday_15396.csv.gz  in=294,763,771 out=56,846,905 elapsed=124.6s

  [6937/20519] intraday_15397.csv.gz  in=294,776,252 out=56,859,386 elapsed=124.6s

  [6938/20519] intraday_15398.csv.gz  in=294,786,086 out=56,869,220 elapsed=124.6s

  [6939/20519] intraday_15399.csv.gz  in=294,798,334 out=56,881,468 elapsed=124.6s

  [6940/20519] intraday_1540.csv.gz  in=294,812,419 out=56,881,468 elapsed=124.7s

  [6941/20519] intraday_15400.csv.gz  in=294,822,585 out=56,891,634 elapsed=124.7s

  [6942/20519] intraday_15402.csv.gz  in=294,834,317 out=56,903,366 elapsed=124.7s

  [6943/20519] intraday_15401.csv.gz  in=294,841,600 out=56,910,649 elapsed=124.7s

  [6944/20519] intraday_15403.csv.gz  in=294,856,539 out=56,925,588 elapsed=124.7s

  [6945/20519] intraday_15404.csv.gz  in=294,868,939 out=56,937,988 elapsed=124.7s

  [6946/20519] intraday_15405.csv.gz  in=294,881,381 out=56,950,430 elapsed=124.7s

  [6947/20519] intraday_15406.csv.gz  in=294,891,890 out=56,960,823 elapsed=124.8s

  [6948/20519] intraday_15408.csv.gz  in=294,906,595 out=56,975,528 elapsed=124.8s

  [6949/20519] intraday_15409.csv.gz  in=294,918,284 out=56,987,217 elapsed=124.8s

  [6950/20519] intraday_1541.csv.gz  in=294,929,110 out=56,987,217 elapsed=124.8s

  [6951/20519] intraday_15407.csv.gz  in=294,942,373 out=57,000,480 elapsed=124.8s

  [6952/20519] intraday_15410.csv.gz  in=294,954,351 out=57,012,458 elapsed=124.8s

  [6953/20519] intraday_15412.csv.gz  in=294,965,614 out=57,023,721 elapsed=124.9s

  [6954/20519] intraday_15411.csv.gz  in=294,977,042 out=57,035,149 elapsed=124.9s

  [6955/20519] intraday_15413.csv.gz  in=294,988,133 out=57,046,240 elapsed=124.9s

  [6956/20519] intraday_15414.csv.gz  in=295,000,737 out=57,058,844 elapsed=124.9s

  [6957/20519] intraday_15415.csv.gz  in=295,013,413 out=57,071,520 elapsed=124.9s

  [6958/20519] intraday_15417.csv.gz  in=295,022,420 out=57,080,527 elapsed=124.9s

  [6959/20519] intraday_15416.csv.gz  in=295,036,432 out=57,094,295 elapsed=125.0s

  [6960/20519] intraday_15418.csv.gz  in=295,046,755 out=57,104,618 elapsed=125.0s

  [6961/20519] intraday_15419.csv.gz  in=295,060,690 out=57,118,553 elapsed=125.0s

  [6962/20519] intraday_1542.csv.gz  in=295,070,980 out=57,118,553 elapsed=125.0s

  [6963/20519] intraday_15420.csv.gz  in=295,083,549 out=57,131,122 elapsed=125.0s

  [6964/20519] intraday_15421.csv.gz  in=295,092,907 out=57,140,480 elapsed=125.0s

  [6965/20519] intraday_15423.csv.gz  in=295,104,073 out=57,151,646 elapsed=125.1s

  [6966/20519] intraday_15424.csv.gz  in=295,116,385 out=57,163,958 elapsed=125.1s

  [6967/20519] intraday_15422.csv.gz  in=295,129,547 out=57,177,120 elapsed=125.1s

  [6968/20519] intraday_15425.csv.gz  in=295,142,083 out=57,189,656 elapsed=125.1s

  [6969/20519] intraday_15426.csv.gz  in=295,153,050 out=57,200,623 elapsed=125.1s

  [6970/20519] intraday_15427.csv.gz  in=295,165,271 out=57,212,844 elapsed=125.1s

  [6971/20519] intraday_15429.csv.gz  in=295,175,861 out=57,223,434 elapsed=125.1s

  [6972/20519] intraday_1543.csv.gz  in=295,189,512 out=57,223,434 elapsed=125.1s

  [6973/20519] intraday_15428.csv.gz  in=295,200,109 out=57,234,031 elapsed=125.1s

  [6974/20519] intraday_15432.csv.gz  in=295,212,425 out=57,246,347 elapsed=125.2s

  [6975/20519] intraday_15431.csv.gz  in=295,225,489 out=57,259,411 elapsed=125.2s

  [6976/20519] intraday_15433.csv.gz  in=295,239,291 out=57,273,213 elapsed=125.2s

  [6977/20519] intraday_15430.csv.gz  in=295,249,753 out=57,283,675 elapsed=125.2s

  [6978/20519] intraday_15434.csv.gz  in=295,259,885 out=57,293,807 elapsed=125.2s

  [6979/20519] intraday_15435.csv.gz  in=295,270,406 out=57,304,328 elapsed=125.2s

  [6980/20519] intraday_15436.csv.gz  in=295,282,349 out=57,316,271 elapsed=125.2s

  [6981/20519] intraday_15439.csv.gz  in=295,294,806 out=57,328,728 elapsed=125.3s

  [6982/20519] intraday_15438.csv.gz  in=295,305,850 out=57,339,772 elapsed=125.3s

  [6983/20519] intraday_15437.csv.gz  in=295,325,603 out=57,356,409 elapsed=125.3s

  [6984/20519] intraday_15440.csv.gz  in=295,336,512 out=57,367,318 elapsed=125.3s

  [6985/20519] intraday_1544.csv.gz  in=295,349,626 out=57,367,318 elapsed=125.3s

  [6986/20519] intraday_15442.csv.gz  in=295,359,448 out=57,377,140 elapsed=125.3s

  [6987/20519] intraday_15441.csv.gz  in=295,369,352 out=57,387,044 elapsed=125.4s

  [6988/20519] intraday_15443.csv.gz  in=295,380,328 out=57,398,020 elapsed=125.4s

  [6989/20519] intraday_15444.csv.gz  in=295,392,083 out=57,409,775 elapsed=125.4s

  [6990/20519] intraday_15445.csv.gz  in=295,405,209 out=57,422,901 elapsed=125.4s

  [6991/20519] intraday_15446.csv.gz  in=295,418,038 out=57,435,730 elapsed=125.4s

  [6992/20519] intraday_15447.csv.gz  in=295,428,854 out=57,446,546 elapsed=125.4s

  [6993/20519] intraday_15448.csv.gz  in=295,440,281 out=57,457,973 elapsed=125.4s

  [6994/20519] intraday_15449.csv.gz  in=295,451,433 out=57,469,125 elapsed=125.4s

  [6995/20519] intraday_1545.csv.gz  in=295,466,259 out=57,469,125 elapsed=125.5s

  [6996/20519] intraday_15450.csv.gz  in=295,478,785 out=57,481,651 elapsed=125.5s

  [6997/20519] intraday_15451.csv.gz  in=295,489,284 out=57,492,150 elapsed=125.5s

  [6998/20519] intraday_15453.csv.gz  in=295,498,786 out=57,501,652 elapsed=125.5s

  [6999/20519] intraday_15452.csv.gz  in=295,509,758 out=57,512,624 elapsed=125.5s

  [7000/20519] intraday_15454.csv.gz  in=295,523,641 out=57,526,507 elapsed=125.5s

  [7001/20519] intraday_15455.csv.gz  in=295,534,826 out=57,537,692 elapsed=125.5s

  [7002/20519] intraday_15456.csv.gz  in=295,545,592 out=57,548,458 elapsed=125.5s

  [7003/20519] intraday_15457.csv.gz  in=295,559,892 out=57,562,758 elapsed=125.6s

  [7004/20519] intraday_15458.csv.gz  in=295,570,817 out=57,573,683 elapsed=125.6s

  [7005/20519] intraday_15459.csv.gz  in=295,581,624 out=57,584,490 elapsed=125.6s

  [7006/20519] intraday_1546.csv.gz  in=295,595,973 out=57,584,490 elapsed=125.6s

  [7007/20519] intraday_15460.csv.gz  in=295,606,913 out=57,595,430 elapsed=125.6s

  [7008/20519] intraday_15461.csv.gz  in=295,617,475 out=57,605,992 elapsed=125.7s

  [7009/20519] intraday_15462.csv.gz  in=295,629,563 out=57,618,080 elapsed=125.7s

  [7010/20519] intraday_15463.csv.gz  in=295,660,254 out=57,640,820 elapsed=125.7s

  [7011/20519] intraday_15464.csv.gz  in=295,670,539 out=57,651,105 elapsed=125.7s

  [7012/20519] intraday_15466.csv.gz  in=295,680,111 out=57,660,677 elapsed=125.8s

  [7013/20519] intraday_15467.csv.gz  in=295,693,734 out=57,674,300 elapsed=125.8s

  [7014/20519] intraday_15465.csv.gz  in=295,704,284 out=57,684,850 elapsed=125.8s

  [7015/20519] intraday_15468.csv.gz  in=295,715,093 out=57,695,659 elapsed=125.8s

  [7016/20519] intraday_15469.csv.gz  in=295,727,762 out=57,708,328 elapsed=125.8s

  [7017/20519] intraday_1547.csv.gz  in=295,739,689 out=57,708,328 elapsed=125.8s

  [7018/20519] intraday_15470.csv.gz  in=295,751,062 out=57,719,701 elapsed=125.8s

  [7019/20519] intraday_15472.csv.gz  in=295,759,207 out=57,727,846 elapsed=125.9s

  [7020/20519] intraday_15471.csv.gz  in=295,770,350 out=57,738,989 elapsed=125.9s

  [7021/20519] intraday_15473.csv.gz  in=295,782,834 out=57,751,473 elapsed=125.9s

  [7022/20519] intraday_15474.csv.gz  in=295,794,151 out=57,762,790 elapsed=125.9s

  [7023/20519] intraday_15475.csv.gz  in=295,805,015 out=57,773,654 elapsed=125.9s

  [7024/20519] intraday_15477.csv.gz  in=295,815,139 out=57,783,778 elapsed=125.9s

  [7025/20519] intraday_15476.csv.gz  in=295,824,408 out=57,793,039 elapsed=125.9s

  [7026/20519] intraday_15479.csv.gz  in=295,838,332 out=57,806,963 elapsed=125.9s

  [7027/20519] intraday_15478.csv.gz  in=295,846,859 out=57,815,490 elapsed=125.9s

  [7028/20519] intraday_1548.csv.gz  in=295,858,895 out=57,815,490 elapsed=125.9s

  [7029/20519] intraday_15480.csv.gz  in=295,870,349 out=57,826,944 elapsed=126.0s

  [7030/20519] intraday_15483.csv.gz  in=295,880,748 out=57,837,343 elapsed=126.0s

  [7031/20519] intraday_15481.csv.gz  in=295,896,561 out=57,850,765 elapsed=126.0s

  [7032/20519] intraday_15482.csv.gz  in=295,906,974 out=57,861,178 elapsed=126.0s

  [7033/20519] intraday_15484.csv.gz  in=295,917,638 out=57,871,842 elapsed=126.0s

  [7034/20519] intraday_15485.csv.gz  in=295,928,961 out=57,883,165 elapsed=126.0s

  [7035/20519] intraday_15487.csv.gz  in=295,940,579 out=57,894,783 elapsed=126.1s

  [7036/20519] intraday_15486.csv.gz  in=295,956,431 out=57,910,635 elapsed=126.1s

  [7037/20519] intraday_15489.csv.gz  in=295,967,826 out=57,922,030 elapsed=126.1s

  [7038/20519] intraday_15488.csv.gz  in=295,981,170 out=57,935,374 elapsed=126.1s

  [7039/20519] intraday_1549.csv.gz  in=295,992,768 out=57,935,374 elapsed=126.1s

  [7040/20519] intraday_15490.csv.gz  in=296,004,762 out=57,947,368 elapsed=126.1s

  [7041/20519] intraday_15491.csv.gz  in=296,016,739 out=57,959,345 elapsed=126.1s

  [7042/20519] intraday_15492.csv.gz  in=296,029,917 out=57,972,523 elapsed=126.1s

  [7043/20519] intraday_15493.csv.gz  in=296,040,128 out=57,982,734 elapsed=126.1s

  [7044/20519] intraday_15494.csv.gz  in=296,052,294 out=57,994,900 elapsed=126.1s

  [7045/20519] intraday_15495.csv.gz  in=296,063,280 out=58,005,886 elapsed=126.2s

  [7046/20519] intraday_15496.csv.gz  in=296,073,691 out=58,016,297 elapsed=126.2s

  [7047/20519] intraday_15497.csv.gz  in=296,086,404 out=58,029,010 elapsed=126.2s

  [7048/20519] intraday_15498.csv.gz  in=296,097,191 out=58,039,797 elapsed=126.2s

  [7049/20519] intraday_15499.csv.gz  in=296,108,617 out=58,051,223 elapsed=126.2s

  [7050/20519] intraday_15500.csv.gz  in=296,119,623 out=58,062,229 elapsed=126.3s

  [7051/20519] intraday_15501.csv.gz  in=296,130,316 out=58,072,922 elapsed=126.3s

  [7052/20519] intraday_1550.csv.gz  in=296,164,539 out=58,072,922 elapsed=126.3s

  [7053/20519] intraday_15502.csv.gz  in=296,175,578 out=58,083,956 elapsed=126.3s

  [7054/20519] intraday_15503.csv.gz  in=296,187,633 out=58,096,011 elapsed=126.3s

  [7055/20519] intraday_15505.csv.gz  in=296,198,568 out=58,106,946 elapsed=126.3s

  [7056/20519] intraday_15506.csv.gz  in=296,210,179 out=58,118,557 elapsed=126.3s

  [7057/20519] intraday_15504.csv.gz  in=296,222,011 out=58,130,389 elapsed=126.3s

  [7058/20519] intraday_15507.csv.gz  in=296,230,980 out=58,139,358 elapsed=126.3s

  [7059/20519] intraday_15509.csv.gz  in=296,240,176 out=58,148,554 elapsed=126.4s

  [7060/20519] intraday_1551.csv.gz  in=296,251,089 out=58,148,554 elapsed=126.4s

  [7061/20519] intraday_15508.csv.gz  in=296,265,973 out=58,163,438 elapsed=126.4s

  [7062/20519] intraday_15510.csv.gz  in=296,280,561 out=58,176,227 elapsed=126.4s

  [7063/20519] intraday_15511.csv.gz  in=296,292,948 out=58,188,614 elapsed=126.4s

  [7064/20519] intraday_15512.csv.gz  in=296,306,560 out=58,202,226 elapsed=126.4s

  [7065/20519] intraday_15513.csv.gz  in=296,316,584 out=58,212,250 elapsed=126.4s

  [7066/20519] intraday_15514.csv.gz  in=296,333,473 out=58,225,453 elapsed=126.4s

  [7067/20519] intraday_15515.csv.gz  in=296,346,390 out=58,238,370 elapsed=126.5s

  [7068/20519] intraday_15516.csv.gz  in=296,357,463 out=58,249,443 elapsed=126.5s

  [7069/20519] intraday_15517.csv.gz  in=296,369,953 out=58,261,933 elapsed=126.5s

  [7070/20519] intraday_1552.csv.gz  in=296,382,424 out=58,261,933 elapsed=126.5s

  [7071/20519] intraday_15519.csv.gz  in=296,399,687 out=58,279,196 elapsed=126.5s

  [7072/20519] intraday_15520.csv.gz  in=296,413,259 out=58,292,768 elapsed=126.5s

  [7073/20519] intraday_15518.csv.gz  in=296,427,039 out=58,306,548 elapsed=126.5s

  [7074/20519] intraday_15521.csv.gz  in=296,440,473 out=58,319,982 elapsed=126.5s

  [7075/20519] intraday_15522.csv.gz  in=296,451,097 out=58,330,606 elapsed=126.5s

  [7076/20519] intraday_15523.csv.gz  in=296,462,871 out=58,342,380 elapsed=126.6s

  [7077/20519] intraday_15525.csv.gz  in=296,475,528 out=58,355,037 elapsed=126.6s

  [7078/20519] intraday_15524.csv.gz  in=296,484,010 out=58,363,519 elapsed=126.6s

  [7079/20519] intraday_15526.csv.gz  in=296,493,893 out=58,373,402 elapsed=126.6s

  [7080/20519] intraday_15527.csv.gz  in=296,505,598 out=58,385,107 elapsed=126.6s

  [7081/20519] intraday_1553.csv.gz  in=296,517,411 out=58,385,107 elapsed=126.6s

  [7082/20519] intraday_15529.csv.gz  in=296,531,886 out=58,399,582 elapsed=126.6s

  [7083/20519] intraday_15528.csv.gz  in=296,543,955 out=58,411,651 elapsed=126.6s

  [7084/20519] intraday_15530.csv.gz  in=296,555,007 out=58,422,703 elapsed=126.7s

  [7085/20519] intraday_15532.csv.gz  in=296,565,725 out=58,433,421 elapsed=126.7s

  [7086/20519] intraday_15533.csv.gz  in=296,578,051 out=58,445,747 elapsed=126.7s

  [7087/20519] intraday_15531.csv.gz  in=296,588,541 out=58,456,237 elapsed=126.7s

  [7088/20519] intraday_15535.csv.gz  in=296,600,935 out=58,468,631 elapsed=126.8s

  [7089/20519] intraday_15534.csv.gz  in=296,611,538 out=58,479,234 elapsed=126.8s

  [7090/20519] intraday_15536.csv.gz  in=296,625,074 out=58,492,770 elapsed=126.8s

  [7091/20519] intraday_15537.csv.gz  in=296,636,450 out=58,504,146 elapsed=126.8s

  [7092/20519] intraday_15539.csv.gz  in=296,645,761 out=58,513,457 elapsed=126.8s

  [7093/20519] intraday_15538.csv.gz  in=296,660,701 out=58,528,397 elapsed=126.9s

  [7094/20519] intraday_1554.csv.gz  in=296,672,499 out=58,528,397 elapsed=126.9s

  [7095/20519] intraday_15540.csv.gz  in=296,683,872 out=58,539,770 elapsed=126.9s

  [7096/20519] intraday_15541.csv.gz  in=296,696,458 out=58,552,356 elapsed=126.9s

  [7097/20519] intraday_15543.csv.gz  in=296,707,420 out=58,563,318 elapsed=126.9s

  [7098/20519] intraday_15542.csv.gz  in=296,724,742 out=58,576,490 elapsed=126.9s

  [7099/20519] intraday_15544.csv.gz  in=296,732,050 out=58,583,798 elapsed=126.9s

  [7100/20519] intraday_15545.csv.gz  in=296,742,016 out=58,593,764 elapsed=126.9s

  [7101/20519] intraday_15546.csv.gz  in=296,750,049 out=58,601,797 elapsed=126.9s

  [7102/20519] intraday_15548.csv.gz  in=296,762,312 out=58,614,060 elapsed=127.0s

  [7103/20519] intraday_15547.csv.gz  in=296,778,406 out=58,630,154 elapsed=127.0s

  [7104/20519] intraday_1555.csv.gz  in=296,791,221 out=58,630,154 elapsed=127.0s

  [7105/20519] intraday_15549.csv.gz  in=296,803,987 out=58,642,920 elapsed=127.0s

  [7106/20519] intraday_15550.csv.gz  in=296,815,073 out=58,654,006 elapsed=127.0s

  [7107/20519] intraday_15551.csv.gz  in=296,827,138 out=58,666,071 elapsed=127.0s

  [7108/20519] intraday_15552.csv.gz  in=296,841,389 out=58,680,322 elapsed=127.0s

  [7109/20519] intraday_15553.csv.gz  in=296,854,867 out=58,693,800 elapsed=127.0s

  [7110/20519] intraday_15555.csv.gz  in=296,869,915 out=58,708,848 elapsed=127.1s

  [7111/20519] intraday_15554.csv.gz  in=296,880,958 out=58,719,891 elapsed=127.1s

  [7112/20519] intraday_15557.csv.gz  in=296,892,144 out=58,731,077 elapsed=127.1s

  [7113/20519] intraday_15556.csv.gz  in=296,904,679 out=58,743,612 elapsed=127.1s

  [7114/20519] intraday_1556.csv.gz  in=296,916,690 out=58,743,612 elapsed=127.1s

  [7115/20519] intraday_15559.csv.gz  in=296,932,460 out=58,758,244 elapsed=127.1s

  [7116/20519] intraday_15558.csv.gz  in=296,945,125 out=58,770,909 elapsed=127.1s

  [7117/20519] intraday_15560.csv.gz  in=296,958,115 out=58,783,899 elapsed=127.1s

  [7118/20519] intraday_15561.csv.gz  in=296,968,825 out=58,794,609 elapsed=127.1s

  [7119/20519] intraday_15562.csv.gz  in=296,979,327 out=58,805,111 elapsed=127.2s

  [7120/20519] intraday_15563.csv.gz  in=296,994,568 out=58,820,352 elapsed=127.2s

  [7121/20519] intraday_15565.csv.gz  in=297,005,845 out=58,831,629 elapsed=127.2s

  [7122/20519] intraday_15564.csv.gz  in=297,020,328 out=58,846,112 elapsed=127.2s

  [7123/20519] intraday_15566.csv.gz  in=297,032,071 out=58,857,855 elapsed=127.2s

  [7124/20519] intraday_15568.csv.gz  in=297,044,366 out=58,870,150 elapsed=127.2s

  [7125/20519] intraday_1557.csv.gz  in=297,057,363 out=58,870,150 elapsed=127.2s

  [7126/20519] intraday_15569.csv.gz  in=297,070,825 out=58,883,612 elapsed=127.3s

  [7127/20519] intraday_15567.csv.gz  in=297,103,849 out=58,908,934 elapsed=127.3s

  [7128/20519] intraday_15570.csv.gz  in=297,115,804 out=58,920,889 elapsed=127.3s

  [7129/20519] intraday_15571.csv.gz  in=297,128,154 out=58,933,239 elapsed=127.3s

  [7130/20519] intraday_15572.csv.gz  in=297,139,999 out=58,945,084 elapsed=127.3s

  [7131/20519] intraday_15573.csv.gz  in=297,150,118 out=58,955,203 elapsed=127.3s

  [7132/20519] intraday_15574.csv.gz  in=297,161,939 out=58,967,024 elapsed=127.3s

  [7133/20519] intraday_15575.csv.gz  in=297,174,351 out=58,979,436 elapsed=127.3s

  [7134/20519] intraday_15576.csv.gz  in=297,188,418 out=58,993,217 elapsed=127.4s

  [7135/20519] intraday_15577.csv.gz  in=297,203,749 out=59,008,533 elapsed=127.4s

  [7136/20519] intraday_15578.csv.gz  in=297,216,771 out=59,021,555 elapsed=127.4s

  [7137/20519] intraday_15579.csv.gz  in=297,227,567 out=59,032,351 elapsed=127.4s

  [7138/20519] intraday_1558.csv.gz  in=297,240,157 out=59,032,351 elapsed=127.4s

  [7139/20519] intraday_15580.csv.gz  in=297,252,356 out=59,044,550 elapsed=127.4s

  [7140/20519] intraday_15581.csv.gz  in=297,265,570 out=59,057,764 elapsed=127.4s

  [7141/20519] intraday_15582.csv.gz  in=297,277,776 out=59,069,970 elapsed=127.5s

  [7142/20519] intraday_15583.csv.gz  in=297,290,650 out=59,082,844 elapsed=127.5s

  [7143/20519] intraday_15584.csv.gz  in=297,299,812 out=59,092,006 elapsed=127.5s

  [7144/20519] intraday_15586.csv.gz  in=297,308,973 out=59,101,167 elapsed=127.5s

  [7145/20519] intraday_15585.csv.gz  in=297,321,045 out=59,113,239 elapsed=127.5s

  [7146/20519] intraday_15588.csv.gz  in=297,332,940 out=59,125,134 elapsed=127.5s

  [7147/20519] intraday_15589.csv.gz  in=297,347,416 out=59,139,610 elapsed=127.5s

  [7148/20519] intraday_1559.csv.gz  in=297,362,519 out=59,139,610 elapsed=127.5s

  [7149/20519] intraday_15587.csv.gz  in=297,373,983 out=59,151,074 elapsed=127.5s

  [7150/20519] intraday_15590.csv.gz  in=297,385,194 out=59,162,285 elapsed=127.6s

  [7151/20519] intraday_15593.csv.gz  in=297,396,862 out=59,173,953 elapsed=127.6s

  [7152/20519] intraday_15592.csv.gz  in=297,409,162 out=59,186,253 elapsed=127.6s

  [7153/20519] intraday_15591.csv.gz  in=297,424,598 out=59,201,288 elapsed=127.6s

  [7154/20519] intraday_15595.csv.gz  in=297,436,605 out=59,213,295 elapsed=127.6s

  [7155/20519] intraday_15594.csv.gz  in=297,448,550 out=59,225,240 elapsed=127.6s

  [7156/20519] intraday_15596.csv.gz  in=297,460,215 out=59,236,905 elapsed=127.6s

  [7157/20519] intraday_15597.csv.gz  in=297,469,976 out=59,246,666 elapsed=127.7s

  [7158/20519] intraday_15598.csv.gz  in=297,482,559 out=59,259,249 elapsed=127.7s

  [7159/20519] intraday_1560.csv.gz  in=297,493,707 out=59,259,249 elapsed=127.7s

  [7160/20519] intraday_15600.csv.gz  in=297,507,345 out=59,272,887 elapsed=127.7s

  [7161/20519] intraday_15599.csv.gz  in=297,520,404 out=59,285,946 elapsed=127.7s

  [7162/20519] intraday_15602.csv.gz  in=297,533,845 out=59,299,387 elapsed=127.7s

  [7163/20519] intraday_15601.csv.gz  in=297,546,059 out=59,311,601 elapsed=127.8s

  [7164/20519] intraday_15603.csv.gz  in=297,557,269 out=59,322,811 elapsed=127.9s

  [7165/20519] intraday_15604.csv.gz  in=297,567,683 out=59,333,225 elapsed=127.9s

  [7166/20519] intraday_15606.csv.gz  in=297,581,226 out=59,346,768 elapsed=127.9s

  [7167/20519] intraday_15605.csv.gz  in=297,592,545 out=59,358,087 elapsed=127.9s

  [7168/20519] intraday_15607.csv.gz  in=297,607,384 out=59,372,926 elapsed=127.9s

  [7169/20519] intraday_15609.csv.gz  in=297,618,959 out=59,384,501 elapsed=127.9s

  [7170/20519] intraday_15608.csv.gz  in=297,630,556 out=59,396,098 elapsed=127.9s

  [7171/20519] intraday_15610.csv.gz  in=297,641,706 out=59,407,248 elapsed=127.9s

  [7172/20519] intraday_1561.csv.gz  in=297,655,541 out=59,407,248 elapsed=127.9s

  [7173/20519] intraday_15612.csv.gz  in=297,668,854 out=59,420,561 elapsed=127.9s

  [7174/20519] intraday_15613.csv.gz  in=297,682,602 out=59,434,309 elapsed=128.0s

  [7175/20519] intraday_15611.csv.gz  in=297,695,873 out=59,447,580 elapsed=128.0s

  [7176/20519] intraday_15615.csv.gz  in=297,708,397 out=59,460,104 elapsed=128.0s

  [7177/20519] intraday_15614.csv.gz  in=297,720,656 out=59,472,363 elapsed=128.0s

  [7178/20519] intraday_15616.csv.gz  in=297,733,228 out=59,484,809 elapsed=128.0s

  [7179/20519] intraday_15617.csv.gz  in=297,744,941 out=59,496,522 elapsed=128.0s

  [7180/20519] intraday_15619.csv.gz  in=297,756,555 out=59,508,136 elapsed=128.0s

  [7181/20519] intraday_15618.csv.gz  in=297,769,502 out=59,521,083 elapsed=128.0s

  [7182/20519] intraday_1562.csv.gz  in=297,780,138 out=59,521,083 elapsed=128.0s

  [7183/20519] intraday_15620.csv.gz  in=297,791,383 out=59,532,328 elapsed=128.1s

  [7184/20519] intraday_15622.csv.gz  in=297,801,945 out=59,542,890 elapsed=128.1s

  [7185/20519] intraday_15623.csv.gz  in=297,814,227 out=59,555,172 elapsed=128.1s

  [7186/20519] intraday_15621.csv.gz  in=297,824,841 out=59,565,786 elapsed=128.1s

  [7187/20519] intraday_15624.csv.gz  in=297,839,035 out=59,579,980 elapsed=128.1s

  [7188/20519] intraday_15625.csv.gz  in=297,850,239 out=59,591,184 elapsed=128.1s

  [7189/20519] intraday_15626.csv.gz  in=297,861,286 out=59,602,231 elapsed=128.1s

  [7190/20519] intraday_15628.csv.gz  in=297,872,873 out=59,613,818 elapsed=128.2s

  [7191/20519] intraday_15627.csv.gz  in=297,882,311 out=59,623,256 elapsed=128.2s

  [7192/20519] intraday_15629.csv.gz  in=297,894,750 out=59,635,695 elapsed=128.2s

  [7193/20519] intraday_1563.csv.gz  in=297,906,799 out=59,635,695 elapsed=128.2s

  [7194/20519] intraday_15630.csv.gz  in=297,920,588 out=59,649,484 elapsed=128.2s

  [7195/20519] intraday_15631.csv.gz  in=297,934,565 out=59,663,461 elapsed=128.2s

  [7196/20519] intraday_15633.csv.gz  in=297,946,502 out=59,675,398 elapsed=128.3s

  [7197/20519] intraday_15632.csv.gz  in=297,959,750 out=59,688,646 elapsed=128.3s

  [7198/20519] intraday_15635.csv.gz  in=297,972,017 out=59,700,913 elapsed=128.3s

  [7199/20519] intraday_15634.csv.gz  in=297,984,305 out=59,713,201 elapsed=128.3s

  [7200/20519] intraday_15637.csv.gz  in=297,997,028 out=59,725,924 elapsed=128.3s

  [7201/20519] intraday_15636.csv.gz  in=298,012,371 out=59,741,267 elapsed=128.3s

  [7202/20519] intraday_15638.csv.gz  in=298,023,905 out=59,752,801 elapsed=128.3s

  [7203/20519] intraday_15639.csv.gz  in=298,036,733 out=59,765,629 elapsed=128.3s

  [7204/20519] intraday_1564.csv.gz  in=298,049,340 out=59,765,629 elapsed=128.3s

  [7205/20519] intraday_15640.csv.gz  in=298,061,326 out=59,777,615 elapsed=128.4s

  [7206/20519] intraday_15642.csv.gz  in=298,074,238 out=59,790,527 elapsed=128.4s

  [7207/20519] intraday_15643.csv.gz  in=298,087,005 out=59,803,294 elapsed=128.4s

  [7208/20519] intraday_15641.csv.gz  in=298,099,389 out=59,815,678 elapsed=128.4s

  [7209/20519] intraday_15644.csv.gz  in=298,110,577 out=59,826,866 elapsed=128.4s

  [7210/20519] intraday_15645.csv.gz  in=298,122,504 out=59,838,793 elapsed=128.4s

  [7211/20519] intraday_15647.csv.gz  in=298,133,937 out=59,850,226 elapsed=128.4s

  [7212/20519] intraday_15646.csv.gz  in=298,145,395 out=59,861,684 elapsed=128.5s

  [7213/20519] intraday_15648.csv.gz  in=298,160,472 out=59,876,245 elapsed=128.5s

  [7214/20519] intraday_15649.csv.gz  in=298,174,472 out=59,890,245 elapsed=128.5s

  [7215/20519] intraday_1565.csv.gz  in=298,184,752 out=59,890,245 elapsed=128.5s

  [7216/20519] intraday_15651.csv.gz  in=298,196,508 out=59,902,001 elapsed=128.5s

  [7217/20519] intraday_15650.csv.gz  in=298,208,388 out=59,913,881 elapsed=128.5s

  [7218/20519] intraday_15652.csv.gz  in=298,218,345 out=59,923,838 elapsed=128.5s

  [7219/20519] intraday_15654.csv.gz  in=298,229,282 out=59,934,775 elapsed=128.6s

  [7220/20519] intraday_15653.csv.gz  in=298,244,943 out=59,950,436 elapsed=128.6s

  [7221/20519] intraday_15655.csv.gz  in=298,257,523 out=59,963,016 elapsed=128.6s

  [7222/20519] intraday_15656.csv.gz  in=298,269,357 out=59,974,850 elapsed=128.6s

  [7223/20519] intraday_15657.csv.gz  in=298,283,328 out=59,988,821 elapsed=128.6s

  [7224/20519] intraday_15658.csv.gz  in=298,295,411 out=60,000,904 elapsed=128.6s

  [7225/20519] intraday_15659.csv.gz  in=298,310,405 out=60,015,898 elapsed=128.6s

  [7226/20519] intraday_15660.csv.gz  in=298,324,517 out=60,030,010 elapsed=128.6s

  [7227/20519] intraday_15661.csv.gz  in=298,334,602 out=60,040,095 elapsed=128.7s

  [7228/20519] intraday_1566.csv.gz  in=298,347,951 out=60,040,095 elapsed=128.7s

  [7229/20519] intraday_15662.csv.gz  in=298,362,117 out=60,054,261 elapsed=128.7s

  [7230/20519] intraday_15663.csv.gz  in=298,378,489 out=60,070,633 elapsed=128.7s

  [7231/20519] intraday_15664.csv.gz  in=298,393,945 out=60,086,089 elapsed=128.7s

  [7232/20519] intraday_15665.csv.gz  in=298,408,906 out=60,101,050 elapsed=128.7s

  [7233/20519] intraday_15667.csv.gz  in=298,421,216 out=60,113,360 elapsed=128.8s

  [7234/20519] intraday_15666.csv.gz  in=298,433,107 out=60,125,251 elapsed=128.8s

  [7235/20519] intraday_15668.csv.gz  in=298,445,145 out=60,137,289 elapsed=128.8s

  [7236/20519] intraday_15669.csv.gz  in=298,455,495 out=60,147,639 elapsed=128.8s

  [7237/20519] intraday_1567.csv.gz  in=298,470,681 out=60,147,639 elapsed=128.8s

  [7238/20519] intraday_15670.csv.gz  in=298,482,595 out=60,159,553 elapsed=128.8s

  [7239/20519] intraday_15672.csv.gz  in=298,497,422 out=60,173,750 elapsed=128.9s

  [7240/20519] intraday_15673.csv.gz  in=298,509,757 out=60,186,085 elapsed=128.9s

  [7241/20519] intraday_15671.csv.gz  in=298,520,562 out=60,196,890 elapsed=128.9s

  [7242/20519] intraday_15674.csv.gz  in=298,534,402 out=60,210,730 elapsed=128.9s

  [7243/20519] intraday_15675.csv.gz  in=298,545,714 out=60,222,042 elapsed=128.9s

  [7244/20519] intraday_15676.csv.gz  in=298,556,789 out=60,233,117 elapsed=128.9s

  [7245/20519] intraday_15677.csv.gz  in=298,570,067 out=60,246,395 elapsed=128.9s

  [7246/20519] intraday_15679.csv.gz  in=298,582,341 out=60,258,669 elapsed=129.0s

  [7247/20519] intraday_1568.csv.gz  in=298,594,396 out=60,258,669 elapsed=129.0s

  [7248/20519] intraday_15680.csv.gz  in=298,607,789 out=60,272,062 elapsed=129.0s

  [7249/20519] intraday_15678.csv.gz  in=298,619,380 out=60,283,653 elapsed=129.0s

  [7250/20519] intraday_15681.csv.gz  in=298,632,828 out=60,297,101 elapsed=129.0s

  [7251/20519] intraday_15682.csv.gz  in=298,645,398 out=60,309,671 elapsed=129.0s

  [7252/20519] intraday_15683.csv.gz  in=298,659,464 out=60,323,737 elapsed=129.0s

  [7253/20519] intraday_15684.csv.gz  in=298,672,467 out=60,336,740 elapsed=129.0s

  [7254/20519] intraday_15686.csv.gz  in=298,684,986 out=60,349,259 elapsed=129.0s

  [7255/20519] intraday_15685.csv.gz  in=298,697,001 out=60,361,274 elapsed=129.1s

  [7256/20519] intraday_15689.csv.gz  in=298,706,116 out=60,370,389 elapsed=129.1s

  [7257/20519] intraday_15687.csv.gz  in=298,717,672 out=60,381,945 elapsed=129.1s

  [7258/20519] intraday_1569.csv.gz  in=298,729,361 out=60,381,945 elapsed=129.1s

  [7259/20519] intraday_15688.csv.gz  in=298,739,453 out=60,392,037 elapsed=129.1s

  [7260/20519] intraday_15691.csv.gz  in=298,744,814 out=60,397,398 elapsed=129.1s

  [7261/20519] intraday_15690.csv.gz  in=298,754,613 out=60,407,197 elapsed=129.1s

  [7262/20519] intraday_15692.csv.gz  in=298,770,319 out=60,416,970 elapsed=129.1s

  [7263/20519] intraday_15693.csv.gz  in=298,786,712 out=60,433,363 elapsed=129.2s

  [7264/20519] intraday_15695.csv.gz  in=298,798,839 out=60,445,490 elapsed=129.2s

  [7265/20519] intraday_15696.csv.gz  in=298,810,517 out=60,457,168 elapsed=129.2s

  [7266/20519] intraday_15694.csv.gz  in=298,824,905 out=60,471,556 elapsed=129.2s

  [7267/20519] intraday_15697.csv.gz  in=298,836,557 out=60,483,208 elapsed=129.2s

  [7268/20519] intraday_1570.csv.gz  in=298,849,264 out=60,483,208 elapsed=129.2s

  [7269/20519] intraday_15698.csv.gz  in=298,863,703 out=60,497,647 elapsed=129.3s

  [7270/20519] intraday_15700.csv.gz  in=298,874,583 out=60,508,527 elapsed=129.3s

  [7271/20519] intraday_15701.csv.gz  in=298,886,596 out=60,520,540 elapsed=129.3s

  [7272/20519] intraday_15699.csv.gz  in=298,899,242 out=60,533,186 elapsed=129.3s

  [7273/20519] intraday_15702.csv.gz  in=298,911,827 out=60,545,771 elapsed=129.3s

  [7274/20519] intraday_15703.csv.gz  in=298,923,042 out=60,556,986 elapsed=129.3s

  [7275/20519] intraday_15705.csv.gz  in=298,936,314 out=60,570,258 elapsed=129.3s

  [7276/20519] intraday_15704.csv.gz  in=298,951,874 out=60,584,341 elapsed=129.3s

  [7277/20519] intraday_15707.csv.gz  in=298,961,808 out=60,594,275 elapsed=129.4s

  [7278/20519] intraday_15706.csv.gz  in=298,974,015 out=60,606,482 elapsed=129.4s

  [7279/20519] intraday_15708.csv.gz  in=298,983,562 out=60,616,029 elapsed=129.4s

  [7280/20519] intraday_1571.csv.gz  in=298,996,045 out=60,616,029 elapsed=129.4s

  [7281/20519] intraday_15709.csv.gz  in=299,011,772 out=60,631,756 elapsed=129.4s

  [7282/20519] intraday_15710.csv.gz  in=299,025,104 out=60,645,088 elapsed=129.4s

  [7283/20519] intraday_15712.csv.gz  in=299,037,477 out=60,657,255 elapsed=129.4s

  [7284/20519] intraday_15713.csv.gz  in=299,048,550 out=60,668,328 elapsed=129.4s

  [7285/20519] intraday_15711.csv.gz  in=299,059,452 out=60,679,230 elapsed=129.5s

  [7286/20519] intraday_15714.csv.gz  in=299,071,664 out=60,691,442 elapsed=129.5s

  [7287/20519] intraday_15715.csv.gz  in=299,086,788 out=60,705,571 elapsed=129.5s

  [7288/20519] intraday_15716.csv.gz  in=299,098,770 out=60,717,553 elapsed=129.5s

  [7289/20519] intraday_15717.csv.gz  in=299,111,310 out=60,730,093 elapsed=129.5s

  [7290/20519] intraday_15718.csv.gz  in=299,122,564 out=60,741,347 elapsed=129.5s

  [7291/20519] intraday_15719.csv.gz  in=299,132,328 out=60,751,111 elapsed=129.5s

  [7292/20519] intraday_1572.csv.gz  in=299,143,858 out=60,751,111 elapsed=129.5s

  [7293/20519] intraday_15721.csv.gz  in=299,156,660 out=60,763,913 elapsed=129.6s

  [7294/20519] intraday_15720.csv.gz  in=299,167,876 out=60,775,129 elapsed=129.6s

  [7295/20519] intraday_15722.csv.gz  in=299,179,483 out=60,786,736 elapsed=129.6s

  [7296/20519] intraday_15725.csv.gz  in=299,189,551 out=60,796,804 elapsed=129.6s

  [7297/20519] intraday_15724.csv.gz  in=299,202,253 out=60,809,506 elapsed=129.6s

  [7298/20519] intraday_15723.csv.gz  in=299,218,345 out=60,825,598 elapsed=129.6s

  [7299/20519] intraday_15726.csv.gz  in=299,230,252 out=60,837,505 elapsed=129.6s

  [7300/20519] intraday_15727.csv.gz  in=299,242,593 out=60,849,846 elapsed=129.6s

  [7301/20519] intraday_15728.csv.gz  in=299,254,548 out=60,861,801 elapsed=129.7s

  [7302/20519] intraday_1573.csv.gz  in=299,267,390 out=60,861,801 elapsed=129.7s

  [7303/20519] intraday_15729.csv.gz  in=299,281,089 out=60,875,500 elapsed=129.7s

  [7304/20519] intraday_15730.csv.gz  in=299,290,131 out=60,884,542 elapsed=129.7s

  [7305/20519] intraday_15731.csv.gz  in=299,301,711 out=60,896,122 elapsed=129.7s

  [7306/20519] intraday_15733.csv.gz  in=299,312,653 out=60,907,064 elapsed=129.7s

  [7307/20519] intraday_15732.csv.gz  in=299,321,552 out=60,915,963 elapsed=129.7s

  [7308/20519] intraday_15734.csv.gz  in=299,339,014 out=60,930,604 elapsed=129.8s

  [7309/20519] intraday_15735.csv.gz  in=299,352,659 out=60,944,249 elapsed=129.8s

  [7310/20519] intraday_15737.csv.gz  in=299,366,163 out=60,957,753 elapsed=129.8s

  [7311/20519] intraday_15736.csv.gz  in=299,378,408 out=60,969,998 elapsed=129.8s

  [7312/20519] intraday_15738.csv.gz  in=299,389,583 out=60,981,173 elapsed=129.8s

  [7313/20519] intraday_15739.csv.gz  in=299,401,110 out=60,992,700 elapsed=129.8s

  [7314/20519] intraday_1574.csv.gz  in=299,413,982 out=60,992,700 elapsed=129.8s

  [7315/20519] intraday_15740.csv.gz  in=299,424,930 out=61,003,648 elapsed=129.9s

  [7316/20519] intraday_15741.csv.gz  in=299,436,073 out=61,014,791 elapsed=129.9s

  [7317/20519] intraday_15743.csv.gz  in=299,447,437 out=61,026,155 elapsed=129.9s

  [7318/20519] intraday_15742.csv.gz  in=299,458,802 out=61,037,520 elapsed=129.9s

  [7319/20519] intraday_15744.csv.gz  in=299,471,934 out=61,050,652 elapsed=129.9s

  [7320/20519] intraday_15745.csv.gz  in=299,484,408 out=61,063,126 elapsed=129.9s

  [7321/20519] intraday_15746.csv.gz  in=299,497,726 out=61,076,444 elapsed=129.9s

  [7322/20519] intraday_15747.csv.gz  in=299,511,126 out=61,089,844 elapsed=129.9s

  [7323/20519] intraday_15749.csv.gz  in=299,522,190 out=61,100,908 elapsed=129.9s

  [7324/20519] intraday_15748.csv.gz  in=299,534,657 out=61,113,375 elapsed=129.9s

  [7325/20519] intraday_1575.csv.gz  in=299,561,592 out=61,113,375 elapsed=130.0s

  [7326/20519] intraday_15751.csv.gz  in=299,573,831 out=61,125,614 elapsed=130.0s

  [7327/20519] intraday_15752.csv.gz  in=299,587,079 out=61,138,862 elapsed=130.0s

  [7328/20519] intraday_15750.csv.gz  in=299,616,168 out=61,159,786 elapsed=130.0s

  [7329/20519] intraday_15753.csv.gz  in=299,627,094 out=61,170,712 elapsed=130.0s

  [7330/20519] intraday_15755.csv.gz  in=299,638,216 out=61,181,834 elapsed=130.0s

  [7331/20519] intraday_15754.csv.gz  in=299,650,102 out=61,193,720 elapsed=130.0s

  [7332/20519] intraday_15756.csv.gz  in=299,660,727 out=61,204,345 elapsed=130.1s

  [7333/20519] intraday_15757.csv.gz  in=299,673,569 out=61,217,187 elapsed=130.1s

  [7334/20519] intraday_15758.csv.gz  in=299,689,025 out=61,232,643 elapsed=130.1s

  [7335/20519] intraday_15759.csv.gz  in=299,701,605 out=61,245,223 elapsed=130.1s

  [7336/20519] intraday_1576.csv.gz  in=299,714,271 out=61,245,223 elapsed=130.1s

  [7337/20519] intraday_15760.csv.gz  in=299,726,462 out=61,257,414 elapsed=130.1s

  [7338/20519] intraday_15762.csv.gz  in=299,734,986 out=61,265,938 elapsed=130.1s

  [7339/20519] intraday_15763.csv.gz  in=299,746,323 out=61,277,275 elapsed=130.2s

  [7340/20519] intraday_15761.csv.gz  in=299,763,068 out=61,292,546 elapsed=130.2s

  [7341/20519] intraday_15764.csv.gz  in=299,775,950 out=61,305,428 elapsed=130.2s

  [7342/20519] intraday_15767.csv.gz  in=299,787,989 out=61,317,467 elapsed=130.2s

  [7343/20519] intraday_15766.csv.gz  in=299,799,612 out=61,329,090 elapsed=130.2s

  [7344/20519] intraday_15765.csv.gz  in=299,810,198 out=61,339,676 elapsed=130.2s

  [7345/20519] intraday_15768.csv.gz  in=299,820,541 out=61,350,019 elapsed=130.2s

  [7346/20519] intraday_15769.csv.gz  in=299,831,604 out=61,361,082 elapsed=130.2s

  [7347/20519] intraday_1577.csv.gz  in=299,843,921 out=61,361,082 elapsed=130.3s

  [7348/20519] intraday_15770.csv.gz  in=299,857,592 out=61,374,753 elapsed=130.3s

  [7349/20519] intraday_15771.csv.gz  in=299,868,331 out=61,385,492 elapsed=130.3s

  [7350/20519] intraday_15773.csv.gz  in=299,878,496 out=61,395,657 elapsed=130.3s

  [7351/20519] intraday_15772.csv.gz  in=299,891,019 out=61,408,180 elapsed=130.3s

  [7352/20519] intraday_15774.csv.gz  in=299,902,622 out=61,419,783 elapsed=130.3s

  [7353/20519] intraday_15775.csv.gz  in=299,915,044 out=61,432,205 elapsed=130.3s

  [7354/20519] intraday_15776.csv.gz  in=299,928,941 out=61,446,102 elapsed=130.3s

  [7355/20519] intraday_15777.csv.gz  in=299,943,381 out=61,460,542 elapsed=130.3s

  [7356/20519] intraday_1578.csv.gz  in=299,952,794 out=61,460,542 elapsed=130.4s

  [7357/20519] intraday_15778.csv.gz  in=299,966,074 out=61,473,822 elapsed=130.4s

  [7358/20519] intraday_15779.csv.gz  in=299,978,410 out=61,486,158 elapsed=130.4s

  [7359/20519] intraday_15780.csv.gz  in=299,990,646 out=61,498,394 elapsed=130.4s

  [7360/20519] intraday_15781.csv.gz  in=300,002,158 out=61,509,906 elapsed=130.4s

  [7361/20519] intraday_15783.csv.gz  in=300,012,885 out=61,520,633 elapsed=130.4s

  [7362/20519] intraday_15784.csv.gz  in=300,024,900 out=61,532,648 elapsed=130.4s

  [7363/20519] intraday_15782.csv.gz  in=300,039,287 out=61,547,010 elapsed=130.4s

  [7364/20519] intraday_15785.csv.gz  in=300,053,142 out=61,560,865 elapsed=130.4s

  [7365/20519] intraday_15786.csv.gz  in=300,065,025 out=61,572,748 elapsed=130.5s

  [7366/20519] intraday_15788.csv.gz  in=300,076,709 out=61,584,432 elapsed=130.5s

  [7367/20519] intraday_15789.csv.gz  in=300,090,092 out=61,597,815 elapsed=130.5s

  [7368/20519] intraday_1579.csv.gz  in=300,102,323 out=61,597,815 elapsed=130.5s

  [7369/20519] intraday_15787.csv.gz  in=300,114,268 out=61,609,760 elapsed=130.5s

  [7370/20519] intraday_15790.csv.gz  in=300,125,592 out=61,621,084 elapsed=130.5s

  [7371/20519] intraday_15792.csv.gz  in=300,136,665 out=61,632,157 elapsed=130.5s

  [7372/20519] intraday_15791.csv.gz  in=300,148,122 out=61,643,614 elapsed=130.6s

  [7373/20519] intraday_15793.csv.gz  in=300,159,957 out=61,655,449 elapsed=130.6s

  [7374/20519] intraday_15794.csv.gz  in=300,174,171 out=61,668,838 elapsed=130.6s

  [7375/20519] intraday_15798.csv.gz  in=300,183,840 out=61,678,507 elapsed=130.6s

  [7376/20519] intraday_15795.csv.gz  in=300,196,679 out=61,691,346 elapsed=130.6s

  [7377/20519] intraday_15797.csv.gz  in=300,208,918 out=61,703,585 elapsed=130.6s

  [7378/20519] intraday_15796.csv.gz  in=300,221,173 out=61,715,840 elapsed=130.6s

  [7379/20519] intraday_15799.csv.gz  in=300,236,914 out=61,731,581 elapsed=130.7s

  [7380/20519] intraday_1580.csv.gz  in=300,250,520 out=61,731,581 elapsed=130.7s

  [7381/20519] intraday_15800.csv.gz  in=300,261,451 out=61,742,512 elapsed=130.7s

  [7382/20519] intraday_15801.csv.gz  in=300,273,200 out=61,754,261 elapsed=130.7s

  [7383/20519] intraday_15803.csv.gz  in=300,287,463 out=61,768,524 elapsed=130.7s

  [7384/20519] intraday_15802.csv.gz  in=300,300,214 out=61,781,275 elapsed=130.7s

  [7385/20519] intraday_15804.csv.gz  in=300,311,235 out=61,792,296 elapsed=130.8s

  [7386/20519] intraday_15805.csv.gz  in=300,326,211 out=61,807,272 elapsed=130.8s

  [7387/20519] intraday_15806.csv.gz  in=300,339,440 out=61,820,501 elapsed=130.8s

  [7388/20519] intraday_15807.csv.gz  in=300,352,400 out=61,833,461 elapsed=130.8s

  [7389/20519] intraday_15809.csv.gz  in=300,368,583 out=61,849,644 elapsed=130.8s

  [7390/20519] intraday_15808.csv.gz  in=300,380,953 out=61,862,014 elapsed=130.8s

  [7391/20519] intraday_1581.csv.gz  in=300,391,515 out=61,862,014 elapsed=130.8s

  [7392/20519] intraday_15811.csv.gz  in=300,405,756 out=61,876,255 elapsed=130.9s

  [7393/20519] intraday_15810.csv.gz  in=300,422,809 out=61,893,308 elapsed=130.9s

  [7394/20519] intraday_15812.csv.gz  in=300,435,710 out=61,906,209 elapsed=130.9s

  [7395/20519] intraday_15813.csv.gz  in=300,448,750 out=61,919,249 elapsed=130.9s

  [7396/20519] intraday_15814.csv.gz  in=300,461,993 out=61,932,492 elapsed=130.9s

  [7397/20519] intraday_15815.csv.gz  in=300,471,193 out=61,941,692 elapsed=130.9s

  [7398/20519] intraday_15816.csv.gz  in=300,483,556 out=61,954,055 elapsed=131.0s

  [7399/20519] intraday_15818.csv.gz  in=300,495,931 out=61,966,430 elapsed=131.0s

  [7400/20519] intraday_15817.csv.gz  in=300,506,600 out=61,977,099 elapsed=131.0s

  [7401/20519] intraday_1582.csv.gz  in=300,520,594 out=61,977,099 elapsed=131.0s

  [7402/20519] intraday_15819.csv.gz  in=300,533,718 out=61,990,223 elapsed=131.0s

  [7403/20519] intraday_15820.csv.gz  in=300,547,598 out=62,004,103 elapsed=131.0s

  [7404/20519] intraday_15822.csv.gz  in=300,560,723 out=62,017,228 elapsed=131.0s

  [7405/20519] intraday_15823.csv.gz  in=300,572,982 out=62,029,487 elapsed=131.1s

  [7406/20519] intraday_15824.csv.gz  in=300,585,538 out=62,042,043 elapsed=131.1s

  [7407/20519] intraday_15821.csv.gz  in=300,595,713 out=62,052,218 elapsed=131.1s

  [7408/20519] intraday_15825.csv.gz  in=300,607,227 out=62,063,732 elapsed=131.1s

  [7409/20519] intraday_15826.csv.gz  in=300,619,829 out=62,076,334 elapsed=131.1s

  [7410/20519] intraday_15827.csv.gz  in=300,632,872 out=62,089,377 elapsed=131.1s

  [7411/20519] intraday_15828.csv.gz  in=300,646,012 out=62,102,517 elapsed=131.1s

  [7412/20519] intraday_15829.csv.gz  in=300,660,678 out=62,117,183 elapsed=131.1s

  [7413/20519] intraday_1583.csv.gz  in=300,674,340 out=62,117,183 elapsed=131.1s

  [7414/20519] intraday_15830.csv.gz  in=300,685,574 out=62,128,417 elapsed=131.2s

  [7415/20519] intraday_15832.csv.gz  in=300,697,261 out=62,140,104 elapsed=131.2s

  [7416/20519] intraday_15831.csv.gz  in=300,709,296 out=62,152,139 elapsed=131.2s

  [7417/20519] intraday_15833.csv.gz  in=300,720,534 out=62,163,377 elapsed=131.2s

  [7418/20519] intraday_15834.csv.gz  in=300,731,380 out=62,174,223 elapsed=131.2s

  [7419/20519] intraday_15835.csv.gz  in=300,739,495 out=62,182,338 elapsed=131.3s

  [7420/20519] intraday_15837.csv.gz  in=300,745,847 out=62,188,690 elapsed=131.3s

  [7421/20519] intraday_15838.csv.gz  in=300,762,317 out=62,205,160 elapsed=131.3s

  [7422/20519] intraday_15839.csv.gz  in=300,776,385 out=62,219,228 elapsed=131.3s

  [7423/20519] intraday_1584.csv.gz  in=300,790,301 out=62,219,228 elapsed=131.3s

  [7424/20519] intraday_15836.csv.gz  in=300,801,918 out=62,230,845 elapsed=131.3s

  [7425/20519] intraday_15840.csv.gz  in=300,814,706 out=62,243,633 elapsed=131.3s

  [7426/20519] intraday_15841.csv.gz  in=300,827,726 out=62,256,653 elapsed=131.3s

  [7427/20519] intraday_15842.csv.gz  in=300,839,132 out=62,268,059 elapsed=131.4s

  [7428/20519] intraday_15843.csv.gz  in=300,852,331 out=62,281,258 elapsed=131.4s

  [7429/20519] intraday_15844.csv.gz  in=300,864,315 out=62,293,242 elapsed=131.4s

  [7430/20519] intraday_15845.csv.gz  in=300,876,091 out=62,305,018 elapsed=131.4s

  [7431/20519] intraday_15847.csv.gz  in=300,888,199 out=62,317,126 elapsed=131.4s

  [7432/20519] intraday_15846.csv.gz  in=300,901,047 out=62,329,974 elapsed=131.4s

  [7433/20519] intraday_15848.csv.gz  in=300,911,752 out=62,340,679 elapsed=131.4s

  [7434/20519] intraday_15849.csv.gz  in=300,925,088 out=62,354,015 elapsed=131.4s

  [7435/20519] intraday_1585.csv.gz  in=300,936,257 out=62,354,015 elapsed=131.4s

  [7436/20519] intraday_15850.csv.gz  in=300,949,090 out=62,366,848 elapsed=131.5s

  [7437/20519] intraday_15851.csv.gz  in=300,963,121 out=62,380,312 elapsed=131.5s

  [7438/20519] intraday_15853.csv.gz  in=300,972,172 out=62,389,363 elapsed=131.5s

  [7439/20519] intraday_15852.csv.gz  in=300,981,684 out=62,398,875 elapsed=131.5s

  [7440/20519] intraday_15854.csv.gz  in=300,997,549 out=62,414,740 elapsed=131.5s

  [7441/20519] intraday_15856.csv.gz  in=301,008,393 out=62,425,584 elapsed=131.5s

  [7442/20519] intraday_15855.csv.gz  in=301,020,790 out=62,437,981 elapsed=131.5s

  [7443/20519] intraday_15857.csv.gz  in=301,032,395 out=62,449,586 elapsed=131.6s

  [7444/20519] intraday_15858.csv.gz  in=301,043,986 out=62,461,177 elapsed=131.6s

  [7445/20519] intraday_1586.csv.gz  in=301,056,357 out=62,461,177 elapsed=131.6s

  [7446/20519] intraday_15859.csv.gz  in=301,069,312 out=62,474,132 elapsed=131.6s

  [7447/20519] intraday_15860.csv.gz  in=301,081,355 out=62,486,175 elapsed=131.6s

  [7448/20519] intraday_15861.csv.gz  in=301,093,514 out=62,498,334 elapsed=131.6s

  [7449/20519] intraday_15862.csv.gz  in=301,105,996 out=62,510,816 elapsed=131.6s

  [7450/20519] intraday_15863.csv.gz  in=301,117,059 out=62,521,879 elapsed=131.6s

  [7451/20519] intraday_15864.csv.gz  in=301,127,544 out=62,532,364 elapsed=131.7s

  [7452/20519] intraday_15865.csv.gz  in=301,139,733 out=62,544,553 elapsed=131.7s

  [7453/20519] intraday_15866.csv.gz  in=301,152,682 out=62,557,502 elapsed=131.7s

  [7454/20519] intraday_15867.csv.gz  in=301,164,842 out=62,569,662 elapsed=131.7s

  [7455/20519] intraday_1587.csv.gz  in=301,177,448 out=62,569,662 elapsed=131.8s

  [7456/20519] intraday_15869.csv.gz  in=301,188,405 out=62,580,619 elapsed=131.8s

  [7457/20519] intraday_15868.csv.gz  in=301,204,196 out=62,596,410 elapsed=131.8s

  [7458/20519] intraday_15870.csv.gz  in=301,214,422 out=62,606,636 elapsed=131.8s

  [7459/20519] intraday_15871.csv.gz  in=301,227,055 out=62,619,269 elapsed=131.8s

  [7460/20519] intraday_15873.csv.gz  in=301,238,570 out=62,630,784 elapsed=131.8s

  [7461/20519] intraday_15872.csv.gz  in=301,262,657 out=62,654,871 elapsed=131.9s

  [7462/20519] intraday_15874.csv.gz  in=301,276,131 out=62,668,345 elapsed=131.9s

  [7463/20519] intraday_15875.csv.gz  in=301,286,130 out=62,678,344 elapsed=131.9s

  [7464/20519] intraday_15876.csv.gz  in=301,296,725 out=62,688,939 elapsed=131.9s

  [7465/20519] intraday_15878.csv.gz  in=301,309,315 out=62,701,529 elapsed=131.9s

  [7466/20519] intraday_15877.csv.gz  in=301,318,871 out=62,711,085 elapsed=131.9s

  [7467/20519] intraday_1588.csv.gz  in=301,330,265 out=62,711,085 elapsed=131.9s

  [7468/20519] intraday_15879.csv.gz  in=301,342,230 out=62,723,050 elapsed=131.9s

  [7469/20519] intraday_15881.csv.gz  in=301,352,865 out=62,733,685 elapsed=132.0s

  [7470/20519] intraday_15882.csv.gz  in=301,366,542 out=62,747,362 elapsed=132.0s

  [7471/20519] intraday_15880.csv.gz  in=301,380,445 out=62,761,265 elapsed=132.0s

  [7472/20519] intraday_15884.csv.gz  in=301,392,182 out=62,773,002 elapsed=132.0s

  [7473/20519] intraday_15883.csv.gz  in=301,407,690 out=62,786,550 elapsed=132.0s

  [7474/20519] intraday_15885.csv.gz  in=301,419,279 out=62,798,139 elapsed=132.0s

  [7475/20519] intraday_15886.csv.gz  in=301,430,014 out=62,808,874 elapsed=132.0s

  [7476/20519] intraday_15888.csv.gz  in=301,442,523 out=62,820,359 elapsed=132.1s

  [7477/20519] intraday_15887.csv.gz  in=301,454,938 out=62,832,774 elapsed=132.1s

  [7478/20519] intraday_1589.csv.gz  in=301,466,460 out=62,832,774 elapsed=132.1s

  [7479/20519] intraday_15889.csv.gz  in=301,481,117 out=62,847,431 elapsed=132.1s

  [7480/20519] intraday_15890.csv.gz  in=301,500,528 out=62,863,884 elapsed=132.1s

  [7481/20519] intraday_15891.csv.gz  in=301,513,249 out=62,876,605 elapsed=132.1s

  [7482/20519] intraday_15892.csv.gz  in=301,526,170 out=62,889,526 elapsed=132.1s

  [7483/20519] intraday_15893.csv.gz  in=301,539,248 out=62,902,604 elapsed=132.1s

  [7484/20519] intraday_15894.csv.gz  in=301,549,747 out=62,913,103 elapsed=132.2s

  [7485/20519] intraday_15895.csv.gz  in=301,560,911 out=62,924,267 elapsed=132.2s

  [7486/20519] intraday_15897.csv.gz  in=301,572,790 out=62,936,146 elapsed=132.2s

  [7487/20519] intraday_15898.csv.gz  in=301,584,712 out=62,948,068 elapsed=132.2s

  [7488/20519] intraday_1590.csv.gz  in=301,596,208 out=62,948,068 elapsed=132.2s

  [7489/20519] intraday_15896.csv.gz  in=301,629,880 out=62,971,387 elapsed=132.2s

  [7490/20519] intraday_15899.csv.gz  in=301,646,909 out=62,986,359 elapsed=132.2s

  [7491/20519] intraday_15900.csv.gz  in=301,659,531 out=62,998,981 elapsed=132.3s

  [7492/20519] intraday_15902.csv.gz  in=301,670,798 out=63,010,248 elapsed=132.3s

  [7493/20519] intraday_15901.csv.gz  in=301,681,880 out=63,021,330 elapsed=132.3s

  [7494/20519] intraday_15904.csv.gz  in=301,695,477 out=63,034,927 elapsed=132.3s

  [7495/20519] intraday_15903.csv.gz  in=301,709,363 out=63,048,813 elapsed=132.3s

  [7496/20519] intraday_15905.csv.gz  in=301,722,119 out=63,061,569 elapsed=132.3s

  [7497/20519] intraday_15906.csv.gz  in=301,743,809 out=63,079,675 elapsed=132.3s

  [7498/20519] intraday_15907.csv.gz  in=301,754,319 out=63,090,185 elapsed=132.4s

  [7499/20519] intraday_15909.csv.gz  in=301,767,347 out=63,103,213 elapsed=132.4s

  [7500/20519] intraday_1591.csv.gz  in=301,779,367 out=63,103,213 elapsed=132.4s

  [7501/20519] intraday_15908.csv.gz  in=301,789,822 out=63,113,668 elapsed=132.4s

  [7502/20519] intraday_15910.csv.gz  in=301,799,723 out=63,123,569 elapsed=132.4s

  [7503/20519] intraday_15913.csv.gz  in=301,809,627 out=63,133,473 elapsed=132.4s

  [7504/20519] intraday_15911.csv.gz  in=301,822,116 out=63,145,962 elapsed=132.4s

  [7505/20519] intraday_15912.csv.gz  in=301,832,929 out=63,156,775 elapsed=132.4s

  [7506/20519] intraday_15914.csv.gz  in=301,843,661 out=63,167,507 elapsed=132.4s

  [7507/20519] intraday_15915.csv.gz  in=301,857,458 out=63,181,304 elapsed=132.4s

  [7508/20519] intraday_15916.csv.gz  in=301,868,974 out=63,192,820 elapsed=132.5s

  [7509/20519] intraday_15918.csv.gz  in=301,879,803 out=63,203,649 elapsed=132.5s

  [7510/20519] intraday_15917.csv.gz  in=301,892,188 out=63,216,034 elapsed=132.5s

  [7511/20519] intraday_1592.csv.gz  in=301,903,625 out=63,216,034 elapsed=132.5s

  [7512/20519] intraday_15919.csv.gz  in=301,914,067 out=63,226,476 elapsed=132.5s

  [7513/20519] intraday_15920.csv.gz  in=301,926,619 out=63,239,028 elapsed=132.5s

  [7514/20519] intraday_15921.csv.gz  in=301,940,634 out=63,253,043 elapsed=132.5s

  [7515/20519] intraday_15923.csv.gz  in=301,953,068 out=63,265,477 elapsed=132.6s

  [7516/20519] intraday_15922.csv.gz  in=301,967,185 out=63,279,594 elapsed=132.6s

  [7517/20519] intraday_15925.csv.gz  in=301,978,964 out=63,291,373 elapsed=132.6s

  [7518/20519] intraday_15924.csv.gz  in=301,990,743 out=63,303,152 elapsed=132.6s

  [7519/20519] intraday_15926.csv.gz  in=302,001,386 out=63,313,795 elapsed=132.6s

  [7520/20519] intraday_15927.csv.gz  in=302,015,203 out=63,327,612 elapsed=132.7s

  [7521/20519] intraday_15929.csv.gz  in=302,026,982 out=63,339,391 elapsed=132.7s

  [7522/20519] intraday_1593.csv.gz  in=302,038,901 out=63,339,391 elapsed=132.7s

  [7523/20519] intraday_15928.csv.gz  in=302,050,725 out=63,351,215 elapsed=132.7s

  [7524/20519] intraday_15931.csv.gz  in=302,063,458 out=63,363,948 elapsed=132.7s

  [7525/20519] intraday_15932.csv.gz  in=302,075,382 out=63,375,872 elapsed=132.8s

  [7526/20519] intraday_15933.csv.gz  in=302,087,784 out=63,388,274 elapsed=132.8s

  [7527/20519] intraday_15930.csv.gz  in=302,126,352 out=63,416,342 elapsed=132.8s

  [7528/20519] intraday_15936.csv.gz  in=302,137,661 out=63,427,651 elapsed=132.8s

  [7529/20519] intraday_15935.csv.gz  in=302,150,226 out=63,440,216 elapsed=132.8s

  [7530/20519] intraday_15937.csv.gz  in=302,160,824 out=63,450,814 elapsed=132.9s

  [7531/20519] intraday_15934.csv.gz  in=302,174,227 out=63,464,217 elapsed=132.9s

  [7532/20519] intraday_15938.csv.gz  in=302,185,335 out=63,475,325 elapsed=132.9s

  [7533/20519] intraday_1594.csv.gz  in=302,196,570 out=63,475,325 elapsed=132.9s

  [7534/20519] intraday_15939.csv.gz  in=302,208,956 out=63,487,711 elapsed=132.9s

  [7535/20519] intraday_15941.csv.gz  in=302,221,136 out=63,499,891 elapsed=132.9s

  [7536/20519] intraday_15940.csv.gz  in=302,240,218 out=63,516,858 elapsed=132.9s

  [7537/20519] intraday_15943.csv.gz  in=302,251,332 out=63,527,972 elapsed=133.0s

  [7538/20519] intraday_15942.csv.gz  in=302,262,966 out=63,539,606 elapsed=133.0s

  [7539/20519] intraday_15944.csv.gz  in=302,277,682 out=63,554,322 elapsed=133.0s

  [7540/20519] intraday_15945.csv.gz  in=302,288,069 out=63,564,709 elapsed=133.0s

  [7541/20519] intraday_15946.csv.gz  in=302,299,359 out=63,575,999 elapsed=133.0s

  [7542/20519] intraday_15947.csv.gz  in=302,312,407 out=63,589,047 elapsed=133.0s

  [7543/20519] intraday_15948.csv.gz  in=302,325,788 out=63,602,428 elapsed=133.0s

  [7544/20519] intraday_15949.csv.gz  in=302,336,944 out=63,613,584 elapsed=133.0s

  [7545/20519] intraday_1595.csv.gz  in=302,347,093 out=63,613,584 elapsed=133.0s

  [7546/20519] intraday_15950.csv.gz  in=302,361,038 out=63,627,529 elapsed=133.1s

  [7547/20519] intraday_15951.csv.gz  in=302,375,134 out=63,641,625 elapsed=133.1s

  [7548/20519] intraday_15953.csv.gz  in=302,387,682 out=63,654,173 elapsed=133.1s

  [7549/20519] intraday_15952.csv.gz  in=302,401,839 out=63,668,330 elapsed=133.1s

  [7550/20519] intraday_15954.csv.gz  in=302,418,724 out=63,685,215 elapsed=133.1s

  [7551/20519] intraday_15955.csv.gz  in=302,436,283 out=63,702,774 elapsed=133.1s

  [7552/20519] intraday_15956.csv.gz  in=302,450,096 out=63,716,587 elapsed=133.2s

  [7553/20519] intraday_15957.csv.gz  in=302,463,638 out=63,730,129 elapsed=133.2s

  [7554/20519] intraday_15958.csv.gz  in=302,474,617 out=63,741,108 elapsed=133.2s

  [7555/20519] intraday_15959.csv.gz  in=302,489,582 out=63,756,073 elapsed=133.2s

  [7556/20519] intraday_1596.csv.gz  in=302,501,331 out=63,756,073 elapsed=133.2s

  [7557/20519] intraday_15960.csv.gz  in=302,512,160 out=63,766,902 elapsed=133.2s

  [7558/20519] intraday_15961.csv.gz  in=302,528,191 out=63,781,567 elapsed=133.2s

  [7559/20519] intraday_15962.csv.gz  in=302,538,023 out=63,791,399 elapsed=133.2s

  [7560/20519] intraday_15963.csv.gz  in=302,551,898 out=63,805,274 elapsed=133.3s

  [7561/20519] intraday_15964.csv.gz  in=302,564,279 out=63,817,655 elapsed=133.3s

  [7562/20519] intraday_15966.csv.gz  in=302,575,227 out=63,828,603 elapsed=133.3s

  [7563/20519] intraday_15965.csv.gz  in=302,588,438 out=63,841,814 elapsed=133.3s

  [7564/20519] intraday_15968.csv.gz  in=302,600,651 out=63,854,027 elapsed=133.3s

  [7565/20519] intraday_15969.csv.gz  in=302,613,391 out=63,866,767 elapsed=133.3s

  [7566/20519] intraday_15967.csv.gz  in=302,625,956 out=63,879,332 elapsed=133.3s

  [7567/20519] intraday_1597.csv.gz  in=302,638,087 out=63,879,332 elapsed=133.3s

  [7568/20519] intraday_15970.csv.gz  in=302,653,401 out=63,893,405 elapsed=133.3s

  [7569/20519] intraday_15971.csv.gz  in=302,667,028 out=63,907,032 elapsed=133.4s

  [7570/20519] intraday_15972.csv.gz  in=302,681,342 out=63,921,346 elapsed=133.4s

  [7571/20519] intraday_15973.csv.gz  in=302,693,127 out=63,933,131 elapsed=133.4s

  [7572/20519] intraday_15974.csv.gz  in=302,709,071 out=63,949,075 elapsed=133.4s

  [7573/20519] intraday_15976.csv.gz  in=302,720,721 out=63,960,725 elapsed=133.5s

  [7574/20519] intraday_15977.csv.gz  in=302,733,017 out=63,973,021 elapsed=133.5s

  [7575/20519] intraday_15978.csv.gz  in=302,743,116 out=63,983,120 elapsed=133.5s

  [7576/20519] intraday_15979.csv.gz  in=302,755,115 out=63,995,119 elapsed=133.5s

  [7577/20519] intraday_15975.csv.gz  in=302,765,145 out=64,005,149 elapsed=133.5s

  [7578/20519] intraday_1598.csv.gz  in=302,780,735 out=64,005,149 elapsed=133.5s

  [7579/20519] intraday_15980.csv.gz  in=302,789,705 out=64,014,119 elapsed=133.5s

  [7580/20519] intraday_15982.csv.gz  in=302,798,386 out=64,022,800 elapsed=133.5s

  [7581/20519] intraday_15981.csv.gz  in=302,808,437 out=64,032,851 elapsed=133.5s

  [7582/20519] intraday_15983.csv.gz  in=302,824,012 out=64,048,426 elapsed=133.5s

  [7583/20519] intraday_15984.csv.gz  in=302,836,999 out=64,061,413 elapsed=133.6s

  [7584/20519] intraday_15986.csv.gz  in=302,848,868 out=64,073,282 elapsed=133.6s

  [7585/20519] intraday_15985.csv.gz  in=302,863,497 out=64,087,911 elapsed=133.6s

  [7586/20519] intraday_15987.csv.gz  in=302,878,036 out=64,102,450 elapsed=133.6s

  [7587/20519] intraday_15988.csv.gz  in=302,892,788 out=64,117,202 elapsed=133.6s

  [7588/20519] intraday_15989.csv.gz  in=302,905,150 out=64,129,564 elapsed=133.6s

  [7589/20519] intraday_1599.csv.gz  in=302,930,932 out=64,129,564 elapsed=133.6s

  [7590/20519] intraday_15990.csv.gz  in=302,942,588 out=64,141,220 elapsed=133.6s

  [7591/20519] intraday_15992.csv.gz  in=302,958,060 out=64,156,342 elapsed=133.7s

  [7592/20519] intraday_15991.csv.gz  in=302,969,189 out=64,167,471 elapsed=133.7s

  [7593/20519] intraday_15993.csv.gz  in=302,978,986 out=64,177,268 elapsed=133.7s

  [7594/20519] intraday_15994.csv.gz  in=302,991,541 out=64,189,823 elapsed=133.7s

  [7595/20519] intraday_15997.csv.gz  in=303,001,673 out=64,199,955 elapsed=133.8s

  [7596/20519] intraday_15995.csv.gz  in=303,014,901 out=64,213,183 elapsed=133.8s

  [7597/20519] intraday_15998.csv.gz  in=303,025,841 out=64,224,123 elapsed=133.8s

  [7598/20519] intraday_15996.csv.gz  in=303,038,099 out=64,236,381 elapsed=133.9s

  [7599/20519] intraday_15999.csv.gz  in=303,052,203 out=64,250,485 elapsed=133.9s

  [7600/20519] intraday_1600.csv.gz  in=303,062,288 out=64,250,485 elapsed=133.9s

  [7601/20519] intraday_16000.csv.gz  in=303,074,895 out=64,263,092 elapsed=133.9s

  [7602/20519] intraday_16001.csv.gz  in=303,085,816 out=64,274,013 elapsed=133.9s

  [7603/20519] intraday_16002.csv.gz  in=303,096,028 out=64,284,225 elapsed=133.9s

  [7604/20519] intraday_16004.csv.gz  in=303,108,217 out=64,296,414 elapsed=133.9s

  [7605/20519] intraday_16003.csv.gz  in=303,120,045 out=64,308,242 elapsed=134.0s

  [7606/20519] intraday_16006.csv.gz  in=303,132,633 out=64,320,830 elapsed=134.0s

  [7607/20519] intraday_16007.csv.gz  in=303,144,917 out=64,333,114 elapsed=134.0s

  [7608/20519] intraday_16005.csv.gz  in=303,156,656 out=64,344,853 elapsed=134.0s

  [7609/20519] intraday_16009.csv.gz  in=303,166,413 out=64,354,610 elapsed=134.0s

  [7610/20519] intraday_1601.csv.gz  in=303,177,780 out=64,354,610 elapsed=134.0s

  [7611/20519] intraday_16011.csv.gz  in=303,190,598 out=64,367,428 elapsed=134.1s

  [7612/20519] intraday_16010.csv.gz  in=303,202,393 out=64,379,223 elapsed=134.1s

  [7613/20519] intraday_16008.csv.gz  in=303,235,808 out=64,404,243 elapsed=134.1s

  [7614/20519] intraday_16012.csv.gz  in=303,248,050 out=64,416,485 elapsed=134.1s

  [7615/20519] intraday_16015.csv.gz  in=303,258,471 out=64,426,906 elapsed=134.1s

  [7616/20519] intraday_16014.csv.gz  in=303,271,075 out=64,439,510 elapsed=134.1s

  [7617/20519] intraday_16013.csv.gz  in=303,286,909 out=64,455,013 elapsed=134.1s

  [7618/20519] intraday_16016.csv.gz  in=303,299,776 out=64,467,880 elapsed=134.1s

  [7619/20519] intraday_1602.csv.gz  in=303,312,061 out=64,467,880 elapsed=134.2s

  [7620/20519] intraday_16018.csv.gz  in=303,324,330 out=64,480,149 elapsed=134.2s

  [7621/20519] intraday_16019.csv.gz  in=303,336,574 out=64,492,393 elapsed=134.2s

  [7622/20519] intraday_16017.csv.gz  in=303,360,316 out=64,516,135 elapsed=134.2s

  [7623/20519] intraday_16020.csv.gz  in=303,371,319 out=64,527,138 elapsed=134.2s

  [7624/20519] intraday_16021.csv.gz  in=303,381,348 out=64,537,167 elapsed=134.2s

  [7625/20519] intraday_16022.csv.gz  in=303,390,903 out=64,546,722 elapsed=134.2s

  [7626/20519] intraday_16023.csv.gz  in=303,401,445 out=64,557,264 elapsed=134.2s

  [7627/20519] intraday_16024.csv.gz  in=303,413,027 out=64,568,846 elapsed=134.3s

  [7628/20519] intraday_16025.csv.gz  in=303,427,719 out=64,583,538 elapsed=134.3s

  [7629/20519] intraday_16026.csv.gz  in=303,442,934 out=64,598,753 elapsed=134.3s

  [7630/20519] intraday_16027.csv.gz  in=303,455,887 out=64,611,706 elapsed=134.3s

  [7631/20519] intraday_16029.csv.gz  in=303,468,716 out=64,624,535 elapsed=134.3s

  [7632/20519] intraday_16028.csv.gz  in=303,478,387 out=64,634,206 elapsed=134.3s

  [7633/20519] intraday_16030.csv.gz  in=303,491,536 out=64,646,801 elapsed=134.3s

  [7634/20519] intraday_1603.csv.gz  in=303,506,762 out=64,646,801 elapsed=134.4s

  [7635/20519] intraday_16032.csv.gz  in=303,519,274 out=64,659,313 elapsed=134.4s

  [7636/20519] intraday_16031.csv.gz  in=303,537,779 out=64,674,556 elapsed=134.4s

  [7637/20519] intraday_16034.csv.gz  in=303,551,499 out=64,688,276 elapsed=134.4s

  [7638/20519] intraday_16033.csv.gz  in=303,561,956 out=64,698,733 elapsed=134.4s

  [7639/20519] intraday_16035.csv.gz  in=303,573,716 out=64,710,493 elapsed=134.4s

  [7640/20519] intraday_16036.csv.gz  in=303,586,063 out=64,722,840 elapsed=134.5s

  [7641/20519] intraday_16039.csv.gz  in=303,596,397 out=64,733,174 elapsed=134.5s

  [7642/20519] intraday_16037.csv.gz  in=303,608,543 out=64,745,320 elapsed=134.5s

  [7643/20519] intraday_1604.csv.gz  in=303,620,945 out=64,745,320 elapsed=134.5s

  [7644/20519] intraday_16038.csv.gz  in=303,634,100 out=64,758,475 elapsed=134.5s

  [7645/20519] intraday_16043.csv.gz  in=303,644,702 out=64,769,077 elapsed=134.5s

  [7646/20519] intraday_16041.csv.gz  in=303,659,834 out=64,784,209 elapsed=134.5s

  [7647/20519] intraday_16042.csv.gz  in=303,672,760 out=64,797,135 elapsed=134.5s

  [7648/20519] intraday_16044.csv.gz  in=303,684,460 out=64,808,835 elapsed=134.6s

  [7649/20519] intraday_16040.csv.gz  in=303,697,565 out=64,820,995 elapsed=134.6s

  [7650/20519] intraday_16045.csv.gz  in=303,708,506 out=64,831,936 elapsed=134.6s

  [7651/20519] intraday_16046.csv.gz  in=303,719,265 out=64,842,695 elapsed=134.6s

  [7652/20519] intraday_16047.csv.gz  in=303,731,836 out=64,855,266 elapsed=134.6s

  [7653/20519] intraday_16049.csv.gz  in=303,742,354 out=64,865,784 elapsed=134.6s

  [7654/20519] intraday_16048.csv.gz  in=303,757,533 out=64,880,963 elapsed=134.6s

  [7655/20519] intraday_1605.csv.gz  in=303,771,315 out=64,880,963 elapsed=134.6s

  [7656/20519] intraday_16050.csv.gz  in=303,783,666 out=64,893,314 elapsed=134.7s

  [7657/20519] intraday_16054.csv.gz  in=303,796,695 out=64,906,343 elapsed=134.7s

  [7658/20519] intraday_16053.csv.gz  in=303,808,564 out=64,918,212 elapsed=134.7s

  [7659/20519] intraday_16052.csv.gz  in=303,823,569 out=64,930,910 elapsed=134.7s

  [7660/20519] intraday_16051.csv.gz  in=303,864,857 out=64,960,977 elapsed=134.7s

  [7661/20519] intraday_16056.csv.gz  in=303,879,295 out=64,975,415 elapsed=134.8s

  [7662/20519] intraday_16057.csv.gz  in=303,890,663 out=64,986,067 elapsed=134.8s

  [7663/20519] intraday_16055.csv.gz  in=303,901,792 out=64,997,196 elapsed=134.8s

  [7664/20519] intraday_16058.csv.gz  in=303,911,517 out=65,006,921 elapsed=134.8s

  [7665/20519] intraday_16059.csv.gz  in=303,922,910 out=65,018,314 elapsed=134.8s

  [7666/20519] intraday_1606.csv.gz  in=303,935,895 out=65,018,314 elapsed=134.8s

  [7667/20519] intraday_16060.csv.gz  in=303,949,655 out=65,032,074 elapsed=134.8s

  [7668/20519] intraday_16061.csv.gz  in=303,960,736 out=65,043,155 elapsed=134.9s

  [7669/20519] intraday_16062.csv.gz  in=303,971,987 out=65,054,406 elapsed=134.9s

  [7670/20519] intraday_16063.csv.gz  in=303,981,970 out=65,064,389 elapsed=134.9s

  [7671/20519] intraday_16064.csv.gz  in=303,992,743 out=65,075,162 elapsed=134.9s

  [7672/20519] intraday_16065.csv.gz  in=304,004,523 out=65,086,942 elapsed=134.9s

  [7673/20519] intraday_16066.csv.gz  in=304,019,297 out=65,101,716 elapsed=134.9s

  [7674/20519] intraday_16069.csv.gz  in=304,029,986 out=65,112,405 elapsed=135.0s

  [7675/20519] intraday_16067.csv.gz  in=304,044,382 out=65,126,801 elapsed=135.0s

  [7676/20519] intraday_1607.csv.gz  in=304,058,595 out=65,126,801 elapsed=135.0s

  [7677/20519] intraday_16068.csv.gz  in=304,072,659 out=65,140,865 elapsed=135.0s

  [7678/20519] intraday_16071.csv.gz  in=304,082,705 out=65,150,911 elapsed=135.0s

  [7679/20519] intraday_16070.csv.gz  in=304,099,116 out=65,167,322 elapsed=135.0s

  [7680/20519] intraday_16073.csv.gz  in=304,108,946 out=65,177,152 elapsed=135.0s

  [7681/20519] intraday_16074.csv.gz  in=304,121,244 out=65,189,450 elapsed=135.0s

  [7682/20519] intraday_16072.csv.gz  in=304,135,995 out=65,204,201 elapsed=135.0s

  [7683/20519] intraday_16075.csv.gz  in=304,147,274 out=65,215,480 elapsed=135.1s

  [7684/20519] intraday_16076.csv.gz  in=304,160,309 out=65,228,515 elapsed=135.1s

  [7685/20519] intraday_16078.csv.gz  in=304,173,013 out=65,241,219 elapsed=135.1s

  [7686/20519] intraday_16077.csv.gz  in=304,185,379 out=65,253,585 elapsed=135.1s

  [7687/20519] intraday_16079.csv.gz  in=304,197,395 out=65,265,601 elapsed=135.1s

  [7688/20519] intraday_1608.csv.gz  in=304,211,456 out=65,265,601 elapsed=135.1s

  [7689/20519] intraday_16080.csv.gz  in=304,222,135 out=65,276,280 elapsed=135.1s

  [7690/20519] intraday_16081.csv.gz  in=304,233,845 out=65,287,990 elapsed=135.2s

  [7691/20519] intraday_16083.csv.gz  in=304,244,982 out=65,299,127 elapsed=135.2s

  [7692/20519] intraday_16082.csv.gz  in=304,256,706 out=65,310,851 elapsed=135.2s

  [7693/20519] intraday_16084.csv.gz  in=304,268,090 out=65,322,235 elapsed=135.2s

  [7694/20519] intraday_16085.csv.gz  in=304,281,123 out=65,335,268 elapsed=135.2s

  [7695/20519] intraday_16087.csv.gz  in=304,292,589 out=65,346,734 elapsed=135.2s

  [7696/20519] intraday_16088.csv.gz  in=304,303,558 out=65,357,703 elapsed=135.2s

  [7697/20519] intraday_16086.csv.gz  in=304,315,638 out=65,369,783 elapsed=135.2s

  [7698/20519] intraday_16089.csv.gz  in=304,328,777 out=65,382,922 elapsed=135.3s

  [7699/20519] intraday_1609.csv.gz  in=304,341,894 out=65,382,922 elapsed=135.3s

  [7700/20519] intraday_16090.csv.gz  in=304,353,466 out=65,394,494 elapsed=135.3s

  [7701/20519] intraday_16091.csv.gz  in=304,365,156 out=65,406,184 elapsed=135.3s

  [7702/20519] intraday_16092.csv.gz  in=304,377,277 out=65,418,305 elapsed=135.3s

  [7703/20519] intraday_16095.csv.gz  in=304,391,991 out=65,433,019 elapsed=135.3s

  [7704/20519] intraday_16093.csv.gz  in=304,405,600 out=65,446,628 elapsed=135.3s

  [7705/20519] intraday_16094.csv.gz  in=304,417,089 out=65,458,117 elapsed=135.3s

  [7706/20519] intraday_16096.csv.gz  in=304,429,785 out=65,470,813 elapsed=135.3s

  [7707/20519] intraday_16097.csv.gz  in=304,443,989 out=65,485,017 elapsed=135.4s

  [7708/20519] intraday_16098.csv.gz  in=304,456,555 out=65,497,583 elapsed=135.4s

  [7709/20519] intraday_1610.csv.gz  in=304,469,454 out=65,497,583 elapsed=135.4s

  [7710/20519] intraday_16099.csv.gz  in=304,488,755 out=65,516,884 elapsed=135.4s

  [7711/20519] intraday_16102.csv.gz  in=304,500,047 out=65,528,176 elapsed=135.4s

  [7712/20519] intraday_16101.csv.gz  in=304,515,981 out=65,544,110 elapsed=135.4s

  [7713/20519] intraday_16103.csv.gz  in=304,530,773 out=65,558,902 elapsed=135.4s

  [7714/20519] intraday_16100.csv.gz  in=304,545,308 out=65,573,437 elapsed=135.4s

  [7715/20519] intraday_16104.csv.gz  in=304,557,717 out=65,585,846 elapsed=135.4s

  [7716/20519] intraday_16105.csv.gz  in=304,567,574 out=65,595,703 elapsed=135.5s

  [7717/20519] intraday_16107.csv.gz  in=304,579,868 out=65,607,997 elapsed=135.5s

  [7718/20519] intraday_16106.csv.gz  in=304,591,927 out=65,620,056 elapsed=135.5s

  [7719/20519] intraday_16108.csv.gz  in=304,603,735 out=65,631,864 elapsed=135.5s

  [7720/20519] intraday_16109.csv.gz  in=304,617,249 out=65,645,378 elapsed=135.5s

  [7721/20519] intraday_1611.csv.gz  in=304,628,913 out=65,645,378 elapsed=135.5s

  [7722/20519] intraday_16110.csv.gz  in=304,642,114 out=65,658,575 elapsed=135.5s

  [7723/20519] intraday_16112.csv.gz  in=304,653,312 out=65,669,773 elapsed=135.6s

  [7724/20519] intraday_16113.csv.gz  in=304,666,795 out=65,683,256 elapsed=135.6s

  [7725/20519] intraday_16114.csv.gz  in=304,679,705 out=65,696,166 elapsed=135.6s

  [7726/20519] intraday_16115.csv.gz  in=304,691,203 out=65,707,664 elapsed=135.6s

  [7727/20519] intraday_16116.csv.gz  in=304,705,591 out=65,722,052 elapsed=135.6s

  [7728/20519] intraday_16111.csv.gz  in=304,716,858 out=65,733,319 elapsed=135.6s

  [7729/20519] intraday_16118.csv.gz  in=304,729,114 out=65,745,575 elapsed=135.7s

  [7730/20519] intraday_1612.csv.gz  in=304,740,216 out=65,745,575 elapsed=135.7s

  [7731/20519] intraday_16117.csv.gz  in=304,767,257 out=65,767,997 elapsed=135.7s

  [7732/20519] intraday_16119.csv.gz  in=304,780,340 out=65,781,080 elapsed=135.7s

  [7733/20519] intraday_16120.csv.gz  in=304,792,004 out=65,792,744 elapsed=135.7s

  [7734/20519] intraday_16121.csv.gz  in=304,805,360 out=65,806,100 elapsed=135.8s

  [7735/20519] intraday_16124.csv.gz  in=304,816,079 out=65,816,819 elapsed=135.8s

  [7736/20519] intraday_16122.csv.gz  in=304,826,518 out=65,827,258 elapsed=135.8s

  [7737/20519] intraday_16123.csv.gz  in=304,838,372 out=65,839,112 elapsed=135.8s

  [7738/20519] intraday_16125.csv.gz  in=304,848,071 out=65,848,231 elapsed=135.8s

  [7739/20519] intraday_16127.csv.gz  in=304,851,779 out=65,851,939 elapsed=135.8s

  [7740/20519] intraday_16128.csv.gz  in=304,867,837 out=65,867,997 elapsed=135.9s

  [7741/20519] intraday_16126.csv.gz  in=304,878,591 out=65,878,751 elapsed=135.9s

  [7742/20519] intraday_1613.csv.gz  in=304,893,901 out=65,878,751 elapsed=135.9s

  [7743/20519] intraday_16129.csv.gz  in=304,908,363 out=65,893,213 elapsed=135.9s

  [7744/20519] intraday_16130.csv.gz  in=304,922,407 out=65,907,257 elapsed=135.9s

  [7745/20519] intraday_16131.csv.gz  in=304,934,182 out=65,919,032 elapsed=135.9s

  [7746/20519] intraday_16132.csv.gz  in=304,947,274 out=65,932,124 elapsed=135.9s

  [7747/20519] intraday_16133.csv.gz  in=304,961,669 out=65,946,519 elapsed=135.9s

  [7748/20519] intraday_16134.csv.gz  in=304,974,615 out=65,959,465 elapsed=136.0s

  [7749/20519] intraday_16135.csv.gz  in=304,986,777 out=65,971,627 elapsed=136.0s

  [7750/20519] intraday_16137.csv.gz  in=305,000,308 out=65,985,158 elapsed=136.0s

  [7751/20519] intraday_16136.csv.gz  in=305,012,898 out=65,997,748 elapsed=136.0s

  [7752/20519] intraday_16138.csv.gz  in=305,022,957 out=66,007,807 elapsed=136.0s

  [7753/20519] intraday_1614.csv.gz  in=305,037,249 out=66,007,807 elapsed=136.0s

  [7754/20519] intraday_16139.csv.gz  in=305,050,850 out=66,021,408 elapsed=136.0s

  [7755/20519] intraday_16140.csv.gz  in=305,065,378 out=66,035,936 elapsed=136.0s

  [7756/20519] intraday_16141.csv.gz  in=305,077,181 out=66,047,739 elapsed=136.0s

  [7757/20519] intraday_16142.csv.gz  in=305,088,369 out=66,058,927 elapsed=136.1s

  [7758/20519] intraday_16143.csv.gz  in=305,099,607 out=66,070,165 elapsed=136.1s

  [7759/20519] intraday_16144.csv.gz  in=305,114,382 out=66,084,940 elapsed=136.1s

  [7760/20519] intraday_16145.csv.gz  in=305,129,199 out=66,099,757 elapsed=136.1s

  [7761/20519] intraday_16146.csv.gz  in=305,140,235 out=66,110,793 elapsed=136.1s

  [7762/20519] intraday_16147.csv.gz  in=305,151,142 out=66,121,700 elapsed=136.1s

  [7763/20519] intraday_16148.csv.gz  in=305,163,680 out=66,134,238 elapsed=136.1s

  [7764/20519] intraday_1615.csv.gz  in=305,175,057 out=66,134,238 elapsed=136.1s

  [7765/20519] intraday_16150.csv.gz  in=305,188,004 out=66,147,185 elapsed=136.1s

  [7766/20519] intraday_16149.csv.gz  in=305,200,217 out=66,159,398 elapsed=136.2s

  [7767/20519] intraday_16151.csv.gz  in=305,212,954 out=66,172,135 elapsed=136.2s

  [7768/20519] intraday_16152.csv.gz  in=305,224,869 out=66,184,050 elapsed=136.2s

  [7769/20519] intraday_16154.csv.gz  in=305,236,742 out=66,195,923 elapsed=136.2s

  [7770/20519] intraday_16153.csv.gz  in=305,247,931 out=66,207,112 elapsed=136.2s

  [7771/20519] intraday_16155.csv.gz  in=305,258,925 out=66,218,106 elapsed=136.2s

  [7772/20519] intraday_16156.csv.gz  in=305,274,060 out=66,233,241 elapsed=136.2s

  [7773/20519] intraday_16158.csv.gz  in=305,290,416 out=66,249,597 elapsed=136.3s

  [7774/20519] intraday_1616.csv.gz  in=305,302,707 out=66,249,597 elapsed=136.3s

  [7775/20519] intraday_16157.csv.gz  in=305,317,067 out=66,263,957 elapsed=136.3s

  [7776/20519] intraday_16159.csv.gz  in=305,328,884 out=66,275,774 elapsed=136.3s

  [7777/20519] intraday_16161.csv.gz  in=305,342,024 out=66,288,914 elapsed=136.3s

  [7778/20519] intraday_16163.csv.gz  in=305,354,446 out=66,301,336 elapsed=136.3s

  [7779/20519] intraday_16160.csv.gz  in=305,365,350 out=66,312,240 elapsed=136.3s

  [7780/20519] intraday_16162.csv.gz  in=305,378,428 out=66,325,318 elapsed=136.3s

  [7781/20519] intraday_16164.csv.gz  in=305,391,637 out=66,338,527 elapsed=136.4s

  [7782/20519] intraday_16165.csv.gz  in=305,402,950 out=66,349,840 elapsed=136.4s

  [7783/20519] intraday_16166.csv.gz  in=305,413,412 out=66,360,302 elapsed=136.4s

  [7784/20519] intraday_16167.csv.gz  in=305,424,065 out=66,370,955 elapsed=136.4s

  [7785/20519] intraday_1617.csv.gz  in=305,436,311 out=66,370,955 elapsed=136.4s

  [7786/20519] intraday_16168.csv.gz  in=305,448,247 out=66,382,891 elapsed=136.4s

  [7787/20519] intraday_16169.csv.gz  in=305,460,388 out=66,395,032 elapsed=136.4s

  [7788/20519] intraday_16170.csv.gz  in=305,475,233 out=66,409,877 elapsed=136.4s

  [7789/20519] intraday_16172.csv.gz  in=305,487,663 out=66,422,307 elapsed=136.5s

  [7790/20519] intraday_16171.csv.gz  in=305,501,101 out=66,435,745 elapsed=136.5s

  [7791/20519] intraday_16173.csv.gz  in=305,512,410 out=66,447,054 elapsed=136.5s

  [7792/20519] intraday_16174.csv.gz  in=305,524,626 out=66,459,270 elapsed=136.5s

  [7793/20519] intraday_16177.csv.gz  in=305,537,601 out=66,472,245 elapsed=136.5s

  [7794/20519] intraday_16176.csv.gz  in=305,549,113 out=66,483,757 elapsed=136.5s

  [7795/20519] intraday_16175.csv.gz  in=305,561,053 out=66,495,697 elapsed=136.5s

  [7796/20519] intraday_16178.csv.gz  in=305,571,101 out=66,505,745 elapsed=136.5s

  [7797/20519] intraday_1618.csv.gz  in=305,583,268 out=66,505,745 elapsed=136.5s

  [7798/20519] intraday_16179.csv.gz  in=305,597,632 out=66,520,109 elapsed=136.6s

  [7799/20519] intraday_16181.csv.gz  in=305,610,023 out=66,532,500 elapsed=136.6s

  [7800/20519] intraday_16182.csv.gz  in=305,624,424 out=66,546,901 elapsed=136.6s

  [7801/20519] intraday_16183.csv.gz  in=305,636,819 out=66,559,296 elapsed=136.6s

  [7802/20519] intraday_16180.csv.gz  in=305,648,148 out=66,570,625 elapsed=136.6s

  [7803/20519] intraday_16184.csv.gz  in=305,659,865 out=66,582,342 elapsed=136.6s

  [7804/20519] intraday_16185.csv.gz  in=305,671,494 out=66,593,971 elapsed=136.6s

  [7805/20519] intraday_16187.csv.gz  in=305,683,610 out=66,606,087 elapsed=136.7s

  [7806/20519] intraday_16186.csv.gz  in=305,697,695 out=66,620,172 elapsed=136.7s

  [7807/20519] intraday_16188.csv.gz  in=305,711,232 out=66,633,709 elapsed=136.7s

  [7808/20519] intraday_16189.csv.gz  in=305,720,878 out=66,643,355 elapsed=136.7s

  [7809/20519] intraday_16190.csv.gz  in=305,733,116 out=66,655,593 elapsed=136.7s

  [7810/20519] intraday_1619.csv.gz  in=305,745,558 out=66,655,593 elapsed=136.7s

  [7811/20519] intraday_16192.csv.gz  in=305,759,085 out=66,669,120 elapsed=136.7s

  [7812/20519] intraday_16191.csv.gz  in=305,769,823 out=66,679,858 elapsed=136.8s

  [7813/20519] intraday_16193.csv.gz  in=305,782,773 out=66,692,808 elapsed=136.8s

  [7814/20519] intraday_16194.csv.gz  in=305,796,583 out=66,706,618 elapsed=136.8s

  [7815/20519] intraday_16195.csv.gz  in=305,808,722 out=66,718,757 elapsed=136.8s

  [7816/20519] intraday_16196.csv.gz  in=305,820,914 out=66,730,949 elapsed=136.8s

  [7817/20519] intraday_16197.csv.gz  in=305,828,935 out=66,738,970 elapsed=136.8s

  [7818/20519] intraday_16198.csv.gz  in=305,841,587 out=66,751,622 elapsed=136.9s

  [7819/20519] intraday_16199.csv.gz  in=305,854,849 out=66,764,884 elapsed=136.9s

  [7820/20519] intraday_16200.csv.gz  in=305,866,944 out=66,776,979 elapsed=136.9s

  [7821/20519] intraday_1620.csv.gz  in=305,879,190 out=66,776,979 elapsed=136.9s

  [7822/20519] intraday_16201.csv.gz  in=305,889,034 out=66,786,823 elapsed=136.9s

  [7823/20519] intraday_16202.csv.gz  in=305,901,667 out=66,799,456 elapsed=136.9s

  [7824/20519] intraday_16203.csv.gz  in=305,910,590 out=66,808,379 elapsed=136.9s

  [7825/20519] intraday_16206.csv.gz  in=305,922,501 out=66,820,290 elapsed=137.0s

  [7826/20519] intraday_16204.csv.gz  in=305,934,914 out=66,832,703 elapsed=137.0s

  [7827/20519] intraday_16205.csv.gz  in=305,948,427 out=66,846,216 elapsed=137.0s

  [7828/20519] intraday_16208.csv.gz  in=305,958,279 out=66,856,068 elapsed=137.0s

  [7829/20519] intraday_16207.csv.gz  in=305,969,938 out=66,867,727 elapsed=137.0s

  [7830/20519] intraday_1621.csv.gz  in=305,983,105 out=66,867,727 elapsed=137.0s

  [7831/20519] intraday_16209.csv.gz  in=305,994,135 out=66,878,757 elapsed=137.0s

  [7832/20519] intraday_16212.csv.gz  in=306,008,467 out=66,893,089 elapsed=137.0s

  [7833/20519] intraday_16210.csv.gz  in=306,021,497 out=66,906,119 elapsed=137.1s

  [7834/20519] intraday_16211.csv.gz  in=306,038,880 out=66,923,502 elapsed=137.1s

  [7835/20519] intraday_16213.csv.gz  in=306,052,864 out=66,937,486 elapsed=137.1s

  [7836/20519] intraday_16214.csv.gz  in=306,064,537 out=66,949,159 elapsed=137.1s

  [7837/20519] intraday_16215.csv.gz  in=306,078,723 out=66,963,345 elapsed=137.1s

  [7838/20519] intraday_16216.csv.gz  in=306,089,607 out=66,974,229 elapsed=137.1s

  [7839/20519] intraday_16218.csv.gz  in=306,099,827 out=66,984,449 elapsed=137.2s

  [7840/20519] intraday_16217.csv.gz  in=306,115,183 out=66,999,805 elapsed=137.2s

  [7841/20519] intraday_16219.csv.gz  in=306,128,252 out=67,012,874 elapsed=137.2s

  [7842/20519] intraday_1622.csv.gz  in=306,141,246 out=67,012,874 elapsed=137.2s

  [7843/20519] intraday_16220.csv.gz  in=306,152,870 out=67,024,498 elapsed=137.2s

  [7844/20519] intraday_16222.csv.gz  in=306,165,555 out=67,037,183 elapsed=137.2s

  [7845/20519] intraday_16221.csv.gz  in=306,178,954 out=67,050,582 elapsed=137.2s

  [7846/20519] intraday_16223.csv.gz  in=306,191,699 out=67,063,327 elapsed=137.3s

  [7847/20519] intraday_16224.csv.gz  in=306,206,042 out=67,077,670 elapsed=137.3s

  [7848/20519] intraday_16225.csv.gz  in=306,216,329 out=67,087,957 elapsed=137.3s

  [7849/20519] intraday_16226.csv.gz  in=306,228,025 out=67,099,653 elapsed=137.3s

  [7850/20519] intraday_16228.csv.gz  in=306,240,293 out=67,111,921 elapsed=137.3s

  [7851/20519] intraday_16227.csv.gz  in=306,252,964 out=67,124,592 elapsed=137.3s

  [7852/20519] intraday_16229.csv.gz  in=306,265,928 out=67,137,556 elapsed=137.3s

  [7853/20519] intraday_1623.csv.gz  in=306,280,598 out=67,137,556 elapsed=137.4s

  [7854/20519] intraday_16230.csv.gz  in=306,294,335 out=67,151,293 elapsed=137.4s

  [7855/20519] intraday_16231.csv.gz  in=306,308,026 out=67,164,984 elapsed=137.4s

  [7856/20519] intraday_16232.csv.gz  in=306,318,765 out=67,175,723 elapsed=137.4s

  [7857/20519] intraday_16233.csv.gz  in=306,332,027 out=67,188,985 elapsed=137.4s

  [7858/20519] intraday_16234.csv.gz  in=306,343,656 out=67,200,614 elapsed=137.4s

  [7859/20519] intraday_16235.csv.gz  in=306,356,251 out=67,213,209 elapsed=137.5s

  [7860/20519] intraday_16236.csv.gz  in=306,370,161 out=67,227,119 elapsed=137.5s

  [7861/20519] intraday_16237.csv.gz  in=306,383,319 out=67,240,277 elapsed=137.5s

  [7862/20519] intraday_16238.csv.gz  in=306,396,755 out=67,253,713 elapsed=137.5s

  [7863/20519] intraday_1624.csv.gz  in=306,408,205 out=67,253,713 elapsed=137.5s

  [7864/20519] intraday_16239.csv.gz  in=306,420,044 out=67,265,552 elapsed=137.5s

  [7865/20519] intraday_16240.csv.gz  in=306,434,294 out=67,279,802 elapsed=137.5s

  [7866/20519] intraday_16241.csv.gz  in=306,449,034 out=67,294,542 elapsed=137.6s

  [7867/20519] intraday_16243.csv.gz  in=306,463,837 out=67,309,345 elapsed=138.0s

  [7868/20519] intraday_16242.csv.gz  in=306,478,471 out=67,323,979 elapsed=138.0s

  [7869/20519] intraday_16245.csv.gz  in=306,490,467 out=67,335,975 elapsed=138.0s

  [7870/20519] intraday_16244.csv.gz  in=306,510,245 out=67,355,753 elapsed=138.0s

  [7871/20519] intraday_16246.csv.gz  in=306,526,980 out=67,372,488 elapsed=138.0s

  [7872/20519] intraday_16247.csv.gz  in=306,538,835 out=67,384,343 elapsed=138.0s

  [7873/20519] intraday_16248.csv.gz  in=306,553,582 out=67,399,090 elapsed=138.0s

  [7874/20519] intraday_16249.csv.gz  in=306,564,449 out=67,409,957 elapsed=138.0s

  [7875/20519] intraday_1625.csv.gz  in=306,578,724 out=67,409,957 elapsed=138.0s

  [7876/20519] intraday_16250.csv.gz  in=306,591,228 out=67,422,461 elapsed=138.0s

  [7877/20519] intraday_16251.csv.gz  in=306,602,042 out=67,433,275 elapsed=138.1s

  [7878/20519] intraday_16252.csv.gz  in=306,616,963 out=67,448,196 elapsed=138.1s

  [7879/20519] intraday_16253.csv.gz  in=306,628,306 out=67,459,539 elapsed=138.1s

  [7880/20519] intraday_16254.csv.gz  in=306,643,919 out=67,475,152 elapsed=138.1s

  [7881/20519] intraday_16255.csv.gz  in=306,654,662 out=67,485,895 elapsed=138.1s

  [7882/20519] intraday_16257.csv.gz  in=306,665,285 out=67,496,518 elapsed=138.1s

  [7883/20519] intraday_16256.csv.gz  in=306,677,684 out=67,508,917 elapsed=138.1s

  [7884/20519] intraday_16258.csv.gz  in=306,691,297 out=67,522,530 elapsed=138.1s

  [7885/20519] intraday_1626.csv.gz  in=306,704,893 out=67,522,530 elapsed=138.2s

  [7886/20519] intraday_16259.csv.gz  in=306,717,996 out=67,535,633 elapsed=138.2s

  [7887/20519] intraday_16260.csv.gz  in=306,732,960 out=67,550,597 elapsed=138.2s

  [7888/20519] intraday_16261.csv.gz  in=306,746,842 out=67,564,479 elapsed=138.2s

  [7889/20519] intraday_16262.csv.gz  in=306,761,033 out=67,578,670 elapsed=138.2s

  [7890/20519] intraday_16263.csv.gz  in=306,776,293 out=67,593,930 elapsed=138.2s

  [7891/20519] intraday_16264.csv.gz  in=306,788,295 out=67,605,932 elapsed=138.2s

  [7892/20519] intraday_16266.csv.gz  in=306,801,242 out=67,618,879 elapsed=138.3s

  [7893/20519] intraday_16268.csv.gz  in=306,814,599 out=67,632,236 elapsed=138.3s

  [7894/20519] intraday_16267.csv.gz  in=306,824,247 out=67,641,884 elapsed=138.3s

  [7895/20519] intraday_16265.csv.gz  in=306,836,270 out=67,653,907 elapsed=138.3s

  [7896/20519] intraday_16269.csv.gz  in=306,845,814 out=67,663,451 elapsed=138.3s

  [7897/20519] intraday_16270.csv.gz  in=306,854,289 out=67,671,926 elapsed=138.3s

  [7898/20519] intraday_1627.csv.gz  in=306,871,678 out=67,671,926 elapsed=138.3s

  [7899/20519] intraday_16272.csv.gz  in=306,886,923 out=67,687,171 elapsed=138.3s

  [7900/20519] intraday_16271.csv.gz  in=306,897,747 out=67,697,995 elapsed=138.3s

  [7901/20519] intraday_16273.csv.gz  in=306,911,741 out=67,711,989 elapsed=138.4s

  [7902/20519] intraday_16275.csv.gz  in=306,922,474 out=67,722,722 elapsed=138.4s

  [7903/20519] intraday_16274.csv.gz  in=306,935,594 out=67,735,842 elapsed=138.4s

  [7904/20519] intraday_16276.csv.gz  in=306,947,791 out=67,748,039 elapsed=138.4s

  [7905/20519] intraday_16277.csv.gz  in=306,961,007 out=67,761,255 elapsed=138.4s

  [7906/20519] intraday_1628.csv.gz  in=306,972,235 out=67,761,255 elapsed=138.4s

  [7907/20519] intraday_16278.csv.gz  in=306,984,609 out=67,773,629 elapsed=138.4s

  [7908/20519] intraday_16279.csv.gz  in=306,996,105 out=67,785,125 elapsed=138.5s

  [7909/20519] intraday_16281.csv.gz  in=307,009,404 out=67,798,424 elapsed=138.5s

  [7910/20519] intraday_16282.csv.gz  in=307,018,821 out=67,807,841 elapsed=138.5s

  [7911/20519] intraday_16280.csv.gz  in=307,030,673 out=67,819,693 elapsed=138.5s

  [7912/20519] intraday_16283.csv.gz  in=307,034,028 out=67,823,048 elapsed=138.5s

  [7913/20519] intraday_16284.csv.gz  in=307,041,673 out=67,830,693 elapsed=138.5s

  [7914/20519] intraday_16285.csv.gz  in=307,056,556 out=67,845,576 elapsed=138.5s

  [7915/20519] intraday_16287.csv.gz  in=307,069,330 out=67,858,350 elapsed=138.6s

  [7916/20519] intraday_16286.csv.gz  in=307,083,004 out=67,872,024 elapsed=138.6s

  [7917/20519] intraday_16289.csv.gz  in=307,095,988 out=67,885,008 elapsed=138.6s

  [7918/20519] intraday_16288.csv.gz  in=307,106,349 out=67,895,369 elapsed=138.6s

  [7919/20519] intraday_1629.csv.gz  in=307,119,756 out=67,895,369 elapsed=138.6s

  [7920/20519] intraday_16290.csv.gz  in=307,132,388 out=67,908,001 elapsed=138.6s

  [7921/20519] intraday_16291.csv.gz  in=307,146,882 out=67,921,379 elapsed=138.6s

  [7922/20519] intraday_16292.csv.gz  in=307,159,559 out=67,934,056 elapsed=138.7s

  [7923/20519] intraday_16294.csv.gz  in=307,171,487 out=67,945,984 elapsed=138.7s

  [7924/20519] intraday_16293.csv.gz  in=307,184,675 out=67,959,026 elapsed=138.7s

  [7925/20519] intraday_16295.csv.gz  in=307,194,879 out=67,969,230 elapsed=138.7s

  [7926/20519] intraday_16296.csv.gz  in=307,206,837 out=67,981,188 elapsed=138.7s

  [7927/20519] intraday_16297.csv.gz  in=307,219,590 out=67,993,941 elapsed=138.7s

  [7928/20519] intraday_16298.csv.gz  in=307,231,744 out=68,006,095 elapsed=138.7s

  [7929/20519] intraday_1630.csv.gz  in=307,247,733 out=68,006,095 elapsed=138.8s

  [7930/20519] intraday_16301.csv.gz  in=307,258,637 out=68,016,999 elapsed=138.8s

  [7931/20519] intraday_16302.csv.gz  in=307,260,247 out=68,018,609 elapsed=138.8s

  [7932/20519] intraday_16299.csv.gz  in=307,275,714 out=68,034,076 elapsed=138.9s

  [7933/20519] intraday_16303.csv.gz  in=307,276,184 out=68,034,546 elapsed=138.9s

  [7934/20519] intraday_16300.csv.gz  in=307,290,668 out=68,049,030 elapsed=138.9s

  [7935/20519] intraday_16304.csv.gz  in=307,300,360 out=68,058,722 elapsed=138.9s

  [7936/20519] intraday_16306.csv.gz  in=307,310,258 out=68,068,620 elapsed=138.9s

  [7937/20519] intraday_16305.csv.gz  in=307,321,348 out=68,079,710 elapsed=139.0s

  [7938/20519] intraday_16308.csv.gz  in=307,333,575 out=68,091,937 elapsed=139.0s

  [7939/20519] intraday_16307.csv.gz  in=307,345,606 out=68,103,968 elapsed=139.0s

  [7940/20519] intraday_16309.csv.gz  in=307,360,588 out=68,118,950 elapsed=139.0s

  [7941/20519] intraday_1631.csv.gz  in=307,373,327 out=68,118,950 elapsed=139.0s

  [7942/20519] intraday_16310.csv.gz  in=307,384,414 out=68,130,037 elapsed=139.0s

  [7943/20519] intraday_16312.csv.gz  in=307,394,826 out=68,140,449 elapsed=139.0s

  [7944/20519] intraday_16313.csv.gz  in=307,406,917 out=68,152,540 elapsed=139.0s

  [7945/20519] intraday_16311.csv.gz  in=307,421,311 out=68,166,934 elapsed=139.1s

  [7946/20519] intraday_16314.csv.gz  in=307,432,559 out=68,178,182 elapsed=139.1s

  [7947/20519] intraday_16315.csv.gz  in=307,444,272 out=68,189,895 elapsed=139.1s

  [7948/20519] intraday_16316.csv.gz  in=307,456,958 out=68,202,581 elapsed=139.1s

  [7949/20519] intraday_16319.csv.gz  in=307,462,720 out=68,208,343 elapsed=139.1s

  [7950/20519] intraday_16317.csv.gz  in=307,473,260 out=68,218,883 elapsed=139.1s

  [7951/20519] intraday_16318.csv.gz  in=307,483,177 out=68,228,800 elapsed=139.1s

  [7952/20519] intraday_1632.csv.gz  in=307,496,220 out=68,228,800 elapsed=139.2s

  [7953/20519] intraday_16321.csv.gz  in=307,508,077 out=68,240,657 elapsed=139.2s

  [7954/20519] intraday_16322.csv.gz  in=307,518,742 out=68,251,322 elapsed=139.2s

  [7955/20519] intraday_16320.csv.gz  in=307,531,028 out=68,263,608 elapsed=139.2s

  [7956/20519] intraday_16323.csv.gz  in=307,544,304 out=68,276,884 elapsed=139.2s

  [7957/20519] intraday_16325.csv.gz  in=307,556,400 out=68,288,980 elapsed=139.2s

  [7958/20519] intraday_16326.csv.gz  in=307,566,885 out=68,299,465 elapsed=139.3s

  [7959/20519] intraday_16324.csv.gz  in=307,579,930 out=68,312,510 elapsed=139.3s

  [7960/20519] intraday_16327.csv.gz  in=307,592,108 out=68,324,688 elapsed=139.3s

  [7961/20519] intraday_16328.csv.gz  in=307,607,108 out=68,337,674 elapsed=139.3s

  [7962/20519] intraday_1633.csv.gz  in=307,621,981 out=68,337,674 elapsed=139.3s

  [7963/20519] intraday_16329.csv.gz  in=307,635,103 out=68,350,796 elapsed=139.3s

  [7964/20519] intraday_16330.csv.gz  in=307,648,833 out=68,364,526 elapsed=139.3s

  [7965/20519] intraday_16332.csv.gz  in=307,662,268 out=68,377,961 elapsed=139.3s

  [7966/20519] intraday_16333.csv.gz  in=307,676,080 out=68,391,773 elapsed=139.4s

  [7967/20519] intraday_16334.csv.gz  in=307,677,396 out=68,393,089 elapsed=139.4s

  [7968/20519] intraday_16331.csv.gz  in=307,688,623 out=68,404,316 elapsed=139.4s

  [7969/20519] intraday_16335.csv.gz  in=307,700,282 out=68,415,975 elapsed=139.4s

  [7970/20519] intraday_16336.csv.gz  in=307,712,387 out=68,428,080 elapsed=139.4s

  [7971/20519] intraday_16337.csv.gz  in=307,722,983 out=68,438,676 elapsed=139.4s

  [7972/20519] intraday_16338.csv.gz  in=307,732,539 out=68,448,232 elapsed=139.4s

  [7973/20519] intraday_16339.csv.gz  in=307,743,778 out=68,459,471 elapsed=139.4s

  [7974/20519] intraday_1634.csv.gz  in=307,754,419 out=68,459,471 elapsed=139.4s

  [7975/20519] intraday_16340.csv.gz  in=307,767,974 out=68,473,026 elapsed=139.5s

  [7976/20519] intraday_16343.csv.gz  in=307,777,489 out=68,482,541 elapsed=139.5s

  [7977/20519] intraday_16341.csv.gz  in=307,788,809 out=68,493,861 elapsed=139.5s

  [7978/20519] intraday_16344.csv.gz  in=307,800,379 out=68,505,431 elapsed=139.5s

  [7979/20519] intraday_16342.csv.gz  in=307,813,308 out=68,518,360 elapsed=139.5s

  [7980/20519] intraday_16345.csv.gz  in=307,824,885 out=68,529,937 elapsed=139.5s

  [7981/20519] intraday_16346.csv.gz  in=307,840,520 out=68,545,572 elapsed=139.6s

  [7982/20519] intraday_16347.csv.gz  in=307,854,713 out=68,559,765 elapsed=139.6s

  [7983/20519] intraday_16348.csv.gz  in=307,869,543 out=68,574,595 elapsed=139.6s

  [7984/20519] intraday_1635.csv.gz  in=307,881,466 out=68,574,595 elapsed=139.6s

  [7985/20519] intraday_16349.csv.gz  in=307,894,116 out=68,587,245 elapsed=139.6s

  [7986/20519] intraday_16350.csv.gz  in=307,908,402 out=68,601,531 elapsed=139.6s

  [7987/20519] intraday_16351.csv.gz  in=307,919,125 out=68,612,254 elapsed=139.6s

  [7988/20519] intraday_16353.csv.gz  in=307,929,315 out=68,622,444 elapsed=139.6s

  [7989/20519] intraday_16352.csv.gz  in=307,943,170 out=68,636,299 elapsed=139.6s

  [7990/20519] intraday_16354.csv.gz  in=307,954,536 out=68,647,665 elapsed=139.7s

  [7991/20519] intraday_16356.csv.gz  in=307,959,305 out=68,652,434 elapsed=139.7s

  [7992/20519] intraday_16357.csv.gz  in=307,966,356 out=68,659,485 elapsed=139.7s

  [7993/20519] intraday_16355.csv.gz  in=307,978,228 out=68,671,357 elapsed=139.7s

  [7994/20519] intraday_16358.csv.gz  in=307,988,959 out=68,682,088 elapsed=139.7s

  [7995/20519] intraday_1636.csv.gz  in=308,001,505 out=68,682,088 elapsed=139.7s

  [7996/20519] intraday_16360.csv.gz  in=308,012,785 out=68,693,368 elapsed=139.7s

  [7997/20519] intraday_16359.csv.gz  in=308,024,829 out=68,705,412 elapsed=139.8s

  [7998/20519] intraday_16362.csv.gz  in=308,037,256 out=68,717,839 elapsed=139.8s

  [7999/20519] intraday_16361.csv.gz  in=308,057,212 out=68,734,059 elapsed=139.8s

  [8000/20519] intraday_16363.csv.gz  in=308,069,467 out=68,746,314 elapsed=139.8s

  [8001/20519] intraday_16364.csv.gz  in=308,082,086 out=68,758,933 elapsed=139.8s

  [8002/20519] intraday_16365.csv.gz  in=308,094,229 out=68,771,076 elapsed=139.8s

  [8003/20519] intraday_16366.csv.gz  in=308,106,235 out=68,783,082 elapsed=139.9s

  [8004/20519] intraday_16368.csv.gz  in=308,117,106 out=68,793,953 elapsed=139.9s

  [8005/20519] intraday_16367.csv.gz  in=308,133,338 out=68,810,185 elapsed=139.9s

  [8006/20519] intraday_16369.csv.gz  in=308,144,904 out=68,821,751 elapsed=139.9s

  [8007/20519] intraday_1637.csv.gz  in=308,159,104 out=68,821,751 elapsed=139.9s

  [8008/20519] intraday_16370.csv.gz  in=308,171,777 out=68,834,424 elapsed=139.9s

  [8009/20519] intraday_16371.csv.gz  in=308,186,914 out=68,849,561 elapsed=140.0s

  [8010/20519] intraday_16373.csv.gz  in=308,200,142 out=68,862,789 elapsed=140.0s

  [8011/20519] intraday_16372.csv.gz  in=308,211,519 out=68,874,166 elapsed=140.0s

  [8012/20519] intraday_16374.csv.gz  in=308,224,587 out=68,887,234 elapsed=140.0s

  [8013/20519] intraday_16375.csv.gz  in=308,237,267 out=68,899,914 elapsed=140.0s

  [8014/20519] intraday_16376.csv.gz  in=308,250,030 out=68,912,677 elapsed=140.0s

  [8015/20519] intraday_16377.csv.gz  in=308,268,010 out=68,930,657 elapsed=140.0s

  [8016/20519] intraday_16378.csv.gz  in=308,286,065 out=68,947,739 elapsed=140.0s

  [8017/20519] intraday_16379.csv.gz  in=308,301,435 out=68,963,109 elapsed=140.1s

  [8018/20519] intraday_1638.csv.gz  in=308,317,016 out=68,963,109 elapsed=140.1s

  [8019/20519] intraday_16380.csv.gz  in=308,333,166 out=68,979,259 elapsed=140.1s

  [8020/20519] intraday_16381.csv.gz  in=308,345,870 out=68,991,963 elapsed=140.1s

  [8021/20519] intraday_16382.csv.gz  in=308,359,359 out=69,005,452 elapsed=140.1s

  [8022/20519] intraday_16383.csv.gz  in=308,369,235 out=69,015,328 elapsed=140.1s

  [8023/20519] intraday_16386.csv.gz  in=308,381,915 out=69,028,008 elapsed=140.1s

  [8024/20519] intraday_16387.csv.gz  in=308,395,892 out=69,041,985 elapsed=140.1s

  [8025/20519] intraday_16385.csv.gz  in=308,407,197 out=69,053,290 elapsed=140.1s

  [8026/20519] intraday_16384.csv.gz  in=308,419,794 out=69,065,887 elapsed=140.1s

  [8027/20519] intraday_16388.csv.gz  in=308,433,087 out=69,079,180 elapsed=140.2s

  [8028/20519] intraday_1639.csv.gz  in=308,446,315 out=69,079,180 elapsed=140.2s

  [8029/20519] intraday_16389.csv.gz  in=308,456,316 out=69,089,181 elapsed=140.2s

  [8030/20519] intraday_16390.csv.gz  in=308,467,966 out=69,100,831 elapsed=140.2s

  [8031/20519] intraday_16391.csv.gz  in=308,480,533 out=69,113,398 elapsed=140.2s

  [8032/20519] intraday_16392.csv.gz  in=308,492,903 out=69,125,768 elapsed=140.2s

  [8033/20519] intraday_16394.csv.gz  in=308,494,183 out=69,127,048 elapsed=140.2s

  [8034/20519] intraday_16393.csv.gz  in=308,505,850 out=69,138,715 elapsed=140.2s

  [8035/20519] intraday_16396.csv.gz  in=308,517,350 out=69,150,215 elapsed=140.2s

  [8036/20519] intraday_16395.csv.gz  in=308,531,657 out=69,164,522 elapsed=140.2s

  [8037/20519] intraday_16397.csv.gz  in=308,543,901 out=69,176,766 elapsed=140.3s

  [8038/20519] intraday_16398.csv.gz  in=308,555,955 out=69,188,820 elapsed=140.3s

  [8039/20519] intraday_1640.csv.gz  in=308,569,895 out=69,188,820 elapsed=140.3s

  [8040/20519] intraday_16399.csv.gz  in=308,580,624 out=69,199,549 elapsed=140.3s

  [8041/20519] intraday_16401.csv.gz  in=308,588,384 out=69,207,309 elapsed=140.3s

  [8042/20519] intraday_16400.csv.gz  in=308,600,380 out=69,219,305 elapsed=140.3s

  [8043/20519] intraday_16402.csv.gz  in=308,610,259 out=69,229,184 elapsed=140.3s

  [8044/20519] intraday_16403.csv.gz  in=308,616,244 out=69,235,169 elapsed=140.3s

  [8045/20519] intraday_16404.csv.gz  in=308,631,973 out=69,250,898 elapsed=140.4s

  [8046/20519] intraday_16405.csv.gz  in=308,646,202 out=69,265,127 elapsed=140.4s

  [8047/20519] intraday_16407.csv.gz  in=308,656,612 out=69,275,537 elapsed=140.4s

  [8048/20519] intraday_16406.csv.gz  in=308,672,650 out=69,291,575 elapsed=140.4s

  [8049/20519] intraday_16408.csv.gz  in=308,684,839 out=69,303,764 elapsed=140.4s

  [8050/20519] intraday_16409.csv.gz  in=308,699,853 out=69,318,778 elapsed=140.4s

  [8051/20519] intraday_16411.csv.gz  in=308,699,891 out=69,318,816 elapsed=140.4s

  [8052/20519] intraday_1641.csv.gz  in=308,713,991 out=69,318,816 elapsed=140.4s

  [8053/20519] intraday_16410.csv.gz  in=308,724,625 out=69,329,450 elapsed=140.5s

  [8054/20519] intraday_16412.csv.gz  in=308,728,634 out=69,333,459 elapsed=140.5s

  [8055/20519] intraday_16413.csv.gz  in=308,741,017 out=69,345,842 elapsed=140.5s

  [8056/20519] intraday_16415.csv.gz  in=308,753,244 out=69,358,069 elapsed=140.5s

  [8057/20519] intraday_16416.csv.gz  in=308,763,484 out=69,368,309 elapsed=140.5s

  [8058/20519] intraday_16414.csv.gz  in=308,777,662 out=69,382,487 elapsed=140.5s

  [8059/20519] intraday_16417.csv.gz  in=308,790,298 out=69,395,123 elapsed=140.5s

  [8060/20519] intraday_16418.csv.gz  in=308,804,982 out=69,409,807 elapsed=140.5s

  [8061/20519] intraday_16419.csv.gz  in=308,818,580 out=69,423,405 elapsed=140.5s

  [8062/20519] intraday_1642.csv.gz  in=308,831,754 out=69,423,405 elapsed=140.5s

  [8063/20519] intraday_16420.csv.gz  in=308,842,666 out=69,434,317 elapsed=140.6s

  [8064/20519] intraday_16422.csv.gz  in=308,855,122 out=69,446,773 elapsed=140.6s

  [8065/20519] intraday_16423.csv.gz  in=308,868,086 out=69,459,737 elapsed=140.6s

  [8066/20519] intraday_16421.csv.gz  in=308,878,680 out=69,470,331 elapsed=140.6s

  [8067/20519] intraday_16424.csv.gz  in=308,891,365 out=69,483,016 elapsed=140.6s

  [8068/20519] intraday_16425.csv.gz  in=308,903,961 out=69,495,612 elapsed=140.6s

  [8069/20519] intraday_16426.csv.gz  in=308,915,572 out=69,507,223 elapsed=140.7s

  [8070/20519] intraday_16427.csv.gz  in=308,927,018 out=69,518,669 elapsed=140.7s

  [8071/20519] intraday_16428.csv.gz  in=308,938,011 out=69,529,662 elapsed=140.7s

  [8072/20519] intraday_16429.csv.gz  in=308,949,571 out=69,541,222 elapsed=140.7s

  [8073/20519] intraday_1643.csv.gz  in=308,961,975 out=69,541,222 elapsed=140.7s

  [8074/20519] intraday_16430.csv.gz  in=308,963,214 out=69,542,461 elapsed=140.7s

  [8075/20519] intraday_16431.csv.gz  in=308,972,386 out=69,551,633 elapsed=140.7s

  [8076/20519] intraday_16432.csv.gz  in=308,984,960 out=69,564,207 elapsed=140.8s

  [8077/20519] intraday_16434.csv.gz  in=308,998,200 out=69,577,447 elapsed=140.8s

  [8078/20519] intraday_16435.csv.gz  in=309,010,756 out=69,590,003 elapsed=140.8s

  [8079/20519] intraday_16433.csv.gz  in=309,024,239 out=69,603,486 elapsed=140.8s

  [8080/20519] intraday_16437.csv.gz  in=309,035,072 out=69,614,319 elapsed=140.8s

  [8081/20519] intraday_16439.csv.gz  in=309,047,399 out=69,626,646 elapsed=140.8s

  [8082/20519] intraday_16436.csv.gz  in=309,072,470 out=69,647,962 elapsed=140.8s

  [8083/20519] intraday_1644.csv.gz  in=309,088,528 out=69,647,962 elapsed=140.8s

  [8084/20519] intraday_16438.csv.gz  in=309,098,526 out=69,657,960 elapsed=140.8s

  [8085/20519] intraday_16442.csv.gz  in=309,111,836 out=69,671,270 elapsed=140.9s

  [8086/20519] intraday_16443.csv.gz  in=309,124,576 out=69,684,010 elapsed=140.9s

  [8087/20519] intraday_16441.csv.gz  in=309,138,216 out=69,697,650 elapsed=140.9s

  [8088/20519] intraday_16440.csv.gz  in=309,150,540 out=69,709,974 elapsed=141.0s

  [8089/20519] intraday_16444.csv.gz  in=309,161,612 out=69,721,046 elapsed=141.0s

  [8090/20519] intraday_16445.csv.gz  in=309,173,321 out=69,732,755 elapsed=141.0s

  [8091/20519] intraday_16446.csv.gz  in=309,186,350 out=69,745,784 elapsed=141.0s

  [8092/20519] intraday_16447.csv.gz  in=309,198,607 out=69,758,041 elapsed=141.0s

  [8093/20519] intraday_16448.csv.gz  in=309,211,242 out=69,770,676 elapsed=141.0s

  [8094/20519] intraday_16449.csv.gz  in=309,222,305 out=69,781,739 elapsed=141.0s

  [8095/20519] intraday_1645.csv.gz  in=309,237,738 out=69,781,739 elapsed=141.0s

  [8096/20519] intraday_16450.csv.gz  in=309,251,892 out=69,795,893 elapsed=141.1s

  [8097/20519] intraday_16451.csv.gz  in=309,263,574 out=69,807,575 elapsed=141.1s

  [8098/20519] intraday_16452.csv.gz  in=309,278,157 out=69,822,158 elapsed=141.1s

  [8099/20519] intraday_16453.csv.gz  in=309,290,972 out=69,834,973 elapsed=141.1s

  [8100/20519] intraday_16455.csv.gz  in=309,302,567 out=69,846,568 elapsed=141.1s

  [8101/20519] intraday_16454.csv.gz  in=309,314,675 out=69,858,676 elapsed=141.1s

  [8102/20519] intraday_16457.csv.gz  in=309,327,814 out=69,871,815 elapsed=141.1s

  [8103/20519] intraday_16456.csv.gz  in=309,340,169 out=69,884,170 elapsed=141.2s

  [8104/20519] intraday_16458.csv.gz  in=309,352,078 out=69,896,079 elapsed=141.2s

  [8105/20519] intraday_16459.csv.gz  in=309,364,909 out=69,908,910 elapsed=141.2s

  [8106/20519] intraday_16460.csv.gz  in=309,372,257 out=69,916,258 elapsed=141.2s

  [8107/20519] intraday_1646.csv.gz  in=309,384,564 out=69,916,258 elapsed=141.2s

  [8108/20519] intraday_16461.csv.gz  in=309,397,323 out=69,929,017 elapsed=141.3s

  [8109/20519] intraday_16464.csv.gz  in=309,408,917 out=69,940,611 elapsed=141.3s

  [8110/20519] intraday_16462.csv.gz  in=309,422,632 out=69,954,326 elapsed=141.3s

  [8111/20519] intraday_16465.csv.gz  in=309,432,258 out=69,963,952 elapsed=141.3s

  [8112/20519] intraday_16463.csv.gz  in=309,444,858 out=69,976,552 elapsed=141.3s

  [8113/20519] intraday_16466.csv.gz  in=309,456,328 out=69,988,022 elapsed=141.3s

  [8114/20519] intraday_16469.csv.gz  in=309,467,499 out=69,999,193 elapsed=141.3s

  [8115/20519] intraday_1647.csv.gz  in=309,482,439 out=69,999,193 elapsed=141.3s

  [8116/20519] intraday_16467.csv.gz  in=309,495,777 out=70,012,531 elapsed=141.3s

  [8117/20519] intraday_16468.csv.gz  in=309,508,252 out=70,025,006 elapsed=141.3s

  [8118/20519] intraday_16471.csv.gz  in=309,517,174 out=70,033,928 elapsed=141.4s

  [8119/20519] intraday_16470.csv.gz  in=309,530,081 out=70,046,835 elapsed=141.4s

  [8120/20519] intraday_16473.csv.gz  in=309,542,958 out=70,059,712 elapsed=141.4s

  [8121/20519] intraday_16472.csv.gz  in=309,556,798 out=70,073,552 elapsed=141.4s

  [8122/20519] intraday_16474.csv.gz  in=309,569,015 out=70,085,769 elapsed=141.5s

  [8123/20519] intraday_16476.csv.gz  in=309,579,605 out=70,096,359 elapsed=141.5s

  [8124/20519] intraday_16475.csv.gz  in=309,591,169 out=70,107,923 elapsed=141.5s

  [8125/20519] intraday_16478.csv.gz  in=309,603,249 out=70,120,003 elapsed=141.5s

  [8126/20519] intraday_16477.csv.gz  in=309,613,922 out=70,130,676 elapsed=141.5s

  [8127/20519] intraday_1648.csv.gz  in=309,624,814 out=70,130,676 elapsed=141.5s

  [8128/20519] intraday_16479.csv.gz  in=309,643,633 out=70,149,495 elapsed=141.5s

  [8129/20519] intraday_16480.csv.gz  in=309,652,486 out=70,158,348 elapsed=141.6s

  [8130/20519] intraday_16481.csv.gz  in=309,661,916 out=70,167,778 elapsed=141.6s

  [8131/20519] intraday_16482.csv.gz  in=309,679,730 out=70,185,592 elapsed=141.6s

  [8132/20519] intraday_16483.csv.gz  in=309,690,082 out=70,195,944 elapsed=141.7s

  [8133/20519] intraday_16485.csv.gz  in=309,701,470 out=70,207,332 elapsed=141.7s

  [8134/20519] intraday_16484.csv.gz  in=309,714,126 out=70,219,988 elapsed=141.7s

  [8135/20519] intraday_16487.csv.gz  in=309,727,107 out=70,232,969 elapsed=141.7s

  [8136/20519] intraday_16486.csv.gz  in=309,739,261 out=70,245,123 elapsed=141.7s

  [8137/20519] intraday_16488.csv.gz  in=309,753,456 out=70,257,838 elapsed=141.8s

  [8138/20519] intraday_16490.csv.gz  in=309,764,092 out=70,268,474 elapsed=141.8s

  [8139/20519] intraday_16489.csv.gz  in=309,778,719 out=70,283,101 elapsed=141.8s

  [8140/20519] intraday_1649.csv.gz  in=309,790,185 out=70,283,101 elapsed=141.8s

  [8141/20519] intraday_16491.csv.gz  in=309,800,756 out=70,293,672 elapsed=141.8s

  [8142/20519] intraday_16493.csv.gz  in=309,813,416 out=70,306,332 elapsed=141.9s

  [8143/20519] intraday_16492.csv.gz  in=309,826,458 out=70,319,374 elapsed=141.9s

  [8144/20519] intraday_16494.csv.gz  in=309,838,975 out=70,331,891 elapsed=141.9s

  [8145/20519] intraday_16495.csv.gz  in=309,852,516 out=70,345,432 elapsed=141.9s

  [8146/20519] intraday_16497.csv.gz  in=309,863,420 out=70,356,336 elapsed=141.9s

  [8147/20519] intraday_16496.csv.gz  in=309,876,415 out=70,369,331 elapsed=141.9s

  [8148/20519] intraday_16498.csv.gz  in=309,890,997 out=70,383,913 elapsed=141.9s

  [8149/20519] intraday_1650.csv.gz  in=309,903,194 out=70,383,913 elapsed=141.9s

  [8150/20519] intraday_16500.csv.gz  in=309,914,896 out=70,395,615 elapsed=141.9s

  [8151/20519] intraday_16501.csv.gz  in=309,927,648 out=70,408,367 elapsed=142.0s

  [8152/20519] intraday_16502.csv.gz  in=309,941,652 out=70,422,371 elapsed=142.0s

  [8153/20519] intraday_16503.csv.gz  in=309,954,546 out=70,435,265 elapsed=142.0s

  [8154/20519] intraday_16504.csv.gz  in=309,966,577 out=70,447,296 elapsed=142.1s

  [8155/20519] intraday_16499.csv.gz  in=310,019,934 out=70,496,880 elapsed=142.1s

  [8156/20519] intraday_16506.csv.gz  in=310,034,103 out=70,511,049 elapsed=142.1s

  [8157/20519] intraday_16505.csv.gz  in=310,047,580 out=70,524,526 elapsed=142.1s

  [8158/20519] intraday_16507.csv.gz  in=310,062,300 out=70,539,246 elapsed=142.1s

  [8159/20519] intraday_16508.csv.gz  in=310,077,263 out=70,554,209 elapsed=142.1s

  [8160/20519] intraday_1651.csv.gz  in=310,088,892 out=70,554,209 elapsed=142.1s

  [8161/20519] intraday_16510.csv.gz  in=310,102,635 out=70,567,952 elapsed=142.2s

  [8162/20519] intraday_16509.csv.gz  in=310,120,670 out=70,585,987 elapsed=142.2s

  [8163/20519] intraday_16511.csv.gz  in=310,136,323 out=70,601,640 elapsed=142.2s

  [8164/20519] intraday_16513.csv.gz  in=310,138,106 out=70,603,423 elapsed=142.2s

  [8165/20519] intraday_16512.csv.gz  in=310,150,000 out=70,615,317 elapsed=142.2s

  [8166/20519] intraday_16514.csv.gz  in=310,157,058 out=70,622,375 elapsed=142.3s

  [8167/20519] intraday_16517.csv.gz  in=310,173,151 out=70,638,468 elapsed=142.3s

  [8168/20519] intraday_16516.csv.gz  in=310,186,361 out=70,651,678 elapsed=142.3s

  [8169/20519] intraday_16515.csv.gz  in=310,199,871 out=70,665,188 elapsed=142.3s

  [8170/20519] intraday_16518.csv.gz  in=310,210,816 out=70,676,133 elapsed=142.3s

  [8171/20519] intraday_1652.csv.gz  in=310,220,512 out=70,676,133 elapsed=142.4s

  [8172/20519] intraday_16519.csv.gz  in=310,233,102 out=70,688,723 elapsed=142.4s

  [8173/20519] intraday_16520.csv.gz  in=310,244,413 out=70,700,034 elapsed=142.4s

  [8174/20519] intraday_16522.csv.gz  in=310,256,673 out=70,712,294 elapsed=142.5s

  [8175/20519] intraday_16523.csv.gz  in=310,270,713 out=70,726,334 elapsed=142.5s

  [8176/20519] intraday_16521.csv.gz  in=310,283,899 out=70,739,520 elapsed=142.5s

  [8177/20519] intraday_16524.csv.gz  in=310,298,209 out=70,753,830 elapsed=142.5s

  [8178/20519] intraday_16525.csv.gz  in=310,312,703 out=70,768,324 elapsed=142.5s

  [8179/20519] intraday_16527.csv.gz  in=310,325,560 out=70,781,181 elapsed=142.5s

  [8180/20519] intraday_16526.csv.gz  in=310,340,160 out=70,795,781 elapsed=142.5s

  [8181/20519] intraday_16528.csv.gz  in=310,352,608 out=70,808,229 elapsed=142.5s

  [8182/20519] intraday_1653.csv.gz  in=310,360,922 out=70,808,229 elapsed=142.6s

  [8183/20519] intraday_16529.csv.gz  in=310,373,679 out=70,820,986 elapsed=142.6s

  [8184/20519] intraday_16530.csv.gz  in=310,384,269 out=70,831,576 elapsed=142.6s

  [8185/20519] intraday_16532.csv.gz  in=310,393,034 out=70,840,341 elapsed=142.6s

  [8186/20519] intraday_16533.csv.gz  in=310,403,579 out=70,850,886 elapsed=142.6s

  [8187/20519] intraday_16531.csv.gz  in=310,416,256 out=70,863,563 elapsed=142.6s

  [8188/20519] intraday_16534.csv.gz  in=310,426,624 out=70,873,931 elapsed=142.7s

  [8189/20519] intraday_16536.csv.gz  in=310,440,493 out=70,887,800 elapsed=142.7s

  [8190/20519] intraday_16535.csv.gz  in=310,456,343 out=70,903,650 elapsed=142.7s

  [8191/20519] intraday_16539.csv.gz  in=310,467,649 out=70,914,956 elapsed=142.7s

  [8192/20519] intraday_16537.csv.gz  in=310,481,551 out=70,928,858 elapsed=142.7s

  [8193/20519] intraday_16538.csv.gz  in=310,493,225 out=70,940,532 elapsed=142.7s

  [8194/20519] intraday_1654.csv.gz  in=310,504,182 out=70,940,532 elapsed=142.7s

  [8195/20519] intraday_16540.csv.gz  in=310,518,637 out=70,954,987 elapsed=142.7s

  [8196/20519] intraday_16541.csv.gz  in=310,526,626 out=70,962,976 elapsed=142.8s

  [8197/20519] intraday_16542.csv.gz  in=310,536,312 out=70,972,662 elapsed=142.8s

  [8198/20519] intraday_16543.csv.gz  in=310,548,541 out=70,984,891 elapsed=142.8s

  [8199/20519] intraday_16545.csv.gz  in=310,561,326 out=70,997,676 elapsed=142.8s

  [8200/20519] intraday_16544.csv.gz  in=310,574,791 out=71,011,141 elapsed=142.8s

  [8201/20519] intraday_16547.csv.gz  in=310,585,853 out=71,022,203 elapsed=142.8s

  [8202/20519] intraday_16546.csv.gz  in=310,596,432 out=71,032,782 elapsed=142.8s

  [8203/20519] intraday_1655.csv.gz  in=310,600,512 out=71,032,782 elapsed=142.8s

  [8204/20519] intraday_16548.csv.gz  in=310,614,920 out=71,047,190 elapsed=142.9s

  [8205/20519] intraday_16549.csv.gz  in=310,628,260 out=71,060,530 elapsed=142.9s

  [8206/20519] intraday_16550.csv.gz  in=310,639,579 out=71,071,849 elapsed=142.9s

  [8207/20519] intraday_16551.csv.gz  in=310,649,946 out=71,082,216 elapsed=142.9s

  [8208/20519] intraday_16552.csv.gz  in=310,663,126 out=71,095,396 elapsed=142.9s

  [8209/20519] intraday_16553.csv.gz  in=310,674,995 out=71,107,265 elapsed=143.0s

  [8210/20519] intraday_16556.csv.gz  in=310,687,019 out=71,119,289 elapsed=143.0s

  [8211/20519] intraday_16555.csv.gz  in=310,698,979 out=71,131,249 elapsed=143.0s

  [8212/20519] intraday_16554.csv.gz  in=310,711,176 out=71,143,446 elapsed=143.0s

  [8213/20519] intraday_16557.csv.gz  in=310,722,112 out=71,154,382 elapsed=143.0s

  [8214/20519] intraday_16558.csv.gz  in=310,733,171 out=71,165,441 elapsed=143.0s

  [8215/20519] intraday_16559.csv.gz  in=310,736,177 out=71,168,447 elapsed=143.0s

  [8216/20519] intraday_1656.csv.gz  in=310,750,629 out=71,168,447 elapsed=143.0s

  [8217/20519] intraday_16560.csv.gz  in=310,760,243 out=71,178,061 elapsed=143.0s

  [8218/20519] intraday_16562.csv.gz  in=310,770,583 out=71,188,401 elapsed=143.1s

  [8219/20519] intraday_16561.csv.gz  in=310,792,382 out=71,208,104 elapsed=143.1s

  [8220/20519] intraday_16564.csv.gz  in=310,814,977 out=71,227,861 elapsed=143.1s

  [8221/20519] intraday_16565.csv.gz  in=310,827,951 out=71,240,835 elapsed=143.1s

  [8222/20519] intraday_16563.csv.gz  in=310,842,050 out=71,254,934 elapsed=143.1s

  [8223/20519] intraday_16566.csv.gz  in=310,855,909 out=71,268,793 elapsed=143.1s

  [8224/20519] intraday_16567.csv.gz  in=310,868,052 out=71,280,936 elapsed=143.1s

  [8225/20519] intraday_16568.csv.gz  in=310,878,472 out=71,291,356 elapsed=143.1s

  [8226/20519] intraday_1657.csv.gz  in=310,892,603 out=71,291,356 elapsed=143.1s

  [8227/20519] intraday_16570.csv.gz  in=310,904,596 out=71,303,349 elapsed=143.2s

  [8228/20519] intraday_16569.csv.gz  in=310,913,798 out=71,312,551 elapsed=143.2s

  [8229/20519] intraday_16571.csv.gz  in=310,925,823 out=71,324,576 elapsed=143.2s

  [8230/20519] intraday_16572.csv.gz  in=310,939,515 out=71,338,268 elapsed=143.2s

  [8231/20519] intraday_16573.csv.gz  in=310,952,311 out=71,351,064 elapsed=143.2s

  [8232/20519] intraday_16575.csv.gz  in=310,962,407 out=71,361,160 elapsed=143.2s

  [8233/20519] intraday_16576.csv.gz  in=310,974,175 out=71,372,928 elapsed=143.2s

  [8234/20519] intraday_16574.csv.gz  in=310,987,060 out=71,385,813 elapsed=143.3s

  [8235/20519] intraday_16577.csv.gz  in=310,999,641 out=71,398,394 elapsed=143.3s

  [8236/20519] intraday_16578.csv.gz  in=311,010,535 out=71,409,288 elapsed=143.3s

  [8237/20519] intraday_16579.csv.gz  in=311,023,891 out=71,422,644 elapsed=143.3s

  [8238/20519] intraday_16580.csv.gz  in=311,033,652 out=71,432,405 elapsed=143.3s

  [8239/20519] intraday_1658.csv.gz  in=311,045,518 out=71,432,405 elapsed=143.3s

  [8240/20519] intraday_16581.csv.gz  in=311,058,936 out=71,445,823 elapsed=143.3s

  [8241/20519] intraday_16582.csv.gz  in=311,071,703 out=71,458,590 elapsed=143.3s

  [8242/20519] intraday_16583.csv.gz  in=311,085,688 out=71,472,575 elapsed=143.4s

  [8243/20519] intraday_16584.csv.gz  in=311,100,030 out=71,486,917 elapsed=143.4s

  [8244/20519] intraday_16585.csv.gz  in=311,111,657 out=71,498,544 elapsed=143.4s

  [8245/20519] intraday_16586.csv.gz  in=311,122,207 out=71,509,094 elapsed=143.4s

  [8246/20519] intraday_16587.csv.gz  in=311,134,018 out=71,520,905 elapsed=143.4s

  [8247/20519] intraday_16588.csv.gz  in=311,136,373 out=71,523,260 elapsed=143.4s

  [8248/20519] intraday_16589.csv.gz  in=311,139,908 out=71,526,795 elapsed=143.4s

  [8249/20519] intraday_1659.csv.gz  in=311,151,199 out=71,526,795 elapsed=143.4s

  [8250/20519] intraday_16590.csv.gz  in=311,162,899 out=71,538,495 elapsed=143.4s

  [8251/20519] intraday_16591.csv.gz  in=311,172,597 out=71,548,193 elapsed=143.4s

  [8252/20519] intraday_16592.csv.gz  in=311,188,078 out=71,563,674 elapsed=143.4s

  [8253/20519] intraday_16594.csv.gz  in=311,201,104 out=71,576,700 elapsed=143.5s

  [8254/20519] intraday_16593.csv.gz  in=311,214,029 out=71,589,625 elapsed=143.5s

  [8255/20519] intraday_16595.csv.gz  in=311,226,869 out=71,602,465 elapsed=143.5s

  [8256/20519] intraday_16596.csv.gz  in=311,238,119 out=71,613,715 elapsed=143.5s

  [8257/20519] intraday_16598.csv.gz  in=311,249,811 out=71,625,407 elapsed=143.5s

  [8258/20519] intraday_16597.csv.gz  in=311,259,262 out=71,634,858 elapsed=143.5s

  [8259/20519] intraday_1660.csv.gz  in=311,272,814 out=71,634,858 elapsed=143.5s

  [8260/20519] intraday_16599.csv.gz  in=311,286,085 out=71,648,129 elapsed=143.5s

  [8261/20519] intraday_16600.csv.gz  in=311,299,358 out=71,661,402 elapsed=143.6s

  [8262/20519] intraday_16601.csv.gz  in=311,309,542 out=71,671,586 elapsed=143.6s

  [8263/20519] intraday_16602.csv.gz  in=311,322,123 out=71,684,167 elapsed=143.6s

  [8264/20519] intraday_16604.csv.gz  in=311,335,977 out=71,698,021 elapsed=143.6s

  [8265/20519] intraday_16605.csv.gz  in=311,348,977 out=71,711,021 elapsed=143.6s

  [8266/20519] intraday_16603.csv.gz  in=311,358,648 out=71,720,692 elapsed=143.6s

  [8267/20519] intraday_16606.csv.gz  in=311,370,111 out=71,732,155 elapsed=143.6s

  [8268/20519] intraday_16608.csv.gz  in=311,380,057 out=71,742,101 elapsed=143.7s

  [8269/20519] intraday_16607.csv.gz  in=311,392,197 out=71,754,241 elapsed=143.7s

  [8270/20519] intraday_16609.csv.gz  in=311,404,180 out=71,766,224 elapsed=143.7s

  [8271/20519] intraday_1661.csv.gz  in=311,417,891 out=71,766,224 elapsed=143.7s

  [8272/20519] intraday_16611.csv.gz  in=311,423,697 out=71,772,030 elapsed=143.7s

  [8273/20519] intraday_16610.csv.gz  in=311,428,886 out=71,777,219 elapsed=143.7s

  [8274/20519] intraday_16613.csv.gz  in=311,441,532 out=71,789,865 elapsed=143.7s

  [8275/20519] intraday_16612.csv.gz  in=311,453,852 out=71,802,185 elapsed=143.7s

  [8276/20519] intraday_16614.csv.gz  in=311,467,177 out=71,815,510 elapsed=143.7s

  [8277/20519] intraday_16616.csv.gz  in=311,477,262 out=71,825,595 elapsed=143.8s

  [8278/20519] intraday_16615.csv.gz  in=311,490,643 out=71,838,976 elapsed=143.8s

  [8279/20519] intraday_16618.csv.gz  in=311,500,948 out=71,849,281 elapsed=143.8s

  [8280/20519] intraday_16617.csv.gz  in=311,513,035 out=71,861,368 elapsed=143.8s

  [8281/20519] intraday_16619.csv.gz  in=311,525,866 out=71,874,199 elapsed=143.8s

  [8282/20519] intraday_16620.csv.gz  in=311,537,598 out=71,885,931 elapsed=143.9s

  [8283/20519] intraday_1662.csv.gz  in=311,549,955 out=71,885,931 elapsed=143.9s

  [8284/20519] intraday_16621.csv.gz  in=311,561,660 out=71,897,636 elapsed=143.9s

  [8285/20519] intraday_16622.csv.gz  in=311,575,244 out=71,911,220 elapsed=143.9s

  [8286/20519] intraday_16624.csv.gz  in=311,585,183 out=71,921,159 elapsed=144.0s

  [8287/20519] intraday_16623.csv.gz  in=311,596,262 out=71,932,238 elapsed=144.0s

  [8288/20519] intraday_16625.csv.gz  in=311,609,658 out=71,945,634 elapsed=144.0s

  [8289/20519] intraday_16626.csv.gz  in=311,621,716 out=71,957,692 elapsed=144.0s

  [8290/20519] intraday_1663.csv.gz  in=311,633,771 out=71,957,692 elapsed=144.0s

  [8291/20519] intraday_16628.csv.gz  in=311,646,964 out=71,970,885 elapsed=144.0s

  [8292/20519] intraday_16629.csv.gz  in=311,660,111 out=71,984,032 elapsed=144.0s

  [8293/20519] intraday_16630.csv.gz  in=311,671,581 out=71,995,502 elapsed=144.1s

  [8294/20519] intraday_16631.csv.gz  in=311,685,007 out=72,008,928 elapsed=144.1s

  [8295/20519] intraday_16627.csv.gz  in=311,724,268 out=72,040,065 elapsed=144.1s

  [8296/20519] intraday_16632.csv.gz  in=311,736,982 out=72,052,779 elapsed=144.1s

  [8297/20519] intraday_16633.csv.gz  in=311,748,069 out=72,063,866 elapsed=144.1s

  [8298/20519] intraday_16634.csv.gz  in=311,761,753 out=72,077,550 elapsed=144.1s

  [8299/20519] intraday_16635.csv.gz  in=311,775,175 out=72,090,972 elapsed=144.2s

  [8300/20519] intraday_16637.csv.gz  in=311,782,186 out=72,097,983 elapsed=144.2s

  [8301/20519] intraday_16638.csv.gz  in=311,794,108 out=72,109,905 elapsed=144.2s

  [8302/20519] intraday_16636.csv.gz  in=311,807,427 out=72,123,224 elapsed=144.2s

  [8303/20519] intraday_16640.csv.gz  in=311,820,096 out=72,135,893 elapsed=144.2s

  [8304/20519] intraday_1664.csv.gz  in=311,833,961 out=72,135,893 elapsed=144.2s

  [8305/20519] intraday_16641.csv.gz  in=311,850,478 out=72,152,410 elapsed=144.3s

  [8306/20519] intraday_16639.csv.gz  in=311,889,145 out=72,188,462 elapsed=144.3s

  [8307/20519] intraday_16643.csv.gz  in=311,902,578 out=72,201,895 elapsed=144.3s

  [8308/20519] intraday_16642.csv.gz  in=311,915,031 out=72,214,348 elapsed=144.3s

  [8309/20519] intraday_16644.csv.gz  in=311,925,540 out=72,224,857 elapsed=144.3s

  [8310/20519] intraday_16646.csv.gz  in=311,936,657 out=72,235,974 elapsed=144.3s

  [8311/20519] intraday_16645.csv.gz  in=311,949,189 out=72,248,506 elapsed=144.3s

  [8312/20519] intraday_16647.csv.gz  in=311,961,771 out=72,261,088 elapsed=144.4s

  [8313/20519] intraday_16648.csv.gz  in=311,974,529 out=72,273,846 elapsed=144.4s

  [8314/20519] intraday_1665.csv.gz  in=311,988,741 out=72,273,846 elapsed=144.4s

  [8315/20519] intraday_16649.csv.gz  in=312,005,175 out=72,290,280 elapsed=144.4s

  [8316/20519] intraday_16650.csv.gz  in=312,014,951 out=72,300,056 elapsed=144.4s

  [8317/20519] intraday_16651.csv.gz  in=312,027,720 out=72,312,825 elapsed=144.4s

  [8318/20519] intraday_16652.csv.gz  in=312,040,086 out=72,325,191 elapsed=144.4s

  [8319/20519] intraday_16653.csv.gz  in=312,053,794 out=72,338,899 elapsed=144.5s

  [8320/20519] intraday_16654.csv.gz  in=312,065,248 out=72,350,353 elapsed=144.5s

  [8321/20519] intraday_16656.csv.gz  in=312,079,040 out=72,364,145 elapsed=144.5s

  [8322/20519] intraday_16657.csv.gz  in=312,093,102 out=72,378,207 elapsed=144.5s

  [8323/20519] intraday_16658.csv.gz  in=312,107,495 out=72,392,600 elapsed=144.5s

  [8324/20519] intraday_16659.csv.gz  in=312,118,859 out=72,403,964 elapsed=144.5s

  [8325/20519] intraday_16655.csv.gz  in=312,132,315 out=72,417,420 elapsed=144.5s

  [8326/20519] intraday_1666.csv.gz  in=312,141,605 out=72,417,420 elapsed=144.5s

  [8327/20519] intraday_16660.csv.gz  in=312,154,638 out=72,430,453 elapsed=144.6s

  [8328/20519] intraday_16661.csv.gz  in=312,166,749 out=72,442,564 elapsed=144.6s

  [8329/20519] intraday_16662.csv.gz  in=312,177,118 out=72,452,933 elapsed=144.6s

  [8330/20519] intraday_16663.csv.gz  in=312,189,940 out=72,465,755 elapsed=144.6s

  [8331/20519] intraday_16664.csv.gz  in=312,199,081 out=72,474,896 elapsed=144.6s

  [8332/20519] intraday_16665.csv.gz  in=312,207,545 out=72,483,360 elapsed=144.6s

  [8333/20519] intraday_16667.csv.gz  in=312,223,282 out=72,499,097 elapsed=144.6s

  [8334/20519] intraday_16666.csv.gz  in=312,235,563 out=72,511,378 elapsed=144.7s

  [8335/20519] intraday_16669.csv.gz  in=312,248,555 out=72,524,370 elapsed=144.7s

  [8336/20519] intraday_16668.csv.gz  in=312,261,592 out=72,537,407 elapsed=144.7s

  [8337/20519] intraday_1667.csv.gz  in=312,273,308 out=72,537,407 elapsed=144.7s

  [8338/20519] intraday_16670.csv.gz  in=312,284,171 out=72,548,270 elapsed=144.7s

  [8339/20519] intraday_16671.csv.gz  in=312,296,511 out=72,560,610 elapsed=144.7s

  [8340/20519] intraday_16673.csv.gz  in=312,309,164 out=72,573,263 elapsed=144.7s

  [8341/20519] intraday_16672.csv.gz  in=312,323,782 out=72,587,881 elapsed=144.8s

  [8342/20519] intraday_16674.csv.gz  in=312,334,827 out=72,598,926 elapsed=144.8s

  [8343/20519] intraday_16675.csv.gz  in=312,346,615 out=72,610,714 elapsed=144.8s

  [8344/20519] intraday_16676.csv.gz  in=312,359,078 out=72,623,177 elapsed=144.8s

  [8345/20519] intraday_16677.csv.gz  in=312,368,969 out=72,633,068 elapsed=144.8s

  [8346/20519] intraday_16678.csv.gz  in=312,380,604 out=72,644,703 elapsed=144.8s

  [8347/20519] intraday_16679.csv.gz  in=312,393,428 out=72,657,527 elapsed=144.8s

  [8348/20519] intraday_1668.csv.gz  in=312,412,483 out=72,657,527 elapsed=144.8s

  [8349/20519] intraday_16680.csv.gz  in=312,424,053 out=72,669,097 elapsed=144.8s

  [8350/20519] intraday_16681.csv.gz  in=312,434,490 out=72,679,534 elapsed=144.9s

  [8351/20519] intraday_16682.csv.gz  in=312,445,012 out=72,690,056 elapsed=144.9s

  [8352/20519] intraday_16683.csv.gz  in=312,460,696 out=72,705,740 elapsed=144.9s

  [8353/20519] intraday_16684.csv.gz  in=312,473,592 out=72,718,636 elapsed=144.9s

  [8354/20519] intraday_16685.csv.gz  in=312,484,566 out=72,729,610 elapsed=144.9s

  [8355/20519] intraday_16686.csv.gz  in=312,495,025 out=72,740,069 elapsed=144.9s

  [8356/20519] intraday_16687.csv.gz  in=312,508,942 out=72,753,986 elapsed=145.0s

  [8357/20519] intraday_1669.csv.gz  in=312,519,792 out=72,753,986 elapsed=145.0s

  [8358/20519] intraday_16690.csv.gz  in=312,521,988 out=72,756,182 elapsed=145.0s

  [8359/20519] intraday_16688.csv.gz  in=312,534,365 out=72,768,559 elapsed=145.0s

  [8360/20519] intraday_16689.csv.gz  in=312,542,658 out=72,776,852 elapsed=145.0s

  [8361/20519] intraday_16691.csv.gz  in=312,553,709 out=72,787,903 elapsed=145.1s

  [8362/20519] intraday_16692.csv.gz  in=312,567,645 out=72,801,839 elapsed=145.1s

  [8363/20519] intraday_16693.csv.gz  in=312,580,193 out=72,814,387 elapsed=145.1s

  [8364/20519] intraday_16694.csv.gz  in=312,595,703 out=72,829,897 elapsed=145.1s

  [8365/20519] intraday_16696.csv.gz  in=312,605,755 out=72,839,949 elapsed=145.1s

  [8366/20519] intraday_16698.csv.gz  in=312,619,035 out=72,853,229 elapsed=145.2s

  [8367/20519] intraday_16695.csv.gz  in=312,631,768 out=72,865,962 elapsed=145.2s

  [8368/20519] intraday_16699.csv.gz  in=312,644,077 out=72,878,271 elapsed=145.2s

  [8369/20519] intraday_16697.csv.gz  in=312,674,868 out=72,903,201 elapsed=145.2s

  [8370/20519] intraday_1670.csv.gz  in=312,684,472 out=72,903,201 elapsed=145.2s

  [8371/20519] intraday_16701.csv.gz  in=312,696,072 out=72,914,801 elapsed=145.2s

  [8372/20519] intraday_16702.csv.gz  in=312,705,556 out=72,924,285 elapsed=145.3s

  [8373/20519] intraday_16703.csv.gz  in=312,715,815 out=72,934,544 elapsed=145.3s

  [8374/20519] intraday_16700.csv.gz  in=312,728,958 out=72,947,687 elapsed=145.3s

  [8375/20519] intraday_16704.csv.gz  in=312,739,971 out=72,958,700 elapsed=145.3s

  [8376/20519] intraday_16705.csv.gz  in=312,751,485 out=72,970,214 elapsed=145.3s

  [8377/20519] intraday_16706.csv.gz  in=312,765,134 out=72,983,863 elapsed=145.3s

  [8378/20519] intraday_16708.csv.gz  in=312,777,015 out=72,995,744 elapsed=145.3s

  [8379/20519] intraday_16707.csv.gz  in=312,789,637 out=73,008,366 elapsed=145.3s

  [8380/20519] intraday_16709.csv.gz  in=312,800,714 out=73,019,443 elapsed=145.3s

  [8381/20519] intraday_1671.csv.gz  in=312,814,273 out=73,019,443 elapsed=145.4s

  [8382/20519] intraday_16710.csv.gz  in=312,825,769 out=73,030,939 elapsed=145.4s

  [8383/20519] intraday_16711.csv.gz  in=312,837,930 out=73,043,100 elapsed=145.4s

  [8384/20519] intraday_16712.csv.gz  in=312,849,980 out=73,055,150 elapsed=145.4s

  [8385/20519] intraday_16713.csv.gz  in=312,862,217 out=73,067,387 elapsed=145.4s

  [8386/20519] intraday_16714.csv.gz  in=312,872,394 out=73,077,564 elapsed=145.5s

  [8387/20519] intraday_16716.csv.gz  in=312,884,831 out=73,090,001 elapsed=145.5s

  [8388/20519] intraday_16717.csv.gz  in=312,898,473 out=73,103,643 elapsed=145.5s

  [8389/20519] intraday_16715.csv.gz  in=312,913,000 out=73,118,170 elapsed=145.5s

  [8390/20519] intraday_16718.csv.gz  in=312,925,612 out=73,130,782 elapsed=145.5s

  [8391/20519] intraday_16719.csv.gz  in=312,937,096 out=73,142,266 elapsed=145.5s

  [8392/20519] intraday_1672.csv.gz  in=312,948,476 out=73,142,266 elapsed=145.5s

  [8393/20519] intraday_16720.csv.gz  in=312,959,158 out=73,152,948 elapsed=145.5s

  [8394/20519] intraday_16721.csv.gz  in=312,970,699 out=73,164,489 elapsed=145.5s

  [8395/20519] intraday_16722.csv.gz  in=312,983,148 out=73,176,938 elapsed=145.6s

  [8396/20519] intraday_16724.csv.gz  in=312,997,712 out=73,191,446 elapsed=145.6s

  [8397/20519] intraday_16723.csv.gz  in=313,010,001 out=73,203,735 elapsed=145.6s

  [8398/20519] intraday_16726.csv.gz  in=313,021,536 out=73,215,270 elapsed=145.6s

  [8399/20519] intraday_16725.csv.gz  in=313,030,263 out=73,223,997 elapsed=145.6s

  [8400/20519] intraday_16727.csv.gz  in=313,040,514 out=73,234,248 elapsed=145.6s

  [8401/20519] intraday_16728.csv.gz  in=313,054,979 out=73,248,713 elapsed=145.6s

  [8402/20519] intraday_16729.csv.gz  in=313,066,971 out=73,260,705 elapsed=145.7s

  [8403/20519] intraday_1673.csv.gz  in=313,079,092 out=73,260,705 elapsed=145.7s

  [8404/20519] intraday_16730.csv.gz  in=313,092,321 out=73,273,934 elapsed=145.7s

  [8405/20519] intraday_16733.csv.gz  in=313,100,486 out=73,282,099 elapsed=145.7s

  [8406/20519] intraday_16731.csv.gz  in=313,112,386 out=73,293,999 elapsed=145.7s

  [8407/20519] intraday_16735.csv.gz  in=313,125,004 out=73,306,617 elapsed=145.8s

  [8408/20519] intraday_16732.csv.gz  in=313,137,329 out=73,318,942 elapsed=145.8s

  [8409/20519] intraday_16734.csv.gz  in=313,149,282 out=73,330,895 elapsed=145.8s

  [8410/20519] intraday_16736.csv.gz  in=313,161,819 out=73,343,432 elapsed=145.8s

  [8411/20519] intraday_16738.csv.gz  in=313,173,108 out=73,354,721 elapsed=145.8s

  [8412/20519] intraday_16737.csv.gz  in=313,182,808 out=73,364,421 elapsed=145.8s

  [8413/20519] intraday_16739.csv.gz  in=313,192,286 out=73,373,899 elapsed=145.8s

  [8414/20519] intraday_1674.csv.gz  in=313,203,932 out=73,373,899 elapsed=145.8s

  [8415/20519] intraday_16740.csv.gz  in=313,216,664 out=73,386,631 elapsed=145.8s

  [8416/20519] intraday_16742.csv.gz  in=313,228,421 out=73,398,388 elapsed=145.9s

  [8417/20519] intraday_16744.csv.gz  in=313,238,552 out=73,408,519 elapsed=145.9s

  [8418/20519] intraday_16743.csv.gz  in=313,250,531 out=73,420,498 elapsed=145.9s

  [8419/20519] intraday_16741.csv.gz  in=313,263,534 out=73,433,501 elapsed=145.9s

  [8420/20519] intraday_16745.csv.gz  in=313,274,397 out=73,444,364 elapsed=145.9s

  [8421/20519] intraday_16748.csv.gz  in=313,285,667 out=73,455,634 elapsed=146.0s

  [8422/20519] intraday_16746.csv.gz  in=313,298,264 out=73,468,231 elapsed=146.0s

  [8423/20519] intraday_16749.csv.gz  in=313,310,238 out=73,480,205 elapsed=146.0s

  [8424/20519] intraday_1675.csv.gz  in=313,322,120 out=73,480,205 elapsed=146.0s

  [8425/20519] intraday_16747.csv.gz  in=313,339,818 out=73,497,903 elapsed=146.0s

  [8426/20519] intraday_16750.csv.gz  in=313,352,098 out=73,510,183 elapsed=146.0s

  [8427/20519] intraday_16752.csv.gz  in=313,363,466 out=73,521,551 elapsed=146.1s

  [8428/20519] intraday_16751.csv.gz  in=313,376,242 out=73,533,708 elapsed=146.1s

  [8429/20519] intraday_16754.csv.gz  in=313,386,181 out=73,543,647 elapsed=146.1s

  [8430/20519] intraday_16753.csv.gz  in=313,399,332 out=73,556,798 elapsed=146.1s

  [8431/20519] intraday_16755.csv.gz  in=313,411,464 out=73,568,930 elapsed=146.1s

  [8432/20519] intraday_16756.csv.gz  in=313,421,773 out=73,579,239 elapsed=146.1s

  [8433/20519] intraday_16758.csv.gz  in=313,433,911 out=73,591,377 elapsed=146.1s

  [8434/20519] intraday_16757.csv.gz  in=313,445,305 out=73,602,771 elapsed=146.2s

  [8435/20519] intraday_1676.csv.gz  in=313,458,636 out=73,602,771 elapsed=146.2s

  [8436/20519] intraday_16759.csv.gz  in=313,470,567 out=73,614,702 elapsed=146.2s

  [8437/20519] intraday_16761.csv.gz  in=313,480,242 out=73,624,377 elapsed=146.2s

  [8438/20519] intraday_16760.csv.gz  in=313,492,516 out=73,636,651 elapsed=146.2s

  [8439/20519] intraday_16762.csv.gz  in=313,502,532 out=73,646,667 elapsed=146.2s

  [8440/20519] intraday_16763.csv.gz  in=313,514,327 out=73,658,462 elapsed=146.2s

  [8441/20519] intraday_16764.csv.gz  in=313,527,072 out=73,671,207 elapsed=146.2s

  [8442/20519] intraday_16765.csv.gz  in=313,539,253 out=73,683,388 elapsed=146.2s

  [8443/20519] intraday_16766.csv.gz  in=313,550,789 out=73,694,924 elapsed=146.2s

  [8444/20519] intraday_16768.csv.gz  in=313,562,067 out=73,706,202 elapsed=146.3s

  [8445/20519] intraday_16767.csv.gz  in=313,574,499 out=73,718,634 elapsed=146.3s

  [8446/20519] intraday_16769.csv.gz  in=313,586,603 out=73,730,738 elapsed=146.3s

  [8447/20519] intraday_1677.csv.gz  in=313,598,354 out=73,730,738 elapsed=146.3s

  [8448/20519] intraday_16770.csv.gz  in=313,610,510 out=73,742,894 elapsed=146.3s

  [8449/20519] intraday_16771.csv.gz  in=313,621,939 out=73,754,323 elapsed=146.3s

  [8450/20519] intraday_16773.csv.gz  in=313,635,675 out=73,768,059 elapsed=146.3s

  [8451/20519] intraday_16772.csv.gz  in=313,650,047 out=73,782,431 elapsed=146.4s

  [8452/20519] intraday_16774.csv.gz  in=313,661,579 out=73,793,963 elapsed=146.4s

  [8453/20519] intraday_16776.csv.gz  in=313,675,086 out=73,807,470 elapsed=146.4s

  [8454/20519] intraday_16777.csv.gz  in=313,686,948 out=73,819,332 elapsed=146.4s

  [8455/20519] intraday_16775.csv.gz  in=313,699,297 out=73,831,681 elapsed=146.4s

  [8456/20519] intraday_16778.csv.gz  in=313,713,288 out=73,845,672 elapsed=146.4s

  [8457/20519] intraday_16779.csv.gz  in=313,728,308 out=73,860,692 elapsed=146.4s

  [8458/20519] intraday_1678.csv.gz  in=313,740,962 out=73,860,692 elapsed=146.4s

  [8459/20519] intraday_16780.csv.gz  in=313,757,916 out=73,877,646 elapsed=146.5s

  [8460/20519] intraday_16783.csv.gz  in=313,770,094 out=73,889,824 elapsed=146.5s

  [8461/20519] intraday_16781.csv.gz  in=313,782,248 out=73,901,978 elapsed=146.5s

  [8462/20519] intraday_16784.csv.gz  in=313,794,947 out=73,914,677 elapsed=146.5s

  [8463/20519] intraday_16782.csv.gz  in=313,810,718 out=73,930,448 elapsed=146.5s

  [8464/20519] intraday_16785.csv.gz  in=313,821,221 out=73,940,951 elapsed=146.5s

  [8465/20519] intraday_16786.csv.gz  in=313,833,590 out=73,953,320 elapsed=146.5s

  [8466/20519] intraday_16787.csv.gz  in=313,843,392 out=73,963,122 elapsed=146.5s

  [8467/20519] intraday_16789.csv.gz  in=313,855,327 out=73,975,057 elapsed=146.6s

  [8468/20519] intraday_16788.csv.gz  in=313,867,953 out=73,987,683 elapsed=146.6s

  [8469/20519] intraday_1679.csv.gz  in=313,891,316 out=73,987,683 elapsed=146.6s

  [8470/20519] intraday_16790.csv.gz  in=313,905,183 out=74,001,550 elapsed=146.6s

  [8471/20519] intraday_16791.csv.gz  in=313,916,683 out=74,013,050 elapsed=146.6s

  [8472/20519] intraday_16792.csv.gz  in=313,927,322 out=74,023,689 elapsed=146.6s

  [8473/20519] intraday_16794.csv.gz  in=313,941,780 out=74,038,147 elapsed=146.6s

  [8474/20519] intraday_16793.csv.gz  in=313,953,798 out=74,050,165 elapsed=146.6s

  [8475/20519] intraday_16795.csv.gz  in=313,964,623 out=74,060,990 elapsed=146.6s

  [8476/20519] intraday_16797.csv.gz  in=313,977,340 out=74,073,707 elapsed=146.7s

  [8477/20519] intraday_16798.csv.gz  in=313,990,772 out=74,087,139 elapsed=146.7s

  [8478/20519] intraday_16799.csv.gz  in=314,005,861 out=74,102,228 elapsed=146.7s

  [8479/20519] intraday_16796.csv.gz  in=314,024,526 out=74,119,538 elapsed=146.7s

  [8480/20519] intraday_1680.csv.gz  in=314,035,656 out=74,119,538 elapsed=146.7s

  [8481/20519] intraday_16800.csv.gz  in=314,046,326 out=74,130,208 elapsed=146.7s

  [8482/20519] intraday_16803.csv.gz  in=314,057,521 out=74,141,403 elapsed=146.7s

  [8483/20519] intraday_16802.csv.gz  in=314,069,115 out=74,152,997 elapsed=146.8s

  [8484/20519] intraday_16801.csv.gz  in=314,081,582 out=74,165,464 elapsed=146.8s

  [8485/20519] intraday_16804.csv.gz  in=314,092,252 out=74,176,134 elapsed=146.8s

  [8486/20519] intraday_16805.csv.gz  in=314,101,489 out=74,185,371 elapsed=146.8s

  [8487/20519] intraday_16807.csv.gz  in=314,109,784 out=74,193,666 elapsed=146.8s

  [8488/20519] intraday_16808.csv.gz  in=314,110,260 out=74,193,666 elapsed=146.8s

  [8489/20519] intraday_16806.csv.gz  in=314,119,685 out=74,203,091 elapsed=146.8s

  [8490/20519] intraday_16809.csv.gz  in=314,119,741 out=74,203,091 elapsed=146.9s

  [8491/20519] intraday_16811.csv.gz  in=314,120,218 out=74,203,568 elapsed=146.9s

  [8492/20519] intraday_16812.csv.gz  in=314,120,719 out=74,204,069 elapsed=146.9s

  [8493/20519] intraday_16810.csv.gz  in=314,121,650 out=74,205,000 elapsed=146.9s

  [8494/20519] intraday_16813.csv.gz  in=314,122,004 out=74,205,354 elapsed=146.9s

  [8495/20519] intraday_1681.csv.gz  in=314,131,814 out=74,205,354 elapsed=146.9s

  [8496/20519] intraday_16816.csv.gz  in=314,132,376 out=74,205,916 elapsed=146.9s

  [8497/20519] intraday_16814.csv.gz  in=314,132,751 out=74,206,291 elapsed=146.9s

  [8498/20519] intraday_16817.csv.gz  in=314,133,050 out=74,206,590 elapsed=146.9s

  [8499/20519] intraday_16818.csv.gz  in=314,133,495 out=74,207,035 elapsed=146.9s

  [8500/20519] intraday_16819.csv.gz  in=314,134,229 out=74,207,769 elapsed=146.9s

  [8501/20519] intraday_16815.csv.gz  in=314,135,225 out=74,208,765 elapsed=147.0s

  [8502/20519] intraday_16820.csv.gz  in=314,135,700 out=74,209,240 elapsed=147.0s

  [8503/20519] intraday_16822.csv.gz  in=314,136,476 out=74,210,016 elapsed=147.0s

  [8504/20519] intraday_1682.csv.gz  in=314,149,196 out=74,210,016 elapsed=147.0s

  [8505/20519] intraday_16823.csv.gz  in=314,149,499 out=74,210,319 elapsed=147.0s

  [8506/20519] intraday_16821.csv.gz  in=314,150,026 out=74,210,846 elapsed=147.0s

  [8507/20519] intraday_16824.csv.gz  in=314,150,516 out=74,211,336 elapsed=147.0s

  [8508/20519] intraday_16826.csv.gz  in=314,151,290 out=74,212,110 elapsed=147.0s

  [8509/20519] intraday_16827.csv.gz  in=314,152,118 out=74,212,938 elapsed=147.0s

  [8510/20519] intraday_16828.csv.gz  in=314,152,463 out=74,213,283 elapsed=147.0s

  [8511/20519] intraday_16825.csv.gz  in=314,152,807 out=74,213,627 elapsed=147.0s

  [8512/20519] intraday_16829.csv.gz  in=314,153,216 out=74,214,036 elapsed=147.0s

  [8513/20519] intraday_16830.csv.gz  in=314,153,969 out=74,214,789 elapsed=147.0s

  [8514/20519] intraday_16831.csv.gz  in=314,154,179 out=74,214,999 elapsed=147.0s

  [8515/20519] intraday_16832.csv.gz  in=314,154,468 out=74,215,288 elapsed=147.0s

  [8516/20519] intraday_16833.csv.gz  in=314,154,940 out=74,215,760 elapsed=147.0s

  [8517/20519] intraday_16834.csv.gz  in=314,155,021 out=74,215,841 elapsed=147.0s

  [8518/20519] intraday_16836.csv.gz  in=314,155,292 out=74,216,112 elapsed=147.1s

  [8519/20519] intraday_16835.csv.gz  in=314,155,703 out=74,216,523 elapsed=147.1s

  [8520/20519] intraday_1683.csv.gz  in=314,168,246 out=74,216,523 elapsed=147.1s

  [8521/20519] intraday_16837.csv.gz  in=314,168,306 out=74,216,583 elapsed=147.1s

  [8522/20519] intraday_16838.csv.gz  in=314,169,418 out=74,217,695 elapsed=147.1s

  [8523/20519] intraday_16839.csv.gz  in=314,170,526 out=74,218,803 elapsed=147.1s

  [8524/20519] intraday_16840.csv.gz  in=314,171,552 out=74,219,829 elapsed=147.1s

  [8525/20519] intraday_16842.csv.gz  in=314,171,996 out=74,220,273 elapsed=147.1s

  [8526/20519] intraday_16843.csv.gz  in=314,172,640 out=74,220,917 elapsed=147.1s

  [8527/20519] intraday_1684.csv.gz  in=314,192,639 out=74,220,917 elapsed=147.1s

  [8528/20519] intraday_16844.csv.gz  in=314,192,978 out=74,221,256 elapsed=147.1s

  [8529/20519] intraday_16846.csv.gz  in=314,193,265 out=74,221,543 elapsed=147.1s

  [8530/20519] intraday_16845.csv.gz  in=314,193,739 out=74,222,017 elapsed=147.1s

  [8531/20519] intraday_16848.csv.gz  in=314,193,884 out=74,222,162 elapsed=147.1s

  [8532/20519] intraday_16847.csv.gz  in=314,194,154 out=74,222,432 elapsed=147.1s

  [8533/20519] intraday_16841.csv.gz  in=314,212,804 out=74,236,177 elapsed=147.1s

  [8534/20519] intraday_16849.csv.gz  in=314,213,027 out=74,236,400 elapsed=147.1s

  [8535/20519] intraday_16850.csv.gz  in=314,213,242 out=74,236,615 elapsed=147.2s

  [8536/20519] intraday_16851.csv.gz  in=314,213,323 out=74,236,696 elapsed=147.2s

  [8537/20519] intraday_16852.csv.gz  in=314,214,208 out=74,237,581 elapsed=147.2s

  [8538/20519] intraday_16853.csv.gz  in=314,214,456 out=74,237,829 elapsed=147.2s

  [8539/20519] intraday_16854.csv.gz  in=314,214,694 out=74,238,067 elapsed=147.2s

  [8540/20519] intraday_16855.csv.gz  in=314,214,810 out=74,238,183 elapsed=147.2s

  [8541/20519] intraday_16856.csv.gz  in=314,215,043 out=74,238,416 elapsed=147.2s

  [8542/20519] intraday_1685.csv.gz  in=314,228,745 out=74,238,416 elapsed=147.2s

  [8543/20519] intraday_16857.csv.gz  in=314,228,933 out=74,238,604 elapsed=147.2s

  [8544/20519] intraday_16858.csv.gz  in=314,229,191 out=74,238,862 elapsed=147.2s

  [8545/20519] intraday_16859.csv.gz  in=314,229,364 out=74,239,035 elapsed=147.2s

  [8546/20519] intraday_16861.csv.gz  in=314,230,151 out=74,239,822 elapsed=147.2s

  [8547/20519] intraday_16860.csv.gz  in=314,230,345 out=74,240,016 elapsed=147.2s

  [8548/20519] intraday_16862.csv.gz  in=314,231,478 out=74,241,149 elapsed=147.2s

  [8549/20519] intraday_1686.csv.gz  in=314,243,125 out=74,241,149 elapsed=147.2s

  [8550/20519] intraday_16863.csv.gz  in=314,243,995 out=74,242,019 elapsed=147.2s

  [8551/20519] intraday_16865.csv.gz  in=314,244,122 out=74,242,146 elapsed=147.2s

  [8552/20519] intraday_16866.csv.gz  in=314,244,233 out=74,242,257 elapsed=147.2s

  [8553/20519] intraday_16864.csv.gz  in=314,244,809 out=74,242,833 elapsed=147.2s

  [8554/20519] intraday_16867.csv.gz  in=314,245,037 out=74,243,061 elapsed=147.3s

  [8555/20519] intraday_16868.csv.gz  in=314,245,540 out=74,243,564 elapsed=147.3s

  [8556/20519] intraday_16869.csv.gz  in=314,245,852 out=74,243,876 elapsed=147.3s

  [8557/20519] intraday_16870.csv.gz  in=314,246,381 out=74,244,405 elapsed=147.3s

  [8558/20519] intraday_16871.csv.gz  in=314,246,479 out=74,244,503 elapsed=147.3s

  [8559/20519] intraday_16872.csv.gz  in=314,246,777 out=74,244,801 elapsed=147.3s

  [8560/20519] intraday_16873.csv.gz  in=314,247,007 out=74,245,031 elapsed=147.3s

  [8561/20519] intraday_16874.csv.gz  in=314,247,927 out=74,245,951 elapsed=147.3s

  [8562/20519] intraday_1687.csv.gz  in=314,268,017 out=74,245,951 elapsed=147.3s

  [8563/20519] intraday_16875.csv.gz  in=314,268,647 out=74,246,581 elapsed=147.3s

  [8564/20519] intraday_16876.csv.gz  in=314,268,886 out=74,246,820 elapsed=147.3s

  [8565/20519] intraday_16877.csv.gz  in=314,269,396 out=74,247,330 elapsed=147.3s

  [8566/20519] intraday_16878.csv.gz  in=314,269,673 out=74,247,607 elapsed=147.3s

  [8567/20519] intraday_16879.csv.gz  in=314,269,860 out=74,247,794 elapsed=147.3s

  [8568/20519] intraday_16881.csv.gz  in=314,270,048 out=74,247,982 elapsed=147.3s

  [8569/20519] intraday_16880.csv.gz  in=314,270,853 out=74,248,787 elapsed=147.3s

  [8570/20519] intraday_16882.csv.gz  in=314,271,105 out=74,249,039 elapsed=147.3s

  [8571/20519] intraday_1688.csv.gz  in=314,282,574 out=74,249,039 elapsed=147.3s

  [8572/20519] intraday_16884.csv.gz  in=314,283,369 out=74,249,834 elapsed=147.3s

  [8573/20519] intraday_16883.csv.gz  in=314,283,687 out=74,250,152 elapsed=147.3s

  [8574/20519] intraday_16885.csv.gz  in=314,283,991 out=74,250,456 elapsed=147.3s

  [8575/20519] intraday_16886.csv.gz  in=314,284,350 out=74,250,815 elapsed=147.3s

  [8576/20519] intraday_16888.csv.gz  in=314,284,953 out=74,251,418 elapsed=147.3s

  [8577/20519] intraday_16887.csv.gz  in=314,285,445 out=74,251,910 elapsed=147.3s

  [8578/20519] intraday_16889.csv.gz  in=314,285,500 out=74,251,965 elapsed=147.3s

  [8579/20519] intraday_16890.csv.gz  in=314,285,768 out=74,252,233 elapsed=147.3s

  [8580/20519] intraday_16892.csv.gz  in=314,286,954 out=74,253,419 elapsed=147.3s

  [8581/20519] intraday_16891.csv.gz  in=314,288,077 out=74,254,542 elapsed=147.3s

  [8582/20519] intraday_1689.csv.gz  in=314,300,977 out=74,254,542 elapsed=147.3s

  [8583/20519] intraday_16893.csv.gz  in=314,302,121 out=74,255,686 elapsed=147.3s

  [8584/20519] intraday_16895.csv.gz  in=314,302,696 out=74,256,261 elapsed=147.3s

  [8585/20519] intraday_16894.csv.gz  in=314,303,494 out=74,257,059 elapsed=147.3s

  [8586/20519] intraday_16897.csv.gz  in=314,303,652 out=74,257,217 elapsed=147.3s

  [8587/20519] intraday_16896.csv.gz  in=314,304,259 out=74,257,824 elapsed=147.3s

  [8588/20519] intraday_16899.csv.gz  in=314,304,564 out=74,258,129 elapsed=147.3s

  [8589/20519] intraday_16898.csv.gz  in=314,305,581 out=74,259,146 elapsed=147.3s

  [8590/20519] intraday_16900.csv.gz  in=314,305,850 out=74,259,415 elapsed=147.3s

  [8591/20519] intraday_16901.csv.gz  in=314,306,481 out=74,260,046 elapsed=147.4s

  [8592/20519] intraday_16902.csv.gz  in=314,306,902 out=74,260,467 elapsed=147.4s

  [8593/20519] intraday_16904.csv.gz  in=314,307,206 out=74,260,771 elapsed=147.4s

  [8594/20519] intraday_16903.csv.gz  in=314,307,618 out=74,261,183 elapsed=147.4s

  [8595/20519] intraday_16905.csv.gz  in=314,308,043 out=74,261,608 elapsed=147.4s

  [8596/20519] intraday_1690.csv.gz  in=314,318,593 out=74,261,608 elapsed=147.4s

  [8597/20519] intraday_16906.csv.gz  in=314,318,681 out=74,261,696 elapsed=147.4s

  [8598/20519] intraday_16907.csv.gz  in=314,319,229 out=74,262,244 elapsed=147.4s

  [8599/20519] intraday_16909.csv.gz  in=314,319,422 out=74,262,437 elapsed=147.4s

  [8600/20519] intraday_16908.csv.gz  in=314,319,613 out=74,262,628 elapsed=147.4s

  [8601/20519] intraday_16910.csv.gz  in=314,320,219 out=74,263,234 elapsed=147.4s

  [8602/20519] intraday_16911.csv.gz  in=314,321,671 out=74,264,686 elapsed=147.4s

  [8603/20519] intraday_16912.csv.gz  in=314,322,312 out=74,265,327 elapsed=147.4s

  [8604/20519] intraday_16914.csv.gz  in=314,322,791 out=74,265,806 elapsed=147.4s

  [8605/20519] intraday_16913.csv.gz  in=314,323,417 out=74,266,432 elapsed=147.4s

  [8606/20519] intraday_1691.csv.gz  in=314,336,239 out=74,266,432 elapsed=147.4s

  [8607/20519] intraday_16915.csv.gz  in=314,336,812 out=74,267,005 elapsed=147.4s

  [8608/20519] intraday_16916.csv.gz  in=314,336,937 out=74,267,130 elapsed=147.4s

  [8609/20519] intraday_16917.csv.gz  in=314,337,294 out=74,267,487 elapsed=147.4s

  [8610/20519] intraday_16919.csv.gz  in=314,338,023 out=74,268,216 elapsed=147.4s

  [8611/20519] intraday_16918.csv.gz  in=314,338,378 out=74,268,571 elapsed=147.5s

  [8612/20519] intraday_16920.csv.gz  in=314,338,869 out=74,269,062 elapsed=147.5s

  [8613/20519] intraday_16921.csv.gz  in=314,339,097 out=74,269,290 elapsed=147.5s

  [8614/20519] intraday_16922.csv.gz  in=314,340,061 out=74,270,254 elapsed=147.5s

  [8615/20519] intraday_16923.csv.gz  in=314,340,994 out=74,271,187 elapsed=147.5s

  [8616/20519] intraday_1692.csv.gz  in=314,353,065 out=74,271,187 elapsed=147.5s

  [8617/20519] intraday_16925.csv.gz  in=314,354,831 out=74,272,953 elapsed=147.5s

  [8618/20519] intraday_16924.csv.gz  in=314,356,196 out=74,274,318 elapsed=147.5s

  [8619/20519] intraday_16926.csv.gz  in=314,356,459 out=74,274,581 elapsed=147.5s

  [8620/20519] intraday_16928.csv.gz  in=314,356,748 out=74,274,870 elapsed=147.5s

  [8621/20519] intraday_16929.csv.gz  in=314,357,156 out=74,275,278 elapsed=147.5s

  [8622/20519] intraday_16930.csv.gz  in=314,357,244 out=74,275,366 elapsed=147.5s

  [8623/20519] intraday_16927.csv.gz  in=314,358,307 out=74,276,429 elapsed=147.5s

  [8624/20519] intraday_16932.csv.gz  in=314,358,386 out=74,276,508 elapsed=147.5s

  [8625/20519] intraday_16933.csv.gz  in=314,358,882 out=74,277,004 elapsed=147.5s

  [8626/20519] intraday_16931.csv.gz  in=314,359,449 out=74,277,571 elapsed=147.5s

  [8627/20519] intraday_1693.csv.gz  in=314,370,280 out=74,277,571 elapsed=147.5s

  [8628/20519] intraday_16934.csv.gz  in=314,370,763 out=74,278,054 elapsed=147.5s

  [8629/20519] intraday_16937.csv.gz  in=314,371,245 out=74,278,536 elapsed=147.6s

  [8630/20519] intraday_16935.csv.gz  in=314,372,348 out=74,279,639 elapsed=147.6s

  [8631/20519] intraday_16936.csv.gz  in=314,372,611 out=74,279,902 elapsed=147.6s

  [8632/20519] intraday_16938.csv.gz  in=314,373,148 out=74,280,439 elapsed=147.6s

  [8633/20519] intraday_16939.csv.gz  in=314,374,023 out=74,281,314 elapsed=147.6s

  [8634/20519] intraday_16940.csv.gz  in=314,374,277 out=74,281,568 elapsed=147.6s

  [8635/20519] intraday_16941.csv.gz  in=314,374,755 out=74,282,046 elapsed=147.6s

  [8636/20519] intraday_16942.csv.gz  in=314,374,978 out=74,282,269 elapsed=147.6s

  [8637/20519] intraday_16944.csv.gz  in=314,375,344 out=74,282,635 elapsed=147.6s

  [8638/20519] intraday_16943.csv.gz  in=314,375,930 out=74,283,221 elapsed=147.6s

  [8639/20519] intraday_16945.csv.gz  in=314,376,378 out=74,283,669 elapsed=147.6s

  [8640/20519] intraday_1694.csv.gz  in=314,399,647 out=74,283,669 elapsed=147.6s

  [8641/20519] intraday_16947.csv.gz  in=314,399,866 out=74,283,888 elapsed=147.6s

  [8642/20519] intraday_16949.csv.gz  in=314,400,321 out=74,284,343 elapsed=147.6s

  [8643/20519] intraday_16946.csv.gz  in=314,400,758 out=74,284,780 elapsed=147.6s

  [8644/20519] intraday_16948.csv.gz  in=314,401,003 out=74,285,025 elapsed=147.6s

  [8645/20519] intraday_16950.csv.gz  in=314,401,425 out=74,285,447 elapsed=147.6s

  [8646/20519] intraday_16951.csv.gz  in=314,401,766 out=74,285,788 elapsed=147.6s

  [8647/20519] intraday_16952.csv.gz  in=314,402,111 out=74,286,133 elapsed=147.6s

  [8648/20519] intraday_1695.csv.gz  in=314,417,211 out=74,286,133 elapsed=147.6s

  [8649/20519] intraday_16953.csv.gz  in=314,434,152 out=74,303,074 elapsed=147.7s

  [8650/20519] intraday_16955.csv.gz  in=314,446,842 out=74,315,764 elapsed=147.7s

  [8651/20519] intraday_16954.csv.gz  in=314,460,518 out=74,329,440 elapsed=147.7s

  [8652/20519] intraday_16956.csv.gz  in=314,471,545 out=74,340,467 elapsed=147.7s

  [8653/20519] intraday_16957.csv.gz  in=314,484,437 out=74,353,359 elapsed=147.7s

  [8654/20519] intraday_16958.csv.gz  in=314,501,019 out=74,369,941 elapsed=147.8s

  [8655/20519] intraday_1696.csv.gz  in=314,513,903 out=74,369,941 elapsed=147.8s

  [8656/20519] intraday_16959.csv.gz  in=314,526,998 out=74,383,036 elapsed=147.8s

  [8657/20519] intraday_16960.csv.gz  in=314,538,823 out=74,394,861 elapsed=147.8s

  [8658/20519] intraday_16962.csv.gz  in=314,552,703 out=74,408,741 elapsed=147.8s

  [8659/20519] intraday_16961.csv.gz  in=314,565,749 out=74,421,787 elapsed=147.8s

  [8660/20519] intraday_16963.csv.gz  in=314,576,368 out=74,432,406 elapsed=147.8s

  [8661/20519] intraday_16964.csv.gz  in=314,590,309 out=74,446,347 elapsed=147.9s

  [8662/20519] intraday_16965.csv.gz  in=314,604,306 out=74,460,344 elapsed=147.9s

  [8663/20519] intraday_16966.csv.gz  in=314,616,474 out=74,472,512 elapsed=147.9s

  [8664/20519] intraday_16967.csv.gz  in=314,627,225 out=74,483,263 elapsed=147.9s

  [8665/20519] intraday_16968.csv.gz  in=314,637,813 out=74,493,851 elapsed=147.9s

  [8666/20519] intraday_1697.csv.gz  in=314,649,799 out=74,493,851 elapsed=147.9s

  [8667/20519] intraday_16969.csv.gz  in=314,666,048 out=74,510,100 elapsed=147.9s

  [8668/20519] intraday_16970.csv.gz  in=314,680,535 out=74,524,587 elapsed=147.9s

  [8669/20519] intraday_16971.csv.gz  in=314,692,304 out=74,536,356 elapsed=147.9s

  [8670/20519] intraday_16972.csv.gz  in=314,703,633 out=74,547,685 elapsed=148.0s

  [8671/20519] intraday_16973.csv.gz  in=314,719,149 out=74,563,201 elapsed=148.0s

  [8672/20519] intraday_16974.csv.gz  in=314,731,784 out=74,575,836 elapsed=148.0s

  [8673/20519] intraday_16975.csv.gz  in=314,743,899 out=74,587,951 elapsed=148.0s

  [8674/20519] intraday_16976.csv.gz  in=314,756,580 out=74,600,632 elapsed=148.0s

  [8675/20519] intraday_16977.csv.gz  in=314,768,782 out=74,612,834 elapsed=148.0s

  [8676/20519] intraday_16978.csv.gz  in=314,780,368 out=74,624,420 elapsed=148.0s

  [8677/20519] intraday_16979.csv.gz  in=314,792,465 out=74,636,517 elapsed=148.1s

  [8678/20519] intraday_1698.csv.gz  in=314,807,588 out=74,636,517 elapsed=148.1s

  [8679/20519] intraday_16981.csv.gz  in=314,821,930 out=74,650,859 elapsed=148.1s

  [8680/20519] intraday_16980.csv.gz  in=314,833,321 out=74,662,250 elapsed=148.1s

  [8681/20519] intraday_16982.csv.gz  in=314,846,224 out=74,675,153 elapsed=148.1s

  [8682/20519] intraday_16984.csv.gz  in=314,859,411 out=74,688,340 elapsed=148.1s

  [8683/20519] intraday_16983.csv.gz  in=314,877,640 out=74,706,569 elapsed=148.2s

  [8684/20519] intraday_16985.csv.gz  in=314,889,874 out=74,718,803 elapsed=148.2s

  [8685/20519] intraday_16986.csv.gz  in=314,903,053 out=74,731,982 elapsed=148.2s

  [8686/20519] intraday_16987.csv.gz  in=314,917,782 out=74,746,711 elapsed=148.2s

  [8687/20519] intraday_16988.csv.gz  in=314,931,464 out=74,760,393 elapsed=148.2s

  [8688/20519] intraday_16989.csv.gz  in=314,945,351 out=74,774,280 elapsed=148.2s

  [8689/20519] intraday_1699.csv.gz  in=314,957,360 out=74,774,280 elapsed=148.2s

  [8690/20519] intraday_16990.csv.gz  in=314,968,781 out=74,785,701 elapsed=148.2s

  [8691/20519] intraday_16991.csv.gz  in=314,979,449 out=74,796,369 elapsed=148.2s

  [8692/20519] intraday_16992.csv.gz  in=314,993,867 out=74,810,787 elapsed=148.3s

  [8693/20519] intraday_16994.csv.gz  in=315,005,570 out=74,822,490 elapsed=148.3s

  [8694/20519] intraday_16993.csv.gz  in=315,018,274 out=74,835,194 elapsed=148.3s

  [8695/20519] intraday_16995.csv.gz  in=315,037,906 out=74,854,218 elapsed=148.3s

  [8696/20519] intraday_16996.csv.gz  in=315,050,497 out=74,866,809 elapsed=148.3s

  [8697/20519] intraday_16998.csv.gz  in=315,061,566 out=74,877,878 elapsed=148.3s

  [8698/20519] intraday_1700.csv.gz  in=315,088,207 out=74,877,878 elapsed=148.3s

  [8699/20519] intraday_16997.csv.gz  in=315,101,552 out=74,891,223 elapsed=148.3s

  [8700/20519] intraday_16999.csv.gz  in=315,113,622 out=74,903,293 elapsed=148.3s

  [8701/20519] intraday_17000.csv.gz  in=315,126,388 out=74,916,059 elapsed=148.3s

  [8702/20519] intraday_17001.csv.gz  in=315,138,092 out=74,927,763 elapsed=148.4s

  [8703/20519] intraday_17003.csv.gz  in=315,153,193 out=74,941,545 elapsed=148.4s

  [8704/20519] intraday_17002.csv.gz  in=315,166,206 out=74,954,558 elapsed=148.4s

  [8705/20519] intraday_17005.csv.gz  in=315,179,733 out=74,968,085 elapsed=148.4s

  [8706/20519] intraday_17004.csv.gz  in=315,195,946 out=74,983,501 elapsed=148.4s

  [8707/20519] intraday_17006.csv.gz  in=315,209,694 out=74,997,249 elapsed=148.4s

  [8708/20519] intraday_17007.csv.gz  in=315,225,131 out=75,012,686 elapsed=148.4s

  [8709/20519] intraday_17009.csv.gz  in=315,234,988 out=75,022,543 elapsed=148.5s

  [8710/20519] intraday_1701.csv.gz  in=315,246,179 out=75,022,543 elapsed=148.5s

  [8711/20519] intraday_17008.csv.gz  in=315,259,395 out=75,035,759 elapsed=148.5s

  [8712/20519] intraday_17010.csv.gz  in=315,271,321 out=75,047,685 elapsed=148.5s

  [8713/20519] intraday_17012.csv.gz  in=315,285,301 out=75,061,665 elapsed=148.5s

  [8714/20519] intraday_17011.csv.gz  in=315,298,192 out=75,074,556 elapsed=148.5s

  [8715/20519] intraday_17014.csv.gz  in=315,308,906 out=75,085,270 elapsed=148.5s

  [8716/20519] intraday_17013.csv.gz  in=315,321,143 out=75,097,507 elapsed=148.5s

  [8717/20519] intraday_17015.csv.gz  in=315,333,440 out=75,109,804 elapsed=148.6s

  [8718/20519] intraday_17016.csv.gz  in=315,343,880 out=75,120,244 elapsed=148.6s

  [8719/20519] intraday_17018.csv.gz  in=315,358,174 out=75,134,538 elapsed=148.6s

  [8720/20519] intraday_17017.csv.gz  in=315,375,930 out=75,152,294 elapsed=148.6s

  [8721/20519] intraday_1702.csv.gz  in=315,388,095 out=75,152,294 elapsed=148.6s

  [8722/20519] intraday_17019.csv.gz  in=315,400,213 out=75,164,412 elapsed=148.6s

  [8723/20519] intraday_17022.csv.gz  in=315,408,467 out=75,172,666 elapsed=148.6s

  [8724/20519] intraday_17020.csv.gz  in=315,421,655 out=75,185,854 elapsed=148.7s

  [8725/20519] intraday_17021.csv.gz  in=315,433,549 out=75,197,748 elapsed=148.7s

  [8726/20519] intraday_17023.csv.gz  in=315,446,526 out=75,210,725 elapsed=148.7s

  [8727/20519] intraday_17024.csv.gz  in=315,460,020 out=75,224,219 elapsed=148.7s

  [8728/20519] intraday_17025.csv.gz  in=315,472,848 out=75,237,047 elapsed=148.7s

  [8729/20519] intraday_17026.csv.gz  in=315,483,587 out=75,247,786 elapsed=148.7s

  [8730/20519] intraday_17027.csv.gz  in=315,496,301 out=75,260,500 elapsed=148.7s

  [8731/20519] intraday_17029.csv.gz  in=315,507,970 out=75,272,169 elapsed=148.7s

  [8732/20519] intraday_17028.csv.gz  in=315,518,225 out=75,282,424 elapsed=148.7s

  [8733/20519] intraday_1703.csv.gz  in=315,530,255 out=75,282,424 elapsed=148.7s

  [8734/20519] intraday_17030.csv.gz  in=315,544,293 out=75,296,462 elapsed=148.8s

  [8735/20519] intraday_17031.csv.gz  in=315,557,394 out=75,309,563 elapsed=148.8s

  [8736/20519] intraday_17033.csv.gz  in=315,567,211 out=75,319,380 elapsed=148.8s

  [8737/20519] intraday_17034.csv.gz  in=315,578,617 out=75,330,786 elapsed=148.8s

  [8738/20519] intraday_17032.csv.gz  in=315,592,588 out=75,344,757 elapsed=148.8s

  [8739/20519] intraday_17035.csv.gz  in=315,607,058 out=75,359,227 elapsed=148.9s

  [8740/20519] intraday_17036.csv.gz  in=315,625,949 out=75,378,118 elapsed=148.9s

  [8741/20519] intraday_17037.csv.gz  in=315,638,425 out=75,390,594 elapsed=148.9s

  [8742/20519] intraday_17038.csv.gz  in=315,653,368 out=75,405,537 elapsed=148.9s

  [8743/20519] intraday_17039.csv.gz  in=315,665,957 out=75,418,126 elapsed=148.9s

  [8744/20519] intraday_1704.csv.gz  in=315,676,394 out=75,418,126 elapsed=148.9s

  [8745/20519] intraday_17040.csv.gz  in=315,690,079 out=75,431,811 elapsed=149.0s

  [8746/20519] intraday_17043.csv.gz  in=315,700,657 out=75,442,389 elapsed=149.0s

  [8747/20519] intraday_17042.csv.gz  in=315,716,227 out=75,457,959 elapsed=149.0s

  [8748/20519] intraday_17044.csv.gz  in=315,729,414 out=75,471,146 elapsed=149.0s

  [8749/20519] intraday_17041.csv.gz  in=315,740,241 out=75,481,973 elapsed=149.0s

  [8750/20519] intraday_17045.csv.gz  in=315,751,818 out=75,493,550 elapsed=149.0s

  [8751/20519] intraday_17047.csv.gz  in=315,766,158 out=75,507,565 elapsed=149.1s

  [8752/20519] intraday_17048.csv.gz  in=315,777,570 out=75,518,977 elapsed=149.1s

  [8753/20519] intraday_17046.csv.gz  in=315,789,540 out=75,530,947 elapsed=149.1s

  [8754/20519] intraday_1705.csv.gz  in=315,799,153 out=75,530,947 elapsed=149.1s

  [8755/20519] intraday_17049.csv.gz  in=315,812,907 out=75,544,701 elapsed=149.1s

  [8756/20519] intraday_17050.csv.gz  in=315,826,586 out=75,558,380 elapsed=149.1s

  [8757/20519] intraday_17051.csv.gz  in=315,836,499 out=75,568,293 elapsed=149.1s

  [8758/20519] intraday_17053.csv.gz  in=315,848,567 out=75,580,361 elapsed=149.1s

  [8759/20519] intraday_17052.csv.gz  in=315,860,789 out=75,592,583 elapsed=149.1s

  [8760/20519] intraday_17054.csv.gz  in=315,873,791 out=75,605,585 elapsed=149.1s

  [8761/20519] intraday_17055.csv.gz  in=315,889,999 out=75,621,793 elapsed=149.2s

  [8762/20519] intraday_17057.csv.gz  in=315,901,558 out=75,633,352 elapsed=149.2s

  [8763/20519] intraday_17056.csv.gz  in=315,915,240 out=75,647,034 elapsed=149.2s

  [8764/20519] intraday_17058.csv.gz  in=315,929,940 out=75,661,734 elapsed=149.2s

  [8765/20519] intraday_17059.csv.gz  in=315,942,387 out=75,674,181 elapsed=149.2s

  [8766/20519] intraday_1706.csv.gz  in=315,957,241 out=75,674,181 elapsed=149.2s

  [8767/20519] intraday_17060.csv.gz  in=315,968,993 out=75,685,933 elapsed=149.2s

  [8768/20519] intraday_17063.csv.gz  in=315,983,642 out=75,700,582 elapsed=149.3s

  [8769/20519] intraday_17061.csv.gz  in=315,997,362 out=75,714,302 elapsed=149.3s

  [8770/20519] intraday_17062.csv.gz  in=316,011,802 out=75,728,742 elapsed=149.3s

  [8771/20519] intraday_17064.csv.gz  in=316,022,928 out=75,739,868 elapsed=149.3s

  [8772/20519] intraday_17065.csv.gz  in=316,036,842 out=75,753,782 elapsed=149.3s

  [8773/20519] intraday_17066.csv.gz  in=316,050,603 out=75,767,543 elapsed=149.3s

  [8774/20519] intraday_17067.csv.gz  in=316,065,817 out=75,782,757 elapsed=149.3s

  [8775/20519] intraday_17068.csv.gz  in=316,081,725 out=75,798,665 elapsed=149.3s

  [8776/20519] intraday_1707.csv.gz  in=316,092,883 out=75,798,665 elapsed=149.3s

  [8777/20519] intraday_17070.csv.gz  in=316,105,313 out=75,811,095 elapsed=149.4s

  [8778/20519] intraday_17069.csv.gz  in=316,130,367 out=75,836,149 elapsed=149.4s

  [8779/20519] intraday_17072.csv.gz  in=316,142,731 out=75,848,513 elapsed=149.4s

  [8780/20519] intraday_17073.csv.gz  in=316,172,683 out=75,873,229 elapsed=149.5s

  [8781/20519] intraday_17071.csv.gz  in=316,190,450 out=75,890,996 elapsed=149.5s

  [8782/20519] intraday_17075.csv.gz  in=316,203,664 out=75,904,210 elapsed=149.5s

  [8783/20519] intraday_17074.csv.gz  in=316,213,982 out=75,914,528 elapsed=149.5s

  [8784/20519] intraday_17077.csv.gz  in=316,226,900 out=75,927,446 elapsed=149.5s

  [8785/20519] intraday_17076.csv.gz  in=316,237,939 out=75,938,485 elapsed=149.5s

  [8786/20519] intraday_17079.csv.gz  in=316,253,614 out=75,954,160 elapsed=149.5s

  [8787/20519] intraday_17078.csv.gz  in=316,266,200 out=75,966,746 elapsed=149.5s

  [8788/20519] intraday_1708.csv.gz  in=316,277,653 out=75,966,746 elapsed=149.5s

  [8789/20519] intraday_17080.csv.gz  in=316,288,866 out=75,977,959 elapsed=149.6s

  [8790/20519] intraday_17081.csv.gz  in=316,300,832 out=75,989,925 elapsed=149.6s

  [8791/20519] intraday_17082.csv.gz  in=316,312,140 out=76,001,233 elapsed=149.6s

  [8792/20519] intraday_17083.csv.gz  in=316,326,827 out=76,015,920 elapsed=149.6s

  [8793/20519] intraday_17084.csv.gz  in=316,338,829 out=76,027,922 elapsed=149.6s

  [8794/20519] intraday_17086.csv.gz  in=316,352,609 out=76,041,702 elapsed=149.7s

  [8795/20519] intraday_17088.csv.gz  in=316,367,473 out=76,056,566 elapsed=149.7s

  [8796/20519] intraday_17085.csv.gz  in=316,383,357 out=76,072,450 elapsed=149.7s

  [8797/20519] intraday_17087.csv.gz  in=316,398,571 out=76,087,664 elapsed=149.7s

  [8798/20519] intraday_17089.csv.gz  in=316,410,288 out=76,099,381 elapsed=149.7s

  [8799/20519] intraday_1709.csv.gz  in=316,422,121 out=76,099,381 elapsed=149.7s

  [8800/20519] intraday_17091.csv.gz  in=316,434,624 out=76,111,884 elapsed=149.8s

  [8801/20519] intraday_17090.csv.gz  in=316,447,568 out=76,124,828 elapsed=149.8s

  [8802/20519] intraday_17092.csv.gz  in=316,457,560 out=76,134,820 elapsed=149.8s

  [8803/20519] intraday_17093.csv.gz  in=316,470,490 out=76,147,750 elapsed=149.8s

  [8804/20519] intraday_17094.csv.gz  in=316,480,781 out=76,158,041 elapsed=149.8s

  [8805/20519] intraday_17095.csv.gz  in=316,490,271 out=76,167,531 elapsed=149.8s

  [8806/20519] intraday_17097.csv.gz  in=316,506,367 out=76,183,627 elapsed=149.8s

  [8807/20519] intraday_17096.csv.gz  in=316,517,280 out=76,194,540 elapsed=149.9s

  [8808/20519] intraday_17098.csv.gz  in=316,530,376 out=76,207,636 elapsed=149.9s

  [8809/20519] intraday_1710.csv.gz  in=316,543,061 out=76,207,636 elapsed=149.9s

  [8810/20519] intraday_17099.csv.gz  in=316,556,889 out=76,221,464 elapsed=149.9s

  [8811/20519] intraday_17101.csv.gz  in=316,570,173 out=76,234,748 elapsed=149.9s

  [8812/20519] intraday_17100.csv.gz  in=316,580,467 out=76,245,042 elapsed=150.0s

  [8813/20519] intraday_17102.csv.gz  in=316,596,216 out=76,260,791 elapsed=150.0s

  [8814/20519] intraday_17103.csv.gz  in=316,609,362 out=76,273,937 elapsed=150.0s

  [8815/20519] intraday_17104.csv.gz  in=316,621,128 out=76,285,703 elapsed=150.1s

  [8816/20519] intraday_17105.csv.gz  in=316,633,356 out=76,297,931 elapsed=150.1s

  [8817/20519] intraday_17107.csv.gz  in=316,643,925 out=76,308,500 elapsed=150.1s

  [8818/20519] intraday_17106.csv.gz  in=316,657,682 out=76,322,257 elapsed=150.1s

  [8819/20519] intraday_17108.csv.gz  in=316,670,789 out=76,335,364 elapsed=150.1s

  [8820/20519] intraday_17110.csv.gz  in=316,683,529 out=76,348,104 elapsed=150.1s

  [8821/20519] intraday_1711.csv.gz  in=316,702,954 out=76,348,104 elapsed=150.1s

  [8822/20519] intraday_17109.csv.gz  in=316,716,979 out=76,362,129 elapsed=150.1s

  [8823/20519] intraday_17111.csv.gz  in=316,727,692 out=76,372,842 elapsed=150.1s

  [8824/20519] intraday_17112.csv.gz  in=316,739,771 out=76,384,921 elapsed=150.2s

  [8825/20519] intraday_17113.csv.gz  in=316,755,073 out=76,400,223 elapsed=150.2s

  [8826/20519] intraday_17114.csv.gz  in=316,769,456 out=76,414,606 elapsed=150.2s

  [8827/20519] intraday_17115.csv.gz  in=316,780,754 out=76,425,904 elapsed=150.2s

  [8828/20519] intraday_17116.csv.gz  in=316,791,377 out=76,436,527 elapsed=150.2s

  [8829/20519] intraday_17118.csv.gz  in=316,804,128 out=76,449,278 elapsed=150.2s

  [8830/20519] intraday_17119.csv.gz  in=316,816,588 out=76,461,738 elapsed=150.3s

  [8831/20519] intraday_17117.csv.gz  in=316,830,657 out=76,475,807 elapsed=150.3s

  [8832/20519] intraday_1712.csv.gz  in=316,842,569 out=76,475,807 elapsed=150.3s

  [8833/20519] intraday_17120.csv.gz  in=316,855,292 out=76,488,530 elapsed=150.3s

  [8834/20519] intraday_17121.csv.gz  in=316,867,387 out=76,500,625 elapsed=150.3s

  [8835/20519] intraday_17122.csv.gz  in=316,879,037 out=76,512,275 elapsed=150.3s

  [8836/20519] intraday_17123.csv.gz  in=316,891,303 out=76,524,541 elapsed=150.3s

  [8837/20519] intraday_17124.csv.gz  in=316,902,471 out=76,535,709 elapsed=150.3s

  [8838/20519] intraday_17125.csv.gz  in=316,917,247 out=76,550,485 elapsed=150.4s

  [8839/20519] intraday_17126.csv.gz  in=316,932,390 out=76,565,628 elapsed=150.4s

  [8840/20519] intraday_17127.csv.gz  in=316,946,764 out=76,580,002 elapsed=150.4s

  [8841/20519] intraday_17128.csv.gz  in=316,959,642 out=76,592,880 elapsed=150.4s

  [8842/20519] intraday_1713.csv.gz  in=316,972,593 out=76,592,880 elapsed=150.4s

  [8843/20519] intraday_17129.csv.gz  in=316,984,613 out=76,604,900 elapsed=150.4s

  [8844/20519] intraday_17130.csv.gz  in=316,999,622 out=76,619,909 elapsed=150.4s

  [8845/20519] intraday_17131.csv.gz  in=317,013,275 out=76,633,562 elapsed=150.5s

  [8846/20519] intraday_17133.csv.gz  in=317,025,921 out=76,646,208 elapsed=150.5s

  [8847/20519] intraday_17132.csv.gz  in=317,039,815 out=76,660,102 elapsed=150.5s

  [8848/20519] intraday_17134.csv.gz  in=317,050,786 out=76,671,073 elapsed=150.5s

  [8849/20519] intraday_17135.csv.gz  in=317,061,575 out=76,681,862 elapsed=150.5s

  [8850/20519] intraday_17137.csv.gz  in=317,073,458 out=76,693,745 elapsed=150.5s

  [8851/20519] intraday_17136.csv.gz  in=317,084,534 out=76,704,821 elapsed=150.5s

  [8852/20519] intraday_17138.csv.gz  in=317,097,631 out=76,717,918 elapsed=150.5s

  [8853/20519] intraday_17139.csv.gz  in=317,112,011 out=76,732,298 elapsed=150.6s

  [8854/20519] intraday_1714.csv.gz  in=317,122,947 out=76,732,298 elapsed=150.6s

  [8855/20519] intraday_17140.csv.gz  in=317,136,553 out=76,745,904 elapsed=150.6s

  [8856/20519] intraday_17141.csv.gz  in=317,150,895 out=76,760,246 elapsed=150.6s

  [8857/20519] intraday_17142.csv.gz  in=317,162,114 out=76,771,465 elapsed=150.6s

  [8858/20519] intraday_17144.csv.gz  in=317,175,409 out=76,784,760 elapsed=150.7s

  [8859/20519] intraday_17143.csv.gz  in=317,187,456 out=76,796,807 elapsed=150.7s

  [8860/20519] intraday_17145.csv.gz  in=317,199,121 out=76,808,472 elapsed=150.7s

  [8861/20519] intraday_17146.csv.gz  in=317,211,293 out=76,820,644 elapsed=150.7s

  [8862/20519] intraday_17147.csv.gz  in=317,222,898 out=76,832,249 elapsed=150.7s

  [8863/20519] intraday_1715.csv.gz  in=317,236,156 out=76,832,249 elapsed=150.7s

  [8864/20519] intraday_17149.csv.gz  in=317,249,196 out=76,845,289 elapsed=150.7s

  [8865/20519] intraday_17148.csv.gz  in=317,263,920 out=76,860,013 elapsed=150.7s

  [8866/20519] intraday_17150.csv.gz  in=317,277,519 out=76,873,612 elapsed=150.7s

  [8867/20519] intraday_17152.csv.gz  in=317,289,919 out=76,886,012 elapsed=150.8s

  [8868/20519] intraday_17151.csv.gz  in=317,305,135 out=76,901,228 elapsed=150.8s

  [8869/20519] intraday_17153.csv.gz  in=317,317,348 out=76,913,441 elapsed=150.8s

  [8870/20519] intraday_17154.csv.gz  in=317,329,170 out=76,925,263 elapsed=150.8s

  [8871/20519] intraday_17155.csv.gz  in=317,341,875 out=76,937,968 elapsed=150.8s

  [8872/20519] intraday_17156.csv.gz  in=317,353,792 out=76,949,885 elapsed=150.8s

  [8873/20519] intraday_17158.csv.gz  in=317,364,584 out=76,960,677 elapsed=150.8s

  [8874/20519] intraday_17157.csv.gz  in=317,377,975 out=76,974,068 elapsed=150.8s

  [8875/20519] intraday_17159.csv.gz  in=317,390,342 out=76,986,435 elapsed=150.8s

  [8876/20519] intraday_1716.csv.gz  in=317,401,618 out=76,986,435 elapsed=150.9s

  [8877/20519] intraday_17160.csv.gz  in=317,412,332 out=76,997,149 elapsed=150.9s

  [8878/20519] intraday_17161.csv.gz  in=317,428,130 out=77,012,947 elapsed=150.9s

  [8879/20519] intraday_17163.csv.gz  in=317,442,082 out=77,026,899 elapsed=150.9s

  [8880/20519] intraday_17162.csv.gz  in=317,454,534 out=77,039,351 elapsed=150.9s

  [8881/20519] intraday_17164.csv.gz  in=317,467,686 out=77,052,503 elapsed=151.0s

  [8882/20519] intraday_17165.csv.gz  in=317,478,877 out=77,063,694 elapsed=151.0s

  [8883/20519] intraday_17166.csv.gz  in=317,488,664 out=77,073,481 elapsed=151.0s

  [8884/20519] intraday_17167.csv.gz  in=317,500,716 out=77,085,533 elapsed=151.0s

  [8885/20519] intraday_17169.csv.gz  in=317,513,049 out=77,097,866 elapsed=151.0s

  [8886/20519] intraday_17168.csv.gz  in=317,526,929 out=77,111,746 elapsed=151.0s

  [8887/20519] intraday_1717.csv.gz  in=317,537,307 out=77,111,746 elapsed=151.0s

  [8888/20519] intraday_17170.csv.gz  in=317,548,954 out=77,123,393 elapsed=151.0s

  [8889/20519] intraday_17171.csv.gz  in=317,560,944 out=77,135,383 elapsed=151.0s

  [8890/20519] intraday_17173.csv.gz  in=317,575,439 out=77,149,878 elapsed=151.1s

  [8891/20519] intraday_17172.csv.gz  in=317,585,580 out=77,160,019 elapsed=151.1s

  [8892/20519] intraday_17175.csv.gz  in=317,599,258 out=77,173,697 elapsed=151.1s

  [8893/20519] intraday_17174.csv.gz  in=317,613,417 out=77,187,856 elapsed=151.1s

  [8894/20519] intraday_17176.csv.gz  in=317,623,742 out=77,198,181 elapsed=151.1s

  [8895/20519] intraday_17177.csv.gz  in=317,634,855 out=77,209,294 elapsed=151.1s

  [8896/20519] intraday_17179.csv.gz  in=317,649,835 out=77,224,274 elapsed=151.1s

  [8897/20519] intraday_17178.csv.gz  in=317,664,069 out=77,238,508 elapsed=151.1s

  [8898/20519] intraday_1718.csv.gz  in=317,679,569 out=77,238,508 elapsed=151.1s

  [8899/20519] intraday_17180.csv.gz  in=317,695,120 out=77,254,059 elapsed=151.2s

  [8900/20519] intraday_17181.csv.gz  in=317,708,439 out=77,267,378 elapsed=151.2s

  [8901/20519] intraday_17182.csv.gz  in=317,721,640 out=77,280,579 elapsed=151.2s

  [8902/20519] intraday_17183.csv.gz  in=317,734,308 out=77,293,247 elapsed=151.2s

  [8903/20519] intraday_17184.csv.gz  in=317,746,072 out=77,305,011 elapsed=151.2s

  [8904/20519] intraday_17185.csv.gz  in=317,762,004 out=77,320,943 elapsed=151.3s

  [8905/20519] intraday_17186.csv.gz  in=317,773,942 out=77,332,881 elapsed=151.3s

  [8906/20519] intraday_17188.csv.gz  in=317,788,049 out=77,346,988 elapsed=151.3s

  [8907/20519] intraday_17187.csv.gz  in=317,799,690 out=77,358,629 elapsed=151.3s

  [8908/20519] intraday_1719.csv.gz  in=317,812,829 out=77,358,629 elapsed=151.3s

  [8909/20519] intraday_17189.csv.gz  in=317,824,437 out=77,370,237 elapsed=151.3s

  [8910/20519] intraday_17191.csv.gz  in=317,837,175 out=77,382,975 elapsed=151.3s

  [8911/20519] intraday_17190.csv.gz  in=317,850,540 out=77,396,340 elapsed=151.3s

  [8912/20519] intraday_17192.csv.gz  in=317,863,517 out=77,409,317 elapsed=151.3s

  [8913/20519] intraday_17193.csv.gz  in=317,875,864 out=77,421,664 elapsed=151.3s

  [8914/20519] intraday_17194.csv.gz  in=317,886,845 out=77,432,645 elapsed=151.3s

  [8915/20519] intraday_17195.csv.gz  in=317,898,108 out=77,443,908 elapsed=151.3s

  [8916/20519] intraday_17196.csv.gz  in=317,909,814 out=77,455,614 elapsed=151.3s

  [8917/20519] intraday_17197.csv.gz  in=317,922,822 out=77,468,622 elapsed=151.4s

  [8918/20519] intraday_1720.csv.gz  in=317,935,396 out=77,468,622 elapsed=151.4s

  [8919/20519] intraday_17198.csv.gz  in=317,949,659 out=77,482,885 elapsed=151.4s

  [8920/20519] intraday_17199.csv.gz  in=317,964,967 out=77,498,193 elapsed=151.4s

  [8921/20519] intraday_17200.csv.gz  in=317,977,315 out=77,510,541 elapsed=151.4s

  [8922/20519] intraday_17201.csv.gz  in=317,990,702 out=77,523,928 elapsed=151.4s

  [8923/20519] intraday_17203.csv.gz  in=318,001,970 out=77,535,196 elapsed=151.4s

  [8924/20519] intraday_17202.csv.gz  in=318,015,552 out=77,548,778 elapsed=151.4s

  [8925/20519] intraday_17204.csv.gz  in=318,028,843 out=77,562,069 elapsed=151.4s

  [8926/20519] intraday_17205.csv.gz  in=318,042,004 out=77,575,230 elapsed=151.4s

  [8927/20519] intraday_17206.csv.gz  in=318,057,449 out=77,590,675 elapsed=151.5s

  [8928/20519] intraday_17208.csv.gz  in=318,071,773 out=77,604,999 elapsed=151.5s

  [8929/20519] intraday_17207.csv.gz  in=318,083,831 out=77,617,057 elapsed=151.5s

  [8930/20519] intraday_17209.csv.gz  in=318,098,106 out=77,631,332 elapsed=151.5s

  [8931/20519] intraday_1721.csv.gz  in=318,112,321 out=77,631,332 elapsed=151.5s

  [8932/20519] intraday_17210.csv.gz  in=318,125,678 out=77,644,689 elapsed=151.5s

  [8933/20519] intraday_17211.csv.gz  in=318,140,808 out=77,659,819 elapsed=151.5s

  [8934/20519] intraday_17212.csv.gz  in=318,158,447 out=77,677,458 elapsed=151.6s

  [8935/20519] intraday_17213.csv.gz  in=318,172,458 out=77,691,469 elapsed=151.6s

  [8936/20519] intraday_17214.csv.gz  in=318,188,995 out=77,708,006 elapsed=151.6s

  [8937/20519] intraday_17215.csv.gz  in=318,203,115 out=77,722,126 elapsed=151.6s

  [8938/20519] intraday_17216.csv.gz  in=318,215,645 out=77,734,656 elapsed=151.6s

  [8939/20519] intraday_17217.csv.gz  in=318,227,850 out=77,746,861 elapsed=151.6s

  [8940/20519] intraday_1722.csv.gz  in=318,241,086 out=77,746,861 elapsed=151.6s

  [8941/20519] intraday_17219.csv.gz  in=318,253,067 out=77,758,842 elapsed=151.6s

  [8942/20519] intraday_17218.csv.gz  in=318,264,232 out=77,770,007 elapsed=151.6s

  [8943/20519] intraday_17220.csv.gz  in=318,276,355 out=77,782,130 elapsed=151.7s

  [8944/20519] intraday_17221.csv.gz  in=318,290,113 out=77,795,888 elapsed=151.7s

  [8945/20519] intraday_17223.csv.gz  in=318,303,117 out=77,808,892 elapsed=151.7s

  [8946/20519] intraday_17222.csv.gz  in=318,317,549 out=77,823,324 elapsed=151.7s

  [8947/20519] intraday_17224.csv.gz  in=318,329,788 out=77,835,563 elapsed=151.7s

  [8948/20519] intraday_17225.csv.gz  in=318,342,112 out=77,847,887 elapsed=151.7s

  [8949/20519] intraday_17227.csv.gz  in=318,354,423 out=77,860,198 elapsed=151.7s

  [8950/20519] intraday_17226.csv.gz  in=318,366,795 out=77,872,570 elapsed=151.7s

  [8951/20519] intraday_17228.csv.gz  in=318,380,963 out=77,886,738 elapsed=151.8s

  [8952/20519] intraday_1723.csv.gz  in=318,390,109 out=77,886,738 elapsed=151.8s

  [8953/20519] intraday_17229.csv.gz  in=318,404,945 out=77,901,574 elapsed=151.8s

  [8954/20519] intraday_17230.csv.gz  in=318,419,676 out=77,916,305 elapsed=151.8s

  [8955/20519] intraday_17232.csv.gz  in=318,431,429 out=77,928,058 elapsed=151.8s

  [8956/20519] intraday_17231.csv.gz  in=318,445,565 out=77,942,194 elapsed=151.8s

  [8957/20519] intraday_17233.csv.gz  in=318,458,882 out=77,955,511 elapsed=151.8s

  [8958/20519] intraday_17234.csv.gz  in=318,471,393 out=77,968,022 elapsed=151.8s

  [8959/20519] intraday_17235.csv.gz  in=318,481,841 out=77,978,470 elapsed=151.8s

  [8960/20519] intraday_17237.csv.gz  in=318,492,289 out=77,988,918 elapsed=151.9s

  [8961/20519] intraday_17238.csv.gz  in=318,501,285 out=77,997,914 elapsed=151.9s

  [8962/20519] intraday_17236.csv.gz  in=318,514,788 out=78,011,417 elapsed=151.9s

  [8963/20519] intraday_1724.csv.gz  in=318,526,890 out=78,011,417 elapsed=151.9s

  [8964/20519] intraday_17239.csv.gz  in=318,540,677 out=78,025,204 elapsed=151.9s

  [8965/20519] intraday_17241.csv.gz  in=318,555,412 out=78,039,939 elapsed=151.9s

  [8966/20519] intraday_17240.csv.gz  in=318,571,111 out=78,055,638 elapsed=151.9s

  [8967/20519] intraday_17242.csv.gz  in=318,582,594 out=78,067,121 elapsed=151.9s

  [8968/20519] intraday_17243.csv.gz  in=318,592,948 out=78,077,475 elapsed=151.9s

  [8969/20519] intraday_17244.csv.gz  in=318,606,594 out=78,091,121 elapsed=152.0s

  [8970/20519] intraday_17246.csv.gz  in=318,619,069 out=78,103,596 elapsed=152.0s

  [8971/20519] intraday_17245.csv.gz  in=318,633,657 out=78,118,184 elapsed=152.0s

  [8972/20519] intraday_17248.csv.gz  in=318,645,739 out=78,130,266 elapsed=152.0s

  [8973/20519] intraday_17247.csv.gz  in=318,658,260 out=78,142,787 elapsed=152.0s

  [8974/20519] intraday_1725.csv.gz  in=318,670,246 out=78,142,787 elapsed=152.0s

  [8975/20519] intraday_17250.csv.gz  in=318,679,716 out=78,152,257 elapsed=152.0s

  [8976/20519] intraday_17249.csv.gz  in=318,693,971 out=78,166,512 elapsed=152.1s

  [8977/20519] intraday_17252.csv.gz  in=318,708,920 out=78,181,461 elapsed=152.1s

  [8978/20519] intraday_17253.csv.gz  in=318,720,196 out=78,192,737 elapsed=152.1s

  [8979/20519] intraday_17251.csv.gz  in=318,734,052 out=78,206,593 elapsed=152.1s

  [8980/20519] intraday_17255.csv.gz  in=318,745,573 out=78,218,114 elapsed=152.1s

  [8981/20519] intraday_17254.csv.gz  in=318,756,116 out=78,228,657 elapsed=152.1s

  [8982/20519] intraday_17256.csv.gz  in=318,772,071 out=78,244,612 elapsed=152.1s

  [8983/20519] intraday_17258.csv.gz  in=318,782,690 out=78,255,231 elapsed=152.1s

  [8984/20519] intraday_17257.csv.gz  in=318,796,351 out=78,268,892 elapsed=152.1s

  [8985/20519] intraday_17259.csv.gz  in=318,806,463 out=78,279,004 elapsed=152.1s

  [8986/20519] intraday_1726.csv.gz  in=318,819,009 out=78,279,004 elapsed=152.2s

  [8987/20519] intraday_17260.csv.gz  in=318,832,177 out=78,292,172 elapsed=152.2s

  [8988/20519] intraday_17261.csv.gz  in=318,844,799 out=78,304,794 elapsed=152.2s

  [8989/20519] intraday_17262.csv.gz  in=318,858,122 out=78,318,117 elapsed=152.2s

  [8990/20519] intraday_17263.csv.gz  in=318,871,667 out=78,330,746 elapsed=152.2s

  [8991/20519] intraday_17264.csv.gz  in=318,883,521 out=78,342,600 elapsed=152.2s

  [8992/20519] intraday_17265.csv.gz  in=318,894,546 out=78,353,625 elapsed=152.2s

  [8993/20519] intraday_17266.csv.gz  in=318,907,242 out=78,366,321 elapsed=152.2s

  [8994/20519] intraday_17267.csv.gz  in=318,917,546 out=78,376,625 elapsed=152.2s

  [8995/20519] intraday_17268.csv.gz  in=318,932,267 out=78,391,346 elapsed=152.2s

  [8996/20519] intraday_1727.csv.gz  in=318,944,164 out=78,391,346 elapsed=152.2s

  [8997/20519] intraday_17269.csv.gz  in=318,957,486 out=78,404,668 elapsed=152.2s

  [8998/20519] intraday_17271.csv.gz  in=318,970,158 out=78,417,340 elapsed=152.2s

  [8999/20519] intraday_17270.csv.gz  in=318,984,619 out=78,431,801 elapsed=152.3s

  [9000/20519] intraday_17273.csv.gz  in=318,999,366 out=78,446,548 elapsed=152.3s

  [9001/20519] intraday_17274.csv.gz  in=319,013,315 out=78,460,497 elapsed=152.3s

  [9002/20519] intraday_17272.csv.gz  in=319,035,769 out=78,480,201 elapsed=152.3s

  [9003/20519] intraday_17276.csv.gz  in=319,047,841 out=78,492,273 elapsed=152.3s

  [9004/20519] intraday_17275.csv.gz  in=319,060,693 out=78,505,125 elapsed=152.3s

  [9005/20519] intraday_17277.csv.gz  in=319,071,980 out=78,516,412 elapsed=152.3s

  [9006/20519] intraday_1728.csv.gz  in=319,082,676 out=78,516,412 elapsed=152.3s

  [9007/20519] intraday_17278.csv.gz  in=319,092,814 out=78,526,550 elapsed=152.4s

  [9008/20519] intraday_17279.csv.gz  in=319,104,456 out=78,538,192 elapsed=152.4s

  [9009/20519] intraday_17280.csv.gz  in=319,115,916 out=78,549,652 elapsed=152.4s

  [9010/20519] intraday_17284.csv.gz  in=319,128,967 out=78,562,703 elapsed=152.4s

  [9011/20519] intraday_17281.csv.gz  in=319,141,604 out=78,575,340 elapsed=152.4s

  [9012/20519] intraday_17283.csv.gz  in=319,156,124 out=78,589,860 elapsed=152.4s

  [9013/20519] intraday_17282.csv.gz  in=319,170,078 out=78,603,814 elapsed=152.4s

  [9014/20519] intraday_17285.csv.gz  in=319,181,225 out=78,614,961 elapsed=152.4s

  [9015/20519] intraday_17286.csv.gz  in=319,192,422 out=78,626,158 elapsed=152.5s

  [9016/20519] intraday_17287.csv.gz  in=319,205,602 out=78,639,338 elapsed=152.5s

  [9017/20519] intraday_17288.csv.gz  in=319,217,117 out=78,650,853 elapsed=152.5s

  [9018/20519] intraday_1729.csv.gz  in=319,229,233 out=78,650,853 elapsed=152.5s

  [9019/20519] intraday_17289.csv.gz  in=319,241,738 out=78,663,358 elapsed=152.5s

  [9020/20519] intraday_17290.csv.gz  in=319,253,382 out=78,675,002 elapsed=152.5s

  [9021/20519] intraday_17291.csv.gz  in=319,268,778 out=78,690,398 elapsed=152.6s

  [9022/20519] intraday_17292.csv.gz  in=319,281,368 out=78,702,988 elapsed=152.6s

  [9023/20519] intraday_17293.csv.gz  in=319,294,725 out=78,716,345 elapsed=152.6s

  [9024/20519] intraday_17294.csv.gz  in=319,309,937 out=78,731,557 elapsed=152.6s

  [9025/20519] intraday_17295.csv.gz  in=319,322,118 out=78,743,738 elapsed=152.6s

  [9026/20519] intraday_17296.csv.gz  in=319,334,825 out=78,756,445 elapsed=152.6s

  [9027/20519] intraday_17297.csv.gz  in=319,346,230 out=78,767,850 elapsed=152.6s

  [9028/20519] intraday_1730.csv.gz  in=319,357,506 out=78,767,850 elapsed=152.6s

  [9029/20519] intraday_17298.csv.gz  in=319,370,526 out=78,780,870 elapsed=152.6s

  [9030/20519] intraday_17301.csv.gz  in=319,381,270 out=78,791,614 elapsed=152.7s

  [9031/20519] intraday_17299.csv.gz  in=319,414,640 out=78,818,456 elapsed=152.7s

  [9032/20519] intraday_17303.csv.gz  in=319,425,432 out=78,829,248 elapsed=152.7s

  [9033/20519] intraday_17302.csv.gz  in=319,438,086 out=78,841,902 elapsed=152.7s

  [9034/20519] intraday_17300.csv.gz  in=319,452,026 out=78,855,842 elapsed=152.7s

  [9035/20519] intraday_17305.csv.gz  in=319,464,183 out=78,867,999 elapsed=152.8s

  [9036/20519] intraday_17304.csv.gz  in=319,480,571 out=78,884,387 elapsed=152.8s

  [9037/20519] intraday_17306.csv.gz  in=319,494,753 out=78,898,569 elapsed=152.8s

  [9038/20519] intraday_17308.csv.gz  in=319,508,661 out=78,911,706 elapsed=152.8s

  [9039/20519] intraday_17309.csv.gz  in=319,518,538 out=78,921,583 elapsed=152.8s

  [9040/20519] intraday_17307.csv.gz  in=319,533,316 out=78,936,361 elapsed=152.8s

  [9041/20519] intraday_1731.csv.gz  in=319,544,720 out=78,936,361 elapsed=152.8s

  [9042/20519] intraday_17312.csv.gz  in=319,556,520 out=78,948,161 elapsed=152.8s

  [9043/20519] intraday_17310.csv.gz  in=319,570,125 out=78,961,766 elapsed=152.9s

  [9044/20519] intraday_17311.csv.gz  in=319,583,374 out=78,975,015 elapsed=152.9s

  [9045/20519] intraday_17313.csv.gz  in=319,594,538 out=78,986,179 elapsed=152.9s

  [9046/20519] intraday_17314.csv.gz  in=319,605,226 out=78,996,867 elapsed=152.9s

  [9047/20519] intraday_17315.csv.gz  in=319,615,285 out=79,006,926 elapsed=152.9s

  [9048/20519] intraday_17316.csv.gz  in=319,630,118 out=79,021,759 elapsed=152.9s

  [9049/20519] intraday_17317.csv.gz  in=319,642,407 out=79,034,048 elapsed=152.9s

  [9050/20519] intraday_17319.csv.gz  in=319,652,952 out=79,044,593 elapsed=153.0s

  [9051/20519] intraday_17318.csv.gz  in=319,666,486 out=79,058,127 elapsed=153.0s

  [9052/20519] intraday_1732.csv.gz  in=319,678,589 out=79,058,127 elapsed=153.0s

  [9053/20519] intraday_17321.csv.gz  in=319,691,670 out=79,071,208 elapsed=153.0s

  [9054/20519] intraday_17320.csv.gz  in=319,702,815 out=79,082,353 elapsed=153.0s

  [9055/20519] intraday_17322.csv.gz  in=319,718,835 out=79,098,373 elapsed=153.0s

  [9056/20519] intraday_17323.csv.gz  in=319,733,648 out=79,113,186 elapsed=153.0s

  [9057/20519] intraday_17325.csv.gz  in=319,746,289 out=79,125,827 elapsed=153.1s

  [9058/20519] intraday_17324.csv.gz  in=319,759,290 out=79,138,828 elapsed=153.1s

  [9059/20519] intraday_17326.csv.gz  in=319,774,554 out=79,154,092 elapsed=153.1s

  [9060/20519] intraday_17328.csv.gz  in=319,789,287 out=79,168,825 elapsed=153.1s

  [9061/20519] intraday_17327.csv.gz  in=319,798,617 out=79,178,155 elapsed=153.1s

  [9062/20519] intraday_17329.csv.gz  in=319,808,872 out=79,188,410 elapsed=153.1s

  [9063/20519] intraday_1733.csv.gz  in=319,821,859 out=79,188,410 elapsed=153.1s

  [9064/20519] intraday_17330.csv.gz  in=319,834,203 out=79,200,754 elapsed=153.2s

  [9065/20519] intraday_17331.csv.gz  in=319,848,686 out=79,215,188 elapsed=153.2s

  [9066/20519] intraday_17332.csv.gz  in=319,859,609 out=79,226,111 elapsed=153.2s

  [9067/20519] intraday_17333.csv.gz  in=319,873,074 out=79,239,576 elapsed=153.2s

  [9068/20519] intraday_17335.csv.gz  in=319,885,786 out=79,252,288 elapsed=153.2s

  [9069/20519] intraday_17334.csv.gz  in=319,898,347 out=79,264,849 elapsed=153.2s

  [9070/20519] intraday_17336.csv.gz  in=319,910,876 out=79,277,378 elapsed=153.3s

  [9071/20519] intraday_17337.csv.gz  in=319,921,697 out=79,288,199 elapsed=153.3s

  [9072/20519] intraday_17339.csv.gz  in=319,932,972 out=79,299,474 elapsed=153.3s

  [9073/20519] intraday_17338.csv.gz  in=319,945,547 out=79,312,049 elapsed=153.3s

  [9074/20519] intraday_1734.csv.gz  in=319,955,637 out=79,312,049 elapsed=153.3s

  [9075/20519] intraday_17340.csv.gz  in=319,969,063 out=79,325,475 elapsed=153.3s

  [9076/20519] intraday_17341.csv.gz  in=319,983,306 out=79,339,718 elapsed=153.3s

  [9077/20519] intraday_17343.csv.gz  in=319,994,791 out=79,351,203 elapsed=153.3s

  [9078/20519] intraday_17342.csv.gz  in=320,008,994 out=79,365,406 elapsed=153.3s

  [9079/20519] intraday_17344.csv.gz  in=320,022,940 out=79,379,352 elapsed=153.3s

  [9080/20519] intraday_17346.csv.gz  in=320,034,971 out=79,391,383 elapsed=153.4s

  [9081/20519] intraday_17345.csv.gz  in=320,049,115 out=79,405,527 elapsed=153.4s

  [9082/20519] intraday_17347.csv.gz  in=320,062,498 out=79,418,910 elapsed=153.4s

  [9083/20519] intraday_17348.csv.gz  in=320,076,363 out=79,432,775 elapsed=153.4s

  [9084/20519] intraday_1735.csv.gz  in=320,087,569 out=79,432,775 elapsed=153.4s

  [9085/20519] intraday_17349.csv.gz  in=320,101,967 out=79,447,173 elapsed=153.4s

  [9086/20519] intraday_17350.csv.gz  in=320,113,299 out=79,458,505 elapsed=153.4s

  [9087/20519] intraday_17351.csv.gz  in=320,127,283 out=79,472,489 elapsed=153.4s

  [9088/20519] intraday_17352.csv.gz  in=320,140,356 out=79,485,562 elapsed=153.4s

  [9089/20519] intraday_17353.csv.gz  in=320,154,443 out=79,499,649 elapsed=153.5s

  [9090/20519] intraday_17354.csv.gz  in=320,170,766 out=79,515,972 elapsed=153.5s

  [9091/20519] intraday_17355.csv.gz  in=320,189,672 out=79,534,878 elapsed=153.5s

  [9092/20519] intraday_17356.csv.gz  in=320,202,709 out=79,547,915 elapsed=153.5s

  [9093/20519] intraday_17357.csv.gz  in=320,220,009 out=79,565,215 elapsed=153.5s

  [9094/20519] intraday_17359.csv.gz  in=320,233,030 out=79,578,236 elapsed=153.5s

  [9095/20519] intraday_1736.csv.gz  in=320,244,630 out=79,578,236 elapsed=153.6s

  [9096/20519] intraday_17358.csv.gz  in=320,256,641 out=79,590,247 elapsed=153.6s

  [9097/20519] intraday_17360.csv.gz  in=320,267,435 out=79,601,041 elapsed=153.6s

  [9098/20519] intraday_17362.csv.gz  in=320,277,626 out=79,611,232 elapsed=153.6s

  [9099/20519] intraday_17361.csv.gz  in=320,290,588 out=79,624,194 elapsed=153.6s

  [9100/20519] intraday_17364.csv.gz  in=320,303,908 out=79,637,514 elapsed=153.6s

  [9101/20519] intraday_17365.csv.gz  in=320,318,130 out=79,651,736 elapsed=153.6s

  [9102/20519] intraday_17366.csv.gz  in=320,330,066 out=79,663,672 elapsed=153.6s

  [9103/20519] intraday_17363.csv.gz  in=320,344,533 out=79,678,139 elapsed=153.7s

  [9104/20519] intraday_17367.csv.gz  in=320,356,239 out=79,689,845 elapsed=153.7s

  [9105/20519] intraday_17368.csv.gz  in=320,369,261 out=79,702,867 elapsed=153.7s

  [9106/20519] intraday_1737.csv.gz  in=320,384,990 out=79,702,867 elapsed=153.7s

  [9107/20519] intraday_17369.csv.gz  in=320,398,570 out=79,716,447 elapsed=153.7s

  [9108/20519] intraday_17370.csv.gz  in=320,409,851 out=79,727,728 elapsed=153.7s

  [9109/20519] intraday_17371.csv.gz  in=320,423,874 out=79,741,751 elapsed=153.7s

  [9110/20519] intraday_17374.csv.gz  in=320,440,257 out=79,758,134 elapsed=153.8s

  [9111/20519] intraday_17372.csv.gz  in=320,454,909 out=79,772,786 elapsed=153.8s

  [9112/20519] intraday_17373.csv.gz  in=320,469,166 out=79,787,043 elapsed=153.8s

  [9113/20519] intraday_17375.csv.gz  in=320,479,748 out=79,797,625 elapsed=153.8s

  [9114/20519] intraday_17379.csv.gz  in=320,493,156 out=79,811,033 elapsed=153.8s

  [9115/20519] intraday_17377.csv.gz  in=320,505,107 out=79,822,984 elapsed=153.8s

  [9116/20519] intraday_17376.csv.gz  in=320,519,609 out=79,837,486 elapsed=153.8s

  [9117/20519] intraday_17378.csv.gz  in=320,530,323 out=79,848,200 elapsed=153.8s

  [9118/20519] intraday_17382.csv.gz  in=320,537,386 out=79,855,263 elapsed=153.8s

  [9119/20519] intraday_17381.csv.gz  in=320,549,445 out=79,867,322 elapsed=153.8s

  [9120/20519] intraday_17380.csv.gz  in=320,557,947 out=79,875,824 elapsed=153.8s

  [9121/20519] intraday_1738.csv.gz  in=320,568,999 out=79,875,824 elapsed=153.9s

  [9122/20519] intraday_17383.csv.gz  in=320,584,768 out=79,891,593 elapsed=153.9s

  [9123/20519] intraday_17386.csv.gz  in=320,595,627 out=79,902,452 elapsed=153.9s

  [9124/20519] intraday_17384.csv.gz  in=320,609,913 out=79,916,738 elapsed=154.0s

  [9125/20519] intraday_17387.csv.gz  in=320,623,241 out=79,930,066 elapsed=154.0s

  [9126/20519] intraday_17385.csv.gz  in=320,635,176 out=79,942,001 elapsed=154.0s

  [9127/20519] intraday_17388.csv.gz  in=320,650,657 out=79,957,482 elapsed=154.0s

  [9128/20519] intraday_17389.csv.gz  in=320,663,695 out=79,970,520 elapsed=154.0s

  [9129/20519] intraday_1739.csv.gz  in=320,673,268 out=79,970,520 elapsed=154.1s

  [9130/20519] intraday_17390.csv.gz  in=320,684,652 out=79,981,904 elapsed=154.1s

  [9131/20519] intraday_17391.csv.gz  in=320,697,712 out=79,994,964 elapsed=154.1s

  [9132/20519] intraday_17392.csv.gz  in=320,712,122 out=80,009,374 elapsed=154.1s

  [9133/20519] intraday_17393.csv.gz  in=320,723,027 out=80,020,279 elapsed=154.1s

  [9134/20519] intraday_17394.csv.gz  in=320,740,608 out=80,036,880 elapsed=154.1s

  [9135/20519] intraday_17396.csv.gz  in=320,752,708 out=80,048,980 elapsed=154.2s

  [9136/20519] intraday_17398.csv.gz  in=320,764,498 out=80,060,770 elapsed=154.2s

  [9137/20519] intraday_17395.csv.gz  in=320,777,933 out=80,074,205 elapsed=154.2s

  [9138/20519] intraday_17397.csv.gz  in=320,789,313 out=80,085,585 elapsed=154.2s

  [9139/20519] intraday_1740.csv.gz  in=320,800,130 out=80,085,585 elapsed=154.2s

  [9140/20519] intraday_17399.csv.gz  in=320,815,518 out=80,100,973 elapsed=154.2s

  [9141/20519] intraday_17401.csv.gz  in=320,826,016 out=80,111,471 elapsed=154.2s

  [9142/20519] intraday_17402.csv.gz  in=320,836,931 out=80,122,386 elapsed=154.2s

  [9143/20519] intraday_17400.csv.gz  in=320,850,562 out=80,136,017 elapsed=154.2s

  [9144/20519] intraday_17403.csv.gz  in=320,863,573 out=80,149,028 elapsed=154.2s

  [9145/20519] intraday_17404.csv.gz  in=320,876,168 out=80,161,623 elapsed=154.2s

  [9146/20519] intraday_17405.csv.gz  in=320,887,819 out=80,173,274 elapsed=154.3s

  [9147/20519] intraday_17406.csv.gz  in=320,900,283 out=80,185,738 elapsed=154.3s

  [9148/20519] intraday_17407.csv.gz  in=320,920,957 out=80,206,412 elapsed=154.3s

  [9149/20519] intraday_17408.csv.gz  in=320,932,214 out=80,217,669 elapsed=154.3s

  [9150/20519] intraday_1741.csv.gz  in=320,944,734 out=80,217,669 elapsed=154.3s

  [9151/20519] intraday_17409.csv.gz  in=320,956,639 out=80,229,574 elapsed=154.3s

  [9152/20519] intraday_17410.csv.gz  in=320,966,851 out=80,239,786 elapsed=154.3s

  [9153/20519] intraday_17411.csv.gz  in=320,981,941 out=80,254,876 elapsed=154.3s

  [9154/20519] intraday_17412.csv.gz  in=320,995,660 out=80,268,595 elapsed=154.3s

  [9155/20519] intraday_17413.csv.gz  in=321,008,761 out=80,281,696 elapsed=154.3s

  [9156/20519] intraday_17414.csv.gz  in=321,021,154 out=80,294,089 elapsed=154.3s

  [9157/20519] intraday_17415.csv.gz  in=321,032,456 out=80,305,391 elapsed=154.3s

  [9158/20519] intraday_17416.csv.gz  in=321,047,608 out=80,320,543 elapsed=154.3s

  [9159/20519] intraday_17417.csv.gz  in=321,061,776 out=80,334,711 elapsed=154.4s

  [9160/20519] intraday_17418.csv.gz  in=321,075,523 out=80,348,458 elapsed=154.4s

  [9161/20519] intraday_1742.csv.gz  in=321,092,203 out=80,348,458 elapsed=154.4s

  [9162/20519] intraday_17419.csv.gz  in=321,103,446 out=80,359,701 elapsed=154.4s

  [9163/20519] intraday_17420.csv.gz  in=321,114,298 out=80,370,553 elapsed=154.4s

  [9164/20519] intraday_17421.csv.gz  in=321,124,338 out=80,380,593 elapsed=154.4s

  [9165/20519] intraday_17423.csv.gz  in=321,136,814 out=80,393,069 elapsed=154.4s

  [9166/20519] intraday_17422.csv.gz  in=321,147,964 out=80,404,219 elapsed=154.4s

  [9167/20519] intraday_17424.csv.gz  in=321,159,760 out=80,416,015 elapsed=154.5s

  [9168/20519] intraday_17425.csv.gz  in=321,173,350 out=80,429,605 elapsed=154.5s

  [9169/20519] intraday_17426.csv.gz  in=321,187,172 out=80,443,427 elapsed=154.5s

  [9170/20519] intraday_17427.csv.gz  in=321,200,496 out=80,456,751 elapsed=154.5s

  [9171/20519] intraday_17428.csv.gz  in=321,211,625 out=80,467,880 elapsed=154.5s

  [9172/20519] intraday_17429.csv.gz  in=321,223,135 out=80,479,390 elapsed=154.5s

  [9173/20519] intraday_1743.csv.gz  in=321,236,728 out=80,479,390 elapsed=154.5s

  [9174/20519] intraday_17430.csv.gz  in=321,249,809 out=80,492,471 elapsed=154.5s

  [9175/20519] intraday_17432.csv.gz  in=321,262,891 out=80,505,553 elapsed=154.6s

  [9176/20519] intraday_17433.csv.gz  in=321,275,320 out=80,517,982 elapsed=154.6s

  [9177/20519] intraday_17431.csv.gz  in=321,288,082 out=80,530,744 elapsed=154.6s

  [9178/20519] intraday_17434.csv.gz  in=321,302,777 out=80,545,439 elapsed=154.6s

  [9179/20519] intraday_17435.csv.gz  in=321,316,235 out=80,558,897 elapsed=154.6s

  [9180/20519] intraday_17436.csv.gz  in=321,328,754 out=80,571,416 elapsed=154.6s

  [9181/20519] intraday_17437.csv.gz  in=321,343,132 out=80,585,794 elapsed=154.6s

  [9182/20519] intraday_17438.csv.gz  in=321,355,162 out=80,597,824 elapsed=154.7s

  [9183/20519] intraday_1744.csv.gz  in=321,367,960 out=80,597,824 elapsed=154.7s

  [9184/20519] intraday_17440.csv.gz  in=321,380,488 out=80,610,352 elapsed=154.7s

  [9185/20519] intraday_17439.csv.gz  in=321,393,075 out=80,622,939 elapsed=154.7s

  [9186/20519] intraday_17441.csv.gz  in=321,405,878 out=80,635,742 elapsed=154.7s

  [9187/20519] intraday_17442.csv.gz  in=321,416,996 out=80,646,860 elapsed=154.7s

  [9188/20519] intraday_17443.csv.gz  in=321,429,597 out=80,659,461 elapsed=154.7s

  [9189/20519] intraday_17444.csv.gz  in=321,441,621 out=80,671,485 elapsed=154.7s

  [9190/20519] intraday_17445.csv.gz  in=321,452,897 out=80,682,761 elapsed=154.8s

  [9191/20519] intraday_17446.csv.gz  in=321,464,694 out=80,694,558 elapsed=154.8s

  [9192/20519] intraday_17448.csv.gz  in=321,477,697 out=80,707,561 elapsed=154.8s

  [9193/20519] intraday_17447.csv.gz  in=321,492,475 out=80,722,339 elapsed=154.8s

  [9194/20519] intraday_17449.csv.gz  in=321,506,129 out=80,735,993 elapsed=154.8s

  [9195/20519] intraday_1745.csv.gz  in=321,519,064 out=80,735,993 elapsed=154.8s

  [9196/20519] intraday_17450.csv.gz  in=321,535,079 out=80,751,720 elapsed=154.9s

  [9197/20519] intraday_17451.csv.gz  in=321,545,806 out=80,762,447 elapsed=154.9s

  [9198/20519] intraday_17452.csv.gz  in=321,556,408 out=80,773,049 elapsed=154.9s

  [9199/20519] intraday_17453.csv.gz  in=321,569,782 out=80,786,423 elapsed=154.9s

  [9200/20519] intraday_17454.csv.gz  in=321,582,876 out=80,799,517 elapsed=154.9s

  [9201/20519] intraday_17455.csv.gz  in=321,594,971 out=80,811,612 elapsed=154.9s

  [9202/20519] intraday_17456.csv.gz  in=321,605,349 out=80,821,990 elapsed=155.0s

  [9203/20519] intraday_17458.csv.gz  in=321,615,991 out=80,832,632 elapsed=155.0s

  [9204/20519] intraday_17459.csv.gz  in=321,630,624 out=80,847,265 elapsed=155.0s

  [9205/20519] intraday_17457.csv.gz  in=321,641,374 out=80,858,015 elapsed=155.0s

  [9206/20519] intraday_1746.csv.gz  in=321,655,206 out=80,858,015 elapsed=155.0s

  [9207/20519] intraday_17460.csv.gz  in=321,667,894 out=80,870,703 elapsed=155.1s

  [9208/20519] intraday_17463.csv.gz  in=321,679,577 out=80,882,386 elapsed=155.1s

  [9209/20519] intraday_17462.csv.gz  in=321,689,516 out=80,892,325 elapsed=155.1s

  [9210/20519] intraday_17461.csv.gz  in=321,704,387 out=80,907,196 elapsed=155.1s

  [9211/20519] intraday_17466.csv.gz  in=321,719,485 out=80,922,294 elapsed=155.2s

  [9212/20519] intraday_17464.csv.gz  in=321,732,973 out=80,935,782 elapsed=155.2s

  [9213/20519] intraday_17465.csv.gz  in=321,747,442 out=80,950,251 elapsed=155.2s

  [9214/20519] intraday_17467.csv.gz  in=321,762,073 out=80,964,882 elapsed=155.2s

  [9215/20519] intraday_17470.csv.gz  in=321,773,351 out=80,976,160 elapsed=155.2s

  [9216/20519] intraday_1747.csv.gz  in=321,786,987 out=80,976,160 elapsed=155.2s

  [9217/20519] intraday_17468.csv.gz  in=321,797,223 out=80,986,396 elapsed=155.2s

  [9218/20519] intraday_17469.csv.gz  in=321,812,386 out=81,001,559 elapsed=155.2s

  [9219/20519] intraday_17471.csv.gz  in=321,825,756 out=81,014,929 elapsed=155.3s

  [9220/20519] intraday_17472.csv.gz  in=321,836,256 out=81,025,429 elapsed=155.3s

  [9221/20519] intraday_17473.csv.gz  in=321,848,722 out=81,037,895 elapsed=155.3s

  [9222/20519] intraday_17474.csv.gz  in=321,861,151 out=81,050,324 elapsed=155.3s

  [9223/20519] intraday_17475.csv.gz  in=321,873,765 out=81,062,938 elapsed=155.3s

  [9224/20519] intraday_17476.csv.gz  in=321,887,022 out=81,076,195 elapsed=155.3s

  [9225/20519] intraday_17478.csv.gz  in=321,901,393 out=81,090,566 elapsed=155.3s

  [9226/20519] intraday_17477.csv.gz  in=321,913,773 out=81,102,946 elapsed=155.3s

  [9227/20519] intraday_1748.csv.gz  in=321,927,765 out=81,102,946 elapsed=155.3s

  [9228/20519] intraday_17479.csv.gz  in=321,939,129 out=81,114,310 elapsed=155.3s

  [9229/20519] intraday_17481.csv.gz  in=321,951,872 out=81,127,053 elapsed=155.3s

  [9230/20519] intraday_17482.csv.gz  in=321,964,242 out=81,139,423 elapsed=155.4s

  [9231/20519] intraday_17480.csv.gz  in=321,975,930 out=81,151,111 elapsed=155.4s

  [9232/20519] intraday_17483.csv.gz  in=321,989,625 out=81,164,806 elapsed=155.4s

  [9233/20519] intraday_17485.csv.gz  in=322,002,827 out=81,177,508 elapsed=155.4s

  [9234/20519] intraday_17484.csv.gz  in=322,016,352 out=81,191,033 elapsed=155.4s

  [9235/20519] intraday_17486.csv.gz  in=322,027,619 out=81,202,300 elapsed=155.4s

  [9236/20519] intraday_17487.csv.gz  in=322,041,192 out=81,215,873 elapsed=155.4s

  [9237/20519] intraday_1749.csv.gz  in=322,060,505 out=81,215,873 elapsed=155.4s

  [9238/20519] intraday_17488.csv.gz  in=322,073,953 out=81,229,321 elapsed=155.5s

  [9239/20519] intraday_17490.csv.gz  in=322,086,978 out=81,242,346 elapsed=155.5s

  [9240/20519] intraday_17489.csv.gz  in=322,099,894 out=81,255,262 elapsed=155.5s

  [9241/20519] intraday_17491.csv.gz  in=322,113,592 out=81,268,960 elapsed=155.5s

  [9242/20519] intraday_17493.csv.gz  in=322,125,648 out=81,281,016 elapsed=155.5s

  [9243/20519] intraday_17492.csv.gz  in=322,140,998 out=81,296,366 elapsed=155.5s

  [9244/20519] intraday_17494.csv.gz  in=322,154,135 out=81,309,503 elapsed=155.5s

  [9245/20519] intraday_17495.csv.gz  in=322,167,975 out=81,323,343 elapsed=155.5s

  [9246/20519] intraday_17496.csv.gz  in=322,189,392 out=81,342,946 elapsed=155.6s

  [9247/20519] intraday_17497.csv.gz  in=322,205,924 out=81,359,478 elapsed=155.6s

  [9248/20519] intraday_17499.csv.gz  in=322,220,917 out=81,374,471 elapsed=155.6s

  [9249/20519] intraday_17498.csv.gz  in=322,240,302 out=81,393,856 elapsed=155.6s

  [9250/20519] intraday_1750.csv.gz  in=322,250,825 out=81,393,856 elapsed=155.6s

  [9251/20519] intraday_17500.csv.gz  in=322,266,575 out=81,409,606 elapsed=155.6s

  [9252/20519] intraday_17501.csv.gz  in=322,279,716 out=81,422,747 elapsed=155.6s

  [9253/20519] intraday_17502.csv.gz  in=322,292,582 out=81,435,613 elapsed=155.6s

  [9254/20519] intraday_17503.csv.gz  in=322,303,175 out=81,446,206 elapsed=155.6s

  [9255/20519] intraday_17504.csv.gz  in=322,316,068 out=81,459,099 elapsed=155.7s

  [9256/20519] intraday_17505.csv.gz  in=322,327,100 out=81,470,131 elapsed=155.7s

  [9257/20519] intraday_17507.csv.gz  in=322,341,704 out=81,484,735 elapsed=155.7s

  [9258/20519] intraday_17506.csv.gz  in=322,355,257 out=81,498,288 elapsed=155.7s

  [9259/20519] intraday_17509.csv.gz  in=322,367,651 out=81,510,682 elapsed=155.7s

  [9260/20519] intraday_1751.csv.gz  in=322,379,211 out=81,510,682 elapsed=155.7s

  [9261/20519] intraday_17508.csv.gz  in=322,393,121 out=81,524,592 elapsed=155.7s

  [9262/20519] intraday_17510.csv.gz  in=322,405,921 out=81,537,392 elapsed=155.8s

  [9263/20519] intraday_17511.csv.gz  in=322,418,564 out=81,550,035 elapsed=155.8s

  [9264/20519] intraday_17513.csv.gz  in=322,431,917 out=81,563,388 elapsed=155.8s

  [9265/20519] intraday_17512.csv.gz  in=322,445,150 out=81,576,621 elapsed=155.8s

  [9266/20519] intraday_17514.csv.gz  in=322,458,882 out=81,590,353 elapsed=155.8s

  [9267/20519] intraday_17515.csv.gz  in=322,473,664 out=81,605,135 elapsed=155.8s

  [9268/20519] intraday_17516.csv.gz  in=322,488,261 out=81,619,732 elapsed=155.8s

  [9269/20519] intraday_17517.csv.gz  in=322,502,686 out=81,634,157 elapsed=155.9s

  [9270/20519] intraday_17518.csv.gz  in=322,514,398 out=81,645,869 elapsed=155.9s

  [9271/20519] intraday_17519.csv.gz  in=322,528,339 out=81,659,810 elapsed=155.9s

  [9272/20519] intraday_17520.csv.gz  in=322,539,938 out=81,671,409 elapsed=155.9s

  [9273/20519] intraday_1752.csv.gz  in=322,551,371 out=81,671,409 elapsed=155.9s

  [9274/20519] intraday_17522.csv.gz  in=322,562,144 out=81,682,182 elapsed=155.9s

  [9275/20519] intraday_17521.csv.gz  in=322,574,467 out=81,694,505 elapsed=155.9s

  [9276/20519] intraday_17523.csv.gz  in=322,583,519 out=81,703,557 elapsed=155.9s

  [9277/20519] intraday_17524.csv.gz  in=322,595,964 out=81,716,002 elapsed=156.0s

  [9278/20519] intraday_17525.csv.gz  in=322,600,209 out=81,720,247 elapsed=156.0s

  [9279/20519] intraday_17526.csv.gz  in=322,615,024 out=81,735,062 elapsed=156.0s

  [9280/20519] intraday_17527.csv.gz  in=322,628,338 out=81,748,376 elapsed=156.0s

  [9281/20519] intraday_17528.csv.gz  in=322,640,104 out=81,760,142 elapsed=156.0s

  [9282/20519] intraday_17529.csv.gz  in=322,651,350 out=81,771,388 elapsed=156.0s

  [9283/20519] intraday_1753.csv.gz  in=322,664,998 out=81,771,388 elapsed=156.1s

  [9284/20519] intraday_17530.csv.gz  in=322,678,107 out=81,784,497 elapsed=156.1s

  [9285/20519] intraday_17531.csv.gz  in=322,691,811 out=81,798,201 elapsed=156.1s

  [9286/20519] intraday_17532.csv.gz  in=322,704,102 out=81,810,492 elapsed=156.1s

  [9287/20519] intraday_17533.csv.gz  in=322,714,083 out=81,820,473 elapsed=156.1s

  [9288/20519] intraday_17534.csv.gz  in=322,728,314 out=81,834,704 elapsed=156.1s

  [9289/20519] intraday_17535.csv.gz  in=322,739,988 out=81,846,378 elapsed=156.1s

  [9290/20519] intraday_17536.csv.gz  in=322,750,279 out=81,856,669 elapsed=156.2s

  [9291/20519] intraday_17538.csv.gz  in=322,762,773 out=81,869,163 elapsed=156.2s

  [9292/20519] intraday_17537.csv.gz  in=322,774,570 out=81,880,960 elapsed=156.2s

  [9293/20519] intraday_17539.csv.gz  in=322,786,136 out=81,892,526 elapsed=156.2s

  [9294/20519] intraday_1754.csv.gz  in=322,796,734 out=81,892,526 elapsed=156.2s

  [9295/20519] intraday_17540.csv.gz  in=322,807,692 out=81,903,484 elapsed=156.2s

  [9296/20519] intraday_17541.csv.gz  in=322,818,096 out=81,913,888 elapsed=156.2s

  [9297/20519] intraday_17543.csv.gz  in=322,830,634 out=81,926,426 elapsed=156.3s

  [9298/20519] intraday_17544.csv.gz  in=322,840,585 out=81,936,377 elapsed=156.3s

  [9299/20519] intraday_17542.csv.gz  in=322,854,948 out=81,950,740 elapsed=156.3s

  [9300/20519] intraday_17545.csv.gz  in=322,865,785 out=81,961,577 elapsed=156.3s

  [9301/20519] intraday_17546.csv.gz  in=322,877,342 out=81,973,134 elapsed=156.3s

  [9302/20519] intraday_17547.csv.gz  in=322,890,384 out=81,986,176 elapsed=156.3s

  [9303/20519] intraday_17548.csv.gz  in=322,901,853 out=81,997,645 elapsed=156.3s

  [9304/20519] intraday_17549.csv.gz  in=322,913,470 out=82,009,262 elapsed=156.4s

  [9305/20519] intraday_1755.csv.gz  in=322,926,023 out=82,009,262 elapsed=156.4s

  [9306/20519] intraday_17550.csv.gz  in=322,938,712 out=82,021,951 elapsed=156.4s

  [9307/20519] intraday_17551.csv.gz  in=322,949,538 out=82,032,777 elapsed=156.4s

  [9308/20519] intraday_17552.csv.gz  in=322,961,679 out=82,044,918 elapsed=156.4s

  [9309/20519] intraday_17553.csv.gz  in=322,972,722 out=82,055,961 elapsed=156.4s

  [9310/20519] intraday_17554.csv.gz  in=322,986,349 out=82,069,588 elapsed=156.4s

  [9311/20519] intraday_17555.csv.gz  in=322,999,785 out=82,083,024 elapsed=156.4s

  [9312/20519] intraday_17556.csv.gz  in=323,011,420 out=82,094,659 elapsed=156.5s

  [9313/20519] intraday_17558.csv.gz  in=323,022,706 out=82,105,945 elapsed=156.5s

  [9314/20519] intraday_17557.csv.gz  in=323,034,820 out=82,118,059 elapsed=156.5s

  [9315/20519] intraday_1756.csv.gz  in=323,046,678 out=82,118,059 elapsed=156.5s

  [9316/20519] intraday_17559.csv.gz  in=323,059,417 out=82,130,798 elapsed=156.5s

  [9317/20519] intraday_17560.csv.gz  in=323,073,117 out=82,144,498 elapsed=156.5s

  [9318/20519] intraday_17561.csv.gz  in=323,095,734 out=82,165,731 elapsed=156.6s

  [9319/20519] intraday_17562.csv.gz  in=323,106,751 out=82,176,748 elapsed=156.6s

  [9320/20519] intraday_17564.csv.gz  in=323,117,557 out=82,187,554 elapsed=156.6s

  [9321/20519] intraday_17563.csv.gz  in=323,127,640 out=82,197,637 elapsed=156.6s

  [9322/20519] intraday_17565.csv.gz  in=323,137,866 out=82,207,863 elapsed=156.6s

  [9323/20519] intraday_17566.csv.gz  in=323,150,106 out=82,220,103 elapsed=156.6s

  [9324/20519] intraday_17567.csv.gz  in=323,161,668 out=82,231,665 elapsed=156.6s

  [9325/20519] intraday_17568.csv.gz  in=323,173,867 out=82,243,864 elapsed=156.6s

  [9326/20519] intraday_17569.csv.gz  in=323,187,495 out=82,257,492 elapsed=156.7s

  [9327/20519] intraday_1757.csv.gz  in=323,198,891 out=82,257,492 elapsed=156.7s

  [9328/20519] intraday_17571.csv.gz  in=323,209,953 out=82,268,554 elapsed=156.7s

  [9329/20519] intraday_17570.csv.gz  in=323,222,189 out=82,280,790 elapsed=156.7s

  [9330/20519] intraday_17573.csv.gz  in=323,234,117 out=82,292,718 elapsed=156.7s

  [9331/20519] intraday_17572.csv.gz  in=323,245,137 out=82,303,738 elapsed=156.7s

  [9332/20519] intraday_17574.csv.gz  in=323,257,391 out=82,315,992 elapsed=156.7s

  [9333/20519] intraday_17576.csv.gz  in=323,273,302 out=82,330,674 elapsed=156.8s

  [9334/20519] intraday_17575.csv.gz  in=323,286,474 out=82,343,846 elapsed=156.8s

  [9335/20519] intraday_17578.csv.gz  in=323,299,925 out=82,357,297 elapsed=156.8s

  [9336/20519] intraday_17579.csv.gz  in=323,310,836 out=82,368,208 elapsed=156.8s

  [9337/20519] intraday_17577.csv.gz  in=323,324,886 out=82,382,258 elapsed=156.8s

  [9338/20519] intraday_1758.csv.gz  in=323,339,557 out=82,382,258 elapsed=156.8s

  [9339/20519] intraday_17581.csv.gz  in=323,350,964 out=82,393,665 elapsed=156.8s

  [9340/20519] intraday_17580.csv.gz  in=323,364,320 out=82,407,021 elapsed=156.8s

  [9341/20519] intraday_17582.csv.gz  in=323,375,919 out=82,418,620 elapsed=156.9s

  [9342/20519] intraday_17584.csv.gz  in=323,388,869 out=82,431,570 elapsed=156.9s

  [9343/20519] intraday_17583.csv.gz  in=323,399,490 out=82,442,191 elapsed=156.9s

  [9344/20519] intraday_17585.csv.gz  in=323,410,203 out=82,452,904 elapsed=156.9s

  [9345/20519] intraday_17586.csv.gz  in=323,421,908 out=82,464,609 elapsed=156.9s

  [9346/20519] intraday_17587.csv.gz  in=323,433,421 out=82,476,122 elapsed=156.9s

  [9347/20519] intraday_17588.csv.gz  in=323,454,295 out=82,494,431 elapsed=156.9s

  [9348/20519] intraday_17589.csv.gz  in=323,466,554 out=82,506,690 elapsed=156.9s

  [9349/20519] intraday_1759.csv.gz  in=323,477,778 out=82,506,690 elapsed=156.9s

  [9350/20519] intraday_17591.csv.gz  in=323,490,569 out=82,519,481 elapsed=157.0s

  [9351/20519] intraday_17590.csv.gz  in=323,508,002 out=82,536,174 elapsed=157.0s

  [9352/20519] intraday_17592.csv.gz  in=323,520,913 out=82,549,085 elapsed=157.0s

  [9353/20519] intraday_17593.csv.gz  in=323,533,597 out=82,561,769 elapsed=157.0s

  [9354/20519] intraday_17594.csv.gz  in=323,544,829 out=82,572,831 elapsed=157.0s

  [9355/20519] intraday_17595.csv.gz  in=323,554,346 out=82,582,348 elapsed=157.0s

  [9356/20519] intraday_17596.csv.gz  in=323,566,865 out=82,594,867 elapsed=157.0s

  [9357/20519] intraday_17597.csv.gz  in=323,583,582 out=82,611,584 elapsed=157.1s

  [9358/20519] intraday_17598.csv.gz  in=323,595,357 out=82,623,359 elapsed=157.1s

  [9359/20519] intraday_1760.csv.gz  in=323,612,564 out=82,623,359 elapsed=157.1s

  [9360/20519] intraday_17599.csv.gz  in=323,622,741 out=82,633,536 elapsed=157.1s

  [9361/20519] intraday_17600.csv.gz  in=323,633,737 out=82,644,532 elapsed=157.1s

  [9362/20519] intraday_17601.csv.gz  in=323,643,748 out=82,654,543 elapsed=157.1s

  [9363/20519] intraday_17602.csv.gz  in=323,656,991 out=82,667,786 elapsed=157.2s

  [9364/20519] intraday_17604.csv.gz  in=323,669,598 out=82,680,393 elapsed=157.2s

  [9365/20519] intraday_17603.csv.gz  in=323,682,246 out=82,693,041 elapsed=157.2s

  [9366/20519] intraday_17605.csv.gz  in=323,692,073 out=82,702,868 elapsed=157.2s

  [9367/20519] intraday_17606.csv.gz  in=323,703,077 out=82,713,872 elapsed=157.2s

  [9368/20519] intraday_17607.csv.gz  in=323,715,931 out=82,726,726 elapsed=157.2s

  [9369/20519] intraday_17608.csv.gz  in=323,730,147 out=82,740,942 elapsed=157.2s

  [9370/20519] intraday_1761.csv.gz  in=323,744,150 out=82,740,942 elapsed=157.3s

  [9371/20519] intraday_17609.csv.gz  in=323,757,537 out=82,754,329 elapsed=157.3s

  [9372/20519] intraday_17610.csv.gz  in=323,770,844 out=82,767,636 elapsed=157.3s

  [9373/20519] intraday_17611.csv.gz  in=323,781,520 out=82,778,312 elapsed=157.3s

  [9374/20519] intraday_17612.csv.gz  in=323,796,146 out=82,792,938 elapsed=157.3s

  [9375/20519] intraday_17613.csv.gz  in=323,806,134 out=82,802,926 elapsed=157.3s

  [9376/20519] intraday_17614.csv.gz  in=323,818,528 out=82,815,320 elapsed=157.3s

  [9377/20519] intraday_17615.csv.gz  in=323,828,708 out=82,825,500 elapsed=157.3s

  [9378/20519] intraday_17616.csv.gz  in=323,840,364 out=82,837,156 elapsed=157.3s

  [9379/20519] intraday_17617.csv.gz  in=323,852,563 out=82,849,355 elapsed=157.4s

  [9380/20519] intraday_17619.csv.gz  in=323,865,621 out=82,862,413 elapsed=157.4s

  [9381/20519] intraday_1762.csv.gz  in=323,879,120 out=82,862,413 elapsed=157.4s

  [9382/20519] intraday_17620.csv.gz  in=323,890,940 out=82,874,233 elapsed=157.4s

  [9383/20519] intraday_17618.csv.gz  in=323,909,257 out=82,889,920 elapsed=157.4s

  [9384/20519] intraday_17621.csv.gz  in=323,922,772 out=82,903,435 elapsed=157.4s

  [9385/20519] intraday_17622.csv.gz  in=323,934,646 out=82,915,309 elapsed=157.4s

  [9386/20519] intraday_17623.csv.gz  in=323,944,990 out=82,925,653 elapsed=157.4s

  [9387/20519] intraday_17624.csv.gz  in=323,956,932 out=82,937,595 elapsed=157.4s

  [9388/20519] intraday_17625.csv.gz  in=323,968,670 out=82,949,333 elapsed=157.5s

  [9389/20519] intraday_17626.csv.gz  in=323,983,577 out=82,963,005 elapsed=157.5s

  [9390/20519] intraday_17628.csv.gz  in=323,995,043 out=82,974,471 elapsed=157.5s

  [9391/20519] intraday_17627.csv.gz  in=324,008,105 out=82,987,533 elapsed=157.5s

  [9392/20519] intraday_17629.csv.gz  in=324,019,096 out=82,998,524 elapsed=157.5s

  [9393/20519] intraday_1763.csv.gz  in=324,053,698 out=82,998,524 elapsed=157.5s

  [9394/20519] intraday_17630.csv.gz  in=324,066,838 out=83,011,664 elapsed=157.6s

  [9395/20519] intraday_17632.csv.gz  in=324,078,477 out=83,023,303 elapsed=157.6s

  [9396/20519] intraday_17633.csv.gz  in=324,090,531 out=83,035,357 elapsed=157.6s

  [9397/20519] intraday_17634.csv.gz  in=324,103,852 out=83,048,678 elapsed=157.6s

  [9398/20519] intraday_17631.csv.gz  in=324,115,719 out=83,060,545 elapsed=157.6s

  [9399/20519] intraday_17635.csv.gz  in=324,130,194 out=83,075,020 elapsed=157.6s

  [9400/20519] intraday_17636.csv.gz  in=324,142,233 out=83,087,059 elapsed=157.6s

  [9401/20519] intraday_17637.csv.gz  in=324,154,490 out=83,099,316 elapsed=157.7s

  [9402/20519] intraday_17638.csv.gz  in=324,166,378 out=83,111,204 elapsed=157.7s

  [9403/20519] intraday_1764.csv.gz  in=324,180,231 out=83,111,204 elapsed=157.7s

  [9404/20519] intraday_17639.csv.gz  in=324,193,547 out=83,124,520 elapsed=157.7s

  [9405/20519] intraday_17640.csv.gz  in=324,207,136 out=83,138,109 elapsed=157.7s

  [9406/20519] intraday_17642.csv.gz  in=324,221,312 out=83,152,285 elapsed=157.7s

  [9407/20519] intraday_17643.csv.gz  in=324,236,167 out=83,167,140 elapsed=157.7s

  [9408/20519] intraday_17641.csv.gz  in=324,253,157 out=83,184,130 elapsed=157.7s

  [9409/20519] intraday_17644.csv.gz  in=324,265,014 out=83,195,987 elapsed=157.7s

  [9410/20519] intraday_17645.csv.gz  in=324,279,802 out=83,210,566 elapsed=157.8s

  [9411/20519] intraday_17647.csv.gz  in=324,293,285 out=83,224,049 elapsed=157.8s

  [9412/20519] intraday_17646.csv.gz  in=324,303,848 out=83,234,612 elapsed=157.8s

  [9413/20519] intraday_17648.csv.gz  in=324,316,128 out=83,246,892 elapsed=157.8s

  [9414/20519] intraday_1765.csv.gz  in=324,328,367 out=83,246,892 elapsed=157.8s

  [9415/20519] intraday_17649.csv.gz  in=324,341,121 out=83,259,646 elapsed=157.8s

  [9416/20519] intraday_17652.csv.gz  in=324,352,903 out=83,271,428 elapsed=157.9s

  [9417/20519] intraday_17653.csv.gz  in=324,363,562 out=83,282,087 elapsed=157.9s

  [9418/20519] intraday_17650.csv.gz  in=324,375,583 out=83,294,108 elapsed=157.9s

  [9419/20519] intraday_17651.csv.gz  in=324,389,784 out=83,308,309 elapsed=157.9s

  [9420/20519] intraday_17654.csv.gz  in=324,401,673 out=83,320,198 elapsed=157.9s

  [9421/20519] intraday_17656.csv.gz  in=324,413,944 out=83,332,290 elapsed=157.9s

  [9422/20519] intraday_17655.csv.gz  in=324,426,515 out=83,344,861 elapsed=157.9s

  [9423/20519] intraday_17657.csv.gz  in=324,440,259 out=83,358,605 elapsed=157.9s

  [9424/20519] intraday_1766.csv.gz  in=324,453,192 out=83,358,605 elapsed=158.0s

  [9425/20519] intraday_17658.csv.gz  in=324,466,480 out=83,371,893 elapsed=158.0s

  [9426/20519] intraday_17659.csv.gz  in=324,478,987 out=83,384,400 elapsed=158.0s

  [9427/20519] intraday_17661.csv.gz  in=324,488,800 out=83,394,213 elapsed=158.0s

  [9428/20519] intraday_17662.csv.gz  in=324,500,974 out=83,406,387 elapsed=158.0s

  [9429/20519] intraday_17660.csv.gz  in=324,516,384 out=83,421,797 elapsed=158.0s

  [9430/20519] intraday_17663.csv.gz  in=324,530,047 out=83,435,460 elapsed=158.1s

  [9431/20519] intraday_17664.csv.gz  in=324,540,285 out=83,445,698 elapsed=158.1s

  [9432/20519] intraday_17665.csv.gz  in=324,551,473 out=83,456,886 elapsed=158.1s

  [9433/20519] intraday_17667.csv.gz  in=324,561,696 out=83,467,109 elapsed=158.1s

  [9434/20519] intraday_17668.csv.gz  in=324,569,798 out=83,475,211 elapsed=158.1s

  [9435/20519] intraday_17669.csv.gz  in=324,570,716 out=83,476,129 elapsed=158.1s

  [9436/20519] intraday_17666.csv.gz  in=324,578,913 out=83,484,326 elapsed=158.1s

  [9437/20519] intraday_17670.csv.gz  in=324,579,248 out=83,484,661 elapsed=158.2s

  [9438/20519] intraday_17671.csv.gz  in=324,579,615 out=83,485,028 elapsed=158.2s

  [9439/20519] intraday_17672.csv.gz  in=324,580,211 out=83,485,624 elapsed=158.2s

  [9440/20519] intraday_17674.csv.gz  in=324,580,996 out=83,486,409 elapsed=158.2s

  [9441/20519] intraday_17673.csv.gz  in=324,581,505 out=83,486,918 elapsed=158.2s

  [9442/20519] intraday_1767.csv.gz  in=324,592,293 out=83,486,918 elapsed=158.2s

  [9443/20519] intraday_17675.csv.gz  in=324,592,822 out=83,487,447 elapsed=158.2s

  [9444/20519] intraday_17676.csv.gz  in=324,593,200 out=83,487,825 elapsed=158.2s

  [9445/20519] intraday_17677.csv.gz  in=324,593,815 out=83,488,440 elapsed=158.2s

  [9446/20519] intraday_17679.csv.gz  in=324,594,186 out=83,488,811 elapsed=158.2s

  [9447/20519] intraday_17680.csv.gz  in=324,594,785 out=83,489,410 elapsed=158.2s

  [9448/20519] intraday_17678.csv.gz  in=324,595,143 out=83,489,768 elapsed=158.2s

  [9449/20519] intraday_17681.csv.gz  in=324,596,179 out=83,490,804 elapsed=158.2s

  [9450/20519] intraday_17682.csv.gz  in=324,596,547 out=83,491,172 elapsed=158.2s

  [9451/20519] intraday_17683.csv.gz  in=324,596,994 out=83,491,619 elapsed=158.2s

  [9452/20519] intraday_1768.csv.gz  in=324,610,309 out=83,491,619 elapsed=158.2s

  [9453/20519] intraday_17684.csv.gz  in=324,610,695 out=83,492,005 elapsed=158.2s

  [9454/20519] intraday_17685.csv.gz  in=324,611,390 out=83,492,700 elapsed=158.2s

  [9455/20519] intraday_17686.csv.gz  in=324,611,997 out=83,493,307 elapsed=158.2s

  [9456/20519] intraday_17687.csv.gz  in=324,612,379 out=83,493,689 elapsed=158.3s

  [9457/20519] intraday_17688.csv.gz  in=324,612,596 out=83,493,906 elapsed=158.3s

  [9458/20519] intraday_17691.csv.gz  in=324,612,901 out=83,494,211 elapsed=158.3s

  [9459/20519] intraday_17689.csv.gz  in=324,613,340 out=83,494,650 elapsed=158.3s

  [9460/20519] intraday_17692.csv.gz  in=324,613,797 out=83,495,107 elapsed=158.3s

  [9461/20519] intraday_17693.csv.gz  in=324,613,890 out=83,495,200 elapsed=158.3s

  [9462/20519] intraday_17690.csv.gz  in=324,614,080 out=83,495,390 elapsed=158.3s

  [9463/20519] intraday_17694.csv.gz  in=324,614,433 out=83,495,743 elapsed=158.3s

  [9464/20519] intraday_17696.csv.gz  in=324,614,860 out=83,496,170 elapsed=158.3s

  [9465/20519] intraday_1769.csv.gz  in=324,627,189 out=83,496,170 elapsed=158.3s

  [9466/20519] intraday_17695.csv.gz  in=324,627,639 out=83,496,620 elapsed=158.3s

  [9467/20519] intraday_17697.csv.gz  in=324,628,549 out=83,497,530 elapsed=158.3s

  [9468/20519] intraday_17698.csv.gz  in=324,629,503 out=83,498,484 elapsed=158.3s

  [9469/20519] intraday_17700.csv.gz  in=324,629,562 out=83,498,543 elapsed=158.3s

  [9470/20519] intraday_17699.csv.gz  in=324,630,275 out=83,499,256 elapsed=158.3s

  [9471/20519] intraday_17701.csv.gz  in=324,630,686 out=83,499,667 elapsed=158.3s

  [9472/20519] intraday_17702.csv.gz  in=324,631,008 out=83,499,989 elapsed=158.3s

  [9473/20519] intraday_17703.csv.gz  in=324,631,202 out=83,500,183 elapsed=158.3s

  [9474/20519] intraday_17704.csv.gz  in=324,631,428 out=83,500,409 elapsed=158.4s

  [9475/20519] intraday_1770.csv.gz  in=324,649,549 out=83,500,409 elapsed=158.4s

  [9476/20519] intraday_17705.csv.gz  in=324,649,856 out=83,500,716 elapsed=158.4s

  [9477/20519] intraday_17706.csv.gz  in=324,650,049 out=83,500,909 elapsed=158.4s

  [9478/20519] intraday_17707.csv.gz  in=324,650,151 out=83,501,011 elapsed=158.4s

  [9479/20519] intraday_17708.csv.gz  in=324,650,318 out=83,501,178 elapsed=158.4s

  [9480/20519] intraday_17709.csv.gz  in=324,650,513 out=83,501,373 elapsed=158.4s

  [9481/20519] intraday_17710.csv.gz  in=324,650,681 out=83,501,541 elapsed=158.4s

  [9482/20519] intraday_17711.csv.gz  in=324,651,201 out=83,502,061 elapsed=158.4s

  [9483/20519] intraday_1771.csv.gz  in=324,663,613 out=83,502,061 elapsed=158.4s

  [9484/20519] intraday_17712.csv.gz  in=324,663,880 out=83,502,328 elapsed=158.4s

  [9485/20519] intraday_17713.csv.gz  in=324,664,183 out=83,502,631 elapsed=158.4s

  [9486/20519] intraday_17714.csv.gz  in=324,664,289 out=83,502,737 elapsed=158.4s

  [9487/20519] intraday_17717.csv.gz  in=324,664,623 out=83,503,071 elapsed=158.4s

  [9488/20519] intraday_17716.csv.gz  in=324,664,781 out=83,503,229 elapsed=158.4s

  [9489/20519] intraday_17715.csv.gz  in=324,669,589 out=83,506,917 elapsed=158.4s

  [9490/20519] intraday_17718.csv.gz  in=324,669,957 out=83,507,285 elapsed=158.4s

  [9491/20519] intraday_17719.csv.gz  in=324,670,840 out=83,508,168 elapsed=158.4s

  [9492/20519] intraday_17722.csv.gz  in=324,671,654 out=83,508,982 elapsed=158.5s

  [9493/20519] intraday_17720.csv.gz  in=324,672,118 out=83,509,446 elapsed=158.5s

  [9494/20519] intraday_17721.csv.gz  in=324,673,199 out=83,510,527 elapsed=158.5s

  [9495/20519] intraday_1772.csv.gz  in=324,686,173 out=83,510,527 elapsed=158.5s

  [9496/20519] intraday_17725.csv.gz  in=324,686,359 out=83,510,713 elapsed=158.5s

  [9497/20519] intraday_17724.csv.gz  in=324,686,787 out=83,511,077 elapsed=158.5s

  [9498/20519] intraday_17726.csv.gz  in=324,687,198 out=83,511,488 elapsed=158.5s

  [9499/20519] intraday_17727.csv.gz  in=324,687,445 out=83,511,735 elapsed=158.5s

  [9500/20519] intraday_17723.csv.gz  in=324,688,021 out=83,512,311 elapsed=158.5s

  [9501/20519] intraday_17728.csv.gz  in=324,688,558 out=83,512,848 elapsed=158.5s

  [9502/20519] intraday_17729.csv.gz  in=324,688,727 out=83,513,017 elapsed=158.5s

  [9503/20519] intraday_17730.csv.gz  in=324,688,884 out=83,513,174 elapsed=158.5s

  [9504/20519] intraday_17731.csv.gz  in=324,688,984 out=83,513,274 elapsed=158.5s

  [9505/20519] intraday_17732.csv.gz  in=324,689,837 out=83,514,127 elapsed=158.5s

  [9506/20519] intraday_17734.csv.gz  in=324,690,134 out=83,514,424 elapsed=158.5s

  [9507/20519] intraday_17735.csv.gz  in=324,690,354 out=83,514,644 elapsed=158.5s

  [9508/20519] intraday_17733.csv.gz  in=324,691,364 out=83,515,654 elapsed=158.5s

  [9509/20519] intraday_1773.csv.gz  in=324,703,513 out=83,515,654 elapsed=158.5s

  [9510/20519] intraday_17737.csv.gz  in=324,703,775 out=83,515,916 elapsed=158.6s

  [9511/20519] intraday_17736.csv.gz  in=324,704,279 out=83,516,420 elapsed=158.6s

  [9512/20519] intraday_17739.csv.gz  in=324,704,869 out=83,517,010 elapsed=158.6s

  [9513/20519] intraday_17738.csv.gz  in=324,705,267 out=83,517,408 elapsed=158.6s

  [9514/20519] intraday_17740.csv.gz  in=324,705,514 out=83,517,655 elapsed=158.6s

  [9515/20519] intraday_17742.csv.gz  in=324,706,076 out=83,518,217 elapsed=158.6s

  [9516/20519] intraday_17741.csv.gz  in=324,706,364 out=83,518,505 elapsed=158.6s

  [9517/20519] intraday_17743.csv.gz  in=324,706,476 out=83,518,617 elapsed=158.6s

  [9518/20519] intraday_17744.csv.gz  in=324,706,822 out=83,518,963 elapsed=158.6s

  [9519/20519] intraday_1774.csv.gz  in=324,719,809 out=83,518,963 elapsed=158.6s

  [9520/20519] intraday_17746.csv.gz  in=324,720,179 out=83,519,333 elapsed=158.6s

  [9521/20519] intraday_17745.csv.gz  in=324,720,455 out=83,519,609 elapsed=158.6s

  [9522/20519] intraday_17747.csv.gz  in=324,721,232 out=83,520,386 elapsed=158.6s

  [9523/20519] intraday_17749.csv.gz  in=324,721,576 out=83,520,730 elapsed=158.6s

  [9524/20519] intraday_17748.csv.gz  in=324,721,632 out=83,520,786 elapsed=158.6s

  [9525/20519] intraday_17752.csv.gz  in=324,722,330 out=83,521,484 elapsed=158.6s

  [9526/20519] intraday_17750.csv.gz  in=324,724,297 out=83,523,451 elapsed=158.7s

  [9527/20519] intraday_17751.csv.gz  in=324,725,540 out=83,524,694 elapsed=158.7s

  [9528/20519] intraday_1775.csv.gz  in=324,735,897 out=83,524,694 elapsed=158.7s

  [9529/20519] intraday_17753.csv.gz  in=324,736,493 out=83,525,290 elapsed=158.7s

  [9530/20519] intraday_17754.csv.gz  in=324,736,914 out=83,525,711 elapsed=158.7s

  [9531/20519] intraday_17757.csv.gz  in=324,737,097 out=83,525,894 elapsed=158.7s

  [9532/20519] intraday_17756.csv.gz  in=324,738,036 out=83,526,833 elapsed=158.7s

  [9533/20519] intraday_17758.csv.gz  in=324,738,246 out=83,527,043 elapsed=158.7s

  [9534/20519] intraday_17755.csv.gz  in=324,738,598 out=83,527,395 elapsed=158.7s

  [9535/20519] intraday_17759.csv.gz  in=324,739,185 out=83,527,982 elapsed=158.7s

  [9536/20519] intraday_17760.csv.gz  in=324,739,753 out=83,528,550 elapsed=158.7s

  [9537/20519] intraday_17761.csv.gz  in=324,739,955 out=83,528,752 elapsed=158.7s

  [9538/20519] intraday_17762.csv.gz  in=324,740,228 out=83,529,025 elapsed=158.7s

  [9539/20519] intraday_17763.csv.gz  in=324,740,487 out=83,529,284 elapsed=158.7s

  [9540/20519] intraday_17764.csv.gz  in=324,740,702 out=83,529,499 elapsed=158.7s

  [9541/20519] intraday_1776.csv.gz  in=324,757,515 out=83,529,499 elapsed=158.7s

  [9542/20519] intraday_17766.csv.gz  in=324,757,798 out=83,529,782 elapsed=158.7s

  [9543/20519] intraday_17765.csv.gz  in=324,758,394 out=83,530,378 elapsed=158.7s

  [9544/20519] intraday_17767.csv.gz  in=324,758,536 out=83,530,520 elapsed=158.7s

  [9545/20519] intraday_17768.csv.gz  in=324,758,763 out=83,530,747 elapsed=158.8s

  [9546/20519] intraday_17769.csv.gz  in=324,759,994 out=83,531,978 elapsed=158.8s

  [9547/20519] intraday_17771.csv.gz  in=324,760,474 out=83,532,458 elapsed=158.8s

  [9548/20519] intraday_17770.csv.gz  in=324,761,467 out=83,533,451 elapsed=158.8s

  [9549/20519] intraday_17772.csv.gz  in=324,761,782 out=83,533,766 elapsed=158.8s

  [9550/20519] intraday_17773.csv.gz  in=324,762,506 out=83,534,490 elapsed=158.8s

  [9551/20519] intraday_17774.csv.gz  in=324,762,610 out=83,534,594 elapsed=158.8s

  [9552/20519] intraday_17775.csv.gz  in=324,762,756 out=83,534,740 elapsed=158.8s

  [9553/20519] intraday_1777.csv.gz  in=324,776,697 out=83,534,740 elapsed=158.8s

  [9554/20519] intraday_17776.csv.gz  in=324,777,072 out=83,535,115 elapsed=158.8s

  [9555/20519] intraday_17777.csv.gz  in=324,777,549 out=83,535,592 elapsed=158.8s

  [9556/20519] intraday_17779.csv.gz  in=324,778,190 out=83,536,233 elapsed=158.8s

  [9557/20519] intraday_17778.csv.gz  in=324,778,765 out=83,536,808 elapsed=158.8s

  [9558/20519] intraday_17781.csv.gz  in=324,779,710 out=83,537,753 elapsed=158.8s

  [9559/20519] intraday_17780.csv.gz  in=324,780,776 out=83,538,819 elapsed=158.8s

  [9560/20519] intraday_17782.csv.gz  in=324,781,959 out=83,540,002 elapsed=158.8s

  [9561/20519] intraday_17783.csv.gz  in=324,783,390 out=83,541,433 elapsed=158.8s

  [9562/20519] intraday_17784.csv.gz  in=324,783,889 out=83,541,932 elapsed=158.8s

  [9563/20519] intraday_1778.csv.gz  in=324,799,309 out=83,541,932 elapsed=158.8s

  [9564/20519] intraday_17785.csv.gz  in=324,800,516 out=83,543,139 elapsed=158.9s

  [9565/20519] intraday_17787.csv.gz  in=324,800,969 out=83,543,592 elapsed=158.9s

  [9566/20519] intraday_17786.csv.gz  in=324,801,458 out=83,544,081 elapsed=158.9s

  [9567/20519] intraday_17788.csv.gz  in=324,801,577 out=83,544,200 elapsed=158.9s

  [9568/20519] intraday_17789.csv.gz  in=324,802,300 out=83,544,923 elapsed=158.9s

  [9569/20519] intraday_17790.csv.gz  in=324,802,360 out=83,544,983 elapsed=158.9s

  [9570/20519] intraday_17791.csv.gz  in=324,802,957 out=83,545,580 elapsed=158.9s

  [9571/20519] intraday_17792.csv.gz  in=324,803,278 out=83,545,901 elapsed=158.9s

  [9572/20519] intraday_17793.csv.gz  in=324,804,262 out=83,546,885 elapsed=158.9s

  [9573/20519] intraday_17795.csv.gz  in=324,804,711 out=83,547,334 elapsed=158.9s

  [9574/20519] intraday_1779.csv.gz  in=324,824,591 out=83,547,334 elapsed=158.9s

  [9575/20519] intraday_17796.csv.gz  in=324,825,075 out=83,547,818 elapsed=158.9s

  [9576/20519] intraday_17797.csv.gz  in=324,826,030 out=83,548,773 elapsed=158.9s

  [9577/20519] intraday_17794.csv.gz  in=324,826,390 out=83,549,133 elapsed=158.9s

  [9578/20519] intraday_17798.csv.gz  in=324,826,714 out=83,549,457 elapsed=158.9s

  [9579/20519] intraday_17799.csv.gz  in=324,826,922 out=83,549,665 elapsed=158.9s

  [9580/20519] intraday_17801.csv.gz  in=324,827,424 out=83,550,167 elapsed=158.9s

  [9581/20519] intraday_17802.csv.gz  in=324,827,934 out=83,550,677 elapsed=158.9s

  [9582/20519] intraday_17800.csv.gz  in=324,828,128 out=83,550,854 elapsed=159.0s

  [9583/20519] intraday_17803.csv.gz  in=324,828,434 out=83,551,160 elapsed=159.0s

  [9584/20519] intraday_17804.csv.gz  in=324,828,788 out=83,551,514 elapsed=159.0s

  [9585/20519] intraday_1780.csv.gz  in=324,842,657 out=83,551,514 elapsed=159.0s

  [9586/20519] intraday_17805.csv.gz  in=324,843,000 out=83,551,857 elapsed=159.0s

  [9587/20519] intraday_17807.csv.gz  in=324,843,405 out=83,552,262 elapsed=159.0s

  [9588/20519] intraday_17808.csv.gz  in=324,843,942 out=83,552,799 elapsed=159.0s

  [9589/20519] intraday_17809.csv.gz  in=324,844,263 out=83,553,120 elapsed=159.0s

  [9590/20519] intraday_17806.csv.gz  in=324,844,528 out=83,553,385 elapsed=159.0s

  [9591/20519] intraday_17810.csv.gz  in=324,844,773 out=83,553,630 elapsed=159.0s

  [9592/20519] intraday_1781.csv.gz  in=324,858,228 out=83,553,630 elapsed=159.0s

  [9593/20519] intraday_17812.csv.gz  in=324,872,109 out=83,567,511 elapsed=159.1s

  [9594/20519] intraday_17814.csv.gz  in=324,883,438 out=83,578,840 elapsed=159.1s

  [9595/20519] intraday_17813.csv.gz  in=324,896,852 out=83,592,254 elapsed=159.1s

  [9596/20519] intraday_17811.csv.gz  in=324,912,473 out=83,607,875 elapsed=159.1s

  [9597/20519] intraday_17815.csv.gz  in=324,925,290 out=83,620,692 elapsed=159.1s

  [9598/20519] intraday_17816.csv.gz  in=324,939,751 out=83,635,153 elapsed=159.1s

  [9599/20519] intraday_17818.csv.gz  in=324,950,634 out=83,646,036 elapsed=159.2s

  [9600/20519] intraday_17817.csv.gz  in=324,963,889 out=83,659,291 elapsed=159.2s

  [9601/20519] intraday_17819.csv.gz  in=324,977,950 out=83,673,352 elapsed=159.2s

  [9602/20519] intraday_1782.csv.gz  in=324,996,461 out=83,673,352 elapsed=159.2s

  [9603/20519] intraday_17821.csv.gz  in=325,006,007 out=83,682,898 elapsed=159.2s

  [9604/20519] intraday_17820.csv.gz  in=325,020,217 out=83,697,108 elapsed=159.2s

  [9605/20519] intraday_17822.csv.gz  in=325,032,311 out=83,709,202 elapsed=159.2s

  [9606/20519] intraday_17823.csv.gz  in=325,046,672 out=83,723,563 elapsed=159.3s

  [9607/20519] intraday_17825.csv.gz  in=325,057,573 out=83,734,464 elapsed=159.3s

  [9608/20519] intraday_17824.csv.gz  in=325,069,618 out=83,746,509 elapsed=159.3s

  [9609/20519] intraday_17827.csv.gz  in=325,084,007 out=83,760,898 elapsed=159.3s

  [9610/20519] intraday_17828.csv.gz  in=325,097,572 out=83,774,463 elapsed=159.3s

  [9611/20519] intraday_17826.csv.gz  in=325,109,050 out=83,785,941 elapsed=159.3s

  [9612/20519] intraday_17829.csv.gz  in=325,120,309 out=83,797,200 elapsed=159.3s

  [9613/20519] intraday_1783.csv.gz  in=325,133,523 out=83,797,200 elapsed=159.3s

  [9614/20519] intraday_17831.csv.gz  in=325,145,928 out=83,809,605 elapsed=159.4s

  [9615/20519] intraday_17830.csv.gz  in=325,156,829 out=83,820,506 elapsed=159.4s

  [9616/20519] intraday_17832.csv.gz  in=325,169,863 out=83,833,540 elapsed=159.4s

  [9617/20519] intraday_17833.csv.gz  in=325,182,409 out=83,846,086 elapsed=159.4s

  [9618/20519] intraday_17834.csv.gz  in=325,193,553 out=83,857,230 elapsed=159.4s

  [9619/20519] intraday_17835.csv.gz  in=325,206,133 out=83,869,810 elapsed=159.5s

  [9620/20519] intraday_17836.csv.gz  in=325,217,137 out=83,880,814 elapsed=159.5s

  [9621/20519] intraday_17838.csv.gz  in=325,228,230 out=83,891,907 elapsed=159.5s

  [9622/20519] intraday_17837.csv.gz  in=325,241,318 out=83,904,995 elapsed=159.5s

  [9623/20519] intraday_17839.csv.gz  in=325,255,141 out=83,918,818 elapsed=159.5s

  [9624/20519] intraday_1784.csv.gz  in=325,271,480 out=83,918,818 elapsed=159.5s

  [9625/20519] intraday_17840.csv.gz  in=325,285,828 out=83,933,166 elapsed=159.6s

  [9626/20519] intraday_17841.csv.gz  in=325,298,579 out=83,945,917 elapsed=159.6s

  [9627/20519] intraday_17842.csv.gz  in=325,310,302 out=83,957,640 elapsed=159.6s

  [9628/20519] intraday_17843.csv.gz  in=325,321,547 out=83,968,885 elapsed=159.6s

  [9629/20519] intraday_17844.csv.gz  in=325,334,449 out=83,981,787 elapsed=159.6s

  [9630/20519] intraday_17847.csv.gz  in=325,348,675 out=83,995,494 elapsed=159.6s

  [9631/20519] intraday_17846.csv.gz  in=325,361,206 out=84,008,025 elapsed=159.6s

  [9632/20519] intraday_17848.csv.gz  in=325,372,217 out=84,019,036 elapsed=159.6s

  [9633/20519] intraday_17845.csv.gz  in=325,407,093 out=84,049,459 elapsed=159.7s

  [9634/20519] intraday_1785.csv.gz  in=325,420,389 out=84,049,459 elapsed=159.7s

  [9635/20519] intraday_17849.csv.gz  in=325,431,099 out=84,060,169 elapsed=159.7s

  [9636/20519] intraday_17850.csv.gz  in=325,441,867 out=84,070,937 elapsed=159.7s

  [9637/20519] intraday_17852.csv.gz  in=325,453,171 out=84,082,241 elapsed=159.7s

  [9638/20519] intraday_17853.csv.gz  in=325,466,287 out=84,095,357 elapsed=159.7s

  [9639/20519] intraday_17854.csv.gz  in=325,481,354 out=84,110,424 elapsed=159.7s

  [9640/20519] intraday_17855.csv.gz  in=325,493,539 out=84,122,609 elapsed=159.7s

  [9641/20519] intraday_17856.csv.gz  in=325,505,745 out=84,134,815 elapsed=159.7s

  [9642/20519] intraday_17851.csv.gz  in=325,518,344 out=84,147,414 elapsed=159.7s

  [9643/20519] intraday_17857.csv.gz  in=325,530,272 out=84,159,342 elapsed=159.7s

  [9644/20519] intraday_17858.csv.gz  in=325,542,516 out=84,171,586 elapsed=159.8s

  [9645/20519] intraday_1786.csv.gz  in=325,554,636 out=84,171,586 elapsed=159.8s

  [9646/20519] intraday_17859.csv.gz  in=325,566,915 out=84,183,865 elapsed=159.8s

  [9647/20519] intraday_17860.csv.gz  in=325,580,202 out=84,197,152 elapsed=159.8s

  [9648/20519] intraday_17861.csv.gz  in=325,590,966 out=84,207,916 elapsed=159.8s

  [9649/20519] intraday_17862.csv.gz  in=325,605,661 out=84,222,611 elapsed=159.8s

  [9650/20519] intraday_17864.csv.gz  in=325,617,496 out=84,234,446 elapsed=159.8s

  [9651/20519] intraday_17863.csv.gz  in=325,631,922 out=84,248,872 elapsed=159.8s

  [9652/20519] intraday_17865.csv.gz  in=325,647,756 out=84,264,706 elapsed=159.9s

  [9653/20519] intraday_17867.csv.gz  in=325,658,416 out=84,275,366 elapsed=159.9s

  [9654/20519] intraday_17866.csv.gz  in=325,670,711 out=84,287,661 elapsed=159.9s

  [9655/20519] intraday_17868.csv.gz  in=325,682,760 out=84,299,710 elapsed=159.9s

  [9656/20519] intraday_1787.csv.gz  in=325,695,837 out=84,299,710 elapsed=159.9s

  [9657/20519] intraday_17869.csv.gz  in=325,708,516 out=84,312,389 elapsed=159.9s

  [9658/20519] intraday_17870.csv.gz  in=325,719,352 out=84,323,225 elapsed=159.9s

  [9659/20519] intraday_17872.csv.gz  in=325,730,206 out=84,334,079 elapsed=159.9s

  [9660/20519] intraday_17873.csv.gz  in=325,741,423 out=84,345,296 elapsed=160.0s

  [9661/20519] intraday_17871.csv.gz  in=325,754,723 out=84,358,596 elapsed=160.0s

  [9662/20519] intraday_17875.csv.gz  in=325,768,888 out=84,372,761 elapsed=160.0s

  [9663/20519] intraday_17874.csv.gz  in=325,780,273 out=84,384,146 elapsed=160.0s

  [9664/20519] intraday_17876.csv.gz  in=325,792,991 out=84,396,864 elapsed=160.0s

  [9665/20519] intraday_17878.csv.gz  in=325,806,469 out=84,410,342 elapsed=160.0s

  [9666/20519] intraday_17879.csv.gz  in=325,817,011 out=84,420,884 elapsed=160.0s

  [9667/20519] intraday_17877.csv.gz  in=325,831,557 out=84,435,430 elapsed=160.0s

  [9668/20519] intraday_1788.csv.gz  in=325,841,557 out=84,435,430 elapsed=160.1s

  [9669/20519] intraday_17880.csv.gz  in=325,850,744 out=84,444,617 elapsed=160.1s

  [9670/20519] intraday_17882.csv.gz  in=325,862,937 out=84,456,810 elapsed=160.1s

  [9671/20519] intraday_17881.csv.gz  in=325,878,150 out=84,472,023 elapsed=160.1s

  [9672/20519] intraday_17884.csv.gz  in=325,888,466 out=84,482,339 elapsed=160.1s

  [9673/20519] intraday_17885.csv.gz  in=325,899,874 out=84,493,747 elapsed=160.1s

  [9674/20519] intraday_17883.csv.gz  in=325,913,012 out=84,506,885 elapsed=160.2s

  [9675/20519] intraday_17886.csv.gz  in=325,923,101 out=84,516,974 elapsed=160.2s

  [9676/20519] intraday_17887.csv.gz  in=325,936,929 out=84,530,802 elapsed=160.2s

  [9677/20519] intraday_17888.csv.gz  in=325,949,402 out=84,543,275 elapsed=160.2s

  [9678/20519] intraday_1789.csv.gz  in=325,962,396 out=84,543,275 elapsed=160.2s

  [9679/20519] intraday_17890.csv.gz  in=325,973,613 out=84,554,492 elapsed=160.2s

  [9680/20519] intraday_17889.csv.gz  in=325,988,112 out=84,568,991 elapsed=160.2s

  [9681/20519] intraday_17892.csv.gz  in=326,001,005 out=84,581,884 elapsed=160.3s

  [9682/20519] intraday_17891.csv.gz  in=326,012,329 out=84,593,208 elapsed=160.3s

  [9683/20519] intraday_17894.csv.gz  in=326,027,005 out=84,607,884 elapsed=160.3s

  [9684/20519] intraday_17893.csv.gz  in=326,044,161 out=84,625,040 elapsed=160.3s

  [9685/20519] intraday_17897.csv.gz  in=326,058,972 out=84,639,851 elapsed=160.4s

  [9686/20519] intraday_17895.csv.gz  in=326,073,672 out=84,654,551 elapsed=160.4s

  [9687/20519] intraday_17896.csv.gz  in=326,085,749 out=84,666,628 elapsed=160.4s

  [9688/20519] intraday_17898.csv.gz  in=326,096,799 out=84,677,678 elapsed=160.4s

  [9689/20519] intraday_17900.csv.gz  in=326,107,387 out=84,688,266 elapsed=160.4s

  [9690/20519] intraday_1790.csv.gz  in=326,118,112 out=84,688,266 elapsed=160.4s

  [9691/20519] intraday_17899.csv.gz  in=326,132,722 out=84,702,876 elapsed=160.4s

  [9692/20519] intraday_17901.csv.gz  in=326,144,292 out=84,714,446 elapsed=160.4s

  [9693/20519] intraday_17902.csv.gz  in=326,157,466 out=84,727,620 elapsed=160.4s

  [9694/20519] intraday_17903.csv.gz  in=326,169,373 out=84,739,527 elapsed=160.5s

  [9695/20519] intraday_17904.csv.gz  in=326,183,171 out=84,753,325 elapsed=160.5s

  [9696/20519] intraday_17905.csv.gz  in=326,194,160 out=84,764,314 elapsed=160.5s

  [9697/20519] intraday_17906.csv.gz  in=326,207,309 out=84,777,463 elapsed=160.5s

  [9698/20519] intraday_17907.csv.gz  in=326,218,497 out=84,788,651 elapsed=160.5s

  [9699/20519] intraday_17909.csv.gz  in=326,230,343 out=84,800,497 elapsed=160.5s

  [9700/20519] intraday_1791.csv.gz  in=326,241,949 out=84,800,497 elapsed=160.5s

  [9701/20519] intraday_17908.csv.gz  in=326,254,226 out=84,812,774 elapsed=160.5s

  [9702/20519] intraday_17910.csv.gz  in=326,265,653 out=84,824,201 elapsed=160.5s

  [9703/20519] intraday_17913.csv.gz  in=326,278,598 out=84,837,146 elapsed=160.6s

  [9704/20519] intraday_17914.csv.gz  in=326,290,489 out=84,849,037 elapsed=160.6s

  [9705/20519] intraday_17912.csv.gz  in=326,307,503 out=84,864,852 elapsed=160.7s

  [9706/20519] intraday_17911.csv.gz  in=326,320,170 out=84,877,519 elapsed=160.7s

  [9707/20519] intraday_17916.csv.gz  in=326,332,919 out=84,890,268 elapsed=160.7s

  [9708/20519] intraday_17915.csv.gz  in=326,345,103 out=84,902,452 elapsed=160.7s

  [9709/20519] intraday_17918.csv.gz  in=326,358,706 out=84,916,055 elapsed=160.7s

  [9710/20519] intraday_17917.csv.gz  in=326,375,856 out=84,931,880 elapsed=160.7s

  [9711/20519] intraday_1792.csv.gz  in=326,383,409 out=84,931,880 elapsed=160.7s

  [9712/20519] intraday_17919.csv.gz  in=326,396,953 out=84,945,424 elapsed=160.7s

  [9713/20519] intraday_17920.csv.gz  in=326,413,546 out=84,962,017 elapsed=160.8s

  [9714/20519] intraday_17921.csv.gz  in=326,424,820 out=84,973,291 elapsed=160.8s

  [9715/20519] intraday_17923.csv.gz  in=326,438,161 out=84,986,632 elapsed=160.8s

  [9716/20519] intraday_17922.csv.gz  in=326,452,897 out=85,001,368 elapsed=160.8s

  [9717/20519] intraday_17924.csv.gz  in=326,468,768 out=85,017,239 elapsed=160.8s

  [9718/20519] intraday_17925.csv.gz  in=326,483,972 out=85,032,443 elapsed=160.8s

  [9719/20519] intraday_17926.csv.gz  in=326,502,681 out=85,051,152 elapsed=160.8s

  [9720/20519] intraday_17927.csv.gz  in=326,515,568 out=85,064,039 elapsed=160.9s

  [9721/20519] intraday_1793.csv.gz  in=326,526,300 out=85,064,039 elapsed=160.9s

  [9722/20519] intraday_17929.csv.gz  in=326,538,199 out=85,075,938 elapsed=160.9s

  [9723/20519] intraday_17928.csv.gz  in=326,554,480 out=85,092,219 elapsed=160.9s

  [9724/20519] intraday_17931.csv.gz  in=326,564,444 out=85,102,183 elapsed=160.9s

  [9725/20519] intraday_17930.csv.gz  in=326,577,170 out=85,114,909 elapsed=160.9s

  [9726/20519] intraday_17932.csv.gz  in=326,590,590 out=85,128,329 elapsed=160.9s

  [9727/20519] intraday_17933.csv.gz  in=326,601,211 out=85,138,950 elapsed=160.9s

  [9728/20519] intraday_17934.csv.gz  in=326,614,459 out=85,152,198 elapsed=160.9s

  [9729/20519] intraday_17935.csv.gz  in=326,626,443 out=85,164,182 elapsed=161.0s

  [9730/20519] intraday_17937.csv.gz  in=326,637,932 out=85,175,671 elapsed=161.0s

  [9731/20519] intraday_17936.csv.gz  in=326,653,496 out=85,191,235 elapsed=161.0s

  [9732/20519] intraday_17938.csv.gz  in=326,665,230 out=85,202,969 elapsed=161.0s

  [9733/20519] intraday_17939.csv.gz  in=326,677,329 out=85,215,068 elapsed=161.0s

  [9734/20519] intraday_1794.csv.gz  in=326,683,713 out=85,215,068 elapsed=161.0s

  [9735/20519] intraday_17940.csv.gz  in=326,697,686 out=85,229,041 elapsed=161.1s

  [9736/20519] intraday_17943.csv.gz  in=326,711,114 out=85,242,469 elapsed=161.1s

  [9737/20519] intraday_17942.csv.gz  in=326,724,954 out=85,256,309 elapsed=161.1s

  [9738/20519] intraday_17941.csv.gz  in=326,736,153 out=85,267,508 elapsed=161.1s

  [9739/20519] intraday_17944.csv.gz  in=326,749,122 out=85,280,477 elapsed=161.1s

  [9740/20519] intraday_17946.csv.gz  in=326,760,549 out=85,291,904 elapsed=161.2s

  [9741/20519] intraday_17945.csv.gz  in=326,776,522 out=85,307,877 elapsed=161.2s

  [9742/20519] intraday_17947.csv.gz  in=326,788,600 out=85,319,955 elapsed=161.2s

  [9743/20519] intraday_17948.csv.gz  in=326,801,044 out=85,332,399 elapsed=161.2s

  [9744/20519] intraday_17949.csv.gz  in=326,811,453 out=85,342,808 elapsed=161.2s

  [9745/20519] intraday_17950.csv.gz  in=326,824,071 out=85,355,426 elapsed=161.2s

  [9746/20519] intraday_1795.csv.gz  in=326,838,937 out=85,355,426 elapsed=161.2s

  [9747/20519] intraday_17951.csv.gz  in=326,847,474 out=85,363,963 elapsed=161.2s

  [9748/20519] intraday_17952.csv.gz  in=326,858,526 out=85,375,015 elapsed=161.2s

  [9749/20519] intraday_17953.csv.gz  in=326,866,610 out=85,383,099 elapsed=161.3s

  [9750/20519] intraday_17954.csv.gz  in=326,882,680 out=85,399,169 elapsed=161.3s

  [9751/20519] intraday_17955.csv.gz  in=326,896,108 out=85,412,597 elapsed=161.3s

  [9752/20519] intraday_17956.csv.gz  in=326,908,879 out=85,425,368 elapsed=161.3s

  [9753/20519] intraday_17957.csv.gz  in=326,919,017 out=85,435,506 elapsed=161.3s

  [9754/20519] intraday_17958.csv.gz  in=326,932,387 out=85,448,876 elapsed=161.3s

  [9755/20519] intraday_17959.csv.gz  in=326,946,319 out=85,462,808 elapsed=161.3s

  [9756/20519] intraday_1796.csv.gz  in=326,959,560 out=85,462,808 elapsed=161.3s

  [9757/20519] intraday_17960.csv.gz  in=326,973,032 out=85,476,280 elapsed=161.4s

  [9758/20519] intraday_17962.csv.gz  in=326,987,057 out=85,490,305 elapsed=161.4s

  [9759/20519] intraday_17961.csv.gz  in=326,998,228 out=85,501,476 elapsed=161.4s

  [9760/20519] intraday_17964.csv.gz  in=327,008,610 out=85,511,858 elapsed=161.4s

  [9761/20519] intraday_17963.csv.gz  in=327,021,697 out=85,524,945 elapsed=161.4s

  [9762/20519] intraday_17965.csv.gz  in=327,033,694 out=85,536,942 elapsed=161.4s

  [9763/20519] intraday_17966.csv.gz  in=327,048,875 out=85,552,123 elapsed=161.5s

  [9764/20519] intraday_17967.csv.gz  in=327,059,935 out=85,563,183 elapsed=161.5s

  [9765/20519] intraday_17968.csv.gz  in=327,071,077 out=85,574,325 elapsed=161.5s

  [9766/20519] intraday_1797.csv.gz  in=327,083,256 out=85,574,325 elapsed=161.5s

  [9767/20519] intraday_17969.csv.gz  in=327,094,168 out=85,585,237 elapsed=161.5s

  [9768/20519] intraday_17970.csv.gz  in=327,109,670 out=85,600,739 elapsed=161.5s

  [9769/20519] intraday_17971.csv.gz  in=327,122,672 out=85,613,741 elapsed=161.5s

  [9770/20519] intraday_17972.csv.gz  in=327,133,741 out=85,624,810 elapsed=161.5s

  [9771/20519] intraday_17973.csv.gz  in=327,144,315 out=85,635,384 elapsed=161.5s

  [9772/20519] intraday_17974.csv.gz  in=327,157,011 out=85,648,080 elapsed=161.6s

  [9773/20519] intraday_17975.csv.gz  in=327,170,286 out=85,661,355 elapsed=161.6s

  [9774/20519] intraday_17976.csv.gz  in=327,183,625 out=85,674,694 elapsed=161.6s

  [9775/20519] intraday_17977.csv.gz  in=327,195,129 out=85,686,198 elapsed=161.6s

  [9776/20519] intraday_17979.csv.gz  in=327,206,297 out=85,697,366 elapsed=161.6s

  [9777/20519] intraday_17978.csv.gz  in=327,218,006 out=85,709,075 elapsed=161.6s

  [9778/20519] intraday_1798.csv.gz  in=327,229,405 out=85,709,075 elapsed=161.6s

  [9779/20519] intraday_17980.csv.gz  in=327,241,526 out=85,721,196 elapsed=161.7s

  [9780/20519] intraday_17981.csv.gz  in=327,252,510 out=85,732,180 elapsed=161.7s

  [9781/20519] intraday_17982.csv.gz  in=327,266,668 out=85,746,338 elapsed=161.7s

  [9782/20519] intraday_17983.csv.gz  in=327,280,324 out=85,759,994 elapsed=161.7s

  [9783/20519] intraday_17984.csv.gz  in=327,292,119 out=85,771,789 elapsed=161.7s

  [9784/20519] intraday_17985.csv.gz  in=327,304,126 out=85,783,796 elapsed=161.7s

  [9785/20519] intraday_17986.csv.gz  in=327,315,920 out=85,795,590 elapsed=161.7s

  [9786/20519] intraday_17987.csv.gz  in=327,329,094 out=85,808,764 elapsed=161.8s

  [9787/20519] intraday_17988.csv.gz  in=327,342,760 out=85,822,430 elapsed=161.8s

  [9788/20519] intraday_1799.csv.gz  in=327,355,622 out=85,822,430 elapsed=161.8s

  [9789/20519] intraday_17989.csv.gz  in=327,368,876 out=85,835,684 elapsed=161.8s

  [9790/20519] intraday_17990.csv.gz  in=327,379,810 out=85,846,618 elapsed=161.8s

  [9791/20519] intraday_17991.csv.gz  in=327,391,426 out=85,858,234 elapsed=161.8s

  [9792/20519] intraday_17993.csv.gz  in=327,402,584 out=85,869,392 elapsed=161.8s

  [9793/20519] intraday_17992.csv.gz  in=327,412,838 out=85,879,646 elapsed=161.8s

  [9794/20519] intraday_17994.csv.gz  in=327,425,642 out=85,892,450 elapsed=161.8s

  [9795/20519] intraday_17997.csv.gz  in=327,439,480 out=85,906,288 elapsed=161.9s

  [9796/20519] intraday_17996.csv.gz  in=327,453,826 out=85,920,634 elapsed=161.9s

  [9797/20519] intraday_17995.csv.gz  in=327,465,690 out=85,932,498 elapsed=161.9s

  [9798/20519] intraday_17998.csv.gz  in=327,477,810 out=85,944,618 elapsed=161.9s

  [9799/20519] intraday_1800.csv.gz  in=327,492,423 out=85,944,618 elapsed=161.9s

  [9800/20519] intraday_18000.csv.gz  in=327,504,988 out=85,957,183 elapsed=161.9s

  [9801/20519] intraday_17999.csv.gz  in=327,516,565 out=85,968,760 elapsed=162.0s

  [9802/20519] intraday_18001.csv.gz  in=327,527,680 out=85,979,875 elapsed=162.0s

  [9803/20519] intraday_18002.csv.gz  in=327,540,441 out=85,992,636 elapsed=162.0s

  [9804/20519] intraday_18003.csv.gz  in=327,552,074 out=86,004,269 elapsed=162.0s

  [9805/20519] intraday_18004.csv.gz  in=327,562,943 out=86,015,138 elapsed=162.0s

  [9806/20519] intraday_18006.csv.gz  in=327,577,127 out=86,029,322 elapsed=162.0s

  [9807/20519] intraday_18007.csv.gz  in=327,590,188 out=86,042,383 elapsed=162.1s

  [9808/20519] intraday_18005.csv.gz  in=327,602,549 out=86,054,744 elapsed=162.1s

  [9809/20519] intraday_18008.csv.gz  in=327,615,705 out=86,067,900 elapsed=162.1s

  [9810/20519] intraday_1801.csv.gz  in=327,627,998 out=86,067,900 elapsed=162.1s

  [9811/20519] intraday_18009.csv.gz  in=327,639,234 out=86,079,136 elapsed=162.1s

  [9812/20519] intraday_18010.csv.gz  in=327,650,797 out=86,090,699 elapsed=162.1s

  [9813/20519] intraday_18011.csv.gz  in=327,663,584 out=86,103,486 elapsed=162.1s

  [9814/20519] intraday_18012.csv.gz  in=327,675,869 out=86,115,771 elapsed=162.2s

  [9815/20519] intraday_18014.csv.gz  in=327,687,089 out=86,126,991 elapsed=162.2s

  [9816/20519] intraday_18013.csv.gz  in=327,698,361 out=86,138,263 elapsed=162.2s

  [9817/20519] intraday_18015.csv.gz  in=327,710,762 out=86,150,664 elapsed=162.2s

  [9818/20519] intraday_18016.csv.gz  in=327,721,201 out=86,161,103 elapsed=162.2s

  [9819/20519] intraday_18018.csv.gz  in=327,734,985 out=86,174,887 elapsed=162.2s

  [9820/20519] intraday_18017.csv.gz  in=327,747,780 out=86,187,682 elapsed=162.2s

  [9821/20519] intraday_18019.csv.gz  in=327,760,459 out=86,200,361 elapsed=162.2s

  [9822/20519] intraday_1802.csv.gz  in=327,772,640 out=86,200,361 elapsed=162.3s

  [9823/20519] intraday_18020.csv.gz  in=327,786,766 out=86,214,487 elapsed=162.3s

  [9824/20519] intraday_18022.csv.gz  in=327,796,493 out=86,224,214 elapsed=162.3s

  [9825/20519] intraday_18021.csv.gz  in=327,809,604 out=86,237,325 elapsed=162.3s

  [9826/20519] intraday_18023.csv.gz  in=327,821,749 out=86,249,470 elapsed=162.3s

  [9827/20519] intraday_18024.csv.gz  in=327,838,488 out=86,266,209 elapsed=162.4s

  [9828/20519] intraday_18025.csv.gz  in=327,850,198 out=86,277,919 elapsed=162.4s

  [9829/20519] intraday_18026.csv.gz  in=327,861,591 out=86,289,312 elapsed=162.4s

  [9830/20519] intraday_18027.csv.gz  in=327,872,839 out=86,300,560 elapsed=162.4s

  [9831/20519] intraday_18028.csv.gz  in=327,881,920 out=86,309,641 elapsed=162.4s

  [9832/20519] intraday_18029.csv.gz  in=327,894,168 out=86,321,889 elapsed=162.4s

  [9833/20519] intraday_1803.csv.gz  in=327,907,769 out=86,321,889 elapsed=162.4s

  [9834/20519] intraday_18031.csv.gz  in=327,919,926 out=86,334,046 elapsed=162.4s

  [9835/20519] intraday_18030.csv.gz  in=327,934,393 out=86,348,513 elapsed=162.5s

  [9836/20519] intraday_18033.csv.gz  in=327,944,809 out=86,358,929 elapsed=162.5s

  [9837/20519] intraday_18032.csv.gz  in=327,958,366 out=86,372,486 elapsed=162.5s

  [9838/20519] intraday_18034.csv.gz  in=327,969,681 out=86,383,801 elapsed=162.5s

  [9839/20519] intraday_18035.csv.gz  in=327,984,390 out=86,398,510 elapsed=162.5s

  [9840/20519] intraday_18036.csv.gz  in=328,002,342 out=86,416,462 elapsed=162.5s

  [9841/20519] intraday_18038.csv.gz  in=328,015,813 out=86,429,933 elapsed=162.6s

  [9842/20519] intraday_18039.csv.gz  in=328,029,159 out=86,443,279 elapsed=162.6s

  [9843/20519] intraday_1804.csv.gz  in=328,043,508 out=86,443,279 elapsed=162.6s

  [9844/20519] intraday_18037.csv.gz  in=328,057,464 out=86,457,235 elapsed=162.6s

  [9845/20519] intraday_18040.csv.gz  in=328,069,710 out=86,469,481 elapsed=162.6s

  [9846/20519] intraday_18042.csv.gz  in=328,082,604 out=86,482,375 elapsed=162.6s

  [9847/20519] intraday_18043.csv.gz  in=328,093,026 out=86,492,797 elapsed=162.6s

  [9848/20519] intraday_18041.csv.gz  in=328,106,723 out=86,506,494 elapsed=162.6s

  [9849/20519] intraday_18045.csv.gz  in=328,119,998 out=86,519,769 elapsed=162.7s

  [9850/20519] intraday_18044.csv.gz  in=328,133,140 out=86,532,911 elapsed=162.7s

  [9851/20519] intraday_18046.csv.gz  in=328,143,905 out=86,543,676 elapsed=162.7s

  [9852/20519] intraday_18047.csv.gz  in=328,156,525 out=86,556,296 elapsed=162.7s

  [9853/20519] intraday_18048.csv.gz  in=328,168,784 out=86,568,555 elapsed=162.7s

  [9854/20519] intraday_18049.csv.gz  in=328,181,741 out=86,581,512 elapsed=162.7s

  [9855/20519] intraday_1805.csv.gz  in=328,190,658 out=86,581,512 elapsed=162.7s

  [9856/20519] intraday_18050.csv.gz  in=328,201,722 out=86,592,576 elapsed=162.7s

  [9857/20519] intraday_18051.csv.gz  in=328,212,715 out=86,603,569 elapsed=162.8s

  [9858/20519] intraday_18052.csv.gz  in=328,224,616 out=86,615,470 elapsed=162.8s

  [9859/20519] intraday_18053.csv.gz  in=328,236,641 out=86,627,495 elapsed=162.8s

  [9860/20519] intraday_18054.csv.gz  in=328,248,304 out=86,639,158 elapsed=162.8s

  [9861/20519] intraday_18055.csv.gz  in=328,262,055 out=86,652,909 elapsed=162.8s

  [9862/20519] intraday_18056.csv.gz  in=328,273,746 out=86,664,600 elapsed=162.8s

  [9863/20519] intraday_18057.csv.gz  in=328,285,979 out=86,676,833 elapsed=162.8s

  [9864/20519] intraday_18058.csv.gz  in=328,299,401 out=86,690,255 elapsed=162.8s

  [9865/20519] intraday_18059.csv.gz  in=328,309,325 out=86,700,179 elapsed=162.9s

  [9866/20519] intraday_1806.csv.gz  in=328,321,466 out=86,700,179 elapsed=162.9s

  [9867/20519] intraday_18061.csv.gz  in=328,334,681 out=86,713,394 elapsed=162.9s

  [9868/20519] intraday_18060.csv.gz  in=328,346,636 out=86,725,349 elapsed=162.9s

  [9869/20519] intraday_18063.csv.gz  in=328,359,904 out=86,738,617 elapsed=162.9s

  [9870/20519] intraday_18062.csv.gz  in=328,374,884 out=86,753,597 elapsed=162.9s

  [9871/20519] intraday_18064.csv.gz  in=328,388,975 out=86,767,688 elapsed=162.9s

  [9872/20519] intraday_18065.csv.gz  in=328,401,716 out=86,780,429 elapsed=162.9s

  [9873/20519] intraday_18066.csv.gz  in=328,416,476 out=86,795,189 elapsed=163.0s

  [9874/20519] intraday_18067.csv.gz  in=328,430,381 out=86,809,094 elapsed=163.0s

  [9875/20519] intraday_18068.csv.gz  in=328,447,734 out=86,826,447 elapsed=163.0s

  [9876/20519] intraday_1807.csv.gz  in=328,460,948 out=86,826,447 elapsed=163.0s

  [9877/20519] intraday_18069.csv.gz  in=328,474,947 out=86,840,446 elapsed=163.0s

  [9878/20519] intraday_18070.csv.gz  in=328,491,564 out=86,857,063 elapsed=163.0s

  [9879/20519] intraday_18071.csv.gz  in=328,503,940 out=86,869,439 elapsed=163.0s

  [9880/20519] intraday_18072.csv.gz  in=328,517,243 out=86,882,742 elapsed=163.1s

  [9881/20519] intraday_18074.csv.gz  in=328,529,687 out=86,895,186 elapsed=163.1s

  [9882/20519] intraday_18075.csv.gz  in=328,540,523 out=86,906,022 elapsed=163.1s

  [9883/20519] intraday_18073.csv.gz  in=328,552,545 out=86,918,044 elapsed=163.1s

  [9884/20519] intraday_18077.csv.gz  in=328,564,226 out=86,929,725 elapsed=163.2s

  [9885/20519] intraday_18076.csv.gz  in=328,576,954 out=86,942,453 elapsed=163.2s

  [9886/20519] intraday_18078.csv.gz  in=328,592,201 out=86,957,700 elapsed=163.2s

  [9887/20519] intraday_1808.csv.gz  in=328,602,709 out=86,957,700 elapsed=163.2s

  [9888/20519] intraday_18079.csv.gz  in=328,613,445 out=86,968,436 elapsed=163.2s

  [9889/20519] intraday_18081.csv.gz  in=328,625,431 out=86,980,422 elapsed=163.2s

  [9890/20519] intraday_18080.csv.gz  in=328,638,632 out=86,993,623 elapsed=163.2s

  [9891/20519] intraday_18082.csv.gz  in=328,651,694 out=87,006,685 elapsed=163.3s

  [9892/20519] intraday_18083.csv.gz  in=328,663,689 out=87,018,680 elapsed=163.3s

  [9893/20519] intraday_18084.csv.gz  in=328,676,495 out=87,031,486 elapsed=163.3s

  [9894/20519] intraday_18086.csv.gz  in=328,690,574 out=87,045,565 elapsed=163.3s

  [9895/20519] intraday_18088.csv.gz  in=328,702,890 out=87,057,881 elapsed=163.3s

  [9896/20519] intraday_18087.csv.gz  in=328,717,667 out=87,072,658 elapsed=163.3s

  [9897/20519] intraday_18085.csv.gz  in=328,730,671 out=87,085,662 elapsed=163.3s

  [9898/20519] intraday_18089.csv.gz  in=328,742,107 out=87,097,098 elapsed=163.4s

  [9899/20519] intraday_1809.csv.gz  in=328,752,322 out=87,097,098 elapsed=163.4s

  [9900/20519] intraday_18091.csv.gz  in=328,762,475 out=87,107,251 elapsed=163.4s

  [9901/20519] intraday_18090.csv.gz  in=328,775,208 out=87,119,984 elapsed=163.4s

  [9902/20519] intraday_18093.csv.gz  in=328,785,650 out=87,130,426 elapsed=163.4s

  [9903/20519] intraday_18092.csv.gz  in=328,799,393 out=87,144,169 elapsed=163.4s

  [9904/20519] intraday_18095.csv.gz  in=328,810,318 out=87,155,094 elapsed=163.4s

  [9905/20519] intraday_18094.csv.gz  in=328,819,674 out=87,164,450 elapsed=163.4s

  [9906/20519] intraday_18096.csv.gz  in=328,835,012 out=87,179,788 elapsed=163.5s

  [9907/20519] intraday_18097.csv.gz  in=328,849,198 out=87,193,974 elapsed=163.5s

  [9908/20519] intraday_18098.csv.gz  in=328,861,965 out=87,206,741 elapsed=163.5s

  [9909/20519] intraday_18099.csv.gz  in=328,872,406 out=87,217,182 elapsed=163.5s

  [9910/20519] intraday_1810.csv.gz  in=328,884,690 out=87,217,182 elapsed=163.5s

  [9911/20519] intraday_18100.csv.gz  in=328,897,053 out=87,229,545 elapsed=163.5s

  [9912/20519] intraday_18101.csv.gz  in=328,911,693 out=87,244,185 elapsed=163.6s

  [9913/20519] intraday_18103.csv.gz  in=328,922,789 out=87,255,281 elapsed=163.6s

  [9914/20519] intraday_18102.csv.gz  in=328,935,590 out=87,268,082 elapsed=163.6s

  [9915/20519] intraday_18104.csv.gz  in=328,949,646 out=87,282,138 elapsed=163.6s

  [9916/20519] intraday_18106.csv.gz  in=328,959,548 out=87,292,040 elapsed=163.6s

  [9917/20519] intraday_18105.csv.gz  in=328,972,062 out=87,304,554 elapsed=163.6s

  [9918/20519] intraday_18108.csv.gz  in=328,986,391 out=87,318,883 elapsed=163.6s

  [9919/20519] intraday_18107.csv.gz  in=328,998,544 out=87,331,036 elapsed=163.6s

  [9920/20519] intraday_18109.csv.gz  in=329,010,948 out=87,343,440 elapsed=163.6s

  [9921/20519] intraday_1811.csv.gz  in=329,023,452 out=87,343,440 elapsed=163.6s

  [9922/20519] intraday_18110.csv.gz  in=329,033,205 out=87,353,193 elapsed=163.7s

  [9923/20519] intraday_18111.csv.gz  in=329,045,109 out=87,365,097 elapsed=163.7s

  [9924/20519] intraday_18112.csv.gz  in=329,061,237 out=87,381,225 elapsed=163.7s

  [9925/20519] intraday_18114.csv.gz  in=329,072,222 out=87,392,210 elapsed=163.7s

  [9926/20519] intraday_18113.csv.gz  in=329,084,571 out=87,404,559 elapsed=163.7s

  [9927/20519] intraday_18115.csv.gz  in=329,095,450 out=87,415,438 elapsed=163.7s

  [9928/20519] intraday_18116.csv.gz  in=329,108,415 out=87,428,403 elapsed=163.7s

  [9929/20519] intraday_18117.csv.gz  in=329,122,669 out=87,442,657 elapsed=163.8s

  [9930/20519] intraday_18119.csv.gz  in=329,134,311 out=87,454,299 elapsed=163.8s

  [9931/20519] intraday_1812.csv.gz  in=329,146,232 out=87,454,299 elapsed=163.8s

  [9932/20519] intraday_18118.csv.gz  in=329,159,616 out=87,467,683 elapsed=163.8s

  [9933/20519] intraday_18120.csv.gz  in=329,172,044 out=87,480,111 elapsed=163.8s

  [9934/20519] intraday_18121.csv.gz  in=329,183,422 out=87,491,489 elapsed=163.8s

  [9935/20519] intraday_18123.csv.gz  in=329,194,684 out=87,502,751 elapsed=163.8s

  [9936/20519] intraday_18122.csv.gz  in=329,207,773 out=87,515,840 elapsed=163.8s

  [9937/20519] intraday_18124.csv.gz  in=329,221,744 out=87,529,811 elapsed=163.8s

  [9938/20519] intraday_18127.csv.gz  in=329,232,983 out=87,541,050 elapsed=163.9s

  [9939/20519] intraday_18126.csv.gz  in=329,245,209 out=87,553,276 elapsed=163.9s

  [9940/20519] intraday_18125.csv.gz  in=329,259,403 out=87,567,451 elapsed=163.9s

  [9941/20519] intraday_18128.csv.gz  in=329,271,036 out=87,579,084 elapsed=163.9s

  [9942/20519] intraday_1813.csv.gz  in=329,282,762 out=87,579,084 elapsed=163.9s

  [9943/20519] intraday_18129.csv.gz  in=329,295,001 out=87,591,323 elapsed=164.0s

  [9944/20519] intraday_18132.csv.gz  in=329,306,201 out=87,602,523 elapsed=164.0s

  [9945/20519] intraday_18131.csv.gz  in=329,319,789 out=87,616,111 elapsed=164.0s

  [9946/20519] intraday_18130.csv.gz  in=329,333,030 out=87,629,352 elapsed=164.0s

  [9947/20519] intraday_18135.csv.gz  in=329,343,745 out=87,640,067 elapsed=164.0s

  [9948/20519] intraday_18133.csv.gz  in=329,355,582 out=87,651,904 elapsed=164.0s

  [9949/20519] intraday_18134.csv.gz  in=329,373,027 out=87,667,801 elapsed=164.1s

  [9950/20519] intraday_18136.csv.gz  in=329,394,367 out=87,686,947 elapsed=164.1s

  [9951/20519] intraday_18137.csv.gz  in=329,406,122 out=87,698,702 elapsed=164.1s

  [9952/20519] intraday_18139.csv.gz  in=329,419,457 out=87,712,037 elapsed=164.1s

  [9953/20519] intraday_1814.csv.gz  in=329,431,275 out=87,712,037 elapsed=164.1s

  [9954/20519] intraday_18140.csv.gz  in=329,443,807 out=87,724,569 elapsed=164.2s

  [9955/20519] intraday_18138.csv.gz  in=329,458,671 out=87,739,215 elapsed=164.2s

  [9956/20519] intraday_18142.csv.gz  in=329,471,950 out=87,752,494 elapsed=164.2s

  [9957/20519] intraday_18141.csv.gz  in=329,504,421 out=87,781,742 elapsed=164.2s

  [9958/20519] intraday_18143.csv.gz  in=329,516,965 out=87,794,286 elapsed=164.2s

  [9959/20519] intraday_18145.csv.gz  in=329,527,747 out=87,805,068 elapsed=164.2s

  [9960/20519] intraday_18144.csv.gz  in=329,540,876 out=87,818,197 elapsed=164.2s

  [9961/20519] intraday_18146.csv.gz  in=329,552,322 out=87,829,643 elapsed=164.3s

  [9962/20519] intraday_18147.csv.gz  in=329,564,911 out=87,842,232 elapsed=164.3s

  [9963/20519] intraday_18149.csv.gz  in=329,579,144 out=87,856,465 elapsed=164.3s

  [9964/20519] intraday_1815.csv.gz  in=329,598,272 out=87,856,465 elapsed=164.3s

  [9965/20519] intraday_18148.csv.gz  in=329,613,051 out=87,871,244 elapsed=164.3s

  [9966/20519] intraday_18150.csv.gz  in=329,625,984 out=87,884,177 elapsed=164.3s

  [9967/20519] intraday_18151.csv.gz  in=329,637,669 out=87,895,862 elapsed=164.4s

  [9968/20519] intraday_18153.csv.gz  in=329,650,163 out=87,908,356 elapsed=164.4s

  [9969/20519] intraday_18154.csv.gz  in=329,663,564 out=87,921,757 elapsed=164.4s

  [9970/20519] intraday_18156.csv.gz  in=329,675,847 out=87,934,040 elapsed=164.4s

  [9971/20519] intraday_18152.csv.gz  in=329,687,063 out=87,945,256 elapsed=164.4s

  [9972/20519] intraday_18155.csv.gz  in=329,697,888 out=87,956,081 elapsed=164.4s

  [9973/20519] intraday_18157.csv.gz  in=329,710,073 out=87,968,266 elapsed=164.4s

  [9974/20519] intraday_18158.csv.gz  in=329,720,488 out=87,978,681 elapsed=164.5s

  [9975/20519] intraday_1816.csv.gz  in=329,740,456 out=87,978,681 elapsed=164.5s

  [9976/20519] intraday_18159.csv.gz  in=329,753,921 out=87,992,146 elapsed=164.5s

  [9977/20519] intraday_18160.csv.gz  in=329,768,269 out=88,006,494 elapsed=164.5s

  [9978/20519] intraday_18161.csv.gz  in=329,780,107 out=88,018,332 elapsed=164.5s

  [9979/20519] intraday_18162.csv.gz  in=329,793,828 out=88,032,053 elapsed=164.5s

  [9980/20519] intraday_18164.csv.gz  in=329,803,554 out=88,041,779 elapsed=164.6s

  [9981/20519] intraday_18163.csv.gz  in=329,834,524 out=88,069,488 elapsed=164.6s

  [9982/20519] intraday_18166.csv.gz  in=329,849,693 out=88,084,657 elapsed=164.6s

  [9983/20519] intraday_18167.csv.gz  in=329,862,240 out=88,097,204 elapsed=164.6s

  [9984/20519] intraday_18165.csv.gz  in=329,874,475 out=88,109,439 elapsed=164.6s

  [9985/20519] intraday_18168.csv.gz  in=329,886,030 out=88,120,994 elapsed=164.6s

  [9986/20519] intraday_18169.csv.gz  in=329,898,229 out=88,133,193 elapsed=164.6s

  [9987/20519] intraday_1817.csv.gz  in=329,912,054 out=88,133,193 elapsed=164.7s

  [9988/20519] intraday_18170.csv.gz  in=329,922,118 out=88,143,257 elapsed=164.7s

  [9989/20519] intraday_18172.csv.gz  in=329,935,340 out=88,156,455 elapsed=164.7s

  [9990/20519] intraday_18171.csv.gz  in=329,947,114 out=88,168,229 elapsed=164.7s

  [9991/20519] intraday_18173.csv.gz  in=329,958,801 out=88,179,916 elapsed=164.7s

  [9992/20519] intraday_18174.csv.gz  in=329,971,728 out=88,192,741 elapsed=164.7s

  [9993/20519] intraday_18175.csv.gz  in=329,981,693 out=88,202,706 elapsed=164.8s

  [9994/20519] intraday_18176.csv.gz  in=329,993,277 out=88,214,290 elapsed=164.8s

  [9995/20519] intraday_18177.csv.gz  in=330,008,503 out=88,229,516 elapsed=164.8s

  [9996/20519] intraday_18179.csv.gz  in=330,021,773 out=88,242,786 elapsed=164.8s

  [9997/20519] intraday_1818.csv.gz  in=330,034,438 out=88,242,786 elapsed=164.8s

  [9998/20519] intraday_18180.csv.gz  in=330,048,255 out=88,256,603 elapsed=164.8s

  [9999/20519] intraday_18178.csv.gz  in=330,067,219 out=88,275,567 elapsed=164.8s

  [10000/20519] intraday_18181.csv.gz  in=330,080,750 out=88,289,098 elapsed=164.8s

  [10001/20519] intraday_18182.csv.gz  in=330,093,165 out=88,301,513 elapsed=164.8s

  [10002/20519] intraday_18184.csv.gz  in=330,104,567 out=88,312,915 elapsed=164.9s

  [10003/20519] intraday_18183.csv.gz  in=330,118,928 out=88,327,276 elapsed=164.9s

  [10004/20519] intraday_18185.csv.gz  in=330,129,214 out=88,337,562 elapsed=164.9s

  [10005/20519] intraday_18186.csv.gz  in=330,142,488 out=88,350,836 elapsed=164.9s

  [10006/20519] intraday_18187.csv.gz  in=330,162,480 out=88,370,464 elapsed=164.9s

  [10007/20519] intraday_18188.csv.gz  in=330,174,605 out=88,382,589 elapsed=164.9s

  [10008/20519] intraday_18189.csv.gz  in=330,187,916 out=88,395,900 elapsed=164.9s

  [10009/20519] intraday_1819.csv.gz  in=330,200,395 out=88,395,900 elapsed=165.0s

  [10010/20519] intraday_18190.csv.gz  in=330,212,711 out=88,408,216 elapsed=165.0s

  [10011/20519] intraday_18192.csv.gz  in=330,223,754 out=88,419,259 elapsed=165.0s

  [10012/20519] intraday_18191.csv.gz  in=330,235,767 out=88,431,272 elapsed=165.0s

  [10013/20519] intraday_18193.csv.gz  in=330,246,132 out=88,441,637 elapsed=165.0s

  [10014/20519] intraday_18194.csv.gz  in=330,257,586 out=88,453,091 elapsed=165.0s

  [10015/20519] intraday_18195.csv.gz  in=330,270,420 out=88,465,925 elapsed=165.0s

  [10016/20519] intraday_18197.csv.gz  in=330,284,016 out=88,479,521 elapsed=165.0s

  [10017/20519] intraday_18196.csv.gz  in=330,298,621 out=88,493,826 elapsed=165.1s

  [10018/20519] intraday_1820.csv.gz  in=330,307,464 out=88,493,826 elapsed=165.1s

  [10019/20519] intraday_18198.csv.gz  in=330,319,988 out=88,506,350 elapsed=165.1s

  [10020/20519] intraday_18199.csv.gz  in=330,332,711 out=88,519,073 elapsed=165.1s

  [10021/20519] intraday_18200.csv.gz  in=330,346,221 out=88,532,583 elapsed=165.1s

  [10022/20519] intraday_18201.csv.gz  in=330,356,968 out=88,543,330 elapsed=165.1s

  [10023/20519] intraday_18202.csv.gz  in=330,368,775 out=88,555,137 elapsed=165.2s

  [10024/20519] intraday_18203.csv.gz  in=330,381,822 out=88,568,184 elapsed=165.2s

  [10025/20519] intraday_18204.csv.gz  in=330,396,150 out=88,582,512 elapsed=165.2s

  [10026/20519] intraday_18206.csv.gz  in=330,410,899 out=88,597,261 elapsed=165.2s

  [10027/20519] intraday_18205.csv.gz  in=330,424,895 out=88,611,257 elapsed=165.2s

  [10028/20519] intraday_18207.csv.gz  in=330,439,196 out=88,625,174 elapsed=165.2s

  [10029/20519] intraday_18208.csv.gz  in=330,454,395 out=88,640,373 elapsed=165.2s

  [10030/20519] intraday_1821.csv.gz  in=330,466,682 out=88,640,373 elapsed=165.2s

  [10031/20519] intraday_18209.csv.gz  in=330,480,224 out=88,653,915 elapsed=165.3s

  [10032/20519] intraday_18210.csv.gz  in=330,498,457 out=88,672,148 elapsed=165.3s

  [10033/20519] intraday_18211.csv.gz  in=330,517,985 out=88,690,139 elapsed=165.3s

  [10034/20519] intraday_18213.csv.gz  in=330,528,942 out=88,701,096 elapsed=165.3s

  [10035/20519] intraday_18214.csv.gz  in=330,542,395 out=88,714,230 elapsed=165.3s

  [10036/20519] intraday_18212.csv.gz  in=330,560,739 out=88,732,574 elapsed=165.3s

  [10037/20519] intraday_18215.csv.gz  in=330,571,926 out=88,743,761 elapsed=165.3s

  [10038/20519] intraday_18216.csv.gz  in=330,584,037 out=88,755,872 elapsed=165.4s

  [10039/20519] intraday_18217.csv.gz  in=330,595,996 out=88,767,831 elapsed=165.4s

  [10040/20519] intraday_18218.csv.gz  in=330,609,610 out=88,781,445 elapsed=165.4s

  [10041/20519] intraday_1822.csv.gz  in=330,621,287 out=88,781,445 elapsed=165.4s

  [10042/20519] intraday_18219.csv.gz  in=330,640,302 out=88,798,967 elapsed=165.4s

  [10043/20519] intraday_18220.csv.gz  in=330,655,707 out=88,814,372 elapsed=165.4s

  [10044/20519] intraday_18221.csv.gz  in=330,666,400 out=88,825,065 elapsed=165.4s

  [10045/20519] intraday_18222.csv.gz  in=330,678,799 out=88,837,464 elapsed=165.4s

  [10046/20519] intraday_18223.csv.gz  in=330,690,009 out=88,848,674 elapsed=165.4s

  [10047/20519] intraday_18224.csv.gz  in=330,703,598 out=88,862,263 elapsed=165.5s

  [10048/20519] intraday_18225.csv.gz  in=330,716,220 out=88,874,885 elapsed=165.5s

  [10049/20519] intraday_18226.csv.gz  in=330,729,908 out=88,888,573 elapsed=165.5s

  [10050/20519] intraday_18227.csv.gz  in=330,744,941 out=88,903,606 elapsed=165.5s

  [10051/20519] intraday_18229.csv.gz  in=330,761,399 out=88,920,064 elapsed=165.5s

  [10052/20519] intraday_18228.csv.gz  in=330,773,726 out=88,932,391 elapsed=165.5s

  [10053/20519] intraday_1823.csv.gz  in=330,786,591 out=88,932,391 elapsed=165.5s

  [10054/20519] intraday_18230.csv.gz  in=330,796,760 out=88,942,560 elapsed=165.5s

  [10055/20519] intraday_18231.csv.gz  in=330,809,459 out=88,955,259 elapsed=165.6s

  [10056/20519] intraday_18233.csv.gz  in=330,819,053 out=88,964,853 elapsed=165.6s

  [10057/20519] intraday_18232.csv.gz  in=330,831,936 out=88,977,736 elapsed=165.6s

  [10058/20519] intraday_18235.csv.gz  in=330,840,604 out=88,986,404 elapsed=165.6s

  [10059/20519] intraday_18234.csv.gz  in=330,853,023 out=88,998,823 elapsed=165.6s

  [10060/20519] intraday_18237.csv.gz  in=330,861,077 out=89,006,877 elapsed=165.6s

  [10061/20519] intraday_18238.csv.gz  in=330,877,751 out=89,023,551 elapsed=165.7s

  [10062/20519] intraday_18236.csv.gz  in=330,888,215 out=89,034,015 elapsed=165.7s

  [10063/20519] intraday_1824.csv.gz  in=330,903,373 out=89,034,015 elapsed=165.7s

  [10064/20519] intraday_18239.csv.gz  in=330,918,205 out=89,048,847 elapsed=165.7s

  [10065/20519] intraday_18241.csv.gz  in=330,929,841 out=89,060,483 elapsed=165.7s

  [10066/20519] intraday_18242.csv.gz  in=330,943,921 out=89,074,563 elapsed=165.7s

  [10067/20519] intraday_18243.csv.gz  in=330,959,127 out=89,089,769 elapsed=165.8s

  [10068/20519] intraday_18240.csv.gz  in=330,972,702 out=89,103,344 elapsed=165.8s

  [10069/20519] intraday_18244.csv.gz  in=330,986,011 out=89,116,653 elapsed=165.8s

  [10070/20519] intraday_18246.csv.gz  in=330,998,914 out=89,129,556 elapsed=165.8s

  [10071/20519] intraday_18245.csv.gz  in=331,011,672 out=89,142,314 elapsed=165.8s

  [10072/20519] intraday_18248.csv.gz  in=331,022,930 out=89,153,572 elapsed=165.8s

  [10073/20519] intraday_18247.csv.gz  in=331,036,685 out=89,167,327 elapsed=165.8s

  [10074/20519] intraday_18249.csv.gz  in=331,049,517 out=89,180,159 elapsed=165.8s

  [10075/20519] intraday_1825.csv.gz  in=331,061,855 out=89,180,159 elapsed=165.8s

  [10076/20519] intraday_18250.csv.gz  in=331,075,851 out=89,194,155 elapsed=165.9s

  [10077/20519] intraday_18251.csv.gz  in=331,089,238 out=89,207,542 elapsed=165.9s

  [10078/20519] intraday_18252.csv.gz  in=331,100,246 out=89,218,550 elapsed=165.9s

  [10079/20519] intraday_18253.csv.gz  in=331,111,405 out=89,229,709 elapsed=165.9s

  [10080/20519] intraday_18254.csv.gz  in=331,127,520 out=89,245,824 elapsed=165.9s

  [10081/20519] intraday_18255.csv.gz  in=331,143,384 out=89,261,308 elapsed=165.9s

  [10082/20519] intraday_18256.csv.gz  in=331,154,025 out=89,271,949 elapsed=166.0s

  [10083/20519] intraday_18258.csv.gz  in=331,168,099 out=89,286,023 elapsed=166.0s

  [10084/20519] intraday_18257.csv.gz  in=331,179,405 out=89,297,329 elapsed=166.0s

  [10085/20519] intraday_1826.csv.gz  in=331,189,967 out=89,297,329 elapsed=166.0s

  [10086/20519] intraday_18259.csv.gz  in=331,204,461 out=89,311,823 elapsed=166.0s

  [10087/20519] intraday_18261.csv.gz  in=331,216,499 out=89,323,861 elapsed=166.0s

  [10088/20519] intraday_18260.csv.gz  in=331,229,534 out=89,336,896 elapsed=166.0s

  [10089/20519] intraday_18262.csv.gz  in=331,242,337 out=89,349,699 elapsed=166.1s

  [10090/20519] intraday_18264.csv.gz  in=331,255,468 out=89,362,830 elapsed=166.1s

  [10091/20519] intraday_18263.csv.gz  in=331,267,700 out=89,375,062 elapsed=166.1s

  [10092/20519] intraday_18265.csv.gz  in=331,278,985 out=89,386,347 elapsed=166.1s

  [10093/20519] intraday_18268.csv.gz  in=331,291,634 out=89,398,996 elapsed=166.1s

  [10094/20519] intraday_18266.csv.gz  in=331,307,021 out=89,414,383 elapsed=166.1s

  [10095/20519] intraday_18267.csv.gz  in=331,320,954 out=89,428,316 elapsed=166.1s

  [10096/20519] intraday_18269.csv.gz  in=331,334,058 out=89,441,420 elapsed=166.1s

  [10097/20519] intraday_1827.csv.gz  in=331,348,541 out=89,441,420 elapsed=166.2s

  [10098/20519] intraday_18270.csv.gz  in=331,361,192 out=89,454,071 elapsed=166.2s

  [10099/20519] intraday_18272.csv.gz  in=331,375,539 out=89,468,418 elapsed=166.2s

  [10100/20519] intraday_18271.csv.gz  in=331,387,986 out=89,480,865 elapsed=166.2s

  [10101/20519] intraday_18273.csv.gz  in=331,401,531 out=89,494,410 elapsed=166.2s

  [10102/20519] intraday_18274.csv.gz  in=331,412,116 out=89,504,995 elapsed=166.2s

  [10103/20519] intraday_18275.csv.gz  in=331,424,049 out=89,516,928 elapsed=166.3s

  [10104/20519] intraday_18277.csv.gz  in=331,435,960 out=89,528,839 elapsed=166.3s

  [10105/20519] intraday_18279.csv.gz  in=331,449,715 out=89,542,594 elapsed=166.3s

  [10106/20519] intraday_1828.csv.gz  in=331,462,024 out=89,542,594 elapsed=166.3s

  [10107/20519] intraday_18276.csv.gz  in=331,493,014 out=89,569,836 elapsed=166.3s

  [10108/20519] intraday_18278.csv.gz  in=331,508,565 out=89,584,936 elapsed=166.3s

  [10109/20519] intraday_18280.csv.gz  in=331,521,697 out=89,598,068 elapsed=166.3s

  [10110/20519] intraday_18281.csv.gz  in=331,535,772 out=89,612,143 elapsed=166.4s

  [10111/20519] intraday_18283.csv.gz  in=331,547,142 out=89,623,513 elapsed=166.4s

  [10112/20519] intraday_18282.csv.gz  in=331,559,546 out=89,635,917 elapsed=166.4s

  [10113/20519] intraday_18285.csv.gz  in=331,572,327 out=89,648,698 elapsed=166.4s

  [10114/20519] intraday_18284.csv.gz  in=331,587,258 out=89,663,629 elapsed=166.4s

  [10115/20519] intraday_18286.csv.gz  in=331,601,059 out=89,677,430 elapsed=166.4s

  [10116/20519] intraday_18287.csv.gz  in=331,612,911 out=89,689,282 elapsed=166.4s

  [10117/20519] intraday_18288.csv.gz  in=331,625,980 out=89,702,351 elapsed=166.4s

  [10118/20519] intraday_1829.csv.gz  in=331,636,920 out=89,702,351 elapsed=166.5s

  [10119/20519] intraday_18289.csv.gz  in=331,650,618 out=89,716,049 elapsed=166.5s

  [10120/20519] intraday_18290.csv.gz  in=331,667,158 out=89,732,589 elapsed=166.5s

  [10121/20519] intraday_18293.csv.gz  in=331,679,313 out=89,744,744 elapsed=166.5s

  [10122/20519] intraday_18292.csv.gz  in=331,691,410 out=89,756,841 elapsed=166.5s

  [10123/20519] intraday_18291.csv.gz  in=331,707,234 out=89,772,665 elapsed=166.5s

  [10124/20519] intraday_18294.csv.gz  in=331,718,569 out=89,784,000 elapsed=166.5s

  [10125/20519] intraday_18295.csv.gz  in=331,731,733 out=89,797,164 elapsed=166.6s

  [10126/20519] intraday_18296.csv.gz  in=331,745,390 out=89,810,821 elapsed=166.6s

  [10127/20519] intraday_18298.csv.gz  in=331,768,138 out=89,831,563 elapsed=166.6s

  [10128/20519] intraday_18297.csv.gz  in=331,780,986 out=89,844,411 elapsed=166.6s

  [10129/20519] intraday_1830.csv.gz  in=331,793,223 out=89,844,411 elapsed=166.6s

  [10130/20519] intraday_18299.csv.gz  in=331,806,626 out=89,857,814 elapsed=166.6s

  [10131/20519] intraday_18300.csv.gz  in=331,820,528 out=89,871,170 elapsed=166.6s

  [10132/20519] intraday_18301.csv.gz  in=331,835,295 out=89,885,937 elapsed=166.7s

  [10133/20519] intraday_18302.csv.gz  in=331,849,726 out=89,900,368 elapsed=166.7s

  [10134/20519] intraday_18304.csv.gz  in=331,864,901 out=89,915,543 elapsed=166.7s

  [10135/20519] intraday_18303.csv.gz  in=331,877,518 out=89,928,160 elapsed=166.7s

  [10136/20519] intraday_18305.csv.gz  in=331,890,753 out=89,941,395 elapsed=166.7s

  [10137/20519] intraday_18306.csv.gz  in=331,899,959 out=89,950,601 elapsed=166.7s

  [10138/20519] intraday_18307.csv.gz  in=331,912,959 out=89,963,601 elapsed=166.7s

  [10139/20519] intraday_18308.csv.gz  in=331,927,470 out=89,978,112 elapsed=166.7s

  [10140/20519] intraday_1831.csv.gz  in=331,938,794 out=89,978,112 elapsed=166.7s

  [10141/20519] intraday_18309.csv.gz  in=331,951,906 out=89,991,224 elapsed=166.8s

  [10142/20519] intraday_18310.csv.gz  in=331,963,759 out=90,003,077 elapsed=166.8s

  [10143/20519] intraday_18311.csv.gz  in=331,977,172 out=90,016,490 elapsed=166.8s

  [10144/20519] intraday_18312.csv.gz  in=331,988,893 out=90,028,211 elapsed=166.8s

  [10145/20519] intraday_18313.csv.gz  in=332,003,148 out=90,042,466 elapsed=166.8s

  [10146/20519] intraday_18316.csv.gz  in=332,015,567 out=90,054,885 elapsed=166.8s

  [10147/20519] intraday_18314.csv.gz  in=332,028,853 out=90,068,171 elapsed=166.8s

  [10148/20519] intraday_18315.csv.gz  in=332,041,762 out=90,081,080 elapsed=166.9s

  [10149/20519] intraday_18317.csv.gz  in=332,053,123 out=90,092,441 elapsed=166.9s

  [10150/20519] intraday_18318.csv.gz  in=332,065,293 out=90,104,611 elapsed=166.9s

  [10151/20519] intraday_1832.csv.gz  in=332,076,974 out=90,104,611 elapsed=166.9s

  [10152/20519] intraday_18319.csv.gz  in=332,093,626 out=90,121,263 elapsed=166.9s

  [10153/20519] intraday_18322.csv.gz  in=332,107,747 out=90,135,384 elapsed=166.9s

  [10154/20519] intraday_18320.csv.gz  in=332,123,880 out=90,151,517 elapsed=166.9s

  [10155/20519] intraday_18321.csv.gz  in=332,142,411 out=90,169,428 elapsed=167.0s

  [10156/20519] intraday_18323.csv.gz  in=332,160,571 out=90,187,588 elapsed=167.0s

  [10157/20519] intraday_18324.csv.gz  in=332,174,045 out=90,200,525 elapsed=167.0s

  [10158/20519] intraday_18325.csv.gz  in=332,189,332 out=90,215,812 elapsed=167.0s

  [10159/20519] intraday_18326.csv.gz  in=332,201,211 out=90,227,691 elapsed=167.0s

  [10160/20519] intraday_18328.csv.gz  in=332,215,176 out=90,241,656 elapsed=167.1s

  [10161/20519] intraday_18329.csv.gz  in=332,227,633 out=90,254,113 elapsed=167.1s

  [10162/20519] intraday_1833.csv.gz  in=332,239,831 out=90,254,113 elapsed=167.1s

  [10163/20519] intraday_18327.csv.gz  in=332,251,052 out=90,265,334 elapsed=167.1s

  [10164/20519] intraday_18330.csv.gz  in=332,263,796 out=90,278,078 elapsed=167.1s

  [10165/20519] intraday_18333.csv.gz  in=332,276,574 out=90,290,856 elapsed=167.1s

  [10166/20519] intraday_18331.csv.gz  in=332,290,263 out=90,304,545 elapsed=167.2s

  [10167/20519] intraday_18334.csv.gz  in=332,301,724 out=90,316,006 elapsed=167.2s

  [10168/20519] intraday_18332.csv.gz  in=332,314,180 out=90,328,462 elapsed=167.2s

  [10169/20519] intraday_18335.csv.gz  in=332,326,313 out=90,340,595 elapsed=167.2s

  [10170/20519] intraday_18336.csv.gz  in=332,338,429 out=90,352,711 elapsed=167.2s

  [10171/20519] intraday_18338.csv.gz  in=332,351,753 out=90,366,035 elapsed=167.2s

  [10172/20519] intraday_1834.csv.gz  in=332,362,119 out=90,366,035 elapsed=167.3s

  [10173/20519] intraday_18339.csv.gz  in=332,377,077 out=90,380,993 elapsed=167.3s

  [10174/20519] intraday_18337.csv.gz  in=332,389,337 out=90,393,253 elapsed=167.3s

  [10175/20519] intraday_18340.csv.gz  in=332,400,861 out=90,404,777 elapsed=167.3s

  [10176/20519] intraday_18343.csv.gz  in=332,412,729 out=90,416,645 elapsed=167.3s

  [10177/20519] intraday_18342.csv.gz  in=332,426,183 out=90,430,099 elapsed=167.3s

  [10178/20519] intraday_18341.csv.gz  in=332,439,768 out=90,443,684 elapsed=167.3s

  [10179/20519] intraday_18345.csv.gz  in=332,453,605 out=90,457,521 elapsed=167.3s

  [10180/20519] intraday_18344.csv.gz  in=332,467,116 out=90,471,032 elapsed=167.4s

  [10181/20519] intraday_18346.csv.gz  in=332,482,882 out=90,486,798 elapsed=167.4s

  [10182/20519] intraday_1835.csv.gz  in=332,497,095 out=90,486,798 elapsed=167.4s

  [10183/20519] intraday_18348.csv.gz  in=332,513,435 out=90,503,138 elapsed=167.4s

  [10184/20519] intraday_18349.csv.gz  in=332,527,283 out=90,516,986 elapsed=167.4s

  [10185/20519] intraday_18347.csv.gz  in=332,541,980 out=90,531,683 elapsed=167.4s

  [10186/20519] intraday_18350.csv.gz  in=332,557,660 out=90,547,363 elapsed=167.5s

  [10187/20519] intraday_18353.csv.gz  in=332,571,314 out=90,561,017 elapsed=167.5s

  [10188/20519] intraday_18352.csv.gz  in=332,590,236 out=90,579,939 elapsed=167.5s

  [10189/20519] intraday_18351.csv.gz  in=332,606,276 out=90,595,979 elapsed=167.5s

  [10190/20519] intraday_18355.csv.gz  in=332,619,338 out=90,609,041 elapsed=167.5s

  [10191/20519] intraday_18356.csv.gz  in=332,632,283 out=90,621,986 elapsed=167.6s

  [10192/20519] intraday_18354.csv.gz  in=332,649,789 out=90,639,492 elapsed=167.6s

  [10193/20519] intraday_18357.csv.gz  in=332,659,774 out=90,649,477 elapsed=167.6s

  [10194/20519] intraday_18358.csv.gz  in=332,674,299 out=90,664,002 elapsed=167.6s

  [10195/20519] intraday_1836.csv.gz  in=332,686,600 out=90,664,002 elapsed=167.6s

  [10196/20519] intraday_18359.csv.gz  in=332,698,750 out=90,676,152 elapsed=167.6s

  [10197/20519] intraday_18362.csv.gz  in=332,712,578 out=90,689,980 elapsed=167.6s

  [10198/20519] intraday_18360.csv.gz  in=332,726,319 out=90,703,721 elapsed=167.6s

  [10199/20519] intraday_18361.csv.gz  in=332,739,123 out=90,716,525 elapsed=167.7s

  [10200/20519] intraday_18363.csv.gz  in=332,750,997 out=90,728,399 elapsed=167.7s

  [10201/20519] intraday_18364.csv.gz  in=332,763,942 out=90,741,344 elapsed=167.7s

  [10202/20519] intraday_18365.csv.gz  in=332,777,689 out=90,755,091 elapsed=167.7s

  [10203/20519] intraday_18367.csv.gz  in=332,789,765 out=90,767,167 elapsed=167.7s

  [10204/20519] intraday_18368.csv.gz  in=332,805,566 out=90,782,968 elapsed=167.7s

  [10205/20519] intraday_18366.csv.gz  in=332,820,063 out=90,797,465 elapsed=167.7s

  [10206/20519] intraday_18369.csv.gz  in=332,836,197 out=90,813,599 elapsed=167.7s

  [10207/20519] intraday_1837.csv.gz  in=332,849,541 out=90,813,599 elapsed=167.7s

  [10208/20519] intraday_18371.csv.gz  in=332,864,045 out=90,828,103 elapsed=167.8s

  [10209/20519] intraday_18373.csv.gz  in=332,876,323 out=90,840,381 elapsed=167.8s

  [10210/20519] intraday_18372.csv.gz  in=332,888,753 out=90,852,811 elapsed=167.8s

  [10211/20519] intraday_18370.csv.gz  in=332,901,882 out=90,865,777 elapsed=167.8s

  [10212/20519] intraday_18374.csv.gz  in=332,913,813 out=90,877,708 elapsed=167.8s

  [10213/20519] intraday_18375.csv.gz  in=332,933,219 out=90,897,074 elapsed=167.9s

  [10214/20519] intraday_18377.csv.gz  in=332,941,489 out=90,905,344 elapsed=167.9s

  [10215/20519] intraday_18378.csv.gz  in=332,951,600 out=90,915,455 elapsed=167.9s

  [10216/20519] intraday_18376.csv.gz  in=332,963,208 out=90,927,063 elapsed=167.9s

  [10217/20519] intraday_18379.csv.gz  in=332,969,198 out=90,933,053 elapsed=167.9s

  [10218/20519] intraday_1838.csv.gz  in=332,981,339 out=90,933,053 elapsed=167.9s

  [10219/20519] intraday_18383.csv.gz  in=332,991,823 out=90,943,537 elapsed=167.9s

  [10220/20519] intraday_18381.csv.gz  in=333,006,489 out=90,958,203 elapsed=167.9s

  [10221/20519] intraday_18380.csv.gz  in=333,022,513 out=90,974,227 elapsed=167.9s

  [10222/20519] intraday_18382.csv.gz  in=333,034,731 out=90,986,445 elapsed=168.0s

  [10223/20519] intraday_18386.csv.gz  in=333,047,744 out=90,999,458 elapsed=168.0s

  [10224/20519] intraday_18384.csv.gz  in=333,062,076 out=91,013,790 elapsed=168.0s

  [10225/20519] intraday_18387.csv.gz  in=333,073,898 out=91,025,612 elapsed=168.0s

  [10226/20519] intraday_18385.csv.gz  in=333,089,304 out=91,041,018 elapsed=168.0s

  [10227/20519] intraday_18389.csv.gz  in=333,101,647 out=91,053,361 elapsed=168.1s

  [10228/20519] intraday_18390.csv.gz  in=333,112,813 out=91,064,527 elapsed=168.1s

  [10229/20519] intraday_1839.csv.gz  in=333,136,829 out=91,064,527 elapsed=168.1s

  [10230/20519] intraday_18388.csv.gz  in=333,150,922 out=91,078,620 elapsed=168.1s

  [10231/20519] intraday_18391.csv.gz  in=333,163,297 out=91,090,995 elapsed=168.1s

  [10232/20519] intraday_18392.csv.gz  in=333,177,029 out=91,104,727 elapsed=168.1s

  [10233/20519] intraday_18393.csv.gz  in=333,188,800 out=91,116,498 elapsed=168.1s

  [10234/20519] intraday_18395.csv.gz  in=333,198,799 out=91,126,497 elapsed=168.2s

  [10235/20519] intraday_18394.csv.gz  in=333,209,687 out=91,137,385 elapsed=168.2s

  [10236/20519] intraday_18397.csv.gz  in=333,222,320 out=91,150,018 elapsed=168.2s

  [10237/20519] intraday_18396.csv.gz  in=333,238,431 out=91,166,129 elapsed=168.2s

  [10238/20519] intraday_18398.csv.gz  in=333,249,733 out=91,177,431 elapsed=168.2s

  [10239/20519] intraday_1840.csv.gz  in=333,262,668 out=91,177,431 elapsed=168.2s

  [10240/20519] intraday_18399.csv.gz  in=333,273,692 out=91,188,455 elapsed=168.2s

  [10241/20519] intraday_18402.csv.gz  in=333,286,331 out=91,201,094 elapsed=168.3s

  [10242/20519] intraday_18403.csv.gz  in=333,298,072 out=91,212,835 elapsed=168.3s

  [10243/20519] intraday_18400.csv.gz  in=333,311,416 out=91,226,179 elapsed=168.3s

  [10244/20519] intraday_18401.csv.gz  in=333,324,218 out=91,238,981 elapsed=168.3s

  [10245/20519] intraday_18404.csv.gz  in=333,336,540 out=91,251,303 elapsed=168.3s

  [10246/20519] intraday_18406.csv.gz  in=333,348,893 out=91,263,656 elapsed=168.3s

  [10247/20519] intraday_18407.csv.gz  in=333,359,284 out=91,274,047 elapsed=168.4s

  [10248/20519] intraday_18405.csv.gz  in=333,371,608 out=91,286,371 elapsed=168.4s

  [10249/20519] intraday_18408.csv.gz  in=333,385,485 out=91,300,248 elapsed=168.4s

  [10250/20519] intraday_18409.csv.gz  in=333,399,488 out=91,314,251 elapsed=168.4s

  [10251/20519] intraday_18411.csv.gz  in=333,411,690 out=91,326,453 elapsed=168.4s

  [10252/20519] intraday_18410.csv.gz  in=333,422,951 out=91,337,714 elapsed=168.4s

  [10253/20519] intraday_18412.csv.gz  in=333,435,619 out=91,350,382 elapsed=168.4s

  [10254/20519] intraday_1841.csv.gz  in=333,446,365 out=91,350,382 elapsed=168.4s

  [10255/20519] intraday_18413.csv.gz  in=333,458,716 out=91,362,733 elapsed=168.4s

  [10256/20519] intraday_18414.csv.gz  in=333,472,674 out=91,376,691 elapsed=168.5s

  [10257/20519] intraday_18416.csv.gz  in=333,483,223 out=91,387,240 elapsed=168.5s

  [10258/20519] intraday_18415.csv.gz  in=333,496,108 out=91,400,125 elapsed=168.5s

  [10259/20519] intraday_18417.csv.gz  in=333,507,594 out=91,411,611 elapsed=168.5s

  [10260/20519] intraday_18418.csv.gz  in=333,519,282 out=91,423,257 elapsed=168.5s

  [10261/20519] intraday_18419.csv.gz  in=333,530,562 out=91,434,537 elapsed=168.5s

  [10262/20519] intraday_1842.csv.gz  in=333,542,965 out=91,434,537 elapsed=168.5s

  [10263/20519] intraday_18421.csv.gz  in=333,556,099 out=91,447,671 elapsed=168.6s

  [10264/20519] intraday_18420.csv.gz  in=333,568,106 out=91,459,678 elapsed=168.6s

  [10265/20519] intraday_18422.csv.gz  in=333,581,290 out=91,472,862 elapsed=168.6s

  [10266/20519] intraday_18424.csv.gz  in=333,593,529 out=91,485,101 elapsed=168.6s

  [10267/20519] intraday_18425.csv.gz  in=333,604,849 out=91,496,421 elapsed=168.6s

  [10268/20519] intraday_18423.csv.gz  in=333,618,457 out=91,510,029 elapsed=168.6s

  [10269/20519] intraday_18426.csv.gz  in=333,635,780 out=91,526,867 elapsed=168.7s

  [10270/20519] intraday_18427.csv.gz  in=333,650,162 out=91,541,249 elapsed=168.7s

  [10271/20519] intraday_18429.csv.gz  in=333,661,962 out=91,553,049 elapsed=168.7s

  [10272/20519] intraday_18428.csv.gz  in=333,675,051 out=91,566,138 elapsed=168.7s

  [10273/20519] intraday_1843.csv.gz  in=333,686,458 out=91,566,138 elapsed=168.7s

  [10274/20519] intraday_18430.csv.gz  in=333,697,822 out=91,577,502 elapsed=168.7s

  [10275/20519] intraday_18432.csv.gz  in=333,711,796 out=91,591,476 elapsed=168.8s

  [10276/20519] intraday_18431.csv.gz  in=333,724,096 out=91,603,776 elapsed=168.8s

  [10277/20519] intraday_18433.csv.gz  in=333,741,080 out=91,620,428 elapsed=168.8s

  [10278/20519] intraday_18434.csv.gz  in=333,755,493 out=91,634,841 elapsed=168.8s

  [10279/20519] intraday_18435.csv.gz  in=333,766,533 out=91,645,881 elapsed=168.8s

  [10280/20519] intraday_18436.csv.gz  in=333,777,727 out=91,657,075 elapsed=168.8s

  [10281/20519] intraday_18437.csv.gz  in=333,799,615 out=91,677,690 elapsed=168.8s

  [10282/20519] intraday_18438.csv.gz  in=333,813,599 out=91,691,674 elapsed=168.8s

  [10283/20519] intraday_18439.csv.gz  in=333,825,652 out=91,703,727 elapsed=168.8s

  [10284/20519] intraday_1844.csv.gz  in=333,839,880 out=91,703,727 elapsed=168.8s

  [10285/20519] intraday_18440.csv.gz  in=333,852,172 out=91,716,019 elapsed=168.9s

  [10286/20519] intraday_18441.csv.gz  in=333,864,342 out=91,728,189 elapsed=168.9s

  [10287/20519] intraday_18442.csv.gz  in=333,875,175 out=91,739,022 elapsed=168.9s

  [10288/20519] intraday_18443.csv.gz  in=333,888,354 out=91,752,201 elapsed=168.9s

  [10289/20519] intraday_18445.csv.gz  in=333,899,856 out=91,763,703 elapsed=168.9s

  [10290/20519] intraday_18444.csv.gz  in=333,912,857 out=91,776,704 elapsed=168.9s

  [10291/20519] intraday_18446.csv.gz  in=333,927,507 out=91,791,354 elapsed=168.9s

  [10292/20519] intraday_18447.csv.gz  in=333,941,383 out=91,805,183 elapsed=169.0s

  [10293/20519] intraday_18448.csv.gz  in=333,951,035 out=91,814,835 elapsed=169.0s

  [10294/20519] intraday_18449.csv.gz  in=333,963,848 out=91,827,648 elapsed=169.0s

  [10295/20519] intraday_1845.csv.gz  in=333,979,045 out=91,827,648 elapsed=169.0s

  [10296/20519] intraday_18450.csv.gz  in=333,992,763 out=91,841,366 elapsed=169.0s

  [10297/20519] intraday_18451.csv.gz  in=334,004,403 out=91,853,006 elapsed=169.0s

  [10298/20519] intraday_18452.csv.gz  in=334,016,134 out=91,864,737 elapsed=169.1s

  [10299/20519] intraday_18453.csv.gz  in=334,028,056 out=91,876,659 elapsed=169.1s

  [10300/20519] intraday_18454.csv.gz  in=334,037,509 out=91,886,112 elapsed=169.1s

  [10301/20519] intraday_18455.csv.gz  in=334,050,850 out=91,899,453 elapsed=169.1s

  [10302/20519] intraday_18456.csv.gz  in=334,064,269 out=91,912,872 elapsed=169.1s

  [10303/20519] intraday_18457.csv.gz  in=334,076,023 out=91,924,626 elapsed=169.1s

  [10304/20519] intraday_18458.csv.gz  in=334,093,963 out=91,941,848 elapsed=169.2s

  [10305/20519] intraday_1846.csv.gz  in=334,108,546 out=91,941,848 elapsed=169.2s

  [10306/20519] intraday_18459.csv.gz  in=334,119,118 out=91,952,420 elapsed=169.2s

  [10307/20519] intraday_18460.csv.gz  in=334,130,436 out=91,963,738 elapsed=169.2s

  [10308/20519] intraday_18461.csv.gz  in=334,142,292 out=91,975,594 elapsed=169.2s

  [10309/20519] intraday_18464.csv.gz  in=334,154,957 out=91,988,259 elapsed=169.2s

  [10310/20519] intraday_18463.csv.gz  in=334,167,897 out=92,001,199 elapsed=169.3s

  [10311/20519] intraday_18462.csv.gz  in=334,186,746 out=92,020,048 elapsed=169.3s

  [10312/20519] intraday_18466.csv.gz  in=334,199,491 out=92,032,793 elapsed=169.3s

  [10313/20519] intraday_18465.csv.gz  in=334,212,478 out=92,045,780 elapsed=169.3s

  [10314/20519] intraday_18467.csv.gz  in=334,225,478 out=92,058,780 elapsed=169.3s

  [10315/20519] intraday_1847.csv.gz  in=334,235,884 out=92,058,780 elapsed=169.3s

  [10316/20519] intraday_18469.csv.gz  in=334,246,416 out=92,069,312 elapsed=169.3s

  [10317/20519] intraday_18468.csv.gz  in=334,259,520 out=92,082,416 elapsed=169.3s

  [10318/20519] intraday_18470.csv.gz  in=334,272,724 out=92,095,620 elapsed=169.4s

  [10319/20519] intraday_18471.csv.gz  in=334,283,134 out=92,106,030 elapsed=169.4s

  [10320/20519] intraday_18472.csv.gz  in=334,296,250 out=92,119,146 elapsed=169.4s

  [10321/20519] intraday_18475.csv.gz  in=334,308,564 out=92,131,460 elapsed=169.4s

  [10322/20519] intraday_18473.csv.gz  in=334,320,540 out=92,143,436 elapsed=169.4s

  [10323/20519] intraday_18474.csv.gz  in=334,333,498 out=92,156,394 elapsed=169.4s

  [10324/20519] intraday_18476.csv.gz  in=334,344,295 out=92,167,191 elapsed=169.4s

  [10325/20519] intraday_18477.csv.gz  in=334,355,138 out=92,178,034 elapsed=169.5s

  [10326/20519] intraday_18478.csv.gz  in=334,367,695 out=92,190,591 elapsed=169.5s

  [10327/20519] intraday_18479.csv.gz  in=334,380,316 out=92,203,212 elapsed=169.5s

  [10328/20519] intraday_1848.csv.gz  in=334,393,482 out=92,203,212 elapsed=169.5s

  [10329/20519] intraday_18480.csv.gz  in=334,405,625 out=92,215,355 elapsed=169.5s

  [10330/20519] intraday_18483.csv.gz  in=334,420,352 out=92,230,063 elapsed=169.6s

  [10331/20519] intraday_18481.csv.gz  in=334,433,496 out=92,243,167 elapsed=169.6s

  [10332/20519] intraday_18484.csv.gz  in=334,447,454 out=92,257,125 elapsed=169.6s

  [10333/20519] intraday_18482.csv.gz  in=334,458,712 out=92,268,383 elapsed=169.6s

  [10334/20519] intraday_18485.csv.gz  in=334,469,622 out=92,279,293 elapsed=169.6s

  [10335/20519] intraday_18486.csv.gz  in=334,481,246 out=92,290,917 elapsed=169.6s

  [10336/20519] intraday_18488.csv.gz  in=334,495,681 out=92,305,352 elapsed=169.7s

  [10337/20519] intraday_18489.csv.gz  in=334,512,069 out=92,321,740 elapsed=169.7s

  [10338/20519] intraday_18487.csv.gz  in=334,527,718 out=92,337,389 elapsed=169.7s

  [10339/20519] intraday_1849.csv.gz  in=334,540,543 out=92,337,389 elapsed=169.7s

  [10340/20519] intraday_18490.csv.gz  in=334,555,850 out=92,352,696 elapsed=169.7s

  [10341/20519] intraday_18492.csv.gz  in=334,568,320 out=92,365,166 elapsed=169.7s

  [10342/20519] intraday_18491.csv.gz  in=334,582,111 out=92,378,957 elapsed=169.7s

  [10343/20519] intraday_18493.csv.gz  in=334,598,317 out=92,395,163 elapsed=169.7s

  [10344/20519] intraday_18494.csv.gz  in=334,614,860 out=92,411,706 elapsed=169.8s

  [10345/20519] intraday_18495.csv.gz  in=334,628,333 out=92,425,179 elapsed=169.8s

  [10346/20519] intraday_18496.csv.gz  in=334,646,303 out=92,443,097 elapsed=169.8s

  [10347/20519] intraday_18497.csv.gz  in=334,660,669 out=92,457,463 elapsed=169.8s

  [10348/20519] intraday_18498.csv.gz  in=334,674,759 out=92,471,553 elapsed=169.8s

  [10349/20519] intraday_18499.csv.gz  in=334,687,098 out=92,483,892 elapsed=169.8s

  [10350/20519] intraday_1850.csv.gz  in=334,699,122 out=92,483,892 elapsed=169.8s

  [10351/20519] intraday_18500.csv.gz  in=334,709,747 out=92,494,517 elapsed=169.9s

  [10352/20519] intraday_18501.csv.gz  in=334,722,008 out=92,506,778 elapsed=169.9s

  [10353/20519] intraday_18503.csv.gz  in=334,735,822 out=92,520,508 elapsed=169.9s

  [10354/20519] intraday_18504.csv.gz  in=334,749,720 out=92,534,406 elapsed=169.9s

  [10355/20519] intraday_18502.csv.gz  in=334,762,035 out=92,546,721 elapsed=169.9s

  [10356/20519] intraday_18505.csv.gz  in=334,773,534 out=92,558,220 elapsed=169.9s

  [10357/20519] intraday_18506.csv.gz  in=334,785,241 out=92,569,927 elapsed=169.9s

  [10358/20519] intraday_18507.csv.gz  in=334,797,736 out=92,582,422 elapsed=170.0s

  [10359/20519] intraday_18508.csv.gz  in=334,809,648 out=92,594,334 elapsed=170.0s

  [10360/20519] intraday_1851.csv.gz  in=334,820,178 out=92,594,334 elapsed=170.0s

  [10361/20519] intraday_18510.csv.gz  in=334,834,094 out=92,608,250 elapsed=170.0s

  [10362/20519] intraday_18509.csv.gz  in=334,846,694 out=92,620,850 elapsed=170.0s

  [10363/20519] intraday_18511.csv.gz  in=334,861,354 out=92,635,510 elapsed=170.0s

  [10364/20519] intraday_18512.csv.gz  in=334,874,610 out=92,648,766 elapsed=170.1s

  [10365/20519] intraday_18514.csv.gz  in=334,888,478 out=92,662,634 elapsed=170.1s

  [10366/20519] intraday_18513.csv.gz  in=334,901,996 out=92,676,152 elapsed=170.1s

  [10367/20519] intraday_18515.csv.gz  in=334,913,259 out=92,687,415 elapsed=170.1s

  [10368/20519] intraday_18516.csv.gz  in=334,925,778 out=92,699,934 elapsed=170.1s

  [10369/20519] intraday_18517.csv.gz  in=334,936,050 out=92,710,206 elapsed=170.1s

  [10370/20519] intraday_1852.csv.gz  in=334,948,613 out=92,710,206 elapsed=170.1s

  [10371/20519] intraday_18518.csv.gz  in=334,962,204 out=92,723,797 elapsed=170.2s

  [10372/20519] intraday_18520.csv.gz  in=334,970,292 out=92,731,885 elapsed=170.2s

  [10373/20519] intraday_18522.csv.gz  in=334,971,177 out=92,732,770 elapsed=170.2s

  [10374/20519] intraday_18521.csv.gz  in=334,983,019 out=92,744,612 elapsed=170.2s

  [10375/20519] intraday_18524.csv.gz  in=334,983,319 out=92,744,912 elapsed=170.2s

  [10376/20519] intraday_18523.csv.gz  in=334,983,614 out=92,745,207 elapsed=170.2s

  [10377/20519] intraday_18519.csv.gz  in=334,999,895 out=92,760,455 elapsed=170.2s

  [10378/20519] intraday_18525.csv.gz  in=335,000,459 out=92,761,019 elapsed=170.2s

  [10379/20519] intraday_18526.csv.gz  in=335,000,936 out=92,761,496 elapsed=170.2s

  [10380/20519] intraday_18527.csv.gz  in=335,001,735 out=92,762,295 elapsed=170.3s

  [10381/20519] intraday_18529.csv.gz  in=335,002,087 out=92,762,647 elapsed=170.3s

  [10382/20519] intraday_18528.csv.gz  in=335,002,774 out=92,763,334 elapsed=170.3s

  [10383/20519] intraday_18531.csv.gz  in=335,003,214 out=92,763,774 elapsed=170.3s

  [10384/20519] intraday_18530.csv.gz  in=335,003,812 out=92,764,372 elapsed=170.3s

  [10385/20519] intraday_18532.csv.gz  in=335,004,240 out=92,764,800 elapsed=170.3s

  [10386/20519] intraday_1853.csv.gz  in=335,016,407 out=92,764,800 elapsed=170.3s

  [10387/20519] intraday_18534.csv.gz  in=335,017,293 out=92,765,686 elapsed=170.3s

  [10388/20519] intraday_18533.csv.gz  in=335,017,933 out=92,766,326 elapsed=170.3s

  [10389/20519] intraday_18536.csv.gz  in=335,018,195 out=92,766,588 elapsed=170.3s

  [10390/20519] intraday_18537.csv.gz  in=335,018,522 out=92,766,915 elapsed=170.3s

  [10391/20519] intraday_18535.csv.gz  in=335,018,817 out=92,767,210 elapsed=170.3s

  [10392/20519] intraday_18538.csv.gz  in=335,019,508 out=92,767,901 elapsed=170.3s

  [10393/20519] intraday_18540.csv.gz  in=335,019,755 out=92,768,148 elapsed=170.3s

  [10394/20519] intraday_18541.csv.gz  in=335,020,127 out=92,768,520 elapsed=170.3s

  [10395/20519] intraday_18539.csv.gz  in=335,020,729 out=92,769,122 elapsed=170.3s

  [10396/20519] intraday_18542.csv.gz  in=335,021,415 out=92,769,808 elapsed=170.3s

  [10397/20519] intraday_18543.csv.gz  in=335,021,572 out=92,769,965 elapsed=170.3s

  [10398/20519] intraday_18544.csv.gz  in=335,022,122 out=92,770,515 elapsed=170.4s

  [10399/20519] intraday_18545.csv.gz  in=335,022,451 out=92,770,844 elapsed=170.4s

  [10400/20519] intraday_1854.csv.gz  in=335,047,494 out=92,770,844 elapsed=170.4s

  [10401/20519] intraday_18546.csv.gz  in=335,047,536 out=92,770,886 elapsed=170.4s

  [10402/20519] intraday_18547.csv.gz  in=335,047,924 out=92,771,274 elapsed=170.4s

  [10403/20519] intraday_18549.csv.gz  in=335,048,035 out=92,771,385 elapsed=170.4s

  [10404/20519] intraday_18550.csv.gz  in=335,049,015 out=92,772,365 elapsed=170.4s

  [10405/20519] intraday_18548.csv.gz  in=335,049,318 out=92,772,668 elapsed=170.4s

  [10406/20519] intraday_18551.csv.gz  in=335,050,100 out=92,773,450 elapsed=170.4s

  [10407/20519] intraday_18552.csv.gz  in=335,050,598 out=92,773,948 elapsed=170.4s

  [10408/20519] intraday_18553.csv.gz  in=335,050,983 out=92,774,333 elapsed=170.4s

  [10409/20519] intraday_18554.csv.gz  in=335,051,541 out=92,774,891 elapsed=170.4s

  [10410/20519] intraday_1855.csv.gz  in=335,063,153 out=92,774,891 elapsed=170.4s

  [10411/20519] intraday_18555.csv.gz  in=335,063,720 out=92,775,458 elapsed=170.4s

  [10412/20519] intraday_18556.csv.gz  in=335,063,885 out=92,775,623 elapsed=170.4s

  [10413/20519] intraday_18559.csv.gz  in=335,064,065 out=92,775,803 elapsed=170.4s

  [10414/20519] intraday_18557.csv.gz  in=335,064,248 out=92,775,986 elapsed=170.4s

  [10415/20519] intraday_18558.csv.gz  in=335,064,527 out=92,776,265 elapsed=170.4s

  [10416/20519] intraday_18560.csv.gz  in=335,064,637 out=92,776,375 elapsed=170.4s

  [10417/20519] intraday_18562.csv.gz  in=335,064,786 out=92,776,524 elapsed=170.4s

  [10418/20519] intraday_18561.csv.gz  in=335,064,890 out=92,776,628 elapsed=170.4s

  [10419/20519] intraday_18563.csv.gz  in=335,065,035 out=92,776,773 elapsed=170.5s

  [10420/20519] intraday_18564.csv.gz  in=335,065,577 out=92,777,315 elapsed=170.5s

  [10421/20519] intraday_18565.csv.gz  in=335,066,050 out=92,777,788 elapsed=170.5s

  [10422/20519] intraday_18566.csv.gz  in=335,066,248 out=92,777,986 elapsed=170.5s

  [10423/20519] intraday_1856.csv.gz  in=335,086,512 out=92,777,986 elapsed=170.5s

  [10424/20519] intraday_18567.csv.gz  in=335,086,637 out=92,778,111 elapsed=170.5s

  [10425/20519] intraday_18568.csv.gz  in=335,086,903 out=92,778,377 elapsed=170.5s

  [10426/20519] intraday_18569.csv.gz  in=335,087,519 out=92,778,993 elapsed=170.5s

  [10427/20519] intraday_18570.csv.gz  in=335,087,762 out=92,779,236 elapsed=170.5s

  [10428/20519] intraday_1857.csv.gz  in=335,099,230 out=92,779,236 elapsed=170.5s

  [10429/20519] intraday_18571.csv.gz  in=335,099,378 out=92,779,384 elapsed=170.5s

  [10430/20519] intraday_18572.csv.gz  in=335,099,811 out=92,779,817 elapsed=170.5s

  [10431/20519] intraday_18573.csv.gz  in=335,100,222 out=92,780,228 elapsed=170.5s

  [10432/20519] intraday_18575.csv.gz  in=335,101,254 out=92,781,260 elapsed=170.5s

  [10433/20519] intraday_18576.csv.gz  in=335,101,738 out=92,781,744 elapsed=170.5s

  [10434/20519] intraday_18578.csv.gz  in=335,101,972 out=92,781,978 elapsed=170.5s

  [10435/20519] intraday_18574.csv.gz  in=335,103,173 out=92,783,179 elapsed=170.5s

  [10436/20519] intraday_18579.csv.gz  in=335,103,653 out=92,783,659 elapsed=170.5s

  [10437/20519] intraday_18580.csv.gz  in=335,103,917 out=92,783,923 elapsed=170.6s

  [10438/20519] intraday_18581.csv.gz  in=335,104,160 out=92,784,166 elapsed=170.6s

  [10439/20519] intraday_18582.csv.gz  in=335,104,518 out=92,784,524 elapsed=170.6s

  [10440/20519] intraday_18583.csv.gz  in=335,104,584 out=92,784,590 elapsed=170.6s

  [10441/20519] intraday_18584.csv.gz  in=335,104,667 out=92,784,673 elapsed=170.6s

  [10442/20519] intraday_18577.csv.gz  in=335,121,675 out=92,799,308 elapsed=170.6s

  [10443/20519] intraday_1858.csv.gz  in=335,134,484 out=92,799,308 elapsed=170.6s

  [10444/20519] intraday_18585.csv.gz  in=335,135,155 out=92,799,979 elapsed=170.6s

  [10445/20519] intraday_18586.csv.gz  in=335,135,831 out=92,800,655 elapsed=170.6s

  [10446/20519] intraday_18587.csv.gz  in=335,136,129 out=92,800,953 elapsed=170.6s

  [10447/20519] intraday_18588.csv.gz  in=335,136,470 out=92,801,294 elapsed=170.6s

  [10448/20519] intraday_18589.csv.gz  in=335,136,839 out=92,801,663 elapsed=170.6s

  [10449/20519] intraday_18590.csv.gz  in=335,137,168 out=92,801,992 elapsed=170.6s

  [10450/20519] intraday_18591.csv.gz  in=335,137,492 out=92,802,316 elapsed=170.6s

  [10451/20519] intraday_18592.csv.gz  in=335,138,056 out=92,802,880 elapsed=170.6s

  [10452/20519] intraday_1859.csv.gz  in=335,150,585 out=92,802,880 elapsed=170.6s

  [10453/20519] intraday_18593.csv.gz  in=335,150,871 out=92,803,166 elapsed=170.6s

  [10454/20519] intraday_18594.csv.gz  in=335,151,272 out=92,803,567 elapsed=170.6s

  [10455/20519] intraday_18595.csv.gz  in=335,151,953 out=92,804,248 elapsed=170.7s

  [10456/20519] intraday_18598.csv.gz  in=335,152,299 out=92,804,594 elapsed=170.7s

  [10457/20519] intraday_18596.csv.gz  in=335,152,477 out=92,804,772 elapsed=170.7s

  [10458/20519] intraday_18597.csv.gz  in=335,152,868 out=92,805,163 elapsed=170.7s

  [10459/20519] intraday_18600.csv.gz  in=335,153,298 out=92,805,593 elapsed=170.7s

  [10460/20519] intraday_18599.csv.gz  in=335,153,591 out=92,805,886 elapsed=170.7s

  [10461/20519] intraday_18601.csv.gz  in=335,153,655 out=92,805,950 elapsed=170.7s

  [10462/20519] intraday_18602.csv.gz  in=335,154,035 out=92,806,330 elapsed=170.7s

  [10463/20519] intraday_1860.csv.gz  in=335,168,430 out=92,806,330 elapsed=170.7s

  [10464/20519] intraday_18604.csv.gz  in=335,170,171 out=92,808,071 elapsed=170.7s

  [10465/20519] intraday_18603.csv.gz  in=335,171,062 out=92,808,962 elapsed=170.7s

  [10466/20519] intraday_18605.csv.gz  in=335,171,670 out=92,809,570 elapsed=170.7s

  [10467/20519] intraday_18606.csv.gz  in=335,172,338 out=92,810,238 elapsed=170.7s

  [10468/20519] intraday_18608.csv.gz  in=335,172,675 out=92,810,575 elapsed=170.7s

  [10469/20519] intraday_18609.csv.gz  in=335,173,430 out=92,811,330 elapsed=170.7s

  [10470/20519] intraday_18607.csv.gz  in=335,174,231 out=92,812,131 elapsed=170.7s

  [10471/20519] intraday_18611.csv.gz  in=335,174,464 out=92,812,364 elapsed=170.7s

  [10472/20519] intraday_18610.csv.gz  in=335,175,026 out=92,812,926 elapsed=170.7s

  [10473/20519] intraday_18612.csv.gz  in=335,175,476 out=92,813,376 elapsed=170.8s

  [10474/20519] intraday_18613.csv.gz  in=335,175,902 out=92,813,802 elapsed=170.8s

  [10475/20519] intraday_18614.csv.gz  in=335,176,103 out=92,814,003 elapsed=170.8s

  [10476/20519] intraday_18615.csv.gz  in=335,176,426 out=92,814,326 elapsed=170.8s

  [10477/20519] intraday_1861.csv.gz  in=335,189,401 out=92,814,326 elapsed=170.8s

  [10478/20519] intraday_18616.csv.gz  in=335,189,779 out=92,814,704 elapsed=170.8s

  [10479/20519] intraday_18617.csv.gz  in=335,190,010 out=92,814,935 elapsed=170.8s

  [10480/20519] intraday_18618.csv.gz  in=335,190,310 out=92,815,235 elapsed=170.8s

  [10481/20519] intraday_18619.csv.gz  in=335,190,782 out=92,815,707 elapsed=170.8s

  [10482/20519] intraday_18621.csv.gz  in=335,191,097 out=92,816,022 elapsed=170.8s

  [10483/20519] intraday_18620.csv.gz  in=335,191,186 out=92,816,111 elapsed=170.8s

  [10484/20519] intraday_18622.csv.gz  in=335,192,013 out=92,816,938 elapsed=170.8s

  [10485/20519] intraday_18623.csv.gz  in=335,193,140 out=92,818,065 elapsed=170.8s

  [10486/20519] intraday_18625.csv.gz  in=335,193,340 out=92,818,265 elapsed=170.8s

  [10487/20519] intraday_18624.csv.gz  in=335,193,730 out=92,818,655 elapsed=170.8s

  [10488/20519] intraday_18626.csv.gz  in=335,194,670 out=92,819,595 elapsed=170.8s

  [10489/20519] intraday_18628.csv.gz  in=335,194,791 out=92,819,716 elapsed=170.8s

  [10490/20519] intraday_1862.csv.gz  in=335,206,795 out=92,819,716 elapsed=170.8s

  [10491/20519] intraday_18629.csv.gz  in=335,207,308 out=92,820,229 elapsed=170.8s

  [10492/20519] intraday_18630.csv.gz  in=335,207,901 out=92,820,822 elapsed=170.9s

  [10493/20519] intraday_18627.csv.gz  in=335,208,025 out=92,820,946 elapsed=170.9s

  [10494/20519] intraday_18631.csv.gz  in=335,208,826 out=92,821,747 elapsed=170.9s

  [10495/20519] intraday_18632.csv.gz  in=335,209,309 out=92,822,230 elapsed=170.9s

  [10496/20519] intraday_18633.csv.gz  in=335,209,993 out=92,822,914 elapsed=170.9s

  [10497/20519] intraday_18634.csv.gz  in=335,210,609 out=92,823,530 elapsed=170.9s

  [10498/20519] intraday_1863.csv.gz  in=335,220,989 out=92,823,530 elapsed=170.9s

  [10499/20519] intraday_18635.csv.gz  in=335,222,280 out=92,824,821 elapsed=170.9s

  [10500/20519] intraday_18636.csv.gz  in=335,223,878 out=92,826,419 elapsed=170.9s

  [10501/20519] intraday_18638.csv.gz  in=335,224,811 out=92,827,352 elapsed=170.9s

  [10502/20519] intraday_18639.csv.gz  in=335,225,521 out=92,828,062 elapsed=170.9s

  [10503/20519] intraday_18637.csv.gz  in=335,226,117 out=92,828,658 elapsed=170.9s

  [10504/20519] intraday_18640.csv.gz  in=335,226,777 out=92,829,318 elapsed=170.9s

  [10505/20519] intraday_18641.csv.gz  in=335,226,923 out=92,829,464 elapsed=170.9s

  [10506/20519] intraday_18643.csv.gz  in=335,227,057 out=92,829,598 elapsed=170.9s

  [10507/20519] intraday_1864.csv.gz  in=335,239,084 out=92,829,598 elapsed=170.9s

  [10508/20519] intraday_18644.csv.gz  in=335,239,561 out=92,830,075 elapsed=170.9s

  [10509/20519] intraday_18645.csv.gz  in=335,240,154 out=92,830,668 elapsed=170.9s

  [10510/20519] intraday_18642.csv.gz  in=335,240,519 out=92,831,033 elapsed=170.9s

  [10511/20519] intraday_18646.csv.gz  in=335,241,155 out=92,831,669 elapsed=171.0s

  [10512/20519] intraday_18647.csv.gz  in=335,241,694 out=92,832,208 elapsed=171.0s

  [10513/20519] intraday_18649.csv.gz  in=335,242,304 out=92,832,818 elapsed=171.0s

  [10514/20519] intraday_18648.csv.gz  in=335,242,737 out=92,833,251 elapsed=171.0s

  [10515/20519] intraday_18650.csv.gz  in=335,243,482 out=92,833,996 elapsed=171.0s

  [10516/20519] intraday_18651.csv.gz  in=335,243,881 out=92,834,395 elapsed=171.0s

  [10517/20519] intraday_18652.csv.gz  in=335,244,337 out=92,834,851 elapsed=171.0s

  [10518/20519] intraday_18653.csv.gz  in=335,244,639 out=92,835,153 elapsed=171.0s

  [10519/20519] intraday_1865.csv.gz  in=335,255,928 out=92,835,153 elapsed=171.0s

  [10520/20519] intraday_18655.csv.gz  in=335,256,557 out=92,835,782 elapsed=171.0s

  [10521/20519] intraday_18658.csv.gz  in=335,256,893 out=92,836,118 elapsed=171.0s

  [10522/20519] intraday_18657.csv.gz  in=335,257,276 out=92,836,501 elapsed=171.0s

  [10523/20519] intraday_18659.csv.gz  in=335,257,573 out=92,836,798 elapsed=171.0s

  [10524/20519] intraday_18660.csv.gz  in=335,257,982 out=92,837,207 elapsed=171.0s

  [10525/20519] intraday_18656.csv.gz  in=335,268,529 out=92,846,029 elapsed=171.0s

  [10526/20519] intraday_18654.csv.gz  in=335,297,806 out=92,866,290 elapsed=171.0s

  [10527/20519] intraday_18662.csv.gz  in=335,298,120 out=92,866,604 elapsed=171.0s

  [10528/20519] intraday_18661.csv.gz  in=335,298,655 out=92,867,139 elapsed=171.0s

  [10529/20519] intraday_18663.csv.gz  in=335,299,073 out=92,867,557 elapsed=171.1s

  [10530/20519] intraday_1866.csv.gz  in=335,323,332 out=92,867,557 elapsed=171.1s

  [10531/20519] intraday_18664.csv.gz  in=335,339,368 out=92,883,593 elapsed=171.1s

  [10532/20519] intraday_18665.csv.gz  in=335,353,520 out=92,897,745 elapsed=171.1s

  [10533/20519] intraday_18667.csv.gz  in=335,365,588 out=92,909,813 elapsed=171.1s

  [10534/20519] intraday_18666.csv.gz  in=335,378,331 out=92,922,556 elapsed=171.1s

  [10535/20519] intraday_18668.csv.gz  in=335,391,701 out=92,935,926 elapsed=171.2s

  [10536/20519] intraday_1867.csv.gz  in=335,401,549 out=92,935,926 elapsed=171.2s

  [10537/20519] intraday_18669.csv.gz  in=335,415,240 out=92,949,617 elapsed=171.2s

  [10538/20519] intraday_18671.csv.gz  in=335,427,721 out=92,962,098 elapsed=171.2s

  [10539/20519] intraday_18672.csv.gz  in=335,441,920 out=92,976,297 elapsed=171.2s

  [10540/20519] intraday_18673.csv.gz  in=335,456,466 out=92,990,843 elapsed=171.2s

  [10541/20519] intraday_18670.csv.gz  in=335,469,545 out=93,003,922 elapsed=171.2s

  [10542/20519] intraday_18674.csv.gz  in=335,479,865 out=93,014,242 elapsed=171.2s

  [10543/20519] intraday_18675.csv.gz  in=335,492,603 out=93,026,980 elapsed=171.3s

  [10544/20519] intraday_18678.csv.gz  in=335,503,862 out=93,038,239 elapsed=171.3s

  [10545/20519] intraday_18677.csv.gz  in=335,515,344 out=93,049,721 elapsed=171.3s

  [10546/20519] intraday_18676.csv.gz  in=335,529,561 out=93,063,938 elapsed=171.3s

  [10547/20519] intraday_18679.csv.gz  in=335,540,305 out=93,074,682 elapsed=171.3s

  [10548/20519] intraday_1868.csv.gz  in=335,551,784 out=93,074,682 elapsed=171.3s

  [10549/20519] intraday_18681.csv.gz  in=335,564,124 out=93,087,022 elapsed=171.3s

  [10550/20519] intraday_18680.csv.gz  in=335,579,100 out=93,101,998 elapsed=171.3s

  [10551/20519] intraday_18682.csv.gz  in=335,590,087 out=93,112,985 elapsed=171.3s

  [10552/20519] intraday_18683.csv.gz  in=335,601,787 out=93,124,685 elapsed=171.4s

  [10553/20519] intraday_18684.csv.gz  in=335,615,272 out=93,138,170 elapsed=171.4s

  [10554/20519] intraday_18685.csv.gz  in=335,627,932 out=93,150,830 elapsed=171.4s

  [10555/20519] intraday_18687.csv.gz  in=335,638,085 out=93,160,983 elapsed=171.4s

  [10556/20519] intraday_18686.csv.gz  in=335,651,124 out=93,174,022 elapsed=171.4s

  [10557/20519] intraday_18688.csv.gz  in=335,663,680 out=93,186,578 elapsed=171.4s

  [10558/20519] intraday_1869.csv.gz  in=335,674,382 out=93,186,578 elapsed=171.4s

  [10559/20519] intraday_18689.csv.gz  in=335,686,271 out=93,198,467 elapsed=171.4s

  [10560/20519] intraday_18692.csv.gz  in=335,698,441 out=93,210,637 elapsed=171.6s

  [10561/20519] intraday_18691.csv.gz  in=335,710,716 out=93,222,912 elapsed=171.6s

  [10562/20519] intraday_18690.csv.gz  in=335,722,936 out=93,235,132 elapsed=171.6s

  [10563/20519] intraday_18693.csv.gz  in=335,736,699 out=93,248,895 elapsed=171.6s

  [10564/20519] intraday_18694.csv.gz  in=335,749,337 out=93,261,533 elapsed=171.6s

  [10565/20519] intraday_18695.csv.gz  in=335,761,194 out=93,273,390 elapsed=171.6s

  [10566/20519] intraday_18697.csv.gz  in=335,773,038 out=93,285,234 elapsed=171.7s

  [10567/20519] intraday_18696.csv.gz  in=335,785,709 out=93,297,905 elapsed=171.7s

  [10568/20519] intraday_18698.csv.gz  in=335,798,232 out=93,310,428 elapsed=171.7s

  [10569/20519] intraday_18699.csv.gz  in=335,810,821 out=93,323,017 elapsed=171.7s

  [10570/20519] intraday_1870.csv.gz  in=335,823,975 out=93,323,017 elapsed=171.7s

  [10571/20519] intraday_18701.csv.gz  in=335,835,307 out=93,334,349 elapsed=171.7s

  [10572/20519] intraday_18700.csv.gz  in=335,845,619 out=93,344,661 elapsed=171.7s

  [10573/20519] intraday_18703.csv.gz  in=335,856,520 out=93,355,562 elapsed=171.7s

  [10574/20519] intraday_18702.csv.gz  in=335,867,295 out=93,366,337 elapsed=171.8s

  [10575/20519] intraday_18704.csv.gz  in=335,879,511 out=93,378,553 elapsed=171.8s

  [10576/20519] intraday_18705.csv.gz  in=335,891,161 out=93,390,203 elapsed=171.8s

  [10577/20519] intraday_18706.csv.gz  in=335,904,828 out=93,403,870 elapsed=171.8s

  [10578/20519] intraday_18707.csv.gz  in=335,919,434 out=93,418,476 elapsed=171.8s

  [10579/20519] intraday_18708.csv.gz  in=335,930,567 out=93,429,609 elapsed=171.8s

  [10580/20519] intraday_1871.csv.gz  in=335,941,158 out=93,429,609 elapsed=171.8s

  [10581/20519] intraday_18709.csv.gz  in=335,952,420 out=93,440,871 elapsed=171.8s

  [10582/20519] intraday_18710.csv.gz  in=335,965,593 out=93,454,044 elapsed=171.8s

  [10583/20519] intraday_18711.csv.gz  in=335,978,092 out=93,466,543 elapsed=171.9s

  [10584/20519] intraday_18713.csv.gz  in=335,988,803 out=93,477,254 elapsed=171.9s

  [10585/20519] intraday_18715.csv.gz  in=336,001,588 out=93,490,039 elapsed=171.9s

  [10586/20519] intraday_18714.csv.gz  in=336,013,825 out=93,502,276 elapsed=171.9s

  [10587/20519] intraday_18712.csv.gz  in=336,027,317 out=93,515,768 elapsed=171.9s

  [10588/20519] intraday_18716.csv.gz  in=336,041,051 out=93,529,502 elapsed=171.9s

  [10589/20519] intraday_18719.csv.gz  in=336,051,039 out=93,539,490 elapsed=171.9s

  [10590/20519] intraday_18717.csv.gz  in=336,065,920 out=93,554,371 elapsed=171.9s

  [10591/20519] intraday_18718.csv.gz  in=336,078,429 out=93,566,880 elapsed=172.0s

  [10592/20519] intraday_1872.csv.gz  in=336,091,615 out=93,566,880 elapsed=172.0s

  [10593/20519] intraday_18720.csv.gz  in=336,103,381 out=93,578,646 elapsed=172.0s

  [10594/20519] intraday_18722.csv.gz  in=336,116,570 out=93,591,835 elapsed=172.0s

  [10595/20519] intraday_18723.csv.gz  in=336,130,009 out=93,605,274 elapsed=172.0s

  [10596/20519] intraday_18721.csv.gz  in=336,142,702 out=93,617,967 elapsed=172.0s

  [10597/20519] intraday_18724.csv.gz  in=336,152,928 out=93,628,193 elapsed=172.0s

  [10598/20519] intraday_18725.csv.gz  in=336,165,515 out=93,640,780 elapsed=172.1s

  [10599/20519] intraday_18727.csv.gz  in=336,180,489 out=93,655,754 elapsed=172.1s

  [10600/20519] intraday_18728.csv.gz  in=336,192,508 out=93,667,773 elapsed=172.1s

  [10601/20519] intraday_18726.csv.gz  in=336,203,286 out=93,678,551 elapsed=172.1s

  [10602/20519] intraday_18729.csv.gz  in=336,217,073 out=93,692,338 elapsed=172.1s

  [10603/20519] intraday_1873.csv.gz  in=336,227,797 out=93,692,338 elapsed=172.1s

  [10604/20519] intraday_18732.csv.gz  in=336,236,973 out=93,701,514 elapsed=172.2s

  [10605/20519] intraday_18731.csv.gz  in=336,249,595 out=93,714,136 elapsed=172.2s

  [10606/20519] intraday_18733.csv.gz  in=336,262,509 out=93,727,050 elapsed=172.2s

  [10607/20519] intraday_18730.csv.gz  in=336,275,914 out=93,740,455 elapsed=172.2s

  [10608/20519] intraday_18735.csv.gz  in=336,287,894 out=93,752,435 elapsed=172.3s

  [10609/20519] intraday_18734.csv.gz  in=336,301,715 out=93,766,256 elapsed=172.3s

  [10610/20519] intraday_18736.csv.gz  in=336,335,227 out=93,797,062 elapsed=172.3s

  [10611/20519] intraday_18738.csv.gz  in=336,345,802 out=93,807,637 elapsed=172.3s

  [10612/20519] intraday_18739.csv.gz  in=336,359,453 out=93,821,288 elapsed=172.3s

  [10613/20519] intraday_1874.csv.gz  in=336,370,752 out=93,821,288 elapsed=172.3s

  [10614/20519] intraday_18737.csv.gz  in=336,382,243 out=93,832,779 elapsed=172.3s

  [10615/20519] intraday_18740.csv.gz  in=336,394,558 out=93,845,094 elapsed=172.4s

  [10616/20519] intraday_18742.csv.gz  in=336,405,352 out=93,855,888 elapsed=172.4s

  [10617/20519] intraday_18741.csv.gz  in=336,418,123 out=93,868,659 elapsed=172.4s

  [10618/20519] intraday_18743.csv.gz  in=336,428,595 out=93,879,131 elapsed=172.4s

  [10619/20519] intraday_18744.csv.gz  in=336,442,786 out=93,893,322 elapsed=172.4s

  [10620/20519] intraday_18746.csv.gz  in=336,456,009 out=93,906,545 elapsed=172.4s

  [10621/20519] intraday_18747.csv.gz  in=336,470,790 out=93,921,326 elapsed=172.5s

  [10622/20519] intraday_18745.csv.gz  in=336,485,787 out=93,936,323 elapsed=172.5s

  [10623/20519] intraday_18748.csv.gz  in=336,497,963 out=93,948,499 elapsed=172.5s

  [10624/20519] intraday_18749.csv.gz  in=336,513,255 out=93,963,791 elapsed=172.5s

  [10625/20519] intraday_1875.csv.gz  in=336,524,666 out=93,963,791 elapsed=172.5s

  [10626/20519] intraday_18750.csv.gz  in=336,535,206 out=93,974,331 elapsed=172.5s

  [10627/20519] intraday_18752.csv.gz  in=336,545,516 out=93,984,641 elapsed=172.5s

  [10628/20519] intraday_18751.csv.gz  in=336,560,877 out=94,000,002 elapsed=172.5s

  [10629/20519] intraday_18753.csv.gz  in=336,572,906 out=94,012,031 elapsed=172.5s

  [10630/20519] intraday_18754.csv.gz  in=336,585,639 out=94,024,764 elapsed=172.6s

  [10631/20519] intraday_18755.csv.gz  in=336,597,405 out=94,036,530 elapsed=172.6s

  [10632/20519] intraday_18756.csv.gz  in=336,610,520 out=94,049,645 elapsed=172.6s

  [10633/20519] intraday_18757.csv.gz  in=336,623,658 out=94,062,783 elapsed=172.6s

  [10634/20519] intraday_18758.csv.gz  in=336,637,272 out=94,076,397 elapsed=172.6s

  [10635/20519] intraday_18759.csv.gz  in=336,648,681 out=94,087,806 elapsed=172.6s

  [10636/20519] intraday_1876.csv.gz  in=336,661,845 out=94,087,806 elapsed=172.7s

  [10637/20519] intraday_18760.csv.gz  in=336,672,147 out=94,098,108 elapsed=172.7s

  [10638/20519] intraday_18761.csv.gz  in=336,684,478 out=94,110,439 elapsed=172.7s

  [10639/20519] intraday_18762.csv.gz  in=336,696,730 out=94,122,691 elapsed=172.7s

  [10640/20519] intraday_18763.csv.gz  in=336,710,027 out=94,135,988 elapsed=172.7s

  [10641/20519] intraday_18764.csv.gz  in=336,723,983 out=94,149,944 elapsed=172.7s

  [10642/20519] intraday_18765.csv.gz  in=336,736,855 out=94,162,816 elapsed=172.7s

  [10643/20519] intraday_18767.csv.gz  in=336,749,837 out=94,175,798 elapsed=172.8s

  [10644/20519] intraday_18768.csv.gz  in=336,762,168 out=94,188,129 elapsed=172.8s

  [10645/20519] intraday_18766.csv.gz  in=336,773,140 out=94,199,101 elapsed=172.8s

  [10646/20519] intraday_18769.csv.gz  in=336,784,443 out=94,210,404 elapsed=172.8s

  [10647/20519] intraday_1877.csv.gz  in=336,796,306 out=94,210,404 elapsed=172.8s

  [10648/20519] intraday_18770.csv.gz  in=336,809,928 out=94,224,026 elapsed=172.8s

  [10649/20519] intraday_18773.csv.gz  in=336,823,954 out=94,238,052 elapsed=172.8s

  [10650/20519] intraday_18771.csv.gz  in=336,840,409 out=94,254,507 elapsed=172.8s

  [10651/20519] intraday_18774.csv.gz  in=336,853,536 out=94,267,634 elapsed=172.9s

  [10652/20519] intraday_18772.csv.gz  in=336,869,981 out=94,284,079 elapsed=172.9s

  [10653/20519] intraday_18776.csv.gz  in=336,883,975 out=94,298,073 elapsed=172.9s

  [10654/20519] intraday_18778.csv.gz  in=336,902,025 out=94,316,123 elapsed=172.9s

  [10655/20519] intraday_18777.csv.gz  in=336,918,048 out=94,332,146 elapsed=172.9s

  [10656/20519] intraday_18775.csv.gz  in=336,959,877 out=94,369,601 elapsed=173.0s

  [10657/20519] intraday_1878.csv.gz  in=336,971,533 out=94,369,601 elapsed=173.0s

  [10658/20519] intraday_18779.csv.gz  in=336,986,189 out=94,384,257 elapsed=173.0s

  [10659/20519] intraday_18782.csv.gz  in=336,999,174 out=94,397,242 elapsed=173.0s

  [10660/20519] intraday_18781.csv.gz  in=337,013,105 out=94,411,173 elapsed=173.0s

  [10661/20519] intraday_18780.csv.gz  in=337,028,278 out=94,426,346 elapsed=173.0s

  [10662/20519] intraday_18783.csv.gz  in=337,038,006 out=94,436,074 elapsed=173.0s

  [10663/20519] intraday_18784.csv.gz  in=337,051,046 out=94,449,114 elapsed=173.0s

  [10664/20519] intraday_18785.csv.gz  in=337,062,197 out=94,460,265 elapsed=173.1s

  [10665/20519] intraday_18786.csv.gz  in=337,075,002 out=94,473,070 elapsed=173.1s

  [10666/20519] intraday_18788.csv.gz  in=337,089,569 out=94,487,637 elapsed=173.1s

  [10667/20519] intraday_18789.csv.gz  in=337,101,591 out=94,499,659 elapsed=173.1s

  [10668/20519] intraday_1879.csv.gz  in=337,111,280 out=94,499,659 elapsed=173.1s

  [10669/20519] intraday_18787.csv.gz  in=337,124,488 out=94,512,867 elapsed=173.1s

  [10670/20519] intraday_18790.csv.gz  in=337,136,216 out=94,524,595 elapsed=173.1s

  [10671/20519] intraday_18791.csv.gz  in=337,150,230 out=94,538,609 elapsed=173.2s

  [10672/20519] intraday_18792.csv.gz  in=337,162,222 out=94,550,601 elapsed=173.2s

  [10673/20519] intraday_18794.csv.gz  in=337,176,208 out=94,564,587 elapsed=173.2s

  [10674/20519] intraday_18793.csv.gz  in=337,190,508 out=94,578,887 elapsed=173.2s

  [10675/20519] intraday_18795.csv.gz  in=337,204,757 out=94,593,136 elapsed=173.2s

  [10676/20519] intraday_18796.csv.gz  in=337,218,328 out=94,606,707 elapsed=173.2s

  [10677/20519] intraday_18797.csv.gz  in=337,230,943 out=94,619,322 elapsed=173.2s

  [10678/20519] intraday_18798.csv.gz  in=337,243,649 out=94,632,028 elapsed=173.3s

  [10679/20519] intraday_18799.csv.gz  in=337,257,870 out=94,646,249 elapsed=173.3s

  [10680/20519] intraday_1880.csv.gz  in=337,275,709 out=94,646,249 elapsed=173.3s

  [10681/20519] intraday_18800.csv.gz  in=337,286,519 out=94,657,059 elapsed=173.3s

  [10682/20519] intraday_18801.csv.gz  in=337,299,351 out=94,669,891 elapsed=173.3s

  [10683/20519] intraday_18802.csv.gz  in=337,311,016 out=94,681,556 elapsed=173.3s

  [10684/20519] intraday_18803.csv.gz  in=337,318,579 out=94,689,119 elapsed=173.3s

  [10685/20519] intraday_18805.csv.gz  in=337,321,016 out=94,691,556 elapsed=173.3s

  [10686/20519] intraday_18804.csv.gz  in=337,333,117 out=94,703,657 elapsed=173.4s

  [10687/20519] intraday_18806.csv.gz  in=337,349,951 out=94,720,491 elapsed=173.4s

  [10688/20519] intraday_18807.csv.gz  in=337,363,122 out=94,733,662 elapsed=173.4s

  [10689/20519] intraday_18808.csv.gz  in=337,376,186 out=94,746,726 elapsed=173.4s

  [10690/20519] intraday_1881.csv.gz  in=337,388,085 out=94,746,726 elapsed=173.4s

  [10691/20519] intraday_18809.csv.gz  in=337,400,579 out=94,759,220 elapsed=173.4s

  [10692/20519] intraday_18810.csv.gz  in=337,414,848 out=94,773,489 elapsed=173.4s

  [10693/20519] intraday_18811.csv.gz  in=337,429,471 out=94,788,112 elapsed=173.5s

  [10694/20519] intraday_18812.csv.gz  in=337,442,360 out=94,801,001 elapsed=173.5s

  [10695/20519] intraday_18814.csv.gz  in=337,457,593 out=94,816,234 elapsed=173.5s

  [10696/20519] intraday_18813.csv.gz  in=337,469,773 out=94,828,414 elapsed=173.5s

  [10697/20519] intraday_18815.csv.gz  in=337,482,367 out=94,841,008 elapsed=173.5s

  [10698/20519] intraday_18816.csv.gz  in=337,492,042 out=94,850,683 elapsed=173.5s

  [10699/20519] intraday_18817.csv.gz  in=337,510,898 out=94,868,797 elapsed=173.5s

  [10700/20519] intraday_1882.csv.gz  in=337,525,607 out=94,868,797 elapsed=173.6s

  [10701/20519] intraday_18818.csv.gz  in=337,552,151 out=94,894,268 elapsed=173.6s

  [10702/20519] intraday_18820.csv.gz  in=337,563,253 out=94,905,370 elapsed=173.6s

  [10703/20519] intraday_18819.csv.gz  in=337,575,663 out=94,917,780 elapsed=173.6s

  [10704/20519] intraday_18821.csv.gz  in=337,586,175 out=94,928,292 elapsed=173.6s

  [10705/20519] intraday_18822.csv.gz  in=337,602,068 out=94,944,185 elapsed=173.6s

  [10706/20519] intraday_18825.csv.gz  in=337,612,823 out=94,954,940 elapsed=173.6s

  [10707/20519] intraday_18824.csv.gz  in=337,623,698 out=94,965,815 elapsed=173.6s

  [10708/20519] intraday_18823.csv.gz  in=337,636,831 out=94,978,948 elapsed=173.7s

  [10709/20519] intraday_18826.csv.gz  in=337,649,836 out=94,991,953 elapsed=173.7s

  [10710/20519] intraday_18829.csv.gz  in=337,661,569 out=95,003,686 elapsed=173.7s

  [10711/20519] intraday_18827.csv.gz  in=337,674,273 out=95,016,390 elapsed=173.7s

  [10712/20519] intraday_18828.csv.gz  in=337,687,518 out=95,029,635 elapsed=173.7s

  [10713/20519] intraday_1883.csv.gz  in=337,699,235 out=95,029,635 elapsed=173.7s

  [10714/20519] intraday_18830.csv.gz  in=337,711,223 out=95,041,623 elapsed=173.7s

  [10715/20519] intraday_18832.csv.gz  in=337,722,258 out=95,052,658 elapsed=173.8s

  [10716/20519] intraday_18831.csv.gz  in=337,735,141 out=95,065,541 elapsed=173.8s

  [10717/20519] intraday_18833.csv.gz  in=337,745,426 out=95,075,826 elapsed=173.8s

  [10718/20519] intraday_18835.csv.gz  in=337,757,994 out=95,088,394 elapsed=173.8s

  [10719/20519] intraday_18834.csv.gz  in=337,772,082 out=95,102,482 elapsed=173.8s

  [10720/20519] intraday_18837.csv.gz  in=337,783,722 out=95,114,122 elapsed=173.8s

  [10721/20519] intraday_18838.csv.gz  in=337,795,697 out=95,126,097 elapsed=173.8s

  [10722/20519] intraday_18836.csv.gz  in=337,808,625 out=95,139,025 elapsed=173.8s

  [10723/20519] intraday_18839.csv.gz  in=337,821,357 out=95,151,757 elapsed=173.8s

  [10724/20519] intraday_1884.csv.gz  in=337,835,232 out=95,151,757 elapsed=173.8s

  [10725/20519] intraday_18841.csv.gz  in=337,848,902 out=95,165,427 elapsed=173.9s

  [10726/20519] intraday_18843.csv.gz  in=337,860,035 out=95,176,560 elapsed=173.9s

  [10727/20519] intraday_18842.csv.gz  in=337,870,147 out=95,186,672 elapsed=173.9s

  [10728/20519] intraday_18840.csv.gz  in=337,889,406 out=95,205,931 elapsed=173.9s

  [10729/20519] intraday_18845.csv.gz  in=337,899,687 out=95,216,212 elapsed=173.9s

  [10730/20519] intraday_18844.csv.gz  in=337,911,651 out=95,228,176 elapsed=173.9s

  [10731/20519] intraday_18846.csv.gz  in=337,924,377 out=95,240,902 elapsed=173.9s

  [10732/20519] intraday_18847.csv.gz  in=337,944,903 out=95,260,306 elapsed=174.0s

  [10733/20519] intraday_18849.csv.gz  in=337,958,846 out=95,274,249 elapsed=174.0s

  [10734/20519] intraday_1885.csv.gz  in=337,972,390 out=95,274,249 elapsed=174.0s

  [10735/20519] intraday_18848.csv.gz  in=337,984,761 out=95,286,620 elapsed=174.0s

  [10736/20519] intraday_18850.csv.gz  in=337,995,824 out=95,297,683 elapsed=174.0s

  [10737/20519] intraday_18852.csv.gz  in=338,008,121 out=95,309,980 elapsed=174.0s

  [10738/20519] intraday_18851.csv.gz  in=338,019,852 out=95,321,711 elapsed=174.0s

  [10739/20519] intraday_18853.csv.gz  in=338,032,804 out=95,334,663 elapsed=174.0s

  [10740/20519] intraday_18855.csv.gz  in=338,044,776 out=95,346,635 elapsed=174.1s

  [10741/20519] intraday_18856.csv.gz  in=338,055,323 out=95,357,182 elapsed=174.1s

  [10742/20519] intraday_18854.csv.gz  in=338,068,686 out=95,370,545 elapsed=174.1s

  [10743/20519] intraday_18857.csv.gz  in=338,082,271 out=95,384,130 elapsed=174.1s

  [10744/20519] intraday_18858.csv.gz  in=338,097,331 out=95,399,190 elapsed=174.1s

  [10745/20519] intraday_1886.csv.gz  in=338,110,345 out=95,399,190 elapsed=174.1s

  [10746/20519] intraday_18859.csv.gz  in=338,123,628 out=95,412,473 elapsed=174.1s

  [10747/20519] intraday_18860.csv.gz  in=338,137,151 out=95,425,996 elapsed=174.1s

  [10748/20519] intraday_18862.csv.gz  in=338,147,544 out=95,436,389 elapsed=174.2s

  [10749/20519] intraday_18861.csv.gz  in=338,157,917 out=95,446,762 elapsed=174.2s

  [10750/20519] intraday_18863.csv.gz  in=338,170,757 out=95,459,602 elapsed=174.2s

  [10751/20519] intraday_18865.csv.gz  in=338,182,798 out=95,471,643 elapsed=174.2s

  [10752/20519] intraday_18867.csv.gz  in=338,194,855 out=95,483,700 elapsed=174.3s

  [10753/20519] intraday_18864.csv.gz  in=338,208,503 out=95,497,348 elapsed=174.3s

  [10754/20519] intraday_18866.csv.gz  in=338,220,582 out=95,509,427 elapsed=174.3s

  [10755/20519] intraday_18868.csv.gz  in=338,234,832 out=95,523,128 elapsed=174.3s

  [10756/20519] intraday_1887.csv.gz  in=338,247,579 out=95,523,128 elapsed=174.3s

  [10757/20519] intraday_18869.csv.gz  in=338,258,683 out=95,534,232 elapsed=174.3s

  [10758/20519] intraday_18870.csv.gz  in=338,273,123 out=95,548,672 elapsed=174.3s

  [10759/20519] intraday_18871.csv.gz  in=338,286,067 out=95,561,616 elapsed=174.3s

  [10760/20519] intraday_18872.csv.gz  in=338,299,945 out=95,575,494 elapsed=174.4s

  [10761/20519] intraday_18873.csv.gz  in=338,313,448 out=95,588,997 elapsed=174.4s

  [10762/20519] intraday_18874.csv.gz  in=338,323,728 out=95,599,277 elapsed=174.4s

  [10763/20519] intraday_18875.csv.gz  in=338,336,209 out=95,611,691 elapsed=174.4s

  [10764/20519] intraday_18877.csv.gz  in=338,347,230 out=95,622,712 elapsed=174.4s

  [10765/20519] intraday_18876.csv.gz  in=338,360,115 out=95,635,597 elapsed=174.4s

  [10766/20519] intraday_18879.csv.gz  in=338,371,451 out=95,646,933 elapsed=174.4s

  [10767/20519] intraday_18878.csv.gz  in=338,384,358 out=95,659,840 elapsed=174.4s

  [10768/20519] intraday_1888.csv.gz  in=338,396,602 out=95,659,840 elapsed=174.4s

  [10769/20519] intraday_18880.csv.gz  in=338,406,765 out=95,670,003 elapsed=174.4s

  [10770/20519] intraday_18882.csv.gz  in=338,420,222 out=95,683,460 elapsed=174.4s

  [10771/20519] intraday_18881.csv.gz  in=338,432,528 out=95,695,766 elapsed=174.4s

  [10772/20519] intraday_18884.csv.gz  in=338,444,743 out=95,707,981 elapsed=174.4s

  [10773/20519] intraday_18883.csv.gz  in=338,455,723 out=95,718,961 elapsed=174.4s

  [10774/20519] intraday_18885.csv.gz  in=338,466,392 out=95,729,630 elapsed=174.4s

  [10775/20519] intraday_18886.csv.gz  in=338,478,869 out=95,742,107 elapsed=174.4s

  [10776/20519] intraday_18887.csv.gz  in=338,492,030 out=95,755,268 elapsed=174.4s

  [10777/20519] intraday_18888.csv.gz  in=338,510,040 out=95,773,278 elapsed=174.4s

  [10778/20519] intraday_1889.csv.gz  in=338,521,362 out=95,773,278 elapsed=174.4s

  [10779/20519] intraday_18889.csv.gz  in=338,533,574 out=95,785,490 elapsed=174.5s

  [10780/20519] intraday_18891.csv.gz  in=338,543,644 out=95,795,560 elapsed=174.5s

  [10781/20519] intraday_18890.csv.gz  in=338,557,095 out=95,809,011 elapsed=174.5s

  [10782/20519] intraday_18893.csv.gz  in=338,568,088 out=95,820,004 elapsed=174.5s

  [10783/20519] intraday_18892.csv.gz  in=338,583,828 out=95,835,744 elapsed=174.5s

  [10784/20519] intraday_18894.csv.gz  in=338,599,276 out=95,851,192 elapsed=174.5s

  [10785/20519] intraday_18895.csv.gz  in=338,609,176 out=95,861,092 elapsed=174.5s

  [10786/20519] intraday_18896.csv.gz  in=338,623,697 out=95,875,613 elapsed=174.6s

  [10787/20519] intraday_18897.csv.gz  in=338,635,424 out=95,887,340 elapsed=174.6s

  [10788/20519] intraday_18898.csv.gz  in=338,647,214 out=95,899,130 elapsed=174.6s

  [10789/20519] intraday_18899.csv.gz  in=338,660,153 out=95,912,069 elapsed=174.6s

  [10790/20519] intraday_1890.csv.gz  in=338,671,003 out=95,912,069 elapsed=174.6s

  [10791/20519] intraday_18900.csv.gz  in=338,684,647 out=95,925,713 elapsed=174.6s

  [10792/20519] intraday_18902.csv.gz  in=338,694,463 out=95,935,529 elapsed=174.6s

  [10793/20519] intraday_18901.csv.gz  in=338,707,753 out=95,948,819 elapsed=174.6s

  [10794/20519] intraday_18903.csv.gz  in=338,719,635 out=95,960,701 elapsed=174.6s

  [10795/20519] intraday_18905.csv.gz  in=338,731,246 out=95,972,312 elapsed=174.7s

  [10796/20519] intraday_18904.csv.gz  in=338,743,017 out=95,984,083 elapsed=174.7s

  [10797/20519] intraday_18906.csv.gz  in=338,759,478 out=96,000,544 elapsed=174.7s

  [10798/20519] intraday_18907.csv.gz  in=338,774,425 out=96,015,491 elapsed=174.7s

  [10799/20519] intraday_18908.csv.gz  in=338,785,880 out=96,026,946 elapsed=174.7s

  [10800/20519] intraday_18909.csv.gz  in=338,797,040 out=96,038,106 elapsed=174.7s

  [10801/20519] intraday_1891.csv.gz  in=338,808,669 out=96,038,106 elapsed=174.7s

  [10802/20519] intraday_18910.csv.gz  in=338,822,944 out=96,052,381 elapsed=174.7s

  [10803/20519] intraday_18911.csv.gz  in=338,834,667 out=96,064,104 elapsed=174.7s

  [10804/20519] intraday_18913.csv.gz  in=338,850,450 out=96,079,887 elapsed=174.8s

  [10805/20519] intraday_18912.csv.gz  in=338,863,076 out=96,092,513 elapsed=174.8s

  [10806/20519] intraday_18914.csv.gz  in=338,878,226 out=96,107,663 elapsed=174.8s

  [10807/20519] intraday_18915.csv.gz  in=338,892,506 out=96,121,943 elapsed=174.8s

  [10808/20519] intraday_18916.csv.gz  in=338,906,240 out=96,135,677 elapsed=174.8s

  [10809/20519] intraday_18918.csv.gz  in=338,918,112 out=96,147,549 elapsed=174.8s

  [10810/20519] intraday_18917.csv.gz  in=338,942,807 out=96,171,214 elapsed=174.9s

  [10811/20519] intraday_1892.csv.gz  in=338,955,330 out=96,171,214 elapsed=174.9s

  [10812/20519] intraday_18919.csv.gz  in=338,982,581 out=96,196,901 elapsed=174.9s

  [10813/20519] intraday_18920.csv.gz  in=338,996,564 out=96,210,884 elapsed=174.9s

  [10814/20519] intraday_18922.csv.gz  in=339,012,169 out=96,226,489 elapsed=174.9s

  [10815/20519] intraday_18923.csv.gz  in=339,025,606 out=96,239,926 elapsed=174.9s

  [10816/20519] intraday_18921.csv.gz  in=339,043,721 out=96,258,041 elapsed=175.0s

  [10817/20519] intraday_18924.csv.gz  in=339,057,908 out=96,272,228 elapsed=175.0s

  [10818/20519] intraday_18925.csv.gz  in=339,070,972 out=96,285,292 elapsed=175.0s

  [10819/20519] intraday_18926.csv.gz  in=339,080,905 out=96,295,225 elapsed=175.0s

  [10820/20519] intraday_18927.csv.gz  in=339,093,603 out=96,307,923 elapsed=175.0s

  [10821/20519] intraday_18928.csv.gz  in=339,106,348 out=96,320,668 elapsed=175.0s

  [10822/20519] intraday_18929.csv.gz  in=339,117,096 out=96,331,416 elapsed=175.0s

  [10823/20519] intraday_1893.csv.gz  in=339,128,339 out=96,331,416 elapsed=175.0s

  [10824/20519] intraday_18930.csv.gz  in=339,141,489 out=96,344,566 elapsed=175.1s

  [10825/20519] intraday_18931.csv.gz  in=339,155,632 out=96,358,709 elapsed=175.1s

  [10826/20519] intraday_18932.csv.gz  in=339,168,325 out=96,371,402 elapsed=175.1s

  [10827/20519] intraday_18933.csv.gz  in=339,179,333 out=96,382,410 elapsed=175.1s

  [10828/20519] intraday_18934.csv.gz  in=339,192,919 out=96,395,996 elapsed=175.1s

  [10829/20519] intraday_18935.csv.gz  in=339,205,169 out=96,408,246 elapsed=175.1s

  [10830/20519] intraday_18937.csv.gz  in=339,219,094 out=96,422,171 elapsed=175.1s

  [10831/20519] intraday_18936.csv.gz  in=339,244,465 out=96,446,279 elapsed=175.2s

  [10832/20519] intraday_18938.csv.gz  in=339,259,194 out=96,461,008 elapsed=175.2s

  [10833/20519] intraday_1894.csv.gz  in=339,270,995 out=96,461,008 elapsed=175.2s

  [10834/20519] intraday_18939.csv.gz  in=339,284,255 out=96,474,268 elapsed=175.2s

  [10835/20519] intraday_18940.csv.gz  in=339,296,252 out=96,486,265 elapsed=175.2s

  [10836/20519] intraday_18942.csv.gz  in=339,309,625 out=96,499,638 elapsed=175.2s

  [10837/20519] intraday_18941.csv.gz  in=339,322,219 out=96,512,232 elapsed=175.3s

  [10838/20519] intraday_18943.csv.gz  in=339,332,412 out=96,522,425 elapsed=175.3s

  [10839/20519] intraday_18945.csv.gz  in=339,343,261 out=96,533,274 elapsed=175.3s

  [10840/20519] intraday_18944.csv.gz  in=339,359,272 out=96,549,285 elapsed=175.3s

  [10841/20519] intraday_18947.csv.gz  in=339,371,166 out=96,561,179 elapsed=175.3s

  [10842/20519] intraday_18948.csv.gz  in=339,372,248 out=96,562,261 elapsed=175.3s

  [10843/20519] intraday_18946.csv.gz  in=339,379,336 out=96,569,349 elapsed=175.3s

  [10844/20519] intraday_18949.csv.gz  in=339,395,776 out=96,585,789 elapsed=175.4s

  [10845/20519] intraday_1895.csv.gz  in=339,408,008 out=96,585,789 elapsed=175.4s

  [10846/20519] intraday_18950.csv.gz  in=339,421,986 out=96,599,767 elapsed=175.4s

  [10847/20519] intraday_18951.csv.gz  in=339,436,434 out=96,614,215 elapsed=175.4s

  [10848/20519] intraday_18953.csv.gz  in=339,450,059 out=96,627,840 elapsed=175.4s

  [10849/20519] intraday_18954.csv.gz  in=339,465,202 out=96,642,983 elapsed=175.4s

  [10850/20519] intraday_18952.csv.gz  in=339,475,770 out=96,653,551 elapsed=175.4s

  [10851/20519] intraday_18955.csv.gz  in=339,488,481 out=96,665,975 elapsed=175.4s

  [10852/20519] intraday_18956.csv.gz  in=339,501,086 out=96,678,580 elapsed=175.5s

  [10853/20519] intraday_18958.csv.gz  in=339,513,967 out=96,691,461 elapsed=175.5s

  [10854/20519] intraday_1896.csv.gz  in=339,525,836 out=96,691,461 elapsed=175.5s

  [10855/20519] intraday_18959.csv.gz  in=339,535,604 out=96,701,229 elapsed=175.5s

  [10856/20519] intraday_18957.csv.gz  in=339,550,553 out=96,716,178 elapsed=175.5s

  [10857/20519] intraday_18960.csv.gz  in=339,563,469 out=96,729,094 elapsed=175.5s

  [10858/20519] intraday_18963.csv.gz  in=339,574,418 out=96,740,043 elapsed=175.6s

  [10859/20519] intraday_18962.csv.gz  in=339,585,588 out=96,751,213 elapsed=175.6s

  [10860/20519] intraday_18964.csv.gz  in=339,595,463 out=96,761,088 elapsed=175.6s

  [10861/20519] intraday_18961.csv.gz  in=339,610,303 out=96,775,928 elapsed=175.6s

  [10862/20519] intraday_18965.csv.gz  in=339,627,670 out=96,793,295 elapsed=175.6s

  [10863/20519] intraday_18967.csv.gz  in=339,637,683 out=96,803,308 elapsed=175.6s

  [10864/20519] intraday_18966.csv.gz  in=339,651,066 out=96,816,691 elapsed=175.7s

  [10865/20519] intraday_18968.csv.gz  in=339,662,021 out=96,827,646 elapsed=175.7s

  [10866/20519] intraday_18969.csv.gz  in=339,675,790 out=96,841,415 elapsed=175.7s

  [10867/20519] intraday_1897.csv.gz  in=339,688,137 out=96,841,415 elapsed=175.7s

  [10868/20519] intraday_18970.csv.gz  in=339,701,316 out=96,854,594 elapsed=175.7s

  [10869/20519] intraday_18972.csv.gz  in=339,712,750 out=96,866,028 elapsed=175.7s

  [10870/20519] intraday_18973.csv.gz  in=339,725,411 out=96,878,689 elapsed=175.7s

  [10871/20519] intraday_18971.csv.gz  in=339,738,079 out=96,891,357 elapsed=175.7s

  [10872/20519] intraday_18974.csv.gz  in=339,749,980 out=96,903,258 elapsed=175.8s

  [10873/20519] intraday_18975.csv.gz  in=339,761,382 out=96,914,660 elapsed=175.8s

  [10874/20519] intraday_18976.csv.gz  in=339,771,930 out=96,925,208 elapsed=175.8s

  [10875/20519] intraday_18977.csv.gz  in=339,785,775 out=96,939,053 elapsed=175.8s

  [10876/20519] intraday_1898.csv.gz  in=339,797,956 out=96,939,053 elapsed=175.8s

  [10877/20519] intraday_18979.csv.gz  in=339,810,847 out=96,951,944 elapsed=175.8s

  [10878/20519] intraday_18978.csv.gz  in=339,825,242 out=96,966,339 elapsed=175.9s

  [10879/20519] intraday_18980.csv.gz  in=339,836,469 out=96,977,566 elapsed=175.9s

  [10880/20519] intraday_18981.csv.gz  in=339,848,492 out=96,989,589 elapsed=175.9s

  [10881/20519] intraday_18982.csv.gz  in=339,860,417 out=97,001,514 elapsed=175.9s

  [10882/20519] intraday_18985.csv.gz  in=339,871,572 out=97,012,669 elapsed=175.9s

  [10883/20519] intraday_18984.csv.gz  in=339,885,989 out=97,027,086 elapsed=175.9s

  [10884/20519] intraday_18983.csv.gz  in=339,900,016 out=97,041,113 elapsed=175.9s

  [10885/20519] intraday_18987.csv.gz  in=339,909,922 out=97,051,019 elapsed=175.9s

  [10886/20519] intraday_18986.csv.gz  in=339,920,735 out=97,061,832 elapsed=175.9s

  [10887/20519] intraday_18988.csv.gz  in=339,931,228 out=97,072,325 elapsed=176.0s

  [10888/20519] intraday_18990.csv.gz  in=339,943,434 out=97,084,531 elapsed=176.0s

  [10889/20519] intraday_18989.csv.gz  in=339,956,032 out=97,097,129 elapsed=176.0s

  [10890/20519] intraday_1899.csv.gz  in=339,981,756 out=97,097,129 elapsed=176.0s

  [10891/20519] intraday_18991.csv.gz  in=339,995,243 out=97,110,616 elapsed=176.0s

  [10892/20519] intraday_18994.csv.gz  in=340,006,899 out=97,122,272 elapsed=176.0s

  [10893/20519] intraday_18995.csv.gz  in=340,018,229 out=97,133,602 elapsed=176.1s

  [10894/20519] intraday_18993.csv.gz  in=340,030,161 out=97,145,534 elapsed=176.1s

  [10895/20519] intraday_18996.csv.gz  in=340,042,126 out=97,157,499 elapsed=176.1s

  [10896/20519] intraday_18992.csv.gz  in=340,062,548 out=97,177,921 elapsed=176.1s

  [10897/20519] intraday_18998.csv.gz  in=340,073,872 out=97,189,245 elapsed=176.1s

  [10898/20519] intraday_18997.csv.gz  in=340,088,354 out=97,203,727 elapsed=176.1s

  [10899/20519] intraday_18999.csv.gz  in=340,098,954 out=97,214,327 elapsed=176.1s

  [10900/20519] intraday_19000.csv.gz  in=340,112,662 out=97,228,035 elapsed=176.1s

  [10901/20519] intraday_1900.csv.gz  in=340,126,294 out=97,228,035 elapsed=176.1s

  [10902/20519] intraday_19002.csv.gz  in=340,138,754 out=97,240,495 elapsed=176.2s

  [10903/20519] intraday_19001.csv.gz  in=340,154,217 out=97,255,958 elapsed=176.2s

  [10904/20519] intraday_19003.csv.gz  in=340,168,361 out=97,270,102 elapsed=176.2s

  [10905/20519] intraday_19004.csv.gz  in=340,178,230 out=97,279,971 elapsed=176.2s

  [10906/20519] intraday_19005.csv.gz  in=340,188,534 out=97,290,275 elapsed=176.2s

  [10907/20519] intraday_19007.csv.gz  in=340,202,298 out=97,304,039 elapsed=176.3s

  [10908/20519] intraday_19006.csv.gz  in=340,214,569 out=97,316,310 elapsed=176.3s

  [10909/20519] intraday_19008.csv.gz  in=340,226,296 out=97,328,037 elapsed=176.3s

  [10910/20519] intraday_19009.csv.gz  in=340,238,374 out=97,340,115 elapsed=176.3s

  [10911/20519] intraday_19010.csv.gz  in=340,250,062 out=97,351,803 elapsed=176.3s

  [10912/20519] intraday_1901.csv.gz  in=340,264,892 out=97,351,803 elapsed=176.3s

  [10913/20519] intraday_19011.csv.gz  in=340,278,617 out=97,365,086 elapsed=176.4s

  [10914/20519] intraday_19014.csv.gz  in=340,292,225 out=97,378,694 elapsed=176.4s

  [10915/20519] intraday_19013.csv.gz  in=340,307,932 out=97,394,401 elapsed=176.4s

  [10916/20519] intraday_19012.csv.gz  in=340,318,590 out=97,405,059 elapsed=176.4s

  [10917/20519] intraday_19015.csv.gz  in=340,332,316 out=97,418,785 elapsed=176.4s

  [10918/20519] intraday_19018.csv.gz  in=340,344,170 out=97,430,639 elapsed=176.4s

  [10919/20519] intraday_19017.csv.gz  in=340,358,452 out=97,444,591 elapsed=176.4s

  [10920/20519] intraday_1902.csv.gz  in=340,370,206 out=97,444,591 elapsed=176.5s

  [10921/20519] intraday_19016.csv.gz  in=340,383,175 out=97,457,560 elapsed=176.5s

  [10922/20519] intraday_19019.csv.gz  in=340,397,191 out=97,471,576 elapsed=176.5s

  [10923/20519] intraday_19020.csv.gz  in=340,408,086 out=97,482,471 elapsed=176.5s

  [10924/20519] intraday_19021.csv.gz  in=340,420,409 out=97,494,794 elapsed=176.5s

  [10925/20519] intraday_19022.csv.gz  in=340,432,310 out=97,506,695 elapsed=176.5s

  [10926/20519] intraday_19023.csv.gz  in=340,443,271 out=97,517,656 elapsed=176.5s

  [10927/20519] intraday_19024.csv.gz  in=340,456,098 out=97,530,483 elapsed=176.5s

  [10928/20519] intraday_19025.csv.gz  in=340,469,012 out=97,543,397 elapsed=176.6s

  [10929/20519] intraday_19026.csv.gz  in=340,480,889 out=97,555,274 elapsed=176.6s

  [10930/20519] intraday_19027.csv.gz  in=340,493,330 out=97,567,715 elapsed=176.6s

  [10931/20519] intraday_19030.csv.gz  in=340,507,036 out=97,581,421 elapsed=176.6s

  [10932/20519] intraday_1903.csv.gz  in=340,530,403 out=97,581,421 elapsed=176.6s

  [10933/20519] intraday_19028.csv.gz  in=340,541,502 out=97,592,520 elapsed=176.6s

  [10934/20519] intraday_19029.csv.gz  in=340,554,242 out=97,605,260 elapsed=176.6s

  [10935/20519] intraday_19032.csv.gz  in=340,568,287 out=97,619,305 elapsed=176.7s

  [10936/20519] intraday_19034.csv.gz  in=340,580,133 out=97,631,151 elapsed=176.7s

  [10937/20519] intraday_19031.csv.gz  in=340,598,202 out=97,649,220 elapsed=176.7s

  [10938/20519] intraday_19033.csv.gz  in=340,615,970 out=97,666,988 elapsed=176.7s

  [10939/20519] intraday_19035.csv.gz  in=340,629,161 out=97,680,179 elapsed=176.7s

  [10940/20519] intraday_19037.csv.gz  in=340,644,953 out=97,695,971 elapsed=176.7s

  [10941/20519] intraday_19036.csv.gz  in=340,655,066 out=97,706,084 elapsed=176.8s

  [10942/20519] intraday_19038.csv.gz  in=340,666,800 out=97,717,818 elapsed=176.8s

  [10943/20519] intraday_19039.csv.gz  in=340,680,456 out=97,731,474 elapsed=176.8s

  [10944/20519] intraday_1904.csv.gz  in=340,693,126 out=97,731,474 elapsed=176.8s

  [10945/20519] intraday_19040.csv.gz  in=340,704,557 out=97,742,905 elapsed=176.8s

  [10946/20519] intraday_19041.csv.gz  in=340,716,500 out=97,754,848 elapsed=176.8s

  [10947/20519] intraday_19042.csv.gz  in=340,729,201 out=97,767,549 elapsed=176.8s

  [10948/20519] intraday_19043.csv.gz  in=340,741,399 out=97,779,747 elapsed=176.8s

  [10949/20519] intraday_19045.csv.gz  in=340,752,013 out=97,790,361 elapsed=176.9s

  [10950/20519] intraday_19046.csv.gz  in=340,763,720 out=97,802,068 elapsed=176.9s

  [10951/20519] intraday_19044.csv.gz  in=340,777,718 out=97,816,066 elapsed=176.9s

  [10952/20519] intraday_19047.csv.gz  in=340,789,479 out=97,827,827 elapsed=176.9s

  [10953/20519] intraday_19048.csv.gz  in=340,801,864 out=97,840,212 elapsed=176.9s

  [10954/20519] intraday_19049.csv.gz  in=340,813,374 out=97,851,722 elapsed=176.9s

  [10955/20519] intraday_19051.csv.gz  in=340,825,164 out=97,863,512 elapsed=176.9s

  [10956/20519] intraday_1905.csv.gz  in=340,845,412 out=97,863,512 elapsed=176.9s

  [10957/20519] intraday_19050.csv.gz  in=340,859,936 out=97,878,036 elapsed=176.9s

  [10958/20519] intraday_19052.csv.gz  in=340,871,313 out=97,889,413 elapsed=176.9s

  [10959/20519] intraday_19054.csv.gz  in=340,881,721 out=97,899,820 elapsed=177.0s

  [10960/20519] intraday_19053.csv.gz  in=340,895,953 out=97,914,052 elapsed=177.0s

  [10961/20519] intraday_19055.csv.gz  in=340,908,227 out=97,926,326 elapsed=177.0s

  [10962/20519] intraday_19056.csv.gz  in=340,923,391 out=97,941,490 elapsed=177.0s

  [10963/20519] intraday_19058.csv.gz  in=340,937,051 out=97,955,150 elapsed=177.0s

  [10964/20519] intraday_19057.csv.gz  in=340,952,854 out=97,970,953 elapsed=177.0s

  [10965/20519] intraday_19059.csv.gz  in=340,966,595 out=97,984,694 elapsed=177.0s

  [10966/20519] intraday_1906.csv.gz  in=340,979,563 out=97,984,694 elapsed=177.0s

  [10967/20519] intraday_19061.csv.gz  in=340,993,018 out=97,998,149 elapsed=177.0s

  [10968/20519] intraday_19060.csv.gz  in=341,006,940 out=98,012,071 elapsed=177.0s

  [10969/20519] intraday_19062.csv.gz  in=341,023,778 out=98,028,909 elapsed=177.1s

  [10970/20519] intraday_19063.csv.gz  in=341,037,515 out=98,042,646 elapsed=177.1s

  [10971/20519] intraday_19064.csv.gz  in=341,055,694 out=98,060,825 elapsed=177.1s

  [10972/20519] intraday_19065.csv.gz  in=341,070,027 out=98,075,158 elapsed=177.1s

  [10973/20519] intraday_19067.csv.gz  in=341,083,442 out=98,088,573 elapsed=177.1s

  [10974/20519] intraday_19066.csv.gz  in=341,098,097 out=98,103,228 elapsed=177.1s

  [10975/20519] intraday_19069.csv.gz  in=341,108,005 out=98,113,136 elapsed=177.1s

  [10976/20519] intraday_1907.csv.gz  in=341,120,507 out=98,113,136 elapsed=177.2s

  [10977/20519] intraday_19068.csv.gz  in=341,133,743 out=98,126,372 elapsed=177.2s

  [10978/20519] intraday_19070.csv.gz  in=341,146,231 out=98,138,724 elapsed=177.2s

  [10979/20519] intraday_19071.csv.gz  in=341,157,733 out=98,150,226 elapsed=177.2s

  [10980/20519] intraday_19072.csv.gz  in=341,171,115 out=98,163,608 elapsed=177.2s

  [10981/20519] intraday_19074.csv.gz  in=341,184,635 out=98,177,128 elapsed=177.3s

  [10982/20519] intraday_19075.csv.gz  in=341,196,652 out=98,189,145 elapsed=177.3s

  [10983/20519] intraday_19073.csv.gz  in=341,209,587 out=98,202,080 elapsed=177.3s

  [10984/20519] intraday_19076.csv.gz  in=341,221,301 out=98,213,794 elapsed=177.3s

  [10985/20519] intraday_19079.csv.gz  in=341,234,350 out=98,226,843 elapsed=177.3s

  [10986/20519] intraday_19077.csv.gz  in=341,248,769 out=98,241,262 elapsed=177.3s

  [10987/20519] intraday_1908.csv.gz  in=341,262,089 out=98,241,262 elapsed=177.3s

  [10988/20519] intraday_19078.csv.gz  in=341,274,032 out=98,253,205 elapsed=177.3s

  [10989/20519] intraday_19080.csv.gz  in=341,287,722 out=98,266,895 elapsed=177.4s

  [10990/20519] intraday_19081.csv.gz  in=341,301,409 out=98,280,582 elapsed=177.4s

  [10991/20519] intraday_19082.csv.gz  in=341,315,122 out=98,294,295 elapsed=177.4s

  [10992/20519] intraday_19083.csv.gz  in=341,327,320 out=98,306,493 elapsed=177.4s

  [10993/20519] intraday_19084.csv.gz  in=341,341,049 out=98,320,222 elapsed=177.4s

  [10994/20519] intraday_19085.csv.gz  in=341,353,679 out=98,332,852 elapsed=177.5s

  [10995/20519] intraday_19087.csv.gz  in=341,368,839 out=98,348,012 elapsed=177.5s

  [10996/20519] intraday_19086.csv.gz  in=341,378,497 out=98,357,670 elapsed=177.5s

  [10997/20519] intraday_19088.csv.gz  in=341,389,923 out=98,369,096 elapsed=177.5s

  [10998/20519] intraday_19089.csv.gz  in=341,396,893 out=98,376,066 elapsed=177.5s

  [10999/20519] intraday_1909.csv.gz  in=341,413,906 out=98,376,066 elapsed=177.5s

  [11000/20519] intraday_19091.csv.gz  in=341,415,729 out=98,377,889 elapsed=177.5s

  [11001/20519] intraday_19090.csv.gz  in=341,427,181 out=98,389,341 elapsed=177.5s

  [11002/20519] intraday_19093.csv.gz  in=341,440,730 out=98,402,890 elapsed=177.5s

  [11003/20519] intraday_19092.csv.gz  in=341,458,437 out=98,420,597 elapsed=177.6s

  [11004/20519] intraday_19094.csv.gz  in=341,471,022 out=98,433,182 elapsed=177.6s

  [11005/20519] intraday_19096.csv.gz  in=341,485,265 out=98,447,425 elapsed=177.6s

  [11006/20519] intraday_19095.csv.gz  in=341,496,182 out=98,458,342 elapsed=177.6s

  [11007/20519] intraday_19098.csv.gz  in=341,509,787 out=98,471,947 elapsed=177.6s

  [11008/20519] intraday_19099.csv.gz  in=341,522,225 out=98,484,385 elapsed=177.6s

  [11009/20519] intraday_19097.csv.gz  in=341,537,230 out=98,499,390 elapsed=177.6s

  [11010/20519] intraday_1910.csv.gz  in=341,549,114 out=98,499,390 elapsed=177.6s

  [11011/20519] intraday_19100.csv.gz  in=341,563,055 out=98,513,331 elapsed=177.7s

  [11012/20519] intraday_19101.csv.gz  in=341,576,564 out=98,526,840 elapsed=177.7s

  [11013/20519] intraday_19102.csv.gz  in=341,586,976 out=98,537,252 elapsed=177.7s

  [11014/20519] intraday_19103.csv.gz  in=341,599,794 out=98,550,070 elapsed=177.7s

  [11015/20519] intraday_19104.csv.gz  in=341,615,065 out=98,565,341 elapsed=177.7s

  [11016/20519] intraday_19105.csv.gz  in=341,626,925 out=98,577,201 elapsed=177.7s

  [11017/20519] intraday_19107.csv.gz  in=341,637,857 out=98,588,133 elapsed=177.7s

  [11018/20519] intraday_19106.csv.gz  in=341,654,565 out=98,603,701 elapsed=177.7s

  [11019/20519] intraday_19109.csv.gz  in=341,667,856 out=98,616,992 elapsed=177.8s

  [11020/20519] intraday_19108.csv.gz  in=341,684,232 out=98,633,368 elapsed=177.8s

  [11021/20519] intraday_19110.csv.gz  in=341,694,652 out=98,643,788 elapsed=177.8s

  [11022/20519] intraday_1911.csv.gz  in=341,707,796 out=98,643,788 elapsed=177.8s

  [11023/20519] intraday_19111.csv.gz  in=341,719,196 out=98,655,188 elapsed=177.8s

  [11024/20519] intraday_19113.csv.gz  in=341,732,334 out=98,668,326 elapsed=177.8s

  [11025/20519] intraday_19114.csv.gz  in=341,745,455 out=98,681,447 elapsed=177.9s

  [11026/20519] intraday_19112.csv.gz  in=341,758,960 out=98,694,952 elapsed=177.9s

  [11027/20519] intraday_19115.csv.gz  in=341,770,480 out=98,706,472 elapsed=177.9s

  [11028/20519] intraday_19116.csv.gz  in=341,790,458 out=98,726,450 elapsed=177.9s

  [11029/20519] intraday_19118.csv.gz  in=341,802,542 out=98,738,534 elapsed=177.9s

  [11030/20519] intraday_19117.csv.gz  in=341,815,043 out=98,751,035 elapsed=177.9s

  [11031/20519] intraday_1912.csv.gz  in=341,828,157 out=98,751,035 elapsed=177.9s

  [11032/20519] intraday_19119.csv.gz  in=341,838,888 out=98,761,766 elapsed=178.0s

  [11033/20519] intraday_19120.csv.gz  in=341,853,696 out=98,776,574 elapsed=178.0s

  [11034/20519] intraday_19123.csv.gz  in=341,864,103 out=98,786,981 elapsed=178.0s

  [11035/20519] intraday_19121.csv.gz  in=341,879,222 out=98,802,100 elapsed=178.0s

  [11036/20519] intraday_19122.csv.gz  in=341,892,515 out=98,815,393 elapsed=178.0s

  [11037/20519] intraday_19125.csv.gz  in=341,905,154 out=98,828,032 elapsed=178.0s

  [11038/20519] intraday_19124.csv.gz  in=341,917,975 out=98,840,853 elapsed=178.0s

  [11039/20519] intraday_19127.csv.gz  in=341,931,588 out=98,854,466 elapsed=178.1s

  [11040/20519] intraday_19126.csv.gz  in=341,946,022 out=98,868,900 elapsed=178.1s

  [11041/20519] intraday_19128.csv.gz  in=341,956,665 out=98,879,543 elapsed=178.1s

  [11042/20519] intraday_1913.csv.gz  in=341,968,103 out=98,879,543 elapsed=178.1s

  [11043/20519] intraday_19129.csv.gz  in=341,980,760 out=98,892,200 elapsed=178.1s

  [11044/20519] intraday_19130.csv.gz  in=341,991,363 out=98,902,803 elapsed=178.1s

  [11045/20519] intraday_19131.csv.gz  in=342,001,335 out=98,912,775 elapsed=178.1s

  [11046/20519] intraday_19133.csv.gz  in=342,013,123 out=98,924,563 elapsed=178.2s

  [11047/20519] intraday_19132.csv.gz  in=342,026,918 out=98,938,358 elapsed=178.2s

  [11048/20519] intraday_19135.csv.gz  in=342,041,507 out=98,952,947 elapsed=178.2s

  [11049/20519] intraday_19134.csv.gz  in=342,055,703 out=98,967,143 elapsed=178.2s

  [11050/20519] intraday_19136.csv.gz  in=342,067,282 out=98,978,722 elapsed=178.2s

  [11051/20519] intraday_19137.csv.gz  in=342,078,425 out=98,989,865 elapsed=178.2s

  [11052/20519] intraday_19138.csv.gz  in=342,091,105 out=99,002,545 elapsed=178.2s

  [11053/20519] intraday_1914.csv.gz  in=342,101,631 out=99,002,545 elapsed=178.3s

  [11054/20519] intraday_19140.csv.gz  in=342,115,893 out=99,016,807 elapsed=178.3s

  [11055/20519] intraday_19139.csv.gz  in=342,130,083 out=99,030,997 elapsed=178.3s

  [11056/20519] intraday_19141.csv.gz  in=342,141,242 out=99,042,156 elapsed=178.3s

  [11057/20519] intraday_19143.csv.gz  in=342,154,268 out=99,055,182 elapsed=178.4s

  [11058/20519] intraday_19144.csv.gz  in=342,169,330 out=99,070,244 elapsed=178.4s

  [11059/20519] intraday_19142.csv.gz  in=342,181,200 out=99,082,114 elapsed=178.4s

  [11060/20519] intraday_19145.csv.gz  in=342,200,466 out=99,101,380 elapsed=178.4s

  [11061/20519] intraday_19146.csv.gz  in=342,214,505 out=99,115,419 elapsed=178.4s

  [11062/20519] intraday_19148.csv.gz  in=342,226,035 out=99,126,949 elapsed=178.4s

  [11063/20519] intraday_19147.csv.gz  in=342,236,706 out=99,137,620 elapsed=178.4s

  [11064/20519] intraday_19149.csv.gz  in=342,249,552 out=99,150,466 elapsed=178.4s

  [11065/20519] intraday_1915.csv.gz  in=342,263,456 out=99,150,466 elapsed=178.4s

  [11066/20519] intraday_19150.csv.gz  in=342,276,881 out=99,163,891 elapsed=178.5s

  [11067/20519] intraday_19151.csv.gz  in=342,289,901 out=99,176,911 elapsed=178.5s

  [11068/20519] intraday_19153.csv.gz  in=342,301,706 out=99,188,716 elapsed=178.5s

  [11069/20519] intraday_19152.csv.gz  in=342,314,436 out=99,201,446 elapsed=178.5s

  [11070/20519] intraday_19154.csv.gz  in=342,324,784 out=99,211,794 elapsed=178.5s

  [11071/20519] intraday_19155.csv.gz  in=342,338,167 out=99,225,177 elapsed=178.5s

  [11072/20519] intraday_19156.csv.gz  in=342,352,652 out=99,239,662 elapsed=178.5s

  [11073/20519] intraday_19158.csv.gz  in=342,367,336 out=99,254,346 elapsed=178.5s

  [11074/20519] intraday_1916.csv.gz  in=342,380,389 out=99,254,346 elapsed=178.5s

  [11075/20519] intraday_19157.csv.gz  in=342,394,869 out=99,268,826 elapsed=178.6s

  [11076/20519] intraday_19159.csv.gz  in=342,407,068 out=99,281,025 elapsed=178.6s

  [11077/20519] intraday_19161.csv.gz  in=342,419,024 out=99,292,981 elapsed=178.6s

  [11078/20519] intraday_19162.csv.gz  in=342,432,924 out=99,306,881 elapsed=178.6s

  [11079/20519] intraday_19163.csv.gz  in=342,445,591 out=99,319,548 elapsed=178.6s

  [11080/20519] intraday_19160.csv.gz  in=342,461,276 out=99,335,233 elapsed=178.6s

  [11081/20519] intraday_19165.csv.gz  in=342,473,022 out=99,346,979 elapsed=178.6s

  [11082/20519] intraday_19166.csv.gz  in=342,482,991 out=99,356,948 elapsed=178.7s

  [11083/20519] intraday_19167.csv.gz  in=342,496,801 out=99,370,758 elapsed=178.7s

  [11084/20519] intraday_19168.csv.gz  in=342,511,033 out=99,384,990 elapsed=178.7s

  [11085/20519] intraday_19164.csv.gz  in=342,523,656 out=99,397,613 elapsed=178.7s

  [11086/20519] intraday_1917.csv.gz  in=342,545,679 out=99,397,613 elapsed=178.7s

  [11087/20519] intraday_19169.csv.gz  in=342,556,582 out=99,408,516 elapsed=178.7s

  [11088/20519] intraday_19170.csv.gz  in=342,569,997 out=99,421,931 elapsed=178.8s

  [11089/20519] intraday_19171.csv.gz  in=342,581,488 out=99,433,422 elapsed=178.8s

  [11090/20519] intraday_19174.csv.gz  in=342,599,230 out=99,451,164 elapsed=178.8s

  [11091/20519] intraday_19172.csv.gz  in=342,611,499 out=99,463,433 elapsed=178.8s

  [11092/20519] intraday_19175.csv.gz  in=342,624,431 out=99,476,365 elapsed=178.8s

  [11093/20519] intraday_19173.csv.gz  in=342,638,768 out=99,490,702 elapsed=178.8s

  [11094/20519] intraday_19176.csv.gz  in=342,653,936 out=99,505,870 elapsed=178.9s

  [11095/20519] intraday_19177.csv.gz  in=342,666,160 out=99,518,094 elapsed=178.9s

  [11096/20519] intraday_19178.csv.gz  in=342,679,469 out=99,531,403 elapsed=178.9s

  [11097/20519] intraday_1918.csv.gz  in=342,691,920 out=99,531,403 elapsed=178.9s

  [11098/20519] intraday_19179.csv.gz  in=342,703,354 out=99,542,837 elapsed=178.9s

  [11099/20519] intraday_19181.csv.gz  in=342,714,338 out=99,553,821 elapsed=178.9s

  [11100/20519] intraday_19182.csv.gz  in=342,728,740 out=99,568,223 elapsed=179.0s

  [11101/20519] intraday_19183.csv.gz  in=342,740,275 out=99,579,758 elapsed=179.0s

  [11102/20519] intraday_19180.csv.gz  in=342,757,790 out=99,596,339 elapsed=179.0s

  [11103/20519] intraday_19184.csv.gz  in=342,770,886 out=99,609,435 elapsed=179.0s

  [11104/20519] intraday_19186.csv.gz  in=342,783,246 out=99,621,795 elapsed=179.0s

  [11105/20519] intraday_19185.csv.gz  in=342,795,554 out=99,634,103 elapsed=179.0s

  [11106/20519] intraday_19187.csv.gz  in=342,809,663 out=99,648,212 elapsed=179.0s

  [11107/20519] intraday_19188.csv.gz  in=342,820,173 out=99,658,722 elapsed=179.0s

  [11108/20519] intraday_1919.csv.gz  in=342,835,753 out=99,658,722 elapsed=179.0s

  [11109/20519] intraday_19189.csv.gz  in=342,848,092 out=99,671,061 elapsed=179.0s

  [11110/20519] intraday_19190.csv.gz  in=342,860,095 out=99,683,064 elapsed=179.1s

  [11111/20519] intraday_19191.csv.gz  in=342,873,300 out=99,696,269 elapsed=179.1s

  [11112/20519] intraday_19192.csv.gz  in=342,885,639 out=99,708,608 elapsed=179.1s

  [11113/20519] intraday_19193.csv.gz  in=342,900,705 out=99,723,674 elapsed=179.1s

  [11114/20519] intraday_19195.csv.gz  in=342,912,921 out=99,735,890 elapsed=179.1s

  [11115/20519] intraday_19196.csv.gz  in=342,929,116 out=99,752,085 elapsed=179.2s

  [11116/20519] intraday_19194.csv.gz  in=342,941,048 out=99,764,017 elapsed=179.2s

  [11117/20519] intraday_19197.csv.gz  in=342,952,830 out=99,775,799 elapsed=179.2s

  [11118/20519] intraday_19198.csv.gz  in=342,964,970 out=99,787,939 elapsed=179.2s

  [11119/20519] intraday_1920.csv.gz  in=342,978,577 out=99,787,939 elapsed=179.2s

  [11120/20519] intraday_19199.csv.gz  in=343,000,489 out=99,809,090 elapsed=179.2s

  [11121/20519] intraday_19202.csv.gz  in=343,014,679 out=99,823,280 elapsed=179.3s

  [11122/20519] intraday_19200.csv.gz  in=343,031,499 out=99,840,100 elapsed=179.3s

  [11123/20519] intraday_19201.csv.gz  in=343,045,656 out=99,854,257 elapsed=179.3s

  [11124/20519] intraday_19203.csv.gz  in=343,060,428 out=99,869,029 elapsed=179.3s

  [11125/20519] intraday_19204.csv.gz  in=343,073,329 out=99,881,930 elapsed=179.3s

  [11126/20519] intraday_19205.csv.gz  in=343,089,597 out=99,898,198 elapsed=179.3s

  [11127/20519] intraday_19206.csv.gz  in=343,104,848 out=99,913,449 elapsed=179.4s

  [11128/20519] intraday_19208.csv.gz  in=343,120,647 out=99,929,248 elapsed=179.4s

  [11129/20519] intraday_19207.csv.gz  in=343,139,265 out=99,947,866 elapsed=179.4s

  [11130/20519] intraday_1921.csv.gz  in=343,152,353 out=99,947,866 elapsed=179.4s

  [11131/20519] intraday_19209.csv.gz  in=343,165,953 out=99,961,466 elapsed=179.4s

  [11132/20519] intraday_19210.csv.gz  in=343,178,710 out=99,974,223 elapsed=179.4s

  [11133/20519] intraday_19211.csv.gz  in=343,192,927 out=99,988,440 elapsed=179.4s

  [11134/20519] intraday_19213.csv.gz  in=343,205,000 out=100,000,513 elapsed=179.4s

  [11135/20519] intraday_19212.csv.gz  in=343,218,166 out=100,013,439 elapsed=179.4s

  [11136/20519] intraday_19214.csv.gz  in=343,229,439 out=100,024,712 elapsed=179.5s

  [11137/20519] intraday_19215.csv.gz  in=343,243,105 out=100,038,378 elapsed=179.5s

  [11138/20519] intraday_19216.csv.gz  in=343,256,131 out=100,051,404 elapsed=179.5s

  [11139/20519] intraday_19218.csv.gz  in=343,268,247 out=100,063,520 elapsed=179.5s

  [11140/20519] intraday_19219.csv.gz  in=343,279,973 out=100,075,246 elapsed=179.5s

  [11141/20519] intraday_19217.csv.gz  in=343,294,803 out=100,090,076 elapsed=179.5s

  [11142/20519] intraday_1922.csv.gz  in=343,314,578 out=100,090,076 elapsed=179.5s

  [11143/20519] intraday_19220.csv.gz  in=343,328,879 out=100,104,377 elapsed=179.5s

  [11144/20519] intraday_19222.csv.gz  in=343,342,756 out=100,118,254 elapsed=179.6s

  [11145/20519] intraday_19221.csv.gz  in=343,355,710 out=100,131,208 elapsed=179.6s

  [11146/20519] intraday_19223.csv.gz  in=343,369,572 out=100,145,070 elapsed=179.6s

  [11147/20519] intraday_19224.csv.gz  in=343,383,318 out=100,158,816 elapsed=179.6s

  [11148/20519] intraday_19226.csv.gz  in=343,395,525 out=100,171,023 elapsed=179.6s

  [11149/20519] intraday_19227.csv.gz  in=343,408,661 out=100,184,159 elapsed=179.6s

  [11150/20519] intraday_19225.csv.gz  in=343,422,695 out=100,198,193 elapsed=179.6s

  [11151/20519] intraday_19228.csv.gz  in=343,436,141 out=100,211,639 elapsed=179.6s

  [11152/20519] intraday_19229.csv.gz  in=343,445,793 out=100,221,291 elapsed=179.7s

  [11153/20519] intraday_1923.csv.gz  in=343,461,104 out=100,221,291 elapsed=179.7s

  [11154/20519] intraday_19230.csv.gz  in=343,476,546 out=100,236,733 elapsed=179.7s

  [11155/20519] intraday_19231.csv.gz  in=343,487,641 out=100,247,828 elapsed=179.7s

  [11156/20519] intraday_19232.csv.gz  in=343,495,397 out=100,255,584 elapsed=179.7s

  [11157/20519] intraday_19234.csv.gz  in=343,496,764 out=100,256,951 elapsed=179.7s

  [11158/20519] intraday_19233.csv.gz  in=343,508,693 out=100,268,880 elapsed=179.7s

  [11159/20519] intraday_19235.csv.gz  in=343,524,261 out=100,284,448 elapsed=179.7s

  [11160/20519] intraday_19238.csv.gz  in=343,533,061 out=100,293,248 elapsed=179.8s

  [11161/20519] intraday_19237.csv.gz  in=343,545,445 out=100,305,632 elapsed=179.8s

  [11162/20519] intraday_19236.csv.gz  in=343,558,388 out=100,318,575 elapsed=179.8s

  [11163/20519] intraday_1924.csv.gz  in=343,573,422 out=100,318,575 elapsed=179.8s

  [11164/20519] intraday_19239.csv.gz  in=343,586,863 out=100,332,016 elapsed=179.8s

  [11165/20519] intraday_19241.csv.gz  in=343,598,677 out=100,343,830 elapsed=179.8s

  [11166/20519] intraday_19240.csv.gz  in=343,611,330 out=100,356,483 elapsed=179.9s

  [11167/20519] intraday_19243.csv.gz  in=343,626,138 out=100,371,291 elapsed=179.9s

  [11168/20519] intraday_19242.csv.gz  in=343,637,927 out=100,383,080 elapsed=179.9s

  [11169/20519] intraday_19245.csv.gz  in=343,647,778 out=100,392,931 elapsed=179.9s

  [11170/20519] intraday_19244.csv.gz  in=343,660,138 out=100,405,291 elapsed=179.9s

  [11171/20519] intraday_19246.csv.gz  in=343,672,072 out=100,417,225 elapsed=179.9s

  [11172/20519] intraday_19247.csv.gz  in=343,684,446 out=100,429,599 elapsed=179.9s

  [11173/20519] intraday_19248.csv.gz  in=343,696,101 out=100,441,254 elapsed=179.9s

  [11174/20519] intraday_1925.csv.gz  in=343,710,047 out=100,441,254 elapsed=180.0s

  [11175/20519] intraday_19249.csv.gz  in=343,720,352 out=100,451,559 elapsed=180.0s

  [11176/20519] intraday_19250.csv.gz  in=343,730,354 out=100,461,561 elapsed=180.0s

  [11177/20519] intraday_19252.csv.gz  in=343,742,086 out=100,473,293 elapsed=180.0s

  [11178/20519] intraday_19254.csv.gz  in=343,751,926 out=100,483,133 elapsed=180.0s

  [11179/20519] intraday_19251.csv.gz  in=343,765,038 out=100,496,245 elapsed=180.0s

  [11180/20519] intraday_19253.csv.gz  in=343,774,786 out=100,505,993 elapsed=180.0s

  [11181/20519] intraday_19258.csv.gz  in=343,786,030 out=100,517,237 elapsed=180.1s

  [11182/20519] intraday_19255.csv.gz  in=343,806,128 out=100,536,498 elapsed=180.1s

  [11183/20519] intraday_19257.csv.gz  in=343,817,559 out=100,547,929 elapsed=180.1s

  [11184/20519] intraday_19259.csv.gz  in=343,828,657 out=100,559,027 elapsed=180.1s

  [11185/20519] intraday_19256.csv.gz  in=343,841,068 out=100,571,438 elapsed=180.1s

  [11186/20519] intraday_19260.csv.gz  in=343,852,433 out=100,582,803 elapsed=180.1s

  [11187/20519] intraday_1926.csv.gz  in=343,867,300 out=100,582,803 elapsed=180.1s

  [11188/20519] intraday_19262.csv.gz  in=343,876,960 out=100,592,463 elapsed=180.2s

  [11189/20519] intraday_19261.csv.gz  in=343,888,486 out=100,603,989 elapsed=180.2s

  [11190/20519] intraday_19264.csv.gz  in=343,900,903 out=100,616,406 elapsed=180.2s

  [11191/20519] intraday_19263.csv.gz  in=343,915,059 out=100,630,562 elapsed=180.2s

  [11192/20519] intraday_19266.csv.gz  in=343,925,105 out=100,640,608 elapsed=180.2s

  [11193/20519] intraday_19265.csv.gz  in=343,936,952 out=100,652,455 elapsed=180.2s

  [11194/20519] intraday_19267.csv.gz  in=343,948,069 out=100,663,572 elapsed=180.2s

  [11195/20519] intraday_19268.csv.gz  in=343,959,702 out=100,675,205 elapsed=180.3s

  [11196/20519] intraday_1927.csv.gz  in=343,970,602 out=100,675,205 elapsed=180.3s

  [11197/20519] intraday_19269.csv.gz  in=343,982,201 out=100,686,804 elapsed=180.3s

  [11198/20519] intraday_19270.csv.gz  in=343,995,821 out=100,700,424 elapsed=180.3s

  [11199/20519] intraday_19271.csv.gz  in=344,005,534 out=100,710,137 elapsed=180.3s

  [11200/20519] intraday_19272.csv.gz  in=344,015,584 out=100,720,187 elapsed=180.4s

  [11201/20519] intraday_19274.csv.gz  in=344,025,524 out=100,730,127 elapsed=180.4s

  [11202/20519] intraday_19273.csv.gz  in=344,035,186 out=100,739,789 elapsed=180.4s

  [11203/20519] intraday_19275.csv.gz  in=344,047,203 out=100,751,806 elapsed=180.4s

  [11204/20519] intraday_19276.csv.gz  in=344,057,692 out=100,762,295 elapsed=180.4s

  [11205/20519] intraday_19277.csv.gz  in=344,070,789 out=100,775,392 elapsed=180.4s

  [11206/20519] intraday_19278.csv.gz  in=344,082,919 out=100,787,522 elapsed=180.4s

  [11207/20519] intraday_19279.csv.gz  in=344,093,780 out=100,798,383 elapsed=180.4s

  [11208/20519] intraday_1928.csv.gz  in=344,104,803 out=100,798,383 elapsed=180.4s

  [11209/20519] intraday_19280.csv.gz  in=344,114,795 out=100,808,375 elapsed=180.5s

  [11210/20519] intraday_19281.csv.gz  in=344,127,362 out=100,820,942 elapsed=180.5s

  [11211/20519] intraday_19283.csv.gz  in=344,140,033 out=100,833,613 elapsed=180.5s

  [11212/20519] intraday_19282.csv.gz  in=344,151,692 out=100,845,272 elapsed=180.5s

  [11213/20519] intraday_19284.csv.gz  in=344,162,228 out=100,855,808 elapsed=180.5s

  [11214/20519] intraday_19286.csv.gz  in=344,174,819 out=100,868,399 elapsed=180.5s

  [11215/20519] intraday_19285.csv.gz  in=344,185,678 out=100,879,258 elapsed=180.5s

  [11216/20519] intraday_19287.csv.gz  in=344,197,441 out=100,891,021 elapsed=180.6s

  [11217/20519] intraday_19288.csv.gz  in=344,209,750 out=100,903,330 elapsed=180.6s

  [11218/20519] intraday_1929.csv.gz  in=344,222,509 out=100,903,330 elapsed=180.6s

  [11219/20519] intraday_19289.csv.gz  in=344,234,682 out=100,915,503 elapsed=180.6s

  [11220/20519] intraday_19290.csv.gz  in=344,244,291 out=100,925,112 elapsed=180.6s

  [11221/20519] intraday_19291.csv.gz  in=344,254,720 out=100,935,541 elapsed=180.6s

  [11222/20519] intraday_19292.csv.gz  in=344,266,280 out=100,947,101 elapsed=180.7s

  [11223/20519] intraday_19294.csv.gz  in=344,278,204 out=100,959,025 elapsed=180.7s

  [11224/20519] intraday_19293.csv.gz  in=344,290,769 out=100,971,590 elapsed=180.7s

  [11225/20519] intraday_19295.csv.gz  in=344,300,952 out=100,981,773 elapsed=180.7s

  [11226/20519] intraday_19296.csv.gz  in=344,312,869 out=100,993,690 elapsed=180.7s

  [11227/20519] intraday_19298.csv.gz  in=344,326,072 out=101,006,893 elapsed=180.7s

  [11228/20519] intraday_19299.csv.gz  in=344,339,860 out=101,020,681 elapsed=180.7s

  [11229/20519] intraday_19297.csv.gz  in=344,348,303 out=101,029,124 elapsed=180.7s

  [11230/20519] intraday_1930.csv.gz  in=344,359,971 out=101,029,124 elapsed=180.7s

  [11231/20519] intraday_19300.csv.gz  in=344,371,356 out=101,040,509 elapsed=180.8s

  [11232/20519] intraday_19302.csv.gz  in=344,382,583 out=101,051,736 elapsed=180.8s

  [11233/20519] intraday_19301.csv.gz  in=344,395,589 out=101,064,742 elapsed=180.8s

  [11234/20519] intraday_19303.csv.gz  in=344,405,381 out=101,074,534 elapsed=180.8s

  [11235/20519] intraday_19304.csv.gz  in=344,417,061 out=101,086,214 elapsed=180.8s

  [11236/20519] intraday_19305.csv.gz  in=344,429,482 out=101,098,635 elapsed=180.8s

  [11237/20519] intraday_19307.csv.gz  in=344,439,386 out=101,108,539 elapsed=180.9s

  [11238/20519] intraday_19306.csv.gz  in=344,450,825 out=101,119,958 elapsed=180.9s

  [11239/20519] intraday_19308.csv.gz  in=344,462,272 out=101,131,405 elapsed=180.9s

  [11240/20519] intraday_19309.csv.gz  in=344,472,207 out=101,141,340 elapsed=180.9s

  [11241/20519] intraday_1931.csv.gz  in=344,481,619 out=101,141,340 elapsed=180.9s

  [11242/20519] intraday_19310.csv.gz  in=344,493,429 out=101,153,150 elapsed=180.9s

  [11243/20519] intraday_19311.csv.gz  in=344,504,953 out=101,164,674 elapsed=180.9s

  [11244/20519] intraday_19313.csv.gz  in=344,517,075 out=101,176,796 elapsed=181.0s

  [11245/20519] intraday_19312.csv.gz  in=344,528,291 out=101,188,012 elapsed=181.0s

  [11246/20519] intraday_19314.csv.gz  in=344,542,161 out=101,201,882 elapsed=181.0s

  [11247/20519] intraday_19315.csv.gz  in=344,553,635 out=101,213,356 elapsed=181.0s

  [11248/20519] intraday_19316.csv.gz  in=344,568,567 out=101,228,288 elapsed=181.0s

  [11249/20519] intraday_19317.csv.gz  in=344,583,057 out=101,242,778 elapsed=181.0s

  [11250/20519] intraday_1932.csv.gz  in=344,592,034 out=101,242,778 elapsed=181.0s

  [11251/20519] intraday_19318.csv.gz  in=344,604,090 out=101,254,834 elapsed=181.0s

  [11252/20519] intraday_19319.csv.gz  in=344,616,100 out=101,266,844 elapsed=181.0s

  [11253/20519] intraday_19320.csv.gz  in=344,627,000 out=101,277,744 elapsed=181.1s

  [11254/20519] intraday_19321.csv.gz  in=344,637,809 out=101,288,553 elapsed=181.1s

  [11255/20519] intraday_19322.csv.gz  in=344,650,992 out=101,301,736 elapsed=181.1s

  [11256/20519] intraday_19324.csv.gz  in=344,661,544 out=101,312,288 elapsed=181.1s

  [11257/20519] intraday_19323.csv.gz  in=344,672,770 out=101,323,514 elapsed=181.1s

  [11258/20519] intraday_19325.csv.gz  in=344,686,241 out=101,336,985 elapsed=181.1s

  [11259/20519] intraday_19326.csv.gz  in=344,696,880 out=101,347,624 elapsed=181.2s

  [11260/20519] intraday_19328.csv.gz  in=344,708,356 out=101,359,100 elapsed=181.2s

  [11261/20519] intraday_19329.csv.gz  in=344,721,146 out=101,371,890 elapsed=181.2s

  [11262/20519] intraday_1933.csv.gz  in=344,731,048 out=101,371,890 elapsed=181.2s

  [11263/20519] intraday_19327.csv.gz  in=344,742,799 out=101,383,641 elapsed=181.2s

  [11264/20519] intraday_19330.csv.gz  in=344,753,544 out=101,394,386 elapsed=181.2s

  [11265/20519] intraday_19331.csv.gz  in=344,764,643 out=101,405,485 elapsed=181.2s

  [11266/20519] intraday_19332.csv.gz  in=344,775,639 out=101,416,481 elapsed=181.2s

  [11267/20519] intraday_19333.csv.gz  in=344,785,747 out=101,426,589 elapsed=181.3s

  [11268/20519] intraday_19334.csv.gz  in=344,797,165 out=101,438,007 elapsed=181.3s

  [11269/20519] intraday_19335.csv.gz  in=344,808,596 out=101,449,438 elapsed=181.3s

  [11270/20519] intraday_19336.csv.gz  in=344,820,446 out=101,461,288 elapsed=181.3s

  [11271/20519] intraday_19337.csv.gz  in=344,832,264 out=101,473,106 elapsed=181.3s

  [11272/20519] intraday_19338.csv.gz  in=344,846,501 out=101,487,343 elapsed=181.3s

  [11273/20519] intraday_1934.csv.gz  in=344,851,092 out=101,487,343 elapsed=181.3s

  [11274/20519] intraday_19340.csv.gz  in=344,862,628 out=101,498,879 elapsed=181.3s

  [11275/20519] intraday_19339.csv.gz  in=344,882,766 out=101,518,337 elapsed=181.3s

  [11276/20519] intraday_19341.csv.gz  in=344,894,773 out=101,530,344 elapsed=181.4s

  [11277/20519] intraday_19344.csv.gz  in=344,907,210 out=101,542,781 elapsed=181.4s

  [11278/20519] intraday_19343.csv.gz  in=344,921,021 out=101,556,592 elapsed=181.4s

  [11279/20519] intraday_19342.csv.gz  in=344,935,449 out=101,571,020 elapsed=181.4s

  [11280/20519] intraday_19345.csv.gz  in=344,948,745 out=101,584,316 elapsed=181.4s

  [11281/20519] intraday_19346.csv.gz  in=344,960,419 out=101,595,990 elapsed=181.4s

  [11282/20519] intraday_19347.csv.gz  in=344,972,799 out=101,608,370 elapsed=181.4s

  [11283/20519] intraday_19348.csv.gz  in=344,986,971 out=101,622,542 elapsed=181.4s

  [11284/20519] intraday_1935.csv.gz  in=345,001,847 out=101,622,542 elapsed=181.5s

  [11285/20519] intraday_19350.csv.gz  in=345,012,900 out=101,633,595 elapsed=181.5s

  [11286/20519] intraday_19349.csv.gz  in=345,030,336 out=101,651,031 elapsed=181.5s

  [11287/20519] intraday_19351.csv.gz  in=345,046,219 out=101,666,914 elapsed=181.5s

  [11288/20519] intraday_19352.csv.gz  in=345,056,748 out=101,677,443 elapsed=181.5s

  [11289/20519] intraday_19354.csv.gz  in=345,066,235 out=101,686,930 elapsed=181.5s

  [11290/20519] intraday_19353.csv.gz  in=345,078,708 out=101,699,403 elapsed=181.5s

  [11291/20519] intraday_19356.csv.gz  in=345,089,205 out=101,709,900 elapsed=181.6s

  [11292/20519] intraday_19355.csv.gz  in=345,101,970 out=101,722,665 elapsed=181.6s

  [11293/20519] intraday_19357.csv.gz  in=345,114,832 out=101,735,527 elapsed=181.6s

  [11294/20519] intraday_19358.csv.gz  in=345,126,218 out=101,746,913 elapsed=181.6s

  [11295/20519] intraday_1936.csv.gz  in=345,140,067 out=101,746,913 elapsed=181.6s

  [11296/20519] intraday_19359.csv.gz  in=345,151,847 out=101,758,693 elapsed=181.6s

  [11297/20519] intraday_19361.csv.gz  in=345,162,749 out=101,769,595 elapsed=181.6s

  [11298/20519] intraday_19362.csv.gz  in=345,175,074 out=101,781,920 elapsed=181.7s

  [11299/20519] intraday_19363.csv.gz  in=345,186,227 out=101,793,073 elapsed=181.7s

  [11300/20519] intraday_19360.csv.gz  in=345,197,211 out=101,804,057 elapsed=181.7s

  [11301/20519] intraday_19364.csv.gz  in=345,209,620 out=101,816,458 elapsed=181.7s

  [11302/20519] intraday_19365.csv.gz  in=345,223,214 out=101,830,052 elapsed=181.7s

  [11303/20519] intraday_19367.csv.gz  in=345,235,231 out=101,842,069 elapsed=181.7s

  [11304/20519] intraday_19368.csv.gz  in=345,248,849 out=101,855,687 elapsed=181.7s

  [11305/20519] intraday_19366.csv.gz  in=345,262,621 out=101,869,459 elapsed=181.8s

  [11306/20519] intraday_1937.csv.gz  in=345,274,660 out=101,869,459 elapsed=181.8s

  [11307/20519] intraday_19369.csv.gz  in=345,285,055 out=101,879,854 elapsed=181.8s

  [11308/20519] intraday_19372.csv.gz  in=345,297,273 out=101,892,072 elapsed=181.8s

  [11309/20519] intraday_19370.csv.gz  in=345,309,885 out=101,904,684 elapsed=181.8s

  [11310/20519] intraday_19371.csv.gz  in=345,320,975 out=101,915,774 elapsed=181.8s

  [11311/20519] intraday_19373.csv.gz  in=345,332,910 out=101,927,701 elapsed=181.8s

  [11312/20519] intraday_19374.csv.gz  in=345,339,686 out=101,934,477 elapsed=181.8s

  [11313/20519] intraday_19377.csv.gz  in=345,340,487 out=101,935,278 elapsed=181.8s

  [11314/20519] intraday_19376.csv.gz  in=345,345,829 out=101,940,620 elapsed=181.8s

  [11315/20519] intraday_19375.csv.gz  in=345,355,148 out=101,949,939 elapsed=181.9s

  [11316/20519] intraday_19379.csv.gz  in=345,359,178 out=101,953,899 elapsed=181.9s

  [11317/20519] intraday_1938.csv.gz  in=345,370,764 out=101,953,899 elapsed=181.9s

  [11318/20519] intraday_19380.csv.gz  in=345,371,101 out=101,954,236 elapsed=181.9s

  [11319/20519] intraday_19378.csv.gz  in=345,376,974 out=101,959,658 elapsed=181.9s

  [11320/20519] intraday_19381.csv.gz  in=345,377,356 out=101,960,040 elapsed=181.9s

  [11321/20519] intraday_19382.csv.gz  in=345,377,965 out=101,960,649 elapsed=181.9s

  [11322/20519] intraday_19384.csv.gz  in=345,378,306 out=101,960,990 elapsed=181.9s

  [11323/20519] intraday_19383.csv.gz  in=345,378,765 out=101,961,449 elapsed=181.9s

  [11324/20519] intraday_19386.csv.gz  in=345,379,101 out=101,961,785 elapsed=181.9s

  [11325/20519] intraday_19385.csv.gz  in=345,379,872 out=101,962,556 elapsed=181.9s

  [11326/20519] intraday_19387.csv.gz  in=345,380,362 out=101,963,046 elapsed=181.9s

  [11327/20519] intraday_19388.csv.gz  in=345,380,745 out=101,963,429 elapsed=181.9s

  [11328/20519] intraday_19389.csv.gz  in=345,382,595 out=101,965,095 elapsed=181.9s

  [11329/20519] intraday_1939.csv.gz  in=345,395,913 out=101,965,095 elapsed=181.9s

  [11330/20519] intraday_19391.csv.gz  in=345,396,339 out=101,965,521 elapsed=182.0s

  [11331/20519] intraday_19392.csv.gz  in=345,396,542 out=101,965,724 elapsed=182.0s

  [11332/20519] intraday_19390.csv.gz  in=345,396,806 out=101,965,988 elapsed=182.0s

  [11333/20519] intraday_19393.csv.gz  in=345,397,330 out=101,966,512 elapsed=182.0s

  [11334/20519] intraday_19395.csv.gz  in=345,397,632 out=101,966,814 elapsed=182.0s

  [11335/20519] intraday_19394.csv.gz  in=345,398,065 out=101,967,247 elapsed=182.0s

  [11336/20519] intraday_19396.csv.gz  in=345,398,364 out=101,967,546 elapsed=182.0s

  [11337/20519] intraday_19399.csv.gz  in=345,398,666 out=101,967,848 elapsed=182.0s

  [11338/20519] intraday_19397.csv.gz  in=345,399,061 out=101,968,243 elapsed=182.0s

  [11339/20519] intraday_19400.csv.gz  in=345,399,294 out=101,968,476 elapsed=182.0s

  [11340/20519] intraday_19402.csv.gz  in=345,399,679 out=101,968,861 elapsed=182.0s

  [11341/20519] intraday_19398.csv.gz  in=345,400,479 out=101,969,620 elapsed=182.0s

  [11342/20519] intraday_19403.csv.gz  in=345,400,641 out=101,969,782 elapsed=182.0s

  [11343/20519] intraday_19404.csv.gz  in=345,400,680 out=101,969,821 elapsed=182.0s

  [11344/20519] intraday_19405.csv.gz  in=345,401,314 out=101,970,455 elapsed=182.0s

  [11345/20519] intraday_1940.csv.gz  in=345,415,842 out=101,970,455 elapsed=182.0s

  [11346/20519] intraday_19406.csv.gz  in=345,416,614 out=101,971,227 elapsed=182.0s

  [11347/20519] intraday_19401.csv.gz  in=345,431,771 out=101,985,261 elapsed=182.0s

  [11348/20519] intraday_19408.csv.gz  in=345,432,055 out=101,985,545 elapsed=182.1s

  [11349/20519] intraday_19407.csv.gz  in=345,432,378 out=101,985,868 elapsed=182.1s

  [11350/20519] intraday_19409.csv.gz  in=345,432,519 out=101,986,009 elapsed=182.1s

  [11351/20519] intraday_19410.csv.gz  in=345,432,775 out=101,986,265 elapsed=182.1s

  [11352/20519] intraday_1941.csv.gz  in=345,445,114 out=101,986,265 elapsed=182.1s

  [11353/20519] intraday_19412.csv.gz  in=345,446,076 out=101,987,227 elapsed=182.1s

  [11354/20519] intraday_19414.csv.gz  in=345,446,199 out=101,987,350 elapsed=182.1s

  [11355/20519] intraday_19413.csv.gz  in=345,446,475 out=101,987,626 elapsed=182.1s

  [11356/20519] intraday_19411.csv.gz  in=345,453,346 out=101,993,961 elapsed=182.1s

  [11357/20519] intraday_19415.csv.gz  in=345,453,647 out=101,994,262 elapsed=182.1s

  [11358/20519] intraday_19416.csv.gz  in=345,453,694 out=101,994,309 elapsed=182.1s

  [11359/20519] intraday_19417.csv.gz  in=345,453,903 out=101,994,518 elapsed=182.1s

  [11360/20519] intraday_19419.csv.gz  in=345,454,481 out=101,995,096 elapsed=182.1s

  [11361/20519] intraday_19418.csv.gz  in=345,454,596 out=101,995,211 elapsed=182.1s

  [11362/20519] intraday_19421.csv.gz  in=345,454,749 out=101,995,364 elapsed=182.1s

  [11363/20519] intraday_19422.csv.gz  in=345,454,824 out=101,995,439 elapsed=182.1s

  [11364/20519] intraday_19420.csv.gz  in=345,455,242 out=101,995,857 elapsed=182.1s

  [11365/20519] intraday_19423.csv.gz  in=345,455,339 out=101,995,954 elapsed=182.1s

  [11366/20519] intraday_19426.csv.gz  in=345,455,429 out=101,996,044 elapsed=182.2s

  [11367/20519] intraday_1942.csv.gz  in=345,467,615 out=101,996,044 elapsed=182.2s

  [11368/20519] intraday_19424.csv.gz  in=345,468,352 out=101,996,781 elapsed=182.2s

  [11369/20519] intraday_19425.csv.gz  in=345,469,628 out=101,998,057 elapsed=182.2s

  [11370/20519] intraday_19429.csv.gz  in=345,470,247 out=101,998,676 elapsed=182.2s

  [11371/20519] intraday_19427.csv.gz  in=345,474,545 out=102,002,937 elapsed=182.2s

  [11372/20519] intraday_19430.csv.gz  in=345,476,630 out=102,004,877 elapsed=182.3s

  [11373/20519] intraday_1943.csv.gz  in=345,490,691 out=102,004,877 elapsed=182.3s

  [11374/20519] intraday_19432.csv.gz  in=345,490,816 out=102,005,002 elapsed=182.3s

  [11375/20519] intraday_19428.csv.gz  in=345,506,972 out=102,020,689 elapsed=182.3s

  [11376/20519] intraday_19431.csv.gz  in=345,507,585 out=102,021,302 elapsed=182.3s

  [11377/20519] intraday_19436.csv.gz  in=345,507,702 out=102,021,419 elapsed=182.3s

  [11378/20519] intraday_19435.csv.gz  in=345,508,095 out=102,021,812 elapsed=182.3s

  [11379/20519] intraday_19434.csv.gz  in=345,508,286 out=102,022,003 elapsed=182.3s

  [11380/20519] intraday_19433.csv.gz  in=345,508,420 out=102,022,137 elapsed=182.3s

  [11381/20519] intraday_19437.csv.gz  in=345,508,822 out=102,022,539 elapsed=182.3s

  [11382/20519] intraday_19439.csv.gz  in=345,508,903 out=102,022,620 elapsed=182.3s

  [11383/20519] intraday_19438.csv.gz  in=345,512,578 out=102,026,163 elapsed=182.4s

  [11384/20519] intraday_19441.csv.gz  in=345,513,349 out=102,026,934 elapsed=182.4s

  [11385/20519] intraday_1944.csv.gz  in=345,529,067 out=102,026,934 elapsed=182.4s

  [11386/20519] intraday_19440.csv.gz  in=345,532,417 out=102,030,284 elapsed=182.4s

  [11387/20519] intraday_19444.csv.gz  in=345,532,599 out=102,030,466 elapsed=182.4s

  [11388/20519] intraday_19443.csv.gz  in=345,532,741 out=102,030,608 elapsed=182.4s

  [11389/20519] intraday_19445.csv.gz  in=345,533,211 out=102,031,078 elapsed=182.4s

  [11390/20519] intraday_19447.csv.gz  in=345,533,484 out=102,031,351 elapsed=182.4s

  [11391/20519] intraday_19446.csv.gz  in=345,533,833 out=102,031,700 elapsed=182.4s

  [11392/20519] intraday_19442.csv.gz  in=345,537,691 out=102,035,079 elapsed=182.4s

  [11393/20519] intraday_19448.csv.gz  in=345,539,763 out=102,037,151 elapsed=182.4s

  [11394/20519] intraday_19449.csv.gz  in=345,539,936 out=102,037,324 elapsed=182.4s

  [11395/20519] intraday_19450.csv.gz  in=345,540,187 out=102,037,575 elapsed=182.4s

  [11396/20519] intraday_19451.csv.gz  in=345,540,864 out=102,038,252 elapsed=182.4s

  [11397/20519] intraday_1945.csv.gz  in=345,549,809 out=102,038,252 elapsed=182.4s

  [11398/20519] intraday_19452.csv.gz  in=345,549,993 out=102,038,436 elapsed=182.4s

  [11399/20519] intraday_19454.csv.gz  in=345,550,186 out=102,038,629 elapsed=182.4s

  [11400/20519] intraday_19453.csv.gz  in=345,550,470 out=102,038,913 elapsed=182.4s

  [11401/20519] intraday_19455.csv.gz  in=345,550,884 out=102,039,327 elapsed=182.4s

  [11402/20519] intraday_19456.csv.gz  in=345,551,145 out=102,039,588 elapsed=182.4s

  [11403/20519] intraday_19457.csv.gz  in=345,551,314 out=102,039,757 elapsed=182.4s

  [11404/20519] intraday_19458.csv.gz  in=345,552,189 out=102,040,632 elapsed=182.4s

  [11405/20519] intraday_19460.csv.gz  in=345,552,957 out=102,041,400 elapsed=182.4s

  [11406/20519] intraday_19459.csv.gz  in=345,554,108 out=102,042,551 elapsed=182.4s

  [11407/20519] intraday_19461.csv.gz  in=345,555,003 out=102,043,446 elapsed=182.4s

  [11408/20519] intraday_19462.csv.gz  in=345,555,326 out=102,043,769 elapsed=182.4s

  [11409/20519] intraday_19463.csv.gz  in=345,555,797 out=102,044,240 elapsed=182.4s

  [11410/20519] intraday_1946.csv.gz  in=345,573,102 out=102,044,240 elapsed=182.4s

  [11411/20519] intraday_19464.csv.gz  in=345,573,337 out=102,044,475 elapsed=182.4s

  [11412/20519] intraday_19465.csv.gz  in=345,574,178 out=102,045,316 elapsed=182.4s

  [11413/20519] intraday_19466.csv.gz  in=345,574,373 out=102,045,511 elapsed=182.4s

  [11414/20519] intraday_19467.csv.gz  in=345,575,436 out=102,046,574 elapsed=182.5s

  [11415/20519] intraday_19468.csv.gz  in=345,575,698 out=102,046,836 elapsed=182.5s

  [11416/20519] intraday_19469.csv.gz  in=345,576,559 out=102,047,697 elapsed=182.5s

  [11417/20519] intraday_19470.csv.gz  in=345,576,771 out=102,047,909 elapsed=182.5s

  [11418/20519] intraday_19471.csv.gz  in=345,576,861 out=102,047,999 elapsed=182.5s

  [11419/20519] intraday_1947.csv.gz  in=345,590,579 out=102,047,999 elapsed=182.5s

  [11420/20519] intraday_19473.csv.gz  in=345,590,743 out=102,048,163 elapsed=182.5s

  [11421/20519] intraday_19475.csv.gz  in=345,590,859 out=102,048,279 elapsed=182.5s

  [11422/20519] intraday_19474.csv.gz  in=345,591,491 out=102,048,911 elapsed=182.5s

  [11423/20519] intraday_19472.csv.gz  in=345,596,875 out=102,054,274 elapsed=182.5s

  [11424/20519] intraday_19476.csv.gz  in=345,597,021 out=102,054,420 elapsed=182.5s

  [11425/20519] intraday_19479.csv.gz  in=345,597,803 out=102,055,202 elapsed=182.5s

  [11426/20519] intraday_19478.csv.gz  in=345,598,843 out=102,056,242 elapsed=182.5s

  [11427/20519] intraday_19480.csv.gz  in=345,599,230 out=102,056,629 elapsed=182.5s

  [11428/20519] intraday_19482.csv.gz  in=345,599,669 out=102,057,068 elapsed=182.5s

  [11429/20519] intraday_1948.csv.gz  in=345,615,069 out=102,057,068 elapsed=182.5s

  [11430/20519] intraday_19477.csv.gz  in=345,629,613 out=102,070,971 elapsed=182.5s

  [11431/20519] intraday_19481.csv.gz  in=345,629,953 out=102,071,311 elapsed=182.5s

  [11432/20519] intraday_19483.csv.gz  in=345,630,027 out=102,071,385 elapsed=182.5s

  [11433/20519] intraday_19484.csv.gz  in=345,630,614 out=102,071,972 elapsed=182.5s

  [11434/20519] intraday_19485.csv.gz  in=345,632,670 out=102,074,028 elapsed=182.6s

  [11435/20519] intraday_19487.csv.gz  in=345,633,583 out=102,074,941 elapsed=182.6s

  [11436/20519] intraday_19486.csv.gz  in=345,634,867 out=102,076,225 elapsed=182.6s

  [11437/20519] intraday_19489.csv.gz  in=345,635,694 out=102,077,052 elapsed=182.6s

  [11438/20519] intraday_19488.csv.gz  in=345,636,756 out=102,077,741 elapsed=182.6s

  [11439/20519] intraday_19490.csv.gz  in=345,637,506 out=102,078,491 elapsed=182.6s

  [11440/20519] intraday_19492.csv.gz  in=345,639,037 out=102,080,022 elapsed=182.6s

  [11441/20519] intraday_19493.csv.gz  in=345,639,188 out=102,080,173 elapsed=182.6s

  [11442/20519] intraday_1949.csv.gz  in=345,649,855 out=102,080,173 elapsed=182.6s

  [11443/20519] intraday_19491.csv.gz  in=345,651,354 out=102,081,672 elapsed=182.6s

  [11444/20519] intraday_19494.csv.gz  in=345,652,408 out=102,082,726 elapsed=182.6s

  [11445/20519] intraday_19496.csv.gz  in=345,652,832 out=102,083,150 elapsed=182.6s

  [11446/20519] intraday_19495.csv.gz  in=345,653,148 out=102,083,466 elapsed=182.6s

  [11447/20519] intraday_19497.csv.gz  in=345,653,215 out=102,083,533 elapsed=182.6s

  [11448/20519] intraday_19499.csv.gz  in=345,653,398 out=102,083,716 elapsed=182.6s

  [11449/20519] intraday_19498.csv.gz  in=345,653,729 out=102,084,047 elapsed=182.6s

  [11450/20519] intraday_1950.csv.gz  in=345,666,771 out=102,084,047 elapsed=182.6s

  [11451/20519] intraday_19502.csv.gz  in=345,667,617 out=102,084,893 elapsed=182.6s

  [11452/20519] intraday_19501.csv.gz  in=345,668,090 out=102,085,366 elapsed=182.7s

  [11453/20519] intraday_19500.csv.gz  in=345,668,539 out=102,085,815 elapsed=182.7s

  [11454/20519] intraday_19504.csv.gz  in=345,668,891 out=102,086,167 elapsed=182.7s

  [11455/20519] intraday_19503.csv.gz  in=345,670,572 out=102,087,848 elapsed=182.7s

  [11456/20519] intraday_19505.csv.gz  in=345,671,014 out=102,088,290 elapsed=182.7s

  [11457/20519] intraday_19506.csv.gz  in=345,671,572 out=102,088,848 elapsed=182.7s

  [11458/20519] intraday_19507.csv.gz  in=345,671,970 out=102,089,246 elapsed=182.7s

  [11459/20519] intraday_19508.csv.gz  in=345,672,348 out=102,089,624 elapsed=182.7s

  [11460/20519] intraday_19510.csv.gz  in=345,672,885 out=102,090,161 elapsed=182.7s

  [11461/20519] intraday_19511.csv.gz  in=345,673,109 out=102,090,385 elapsed=182.7s

  [11462/20519] intraday_19509.csv.gz  in=345,673,406 out=102,090,682 elapsed=182.7s

  [11463/20519] intraday_19512.csv.gz  in=345,674,174 out=102,091,450 elapsed=182.7s

  [11464/20519] intraday_1951.csv.gz  in=345,692,952 out=102,091,450 elapsed=182.7s

  [11465/20519] intraday_19514.csv.gz  in=345,693,136 out=102,091,634 elapsed=182.7s

  [11466/20519] intraday_19515.csv.gz  in=345,693,392 out=102,091,890 elapsed=182.7s

  [11467/20519] intraday_19513.csv.gz  in=345,693,689 out=102,092,187 elapsed=182.7s

  [11468/20519] intraday_19517.csv.gz  in=345,693,984 out=102,092,482 elapsed=182.7s

  [11469/20519] intraday_19518.csv.gz  in=345,694,355 out=102,092,853 elapsed=182.7s

  [11470/20519] intraday_19519.csv.gz  in=345,694,726 out=102,093,224 elapsed=182.8s

  [11471/20519] intraday_19516.csv.gz  in=345,706,907 out=102,105,263 elapsed=182.8s

  [11472/20519] intraday_1952.csv.gz  in=345,719,401 out=102,105,263 elapsed=182.8s

  [11473/20519] intraday_19522.csv.gz  in=345,732,434 out=102,118,296 elapsed=182.8s

  [11474/20519] intraday_19521.csv.gz  in=345,744,800 out=102,130,662 elapsed=182.8s

  [11475/20519] intraday_19520.csv.gz  in=345,760,867 out=102,146,729 elapsed=182.8s

  [11476/20519] intraday_19523.csv.gz  in=345,770,082 out=102,155,944 elapsed=182.8s

  [11477/20519] intraday_19524.csv.gz  in=345,783,218 out=102,169,080 elapsed=182.8s

  [11478/20519] intraday_19525.csv.gz  in=345,797,414 out=102,183,276 elapsed=182.9s

  [11479/20519] intraday_19526.csv.gz  in=345,809,158 out=102,195,020 elapsed=182.9s

  [11480/20519] intraday_19527.csv.gz  in=345,821,203 out=102,207,065 elapsed=182.9s

  [11481/20519] intraday_19528.csv.gz  in=345,833,958 out=102,219,820 elapsed=182.9s

  [11482/20519] intraday_1953.csv.gz  in=345,847,880 out=102,219,820 elapsed=182.9s

  [11483/20519] intraday_19529.csv.gz  in=345,859,891 out=102,231,831 elapsed=182.9s

  [11484/20519] intraday_19530.csv.gz  in=345,869,671 out=102,241,611 elapsed=182.9s

  [11485/20519] intraday_19531.csv.gz  in=345,881,117 out=102,253,057 elapsed=182.9s

  [11486/20519] intraday_19533.csv.gz  in=345,890,876 out=102,262,816 elapsed=182.9s

  [11487/20519] intraday_19534.csv.gz  in=345,901,455 out=102,273,395 elapsed=182.9s

  [11488/20519] intraday_19532.csv.gz  in=345,936,916 out=102,305,987 elapsed=183.0s

  [11489/20519] intraday_19535.csv.gz  in=345,946,173 out=102,315,244 elapsed=183.0s

  [11490/20519] intraday_19536.csv.gz  in=345,960,550 out=102,329,621 elapsed=183.0s

  [11491/20519] intraday_19537.csv.gz  in=345,973,268 out=102,342,339 elapsed=183.0s

  [11492/20519] intraday_19539.csv.gz  in=345,983,126 out=102,352,197 elapsed=183.0s

  [11493/20519] intraday_1954.csv.gz  in=345,995,462 out=102,352,197 elapsed=183.0s

  [11494/20519] intraday_19538.csv.gz  in=346,005,167 out=102,361,902 elapsed=183.0s

  [11495/20519] intraday_19540.csv.gz  in=346,017,002 out=102,373,737 elapsed=183.0s

  [11496/20519] intraday_19541.csv.gz  in=346,029,239 out=102,385,974 elapsed=183.1s

  [11497/20519] intraday_19543.csv.gz  in=346,039,712 out=102,396,447 elapsed=183.1s

  [11498/20519] intraday_19544.csv.gz  in=346,051,179 out=102,407,914 elapsed=183.1s

  [11499/20519] intraday_19542.csv.gz  in=346,063,762 out=102,420,497 elapsed=183.1s

  [11500/20519] intraday_19545.csv.gz  in=346,074,933 out=102,431,668 elapsed=183.1s

  [11501/20519] intraday_19546.csv.gz  in=346,087,276 out=102,444,011 elapsed=183.1s

  [11502/20519] intraday_19547.csv.gz  in=346,097,541 out=102,454,276 elapsed=183.1s

  [11503/20519] intraday_19549.csv.gz  in=346,110,119 out=102,466,854 elapsed=183.2s

  [11504/20519] intraday_19548.csv.gz  in=346,123,992 out=102,480,727 elapsed=183.2s

  [11505/20519] intraday_1955.csv.gz  in=346,137,363 out=102,480,727 elapsed=183.2s

  [11506/20519] intraday_19550.csv.gz  in=346,150,250 out=102,493,614 elapsed=183.2s

  [11507/20519] intraday_19551.csv.gz  in=346,161,150 out=102,504,514 elapsed=183.2s

  [11508/20519] intraday_19553.csv.gz  in=346,172,825 out=102,516,189 elapsed=183.2s

  [11509/20519] intraday_19552.csv.gz  in=346,184,657 out=102,528,021 elapsed=183.2s

  [11510/20519] intraday_19554.csv.gz  in=346,197,215 out=102,540,579 elapsed=183.3s

  [11511/20519] intraday_19555.csv.gz  in=346,210,402 out=102,553,766 elapsed=183.3s

  [11512/20519] intraday_19556.csv.gz  in=346,220,656 out=102,564,020 elapsed=183.3s

  [11513/20519] intraday_19557.csv.gz  in=346,231,341 out=102,574,705 elapsed=183.3s

  [11514/20519] intraday_19558.csv.gz  in=346,241,538 out=102,584,902 elapsed=183.3s

  [11515/20519] intraday_19559.csv.gz  in=346,251,551 out=102,594,915 elapsed=183.3s

  [11516/20519] intraday_1956.csv.gz  in=346,263,289 out=102,594,915 elapsed=183.3s

  [11517/20519] intraday_19561.csv.gz  in=346,273,670 out=102,605,296 elapsed=183.4s

  [11518/20519] intraday_19560.csv.gz  in=346,286,444 out=102,618,070 elapsed=183.4s

  [11519/20519] intraday_19563.csv.gz  in=346,298,642 out=102,630,268 elapsed=183.4s

  [11520/20519] intraday_19562.csv.gz  in=346,312,772 out=102,644,398 elapsed=183.4s

  [11521/20519] intraday_19564.csv.gz  in=346,324,347 out=102,655,973 elapsed=183.4s

  [11522/20519] intraday_19565.csv.gz  in=346,334,239 out=102,665,865 elapsed=183.4s

  [11523/20519] intraday_19566.csv.gz  in=346,346,828 out=102,678,454 elapsed=183.5s

  [11524/20519] intraday_19567.csv.gz  in=346,357,516 out=102,689,142 elapsed=183.5s

  [11525/20519] intraday_19569.csv.gz  in=346,367,695 out=102,699,321 elapsed=183.5s

  [11526/20519] intraday_19568.csv.gz  in=346,381,389 out=102,713,015 elapsed=183.5s

  [11527/20519] intraday_1957.csv.gz  in=346,396,384 out=102,713,015 elapsed=183.5s

  [11528/20519] intraday_19570.csv.gz  in=346,407,021 out=102,723,652 elapsed=183.5s

  [11529/20519] intraday_19573.csv.gz  in=346,417,920 out=102,734,551 elapsed=183.5s

  [11530/20519] intraday_19572.csv.gz  in=346,432,005 out=102,748,636 elapsed=183.6s

  [11531/20519] intraday_19574.csv.gz  in=346,445,169 out=102,761,800 elapsed=183.6s

  [11532/20519] intraday_19575.csv.gz  in=346,455,009 out=102,771,640 elapsed=183.6s

  [11533/20519] intraday_19571.csv.gz  in=346,466,887 out=102,783,518 elapsed=183.6s

  [11534/20519] intraday_19576.csv.gz  in=346,476,628 out=102,793,259 elapsed=183.6s

  [11535/20519] intraday_19577.csv.gz  in=346,488,194 out=102,804,825 elapsed=183.6s

  [11536/20519] intraday_19578.csv.gz  in=346,501,225 out=102,817,856 elapsed=183.7s

  [11537/20519] intraday_19579.csv.gz  in=346,512,794 out=102,829,425 elapsed=183.7s

  [11538/20519] intraday_19580.csv.gz  in=346,524,119 out=102,840,750 elapsed=183.7s

  [11539/20519] intraday_1958.csv.gz  in=346,541,783 out=102,840,750 elapsed=183.7s

  [11540/20519] intraday_19581.csv.gz  in=346,552,393 out=102,851,360 elapsed=183.7s

  [11541/20519] intraday_19582.csv.gz  in=346,562,374 out=102,861,341 elapsed=183.7s

  [11542/20519] intraday_19583.csv.gz  in=346,572,925 out=102,871,892 elapsed=183.7s

  [11543/20519] intraday_19584.csv.gz  in=346,587,536 out=102,886,503 elapsed=183.7s

  [11544/20519] intraday_19587.csv.gz  in=346,599,973 out=102,898,940 elapsed=183.8s

  [11545/20519] intraday_19586.csv.gz  in=346,612,371 out=102,911,338 elapsed=183.8s

  [11546/20519] intraday_19585.csv.gz  in=346,625,843 out=102,924,810 elapsed=183.8s

  [11547/20519] intraday_19588.csv.gz  in=346,636,086 out=102,935,053 elapsed=183.8s

  [11548/20519] intraday_1959.csv.gz  in=346,648,376 out=102,935,053 elapsed=183.8s

  [11549/20519] intraday_19591.csv.gz  in=346,658,182 out=102,944,859 elapsed=183.8s

  [11550/20519] intraday_19590.csv.gz  in=346,670,965 out=102,957,642 elapsed=183.9s

  [11551/20519] intraday_19593.csv.gz  in=346,681,181 out=102,967,858 elapsed=183.9s

  [11552/20519] intraday_19592.csv.gz  in=346,693,093 out=102,979,770 elapsed=183.9s

  [11553/20519] intraday_19594.csv.gz  in=346,704,207 out=102,990,884 elapsed=183.9s

  [11554/20519] intraday_19589.csv.gz  in=346,715,834 out=103,002,511 elapsed=183.9s

  [11555/20519] intraday_19595.csv.gz  in=346,727,399 out=103,014,076 elapsed=183.9s

  [11556/20519] intraday_19596.csv.gz  in=346,740,856 out=103,027,533 elapsed=183.9s

  [11557/20519] intraday_19597.csv.gz  in=346,752,510 out=103,039,187 elapsed=184.0s

  [11558/20519] intraday_19599.csv.gz  in=346,763,192 out=103,049,869 elapsed=184.0s

  [11559/20519] intraday_19598.csv.gz  in=346,775,591 out=103,062,268 elapsed=184.0s

  [11560/20519] intraday_19600.csv.gz  in=346,787,617 out=103,074,294 elapsed=184.0s

  [11561/20519] intraday_1960.csv.gz  in=346,798,254 out=103,074,294 elapsed=184.0s

  [11562/20519] intraday_19601.csv.gz  in=346,812,281 out=103,088,321 elapsed=184.0s

  [11563/20519] intraday_19602.csv.gz  in=346,829,957 out=103,105,997 elapsed=184.0s

  [11564/20519] intraday_19603.csv.gz  in=346,841,426 out=103,117,466 elapsed=184.0s

  [11565/20519] intraday_19604.csv.gz  in=346,855,425 out=103,131,465 elapsed=184.0s

  [11566/20519] intraday_19605.csv.gz  in=346,865,522 out=103,141,562 elapsed=184.0s

  [11567/20519] intraday_19606.csv.gz  in=346,878,814 out=103,154,854 elapsed=184.1s

  [11568/20519] intraday_19607.csv.gz  in=346,890,804 out=103,166,844 elapsed=184.1s

  [11569/20519] intraday_19608.csv.gz  in=346,902,369 out=103,178,409 elapsed=184.1s

  [11570/20519] intraday_19609.csv.gz  in=346,912,560 out=103,188,600 elapsed=184.1s

  [11571/20519] intraday_19612.csv.gz  in=346,923,765 out=103,199,805 elapsed=184.1s

  [11572/20519] intraday_1961.csv.gz  in=346,935,916 out=103,199,805 elapsed=184.2s

  [11573/20519] intraday_19611.csv.gz  in=346,946,087 out=103,209,976 elapsed=184.2s

  [11574/20519] intraday_19610.csv.gz  in=346,961,110 out=103,224,999 elapsed=184.2s

  [11575/20519] intraday_19613.csv.gz  in=346,973,214 out=103,237,103 elapsed=184.2s

  [11576/20519] intraday_19614.csv.gz  in=346,986,143 out=103,250,032 elapsed=184.2s

  [11577/20519] intraday_19615.csv.gz  in=346,998,111 out=103,262,000 elapsed=184.2s

  [11578/20519] intraday_19617.csv.gz  in=347,010,106 out=103,273,995 elapsed=184.2s

  [11579/20519] intraday_19616.csv.gz  in=347,020,111 out=103,284,000 elapsed=184.3s

  [11580/20519] intraday_19618.csv.gz  in=347,030,521 out=103,294,410 elapsed=184.3s

  [11581/20519] intraday_19619.csv.gz  in=347,042,132 out=103,306,021 elapsed=184.3s

  [11582/20519] intraday_1962.csv.gz  in=347,053,880 out=103,306,021 elapsed=184.3s

  [11583/20519] intraday_19621.csv.gz  in=347,067,333 out=103,319,474 elapsed=184.3s

  [11584/20519] intraday_19620.csv.gz  in=347,079,740 out=103,331,881 elapsed=184.3s

  [11585/20519] intraday_19623.csv.gz  in=347,091,455 out=103,343,596 elapsed=184.4s

  [11586/20519] intraday_19622.csv.gz  in=347,103,259 out=103,355,400 elapsed=184.4s

  [11587/20519] intraday_19624.csv.gz  in=347,117,323 out=103,369,464 elapsed=184.4s

  [11588/20519] intraday_19626.csv.gz  in=347,128,595 out=103,380,736 elapsed=184.4s

  [11589/20519] intraday_19627.csv.gz  in=347,142,808 out=103,394,949 elapsed=184.4s

  [11590/20519] intraday_19625.csv.gz  in=347,154,549 out=103,406,632 elapsed=184.4s

  [11591/20519] intraday_1963.csv.gz  in=347,167,403 out=103,406,632 elapsed=184.4s

  [11592/20519] intraday_19628.csv.gz  in=347,182,079 out=103,421,308 elapsed=184.5s

  [11593/20519] intraday_19629.csv.gz  in=347,195,256 out=103,434,485 elapsed=184.5s

  [11594/20519] intraday_19630.csv.gz  in=347,208,406 out=103,447,635 elapsed=184.5s

  [11595/20519] intraday_19632.csv.gz  in=347,219,204 out=103,458,433 elapsed=184.5s

  [11596/20519] intraday_19631.csv.gz  in=347,235,133 out=103,474,362 elapsed=184.5s

  [11597/20519] intraday_19633.csv.gz  in=347,252,416 out=103,491,645 elapsed=184.5s

  [11598/20519] intraday_19635.csv.gz  in=347,266,494 out=103,505,723 elapsed=184.5s

  [11599/20519] intraday_19634.csv.gz  in=347,283,207 out=103,522,436 elapsed=184.5s

  [11600/20519] intraday_19637.csv.gz  in=347,294,500 out=103,533,729 elapsed=184.6s

  [11601/20519] intraday_19636.csv.gz  in=347,310,020 out=103,549,249 elapsed=184.6s

  [11602/20519] intraday_19639.csv.gz  in=347,322,330 out=103,561,559 elapsed=184.6s

  [11603/20519] intraday_19638.csv.gz  in=347,334,902 out=103,574,131 elapsed=184.6s

  [11604/20519] intraday_1964.csv.gz  in=347,349,583 out=103,574,131 elapsed=184.6s

  [11605/20519] intraday_19640.csv.gz  in=347,360,834 out=103,585,382 elapsed=184.6s

  [11606/20519] intraday_19641.csv.gz  in=347,370,987 out=103,595,535 elapsed=184.6s

  [11607/20519] intraday_19643.csv.gz  in=347,381,692 out=103,606,240 elapsed=184.7s

  [11608/20519] intraday_19644.csv.gz  in=347,397,106 out=103,621,654 elapsed=184.7s

  [11609/20519] intraday_19642.csv.gz  in=347,409,953 out=103,634,501 elapsed=184.7s

  [11610/20519] intraday_19645.csv.gz  in=347,419,055 out=103,643,603 elapsed=184.7s

  [11611/20519] intraday_19647.csv.gz  in=347,429,904 out=103,654,452 elapsed=184.7s

  [11612/20519] intraday_19646.csv.gz  in=347,442,119 out=103,666,667 elapsed=184.7s

  [11613/20519] intraday_1965.csv.gz  in=347,455,874 out=103,666,667 elapsed=184.7s

  [11614/20519] intraday_19649.csv.gz  in=347,466,376 out=103,677,169 elapsed=184.7s

  [11615/20519] intraday_19648.csv.gz  in=347,479,586 out=103,690,379 elapsed=184.8s

  [11616/20519] intraday_19651.csv.gz  in=347,492,915 out=103,703,708 elapsed=184.8s

  [11617/20519] intraday_19650.csv.gz  in=347,508,227 out=103,719,020 elapsed=184.8s

  [11618/20519] intraday_19653.csv.gz  in=347,521,805 out=103,732,598 elapsed=184.8s

  [11619/20519] intraday_19652.csv.gz  in=347,533,775 out=103,744,568 elapsed=184.8s

  [11620/20519] intraday_19654.csv.gz  in=347,546,249 out=103,757,042 elapsed=184.8s

  [11621/20519] intraday_19656.csv.gz  in=347,558,386 out=103,769,179 elapsed=184.9s

  [11622/20519] intraday_19655.csv.gz  in=347,570,490 out=103,781,283 elapsed=184.9s

  [11623/20519] intraday_19657.csv.gz  in=347,579,824 out=103,790,617 elapsed=184.9s

  [11624/20519] intraday_19658.csv.gz  in=347,593,078 out=103,803,871 elapsed=184.9s

  [11625/20519] intraday_19659.csv.gz  in=347,601,909 out=103,812,702 elapsed=184.9s

  [11626/20519] intraday_1966.csv.gz  in=347,613,144 out=103,812,702 elapsed=184.9s

  [11627/20519] intraday_19660.csv.gz  in=347,622,581 out=103,822,139 elapsed=184.9s

  [11628/20519] intraday_19661.csv.gz  in=347,632,704 out=103,832,262 elapsed=184.9s

  [11629/20519] intraday_19662.csv.gz  in=347,649,445 out=103,849,003 elapsed=185.0s

  [11630/20519] intraday_19663.csv.gz  in=347,662,674 out=103,862,232 elapsed=185.0s

  [11631/20519] intraday_19664.csv.gz  in=347,675,577 out=103,875,135 elapsed=185.0s

  [11632/20519] intraday_19665.csv.gz  in=347,686,654 out=103,886,212 elapsed=185.0s

  [11633/20519] intraday_19668.csv.gz  in=347,698,055 out=103,897,613 elapsed=185.0s

  [11634/20519] intraday_19669.csv.gz  in=347,709,817 out=103,909,375 elapsed=185.0s

  [11635/20519] intraday_19666.csv.gz  in=347,723,572 out=103,923,130 elapsed=185.1s

  [11636/20519] intraday_19667.csv.gz  in=347,738,699 out=103,938,257 elapsed=185.1s

  [11637/20519] intraday_1967.csv.gz  in=347,750,013 out=103,938,257 elapsed=185.1s

  [11638/20519] intraday_19670.csv.gz  in=347,762,405 out=103,950,649 elapsed=185.1s

  [11639/20519] intraday_19672.csv.gz  in=347,773,048 out=103,961,292 elapsed=185.1s

  [11640/20519] intraday_19673.csv.gz  in=347,785,515 out=103,973,759 elapsed=185.1s

  [11641/20519] intraday_19674.csv.gz  in=347,799,770 out=103,988,014 elapsed=185.1s

  [11642/20519] intraday_19671.csv.gz  in=347,812,593 out=104,000,837 elapsed=185.1s

  [11643/20519] intraday_19675.csv.gz  in=347,825,084 out=104,013,328 elapsed=185.1s

  [11644/20519] intraday_19677.csv.gz  in=347,834,271 out=104,022,515 elapsed=185.2s

  [11645/20519] intraday_19679.csv.gz  in=347,848,685 out=104,036,929 elapsed=185.2s

  [11646/20519] intraday_19678.csv.gz  in=347,864,890 out=104,053,134 elapsed=185.2s

  [11647/20519] intraday_1968.csv.gz  in=347,878,312 out=104,053,134 elapsed=185.2s

  [11648/20519] intraday_19676.csv.gz  in=347,890,752 out=104,065,574 elapsed=185.2s

  [11649/20519] intraday_19680.csv.gz  in=347,901,161 out=104,075,983 elapsed=185.2s

  [11650/20519] intraday_19681.csv.gz  in=347,911,951 out=104,086,773 elapsed=185.3s

  [11651/20519] intraday_19682.csv.gz  in=347,922,801 out=104,097,623 elapsed=185.3s

  [11652/20519] intraday_19684.csv.gz  in=347,937,492 out=104,112,314 elapsed=185.3s

  [11653/20519] intraday_19683.csv.gz  in=347,949,598 out=104,124,420 elapsed=185.3s

  [11654/20519] intraday_19685.csv.gz  in=347,960,744 out=104,135,566 elapsed=185.3s

  [11655/20519] intraday_19686.csv.gz  in=347,973,582 out=104,148,404 elapsed=185.3s

  [11656/20519] intraday_19688.csv.gz  in=347,985,321 out=104,160,143 elapsed=185.3s

  [11657/20519] intraday_19687.csv.gz  in=347,997,026 out=104,171,848 elapsed=185.4s

  [11658/20519] intraday_19689.csv.gz  in=348,009,553 out=104,184,375 elapsed=185.4s

  [11659/20519] intraday_1969.csv.gz  in=348,020,482 out=104,184,375 elapsed=185.4s

  [11660/20519] intraday_19690.csv.gz  in=348,032,582 out=104,196,475 elapsed=185.4s

  [11661/20519] intraday_19691.csv.gz  in=348,044,503 out=104,208,396 elapsed=185.4s

  [11662/20519] intraday_19692.csv.gz  in=348,058,096 out=104,221,989 elapsed=185.4s

  [11663/20519] intraday_19693.csv.gz  in=348,069,187 out=104,233,080 elapsed=185.5s

  [11664/20519] intraday_19694.csv.gz  in=348,079,518 out=104,243,411 elapsed=185.5s

  [11665/20519] intraday_19695.csv.gz  in=348,092,730 out=104,256,623 elapsed=185.5s

  [11666/20519] intraday_19698.csv.gz  in=348,104,673 out=104,268,566 elapsed=185.5s

  [11667/20519] intraday_19696.csv.gz  in=348,117,828 out=104,281,721 elapsed=185.5s

  [11668/20519] intraday_19697.csv.gz  in=348,131,674 out=104,295,567 elapsed=185.5s

  [11669/20519] intraday_19699.csv.gz  in=348,142,438 out=104,306,331 elapsed=185.5s

  [11670/20519] intraday_1970.csv.gz  in=348,155,398 out=104,306,331 elapsed=185.5s

  [11671/20519] intraday_19700.csv.gz  in=348,165,963 out=104,316,896 elapsed=185.5s

  [11672/20519] intraday_19701.csv.gz  in=348,176,779 out=104,327,712 elapsed=185.6s

  [11673/20519] intraday_19702.csv.gz  in=348,189,388 out=104,340,321 elapsed=185.6s

  [11674/20519] intraday_19704.csv.gz  in=348,201,655 out=104,352,588 elapsed=185.6s

  [11675/20519] intraday_19703.csv.gz  in=348,214,090 out=104,365,023 elapsed=185.6s

  [11676/20519] intraday_19705.csv.gz  in=348,229,118 out=104,380,051 elapsed=185.6s

  [11677/20519] intraday_19706.csv.gz  in=348,242,281 out=104,393,214 elapsed=185.6s

  [11678/20519] intraday_1971.csv.gz  in=348,252,721 out=104,393,214 elapsed=185.7s

  [11679/20519] intraday_19709.csv.gz  in=348,266,013 out=104,406,506 elapsed=185.7s

  [11680/20519] intraday_19708.csv.gz  in=348,276,998 out=104,417,491 elapsed=185.7s

  [11681/20519] intraday_19707.csv.gz  in=348,288,141 out=104,428,634 elapsed=185.7s

  [11682/20519] intraday_19710.csv.gz  in=348,301,173 out=104,441,666 elapsed=185.7s

  [11683/20519] intraday_19712.csv.gz  in=348,309,828 out=104,450,321 elapsed=185.7s

  [11684/20519] intraday_19711.csv.gz  in=348,322,617 out=104,463,110 elapsed=185.8s

  [11685/20519] intraday_19713.csv.gz  in=348,335,999 out=104,476,492 elapsed=185.8s

  [11686/20519] intraday_19714.csv.gz  in=348,348,635 out=104,489,128 elapsed=185.8s

  [11687/20519] intraday_19715.csv.gz  in=348,361,865 out=104,502,358 elapsed=185.8s

  [11688/20519] intraday_19717.csv.gz  in=348,372,766 out=104,513,259 elapsed=185.8s

  [11689/20519] intraday_19716.csv.gz  in=348,384,931 out=104,525,424 elapsed=185.8s

  [11690/20519] intraday_19718.csv.gz  in=348,396,261 out=104,536,754 elapsed=185.8s

  [11691/20519] intraday_19719.csv.gz  in=348,407,101 out=104,547,594 elapsed=185.9s

  [11692/20519] intraday_1972.csv.gz  in=348,418,499 out=104,547,594 elapsed=185.9s

  [11693/20519] intraday_19720.csv.gz  in=348,431,205 out=104,560,300 elapsed=185.9s

  [11694/20519] intraday_19721.csv.gz  in=348,443,173 out=104,572,268 elapsed=185.9s

  [11695/20519] intraday_19722.csv.gz  in=348,456,647 out=104,585,742 elapsed=185.9s

  [11696/20519] intraday_19723.csv.gz  in=348,467,297 out=104,596,392 elapsed=185.9s

  [11697/20519] intraday_19725.csv.gz  in=348,477,671 out=104,606,766 elapsed=185.9s

  [11698/20519] intraday_19724.csv.gz  in=348,488,893 out=104,617,988 elapsed=186.0s

  [11699/20519] intraday_19727.csv.gz  in=348,501,253 out=104,630,348 elapsed=186.0s

  [11700/20519] intraday_19728.csv.gz  in=348,515,234 out=104,644,329 elapsed=186.0s

  [11701/20519] intraday_19729.csv.gz  in=348,529,543 out=104,658,638 elapsed=186.0s

  [11702/20519] intraday_1973.csv.gz  in=348,543,154 out=104,658,638 elapsed=186.0s

  [11703/20519] intraday_19726.csv.gz  in=348,558,434 out=104,673,918 elapsed=186.0s

  [11704/20519] intraday_19730.csv.gz  in=348,572,159 out=104,687,643 elapsed=186.0s

  [11705/20519] intraday_19731.csv.gz  in=348,581,708 out=104,697,192 elapsed=186.1s

  [11706/20519] intraday_19732.csv.gz  in=348,594,105 out=104,709,589 elapsed=186.1s

  [11707/20519] intraday_19734.csv.gz  in=348,605,133 out=104,720,617 elapsed=186.1s

  [11708/20519] intraday_19733.csv.gz  in=348,618,189 out=104,733,673 elapsed=186.1s

  [11709/20519] intraday_19736.csv.gz  in=348,629,920 out=104,745,404 elapsed=186.1s

  [11710/20519] intraday_19735.csv.gz  in=348,640,273 out=104,755,757 elapsed=186.1s

  [11711/20519] intraday_19737.csv.gz  in=348,650,890 out=104,766,374 elapsed=186.1s

  [11712/20519] intraday_19738.csv.gz  in=348,663,931 out=104,779,415 elapsed=186.1s

  [11713/20519] intraday_19739.csv.gz  in=348,675,998 out=104,791,482 elapsed=186.2s

  [11714/20519] intraday_1974.csv.gz  in=348,686,876 out=104,791,482 elapsed=186.2s

  [11715/20519] intraday_19740.csv.gz  in=348,699,408 out=104,804,014 elapsed=186.2s

  [11716/20519] intraday_19741.csv.gz  in=348,709,772 out=104,814,378 elapsed=186.2s

  [11717/20519] intraday_19742.csv.gz  in=348,721,343 out=104,825,949 elapsed=186.2s

  [11718/20519] intraday_19743.csv.gz  in=348,734,857 out=104,839,463 elapsed=186.2s

  [11719/20519] intraday_19744.csv.gz  in=348,749,903 out=104,854,509 elapsed=186.2s

  [11720/20519] intraday_19745.csv.gz  in=348,764,241 out=104,868,847 elapsed=186.3s

  [11721/20519] intraday_19748.csv.gz  in=348,778,289 out=104,882,895 elapsed=186.3s

  [11722/20519] intraday_19747.csv.gz  in=348,798,506 out=104,903,112 elapsed=186.3s

  [11723/20519] intraday_19746.csv.gz  in=348,812,024 out=104,916,630 elapsed=186.3s

  [11724/20519] intraday_19749.csv.gz  in=348,822,147 out=104,926,753 elapsed=186.3s

  [11725/20519] intraday_1975.csv.gz  in=348,837,228 out=104,926,753 elapsed=186.3s

  [11726/20519] intraday_19751.csv.gz  in=348,846,886 out=104,936,411 elapsed=186.3s

  [11727/20519] intraday_19752.csv.gz  in=348,858,086 out=104,947,611 elapsed=186.4s

  [11728/20519] intraday_19750.csv.gz  in=348,872,665 out=104,962,190 elapsed=186.4s

  [11729/20519] intraday_19754.csv.gz  in=348,884,841 out=104,974,366 elapsed=186.4s

  [11730/20519] intraday_19753.csv.gz  in=348,897,432 out=104,986,957 elapsed=186.4s

  [11731/20519] intraday_19755.csv.gz  in=348,909,123 out=104,998,648 elapsed=186.4s

  [11732/20519] intraday_19756.csv.gz  in=348,921,359 out=105,010,884 elapsed=186.4s

  [11733/20519] intraday_19757.csv.gz  in=348,933,937 out=105,023,462 elapsed=186.4s

  [11734/20519] intraday_19758.csv.gz  in=348,945,971 out=105,035,496 elapsed=186.4s

  [11735/20519] intraday_19759.csv.gz  in=348,956,915 out=105,046,440 elapsed=186.4s

  [11736/20519] intraday_1976.csv.gz  in=348,969,645 out=105,046,440 elapsed=186.5s

  [11737/20519] intraday_19761.csv.gz  in=348,980,697 out=105,057,492 elapsed=186.5s

  [11738/20519] intraday_19760.csv.gz  in=348,992,268 out=105,069,063 elapsed=186.5s

  [11739/20519] intraday_19762.csv.gz  in=349,003,832 out=105,080,627 elapsed=186.5s

  [11740/20519] intraday_19763.csv.gz  in=349,015,947 out=105,092,742 elapsed=186.5s

  [11741/20519] intraday_19765.csv.gz  in=349,026,844 out=105,103,639 elapsed=186.5s

  [11742/20519] intraday_19764.csv.gz  in=349,040,584 out=105,117,379 elapsed=186.5s

  [11743/20519] intraday_19767.csv.gz  in=349,053,276 out=105,130,071 elapsed=186.5s

  [11744/20519] intraday_19766.csv.gz  in=349,065,583 out=105,142,378 elapsed=186.5s

  [11745/20519] intraday_19768.csv.gz  in=349,077,089 out=105,153,884 elapsed=186.6s

  [11746/20519] intraday_19769.csv.gz  in=349,090,339 out=105,167,134 elapsed=186.6s

  [11747/20519] intraday_1977.csv.gz  in=349,102,418 out=105,167,134 elapsed=186.6s

  [11748/20519] intraday_19770.csv.gz  in=349,117,564 out=105,182,280 elapsed=186.6s

  [11749/20519] intraday_19773.csv.gz  in=349,130,519 out=105,195,235 elapsed=186.6s

  [11750/20519] intraday_19771.csv.gz  in=349,145,368 out=105,210,084 elapsed=186.6s

  [11751/20519] intraday_19772.csv.gz  in=349,158,697 out=105,223,413 elapsed=186.6s

  [11752/20519] intraday_19774.csv.gz  in=349,178,816 out=105,243,532 elapsed=186.7s

  [11753/20519] intraday_19775.csv.gz  in=349,192,392 out=105,257,108 elapsed=186.7s

  [11754/20519] intraday_19778.csv.gz  in=349,203,805 out=105,268,521 elapsed=186.7s

  [11755/20519] intraday_19777.csv.gz  in=349,222,457 out=105,287,173 elapsed=186.7s

  [11756/20519] intraday_19776.csv.gz  in=349,249,492 out=105,313,435 elapsed=186.7s

  [11757/20519] intraday_19779.csv.gz  in=349,265,980 out=105,329,923 elapsed=186.7s

  [11758/20519] intraday_1978.csv.gz  in=349,278,876 out=105,329,923 elapsed=186.8s

  [11759/20519] intraday_19782.csv.gz  in=349,290,669 out=105,341,716 elapsed=186.8s

  [11760/20519] intraday_19780.csv.gz  in=349,302,564 out=105,353,611 elapsed=186.8s

  [11761/20519] intraday_19781.csv.gz  in=349,317,165 out=105,368,212 elapsed=186.8s

  [11762/20519] intraday_19783.csv.gz  in=349,329,957 out=105,381,004 elapsed=186.8s

  [11763/20519] intraday_19784.csv.gz  in=349,340,157 out=105,391,204 elapsed=186.8s

  [11764/20519] intraday_19785.csv.gz  in=349,352,760 out=105,403,807 elapsed=186.8s

  [11765/20519] intraday_19787.csv.gz  in=349,365,289 out=105,416,336 elapsed=186.9s

  [11766/20519] intraday_19786.csv.gz  in=349,377,523 out=105,428,570 elapsed=186.9s

  [11767/20519] intraday_19789.csv.gz  in=349,389,282 out=105,440,329 elapsed=186.9s

  [11768/20519] intraday_19788.csv.gz  in=349,400,288 out=105,451,335 elapsed=186.9s

  [11769/20519] intraday_1979.csv.gz  in=349,412,982 out=105,451,335 elapsed=186.9s

  [11770/20519] intraday_19790.csv.gz  in=349,427,420 out=105,465,773 elapsed=186.9s

  [11771/20519] intraday_19792.csv.gz  in=349,439,766 out=105,478,119 elapsed=187.0s

  [11772/20519] intraday_19791.csv.gz  in=349,452,361 out=105,490,714 elapsed=187.0s

  [11773/20519] intraday_19794.csv.gz  in=349,466,314 out=105,504,667 elapsed=187.0s

  [11774/20519] intraday_19795.csv.gz  in=349,478,677 out=105,517,030 elapsed=187.0s

  [11775/20519] intraday_19793.csv.gz  in=349,492,027 out=105,530,380 elapsed=187.0s

  [11776/20519] intraday_19797.csv.gz  in=349,502,996 out=105,541,349 elapsed=187.0s

  [11777/20519] intraday_19796.csv.gz  in=349,517,795 out=105,556,148 elapsed=187.0s

  [11778/20519] intraday_19799.csv.gz  in=349,529,652 out=105,568,005 elapsed=187.0s

  [11779/20519] intraday_1980.csv.gz  in=349,542,616 out=105,568,005 elapsed=187.1s

  [11780/20519] intraday_19798.csv.gz  in=349,556,618 out=105,582,007 elapsed=187.1s

  [11781/20519] intraday_19800.csv.gz  in=349,568,527 out=105,593,916 elapsed=187.1s

  [11782/20519] intraday_19802.csv.gz  in=349,575,880 out=105,601,269 elapsed=187.1s

  [11783/20519] intraday_19804.csv.gz  in=349,582,492 out=105,607,881 elapsed=187.1s

  [11784/20519] intraday_19801.csv.gz  in=349,594,657 out=105,620,046 elapsed=187.1s

  [11785/20519] intraday_19803.csv.gz  in=349,605,928 out=105,631,317 elapsed=187.1s

  [11786/20519] intraday_19807.csv.gz  in=349,619,679 out=105,645,068 elapsed=187.2s

  [11787/20519] intraday_19808.csv.gz  in=349,633,512 out=105,658,901 elapsed=187.2s

  [11788/20519] intraday_19805.csv.gz  in=349,650,909 out=105,676,298 elapsed=187.2s

  [11789/20519] intraday_19806.csv.gz  in=349,666,107 out=105,691,496 elapsed=187.2s

  [11790/20519] intraday_19809.csv.gz  in=349,680,071 out=105,705,460 elapsed=187.2s

  [11791/20519] intraday_1981.csv.gz  in=349,691,089 out=105,705,460 elapsed=187.2s

  [11792/20519] intraday_19810.csv.gz  in=349,707,429 out=105,721,800 elapsed=187.2s

  [11793/20519] intraday_19811.csv.gz  in=349,720,415 out=105,734,786 elapsed=187.3s

  [11794/20519] intraday_19812.csv.gz  in=349,733,935 out=105,748,306 elapsed=187.3s

  [11795/20519] intraday_19813.csv.gz  in=349,746,156 out=105,760,527 elapsed=187.3s

  [11796/20519] intraday_19814.csv.gz  in=349,761,092 out=105,775,463 elapsed=187.3s

  [11797/20519] intraday_19815.csv.gz  in=349,772,382 out=105,786,753 elapsed=187.3s

  [11798/20519] intraday_19816.csv.gz  in=349,785,578 out=105,799,949 elapsed=187.3s

  [11799/20519] intraday_19818.csv.gz  in=349,798,065 out=105,812,436 elapsed=187.4s

  [11800/20519] intraday_19819.csv.gz  in=349,810,156 out=105,824,527 elapsed=187.4s

  [11801/20519] intraday_19817.csv.gz  in=349,824,227 out=105,838,598 elapsed=187.4s

  [11802/20519] intraday_19820.csv.gz  in=349,834,467 out=105,848,838 elapsed=187.4s

  [11803/20519] intraday_1982.csv.gz  in=349,867,183 out=105,848,838 elapsed=187.4s

  [11804/20519] intraday_19821.csv.gz  in=349,883,504 out=105,865,159 elapsed=187.4s

  [11805/20519] intraday_19822.csv.gz  in=349,898,686 out=105,880,341 elapsed=187.5s

  [11806/20519] intraday_19823.csv.gz  in=349,909,745 out=105,891,400 elapsed=187.5s

  [11807/20519] intraday_19824.csv.gz  in=349,920,055 out=105,901,710 elapsed=187.5s

  [11808/20519] intraday_19825.csv.gz  in=349,933,106 out=105,914,761 elapsed=187.5s

  [11809/20519] intraday_19827.csv.gz  in=349,946,624 out=105,928,279 elapsed=187.5s

  [11810/20519] intraday_19829.csv.gz  in=349,959,476 out=105,941,131 elapsed=187.5s

  [11811/20519] intraday_19828.csv.gz  in=349,972,012 out=105,953,667 elapsed=187.5s

  [11812/20519] intraday_19826.csv.gz  in=349,985,192 out=105,966,847 elapsed=187.5s

  [11813/20519] intraday_1983.csv.gz  in=349,997,670 out=105,966,847 elapsed=187.5s

  [11814/20519] intraday_19830.csv.gz  in=350,010,410 out=105,979,587 elapsed=187.5s

  [11815/20519] intraday_19832.csv.gz  in=350,022,448 out=105,991,625 elapsed=187.5s

  [11816/20519] intraday_19833.csv.gz  in=350,037,412 out=106,006,578 elapsed=187.5s

  [11817/20519] intraday_19831.csv.gz  in=350,050,275 out=106,019,441 elapsed=187.5s

  [11818/20519] intraday_19834.csv.gz  in=350,064,715 out=106,033,881 elapsed=187.6s

  [11819/20519] intraday_19836.csv.gz  in=350,076,193 out=106,045,359 elapsed=187.6s

  [11820/20519] intraday_19837.csv.gz  in=350,087,743 out=106,056,909 elapsed=187.6s

  [11821/20519] intraday_19838.csv.gz  in=350,100,953 out=106,070,119 elapsed=187.6s

  [11822/20519] intraday_19835.csv.gz  in=350,115,338 out=106,084,504 elapsed=187.6s

  [11823/20519] intraday_19839.csv.gz  in=350,128,990 out=106,098,156 elapsed=187.6s

  [11824/20519] intraday_1984.csv.gz  in=350,143,641 out=106,098,156 elapsed=187.6s

  [11825/20519] intraday_19841.csv.gz  in=350,155,368 out=106,109,883 elapsed=187.6s

  [11826/20519] intraday_19840.csv.gz  in=350,170,183 out=106,124,698 elapsed=187.6s

  [11827/20519] intraday_19842.csv.gz  in=350,180,845 out=106,135,360 elapsed=187.6s

  [11828/20519] intraday_19844.csv.gz  in=350,191,657 out=106,146,172 elapsed=187.7s

  [11829/20519] intraday_19843.csv.gz  in=350,203,633 out=106,158,148 elapsed=187.7s

  [11830/20519] intraday_19846.csv.gz  in=350,216,068 out=106,170,583 elapsed=187.7s

  [11831/20519] intraday_19845.csv.gz  in=350,229,343 out=106,183,858 elapsed=187.7s

  [11832/20519] intraday_19848.csv.gz  in=350,243,988 out=106,198,503 elapsed=187.7s

  [11833/20519] intraday_1985.csv.gz  in=350,255,971 out=106,198,503 elapsed=187.7s

  [11834/20519] intraday_19847.csv.gz  in=350,269,713 out=106,212,245 elapsed=187.7s

  [11835/20519] intraday_19849.csv.gz  in=350,282,488 out=106,225,020 elapsed=187.7s

  [11836/20519] intraday_19850.csv.gz  in=350,294,958 out=106,237,490 elapsed=187.8s

  [11837/20519] intraday_19852.csv.gz  in=350,309,241 out=106,251,773 elapsed=187.8s

  [11838/20519] intraday_19851.csv.gz  in=350,320,781 out=106,263,313 elapsed=187.8s

  [11839/20519] intraday_19853.csv.gz  in=350,334,147 out=106,276,679 elapsed=187.8s

  [11840/20519] intraday_19854.csv.gz  in=350,346,654 out=106,289,186 elapsed=187.8s

  [11841/20519] intraday_19855.csv.gz  in=350,356,860 out=106,299,392 elapsed=187.9s

  [11842/20519] intraday_19857.csv.gz  in=350,372,783 out=106,315,315 elapsed=187.9s

  [11843/20519] intraday_19858.csv.gz  in=350,385,310 out=106,327,842 elapsed=187.9s

  [11844/20519] intraday_19856.csv.gz  in=350,400,520 out=106,343,052 elapsed=187.9s

  [11845/20519] intraday_1986.csv.gz  in=350,413,064 out=106,343,052 elapsed=187.9s

  [11846/20519] intraday_19859.csv.gz  in=350,427,910 out=106,357,898 elapsed=187.9s

  [11847/20519] intraday_19860.csv.gz  in=350,438,824 out=106,368,812 elapsed=187.9s

  [11848/20519] intraday_19861.csv.gz  in=350,450,773 out=106,380,761 elapsed=187.9s

  [11849/20519] intraday_19863.csv.gz  in=350,465,533 out=106,395,521 elapsed=187.9s

  [11850/20519] intraday_19862.csv.gz  in=350,477,885 out=106,407,873 elapsed=188.0s

  [11851/20519] intraday_19864.csv.gz  in=350,490,190 out=106,420,178 elapsed=188.0s

  [11852/20519] intraday_19865.csv.gz  in=350,503,532 out=106,433,520 elapsed=188.0s

  [11853/20519] intraday_19867.csv.gz  in=350,514,737 out=106,444,725 elapsed=188.0s

  [11854/20519] intraday_19868.csv.gz  in=350,526,197 out=106,456,185 elapsed=188.0s

  [11855/20519] intraday_19866.csv.gz  in=350,549,015 out=106,478,307 elapsed=188.0s

  [11856/20519] intraday_1987.csv.gz  in=350,561,317 out=106,478,307 elapsed=188.0s

  [11857/20519] intraday_19869.csv.gz  in=350,581,885 out=106,498,475 elapsed=188.0s

  [11858/20519] intraday_19870.csv.gz  in=350,595,854 out=106,512,444 elapsed=188.1s

  [11859/20519] intraday_19872.csv.gz  in=350,610,359 out=106,526,949 elapsed=188.1s

  [11860/20519] intraday_19871.csv.gz  in=350,624,973 out=106,541,563 elapsed=188.1s

  [11861/20519] intraday_19873.csv.gz  in=350,637,100 out=106,553,690 elapsed=188.1s

  [11862/20519] intraday_19874.csv.gz  in=350,648,191 out=106,564,781 elapsed=188.1s

  [11863/20519] intraday_19875.csv.gz  in=350,661,435 out=106,578,025 elapsed=188.1s

  [11864/20519] intraday_19876.csv.gz  in=350,674,658 out=106,591,248 elapsed=188.2s

  [11865/20519] intraday_19877.csv.gz  in=350,687,688 out=106,604,278 elapsed=188.2s

  [11866/20519] intraday_19879.csv.gz  in=350,700,152 out=106,616,742 elapsed=188.2s

  [11867/20519] intraday_1988.csv.gz  in=350,713,445 out=106,616,742 elapsed=188.2s

  [11868/20519] intraday_19878.csv.gz  in=350,724,203 out=106,627,500 elapsed=188.2s

  [11869/20519] intraday_19880.csv.gz  in=350,735,405 out=106,638,702 elapsed=188.2s

  [11870/20519] intraday_19881.csv.gz  in=350,749,264 out=106,652,561 elapsed=188.2s

  [11871/20519] intraday_19883.csv.gz  in=350,762,979 out=106,666,276 elapsed=188.2s

  [11872/20519] intraday_19882.csv.gz  in=350,776,166 out=106,679,463 elapsed=188.2s

  [11873/20519] intraday_19884.csv.gz  in=350,786,356 out=106,689,653 elapsed=188.3s

  [11874/20519] intraday_19885.csv.gz  in=350,798,522 out=106,701,819 elapsed=188.3s

  [11875/20519] intraday_19886.csv.gz  in=350,813,075 out=106,716,372 elapsed=188.3s

  [11876/20519] intraday_19887.csv.gz  in=350,828,596 out=106,731,893 elapsed=188.4s

  [11877/20519] intraday_1989.csv.gz  in=350,841,042 out=106,731,893 elapsed=188.4s

  [11878/20519] intraday_19888.csv.gz  in=350,857,750 out=106,748,601 elapsed=188.4s

  [11879/20519] intraday_19889.csv.gz  in=350,872,530 out=106,763,381 elapsed=188.4s

  [11880/20519] intraday_19890.csv.gz  in=350,884,883 out=106,775,734 elapsed=188.4s

  [11881/20519] intraday_19891.csv.gz  in=350,901,345 out=106,792,196 elapsed=188.4s

  [11882/20519] intraday_19892.csv.gz  in=350,912,429 out=106,803,280 elapsed=188.4s

  [11883/20519] intraday_19894.csv.gz  in=350,923,635 out=106,814,486 elapsed=188.5s

  [11884/20519] intraday_19893.csv.gz  in=350,939,124 out=106,829,975 elapsed=188.5s

  [11885/20519] intraday_19895.csv.gz  in=350,952,101 out=106,842,952 elapsed=188.5s

  [11886/20519] intraday_19896.csv.gz  in=350,964,138 out=106,854,989 elapsed=188.5s

  [11887/20519] intraday_19897.csv.gz  in=350,977,446 out=106,868,297 elapsed=188.5s

  [11888/20519] intraday_19898.csv.gz  in=350,990,557 out=106,881,408 elapsed=188.5s

  [11889/20519] intraday_19899.csv.gz  in=351,004,011 out=106,894,862 elapsed=188.5s

  [11890/20519] intraday_1990.csv.gz  in=351,016,464 out=106,894,862 elapsed=188.5s

  [11891/20519] intraday_19900.csv.gz  in=351,031,073 out=106,909,471 elapsed=188.6s

  [11892/20519] intraday_19901.csv.gz  in=351,041,932 out=106,920,330 elapsed=188.6s

  [11893/20519] intraday_19903.csv.gz  in=351,054,635 out=106,933,033 elapsed=188.6s

  [11894/20519] intraday_19902.csv.gz  in=351,066,770 out=106,945,168 elapsed=188.6s

  [11895/20519] intraday_19904.csv.gz  in=351,079,249 out=106,957,647 elapsed=188.6s

  [11896/20519] intraday_19905.csv.gz  in=351,091,744 out=106,970,142 elapsed=188.6s

  [11897/20519] intraday_19906.csv.gz  in=351,107,168 out=106,985,566 elapsed=188.6s

  [11898/20519] intraday_19907.csv.gz  in=351,120,246 out=106,998,644 elapsed=188.7s

  [11899/20519] intraday_19908.csv.gz  in=351,132,222 out=107,010,620 elapsed=188.7s

  [11900/20519] intraday_1991.csv.gz  in=351,143,263 out=107,010,620 elapsed=188.7s

  [11901/20519] intraday_19909.csv.gz  in=351,158,312 out=107,025,669 elapsed=188.7s

  [11902/20519] intraday_19910.csv.gz  in=351,171,277 out=107,038,634 elapsed=188.7s

  [11903/20519] intraday_19911.csv.gz  in=351,183,722 out=107,051,079 elapsed=188.7s

  [11904/20519] intraday_19912.csv.gz  in=351,197,597 out=107,064,954 elapsed=188.7s

  [11905/20519] intraday_19913.csv.gz  in=351,214,081 out=107,081,438 elapsed=188.8s

  [11906/20519] intraday_19915.csv.gz  in=351,227,833 out=107,095,190 elapsed=188.8s

  [11907/20519] intraday_19914.csv.gz  in=351,243,046 out=107,110,403 elapsed=188.8s

  [11908/20519] intraday_19916.csv.gz  in=351,257,303 out=107,124,660 elapsed=188.8s

  [11909/20519] intraday_19917.csv.gz  in=351,273,191 out=107,140,548 elapsed=188.8s

  [11910/20519] intraday_19918.csv.gz  in=351,287,404 out=107,154,761 elapsed=188.8s

  [11911/20519] intraday_19919.csv.gz  in=351,303,935 out=107,171,292 elapsed=188.8s

  [11912/20519] intraday_1992.csv.gz  in=351,316,993 out=107,171,292 elapsed=188.8s

  [11913/20519] intraday_19920.csv.gz  in=351,336,285 out=107,190,584 elapsed=188.9s

  [11914/20519] intraday_19921.csv.gz  in=351,352,147 out=107,206,446 elapsed=188.9s

  [11915/20519] intraday_19923.csv.gz  in=351,365,250 out=107,219,549 elapsed=188.9s

  [11916/20519] intraday_19924.csv.gz  in=351,384,432 out=107,238,731 elapsed=188.9s

  [11917/20519] intraday_19922.csv.gz  in=351,399,497 out=107,253,796 elapsed=188.9s

  [11918/20519] intraday_19926.csv.gz  in=351,413,863 out=107,268,162 elapsed=189.0s

  [11919/20519] intraday_19925.csv.gz  in=351,425,909 out=107,280,208 elapsed=189.0s

  [11920/20519] intraday_19928.csv.gz  in=351,438,394 out=107,292,693 elapsed=189.0s

  [11921/20519] intraday_1993.csv.gz  in=351,451,426 out=107,292,693 elapsed=189.0s

  [11922/20519] intraday_19927.csv.gz  in=351,463,532 out=107,304,799 elapsed=189.0s

  [11923/20519] intraday_19929.csv.gz  in=351,477,269 out=107,318,536 elapsed=189.0s

  [11924/20519] intraday_19932.csv.gz  in=351,489,833 out=107,331,100 elapsed=189.0s

  [11925/20519] intraday_19931.csv.gz  in=351,501,874 out=107,343,141 elapsed=189.1s

  [11926/20519] intraday_19933.csv.gz  in=351,516,861 out=107,358,128 elapsed=189.1s

  [11927/20519] intraday_19930.csv.gz  in=351,530,887 out=107,372,154 elapsed=189.1s

  [11928/20519] intraday_19935.csv.gz  in=351,544,131 out=107,385,398 elapsed=189.1s

  [11929/20519] intraday_19934.csv.gz  in=351,557,556 out=107,398,823 elapsed=189.1s

  [11930/20519] intraday_19936.csv.gz  in=351,571,919 out=107,413,186 elapsed=189.1s

  [11931/20519] intraday_19937.csv.gz  in=351,587,078 out=107,428,345 elapsed=189.1s

  [11932/20519] intraday_1994.csv.gz  in=351,599,493 out=107,428,345 elapsed=189.1s

  [11933/20519] intraday_19938.csv.gz  in=351,612,403 out=107,441,255 elapsed=189.1s

  [11934/20519] intraday_19939.csv.gz  in=351,626,187 out=107,455,039 elapsed=189.1s

  [11935/20519] intraday_19940.csv.gz  in=351,640,416 out=107,469,268 elapsed=189.1s

  [11936/20519] intraday_19941.csv.gz  in=351,653,741 out=107,482,593 elapsed=189.2s

  [11937/20519] intraday_19942.csv.gz  in=351,665,271 out=107,494,123 elapsed=189.2s

  [11938/20519] intraday_19943.csv.gz  in=351,680,106 out=107,508,958 elapsed=189.2s

  [11939/20519] intraday_19944.csv.gz  in=351,690,050 out=107,518,902 elapsed=189.2s

  [11940/20519] intraday_19945.csv.gz  in=351,699,633 out=107,528,485 elapsed=189.2s

  [11941/20519] intraday_19947.csv.gz  in=351,703,233 out=107,532,085 elapsed=189.2s

  [11942/20519] intraday_19946.csv.gz  in=351,716,033 out=107,544,885 elapsed=189.2s

  [11943/20519] intraday_19949.csv.gz  in=351,730,554 out=107,559,406 elapsed=189.3s

  [11944/20519] intraday_1995.csv.gz  in=351,741,993 out=107,559,406 elapsed=189.3s

  [11945/20519] intraday_19948.csv.gz  in=351,759,912 out=107,577,325 elapsed=189.3s

  [11946/20519] intraday_19951.csv.gz  in=351,769,726 out=107,587,139 elapsed=189.3s

  [11947/20519] intraday_19950.csv.gz  in=351,784,243 out=107,601,656 elapsed=189.3s

  [11948/20519] intraday_19953.csv.gz  in=351,799,098 out=107,616,511 elapsed=189.3s

  [11949/20519] intraday_19952.csv.gz  in=351,812,888 out=107,630,301 elapsed=189.3s

  [11950/20519] intraday_19954.csv.gz  in=351,827,389 out=107,644,802 elapsed=189.4s

  [11951/20519] intraday_19956.csv.gz  in=351,841,393 out=107,658,806 elapsed=189.4s

  [11952/20519] intraday_19955.csv.gz  in=351,854,040 out=107,671,453 elapsed=189.4s

  [11953/20519] intraday_19957.csv.gz  in=351,866,848 out=107,684,261 elapsed=189.4s

  [11954/20519] intraday_19958.csv.gz  in=351,878,399 out=107,695,812 elapsed=189.4s

  [11955/20519] intraday_1996.csv.gz  in=351,889,126 out=107,695,812 elapsed=189.4s

  [11956/20519] intraday_19960.csv.gz  in=351,903,885 out=107,710,571 elapsed=189.5s

  [11957/20519] intraday_19959.csv.gz  in=351,916,631 out=107,723,317 elapsed=189.5s

  [11958/20519] intraday_19962.csv.gz  in=351,928,884 out=107,735,570 elapsed=189.5s

  [11959/20519] intraday_19961.csv.gz  in=351,941,887 out=107,748,573 elapsed=189.5s

  [11960/20519] intraday_19964.csv.gz  in=351,956,695 out=107,763,381 elapsed=189.5s

  [11961/20519] intraday_19963.csv.gz  in=351,969,020 out=107,775,706 elapsed=189.5s

  [11962/20519] intraday_19965.csv.gz  in=351,984,531 out=107,791,217 elapsed=189.5s

  [11963/20519] intraday_19967.csv.gz  in=351,995,105 out=107,801,791 elapsed=189.5s

  [11964/20519] intraday_19966.csv.gz  in=352,022,470 out=107,829,156 elapsed=189.6s

  [11965/20519] intraday_19969.csv.gz  in=352,035,498 out=107,842,184 elapsed=189.6s

  [11966/20519] intraday_1997.csv.gz  in=352,045,564 out=107,842,184 elapsed=189.6s

  [11967/20519] intraday_19968.csv.gz  in=352,058,784 out=107,855,404 elapsed=189.6s

  [11968/20519] intraday_19970.csv.gz  in=352,072,425 out=107,869,045 elapsed=189.6s

  [11969/20519] intraday_19972.csv.gz  in=352,085,048 out=107,881,668 elapsed=189.6s

  [11970/20519] intraday_19971.csv.gz  in=352,096,892 out=107,893,512 elapsed=189.6s

  [11971/20519] intraday_19974.csv.gz  in=352,114,582 out=107,911,202 elapsed=189.7s

  [11972/20519] intraday_19973.csv.gz  in=352,127,922 out=107,924,542 elapsed=189.7s

  [11973/20519] intraday_19976.csv.gz  in=352,142,390 out=107,939,010 elapsed=189.7s

  [11974/20519] intraday_19975.csv.gz  in=352,153,505 out=107,950,125 elapsed=189.7s

  [11975/20519] intraday_19977.csv.gz  in=352,168,397 out=107,965,017 elapsed=189.7s

  [11976/20519] intraday_19978.csv.gz  in=352,182,020 out=107,978,640 elapsed=189.7s

  [11977/20519] intraday_1998.csv.gz  in=352,195,734 out=107,978,640 elapsed=189.7s

  [11978/20519] intraday_19979.csv.gz  in=352,208,120 out=107,991,026 elapsed=189.7s

  [11979/20519] intraday_19980.csv.gz  in=352,219,645 out=108,002,551 elapsed=189.7s

  [11980/20519] intraday_19981.csv.gz  in=352,231,864 out=108,014,770 elapsed=189.8s

  [11981/20519] intraday_19982.csv.gz  in=352,251,580 out=108,034,202 elapsed=189.8s

  [11982/20519] intraday_19983.csv.gz  in=352,266,233 out=108,048,855 elapsed=189.8s

  [11983/20519] intraday_19984.csv.gz  in=352,279,488 out=108,062,110 elapsed=189.8s

  [11984/20519] intraday_19985.csv.gz  in=352,290,422 out=108,073,044 elapsed=189.8s

  [11985/20519] intraday_19987.csv.gz  in=352,301,590 out=108,084,212 elapsed=189.9s

  [11986/20519] intraday_19986.csv.gz  in=352,312,616 out=108,095,238 elapsed=189.9s

  [11987/20519] intraday_19988.csv.gz  in=352,325,557 out=108,108,179 elapsed=189.9s

  [11988/20519] intraday_19989.csv.gz  in=352,338,853 out=108,121,475 elapsed=189.9s

  [11989/20519] intraday_1999.csv.gz  in=352,350,588 out=108,121,475 elapsed=189.9s

  [11990/20519] intraday_19990.csv.gz  in=352,363,842 out=108,134,729 elapsed=189.9s

  [11991/20519] intraday_19991.csv.gz  in=352,379,249 out=108,150,136 elapsed=189.9s

  [11992/20519] intraday_19992.csv.gz  in=352,390,817 out=108,161,704 elapsed=189.9s

  [11993/20519] intraday_19993.csv.gz  in=352,403,654 out=108,174,541 elapsed=190.0s

  [11994/20519] intraday_19994.csv.gz  in=352,415,074 out=108,185,961 elapsed=190.0s

  [11995/20519] intraday_19996.csv.gz  in=352,429,192 out=108,200,079 elapsed=190.0s

  [11996/20519] intraday_19995.csv.gz  in=352,443,963 out=108,214,850 elapsed=190.0s

  [11997/20519] intraday_19998.csv.gz  in=352,453,489 out=108,224,376 elapsed=190.0s

  [11998/20519] intraday_19997.csv.gz  in=352,466,428 out=108,237,315 elapsed=190.0s

  [11999/20519] intraday_2000.csv.gz  in=352,480,105 out=108,237,315 elapsed=190.0s

  [12000/20519] intraday_19999.csv.gz  in=352,496,078 out=108,253,288 elapsed=190.0s

  [12001/20519] intraday_20000.csv.gz  in=352,511,246 out=108,268,456 elapsed=190.1s

  [12002/20519] intraday_20001.csv.gz  in=352,523,391 out=108,280,601 elapsed=190.1s

  [12003/20519] intraday_20002.csv.gz  in=352,538,381 out=108,295,591 elapsed=190.1s

  [12004/20519] intraday_20003.csv.gz  in=352,549,709 out=108,306,919 elapsed=190.1s

  [12005/20519] intraday_20004.csv.gz  in=352,562,408 out=108,319,618 elapsed=190.1s

  [12006/20519] intraday_20007.csv.gz  in=352,575,180 out=108,332,390 elapsed=190.1s

  [12007/20519] intraday_20005.csv.gz  in=352,587,775 out=108,344,985 elapsed=190.2s

  [12008/20519] intraday_20006.csv.gz  in=352,601,772 out=108,358,982 elapsed=190.2s

  [12009/20519] intraday_20008.csv.gz  in=352,614,383 out=108,371,593 elapsed=190.2s

  [12010/20519] intraday_20009.csv.gz  in=352,626,693 out=108,383,903 elapsed=190.2s

  [12011/20519] intraday_2001.csv.gz  in=352,640,341 out=108,383,903 elapsed=190.2s

  [12012/20519] intraday_20011.csv.gz  in=352,650,890 out=108,394,452 elapsed=190.2s

  [12013/20519] intraday_20010.csv.gz  in=352,662,121 out=108,405,683 elapsed=190.2s

  [12014/20519] intraday_20012.csv.gz  in=352,677,932 out=108,421,494 elapsed=190.3s

  [12015/20519] intraday_20013.csv.gz  in=352,692,274 out=108,435,836 elapsed=190.3s

  [12016/20519] intraday_20015.csv.gz  in=352,707,076 out=108,450,638 elapsed=190.3s

  [12017/20519] intraday_20016.csv.gz  in=352,718,746 out=108,462,308 elapsed=190.3s

  [12018/20519] intraday_20014.csv.gz  in=352,733,419 out=108,476,981 elapsed=190.3s

  [12019/20519] intraday_20017.csv.gz  in=352,743,837 out=108,487,399 elapsed=190.3s

  [12020/20519] intraday_20018.csv.gz  in=352,756,733 out=108,500,295 elapsed=190.4s

  [12021/20519] intraday_20019.csv.gz  in=352,769,969 out=108,513,531 elapsed=190.4s

  [12022/20519] intraday_2002.csv.gz  in=352,786,881 out=108,513,531 elapsed=190.4s

  [12023/20519] intraday_20020.csv.gz  in=352,799,223 out=108,525,873 elapsed=190.4s

  [12024/20519] intraday_20021.csv.gz  in=352,810,949 out=108,537,599 elapsed=190.4s

  [12025/20519] intraday_20022.csv.gz  in=352,823,266 out=108,549,916 elapsed=190.5s

  [12026/20519] intraday_20023.csv.gz  in=352,834,549 out=108,561,199 elapsed=190.5s

  [12027/20519] intraday_20024.csv.gz  in=352,848,639 out=108,575,289 elapsed=190.5s

  [12028/20519] intraday_20025.csv.gz  in=352,861,229 out=108,587,879 elapsed=190.5s

  [12029/20519] intraday_20026.csv.gz  in=352,874,932 out=108,601,582 elapsed=190.5s

  [12030/20519] intraday_20028.csv.gz  in=352,887,104 out=108,613,754 elapsed=190.5s

  [12031/20519] intraday_20027.csv.gz  in=352,905,079 out=108,631,498 elapsed=190.5s

  [12032/20519] intraday_2003.csv.gz  in=352,914,977 out=108,631,498 elapsed=190.5s

  [12033/20519] intraday_20029.csv.gz  in=352,929,740 out=108,646,261 elapsed=190.5s

  [12034/20519] intraday_20033.csv.gz  in=352,941,852 out=108,658,373 elapsed=190.6s

  [12035/20519] intraday_20032.csv.gz  in=352,957,895 out=108,674,416 elapsed=190.6s

  [12036/20519] intraday_20031.csv.gz  in=352,974,053 out=108,690,574 elapsed=190.6s

  [12037/20519] intraday_20030.csv.gz  in=352,989,668 out=108,706,189 elapsed=190.6s

  [12038/20519] intraday_20034.csv.gz  in=353,005,306 out=108,721,827 elapsed=190.6s

  [12039/20519] intraday_20037.csv.gz  in=353,016,123 out=108,732,644 elapsed=190.6s

  [12040/20519] intraday_20035.csv.gz  in=353,027,259 out=108,743,780 elapsed=190.6s

  [12041/20519] intraday_20036.csv.gz  in=353,044,064 out=108,760,585 elapsed=190.6s

  [12042/20519] intraday_20038.csv.gz  in=353,057,330 out=108,773,851 elapsed=190.6s

  [12043/20519] intraday_2004.csv.gz  in=353,070,298 out=108,773,851 elapsed=190.6s

  [12044/20519] intraday_20039.csv.gz  in=353,083,199 out=108,786,752 elapsed=190.6s

  [12045/20519] intraday_20041.csv.gz  in=353,095,749 out=108,799,302 elapsed=190.7s

  [12046/20519] intraday_20040.csv.gz  in=353,109,389 out=108,812,942 elapsed=190.7s

  [12047/20519] intraday_20042.csv.gz  in=353,122,447 out=108,826,000 elapsed=190.7s

  [12048/20519] intraday_20043.csv.gz  in=353,136,335 out=108,839,888 elapsed=190.7s

  [12049/20519] intraday_20044.csv.gz  in=353,147,919 out=108,851,472 elapsed=190.7s

  [12050/20519] intraday_20045.csv.gz  in=353,160,282 out=108,863,835 elapsed=190.7s

  [12051/20519] intraday_20047.csv.gz  in=353,172,322 out=108,875,875 elapsed=190.8s

  [12052/20519] intraday_20046.csv.gz  in=353,184,803 out=108,888,356 elapsed=190.8s

  [12053/20519] intraday_20048.csv.gz  in=353,197,373 out=108,900,917 elapsed=190.8s

  [12054/20519] intraday_20049.csv.gz  in=353,211,571 out=108,915,115 elapsed=190.8s

  [12055/20519] intraday_2005.csv.gz  in=353,223,060 out=108,915,115 elapsed=190.8s

  [12056/20519] intraday_20050.csv.gz  in=353,237,841 out=108,929,896 elapsed=190.8s

  [12057/20519] intraday_20051.csv.gz  in=353,250,485 out=108,942,540 elapsed=190.8s

  [12058/20519] intraday_20052.csv.gz  in=353,264,627 out=108,956,682 elapsed=190.8s

  [12059/20519] intraday_20054.csv.gz  in=353,277,704 out=108,969,759 elapsed=190.8s

  [12060/20519] intraday_20053.csv.gz  in=353,290,817 out=108,982,872 elapsed=190.9s

  [12061/20519] intraday_20055.csv.gz  in=353,305,459 out=108,997,514 elapsed=190.9s

  [12062/20519] intraday_20056.csv.gz  in=353,322,060 out=109,014,115 elapsed=190.9s

  [12063/20519] intraday_20058.csv.gz  in=353,335,244 out=109,027,299 elapsed=190.9s

  [12064/20519] intraday_20057.csv.gz  in=353,350,251 out=109,042,306 elapsed=190.9s

  [12065/20519] intraday_20059.csv.gz  in=353,366,735 out=109,058,790 elapsed=190.9s

  [12066/20519] intraday_2006.csv.gz  in=353,379,594 out=109,058,790 elapsed=190.9s

  [12067/20519] intraday_20060.csv.gz  in=353,394,775 out=109,073,971 elapsed=190.9s

  [12068/20519] intraday_20061.csv.gz  in=353,410,506 out=109,089,702 elapsed=191.0s

  [12069/20519] intraday_20063.csv.gz  in=353,430,730 out=109,109,926 elapsed=191.0s

  [12070/20519] intraday_20062.csv.gz  in=353,447,564 out=109,126,760 elapsed=191.0s

  [12071/20519] intraday_20064.csv.gz  in=353,462,585 out=109,141,781 elapsed=191.0s

  [12072/20519] intraday_20065.csv.gz  in=353,479,164 out=109,158,360 elapsed=191.0s

  [12073/20519] intraday_20066.csv.gz  in=353,492,504 out=109,171,700 elapsed=191.0s

  [12074/20519] intraday_20067.csv.gz  in=353,507,560 out=109,186,756 elapsed=191.0s

  [12075/20519] intraday_20068.csv.gz  in=353,520,424 out=109,199,620 elapsed=191.0s

  [12076/20519] intraday_2007.csv.gz  in=353,530,305 out=109,199,620 elapsed=191.0s

  [12077/20519] intraday_20069.csv.gz  in=353,543,968 out=109,213,283 elapsed=191.1s

  [12078/20519] intraday_20070.csv.gz  in=353,555,549 out=109,224,864 elapsed=191.1s

  [12079/20519] intraday_20071.csv.gz  in=353,569,695 out=109,239,010 elapsed=191.1s

  [12080/20519] intraday_20072.csv.gz  in=353,582,622 out=109,251,937 elapsed=191.1s

  [12081/20519] intraday_20073.csv.gz  in=353,598,564 out=109,267,879 elapsed=191.1s

  [12082/20519] intraday_20074.csv.gz  in=353,609,858 out=109,279,173 elapsed=191.1s

  [12083/20519] intraday_20076.csv.gz  in=353,624,601 out=109,293,916 elapsed=191.1s

  [12084/20519] intraday_20075.csv.gz  in=353,636,684 out=109,305,999 elapsed=191.1s

  [12085/20519] intraday_20078.csv.gz  in=353,649,806 out=109,319,121 elapsed=191.2s

  [12086/20519] intraday_20077.csv.gz  in=353,663,709 out=109,333,024 elapsed=191.2s

  [12087/20519] intraday_2008.csv.gz  in=353,676,051 out=109,333,024 elapsed=191.2s

  [12088/20519] intraday_20079.csv.gz  in=353,690,390 out=109,347,363 elapsed=191.2s

  [12089/20519] intraday_20081.csv.gz  in=353,703,728 out=109,360,701 elapsed=191.2s

  [12090/20519] intraday_20080.csv.gz  in=353,718,771 out=109,375,744 elapsed=191.2s

  [12091/20519] intraday_20083.csv.gz  in=353,731,746 out=109,388,719 elapsed=191.2s

  [12092/20519] intraday_20082.csv.gz  in=353,745,191 out=109,402,164 elapsed=191.3s

  [12093/20519] intraday_20084.csv.gz  in=353,759,654 out=109,416,627 elapsed=191.3s

  [12094/20519] intraday_20085.csv.gz  in=353,771,754 out=109,428,727 elapsed=191.3s

  [12095/20519] intraday_20086.csv.gz  in=353,786,725 out=109,443,698 elapsed=191.3s

  [12096/20519] intraday_20087.csv.gz  in=353,796,720 out=109,453,693 elapsed=191.3s

  [12097/20519] intraday_20089.csv.gz  in=353,809,724 out=109,466,697 elapsed=191.3s

  [12098/20519] intraday_20088.csv.gz  in=353,822,804 out=109,479,777 elapsed=191.3s

  [12099/20519] intraday_20090.csv.gz  in=353,826,678 out=109,483,651 elapsed=191.4s

  [12100/20519] intraday_2009.csv.gz  in=353,837,555 out=109,483,651 elapsed=191.4s

  [12101/20519] intraday_20093.csv.gz  in=353,850,593 out=109,496,689 elapsed=191.4s

  [12102/20519] intraday_20094.csv.gz  in=353,860,117 out=109,506,213 elapsed=191.5s

  [12103/20519] intraday_20092.csv.gz  in=353,872,762 out=109,518,836 elapsed=191.5s

  [12104/20519] intraday_20091.csv.gz  in=353,889,275 out=109,535,349 elapsed=191.5s

  [12105/20519] intraday_20095.csv.gz  in=353,901,423 out=109,547,497 elapsed=191.5s

  [12106/20519] intraday_20097.csv.gz  in=353,912,796 out=109,558,870 elapsed=191.5s

  [12107/20519] intraday_20098.csv.gz  in=353,925,278 out=109,571,352 elapsed=191.5s

  [12108/20519] intraday_20099.csv.gz  in=353,938,222 out=109,584,296 elapsed=191.5s

  [12109/20519] intraday_2010.csv.gz  in=353,950,481 out=109,584,296 elapsed=191.5s

  [12110/20519] intraday_20096.csv.gz  in=353,965,428 out=109,599,243 elapsed=191.6s

  [12111/20519] intraday_20100.csv.gz  in=353,978,102 out=109,611,917 elapsed=191.6s

  [12112/20519] intraday_20102.csv.gz  in=353,989,630 out=109,623,445 elapsed=191.6s

  [12113/20519] intraday_20101.csv.gz  in=353,999,528 out=109,633,343 elapsed=191.6s

  [12114/20519] intraday_20103.csv.gz  in=354,012,552 out=109,646,367 elapsed=191.6s

  [12115/20519] intraday_20105.csv.gz  in=354,023,823 out=109,657,638 elapsed=191.6s

  [12116/20519] intraday_20107.csv.gz  in=354,037,110 out=109,670,925 elapsed=191.7s

  [12117/20519] intraday_20106.csv.gz  in=354,048,476 out=109,682,291 elapsed=191.7s

  [12118/20519] intraday_20104.csv.gz  in=354,068,858 out=109,702,525 elapsed=191.7s

  [12119/20519] intraday_20108.csv.gz  in=354,083,116 out=109,716,783 elapsed=191.7s

  [12120/20519] intraday_2011.csv.gz  in=354,094,078 out=109,716,783 elapsed=191.7s

  [12121/20519] intraday_20109.csv.gz  in=354,105,286 out=109,727,991 elapsed=191.7s

  [12122/20519] intraday_20110.csv.gz  in=354,115,493 out=109,738,198 elapsed=191.7s

  [12123/20519] intraday_20112.csv.gz  in=354,128,322 out=109,751,027 elapsed=191.8s

  [12124/20519] intraday_20111.csv.gz  in=354,140,241 out=109,762,946 elapsed=191.8s

  [12125/20519] intraday_20113.csv.gz  in=354,152,647 out=109,775,352 elapsed=191.8s

  [12126/20519] intraday_20114.csv.gz  in=354,164,296 out=109,786,962 elapsed=191.8s

  [12127/20519] intraday_20116.csv.gz  in=354,176,268 out=109,798,934 elapsed=191.8s

  [12128/20519] intraday_20118.csv.gz  in=354,188,114 out=109,810,780 elapsed=191.8s

  [12129/20519] intraday_20117.csv.gz  in=354,199,392 out=109,822,058 elapsed=191.8s

  [12130/20519] intraday_20119.csv.gz  in=354,211,761 out=109,834,427 elapsed=191.8s

  [12131/20519] intraday_20115.csv.gz  in=354,245,819 out=109,867,875 elapsed=191.9s

  [12132/20519] intraday_2012.csv.gz  in=354,259,359 out=109,867,875 elapsed=191.9s

  [12133/20519] intraday_20120.csv.gz  in=354,271,901 out=109,880,417 elapsed=191.9s

  [12134/20519] intraday_20121.csv.gz  in=354,285,545 out=109,894,061 elapsed=191.9s

  [12135/20519] intraday_20122.csv.gz  in=354,297,681 out=109,906,197 elapsed=191.9s

  [12136/20519] intraday_20123.csv.gz  in=354,308,816 out=109,917,332 elapsed=191.9s

  [12137/20519] intraday_20126.csv.gz  in=354,322,447 out=109,930,963 elapsed=192.0s

  [12138/20519] intraday_20125.csv.gz  in=354,336,043 out=109,944,559 elapsed=192.0s

  [12139/20519] intraday_20124.csv.gz  in=354,347,519 out=109,956,035 elapsed=192.0s

  [12140/20519] intraday_20127.csv.gz  in=354,360,404 out=109,968,920 elapsed=192.0s

  [12141/20519] intraday_20128.csv.gz  in=354,370,535 out=109,979,051 elapsed=192.0s

  [12142/20519] intraday_2013.csv.gz  in=354,381,952 out=109,979,051 elapsed=192.0s

  [12143/20519] intraday_20130.csv.gz  in=354,392,325 out=109,989,424 elapsed=192.0s

  [12144/20519] intraday_20131.csv.gz  in=354,403,981 out=110,001,080 elapsed=192.1s

  [12145/20519] intraday_20129.csv.gz  in=354,415,402 out=110,012,501 elapsed=192.1s

  [12146/20519] intraday_20132.csv.gz  in=354,428,444 out=110,025,543 elapsed=192.1s

  [12147/20519] intraday_20133.csv.gz  in=354,441,037 out=110,038,136 elapsed=192.1s

  [12148/20519] intraday_20135.csv.gz  in=354,452,545 out=110,049,644 elapsed=192.1s

  [12149/20519] intraday_20136.csv.gz  in=354,464,766 out=110,061,865 elapsed=192.1s

  [12150/20519] intraday_20134.csv.gz  in=354,479,256 out=110,076,355 elapsed=192.1s

  [12151/20519] intraday_20137.csv.gz  in=354,490,194 out=110,087,293 elapsed=192.1s

  [12152/20519] intraday_20138.csv.gz  in=354,503,205 out=110,100,304 elapsed=192.1s

  [12153/20519] intraday_2014.csv.gz  in=354,514,223 out=110,100,304 elapsed=192.5s

  [12154/20519] intraday_20139.csv.gz  in=354,526,557 out=110,112,638 elapsed=192.6s

  [12155/20519] intraday_20140.csv.gz  in=354,541,935 out=110,127,933 elapsed=192.6s

  [12156/20519] intraday_20142.csv.gz  in=354,555,070 out=110,141,068 elapsed=192.6s

  [12157/20519] intraday_20141.csv.gz  in=354,571,655 out=110,157,497 elapsed=192.6s

  [12158/20519] intraday_20143.csv.gz  in=354,584,177 out=110,170,019 elapsed=192.6s

  [12159/20519] intraday_20144.csv.gz  in=354,595,714 out=110,181,556 elapsed=192.6s

  [12160/20519] intraday_20145.csv.gz  in=354,610,167 out=110,196,009 elapsed=192.6s

  [12161/20519] intraday_20146.csv.gz  in=354,621,699 out=110,207,541 elapsed=192.7s

  [12162/20519] intraday_20147.csv.gz  in=354,632,664 out=110,218,506 elapsed=192.7s

  [12163/20519] intraday_20148.csv.gz  in=354,643,794 out=110,229,636 elapsed=192.7s

  [12164/20519] intraday_20149.csv.gz  in=354,658,020 out=110,243,862 elapsed=192.7s

  [12165/20519] intraday_2015.csv.gz  in=354,669,155 out=110,243,862 elapsed=192.7s

  [12166/20519] intraday_20150.csv.gz  in=354,681,328 out=110,256,035 elapsed=192.7s

  [12167/20519] intraday_20152.csv.gz  in=354,692,590 out=110,267,297 elapsed=192.7s

  [12168/20519] intraday_20151.csv.gz  in=354,705,752 out=110,280,459 elapsed=192.7s

  [12169/20519] intraday_20153.csv.gz  in=354,717,514 out=110,292,221 elapsed=192.8s

  [12170/20519] intraday_20154.csv.gz  in=354,727,445 out=110,302,152 elapsed=192.8s

  [12171/20519] intraday_20155.csv.gz  in=354,741,154 out=110,315,861 elapsed=192.8s

  [12172/20519] intraday_20158.csv.gz  in=354,755,144 out=110,329,851 elapsed=192.8s

  [12173/20519] intraday_20156.csv.gz  in=354,768,541 out=110,343,248 elapsed=192.8s

  [12174/20519] intraday_20157.csv.gz  in=354,782,281 out=110,356,988 elapsed=192.8s

  [12175/20519] intraday_20159.csv.gz  in=354,793,405 out=110,368,112 elapsed=192.8s

  [12176/20519] intraday_20160.csv.gz  in=354,802,478 out=110,377,185 elapsed=192.9s

  [12177/20519] intraday_2016.csv.gz  in=354,817,485 out=110,377,185 elapsed=192.9s

  [12178/20519] intraday_20162.csv.gz  in=354,830,589 out=110,390,289 elapsed=192.9s

  [12179/20519] intraday_20161.csv.gz  in=354,842,482 out=110,402,182 elapsed=192.9s

  [12180/20519] intraday_20163.csv.gz  in=354,853,537 out=110,413,237 elapsed=192.9s

  [12181/20519] intraday_20164.csv.gz  in=354,863,931 out=110,423,631 elapsed=192.9s

  [12182/20519] intraday_20165.csv.gz  in=354,875,447 out=110,435,147 elapsed=192.9s

  [12183/20519] intraday_20166.csv.gz  in=354,886,130 out=110,445,830 elapsed=193.0s

  [12184/20519] intraday_20168.csv.gz  in=354,898,398 out=110,458,098 elapsed=193.0s

  [12185/20519] intraday_20167.csv.gz  in=354,911,506 out=110,471,206 elapsed=193.0s

  [12186/20519] intraday_2017.csv.gz  in=354,922,896 out=110,471,206 elapsed=193.0s

  [12187/20519] intraday_20169.csv.gz  in=354,935,478 out=110,483,788 elapsed=193.0s

  [12188/20519] intraday_20171.csv.gz  in=354,946,407 out=110,494,717 elapsed=193.0s

  [12189/20519] intraday_20172.csv.gz  in=354,958,729 out=110,507,039 elapsed=193.0s

  [12190/20519] intraday_20170.csv.gz  in=354,969,401 out=110,517,711 elapsed=193.0s

  [12191/20519] intraday_20173.csv.gz  in=354,984,369 out=110,532,679 elapsed=193.0s

  [12192/20519] intraday_20174.csv.gz  in=354,998,002 out=110,546,312 elapsed=193.1s

  [12193/20519] intraday_20175.csv.gz  in=355,012,167 out=110,560,477 elapsed=193.1s

  [12194/20519] intraday_20176.csv.gz  in=355,024,473 out=110,572,783 elapsed=193.1s

  [12195/20519] intraday_20177.csv.gz  in=355,039,050 out=110,587,360 elapsed=193.1s

  [12196/20519] intraday_20178.csv.gz  in=355,049,762 out=110,598,072 elapsed=193.1s

  [12197/20519] intraday_20179.csv.gz  in=355,063,743 out=110,612,053 elapsed=193.2s

  [12198/20519] intraday_20180.csv.gz  in=355,074,525 out=110,622,835 elapsed=193.2s

  [12199/20519] intraday_2018.csv.gz  in=355,086,491 out=110,622,835 elapsed=193.2s

  [12200/20519] intraday_20181.csv.gz  in=355,098,853 out=110,635,197 elapsed=193.2s

  [12201/20519] intraday_20183.csv.gz  in=355,111,491 out=110,647,835 elapsed=193.2s

  [12202/20519] intraday_20184.csv.gz  in=355,124,371 out=110,660,715 elapsed=193.2s

  [12203/20519] intraday_20185.csv.gz  in=355,136,339 out=110,672,683 elapsed=193.2s

  [12204/20519] intraday_20182.csv.gz  in=355,148,162 out=110,684,506 elapsed=193.2s

  [12205/20519] intraday_20186.csv.gz  in=355,161,353 out=110,697,697 elapsed=193.2s

  [12206/20519] intraday_20187.csv.gz  in=355,171,890 out=110,708,234 elapsed=193.3s

  [12207/20519] intraday_20188.csv.gz  in=355,183,113 out=110,719,457 elapsed=193.3s

  [12208/20519] intraday_2019.csv.gz  in=355,194,120 out=110,719,457 elapsed=193.3s

  [12209/20519] intraday_20189.csv.gz  in=355,206,295 out=110,731,632 elapsed=193.3s

  [12210/20519] intraday_20190.csv.gz  in=355,218,310 out=110,743,647 elapsed=193.4s

  [12211/20519] intraday_20191.csv.gz  in=355,232,937 out=110,758,182 elapsed=193.4s

  [12212/20519] intraday_20192.csv.gz  in=355,246,068 out=110,771,313 elapsed=193.4s

  [12213/20519] intraday_20193.csv.gz  in=355,259,120 out=110,784,365 elapsed=193.4s

  [12214/20519] intraday_20194.csv.gz  in=355,270,115 out=110,795,360 elapsed=193.4s

  [12215/20519] intraday_20195.csv.gz  in=355,283,431 out=110,808,676 elapsed=193.4s

  [12216/20519] intraday_20196.csv.gz  in=355,295,708 out=110,820,953 elapsed=193.5s

  [12217/20519] intraday_2020.csv.gz  in=355,307,525 out=110,820,953 elapsed=193.5s

  [12218/20519] intraday_20198.csv.gz  in=355,321,796 out=110,835,215 elapsed=193.5s

  [12219/20519] intraday_20199.csv.gz  in=355,336,914 out=110,850,333 elapsed=193.5s

  [12220/20519] intraday_20197.csv.gz  in=355,348,422 out=110,861,841 elapsed=193.5s

  [12221/20519] intraday_20202.csv.gz  in=355,362,858 out=110,876,277 elapsed=193.6s

  [12222/20519] intraday_20201.csv.gz  in=355,376,139 out=110,889,558 elapsed=193.6s

  [12223/20519] intraday_20200.csv.gz  in=355,390,105 out=110,903,524 elapsed=193.6s

  [12224/20519] intraday_20203.csv.gz  in=355,404,453 out=110,917,872 elapsed=193.6s

  [12225/20519] intraday_20204.csv.gz  in=355,417,824 out=110,931,243 elapsed=193.6s

  [12226/20519] intraday_20205.csv.gz  in=355,433,127 out=110,946,546 elapsed=193.6s

  [12227/20519] intraday_20207.csv.gz  in=355,446,059 out=110,959,478 elapsed=193.6s

  [12228/20519] intraday_20206.csv.gz  in=355,463,651 out=110,977,070 elapsed=193.7s

  [12229/20519] intraday_20209.csv.gz  in=355,475,669 out=110,989,088 elapsed=193.7s

  [12230/20519] intraday_20208.csv.gz  in=355,492,056 out=111,005,475 elapsed=193.7s

  [12231/20519] intraday_2021.csv.gz  in=355,504,363 out=111,005,475 elapsed=193.7s

  [12232/20519] intraday_20210.csv.gz  in=355,517,573 out=111,018,685 elapsed=193.7s

  [12233/20519] intraday_20211.csv.gz  in=355,528,490 out=111,029,602 elapsed=193.7s

  [12234/20519] intraday_20213.csv.gz  in=355,539,102 out=111,040,214 elapsed=193.7s

  [12235/20519] intraday_20214.csv.gz  in=355,551,887 out=111,052,999 elapsed=193.7s

  [12236/20519] intraday_20212.csv.gz  in=355,565,965 out=111,067,077 elapsed=193.7s

  [12237/20519] intraday_20215.csv.gz  in=355,578,327 out=111,079,439 elapsed=193.8s

  [12238/20519] intraday_20217.csv.gz  in=355,589,080 out=111,090,192 elapsed=193.8s

  [12239/20519] intraday_20216.csv.gz  in=355,604,305 out=111,105,417 elapsed=193.8s

  [12240/20519] intraday_20219.csv.gz  in=355,617,679 out=111,118,791 elapsed=193.8s

  [12241/20519] intraday_20218.csv.gz  in=355,629,418 out=111,130,530 elapsed=193.8s

  [12242/20519] intraday_2022.csv.gz  in=355,644,947 out=111,130,530 elapsed=193.8s

  [12243/20519] intraday_20220.csv.gz  in=355,657,336 out=111,142,919 elapsed=193.9s

  [12244/20519] intraday_20221.csv.gz  in=355,669,610 out=111,155,193 elapsed=193.9s

  [12245/20519] intraday_20222.csv.gz  in=355,686,362 out=111,171,831 elapsed=193.9s

  [12246/20519] intraday_20223.csv.gz  in=355,701,020 out=111,186,489 elapsed=193.9s

  [12247/20519] intraday_20225.csv.gz  in=355,715,089 out=111,200,558 elapsed=193.9s

  [12248/20519] intraday_20224.csv.gz  in=355,727,579 out=111,213,048 elapsed=193.9s

  [12249/20519] intraday_20226.csv.gz  in=355,740,263 out=111,225,732 elapsed=194.0s

  [12250/20519] intraday_20228.csv.gz  in=355,751,711 out=111,237,180 elapsed=194.0s

  [12251/20519] intraday_20227.csv.gz  in=355,764,577 out=111,250,046 elapsed=194.0s

  [12252/20519] intraday_20229.csv.gz  in=355,779,055 out=111,264,524 elapsed=194.0s

  [12253/20519] intraday_20230.csv.gz  in=355,789,066 out=111,274,535 elapsed=194.0s

  [12254/20519] intraday_2023.csv.gz  in=355,800,150 out=111,274,535 elapsed=194.0s

  [12255/20519] intraday_20231.csv.gz  in=355,808,784 out=111,283,169 elapsed=194.0s

  [12256/20519] intraday_20234.csv.gz  in=355,808,839 out=111,283,204 elapsed=194.0s

  [12257/20519] intraday_20233.csv.gz  in=355,812,704 out=111,287,069 elapsed=194.0s

  [12258/20519] intraday_20235.csv.gz  in=355,813,900 out=111,288,265 elapsed=194.0s

  [12259/20519] intraday_20232.csv.gz  in=355,825,524 out=111,299,889 elapsed=194.0s

  [12260/20519] intraday_20237.csv.gz  in=355,825,938 out=111,300,303 elapsed=194.0s

  [12261/20519] intraday_20236.csv.gz  in=355,826,155 out=111,300,520 elapsed=194.0s

  [12262/20519] intraday_20238.csv.gz  in=355,826,501 out=111,300,866 elapsed=194.0s

  [12263/20519] intraday_20239.csv.gz  in=355,826,805 out=111,301,170 elapsed=194.1s

  [12264/20519] intraday_20240.csv.gz  in=355,827,573 out=111,301,938 elapsed=194.1s

  [12265/20519] intraday_20241.csv.gz  in=355,828,090 out=111,302,455 elapsed=194.1s

  [12266/20519] intraday_20242.csv.gz  in=355,828,375 out=111,302,740 elapsed=194.1s

  [12267/20519] intraday_20243.csv.gz  in=355,828,731 out=111,303,096 elapsed=194.1s

  [12268/20519] intraday_20244.csv.gz  in=355,829,144 out=111,303,509 elapsed=194.1s

  [12269/20519] intraday_2024.csv.gz  in=355,843,682 out=111,303,509 elapsed=194.1s

  [12270/20519] intraday_20247.csv.gz  in=355,844,384 out=111,304,211 elapsed=194.1s

  [12271/20519] intraday_20245.csv.gz  in=355,844,881 out=111,304,708 elapsed=194.1s

  [12272/20519] intraday_20248.csv.gz  in=355,845,104 out=111,304,931 elapsed=194.1s

  [12273/20519] intraday_20246.csv.gz  in=355,846,656 out=111,306,483 elapsed=194.1s

  [12274/20519] intraday_20249.csv.gz  in=355,846,931 out=111,306,758 elapsed=194.1s

  [12275/20519] intraday_20250.csv.gz  in=355,847,199 out=111,307,026 elapsed=194.1s

  [12276/20519] intraday_20251.csv.gz  in=355,847,656 out=111,307,483 elapsed=194.1s

  [12277/20519] intraday_20252.csv.gz  in=355,848,123 out=111,307,950 elapsed=194.1s

  [12278/20519] intraday_2025.csv.gz  in=355,863,184 out=111,307,950 elapsed=194.1s

  [12279/20519] intraday_20255.csv.gz  in=355,863,506 out=111,308,272 elapsed=194.2s

  [12280/20519] intraday_20254.csv.gz  in=355,863,680 out=111,308,446 elapsed=194.2s

  [12281/20519] intraday_20256.csv.gz  in=355,863,800 out=111,308,566 elapsed=194.2s

  [12282/20519] intraday_20253.csv.gz  in=355,864,113 out=111,308,879 elapsed=194.2s

  [12283/20519] intraday_20258.csv.gz  in=355,864,428 out=111,309,194 elapsed=194.2s

  [12284/20519] intraday_20259.csv.gz  in=355,865,860 out=111,310,626 elapsed=194.2s

  [12285/20519] intraday_20260.csv.gz  in=355,866,262 out=111,311,028 elapsed=194.2s

  [12286/20519] intraday_20262.csv.gz  in=355,866,332 out=111,311,098 elapsed=194.2s

  [12287/20519] intraday_20261.csv.gz  in=355,866,809 out=111,311,575 elapsed=194.2s

  [12288/20519] intraday_20263.csv.gz  in=355,867,598 out=111,312,364 elapsed=194.2s

  [12289/20519] intraday_2026.csv.gz  in=355,881,746 out=111,312,364 elapsed=194.2s

  [12290/20519] intraday_20257.csv.gz  in=355,895,103 out=111,325,721 elapsed=194.2s

  [12291/20519] intraday_20264.csv.gz  in=355,895,402 out=111,326,020 elapsed=194.2s

  [12292/20519] intraday_20266.csv.gz  in=355,895,591 out=111,326,209 elapsed=194.2s

  [12293/20519] intraday_20265.csv.gz  in=355,896,697 out=111,327,315 elapsed=194.2s

  [12294/20519] intraday_20267.csv.gz  in=355,896,962 out=111,327,580 elapsed=194.2s

  [12295/20519] intraday_20270.csv.gz  in=355,897,430 out=111,328,048 elapsed=194.3s

  [12296/20519] intraday_20269.csv.gz  in=355,897,725 out=111,328,343 elapsed=194.3s

  [12297/20519] intraday_20271.csv.gz  in=355,898,056 out=111,328,674 elapsed=194.3s

  [12298/20519] intraday_2027.csv.gz  in=355,912,281 out=111,328,674 elapsed=194.3s

  [12299/20519] intraday_20272.csv.gz  in=355,912,387 out=111,328,780 elapsed=194.3s

  [12300/20519] intraday_20274.csv.gz  in=355,912,504 out=111,328,897 elapsed=194.3s

  [12301/20519] intraday_20275.csv.gz  in=355,912,603 out=111,328,996 elapsed=194.3s

  [12302/20519] intraday_20268.csv.gz  in=355,917,189 out=111,333,582 elapsed=194.3s

  [12303/20519] intraday_20273.csv.gz  in=355,917,250 out=111,333,643 elapsed=194.3s

  [12304/20519] intraday_20277.csv.gz  in=355,917,729 out=111,334,122 elapsed=194.3s

  [12305/20519] intraday_20278.csv.gz  in=355,918,098 out=111,334,491 elapsed=194.3s

  [12306/20519] intraday_20276.csv.gz  in=355,918,255 out=111,334,648 elapsed=194.3s

  [12307/20519] intraday_20279.csv.gz  in=355,918,399 out=111,334,792 elapsed=194.4s

  [12308/20519] intraday_20281.csv.gz  in=355,918,562 out=111,334,955 elapsed=194.4s

  [12309/20519] intraday_20283.csv.gz  in=355,918,771 out=111,335,164 elapsed=194.4s

  [12310/20519] intraday_2028.csv.gz  in=355,932,289 out=111,335,164 elapsed=194.4s

  [12311/20519] intraday_20280.csv.gz  in=355,938,160 out=111,341,035 elapsed=194.4s

  [12312/20519] intraday_20285.csv.gz  in=355,938,302 out=111,341,177 elapsed=194.4s

  [12313/20519] intraday_20282.csv.gz  in=355,957,713 out=111,360,588 elapsed=194.4s

  [12314/20519] intraday_20284.csv.gz  in=355,957,933 out=111,360,808 elapsed=194.4s

  [12315/20519] intraday_20286.csv.gz  in=355,958,381 out=111,361,256 elapsed=194.4s

  [12316/20519] intraday_20287.csv.gz  in=355,959,132 out=111,362,007 elapsed=194.4s

  [12317/20519] intraday_20289.csv.gz  in=355,959,573 out=111,362,448 elapsed=194.4s

  [12318/20519] intraday_20290.csv.gz  in=355,959,702 out=111,362,577 elapsed=194.4s

  [12319/20519] intraday_20288.csv.gz  in=355,961,499 out=111,364,374 elapsed=194.5s

  [12320/20519] intraday_2029.csv.gz  in=355,973,544 out=111,364,374 elapsed=194.5s

  [12321/20519] intraday_20291.csv.gz  in=355,973,635 out=111,364,465 elapsed=194.5s

  [12322/20519] intraday_20292.csv.gz  in=355,973,848 out=111,364,678 elapsed=194.5s

  [12323/20519] intraday_20295.csv.gz  in=355,974,416 out=111,365,246 elapsed=194.5s

  [12324/20519] intraday_20293.csv.gz  in=355,976,142 out=111,366,972 elapsed=194.5s

  [12325/20519] intraday_20297.csv.gz  in=355,976,211 out=111,367,041 elapsed=194.5s

  [12326/20519] intraday_20294.csv.gz  in=355,980,810 out=111,371,640 elapsed=194.5s

  [12327/20519] intraday_20298.csv.gz  in=355,980,977 out=111,371,807 elapsed=194.5s

  [12328/20519] intraday_20296.csv.gz  in=355,981,027 out=111,371,857 elapsed=194.5s

  [12329/20519] intraday_20300.csv.gz  in=355,981,683 out=111,372,513 elapsed=194.5s

  [12330/20519] intraday_20299.csv.gz  in=355,982,544 out=111,373,374 elapsed=194.5s

  [12331/20519] intraday_20302.csv.gz  in=355,982,742 out=111,373,572 elapsed=194.5s

  [12332/20519] intraday_20301.csv.gz  in=355,982,969 out=111,373,799 elapsed=194.5s

  [12333/20519] intraday_20303.csv.gz  in=355,983,431 out=111,374,261 elapsed=194.5s

  [12334/20519] intraday_20304.csv.gz  in=355,983,558 out=111,374,388 elapsed=194.6s

  [12335/20519] intraday_2030.csv.gz  in=355,995,829 out=111,374,388 elapsed=194.6s

  [12336/20519] intraday_20305.csv.gz  in=355,996,239 out=111,374,798 elapsed=194.6s

  [12337/20519] intraday_20307.csv.gz  in=355,996,476 out=111,375,035 elapsed=194.6s

  [12338/20519] intraday_20306.csv.gz  in=355,996,823 out=111,375,382 elapsed=194.6s

  [12339/20519] intraday_20308.csv.gz  in=355,997,105 out=111,375,664 elapsed=194.6s

  [12340/20519] intraday_20309.csv.gz  in=355,997,684 out=111,376,243 elapsed=194.6s

  [12341/20519] intraday_20310.csv.gz  in=355,997,939 out=111,376,498 elapsed=194.6s

  [12342/20519] intraday_20311.csv.gz  in=355,998,224 out=111,376,783 elapsed=194.6s

  [12343/20519] intraday_20313.csv.gz  in=355,998,644 out=111,377,203 elapsed=194.6s

  [12344/20519] intraday_20312.csv.gz  in=355,998,981 out=111,377,540 elapsed=194.6s

  [12345/20519] intraday_2031.csv.gz  in=356,009,704 out=111,377,540 elapsed=194.6s

  [12346/20519] intraday_20315.csv.gz  in=356,009,864 out=111,377,700 elapsed=194.6s

  [12347/20519] intraday_20314.csv.gz  in=356,010,917 out=111,378,753 elapsed=194.6s

  [12348/20519] intraday_20316.csv.gz  in=356,011,702 out=111,379,538 elapsed=194.6s

  [12349/20519] intraday_20319.csv.gz  in=356,012,572 out=111,380,408 elapsed=194.6s

  [12350/20519] intraday_20317.csv.gz  in=356,013,663 out=111,381,499 elapsed=194.6s

  [12351/20519] intraday_20318.csv.gz  in=356,014,709 out=111,382,545 elapsed=194.6s

  [12352/20519] intraday_20320.csv.gz  in=356,016,241 out=111,384,077 elapsed=194.6s

  [12353/20519] intraday_20321.csv.gz  in=356,016,887 out=111,384,723 elapsed=194.7s

  [12354/20519] intraday_2032.csv.gz  in=356,028,727 out=111,384,723 elapsed=194.7s

  [12355/20519] intraday_20322.csv.gz  in=356,028,889 out=111,384,885 elapsed=194.7s

  [12356/20519] intraday_20323.csv.gz  in=356,029,830 out=111,385,826 elapsed=194.7s

  [12357/20519] intraday_20324.csv.gz  in=356,030,220 out=111,386,216 elapsed=194.7s

  [12358/20519] intraday_20325.csv.gz  in=356,030,547 out=111,386,543 elapsed=194.7s

  [12359/20519] intraday_20327.csv.gz  in=356,030,903 out=111,386,899 elapsed=194.7s

  [12360/20519] intraday_20328.csv.gz  in=356,031,206 out=111,387,202 elapsed=194.7s

  [12361/20519] intraday_20326.csv.gz  in=356,034,096 out=111,390,092 elapsed=194.7s

  [12362/20519] intraday_20330.csv.gz  in=356,034,465 out=111,390,461 elapsed=194.7s

  [12363/20519] intraday_20329.csv.gz  in=356,039,441 out=111,395,437 elapsed=194.7s

  [12364/20519] intraday_20331.csv.gz  in=356,039,602 out=111,395,598 elapsed=194.7s

  [12365/20519] intraday_2033.csv.gz  in=356,051,115 out=111,395,598 elapsed=194.7s

  [12366/20519] intraday_20332.csv.gz  in=356,051,671 out=111,396,154 elapsed=194.7s

  [12367/20519] intraday_20333.csv.gz  in=356,051,789 out=111,396,272 elapsed=194.7s

  [12368/20519] intraday_20335.csv.gz  in=356,052,047 out=111,396,530 elapsed=194.7s

  [12369/20519] intraday_20337.csv.gz  in=356,052,740 out=111,397,223 elapsed=194.7s

  [12370/20519] intraday_20336.csv.gz  in=356,054,052 out=111,398,535 elapsed=194.7s

  [12371/20519] intraday_20334.csv.gz  in=356,065,005 out=111,409,488 elapsed=194.7s

  [12372/20519] intraday_20339.csv.gz  in=356,065,269 out=111,409,752 elapsed=194.7s

  [12373/20519] intraday_20338.csv.gz  in=356,070,500 out=111,414,983 elapsed=194.7s

  [12374/20519] intraday_20340.csv.gz  in=356,071,087 out=111,415,570 elapsed=194.7s

  [12375/20519] intraday_20342.csv.gz  in=356,071,563 out=111,416,046 elapsed=194.7s

  [12376/20519] intraday_20341.csv.gz  in=356,071,732 out=111,416,215 elapsed=194.7s

  [12377/20519] intraday_2034.csv.gz  in=356,085,842 out=111,416,215 elapsed=194.7s

  [12378/20519] intraday_20343.csv.gz  in=356,086,636 out=111,417,009 elapsed=194.7s

  [12379/20519] intraday_20345.csv.gz  in=356,087,062 out=111,417,435 elapsed=194.8s

  [12380/20519] intraday_20344.csv.gz  in=356,087,789 out=111,418,162 elapsed=194.8s

  [12381/20519] intraday_20346.csv.gz  in=356,088,118 out=111,418,491 elapsed=194.8s

  [12382/20519] intraday_20347.csv.gz  in=356,089,217 out=111,419,590 elapsed=194.8s

  [12383/20519] intraday_20348.csv.gz  in=356,090,189 out=111,420,562 elapsed=194.8s

  [12384/20519] intraday_20350.csv.gz  in=356,091,712 out=111,422,085 elapsed=194.8s

  [12385/20519] intraday_20349.csv.gz  in=356,093,240 out=111,423,613 elapsed=194.8s

  [12386/20519] intraday_2035.csv.gz  in=356,104,176 out=111,423,613 elapsed=194.8s

  [12387/20519] intraday_20351.csv.gz  in=356,104,789 out=111,424,226 elapsed=194.8s

  [12388/20519] intraday_20354.csv.gz  in=356,105,112 out=111,424,549 elapsed=194.8s

  [12389/20519] intraday_20353.csv.gz  in=356,105,707 out=111,425,144 elapsed=194.8s

  [12390/20519] intraday_20352.csv.gz  in=356,115,090 out=111,434,527 elapsed=194.8s

  [12391/20519] intraday_20356.csv.gz  in=356,115,632 out=111,435,069 elapsed=194.8s

  [12392/20519] intraday_20355.csv.gz  in=356,115,708 out=111,435,145 elapsed=194.8s

  [12393/20519] intraday_20358.csv.gz  in=356,116,184 out=111,435,621 elapsed=194.8s

  [12394/20519] intraday_20359.csv.gz  in=356,116,662 out=111,436,099 elapsed=194.8s

  [12395/20519] intraday_20357.csv.gz  in=356,116,845 out=111,436,282 elapsed=194.8s

  [12396/20519] intraday_20361.csv.gz  in=356,117,209 out=111,436,646 elapsed=194.8s

  [12397/20519] intraday_20360.csv.gz  in=356,118,256 out=111,437,693 elapsed=194.9s

  [12398/20519] intraday_20363.csv.gz  in=356,118,766 out=111,438,203 elapsed=194.9s

  [12399/20519] intraday_2036.csv.gz  in=356,131,649 out=111,438,203 elapsed=194.9s

  [12400/20519] intraday_20362.csv.gz  in=356,131,969 out=111,438,523 elapsed=194.9s

  [12401/20519] intraday_20364.csv.gz  in=356,132,536 out=111,439,090 elapsed=194.9s

  [12402/20519] intraday_20365.csv.gz  in=356,133,148 out=111,439,702 elapsed=194.9s

  [12403/20519] intraday_20366.csv.gz  in=356,133,419 out=111,439,973 elapsed=194.9s

  [12404/20519] intraday_20367.csv.gz  in=356,133,745 out=111,440,299 elapsed=194.9s

  [12405/20519] intraday_20368.csv.gz  in=356,134,059 out=111,440,613 elapsed=194.9s

  [12406/20519] intraday_20370.csv.gz  in=356,134,458 out=111,441,012 elapsed=194.9s

  [12407/20519] intraday_20371.csv.gz  in=356,134,914 out=111,441,468 elapsed=194.9s

  [12408/20519] intraday_20369.csv.gz  in=356,135,187 out=111,441,741 elapsed=194.9s

  [12409/20519] intraday_20372.csv.gz  in=356,135,402 out=111,441,956 elapsed=194.9s

  [12410/20519] intraday_20373.csv.gz  in=356,136,038 out=111,442,592 elapsed=194.9s

  [12411/20519] intraday_20374.csv.gz  in=356,136,403 out=111,442,957 elapsed=194.9s

  [12412/20519] intraday_2037.csv.gz  in=356,148,793 out=111,442,957 elapsed=194.9s

  [12413/20519] intraday_20375.csv.gz  in=356,149,238 out=111,443,402 elapsed=194.9s

  [12414/20519] intraday_20376.csv.gz  in=356,149,430 out=111,443,594 elapsed=194.9s

  [12415/20519] intraday_20377.csv.gz  in=356,149,670 out=111,443,834 elapsed=195.0s

  [12416/20519] intraday_20379.csv.gz  in=356,161,762 out=111,455,926 elapsed=195.0s

  [12417/20519] intraday_20378.csv.gz  in=356,179,025 out=111,473,189 elapsed=195.0s

  [12418/20519] intraday_2038.csv.gz  in=356,192,415 out=111,473,189 elapsed=195.0s

  [12419/20519] intraday_20380.csv.gz  in=356,205,539 out=111,486,313 elapsed=195.0s

  [12420/20519] intraday_20381.csv.gz  in=356,214,912 out=111,495,686 elapsed=195.0s

  [12421/20519] intraday_20382.csv.gz  in=356,227,746 out=111,508,520 elapsed=195.0s

  [12422/20519] intraday_20383.csv.gz  in=356,242,193 out=111,522,967 elapsed=195.1s

  [12423/20519] intraday_20384.csv.gz  in=356,254,820 out=111,535,594 elapsed=195.1s

  [12424/20519] intraday_20385.csv.gz  in=356,266,223 out=111,546,997 elapsed=195.1s

  [12425/20519] intraday_20386.csv.gz  in=356,278,494 out=111,559,268 elapsed=195.1s

  [12426/20519] intraday_20387.csv.gz  in=356,291,498 out=111,572,272 elapsed=195.1s

  [12427/20519] intraday_20389.csv.gz  in=356,303,039 out=111,583,813 elapsed=195.1s

  [12428/20519] intraday_2039.csv.gz  in=356,321,260 out=111,583,813 elapsed=195.1s

  [12429/20519] intraday_20388.csv.gz  in=356,330,279 out=111,592,832 elapsed=195.1s

  [12430/20519] intraday_20390.csv.gz  in=356,343,231 out=111,605,784 elapsed=195.1s

  [12431/20519] intraday_20391.csv.gz  in=356,354,562 out=111,617,115 elapsed=195.2s

  [12432/20519] intraday_20393.csv.gz  in=356,364,195 out=111,626,748 elapsed=195.2s

  [12433/20519] intraday_20392.csv.gz  in=356,374,625 out=111,637,178 elapsed=195.2s

  [12434/20519] intraday_20394.csv.gz  in=356,388,410 out=111,650,963 elapsed=195.2s

  [12435/20519] intraday_20395.csv.gz  in=356,401,620 out=111,664,173 elapsed=195.2s

  [12436/20519] intraday_20396.csv.gz  in=356,412,172 out=111,674,725 elapsed=195.2s

  [12437/20519] intraday_20397.csv.gz  in=356,422,058 out=111,684,611 elapsed=195.2s

  [12438/20519] intraday_20399.csv.gz  in=356,434,743 out=111,697,296 elapsed=195.2s

  [12439/20519] intraday_20398.csv.gz  in=356,446,873 out=111,709,426 elapsed=195.2s

  [12440/20519] intraday_2040.csv.gz  in=356,460,840 out=111,709,426 elapsed=195.2s

  [12441/20519] intraday_20400.csv.gz  in=356,472,390 out=111,720,976 elapsed=195.3s

  [12442/20519] intraday_20401.csv.gz  in=356,483,328 out=111,731,914 elapsed=195.3s

  [12443/20519] intraday_20402.csv.gz  in=356,495,638 out=111,744,224 elapsed=195.3s

  [12444/20519] intraday_20403.csv.gz  in=356,507,262 out=111,755,848 elapsed=195.3s

  [12445/20519] intraday_20404.csv.gz  in=356,519,223 out=111,767,809 elapsed=195.3s

  [12446/20519] intraday_20405.csv.gz  in=356,529,763 out=111,778,349 elapsed=195.3s

  [12447/20519] intraday_20406.csv.gz  in=356,544,671 out=111,793,257 elapsed=195.3s

  [12448/20519] intraday_20407.csv.gz  in=356,556,850 out=111,805,436 elapsed=195.4s

  [12449/20519] intraday_20408.csv.gz  in=356,570,321 out=111,818,907 elapsed=195.4s

  [12450/20519] intraday_20409.csv.gz  in=356,581,442 out=111,830,028 elapsed=195.4s

  [12451/20519] intraday_2041.csv.gz  in=356,596,276 out=111,830,028 elapsed=195.4s

  [12452/20519] intraday_20410.csv.gz  in=356,607,581 out=111,841,333 elapsed=195.4s

  [12453/20519] intraday_20411.csv.gz  in=356,618,777 out=111,852,529 elapsed=195.5s

  [12454/20519] intraday_20413.csv.gz  in=356,632,607 out=111,866,359 elapsed=195.5s

  [12455/20519] intraday_20412.csv.gz  in=356,644,948 out=111,878,700 elapsed=195.5s

  [12456/20519] intraday_20414.csv.gz  in=356,656,530 out=111,890,282 elapsed=195.5s

  [12457/20519] intraday_20415.csv.gz  in=356,667,378 out=111,901,130 elapsed=195.5s

  [12458/20519] intraday_20416.csv.gz  in=356,677,427 out=111,911,179 elapsed=195.5s

  [12459/20519] intraday_20417.csv.gz  in=356,687,734 out=111,921,486 elapsed=195.5s

  [12460/20519] intraday_20418.csv.gz  in=356,699,522 out=111,933,274 elapsed=195.6s

  [12461/20519] intraday_20419.csv.gz  in=356,711,793 out=111,945,545 elapsed=195.6s

  [12462/20519] intraday_2042.csv.gz  in=356,725,190 out=111,945,545 elapsed=195.6s

  [12463/20519] intraday_20420.csv.gz  in=356,738,288 out=111,958,643 elapsed=195.6s

  [12464/20519] intraday_20421.csv.gz  in=356,752,745 out=111,973,100 elapsed=195.6s

  [12465/20519] intraday_20423.csv.gz  in=356,763,451 out=111,983,806 elapsed=195.6s

  [12466/20519] intraday_20422.csv.gz  in=356,774,021 out=111,994,376 elapsed=195.6s

  [12467/20519] intraday_20424.csv.gz  in=356,786,166 out=112,006,521 elapsed=195.6s

  [12468/20519] intraday_20425.csv.gz  in=356,797,508 out=112,017,863 elapsed=195.6s

  [12469/20519] intraday_20426.csv.gz  in=356,810,111 out=112,030,466 elapsed=195.6s

  [12470/20519] intraday_20428.csv.gz  in=356,820,746 out=112,041,101 elapsed=195.7s

  [12471/20519] intraday_20429.csv.gz  in=356,833,038 out=112,053,393 elapsed=195.7s

  [12472/20519] intraday_20427.csv.gz  in=356,844,284 out=112,064,639 elapsed=195.7s

  [12473/20519] intraday_2043.csv.gz  in=356,856,708 out=112,064,639 elapsed=195.7s

  [12474/20519] intraday_20430.csv.gz  in=356,870,030 out=112,077,961 elapsed=195.7s

  [12475/20519] intraday_20432.csv.gz  in=356,882,965 out=112,090,896 elapsed=195.7s

  [12476/20519] intraday_20431.csv.gz  in=356,894,888 out=112,102,819 elapsed=195.7s

  [12477/20519] intraday_20433.csv.gz  in=356,905,380 out=112,113,311 elapsed=195.7s

  [12478/20519] intraday_20434.csv.gz  in=356,914,891 out=112,122,822 elapsed=195.7s

  [12479/20519] intraday_20436.csv.gz  in=356,928,129 out=112,136,060 elapsed=195.7s

  [12480/20519] intraday_20435.csv.gz  in=356,940,613 out=112,148,544 elapsed=195.8s

  [12481/20519] intraday_20437.csv.gz  in=356,952,060 out=112,159,991 elapsed=195.8s

  [12482/20519] intraday_20438.csv.gz  in=356,963,852 out=112,171,783 elapsed=195.8s

  [12483/20519] intraday_20439.csv.gz  in=356,975,006 out=112,182,937 elapsed=195.8s

  [12484/20519] intraday_2044.csv.gz  in=356,988,378 out=112,182,937 elapsed=195.8s

  [12485/20519] intraday_20440.csv.gz  in=356,998,992 out=112,193,551 elapsed=195.8s

  [12486/20519] intraday_20441.csv.gz  in=357,011,998 out=112,206,557 elapsed=195.8s

  [12487/20519] intraday_20442.csv.gz  in=357,024,308 out=112,218,867 elapsed=195.8s

  [12488/20519] intraday_20444.csv.gz  in=357,038,022 out=112,232,581 elapsed=195.9s

  [12489/20519] intraday_20443.csv.gz  in=357,052,062 out=112,246,621 elapsed=195.9s

  [12490/20519] intraday_20446.csv.gz  in=357,061,831 out=112,256,390 elapsed=195.9s

  [12491/20519] intraday_20445.csv.gz  in=357,074,609 out=112,269,168 elapsed=195.9s

  [12492/20519] intraday_20447.csv.gz  in=357,085,617 out=112,280,176 elapsed=195.9s

  [12493/20519] intraday_20448.csv.gz  in=357,099,075 out=112,293,634 elapsed=195.9s

  [12494/20519] intraday_2045.csv.gz  in=357,110,855 out=112,293,634 elapsed=195.9s

  [12495/20519] intraday_20449.csv.gz  in=357,121,170 out=112,303,949 elapsed=195.9s

  [12496/20519] intraday_20450.csv.gz  in=357,133,491 out=112,316,270 elapsed=195.9s

  [12497/20519] intraday_20451.csv.gz  in=357,144,560 out=112,327,339 elapsed=195.9s

  [12498/20519] intraday_20452.csv.gz  in=357,154,311 out=112,337,090 elapsed=195.9s

  [12499/20519] intraday_20454.csv.gz  in=357,168,377 out=112,351,156 elapsed=195.9s

  [12500/20519] intraday_20453.csv.gz  in=357,179,182 out=112,361,961 elapsed=196.0s

  [12501/20519] intraday_20455.csv.gz  in=357,191,762 out=112,374,541 elapsed=196.0s

  [12502/20519] intraday_20456.csv.gz  in=357,203,736 out=112,386,515 elapsed=196.0s

  [12503/20519] intraday_20457.csv.gz  in=357,213,343 out=112,396,122 elapsed=196.0s

  [12504/20519] intraday_20458.csv.gz  in=357,225,113 out=112,407,892 elapsed=196.0s

  [12505/20519] intraday_20459.csv.gz  in=357,238,757 out=112,421,536 elapsed=196.0s

  [12506/20519] intraday_20460.csv.gz  in=357,254,078 out=112,436,857 elapsed=196.0s

  [12507/20519] intraday_20461.csv.gz  in=357,267,390 out=112,450,169 elapsed=196.0s

  [12508/20519] intraday_2046.csv.gz  in=357,280,348 out=112,450,169 elapsed=196.0s

  [12509/20519] intraday_20462.csv.gz  in=357,294,584 out=112,464,405 elapsed=196.1s

  [12510/20519] intraday_20463.csv.gz  in=357,306,130 out=112,475,951 elapsed=196.1s

  [12511/20519] intraday_20464.csv.gz  in=357,319,593 out=112,489,414 elapsed=196.1s

  [12512/20519] intraday_20465.csv.gz  in=357,331,253 out=112,501,074 elapsed=196.1s

  [12513/20519] intraday_20466.csv.gz  in=357,344,244 out=112,514,065 elapsed=196.1s

  [12514/20519] intraday_20467.csv.gz  in=357,354,304 out=112,524,125 elapsed=196.1s

  [12515/20519] intraday_20468.csv.gz  in=357,367,785 out=112,537,606 elapsed=196.1s

  [12516/20519] intraday_20469.csv.gz  in=357,379,286 out=112,549,107 elapsed=196.1s

  [12517/20519] intraday_2047.csv.gz  in=357,391,838 out=112,549,107 elapsed=196.1s

  [12518/20519] intraday_20470.csv.gz  in=357,402,930 out=112,560,199 elapsed=196.2s

  [12519/20519] intraday_20473.csv.gz  in=357,414,654 out=112,571,923 elapsed=196.2s

  [12520/20519] intraday_20471.csv.gz  in=357,427,348 out=112,584,617 elapsed=196.2s

  [12521/20519] intraday_20474.csv.gz  in=357,439,474 out=112,596,743 elapsed=196.2s

  [12522/20519] intraday_20472.csv.gz  in=357,451,195 out=112,608,464 elapsed=196.2s

  [12523/20519] intraday_20475.csv.gz  in=357,462,553 out=112,619,822 elapsed=196.2s

  [12524/20519] intraday_20476.csv.gz  in=357,473,148 out=112,630,417 elapsed=196.2s

  [12525/20519] intraday_20477.csv.gz  in=357,484,929 out=112,642,198 elapsed=196.2s

  [12526/20519] intraday_20478.csv.gz  in=357,496,805 out=112,654,074 elapsed=196.2s

  [12527/20519] intraday_20479.csv.gz  in=357,509,371 out=112,666,640 elapsed=196.3s

  [12528/20519] intraday_2048.csv.gz  in=357,524,447 out=112,666,640 elapsed=196.3s

  [12529/20519] intraday_20480.csv.gz  in=357,537,350 out=112,679,543 elapsed=196.3s

  [12530/20519] intraday_20481.csv.gz  in=357,547,895 out=112,690,088 elapsed=196.3s

  [12531/20519] intraday_20482.csv.gz  in=357,562,219 out=112,704,412 elapsed=196.3s

  [12532/20519] intraday_20483.csv.gz  in=357,572,332 out=112,714,525 elapsed=196.3s

  [12533/20519] intraday_20484.csv.gz  in=357,586,040 out=112,728,233 elapsed=196.3s

  [12534/20519] intraday_20486.csv.gz  in=357,599,518 out=112,741,711 elapsed=196.4s

  [12535/20519] intraday_20487.csv.gz  in=357,613,425 out=112,755,618 elapsed=196.4s

  [12536/20519] intraday_20488.csv.gz  in=357,627,860 out=112,770,053 elapsed=196.4s

  [12537/20519] intraday_20485.csv.gz  in=357,642,919 out=112,785,112 elapsed=196.4s

  [12538/20519] intraday_20489.csv.gz  in=357,657,208 out=112,799,401 elapsed=196.4s

  [12539/20519] intraday_2049.csv.gz  in=357,672,958 out=112,799,401 elapsed=196.4s

  [12540/20519] intraday_20490.csv.gz  in=357,687,784 out=112,814,227 elapsed=196.5s

  [12541/20519] intraday_20493.csv.gz  in=357,702,177 out=112,828,620 elapsed=196.5s

  [12542/20519] intraday_20491.csv.gz  in=357,717,654 out=112,844,097 elapsed=196.5s

  [12543/20519] intraday_20492.csv.gz  in=357,733,437 out=112,859,880 elapsed=196.5s

  [12544/20519] intraday_20494.csv.gz  in=357,749,569 out=112,876,012 elapsed=196.5s

  [12545/20519] intraday_20495.csv.gz  in=357,761,487 out=112,887,930 elapsed=196.5s

  [12546/20519] intraday_20496.csv.gz  in=357,774,090 out=112,900,533 elapsed=196.5s

  [12547/20519] intraday_20497.csv.gz  in=357,785,202 out=112,911,645 elapsed=196.5s

  [12548/20519] intraday_20499.csv.gz  in=357,797,488 out=112,923,931 elapsed=196.6s

  [12549/20519] intraday_20498.csv.gz  in=357,809,326 out=112,935,769 elapsed=196.6s

  [12550/20519] intraday_2050.csv.gz  in=357,822,144 out=112,935,769 elapsed=196.6s

  [12551/20519] intraday_20500.csv.gz  in=357,834,135 out=112,947,760 elapsed=196.6s

  [12552/20519] intraday_20502.csv.gz  in=357,849,144 out=112,962,769 elapsed=196.6s

  [12553/20519] intraday_20501.csv.gz  in=357,860,684 out=112,974,309 elapsed=196.6s

  [12554/20519] intraday_20503.csv.gz  in=357,871,784 out=112,985,409 elapsed=196.6s

  [12555/20519] intraday_20504.csv.gz  in=357,883,151 out=112,996,776 elapsed=196.6s

  [12556/20519] intraday_20505.csv.gz  in=357,894,263 out=113,007,888 elapsed=196.7s

  [12557/20519] intraday_20507.csv.gz  in=357,906,826 out=113,020,451 elapsed=196.7s

  [12558/20519] intraday_20508.csv.gz  in=357,920,134 out=113,033,759 elapsed=196.7s

  [12559/20519] intraday_20506.csv.gz  in=357,933,698 out=113,047,323 elapsed=196.7s

  [12560/20519] intraday_20509.csv.gz  in=357,947,258 out=113,060,883 elapsed=196.7s

  [12561/20519] intraday_2051.csv.gz  in=357,959,804 out=113,060,883 elapsed=196.7s

  [12562/20519] intraday_20510.csv.gz  in=357,972,991 out=113,074,070 elapsed=196.7s

  [12563/20519] intraday_20512.csv.gz  in=357,983,440 out=113,084,519 elapsed=196.7s

  [12564/20519] intraday_20513.csv.gz  in=357,996,484 out=113,097,563 elapsed=196.7s

  [12565/20519] intraday_20511.csv.gz  in=358,011,115 out=113,112,194 elapsed=196.8s

  [12566/20519] intraday_20514.csv.gz  in=358,024,996 out=113,126,075 elapsed=196.8s

  [12567/20519] intraday_20515.csv.gz  in=358,037,597 out=113,138,676 elapsed=196.8s

  [12568/20519] intraday_20516.csv.gz  in=358,049,744 out=113,150,823 elapsed=196.8s

  [12569/20519] intraday_20517.csv.gz  in=358,057,479 out=113,158,558 elapsed=196.8s

  [12570/20519] intraday_20518.csv.gz  in=358,068,409 out=113,169,488 elapsed=196.8s

  [12571/20519] intraday_20519.csv.gz  in=358,075,547 out=113,176,626 elapsed=196.8s

  [12572/20519] intraday_2053.csv.gz  in=358,086,578 out=113,176,626 elapsed=196.8s

  [12573/20519] intraday_2054.csv.gz  in=358,098,573 out=113,176,626 elapsed=196.8s

  [12574/20519] intraday_2052.csv.gz  in=358,119,550 out=113,176,626 elapsed=196.8s

  [12575/20519] intraday_2055.csv.gz  in=358,131,211 out=113,176,626 elapsed=196.9s

  [12576/20519] intraday_2056.csv.gz  in=358,146,524 out=113,176,626 elapsed=196.9s

  [12577/20519] intraday_2057.csv.gz  in=358,159,581 out=113,176,626 elapsed=196.9s

  [12578/20519] intraday_2058.csv.gz  in=358,174,897 out=113,176,626 elapsed=196.9s

  [12579/20519] intraday_2060.csv.gz  in=358,188,264 out=113,176,626 elapsed=196.9s

  [12580/20519] intraday_2061.csv.gz  in=358,202,678 out=113,176,626 elapsed=196.9s

  [12581/20519] intraday_2059.csv.gz  in=358,215,075 out=113,176,626 elapsed=196.9s

  [12582/20519] intraday_2062.csv.gz  in=358,227,586 out=113,176,626 elapsed=196.9s

  [12583/20519] intraday_2063.csv.gz  in=358,242,107 out=113,176,626 elapsed=196.9s

  [12584/20519] intraday_2064.csv.gz  in=358,257,139 out=113,176,626 elapsed=196.9s

  [12585/20519] intraday_2065.csv.gz  in=358,272,326 out=113,176,626 elapsed=197.0s

  [12586/20519] intraday_2067.csv.gz  in=358,284,298 out=113,176,626 elapsed=197.0s

  [12587/20519] intraday_2066.csv.gz  in=358,297,767 out=113,176,626 elapsed=197.0s

  [12588/20519] intraday_2068.csv.gz  in=358,313,929 out=113,176,626 elapsed=197.0s

  [12589/20519] intraday_2070.csv.gz  in=358,326,307 out=113,176,626 elapsed=197.0s

  [12590/20519] intraday_2069.csv.gz  in=358,339,445 out=113,176,626 elapsed=197.0s

  [12591/20519] intraday_2072.csv.gz  in=358,347,072 out=113,176,626 elapsed=197.0s

  [12592/20519] intraday_2074.csv.gz  in=358,353,189 out=113,176,626 elapsed=197.0s

  [12593/20519] intraday_2073.csv.gz  in=358,364,154 out=113,176,626 elapsed=197.0s

  [12594/20519] intraday_2071.csv.gz  in=358,379,534 out=113,176,626 elapsed=197.0s

  [12595/20519] intraday_2078.csv.gz  in=358,390,392 out=113,176,626 elapsed=197.1s

  [12596/20519] intraday_2076.csv.gz  in=358,404,948 out=113,176,626 elapsed=197.1s

  [12597/20519] intraday_2077.csv.gz  in=358,416,930 out=113,176,626 elapsed=197.1s

  [12598/20519] intraday_2075.csv.gz  in=358,431,722 out=113,176,626 elapsed=197.1s

  [12599/20519] intraday_2079.csv.gz  in=358,445,799 out=113,176,626 elapsed=197.1s

  [12600/20519] intraday_2082.csv.gz  in=358,458,650 out=113,176,626 elapsed=197.1s

  [12601/20519] intraday_2081.csv.gz  in=358,470,893 out=113,176,626 elapsed=197.1s

  [12602/20519] intraday_2080.csv.gz  in=358,485,288 out=113,176,626 elapsed=197.1s

  [12603/20519] intraday_2083.csv.gz  in=358,499,708 out=113,176,626 elapsed=197.1s

  [12604/20519] intraday_2084.csv.gz  in=358,515,024 out=113,176,626 elapsed=197.1s

  [12605/20519] intraday_2085.csv.gz  in=358,524,942 out=113,176,626 elapsed=197.2s

  [12606/20519] intraday_2086.csv.gz  in=358,536,733 out=113,176,626 elapsed=197.2s

  [12607/20519] intraday_2087.csv.gz  in=358,550,469 out=113,176,626 elapsed=197.2s

  [12608/20519] intraday_2088.csv.gz  in=358,561,738 out=113,176,626 elapsed=197.2s

  [12609/20519] intraday_2090.csv.gz  in=358,574,344 out=113,176,626 elapsed=197.2s

  [12610/20519] intraday_2089.csv.gz  in=358,585,590 out=113,176,626 elapsed=197.2s

  [12611/20519] intraday_2091.csv.gz  in=358,598,161 out=113,176,626 elapsed=197.2s

  [12612/20519] intraday_2092.csv.gz  in=358,610,892 out=113,176,626 elapsed=197.2s

  [12613/20519] intraday_2093.csv.gz  in=358,623,072 out=113,176,626 elapsed=197.2s

  [12614/20519] intraday_2094.csv.gz  in=358,635,297 out=113,176,626 elapsed=197.3s

  [12615/20519] intraday_2095.csv.gz  in=358,648,799 out=113,176,626 elapsed=197.3s

  [12616/20519] intraday_2096.csv.gz  in=358,661,124 out=113,176,626 elapsed=197.3s

  [12617/20519] intraday_2097.csv.gz  in=358,673,510 out=113,176,626 elapsed=197.3s

  [12618/20519] intraday_2098.csv.gz  in=358,686,016 out=113,176,626 elapsed=197.3s

  [12619/20519] intraday_2100.csv.gz  in=358,695,272 out=113,176,626 elapsed=197.3s

  [12620/20519] intraday_2099.csv.gz  in=358,707,763 out=113,176,626 elapsed=197.3s

  [12621/20519] intraday_2101.csv.gz  in=358,719,992 out=113,176,626 elapsed=197.3s

  [12622/20519] intraday_2102.csv.gz  in=358,732,539 out=113,176,626 elapsed=197.4s

  [12623/20519] intraday_2103.csv.gz  in=358,746,060 out=113,176,626 elapsed=197.4s

  [12624/20519] intraday_2105.csv.gz  in=358,758,397 out=113,176,626 elapsed=197.4s

  [12625/20519] intraday_2104.csv.gz  in=358,773,369 out=113,176,626 elapsed=197.4s

  [12626/20519] intraday_2108.csv.gz  in=358,786,236 out=113,176,626 elapsed=197.5s

  [12627/20519] intraday_2106.csv.gz  in=358,797,910 out=113,176,626 elapsed=197.5s

  [12628/20519] intraday_2109.csv.gz  in=358,809,027 out=113,176,626 elapsed=197.5s

  [12629/20519] intraday_2107.csv.gz  in=358,821,323 out=113,176,626 elapsed=197.5s

  [12630/20519] intraday_2112.csv.gz  in=358,832,510 out=113,176,626 elapsed=197.5s

  [12631/20519] intraday_2111.csv.gz  in=358,843,875 out=113,176,626 elapsed=197.5s

  [12632/20519] intraday_2110.csv.gz  in=358,856,893 out=113,176,626 elapsed=197.5s

  [12633/20519] intraday_2113.csv.gz  in=358,869,666 out=113,176,626 elapsed=197.5s

  [12634/20519] intraday_2114.csv.gz  in=358,881,615 out=113,176,626 elapsed=197.5s

  [12635/20519] intraday_2116.csv.gz  in=358,893,686 out=113,176,626 elapsed=197.5s

  [12636/20519] intraday_2117.csv.gz  in=358,907,862 out=113,176,626 elapsed=197.5s

  [12637/20519] intraday_2115.csv.gz  in=358,922,603 out=113,176,626 elapsed=197.5s

  [12638/20519] intraday_2118.csv.gz  in=358,935,379 out=113,176,626 elapsed=197.6s

  [12639/20519] intraday_2119.csv.gz  in=358,948,152 out=113,176,626 elapsed=197.6s

  [12640/20519] intraday_2120.csv.gz  in=358,961,180 out=113,176,626 elapsed=197.6s

  [12641/20519] intraday_2121.csv.gz  in=358,972,283 out=113,176,626 elapsed=197.6s

  [12642/20519] intraday_2123.csv.gz  in=358,984,625 out=113,176,626 elapsed=197.6s

  [12643/20519] intraday_2124.csv.gz  in=358,995,184 out=113,176,626 elapsed=197.6s

  [12644/20519] intraday_2122.csv.gz  in=359,007,584 out=113,176,626 elapsed=197.6s

  [12645/20519] intraday_2125.csv.gz  in=359,021,094 out=113,176,626 elapsed=197.6s

  [12646/20519] intraday_2128.csv.gz  in=359,033,544 out=113,176,626 elapsed=197.6s

  [12647/20519] intraday_2126.csv.gz  in=359,045,647 out=113,176,626 elapsed=197.6s

  [12648/20519] intraday_2127.csv.gz  in=359,056,681 out=113,176,626 elapsed=197.6s

  [12649/20519] intraday_2129.csv.gz  in=359,070,641 out=113,176,626 elapsed=197.7s

  [12650/20519] intraday_2130.csv.gz  in=359,082,450 out=113,176,626 elapsed=197.7s

  [12651/20519] intraday_2131.csv.gz  in=359,094,132 out=113,176,626 elapsed=197.7s

  [12652/20519] intraday_2132.csv.gz  in=359,108,162 out=113,176,626 elapsed=197.7s

  [12653/20519] intraday_2133.csv.gz  in=359,119,942 out=113,176,626 elapsed=197.7s

  [12654/20519] intraday_2135.csv.gz  in=359,132,493 out=113,176,626 elapsed=197.7s

  [12655/20519] intraday_2134.csv.gz  in=359,145,350 out=113,176,626 elapsed=197.7s

  [12656/20519] intraday_2136.csv.gz  in=359,156,213 out=113,176,626 elapsed=197.7s

  [12657/20519] intraday_2137.csv.gz  in=359,166,828 out=113,176,626 elapsed=197.7s

  [12658/20519] intraday_2138.csv.gz  in=359,180,193 out=113,176,626 elapsed=197.8s

  [12659/20519] intraday_2140.csv.gz  in=359,194,965 out=113,176,626 elapsed=197.8s

  [12660/20519] intraday_2139.csv.gz  in=359,208,778 out=113,176,626 elapsed=197.8s

  [12661/20519] intraday_2141.csv.gz  in=359,223,177 out=113,176,626 elapsed=197.8s

  [12662/20519] intraday_2144.csv.gz  in=359,234,666 out=113,176,626 elapsed=197.8s

  [12663/20519] intraday_2142.csv.gz  in=359,245,274 out=113,176,626 elapsed=197.8s

  [12664/20519] intraday_2143.csv.gz  in=359,257,165 out=113,176,626 elapsed=197.8s

  [12665/20519] intraday_2146.csv.gz  in=359,271,158 out=113,176,626 elapsed=197.8s

  [12666/20519] intraday_2147.csv.gz  in=359,282,582 out=113,176,626 elapsed=197.8s

  [12667/20519] intraday_2145.csv.gz  in=359,295,011 out=113,176,626 elapsed=197.8s

  [12668/20519] intraday_2148.csv.gz  in=359,306,419 out=113,176,626 elapsed=197.8s

  [12669/20519] intraday_2149.csv.gz  in=359,318,266 out=113,176,626 elapsed=197.9s

  [12670/20519] intraday_2151.csv.gz  in=359,329,659 out=113,176,626 elapsed=197.9s

  [12671/20519] intraday_2150.csv.gz  in=359,342,551 out=113,176,626 elapsed=197.9s

  [12672/20519] intraday_2152.csv.gz  in=359,355,559 out=113,176,626 elapsed=197.9s

  [12673/20519] intraday_2153.csv.gz  in=359,366,464 out=113,176,626 elapsed=197.9s

  [12674/20519] intraday_2154.csv.gz  in=359,378,166 out=113,176,626 elapsed=197.9s

  [12675/20519] intraday_2155.csv.gz  in=359,390,326 out=113,176,626 elapsed=197.9s

  [12676/20519] intraday_2157.csv.gz  in=359,400,933 out=113,176,626 elapsed=197.9s

  [12677/20519] intraday_2158.csv.gz  in=359,413,032 out=113,176,626 elapsed=197.9s

  [12678/20519] intraday_2159.csv.gz  in=359,422,823 out=113,176,626 elapsed=197.9s

  [12679/20519] intraday_2156.csv.gz  in=359,438,613 out=113,176,626 elapsed=198.0s

  [12680/20519] intraday_2160.csv.gz  in=359,452,999 out=113,176,626 elapsed=198.0s

  [12681/20519] intraday_2161.csv.gz  in=359,464,676 out=113,176,626 elapsed=198.0s

  [12682/20519] intraday_2162.csv.gz  in=359,480,728 out=113,176,626 elapsed=198.0s

  [12683/20519] intraday_2163.csv.gz  in=359,493,022 out=113,176,626 elapsed=198.0s

  [12684/20519] intraday_2164.csv.gz  in=359,507,772 out=113,176,626 elapsed=198.0s

  [12685/20519] intraday_2165.csv.gz  in=359,521,201 out=113,176,626 elapsed=198.0s

  [12686/20519] intraday_2168.csv.gz  in=359,533,632 out=113,176,626 elapsed=198.0s

  [12687/20519] intraday_2167.csv.gz  in=359,547,271 out=113,176,626 elapsed=198.0s

  [12688/20519] intraday_2166.csv.gz  in=359,561,881 out=113,176,626 elapsed=198.0s

  [12689/20519] intraday_2169.csv.gz  in=359,574,231 out=113,176,626 elapsed=198.1s

  [12690/20519] intraday_2170.csv.gz  in=359,586,281 out=113,176,626 elapsed=198.1s

  [12691/20519] intraday_2171.csv.gz  in=359,599,181 out=113,176,626 elapsed=198.1s

  [12692/20519] intraday_2172.csv.gz  in=359,611,805 out=113,176,626 elapsed=198.1s

  [12693/20519] intraday_2173.csv.gz  in=359,623,235 out=113,176,626 elapsed=198.1s

  [12694/20519] intraday_2176.csv.gz  in=359,634,823 out=113,176,626 elapsed=198.1s

  [12695/20519] intraday_2174.csv.gz  in=359,649,681 out=113,176,626 elapsed=198.1s

  [12696/20519] intraday_2175.csv.gz  in=359,661,961 out=113,176,626 elapsed=198.1s

  [12697/20519] intraday_2177.csv.gz  in=359,677,382 out=113,176,626 elapsed=198.1s

  [12698/20519] intraday_2178.csv.gz  in=359,687,707 out=113,176,626 elapsed=198.1s

  [12699/20519] intraday_2179.csv.gz  in=359,700,713 out=113,176,626 elapsed=198.1s

  [12700/20519] intraday_2180.csv.gz  in=359,715,109 out=113,176,626 elapsed=198.2s

  [12701/20519] intraday_2181.csv.gz  in=359,730,087 out=113,176,626 elapsed=198.2s

  [12702/20519] intraday_2183.csv.gz  in=359,743,608 out=113,176,626 elapsed=198.2s

  [12703/20519] intraday_2182.csv.gz  in=359,756,506 out=113,176,626 elapsed=198.2s

  [12704/20519] intraday_2184.csv.gz  in=359,768,499 out=113,176,626 elapsed=198.2s

  [12705/20519] intraday_2186.csv.gz  in=359,780,644 out=113,176,626 elapsed=198.2s

  [12706/20519] intraday_2185.csv.gz  in=359,793,718 out=113,176,626 elapsed=198.2s

  [12707/20519] intraday_2188.csv.gz  in=359,805,552 out=113,176,626 elapsed=198.2s

  [12708/20519] intraday_2187.csv.gz  in=359,819,769 out=113,176,626 elapsed=198.2s

  [12709/20519] intraday_2190.csv.gz  in=359,832,191 out=113,176,626 elapsed=198.2s

  [12710/20519] intraday_2189.csv.gz  in=359,848,833 out=113,176,626 elapsed=198.2s

  [12711/20519] intraday_2192.csv.gz  in=359,860,957 out=113,176,626 elapsed=198.3s

  [12712/20519] intraday_2191.csv.gz  in=359,875,433 out=113,176,626 elapsed=198.3s

  [12713/20519] intraday_2193.csv.gz  in=359,888,111 out=113,176,626 elapsed=198.3s

  [12714/20519] intraday_2194.csv.gz  in=359,899,007 out=113,176,626 elapsed=198.3s

  [12715/20519] intraday_2195.csv.gz  in=359,913,696 out=113,176,626 elapsed=198.3s

  [12716/20519] intraday_2196.csv.gz  in=359,926,969 out=113,176,626 elapsed=198.3s

  [12717/20519] intraday_2198.csv.gz  in=359,939,229 out=113,176,626 elapsed=198.3s

  [12718/20519] intraday_2197.csv.gz  in=359,954,801 out=113,176,626 elapsed=198.3s

  [12719/20519] intraday_2199.csv.gz  in=359,969,637 out=113,176,626 elapsed=198.4s

  [12720/20519] intraday_2200.csv.gz  in=359,982,887 out=113,176,626 elapsed=198.4s

  [12721/20519] intraday_2201.csv.gz  in=359,996,296 out=113,176,626 elapsed=198.4s

  [12722/20519] intraday_2202.csv.gz  in=360,010,662 out=113,176,626 elapsed=198.4s

  [12723/20519] intraday_2203.csv.gz  in=360,026,201 out=113,176,626 elapsed=198.4s

  [12724/20519] intraday_2204.csv.gz  in=360,040,464 out=113,176,626 elapsed=198.4s

  [12725/20519] intraday_2205.csv.gz  in=360,054,603 out=113,176,626 elapsed=198.4s

  [12726/20519] intraday_2206.csv.gz  in=360,068,536 out=113,176,626 elapsed=198.5s

  [12727/20519] intraday_2208.csv.gz  in=360,081,234 out=113,176,626 elapsed=198.5s

  [12728/20519] intraday_2207.csv.gz  in=360,092,905 out=113,176,626 elapsed=198.5s

  [12729/20519] intraday_2209.csv.gz  in=360,103,492 out=113,176,626 elapsed=198.5s

  [12730/20519] intraday_2211.csv.gz  in=360,111,625 out=113,176,626 elapsed=198.5s

  [12731/20519] intraday_2212.csv.gz  in=360,121,210 out=113,176,626 elapsed=198.5s

  [12732/20519] intraday_2210.csv.gz  in=360,135,905 out=113,176,626 elapsed=198.5s

  [12733/20519] intraday_2213.csv.gz  in=360,145,873 out=113,176,626 elapsed=198.5s

  [12734/20519] intraday_2214.csv.gz  in=360,161,150 out=113,176,626 elapsed=198.5s

  [12735/20519] intraday_2215.csv.gz  in=360,174,996 out=113,176,626 elapsed=198.5s

  [12736/20519] intraday_2216.csv.gz  in=360,187,269 out=113,176,626 elapsed=198.6s

  [12737/20519] intraday_2217.csv.gz  in=360,198,407 out=113,176,626 elapsed=198.6s

  [12738/20519] intraday_2218.csv.gz  in=360,212,213 out=113,176,626 elapsed=198.6s

  [12739/20519] intraday_2219.csv.gz  in=360,226,524 out=113,176,626 elapsed=198.6s

  [12740/20519] intraday_2220.csv.gz  in=360,239,256 out=113,176,626 elapsed=198.6s

  [12741/20519] intraday_2221.csv.gz  in=360,252,037 out=113,176,626 elapsed=198.6s

  [12742/20519] intraday_2222.csv.gz  in=360,266,350 out=113,176,626 elapsed=198.6s

  [12743/20519] intraday_2223.csv.gz  in=360,281,350 out=113,176,626 elapsed=198.6s

  [12744/20519] intraday_2224.csv.gz  in=360,290,897 out=113,176,626 elapsed=198.6s

  [12745/20519] intraday_2225.csv.gz  in=360,302,651 out=113,176,626 elapsed=198.6s

  [12746/20519] intraday_2226.csv.gz  in=360,316,902 out=113,176,626 elapsed=198.7s

  [12747/20519] intraday_2227.csv.gz  in=360,334,539 out=113,176,626 elapsed=198.7s

  [12748/20519] intraday_2228.csv.gz  in=360,346,414 out=113,176,626 elapsed=198.7s

  [12749/20519] intraday_2229.csv.gz  in=360,359,036 out=113,176,626 elapsed=198.7s

  [12750/20519] intraday_2231.csv.gz  in=360,371,620 out=113,176,626 elapsed=198.7s

  [12751/20519] intraday_2230.csv.gz  in=360,384,968 out=113,176,626 elapsed=198.7s

  [12752/20519] intraday_2233.csv.gz  in=360,397,442 out=113,176,626 elapsed=198.7s

  [12753/20519] intraday_2232.csv.gz  in=360,417,419 out=113,176,626 elapsed=198.7s

  [12754/20519] intraday_2234.csv.gz  in=360,430,706 out=113,176,626 elapsed=198.7s

  [12755/20519] intraday_2236.csv.gz  in=360,443,387 out=113,176,626 elapsed=198.7s

  [12756/20519] intraday_2237.csv.gz  in=360,456,733 out=113,176,626 elapsed=198.7s

  [12757/20519] intraday_2235.csv.gz  in=360,469,330 out=113,176,626 elapsed=198.7s

  [12758/20519] intraday_2238.csv.gz  in=360,481,989 out=113,176,626 elapsed=198.8s

  [12759/20519] intraday_2239.csv.gz  in=360,491,077 out=113,176,626 elapsed=198.8s

  [12760/20519] intraday_2241.csv.gz  in=360,508,181 out=113,176,626 elapsed=198.8s

  [12761/20519] intraday_2240.csv.gz  in=360,521,191 out=113,176,626 elapsed=198.8s

  [12762/20519] intraday_2243.csv.gz  in=360,535,738 out=113,176,626 elapsed=198.8s

  [12763/20519] intraday_2242.csv.gz  in=360,547,703 out=113,176,626 elapsed=198.8s

  [12764/20519] intraday_2244.csv.gz  in=360,562,288 out=113,176,626 elapsed=198.8s

  [12765/20519] intraday_2245.csv.gz  in=360,574,622 out=113,176,626 elapsed=198.8s

  [12766/20519] intraday_2246.csv.gz  in=360,587,629 out=113,176,626 elapsed=198.8s

  [12767/20519] intraday_2247.csv.gz  in=360,600,862 out=113,176,626 elapsed=198.9s

  [12768/20519] intraday_2248.csv.gz  in=360,612,033 out=113,176,626 elapsed=198.9s

  [12769/20519] intraday_2250.csv.gz  in=360,623,613 out=113,176,626 elapsed=198.9s

  [12770/20519] intraday_2249.csv.gz  in=360,636,773 out=113,176,626 elapsed=198.9s

  [12771/20519] intraday_2251.csv.gz  in=360,647,873 out=113,176,626 elapsed=198.9s

  [12772/20519] intraday_2252.csv.gz  in=360,663,001 out=113,176,626 elapsed=198.9s

  [12773/20519] intraday_2253.csv.gz  in=360,673,673 out=113,176,626 elapsed=198.9s

  [12774/20519] intraday_2255.csv.gz  in=360,686,474 out=113,176,626 elapsed=198.9s

  [12775/20519] intraday_2254.csv.gz  in=360,701,081 out=113,176,626 elapsed=198.9s

  [12776/20519] intraday_2257.csv.gz  in=360,713,697 out=113,176,626 elapsed=198.9s

  [12777/20519] intraday_2256.csv.gz  in=360,727,742 out=113,176,626 elapsed=199.0s

  [12778/20519] intraday_2258.csv.gz  in=360,740,199 out=113,176,626 elapsed=199.0s

  [12779/20519] intraday_2260.csv.gz  in=360,751,306 out=113,176,626 elapsed=199.0s

  [12780/20519] intraday_2259.csv.gz  in=360,764,698 out=113,176,626 elapsed=199.0s

  [12781/20519] intraday_2262.csv.gz  in=360,781,242 out=113,176,626 elapsed=199.0s

  [12782/20519] intraday_2261.csv.gz  in=360,793,907 out=113,176,626 elapsed=199.0s

  [12783/20519] intraday_2264.csv.gz  in=360,806,510 out=113,176,626 elapsed=199.0s

  [12784/20519] intraday_2263.csv.gz  in=360,817,312 out=113,176,626 elapsed=199.0s

  [12785/20519] intraday_2266.csv.gz  in=360,828,415 out=113,176,626 elapsed=199.1s

  [12786/20519] intraday_2265.csv.gz  in=360,840,293 out=113,176,626 elapsed=199.1s

  [12787/20519] intraday_2268.csv.gz  in=360,854,368 out=113,176,626 elapsed=199.1s

  [12788/20519] intraday_2267.csv.gz  in=360,867,683 out=113,176,626 elapsed=199.1s

  [12789/20519] intraday_2270.csv.gz  in=360,878,883 out=113,176,626 elapsed=199.1s

  [12790/20519] intraday_2269.csv.gz  in=360,890,147 out=113,176,626 elapsed=199.1s

  [12791/20519] intraday_2271.csv.gz  in=360,903,328 out=113,176,626 elapsed=199.1s

  [12792/20519] intraday_2272.csv.gz  in=360,916,373 out=113,176,626 elapsed=199.1s

  [12793/20519] intraday_2273.csv.gz  in=360,929,496 out=113,176,626 elapsed=199.1s

  [12794/20519] intraday_2274.csv.gz  in=360,941,618 out=113,176,626 elapsed=199.1s

  [12795/20519] intraday_2276.csv.gz  in=360,951,854 out=113,176,626 elapsed=199.2s

  [12796/20519] intraday_2275.csv.gz  in=360,963,645 out=113,176,626 elapsed=199.2s

  [12797/20519] intraday_2278.csv.gz  in=360,976,248 out=113,176,626 elapsed=199.2s

  [12798/20519] intraday_2277.csv.gz  in=360,990,471 out=113,176,626 elapsed=199.2s

  [12799/20519] intraday_2280.csv.gz  in=361,005,318 out=113,176,626 elapsed=199.2s

  [12800/20519] intraday_2281.csv.gz  in=361,016,465 out=113,176,626 elapsed=199.2s

  [12801/20519] intraday_2279.csv.gz  in=361,032,471 out=113,176,626 elapsed=199.2s

  [12802/20519] intraday_2282.csv.gz  in=361,044,405 out=113,176,626 elapsed=199.2s

  [12803/20519] intraday_2283.csv.gz  in=361,056,441 out=113,176,626 elapsed=199.2s

  [12804/20519] intraday_2285.csv.gz  in=361,071,481 out=113,176,626 elapsed=199.2s

  [12805/20519] intraday_2284.csv.gz  in=361,084,230 out=113,176,626 elapsed=199.3s

  [12806/20519] intraday_2286.csv.gz  in=361,095,035 out=113,176,626 elapsed=199.3s

  [12807/20519] intraday_2288.csv.gz  in=361,106,737 out=113,176,626 elapsed=199.3s

  [12808/20519] intraday_2287.csv.gz  in=361,122,341 out=113,176,626 elapsed=199.3s

  [12809/20519] intraday_2290.csv.gz  in=361,133,749 out=113,176,626 elapsed=199.4s

  [12810/20519] intraday_2289.csv.gz  in=361,147,961 out=113,176,626 elapsed=199.4s

  [12811/20519] intraday_2292.csv.gz  in=361,158,374 out=113,176,626 elapsed=199.4s

  [12812/20519] intraday_2291.csv.gz  in=361,171,737 out=113,176,626 elapsed=199.4s

  [12813/20519] intraday_2294.csv.gz  in=361,184,122 out=113,176,626 elapsed=199.4s

  [12814/20519] intraday_2293.csv.gz  in=361,195,889 out=113,176,626 elapsed=199.4s

  [12815/20519] intraday_2295.csv.gz  in=361,209,531 out=113,176,626 elapsed=199.5s

  [12816/20519] intraday_2296.csv.gz  in=361,222,693 out=113,176,626 elapsed=199.5s

  [12817/20519] intraday_2297.csv.gz  in=361,235,942 out=113,176,626 elapsed=199.5s

  [12818/20519] intraday_2298.csv.gz  in=361,245,930 out=113,176,626 elapsed=199.5s

  [12819/20519] intraday_2299.csv.gz  in=361,267,857 out=113,176,626 elapsed=199.5s

  [12820/20519] intraday_2300.csv.gz  in=361,279,742 out=113,176,626 elapsed=199.5s

  [12821/20519] intraday_2301.csv.gz  in=361,295,620 out=113,176,626 elapsed=199.5s

  [12822/20519] intraday_2303.csv.gz  in=361,311,219 out=113,176,626 elapsed=199.5s

  [12823/20519] intraday_2302.csv.gz  in=361,332,102 out=113,176,626 elapsed=199.6s

  [12824/20519] intraday_2304.csv.gz  in=361,344,581 out=113,176,626 elapsed=199.6s

  [12825/20519] intraday_2305.csv.gz  in=361,358,742 out=113,176,626 elapsed=199.6s

  [12826/20519] intraday_2306.csv.gz  in=361,372,101 out=113,176,626 elapsed=199.6s

  [12827/20519] intraday_2308.csv.gz  in=361,384,223 out=113,176,626 elapsed=199.6s

  [12828/20519] intraday_2307.csv.gz  in=361,399,013 out=113,176,626 elapsed=199.6s

  [12829/20519] intraday_2309.csv.gz  in=361,411,693 out=113,176,626 elapsed=199.6s

  [12830/20519] intraday_2312.csv.gz  in=361,423,448 out=113,176,626 elapsed=199.6s

  [12831/20519] intraday_2311.csv.gz  in=361,436,868 out=113,176,626 elapsed=199.6s

  [12832/20519] intraday_2310.csv.gz  in=361,450,300 out=113,176,626 elapsed=199.6s

  [12833/20519] intraday_2313.csv.gz  in=361,463,549 out=113,176,626 elapsed=199.6s

  [12834/20519] intraday_2314.csv.gz  in=361,478,938 out=113,176,626 elapsed=199.7s

  [12835/20519] intraday_2316.csv.gz  in=361,492,029 out=113,176,626 elapsed=199.7s

  [12836/20519] intraday_2317.csv.gz  in=361,504,491 out=113,176,626 elapsed=199.7s

  [12837/20519] intraday_2315.csv.gz  in=361,516,397 out=113,176,626 elapsed=199.7s

  [12838/20519] intraday_2318.csv.gz  in=361,528,558 out=113,176,626 elapsed=199.7s

  [12839/20519] intraday_2319.csv.gz  in=361,543,186 out=113,176,626 elapsed=199.7s

  [12840/20519] intraday_2321.csv.gz  in=361,556,211 out=113,176,626 elapsed=199.7s

  [12841/20519] intraday_2320.csv.gz  in=361,571,778 out=113,176,626 elapsed=199.7s

  [12842/20519] intraday_2323.csv.gz  in=361,585,150 out=113,176,626 elapsed=199.7s

  [12843/20519] intraday_2322.csv.gz  in=361,598,387 out=113,176,626 elapsed=199.7s

  [12844/20519] intraday_2324.csv.gz  in=361,610,685 out=113,176,626 elapsed=199.8s

  [12845/20519] intraday_2327.csv.gz  in=361,625,763 out=113,176,626 elapsed=199.8s

  [12846/20519] intraday_2325.csv.gz  in=361,638,285 out=113,176,626 elapsed=199.8s

  [12847/20519] intraday_2326.csv.gz  in=361,651,626 out=113,176,626 elapsed=199.8s

  [12848/20519] intraday_2328.csv.gz  in=361,668,114 out=113,176,626 elapsed=199.8s

  [12849/20519] intraday_2329.csv.gz  in=361,680,800 out=113,176,626 elapsed=199.8s

  [12850/20519] intraday_2330.csv.gz  in=361,694,606 out=113,176,626 elapsed=199.8s

  [12851/20519] intraday_2331.csv.gz  in=361,707,595 out=113,176,626 elapsed=199.8s

  [12852/20519] intraday_2332.csv.gz  in=361,719,638 out=113,176,626 elapsed=199.8s

  [12853/20519] intraday_2333.csv.gz  in=361,731,453 out=113,176,626 elapsed=199.8s

  [12854/20519] intraday_2334.csv.gz  in=361,749,468 out=113,176,626 elapsed=199.9s

  [12855/20519] intraday_2335.csv.gz  in=361,762,092 out=113,176,626 elapsed=199.9s

  [12856/20519] intraday_2336.csv.gz  in=361,778,759 out=113,176,626 elapsed=199.9s

  [12857/20519] intraday_2337.csv.gz  in=361,789,866 out=113,176,626 elapsed=199.9s

  [12858/20519] intraday_2338.csv.gz  in=361,805,158 out=113,176,626 elapsed=199.9s

  [12859/20519] intraday_2341.csv.gz  in=361,818,497 out=113,176,626 elapsed=199.9s

  [12860/20519] intraday_2340.csv.gz  in=361,832,880 out=113,176,626 elapsed=199.9s

  [12861/20519] intraday_2339.csv.gz  in=361,845,280 out=113,176,626 elapsed=199.9s

  [12862/20519] intraday_2343.csv.gz  in=361,859,797 out=113,176,626 elapsed=199.9s

  [12863/20519] intraday_2344.csv.gz  in=361,873,760 out=113,176,626 elapsed=199.9s

  [12864/20519] intraday_2342.csv.gz  in=361,894,977 out=113,176,626 elapsed=200.0s

  [12865/20519] intraday_2345.csv.gz  in=361,909,920 out=113,176,626 elapsed=200.0s

  [12866/20519] intraday_2346.csv.gz  in=361,921,518 out=113,176,626 elapsed=200.0s

  [12867/20519] intraday_2347.csv.gz  in=361,933,143 out=113,176,626 elapsed=200.0s

  [12868/20519] intraday_2350.csv.gz  in=361,942,209 out=113,176,626 elapsed=200.0s

  [12869/20519] intraday_2349.csv.gz  in=361,956,055 out=113,176,626 elapsed=200.0s

  [12870/20519] intraday_2348.csv.gz  in=361,969,621 out=113,176,626 elapsed=200.0s

  [12871/20519] intraday_2351.csv.gz  in=361,978,568 out=113,176,626 elapsed=200.0s

  [12872/20519] intraday_2353.csv.gz  in=361,979,977 out=113,176,626 elapsed=200.0s

  [12873/20519] intraday_2352.csv.gz  in=361,991,840 out=113,176,626 elapsed=200.0s

  [12874/20519] intraday_2355.csv.gz  in=362,005,934 out=113,176,626 elapsed=200.0s

  [12875/20519] intraday_2354.csv.gz  in=362,022,301 out=113,176,626 elapsed=200.1s

  [12876/20519] intraday_2356.csv.gz  in=362,034,863 out=113,176,626 elapsed=200.1s

  [12877/20519] intraday_2357.csv.gz  in=362,046,114 out=113,176,626 elapsed=200.1s

  [12878/20519] intraday_2358.csv.gz  in=362,061,163 out=113,176,626 elapsed=200.1s

  [12879/20519] intraday_2361.csv.gz  in=362,073,853 out=113,176,626 elapsed=200.1s

  [12880/20519] intraday_2359.csv.gz  in=362,095,656 out=113,176,626 elapsed=200.1s

  [12881/20519] intraday_2360.csv.gz  in=362,108,624 out=113,176,626 elapsed=200.1s

  [12882/20519] intraday_2362.csv.gz  in=362,126,393 out=113,176,626 elapsed=200.2s

  [12883/20519] intraday_2364.csv.gz  in=362,136,208 out=113,176,626 elapsed=200.2s

  [12884/20519] intraday_2363.csv.gz  in=362,151,285 out=113,176,626 elapsed=200.2s

  [12885/20519] intraday_2365.csv.gz  in=362,163,932 out=113,176,626 elapsed=200.2s

  [12886/20519] intraday_2366.csv.gz  in=362,177,859 out=113,176,626 elapsed=200.2s

  [12887/20519] intraday_2367.csv.gz  in=362,188,524 out=113,176,626 elapsed=200.2s

  [12888/20519] intraday_2369.csv.gz  in=362,201,085 out=113,176,626 elapsed=200.2s

  [12889/20519] intraday_2371.csv.gz  in=362,213,638 out=113,176,626 elapsed=200.2s

  [12890/20519] intraday_2368.csv.gz  in=362,225,101 out=113,176,626 elapsed=200.2s

  [12891/20519] intraday_2370.csv.gz  in=362,238,159 out=113,176,626 elapsed=200.2s

  [12892/20519] intraday_2372.csv.gz  in=362,249,074 out=113,176,626 elapsed=200.3s

  [12893/20519] intraday_2375.csv.gz  in=362,261,106 out=113,176,626 elapsed=200.3s

  [12894/20519] intraday_2373.csv.gz  in=362,273,172 out=113,176,626 elapsed=200.3s

  [12895/20519] intraday_2374.csv.gz  in=362,287,237 out=113,176,626 elapsed=200.3s

  [12896/20519] intraday_2378.csv.gz  in=362,300,163 out=113,176,626 elapsed=200.3s

  [12897/20519] intraday_2377.csv.gz  in=362,318,442 out=113,176,626 elapsed=200.3s

  [12898/20519] intraday_2376.csv.gz  in=362,330,821 out=113,176,626 elapsed=200.3s

  [12899/20519] intraday_2379.csv.gz  in=362,340,306 out=113,176,626 elapsed=200.3s

  [12900/20519] intraday_2381.csv.gz  in=362,356,439 out=113,176,626 elapsed=200.4s

  [12901/20519] intraday_2382.csv.gz  in=362,369,904 out=113,176,626 elapsed=200.4s

  [12902/20519] intraday_2380.csv.gz  in=362,382,266 out=113,176,626 elapsed=200.4s

  [12903/20519] intraday_2383.csv.gz  in=362,397,591 out=113,176,626 elapsed=200.4s

  [12904/20519] intraday_2386.csv.gz  in=362,409,893 out=113,176,626 elapsed=200.4s

  [12905/20519] intraday_2384.csv.gz  in=362,424,410 out=113,176,626 elapsed=200.4s

  [12906/20519] intraday_2385.csv.gz  in=362,436,468 out=113,176,626 elapsed=200.4s

  [12907/20519] intraday_2388.csv.gz  in=362,448,095 out=113,176,626 elapsed=200.5s

  [12908/20519] intraday_2390.csv.gz  in=362,459,791 out=113,176,626 elapsed=200.5s

  [12909/20519] intraday_2389.csv.gz  in=362,472,088 out=113,176,626 elapsed=200.5s

  [12910/20519] intraday_2387.csv.gz  in=362,495,364 out=113,176,626 elapsed=200.5s

  [12911/20519] intraday_2391.csv.gz  in=362,506,761 out=113,176,626 elapsed=200.5s

  [12912/20519] intraday_2392.csv.gz  in=362,518,440 out=113,176,626 elapsed=200.5s

  [12913/20519] intraday_2393.csv.gz  in=362,530,386 out=113,176,626 elapsed=200.5s

  [12914/20519] intraday_2396.csv.gz  in=362,542,623 out=113,176,626 elapsed=200.5s

  [12915/20519] intraday_2394.csv.gz  in=362,557,005 out=113,176,626 elapsed=200.6s

  [12916/20519] intraday_2397.csv.gz  in=362,570,679 out=113,176,626 elapsed=200.6s

  [12917/20519] intraday_2395.csv.gz  in=362,584,679 out=113,176,626 elapsed=200.6s

  [12918/20519] intraday_2398.csv.gz  in=362,600,037 out=113,176,626 elapsed=200.6s

  [12919/20519] intraday_2399.csv.gz  in=362,613,717 out=113,176,626 elapsed=200.6s

  [12920/20519] intraday_2400.csv.gz  in=362,631,002 out=113,176,626 elapsed=200.6s

  [12921/20519] intraday_2401.csv.gz  in=362,651,546 out=113,176,626 elapsed=200.6s

  [12922/20519] intraday_2402.csv.gz  in=362,663,646 out=113,176,626 elapsed=200.6s

  [12923/20519] intraday_2403.csv.gz  in=362,675,853 out=113,176,626 elapsed=200.6s

  [12924/20519] intraday_2405.csv.gz  in=362,688,031 out=113,176,626 elapsed=200.6s

  [12925/20519] intraday_2404.csv.gz  in=362,708,395 out=113,176,626 elapsed=200.6s

  [12926/20519] intraday_2406.csv.gz  in=362,720,186 out=113,176,626 elapsed=200.6s

  [12927/20519] intraday_2407.csv.gz  in=362,733,827 out=113,176,626 elapsed=200.6s

  [12928/20519] intraday_2408.csv.gz  in=362,749,997 out=113,176,626 elapsed=200.7s

  [12929/20519] intraday_2409.csv.gz  in=362,763,297 out=113,176,626 elapsed=200.7s

  [12930/20519] intraday_2410.csv.gz  in=362,783,435 out=113,176,626 elapsed=200.7s

  [12931/20519] intraday_2411.csv.gz  in=362,797,142 out=113,176,626 elapsed=200.7s

  [12932/20519] intraday_2413.csv.gz  in=362,810,542 out=113,176,626 elapsed=200.7s

  [12933/20519] intraday_2412.csv.gz  in=362,823,175 out=113,176,626 elapsed=200.7s

  [12934/20519] intraday_2415.csv.gz  in=362,835,712 out=113,176,626 elapsed=200.7s

  [12935/20519] intraday_2414.csv.gz  in=362,850,749 out=113,176,626 elapsed=200.7s

  [12936/20519] intraday_2416.csv.gz  in=362,871,002 out=113,176,626 elapsed=200.7s

  [12937/20519] intraday_2419.csv.gz  in=362,885,382 out=113,176,626 elapsed=200.8s

  [12938/20519] intraday_2417.csv.gz  in=362,913,901 out=113,176,626 elapsed=200.8s

  [12939/20519] intraday_2418.csv.gz  in=362,928,087 out=113,176,626 elapsed=200.8s

  [12940/20519] intraday_2420.csv.gz  in=362,942,542 out=113,176,626 elapsed=200.8s

  [12941/20519] intraday_2424.csv.gz  in=362,955,153 out=113,176,626 elapsed=200.9s

  [12942/20519] intraday_2422.csv.gz  in=362,965,123 out=113,176,626 elapsed=200.9s

  [12943/20519] intraday_2421.csv.gz  in=362,980,750 out=113,176,626 elapsed=200.9s

  [12944/20519] intraday_2423.csv.gz  in=362,992,729 out=113,176,626 elapsed=200.9s

  [12945/20519] intraday_2425.csv.gz  in=363,007,376 out=113,176,626 elapsed=200.9s

  [12946/20519] intraday_2428.csv.gz  in=363,018,189 out=113,176,626 elapsed=200.9s

  [12947/20519] intraday_2426.csv.gz  in=363,027,722 out=113,176,626 elapsed=200.9s

  [12948/20519] intraday_2427.csv.gz  in=363,040,187 out=113,176,626 elapsed=200.9s

  [12949/20519] intraday_2429.csv.gz  in=363,056,773 out=113,176,626 elapsed=200.9s

  [12950/20519] intraday_2430.csv.gz  in=363,068,917 out=113,176,626 elapsed=201.0s

  [12951/20519] intraday_2432.csv.gz  in=363,080,491 out=113,176,626 elapsed=201.0s

  [12952/20519] intraday_2431.csv.gz  in=363,092,864 out=113,176,626 elapsed=201.0s

  [12953/20519] intraday_2433.csv.gz  in=363,103,600 out=113,176,626 elapsed=201.0s

  [12954/20519] intraday_2435.csv.gz  in=363,118,250 out=113,176,626 elapsed=201.0s

  [12955/20519] intraday_2434.csv.gz  in=363,129,600 out=113,176,626 elapsed=201.0s

  [12956/20519] intraday_2437.csv.gz  in=363,142,253 out=113,176,626 elapsed=201.0s

  [12957/20519] intraday_2438.csv.gz  in=363,154,594 out=113,176,626 elapsed=201.1s

  [12958/20519] intraday_2436.csv.gz  in=363,179,883 out=113,176,626 elapsed=201.1s

  [12959/20519] intraday_2439.csv.gz  in=363,191,236 out=113,176,626 elapsed=201.1s

  [12960/20519] intraday_2440.csv.gz  in=363,203,585 out=113,176,626 elapsed=201.1s

  [12961/20519] intraday_2441.csv.gz  in=363,218,318 out=113,176,626 elapsed=201.1s

  [12962/20519] intraday_2442.csv.gz  in=363,231,072 out=113,176,626 elapsed=201.1s

  [12963/20519] intraday_2444.csv.gz  in=363,243,930 out=113,176,626 elapsed=201.1s

  [12964/20519] intraday_2443.csv.gz  in=363,257,662 out=113,176,626 elapsed=201.1s

  [12965/20519] intraday_2445.csv.gz  in=363,272,095 out=113,176,626 elapsed=201.2s

  [12966/20519] intraday_2446.csv.gz  in=363,286,093 out=113,176,626 elapsed=201.2s

  [12967/20519] intraday_2447.csv.gz  in=363,300,725 out=113,176,626 elapsed=201.2s

  [12968/20519] intraday_2448.csv.gz  in=363,314,630 out=113,176,626 elapsed=201.2s

  [12969/20519] intraday_2449.csv.gz  in=363,326,031 out=113,176,626 elapsed=201.2s

  [12970/20519] intraday_2451.csv.gz  in=363,339,947 out=113,176,626 elapsed=201.2s

  [12971/20519] intraday_2450.csv.gz  in=363,352,596 out=113,176,626 elapsed=201.2s

  [12972/20519] intraday_2452.csv.gz  in=363,365,899 out=113,176,626 elapsed=201.3s

  [12973/20519] intraday_2453.csv.gz  in=363,377,189 out=113,176,626 elapsed=201.3s

  [12974/20519] intraday_2454.csv.gz  in=363,391,027 out=113,176,626 elapsed=201.3s

  [12975/20519] intraday_2455.csv.gz  in=363,406,154 out=113,176,626 elapsed=201.3s

  [12976/20519] intraday_2456.csv.gz  in=363,421,109 out=113,176,626 elapsed=201.3s

  [12977/20519] intraday_2458.csv.gz  in=363,431,343 out=113,176,626 elapsed=201.3s

  [12978/20519] intraday_2457.csv.gz  in=363,447,606 out=113,176,626 elapsed=201.3s

  [12979/20519] intraday_2459.csv.gz  in=363,460,373 out=113,176,626 elapsed=201.3s

  [12980/20519] intraday_2460.csv.gz  in=363,474,533 out=113,176,626 elapsed=201.4s

  [12981/20519] intraday_2462.csv.gz  in=363,487,913 out=113,176,626 elapsed=201.4s

  [12982/20519] intraday_2461.csv.gz  in=363,502,849 out=113,176,626 elapsed=201.4s

  [12983/20519] intraday_2463.csv.gz  in=363,517,282 out=113,176,626 elapsed=201.4s

  [12984/20519] intraday_2464.csv.gz  in=363,529,461 out=113,176,626 elapsed=201.4s

  [12985/20519] intraday_2468.csv.gz  in=363,541,281 out=113,176,626 elapsed=201.5s

  [12986/20519] intraday_2466.csv.gz  in=363,554,330 out=113,176,626 elapsed=201.5s

  [12987/20519] intraday_2465.csv.gz  in=363,567,762 out=113,176,626 elapsed=201.5s

  [12988/20519] intraday_2467.csv.gz  in=363,582,091 out=113,176,626 elapsed=201.5s

  [12989/20519] intraday_2470.csv.gz  in=363,594,559 out=113,176,626 elapsed=201.5s

  [12990/20519] intraday_2469.csv.gz  in=363,611,787 out=113,176,626 elapsed=201.6s

  [12991/20519] intraday_2471.csv.gz  in=363,626,000 out=113,176,626 elapsed=201.6s

  [12992/20519] intraday_2472.csv.gz  in=363,641,625 out=113,176,626 elapsed=201.6s

  [12993/20519] intraday_2473.csv.gz  in=363,654,732 out=113,176,626 elapsed=201.6s

  [12994/20519] intraday_2474.csv.gz  in=363,665,691 out=113,176,626 elapsed=201.6s

  [12995/20519] intraday_2475.csv.gz  in=363,680,189 out=113,176,626 elapsed=201.6s

  [12996/20519] intraday_2476.csv.gz  in=363,693,553 out=113,176,626 elapsed=201.6s

  [12997/20519] intraday_2478.csv.gz  in=363,705,499 out=113,176,626 elapsed=201.6s

  [12998/20519] intraday_2477.csv.gz  in=363,721,633 out=113,176,626 elapsed=201.7s

  [12999/20519] intraday_2479.csv.gz  in=363,735,735 out=113,176,626 elapsed=201.7s

  [13000/20519] intraday_2480.csv.gz  in=363,749,716 out=113,176,626 elapsed=201.7s

  [13001/20519] intraday_2481.csv.gz  in=363,765,250 out=113,176,626 elapsed=201.7s

  [13002/20519] intraday_2482.csv.gz  in=363,779,534 out=113,176,626 elapsed=201.7s

  [13003/20519] intraday_2483.csv.gz  in=363,794,436 out=113,176,626 elapsed=201.7s

  [13004/20519] intraday_2484.csv.gz  in=363,810,248 out=113,176,626 elapsed=201.7s

  [13005/20519] intraday_2485.csv.gz  in=363,823,623 out=113,176,626 elapsed=201.7s

  [13006/20519] intraday_2486.csv.gz  in=363,837,980 out=113,176,626 elapsed=201.7s

  [13007/20519] intraday_2487.csv.gz  in=363,849,769 out=113,176,626 elapsed=201.8s

  [13008/20519] intraday_2489.csv.gz  in=363,861,574 out=113,176,626 elapsed=201.8s

  [13009/20519] intraday_2488.csv.gz  in=363,873,790 out=113,176,626 elapsed=201.8s

  [13010/20519] intraday_2491.csv.gz  in=363,882,507 out=113,176,626 elapsed=201.8s

  [13011/20519] intraday_2490.csv.gz  in=363,897,182 out=113,176,626 elapsed=201.8s

  [13012/20519] intraday_2492.csv.gz  in=363,905,244 out=113,176,626 elapsed=201.8s

  [13013/20519] intraday_2493.csv.gz  in=363,916,733 out=113,176,626 elapsed=201.8s

  [13014/20519] intraday_2494.csv.gz  in=363,932,030 out=113,176,626 elapsed=201.8s

  [13015/20519] intraday_2495.csv.gz  in=363,945,945 out=113,176,626 elapsed=201.8s

  [13016/20519] intraday_2497.csv.gz  in=363,956,934 out=113,176,626 elapsed=201.9s

  [13017/20519] intraday_2498.csv.gz  in=363,971,678 out=113,176,626 elapsed=201.9s

  [13018/20519] intraday_2499.csv.gz  in=363,985,581 out=113,176,626 elapsed=201.9s

  [13019/20519] intraday_2496.csv.gz  in=363,997,394 out=113,176,626 elapsed=201.9s

  [13020/20519] intraday_2500.csv.gz  in=364,009,844 out=113,176,626 elapsed=201.9s

  [13021/20519] intraday_2501.csv.gz  in=364,021,704 out=113,176,626 elapsed=201.9s

  [13022/20519] intraday_2503.csv.gz  in=364,036,128 out=113,176,626 elapsed=201.9s

  [13023/20519] intraday_2502.csv.gz  in=364,049,487 out=113,176,626 elapsed=201.9s

  [13024/20519] intraday_2504.csv.gz  in=364,058,576 out=113,176,626 elapsed=201.9s

  [13025/20519] intraday_2505.csv.gz  in=364,069,742 out=113,176,626 elapsed=201.9s

  [13026/20519] intraday_2506.csv.gz  in=364,082,676 out=113,176,626 elapsed=202.0s

  [13027/20519] intraday_2507.csv.gz  in=364,093,416 out=113,176,626 elapsed=202.0s

  [13028/20519] intraday_2508.csv.gz  in=364,104,752 out=113,176,626 elapsed=202.0s

  [13029/20519] intraday_2509.csv.gz  in=364,116,637 out=113,176,626 elapsed=202.0s

  [13030/20519] intraday_2510.csv.gz  in=364,128,763 out=113,176,626 elapsed=202.0s

  [13031/20519] intraday_2511.csv.gz  in=364,140,772 out=113,176,626 elapsed=202.0s

  [13032/20519] intraday_2513.csv.gz  in=364,152,049 out=113,176,626 elapsed=202.0s

  [13033/20519] intraday_2512.csv.gz  in=364,163,805 out=113,176,626 elapsed=202.1s

  [13034/20519] intraday_2514.csv.gz  in=364,176,851 out=113,176,626 elapsed=202.1s

  [13035/20519] intraday_2515.csv.gz  in=364,188,582 out=113,176,626 elapsed=202.1s

  [13036/20519] intraday_2516.csv.gz  in=364,200,713 out=113,176,626 elapsed=202.1s

  [13037/20519] intraday_2517.csv.gz  in=364,213,299 out=113,176,626 elapsed=202.1s

  [13038/20519] intraday_2518.csv.gz  in=364,225,194 out=113,176,626 elapsed=202.1s

  [13039/20519] intraday_2519.csv.gz  in=364,234,011 out=113,176,626 elapsed=202.1s

  [13040/20519] intraday_2520.csv.gz  in=364,245,847 out=113,176,626 elapsed=202.1s

  [13041/20519] intraday_2521.csv.gz  in=364,259,318 out=113,176,626 elapsed=202.2s

  [13042/20519] intraday_2523.csv.gz  in=364,273,793 out=113,176,626 elapsed=202.2s

  [13043/20519] intraday_2522.csv.gz  in=364,286,192 out=113,176,626 elapsed=202.2s

  [13044/20519] intraday_2524.csv.gz  in=364,299,563 out=113,176,626 elapsed=202.2s

  [13045/20519] intraday_2525.csv.gz  in=364,310,934 out=113,176,626 elapsed=202.2s

  [13046/20519] intraday_2526.csv.gz  in=364,323,599 out=113,176,626 elapsed=202.2s

  [13047/20519] intraday_2527.csv.gz  in=364,336,430 out=113,176,626 elapsed=202.2s

  [13048/20519] intraday_2528.csv.gz  in=364,347,550 out=113,176,626 elapsed=202.2s

  [13049/20519] intraday_2529.csv.gz  in=364,360,636 out=113,176,626 elapsed=202.3s

  [13050/20519] intraday_2530.csv.gz  in=364,372,188 out=113,176,626 elapsed=202.3s

  [13051/20519] intraday_2531.csv.gz  in=364,382,565 out=113,176,626 elapsed=202.3s

  [13052/20519] intraday_2532.csv.gz  in=364,394,838 out=113,176,626 elapsed=202.3s

  [13053/20519] intraday_2533.csv.gz  in=364,404,791 out=113,176,626 elapsed=202.3s

  [13054/20519] intraday_2534.csv.gz  in=364,419,853 out=113,176,626 elapsed=202.3s

  [13055/20519] intraday_2535.csv.gz  in=364,432,006 out=113,176,626 elapsed=202.3s

  [13056/20519] intraday_2536.csv.gz  in=364,446,352 out=113,176,626 elapsed=202.4s

  [13057/20519] intraday_2538.csv.gz  in=364,458,637 out=113,176,626 elapsed=202.4s

  [13058/20519] intraday_2537.csv.gz  in=364,470,422 out=113,176,626 elapsed=202.4s

  [13059/20519] intraday_2541.csv.gz  in=364,482,531 out=113,176,626 elapsed=202.4s

  [13060/20519] intraday_2540.csv.gz  in=364,492,790 out=113,176,626 elapsed=202.4s

  [13061/20519] intraday_2542.csv.gz  in=364,504,887 out=113,176,626 elapsed=202.5s

  [13062/20519] intraday_2539.csv.gz  in=364,516,940 out=113,176,626 elapsed=202.5s

  [13063/20519] intraday_2543.csv.gz  in=364,527,140 out=113,176,626 elapsed=202.5s

  [13064/20519] intraday_2545.csv.gz  in=364,538,050 out=113,176,626 elapsed=202.5s

  [13065/20519] intraday_2546.csv.gz  in=364,549,414 out=113,176,626 elapsed=202.5s

  [13066/20519] intraday_2547.csv.gz  in=364,563,025 out=113,176,626 elapsed=202.5s

  [13067/20519] intraday_2544.csv.gz  in=364,576,060 out=113,176,626 elapsed=202.5s

  [13068/20519] intraday_2548.csv.gz  in=364,590,056 out=113,176,626 elapsed=202.5s

  [13069/20519] intraday_2549.csv.gz  in=364,600,963 out=113,176,626 elapsed=202.5s

  [13070/20519] intraday_2550.csv.gz  in=364,611,966 out=113,176,626 elapsed=202.5s

  [13071/20519] intraday_2552.csv.gz  in=364,625,505 out=113,176,626 elapsed=202.6s

  [13072/20519] intraday_2554.csv.gz  in=364,636,269 out=113,176,626 elapsed=202.6s

  [13073/20519] intraday_2551.csv.gz  in=364,649,671 out=113,176,626 elapsed=202.6s

  [13074/20519] intraday_2553.csv.gz  in=364,662,115 out=113,176,626 elapsed=202.6s

  [13075/20519] intraday_2555.csv.gz  in=364,673,050 out=113,176,626 elapsed=202.6s

  [13076/20519] intraday_2557.csv.gz  in=364,687,506 out=113,176,626 elapsed=202.6s

  [13077/20519] intraday_2556.csv.gz  in=364,697,392 out=113,176,626 elapsed=202.6s

  [13078/20519] intraday_2558.csv.gz  in=364,709,213 out=113,176,626 elapsed=202.6s

  [13079/20519] intraday_2559.csv.gz  in=364,722,292 out=113,176,626 elapsed=202.6s

  [13080/20519] intraday_2562.csv.gz  in=364,733,913 out=113,176,626 elapsed=202.7s

  [13081/20519] intraday_2560.csv.gz  in=364,746,904 out=113,176,626 elapsed=202.7s

  [13082/20519] intraday_2561.csv.gz  in=364,758,360 out=113,176,626 elapsed=202.7s

  [13083/20519] intraday_2563.csv.gz  in=364,770,896 out=113,176,626 elapsed=202.7s

  [13084/20519] intraday_2564.csv.gz  in=364,781,477 out=113,176,626 elapsed=202.7s

  [13085/20519] intraday_2566.csv.gz  in=364,791,187 out=113,176,626 elapsed=202.7s

  [13086/20519] intraday_2565.csv.gz  in=364,803,836 out=113,176,626 elapsed=202.7s

  [13087/20519] intraday_2568.csv.gz  in=364,816,134 out=113,176,626 elapsed=202.7s

  [13088/20519] intraday_2567.csv.gz  in=364,827,779 out=113,176,626 elapsed=202.7s

  [13089/20519] intraday_2569.csv.gz  in=364,839,465 out=113,176,626 elapsed=202.7s

  [13090/20519] intraday_2570.csv.gz  in=364,851,144 out=113,176,626 elapsed=202.8s

  [13091/20519] intraday_2573.csv.gz  in=364,862,311 out=113,176,626 elapsed=202.8s

  [13092/20519] intraday_2571.csv.gz  in=364,874,502 out=113,176,626 elapsed=202.8s

  [13093/20519] intraday_2572.csv.gz  in=364,884,830 out=113,176,626 elapsed=202.8s

  [13094/20519] intraday_2574.csv.gz  in=364,896,616 out=113,176,626 elapsed=202.8s

  [13095/20519] intraday_2576.csv.gz  in=364,908,363 out=113,176,626 elapsed=202.8s

  [13096/20519] intraday_2575.csv.gz  in=364,922,830 out=113,176,626 elapsed=202.8s

  [13097/20519] intraday_2580.csv.gz  in=364,935,247 out=113,176,626 elapsed=202.9s

  [13098/20519] intraday_2579.csv.gz  in=364,946,984 out=113,176,626 elapsed=202.9s

  [13099/20519] intraday_2577.csv.gz  in=364,959,371 out=113,176,626 elapsed=202.9s

  [13100/20519] intraday_2582.csv.gz  in=364,970,019 out=113,176,626 elapsed=202.9s

  [13101/20519] intraday_2578.csv.gz  in=364,982,547 out=113,176,626 elapsed=202.9s

  [13102/20519] intraday_2583.csv.gz  in=364,997,014 out=113,176,626 elapsed=202.9s

  [13103/20519] intraday_2581.csv.gz  in=365,012,298 out=113,176,626 elapsed=202.9s

  [13104/20519] intraday_2584.csv.gz  in=365,024,947 out=113,176,626 elapsed=202.9s

  [13105/20519] intraday_2585.csv.gz  in=365,038,374 out=113,176,626 elapsed=202.9s

  [13106/20519] intraday_2586.csv.gz  in=365,052,094 out=113,176,626 elapsed=203.0s

  [13107/20519] intraday_2588.csv.gz  in=365,064,223 out=113,176,626 elapsed=203.0s

  [13108/20519] intraday_2587.csv.gz  in=365,077,042 out=113,176,626 elapsed=203.0s

  [13109/20519] intraday_2589.csv.gz  in=365,089,491 out=113,176,626 elapsed=203.0s

  [13110/20519] intraday_2592.csv.gz  in=365,100,561 out=113,176,626 elapsed=203.0s

  [13111/20519] intraday_2591.csv.gz  in=365,112,087 out=113,176,626 elapsed=203.0s

  [13112/20519] intraday_2590.csv.gz  in=365,122,639 out=113,176,626 elapsed=203.0s

  [13113/20519] intraday_2594.csv.gz  in=365,133,690 out=113,176,626 elapsed=203.0s

  [13114/20519] intraday_2595.csv.gz  in=365,146,834 out=113,176,626 elapsed=203.0s

  [13115/20519] intraday_2596.csv.gz  in=365,159,033 out=113,176,626 elapsed=203.1s

  [13116/20519] intraday_2593.csv.gz  in=365,172,315 out=113,176,626 elapsed=203.1s

  [13117/20519] intraday_2599.csv.gz  in=365,185,208 out=113,176,626 elapsed=203.1s

  [13118/20519] intraday_2598.csv.gz  in=365,196,306 out=113,176,626 elapsed=203.1s

  [13119/20519] intraday_2597.csv.gz  in=365,209,818 out=113,176,626 elapsed=203.1s

  [13120/20519] intraday_2600.csv.gz  in=365,224,590 out=113,176,626 elapsed=203.1s

  [13121/20519] intraday_2603.csv.gz  in=365,238,153 out=113,176,626 elapsed=203.1s

  [13122/20519] intraday_2602.csv.gz  in=365,251,426 out=113,176,626 elapsed=203.1s

  [13123/20519] intraday_2604.csv.gz  in=365,263,343 out=113,176,626 elapsed=203.1s

  [13124/20519] intraday_2601.csv.gz  in=365,277,094 out=113,176,626 elapsed=203.1s

  [13125/20519] intraday_2605.csv.gz  in=365,289,693 out=113,176,626 elapsed=203.1s

  [13126/20519] intraday_2606.csv.gz  in=365,302,907 out=113,176,626 elapsed=203.2s

  [13127/20519] intraday_2607.csv.gz  in=365,315,479 out=113,176,626 elapsed=203.2s

  [13128/20519] intraday_2609.csv.gz  in=365,329,098 out=113,176,626 elapsed=203.2s

  [13129/20519] intraday_2608.csv.gz  in=365,344,850 out=113,176,626 elapsed=203.2s

  [13130/20519] intraday_2610.csv.gz  in=365,357,575 out=113,176,626 elapsed=203.2s

  [13131/20519] intraday_2611.csv.gz  in=365,371,608 out=113,176,626 elapsed=203.2s

  [13132/20519] intraday_2612.csv.gz  in=365,381,459 out=113,176,626 elapsed=203.2s

  [13133/20519] intraday_2614.csv.gz  in=365,392,267 out=113,176,626 elapsed=203.2s

  [13134/20519] intraday_2613.csv.gz  in=365,404,863 out=113,176,626 elapsed=203.3s

  [13135/20519] intraday_2616.csv.gz  in=365,418,649 out=113,176,626 elapsed=203.3s

  [13136/20519] intraday_2615.csv.gz  in=365,433,090 out=113,176,626 elapsed=203.3s

  [13137/20519] intraday_2617.csv.gz  in=365,449,216 out=113,176,626 elapsed=203.3s

  [13138/20519] intraday_2618.csv.gz  in=365,461,157 out=113,176,626 elapsed=203.3s

  [13139/20519] intraday_2619.csv.gz  in=365,475,098 out=113,176,626 elapsed=203.3s

  [13140/20519] intraday_2621.csv.gz  in=365,488,714 out=113,176,626 elapsed=203.3s

  [13141/20519] intraday_2620.csv.gz  in=365,502,314 out=113,176,626 elapsed=203.3s

  [13142/20519] intraday_2622.csv.gz  in=365,515,408 out=113,176,626 elapsed=203.3s

  [13143/20519] intraday_2623.csv.gz  in=365,531,002 out=113,176,626 elapsed=203.4s

  [13144/20519] intraday_2625.csv.gz  in=365,544,595 out=113,176,626 elapsed=203.4s

  [13145/20519] intraday_2624.csv.gz  in=365,558,936 out=113,176,626 elapsed=203.4s

  [13146/20519] intraday_2628.csv.gz  in=365,571,753 out=113,176,626 elapsed=203.4s

  [13147/20519] intraday_2626.csv.gz  in=365,584,607 out=113,176,626 elapsed=203.4s

  [13148/20519] intraday_2627.csv.gz  in=365,594,512 out=113,176,626 elapsed=203.4s

  [13149/20519] intraday_2629.csv.gz  in=365,606,668 out=113,176,626 elapsed=203.4s

  [13150/20519] intraday_2633.csv.gz  in=365,612,691 out=113,176,626 elapsed=203.5s

  [13151/20519] intraday_2632.csv.gz  in=365,622,954 out=113,176,626 elapsed=203.5s

  [13152/20519] intraday_2630.csv.gz  in=365,634,831 out=113,176,626 elapsed=203.5s

  [13153/20519] intraday_2631.csv.gz  in=365,641,902 out=113,176,626 elapsed=203.5s

  [13154/20519] intraday_2635.csv.gz  in=365,642,027 out=113,176,626 elapsed=203.5s

  [13155/20519] intraday_2634.csv.gz  in=365,644,228 out=113,176,626 elapsed=203.5s

  [13156/20519] intraday_2637.csv.gz  in=365,644,452 out=113,176,626 elapsed=203.5s

  [13157/20519] intraday_2636.csv.gz  in=365,656,914 out=113,176,626 elapsed=203.6s

  [13158/20519] intraday_2639.csv.gz  in=365,657,025 out=113,176,626 elapsed=203.6s

  [13159/20519] intraday_2638.csv.gz  in=365,657,106 out=113,176,626 elapsed=203.6s

  [13160/20519] intraday_2640.csv.gz  in=365,663,595 out=113,176,626 elapsed=203.6s

  [13161/20519] intraday_2641.csv.gz  in=365,663,628 out=113,176,626 elapsed=203.6s

  [13162/20519] intraday_2642.csv.gz  in=365,663,639 out=113,176,626 elapsed=203.6s

  [13163/20519] intraday_2643.csv.gz  in=365,663,651 out=113,176,626 elapsed=203.6s

  [13164/20519] intraday_2644.csv.gz  in=365,663,693 out=113,176,626 elapsed=203.6s

  [13165/20519] intraday_2645.csv.gz  in=365,664,469 out=113,176,626 elapsed=203.6s

  [13166/20519] intraday_2648.csv.gz  in=365,664,513 out=113,176,626 elapsed=203.6s

  [13167/20519] intraday_2649.csv.gz  in=365,664,542 out=113,176,626 elapsed=203.6s

  [13168/20519] intraday_2647.csv.gz  in=365,675,685 out=113,176,626 elapsed=203.6s

  [13169/20519] intraday_2646.csv.gz  in=365,675,756 out=113,176,626 elapsed=203.6s

  [13170/20519] intraday_2651.csv.gz  in=365,675,843 out=113,176,626 elapsed=203.6s

  [13171/20519] intraday_2652.csv.gz  in=365,675,858 out=113,176,626 elapsed=203.6s

  [13172/20519] intraday_2653.csv.gz  in=365,681,712 out=113,176,626 elapsed=203.7s

  [13173/20519] intraday_2650.csv.gz  in=365,696,372 out=113,176,626 elapsed=203.7s

  [13174/20519] intraday_2654.csv.gz  in=365,696,703 out=113,176,626 elapsed=203.7s

  [13175/20519] intraday_2655.csv.gz  in=365,696,869 out=113,176,626 elapsed=203.7s

  [13176/20519] intraday_2656.csv.gz  in=365,698,814 out=113,176,626 elapsed=203.7s

  [13177/20519] intraday_2658.csv.gz  in=365,702,974 out=113,176,626 elapsed=203.7s

  [13178/20519] intraday_2657.csv.gz  in=365,706,174 out=113,176,626 elapsed=203.7s

  [13179/20519] intraday_2659.csv.gz  in=365,706,197 out=113,176,626 elapsed=203.7s

  [13180/20519] intraday_2662.csv.gz  in=365,706,240 out=113,176,626 elapsed=203.7s

  [13181/20519] intraday_2660.csv.gz  in=365,709,718 out=113,176,626 elapsed=203.7s

  [13182/20519] intraday_2663.csv.gz  in=365,709,878 out=113,176,626 elapsed=203.7s

  [13183/20519] intraday_2661.csv.gz  in=365,718,553 out=113,176,626 elapsed=203.7s

  [13184/20519] intraday_2664.csv.gz  in=365,718,641 out=113,176,626 elapsed=203.7s

  [13185/20519] intraday_2666.csv.gz  in=365,731,943 out=113,176,626 elapsed=203.8s

  [13186/20519] intraday_2665.csv.gz  in=365,746,777 out=113,176,626 elapsed=203.8s

  [13187/20519] intraday_2668.csv.gz  in=365,757,078 out=113,176,626 elapsed=203.8s

  [13188/20519] intraday_2667.csv.gz  in=365,769,530 out=113,176,626 elapsed=203.8s

  [13189/20519] intraday_2671.csv.gz  in=365,780,973 out=113,176,626 elapsed=203.8s

  [13190/20519] intraday_2672.csv.gz  in=365,795,010 out=113,176,626 elapsed=203.8s

  [13191/20519] intraday_2669.csv.gz  in=365,808,915 out=113,176,626 elapsed=203.8s

  [13192/20519] intraday_2670.csv.gz  in=365,822,144 out=113,176,626 elapsed=203.8s

  [13193/20519] intraday_2675.csv.gz  in=365,830,822 out=113,176,626 elapsed=203.8s

  [13194/20519] intraday_2673.csv.gz  in=365,843,588 out=113,176,626 elapsed=203.9s

  [13195/20519] intraday_2676.csv.gz  in=365,855,050 out=113,176,626 elapsed=203.9s

  [13196/20519] intraday_2674.csv.gz  in=365,868,267 out=113,176,626 elapsed=203.9s

  [13197/20519] intraday_2677.csv.gz  in=365,879,270 out=113,176,626 elapsed=203.9s

  [13198/20519] intraday_2678.csv.gz  in=365,896,132 out=113,176,626 elapsed=203.9s

  [13199/20519] intraday_2679.csv.gz  in=365,906,672 out=113,176,626 elapsed=203.9s

  [13200/20519] intraday_2680.csv.gz  in=365,916,545 out=113,176,626 elapsed=203.9s

  [13201/20519] intraday_2681.csv.gz  in=365,928,869 out=113,176,626 elapsed=203.9s

  [13202/20519] intraday_2683.csv.gz  in=365,939,127 out=113,176,626 elapsed=203.9s

  [13203/20519] intraday_2685.csv.gz  in=365,951,050 out=113,176,626 elapsed=203.9s

  [13204/20519] intraday_2684.csv.gz  in=365,964,040 out=113,176,626 elapsed=203.9s

  [13205/20519] intraday_2682.csv.gz  in=365,975,726 out=113,176,626 elapsed=203.9s

  [13206/20519] intraday_2689.csv.gz  in=365,986,971 out=113,176,626 elapsed=204.0s

  [13207/20519] intraday_2687.csv.gz  in=365,998,293 out=113,176,626 elapsed=204.0s

  [13208/20519] intraday_2686.csv.gz  in=366,010,648 out=113,176,626 elapsed=204.0s

  [13209/20519] intraday_2688.csv.gz  in=366,021,615 out=113,176,626 elapsed=204.0s

  [13210/20519] intraday_2690.csv.gz  in=366,031,112 out=113,176,626 elapsed=204.0s

  [13211/20519] intraday_2692.csv.gz  in=366,042,900 out=113,176,626 elapsed=204.0s

  [13212/20519] intraday_2691.csv.gz  in=366,054,690 out=113,176,626 elapsed=204.0s

  [13213/20519] intraday_2693.csv.gz  in=366,066,921 out=113,176,626 elapsed=204.0s

  [13214/20519] intraday_2694.csv.gz  in=366,080,572 out=113,176,626 elapsed=204.0s

  [13215/20519] intraday_2695.csv.gz  in=366,093,220 out=113,176,626 elapsed=204.0s

  [13216/20519] intraday_2696.csv.gz  in=366,103,966 out=113,176,626 elapsed=204.1s

  [13217/20519] intraday_2697.csv.gz  in=366,115,793 out=113,176,626 elapsed=204.1s

  [13218/20519] intraday_2698.csv.gz  in=366,128,479 out=113,176,626 elapsed=204.1s

  [13219/20519] intraday_2699.csv.gz  in=366,139,288 out=113,176,626 elapsed=204.1s

  [13220/20519] intraday_2700.csv.gz  in=366,152,694 out=113,176,626 elapsed=204.1s

  [13221/20519] intraday_2701.csv.gz  in=366,161,595 out=113,176,626 elapsed=204.1s

  [13222/20519] intraday_2702.csv.gz  in=366,172,911 out=113,176,626 elapsed=204.1s

  [13223/20519] intraday_2704.csv.gz  in=366,184,106 out=113,176,626 elapsed=204.1s

  [13224/20519] intraday_2703.csv.gz  in=366,193,744 out=113,176,626 elapsed=204.1s

  [13225/20519] intraday_2705.csv.gz  in=366,206,248 out=113,176,626 elapsed=204.1s

  [13226/20519] intraday_2709.csv.gz  in=366,217,413 out=113,176,626 elapsed=204.2s

  [13227/20519] intraday_2706.csv.gz  in=366,230,727 out=113,176,626 elapsed=204.2s

  [13228/20519] intraday_2707.csv.gz  in=366,246,699 out=113,176,626 elapsed=204.2s

  [13229/20519] intraday_2708.csv.gz  in=366,259,542 out=113,176,626 elapsed=204.2s

  [13230/20519] intraday_2712.csv.gz  in=366,286,545 out=113,176,626 elapsed=204.4s

  [13231/20519] intraday_2710.csv.gz  in=366,297,385 out=113,176,626 elapsed=204.4s

  [13232/20519] intraday_2711.csv.gz  in=366,308,878 out=113,176,626 elapsed=204.5s

  [13233/20519] intraday_2713.csv.gz  in=366,320,210 out=113,176,626 elapsed=204.5s

  [13234/20519] intraday_2714.csv.gz  in=366,329,910 out=113,176,626 elapsed=204.5s

  [13235/20519] intraday_2715.csv.gz  in=366,341,089 out=113,176,626 elapsed=204.5s

  [13236/20519] intraday_2718.csv.gz  in=366,351,480 out=113,176,626 elapsed=204.5s

  [13237/20519] intraday_2716.csv.gz  in=366,361,424 out=113,176,626 elapsed=204.5s

  [13238/20519] intraday_2717.csv.gz  in=366,376,047 out=113,176,626 elapsed=204.5s

  [13239/20519] intraday_2720.csv.gz  in=366,387,990 out=113,176,626 elapsed=204.6s

  [13240/20519] intraday_2721.csv.gz  in=366,396,906 out=113,176,626 elapsed=204.6s

  [13241/20519] intraday_2719.csv.gz  in=366,409,443 out=113,176,626 elapsed=204.6s

  [13242/20519] intraday_2722.csv.gz  in=366,421,847 out=113,176,626 elapsed=204.6s

  [13243/20519] intraday_2723.csv.gz  in=366,433,518 out=113,176,626 elapsed=204.6s

  [13244/20519] intraday_2725.csv.gz  in=366,444,556 out=113,176,626 elapsed=204.6s

  [13245/20519] intraday_2724.csv.gz  in=366,458,886 out=113,176,626 elapsed=204.6s

  [13246/20519] intraday_2726.csv.gz  in=366,470,294 out=113,176,626 elapsed=204.6s

  [13247/20519] intraday_2728.csv.gz  in=366,482,034 out=113,176,626 elapsed=204.6s

  [13248/20519] intraday_2727.csv.gz  in=366,491,446 out=113,176,626 elapsed=204.6s

  [13249/20519] intraday_2729.csv.gz  in=366,505,653 out=113,176,626 elapsed=204.6s

  [13250/20519] intraday_2730.csv.gz  in=366,515,259 out=113,176,626 elapsed=204.7s

  [13251/20519] intraday_2732.csv.gz  in=366,527,868 out=113,176,626 elapsed=204.7s

  [13252/20519] intraday_2731.csv.gz  in=366,541,249 out=113,176,626 elapsed=204.7s

  [13253/20519] intraday_2735.csv.gz  in=366,552,468 out=113,176,626 elapsed=204.7s

  [13254/20519] intraday_2733.csv.gz  in=366,561,699 out=113,176,626 elapsed=204.7s

  [13255/20519] intraday_2736.csv.gz  in=366,573,815 out=113,176,626 elapsed=204.7s

  [13256/20519] intraday_2734.csv.gz  in=366,597,032 out=113,176,626 elapsed=204.7s

  [13257/20519] intraday_2737.csv.gz  in=366,606,740 out=113,176,626 elapsed=204.7s

  [13258/20519] intraday_2738.csv.gz  in=366,617,314 out=113,176,626 elapsed=204.7s

  [13259/20519] intraday_2739.csv.gz  in=366,628,391 out=113,176,626 elapsed=204.7s

  [13260/20519] intraday_2740.csv.gz  in=366,639,444 out=113,176,626 elapsed=204.7s

  [13261/20519] intraday_2742.csv.gz  in=366,650,878 out=113,176,626 elapsed=204.8s

  [13262/20519] intraday_2744.csv.gz  in=366,661,094 out=113,176,626 elapsed=204.8s

  [13263/20519] intraday_2741.csv.gz  in=366,672,761 out=113,176,626 elapsed=204.8s

  [13264/20519] intraday_2743.csv.gz  in=366,684,439 out=113,176,626 elapsed=204.8s

  [13265/20519] intraday_2745.csv.gz  in=366,694,807 out=113,176,626 elapsed=204.8s

  [13266/20519] intraday_2746.csv.gz  in=366,707,652 out=113,176,626 elapsed=204.8s

  [13267/20519] intraday_2748.csv.gz  in=366,718,667 out=113,176,626 elapsed=204.8s

  [13268/20519] intraday_2747.csv.gz  in=366,733,349 out=113,176,626 elapsed=204.8s

  [13269/20519] intraday_2749.csv.gz  in=366,742,140 out=113,176,626 elapsed=204.8s

  [13270/20519] intraday_2750.csv.gz  in=366,752,546 out=113,176,626 elapsed=204.8s

  [13271/20519] intraday_2751.csv.gz  in=366,764,341 out=113,176,626 elapsed=204.8s

  [13272/20519] intraday_2752.csv.gz  in=366,776,346 out=113,176,626 elapsed=204.8s

  [13273/20519] intraday_2753.csv.gz  in=366,789,978 out=113,176,626 elapsed=204.9s

  [13274/20519] intraday_2755.csv.gz  in=366,802,556 out=113,176,626 elapsed=204.9s

  [13275/20519] intraday_2754.csv.gz  in=366,814,024 out=113,176,626 elapsed=204.9s

  [13276/20519] intraday_2756.csv.gz  in=366,826,074 out=113,176,626 elapsed=204.9s

  [13277/20519] intraday_2757.csv.gz  in=366,839,013 out=113,176,626 elapsed=204.9s

  [13278/20519] intraday_2759.csv.gz  in=366,850,613 out=113,176,626 elapsed=204.9s

  [13279/20519] intraday_2758.csv.gz  in=366,862,400 out=113,176,626 elapsed=204.9s

  [13280/20519] intraday_2760.csv.gz  in=366,874,565 out=113,176,626 elapsed=204.9s

  [13281/20519] intraday_2761.csv.gz  in=366,885,667 out=113,176,626 elapsed=204.9s

  [13282/20519] intraday_2762.csv.gz  in=366,897,515 out=113,176,626 elapsed=204.9s

  [13283/20519] intraday_2763.csv.gz  in=366,909,206 out=113,176,626 elapsed=205.0s

  [13284/20519] intraday_2764.csv.gz  in=366,919,150 out=113,176,626 elapsed=205.0s

  [13285/20519] intraday_2765.csv.gz  in=366,931,208 out=113,176,626 elapsed=205.0s

  [13286/20519] intraday_2766.csv.gz  in=366,941,756 out=113,176,626 elapsed=205.0s

  [13287/20519] intraday_2767.csv.gz  in=366,953,206 out=113,176,626 elapsed=205.0s

  [13288/20519] intraday_2768.csv.gz  in=366,966,755 out=113,176,626 elapsed=205.0s

  [13289/20519] intraday_2769.csv.gz  in=366,976,114 out=113,176,626 elapsed=205.0s

  [13290/20519] intraday_2770.csv.gz  in=366,991,760 out=113,176,626 elapsed=205.0s

  [13291/20519] intraday_2771.csv.gz  in=367,006,179 out=113,176,626 elapsed=205.0s

  [13292/20519] intraday_2774.csv.gz  in=367,018,325 out=113,176,626 elapsed=205.1s

  [13293/20519] intraday_2773.csv.gz  in=367,030,888 out=113,176,626 elapsed=205.1s

  [13294/20519] intraday_2772.csv.gz  in=367,044,702 out=113,176,626 elapsed=205.1s

  [13295/20519] intraday_2775.csv.gz  in=367,056,485 out=113,176,626 elapsed=205.1s

  [13296/20519] intraday_2776.csv.gz  in=367,069,196 out=113,176,626 elapsed=205.1s

  [13297/20519] intraday_2777.csv.gz  in=367,090,638 out=113,176,626 elapsed=205.1s

  [13298/20519] intraday_2778.csv.gz  in=367,101,583 out=113,176,626 elapsed=205.1s

  [13299/20519] intraday_2779.csv.gz  in=367,114,526 out=113,176,626 elapsed=205.1s

  [13300/20519] intraday_2780.csv.gz  in=367,130,035 out=113,176,626 elapsed=205.1s

  [13301/20519] intraday_2781.csv.gz  in=367,142,076 out=113,176,626 elapsed=205.1s

  [13302/20519] intraday_2782.csv.gz  in=367,154,984 out=113,176,626 elapsed=205.2s

  [13303/20519] intraday_2783.csv.gz  in=367,166,326 out=113,176,626 elapsed=205.2s

  [13304/20519] intraday_2784.csv.gz  in=367,177,926 out=113,176,626 elapsed=205.2s

  [13305/20519] intraday_2786.csv.gz  in=367,191,206 out=113,176,626 elapsed=205.2s

  [13306/20519] intraday_2785.csv.gz  in=367,202,850 out=113,176,626 elapsed=205.2s

  [13307/20519] intraday_2787.csv.gz  in=367,215,083 out=113,176,626 elapsed=205.2s

  [13308/20519] intraday_2789.csv.gz  in=367,225,602 out=113,176,626 elapsed=205.2s

  [13309/20519] intraday_2791.csv.gz  in=367,237,596 out=113,176,626 elapsed=205.2s

  [13310/20519] intraday_2788.csv.gz  in=367,253,468 out=113,176,626 elapsed=205.2s

  [13311/20519] intraday_2790.csv.gz  in=367,265,905 out=113,176,626 elapsed=205.2s

  [13312/20519] intraday_2792.csv.gz  in=367,278,834 out=113,176,626 elapsed=205.3s

  [13313/20519] intraday_2793.csv.gz  in=367,290,040 out=113,176,626 elapsed=205.3s

  [13314/20519] intraday_2795.csv.gz  in=367,306,844 out=113,176,626 elapsed=205.3s

  [13315/20519] intraday_2794.csv.gz  in=367,321,979 out=113,176,626 elapsed=205.3s

  [13316/20519] intraday_2796.csv.gz  in=367,335,085 out=113,176,626 elapsed=205.3s

  [13317/20519] intraday_2797.csv.gz  in=367,348,631 out=113,176,626 elapsed=205.3s

  [13318/20519] intraday_2798.csv.gz  in=367,359,598 out=113,176,626 elapsed=205.3s

  [13319/20519] intraday_2799.csv.gz  in=367,369,677 out=113,176,626 elapsed=205.3s

  [13320/20519] intraday_2800.csv.gz  in=367,381,526 out=113,176,626 elapsed=205.3s

  [13321/20519] intraday_2801.csv.gz  in=367,393,581 out=113,176,626 elapsed=205.3s

  [13322/20519] intraday_2802.csv.gz  in=367,401,522 out=113,176,626 elapsed=205.3s

  [13323/20519] intraday_2803.csv.gz  in=367,409,830 out=113,176,626 elapsed=205.4s

  [13324/20519] intraday_2804.csv.gz  in=367,420,773 out=113,176,626 elapsed=205.4s

  [13325/20519] intraday_2805.csv.gz  in=367,423,036 out=113,176,626 elapsed=205.4s

  [13326/20519] intraday_2806.csv.gz  in=367,438,605 out=113,176,626 elapsed=205.4s

  [13327/20519] intraday_2807.csv.gz  in=367,453,471 out=113,176,626 elapsed=205.4s

  [13328/20519] intraday_2808.csv.gz  in=367,466,605 out=113,176,626 elapsed=205.4s

  [13329/20519] intraday_2809.csv.gz  in=367,477,386 out=113,176,626 elapsed=205.4s

  [13330/20519] intraday_2812.csv.gz  in=367,489,970 out=113,176,626 elapsed=205.5s

  [13331/20519] intraday_2810.csv.gz  in=367,504,789 out=113,176,626 elapsed=205.5s

  [13332/20519] intraday_2811.csv.gz  in=367,518,526 out=113,176,626 elapsed=205.5s

  [13333/20519] intraday_2813.csv.gz  in=367,530,558 out=113,176,626 elapsed=205.5s

  [13334/20519] intraday_2816.csv.gz  in=367,539,538 out=113,176,626 elapsed=205.5s

  [13335/20519] intraday_2815.csv.gz  in=367,553,491 out=113,176,626 elapsed=205.5s

  [13336/20519] intraday_2817.csv.gz  in=367,566,629 out=113,176,626 elapsed=205.5s

  [13337/20519] intraday_2814.csv.gz  in=367,580,650 out=113,176,626 elapsed=205.5s

  [13338/20519] intraday_2818.csv.gz  in=367,592,937 out=113,176,626 elapsed=205.6s

  [13339/20519] intraday_2820.csv.gz  in=367,603,959 out=113,176,626 elapsed=205.6s

  [13340/20519] intraday_2819.csv.gz  in=367,615,001 out=113,176,626 elapsed=205.6s

  [13341/20519] intraday_2821.csv.gz  in=367,626,142 out=113,176,626 elapsed=205.6s

  [13342/20519] intraday_2825.csv.gz  in=367,638,987 out=113,176,626 elapsed=205.6s

  [13343/20519] intraday_2824.csv.gz  in=367,649,744 out=113,176,626 elapsed=205.6s

  [13344/20519] intraday_2823.csv.gz  in=367,662,044 out=113,176,626 elapsed=205.6s

  [13345/20519] intraday_2822.csv.gz  in=367,674,925 out=113,176,626 elapsed=205.6s

  [13346/20519] intraday_2828.csv.gz  in=367,687,452 out=113,176,626 elapsed=205.7s

  [13347/20519] intraday_2826.csv.gz  in=367,700,305 out=113,176,626 elapsed=205.7s

  [13348/20519] intraday_2827.csv.gz  in=367,712,217 out=113,176,626 elapsed=205.7s

  [13349/20519] intraday_2829.csv.gz  in=367,725,119 out=113,176,626 elapsed=205.7s

  [13350/20519] intraday_2830.csv.gz  in=367,746,291 out=113,176,626 elapsed=205.7s

  [13351/20519] intraday_2831.csv.gz  in=367,756,071 out=113,176,626 elapsed=205.7s

  [13352/20519] intraday_2833.csv.gz  in=367,768,298 out=113,176,626 elapsed=205.7s

  [13353/20519] intraday_2832.csv.gz  in=367,780,207 out=113,176,626 elapsed=205.7s

  [13354/20519] intraday_2835.csv.gz  in=367,794,399 out=113,176,626 elapsed=205.8s

  [13355/20519] intraday_2837.csv.gz  in=367,807,726 out=113,176,626 elapsed=205.8s

  [13356/20519] intraday_2836.csv.gz  in=367,821,180 out=113,176,626 elapsed=205.8s

  [13357/20519] intraday_2834.csv.gz  in=367,840,172 out=113,176,626 elapsed=205.8s

  [13358/20519] intraday_2838.csv.gz  in=367,853,017 out=113,176,626 elapsed=205.8s

  [13359/20519] intraday_2839.csv.gz  in=367,866,054 out=113,176,626 elapsed=205.8s

  [13360/20519] intraday_2841.csv.gz  in=367,878,745 out=113,176,626 elapsed=205.8s

  [13361/20519] intraday_2840.csv.gz  in=367,907,925 out=113,176,626 elapsed=205.8s

  [13362/20519] intraday_2843.csv.gz  in=367,918,446 out=113,176,626 elapsed=205.8s

  [13363/20519] intraday_2842.csv.gz  in=367,928,766 out=113,176,626 elapsed=205.8s

  [13364/20519] intraday_2844.csv.gz  in=367,939,734 out=113,176,626 elapsed=205.8s

  [13365/20519] intraday_2845.csv.gz  in=367,950,541 out=113,176,626 elapsed=205.8s

  [13366/20519] intraday_2846.csv.gz  in=367,964,747 out=113,176,626 elapsed=205.9s

  [13367/20519] intraday_2847.csv.gz  in=367,978,244 out=113,176,626 elapsed=205.9s

  [13368/20519] intraday_2848.csv.gz  in=367,990,219 out=113,176,626 elapsed=205.9s

  [13369/20519] intraday_2849.csv.gz  in=368,004,138 out=113,176,626 elapsed=205.9s

  [13370/20519] intraday_2851.csv.gz  in=368,020,742 out=113,176,626 elapsed=205.9s

  [13371/20519] intraday_2850.csv.gz  in=368,048,143 out=113,176,626 elapsed=205.9s

  [13372/20519] intraday_2852.csv.gz  in=368,059,206 out=113,176,626 elapsed=205.9s

  [13373/20519] intraday_2853.csv.gz  in=368,070,589 out=113,176,626 elapsed=205.9s

  [13374/20519] intraday_2854.csv.gz  in=368,082,849 out=113,176,626 elapsed=205.9s

  [13375/20519] intraday_2855.csv.gz  in=368,093,471 out=113,176,626 elapsed=205.9s

  [13376/20519] intraday_2856.csv.gz  in=368,105,537 out=113,176,626 elapsed=205.9s

  [13377/20519] intraday_2857.csv.gz  in=368,116,150 out=113,176,626 elapsed=205.9s

  [13378/20519] intraday_2860.csv.gz  in=368,128,782 out=113,176,626 elapsed=206.0s

  [13379/20519] intraday_2859.csv.gz  in=368,139,966 out=113,176,626 elapsed=206.0s

  [13380/20519] intraday_2861.csv.gz  in=368,151,879 out=113,176,626 elapsed=206.0s

  [13381/20519] intraday_2858.csv.gz  in=368,171,311 out=113,176,626 elapsed=206.0s

  [13382/20519] intraday_2863.csv.gz  in=368,184,015 out=113,176,626 elapsed=206.0s

  [13383/20519] intraday_2865.csv.gz  in=368,196,994 out=113,176,626 elapsed=206.0s

  [13384/20519] intraday_2862.csv.gz  in=368,206,838 out=113,176,626 elapsed=206.0s

  [13385/20519] intraday_2864.csv.gz  in=368,219,461 out=113,176,626 elapsed=206.0s

  [13386/20519] intraday_2866.csv.gz  in=368,231,924 out=113,176,626 elapsed=206.0s

  [13387/20519] intraday_2867.csv.gz  in=368,243,317 out=113,176,626 elapsed=206.0s

  [13388/20519] intraday_2868.csv.gz  in=368,252,889 out=113,176,626 elapsed=206.1s

  [13389/20519] intraday_2869.csv.gz  in=368,265,371 out=113,176,626 elapsed=206.1s

  [13390/20519] intraday_2871.csv.gz  in=368,275,613 out=113,176,626 elapsed=206.1s

  [13391/20519] intraday_2870.csv.gz  in=368,290,882 out=113,176,626 elapsed=206.1s

  [13392/20519] intraday_2872.csv.gz  in=368,304,853 out=113,176,626 elapsed=206.1s

  [13393/20519] intraday_2874.csv.gz  in=368,314,754 out=113,176,626 elapsed=206.1s

  [13394/20519] intraday_2873.csv.gz  in=368,330,090 out=113,176,626 elapsed=206.1s

  [13395/20519] intraday_2877.csv.gz  in=368,342,697 out=113,176,626 elapsed=206.1s

  [13396/20519] intraday_2876.csv.gz  in=368,355,879 out=113,176,626 elapsed=206.1s

  [13397/20519] intraday_2875.csv.gz  in=368,368,197 out=113,176,626 elapsed=206.2s

  [13398/20519] intraday_2878.csv.gz  in=368,378,755 out=113,176,626 elapsed=206.2s

  [13399/20519] intraday_2879.csv.gz  in=368,389,985 out=113,176,626 elapsed=206.2s

  [13400/20519] intraday_2882.csv.gz  in=368,401,994 out=113,176,626 elapsed=206.2s

  [13401/20519] intraday_2881.csv.gz  in=368,414,171 out=113,176,626 elapsed=206.2s

  [13402/20519] intraday_2880.csv.gz  in=368,430,893 out=113,176,626 elapsed=206.2s

  [13403/20519] intraday_2883.csv.gz  in=368,442,911 out=113,176,626 elapsed=206.2s

  [13404/20519] intraday_2885.csv.gz  in=368,453,482 out=113,176,626 elapsed=206.2s

  [13405/20519] intraday_2884.csv.gz  in=368,466,441 out=113,176,626 elapsed=206.2s

  [13406/20519] intraday_2886.csv.gz  in=368,477,115 out=113,176,626 elapsed=206.2s

  [13407/20519] intraday_2887.csv.gz  in=368,489,622 out=113,176,626 elapsed=206.2s

  [13408/20519] intraday_2888.csv.gz  in=368,506,368 out=113,176,626 elapsed=206.3s

  [13409/20519] intraday_2889.csv.gz  in=368,516,874 out=113,176,626 elapsed=206.3s

  [13410/20519] intraday_2891.csv.gz  in=368,527,355 out=113,176,626 elapsed=206.3s

  [13411/20519] intraday_2890.csv.gz  in=368,537,992 out=113,176,626 elapsed=206.3s

  [13412/20519] intraday_2892.csv.gz  in=368,550,510 out=113,176,626 elapsed=206.3s

  [13413/20519] intraday_2895.csv.gz  in=368,561,766 out=113,176,626 elapsed=206.3s

  [13414/20519] intraday_2894.csv.gz  in=368,577,318 out=113,176,626 elapsed=206.3s

  [13415/20519] intraday_2893.csv.gz  in=368,588,653 out=113,176,626 elapsed=206.3s

  [13416/20519] intraday_2896.csv.gz  in=368,601,863 out=113,176,626 elapsed=206.3s

  [13417/20519] intraday_2897.csv.gz  in=368,615,308 out=113,176,626 elapsed=206.4s

  [13418/20519] intraday_2899.csv.gz  in=368,627,410 out=113,176,626 elapsed=206.4s

  [13419/20519] intraday_2898.csv.gz  in=368,654,603 out=113,176,626 elapsed=206.4s

  [13420/20519] intraday_2900.csv.gz  in=368,667,009 out=113,176,626 elapsed=206.4s

  [13421/20519] intraday_2902.csv.gz  in=368,681,750 out=113,176,626 elapsed=206.4s

  [13422/20519] intraday_2901.csv.gz  in=368,706,059 out=113,176,626 elapsed=206.4s

  [13423/20519] intraday_2904.csv.gz  in=368,720,072 out=113,176,626 elapsed=206.4s

  [13424/20519] intraday_2903.csv.gz  in=368,732,778 out=113,176,626 elapsed=206.4s

  [13425/20519] intraday_2905.csv.gz  in=368,743,585 out=113,176,626 elapsed=206.4s

  [13426/20519] intraday_2906.csv.gz  in=368,756,049 out=113,176,626 elapsed=206.5s

  [13427/20519] intraday_2907.csv.gz  in=368,767,931 out=113,176,626 elapsed=206.5s

  [13428/20519] intraday_2908.csv.gz  in=368,792,655 out=113,176,626 elapsed=206.5s

  [13429/20519] intraday_2909.csv.gz  in=368,805,913 out=113,176,626 elapsed=206.5s

  [13430/20519] intraday_2910.csv.gz  in=368,816,576 out=113,176,626 elapsed=206.5s

  [13431/20519] intraday_2911.csv.gz  in=368,827,797 out=113,176,626 elapsed=206.5s

  [13432/20519] intraday_2912.csv.gz  in=368,841,957 out=113,176,626 elapsed=206.5s

  [13433/20519] intraday_2913.csv.gz  in=368,857,117 out=113,176,626 elapsed=206.5s

  [13434/20519] intraday_2914.csv.gz  in=368,869,950 out=113,176,626 elapsed=206.6s

  [13435/20519] intraday_2915.csv.gz  in=368,882,621 out=113,176,626 elapsed=206.6s

  [13436/20519] intraday_2916.csv.gz  in=368,896,609 out=113,176,626 elapsed=206.6s

  [13437/20519] intraday_2919.csv.gz  in=368,908,847 out=113,176,626 elapsed=206.6s

  [13438/20519] intraday_2918.csv.gz  in=368,922,155 out=113,176,626 elapsed=206.6s

  [13439/20519] intraday_2917.csv.gz  in=368,935,512 out=113,176,626 elapsed=206.6s

  [13440/20519] intraday_2920.csv.gz  in=368,949,948 out=113,176,626 elapsed=206.6s

  [13441/20519] intraday_2921.csv.gz  in=368,971,346 out=113,176,626 elapsed=206.7s

  [13442/20519] intraday_2923.csv.gz  in=368,984,474 out=113,176,626 elapsed=206.7s

  [13443/20519] intraday_2922.csv.gz  in=368,997,259 out=113,176,626 elapsed=206.7s

  [13444/20519] intraday_2924.csv.gz  in=369,009,682 out=113,176,626 elapsed=206.7s

  [13445/20519] intraday_2926.csv.gz  in=369,021,018 out=113,176,626 elapsed=206.7s

  [13446/20519] intraday_2927.csv.gz  in=369,034,860 out=113,176,626 elapsed=206.7s

  [13447/20519] intraday_2925.csv.gz  in=369,047,356 out=113,176,626 elapsed=206.7s

  [13448/20519] intraday_2928.csv.gz  in=369,060,365 out=113,176,626 elapsed=206.7s

  [13449/20519] intraday_2929.csv.gz  in=369,077,014 out=113,176,626 elapsed=206.7s

  [13450/20519] intraday_2931.csv.gz  in=369,090,879 out=113,176,626 elapsed=206.7s

  [13451/20519] intraday_2930.csv.gz  in=369,103,257 out=113,176,626 elapsed=206.7s

  [13452/20519] intraday_2932.csv.gz  in=369,116,943 out=113,176,626 elapsed=206.8s

  [13453/20519] intraday_2933.csv.gz  in=369,129,388 out=113,176,626 elapsed=206.8s

  [13454/20519] intraday_2934.csv.gz  in=369,142,273 out=113,176,626 elapsed=206.8s

  [13455/20519] intraday_2935.csv.gz  in=369,164,384 out=113,176,626 elapsed=206.8s

  [13456/20519] intraday_2937.csv.gz  in=369,177,804 out=113,176,626 elapsed=206.8s

  [13457/20519] intraday_2936.csv.gz  in=369,192,932 out=113,176,626 elapsed=206.8s

  [13458/20519] intraday_2938.csv.gz  in=369,207,459 out=113,176,626 elapsed=206.8s

  [13459/20519] intraday_2939.csv.gz  in=369,218,465 out=113,176,626 elapsed=206.8s

  [13460/20519] intraday_2940.csv.gz  in=369,229,691 out=113,176,626 elapsed=206.8s

  [13461/20519] intraday_2942.csv.gz  in=369,241,619 out=113,176,626 elapsed=206.9s

  [13462/20519] intraday_2941.csv.gz  in=369,254,561 out=113,176,626 elapsed=206.9s

  [13463/20519] intraday_2944.csv.gz  in=369,262,020 out=113,176,626 elapsed=206.9s

  [13464/20519] intraday_2943.csv.gz  in=369,272,967 out=113,176,626 elapsed=206.9s

  [13465/20519] intraday_2946.csv.gz  in=369,279,118 out=113,176,626 elapsed=206.9s

  [13466/20519] intraday_2945.csv.gz  in=369,288,615 out=113,176,626 elapsed=206.9s

  [13467/20519] intraday_2947.csv.gz  in=369,305,369 out=113,176,626 elapsed=206.9s

  [13468/20519] intraday_2950.csv.gz  in=369,316,410 out=113,176,626 elapsed=207.0s

  [13469/20519] intraday_2949.csv.gz  in=369,330,349 out=113,176,626 elapsed=207.0s

  [13470/20519] intraday_2951.csv.gz  in=369,345,431 out=113,176,626 elapsed=207.0s

  [13471/20519] intraday_2948.csv.gz  in=369,360,561 out=113,176,626 elapsed=207.0s

  [13472/20519] intraday_2952.csv.gz  in=369,375,445 out=113,176,626 elapsed=207.0s

  [13473/20519] intraday_2953.csv.gz  in=369,388,583 out=113,176,626 elapsed=207.0s

  [13474/20519] intraday_2954.csv.gz  in=369,401,811 out=113,176,626 elapsed=207.0s

  [13475/20519] intraday_2955.csv.gz  in=369,416,681 out=113,176,626 elapsed=207.0s

  [13476/20519] intraday_2956.csv.gz  in=369,431,251 out=113,176,626 elapsed=207.0s

  [13477/20519] intraday_2957.csv.gz  in=369,441,228 out=113,176,626 elapsed=207.1s

  [13478/20519] intraday_2958.csv.gz  in=369,455,203 out=113,176,626 elapsed=207.1s

  [13479/20519] intraday_2959.csv.gz  in=369,468,892 out=113,176,626 elapsed=207.1s

  [13480/20519] intraday_2961.csv.gz  in=369,480,335 out=113,176,626 elapsed=207.1s

  [13481/20519] intraday_2962.csv.gz  in=369,491,728 out=113,176,626 elapsed=207.1s

  [13482/20519] intraday_2960.csv.gz  in=369,504,199 out=113,176,626 elapsed=207.1s

  [13483/20519] intraday_2963.csv.gz  in=369,518,298 out=113,176,626 elapsed=207.1s

  [13484/20519] intraday_2964.csv.gz  in=369,531,256 out=113,176,626 elapsed=207.1s

  [13485/20519] intraday_2966.csv.gz  in=369,544,305 out=113,176,626 elapsed=207.1s

  [13486/20519] intraday_2965.csv.gz  in=369,555,500 out=113,176,626 elapsed=207.1s

  [13487/20519] intraday_2968.csv.gz  in=369,567,743 out=113,176,626 elapsed=207.1s

  [13488/20519] intraday_2967.csv.gz  in=369,581,785 out=113,176,626 elapsed=207.2s

  [13489/20519] intraday_2969.csv.gz  in=369,594,477 out=113,176,626 elapsed=207.2s

  [13490/20519] intraday_2970.csv.gz  in=369,612,714 out=113,176,626 elapsed=207.2s

  [13491/20519] intraday_2972.csv.gz  in=369,623,272 out=113,176,626 elapsed=207.2s

  [13492/20519] intraday_2974.csv.gz  in=369,635,993 out=113,176,626 elapsed=207.2s

  [13493/20519] intraday_2973.csv.gz  in=369,649,084 out=113,176,626 elapsed=207.2s

  [13494/20519] intraday_2971.csv.gz  in=369,661,585 out=113,176,626 elapsed=207.2s

  [13495/20519] intraday_2975.csv.gz  in=369,675,174 out=113,176,626 elapsed=207.2s

  [13496/20519] intraday_2976.csv.gz  in=369,691,050 out=113,176,626 elapsed=207.3s

  [13497/20519] intraday_2977.csv.gz  in=369,705,134 out=113,176,626 elapsed=207.3s

  [13498/20519] intraday_2978.csv.gz  in=369,718,796 out=113,176,626 elapsed=207.3s

  [13499/20519] intraday_2979.csv.gz  in=369,733,754 out=113,176,626 elapsed=207.3s

  [13500/20519] intraday_2981.csv.gz  in=369,749,639 out=113,176,626 elapsed=207.3s

  [13501/20519] intraday_2983.csv.gz  in=369,760,221 out=113,176,626 elapsed=207.3s

  [13502/20519] intraday_2982.csv.gz  in=369,777,896 out=113,176,626 elapsed=207.3s

  [13503/20519] intraday_2980.csv.gz  in=369,808,854 out=113,176,626 elapsed=207.3s

  [13504/20519] intraday_2984.csv.gz  in=369,821,704 out=113,176,626 elapsed=207.3s

  [13505/20519] intraday_2986.csv.gz  in=369,834,174 out=113,176,626 elapsed=207.3s

  [13506/20519] intraday_2985.csv.gz  in=369,846,473 out=113,176,626 elapsed=207.3s

  [13507/20519] intraday_2987.csv.gz  in=369,861,004 out=113,176,626 elapsed=207.3s

  [13508/20519] intraday_2988.csv.gz  in=369,875,097 out=113,176,626 elapsed=207.3s

  [13509/20519] intraday_2990.csv.gz  in=369,889,640 out=113,176,626 elapsed=207.4s

  [13510/20519] intraday_2989.csv.gz  in=369,901,813 out=113,176,626 elapsed=207.4s

  [13511/20519] intraday_2991.csv.gz  in=369,913,502 out=113,176,626 elapsed=207.4s

  [13512/20519] intraday_2992.csv.gz  in=369,926,830 out=113,176,626 elapsed=207.4s

  [13513/20519] intraday_2993.csv.gz  in=369,939,058 out=113,176,626 elapsed=207.4s

  [13514/20519] intraday_2994.csv.gz  in=369,951,182 out=113,176,626 elapsed=207.4s

  [13515/20519] intraday_2995.csv.gz  in=369,963,762 out=113,176,626 elapsed=207.4s

  [13516/20519] intraday_2997.csv.gz  in=369,976,768 out=113,176,626 elapsed=207.4s

  [13517/20519] intraday_2998.csv.gz  in=369,989,048 out=113,176,626 elapsed=207.4s

  [13518/20519] intraday_2996.csv.gz  in=370,000,655 out=113,176,626 elapsed=207.5s

  [13519/20519] intraday_3001.csv.gz  in=370,014,531 out=113,176,626 elapsed=207.5s

  [13520/20519] intraday_3000.csv.gz  in=370,026,602 out=113,176,626 elapsed=207.5s

  [13521/20519] intraday_2999.csv.gz  in=370,039,184 out=113,176,626 elapsed=207.5s

  [13522/20519] intraday_3002.csv.gz  in=370,051,723 out=113,176,626 elapsed=207.5s

  [13523/20519] intraday_3003.csv.gz  in=370,062,702 out=113,176,626 elapsed=207.5s

  [13524/20519] intraday_3004.csv.gz  in=370,076,726 out=113,176,626 elapsed=207.5s

  [13525/20519] intraday_3006.csv.gz  in=370,089,499 out=113,176,626 elapsed=207.5s

  [13526/20519] intraday_3005.csv.gz  in=370,103,469 out=113,176,626 elapsed=207.6s

  [13527/20519] intraday_3007.csv.gz  in=370,116,151 out=113,176,626 elapsed=207.6s

  [13528/20519] intraday_3009.csv.gz  in=370,126,279 out=113,176,626 elapsed=207.6s

  [13529/20519] intraday_3008.csv.gz  in=370,138,614 out=113,176,626 elapsed=207.6s

  [13530/20519] intraday_3010.csv.gz  in=370,151,661 out=113,176,626 elapsed=207.6s

  [13531/20519] intraday_3011.csv.gz  in=370,168,198 out=113,176,626 elapsed=207.6s

  [13532/20519] intraday_3012.csv.gz  in=370,179,195 out=113,176,626 elapsed=207.6s

  [13533/20519] intraday_3013.csv.gz  in=370,192,936 out=113,176,626 elapsed=207.6s

  [13534/20519] intraday_3014.csv.gz  in=370,207,750 out=113,176,626 elapsed=207.6s

  [13535/20519] intraday_3015.csv.gz  in=370,217,118 out=113,176,626 elapsed=207.6s

  [13536/20519] intraday_3017.csv.gz  in=370,230,503 out=113,176,626 elapsed=207.6s

  [13537/20519] intraday_3016.csv.gz  in=370,244,331 out=113,176,626 elapsed=207.6s

  [13538/20519] intraday_3019.csv.gz  in=370,255,201 out=113,176,626 elapsed=207.6s

  [13539/20519] intraday_3018.csv.gz  in=370,269,400 out=113,176,626 elapsed=207.6s

  [13540/20519] intraday_3020.csv.gz  in=370,280,913 out=113,176,626 elapsed=207.6s

  [13541/20519] intraday_3021.csv.gz  in=370,292,998 out=113,176,626 elapsed=207.7s

  [13542/20519] intraday_3022.csv.gz  in=370,305,990 out=113,176,626 elapsed=207.7s

  [13543/20519] intraday_3023.csv.gz  in=370,319,475 out=113,176,626 elapsed=207.7s

  [13544/20519] intraday_3024.csv.gz  in=370,331,641 out=113,176,626 elapsed=207.7s

  [13545/20519] intraday_3026.csv.gz  in=370,342,450 out=113,176,626 elapsed=207.7s

  [13546/20519] intraday_3027.csv.gz  in=370,353,418 out=113,176,626 elapsed=207.7s

  [13547/20519] intraday_3025.csv.gz  in=370,367,367 out=113,176,626 elapsed=207.7s

  [13548/20519] intraday_3028.csv.gz  in=370,381,068 out=113,176,626 elapsed=207.7s

  [13549/20519] intraday_3030.csv.gz  in=370,392,186 out=113,176,626 elapsed=207.7s

  [13550/20519] intraday_3029.csv.gz  in=370,409,563 out=113,176,626 elapsed=207.7s

  [13551/20519] intraday_3031.csv.gz  in=370,421,306 out=113,176,626 elapsed=207.7s

  [13552/20519] intraday_3032.csv.gz  in=370,431,864 out=113,176,626 elapsed=207.7s

  [13553/20519] intraday_3033.csv.gz  in=370,445,681 out=113,176,626 elapsed=207.7s

  [13554/20519] intraday_3034.csv.gz  in=370,457,991 out=113,176,626 elapsed=207.7s

  [13555/20519] intraday_3036.csv.gz  in=370,481,652 out=113,176,626 elapsed=207.7s

  [13556/20519] intraday_3037.csv.gz  in=370,498,064 out=113,176,626 elapsed=207.7s

  [13557/20519] intraday_3035.csv.gz  in=370,528,181 out=113,176,626 elapsed=207.7s

  [13558/20519] intraday_3038.csv.gz  in=370,541,721 out=113,176,626 elapsed=207.7s

  [13559/20519] intraday_3040.csv.gz  in=370,554,998 out=113,176,626 elapsed=207.8s

  [13560/20519] intraday_3041.csv.gz  in=370,568,325 out=113,176,626 elapsed=207.8s

  [13561/20519] intraday_3039.csv.gz  in=370,583,286 out=113,176,626 elapsed=207.8s

  [13562/20519] intraday_3042.csv.gz  in=370,598,099 out=113,176,626 elapsed=207.8s

  [13563/20519] intraday_3043.csv.gz  in=370,610,824 out=113,176,626 elapsed=207.8s

  [13564/20519] intraday_3044.csv.gz  in=370,623,873 out=113,176,626 elapsed=207.8s

  [13565/20519] intraday_3045.csv.gz  in=370,636,941 out=113,176,626 elapsed=207.8s

  [13566/20519] intraday_3046.csv.gz  in=370,649,756 out=113,176,626 elapsed=207.8s

  [13567/20519] intraday_3047.csv.gz  in=370,662,230 out=113,176,626 elapsed=207.8s

  [13568/20519] intraday_3049.csv.gz  in=370,675,354 out=113,176,626 elapsed=207.8s

  [13569/20519] intraday_3048.csv.gz  in=370,688,404 out=113,176,626 elapsed=207.8s

  [13570/20519] intraday_3050.csv.gz  in=370,701,982 out=113,176,626 elapsed=207.8s

  [13571/20519] intraday_3052.csv.gz  in=370,714,109 out=113,176,626 elapsed=207.9s

  [13572/20519] intraday_3051.csv.gz  in=370,726,576 out=113,176,626 elapsed=207.9s

  [13573/20519] intraday_3053.csv.gz  in=370,741,801 out=113,176,626 elapsed=207.9s

  [13574/20519] intraday_3054.csv.gz  in=370,757,156 out=113,176,626 elapsed=207.9s

  [13575/20519] intraday_3056.csv.gz  in=370,770,373 out=113,176,626 elapsed=207.9s

  [13576/20519] intraday_3055.csv.gz  in=370,787,609 out=113,176,626 elapsed=207.9s

  [13577/20519] intraday_3058.csv.gz  in=370,801,784 out=113,176,626 elapsed=207.9s

  [13578/20519] intraday_3057.csv.gz  in=370,816,253 out=113,176,626 elapsed=207.9s

  [13579/20519] intraday_3061.csv.gz  in=370,830,536 out=113,176,626 elapsed=207.9s

  [13580/20519] intraday_3059.csv.gz  in=370,844,386 out=113,176,626 elapsed=208.0s

  [13581/20519] intraday_3060.csv.gz  in=370,857,931 out=113,176,626 elapsed=208.0s

  [13582/20519] intraday_3062.csv.gz  in=370,874,833 out=113,176,626 elapsed=208.0s

  [13583/20519] intraday_3064.csv.gz  in=370,889,657 out=113,176,626 elapsed=208.0s

  [13584/20519] intraday_3063.csv.gz  in=370,902,527 out=113,176,626 elapsed=208.0s

  [13585/20519] intraday_3065.csv.gz  in=370,916,160 out=113,176,626 elapsed=208.0s

  [13586/20519] intraday_3066.csv.gz  in=370,929,761 out=113,176,626 elapsed=208.0s

  [13587/20519] intraday_3067.csv.gz  in=370,941,480 out=113,176,626 elapsed=208.0s

  [13588/20519] intraday_3068.csv.gz  in=370,954,614 out=113,176,626 elapsed=208.0s

  [13589/20519] intraday_3070.csv.gz  in=370,970,508 out=113,176,626 elapsed=208.1s

  [13590/20519] intraday_3069.csv.gz  in=370,986,938 out=113,176,626 elapsed=208.1s

  [13591/20519] intraday_3071.csv.gz  in=371,001,592 out=113,176,626 elapsed=208.1s

  [13592/20519] intraday_3072.csv.gz  in=371,015,224 out=113,176,626 elapsed=208.1s

  [13593/20519] intraday_3075.csv.gz  in=371,028,658 out=113,176,626 elapsed=208.1s

  [13594/20519] intraday_3073.csv.gz  in=371,043,619 out=113,176,626 elapsed=208.1s

  [13595/20519] intraday_3074.csv.gz  in=371,058,183 out=113,176,626 elapsed=208.1s

  [13596/20519] intraday_3076.csv.gz  in=371,072,866 out=113,176,626 elapsed=208.1s

  [13597/20519] intraday_3078.csv.gz  in=371,087,954 out=113,176,626 elapsed=208.1s

  [13598/20519] intraday_3077.csv.gz  in=371,103,492 out=113,176,626 elapsed=208.1s

  [13599/20519] intraday_3079.csv.gz  in=371,120,365 out=113,176,626 elapsed=208.1s

  [13600/20519] intraday_3080.csv.gz  in=371,133,316 out=113,176,626 elapsed=208.1s

  [13601/20519] intraday_3081.csv.gz  in=371,144,044 out=113,176,626 elapsed=208.2s

  [13602/20519] intraday_3082.csv.gz  in=371,157,498 out=113,176,626 elapsed=208.2s

  [13603/20519] intraday_3083.csv.gz  in=371,169,710 out=113,176,626 elapsed=208.2s

  [13604/20519] intraday_3084.csv.gz  in=371,182,202 out=113,176,626 elapsed=208.2s

  [13605/20519] intraday_3085.csv.gz  in=371,190,335 out=113,176,626 elapsed=208.2s

  [13606/20519] intraday_3086.csv.gz  in=371,201,010 out=113,176,626 elapsed=208.2s

  [13607/20519] intraday_3089.csv.gz  in=371,215,243 out=113,176,626 elapsed=208.2s

  [13608/20519] intraday_3087.csv.gz  in=371,222,205 out=113,176,626 elapsed=208.2s

  [13609/20519] intraday_3088.csv.gz  in=371,236,532 out=113,176,626 elapsed=208.2s

  [13610/20519] intraday_3090.csv.gz  in=371,248,844 out=113,176,626 elapsed=208.2s

  [13611/20519] intraday_3091.csv.gz  in=371,259,091 out=113,176,626 elapsed=208.2s

  [13612/20519] intraday_3092.csv.gz  in=371,275,788 out=113,176,626 elapsed=208.3s

  [13613/20519] intraday_3093.csv.gz  in=371,290,070 out=113,176,626 elapsed=208.3s

  [13614/20519] intraday_3095.csv.gz  in=371,302,214 out=113,176,626 elapsed=208.3s

  [13615/20519] intraday_3094.csv.gz  in=371,314,702 out=113,176,626 elapsed=208.3s

  [13616/20519] intraday_3096.csv.gz  in=371,328,084 out=113,176,626 elapsed=208.4s

  [13617/20519] intraday_3098.csv.gz  in=371,337,821 out=113,176,626 elapsed=208.4s

  [13618/20519] intraday_3097.csv.gz  in=371,351,177 out=113,176,626 elapsed=208.4s

  [13619/20519] intraday_3099.csv.gz  in=371,363,200 out=113,176,626 elapsed=208.4s

  [13620/20519] intraday_3103.csv.gz  in=371,373,277 out=113,176,626 elapsed=208.4s

  [13621/20519] intraday_3101.csv.gz  in=371,385,452 out=113,176,626 elapsed=208.5s

  [13622/20519] intraday_3102.csv.gz  in=371,396,553 out=113,176,626 elapsed=208.5s

  [13623/20519] intraday_3100.csv.gz  in=371,409,042 out=113,176,626 elapsed=208.5s

  [13624/20519] intraday_3107.csv.gz  in=371,420,739 out=113,176,626 elapsed=208.5s

  [13625/20519] intraday_3104.csv.gz  in=371,434,033 out=113,176,626 elapsed=208.5s

  [13626/20519] intraday_3106.csv.gz  in=371,444,525 out=113,176,626 elapsed=208.5s

  [13627/20519] intraday_3105.csv.gz  in=371,456,419 out=113,176,626 elapsed=208.5s

  [13628/20519] intraday_3108.csv.gz  in=371,469,567 out=113,176,626 elapsed=208.6s

  [13629/20519] intraday_3109.csv.gz  in=371,480,667 out=113,176,626 elapsed=208.6s

  [13630/20519] intraday_3110.csv.gz  in=371,493,488 out=113,176,626 elapsed=208.6s

  [13631/20519] intraday_3111.csv.gz  in=371,506,512 out=113,176,626 elapsed=208.6s

  [13632/20519] intraday_3112.csv.gz  in=371,519,072 out=113,176,626 elapsed=208.6s

  [13633/20519] intraday_3113.csv.gz  in=371,529,079 out=113,176,626 elapsed=208.6s

  [13634/20519] intraday_3114.csv.gz  in=371,541,001 out=113,176,626 elapsed=208.6s

  [13635/20519] intraday_3115.csv.gz  in=371,553,543 out=113,176,626 elapsed=208.6s

  [13636/20519] intraday_3119.csv.gz  in=371,566,362 out=113,176,626 elapsed=208.7s

  [13637/20519] intraday_3116.csv.gz  in=371,578,340 out=113,176,626 elapsed=208.7s

  [13638/20519] intraday_3117.csv.gz  in=371,592,595 out=113,176,626 elapsed=208.7s

  [13639/20519] intraday_3118.csv.gz  in=371,605,930 out=113,176,626 elapsed=208.7s

  [13640/20519] intraday_3120.csv.gz  in=371,617,788 out=113,176,626 elapsed=208.7s

  [13641/20519] intraday_3121.csv.gz  in=371,630,766 out=113,176,626 elapsed=208.7s

  [13642/20519] intraday_3122.csv.gz  in=371,642,936 out=113,176,626 elapsed=208.7s

  [13643/20519] intraday_3123.csv.gz  in=371,655,842 out=113,176,626 elapsed=208.7s

  [13644/20519] intraday_3124.csv.gz  in=371,666,335 out=113,176,626 elapsed=208.7s

  [13645/20519] intraday_3126.csv.gz  in=371,676,789 out=113,176,626 elapsed=208.7s

  [13646/20519] intraday_3125.csv.gz  in=371,687,602 out=113,176,626 elapsed=208.8s

  [13647/20519] intraday_3127.csv.gz  in=371,704,915 out=113,176,626 elapsed=208.8s

  [13648/20519] intraday_3128.csv.gz  in=371,718,296 out=113,176,626 elapsed=208.8s

  [13649/20519] intraday_3130.csv.gz  in=371,729,784 out=113,176,626 elapsed=208.8s

  [13650/20519] intraday_3131.csv.gz  in=371,742,690 out=113,176,626 elapsed=208.8s

  [13651/20519] intraday_3129.csv.gz  in=371,756,031 out=113,176,626 elapsed=208.8s

  [13652/20519] intraday_3132.csv.gz  in=371,766,945 out=113,176,626 elapsed=208.8s

  [13653/20519] intraday_3133.csv.gz  in=371,779,261 out=113,176,626 elapsed=208.8s

  [13654/20519] intraday_3134.csv.gz  in=371,791,124 out=113,176,626 elapsed=208.8s

  [13655/20519] intraday_3136.csv.gz  in=371,803,261 out=113,176,626 elapsed=208.8s

  [13656/20519] intraday_3135.csv.gz  in=371,814,070 out=113,176,626 elapsed=208.8s

  [13657/20519] intraday_3139.csv.gz  in=371,824,611 out=113,176,626 elapsed=208.9s

  [13658/20519] intraday_3138.csv.gz  in=371,836,790 out=113,176,626 elapsed=208.9s

  [13659/20519] intraday_3140.csv.gz  in=371,850,796 out=113,176,626 elapsed=208.9s

  [13660/20519] intraday_3137.csv.gz  in=371,861,567 out=113,176,626 elapsed=208.9s

  [13661/20519] intraday_3143.csv.gz  in=371,874,372 out=113,176,626 elapsed=208.9s

  [13662/20519] intraday_3141.csv.gz  in=371,884,360 out=113,176,626 elapsed=208.9s

  [13663/20519] intraday_3144.csv.gz  in=371,895,292 out=113,176,626 elapsed=208.9s

  [13664/20519] intraday_3142.csv.gz  in=371,908,336 out=113,176,626 elapsed=208.9s

  [13665/20519] intraday_3146.csv.gz  in=371,920,383 out=113,176,626 elapsed=208.9s

  [13666/20519] intraday_3148.csv.gz  in=371,931,973 out=113,176,626 elapsed=209.0s

  [13667/20519] intraday_3145.csv.gz  in=371,943,959 out=113,176,626 elapsed=209.0s

  [13668/20519] intraday_3147.csv.gz  in=371,955,529 out=113,176,626 elapsed=209.0s

  [13669/20519] intraday_3151.csv.gz  in=371,967,574 out=113,176,626 elapsed=209.0s

  [13670/20519] intraday_3149.csv.gz  in=371,979,801 out=113,176,626 elapsed=209.0s

  [13671/20519] intraday_3150.csv.gz  in=371,989,409 out=113,176,626 elapsed=209.0s

  [13672/20519] intraday_3152.csv.gz  in=372,003,139 out=113,176,626 elapsed=209.0s

  [13673/20519] intraday_3153.csv.gz  in=372,014,230 out=113,176,626 elapsed=209.0s

  [13674/20519] intraday_3154.csv.gz  in=372,027,909 out=113,176,626 elapsed=209.0s

  [13675/20519] intraday_3156.csv.gz  in=372,036,345 out=113,176,626 elapsed=209.0s

  [13676/20519] intraday_3155.csv.gz  in=372,049,460 out=113,176,626 elapsed=209.0s

  [13677/20519] intraday_3157.csv.gz  in=372,062,341 out=113,176,626 elapsed=209.1s

  [13678/20519] intraday_3159.csv.gz  in=372,074,215 out=113,176,626 elapsed=209.1s

  [13679/20519] intraday_3160.csv.gz  in=372,085,112 out=113,176,626 elapsed=209.1s

  [13680/20519] intraday_3158.csv.gz  in=372,097,103 out=113,176,626 elapsed=209.1s

  [13681/20519] intraday_3162.csv.gz  in=372,107,616 out=113,176,626 elapsed=209.1s

  [13682/20519] intraday_3163.csv.gz  in=372,118,192 out=113,176,626 elapsed=209.1s

  [13683/20519] intraday_3161.csv.gz  in=372,128,818 out=113,176,626 elapsed=209.1s

  [13684/20519] intraday_3164.csv.gz  in=372,141,399 out=113,176,626 elapsed=209.1s

  [13685/20519] intraday_3165.csv.gz  in=372,152,863 out=113,176,626 elapsed=209.1s

  [13686/20519] intraday_3167.csv.gz  in=372,163,817 out=113,176,626 elapsed=209.1s

  [13687/20519] intraday_3166.csv.gz  in=372,176,132 out=113,176,626 elapsed=209.1s

  [13688/20519] intraday_3168.csv.gz  in=372,186,432 out=113,176,626 elapsed=209.1s

  [13689/20519] intraday_3169.csv.gz  in=372,199,929 out=113,176,626 elapsed=209.2s

  [13690/20519] intraday_3173.csv.gz  in=372,209,651 out=113,176,626 elapsed=209.2s

  [13691/20519] intraday_3171.csv.gz  in=372,218,954 out=113,176,626 elapsed=209.2s

  [13692/20519] intraday_3170.csv.gz  in=372,234,582 out=113,176,626 elapsed=209.2s

  [13693/20519] intraday_3172.csv.gz  in=372,246,995 out=113,176,626 elapsed=209.2s

  [13694/20519] intraday_3175.csv.gz  in=372,257,903 out=113,176,626 elapsed=209.2s

  [13695/20519] intraday_3177.csv.gz  in=372,269,255 out=113,176,626 elapsed=209.2s

  [13696/20519] intraday_3176.csv.gz  in=372,283,568 out=113,176,626 elapsed=209.2s

  [13697/20519] intraday_3174.csv.gz  in=372,299,265 out=113,176,626 elapsed=209.2s

  [13698/20519] intraday_3178.csv.gz  in=372,314,590 out=113,176,626 elapsed=209.3s

  [13699/20519] intraday_3181.csv.gz  in=372,326,976 out=113,176,626 elapsed=209.3s

  [13700/20519] intraday_3179.csv.gz  in=372,338,843 out=113,176,626 elapsed=209.3s

  [13701/20519] intraday_3180.csv.gz  in=372,352,482 out=113,176,626 elapsed=209.3s

  [13702/20519] intraday_3182.csv.gz  in=372,363,793 out=113,176,626 elapsed=209.3s

  [13703/20519] intraday_3183.csv.gz  in=372,375,941 out=113,176,626 elapsed=209.3s

  [13704/20519] intraday_3185.csv.gz  in=372,387,305 out=113,176,626 elapsed=209.3s

  [13705/20519] intraday_3184.csv.gz  in=372,400,968 out=113,176,626 elapsed=209.3s

  [13706/20519] intraday_3186.csv.gz  in=372,412,798 out=113,176,626 elapsed=209.3s

  [13707/20519] intraday_3187.csv.gz  in=372,424,596 out=113,176,626 elapsed=209.3s

  [13708/20519] intraday_3189.csv.gz  in=372,435,534 out=113,176,626 elapsed=209.4s

  [13709/20519] intraday_3188.csv.gz  in=372,447,431 out=113,176,626 elapsed=209.4s

  [13710/20519] intraday_3190.csv.gz  in=372,460,151 out=113,176,626 elapsed=209.4s

  [13711/20519] intraday_3191.csv.gz  in=372,472,579 out=113,176,626 elapsed=209.4s

  [13712/20519] intraday_3193.csv.gz  in=372,483,976 out=113,176,626 elapsed=209.4s

  [13713/20519] intraday_3192.csv.gz  in=372,504,508 out=113,176,626 elapsed=209.4s

  [13714/20519] intraday_3194.csv.gz  in=372,517,969 out=113,176,626 elapsed=209.4s

  [13715/20519] intraday_3195.csv.gz  in=372,531,893 out=113,176,626 elapsed=209.4s

  [13716/20519] intraday_3196.csv.gz  in=372,543,574 out=113,176,626 elapsed=209.4s

  [13717/20519] intraday_3198.csv.gz  in=372,556,542 out=113,176,626 elapsed=209.5s

  [13718/20519] intraday_3197.csv.gz  in=372,569,154 out=113,176,626 elapsed=209.5s

  [13719/20519] intraday_3199.csv.gz  in=372,580,863 out=113,176,626 elapsed=209.5s

  [13720/20519] intraday_3200.csv.gz  in=372,593,798 out=113,176,626 elapsed=209.5s

  [13721/20519] intraday_3201.csv.gz  in=372,606,489 out=113,176,626 elapsed=209.5s

  [13722/20519] intraday_3202.csv.gz  in=372,619,909 out=113,176,626 elapsed=209.5s

  [13723/20519] intraday_3204.csv.gz  in=372,633,443 out=113,176,626 elapsed=209.6s

  [13724/20519] intraday_3205.csv.gz  in=372,645,108 out=113,176,626 elapsed=209.6s

  [13725/20519] intraday_3203.csv.gz  in=372,659,977 out=113,176,626 elapsed=209.6s

  [13726/20519] intraday_3206.csv.gz  in=372,672,671 out=113,176,626 elapsed=209.6s

  [13727/20519] intraday_3208.csv.gz  in=372,684,087 out=113,176,626 elapsed=209.6s

  [13728/20519] intraday_3207.csv.gz  in=372,695,739 out=113,176,626 elapsed=209.6s

  [13729/20519] intraday_3209.csv.gz  in=372,707,416 out=113,176,626 elapsed=209.6s

  [13730/20519] intraday_3211.csv.gz  in=372,720,757 out=113,176,626 elapsed=209.7s

  [13731/20519] intraday_3212.csv.gz  in=372,735,508 out=113,176,626 elapsed=209.7s

  [13732/20519] intraday_3213.csv.gz  in=372,746,666 out=113,176,626 elapsed=209.7s

  [13733/20519] intraday_3210.csv.gz  in=372,770,660 out=113,176,626 elapsed=209.7s

  [13734/20519] intraday_3216.csv.gz  in=372,783,075 out=113,176,626 elapsed=209.7s

  [13735/20519] intraday_3215.csv.gz  in=372,795,797 out=113,176,626 elapsed=209.7s

  [13736/20519] intraday_3214.csv.gz  in=372,808,761 out=113,176,626 elapsed=209.7s

  [13737/20519] intraday_3217.csv.gz  in=372,821,796 out=113,176,626 elapsed=209.7s

  [13738/20519] intraday_3219.csv.gz  in=372,835,296 out=113,176,626 elapsed=209.8s

  [13739/20519] intraday_3218.csv.gz  in=372,850,623 out=113,176,626 elapsed=209.8s

  [13740/20519] intraday_3220.csv.gz  in=372,863,866 out=113,176,626 elapsed=209.8s

  [13741/20519] intraday_3221.csv.gz  in=372,876,548 out=113,176,626 elapsed=209.8s

  [13742/20519] intraday_3222.csv.gz  in=372,887,814 out=113,176,626 elapsed=209.8s

  [13743/20519] intraday_3223.csv.gz  in=372,900,272 out=113,176,626 elapsed=209.8s

  [13744/20519] intraday_3224.csv.gz  in=372,910,078 out=113,176,626 elapsed=209.8s

  [13745/20519] intraday_3225.csv.gz  in=372,923,820 out=113,176,626 elapsed=209.8s

  [13746/20519] intraday_3226.csv.gz  in=372,930,411 out=113,176,626 elapsed=209.8s

  [13747/20519] intraday_3228.csv.gz  in=372,938,830 out=113,176,626 elapsed=209.8s

  [13748/20519] intraday_3227.csv.gz  in=372,949,171 out=113,176,626 elapsed=209.9s

  [13749/20519] intraday_3229.csv.gz  in=372,963,525 out=113,176,626 elapsed=209.9s

  [13750/20519] intraday_3231.csv.gz  in=372,975,190 out=113,176,626 elapsed=209.9s

  [13751/20519] intraday_3230.csv.gz  in=372,988,675 out=113,176,626 elapsed=209.9s

  [13752/20519] intraday_3232.csv.gz  in=372,998,572 out=113,176,626 elapsed=209.9s

  [13753/20519] intraday_3233.csv.gz  in=373,012,599 out=113,176,626 elapsed=209.9s

  [13754/20519] intraday_3235.csv.gz  in=373,025,030 out=113,176,626 elapsed=209.9s

  [13755/20519] intraday_3237.csv.gz  in=373,037,979 out=113,176,626 elapsed=209.9s

  [13756/20519] intraday_3234.csv.gz  in=373,051,955 out=113,176,626 elapsed=209.9s

  [13757/20519] intraday_3236.csv.gz  in=373,063,748 out=113,176,626 elapsed=209.9s

  [13758/20519] intraday_3241.csv.gz  in=373,075,674 out=113,176,626 elapsed=210.0s

  [13759/20519] intraday_3239.csv.gz  in=373,085,134 out=113,176,626 elapsed=210.0s

  [13760/20519] intraday_3238.csv.gz  in=373,097,775 out=113,176,626 elapsed=210.0s

  [13761/20519] intraday_3240.csv.gz  in=373,109,943 out=113,176,626 elapsed=210.0s

  [13762/20519] intraday_3242.csv.gz  in=373,121,547 out=113,176,626 elapsed=210.0s

  [13763/20519] intraday_3243.csv.gz  in=373,132,806 out=113,176,626 elapsed=210.0s

  [13764/20519] intraday_3244.csv.gz  in=373,148,829 out=113,176,626 elapsed=210.0s

  [13765/20519] intraday_3245.csv.gz  in=373,161,677 out=113,176,626 elapsed=210.0s

  [13766/20519] intraday_3247.csv.gz  in=373,171,838 out=113,176,626 elapsed=210.0s

  [13767/20519] intraday_3246.csv.gz  in=373,183,078 out=113,176,626 elapsed=210.0s

  [13768/20519] intraday_3248.csv.gz  in=373,194,459 out=113,176,626 elapsed=210.1s

  [13769/20519] intraday_3249.csv.gz  in=373,207,308 out=113,176,626 elapsed=210.1s

  [13770/20519] intraday_3251.csv.gz  in=373,219,021 out=113,176,626 elapsed=210.1s

  [13771/20519] intraday_3250.csv.gz  in=373,230,204 out=113,176,626 elapsed=210.1s

  [13772/20519] intraday_3252.csv.gz  in=373,242,565 out=113,176,626 elapsed=210.1s

  [13773/20519] intraday_3255.csv.gz  in=373,254,535 out=113,176,626 elapsed=210.1s

  [13774/20519] intraday_3253.csv.gz  in=373,266,593 out=113,176,626 elapsed=210.1s

  [13775/20519] intraday_3254.csv.gz  in=373,280,648 out=113,176,626 elapsed=210.1s

  [13776/20519] intraday_3256.csv.gz  in=373,293,551 out=113,176,626 elapsed=210.1s

  [13777/20519] intraday_3258.csv.gz  in=373,308,463 out=113,176,626 elapsed=210.1s

  [13778/20519] intraday_3257.csv.gz  in=373,319,803 out=113,176,626 elapsed=210.2s

  [13779/20519] intraday_3259.csv.gz  in=373,333,556 out=113,176,626 elapsed=210.2s

  [13780/20519] intraday_3260.csv.gz  in=373,346,655 out=113,176,626 elapsed=210.2s

  [13781/20519] intraday_3262.csv.gz  in=373,358,598 out=113,176,626 elapsed=210.2s

  [13782/20519] intraday_3263.csv.gz  in=373,370,770 out=113,176,626 elapsed=210.2s

  [13783/20519] intraday_3261.csv.gz  in=373,381,428 out=113,176,626 elapsed=210.2s

  [13784/20519] intraday_3264.csv.gz  in=373,393,977 out=113,176,626 elapsed=210.2s

  [13785/20519] intraday_3265.csv.gz  in=373,408,368 out=113,176,626 elapsed=210.2s

  [13786/20519] intraday_3266.csv.gz  in=373,419,172 out=113,176,626 elapsed=210.2s

  [13787/20519] intraday_3267.csv.gz  in=373,434,771 out=113,176,626 elapsed=210.2s

  [13788/20519] intraday_3268.csv.gz  in=373,445,417 out=113,176,626 elapsed=210.3s

  [13789/20519] intraday_3269.csv.gz  in=373,458,954 out=113,176,626 elapsed=210.3s

  [13790/20519] intraday_3271.csv.gz  in=373,469,471 out=113,176,626 elapsed=210.3s

  [13791/20519] intraday_3270.csv.gz  in=373,481,933 out=113,176,626 elapsed=210.3s

  [13792/20519] intraday_3273.csv.gz  in=373,492,072 out=113,176,626 elapsed=210.3s

  [13793/20519] intraday_3272.csv.gz  in=373,504,687 out=113,176,626 elapsed=210.3s

  [13794/20519] intraday_3274.csv.gz  in=373,515,905 out=113,176,626 elapsed=210.3s

  [13795/20519] intraday_3275.csv.gz  in=373,527,686 out=113,176,626 elapsed=210.3s

  [13796/20519] intraday_3276.csv.gz  in=373,538,161 out=113,176,626 elapsed=210.3s

  [13797/20519] intraday_3278.csv.gz  in=373,549,067 out=113,176,626 elapsed=210.3s

  [13798/20519] intraday_3277.csv.gz  in=373,566,471 out=113,176,626 elapsed=210.3s

  [13799/20519] intraday_3279.csv.gz  in=373,577,435 out=113,176,626 elapsed=210.4s

  [13800/20519] intraday_3280.csv.gz  in=373,588,213 out=113,176,626 elapsed=210.4s

  [13801/20519] intraday_3281.csv.gz  in=373,600,879 out=113,176,626 elapsed=210.4s

  [13802/20519] intraday_3282.csv.gz  in=373,610,352 out=113,176,626 elapsed=210.4s

  [13803/20519] intraday_3284.csv.gz  in=373,620,886 out=113,176,626 elapsed=210.4s

  [13804/20519] intraday_3285.csv.gz  in=373,630,733 out=113,176,626 elapsed=210.4s

  [13805/20519] intraday_3283.csv.gz  in=373,645,208 out=113,176,626 elapsed=210.4s

  [13806/20519] intraday_3286.csv.gz  in=373,656,622 out=113,176,626 elapsed=210.4s

  [13807/20519] intraday_3287.csv.gz  in=373,668,435 out=113,176,626 elapsed=210.5s

  [13808/20519] intraday_3288.csv.gz  in=373,679,221 out=113,176,626 elapsed=210.5s

  [13809/20519] intraday_3289.csv.gz  in=373,702,286 out=113,176,626 elapsed=210.5s

  [13810/20519] intraday_3290.csv.gz  in=373,713,481 out=113,176,626 elapsed=210.5s

  [13811/20519] intraday_3291.csv.gz  in=373,723,040 out=113,176,626 elapsed=210.5s

  [13812/20519] intraday_3292.csv.gz  in=373,735,080 out=113,176,626 elapsed=210.5s

  [13813/20519] intraday_3293.csv.gz  in=373,748,260 out=113,176,626 elapsed=210.5s

  [13814/20519] intraday_3294.csv.gz  in=373,765,762 out=113,176,626 elapsed=210.5s

  [13815/20519] intraday_3295.csv.gz  in=373,778,471 out=113,176,626 elapsed=210.6s

  [13816/20519] intraday_3297.csv.gz  in=373,787,912 out=113,176,626 elapsed=210.6s

  [13817/20519] intraday_3296.csv.gz  in=373,800,922 out=113,176,626 elapsed=210.6s

  [13818/20519] intraday_3298.csv.gz  in=373,812,438 out=113,176,626 elapsed=210.6s

  [13819/20519] intraday_3299.csv.gz  in=373,823,197 out=113,176,626 elapsed=210.6s

  [13820/20519] intraday_3300.csv.gz  in=373,834,749 out=113,176,626 elapsed=210.6s

  [13821/20519] intraday_3302.csv.gz  in=373,846,093 out=113,176,626 elapsed=210.6s

  [13822/20519] intraday_3301.csv.gz  in=373,857,500 out=113,176,626 elapsed=210.6s

  [13823/20519] intraday_3303.csv.gz  in=373,867,346 out=113,176,626 elapsed=210.6s

  [13824/20519] intraday_3304.csv.gz  in=373,878,451 out=113,176,626 elapsed=210.7s

  [13825/20519] intraday_3305.csv.gz  in=373,891,133 out=113,176,626 elapsed=210.7s

  [13826/20519] intraday_3306.csv.gz  in=373,902,231 out=113,176,626 elapsed=210.7s

  [13827/20519] intraday_3307.csv.gz  in=373,914,154 out=113,176,626 elapsed=210.7s

  [13828/20519] intraday_3309.csv.gz  in=373,924,733 out=113,176,626 elapsed=210.7s

  [13829/20519] intraday_3308.csv.gz  in=373,934,118 out=113,176,626 elapsed=210.7s

  [13830/20519] intraday_3310.csv.gz  in=373,946,796 out=113,176,626 elapsed=210.7s

  [13831/20519] intraday_3311.csv.gz  in=373,960,903 out=113,176,626 elapsed=210.7s

  [13832/20519] intraday_3313.csv.gz  in=373,972,158 out=113,176,626 elapsed=210.7s

  [13833/20519] intraday_3312.csv.gz  in=373,982,287 out=113,176,626 elapsed=210.7s

  [13834/20519] intraday_3314.csv.gz  in=373,991,623 out=113,176,626 elapsed=210.7s

  [13835/20519] intraday_3315.csv.gz  in=374,004,898 out=113,176,626 elapsed=210.7s

  [13836/20519] intraday_3316.csv.gz  in=374,016,369 out=113,176,626 elapsed=210.8s

  [13837/20519] intraday_3317.csv.gz  in=374,031,038 out=113,176,626 elapsed=210.8s

  [13838/20519] intraday_3319.csv.gz  in=374,045,508 out=113,176,626 elapsed=210.8s

  [13839/20519] intraday_3318.csv.gz  in=374,056,566 out=113,176,626 elapsed=210.8s

  [13840/20519] intraday_3320.csv.gz  in=374,069,532 out=113,176,626 elapsed=210.8s

  [13841/20519] intraday_3321.csv.gz  in=374,082,233 out=113,176,626 elapsed=210.8s

  [13842/20519] intraday_3322.csv.gz  in=374,094,943 out=113,176,626 elapsed=210.8s

  [13843/20519] intraday_3324.csv.gz  in=374,106,451 out=113,176,626 elapsed=210.8s

  [13844/20519] intraday_3323.csv.gz  in=374,116,778 out=113,176,626 elapsed=210.8s

  [13845/20519] intraday_3327.csv.gz  in=374,127,435 out=113,176,626 elapsed=210.9s

  [13846/20519] intraday_3326.csv.gz  in=374,138,211 out=113,176,626 elapsed=210.9s

  [13847/20519] intraday_3325.csv.gz  in=374,152,586 out=113,176,626 elapsed=210.9s

  [13848/20519] intraday_3328.csv.gz  in=374,164,165 out=113,176,626 elapsed=210.9s

  [13849/20519] intraday_3329.csv.gz  in=374,176,545 out=113,176,626 elapsed=210.9s

  [13850/20519] intraday_3330.csv.gz  in=374,188,357 out=113,176,626 elapsed=210.9s

  [13851/20519] intraday_3331.csv.gz  in=374,200,187 out=113,176,626 elapsed=210.9s

  [13852/20519] intraday_3332.csv.gz  in=374,211,832 out=113,176,626 elapsed=210.9s

  [13853/20519] intraday_3333.csv.gz  in=374,223,364 out=113,176,626 elapsed=210.9s

  [13854/20519] intraday_3336.csv.gz  in=374,236,781 out=113,176,626 elapsed=210.9s

  [13855/20519] intraday_3335.csv.gz  in=374,250,560 out=113,176,626 elapsed=210.9s

  [13856/20519] intraday_3334.csv.gz  in=374,261,216 out=113,176,626 elapsed=211.0s

  [13857/20519] intraday_3337.csv.gz  in=374,272,649 out=113,176,626 elapsed=211.0s

  [13858/20519] intraday_3338.csv.gz  in=374,284,714 out=113,176,626 elapsed=211.0s

  [13859/20519] intraday_3340.csv.gz  in=374,295,962 out=113,176,626 elapsed=211.0s

  [13860/20519] intraday_3339.csv.gz  in=374,312,338 out=113,176,626 elapsed=211.0s

  [13861/20519] intraday_3341.csv.gz  in=374,324,763 out=113,176,626 elapsed=211.0s

  [13862/20519] intraday_3343.csv.gz  in=374,337,149 out=113,176,626 elapsed=211.1s

  [13863/20519] intraday_3342.csv.gz  in=374,350,437 out=113,176,626 elapsed=211.1s

  [13864/20519] intraday_3344.csv.gz  in=374,365,302 out=113,176,626 elapsed=211.1s

  [13865/20519] intraday_3345.csv.gz  in=374,379,201 out=113,176,626 elapsed=211.1s

  [13866/20519] intraday_3346.csv.gz  in=374,391,188 out=113,176,626 elapsed=211.1s

  [13867/20519] intraday_3347.csv.gz  in=374,403,822 out=113,176,626 elapsed=211.1s

  [13868/20519] intraday_3348.csv.gz  in=374,416,684 out=113,176,626 elapsed=211.1s

  [13869/20519] intraday_3351.csv.gz  in=374,430,031 out=113,176,626 elapsed=211.1s

  [13870/20519] intraday_3350.csv.gz  in=374,440,045 out=113,176,626 elapsed=211.1s

  [13871/20519] intraday_3349.csv.gz  in=374,458,753 out=113,176,626 elapsed=211.1s

  [13872/20519] intraday_3352.csv.gz  in=374,471,266 out=113,176,626 elapsed=211.1s

  [13873/20519] intraday_3353.csv.gz  in=374,487,169 out=113,176,626 elapsed=211.2s

  [13874/20519] intraday_3354.csv.gz  in=374,498,623 out=113,176,626 elapsed=211.2s

  [13875/20519] intraday_3356.csv.gz  in=374,511,452 out=113,176,626 elapsed=211.2s

  [13876/20519] intraday_3358.csv.gz  in=374,523,754 out=113,176,626 elapsed=211.2s

  [13877/20519] intraday_3355.csv.gz  in=374,535,261 out=113,176,626 elapsed=211.2s

  [13878/20519] intraday_3357.csv.gz  in=374,547,798 out=113,176,626 elapsed=211.2s

  [13879/20519] intraday_3359.csv.gz  in=374,562,562 out=113,176,626 elapsed=211.2s

  [13880/20519] intraday_3361.csv.gz  in=374,575,178 out=113,176,626 elapsed=211.2s

  [13881/20519] intraday_3362.csv.gz  in=374,588,134 out=113,176,626 elapsed=211.2s

  [13882/20519] intraday_3363.csv.gz  in=374,598,936 out=113,176,626 elapsed=211.2s

  [13883/20519] intraday_3360.csv.gz  in=374,611,729 out=113,176,626 elapsed=211.3s

  [13884/20519] intraday_3365.csv.gz  in=374,621,361 out=113,176,626 elapsed=211.3s

  [13885/20519] intraday_3364.csv.gz  in=374,637,575 out=113,176,626 elapsed=211.3s

  [13886/20519] intraday_3366.csv.gz  in=374,650,781 out=113,176,626 elapsed=211.3s

  [13887/20519] intraday_3367.csv.gz  in=374,657,458 out=113,176,626 elapsed=211.3s

  [13888/20519] intraday_3368.csv.gz  in=374,667,031 out=113,176,626 elapsed=211.3s

  [13889/20519] intraday_3369.csv.gz  in=374,677,399 out=113,176,626 elapsed=211.3s

  [13890/20519] intraday_3370.csv.gz  in=374,692,267 out=113,176,626 elapsed=211.3s

  [13891/20519] intraday_3371.csv.gz  in=374,706,046 out=113,176,626 elapsed=211.3s

  [13892/20519] intraday_3373.csv.gz  in=374,716,390 out=113,176,626 elapsed=211.3s

  [13893/20519] intraday_3372.csv.gz  in=374,727,957 out=113,176,626 elapsed=211.3s

  [13894/20519] intraday_3375.csv.gz  in=374,742,543 out=113,176,626 elapsed=211.3s

  [13895/20519] intraday_3374.csv.gz  in=374,757,124 out=113,176,626 elapsed=211.4s

  [13896/20519] intraday_3376.csv.gz  in=374,769,891 out=113,176,626 elapsed=211.4s

  [13897/20519] intraday_3377.csv.gz  in=374,782,058 out=113,176,626 elapsed=211.4s

  [13898/20519] intraday_3379.csv.gz  in=374,795,607 out=113,176,626 elapsed=211.4s

  [13899/20519] intraday_3378.csv.gz  in=374,809,290 out=113,176,626 elapsed=211.4s

  [13900/20519] intraday_3380.csv.gz  in=374,818,877 out=113,176,626 elapsed=211.5s

  [13901/20519] intraday_3381.csv.gz  in=374,830,737 out=113,176,626 elapsed=211.5s

  [13902/20519] intraday_3384.csv.gz  in=374,842,503 out=113,176,626 elapsed=211.5s

  [13903/20519] intraday_3383.csv.gz  in=374,852,687 out=113,176,626 elapsed=211.5s

  [13904/20519] intraday_3382.csv.gz  in=374,865,482 out=113,176,626 elapsed=211.5s

  [13905/20519] intraday_3385.csv.gz  in=374,876,813 out=113,176,626 elapsed=211.5s

  [13906/20519] intraday_3386.csv.gz  in=374,889,302 out=113,176,626 elapsed=211.5s

  [13907/20519] intraday_3388.csv.gz  in=374,900,870 out=113,176,626 elapsed=211.5s

  [13908/20519] intraday_3387.csv.gz  in=374,913,025 out=113,176,626 elapsed=211.5s

  [13909/20519] intraday_3389.csv.gz  in=374,925,421 out=113,176,626 elapsed=211.6s

  [13910/20519] intraday_3391.csv.gz  in=374,936,791 out=113,176,626 elapsed=211.6s

  [13911/20519] intraday_3390.csv.gz  in=374,949,574 out=113,176,626 elapsed=211.6s

  [13912/20519] intraday_3394.csv.gz  in=374,961,485 out=113,176,626 elapsed=211.6s

  [13913/20519] intraday_3392.csv.gz  in=374,973,637 out=113,176,626 elapsed=211.6s

  [13914/20519] intraday_3393.csv.gz  in=374,986,363 out=113,176,626 elapsed=211.6s

  [13915/20519] intraday_3396.csv.gz  in=374,998,041 out=113,176,626 elapsed=211.6s

  [13916/20519] intraday_3395.csv.gz  in=375,009,196 out=113,176,626 elapsed=211.6s

  [13917/20519] intraday_3397.csv.gz  in=375,021,987 out=113,176,626 elapsed=211.6s

  [13918/20519] intraday_3398.csv.gz  in=375,036,060 out=113,176,626 elapsed=211.6s

  [13919/20519] intraday_3400.csv.gz  in=375,048,424 out=113,176,626 elapsed=211.7s

  [13920/20519] intraday_3401.csv.gz  in=375,061,001 out=113,176,626 elapsed=211.7s

  [13921/20519] intraday_3399.csv.gz  in=375,077,329 out=113,176,626 elapsed=211.7s

  [13922/20519] intraday_3402.csv.gz  in=375,089,196 out=113,176,626 elapsed=211.7s

  [13923/20519] intraday_3403.csv.gz  in=375,102,306 out=113,176,626 elapsed=211.7s

  [13924/20519] intraday_3405.csv.gz  in=375,114,534 out=113,176,626 elapsed=211.7s

  [13925/20519] intraday_3404.csv.gz  in=375,127,249 out=113,176,626 elapsed=211.7s

  [13926/20519] intraday_3406.csv.gz  in=375,138,214 out=113,176,626 elapsed=211.7s

  [13927/20519] intraday_3407.csv.gz  in=375,148,020 out=113,176,626 elapsed=211.8s

  [13928/20519] intraday_3409.csv.gz  in=375,157,595 out=113,176,626 elapsed=211.8s

  [13929/20519] intraday_3408.csv.gz  in=375,169,214 out=113,176,626 elapsed=211.8s

  [13930/20519] intraday_3410.csv.gz  in=375,183,704 out=113,176,626 elapsed=211.8s

  [13931/20519] intraday_3412.csv.gz  in=375,196,332 out=113,176,626 elapsed=211.8s

  [13932/20519] intraday_3411.csv.gz  in=375,208,926 out=113,176,626 elapsed=211.8s

  [13933/20519] intraday_3413.csv.gz  in=375,220,358 out=113,176,626 elapsed=211.8s

  [13934/20519] intraday_3414.csv.gz  in=375,231,005 out=113,176,626 elapsed=211.8s

  [13935/20519] intraday_3416.csv.gz  in=375,241,573 out=113,176,626 elapsed=211.8s

  [13936/20519] intraday_3417.csv.gz  in=375,252,086 out=113,176,626 elapsed=211.8s

  [13937/20519] intraday_3415.csv.gz  in=375,265,037 out=113,176,626 elapsed=211.8s

  [13938/20519] intraday_3418.csv.gz  in=375,276,974 out=113,176,626 elapsed=211.8s

  [13939/20519] intraday_3420.csv.gz  in=375,288,312 out=113,176,626 elapsed=211.9s

  [13940/20519] intraday_3419.csv.gz  in=375,299,862 out=113,176,626 elapsed=211.9s

  [13941/20519] intraday_3422.csv.gz  in=375,309,495 out=113,176,626 elapsed=211.9s

  [13942/20519] intraday_3421.csv.gz  in=375,321,461 out=113,176,626 elapsed=211.9s

  [13943/20519] intraday_3423.csv.gz  in=375,334,923 out=113,176,626 elapsed=211.9s

  [13944/20519] intraday_3424.csv.gz  in=375,346,573 out=113,176,626 elapsed=211.9s

  [13945/20519] intraday_3425.csv.gz  in=375,357,186 out=113,176,626 elapsed=211.9s

  [13946/20519] intraday_3426.csv.gz  in=375,367,078 out=113,176,626 elapsed=211.9s

  [13947/20519] intraday_3427.csv.gz  in=375,379,221 out=113,176,626 elapsed=211.9s

  [13948/20519] intraday_3429.csv.gz  in=375,390,446 out=113,176,626 elapsed=211.9s

  [13949/20519] intraday_3428.csv.gz  in=375,403,459 out=113,176,626 elapsed=211.9s

  [13950/20519] intraday_3433.csv.gz  in=375,417,409 out=113,176,626 elapsed=212.0s

  [13951/20519] intraday_3431.csv.gz  in=375,429,944 out=113,176,626 elapsed=212.0s

  [13952/20519] intraday_3430.csv.gz  in=375,441,113 out=113,176,626 elapsed=212.0s

  [13953/20519] intraday_3432.csv.gz  in=375,450,644 out=113,176,626 elapsed=212.0s

  [13954/20519] intraday_3435.csv.gz  in=375,461,087 out=113,176,626 elapsed=212.0s

  [13955/20519] intraday_3434.csv.gz  in=375,475,086 out=113,176,626 elapsed=212.0s

  [13956/20519] intraday_3436.csv.gz  in=375,488,323 out=113,176,626 elapsed=212.0s

  [13957/20519] intraday_3437.csv.gz  in=375,501,531 out=113,176,626 elapsed=212.0s

  [13958/20519] intraday_3438.csv.gz  in=375,510,965 out=113,176,626 elapsed=212.0s

  [13959/20519] intraday_3439.csv.gz  in=375,522,175 out=113,176,626 elapsed=212.0s

  [13960/20519] intraday_3440.csv.gz  in=375,533,726 out=113,176,626 elapsed=212.0s

  [13961/20519] intraday_3441.csv.gz  in=375,547,166 out=113,176,626 elapsed=212.1s

  [13962/20519] intraday_3442.csv.gz  in=375,556,241 out=113,176,626 elapsed=212.1s

  [13963/20519] intraday_3444.csv.gz  in=375,567,325 out=113,176,626 elapsed=212.1s

  [13964/20519] intraday_3443.csv.gz  in=375,578,681 out=113,176,626 elapsed=212.1s

  [13965/20519] intraday_3445.csv.gz  in=375,590,855 out=113,176,626 elapsed=212.1s

  [13966/20519] intraday_3447.csv.gz  in=375,603,510 out=113,176,626 elapsed=212.1s

  [13967/20519] intraday_3446.csv.gz  in=375,615,660 out=113,176,626 elapsed=212.1s

  [13968/20519] intraday_3448.csv.gz  in=375,626,174 out=113,176,626 elapsed=212.1s

  [13969/20519] intraday_3449.csv.gz  in=375,635,659 out=113,176,626 elapsed=212.1s

  [13970/20519] intraday_3451.csv.gz  in=375,651,599 out=113,176,626 elapsed=212.1s

  [13971/20519] intraday_3450.csv.gz  in=375,662,339 out=113,176,626 elapsed=212.2s

  [13972/20519] intraday_3452.csv.gz  in=375,675,093 out=113,176,626 elapsed=212.2s

  [13973/20519] intraday_3453.csv.gz  in=375,686,527 out=113,176,626 elapsed=212.2s

  [13974/20519] intraday_3455.csv.gz  in=375,696,994 out=113,176,626 elapsed=212.2s

  [13975/20519] intraday_3454.csv.gz  in=375,707,550 out=113,176,626 elapsed=212.2s

  [13976/20519] intraday_3456.csv.gz  in=375,719,843 out=113,176,626 elapsed=212.2s

  [13977/20519] intraday_3457.csv.gz  in=375,733,616 out=113,176,626 elapsed=212.2s

  [13978/20519] intraday_3458.csv.gz  in=375,746,114 out=113,176,626 elapsed=212.2s

  [13979/20519] intraday_3459.csv.gz  in=375,758,866 out=113,176,626 elapsed=212.2s

  [13980/20519] intraday_3460.csv.gz  in=375,773,035 out=113,176,626 elapsed=212.2s

  [13981/20519] intraday_3461.csv.gz  in=375,786,567 out=113,176,626 elapsed=212.2s

  [13982/20519] intraday_3462.csv.gz  in=375,799,909 out=113,176,626 elapsed=212.2s

  [13983/20519] intraday_3463.csv.gz  in=375,811,706 out=113,176,626 elapsed=212.3s

  [13984/20519] intraday_3464.csv.gz  in=375,824,312 out=113,176,626 elapsed=212.3s

  [13985/20519] intraday_3465.csv.gz  in=375,834,864 out=113,176,626 elapsed=212.3s

  [13986/20519] intraday_3467.csv.gz  in=375,846,581 out=113,176,626 elapsed=212.3s

  [13987/20519] intraday_3466.csv.gz  in=375,859,999 out=113,176,626 elapsed=212.3s

  [13988/20519] intraday_3468.csv.gz  in=375,872,719 out=113,176,626 elapsed=212.3s

  [13989/20519] intraday_3469.csv.gz  in=375,882,930 out=113,176,626 elapsed=212.3s

  [13990/20519] intraday_3470.csv.gz  in=375,895,776 out=113,176,626 elapsed=212.3s

  [13991/20519] intraday_3471.csv.gz  in=375,908,128 out=113,176,626 elapsed=212.3s

  [13992/20519] intraday_3472.csv.gz  in=375,920,842 out=113,176,626 elapsed=212.3s

  [13993/20519] intraday_3474.csv.gz  in=375,932,196 out=113,176,626 elapsed=212.4s

  [13994/20519] intraday_3475.csv.gz  in=375,944,239 out=113,176,626 elapsed=212.4s

  [13995/20519] intraday_3473.csv.gz  in=375,958,325 out=113,176,626 elapsed=212.4s

  [13996/20519] intraday_3476.csv.gz  in=375,973,311 out=113,176,626 elapsed=212.4s

  [13997/20519] intraday_3477.csv.gz  in=375,987,253 out=113,176,626 elapsed=212.5s

  [13998/20519] intraday_3479.csv.gz  in=375,999,916 out=113,176,626 elapsed=212.5s

  [13999/20519] intraday_3478.csv.gz  in=376,012,116 out=113,176,626 elapsed=212.5s

  [14000/20519] intraday_3480.csv.gz  in=376,024,514 out=113,176,626 elapsed=212.5s

  [14001/20519] intraday_3481.csv.gz  in=376,036,930 out=113,176,626 elapsed=212.5s

  [14002/20519] intraday_3482.csv.gz  in=376,050,513 out=113,176,626 elapsed=212.5s

  [14003/20519] intraday_3483.csv.gz  in=376,065,368 out=113,176,626 elapsed=212.5s

  [14004/20519] intraday_3485.csv.gz  in=376,081,598 out=113,176,626 elapsed=212.6s

  [14005/20519] intraday_3484.csv.gz  in=376,093,362 out=113,176,626 elapsed=212.6s

  [14006/20519] intraday_3486.csv.gz  in=376,105,372 out=113,176,626 elapsed=212.6s

  [14007/20519] intraday_3487.csv.gz  in=376,117,830 out=113,176,626 elapsed=212.6s

  [14008/20519] intraday_3488.csv.gz  in=376,128,940 out=113,176,626 elapsed=212.6s

  [14009/20519] intraday_3490.csv.gz  in=376,139,138 out=113,176,626 elapsed=212.6s

  [14010/20519] intraday_3489.csv.gz  in=376,152,125 out=113,176,626 elapsed=212.6s

  [14011/20519] intraday_3493.csv.gz  in=376,166,609 out=113,176,626 elapsed=212.6s

  [14012/20519] intraday_3491.csv.gz  in=376,181,377 out=113,176,626 elapsed=212.6s

  [14013/20519] intraday_3492.csv.gz  in=376,193,926 out=113,176,626 elapsed=212.6s

  [14014/20519] intraday_3494.csv.gz  in=376,206,390 out=113,176,626 elapsed=212.6s

  [14015/20519] intraday_3495.csv.gz  in=376,219,389 out=113,176,626 elapsed=212.7s

  [14016/20519] intraday_3497.csv.gz  in=376,232,519 out=113,176,626 elapsed=212.7s

  [14017/20519] intraday_3496.csv.gz  in=376,244,956 out=113,176,626 elapsed=212.7s

  [14018/20519] intraday_3498.csv.gz  in=376,257,597 out=113,176,626 elapsed=212.7s

  [14019/20519] intraday_3499.csv.gz  in=376,272,178 out=113,176,626 elapsed=212.7s

  [14020/20519] intraday_3501.csv.gz  in=376,285,324 out=113,176,626 elapsed=212.7s

  [14021/20519] intraday_3500.csv.gz  in=376,299,914 out=113,176,626 elapsed=212.7s

  [14022/20519] intraday_3502.csv.gz  in=376,313,281 out=113,176,626 elapsed=212.7s

  [14023/20519] intraday_3505.csv.gz  in=376,325,120 out=113,176,626 elapsed=212.7s

  [14024/20519] intraday_3504.csv.gz  in=376,335,798 out=113,176,626 elapsed=212.8s

  [14025/20519] intraday_3503.csv.gz  in=376,347,528 out=113,176,626 elapsed=212.8s

  [14026/20519] intraday_3506.csv.gz  in=376,360,639 out=113,176,626 elapsed=212.8s

  [14027/20519] intraday_3507.csv.gz  in=376,369,025 out=113,176,626 elapsed=212.8s

  [14028/20519] intraday_3508.csv.gz  in=376,377,764 out=113,176,626 elapsed=212.8s

  [14029/20519] intraday_3509.csv.gz  in=376,390,285 out=113,176,626 elapsed=212.8s

  [14030/20519] intraday_3510.csv.gz  in=376,404,492 out=113,176,626 elapsed=212.8s

  [14031/20519] intraday_3512.csv.gz  in=376,416,786 out=113,176,626 elapsed=212.8s

  [14032/20519] intraday_3511.csv.gz  in=376,430,183 out=113,176,626 elapsed=212.8s

  [14033/20519] intraday_3513.csv.gz  in=376,440,171 out=113,176,626 elapsed=212.8s

  [14034/20519] intraday_3514.csv.gz  in=376,453,685 out=113,176,626 elapsed=212.8s

  [14035/20519] intraday_3516.csv.gz  in=376,466,281 out=113,176,626 elapsed=212.9s

  [14036/20519] intraday_3515.csv.gz  in=376,479,879 out=113,176,626 elapsed=212.9s

  [14037/20519] intraday_3517.csv.gz  in=376,491,908 out=113,176,626 elapsed=212.9s

  [14038/20519] intraday_3518.csv.gz  in=376,506,196 out=113,176,626 elapsed=212.9s

  [14039/20519] intraday_3520.csv.gz  in=376,515,440 out=113,176,626 elapsed=212.9s

  [14040/20519] intraday_3519.csv.gz  in=376,528,790 out=113,176,626 elapsed=212.9s

  [14041/20519] intraday_3522.csv.gz  in=376,540,965 out=113,176,626 elapsed=212.9s

  [14042/20519] intraday_3521.csv.gz  in=376,553,402 out=113,176,626 elapsed=212.9s

  [14043/20519] intraday_3523.csv.gz  in=376,563,907 out=113,176,626 elapsed=212.9s

  [14044/20519] intraday_3525.csv.gz  in=376,575,241 out=113,176,626 elapsed=212.9s

  [14045/20519] intraday_3526.csv.gz  in=376,587,936 out=113,176,626 elapsed=212.9s

  [14046/20519] intraday_3524.csv.gz  in=376,599,841 out=113,176,626 elapsed=213.0s

  [14047/20519] intraday_3527.csv.gz  in=376,612,202 out=113,176,626 elapsed=213.0s

  [14048/20519] intraday_3529.csv.gz  in=376,625,316 out=113,176,626 elapsed=213.0s

  [14049/20519] intraday_3530.csv.gz  in=376,638,241 out=113,176,626 elapsed=213.0s

  [14050/20519] intraday_3528.csv.gz  in=376,649,963 out=113,176,626 elapsed=213.0s

  [14051/20519] intraday_3531.csv.gz  in=376,661,343 out=113,176,626 elapsed=213.0s

  [14052/20519] intraday_3532.csv.gz  in=376,672,693 out=113,176,626 elapsed=213.0s

  [14053/20519] intraday_3534.csv.gz  in=376,685,096 out=113,176,626 elapsed=213.0s

  [14054/20519] intraday_3533.csv.gz  in=376,698,080 out=113,176,626 elapsed=213.0s

  [14055/20519] intraday_3536.csv.gz  in=376,710,290 out=113,176,626 elapsed=213.0s

  [14056/20519] intraday_3535.csv.gz  in=376,720,895 out=113,176,626 elapsed=213.0s

  [14057/20519] intraday_3537.csv.gz  in=376,733,227 out=113,176,626 elapsed=213.0s

  [14058/20519] intraday_3538.csv.gz  in=376,747,369 out=113,176,626 elapsed=213.1s

  [14059/20519] intraday_3541.csv.gz  in=376,758,943 out=113,176,626 elapsed=213.1s

  [14060/20519] intraday_3539.csv.gz  in=376,773,219 out=113,176,626 elapsed=213.1s

  [14061/20519] intraday_3542.csv.gz  in=376,784,669 out=113,176,626 elapsed=213.1s

  [14062/20519] intraday_3540.csv.gz  in=376,797,740 out=113,176,626 elapsed=213.1s

  [14063/20519] intraday_3543.csv.gz  in=376,810,329 out=113,176,626 elapsed=213.1s

  [14064/20519] intraday_3545.csv.gz  in=376,822,653 out=113,176,626 elapsed=213.1s

  [14065/20519] intraday_3544.csv.gz  in=376,834,172 out=113,176,626 elapsed=213.1s

  [14066/20519] intraday_3546.csv.gz  in=376,845,041 out=113,176,626 elapsed=213.1s

  [14067/20519] intraday_3547.csv.gz  in=376,855,728 out=113,176,626 elapsed=213.1s

  [14068/20519] intraday_3548.csv.gz  in=376,866,698 out=113,176,626 elapsed=213.1s

  [14069/20519] intraday_3550.csv.gz  in=376,880,571 out=113,176,626 elapsed=213.2s

  [14070/20519] intraday_3549.csv.gz  in=376,890,889 out=113,176,626 elapsed=213.2s

  [14071/20519] intraday_3551.csv.gz  in=376,903,155 out=113,176,626 elapsed=213.2s

  [14072/20519] intraday_3553.csv.gz  in=376,914,436 out=113,176,626 elapsed=213.2s

  [14073/20519] intraday_3552.csv.gz  in=376,928,006 out=113,176,626 elapsed=213.2s

  [14074/20519] intraday_3554.csv.gz  in=376,939,343 out=113,176,626 elapsed=213.2s

  [14075/20519] intraday_3556.csv.gz  in=376,949,535 out=113,176,626 elapsed=213.2s

  [14076/20519] intraday_3557.csv.gz  in=376,961,319 out=113,176,626 elapsed=213.2s

  [14077/20519] intraday_3555.csv.gz  in=376,973,973 out=113,176,626 elapsed=213.2s

  [14078/20519] intraday_3558.csv.gz  in=376,985,819 out=113,176,626 elapsed=213.2s

  [14079/20519] intraday_3559.csv.gz  in=376,996,200 out=113,176,626 elapsed=213.2s

  [14080/20519] intraday_3561.csv.gz  in=377,007,096 out=113,176,626 elapsed=213.3s

  [14081/20519] intraday_3560.csv.gz  in=377,018,523 out=113,176,626 elapsed=213.3s

  [14082/20519] intraday_3562.csv.gz  in=377,028,936 out=113,176,626 elapsed=213.3s

  [14083/20519] intraday_3563.csv.gz  in=377,041,778 out=113,176,626 elapsed=213.3s

  [14084/20519] intraday_3566.csv.gz  in=377,051,287 out=113,176,626 elapsed=213.3s

  [14085/20519] intraday_3564.csv.gz  in=377,063,611 out=113,176,626 elapsed=213.3s

  [14086/20519] intraday_3565.csv.gz  in=377,074,047 out=113,176,626 elapsed=213.3s

  [14087/20519] intraday_3567.csv.gz  in=377,087,835 out=113,176,626 elapsed=213.3s

  [14088/20519] intraday_3568.csv.gz  in=377,101,134 out=113,176,626 elapsed=213.3s

  [14089/20519] intraday_3570.csv.gz  in=377,113,242 out=113,176,626 elapsed=213.3s

  [14090/20519] intraday_3572.csv.gz  in=377,123,566 out=113,176,626 elapsed=213.3s

  [14091/20519] intraday_3569.csv.gz  in=377,134,748 out=113,176,626 elapsed=213.3s

  [14092/20519] intraday_3571.csv.gz  in=377,146,160 out=113,176,626 elapsed=213.3s

  [14093/20519] intraday_3576.csv.gz  in=377,158,852 out=113,176,626 elapsed=213.4s

  [14094/20519] intraday_3574.csv.gz  in=377,171,687 out=113,176,626 elapsed=213.4s

  [14095/20519] intraday_3573.csv.gz  in=377,185,049 out=113,176,626 elapsed=213.4s

  [14096/20519] intraday_3575.csv.gz  in=377,197,581 out=113,176,626 elapsed=213.4s

  [14097/20519] intraday_3577.csv.gz  in=377,208,100 out=113,176,626 elapsed=213.4s

  [14098/20519] intraday_3580.csv.gz  in=377,218,957 out=113,176,626 elapsed=213.4s

  [14099/20519] intraday_3578.csv.gz  in=377,229,248 out=113,176,626 elapsed=213.4s

  [14100/20519] intraday_3579.csv.gz  in=377,241,083 out=113,176,626 elapsed=213.4s

  [14101/20519] intraday_3581.csv.gz  in=377,254,375 out=113,176,626 elapsed=213.4s

  [14102/20519] intraday_3583.csv.gz  in=377,264,108 out=113,176,626 elapsed=213.4s

  [14103/20519] intraday_3582.csv.gz  in=377,274,364 out=113,176,626 elapsed=213.4s

  [14104/20519] intraday_3585.csv.gz  in=377,287,089 out=113,176,626 elapsed=213.4s

  [14105/20519] intraday_3586.csv.gz  in=377,298,973 out=113,176,626 elapsed=213.5s

  [14106/20519] intraday_3584.csv.gz  in=377,309,663 out=113,176,626 elapsed=213.5s

  [14107/20519] intraday_3587.csv.gz  in=377,322,464 out=113,176,626 elapsed=213.5s

  [14108/20519] intraday_3588.csv.gz  in=377,333,889 out=113,176,626 elapsed=213.5s

  [14109/20519] intraday_3589.csv.gz  in=377,345,397 out=113,176,626 elapsed=213.5s

  [14110/20519] intraday_3590.csv.gz  in=377,356,613 out=113,176,626 elapsed=213.5s

  [14111/20519] intraday_3591.csv.gz  in=377,370,293 out=113,176,626 elapsed=213.5s

  [14112/20519] intraday_3592.csv.gz  in=377,382,692 out=113,176,626 elapsed=213.5s

  [14113/20519] intraday_3593.csv.gz  in=377,393,551 out=113,176,626 elapsed=213.5s

  [14114/20519] intraday_3594.csv.gz  in=377,403,886 out=113,176,626 elapsed=213.5s

  [14115/20519] intraday_3596.csv.gz  in=377,416,270 out=113,176,626 elapsed=213.6s

  [14116/20519] intraday_3595.csv.gz  in=377,428,272 out=113,176,626 elapsed=213.6s

  [14117/20519] intraday_3597.csv.gz  in=377,443,382 out=113,176,626 elapsed=213.6s

  [14118/20519] intraday_3598.csv.gz  in=377,454,111 out=113,176,626 elapsed=213.6s

  [14119/20519] intraday_3599.csv.gz  in=377,471,419 out=113,176,626 elapsed=213.6s

  [14120/20519] intraday_3600.csv.gz  in=377,484,579 out=113,176,626 elapsed=213.6s

  [14121/20519] intraday_3602.csv.gz  in=377,497,579 out=113,176,626 elapsed=213.6s

  [14122/20519] intraday_3601.csv.gz  in=377,511,850 out=113,176,626 elapsed=213.6s

  [14123/20519] intraday_3603.csv.gz  in=377,523,232 out=113,176,626 elapsed=213.6s

  [14124/20519] intraday_3604.csv.gz  in=377,534,694 out=113,176,626 elapsed=213.6s

  [14125/20519] intraday_3605.csv.gz  in=377,546,941 out=113,176,626 elapsed=213.6s

  [14126/20519] intraday_3607.csv.gz  in=377,558,163 out=113,176,626 elapsed=213.7s

  [14127/20519] intraday_3606.csv.gz  in=377,576,837 out=113,176,626 elapsed=213.7s

  [14128/20519] intraday_3609.csv.gz  in=377,589,512 out=113,176,626 elapsed=213.7s

  [14129/20519] intraday_3608.csv.gz  in=377,601,588 out=113,176,626 elapsed=213.7s

  [14130/20519] intraday_3610.csv.gz  in=377,612,716 out=113,176,626 elapsed=213.7s

  [14131/20519] intraday_3612.csv.gz  in=377,624,848 out=113,176,626 elapsed=213.7s

  [14132/20519] intraday_3611.csv.gz  in=377,638,698 out=113,176,626 elapsed=213.7s

  [14133/20519] intraday_3613.csv.gz  in=377,651,931 out=113,176,626 elapsed=213.7s

  [14134/20519] intraday_3617.csv.gz  in=377,664,898 out=113,176,626 elapsed=213.8s

  [14135/20519] intraday_3615.csv.gz  in=377,677,499 out=113,176,626 elapsed=213.8s

  [14136/20519] intraday_3614.csv.gz  in=377,690,159 out=113,176,626 elapsed=213.8s

  [14137/20519] intraday_3616.csv.gz  in=377,704,283 out=113,176,626 elapsed=213.8s

  [14138/20519] intraday_3618.csv.gz  in=377,715,653 out=113,176,626 elapsed=213.8s

  [14139/20519] intraday_3620.csv.gz  in=377,727,456 out=113,176,626 elapsed=213.8s

  [14140/20519] intraday_3619.csv.gz  in=377,740,962 out=113,176,626 elapsed=213.8s

  [14141/20519] intraday_3621.csv.gz  in=377,753,595 out=113,176,626 elapsed=213.8s

  [14142/20519] intraday_3622.csv.gz  in=377,767,694 out=113,176,626 elapsed=213.8s

  [14143/20519] intraday_3624.csv.gz  in=377,781,220 out=113,176,626 elapsed=213.8s

  [14144/20519] intraday_3623.csv.gz  in=377,794,810 out=113,176,626 elapsed=213.8s

  [14145/20519] intraday_3625.csv.gz  in=377,808,709 out=113,176,626 elapsed=213.8s

  [14146/20519] intraday_3626.csv.gz  in=377,821,243 out=113,176,626 elapsed=213.9s

  [14147/20519] intraday_3628.csv.gz  in=377,832,090 out=113,176,626 elapsed=213.9s

  [14148/20519] intraday_3627.csv.gz  in=377,844,056 out=113,176,626 elapsed=213.9s

  [14149/20519] intraday_3629.csv.gz  in=377,856,736 out=113,176,626 elapsed=213.9s

  [14150/20519] intraday_3630.csv.gz  in=377,866,351 out=113,176,626 elapsed=213.9s

  [14151/20519] intraday_3632.csv.gz  in=377,879,197 out=113,176,626 elapsed=213.9s

  [14152/20519] intraday_3631.csv.gz  in=377,892,081 out=113,176,626 elapsed=213.9s

  [14153/20519] intraday_3633.csv.gz  in=377,910,591 out=113,176,626 elapsed=213.9s

  [14154/20519] intraday_3634.csv.gz  in=377,921,644 out=113,176,626 elapsed=213.9s

  [14155/20519] intraday_3636.csv.gz  in=377,934,384 out=113,176,626 elapsed=213.9s

  [14156/20519] intraday_3635.csv.gz  in=377,947,284 out=113,176,626 elapsed=213.9s

  [14157/20519] intraday_3637.csv.gz  in=377,959,052 out=113,176,626 elapsed=213.9s

  [14158/20519] intraday_3638.csv.gz  in=377,972,629 out=113,176,626 elapsed=214.0s

  [14159/20519] intraday_3639.csv.gz  in=377,990,499 out=113,176,626 elapsed=214.0s

  [14160/20519] intraday_3641.csv.gz  in=378,003,259 out=113,176,626 elapsed=214.0s

  [14161/20519] intraday_3640.csv.gz  in=378,017,312 out=113,176,626 elapsed=214.0s

  [14162/20519] intraday_3643.csv.gz  in=378,028,528 out=113,176,626 elapsed=214.0s

  [14163/20519] intraday_3642.csv.gz  in=378,041,191 out=113,176,626 elapsed=214.0s

  [14164/20519] intraday_3644.csv.gz  in=378,052,693 out=113,176,626 elapsed=214.0s

  [14165/20519] intraday_3645.csv.gz  in=378,063,742 out=113,176,626 elapsed=214.0s

  [14166/20519] intraday_3646.csv.gz  in=378,077,321 out=113,176,626 elapsed=214.0s

  [14167/20519] intraday_3647.csv.gz  in=378,086,188 out=113,176,626 elapsed=214.0s

  [14168/20519] intraday_3648.csv.gz  in=378,094,653 out=113,176,626 elapsed=214.0s

  [14169/20519] intraday_3649.csv.gz  in=378,104,727 out=113,176,626 elapsed=214.1s

  [14170/20519] intraday_3651.csv.gz  in=378,118,903 out=113,176,626 elapsed=214.1s

  [14171/20519] intraday_3650.csv.gz  in=378,134,101 out=113,176,626 elapsed=214.1s

  [14172/20519] intraday_3652.csv.gz  in=378,147,440 out=113,176,626 elapsed=214.1s

  [14173/20519] intraday_3653.csv.gz  in=378,157,841 out=113,176,626 elapsed=214.1s

  [14174/20519] intraday_3654.csv.gz  in=378,172,564 out=113,176,626 elapsed=214.1s

  [14175/20519] intraday_3655.csv.gz  in=378,186,993 out=113,176,626 elapsed=214.1s

  [14176/20519] intraday_3656.csv.gz  in=378,203,055 out=113,176,626 elapsed=214.1s

  [14177/20519] intraday_3657.csv.gz  in=378,215,638 out=113,176,626 elapsed=214.1s

  [14178/20519] intraday_3658.csv.gz  in=378,229,696 out=113,176,626 elapsed=214.1s

  [14179/20519] intraday_3660.csv.gz  in=378,239,387 out=113,176,626 elapsed=214.2s

  [14180/20519] intraday_3659.csv.gz  in=378,254,495 out=113,176,626 elapsed=214.2s

  [14181/20519] intraday_3661.csv.gz  in=378,267,065 out=113,176,626 elapsed=214.2s

  [14182/20519] intraday_3662.csv.gz  in=378,280,019 out=113,176,626 elapsed=214.2s

  [14183/20519] intraday_3663.csv.gz  in=378,290,753 out=113,176,626 elapsed=214.2s

  [14184/20519] intraday_3664.csv.gz  in=378,302,701 out=113,176,626 elapsed=214.2s

  [14185/20519] intraday_3665.csv.gz  in=378,314,309 out=113,176,626 elapsed=214.2s

  [14186/20519] intraday_3666.csv.gz  in=378,327,189 out=113,176,626 elapsed=214.2s

  [14187/20519] intraday_3667.csv.gz  in=378,340,174 out=113,176,626 elapsed=214.2s

  [14188/20519] intraday_3668.csv.gz  in=378,350,977 out=113,176,626 elapsed=214.2s

  [14189/20519] intraday_3669.csv.gz  in=378,364,238 out=113,176,626 elapsed=214.2s

  [14190/20519] intraday_3671.csv.gz  in=378,375,565 out=113,176,626 elapsed=214.3s

  [14191/20519] intraday_3670.csv.gz  in=378,389,614 out=113,176,626 elapsed=214.3s

  [14192/20519] intraday_3673.csv.gz  in=378,401,793 out=113,176,626 elapsed=214.3s

  [14193/20519] intraday_3672.csv.gz  in=378,414,097 out=113,176,626 elapsed=214.3s

  [14194/20519] intraday_3674.csv.gz  in=378,426,598 out=113,176,626 elapsed=214.3s

  [14195/20519] intraday_3677.csv.gz  in=378,439,368 out=113,176,626 elapsed=214.3s

  [14196/20519] intraday_3675.csv.gz  in=378,450,349 out=113,176,626 elapsed=214.3s

  [14197/20519] intraday_3676.csv.gz  in=378,462,961 out=113,176,626 elapsed=214.3s

  [14198/20519] intraday_3678.csv.gz  in=378,477,290 out=113,176,626 elapsed=214.3s

  [14199/20519] intraday_3679.csv.gz  in=378,493,773 out=113,176,626 elapsed=214.3s

  [14200/20519] intraday_3680.csv.gz  in=378,510,211 out=113,176,626 elapsed=214.3s

  [14201/20519] intraday_3681.csv.gz  in=378,521,184 out=113,176,626 elapsed=214.4s

  [14202/20519] intraday_3682.csv.gz  in=378,532,744 out=113,176,626 elapsed=214.4s

  [14203/20519] intraday_3683.csv.gz  in=378,545,361 out=113,176,626 elapsed=214.4s

  [14204/20519] intraday_3684.csv.gz  in=378,557,137 out=113,176,626 elapsed=214.4s

  [14205/20519] intraday_3685.csv.gz  in=378,570,193 out=113,176,626 elapsed=214.4s

  [14206/20519] intraday_3686.csv.gz  in=378,584,831 out=113,176,626 elapsed=214.4s

  [14207/20519] intraday_3687.csv.gz  in=378,594,537 out=113,176,626 elapsed=214.4s

  [14208/20519] intraday_3688.csv.gz  in=378,607,854 out=113,176,626 elapsed=214.4s

  [14209/20519] intraday_3691.csv.gz  in=378,620,195 out=113,176,626 elapsed=214.5s

  [14210/20519] intraday_3689.csv.gz  in=378,630,621 out=113,176,626 elapsed=214.5s

  [14211/20519] intraday_3690.csv.gz  in=378,644,356 out=113,176,626 elapsed=214.5s

  [14212/20519] intraday_3692.csv.gz  in=378,656,368 out=113,176,626 elapsed=214.5s

  [14213/20519] intraday_3693.csv.gz  in=378,668,046 out=113,176,626 elapsed=214.5s

  [14214/20519] intraday_3694.csv.gz  in=378,679,289 out=113,176,626 elapsed=214.6s

  [14215/20519] intraday_3695.csv.gz  in=378,692,547 out=113,176,626 elapsed=214.6s

  [14216/20519] intraday_3696.csv.gz  in=378,703,366 out=113,176,626 elapsed=214.6s

  [14217/20519] intraday_3697.csv.gz  in=378,715,526 out=113,176,626 elapsed=214.6s

  [14218/20519] intraday_3699.csv.gz  in=378,726,790 out=113,176,626 elapsed=214.6s

  [14219/20519] intraday_3700.csv.gz  in=378,738,740 out=113,176,626 elapsed=214.6s

  [14220/20519] intraday_3698.csv.gz  in=378,750,850 out=113,176,626 elapsed=214.6s

  [14221/20519] intraday_3701.csv.gz  in=378,765,429 out=113,176,626 elapsed=214.6s

  [14222/20519] intraday_3702.csv.gz  in=378,775,338 out=113,176,626 elapsed=214.6s

  [14223/20519] intraday_3704.csv.gz  in=378,786,950 out=113,176,626 elapsed=214.6s

  [14224/20519] intraday_3703.csv.gz  in=378,800,600 out=113,176,626 elapsed=214.6s

  [14225/20519] intraday_3705.csv.gz  in=378,811,462 out=113,176,626 elapsed=214.7s

  [14226/20519] intraday_3706.csv.gz  in=378,822,340 out=113,176,626 elapsed=214.7s

  [14227/20519] intraday_3707.csv.gz  in=378,837,105 out=113,176,626 elapsed=214.7s

  [14228/20519] intraday_3708.csv.gz  in=378,850,405 out=113,176,626 elapsed=214.8s

  [14229/20519] intraday_3712.csv.gz  in=378,860,551 out=113,176,626 elapsed=214.9s

  [14230/20519] intraday_3709.csv.gz  in=378,872,346 out=113,176,626 elapsed=214.9s

  [14231/20519] intraday_3710.csv.gz  in=378,883,359 out=113,176,626 elapsed=214.9s

  [14232/20519] intraday_3711.csv.gz  in=378,905,854 out=113,176,626 elapsed=214.9s

  [14233/20519] intraday_3713.csv.gz  in=378,922,577 out=113,176,626 elapsed=214.9s

  [14234/20519] intraday_3714.csv.gz  in=378,935,915 out=113,176,626 elapsed=214.9s

  [14235/20519] intraday_3715.csv.gz  in=378,948,418 out=113,176,626 elapsed=214.9s

  [14236/20519] intraday_3716.csv.gz  in=378,960,590 out=113,176,626 elapsed=214.9s

  [14237/20519] intraday_3718.csv.gz  in=378,970,486 out=113,176,626 elapsed=214.9s

  [14238/20519] intraday_3719.csv.gz  in=378,982,531 out=113,176,626 elapsed=214.9s

  [14239/20519] intraday_3720.csv.gz  in=378,994,331 out=113,176,626 elapsed=215.0s

  [14240/20519] intraday_3717.csv.gz  in=379,010,077 out=113,176,626 elapsed=215.0s

  [14241/20519] intraday_3722.csv.gz  in=379,020,508 out=113,176,626 elapsed=215.0s

  [14242/20519] intraday_3721.csv.gz  in=379,033,800 out=113,176,626 elapsed=215.0s

  [14243/20519] intraday_3724.csv.gz  in=379,045,768 out=113,176,626 elapsed=215.0s

  [14244/20519] intraday_3725.csv.gz  in=379,058,668 out=113,176,626 elapsed=215.0s

  [14245/20519] intraday_3726.csv.gz  in=379,071,122 out=113,176,626 elapsed=215.0s

  [14246/20519] intraday_3723.csv.gz  in=379,083,274 out=113,176,626 elapsed=215.0s

  [14247/20519] intraday_3728.csv.gz  in=379,095,683 out=113,176,626 elapsed=215.0s

  [14248/20519] intraday_3727.csv.gz  in=379,109,306 out=113,176,626 elapsed=215.1s

  [14249/20519] intraday_3730.csv.gz  in=379,119,720 out=113,176,626 elapsed=215.1s

  [14250/20519] intraday_3729.csv.gz  in=379,133,211 out=113,176,626 elapsed=215.1s

  [14251/20519] intraday_3734.csv.gz  in=379,144,011 out=113,176,626 elapsed=215.1s

  [14252/20519] intraday_3733.csv.gz  in=379,156,105 out=113,176,626 elapsed=215.1s

  [14253/20519] intraday_3732.csv.gz  in=379,168,603 out=113,176,626 elapsed=215.1s

  [14254/20519] intraday_3731.csv.gz  in=379,185,108 out=113,176,626 elapsed=215.1s

  [14255/20519] intraday_3735.csv.gz  in=379,197,042 out=113,176,626 elapsed=215.2s

  [14256/20519] intraday_3736.csv.gz  in=379,211,027 out=113,176,626 elapsed=215.2s

  [14257/20519] intraday_3738.csv.gz  in=379,225,088 out=113,176,626 elapsed=215.2s

  [14258/20519] intraday_3737.csv.gz  in=379,239,849 out=113,176,626 elapsed=215.2s

  [14259/20519] intraday_3739.csv.gz  in=379,250,641 out=113,176,626 elapsed=215.2s

  [14260/20519] intraday_3741.csv.gz  in=379,264,889 out=113,176,626 elapsed=215.2s

  [14261/20519] intraday_3742.csv.gz  in=379,278,952 out=113,176,626 elapsed=215.2s

  [14262/20519] intraday_3740.csv.gz  in=379,294,760 out=113,176,626 elapsed=215.2s

  [14263/20519] intraday_3743.csv.gz  in=379,306,583 out=113,176,626 elapsed=215.2s

  [14264/20519] intraday_3744.csv.gz  in=379,319,334 out=113,176,626 elapsed=215.2s

  [14265/20519] intraday_3745.csv.gz  in=379,331,122 out=113,176,626 elapsed=215.2s

  [14266/20519] intraday_3746.csv.gz  in=379,344,345 out=113,176,626 elapsed=215.2s

  [14267/20519] intraday_3747.csv.gz  in=379,356,804 out=113,176,626 elapsed=215.3s

  [14268/20519] intraday_3748.csv.gz  in=379,368,754 out=113,176,626 elapsed=215.3s

  [14269/20519] intraday_3749.csv.gz  in=379,384,020 out=113,176,626 elapsed=215.3s

  [14270/20519] intraday_3750.csv.gz  in=379,397,544 out=113,176,626 elapsed=215.3s

  [14271/20519] intraday_3751.csv.gz  in=379,411,069 out=113,176,626 elapsed=215.3s

  [14272/20519] intraday_3752.csv.gz  in=379,423,973 out=113,176,626 elapsed=215.3s

  [14273/20519] intraday_3754.csv.gz  in=379,435,879 out=113,176,626 elapsed=215.3s

  [14274/20519] intraday_3753.csv.gz  in=379,451,679 out=113,176,626 elapsed=215.3s

  [14275/20519] intraday_3756.csv.gz  in=379,466,506 out=113,176,626 elapsed=215.3s

  [14276/20519] intraday_3755.csv.gz  in=379,480,559 out=113,176,626 elapsed=215.3s

  [14277/20519] intraday_3758.csv.gz  in=379,493,091 out=113,176,626 elapsed=215.3s

  [14278/20519] intraday_3759.csv.gz  in=379,505,508 out=113,176,626 elapsed=215.3s

  [14279/20519] intraday_3757.csv.gz  in=379,519,668 out=113,176,626 elapsed=215.3s

  [14280/20519] intraday_3760.csv.gz  in=379,543,530 out=113,176,626 elapsed=215.4s

  [14281/20519] intraday_3761.csv.gz  in=379,556,045 out=113,176,626 elapsed=215.4s

  [14282/20519] intraday_3763.csv.gz  in=379,573,240 out=113,176,626 elapsed=215.4s

  [14283/20519] intraday_3762.csv.gz  in=379,588,768 out=113,176,626 elapsed=215.5s

  [14284/20519] intraday_3764.csv.gz  in=379,603,087 out=113,176,626 elapsed=215.5s

  [14285/20519] intraday_3765.csv.gz  in=379,618,485 out=113,176,626 elapsed=215.5s

  [14286/20519] intraday_3767.csv.gz  in=379,632,143 out=113,176,626 elapsed=215.5s

  [14287/20519] intraday_3769.csv.gz  in=379,649,792 out=113,176,626 elapsed=215.6s

  [14288/20519] intraday_3768.csv.gz  in=379,661,924 out=113,176,626 elapsed=215.6s

  [14289/20519] intraday_3766.csv.gz  in=379,681,282 out=113,176,626 elapsed=215.6s

  [14290/20519] intraday_3770.csv.gz  in=379,692,626 out=113,176,626 elapsed=215.6s

  [14291/20519] intraday_3773.csv.gz  in=379,705,393 out=113,176,626 elapsed=215.6s

  [14292/20519] intraday_3772.csv.gz  in=379,718,468 out=113,176,626 elapsed=215.6s

  [14293/20519] intraday_3771.csv.gz  in=379,731,017 out=113,176,626 elapsed=215.6s

  [14294/20519] intraday_3774.csv.gz  in=379,746,438 out=113,176,626 elapsed=215.6s

  [14295/20519] intraday_3776.csv.gz  in=379,758,863 out=113,176,626 elapsed=215.6s

  [14296/20519] intraday_3775.csv.gz  in=379,771,008 out=113,176,626 elapsed=215.6s

  [14297/20519] intraday_3777.csv.gz  in=379,784,746 out=113,176,626 elapsed=215.6s

  [14298/20519] intraday_3778.csv.gz  in=379,797,040 out=113,176,626 elapsed=215.6s

  [14299/20519] intraday_3779.csv.gz  in=379,809,748 out=113,176,626 elapsed=215.6s

  [14300/20519] intraday_3780.csv.gz  in=379,824,424 out=113,176,626 elapsed=215.6s

  [14301/20519] intraday_3782.csv.gz  in=379,837,973 out=113,176,626 elapsed=215.7s

  [14302/20519] intraday_3781.csv.gz  in=379,851,858 out=113,176,626 elapsed=215.7s

  [14303/20519] intraday_3783.csv.gz  in=379,864,519 out=113,176,626 elapsed=215.7s

  [14304/20519] intraday_3785.csv.gz  in=379,876,264 out=113,176,626 elapsed=215.7s

  [14305/20519] intraday_3784.csv.gz  in=379,887,784 out=113,176,626 elapsed=215.7s

  [14306/20519] intraday_3786.csv.gz  in=379,899,010 out=113,176,626 elapsed=215.7s

  [14307/20519] intraday_3787.csv.gz  in=379,913,191 out=113,176,626 elapsed=215.7s

  [14308/20519] intraday_3788.csv.gz  in=379,920,426 out=113,176,626 elapsed=215.7s

  [14309/20519] intraday_3789.csv.gz  in=379,931,998 out=113,176,626 elapsed=215.7s

  [14310/20519] intraday_3790.csv.gz  in=379,940,377 out=113,176,626 elapsed=215.7s

  [14311/20519] intraday_3792.csv.gz  in=379,955,570 out=113,176,626 elapsed=215.8s

  [14312/20519] intraday_3791.csv.gz  in=379,971,058 out=113,176,626 elapsed=215.8s

  [14313/20519] intraday_3794.csv.gz  in=379,981,221 out=113,176,626 elapsed=215.8s

  [14314/20519] intraday_3793.csv.gz  in=379,994,014 out=113,176,626 elapsed=215.8s

  [14315/20519] intraday_3795.csv.gz  in=380,010,000 out=113,176,626 elapsed=215.8s

  [14316/20519] intraday_3796.csv.gz  in=380,024,458 out=113,176,626 elapsed=215.8s

  [14317/20519] intraday_3797.csv.gz  in=380,036,885 out=113,176,626 elapsed=215.8s

  [14318/20519] intraday_3798.csv.gz  in=380,048,809 out=113,176,626 elapsed=215.8s

  [14319/20519] intraday_3799.csv.gz  in=380,063,599 out=113,176,626 elapsed=215.8s

  [14320/20519] intraday_3800.csv.gz  in=380,079,013 out=113,176,626 elapsed=215.8s

  [14321/20519] intraday_3801.csv.gz  in=380,088,859 out=113,176,626 elapsed=215.8s

  [14322/20519] intraday_3802.csv.gz  in=380,100,616 out=113,176,626 elapsed=215.8s

  [14323/20519] intraday_3803.csv.gz  in=380,113,777 out=113,176,626 elapsed=215.9s

  [14324/20519] intraday_3804.csv.gz  in=380,124,184 out=113,176,626 elapsed=215.9s

  [14325/20519] intraday_3805.csv.gz  in=380,135,576 out=113,176,626 elapsed=215.9s

  [14326/20519] intraday_3806.csv.gz  in=380,147,137 out=113,176,626 elapsed=215.9s

  [14327/20519] intraday_3809.csv.gz  in=380,157,694 out=113,176,626 elapsed=215.9s

  [14328/20519] intraday_3807.csv.gz  in=380,170,763 out=113,176,626 elapsed=215.9s

  [14329/20519] intraday_3808.csv.gz  in=380,183,971 out=113,176,626 elapsed=215.9s

  [14330/20519] intraday_3810.csv.gz  in=380,196,937 out=113,176,626 elapsed=215.9s

  [14331/20519] intraday_3812.csv.gz  in=380,208,841 out=113,176,626 elapsed=215.9s

  [14332/20519] intraday_3811.csv.gz  in=380,223,294 out=113,176,626 elapsed=215.9s

  [14333/20519] intraday_3813.csv.gz  in=380,235,433 out=113,176,626 elapsed=216.0s

  [14334/20519] intraday_3814.csv.gz  in=380,247,553 out=113,176,626 elapsed=216.0s

  [14335/20519] intraday_3816.csv.gz  in=380,257,116 out=113,176,626 elapsed=216.0s

  [14336/20519] intraday_3817.csv.gz  in=380,270,106 out=113,176,626 elapsed=216.0s

  [14337/20519] intraday_3818.csv.gz  in=380,282,950 out=113,176,626 elapsed=216.0s

  [14338/20519] intraday_3815.csv.gz  in=380,295,393 out=113,176,626 elapsed=216.0s

  [14339/20519] intraday_3819.csv.gz  in=380,315,037 out=113,176,626 elapsed=216.0s

  [14340/20519] intraday_3821.csv.gz  in=380,330,114 out=113,176,626 elapsed=216.0s

  [14341/20519] intraday_3820.csv.gz  in=380,344,977 out=113,176,626 elapsed=216.0s

  [14342/20519] intraday_3822.csv.gz  in=380,356,886 out=113,176,626 elapsed=216.0s

  [14343/20519] intraday_3823.csv.gz  in=380,369,131 out=113,176,626 elapsed=216.1s

  [14344/20519] intraday_3824.csv.gz  in=380,382,478 out=113,176,626 elapsed=216.1s

  [14345/20519] intraday_3825.csv.gz  in=380,394,099 out=113,176,626 elapsed=216.1s

  [14346/20519] intraday_3826.csv.gz  in=380,407,665 out=113,176,626 elapsed=216.1s

  [14347/20519] intraday_3827.csv.gz  in=380,418,043 out=113,176,626 elapsed=216.1s

  [14348/20519] intraday_3828.csv.gz  in=380,428,641 out=113,176,626 elapsed=216.1s

  [14349/20519] intraday_3829.csv.gz  in=380,440,077 out=113,176,626 elapsed=216.1s

  [14350/20519] intraday_3831.csv.gz  in=380,454,748 out=113,176,626 elapsed=216.1s

  [14351/20519] intraday_3830.csv.gz  in=380,464,765 out=113,176,626 elapsed=216.1s

  [14352/20519] intraday_3832.csv.gz  in=380,476,934 out=113,176,626 elapsed=216.2s

  [14353/20519] intraday_3834.csv.gz  in=380,488,789 out=113,176,626 elapsed=216.2s

  [14354/20519] intraday_3835.csv.gz  in=380,499,946 out=113,176,626 elapsed=216.2s

  [14355/20519] intraday_3833.csv.gz  in=380,521,967 out=113,176,626 elapsed=216.2s

  [14356/20519] intraday_3836.csv.gz  in=380,535,096 out=113,176,626 elapsed=216.2s

  [14357/20519] intraday_3838.csv.gz  in=380,547,374 out=113,176,626 elapsed=216.2s

  [14358/20519] intraday_3837.csv.gz  in=380,558,570 out=113,176,626 elapsed=216.2s

  [14359/20519] intraday_3841.csv.gz  in=380,569,656 out=113,176,626 elapsed=216.2s

  [14360/20519] intraday_3840.csv.gz  in=380,580,761 out=113,176,626 elapsed=216.2s

  [14361/20519] intraday_3839.csv.gz  in=380,596,111 out=113,176,626 elapsed=216.2s

  [14362/20519] intraday_3842.csv.gz  in=380,607,941 out=113,176,626 elapsed=216.2s

  [14363/20519] intraday_3846.csv.gz  in=380,619,322 out=113,176,626 elapsed=216.3s

  [14364/20519] intraday_3843.csv.gz  in=380,630,137 out=113,176,626 elapsed=216.3s

  [14365/20519] intraday_3844.csv.gz  in=380,642,205 out=113,176,626 elapsed=216.3s

  [14366/20519] intraday_3845.csv.gz  in=380,655,157 out=113,176,626 elapsed=216.3s

  [14367/20519] intraday_3847.csv.gz  in=380,665,703 out=113,176,626 elapsed=216.3s

  [14368/20519] intraday_3848.csv.gz  in=380,679,588 out=113,176,626 elapsed=216.3s

  [14369/20519] intraday_3850.csv.gz  in=380,697,054 out=113,176,626 elapsed=216.3s

  [14370/20519] intraday_3849.csv.gz  in=380,710,754 out=113,176,626 elapsed=216.3s

  [14371/20519] intraday_3851.csv.gz  in=380,721,830 out=113,176,626 elapsed=216.4s

  [14372/20519] intraday_3853.csv.gz  in=380,733,405 out=113,176,626 elapsed=216.4s

  [14373/20519] intraday_3852.csv.gz  in=380,746,174 out=113,176,626 elapsed=216.4s

  [14374/20519] intraday_3854.csv.gz  in=380,760,854 out=113,176,626 elapsed=216.4s

  [14375/20519] intraday_3855.csv.gz  in=380,776,519 out=113,176,626 elapsed=216.4s

  [14376/20519] intraday_3856.csv.gz  in=380,787,824 out=113,176,626 elapsed=216.4s

  [14377/20519] intraday_3857.csv.gz  in=380,801,093 out=113,176,626 elapsed=216.4s

  [14378/20519] intraday_3858.csv.gz  in=380,814,201 out=113,176,626 elapsed=216.5s

  [14379/20519] intraday_3860.csv.gz  in=380,825,490 out=113,176,626 elapsed=216.5s

  [14380/20519] intraday_3861.csv.gz  in=380,836,988 out=113,176,626 elapsed=216.5s

  [14381/20519] intraday_3859.csv.gz  in=380,847,325 out=113,176,626 elapsed=216.5s

  [14382/20519] intraday_3863.csv.gz  in=380,857,373 out=113,176,626 elapsed=216.6s

  [14383/20519] intraday_3862.csv.gz  in=380,870,920 out=113,176,626 elapsed=216.6s

  [14384/20519] intraday_3864.csv.gz  in=380,883,381 out=113,176,626 elapsed=216.6s

  [14385/20519] intraday_3865.csv.gz  in=380,894,797 out=113,176,626 elapsed=216.6s

  [14386/20519] intraday_3866.csv.gz  in=380,907,668 out=113,176,626 elapsed=216.6s

  [14387/20519] intraday_3867.csv.gz  in=380,920,929 out=113,176,626 elapsed=216.6s

  [14388/20519] intraday_3869.csv.gz  in=380,932,638 out=113,176,626 elapsed=216.6s

  [14389/20519] intraday_3868.csv.gz  in=380,945,763 out=113,176,626 elapsed=216.6s

  [14390/20519] intraday_3870.csv.gz  in=380,956,836 out=113,176,626 elapsed=216.6s

  [14391/20519] intraday_3871.csv.gz  in=380,967,347 out=113,176,626 elapsed=216.6s

  [14392/20519] intraday_3872.csv.gz  in=380,984,714 out=113,176,626 elapsed=216.6s

  [14393/20519] intraday_3874.csv.gz  in=380,997,153 out=113,176,626 elapsed=216.7s

  [14394/20519] intraday_3873.csv.gz  in=381,016,933 out=113,176,626 elapsed=216.7s

  [14395/20519] intraday_3875.csv.gz  in=381,027,377 out=113,176,626 elapsed=216.7s

  [14396/20519] intraday_3876.csv.gz  in=381,040,209 out=113,176,626 elapsed=216.7s

  [14397/20519] intraday_3879.csv.gz  in=381,053,911 out=113,176,626 elapsed=216.7s

  [14398/20519] intraday_3877.csv.gz  in=381,067,644 out=113,176,626 elapsed=216.7s

  [14399/20519] intraday_3878.csv.gz  in=381,082,250 out=113,176,626 elapsed=216.7s

  [14400/20519] intraday_3880.csv.gz  in=381,093,266 out=113,176,626 elapsed=216.7s

  [14401/20519] intraday_3882.csv.gz  in=381,108,121 out=113,176,626 elapsed=216.7s

  [14402/20519] intraday_3881.csv.gz  in=381,129,892 out=113,176,626 elapsed=216.8s

  [14403/20519] intraday_3884.csv.gz  in=381,141,926 out=113,176,626 elapsed=216.8s

  [14404/20519] intraday_3883.csv.gz  in=381,158,112 out=113,176,626 elapsed=216.8s

  [14405/20519] intraday_3885.csv.gz  in=381,170,265 out=113,176,626 elapsed=216.8s

  [14406/20519] intraday_3886.csv.gz  in=381,181,987 out=113,176,626 elapsed=216.8s

  [14407/20519] intraday_3887.csv.gz  in=381,195,439 out=113,176,626 elapsed=216.8s

  [14408/20519] intraday_3888.csv.gz  in=381,207,618 out=113,176,626 elapsed=216.8s

  [14409/20519] intraday_3889.csv.gz  in=381,220,120 out=113,176,626 elapsed=216.8s

  [14410/20519] intraday_3890.csv.gz  in=381,232,864 out=113,176,626 elapsed=216.8s

  [14411/20519] intraday_3891.csv.gz  in=381,247,060 out=113,176,626 elapsed=216.8s

  [14412/20519] intraday_3892.csv.gz  in=381,261,601 out=113,176,626 elapsed=216.8s

  [14413/20519] intraday_3893.csv.gz  in=381,275,120 out=113,176,626 elapsed=216.9s

  [14414/20519] intraday_3894.csv.gz  in=381,291,738 out=113,176,626 elapsed=216.9s

  [14415/20519] intraday_3895.csv.gz  in=381,303,213 out=113,176,626 elapsed=216.9s

  [14416/20519] intraday_3896.csv.gz  in=381,315,378 out=113,176,626 elapsed=216.9s

  [14417/20519] intraday_3898.csv.gz  in=381,330,078 out=113,176,626 elapsed=216.9s

  [14418/20519] intraday_3897.csv.gz  in=381,345,333 out=113,176,626 elapsed=216.9s

  [14419/20519] intraday_3900.csv.gz  in=381,359,618 out=113,176,626 elapsed=216.9s

  [14420/20519] intraday_3899.csv.gz  in=381,370,602 out=113,176,626 elapsed=216.9s

  [14421/20519] intraday_3901.csv.gz  in=381,383,140 out=113,176,626 elapsed=216.9s

  [14422/20519] intraday_3902.csv.gz  in=381,396,063 out=113,176,626 elapsed=216.9s

  [14423/20519] intraday_3903.csv.gz  in=381,411,024 out=113,176,626 elapsed=216.9s

  [14424/20519] intraday_3904.csv.gz  in=381,425,124 out=113,176,626 elapsed=217.0s

  [14425/20519] intraday_3907.csv.gz  in=381,436,528 out=113,176,626 elapsed=217.0s

  [14426/20519] intraday_3906.csv.gz  in=381,451,983 out=113,176,626 elapsed=217.0s

  [14427/20519] intraday_3908.csv.gz  in=381,465,368 out=113,176,626 elapsed=217.0s

  [14428/20519] intraday_3905.csv.gz  in=381,482,413 out=113,176,626 elapsed=217.0s

  [14429/20519] intraday_3909.csv.gz  in=381,494,925 out=113,176,626 elapsed=217.0s

  [14430/20519] intraday_3910.csv.gz  in=381,506,747 out=113,176,626 elapsed=217.0s

  [14431/20519] intraday_3911.csv.gz  in=381,517,897 out=113,176,626 elapsed=217.0s

  [14432/20519] intraday_3912.csv.gz  in=381,529,712 out=113,176,626 elapsed=217.0s

  [14433/20519] intraday_3914.csv.gz  in=381,542,377 out=113,176,626 elapsed=217.1s

  [14434/20519] intraday_3913.csv.gz  in=381,556,137 out=113,176,626 elapsed=217.1s

  [14435/20519] intraday_3916.csv.gz  in=381,567,914 out=113,176,626 elapsed=217.1s

  [14436/20519] intraday_3915.csv.gz  in=381,584,611 out=113,176,626 elapsed=217.1s

  [14437/20519] intraday_3917.csv.gz  in=381,596,993 out=113,176,626 elapsed=217.1s

  [14438/20519] intraday_3919.csv.gz  in=381,608,851 out=113,176,626 elapsed=217.1s

  [14439/20519] intraday_3918.csv.gz  in=381,622,145 out=113,176,626 elapsed=217.1s

  [14440/20519] intraday_3920.csv.gz  in=381,634,558 out=113,176,626 elapsed=217.1s

  [14441/20519] intraday_3922.csv.gz  in=381,648,048 out=113,176,626 elapsed=217.1s

  [14442/20519] intraday_3923.csv.gz  in=381,661,719 out=113,176,626 elapsed=217.1s

  [14443/20519] intraday_3921.csv.gz  in=381,676,468 out=113,176,626 elapsed=217.1s

  [14444/20519] intraday_3924.csv.gz  in=381,689,687 out=113,176,626 elapsed=217.2s

  [14445/20519] intraday_3926.csv.gz  in=381,702,971 out=113,176,626 elapsed=217.2s

  [14446/20519] intraday_3925.csv.gz  in=381,714,735 out=113,176,626 elapsed=217.2s

  [14447/20519] intraday_3928.csv.gz  in=381,728,683 out=113,176,626 elapsed=217.2s

  [14448/20519] intraday_3927.csv.gz  in=381,739,261 out=113,176,626 elapsed=217.2s

  [14449/20519] intraday_3929.csv.gz  in=381,747,730 out=113,176,626 elapsed=217.2s

  [14450/20519] intraday_3931.csv.gz  in=381,758,674 out=113,176,626 elapsed=217.2s

  [14451/20519] intraday_3930.csv.gz  in=381,768,154 out=113,176,626 elapsed=217.2s

  [14452/20519] intraday_3933.csv.gz  in=381,782,813 out=113,176,626 elapsed=217.2s

  [14453/20519] intraday_3932.csv.gz  in=381,799,132 out=113,176,626 elapsed=217.2s

  [14454/20519] intraday_3934.csv.gz  in=381,812,103 out=113,176,626 elapsed=217.3s

  [14455/20519] intraday_3935.csv.gz  in=381,822,775 out=113,176,626 elapsed=217.3s

  [14456/20519] intraday_3936.csv.gz  in=381,837,965 out=113,176,626 elapsed=217.3s

  [14457/20519] intraday_3937.csv.gz  in=381,852,788 out=113,176,626 elapsed=217.3s

  [14458/20519] intraday_3939.csv.gz  in=381,865,735 out=113,176,626 elapsed=217.3s

  [14459/20519] intraday_3938.csv.gz  in=381,878,540 out=113,176,626 elapsed=217.3s

  [14460/20519] intraday_3940.csv.gz  in=381,893,441 out=113,176,626 elapsed=217.3s

  [14461/20519] intraday_3941.csv.gz  in=381,909,450 out=113,176,626 elapsed=217.3s

  [14462/20519] intraday_3943.csv.gz  in=381,923,057 out=113,176,626 elapsed=217.3s

  [14463/20519] intraday_3942.csv.gz  in=381,933,040 out=113,176,626 elapsed=217.3s

  [14464/20519] intraday_3944.csv.gz  in=381,946,363 out=113,176,626 elapsed=217.4s

  [14465/20519] intraday_3946.csv.gz  in=381,957,510 out=113,176,626 elapsed=217.4s

  [14466/20519] intraday_3945.csv.gz  in=381,969,529 out=113,176,626 elapsed=217.4s

  [14467/20519] intraday_3948.csv.gz  in=381,981,786 out=113,176,626 elapsed=217.4s

  [14468/20519] intraday_3949.csv.gz  in=381,995,208 out=113,176,626 elapsed=217.4s

  [14469/20519] intraday_3950.csv.gz  in=382,007,392 out=113,176,626 elapsed=217.4s

  [14470/20519] intraday_3947.csv.gz  in=382,020,601 out=113,176,626 elapsed=217.4s

  [14471/20519] intraday_3951.csv.gz  in=382,034,937 out=113,176,626 elapsed=217.4s

  [14472/20519] intraday_3954.csv.gz  in=382,047,529 out=113,176,626 elapsed=217.4s

  [14473/20519] intraday_3953.csv.gz  in=382,060,781 out=113,176,626 elapsed=217.5s

  [14474/20519] intraday_3952.csv.gz  in=382,074,696 out=113,176,626 elapsed=217.5s

  [14475/20519] intraday_3955.csv.gz  in=382,087,788 out=113,176,626 elapsed=217.5s

  [14476/20519] intraday_3957.csv.gz  in=382,098,405 out=113,176,626 elapsed=217.5s

  [14477/20519] intraday_3956.csv.gz  in=382,110,708 out=113,176,626 elapsed=217.5s

  [14478/20519] intraday_3958.csv.gz  in=382,123,631 out=113,176,626 elapsed=217.6s

  [14479/20519] intraday_3961.csv.gz  in=382,139,346 out=113,176,626 elapsed=217.6s

  [14480/20519] intraday_3959.csv.gz  in=382,153,216 out=113,176,626 elapsed=217.6s

  [14481/20519] intraday_3960.csv.gz  in=382,167,804 out=113,176,626 elapsed=217.6s

  [14482/20519] intraday_3963.csv.gz  in=382,179,930 out=113,176,626 elapsed=217.6s

  [14483/20519] intraday_3965.csv.gz  in=382,194,631 out=113,176,626 elapsed=217.6s

  [14484/20519] intraday_3962.csv.gz  in=382,208,221 out=113,176,626 elapsed=217.6s

  [14485/20519] intraday_3964.csv.gz  in=382,221,471 out=113,176,626 elapsed=217.6s

  [14486/20519] intraday_3966.csv.gz  in=382,233,199 out=113,176,626 elapsed=217.7s

  [14487/20519] intraday_3969.csv.gz  in=382,244,399 out=113,176,626 elapsed=217.7s

  [14488/20519] intraday_3968.csv.gz  in=382,256,094 out=113,176,626 elapsed=217.7s

  [14489/20519] intraday_3967.csv.gz  in=382,269,433 out=113,176,626 elapsed=217.7s

  [14490/20519] intraday_3970.csv.gz  in=382,281,276 out=113,176,626 elapsed=217.7s

  [14491/20519] intraday_3971.csv.gz  in=382,294,462 out=113,176,626 elapsed=217.7s

  [14492/20519] intraday_3973.csv.gz  in=382,307,443 out=113,176,626 elapsed=217.7s

  [14493/20519] intraday_3972.csv.gz  in=382,320,415 out=113,176,626 elapsed=217.7s

  [14494/20519] intraday_3974.csv.gz  in=382,334,206 out=113,176,626 elapsed=217.7s

  [14495/20519] intraday_3976.csv.gz  in=382,347,284 out=113,176,626 elapsed=217.7s

  [14496/20519] intraday_3975.csv.gz  in=382,359,290 out=113,176,626 elapsed=217.7s

  [14497/20519] intraday_3977.csv.gz  in=382,371,873 out=113,176,626 elapsed=217.8s

  [14498/20519] intraday_3978.csv.gz  in=382,383,550 out=113,176,626 elapsed=217.8s

  [14499/20519] intraday_3981.csv.gz  in=382,394,205 out=113,176,626 elapsed=217.8s

  [14500/20519] intraday_3979.csv.gz  in=382,407,026 out=113,176,626 elapsed=217.8s

  [14501/20519] intraday_3982.csv.gz  in=382,420,713 out=113,176,626 elapsed=217.8s

  [14502/20519] intraday_3980.csv.gz  in=382,432,608 out=113,176,626 elapsed=217.8s

  [14503/20519] intraday_3983.csv.gz  in=382,443,287 out=113,176,626 elapsed=217.8s

  [14504/20519] intraday_3984.csv.gz  in=382,454,326 out=113,176,626 elapsed=217.8s

  [14505/20519] intraday_3985.csv.gz  in=382,468,443 out=113,176,626 elapsed=217.9s

  [14506/20519] intraday_3986.csv.gz  in=382,480,731 out=113,176,626 elapsed=217.9s

  [14507/20519] intraday_3987.csv.gz  in=382,493,002 out=113,176,626 elapsed=217.9s

  [14508/20519] intraday_3988.csv.gz  in=382,504,015 out=113,176,626 elapsed=217.9s

  [14509/20519] intraday_3990.csv.gz  in=382,516,541 out=113,176,626 elapsed=217.9s

  [14510/20519] intraday_3991.csv.gz  in=382,529,019 out=113,176,626 elapsed=217.9s

  [14511/20519] intraday_3989.csv.gz  in=382,544,188 out=113,176,626 elapsed=217.9s

  [14512/20519] intraday_3992.csv.gz  in=382,557,154 out=113,176,626 elapsed=217.9s

  [14513/20519] intraday_3993.csv.gz  in=382,570,134 out=113,176,626 elapsed=217.9s

  [14514/20519] intraday_3994.csv.gz  in=382,582,118 out=113,176,626 elapsed=217.9s

  [14515/20519] intraday_3995.csv.gz  in=382,597,052 out=113,176,626 elapsed=218.0s

  [14516/20519] intraday_3996.csv.gz  in=382,611,348 out=113,176,626 elapsed=218.0s

  [14517/20519] intraday_3997.csv.gz  in=382,624,760 out=113,176,626 elapsed=218.0s

  [14518/20519] intraday_3999.csv.gz  in=382,635,497 out=113,176,626 elapsed=218.0s

  [14519/20519] intraday_4000.csv.gz  in=382,648,213 out=113,176,626 elapsed=218.0s

  [14520/20519] intraday_3998.csv.gz  in=382,661,685 out=113,176,626 elapsed=218.0s

  [14521/20519] intraday_4001.csv.gz  in=382,673,123 out=113,176,626 elapsed=218.0s

  [14522/20519] intraday_4003.csv.gz  in=382,687,363 out=113,176,626 elapsed=218.0s

  [14523/20519] intraday_4004.csv.gz  in=382,699,611 out=113,176,626 elapsed=218.0s

  [14524/20519] intraday_4002.csv.gz  in=382,712,417 out=113,176,626 elapsed=218.0s

  [14525/20519] intraday_4006.csv.gz  in=382,724,824 out=113,176,626 elapsed=218.1s

  [14526/20519] intraday_4005.csv.gz  in=382,734,685 out=113,176,626 elapsed=218.1s

  [14527/20519] intraday_4007.csv.gz  in=382,750,353 out=113,176,626 elapsed=218.1s

  [14528/20519] intraday_4008.csv.gz  in=382,762,389 out=113,176,626 elapsed=218.1s

  [14529/20519] intraday_4012.csv.gz  in=382,776,404 out=113,176,626 elapsed=218.1s

  [14530/20519] intraday_4010.csv.gz  in=382,787,755 out=113,176,626 elapsed=218.1s

  [14531/20519] intraday_4009.csv.gz  in=382,800,205 out=113,176,626 elapsed=218.1s

  [14532/20519] intraday_4011.csv.gz  in=382,812,200 out=113,176,626 elapsed=218.1s

  [14533/20519] intraday_4015.csv.gz  in=382,824,105 out=113,176,626 elapsed=218.1s

  [14534/20519] intraday_4014.csv.gz  in=382,836,176 out=113,176,626 elapsed=218.1s

  [14535/20519] intraday_4016.csv.gz  in=382,847,898 out=113,176,626 elapsed=218.1s

  [14536/20519] intraday_4013.csv.gz  in=382,863,891 out=113,176,626 elapsed=218.1s

  [14537/20519] intraday_4017.csv.gz  in=382,877,988 out=113,176,626 elapsed=218.2s

  [14538/20519] intraday_4018.csv.gz  in=382,892,680 out=113,176,626 elapsed=218.2s

  [14539/20519] intraday_4020.csv.gz  in=382,903,670 out=113,176,626 elapsed=218.2s

  [14540/20519] intraday_4019.csv.gz  in=382,918,556 out=113,176,626 elapsed=218.2s

  [14541/20519] intraday_4021.csv.gz  in=382,933,100 out=113,176,626 elapsed=218.2s

  [14542/20519] intraday_4024.csv.gz  in=382,948,098 out=113,176,626 elapsed=218.2s

  [14543/20519] intraday_4022.csv.gz  in=382,964,421 out=113,176,626 elapsed=218.2s

  [14544/20519] intraday_4023.csv.gz  in=382,978,247 out=113,176,626 elapsed=218.2s

  [14545/20519] intraday_4025.csv.gz  in=382,990,374 out=113,176,626 elapsed=218.2s

  [14546/20519] intraday_4027.csv.gz  in=383,003,625 out=113,176,626 elapsed=218.3s

  [14547/20519] intraday_4028.csv.gz  in=383,015,590 out=113,176,626 elapsed=218.3s

  [14548/20519] intraday_4026.csv.gz  in=383,027,927 out=113,176,626 elapsed=218.3s

  [14549/20519] intraday_4029.csv.gz  in=383,040,110 out=113,176,626 elapsed=218.3s

  [14550/20519] intraday_4030.csv.gz  in=383,051,717 out=113,176,626 elapsed=218.3s

  [14551/20519] intraday_4031.csv.gz  in=383,065,672 out=113,176,626 elapsed=218.3s

  [14552/20519] intraday_4032.csv.gz  in=383,079,647 out=113,176,626 elapsed=218.3s

  [14553/20519] intraday_4033.csv.gz  in=383,092,993 out=113,176,626 elapsed=218.3s

  [14554/20519] intraday_4034.csv.gz  in=383,105,931 out=113,176,626 elapsed=218.3s

  [14555/20519] intraday_4037.csv.gz  in=383,119,183 out=113,176,626 elapsed=218.3s

  [14556/20519] intraday_4035.csv.gz  in=383,133,090 out=113,176,626 elapsed=218.4s

  [14557/20519] intraday_4036.csv.gz  in=383,146,543 out=113,176,626 elapsed=218.4s

  [14558/20519] intraday_4039.csv.gz  in=383,160,739 out=113,176,626 elapsed=218.4s

  [14559/20519] intraday_4041.csv.gz  in=383,175,084 out=113,176,626 elapsed=218.4s

  [14560/20519] intraday_4040.csv.gz  in=383,187,017 out=113,176,626 elapsed=218.4s

  [14561/20519] intraday_4038.csv.gz  in=383,201,624 out=113,176,626 elapsed=218.4s

  [14562/20519] intraday_4042.csv.gz  in=383,213,971 out=113,176,626 elapsed=218.4s

  [14563/20519] intraday_4043.csv.gz  in=383,227,899 out=113,176,626 elapsed=218.5s

  [14564/20519] intraday_4044.csv.gz  in=383,244,105 out=113,176,626 elapsed=218.5s

  [14565/20519] intraday_4045.csv.gz  in=383,259,066 out=113,176,626 elapsed=218.5s

  [14566/20519] intraday_4046.csv.gz  in=383,272,489 out=113,176,626 elapsed=218.5s

  [14567/20519] intraday_4048.csv.gz  in=383,284,747 out=113,176,626 elapsed=218.5s

  [14568/20519] intraday_4047.csv.gz  in=383,300,796 out=113,176,626 elapsed=218.5s

  [14569/20519] intraday_4049.csv.gz  in=383,313,766 out=113,176,626 elapsed=218.5s

  [14570/20519] intraday_4050.csv.gz  in=383,324,853 out=113,176,626 elapsed=218.5s

  [14571/20519] intraday_4053.csv.gz  in=383,338,410 out=113,176,626 elapsed=218.6s

  [14572/20519] intraday_4051.csv.gz  in=383,352,643 out=113,176,626 elapsed=218.6s

  [14573/20519] intraday_4052.csv.gz  in=383,363,170 out=113,176,626 elapsed=218.6s

  [14574/20519] intraday_4054.csv.gz  in=383,376,712 out=113,176,626 elapsed=218.6s

  [14575/20519] intraday_4056.csv.gz  in=383,388,246 out=113,176,626 elapsed=218.6s

  [14576/20519] intraday_4055.csv.gz  in=383,404,923 out=113,176,626 elapsed=218.6s

  [14577/20519] intraday_4057.csv.gz  in=383,418,358 out=113,176,626 elapsed=218.6s

  [14578/20519] intraday_4059.csv.gz  in=383,430,823 out=113,176,626 elapsed=218.6s

  [14579/20519] intraday_4058.csv.gz  in=383,444,215 out=113,176,626 elapsed=218.6s

  [14580/20519] intraday_4061.csv.gz  in=383,459,080 out=113,176,626 elapsed=218.7s

  [14581/20519] intraday_4060.csv.gz  in=383,473,429 out=113,176,626 elapsed=218.7s

  [14582/20519] intraday_4063.csv.gz  in=383,486,521 out=113,176,626 elapsed=218.7s

  [14583/20519] intraday_4062.csv.gz  in=383,501,343 out=113,176,626 elapsed=218.7s

  [14584/20519] intraday_4065.csv.gz  in=383,512,865 out=113,176,626 elapsed=218.7s

  [14585/20519] intraday_4064.csv.gz  in=383,526,480 out=113,176,626 elapsed=218.7s

  [14586/20519] intraday_4066.csv.gz  in=383,538,871 out=113,176,626 elapsed=218.7s

  [14587/20519] intraday_4067.csv.gz  in=383,551,633 out=113,176,626 elapsed=218.7s

  [14588/20519] intraday_4068.csv.gz  in=383,566,327 out=113,176,626 elapsed=218.7s

  [14589/20519] intraday_4069.csv.gz  in=383,575,999 out=113,176,626 elapsed=218.7s

  [14590/20519] intraday_4072.csv.gz  in=383,576,072 out=113,176,626 elapsed=218.7s

  [14591/20519] intraday_4070.csv.gz  in=383,584,832 out=113,176,626 elapsed=218.8s

  [14592/20519] intraday_4073.csv.gz  in=383,585,877 out=113,176,626 elapsed=218.8s

  [14593/20519] intraday_4071.csv.gz  in=383,597,746 out=113,176,626 elapsed=218.8s

  [14594/20519] intraday_4074.csv.gz  in=383,597,784 out=113,176,626 elapsed=218.8s

  [14595/20519] intraday_4075.csv.gz  in=383,597,912 out=113,176,626 elapsed=218.8s

  [14596/20519] intraday_4077.csv.gz  in=383,598,521 out=113,176,626 elapsed=218.8s

  [14597/20519] intraday_4076.csv.gz  in=383,598,552 out=113,176,626 elapsed=218.8s

  [14598/20519] intraday_4078.csv.gz  in=383,598,704 out=113,176,626 elapsed=218.8s

  [14599/20519] intraday_4080.csv.gz  in=383,598,733 out=113,176,626 elapsed=218.8s

  [14600/20519] intraday_4079.csv.gz  in=383,598,812 out=113,176,626 elapsed=218.8s

  [14601/20519] intraday_4082.csv.gz  in=383,598,824 out=113,176,626 elapsed=218.8s

  [14602/20519] intraday_4081.csv.gz  in=383,599,852 out=113,176,626 elapsed=218.8s

  [14603/20519] intraday_4083.csv.gz  in=383,599,860 out=113,176,626 elapsed=218.8s

  [14604/20519] intraday_4085.csv.gz  in=383,599,963 out=113,176,626 elapsed=218.8s

  [14605/20519] intraday_4084.csv.gz  in=383,600,688 out=113,176,626 elapsed=218.8s

  [14606/20519] intraday_4086.csv.gz  in=383,600,721 out=113,176,626 elapsed=218.8s

  [14607/20519] intraday_4088.csv.gz  in=383,605,049 out=113,176,626 elapsed=218.8s

  [14608/20519] intraday_4087.csv.gz  in=383,605,610 out=113,176,626 elapsed=218.9s

  [14609/20519] intraday_4089.csv.gz  in=383,614,490 out=113,176,626 elapsed=218.9s

  [14610/20519] intraday_4090.csv.gz  in=383,614,637 out=113,176,626 elapsed=218.9s

  [14611/20519] intraday_4093.csv.gz  in=383,614,701 out=113,176,626 elapsed=218.9s

  [14612/20519] intraday_4091.csv.gz  in=383,615,230 out=113,176,626 elapsed=218.9s

  [14613/20519] intraday_4092.csv.gz  in=383,615,307 out=113,176,626 elapsed=218.9s

  [14614/20519] intraday_4094.csv.gz  in=383,616,505 out=113,176,626 elapsed=218.9s

  [14615/20519] intraday_4096.csv.gz  in=383,616,578 out=113,176,626 elapsed=218.9s

  [14616/20519] intraday_4095.csv.gz  in=383,616,691 out=113,176,626 elapsed=218.9s

  [14617/20519] intraday_4097.csv.gz  in=383,623,137 out=113,176,626 elapsed=218.9s

  [14618/20519] intraday_4098.csv.gz  in=383,623,156 out=113,176,626 elapsed=218.9s

  [14619/20519] intraday_4099.csv.gz  in=383,624,107 out=113,176,626 elapsed=218.9s

  [14620/20519] intraday_4102.csv.gz  in=383,624,903 out=113,176,626 elapsed=218.9s

  [14621/20519] intraday_4101.csv.gz  in=383,625,059 out=113,176,626 elapsed=218.9s

  [14622/20519] intraday_4100.csv.gz  in=383,631,493 out=113,176,626 elapsed=218.9s

  [14623/20519] intraday_4104.csv.gz  in=383,631,525 out=113,176,626 elapsed=218.9s

  [14624/20519] intraday_4105.csv.gz  in=383,631,639 out=113,176,626 elapsed=219.0s

  [14625/20519] intraday_4103.csv.gz  in=383,634,124 out=113,176,626 elapsed=219.0s

  [14626/20519] intraday_4106.csv.gz  in=383,634,163 out=113,176,626 elapsed=219.0s

  [14627/20519] intraday_4109.csv.gz  in=383,634,299 out=113,176,626 elapsed=219.0s

  [14628/20519] intraday_4108.csv.gz  in=383,634,712 out=113,176,626 elapsed=219.0s

  [14629/20519] intraday_4107.csv.gz  in=383,642,482 out=113,176,626 elapsed=219.0s

  [14630/20519] intraday_4110.csv.gz  in=383,642,618 out=113,176,626 elapsed=219.0s

  [14631/20519] intraday_4112.csv.gz  in=383,642,881 out=113,176,626 elapsed=219.0s

  [14632/20519] intraday_4113.csv.gz  in=383,643,020 out=113,176,626 elapsed=219.0s

  [14633/20519] intraday_4111.csv.gz  in=383,643,115 out=113,176,626 elapsed=219.0s

  [14634/20519] intraday_4114.csv.gz  in=383,643,183 out=113,176,626 elapsed=219.0s

  [14635/20519] intraday_4115.csv.gz  in=383,658,753 out=113,176,626 elapsed=219.0s

  [14636/20519] intraday_4116.csv.gz  in=383,673,644 out=113,176,626 elapsed=219.0s

  [14637/20519] intraday_4118.csv.gz  in=383,683,912 out=113,176,626 elapsed=219.1s

  [14638/20519] intraday_4117.csv.gz  in=383,696,885 out=113,176,626 elapsed=219.1s

  [14639/20519] intraday_4119.csv.gz  in=383,711,493 out=113,176,626 elapsed=219.1s

  [14640/20519] intraday_4120.csv.gz  in=383,725,943 out=113,176,626 elapsed=219.1s

  [14641/20519] intraday_4121.csv.gz  in=383,738,116 out=113,176,626 elapsed=219.1s

  [14642/20519] intraday_4122.csv.gz  in=383,750,004 out=113,176,626 elapsed=219.1s

  [14643/20519] intraday_4123.csv.gz  in=383,764,297 out=113,176,626 elapsed=219.1s

  [14644/20519] intraday_4125.csv.gz  in=383,774,968 out=113,176,626 elapsed=219.1s

  [14645/20519] intraday_4126.csv.gz  in=383,788,985 out=113,176,626 elapsed=219.2s

  [14646/20519] intraday_4124.csv.gz  in=383,804,493 out=113,176,626 elapsed=219.2s

  [14647/20519] intraday_4127.csv.gz  in=383,816,034 out=113,176,626 elapsed=219.2s

  [14648/20519] intraday_4130.csv.gz  in=383,827,401 out=113,176,626 elapsed=219.2s

  [14649/20519] intraday_4128.csv.gz  in=383,838,943 out=113,176,626 elapsed=219.2s

  [14650/20519] intraday_4129.csv.gz  in=383,849,932 out=113,176,626 elapsed=219.2s

  [14651/20519] intraday_4131.csv.gz  in=383,863,708 out=113,176,626 elapsed=219.2s

  [14652/20519] intraday_4132.csv.gz  in=383,877,676 out=113,176,626 elapsed=219.3s

  [14653/20519] intraday_4134.csv.gz  in=383,890,399 out=113,176,626 elapsed=219.3s

  [14654/20519] intraday_4133.csv.gz  in=383,901,106 out=113,176,626 elapsed=219.3s

  [14655/20519] intraday_4135.csv.gz  in=383,915,267 out=113,176,626 elapsed=219.3s

  [14656/20519] intraday_4136.csv.gz  in=383,927,684 out=113,176,626 elapsed=219.3s

  [14657/20519] intraday_4139.csv.gz  in=383,939,234 out=113,176,626 elapsed=219.3s

  [14658/20519] intraday_4138.csv.gz  in=383,951,577 out=113,176,626 elapsed=219.3s

  [14659/20519] intraday_4140.csv.gz  in=383,961,381 out=113,176,626 elapsed=219.3s

  [14660/20519] intraday_4137.csv.gz  in=383,973,017 out=113,176,626 elapsed=219.3s

  [14661/20519] intraday_4141.csv.gz  in=383,986,111 out=113,176,626 elapsed=219.4s

  [14662/20519] intraday_4143.csv.gz  in=383,998,371 out=113,176,626 elapsed=219.4s

  [14663/20519] intraday_4144.csv.gz  in=384,013,861 out=113,176,626 elapsed=219.4s

  [14664/20519] intraday_4142.csv.gz  in=384,026,509 out=113,176,626 elapsed=219.4s

  [14665/20519] intraday_4146.csv.gz  in=384,038,596 out=113,176,626 elapsed=219.4s

  [14666/20519] intraday_4145.csv.gz  in=384,053,208 out=113,176,626 elapsed=219.4s

  [14667/20519] intraday_4147.csv.gz  in=384,065,155 out=113,176,626 elapsed=219.4s

  [14668/20519] intraday_4148.csv.gz  in=384,078,322 out=113,176,626 elapsed=219.4s

  [14669/20519] intraday_4149.csv.gz  in=384,090,280 out=113,176,626 elapsed=219.4s

  [14670/20519] intraday_4150.csv.gz  in=384,103,266 out=113,176,626 elapsed=219.4s

  [14671/20519] intraday_4151.csv.gz  in=384,113,438 out=113,176,626 elapsed=219.5s

  [14672/20519] intraday_4153.csv.gz  in=384,125,722 out=113,176,626 elapsed=219.5s

  [14673/20519] intraday_4154.csv.gz  in=384,135,456 out=113,176,626 elapsed=219.5s

  [14674/20519] intraday_4155.csv.gz  in=384,149,953 out=113,176,626 elapsed=219.5s

  [14675/20519] intraday_4152.csv.gz  in=384,161,017 out=113,176,626 elapsed=219.5s

  [14676/20519] intraday_4156.csv.gz  in=384,173,890 out=113,176,626 elapsed=219.5s

  [14677/20519] intraday_4158.csv.gz  in=384,185,125 out=113,176,626 elapsed=219.5s

  [14678/20519] intraday_4159.csv.gz  in=384,196,718 out=113,176,626 elapsed=219.6s

  [14679/20519] intraday_4157.csv.gz  in=384,208,825 out=113,176,626 elapsed=219.6s

  [14680/20519] intraday_4160.csv.gz  in=384,221,703 out=113,176,626 elapsed=219.6s

  [14681/20519] intraday_4161.csv.gz  in=384,232,548 out=113,176,626 elapsed=219.6s

  [14682/20519] intraday_4162.csv.gz  in=384,244,510 out=113,176,626 elapsed=219.6s

  [14683/20519] intraday_4163.csv.gz  in=384,255,883 out=113,176,626 elapsed=219.6s

  [14684/20519] intraday_4164.csv.gz  in=384,266,609 out=113,176,626 elapsed=219.6s

  [14685/20519] intraday_4165.csv.gz  in=384,277,844 out=113,176,626 elapsed=219.6s

  [14686/20519] intraday_4166.csv.gz  in=384,289,213 out=113,176,626 elapsed=219.6s

  [14687/20519] intraday_4167.csv.gz  in=384,300,484 out=113,176,626 elapsed=219.6s

  [14688/20519] intraday_4168.csv.gz  in=384,313,820 out=113,176,626 elapsed=219.6s

  [14689/20519] intraday_4169.csv.gz  in=384,326,128 out=113,176,626 elapsed=219.6s

  [14690/20519] intraday_4170.csv.gz  in=384,336,700 out=113,176,626 elapsed=219.6s

  [14691/20519] intraday_4171.csv.gz  in=384,347,217 out=113,176,626 elapsed=219.7s

  [14692/20519] intraday_4172.csv.gz  in=384,360,678 out=113,176,626 elapsed=219.7s

  [14693/20519] intraday_4173.csv.gz  in=384,372,886 out=113,176,626 elapsed=219.7s

  [14694/20519] intraday_4174.csv.gz  in=384,384,200 out=113,176,626 elapsed=219.7s

  [14695/20519] intraday_4175.csv.gz  in=384,395,619 out=113,176,626 elapsed=219.7s

  [14696/20519] intraday_4177.csv.gz  in=384,407,367 out=113,176,626 elapsed=219.7s

  [14697/20519] intraday_4176.csv.gz  in=384,418,781 out=113,176,626 elapsed=219.7s

  [14698/20519] intraday_4178.csv.gz  in=384,434,168 out=113,176,626 elapsed=219.7s

  [14699/20519] intraday_4181.csv.gz  in=384,445,674 out=113,176,626 elapsed=219.7s

  [14700/20519] intraday_4179.csv.gz  in=384,458,734 out=113,176,626 elapsed=219.7s

  [14701/20519] intraday_4180.csv.gz  in=384,470,700 out=113,176,626 elapsed=219.7s

  [14702/20519] intraday_4182.csv.gz  in=384,483,007 out=113,176,626 elapsed=219.8s

  [14703/20519] intraday_4183.csv.gz  in=384,493,005 out=113,176,626 elapsed=219.8s

  [14704/20519] intraday_4185.csv.gz  in=384,504,479 out=113,176,626 elapsed=219.8s

  [14705/20519] intraday_4184.csv.gz  in=384,516,569 out=113,176,626 elapsed=219.8s

  [14706/20519] intraday_4189.csv.gz  in=384,526,776 out=113,176,626 elapsed=219.8s

  [14707/20519] intraday_4186.csv.gz  in=384,540,332 out=113,176,626 elapsed=219.8s

  [14708/20519] intraday_4187.csv.gz  in=384,550,116 out=113,176,626 elapsed=219.8s

  [14709/20519] intraday_4188.csv.gz  in=384,560,949 out=113,176,626 elapsed=219.8s

  [14710/20519] intraday_4190.csv.gz  in=384,575,238 out=113,176,626 elapsed=219.8s

  [14711/20519] intraday_4193.csv.gz  in=384,585,560 out=113,176,626 elapsed=219.9s

  [14712/20519] intraday_4191.csv.gz  in=384,597,366 out=113,176,626 elapsed=219.9s

  [14713/20519] intraday_4194.csv.gz  in=384,608,128 out=113,176,626 elapsed=219.9s

  [14714/20519] intraday_4192.csv.gz  in=384,621,344 out=113,176,626 elapsed=219.9s

  [14715/20519] intraday_4195.csv.gz  in=384,633,216 out=113,176,626 elapsed=219.9s

  [14716/20519] intraday_4196.csv.gz  in=384,649,623 out=113,176,626 elapsed=219.9s

  [14717/20519] intraday_4198.csv.gz  in=384,660,994 out=113,176,626 elapsed=219.9s

  [14718/20519] intraday_4197.csv.gz  in=384,672,515 out=113,176,626 elapsed=219.9s

  [14719/20519] intraday_4199.csv.gz  in=384,684,141 out=113,176,626 elapsed=219.9s

  [14720/20519] intraday_4200.csv.gz  in=384,694,820 out=113,176,626 elapsed=219.9s

  [14721/20519] intraday_4201.csv.gz  in=384,708,171 out=113,176,626 elapsed=219.9s

  [14722/20519] intraday_4202.csv.gz  in=384,723,218 out=113,176,626 elapsed=220.0s

  [14723/20519] intraday_4203.csv.gz  in=384,735,058 out=113,176,626 elapsed=220.0s

  [14724/20519] intraday_4205.csv.gz  in=384,748,222 out=113,176,626 elapsed=220.0s

  [14725/20519] intraday_4204.csv.gz  in=384,761,599 out=113,176,626 elapsed=220.0s

  [14726/20519] intraday_4206.csv.gz  in=384,775,018 out=113,176,626 elapsed=220.0s

  [14727/20519] intraday_4209.csv.gz  in=384,786,851 out=113,176,626 elapsed=220.0s

  [14728/20519] intraday_4207.csv.gz  in=384,809,314 out=113,176,626 elapsed=220.0s

  [14729/20519] intraday_4208.csv.gz  in=384,822,366 out=113,176,626 elapsed=220.0s

  [14730/20519] intraday_4210.csv.gz  in=384,833,307 out=113,176,626 elapsed=220.0s

  [14731/20519] intraday_4211.csv.gz  in=384,845,234 out=113,176,626 elapsed=220.1s

  [14732/20519] intraday_4212.csv.gz  in=384,857,002 out=113,176,626 elapsed=220.1s

  [14733/20519] intraday_4213.csv.gz  in=384,868,956 out=113,176,626 elapsed=220.1s

  [14734/20519] intraday_4216.csv.gz  in=384,880,937 out=113,176,626 elapsed=220.1s

  [14735/20519] intraday_4214.csv.gz  in=384,892,569 out=113,176,626 elapsed=220.1s

  [14736/20519] intraday_4215.csv.gz  in=384,905,855 out=113,176,626 elapsed=220.1s

  [14737/20519] intraday_4220.csv.gz  in=384,916,713 out=113,176,626 elapsed=220.1s

  [14738/20519] intraday_4219.csv.gz  in=384,927,792 out=113,176,626 elapsed=220.1s

  [14739/20519] intraday_4217.csv.gz  in=384,940,278 out=113,176,626 elapsed=220.1s

  [14740/20519] intraday_4218.csv.gz  in=384,955,680 out=113,176,626 elapsed=220.1s

  [14741/20519] intraday_4222.csv.gz  in=384,970,398 out=113,176,626 elapsed=220.2s

  [14742/20519] intraday_4221.csv.gz  in=384,984,873 out=113,176,626 elapsed=220.2s

  [14743/20519] intraday_4223.csv.gz  in=384,996,594 out=113,176,626 elapsed=220.2s

  [14744/20519] intraday_4224.csv.gz  in=385,009,578 out=113,176,626 elapsed=220.2s

  [14745/20519] intraday_4226.csv.gz  in=385,021,546 out=113,176,626 elapsed=220.2s

  [14746/20519] intraday_4225.csv.gz  in=385,034,934 out=113,176,626 elapsed=220.2s

  [14747/20519] intraday_4228.csv.gz  in=385,048,325 out=113,176,626 elapsed=220.2s

  [14748/20519] intraday_4227.csv.gz  in=385,063,838 out=113,176,626 elapsed=220.2s

  [14749/20519] intraday_4229.csv.gz  in=385,077,234 out=113,176,626 elapsed=220.2s

  [14750/20519] intraday_4232.csv.gz  in=385,089,378 out=113,176,626 elapsed=220.2s

  [14751/20519] intraday_4230.csv.gz  in=385,105,761 out=113,176,626 elapsed=220.2s

  [14752/20519] intraday_4231.csv.gz  in=385,118,442 out=113,176,626 elapsed=220.3s

  [14753/20519] intraday_4233.csv.gz  in=385,129,433 out=113,176,626 elapsed=220.3s

  [14754/20519] intraday_4234.csv.gz  in=385,140,805 out=113,176,626 elapsed=220.3s

  [14755/20519] intraday_4235.csv.gz  in=385,152,327 out=113,176,626 elapsed=220.3s

  [14756/20519] intraday_4236.csv.gz  in=385,165,343 out=113,176,626 elapsed=220.3s

  [14757/20519] intraday_4237.csv.gz  in=385,177,633 out=113,176,626 elapsed=220.3s

  [14758/20519] intraday_4238.csv.gz  in=385,193,182 out=113,176,626 elapsed=220.3s

  [14759/20519] intraday_4240.csv.gz  in=385,206,624 out=113,176,626 elapsed=220.3s

  [14760/20519] intraday_4239.csv.gz  in=385,219,421 out=113,176,626 elapsed=220.3s

  [14761/20519] intraday_4241.csv.gz  in=385,231,911 out=113,176,626 elapsed=220.3s

  [14762/20519] intraday_4242.csv.gz  in=385,245,387 out=113,176,626 elapsed=220.3s

  [14763/20519] intraday_4244.csv.gz  in=385,257,987 out=113,176,626 elapsed=220.4s

  [14764/20519] intraday_4245.csv.gz  in=385,272,361 out=113,176,626 elapsed=220.4s

  [14765/20519] intraday_4243.csv.gz  in=385,284,263 out=113,176,626 elapsed=220.4s

  [14766/20519] intraday_4246.csv.gz  in=385,298,377 out=113,176,626 elapsed=220.4s

  [14767/20519] intraday_4247.csv.gz  in=385,311,506 out=113,176,626 elapsed=220.4s

  [14768/20519] intraday_4249.csv.gz  in=385,321,812 out=113,176,626 elapsed=220.5s

  [14769/20519] intraday_4250.csv.gz  in=385,334,734 out=113,176,626 elapsed=220.5s

  [14770/20519] intraday_4248.csv.gz  in=385,346,635 out=113,176,626 elapsed=220.5s

  [14771/20519] intraday_4253.csv.gz  in=385,354,222 out=113,176,626 elapsed=220.5s

  [14772/20519] intraday_4251.csv.gz  in=385,365,629 out=113,176,626 elapsed=220.5s

  [14773/20519] intraday_4254.csv.gz  in=385,375,934 out=113,176,626 elapsed=220.5s

  [14774/20519] intraday_4252.csv.gz  in=385,388,401 out=113,176,626 elapsed=220.5s

  [14775/20519] intraday_4255.csv.gz  in=385,395,660 out=113,176,626 elapsed=220.6s

  [14776/20519] intraday_4257.csv.gz  in=385,409,679 out=113,176,626 elapsed=220.6s

  [14777/20519] intraday_4258.csv.gz  in=385,422,142 out=113,176,626 elapsed=220.6s

  [14778/20519] intraday_4256.csv.gz  in=385,437,925 out=113,176,626 elapsed=220.6s

  [14779/20519] intraday_4259.csv.gz  in=385,448,073 out=113,176,626 elapsed=220.6s

  [14780/20519] intraday_4261.csv.gz  in=385,462,472 out=113,176,626 elapsed=220.6s

  [14781/20519] intraday_4260.csv.gz  in=385,477,398 out=113,176,626 elapsed=220.6s

  [14782/20519] intraday_4262.csv.gz  in=385,489,918 out=113,176,626 elapsed=220.6s

  [14783/20519] intraday_4263.csv.gz  in=385,502,128 out=113,176,626 elapsed=220.6s

  [14784/20519] intraday_4264.csv.gz  in=385,516,613 out=113,176,626 elapsed=220.7s

  [14785/20519] intraday_4267.csv.gz  in=385,529,690 out=113,176,626 elapsed=220.7s

  [14786/20519] intraday_4266.csv.gz  in=385,540,878 out=113,176,626 elapsed=220.7s

  [14787/20519] intraday_4265.csv.gz  in=385,556,568 out=113,176,626 elapsed=220.7s

  [14788/20519] intraday_4268.csv.gz  in=385,568,929 out=113,176,626 elapsed=220.7s

  [14789/20519] intraday_4269.csv.gz  in=385,580,941 out=113,176,626 elapsed=220.7s

  [14790/20519] intraday_4270.csv.gz  in=385,592,203 out=113,176,626 elapsed=220.7s

  [14791/20519] intraday_4271.csv.gz  in=385,603,699 out=113,176,626 elapsed=220.7s

  [14792/20519] intraday_4273.csv.gz  in=385,616,884 out=113,176,626 elapsed=220.7s

  [14793/20519] intraday_4274.csv.gz  in=385,627,220 out=113,176,626 elapsed=220.7s

  [14794/20519] intraday_4272.csv.gz  in=385,641,609 out=113,176,626 elapsed=220.8s

  [14795/20519] intraday_4275.csv.gz  in=385,654,362 out=113,176,626 elapsed=220.8s

  [14796/20519] intraday_4277.csv.gz  in=385,667,279 out=113,176,626 elapsed=220.8s

  [14797/20519] intraday_4276.csv.gz  in=385,681,393 out=113,176,626 elapsed=220.8s

  [14798/20519] intraday_4278.csv.gz  in=385,693,552 out=113,176,626 elapsed=220.8s

  [14799/20519] intraday_4279.csv.gz  in=385,706,235 out=113,176,626 elapsed=220.8s

  [14800/20519] intraday_4280.csv.gz  in=385,718,611 out=113,176,626 elapsed=220.8s

  [14801/20519] intraday_4282.csv.gz  in=385,732,121 out=113,176,626 elapsed=220.8s

  [14802/20519] intraday_4281.csv.gz  in=385,743,302 out=113,176,626 elapsed=220.8s

  [14803/20519] intraday_4283.csv.gz  in=385,756,392 out=113,176,626 elapsed=220.8s

  [14804/20519] intraday_4284.csv.gz  in=385,770,370 out=113,176,626 elapsed=220.8s

  [14805/20519] intraday_4285.csv.gz  in=385,784,760 out=113,176,626 elapsed=220.9s

  [14806/20519] intraday_4286.csv.gz  in=385,798,644 out=113,176,626 elapsed=220.9s

  [14807/20519] intraday_4287.csv.gz  in=385,809,731 out=113,176,626 elapsed=220.9s

  [14808/20519] intraday_4288.csv.gz  in=385,821,978 out=113,176,626 elapsed=220.9s

  [14809/20519] intraday_4290.csv.gz  in=385,833,840 out=113,176,626 elapsed=220.9s

  [14810/20519] intraday_4289.csv.gz  in=385,847,056 out=113,176,626 elapsed=220.9s

  [14811/20519] intraday_4291.csv.gz  in=385,859,182 out=113,176,626 elapsed=220.9s

  [14812/20519] intraday_4292.csv.gz  in=385,870,812 out=113,176,626 elapsed=220.9s

  [14813/20519] intraday_4293.csv.gz  in=385,884,070 out=113,176,626 elapsed=220.9s

  [14814/20519] intraday_4295.csv.gz  in=385,895,585 out=113,176,626 elapsed=220.9s

  [14815/20519] intraday_4294.csv.gz  in=385,907,196 out=113,176,626 elapsed=221.0s

  [14816/20519] intraday_4298.csv.gz  in=385,920,744 out=113,176,626 elapsed=221.0s

  [14817/20519] intraday_4296.csv.gz  in=385,934,341 out=113,176,626 elapsed=221.0s

  [14818/20519] intraday_4297.csv.gz  in=385,945,509 out=113,176,626 elapsed=221.0s

  [14819/20519] intraday_4299.csv.gz  in=385,956,818 out=113,176,626 elapsed=221.0s

  [14820/20519] intraday_4300.csv.gz  in=385,969,520 out=113,176,626 elapsed=221.0s

  [14821/20519] intraday_4302.csv.gz  in=385,980,722 out=113,176,626 elapsed=221.0s

  [14822/20519] intraday_4301.csv.gz  in=385,993,329 out=113,176,626 elapsed=221.0s

  [14823/20519] intraday_4303.csv.gz  in=386,005,826 out=113,176,626 elapsed=221.0s

  [14824/20519] intraday_4306.csv.gz  in=386,019,511 out=113,176,626 elapsed=221.1s

  [14825/20519] intraday_4305.csv.gz  in=386,029,039 out=113,176,626 elapsed=221.1s

  [14826/20519] intraday_4307.csv.gz  in=386,040,283 out=113,176,626 elapsed=221.1s

  [14827/20519] intraday_4304.csv.gz  in=386,051,553 out=113,176,626 elapsed=221.1s

  [14828/20519] intraday_4308.csv.gz  in=386,062,869 out=113,176,626 elapsed=221.1s

  [14829/20519] intraday_4310.csv.gz  in=386,075,307 out=113,176,626 elapsed=221.1s

  [14830/20519] intraday_4309.csv.gz  in=386,088,316 out=113,176,626 elapsed=221.1s

  [14831/20519] intraday_4311.csv.gz  in=386,099,230 out=113,176,626 elapsed=221.1s

  [14832/20519] intraday_4312.csv.gz  in=386,109,939 out=113,176,626 elapsed=221.1s

  [14833/20519] intraday_4314.csv.gz  in=386,122,287 out=113,176,626 elapsed=221.1s

  [14834/20519] intraday_4313.csv.gz  in=386,136,595 out=113,176,626 elapsed=221.2s

  [14835/20519] intraday_4315.csv.gz  in=386,148,861 out=113,176,626 elapsed=221.2s

  [14836/20519] intraday_4316.csv.gz  in=386,159,797 out=113,176,626 elapsed=221.2s

  [14837/20519] intraday_4318.csv.gz  in=386,170,995 out=113,176,626 elapsed=221.2s

  [14838/20519] intraday_4317.csv.gz  in=386,182,887 out=113,176,626 elapsed=221.2s

  [14839/20519] intraday_4319.csv.gz  in=386,197,387 out=113,176,626 elapsed=221.2s

  [14840/20519] intraday_4320.csv.gz  in=386,210,000 out=113,176,626 elapsed=221.2s

  [14841/20519] intraday_4322.csv.gz  in=386,222,420 out=113,176,626 elapsed=221.2s

  [14842/20519] intraday_4321.csv.gz  in=386,235,600 out=113,176,626 elapsed=221.2s

  [14843/20519] intraday_4323.csv.gz  in=386,252,278 out=113,176,626 elapsed=221.2s

  [14844/20519] intraday_4324.csv.gz  in=386,263,413 out=113,176,626 elapsed=221.3s

  [14845/20519] intraday_4326.csv.gz  in=386,274,247 out=113,176,626 elapsed=221.3s

  [14846/20519] intraday_4328.csv.gz  in=386,285,141 out=113,176,626 elapsed=221.3s

  [14847/20519] intraday_4327.csv.gz  in=386,298,813 out=113,176,626 elapsed=221.3s

  [14848/20519] intraday_4325.csv.gz  in=386,310,332 out=113,176,626 elapsed=221.3s

  [14849/20519] intraday_4330.csv.gz  in=386,322,631 out=113,176,626 elapsed=221.3s

  [14850/20519] intraday_4329.csv.gz  in=386,333,121 out=113,176,626 elapsed=221.3s

  [14851/20519] intraday_4332.csv.gz  in=386,344,182 out=113,176,626 elapsed=221.3s

  [14852/20519] intraday_4331.csv.gz  in=386,358,146 out=113,176,626 elapsed=221.3s

  [14853/20519] intraday_4334.csv.gz  in=386,368,617 out=113,176,626 elapsed=221.4s

  [14854/20519] intraday_4333.csv.gz  in=386,380,530 out=113,176,626 elapsed=221.4s

  [14855/20519] intraday_4336.csv.gz  in=386,393,587 out=113,176,626 elapsed=221.4s

  [14856/20519] intraday_4335.csv.gz  in=386,405,725 out=113,176,626 elapsed=221.4s

  [14857/20519] intraday_4338.csv.gz  in=386,417,033 out=113,176,626 elapsed=221.4s

  [14858/20519] intraday_4337.csv.gz  in=386,432,140 out=113,176,626 elapsed=221.4s

  [14859/20519] intraday_4339.csv.gz  in=386,443,027 out=113,176,626 elapsed=221.4s

  [14860/20519] intraday_4340.csv.gz  in=386,453,769 out=113,176,626 elapsed=221.4s

  [14861/20519] intraday_4341.csv.gz  in=386,466,907 out=113,176,626 elapsed=221.4s

  [14862/20519] intraday_4342.csv.gz  in=386,479,947 out=113,176,626 elapsed=221.5s

  [14863/20519] intraday_4343.csv.gz  in=386,495,003 out=113,176,626 elapsed=221.5s

  [14864/20519] intraday_4344.csv.gz  in=386,505,972 out=113,176,626 elapsed=221.5s

  [14865/20519] intraday_4345.csv.gz  in=386,520,070 out=113,176,626 elapsed=221.5s

  [14866/20519] intraday_4347.csv.gz  in=386,534,651 out=113,176,626 elapsed=221.5s

  [14867/20519] intraday_4348.csv.gz  in=386,549,795 out=113,176,626 elapsed=221.5s

  [14868/20519] intraday_4349.csv.gz  in=386,562,530 out=113,176,626 elapsed=221.5s

  [14869/20519] intraday_4346.csv.gz  in=386,576,207 out=113,176,626 elapsed=221.5s

  [14870/20519] intraday_4350.csv.gz  in=386,587,729 out=113,176,626 elapsed=221.6s

  [14871/20519] intraday_4351.csv.gz  in=386,600,288 out=113,176,626 elapsed=221.6s

  [14872/20519] intraday_4352.csv.gz  in=386,611,102 out=113,176,626 elapsed=221.6s

  [14873/20519] intraday_4353.csv.gz  in=386,622,143 out=113,176,626 elapsed=221.6s

  [14874/20519] intraday_4354.csv.gz  in=386,633,882 out=113,176,626 elapsed=221.6s

  [14875/20519] intraday_4355.csv.gz  in=386,646,943 out=113,176,626 elapsed=221.6s

  [14876/20519] intraday_4357.csv.gz  in=386,659,016 out=113,176,626 elapsed=221.6s

  [14877/20519] intraday_4356.csv.gz  in=386,671,807 out=113,176,626 elapsed=221.6s

  [14878/20519] intraday_4359.csv.gz  in=386,685,151 out=113,176,626 elapsed=221.7s

  [14879/20519] intraday_4358.csv.gz  in=386,697,839 out=113,176,626 elapsed=221.7s

  [14880/20519] intraday_4360.csv.gz  in=386,710,504 out=113,176,626 elapsed=221.7s

  [14881/20519] intraday_4361.csv.gz  in=386,723,410 out=113,176,626 elapsed=221.7s

  [14882/20519] intraday_4362.csv.gz  in=386,736,283 out=113,176,626 elapsed=221.7s

  [14883/20519] intraday_4363.csv.gz  in=386,750,241 out=113,176,626 elapsed=221.7s

  [14884/20519] intraday_4364.csv.gz  in=386,761,811 out=113,176,626 elapsed=221.7s

  [14885/20519] intraday_4367.csv.gz  in=386,775,356 out=113,176,626 elapsed=221.7s

  [14886/20519] intraday_4366.csv.gz  in=386,787,792 out=113,176,626 elapsed=221.7s

  [14887/20519] intraday_4365.csv.gz  in=386,803,031 out=113,176,626 elapsed=221.7s

  [14888/20519] intraday_4368.csv.gz  in=386,816,658 out=113,176,626 elapsed=221.7s

  [14889/20519] intraday_4369.csv.gz  in=386,830,916 out=113,176,626 elapsed=221.8s

  [14890/20519] intraday_4370.csv.gz  in=386,844,912 out=113,176,626 elapsed=221.8s

  [14891/20519] intraday_4371.csv.gz  in=386,860,411 out=113,176,626 elapsed=221.8s

  [14892/20519] intraday_4372.csv.gz  in=386,880,862 out=113,176,626 elapsed=221.8s

  [14893/20519] intraday_4373.csv.gz  in=386,892,658 out=113,176,626 elapsed=221.8s

  [14894/20519] intraday_4374.csv.gz  in=386,903,208 out=113,176,626 elapsed=221.8s

  [14895/20519] intraday_4375.csv.gz  in=386,917,067 out=113,176,626 elapsed=221.8s

  [14896/20519] intraday_4376.csv.gz  in=386,926,698 out=113,176,626 elapsed=221.8s

  [14897/20519] intraday_4377.csv.gz  in=386,940,039 out=113,176,626 elapsed=221.8s

  [14898/20519] intraday_4378.csv.gz  in=386,952,941 out=113,176,626 elapsed=221.8s

  [14899/20519] intraday_4379.csv.gz  in=386,967,729 out=113,176,626 elapsed=221.8s

  [14900/20519] intraday_4381.csv.gz  in=386,980,580 out=113,176,626 elapsed=221.9s

  [14901/20519] intraday_4380.csv.gz  in=386,992,634 out=113,176,626 elapsed=221.9s

  [14902/20519] intraday_4382.csv.gz  in=387,005,946 out=113,176,626 elapsed=221.9s

  [14903/20519] intraday_4383.csv.gz  in=387,019,157 out=113,176,626 elapsed=221.9s

  [14904/20519] intraday_4385.csv.gz  in=387,033,579 out=113,176,626 elapsed=221.9s

  [14905/20519] intraday_4384.csv.gz  in=387,045,461 out=113,176,626 elapsed=221.9s

  [14906/20519] intraday_4387.csv.gz  in=387,057,817 out=113,176,626 elapsed=221.9s

  [14907/20519] intraday_4388.csv.gz  in=387,072,070 out=113,176,626 elapsed=221.9s

  [14908/20519] intraday_4386.csv.gz  in=387,087,052 out=113,176,626 elapsed=222.0s

  [14909/20519] intraday_4389.csv.gz  in=387,098,094 out=113,176,626 elapsed=222.0s

  [14910/20519] intraday_4390.csv.gz  in=387,109,337 out=113,176,626 elapsed=222.0s

  [14911/20519] intraday_4393.csv.gz  in=387,118,215 out=113,176,626 elapsed=222.0s

  [14912/20519] intraday_4391.csv.gz  in=387,131,040 out=113,176,626 elapsed=222.0s

  [14913/20519] intraday_4392.csv.gz  in=387,144,092 out=113,176,626 elapsed=222.0s

  [14914/20519] intraday_4394.csv.gz  in=387,152,393 out=113,176,626 elapsed=222.0s

  [14915/20519] intraday_4396.csv.gz  in=387,153,715 out=113,176,626 elapsed=222.0s

  [14916/20519] intraday_4397.csv.gz  in=387,168,629 out=113,176,626 elapsed=222.0s

  [14917/20519] intraday_4395.csv.gz  in=387,180,426 out=113,176,626 elapsed=222.0s

  [14918/20519] intraday_4400.csv.gz  in=387,191,117 out=113,176,626 elapsed=222.0s

  [14919/20519] intraday_4398.csv.gz  in=387,205,966 out=113,176,626 elapsed=222.0s

  [14920/20519] intraday_4399.csv.gz  in=387,218,631 out=113,176,626 elapsed=222.1s

  [14921/20519] intraday_4401.csv.gz  in=387,233,816 out=113,176,626 elapsed=222.1s

  [14922/20519] intraday_4403.csv.gz  in=387,246,469 out=113,176,626 elapsed=222.1s

  [14923/20519] intraday_4402.csv.gz  in=387,261,178 out=113,176,626 elapsed=222.1s

  [14924/20519] intraday_4405.csv.gz  in=387,274,932 out=113,176,626 elapsed=222.1s

  [14925/20519] intraday_4404.csv.gz  in=387,286,186 out=113,176,626 elapsed=222.1s

  [14926/20519] intraday_4407.csv.gz  in=387,296,149 out=113,176,626 elapsed=222.1s

  [14927/20519] intraday_4406.csv.gz  in=387,311,832 out=113,176,626 elapsed=222.1s

  [14928/20519] intraday_4409.csv.gz  in=387,326,049 out=113,176,626 elapsed=222.1s

  [14929/20519] intraday_4408.csv.gz  in=387,338,749 out=113,176,626 elapsed=222.1s

  [14930/20519] intraday_4411.csv.gz  in=387,349,689 out=113,176,626 elapsed=222.2s

  [14931/20519] intraday_4410.csv.gz  in=387,362,459 out=113,176,626 elapsed=222.2s

  [14932/20519] intraday_4412.csv.gz  in=387,373,903 out=113,176,626 elapsed=222.2s

  [14933/20519] intraday_4413.csv.gz  in=387,387,156 out=113,176,626 elapsed=222.2s

  [14934/20519] intraday_4414.csv.gz  in=387,400,215 out=113,176,626 elapsed=222.2s

  [14935/20519] intraday_4415.csv.gz  in=387,411,391 out=113,176,626 elapsed=222.2s

  [14936/20519] intraday_4416.csv.gz  in=387,424,689 out=113,176,626 elapsed=222.2s

  [14937/20519] intraday_4418.csv.gz  in=387,436,803 out=113,176,626 elapsed=222.2s

  [14938/20519] intraday_4417.csv.gz  in=387,450,262 out=113,176,626 elapsed=222.2s

  [14939/20519] intraday_4421.csv.gz  in=387,462,228 out=113,176,626 elapsed=222.2s

  [14940/20519] intraday_4419.csv.gz  in=387,473,862 out=113,176,626 elapsed=222.3s

  [14941/20519] intraday_4420.csv.gz  in=387,486,562 out=113,176,626 elapsed=222.3s

  [14942/20519] intraday_4422.csv.gz  in=387,496,892 out=113,176,626 elapsed=222.3s

  [14943/20519] intraday_4423.csv.gz  in=387,509,807 out=113,176,626 elapsed=222.3s

  [14944/20519] intraday_4424.csv.gz  in=387,522,190 out=113,176,626 elapsed=222.3s

  [14945/20519] intraday_4426.csv.gz  in=387,537,689 out=113,176,626 elapsed=222.3s

  [14946/20519] intraday_4425.csv.gz  in=387,551,938 out=113,176,626 elapsed=222.3s

  [14947/20519] intraday_4428.csv.gz  in=387,563,512 out=113,176,626 elapsed=222.3s

  [14948/20519] intraday_4429.csv.gz  in=387,575,677 out=113,176,626 elapsed=222.3s

  [14949/20519] intraday_4427.csv.gz  in=387,589,345 out=113,176,626 elapsed=222.3s

  [14950/20519] intraday_4430.csv.gz  in=387,602,466 out=113,176,626 elapsed=222.4s

  [14951/20519] intraday_4433.csv.gz  in=387,613,310 out=113,176,626 elapsed=222.4s

  [14952/20519] intraday_4431.csv.gz  in=387,624,755 out=113,176,626 elapsed=222.4s

  [14953/20519] intraday_4434.csv.gz  in=387,635,715 out=113,176,626 elapsed=222.4s

  [14954/20519] intraday_4432.csv.gz  in=387,647,768 out=113,176,626 elapsed=222.4s

  [14955/20519] intraday_4435.csv.gz  in=387,658,672 out=113,176,626 elapsed=222.5s

  [14956/20519] intraday_4438.csv.gz  in=387,670,277 out=113,176,626 elapsed=222.5s

  [14957/20519] intraday_4437.csv.gz  in=387,688,890 out=113,176,626 elapsed=222.5s

  [14958/20519] intraday_4436.csv.gz  in=387,701,149 out=113,176,626 elapsed=222.5s

  [14959/20519] intraday_4440.csv.gz  in=387,712,122 out=113,176,626 elapsed=222.5s

  [14960/20519] intraday_4441.csv.gz  in=387,723,995 out=113,176,626 elapsed=222.5s

  [14961/20519] intraday_4439.csv.gz  in=387,737,083 out=113,176,626 elapsed=222.5s

  [14962/20519] intraday_4442.csv.gz  in=387,749,804 out=113,176,626 elapsed=222.5s

  [14963/20519] intraday_4443.csv.gz  in=387,760,806 out=113,176,626 elapsed=222.5s

  [14964/20519] intraday_4444.csv.gz  in=387,773,196 out=113,176,626 elapsed=222.6s

  [14965/20519] intraday_4446.csv.gz  in=387,783,133 out=113,176,626 elapsed=222.6s

  [14966/20519] intraday_4445.csv.gz  in=387,797,011 out=113,176,626 elapsed=222.6s

  [14967/20519] intraday_4447.csv.gz  in=387,810,213 out=113,176,626 elapsed=222.6s

  [14968/20519] intraday_4448.csv.gz  in=387,821,123 out=113,176,626 elapsed=222.6s

  [14969/20519] intraday_4449.csv.gz  in=387,832,182 out=113,176,626 elapsed=222.6s

  [14970/20519] intraday_4450.csv.gz  in=387,845,253 out=113,176,626 elapsed=222.6s

  [14971/20519] intraday_4451.csv.gz  in=387,858,118 out=113,176,626 elapsed=222.7s

  [14972/20519] intraday_4452.csv.gz  in=387,869,672 out=113,176,626 elapsed=222.7s

  [14973/20519] intraday_4454.csv.gz  in=387,883,266 out=113,176,626 elapsed=222.7s

  [14974/20519] intraday_4453.csv.gz  in=387,893,391 out=113,176,626 elapsed=222.7s

  [14975/20519] intraday_4456.csv.gz  in=387,905,472 out=113,176,626 elapsed=222.7s

  [14976/20519] intraday_4458.csv.gz  in=387,917,276 out=113,176,626 elapsed=222.7s

  [14977/20519] intraday_4455.csv.gz  in=387,929,131 out=113,176,626 elapsed=222.7s

  [14978/20519] intraday_4457.csv.gz  in=387,939,896 out=113,176,626 elapsed=222.7s

  [14979/20519] intraday_4460.csv.gz  in=387,953,711 out=113,176,626 elapsed=222.7s

  [14980/20519] intraday_4461.csv.gz  in=387,966,567 out=113,176,626 elapsed=222.7s

  [14981/20519] intraday_4459.csv.gz  in=387,977,659 out=113,176,626 elapsed=222.7s

  [14982/20519] intraday_4462.csv.gz  in=387,991,010 out=113,176,626 elapsed=222.8s

  [14983/20519] intraday_4463.csv.gz  in=388,003,238 out=113,176,626 elapsed=222.8s

  [14984/20519] intraday_4464.csv.gz  in=388,014,047 out=113,176,626 elapsed=222.8s

  [14985/20519] intraday_4465.csv.gz  in=388,025,506 out=113,176,626 elapsed=222.8s

  [14986/20519] intraday_4467.csv.gz  in=388,036,873 out=113,176,626 elapsed=222.8s

  [14987/20519] intraday_4466.csv.gz  in=388,048,446 out=113,176,626 elapsed=222.8s

  [14988/20519] intraday_4469.csv.gz  in=388,059,381 out=113,176,626 elapsed=222.8s

  [14989/20519] intraday_4468.csv.gz  in=388,072,422 out=113,176,626 elapsed=222.8s

  [14990/20519] intraday_4471.csv.gz  in=388,084,594 out=113,176,626 elapsed=222.8s

  [14991/20519] intraday_4470.csv.gz  in=388,094,544 out=113,176,626 elapsed=222.8s

  [14992/20519] intraday_4472.csv.gz  in=388,109,631 out=113,176,626 elapsed=222.8s

  [14993/20519] intraday_4473.csv.gz  in=388,120,132 out=113,176,626 elapsed=222.9s

  [14994/20519] intraday_4474.csv.gz  in=388,132,162 out=113,176,626 elapsed=222.9s

  [14995/20519] intraday_4475.csv.gz  in=388,142,165 out=113,176,626 elapsed=222.9s

  [14996/20519] intraday_4476.csv.gz  in=388,153,522 out=113,176,626 elapsed=222.9s

  [14997/20519] intraday_4477.csv.gz  in=388,166,802 out=113,176,626 elapsed=222.9s

  [14998/20519] intraday_4479.csv.gz  in=388,178,055 out=113,176,626 elapsed=222.9s

  [14999/20519] intraday_4478.csv.gz  in=388,193,323 out=113,176,626 elapsed=222.9s

  [15000/20519] intraday_4480.csv.gz  in=388,204,391 out=113,176,626 elapsed=222.9s

  [15001/20519] intraday_4482.csv.gz  in=388,217,708 out=113,176,626 elapsed=222.9s

  [15002/20519] intraday_4483.csv.gz  in=388,230,983 out=113,176,626 elapsed=222.9s

  [15003/20519] intraday_4481.csv.gz  in=388,249,620 out=113,176,626 elapsed=223.0s

  [15004/20519] intraday_4484.csv.gz  in=388,264,568 out=113,176,626 elapsed=223.0s

  [15005/20519] intraday_4485.csv.gz  in=388,275,113 out=113,176,626 elapsed=223.0s

  [15006/20519] intraday_4486.csv.gz  in=388,289,731 out=113,176,626 elapsed=223.0s

  [15007/20519] intraday_4487.csv.gz  in=388,302,771 out=113,176,626 elapsed=223.0s

  [15008/20519] intraday_4488.csv.gz  in=388,317,366 out=113,176,626 elapsed=223.0s

  [15009/20519] intraday_4490.csv.gz  in=388,329,631 out=113,176,626 elapsed=223.0s

  [15010/20519] intraday_4489.csv.gz  in=388,342,650 out=113,176,626 elapsed=223.0s

  [15011/20519] intraday_4491.csv.gz  in=388,354,138 out=113,176,626 elapsed=223.0s

  [15012/20519] intraday_4492.csv.gz  in=388,365,888 out=113,176,626 elapsed=223.0s

  [15013/20519] intraday_4494.csv.gz  in=388,376,883 out=113,176,626 elapsed=223.0s

  [15014/20519] intraday_4493.csv.gz  in=388,388,158 out=113,176,626 elapsed=223.1s

  [15015/20519] intraday_4495.csv.gz  in=388,400,161 out=113,176,626 elapsed=223.1s

  [15016/20519] intraday_4496.csv.gz  in=388,411,297 out=113,176,626 elapsed=223.1s

  [15017/20519] intraday_4498.csv.gz  in=388,423,368 out=113,176,626 elapsed=223.1s

  [15018/20519] intraday_4497.csv.gz  in=388,436,574 out=113,176,626 elapsed=223.1s

  [15019/20519] intraday_4500.csv.gz  in=388,449,571 out=113,176,626 elapsed=223.1s

  [15020/20519] intraday_4499.csv.gz  in=388,462,320 out=113,176,626 elapsed=223.1s

  [15021/20519] intraday_4501.csv.gz  in=388,475,407 out=113,176,626 elapsed=223.1s

  [15022/20519] intraday_4503.csv.gz  in=388,488,500 out=113,176,626 elapsed=223.1s

  [15023/20519] intraday_4502.csv.gz  in=388,506,006 out=113,176,626 elapsed=223.1s

  [15024/20519] intraday_4505.csv.gz  in=388,516,581 out=113,176,626 elapsed=223.2s

  [15025/20519] intraday_4504.csv.gz  in=388,530,711 out=113,176,626 elapsed=223.2s

  [15026/20519] intraday_4506.csv.gz  in=388,545,521 out=113,176,626 elapsed=223.2s

  [15027/20519] intraday_4507.csv.gz  in=388,557,541 out=113,176,626 elapsed=223.2s

  [15028/20519] intraday_4509.csv.gz  in=388,571,193 out=113,176,626 elapsed=223.2s

  [15029/20519] intraday_4508.csv.gz  in=388,584,987 out=113,176,626 elapsed=223.2s

  [15030/20519] intraday_4510.csv.gz  in=388,599,172 out=113,176,626 elapsed=223.2s

  [15031/20519] intraday_4511.csv.gz  in=388,611,835 out=113,176,626 elapsed=223.2s

  [15032/20519] intraday_4512.csv.gz  in=388,627,674 out=113,176,626 elapsed=223.2s

  [15033/20519] intraday_4513.csv.gz  in=388,640,432 out=113,176,626 elapsed=223.2s

  [15034/20519] intraday_4514.csv.gz  in=388,651,980 out=113,176,626 elapsed=223.3s

  [15035/20519] intraday_4518.csv.gz  in=388,666,084 out=113,176,626 elapsed=223.3s

  [15036/20519] intraday_4515.csv.gz  in=388,677,348 out=113,176,626 elapsed=223.3s

  [15037/20519] intraday_4517.csv.gz  in=388,687,347 out=113,176,626 elapsed=223.3s

  [15038/20519] intraday_4516.csv.gz  in=388,701,551 out=113,176,626 elapsed=223.3s

  [15039/20519] intraday_4519.csv.gz  in=388,715,477 out=113,176,626 elapsed=223.3s

  [15040/20519] intraday_4521.csv.gz  in=388,726,484 out=113,176,626 elapsed=223.3s

  [15041/20519] intraday_4522.csv.gz  in=388,739,336 out=113,176,626 elapsed=223.3s

  [15042/20519] intraday_4520.csv.gz  in=388,756,028 out=113,176,626 elapsed=223.3s

  [15043/20519] intraday_4523.csv.gz  in=388,769,259 out=113,176,626 elapsed=223.3s

  [15044/20519] intraday_4524.csv.gz  in=388,781,243 out=113,176,626 elapsed=223.3s

  [15045/20519] intraday_4525.csv.gz  in=388,792,991 out=113,176,626 elapsed=223.3s

  [15046/20519] intraday_4526.csv.gz  in=388,807,430 out=113,176,626 elapsed=223.3s

  [15047/20519] intraday_4527.csv.gz  in=388,822,601 out=113,176,626 elapsed=223.3s

  [15048/20519] intraday_4528.csv.gz  in=388,835,145 out=113,176,626 elapsed=223.3s

  [15049/20519] intraday_4529.csv.gz  in=388,848,899 out=113,176,626 elapsed=223.4s

  [15050/20519] intraday_4531.csv.gz  in=388,860,104 out=113,176,626 elapsed=223.4s

  [15051/20519] intraday_4530.csv.gz  in=388,871,304 out=113,176,626 elapsed=223.4s

  [15052/20519] intraday_4532.csv.gz  in=388,883,632 out=113,176,626 elapsed=223.4s

  [15053/20519] intraday_4533.csv.gz  in=388,896,382 out=113,176,626 elapsed=223.4s

  [15054/20519] intraday_4535.csv.gz  in=388,905,241 out=113,176,626 elapsed=223.4s

  [15055/20519] intraday_4534.csv.gz  in=388,914,219 out=113,176,626 elapsed=223.4s

  [15056/20519] intraday_4537.csv.gz  in=388,914,528 out=113,176,626 elapsed=223.4s

  [15057/20519] intraday_4536.csv.gz  in=388,926,343 out=113,176,626 elapsed=223.4s

  [15058/20519] intraday_4539.csv.gz  in=388,940,232 out=113,176,626 elapsed=223.4s

  [15059/20519] intraday_4538.csv.gz  in=388,955,419 out=113,176,626 elapsed=223.5s

  [15060/20519] intraday_4541.csv.gz  in=388,965,965 out=113,176,626 elapsed=223.5s

  [15061/20519] intraday_4540.csv.gz  in=388,978,348 out=113,176,626 elapsed=223.5s

  [15062/20519] intraday_4542.csv.gz  in=388,993,548 out=113,176,626 elapsed=223.5s

  [15063/20519] intraday_4545.csv.gz  in=389,006,282 out=113,176,626 elapsed=223.5s

  [15064/20519] intraday_4544.csv.gz  in=389,020,254 out=113,176,626 elapsed=223.5s

  [15065/20519] intraday_4546.csv.gz  in=389,033,766 out=113,176,626 elapsed=223.5s

  [15066/20519] intraday_4543.csv.gz  in=389,055,527 out=113,176,626 elapsed=223.6s

  [15067/20519] intraday_4548.csv.gz  in=389,066,013 out=113,176,626 elapsed=223.6s

  [15068/20519] intraday_4547.csv.gz  in=389,081,147 out=113,176,626 elapsed=223.6s

  [15069/20519] intraday_4549.csv.gz  in=389,093,746 out=113,176,626 elapsed=223.6s

  [15070/20519] intraday_4551.csv.gz  in=389,104,931 out=113,176,626 elapsed=223.6s

  [15071/20519] intraday_4552.csv.gz  in=389,115,710 out=113,176,626 elapsed=223.6s

  [15072/20519] intraday_4550.csv.gz  in=389,128,287 out=113,176,626 elapsed=223.6s

  [15073/20519] intraday_4553.csv.gz  in=389,139,256 out=113,176,626 elapsed=223.6s

  [15074/20519] intraday_4555.csv.gz  in=389,151,970 out=113,176,626 elapsed=223.6s

  [15075/20519] intraday_4556.csv.gz  in=389,162,678 out=113,176,626 elapsed=223.6s

  [15076/20519] intraday_4554.csv.gz  in=389,175,809 out=113,176,626 elapsed=223.6s

  [15077/20519] intraday_4557.csv.gz  in=389,188,158 out=113,176,626 elapsed=223.7s

  [15078/20519] intraday_4559.csv.gz  in=389,201,289 out=113,176,626 elapsed=223.7s

  [15079/20519] intraday_4558.csv.gz  in=389,214,558 out=113,176,626 elapsed=223.7s

  [15080/20519] intraday_4560.csv.gz  in=389,226,839 out=113,176,626 elapsed=223.7s

  [15081/20519] intraday_4561.csv.gz  in=389,241,335 out=113,176,626 elapsed=223.7s

  [15082/20519] intraday_4563.csv.gz  in=389,252,101 out=113,176,626 elapsed=223.7s

  [15083/20519] intraday_4562.csv.gz  in=389,263,468 out=113,176,626 elapsed=223.7s

  [15084/20519] intraday_4564.csv.gz  in=389,275,875 out=113,176,626 elapsed=223.7s

  [15085/20519] intraday_4565.csv.gz  in=389,288,310 out=113,176,626 elapsed=223.7s

  [15086/20519] intraday_4566.csv.gz  in=389,302,654 out=113,176,626 elapsed=223.7s

  [15087/20519] intraday_4567.csv.gz  in=389,317,608 out=113,176,626 elapsed=223.8s

  [15088/20519] intraday_4568.csv.gz  in=389,330,567 out=113,176,626 elapsed=223.8s

  [15089/20519] intraday_4569.csv.gz  in=389,342,030 out=113,176,626 elapsed=223.8s

  [15090/20519] intraday_4571.csv.gz  in=389,355,904 out=113,176,626 elapsed=223.8s

  [15091/20519] intraday_4570.csv.gz  in=389,367,389 out=113,176,626 elapsed=223.8s

  [15092/20519] intraday_4572.csv.gz  in=389,377,972 out=113,176,626 elapsed=223.8s

  [15093/20519] intraday_4573.csv.gz  in=389,390,917 out=113,176,626 elapsed=223.8s

  [15094/20519] intraday_4574.csv.gz  in=389,401,786 out=113,176,626 elapsed=223.8s

  [15095/20519] intraday_4575.csv.gz  in=389,412,359 out=113,176,626 elapsed=223.8s

  [15096/20519] intraday_4577.csv.gz  in=389,424,417 out=113,176,626 elapsed=223.8s

  [15097/20519] intraday_4576.csv.gz  in=389,436,235 out=113,176,626 elapsed=223.8s

  [15098/20519] intraday_4578.csv.gz  in=389,448,256 out=113,176,626 elapsed=223.9s

  [15099/20519] intraday_4579.csv.gz  in=389,461,141 out=113,176,626 elapsed=223.9s

  [15100/20519] intraday_4581.csv.gz  in=389,472,024 out=113,176,626 elapsed=223.9s

  [15101/20519] intraday_4580.csv.gz  in=389,485,889 out=113,176,626 elapsed=223.9s

  [15102/20519] intraday_4584.csv.gz  in=389,497,041 out=113,176,626 elapsed=223.9s

  [15103/20519] intraday_4582.csv.gz  in=389,511,000 out=113,176,626 elapsed=223.9s

  [15104/20519] intraday_4583.csv.gz  in=389,522,705 out=113,176,626 elapsed=223.9s

  [15105/20519] intraday_4585.csv.gz  in=389,534,789 out=113,176,626 elapsed=223.9s

  [15106/20519] intraday_4587.csv.gz  in=389,544,397 out=113,176,626 elapsed=223.9s

  [15107/20519] intraday_4586.csv.gz  in=389,555,517 out=113,176,626 elapsed=224.0s

  [15108/20519] intraday_4588.csv.gz  in=389,569,611 out=113,176,626 elapsed=224.0s

  [15109/20519] intraday_4589.csv.gz  in=389,579,435 out=113,176,626 elapsed=224.0s

  [15110/20519] intraday_4590.csv.gz  in=389,591,196 out=113,176,626 elapsed=224.0s

  [15111/20519] intraday_4591.csv.gz  in=389,602,703 out=113,176,626 elapsed=224.0s

  [15112/20519] intraday_4592.csv.gz  in=389,614,637 out=113,176,626 elapsed=224.0s

  [15113/20519] intraday_4593.csv.gz  in=389,626,247 out=113,176,626 elapsed=224.0s

  [15114/20519] intraday_4594.csv.gz  in=389,636,621 out=113,176,626 elapsed=224.0s

  [15115/20519] intraday_4596.csv.gz  in=389,647,330 out=113,176,626 elapsed=224.0s

  [15116/20519] intraday_4597.csv.gz  in=389,659,669 out=113,176,626 elapsed=224.0s

  [15117/20519] intraday_4595.csv.gz  in=389,675,607 out=113,176,626 elapsed=224.0s

  [15118/20519] intraday_4598.csv.gz  in=389,686,781 out=113,176,626 elapsed=224.0s

  [15119/20519] intraday_4600.csv.gz  in=389,697,975 out=113,176,626 elapsed=224.1s

  [15120/20519] intraday_4601.csv.gz  in=389,711,944 out=113,176,626 elapsed=224.1s

  [15121/20519] intraday_4599.csv.gz  in=389,732,599 out=113,176,626 elapsed=224.1s

  [15122/20519] intraday_4602.csv.gz  in=389,746,054 out=113,176,626 elapsed=224.1s

  [15123/20519] intraday_4603.csv.gz  in=389,759,613 out=113,176,626 elapsed=224.1s

  [15124/20519] intraday_4604.csv.gz  in=389,771,706 out=113,176,626 elapsed=224.1s

  [15125/20519] intraday_4605.csv.gz  in=389,781,458 out=113,176,626 elapsed=224.1s

  [15126/20519] intraday_4607.csv.gz  in=389,792,584 out=113,176,626 elapsed=224.1s

  [15127/20519] intraday_4606.csv.gz  in=389,816,445 out=113,176,626 elapsed=224.1s

  [15128/20519] intraday_4608.csv.gz  in=389,828,720 out=113,176,626 elapsed=224.1s

  [15129/20519] intraday_4609.csv.gz  in=389,841,401 out=113,176,626 elapsed=224.1s

  [15130/20519] intraday_4611.csv.gz  in=389,851,413 out=113,176,626 elapsed=224.2s

  [15131/20519] intraday_4610.csv.gz  in=389,863,110 out=113,176,626 elapsed=224.2s

  [15132/20519] intraday_4612.csv.gz  in=389,875,140 out=113,176,626 elapsed=224.2s

  [15133/20519] intraday_4616.csv.gz  in=389,885,470 out=113,176,626 elapsed=224.2s

  [15134/20519] intraday_4614.csv.gz  in=389,896,950 out=113,176,626 elapsed=224.2s

  [15135/20519] intraday_4613.csv.gz  in=389,911,353 out=113,176,626 elapsed=224.2s

  [15136/20519] intraday_4615.csv.gz  in=389,923,827 out=113,176,626 elapsed=224.2s

  [15137/20519] intraday_4617.csv.gz  in=389,935,274 out=113,176,626 elapsed=224.2s

  [15138/20519] intraday_4618.csv.gz  in=389,948,016 out=113,176,626 elapsed=224.2s

  [15139/20519] intraday_4619.csv.gz  in=389,965,047 out=113,176,626 elapsed=224.2s

  [15140/20519] intraday_4620.csv.gz  in=389,978,117 out=113,176,626 elapsed=224.2s

  [15141/20519] intraday_4621.csv.gz  in=389,989,475 out=113,176,626 elapsed=224.3s

  [15142/20519] intraday_4622.csv.gz  in=389,999,918 out=113,176,626 elapsed=224.3s

  [15143/20519] intraday_4623.csv.gz  in=390,013,951 out=113,176,626 elapsed=224.3s

  [15144/20519] intraday_4624.csv.gz  in=390,028,713 out=113,176,626 elapsed=224.3s

  [15145/20519] intraday_4625.csv.gz  in=390,043,152 out=113,176,626 elapsed=224.3s

  [15146/20519] intraday_4626.csv.gz  in=390,053,934 out=113,176,626 elapsed=224.3s

  [15147/20519] intraday_4628.csv.gz  in=390,067,858 out=113,176,626 elapsed=224.3s

  [15148/20519] intraday_4627.csv.gz  in=390,084,515 out=113,176,626 elapsed=224.3s

  [15149/20519] intraday_4630.csv.gz  in=390,098,579 out=113,176,626 elapsed=224.4s

  [15150/20519] intraday_4629.csv.gz  in=390,116,055 out=113,176,626 elapsed=224.4s

  [15151/20519] intraday_4631.csv.gz  in=390,128,082 out=113,176,626 elapsed=224.4s

  [15152/20519] intraday_4632.csv.gz  in=390,139,637 out=113,176,626 elapsed=224.4s

  [15153/20519] intraday_4634.csv.gz  in=390,150,858 out=113,176,626 elapsed=224.4s

  [15154/20519] intraday_4635.csv.gz  in=390,162,247 out=113,176,626 elapsed=224.4s

  [15155/20519] intraday_4633.csv.gz  in=390,174,430 out=113,176,626 elapsed=224.4s

  [15156/20519] intraday_4636.csv.gz  in=390,185,796 out=113,176,626 elapsed=224.4s

  [15157/20519] intraday_4638.csv.gz  in=390,202,227 out=113,176,626 elapsed=224.5s

  [15158/20519] intraday_4639.csv.gz  in=390,214,394 out=113,176,626 elapsed=224.5s

  [15159/20519] intraday_4637.csv.gz  in=390,226,706 out=113,176,626 elapsed=224.5s

  [15160/20519] intraday_4640.csv.gz  in=390,240,380 out=113,176,626 elapsed=224.5s

  [15161/20519] intraday_4642.csv.gz  in=390,252,928 out=113,176,626 elapsed=224.6s

  [15162/20519] intraday_4641.csv.gz  in=390,265,700 out=113,176,626 elapsed=224.6s

  [15163/20519] intraday_4643.csv.gz  in=390,278,205 out=113,176,626 elapsed=224.6s

  [15164/20519] intraday_4646.csv.gz  in=390,289,730 out=113,176,626 elapsed=224.6s

  [15165/20519] intraday_4645.csv.gz  in=390,302,785 out=113,176,626 elapsed=224.6s

  [15166/20519] intraday_4647.csv.gz  in=390,316,957 out=113,176,626 elapsed=224.6s

  [15167/20519] intraday_4644.csv.gz  in=390,330,790 out=113,176,626 elapsed=224.6s

  [15168/20519] intraday_4648.csv.gz  in=390,344,032 out=113,176,626 elapsed=224.7s

  [15169/20519] intraday_4650.csv.gz  in=390,358,416 out=113,176,626 elapsed=224.7s

  [15170/20519] intraday_4651.csv.gz  in=390,371,419 out=113,176,626 elapsed=224.7s

  [15171/20519] intraday_4649.csv.gz  in=390,386,214 out=113,176,626 elapsed=224.7s

  [15172/20519] intraday_4652.csv.gz  in=390,400,895 out=113,176,626 elapsed=224.7s

  [15173/20519] intraday_4654.csv.gz  in=390,413,884 out=113,176,626 elapsed=224.7s

  [15174/20519] intraday_4655.csv.gz  in=390,425,491 out=113,176,626 elapsed=224.7s

  [15175/20519] intraday_4653.csv.gz  in=390,439,859 out=113,176,626 elapsed=224.7s

  [15176/20519] intraday_4656.csv.gz  in=390,450,210 out=113,176,626 elapsed=224.7s

  [15177/20519] intraday_4657.csv.gz  in=390,463,210 out=113,176,626 elapsed=224.7s

  [15178/20519] intraday_4658.csv.gz  in=390,474,657 out=113,176,626 elapsed=224.8s

  [15179/20519] intraday_4659.csv.gz  in=390,489,157 out=113,176,626 elapsed=224.8s

  [15180/20519] intraday_4660.csv.gz  in=390,502,797 out=113,176,626 elapsed=224.8s

  [15181/20519] intraday_4662.csv.gz  in=390,514,906 out=113,176,626 elapsed=224.8s

  [15182/20519] intraday_4661.csv.gz  in=390,532,335 out=113,176,626 elapsed=224.8s

  [15183/20519] intraday_4663.csv.gz  in=390,545,904 out=113,176,626 elapsed=224.8s

  [15184/20519] intraday_4664.csv.gz  in=390,559,346 out=113,176,626 elapsed=224.8s

  [15185/20519] intraday_4665.csv.gz  in=390,570,728 out=113,176,626 elapsed=224.8s

  [15186/20519] intraday_4666.csv.gz  in=390,583,533 out=113,176,626 elapsed=224.8s

  [15187/20519] intraday_4668.csv.gz  in=390,597,720 out=113,176,626 elapsed=224.8s

  [15188/20519] intraday_4667.csv.gz  in=390,612,769 out=113,176,626 elapsed=224.8s

  [15189/20519] intraday_4669.csv.gz  in=390,625,444 out=113,176,626 elapsed=224.9s

  [15190/20519] intraday_4671.csv.gz  in=390,636,303 out=113,176,626 elapsed=224.9s

  [15191/20519] intraday_4672.csv.gz  in=390,647,643 out=113,176,626 elapsed=224.9s

  [15192/20519] intraday_4670.csv.gz  in=390,664,210 out=113,176,626 elapsed=224.9s

  [15193/20519] intraday_4673.csv.gz  in=390,675,805 out=113,176,626 elapsed=224.9s

  [15194/20519] intraday_4675.csv.gz  in=390,685,004 out=113,176,626 elapsed=224.9s

  [15195/20519] intraday_4676.csv.gz  in=390,699,289 out=113,176,626 elapsed=224.9s

  [15196/20519] intraday_4674.csv.gz  in=390,712,697 out=113,176,626 elapsed=224.9s

  [15197/20519] intraday_4677.csv.gz  in=390,724,160 out=113,176,626 elapsed=224.9s

  [15198/20519] intraday_4678.csv.gz  in=390,724,432 out=113,176,626 elapsed=224.9s

  [15199/20519] intraday_4679.csv.gz  in=390,738,735 out=113,176,626 elapsed=225.0s

  [15200/20519] intraday_4680.csv.gz  in=390,752,502 out=113,176,626 elapsed=225.0s

  [15201/20519] intraday_4682.csv.gz  in=390,762,305 out=113,176,626 elapsed=225.0s

  [15202/20519] intraday_4681.csv.gz  in=390,774,118 out=113,176,626 elapsed=225.0s

  [15203/20519] intraday_4683.csv.gz  in=390,789,073 out=113,176,626 elapsed=225.0s

  [15204/20519] intraday_4685.csv.gz  in=390,801,203 out=113,176,626 elapsed=225.0s

  [15205/20519] intraday_4686.csv.gz  in=390,813,517 out=113,176,626 elapsed=225.0s

  [15206/20519] intraday_4684.csv.gz  in=390,829,693 out=113,176,626 elapsed=225.0s

  [15207/20519] intraday_4687.csv.gz  in=390,843,243 out=113,176,626 elapsed=225.0s

  [15208/20519] intraday_4688.csv.gz  in=390,857,204 out=113,176,626 elapsed=225.0s

  [15209/20519] intraday_4689.csv.gz  in=390,867,852 out=113,176,626 elapsed=225.1s

  [15210/20519] intraday_4691.csv.gz  in=390,880,963 out=113,176,626 elapsed=225.1s

  [15211/20519] intraday_4690.csv.gz  in=390,892,786 out=113,176,626 elapsed=225.1s

  [15212/20519] intraday_4692.csv.gz  in=390,902,913 out=113,176,626 elapsed=225.1s

  [15213/20519] intraday_4694.csv.gz  in=390,912,826 out=113,176,626 elapsed=225.1s

  [15214/20519] intraday_4693.csv.gz  in=390,923,455 out=113,176,626 elapsed=225.1s

  [15215/20519] intraday_4696.csv.gz  in=390,935,650 out=113,176,626 elapsed=225.1s

  [15216/20519] intraday_4695.csv.gz  in=390,948,707 out=113,176,626 elapsed=225.1s

  [15217/20519] intraday_4697.csv.gz  in=390,958,679 out=113,176,626 elapsed=225.1s

  [15218/20519] intraday_4698.csv.gz  in=390,970,629 out=113,176,626 elapsed=225.2s

  [15219/20519] intraday_4699.csv.gz  in=390,983,515 out=113,176,626 elapsed=225.2s

  [15220/20519] intraday_4700.csv.gz  in=390,996,758 out=113,176,626 elapsed=225.2s

  [15221/20519] intraday_4701.csv.gz  in=391,010,716 out=113,176,626 elapsed=225.2s

  [15222/20519] intraday_4702.csv.gz  in=391,022,513 out=113,176,626 elapsed=225.2s

  [15223/20519] intraday_4703.csv.gz  in=391,034,337 out=113,176,626 elapsed=225.2s

  [15224/20519] intraday_4704.csv.gz  in=391,044,346 out=113,176,626 elapsed=225.2s

  [15225/20519] intraday_4705.csv.gz  in=391,056,482 out=113,176,626 elapsed=225.2s

  [15226/20519] intraday_4707.csv.gz  in=391,069,056 out=113,176,626 elapsed=225.2s

  [15227/20519] intraday_4706.csv.gz  in=391,085,115 out=113,176,626 elapsed=225.3s

  [15228/20519] intraday_4708.csv.gz  in=391,098,952 out=113,176,626 elapsed=225.3s

  [15229/20519] intraday_4709.csv.gz  in=391,113,742 out=113,176,626 elapsed=225.3s

  [15230/20519] intraday_4710.csv.gz  in=391,124,692 out=113,176,626 elapsed=225.3s

  [15231/20519] intraday_4712.csv.gz  in=391,137,315 out=113,176,626 elapsed=225.3s

  [15232/20519] intraday_4711.csv.gz  in=391,148,127 out=113,176,626 elapsed=225.3s

  [15233/20519] intraday_4716.csv.gz  in=391,158,843 out=113,176,626 elapsed=225.4s

  [15234/20519] intraday_4715.csv.gz  in=391,168,923 out=113,176,626 elapsed=225.4s

  [15235/20519] intraday_4714.csv.gz  in=391,181,221 out=113,176,626 elapsed=225.4s

  [15236/20519] intraday_4713.csv.gz  in=391,207,280 out=113,176,626 elapsed=225.5s

  [15237/20519] intraday_4718.csv.gz  in=391,218,784 out=113,176,626 elapsed=225.5s

  [15238/20519] intraday_4717.csv.gz  in=391,249,132 out=113,176,626 elapsed=225.5s

  [15239/20519] intraday_4719.csv.gz  in=391,262,664 out=113,176,626 elapsed=225.5s

  [15240/20519] intraday_4721.csv.gz  in=391,274,719 out=113,176,626 elapsed=225.5s

  [15241/20519] intraday_4720.csv.gz  in=391,296,185 out=113,176,626 elapsed=225.5s

  [15242/20519] intraday_4722.csv.gz  in=391,307,204 out=113,176,626 elapsed=225.5s

  [15243/20519] intraday_4725.csv.gz  in=391,317,259 out=113,176,626 elapsed=225.6s

  [15244/20519] intraday_4723.csv.gz  in=391,328,603 out=113,176,626 elapsed=225.6s

  [15245/20519] intraday_4724.csv.gz  in=391,341,496 out=113,176,626 elapsed=225.6s

  [15246/20519] intraday_4726.csv.gz  in=391,352,931 out=113,176,626 elapsed=225.6s

  [15247/20519] intraday_4727.csv.gz  in=391,364,194 out=113,176,626 elapsed=225.6s

  [15248/20519] intraday_4728.csv.gz  in=391,373,726 out=113,176,626 elapsed=225.6s

  [15249/20519] intraday_4729.csv.gz  in=391,384,885 out=113,176,626 elapsed=225.6s

  [15250/20519] intraday_4730.csv.gz  in=391,396,324 out=113,176,626 elapsed=225.7s

  [15251/20519] intraday_4732.csv.gz  in=391,408,826 out=113,176,626 elapsed=225.7s

  [15252/20519] intraday_4731.csv.gz  in=391,424,541 out=113,176,626 elapsed=225.7s

  [15253/20519] intraday_4733.csv.gz  in=391,436,598 out=113,176,626 elapsed=225.7s

  [15254/20519] intraday_4735.csv.gz  in=391,447,412 out=113,176,626 elapsed=225.7s

  [15255/20519] intraday_4734.csv.gz  in=391,457,093 out=113,176,626 elapsed=225.7s

  [15256/20519] intraday_4736.csv.gz  in=391,469,038 out=113,176,626 elapsed=225.7s

  [15257/20519] intraday_4737.csv.gz  in=391,481,510 out=113,176,626 elapsed=225.7s

  [15258/20519] intraday_4738.csv.gz  in=391,493,310 out=113,176,626 elapsed=225.7s

  [15259/20519] intraday_4739.csv.gz  in=391,505,600 out=113,176,626 elapsed=225.7s

  [15260/20519] intraday_4740.csv.gz  in=391,517,636 out=113,176,626 elapsed=225.7s

  [15261/20519] intraday_4741.csv.gz  in=391,528,059 out=113,176,626 elapsed=225.8s

  [15262/20519] intraday_4742.csv.gz  in=391,543,623 out=113,176,626 elapsed=225.8s

  [15263/20519] intraday_4743.csv.gz  in=391,556,832 out=113,176,626 elapsed=225.8s

  [15264/20519] intraday_4746.csv.gz  in=391,568,318 out=113,176,626 elapsed=225.8s

  [15265/20519] intraday_4745.csv.gz  in=391,579,340 out=113,176,626 elapsed=225.8s

  [15266/20519] intraday_4744.csv.gz  in=391,592,616 out=113,176,626 elapsed=225.8s

  [15267/20519] intraday_4747.csv.gz  in=391,602,112 out=113,176,626 elapsed=225.8s

  [15268/20519] intraday_4748.csv.gz  in=391,614,326 out=113,176,626 elapsed=225.8s

  [15269/20519] intraday_4749.csv.gz  in=391,625,637 out=113,176,626 elapsed=225.8s

  [15270/20519] intraday_4751.csv.gz  in=391,636,229 out=113,176,626 elapsed=225.8s

  [15271/20519] intraday_4750.csv.gz  in=391,649,546 out=113,176,626 elapsed=225.8s

  [15272/20519] intraday_4752.csv.gz  in=391,660,606 out=113,176,626 elapsed=225.9s

  [15273/20519] intraday_4753.csv.gz  in=391,671,051 out=113,176,626 elapsed=225.9s

  [15274/20519] intraday_4755.csv.gz  in=391,682,940 out=113,176,626 elapsed=225.9s

  [15275/20519] intraday_4754.csv.gz  in=391,696,447 out=113,176,626 elapsed=225.9s

  [15276/20519] intraday_4756.csv.gz  in=391,709,237 out=113,176,626 elapsed=225.9s

  [15277/20519] intraday_4757.csv.gz  in=391,719,465 out=113,176,626 elapsed=225.9s

  [15278/20519] intraday_4758.csv.gz  in=391,729,340 out=113,176,626 elapsed=225.9s

  [15279/20519] intraday_4759.csv.gz  in=391,740,578 out=113,176,626 elapsed=225.9s

  [15280/20519] intraday_4760.csv.gz  in=391,756,474 out=113,176,626 elapsed=225.9s

  [15281/20519] intraday_4761.csv.gz  in=391,770,761 out=113,176,626 elapsed=225.9s

  [15282/20519] intraday_4762.csv.gz  in=391,782,178 out=113,176,626 elapsed=225.9s

  [15283/20519] intraday_4763.csv.gz  in=391,793,165 out=113,176,626 elapsed=226.0s

  [15284/20519] intraday_4764.csv.gz  in=391,803,253 out=113,176,626 elapsed=226.0s

  [15285/20519] intraday_4765.csv.gz  in=391,816,432 out=113,176,626 elapsed=226.0s

  [15286/20519] intraday_4766.csv.gz  in=391,832,053 out=113,176,626 elapsed=226.0s

  [15287/20519] intraday_4767.csv.gz  in=391,844,172 out=113,176,626 elapsed=226.0s

  [15288/20519] intraday_4769.csv.gz  in=391,856,857 out=113,176,626 elapsed=226.0s

  [15289/20519] intraday_4768.csv.gz  in=391,870,667 out=113,176,626 elapsed=226.0s

  [15290/20519] intraday_4770.csv.gz  in=391,883,769 out=113,176,626 elapsed=226.1s

  [15291/20519] intraday_4773.csv.gz  in=391,903,426 out=113,176,626 elapsed=226.1s

  [15292/20519] intraday_4771.csv.gz  in=391,920,445 out=113,176,626 elapsed=226.1s

  [15293/20519] intraday_4772.csv.gz  in=391,932,673 out=113,176,626 elapsed=226.1s

  [15294/20519] intraday_4775.csv.gz  in=391,943,603 out=113,176,626 elapsed=226.1s

  [15295/20519] intraday_4774.csv.gz  in=391,954,279 out=113,176,626 elapsed=226.1s

  [15296/20519] intraday_4776.csv.gz  in=391,966,508 out=113,176,626 elapsed=226.1s

  [15297/20519] intraday_4777.csv.gz  in=391,977,739 out=113,176,626 elapsed=226.1s

  [15298/20519] intraday_4778.csv.gz  in=391,989,430 out=113,176,626 elapsed=226.1s

  [15299/20519] intraday_4779.csv.gz  in=392,003,488 out=113,176,626 elapsed=226.1s

  [15300/20519] intraday_4780.csv.gz  in=392,025,485 out=113,176,626 elapsed=226.1s

  [15301/20519] intraday_4781.csv.gz  in=392,054,123 out=113,176,626 elapsed=226.1s

  [15302/20519] intraday_4783.csv.gz  in=392,064,556 out=113,176,626 elapsed=226.2s

  [15303/20519] intraday_4784.csv.gz  in=392,076,480 out=113,176,626 elapsed=226.2s

  [15304/20519] intraday_4782.csv.gz  in=392,091,127 out=113,176,626 elapsed=226.2s

  [15305/20519] intraday_4785.csv.gz  in=392,103,996 out=113,176,626 elapsed=226.2s

  [15306/20519] intraday_4786.csv.gz  in=392,118,293 out=113,176,626 elapsed=226.2s

  [15307/20519] intraday_4787.csv.gz  in=392,130,264 out=113,176,626 elapsed=226.2s

  [15308/20519] intraday_4788.csv.gz  in=392,143,146 out=113,176,626 elapsed=226.2s

  [15309/20519] intraday_4789.csv.gz  in=392,156,103 out=113,176,626 elapsed=226.2s

  [15310/20519] intraday_4790.csv.gz  in=392,169,832 out=113,176,626 elapsed=226.2s

  [15311/20519] intraday_4792.csv.gz  in=392,183,562 out=113,176,626 elapsed=226.2s

  [15312/20519] intraday_4791.csv.gz  in=392,198,498 out=113,176,626 elapsed=226.2s

  [15313/20519] intraday_4793.csv.gz  in=392,209,365 out=113,176,626 elapsed=226.3s

  [15314/20519] intraday_4795.csv.gz  in=392,221,613 out=113,176,626 elapsed=226.3s

  [15315/20519] intraday_4794.csv.gz  in=392,237,417 out=113,176,626 elapsed=226.3s

  [15316/20519] intraday_4796.csv.gz  in=392,249,143 out=113,176,626 elapsed=226.3s

  [15317/20519] intraday_4797.csv.gz  in=392,259,675 out=113,176,626 elapsed=226.3s

  [15318/20519] intraday_4798.csv.gz  in=392,271,528 out=113,176,626 elapsed=226.3s

  [15319/20519] intraday_4800.csv.gz  in=392,285,117 out=113,176,626 elapsed=226.3s

  [15320/20519] intraday_4799.csv.gz  in=392,299,097 out=113,176,626 elapsed=226.3s

  [15321/20519] intraday_4801.csv.gz  in=392,326,057 out=113,176,626 elapsed=226.3s

  [15322/20519] intraday_4802.csv.gz  in=392,343,446 out=113,176,626 elapsed=226.3s

  [15323/20519] intraday_4803.csv.gz  in=392,354,820 out=113,176,626 elapsed=226.3s

  [15324/20519] intraday_4804.csv.gz  in=392,367,682 out=113,176,626 elapsed=226.4s

  [15325/20519] intraday_4805.csv.gz  in=392,378,646 out=113,176,626 elapsed=226.4s

  [15326/20519] intraday_4807.csv.gz  in=392,389,084 out=113,176,626 elapsed=226.4s

  [15327/20519] intraday_4806.csv.gz  in=392,401,982 out=113,176,626 elapsed=226.4s

  [15328/20519] intraday_4808.csv.gz  in=392,414,938 out=113,176,626 elapsed=226.4s

  [15329/20519] intraday_4809.csv.gz  in=392,429,245 out=113,176,626 elapsed=226.4s

  [15330/20519] intraday_4810.csv.gz  in=392,442,401 out=113,176,626 elapsed=226.4s

  [15331/20519] intraday_4811.csv.gz  in=392,455,724 out=113,176,626 elapsed=226.4s

  [15332/20519] intraday_4814.csv.gz  in=392,467,891 out=113,176,626 elapsed=226.5s

  [15333/20519] intraday_4815.csv.gz  in=392,479,259 out=113,176,626 elapsed=226.5s

  [15334/20519] intraday_4813.csv.gz  in=392,491,066 out=113,176,626 elapsed=226.5s

  [15335/20519] intraday_4812.csv.gz  in=392,502,171 out=113,176,626 elapsed=226.5s

  [15336/20519] intraday_4817.csv.gz  in=392,510,033 out=113,176,626 elapsed=226.5s

  [15337/20519] intraday_4816.csv.gz  in=392,521,154 out=113,176,626 elapsed=226.5s

  [15338/20519] intraday_4818.csv.gz  in=392,530,760 out=113,176,626 elapsed=226.6s

  [15339/20519] intraday_4819.csv.gz  in=392,544,526 out=113,176,626 elapsed=226.6s

  [15340/20519] intraday_4820.csv.gz  in=392,560,082 out=113,176,626 elapsed=226.6s

  [15341/20519] intraday_4821.csv.gz  in=392,574,254 out=113,176,626 elapsed=226.6s

  [15342/20519] intraday_4823.csv.gz  in=392,583,712 out=113,176,626 elapsed=226.6s

  [15343/20519] intraday_4822.csv.gz  in=392,596,187 out=113,176,626 elapsed=226.6s

  [15344/20519] intraday_4824.csv.gz  in=392,611,020 out=113,176,626 elapsed=226.7s

  [15345/20519] intraday_4826.csv.gz  in=392,623,341 out=113,176,626 elapsed=226.7s

  [15346/20519] intraday_4827.csv.gz  in=392,634,732 out=113,176,626 elapsed=226.7s

  [15347/20519] intraday_4825.csv.gz  in=392,650,827 out=113,176,626 elapsed=226.7s

  [15348/20519] intraday_4828.csv.gz  in=392,665,147 out=113,176,626 elapsed=226.7s

  [15349/20519] intraday_4830.csv.gz  in=392,675,672 out=113,176,626 elapsed=226.7s

  [15350/20519] intraday_4829.csv.gz  in=392,689,379 out=113,176,626 elapsed=226.7s

  [15351/20519] intraday_4831.csv.gz  in=392,701,470 out=113,176,626 elapsed=226.7s

  [15352/20519] intraday_4832.csv.gz  in=392,713,712 out=113,176,626 elapsed=226.7s

  [15353/20519] intraday_4833.csv.gz  in=392,727,488 out=113,176,626 elapsed=226.7s

  [15354/20519] intraday_4835.csv.gz  in=392,737,840 out=113,176,626 elapsed=226.7s

  [15355/20519] intraday_4834.csv.gz  in=392,748,602 out=113,176,626 elapsed=226.7s

  [15356/20519] intraday_4836.csv.gz  in=392,761,682 out=113,176,626 elapsed=226.8s

  [15357/20519] intraday_4837.csv.gz  in=392,773,654 out=113,176,626 elapsed=226.8s

  [15358/20519] intraday_4838.csv.gz  in=392,783,835 out=113,176,626 elapsed=226.8s

  [15359/20519] intraday_4839.csv.gz  in=392,795,453 out=113,176,626 elapsed=226.8s

  [15360/20519] intraday_4840.csv.gz  in=392,808,673 out=113,176,626 elapsed=226.8s

  [15361/20519] intraday_4841.csv.gz  in=392,821,769 out=113,176,626 elapsed=226.8s

  [15362/20519] intraday_4842.csv.gz  in=392,833,133 out=113,176,626 elapsed=226.8s

  [15363/20519] intraday_4843.csv.gz  in=392,845,462 out=113,176,626 elapsed=226.8s

  [15364/20519] intraday_4845.csv.gz  in=392,855,131 out=113,176,626 elapsed=226.8s

  [15365/20519] intraday_4844.csv.gz  in=392,887,386 out=113,176,626 elapsed=226.8s

  [15366/20519] intraday_4846.csv.gz  in=392,900,379 out=113,176,626 elapsed=226.8s

  [15367/20519] intraday_4847.csv.gz  in=392,912,025 out=113,176,626 elapsed=226.9s

  [15368/20519] intraday_4850.csv.gz  in=392,926,687 out=113,176,626 elapsed=226.9s

  [15369/20519] intraday_4848.csv.gz  in=392,938,845 out=113,176,626 elapsed=226.9s

  [15370/20519] intraday_4849.csv.gz  in=392,953,926 out=113,176,626 elapsed=226.9s

  [15371/20519] intraday_4852.csv.gz  in=392,965,023 out=113,176,626 elapsed=226.9s

  [15372/20519] intraday_4851.csv.gz  in=392,976,169 out=113,176,626 elapsed=226.9s

  [15373/20519] intraday_4853.csv.gz  in=392,988,499 out=113,176,626 elapsed=226.9s

  [15374/20519] intraday_4854.csv.gz  in=393,000,782 out=113,176,626 elapsed=226.9s

  [15375/20519] intraday_4856.csv.gz  in=393,010,446 out=113,176,626 elapsed=227.0s

  [15376/20519] intraday_4857.csv.gz  in=393,021,594 out=113,176,626 elapsed=227.0s

  [15377/20519] intraday_4855.csv.gz  in=393,046,394 out=113,176,626 elapsed=227.0s

  [15378/20519] intraday_4859.csv.gz  in=393,057,397 out=113,176,626 elapsed=227.0s

  [15379/20519] intraday_4858.csv.gz  in=393,068,693 out=113,176,626 elapsed=227.0s

  [15380/20519] intraday_4860.csv.gz  in=393,082,715 out=113,176,626 elapsed=227.0s

  [15381/20519] intraday_4862.csv.gz  in=393,094,326 out=113,176,626 elapsed=227.0s

  [15382/20519] intraday_4863.csv.gz  in=393,105,283 out=113,176,626 elapsed=227.0s

  [15383/20519] intraday_4861.csv.gz  in=393,117,597 out=113,176,626 elapsed=227.0s

  [15384/20519] intraday_4864.csv.gz  in=393,128,939 out=113,176,626 elapsed=227.0s

  [15385/20519] intraday_4867.csv.gz  in=393,139,669 out=113,176,626 elapsed=227.1s

  [15386/20519] intraday_4866.csv.gz  in=393,149,615 out=113,176,626 elapsed=227.1s

  [15387/20519] intraday_4865.csv.gz  in=393,168,837 out=113,176,626 elapsed=227.1s

  [15388/20519] intraday_4868.csv.gz  in=393,180,847 out=113,176,626 elapsed=227.1s

  [15389/20519] intraday_4869.csv.gz  in=393,190,162 out=113,176,626 elapsed=227.1s

  [15390/20519] intraday_4870.csv.gz  in=393,201,640 out=113,176,626 elapsed=227.1s

  [15391/20519] intraday_4871.csv.gz  in=393,212,400 out=113,176,626 elapsed=227.1s

  [15392/20519] intraday_4873.csv.gz  in=393,226,434 out=113,176,626 elapsed=227.1s

  [15393/20519] intraday_4872.csv.gz  in=393,241,905 out=113,176,626 elapsed=227.1s

  [15394/20519] intraday_4874.csv.gz  in=393,253,582 out=113,176,626 elapsed=227.1s

  [15395/20519] intraday_4875.csv.gz  in=393,263,464 out=113,176,626 elapsed=227.2s

  [15396/20519] intraday_4876.csv.gz  in=393,274,175 out=113,176,626 elapsed=227.2s

  [15397/20519] intraday_4878.csv.gz  in=393,286,981 out=113,176,626 elapsed=227.2s

  [15398/20519] intraday_4877.csv.gz  in=393,299,890 out=113,176,626 elapsed=227.2s

  [15399/20519] intraday_4881.csv.gz  in=393,311,055 out=113,176,626 elapsed=227.2s

  [15400/20519] intraday_4879.csv.gz  in=393,322,463 out=113,176,626 elapsed=227.2s

  [15401/20519] intraday_4882.csv.gz  in=393,336,948 out=113,176,626 elapsed=227.2s

  [15402/20519] intraday_4880.csv.gz  in=393,347,782 out=113,176,626 elapsed=227.2s

  [15403/20519] intraday_4884.csv.gz  in=393,360,877 out=113,176,626 elapsed=227.3s

  [15404/20519] intraday_4883.csv.gz  in=393,375,675 out=113,176,626 elapsed=227.3s

  [15405/20519] intraday_4885.csv.gz  in=393,388,073 out=113,176,626 elapsed=227.3s

  [15406/20519] intraday_4886.csv.gz  in=393,399,504 out=113,176,626 elapsed=227.3s

  [15407/20519] intraday_4887.csv.gz  in=393,410,683 out=113,176,626 elapsed=227.3s

  [15408/20519] intraday_4889.csv.gz  in=393,422,968 out=113,176,626 elapsed=227.3s

  [15409/20519] intraday_4888.csv.gz  in=393,434,231 out=113,176,626 elapsed=227.3s

  [15410/20519] intraday_4890.csv.gz  in=393,445,793 out=113,176,626 elapsed=227.3s

  [15411/20519] intraday_4891.csv.gz  in=393,459,147 out=113,176,626 elapsed=227.3s

  [15412/20519] intraday_4895.csv.gz  in=393,472,635 out=113,176,626 elapsed=227.4s

  [15413/20519] intraday_4893.csv.gz  in=393,484,145 out=113,176,626 elapsed=227.4s

  [15414/20519] intraday_4894.csv.gz  in=393,494,614 out=113,176,626 elapsed=227.4s

  [15415/20519] intraday_4892.csv.gz  in=393,505,315 out=113,176,626 elapsed=227.4s

  [15416/20519] intraday_4896.csv.gz  in=393,516,734 out=113,176,626 elapsed=227.4s

  [15417/20519] intraday_4897.csv.gz  in=393,528,867 out=113,176,626 elapsed=227.4s

  [15418/20519] intraday_4899.csv.gz  in=393,539,547 out=113,176,626 elapsed=227.4s

  [15419/20519] intraday_4898.csv.gz  in=393,550,197 out=113,176,626 elapsed=227.4s

  [15420/20519] intraday_4900.csv.gz  in=393,561,766 out=113,176,626 elapsed=227.4s

  [15421/20519] intraday_4901.csv.gz  in=393,577,515 out=113,176,626 elapsed=227.5s

  [15422/20519] intraday_4903.csv.gz  in=393,588,428 out=113,176,626 elapsed=227.5s

  [15423/20519] intraday_4902.csv.gz  in=393,601,361 out=113,176,626 elapsed=227.5s

  [15424/20519] intraday_4905.csv.gz  in=393,612,703 out=113,176,626 elapsed=227.5s

  [15425/20519] intraday_4904.csv.gz  in=393,623,980 out=113,176,626 elapsed=227.5s

  [15426/20519] intraday_4908.csv.gz  in=393,635,272 out=113,176,626 elapsed=227.5s

  [15427/20519] intraday_4907.csv.gz  in=393,651,077 out=113,176,626 elapsed=227.5s

  [15428/20519] intraday_4906.csv.gz  in=393,665,358 out=113,176,626 elapsed=227.5s

  [15429/20519] intraday_4909.csv.gz  in=393,679,663 out=113,176,626 elapsed=227.5s

  [15430/20519] intraday_4911.csv.gz  in=393,693,981 out=113,176,626 elapsed=227.6s

  [15431/20519] intraday_4910.csv.gz  in=393,708,219 out=113,176,626 elapsed=227.6s

  [15432/20519] intraday_4912.csv.gz  in=393,720,879 out=113,176,626 elapsed=227.6s

  [15433/20519] intraday_4913.csv.gz  in=393,732,791 out=113,176,626 elapsed=227.6s

  [15434/20519] intraday_4915.csv.gz  in=393,742,645 out=113,176,626 elapsed=227.6s

  [15435/20519] intraday_4917.csv.gz  in=393,753,285 out=113,176,626 elapsed=227.6s

  [15436/20519] intraday_4914.csv.gz  in=393,765,584 out=113,176,626 elapsed=227.6s

  [15437/20519] intraday_4916.csv.gz  in=393,778,592 out=113,176,626 elapsed=227.6s

  [15438/20519] intraday_4918.csv.gz  in=393,790,365 out=113,176,626 elapsed=227.6s

  [15439/20519] intraday_4919.csv.gz  in=393,803,673 out=113,176,626 elapsed=227.6s

  [15440/20519] intraday_4921.csv.gz  in=393,819,781 out=113,176,626 elapsed=227.7s

  [15441/20519] intraday_4920.csv.gz  in=393,832,509 out=113,176,626 elapsed=227.7s

  [15442/20519] intraday_4922.csv.gz  in=393,843,444 out=113,176,626 elapsed=227.7s

  [15443/20519] intraday_4923.csv.gz  in=393,858,920 out=113,176,626 elapsed=227.7s

  [15444/20519] intraday_4924.csv.gz  in=393,870,037 out=113,176,626 elapsed=227.7s

  [15445/20519] intraday_4925.csv.gz  in=393,882,036 out=113,176,626 elapsed=227.7s

  [15446/20519] intraday_4926.csv.gz  in=393,895,562 out=113,176,626 elapsed=227.7s

  [15447/20519] intraday_4928.csv.gz  in=393,907,459 out=113,176,626 elapsed=227.7s

  [15448/20519] intraday_4927.csv.gz  in=393,921,542 out=113,176,626 elapsed=227.7s

  [15449/20519] intraday_4929.csv.gz  in=393,935,466 out=113,176,626 elapsed=227.7s

  [15450/20519] intraday_4930.csv.gz  in=393,948,939 out=113,176,626 elapsed=227.7s

  [15451/20519] intraday_4931.csv.gz  in=393,962,223 out=113,176,626 elapsed=227.7s

  [15452/20519] intraday_4933.csv.gz  in=393,976,835 out=113,176,626 elapsed=227.7s

  [15453/20519] intraday_4932.csv.gz  in=393,998,697 out=113,176,626 elapsed=227.7s

  [15454/20519] intraday_4934.csv.gz  in=394,010,270 out=113,176,626 elapsed=227.8s

  [15455/20519] intraday_4935.csv.gz  in=394,025,840 out=113,176,626 elapsed=227.8s

  [15456/20519] intraday_4936.csv.gz  in=394,037,493 out=113,176,626 elapsed=227.8s

  [15457/20519] intraday_4937.csv.gz  in=394,049,242 out=113,176,626 elapsed=227.8s

  [15458/20519] intraday_4938.csv.gz  in=394,059,707 out=113,176,626 elapsed=227.8s

  [15459/20519] intraday_4940.csv.gz  in=394,070,455 out=113,176,626 elapsed=227.8s

  [15460/20519] intraday_4939.csv.gz  in=394,083,430 out=113,176,626 elapsed=227.8s

  [15461/20519] intraday_4941.csv.gz  in=394,096,930 out=113,176,626 elapsed=227.8s

  [15462/20519] intraday_4942.csv.gz  in=394,109,637 out=113,176,626 elapsed=227.8s

  [15463/20519] intraday_4943.csv.gz  in=394,126,128 out=113,176,626 elapsed=227.8s

  [15464/20519] intraday_4944.csv.gz  in=394,137,459 out=113,176,626 elapsed=227.9s

  [15465/20519] intraday_4945.csv.gz  in=394,149,776 out=113,176,626 elapsed=227.9s

  [15466/20519] intraday_4948.csv.gz  in=394,160,669 out=113,176,626 elapsed=227.9s

  [15467/20519] intraday_4949.csv.gz  in=394,174,415 out=113,176,626 elapsed=227.9s

  [15468/20519] intraday_4946.csv.gz  in=394,199,428 out=113,176,626 elapsed=227.9s

  [15469/20519] intraday_4947.csv.gz  in=394,213,594 out=113,176,626 elapsed=227.9s

  [15470/20519] intraday_4950.csv.gz  in=394,228,686 out=113,176,626 elapsed=227.9s

  [15471/20519] intraday_4951.csv.gz  in=394,241,813 out=113,176,626 elapsed=227.9s

  [15472/20519] intraday_4952.csv.gz  in=394,256,078 out=113,176,626 elapsed=227.9s

  [15473/20519] intraday_4953.csv.gz  in=394,266,698 out=113,176,626 elapsed=227.9s

  [15474/20519] intraday_4954.csv.gz  in=394,278,420 out=113,176,626 elapsed=228.0s

  [15475/20519] intraday_4957.csv.gz  in=394,287,975 out=113,176,626 elapsed=228.0s

  [15476/20519] intraday_4955.csv.gz  in=394,301,271 out=113,176,626 elapsed=228.0s

  [15477/20519] intraday_4956.csv.gz  in=394,314,506 out=113,176,626 elapsed=228.0s

  [15478/20519] intraday_4960.csv.gz  in=394,321,185 out=113,176,626 elapsed=228.0s

  [15479/20519] intraday_4959.csv.gz  in=394,331,584 out=113,176,626 elapsed=228.0s

  [15480/20519] intraday_4958.csv.gz  in=394,340,730 out=113,176,626 elapsed=228.0s

  [15481/20519] intraday_4963.csv.gz  in=394,504,290 out=113,176,626 elapsed=228.1s

  [15482/20519] intraday_4964.csv.gz  in=394,676,985 out=113,176,626 elapsed=228.1s

  [15483/20519] intraday_4962.csv.gz  in=394,846,874 out=113,176,626 elapsed=228.2s

  [15484/20519] intraday_4961.csv.gz  in=395,049,874 out=113,176,626 elapsed=228.2s

  [15485/20519] intraday_4965.csv.gz  in=395,236,753 out=113,176,626 elapsed=228.3s

  [15486/20519] intraday_4968.csv.gz  in=395,391,676 out=113,176,626 elapsed=228.3s

  [15487/20519] intraday_4967.csv.gz  in=395,577,482 out=113,176,626 elapsed=228.3s

  [15488/20519] intraday_4966.csv.gz  in=395,783,810 out=113,176,626 elapsed=228.3s

  [15489/20519] intraday_4970.csv.gz  in=395,956,047 out=113,176,626 elapsed=228.5s

  [15490/20519] intraday_4969.csv.gz  in=396,136,190 out=113,176,626 elapsed=228.5s

  [15491/20519] intraday_4972.csv.gz  in=396,293,879 out=113,176,626 elapsed=228.5s

  [15492/20519] intraday_4971.csv.gz  in=396,470,488 out=113,176,626 elapsed=228.5s

  [15493/20519] intraday_4976.csv.gz  in=396,588,744 out=113,176,626 elapsed=228.6s

  [15494/20519] intraday_4973.csv.gz  in=396,746,861 out=113,176,626 elapsed=228.6s

  [15495/20519] intraday_4975.csv.gz  in=396,879,433 out=113,176,626 elapsed=228.7s

  [15496/20519] intraday_4974.csv.gz  in=397,027,279 out=113,176,626 elapsed=228.7s

  [15497/20519] intraday_4979.csv.gz  in=397,158,662 out=113,176,626 elapsed=228.8s

  [15498/20519] intraday_4978.csv.gz  in=397,330,715 out=113,176,626 elapsed=228.8s

  [15499/20519] intraday_4977.csv.gz  in=397,521,506 out=113,176,626 elapsed=228.8s

  [15500/20519] intraday_4980.csv.gz  in=397,685,390 out=113,176,626 elapsed=228.8s

  [15501/20519] intraday_4981.csv.gz  in=397,832,512 out=113,176,626 elapsed=228.9s

  [15502/20519] intraday_4983.csv.gz  in=397,971,624 out=113,176,626 elapsed=228.9s

  [15503/20519] intraday_4984.csv.gz  in=398,123,058 out=113,176,626 elapsed=229.0s

  [15504/20519] intraday_4982.csv.gz  in=398,299,409 out=113,176,626 elapsed=229.0s

  [15505/20519] intraday_4985.csv.gz  in=398,461,156 out=113,176,626 elapsed=229.0s

  [15506/20519] intraday_4986.csv.gz  in=398,607,932 out=113,176,626 elapsed=229.1s

  [15507/20519] intraday_4988.csv.gz  in=398,753,926 out=113,176,626 elapsed=229.1s

  [15508/20519] intraday_4987.csv.gz  in=398,914,426 out=113,176,626 elapsed=229.1s

  [15509/20519] intraday_4989.csv.gz  in=399,096,898 out=113,176,626 elapsed=229.2s

  [15510/20519] intraday_4990.csv.gz  in=399,289,051 out=113,176,626 elapsed=229.2s

  [15511/20519] intraday_4992.csv.gz  in=399,440,676 out=113,176,626 elapsed=229.2s

  [15512/20519] intraday_4991.csv.gz  in=399,634,924 out=113,176,626 elapsed=229.2s

  [15513/20519] intraday_4993.csv.gz  in=399,786,422 out=113,176,626 elapsed=229.3s

  [15514/20519] intraday_4994.csv.gz  in=399,935,255 out=113,176,626 elapsed=229.4s

  [15515/20519] intraday_4996.csv.gz  in=400,076,141 out=113,176,626 elapsed=229.4s

  [15516/20519] intraday_4995.csv.gz  in=400,254,912 out=113,176,626 elapsed=229.4s

  [15517/20519] intraday_4997.csv.gz  in=400,412,865 out=113,176,626 elapsed=229.4s

  [15518/20519] intraday_4999.csv.gz  in=400,540,255 out=113,176,626 elapsed=229.5s

  [15519/20519] intraday_5000.csv.gz  in=400,679,817 out=113,176,626 elapsed=229.5s

  [15520/20519] intraday_4998.csv.gz  in=400,833,961 out=113,176,626 elapsed=229.5s

  [15521/20519] intraday_5001.csv.gz  in=400,995,142 out=113,176,626 elapsed=229.6s

  [15522/20519] intraday_5002.csv.gz  in=401,147,657 out=113,176,626 elapsed=229.6s

  [15523/20519] intraday_5003.csv.gz  in=401,304,607 out=113,176,626 elapsed=229.7s

  [15524/20519] intraday_5004.csv.gz  in=401,477,168 out=113,176,626 elapsed=229.7s

  [15525/20519] intraday_5005.csv.gz  in=401,643,101 out=113,176,626 elapsed=229.7s

  [15526/20519] intraday_5006.csv.gz  in=401,799,450 out=113,176,626 elapsed=229.8s

  [15527/20519] intraday_5007.csv.gz  in=401,939,029 out=113,176,626 elapsed=229.8s

  [15528/20519] intraday_5008.csv.gz  in=402,083,269 out=113,176,626 elapsed=229.8s

  [15529/20519] intraday_5009.csv.gz  in=402,242,988 out=113,176,626 elapsed=229.8s

  [15530/20519] intraday_5010.csv.gz  in=402,375,987 out=113,176,626 elapsed=229.9s

  [15531/20519] intraday_5011.csv.gz  in=402,516,176 out=113,176,626 elapsed=229.9s

  [15532/20519] intraday_5013.csv.gz  in=402,647,325 out=113,176,626 elapsed=229.9s

  [15533/20519] intraday_5012.csv.gz  in=402,850,364 out=113,176,626 elapsed=230.0s

  [15534/20519] intraday_5014.csv.gz  in=403,006,058 out=113,176,626 elapsed=230.0s

  [15535/20519] intraday_5015.csv.gz  in=403,169,375 out=113,176,626 elapsed=230.0s

  [15536/20519] intraday_5016.csv.gz  in=403,328,760 out=113,176,626 elapsed=230.0s

  [15537/20519] intraday_5017.csv.gz  in=403,471,176 out=113,176,626 elapsed=230.1s

  [15538/20519] intraday_5018.csv.gz  in=403,623,403 out=113,176,626 elapsed=230.1s

  [15539/20519] intraday_5020.csv.gz  in=403,769,573 out=113,176,626 elapsed=230.2s

  [15540/20519] intraday_5019.csv.gz  in=403,943,304 out=113,176,626 elapsed=230.2s

  [15541/20519] intraday_5021.csv.gz  in=404,105,941 out=113,176,626 elapsed=230.2s

  [15542/20519] intraday_5022.csv.gz  in=404,249,819 out=113,176,626 elapsed=230.2s

  [15543/20519] intraday_5023.csv.gz  in=404,387,406 out=113,176,626 elapsed=230.3s

  [15544/20519] intraday_5024.csv.gz  in=404,520,634 out=113,176,626 elapsed=230.3s

  [15545/20519] intraday_5026.csv.gz  in=404,690,111 out=113,176,626 elapsed=230.4s

  [15546/20519] intraday_5025.csv.gz  in=404,881,779 out=113,176,626 elapsed=230.4s

  [15547/20519] intraday_5028.csv.gz  in=405,033,649 out=113,176,626 elapsed=230.4s

  [15548/20519] intraday_5027.csv.gz  in=405,204,692 out=113,176,626 elapsed=230.4s

  [15549/20519] intraday_5029.csv.gz  in=405,354,954 out=113,176,626 elapsed=230.5s

  [15550/20519] intraday_5030.csv.gz  in=405,506,581 out=113,176,626 elapsed=230.5s

  [15551/20519] intraday_5031.csv.gz  in=405,658,914 out=113,176,626 elapsed=230.6s

  [15552/20519] intraday_5032.csv.gz  in=405,797,664 out=113,176,626 elapsed=230.6s

  [15553/20519] intraday_5033.csv.gz  in=405,968,681 out=113,176,626 elapsed=230.6s

  [15554/20519] intraday_5034.csv.gz  in=406,108,988 out=113,176,626 elapsed=230.7s

  [15555/20519] intraday_5037.csv.gz  in=406,265,591 out=113,176,626 elapsed=230.8s

  [15556/20519] intraday_5036.csv.gz  in=406,408,705 out=113,176,626 elapsed=230.8s

  [15557/20519] intraday_5035.csv.gz  in=406,568,629 out=113,176,626 elapsed=230.8s

  [15558/20519] intraday_5038.csv.gz  in=406,718,144 out=113,176,626 elapsed=230.8s

  [15559/20519] intraday_5040.csv.gz  in=406,840,286 out=113,176,626 elapsed=230.9s

  [15560/20519] intraday_5039.csv.gz  in=407,005,833 out=113,176,626 elapsed=230.9s

  [15561/20519] intraday_5041.csv.gz  in=407,152,330 out=113,176,626 elapsed=230.9s

  [15562/20519] intraday_5042.csv.gz  in=407,302,677 out=113,176,626 elapsed=230.9s

  [15563/20519] intraday_5044.csv.gz  in=407,482,199 out=113,176,626 elapsed=231.0s

  [15564/20519] intraday_5043.csv.gz  in=407,689,714 out=113,176,626 elapsed=231.1s

  [15565/20519] intraday_5045.csv.gz  in=407,852,880 out=113,176,626 elapsed=231.1s

  [15566/20519] intraday_5046.csv.gz  in=408,003,318 out=113,176,626 elapsed=231.1s

  [15567/20519] intraday_5047.csv.gz  in=408,148,972 out=113,176,626 elapsed=231.2s

  [15568/20519] intraday_5050.csv.gz  in=408,291,758 out=113,176,626 elapsed=231.2s

  [15569/20519] intraday_5048.csv.gz  in=408,470,185 out=113,176,626 elapsed=231.2s

  [15570/20519] intraday_5049.csv.gz  in=408,680,465 out=113,176,626 elapsed=231.2s

  [15571/20519] intraday_5051.csv.gz  in=408,853,644 out=113,176,626 elapsed=231.3s

  [15572/20519] intraday_5052.csv.gz  in=409,027,813 out=113,176,626 elapsed=231.3s

  [15573/20519] intraday_5053.csv.gz  in=409,207,768 out=113,176,626 elapsed=231.4s

  [15574/20519] intraday_5054.csv.gz  in=409,379,102 out=113,176,626 elapsed=231.4s

  [15575/20519] intraday_5055.csv.gz  in=409,532,782 out=113,176,626 elapsed=231.5s

  [15576/20519] intraday_5056.csv.gz  in=409,693,367 out=113,176,626 elapsed=231.5s

  [15577/20519] intraday_5057.csv.gz  in=409,832,273 out=113,176,626 elapsed=231.5s

  [15578/20519] intraday_5059.csv.gz  in=409,982,888 out=113,176,626 elapsed=231.6s

  [15579/20519] intraday_5058.csv.gz  in=410,174,058 out=113,176,626 elapsed=231.6s

  [15580/20519] intraday_5060.csv.gz  in=410,339,137 out=113,176,626 elapsed=231.6s

  [15581/20519] intraday_5061.csv.gz  in=410,509,949 out=113,176,626 elapsed=231.7s

  [15582/20519] intraday_5063.csv.gz  in=410,651,280 out=113,176,626 elapsed=231.7s

  [15583/20519] intraday_5062.csv.gz  in=410,830,885 out=113,176,626 elapsed=231.7s

  [15584/20519] intraday_5064.csv.gz  in=410,991,340 out=113,176,626 elapsed=231.8s

  [15585/20519] intraday_5065.csv.gz  in=411,189,775 out=113,176,626 elapsed=231.8s

  [15586/20519] intraday_5066.csv.gz  in=411,331,542 out=113,176,626 elapsed=231.8s

  [15587/20519] intraday_5067.csv.gz  in=411,481,503 out=113,176,626 elapsed=231.9s

  [15588/20519] intraday_5068.csv.gz  in=411,682,186 out=113,176,626 elapsed=231.9s

  [15589/20519] intraday_5070.csv.gz  in=411,827,836 out=113,176,626 elapsed=232.0s

  [15590/20519] intraday_5069.csv.gz  in=412,004,542 out=113,176,626 elapsed=232.0s

  [15591/20519] intraday_5071.csv.gz  in=412,171,540 out=113,176,626 elapsed=232.0s

  [15592/20519] intraday_5072.csv.gz  in=412,345,231 out=113,176,626 elapsed=232.1s

  [15593/20519] intraday_5073.csv.gz  in=412,506,855 out=113,176,626 elapsed=232.1s

  [15594/20519] intraday_5075.csv.gz  in=412,677,877 out=113,176,626 elapsed=232.2s

  [15595/20519] intraday_5074.csv.gz  in=412,895,950 out=113,176,626 elapsed=232.2s

  [15596/20519] intraday_5076.csv.gz  in=413,086,504 out=113,176,626 elapsed=232.2s

  [15597/20519] intraday_5077.csv.gz  in=413,288,973 out=113,176,626 elapsed=232.3s

  [15598/20519] intraday_5078.csv.gz  in=413,458,390 out=113,176,626 elapsed=232.3s

  [15599/20519] intraday_5079.csv.gz  in=413,614,691 out=113,176,626 elapsed=232.3s

  [15600/20519] intraday_5080.csv.gz  in=413,758,262 out=113,176,626 elapsed=232.3s

  [15601/20519] intraday_5081.csv.gz  in=413,914,764 out=113,176,626 elapsed=232.4s

  [15602/20519] intraday_5082.csv.gz  in=414,057,264 out=113,176,626 elapsed=232.4s

  [15603/20519] intraday_5083.csv.gz  in=414,216,507 out=113,176,626 elapsed=232.5s

  [15604/20519] intraday_5084.csv.gz  in=414,382,210 out=113,176,626 elapsed=232.5s

  [15605/20519] intraday_5086.csv.gz  in=414,571,400 out=113,176,626 elapsed=232.6s

  [15606/20519] intraday_5085.csv.gz  in=414,746,295 out=113,176,626 elapsed=232.6s

  [15607/20519] intraday_5087.csv.gz  in=414,903,797 out=113,176,626 elapsed=232.6s

  [15608/20519] intraday_5088.csv.gz  in=415,060,957 out=113,176,626 elapsed=232.6s

  [15609/20519] intraday_5089.csv.gz  in=415,231,964 out=113,176,626 elapsed=232.8s

  [15610/20519] intraday_5090.csv.gz  in=415,391,429 out=113,176,626 elapsed=232.8s

  [15611/20519] intraday_5091.csv.gz  in=415,551,834 out=113,176,626 elapsed=232.8s

  [15612/20519] intraday_5092.csv.gz  in=415,737,423 out=113,176,626 elapsed=232.8s

  [15613/20519] intraday_5093.csv.gz  in=415,900,504 out=113,176,626 elapsed=232.9s

  [15614/20519] intraday_5094.csv.gz  in=416,073,091 out=113,176,626 elapsed=233.0s

  [15615/20519] intraday_5095.csv.gz  in=416,236,592 out=113,176,626 elapsed=233.0s

  [15616/20519] intraday_5096.csv.gz  in=416,371,294 out=113,176,626 elapsed=233.0s

  [15617/20519] intraday_5097.csv.gz  in=416,518,809 out=113,176,626 elapsed=233.0s

  [15618/20519] intraday_5100.csv.gz  in=416,627,584 out=113,176,626 elapsed=233.1s

  [15619/20519] intraday_5098.csv.gz  in=416,775,274 out=113,176,626 elapsed=233.1s

  [15620/20519] intraday_5103.csv.gz  in=416,790,652 out=113,176,626 elapsed=233.1s

  [15621/20519] intraday_5099.csv.gz  in=416,970,606 out=113,176,626 elapsed=233.1s

  [15622/20519] intraday_5104.csv.gz  in=416,982,926 out=113,176,626 elapsed=233.1s

  [15623/20519] intraday_5101.csv.gz  in=417,096,887 out=113,176,626 elapsed=233.2s

  [15624/20519] intraday_5105.csv.gz  in=417,110,752 out=113,176,626 elapsed=233.2s

  [15625/20519] intraday_5102.csv.gz  in=417,223,541 out=113,176,626 elapsed=233.2s

  [15626/20519] intraday_5106.csv.gz  in=417,234,714 out=113,176,626 elapsed=233.2s

  [15627/20519] intraday_5107.csv.gz  in=417,248,106 out=113,176,626 elapsed=233.2s

  [15628/20519] intraday_5109.csv.gz  in=417,261,806 out=113,176,626 elapsed=233.2s

  [15629/20519] intraday_5110.csv.gz  in=417,273,447 out=113,176,626 elapsed=233.2s

  [15630/20519] intraday_5111.csv.gz  in=417,287,345 out=113,176,626 elapsed=233.3s

  [15631/20519] intraday_5108.csv.gz  in=417,304,011 out=113,176,626 elapsed=233.3s

  [15632/20519] intraday_5112.csv.gz  in=417,317,353 out=113,176,626 elapsed=233.3s

  [15633/20519] intraday_5113.csv.gz  in=417,331,285 out=113,176,626 elapsed=233.3s

  [15634/20519] intraday_5115.csv.gz  in=417,344,268 out=113,176,626 elapsed=233.3s

  [15635/20519] intraday_5114.csv.gz  in=417,357,405 out=113,176,626 elapsed=233.3s

  [15636/20519] intraday_5117.csv.gz  in=417,367,504 out=113,176,626 elapsed=233.3s

  [15637/20519] intraday_5116.csv.gz  in=417,378,520 out=113,176,626 elapsed=233.3s

  [15638/20519] intraday_5120.csv.gz  in=417,391,801 out=113,176,626 elapsed=233.3s

  [15639/20519] intraday_5118.csv.gz  in=417,401,209 out=113,176,626 elapsed=233.4s

  [15640/20519] intraday_5119.csv.gz  in=417,421,441 out=113,176,626 elapsed=233.4s

  [15641/20519] intraday_5121.csv.gz  in=417,434,052 out=113,176,626 elapsed=233.4s

  [15642/20519] intraday_5122.csv.gz  in=417,445,942 out=113,176,626 elapsed=233.4s

  [15643/20519] intraday_5123.csv.gz  in=417,467,365 out=113,176,626 elapsed=233.4s

  [15644/20519] intraday_5124.csv.gz  in=417,481,216 out=113,176,626 elapsed=233.4s

  [15645/20519] intraday_5125.csv.gz  in=417,492,304 out=113,176,626 elapsed=233.4s

  [15646/20519] intraday_5126.csv.gz  in=417,504,392 out=113,176,626 elapsed=233.4s

  [15647/20519] intraday_5127.csv.gz  in=417,517,511 out=113,176,626 elapsed=233.4s

  [15648/20519] intraday_5129.csv.gz  in=417,529,834 out=113,176,626 elapsed=233.4s

  [15649/20519] intraday_5130.csv.gz  in=417,541,859 out=113,176,626 elapsed=233.4s

  [15650/20519] intraday_5128.csv.gz  in=417,553,159 out=113,176,626 elapsed=233.5s

  [15651/20519] intraday_5131.csv.gz  in=417,567,067 out=113,176,626 elapsed=233.5s

  [15652/20519] intraday_5133.csv.gz  in=417,583,135 out=113,176,626 elapsed=233.5s

  [15653/20519] intraday_5134.csv.gz  in=417,594,049 out=113,176,626 elapsed=233.5s

  [15654/20519] intraday_5132.csv.gz  in=417,609,057 out=113,176,626 elapsed=233.5s

  [15655/20519] intraday_5136.csv.gz  in=417,621,190 out=113,176,626 elapsed=233.5s

  [15656/20519] intraday_5135.csv.gz  in=417,633,526 out=113,176,626 elapsed=233.5s

  [15657/20519] intraday_5138.csv.gz  in=417,644,417 out=113,176,626 elapsed=233.6s

  [15658/20519] intraday_5137.csv.gz  in=417,659,687 out=113,176,626 elapsed=233.6s

  [15659/20519] intraday_5142.csv.gz  in=417,672,330 out=113,176,626 elapsed=233.6s

  [15660/20519] intraday_5140.csv.gz  in=417,685,231 out=113,176,626 elapsed=233.6s

  [15661/20519] intraday_5139.csv.gz  in=417,697,965 out=113,176,626 elapsed=233.6s

  [15662/20519] intraday_5141.csv.gz  in=417,720,788 out=113,176,626 elapsed=233.6s

  [15663/20519] intraday_5144.csv.gz  in=417,732,734 out=113,176,626 elapsed=233.6s

  [15664/20519] intraday_5145.csv.gz  in=417,746,020 out=113,176,626 elapsed=233.7s

  [15665/20519] intraday_5146.csv.gz  in=417,758,831 out=113,176,626 elapsed=233.7s

  [15666/20519] intraday_5143.csv.gz  in=417,771,714 out=113,176,626 elapsed=233.7s

  [15667/20519] intraday_5147.csv.gz  in=417,785,287 out=113,176,626 elapsed=233.7s

  [15668/20519] intraday_5148.csv.gz  in=417,798,332 out=113,176,626 elapsed=233.7s

  [15669/20519] intraday_5149.csv.gz  in=417,810,131 out=113,176,626 elapsed=233.7s

  [15670/20519] intraday_5151.csv.gz  in=417,823,892 out=113,176,626 elapsed=233.7s

  [15671/20519] intraday_5150.csv.gz  in=417,835,906 out=113,176,626 elapsed=233.7s

  [15672/20519] intraday_5152.csv.gz  in=417,846,808 out=113,176,626 elapsed=233.7s

  [15673/20519] intraday_5155.csv.gz  in=417,857,448 out=113,176,626 elapsed=233.8s

  [15674/20519] intraday_5153.csv.gz  in=417,868,866 out=113,176,626 elapsed=233.8s

  [15675/20519] intraday_5154.csv.gz  in=417,882,853 out=113,176,626 elapsed=233.8s

  [15676/20519] intraday_5156.csv.gz  in=417,894,944 out=113,176,626 elapsed=233.8s

  [15677/20519] intraday_5157.csv.gz  in=417,908,332 out=113,176,626 elapsed=233.8s

  [15678/20519] intraday_5159.csv.gz  in=417,921,737 out=113,176,626 elapsed=233.8s

  [15679/20519] intraday_5158.csv.gz  in=417,935,495 out=113,176,626 elapsed=233.8s

  [15680/20519] intraday_5160.csv.gz  in=417,947,642 out=113,176,626 elapsed=233.8s

  [15681/20519] intraday_5161.csv.gz  in=417,961,259 out=113,176,626 elapsed=233.8s

  [15682/20519] intraday_5163.csv.gz  in=417,974,221 out=113,176,626 elapsed=233.8s

  [15683/20519] intraday_5162.csv.gz  in=417,986,152 out=113,176,626 elapsed=233.8s

  [15684/20519] intraday_5164.csv.gz  in=417,997,574 out=113,176,626 elapsed=233.9s

  [15685/20519] intraday_5165.csv.gz  in=418,008,308 out=113,176,626 elapsed=233.9s

  [15686/20519] intraday_5166.csv.gz  in=418,019,492 out=113,176,626 elapsed=233.9s

  [15687/20519] intraday_5167.csv.gz  in=418,035,951 out=113,176,626 elapsed=233.9s

  [15688/20519] intraday_5168.csv.gz  in=418,048,565 out=113,176,626 elapsed=233.9s

  [15689/20519] intraday_5169.csv.gz  in=418,062,337 out=113,176,626 elapsed=233.9s

  [15690/20519] intraday_5170.csv.gz  in=418,074,275 out=113,176,626 elapsed=233.9s

  [15691/20519] intraday_5171.csv.gz  in=418,084,168 out=113,176,626 elapsed=233.9s

  [15692/20519] intraday_5172.csv.gz  in=418,095,803 out=113,176,626 elapsed=233.9s

  [15693/20519] intraday_5174.csv.gz  in=418,108,281 out=113,176,626 elapsed=234.0s

  [15694/20519] intraday_5175.csv.gz  in=418,121,777 out=113,176,626 elapsed=234.0s

  [15695/20519] intraday_5173.csv.gz  in=418,133,964 out=113,176,626 elapsed=234.0s

  [15696/20519] intraday_5176.csv.gz  in=418,146,770 out=113,176,626 elapsed=234.0s

  [15697/20519] intraday_5177.csv.gz  in=418,159,865 out=113,176,626 elapsed=234.0s

  [15698/20519] intraday_5179.csv.gz  in=418,172,991 out=113,176,626 elapsed=234.0s

  [15699/20519] intraday_5178.csv.gz  in=418,187,776 out=113,176,626 elapsed=234.0s

  [15700/20519] intraday_5180.csv.gz  in=418,199,465 out=113,176,626 elapsed=234.0s

  [15701/20519] intraday_5181.csv.gz  in=418,212,405 out=113,176,626 elapsed=234.0s

  [15702/20519] intraday_5182.csv.gz  in=418,222,562 out=113,176,626 elapsed=234.0s

  [15703/20519] intraday_5184.csv.gz  in=418,235,145 out=113,176,626 elapsed=234.0s

  [15704/20519] intraday_5183.csv.gz  in=418,247,238 out=113,176,626 elapsed=234.1s

  [15705/20519] intraday_5186.csv.gz  in=418,260,979 out=113,176,626 elapsed=234.1s

  [15706/20519] intraday_5185.csv.gz  in=418,276,288 out=113,176,626 elapsed=234.1s

  [15707/20519] intraday_5187.csv.gz  in=418,288,725 out=113,176,626 elapsed=234.1s

  [15708/20519] intraday_5188.csv.gz  in=418,300,288 out=113,176,626 elapsed=234.1s

  [15709/20519] intraday_5189.csv.gz  in=418,311,442 out=113,176,626 elapsed=234.1s

  [15710/20519] intraday_5190.csv.gz  in=418,325,263 out=113,176,626 elapsed=234.1s

  [15711/20519] intraday_5191.csv.gz  in=418,342,665 out=113,176,626 elapsed=234.1s

  [15712/20519] intraday_5192.csv.gz  in=418,354,087 out=113,176,626 elapsed=234.1s

  [15713/20519] intraday_5193.csv.gz  in=418,367,842 out=113,176,626 elapsed=234.1s

  [15714/20519] intraday_5194.csv.gz  in=418,381,478 out=113,176,626 elapsed=234.1s

  [15715/20519] intraday_5195.csv.gz  in=418,395,900 out=113,176,626 elapsed=234.2s

  [15716/20519] intraday_5198.csv.gz  in=418,408,808 out=113,176,626 elapsed=234.2s

  [15717/20519] intraday_5197.csv.gz  in=418,425,321 out=113,176,626 elapsed=234.2s

  [15718/20519] intraday_5196.csv.gz  in=418,438,712 out=113,176,626 elapsed=234.2s

  [15719/20519] intraday_5199.csv.gz  in=418,449,022 out=113,176,626 elapsed=234.2s

  [15720/20519] intraday_5201.csv.gz  in=418,462,018 out=113,176,626 elapsed=234.2s

  [15721/20519] intraday_5200.csv.gz  in=418,476,171 out=113,176,626 elapsed=234.2s

  [15722/20519] intraday_5202.csv.gz  in=418,488,976 out=113,176,626 elapsed=234.2s

  [15723/20519] intraday_5204.csv.gz  in=418,504,177 out=113,176,626 elapsed=234.2s

  [15724/20519] intraday_5206.csv.gz  in=418,517,289 out=113,176,626 elapsed=234.3s

  [15725/20519] intraday_5203.csv.gz  in=418,530,454 out=113,176,626 elapsed=234.3s

  [15726/20519] intraday_5205.csv.gz  in=418,541,201 out=113,176,626 elapsed=234.3s

  [15727/20519] intraday_5208.csv.gz  in=418,551,289 out=113,176,626 elapsed=234.3s

  [15728/20519] intraday_5210.csv.gz  in=418,566,595 out=113,176,626 elapsed=234.3s

  [15729/20519] intraday_5209.csv.gz  in=418,578,839 out=113,176,626 elapsed=234.3s

  [15730/20519] intraday_5207.csv.gz  in=418,596,190 out=113,176,626 elapsed=234.3s

  [15731/20519] intraday_5211.csv.gz  in=418,610,255 out=113,176,626 elapsed=234.3s

  [15732/20519] intraday_5213.csv.gz  in=418,622,942 out=113,176,626 elapsed=234.3s

  [15733/20519] intraday_5214.csv.gz  in=418,636,030 out=113,176,626 elapsed=234.3s

  [15734/20519] intraday_5212.csv.gz  in=418,647,390 out=113,176,626 elapsed=234.3s

  [15735/20519] intraday_5216.csv.gz  in=418,664,445 out=113,176,626 elapsed=234.4s

  [15736/20519] intraday_5215.csv.gz  in=418,677,181 out=113,176,626 elapsed=234.4s

  [15737/20519] intraday_5218.csv.gz  in=418,691,596 out=113,176,626 elapsed=234.4s

  [15738/20519] intraday_5217.csv.gz  in=418,704,519 out=113,176,626 elapsed=234.4s

  [15739/20519] intraday_5221.csv.gz  in=418,716,337 out=113,176,626 elapsed=234.4s

  [15740/20519] intraday_5220.csv.gz  in=418,730,544 out=113,176,626 elapsed=234.4s

  [15741/20519] intraday_5222.csv.gz  in=418,741,952 out=113,176,626 elapsed=234.4s

  [15742/20519] intraday_5219.csv.gz  in=418,757,546 out=113,176,626 elapsed=234.4s

  [15743/20519] intraday_5223.csv.gz  in=418,769,753 out=113,176,626 elapsed=234.4s

  [15744/20519] intraday_5225.csv.gz  in=418,782,457 out=113,176,626 elapsed=234.4s

  [15745/20519] intraday_5226.csv.gz  in=418,795,300 out=113,176,626 elapsed=234.4s

  [15746/20519] intraday_5224.csv.gz  in=418,806,108 out=113,176,626 elapsed=234.5s

  [15747/20519] intraday_5229.csv.gz  in=418,817,760 out=113,176,626 elapsed=234.5s

  [15748/20519] intraday_5227.csv.gz  in=418,837,411 out=113,176,626 elapsed=234.5s

  [15749/20519] intraday_5228.csv.gz  in=418,852,998 out=113,176,626 elapsed=234.5s

  [15750/20519] intraday_5230.csv.gz  in=418,864,823 out=113,176,626 elapsed=234.5s

  [15751/20519] intraday_5232.csv.gz  in=418,876,855 out=113,176,626 elapsed=234.5s

  [15752/20519] intraday_5231.csv.gz  in=418,890,598 out=113,176,626 elapsed=234.5s

  [15753/20519] intraday_5233.csv.gz  in=418,902,850 out=113,176,626 elapsed=234.5s

  [15754/20519] intraday_5237.csv.gz  in=418,915,221 out=113,176,626 elapsed=234.6s

  [15755/20519] intraday_5234.csv.gz  in=418,930,635 out=113,176,626 elapsed=234.6s

  [15756/20519] intraday_5235.csv.gz  in=418,943,894 out=113,176,626 elapsed=234.6s

  [15757/20519] intraday_5236.csv.gz  in=418,958,001 out=113,176,626 elapsed=234.6s

  [15758/20519] intraday_5238.csv.gz  in=418,971,324 out=113,176,626 elapsed=234.6s

  [15759/20519] intraday_5240.csv.gz  in=418,983,247 out=113,176,626 elapsed=234.7s

  [15760/20519] intraday_5241.csv.gz  in=418,997,732 out=113,176,626 elapsed=234.7s

  [15761/20519] intraday_5242.csv.gz  in=419,006,570 out=113,176,626 elapsed=234.7s

  [15762/20519] intraday_5239.csv.gz  in=419,020,160 out=113,176,626 elapsed=234.7s

  [15763/20519] intraday_5243.csv.gz  in=419,031,943 out=113,176,626 elapsed=234.7s

  [15764/20519] intraday_5244.csv.gz  in=419,040,946 out=113,176,626 elapsed=234.7s

  [15765/20519] intraday_5245.csv.gz  in=419,057,181 out=113,176,626 elapsed=234.7s

  [15766/20519] intraday_5246.csv.gz  in=419,070,350 out=113,176,626 elapsed=234.7s

  [15767/20519] intraday_5247.csv.gz  in=419,085,008 out=113,176,626 elapsed=234.7s

  [15768/20519] intraday_5248.csv.gz  in=419,096,261 out=113,176,626 elapsed=234.7s

  [15769/20519] intraday_5249.csv.gz  in=419,109,589 out=113,176,626 elapsed=234.7s

  [15770/20519] intraday_5251.csv.gz  in=419,123,732 out=113,176,626 elapsed=234.8s

  [15771/20519] intraday_5250.csv.gz  in=419,140,767 out=113,176,626 elapsed=234.8s

  [15772/20519] intraday_5252.csv.gz  in=419,152,889 out=113,176,626 elapsed=234.8s

  [15773/20519] intraday_5253.csv.gz  in=419,167,226 out=113,176,626 elapsed=234.8s

  [15774/20519] intraday_5254.csv.gz  in=419,181,010 out=113,176,626 elapsed=234.8s

  [15775/20519] intraday_5255.csv.gz  in=419,194,803 out=113,176,626 elapsed=234.8s

  [15776/20519] intraday_5256.csv.gz  in=419,208,602 out=113,176,626 elapsed=234.8s

  [15777/20519] intraday_5257.csv.gz  in=419,221,811 out=113,176,626 elapsed=234.8s

  [15778/20519] intraday_5260.csv.gz  in=419,231,718 out=113,176,626 elapsed=234.8s

  [15779/20519] intraday_5261.csv.gz  in=419,247,203 out=113,176,626 elapsed=234.8s

  [15780/20519] intraday_5259.csv.gz  in=419,258,511 out=113,176,626 elapsed=234.9s

  [15781/20519] intraday_5258.csv.gz  in=419,270,672 out=113,176,626 elapsed=234.9s

  [15782/20519] intraday_5262.csv.gz  in=419,284,114 out=113,176,626 elapsed=234.9s

  [15783/20519] intraday_5264.csv.gz  in=419,296,496 out=113,176,626 elapsed=234.9s

  [15784/20519] intraday_5263.csv.gz  in=419,308,206 out=113,176,626 elapsed=234.9s

  [15785/20519] intraday_5265.csv.gz  in=419,320,691 out=113,176,626 elapsed=234.9s

  [15786/20519] intraday_5266.csv.gz  in=419,334,721 out=113,176,626 elapsed=234.9s

  [15787/20519] intraday_5267.csv.gz  in=419,346,416 out=113,176,626 elapsed=234.9s

  [15788/20519] intraday_5269.csv.gz  in=419,359,552 out=113,176,626 elapsed=234.9s

  [15789/20519] intraday_5268.csv.gz  in=419,372,155 out=113,176,626 elapsed=234.9s

  [15790/20519] intraday_5270.csv.gz  in=419,383,426 out=113,176,626 elapsed=234.9s

  [15791/20519] intraday_5271.csv.gz  in=419,395,596 out=113,176,626 elapsed=235.0s

  [15792/20519] intraday_5272.csv.gz  in=419,406,685 out=113,176,626 elapsed=235.0s

  [15793/20519] intraday_5274.csv.gz  in=419,421,502 out=113,176,626 elapsed=235.0s

  [15794/20519] intraday_5273.csv.gz  in=419,436,681 out=113,176,626 elapsed=235.0s

  [15795/20519] intraday_5276.csv.gz  in=419,448,002 out=113,176,626 elapsed=235.0s

  [15796/20519] intraday_5275.csv.gz  in=419,464,612 out=113,176,626 elapsed=235.0s

  [15797/20519] intraday_5277.csv.gz  in=419,476,829 out=113,176,626 elapsed=235.0s

  [15798/20519] intraday_5278.csv.gz  in=419,489,138 out=113,176,626 elapsed=235.0s

  [15799/20519] intraday_5280.csv.gz  in=419,500,116 out=113,176,626 elapsed=235.0s

  [15800/20519] intraday_5282.csv.gz  in=419,513,315 out=113,176,626 elapsed=235.1s

  [15801/20519] intraday_5279.csv.gz  in=419,528,345 out=113,176,626 elapsed=235.1s

  [15802/20519] intraday_5281.csv.gz  in=419,541,031 out=113,176,626 elapsed=235.1s

  [15803/20519] intraday_5283.csv.gz  in=419,552,050 out=113,176,626 elapsed=235.1s

  [15804/20519] intraday_5284.csv.gz  in=419,563,989 out=113,176,626 elapsed=235.1s

  [15805/20519] intraday_5285.csv.gz  in=419,577,003 out=113,176,626 elapsed=235.1s

  [15806/20519] intraday_5286.csv.gz  in=419,589,550 out=113,176,626 elapsed=235.1s

  [15807/20519] intraday_5287.csv.gz  in=419,603,295 out=113,176,626 elapsed=235.1s

  [15808/20519] intraday_5290.csv.gz  in=419,616,623 out=113,176,626 elapsed=235.1s

  [15809/20519] intraday_5288.csv.gz  in=419,630,209 out=113,176,626 elapsed=235.1s

  [15810/20519] intraday_5289.csv.gz  in=419,643,434 out=113,176,626 elapsed=235.1s

  [15811/20519] intraday_5292.csv.gz  in=419,655,675 out=113,176,626 elapsed=235.1s

  [15812/20519] intraday_5291.csv.gz  in=419,668,221 out=113,176,626 elapsed=235.2s

  [15813/20519] intraday_5293.csv.gz  in=419,681,748 out=113,176,626 elapsed=235.2s

  [15814/20519] intraday_5294.csv.gz  in=419,692,830 out=113,176,626 elapsed=235.2s

  [15815/20519] intraday_5296.csv.gz  in=419,709,373 out=113,176,626 elapsed=235.2s

  [15816/20519] intraday_5295.csv.gz  in=419,721,462 out=113,176,626 elapsed=235.2s

  [15817/20519] intraday_5297.csv.gz  in=419,731,113 out=113,176,626 elapsed=235.2s

  [15818/20519] intraday_5298.csv.gz  in=419,742,728 out=113,176,626 elapsed=235.2s

  [15819/20519] intraday_5299.csv.gz  in=419,756,350 out=113,176,626 elapsed=235.2s

  [15820/20519] intraday_5300.csv.gz  in=419,769,612 out=113,176,626 elapsed=235.2s

  [15821/20519] intraday_5301.csv.gz  in=419,783,829 out=113,176,626 elapsed=235.2s

  [15822/20519] intraday_5302.csv.gz  in=419,795,698 out=113,176,626 elapsed=235.3s

  [15823/20519] intraday_5304.csv.gz  in=419,807,648 out=113,176,626 elapsed=235.3s

  [15824/20519] intraday_5303.csv.gz  in=419,821,346 out=113,176,626 elapsed=235.3s

  [15825/20519] intraday_5306.csv.gz  in=419,833,347 out=113,176,626 elapsed=235.3s

  [15826/20519] intraday_5305.csv.gz  in=419,846,017 out=113,176,626 elapsed=235.3s

  [15827/20519] intraday_5308.csv.gz  in=419,856,634 out=113,176,626 elapsed=235.3s

  [15828/20519] intraday_5307.csv.gz  in=419,867,933 out=113,176,626 elapsed=235.3s

  [15829/20519] intraday_5310.csv.gz  in=419,881,699 out=113,176,626 elapsed=235.3s

  [15830/20519] intraday_5309.csv.gz  in=419,897,751 out=113,176,626 elapsed=235.3s

  [15831/20519] intraday_5311.csv.gz  in=419,911,940 out=113,176,626 elapsed=235.3s

  [15832/20519] intraday_5312.csv.gz  in=419,923,997 out=113,176,626 elapsed=235.3s

  [15833/20519] intraday_5313.csv.gz  in=419,934,606 out=113,176,626 elapsed=235.3s

  [15834/20519] intraday_5315.csv.gz  in=419,947,260 out=113,176,626 elapsed=235.3s

  [15835/20519] intraday_5314.csv.gz  in=419,959,355 out=113,176,626 elapsed=235.3s

  [15836/20519] intraday_5316.csv.gz  in=419,971,245 out=113,176,626 elapsed=235.4s

  [15837/20519] intraday_5317.csv.gz  in=419,984,496 out=113,176,626 elapsed=235.4s

  [15838/20519] intraday_5318.csv.gz  in=419,996,851 out=113,176,626 elapsed=235.4s

  [15839/20519] intraday_5319.csv.gz  in=420,009,756 out=113,176,626 elapsed=235.4s

  [15840/20519] intraday_5320.csv.gz  in=420,020,903 out=113,176,626 elapsed=235.4s

  [15841/20519] intraday_5321.csv.gz  in=420,034,957 out=113,176,626 elapsed=235.4s

  [15842/20519] intraday_5322.csv.gz  in=420,046,557 out=113,176,626 elapsed=235.4s

  [15843/20519] intraday_5323.csv.gz  in=420,059,476 out=113,176,626 elapsed=235.4s

  [15844/20519] intraday_5324.csv.gz  in=420,070,038 out=113,176,626 elapsed=235.4s

  [15845/20519] intraday_5326.csv.gz  in=420,083,120 out=113,176,626 elapsed=235.4s

  [15846/20519] intraday_5325.csv.gz  in=420,096,182 out=113,176,626 elapsed=235.4s

  [15847/20519] intraday_5327.csv.gz  in=420,112,328 out=113,176,626 elapsed=235.5s

  [15848/20519] intraday_5328.csv.gz  in=420,126,631 out=113,176,626 elapsed=235.5s

  [15849/20519] intraday_5330.csv.gz  in=420,138,380 out=113,176,626 elapsed=235.5s

  [15850/20519] intraday_5331.csv.gz  in=420,150,079 out=113,176,626 elapsed=235.5s

  [15851/20519] intraday_5329.csv.gz  in=420,163,086 out=113,176,626 elapsed=235.5s

  [15852/20519] intraday_5332.csv.gz  in=420,177,144 out=113,176,626 elapsed=235.5s

  [15853/20519] intraday_5334.csv.gz  in=420,189,030 out=113,176,626 elapsed=235.6s

  [15854/20519] intraday_5335.csv.gz  in=420,202,809 out=113,176,626 elapsed=235.6s

  [15855/20519] intraday_5333.csv.gz  in=420,220,817 out=113,176,626 elapsed=235.6s

  [15856/20519] intraday_5336.csv.gz  in=420,233,567 out=113,176,626 elapsed=235.6s

  [15857/20519] intraday_5340.csv.gz  in=420,247,134 out=113,176,626 elapsed=235.6s

  [15858/20519] intraday_5338.csv.gz  in=420,261,393 out=113,176,626 elapsed=235.6s

  [15859/20519] intraday_5339.csv.gz  in=420,273,799 out=113,176,626 elapsed=235.6s

  [15860/20519] intraday_5337.csv.gz  in=420,288,431 out=113,176,626 elapsed=235.6s

  [15861/20519] intraday_5342.csv.gz  in=420,302,669 out=113,176,626 elapsed=235.7s

  [15862/20519] intraday_5341.csv.gz  in=420,314,448 out=113,176,626 elapsed=235.7s

  [15863/20519] intraday_5344.csv.gz  in=420,327,438 out=113,176,626 elapsed=235.7s

  [15864/20519] intraday_5343.csv.gz  in=420,340,272 out=113,176,626 elapsed=235.7s

  [15865/20519] intraday_5347.csv.gz  in=420,351,582 out=113,176,626 elapsed=235.7s

  [15866/20519] intraday_5346.csv.gz  in=420,367,363 out=113,176,626 elapsed=235.7s

  [15867/20519] intraday_5348.csv.gz  in=420,380,595 out=113,176,626 elapsed=235.7s

  [15868/20519] intraday_5345.csv.gz  in=420,393,846 out=113,176,626 elapsed=235.7s

  [15869/20519] intraday_5350.csv.gz  in=420,404,752 out=113,176,626 elapsed=235.7s

  [15870/20519] intraday_5349.csv.gz  in=420,421,180 out=113,176,626 elapsed=235.8s

  [15871/20519] intraday_5351.csv.gz  in=420,433,346 out=113,176,626 elapsed=235.8s

  [15872/20519] intraday_5352.csv.gz  in=420,448,852 out=113,176,626 elapsed=235.8s

  [15873/20519] intraday_5353.csv.gz  in=420,463,740 out=113,176,626 elapsed=235.8s

  [15874/20519] intraday_5356.csv.gz  in=420,478,018 out=113,176,626 elapsed=235.8s

  [15875/20519] intraday_5355.csv.gz  in=420,491,595 out=113,176,626 elapsed=235.8s

  [15876/20519] intraday_5354.csv.gz  in=420,503,970 out=113,176,626 elapsed=235.8s

  [15877/20519] intraday_5357.csv.gz  in=420,519,012 out=113,176,626 elapsed=235.8s

  [15878/20519] intraday_5359.csv.gz  in=420,533,528 out=113,176,626 elapsed=235.8s

  [15879/20519] intraday_5360.csv.gz  in=420,547,643 out=113,176,626 elapsed=235.8s

  [15880/20519] intraday_5358.csv.gz  in=420,563,547 out=113,176,626 elapsed=235.8s

  [15881/20519] intraday_5363.csv.gz  in=420,576,409 out=113,176,626 elapsed=235.9s

  [15882/20519] intraday_5361.csv.gz  in=420,593,367 out=113,176,626 elapsed=235.9s

  [15883/20519] intraday_5362.csv.gz  in=420,607,363 out=113,176,626 elapsed=235.9s

  [15884/20519] intraday_5364.csv.gz  in=420,619,329 out=113,176,626 elapsed=235.9s

  [15885/20519] intraday_5365.csv.gz  in=420,632,632 out=113,176,626 elapsed=235.9s

  [15886/20519] intraday_5367.csv.gz  in=420,646,396 out=113,176,626 elapsed=235.9s

  [15887/20519] intraday_5366.csv.gz  in=420,657,526 out=113,176,626 elapsed=235.9s

  [15888/20519] intraday_5368.csv.gz  in=420,671,248 out=113,176,626 elapsed=235.9s

  [15889/20519] intraday_5370.csv.gz  in=420,687,329 out=113,176,626 elapsed=235.9s

  [15890/20519] intraday_5369.csv.gz  in=420,701,673 out=113,176,626 elapsed=235.9s

  [15891/20519] intraday_5371.csv.gz  in=420,714,353 out=113,176,626 elapsed=235.9s

  [15892/20519] intraday_5372.csv.gz  in=420,726,577 out=113,176,626 elapsed=236.0s

  [15893/20519] intraday_5373.csv.gz  in=420,741,184 out=113,176,626 elapsed=236.0s

  [15894/20519] intraday_5374.csv.gz  in=420,753,920 out=113,176,626 elapsed=236.0s

  [15895/20519] intraday_5375.csv.gz  in=420,766,437 out=113,176,626 elapsed=236.0s

  [15896/20519] intraday_5376.csv.gz  in=420,782,283 out=113,176,626 elapsed=236.0s

  [15897/20519] intraday_5377.csv.gz  in=420,796,413 out=113,176,626 elapsed=236.0s

  [15898/20519] intraday_5378.csv.gz  in=420,809,982 out=113,176,626 elapsed=236.0s

  [15899/20519] intraday_5380.csv.gz  in=420,820,932 out=113,176,626 elapsed=236.0s

  [15900/20519] intraday_5381.csv.gz  in=420,834,633 out=113,176,626 elapsed=236.0s

  [15901/20519] intraday_5379.csv.gz  in=420,847,545 out=113,176,626 elapsed=236.0s

  [15902/20519] intraday_5382.csv.gz  in=420,859,201 out=113,176,626 elapsed=236.1s

  [15903/20519] intraday_5383.csv.gz  in=420,873,654 out=113,176,626 elapsed=236.1s

  [15904/20519] intraday_5384.csv.gz  in=420,882,526 out=113,176,626 elapsed=236.1s

  [15905/20519] intraday_5385.csv.gz  in=420,894,046 out=113,176,626 elapsed=236.1s

  [15906/20519] intraday_5388.csv.gz  in=420,894,846 out=113,176,626 elapsed=236.1s

  [15907/20519] intraday_5386.csv.gz  in=420,904,404 out=113,176,626 elapsed=236.1s

  [15908/20519] intraday_5387.csv.gz  in=420,904,959 out=113,176,626 elapsed=236.1s

  [15909/20519] intraday_5389.csv.gz  in=420,906,733 out=113,176,626 elapsed=236.1s

  [15910/20519] intraday_5391.csv.gz  in=420,906,900 out=113,176,626 elapsed=236.1s

  [15911/20519] intraday_5392.csv.gz  in=420,907,658 out=113,176,626 elapsed=236.1s

  [15912/20519] intraday_5390.csv.gz  in=420,908,262 out=113,176,626 elapsed=236.1s

  [15913/20519] intraday_5393.csv.gz  in=420,908,617 out=113,176,626 elapsed=236.1s

  [15914/20519] intraday_5395.csv.gz  in=420,908,647 out=113,176,626 elapsed=236.1s

  [15915/20519] intraday_5394.csv.gz  in=420,909,040 out=113,176,626 elapsed=236.1s

  [15916/20519] intraday_5396.csv.gz  in=420,909,074 out=113,176,626 elapsed=236.1s

  [15917/20519] intraday_5397.csv.gz  in=420,924,820 out=113,176,626 elapsed=236.2s

  [15918/20519] intraday_5398.csv.gz  in=420,937,999 out=113,176,626 elapsed=236.2s

  [15919/20519] intraday_5400.csv.gz  in=420,950,267 out=113,176,626 elapsed=236.2s

  [15920/20519] intraday_5399.csv.gz  in=420,963,693 out=113,176,626 elapsed=236.2s

  [15921/20519] intraday_5401.csv.gz  in=420,976,480 out=113,176,626 elapsed=236.2s

  [15922/20519] intraday_5404.csv.gz  in=420,988,262 out=113,176,626 elapsed=236.2s

  [15923/20519] intraday_5402.csv.gz  in=421,003,530 out=113,176,626 elapsed=236.2s

  [15924/20519] intraday_5405.csv.gz  in=421,017,543 out=113,176,626 elapsed=236.2s

  [15925/20519] intraday_5403.csv.gz  in=421,031,990 out=113,176,626 elapsed=236.2s

  [15926/20519] intraday_5406.csv.gz  in=421,046,580 out=113,176,626 elapsed=236.2s

  [15927/20519] intraday_5408.csv.gz  in=421,060,315 out=113,176,626 elapsed=236.3s

  [15928/20519] intraday_5410.csv.gz  in=421,072,602 out=113,176,626 elapsed=236.3s

  [15929/20519] intraday_5407.csv.gz  in=421,086,858 out=113,176,626 elapsed=236.3s

  [15930/20519] intraday_5409.csv.gz  in=421,098,936 out=113,176,626 elapsed=236.3s

  [15931/20519] intraday_5412.csv.gz  in=421,108,395 out=113,176,626 elapsed=236.3s

  [15932/20519] intraday_5411.csv.gz  in=421,119,009 out=113,176,626 elapsed=236.3s

  [15933/20519] intraday_5414.csv.gz  in=421,132,717 out=113,176,626 elapsed=236.3s

  [15934/20519] intraday_5413.csv.gz  in=421,148,174 out=113,176,626 elapsed=236.3s

  [15935/20519] intraday_5415.csv.gz  in=421,159,794 out=113,176,626 elapsed=236.4s

  [15936/20519] intraday_5416.csv.gz  in=421,171,899 out=113,176,626 elapsed=236.4s

  [15937/20519] intraday_5417.csv.gz  in=421,185,135 out=113,176,626 elapsed=236.4s

  [15938/20519] intraday_5418.csv.gz  in=421,198,759 out=113,176,626 elapsed=236.4s

  [15939/20519] intraday_5419.csv.gz  in=421,212,042 out=113,176,626 elapsed=236.4s

  [15940/20519] intraday_5420.csv.gz  in=421,224,492 out=113,176,626 elapsed=236.4s

  [15941/20519] intraday_5421.csv.gz  in=421,237,988 out=113,176,626 elapsed=236.4s

  [15942/20519] intraday_5422.csv.gz  in=421,249,148 out=113,176,626 elapsed=236.4s

  [15943/20519] intraday_5423.csv.gz  in=421,261,611 out=113,176,626 elapsed=236.4s

  [15944/20519] intraday_5424.csv.gz  in=421,273,051 out=113,176,626 elapsed=236.4s

  [15945/20519] intraday_5426.csv.gz  in=421,288,204 out=113,176,626 elapsed=236.5s

  [15946/20519] intraday_5425.csv.gz  in=421,302,612 out=113,176,626 elapsed=236.5s

  [15947/20519] intraday_5427.csv.gz  in=421,317,996 out=113,176,626 elapsed=236.5s

  [15948/20519] intraday_5428.csv.gz  in=421,329,575 out=113,176,626 elapsed=236.5s

  [15949/20519] intraday_5429.csv.gz  in=421,341,526 out=113,176,626 elapsed=236.5s

  [15950/20519] intraday_5432.csv.gz  in=421,352,445 out=113,176,626 elapsed=236.5s

  [15951/20519] intraday_5430.csv.gz  in=421,364,832 out=113,176,626 elapsed=236.5s

  [15952/20519] intraday_5431.csv.gz  in=421,379,324 out=113,176,626 elapsed=236.5s

  [15953/20519] intraday_5434.csv.gz  in=421,392,412 out=113,176,626 elapsed=236.6s

  [15954/20519] intraday_5433.csv.gz  in=421,405,042 out=113,176,626 elapsed=236.6s

  [15955/20519] intraday_5435.csv.gz  in=421,415,939 out=113,176,626 elapsed=236.6s

  [15956/20519] intraday_5436.csv.gz  in=421,427,007 out=113,176,626 elapsed=236.6s

  [15957/20519] intraday_5437.csv.gz  in=421,440,172 out=113,176,626 elapsed=236.6s

  [15958/20519] intraday_5438.csv.gz  in=421,453,253 out=113,176,626 elapsed=236.7s

  [15959/20519] intraday_5440.csv.gz  in=421,466,602 out=113,176,626 elapsed=236.7s

  [15960/20519] intraday_5439.csv.gz  in=421,480,355 out=113,176,626 elapsed=236.7s

  [15961/20519] intraday_5441.csv.gz  in=421,493,993 out=113,176,626 elapsed=236.7s

  [15962/20519] intraday_5444.csv.gz  in=421,505,625 out=113,176,626 elapsed=236.7s

  [15963/20519] intraday_5442.csv.gz  in=421,517,974 out=113,176,626 elapsed=236.7s

  [15964/20519] intraday_5443.csv.gz  in=421,530,207 out=113,176,626 elapsed=236.7s

  [15965/20519] intraday_5445.csv.gz  in=421,542,810 out=113,176,626 elapsed=236.7s

  [15966/20519] intraday_5446.csv.gz  in=421,554,030 out=113,176,626 elapsed=236.7s

  [15967/20519] intraday_5447.csv.gz  in=421,565,989 out=113,176,626 elapsed=236.7s

  [15968/20519] intraday_5448.csv.gz  in=421,581,164 out=113,176,626 elapsed=236.7s

  [15969/20519] intraday_5450.csv.gz  in=421,592,906 out=113,176,626 elapsed=236.7s

  [15970/20519] intraday_5449.csv.gz  in=421,602,628 out=113,176,626 elapsed=236.7s

  [15971/20519] intraday_5451.csv.gz  in=421,616,908 out=113,176,626 elapsed=236.8s

  [15972/20519] intraday_5454.csv.gz  in=421,629,290 out=113,176,626 elapsed=236.8s

  [15973/20519] intraday_5453.csv.gz  in=421,644,225 out=113,176,626 elapsed=236.8s

  [15974/20519] intraday_5452.csv.gz  in=421,666,122 out=113,176,626 elapsed=236.8s

  [15975/20519] intraday_5455.csv.gz  in=421,679,375 out=113,176,626 elapsed=236.8s

  [15976/20519] intraday_5457.csv.gz  in=421,692,422 out=113,176,626 elapsed=236.8s

  [15977/20519] intraday_5456.csv.gz  in=421,705,407 out=113,176,626 elapsed=236.8s

  [15978/20519] intraday_5458.csv.gz  in=421,717,082 out=113,176,626 elapsed=236.8s

  [15979/20519] intraday_5460.csv.gz  in=421,727,489 out=113,176,626 elapsed=236.8s

  [15980/20519] intraday_5459.csv.gz  in=421,738,267 out=113,176,626 elapsed=236.8s

  [15981/20519] intraday_5462.csv.gz  in=421,751,711 out=113,176,626 elapsed=236.9s

  [15982/20519] intraday_5461.csv.gz  in=421,766,866 out=113,176,626 elapsed=236.9s

  [15983/20519] intraday_5464.csv.gz  in=421,778,752 out=113,176,626 elapsed=236.9s

  [15984/20519] intraday_5465.csv.gz  in=421,788,912 out=113,176,626 elapsed=236.9s

  [15985/20519] intraday_5463.csv.gz  in=421,803,424 out=113,176,626 elapsed=236.9s

  [15986/20519] intraday_5466.csv.gz  in=421,815,164 out=113,176,626 elapsed=236.9s

  [15987/20519] intraday_5467.csv.gz  in=421,827,614 out=113,176,626 elapsed=236.9s

  [15988/20519] intraday_5468.csv.gz  in=421,839,533 out=113,176,626 elapsed=236.9s

  [15989/20519] intraday_5469.csv.gz  in=421,853,458 out=113,176,626 elapsed=236.9s

  [15990/20519] intraday_5470.csv.gz  in=421,865,118 out=113,176,626 elapsed=237.0s

  [15991/20519] intraday_5471.csv.gz  in=421,876,749 out=113,176,626 elapsed=237.0s

  [15992/20519] intraday_5472.csv.gz  in=421,888,508 out=113,176,626 elapsed=237.0s

  [15993/20519] intraday_5473.csv.gz  in=421,902,115 out=113,176,626 elapsed=237.0s

  [15994/20519] intraday_5474.csv.gz  in=421,913,549 out=113,176,626 elapsed=237.0s

  [15995/20519] intraday_5475.csv.gz  in=421,926,818 out=113,176,626 elapsed=237.0s

  [15996/20519] intraday_5476.csv.gz  in=421,936,869 out=113,176,626 elapsed=237.0s

  [15997/20519] intraday_5479.csv.gz  in=421,953,054 out=113,176,626 elapsed=237.0s

  [15998/20519] intraday_5477.csv.gz  in=421,966,213 out=113,176,626 elapsed=237.0s

  [15999/20519] intraday_5478.csv.gz  in=421,978,255 out=113,176,626 elapsed=237.0s

  [16000/20519] intraday_5481.csv.gz  in=421,990,609 out=113,176,626 elapsed=237.1s

  [16001/20519] intraday_5480.csv.gz  in=422,004,233 out=113,176,626 elapsed=237.1s

  [16002/20519] intraday_5482.csv.gz  in=422,015,930 out=113,176,626 elapsed=237.1s

  [16003/20519] intraday_5483.csv.gz  in=422,027,614 out=113,176,626 elapsed=237.1s

  [16004/20519] intraday_5484.csv.gz  in=422,041,772 out=113,176,626 elapsed=237.1s

  [16005/20519] intraday_5487.csv.gz  in=422,055,331 out=113,176,626 elapsed=237.1s

  [16006/20519] intraday_5485.csv.gz  in=422,074,611 out=113,176,626 elapsed=237.1s

  [16007/20519] intraday_5486.csv.gz  in=422,086,747 out=113,176,626 elapsed=237.1s

  [16008/20519] intraday_5488.csv.gz  in=422,099,969 out=113,176,626 elapsed=237.1s

  [16009/20519] intraday_5489.csv.gz  in=422,114,105 out=113,176,626 elapsed=237.1s

  [16010/20519] intraday_5491.csv.gz  in=422,126,444 out=113,176,626 elapsed=237.2s

  [16011/20519] intraday_5490.csv.gz  in=422,140,210 out=113,176,626 elapsed=237.2s

  [16012/20519] intraday_5492.csv.gz  in=422,153,454 out=113,176,626 elapsed=237.2s

  [16013/20519] intraday_5493.csv.gz  in=422,164,856 out=113,176,626 elapsed=237.2s

  [16014/20519] intraday_5495.csv.gz  in=422,177,379 out=113,176,626 elapsed=237.2s

  [16015/20519] intraday_5494.csv.gz  in=422,191,845 out=113,176,626 elapsed=237.2s

  [16016/20519] intraday_5496.csv.gz  in=422,205,193 out=113,176,626 elapsed=237.2s

  [16017/20519] intraday_5497.csv.gz  in=422,235,920 out=113,176,626 elapsed=237.2s

  [16018/20519] intraday_5498.csv.gz  in=422,251,184 out=113,176,626 elapsed=237.2s

  [16019/20519] intraday_5499.csv.gz  in=422,262,690 out=113,176,626 elapsed=237.3s

  [16020/20519] intraday_5502.csv.gz  in=422,273,794 out=113,176,626 elapsed=237.3s

  [16021/20519] intraday_5501.csv.gz  in=422,290,322 out=113,176,626 elapsed=237.3s

  [16022/20519] intraday_5500.csv.gz  in=422,303,441 out=113,176,626 elapsed=237.3s

  [16023/20519] intraday_5503.csv.gz  in=422,315,675 out=113,176,626 elapsed=237.3s

  [16024/20519] intraday_5506.csv.gz  in=422,328,020 out=113,176,626 elapsed=237.3s

  [16025/20519] intraday_5504.csv.gz  in=422,344,302 out=113,176,626 elapsed=237.3s

  [16026/20519] intraday_5507.csv.gz  in=422,357,910 out=113,176,626 elapsed=237.3s

  [16027/20519] intraday_5505.csv.gz  in=422,372,699 out=113,176,626 elapsed=237.3s

  [16028/20519] intraday_5509.csv.gz  in=422,385,694 out=113,176,626 elapsed=237.4s

  [16029/20519] intraday_5508.csv.gz  in=422,399,335 out=113,176,626 elapsed=237.4s

  [16030/20519] intraday_5510.csv.gz  in=422,415,728 out=113,176,626 elapsed=237.4s

  [16031/20519] intraday_5511.csv.gz  in=422,428,667 out=113,176,626 elapsed=237.4s

  [16032/20519] intraday_5512.csv.gz  in=422,443,596 out=113,176,626 elapsed=237.4s

  [16033/20519] intraday_5514.csv.gz  in=422,457,584 out=113,176,626 elapsed=237.4s

  [16034/20519] intraday_5513.csv.gz  in=422,473,929 out=113,176,626 elapsed=237.4s

  [16035/20519] intraday_5515.csv.gz  in=422,486,086 out=113,176,626 elapsed=237.4s

  [16036/20519] intraday_5516.csv.gz  in=422,497,126 out=113,176,626 elapsed=237.4s

  [16037/20519] intraday_5517.csv.gz  in=422,511,678 out=113,176,626 elapsed=237.5s

  [16038/20519] intraday_5518.csv.gz  in=422,522,600 out=113,176,626 elapsed=237.5s

  [16039/20519] intraday_5519.csv.gz  in=422,536,042 out=113,176,626 elapsed=237.5s

  [16040/20519] intraday_5520.csv.gz  in=422,548,928 out=113,176,626 elapsed=237.5s

  [16041/20519] intraday_5522.csv.gz  in=422,561,978 out=113,176,626 elapsed=237.5s

  [16042/20519] intraday_5521.csv.gz  in=422,578,448 out=113,176,626 elapsed=237.5s

  [16043/20519] intraday_5524.csv.gz  in=422,591,597 out=113,176,626 elapsed=237.6s

  [16044/20519] intraday_5523.csv.gz  in=422,604,348 out=113,176,626 elapsed=237.6s

  [16045/20519] intraday_5525.csv.gz  in=422,617,935 out=113,176,626 elapsed=237.6s

  [16046/20519] intraday_5527.csv.gz  in=422,631,016 out=113,176,626 elapsed=237.6s

  [16047/20519] intraday_5526.csv.gz  in=422,646,438 out=113,176,626 elapsed=237.6s

  [16048/20519] intraday_5528.csv.gz  in=422,661,284 out=113,176,626 elapsed=237.6s

  [16049/20519] intraday_5529.csv.gz  in=422,676,139 out=113,176,626 elapsed=237.6s

  [16050/20519] intraday_5531.csv.gz  in=422,687,435 out=113,176,626 elapsed=237.7s

  [16051/20519] intraday_5532.csv.gz  in=422,699,214 out=113,176,626 elapsed=237.7s

  [16052/20519] intraday_5530.csv.gz  in=422,714,421 out=113,176,626 elapsed=237.7s

  [16053/20519] intraday_5533.csv.gz  in=422,728,189 out=113,176,626 elapsed=237.7s

  [16054/20519] intraday_5534.csv.gz  in=422,740,369 out=113,176,626 elapsed=237.7s

  [16055/20519] intraday_5536.csv.gz  in=422,747,984 out=113,176,626 elapsed=237.7s

  [16056/20519] intraday_5537.csv.gz  in=422,759,605 out=113,176,626 elapsed=237.7s

  [16057/20519] intraday_5539.csv.gz  in=422,774,032 out=113,176,626 elapsed=237.7s

  [16058/20519] intraday_5538.csv.gz  in=422,782,650 out=113,176,626 elapsed=237.8s

  [16059/20519] intraday_5535.csv.gz  in=422,816,332 out=113,176,626 elapsed=237.8s

  [16060/20519] intraday_5540.csv.gz  in=422,829,618 out=113,176,626 elapsed=237.8s

  [16061/20519] intraday_5542.csv.gz  in=422,841,201 out=113,176,626 elapsed=237.8s

  [16062/20519] intraday_5541.csv.gz  in=422,853,596 out=113,176,626 elapsed=237.8s

  [16063/20519] intraday_5543.csv.gz  in=422,865,912 out=113,176,626 elapsed=237.8s

  [16064/20519] intraday_5544.csv.gz  in=422,881,107 out=113,176,626 elapsed=237.8s

  [16065/20519] intraday_5545.csv.gz  in=422,896,531 out=113,176,626 elapsed=237.8s

  [16066/20519] intraday_5547.csv.gz  in=422,909,377 out=113,176,626 elapsed=237.8s

  [16067/20519] intraday_5546.csv.gz  in=422,920,903 out=113,176,626 elapsed=237.8s

  [16068/20519] intraday_5548.csv.gz  in=422,934,474 out=113,176,626 elapsed=237.8s

  [16069/20519] intraday_5549.csv.gz  in=422,947,820 out=113,176,626 elapsed=237.8s

  [16070/20519] intraday_5551.csv.gz  in=422,959,788 out=113,176,626 elapsed=237.9s

  [16071/20519] intraday_5550.csv.gz  in=422,976,735 out=113,176,626 elapsed=237.9s

  [16072/20519] intraday_5552.csv.gz  in=422,988,254 out=113,176,626 elapsed=237.9s

  [16073/20519] intraday_5553.csv.gz  in=422,998,423 out=113,176,626 elapsed=237.9s

  [16074/20519] intraday_5554.csv.gz  in=423,007,416 out=113,176,626 elapsed=237.9s

  [16075/20519] intraday_5556.csv.gz  in=423,020,933 out=113,176,626 elapsed=237.9s

  [16076/20519] intraday_5555.csv.gz  in=423,035,237 out=113,176,626 elapsed=237.9s

  [16077/20519] intraday_5557.csv.gz  in=423,045,475 out=113,176,626 elapsed=237.9s

  [16078/20519] intraday_5558.csv.gz  in=423,056,696 out=113,176,626 elapsed=237.9s

  [16079/20519] intraday_5559.csv.gz  in=423,068,724 out=113,176,626 elapsed=237.9s

  [16080/20519] intraday_5560.csv.gz  in=423,082,484 out=113,176,626 elapsed=237.9s

  [16081/20519] intraday_5561.csv.gz  in=423,095,013 out=113,176,626 elapsed=238.0s

  [16082/20519] intraday_5562.csv.gz  in=423,107,343 out=113,176,626 elapsed=238.0s

  [16083/20519] intraday_5564.csv.gz  in=423,118,407 out=113,176,626 elapsed=238.0s

  [16084/20519] intraday_5563.csv.gz  in=423,132,119 out=113,176,626 elapsed=238.0s

  [16085/20519] intraday_5566.csv.gz  in=423,143,645 out=113,176,626 elapsed=238.0s

  [16086/20519] intraday_5565.csv.gz  in=423,156,039 out=113,176,626 elapsed=238.0s

  [16087/20519] intraday_5567.csv.gz  in=423,169,065 out=113,176,626 elapsed=238.0s

  [16088/20519] intraday_5570.csv.gz  in=423,179,799 out=113,176,626 elapsed=238.0s

  [16089/20519] intraday_5568.csv.gz  in=423,194,673 out=113,176,626 elapsed=238.0s

  [16090/20519] intraday_5569.csv.gz  in=423,209,576 out=113,176,626 elapsed=238.0s

  [16091/20519] intraday_5572.csv.gz  in=423,221,658 out=113,176,626 elapsed=238.1s

  [16092/20519] intraday_5571.csv.gz  in=423,233,308 out=113,176,626 elapsed=238.1s

  [16093/20519] intraday_5573.csv.gz  in=423,247,156 out=113,176,626 elapsed=238.1s

  [16094/20519] intraday_5576.csv.gz  in=423,258,840 out=113,176,626 elapsed=238.1s

  [16095/20519] intraday_5577.csv.gz  in=423,269,506 out=113,176,626 elapsed=238.1s

  [16096/20519] intraday_5574.csv.gz  in=423,291,159 out=113,176,626 elapsed=238.1s

  [16097/20519] intraday_5575.csv.gz  in=423,302,938 out=113,176,626 elapsed=238.1s

  [16098/20519] intraday_5578.csv.gz  in=423,313,992 out=113,176,626 elapsed=238.1s

  [16099/20519] intraday_5580.csv.gz  in=423,326,355 out=113,176,626 elapsed=238.1s

  [16100/20519] intraday_5581.csv.gz  in=423,338,563 out=113,176,626 elapsed=238.1s

  [16101/20519] intraday_5579.csv.gz  in=423,355,118 out=113,176,626 elapsed=238.1s

  [16102/20519] intraday_5582.csv.gz  in=423,368,913 out=113,176,626 elapsed=238.2s

  [16103/20519] intraday_5584.csv.gz  in=423,380,802 out=113,176,626 elapsed=238.2s

  [16104/20519] intraday_5585.csv.gz  in=423,392,627 out=113,176,626 elapsed=238.2s

  [16105/20519] intraday_5583.csv.gz  in=423,405,286 out=113,176,626 elapsed=238.2s

  [16106/20519] intraday_5586.csv.gz  in=423,416,648 out=113,176,626 elapsed=238.2s

  [16107/20519] intraday_5588.csv.gz  in=423,427,817 out=113,176,626 elapsed=238.2s

  [16108/20519] intraday_5589.csv.gz  in=423,439,137 out=113,176,626 elapsed=238.2s

  [16109/20519] intraday_5587.csv.gz  in=423,451,192 out=113,176,626 elapsed=238.2s

  [16110/20519] intraday_5590.csv.gz  in=423,465,113 out=113,176,626 elapsed=238.2s

  [16111/20519] intraday_5591.csv.gz  in=423,475,299 out=113,176,626 elapsed=238.2s

  [16112/20519] intraday_5592.csv.gz  in=423,485,339 out=113,176,626 elapsed=238.3s

  [16113/20519] intraday_5593.csv.gz  in=423,499,741 out=113,176,626 elapsed=238.3s

  [16114/20519] intraday_5594.csv.gz  in=423,511,971 out=113,176,626 elapsed=238.3s

  [16115/20519] intraday_5596.csv.gz  in=423,523,760 out=113,176,626 elapsed=238.3s

  [16116/20519] intraday_5595.csv.gz  in=423,537,889 out=113,176,626 elapsed=238.3s

  [16117/20519] intraday_5597.csv.gz  in=423,550,640 out=113,176,626 elapsed=238.3s

  [16118/20519] intraday_5598.csv.gz  in=423,562,927 out=113,176,626 elapsed=238.3s

  [16119/20519] intraday_5600.csv.gz  in=423,574,426 out=113,176,626 elapsed=238.3s

  [16120/20519] intraday_5599.csv.gz  in=423,587,016 out=113,176,626 elapsed=238.3s

  [16121/20519] intraday_5601.csv.gz  in=423,597,754 out=113,176,626 elapsed=238.4s

  [16122/20519] intraday_5603.csv.gz  in=423,612,304 out=113,176,626 elapsed=238.4s

  [16123/20519] intraday_5602.csv.gz  in=423,623,026 out=113,176,626 elapsed=238.4s

  [16124/20519] intraday_5604.csv.gz  in=423,636,069 out=113,176,626 elapsed=238.4s

  [16125/20519] intraday_5606.csv.gz  in=423,648,190 out=113,176,626 elapsed=238.4s

  [16126/20519] intraday_5605.csv.gz  in=423,662,234 out=113,176,626 elapsed=238.4s

  [16127/20519] intraday_5607.csv.gz  in=423,671,910 out=113,176,626 elapsed=238.4s

  [16128/20519] intraday_5608.csv.gz  in=423,683,425 out=113,176,626 elapsed=238.4s

  [16129/20519] intraday_5611.csv.gz  in=423,696,857 out=113,176,626 elapsed=238.4s

  [16130/20519] intraday_5610.csv.gz  in=423,708,964 out=113,176,626 elapsed=238.4s

  [16131/20519] intraday_5609.csv.gz  in=423,720,662 out=113,176,626 elapsed=238.4s

  [16132/20519] intraday_5612.csv.gz  in=423,731,736 out=113,176,626 elapsed=238.5s

  [16133/20519] intraday_5613.csv.gz  in=423,743,333 out=113,176,626 elapsed=238.5s

  [16134/20519] intraday_5615.csv.gz  in=423,756,701 out=113,176,626 elapsed=238.5s

  [16135/20519] intraday_5614.csv.gz  in=423,767,131 out=113,176,626 elapsed=238.5s

  [16136/20519] intraday_5616.csv.gz  in=423,778,039 out=113,176,626 elapsed=238.5s

  [16137/20519] intraday_5617.csv.gz  in=423,790,673 out=113,176,626 elapsed=238.5s

  [16138/20519] intraday_5618.csv.gz  in=423,801,305 out=113,176,626 elapsed=238.5s

  [16139/20519] intraday_5619.csv.gz  in=423,812,946 out=113,176,626 elapsed=238.5s

  [16140/20519] intraday_5621.csv.gz  in=423,827,954 out=113,176,626 elapsed=238.6s

  [16141/20519] intraday_5620.csv.gz  in=423,839,364 out=113,176,626 elapsed=238.6s

  [16142/20519] intraday_5622.csv.gz  in=423,853,475 out=113,176,626 elapsed=238.6s

  [16143/20519] intraday_5623.csv.gz  in=423,865,441 out=113,176,626 elapsed=238.6s

  [16144/20519] intraday_5624.csv.gz  in=423,877,398 out=113,176,626 elapsed=238.6s

  [16145/20519] intraday_5625.csv.gz  in=423,888,512 out=113,176,626 elapsed=238.6s

  [16146/20519] intraday_5626.csv.gz  in=423,902,139 out=113,176,626 elapsed=238.6s

  [16147/20519] intraday_5627.csv.gz  in=423,918,147 out=113,176,626 elapsed=238.6s

  [16148/20519] intraday_5628.csv.gz  in=423,930,090 out=113,176,626 elapsed=238.7s

  [16149/20519] intraday_5629.csv.gz  in=423,943,299 out=113,176,626 elapsed=238.7s

  [16150/20519] intraday_5630.csv.gz  in=423,956,314 out=113,176,626 elapsed=238.7s

  [16151/20519] intraday_5631.csv.gz  in=423,969,863 out=113,176,626 elapsed=238.7s

  [16152/20519] intraday_5632.csv.gz  in=423,984,169 out=113,176,626 elapsed=238.7s

  [16153/20519] intraday_5633.csv.gz  in=423,996,571 out=113,176,626 elapsed=238.7s

  [16154/20519] intraday_5634.csv.gz  in=424,009,551 out=113,176,626 elapsed=238.7s

  [16155/20519] intraday_5636.csv.gz  in=424,023,539 out=113,176,626 elapsed=238.7s

  [16156/20519] intraday_5635.csv.gz  in=424,035,092 out=113,176,626 elapsed=238.7s

  [16157/20519] intraday_5639.csv.gz  in=424,047,069 out=113,176,626 elapsed=238.8s

  [16158/20519] intraday_5637.csv.gz  in=424,074,779 out=113,176,626 elapsed=238.8s

  [16159/20519] intraday_5638.csv.gz  in=424,087,492 out=113,176,626 elapsed=238.8s

  [16160/20519] intraday_5640.csv.gz  in=424,102,108 out=113,176,626 elapsed=238.8s

  [16161/20519] intraday_5641.csv.gz  in=424,113,054 out=113,176,626 elapsed=238.8s

  [16162/20519] intraday_5642.csv.gz  in=424,125,422 out=113,176,626 elapsed=238.8s

  [16163/20519] intraday_5643.csv.gz  in=424,141,830 out=113,176,626 elapsed=238.8s

  [16164/20519] intraday_5644.csv.gz  in=424,152,527 out=113,176,626 elapsed=238.8s

  [16165/20519] intraday_5645.csv.gz  in=424,166,232 out=113,176,626 elapsed=238.8s

  [16166/20519] intraday_5646.csv.gz  in=424,182,165 out=113,176,626 elapsed=238.8s

  [16167/20519] intraday_5647.csv.gz  in=424,197,104 out=113,176,626 elapsed=238.8s

  [16168/20519] intraday_5648.csv.gz  in=424,209,203 out=113,176,626 elapsed=238.8s

  [16169/20519] intraday_5649.csv.gz  in=424,222,349 out=113,176,626 elapsed=238.8s

  [16170/20519] intraday_5650.csv.gz  in=424,235,790 out=113,176,626 elapsed=238.8s

  [16171/20519] intraday_5651.csv.gz  in=424,248,577 out=113,176,626 elapsed=238.8s

  [16172/20519] intraday_5652.csv.gz  in=424,264,326 out=113,176,626 elapsed=238.9s

  [16173/20519] intraday_5653.csv.gz  in=424,277,207 out=113,176,626 elapsed=238.9s

  [16174/20519] intraday_5654.csv.gz  in=424,290,531 out=113,176,626 elapsed=238.9s

  [16175/20519] intraday_5655.csv.gz  in=424,306,107 out=113,176,626 elapsed=238.9s

  [16176/20519] intraday_5656.csv.gz  in=424,319,453 out=113,176,626 elapsed=238.9s

  [16177/20519] intraday_5657.csv.gz  in=424,331,466 out=113,176,626 elapsed=238.9s

  [16178/20519] intraday_5658.csv.gz  in=424,342,585 out=113,176,626 elapsed=238.9s

  [16179/20519] intraday_5659.csv.gz  in=424,356,639 out=113,176,626 elapsed=238.9s

  [16180/20519] intraday_5660.csv.gz  in=424,367,781 out=113,176,626 elapsed=238.9s

  [16181/20519] intraday_5661.csv.gz  in=424,381,101 out=113,176,626 elapsed=238.9s

  [16182/20519] intraday_5662.csv.gz  in=424,393,269 out=113,176,626 elapsed=238.9s

  [16183/20519] intraday_5663.csv.gz  in=424,410,140 out=113,176,626 elapsed=238.9s

  [16184/20519] intraday_5664.csv.gz  in=424,422,385 out=113,176,626 elapsed=238.9s

  [16185/20519] intraday_5666.csv.gz  in=424,434,330 out=113,176,626 elapsed=238.9s

  [16186/20519] intraday_5665.csv.gz  in=424,446,928 out=113,176,626 elapsed=238.9s

  [16187/20519] intraday_5667.csv.gz  in=424,459,338 out=113,176,626 elapsed=238.9s

  [16188/20519] intraday_5668.csv.gz  in=424,470,927 out=113,176,626 elapsed=238.9s

  [16189/20519] intraday_5670.csv.gz  in=424,484,932 out=113,176,626 elapsed=238.9s

  [16190/20519] intraday_5669.csv.gz  in=424,498,620 out=113,176,626 elapsed=239.0s

  [16191/20519] intraday_5671.csv.gz  in=424,514,158 out=113,176,626 elapsed=239.0s

  [16192/20519] intraday_5672.csv.gz  in=424,527,969 out=113,176,626 elapsed=239.0s

  [16193/20519] intraday_5673.csv.gz  in=424,538,946 out=113,176,626 elapsed=239.0s

  [16194/20519] intraday_5674.csv.gz  in=424,550,739 out=113,176,626 elapsed=239.0s

  [16195/20519] intraday_5675.csv.gz  in=424,564,355 out=113,176,626 elapsed=239.0s

  [16196/20519] intraday_5676.csv.gz  in=424,576,565 out=113,176,626 elapsed=239.0s

  [16197/20519] intraday_5677.csv.gz  in=424,602,263 out=113,176,626 elapsed=239.0s

  [16198/20519] intraday_5678.csv.gz  in=424,609,642 out=113,176,626 elapsed=239.0s

  [16199/20519] intraday_5679.csv.gz  in=424,620,853 out=113,176,626 elapsed=239.0s

  [16200/20519] intraday_5680.csv.gz  in=424,628,558 out=113,176,626 elapsed=239.1s

  [16201/20519] intraday_5682.csv.gz  in=424,641,689 out=113,176,626 elapsed=239.1s

  [16202/20519] intraday_5681.csv.gz  in=424,657,185 out=113,176,626 elapsed=239.1s

  [16203/20519] intraday_5684.csv.gz  in=424,667,768 out=113,176,626 elapsed=239.1s

  [16204/20519] intraday_5683.csv.gz  in=424,680,006 out=113,176,626 elapsed=239.1s

  [16205/20519] intraday_5685.csv.gz  in=424,692,391 out=113,176,626 elapsed=239.1s

  [16206/20519] intraday_5687.csv.gz  in=424,708,107 out=113,176,626 elapsed=239.1s

  [16207/20519] intraday_5686.csv.gz  in=424,723,514 out=113,176,626 elapsed=239.1s

  [16208/20519] intraday_5688.csv.gz  in=424,735,201 out=113,176,626 elapsed=239.1s

  [16209/20519] intraday_5689.csv.gz  in=424,748,836 out=113,176,626 elapsed=239.2s

  [16210/20519] intraday_5691.csv.gz  in=424,761,514 out=113,176,626 elapsed=239.2s

  [16211/20519] intraday_5690.csv.gz  in=424,775,604 out=113,176,626 elapsed=239.2s

  [16212/20519] intraday_5692.csv.gz  in=424,789,038 out=113,176,626 elapsed=239.2s

  [16213/20519] intraday_5695.csv.gz  in=424,799,698 out=113,176,626 elapsed=239.2s

  [16214/20519] intraday_5694.csv.gz  in=424,811,379 out=113,176,626 elapsed=239.2s

  [16215/20519] intraday_5696.csv.gz  in=424,820,988 out=113,176,626 elapsed=239.2s

  [16216/20519] intraday_5693.csv.gz  in=424,835,170 out=113,176,626 elapsed=239.2s

  [16217/20519] intraday_5697.csv.gz  in=424,848,950 out=113,176,626 elapsed=239.2s

  [16218/20519] intraday_5698.csv.gz  in=424,861,901 out=113,176,626 elapsed=239.2s

  [16219/20519] intraday_5699.csv.gz  in=424,875,273 out=113,176,626 elapsed=239.3s

  [16220/20519] intraday_5702.csv.gz  in=424,888,231 out=113,176,626 elapsed=239.3s

  [16221/20519] intraday_5700.csv.gz  in=424,900,291 out=113,176,626 elapsed=239.3s

  [16222/20519] intraday_5701.csv.gz  in=424,912,148 out=113,176,626 elapsed=239.3s

  [16223/20519] intraday_5703.csv.gz  in=424,925,276 out=113,176,626 elapsed=239.3s

  [16224/20519] intraday_5704.csv.gz  in=424,938,130 out=113,176,626 elapsed=239.3s

  [16225/20519] intraday_5705.csv.gz  in=424,951,136 out=113,176,626 elapsed=239.3s

  [16226/20519] intraday_5706.csv.gz  in=424,961,999 out=113,176,626 elapsed=239.3s

  [16227/20519] intraday_5707.csv.gz  in=424,973,889 out=113,176,626 elapsed=239.3s

  [16228/20519] intraday_5710.csv.gz  in=424,988,917 out=113,176,626 elapsed=239.3s

  [16229/20519] intraday_5708.csv.gz  in=425,000,952 out=113,176,626 elapsed=239.3s

  [16230/20519] intraday_5709.csv.gz  in=425,015,184 out=113,176,626 elapsed=239.3s

  [16231/20519] intraday_5711.csv.gz  in=425,030,604 out=113,176,626 elapsed=239.3s

  [16232/20519] intraday_5714.csv.gz  in=425,042,626 out=113,176,626 elapsed=239.4s

  [16233/20519] intraday_5712.csv.gz  in=425,058,916 out=113,176,626 elapsed=239.4s

  [16234/20519] intraday_5713.csv.gz  in=425,070,940 out=113,176,626 elapsed=239.4s

  [16235/20519] intraday_5715.csv.gz  in=425,102,921 out=113,176,626 elapsed=239.4s

  [16236/20519] intraday_5716.csv.gz  in=425,112,434 out=113,176,626 elapsed=239.4s

  [16237/20519] intraday_5717.csv.gz  in=425,126,192 out=113,176,626 elapsed=239.4s

  [16238/20519] intraday_5718.csv.gz  in=425,137,071 out=113,176,626 elapsed=239.4s

  [16239/20519] intraday_5719.csv.gz  in=425,147,377 out=113,176,626 elapsed=239.4s

  [16240/20519] intraday_5720.csv.gz  in=425,158,478 out=113,176,626 elapsed=239.4s

  [16241/20519] intraday_5721.csv.gz  in=425,171,016 out=113,176,626 elapsed=239.4s

  [16242/20519] intraday_5723.csv.gz  in=425,182,628 out=113,176,626 elapsed=239.5s

  [16243/20519] intraday_5722.csv.gz  in=425,195,993 out=113,176,626 elapsed=239.5s

  [16244/20519] intraday_5724.csv.gz  in=425,209,470 out=113,176,626 elapsed=239.5s

  [16245/20519] intraday_5726.csv.gz  in=425,221,432 out=113,176,626 elapsed=239.5s

  [16246/20519] intraday_5725.csv.gz  in=425,234,022 out=113,176,626 elapsed=239.5s

  [16247/20519] intraday_5727.csv.gz  in=425,245,429 out=113,176,626 elapsed=239.5s

  [16248/20519] intraday_5728.csv.gz  in=425,257,729 out=113,176,626 elapsed=239.5s

  [16249/20519] intraday_5729.csv.gz  in=425,268,277 out=113,176,626 elapsed=239.5s

  [16250/20519] intraday_5731.csv.gz  in=425,278,622 out=113,176,626 elapsed=239.5s

  [16251/20519] intraday_5730.csv.gz  in=425,292,306 out=113,176,626 elapsed=239.5s

  [16252/20519] intraday_5732.csv.gz  in=425,307,519 out=113,176,626 elapsed=239.5s

  [16253/20519] intraday_5734.csv.gz  in=425,318,137 out=113,176,626 elapsed=239.6s

  [16254/20519] intraday_5733.csv.gz  in=425,329,237 out=113,176,626 elapsed=239.6s

  [16255/20519] intraday_5735.csv.gz  in=425,343,708 out=113,176,626 elapsed=239.6s

  [16256/20519] intraday_5736.csv.gz  in=425,356,718 out=113,176,626 elapsed=239.6s

  [16257/20519] intraday_5737.csv.gz  in=425,369,985 out=113,176,626 elapsed=239.6s

  [16258/20519] intraday_5738.csv.gz  in=425,380,903 out=113,176,626 elapsed=239.6s

  [16259/20519] intraday_5740.csv.gz  in=425,393,296 out=113,176,626 elapsed=239.7s

  [16260/20519] intraday_5739.csv.gz  in=425,406,425 out=113,176,626 elapsed=239.7s

  [16261/20519] intraday_5742.csv.gz  in=425,417,598 out=113,176,626 elapsed=239.7s

  [16262/20519] intraday_5741.csv.gz  in=425,430,681 out=113,176,626 elapsed=239.7s

  [16263/20519] intraday_5743.csv.gz  in=425,445,107 out=113,176,626 elapsed=239.7s

  [16264/20519] intraday_5744.csv.gz  in=425,455,738 out=113,176,626 elapsed=239.7s

  [16265/20519] intraday_5745.csv.gz  in=425,471,576 out=113,176,626 elapsed=239.7s

  [16266/20519] intraday_5746.csv.gz  in=425,484,451 out=113,176,626 elapsed=239.7s

  [16267/20519] intraday_5747.csv.gz  in=425,497,940 out=113,176,626 elapsed=239.7s

  [16268/20519] intraday_5748.csv.gz  in=425,511,351 out=113,176,626 elapsed=239.7s

  [16269/20519] intraday_5749.csv.gz  in=425,522,816 out=113,176,626 elapsed=239.7s

  [16270/20519] intraday_5750.csv.gz  in=425,534,427 out=113,176,626 elapsed=239.7s

  [16271/20519] intraday_5751.csv.gz  in=425,546,386 out=113,176,626 elapsed=239.7s

  [16272/20519] intraday_5752.csv.gz  in=425,558,930 out=113,176,626 elapsed=239.7s

  [16273/20519] intraday_5753.csv.gz  in=425,571,897 out=113,176,626 elapsed=239.8s

  [16274/20519] intraday_5754.csv.gz  in=425,583,014 out=113,176,626 elapsed=239.8s

  [16275/20519] intraday_5755.csv.gz  in=425,594,599 out=113,176,626 elapsed=239.8s

  [16276/20519] intraday_5756.csv.gz  in=425,607,339 out=113,176,626 elapsed=239.8s

  [16277/20519] intraday_5757.csv.gz  in=425,620,436 out=113,176,626 elapsed=239.8s

  [16278/20519] intraday_5759.csv.gz  in=425,634,049 out=113,176,626 elapsed=239.8s

  [16279/20519] intraday_5758.csv.gz  in=425,644,717 out=113,176,626 elapsed=239.8s

  [16280/20519] intraday_5760.csv.gz  in=425,654,756 out=113,176,626 elapsed=239.8s

  [16281/20519] intraday_5761.csv.gz  in=425,666,818 out=113,176,626 elapsed=239.8s

  [16282/20519] intraday_5762.csv.gz  in=425,679,410 out=113,176,626 elapsed=239.8s

  [16283/20519] intraday_5763.csv.gz  in=425,693,498 out=113,176,626 elapsed=239.8s

  [16284/20519] intraday_5764.csv.gz  in=425,709,198 out=113,176,626 elapsed=239.8s

  [16285/20519] intraday_5765.csv.gz  in=425,722,333 out=113,176,626 elapsed=239.9s

  [16286/20519] intraday_5767.csv.gz  in=425,733,815 out=113,176,626 elapsed=239.9s

  [16287/20519] intraday_5766.csv.gz  in=425,745,304 out=113,176,626 elapsed=239.9s

  [16288/20519] intraday_5769.csv.gz  in=425,761,930 out=113,176,626 elapsed=239.9s

  [16289/20519] intraday_5768.csv.gz  in=425,775,668 out=113,176,626 elapsed=239.9s

  [16290/20519] intraday_5770.csv.gz  in=425,788,310 out=113,176,626 elapsed=239.9s

  [16291/20519] intraday_5772.csv.gz  in=425,801,095 out=113,176,626 elapsed=239.9s

  [16292/20519] intraday_5771.csv.gz  in=425,817,695 out=113,176,626 elapsed=239.9s

  [16293/20519] intraday_5773.csv.gz  in=425,831,175 out=113,176,626 elapsed=239.9s

  [16294/20519] intraday_5774.csv.gz  in=425,844,679 out=113,176,626 elapsed=239.9s

  [16295/20519] intraday_5775.csv.gz  in=425,857,033 out=113,176,626 elapsed=239.9s

  [16296/20519] intraday_5776.csv.gz  in=425,869,147 out=113,176,626 elapsed=240.0s

  [16297/20519] intraday_5777.csv.gz  in=425,882,117 out=113,176,626 elapsed=240.0s

  [16298/20519] intraday_5778.csv.gz  in=425,894,297 out=113,176,626 elapsed=240.0s

  [16299/20519] intraday_5779.csv.gz  in=425,908,206 out=113,176,626 elapsed=240.0s

  [16300/20519] intraday_5781.csv.gz  in=425,921,313 out=113,176,626 elapsed=240.0s

  [16301/20519] intraday_5780.csv.gz  in=425,933,111 out=113,176,626 elapsed=240.0s

  [16302/20519] intraday_5782.csv.gz  in=425,952,002 out=113,176,626 elapsed=240.0s

  [16303/20519] intraday_5783.csv.gz  in=425,964,696 out=113,176,626 elapsed=240.0s

  [16304/20519] intraday_5784.csv.gz  in=425,977,522 out=113,176,626 elapsed=240.0s

  [16305/20519] intraday_5785.csv.gz  in=425,993,272 out=113,176,626 elapsed=240.0s

  [16306/20519] intraday_5786.csv.gz  in=426,004,476 out=113,176,626 elapsed=240.1s

  [16307/20519] intraday_5787.csv.gz  in=426,018,236 out=113,176,626 elapsed=240.1s

  [16308/20519] intraday_5789.csv.gz  in=426,033,802 out=113,176,626 elapsed=240.1s

  [16309/20519] intraday_5788.csv.gz  in=426,048,315 out=113,176,626 elapsed=240.1s

  [16310/20519] intraday_5791.csv.gz  in=426,060,649 out=113,176,626 elapsed=240.1s

  [16311/20519] intraday_5792.csv.gz  in=426,074,282 out=113,176,626 elapsed=240.1s

  [16312/20519] intraday_5793.csv.gz  in=426,087,013 out=113,176,626 elapsed=240.1s

  [16313/20519] intraday_5790.csv.gz  in=426,104,673 out=113,176,626 elapsed=240.1s

  [16314/20519] intraday_5796.csv.gz  in=426,118,651 out=113,176,626 elapsed=240.2s

  [16315/20519] intraday_5794.csv.gz  in=426,132,432 out=113,176,626 elapsed=240.2s

  [16316/20519] intraday_5795.csv.gz  in=426,147,136 out=113,176,626 elapsed=240.2s

  [16317/20519] intraday_5797.csv.gz  in=426,161,970 out=113,176,626 elapsed=240.2s

  [16318/20519] intraday_5799.csv.gz  in=426,174,218 out=113,176,626 elapsed=240.2s

  [16319/20519] intraday_5800.csv.gz  in=426,186,395 out=113,176,626 elapsed=240.2s

  [16320/20519] intraday_5798.csv.gz  in=426,199,982 out=113,176,626 elapsed=240.2s

  [16321/20519] intraday_5801.csv.gz  in=426,213,020 out=113,176,626 elapsed=240.2s

  [16322/20519] intraday_5802.csv.gz  in=426,224,107 out=113,176,626 elapsed=240.2s

  [16323/20519] intraday_5804.csv.gz  in=426,236,542 out=113,176,626 elapsed=240.2s

  [16324/20519] intraday_5803.csv.gz  in=426,249,487 out=113,176,626 elapsed=240.2s

  [16325/20519] intraday_5805.csv.gz  in=426,264,064 out=113,176,626 elapsed=240.2s

  [16326/20519] intraday_5806.csv.gz  in=426,277,768 out=113,176,626 elapsed=240.3s

  [16327/20519] intraday_5807.csv.gz  in=426,289,952 out=113,176,626 elapsed=240.3s

  [16328/20519] intraday_5808.csv.gz  in=426,301,466 out=113,176,626 elapsed=240.3s

  [16329/20519] intraday_5810.csv.gz  in=426,313,022 out=113,176,626 elapsed=240.3s

  [16330/20519] intraday_5809.csv.gz  in=426,326,732 out=113,176,626 elapsed=240.3s

  [16331/20519] intraday_5811.csv.gz  in=426,338,964 out=113,176,626 elapsed=240.3s

  [16332/20519] intraday_5812.csv.gz  in=426,354,513 out=113,176,626 elapsed=240.3s

  [16333/20519] intraday_5813.csv.gz  in=426,368,720 out=113,176,626 elapsed=240.3s

  [16334/20519] intraday_5814.csv.gz  in=426,383,459 out=113,176,626 elapsed=240.3s

  [16335/20519] intraday_5816.csv.gz  in=426,394,877 out=113,176,626 elapsed=240.3s

  [16336/20519] intraday_5817.csv.gz  in=426,408,675 out=113,176,626 elapsed=240.4s

  [16337/20519] intraday_5815.csv.gz  in=426,421,360 out=113,176,626 elapsed=240.4s

  [16338/20519] intraday_5818.csv.gz  in=426,432,277 out=113,176,626 elapsed=240.4s

  [16339/20519] intraday_5819.csv.gz  in=426,446,738 out=113,176,626 elapsed=240.4s

  [16340/20519] intraday_5820.csv.gz  in=426,454,184 out=113,176,626 elapsed=240.4s

  [16341/20519] intraday_5821.csv.gz  in=426,463,317 out=113,176,626 elapsed=240.4s

  [16342/20519] intraday_5822.csv.gz  in=426,473,587 out=113,176,626 elapsed=240.4s

  [16343/20519] intraday_5823.csv.gz  in=426,489,623 out=113,176,626 elapsed=240.4s

  [16344/20519] intraday_5825.csv.gz  in=426,501,284 out=113,176,626 elapsed=240.4s

  [16345/20519] intraday_5824.csv.gz  in=426,514,692 out=113,176,626 elapsed=240.4s

  [16346/20519] intraday_5826.csv.gz  in=426,525,431 out=113,176,626 elapsed=240.4s

  [16347/20519] intraday_5827.csv.gz  in=426,538,906 out=113,176,626 elapsed=240.5s

  [16348/20519] intraday_5828.csv.gz  in=426,554,700 out=113,176,626 elapsed=240.5s

  [16349/20519] intraday_5830.csv.gz  in=426,566,292 out=113,176,626 elapsed=240.5s

  [16350/20519] intraday_5829.csv.gz  in=426,580,389 out=113,176,626 elapsed=240.5s

  [16351/20519] intraday_5832.csv.gz  in=426,593,860 out=113,176,626 elapsed=240.5s

  [16352/20519] intraday_5833.csv.gz  in=426,608,336 out=113,176,626 elapsed=240.5s

  [16353/20519] intraday_5831.csv.gz  in=426,621,689 out=113,176,626 elapsed=240.5s

  [16354/20519] intraday_5834.csv.gz  in=426,635,372 out=113,176,626 elapsed=240.5s

  [16355/20519] intraday_5836.csv.gz  in=426,647,345 out=113,176,626 elapsed=240.6s

  [16356/20519] intraday_5835.csv.gz  in=426,659,461 out=113,176,626 elapsed=240.6s

  [16357/20519] intraday_5837.csv.gz  in=426,669,509 out=113,176,626 elapsed=240.6s

  [16358/20519] intraday_5838.csv.gz  in=426,686,064 out=113,176,626 elapsed=240.6s

  [16359/20519] intraday_5839.csv.gz  in=426,700,059 out=113,176,626 elapsed=240.6s

  [16360/20519] intraday_5840.csv.gz  in=426,713,303 out=113,176,626 elapsed=240.7s

  [16361/20519] intraday_5841.csv.gz  in=426,731,236 out=113,176,626 elapsed=240.7s

  [16362/20519] intraday_5842.csv.gz  in=426,742,578 out=113,176,626 elapsed=240.7s

  [16363/20519] intraday_5843.csv.gz  in=426,754,964 out=113,176,626 elapsed=240.7s

  [16364/20519] intraday_5845.csv.gz  in=426,767,475 out=113,176,626 elapsed=240.7s

  [16365/20519] intraday_5847.csv.gz  in=426,780,347 out=113,176,626 elapsed=240.7s

  [16366/20519] intraday_5846.csv.gz  in=426,792,503 out=113,176,626 elapsed=240.8s

  [16367/20519] intraday_5844.csv.gz  in=426,805,770 out=113,176,626 elapsed=240.8s

  [16368/20519] intraday_5848.csv.gz  in=426,816,825 out=113,176,626 elapsed=240.8s

  [16369/20519] intraday_5850.csv.gz  in=426,828,737 out=113,176,626 elapsed=240.8s

  [16370/20519] intraday_5849.csv.gz  in=426,840,477 out=113,176,626 elapsed=240.8s

  [16371/20519] intraday_5851.csv.gz  in=426,853,615 out=113,176,626 elapsed=240.8s

  [16372/20519] intraday_5852.csv.gz  in=426,867,590 out=113,176,626 elapsed=240.8s

  [16373/20519] intraday_5853.csv.gz  in=426,882,739 out=113,176,626 elapsed=240.8s

  [16374/20519] intraday_5855.csv.gz  in=426,894,859 out=113,176,626 elapsed=240.8s

  [16375/20519] intraday_5854.csv.gz  in=426,907,439 out=113,176,626 elapsed=240.8s

  [16376/20519] intraday_5856.csv.gz  in=426,919,835 out=113,176,626 elapsed=240.8s

  [16377/20519] intraday_5858.csv.gz  in=426,930,360 out=113,176,626 elapsed=240.9s

  [16378/20519] intraday_5857.csv.gz  in=426,944,448 out=113,176,626 elapsed=240.9s

  [16379/20519] intraday_5859.csv.gz  in=426,956,605 out=113,176,626 elapsed=240.9s

  [16380/20519] intraday_5860.csv.gz  in=426,968,174 out=113,176,626 elapsed=240.9s

  [16381/20519] intraday_5861.csv.gz  in=426,978,927 out=113,176,626 elapsed=240.9s

  [16382/20519] intraday_5863.csv.gz  in=426,991,674 out=113,176,626 elapsed=240.9s

  [16383/20519] intraday_5862.csv.gz  in=427,002,722 out=113,176,626 elapsed=240.9s

  [16384/20519] intraday_5864.csv.gz  in=427,014,620 out=113,176,626 elapsed=240.9s

  [16385/20519] intraday_5865.csv.gz  in=427,027,379 out=113,176,626 elapsed=240.9s

  [16386/20519] intraday_5867.csv.gz  in=427,039,867 out=113,176,626 elapsed=240.9s

  [16387/20519] intraday_5866.csv.gz  in=427,053,330 out=113,176,626 elapsed=241.0s

  [16388/20519] intraday_5868.csv.gz  in=427,065,551 out=113,176,626 elapsed=241.0s

  [16389/20519] intraday_5869.csv.gz  in=427,076,247 out=113,176,626 elapsed=241.0s

  [16390/20519] intraday_5870.csv.gz  in=427,087,800 out=113,176,626 elapsed=241.0s

  [16391/20519] intraday_5871.csv.gz  in=427,099,322 out=113,176,626 elapsed=241.0s

  [16392/20519] intraday_5872.csv.gz  in=427,110,343 out=113,176,626 elapsed=241.0s

  [16393/20519] intraday_5873.csv.gz  in=427,121,358 out=113,176,626 elapsed=241.0s

  [16394/20519] intraday_5874.csv.gz  in=427,135,847 out=113,176,626 elapsed=241.0s

  [16395/20519] intraday_5875.csv.gz  in=427,146,290 out=113,176,626 elapsed=241.0s

  [16396/20519] intraday_5876.csv.gz  in=427,157,047 out=113,176,626 elapsed=241.0s

  [16397/20519] intraday_5877.csv.gz  in=427,171,499 out=113,176,626 elapsed=241.0s

  [16398/20519] intraday_5879.csv.gz  in=427,184,487 out=113,176,626 elapsed=241.1s

  [16399/20519] intraday_5878.csv.gz  in=427,197,370 out=113,176,626 elapsed=241.1s

  [16400/20519] intraday_5880.csv.gz  in=427,209,131 out=113,176,626 elapsed=241.1s

  [16401/20519] intraday_5882.csv.gz  in=427,221,711 out=113,176,626 elapsed=241.1s

  [16402/20519] intraday_5881.csv.gz  in=427,234,368 out=113,176,626 elapsed=241.1s

  [16403/20519] intraday_5884.csv.gz  in=427,245,610 out=113,176,626 elapsed=241.1s

  [16404/20519] intraday_5883.csv.gz  in=427,259,373 out=113,176,626 elapsed=241.1s

  [16405/20519] intraday_5885.csv.gz  in=427,269,717 out=113,176,626 elapsed=241.1s

  [16406/20519] intraday_5886.csv.gz  in=427,281,074 out=113,176,626 elapsed=241.1s

  [16407/20519] intraday_5887.csv.gz  in=427,296,642 out=113,176,626 elapsed=241.1s

  [16408/20519] intraday_5888.csv.gz  in=427,310,006 out=113,176,626 elapsed=241.2s

  [16409/20519] intraday_5889.csv.gz  in=427,323,453 out=113,176,626 elapsed=241.2s

  [16410/20519] intraday_5890.csv.gz  in=427,335,939 out=113,176,626 elapsed=241.2s

  [16411/20519] intraday_5891.csv.gz  in=427,364,454 out=113,176,626 elapsed=241.2s

  [16412/20519] intraday_5893.csv.gz  in=427,376,057 out=113,176,626 elapsed=241.2s

  [16413/20519] intraday_5892.csv.gz  in=427,395,785 out=113,176,626 elapsed=241.2s

  [16414/20519] intraday_5894.csv.gz  in=427,407,662 out=113,176,626 elapsed=241.2s

  [16415/20519] intraday_5895.csv.gz  in=427,421,237 out=113,176,626 elapsed=241.2s

  [16416/20519] intraday_5898.csv.gz  in=427,431,682 out=113,176,626 elapsed=241.2s

  [16417/20519] intraday_5896.csv.gz  in=427,444,427 out=113,176,626 elapsed=241.2s

  [16418/20519] intraday_5897.csv.gz  in=427,456,129 out=113,176,626 elapsed=241.2s

  [16419/20519] intraday_5899.csv.gz  in=427,469,853 out=113,176,626 elapsed=241.3s

  [16420/20519] intraday_5900.csv.gz  in=427,480,909 out=113,176,626 elapsed=241.3s

  [16421/20519] intraday_5902.csv.gz  in=427,490,252 out=113,176,626 elapsed=241.3s

  [16422/20519] intraday_5901.csv.gz  in=427,512,679 out=113,176,626 elapsed=241.3s

  [16423/20519] intraday_5903.csv.gz  in=427,524,468 out=113,176,626 elapsed=241.3s

  [16424/20519] intraday_5904.csv.gz  in=427,536,986 out=113,176,626 elapsed=241.3s

  [16425/20519] intraday_5905.csv.gz  in=427,551,748 out=113,176,626 elapsed=241.3s

  [16426/20519] intraday_5907.csv.gz  in=427,565,774 out=113,176,626 elapsed=241.3s

  [16427/20519] intraday_5906.csv.gz  in=427,580,541 out=113,176,626 elapsed=241.3s

  [16428/20519] intraday_5908.csv.gz  in=427,591,962 out=113,176,626 elapsed=241.3s

  [16429/20519] intraday_5909.csv.gz  in=427,604,289 out=113,176,626 elapsed=241.3s

  [16430/20519] intraday_5910.csv.gz  in=427,617,828 out=113,176,626 elapsed=241.3s

  [16431/20519] intraday_5911.csv.gz  in=427,634,246 out=113,176,626 elapsed=241.3s

  [16432/20519] intraday_5912.csv.gz  in=427,647,362 out=113,176,626 elapsed=241.3s

  [16433/20519] intraday_5913.csv.gz  in=427,660,520 out=113,176,626 elapsed=241.3s

  [16434/20519] intraday_5914.csv.gz  in=427,673,709 out=113,176,626 elapsed=241.3s

  [16435/20519] intraday_5915.csv.gz  in=427,688,226 out=113,176,626 elapsed=241.3s

  [16436/20519] intraday_5916.csv.gz  in=427,701,727 out=113,176,626 elapsed=241.3s

  [16437/20519] intraday_5917.csv.gz  in=427,716,920 out=113,176,626 elapsed=241.3s

  [16438/20519] intraday_5918.csv.gz  in=427,729,372 out=113,176,626 elapsed=241.3s

  [16439/20519] intraday_5919.csv.gz  in=427,742,316 out=113,176,626 elapsed=241.4s

  [16440/20519] intraday_5920.csv.gz  in=427,754,288 out=113,176,626 elapsed=241.4s

  [16441/20519] intraday_5921.csv.gz  in=427,768,832 out=113,176,626 elapsed=241.4s

  [16442/20519] intraday_5923.csv.gz  in=427,783,046 out=113,176,626 elapsed=241.4s

  [16443/20519] intraday_5922.csv.gz  in=427,795,225 out=113,176,626 elapsed=241.4s

  [16444/20519] intraday_5924.csv.gz  in=427,808,345 out=113,176,626 elapsed=241.4s

  [16445/20519] intraday_5925.csv.gz  in=427,821,853 out=113,176,626 elapsed=241.4s

  [16446/20519] intraday_5926.csv.gz  in=427,839,048 out=113,176,626 elapsed=241.4s

  [16447/20519] intraday_5928.csv.gz  in=427,852,682 out=113,176,626 elapsed=241.4s

  [16448/20519] intraday_5927.csv.gz  in=427,867,318 out=113,176,626 elapsed=241.4s

  [16449/20519] intraday_5930.csv.gz  in=427,880,922 out=113,176,626 elapsed=241.9s

  [16450/20519] intraday_5929.csv.gz  in=427,893,538 out=113,176,626 elapsed=241.9s

  [16451/20519] intraday_5932.csv.gz  in=427,905,315 out=113,176,626 elapsed=241.9s

  [16452/20519] intraday_5931.csv.gz  in=427,922,734 out=113,176,626 elapsed=241.9s

  [16453/20519] intraday_5935.csv.gz  in=427,934,845 out=113,176,626 elapsed=242.0s

  [16454/20519] intraday_5936.csv.gz  in=427,948,792 out=113,176,626 elapsed=242.0s

  [16455/20519] intraday_5933.csv.gz  in=427,960,903 out=113,176,626 elapsed=242.0s

  [16456/20519] intraday_5934.csv.gz  in=427,974,288 out=113,176,626 elapsed=242.0s

  [16457/20519] intraday_5938.csv.gz  in=427,988,657 out=113,176,626 elapsed=242.0s

  [16458/20519] intraday_5937.csv.gz  in=428,003,103 out=113,176,626 elapsed=242.0s

  [16459/20519] intraday_5940.csv.gz  in=428,017,470 out=113,176,626 elapsed=242.0s

  [16460/20519] intraday_5939.csv.gz  in=428,032,418 out=113,176,626 elapsed=242.0s

  [16461/20519] intraday_5942.csv.gz  in=428,045,291 out=113,176,626 elapsed=242.0s

  [16462/20519] intraday_5941.csv.gz  in=428,057,054 out=113,176,626 elapsed=242.1s

  [16463/20519] intraday_5943.csv.gz  in=428,068,962 out=113,176,626 elapsed=242.1s

  [16464/20519] intraday_5944.csv.gz  in=428,080,883 out=113,176,626 elapsed=242.1s

  [16465/20519] intraday_5947.csv.gz  in=428,094,388 out=113,176,626 elapsed=242.1s

  [16466/20519] intraday_5945.csv.gz  in=428,106,437 out=113,176,626 elapsed=242.1s

  [16467/20519] intraday_5946.csv.gz  in=428,118,950 out=113,176,626 elapsed=242.1s

  [16468/20519] intraday_5948.csv.gz  in=428,134,746 out=113,176,626 elapsed=242.1s

  [16469/20519] intraday_5949.csv.gz  in=428,146,127 out=113,176,626 elapsed=242.1s

  [16470/20519] intraday_5950.csv.gz  in=428,157,913 out=113,176,626 elapsed=242.1s

  [16471/20519] intraday_5951.csv.gz  in=428,171,814 out=113,176,626 elapsed=242.1s

  [16472/20519] intraday_5952.csv.gz  in=428,184,318 out=113,176,626 elapsed=242.2s

  [16473/20519] intraday_5953.csv.gz  in=428,196,672 out=113,176,626 elapsed=242.2s

  [16474/20519] intraday_5954.csv.gz  in=428,213,707 out=113,176,626 elapsed=242.2s

  [16475/20519] intraday_5955.csv.gz  in=428,227,420 out=113,176,626 elapsed=242.2s

  [16476/20519] intraday_5956.csv.gz  in=428,241,391 out=113,176,626 elapsed=242.2s

  [16477/20519] intraday_5957.csv.gz  in=428,253,838 out=113,176,626 elapsed=242.2s

  [16478/20519] intraday_5959.csv.gz  in=428,268,290 out=113,176,626 elapsed=242.2s

  [16479/20519] intraday_5958.csv.gz  in=428,280,302 out=113,176,626 elapsed=242.2s

  [16480/20519] intraday_5960.csv.gz  in=428,291,245 out=113,176,626 elapsed=242.2s

  [16481/20519] intraday_5962.csv.gz  in=428,300,113 out=113,176,626 elapsed=242.3s

  [16482/20519] intraday_5963.csv.gz  in=428,308,550 out=113,176,626 elapsed=242.3s

  [16483/20519] intraday_5961.csv.gz  in=428,322,561 out=113,176,626 elapsed=242.3s

  [16484/20519] intraday_5964.csv.gz  in=428,333,375 out=113,176,626 elapsed=242.3s

  [16485/20519] intraday_5967.csv.gz  in=428,346,894 out=113,176,626 elapsed=242.3s

  [16486/20519] intraday_5968.csv.gz  in=428,357,004 out=113,176,626 elapsed=242.3s

  [16487/20519] intraday_5966.csv.gz  in=428,375,656 out=113,176,626 elapsed=242.3s

  [16488/20519] intraday_5965.csv.gz  in=428,390,993 out=113,176,626 elapsed=242.3s

  [16489/20519] intraday_5970.csv.gz  in=428,405,205 out=113,176,626 elapsed=242.3s

  [16490/20519] intraday_5972.csv.gz  in=428,415,493 out=113,176,626 elapsed=242.3s

  [16491/20519] intraday_5969.csv.gz  in=428,428,666 out=113,176,626 elapsed=242.3s

  [16492/20519] intraday_5971.csv.gz  in=428,443,216 out=113,176,626 elapsed=242.4s

  [16493/20519] intraday_5973.csv.gz  in=428,456,156 out=113,176,626 elapsed=242.4s

  [16494/20519] intraday_5974.csv.gz  in=428,470,613 out=113,176,626 elapsed=242.4s

  [16495/20519] intraday_5975.csv.gz  in=428,484,689 out=113,176,626 elapsed=242.4s

  [16496/20519] intraday_5978.csv.gz  in=428,496,790 out=113,176,626 elapsed=242.4s

  [16497/20519] intraday_5976.csv.gz  in=428,509,393 out=113,176,626 elapsed=242.4s

  [16498/20519] intraday_5977.csv.gz  in=428,524,350 out=113,176,626 elapsed=242.4s

  [16499/20519] intraday_5979.csv.gz  in=428,535,245 out=113,176,626 elapsed=242.4s

  [16500/20519] intraday_5980.csv.gz  in=428,544,181 out=113,176,626 elapsed=242.4s

  [16501/20519] intraday_5981.csv.gz  in=428,558,236 out=113,176,626 elapsed=242.5s

  [16502/20519] intraday_5982.csv.gz  in=428,571,017 out=113,176,626 elapsed=242.5s

  [16503/20519] intraday_5983.csv.gz  in=428,581,104 out=113,176,626 elapsed=242.5s

  [16504/20519] intraday_5984.csv.gz  in=428,599,784 out=113,176,626 elapsed=242.5s

  [16505/20519] intraday_5986.csv.gz  in=428,613,117 out=113,176,626 elapsed=242.5s

  [16506/20519] intraday_5985.csv.gz  in=428,625,954 out=113,176,626 elapsed=242.5s

  [16507/20519] intraday_5987.csv.gz  in=428,641,821 out=113,176,626 elapsed=242.5s

  [16508/20519] intraday_5988.csv.gz  in=428,654,749 out=113,176,626 elapsed=242.5s

  [16509/20519] intraday_5989.csv.gz  in=428,666,741 out=113,176,626 elapsed=242.5s

  [16510/20519] intraday_5991.csv.gz  in=428,677,612 out=113,176,626 elapsed=242.6s

  [16511/20519] intraday_5990.csv.gz  in=428,689,253 out=113,176,626 elapsed=242.6s

  [16512/20519] intraday_5993.csv.gz  in=428,701,274 out=113,176,626 elapsed=242.6s

  [16513/20519] intraday_5992.csv.gz  in=428,713,569 out=113,176,626 elapsed=242.6s

  [16514/20519] intraday_5995.csv.gz  in=428,729,402 out=113,176,626 elapsed=242.6s

  [16515/20519] intraday_5994.csv.gz  in=428,741,167 out=113,176,626 elapsed=242.6s

  [16516/20519] intraday_5997.csv.gz  in=428,752,089 out=113,176,626 elapsed=242.6s

  [16517/20519] intraday_5996.csv.gz  in=428,764,031 out=113,176,626 elapsed=242.7s

  [16518/20519] intraday_5998.csv.gz  in=428,776,446 out=113,176,626 elapsed=242.7s

  [16519/20519] intraday_6000.csv.gz  in=428,787,134 out=113,176,626 elapsed=242.7s

  [16520/20519] intraday_5999.csv.gz  in=428,799,812 out=113,176,626 elapsed=242.7s

  [16521/20519] intraday_6002.csv.gz  in=428,808,903 out=113,176,626 elapsed=242.7s

  [16522/20519] intraday_6001.csv.gz  in=428,832,253 out=113,176,626 elapsed=242.7s

  [16523/20519] intraday_6004.csv.gz  in=428,842,107 out=113,176,626 elapsed=242.7s

  [16524/20519] intraday_6003.csv.gz  in=428,853,935 out=113,176,626 elapsed=242.8s

  [16525/20519] intraday_6005.csv.gz  in=428,865,174 out=113,176,626 elapsed=242.8s

  [16526/20519] intraday_6006.csv.gz  in=428,878,207 out=113,176,626 elapsed=242.8s

  [16527/20519] intraday_6007.csv.gz  in=428,890,036 out=113,176,626 elapsed=242.8s

  [16528/20519] intraday_6008.csv.gz  in=428,903,880 out=113,176,626 elapsed=242.8s

  [16529/20519] intraday_6010.csv.gz  in=428,914,474 out=113,176,626 elapsed=242.8s

  [16530/20519] intraday_6011.csv.gz  in=428,926,604 out=113,176,626 elapsed=242.8s

  [16531/20519] intraday_6009.csv.gz  in=428,945,842 out=113,176,626 elapsed=242.8s

  [16532/20519] intraday_6013.csv.gz  in=428,959,044 out=113,176,626 elapsed=242.8s

  [16533/20519] intraday_6012.csv.gz  in=428,972,473 out=113,176,626 elapsed=242.8s

  [16534/20519] intraday_6015.csv.gz  in=428,984,059 out=113,176,626 elapsed=242.8s

  [16535/20519] intraday_6014.csv.gz  in=428,996,730 out=113,176,626 elapsed=242.9s

  [16536/20519] intraday_6016.csv.gz  in=429,009,548 out=113,176,626 elapsed=242.9s

  [16537/20519] intraday_6017.csv.gz  in=429,021,967 out=113,176,626 elapsed=242.9s

  [16538/20519] intraday_6019.csv.gz  in=429,034,693 out=113,176,626 elapsed=242.9s

  [16539/20519] intraday_6018.csv.gz  in=429,046,257 out=113,176,626 elapsed=242.9s

  [16540/20519] intraday_6020.csv.gz  in=429,058,854 out=113,176,626 elapsed=242.9s

  [16541/20519] intraday_6021.csv.gz  in=429,071,148 out=113,176,626 elapsed=242.9s

  [16542/20519] intraday_6022.csv.gz  in=429,084,315 out=113,176,626 elapsed=242.9s

  [16543/20519] intraday_6023.csv.gz  in=429,110,184 out=113,176,626 elapsed=242.9s

  [16544/20519] intraday_6024.csv.gz  in=429,122,620 out=113,176,626 elapsed=242.9s

  [16545/20519] intraday_6026.csv.gz  in=429,135,667 out=113,176,626 elapsed=243.0s

  [16546/20519] intraday_6025.csv.gz  in=429,147,427 out=113,176,626 elapsed=243.0s

  [16547/20519] intraday_6027.csv.gz  in=429,159,995 out=113,176,626 elapsed=243.0s

  [16548/20519] intraday_6028.csv.gz  in=429,169,448 out=113,176,626 elapsed=243.0s

  [16549/20519] intraday_6029.csv.gz  in=429,183,933 out=113,176,626 elapsed=243.0s

  [16550/20519] intraday_6030.csv.gz  in=429,199,992 out=113,176,626 elapsed=243.0s

  [16551/20519] intraday_6031.csv.gz  in=429,209,867 out=113,176,626 elapsed=243.0s

  [16552/20519] intraday_6032.csv.gz  in=429,222,439 out=113,176,626 elapsed=243.0s

  [16553/20519] intraday_6034.csv.gz  in=429,233,087 out=113,176,626 elapsed=243.0s

  [16554/20519] intraday_6033.csv.gz  in=429,245,484 out=113,176,626 elapsed=243.0s

  [16555/20519] intraday_6035.csv.gz  in=429,257,298 out=113,176,626 elapsed=243.0s

  [16556/20519] intraday_6036.csv.gz  in=429,268,385 out=113,176,626 elapsed=243.0s

  [16557/20519] intraday_6037.csv.gz  in=429,282,008 out=113,176,626 elapsed=243.1s

  [16558/20519] intraday_6038.csv.gz  in=429,293,893 out=113,176,626 elapsed=243.1s

  [16559/20519] intraday_6040.csv.gz  in=429,303,095 out=113,176,626 elapsed=243.1s

  [16560/20519] intraday_6039.csv.gz  in=429,316,173 out=113,176,626 elapsed=243.1s

  [16561/20519] intraday_6041.csv.gz  in=429,328,608 out=113,176,626 elapsed=243.1s

  [16562/20519] intraday_6043.csv.gz  in=429,338,964 out=113,176,626 elapsed=243.1s

  [16563/20519] intraday_6042.csv.gz  in=429,350,897 out=113,176,626 elapsed=243.1s

  [16564/20519] intraday_6045.csv.gz  in=429,359,988 out=113,176,626 elapsed=243.1s

  [16565/20519] intraday_6044.csv.gz  in=429,371,810 out=113,176,626 elapsed=243.1s

  [16566/20519] intraday_6046.csv.gz  in=429,382,363 out=113,176,626 elapsed=243.1s

  [16567/20519] intraday_6047.csv.gz  in=429,396,458 out=113,176,626 elapsed=243.2s

  [16568/20519] intraday_6049.csv.gz  in=429,407,964 out=113,176,626 elapsed=243.2s

  [16569/20519] intraday_6048.csv.gz  in=429,425,549 out=113,176,626 elapsed=243.2s

  [16570/20519] intraday_6051.csv.gz  in=429,435,861 out=113,176,626 elapsed=243.2s

  [16571/20519] intraday_6050.csv.gz  in=429,447,979 out=113,176,626 elapsed=243.2s

  [16572/20519] intraday_6053.csv.gz  in=429,459,241 out=113,176,626 elapsed=243.2s

  [16573/20519] intraday_6052.csv.gz  in=429,474,866 out=113,176,626 elapsed=243.2s

  [16574/20519] intraday_6055.csv.gz  in=429,486,629 out=113,176,626 elapsed=243.2s

  [16575/20519] intraday_6054.csv.gz  in=429,502,410 out=113,176,626 elapsed=243.2s

  [16576/20519] intraday_6056.csv.gz  in=429,515,112 out=113,176,626 elapsed=243.3s

  [16577/20519] intraday_6058.csv.gz  in=429,536,027 out=113,176,626 elapsed=243.3s

  [16578/20519] intraday_6057.csv.gz  in=429,549,212 out=113,176,626 elapsed=243.3s

  [16579/20519] intraday_6060.csv.gz  in=429,561,939 out=113,176,626 elapsed=243.3s

  [16580/20519] intraday_6059.csv.gz  in=429,573,991 out=113,176,626 elapsed=243.3s

  [16581/20519] intraday_6062.csv.gz  in=429,585,656 out=113,176,626 elapsed=243.3s

  [16582/20519] intraday_6061.csv.gz  in=429,598,817 out=113,176,626 elapsed=243.3s

  [16583/20519] intraday_6063.csv.gz  in=429,612,215 out=113,176,626 elapsed=243.3s

  [16584/20519] intraday_6064.csv.gz  in=429,624,989 out=113,176,626 elapsed=243.3s

  [16585/20519] intraday_6065.csv.gz  in=429,637,786 out=113,176,626 elapsed=243.3s

  [16586/20519] intraday_6068.csv.gz  in=429,648,173 out=113,176,626 elapsed=243.4s

  [16587/20519] intraday_6066.csv.gz  in=429,663,224 out=113,176,626 elapsed=243.4s

  [16588/20519] intraday_6067.csv.gz  in=429,679,046 out=113,176,626 elapsed=243.4s

  [16589/20519] intraday_6071.csv.gz  in=429,688,990 out=113,176,626 elapsed=243.4s

  [16590/20519] intraday_6069.csv.gz  in=429,701,050 out=113,176,626 elapsed=243.4s

  [16591/20519] intraday_6072.csv.gz  in=429,712,183 out=113,176,626 elapsed=243.4s

  [16592/20519] intraday_6070.csv.gz  in=429,730,576 out=113,176,626 elapsed=243.4s

  [16593/20519] intraday_6074.csv.gz  in=429,743,952 out=113,176,626 elapsed=243.4s

  [16594/20519] intraday_6076.csv.gz  in=429,756,562 out=113,176,626 elapsed=243.4s

  [16595/20519] intraday_6073.csv.gz  in=429,772,103 out=113,176,626 elapsed=243.4s

  [16596/20519] intraday_6075.csv.gz  in=429,785,435 out=113,176,626 elapsed=243.5s

  [16597/20519] intraday_6077.csv.gz  in=429,797,595 out=113,176,626 elapsed=243.5s

  [16598/20519] intraday_6079.csv.gz  in=429,812,311 out=113,176,626 elapsed=243.5s

  [16599/20519] intraday_6078.csv.gz  in=429,824,575 out=113,176,626 elapsed=243.5s

  [16600/20519] intraday_6080.csv.gz  in=429,836,271 out=113,176,626 elapsed=243.5s

  [16601/20519] intraday_6081.csv.gz  in=429,850,298 out=113,176,626 elapsed=243.5s

  [16602/20519] intraday_6085.csv.gz  in=429,861,678 out=113,176,626 elapsed=243.5s

  [16603/20519] intraday_6082.csv.gz  in=429,877,601 out=113,176,626 elapsed=243.5s

  [16604/20519] intraday_6083.csv.gz  in=429,890,217 out=113,176,626 elapsed=243.5s

  [16605/20519] intraday_6084.csv.gz  in=429,901,279 out=113,176,626 elapsed=243.5s

  [16606/20519] intraday_6087.csv.gz  in=429,912,409 out=113,176,626 elapsed=243.5s

  [16607/20519] intraday_6088.csv.gz  in=429,925,833 out=113,176,626 elapsed=243.6s

  [16608/20519] intraday_6086.csv.gz  in=429,939,292 out=113,176,626 elapsed=243.6s

  [16609/20519] intraday_6089.csv.gz  in=429,957,297 out=113,176,626 elapsed=243.6s

  [16610/20519] intraday_6090.csv.gz  in=429,973,039 out=113,176,626 elapsed=243.6s

  [16611/20519] intraday_6092.csv.gz  in=429,984,573 out=113,176,626 elapsed=243.7s

  [16612/20519] intraday_6093.csv.gz  in=429,996,667 out=113,176,626 elapsed=243.7s

  [16613/20519] intraday_6091.csv.gz  in=430,009,207 out=113,176,626 elapsed=243.7s

  [16614/20519] intraday_6094.csv.gz  in=430,020,838 out=113,176,626 elapsed=243.7s

  [16615/20519] intraday_6098.csv.gz  in=430,034,823 out=113,176,626 elapsed=243.7s

  [16616/20519] intraday_6095.csv.gz  in=430,047,149 out=113,176,626 elapsed=243.8s

  [16617/20519] intraday_6097.csv.gz  in=430,065,934 out=113,176,626 elapsed=243.8s

  [16618/20519] intraday_6096.csv.gz  in=430,078,084 out=113,176,626 elapsed=243.8s

  [16619/20519] intraday_6102.csv.gz  in=430,091,470 out=113,176,626 elapsed=243.8s

  [16620/20519] intraday_6101.csv.gz  in=430,103,268 out=113,176,626 elapsed=243.8s

  [16621/20519] intraday_6099.csv.gz  in=430,116,228 out=113,176,626 elapsed=243.8s

  [16622/20519] intraday_6100.csv.gz  in=430,128,426 out=113,176,626 elapsed=243.8s

  [16623/20519] intraday_6103.csv.gz  in=430,139,463 out=113,176,626 elapsed=243.8s

  [16624/20519] intraday_6105.csv.gz  in=430,147,796 out=113,176,626 elapsed=243.8s

  [16625/20519] intraday_6104.csv.gz  in=430,162,390 out=113,176,626 elapsed=243.8s

  [16626/20519] intraday_6106.csv.gz  in=430,171,624 out=113,176,626 elapsed=243.8s

  [16627/20519] intraday_6107.csv.gz  in=430,180,532 out=113,176,626 elapsed=243.8s

  [16628/20519] intraday_6108.csv.gz  in=430,180,610 out=113,176,626 elapsed=243.9s

  [16629/20519] intraday_6109.csv.gz  in=430,180,630 out=113,176,626 elapsed=243.9s

  [16630/20519] intraday_6110.csv.gz  in=430,180,647 out=113,176,626 elapsed=243.9s

  [16631/20519] intraday_6111.csv.gz  in=430,180,662 out=113,176,626 elapsed=243.9s

  [16632/20519] intraday_6112.csv.gz  in=430,183,844 out=113,176,626 elapsed=243.9s

  [16633/20519] intraday_6113.csv.gz  in=430,187,474 out=113,176,626 elapsed=243.9s

  [16634/20519] intraday_6115.csv.gz  in=430,192,966 out=113,176,626 elapsed=243.9s

  [16635/20519] intraday_6116.csv.gz  in=430,194,313 out=113,176,626 elapsed=243.9s

  [16636/20519] intraday_6114.csv.gz  in=430,206,652 out=113,176,626 elapsed=243.9s

  [16637/20519] intraday_6118.csv.gz  in=430,207,921 out=113,176,626 elapsed=243.9s

  [16638/20519] intraday_6117.csv.gz  in=430,208,860 out=113,176,626 elapsed=243.9s

  [16639/20519] intraday_6119.csv.gz  in=430,216,952 out=113,176,626 elapsed=243.9s

  [16640/20519] intraday_6120.csv.gz  in=430,218,307 out=113,176,626 elapsed=243.9s

  [16641/20519] intraday_6124.csv.gz  in=430,218,328 out=113,176,626 elapsed=243.9s

  [16642/20519] intraday_6123.csv.gz  in=430,220,676 out=113,176,626 elapsed=243.9s

  [16643/20519] intraday_6121.csv.gz  in=430,220,997 out=113,176,626 elapsed=244.0s

  [16644/20519] intraday_6122.csv.gz  in=430,221,038 out=113,176,626 elapsed=244.0s

  [16645/20519] intraday_6126.csv.gz  in=430,221,152 out=113,176,626 elapsed=244.0s

  [16646/20519] intraday_6127.csv.gz  in=430,230,381 out=113,176,626 elapsed=244.0s

  [16647/20519] intraday_6125.csv.gz  in=430,230,931 out=113,176,626 elapsed=244.0s

  [16648/20519] intraday_6128.csv.gz  in=430,247,565 out=113,176,626 elapsed=244.0s

  [16649/20519] intraday_6129.csv.gz  in=430,260,382 out=113,176,626 elapsed=244.0s

  [16650/20519] intraday_6130.csv.gz  in=430,274,723 out=113,176,626 elapsed=244.0s

  [16651/20519] intraday_6131.csv.gz  in=430,286,148 out=113,176,626 elapsed=244.0s

  [16652/20519] intraday_6133.csv.gz  in=430,301,333 out=113,176,626 elapsed=244.0s

  [16653/20519] intraday_6132.csv.gz  in=430,314,363 out=113,176,626 elapsed=244.0s

  [16654/20519] intraday_6134.csv.gz  in=430,331,302 out=113,176,626 elapsed=244.1s

  [16655/20519] intraday_6136.csv.gz  in=430,345,374 out=113,176,626 elapsed=244.1s

  [16656/20519] intraday_6135.csv.gz  in=430,356,692 out=113,176,626 elapsed=244.1s

  [16657/20519] intraday_6137.csv.gz  in=430,372,633 out=113,176,626 elapsed=244.1s

  [16658/20519] intraday_6140.csv.gz  in=430,385,471 out=113,176,626 elapsed=244.1s

  [16659/20519] intraday_6141.csv.gz  in=430,397,973 out=113,176,626 elapsed=244.1s

  [16660/20519] intraday_6139.csv.gz  in=430,411,377 out=113,176,626 elapsed=244.1s

  [16661/20519] intraday_6138.csv.gz  in=430,426,235 out=113,176,626 elapsed=244.1s

  [16662/20519] intraday_6143.csv.gz  in=430,435,192 out=113,176,626 elapsed=244.1s

  [16663/20519] intraday_6145.csv.gz  in=430,449,216 out=113,176,626 elapsed=244.1s

  [16664/20519] intraday_6142.csv.gz  in=430,459,300 out=113,176,626 elapsed=244.1s

  [16665/20519] intraday_6144.csv.gz  in=430,473,744 out=113,176,626 elapsed=244.1s

  [16666/20519] intraday_6146.csv.gz  in=430,484,829 out=113,176,626 elapsed=244.2s

  [16667/20519] intraday_6147.csv.gz  in=430,497,151 out=113,176,626 elapsed=244.2s

  [16668/20519] intraday_6149.csv.gz  in=430,510,619 out=113,176,626 elapsed=244.2s

  [16669/20519] intraday_6148.csv.gz  in=430,539,026 out=113,176,626 elapsed=244.2s

  [16670/20519] intraday_6151.csv.gz  in=430,552,353 out=113,176,626 elapsed=244.2s

  [16671/20519] intraday_6152.csv.gz  in=430,565,222 out=113,176,626 elapsed=244.2s

  [16672/20519] intraday_6150.csv.gz  in=430,578,843 out=113,176,626 elapsed=244.2s

  [16673/20519] intraday_6153.csv.gz  in=430,590,645 out=113,176,626 elapsed=244.2s

  [16674/20519] intraday_6154.csv.gz  in=430,601,467 out=113,176,626 elapsed=244.2s

  [16675/20519] intraday_6155.csv.gz  in=430,613,830 out=113,176,626 elapsed=244.2s

  [16676/20519] intraday_6156.csv.gz  in=430,628,022 out=113,176,626 elapsed=244.2s

  [16677/20519] intraday_6157.csv.gz  in=430,643,473 out=113,176,626 elapsed=244.3s

  [16678/20519] intraday_6158.csv.gz  in=430,658,802 out=113,176,626 elapsed=244.3s

  [16679/20519] intraday_6160.csv.gz  in=430,670,587 out=113,176,626 elapsed=244.3s

  [16680/20519] intraday_6159.csv.gz  in=430,681,904 out=113,176,626 elapsed=244.3s

  [16681/20519] intraday_6161.csv.gz  in=430,694,661 out=113,176,626 elapsed=244.3s

  [16682/20519] intraday_6162.csv.gz  in=430,709,497 out=113,176,626 elapsed=244.3s

  [16683/20519] intraday_6163.csv.gz  in=430,720,870 out=113,176,626 elapsed=244.3s

  [16684/20519] intraday_6164.csv.gz  in=430,733,757 out=113,176,626 elapsed=244.3s

  [16685/20519] intraday_6165.csv.gz  in=430,744,622 out=113,176,626 elapsed=244.3s

  [16686/20519] intraday_6166.csv.gz  in=430,756,460 out=113,176,626 elapsed=244.3s

  [16687/20519] intraday_6167.csv.gz  in=430,767,229 out=113,176,626 elapsed=244.3s

  [16688/20519] intraday_6168.csv.gz  in=430,779,502 out=113,176,626 elapsed=244.3s

  [16689/20519] intraday_6169.csv.gz  in=430,792,705 out=113,176,626 elapsed=244.4s

  [16690/20519] intraday_6170.csv.gz  in=430,805,036 out=113,176,626 elapsed=244.4s

  [16691/20519] intraday_6171.csv.gz  in=430,818,547 out=113,176,626 elapsed=244.4s

  [16692/20519] intraday_6172.csv.gz  in=430,831,548 out=113,176,626 elapsed=244.4s

  [16693/20519] intraday_6175.csv.gz  in=430,844,230 out=113,176,626 elapsed=244.4s

  [16694/20519] intraday_6173.csv.gz  in=430,856,092 out=113,176,626 elapsed=244.4s

  [16695/20519] intraday_6174.csv.gz  in=430,868,834 out=113,176,626 elapsed=244.4s

  [16696/20519] intraday_6176.csv.gz  in=430,879,602 out=113,176,626 elapsed=244.4s

  [16697/20519] intraday_6177.csv.gz  in=430,892,085 out=113,176,626 elapsed=244.4s

  [16698/20519] intraday_6178.csv.gz  in=430,903,999 out=113,176,626 elapsed=244.4s

  [16699/20519] intraday_6179.csv.gz  in=430,917,608 out=113,176,626 elapsed=244.4s

  [16700/20519] intraday_6180.csv.gz  in=430,931,065 out=113,176,626 elapsed=244.4s

  [16701/20519] intraday_6181.csv.gz  in=430,942,845 out=113,176,626 elapsed=244.5s

  [16702/20519] intraday_6182.csv.gz  in=430,957,294 out=113,176,626 elapsed=244.5s

  [16703/20519] intraday_6183.csv.gz  in=430,970,258 out=113,176,626 elapsed=244.5s

  [16704/20519] intraday_6185.csv.gz  in=430,983,544 out=113,176,626 elapsed=244.5s

  [16705/20519] intraday_6184.csv.gz  in=430,996,308 out=113,176,626 elapsed=244.5s

  [16706/20519] intraday_6186.csv.gz  in=431,010,577 out=113,176,626 elapsed=244.5s

  [16707/20519] intraday_6188.csv.gz  in=431,022,885 out=113,176,626 elapsed=244.5s

  [16708/20519] intraday_6187.csv.gz  in=431,036,698 out=113,176,626 elapsed=244.5s

  [16709/20519] intraday_6190.csv.gz  in=431,049,020 out=113,176,626 elapsed=244.5s

  [16710/20519] intraday_6189.csv.gz  in=431,061,598 out=113,176,626 elapsed=244.5s

  [16711/20519] intraday_6191.csv.gz  in=431,072,118 out=113,176,626 elapsed=244.5s

  [16712/20519] intraday_6192.csv.gz  in=431,087,364 out=113,176,626 elapsed=244.6s

  [16713/20519] intraday_6195.csv.gz  in=431,099,951 out=113,176,626 elapsed=244.6s

  [16714/20519] intraday_6193.csv.gz  in=431,114,868 out=113,176,626 elapsed=244.6s

  [16715/20519] intraday_6194.csv.gz  in=431,127,512 out=113,176,626 elapsed=244.6s

  [16716/20519] intraday_6196.csv.gz  in=431,140,174 out=113,176,626 elapsed=244.6s

  [16717/20519] intraday_6197.csv.gz  in=431,150,579 out=113,176,626 elapsed=244.6s

  [16718/20519] intraday_6198.csv.gz  in=431,163,042 out=113,176,626 elapsed=244.6s

  [16719/20519] intraday_6199.csv.gz  in=431,175,934 out=113,176,626 elapsed=244.6s

  [16720/20519] intraday_6200.csv.gz  in=431,190,089 out=113,176,626 elapsed=244.6s

  [16721/20519] intraday_6201.csv.gz  in=431,201,212 out=113,176,626 elapsed=244.6s

  [16722/20519] intraday_6203.csv.gz  in=431,211,565 out=113,176,626 elapsed=244.7s

  [16723/20519] intraday_6204.csv.gz  in=431,226,200 out=113,176,626 elapsed=244.7s

  [16724/20519] intraday_6202.csv.gz  in=431,239,693 out=113,176,626 elapsed=244.7s

  [16725/20519] intraday_6205.csv.gz  in=431,250,992 out=113,176,626 elapsed=244.7s

  [16726/20519] intraday_6207.csv.gz  in=431,260,863 out=113,176,626 elapsed=244.7s

  [16727/20519] intraday_6209.csv.gz  in=431,273,226 out=113,176,626 elapsed=244.7s

  [16728/20519] intraday_6206.csv.gz  in=431,287,876 out=113,176,626 elapsed=244.7s

  [16729/20519] intraday_6208.csv.gz  in=431,299,408 out=113,176,626 elapsed=244.7s

  [16730/20519] intraday_6210.csv.gz  in=431,315,584 out=113,176,626 elapsed=244.7s

  [16731/20519] intraday_6211.csv.gz  in=431,332,228 out=113,176,626 elapsed=244.8s

  [16732/20519] intraday_6214.csv.gz  in=431,344,163 out=113,176,626 elapsed=244.8s

  [16733/20519] intraday_6212.csv.gz  in=431,356,895 out=113,176,626 elapsed=244.8s

  [16734/20519] intraday_6213.csv.gz  in=431,369,262 out=113,176,626 elapsed=244.8s

  [16735/20519] intraday_6217.csv.gz  in=431,383,475 out=113,176,626 elapsed=244.8s

  [16736/20519] intraday_6216.csv.gz  in=431,398,424 out=113,176,626 elapsed=244.8s

  [16737/20519] intraday_6215.csv.gz  in=431,412,633 out=113,176,626 elapsed=244.8s

  [16738/20519] intraday_6218.csv.gz  in=431,424,656 out=113,176,626 elapsed=244.8s

  [16739/20519] intraday_6220.csv.gz  in=431,438,352 out=113,176,626 elapsed=244.8s

  [16740/20519] intraday_6221.csv.gz  in=431,452,123 out=113,176,626 elapsed=244.9s

  [16741/20519] intraday_6219.csv.gz  in=431,466,431 out=113,176,626 elapsed=244.9s

  [16742/20519] intraday_6222.csv.gz  in=431,478,964 out=113,176,626 elapsed=244.9s

  [16743/20519] intraday_6223.csv.gz  in=431,492,069 out=113,176,626 elapsed=244.9s

  [16744/20519] intraday_6225.csv.gz  in=431,505,497 out=113,176,626 elapsed=244.9s

  [16745/20519] intraday_6226.csv.gz  in=431,519,560 out=113,176,626 elapsed=244.9s

  [16746/20519] intraday_6224.csv.gz  in=431,532,789 out=113,176,626 elapsed=244.9s

  [16747/20519] intraday_6227.csv.gz  in=431,544,382 out=113,176,626 elapsed=244.9s

  [16748/20519] intraday_6228.csv.gz  in=431,555,885 out=113,176,626 elapsed=244.9s

  [16749/20519] intraday_6230.csv.gz  in=431,569,573 out=113,176,626 elapsed=244.9s

  [16750/20519] intraday_6229.csv.gz  in=431,587,087 out=113,176,626 elapsed=244.9s

  [16751/20519] intraday_6231.csv.gz  in=431,600,151 out=113,176,626 elapsed=244.9s

  [16752/20519] intraday_6232.csv.gz  in=431,614,825 out=113,176,626 elapsed=245.0s

  [16753/20519] intraday_6234.csv.gz  in=431,628,208 out=113,176,626 elapsed=245.0s

  [16754/20519] intraday_6233.csv.gz  in=431,643,029 out=113,176,626 elapsed=245.0s

  [16755/20519] intraday_6235.csv.gz  in=431,656,595 out=113,176,626 elapsed=245.0s

  [16756/20519] intraday_6238.csv.gz  in=431,668,230 out=113,176,626 elapsed=245.0s

  [16757/20519] intraday_6237.csv.gz  in=431,682,891 out=113,176,626 elapsed=245.0s

  [16758/20519] intraday_6236.csv.gz  in=431,697,788 out=113,176,626 elapsed=245.0s

  [16759/20519] intraday_6239.csv.gz  in=431,713,140 out=113,176,626 elapsed=245.0s

  [16760/20519] intraday_6242.csv.gz  in=431,728,242 out=113,176,626 elapsed=245.0s

  [16761/20519] intraday_6240.csv.gz  in=431,741,078 out=113,176,626 elapsed=245.0s

  [16762/20519] intraday_6241.csv.gz  in=431,755,239 out=113,176,626 elapsed=245.0s

  [16763/20519] intraday_6243.csv.gz  in=431,770,545 out=113,176,626 elapsed=245.0s

  [16764/20519] intraday_6245.csv.gz  in=431,784,800 out=113,176,626 elapsed=245.1s

  [16765/20519] intraday_6244.csv.gz  in=431,799,073 out=113,176,626 elapsed=245.1s

  [16766/20519] intraday_6246.csv.gz  in=431,811,631 out=113,176,626 elapsed=245.1s

  [16767/20519] intraday_6248.csv.gz  in=431,822,487 out=113,176,626 elapsed=245.1s

  [16768/20519] intraday_6247.csv.gz  in=431,834,918 out=113,176,626 elapsed=245.1s

  [16769/20519] intraday_6249.csv.gz  in=431,850,411 out=113,176,626 elapsed=245.1s

  [16770/20519] intraday_6250.csv.gz  in=431,861,517 out=113,176,626 elapsed=245.1s

  [16771/20519] intraday_6251.csv.gz  in=431,875,298 out=113,176,626 elapsed=245.1s

  [16772/20519] intraday_6252.csv.gz  in=431,888,786 out=113,176,626 elapsed=245.1s

  [16773/20519] intraday_6253.csv.gz  in=431,904,450 out=113,176,626 elapsed=245.1s

  [16774/20519] intraday_6254.csv.gz  in=431,915,860 out=113,176,626 elapsed=245.1s

  [16775/20519] intraday_6255.csv.gz  in=431,929,406 out=113,176,626 elapsed=245.2s

  [16776/20519] intraday_6257.csv.gz  in=431,942,239 out=113,176,626 elapsed=245.2s

  [16777/20519] intraday_6256.csv.gz  in=431,955,253 out=113,176,626 elapsed=245.2s

  [16778/20519] intraday_6258.csv.gz  in=431,969,530 out=113,176,626 elapsed=245.2s

  [16779/20519] intraday_6259.csv.gz  in=431,984,533 out=113,176,626 elapsed=245.2s

  [16780/20519] intraday_6261.csv.gz  in=431,998,621 out=113,176,626 elapsed=245.2s

  [16781/20519] intraday_6260.csv.gz  in=432,013,691 out=113,176,626 elapsed=245.2s

  [16782/20519] intraday_6263.csv.gz  in=432,025,020 out=113,176,626 elapsed=245.2s

  [16783/20519] intraday_6262.csv.gz  in=432,039,301 out=113,176,626 elapsed=245.2s

  [16784/20519] intraday_6265.csv.gz  in=432,051,677 out=113,176,626 elapsed=245.2s

  [16785/20519] intraday_6266.csv.gz  in=432,065,358 out=113,176,626 elapsed=245.2s

  [16786/20519] intraday_6264.csv.gz  in=432,079,305 out=113,176,626 elapsed=245.3s

  [16787/20519] intraday_6267.csv.gz  in=432,090,060 out=113,176,626 elapsed=245.3s

  [16788/20519] intraday_6269.csv.gz  in=432,101,935 out=113,176,626 elapsed=245.3s

  [16789/20519] intraday_6270.csv.gz  in=432,104,582 out=113,176,626 elapsed=245.3s

  [16790/20519] intraday_6268.csv.gz  in=432,113,906 out=113,176,626 elapsed=245.3s

  [16791/20519] intraday_6271.csv.gz  in=432,129,503 out=113,176,626 elapsed=245.3s

  [16792/20519] intraday_6272.csv.gz  in=432,142,994 out=113,176,626 elapsed=245.3s

  [16793/20519] intraday_6273.csv.gz  in=432,164,781 out=113,176,626 elapsed=245.3s

  [16794/20519] intraday_6274.csv.gz  in=432,192,410 out=113,176,626 elapsed=245.3s

  [16795/20519] intraday_6275.csv.gz  in=432,205,529 out=113,176,626 elapsed=245.3s

  [16796/20519] intraday_6276.csv.gz  in=432,220,128 out=113,176,626 elapsed=245.3s

  [16797/20519] intraday_6277.csv.gz  in=432,237,643 out=113,176,626 elapsed=245.4s

  [16798/20519] intraday_6279.csv.gz  in=432,252,571 out=113,176,626 elapsed=245.4s

  [16799/20519] intraday_6278.csv.gz  in=432,263,386 out=113,176,626 elapsed=245.4s

  [16800/20519] intraday_6280.csv.gz  in=432,278,334 out=113,176,626 elapsed=245.4s

  [16801/20519] intraday_6283.csv.gz  in=432,290,861 out=113,176,626 elapsed=245.4s

  [16802/20519] intraday_6282.csv.gz  in=432,304,097 out=113,176,626 elapsed=245.4s

  [16803/20519] intraday_6281.csv.gz  in=432,320,672 out=113,176,626 elapsed=245.4s

  [16804/20519] intraday_6284.csv.gz  in=432,334,075 out=113,176,626 elapsed=245.4s

  [16805/20519] intraday_6285.csv.gz  in=432,343,501 out=113,176,626 elapsed=245.4s

  [16806/20519] intraday_6286.csv.gz  in=432,352,979 out=113,176,626 elapsed=245.5s

  [16807/20519] intraday_6287.csv.gz  in=432,366,895 out=113,176,626 elapsed=245.5s

  [16808/20519] intraday_6289.csv.gz  in=432,377,963 out=113,176,626 elapsed=245.5s

  [16809/20519] intraday_6288.csv.gz  in=432,390,963 out=113,176,626 elapsed=245.5s

  [16810/20519] intraday_6290.csv.gz  in=432,404,654 out=113,176,626 elapsed=245.5s

  [16811/20519] intraday_6291.csv.gz  in=432,417,302 out=113,176,626 elapsed=245.5s

  [16812/20519] intraday_6293.csv.gz  in=432,431,234 out=113,176,626 elapsed=245.5s

  [16813/20519] intraday_6292.csv.gz  in=432,443,313 out=113,176,626 elapsed=245.5s

  [16814/20519] intraday_6294.csv.gz  in=432,457,629 out=113,176,626 elapsed=245.5s

  [16815/20519] intraday_6295.csv.gz  in=432,470,707 out=113,176,626 elapsed=245.5s

  [16816/20519] intraday_6296.csv.gz  in=432,482,671 out=113,176,626 elapsed=245.5s

  [16817/20519] intraday_6297.csv.gz  in=432,494,277 out=113,176,626 elapsed=245.6s

  [16818/20519] intraday_6298.csv.gz  in=432,508,349 out=113,176,626 elapsed=245.6s

  [16819/20519] intraday_6299.csv.gz  in=432,521,247 out=113,176,626 elapsed=245.6s

  [16820/20519] intraday_6300.csv.gz  in=432,545,229 out=113,176,626 elapsed=245.6s

  [16821/20519] intraday_6301.csv.gz  in=432,562,190 out=113,176,626 elapsed=245.6s

  [16822/20519] intraday_6302.csv.gz  in=432,575,048 out=113,176,626 elapsed=245.6s

  [16823/20519] intraday_6303.csv.gz  in=432,585,394 out=113,176,626 elapsed=245.6s

  [16824/20519] intraday_6304.csv.gz  in=432,598,224 out=113,176,626 elapsed=245.6s

  [16825/20519] intraday_6306.csv.gz  in=432,610,104 out=113,176,626 elapsed=245.7s

  [16826/20519] intraday_6305.csv.gz  in=432,633,404 out=113,176,626 elapsed=245.7s

  [16827/20519] intraday_6307.csv.gz  in=432,645,280 out=113,176,626 elapsed=245.7s

  [16828/20519] intraday_6308.csv.gz  in=432,655,778 out=113,176,626 elapsed=245.7s

  [16829/20519] intraday_6309.csv.gz  in=432,668,438 out=113,176,626 elapsed=245.7s

  [16830/20519] intraday_6311.csv.gz  in=432,679,118 out=113,176,626 elapsed=245.7s

  [16831/20519] intraday_6310.csv.gz  in=432,701,014 out=113,176,626 elapsed=245.7s

  [16832/20519] intraday_6312.csv.gz  in=432,718,080 out=113,176,626 elapsed=245.7s

  [16833/20519] intraday_6313.csv.gz  in=432,732,288 out=113,176,626 elapsed=245.7s

  [16834/20519] intraday_6314.csv.gz  in=432,742,998 out=113,176,626 elapsed=245.7s

  [16835/20519] intraday_6316.csv.gz  in=432,753,456 out=113,176,626 elapsed=245.8s

  [16836/20519] intraday_6315.csv.gz  in=432,767,112 out=113,176,626 elapsed=245.8s

  [16837/20519] intraday_6318.csv.gz  in=432,780,582 out=113,176,626 elapsed=245.8s

  [16838/20519] intraday_6317.csv.gz  in=432,795,343 out=113,176,626 elapsed=245.8s

  [16839/20519] intraday_6320.csv.gz  in=432,816,419 out=113,176,626 elapsed=245.8s

  [16840/20519] intraday_6319.csv.gz  in=432,830,835 out=113,176,626 elapsed=245.8s

  [16841/20519] intraday_6321.csv.gz  in=432,842,595 out=113,176,626 elapsed=245.8s

  [16842/20519] intraday_6322.csv.gz  in=432,852,975 out=113,176,626 elapsed=245.9s

  [16843/20519] intraday_6323.csv.gz  in=432,867,266 out=113,176,626 elapsed=245.9s

  [16844/20519] intraday_6324.csv.gz  in=432,877,741 out=113,176,626 elapsed=245.9s

  [16845/20519] intraday_6325.csv.gz  in=432,892,196 out=113,176,626 elapsed=245.9s

  [16846/20519] intraday_6326.csv.gz  in=432,905,509 out=113,176,626 elapsed=245.9s

  [16847/20519] intraday_6327.csv.gz  in=432,918,145 out=113,176,626 elapsed=245.9s

  [16848/20519] intraday_6328.csv.gz  in=432,933,716 out=113,176,626 elapsed=245.9s

  [16849/20519] intraday_6329.csv.gz  in=432,946,598 out=113,176,626 elapsed=245.9s

  [16850/20519] intraday_6331.csv.gz  in=432,958,298 out=113,176,626 elapsed=245.9s

  [16851/20519] intraday_6330.csv.gz  in=432,972,678 out=113,176,626 elapsed=245.9s

  [16852/20519] intraday_6332.csv.gz  in=432,986,904 out=113,176,626 elapsed=245.9s

  [16853/20519] intraday_6333.csv.gz  in=432,998,540 out=113,176,626 elapsed=245.9s

  [16854/20519] intraday_6334.csv.gz  in=433,008,365 out=113,176,626 elapsed=246.0s

  [16855/20519] intraday_6335.csv.gz  in=433,020,139 out=113,176,626 elapsed=246.0s

  [16856/20519] intraday_6337.csv.gz  in=433,035,095 out=113,176,626 elapsed=246.0s

  [16857/20519] intraday_6336.csv.gz  in=433,049,403 out=113,176,626 elapsed=246.0s

  [16858/20519] intraday_6338.csv.gz  in=433,063,258 out=113,176,626 elapsed=246.0s

  [16859/20519] intraday_6339.csv.gz  in=433,075,950 out=113,176,626 elapsed=246.0s

  [16860/20519] intraday_6340.csv.gz  in=433,087,323 out=113,176,626 elapsed=246.0s

  [16861/20519] intraday_6341.csv.gz  in=433,099,036 out=113,176,626 elapsed=246.0s

  [16862/20519] intraday_6343.csv.gz  in=433,111,294 out=113,176,626 elapsed=246.0s

  [16863/20519] intraday_6342.csv.gz  in=433,123,103 out=113,176,626 elapsed=246.0s

  [16864/20519] intraday_6344.csv.gz  in=433,136,341 out=113,176,626 elapsed=246.0s

  [16865/20519] intraday_6345.csv.gz  in=433,149,135 out=113,176,626 elapsed=246.1s

  [16866/20519] intraday_6346.csv.gz  in=433,160,824 out=113,176,626 elapsed=246.1s

  [16867/20519] intraday_6347.csv.gz  in=433,171,347 out=113,176,626 elapsed=246.1s

  [16868/20519] intraday_6348.csv.gz  in=433,185,392 out=113,176,626 elapsed=246.1s

  [16869/20519] intraday_6349.csv.gz  in=433,196,893 out=113,176,626 elapsed=246.1s

  [16870/20519] intraday_6351.csv.gz  in=433,206,567 out=113,176,626 elapsed=246.1s

  [16871/20519] intraday_6350.csv.gz  in=433,219,966 out=113,176,626 elapsed=246.1s

  [16872/20519] intraday_6352.csv.gz  in=433,232,370 out=113,176,626 elapsed=246.1s

  [16873/20519] intraday_6353.csv.gz  in=433,245,633 out=113,176,626 elapsed=246.1s

  [16874/20519] intraday_6354.csv.gz  in=433,260,713 out=113,176,626 elapsed=246.1s

  [16875/20519] intraday_6355.csv.gz  in=433,276,310 out=113,176,626 elapsed=246.2s

  [16876/20519] intraday_6356.csv.gz  in=433,291,973 out=113,176,626 elapsed=246.2s

  [16877/20519] intraday_6357.csv.gz  in=433,303,435 out=113,176,626 elapsed=246.2s

  [16878/20519] intraday_6359.csv.gz  in=433,316,962 out=113,176,626 elapsed=246.2s

  [16879/20519] intraday_6358.csv.gz  in=433,329,936 out=113,176,626 elapsed=246.2s

  [16880/20519] intraday_6360.csv.gz  in=433,346,313 out=113,176,626 elapsed=246.2s

  [16881/20519] intraday_6361.csv.gz  in=433,367,673 out=113,176,626 elapsed=246.2s

  [16882/20519] intraday_6362.csv.gz  in=433,380,768 out=113,176,626 elapsed=246.2s

  [16883/20519] intraday_6364.csv.gz  in=433,394,637 out=113,176,626 elapsed=246.2s

  [16884/20519] intraday_6363.csv.gz  in=433,407,929 out=113,176,626 elapsed=246.3s

  [16885/20519] intraday_6365.csv.gz  in=433,422,539 out=113,176,626 elapsed=246.3s

  [16886/20519] intraday_6366.csv.gz  in=433,434,944 out=113,176,626 elapsed=246.3s

  [16887/20519] intraday_6367.csv.gz  in=433,447,888 out=113,176,626 elapsed=246.3s

  [16888/20519] intraday_6368.csv.gz  in=433,461,115 out=113,176,626 elapsed=246.3s

  [16889/20519] intraday_6369.csv.gz  in=433,473,507 out=113,176,626 elapsed=246.3s

  [16890/20519] intraday_6370.csv.gz  in=433,487,626 out=113,176,626 elapsed=246.3s

  [16891/20519] intraday_6371.csv.gz  in=433,499,512 out=113,176,626 elapsed=246.3s

  [16892/20519] intraday_6372.csv.gz  in=433,517,967 out=113,176,626 elapsed=246.3s

  [16893/20519] intraday_6373.csv.gz  in=433,532,622 out=113,176,626 elapsed=246.3s

  [16894/20519] intraday_6374.csv.gz  in=433,546,210 out=113,176,626 elapsed=246.3s

  [16895/20519] intraday_6375.csv.gz  in=433,559,322 out=113,176,626 elapsed=246.4s

  [16896/20519] intraday_6376.csv.gz  in=433,573,693 out=113,176,626 elapsed=246.4s

  [16897/20519] intraday_6377.csv.gz  in=433,588,192 out=113,176,626 elapsed=246.4s

  [16898/20519] intraday_6378.csv.gz  in=433,600,825 out=113,176,626 elapsed=246.4s

  [16899/20519] intraday_6379.csv.gz  in=433,614,326 out=113,176,626 elapsed=246.4s

  [16900/20519] intraday_6381.csv.gz  in=433,627,656 out=113,176,626 elapsed=246.4s

  [16901/20519] intraday_6380.csv.gz  in=433,643,166 out=113,176,626 elapsed=246.4s

  [16902/20519] intraday_6382.csv.gz  in=433,654,934 out=113,176,626 elapsed=246.4s

  [16903/20519] intraday_6383.csv.gz  in=433,669,267 out=113,176,626 elapsed=246.4s

  [16904/20519] intraday_6384.csv.gz  in=433,681,101 out=113,176,626 elapsed=246.4s

  [16905/20519] intraday_6385.csv.gz  in=433,695,444 out=113,176,626 elapsed=246.4s

  [16906/20519] intraday_6387.csv.gz  in=433,710,199 out=113,176,626 elapsed=246.4s

  [16907/20519] intraday_6386.csv.gz  in=433,726,126 out=113,176,626 elapsed=246.4s

  [16908/20519] intraday_6388.csv.gz  in=433,740,819 out=113,176,626 elapsed=246.4s

  [16909/20519] intraday_6389.csv.gz  in=433,753,775 out=113,176,626 elapsed=246.4s

  [16910/20519] intraday_6391.csv.gz  in=433,766,564 out=113,176,626 elapsed=246.5s

  [16911/20519] intraday_6392.csv.gz  in=433,777,578 out=113,176,626 elapsed=246.5s

  [16912/20519] intraday_6390.csv.gz  in=433,794,804 out=113,176,626 elapsed=246.5s

  [16913/20519] intraday_6393.csv.gz  in=433,808,606 out=113,176,626 elapsed=246.5s

  [16914/20519] intraday_6394.csv.gz  in=433,820,345 out=113,176,626 elapsed=246.5s

  [16915/20519] intraday_6395.csv.gz  in=433,832,770 out=113,176,626 elapsed=246.5s

  [16916/20519] intraday_6396.csv.gz  in=433,846,731 out=113,176,626 elapsed=246.5s

  [16917/20519] intraday_6399.csv.gz  in=433,858,802 out=113,176,626 elapsed=246.5s

  [16918/20519] intraday_6398.csv.gz  in=433,870,454 out=113,176,626 elapsed=246.5s

  [16919/20519] intraday_6397.csv.gz  in=433,896,964 out=113,176,626 elapsed=246.5s

  [16920/20519] intraday_6400.csv.gz  in=433,910,265 out=113,176,626 elapsed=246.6s

  [16921/20519] intraday_6401.csv.gz  in=433,921,991 out=113,176,626 elapsed=246.6s

  [16922/20519] intraday_6402.csv.gz  in=433,937,706 out=113,176,626 elapsed=246.6s

  [16923/20519] intraday_6403.csv.gz  in=433,951,880 out=113,176,626 elapsed=246.6s

  [16924/20519] intraday_6404.csv.gz  in=433,966,619 out=113,176,626 elapsed=246.6s

  [16925/20519] intraday_6405.csv.gz  in=433,981,266 out=113,176,626 elapsed=246.6s

  [16926/20519] intraday_6406.csv.gz  in=433,995,261 out=113,176,626 elapsed=246.6s

  [16927/20519] intraday_6408.csv.gz  in=434,008,065 out=113,176,626 elapsed=246.6s

  [16928/20519] intraday_6407.csv.gz  in=434,019,537 out=113,176,626 elapsed=246.6s

  [16929/20519] intraday_6409.csv.gz  in=434,031,979 out=113,176,626 elapsed=246.7s

  [16930/20519] intraday_6410.csv.gz  in=434,044,963 out=113,176,626 elapsed=246.7s

  [16931/20519] intraday_6411.csv.gz  in=434,055,203 out=113,176,626 elapsed=246.7s

  [16932/20519] intraday_6412.csv.gz  in=434,064,111 out=113,176,626 elapsed=246.7s

  [16933/20519] intraday_6414.csv.gz  in=434,066,794 out=113,176,626 elapsed=246.7s

  [16934/20519] intraday_6413.csv.gz  in=434,079,365 out=113,176,626 elapsed=246.7s

  [16935/20519] intraday_6415.csv.gz  in=434,095,694 out=113,176,626 elapsed=246.8s

  [16936/20519] intraday_6416.csv.gz  in=434,108,595 out=113,176,626 elapsed=246.8s

  [16937/20519] intraday_6418.csv.gz  in=434,119,838 out=113,176,626 elapsed=246.8s

  [16938/20519] intraday_6417.csv.gz  in=434,133,825 out=113,176,626 elapsed=246.8s

  [16939/20519] intraday_6419.csv.gz  in=434,146,696 out=113,176,626 elapsed=246.8s

  [16940/20519] intraday_6420.csv.gz  in=434,160,974 out=113,176,626 elapsed=246.8s

  [16941/20519] intraday_6421.csv.gz  in=434,176,008 out=113,176,626 elapsed=246.8s

  [16942/20519] intraday_6422.csv.gz  in=434,188,717 out=113,176,626 elapsed=246.8s

  [16943/20519] intraday_6423.csv.gz  in=434,202,670 out=113,176,626 elapsed=246.8s

  [16944/20519] intraday_6424.csv.gz  in=434,217,167 out=113,176,626 elapsed=246.8s

  [16945/20519] intraday_6425.csv.gz  in=434,233,157 out=113,176,626 elapsed=246.9s

  [16946/20519] intraday_6426.csv.gz  in=434,247,007 out=113,176,626 elapsed=246.9s

  [16947/20519] intraday_6428.csv.gz  in=434,259,492 out=113,176,626 elapsed=246.9s

  [16948/20519] intraday_6427.csv.gz  in=434,273,210 out=113,176,626 elapsed=246.9s

  [16949/20519] intraday_6429.csv.gz  in=434,284,102 out=113,176,626 elapsed=246.9s

  [16950/20519] intraday_6430.csv.gz  in=434,293,737 out=113,176,626 elapsed=246.9s

  [16951/20519] intraday_6431.csv.gz  in=434,307,520 out=113,176,626 elapsed=246.9s

  [16952/20519] intraday_6433.csv.gz  in=434,317,938 out=113,176,626 elapsed=246.9s

  [16953/20519] intraday_6432.csv.gz  in=434,331,879 out=113,176,626 elapsed=246.9s

  [16954/20519] intraday_6434.csv.gz  in=434,345,240 out=113,176,626 elapsed=247.0s

  [16955/20519] intraday_6436.csv.gz  in=434,358,151 out=113,176,626 elapsed=247.0s

  [16956/20519] intraday_6435.csv.gz  in=434,370,536 out=113,176,626 elapsed=247.0s

  [16957/20519] intraday_6438.csv.gz  in=434,383,959 out=113,176,626 elapsed=247.0s

  [16958/20519] intraday_6437.csv.gz  in=434,396,201 out=113,176,626 elapsed=247.0s

  [16959/20519] intraday_6442.csv.gz  in=434,408,035 out=113,176,626 elapsed=247.0s

  [16960/20519] intraday_6439.csv.gz  in=434,420,368 out=113,176,626 elapsed=247.0s

  [16961/20519] intraday_6441.csv.gz  in=434,431,820 out=113,176,626 elapsed=247.0s

  [16962/20519] intraday_6440.csv.gz  in=434,443,204 out=113,176,626 elapsed=247.0s

  [16963/20519] intraday_6443.csv.gz  in=434,456,005 out=113,176,626 elapsed=247.0s

  [16964/20519] intraday_6445.csv.gz  in=434,473,309 out=113,176,626 elapsed=247.1s

  [16965/20519] intraday_6444.csv.gz  in=434,487,790 out=113,176,626 elapsed=247.1s

  [16966/20519] intraday_6446.csv.gz  in=434,498,640 out=113,176,626 elapsed=247.1s

  [16967/20519] intraday_6447.csv.gz  in=434,509,365 out=113,176,626 elapsed=247.1s

  [16968/20519] intraday_6448.csv.gz  in=434,522,470 out=113,176,626 elapsed=247.1s

  [16969/20519] intraday_6449.csv.gz  in=434,537,393 out=113,176,626 elapsed=247.1s

  [16970/20519] intraday_6450.csv.gz  in=434,549,336 out=113,176,626 elapsed=247.1s

  [16971/20519] intraday_6451.csv.gz  in=434,563,019 out=113,176,626 elapsed=247.1s

  [16972/20519] intraday_6454.csv.gz  in=434,574,155 out=113,176,626 elapsed=247.1s

  [16973/20519] intraday_6452.csv.gz  in=434,584,642 out=113,176,626 elapsed=247.2s

  [16974/20519] intraday_6455.csv.gz  in=434,596,602 out=113,176,626 elapsed=247.2s

  [16975/20519] intraday_6453.csv.gz  in=434,609,005 out=113,176,626 elapsed=247.2s

  [16976/20519] intraday_6456.csv.gz  in=434,622,216 out=113,176,626 elapsed=247.2s

  [16977/20519] intraday_6458.csv.gz  in=434,635,747 out=113,176,626 elapsed=247.2s

  [16978/20519] intraday_6457.csv.gz  in=434,649,004 out=113,176,626 elapsed=247.2s

  [16979/20519] intraday_6459.csv.gz  in=434,662,025 out=113,176,626 elapsed=247.2s

  [16980/20519] intraday_6460.csv.gz  in=434,673,052 out=113,176,626 elapsed=247.2s

  [16981/20519] intraday_6463.csv.gz  in=434,684,064 out=113,176,626 elapsed=247.2s

  [16982/20519] intraday_6462.csv.gz  in=434,695,670 out=113,176,626 elapsed=247.2s

  [16983/20519] intraday_6461.csv.gz  in=434,708,746 out=113,176,626 elapsed=247.2s

  [16984/20519] intraday_6464.csv.gz  in=434,720,466 out=113,176,626 elapsed=247.3s

  [16985/20519] intraday_6465.csv.gz  in=434,732,406 out=113,176,626 elapsed=247.3s

  [16986/20519] intraday_6467.csv.gz  in=434,745,088 out=113,176,626 elapsed=247.3s

  [16987/20519] intraday_6466.csv.gz  in=434,758,043 out=113,176,626 elapsed=247.3s

  [16988/20519] intraday_6468.csv.gz  in=434,769,786 out=113,176,626 elapsed=247.3s

  [16989/20519] intraday_6470.csv.gz  in=434,782,827 out=113,176,626 elapsed=247.3s

  [16990/20519] intraday_6469.csv.gz  in=434,797,823 out=113,176,626 elapsed=247.3s

  [16991/20519] intraday_6471.csv.gz  in=434,809,747 out=113,176,626 elapsed=247.3s

  [16992/20519] intraday_6472.csv.gz  in=434,820,736 out=113,176,626 elapsed=247.3s

  [16993/20519] intraday_6475.csv.gz  in=434,832,979 out=113,176,626 elapsed=247.3s

  [16994/20519] intraday_6474.csv.gz  in=434,847,517 out=113,176,626 elapsed=247.4s

  [16995/20519] intraday_6473.csv.gz  in=434,861,605 out=113,176,626 elapsed=247.4s

  [16996/20519] intraday_6477.csv.gz  in=434,873,883 out=113,176,626 elapsed=247.4s

  [16997/20519] intraday_6476.csv.gz  in=434,885,889 out=113,176,626 elapsed=247.4s

  [16998/20519] intraday_6478.csv.gz  in=434,896,886 out=113,176,626 elapsed=247.4s

  [16999/20519] intraday_6479.csv.gz  in=434,910,959 out=113,176,626 elapsed=247.4s

  [17000/20519] intraday_6481.csv.gz  in=434,922,493 out=113,176,626 elapsed=247.4s

  [17001/20519] intraday_6480.csv.gz  in=434,938,835 out=113,176,626 elapsed=247.4s

  [17002/20519] intraday_6482.csv.gz  in=434,951,344 out=113,176,626 elapsed=247.4s

  [17003/20519] intraday_6483.csv.gz  in=434,964,530 out=113,176,626 elapsed=247.4s

  [17004/20519] intraday_6485.csv.gz  in=434,975,856 out=113,176,626 elapsed=247.4s

  [17005/20519] intraday_6484.csv.gz  in=434,986,434 out=113,176,626 elapsed=247.5s

  [17006/20519] intraday_6486.csv.gz  in=434,998,315 out=113,176,626 elapsed=247.5s

  [17007/20519] intraday_6487.csv.gz  in=435,013,139 out=113,176,626 elapsed=247.5s

  [17008/20519] intraday_6488.csv.gz  in=435,024,262 out=113,176,626 elapsed=247.5s

  [17009/20519] intraday_6489.csv.gz  in=435,037,256 out=113,176,626 elapsed=247.5s

  [17010/20519] intraday_6490.csv.gz  in=435,047,652 out=113,176,626 elapsed=247.5s

  [17011/20519] intraday_6491.csv.gz  in=435,061,783 out=113,176,626 elapsed=247.5s

  [17012/20519] intraday_6492.csv.gz  in=435,074,191 out=113,176,626 elapsed=247.5s

  [17013/20519] intraday_6493.csv.gz  in=435,088,078 out=113,176,626 elapsed=247.5s

  [17014/20519] intraday_6494.csv.gz  in=435,098,845 out=113,176,626 elapsed=247.5s

  [17015/20519] intraday_6495.csv.gz  in=435,109,487 out=113,176,626 elapsed=247.6s

  [17016/20519] intraday_6496.csv.gz  in=435,121,839 out=113,176,626 elapsed=247.6s

  [17017/20519] intraday_6497.csv.gz  in=435,138,034 out=113,176,626 elapsed=247.6s

  [17018/20519] intraday_6501.csv.gz  in=435,149,502 out=113,176,626 elapsed=247.6s

  [17019/20519] intraday_6498.csv.gz  in=435,165,984 out=113,176,626 elapsed=247.6s

  [17020/20519] intraday_6500.csv.gz  in=435,179,300 out=113,176,626 elapsed=247.6s

  [17021/20519] intraday_6499.csv.gz  in=435,193,291 out=113,176,626 elapsed=247.7s

  [17022/20519] intraday_6503.csv.gz  in=435,207,546 out=113,176,626 elapsed=247.7s

  [17023/20519] intraday_6504.csv.gz  in=435,222,074 out=113,176,626 elapsed=247.7s

  [17024/20519] intraday_6502.csv.gz  in=435,236,586 out=113,176,626 elapsed=247.7s

  [17025/20519] intraday_6505.csv.gz  in=435,248,658 out=113,176,626 elapsed=247.7s

  [17026/20519] intraday_6507.csv.gz  in=435,262,801 out=113,176,626 elapsed=247.7s

  [17027/20519] intraday_6506.csv.gz  in=435,279,434 out=113,176,626 elapsed=247.7s

  [17028/20519] intraday_6508.csv.gz  in=435,293,135 out=113,176,626 elapsed=247.8s

  [17029/20519] intraday_6509.csv.gz  in=435,305,705 out=113,176,626 elapsed=247.8s

  [17030/20519] intraday_6510.csv.gz  in=435,319,093 out=113,176,626 elapsed=247.8s

  [17031/20519] intraday_6511.csv.gz  in=435,331,402 out=113,176,626 elapsed=247.8s

  [17032/20519] intraday_6513.csv.gz  in=435,343,955 out=113,176,626 elapsed=247.8s

  [17033/20519] intraday_6515.csv.gz  in=435,356,050 out=113,176,626 elapsed=247.8s

  [17034/20519] intraday_6514.csv.gz  in=435,368,964 out=113,176,626 elapsed=247.8s

  [17035/20519] intraday_6512.csv.gz  in=435,383,529 out=113,176,626 elapsed=247.8s

  [17036/20519] intraday_6516.csv.gz  in=435,398,585 out=113,176,626 elapsed=247.9s

  [17037/20519] intraday_6517.csv.gz  in=435,413,835 out=113,176,626 elapsed=247.9s

  [17038/20519] intraday_6518.csv.gz  in=435,427,775 out=113,176,626 elapsed=247.9s

  [17039/20519] intraday_6519.csv.gz  in=435,438,605 out=113,176,626 elapsed=247.9s

  [17040/20519] intraday_6522.csv.gz  in=435,450,192 out=113,176,626 elapsed=247.9s

  [17041/20519] intraday_6521.csv.gz  in=435,462,920 out=113,176,626 elapsed=247.9s

  [17042/20519] intraday_6523.csv.gz  in=435,477,887 out=113,176,626 elapsed=247.9s

  [17043/20519] intraday_6520.csv.gz  in=435,510,963 out=113,176,626 elapsed=247.9s

  [17044/20519] intraday_6525.csv.gz  in=435,522,935 out=113,176,626 elapsed=247.9s

  [17045/20519] intraday_6524.csv.gz  in=435,536,253 out=113,176,626 elapsed=247.9s

  [17046/20519] intraday_6526.csv.gz  in=435,551,102 out=113,176,626 elapsed=247.9s

  [17047/20519] intraday_6527.csv.gz  in=435,573,486 out=113,176,626 elapsed=248.0s

  [17048/20519] intraday_6528.csv.gz  in=435,587,031 out=113,176,626 elapsed=248.0s

  [17049/20519] intraday_6531.csv.gz  in=435,599,530 out=113,176,626 elapsed=248.0s

  [17050/20519] intraday_6529.csv.gz  in=435,615,500 out=113,176,626 elapsed=248.0s

  [17051/20519] intraday_6530.csv.gz  in=435,632,234 out=113,176,626 elapsed=248.0s

  [17052/20519] intraday_6532.csv.gz  in=435,648,137 out=113,176,626 elapsed=248.0s

  [17053/20519] intraday_6534.csv.gz  in=435,661,253 out=113,176,626 elapsed=248.0s

  [17054/20519] intraday_6533.csv.gz  in=435,672,909 out=113,176,626 elapsed=248.0s

  [17055/20519] intraday_6535.csv.gz  in=435,684,194 out=113,176,626 elapsed=248.0s

  [17056/20519] intraday_6536.csv.gz  in=435,698,704 out=113,176,626 elapsed=248.0s

  [17057/20519] intraday_6538.csv.gz  in=435,712,814 out=113,176,626 elapsed=248.1s

  [17058/20519] intraday_6537.csv.gz  in=435,724,065 out=113,176,626 elapsed=248.1s

  [17059/20519] intraday_6539.csv.gz  in=435,736,382 out=113,176,626 elapsed=248.1s

  [17060/20519] intraday_6540.csv.gz  in=435,751,721 out=113,176,626 elapsed=248.1s

  [17061/20519] intraday_6541.csv.gz  in=435,764,931 out=113,176,626 elapsed=248.1s

  [17062/20519] intraday_6542.csv.gz  in=435,777,671 out=113,176,626 elapsed=248.1s

  [17063/20519] intraday_6544.csv.gz  in=435,790,082 out=113,176,626 elapsed=248.1s

  [17064/20519] intraday_6543.csv.gz  in=435,803,153 out=113,176,626 elapsed=248.1s

  [17065/20519] intraday_6546.csv.gz  in=435,817,703 out=113,176,626 elapsed=248.1s

  [17066/20519] intraday_6545.csv.gz  in=435,830,895 out=113,176,626 elapsed=248.1s

  [17067/20519] intraday_6547.csv.gz  in=435,844,416 out=113,176,626 elapsed=248.1s

  [17068/20519] intraday_6549.csv.gz  in=435,858,261 out=113,176,626 elapsed=248.2s

  [17069/20519] intraday_6550.csv.gz  in=435,869,047 out=113,176,626 elapsed=248.2s

  [17070/20519] intraday_6548.csv.gz  in=435,884,040 out=113,176,626 elapsed=248.2s

  [17071/20519] intraday_6551.csv.gz  in=435,897,693 out=113,176,626 elapsed=248.2s

  [17072/20519] intraday_6553.csv.gz  in=435,909,461 out=113,176,626 elapsed=248.2s

  [17073/20519] intraday_6552.csv.gz  in=435,922,231 out=113,176,626 elapsed=248.2s

  [17074/20519] intraday_6554.csv.gz  in=435,934,022 out=113,176,626 elapsed=248.2s

  [17075/20519] intraday_6555.csv.gz  in=435,942,562 out=113,176,626 elapsed=248.2s

  [17076/20519] intraday_6557.csv.gz  in=435,947,812 out=113,176,626 elapsed=248.2s

  [17077/20519] intraday_6556.csv.gz  in=435,960,398 out=113,176,626 elapsed=248.2s

  [17078/20519] intraday_6558.csv.gz  in=435,979,674 out=113,176,626 elapsed=248.2s

  [17079/20519] intraday_6560.csv.gz  in=435,992,640 out=113,176,626 elapsed=248.3s

  [17080/20519] intraday_6559.csv.gz  in=436,006,015 out=113,176,626 elapsed=248.3s

  [17081/20519] intraday_6561.csv.gz  in=436,017,503 out=113,176,626 elapsed=248.3s

  [17082/20519] intraday_6562.csv.gz  in=436,030,287 out=113,176,626 elapsed=248.3s

  [17083/20519] intraday_6565.csv.gz  in=436,042,339 out=113,176,626 elapsed=248.3s

  [17084/20519] intraday_6563.csv.gz  in=436,057,720 out=113,176,626 elapsed=248.3s

  [17085/20519] intraday_6564.csv.gz  in=436,072,059 out=113,176,626 elapsed=248.3s

  [17086/20519] intraday_6566.csv.gz  in=436,089,503 out=113,176,626 elapsed=248.3s

  [17087/20519] intraday_6567.csv.gz  in=436,103,336 out=113,176,626 elapsed=248.4s

  [17088/20519] intraday_6568.csv.gz  in=436,119,769 out=113,176,626 elapsed=248.4s

  [17089/20519] intraday_6569.csv.gz  in=436,133,497 out=113,176,626 elapsed=248.4s

  [17090/20519] intraday_6570.csv.gz  in=436,147,673 out=113,176,626 elapsed=248.4s

  [17091/20519] intraday_6571.csv.gz  in=436,160,002 out=113,176,626 elapsed=248.4s

  [17092/20519] intraday_6573.csv.gz  in=436,169,218 out=113,176,626 elapsed=248.4s

  [17093/20519] intraday_6572.csv.gz  in=436,179,645 out=113,176,626 elapsed=248.4s

  [17094/20519] intraday_6574.csv.gz  in=436,193,899 out=113,176,626 elapsed=248.4s

  [17095/20519] intraday_6575.csv.gz  in=436,207,102 out=113,176,626 elapsed=248.4s

  [17096/20519] intraday_6576.csv.gz  in=436,219,194 out=113,176,626 elapsed=248.4s

  [17097/20519] intraday_6577.csv.gz  in=436,231,932 out=113,176,626 elapsed=248.5s

  [17098/20519] intraday_6578.csv.gz  in=436,244,287 out=113,176,626 elapsed=248.5s

  [17099/20519] intraday_6579.csv.gz  in=436,256,747 out=113,176,626 elapsed=248.5s

  [17100/20519] intraday_6580.csv.gz  in=436,268,769 out=113,176,626 elapsed=248.5s

  [17101/20519] intraday_6581.csv.gz  in=436,282,343 out=113,176,626 elapsed=248.5s

  [17102/20519] intraday_6582.csv.gz  in=436,296,207 out=113,176,626 elapsed=248.5s

  [17103/20519] intraday_6584.csv.gz  in=436,307,767 out=113,176,626 elapsed=248.5s

  [17104/20519] intraday_6585.csv.gz  in=436,319,968 out=113,176,626 elapsed=248.5s

  [17105/20519] intraday_6586.csv.gz  in=436,332,389 out=113,176,626 elapsed=248.5s

  [17106/20519] intraday_6583.csv.gz  in=436,353,395 out=113,176,626 elapsed=248.5s

  [17107/20519] intraday_6587.csv.gz  in=436,365,980 out=113,176,626 elapsed=248.6s

  [17108/20519] intraday_6588.csv.gz  in=436,383,630 out=113,176,626 elapsed=248.6s

  [17109/20519] intraday_6590.csv.gz  in=436,395,306 out=113,176,626 elapsed=248.6s

  [17110/20519] intraday_6589.csv.gz  in=436,408,068 out=113,176,626 elapsed=248.6s

  [17111/20519] intraday_6591.csv.gz  in=436,420,972 out=113,176,626 elapsed=248.6s

  [17112/20519] intraday_6592.csv.gz  in=436,434,780 out=113,176,626 elapsed=248.6s

  [17113/20519] intraday_6593.csv.gz  in=436,446,390 out=113,176,626 elapsed=248.6s

  [17114/20519] intraday_6594.csv.gz  in=436,461,187 out=113,176,626 elapsed=248.6s

  [17115/20519] intraday_6595.csv.gz  in=436,472,402 out=113,176,626 elapsed=248.6s

  [17116/20519] intraday_6596.csv.gz  in=436,486,495 out=113,176,626 elapsed=248.6s

  [17117/20519] intraday_6597.csv.gz  in=436,498,708 out=113,176,626 elapsed=248.7s

  [17118/20519] intraday_6598.csv.gz  in=436,511,201 out=113,176,626 elapsed=248.7s

  [17119/20519] intraday_6599.csv.gz  in=436,527,790 out=113,176,626 elapsed=248.7s

  [17120/20519] intraday_6600.csv.gz  in=436,541,129 out=113,176,626 elapsed=248.7s

  [17121/20519] intraday_6603.csv.gz  in=436,552,255 out=113,176,626 elapsed=248.7s

  [17122/20519] intraday_6602.csv.gz  in=436,566,091 out=113,176,626 elapsed=248.7s

  [17123/20519] intraday_6601.csv.gz  in=436,577,360 out=113,176,626 elapsed=248.7s

  [17124/20519] intraday_6606.csv.gz  in=436,588,070 out=113,176,626 elapsed=248.8s

  [17125/20519] intraday_6604.csv.gz  in=436,600,445 out=113,176,626 elapsed=248.8s

  [17126/20519] intraday_6605.csv.gz  in=436,613,842 out=113,176,626 elapsed=248.8s

  [17127/20519] intraday_6608.csv.gz  in=436,625,630 out=113,176,626 elapsed=248.8s

  [17128/20519] intraday_6607.csv.gz  in=436,637,179 out=113,176,626 elapsed=248.8s

  [17129/20519] intraday_6609.csv.gz  in=436,649,573 out=113,176,626 elapsed=248.8s

  [17130/20519] intraday_6610.csv.gz  in=436,662,261 out=113,176,626 elapsed=248.8s

  [17131/20519] intraday_6611.csv.gz  in=436,674,616 out=113,176,626 elapsed=248.8s

  [17132/20519] intraday_6612.csv.gz  in=436,689,484 out=113,176,626 elapsed=248.8s

  [17133/20519] intraday_6613.csv.gz  in=436,703,423 out=113,176,626 elapsed=248.8s

  [17134/20519] intraday_6614.csv.gz  in=436,716,311 out=113,176,626 elapsed=248.8s

  [17135/20519] intraday_6615.csv.gz  in=436,727,696 out=113,176,626 elapsed=248.8s

  [17136/20519] intraday_6618.csv.gz  in=436,740,860 out=113,176,626 elapsed=248.9s

  [17137/20519] intraday_6616.csv.gz  in=436,754,890 out=113,176,626 elapsed=248.9s

  [17138/20519] intraday_6617.csv.gz  in=436,769,679 out=113,176,626 elapsed=248.9s

  [17139/20519] intraday_6619.csv.gz  in=436,783,361 out=113,176,626 elapsed=248.9s

  [17140/20519] intraday_6620.csv.gz  in=436,795,044 out=113,176,626 elapsed=248.9s

  [17141/20519] intraday_6621.csv.gz  in=436,806,728 out=113,176,626 elapsed=248.9s

  [17142/20519] intraday_6622.csv.gz  in=436,823,399 out=113,176,626 elapsed=248.9s

  [17143/20519] intraday_6624.csv.gz  in=436,836,546 out=113,176,626 elapsed=248.9s

  [17144/20519] intraday_6623.csv.gz  in=436,852,295 out=113,176,626 elapsed=248.9s

  [17145/20519] intraday_6626.csv.gz  in=436,865,008 out=113,176,626 elapsed=249.0s

  [17146/20519] intraday_6625.csv.gz  in=436,878,246 out=113,176,626 elapsed=249.0s

  [17147/20519] intraday_6627.csv.gz  in=436,889,689 out=113,176,626 elapsed=249.0s

  [17148/20519] intraday_6628.csv.gz  in=436,901,953 out=113,176,626 elapsed=249.0s

  [17149/20519] intraday_6629.csv.gz  in=436,912,938 out=113,176,626 elapsed=249.0s

  [17150/20519] intraday_6630.csv.gz  in=436,927,439 out=113,176,626 elapsed=249.0s

  [17151/20519] intraday_6632.csv.gz  in=436,939,491 out=113,176,626 elapsed=249.0s

  [17152/20519] intraday_6631.csv.gz  in=436,952,504 out=113,176,626 elapsed=249.0s

  [17153/20519] intraday_6633.csv.gz  in=436,962,836 out=113,176,626 elapsed=249.0s

  [17154/20519] intraday_6634.csv.gz  in=436,976,122 out=113,176,626 elapsed=249.1s

  [17155/20519] intraday_6635.csv.gz  in=436,987,994 out=113,176,626 elapsed=249.1s

  [17156/20519] intraday_6636.csv.gz  in=437,000,156 out=113,176,626 elapsed=249.1s

  [17157/20519] intraday_6638.csv.gz  in=437,009,887 out=113,176,626 elapsed=249.1s

  [17158/20519] intraday_6640.csv.gz  in=437,022,538 out=113,176,626 elapsed=249.1s

  [17159/20519] intraday_6639.csv.gz  in=437,034,741 out=113,176,626 elapsed=249.1s

  [17160/20519] intraday_6637.csv.gz  in=437,051,465 out=113,176,626 elapsed=249.1s

  [17161/20519] intraday_6641.csv.gz  in=437,067,209 out=113,176,626 elapsed=249.1s

  [17162/20519] intraday_6643.csv.gz  in=437,080,630 out=113,176,626 elapsed=249.1s

  [17163/20519] intraday_6644.csv.gz  in=437,093,038 out=113,176,626 elapsed=249.1s

  [17164/20519] intraday_6642.csv.gz  in=437,107,765 out=113,176,626 elapsed=249.1s

  [17165/20519] intraday_6645.csv.gz  in=437,121,896 out=113,176,626 elapsed=249.2s

  [17166/20519] intraday_6646.csv.gz  in=437,135,215 out=113,176,626 elapsed=249.2s

  [17167/20519] intraday_6647.csv.gz  in=437,151,472 out=113,176,626 elapsed=249.2s

  [17168/20519] intraday_6648.csv.gz  in=437,166,423 out=113,176,626 elapsed=249.2s

  [17169/20519] intraday_6649.csv.gz  in=437,183,791 out=113,176,626 elapsed=249.2s

  [17170/20519] intraday_6650.csv.gz  in=437,198,026 out=113,176,626 elapsed=249.2s

  [17171/20519] intraday_6652.csv.gz  in=437,211,783 out=113,176,626 elapsed=249.3s

  [17172/20519] intraday_6651.csv.gz  in=437,226,145 out=113,176,626 elapsed=249.3s

  [17173/20519] intraday_6654.csv.gz  in=437,238,691 out=113,176,626 elapsed=249.3s

  [17174/20519] intraday_6653.csv.gz  in=437,251,749 out=113,176,626 elapsed=249.3s

  [17175/20519] intraday_6655.csv.gz  in=437,264,901 out=113,176,626 elapsed=249.3s

  [17176/20519] intraday_6656.csv.gz  in=437,279,075 out=113,176,626 elapsed=249.3s

  [17177/20519] intraday_6658.csv.gz  in=437,291,484 out=113,176,626 elapsed=249.3s

  [17178/20519] intraday_6657.csv.gz  in=437,305,726 out=113,176,626 elapsed=249.3s

  [17179/20519] intraday_6659.csv.gz  in=437,319,410 out=113,176,626 elapsed=249.3s

  [17180/20519] intraday_6660.csv.gz  in=437,334,112 out=113,176,626 elapsed=249.3s

  [17181/20519] intraday_6661.csv.gz  in=437,348,204 out=113,176,626 elapsed=249.3s

  [17182/20519] intraday_6662.csv.gz  in=437,361,135 out=113,176,626 elapsed=249.3s

  [17183/20519] intraday_6663.csv.gz  in=437,375,877 out=113,176,626 elapsed=249.4s

  [17184/20519] intraday_6665.csv.gz  in=437,388,099 out=113,176,626 elapsed=249.4s

  [17185/20519] intraday_6664.csv.gz  in=437,403,682 out=113,176,626 elapsed=249.4s

  [17186/20519] intraday_6666.csv.gz  in=437,417,409 out=113,176,626 elapsed=249.4s

  [17187/20519] intraday_6668.csv.gz  in=437,430,464 out=113,176,626 elapsed=249.4s

  [17188/20519] intraday_6667.csv.gz  in=437,445,846 out=113,176,626 elapsed=249.4s

  [17189/20519] intraday_6669.csv.gz  in=437,456,825 out=113,176,626 elapsed=249.4s

  [17190/20519] intraday_6670.csv.gz  in=437,471,555 out=113,176,626 elapsed=249.4s

  [17191/20519] intraday_6671.csv.gz  in=437,483,271 out=113,176,626 elapsed=249.4s

  [17192/20519] intraday_6672.csv.gz  in=437,498,381 out=113,176,626 elapsed=249.4s

  [17193/20519] intraday_6673.csv.gz  in=437,513,973 out=113,176,626 elapsed=249.4s

  [17194/20519] intraday_6676.csv.gz  in=437,526,402 out=113,176,626 elapsed=249.5s

  [17195/20519] intraday_6674.csv.gz  in=437,542,958 out=113,176,626 elapsed=249.5s

  [17196/20519] intraday_6677.csv.gz  in=437,555,227 out=113,176,626 elapsed=249.5s

  [17197/20519] intraday_6675.csv.gz  in=437,570,335 out=113,176,626 elapsed=249.5s

  [17198/20519] intraday_6679.csv.gz  in=437,581,492 out=113,176,626 elapsed=249.5s

  [17199/20519] intraday_6681.csv.gz  in=437,592,321 out=113,176,626 elapsed=249.5s

  [17200/20519] intraday_6678.csv.gz  in=437,604,329 out=113,176,626 elapsed=249.5s

  [17201/20519] intraday_6680.csv.gz  in=437,619,250 out=113,176,626 elapsed=249.5s

  [17202/20519] intraday_6682.csv.gz  in=437,632,373 out=113,176,626 elapsed=249.5s

  [17203/20519] intraday_6684.csv.gz  in=437,648,164 out=113,176,626 elapsed=249.6s

  [17204/20519] intraday_6683.csv.gz  in=437,661,039 out=113,176,626 elapsed=249.6s

  [17205/20519] intraday_6685.csv.gz  in=437,677,576 out=113,176,626 elapsed=249.6s

  [17206/20519] intraday_6687.csv.gz  in=437,691,206 out=113,176,626 elapsed=249.6s

  [17207/20519] intraday_6686.csv.gz  in=437,703,943 out=113,176,626 elapsed=249.6s

  [17208/20519] intraday_6688.csv.gz  in=437,717,891 out=113,176,626 elapsed=249.6s

  [17209/20519] intraday_6690.csv.gz  in=437,732,168 out=113,176,626 elapsed=249.7s

  [17210/20519] intraday_6691.csv.gz  in=437,746,572 out=113,176,626 elapsed=249.7s

  [17211/20519] intraday_6689.csv.gz  in=437,759,383 out=113,176,626 elapsed=249.7s

  [17212/20519] intraday_6693.csv.gz  in=437,772,910 out=113,176,626 elapsed=249.7s

  [17213/20519] intraday_6694.csv.gz  in=437,784,416 out=113,176,626 elapsed=249.7s

  [17214/20519] intraday_6696.csv.gz  in=437,796,329 out=113,176,626 elapsed=249.7s

  [17215/20519] intraday_6692.csv.gz  in=437,809,995 out=113,176,626 elapsed=249.7s

  [17216/20519] intraday_6695.csv.gz  in=437,823,747 out=113,176,626 elapsed=249.8s

  [17217/20519] intraday_6698.csv.gz  in=437,835,090 out=113,176,626 elapsed=249.8s

  [17218/20519] intraday_6699.csv.gz  in=437,843,288 out=113,176,626 elapsed=249.8s

  [17219/20519] intraday_6700.csv.gz  in=437,856,334 out=113,176,626 elapsed=249.8s

  [17220/20519] intraday_6697.csv.gz  in=437,868,491 out=113,176,626 elapsed=249.8s

  [17221/20519] intraday_6701.csv.gz  in=437,872,263 out=113,176,626 elapsed=249.8s

  [17222/20519] intraday_6703.csv.gz  in=437,872,472 out=113,176,626 elapsed=249.8s

  [17223/20519] intraday_6702.csv.gz  in=437,872,508 out=113,176,626 elapsed=249.8s

  [17224/20519] intraday_6705.csv.gz  in=437,872,532 out=113,176,626 elapsed=249.8s

  [17225/20519] intraday_6704.csv.gz  in=437,873,227 out=113,176,626 elapsed=249.8s

  [17226/20519] intraday_6706.csv.gz  in=437,873,237 out=113,176,626 elapsed=249.8s

  [17227/20519] intraday_6707.csv.gz  in=437,873,258 out=113,176,626 elapsed=249.9s

  [17228/20519] intraday_6709.csv.gz  in=437,873,261 out=113,176,626 elapsed=249.9s

  [17229/20519] intraday_6708.csv.gz  in=437,873,589 out=113,176,626 elapsed=249.9s

  [17230/20519] intraday_6710.csv.gz  in=437,873,614 out=113,176,626 elapsed=249.9s

  [17231/20519] intraday_6711.csv.gz  in=437,891,322 out=113,176,626 elapsed=249.9s

  [17232/20519] intraday_6713.csv.gz  in=437,905,217 out=113,176,626 elapsed=249.9s

  [17233/20519] intraday_6712.csv.gz  in=437,919,054 out=113,176,626 elapsed=249.9s

  [17234/20519] intraday_6715.csv.gz  in=437,931,179 out=113,176,626 elapsed=249.9s

  [17235/20519] intraday_6714.csv.gz  in=437,943,924 out=113,176,626 elapsed=249.9s

  [17236/20519] intraday_6716.csv.gz  in=437,959,506 out=113,176,626 elapsed=249.9s

  [17237/20519] intraday_6717.csv.gz  in=437,975,873 out=113,176,626 elapsed=249.9s

  [17238/20519] intraday_6718.csv.gz  in=437,988,662 out=113,176,626 elapsed=250.0s

  [17239/20519] intraday_6719.csv.gz  in=438,002,944 out=113,176,626 elapsed=250.0s

  [17240/20519] intraday_6720.csv.gz  in=438,017,762 out=113,176,626 elapsed=250.0s

  [17241/20519] intraday_6721.csv.gz  in=438,033,717 out=113,176,626 elapsed=250.0s

  [17242/20519] intraday_6722.csv.gz  in=438,048,716 out=113,176,626 elapsed=250.0s

  [17243/20519] intraday_6723.csv.gz  in=438,062,351 out=113,176,626 elapsed=250.0s

  [17244/20519] intraday_6724.csv.gz  in=438,076,096 out=113,176,626 elapsed=250.0s

  [17245/20519] intraday_6725.csv.gz  in=438,087,288 out=113,176,626 elapsed=250.0s

  [17246/20519] intraday_6726.csv.gz  in=438,100,207 out=113,176,626 elapsed=250.0s

  [17247/20519] intraday_6727.csv.gz  in=438,115,042 out=113,176,626 elapsed=250.0s

  [17248/20519] intraday_6728.csv.gz  in=438,129,524 out=113,176,626 elapsed=250.0s

  [17249/20519] intraday_6729.csv.gz  in=438,141,177 out=113,176,626 elapsed=250.1s

  [17250/20519] intraday_6730.csv.gz  in=438,154,381 out=113,176,626 elapsed=250.1s

  [17251/20519] intraday_6731.csv.gz  in=438,166,644 out=113,176,626 elapsed=250.1s

  [17252/20519] intraday_6732.csv.gz  in=438,179,934 out=113,176,626 elapsed=250.1s

  [17253/20519] intraday_6736.csv.gz  in=438,193,604 out=113,176,626 elapsed=250.1s

  [17254/20519] intraday_6733.csv.gz  in=438,206,106 out=113,176,626 elapsed=250.1s

  [17255/20519] intraday_6734.csv.gz  in=438,220,236 out=113,176,626 elapsed=250.1s

  [17256/20519] intraday_6735.csv.gz  in=438,234,386 out=113,176,626 elapsed=250.1s

  [17257/20519] intraday_6737.csv.gz  in=438,245,672 out=113,176,626 elapsed=250.1s

  [17258/20519] intraday_6739.csv.gz  in=438,258,461 out=113,176,626 elapsed=250.2s

  [17259/20519] intraday_6738.csv.gz  in=438,272,041 out=113,176,626 elapsed=250.2s

  [17260/20519] intraday_6740.csv.gz  in=438,285,941 out=113,176,626 elapsed=250.2s

  [17261/20519] intraday_6742.csv.gz  in=438,300,971 out=113,176,626 elapsed=250.2s

  [17262/20519] intraday_6741.csv.gz  in=438,320,010 out=113,176,626 elapsed=250.2s

  [17263/20519] intraday_6743.csv.gz  in=438,330,557 out=113,176,626 elapsed=250.2s

  [17264/20519] intraday_6744.csv.gz  in=438,344,201 out=113,176,626 elapsed=250.2s

  [17265/20519] intraday_6748.csv.gz  in=438,356,497 out=113,176,626 elapsed=250.2s

  [17266/20519] intraday_6746.csv.gz  in=438,377,034 out=113,176,626 elapsed=250.3s

  [17267/20519] intraday_6747.csv.gz  in=438,391,033 out=113,176,626 elapsed=250.3s

  [17268/20519] intraday_6745.csv.gz  in=438,406,631 out=113,176,626 elapsed=250.3s

  [17269/20519] intraday_6749.csv.gz  in=438,419,966 out=113,176,626 elapsed=250.3s

  [17270/20519] intraday_6750.csv.gz  in=438,431,370 out=113,176,626 elapsed=250.3s

  [17271/20519] intraday_6752.csv.gz  in=438,444,261 out=113,176,626 elapsed=250.3s

  [17272/20519] intraday_6751.csv.gz  in=438,456,205 out=113,176,626 elapsed=250.3s

  [17273/20519] intraday_6754.csv.gz  in=438,480,019 out=113,176,626 elapsed=250.3s

  [17274/20519] intraday_6753.csv.gz  in=438,493,839 out=113,176,626 elapsed=250.3s

  [17275/20519] intraday_6755.csv.gz  in=438,507,439 out=113,176,626 elapsed=250.3s

  [17276/20519] intraday_6756.csv.gz  in=438,520,332 out=113,176,626 elapsed=250.4s

  [17277/20519] intraday_6757.csv.gz  in=438,533,253 out=113,176,626 elapsed=250.4s

  [17278/20519] intraday_6759.csv.gz  in=438,545,519 out=113,176,626 elapsed=250.4s

  [17279/20519] intraday_6758.csv.gz  in=438,560,373 out=113,176,626 elapsed=250.4s

  [17280/20519] intraday_6760.csv.gz  in=438,573,902 out=113,176,626 elapsed=250.4s

  [17281/20519] intraday_6761.csv.gz  in=438,585,572 out=113,176,626 elapsed=250.4s

  [17282/20519] intraday_6762.csv.gz  in=438,597,264 out=113,176,626 elapsed=250.4s

  [17283/20519] intraday_6763.csv.gz  in=438,612,586 out=113,176,626 elapsed=250.4s

  [17284/20519] intraday_6764.csv.gz  in=438,622,720 out=113,176,626 elapsed=250.4s

  [17285/20519] intraday_6765.csv.gz  in=438,639,445 out=113,176,626 elapsed=250.4s

  [17286/20519] intraday_6766.csv.gz  in=438,653,524 out=113,176,626 elapsed=250.5s

  [17287/20519] intraday_6767.csv.gz  in=438,667,138 out=113,176,626 elapsed=250.5s

  [17288/20519] intraday_6769.csv.gz  in=438,680,875 out=113,176,626 elapsed=250.5s

  [17289/20519] intraday_6768.csv.gz  in=438,694,751 out=113,176,626 elapsed=250.5s

  [17290/20519] intraday_6771.csv.gz  in=438,708,169 out=113,176,626 elapsed=250.5s

  [17291/20519] intraday_6773.csv.gz  in=438,719,852 out=113,176,626 elapsed=250.5s

  [17292/20519] intraday_6770.csv.gz  in=438,753,302 out=113,176,626 elapsed=250.5s

  [17293/20519] intraday_6772.csv.gz  in=438,788,202 out=113,176,626 elapsed=250.5s

  [17294/20519] intraday_6774.csv.gz  in=438,799,959 out=113,176,626 elapsed=250.5s

  [17295/20519] intraday_6775.csv.gz  in=438,811,928 out=113,176,626 elapsed=250.5s

  [17296/20519] intraday_6776.csv.gz  in=438,828,410 out=113,176,626 elapsed=250.6s

  [17297/20519] intraday_6777.csv.gz  in=438,841,525 out=113,176,626 elapsed=250.6s

  [17298/20519] intraday_6778.csv.gz  in=438,856,167 out=113,176,626 elapsed=250.6s

  [17299/20519] intraday_6779.csv.gz  in=438,869,208 out=113,176,626 elapsed=250.6s

  [17300/20519] intraday_6780.csv.gz  in=438,881,061 out=113,176,626 elapsed=250.6s

  [17301/20519] intraday_6782.csv.gz  in=438,894,206 out=113,176,626 elapsed=250.6s

  [17302/20519] intraday_6781.csv.gz  in=438,905,917 out=113,176,626 elapsed=250.6s

  [17303/20519] intraday_6783.csv.gz  in=438,918,775 out=113,176,626 elapsed=250.6s

  [17304/20519] intraday_6784.csv.gz  in=438,932,133 out=113,176,626 elapsed=250.7s

  [17305/20519] intraday_6785.csv.gz  in=438,943,978 out=113,176,626 elapsed=250.7s

  [17306/20519] intraday_6786.csv.gz  in=438,957,282 out=113,176,626 elapsed=250.7s

  [17307/20519] intraday_6787.csv.gz  in=438,968,087 out=113,176,626 elapsed=250.7s

  [17308/20519] intraday_6788.csv.gz  in=438,981,931 out=113,176,626 elapsed=250.7s

  [17309/20519] intraday_6791.csv.gz  in=438,992,156 out=113,176,626 elapsed=250.7s

  [17310/20519] intraday_6790.csv.gz  in=439,007,270 out=113,176,626 elapsed=250.7s

  [17311/20519] intraday_6789.csv.gz  in=439,019,414 out=113,176,626 elapsed=250.7s

  [17312/20519] intraday_6792.csv.gz  in=439,031,044 out=113,176,626 elapsed=250.7s

  [17313/20519] intraday_6793.csv.gz  in=439,043,264 out=113,176,626 elapsed=250.8s

  [17314/20519] intraday_6794.csv.gz  in=439,063,107 out=113,176,626 elapsed=250.8s

  [17315/20519] intraday_6795.csv.gz  in=439,079,150 out=113,176,626 elapsed=250.8s

  [17316/20519] intraday_6796.csv.gz  in=439,094,328 out=113,176,626 elapsed=250.8s

  [17317/20519] intraday_6797.csv.gz  in=439,107,546 out=113,176,626 elapsed=250.8s

  [17318/20519] intraday_6798.csv.gz  in=439,121,371 out=113,176,626 elapsed=250.8s

  [17319/20519] intraday_6801.csv.gz  in=439,135,274 out=113,176,626 elapsed=250.8s

  [17320/20519] intraday_6800.csv.gz  in=439,151,661 out=113,176,626 elapsed=250.8s

  [17321/20519] intraday_6799.csv.gz  in=439,166,247 out=113,176,626 elapsed=250.9s

  [17322/20519] intraday_6802.csv.gz  in=439,178,716 out=113,176,626 elapsed=250.9s

  [17323/20519] intraday_6804.csv.gz  in=439,194,212 out=113,176,626 elapsed=250.9s

  [17324/20519] intraday_6805.csv.gz  in=439,207,852 out=113,176,626 elapsed=250.9s

  [17325/20519] intraday_6803.csv.gz  in=439,224,364 out=113,176,626 elapsed=250.9s

  [17326/20519] intraday_6806.csv.gz  in=439,238,613 out=113,176,626 elapsed=250.9s

  [17327/20519] intraday_6808.csv.gz  in=439,251,603 out=113,176,626 elapsed=250.9s

  [17328/20519] intraday_6807.csv.gz  in=439,264,523 out=113,176,626 elapsed=250.9s

  [17329/20519] intraday_6809.csv.gz  in=439,279,641 out=113,176,626 elapsed=250.9s

  [17330/20519] intraday_6811.csv.gz  in=439,293,089 out=113,176,626 elapsed=251.0s

  [17331/20519] intraday_6810.csv.gz  in=439,307,160 out=113,176,626 elapsed=251.0s

  [17332/20519] intraday_6812.csv.gz  in=439,320,695 out=113,176,626 elapsed=251.0s

  [17333/20519] intraday_6813.csv.gz  in=439,337,371 out=113,176,626 elapsed=251.0s

  [17334/20519] intraday_6814.csv.gz  in=439,351,410 out=113,176,626 elapsed=251.0s

  [17335/20519] intraday_6816.csv.gz  in=439,363,155 out=113,176,626 elapsed=251.0s

  [17336/20519] intraday_6818.csv.gz  in=439,376,035 out=113,176,626 elapsed=251.0s

  [17337/20519] intraday_6819.csv.gz  in=439,389,014 out=113,176,626 elapsed=251.0s

  [17338/20519] intraday_6817.csv.gz  in=439,407,729 out=113,176,626 elapsed=251.0s

  [17339/20519] intraday_6815.csv.gz  in=439,422,105 out=113,176,626 elapsed=251.0s

  [17340/20519] intraday_6820.csv.gz  in=439,438,124 out=113,176,626 elapsed=251.1s

  [17341/20519] intraday_6822.csv.gz  in=439,450,867 out=113,176,626 elapsed=251.1s

  [17342/20519] intraday_6821.csv.gz  in=439,464,330 out=113,176,626 elapsed=251.1s

  [17343/20519] intraday_6823.csv.gz  in=439,478,760 out=113,176,626 elapsed=251.1s

  [17344/20519] intraday_6824.csv.gz  in=439,491,887 out=113,176,626 elapsed=251.1s

  [17345/20519] intraday_6825.csv.gz  in=439,506,292 out=113,176,626 elapsed=251.1s

  [17346/20519] intraday_6826.csv.gz  in=439,523,627 out=113,176,626 elapsed=251.1s

  [17347/20519] intraday_6827.csv.gz  in=439,539,841 out=113,176,626 elapsed=251.1s

  [17348/20519] intraday_6828.csv.gz  in=439,553,447 out=113,176,626 elapsed=251.1s

  [17349/20519] intraday_6829.csv.gz  in=439,570,343 out=113,176,626 elapsed=251.2s

  [17350/20519] intraday_6830.csv.gz  in=439,585,707 out=113,176,626 elapsed=251.2s

  [17351/20519] intraday_6831.csv.gz  in=439,598,581 out=113,176,626 elapsed=251.2s

  [17352/20519] intraday_6832.csv.gz  in=439,610,292 out=113,176,626 elapsed=251.2s

  [17353/20519] intraday_6833.csv.gz  in=439,625,075 out=113,176,626 elapsed=251.2s

  [17354/20519] intraday_6834.csv.gz  in=439,636,549 out=113,176,626 elapsed=251.2s

  [17355/20519] intraday_6835.csv.gz  in=439,653,831 out=113,176,626 elapsed=251.2s

  [17356/20519] intraday_6836.csv.gz  in=439,665,969 out=113,176,626 elapsed=251.2s

  [17357/20519] intraday_6837.csv.gz  in=439,682,960 out=113,176,626 elapsed=251.2s

  [17358/20519] intraday_6838.csv.gz  in=439,696,464 out=113,176,626 elapsed=251.3s

  [17359/20519] intraday_6840.csv.gz  in=439,709,617 out=113,176,626 elapsed=251.3s

  [17360/20519] intraday_6839.csv.gz  in=439,722,623 out=113,176,626 elapsed=251.3s

  [17361/20519] intraday_6842.csv.gz  in=439,735,239 out=113,176,626 elapsed=251.3s

  [17362/20519] intraday_6841.csv.gz  in=439,747,777 out=113,176,626 elapsed=251.3s

  [17363/20519] intraday_6843.csv.gz  in=439,764,685 out=113,176,626 elapsed=251.3s

  [17364/20519] intraday_6844.csv.gz  in=439,780,162 out=113,176,626 elapsed=251.3s

  [17365/20519] intraday_6845.csv.gz  in=439,795,192 out=113,176,626 elapsed=251.3s

  [17366/20519] intraday_6846.csv.gz  in=439,816,877 out=113,176,626 elapsed=251.3s

  [17367/20519] intraday_6847.csv.gz  in=439,831,230 out=113,176,626 elapsed=251.3s

  [17368/20519] intraday_6848.csv.gz  in=439,842,390 out=113,176,626 elapsed=251.3s

  [17369/20519] intraday_6849.csv.gz  in=439,856,814 out=113,176,626 elapsed=251.3s

  [17370/20519] intraday_6850.csv.gz  in=439,868,186 out=113,176,626 elapsed=251.3s

  [17371/20519] intraday_6851.csv.gz  in=439,883,284 out=113,176,626 elapsed=251.3s

  [17372/20519] intraday_6852.csv.gz  in=439,892,811 out=113,176,626 elapsed=251.3s

  [17373/20519] intraday_6853.csv.gz  in=439,903,033 out=113,176,626 elapsed=251.3s

  [17374/20519] intraday_6854.csv.gz  in=439,915,436 out=113,176,626 elapsed=251.3s

  [17375/20519] intraday_6856.csv.gz  in=439,928,447 out=113,176,626 elapsed=251.3s

  [17376/20519] intraday_6857.csv.gz  in=439,941,688 out=113,176,626 elapsed=251.3s

  [17377/20519] intraday_6859.csv.gz  in=439,955,597 out=113,176,626 elapsed=251.4s

  [17378/20519] intraday_6858.csv.gz  in=439,966,299 out=113,176,626 elapsed=251.4s

  [17379/20519] intraday_6860.csv.gz  in=439,980,601 out=113,176,626 elapsed=251.4s

  [17380/20519] intraday_6855.csv.gz  in=440,028,000 out=113,176,626 elapsed=251.4s

  [17381/20519] intraday_6862.csv.gz  in=440,040,620 out=113,176,626 elapsed=251.4s

  [17382/20519] intraday_6861.csv.gz  in=440,057,036 out=113,176,626 elapsed=251.4s

  [17383/20519] intraday_6864.csv.gz  in=440,071,974 out=113,176,626 elapsed=251.4s

  [17384/20519] intraday_6863.csv.gz  in=440,084,725 out=113,176,626 elapsed=251.4s

  [17385/20519] intraday_6868.csv.gz  in=440,098,185 out=113,176,626 elapsed=251.5s

  [17386/20519] intraday_6865.csv.gz  in=440,113,676 out=113,176,626 elapsed=251.5s

  [17387/20519] intraday_6867.csv.gz  in=440,127,477 out=113,176,626 elapsed=251.5s

  [17388/20519] intraday_6866.csv.gz  in=440,142,391 out=113,176,626 elapsed=251.5s

  [17389/20519] intraday_6869.csv.gz  in=440,152,753 out=113,176,626 elapsed=251.5s

  [17390/20519] intraday_6870.csv.gz  in=440,162,352 out=113,176,626 elapsed=251.5s

  [17391/20519] intraday_6871.csv.gz  in=440,177,972 out=113,176,626 elapsed=251.5s

  [17392/20519] intraday_6872.csv.gz  in=440,192,159 out=113,176,626 elapsed=251.5s

  [17393/20519] intraday_6873.csv.gz  in=440,202,868 out=113,176,626 elapsed=251.5s

  [17394/20519] intraday_6874.csv.gz  in=440,214,650 out=113,176,626 elapsed=251.6s

  [17395/20519] intraday_6875.csv.gz  in=440,227,898 out=113,176,626 elapsed=251.6s

  [17396/20519] intraday_6876.csv.gz  in=440,240,375 out=113,176,626 elapsed=251.6s

  [17397/20519] intraday_6877.csv.gz  in=440,251,420 out=113,176,626 elapsed=251.6s

  [17398/20519] intraday_6879.csv.gz  in=440,265,020 out=113,176,626 elapsed=251.7s

  [17399/20519] intraday_6880.csv.gz  in=440,277,582 out=113,176,626 elapsed=251.7s

  [17400/20519] intraday_6878.csv.gz  in=440,291,056 out=113,176,626 elapsed=251.7s

  [17401/20519] intraday_6881.csv.gz  in=440,303,042 out=113,176,626 elapsed=251.7s

  [17402/20519] intraday_6883.csv.gz  in=440,315,920 out=113,176,626 elapsed=251.7s

  [17403/20519] intraday_6884.csv.gz  in=440,329,970 out=113,176,626 elapsed=251.7s

  [17404/20519] intraday_6882.csv.gz  in=440,342,110 out=113,176,626 elapsed=251.7s

  [17405/20519] intraday_6885.csv.gz  in=440,359,875 out=113,176,626 elapsed=251.8s

  [17406/20519] intraday_6887.csv.gz  in=440,370,293 out=113,176,626 elapsed=251.8s

  [17407/20519] intraday_6888.csv.gz  in=440,384,806 out=113,176,626 elapsed=251.8s

  [17408/20519] intraday_6886.csv.gz  in=440,400,115 out=113,176,626 elapsed=251.8s

  [17409/20519] intraday_6889.csv.gz  in=440,415,000 out=113,176,626 elapsed=251.8s

  [17410/20519] intraday_6890.csv.gz  in=440,427,265 out=113,176,626 elapsed=251.8s

  [17411/20519] intraday_6891.csv.gz  in=440,440,462 out=113,176,626 elapsed=251.8s

  [17412/20519] intraday_6892.csv.gz  in=440,451,318 out=113,176,626 elapsed=251.8s

  [17413/20519] intraday_6894.csv.gz  in=440,462,223 out=113,176,626 elapsed=251.8s

  [17414/20519] intraday_6895.csv.gz  in=440,473,321 out=113,176,626 elapsed=251.8s

  [17415/20519] intraday_6893.csv.gz  in=440,486,845 out=113,176,626 elapsed=251.8s

  [17416/20519] intraday_6896.csv.gz  in=440,499,154 out=113,176,626 elapsed=251.9s

  [17417/20519] intraday_6899.csv.gz  in=440,512,496 out=113,176,626 elapsed=251.9s

  [17418/20519] intraday_6898.csv.gz  in=440,525,586 out=113,176,626 elapsed=251.9s

  [17419/20519] intraday_6897.csv.gz  in=440,539,687 out=113,176,626 elapsed=251.9s

  [17420/20519] intraday_6900.csv.gz  in=440,551,861 out=113,176,626 elapsed=251.9s

  [17421/20519] intraday_6901.csv.gz  in=440,563,544 out=113,176,626 elapsed=251.9s

  [17422/20519] intraday_6902.csv.gz  in=440,577,688 out=113,176,626 elapsed=251.9s

  [17423/20519] intraday_6903.csv.gz  in=440,589,520 out=113,176,626 elapsed=251.9s

  [17424/20519] intraday_6905.csv.gz  in=440,600,846 out=113,176,626 elapsed=251.9s

  [17425/20519] intraday_6906.csv.gz  in=440,611,165 out=113,176,626 elapsed=251.9s

  [17426/20519] intraday_6904.csv.gz  in=440,624,047 out=113,176,626 elapsed=252.0s

  [17427/20519] intraday_6907.csv.gz  in=440,640,691 out=113,176,626 elapsed=252.0s

  [17428/20519] intraday_6908.csv.gz  in=440,650,227 out=113,176,626 elapsed=252.0s

  [17429/20519] intraday_6909.csv.gz  in=440,667,023 out=113,176,626 elapsed=252.0s

  [17430/20519] intraday_6910.csv.gz  in=440,680,664 out=113,176,626 elapsed=252.0s

  [17431/20519] intraday_6911.csv.gz  in=440,694,598 out=113,176,626 elapsed=252.0s

  [17432/20519] intraday_6912.csv.gz  in=440,706,724 out=113,176,626 elapsed=252.0s

  [17433/20519] intraday_6913.csv.gz  in=440,720,468 out=113,176,626 elapsed=252.0s

  [17434/20519] intraday_6915.csv.gz  in=440,733,906 out=113,176,626 elapsed=252.0s

  [17435/20519] intraday_6916.csv.gz  in=440,748,854 out=113,176,626 elapsed=252.0s

  [17436/20519] intraday_6914.csv.gz  in=440,762,774 out=113,176,626 elapsed=252.1s

  [17437/20519] intraday_6917.csv.gz  in=440,774,225 out=113,176,626 elapsed=252.1s

  [17438/20519] intraday_6918.csv.gz  in=440,785,349 out=113,176,626 elapsed=252.1s

  [17439/20519] intraday_6919.csv.gz  in=440,796,585 out=113,176,626 elapsed=252.1s

  [17440/20519] intraday_6920.csv.gz  in=440,811,669 out=113,176,626 elapsed=252.1s

  [17441/20519] intraday_6921.csv.gz  in=440,824,730 out=113,176,626 elapsed=252.1s

  [17442/20519] intraday_6923.csv.gz  in=440,837,004 out=113,176,626 elapsed=252.1s

  [17443/20519] intraday_6922.csv.gz  in=440,851,294 out=113,176,626 elapsed=252.1s

  [17444/20519] intraday_6924.csv.gz  in=440,862,783 out=113,176,626 elapsed=252.1s

  [17445/20519] intraday_6925.csv.gz  in=440,875,748 out=113,176,626 elapsed=252.1s

  [17446/20519] intraday_6928.csv.gz  in=440,890,195 out=113,176,626 elapsed=252.2s

  [17447/20519] intraday_6926.csv.gz  in=440,902,668 out=113,176,626 elapsed=252.2s

  [17448/20519] intraday_6929.csv.gz  in=440,914,597 out=113,176,626 elapsed=252.2s

  [17449/20519] intraday_6927.csv.gz  in=440,927,093 out=113,176,626 elapsed=252.2s

  [17450/20519] intraday_6931.csv.gz  in=440,938,106 out=113,176,626 elapsed=252.2s

  [17451/20519] intraday_6930.csv.gz  in=440,951,071 out=113,176,626 elapsed=252.2s

  [17452/20519] intraday_6933.csv.gz  in=440,963,093 out=113,176,626 elapsed=252.2s

  [17453/20519] intraday_6932.csv.gz  in=440,977,063 out=113,176,626 elapsed=252.2s

  [17454/20519] intraday_6934.csv.gz  in=440,990,944 out=113,176,626 elapsed=252.2s

  [17455/20519] intraday_6935.csv.gz  in=441,000,643 out=113,176,626 elapsed=252.3s

  [17456/20519] intraday_6937.csv.gz  in=441,013,985 out=113,176,626 elapsed=252.3s

  [17457/20519] intraday_6936.csv.gz  in=441,025,685 out=113,176,626 elapsed=252.3s

  [17458/20519] intraday_6938.csv.gz  in=441,042,408 out=113,176,626 elapsed=252.3s

  [17459/20519] intraday_6939.csv.gz  in=441,058,027 out=113,176,626 elapsed=252.3s

  [17460/20519] intraday_6941.csv.gz  in=441,071,044 out=113,176,626 elapsed=252.3s

  [17461/20519] intraday_6940.csv.gz  in=441,084,801 out=113,176,626 elapsed=252.3s

  [17462/20519] intraday_6942.csv.gz  in=441,096,605 out=113,176,626 elapsed=252.3s

  [17463/20519] intraday_6943.csv.gz  in=441,110,945 out=113,176,626 elapsed=252.3s

  [17464/20519] intraday_6944.csv.gz  in=441,128,507 out=113,176,626 elapsed=252.3s

  [17465/20519] intraday_6946.csv.gz  in=441,140,178 out=113,176,626 elapsed=252.4s

  [17466/20519] intraday_6947.csv.gz  in=441,155,634 out=113,176,626 elapsed=252.4s

  [17467/20519] intraday_6945.csv.gz  in=441,187,146 out=113,176,626 elapsed=252.4s

  [17468/20519] intraday_6948.csv.gz  in=441,202,367 out=113,176,626 elapsed=252.4s

  [17469/20519] intraday_6949.csv.gz  in=441,216,846 out=113,176,626 elapsed=252.4s

  [17470/20519] intraday_6950.csv.gz  in=441,230,416 out=113,176,626 elapsed=252.4s

  [17471/20519] intraday_6951.csv.gz  in=441,243,501 out=113,176,626 elapsed=252.4s

  [17472/20519] intraday_6952.csv.gz  in=441,255,818 out=113,176,626 elapsed=252.4s

  [17473/20519] intraday_6954.csv.gz  in=441,270,092 out=113,176,626 elapsed=252.4s

  [17474/20519] intraday_6953.csv.gz  in=441,284,362 out=113,176,626 elapsed=252.4s

  [17475/20519] intraday_6955.csv.gz  in=441,295,598 out=113,176,626 elapsed=252.4s

  [17476/20519] intraday_6959.csv.gz  in=441,309,497 out=113,176,626 elapsed=252.5s

  [17477/20519] intraday_6956.csv.gz  in=441,322,617 out=113,176,626 elapsed=252.5s

  [17478/20519] intraday_6958.csv.gz  in=441,336,536 out=113,176,626 elapsed=252.5s

  [17479/20519] intraday_6957.csv.gz  in=441,352,269 out=113,176,626 elapsed=252.5s

  [17480/20519] intraday_6961.csv.gz  in=441,368,382 out=113,176,626 elapsed=252.5s

  [17481/20519] intraday_6962.csv.gz  in=441,381,015 out=113,176,626 elapsed=252.5s

  [17482/20519] intraday_6963.csv.gz  in=441,394,036 out=113,176,626 elapsed=252.5s

  [17483/20519] intraday_6960.csv.gz  in=441,407,819 out=113,176,626 elapsed=252.5s

  [17484/20519] intraday_6966.csv.gz  in=441,418,786 out=113,176,626 elapsed=252.6s

  [17485/20519] intraday_6965.csv.gz  in=441,432,835 out=113,176,626 elapsed=252.6s

  [17486/20519] intraday_6964.csv.gz  in=441,448,246 out=113,176,626 elapsed=252.6s

  [17487/20519] intraday_6967.csv.gz  in=441,463,443 out=113,176,626 elapsed=252.6s

  [17488/20519] intraday_6970.csv.gz  in=441,479,161 out=113,176,626 elapsed=252.6s

  [17489/20519] intraday_6968.csv.gz  in=441,491,542 out=113,176,626 elapsed=252.6s

  [17490/20519] intraday_6969.csv.gz  in=441,505,525 out=113,176,626 elapsed=252.6s

  [17491/20519] intraday_6971.csv.gz  in=441,521,997 out=113,176,626 elapsed=252.6s

  [17492/20519] intraday_6972.csv.gz  in=441,537,208 out=113,176,626 elapsed=252.7s

  [17493/20519] intraday_6973.csv.gz  in=441,551,312 out=113,176,626 elapsed=252.7s

  [17494/20519] intraday_6974.csv.gz  in=441,563,990 out=113,176,626 elapsed=252.7s

  [17495/20519] intraday_6975.csv.gz  in=441,576,874 out=113,176,626 elapsed=252.7s

  [17496/20519] intraday_6976.csv.gz  in=441,587,626 out=113,176,626 elapsed=252.8s

  [17497/20519] intraday_6977.csv.gz  in=441,602,662 out=113,176,626 elapsed=252.8s

  [17498/20519] intraday_6978.csv.gz  in=441,614,264 out=113,176,626 elapsed=252.8s

  [17499/20519] intraday_6980.csv.gz  in=441,626,854 out=113,176,626 elapsed=252.8s

  [17500/20519] intraday_6979.csv.gz  in=441,640,646 out=113,176,626 elapsed=252.8s

  [17501/20519] intraday_6981.csv.gz  in=441,656,135 out=113,176,626 elapsed=252.8s

  [17502/20519] intraday_6983.csv.gz  in=441,668,084 out=113,176,626 elapsed=252.8s

  [17503/20519] intraday_6982.csv.gz  in=441,680,360 out=113,176,626 elapsed=252.8s

  [17504/20519] intraday_6984.csv.gz  in=441,692,658 out=113,176,626 elapsed=252.8s

  [17505/20519] intraday_6985.csv.gz  in=441,706,032 out=113,176,626 elapsed=252.8s

  [17506/20519] intraday_6986.csv.gz  in=441,717,225 out=113,176,626 elapsed=252.9s

  [17507/20519] intraday_6988.csv.gz  in=441,731,655 out=113,176,626 elapsed=252.9s

  [17508/20519] intraday_6987.csv.gz  in=441,747,211 out=113,176,626 elapsed=252.9s

  [17509/20519] intraday_6991.csv.gz  in=441,758,513 out=113,176,626 elapsed=252.9s

  [17510/20519] intraday_6992.csv.gz  in=441,770,423 out=113,176,626 elapsed=252.9s

  [17511/20519] intraday_6989.csv.gz  in=441,785,344 out=113,176,626 elapsed=252.9s

  [17512/20519] intraday_6990.csv.gz  in=441,824,915 out=113,176,626 elapsed=252.9s

  [17513/20519] intraday_6993.csv.gz  in=441,838,530 out=113,176,626 elapsed=252.9s

  [17514/20519] intraday_6995.csv.gz  in=441,850,697 out=113,176,626 elapsed=253.0s

  [17515/20519] intraday_6994.csv.gz  in=441,863,080 out=113,176,626 elapsed=253.0s

  [17516/20519] intraday_6996.csv.gz  in=441,872,746 out=113,176,626 elapsed=253.0s

  [17517/20519] intraday_6997.csv.gz  in=441,886,102 out=113,176,626 elapsed=253.0s

  [17518/20519] intraday_6998.csv.gz  in=441,893,395 out=113,176,626 elapsed=253.0s

  [17519/20519] intraday_7000.csv.gz  in=441,905,724 out=113,176,626 elapsed=253.0s

  [17520/20519] intraday_6999.csv.gz  in=441,922,263 out=113,176,626 elapsed=253.0s

  [17521/20519] intraday_7001.csv.gz  in=441,935,840 out=113,176,626 elapsed=253.0s

  [17522/20519] intraday_7002.csv.gz  in=441,946,272 out=113,176,626 elapsed=253.0s

  [17523/20519] intraday_7003.csv.gz  in=441,959,932 out=113,176,626 elapsed=253.0s

  [17524/20519] intraday_7004.csv.gz  in=441,975,084 out=113,176,626 elapsed=253.0s

  [17525/20519] intraday_7005.csv.gz  in=441,991,940 out=113,176,626 elapsed=253.1s

  [17526/20519] intraday_7006.csv.gz  in=442,003,808 out=113,176,626 elapsed=253.1s

  [17527/20519] intraday_7007.csv.gz  in=442,017,308 out=113,176,626 elapsed=253.1s

  [17528/20519] intraday_7008.csv.gz  in=442,031,521 out=113,176,626 elapsed=253.1s

  [17529/20519] intraday_7009.csv.gz  in=442,047,849 out=113,176,626 elapsed=253.1s

  [17530/20519] intraday_7010.csv.gz  in=442,063,084 out=113,176,626 elapsed=253.1s

  [17531/20519] intraday_7011.csv.gz  in=442,075,715 out=113,176,626 elapsed=253.1s

  [17532/20519] intraday_7012.csv.gz  in=442,089,622 out=113,176,626 elapsed=253.1s

  [17533/20519] intraday_7013.csv.gz  in=442,099,108 out=113,176,626 elapsed=253.1s

  [17534/20519] intraday_7014.csv.gz  in=442,109,222 out=113,176,626 elapsed=253.1s

  [17535/20519] intraday_7015.csv.gz  in=442,124,450 out=113,176,626 elapsed=253.1s

  [17536/20519] intraday_7016.csv.gz  in=442,138,500 out=113,176,626 elapsed=253.2s

  [17537/20519] intraday_7018.csv.gz  in=442,149,809 out=113,176,626 elapsed=253.2s

  [17538/20519] intraday_7017.csv.gz  in=442,161,914 out=113,176,626 elapsed=253.2s

  [17539/20519] intraday_7019.csv.gz  in=442,174,080 out=113,176,626 elapsed=253.2s

  [17540/20519] intraday_7020.csv.gz  in=442,186,739 out=113,176,626 elapsed=253.2s

  [17541/20519] intraday_7021.csv.gz  in=442,198,679 out=113,176,626 elapsed=253.2s

  [17542/20519] intraday_7022.csv.gz  in=442,211,875 out=113,176,626 elapsed=253.2s

  [17543/20519] intraday_7025.csv.gz  in=442,223,421 out=113,176,626 elapsed=253.2s

  [17544/20519] intraday_7024.csv.gz  in=442,237,532 out=113,176,626 elapsed=253.2s

  [17545/20519] intraday_7023.csv.gz  in=442,250,868 out=113,176,626 elapsed=253.2s

  [17546/20519] intraday_7026.csv.gz  in=442,263,845 out=113,176,626 elapsed=253.2s

  [17547/20519] intraday_7027.csv.gz  in=442,275,130 out=113,176,626 elapsed=253.3s

  [17548/20519] intraday_7028.csv.gz  in=442,289,683 out=113,176,626 elapsed=253.3s

  [17549/20519] intraday_7030.csv.gz  in=442,304,448 out=113,176,626 elapsed=253.3s

  [17550/20519] intraday_7029.csv.gz  in=442,322,651 out=113,176,626 elapsed=253.3s

  [17551/20519] intraday_7031.csv.gz  in=442,333,642 out=113,176,626 elapsed=253.3s

  [17552/20519] intraday_7034.csv.gz  in=442,346,079 out=113,176,626 elapsed=253.3s

  [17553/20519] intraday_7035.csv.gz  in=442,358,553 out=113,176,626 elapsed=253.3s

  [17554/20519] intraday_7033.csv.gz  in=442,373,683 out=113,176,626 elapsed=253.3s

  [17555/20519] intraday_7032.csv.gz  in=442,389,371 out=113,176,626 elapsed=253.3s

  [17556/20519] intraday_7036.csv.gz  in=442,400,955 out=113,176,626 elapsed=253.3s

  [17557/20519] intraday_7037.csv.gz  in=442,413,793 out=113,176,626 elapsed=253.3s

  [17558/20519] intraday_7039.csv.gz  in=442,425,254 out=113,176,626 elapsed=253.3s

  [17559/20519] intraday_7038.csv.gz  in=442,435,674 out=113,176,626 elapsed=253.3s

  [17560/20519] intraday_7040.csv.gz  in=442,447,981 out=113,176,626 elapsed=253.3s

  [17561/20519] intraday_7043.csv.gz  in=442,461,326 out=113,176,626 elapsed=253.3s

  [17562/20519] intraday_7042.csv.gz  in=442,475,005 out=113,176,626 elapsed=253.3s

  [17563/20519] intraday_7041.csv.gz  in=442,487,760 out=113,176,626 elapsed=253.4s

  [17564/20519] intraday_7044.csv.gz  in=442,500,485 out=113,176,626 elapsed=253.4s

  [17565/20519] intraday_7045.csv.gz  in=442,512,740 out=113,176,626 elapsed=253.4s

  [17566/20519] intraday_7047.csv.gz  in=442,526,700 out=113,176,626 elapsed=253.4s

  [17567/20519] intraday_7046.csv.gz  in=442,539,017 out=113,176,626 elapsed=253.4s

  [17568/20519] intraday_7048.csv.gz  in=442,551,513 out=113,176,626 elapsed=253.4s

  [17569/20519] intraday_7049.csv.gz  in=442,563,082 out=113,176,626 elapsed=253.4s

  [17570/20519] intraday_7050.csv.gz  in=442,573,217 out=113,176,626 elapsed=253.4s

  [17571/20519] intraday_7052.csv.gz  in=442,583,124 out=113,176,626 elapsed=253.4s

  [17572/20519] intraday_7051.csv.gz  in=442,598,494 out=113,176,626 elapsed=253.5s

  [17573/20519] intraday_7053.csv.gz  in=442,613,232 out=113,176,626 elapsed=253.5s

  [17574/20519] intraday_7055.csv.gz  in=442,626,439 out=113,176,626 elapsed=253.5s

  [17575/20519] intraday_7054.csv.gz  in=442,641,594 out=113,176,626 elapsed=253.5s

  [17576/20519] intraday_7056.csv.gz  in=442,654,490 out=113,176,626 elapsed=253.5s

  [17577/20519] intraday_7057.csv.gz  in=442,667,499 out=113,176,626 elapsed=253.5s

  [17578/20519] intraday_7058.csv.gz  in=442,681,338 out=113,176,626 elapsed=253.5s

  [17579/20519] intraday_7059.csv.gz  in=442,695,280 out=113,176,626 elapsed=253.5s

  [17580/20519] intraday_7060.csv.gz  in=442,708,796 out=113,176,626 elapsed=253.5s

  [17581/20519] intraday_7061.csv.gz  in=442,720,898 out=113,176,626 elapsed=253.5s

  [17582/20519] intraday_7062.csv.gz  in=442,732,576 out=113,176,626 elapsed=253.5s

  [17583/20519] intraday_7063.csv.gz  in=442,743,895 out=113,176,626 elapsed=253.6s

  [17584/20519] intraday_7064.csv.gz  in=442,758,990 out=113,176,626 elapsed=253.6s

  [17585/20519] intraday_7065.csv.gz  in=442,771,928 out=113,176,626 elapsed=253.6s

  [17586/20519] intraday_7066.csv.gz  in=442,786,030 out=113,176,626 elapsed=253.6s

  [17587/20519] intraday_7067.csv.gz  in=442,799,660 out=113,176,626 elapsed=253.6s

  [17588/20519] intraday_7070.csv.gz  in=442,812,532 out=113,176,626 elapsed=253.6s

  [17589/20519] intraday_7069.csv.gz  in=442,824,002 out=113,176,626 elapsed=253.7s

  [17590/20519] intraday_7071.csv.gz  in=442,836,908 out=113,176,626 elapsed=253.7s

  [17591/20519] intraday_7068.csv.gz  in=442,858,020 out=113,176,626 elapsed=253.7s

  [17592/20519] intraday_7073.csv.gz  in=442,869,409 out=113,176,626 elapsed=253.7s

  [17593/20519] intraday_7072.csv.gz  in=442,883,936 out=113,176,626 elapsed=253.7s

  [17594/20519] intraday_7074.csv.gz  in=442,897,060 out=113,176,626 elapsed=253.7s

  [17595/20519] intraday_7075.csv.gz  in=442,907,813 out=113,176,626 elapsed=253.7s

  [17596/20519] intraday_7078.csv.gz  in=442,920,424 out=113,176,626 elapsed=253.8s

  [17597/20519] intraday_7076.csv.gz  in=442,934,313 out=113,176,626 elapsed=253.8s

  [17598/20519] intraday_7079.csv.gz  in=442,949,947 out=113,176,626 elapsed=253.8s

  [17599/20519] intraday_7077.csv.gz  in=442,972,608 out=113,176,626 elapsed=253.8s

  [17600/20519] intraday_7080.csv.gz  in=442,994,504 out=113,176,626 elapsed=253.8s

  [17601/20519] intraday_7083.csv.gz  in=443,011,411 out=113,176,626 elapsed=253.8s

  [17602/20519] intraday_7081.csv.gz  in=443,022,852 out=113,176,626 elapsed=253.8s

  [17603/20519] intraday_7082.csv.gz  in=443,040,431 out=113,176,626 elapsed=253.8s

  [17604/20519] intraday_7084.csv.gz  in=443,054,836 out=113,176,626 elapsed=253.8s

  [17605/20519] intraday_7086.csv.gz  in=443,066,315 out=113,176,626 elapsed=253.9s

  [17606/20519] intraday_7085.csv.gz  in=443,078,325 out=113,176,626 elapsed=253.9s

  [17607/20519] intraday_7087.csv.gz  in=443,093,846 out=113,176,626 elapsed=253.9s

  [17608/20519] intraday_7088.csv.gz  in=443,106,824 out=113,176,626 elapsed=253.9s

  [17609/20519] intraday_7090.csv.gz  in=443,119,708 out=113,176,626 elapsed=253.9s

  [17610/20519] intraday_7092.csv.gz  in=443,134,854 out=113,176,626 elapsed=253.9s

  [17611/20519] intraday_7091.csv.gz  in=443,149,462 out=113,176,626 elapsed=253.9s

  [17612/20519] intraday_7089.csv.gz  in=443,165,483 out=113,176,626 elapsed=253.9s

  [17613/20519] intraday_7093.csv.gz  in=443,178,540 out=113,176,626 elapsed=253.9s

  [17614/20519] intraday_7096.csv.gz  in=443,192,352 out=113,176,626 elapsed=253.9s

  [17615/20519] intraday_7094.csv.gz  in=443,207,935 out=113,176,626 elapsed=254.0s

  [17616/20519] intraday_7095.csv.gz  in=443,234,177 out=113,176,626 elapsed=254.0s

  [17617/20519] intraday_7097.csv.gz  in=443,248,082 out=113,176,626 elapsed=254.0s

  [17618/20519] intraday_7098.csv.gz  in=443,261,574 out=113,176,626 elapsed=254.0s

  [17619/20519] intraday_7099.csv.gz  in=443,273,767 out=113,176,626 elapsed=254.0s

  [17620/20519] intraday_7101.csv.gz  in=443,290,706 out=113,176,626 elapsed=254.0s

  [17621/20519] intraday_7100.csv.gz  in=443,304,540 out=113,176,626 elapsed=254.0s

  [17622/20519] intraday_7102.csv.gz  in=443,320,266 out=113,176,626 elapsed=254.0s

  [17623/20519] intraday_7103.csv.gz  in=443,331,854 out=113,176,626 elapsed=254.0s

  [17624/20519] intraday_7104.csv.gz  in=443,344,779 out=113,176,626 elapsed=254.0s

  [17625/20519] intraday_7105.csv.gz  in=443,362,924 out=113,176,626 elapsed=254.0s

  [17626/20519] intraday_7107.csv.gz  in=443,375,166 out=113,176,626 elapsed=254.1s

  [17627/20519] intraday_7106.csv.gz  in=443,386,998 out=113,176,626 elapsed=254.1s

  [17628/20519] intraday_7109.csv.gz  in=443,402,055 out=113,176,626 elapsed=254.1s

  [17629/20519] intraday_7108.csv.gz  in=443,417,972 out=113,176,626 elapsed=254.1s

  [17630/20519] intraday_7110.csv.gz  in=443,430,716 out=113,176,626 elapsed=254.1s

  [17631/20519] intraday_7111.csv.gz  in=443,443,804 out=113,176,626 elapsed=254.1s

  [17632/20519] intraday_7112.csv.gz  in=443,456,435 out=113,176,626 elapsed=254.1s

  [17633/20519] intraday_7113.csv.gz  in=443,468,387 out=113,176,626 elapsed=254.1s

  [17634/20519] intraday_7114.csv.gz  in=443,486,177 out=113,176,626 elapsed=254.1s

  [17635/20519] intraday_7115.csv.gz  in=443,500,461 out=113,176,626 elapsed=254.1s

  [17636/20519] intraday_7117.csv.gz  in=443,516,617 out=113,176,626 elapsed=254.2s

  [17637/20519] intraday_7119.csv.gz  in=443,528,623 out=113,176,626 elapsed=254.2s

  [17638/20519] intraday_7116.csv.gz  in=443,543,838 out=113,176,626 elapsed=254.2s

  [17639/20519] intraday_7118.csv.gz  in=443,557,632 out=113,176,626 elapsed=254.2s

  [17640/20519] intraday_7120.csv.gz  in=443,570,072 out=113,176,626 elapsed=254.2s

  [17641/20519] intraday_7121.csv.gz  in=443,583,333 out=113,176,626 elapsed=254.2s

  [17642/20519] intraday_7122.csv.gz  in=443,595,192 out=113,176,626 elapsed=254.2s

  [17643/20519] intraday_7123.csv.gz  in=443,630,664 out=113,176,626 elapsed=254.2s

  [17644/20519] intraday_7126.csv.gz  in=443,645,618 out=113,176,626 elapsed=254.3s

  [17645/20519] intraday_7124.csv.gz  in=443,659,050 out=113,176,626 elapsed=254.3s

  [17646/20519] intraday_7125.csv.gz  in=443,673,080 out=113,176,626 elapsed=254.3s

  [17647/20519] intraday_7127.csv.gz  in=443,685,814 out=113,176,626 elapsed=254.3s

  [17648/20519] intraday_7128.csv.gz  in=443,697,747 out=113,176,626 elapsed=254.3s

  [17649/20519] intraday_7129.csv.gz  in=443,711,710 out=113,176,626 elapsed=254.3s

  [17650/20519] intraday_7130.csv.gz  in=443,724,129 out=113,176,626 elapsed=254.3s

  [17651/20519] intraday_7131.csv.gz  in=443,736,435 out=113,176,626 elapsed=254.3s

  [17652/20519] intraday_7132.csv.gz  in=443,751,208 out=113,176,626 elapsed=254.3s

  [17653/20519] intraday_7133.csv.gz  in=443,766,506 out=113,176,626 elapsed=254.3s

  [17654/20519] intraday_7134.csv.gz  in=443,781,158 out=113,176,626 elapsed=254.3s

  [17655/20519] intraday_7135.csv.gz  in=443,794,954 out=113,176,626 elapsed=254.4s

  [17656/20519] intraday_7136.csv.gz  in=443,805,990 out=113,176,626 elapsed=254.4s

  [17657/20519] intraday_7138.csv.gz  in=443,818,005 out=113,176,626 elapsed=254.4s

  [17658/20519] intraday_7139.csv.gz  in=443,833,015 out=113,176,626 elapsed=254.4s

  [17659/20519] intraday_7137.csv.gz  in=443,846,610 out=113,176,626 elapsed=254.4s

  [17660/20519] intraday_7140.csv.gz  in=443,856,292 out=113,176,626 elapsed=254.4s

  [17661/20519] intraday_7141.csv.gz  in=443,866,002 out=113,176,626 elapsed=254.4s

  [17662/20519] intraday_7142.csv.gz  in=443,879,758 out=113,176,626 elapsed=254.4s

  [17663/20519] intraday_7143.csv.gz  in=443,880,399 out=113,176,626 elapsed=254.4s

  [17664/20519] intraday_7144.csv.gz  in=443,897,276 out=113,176,626 elapsed=254.4s

  [17665/20519] intraday_7146.csv.gz  in=443,910,370 out=113,176,626 elapsed=254.4s

  [17666/20519] intraday_7145.csv.gz  in=443,924,861 out=113,176,626 elapsed=254.4s

  [17667/20519] intraday_7147.csv.gz  in=443,936,155 out=113,176,626 elapsed=254.5s

  [17668/20519] intraday_7148.csv.gz  in=443,947,777 out=113,176,626 elapsed=254.5s

  [17669/20519] intraday_7150.csv.gz  in=443,963,076 out=113,176,626 elapsed=254.5s

  [17670/20519] intraday_7149.csv.gz  in=443,977,642 out=113,176,626 elapsed=254.5s

  [17671/20519] intraday_7151.csv.gz  in=443,989,635 out=113,176,626 elapsed=254.5s

  [17672/20519] intraday_7152.csv.gz  in=444,002,858 out=113,176,626 elapsed=254.5s

  [17673/20519] intraday_7153.csv.gz  in=444,016,332 out=113,176,626 elapsed=254.5s

  [17674/20519] intraday_7154.csv.gz  in=444,036,144 out=113,176,626 elapsed=254.5s

  [17675/20519] intraday_7155.csv.gz  in=444,052,133 out=113,176,626 elapsed=254.5s

  [17676/20519] intraday_7156.csv.gz  in=444,065,110 out=113,176,626 elapsed=254.5s

  [17677/20519] intraday_7159.csv.gz  in=444,074,003 out=113,176,626 elapsed=254.5s

  [17678/20519] intraday_7157.csv.gz  in=444,086,959 out=113,176,626 elapsed=254.6s

  [17679/20519] intraday_7158.csv.gz  in=444,096,662 out=113,176,626 elapsed=254.6s

  [17680/20519] intraday_7161.csv.gz  in=444,109,999 out=113,176,626 elapsed=254.6s

  [17681/20519] intraday_7162.csv.gz  in=444,122,454 out=113,176,626 elapsed=254.6s

  [17682/20519] intraday_7160.csv.gz  in=444,137,383 out=113,176,626 elapsed=254.6s

  [17683/20519] intraday_7163.csv.gz  in=444,147,921 out=113,176,626 elapsed=254.6s

  [17684/20519] intraday_7164.csv.gz  in=444,160,828 out=113,176,626 elapsed=254.6s

  [17685/20519] intraday_7165.csv.gz  in=444,174,486 out=113,176,626 elapsed=254.6s

  [17686/20519] intraday_7167.csv.gz  in=444,187,027 out=113,176,626 elapsed=254.7s

  [17687/20519] intraday_7168.csv.gz  in=444,200,080 out=113,176,626 elapsed=254.7s

  [17688/20519] intraday_7166.csv.gz  in=444,210,752 out=113,176,626 elapsed=254.7s

  [17689/20519] intraday_7169.csv.gz  in=444,224,149 out=113,176,626 elapsed=254.7s

  [17690/20519] intraday_7171.csv.gz  in=444,239,132 out=113,176,626 elapsed=254.7s

  [17691/20519] intraday_7172.csv.gz  in=444,250,429 out=113,176,626 elapsed=254.7s

  [17692/20519] intraday_7170.csv.gz  in=444,261,011 out=113,176,626 elapsed=254.7s

  [17693/20519] intraday_7174.csv.gz  in=444,277,315 out=113,176,626 elapsed=254.8s

  [17694/20519] intraday_7173.csv.gz  in=444,290,643 out=113,176,626 elapsed=254.8s

  [17695/20519] intraday_7175.csv.gz  in=444,304,211 out=113,176,626 elapsed=254.8s

  [17696/20519] intraday_7176.csv.gz  in=444,315,854 out=113,176,626 elapsed=254.8s

  [17697/20519] intraday_7179.csv.gz  in=444,326,922 out=113,176,626 elapsed=254.8s

  [17698/20519] intraday_7180.csv.gz  in=444,341,201 out=113,176,626 elapsed=254.8s

  [17699/20519] intraday_7177.csv.gz  in=444,352,858 out=113,176,626 elapsed=254.8s

  [17700/20519] intraday_7178.csv.gz  in=444,366,831 out=113,176,626 elapsed=254.8s

  [17701/20519] intraday_7182.csv.gz  in=444,378,653 out=113,176,626 elapsed=254.9s

  [17702/20519] intraday_7181.csv.gz  in=444,388,412 out=113,176,626 elapsed=254.9s

  [17703/20519] intraday_7184.csv.gz  in=444,399,734 out=113,176,626 elapsed=254.9s

  [17704/20519] intraday_7183.csv.gz  in=444,410,758 out=113,176,626 elapsed=254.9s

  [17705/20519] intraday_7187.csv.gz  in=444,422,161 out=113,176,626 elapsed=254.9s

  [17706/20519] intraday_7188.csv.gz  in=444,436,402 out=113,176,626 elapsed=254.9s

  [17707/20519] intraday_7186.csv.gz  in=444,451,419 out=113,176,626 elapsed=254.9s

  [17708/20519] intraday_7185.csv.gz  in=444,463,806 out=113,176,626 elapsed=254.9s

  [17709/20519] intraday_7189.csv.gz  in=444,476,458 out=113,176,626 elapsed=254.9s

  [17710/20519] intraday_7190.csv.gz  in=444,487,261 out=113,176,626 elapsed=254.9s

  [17711/20519] intraday_7191.csv.gz  in=444,500,801 out=113,176,626 elapsed=255.0s

  [17712/20519] intraday_7192.csv.gz  in=444,512,973 out=113,176,626 elapsed=255.0s

  [17713/20519] intraday_7193.csv.gz  in=444,524,695 out=113,176,626 elapsed=255.0s

  [17714/20519] intraday_7195.csv.gz  in=444,535,734 out=113,176,626 elapsed=255.0s

  [17715/20519] intraday_7194.csv.gz  in=444,546,090 out=113,176,626 elapsed=255.0s

  [17716/20519] intraday_7196.csv.gz  in=444,559,715 out=113,176,626 elapsed=255.0s

  [17717/20519] intraday_7197.csv.gz  in=444,571,037 out=113,176,626 elapsed=255.0s

  [17718/20519] intraday_7198.csv.gz  in=444,585,408 out=113,176,626 elapsed=255.0s

  [17719/20519] intraday_7199.csv.gz  in=444,599,156 out=113,176,626 elapsed=255.0s

  [17720/20519] intraday_7200.csv.gz  in=444,612,352 out=113,176,626 elapsed=255.1s

  [17721/20519] intraday_7201.csv.gz  in=444,623,029 out=113,176,626 elapsed=255.1s

  [17722/20519] intraday_7203.csv.gz  in=444,637,509 out=113,176,626 elapsed=255.1s

  [17723/20519] intraday_7202.csv.gz  in=444,649,654 out=113,176,626 elapsed=255.1s

  [17724/20519] intraday_7206.csv.gz  in=444,661,066 out=113,176,626 elapsed=255.1s

  [17725/20519] intraday_7205.csv.gz  in=444,673,845 out=113,176,626 elapsed=255.1s

  [17726/20519] intraday_7204.csv.gz  in=444,686,934 out=113,176,626 elapsed=255.1s

  [17727/20519] intraday_7207.csv.gz  in=444,696,720 out=113,176,626 elapsed=255.1s

  [17728/20519] intraday_7208.csv.gz  in=444,707,493 out=113,176,626 elapsed=255.1s

  [17729/20519] intraday_7210.csv.gz  in=444,720,639 out=113,176,626 elapsed=255.1s

  [17730/20519] intraday_7209.csv.gz  in=444,736,515 out=113,176,626 elapsed=255.2s

  [17731/20519] intraday_7211.csv.gz  in=444,749,869 out=113,176,626 elapsed=255.2s

  [17732/20519] intraday_7212.csv.gz  in=444,762,128 out=113,176,626 elapsed=255.2s

  [17733/20519] intraday_7214.csv.gz  in=444,774,839 out=113,176,626 elapsed=255.2s

  [17734/20519] intraday_7213.csv.gz  in=444,792,175 out=113,176,626 elapsed=255.2s

  [17735/20519] intraday_7215.csv.gz  in=444,803,891 out=113,176,626 elapsed=255.2s

  [17736/20519] intraday_7216.csv.gz  in=444,815,357 out=113,176,626 elapsed=255.2s

  [17737/20519] intraday_7218.csv.gz  in=444,827,064 out=113,176,626 elapsed=255.2s

  [17738/20519] intraday_7217.csv.gz  in=444,840,357 out=113,176,626 elapsed=255.2s

  [17739/20519] intraday_7219.csv.gz  in=444,853,936 out=113,176,626 elapsed=255.3s

  [17740/20519] intraday_7220.csv.gz  in=444,867,112 out=113,176,626 elapsed=255.3s

  [17741/20519] intraday_7221.csv.gz  in=444,879,370 out=113,176,626 elapsed=255.3s

  [17742/20519] intraday_7222.csv.gz  in=444,889,999 out=113,176,626 elapsed=255.3s

  [17743/20519] intraday_7223.csv.gz  in=444,903,112 out=113,176,626 elapsed=255.3s

  [17744/20519] intraday_7224.csv.gz  in=444,913,838 out=113,176,626 elapsed=255.3s

  [17745/20519] intraday_7225.csv.gz  in=444,925,788 out=113,176,626 elapsed=255.3s

  [17746/20519] intraday_7226.csv.gz  in=444,938,696 out=113,176,626 elapsed=255.3s

  [17747/20519] intraday_7228.csv.gz  in=444,953,136 out=113,176,626 elapsed=255.3s

  [17748/20519] intraday_7227.csv.gz  in=444,969,376 out=113,176,626 elapsed=255.3s

  [17749/20519] intraday_7229.csv.gz  in=444,982,917 out=113,176,626 elapsed=255.3s

  [17750/20519] intraday_7232.csv.gz  in=444,995,570 out=113,176,626 elapsed=255.4s

  [17751/20519] intraday_7230.csv.gz  in=445,008,081 out=113,176,626 elapsed=255.4s

  [17752/20519] intraday_7231.csv.gz  in=445,019,562 out=113,176,626 elapsed=255.4s

  [17753/20519] intraday_7234.csv.gz  in=445,031,330 out=113,176,626 elapsed=255.4s

  [17754/20519] intraday_7235.csv.gz  in=445,042,858 out=113,176,626 elapsed=255.4s

  [17755/20519] intraday_7233.csv.gz  in=445,059,771 out=113,176,626 elapsed=255.4s

  [17756/20519] intraday_7236.csv.gz  in=445,073,463 out=113,176,626 elapsed=255.4s

  [17757/20519] intraday_7238.csv.gz  in=445,086,853 out=113,176,626 elapsed=255.4s

  [17758/20519] intraday_7239.csv.gz  in=445,099,243 out=113,176,626 elapsed=255.4s

  [17759/20519] intraday_7237.csv.gz  in=445,112,610 out=113,176,626 elapsed=255.5s

  [17760/20519] intraday_7240.csv.gz  in=445,125,171 out=113,176,626 elapsed=255.5s

  [17761/20519] intraday_7241.csv.gz  in=445,136,531 out=113,176,626 elapsed=255.5s

  [17762/20519] intraday_7242.csv.gz  in=445,150,929 out=113,176,626 elapsed=255.5s

  [17763/20519] intraday_7244.csv.gz  in=445,161,127 out=113,176,626 elapsed=255.5s

  [17764/20519] intraday_7245.csv.gz  in=445,173,706 out=113,176,626 elapsed=255.5s

  [17765/20519] intraday_7246.csv.gz  in=445,188,141 out=113,176,626 elapsed=255.5s

  [17766/20519] intraday_7243.csv.gz  in=445,224,042 out=113,176,626 elapsed=255.5s

  [17767/20519] intraday_7247.csv.gz  in=445,236,914 out=113,176,626 elapsed=255.5s

  [17768/20519] intraday_7248.csv.gz  in=445,252,085 out=113,176,626 elapsed=255.5s

  [17769/20519] intraday_7249.csv.gz  in=445,264,561 out=113,176,626 elapsed=255.6s

  [17770/20519] intraday_7251.csv.gz  in=445,277,685 out=113,176,626 elapsed=255.6s

  [17771/20519] intraday_7250.csv.gz  in=445,293,676 out=113,176,626 elapsed=255.6s

  [17772/20519] intraday_7252.csv.gz  in=445,306,704 out=113,176,626 elapsed=255.6s

  [17773/20519] intraday_7254.csv.gz  in=445,321,213 out=113,176,626 elapsed=255.6s

  [17774/20519] intraday_7253.csv.gz  in=445,336,787 out=113,176,626 elapsed=255.6s

  [17775/20519] intraday_7255.csv.gz  in=445,347,113 out=113,176,626 elapsed=255.6s

  [17776/20519] intraday_7256.csv.gz  in=445,362,200 out=113,176,626 elapsed=255.6s

  [17777/20519] intraday_7257.csv.gz  in=445,372,616 out=113,176,626 elapsed=255.6s

  [17778/20519] intraday_7258.csv.gz  in=445,387,280 out=113,176,626 elapsed=255.6s

  [17779/20519] intraday_7259.csv.gz  in=445,403,389 out=113,176,626 elapsed=255.7s

  [17780/20519] intraday_7262.csv.gz  in=445,418,432 out=113,176,626 elapsed=255.7s

  [17781/20519] intraday_7261.csv.gz  in=445,432,971 out=113,176,626 elapsed=255.7s

  [17782/20519] intraday_7260.csv.gz  in=445,449,406 out=113,176,626 elapsed=255.7s

  [17783/20519] intraday_7263.csv.gz  in=445,462,948 out=113,176,626 elapsed=255.7s

  [17784/20519] intraday_7264.csv.gz  in=445,474,098 out=113,176,626 elapsed=255.7s

  [17785/20519] intraday_7266.csv.gz  in=445,488,385 out=113,176,626 elapsed=255.8s

  [17786/20519] intraday_7265.csv.gz  in=445,499,022 out=113,176,626 elapsed=255.8s

  [17787/20519] intraday_7267.csv.gz  in=445,510,121 out=113,176,626 elapsed=255.8s

  [17788/20519] intraday_7268.csv.gz  in=445,523,345 out=113,176,626 elapsed=255.8s

  [17789/20519] intraday_7270.csv.gz  in=445,538,599 out=113,176,626 elapsed=255.8s

  [17790/20519] intraday_7269.csv.gz  in=445,551,071 out=113,176,626 elapsed=255.8s

  [17791/20519] intraday_7271.csv.gz  in=445,563,877 out=113,176,626 elapsed=255.8s

  [17792/20519] intraday_7272.csv.gz  in=445,576,375 out=113,176,626 elapsed=255.8s

  [17793/20519] intraday_7273.csv.gz  in=445,588,182 out=113,176,626 elapsed=255.8s

  [17794/20519] intraday_7274.csv.gz  in=445,600,744 out=113,176,626 elapsed=255.9s

  [17795/20519] intraday_7276.csv.gz  in=445,617,250 out=113,176,626 elapsed=255.9s

  [17796/20519] intraday_7275.csv.gz  in=445,629,107 out=113,176,626 elapsed=255.9s

  [17797/20519] intraday_7277.csv.gz  in=445,643,169 out=113,176,626 elapsed=255.9s

  [17798/20519] intraday_7278.csv.gz  in=445,656,999 out=113,176,626 elapsed=255.9s

  [17799/20519] intraday_7279.csv.gz  in=445,671,572 out=113,176,626 elapsed=255.9s

  [17800/20519] intraday_7281.csv.gz  in=445,682,937 out=113,176,626 elapsed=255.9s

  [17801/20519] intraday_7280.csv.gz  in=445,694,606 out=113,176,626 elapsed=255.9s

  [17802/20519] intraday_7282.csv.gz  in=445,708,272 out=113,176,626 elapsed=255.9s

  [17803/20519] intraday_7285.csv.gz  in=445,716,168 out=113,176,626 elapsed=256.0s

  [17804/20519] intraday_7283.csv.gz  in=445,728,081 out=113,176,626 elapsed=256.0s

  [17805/20519] intraday_7286.csv.gz  in=445,740,639 out=113,176,626 elapsed=256.0s

  [17806/20519] intraday_7284.csv.gz  in=445,753,299 out=113,176,626 elapsed=256.0s

  [17807/20519] intraday_7287.csv.gz  in=445,760,050 out=113,176,626 elapsed=256.0s

  [17808/20519] intraday_7290.csv.gz  in=445,772,920 out=113,176,626 elapsed=256.0s

  [17809/20519] intraday_7289.csv.gz  in=445,788,262 out=113,176,626 elapsed=256.0s

  [17810/20519] intraday_7288.csv.gz  in=445,804,658 out=113,176,626 elapsed=256.0s

  [17811/20519] intraday_7292.csv.gz  in=445,816,982 out=113,176,626 elapsed=256.0s

  [17812/20519] intraday_7293.csv.gz  in=445,831,176 out=113,176,626 elapsed=256.0s

  [17813/20519] intraday_7291.csv.gz  in=445,842,899 out=113,176,626 elapsed=256.0s

  [17814/20519] intraday_7294.csv.gz  in=445,859,294 out=113,176,626 elapsed=256.1s

  [17815/20519] intraday_7295.csv.gz  in=445,870,825 out=113,176,626 elapsed=256.1s

  [17816/20519] intraday_7297.csv.gz  in=445,885,428 out=113,176,626 elapsed=256.1s

  [17817/20519] intraday_7296.csv.gz  in=445,899,416 out=113,176,626 elapsed=256.1s

  [17818/20519] intraday_7298.csv.gz  in=445,915,963 out=113,176,626 elapsed=256.1s

  [17819/20519] intraday_7299.csv.gz  in=445,931,065 out=113,176,626 elapsed=256.1s

  [17820/20519] intraday_7300.csv.gz  in=445,943,921 out=113,176,626 elapsed=256.1s

  [17821/20519] intraday_7301.csv.gz  in=445,960,894 out=113,176,626 elapsed=256.1s

  [17822/20519] intraday_7302.csv.gz  in=445,971,385 out=113,176,626 elapsed=256.1s

  [17823/20519] intraday_7305.csv.gz  in=445,984,613 out=113,176,626 elapsed=256.2s

  [17824/20519] intraday_7304.csv.gz  in=445,999,716 out=113,176,626 elapsed=256.2s

  [17825/20519] intraday_7303.csv.gz  in=446,011,360 out=113,176,626 elapsed=256.2s

  [17826/20519] intraday_7306.csv.gz  in=446,024,018 out=113,176,626 elapsed=256.2s

  [17827/20519] intraday_7308.csv.gz  in=446,036,975 out=113,176,626 elapsed=256.2s

  [17828/20519] intraday_7309.csv.gz  in=446,049,986 out=113,176,626 elapsed=256.2s

  [17829/20519] intraday_7310.csv.gz  in=446,062,715 out=113,176,626 elapsed=256.2s

  [17830/20519] intraday_7307.csv.gz  in=446,075,255 out=113,176,626 elapsed=256.2s

  [17831/20519] intraday_7311.csv.gz  in=446,087,850 out=113,176,626 elapsed=256.2s

  [17832/20519] intraday_7312.csv.gz  in=446,101,554 out=113,176,626 elapsed=256.2s

  [17833/20519] intraday_7313.csv.gz  in=446,115,081 out=113,176,626 elapsed=256.2s

  [17834/20519] intraday_7314.csv.gz  in=446,125,919 out=113,176,626 elapsed=256.3s

  [17835/20519] intraday_7315.csv.gz  in=446,138,443 out=113,176,626 elapsed=256.3s

  [17836/20519] intraday_7316.csv.gz  in=446,150,454 out=113,176,626 elapsed=256.3s

  [17837/20519] intraday_7317.csv.gz  in=446,164,649 out=113,176,626 elapsed=256.3s

  [17838/20519] intraday_7319.csv.gz  in=446,178,690 out=113,176,626 elapsed=256.3s

  [17839/20519] intraday_7320.csv.gz  in=446,188,683 out=113,176,626 elapsed=256.3s

  [17840/20519] intraday_7318.csv.gz  in=446,205,047 out=113,176,626 elapsed=256.3s

  [17841/20519] intraday_7321.csv.gz  in=446,219,601 out=113,176,626 elapsed=256.3s

  [17842/20519] intraday_7322.csv.gz  in=446,233,598 out=113,176,626 elapsed=256.4s

  [17843/20519] intraday_7324.csv.gz  in=446,246,126 out=113,176,626 elapsed=256.4s

  [17844/20519] intraday_7323.csv.gz  in=446,258,965 out=113,176,626 elapsed=256.4s

  [17845/20519] intraday_7325.csv.gz  in=446,270,574 out=113,176,626 elapsed=256.4s

  [17846/20519] intraday_7326.csv.gz  in=446,284,222 out=113,176,626 elapsed=256.4s

  [17847/20519] intraday_7328.csv.gz  in=446,295,793 out=113,176,626 elapsed=256.4s

  [17848/20519] intraday_7327.csv.gz  in=446,308,274 out=113,176,626 elapsed=256.4s

  [17849/20519] intraday_7330.csv.gz  in=446,321,223 out=113,176,626 elapsed=256.4s

  [17850/20519] intraday_7331.csv.gz  in=446,335,683 out=113,176,626 elapsed=256.4s

  [17851/20519] intraday_7329.csv.gz  in=446,348,262 out=113,176,626 elapsed=256.4s

  [17852/20519] intraday_7333.csv.gz  in=446,360,381 out=113,176,626 elapsed=256.5s

  [17853/20519] intraday_7332.csv.gz  in=446,375,336 out=113,176,626 elapsed=256.5s

  [17854/20519] intraday_7335.csv.gz  in=446,388,939 out=113,176,626 elapsed=256.5s

  [17855/20519] intraday_7334.csv.gz  in=446,401,210 out=113,176,626 elapsed=256.5s

  [17856/20519] intraday_7336.csv.gz  in=446,413,637 out=113,176,626 elapsed=256.5s

  [17857/20519] intraday_7338.csv.gz  in=446,424,580 out=113,176,626 elapsed=256.5s

  [17858/20519] intraday_7339.csv.gz  in=446,436,384 out=113,176,626 elapsed=256.5s

  [17859/20519] intraday_7337.csv.gz  in=446,449,113 out=113,176,626 elapsed=256.5s

  [17860/20519] intraday_7341.csv.gz  in=446,459,323 out=113,176,626 elapsed=256.5s

  [17861/20519] intraday_7343.csv.gz  in=446,472,386 out=113,176,626 elapsed=256.5s

  [17862/20519] intraday_7342.csv.gz  in=446,487,961 out=113,176,626 elapsed=256.5s

  [17863/20519] intraday_7340.csv.gz  in=446,502,802 out=113,176,626 elapsed=256.5s

  [17864/20519] intraday_7344.csv.gz  in=446,518,150 out=113,176,626 elapsed=256.6s

  [17865/20519] intraday_7346.csv.gz  in=446,531,154 out=113,176,626 elapsed=256.6s

  [17866/20519] intraday_7345.csv.gz  in=446,543,204 out=113,176,626 elapsed=256.6s

  [17867/20519] intraday_7347.csv.gz  in=446,556,495 out=113,176,626 elapsed=256.6s

  [17868/20519] intraday_7348.csv.gz  in=446,569,507 out=113,176,626 elapsed=256.6s

  [17869/20519] intraday_7349.csv.gz  in=446,583,489 out=113,176,626 elapsed=256.6s

  [17870/20519] intraday_7351.csv.gz  in=446,594,656 out=113,176,626 elapsed=256.6s

  [17871/20519] intraday_7350.csv.gz  in=446,606,539 out=113,176,626 elapsed=256.6s

  [17872/20519] intraday_7352.csv.gz  in=446,617,956 out=113,176,626 elapsed=256.6s

  [17873/20519] intraday_7353.csv.gz  in=446,633,176 out=113,176,626 elapsed=256.7s

  [17874/20519] intraday_7354.csv.gz  in=446,646,580 out=113,176,626 elapsed=256.7s

  [17875/20519] intraday_7355.csv.gz  in=446,661,547 out=113,176,626 elapsed=256.7s

  [17876/20519] intraday_7358.csv.gz  in=446,672,742 out=113,176,626 elapsed=256.7s

  [17877/20519] intraday_7356.csv.gz  in=446,685,218 out=113,176,626 elapsed=256.7s

  [17878/20519] intraday_7357.csv.gz  in=446,697,888 out=113,176,626 elapsed=256.7s

  [17879/20519] intraday_7362.csv.gz  in=446,709,828 out=113,176,626 elapsed=256.8s

  [17880/20519] intraday_7359.csv.gz  in=446,721,851 out=113,176,626 elapsed=256.8s

  [17881/20519] intraday_7360.csv.gz  in=446,734,589 out=113,176,626 elapsed=256.8s

  [17882/20519] intraday_7361.csv.gz  in=446,748,536 out=113,176,626 elapsed=256.8s

  [17883/20519] intraday_7364.csv.gz  in=446,758,531 out=113,176,626 elapsed=256.8s

  [17884/20519] intraday_7366.csv.gz  in=446,770,300 out=113,176,626 elapsed=256.9s

  [17885/20519] intraday_7363.csv.gz  in=446,782,235 out=113,176,626 elapsed=256.9s

  [17886/20519] intraday_7365.csv.gz  in=446,797,199 out=113,176,626 elapsed=256.9s

  [17887/20519] intraday_7369.csv.gz  in=446,806,767 out=113,176,626 elapsed=256.9s

  [17888/20519] intraday_7368.csv.gz  in=446,817,666 out=113,176,626 elapsed=256.9s

  [17889/20519] intraday_7367.csv.gz  in=446,829,744 out=113,176,626 elapsed=256.9s

  [17890/20519] intraday_7371.csv.gz  in=446,847,680 out=113,176,626 elapsed=256.9s

  [17891/20519] intraday_7370.csv.gz  in=446,859,813 out=113,176,626 elapsed=256.9s

  [17892/20519] intraday_7372.csv.gz  in=446,877,592 out=113,176,626 elapsed=256.9s

  [17893/20519] intraday_7373.csv.gz  in=446,891,405 out=113,176,626 elapsed=257.0s

  [17894/20519] intraday_7374.csv.gz  in=446,901,952 out=113,176,626 elapsed=257.0s

  [17895/20519] intraday_7375.csv.gz  in=446,914,769 out=113,176,626 elapsed=257.0s

  [17896/20519] intraday_7376.csv.gz  in=446,930,075 out=113,176,626 elapsed=257.0s

  [17897/20519] intraday_7377.csv.gz  in=446,944,161 out=113,176,626 elapsed=257.0s

  [17898/20519] intraday_7379.csv.gz  in=446,958,803 out=113,176,626 elapsed=257.0s

  [17899/20519] intraday_7378.csv.gz  in=446,973,742 out=113,176,626 elapsed=257.0s

  [17900/20519] intraday_7380.csv.gz  in=446,987,243 out=113,176,626 elapsed=257.0s

  [17901/20519] intraday_7382.csv.gz  in=447,000,874 out=113,176,626 elapsed=257.0s

  [17902/20519] intraday_7381.csv.gz  in=447,014,602 out=113,176,626 elapsed=257.0s

  [17903/20519] intraday_7383.csv.gz  in=447,028,344 out=113,176,626 elapsed=257.0s

  [17904/20519] intraday_7385.csv.gz  in=447,042,107 out=113,176,626 elapsed=257.1s

  [17905/20519] intraday_7384.csv.gz  in=447,053,414 out=113,176,626 elapsed=257.1s

  [17906/20519] intraday_7386.csv.gz  in=447,066,975 out=113,176,626 elapsed=257.1s

  [17907/20519] intraday_7387.csv.gz  in=447,080,441 out=113,176,626 elapsed=257.1s

  [17908/20519] intraday_7389.csv.gz  in=447,094,861 out=113,176,626 elapsed=257.1s

  [17909/20519] intraday_7388.csv.gz  in=447,106,772 out=113,176,626 elapsed=257.1s

  [17910/20519] intraday_7390.csv.gz  in=447,119,512 out=113,176,626 elapsed=257.1s

  [17911/20519] intraday_7391.csv.gz  in=447,135,868 out=113,176,626 elapsed=257.1s

  [17912/20519] intraday_7392.csv.gz  in=447,147,934 out=113,176,626 elapsed=257.1s

  [17913/20519] intraday_7393.csv.gz  in=447,160,579 out=113,176,626 elapsed=257.2s

  [17914/20519] intraday_7395.csv.gz  in=447,173,719 out=113,176,626 elapsed=257.2s

  [17915/20519] intraday_7394.csv.gz  in=447,190,973 out=113,176,626 elapsed=257.2s

  [17916/20519] intraday_7396.csv.gz  in=447,202,945 out=113,176,626 elapsed=257.2s

  [17917/20519] intraday_7397.csv.gz  in=447,218,994 out=113,176,626 elapsed=257.2s

  [17918/20519] intraday_7398.csv.gz  in=447,234,902 out=113,176,626 elapsed=257.2s

  [17919/20519] intraday_7399.csv.gz  in=447,247,469 out=113,176,626 elapsed=257.2s

  [17920/20519] intraday_7400.csv.gz  in=447,260,812 out=113,176,626 elapsed=257.2s

  [17921/20519] intraday_7401.csv.gz  in=447,274,497 out=113,176,626 elapsed=257.2s

  [17922/20519] intraday_7402.csv.gz  in=447,287,032 out=113,176,626 elapsed=257.3s

  [17923/20519] intraday_7403.csv.gz  in=447,306,070 out=113,176,626 elapsed=257.3s

  [17924/20519] intraday_7404.csv.gz  in=447,320,644 out=113,176,626 elapsed=257.3s

  [17925/20519] intraday_7405.csv.gz  in=447,335,880 out=113,176,626 elapsed=257.3s

  [17926/20519] intraday_7406.csv.gz  in=447,353,290 out=113,176,626 elapsed=257.3s

  [17927/20519] intraday_7407.csv.gz  in=447,368,229 out=113,176,626 elapsed=257.3s

  [17928/20519] intraday_7408.csv.gz  in=447,381,237 out=113,176,626 elapsed=257.3s

  [17929/20519] intraday_7409.csv.gz  in=447,393,385 out=113,176,626 elapsed=257.3s

  [17930/20519] intraday_7410.csv.gz  in=447,406,707 out=113,176,626 elapsed=257.3s

  [17931/20519] intraday_7411.csv.gz  in=447,418,201 out=113,176,626 elapsed=257.3s

  [17932/20519] intraday_7413.csv.gz  in=447,430,892 out=113,176,626 elapsed=257.4s

  [17933/20519] intraday_7412.csv.gz  in=447,445,003 out=113,176,626 elapsed=257.4s

  [17934/20519] intraday_7415.csv.gz  in=447,459,172 out=113,176,626 elapsed=257.4s

  [17935/20519] intraday_7414.csv.gz  in=447,475,168 out=113,176,626 elapsed=257.4s

  [17936/20519] intraday_7417.csv.gz  in=447,486,974 out=113,176,626 elapsed=257.4s

  [17937/20519] intraday_7418.csv.gz  in=447,501,447 out=113,176,626 elapsed=257.4s

  [17938/20519] intraday_7416.csv.gz  in=447,515,036 out=113,176,626 elapsed=257.4s

  [17939/20519] intraday_7419.csv.gz  in=447,527,134 out=113,176,626 elapsed=257.4s

  [17940/20519] intraday_7420.csv.gz  in=447,539,999 out=113,176,626 elapsed=257.4s

  [17941/20519] intraday_7421.csv.gz  in=447,555,810 out=113,176,626 elapsed=257.4s

  [17942/20519] intraday_7422.csv.gz  in=447,570,791 out=113,176,626 elapsed=257.4s

  [17943/20519] intraday_7424.csv.gz  in=447,585,410 out=113,176,626 elapsed=257.5s

  [17944/20519] intraday_7423.csv.gz  in=447,605,521 out=113,176,626 elapsed=257.5s

  [17945/20519] intraday_7426.csv.gz  in=447,619,129 out=113,176,626 elapsed=257.5s

  [17946/20519] intraday_7425.csv.gz  in=447,632,110 out=113,176,626 elapsed=257.5s

  [17947/20519] intraday_7428.csv.gz  in=447,646,722 out=113,176,626 elapsed=257.5s

  [17948/20519] intraday_7427.csv.gz  in=447,657,423 out=113,176,626 elapsed=257.5s

  [17949/20519] intraday_7429.csv.gz  in=447,668,335 out=113,176,626 elapsed=257.5s

  [17950/20519] intraday_7432.csv.gz  in=447,670,428 out=113,176,626 elapsed=257.5s

  [17951/20519] intraday_7430.csv.gz  in=447,679,690 out=113,176,626 elapsed=257.5s

  [17952/20519] intraday_7431.csv.gz  in=447,693,209 out=113,176,626 elapsed=257.5s

  [17953/20519] intraday_7434.csv.gz  in=447,693,244 out=113,176,626 elapsed=257.5s

  [17954/20519] intraday_7433.csv.gz  in=447,693,352 out=113,176,626 elapsed=257.6s

  [17955/20519] intraday_7435.csv.gz  in=447,693,374 out=113,176,626 elapsed=257.6s

  [17956/20519] intraday_7436.csv.gz  in=447,701,257 out=113,176,626 elapsed=257.6s

  [17957/20519] intraday_7437.csv.gz  in=447,703,769 out=113,176,626 elapsed=257.6s

  [17958/20519] intraday_7438.csv.gz  in=447,703,812 out=113,176,626 elapsed=257.6s

  [17959/20519] intraday_7439.csv.gz  in=447,705,631 out=113,176,626 elapsed=257.6s

  [17960/20519] intraday_7440.csv.gz  in=447,705,807 out=113,176,626 elapsed=257.6s

  [17961/20519] intraday_7441.csv.gz  in=447,710,664 out=113,176,626 elapsed=257.6s

  [17962/20519] intraday_7443.csv.gz  in=447,711,820 out=113,176,626 elapsed=257.6s

  [17963/20519] intraday_7442.csv.gz  in=447,711,954 out=113,176,626 elapsed=257.6s

  [17964/20519] intraday_7444.csv.gz  in=447,711,967 out=113,176,626 elapsed=257.6s

  [17965/20519] intraday_7445.csv.gz  in=447,711,990 out=113,176,626 elapsed=257.7s

  [17966/20519] intraday_7447.csv.gz  in=447,712,908 out=113,176,626 elapsed=257.7s

  [17967/20519] intraday_7446.csv.gz  in=447,713,010 out=113,176,626 elapsed=257.7s

  [17968/20519] intraday_7451.csv.gz  in=447,713,055 out=113,176,626 elapsed=257.7s

  [17969/20519] intraday_7448.csv.gz  in=447,713,954 out=113,176,626 elapsed=257.7s

  [17970/20519] intraday_7450.csv.gz  in=447,713,962 out=113,176,626 elapsed=257.7s

  [17971/20519] intraday_7449.csv.gz  in=447,714,125 out=113,176,626 elapsed=257.7s

  [17972/20519] intraday_7454.csv.gz  in=447,718,410 out=113,176,626 elapsed=257.8s

  [17973/20519] intraday_7453.csv.gz  in=447,722,866 out=113,176,626 elapsed=257.8s

  [17974/20519] intraday_7452.csv.gz  in=447,724,202 out=113,176,626 elapsed=257.8s

  [17975/20519] intraday_7455.csv.gz  in=447,724,922 out=113,176,626 elapsed=257.8s

  [17976/20519] intraday_7456.csv.gz  in=447,725,239 out=113,176,626 elapsed=257.8s

  [17977/20519] intraday_7457.csv.gz  in=447,729,462 out=113,176,626 elapsed=257.8s

  [17978/20519] intraday_7458.csv.gz  in=447,729,485 out=113,176,626 elapsed=257.8s

  [17979/20519] intraday_7459.csv.gz  in=447,729,616 out=113,176,626 elapsed=257.8s

  [17980/20519] intraday_7460.csv.gz  in=447,729,827 out=113,176,626 elapsed=257.8s

  [17981/20519] intraday_7461.csv.gz  in=447,730,133 out=113,176,626 elapsed=257.9s

  [17982/20519] intraday_7463.csv.gz  in=447,733,615 out=113,176,626 elapsed=257.9s

  [17983/20519] intraday_7464.csv.gz  in=447,736,436 out=113,176,626 elapsed=257.9s

  [17984/20519] intraday_7465.csv.gz  in=447,738,849 out=113,176,626 elapsed=257.9s

  [17985/20519] intraday_7462.csv.gz  in=447,770,592 out=113,176,626 elapsed=257.9s

  [17986/20519] intraday_7466.csv.gz  in=447,773,085 out=113,176,626 elapsed=257.9s

  [17987/20519] intraday_7467.csv.gz  in=447,775,526 out=113,176,626 elapsed=257.9s

  [17988/20519] intraday_7468.csv.gz  in=447,778,565 out=113,176,626 elapsed=257.9s

  [17989/20519] intraday_7469.csv.gz  in=447,782,595 out=113,176,626 elapsed=257.9s

  [17990/20519] intraday_7472.csv.gz  in=447,785,628 out=113,176,626 elapsed=257.9s

  [17991/20519] intraday_7471.csv.gz  in=447,788,322 out=113,176,626 elapsed=257.9s

  [17992/20519] intraday_7470.csv.gz  in=447,790,561 out=113,176,626 elapsed=257.9s

  [17993/20519] intraday_7474.csv.gz  in=447,794,256 out=113,176,626 elapsed=257.9s

  [17994/20519] intraday_7473.csv.gz  in=447,798,524 out=113,176,626 elapsed=257.9s

  [17995/20519] intraday_7475.csv.gz  in=447,801,535 out=113,176,626 elapsed=257.9s

  [17996/20519] intraday_7476.csv.gz  in=447,804,574 out=113,176,626 elapsed=257.9s

  [17997/20519] intraday_7477.csv.gz  in=447,807,027 out=113,176,626 elapsed=258.0s

  [17998/20519] intraday_7478.csv.gz  in=447,809,115 out=113,176,626 elapsed=258.0s

  [17999/20519] intraday_7479.csv.gz  in=447,812,391 out=113,176,626 elapsed=258.0s

  [18000/20519] intraday_7481.csv.gz  in=447,814,442 out=113,176,626 elapsed=258.0s

  [18001/20519] intraday_7480.csv.gz  in=447,817,118 out=113,176,626 elapsed=258.0s

  [18002/20519] intraday_7482.csv.gz  in=447,819,233 out=113,176,626 elapsed=258.0s

  [18003/20519] intraday_7483.csv.gz  in=447,822,006 out=113,176,626 elapsed=258.0s

  [18004/20519] intraday_7485.csv.gz  in=447,823,698 out=113,176,626 elapsed=258.0s

  [18005/20519] intraday_7484.csv.gz  in=447,826,924 out=113,176,626 elapsed=258.0s

  [18006/20519] intraday_7487.csv.gz  in=447,829,217 out=113,176,626 elapsed=258.0s

  [18007/20519] intraday_7486.csv.gz  in=447,831,868 out=113,176,626 elapsed=258.0s

  [18008/20519] intraday_7489.csv.gz  in=447,834,303 out=113,176,626 elapsed=258.0s

  [18009/20519] intraday_7488.csv.gz  in=447,837,512 out=113,176,626 elapsed=258.0s

  [18010/20519] intraday_7490.csv.gz  in=447,840,094 out=113,176,626 elapsed=258.1s

  [18011/20519] intraday_7491.csv.gz  in=447,842,665 out=113,176,626 elapsed=258.1s

  [18012/20519] intraday_7493.csv.gz  in=447,846,623 out=113,176,626 elapsed=258.1s

  [18013/20519] intraday_7492.csv.gz  in=447,849,863 out=113,176,626 elapsed=258.1s

  [18014/20519] intraday_7495.csv.gz  in=447,851,286 out=113,176,626 elapsed=258.1s

  [18015/20519] intraday_7494.csv.gz  in=447,853,737 out=113,176,626 elapsed=258.1s

  [18016/20519] intraday_7496.csv.gz  in=447,856,783 out=113,176,626 elapsed=258.1s

  [18017/20519] intraday_7497.csv.gz  in=447,859,244 out=113,176,626 elapsed=258.1s

  [18018/20519] intraday_7499.csv.gz  in=447,861,534 out=113,176,626 elapsed=258.1s

  [18019/20519] intraday_7498.csv.gz  in=447,863,743 out=113,176,626 elapsed=258.1s

  [18020/20519] intraday_7500.csv.gz  in=447,865,929 out=113,176,626 elapsed=258.1s

  [18021/20519] intraday_7502.csv.gz  in=447,867,914 out=113,176,626 elapsed=258.1s

  [18022/20519] intraday_7501.csv.gz  in=447,870,350 out=113,176,626 elapsed=258.1s

  [18023/20519] intraday_7503.csv.gz  in=447,873,000 out=113,176,626 elapsed=258.1s

  [18024/20519] intraday_7504.csv.gz  in=447,875,374 out=113,176,626 elapsed=258.1s

  [18025/20519] intraday_7505.csv.gz  in=447,878,254 out=113,176,626 elapsed=258.1s

  [18026/20519] intraday_7507.csv.gz  in=447,880,505 out=113,176,626 elapsed=258.2s

  [18027/20519] intraday_7506.csv.gz  in=447,883,200 out=113,176,626 elapsed=258.2s

  [18028/20519] intraday_7508.csv.gz  in=447,885,346 out=113,176,626 elapsed=258.2s

  [18029/20519] intraday_7509.csv.gz  in=447,886,747 out=113,176,626 elapsed=258.2s

  [18030/20519] intraday_7510.csv.gz  in=447,888,944 out=113,176,626 elapsed=258.2s

  [18031/20519] intraday_7512.csv.gz  in=447,892,480 out=113,176,626 elapsed=258.2s

  [18032/20519] intraday_7511.csv.gz  in=447,894,501 out=113,176,626 elapsed=258.2s

  [18033/20519] intraday_7514.csv.gz  in=447,896,409 out=113,176,626 elapsed=258.2s

  [18034/20519] intraday_7513.csv.gz  in=447,898,408 out=113,176,626 elapsed=258.2s

  [18035/20519] intraday_7516.csv.gz  in=447,900,782 out=113,176,626 elapsed=258.2s

  [18036/20519] intraday_7515.csv.gz  in=447,905,002 out=113,176,626 elapsed=258.2s

  [18037/20519] intraday_7518.csv.gz  in=447,908,887 out=113,176,626 elapsed=258.2s

  [18038/20519] intraday_7517.csv.gz  in=447,915,788 out=113,176,626 elapsed=258.2s

  [18039/20519] intraday_7520.csv.gz  in=447,917,432 out=113,176,626 elapsed=258.2s

  [18040/20519] intraday_7519.csv.gz  in=447,919,873 out=113,176,626 elapsed=258.2s

  [18041/20519] intraday_7521.csv.gz  in=447,922,462 out=113,176,626 elapsed=258.2s

  [18042/20519] intraday_7522.csv.gz  in=447,925,116 out=113,176,626 elapsed=258.3s

  [18043/20519] intraday_7523.csv.gz  in=447,926,817 out=113,176,626 elapsed=258.3s

  [18044/20519] intraday_7525.csv.gz  in=447,928,603 out=113,176,626 elapsed=258.3s

  [18045/20519] intraday_7524.csv.gz  in=447,931,729 out=113,176,626 elapsed=258.3s

  [18046/20519] intraday_7526.csv.gz  in=447,933,386 out=113,176,626 elapsed=258.3s

  [18047/20519] intraday_7527.csv.gz  in=447,935,629 out=113,176,626 elapsed=258.3s

  [18048/20519] intraday_7529.csv.gz  in=447,939,242 out=113,176,626 elapsed=258.3s

  [18049/20519] intraday_7528.csv.gz  in=447,943,003 out=113,176,626 elapsed=258.3s

  [18050/20519] intraday_7530.csv.gz  in=447,945,488 out=113,176,626 elapsed=258.3s

  [18051/20519] intraday_7531.csv.gz  in=447,948,126 out=113,176,626 elapsed=258.3s

  [18052/20519] intraday_7533.csv.gz  in=447,950,560 out=113,176,626 elapsed=258.3s

  [18053/20519] intraday_7532.csv.gz  in=447,953,025 out=113,176,626 elapsed=258.3s

  [18054/20519] intraday_7535.csv.gz  in=447,955,479 out=113,176,626 elapsed=258.3s

  [18055/20519] intraday_7534.csv.gz  in=447,957,942 out=113,176,626 elapsed=258.3s

  [18056/20519] intraday_7536.csv.gz  in=447,961,103 out=113,176,626 elapsed=258.3s

  [18057/20519] intraday_7537.csv.gz  in=447,963,052 out=113,176,626 elapsed=258.3s

  [18058/20519] intraday_7538.csv.gz  in=447,966,152 out=113,176,626 elapsed=258.4s

  [18059/20519] intraday_7539.csv.gz  in=447,968,068 out=113,176,626 elapsed=258.4s

  [18060/20519] intraday_7541.csv.gz  in=447,970,172 out=113,176,626 elapsed=258.4s

  [18061/20519] intraday_7540.csv.gz  in=447,972,926 out=113,176,626 elapsed=258.4s

  [18062/20519] intraday_7542.csv.gz  in=447,975,093 out=113,176,626 elapsed=258.4s

  [18063/20519] intraday_7544.csv.gz  in=447,976,464 out=113,176,626 elapsed=258.4s

  [18064/20519] intraday_7543.csv.gz  in=447,978,619 out=113,176,626 elapsed=258.4s

  [18065/20519] intraday_7545.csv.gz  in=447,981,394 out=113,176,626 elapsed=258.4s

  [18066/20519] intraday_7547.csv.gz  in=447,987,027 out=113,176,626 elapsed=258.4s

  [18067/20519] intraday_7546.csv.gz  in=447,992,281 out=113,176,626 elapsed=258.4s

  [18068/20519] intraday_7548.csv.gz  in=447,995,801 out=113,176,626 elapsed=258.4s

  [18069/20519] intraday_7549.csv.gz  in=447,998,409 out=113,176,626 elapsed=258.4s

  [18070/20519] intraday_7550.csv.gz  in=448,001,076 out=113,176,626 elapsed=258.4s

  [18071/20519] intraday_7551.csv.gz  in=448,005,207 out=113,176,626 elapsed=258.4s

  [18072/20519] intraday_7554.csv.gz  in=448,007,415 out=113,176,626 elapsed=258.4s

  [18073/20519] intraday_7553.csv.gz  in=448,012,233 out=113,176,626 elapsed=258.5s

  [18074/20519] intraday_7552.csv.gz  in=448,015,274 out=113,176,626 elapsed=258.5s

  [18075/20519] intraday_7555.csv.gz  in=448,017,769 out=113,176,626 elapsed=258.5s

  [18076/20519] intraday_7556.csv.gz  in=448,020,883 out=113,176,626 elapsed=258.5s

  [18077/20519] intraday_7558.csv.gz  in=448,023,319 out=113,176,626 elapsed=258.5s

  [18078/20519] intraday_7557.csv.gz  in=448,026,315 out=113,176,626 elapsed=258.5s

  [18079/20519] intraday_7560.csv.gz  in=448,028,846 out=113,176,626 elapsed=258.5s

  [18080/20519] intraday_7559.csv.gz  in=448,031,039 out=113,176,626 elapsed=258.5s

  [18081/20519] intraday_7562.csv.gz  in=448,035,268 out=113,176,626 elapsed=258.5s

  [18082/20519] intraday_7561.csv.gz  in=448,038,156 out=113,176,626 elapsed=258.5s

  [18083/20519] intraday_7563.csv.gz  in=448,039,542 out=113,176,626 elapsed=258.5s

  [18084/20519] intraday_7564.csv.gz  in=448,041,726 out=113,176,626 elapsed=258.5s

  [18085/20519] intraday_7565.csv.gz  in=448,045,504 out=113,176,626 elapsed=258.5s

  [18086/20519] intraday_7566.csv.gz  in=448,050,217 out=113,176,626 elapsed=258.5s

  [18087/20519] intraday_7568.csv.gz  in=448,052,989 out=113,176,626 elapsed=258.5s

  [18088/20519] intraday_7567.csv.gz  in=448,055,105 out=113,176,626 elapsed=258.5s

  [18089/20519] intraday_7569.csv.gz  in=448,059,596 out=113,176,626 elapsed=258.5s

  [18090/20519] intraday_7570.csv.gz  in=448,065,624 out=113,176,626 elapsed=258.6s

  [18091/20519] intraday_7571.csv.gz  in=448,067,762 out=113,176,626 elapsed=258.6s

  [18092/20519] intraday_7572.csv.gz  in=448,071,283 out=113,176,626 elapsed=258.6s

  [18093/20519] intraday_7573.csv.gz  in=448,075,644 out=113,176,626 elapsed=258.6s

  [18094/20519] intraday_7575.csv.gz  in=448,078,139 out=113,176,626 elapsed=258.6s

  [18095/20519] intraday_7574.csv.gz  in=448,080,570 out=113,176,626 elapsed=258.6s

  [18096/20519] intraday_7577.csv.gz  in=448,083,230 out=113,176,626 elapsed=258.6s

  [18097/20519] intraday_7576.csv.gz  in=448,090,748 out=113,176,626 elapsed=258.6s

  [18098/20519] intraday_7580.csv.gz  in=448,095,181 out=113,176,626 elapsed=258.6s

  [18099/20519] intraday_7579.csv.gz  in=448,098,427 out=113,176,626 elapsed=258.6s

  [18100/20519] intraday_7578.csv.gz  in=448,104,925 out=113,176,626 elapsed=258.6s

  [18101/20519] intraday_7581.csv.gz  in=448,109,289 out=113,176,626 elapsed=258.6s

  [18102/20519] intraday_7585.csv.gz  in=448,111,684 out=113,176,626 elapsed=258.6s

  [18103/20519] intraday_7582.csv.gz  in=448,114,534 out=113,176,626 elapsed=258.6s

  [18104/20519] intraday_7584.csv.gz  in=448,116,656 out=113,176,626 elapsed=258.6s

  [18105/20519] intraday_7583.csv.gz  in=448,119,827 out=113,176,626 elapsed=258.7s

  [18106/20519] intraday_7586.csv.gz  in=448,122,430 out=113,176,626 elapsed=258.7s

  [18107/20519] intraday_7587.csv.gz  in=448,124,520 out=113,176,626 elapsed=258.7s

  [18108/20519] intraday_7588.csv.gz  in=448,130,055 out=113,176,626 elapsed=258.7s

  [18109/20519] intraday_7590.csv.gz  in=448,134,401 out=113,176,626 elapsed=258.7s

  [18110/20519] intraday_7589.csv.gz  in=448,138,356 out=113,176,626 elapsed=258.7s

  [18111/20519] intraday_7591.csv.gz  in=448,143,631 out=113,176,626 elapsed=258.7s

  [18112/20519] intraday_7592.csv.gz  in=448,145,573 out=113,176,626 elapsed=258.7s

  [18113/20519] intraday_7594.csv.gz  in=448,148,340 out=113,176,626 elapsed=258.7s

  [18114/20519] intraday_7593.csv.gz  in=448,151,479 out=113,176,626 elapsed=258.7s

  [18115/20519] intraday_7595.csv.gz  in=448,154,003 out=113,176,626 elapsed=258.7s

  [18116/20519] intraday_7597.csv.gz  in=448,156,805 out=113,176,626 elapsed=258.7s

  [18117/20519] intraday_7596.csv.gz  in=448,159,724 out=113,176,626 elapsed=258.8s

  [18118/20519] intraday_7599.csv.gz  in=448,162,130 out=113,176,626 elapsed=258.8s

  [18119/20519] intraday_7598.csv.gz  in=448,164,759 out=113,176,626 elapsed=258.8s

  [18120/20519] intraday_7600.csv.gz  in=448,166,610 out=113,176,626 elapsed=258.8s

  [18121/20519] intraday_7601.csv.gz  in=448,169,758 out=113,176,626 elapsed=258.8s

  [18122/20519] intraday_7602.csv.gz  in=448,171,809 out=113,176,626 elapsed=258.8s

  [18123/20519] intraday_7604.csv.gz  in=448,174,746 out=113,176,626 elapsed=258.8s

  [18124/20519] intraday_7603.csv.gz  in=448,177,362 out=113,176,626 elapsed=258.8s

  [18125/20519] intraday_7605.csv.gz  in=448,179,355 out=113,176,626 elapsed=258.8s

  [18126/20519] intraday_7608.csv.gz  in=448,179,360 out=113,176,626 elapsed=258.8s

  [18127/20519] intraday_7607.csv.gz  in=448,180,492 out=113,176,626 elapsed=258.8s

  [18128/20519] intraday_7606.csv.gz  in=448,183,365 out=113,176,626 elapsed=258.8s

  [18129/20519] intraday_7610.csv.gz  in=448,196,043 out=113,176,626 elapsed=258.8s

  [18130/20519] intraday_7611.csv.gz  in=448,209,420 out=113,176,626 elapsed=258.9s

  [18131/20519] intraday_7609.csv.gz  in=448,227,288 out=113,176,626 elapsed=258.9s

  [18132/20519] intraday_7612.csv.gz  in=448,239,012 out=113,176,626 elapsed=258.9s

  [18133/20519] intraday_7613.csv.gz  in=448,253,847 out=113,176,626 elapsed=258.9s

  [18134/20519] intraday_7614.csv.gz  in=448,269,631 out=113,176,626 elapsed=258.9s

  [18135/20519] intraday_7616.csv.gz  in=448,283,311 out=113,176,626 elapsed=258.9s

  [18136/20519] intraday_7615.csv.gz  in=448,296,968 out=113,176,626 elapsed=258.9s

  [18137/20519] intraday_7617.csv.gz  in=448,310,227 out=113,176,626 elapsed=258.9s

  [18138/20519] intraday_7619.csv.gz  in=448,324,445 out=113,176,626 elapsed=258.9s

  [18139/20519] intraday_7618.csv.gz  in=448,338,574 out=113,176,626 elapsed=258.9s

  [18140/20519] intraday_7620.csv.gz  in=448,353,907 out=113,176,626 elapsed=259.0s

  [18141/20519] intraday_7621.csv.gz  in=448,367,188 out=113,176,626 elapsed=259.0s

  [18142/20519] intraday_7623.csv.gz  in=448,378,341 out=113,176,626 elapsed=259.0s

  [18143/20519] intraday_7622.csv.gz  in=448,391,764 out=113,176,626 elapsed=259.0s

  [18144/20519] intraday_7624.csv.gz  in=448,402,524 out=113,176,626 elapsed=259.0s

  [18145/20519] intraday_7626.csv.gz  in=448,416,109 out=113,176,626 elapsed=259.0s

  [18146/20519] intraday_7627.csv.gz  in=448,428,703 out=113,176,626 elapsed=259.0s

  [18147/20519] intraday_7625.csv.gz  in=448,443,024 out=113,176,626 elapsed=259.0s

  [18148/20519] intraday_7628.csv.gz  in=448,453,562 out=113,176,626 elapsed=259.0s

  [18149/20519] intraday_7630.csv.gz  in=448,467,664 out=113,176,626 elapsed=259.0s

  [18150/20519] intraday_7629.csv.gz  in=448,480,997 out=113,176,626 elapsed=259.1s

  [18151/20519] intraday_7631.csv.gz  in=448,492,444 out=113,176,626 elapsed=259.1s

  [18152/20519] intraday_7633.csv.gz  in=448,506,123 out=113,176,626 elapsed=259.1s

  [18153/20519] intraday_7635.csv.gz  in=448,519,661 out=113,176,626 elapsed=259.1s

  [18154/20519] intraday_7632.csv.gz  in=448,534,561 out=113,176,626 elapsed=259.1s

  [18155/20519] intraday_7634.csv.gz  in=448,548,085 out=113,176,626 elapsed=259.1s

  [18156/20519] intraday_7636.csv.gz  in=448,560,939 out=113,176,626 elapsed=259.1s

  [18157/20519] intraday_7638.csv.gz  in=448,573,908 out=113,176,626 elapsed=259.1s

  [18158/20519] intraday_7637.csv.gz  in=448,586,420 out=113,176,626 elapsed=259.1s

  [18159/20519] intraday_7639.csv.gz  in=448,601,619 out=113,176,626 elapsed=259.1s

  [18160/20519] intraday_7640.csv.gz  in=448,614,673 out=113,176,626 elapsed=259.1s

  [18161/20519] intraday_7642.csv.gz  in=448,629,306 out=113,176,626 elapsed=259.2s

  [18162/20519] intraday_7643.csv.gz  in=448,643,694 out=113,176,626 elapsed=259.2s

  [18163/20519] intraday_7641.csv.gz  in=448,654,848 out=113,176,626 elapsed=259.2s

  [18164/20519] intraday_7644.csv.gz  in=448,667,290 out=113,176,626 elapsed=259.2s

  [18165/20519] intraday_7645.csv.gz  in=448,681,452 out=113,176,626 elapsed=259.2s

  [18166/20519] intraday_7646.csv.gz  in=448,693,177 out=113,176,626 elapsed=259.2s

  [18167/20519] intraday_7647.csv.gz  in=448,705,528 out=113,176,626 elapsed=259.2s

  [18168/20519] intraday_7648.csv.gz  in=448,716,092 out=113,176,626 elapsed=259.2s

  [18169/20519] intraday_7649.csv.gz  in=448,729,130 out=113,176,626 elapsed=259.2s

  [18170/20519] intraday_7650.csv.gz  in=448,744,157 out=113,176,626 elapsed=259.3s

  [18171/20519] intraday_7652.csv.gz  in=448,756,458 out=113,176,626 elapsed=259.3s

  [18172/20519] intraday_7651.csv.gz  in=448,769,391 out=113,176,626 elapsed=259.3s

  [18173/20519] intraday_7653.csv.gz  in=448,785,664 out=113,176,626 elapsed=259.3s

  [18174/20519] intraday_7654.csv.gz  in=448,798,334 out=113,176,626 elapsed=259.3s

  [18175/20519] intraday_7655.csv.gz  in=448,811,071 out=113,176,626 elapsed=259.3s

  [18176/20519] intraday_7656.csv.gz  in=448,823,518 out=113,176,626 elapsed=259.3s

  [18177/20519] intraday_7657.csv.gz  in=448,835,889 out=113,176,626 elapsed=259.3s

  [18178/20519] intraday_7658.csv.gz  in=448,847,927 out=113,176,626 elapsed=259.3s

  [18179/20519] intraday_7659.csv.gz  in=448,859,651 out=113,176,626 elapsed=259.4s

  [18180/20519] intraday_7660.csv.gz  in=448,872,888 out=113,176,626 elapsed=259.4s

  [18181/20519] intraday_7661.csv.gz  in=448,885,571 out=113,176,626 elapsed=259.4s

  [18182/20519] intraday_7663.csv.gz  in=448,900,712 out=113,176,626 elapsed=259.4s

  [18183/20519] intraday_7665.csv.gz  in=448,914,381 out=113,176,626 elapsed=259.4s

  [18184/20519] intraday_7664.csv.gz  in=448,927,022 out=113,176,626 elapsed=259.4s

  [18185/20519] intraday_7662.csv.gz  in=448,942,134 out=113,176,626 elapsed=259.4s

  [18186/20519] intraday_7666.csv.gz  in=448,952,637 out=113,176,626 elapsed=259.4s

  [18187/20519] intraday_7669.csv.gz  in=448,964,562 out=113,176,626 elapsed=259.4s

  [18188/20519] intraday_7667.csv.gz  in=448,978,708 out=113,176,626 elapsed=259.5s

  [18189/20519] intraday_7668.csv.gz  in=448,992,720 out=113,176,626 elapsed=259.5s

  [18190/20519] intraday_7670.csv.gz  in=449,006,413 out=113,176,626 elapsed=259.5s

  [18191/20519] intraday_7671.csv.gz  in=449,019,039 out=113,176,626 elapsed=259.5s

  [18192/20519] intraday_7672.csv.gz  in=449,030,264 out=113,176,626 elapsed=259.5s

  [18193/20519] intraday_7673.csv.gz  in=449,043,369 out=113,176,626 elapsed=259.5s

  [18194/20519] intraday_7674.csv.gz  in=449,057,205 out=113,176,626 elapsed=259.5s

  [18195/20519] intraday_7675.csv.gz  in=449,072,914 out=113,176,626 elapsed=259.5s

  [18196/20519] intraday_7677.csv.gz  in=449,086,677 out=113,176,626 elapsed=259.5s

  [18197/20519] intraday_7678.csv.gz  in=449,098,676 out=113,176,626 elapsed=259.5s

  [18198/20519] intraday_7676.csv.gz  in=449,113,979 out=113,176,626 elapsed=259.5s

  [18199/20519] intraday_7679.csv.gz  in=449,125,950 out=113,176,626 elapsed=259.5s

  [18200/20519] intraday_7680.csv.gz  in=449,138,135 out=113,176,626 elapsed=259.6s

  [18201/20519] intraday_7682.csv.gz  in=449,152,188 out=113,176,626 elapsed=259.6s

  [18202/20519] intraday_7683.csv.gz  in=449,165,061 out=113,176,626 elapsed=259.6s

  [18203/20519] intraday_7681.csv.gz  in=449,177,734 out=113,176,626 elapsed=259.6s

  [18204/20519] intraday_7685.csv.gz  in=449,189,481 out=113,176,626 elapsed=259.6s

  [18205/20519] intraday_7687.csv.gz  in=449,200,513 out=113,176,626 elapsed=259.6s

  [18206/20519] intraday_7684.csv.gz  in=449,210,928 out=113,176,626 elapsed=259.6s

  [18207/20519] intraday_7686.csv.gz  in=449,224,890 out=113,176,626 elapsed=259.6s

  [18208/20519] intraday_7688.csv.gz  in=449,237,305 out=113,176,626 elapsed=259.7s

  [18209/20519] intraday_7689.csv.gz  in=449,248,209 out=113,176,626 elapsed=259.7s

  [18210/20519] intraday_7691.csv.gz  in=449,261,387 out=113,176,626 elapsed=259.7s

  [18211/20519] intraday_7690.csv.gz  in=449,273,862 out=113,176,626 elapsed=259.7s

  [18212/20519] intraday_7694.csv.gz  in=449,287,542 out=113,176,626 elapsed=259.7s

  [18213/20519] intraday_7692.csv.gz  in=449,305,328 out=113,176,626 elapsed=259.7s

  [18214/20519] intraday_7695.csv.gz  in=449,317,045 out=113,176,626 elapsed=259.8s

  [18215/20519] intraday_7693.csv.gz  in=449,332,641 out=113,176,626 elapsed=259.8s

  [18216/20519] intraday_7696.csv.gz  in=449,346,358 out=113,176,626 elapsed=259.8s

  [18217/20519] intraday_7698.csv.gz  in=449,362,936 out=113,176,626 elapsed=259.8s

  [18218/20519] intraday_7697.csv.gz  in=449,379,448 out=113,176,626 elapsed=259.8s

  [18219/20519] intraday_7699.csv.gz  in=449,393,142 out=113,176,626 elapsed=259.9s

  [18220/20519] intraday_7700.csv.gz  in=449,406,888 out=113,176,626 elapsed=259.9s

  [18221/20519] intraday_7701.csv.gz  in=449,420,777 out=113,176,626 elapsed=259.9s

  [18222/20519] intraday_7702.csv.gz  in=449,434,092 out=113,176,626 elapsed=259.9s

  [18223/20519] intraday_7703.csv.gz  in=449,448,085 out=113,176,626 elapsed=259.9s

  [18224/20519] intraday_7704.csv.gz  in=449,461,647 out=113,176,626 elapsed=259.9s

  [18225/20519] intraday_7705.csv.gz  in=449,474,466 out=113,176,626 elapsed=259.9s

  [18226/20519] intraday_7706.csv.gz  in=449,487,170 out=113,176,626 elapsed=259.9s

  [18227/20519] intraday_7708.csv.gz  in=449,500,948 out=113,176,626 elapsed=259.9s

  [18228/20519] intraday_7707.csv.gz  in=449,514,724 out=113,176,626 elapsed=259.9s

  [18229/20519] intraday_7709.csv.gz  in=449,525,147 out=113,176,626 elapsed=260.0s

  [18230/20519] intraday_7710.csv.gz  in=449,538,010 out=113,176,626 elapsed=260.0s

  [18231/20519] intraday_7711.csv.gz  in=449,553,803 out=113,176,626 elapsed=260.0s

  [18232/20519] intraday_7712.csv.gz  in=449,567,634 out=113,176,626 elapsed=260.0s

  [18233/20519] intraday_7713.csv.gz  in=449,581,846 out=113,176,626 elapsed=260.0s

  [18234/20519] intraday_7714.csv.gz  in=449,594,019 out=113,176,626 elapsed=260.0s

  [18235/20519] intraday_7715.csv.gz  in=449,610,512 out=113,176,626 elapsed=260.0s

  [18236/20519] intraday_7716.csv.gz  in=449,624,747 out=113,176,626 elapsed=260.0s

  [18237/20519] intraday_7718.csv.gz  in=449,639,824 out=113,176,626 elapsed=260.0s

  [18238/20519] intraday_7717.csv.gz  in=449,654,278 out=113,176,626 elapsed=260.0s

  [18239/20519] intraday_7719.csv.gz  in=449,668,609 out=113,176,626 elapsed=260.0s

  [18240/20519] intraday_7721.csv.gz  in=449,683,522 out=113,176,626 elapsed=260.1s

  [18241/20519] intraday_7722.csv.gz  in=449,696,700 out=113,176,626 elapsed=260.1s

  [18242/20519] intraday_7720.csv.gz  in=449,707,972 out=113,176,626 elapsed=260.1s

  [18243/20519] intraday_7723.csv.gz  in=449,721,586 out=113,176,626 elapsed=260.1s

  [18244/20519] intraday_7727.csv.gz  in=449,736,748 out=113,176,626 elapsed=260.1s

  [18245/20519] intraday_7726.csv.gz  in=449,752,333 out=113,176,626 elapsed=260.1s

  [18246/20519] intraday_7725.csv.gz  in=449,768,057 out=113,176,626 elapsed=260.1s

  [18247/20519] intraday_7724.csv.gz  in=449,785,186 out=113,176,626 elapsed=260.1s

  [18248/20519] intraday_7730.csv.gz  in=449,796,702 out=113,176,626 elapsed=260.2s

  [18249/20519] intraday_7731.csv.gz  in=449,812,145 out=113,176,626 elapsed=260.2s

  [18250/20519] intraday_7728.csv.gz  in=449,824,176 out=113,176,626 elapsed=260.2s

  [18251/20519] intraday_7729.csv.gz  in=449,838,511 out=113,176,626 elapsed=260.2s

  [18252/20519] intraday_7732.csv.gz  in=449,849,395 out=113,176,626 elapsed=260.2s

  [18253/20519] intraday_7734.csv.gz  in=449,862,360 out=113,176,626 elapsed=260.2s

  [18254/20519] intraday_7735.csv.gz  in=449,877,970 out=113,176,626 elapsed=260.2s

  [18255/20519] intraday_7733.csv.gz  in=449,893,147 out=113,176,626 elapsed=260.2s

  [18256/20519] intraday_7736.csv.gz  in=449,904,966 out=113,176,626 elapsed=260.2s

  [18257/20519] intraday_7737.csv.gz  in=449,918,636 out=113,176,626 elapsed=260.2s

  [18258/20519] intraday_7739.csv.gz  in=449,930,623 out=113,176,626 elapsed=260.2s

  [18259/20519] intraday_7738.csv.gz  in=449,943,973 out=113,176,626 elapsed=260.2s

  [18260/20519] intraday_7741.csv.gz  in=449,958,825 out=113,176,626 elapsed=260.3s

  [18261/20519] intraday_7740.csv.gz  in=449,971,894 out=113,176,626 elapsed=260.3s

  [18262/20519] intraday_7742.csv.gz  in=449,986,635 out=113,176,626 elapsed=260.3s

  [18263/20519] intraday_7743.csv.gz  in=450,001,398 out=113,176,626 elapsed=260.3s

  [18264/20519] intraday_7747.csv.gz  in=450,015,771 out=113,176,626 elapsed=260.3s

  [18265/20519] intraday_7744.csv.gz  in=450,030,196 out=113,176,626 elapsed=260.3s

  [18266/20519] intraday_7745.csv.gz  in=450,041,907 out=113,176,626 elapsed=260.3s

  [18267/20519] intraday_7746.csv.gz  in=450,054,149 out=113,176,626 elapsed=260.3s

  [18268/20519] intraday_7748.csv.gz  in=450,066,950 out=113,176,626 elapsed=260.3s

  [18269/20519] intraday_7749.csv.gz  in=450,079,476 out=113,176,626 elapsed=260.4s

  [18270/20519] intraday_7751.csv.gz  in=450,091,968 out=113,176,626 elapsed=260.4s

  [18271/20519] intraday_7750.csv.gz  in=450,101,210 out=113,176,626 elapsed=260.4s

  [18272/20519] intraday_7752.csv.gz  in=450,109,678 out=113,176,626 elapsed=260.4s

  [18273/20519] intraday_7754.csv.gz  in=450,123,220 out=113,176,626 elapsed=260.4s

  [18274/20519] intraday_7753.csv.gz  in=450,138,963 out=113,176,626 elapsed=260.4s

  [18275/20519] intraday_7756.csv.gz  in=450,152,103 out=113,176,626 elapsed=260.4s

  [18276/20519] intraday_7755.csv.gz  in=450,164,258 out=113,176,626 elapsed=260.4s

  [18277/20519] intraday_7757.csv.gz  in=450,175,484 out=113,176,626 elapsed=260.4s

  [18278/20519] intraday_7758.csv.gz  in=450,189,475 out=113,176,626 elapsed=260.4s

  [18279/20519] intraday_7759.csv.gz  in=450,206,841 out=113,176,626 elapsed=260.4s

  [18280/20519] intraday_7760.csv.gz  in=450,217,628 out=113,176,626 elapsed=260.5s

  [18281/20519] intraday_7761.csv.gz  in=450,230,934 out=113,176,626 elapsed=260.5s

  [18282/20519] intraday_7764.csv.gz  in=450,242,805 out=113,176,626 elapsed=260.5s

  [18283/20519] intraday_7762.csv.gz  in=450,256,551 out=113,176,626 elapsed=260.5s

  [18284/20519] intraday_7763.csv.gz  in=450,271,501 out=113,176,626 elapsed=260.5s

  [18285/20519] intraday_7767.csv.gz  in=450,281,625 out=113,176,626 elapsed=260.5s

  [18286/20519] intraday_7765.csv.gz  in=450,295,629 out=113,176,626 elapsed=260.5s

  [18287/20519] intraday_7766.csv.gz  in=450,308,591 out=113,176,626 elapsed=260.5s

  [18288/20519] intraday_7768.csv.gz  in=450,320,987 out=113,176,626 elapsed=260.5s

  [18289/20519] intraday_7769.csv.gz  in=450,335,368 out=113,176,626 elapsed=260.6s

  [18290/20519] intraday_7771.csv.gz  in=450,346,181 out=113,176,626 elapsed=260.6s

  [18291/20519] intraday_7772.csv.gz  in=450,358,356 out=113,176,626 elapsed=260.6s

  [18292/20519] intraday_7770.csv.gz  in=450,372,606 out=113,176,626 elapsed=260.6s

  [18293/20519] intraday_7773.csv.gz  in=450,384,528 out=113,176,626 elapsed=260.6s

  [18294/20519] intraday_7776.csv.gz  in=450,399,769 out=113,176,626 elapsed=260.6s

  [18295/20519] intraday_7775.csv.gz  in=450,410,977 out=113,176,626 elapsed=260.6s

  [18296/20519] intraday_7777.csv.gz  in=450,423,959 out=113,176,626 elapsed=260.6s

  [18297/20519] intraday_7774.csv.gz  in=450,437,232 out=113,176,626 elapsed=260.6s

  [18298/20519] intraday_7778.csv.gz  in=450,453,483 out=113,176,626 elapsed=260.6s

  [18299/20519] intraday_7779.csv.gz  in=450,465,071 out=113,176,626 elapsed=260.6s

  [18300/20519] intraday_7781.csv.gz  in=450,478,316 out=113,176,626 elapsed=260.7s

  [18301/20519] intraday_7782.csv.gz  in=450,490,691 out=113,176,626 elapsed=260.7s

  [18302/20519] intraday_7780.csv.gz  in=450,503,650 out=113,176,626 elapsed=260.7s

  [18303/20519] intraday_7783.csv.gz  in=450,519,584 out=113,176,626 elapsed=260.7s

  [18304/20519] intraday_7786.csv.gz  in=450,532,597 out=113,176,626 elapsed=260.7s

  [18305/20519] intraday_7784.csv.gz  in=450,546,047 out=113,176,626 elapsed=260.7s

  [18306/20519] intraday_7787.csv.gz  in=450,559,895 out=113,176,626 elapsed=260.7s

  [18307/20519] intraday_7785.csv.gz  in=450,570,389 out=113,176,626 elapsed=260.8s

  [18308/20519] intraday_7788.csv.gz  in=450,582,939 out=113,176,626 elapsed=260.8s

  [18309/20519] intraday_7790.csv.gz  in=450,595,075 out=113,176,626 elapsed=260.8s

  [18310/20519] intraday_7789.csv.gz  in=450,608,995 out=113,176,626 elapsed=260.8s

  [18311/20519] intraday_7792.csv.gz  in=450,620,092 out=113,176,626 elapsed=260.8s

  [18312/20519] intraday_7791.csv.gz  in=450,632,769 out=113,176,626 elapsed=260.8s

  [18313/20519] intraday_7793.csv.gz  in=450,644,930 out=113,176,626 elapsed=260.9s

  [18314/20519] intraday_7794.csv.gz  in=450,658,821 out=113,176,626 elapsed=260.9s

  [18315/20519] intraday_7795.csv.gz  in=450,672,984 out=113,176,626 elapsed=260.9s

  [18316/20519] intraday_7796.csv.gz  in=450,683,805 out=113,176,626 elapsed=260.9s

  [18317/20519] intraday_7799.csv.gz  in=450,695,925 out=113,176,626 elapsed=260.9s

  [18318/20519] intraday_7798.csv.gz  in=450,707,787 out=113,176,626 elapsed=260.9s

  [18319/20519] intraday_7800.csv.gz  in=450,721,515 out=113,176,626 elapsed=261.0s

  [18320/20519] intraday_7797.csv.gz  in=450,737,226 out=113,176,626 elapsed=261.0s

  [18321/20519] intraday_7801.csv.gz  in=450,748,429 out=113,176,626 elapsed=261.0s

  [18322/20519] intraday_7802.csv.gz  in=450,760,461 out=113,176,626 elapsed=261.0s

  [18323/20519] intraday_7803.csv.gz  in=450,772,333 out=113,176,626 elapsed=261.0s

  [18324/20519] intraday_7804.csv.gz  in=450,783,778 out=113,176,626 elapsed=261.0s

  [18325/20519] intraday_7807.csv.gz  in=450,797,610 out=113,176,626 elapsed=261.0s

  [18326/20519] intraday_7805.csv.gz  in=450,812,497 out=113,176,626 elapsed=261.0s

  [18327/20519] intraday_7806.csv.gz  in=450,825,974 out=113,176,626 elapsed=261.1s

  [18328/20519] intraday_7808.csv.gz  in=450,839,900 out=113,176,626 elapsed=261.1s

  [18329/20519] intraday_7809.csv.gz  in=450,853,188 out=113,176,626 elapsed=261.1s

  [18330/20519] intraday_7810.csv.gz  in=450,865,301 out=113,176,626 elapsed=261.1s

  [18331/20519] intraday_7811.csv.gz  in=450,880,285 out=113,176,626 elapsed=261.1s

  [18332/20519] intraday_7812.csv.gz  in=450,892,056 out=113,176,626 elapsed=261.1s

  [18333/20519] intraday_7813.csv.gz  in=450,907,493 out=113,176,626 elapsed=261.1s

  [18334/20519] intraday_7814.csv.gz  in=450,920,555 out=113,176,626 elapsed=261.2s

  [18335/20519] intraday_7815.csv.gz  in=450,931,841 out=113,176,626 elapsed=261.2s

  [18336/20519] intraday_7816.csv.gz  in=450,944,033 out=113,176,626 elapsed=261.2s

  [18337/20519] intraday_7817.csv.gz  in=450,954,892 out=113,176,626 elapsed=261.2s

  [18338/20519] intraday_7818.csv.gz  in=450,968,660 out=113,176,626 elapsed=261.2s

  [18339/20519] intraday_7821.csv.gz  in=450,981,410 out=113,176,626 elapsed=261.2s

  [18340/20519] intraday_7822.csv.gz  in=450,992,985 out=113,176,626 elapsed=261.2s

  [18341/20519] intraday_7819.csv.gz  in=451,007,683 out=113,176,626 elapsed=261.2s

  [18342/20519] intraday_7820.csv.gz  in=451,022,945 out=113,176,626 elapsed=261.2s

  [18343/20519] intraday_7823.csv.gz  in=451,035,466 out=113,176,626 elapsed=261.3s

  [18344/20519] intraday_7824.csv.gz  in=451,047,068 out=113,176,626 elapsed=261.3s

  [18345/20519] intraday_7826.csv.gz  in=451,060,907 out=113,176,626 elapsed=261.3s

  [18346/20519] intraday_7825.csv.gz  in=451,074,274 out=113,176,626 elapsed=261.3s

  [18347/20519] intraday_7827.csv.gz  in=451,085,880 out=113,176,626 elapsed=261.3s

  [18348/20519] intraday_7828.csv.gz  in=451,097,645 out=113,176,626 elapsed=261.3s

  [18349/20519] intraday_7829.csv.gz  in=451,108,747 out=113,176,626 elapsed=261.3s

  [18350/20519] intraday_7830.csv.gz  in=451,121,938 out=113,176,626 elapsed=261.4s

  [18351/20519] intraday_7832.csv.gz  in=451,133,687 out=113,176,626 elapsed=261.4s

  [18352/20519] intraday_7831.csv.gz  in=451,144,323 out=113,176,626 elapsed=261.4s

  [18353/20519] intraday_7833.csv.gz  in=451,155,092 out=113,176,626 elapsed=261.4s

  [18354/20519] intraday_7835.csv.gz  in=451,167,233 out=113,176,626 elapsed=261.4s

  [18355/20519] intraday_7834.csv.gz  in=451,180,480 out=113,176,626 elapsed=261.4s

  [18356/20519] intraday_7836.csv.gz  in=451,199,251 out=113,176,626 elapsed=261.4s

  [18357/20519] intraday_7837.csv.gz  in=451,215,603 out=113,176,626 elapsed=261.5s

  [18358/20519] intraday_7839.csv.gz  in=451,227,439 out=113,176,626 elapsed=261.5s

  [18359/20519] intraday_7838.csv.gz  in=451,240,375 out=113,176,626 elapsed=261.5s

  [18360/20519] intraday_7840.csv.gz  in=451,251,836 out=113,176,626 elapsed=261.5s

  [18361/20519] intraday_7841.csv.gz  in=451,267,828 out=113,176,626 elapsed=261.5s

  [18362/20519] intraday_7842.csv.gz  in=451,282,191 out=113,176,626 elapsed=261.5s

  [18363/20519] intraday_7844.csv.gz  in=451,293,912 out=113,176,626 elapsed=261.5s

  [18364/20519] intraday_7843.csv.gz  in=451,309,200 out=113,176,626 elapsed=261.5s

  [18365/20519] intraday_7845.csv.gz  in=451,324,136 out=113,176,626 elapsed=261.5s

  [18366/20519] intraday_7846.csv.gz  in=451,338,952 out=113,176,626 elapsed=261.5s

  [18367/20519] intraday_7847.csv.gz  in=451,350,996 out=113,176,626 elapsed=261.5s

  [18368/20519] intraday_7848.csv.gz  in=451,365,807 out=113,176,626 elapsed=261.6s

  [18369/20519] intraday_7849.csv.gz  in=451,377,510 out=113,176,626 elapsed=261.6s

  [18370/20519] intraday_7850.csv.gz  in=451,390,213 out=113,176,626 elapsed=261.6s

  [18371/20519] intraday_7851.csv.gz  in=451,403,437 out=113,176,626 elapsed=261.6s

  [18372/20519] intraday_7852.csv.gz  in=451,415,977 out=113,176,626 elapsed=261.6s

  [18373/20519] intraday_7853.csv.gz  in=451,427,770 out=113,176,626 elapsed=261.6s

  [18374/20519] intraday_7855.csv.gz  in=451,439,737 out=113,176,626 elapsed=261.6s

  [18375/20519] intraday_7854.csv.gz  in=451,454,532 out=113,176,626 elapsed=261.7s

  [18376/20519] intraday_7856.csv.gz  in=451,470,963 out=113,176,626 elapsed=261.7s

  [18377/20519] intraday_7857.csv.gz  in=451,482,544 out=113,176,626 elapsed=261.7s

  [18378/20519] intraday_7858.csv.gz  in=451,494,926 out=113,176,626 elapsed=261.7s

  [18379/20519] intraday_7861.csv.gz  in=451,507,177 out=113,176,626 elapsed=261.7s

  [18380/20519] intraday_7859.csv.gz  in=451,523,936 out=113,176,626 elapsed=261.7s

  [18381/20519] intraday_7860.csv.gz  in=451,539,119 out=113,176,626 elapsed=261.7s

  [18382/20519] intraday_7862.csv.gz  in=451,554,867 out=113,176,626 elapsed=261.7s

  [18383/20519] intraday_7863.csv.gz  in=451,569,498 out=113,176,626 elapsed=261.7s

  [18384/20519] intraday_7864.csv.gz  in=451,579,700 out=113,176,626 elapsed=261.7s

  [18385/20519] intraday_7867.csv.gz  in=451,594,371 out=113,176,626 elapsed=261.8s

  [18386/20519] intraday_7866.csv.gz  in=451,607,694 out=113,176,626 elapsed=261.8s

  [18387/20519] intraday_7865.csv.gz  in=451,621,105 out=113,176,626 elapsed=261.8s

  [18388/20519] intraday_7868.csv.gz  in=451,640,713 out=113,176,626 elapsed=261.8s

  [18389/20519] intraday_7870.csv.gz  in=451,653,771 out=113,176,626 elapsed=261.8s

  [18390/20519] intraday_7869.csv.gz  in=451,669,498 out=113,176,626 elapsed=261.8s

  [18391/20519] intraday_7871.csv.gz  in=451,686,354 out=113,176,626 elapsed=261.8s

  [18392/20519] intraday_7873.csv.gz  in=451,698,197 out=113,176,626 elapsed=261.9s

  [18393/20519] intraday_7872.csv.gz  in=451,711,588 out=113,176,626 elapsed=261.9s

  [18394/20519] intraday_7874.csv.gz  in=451,723,962 out=113,176,626 elapsed=261.9s

  [18395/20519] intraday_7875.csv.gz  in=451,737,976 out=113,176,626 elapsed=261.9s

  [18396/20519] intraday_7876.csv.gz  in=451,749,360 out=113,176,626 elapsed=261.9s

  [18397/20519] intraday_7879.csv.gz  in=451,763,084 out=113,176,626 elapsed=262.0s

  [18398/20519] intraday_7878.csv.gz  in=451,775,521 out=113,176,626 elapsed=262.0s

  [18399/20519] intraday_7877.csv.gz  in=451,789,578 out=113,176,626 elapsed=262.0s

  [18400/20519] intraday_7880.csv.gz  in=451,804,493 out=113,176,626 elapsed=262.0s

  [18401/20519] intraday_7881.csv.gz  in=451,816,077 out=113,176,626 elapsed=262.0s

  [18402/20519] intraday_7882.csv.gz  in=451,829,980 out=113,176,626 elapsed=262.0s

  [18403/20519] intraday_7883.csv.gz  in=451,842,709 out=113,176,626 elapsed=262.0s

  [18404/20519] intraday_7885.csv.gz  in=451,855,158 out=113,176,626 elapsed=262.1s

  [18405/20519] intraday_7884.csv.gz  in=451,867,603 out=113,176,626 elapsed=262.1s

  [18406/20519] intraday_7887.csv.gz  in=451,881,255 out=113,176,626 elapsed=262.1s

  [18407/20519] intraday_7886.csv.gz  in=451,896,421 out=113,176,626 elapsed=262.1s

  [18408/20519] intraday_7888.csv.gz  in=451,908,635 out=113,176,626 elapsed=262.1s

  [18409/20519] intraday_7889.csv.gz  in=451,923,582 out=113,176,626 elapsed=262.1s

  [18410/20519] intraday_7890.csv.gz  in=451,934,908 out=113,176,626 elapsed=262.2s

  [18411/20519] intraday_7891.csv.gz  in=451,948,065 out=113,176,626 elapsed=262.2s

  [18412/20519] intraday_7892.csv.gz  in=451,959,417 out=113,176,626 elapsed=262.2s

  [18413/20519] intraday_7893.csv.gz  in=451,973,812 out=113,176,626 elapsed=262.2s

  [18414/20519] intraday_7895.csv.gz  in=451,984,457 out=113,176,626 elapsed=262.3s

  [18415/20519] intraday_7896.csv.gz  in=451,998,194 out=113,176,626 elapsed=262.3s

  [18416/20519] intraday_7894.csv.gz  in=452,008,438 out=113,176,626 elapsed=262.3s

  [18417/20519] intraday_7897.csv.gz  in=452,010,099 out=113,176,626 elapsed=262.3s

  [18418/20519] intraday_7898.csv.gz  in=452,027,032 out=113,176,626 elapsed=262.3s

  [18419/20519] intraday_7900.csv.gz  in=452,042,411 out=113,176,626 elapsed=262.3s

  [18420/20519] intraday_7899.csv.gz  in=452,058,571 out=113,176,626 elapsed=262.3s

  [18421/20519] intraday_7901.csv.gz  in=452,071,827 out=113,176,626 elapsed=262.3s

  [18422/20519] intraday_7902.csv.gz  in=452,083,258 out=113,176,626 elapsed=262.4s

  [18423/20519] intraday_7903.csv.gz  in=452,093,847 out=113,176,626 elapsed=262.4s

  [18424/20519] intraday_7904.csv.gz  in=452,108,100 out=113,176,626 elapsed=262.4s

  [18425/20519] intraday_7905.csv.gz  in=452,123,724 out=113,176,626 elapsed=262.4s

  [18426/20519] intraday_7906.csv.gz  in=452,135,356 out=113,176,626 elapsed=262.4s

  [18427/20519] intraday_7908.csv.gz  in=452,149,360 out=113,176,626 elapsed=262.4s

  [18428/20519] intraday_7907.csv.gz  in=452,163,137 out=113,176,626 elapsed=262.5s

  [18429/20519] intraday_7909.csv.gz  in=452,178,542 out=113,176,626 elapsed=262.5s

  [18430/20519] intraday_7910.csv.gz  in=452,191,438 out=113,176,626 elapsed=262.5s

  [18431/20519] intraday_7912.csv.gz  in=452,206,764 out=113,176,626 elapsed=262.5s

  [18432/20519] intraday_7913.csv.gz  in=452,217,876 out=113,176,626 elapsed=262.6s

  [18433/20519] intraday_7911.csv.gz  in=452,231,393 out=113,176,626 elapsed=262.6s

  [18434/20519] intraday_7914.csv.gz  in=452,241,330 out=113,176,626 elapsed=262.6s

  [18435/20519] intraday_7915.csv.gz  in=452,255,592 out=113,176,626 elapsed=262.6s

  [18436/20519] intraday_7918.csv.gz  in=452,267,024 out=113,176,626 elapsed=262.6s

  [18437/20519] intraday_7916.csv.gz  in=452,280,195 out=113,176,626 elapsed=262.6s

  [18438/20519] intraday_7917.csv.gz  in=452,291,001 out=113,176,626 elapsed=262.6s

  [18439/20519] intraday_7919.csv.gz  in=452,302,114 out=113,176,626 elapsed=262.6s

  [18440/20519] intraday_7920.csv.gz  in=452,315,924 out=113,176,626 elapsed=262.7s

  [18441/20519] intraday_7921.csv.gz  in=452,328,034 out=113,176,626 elapsed=262.7s

  [18442/20519] intraday_7922.csv.gz  in=452,342,751 out=113,176,626 elapsed=262.7s

  [18443/20519] intraday_7923.csv.gz  in=452,357,042 out=113,176,626 elapsed=262.7s

  [18444/20519] intraday_7924.csv.gz  in=452,370,803 out=113,176,626 elapsed=262.7s

  [18445/20519] intraday_7925.csv.gz  in=452,384,117 out=113,176,626 elapsed=262.7s

  [18446/20519] intraday_7927.csv.gz  in=452,396,247 out=113,176,626 elapsed=262.7s

  [18447/20519] intraday_7926.csv.gz  in=452,407,697 out=113,176,626 elapsed=262.7s

  [18448/20519] intraday_7929.csv.gz  in=452,423,622 out=113,176,626 elapsed=262.7s

  [18449/20519] intraday_7928.csv.gz  in=452,437,873 out=113,176,626 elapsed=262.8s

  [18450/20519] intraday_7931.csv.gz  in=452,447,685 out=113,176,626 elapsed=262.8s

  [18451/20519] intraday_7930.csv.gz  in=452,460,728 out=113,176,626 elapsed=262.8s

  [18452/20519] intraday_7933.csv.gz  in=452,474,662 out=113,176,626 elapsed=262.8s

  [18453/20519] intraday_7932.csv.gz  in=452,489,151 out=113,176,626 elapsed=262.8s

  [18454/20519] intraday_7935.csv.gz  in=452,502,294 out=113,176,626 elapsed=262.8s

  [18455/20519] intraday_7934.csv.gz  in=452,514,023 out=113,176,626 elapsed=262.8s

  [18456/20519] intraday_7936.csv.gz  in=452,527,370 out=113,176,626 elapsed=262.8s

  [18457/20519] intraday_7937.csv.gz  in=452,540,503 out=113,176,626 elapsed=262.8s

  [18458/20519] intraday_7939.csv.gz  in=452,552,784 out=113,176,626 elapsed=262.9s

  [18459/20519] intraday_7938.csv.gz  in=452,563,484 out=113,176,626 elapsed=262.9s

  [18460/20519] intraday_7940.csv.gz  in=452,575,682 out=113,176,626 elapsed=262.9s

  [18461/20519] intraday_7942.csv.gz  in=452,587,720 out=113,176,626 elapsed=262.9s

  [18462/20519] intraday_7944.csv.gz  in=452,599,664 out=113,176,626 elapsed=262.9s

  [18463/20519] intraday_7943.csv.gz  in=452,614,369 out=113,176,626 elapsed=262.9s

  [18464/20519] intraday_7941.csv.gz  in=452,628,943 out=113,176,626 elapsed=262.9s

  [18465/20519] intraday_7946.csv.gz  in=452,643,576 out=113,176,626 elapsed=262.9s

  [18466/20519] intraday_7947.csv.gz  in=452,656,040 out=113,176,626 elapsed=262.9s

  [18467/20519] intraday_7945.csv.gz  in=452,667,298 out=113,176,626 elapsed=262.9s

  [18468/20519] intraday_7948.csv.gz  in=452,679,149 out=113,176,626 elapsed=263.0s

  [18469/20519] intraday_7949.csv.gz  in=452,692,173 out=113,176,626 elapsed=263.0s

  [18470/20519] intraday_7950.csv.gz  in=452,704,841 out=113,176,626 elapsed=263.0s

  [18471/20519] intraday_7952.csv.gz  in=452,718,617 out=113,176,626 elapsed=263.0s

  [18472/20519] intraday_7954.csv.gz  in=452,731,419 out=113,176,626 elapsed=263.0s

  [18473/20519] intraday_7953.csv.gz  in=452,746,225 out=113,176,626 elapsed=263.0s

  [18474/20519] intraday_7951.csv.gz  in=452,759,973 out=113,176,626 elapsed=263.0s

  [18475/20519] intraday_7955.csv.gz  in=452,772,121 out=113,176,626 elapsed=263.0s

  [18476/20519] intraday_7957.csv.gz  in=452,786,428 out=113,176,626 elapsed=263.1s

  [18477/20519] intraday_7956.csv.gz  in=452,797,354 out=113,176,626 elapsed=263.1s

  [18478/20519] intraday_7959.csv.gz  in=452,810,241 out=113,176,626 elapsed=263.1s

  [18479/20519] intraday_7958.csv.gz  in=452,823,999 out=113,176,626 elapsed=263.1s

  [18480/20519] intraday_7962.csv.gz  in=452,835,441 out=113,176,626 elapsed=263.1s

  [18481/20519] intraday_7960.csv.gz  in=452,848,643 out=113,176,626 elapsed=263.1s

  [18482/20519] intraday_7961.csv.gz  in=452,860,647 out=113,176,626 elapsed=263.1s

  [18483/20519] intraday_7963.csv.gz  in=452,872,168 out=113,176,626 elapsed=263.1s

  [18484/20519] intraday_7964.csv.gz  in=452,886,456 out=113,176,626 elapsed=263.1s

  [18485/20519] intraday_7965.csv.gz  in=452,900,111 out=113,176,626 elapsed=263.1s

  [18486/20519] intraday_7966.csv.gz  in=452,913,809 out=113,176,626 elapsed=263.1s

  [18487/20519] intraday_7967.csv.gz  in=452,929,074 out=113,176,626 elapsed=263.2s

  [18488/20519] intraday_7968.csv.gz  in=452,940,276 out=113,176,626 elapsed=263.2s

  [18489/20519] intraday_7969.csv.gz  in=452,952,938 out=113,176,626 elapsed=263.2s

  [18490/20519] intraday_7970.csv.gz  in=452,965,451 out=113,176,626 elapsed=263.2s

  [18491/20519] intraday_7971.csv.gz  in=452,977,715 out=113,176,626 elapsed=263.2s

  [18492/20519] intraday_7972.csv.gz  in=452,991,718 out=113,176,626 elapsed=263.2s

  [18493/20519] intraday_7973.csv.gz  in=453,003,872 out=113,176,626 elapsed=263.2s

  [18494/20519] intraday_7974.csv.gz  in=453,014,054 out=113,176,626 elapsed=263.2s

  [18495/20519] intraday_7975.csv.gz  in=453,027,960 out=113,176,626 elapsed=263.2s

  [18496/20519] intraday_7976.csv.gz  in=453,039,859 out=113,176,626 elapsed=263.2s

  [18497/20519] intraday_7977.csv.gz  in=453,051,061 out=113,176,626 elapsed=263.2s

  [18498/20519] intraday_7978.csv.gz  in=453,066,925 out=113,176,626 elapsed=263.2s

  [18499/20519] intraday_7979.csv.gz  in=453,077,791 out=113,176,626 elapsed=263.2s

  [18500/20519] intraday_7981.csv.gz  in=453,090,937 out=113,176,626 elapsed=263.2s

  [18501/20519] intraday_7980.csv.gz  in=453,102,794 out=113,176,626 elapsed=263.2s

  [18502/20519] intraday_7982.csv.gz  in=453,119,222 out=113,176,626 elapsed=263.3s

  [18503/20519] intraday_7983.csv.gz  in=453,135,391 out=113,176,626 elapsed=263.3s

  [18504/20519] intraday_7984.csv.gz  in=453,148,373 out=113,176,626 elapsed=263.3s

  [18505/20519] intraday_7985.csv.gz  in=453,161,331 out=113,176,626 elapsed=263.3s

  [18506/20519] intraday_7987.csv.gz  in=453,174,169 out=113,176,626 elapsed=263.3s

  [18507/20519] intraday_7986.csv.gz  in=453,186,468 out=113,176,626 elapsed=263.3s

  [18508/20519] intraday_7989.csv.gz  in=453,198,743 out=113,176,626 elapsed=263.3s

  [18509/20519] intraday_7988.csv.gz  in=453,214,893 out=113,176,626 elapsed=263.3s

  [18510/20519] intraday_7990.csv.gz  in=453,227,394 out=113,176,626 elapsed=263.3s

  [18511/20519] intraday_7991.csv.gz  in=453,241,248 out=113,176,626 elapsed=263.3s

  [18512/20519] intraday_7992.csv.gz  in=453,256,007 out=113,176,626 elapsed=263.4s

  [18513/20519] intraday_7993.csv.gz  in=453,271,280 out=113,176,626 elapsed=263.4s

  [18514/20519] intraday_7994.csv.gz  in=453,285,541 out=113,176,626 elapsed=263.4s

  [18515/20519] intraday_7995.csv.gz  in=453,297,337 out=113,176,626 elapsed=263.4s

  [18516/20519] intraday_7996.csv.gz  in=453,310,169 out=113,176,626 elapsed=263.4s

  [18517/20519] intraday_7997.csv.gz  in=453,323,377 out=113,176,626 elapsed=263.4s

  [18518/20519] intraday_7998.csv.gz  in=453,338,190 out=113,176,626 elapsed=263.4s

  [18519/20519] intraday_7999.csv.gz  in=453,350,519 out=113,176,626 elapsed=263.4s

  [18520/20519] intraday_8000.csv.gz  in=453,360,819 out=113,176,626 elapsed=263.4s

  [18521/20519] intraday_8003.csv.gz  in=453,375,790 out=113,176,626 elapsed=263.4s

  [18522/20519] intraday_8001.csv.gz  in=453,391,844 out=113,176,626 elapsed=263.4s

  [18523/20519] intraday_8002.csv.gz  in=453,405,067 out=113,176,626 elapsed=263.4s

  [18524/20519] intraday_8004.csv.gz  in=453,417,283 out=113,176,626 elapsed=263.5s

  [18525/20519] intraday_8007.csv.gz  in=453,430,393 out=113,176,626 elapsed=263.5s

  [18526/20519] intraday_8006.csv.gz  in=453,443,515 out=113,176,626 elapsed=263.5s

  [18527/20519] intraday_8005.csv.gz  in=453,462,334 out=113,176,626 elapsed=263.5s

  [18528/20519] intraday_8008.csv.gz  in=453,477,065 out=113,176,626 elapsed=263.5s

  [18529/20519] intraday_8010.csv.gz  in=453,488,633 out=113,176,626 elapsed=263.5s

  [18530/20519] intraday_8009.csv.gz  in=453,503,041 out=113,176,626 elapsed=263.5s

  [18531/20519] intraday_8011.csv.gz  in=453,518,528 out=113,176,626 elapsed=263.5s

  [18532/20519] intraday_8012.csv.gz  in=453,532,955 out=113,176,626 elapsed=263.5s

  [18533/20519] intraday_8013.csv.gz  in=453,547,903 out=113,176,626 elapsed=263.5s

  [18534/20519] intraday_8014.csv.gz  in=453,563,746 out=113,176,626 elapsed=263.5s

  [18535/20519] intraday_8015.csv.gz  in=453,578,960 out=113,176,626 elapsed=263.5s

  [18536/20519] intraday_8016.csv.gz  in=453,591,930 out=113,176,626 elapsed=263.6s

  [18537/20519] intraday_8018.csv.gz  in=453,603,840 out=113,176,626 elapsed=263.6s

  [18538/20519] intraday_8017.csv.gz  in=453,622,497 out=113,176,626 elapsed=263.6s

  [18539/20519] intraday_8019.csv.gz  in=453,636,112 out=113,176,626 elapsed=263.6s

  [18540/20519] intraday_8020.csv.gz  in=453,649,066 out=113,176,626 elapsed=263.6s

  [18541/20519] intraday_8021.csv.gz  in=453,662,724 out=113,176,626 elapsed=263.6s

  [18542/20519] intraday_8022.csv.gz  in=453,673,937 out=113,176,626 elapsed=263.6s

  [18543/20519] intraday_8024.csv.gz  in=453,693,929 out=113,176,626 elapsed=263.6s

  [18544/20519] intraday_8023.csv.gz  in=453,708,994 out=113,176,626 elapsed=263.6s

  [18545/20519] intraday_8026.csv.gz  in=453,720,798 out=113,176,626 elapsed=263.6s

  [18546/20519] intraday_8025.csv.gz  in=453,737,187 out=113,176,626 elapsed=263.7s

  [18547/20519] intraday_8027.csv.gz  in=453,750,957 out=113,176,626 elapsed=263.7s

  [18548/20519] intraday_8028.csv.gz  in=453,763,319 out=113,176,626 elapsed=263.7s

  [18549/20519] intraday_8029.csv.gz  in=453,776,809 out=113,176,626 elapsed=263.7s

  [18550/20519] intraday_8031.csv.gz  in=453,791,054 out=113,176,626 elapsed=263.7s

  [18551/20519] intraday_8030.csv.gz  in=453,802,861 out=113,176,626 elapsed=263.7s

  [18552/20519] intraday_8032.csv.gz  in=453,817,592 out=113,176,626 elapsed=263.7s

  [18553/20519] intraday_8033.csv.gz  in=453,831,666 out=113,176,626 elapsed=263.7s

  [18554/20519] intraday_8035.csv.gz  in=453,846,448 out=113,176,626 elapsed=263.8s

  [18555/20519] intraday_8034.csv.gz  in=453,861,987 out=113,176,626 elapsed=263.8s

  [18556/20519] intraday_8036.csv.gz  in=453,872,272 out=113,176,626 elapsed=263.8s

  [18557/20519] intraday_8037.csv.gz  in=453,885,960 out=113,176,626 elapsed=263.8s

  [18558/20519] intraday_8038.csv.gz  in=453,897,710 out=113,176,626 elapsed=263.8s

  [18559/20519] intraday_8040.csv.gz  in=453,906,054 out=113,176,626 elapsed=263.8s

  [18560/20519] intraday_8039.csv.gz  in=453,921,463 out=113,176,626 elapsed=263.8s

  [18561/20519] intraday_8041.csv.gz  in=453,933,712 out=113,176,626 elapsed=263.9s

  [18562/20519] intraday_8042.csv.gz  in=453,945,050 out=113,176,626 elapsed=263.9s

  [18563/20519] intraday_8043.csv.gz  in=453,955,047 out=113,176,626 elapsed=263.9s

  [18564/20519] intraday_8046.csv.gz  in=453,967,955 out=113,176,626 elapsed=263.9s

  [18565/20519] intraday_8045.csv.gz  in=453,982,257 out=113,176,626 elapsed=263.9s

  [18566/20519] intraday_8044.csv.gz  in=453,997,357 out=113,176,626 elapsed=263.9s

  [18567/20519] intraday_8047.csv.gz  in=454,008,614 out=113,176,626 elapsed=263.9s

  [18568/20519] intraday_8050.csv.gz  in=454,022,682 out=113,176,626 elapsed=264.0s

  [18569/20519] intraday_8051.csv.gz  in=454,035,158 out=113,176,626 elapsed=264.0s

  [18570/20519] intraday_8048.csv.gz  in=454,046,353 out=113,176,626 elapsed=264.0s

  [18571/20519] intraday_8049.csv.gz  in=454,061,097 out=113,176,626 elapsed=264.0s

  [18572/20519] intraday_8052.csv.gz  in=454,074,526 out=113,176,626 elapsed=264.0s

  [18573/20519] intraday_8053.csv.gz  in=454,090,039 out=113,176,626 elapsed=264.0s

  [18574/20519] intraday_8054.csv.gz  in=454,104,357 out=113,176,626 elapsed=264.0s

  [18575/20519] intraday_8055.csv.gz  in=454,117,544 out=113,176,626 elapsed=264.0s

  [18576/20519] intraday_8059.csv.gz  in=454,127,580 out=113,176,626 elapsed=264.0s

  [18577/20519] intraday_8058.csv.gz  in=454,137,036 out=113,176,626 elapsed=264.0s

  [18578/20519] intraday_8057.csv.gz  in=454,150,314 out=113,176,626 elapsed=264.0s

  [18579/20519] intraday_8056.csv.gz  in=454,163,546 out=113,176,626 elapsed=264.0s

  [18580/20519] intraday_8061.csv.gz  in=454,175,941 out=113,176,626 elapsed=264.1s

  [18581/20519] intraday_8060.csv.gz  in=454,189,291 out=113,176,626 elapsed=264.1s

  [18582/20519] intraday_8062.csv.gz  in=454,200,019 out=113,176,626 elapsed=264.1s

  [18583/20519] intraday_8063.csv.gz  in=454,212,179 out=113,176,626 elapsed=264.1s

  [18584/20519] intraday_8064.csv.gz  in=454,224,202 out=113,176,626 elapsed=264.1s

  [18585/20519] intraday_8066.csv.gz  in=454,236,789 out=113,176,626 elapsed=264.1s

  [18586/20519] intraday_8065.csv.gz  in=454,249,342 out=113,176,626 elapsed=264.1s

  [18587/20519] intraday_8067.csv.gz  in=454,262,569 out=113,176,626 elapsed=264.1s

  [18588/20519] intraday_8068.csv.gz  in=454,275,754 out=113,176,626 elapsed=264.1s

  [18589/20519] intraday_8069.csv.gz  in=454,289,355 out=113,176,626 elapsed=264.1s

  [18590/20519] intraday_8071.csv.gz  in=454,300,925 out=113,176,626 elapsed=264.1s

  [18591/20519] intraday_8072.csv.gz  in=454,311,437 out=113,176,626 elapsed=264.2s

  [18592/20519] intraday_8073.csv.gz  in=454,325,767 out=113,176,626 elapsed=264.2s

  [18593/20519] intraday_8070.csv.gz  in=454,347,307 out=113,176,626 elapsed=264.2s

  [18594/20519] intraday_8074.csv.gz  in=454,363,497 out=113,176,626 elapsed=264.2s

  [18595/20519] intraday_8075.csv.gz  in=454,376,210 out=113,176,626 elapsed=264.2s

  [18596/20519] intraday_8077.csv.gz  in=454,389,221 out=113,176,626 elapsed=264.2s

  [18597/20519] intraday_8076.csv.gz  in=454,399,807 out=113,176,626 elapsed=264.2s

  [18598/20519] intraday_8078.csv.gz  in=454,419,435 out=113,176,626 elapsed=264.2s

  [18599/20519] intraday_8080.csv.gz  in=454,432,067 out=113,176,626 elapsed=264.2s

  [18600/20519] intraday_8079.csv.gz  in=454,444,549 out=113,176,626 elapsed=264.2s

  [18601/20519] intraday_8082.csv.gz  in=454,457,327 out=113,176,626 elapsed=264.3s

  [18602/20519] intraday_8081.csv.gz  in=454,469,690 out=113,176,626 elapsed=264.3s

  [18603/20519] intraday_8083.csv.gz  in=454,480,963 out=113,176,626 elapsed=264.3s

  [18604/20519] intraday_8084.csv.gz  in=454,492,196 out=113,176,626 elapsed=264.3s

  [18605/20519] intraday_8086.csv.gz  in=454,504,814 out=113,176,626 elapsed=264.3s

  [18606/20519] intraday_8085.csv.gz  in=454,516,885 out=113,176,626 elapsed=264.3s

  [18607/20519] intraday_8089.csv.gz  in=454,528,131 out=113,176,626 elapsed=264.3s

  [18608/20519] intraday_8088.csv.gz  in=454,541,775 out=113,176,626 elapsed=264.3s

  [18609/20519] intraday_8087.csv.gz  in=454,553,183 out=113,176,626 elapsed=264.3s

  [18610/20519] intraday_8090.csv.gz  in=454,564,884 out=113,176,626 elapsed=264.3s

  [18611/20519] intraday_8091.csv.gz  in=454,578,256 out=113,176,626 elapsed=264.4s

  [18612/20519] intraday_8093.csv.gz  in=454,590,493 out=113,176,626 elapsed=264.4s

  [18613/20519] intraday_8092.csv.gz  in=454,602,865 out=113,176,626 elapsed=264.4s

  [18614/20519] intraday_8095.csv.gz  in=454,613,635 out=113,176,626 elapsed=264.4s

  [18615/20519] intraday_8094.csv.gz  in=454,625,444 out=113,176,626 elapsed=264.4s

  [18616/20519] intraday_8096.csv.gz  in=454,641,181 out=113,176,626 elapsed=264.4s

  [18617/20519] intraday_8097.csv.gz  in=454,652,654 out=113,176,626 elapsed=264.4s

  [18618/20519] intraday_8099.csv.gz  in=454,664,804 out=113,176,626 elapsed=264.4s

  [18619/20519] intraday_8098.csv.gz  in=454,679,745 out=113,176,626 elapsed=264.4s

  [18620/20519] intraday_8100.csv.gz  in=454,694,266 out=113,176,626 elapsed=264.4s

  [18621/20519] intraday_8101.csv.gz  in=454,704,830 out=113,176,626 elapsed=264.4s

  [18622/20519] intraday_8103.csv.gz  in=454,717,101 out=113,176,626 elapsed=264.5s

  [18623/20519] intraday_8104.csv.gz  in=454,728,891 out=113,176,626 elapsed=264.5s

  [18624/20519] intraday_8105.csv.gz  in=454,740,998 out=113,176,626 elapsed=264.5s

  [18625/20519] intraday_8102.csv.gz  in=454,753,484 out=113,176,626 elapsed=264.5s

  [18626/20519] intraday_8106.csv.gz  in=454,765,314 out=113,176,626 elapsed=264.5s

  [18627/20519] intraday_8107.csv.gz  in=454,781,767 out=113,176,626 elapsed=264.5s

  [18628/20519] intraday_8109.csv.gz  in=454,795,193 out=113,176,626 elapsed=264.5s

  [18629/20519] intraday_8108.csv.gz  in=454,806,014 out=113,176,626 elapsed=264.5s

  [18630/20519] intraday_8110.csv.gz  in=454,819,670 out=113,176,626 elapsed=264.5s

  [18631/20519] intraday_8111.csv.gz  in=454,833,143 out=113,176,626 elapsed=264.5s

  [18632/20519] intraday_8112.csv.gz  in=454,845,841 out=113,176,626 elapsed=264.6s

  [18633/20519] intraday_8113.csv.gz  in=454,857,697 out=113,176,626 elapsed=264.6s

  [18634/20519] intraday_8114.csv.gz  in=454,870,700 out=113,176,626 elapsed=264.6s

  [18635/20519] intraday_8115.csv.gz  in=454,883,675 out=113,176,626 elapsed=264.6s

  [18636/20519] intraday_8116.csv.gz  in=454,896,017 out=113,176,626 elapsed=264.6s

  [18637/20519] intraday_8117.csv.gz  in=454,909,163 out=113,176,626 elapsed=264.6s

  [18638/20519] intraday_8118.csv.gz  in=454,920,557 out=113,176,626 elapsed=264.6s

  [18639/20519] intraday_8119.csv.gz  in=454,934,705 out=113,176,626 elapsed=264.6s

  [18640/20519] intraday_8121.csv.gz  in=454,947,636 out=113,176,626 elapsed=264.6s

  [18641/20519] intraday_8120.csv.gz  in=454,957,951 out=113,176,626 elapsed=264.6s

  [18642/20519] intraday_8122.csv.gz  in=454,969,297 out=113,176,626 elapsed=264.7s

  [18643/20519] intraday_8123.csv.gz  in=454,980,963 out=113,176,626 elapsed=264.7s

  [18644/20519] intraday_8124.csv.gz  in=454,991,263 out=113,176,626 elapsed=264.7s

  [18645/20519] intraday_8125.csv.gz  in=455,001,860 out=113,176,626 elapsed=264.7s

  [18646/20519] intraday_8126.csv.gz  in=455,013,763 out=113,176,626 elapsed=264.7s

  [18647/20519] intraday_8127.csv.gz  in=455,027,991 out=113,176,626 elapsed=264.7s

  [18648/20519] intraday_8129.csv.gz  in=455,041,568 out=113,176,626 elapsed=264.7s

  [18649/20519] intraday_8128.csv.gz  in=455,059,360 out=113,176,626 elapsed=264.7s

  [18650/20519] intraday_8130.csv.gz  in=455,071,222 out=113,176,626 elapsed=264.7s

  [18651/20519] intraday_8132.csv.gz  in=455,084,488 out=113,176,626 elapsed=264.8s

  [18652/20519] intraday_8131.csv.gz  in=455,095,859 out=113,176,626 elapsed=264.8s

  [18653/20519] intraday_8135.csv.gz  in=455,108,327 out=113,176,626 elapsed=264.8s

  [18654/20519] intraday_8133.csv.gz  in=455,121,862 out=113,176,626 elapsed=264.8s

  [18655/20519] intraday_8136.csv.gz  in=455,134,302 out=113,176,626 elapsed=264.8s

  [18656/20519] intraday_8137.csv.gz  in=455,146,585 out=113,176,626 elapsed=264.8s

  [18657/20519] intraday_8134.csv.gz  in=455,163,107 out=113,176,626 elapsed=264.8s

  [18658/20519] intraday_8138.csv.gz  in=455,177,238 out=113,176,626 elapsed=264.8s

  [18659/20519] intraday_8139.csv.gz  in=455,192,183 out=113,176,626 elapsed=264.8s

  [18660/20519] intraday_8140.csv.gz  in=455,203,272 out=113,176,626 elapsed=264.9s

  [18661/20519] intraday_8141.csv.gz  in=455,219,165 out=113,176,626 elapsed=264.9s

  [18662/20519] intraday_8142.csv.gz  in=455,230,845 out=113,176,626 elapsed=264.9s

  [18663/20519] intraday_8143.csv.gz  in=455,245,123 out=113,176,626 elapsed=264.9s

  [18664/20519] intraday_8144.csv.gz  in=455,257,671 out=113,176,626 elapsed=264.9s

  [18665/20519] intraday_8146.csv.gz  in=455,270,699 out=113,176,626 elapsed=265.0s

  [18666/20519] intraday_8148.csv.gz  in=455,282,772 out=113,176,626 elapsed=265.0s

  [18667/20519] intraday_8147.csv.gz  in=455,296,775 out=113,176,626 elapsed=265.0s

  [18668/20519] intraday_8145.csv.gz  in=455,308,638 out=113,176,626 elapsed=265.0s

  [18669/20519] intraday_8149.csv.gz  in=455,321,206 out=113,176,626 elapsed=265.0s

  [18670/20519] intraday_8150.csv.gz  in=455,335,529 out=113,176,626 elapsed=265.0s

  [18671/20519] intraday_8151.csv.gz  in=455,350,161 out=113,176,626 elapsed=265.0s

  [18672/20519] intraday_8152.csv.gz  in=455,364,045 out=113,176,626 elapsed=265.0s

  [18673/20519] intraday_8153.csv.gz  in=455,377,877 out=113,176,626 elapsed=265.0s

  [18674/20519] intraday_8154.csv.gz  in=455,394,229 out=113,176,626 elapsed=265.1s

  [18675/20519] intraday_8155.csv.gz  in=455,405,865 out=113,176,626 elapsed=265.1s

  [18676/20519] intraday_8156.csv.gz  in=455,419,242 out=113,176,626 elapsed=265.1s

  [18677/20519] intraday_8157.csv.gz  in=455,433,295 out=113,176,626 elapsed=265.1s

  [18678/20519] intraday_8158.csv.gz  in=455,445,306 out=113,176,626 elapsed=265.1s

  [18679/20519] intraday_8159.csv.gz  in=455,458,984 out=113,176,626 elapsed=265.1s

  [18680/20519] intraday_8160.csv.gz  in=455,474,519 out=113,176,626 elapsed=265.1s

  [18681/20519] intraday_8161.csv.gz  in=455,491,175 out=113,176,626 elapsed=265.1s

  [18682/20519] intraday_8162.csv.gz  in=455,506,312 out=113,176,626 elapsed=265.1s

  [18683/20519] intraday_8165.csv.gz  in=455,521,785 out=113,176,626 elapsed=265.1s

  [18684/20519] intraday_8164.csv.gz  in=455,534,637 out=113,176,626 elapsed=265.1s

  [18685/20519] intraday_8163.csv.gz  in=455,547,563 out=113,176,626 elapsed=265.1s

  [18686/20519] intraday_8166.csv.gz  in=455,558,727 out=113,176,626 elapsed=265.2s

  [18687/20519] intraday_8168.csv.gz  in=455,569,538 out=113,176,626 elapsed=265.2s

  [18688/20519] intraday_8167.csv.gz  in=455,584,101 out=113,176,626 elapsed=265.2s

  [18689/20519] intraday_8169.csv.gz  in=455,598,378 out=113,176,626 elapsed=265.2s

  [18690/20519] intraday_8170.csv.gz  in=455,612,147 out=113,176,626 elapsed=265.2s

  [18691/20519] intraday_8171.csv.gz  in=455,627,465 out=113,176,626 elapsed=265.2s

  [18692/20519] intraday_8172.csv.gz  in=455,643,627 out=113,176,626 elapsed=265.3s

  [18693/20519] intraday_8174.csv.gz  in=455,657,569 out=113,176,626 elapsed=265.3s

  [18694/20519] intraday_8173.csv.gz  in=455,669,890 out=113,176,626 elapsed=265.3s

  [18695/20519] intraday_8175.csv.gz  in=455,681,534 out=113,176,626 elapsed=265.3s

  [18696/20519] intraday_8176.csv.gz  in=455,694,563 out=113,176,626 elapsed=265.3s

  [18697/20519] intraday_8177.csv.gz  in=455,708,472 out=113,176,626 elapsed=265.3s

  [18698/20519] intraday_8179.csv.gz  in=455,722,183 out=113,176,626 elapsed=265.3s

  [18699/20519] intraday_8178.csv.gz  in=455,737,053 out=113,176,626 elapsed=265.3s

  [18700/20519] intraday_8180.csv.gz  in=455,750,576 out=113,176,626 elapsed=265.3s

  [18701/20519] intraday_8181.csv.gz  in=455,763,165 out=113,176,626 elapsed=265.3s

  [18702/20519] intraday_8182.csv.gz  in=455,775,389 out=113,176,626 elapsed=265.4s

  [18703/20519] intraday_8184.csv.gz  in=455,786,892 out=113,176,626 elapsed=265.4s

  [18704/20519] intraday_8183.csv.gz  in=455,799,985 out=113,176,626 elapsed=265.4s

  [18705/20519] intraday_8185.csv.gz  in=455,811,354 out=113,176,626 elapsed=265.4s

  [18706/20519] intraday_8188.csv.gz  in=455,818,034 out=113,176,626 elapsed=265.4s

  [18707/20519] intraday_8186.csv.gz  in=455,825,478 out=113,176,626 elapsed=265.4s

  [18708/20519] intraday_8189.csv.gz  in=455,825,517 out=113,176,626 elapsed=265.4s

  [18709/20519] intraday_8187.csv.gz  in=455,837,800 out=113,176,626 elapsed=265.4s

  [18710/20519] intraday_8191.csv.gz  in=455,840,288 out=113,176,626 elapsed=265.4s

  [18711/20519] intraday_8190.csv.gz  in=455,844,385 out=113,176,626 elapsed=265.4s

  [18712/20519] intraday_8192.csv.gz  in=455,845,400 out=113,176,626 elapsed=265.4s

  [18713/20519] intraday_8193.csv.gz  in=455,846,337 out=113,176,626 elapsed=265.4s

  [18714/20519] intraday_8194.csv.gz  in=455,846,967 out=113,176,626 elapsed=265.4s

  [18715/20519] intraday_8195.csv.gz  in=455,847,052 out=113,176,626 elapsed=265.4s

  [18716/20519] intraday_8196.csv.gz  in=455,847,118 out=113,176,626 elapsed=265.5s

  [18717/20519] intraday_8198.csv.gz  in=455,847,472 out=113,176,626 elapsed=265.5s

  [18718/20519] intraday_8197.csv.gz  in=455,850,280 out=113,176,626 elapsed=265.5s

  [18719/20519] intraday_8200.csv.gz  in=455,850,440 out=113,176,626 elapsed=265.5s

  [18720/20519] intraday_8199.csv.gz  in=455,855,052 out=113,176,626 elapsed=265.5s

  [18721/20519] intraday_8202.csv.gz  in=455,856,375 out=113,176,626 elapsed=265.5s

  [18722/20519] intraday_8201.csv.gz  in=455,861,143 out=113,176,626 elapsed=265.5s

  [18723/20519] intraday_8203.csv.gz  in=455,861,393 out=113,176,626 elapsed=265.5s

  [18724/20519] intraday_8204.csv.gz  in=455,861,433 out=113,176,626 elapsed=265.5s

  [18725/20519] intraday_8206.csv.gz  in=455,861,434 out=113,176,626 elapsed=265.5s

  [18726/20519] intraday_8207.csv.gz  in=455,866,217 out=113,176,626 elapsed=265.5s

  [18727/20519] intraday_8205.csv.gz  in=455,876,940 out=113,176,626 elapsed=265.5s

  [18728/20519] intraday_8209.csv.gz  in=455,877,523 out=113,176,626 elapsed=265.6s

  [18729/20519] intraday_8208.csv.gz  in=455,885,975 out=113,176,626 elapsed=265.6s

  [18730/20519] intraday_8210.csv.gz  in=455,886,093 out=113,176,626 elapsed=265.6s

  [18731/20519] intraday_8211.csv.gz  in=455,887,071 out=113,176,626 elapsed=265.6s

  [18732/20519] intraday_8213.csv.gz  in=455,887,294 out=113,176,626 elapsed=265.6s

  [18733/20519] intraday_8214.csv.gz  in=455,888,909 out=113,176,626 elapsed=265.6s

  [18734/20519] intraday_8212.csv.gz  in=455,902,805 out=113,176,626 elapsed=265.6s

  [18735/20519] intraday_8215.csv.gz  in=455,903,371 out=113,176,626 elapsed=265.6s

  [18736/20519] intraday_8218.csv.gz  in=455,904,456 out=113,176,626 elapsed=265.6s

  [18737/20519] intraday_8217.csv.gz  in=455,905,025 out=113,176,626 elapsed=265.6s

  [18738/20519] intraday_8216.csv.gz  in=455,905,845 out=113,176,626 elapsed=265.6s

  [18739/20519] intraday_8220.csv.gz  in=455,907,103 out=113,176,626 elapsed=265.6s

  [18740/20519] intraday_8219.csv.gz  in=455,907,881 out=113,176,626 elapsed=265.6s

  [18741/20519] intraday_8221.csv.gz  in=455,908,559 out=113,176,626 elapsed=265.6s

  [18742/20519] intraday_8222.csv.gz  in=455,909,240 out=113,176,626 elapsed=265.6s

  [18743/20519] intraday_8225.csv.gz  in=455,910,080 out=113,176,626 elapsed=265.6s

  [18744/20519] intraday_8224.csv.gz  in=455,911,441 out=113,176,626 elapsed=265.6s

  [18745/20519] intraday_8227.csv.gz  in=455,912,505 out=113,176,626 elapsed=265.6s

  [18746/20519] intraday_8223.csv.gz  in=455,913,494 out=113,176,626 elapsed=265.6s

  [18747/20519] intraday_8226.csv.gz  in=455,914,332 out=113,176,626 elapsed=265.6s

  [18748/20519] intraday_8231.csv.gz  in=455,915,145 out=113,176,626 elapsed=265.6s

  [18749/20519] intraday_8228.csv.gz  in=455,915,406 out=113,176,626 elapsed=265.7s

  [18750/20519] intraday_8230.csv.gz  in=455,916,208 out=113,176,626 elapsed=265.7s

  [18751/20519] intraday_8229.csv.gz  in=455,916,548 out=113,176,626 elapsed=265.7s

  [18752/20519] intraday_8233.csv.gz  in=455,916,933 out=113,176,626 elapsed=265.7s

  [18753/20519] intraday_8232.csv.gz  in=455,917,495 out=113,176,626 elapsed=265.7s

  [18754/20519] intraday_8234.csv.gz  in=455,918,167 out=113,176,626 elapsed=265.7s

  [18755/20519] intraday_8235.csv.gz  in=455,918,810 out=113,176,626 elapsed=265.7s

  [18756/20519] intraday_8236.csv.gz  in=455,919,199 out=113,176,626 elapsed=265.7s

  [18757/20519] intraday_8238.csv.gz  in=455,919,640 out=113,176,626 elapsed=265.7s

  [18758/20519] intraday_8239.csv.gz  in=455,920,608 out=113,176,626 elapsed=265.7s

  [18759/20519] intraday_8240.csv.gz  in=455,921,183 out=113,176,626 elapsed=265.7s

  [18760/20519] intraday_8242.csv.gz  in=455,922,166 out=113,176,626 elapsed=265.7s

  [18761/20519] intraday_8237.csv.gz  in=455,923,064 out=113,176,626 elapsed=265.7s

  [18762/20519] intraday_8241.csv.gz  in=455,923,259 out=113,176,626 elapsed=265.7s

  [18763/20519] intraday_8243.csv.gz  in=455,924,349 out=113,176,626 elapsed=265.7s

  [18764/20519] intraday_8245.csv.gz  in=455,925,312 out=113,176,626 elapsed=265.7s

  [18765/20519] intraday_8248.csv.gz  in=455,925,756 out=113,176,626 elapsed=265.7s

  [18766/20519] intraday_8246.csv.gz  in=455,926,306 out=113,176,626 elapsed=265.7s

  [18767/20519] intraday_8249.csv.gz  in=455,927,039 out=113,176,626 elapsed=265.7s

  [18768/20519] intraday_8244.csv.gz  in=455,928,505 out=113,176,626 elapsed=265.7s

  [18769/20519] intraday_8247.csv.gz  in=455,929,082 out=113,176,626 elapsed=265.7s

  [18770/20519] intraday_8250.csv.gz  in=455,929,486 out=113,176,626 elapsed=265.7s

  [18771/20519] intraday_8251.csv.gz  in=455,930,147 out=113,176,626 elapsed=265.7s

  [18772/20519] intraday_8252.csv.gz  in=455,930,698 out=113,176,626 elapsed=265.7s

  [18773/20519] intraday_8254.csv.gz  in=455,931,035 out=113,176,626 elapsed=265.7s

  [18774/20519] intraday_8253.csv.gz  in=455,931,366 out=113,176,626 elapsed=265.7s

  [18775/20519] intraday_8255.csv.gz  in=455,931,856 out=113,176,626 elapsed=265.7s

  [18776/20519] intraday_8257.csv.gz  in=455,932,352 out=113,176,626 elapsed=265.7s

  [18777/20519] intraday_8259.csv.gz  in=455,932,962 out=113,176,626 elapsed=265.8s

  [18778/20519] intraday_8256.csv.gz  in=455,933,340 out=113,176,626 elapsed=265.8s

  [18779/20519] intraday_8258.csv.gz  in=455,933,905 out=113,176,626 elapsed=265.8s

  [18780/20519] intraday_8260.csv.gz  in=455,934,123 out=113,176,626 elapsed=265.8s

  [18781/20519] intraday_8261.csv.gz  in=455,934,642 out=113,176,626 elapsed=265.8s

  [18782/20519] intraday_8264.csv.gz  in=455,934,969 out=113,176,626 elapsed=265.8s

  [18783/20519] intraday_8262.csv.gz  in=455,935,598 out=113,176,626 elapsed=265.8s

  [18784/20519] intraday_8263.csv.gz  in=455,935,879 out=113,176,626 elapsed=265.8s

  [18785/20519] intraday_8265.csv.gz  in=455,936,402 out=113,176,626 elapsed=265.8s

  [18786/20519] intraday_8268.csv.gz  in=455,937,314 out=113,176,626 elapsed=265.8s

  [18787/20519] intraday_8266.csv.gz  in=455,938,436 out=113,176,626 elapsed=265.8s

  [18788/20519] intraday_8267.csv.gz  in=455,939,602 out=113,176,626 elapsed=265.8s

  [18789/20519] intraday_8269.csv.gz  in=455,940,175 out=113,176,626 elapsed=265.8s

  [18790/20519] intraday_8270.csv.gz  in=455,940,390 out=113,176,626 elapsed=265.9s

  [18791/20519] intraday_8271.csv.gz  in=455,940,595 out=113,176,626 elapsed=265.9s

  [18792/20519] intraday_8273.csv.gz  in=455,941,450 out=113,176,626 elapsed=265.9s

  [18793/20519] intraday_8272.csv.gz  in=455,942,421 out=113,176,626 elapsed=265.9s

  [18794/20519] intraday_8274.csv.gz  in=455,942,688 out=113,176,626 elapsed=265.9s

  [18795/20519] intraday_8275.csv.gz  in=455,943,655 out=113,176,626 elapsed=265.9s

  [18796/20519] intraday_8276.csv.gz  in=455,943,783 out=113,176,626 elapsed=265.9s

  [18797/20519] intraday_8278.csv.gz  in=455,944,287 out=113,176,626 elapsed=265.9s

  [18798/20519] intraday_8277.csv.gz  in=455,944,484 out=113,176,626 elapsed=265.9s

  [18799/20519] intraday_8279.csv.gz  in=455,945,960 out=113,176,626 elapsed=265.9s

  [18800/20519] intraday_8280.csv.gz  in=455,947,087 out=113,176,626 elapsed=265.9s

  [18801/20519] intraday_8282.csv.gz  in=455,947,742 out=113,176,626 elapsed=265.9s

  [18802/20519] intraday_8281.csv.gz  in=455,948,089 out=113,176,626 elapsed=265.9s

  [18803/20519] intraday_8283.csv.gz  in=455,948,615 out=113,176,626 elapsed=265.9s

  [18804/20519] intraday_8286.csv.gz  in=455,948,988 out=113,176,626 elapsed=265.9s

  [18805/20519] intraday_8284.csv.gz  in=455,949,432 out=113,176,626 elapsed=265.9s

  [18806/20519] intraday_8287.csv.gz  in=455,950,041 out=113,176,626 elapsed=266.0s

  [18807/20519] intraday_8285.csv.gz  in=455,951,092 out=113,176,626 elapsed=266.0s

  [18808/20519] intraday_8290.csv.gz  in=455,951,607 out=113,176,626 elapsed=266.0s

  [18809/20519] intraday_8291.csv.gz  in=455,952,360 out=113,176,626 elapsed=266.0s

  [18810/20519] intraday_8288.csv.gz  in=455,952,749 out=113,176,626 elapsed=266.0s

  [18811/20519] intraday_8289.csv.gz  in=455,953,784 out=113,176,626 elapsed=266.0s

  [18812/20519] intraday_8293.csv.gz  in=455,954,485 out=113,176,626 elapsed=266.0s

  [18813/20519] intraday_8292.csv.gz  in=455,955,140 out=113,176,626 elapsed=266.0s

  [18814/20519] intraday_8295.csv.gz  in=455,955,503 out=113,176,626 elapsed=266.0s

  [18815/20519] intraday_8294.csv.gz  in=455,955,601 out=113,176,626 elapsed=266.0s

  [18816/20519] intraday_8296.csv.gz  in=455,956,246 out=113,176,626 elapsed=266.0s

  [18817/20519] intraday_8298.csv.gz  in=455,957,712 out=113,176,626 elapsed=266.0s

  [18818/20519] intraday_8300.csv.gz  in=455,958,678 out=113,176,626 elapsed=266.0s

  [18819/20519] intraday_8299.csv.gz  in=455,959,818 out=113,176,626 elapsed=266.0s

  [18820/20519] intraday_8297.csv.gz  in=455,962,148 out=113,176,626 elapsed=266.0s

  [18821/20519] intraday_8302.csv.gz  in=455,963,064 out=113,176,626 elapsed=266.0s

  [18822/20519] intraday_8303.csv.gz  in=455,964,174 out=113,176,626 elapsed=266.0s

  [18823/20519] intraday_8305.csv.gz  in=455,964,447 out=113,176,626 elapsed=266.0s

  [18824/20519] intraday_8301.csv.gz  in=455,964,922 out=113,176,626 elapsed=266.0s

  [18825/20519] intraday_8304.csv.gz  in=455,966,254 out=113,176,626 elapsed=266.0s

  [18826/20519] intraday_8306.csv.gz  in=455,967,078 out=113,176,626 elapsed=266.0s

  [18827/20519] intraday_8308.csv.gz  in=455,967,659 out=113,176,626 elapsed=266.0s

  [18828/20519] intraday_8310.csv.gz  in=455,968,145 out=113,176,626 elapsed=266.0s

  [18829/20519] intraday_8311.csv.gz  in=455,968,483 out=113,176,626 elapsed=266.0s

  [18830/20519] intraday_8307.csv.gz  in=455,969,694 out=113,176,626 elapsed=266.0s

  [18831/20519] intraday_8309.csv.gz  in=455,970,457 out=113,176,626 elapsed=266.0s

  [18832/20519] intraday_8313.csv.gz  in=455,971,439 out=113,176,626 elapsed=266.0s

  [18833/20519] intraday_8314.csv.gz  in=455,971,624 out=113,176,626 elapsed=266.1s

  [18834/20519] intraday_8315.csv.gz  in=455,972,355 out=113,176,626 elapsed=266.1s

  [18835/20519] intraday_8312.csv.gz  in=455,976,620 out=113,176,626 elapsed=266.1s

  [18836/20519] intraday_8316.csv.gz  in=455,978,186 out=113,176,626 elapsed=266.1s

  [18837/20519] intraday_8317.csv.gz  in=455,979,917 out=113,176,626 elapsed=266.1s

  [18838/20519] intraday_8318.csv.gz  in=455,980,763 out=113,176,626 elapsed=266.1s

  [18839/20519] intraday_8319.csv.gz  in=455,981,103 out=113,176,626 elapsed=266.1s

  [18840/20519] intraday_8320.csv.gz  in=455,982,941 out=113,176,626 elapsed=266.1s

  [18841/20519] intraday_8321.csv.gz  in=455,983,438 out=113,176,626 elapsed=266.1s

  [18842/20519] intraday_8325.csv.gz  in=455,984,224 out=113,176,626 elapsed=266.1s

  [18843/20519] intraday_8322.csv.gz  in=455,984,739 out=113,176,626 elapsed=266.1s

  [18844/20519] intraday_8324.csv.gz  in=455,985,343 out=113,176,626 elapsed=266.1s

  [18845/20519] intraday_8323.csv.gz  in=455,986,339 out=113,176,626 elapsed=266.1s

  [18846/20519] intraday_8326.csv.gz  in=455,987,136 out=113,176,626 elapsed=266.1s

  [18847/20519] intraday_8328.csv.gz  in=455,988,238 out=113,176,626 elapsed=266.1s

  [18848/20519] intraday_8327.csv.gz  in=455,988,987 out=113,176,626 elapsed=266.1s

  [18849/20519] intraday_8329.csv.gz  in=455,991,172 out=113,176,626 elapsed=266.1s

  [18850/20519] intraday_8330.csv.gz  in=455,992,632 out=113,176,626 elapsed=266.1s

  [18851/20519] intraday_8331.csv.gz  in=455,993,335 out=113,176,626 elapsed=266.1s

  [18852/20519] intraday_8332.csv.gz  in=455,994,717 out=113,176,626 elapsed=266.1s

  [18853/20519] intraday_8333.csv.gz  in=455,995,589 out=113,176,626 elapsed=266.1s

  [18854/20519] intraday_8334.csv.gz  in=455,996,041 out=113,176,626 elapsed=266.1s

  [18855/20519] intraday_8338.csv.gz  in=455,996,660 out=113,176,626 elapsed=266.1s

  [18856/20519] intraday_8336.csv.gz  in=455,997,183 out=113,176,626 elapsed=266.1s

  [18857/20519] intraday_8337.csv.gz  in=455,997,623 out=113,176,626 elapsed=266.1s

  [18858/20519] intraday_8335.csv.gz  in=455,997,850 out=113,176,626 elapsed=266.2s

  [18859/20519] intraday_8339.csv.gz  in=455,998,610 out=113,176,626 elapsed=266.2s

  [18860/20519] intraday_8340.csv.gz  in=455,999,591 out=113,176,626 elapsed=266.2s

  [18861/20519] intraday_8341.csv.gz  in=456,000,702 out=113,176,626 elapsed=266.2s

  [18862/20519] intraday_8342.csv.gz  in=456,001,342 out=113,176,626 elapsed=266.2s

  [18863/20519] intraday_8343.csv.gz  in=456,002,344 out=113,176,626 elapsed=266.2s

  [18864/20519] intraday_8345.csv.gz  in=456,003,209 out=113,176,626 elapsed=266.2s

  [18865/20519] intraday_8344.csv.gz  in=456,004,128 out=113,176,626 elapsed=266.2s

  [18866/20519] intraday_8346.csv.gz  in=456,004,588 out=113,176,626 elapsed=266.2s

  [18867/20519] intraday_8349.csv.gz  in=456,005,832 out=113,176,626 elapsed=266.2s

  [18868/20519] intraday_8348.csv.gz  in=456,006,250 out=113,176,626 elapsed=266.2s

  [18869/20519] intraday_8347.csv.gz  in=456,006,750 out=113,176,626 elapsed=266.2s

  [18870/20519] intraday_8350.csv.gz  in=456,007,384 out=113,176,626 elapsed=266.2s

  [18871/20519] intraday_8351.csv.gz  in=456,007,748 out=113,176,626 elapsed=266.2s

  [18872/20519] intraday_8352.csv.gz  in=456,008,549 out=113,176,626 elapsed=266.2s

  [18873/20519] intraday_8355.csv.gz  in=456,008,947 out=113,176,626 elapsed=266.2s

  [18874/20519] intraday_8356.csv.gz  in=456,009,329 out=113,176,626 elapsed=266.2s

  [18875/20519] intraday_8357.csv.gz  in=456,010,331 out=113,176,626 elapsed=266.2s

  [18876/20519] intraday_8353.csv.gz  in=456,010,684 out=113,176,626 elapsed=266.2s

  [18877/20519] intraday_8358.csv.gz  in=456,010,693 out=113,176,626 elapsed=266.2s

  [18878/20519] intraday_8354.csv.gz  in=456,011,938 out=113,176,626 elapsed=266.2s

  [18879/20519] intraday_8361.csv.gz  in=456,025,828 out=113,176,626 elapsed=266.3s

  [18880/20519] intraday_8360.csv.gz  in=456,038,316 out=113,176,626 elapsed=266.3s

  [18881/20519] intraday_8359.csv.gz  in=456,053,815 out=113,176,626 elapsed=266.3s

  [18882/20519] intraday_8362.csv.gz  in=456,066,278 out=113,176,626 elapsed=266.3s

  [18883/20519] intraday_8363.csv.gz  in=456,079,405 out=113,176,626 elapsed=266.3s

  [18884/20519] intraday_8366.csv.gz  in=456,091,834 out=113,176,626 elapsed=266.3s

  [18885/20519] intraday_8364.csv.gz  in=456,106,389 out=113,176,626 elapsed=266.3s

  [18886/20519] intraday_8367.csv.gz  in=456,119,610 out=113,176,626 elapsed=266.3s

  [18887/20519] intraday_8365.csv.gz  in=456,135,004 out=113,176,626 elapsed=266.3s

  [18888/20519] intraday_8368.csv.gz  in=456,150,596 out=113,176,626 elapsed=266.4s

  [18889/20519] intraday_8369.csv.gz  in=456,165,581 out=113,176,626 elapsed=266.4s

  [18890/20519] intraday_8371.csv.gz  in=456,180,154 out=113,176,626 elapsed=266.4s

  [18891/20519] intraday_8370.csv.gz  in=456,193,784 out=113,176,626 elapsed=266.4s

  [18892/20519] intraday_8372.csv.gz  in=456,206,930 out=113,176,626 elapsed=266.4s

  [18893/20519] intraday_8373.csv.gz  in=456,216,638 out=113,176,626 elapsed=266.4s

  [18894/20519] intraday_8374.csv.gz  in=456,227,323 out=113,176,626 elapsed=266.4s

  [18895/20519] intraday_8375.csv.gz  in=456,241,122 out=113,176,626 elapsed=266.4s

  [18896/20519] intraday_8377.csv.gz  in=456,252,576 out=113,176,626 elapsed=266.4s

  [18897/20519] intraday_8376.csv.gz  in=456,266,196 out=113,176,626 elapsed=266.4s

  [18898/20519] intraday_8378.csv.gz  in=456,278,238 out=113,176,626 elapsed=266.4s

  [18899/20519] intraday_8379.csv.gz  in=456,290,818 out=113,176,626 elapsed=266.5s

  [18900/20519] intraday_8380.csv.gz  in=456,303,962 out=113,176,626 elapsed=266.5s

  [18901/20519] intraday_8381.csv.gz  in=456,316,716 out=113,176,626 elapsed=266.5s

  [18902/20519] intraday_8382.csv.gz  in=456,331,167 out=113,176,626 elapsed=266.5s

  [18903/20519] intraday_8383.csv.gz  in=456,345,025 out=113,176,626 elapsed=266.5s

  [18904/20519] intraday_8384.csv.gz  in=456,358,210 out=113,176,626 elapsed=266.5s

  [18905/20519] intraday_8386.csv.gz  in=456,371,138 out=113,176,626 elapsed=266.5s

  [18906/20519] intraday_8385.csv.gz  in=456,383,304 out=113,176,626 elapsed=266.5s

  [18907/20519] intraday_8387.csv.gz  in=456,395,300 out=113,176,626 elapsed=266.5s

  [18908/20519] intraday_8388.csv.gz  in=456,410,316 out=113,176,626 elapsed=266.5s

  [18909/20519] intraday_8389.csv.gz  in=456,427,173 out=113,176,626 elapsed=266.6s

  [18910/20519] intraday_8390.csv.gz  in=456,440,472 out=113,176,626 elapsed=266.6s

  [18911/20519] intraday_8391.csv.gz  in=456,452,276 out=113,176,626 elapsed=266.6s

  [18912/20519] intraday_8392.csv.gz  in=456,464,798 out=113,176,626 elapsed=266.6s

  [18913/20519] intraday_8394.csv.gz  in=456,477,167 out=113,176,626 elapsed=266.6s

  [18914/20519] intraday_8395.csv.gz  in=456,489,614 out=113,176,626 elapsed=266.6s

  [18915/20519] intraday_8393.csv.gz  in=456,504,004 out=113,176,626 elapsed=266.6s

  [18916/20519] intraday_8397.csv.gz  in=456,517,462 out=113,176,626 elapsed=266.6s

  [18917/20519] intraday_8396.csv.gz  in=456,529,067 out=113,176,626 elapsed=266.6s

  [18918/20519] intraday_8399.csv.gz  in=456,541,389 out=113,176,626 elapsed=266.6s

  [18919/20519] intraday_8400.csv.gz  in=456,553,972 out=113,176,626 elapsed=266.7s

  [18920/20519] intraday_8401.csv.gz  in=456,567,885 out=113,176,626 elapsed=266.7s

  [18921/20519] intraday_8398.csv.gz  in=456,578,328 out=113,176,626 elapsed=266.7s

  [18922/20519] intraday_8402.csv.gz  in=456,590,954 out=113,176,626 elapsed=266.7s

  [18923/20519] intraday_8403.csv.gz  in=456,604,999 out=113,176,626 elapsed=266.7s

  [18924/20519] intraday_8404.csv.gz  in=456,616,313 out=113,176,626 elapsed=266.7s

  [18925/20519] intraday_8405.csv.gz  in=456,628,149 out=113,176,626 elapsed=266.7s

  [18926/20519] intraday_8406.csv.gz  in=456,641,963 out=113,176,626 elapsed=266.7s

  [18927/20519] intraday_8407.csv.gz  in=456,653,605 out=113,176,626 elapsed=266.7s

  [18928/20519] intraday_8410.csv.gz  in=456,665,827 out=113,176,626 elapsed=266.7s

  [18929/20519] intraday_8409.csv.gz  in=456,677,700 out=113,176,626 elapsed=266.8s

  [18930/20519] intraday_8408.csv.gz  in=456,690,666 out=113,176,626 elapsed=266.8s

  [18931/20519] intraday_8411.csv.gz  in=456,705,631 out=113,176,626 elapsed=266.8s

  [18932/20519] intraday_8412.csv.gz  in=456,718,350 out=113,176,626 elapsed=266.8s

  [18933/20519] intraday_8414.csv.gz  in=456,732,048 out=113,176,626 elapsed=266.8s

  [18934/20519] intraday_8413.csv.gz  in=456,746,681 out=113,176,626 elapsed=266.8s

  [18935/20519] intraday_8415.csv.gz  in=456,758,453 out=113,176,626 elapsed=266.8s

  [18936/20519] intraday_8416.csv.gz  in=456,769,116 out=113,176,626 elapsed=266.8s

  [18937/20519] intraday_8418.csv.gz  in=456,782,848 out=113,176,626 elapsed=266.8s

  [18938/20519] intraday_8417.csv.gz  in=456,797,964 out=113,176,626 elapsed=266.9s

  [18939/20519] intraday_8419.csv.gz  in=456,809,788 out=113,176,626 elapsed=266.9s

  [18940/20519] intraday_8420.csv.gz  in=456,824,019 out=113,176,626 elapsed=266.9s

  [18941/20519] intraday_8422.csv.gz  in=456,835,063 out=113,176,626 elapsed=267.1s

  [18942/20519] intraday_8421.csv.gz  in=456,846,476 out=113,176,626 elapsed=267.1s

  [18943/20519] intraday_8423.csv.gz  in=456,857,619 out=113,176,626 elapsed=267.1s

  [18944/20519] intraday_8424.csv.gz  in=456,872,038 out=113,176,626 elapsed=267.1s

  [18945/20519] intraday_8425.csv.gz  in=456,884,788 out=113,176,626 elapsed=267.1s

  [18946/20519] intraday_8427.csv.gz  in=456,897,546 out=113,176,626 elapsed=267.1s

  [18947/20519] intraday_8426.csv.gz  in=456,912,634 out=113,176,626 elapsed=267.1s

  [18948/20519] intraday_8428.csv.gz  in=456,924,086 out=113,176,626 elapsed=267.1s

  [18949/20519] intraday_8429.csv.gz  in=456,935,559 out=113,176,626 elapsed=267.1s

  [18950/20519] intraday_8430.csv.gz  in=456,948,656 out=113,176,626 elapsed=267.1s

  [18951/20519] intraday_8433.csv.gz  in=456,960,432 out=113,176,626 elapsed=267.1s

  [18952/20519] intraday_8431.csv.gz  in=456,973,156 out=113,176,626 elapsed=267.1s

  [18953/20519] intraday_8434.csv.gz  in=456,983,520 out=113,176,626 elapsed=267.2s

  [18954/20519] intraday_8432.csv.gz  in=456,997,857 out=113,176,626 elapsed=267.2s

  [18955/20519] intraday_8435.csv.gz  in=457,008,923 out=113,176,626 elapsed=267.2s

  [18956/20519] intraday_8438.csv.gz  in=457,021,599 out=113,176,626 elapsed=267.2s

  [18957/20519] intraday_8436.csv.gz  in=457,035,487 out=113,176,626 elapsed=267.2s

  [18958/20519] intraday_8437.csv.gz  in=457,046,350 out=113,176,626 elapsed=267.2s

  [18959/20519] intraday_8439.csv.gz  in=457,056,554 out=113,176,626 elapsed=267.2s

  [18960/20519] intraday_8440.csv.gz  in=457,067,913 out=113,176,626 elapsed=267.2s

  [18961/20519] intraday_8441.csv.gz  in=457,080,389 out=113,176,626 elapsed=267.2s

  [18962/20519] intraday_8442.csv.gz  in=457,096,204 out=113,176,626 elapsed=267.3s

  [18963/20519] intraday_8443.csv.gz  in=457,113,231 out=113,176,626 elapsed=267.3s

  [18964/20519] intraday_8444.csv.gz  in=457,126,823 out=113,176,626 elapsed=267.3s

  [18965/20519] intraday_8445.csv.gz  in=457,138,622 out=113,176,626 elapsed=267.3s

  [18966/20519] intraday_8446.csv.gz  in=457,150,437 out=113,176,626 elapsed=267.3s

  [18967/20519] intraday_8447.csv.gz  in=457,164,992 out=113,176,626 elapsed=267.3s

  [18968/20519] intraday_8448.csv.gz  in=457,179,006 out=113,176,626 elapsed=267.3s

  [18969/20519] intraday_8450.csv.gz  in=457,190,702 out=113,176,626 elapsed=267.3s

  [18970/20519] intraday_8449.csv.gz  in=457,205,484 out=113,176,626 elapsed=267.3s

  [18971/20519] intraday_8451.csv.gz  in=457,219,859 out=113,176,626 elapsed=267.3s

  [18972/20519] intraday_8453.csv.gz  in=457,233,330 out=113,176,626 elapsed=267.3s

  [18973/20519] intraday_8452.csv.gz  in=457,247,606 out=113,176,626 elapsed=267.3s

  [18974/20519] intraday_8454.csv.gz  in=457,261,859 out=113,176,626 elapsed=267.4s

  [18975/20519] intraday_8456.csv.gz  in=457,273,829 out=113,176,626 elapsed=267.4s

  [18976/20519] intraday_8457.csv.gz  in=457,286,681 out=113,176,626 elapsed=267.4s

  [18977/20519] intraday_8455.csv.gz  in=457,299,027 out=113,176,626 elapsed=267.4s

  [18978/20519] intraday_8461.csv.gz  in=457,314,183 out=113,176,626 elapsed=267.4s

  [18979/20519] intraday_8458.csv.gz  in=457,328,442 out=113,176,626 elapsed=267.4s

  [18980/20519] intraday_8460.csv.gz  in=457,341,863 out=113,176,626 elapsed=267.4s

  [18981/20519] intraday_8459.csv.gz  in=457,354,807 out=113,176,626 elapsed=267.4s

  [18982/20519] intraday_8463.csv.gz  in=457,367,484 out=113,176,626 elapsed=267.4s

  [18983/20519] intraday_8462.csv.gz  in=457,381,304 out=113,176,626 elapsed=267.5s

  [18984/20519] intraday_8465.csv.gz  in=457,400,348 out=113,176,626 elapsed=267.5s

  [18985/20519] intraday_8464.csv.gz  in=457,412,620 out=113,176,626 elapsed=267.5s

  [18986/20519] intraday_8466.csv.gz  in=457,425,450 out=113,176,626 elapsed=267.5s

  [18987/20519] intraday_8467.csv.gz  in=457,438,967 out=113,176,626 elapsed=267.5s

  [18988/20519] intraday_8468.csv.gz  in=457,455,705 out=113,176,626 elapsed=267.5s

  [18989/20519] intraday_8469.csv.gz  in=457,469,519 out=113,176,626 elapsed=267.5s

  [18990/20519] intraday_8470.csv.gz  in=457,481,520 out=113,176,626 elapsed=267.5s

  [18991/20519] intraday_8472.csv.gz  in=457,494,500 out=113,176,626 elapsed=267.5s

  [18992/20519] intraday_8473.csv.gz  in=457,507,933 out=113,176,626 elapsed=267.5s

  [18993/20519] intraday_8471.csv.gz  in=457,522,249 out=113,176,626 elapsed=267.5s

  [18994/20519] intraday_8474.csv.gz  in=457,541,641 out=113,176,626 elapsed=267.6s

  [18995/20519] intraday_8475.csv.gz  in=457,555,555 out=113,176,626 elapsed=267.6s

  [18996/20519] intraday_8477.csv.gz  in=457,571,982 out=113,176,626 elapsed=267.6s

  [18997/20519] intraday_8476.csv.gz  in=457,585,756 out=113,176,626 elapsed=267.6s

  [18998/20519] intraday_8478.csv.gz  in=457,599,067 out=113,176,626 elapsed=267.6s

  [18999/20519] intraday_8480.csv.gz  in=457,611,180 out=113,176,626 elapsed=267.6s

  [19000/20519] intraday_8479.csv.gz  in=457,623,023 out=113,176,626 elapsed=267.6s

  [19001/20519] intraday_8481.csv.gz  in=457,636,207 out=113,176,626 elapsed=267.6s

  [19002/20519] intraday_8482.csv.gz  in=457,647,548 out=113,176,626 elapsed=267.6s

  [19003/20519] intraday_8483.csv.gz  in=457,660,128 out=113,176,626 elapsed=267.7s

  [19004/20519] intraday_8486.csv.gz  in=457,671,779 out=113,176,626 elapsed=267.7s

  [19005/20519] intraday_8485.csv.gz  in=457,687,906 out=113,176,626 elapsed=267.7s

  [19006/20519] intraday_8484.csv.gz  in=457,701,895 out=113,176,626 elapsed=267.7s

  [19007/20519] intraday_8487.csv.gz  in=457,715,505 out=113,176,626 elapsed=267.7s

  [19008/20519] intraday_8488.csv.gz  in=457,726,667 out=113,176,626 elapsed=267.7s

  [19009/20519] intraday_8490.csv.gz  in=457,738,001 out=113,176,626 elapsed=267.7s

  [19010/20519] intraday_8489.csv.gz  in=457,753,267 out=113,176,626 elapsed=267.8s

  [19011/20519] intraday_8491.csv.gz  in=457,766,842 out=113,176,626 elapsed=267.8s

  [19012/20519] intraday_8493.csv.gz  in=457,781,388 out=113,176,626 elapsed=267.8s

  [19013/20519] intraday_8495.csv.gz  in=457,795,523 out=113,176,626 elapsed=267.8s

  [19014/20519] intraday_8492.csv.gz  in=457,810,177 out=113,176,626 elapsed=267.8s

  [19015/20519] intraday_8496.csv.gz  in=457,822,173 out=113,176,626 elapsed=267.8s

  [19016/20519] intraday_8494.csv.gz  in=457,836,550 out=113,176,626 elapsed=267.8s

  [19017/20519] intraday_8498.csv.gz  in=457,848,110 out=113,176,626 elapsed=267.8s

  [19018/20519] intraday_8497.csv.gz  in=457,862,357 out=113,176,626 elapsed=267.9s

  [19019/20519] intraday_8500.csv.gz  in=457,872,777 out=113,176,626 elapsed=267.9s

  [19020/20519] intraday_8499.csv.gz  in=457,887,467 out=113,176,626 elapsed=267.9s

  [19021/20519] intraday_8501.csv.gz  in=457,896,145 out=113,176,626 elapsed=267.9s

  [19022/20519] intraday_8502.csv.gz  in=457,910,026 out=113,176,626 elapsed=267.9s

  [19023/20519] intraday_8503.csv.gz  in=457,911,217 out=113,176,626 elapsed=267.9s

  [19024/20519] intraday_8505.csv.gz  in=457,925,380 out=113,176,626 elapsed=267.9s

  [19025/20519] intraday_8507.csv.gz  in=457,937,356 out=113,176,626 elapsed=267.9s

  [19026/20519] intraday_8506.csv.gz  in=457,952,227 out=113,176,626 elapsed=268.0s

  [19027/20519] intraday_8508.csv.gz  in=457,965,156 out=113,176,626 elapsed=268.0s

  [19028/20519] intraday_8504.csv.gz  in=458,011,877 out=113,176,626 elapsed=268.0s

  [19029/20519] intraday_8509.csv.gz  in=458,022,846 out=113,176,626 elapsed=268.0s

  [19030/20519] intraday_8510.csv.gz  in=458,035,850 out=113,176,626 elapsed=268.0s

  [19031/20519] intraday_8512.csv.gz  in=458,049,291 out=113,176,626 elapsed=268.0s

  [19032/20519] intraday_8511.csv.gz  in=458,064,054 out=113,176,626 elapsed=268.0s

  [19033/20519] intraday_8513.csv.gz  in=458,076,783 out=113,176,626 elapsed=268.0s

  [19034/20519] intraday_8514.csv.gz  in=458,088,461 out=113,176,626 elapsed=268.0s

  [19035/20519] intraday_8516.csv.gz  in=458,101,377 out=113,176,626 elapsed=268.0s

  [19036/20519] intraday_8515.csv.gz  in=458,115,845 out=113,176,626 elapsed=268.0s

  [19037/20519] intraday_8518.csv.gz  in=458,128,755 out=113,176,626 elapsed=268.1s

  [19038/20519] intraday_8517.csv.gz  in=458,141,966 out=113,176,626 elapsed=268.1s

  [19039/20519] intraday_8521.csv.gz  in=458,152,265 out=113,176,626 elapsed=268.1s

  [19040/20519] intraday_8519.csv.gz  in=458,165,009 out=113,176,626 elapsed=268.1s

  [19041/20519] intraday_8520.csv.gz  in=458,174,498 out=113,176,626 elapsed=268.1s

  [19042/20519] intraday_8524.csv.gz  in=458,185,001 out=113,176,626 elapsed=268.1s

  [19043/20519] intraday_8525.csv.gz  in=458,195,668 out=113,176,626 elapsed=268.1s

  [19044/20519] intraday_8522.csv.gz  in=458,209,592 out=113,176,626 elapsed=268.1s

  [19045/20519] intraday_8523.csv.gz  in=458,221,861 out=113,176,626 elapsed=268.1s

  [19046/20519] intraday_8527.csv.gz  in=458,234,515 out=113,176,626 elapsed=268.1s

  [19047/20519] intraday_8526.csv.gz  in=458,246,687 out=113,176,626 elapsed=268.1s

  [19048/20519] intraday_8528.csv.gz  in=458,258,514 out=113,176,626 elapsed=268.2s

  [19049/20519] intraday_8529.csv.gz  in=458,271,945 out=113,176,626 elapsed=268.2s

  [19050/20519] intraday_8532.csv.gz  in=458,283,264 out=113,176,626 elapsed=268.2s

  [19051/20519] intraday_8530.csv.gz  in=458,296,276 out=113,176,626 elapsed=268.2s

  [19052/20519] intraday_8533.csv.gz  in=458,307,958 out=113,176,626 elapsed=268.2s

  [19053/20519] intraday_8531.csv.gz  in=458,321,399 out=113,176,626 elapsed=268.2s

  [19054/20519] intraday_8534.csv.gz  in=458,333,365 out=113,176,626 elapsed=268.2s

  [19055/20519] intraday_8536.csv.gz  in=458,348,916 out=113,176,626 elapsed=268.2s

  [19056/20519] intraday_8535.csv.gz  in=458,362,327 out=113,176,626 elapsed=268.2s

  [19057/20519] intraday_8537.csv.gz  in=458,376,399 out=113,176,626 elapsed=268.2s

  [19058/20519] intraday_8539.csv.gz  in=458,388,620 out=113,176,626 elapsed=268.3s

  [19059/20519] intraday_8540.csv.gz  in=458,401,253 out=113,176,626 elapsed=268.3s

  [19060/20519] intraday_8538.csv.gz  in=458,411,881 out=113,176,626 elapsed=268.3s

  [19061/20519] intraday_8541.csv.gz  in=458,423,396 out=113,176,626 elapsed=268.3s

  [19062/20519] intraday_8542.csv.gz  in=458,434,819 out=113,176,626 elapsed=268.3s

  [19063/20519] intraday_8543.csv.gz  in=458,445,069 out=113,176,626 elapsed=268.3s

  [19064/20519] intraday_8544.csv.gz  in=458,457,555 out=113,176,626 elapsed=268.3s

  [19065/20519] intraday_8545.csv.gz  in=458,467,483 out=113,176,626 elapsed=268.3s

  [19066/20519] intraday_8548.csv.gz  in=458,480,425 out=113,176,626 elapsed=268.3s

  [19067/20519] intraday_8546.csv.gz  in=458,491,713 out=113,176,626 elapsed=268.3s

  [19068/20519] intraday_8547.csv.gz  in=458,503,596 out=113,176,626 elapsed=268.3s

  [19069/20519] intraday_8549.csv.gz  in=458,515,189 out=113,176,626 elapsed=268.3s

  [19070/20519] intraday_8551.csv.gz  in=458,525,600 out=113,176,626 elapsed=268.4s

  [19071/20519] intraday_8550.csv.gz  in=458,538,784 out=113,176,626 elapsed=268.4s

  [19072/20519] intraday_8552.csv.gz  in=458,549,974 out=113,176,626 elapsed=268.4s

  [19073/20519] intraday_8553.csv.gz  in=458,562,664 out=113,176,626 elapsed=268.4s

  [19074/20519] intraday_8555.csv.gz  in=458,573,979 out=113,176,626 elapsed=268.4s

  [19075/20519] intraday_8554.csv.gz  in=458,585,709 out=113,176,626 elapsed=268.4s

  [19076/20519] intraday_8556.csv.gz  in=458,597,510 out=113,176,626 elapsed=268.4s

  [19077/20519] intraday_8557.csv.gz  in=458,608,586 out=113,176,626 elapsed=268.4s

  [19078/20519] intraday_8558.csv.gz  in=458,622,333 out=113,176,626 elapsed=268.4s

  [19079/20519] intraday_8559.csv.gz  in=458,632,280 out=113,176,626 elapsed=268.4s

  [19080/20519] intraday_8560.csv.gz  in=458,645,341 out=113,176,626 elapsed=268.4s

  [19081/20519] intraday_8561.csv.gz  in=458,658,563 out=113,176,626 elapsed=268.5s

  [19082/20519] intraday_8562.csv.gz  in=458,670,309 out=113,176,626 elapsed=268.5s

  [19083/20519] intraday_8563.csv.gz  in=458,680,966 out=113,176,626 elapsed=268.5s

  [19084/20519] intraday_8564.csv.gz  in=458,694,401 out=113,176,626 elapsed=268.5s

  [19085/20519] intraday_8565.csv.gz  in=458,706,269 out=113,176,626 elapsed=268.5s

  [19086/20519] intraday_8566.csv.gz  in=458,718,900 out=113,176,626 elapsed=268.5s

  [19087/20519] intraday_8567.csv.gz  in=458,730,299 out=113,176,626 elapsed=268.5s

  [19088/20519] intraday_8568.csv.gz  in=458,741,687 out=113,176,626 elapsed=268.5s

  [19089/20519] intraday_8570.csv.gz  in=458,753,004 out=113,176,626 elapsed=268.5s

  [19090/20519] intraday_8569.csv.gz  in=458,763,976 out=113,176,626 elapsed=268.5s

  [19091/20519] intraday_8572.csv.gz  in=458,776,515 out=113,176,626 elapsed=268.5s

  [19092/20519] intraday_8571.csv.gz  in=458,789,253 out=113,176,626 elapsed=268.5s

  [19093/20519] intraday_8574.csv.gz  in=458,800,809 out=113,176,626 elapsed=268.5s

  [19094/20519] intraday_8573.csv.gz  in=458,815,854 out=113,176,626 elapsed=268.5s

  [19095/20519] intraday_8576.csv.gz  in=458,825,633 out=113,176,626 elapsed=268.5s

  [19096/20519] intraday_8575.csv.gz  in=458,837,205 out=113,176,626 elapsed=268.6s

  [19097/20519] intraday_8577.csv.gz  in=458,849,843 out=113,176,626 elapsed=268.6s

  [19098/20519] intraday_8579.csv.gz  in=458,863,427 out=113,176,626 elapsed=268.6s

  [19099/20519] intraday_8580.csv.gz  in=458,873,848 out=113,176,626 elapsed=268.6s

  [19100/20519] intraday_8578.csv.gz  in=458,885,546 out=113,176,626 elapsed=268.6s

  [19101/20519] intraday_8581.csv.gz  in=458,896,929 out=113,176,626 elapsed=268.6s

  [19102/20519] intraday_8582.csv.gz  in=458,908,345 out=113,176,626 elapsed=268.6s

  [19103/20519] intraday_8583.csv.gz  in=458,921,251 out=113,176,626 elapsed=268.6s

  [19104/20519] intraday_8584.csv.gz  in=458,932,603 out=113,176,626 elapsed=268.6s

  [19105/20519] intraday_8585.csv.gz  in=458,943,088 out=113,176,626 elapsed=268.6s

  [19106/20519] intraday_8586.csv.gz  in=458,953,545 out=113,176,626 elapsed=268.7s

  [19107/20519] intraday_8587.csv.gz  in=458,964,044 out=113,176,626 elapsed=268.7s

  [19108/20519] intraday_8588.csv.gz  in=458,973,885 out=113,176,626 elapsed=268.7s

  [19109/20519] intraday_8589.csv.gz  in=458,988,393 out=113,176,626 elapsed=268.7s

  [19110/20519] intraday_8591.csv.gz  in=459,002,131 out=113,176,626 elapsed=268.7s

  [19111/20519] intraday_8592.csv.gz  in=459,012,501 out=113,176,626 elapsed=268.7s

  [19112/20519] intraday_8590.csv.gz  in=459,030,275 out=113,176,626 elapsed=268.7s

  [19113/20519] intraday_8593.csv.gz  in=459,041,908 out=113,176,626 elapsed=268.7s

  [19114/20519] intraday_8594.csv.gz  in=459,056,232 out=113,176,626 elapsed=268.7s

  [19115/20519] intraday_8595.csv.gz  in=459,067,817 out=113,176,626 elapsed=268.7s

  [19116/20519] intraday_8596.csv.gz  in=459,082,937 out=113,176,626 elapsed=268.7s

  [19117/20519] intraday_8598.csv.gz  in=459,095,734 out=113,176,626 elapsed=268.8s

  [19118/20519] intraday_8599.csv.gz  in=459,107,579 out=113,176,626 elapsed=268.8s

  [19119/20519] intraday_8600.csv.gz  in=459,121,864 out=113,176,626 elapsed=268.8s

  [19120/20519] intraday_8597.csv.gz  in=459,133,520 out=113,176,626 elapsed=268.8s

  [19121/20519] intraday_8601.csv.gz  in=459,147,098 out=113,176,626 elapsed=268.9s

  [19122/20519] intraday_8602.csv.gz  in=459,159,885 out=113,176,626 elapsed=268.9s

  [19123/20519] intraday_8604.csv.gz  in=459,170,596 out=113,176,626 elapsed=268.9s

  [19124/20519] intraday_8603.csv.gz  in=459,182,974 out=113,176,626 elapsed=268.9s

  [19125/20519] intraday_8606.csv.gz  in=459,195,312 out=113,176,626 elapsed=269.0s

  [19126/20519] intraday_8607.csv.gz  in=459,207,438 out=113,176,626 elapsed=269.0s

  [19127/20519] intraday_8605.csv.gz  in=459,220,726 out=113,176,626 elapsed=269.0s

  [19128/20519] intraday_8608.csv.gz  in=459,233,152 out=113,176,626 elapsed=269.0s

  [19129/20519] intraday_8609.csv.gz  in=459,247,510 out=113,176,626 elapsed=269.0s

  [19130/20519] intraday_8610.csv.gz  in=459,258,926 out=113,176,626 elapsed=269.0s

  [19131/20519] intraday_8611.csv.gz  in=459,271,141 out=113,176,626 elapsed=269.0s

  [19132/20519] intraday_8612.csv.gz  in=459,287,115 out=113,176,626 elapsed=269.0s

  [19133/20519] intraday_8613.csv.gz  in=459,299,100 out=113,176,626 elapsed=269.0s

  [19134/20519] intraday_8615.csv.gz  in=459,313,035 out=113,176,626 elapsed=269.1s

  [19135/20519] intraday_8614.csv.gz  in=459,326,466 out=113,176,626 elapsed=269.1s

  [19136/20519] intraday_8617.csv.gz  in=459,336,762 out=113,176,626 elapsed=269.1s

  [19137/20519] intraday_8616.csv.gz  in=459,352,404 out=113,176,626 elapsed=269.1s

  [19138/20519] intraday_8619.csv.gz  in=459,365,207 out=113,176,626 elapsed=269.1s

  [19139/20519] intraday_8618.csv.gz  in=459,377,710 out=113,176,626 elapsed=269.1s

  [19140/20519] intraday_8620.csv.gz  in=459,390,767 out=113,176,626 elapsed=269.1s

  [19141/20519] intraday_8621.csv.gz  in=459,405,205 out=113,176,626 elapsed=269.1s

  [19142/20519] intraday_8622.csv.gz  in=459,421,647 out=113,176,626 elapsed=269.1s

  [19143/20519] intraday_8624.csv.gz  in=459,435,471 out=113,176,626 elapsed=269.1s

  [19144/20519] intraday_8626.csv.gz  in=459,447,930 out=113,176,626 elapsed=269.2s

  [19145/20519] intraday_8623.csv.gz  in=459,476,914 out=113,176,626 elapsed=269.2s

  [19146/20519] intraday_8625.csv.gz  in=459,492,504 out=113,176,626 elapsed=269.2s

  [19147/20519] intraday_8627.csv.gz  in=459,505,917 out=113,176,626 elapsed=269.2s

  [19148/20519] intraday_8628.csv.gz  in=459,515,723 out=113,176,626 elapsed=269.2s

  [19149/20519] intraday_8629.csv.gz  in=459,530,314 out=113,176,626 elapsed=269.2s

  [19150/20519] intraday_8630.csv.gz  in=459,540,072 out=113,176,626 elapsed=269.2s

  [19151/20519] intraday_8631.csv.gz  in=459,552,945 out=113,176,626 elapsed=269.2s

  [19152/20519] intraday_8633.csv.gz  in=459,567,744 out=113,176,626 elapsed=269.2s

  [19153/20519] intraday_8632.csv.gz  in=459,580,868 out=113,176,626 elapsed=269.3s

  [19154/20519] intraday_8635.csv.gz  in=459,592,964 out=113,176,626 elapsed=269.3s

  [19155/20519] intraday_8634.csv.gz  in=459,604,137 out=113,176,626 elapsed=269.3s

  [19156/20519] intraday_8636.csv.gz  in=459,615,747 out=113,176,626 elapsed=269.3s

  [19157/20519] intraday_8637.csv.gz  in=459,627,920 out=113,176,626 elapsed=269.3s

  [19158/20519] intraday_8638.csv.gz  in=459,638,913 out=113,176,626 elapsed=269.3s

  [19159/20519] intraday_8639.csv.gz  in=459,653,304 out=113,176,626 elapsed=269.3s

  [19160/20519] intraday_8640.csv.gz  in=459,667,945 out=113,176,626 elapsed=269.3s

  [19161/20519] intraday_8641.csv.gz  in=459,680,586 out=113,176,626 elapsed=269.3s

  [19162/20519] intraday_8642.csv.gz  in=459,695,615 out=113,176,626 elapsed=269.3s

  [19163/20519] intraday_8643.csv.gz  in=459,708,304 out=113,176,626 elapsed=269.3s

  [19164/20519] intraday_8644.csv.gz  in=459,720,434 out=113,176,626 elapsed=269.3s

  [19165/20519] intraday_8645.csv.gz  in=459,734,183 out=113,176,626 elapsed=269.3s

  [19166/20519] intraday_8646.csv.gz  in=459,745,169 out=113,176,626 elapsed=269.3s

  [19167/20519] intraday_8647.csv.gz  in=459,756,475 out=113,176,626 elapsed=269.3s

  [19168/20519] intraday_8648.csv.gz  in=459,763,464 out=113,176,626 elapsed=269.3s

  [19169/20519] intraday_8649.csv.gz  in=459,774,715 out=113,176,626 elapsed=269.3s

  [19170/20519] intraday_8650.csv.gz  in=459,782,501 out=113,176,626 elapsed=269.4s

  [19171/20519] intraday_8653.csv.gz  in=459,794,903 out=113,176,626 elapsed=269.4s

  [19172/20519] intraday_8651.csv.gz  in=459,810,183 out=113,176,626 elapsed=269.4s

  [19173/20519] intraday_8652.csv.gz  in=459,825,654 out=113,176,626 elapsed=269.4s

  [19174/20519] intraday_8654.csv.gz  in=459,838,583 out=113,176,626 elapsed=269.4s

  [19175/20519] intraday_8655.csv.gz  in=459,850,950 out=113,176,626 elapsed=269.4s

  [19176/20519] intraday_8657.csv.gz  in=459,866,034 out=113,176,626 elapsed=269.4s

  [19177/20519] intraday_8656.csv.gz  in=459,877,725 out=113,176,626 elapsed=269.4s

  [19178/20519] intraday_8658.csv.gz  in=459,892,546 out=113,176,626 elapsed=269.4s

  [19179/20519] intraday_8659.csv.gz  in=459,904,424 out=113,176,626 elapsed=269.4s

  [19180/20519] intraday_8660.csv.gz  in=459,917,362 out=113,176,626 elapsed=269.5s

  [19181/20519] intraday_8662.csv.gz  in=459,931,454 out=113,176,626 elapsed=269.5s

  [19182/20519] intraday_8661.csv.gz  in=459,945,647 out=113,176,626 elapsed=269.5s

  [19183/20519] intraday_8663.csv.gz  in=459,958,765 out=113,176,626 elapsed=269.5s

  [19184/20519] intraday_8664.csv.gz  in=459,972,946 out=113,176,626 elapsed=269.5s

  [19185/20519] intraday_8666.csv.gz  in=459,982,507 out=113,176,626 elapsed=269.5s

  [19186/20519] intraday_8665.csv.gz  in=459,996,537 out=113,176,626 elapsed=269.5s

  [19187/20519] intraday_8667.csv.gz  in=460,008,425 out=113,176,626 elapsed=269.5s

  [19188/20519] intraday_8668.csv.gz  in=460,022,048 out=113,176,626 elapsed=269.5s

  [19189/20519] intraday_8669.csv.gz  in=460,035,737 out=113,176,626 elapsed=269.5s

  [19190/20519] intraday_8670.csv.gz  in=460,047,419 out=113,176,626 elapsed=269.5s

  [19191/20519] intraday_8671.csv.gz  in=460,059,061 out=113,176,626 elapsed=269.6s

  [19192/20519] intraday_8672.csv.gz  in=460,069,950 out=113,176,626 elapsed=269.6s

  [19193/20519] intraday_8674.csv.gz  in=460,082,241 out=113,176,626 elapsed=269.6s

  [19194/20519] intraday_8675.csv.gz  in=460,095,378 out=113,176,626 elapsed=269.6s

  [19195/20519] intraday_8673.csv.gz  in=460,110,070 out=113,176,626 elapsed=269.6s

  [19196/20519] intraday_8676.csv.gz  in=460,123,706 out=113,176,626 elapsed=269.6s

  [19197/20519] intraday_8677.csv.gz  in=460,136,252 out=113,176,626 elapsed=269.6s

  [19198/20519] intraday_8679.csv.gz  in=460,147,699 out=113,176,626 elapsed=269.6s

  [19199/20519] intraday_8678.csv.gz  in=460,160,633 out=113,176,626 elapsed=269.6s

  [19200/20519] intraday_8680.csv.gz  in=460,172,707 out=113,176,626 elapsed=269.6s

  [19201/20519] intraday_8681.csv.gz  in=460,186,012 out=113,176,626 elapsed=269.7s

  [19202/20519] intraday_8682.csv.gz  in=460,203,132 out=113,176,626 elapsed=269.7s

  [19203/20519] intraday_8683.csv.gz  in=460,217,659 out=113,176,626 elapsed=269.7s

  [19204/20519] intraday_8684.csv.gz  in=460,228,032 out=113,176,626 elapsed=269.7s

  [19205/20519] intraday_8685.csv.gz  in=460,240,220 out=113,176,626 elapsed=269.7s

  [19206/20519] intraday_8686.csv.gz  in=460,253,715 out=113,176,626 elapsed=269.7s

  [19207/20519] intraday_8687.csv.gz  in=460,264,886 out=113,176,626 elapsed=269.7s

  [19208/20519] intraday_8688.csv.gz  in=460,277,186 out=113,176,626 elapsed=269.7s

  [19209/20519] intraday_8689.csv.gz  in=460,287,925 out=113,176,626 elapsed=269.7s

  [19210/20519] intraday_8690.csv.gz  in=460,300,662 out=113,176,626 elapsed=269.7s

  [19211/20519] intraday_8691.csv.gz  in=460,311,303 out=113,176,626 elapsed=269.7s

  [19212/20519] intraday_8692.csv.gz  in=460,323,255 out=113,176,626 elapsed=269.7s

  [19213/20519] intraday_8693.csv.gz  in=460,335,182 out=113,176,626 elapsed=269.8s

  [19214/20519] intraday_8695.csv.gz  in=460,347,215 out=113,176,626 elapsed=269.8s

  [19215/20519] intraday_8694.csv.gz  in=460,360,829 out=113,176,626 elapsed=269.8s

  [19216/20519] intraday_8696.csv.gz  in=460,375,385 out=113,176,626 elapsed=269.8s

  [19217/20519] intraday_8697.csv.gz  in=460,386,253 out=113,176,626 elapsed=269.8s

  [19218/20519] intraday_8698.csv.gz  in=460,398,280 out=113,176,626 elapsed=269.8s

  [19219/20519] intraday_8699.csv.gz  in=460,411,631 out=113,176,626 elapsed=269.9s

  [19220/20519] intraday_8700.csv.gz  in=460,422,997 out=113,176,626 elapsed=269.9s

  [19221/20519] intraday_8703.csv.gz  in=460,433,835 out=113,176,626 elapsed=269.9s

  [19222/20519] intraday_8701.csv.gz  in=460,445,276 out=113,176,626 elapsed=269.9s

  [19223/20519] intraday_8702.csv.gz  in=460,457,475 out=113,176,626 elapsed=269.9s

  [19224/20519] intraday_8704.csv.gz  in=460,472,936 out=113,176,626 elapsed=269.9s

  [19225/20519] intraday_8706.csv.gz  in=460,485,848 out=113,176,626 elapsed=270.0s

  [19226/20519] intraday_8707.csv.gz  in=460,499,048 out=113,176,626 elapsed=270.0s

  [19227/20519] intraday_8705.csv.gz  in=460,510,552 out=113,176,626 elapsed=270.0s

  [19228/20519] intraday_8708.csv.gz  in=460,522,365 out=113,176,626 elapsed=270.0s

  [19229/20519] intraday_8709.csv.gz  in=460,533,068 out=113,176,626 elapsed=270.0s

  [19230/20519] intraday_8711.csv.gz  in=460,546,377 out=113,176,626 elapsed=270.0s

  [19231/20519] intraday_8712.csv.gz  in=460,557,864 out=113,176,626 elapsed=270.0s

  [19232/20519] intraday_8710.csv.gz  in=460,571,637 out=113,176,626 elapsed=270.0s

  [19233/20519] intraday_8713.csv.gz  in=460,584,953 out=113,176,626 elapsed=270.0s

  [19234/20519] intraday_8714.csv.gz  in=460,596,331 out=113,176,626 elapsed=270.0s

  [19235/20519] intraday_8716.csv.gz  in=460,606,991 out=113,176,626 elapsed=270.1s

  [19236/20519] intraday_8715.csv.gz  in=460,619,654 out=113,176,626 elapsed=270.1s

  [19237/20519] intraday_8717.csv.gz  in=460,634,764 out=113,176,626 elapsed=270.1s

  [19238/20519] intraday_8718.csv.gz  in=460,647,735 out=113,176,626 elapsed=270.1s

  [19239/20519] intraday_8721.csv.gz  in=460,659,160 out=113,176,626 elapsed=270.1s

  [19240/20519] intraday_8720.csv.gz  in=460,670,971 out=113,176,626 elapsed=270.1s

  [19241/20519] intraday_8719.csv.gz  in=460,688,726 out=113,176,626 elapsed=270.1s

  [19242/20519] intraday_8722.csv.gz  in=460,699,306 out=113,176,626 elapsed=270.1s

  [19243/20519] intraday_8724.csv.gz  in=460,711,708 out=113,176,626 elapsed=270.1s

  [19244/20519] intraday_8725.csv.gz  in=460,725,812 out=113,176,626 elapsed=270.2s

  [19245/20519] intraday_8723.csv.gz  in=460,738,878 out=113,176,626 elapsed=270.2s

  [19246/20519] intraday_8726.csv.gz  in=460,749,698 out=113,176,626 elapsed=270.2s

  [19247/20519] intraday_8730.csv.gz  in=460,760,051 out=113,176,626 elapsed=270.2s

  [19248/20519] intraday_8728.csv.gz  in=460,771,214 out=113,176,626 elapsed=270.2s

  [19249/20519] intraday_8727.csv.gz  in=460,783,828 out=113,176,626 elapsed=270.2s

  [19250/20519] intraday_8729.csv.gz  in=460,797,854 out=113,176,626 elapsed=270.2s

  [19251/20519] intraday_8731.csv.gz  in=460,809,524 out=113,176,626 elapsed=270.2s

  [19252/20519] intraday_8732.csv.gz  in=460,820,726 out=113,176,626 elapsed=270.2s

  [19253/20519] intraday_8733.csv.gz  in=460,831,128 out=113,176,626 elapsed=270.2s

  [19254/20519] intraday_8734.csv.gz  in=460,842,226 out=113,176,626 elapsed=270.2s

  [19255/20519] intraday_8737.csv.gz  in=460,855,468 out=113,176,626 elapsed=270.3s

  [19256/20519] intraday_8738.csv.gz  in=460,866,805 out=113,176,626 elapsed=270.3s

  [19257/20519] intraday_8736.csv.gz  in=460,882,892 out=113,176,626 elapsed=270.3s

  [19258/20519] intraday_8735.csv.gz  in=460,898,993 out=113,176,626 elapsed=270.3s

  [19259/20519] intraday_8739.csv.gz  in=460,911,629 out=113,176,626 elapsed=270.3s

  [19260/20519] intraday_8741.csv.gz  in=460,923,703 out=113,176,626 elapsed=270.3s

  [19261/20519] intraday_8740.csv.gz  in=460,937,469 out=113,176,626 elapsed=270.3s

  [19262/20519] intraday_8742.csv.gz  in=460,952,452 out=113,176,626 elapsed=270.3s

  [19263/20519] intraday_8745.csv.gz  in=460,965,613 out=113,176,626 elapsed=270.3s

  [19264/20519] intraday_8744.csv.gz  in=460,980,225 out=113,176,626 elapsed=270.3s

  [19265/20519] intraday_8743.csv.gz  in=460,992,409 out=113,176,626 elapsed=270.3s

  [19266/20519] intraday_8747.csv.gz  in=461,006,032 out=113,176,626 elapsed=270.4s

  [19267/20519] intraday_8746.csv.gz  in=461,019,054 out=113,176,626 elapsed=270.4s

  [19268/20519] intraday_8748.csv.gz  in=461,031,156 out=113,176,626 elapsed=270.4s

  [19269/20519] intraday_8749.csv.gz  in=461,049,433 out=113,176,626 elapsed=270.4s

  [19270/20519] intraday_8750.csv.gz  in=461,061,456 out=113,176,626 elapsed=270.4s

  [19271/20519] intraday_8752.csv.gz  in=461,072,898 out=113,176,626 elapsed=270.4s

  [19272/20519] intraday_8751.csv.gz  in=461,085,796 out=113,176,626 elapsed=270.4s

  [19273/20519] intraday_8753.csv.gz  in=461,099,504 out=113,176,626 elapsed=270.4s

  [19274/20519] intraday_8754.csv.gz  in=461,111,812 out=113,176,626 elapsed=270.4s

  [19275/20519] intraday_8756.csv.gz  in=461,123,402 out=113,176,626 elapsed=270.4s

  [19276/20519] intraday_8757.csv.gz  in=461,135,995 out=113,176,626 elapsed=270.5s

  [19277/20519] intraday_8755.csv.gz  in=461,153,298 out=113,176,626 elapsed=270.5s

  [19278/20519] intraday_8759.csv.gz  in=461,165,877 out=113,176,626 elapsed=270.5s

  [19279/20519] intraday_8758.csv.gz  in=461,181,685 out=113,176,626 elapsed=270.5s

  [19280/20519] intraday_8760.csv.gz  in=461,194,237 out=113,176,626 elapsed=270.5s

  [19281/20519] intraday_8761.csv.gz  in=461,209,367 out=113,176,626 elapsed=270.5s

  [19282/20519] intraday_8762.csv.gz  in=461,224,593 out=113,176,626 elapsed=270.5s

  [19283/20519] intraday_8763.csv.gz  in=461,235,512 out=113,176,626 elapsed=270.5s

  [19284/20519] intraday_8764.csv.gz  in=461,248,631 out=113,176,626 elapsed=270.5s

  [19285/20519] intraday_8765.csv.gz  in=461,261,543 out=113,176,626 elapsed=270.5s

  [19286/20519] intraday_8767.csv.gz  in=461,276,858 out=113,176,626 elapsed=270.6s

  [19287/20519] intraday_8766.csv.gz  in=461,289,321 out=113,176,626 elapsed=270.6s

  [19288/20519] intraday_8769.csv.gz  in=461,310,913 out=113,176,626 elapsed=270.6s

  [19289/20519] intraday_8768.csv.gz  in=461,326,521 out=113,176,626 elapsed=270.6s

  [19290/20519] intraday_8771.csv.gz  in=461,340,891 out=113,176,626 elapsed=270.6s

  [19291/20519] intraday_8770.csv.gz  in=461,356,248 out=113,176,626 elapsed=270.6s

  [19292/20519] intraday_8772.csv.gz  in=461,368,851 out=113,176,626 elapsed=270.6s

  [19293/20519] intraday_8773.csv.gz  in=461,381,303 out=113,176,626 elapsed=270.6s

  [19294/20519] intraday_8774.csv.gz  in=461,391,936 out=113,176,626 elapsed=270.6s

  [19295/20519] intraday_8776.csv.gz  in=461,402,983 out=113,176,626 elapsed=270.6s

  [19296/20519] intraday_8775.csv.gz  in=461,417,607 out=113,176,626 elapsed=270.7s

  [19297/20519] intraday_8778.csv.gz  in=461,431,470 out=113,176,626 elapsed=270.7s

  [19298/20519] intraday_8777.csv.gz  in=461,444,268 out=113,176,626 elapsed=270.7s

  [19299/20519] intraday_8779.csv.gz  in=461,458,802 out=113,176,626 elapsed=270.7s

  [19300/20519] intraday_8780.csv.gz  in=461,469,965 out=113,176,626 elapsed=270.7s

  [19301/20519] intraday_8781.csv.gz  in=461,481,811 out=113,176,626 elapsed=270.7s

  [19302/20519] intraday_8782.csv.gz  in=461,493,785 out=113,176,626 elapsed=270.7s

  [19303/20519] intraday_8783.csv.gz  in=461,506,040 out=113,176,626 elapsed=270.7s

  [19304/20519] intraday_8784.csv.gz  in=461,517,628 out=113,176,626 elapsed=270.7s

  [19305/20519] intraday_8785.csv.gz  in=461,531,713 out=113,176,626 elapsed=270.7s

  [19306/20519] intraday_8786.csv.gz  in=461,546,593 out=113,176,626 elapsed=270.7s

  [19307/20519] intraday_8788.csv.gz  in=461,561,344 out=113,176,626 elapsed=270.8s

  [19308/20519] intraday_8789.csv.gz  in=461,573,616 out=113,176,626 elapsed=270.8s

  [19309/20519] intraday_8787.csv.gz  in=461,587,314 out=113,176,626 elapsed=270.8s

  [19310/20519] intraday_8790.csv.gz  in=461,599,183 out=113,176,626 elapsed=270.8s

  [19311/20519] intraday_8791.csv.gz  in=461,613,412 out=113,176,626 elapsed=270.8s

  [19312/20519] intraday_8792.csv.gz  in=461,624,655 out=113,176,626 elapsed=270.8s

  [19313/20519] intraday_8793.csv.gz  in=461,636,288 out=113,176,626 elapsed=270.8s

  [19314/20519] intraday_8794.csv.gz  in=461,642,893 out=113,176,626 elapsed=270.9s

  [19315/20519] intraday_8796.csv.gz  in=461,649,551 out=113,176,626 elapsed=270.9s

  [19316/20519] intraday_8797.csv.gz  in=461,664,943 out=113,176,626 elapsed=270.9s

  [19317/20519] intraday_8798.csv.gz  in=461,676,809 out=113,176,626 elapsed=270.9s

  [19318/20519] intraday_8795.csv.gz  in=461,689,744 out=113,176,626 elapsed=270.9s

  [19319/20519] intraday_8800.csv.gz  in=461,700,142 out=113,176,626 elapsed=270.9s

  [19320/20519] intraday_8801.csv.gz  in=461,712,377 out=113,176,626 elapsed=270.9s

  [19321/20519] intraday_8802.csv.gz  in=461,727,936 out=113,176,626 elapsed=271.0s

  [19322/20519] intraday_8799.csv.gz  in=461,742,274 out=113,176,626 elapsed=271.0s

  [19323/20519] intraday_8803.csv.gz  in=461,756,457 out=113,176,626 elapsed=271.0s

  [19324/20519] intraday_8805.csv.gz  in=461,768,939 out=113,176,626 elapsed=271.0s

  [19325/20519] intraday_8806.csv.gz  in=461,783,671 out=113,176,626 elapsed=271.0s

  [19326/20519] intraday_8804.csv.gz  in=461,795,270 out=113,176,626 elapsed=271.0s

  [19327/20519] intraday_8807.csv.gz  in=461,809,535 out=113,176,626 elapsed=271.0s

  [19328/20519] intraday_8808.csv.gz  in=461,823,461 out=113,176,626 elapsed=271.0s

  [19329/20519] intraday_8809.csv.gz  in=461,836,935 out=113,176,626 elapsed=271.0s

  [19330/20519] intraday_8810.csv.gz  in=461,851,250 out=113,176,626 elapsed=271.0s

  [19331/20519] intraday_8811.csv.gz  in=461,861,144 out=113,176,626 elapsed=271.0s

  [19332/20519] intraday_8812.csv.gz  in=461,872,982 out=113,176,626 elapsed=271.0s

  [19333/20519] intraday_8813.csv.gz  in=461,886,896 out=113,176,626 elapsed=271.0s

  [19334/20519] intraday_8814.csv.gz  in=461,899,141 out=113,176,626 elapsed=271.0s

  [19335/20519] intraday_8815.csv.gz  in=461,911,402 out=113,176,626 elapsed=271.0s

  [19336/20519] intraday_8816.csv.gz  in=461,922,598 out=113,176,626 elapsed=271.1s

  [19337/20519] intraday_8818.csv.gz  in=461,936,735 out=113,176,626 elapsed=271.1s

  [19338/20519] intraday_8817.csv.gz  in=461,948,868 out=113,176,626 elapsed=271.1s

  [19339/20519] intraday_8819.csv.gz  in=461,961,642 out=113,176,626 elapsed=271.1s

  [19340/20519] intraday_8820.csv.gz  in=461,975,278 out=113,176,626 elapsed=271.1s

  [19341/20519] intraday_8821.csv.gz  in=461,988,701 out=113,176,626 elapsed=271.1s

  [19342/20519] intraday_8822.csv.gz  in=462,002,005 out=113,176,626 elapsed=271.1s

  [19343/20519] intraday_8823.csv.gz  in=462,014,399 out=113,176,626 elapsed=271.1s

  [19344/20519] intraday_8824.csv.gz  in=462,026,389 out=113,176,626 elapsed=271.1s

  [19345/20519] intraday_8825.csv.gz  in=462,043,361 out=113,176,626 elapsed=271.1s

  [19346/20519] intraday_8826.csv.gz  in=462,057,413 out=113,176,626 elapsed=271.2s

  [19347/20519] intraday_8827.csv.gz  in=462,073,223 out=113,176,626 elapsed=271.2s

  [19348/20519] intraday_8829.csv.gz  in=462,084,663 out=113,176,626 elapsed=271.2s

  [19349/20519] intraday_8828.csv.gz  in=462,098,205 out=113,176,626 elapsed=271.2s

  [19350/20519] intraday_8830.csv.gz  in=462,110,640 out=113,176,626 elapsed=271.2s

  [19351/20519] intraday_8831.csv.gz  in=462,123,559 out=113,176,626 elapsed=271.2s

  [19352/20519] intraday_8833.csv.gz  in=462,136,426 out=113,176,626 elapsed=271.2s

  [19353/20519] intraday_8832.csv.gz  in=462,147,387 out=113,176,626 elapsed=271.2s

  [19354/20519] intraday_8834.csv.gz  in=462,158,065 out=113,176,626 elapsed=271.2s

  [19355/20519] intraday_8835.csv.gz  in=462,170,331 out=113,176,626 elapsed=271.2s

  [19356/20519] intraday_8837.csv.gz  in=462,182,158 out=113,176,626 elapsed=271.3s

  [19357/20519] intraday_8836.csv.gz  in=462,193,211 out=113,176,626 elapsed=271.3s

  [19358/20519] intraday_8838.csv.gz  in=462,205,561 out=113,176,626 elapsed=271.3s

  [19359/20519] intraday_8839.csv.gz  in=462,219,304 out=113,176,626 elapsed=271.3s

  [19360/20519] intraday_8840.csv.gz  in=462,231,401 out=113,176,626 elapsed=271.3s

  [19361/20519] intraday_8841.csv.gz  in=462,245,179 out=113,176,626 elapsed=271.3s

  [19362/20519] intraday_8842.csv.gz  in=462,256,334 out=113,176,626 elapsed=271.3s

  [19363/20519] intraday_8843.csv.gz  in=462,267,447 out=113,176,626 elapsed=271.3s

  [19364/20519] intraday_8845.csv.gz  in=462,277,958 out=113,176,626 elapsed=271.3s

  [19365/20519] intraday_8844.csv.gz  in=462,291,592 out=113,176,626 elapsed=271.3s

  [19366/20519] intraday_8846.csv.gz  in=462,303,346 out=113,176,626 elapsed=271.3s

  [19367/20519] intraday_8847.csv.gz  in=462,315,383 out=113,176,626 elapsed=271.3s

  [19368/20519] intraday_8848.csv.gz  in=462,326,800 out=113,176,626 elapsed=271.3s

  [19369/20519] intraday_8849.csv.gz  in=462,342,682 out=113,176,626 elapsed=271.3s

  [19370/20519] intraday_8851.csv.gz  in=462,356,069 out=113,176,626 elapsed=271.3s

  [19371/20519] intraday_8850.csv.gz  in=462,369,493 out=113,176,626 elapsed=271.3s

  [19372/20519] intraday_8852.csv.gz  in=462,389,028 out=113,176,626 elapsed=271.3s

  [19373/20519] intraday_8853.csv.gz  in=462,403,106 out=113,176,626 elapsed=271.4s

  [19374/20519] intraday_8854.csv.gz  in=462,414,238 out=113,176,626 elapsed=271.4s

  [19375/20519] intraday_8855.csv.gz  in=462,426,446 out=113,176,626 elapsed=271.4s

  [19376/20519] intraday_8856.csv.gz  in=462,439,144 out=113,176,626 elapsed=271.4s

  [19377/20519] intraday_8857.csv.gz  in=462,451,578 out=113,176,626 elapsed=271.4s

  [19378/20519] intraday_8859.csv.gz  in=462,462,638 out=113,176,626 elapsed=271.4s

  [19379/20519] intraday_8858.csv.gz  in=462,479,599 out=113,176,626 elapsed=271.4s

  [19380/20519] intraday_8860.csv.gz  in=462,492,361 out=113,176,626 elapsed=271.4s

  [19381/20519] intraday_8861.csv.gz  in=462,503,232 out=113,176,626 elapsed=271.4s

  [19382/20519] intraday_8862.csv.gz  in=462,518,609 out=113,176,626 elapsed=271.4s

  [19383/20519] intraday_8863.csv.gz  in=462,530,668 out=113,176,626 elapsed=271.4s

  [19384/20519] intraday_8864.csv.gz  in=462,544,651 out=113,176,626 elapsed=271.5s

  [19385/20519] intraday_8865.csv.gz  in=462,558,281 out=113,176,626 elapsed=271.5s

  [19386/20519] intraday_8866.csv.gz  in=462,569,428 out=113,176,626 elapsed=271.5s

  [19387/20519] intraday_8867.csv.gz  in=462,578,705 out=113,176,626 elapsed=271.5s

  [19388/20519] intraday_8868.csv.gz  in=462,590,701 out=113,176,626 elapsed=271.5s

  [19389/20519] intraday_8869.csv.gz  in=462,603,791 out=113,176,626 elapsed=271.5s

  [19390/20519] intraday_8870.csv.gz  in=462,617,598 out=113,176,626 elapsed=271.5s

  [19391/20519] intraday_8871.csv.gz  in=462,632,131 out=113,176,626 elapsed=271.5s

  [19392/20519] intraday_8872.csv.gz  in=462,644,869 out=113,176,626 elapsed=271.5s

  [19393/20519] intraday_8873.csv.gz  in=462,658,080 out=113,176,626 elapsed=271.6s

  [19394/20519] intraday_8874.csv.gz  in=462,671,737 out=113,176,626 elapsed=271.6s

  [19395/20519] intraday_8875.csv.gz  in=462,682,447 out=113,176,626 elapsed=271.6s

  [19396/20519] intraday_8876.csv.gz  in=462,694,162 out=113,176,626 elapsed=271.6s

  [19397/20519] intraday_8877.csv.gz  in=462,710,202 out=113,176,626 elapsed=271.6s

  [19398/20519] intraday_8878.csv.gz  in=462,721,522 out=113,176,626 elapsed=271.6s

  [19399/20519] intraday_8879.csv.gz  in=462,732,915 out=113,176,626 elapsed=271.6s

  [19400/20519] intraday_8881.csv.gz  in=462,751,259 out=113,176,626 elapsed=271.6s

  [19401/20519] intraday_8880.csv.gz  in=462,764,833 out=113,176,626 elapsed=271.6s

  [19402/20519] intraday_8882.csv.gz  in=462,777,699 out=113,176,626 elapsed=271.6s

  [19403/20519] intraday_8883.csv.gz  in=462,789,349 out=113,176,626 elapsed=271.6s

  [19404/20519] intraday_8884.csv.gz  in=462,801,884 out=113,176,626 elapsed=271.7s

  [19405/20519] intraday_8885.csv.gz  in=462,816,439 out=113,176,626 elapsed=271.7s

  [19406/20519] intraday_8886.csv.gz  in=462,828,976 out=113,176,626 elapsed=271.7s

  [19407/20519] intraday_8887.csv.gz  in=462,844,211 out=113,176,626 elapsed=271.7s

  [19408/20519] intraday_8888.csv.gz  in=462,857,839 out=113,176,626 elapsed=271.7s

  [19409/20519] intraday_8889.csv.gz  in=462,870,705 out=113,176,626 elapsed=271.7s

  [19410/20519] intraday_8890.csv.gz  in=462,883,341 out=113,176,626 elapsed=271.7s

  [19411/20519] intraday_8894.csv.gz  in=462,896,981 out=113,176,626 elapsed=271.7s

  [19412/20519] intraday_8891.csv.gz  in=462,910,330 out=113,176,626 elapsed=271.7s

  [19413/20519] intraday_8893.csv.gz  in=462,923,680 out=113,176,626 elapsed=271.8s

  [19414/20519] intraday_8892.csv.gz  in=462,938,085 out=113,176,626 elapsed=271.8s

  [19415/20519] intraday_8895.csv.gz  in=462,949,190 out=113,176,626 elapsed=271.8s

  [19416/20519] intraday_8897.csv.gz  in=462,962,549 out=113,176,626 elapsed=271.8s

  [19417/20519] intraday_8898.csv.gz  in=462,973,971 out=113,176,626 elapsed=271.8s

  [19418/20519] intraday_8896.csv.gz  in=462,998,945 out=113,176,626 elapsed=271.8s

  [19419/20519] intraday_8899.csv.gz  in=463,013,743 out=113,176,626 elapsed=271.8s

  [19420/20519] intraday_8900.csv.gz  in=463,027,118 out=113,176,626 elapsed=271.8s

  [19421/20519] intraday_8902.csv.gz  in=463,039,357 out=113,176,626 elapsed=271.8s

  [19422/20519] intraday_8901.csv.gz  in=463,053,296 out=113,176,626 elapsed=271.8s

  [19423/20519] intraday_8903.csv.gz  in=463,066,897 out=113,176,626 elapsed=271.9s

  [19424/20519] intraday_8905.csv.gz  in=463,079,289 out=113,176,626 elapsed=271.9s

  [19425/20519] intraday_8904.csv.gz  in=463,092,520 out=113,176,626 elapsed=271.9s

  [19426/20519] intraday_8906.csv.gz  in=463,108,006 out=113,176,626 elapsed=271.9s

  [19427/20519] intraday_8908.csv.gz  in=463,119,785 out=113,176,626 elapsed=271.9s

  [19428/20519] intraday_8907.csv.gz  in=463,134,765 out=113,176,626 elapsed=271.9s

  [19429/20519] intraday_8910.csv.gz  in=463,149,264 out=113,176,626 elapsed=271.9s

  [19430/20519] intraday_8909.csv.gz  in=463,161,444 out=113,176,626 elapsed=271.9s

  [19431/20519] intraday_8911.csv.gz  in=463,172,795 out=113,176,626 elapsed=271.9s

  [19432/20519] intraday_8912.csv.gz  in=463,188,036 out=113,176,626 elapsed=272.0s

  [19433/20519] intraday_8914.csv.gz  in=463,210,795 out=113,176,626 elapsed=272.0s

  [19434/20519] intraday_8913.csv.gz  in=463,227,065 out=113,176,626 elapsed=272.0s

  [19435/20519] intraday_8915.csv.gz  in=463,240,616 out=113,176,626 elapsed=272.0s

  [19436/20519] intraday_8917.csv.gz  in=463,252,465 out=113,176,626 elapsed=272.0s

  [19437/20519] intraday_8918.csv.gz  in=463,265,826 out=113,176,626 elapsed=272.0s

  [19438/20519] intraday_8916.csv.gz  in=463,282,560 out=113,176,626 elapsed=272.0s

  [19439/20519] intraday_8919.csv.gz  in=463,293,871 out=113,176,626 elapsed=272.0s

  [19440/20519] intraday_8920.csv.gz  in=463,307,184 out=113,176,626 elapsed=272.0s

  [19441/20519] intraday_8921.csv.gz  in=463,318,341 out=113,176,626 elapsed=272.0s

  [19442/20519] intraday_8922.csv.gz  in=463,332,054 out=113,176,626 elapsed=272.0s

  [19443/20519] intraday_8923.csv.gz  in=463,344,480 out=113,176,626 elapsed=272.0s

  [19444/20519] intraday_8924.csv.gz  in=463,360,480 out=113,176,626 elapsed=272.0s

  [19445/20519] intraday_8925.csv.gz  in=463,371,429 out=113,176,626 elapsed=272.0s

  [19446/20519] intraday_8926.csv.gz  in=463,383,975 out=113,176,626 elapsed=272.0s

  [19447/20519] intraday_8927.csv.gz  in=463,394,872 out=113,176,626 elapsed=272.0s

  [19448/20519] intraday_8928.csv.gz  in=463,408,039 out=113,176,626 elapsed=272.0s

  [19449/20519] intraday_8929.csv.gz  in=463,420,013 out=113,176,626 elapsed=272.0s

  [19450/20519] intraday_8930.csv.gz  in=463,434,170 out=113,176,626 elapsed=272.0s

  [19451/20519] intraday_8931.csv.gz  in=463,448,669 out=113,176,626 elapsed=272.0s

  [19452/20519] intraday_8932.csv.gz  in=463,462,013 out=113,176,626 elapsed=272.1s

  [19453/20519] intraday_8933.csv.gz  in=463,476,556 out=113,176,626 elapsed=272.1s

  [19454/20519] intraday_8934.csv.gz  in=463,489,452 out=113,176,626 elapsed=272.1s

  [19455/20519] intraday_8935.csv.gz  in=463,501,285 out=113,176,626 elapsed=272.1s

  [19456/20519] intraday_8936.csv.gz  in=463,514,382 out=113,176,626 elapsed=272.1s

  [19457/20519] intraday_8939.csv.gz  in=463,521,788 out=113,176,626 elapsed=272.1s

  [19458/20519] intraday_8938.csv.gz  in=463,535,538 out=113,176,626 elapsed=272.1s

  [19459/20519] intraday_8937.csv.gz  in=463,546,144 out=113,176,626 elapsed=272.1s

  [19460/20519] intraday_8940.csv.gz  in=463,556,945 out=113,176,626 elapsed=272.1s

  [19461/20519] intraday_8942.csv.gz  in=463,559,604 out=113,176,626 elapsed=272.1s

  [19462/20519] intraday_8941.csv.gz  in=463,570,175 out=113,176,626 elapsed=272.1s

  [19463/20519] intraday_8943.csv.gz  in=463,572,472 out=113,176,626 elapsed=272.1s

  [19464/20519] intraday_8945.csv.gz  in=463,572,760 out=113,176,626 elapsed=272.1s

  [19465/20519] intraday_8944.csv.gz  in=463,573,633 out=113,176,626 elapsed=272.1s

  [19466/20519] intraday_8946.csv.gz  in=463,573,804 out=113,176,626 elapsed=272.2s

  [19467/20519] intraday_8948.csv.gz  in=463,573,881 out=113,176,626 elapsed=272.2s

  [19468/20519] intraday_8949.csv.gz  in=463,573,950 out=113,176,626 elapsed=272.2s

  [19469/20519] intraday_8947.csv.gz  in=463,580,461 out=113,176,626 elapsed=272.2s

  [19470/20519] intraday_8950.csv.gz  in=463,580,901 out=113,176,626 elapsed=272.2s

  [19471/20519] intraday_8953.csv.gz  in=463,581,142 out=113,176,626 elapsed=272.2s

  [19472/20519] intraday_8951.csv.gz  in=463,595,099 out=113,176,626 elapsed=272.2s

  [19473/20519] intraday_8952.csv.gz  in=463,595,439 out=113,176,626 elapsed=272.2s

  [19474/20519] intraday_8954.csv.gz  in=463,595,449 out=113,176,626 elapsed=272.2s

  [19475/20519] intraday_8955.csv.gz  in=463,596,293 out=113,176,626 elapsed=272.2s

  [19476/20519] intraday_8957.csv.gz  in=463,596,312 out=113,176,626 elapsed=272.2s

  [19477/20519] intraday_8956.csv.gz  in=463,596,380 out=113,176,626 elapsed=272.2s

  [19478/20519] intraday_8958.csv.gz  in=463,596,418 out=113,176,626 elapsed=272.2s

  [19479/20519] intraday_8959.csv.gz  in=463,598,443 out=113,176,626 elapsed=272.2s

  [19480/20519] intraday_8962.csv.gz  in=463,603,208 out=113,176,626 elapsed=272.3s

  [19481/20519] intraday_8960.csv.gz  in=463,606,738 out=113,176,626 elapsed=272.3s

  [19482/20519] intraday_8961.csv.gz  in=463,607,249 out=113,176,626 elapsed=272.3s

  [19483/20519] intraday_8963.csv.gz  in=463,607,454 out=113,176,626 elapsed=272.3s

  [19484/20519] intraday_8964.csv.gz  in=463,607,467 out=113,176,626 elapsed=272.3s

  [19485/20519] intraday_8966.csv.gz  in=463,607,772 out=113,176,626 elapsed=272.3s

  [19486/20519] intraday_8965.csv.gz  in=463,611,534 out=113,176,626 elapsed=272.3s

  [19487/20519] intraday_8969.csv.gz  in=463,611,565 out=113,176,626 elapsed=272.3s

  [19488/20519] intraday_8968.csv.gz  in=463,611,828 out=113,176,626 elapsed=272.3s

  [19489/20519] intraday_8967.csv.gz  in=463,614,934 out=113,176,626 elapsed=272.3s

  [19490/20519] intraday_8970.csv.gz  in=463,619,717 out=113,176,626 elapsed=272.3s

  [19491/20519] intraday_8972.csv.gz  in=463,621,615 out=113,176,626 elapsed=272.3s

  [19492/20519] intraday_8974.csv.gz  in=463,633,358 out=113,176,626 elapsed=272.4s

  [19493/20519] intraday_8973.csv.gz  in=463,648,699 out=113,176,626 elapsed=272.4s

  [19494/20519] intraday_8971.csv.gz  in=463,679,767 out=113,176,626 elapsed=272.4s

  [19495/20519] intraday_8975.csv.gz  in=463,693,564 out=113,176,626 elapsed=272.4s

  [19496/20519] intraday_8976.csv.gz  in=463,704,246 out=113,176,626 elapsed=272.4s

  [19497/20519] intraday_8977.csv.gz  in=463,717,580 out=113,176,626 elapsed=272.4s

  [19498/20519] intraday_8978.csv.gz  in=463,731,742 out=113,176,626 elapsed=272.4s

  [19499/20519] intraday_8979.csv.gz  in=463,746,873 out=113,176,626 elapsed=272.4s

  [19500/20519] intraday_8980.csv.gz  in=463,759,399 out=113,176,626 elapsed=272.4s

  [19501/20519] intraday_8981.csv.gz  in=463,772,144 out=113,176,626 elapsed=272.4s

  [19502/20519] intraday_8984.csv.gz  in=463,785,242 out=113,176,626 elapsed=272.5s

  [19503/20519] intraday_8982.csv.gz  in=463,799,074 out=113,176,626 elapsed=272.5s

  [19504/20519] intraday_8983.csv.gz  in=463,813,568 out=113,176,626 elapsed=272.5s

  [19505/20519] intraday_8985.csv.gz  in=463,829,282 out=113,176,626 elapsed=272.5s

  [19506/20519] intraday_8987.csv.gz  in=463,839,131 out=113,176,626 elapsed=272.5s

  [19507/20519] intraday_8988.csv.gz  in=463,850,821 out=113,176,626 elapsed=272.5s

  [19508/20519] intraday_8986.csv.gz  in=463,862,815 out=113,176,626 elapsed=272.5s

  [19509/20519] intraday_8989.csv.gz  in=463,876,102 out=113,176,626 elapsed=272.5s

  [19510/20519] intraday_8990.csv.gz  in=463,889,098 out=113,176,626 elapsed=272.5s

  [19511/20519] intraday_8991.csv.gz  in=463,899,715 out=113,176,626 elapsed=272.5s

  [19512/20519] intraday_8992.csv.gz  in=463,911,405 out=113,176,626 elapsed=272.6s

  [19513/20519] intraday_8993.csv.gz  in=463,922,829 out=113,176,626 elapsed=272.6s

  [19514/20519] intraday_8994.csv.gz  in=463,935,783 out=113,176,626 elapsed=272.6s

  [19515/20519] intraday_8995.csv.gz  in=463,949,587 out=113,176,626 elapsed=272.6s

  [19516/20519] intraday_8997.csv.gz  in=463,963,781 out=113,176,626 elapsed=272.6s

  [19517/20519] intraday_8996.csv.gz  in=463,976,519 out=113,176,626 elapsed=272.6s

  [19518/20519] intraday_8999.csv.gz  in=463,988,302 out=113,176,626 elapsed=272.6s

  [19519/20519] intraday_8998.csv.gz  in=464,001,271 out=113,176,626 elapsed=272.6s

  [19520/20519] intraday_9000.csv.gz  in=464,012,925 out=113,176,626 elapsed=272.6s

  [19521/20519] intraday_9001.csv.gz  in=464,024,802 out=113,176,626 elapsed=272.6s

  [19522/20519] intraday_9002.csv.gz  in=464,037,476 out=113,176,626 elapsed=272.7s

  [19523/20519] intraday_9004.csv.gz  in=464,050,733 out=113,176,626 elapsed=272.7s

  [19524/20519] intraday_9003.csv.gz  in=464,066,873 out=113,176,626 elapsed=272.7s

  [19525/20519] intraday_9005.csv.gz  in=464,077,802 out=113,176,626 elapsed=272.7s

  [19526/20519] intraday_9007.csv.gz  in=464,090,278 out=113,176,626 elapsed=272.7s

  [19527/20519] intraday_9006.csv.gz  in=464,101,822 out=113,176,626 elapsed=272.7s

  [19528/20519] intraday_9008.csv.gz  in=464,114,265 out=113,176,626 elapsed=272.7s

  [19529/20519] intraday_9009.csv.gz  in=464,126,318 out=113,176,626 elapsed=272.7s

  [19530/20519] intraday_9011.csv.gz  in=464,137,802 out=113,176,626 elapsed=272.7s

  [19531/20519] intraday_9010.csv.gz  in=464,148,933 out=113,176,626 elapsed=272.7s

  [19532/20519] intraday_9012.csv.gz  in=464,159,789 out=113,176,626 elapsed=272.8s

  [19533/20519] intraday_9013.csv.gz  in=464,172,008 out=113,176,626 elapsed=272.8s

  [19534/20519] intraday_9014.csv.gz  in=464,184,346 out=113,176,626 elapsed=272.8s

  [19535/20519] intraday_9015.csv.gz  in=464,196,247 out=113,176,626 elapsed=272.8s

  [19536/20519] intraday_9016.csv.gz  in=464,208,994 out=113,176,626 elapsed=272.8s

  [19537/20519] intraday_9018.csv.gz  in=464,219,392 out=113,176,626 elapsed=272.8s

  [19538/20519] intraday_9017.csv.gz  in=464,233,780 out=113,176,626 elapsed=272.8s

  [19539/20519] intraday_9019.csv.gz  in=464,245,854 out=113,176,626 elapsed=272.9s

  [19540/20519] intraday_9020.csv.gz  in=464,258,373 out=113,176,626 elapsed=272.9s

  [19541/20519] intraday_9021.csv.gz  in=464,269,823 out=113,176,626 elapsed=272.9s

  [19542/20519] intraday_9022.csv.gz  in=464,282,061 out=113,176,626 elapsed=272.9s

  [19543/20519] intraday_9023.csv.gz  in=464,295,177 out=113,176,626 elapsed=272.9s

  [19544/20519] intraday_9024.csv.gz  in=464,305,200 out=113,176,626 elapsed=272.9s

  [19545/20519] intraday_9025.csv.gz  in=464,320,685 out=113,176,626 elapsed=272.9s

  [19546/20519] intraday_9027.csv.gz  in=464,333,514 out=113,176,626 elapsed=272.9s

  [19547/20519] intraday_9029.csv.gz  in=464,345,761 out=113,176,626 elapsed=273.0s

  [19548/20519] intraday_9026.csv.gz  in=464,357,134 out=113,176,626 elapsed=273.0s

  [19549/20519] intraday_9028.csv.gz  in=464,371,439 out=113,176,626 elapsed=273.0s

  [19550/20519] intraday_9030.csv.gz  in=464,382,258 out=113,176,626 elapsed=273.0s

  [19551/20519] intraday_9031.csv.gz  in=464,392,935 out=113,176,626 elapsed=273.0s

  [19552/20519] intraday_9033.csv.gz  in=464,406,010 out=113,176,626 elapsed=273.0s

  [19553/20519] intraday_9032.csv.gz  in=464,418,854 out=113,176,626 elapsed=273.0s

  [19554/20519] intraday_9034.csv.gz  in=464,429,985 out=113,176,626 elapsed=273.0s

  [19555/20519] intraday_9035.csv.gz  in=464,442,940 out=113,176,626 elapsed=273.0s

  [19556/20519] intraday_9037.csv.gz  in=464,453,117 out=113,176,626 elapsed=273.0s

  [19557/20519] intraday_9036.csv.gz  in=464,465,924 out=113,176,626 elapsed=273.0s

  [19558/20519] intraday_9039.csv.gz  in=464,480,702 out=113,176,626 elapsed=273.1s

  [19559/20519] intraday_9038.csv.gz  in=464,494,703 out=113,176,626 elapsed=273.1s

  [19560/20519] intraday_9040.csv.gz  in=464,506,401 out=113,176,626 elapsed=273.1s

  [19561/20519] intraday_9042.csv.gz  in=464,517,961 out=113,176,626 elapsed=273.1s

  [19562/20519] intraday_9041.csv.gz  in=464,531,255 out=113,176,626 elapsed=273.1s

  [19563/20519] intraday_9043.csv.gz  in=464,540,618 out=113,176,626 elapsed=273.1s

  [19564/20519] intraday_9044.csv.gz  in=464,553,543 out=113,176,626 elapsed=273.1s

  [19565/20519] intraday_9046.csv.gz  in=464,566,499 out=113,176,626 elapsed=273.1s

  [19566/20519] intraday_9047.csv.gz  in=464,579,006 out=113,176,626 elapsed=273.1s

  [19567/20519] intraday_9045.csv.gz  in=464,591,518 out=113,176,626 elapsed=273.1s

  [19568/20519] intraday_9049.csv.gz  in=464,602,821 out=113,176,626 elapsed=273.2s

  [19569/20519] intraday_9048.csv.gz  in=464,615,905 out=113,176,626 elapsed=273.2s

  [19570/20519] intraday_9050.csv.gz  in=464,628,626 out=113,176,626 elapsed=273.2s

  [19571/20519] intraday_9052.csv.gz  in=464,638,924 out=113,176,626 elapsed=273.2s

  [19572/20519] intraday_9051.csv.gz  in=464,651,785 out=113,176,626 elapsed=273.2s

  [19573/20519] intraday_9053.csv.gz  in=464,663,914 out=113,176,626 elapsed=273.2s

  [19574/20519] intraday_9054.csv.gz  in=464,672,822 out=113,176,626 elapsed=273.2s

  [19575/20519] intraday_9055.csv.gz  in=464,684,386 out=113,176,626 elapsed=273.2s

  [19576/20519] intraday_9056.csv.gz  in=464,696,582 out=113,176,626 elapsed=273.3s

  [19577/20519] intraday_9057.csv.gz  in=464,712,705 out=113,176,626 elapsed=273.3s

  [19578/20519] intraday_9058.csv.gz  in=464,728,004 out=113,176,626 elapsed=273.3s

  [19579/20519] intraday_9059.csv.gz  in=464,739,073 out=113,176,626 elapsed=273.3s

  [19580/20519] intraday_9060.csv.gz  in=464,751,605 out=113,176,626 elapsed=273.3s

  [19581/20519] intraday_9062.csv.gz  in=464,763,660 out=113,176,626 elapsed=273.3s

  [19582/20519] intraday_9061.csv.gz  in=464,777,411 out=113,176,626 elapsed=273.3s

  [19583/20519] intraday_9063.csv.gz  in=464,791,862 out=113,176,626 elapsed=273.3s

  [19584/20519] intraday_9064.csv.gz  in=464,805,547 out=113,176,626 elapsed=273.3s

  [19585/20519] intraday_9065.csv.gz  in=464,817,376 out=113,176,626 elapsed=273.3s

  [19586/20519] intraday_9067.csv.gz  in=464,830,353 out=113,176,626 elapsed=273.4s

  [19587/20519] intraday_9066.csv.gz  in=464,845,018 out=113,176,626 elapsed=273.4s

  [19588/20519] intraday_9068.csv.gz  in=464,857,828 out=113,176,626 elapsed=273.4s

  [19589/20519] intraday_9069.csv.gz  in=464,870,892 out=113,176,626 elapsed=273.4s

  [19590/20519] intraday_9071.csv.gz  in=464,883,190 out=113,176,626 elapsed=273.4s

  [19591/20519] intraday_9070.csv.gz  in=464,894,913 out=113,176,626 elapsed=273.4s

  [19592/20519] intraday_9072.csv.gz  in=464,908,645 out=113,176,626 elapsed=273.4s

  [19593/20519] intraday_9073.csv.gz  in=464,920,231 out=113,176,626 elapsed=273.4s

  [19594/20519] intraday_9074.csv.gz  in=464,931,313 out=113,176,626 elapsed=273.4s

  [19595/20519] intraday_9075.csv.gz  in=464,943,806 out=113,176,626 elapsed=273.4s

  [19596/20519] intraday_9076.csv.gz  in=464,959,433 out=113,176,626 elapsed=273.4s

  [19597/20519] intraday_9077.csv.gz  in=464,973,256 out=113,176,626 elapsed=273.5s

  [19598/20519] intraday_9079.csv.gz  in=464,985,555 out=113,176,626 elapsed=273.5s

  [19599/20519] intraday_9078.csv.gz  in=464,997,697 out=113,176,626 elapsed=273.5s

  [19600/20519] intraday_9080.csv.gz  in=465,013,792 out=113,176,626 elapsed=273.5s

  [19601/20519] intraday_9082.csv.gz  in=465,026,937 out=113,176,626 elapsed=273.5s

  [19602/20519] intraday_9083.csv.gz  in=465,041,723 out=113,176,626 elapsed=273.5s

  [19603/20519] intraday_9081.csv.gz  in=465,053,315 out=113,176,626 elapsed=273.5s

  [19604/20519] intraday_9084.csv.gz  in=465,066,583 out=113,176,626 elapsed=273.5s

  [19605/20519] intraday_9085.csv.gz  in=465,076,644 out=113,176,626 elapsed=273.5s

  [19606/20519] intraday_9087.csv.gz  in=465,088,470 out=113,176,626 elapsed=273.5s

  [19607/20519] intraday_9086.csv.gz  in=465,102,019 out=113,176,626 elapsed=273.6s

  [19608/20519] intraday_9088.csv.gz  in=465,114,433 out=113,176,626 elapsed=273.6s

  [19609/20519] intraday_9089.csv.gz  in=465,132,814 out=113,176,626 elapsed=273.6s

  [19610/20519] intraday_9090.csv.gz  in=465,146,188 out=113,176,626 elapsed=273.6s

  [19611/20519] intraday_9092.csv.gz  in=465,162,302 out=113,176,626 elapsed=273.6s

  [19612/20519] intraday_9093.csv.gz  in=465,175,335 out=113,176,626 elapsed=273.6s

  [19613/20519] intraday_9091.csv.gz  in=465,195,849 out=113,176,626 elapsed=273.6s

  [19614/20519] intraday_9095.csv.gz  in=465,208,786 out=113,176,626 elapsed=273.6s

  [19615/20519] intraday_9096.csv.gz  in=465,219,318 out=113,176,626 elapsed=273.6s

  [19616/20519] intraday_9094.csv.gz  in=465,231,707 out=113,176,626 elapsed=273.6s

  [19617/20519] intraday_9097.csv.gz  in=465,245,283 out=113,176,626 elapsed=273.6s

  [19618/20519] intraday_9098.csv.gz  in=465,255,175 out=113,176,626 elapsed=273.7s

  [19619/20519] intraday_9100.csv.gz  in=465,268,229 out=113,176,626 elapsed=273.7s

  [19620/20519] intraday_9101.csv.gz  in=465,283,350 out=113,176,626 elapsed=273.7s

  [19621/20519] intraday_9099.csv.gz  in=465,298,238 out=113,176,626 elapsed=273.7s

  [19622/20519] intraday_9102.csv.gz  in=465,309,377 out=113,176,626 elapsed=273.7s

  [19623/20519] intraday_9103.csv.gz  in=465,321,514 out=113,176,626 elapsed=273.7s

  [19624/20519] intraday_9104.csv.gz  in=465,334,235 out=113,176,626 elapsed=273.7s

  [19625/20519] intraday_9105.csv.gz  in=465,345,622 out=113,176,626 elapsed=273.7s

  [19626/20519] intraday_9106.csv.gz  in=465,357,942 out=113,176,626 elapsed=273.7s

  [19627/20519] intraday_9109.csv.gz  in=465,370,807 out=113,176,626 elapsed=273.8s

  [19628/20519] intraday_9108.csv.gz  in=465,386,434 out=113,176,626 elapsed=273.8s

  [19629/20519] intraday_9107.csv.gz  in=465,400,518 out=113,176,626 elapsed=273.8s

  [19630/20519] intraday_9110.csv.gz  in=465,414,589 out=113,176,626 elapsed=273.8s

  [19631/20519] intraday_9112.csv.gz  in=465,428,329 out=113,176,626 elapsed=273.8s

  [19632/20519] intraday_9111.csv.gz  in=465,440,983 out=113,176,626 elapsed=273.8s

  [19633/20519] intraday_9113.csv.gz  in=465,454,100 out=113,176,626 elapsed=273.8s

  [19634/20519] intraday_9114.csv.gz  in=465,465,037 out=113,176,626 elapsed=273.8s

  [19635/20519] intraday_9116.csv.gz  in=465,472,232 out=113,176,626 elapsed=273.9s

  [19636/20519] intraday_9115.csv.gz  in=465,483,797 out=113,176,626 elapsed=273.9s

  [19637/20519] intraday_9117.csv.gz  in=465,495,001 out=113,176,626 elapsed=273.9s

  [19638/20519] intraday_9118.csv.gz  in=465,500,773 out=113,176,626 elapsed=273.9s

  [19639/20519] intraday_9120.csv.gz  in=465,516,691 out=113,176,626 elapsed=273.9s

  [19640/20519] intraday_9119.csv.gz  in=465,541,963 out=113,176,626 elapsed=273.9s

  [19641/20519] intraday_9122.csv.gz  in=465,555,229 out=113,176,626 elapsed=274.0s

  [19642/20519] intraday_9121.csv.gz  in=465,567,565 out=113,176,626 elapsed=274.0s

  [19643/20519] intraday_9123.csv.gz  in=465,577,476 out=113,176,626 elapsed=274.0s

  [19644/20519] intraday_9126.csv.gz  in=465,592,543 out=113,176,626 elapsed=274.0s

  [19645/20519] intraday_9124.csv.gz  in=465,605,053 out=113,176,626 elapsed=274.0s

  [19646/20519] intraday_9128.csv.gz  in=465,617,647 out=113,176,626 elapsed=274.0s

  [19647/20519] intraday_9125.csv.gz  in=465,633,124 out=113,176,626 elapsed=274.0s

  [19648/20519] intraday_9127.csv.gz  in=465,645,106 out=113,176,626 elapsed=274.0s

  [19649/20519] intraday_9129.csv.gz  in=465,659,815 out=113,176,626 elapsed=274.1s

  [19650/20519] intraday_9130.csv.gz  in=465,674,769 out=113,176,626 elapsed=274.1s

  [19651/20519] intraday_9131.csv.gz  in=465,687,263 out=113,176,626 elapsed=274.1s

  [19652/20519] intraday_9132.csv.gz  in=465,701,288 out=113,176,626 elapsed=274.1s

  [19653/20519] intraday_9133.csv.gz  in=465,715,686 out=113,176,626 elapsed=274.1s

  [19654/20519] intraday_9134.csv.gz  in=465,724,917 out=113,176,626 elapsed=274.1s

  [19655/20519] intraday_9136.csv.gz  in=465,739,426 out=113,176,626 elapsed=274.1s

  [19656/20519] intraday_9137.csv.gz  in=465,752,533 out=113,176,626 elapsed=274.1s

  [19657/20519] intraday_9138.csv.gz  in=465,764,672 out=113,176,626 elapsed=274.1s

  [19658/20519] intraday_9135.csv.gz  in=465,776,527 out=113,176,626 elapsed=274.1s

  [19659/20519] intraday_9140.csv.gz  in=465,787,915 out=113,176,626 elapsed=274.2s

  [19660/20519] intraday_9139.csv.gz  in=465,798,318 out=113,176,626 elapsed=274.2s

  [19661/20519] intraday_9142.csv.gz  in=465,810,977 out=113,176,626 elapsed=274.2s

  [19662/20519] intraday_9141.csv.gz  in=465,824,589 out=113,176,626 elapsed=274.2s

  [19663/20519] intraday_9143.csv.gz  in=465,838,393 out=113,176,626 elapsed=274.2s

  [19664/20519] intraday_9145.csv.gz  in=465,851,064 out=113,176,626 elapsed=274.2s

  [19665/20519] intraday_9146.csv.gz  in=465,863,830 out=113,176,626 elapsed=274.2s

  [19666/20519] intraday_9147.csv.gz  in=465,875,737 out=113,176,626 elapsed=274.2s

  [19667/20519] intraday_9144.csv.gz  in=465,891,395 out=113,176,626 elapsed=274.2s

  [19668/20519] intraday_9148.csv.gz  in=465,902,474 out=113,176,626 elapsed=274.2s

  [19669/20519] intraday_9149.csv.gz  in=465,915,723 out=113,176,626 elapsed=274.3s

  [19670/20519] intraday_9150.csv.gz  in=465,932,311 out=113,176,626 elapsed=274.3s

  [19671/20519] intraday_9151.csv.gz  in=465,947,390 out=113,176,626 elapsed=274.3s

  [19672/20519] intraday_9152.csv.gz  in=465,957,062 out=113,176,626 elapsed=274.3s

  [19673/20519] intraday_9153.csv.gz  in=465,969,106 out=113,176,626 elapsed=274.3s

  [19674/20519] intraday_9155.csv.gz  in=465,983,632 out=113,176,626 elapsed=274.3s

  [19675/20519] intraday_9154.csv.gz  in=465,996,201 out=113,176,626 elapsed=274.3s

  [19676/20519] intraday_9156.csv.gz  in=466,007,390 out=113,176,626 elapsed=274.3s

  [19677/20519] intraday_9157.csv.gz  in=466,019,469 out=113,176,626 elapsed=274.3s

  [19678/20519] intraday_9159.csv.gz  in=466,030,037 out=113,176,626 elapsed=274.3s

  [19679/20519] intraday_9158.csv.gz  in=466,046,588 out=113,176,626 elapsed=274.3s

  [19680/20519] intraday_9161.csv.gz  in=466,060,100 out=113,176,626 elapsed=274.4s

  [19681/20519] intraday_9160.csv.gz  in=466,073,430 out=113,176,626 elapsed=274.4s

  [19682/20519] intraday_9162.csv.gz  in=466,084,964 out=113,176,626 elapsed=274.4s

  [19683/20519] intraday_9163.csv.gz  in=466,097,757 out=113,176,626 elapsed=274.4s

  [19684/20519] intraday_9164.csv.gz  in=466,111,818 out=113,176,626 elapsed=274.4s

  [19685/20519] intraday_9165.csv.gz  in=466,124,399 out=113,176,626 elapsed=274.4s

  [19686/20519] intraday_9167.csv.gz  in=466,135,500 out=113,176,626 elapsed=274.4s

  [19687/20519] intraday_9166.csv.gz  in=466,148,238 out=113,176,626 elapsed=274.4s

  [19688/20519] intraday_9168.csv.gz  in=466,160,772 out=113,176,626 elapsed=274.4s

  [19689/20519] intraday_9170.csv.gz  in=466,172,718 out=113,176,626 elapsed=274.5s

  [19690/20519] intraday_9171.csv.gz  in=466,183,743 out=113,176,626 elapsed=274.5s

  [19691/20519] intraday_9169.csv.gz  in=466,196,358 out=113,176,626 elapsed=274.5s

  [19692/20519] intraday_9172.csv.gz  in=466,209,407 out=113,176,626 elapsed=274.5s

  [19693/20519] intraday_9173.csv.gz  in=466,224,183 out=113,176,626 elapsed=274.5s

  [19694/20519] intraday_9175.csv.gz  in=466,237,402 out=113,176,626 elapsed=274.5s

  [19695/20519] intraday_9174.csv.gz  in=466,251,094 out=113,176,626 elapsed=274.5s

  [19696/20519] intraday_9176.csv.gz  in=466,263,777 out=113,176,626 elapsed=274.5s

  [19697/20519] intraday_9177.csv.gz  in=466,275,640 out=113,176,626 elapsed=274.5s

  [19698/20519] intraday_9178.csv.gz  in=466,285,152 out=113,176,626 elapsed=274.5s

  [19699/20519] intraday_9179.csv.gz  in=466,298,535 out=113,176,626 elapsed=274.5s

  [19700/20519] intraday_9182.csv.gz  in=466,312,188 out=113,176,626 elapsed=274.6s

  [19701/20519] intraday_9180.csv.gz  in=466,325,891 out=113,176,626 elapsed=274.6s

  [19702/20519] intraday_9181.csv.gz  in=466,338,221 out=113,176,626 elapsed=274.6s

  [19703/20519] intraday_9183.csv.gz  in=466,349,938 out=113,176,626 elapsed=274.6s

  [19704/20519] intraday_9184.csv.gz  in=466,360,349 out=113,176,626 elapsed=274.6s

  [19705/20519] intraday_9187.csv.gz  in=466,372,092 out=113,176,626 elapsed=274.6s

  [19706/20519] intraday_9185.csv.gz  in=466,385,567 out=113,176,626 elapsed=274.6s

  [19707/20519] intraday_9186.csv.gz  in=466,400,505 out=113,176,626 elapsed=274.6s

  [19708/20519] intraday_9188.csv.gz  in=466,414,572 out=113,176,626 elapsed=274.6s

  [19709/20519] intraday_9191.csv.gz  in=466,426,345 out=113,176,626 elapsed=274.6s

  [19710/20519] intraday_9189.csv.gz  in=466,438,628 out=113,176,626 elapsed=274.6s

  [19711/20519] intraday_9190.csv.gz  in=466,449,559 out=113,176,626 elapsed=274.7s

  [19712/20519] intraday_9192.csv.gz  in=466,463,183 out=113,176,626 elapsed=274.7s

  [19713/20519] intraday_9193.csv.gz  in=466,474,617 out=113,176,626 elapsed=274.7s

  [19714/20519] intraday_9194.csv.gz  in=466,488,207 out=113,176,626 elapsed=274.7s

  [19715/20519] intraday_9195.csv.gz  in=466,499,959 out=113,176,626 elapsed=274.7s

  [19716/20519] intraday_9197.csv.gz  in=466,511,228 out=113,176,626 elapsed=274.7s

  [19717/20519] intraday_9196.csv.gz  in=466,523,605 out=113,176,626 elapsed=274.7s

  [19718/20519] intraday_9198.csv.gz  in=466,537,650 out=113,176,626 elapsed=274.7s

  [19719/20519] intraday_9200.csv.gz  in=466,549,775 out=113,176,626 elapsed=274.7s

  [19720/20519] intraday_9199.csv.gz  in=466,560,771 out=113,176,626 elapsed=274.7s

  [19721/20519] intraday_9201.csv.gz  in=466,572,030 out=113,176,626 elapsed=274.7s

  [19722/20519] intraday_9203.csv.gz  in=466,583,533 out=113,176,626 elapsed=274.8s

  [19723/20519] intraday_9202.csv.gz  in=466,594,473 out=113,176,626 elapsed=274.8s

  [19724/20519] intraday_9205.csv.gz  in=466,610,760 out=113,176,626 elapsed=274.8s

  [19725/20519] intraday_9204.csv.gz  in=466,627,602 out=113,176,626 elapsed=274.8s

  [19726/20519] intraday_9206.csv.gz  in=466,643,094 out=113,176,626 elapsed=274.8s

  [19727/20519] intraday_9207.csv.gz  in=466,653,723 out=113,176,626 elapsed=274.8s

  [19728/20519] intraday_9209.csv.gz  in=466,668,181 out=113,176,626 elapsed=274.8s

  [19729/20519] intraday_9208.csv.gz  in=466,680,037 out=113,176,626 elapsed=274.8s

  [19730/20519] intraday_9211.csv.gz  in=466,695,973 out=113,176,626 elapsed=274.9s

  [19731/20519] intraday_9210.csv.gz  in=466,714,269 out=113,176,626 elapsed=274.9s

  [19732/20519] intraday_9212.csv.gz  in=466,726,396 out=113,176,626 elapsed=274.9s

  [19733/20519] intraday_9213.csv.gz  in=466,740,091 out=113,176,626 elapsed=274.9s

  [19734/20519] intraday_9214.csv.gz  in=466,752,387 out=113,176,626 elapsed=274.9s

  [19735/20519] intraday_9216.csv.gz  in=466,766,163 out=113,176,626 elapsed=274.9s

  [19736/20519] intraday_9215.csv.gz  in=466,780,875 out=113,176,626 elapsed=274.9s

  [19737/20519] intraday_9217.csv.gz  in=466,792,098 out=113,176,626 elapsed=274.9s

  [19738/20519] intraday_9218.csv.gz  in=466,804,951 out=113,176,626 elapsed=275.0s

  [19739/20519] intraday_9220.csv.gz  in=466,817,700 out=113,176,626 elapsed=275.0s

  [19740/20519] intraday_9221.csv.gz  in=466,830,477 out=113,176,626 elapsed=275.0s

  [19741/20519] intraday_9219.csv.gz  in=466,842,045 out=113,176,626 elapsed=275.0s

  [19742/20519] intraday_9222.csv.gz  in=466,853,715 out=113,176,626 elapsed=275.0s

  [19743/20519] intraday_9223.csv.gz  in=466,868,671 out=113,176,626 elapsed=275.0s

  [19744/20519] intraday_9224.csv.gz  in=466,884,398 out=113,176,626 elapsed=275.0s

  [19745/20519] intraday_9225.csv.gz  in=466,897,014 out=113,176,626 elapsed=275.0s

  [19746/20519] intraday_9226.csv.gz  in=466,909,850 out=113,176,626 elapsed=275.0s

  [19747/20519] intraday_9228.csv.gz  in=466,923,408 out=113,176,626 elapsed=275.1s

  [19748/20519] intraday_9227.csv.gz  in=466,936,605 out=113,176,626 elapsed=275.1s

  [19749/20519] intraday_9230.csv.gz  in=466,950,587 out=113,176,626 elapsed=275.1s

  [19750/20519] intraday_9229.csv.gz  in=466,963,677 out=113,176,626 elapsed=275.1s

  [19751/20519] intraday_9231.csv.gz  in=466,978,918 out=113,176,626 elapsed=275.1s

  [19752/20519] intraday_9232.csv.gz  in=466,990,714 out=113,176,626 elapsed=275.1s

  [19753/20519] intraday_9233.csv.gz  in=467,001,744 out=113,176,626 elapsed=275.1s

  [19754/20519] intraday_9235.csv.gz  in=467,012,816 out=113,176,626 elapsed=275.1s

  [19755/20519] intraday_9234.csv.gz  in=467,027,501 out=113,176,626 elapsed=275.1s

  [19756/20519] intraday_9237.csv.gz  in=467,042,851 out=113,176,626 elapsed=275.2s

  [19757/20519] intraday_9236.csv.gz  in=467,059,150 out=113,176,626 elapsed=275.2s

  [19758/20519] intraday_9239.csv.gz  in=467,072,040 out=113,176,626 elapsed=275.2s

  [19759/20519] intraday_9238.csv.gz  in=467,092,543 out=113,176,626 elapsed=275.2s

  [19760/20519] intraday_9240.csv.gz  in=467,109,524 out=113,176,626 elapsed=275.2s

  [19761/20519] intraday_9242.csv.gz  in=467,123,798 out=113,176,626 elapsed=275.2s

  [19762/20519] intraday_9243.csv.gz  in=467,135,071 out=113,176,626 elapsed=275.2s

  [19763/20519] intraday_9241.csv.gz  in=467,151,615 out=113,176,626 elapsed=275.2s

  [19764/20519] intraday_9244.csv.gz  in=467,164,847 out=113,176,626 elapsed=275.2s

  [19765/20519] intraday_9245.csv.gz  in=467,176,899 out=113,176,626 elapsed=275.2s

  [19766/20519] intraday_9247.csv.gz  in=467,190,917 out=113,176,626 elapsed=275.2s

  [19767/20519] intraday_9246.csv.gz  in=467,203,971 out=113,176,626 elapsed=275.3s

  [19768/20519] intraday_9249.csv.gz  in=467,215,318 out=113,176,626 elapsed=275.3s

  [19769/20519] intraday_9250.csv.gz  in=467,227,300 out=113,176,626 elapsed=275.3s

  [19770/20519] intraday_9248.csv.gz  in=467,244,147 out=113,176,626 elapsed=275.3s

  [19771/20519] intraday_9251.csv.gz  in=467,255,897 out=113,176,626 elapsed=275.3s

  [19772/20519] intraday_9252.csv.gz  in=467,268,343 out=113,176,626 elapsed=275.3s

  [19773/20519] intraday_9253.csv.gz  in=467,280,465 out=113,176,626 elapsed=275.3s

  [19774/20519] intraday_9254.csv.gz  in=467,293,361 out=113,176,626 elapsed=275.3s

  [19775/20519] intraday_9255.csv.gz  in=467,308,561 out=113,176,626 elapsed=275.3s

  [19776/20519] intraday_9256.csv.gz  in=467,321,995 out=113,176,626 elapsed=275.3s

  [19777/20519] intraday_9257.csv.gz  in=467,338,339 out=113,176,626 elapsed=275.3s

  [19778/20519] intraday_9258.csv.gz  in=467,351,768 out=113,176,626 elapsed=275.4s

  [19779/20519] intraday_9259.csv.gz  in=467,362,719 out=113,176,626 elapsed=275.4s

  [19780/20519] intraday_9260.csv.gz  in=467,376,902 out=113,176,626 elapsed=275.4s

  [19781/20519] intraday_9261.csv.gz  in=467,387,688 out=113,176,626 elapsed=275.4s

  [19782/20519] intraday_9262.csv.gz  in=467,401,711 out=113,176,626 elapsed=275.4s

  [19783/20519] intraday_9264.csv.gz  in=467,410,124 out=113,176,626 elapsed=275.4s

  [19784/20519] intraday_9265.csv.gz  in=467,422,740 out=113,176,626 elapsed=275.4s

  [19785/20519] intraday_9263.csv.gz  in=467,430,881 out=113,176,626 elapsed=275.4s

  [19786/20519] intraday_9266.csv.gz  in=467,432,163 out=113,176,626 elapsed=275.4s

  [19787/20519] intraday_9270.csv.gz  in=467,444,768 out=113,176,626 elapsed=275.4s

  [19788/20519] intraday_9269.csv.gz  in=467,457,681 out=113,176,626 elapsed=275.4s

  [19789/20519] intraday_9268.csv.gz  in=467,473,625 out=113,176,626 elapsed=275.4s

  [19790/20519] intraday_9271.csv.gz  in=467,484,310 out=113,176,626 elapsed=275.5s

  [19791/20519] intraday_9272.csv.gz  in=467,497,269 out=113,176,626 elapsed=275.5s

  [19792/20519] intraday_9267.csv.gz  in=467,556,544 out=113,176,626 elapsed=275.5s

  [19793/20519] intraday_9273.csv.gz  in=467,571,327 out=113,176,626 elapsed=275.5s

  [19794/20519] intraday_9274.csv.gz  in=467,586,069 out=113,176,626 elapsed=275.5s

  [19795/20519] intraday_9275.csv.gz  in=467,599,124 out=113,176,626 elapsed=275.5s

  [19796/20519] intraday_9276.csv.gz  in=467,611,383 out=113,176,626 elapsed=275.5s

  [19797/20519] intraday_9278.csv.gz  in=467,625,910 out=113,176,626 elapsed=275.5s

  [19798/20519] intraday_9277.csv.gz  in=467,640,446 out=113,176,626 elapsed=275.5s

  [19799/20519] intraday_9280.csv.gz  in=467,654,031 out=113,176,626 elapsed=275.5s

  [19800/20519] intraday_9279.csv.gz  in=467,667,483 out=113,176,626 elapsed=275.5s

  [19801/20519] intraday_9282.csv.gz  in=467,677,940 out=113,176,626 elapsed=275.6s

  [19802/20519] intraday_9281.csv.gz  in=467,691,989 out=113,176,626 elapsed=275.6s

  [19803/20519] intraday_9283.csv.gz  in=467,702,527 out=113,176,626 elapsed=275.6s

  [19804/20519] intraday_9284.csv.gz  in=467,716,090 out=113,176,626 elapsed=275.6s

  [19805/20519] intraday_9287.csv.gz  in=467,727,380 out=113,176,626 elapsed=275.6s

  [19806/20519] intraday_9285.csv.gz  in=467,740,682 out=113,176,626 elapsed=275.6s

  [19807/20519] intraday_9286.csv.gz  in=467,753,564 out=113,176,626 elapsed=275.6s

  [19808/20519] intraday_9288.csv.gz  in=467,765,003 out=113,176,626 elapsed=275.6s

  [19809/20519] intraday_9289.csv.gz  in=467,778,733 out=113,176,626 elapsed=275.6s

  [19810/20519] intraday_9290.csv.gz  in=467,791,540 out=113,176,626 elapsed=275.6s

  [19811/20519] intraday_9292.csv.gz  in=467,805,511 out=113,176,626 elapsed=275.6s

  [19812/20519] intraday_9291.csv.gz  in=467,819,747 out=113,176,626 elapsed=275.7s

  [19813/20519] intraday_9294.csv.gz  in=467,832,536 out=113,176,626 elapsed=275.7s

  [19814/20519] intraday_9293.csv.gz  in=467,845,192 out=113,176,626 elapsed=275.7s

  [19815/20519] intraday_9295.csv.gz  in=467,857,220 out=113,176,626 elapsed=275.7s

  [19816/20519] intraday_9297.csv.gz  in=467,870,694 out=113,176,626 elapsed=275.7s

  [19817/20519] intraday_9296.csv.gz  in=467,882,057 out=113,176,626 elapsed=275.7s

  [19818/20519] intraday_9298.csv.gz  in=467,897,569 out=113,176,626 elapsed=275.7s

  [19819/20519] intraday_9299.csv.gz  in=467,911,157 out=113,176,626 elapsed=275.7s

  [19820/20519] intraday_9301.csv.gz  in=467,923,398 out=113,176,626 elapsed=275.7s

  [19821/20519] intraday_9300.csv.gz  in=467,934,589 out=113,176,626 elapsed=275.7s

  [19822/20519] intraday_9302.csv.gz  in=467,947,634 out=113,176,626 elapsed=275.7s

  [19823/20519] intraday_9304.csv.gz  in=467,959,674 out=113,176,626 elapsed=275.8s

  [19824/20519] intraday_9303.csv.gz  in=467,971,505 out=113,176,626 elapsed=275.8s

  [19825/20519] intraday_9305.csv.gz  in=467,983,218 out=113,176,626 elapsed=275.8s

  [19826/20519] intraday_9306.csv.gz  in=467,995,465 out=113,176,626 elapsed=275.8s

  [19827/20519] intraday_9307.csv.gz  in=468,006,499 out=113,176,626 elapsed=275.8s

  [19828/20519] intraday_9309.csv.gz  in=468,019,343 out=113,176,626 elapsed=275.8s

  [19829/20519] intraday_9308.csv.gz  in=468,031,448 out=113,176,626 elapsed=275.8s

  [19830/20519] intraday_9310.csv.gz  in=468,044,935 out=113,176,626 elapsed=275.8s

  [19831/20519] intraday_9312.csv.gz  in=468,058,605 out=113,176,626 elapsed=275.8s

  [19832/20519] intraday_9311.csv.gz  in=468,072,228 out=113,176,626 elapsed=275.8s

  [19833/20519] intraday_9313.csv.gz  in=468,083,473 out=113,176,626 elapsed=275.8s

  [19834/20519] intraday_9314.csv.gz  in=468,095,747 out=113,176,626 elapsed=275.8s

  [19835/20519] intraday_9316.csv.gz  in=468,107,213 out=113,176,626 elapsed=275.9s

  [19836/20519] intraday_9315.csv.gz  in=468,120,535 out=113,176,626 elapsed=275.9s

  [19837/20519] intraday_9318.csv.gz  in=468,132,112 out=113,176,626 elapsed=275.9s

  [19838/20519] intraday_9319.csv.gz  in=468,142,857 out=113,176,626 elapsed=275.9s

  [19839/20519] intraday_9317.csv.gz  in=468,155,430 out=113,176,626 elapsed=275.9s

  [19840/20519] intraday_9321.csv.gz  in=468,166,983 out=113,176,626 elapsed=275.9s

  [19841/20519] intraday_9320.csv.gz  in=468,184,296 out=113,176,626 elapsed=275.9s

  [19842/20519] intraday_9323.csv.gz  in=468,197,210 out=113,176,626 elapsed=275.9s

  [19843/20519] intraday_9325.csv.gz  in=468,208,709 out=113,176,626 elapsed=275.9s

  [19844/20519] intraday_9324.csv.gz  in=468,221,626 out=113,176,626 elapsed=276.0s

  [19845/20519] intraday_9322.csv.gz  in=468,234,549 out=113,176,626 elapsed=276.0s

  [19846/20519] intraday_9327.csv.gz  in=468,248,070 out=113,176,626 elapsed=276.0s

  [19847/20519] intraday_9326.csv.gz  in=468,259,446 out=113,176,626 elapsed=276.0s

  [19848/20519] intraday_9328.csv.gz  in=468,272,509 out=113,176,626 elapsed=276.0s

  [19849/20519] intraday_9329.csv.gz  in=468,284,134 out=113,176,626 elapsed=276.0s

  [19850/20519] intraday_9330.csv.gz  in=468,297,608 out=113,176,626 elapsed=276.0s

  [19851/20519] intraday_9332.csv.gz  in=468,308,221 out=113,176,626 elapsed=276.0s

  [19852/20519] intraday_9331.csv.gz  in=468,320,452 out=113,176,626 elapsed=276.0s

  [19853/20519] intraday_9334.csv.gz  in=468,333,446 out=113,176,626 elapsed=276.1s

  [19854/20519] intraday_9333.csv.gz  in=468,348,569 out=113,176,626 elapsed=276.1s

  [19855/20519] intraday_9335.csv.gz  in=468,362,148 out=113,176,626 elapsed=276.1s

  [19856/20519] intraday_9336.csv.gz  in=468,374,796 out=113,176,626 elapsed=276.1s

  [19857/20519] intraday_9337.csv.gz  in=468,387,059 out=113,176,626 elapsed=276.1s

  [19858/20519] intraday_9338.csv.gz  in=468,397,294 out=113,176,626 elapsed=276.1s

  [19859/20519] intraday_9339.csv.gz  in=468,408,662 out=113,176,626 elapsed=276.1s

  [19860/20519] intraday_9340.csv.gz  in=468,421,724 out=113,176,626 elapsed=276.1s

  [19861/20519] intraday_9341.csv.gz  in=468,435,280 out=113,176,626 elapsed=276.1s

  [19862/20519] intraday_9343.csv.gz  in=468,448,058 out=113,176,626 elapsed=276.1s

  [19863/20519] intraday_9342.csv.gz  in=468,460,179 out=113,176,626 elapsed=276.1s

  [19864/20519] intraday_9344.csv.gz  in=468,471,071 out=113,176,626 elapsed=276.2s

  [19865/20519] intraday_9346.csv.gz  in=468,483,176 out=113,176,626 elapsed=276.2s

  [19866/20519] intraday_9347.csv.gz  in=468,494,421 out=113,176,626 elapsed=276.2s

  [19867/20519] intraday_9345.csv.gz  in=468,507,920 out=113,176,626 elapsed=276.2s

  [19868/20519] intraday_9348.csv.gz  in=468,520,244 out=113,176,626 elapsed=276.2s

  [19869/20519] intraday_9349.csv.gz  in=468,529,477 out=113,176,626 elapsed=276.2s

  [19870/20519] intraday_9350.csv.gz  in=468,542,105 out=113,176,626 elapsed=276.2s

  [19871/20519] intraday_9351.csv.gz  in=468,555,400 out=113,176,626 elapsed=276.2s

  [19872/20519] intraday_9352.csv.gz  in=468,570,573 out=113,176,626 elapsed=276.2s

  [19873/20519] intraday_9353.csv.gz  in=468,585,226 out=113,176,626 elapsed=276.2s

  [19874/20519] intraday_9355.csv.gz  in=468,597,297 out=113,176,626 elapsed=276.2s

  [19875/20519] intraday_9354.csv.gz  in=468,610,033 out=113,176,626 elapsed=276.2s

  [19876/20519] intraday_9356.csv.gz  in=468,624,540 out=113,176,626 elapsed=276.3s

  [19877/20519] intraday_9357.csv.gz  in=468,635,441 out=113,176,626 elapsed=276.3s

  [19878/20519] intraday_9359.csv.gz  in=468,647,788 out=113,176,626 elapsed=276.3s

  [19879/20519] intraday_9358.csv.gz  in=468,664,544 out=113,176,626 elapsed=276.3s

  [19880/20519] intraday_9360.csv.gz  in=468,677,744 out=113,176,626 elapsed=276.3s

  [19881/20519] intraday_9361.csv.gz  in=468,691,415 out=113,176,626 elapsed=276.3s

  [19882/20519] intraday_9363.csv.gz  in=468,704,659 out=113,176,626 elapsed=276.3s

  [19883/20519] intraday_9362.csv.gz  in=468,717,418 out=113,176,626 elapsed=276.3s

  [19884/20519] intraday_9364.csv.gz  in=468,730,190 out=113,176,626 elapsed=276.3s

  [19885/20519] intraday_9365.csv.gz  in=468,742,707 out=113,176,626 elapsed=276.3s

  [19886/20519] intraday_9366.csv.gz  in=468,755,393 out=113,176,626 elapsed=276.3s

  [19887/20519] intraday_9367.csv.gz  in=468,767,893 out=113,176,626 elapsed=276.4s

  [19888/20519] intraday_9368.csv.gz  in=468,780,957 out=113,176,626 elapsed=276.4s

  [19889/20519] intraday_9369.csv.gz  in=468,791,992 out=113,176,626 elapsed=276.4s

  [19890/20519] intraday_9370.csv.gz  in=468,804,486 out=113,176,626 elapsed=276.4s

  [19891/20519] intraday_9371.csv.gz  in=468,821,516 out=113,176,626 elapsed=276.4s

  [19892/20519] intraday_9372.csv.gz  in=468,834,530 out=113,176,626 elapsed=276.4s

  [19893/20519] intraday_9373.csv.gz  in=468,847,888 out=113,176,626 elapsed=276.4s

  [19894/20519] intraday_9374.csv.gz  in=468,859,961 out=113,176,626 elapsed=276.4s

  [19895/20519] intraday_9377.csv.gz  in=468,872,941 out=113,176,626 elapsed=276.4s

  [19896/20519] intraday_9376.csv.gz  in=468,885,409 out=113,176,626 elapsed=276.4s

  [19897/20519] intraday_9378.csv.gz  in=468,900,299 out=113,176,626 elapsed=276.4s

  [19898/20519] intraday_9375.csv.gz  in=468,914,812 out=113,176,626 elapsed=276.4s

  [19899/20519] intraday_9380.csv.gz  in=468,925,433 out=113,176,626 elapsed=276.5s

  [19900/20519] intraday_9379.csv.gz  in=468,938,965 out=113,176,626 elapsed=276.5s

  [19901/20519] intraday_9381.csv.gz  in=468,952,462 out=113,176,626 elapsed=276.5s

  [19902/20519] intraday_9382.csv.gz  in=468,965,271 out=113,176,626 elapsed=276.5s

  [19903/20519] intraday_9384.csv.gz  in=468,981,536 out=113,176,626 elapsed=276.5s

  [19904/20519] intraday_9383.csv.gz  in=468,995,255 out=113,176,626 elapsed=276.5s

  [19905/20519] intraday_9385.csv.gz  in=469,009,951 out=113,176,626 elapsed=276.5s

  [19906/20519] intraday_9386.csv.gz  in=469,027,999 out=113,176,626 elapsed=276.5s

  [19907/20519] intraday_9388.csv.gz  in=469,040,139 out=113,176,626 elapsed=276.5s

  [19908/20519] intraday_9387.csv.gz  in=469,055,321 out=113,176,626 elapsed=276.5s

  [19909/20519] intraday_9390.csv.gz  in=469,067,877 out=113,176,626 elapsed=276.6s

  [19910/20519] intraday_9389.csv.gz  in=469,080,517 out=113,176,626 elapsed=276.6s

  [19911/20519] intraday_9391.csv.gz  in=469,091,530 out=113,176,626 elapsed=276.6s

  [19912/20519] intraday_9392.csv.gz  in=469,104,976 out=113,176,626 elapsed=276.6s

  [19913/20519] intraday_9393.csv.gz  in=469,115,330 out=113,176,626 elapsed=276.6s

  [19914/20519] intraday_9395.csv.gz  in=469,128,928 out=113,176,626 elapsed=276.6s

  [19915/20519] intraday_9394.csv.gz  in=469,143,537 out=113,176,626 elapsed=276.6s

  [19916/20519] intraday_9396.csv.gz  in=469,158,529 out=113,176,626 elapsed=276.6s

  [19917/20519] intraday_9397.csv.gz  in=469,170,099 out=113,176,626 elapsed=276.6s

  [19918/20519] intraday_9398.csv.gz  in=469,180,862 out=113,176,626 elapsed=276.6s

  [19919/20519] intraday_9400.csv.gz  in=469,192,325 out=113,176,626 elapsed=276.6s

  [19920/20519] intraday_9399.csv.gz  in=469,205,937 out=113,176,626 elapsed=276.6s

  [19921/20519] intraday_9401.csv.gz  in=469,218,303 out=113,176,626 elapsed=276.6s

  [19922/20519] intraday_9404.csv.gz  in=469,231,644 out=113,176,626 elapsed=276.7s

  [19923/20519] intraday_9402.csv.gz  in=469,246,516 out=113,176,626 elapsed=276.7s

  [19924/20519] intraday_9403.csv.gz  in=469,261,464 out=113,176,626 elapsed=276.7s

  [19925/20519] intraday_9405.csv.gz  in=469,276,202 out=113,176,626 elapsed=276.7s

  [19926/20519] intraday_9406.csv.gz  in=469,288,804 out=113,176,626 elapsed=276.7s

  [19927/20519] intraday_9408.csv.gz  in=469,301,073 out=113,176,626 elapsed=276.7s

  [19928/20519] intraday_9407.csv.gz  in=469,314,569 out=113,176,626 elapsed=276.7s

  [19929/20519] intraday_9410.csv.gz  in=469,324,302 out=113,176,626 elapsed=276.7s

  [19930/20519] intraday_9409.csv.gz  in=469,337,153 out=113,176,626 elapsed=276.7s

  [19931/20519] intraday_9411.csv.gz  in=469,345,386 out=113,176,626 elapsed=276.7s

  [19932/20519] intraday_9412.csv.gz  in=469,355,776 out=113,176,626 elapsed=276.7s

  [19933/20519] intraday_9413.csv.gz  in=469,360,830 out=113,176,626 elapsed=276.8s

  [19934/20519] intraday_9414.csv.gz  in=469,389,188 out=113,176,626 elapsed=276.8s

  [19935/20519] intraday_9415.csv.gz  in=469,405,272 out=113,176,626 elapsed=276.8s

  [19936/20519] intraday_9417.csv.gz  in=469,416,020 out=113,176,626 elapsed=276.8s

  [19937/20519] intraday_9416.csv.gz  in=469,428,957 out=113,176,626 elapsed=276.8s

  [19938/20519] intraday_9418.csv.gz  in=469,439,729 out=113,176,626 elapsed=276.8s

  [19939/20519] intraday_9419.csv.gz  in=469,451,990 out=113,176,626 elapsed=276.8s

  [19940/20519] intraday_9420.csv.gz  in=469,467,472 out=113,176,626 elapsed=276.8s

  [19941/20519] intraday_9421.csv.gz  in=469,481,498 out=113,176,626 elapsed=276.8s

  [19942/20519] intraday_9422.csv.gz  in=469,493,901 out=113,176,626 elapsed=276.9s

  [19943/20519] intraday_9424.csv.gz  in=469,508,528 out=113,176,626 elapsed=276.9s

  [19944/20519] intraday_9423.csv.gz  in=469,520,404 out=113,176,626 elapsed=276.9s

  [19945/20519] intraday_9425.csv.gz  in=469,535,084 out=113,176,626 elapsed=276.9s

  [19946/20519] intraday_9426.csv.gz  in=469,546,827 out=113,176,626 elapsed=276.9s

  [19947/20519] intraday_9427.csv.gz  in=469,561,261 out=113,176,626 elapsed=276.9s

  [19948/20519] intraday_9429.csv.gz  in=469,572,069 out=113,176,626 elapsed=276.9s

  [19949/20519] intraday_9428.csv.gz  in=469,585,583 out=113,176,626 elapsed=276.9s

  [19950/20519] intraday_9430.csv.gz  in=469,596,892 out=113,176,626 elapsed=277.0s

  [19951/20519] intraday_9431.csv.gz  in=469,610,098 out=113,176,626 elapsed=277.0s

  [19952/20519] intraday_9433.csv.gz  in=469,622,501 out=113,176,626 elapsed=277.0s

  [19953/20519] intraday_9432.csv.gz  in=469,634,857 out=113,176,626 elapsed=277.0s

  [19954/20519] intraday_9434.csv.gz  in=469,646,205 out=113,176,626 elapsed=277.0s

  [19955/20519] intraday_9435.csv.gz  in=469,657,850 out=113,176,626 elapsed=277.0s

  [19956/20519] intraday_9436.csv.gz  in=469,670,304 out=113,176,626 elapsed=277.0s

  [19957/20519] intraday_9437.csv.gz  in=469,683,076 out=113,176,626 elapsed=277.0s

  [19958/20519] intraday_9438.csv.gz  in=469,695,341 out=113,176,626 elapsed=277.0s

  [19959/20519] intraday_9440.csv.gz  in=469,707,609 out=113,176,626 elapsed=277.1s

  [19960/20519] intraday_9439.csv.gz  in=469,721,625 out=113,176,626 elapsed=277.1s

  [19961/20519] intraday_9441.csv.gz  in=469,733,201 out=113,176,626 elapsed=277.1s

  [19962/20519] intraday_9444.csv.gz  in=469,745,691 out=113,176,626 elapsed=277.1s

  [19963/20519] intraday_9442.csv.gz  in=469,757,326 out=113,176,626 elapsed=277.1s

  [19964/20519] intraday_9443.csv.gz  in=469,768,929 out=113,176,626 elapsed=277.1s

  [19965/20519] intraday_9447.csv.gz  in=469,779,173 out=113,176,626 elapsed=277.1s

  [19966/20519] intraday_9446.csv.gz  in=469,792,393 out=113,176,626 elapsed=277.1s

  [19967/20519] intraday_9445.csv.gz  in=469,807,386 out=113,176,626 elapsed=277.1s

  [19968/20519] intraday_9448.csv.gz  in=469,819,209 out=113,176,626 elapsed=277.1s

  [19969/20519] intraday_9451.csv.gz  in=469,831,063 out=113,176,626 elapsed=277.2s

  [19970/20519] intraday_9450.csv.gz  in=469,843,675 out=113,176,626 elapsed=277.2s

  [19971/20519] intraday_9449.csv.gz  in=469,855,928 out=113,176,626 elapsed=277.2s

  [19972/20519] intraday_9452.csv.gz  in=469,868,251 out=113,176,626 elapsed=277.2s

  [19973/20519] intraday_9453.csv.gz  in=469,879,413 out=113,176,626 elapsed=277.2s

  [19974/20519] intraday_9454.csv.gz  in=469,890,023 out=113,176,626 elapsed=277.2s

  [19975/20519] intraday_9455.csv.gz  in=469,901,817 out=113,176,626 elapsed=277.2s

  [19976/20519] intraday_9456.csv.gz  in=469,914,300 out=113,176,626 elapsed=277.2s

  [19977/20519] intraday_9458.csv.gz  in=469,927,570 out=113,176,626 elapsed=277.3s

  [19978/20519] intraday_9459.csv.gz  in=469,941,162 out=113,176,626 elapsed=277.3s

  [19979/20519] intraday_9457.csv.gz  in=469,953,476 out=113,176,626 elapsed=277.3s

  [19980/20519] intraday_9460.csv.gz  in=469,964,985 out=113,176,626 elapsed=277.3s

  [19981/20519] intraday_9461.csv.gz  in=469,977,372 out=113,176,626 elapsed=277.3s

  [19982/20519] intraday_9462.csv.gz  in=469,989,298 out=113,176,626 elapsed=277.3s

  [19983/20519] intraday_9463.csv.gz  in=470,002,830 out=113,176,626 elapsed=277.3s

  [19984/20519] intraday_9464.csv.gz  in=470,013,076 out=113,176,626 elapsed=277.3s

  [19985/20519] intraday_9465.csv.gz  in=470,025,693 out=113,176,626 elapsed=277.4s

  [19986/20519] intraday_9466.csv.gz  in=470,036,640 out=113,176,626 elapsed=277.4s

  [19987/20519] intraday_9467.csv.gz  in=470,049,538 out=113,176,626 elapsed=277.4s

  [19988/20519] intraday_9468.csv.gz  in=470,061,899 out=113,176,626 elapsed=277.4s

  [19989/20519] intraday_9470.csv.gz  in=470,076,146 out=113,176,626 elapsed=277.4s

  [19990/20519] intraday_9469.csv.gz  in=470,089,391 out=113,176,626 elapsed=277.4s

  [19991/20519] intraday_9471.csv.gz  in=470,100,949 out=113,176,626 elapsed=277.4s

  [19992/20519] intraday_9472.csv.gz  in=470,112,429 out=113,176,626 elapsed=277.4s

  [19993/20519] intraday_9474.csv.gz  in=470,125,443 out=113,176,626 elapsed=277.4s

  [19994/20519] intraday_9473.csv.gz  in=470,135,692 out=113,176,626 elapsed=277.4s

  [19995/20519] intraday_9475.csv.gz  in=470,148,067 out=113,176,626 elapsed=277.4s

  [19996/20519] intraday_9476.csv.gz  in=470,159,925 out=113,176,626 elapsed=277.4s

  [19997/20519] intraday_9479.csv.gz  in=470,170,472 out=113,176,626 elapsed=277.5s

  [19998/20519] intraday_9477.csv.gz  in=470,183,796 out=113,176,626 elapsed=277.5s

  [19999/20519] intraday_9478.csv.gz  in=470,196,819 out=113,176,626 elapsed=277.5s

  [20000/20519] intraday_9480.csv.gz  in=470,210,901 out=113,176,626 elapsed=277.5s

  [20001/20519] intraday_9484.csv.gz  in=470,222,278 out=113,176,626 elapsed=277.5s

  [20002/20519] intraday_9481.csv.gz  in=470,238,461 out=113,176,626 elapsed=277.5s

  [20003/20519] intraday_9482.csv.gz  in=470,248,960 out=113,176,626 elapsed=277.5s

  [20004/20519] intraday_9483.csv.gz  in=470,263,468 out=113,176,626 elapsed=277.5s

  [20005/20519] intraday_9485.csv.gz  in=470,273,811 out=113,176,626 elapsed=277.6s

  [20006/20519] intraday_9487.csv.gz  in=470,286,878 out=113,176,626 elapsed=277.6s

  [20007/20519] intraday_9486.csv.gz  in=470,299,360 out=113,176,626 elapsed=277.6s

  [20008/20519] intraday_9488.csv.gz  in=470,312,339 out=113,176,626 elapsed=277.6s

  [20009/20519] intraday_9489.csv.gz  in=470,324,902 out=113,176,626 elapsed=277.6s

  [20010/20519] intraday_9490.csv.gz  in=470,337,503 out=113,176,626 elapsed=277.6s

  [20011/20519] intraday_9492.csv.gz  in=470,349,455 out=113,176,626 elapsed=277.6s

  [20012/20519] intraday_9491.csv.gz  in=470,359,085 out=113,176,626 elapsed=277.6s

  [20013/20519] intraday_9493.csv.gz  in=470,372,218 out=113,176,626 elapsed=277.6s

  [20014/20519] intraday_9494.csv.gz  in=470,383,623 out=113,176,626 elapsed=277.6s

  [20015/20519] intraday_9495.csv.gz  in=470,395,342 out=113,176,626 elapsed=277.6s

  [20016/20519] intraday_9496.csv.gz  in=470,406,241 out=113,176,626 elapsed=277.7s

  [20017/20519] intraday_9498.csv.gz  in=470,418,646 out=113,176,626 elapsed=277.7s

  [20018/20519] intraday_9497.csv.gz  in=470,430,205 out=113,176,626 elapsed=277.7s

  [20019/20519] intraday_9499.csv.gz  in=470,445,984 out=113,176,626 elapsed=277.7s

  [20020/20519] intraday_9500.csv.gz  in=470,461,925 out=113,176,626 elapsed=277.7s

  [20021/20519] intraday_9501.csv.gz  in=470,473,100 out=113,176,626 elapsed=277.7s

  [20022/20519] intraday_9503.csv.gz  in=470,485,830 out=113,176,626 elapsed=277.7s

  [20023/20519] intraday_9502.csv.gz  in=470,498,340 out=113,176,626 elapsed=277.7s

  [20024/20519] intraday_9504.csv.gz  in=470,511,510 out=113,176,626 elapsed=277.7s

  [20025/20519] intraday_9505.csv.gz  in=470,527,128 out=113,176,626 elapsed=277.7s

  [20026/20519] intraday_9507.csv.gz  in=470,539,342 out=113,176,626 elapsed=277.8s

  [20027/20519] intraday_9506.csv.gz  in=470,551,244 out=113,176,626 elapsed=277.8s

  [20028/20519] intraday_9508.csv.gz  in=470,564,996 out=113,176,626 elapsed=277.8s

  [20029/20519] intraday_9509.csv.gz  in=470,578,429 out=113,176,626 elapsed=277.8s

  [20030/20519] intraday_9510.csv.gz  in=470,591,430 out=113,176,626 elapsed=277.8s

  [20031/20519] intraday_9512.csv.gz  in=470,604,436 out=113,176,626 elapsed=277.8s

  [20032/20519] intraday_9511.csv.gz  in=470,617,001 out=113,176,626 elapsed=277.8s

  [20033/20519] intraday_9514.csv.gz  in=470,630,379 out=113,176,626 elapsed=277.8s

  [20034/20519] intraday_9513.csv.gz  in=470,643,307 out=113,176,626 elapsed=277.9s

  [20035/20519] intraday_9515.csv.gz  in=470,653,891 out=113,176,626 elapsed=277.9s

  [20036/20519] intraday_9516.csv.gz  in=470,666,384 out=113,176,626 elapsed=277.9s

  [20037/20519] intraday_9517.csv.gz  in=470,680,169 out=113,176,626 elapsed=277.9s

  [20038/20519] intraday_9519.csv.gz  in=470,693,460 out=113,176,626 elapsed=277.9s

  [20039/20519] intraday_9518.csv.gz  in=470,707,883 out=113,176,626 elapsed=277.9s

  [20040/20519] intraday_9521.csv.gz  in=470,720,899 out=113,176,626 elapsed=277.9s

  [20041/20519] intraday_9520.csv.gz  in=470,733,068 out=113,176,626 elapsed=278.0s

  [20042/20519] intraday_9522.csv.gz  in=470,748,312 out=113,176,626 elapsed=278.0s

  [20043/20519] intraday_9523.csv.gz  in=470,760,260 out=113,176,626 elapsed=278.0s

  [20044/20519] intraday_9524.csv.gz  in=470,772,542 out=113,176,626 elapsed=278.0s

  [20045/20519] intraday_9525.csv.gz  in=470,787,661 out=113,176,626 elapsed=278.0s

  [20046/20519] intraday_9528.csv.gz  in=470,800,583 out=113,176,626 elapsed=278.0s

  [20047/20519] intraday_9529.csv.gz  in=470,814,217 out=113,176,626 elapsed=278.1s

  [20048/20519] intraday_9526.csv.gz  in=470,829,213 out=113,176,626 elapsed=278.1s

  [20049/20519] intraday_9527.csv.gz  in=470,838,566 out=113,176,626 elapsed=278.1s

  [20050/20519] intraday_9530.csv.gz  in=470,850,532 out=113,176,626 elapsed=278.1s

  [20051/20519] intraday_9532.csv.gz  in=470,866,009 out=113,176,626 elapsed=278.1s

  [20052/20519] intraday_9533.csv.gz  in=470,884,227 out=113,176,626 elapsed=278.1s

  [20053/20519] intraday_9531.csv.gz  in=470,897,958 out=113,176,626 elapsed=278.1s

  [20054/20519] intraday_9534.csv.gz  in=470,913,477 out=113,176,626 elapsed=278.1s

  [20055/20519] intraday_9536.csv.gz  in=470,925,430 out=113,176,626 elapsed=278.1s

  [20056/20519] intraday_9535.csv.gz  in=470,938,864 out=113,176,626 elapsed=278.1s

  [20057/20519] intraday_9537.csv.gz  in=470,951,747 out=113,176,626 elapsed=278.1s

  [20058/20519] intraday_9538.csv.gz  in=470,961,865 out=113,176,626 elapsed=278.2s

  [20059/20519] intraday_9539.csv.gz  in=470,975,636 out=113,176,626 elapsed=278.2s

  [20060/20519] intraday_9541.csv.gz  in=470,988,901 out=113,176,626 elapsed=278.2s

  [20061/20519] intraday_9540.csv.gz  in=470,999,654 out=113,176,626 elapsed=278.2s

  [20062/20519] intraday_9544.csv.gz  in=471,010,688 out=113,176,626 elapsed=278.2s

  [20063/20519] intraday_9545.csv.gz  in=471,022,915 out=113,176,626 elapsed=278.2s

  [20064/20519] intraday_9542.csv.gz  in=471,035,667 out=113,176,626 elapsed=278.2s

  [20065/20519] intraday_9543.csv.gz  in=471,051,400 out=113,176,626 elapsed=278.2s

  [20066/20519] intraday_9546.csv.gz  in=471,062,903 out=113,176,626 elapsed=278.2s

  [20067/20519] intraday_9548.csv.gz  in=471,074,161 out=113,176,626 elapsed=278.3s

  [20068/20519] intraday_9547.csv.gz  in=471,086,577 out=113,176,626 elapsed=278.3s

  [20069/20519] intraday_9549.csv.gz  in=471,100,106 out=113,176,626 elapsed=278.3s

  [20070/20519] intraday_9550.csv.gz  in=471,115,127 out=113,176,626 elapsed=278.3s

  [20071/20519] intraday_9551.csv.gz  in=471,128,942 out=113,176,626 elapsed=278.3s

  [20072/20519] intraday_9552.csv.gz  in=471,143,882 out=113,176,626 elapsed=278.3s

  [20073/20519] intraday_9553.csv.gz  in=471,156,789 out=113,176,626 elapsed=278.3s

  [20074/20519] intraday_9554.csv.gz  in=471,168,644 out=113,176,626 elapsed=278.3s

  [20075/20519] intraday_9555.csv.gz  in=471,182,044 out=113,176,626 elapsed=278.3s

  [20076/20519] intraday_9557.csv.gz  in=471,195,746 out=113,176,626 elapsed=278.3s

  [20077/20519] intraday_9556.csv.gz  in=471,207,577 out=113,176,626 elapsed=278.4s

  [20078/20519] intraday_9558.csv.gz  in=471,214,960 out=113,176,626 elapsed=278.4s

  [20079/20519] intraday_9559.csv.gz  in=471,224,503 out=113,176,626 elapsed=278.4s

  [20080/20519] intraday_9560.csv.gz  in=471,235,468 out=113,176,626 elapsed=278.4s

  [20081/20519] intraday_9564.csv.gz  in=471,245,510 out=113,176,626 elapsed=278.4s

  [20082/20519] intraday_9563.csv.gz  in=471,258,060 out=113,176,626 elapsed=278.4s

  [20083/20519] intraday_9562.csv.gz  in=471,270,126 out=113,176,626 elapsed=278.4s

  [20084/20519] intraday_9561.csv.gz  in=471,286,603 out=113,176,626 elapsed=278.4s

  [20085/20519] intraday_9566.csv.gz  in=471,300,128 out=113,176,626 elapsed=278.4s

  [20086/20519] intraday_9568.csv.gz  in=471,312,539 out=113,176,626 elapsed=278.4s

  [20087/20519] intraday_9565.csv.gz  in=471,325,115 out=113,176,626 elapsed=278.4s

  [20088/20519] intraday_9567.csv.gz  in=471,339,847 out=113,176,626 elapsed=278.4s

  [20089/20519] intraday_9571.csv.gz  in=471,353,320 out=113,176,626 elapsed=278.5s

  [20090/20519] intraday_9569.csv.gz  in=471,365,787 out=113,176,626 elapsed=278.5s

  [20091/20519] intraday_9572.csv.gz  in=471,378,929 out=113,176,626 elapsed=278.5s

  [20092/20519] intraday_9570.csv.gz  in=471,393,330 out=113,176,626 elapsed=278.5s

  [20093/20519] intraday_9573.csv.gz  in=471,406,833 out=113,176,626 elapsed=278.5s

  [20094/20519] intraday_9574.csv.gz  in=471,421,341 out=113,176,626 elapsed=278.5s

  [20095/20519] intraday_9575.csv.gz  in=471,431,866 out=113,176,626 elapsed=278.5s

  [20096/20519] intraday_9576.csv.gz  in=471,442,965 out=113,176,626 elapsed=278.5s

  [20097/20519] intraday_9577.csv.gz  in=471,456,305 out=113,176,626 elapsed=278.5s

  [20098/20519] intraday_9579.csv.gz  in=471,468,261 out=113,176,626 elapsed=278.5s

  [20099/20519] intraday_9578.csv.gz  in=471,480,989 out=113,176,626 elapsed=278.5s

  [20100/20519] intraday_9581.csv.gz  in=471,492,688 out=113,176,626 elapsed=278.6s

  [20101/20519] intraday_9580.csv.gz  in=471,503,531 out=113,176,626 elapsed=278.6s

  [20102/20519] intraday_9582.csv.gz  in=471,518,343 out=113,176,626 elapsed=278.6s

  [20103/20519] intraday_9583.csv.gz  in=471,531,619 out=113,176,626 elapsed=278.6s

  [20104/20519] intraday_9585.csv.gz  in=471,544,391 out=113,176,626 elapsed=278.6s

  [20105/20519] intraday_9584.csv.gz  in=471,556,617 out=113,176,626 elapsed=278.6s

  [20106/20519] intraday_9586.csv.gz  in=471,568,752 out=113,176,626 elapsed=278.6s

  [20107/20519] intraday_9587.csv.gz  in=471,585,553 out=113,176,626 elapsed=278.6s

  [20108/20519] intraday_9590.csv.gz  in=471,597,484 out=113,176,626 elapsed=278.6s

  [20109/20519] intraday_9588.csv.gz  in=471,613,689 out=113,176,626 elapsed=278.6s

  [20110/20519] intraday_9589.csv.gz  in=471,626,181 out=113,176,626 elapsed=278.6s

  [20111/20519] intraday_9591.csv.gz  in=471,641,574 out=113,176,626 elapsed=278.7s

  [20112/20519] intraday_9592.csv.gz  in=471,654,866 out=113,176,626 elapsed=278.7s

  [20113/20519] intraday_9594.csv.gz  in=471,665,232 out=113,176,626 elapsed=278.7s

  [20114/20519] intraday_9593.csv.gz  in=471,675,487 out=113,176,626 elapsed=278.7s

  [20115/20519] intraday_9595.csv.gz  in=471,689,095 out=113,176,626 elapsed=278.7s

  [20116/20519] intraday_9596.csv.gz  in=471,701,092 out=113,176,626 elapsed=278.7s

  [20117/20519] intraday_9597.csv.gz  in=471,713,165 out=113,176,626 elapsed=278.7s

  [20118/20519] intraday_9598.csv.gz  in=471,729,008 out=113,176,626 elapsed=278.7s

  [20119/20519] intraday_9600.csv.gz  in=471,740,497 out=113,176,626 elapsed=278.7s

  [20120/20519] intraday_9599.csv.gz  in=471,751,523 out=113,176,626 elapsed=278.7s

  [20121/20519] intraday_9601.csv.gz  in=471,763,088 out=113,176,626 elapsed=278.8s

  [20122/20519] intraday_9602.csv.gz  in=471,776,858 out=113,176,626 elapsed=278.8s

  [20123/20519] intraday_9603.csv.gz  in=471,789,213 out=113,176,626 elapsed=278.8s

  [20124/20519] intraday_9604.csv.gz  in=471,802,402 out=113,176,626 elapsed=278.8s

  [20125/20519] intraday_9605.csv.gz  in=471,817,982 out=113,176,626 elapsed=278.8s

  [20126/20519] intraday_9606.csv.gz  in=471,834,151 out=113,176,626 elapsed=278.8s

  [20127/20519] intraday_9607.csv.gz  in=471,848,736 out=113,176,626 elapsed=278.8s

  [20128/20519] intraday_9608.csv.gz  in=471,860,117 out=113,176,626 elapsed=278.8s

  [20129/20519] intraday_9610.csv.gz  in=471,870,098 out=113,176,626 elapsed=278.8s

  [20130/20519] intraday_9609.csv.gz  in=471,882,193 out=113,176,626 elapsed=278.9s

  [20131/20519] intraday_9611.csv.gz  in=471,894,215 out=113,176,626 elapsed=278.9s

  [20132/20519] intraday_9612.csv.gz  in=471,906,645 out=113,176,626 elapsed=278.9s

  [20133/20519] intraday_9614.csv.gz  in=471,919,832 out=113,176,626 elapsed=278.9s

  [20134/20519] intraday_9613.csv.gz  in=471,931,157 out=113,176,626 elapsed=278.9s

  [20135/20519] intraday_9615.csv.gz  in=471,943,307 out=113,176,626 elapsed=278.9s

  [20136/20519] intraday_9616.csv.gz  in=471,955,038 out=113,176,626 elapsed=279.0s

  [20137/20519] intraday_9617.csv.gz  in=471,968,234 out=113,176,626 elapsed=279.0s

  [20138/20519] intraday_9618.csv.gz  in=471,979,836 out=113,176,626 elapsed=279.0s

  [20139/20519] intraday_9619.csv.gz  in=471,991,059 out=113,176,626 elapsed=279.0s

  [20140/20519] intraday_9620.csv.gz  in=472,004,089 out=113,176,626 elapsed=279.0s

  [20141/20519] intraday_9621.csv.gz  in=472,016,864 out=113,176,626 elapsed=279.0s

  [20142/20519] intraday_9622.csv.gz  in=472,033,967 out=113,176,626 elapsed=279.0s

  [20143/20519] intraday_9623.csv.gz  in=472,046,541 out=113,176,626 elapsed=279.1s

  [20144/20519] intraday_9624.csv.gz  in=472,058,190 out=113,176,626 elapsed=279.1s

  [20145/20519] intraday_9625.csv.gz  in=472,070,451 out=113,176,626 elapsed=279.1s

  [20146/20519] intraday_9626.csv.gz  in=472,082,148 out=113,176,626 elapsed=279.1s

  [20147/20519] intraday_9627.csv.gz  in=472,097,338 out=113,176,626 elapsed=279.1s

  [20148/20519] intraday_9628.csv.gz  in=472,110,812 out=113,176,626 elapsed=279.1s

  [20149/20519] intraday_9629.csv.gz  in=472,125,332 out=113,176,626 elapsed=279.1s

  [20150/20519] intraday_9630.csv.gz  in=472,147,270 out=113,176,626 elapsed=279.1s

  [20151/20519] intraday_9631.csv.gz  in=472,158,378 out=113,176,626 elapsed=279.1s

  [20152/20519] intraday_9633.csv.gz  in=472,170,505 out=113,176,626 elapsed=279.1s

  [20153/20519] intraday_9632.csv.gz  in=472,181,496 out=113,176,626 elapsed=279.1s

  [20154/20519] intraday_9634.csv.gz  in=472,194,128 out=113,176,626 elapsed=279.2s

  [20155/20519] intraday_9635.csv.gz  in=472,209,389 out=113,176,626 elapsed=279.2s

  [20156/20519] intraday_9637.csv.gz  in=472,220,716 out=113,176,626 elapsed=279.2s

  [20157/20519] intraday_9636.csv.gz  in=472,233,237 out=113,176,626 elapsed=279.2s

  [20158/20519] intraday_9638.csv.gz  in=472,244,252 out=113,176,626 elapsed=279.2s

  [20159/20519] intraday_9639.csv.gz  in=472,257,151 out=113,176,626 elapsed=279.2s

  [20160/20519] intraday_9641.csv.gz  in=472,269,678 out=113,176,626 elapsed=279.2s

  [20161/20519] intraday_9640.csv.gz  in=472,281,566 out=113,176,626 elapsed=279.2s

  [20162/20519] intraday_9642.csv.gz  in=472,291,644 out=113,176,626 elapsed=279.2s

  [20163/20519] intraday_9643.csv.gz  in=472,302,213 out=113,176,626 elapsed=279.2s

  [20164/20519] intraday_9644.csv.gz  in=472,313,487 out=113,176,626 elapsed=279.3s

  [20165/20519] intraday_9645.csv.gz  in=472,331,419 out=113,176,626 elapsed=279.3s

  [20166/20519] intraday_9646.csv.gz  in=472,347,641 out=113,176,626 elapsed=279.3s

  [20167/20519] intraday_9647.csv.gz  in=472,359,826 out=113,176,626 elapsed=279.3s

  [20168/20519] intraday_9648.csv.gz  in=472,371,175 out=113,176,626 elapsed=279.3s

  [20169/20519] intraday_9649.csv.gz  in=472,383,267 out=113,176,626 elapsed=279.3s

  [20170/20519] intraday_9650.csv.gz  in=472,398,096 out=113,176,626 elapsed=279.3s

  [20171/20519] intraday_9651.csv.gz  in=472,410,298 out=113,176,626 elapsed=279.3s

  [20172/20519] intraday_9652.csv.gz  in=472,426,170 out=113,176,626 elapsed=279.3s

  [20173/20519] intraday_9653.csv.gz  in=472,436,715 out=113,176,626 elapsed=279.3s

  [20174/20519] intraday_9654.csv.gz  in=472,449,973 out=113,176,626 elapsed=279.3s

  [20175/20519] intraday_9655.csv.gz  in=472,463,200 out=113,176,626 elapsed=279.3s

  [20176/20519] intraday_9656.csv.gz  in=472,475,856 out=113,176,626 elapsed=279.3s

  [20177/20519] intraday_9658.csv.gz  in=472,488,449 out=113,176,626 elapsed=279.4s

  [20178/20519] intraday_9657.csv.gz  in=472,502,050 out=113,176,626 elapsed=279.4s

  [20179/20519] intraday_9659.csv.gz  in=472,515,414 out=113,176,626 elapsed=279.4s

  [20180/20519] intraday_9660.csv.gz  in=472,527,310 out=113,176,626 elapsed=279.4s

  [20181/20519] intraday_9661.csv.gz  in=472,539,702 out=113,176,626 elapsed=279.4s

  [20182/20519] intraday_9663.csv.gz  in=472,551,515 out=113,176,626 elapsed=279.4s

  [20183/20519] intraday_9662.csv.gz  in=472,564,082 out=113,176,626 elapsed=279.4s

  [20184/20519] intraday_9664.csv.gz  in=472,578,861 out=113,176,626 elapsed=279.4s

  [20185/20519] intraday_9665.csv.gz  in=472,593,938 out=113,176,626 elapsed=279.4s

  [20186/20519] intraday_9666.csv.gz  in=472,609,712 out=113,176,626 elapsed=279.4s

  [20187/20519] intraday_9667.csv.gz  in=472,623,054 out=113,176,626 elapsed=279.4s

  [20188/20519] intraday_9668.csv.gz  in=472,635,850 out=113,176,626 elapsed=279.5s

  [20189/20519] intraday_9669.csv.gz  in=472,649,371 out=113,176,626 elapsed=279.5s

  [20190/20519] intraday_9670.csv.gz  in=472,660,414 out=113,176,626 elapsed=279.5s

  [20191/20519] intraday_9672.csv.gz  in=472,674,740 out=113,176,626 elapsed=279.5s

  [20192/20519] intraday_9671.csv.gz  in=472,690,042 out=113,176,626 elapsed=279.5s

  [20193/20519] intraday_9673.csv.gz  in=472,703,391 out=113,176,626 elapsed=279.5s

  [20194/20519] intraday_9674.csv.gz  in=472,714,453 out=113,176,626 elapsed=279.5s

  [20195/20519] intraday_9675.csv.gz  in=472,729,366 out=113,176,626 elapsed=279.5s

  [20196/20519] intraday_9676.csv.gz  in=472,741,625 out=113,176,626 elapsed=279.5s

  [20197/20519] intraday_9677.csv.gz  in=472,755,788 out=113,176,626 elapsed=279.5s

  [20198/20519] intraday_9678.csv.gz  in=472,770,150 out=113,176,626 elapsed=279.6s

  [20199/20519] intraday_9679.csv.gz  in=472,787,763 out=113,176,626 elapsed=279.6s

  [20200/20519] intraday_9680.csv.gz  in=472,800,546 out=113,176,626 elapsed=279.6s

  [20201/20519] intraday_9682.csv.gz  in=472,812,022 out=113,176,626 elapsed=279.6s

  [20202/20519] intraday_9681.csv.gz  in=472,828,895 out=113,176,626 elapsed=279.6s

  [20203/20519] intraday_9683.csv.gz  in=472,842,188 out=113,176,626 elapsed=279.6s

  [20204/20519] intraday_9685.csv.gz  in=472,854,606 out=113,176,626 elapsed=279.6s

  [20205/20519] intraday_9684.csv.gz  in=472,866,315 out=113,176,626 elapsed=279.6s

  [20206/20519] intraday_9687.csv.gz  in=472,879,050 out=113,176,626 elapsed=279.6s

  [20207/20519] intraday_9686.csv.gz  in=472,890,028 out=113,176,626 elapsed=279.6s

  [20208/20519] intraday_9688.csv.gz  in=472,903,575 out=113,176,626 elapsed=279.6s

  [20209/20519] intraday_9689.csv.gz  in=472,919,802 out=113,176,626 elapsed=279.7s

  [20210/20519] intraday_9690.csv.gz  in=472,931,158 out=113,176,626 elapsed=279.7s

  [20211/20519] intraday_9691.csv.gz  in=472,943,461 out=113,176,626 elapsed=279.7s

  [20212/20519] intraday_9692.csv.gz  in=472,956,172 out=113,176,626 elapsed=279.7s

  [20213/20519] intraday_9693.csv.gz  in=472,968,969 out=113,176,626 elapsed=279.7s

  [20214/20519] intraday_9694.csv.gz  in=472,980,161 out=113,176,626 elapsed=279.7s

  [20215/20519] intraday_9695.csv.gz  in=472,993,003 out=113,176,626 elapsed=279.7s

  [20216/20519] intraday_9697.csv.gz  in=473,006,966 out=113,176,626 elapsed=279.7s

  [20217/20519] intraday_9696.csv.gz  in=473,021,310 out=113,176,626 elapsed=279.7s

  [20218/20519] intraday_9700.csv.gz  in=473,033,561 out=113,176,626 elapsed=279.8s

  [20219/20519] intraday_9699.csv.gz  in=473,046,974 out=113,176,626 elapsed=279.8s

  [20220/20519] intraday_9698.csv.gz  in=473,061,601 out=113,176,626 elapsed=279.8s

  [20221/20519] intraday_9701.csv.gz  in=473,075,130 out=113,176,626 elapsed=279.8s

  [20222/20519] intraday_9702.csv.gz  in=473,087,074 out=113,176,626 elapsed=279.8s

  [20223/20519] intraday_9703.csv.gz  in=473,100,526 out=113,176,626 elapsed=279.8s

  [20224/20519] intraday_9705.csv.gz  in=473,108,014 out=113,176,626 elapsed=279.8s

  [20225/20519] intraday_9704.csv.gz  in=473,116,359 out=113,176,626 elapsed=279.8s

  [20226/20519] intraday_9708.csv.gz  in=473,116,380 out=113,176,626 elapsed=279.8s

  [20227/20519] intraday_9706.csv.gz  in=473,128,944 out=113,176,626 elapsed=279.8s

  [20228/20519] intraday_9709.csv.gz  in=473,128,962 out=113,176,626 elapsed=279.8s

  [20229/20519] intraday_9707.csv.gz  in=473,130,609 out=113,176,626 elapsed=279.8s

  [20230/20519] intraday_9710.csv.gz  in=473,130,870 out=113,176,626 elapsed=279.9s

  [20231/20519] intraday_9712.csv.gz  in=473,130,975 out=113,176,626 elapsed=279.9s

  [20232/20519] intraday_9711.csv.gz  in=473,135,114 out=113,176,626 elapsed=279.9s

  [20233/20519] intraday_9713.csv.gz  in=473,136,612 out=113,176,626 elapsed=279.9s

  [20234/20519] intraday_9714.csv.gz  in=473,136,664 out=113,176,626 elapsed=279.9s

  [20235/20519] intraday_9715.csv.gz  in=473,137,102 out=113,176,626 elapsed=279.9s

  [20236/20519] intraday_9716.csv.gz  in=473,137,611 out=113,176,626 elapsed=280.0s

  [20237/20519] intraday_9718.csv.gz  in=473,139,005 out=113,176,626 elapsed=280.0s

  [20238/20519] intraday_9717.csv.gz  in=473,139,121 out=113,176,626 elapsed=280.0s

  [20239/20519] intraday_9719.csv.gz  in=473,139,220 out=113,176,626 elapsed=280.0s

  [20240/20519] intraday_9723.csv.gz  in=473,139,233 out=113,176,626 elapsed=280.0s

  [20241/20519] intraday_9720.csv.gz  in=473,144,360 out=113,176,626 elapsed=280.0s

  [20242/20519] intraday_9721.csv.gz  in=473,146,342 out=113,176,626 elapsed=280.0s

  [20243/20519] intraday_9722.csv.gz  in=473,146,568 out=113,176,626 elapsed=280.0s

  [20244/20519] intraday_9724.csv.gz  in=473,156,968 out=113,176,626 elapsed=280.1s

  [20245/20519] intraday_9726.csv.gz  in=473,158,508 out=113,176,626 elapsed=280.1s

  [20246/20519] intraday_9725.csv.gz  in=473,158,552 out=113,176,626 elapsed=280.1s

  [20247/20519] intraday_9730.csv.gz  in=473,158,598 out=113,176,626 elapsed=280.1s

  [20248/20519] intraday_9728.csv.gz  in=473,159,428 out=113,176,626 elapsed=280.1s

  [20249/20519] intraday_9729.csv.gz  in=473,160,724 out=113,176,626 elapsed=280.1s

  [20250/20519] intraday_9727.csv.gz  in=473,161,928 out=113,176,626 elapsed=280.1s

  [20251/20519] intraday_9731.csv.gz  in=473,162,037 out=113,176,626 elapsed=280.1s

  [20252/20519] intraday_9734.csv.gz  in=473,163,245 out=113,176,626 elapsed=280.1s

  [20253/20519] intraday_9733.csv.gz  in=473,165,635 out=113,176,626 elapsed=280.1s

  [20254/20519] intraday_9732.csv.gz  in=473,165,739 out=113,176,626 elapsed=280.1s

  [20255/20519] intraday_9736.csv.gz  in=473,166,165 out=113,176,626 elapsed=280.1s

  [20256/20519] intraday_9735.csv.gz  in=473,166,911 out=113,176,626 elapsed=280.1s

  [20257/20519] intraday_9738.csv.gz  in=473,166,914 out=113,176,626 elapsed=280.1s

  [20258/20519] intraday_9737.csv.gz  in=473,167,348 out=113,176,626 elapsed=280.1s

  [20259/20519] intraday_9740.csv.gz  in=473,182,401 out=113,176,626 elapsed=280.2s

  [20260/20519] intraday_9739.csv.gz  in=473,192,853 out=113,176,626 elapsed=280.2s

  [20261/20519] intraday_9742.csv.gz  in=473,205,270 out=113,176,626 elapsed=280.2s

  [20262/20519] intraday_9741.csv.gz  in=473,218,044 out=113,176,626 elapsed=280.2s

  [20263/20519] intraday_9743.csv.gz  in=473,227,267 out=113,176,626 elapsed=280.2s

  [20264/20519] intraday_9745.csv.gz  in=473,242,823 out=113,176,626 elapsed=280.2s

  [20265/20519] intraday_9744.csv.gz  in=473,254,667 out=113,176,626 elapsed=280.2s

  [20266/20519] intraday_9747.csv.gz  in=473,265,880 out=113,176,626 elapsed=280.2s

  [20267/20519] intraday_9746.csv.gz  in=473,280,043 out=113,176,626 elapsed=280.3s

  [20268/20519] intraday_9748.csv.gz  in=473,292,460 out=113,176,626 elapsed=280.3s

  [20269/20519] intraday_9749.csv.gz  in=473,307,498 out=113,176,626 elapsed=280.3s

  [20270/20519] intraday_9750.csv.gz  in=473,322,812 out=113,176,626 elapsed=280.3s

  [20271/20519] intraday_9751.csv.gz  in=473,335,260 out=113,176,626 elapsed=280.3s

  [20272/20519] intraday_9752.csv.gz  in=473,348,402 out=113,176,626 elapsed=280.3s

  [20273/20519] intraday_9754.csv.gz  in=473,358,129 out=113,176,626 elapsed=280.3s

  [20274/20519] intraday_9753.csv.gz  in=473,373,648 out=113,176,626 elapsed=280.3s

  [20275/20519] intraday_9756.csv.gz  in=473,385,918 out=113,176,626 elapsed=280.3s

  [20276/20519] intraday_9755.csv.gz  in=473,397,675 out=113,176,626 elapsed=280.3s

  [20277/20519] intraday_9758.csv.gz  in=473,408,935 out=113,176,626 elapsed=280.4s

  [20278/20519] intraday_9757.csv.gz  in=473,423,131 out=113,176,626 elapsed=280.4s

  [20279/20519] intraday_9760.csv.gz  in=473,435,005 out=113,176,626 elapsed=280.4s

  [20280/20519] intraday_9759.csv.gz  in=473,446,016 out=113,176,626 elapsed=280.4s

  [20281/20519] intraday_9761.csv.gz  in=473,460,043 out=113,176,626 elapsed=280.4s

  [20282/20519] intraday_9763.csv.gz  in=473,472,824 out=113,176,626 elapsed=280.4s

  [20283/20519] intraday_9762.csv.gz  in=473,485,167 out=113,176,626 elapsed=280.4s

  [20284/20519] intraday_9764.csv.gz  in=473,498,371 out=113,176,626 elapsed=280.4s

  [20285/20519] intraday_9765.csv.gz  in=473,510,592 out=113,176,626 elapsed=280.4s

  [20286/20519] intraday_9766.csv.gz  in=473,523,069 out=113,176,626 elapsed=280.4s

  [20287/20519] intraday_9768.csv.gz  in=473,534,086 out=113,176,626 elapsed=280.4s

  [20288/20519] intraday_9767.csv.gz  in=473,545,808 out=113,176,626 elapsed=280.4s

  [20289/20519] intraday_9769.csv.gz  in=473,558,626 out=113,176,626 elapsed=280.5s

  [20290/20519] intraday_9770.csv.gz  in=473,572,805 out=113,176,626 elapsed=280.5s

  [20291/20519] intraday_9771.csv.gz  in=473,587,513 out=113,176,626 elapsed=280.5s

  [20292/20519] intraday_9772.csv.gz  in=473,598,314 out=113,176,626 elapsed=280.5s

  [20293/20519] intraday_9773.csv.gz  in=473,609,187 out=113,176,626 elapsed=280.5s

  [20294/20519] intraday_9774.csv.gz  in=473,622,494 out=113,176,626 elapsed=280.5s

  [20295/20519] intraday_9776.csv.gz  in=473,632,988 out=113,176,626 elapsed=280.5s

  [20296/20519] intraday_9778.csv.gz  in=473,643,211 out=113,176,626 elapsed=280.5s

  [20297/20519] intraday_9775.csv.gz  in=473,656,784 out=113,176,626 elapsed=280.5s

  [20298/20519] intraday_9777.csv.gz  in=473,669,310 out=113,176,626 elapsed=280.5s

  [20299/20519] intraday_9779.csv.gz  in=473,679,629 out=113,176,626 elapsed=280.5s

  [20300/20519] intraday_9780.csv.gz  in=473,690,461 out=113,176,626 elapsed=280.5s

  [20301/20519] intraday_9781.csv.gz  in=473,701,539 out=113,176,626 elapsed=280.6s

  [20302/20519] intraday_9783.csv.gz  in=473,714,262 out=113,176,626 elapsed=280.6s

  [20303/20519] intraday_9782.csv.gz  in=473,727,210 out=113,176,626 elapsed=280.6s

  [20304/20519] intraday_9784.csv.gz  in=473,740,041 out=113,176,626 elapsed=280.6s

  [20305/20519] intraday_9786.csv.gz  in=473,751,563 out=113,176,626 elapsed=280.6s

  [20306/20519] intraday_9787.csv.gz  in=473,762,828 out=113,176,626 elapsed=280.6s

  [20307/20519] intraday_9785.csv.gz  in=473,775,927 out=113,176,626 elapsed=280.6s

  [20308/20519] intraday_9789.csv.gz  in=473,786,617 out=113,176,626 elapsed=280.6s

  [20309/20519] intraday_9788.csv.gz  in=473,799,457 out=113,176,626 elapsed=280.6s

  [20310/20519] intraday_9790.csv.gz  in=473,810,778 out=113,176,626 elapsed=280.6s

  [20311/20519] intraday_9791.csv.gz  in=473,822,271 out=113,176,626 elapsed=280.6s

  [20312/20519] intraday_9794.csv.gz  in=473,832,877 out=113,176,626 elapsed=280.7s

  [20313/20519] intraday_9792.csv.gz  in=473,843,641 out=113,176,626 elapsed=280.7s

  [20314/20519] intraday_9793.csv.gz  in=473,857,000 out=113,176,626 elapsed=280.7s

  [20315/20519] intraday_9795.csv.gz  in=473,870,325 out=113,176,626 elapsed=280.7s

  [20316/20519] intraday_9797.csv.gz  in=473,882,716 out=113,176,626 elapsed=280.7s

  [20317/20519] intraday_9796.csv.gz  in=473,895,035 out=113,176,626 elapsed=280.7s

  [20318/20519] intraday_9798.csv.gz  in=473,906,834 out=113,176,626 elapsed=280.7s

  [20319/20519] intraday_9799.csv.gz  in=473,919,076 out=113,176,626 elapsed=280.7s

  [20320/20519] intraday_9800.csv.gz  in=473,930,750 out=113,176,626 elapsed=280.7s

  [20321/20519] intraday_9801.csv.gz  in=473,943,838 out=113,176,626 elapsed=280.7s

  [20322/20519] intraday_9802.csv.gz  in=473,954,844 out=113,176,626 elapsed=280.7s

  [20323/20519] intraday_9803.csv.gz  in=473,967,513 out=113,176,626 elapsed=280.8s

  [20324/20519] intraday_9805.csv.gz  in=473,978,748 out=113,176,626 elapsed=280.8s

  [20325/20519] intraday_9804.csv.gz  in=473,991,090 out=113,176,626 elapsed=280.8s

  [20326/20519] intraday_9806.csv.gz  in=474,006,182 out=113,176,626 elapsed=280.8s

  [20327/20519] intraday_9807.csv.gz  in=474,018,875 out=113,176,626 elapsed=280.8s

  [20328/20519] intraday_9809.csv.gz  in=474,031,225 out=113,176,626 elapsed=280.8s

  [20329/20519] intraday_9810.csv.gz  in=474,043,718 out=113,176,626 elapsed=280.8s

  [20330/20519] intraday_9811.csv.gz  in=474,054,297 out=113,176,626 elapsed=280.8s

  [20331/20519] intraday_9808.csv.gz  in=474,069,049 out=113,176,626 elapsed=280.8s

  [20332/20519] intraday_9812.csv.gz  in=474,081,389 out=113,176,626 elapsed=280.8s

  [20333/20519] intraday_9813.csv.gz  in=474,094,246 out=113,176,626 elapsed=280.9s

  [20334/20519] intraday_9814.csv.gz  in=474,108,454 out=113,176,626 elapsed=280.9s

  [20335/20519] intraday_9815.csv.gz  in=474,120,634 out=113,176,626 elapsed=280.9s

  [20336/20519] intraday_9816.csv.gz  in=474,134,565 out=113,176,626 elapsed=280.9s

  [20337/20519] intraday_9817.csv.gz  in=474,144,687 out=113,176,626 elapsed=280.9s

  [20338/20519] intraday_9818.csv.gz  in=474,158,120 out=113,176,626 elapsed=280.9s

  [20339/20519] intraday_9820.csv.gz  in=474,169,420 out=113,176,626 elapsed=280.9s

  [20340/20519] intraday_9819.csv.gz  in=474,182,312 out=113,176,626 elapsed=280.9s

  [20341/20519] intraday_9821.csv.gz  in=474,194,087 out=113,176,626 elapsed=281.0s

  [20342/20519] intraday_9823.csv.gz  in=474,205,479 out=113,176,626 elapsed=281.0s

  [20343/20519] intraday_9824.csv.gz  in=474,217,279 out=113,176,626 elapsed=281.0s

  [20344/20519] intraday_9822.csv.gz  in=474,227,670 out=113,176,626 elapsed=281.0s

  [20345/20519] intraday_9825.csv.gz  in=474,244,236 out=113,176,626 elapsed=281.0s

  [20346/20519] intraday_9826.csv.gz  in=474,260,328 out=113,176,626 elapsed=281.0s

  [20347/20519] intraday_9827.csv.gz  in=474,271,511 out=113,176,626 elapsed=281.0s

  [20348/20519] intraday_9829.csv.gz  in=474,286,143 out=113,176,626 elapsed=281.1s

  [20349/20519] intraday_9828.csv.gz  in=474,299,229 out=113,176,626 elapsed=281.1s

  [20350/20519] intraday_9830.csv.gz  in=474,312,139 out=113,176,626 elapsed=281.1s

  [20351/20519] intraday_9831.csv.gz  in=474,326,851 out=113,176,626 elapsed=281.1s

  [20352/20519] intraday_9832.csv.gz  in=474,338,446 out=113,176,626 elapsed=281.1s

  [20353/20519] intraday_9834.csv.gz  in=474,352,073 out=113,176,626 elapsed=281.1s

  [20354/20519] intraday_9833.csv.gz  in=474,364,431 out=113,176,626 elapsed=281.1s

  [20355/20519] intraday_9835.csv.gz  in=474,377,304 out=113,176,626 elapsed=281.1s

  [20356/20519] intraday_9837.csv.gz  in=474,390,343 out=113,176,626 elapsed=281.2s

  [20357/20519] intraday_9838.csv.gz  in=474,402,688 out=113,176,626 elapsed=281.2s

  [20358/20519] intraday_9836.csv.gz  in=474,416,228 out=113,176,626 elapsed=281.2s

  [20359/20519] intraday_9839.csv.gz  in=474,429,003 out=113,176,626 elapsed=281.2s

  [20360/20519] intraday_9841.csv.gz  in=474,440,884 out=113,176,626 elapsed=281.2s

  [20361/20519] intraday_9842.csv.gz  in=474,452,087 out=113,176,626 elapsed=281.2s

  [20362/20519] intraday_9843.csv.gz  in=474,465,753 out=113,176,626 elapsed=281.2s

  [20363/20519] intraday_9840.csv.gz  in=474,479,307 out=113,176,626 elapsed=281.2s

  [20364/20519] intraday_9844.csv.gz  in=474,494,044 out=113,176,626 elapsed=281.2s

  [20365/20519] intraday_9846.csv.gz  in=474,507,175 out=113,176,626 elapsed=281.2s

  [20366/20519] intraday_9845.csv.gz  in=474,521,109 out=113,176,626 elapsed=281.3s

  [20367/20519] intraday_9847.csv.gz  in=474,533,919 out=113,176,626 elapsed=281.3s

  [20368/20519] intraday_9849.csv.gz  in=474,545,037 out=113,176,626 elapsed=281.3s

  [20369/20519] intraday_9848.csv.gz  in=474,561,413 out=113,176,626 elapsed=281.3s

  [20370/20519] intraday_9850.csv.gz  in=474,573,746 out=113,176,626 elapsed=281.3s

  [20371/20519] intraday_9851.csv.gz  in=474,588,317 out=113,176,626 elapsed=281.3s

  [20372/20519] intraday_9852.csv.gz  in=474,602,801 out=113,176,626 elapsed=281.3s

  [20373/20519] intraday_9854.csv.gz  in=474,616,277 out=113,176,626 elapsed=281.3s

  [20374/20519] intraday_9853.csv.gz  in=474,626,346 out=113,176,626 elapsed=281.3s

  [20375/20519] intraday_9855.csv.gz  in=474,638,771 out=113,176,626 elapsed=281.3s

  [20376/20519] intraday_9857.csv.gz  in=474,653,988 out=113,176,626 elapsed=281.4s

  [20377/20519] intraday_9856.csv.gz  in=474,666,943 out=113,176,626 elapsed=281.4s

  [20378/20519] intraday_9858.csv.gz  in=474,682,394 out=113,176,626 elapsed=281.4s

  [20379/20519] intraday_9859.csv.gz  in=474,699,680 out=113,176,626 elapsed=281.4s

  [20380/20519] intraday_9863.csv.gz  in=474,712,208 out=113,176,626 elapsed=281.4s

  [20381/20519] intraday_9860.csv.gz  in=474,727,953 out=113,176,626 elapsed=281.4s

  [20382/20519] intraday_9862.csv.gz  in=474,741,017 out=113,176,626 elapsed=281.4s

  [20383/20519] intraday_9861.csv.gz  in=474,753,065 out=113,176,626 elapsed=281.4s

  [20384/20519] intraday_9864.csv.gz  in=474,763,462 out=113,176,626 elapsed=281.4s

  [20385/20519] intraday_9865.csv.gz  in=474,776,855 out=113,176,626 elapsed=281.4s

  [20386/20519] intraday_9866.csv.gz  in=474,787,802 out=113,176,626 elapsed=281.5s

  [20387/20519] intraday_9867.csv.gz  in=474,802,809 out=113,176,626 elapsed=281.5s

  [20388/20519] intraday_9868.csv.gz  in=474,816,100 out=113,176,626 elapsed=281.5s

  [20389/20519] intraday_9870.csv.gz  in=474,829,163 out=113,176,626 elapsed=281.5s

  [20390/20519] intraday_9869.csv.gz  in=474,844,447 out=113,176,626 elapsed=281.5s

  [20391/20519] intraday_9872.csv.gz  in=474,856,219 out=113,176,626 elapsed=281.5s

  [20392/20519] intraday_9871.csv.gz  in=474,867,239 out=113,176,626 elapsed=281.5s

  [20393/20519] intraday_9874.csv.gz  in=474,877,745 out=113,176,626 elapsed=281.5s

  [20394/20519] intraday_9873.csv.gz  in=474,891,752 out=113,176,626 elapsed=281.5s

  [20395/20519] intraday_9876.csv.gz  in=474,906,133 out=113,176,626 elapsed=281.5s

  [20396/20519] intraday_9875.csv.gz  in=474,920,436 out=113,176,626 elapsed=281.5s

  [20397/20519] intraday_9877.csv.gz  in=474,934,377 out=113,176,626 elapsed=281.6s

  [20398/20519] intraday_9878.csv.gz  in=474,948,806 out=113,176,626 elapsed=281.6s

  [20399/20519] intraday_9880.csv.gz  in=474,961,194 out=113,176,626 elapsed=281.6s

  [20400/20519] intraday_9879.csv.gz  in=474,973,399 out=113,176,626 elapsed=281.6s

  [20401/20519] intraday_9881.csv.gz  in=474,987,564 out=113,176,626 elapsed=281.6s

  [20402/20519] intraday_9882.csv.gz  in=474,998,418 out=113,176,626 elapsed=281.6s

  [20403/20519] intraday_9883.csv.gz  in=475,011,727 out=113,176,626 elapsed=281.6s

  [20404/20519] intraday_9884.csv.gz  in=475,018,731 out=113,176,626 elapsed=281.6s

  [20405/20519] intraday_9885.csv.gz  in=475,027,105 out=113,176,626 elapsed=281.6s

  [20406/20519] intraday_9886.csv.gz  in=475,037,691 out=113,176,626 elapsed=281.6s

  [20407/20519] intraday_9887.csv.gz  in=475,052,286 out=113,176,626 elapsed=281.7s

  [20408/20519] intraday_9889.csv.gz  in=475,063,908 out=113,176,626 elapsed=281.7s

  [20409/20519] intraday_9888.csv.gz  in=475,076,175 out=113,176,626 elapsed=281.7s

  [20410/20519] intraday_9890.csv.gz  in=475,086,463 out=113,176,626 elapsed=281.7s

  [20411/20519] intraday_9891.csv.gz  in=475,098,027 out=113,176,626 elapsed=281.7s

  [20412/20519] intraday_9892.csv.gz  in=475,112,886 out=113,176,626 elapsed=281.7s

  [20413/20519] intraday_9894.csv.gz  in=475,123,517 out=113,176,626 elapsed=281.7s

  [20414/20519] intraday_9895.csv.gz  in=475,135,397 out=113,176,626 elapsed=281.7s

  [20415/20519] intraday_9893.csv.gz  in=475,149,874 out=113,176,626 elapsed=281.7s

  [20416/20519] intraday_9896.csv.gz  in=475,164,570 out=113,176,626 elapsed=281.7s

  [20417/20519] intraday_9897.csv.gz  in=475,178,423 out=113,176,626 elapsed=281.8s

  [20418/20519] intraday_9898.csv.gz  in=475,190,418 out=113,176,626 elapsed=281.8s

  [20419/20519] intraday_9899.csv.gz  in=475,204,260 out=113,176,626 elapsed=281.8s

  [20420/20519] intraday_9900.csv.gz  in=475,219,793 out=113,176,626 elapsed=281.8s

  [20421/20519] intraday_9901.csv.gz  in=475,230,347 out=113,176,626 elapsed=281.8s

  [20422/20519] intraday_9902.csv.gz  in=475,243,389 out=113,176,626 elapsed=281.8s

  [20423/20519] intraday_9903.csv.gz  in=475,256,584 out=113,176,626 elapsed=281.8s

  [20424/20519] intraday_9905.csv.gz  in=475,269,306 out=113,176,626 elapsed=281.8s

  [20425/20519] intraday_9904.csv.gz  in=475,285,854 out=113,176,626 elapsed=281.8s

  [20426/20519] intraday_9907.csv.gz  in=475,300,771 out=113,176,626 elapsed=281.8s

  [20427/20519] intraday_9906.csv.gz  in=475,311,518 out=113,176,626 elapsed=281.8s

  [20428/20519] intraday_9908.csv.gz  in=475,325,222 out=113,176,626 elapsed=281.9s

  [20429/20519] intraday_9909.csv.gz  in=475,339,657 out=113,176,626 elapsed=281.9s

  [20430/20519] intraday_9912.csv.gz  in=475,351,830 out=113,176,626 elapsed=281.9s

  [20431/20519] intraday_9911.csv.gz  in=475,364,548 out=113,176,626 elapsed=281.9s

  [20432/20519] intraday_9913.csv.gz  in=475,375,688 out=113,176,626 elapsed=281.9s

  [20433/20519] intraday_9910.csv.gz  in=475,389,243 out=113,176,626 elapsed=281.9s

  [20434/20519] intraday_9915.csv.gz  in=475,399,348 out=113,176,626 elapsed=282.0s

  [20435/20519] intraday_9916.csv.gz  in=475,414,096 out=113,176,626 elapsed=282.0s

  [20436/20519] intraday_9914.csv.gz  in=475,425,862 out=113,176,626 elapsed=282.0s

  [20437/20519] intraday_9917.csv.gz  in=475,441,792 out=113,176,626 elapsed=282.0s

  [20438/20519] intraday_9918.csv.gz  in=475,454,874 out=113,176,626 elapsed=282.0s

  [20439/20519] intraday_9919.csv.gz  in=475,466,173 out=113,176,626 elapsed=282.0s

  [20440/20519] intraday_9920.csv.gz  in=475,477,295 out=113,176,626 elapsed=282.1s

  [20441/20519] intraday_9921.csv.gz  in=475,489,446 out=113,176,626 elapsed=282.1s

  [20442/20519] intraday_9922.csv.gz  in=475,503,624 out=113,176,626 elapsed=282.1s

  [20443/20519] intraday_9923.csv.gz  in=475,514,713 out=113,176,626 elapsed=282.1s

  [20444/20519] intraday_9924.csv.gz  in=475,527,398 out=113,176,626 elapsed=282.1s

  [20445/20519] intraday_9925.csv.gz  in=475,538,360 out=113,176,626 elapsed=282.1s

  [20446/20519] intraday_9927.csv.gz  in=475,549,586 out=113,176,626 elapsed=282.1s

  [20447/20519] intraday_9926.csv.gz  in=475,576,161 out=113,176,626 elapsed=282.1s

  [20448/20519] intraday_9928.csv.gz  in=475,587,339 out=113,176,626 elapsed=282.1s

  [20449/20519] intraday_9929.csv.gz  in=475,600,742 out=113,176,626 elapsed=282.1s

  [20450/20519] intraday_9930.csv.gz  in=475,612,339 out=113,176,626 elapsed=282.1s

  [20451/20519] intraday_9931.csv.gz  in=475,626,291 out=113,176,626 elapsed=282.1s

  [20452/20519] intraday_9932.csv.gz  in=475,639,007 out=113,176,626 elapsed=282.2s

  [20453/20519] intraday_9933.csv.gz  in=475,649,740 out=113,176,626 elapsed=282.2s

  [20454/20519] intraday_9934.csv.gz  in=475,661,717 out=113,176,626 elapsed=282.2s

  [20455/20519] intraday_9936.csv.gz  in=475,672,503 out=113,176,626 elapsed=282.2s

  [20456/20519] intraday_9935.csv.gz  in=475,684,230 out=113,176,626 elapsed=282.2s

  [20457/20519] intraday_9937.csv.gz  in=475,695,238 out=113,176,626 elapsed=282.2s

  [20458/20519] intraday_9938.csv.gz  in=475,706,208 out=113,176,626 elapsed=282.2s

  [20459/20519] intraday_9940.csv.gz  in=475,719,795 out=113,176,626 elapsed=282.2s

  [20460/20519] intraday_9941.csv.gz  in=475,731,792 out=113,176,626 elapsed=282.2s

  [20461/20519] intraday_9942.csv.gz  in=475,746,252 out=113,176,626 elapsed=282.2s

  [20462/20519] intraday_9939.csv.gz  in=475,758,201 out=113,176,626 elapsed=282.2s

  [20463/20519] intraday_9945.csv.gz  in=475,769,182 out=113,176,626 elapsed=282.3s

  [20464/20519] intraday_9944.csv.gz  in=475,781,739 out=113,176,626 elapsed=282.3s

  [20465/20519] intraday_9946.csv.gz  in=475,793,615 out=113,176,626 elapsed=282.3s

  [20466/20519] intraday_9943.csv.gz  in=475,807,092 out=113,176,626 elapsed=282.3s

  [20467/20519] intraday_9949.csv.gz  in=475,819,590 out=113,176,626 elapsed=282.3s

  [20468/20519] intraday_9947.csv.gz  in=475,831,882 out=113,176,626 elapsed=282.3s

  [20469/20519] intraday_9948.csv.gz  in=475,845,945 out=113,176,626 elapsed=282.3s

  [20470/20519] intraday_9950.csv.gz  in=475,857,332 out=113,176,626 elapsed=282.3s

  [20471/20519] intraday_9952.csv.gz  in=475,867,166 out=113,176,626 elapsed=282.3s

  [20472/20519] intraday_9951.csv.gz  in=475,878,825 out=113,176,626 elapsed=282.4s

  [20473/20519] intraday_9954.csv.gz  in=475,891,858 out=113,176,626 elapsed=282.4s

  [20474/20519] intraday_9953.csv.gz  in=475,911,069 out=113,176,626 elapsed=282.4s

  [20475/20519] intraday_9955.csv.gz  in=475,925,942 out=113,176,626 elapsed=282.4s

  [20476/20519] intraday_9957.csv.gz  in=475,938,363 out=113,176,626 elapsed=282.4s

  [20477/20519] intraday_9956.csv.gz  in=475,951,780 out=113,176,626 elapsed=282.4s

  [20478/20519] intraday_9959.csv.gz  in=475,964,738 out=113,176,626 elapsed=282.4s

  [20479/20519] intraday_9958.csv.gz  in=475,974,534 out=113,176,626 elapsed=282.4s

  [20480/20519] intraday_9961.csv.gz  in=475,988,663 out=113,176,626 elapsed=282.4s

  [20481/20519] intraday_9963.csv.gz  in=476,001,382 out=113,176,626 elapsed=282.4s

  [20482/20519] intraday_9960.csv.gz  in=476,014,218 out=113,176,626 elapsed=282.4s

  [20483/20519] intraday_9962.csv.gz  in=476,026,616 out=113,176,626 elapsed=282.4s

  [20484/20519] intraday_9964.csv.gz  in=476,037,755 out=113,176,626 elapsed=282.5s

  [20485/20519] intraday_9966.csv.gz  in=476,048,803 out=113,176,626 elapsed=282.5s

  [20486/20519] intraday_9967.csv.gz  in=476,060,759 out=113,176,626 elapsed=282.5s

  [20487/20519] intraday_9965.csv.gz  in=476,074,409 out=113,176,626 elapsed=282.5s

  [20488/20519] intraday_9969.csv.gz  in=476,083,564 out=113,176,626 elapsed=282.5s

  [20489/20519] intraday_9968.csv.gz  in=476,095,123 out=113,176,626 elapsed=282.5s

  [20490/20519] intraday_9970.csv.gz  in=476,105,676 out=113,176,626 elapsed=282.5s

  [20491/20519] intraday_9971.csv.gz  in=476,132,884 out=113,176,626 elapsed=282.5s

  [20492/20519] intraday_9974.csv.gz  in=476,144,802 out=113,176,626 elapsed=282.6s

  [20493/20519] intraday_9975.csv.gz  in=476,155,763 out=113,176,626 elapsed=282.6s

  [20494/20519] intraday_9973.csv.gz  in=476,170,215 out=113,176,626 elapsed=282.6s

  [20495/20519] intraday_9972.csv.gz  in=476,188,125 out=113,176,626 elapsed=282.6s

  [20496/20519] intraday_9976.csv.gz  in=476,204,351 out=113,176,626 elapsed=282.6s

  [20497/20519] intraday_9978.csv.gz  in=476,220,519 out=113,176,626 elapsed=282.6s

  [20498/20519] intraday_9977.csv.gz  in=476,240,718 out=113,176,626 elapsed=282.6s

  [20499/20519] intraday_9979.csv.gz  in=476,251,604 out=113,176,626 elapsed=282.6s

  [20500/20519] intraday_9980.csv.gz  in=476,263,255 out=113,176,626 elapsed=282.6s

  [20501/20519] intraday_9981.csv.gz  in=476,276,571 out=113,176,626 elapsed=282.6s

  [20502/20519] intraday_9982.csv.gz  in=476,289,891 out=113,176,626 elapsed=282.7s

  [20503/20519] intraday_9983.csv.gz  in=476,302,298 out=113,176,626 elapsed=282.7s

  [20504/20519] intraday_9984.csv.gz  in=476,315,983 out=113,176,626 elapsed=282.7s

  [20505/20519] intraday_9985.csv.gz  in=476,328,345 out=113,176,626 elapsed=282.7s

  [20506/20519] intraday_9986.csv.gz  in=476,339,953 out=113,176,626 elapsed=282.7s

  [20507/20519] intraday_9988.csv.gz  in=476,351,505 out=113,176,626 elapsed=282.7s

  [20508/20519] intraday_9987.csv.gz  in=476,364,694 out=113,176,626 elapsed=282.7s

  [20509/20519] intraday_9990.csv.gz  in=476,377,071 out=113,176,626 elapsed=282.7s

  [20510/20519] intraday_9989.csv.gz  in=476,388,093 out=113,176,626 elapsed=282.7s

  [20511/20519] intraday_9991.csv.gz  in=476,404,809 out=113,176,626 elapsed=282.7s

  [20512/20519] intraday_9994.csv.gz  in=476,415,421 out=113,176,626 elapsed=282.7s

  [20513/20519] intraday_9992.csv.gz  in=476,428,047 out=113,176,626 elapsed=282.8s

  [20514/20519] intraday_9993.csv.gz  in=476,442,539 out=113,176,626 elapsed=282.8s

  [20515/20519] intraday_9995.csv.gz  in=476,458,424 out=113,176,626 elapsed=282.8s

  [20516/20519] intraday_9996.csv.gz  in=476,470,090 out=113,176,626 elapsed=282.8s

  [20517/20519] intraday_9998.csv.gz  in=476,483,421 out=113,176,626 elapsed=282.8s

  [20518/20519] intraday_9997.csv.gz  in=476,495,820 out=113,176,626 elapsed=282.8s

  [20519/20519] intraday_9999.csv.gz  in=476,510,903 out=113,176,626 elapsed=282.8s

✅ DONE  in=476,510,903 → out=113,176,626  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 295.3s

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [20]:
def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,      # лишено для сумісності виклику
    *,
    max_workers: int = 4,
) -> pd.DataFrame:
    """Денні open (перший бар 09:30–09:35) і close (останній бар 15:55–15:59).

    Раніше кожен відібраний рядок проходив через itertuples + оновлення python-словника;
    тепер редукція повністю векторна (sort + drop_duplicates у pyarrow/pandas).
    Клітинка 19 уже рахує це за один прохід — ця функція лишається як самостійний шлях.
    """
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    open_parts, close_parts = [], []
    lock = threading.Lock()

    def _handle(path):
        reader = _open_intraday_csv(path, 64 << 20)
        lo, lc = [], []
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            o_df, c_df = _oc_from_table(pa.Table.from_batches([rb]))
            if len(o_df):
                lo.append(o_df)
            if len(c_df):
                lc.append(c_df)
        with lock:
            open_parts.extend(lo)
            close_parts.extend(lc)

    if max_workers and max_workers > 1:
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            list(ex.map(_handle, files))
    else:
        for p in files:
            _handle(p)

    out = _finalize_oc(open_parts, close_parts)

    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)
    return out

In [21]:
# oc.parquet уже побудовано в клітинці 19 (той самий прохід по файлах).
# Перебудовуємо лише якщо його немає.
_oc_path = str(WORK_DIR / "oc.parquet")
if os.path.exists(_oc_path):
    df_oc = pd.read_parquet(_oc_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(BATCH_DIR), out_path=_oc_path)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [22]:
import os
import gc
import time
import pandas as pd
import numpy as np

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def _prep_oc_prev_close(df_oc: pd.DataFrame) -> pd.DataFrame:
    """['ticker','date','open','prev_close','same_day_close'], date — звичайний рядок 'YYYY-MM-DD'.

    'prev_close' — close ПОПЕРЕДНЬОГО торгового дня (до 16:01).
    'same_day_close' — close ЦЬОГО Ж дня (від 16:01, коли сесія вже
    закрилась о 16:00 і референс-клоуз має перерахуватись на
    сьогоднішній)."""
    oc = df_oc[["ticker", "date", "open", "close"]].copy()
    oc["ticker"] = oc["ticker"].astype(str)
    oc["date"] = oc["date"].astype(str).str.slice(0, 10)
    oc = oc.sort_values(["ticker", "date"], kind="stable")
    oc["prev_close"] = oc.groupby("ticker", sort=False)["close"].shift(1)
    oc = oc.rename(columns={"close": "same_day_close"})
    return oc[["ticker", "date", "open", "prev_close", "same_day_close"]].reset_index(drop=True)


def _rebase_prev_close_after_session_close(df: pd.DataFrame,
                                           dt_col: str = "dt",
                                           prev_close_col: str = "prev_close",
                                           same_day_close_col: str = "same_day_close",
                                           close_boundary: str = "16:01") -> "pd.Series":
    """Від close_boundary (16:01, бо сесія закривається о 16:00) референс-клоуз
    кожного стака перераховується на клоуз ЦЬОГО Ж дня замість
    вчорашнього (інакше з 16:01 до півночі все й далі рахувалось би
    відносно вчорашнього клоуза). Час береться зрізом рядка 'dt'
    (без парсингу дат, як і решта пайплайну)."""
    time_str = df[dt_col].astype(str).str.slice(11, 16)
    after_close = time_str >= close_boundary
    return np.where(after_close, df[same_day_close_col], df[prev_close_col])


def _date_from_dt(s: pd.Series) -> pd.Series:
    """'YYYY-MM-DD' з 'dt'. Для рядкового dt це зріз (C-рівень), без парсингу дат."""
    if pd.api.types.is_string_dtype(s) or s.dtype == object:
        return s.astype(str).str.slice(0, 10)
    return s.dt.strftime("%Y-%m-%d")


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame,
                                        _oc_prepared: Optional[pd.DataFrame] = None,
                                        sort_out: bool = False) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' — референс-клоуз,
    відносно якого рахується Stack%.
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']

    Референс-клоуз перераховується о 16:01: до цього часу — клоуз попереднього
    дня, від 16:01 (сесія вже закрилась о 16:00) — клоуз ЦЬОГО Ж дня. Інакше з
    16:01 до півночі рядки й далі рахувались б відносно вчорашнього клоуза.

    Прискорення проти попередньої версії:
      - 'dt' лишається рядком: ні pd.to_datetime, ні .dt.date (це були python-об'єкти
        на кожен рядок — найдорожча операція в усьому пайплайні);
      - prev_close рахується ОДИН раз (передається через _oc_prepared), а не на кожен батч;
      - без per-batch sort_values (фінальне сортування робить клітинка 47).
    """
    right = _oc_prepared if _oc_prepared is not None else _prep_oc_prev_close(df_oc)
    out = df_intraday
    out = out[out["dt"].notna()]
    out = out.assign(date=_date_from_dt(out["dt"]))
    out = out.merge(right, on=["ticker", "date"], how="left")
    out["prev_close"] = _rebase_prev_close_after_session_close(out)
    out = out.drop(columns=["same_day_close"])
    if sort_out:
        out = out.sort_values(["ticker", "dt"], kind="stable").reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    sort_out: bool = False,
):
    """
    Читає великий Parquet батчами і мерджить денні open/prev_close з oc.parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    df_oc = pd.read_parquet(oc_parquet_path)
    missing = {"ticker", "date", "open", "close"} - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")
    oc_prepared = _prep_oc_prev_close(df_oc)      # рахуємо ОДИН раз, не на кожен батч

    if os.path.exists(out_path):
        os.remove(out_path)
    if not out_path.endswith((".csv", ".gz", ".parquet")):
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0

    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}", flush=True)

    for batch_idx, batch in enumerate(pf.iter_batches(batch_size=batch_rows, columns=cols), 1):
        df_batch = batch.to_pandas()
        df_enriched = enrich_with_day_open_and_prev_close(
            df_batch, None, _oc_prepared=oc_prepared, sort_out=sort_out)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched, preserve_index=False)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            df_enriched.to_csv(
                out_path, index=False, mode="a", header=(total_rows == 0),
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_enriched)
        if batch_idx % log_every_batches == 0:
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s", flush=True)


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [23]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
# print("Результат у файлі:", out_path)

In [24]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    Обчислення в numpy (без проміжних pandas-Series і .replace), без gc на кожен батч.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  "
          f"batch_rows≈{batch_rows:,}  using={value_col}", flush=True)

    for batches, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for c in ("prev_close", value_col):
            if c not in df.columns:
                raise KeyError(f"У вхідному файлі немає колонки '{c}'.")

        num = pd.to_numeric(df[value_col], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0   # 0 → NaN, без ділення на 0
        if round_to is not None:
            pct = np.round(pct, int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s", flush=True)
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [25]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
# print("Готово:", out_path)

In [26]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [27]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [28]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    df = pq.read_table(path).to_pandas()
    inv = {c.strip().lower(): c for c in df.columns}

    has_api = ("x_ticker" in inv) and ("y_ticker" in inv)
    has_direct = ("ticker" in inv) and ("bench" in inv)
    if not (has_api or has_direct):
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={inv["x_ticker"]: "ticker", inv["y_ticker"]: "bench"})
    else:
        df = df.rename(columns={inv["ticker"]: "ticker", inv["bench"]: "bench"})

    for c in ("corr", "beta"):
        if c in inv:
            df = df.rename(columns={inv[c]: c})
        else:
            df[c] = pd.NA

    df = df[["ticker", "bench", "corr", "beta"]].copy()
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"] = df["bench"].astype(str).str.strip().str.upper()
    df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    return (df.sort_values(["ticker", "corr"], ascending=[True, False])
              .drop_duplicates(subset=["ticker"], keep="first")
              .reset_index(drop=True))


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), додає 'bench','corr','beta' по 'ticker'.

    Замість merge на кожен батч (+ strip/upper над мільйонами рядків) нормалізація і
    пошук у мапі йдуть по унікальних тікерах, а результат розгортається за кодами.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка — "
            "інакше bench/corr/beta були б null у всіх рядках."
        )

    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        # dtype="string" тримає bench рядковим і в батчі без жодного збігу: інакше
        # суцільний None дає pyarrow-тип null і схема розійдеться з першим батчем
        df["bench"] = pd.array(_map_by_ticker(codes, cats, m_bench, numeric=False), dtype="string")
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        cols = [c for c in df.columns if c not in ("bench", "corr", "beta")]
        if insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]]
        else:
            df = df[cols + ["bench", "corr", "beta"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path


# опціональний аліас під старе ім'я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [29]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = attach_bench_corr_beta_parquet(
#     input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
#     corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
#     out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     batch_rows=2_000_000,
#     round_decimals=4,
#     insert_before="pct_vs_prev_close",
#     compression="snappy",
# )
# print("Готово:", out_path)

In [30]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [31]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Проміжного premarket_rows_final.parquet більше не існує: bench/corr/beta
# додаються за той самий прохід, що й решта. Готовий файл — у комірці 47.

In [32]:
# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [33]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=12,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 28 тікерів (пропущено 0 по старому маніфесту) | 2026-07-19 00:00:00 → 2026-10-19 23:59:59 | interval=1 | next batch #0152 | run=5cc4b583

   workers: tickers=12, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-07-19 → 2026-10-18 (92 днів)

   📈 обробляються дні: 2026-10-19 → 2026-10-19 (1 днів)

   psutil · старт · 🧠 RAM: 693.1 MB

[10/28] ✓ IWM: 965 рядків |  35.71% | ETA 00:01

[20/28] ✓ UNG: 649 рядків |  71.43% | ETA 00:00

[28/28] ✓ XOP: 477 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 704.5 MB

💾 batch 152 → 18,909 рядків (всього 18,909 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\ETF\intraday_0152.csv.gz

   ✅ після flush · 🧠 RAM: 712.2 MB

   🔚 фінал · 🧠 RAM: 712.2 MB

🏁 Готово. Нових рядків: 18,909 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:01

In [34]:
# Один прохід по ETF-батчах: premarket-рядки + денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc_etf.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    build_oc=True,
    max_workers=4,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  files=152 workers=4

  [1/152] intraday_0004.csv.gz  in=1,760 out=1,760 elapsed=0.0s

  [2/152] intraday_0002.csv.gz  in=11,933 out=11,933 elapsed=0.1s

  [3/152] intraday_0003.csv.gz  in=20,691 out=20,691 elapsed=0.1s

  [4/152] intraday_0005.csv.gz  in=31,264 out=31,264 elapsed=0.1s

  [5/152] intraday_0006.csv.gz  in=41,355 out=41,355 elapsed=0.1s

  [6/152] intraday_0007.csv.gz  in=51,502 out=51,502 elapsed=0.2s

  [7/152] intraday_0008.csv.gz  in=62,186 out=62,186 elapsed=0.2s

  [8/152] intraday_0010.csv.gz  in=63,633 out=63,633 elapsed=0.2s

  [9/152] intraday_0009.csv.gz  in=72,207 out=72,207 elapsed=0.2s

  [10/152] intraday_0011.csv.gz  in=81,941 out=81,941 elapsed=0.2s

  [11/152] intraday_0012.csv.gz  in=91,152 out=91,152 elapsed=0.2s

  [12/152] intraday_0013.csv.gz  in=100,754 out=100,754 elapsed=0.2s

  [13/152] intraday_0014.csv.gz  in=110,387 out=110,387 elapsed=0.2s

  [14/152] intraday_0016.csv.gz  in=111,758 out=111,758 elapsed=0.2s

  [15/152] intraday_0015.csv.gz  in=120,035 out=120,035 elapsed=0.3s

  [16/152] intraday_0018.csv.gz  in=129,262 out=129,262 elapsed=0.3s

  [17/152] intraday_0017.csv.gz  in=138,578 out=138,578 elapsed=0.3s

  [18/152] intraday_0021.csv.gz  in=140,181 out=140,181 elapsed=0.3s

  [19/152] intraday_0020.csv.gz  in=148,351 out=148,351 elapsed=0.3s

  [20/152] intraday_0019.csv.gz  in=157,847 out=157,847 elapsed=0.3s

  [21/152] intraday_0023.csv.gz  in=167,662 out=167,662 elapsed=0.3s

  [22/152] intraday_0022.csv.gz  in=196,862 out=196,862 elapsed=0.3s

  [23/152] intraday_0024.csv.gz  in=218,002 out=218,002 elapsed=0.4s

  [24/152] intraday_0026.csv.gz  in=226,279 out=226,279 elapsed=0.4s

  [25/152] intraday_0027.csv.gz  in=235,077 out=235,077 elapsed=0.4s

  [26/152] intraday_0028.csv.gz  in=244,053 out=244,053 elapsed=0.4s

  [27/152] intraday_0029.csv.gz  in=252,994 out=252,994 elapsed=0.4s

  [28/152] intraday_0030.csv.gz  in=262,243 out=262,243 elapsed=0.4s

  [29/152] intraday_0031.csv.gz  in=271,145 out=271,145 elapsed=0.5s

  [30/152] intraday_0025.csv.gz  in=375,587 out=375,587 elapsed=0.5s

  [31/152] intraday_0032.csv.gz  in=384,366 out=384,366 elapsed=0.5s

  [32/152] intraday_0033.csv.gz  in=393,143 out=393,143 elapsed=0.6s

  [33/152] intraday_0034.csv.gz  in=401,796 out=401,796 elapsed=0.6s

  [34/152] intraday_0035.csv.gz  in=410,508 out=410,508 elapsed=0.6s

  [35/152] intraday_0037.csv.gz  in=419,430 out=419,430 elapsed=0.6s

  [36/152] intraday_0036.csv.gz  in=428,355 out=428,355 elapsed=0.6s

  [37/152] intraday_0038.csv.gz  in=437,237 out=437,237 elapsed=0.6s

  [38/152] intraday_0040.csv.gz  in=445,830 out=445,830 elapsed=0.6s

  [39/152] intraday_0039.csv.gz  in=453,919 out=453,919 elapsed=0.6s

  [40/152] intraday_0041.csv.gz  in=463,227 out=463,227 elapsed=0.6s

  [41/152] intraday_0043.csv.gz  in=471,222 out=471,222 elapsed=0.6s

  [42/152] intraday_0042.csv.gz  in=479,401 out=479,401 elapsed=0.7s

  [43/152] intraday_0045.csv.gz  in=486,582 out=486,582 elapsed=0.9s

  [44/152] intraday_0044.csv.gz  in=495,099 out=495,099 elapsed=0.9s

  [45/152] intraday_0001.csv.gz  in=1,082,019 out=1,082,019 elapsed=0.9s

  [46/152] intraday_0046.csv.gz  in=1,090,385 out=1,090,385 elapsed=0.9s

  [47/152] intraday_0047.csv.gz  in=1,098,733 out=1,098,733 elapsed=0.9s

  [48/152] intraday_0048.csv.gz  in=1,107,041 out=1,107,041 elapsed=0.9s

  [49/152] intraday_0049.csv.gz  in=1,115,603 out=1,115,603 elapsed=0.9s

  [50/152] intraday_0050.csv.gz  in=1,123,880 out=1,123,880 elapsed=1.0s

  [51/152] intraday_0051.csv.gz  in=1,132,076 out=1,132,076 elapsed=1.0s

  [52/152] intraday_0052.csv.gz  in=1,140,350 out=1,140,350 elapsed=1.0s

  [53/152] intraday_0053.csv.gz  in=1,148,364 out=1,148,364 elapsed=1.0s

  [54/152] intraday_0054.csv.gz  in=1,156,344 out=1,156,344 elapsed=1.0s

  [55/152] intraday_0056.csv.gz  in=1,164,562 out=1,164,562 elapsed=1.0s

  [56/152] intraday_0058.csv.gz  in=1,172,958 out=1,172,958 elapsed=1.0s

  [57/152] intraday_0057.csv.gz  in=1,181,781 out=1,181,781 elapsed=1.0s

  [58/152] intraday_0059.csv.gz  in=1,189,748 out=1,189,748 elapsed=1.1s

  [59/152] intraday_0060.csv.gz  in=1,197,814 out=1,197,814 elapsed=1.1s

  [60/152] intraday_0061.csv.gz  in=1,206,064 out=1,206,064 elapsed=1.1s

  [61/152] intraday_0062.csv.gz  in=1,214,193 out=1,214,193 elapsed=1.1s

  [62/152] intraday_0064.csv.gz  in=1,222,415 out=1,222,415 elapsed=1.1s

  [63/152] intraday_0063.csv.gz  in=1,230,741 out=1,230,741 elapsed=1.1s

  [64/152] intraday_0066.csv.gz  in=1,238,523 out=1,238,523 elapsed=1.2s

  [65/152] intraday_0065.csv.gz  in=1,246,888 out=1,246,888 elapsed=1.2s

  [66/152] intraday_0067.csv.gz  in=1,255,145 out=1,255,145 elapsed=1.2s

  [67/152] intraday_0055.csv.gz  in=1,368,954 out=1,368,954 elapsed=1.2s

  [68/152] intraday_0068.csv.gz  in=1,377,472 out=1,377,472 elapsed=1.2s

  [69/152] intraday_0072.csv.gz  in=1,394,819 out=1,394,819 elapsed=1.3s

  [70/152] intraday_0070.csv.gz  in=1,412,403 out=1,412,403 elapsed=1.3s

  [71/152] intraday_0071.csv.gz  in=1,430,041 out=1,430,041 elapsed=1.3s

  [72/152] intraday_0073.csv.gz  in=1,447,121 out=1,447,121 elapsed=1.3s

  [73/152] intraday_0074.csv.gz  in=1,464,856 out=1,464,856 elapsed=1.3s

  [74/152] intraday_0075.csv.gz  in=1,482,239 out=1,482,239 elapsed=1.4s

  [75/152] intraday_0077.csv.gz  in=1,484,607 out=1,484,607 elapsed=1.4s

  [76/152] intraday_0076.csv.gz  in=1,501,364 out=1,501,364 elapsed=1.4s

  [77/152] intraday_0078.csv.gz  in=1,518,960 out=1,518,960 elapsed=1.4s

  [78/152] intraday_0079.csv.gz  in=1,535,445 out=1,535,445 elapsed=1.4s

  [79/152] intraday_0080.csv.gz  in=1,552,382 out=1,552,382 elapsed=1.4s

  [80/152] intraday_0082.csv.gz  in=1,569,251 out=1,569,251 elapsed=1.4s

  [81/152] intraday_0081.csv.gz  in=1,586,413 out=1,586,413 elapsed=1.5s

  [82/152] intraday_0083.csv.gz  in=1,604,362 out=1,604,362 elapsed=1.5s

  [83/152] intraday_0084.csv.gz  in=1,621,662 out=1,621,662 elapsed=1.5s

  [84/152] intraday_0085.csv.gz  in=1,638,586 out=1,638,586 elapsed=1.5s

  [85/152] intraday_0086.csv.gz  in=1,655,557 out=1,655,557 elapsed=1.5s

  [86/152] intraday_0087.csv.gz  in=1,672,374 out=1,672,374 elapsed=1.5s

  [87/152] intraday_0088.csv.gz  in=1,690,115 out=1,690,115 elapsed=1.5s

  [88/152] intraday_0091.csv.gz  in=1,707,230 out=1,707,230 elapsed=1.6s

  [89/152] intraday_0090.csv.gz  in=1,723,628 out=1,723,628 elapsed=1.6s

  [90/152] intraday_0093.csv.gz  in=1,723,637 out=1,723,637 elapsed=1.6s

  [91/152] intraday_0092.csv.gz  in=1,739,852 out=1,739,852 elapsed=1.6s

  [92/152] intraday_0094.csv.gz  in=1,758,814 out=1,758,814 elapsed=1.6s

  [93/152] intraday_0095.csv.gz  in=1,775,367 out=1,775,367 elapsed=1.6s

  [94/152] intraday_0096.csv.gz  in=1,793,285 out=1,793,285 elapsed=1.7s

  [95/152] intraday_0097.csv.gz  in=1,809,447 out=1,809,447 elapsed=1.7s

  [96/152] intraday_0089.csv.gz  in=1,937,006 out=1,937,006 elapsed=1.7s

  [97/152] intraday_0099.csv.gz  in=1,938,616 out=1,938,616 elapsed=1.7s

  [98/152] intraday_0098.csv.gz  in=1,954,305 out=1,954,305 elapsed=1.7s

  [99/152] intraday_0101.csv.gz  in=1,971,118 out=1,971,118 elapsed=1.8s

  [100/152] intraday_0100.csv.gz  in=1,987,634 out=1,987,634 elapsed=1.8s

  [101/152] intraday_0103.csv.gz  in=2,006,707 out=2,006,707 elapsed=1.8s

  [102/152] intraday_0105.csv.gz  in=2,025,920 out=2,025,920 elapsed=1.9s

  [103/152] intraday_0106.csv.gz  in=2,045,930 out=2,045,930 elapsed=1.9s

  [104/152] intraday_0069.csv.gz  in=2,791,183 out=2,791,183 elapsed=2.3s

  [105/152] intraday_0107.csv.gz  in=2,811,050 out=2,811,050 elapsed=2.3s

  [106/152] intraday_0102.csv.gz  in=3,043,135 out=3,043,135 elapsed=2.3s

  [107/152] intraday_0109.csv.gz  in=3,060,591 out=3,060,591 elapsed=2.3s

  [108/152] intraday_0110.csv.gz  in=3,080,313 out=3,080,313 elapsed=2.3s

  [109/152] intraday_0108.csv.gz  in=3,099,353 out=3,099,353 elapsed=2.3s

  [110/152] intraday_0112.csv.gz  in=3,101,522 out=3,101,522 elapsed=2.3s

  [111/152] intraday_0113.csv.gz  in=3,120,377 out=3,120,377 elapsed=2.5s

  [112/152] intraday_0104.csv.gz  in=3,706,603 out=3,706,603 elapsed=2.5s

  [113/152] intraday_0114.csv.gz  in=3,726,346 out=3,726,346 elapsed=2.5s

  [114/152] intraday_0115.csv.gz  in=3,745,321 out=3,745,321 elapsed=2.6s

  [115/152] intraday_0116.csv.gz  in=3,764,168 out=3,764,168 elapsed=2.6s

  [116/152] intraday_0117.csv.gz  in=3,781,344 out=3,781,344 elapsed=2.6s

  [117/152] intraday_0118.csv.gz  in=3,799,678 out=3,799,678 elapsed=2.6s

  [118/152] intraday_0119.csv.gz  in=3,818,511 out=3,818,511 elapsed=2.7s

  [119/152] intraday_0111.csv.gz  in=4,086,695 out=4,086,695 elapsed=2.7s

  [120/152] intraday_0120.csv.gz  in=4,106,177 out=4,106,177 elapsed=2.7s

  [121/152] intraday_0121.csv.gz  in=4,125,470 out=4,125,470 elapsed=2.7s

  [122/152] intraday_0124.csv.gz  in=4,144,543 out=4,144,543 elapsed=2.8s

  [123/152] intraday_0123.csv.gz  in=4,163,269 out=4,163,269 elapsed=2.8s

  [124/152] intraday_0122.csv.gz  in=4,182,997 out=4,182,997 elapsed=2.8s

  [125/152] intraday_0125.csv.gz  in=4,201,996 out=4,201,996 elapsed=2.8s

  [126/152] intraday_0127.csv.gz  in=4,204,144 out=4,204,144 elapsed=2.8s

  [127/152] intraday_0126.csv.gz  in=4,221,902 out=4,221,902 elapsed=2.9s

  [128/152] intraday_0130.csv.gz  in=4,240,975 out=4,240,975 elapsed=2.9s

  [129/152] intraday_0129.csv.gz  in=4,260,941 out=4,260,941 elapsed=2.9s

  [130/152] intraday_0128.csv.gz  in=4,281,039 out=4,281,039 elapsed=2.9s

  [131/152] intraday_0131.csv.gz  in=4,299,863 out=4,299,863 elapsed=2.9s

  [132/152] intraday_0133.csv.gz  in=4,302,174 out=4,302,174 elapsed=2.9s

  [133/152] intraday_0132.csv.gz  in=4,319,021 out=4,319,021 elapsed=3.0s

  [134/152] intraday_0136.csv.gz  in=4,337,764 out=4,337,764 elapsed=3.0s

  [135/152] intraday_0135.csv.gz  in=4,356,466 out=4,356,466 elapsed=3.0s

  [136/152] intraday_0138.csv.gz  in=4,373,856 out=4,373,856 elapsed=3.0s

  [137/152] intraday_0134.csv.gz  in=4,393,378 out=4,393,378 elapsed=3.1s

  [138/152] intraday_0139.csv.gz  in=4,395,284 out=4,395,284 elapsed=3.1s

  [139/152] intraday_0137.csv.gz  in=4,415,162 out=4,415,162 elapsed=3.1s

  [140/152] intraday_0140.csv.gz  in=4,433,539 out=4,433,539 elapsed=3.1s

  [141/152] intraday_0143.csv.gz  in=4,453,125 out=4,453,125 elapsed=3.1s

  [142/152] intraday_0144.csv.gz  in=4,470,176 out=4,470,176 elapsed=3.2s

  [143/152] intraday_0142.csv.gz  in=4,489,358 out=4,489,358 elapsed=3.2s

  [144/152] intraday_0141.csv.gz  in=4,507,742 out=4,507,742 elapsed=3.2s

  [145/152] intraday_0145.csv.gz  in=4,509,590 out=4,509,590 elapsed=3.2s

  [146/152] intraday_0149.csv.gz  in=4,529,999 out=4,529,999 elapsed=3.2s

  [147/152] intraday_0147.csv.gz  in=4,549,075 out=4,549,075 elapsed=3.2s

  [148/152] intraday_0148.csv.gz  in=4,569,213 out=4,569,213 elapsed=3.3s

  [149/152] intraday_0151.csv.gz  in=4,571,309 out=4,571,309 elapsed=3.3s

  [150/152] intraday_0146.csv.gz  in=4,590,136 out=4,590,136 elapsed=3.3s

  [151/152] intraday_0150.csv.gz  in=4,607,463 out=4,607,463 elapsed=3.3s

  [152/152] intraday_0152.csv.gz  in=4,626,372 out=4,626,372 elapsed=3.3s

✅ DONE  in=4,626,372 → out=4,626,372  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 3.4s

In [35]:
# oc_etf.parquet уже побудовано в клітинці 34 (той самий прохід по файлах).
_oc_etf_path = str(WORK_DIR / "oc_etf.parquet")
if os.path.exists(_oc_etf_path):
    df_oc = pd.read_parquet(_oc_etf_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(ETF_DIR), out_path=_oc_etf_path)
print(df_oc.head())

  ticker        date   open  close
0   ARKK  2026-05-01  75.85  76.84
1   ARKK  2026-05-04  77.24  78.21
2   ARKK  2026-05-05  78.40  76.62
3   ARKK  2026-05-06  77.33  79.54
4   ARKK  2026-05-07  79.40  78.09

In [36]:
# Ті самі оптимізовані функції, що й у клітинці 22 — тут лише інші дефолти обгортки
# (ETF-файли замість акційних).
def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [37]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=4,626,372  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 9.2s

Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [38]:
# Та сама оптимізована add_pct_vs_prev_close_parquet із клітинки 24 —
# тут лише інші дефолти обгортки (ETF-файли, колонка Bench%).
def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",              # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [39]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=4,626,372  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 4.8s

Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [40]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий по ключах ('bench'↔'ticker', 'dt').

    Прискорення: ETF-мапа читається одним pq.read_table (лише 3 потрібні колонки)
    замість iter_batches + concat + gc; ключ 'dt' лишається рядком —
    лексикографічний порядок 'YYYY-MM-DD HH:MM:SS' збігається з хронологічним,
    тож per-row парсинг дат не потрібен (крім align_to_minute=True).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    t0 = time.time()

    # ---------- 1) Мапа з ETF-файла: (bench, dt) -> Bench% ----------
    etf_names = [f.name for f in pq.ParquetFile(etf_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    for col in ("ticker", "dt"):
        if col not in cl:
            raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    if val_col is None:
        raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

    etf_map = pq.read_table(etf_path, columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    _dt_is_str = (etf_map["dt"].dtype == object) or pd.api.types.is_string_dtype(etf_map["dt"])
    if align_to_minute or not _dt_is_str:
        etf_map["dt"] = pd.to_datetime(etf_map["dt"], errors="coerce")
        if align_to_minute:
            etf_map["dt"] = etf_map["dt"].dt.floor("T")
    else:
        etf_map["dt"] = etf_map["dt"].astype(str)

    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    # ---------- 2) Потоково проходимо базовий файл ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_path}", flush=True)
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        codes, cats = _ticker_codes(df["bench"])
        df["bench"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)

        _base_dt_is_str = (df["dt"].dtype == object) or pd.api.types.is_string_dtype(df["dt"])
        if align_to_minute or not _base_dt_is_str:
            df["dt"] = pd.to_datetime(df["dt"], errors="coerce")
            if align_to_minute:
                df["dt"] = df["dt"].dt.floor("T")
        else:
            df["dt"] = df["dt"].astype(str)

        merged = df.merge(etf_map, on=["bench", "dt"], how="left")

        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = [c for c in merged.columns if c != "Bench%"]
            pos = cols.index(insert_before)
            merged = merged[cols[:pos] + ["Bench%"] + cols[pos:]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [41]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# merge_bench_pct_from_etf(
#     base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
#     out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
#     batch_rows=2_000_000,
#     align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
#     round_decimals=2,
#     insert_before=None,          # або, наприклад, "pct_vs_prev_close"
#     compression="snappy",
# )

In [42]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


_REPORT_FAILS = {"n": 0}
_GAP_FAILS = {"n": 0}


def _datum_request_retry(endpoint, params, *, max_retries=6, backoff=0.5):
    """Повторює запит при 429/мережевих збоях з наростаючою паузою.
    Вичерпавши спроби — кидає останній виняток."""
    import random, time
    for attempt in range(max_retries + 1):
        try:
            return DatumApi.data_request(endpoint, params)
        except Exception:
            if attempt == max_retries:
                raise
            time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }
        reports_df = _datum_request_retry("/reports", params)
        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)
    except Exception as e:
        _REPORT_FAILS["n"] += 1
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20,
                            max_workers=8, max_fail_ratio=0.15):
    # 16 потоків без пауз давали суцільні 429; з retry вистачає меншого числа
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []
    _REPORT_FAILS["n"] = 0

    # Ті самі репорти вже завантажила комірка 11. Беремо їх лише коли вікно,
    # last_n_reports і набір тикерів збігаються; інакше — звичайний фетч.
    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    if (_c.get("window") == (str(start_date)[:10], str(end_date)[:10])
            and _c.get("last_n_reports") == int(last_n_reports)
            and set(tickers) <= _c.get("tickers", set())):
        _r = _c["reports"].rename(columns={"date": "report_date"})
        _r = (_r[_r["ticker"].isin(tickers)]
                .drop_duplicates(["ticker", "report_date"]).reset_index(drop=True))
        print(f"Reports: узято з кешу комірки 11 ({len(_r)} рядків), фетч пропущено")
        return _r, _r.groupby("ticker")["report_date"].apply(set).to_dict()

    def fetch(t):
        return get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Reports"):
            rep = f.result()
            if rep is not None and not rep.empty:
                parts.append(rep)

    if tickers and _REPORT_FAILS["n"] / len(tickers) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_REPORT_FAILS['n']} з {len(tickers)} тикерів "
            f"({_REPORT_FAILS['n'] / len(tickers) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Репорти вийшли б неповними."
        )

    if not parts:
        return pd.DataFrame(columns=["ticker", "report_date"]), {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map,
                                           max_workers=8, max_fail_ratio=0.15):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    _GAP_FAILS["n"] = 0
    _GAP_FAILS["empty"] = 0

    # Кеш комірки 11 беремо для КОЖНОГО тикера, що в ньому є, а докачуємо лише відсутні. Раніше кеш
    # діяв за умови set(tickers) <= cache: один зайвий тикер викидав увесь кеш, і ~7000 тикерів
    # перекачувались наново; порожні відповіді API при цьому мовчки губились (fetch -> None без
    # лічильника збою) - так sigma лишилась лише у ~1200 тикерів (алфавітний хвіст STC..ZYME).
    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    cached_part = None
    to_fetch = tickers
    if _c.get("window") == (str(start_date)[:10], str(end_date)[:10]) and "gaps" in _c:
        _have = set(_c.get("tickers", set()))
        _use = [t for t in tickers if t in _have]
        _g = _c["gaps"]
        _g = _g[_g["ticker"].isin(_use)].copy()
        _rep = pd.DataFrame([(t, d) for t, ds in (report_days_map or {}).items() for d in ds],
                            columns=["ticker", "date"])
        if len(_rep):
            _g = _g.merge(_rep.assign(_r=1), on=["ticker", "date"], how="left")
            _g = _g[_g["_r"].isna()].drop(columns="_r")
        cached_part = _g.reset_index(drop=True)
        to_fetch = [t for t in tickers if t not in _have]
        print(f"Gaps: з кешу комірки 11 {len(_use)} тикерів ({len(cached_part)} рядків), докачуємо {len(to_fetch)}")
        if not to_fetch:
            return cached_part

    def fetch(t):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }
        try:
            df_gap = _datum_request_retry("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                # порожня відповідь під лімітом виглядає так само, як тикер без гепів - перепитуємо раз
                import time
                time.sleep(1.0)
                df_gap = _datum_request_retry("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                _GAP_FAILS["empty"] = _GAP_FAILS.get("empty", 0) + 1
                return None

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                return None

            out = df_gap.copy()
            out["ticker"] = out["ticker"].astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            return out if not out.empty else None
        except Exception as e:
            _GAP_FAILS["n"] += 1
            print(f"Gap fetch failed for {t}: {e}")
            return None

    all_results = []
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in to_fetch}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Gaps (ex-reports)"):
            result = f.result()
            if result is not None:
                all_results.append(result)

    _bad = _GAP_FAILS["n"] + _GAP_FAILS.get("empty", 0)
    if to_fetch and _bad / len(to_fetch) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив/повернув порожньо на {_bad} з {len(to_fetch)} тикерів "
            f"({_bad / len(to_fetch) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Гепи вийшли б неповними."
        )

    if cached_part is not None:
        all_results.append(cached_part)
    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=None,
):
    """Rolling std по попередньому вікну з обрізанням хвостів на квантилі cap_q.

    Раніше це був rolling(...).apply(python_func) — окремий виклик Python на кожне
    вікно кожного тікера. Тепер вікна будуються через sliding_window_view і квантиль/
    clip/std рахуються одразу по всій матриці вікон групи (чисто numpy).
    Результат збігається з попередньою реалізацією до 1e-12.
    """
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col], kind="stable").copy()
    col = f"{value_col}_sigma_{window}d_cap"

    # Рідкісний випадок min_periods != window має іншу семантику (часткові вікна) —
    # там лишаємо стару, повільну, але точну реалізацію.
    if min_periods != window:
        def compute_sigma(s):
            x = s.shift(1)

            def f(arr):
                arr = arr[~np.isnan(arr)]
                if len(arr) < min_periods:
                    return np.nan
                cap = np.quantile(np.abs(arr), cap_q)
                arr_capped = np.clip(arr, -cap, cap)
                return np.std(arr_capped, ddof=1)

            return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

        out[col] = out.groupby(group_col)[value_col].transform(compute_sigma)
        return out

    vals = pd.to_numeric(out[value_col], errors="coerce").to_numpy(dtype="float64")
    codes, _ = pd.factorize(out[group_col], sort=False)
    res = np.full(vals.shape, np.nan)

    order = np.argsort(codes, kind="stable")
    bounds = np.flatnonzero(np.diff(codes[order])) + 1
    for sl in np.split(order, bounds):
        n = sl.size
        if n <= window:
            continue
        x = vals[sl]
        # вікно з ПОПЕРЕДНІХ значень (еквівалент shift(1) у старій версії)
        w = np.lib.stride_tricks.sliding_window_view(x[:-1], window)   # (n-window, window)
        cap = np.quantile(np.abs(w), cap_q, axis=1, keepdims=True)
        res[sl[window:]] = np.clip(w, -cap, cap).std(axis=1, ddof=1)

    out[col] = res
    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

# 3) Rolling sigma
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

# 4) Добір sigma для тикерів, що випали: гепи з oc.parquet (open / попередній close - те саме, з чого
# рахується Stack%), ті самі дні репортів, те саме вікно і та сама формула.
_all_tk = set(TICKERS["ticker"].dropna().astype(str).str.upper())
_missing = sorted(_all_tk - set(std_by_ticker["ticker"]))
print(f"Sigma з API-гепів: {len(std_by_ticker)} з {len(_all_tk)} тикерів, бракує {len(_missing)}")
if _missing:
    _oc = pd.read_parquet(WORK_DIR / "oc.parquet", columns=["ticker", "date", "open", "close"])
    _oc["ticker"] = _oc["ticker"].astype(str).str.upper()
    _oc["date"] = pd.to_datetime(_oc["date"], errors="coerce").dt.strftime("%Y-%m-%d")
    _oc = _oc.dropna(subset=["date"]).sort_values(["ticker", "date"], kind="stable")
    _oc["gap"] = (pd.to_numeric(_oc["open"], errors="coerce")
                  / pd.to_numeric(_oc.groupby("ticker")["close"].shift(1), errors="coerce") - 1.0) * 100.0
    _fb = _oc[_oc["ticker"].isin(_missing)
              & (_oc["date"] >= str(start_date_str)[:10]) & (_oc["date"] <= str(end_date_str)[:10])]
    _fb = _fb.replace([np.inf, -np.inf], np.nan).dropna(subset=["gap"])
    _rep_fb = pd.DataFrame([(t, d) for t, ds in report_days_map.items() for d in ds], columns=["ticker", "date"])
    if len(_rep_fb):
        _fb = _fb.merge(_rep_fb.assign(_r=1), on=["ticker", "date"], how="left")
        _fb = _fb[_fb["_r"].isna()].drop(columns="_r")
    _fb_sigma = add_rolling_sigma_cap(_fb[["ticker", "date", "gap"]], value_col="gap", window=20,
                                      group_col="ticker", date_col="date", cap_q=0.8, min_periods=20)
    _fb_std = (_fb_sigma.dropna(subset=[sigma_col]).sort_values(["ticker", "date"])
               .groupby("ticker", as_index=False).tail(1)[["ticker", sigma_col]]
               .rename(columns={sigma_col: "sigma"}))
    std_by_ticker = pd.concat([std_by_ticker, _fb_std], ignore_index=True).drop_duplicates("ticker", keep="first")
    print(f"Добрано з oc.parquet: {len(_fb_std)}")

_cov = len(std_by_ticker) / max(1, len(_all_tk))
print(f"Tickers with sigma: {len(std_by_ticker)} з {len(_all_tk)} ({_cov:.1%})")
if _cov < 0.85:
    raise RuntimeError(f"sigma є лише у {_cov:.1%} тикерів - гепи вийшли неповними, final.parquet не збирати")
std_by_ticker.head()

Reports: узято з кешу комірки 11 (4089 рядків), фетч пропущено
Report rows: 4089

Gaps: з кешу комірки 11 7081 тикерів (447068 рядків), докачуємо 0
Rows in gaps (without report days): 447068

Sigma з API-гепів: 6996 з 7081 тикерів, бракує 85

Добрано з oc.parquet: 0
Tickers with sigma: 6996 з 7081 (98.8%)

  ticker     sigma
0      A  0.609382
1     AA  0.790569
2   AAAU  0.784085
3   AACG  2.890473
4   AADX  0.709086

In [43]:
std_by_ticker

     ticker     sigma
0         A  0.609382
1        AA  0.790569
2      AAAU  0.784085
3      AACG  2.890473
4      AADX  0.709086
...     ...       ...
6991   ZVOL  0.517531
6992   ZVRA  0.436579
6993    ZWS  0.684551
6994   ZYBT  2.140565
6995   ZYME  0.742990

[6996 rows x 2 columns]

In [44]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"] = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet.

    Як і в клітинці 28: нормалізація тікера і пошук у мапі йдуть по унікальних
    значеннях, а не по кожному з мільйонів рядків; per-batch merge не потрібен.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)
    sd = dict(zip(sigma_map["ticker"], sigma_map["sigma"]))

    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}", flush=True)
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["sigma"] = _map_by_ticker(codes, cats, sd, numeric=True)

        cols = [c for c in df.columns if c != "sigma"]
        if insert_before and insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["sigma"] + cols[idx:]]
        else:
            df = df[cols + ["sigma"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [45]:
def build_final_in_one_pass(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    corrbeta_parquet_path: str,
    etf_parquet_path: str,
    out_parquet_path: str,
    *,
    sigma_df=None,
    sigma_path=None,
    batch_rows: int = 2_000_000,
    round_decimals=4,
    stack_round_to=None,
    bench_round_decimals=2,
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """Один потоковий прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta
    → Bench% → sigma. Замінює merge_intraday_and_oc_to_file +
    add_pct_vs_prev_close_parquet + attach_bench_corr_beta_parquet +
    merge_bench_pct_from_etf + add_sigma_by_ticker_to_parquet.

    Результат побайтово збігається з ланцюжком; економія — у тому, що ~3 ГБ
    читаються й пишуться один раз, а не шість.
    """
    t0 = time.time()

    # ---------- side-входи: готуються ОДИН раз ----------
    oc_prepared = _prep_oc_prev_close(pq.read_table(oc_parquet_path).to_pandas())

    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка."
        )
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)
    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    etf_names = [f.name for f in pq.ParquetFile(etf_parquet_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    etf_map = pq.read_table(etf_parquet_path,
                            columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if bench_round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(bench_round_decimals)
    etf_map["dt"] = etf_map["dt"].astype(str)
    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    sig = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    m_sigma = dict(zip(sig["ticker"], sig["sigma"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    ORDER = ["ticker", "dt", "o", "h", "l", "c", "v", "date", "open", "prev_close",
             "Stack%", "bench", "corr", "beta", "Bench%", "sigma"]

    pf = pq.ParquetFile(intraday_parquet_path)
    writer = None
    total_rows = 0
    print(f"▶️ START one-pass → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # 1) день + open/prev_close (ключ — сирий ticker, як у ланцюжку)
        df = df[df["dt"].notna()]
        df = df.assign(date=_date_from_dt(df["dt"]))
        df = df.merge(oc_prepared, on=["ticker", "date"], how="left")
        df["prev_close"] = _rebase_prev_close_after_session_close(df)

        # 2) Stack%
        num = pd.to_numeric(df["o"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0
        if stack_round_to is not None:
            pct = np.round(pct, int(stack_round_to))
        df["Stack%"] = pct

        # 3) bench/corr/beta (тут ticker нормалізується — як у ланцюжку)
        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["bench"] = _map_by_ticker(codes, cats, m_bench, numeric=False)
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        # 4) sigma — теж по codes/cats, тому рахуємо ДО мерджа
        df["sigma"] = _map_by_ticker(codes, cats, m_sigma, numeric=True)

        # 5) Bench% по (bench, dt); bench лишається object для мерджа
        df["dt"] = df["dt"].astype(str)
        df = df.merge(etf_map, on=["bench", "dt"], how="left")

        # string-dtype один раз наприкінці: тримає тип bench стабільним між батчами
        df["bench"] = pd.array(df["bench"], dtype="string")

        df = df[[c for c in ORDER if c in df.columns]]
        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,} elapsed={time.time()-t0:,.1f}s", flush=True)
        del df, table, batch
        gc.collect()

    if writer is not None:
        writer.close()
    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path} in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path

In [46]:
# std_by_ticker columns: ['ticker', 'sigma']
# Один прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta → Bench% → sigma.
# Замінює комірки 23, 25, 29, 41 і колишній add_sigma_by_ticker_to_parquet.
sigma_out_path = build_final_in_one_pass(
    intraday_parquet_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_parquet_path=str(WORK_DIR / "oc.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    etf_parquet_path=str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    sigma_df=std_by_ticker,
    batch_rows=2_000_000,
    round_decimals=4,
    bench_round_decimals=2,
    compression="snappy",
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START one-pass → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000 elapsed=46.8s

[batch   10] rows=20,000,000 elapsed=84.3s

[batch   15] rows=30,000,000 elapsed=122.6s

[batch   20] rows=40,000,000 elapsed=159.9s

[batch   25] rows=50,000,000 elapsed=196.6s

[batch   30] rows=60,000,000 elapsed=233.9s

[batch   35] rows=70,000,000 elapsed=270.5s

[batch   40] rows=80,000,000 elapsed=308.4s

[batch   45] rows=90,000,000 elapsed=346.4s

[batch   50] rows=100,000,000 elapsed=385.0s

[batch   55] rows=110,000,000 elapsed=423.3s

✅ DONE rows=113,176,626 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet in 435.6s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 6996
tickers checked in parquet: 6994
max |file_sigma - expected_sigma|: 0.0

In [47]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 113,176,626
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 634/21150
NaN у 'corr' (у прев'ю): 634/21150
NaN у 'beta' (у прев'ю): 634/21150

Перші рядки:

      ticker                   dt           o           h           l           c          v        date    open  prev_close        Stack% bench    corr    beta  Bench%     sigma
0       ABTS  2026-07-19 22:45:00    1.190000    1.190000    1.190000    1.190000        1.0  2026-07-19     NaN         NaN           NaN   XRT  0.3771  1.3166     NaN  3.135848
1       ABTS  2026-07-20 04:37:00    1.150000    1.150000    1.150000    1.150000      828.0  2026-07-20    1.22        1.23 -6.504067e+00   XRT  0.3771  1.3166     NaN  3.135848
2       ABTS  2026-07-20 05:09:00    1.150000    1.150000    1.150000    1.150000      300.0  2026-07-20    1.22        1.23 -6.504067e+00   XRT  0.3771  1.3166     NaN  3.135848
3       ABTS  2026-07-20 09:30:00    1.220000    1.220000    1.220000    1.220000      245.0  2026-07-20    1.22        1.23 -8.130058e-01   XRT  0.3771  1.3166   -0.66  3.135848
4       ABTS  2026-07-20 10:01:00    1.161500    1.161500    1.161500    1.161500     1349.0  2026-07-20    1.22        1.23 -5.569108e+00   XRT  0.3771  1.3166   -1.38  3.135848
5       ABTS  2026-07-20 10:22:00    1.170000    1.170000    1.150700    1.150700      999.0  2026-07-20    1.22        1.23 -4.878052e+00   XRT  0.3771  1.3166   -1.46  3.135848
6       ABTS  2026-07-20 10:44:00    1.180000    1.180000    1.180000    1.180000      100.0  2026-07-20    1.22        1.23 -4.065045e+00   XRT  0.3771  1.3166   -1.66  3.135848
7       ABTS  2026-07-20 11:23:00    1.220000    1.220000    1.220000    1.220000      290.0  2026-07-20    1.22        1.23 -8.130058e-01   XRT  0.3771  1.3166   -1.23  3.135848
8       ABTS  2026-07-20 11:46:00    1.240000    1.240000    1.240000    1.240000      100.0  2026-07-20    1.22        1.23  8.130089e-01   XRT  0.3771  1.3166   -1.22  3.135848
9       ABTS  2026-07-20 11:58:00    1.215000    1.215000    1.215000    1.215000      103.0  2026-07-20    1.22        1.23 -1.219509e+00   XRT  0.3771  1.3166   -1.31  3.135848
10      ABTS  2026-07-20 11:59:00    1.239800    1.300000    1.239800    1.250000     5899.0  2026-07-20    1.22        1.23  7.967460e-01   XRT  0.3771  1.3166   -1.36  3.135848
11      ABTS  2026-07-20 12:00:00    1.260000    1.260000    1.260000    1.260000      287.0  2026-07-20    1.22        1.23  2.439024e+00   XRT  0.3771  1.3166   -1.35  3.135848
12      ABTS  2026-07-20 12:01:00    1.220000    1.220000    1.220000    1.220000      287.0  2026-07-20    1.22        1.23 -8.130058e-01   XRT  0.3771  1.3166   -1.31  3.135848
13      ABTS  2026-07-20 12:07:00    1.250000    1.250000    1.250000    1.250000      200.0  2026-07-20    1.22        1.23  1.626016e+00   XRT  0.3771  1.3166   -1.17  3.135848
14      ABTS  2026-07-20 12:09:00    1.290000    1.290000    1.290000    1.290000      100.0  2026-07-20    1.22        1.23  4.878046e+00   XRT  0.3771  1.3166   -1.19  3.135848
15      ABTS  2026-07-20 12:10:00    1.235000    1.235000    1.235000    1.235000      100.0  2026-07-20    1.22        1.23  4.065052e-01   XRT  0.3771  1.3166   -1.17  3.135848
16      ABTS  2026-07-20 12:27:00    1.260000    1.260000    1.260000    1.260000      100.0  2026-07-20    1.22        1.23  2.439024e+00   XRT  0.3771  1.3166   -1.08  3.135848
17      ABTS  2026-07-20 12:31:00    1.280000    1.280000    1.280000    1.280000      100.0  2026-07-20    1.22        1.23  4.065038e+00   XRT  0.3771  1.3166   -1.07  3.135848
18      ABTS  2026-07-20 12:34:00    1.262600    1.262600    1.262600    1.262600     1000.0  2026-07-20    1.22        1.23  2.650402e+00   XRT  0.3771  1.3166   -1.16  3.135848
19      ABTS  2026-07-20 12:54:00    1.290000    1.290000    1.290000    1.290000      100.0  2026-07-20    1.22        1.23  4.878046e+00   XRT  0.3771  1.3166   -1.28  3.135848
20      ABTS  2026-07-20 13:16:00    1.271100    1.271100    1.271100    1.271100      100.0  2026-07-20    1.22        1.23  3.341467e+00   XRT  0.3771  1.3166   -1.56  3.135848
21      ABTS  2026-07-20 13:17:00    1.280000    1.280000    1.280000    1.280000      100.0  2026-07-20    1.22        1.23  4.065038e+00   XRT  0.3771  1.3166   -1.56  3.135848
22      ABTS  2026-07-20 13:27:00    1.260000    1.260000    1.260000    1.260000      100.0  2026-07-20    1.22        1.23  2.439024e+00   XRT  0.3771  1.3166   -1.56  3.135848
23      ABTS  2026-07-20 13:31:00    1.250000    1.250000    1.240000    1.240000      500.0  2026-07-20    1.22        1.23  1.626016e+00   XRT  0.3771  1.3166   -1.54  3.135848
24      ABTS  2026-07-20 14:03:00    1.240000    1.240000    1.240000    1.240000      100.0  2026-07-20    1.22        1.23  8.130089e-01   XRT  0.3771  1.3166   -1.31  3.135848
25      ABTS  2026-07-20 14:18:00    1.240000    1.240000    1.240000    1.240000      100.0  2026-07-20    1.22        1.23  8.130089e-01   XRT  0.3771  1.3166   -1.33  3.135848
26      ABTS  2026-07-20 14:34:00    1.240000    1.240000    1.240000    1.240000      100.0  2026-07-20    1.22        1.23  8.130089e-01   XRT  0.3771  1.3166   -1.51  3.135848
27      ABTS  2026-07-20 15:05:00    1.240000    1.240000    1.240000    1.240000      100.0  2026-07-20    1.22        1.23  8.130089e-01   XRT  0.3771  1.3166   -1.47  3.135848
28      ABTS  2026-07-20 15:36:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.22        1.23 -1.626013e+00   XRT  0.3771  1.3166   -1.60  3.135848
29      ABTS  2026-07-20 15:37:00    1.230000    1.230000    1.230000    1.230000      100.0  2026-07-20    1.22        1.23  1.550690e-06   XRT  0.3771  1.3166   -1.63  3.135848
30      ABTS  2026-07-20 15:47:00    1.210000    1.210000    1.210000    1.210000      202.0  2026-07-20    1.22        1.23 -1.626013e+00   XRT  0.3771  1.3166   -1.55  3.135848
31      ABTS  2026-07-20 15:52:00    1.210000    1.210000    1.210000    1.210000      107.0  2026-07-20    1.22        1.23 -1.626013e+00   XRT  0.3771  1.3166   -1.59  3.135848
32      ABTS  2026-07-20 15:53:00    1.210000    1.210000    1.210000    1.210000      105.0  2026-07-20    1.22        1.23 -1.626013e+00   XRT  0.3771  1.3166   -1.61  3.135848
33      ABTS  2026-07-20 15:59:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.22        1.23 -1.626013e+00   XRT  0.3771  1.3166   -1.73  3.135848
34      ABTS  2026-07-20 18:37:00    1.180000    1.180000    1.180000    1.180000      180.0  2026-07-20    1.22        1.21 -2.479343e+00   XRT  0.3771  1.3166     NaN  3.135848
35      ABVC  2026-07-20 09:30:00    1.280000    1.282300    1.280000    1.280600     1055.0  2026-07-20    1.28        1.22  4.918030e+00   XBI -0.0595 -0.1070    1.75  1.493347
36      ABVC  2026-07-20 09:49:00    1.225000    1.225000    1.220000    1.220000     4100.0  2026-07-20    1.28        1.22  4.098380e-01   XBI -0.0595 -0.1070    1.84  1.493347
37      ABVC  2026-07-20 09:51:00    1.220000    1.220000    1.220000    1.220000      100.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    1.77  1.493347
38      ABVC  2026-07-20 09:52:00    1.230000    1.230000    1.230000    1.230000      100.0  2026-07-20    1.28        1.22  8.196737e-01   XBI -0.0595 -0.1070    1.68  1.493347
39      ABVC  2026-07-20 09:55:00    1.220000    1.220000    1.220000    1.220000      100.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    1.59  1.493347
40      ABVC  2026-07-20 09:58:00    1.210000    1.210000    1.210000    1.210000      200.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    1.61  1.493347
41      ABVC  2026-07-20 09:59:00    1.219100    1.219100    1.219100    1.219100     1000.0  2026-07-20    1.28        1.22 -7.377062e-02   XBI -0.0595 -0.1070    1.57  1.493347
42      ABVC  2026-07-20 10:03:00    1.211100    1.211100    1.211100    1.211100      100.0  2026-07-20    1.28        1.22 -7.295097e-01   XBI -0.0595 -0.1070    1.18  1.493347
43      ABVC  2026-07-20 10:04:00    1.210000    1.210000    1.201200    1.201200     1802.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    1.26  1.493347
44      ABVC  2026-07-20 10:05:00    1.201200    1.201200    1.201200    1.201200      100.0  2026-07-20    1.28        1.22 -1.540983e+00   XBI -0.0595 -0.1070    1.22  1.493347
45      ABVC  2026-07-20 10:06:00    1.205000    1.205000    1.205000    1.205000     3000.0  2026-07-20    1.28        1.22 -1.229505e+00   XBI -0.0595 -0.1070    1.10  1.493347
46      ABVC  2026-07-20 10:10:00    1.200000    1.200000    1.200000    1.200000      250.0  2026-07-20    1.28        1.22 -1.639340e+00   XBI -0.0595 -0.1070    1.11  1.493347
47      ABVC  2026-07-20 10:20:00    1.210000    1.230000    1.210000    1.230000    10200.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.88  1.493347
48      ABVC  2026-07-20 10:22:00    1.220000    1.220000    1.220000    1.220000      200.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.78  1.493347
49      ABVC  2026-07-20 10:24:00    1.220000    1.220000    1.220000    1.220000     3000.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.98  1.493347
50      ABVC  2026-07-20 10:26:00    1.230000    1.238700    1.230000    1.238700      201.0  2026-07-20    1.28        1.22  8.196737e-01   XBI -0.0595 -0.1070    0.93  1.493347
51      ABVC  2026-07-20 10:27:00    1.240000    1.240000    1.230000    1.230000      690.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    1.09  1.493347
52      ABVC  2026-07-20 10:28:00    1.230000    1.230000    1.230000    1.230000      732.0  2026-07-20    1.28        1.22  8.196737e-01   XBI -0.0595 -0.1070    0.95  1.493347
53      ABVC  2026-07-20 10:29:00    1.240000    1.240000    1.230000    1.230000      425.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.93  1.493347
54      ABVC  2026-07-20 10:30:00    1.230400    1.239300    1.230000    1.239300      771.0  2026-07-20    1.28        1.22  8.524562e-01   XBI -0.0595 -0.1070    1.10  1.493347
55      ABVC  2026-07-20 10:32:00    1.231200    1.239300    1.231200    1.239300      201.0  2026-07-20    1.28        1.22  9.180311e-01   XBI -0.0595 -0.1070    1.02  1.493347
56      ABVC  2026-07-20 10:33:00    1.231200    1.231200    1.231200    1.231200      100.0  2026-07-20    1.28        1.22  9.180311e-01   XBI -0.0595 -0.1070    0.86  1.493347
57      ABVC  2026-07-20 10:37:00    1.234900    1.234900    1.234900    1.234900      102.0  2026-07-20    1.28        1.22  1.221311e+00   XBI -0.0595 -0.1070    0.75  1.493347
58      ABVC  2026-07-20 10:39:00    1.238200    1.238200    1.238200    1.238200      102.0  2026-07-20    1.28        1.22  1.491799e+00   XBI -0.0595 -0.1070    0.72  1.493347
59      ABVC  2026-07-20 10:40:00    1.230000    1.245000    1.230000    1.245000      303.0  2026-07-20    1.28        1.22  8.196737e-01   XBI -0.0595 -0.1070    0.69  1.493347
60      ABVC  2026-07-20 10:41:00    1.240000    1.250000    1.240000    1.250000     1050.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.72  1.493347
61      ABVC  2026-07-20 10:46:00    1.240000    1.245800    1.240000    1.245800      301.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.64  1.493347
62      ABVC  2026-07-20 10:47:00    1.250000    1.250000    1.250000    1.250000    10600.0  2026-07-20    1.28        1.22  2.459016e+00   XBI -0.0595 -0.1070    0.71  1.493347
63      ABVC  2026-07-20 10:49:00    1.248000    1.248000    1.248000    1.248000      100.0  2026-07-20    1.28        1.22  2.295084e+00   XBI -0.0595 -0.1070    0.60  1.493347
64      ABVC  2026-07-20 10:50:00    1.240000    1.240000    1.240000    1.240000      100.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.53  1.493347
65      ABVC  2026-07-20 10:51:00    1.248000    1.248000    1.240000    1.248000      304.0  2026-07-20    1.28        1.22  2.295084e+00   XBI -0.0595 -0.1070    0.55  1.493347
66      ABVC  2026-07-20 10:52:00    1.240000    1.240000    1.240000    1.240000      100.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.60  1.493347
67      ABVC  2026-07-20 10:56:00    1.240000    1.240000    1.240000    1.240000      201.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.43  1.493347
68      ABVC  2026-07-20 10:58:00    1.240000    1.240000    1.240000    1.240000      403.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.36  1.493347
69      ABVC  2026-07-20 10:59:00    1.235000    1.240000    1.235000    1.235000     1303.0  2026-07-20    1.28        1.22  1.229509e+00   XBI -0.0595 -0.1070    0.31  1.493347
70      ABVC  2026-07-20 11:00:00    1.240000    1.240000    1.240000    1.240000      200.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.33  1.493347
71      ABVC  2026-07-20 11:02:00    1.248900    1.248900    1.248900    1.248900      100.0  2026-07-20    1.28        1.22  2.368857e+00   XBI -0.0595 -0.1070    0.44  1.493347
72      ABVC  2026-07-20 11:03:00    1.248800    1.248800    1.248800    1.248800      100.0  2026-07-20    1.28        1.22  2.360659e+00   XBI -0.0595 -0.1070    0.44  1.493347
73      ABVC  2026-07-20 11:04:00    1.248800    1.248800    1.248800    1.248800      100.0  2026-07-20    1.28        1.22  2.360659e+00   XBI -0.0595 -0.1070    0.41  1.493347
74      ABVC  2026-07-20 11:06:00    1.241000    1.247800    1.240000    1.247800     1202.0  2026-07-20    1.28        1.22  1.721316e+00   XBI -0.0595 -0.1070    0.34  1.493347
75      ABVC  2026-07-20 11:07:00    1.240000    1.240000    1.240000    1.240000      500.0  2026-07-20    1.28        1.22  1.639345e+00   XBI -0.0595 -0.1070    0.47  1.493347
76      ABVC  2026-07-20 11:12:00    1.235000    1.238800    1.220000    1.230000     9933.0  2026-07-20    1.28        1.22  1.229509e+00   XBI -0.0595 -0.1070    0.49  1.493347
77      ABVC  2026-07-20 11:17:00    1.227500    1.227500    1.227500    1.227500      104.0  2026-07-20    1.28        1.22  6.147510e-01   XBI -0.0595 -0.1070    0.61  1.493347
78      ABVC  2026-07-20 11:20:00    1.220000    1.220000    1.220000    1.220000      100.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.62  1.493347
79      ABVC  2026-07-20 11:23:00    1.229300    1.229300    1.229300    1.229300      100.0  2026-07-20    1.28        1.22  7.622969e-01   XBI -0.0595 -0.1070    0.63  1.493347
80      ABVC  2026-07-20 11:26:00    1.228000    1.228000    1.228000    1.228000      100.0  2026-07-20    1.28        1.22  6.557414e-01   XBI -0.0595 -0.1070    0.59  1.493347
81      ABVC  2026-07-20 11:27:00    1.227400    1.227400    1.227400    1.227400      100.0  2026-07-20    1.28        1.22  6.065529e-01   XBI -0.0595 -0.1070    0.53  1.493347
82      ABVC  2026-07-20 11:28:00    1.220000    1.220000    1.220000    1.220000      100.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.53  1.493347
83      ABVC  2026-07-20 11:30:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.53  1.493347
84      ABVC  2026-07-20 11:41:00    1.210000    1.210000    1.210000    1.210000      300.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.40  1.493347
85      ABVC  2026-07-20 11:42:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.45  1.493347
86      ABVC  2026-07-20 11:43:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.49  1.493347
87      ABVC  2026-07-20 11:47:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.48  1.493347
88      ABVC  2026-07-20 11:49:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.41  1.493347
89      ABVC  2026-07-20 11:50:00    1.210000    1.210000    1.210000    1.210000      100.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.46  1.493347
90      ABVC  2026-07-20 12:04:00    1.220000    1.220000    1.220000    1.220000     2580.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.57  1.493347
91      ABVC  2026-07-20 12:09:00    1.230000    1.230000    1.230000    1.230000      100.0  2026-07-20    1.28        1.22  8.196737e-01   XBI -0.0595 -0.1070    0.80  1.493347
92      ABVC  2026-07-20 12:10:00    1.228600    1.228600    1.228600    1.228600      100.0  2026-07-20    1.28        1.22  7.049201e-01   XBI -0.0595 -0.1070    0.76  1.493347
93      ABVC  2026-07-20 12:11:00    1.228600    1.228600    1.228600    1.228600      300.0  2026-07-20    1.28        1.22  7.049201e-01   XBI -0.0595 -0.1070    0.85  1.493347
94      ABVC  2026-07-20 12:22:00    1.220100    1.220100    1.220100    1.220100     1300.0  2026-07-20    1.28        1.22  8.200427e-03   XBI -0.0595 -0.1070    0.75  1.493347
95      ABVC  2026-07-20 12:23:00    1.220000    1.220000    1.215000    1.215000      650.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.75  1.493347
96      ABVC  2026-07-20 12:24:00    1.219900    1.219900    1.219900    1.219900      100.0  2026-07-20    1.28        1.22 -8.195736e-03   XBI -0.0595 -0.1070    0.77  1.493347
97      ABVC  2026-07-20 12:42:00    1.219100    1.219100    1.219100    1.219100      100.0  2026-07-20    1.28        1.22 -7.377062e-02   XBI -0.0595 -0.1070    0.32  1.493347
98      ABVC  2026-07-20 13:00:00    1.220000    1.220000    1.220000    1.220000      100.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.59  1.493347
99      ABVC  2026-07-20 13:16:00    1.210000    1.210000    1.210000    1.210000     1000.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.52  1.493347
100     ABVC  2026-07-20 13:21:00    1.209000    1.209000    1.209000    1.209000      100.0  2026-07-20    1.28        1.22 -9.016400e-01   XBI -0.0595 -0.1070    0.66  1.493347
101     ABVC  2026-07-20 13:22:00    1.209000    1.209000    1.209000    1.209000      100.0  2026-07-20    1.28        1.22 -9.016400e-01   XBI -0.0595 -0.1070    0.74  1.493347
102     ABVC  2026-07-20 13:23:00    1.209000    1.209000    1.209000    1.209000      100.0  2026-07-20    1.28        1.22 -9.016400e-01   XBI -0.0595 -0.1070    0.74  1.493347
103     ABVC  2026-07-20 13:35:00    1.209000    1.209000    1.209000    1.209000      100.0  2026-07-20    1.28        1.22 -9.016400e-01   XBI -0.0595 -0.1070    0.57  1.493347
104     ABVC  2026-07-20 14:04:00    1.209800    1.209800    1.209800    1.209800      222.0  2026-07-20    1.28        1.22 -8.360652e-01   XBI -0.0595 -0.1070    0.72  1.493347
105     ABVC  2026-07-20 14:21:00    1.210000    1.210000    1.210000    1.210000     3000.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070    0.67  1.493347
106     ABVC  2026-07-20 14:34:00    1.220000    1.220000    1.220000    1.220000      100.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.48  1.493347
107     ABVC  2026-07-20 15:13:00    1.220000    1.220000    1.220000    1.220000      200.0  2026-07-20    1.28        1.22  2.345101e-06   XBI -0.0595 -0.1070    0.13  1.493347
108     ABVC  2026-07-20 15:35:00    1.210000    1.220000    1.210000    1.220000      948.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070   -0.09  1.493347
109     ABVC  2026-07-20 15:36:00    1.210000    1.210000    1.210000    1.210000      400.0  2026-07-20    1.28        1.22 -8.196690e-01   XBI -0.0595 -0.1070   -0.14  1.493347

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,ABTS,2026-07-19 22:45:00,1.190000,1.190000,1.190000,1.190000,1.0,2026-07-19,NaN,NaN,NaN,XRT,0.3771,1.3166,NaN,3.135848
1,ABTS,2026-07-20 04:37:00,1.150000,1.150000,1.150000,1.150000,828.0,2026-07-20,1.22,1.23,-6.504067,XRT,0.3771,1.3166,NaN,3.135848
2,ABTS,2026-07-20 05:09:00,1.150000,1.150000,1.150000,1.150000,300.0,2026-07-20,1.22,1.23,-6.504067,XRT,0.3771,1.3166,NaN,3.135848
3,ABTS,2026-07-20 09:30:00,1.220000,1.220000,1.220000,1.220000,245.0,2026-07-20,1.22,1.23,-0.813006,XRT,0.3771,1.3166,-0.66,3.135848
4,ABTS,2026-07-20 10:01:00,1.161500,1.161500,1.161500,1.161500,1349.0,2026-07-20,1.22,1.23,-5.569108,XRT,0.3771,1.3166,-1.38,3.135848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AEM,2026-07-19 20:07:00,136.869995,136.869995,136.869995,136.869995,1.0,2026-07-19,NaN,NaN,NaN,GDX,0.9662,0.8956,NaN,1.218670
21146,AEM,2026-07-19 20:15:00,136.869995,140.000000,136.869995,140.000000,300.0,2026-07-19,NaN,NaN,NaN,GDX,0.9662,0.8956,NaN,1.218670
21147,AEM,2026-07-19 20:19:00,139.179993,139.179993,139.179993,139.179993,8.0,2026-07-19,NaN,NaN,NaN,GDX,0.9662,0.8956,NaN,1.218670
21148,AEM,2026-07-19 20:21:00,138.300003,138.300003,136.399994,136.500000,305.0,2026-07-19,NaN,NaN,NaN,GDX,0.9662,0.8956,NaN,1.218670
21149,AEM,2026-07-19 23:44:00,138.000000,138.000000,138.000000,138.000000,10.0,2026-07-19,NaN,NaN,NaN,GDX,0.9662,0.8956,NaN,1.218670

In [48]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional, List

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
    import pyarrow.compute as pc
except Exception:
    pa = pq = ds = pc = None


def _as_f64(col):
    """ChunkedArray -> float64 без походу в pandas (fallback лише для нечислових типів)."""
    if pa.types.is_floating(col.type) or pa.types.is_integer(col.type):
        return col.cast(pa.float64()) if col.type != pa.float64() else col
    if pa.types.is_decimal(col.type):
        return col.cast(pa.float64())
    return pa.chunked_array([pa.array(
        pd.to_numeric(col.to_pandas(), errors="coerce").to_numpy(dtype="float64"))])


def _round_like_numpy(col, ndigits):
    """np.round над Arrow-колонкою + NaN -> null (як робив pa.Table.from_pandas)."""
    if len(col) == 0:
        return col
    v = col.to_numpy(zero_copy_only=False)   # може бути read-only zero-copy view
    if ndigits is not None:
        v = np.round(v, int(ndigits))
    return pa.array(v, from_pandas=True)


def _add_tp_deviation_devsig(table, *, round_tp_dev=2, round_devsig=6, dt_as_timestamp=False):
    """t_p / deviation / dev_sig як арифметика Arrow над колонками таблиці.

    Раніше кожен батч ходив у pandas і назад (batch.to_pandas() +
    pa.Table.from_pandas()). Для рядкових колонок ticker/dt/date/bench це означало
    матеріалізацію мільйонів python-об'єктів str на кожному батчі й повне
    перезбирання Arrow-масивів — найдорожча частина того циклу. Тут таблиця
    лишається в Arrow від читання до запису.
    """
    names = {n.strip().lower(): n for n in table.column_names}
    stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
    bench_col = names.get("bench%")
    beta_col = names.get("beta")
    sigma_col = names.get("sigma")

    need = {
        "stack%/pct_vs_prev_close": stack_col,
        "bench%": bench_col,
        "beta": beta_col,
        "sigma": sigma_col,
    }
    missing = [k for k, v in need.items() if v is None]
    if missing:
        raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

    drop = [c for c in ("t_p", "deviation", "dev_sig") if c in table.column_names]
    if drop:
        table = table.drop_columns(drop) if hasattr(table, "drop_columns") else table.drop(drop)

    stack = _as_f64(table[stack_col])
    beta = _as_f64(table[beta_col])
    bench = _as_f64(table[bench_col])
    sigma = _as_f64(table[sigma_col])

    tp = pc.multiply(stack, beta)
    dev = pc.subtract(tp, bench)
    denom = pc.if_else(pc.equal(sigma, 0), pa.scalar(None, pa.float64()), sigma)  # sigma 0 -> NaN
    dsg = pc.divide(dev, denom)

    # Округлення саме через np.round, а не pc.round: на значеннях, які вже округлені
    # вище по пайплайну (Stack% до 2 знаків, beta до 4), добуток лягає впритул до
    # межі .005, і pc.round подекуди дає результат на 1 ULP інший за np.round.
    # np.round тут ще й трохи швидший, а pa.array(..., from_pandas=True) відтворює
    # ту саму семантику NaN -> null, що давав старий pa.Table.from_pandas().
    tp = _round_like_numpy(tp, round_tp_dev)
    dev = _round_like_numpy(dev, round_tp_dev)
    dsg = _round_like_numpy(dsg, round_devsig)

    if dt_as_timestamp and "dt" in table.column_names and pa.types.is_string(table["dt"].type):
        i = table.column_names.index("dt")
        table = table.set_column(i, "dt", pc.strptime(table["dt"], format="%Y-%m-%d %H:%M:%S",
                                                      unit="ns", error_is_null=True))

    return (table.append_column("t_p", tp)
                 .append_column("deviation", dev)
                 .append_column("dev_sig", dsg))


def _sort_keys(schema_names):
    keys = [("ticker", "ascending")]
    if "date" in schema_names:
        keys.append(("date", "ascending"))
    if "dt" in schema_names:
        keys.append(("dt", "ascending"))
    return keys


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # batch_rows для потокового режиму / бакетування
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,
    max_rows_in_memory: int = 20_000_000,
    dt_as_timestamp: bool = False,
    row_group_size: int = 2_000_000,
) -> str:
    """
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.

    Якщо sort_final_by_ticker=True, output_path фізично відсортований:
    ticker A→Z, всередині тикера date,dt.

    Що змінилось проти попередньої версії:
      1. Обчислення і сортування — ОДИН прохід. Раніше спершу писався повний
         tmp_unsorted, потім він читався назад і переписувався відсортованим:
         3 читання + 3 записи всього файла. Тепер 1 читання + 1 запис
         (або 2+2, якщо файл не влазить у пам'ять і потрібні бакети).
      2. Уся арифметика в Arrow — без batch.to_pandas()/pa.Table.from_pandas()
         на кожному батчі (це матеріалізувало рядкові колонки як python-об'єкти).
      3. Сортування ПЕРЕД додаванням t_p/deviation/dev_sig — take() переставляє
         на 3 float64-колонки менше.
      4. Бакетування по тикерах — через pc.index_in замість pandas .map по рядках.
      5. row_group_size=2M замість дефолтного 1M: менше row-груп → швидший запис,
         трохи менший файл, і стратегії-споживачі (вони читають
         iter_batches(batch_size=1_000_000)) теж читають його швидше.
    """
    if pq is None or pa is None or ds is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet, pyarrow.dataset).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    total_rows = dataset.count_rows()

    tmp_out = output_path + f".tmp_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    def _finish(rows, mode):
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_out, output_path)
        print(f"✅ DONE ({mode}): {rows:,} rows → {output_path} | "
              f"total_time={time.time()-t0:,.1f}s", flush=True)
        return output_path

    # ---------- 1) без сортування: чистий стрім, один прохід ----------
    if not sort_final_by_ticker:
        print(f"▶ START (stream): {input_path} → {output_path} | "
              f"rows={total_rows:,} batch={chunksize:,}", flush=True)
        writer = None
        written = 0
        try:
            for bi, rb in enumerate(dataset.to_batches(batch_size=chunksize), 1):
                if rb.num_rows == 0:
                    continue
                tbl = _add_tp_deviation_devsig(
                    pa.Table.from_batches([rb]), round_tp_dev=round_tp_dev,
                    round_devsig=round_devsig, dt_as_timestamp=dt_as_timestamp)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl, row_group_size=row_group_size)
                written += tbl.num_rows
                if bi % 5 == 0:
                    print(f"[batch {bi:>4}] rows={written:,}  "
                          f"elapsed={time.time()-t0:,.1f}s", flush=True)
        finally:
            if writer is not None:
                writer.close()
        return _finish(written, "stream")

    keys = _sort_keys(schema_names)
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    # ---------- 2) влазить у пам'ять: читання → сорт → рахунок → запис ----------
    if total_rows <= max_rows_in_memory:
        print(f"▶ START (in-memory sort): {input_path} → {output_path} | "
              f"rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        table = _add_tp_deviation_devsig(
            table, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
            dt_as_timestamp=dt_as_timestamp)
        pq.write_table(table, tmp_out, compression=compression,
                       row_group_size=row_group_size)
        written = table.num_rows
        del table
        gc.collect()
        return _finish(written, "in-memory sort")

    # ---------- 3) не влазить: один прохід у бакети, далі сорт кожного ----------
    n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
    tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
    tickers = sorted(str(t) for t in tickers if t is not None)
    # суміжні діапазони тикерів → порядок бакетів = порядок тикерів
    edges = np.array_split(np.arange(len(tickers)), n_buckets)
    rank_to_bucket = np.zeros(len(tickers), dtype="int32")
    for b, idxs in enumerate(edges):
        rank_to_bucket[idxs] = b
    ticker_set = pa.array(tickers, type=pa.string())
    rank_to_bucket_arr = pa.array(rank_to_bucket)

    print(f"▶ START (bucketed sort): {input_path} → {output_path} | rows={total_rows:,} "
          f"tickers={len(tickers):,} buckets={n_buckets}", flush=True)

    bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
    bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
    try:
        for rb in dataset.to_batches(batch_size=chunksize):
            if rb.num_rows == 0:
                continue
            tbl = pa.Table.from_batches([rb])
            # ранг тикера в відсортованому списку → номер бакета, повністю в Arrow
            ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
            bidx = pc.take(rank_to_bucket_arr, ranks)
            for b in range(n_buckets):
                mask = pc.equal(bidx, b)
                if not pc.any(mask).as_py():
                    continue
                part = tbl.filter(mask)
                if part.num_rows == 0:
                    continue
                if bwriters[b] is None:
                    bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                   compression=compression)
                bwriters[b].write_table(part)
    finally:
        for w in bwriters:
            if w is not None:
                w.close()

    writer = None
    written = 0
    try:
        for b, bp in enumerate(bucket_paths):
            if not os.path.exists(bp):
                continue
            tbl = pq.read_table(bp).sort_by(keys)
            tbl = _add_tp_deviation_devsig(
                tbl, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
                dt_as_timestamp=dt_as_timestamp)
            if writer is None:
                writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
            writer.write_table(tbl, row_group_size=row_group_size)
            written += tbl.num_rows
            del tbl
            gc.collect()
            print(f"  bucket {b+1}/{n_buckets}  written={written:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)
    finally:
        if writer is not None:
            writer.close()
        for bp in bucket_paths:
            if os.path.exists(bp):
                os.remove(bp)

    return _finish(written, "bucketed sort")


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    max_rows_in_memory: int = 20_000_000,
    log_every: int = 200,            # лишено для сумісності виклику
    roundtrip_pandas: bool = True,   # лишено для сумісності виклику
):
    """Лише сортування parquet: ticker A→Z, всередині тикера (date, dt).

    Обчислення t_p/deviation/dev_sig тепер робить сам recompute_tp_deviation_devsig
    у тому ж проході, тож окремо ця функція потрібна лише якщо треба відсортувати
    вже готовий файл.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")
    keys = _sort_keys(schema_names)

    total_rows = dataset.count_rows()
    t0 = time.time()
    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    if total_rows <= max_rows_in_memory:
        print(f"▶ SORT (in-memory): rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        pq.write_table(table, tmp_out, compression=compression)
        written = table.num_rows
        del table
        gc.collect()
    else:
        n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
        tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
        tickers = sorted(str(t) for t in tickers if t is not None)
        rank_to_bucket = np.zeros(len(tickers), dtype="int32")
        for b, idxs in enumerate(np.array_split(np.arange(len(tickers)), n_buckets)):
            rank_to_bucket[idxs] = b
        ticker_set = pa.array(tickers, type=pa.string())
        rank_to_bucket_arr = pa.array(rank_to_bucket)
        print(f"▶ SORT (bucketed): rows={total_rows:,} tickers={len(tickers):,} "
              f"buckets={n_buckets}", flush=True)

        bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
        bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
        try:
            for rb in dataset.to_batches():
                if rb.num_rows == 0:
                    continue
                tbl = pa.Table.from_batches([rb])
                ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
                bidx = pc.take(rank_to_bucket_arr, ranks)
                for b in range(n_buckets):
                    mask = pc.equal(bidx, b)
                    if not pc.any(mask).as_py():
                        continue
                    part = tbl.filter(mask)
                    if part.num_rows == 0:
                        continue
                    if bwriters[b] is None:
                        bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                       compression=compression)
                    bwriters[b].write_table(part)
        finally:
            for w in bwriters:
                if w is not None:
                    w.close()

        writer = None
        written = 0
        try:
            for b, bp in enumerate(bucket_paths):
                if not os.path.exists(bp):
                    continue
                tbl = pq.read_table(bp).sort_by(keys)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl)
                written += tbl.num_rows
                del tbl
                gc.collect()
        finally:
            if writer is not None:
                writer.close()
            for bp in bucket_paths:
                if os.path.exists(bp):
                    os.remove(bp)

    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)
    print(f"✅ SORT DONE: {written:,} rows → {output_path} | time={time.time()-t0:,.1f}s", flush=True)
    return output_path

In [49]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (bucketed sort): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | rows=113,176,626 tickers=7,849 buckets=6

  bucket 1/6  written=18,826,733  elapsed=103.3s

  bucket 2/6  written=37,046,155  elapsed=125.4s

  bucket 3/6  written=54,818,510  elapsed=146.7s

  bucket 4/6  written=73,783,572  elapsed=169.7s

  bucket 5/6  written=94,139,498  elapsed=194.6s

  bucket 6/6  written=113,176,626  elapsed=217.8s

✅ DONE (bucketed sort): 113,176,626 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=217.9s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'