In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2025-12-16 00:00:00
end   = 2026-03-16 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2025-12-16
end_date_str   = 2026-03-16

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

  ticker       value
0      A    61531.01
1     AA  1981880.18
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 12690

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,country,exchange,market_cap',
    'active': True,
    'us_exchange': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
top1500 = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(top1500):,} рядків")
top1500.head()

Після фільтрації залишилось: 6,855 рядків

,ticker,value,lvl3,country,exchange,market_cap
0,A,61531.01,Medical Equipment & Devices,UNITED STATES,New York,31603.0
1,AA,1981880.18,Metals & Mining,UNITED STATES,New York,17571.0
2,AAAU,1086434.62,NaN,NaN,NaN,NaN
3,AACG,3.16,Software,UNITED STATES,NASDAQ CM,31.0
4,AAL,1432318.10,Transportation & Logistics,UNITED STATES,NASDAQ GS,6926.0

In [7]:
top1500[top1500["ticker"] == "JD"]

,ticker,value,lvl3,country,exchange,market_cap
3283,JD,2659232.39,E-Commerce Discretionary,UNITED STATES,NASDAQ GS,38776.0

In [8]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [9]:
unique_lvl2 = get_unique_lvl2(top1500)
unique_lvl2

🔹 Знайдено 58 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [10]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "BITO"],
    "Banking": ["KRE", "XLF", "SPY", "BITO"],
    "Institutional Financial Svcs": ["XLF", "SPY", "BITO"],
    "Insurance": ["XLF", "SPY", "BITO"],
    "Specialty Finance": ["XLF", "SPY", "BITO"],

    # --- Tech / Internet / Growth ---
    "Software": ["QQQ", "IWM", "SPY"],
    "IT Services": ["QQQ", "IWM", "SPY"],
    "Semiconductors": ["SOXL", "QQQ", "IWM", "SPY"],
    "Technology Hardware": ["QQQ", "SOXL", "IWM", "SPY"],
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["IWM", "SPY", "QQQ"],
    "Diversified Industrials": ["SPY", "IWM"],
    "Industrial Intermediate Prod": ["IWM", "SPY"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["IWM", "SPY"],
    "Machinery": ["IWM", "SPY"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["IWM", "SPY"],
    "Electrical Equipment": ["QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XLE", "IWM", "SPY"],
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLE", "IWM", "SPY"],
    "Gas & Water Utilities": ["XLE", "IWM", "SPY"],
    "Renewable Energy": ["XLE", "IWM", "SPY"],
    "Chemicals": ["XLE", "IWM", "SPY"],
    "Metals & Mining": ["GDX", "IWM", "SPY"],
    "Steel": ["GDX", "IWM", "SPY"],
    "Construction Materials": ["IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["QQQ", "IWM", "SPY"],
    "Medical Equipment & Devices": ["QQQ", "IWM", "SPY"],
    "Health Care Facilities & Svcs": ["QQQ", "IWM", "SPY"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["SPY", "IWM"],
    "Beverages": ["SPY", "IWM"],
    "Household Products": ["SPY", "IWM"],
    "Tobacco & Cannabis": ["SPY", "IWM"],
    "Retail - Consumer Staples": ["SPY", "IWM"],
    "Wholesale - Consumer Staples": ["SPY", "IWM"],

    "Retail - Discretionary": ["SPY", "IWM", "QQQ"],
    "Wholesale - Discretionary": ["SPY", "IWM", "QQQ"],
    "Consumer Services": ["SPY", "IWM"],
    "Leisure Facilities & Services": ["SPY", "IWM"],
    "Leisure Products": ["SPY", "IWM"],
    "Apparel & Textile Products": ["SPY", "IWM", "QQQ"],
    "Automotive": ["SPY", "IWM", "QQQ"],
    "Home & Office Products": ["SPY", "IWM"],
    "Home Construction": ["IWM", "SPY"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [11]:
# ------------------------------------------------

In [12]:
import time
import math
import pandas as pd

def corr_beta_best_match_batched(
    x_tickers,
    y_tickers,
    period="6 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path=None,          # 🔹 тепер дефолт = None
):
    """
    Викликає /calculations/corr_beta/v2 батчами, об'єднує результати в один DataFrame,
    для кожного X-тікера знаходить Y з максимальною кореляцією.

    Повертає (df_all, df_pairs):
      - df_all   : сирий об'єднаний датафрейм з API
      - df_pairs : мапінг X -> найкращий Y
    """
    # --- валідації ---
    if not x_tickers:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return pd.DataFrame(), empty_pairs

    if not y_tickers:
        raise ValueError("y_tickers не може бути порожнім")

    # --- батчинг (індексний підхід, щоб не губити/дублювати X) ---
    y_str = ",".join(map(str, y_tickers))
    results = []
    i = 0
    n = len(x_tickers)
    bs = max(1, int(batch_size))

    while i < n:
        xs = list(map(str, x_tickers[i : i + bs]))
        x_str = ",".join(xs)

        params = {
            "x_tickers": x_str,
            "y_tickers": y_str,
            "period": period,
            "as_pivot": as_pivot,
            "format": fmt,
        }

        attempt = 0
        while True:
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)

                # підстраховка типів
                if df_chunk is None:
                    fetched_ok = False
                elif isinstance(df_chunk, pd.DataFrame):
                    fetched_ok = not df_chunk.empty
                else:
                    df_chunk = pd.DataFrame(df_chunk)
                    fetched_ok = not df_chunk.empty

                if fetched_ok:
                    results.append(df_chunk)

                i += len(xs)
                print(f"[{i}/{n}] fetched batch of {len(xs)} X тикерів")
                time.sleep(pause)
                break

            except Exception as e:
                msg = str(e).lower()
                attempt += 1

                if "414" in msg or "uri too large" in msg or "request-uri too large" in msg:
                    new_bs = max(1, bs // 2)
                    if new_bs == bs:
                        if attempt >= max_retries:
                            print(
                                f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                                f"після {max_retries} 414-помилок. Помилка: {e}"
                            )
                            i += len(xs)
                            break
                    else:
                        print(
                            f"⚠️  414 на i={i}. Зменшую batch_size {bs} → {new_bs} "
                            f"і формую партію заново."
                        )
                        bs = new_bs
                        break
                else:
                    if attempt >= max_retries:
                        print(
                            f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                            f"після {max_retries} спроб. Помилка: {e}"
                        )
                        i += len(xs)
                        break
                    time.sleep(0.5 * attempt)

    df_all = pd.concat(results, ignore_index=True) if results else pd.DataFrame()

    # --- нормалізація назв колонок ---
    def _col(options, cols_lower):
        for c in options:
            if c.lower() in cols_lower:
                return next(cc for cc in df_all.columns if cc.lower() == c.lower())
        return None

    if df_all.empty:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return df_all, empty_pairs

    cols_lower = {c.lower() for c in df_all.columns}

    x_col    = _col(["x_ticker", "x", "ticker_x", "subject", "symbol_x"], cols_lower)
    y_col    = _col(["y_ticker", "y", "ticker_y", "benchmark", "symbol_y"], cols_lower)
    corr_col = _col(["corr", "correlation", "pearson_corr"], cols_lower)
    beta_col = _col(["beta", "beta_coeff"], cols_lower)

    missing = [
        name
        for name, val in [("x_ticker", x_col), ("y_ticker", y_col), ("corr", corr_col)]
        if val is None
    ]
    if missing:
        raise ValueError(
            f"Від API бракує очікуваних колонок: {', '.join(missing)}. "
            f"Є колонки: {list(df_all.columns)}"
        )

    # --- вибір найкращого Y для кожного X за corr ---
    df_sorted = df_all.sort_values(by=corr_col, ascending=False)
    idx_best = df_sorted.groupby(x_col, as_index=False)[corr_col].idxmax()[corr_col]
    df_best = df_sorted.loc[
        idx_best, [x_col, y_col, corr_col] + ([beta_col] if beta_col else [])
    ].copy()

    rename_map = {
        x_col: "x_ticker",
        y_col: "best_y_ticker",
        corr_col: "best_corr",
    }
    if beta_col:
        rename_map[beta_col] = "beta_with_best"
    df_pairs = df_best.rename(columns=rename_map)

    if "beta_with_best" not in df_pairs.columns:
        df_pairs["beta_with_best"] = pd.NA

    df_pairs = df_pairs[["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]]

    if output_path:
        df_pairs.to_csv(output_path, index=False)
        print(f"✅ Збережено {len(df_pairs)} пар у файл: {output_path}")

    return df_all, df_pairs

In [13]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
):
    """
    Створює два файли:
      1) output_path (за замовчуванням x_to_best_etf_by_lvl3.csv):
         x_ticker, best_y_ticker, best_corr, beta_with_best, lvl3

      2) bench_path (за замовчуванням ticker_bench.csv):
         ticker, benchmark

    Логіка:
      - Для кожного lvl3-сектора збираємо X-список тікерів.
      - Y-список ETF-ів беремо з sector_to_etf[lvl3].
      - Якщо сектору немає в мапі або список порожній → використовуємо fallback_etfs
        (за замовчуванням ["SPY", "QQQ", "IWM"]).
      - Для кожного тикера залишаємо ETF з максимальною кореляцією.
      - Тікери без lvl3 (NaN) обробляються як сектор 'UNKNOWN' з fallback ETF-ами.
    """

    import pandas as pd  # на випадок, якщо не імпортнуто вище

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]

    if sector_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{sector_col}'")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{ticker_col}'")

    # Беремо лише тикер і сектор, але НЕ дропаємо NaN — замінимо їх на 'UNKNOWN'
    df_clean = (
        tickers_df[[ticker_col, sector_col]]
        .drop_duplicates()
        .copy()
    )

    # 🔥 Тікери без сектора → 'UNKNOWN'
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)
    df_clean[ticker_col] = df_clean[ticker_col].astype(str)

    all_sectors = sorted(df_clean[sector_col].unique().tolist())

    all_chunks = []
    all_pairs = []
    sectors_with_fallback = []

    for sector in all_sectors:
        etfs = sector_to_etf.get(sector)

        if not etfs:
            etfs = list(fallback_etfs)
            sectors_with_fallback.append(sector)
            print(
                f"⚠️  Для сектора '{sector}' немає ETF-ів у sector_to_etf — "
                f"використовую fallback: {etfs}"
            )
        else:
            print(f"✅ lvl3: {sector} → ETF-и з мапи: {etfs}")

        x_tickers = (
            df_clean.loc[df_clean[sector_col] == sector, ticker_col]
            .astype(str)
            .unique()
            .tolist()
        )
        if not x_tickers:
            continue

        print(f"\n=== lvl3: {sector} | X-тикерів: {len(x_tickers)} | ETF-и: {etfs} ===")

        df_all_sec, df_pairs_sec = corr_beta_best_match_batched(
            x_tickers=x_tickers,
            y_tickers=etfs,
            period=period,
            as_pivot=as_pivot,
            fmt=fmt,
            batch_size=batch_size,
            pause=pause,
            max_retries=max_retries,
            output_path=None,   # тут не пишемо окремі файли
        )

        if not df_all_sec.empty:
            df_all_sec = df_all_sec.copy()
            df_all_sec[sector_col] = sector
            all_chunks.append(df_all_sec)

        if not df_pairs_sec.empty:
            df_pairs_sec = df_pairs_sec.copy()
            df_pairs_sec[sector_col] = sector
            all_pairs.append(df_pairs_sec)

    df_all = pd.concat(all_chunks, ignore_index=True) if all_chunks else pd.DataFrame()

    if all_pairs:
        df_pairs = pd.concat(all_pairs, ignore_index=True)

        # на випадок дублів по x_ticker — лишаємо найбільшу кореляцію
        df_pairs_sorted = df_pairs.sort_values(by="best_corr", ascending=False)
        idx_best = (
            df_pairs_sorted.groupby("x_ticker", as_index=False)["best_corr"]
            .idxmax()["best_corr"]
        )
        df_pairs = df_pairs_sorted.loc[idx_best].reset_index(drop=True)

        # ⚙️ детальний файл
        df_pairs.to_csv(output_path, index=False)
        print(f"\n✅ Збережено {len(df_pairs)} X→ETF пар у файл: {output_path}")

        # ⚙️ спрощений файл вигляду ticker,benchmark
        df_bench = df_pairs.rename(
            columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"}
        )[["ticker", "benchmark"]]

        df_bench.to_csv(bench_path, index=False)
        print(f"✅ Збережено {len(df_bench)} записів у файл: {bench_path}")

    else:
        df_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", sector_col]
        )
        df_pairs.to_csv(output_path, index=False)
        pd.DataFrame(columns=["ticker", "benchmark"]).to_csv(bench_path, index=False)
        print("\n⚠️ Не вдалося знайти жодної пари X→ETF. Створено порожні файли.")

    if sectors_with_fallback:
        print("\n⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):")
        for s in sectors_with_fallback:
            print("   -", s)

    return df_all, df_pairs

In [14]:
# нове: працюємо напряму з таблицею top1500 (ticker + lvl3)
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=top1500,          # DataFrame з колонками ticker, lvl3, ...
    sector_to_etf=sector_to_etf, # мапа lvl3 -> список ETF-ів
    sector_col="lvl3",           # Yазва колонки сектора в top1500
    ticker_col="ticker",         # назва колонки з тикером
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.1,
    max_retries=3,
    output_path = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path  = str(WORK_DIR / "ticker_bench_.csv")  # або правильна назва
)

print(df_all.head())
print("Рядків у сирих даних:", len(df_all))
print(df_pairs.head())

✅ lvl3: Advertising & Marketing → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Advertising & Marketing | X-тикерів: 34 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[34/34] fetched batch of 34 X тикерів
✅ lvl3: Aerospace & Defense → ETF-и з мапи: ['IWM', 'SPY', 'QQQ']

=== lvl3: Aerospace & Defense | X-тикерів: 73 | ETF-и: ['IWM', 'SPY', 'QQQ'] ===

[73/73] fetched batch of 73 X тикерів
✅ lvl3: Apparel & Textile Products → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Apparel & Textile Products | X-тикерів: 35 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[35/35] fetched batch of 35 X тикерів
✅ lvl3: Asset Management → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Asset Management | X-тикерів: 195 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/195] fetched batch of 150 X тикерів

[195/195] fetched batch of 45 X тикерів
✅ lvl3: Automotive → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Automotive | X-тикерів: 72 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[72/72] fetched batch of 72 X тикерів
✅ lvl3: Banking → ETF-и з мапи: ['KRE', 'XLF', 'SPY', 'BITO']

=== lvl3: Banking | X-тикерів: 219 | ETF-и: ['KRE', 'XLF', 'SPY', 'BITO'] ===

[150/219] fetched batch of 150 X тикерів

[219/219] fetched batch of 69 X тикерів
✅ lvl3: Beverages → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Beverages | X-тикерів: 36 | ETF-и: ['SPY', 'IWM'] ===

[36/36] fetched batch of 36 X тикерів
✅ lvl3: Biotech & Pharma → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Biotech & Pharma | X-тикерів: 664 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/664] fetched batch of 150 X тикерів

[300/664] fetched batch of 150 X тикерів

[450/664] fetched batch of 150 X тикерів

[600/664] fetched batch of 150 X тикерів

[664/664] fetched batch of 64 X тикерів

✅ lvl3: Cable & Satellite → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Cable & Satellite | X-тикерів: 13 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[13/13] fetched batch of 13 X тикерів
✅ lvl3: Chemicals → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Chemicals | X-тикерів: 85 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[85/85] fetched batch of 85 X тикерів
✅ lvl3: Commercial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Commercial Support Services | X-тикерів: 108 | ETF-и: ['IWM', 'SPY'] ===

[108/108] fetched batch of 108 X тикерів
✅ lvl3: Construction Materials → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Construction Materials | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Consumer Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Consumer Services | X-тикерів: 40 | ETF-и: ['SPY', 'IWM'] ===

[40/40] fetched batch of 40 X тикерів
✅ lvl3: Containers & Packaging → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Containers & Packaging | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Diversified Industrials → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Diversified Industrials | X-тикерів: 7 | ETF-и: ['SPY', 'IWM'] ===

[7/7] fetched batch of 7 X тикерів
✅ lvl3: E-Commerce Discretionary → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: E-Commerce Discretionary | X-тикерів: 49 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[49/49] fetched batch of 49 X тикерів
✅ lvl3: Electric Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Electric Utilities | X-тикерів: 67 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[67/67] fetched batch of 67 X тикерів
✅ lvl3: Electrical Equipment → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Electrical Equipment | X-тикерів: 93 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[93/93] fetched batch of 93 X тикерів
✅ lvl3: Engineering & Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Engineering & Construction | X-тикерів: 54 | ETF-и: ['IWM', 'SPY'] ===

[54/54] fetched batch of 54 X тикерів
✅ lvl3: Entertainment Content → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Entertainment Content | X-тикерів: 42 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[42/42] fetched batch of 42 X тикерів
✅ lvl3: Food → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Food | X-тикерів: 66 | ETF-и: ['SPY', 'IWM'] ===

[66/66] fetched batch of 66 X тикерів
✅ lvl3: Forestry, Paper & Wood Products → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Forestry, Paper & Wood Products | X-тикерів: 10 | ETF-и: ['IWM', 'SPY'] ===

[10/10] fetched batch of 10 X тикерів
✅ lvl3: Gas & Water Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Gas & Water Utilities | X-тикерів: 23 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[23/23] fetched batch of 23 X тикерів
✅ lvl3: Health Care Facilities & Svcs → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Health Care Facilities & Svcs | X-тикерів: 100 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[100/100] fetched batch of 100 X тикерів
✅ lvl3: Home & Office Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Home & Office Products | X-тикерів: 21 | ETF-и: ['SPY', 'IWM'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Home Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Home Construction | X-тикерів: 36 | ETF-и: ['IWM', 'SPY'] ===

[36/36] fetched batch of 36 X тикерів
✅ lvl3: Household Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Household Products | X-тикерів: 39 | ETF-и: ['SPY', 'IWM'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: IT Services → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: IT Services | X-тикерів: 69 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[69/69] fetched batch of 69 X тикерів
✅ lvl3: Industrial Intermediate Prod → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Intermediate Prod | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Industrial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Support Services | X-тикерів: 31 | ETF-и: ['IWM', 'SPY'] ===

[31/31] fetched batch of 31 X тикерів
✅ lvl3: Institutional Financial Svcs → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Institutional Financial Svcs | X-тикерів: 37 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[37/37] fetched batch of 37 X тикерів
✅ lvl3: Insurance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Insurance | X-тикерів: 87 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[87/87] fetched batch of 87 X тикерів
✅ lvl3: Internet Media & Services → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Internet Media & Services | X-тикерів: 106 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[106/106] fetched batch of 106 X тикерів
✅ lvl3: Leisure Facilities & Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Facilities & Services | X-тикерів: 112 | ETF-и: ['SPY', 'IWM'] ===

[112/112] fetched batch of 112 X тикерів
✅ lvl3: Leisure Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Products | X-тикерів: 33 | ETF-и: ['SPY', 'IWM'] ===

[33/33] fetched batch of 33 X тикерів
✅ lvl3: Machinery → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Machinery | X-тикерів: 87 | ETF-и: ['IWM', 'SPY'] ===

[87/87] fetched batch of 87 X тикерів
✅ lvl3: Medical Equipment & Devices → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Medical Equipment & Devices | X-тикерів: 203 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/203] fetched batch of 150 X тикерів

[203/203] fetched batch of 53 X тикерів
✅ lvl3: Metals & Mining → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Metals & Mining | X-тикерів: 150 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[150/150] fetched batch of 150 X тикерів
✅ lvl3: Oil & Gas Services & Equip → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Services & Equip | X-тикерів: 55 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[55/55] fetched batch of 55 X тикерів
✅ lvl3: Oil & Gas Supply Chain → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Supply Chain | X-тикерів: 144 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[144/144] fetched batch of 144 X тикерів
✅ lvl3: Publishing & Broadcasting → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Publishing & Broadcasting | X-тикерів: 19 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: REIT → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: REIT | X-тикерів: 131 | ETF-и: ['IWM', 'SPY'] ===

[131/131] fetched batch of 131 X тикерів
✅ lvl3: Real Estate Owners & Developers → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Owners & Developers | X-тикерів: 14 | ETF-и: ['IWM', 'SPY'] ===

[14/14] fetched batch of 14 X тикерів
✅ lvl3: Real Estate Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Services | X-тикерів: 19 | ETF-и: ['IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Renewable Energy → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Renewable Energy | X-тикерів: 60 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[60/60] fetched batch of 60 X тикерів
✅ lvl3: Retail - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Retail - Consumer Staples | X-тикерів: 24 | ETF-и: ['SPY', 'IWM'] ===

[24/24] fetched batch of 24 X тикерів
✅ lvl3: Retail - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Retail - Discretionary | X-тикерів: 101 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[101/101] fetched batch of 101 X тикерів
✅ lvl3: Semiconductors → ETF-и з мапи: ['SOXL', 'QQQ', 'IWM', 'SPY']

=== lvl3: Semiconductors | X-тикерів: 104 | ETF-и: ['SOXL', 'QQQ', 'IWM', 'SPY'] ===

[104/104] fetched batch of 104 X тикерів
✅ lvl3: Software → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Software | X-тикерів: 326 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/326] fetched batch of 150 X тикерів

[300/326] fetched batch of 150 X тикерів

[326/326] fetched batch of 26 X тикерів
✅ lvl3: Specialty Finance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Specialty Finance | X-тикерів: 175 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/175] fetched batch of 150 X тикерів

[175/175] fetched batch of 25 X тикерів
✅ lvl3: Steel → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Steel | X-тикерів: 20 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
✅ lvl3: Technology Hardware → ETF-и з мапи: ['QQQ', 'SOXL', 'IWM', 'SPY']

=== lvl3: Technology Hardware | X-тикерів: 138 | ETF-и: ['QQQ', 'SOXL', 'IWM', 'SPY'] ===

[138/138] fetched batch of 138 X тикерів
✅ lvl3: Telecommunications → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Telecommunications | X-тикерів: 44 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[44/44] fetched batch of 44 X тикерів
✅ lvl3: Tobacco & Cannabis → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Tobacco & Cannabis | X-тикерів: 19 | ETF-и: ['SPY', 'IWM'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Transportation & Logistics → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation & Logistics | X-тикерів: 124 | ETF-и: ['IWM', 'SPY'] ===

[124/124] fetched batch of 124 X тикерів
✅ lvl3: Transportation Equipment → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation Equipment | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
⚠️  Для сектора 'UNKNOWN' немає ETF-ів у sector_to_etf — використовую fallback: ['SPY', 'QQQ', 'IWM']

=== lvl3: UNKNOWN | X-тикерів: 2130 | ETF-и: ['SPY', 'QQQ', 'IWM'] ===

[150/2130] fetched batch of 150 X тикерів

[300/2130] fetched batch of 150 X тикерів

[450/2130] fetched batch of 150 X тикерів

[600/2130] fetched batch of 150 X тикерів

[750/2130] fetched batch of 150 X тикерів

[900/2130] fetched batch of 150 X тикерів

[1050/2130] fetched batch of 150 X тикерів

[1200/2130] fetched batch of 150 X тикерів

[1350/2130] fetched batch of 150 X тикерів

[1500/2130] fetched batch of 150 X тикерів

[1650/2130] fetched batch of 150 X тикерів

[1800/2130] fetched batch of 150 X тикерів

[1950/2130] fetched batch of 150 X тикерів

[2100/2130] fetched batch of 150 X тикерів

[2130/2130] fetched batch of 30 X тикерів

✅ lvl3: Wholesale - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Wholesale - Consumer Staples | X-тикерів: 13 | ETF-и: ['SPY', 'IWM'] ===
[13/13] fetched batch of 13 X тикерів

✅ lvl3: Wholesale - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Wholesale - Discretionary | X-тикерів: 15 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===
[15/15] fetched batch of 15 X тикерів

✅ Збережено 6703 X→ETF пар у файл: C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
✅ Збережено 6703 записів у файл: C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv

⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):
   - UNKNOWN
  x_ticker y_ticker  corr  beta                     lvl3
0      ADV     KWEB -0.17   0.0  Advertising & Marketing
1      ADV      IWM  0.09   0.0  Advertising & Marketing
2      ADV      SPY  0.08   0.0  Advertising & Marketing
3      ADV      QQQ  0.08   0.0  Advertising & Marketing
4     AEHL     KWEB  0.30   0.0  Advertising & Marketing
Рядків у сирих даних: 19761
  x_ticker best_y_ticker  best_corr  beta_with_best  \
0        A           IWM       0.81            0.60
1       AA           SPY       0.77            2.60
2     AAAU           IWM       0.46            0.88
3     AACG           QQQ       0.12            0.00
4      AAL           IWM       0.89            1.68

                          lvl3
0  Medical Equipment & Devices
1              Metals & Mining
2                      UNKNOWN
3                     Software
4   Transportation & Logistics

In [15]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [16]:
top1500

,ticker,value,lvl3,country,exchange,market_cap
0,A,61531.01,Medical Equipment & Devices,UNITED STATES,New York,31603.0
1,AA,1981880.18,Metals & Mining,UNITED STATES,New York,17571.0
2,AAAU,1086434.62,NaN,NaN,NaN,NaN
3,AACG,3.16,Software,UNITED STATES,NASDAQ CM,31.0
4,AAL,1432318.10,Transportation & Logistics,UNITED STATES,NASDAQ GS,6926.0
...,...,...,...,...,...,...
6850,ZWS,184.99,Machinery,UNITED STATES,New York,7537.0
6851,ZYBT,15.04,Biotech & Pharma,UNITED STATES,NASDAQ CM,36.0
6852,ZYME,29043.84,Biotech & Pharma,UNITED STATES,NASDAQ GS,1754.0
6853,ZYXI,19185.83,NaN,NaN,NaN,NaN
6854,ZYXIQ,19185.83,NaN,NaN,NaN,NaN

In [17]:
import pandas as pd

# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

  ticker
0    SPY
1    IWM
2    GDX
3    XLF
4    QQQ
5    XLE
6    KRE
7   BITO
8   KWEB
9   SOXL

In [18]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=top1500,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=6,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 3663 тікерів (пропущено 0 по старому маніфесту) | 2025-12-16 00:00:00 → 2026-03-16 23:59:59 | interval=1 | next batch #0789 | run=33136ab4

   workers: tickers=6, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 3192

   📉 пропущені дні (в межах window): 2025-12-16 → 2026-03-16 (91 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 256.6 MB

[10/3663] – IPHA: empty |   0.27% | ETA 05:48

[20/3663] – IQ: empty |   0.55% | ETA 05:02

[30/3663] – IRE: empty |   0.82% | ETA 04:26

[40/3663] – IRT: empty |   1.09% | ETA 04:09

[50/3663] – ISSB: empty |   1.37% | ETA 03:57

   • RAM · 🧠 RAM: 286.6 MB

[60/3663] – ITIC: empty |   1.64% | ETA 03:52

[70/3663] – ITW: empty |   1.91% | ETA 03:46

[80/3663] – IVLU: empty |   2.18% | ETA 03:45

[90/3663] – IVZ: empty |   2.46% | ETA 03:41

[100/3663] – IWR: empty |   2.73% | ETA 03:37

   • RAM · 🧠 RAM: 288.7 MB

[110/3663] – IYF: empty |   3.00% | ETA 03:34

[120/3663] – IYZ: empty |   3.28% | ETA 03:32

[130/3663] – JBBB: empty |   3.55% | ETA 03:31

[140/3663] – JBND: empty |   3.82% | ETA 03:28

[150/3663] – JEDI: empty |   4.10% | ETA 03:28

   • RAM · 🧠 RAM: 285.8 MB

[160/3663] – JFIN: empty |   4.37% | ETA 03:30

[170/3663] – JKS: empty |   4.64% | ETA 03:27

[180/3663] – JOB: empty |   4.91% | ETA 03:27

[190/3663] – JPST: empty |   5.19% | ETA 03:25

[200/3663] – JQUA: empty |   5.46% | ETA 03:27

   • RAM · 🧠 RAM: 297.8 MB

[210/3663] – KALV: empty |   5.73% | ETA 03:30

[220/3663] – KBE: empty |   6.01% | ETA 03:29

[230/3663] – KDEF: empty |   6.28% | ETA 03:29

[240/3663] – KFY: empty |   6.55% | ETA 03:31

[250/3663] – KIO: empty |   6.83% | ETA 03:31

   • RAM · 🧠 RAM: 301.4 MB

[260/3663] – KLC: empty |   7.10% | ETA 03:30

[270/3663] – KMPR: empty |   7.37% | ETA 03:29

[280/3663] – KNG: empty |   7.64% | ETA 03:27

[290/3663] – KOF: empty |   7.92% | ETA 03:27

[300/3663] – KORE: empty |   8.19% | ETA 03:27

   • RAM · 🧠 RAM: 301.5 MB

[310/3663] – KRE: empty |   8.46% | ETA 03:25

[320/3663] – KRT: empty |   8.74% | ETA 03:24

[330/3663] – KTB: empty |   9.01% | ETA 03:22

[340/3663] – KVYO: empty |   9.28% | ETA 03:21

[350/3663] – KYTX: empty |   9.56% | ETA 03:21

   • RAM · 🧠 RAM: 301.2 MB

[360/3663] – LAD: empty |   9.83% | ETA 03:20

[370/3663] – LAW: empty |  10.10% | ETA 03:19

[380/3663] – LBTYK: empty |  10.37% | ETA 03:18

[390/3663] – LDOS: empty |  10.65% | ETA 03:17

[400/3663] – LESL: empty |  10.92% | ETA 03:17

   • RAM · 🧠 RAM: 302.0 MB

[410/3663] – LFST: empty |  11.19% | ETA 03:16

[420/3663] – LGN: empty |  11.47% | ETA 03:14

[430/3663] – LI: empty |  11.74% | ETA 03:14

[440/3663] – LIN: empty |  12.01% | ETA 03:13

[450/3663] – LITP: empty |  12.29% | ETA 03:12

   • RAM · 🧠 RAM: 301.6 MB

[460/3663] – LMB: empty |  12.56% | ETA 03:11

[470/3663] – LNC: empty |  12.83% | ETA 03:11

[480/3663] – LOAN: empty |  13.10% | ETA 03:10

[490/3663] – LOVE: empty |  13.38% | ETA 03:10

[500/3663] – LPSN: empty |  13.65% | ETA 03:09

   • RAM · 🧠 RAM: 301.6 MB

[510/3663] – LRCX: empty |  13.92% | ETA 03:10

[520/3663] – LTBR: empty |  14.20% | ETA 03:09

[530/3663] – LUCY: empty |  14.47% | ETA 03:09

[540/3663] – LUXE: empty |  14.74% | ETA 03:09

[550/3663] – LWLG: empty |  15.02% | ETA 03:09

   • RAM · 🧠 RAM: 301.3 MB

[560/3663] – LYRA: empty |  15.29% | ETA 03:08

[570/3663] – MAA: empty |  15.56% | ETA 03:08

[580/3663] – MAIN: empty |  15.83% | ETA 03:08

[590/3663] – MARPS: empty |  16.11% | ETA 03:08

[600/3663] – MATX: empty |  16.38% | ETA 03:08

   • RAM · 🧠 RAM: 302.2 MB

[610/3663] – MBIN: empty |  16.65% | ETA 03:07

[620/3663] – MCHB: empty |  16.93% | ETA 03:08

[630/3663] – MCRB: empty |  17.20% | ETA 03:08

[640/3663] – MDCX: empty |  17.47% | ETA 03:07

[650/3663] – MED: empty |  17.75% | ETA 03:07

   • RAM · 🧠 RAM: 308.1 MB

[660/3663] – MEOH: empty |  18.02% | ETA 03:07

[670/3663] – METV: empty |  18.29% | ETA 03:07

[680/3663] – MGC: empty |  18.56% | ETA 03:07

[690/3663] – MGNX: empty |  18.84% | ETA 03:06

[700/3663] – MHK: empty |  19.11% | ETA 03:06

   • RAM · 🧠 RAM: 307.8 MB

[710/3663] – MINY: empty |  19.38% | ETA 03:05

[720/3663] – MITK: empty |  19.66% | ETA 03:05

[730/3663] – MLEC: empty |  19.93% | ETA 03:04

[740/3663] – MLTX: empty |  20.20% | ETA 03:03

[750/3663] – MNDR: empty |  20.48% | ETA 03:03

   • RAM · 🧠 RAM: 308.0 MB

[760/3663] – MNSO: empty |  20.75% | ETA 03:02

[770/3663] – MOG.A: empty |  21.02% | ETA 03:01

[780/3663] – MOS: empty |  21.29% | ETA 03:00

[790/3663] – MPT: empty |  21.57% | ETA 03:00

[800/3663] – MREO: empty |  21.84% | ETA 02:59

   • RAM · 🧠 RAM: 308.4 MB

[810/3663] – MRSH: empty |  22.11% | ETA 02:59

[820/3663] – MSB: empty |  22.39% | ETA 02:58

[830/3663] – MSFT: empty |  22.66% | ETA 02:58

[840/3663] – MSII: empty |  22.93% | ETA 02:57

[850/3663] – MSTW: empty |  23.21% | ETA 02:57

   • RAM · 🧠 RAM: 307.8 MB

[860/3663] – MTBA: empty |  23.48% | ETA 02:56

[870/3663] – MTH: empty |  23.75% | ETA 02:55

[880/3663] – MTZ: empty |  24.02% | ETA 02:55

[890/3663] – MVBF: empty |  24.30% | ETA 02:54

[900/3663] – MWH: empty |  24.57% | ETA 02:54

   • RAM · 🧠 RAM: 307.9 MB

[910/3663] – MYNZ: empty |  24.84% | ETA 02:53

[920/3663] – NAIL: empty |  25.12% | ETA 02:53

[930/3663] – NATO: empty |  25.39% | ETA 02:52

[940/3663] – NBIX: empty |  25.66% | ETA 02:51

[950/3663] – NCEL: empty |  25.94% | ETA 02:50

   • RAM · 🧠 RAM: 308.0 MB

[960/3663] – NCRA: empty |  26.21% | ETA 02:50

[970/3663] – NEE: empty |  26.48% | ETA 02:49

[980/3663] – NEON: empty |  26.75% | ETA 02:48

[990/3663] – NEXA: empty |  27.03% | ETA 02:48

[1000/3663] – NFLU: empty |  27.30% | ETA 02:47

   • RAM · 🧠 RAM: 307.6 MB

[1010/3663] – NGL: empty |  27.57% | ETA 02:47

[1020/3663] – NIHI: empty |  27.85% | ETA 02:46

[1030/3663] – NKE: empty |  28.12% | ETA 02:46

[1040/3663] – NMFC: empty |  28.39% | ETA 02:45

[1050/3663] – NNE: empty |  28.67% | ETA 02:44

   • RAM · 🧠 RAM: 301.6 MB

[1060/3663] – NOBL: empty |  28.94% | ETA 02:44

[1070/3663] – NP: empty |  29.21% | ETA 02:43

[1080/3663] – NRGD: empty |  29.48% | ETA 02:42

[1090/3663] – NSA: empty |  29.76% | ETA 02:41

[1100/3663] – NTLA: empty |  30.03% | ETA 02:41

   • RAM · 🧠 RAM: 303.6 MB

[1110/3663] – NU: empty |  30.30% | ETA 02:40

[1120/3663] – NUS: empty |  30.58% | ETA 02:39

[1130/3663] – NVDA: empty |  30.85% | ETA 02:39

[1140/3663] – NVDX: empty |  31.12% | ETA 02:38

[1150/3663] – NVOX: empty |  31.40% | ETA 02:38

   • RAM · 🧠 RAM: 306.0 MB

[1160/3663] – NVYY: empty |  31.67% | ETA 02:37

[1170/3663] – NWSA: empty |  31.94% | ETA 02:37

[1180/3663] – NXTS: empty |  32.21% | ETA 02:36

[1190/3663] – OBE: empty |  32.49% | ETA 02:35

[1200/3663] – OCFC: empty |  32.76% | ETA 02:35

   • RAM · 🧠 RAM: 306.7 MB

[1210/3663] – OEC: empty |  33.03% | ETA 02:34

[1220/3663] – OGS: empty |  33.31% | ETA 02:33

[1230/3663] – OKE: empty |  33.58% | ETA 02:33

[1240/3663] – OLB: empty |  33.85% | ETA 02:32

[1250/3663] – OMER: empty |  34.13% | ETA 02:31

   • RAM · 🧠 RAM: 306.5 MB

[1260/3663] – ONDL: empty |  34.40% | ETA 02:31

[1270/3663] – ONTF: empty |  34.67% | ETA 02:30

[1280/3663] – OPENW: empty |  34.94% | ETA 02:30

[1290/3663] – OPTT: empty |  35.22% | ETA 02:29

[1300/3663] – ORCL: empty |  35.49% | ETA 02:28

   • RAM · 🧠 RAM: 306.8 MB

[1310/3663] – ORKA: empty |  35.76% | ETA 02:28

[1320/3663] – OS: empty |  36.04% | ETA 02:27

[1330/3663] – OSW: empty |  36.31% | ETA 02:26

[1340/3663] – OTTR: empty |  36.58% | ETA 02:26

[1350/3663] – OZK: empty |  36.86% | ETA 02:25

   • RAM · 🧠 RAM: 307.7 MB

[1360/3663] – PACS: empty |  37.13% | ETA 02:24

[1370/3663] – PANG: empty |  37.40% | ETA 02:24

[1380/3663] – PATK: empty |  37.67% | ETA 02:23

[1390/3663] – PAYP: empty |  37.95% | ETA 02:22

[1400/3663] – PBM: empty |  38.22% | ETA 02:22

   • RAM · 🧠 RAM: 310.1 MB

[1410/3663] – PCG: empty |  38.49% | ETA 02:21

[1420/3663] – PDBC: empty |  38.77% | ETA 02:20

[1430/3663] – PDSB: empty |  39.04% | ETA 02:20

[1440/3663] – PELI: empty |  39.31% | ETA 02:19

[1450/3663] – PERI: empty |  39.59% | ETA 02:19

   • RAM · 🧠 RAM: 310.0 MB

[1460/3663] – PFG: empty |  39.86% | ETA 02:18

[1470/3663] – PFSI: empty |  40.13% | ETA 02:18

[1480/3663] – PHAT: empty |  40.40% | ETA 02:17

[1490/3663] – PHYS: empty |  40.68% | ETA 02:16

[1500/3663] – PINE: empty |  40.95% | ETA 02:16

   • RAM · 🧠 RAM: 313.1 MB

[1510/3663] – PKB: empty |  41.22% | ETA 02:15

[1520/3663] – PLOW: empty |  41.50% | ETA 02:15

[1530/3663] – PLTK: empty |  41.77% | ETA 02:14

[1540/3663] – PLUS: empty |  42.04% | ETA 02:13

[1550/3663] – PMMF: empty |  42.32% | ETA 02:13

   • RAM · 🧠 RAM: 313.6 MB

[1560/3663] – PNR: empty |  42.59% | ETA 02:12

[1570/3663] – POM: empty |  42.86% | ETA 02:11

[1580/3663] – PPC: empty |  43.13% | ETA 02:11

[1590/3663] – PRAA: empty |  43.41% | ETA 02:10

[1600/3663] – PRGS: empty |  43.68% | ETA 02:09

   • RAM · 🧠 RAM: 313.8 MB

[1610/3663] – PRNT: empty |  43.95% | ETA 02:09

[1620/3663] – PRVA: empty |  44.23% | ETA 02:08

[1630/3663] – PSIL: empty |  44.50% | ETA 02:07

[1640/3663] – PSO: empty |  44.77% | ETA 02:07

[1650/3663] – PTF: empty |  45.05% | ETA 02:06

   • RAM · 🧠 RAM: 313.7 MB

[1660/3663] – PTY: empty |  45.32% | ETA 02:05

[1670/3663] – PVLA: empty |  45.59% | ETA 02:05

[1680/3663] – PXED: empty |  45.86% | ETA 02:04

[1690/3663] – QBIG: empty |  46.14% | ETA 02:04

[1700/3663] – QCRH: empty |  46.41% | ETA 02:03

   • RAM · 🧠 RAM: 315.6 MB

[1710/3663] – QCMD: empty |  46.68% | ETA 02:03

[1720/3663] – QNST: empty |  46.96% | ETA 02:02

[1730/3663] – QQQI: empty |  47.23% | ETA 02:01

[1740/3663] – QS: empty |  47.50% | ETA 02:01

[1750/3663] – QUAD: empty |  47.78% | ETA 02:00

   • RAM · 🧠 RAM: 315.5 MB

[1760/3663] – QXO: empty |  48.05% | ETA 01:59

[1770/3663] – RAMP: empty |  48.32% | ETA 01:59

[1780/3663] – RBC: empty |  48.59% | ETA 01:58

[1790/3663] – RCI: empty |  48.87% | ETA 01:58

[1800/3663] – RDI: empty |  49.14% | ETA 01:57

   • RAM · 🧠 RAM: 314.8 MB

[1810/3663] – RDY: empty |  49.41% | ETA 01:56

[1820/3663] – REG: empty |  49.69% | ETA 01:56

[1830/3663] – REMX: empty |  49.96% | ETA 01:55

[1840/3663] – RETO: empty |  50.23% | ETA 01:55

[1850/3663] – RGA: empty |  50.51% | ETA 01:54

   • RAM · 🧠 RAM: 315.4 MB

[1860/3663] – RGTU: empty |  50.78% | ETA 01:53

[1870/3663] – RILY: empty |  51.05% | ETA 01:53

[1880/3663] – RJF: empty |  51.32% | ETA 01:52

[1890/3663] – RLMD: empty |  51.60% | ETA 01:51

[1900/3663] – RMNI: empty |  51.87% | ETA 01:51

   • RAM · 🧠 RAM: 315.8 MB

[1910/3663] – RNP: empty |  52.14% | ETA 01:50

[1920/3663] – ROC: empty |  52.42% | ETA 01:50

[1930/3663] – ROM: empty |  52.69% | ETA 01:49

[1940/3663] – RPID: empty |  52.96% | ETA 01:48

[1950/3663] – RSG: empty |  53.24% | ETA 01:48

   • RAM · 🧠 RAM: 315.1 MB

[1960/3663] – RSVR: empty |  53.51% | ETA 01:47

[1970/3663] – RUSHB: empty |  53.78% | ETA 01:46

[1980/3663] – RVYL: empty |  54.05% | ETA 01:46

[1990/3663] – RY: empty |  54.33% | ETA 01:45

[2000/3663] – RYOJ: empty |  54.60% | ETA 01:45

   • RAM · 🧠 RAM: 315.5 MB

[2010/3663] – SAFE: empty |  54.87% | ETA 01:44

[2020/3663] – SAN: empty |  55.15% | ETA 01:43

[2030/3663] – SB: empty |  55.42% | ETA 01:43

[2040/3663] – SBIO: empty |  55.69% | ETA 01:42

[2050/3663] – SBUX: empty |  55.97% | ETA 01:41

   • RAM · 🧠 RAM: 315.5 MB

[2060/3663] – SCHF: empty |  56.24% | ETA 01:41

[2070/3663] – SCHP: empty |  56.51% | ETA 01:40

[2080/3663] – SCL: empty |  56.78% | ETA 01:39

[2090/3663] – SCYB: empty |  57.06% | ETA 01:39

[2100/3663] – SDOT: empty |  57.33% | ETA 01:38

   • RAM · 🧠 RAM: 315.6 MB

[2110/3663] – SEE: empty |  57.60% | ETA 01:37

[2120/3663] – SEMR: empty |  57.88% | ETA 01:37

[2130/3663] – SETM: empty |  58.15% | ETA 01:36

[2140/3663] – SFNC: empty |  58.42% | ETA 01:36

[2150/3663] – SGI: empty |  58.70% | ETA 01:35

   • RAM · 🧠 RAM: 315.7 MB

[2160/3663] – SGVT: empty |  58.97% | ETA 01:34

[2170/3663] – SHIP: empty |  59.24% | ETA 01:33

[2180/3663] – SHPH: empty |  59.51% | ETA 01:33

[2190/3663] – SIFY: empty |  59.79% | ETA 01:32

[2200/3663] – SIMO: empty |  60.06% | ETA 01:32

   • RAM · 🧠 RAM: 315.6 MB

[2210/3663] – SKBL: empty |  60.33% | ETA 01:31

[2220/3663] – SKM: empty |  60.61% | ETA 01:30

[2230/3663] – SKYY: empty |  60.88% | ETA 01:30

[2240/3663] – SLE: empty |  61.15% | ETA 01:29

[2250/3663] – SLNO: empty |  61.43% | ETA 01:28

   • RAM · 🧠 RAM: 315.7 MB

[2260/3663] – SLVM: empty |  61.70% | ETA 01:28

[2270/3663] – SMA: empty |  61.97% | ETA 01:27

[2280/3663] – SMFG: empty |  62.24% | ETA 01:27

[2290/3663] – SMPL: empty |  62.52% | ETA 01:26

[2300/3663] – SMTK: empty |  62.79% | ETA 01:25

   • RAM · 🧠 RAM: 315.5 MB

[2310/3663] – SNAP: empty |  63.06% | ETA 01:25

[2320/3663] – SNES: empty |  63.34% | ETA 01:24

[2330/3663] ✓ SNOW: 4,996 рядків |  63.61% | ETA 01:24

[2340/3663] ✓ SOBR: 802 рядків |  63.88% | ETA 01:24

[2350/3663] ✓ SOFX: 3,983 рядків |  64.16% | ETA 01:24

   • RAM · 🧠 RAM: 329.3 MB

   ⏳ перед flush · 🧠 RAM: 329.3 MB

💾 batch 789 → 64,353 рядків (всього 64,353 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0789.csv.gz

   ✅ після flush · 🧠 RAM: 332.1 MB

[2360/3663] ✓ SOPH: 1,299 рядків |  64.43% | ETA 01:24

[2370/3663] ✓ SOXQ: 4,141 рядків |  64.70% | ETA 01:24

[2380/3663] ✓ SPB: 1,941 рядків |  64.97% | ETA 01:23

[2390/3663] ✓ SPH: 947 рядків |  65.25% | ETA 01:23

[2400/3663] ✓ SPIR: 3,034 рядків |  65.52% | ETA 01:23

   • RAM · 🧠 RAM: 344.9 MB

   ⏳ перед flush · 🧠 RAM: 344.9 MB

💾 batch 790 → 166,116 рядків (всього 230,469 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0790.csv.gz

   ✅ після flush · 🧠 RAM: 347.7 MB

[2410/3663] ✓ SPPL: 142 рядків |  65.79% | ETA 01:23

[2420/3663] ✓ SPSC: 2,892 рядків |  66.07% | ETA 01:23

[2430/3663] ✓ SPTL: 4,108 рядків |  66.34% | ETA 01:22

[2440/3663] ✓ SPYG: 4,379 рядків |  66.61% | ETA 01:23

[2450/3663] ✓ SQNS: 563 рядків |  66.89% | ETA 01:22

   • RAM · 🧠 RAM: 367.5 MB

   ⏳ перед flush · 🧠 RAM: 367.5 MB

💾 batch 791 → 161,025 рядків (всього 391,494 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0791.csv.gz

   ✅ після flush · 🧠 RAM: 369.2 MB

[2460/3663] ✓ SQQQ: 14,235 рядків |  67.16% | ETA 01:22

[2470/3663] ✓ SSD: 1,732 рядків |  67.43% | ETA 01:22

[2480/3663] ✓ SSP: 3,213 рядків |  67.70% | ETA 01:22

[2490/3663] – STEC: empty |  67.98% | ETA 01:22

[2500/3663] ✓ STI: 624 рядків |  68.25% | ETA 01:21

   • RAM · 🧠 RAM: 394.3 MB

   ⏳ перед flush · 🧠 RAM: 394.3 MB

💾 batch 792 → 165,639 рядків (всього 557,133 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0792.csv.gz

   ✅ після flush · 🧠 RAM: 395.4 MB

[2510/3663] ✓ STLA: 6,227 рядків |  68.52% | ETA 01:21

[2520/3663] ✓ STRT: 546 рядків |  68.80% | ETA 01:21

[2530/3663] ✓ STXS: 2,360 рядків |  69.07% | ETA 01:20

[2540/3663] ✓ SUNE: 1,189 рядків |  69.34% | ETA 01:20

[2550/3663] ✓ SVC: 2,879 рядків |  69.62% | ETA 01:20

   • RAM · 🧠 RAM: 409.1 MB

   ⏳ перед flush · 🧠 RAM: 409.1 MB

💾 batch 793 → 139,332 рядків (всього 696,465 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0793.csv.gz

   ✅ після flush · 🧠 RAM: 413.0 MB

[2560/3663] ✓ SVRN: 9,250 рядків |  69.89% | ETA 01:20

[2570/3663] ✓ SXC: 3,756 рядків |  70.16% | ETA 01:19

[2580/3663] ✓ SYNX: 3,201 рядків |  70.43% | ETA 01:19

[2590/3663] ✓ TALK: 3,927 рядків |  70.71% | ETA 01:19

[2600/3663] ✓ TAYD: 489 рядків |  70.98% | ETA 01:18

   • RAM · 🧠 RAM: 430.6 MB

   ⏳ перед flush · 🧠 RAM: 431.5 MB

💾 batch 794 → 150,764 рядків (всього 847,229 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0794.csv.gz

   ✅ після flush · 🧠 RAM: 435.7 MB

[2610/3663] ✓ TBPH: 3,188 рядків |  71.25% | ETA 01:18

[2620/3663] ✓ TCHI: 274 рядків |  71.53% | ETA 01:17

[2630/3663] ✓ TDAY: 3,375 рядків |  71.80% | ETA 01:17

[2640/3663] ✓ TDY: 2,660 рядків |  72.07% | ETA 01:16

[2650/3663] ✓ TECS: 4,956 рядків |  72.35% | ETA 01:16

   • RAM · 🧠 RAM: 450.5 MB

   ⏳ перед flush · 🧠 RAM: 450.5 MB

💾 batch 795 → 132,400 рядків (всього 979,629 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0795.csv.gz

   ✅ після flush · 🧠 RAM: 452.4 MB

[2660/3663] ✓ TENX: 2,109 рядків |  72.62% | ETA 01:16

[2670/3663] ✓ TEX: 3,754 рядків |  72.89% | ETA 01:15

[2680/3663] ✓ TGEN: 2,014 рядків |  73.16% | ETA 01:15

[2690/3663] ✓ TGT: 4,730 рядків |  73.44% | ETA 01:14

[2700/3663] ✓ THR: 2,524 рядків |  73.71% | ETA 01:14

   • RAM · 🧠 RAM: 466.6 MB

   ⏳ перед flush · 🧠 RAM: 466.6 MB

💾 batch 796 → 124,619 рядків (всього 1,104,248 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0796.csv.gz

   ✅ після flush · 🧠 RAM: 474.2 MB

[2710/3663] ✓ TITN: 1,274 рядків |  73.98% | ETA 01:13

[2720/3663] ✓ TLDR: 183 рядків |  74.26% | ETA 01:13

[2730/3663] ✓ TLSA: 1,080 рядків |  74.53% | ETA 01:12

[2740/3663] ✓ TMCI: 3,157 рядків |  74.80% | ETA 01:12

[2750/3663] ✓ TMQ: 4,447 рядків |  75.08% | ETA 01:11

   • RAM · 🧠 RAM: 490.6 MB

   ⏳ перед flush · 🧠 RAM: 490.6 MB

💾 batch 797 → 154,538 рядків (всього 1,258,786 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0797.csv.gz

   ✅ після flush · 🧠 RAM: 493.2 MB

[2760/3663] ✓ TOKE: 152 рядків |  75.35% | ETA 01:11

[2770/3663] ✓ TORO: 502 рядків |  75.62% | ETA 01:10

[2780/3663] ✓ TPC: 2,937 рядків |  75.89% | ETA 01:10

[2790/3663] ✓ TPVG: 2,701 рядків |  76.17% | ETA 01:09

[2800/3663] ✓ TRI: 3,996 рядків |  76.44% | ETA 01:09

   • RAM · 🧠 RAM: 513.8 MB

   ⏳ перед flush · 🧠 RAM: 513.8 MB

💾 batch 798 → 146,908 рядків (всього 1,405,694 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0798.csv.gz

   ✅ після flush · 🧠 RAM: 514.4 MB

[2810/3663] ✓ TROO: 1,140 рядків |  76.71% | ETA 01:08

[2820/3663] ✓ TRU: 3,829 рядків |  76.99% | ETA 01:08

[2830/3663] ✓ TSCO: 4,071 рядків |  77.26% | ETA 01:07

[2840/3663] ✓ TSLP: 322 рядків |  77.53% | ETA 01:06

[2850/3663] ✓ TSMG: 1,642 рядків |  77.81% | ETA 01:06

   • RAM · 🧠 RAM: 536.0 MB

   ⏳ перед flush · 🧠 RAM: 536.0 MB

💾 batch 799 → 168,315 рядків (всього 1,574,009 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0799.csv.gz

   ✅ після flush · 🧠 RAM: 541.5 MB

[2860/3663] ✓ TSM: 12,668 рядків |  78.08% | ETA 01:06

[2870/3663] ✓ TTAN: 3,790 рядків |  78.35% | ETA 01:05

[2880/3663] – TTSH: empty |  78.62% | ETA 01:04

[2890/3663] ✓ TVGN: 1,350 рядків |  78.90% | ETA 01:04

[2900/3663] – TWNP: empty |  79.17% | ETA 01:03

   • RAM · 🧠 RAM: 557.2 MB

   ⏳ перед flush · 🧠 RAM: 557.2 MB

💾 batch 800 → 144,382 рядків (всього 1,718,391 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0800.csv.gz

   ✅ після flush · 🧠 RAM: 558.4 MB

[2910/3663] ✓ TXO: 1,505 рядків |  79.44% | ETA 01:02

[2920/3663] ✓ TYO: 242 рядків |  79.72% | ETA 01:02

[2930/3663] ✓ UAN: 1,491 рядків |  79.99% | ETA 01:01

[2940/3663] ✓ UBT: 771 рядків |  80.26% | ETA 01:01

[2950/3663] ✓ UE: 3,300 рядків |  80.54% | ETA 01:00

   • RAM · 🧠 RAM: 578.0 MB

   ⏳ перед flush · 🧠 RAM: 578.0 MB

💾 batch 801 → 142,781 рядків (всього 1,861,172 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0801.csv.gz

   ✅ після flush · 🧠 RAM: 581.7 MB

[2960/3663] ✓ UFPI: 1,782 рядків |  80.81% | ETA 00:59

[2970/3663] ✓ UK: 141 рядків |  81.08% | ETA 00:59

[2980/3663] ✓ ULTI: 515 рядків |  81.35% | ETA 00:58

[2990/3663] ✓ UNF: 2,297 рядків |  81.63% | ETA 00:57

[3000/3663] ✓ UONE: 329 рядків |  81.90% | ETA 00:57

   • RAM · 🧠 RAM: 597.8 MB

   ⏳ перед flush · 🧠 RAM: 597.8 MB

💾 batch 802 → 143,286 рядків (всього 2,004,458 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0802.csv.gz

   ✅ після flush · 🧠 RAM: 599.3 MB

[3010/3663] ✓ UOKA: 11,493 рядків |  82.17% | ETA 00:56

[3020/3663] ✓ UPXI: 6,330 рядків |  82.45% | ETA 00:55

[3030/3663] ✓ USA: 3,042 рядків |  82.72% | ETA 00:55

[3040/3663] ✓ USEA: 1,105 рядків |  82.99% | ETA 00:54

[3050/3663] ✓ USHY: 3,985 рядків |  83.27% | ETA 00:53

   • RAM · 🧠 RAM: 622.5 MB

   ⏳ перед flush · 🧠 RAM: 622.5 MB

💾 batch 803 → 167,113 рядків (всього 2,171,571 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0803.csv.gz

   ✅ після flush · 🧠 RAM: 623.5 MB

[3060/3663] ✓ USTB: 1,475 рядків |  83.54% | ETA 00:52

[3070/3663] ✓ UTWO: 648 рядків |  83.81% | ETA 00:52

[3080/3663] – UWMCW: empty |  84.08% | ETA 00:51

[3090/3663] ✓ VAC: 2,905 рядків |  84.36% | ETA 00:50

[3100/3663] ✓ VBK: 3,500 рядків |  84.63% | ETA 00:49

   • RAM · 🧠 RAM: 639.7 MB

   ⏳ перед flush · 🧠 RAM: 639.9 MB

💾 batch 804 → 140,719 рядків (всього 2,312,290 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0804.csv.gz

   ✅ після flush · 🧠 RAM: 642.3 MB

[3110/3663] ✓ VCTR: 3,226 рядків |  84.90% | ETA 00:49

[3120/3663] ✓ VEEE: 6,419 рядків |  85.18% | ETA 00:48

[3130/3663] ✓ VEU: 4,294 рядків |  85.45% | ETA 00:47

[3140/3663] ✓ VGLT: 4,286 рядків |  85.72% | ETA 00:46

[3150/3663] ✓ VIG: 4,250 рядків |  86.00% | ETA 00:46

   • RAM · 🧠 RAM: 666.0 MB

   ⏳ перед flush · 🧠 RAM: 666.0 MB

💾 batch 805 → 173,504 рядків (всього 2,485,794 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0805.csv.gz

   ✅ після flush · 🧠 RAM: 668.7 MB

[3160/3663] ✓ VISN: 3,996 рядків |  86.27% | ETA 00:45

[3170/3663] ✓ VLTO: 3,645 рядків |  86.54% | ETA 00:44

[3180/3663] ✓ VNAM: 422 рядків |  86.81% | ETA 00:43

[3190/3663] ✓ VNRX: 2,458 рядків |  87.09% | ETA 00:43

[3200/3663] ✓ VOOV: 1,206 рядків |  87.36% | ETA 00:42

   • RAM · 🧠 RAM: 685.6 MB

   ⏳ перед flush · 🧠 RAM: 686.1 MB

💾 batch 806 → 148,656 рядків (всього 2,634,450 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0806.csv.gz

   ✅ після flush · 🧠 RAM: 691.0 MB

[3210/3663] ✓ VPLS: 1,674 рядків |  87.63% | ETA 00:41

[3220/3663] ✓ VRME: 1,147 рядків |  87.91% | ETA 00:40

[3230/3663] ✓ VRT: 7,589 рядків |  88.18% | ETA 00:39

[3240/3663] ✓ VSH: 3,749 рядків |  88.45% | ETA 00:39

[3250/3663] ✓ VTAK: 2,436 рядків |  88.73% | ETA 00:38

   • RAM · 🧠 RAM: 706.3 MB

   ⏳ перед flush · 🧠 RAM: 706.3 MB

💾 batch 807 → 137,952 рядків (всього 2,772,402 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0807.csv.gz

   ✅ після flush · 🧠 RAM: 708.6 MB

[3260/3663] ✓ VTR: 3,808 рядків |  89.00% | ETA 00:37

[3270/3663] ✓ VUZI: 3,366 рядків |  89.27% | ETA 00:36

[3280/3663] ✓ VYGR: 3,242 рядків |  89.54% | ETA 00:35

[3290/3663] ✓ WAB: 3,145 рядків |  89.82% | ETA 00:34

[3300/3663] ✓ WASH: 1,378 рядків |  90.09% | ETA 00:33

   • RAM · 🧠 RAM: 726.1 MB

   ⏳ перед flush · 🧠 RAM: 726.1 MB

💾 batch 808 → 155,267 рядків (всього 2,927,669 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0808.csv.gz

   ✅ після flush · 🧠 RAM: 729.6 MB

[3310/3663] ✓ WBTN: 3,029 рядків |  90.36% | ETA 00:33

[3320/3663] ✓ WDH: 960 рядків |  90.64% | ETA 00:32

[3330/3663] ✓ WEED: 103 рядків |  90.91% | ETA 00:31

[3340/3663] ✓ WERN: 3,471 рядків |  91.18% | ETA 00:30

[3350/3663] ✓ WFRD: 3,839 рядків |  91.46% | ETA 00:29

   • RAM · 🧠 RAM: 744.2 MB

   ⏳ перед flush · 🧠 RAM: 744.2 MB

💾 batch 809 → 127,053 рядків (всього 3,054,722 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0809.csv.gz

   ✅ після flush · 🧠 RAM: 755.3 MB

[3360/3663] – WILD: empty |  91.73% | ETA 00:28

[3370/3663] ✓ WIX: 4,497 рядків |  92.00% | ETA 00:27

[3380/3663] ✓ WLY: 2,753 рядків |  92.27% | ETA 00:26

[3390/3663] ✓ WMT: 6,838 рядків |  92.55% | ETA 00:25

[3400/3663] ✓ WPP: 3,189 рядків |  92.82% | ETA 00:25

   • RAM · 🧠 RAM: 765.4 MB

   ⏳ перед flush · 🧠 RAM: 765.4 MB

💾 batch 810 → 130,459 рядків (всього 3,185,181 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0810.csv.gz

   ✅ після flush · 🧠 RAM: 773.9 MB

[3410/3663] ✓ WRD: 5,018 рядків |  93.09% | ETA 00:24

[3420/3663] ✓ WT: 3,750 рядків |  93.37% | ETA 00:23

[3430/3663] ✓ WTV: 2,290 рядків |  93.64% | ETA 00:22

[3440/3663] ✓ WWR: 3,131 рядків |  93.91% | ETA 00:21

[3450/3663] ✓ XBCI: 455 рядків |  94.19% | ETA 00:20

   • RAM · 🧠 RAM: 783.6 MB

   ⏳ перед flush · 🧠 RAM: 783.6 MB

💾 batch 811 → 133,867 рядків (всього 3,319,048 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0811.csv.gz

   ✅ після flush · 🧠 RAM: 788.6 MB

[3460/3663] ✓ XCCC: 1,298 рядків |  94.46% | ETA 00:19

[3470/3663] ✓ XHG: 169 рядків |  94.73% | ETA 00:18

[3480/3663] ✓ XLKI: 112 рядків |  95.00% | ETA 00:17

[3490/3663] ✓ XLU: 5,220 рядків |  95.28% | ETA 00:16

[3500/3663] ✓ XNTK: 1,218 рядків |  95.55% | ETA 00:15

   • RAM · 🧠 RAM: 803.6 MB

   ⏳ перед flush · 🧠 RAM: 803.6 MB

💾 batch 812 → 132,825 рядків (всього 3,451,873 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0812.csv.gz

   ✅ після flush · 🧠 RAM: 807.7 MB

[3510/3663] ✓ XOP: 6,244 рядків |  95.82% | ETA 00:14

[3520/3663] ✓ XPRO: 3,476 рядків |  96.10% | ETA 00:13

[3530/3663] ✓ XRPR: 601 рядків |  96.37% | ETA 00:13

[3540/3663] ✓ XSMO: 2,623 рядків |  96.64% | ETA 00:12

[3550/3663] ✓ XXII: 467 рядків |  96.92% | ETA 00:11

   • RAM · 🧠 RAM: 818.3 MB

   ⏳ перед flush · 🧠 RAM: 818.3 MB

💾 batch 813 → 103,041 рядків (всього 3,554,914 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0813.csv.gz

   ✅ після flush · 🧠 RAM: 827.0 MB

[3560/3663] ✓ XYZG: 260 рядків |  97.19% | ETA 00:10

[3570/3663] ✓ YCL: 638 рядків |  97.46% | ETA 00:09

[3580/3663] ✓ YHGJ: 94 рядків |  97.73% | ETA 00:08

[3590/3663] ✓ YMT: 669 рядків |  98.01% | ETA 00:07

[3600/3663] ✓ YSG: 1,551 рядків |  98.28% | ETA 00:06

   • RAM · 🧠 RAM: 833.8 MB

   ⏳ перед flush · 🧠 RAM: 833.8 MB

💾 batch 814 → 97,309 рядків (всього 3,652,223 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0814.csv.gz

   ✅ після flush · 🧠 RAM: 839.3 MB

[3610/3663] ✓ YYGH: 5,889 рядків |  98.55% | ETA 00:05

[3620/3663] ✓ ZD: 3,819 рядків |  98.83% | ETA 00:04

[3630/3663] ✓ ZGN: 3,179 рядків |  99.10% | ETA 00:03

[3640/3663] ✓ ZLAB: 3,115 рядків |  99.37% | ETA 00:02

[3650/3663] ✓ ZS: 5,269 рядків |  99.65% | ETA 00:01

   • RAM · 🧠 RAM: 850.9 MB

   ⏳ перед flush · 🧠 RAM: 850.9 MB

💾 batch 815 → 111,180 рядків (всього 3,763,403 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0815.csv.gz

   ✅ після flush · 🧠 RAM: 858.2 MB

[3660/3663] – ZYXIQ: empty |  99.92% | ETA 00:00

[3663/3663] ✓ ZYME: 3,656 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 858.3 MB

💾 batch 816 → 38,615 рядків (всього 3,802,018 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0816.csv.gz

   ✅ після flush · 🧠 RAM: 858.3 MB

   🔚 фінал · 🧠 RAM: 858.3 MB

🏁 Готово. Нових рядків: 3,802,018 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 06:05

In [19]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [20]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2025-12-16..2026-03-16]

  [1/816] intraday_0001.csv.gz chunk 5  in=750,000  out=338,531  elapsed=1.0s

  [2/816] intraday_0002.csv.gz chunk 5  in=1,725,827  out=786,424  elapsed=2.4s

  [3/816] intraday_0003.csv.gz chunk 5  in=2,590,424  out=1,192,204  elapsed=3.6s

  [4/816] intraday_0004.csv.gz chunk 5  in=3,333,452  out=1,541,003  elapsed=4.6s

  [5/816] intraday_0005.csv.gz chunk 5  in=4,083,452  out=1,874,778  elapsed=5.6s

  [6/816] intraday_0006.csv.gz chunk 5  in=4,957,443  out=2,272,778  elapsed=6.8s

  [7/816] intraday_0007.csv.gz chunk 5  in=5,912,526  out=2,703,672  elapsed=8.1s

  [8/816] intraday_0008.csv.gz chunk 5  in=6,673,107  out=3,048,238  elapsed=9.2s

  [9/816] intraday_0009.csv.gz chunk 5  in=7,482,671  out=3,414,109  elapsed=10.3s

  [10/816] intraday_0010.csv.gz chunk 5  in=8,422,497  out=3,847,898  elapsed=11.6s

  [11/816] intraday_0011.csv.gz chunk 5  in=9,348,724  out=4,303,151  elapsed=12.9s

  [12/816] intraday_0012.csv.gz chunk 5  in=10,098,724  out=4,658,114  elapsed=13.9s

  [13/816] intraday_0013.csv.gz chunk 5  in=10,952,410  out=5,048,533  elapsed=15.1s

  [14/816] intraday_0014.csv.gz chunk 5  in=11,729,573  out=5,408,759  elapsed=16.1s

  [15/816] intraday_0015.csv.gz chunk 5  in=12,333,647  out=5,685,069  elapsed=17.0s

  [16/816] intraday_0016.csv.gz chunk 5  in=13,083,647  out=6,019,453  elapsed=18.0s

  [17/816] intraday_0017.csv.gz chunk 5  in=14,119,434  out=6,456,742  elapsed=19.4s

  [18/816] intraday_0018.csv.gz chunk 5  in=14,987,474  out=6,895,081  elapsed=20.6s

  [19/816] intraday_0019.csv.gz chunk 5  in=15,723,943  out=7,217,883  elapsed=21.6s

  [20/816] intraday_0020.csv.gz chunk 5  in=16,473,943  out=7,544,690  elapsed=22.6s

  [21/816] intraday_0021.csv.gz chunk 5  in=17,305,781  out=7,925,648  elapsed=23.7s

  [22/816] intraday_0022.csv.gz chunk 5  in=18,114,555  out=8,291,477  elapsed=24.8s

  [23/816] intraday_0023.csv.gz chunk 5  in=18,864,555  out=8,626,090  elapsed=25.8s

  [24/816] intraday_0024.csv.gz chunk 5  in=19,645,557  out=8,989,228  elapsed=26.9s

  [25/816] intraday_0025.csv.gz chunk 5  in=20,416,242  out=9,324,932  elapsed=28.0s

  [26/816] intraday_0026.csv.gz chunk 5  in=21,166,242  out=9,639,597  elapsed=28.9s

  [27/816] intraday_0027.csv.gz chunk 5  in=21,935,669  out=9,989,672  elapsed=30.0s

  [28/816] intraday_0028.csv.gz chunk 5  in=22,685,669  out=10,335,776  elapsed=31.0s

  [29/816] intraday_0029.csv.gz chunk 5  in=23,693,087  out=10,801,637  elapsed=32.4s

  [30/816] intraday_0030.csv.gz chunk 5  in=24,639,604  out=11,233,084  elapsed=33.7s

  [31/816] intraday_0031.csv.gz chunk 5  in=25,543,444  out=11,645,440  elapsed=35.0s

  [32/816] intraday_0032.csv.gz chunk 5  in=26,293,444  out=11,981,737  elapsed=36.0s

  [33/816] intraday_0033.csv.gz chunk 5  in=27,109,346  out=12,341,876  elapsed=37.1s

  [34/816] intraday_0034.csv.gz chunk 5  in=27,922,589  out=12,714,201  elapsed=38.2s

  [35/816] intraday_0035.csv.gz chunk 5  in=28,672,589  out=13,056,705  elapsed=39.3s

  [36/816] intraday_0036.csv.gz chunk 5  in=29,491,745  out=13,451,200  elapsed=40.4s

  [37/816] intraday_0037.csv.gz chunk 5  in=30,234,721  out=13,788,509  elapsed=41.5s

  [38/816] intraday_0038.csv.gz chunk 5  in=30,924,778  out=14,109,157  elapsed=42.4s

  [39/816] intraday_0039.csv.gz chunk 5  in=31,674,778  out=14,441,403  elapsed=43.4s

  [40/816] intraday_0040.csv.gz chunk 5  in=32,407,718  out=14,765,633  elapsed=44.4s

  [41/816] intraday_0041.csv.gz chunk 5  in=33,157,718  out=15,088,225  elapsed=45.4s

  [42/816] intraday_0042.csv.gz chunk 5  in=34,051,794  out=15,509,794  elapsed=46.6s

  [43/816] intraday_0043.csv.gz chunk 5  in=34,960,739  out=15,924,119  elapsed=48.0s

  [44/816] intraday_0044.csv.gz chunk 5  in=35,710,739  out=16,269,878  elapsed=49.0s

  [45/816] intraday_0045.csv.gz chunk 5  in=36,516,274  out=16,636,717  elapsed=50.1s

  [46/816] intraday_0046.csv.gz chunk 5  in=37,318,713  out=16,998,183  elapsed=51.2s

  [47/816] intraday_0047.csv.gz chunk 5  in=38,133,804  out=17,361,208  elapsed=52.3s

  [48/816] intraday_0048.csv.gz chunk 5  in=38,906,436  out=17,722,926  elapsed=53.3s

  [49/816] intraday_0049.csv.gz chunk 5  in=39,656,436  out=18,072,060  elapsed=54.4s

  [50/816] intraday_0050.csv.gz chunk 5  in=40,601,960  out=18,504,752  elapsed=55.7s

  [51/816] intraday_0051.csv.gz chunk 5  in=41,414,383  out=18,879,183  elapsed=56.8s

  [52/816] intraday_0052.csv.gz chunk 5  in=42,164,383  out=19,218,896  elapsed=57.8s

  [53/816] intraday_0053.csv.gz chunk 5  in=42,998,896  out=19,607,415  elapsed=58.9s

  [54/816] intraday_0054.csv.gz chunk 5  in=43,729,514  out=19,940,464  elapsed=59.9s

  [55/816] intraday_0055.csv.gz chunk 5  in=44,479,514  out=20,265,480  elapsed=61.0s

  [56/816] intraday_0056.csv.gz chunk 5  in=45,292,383  out=20,629,454  elapsed=62.1s

  [57/816] intraday_0057.csv.gz chunk 5  in=46,110,329  out=21,009,843  elapsed=63.2s

  [58/816] intraday_0058.csv.gz chunk 5  in=46,830,377  out=21,348,589  elapsed=64.2s

  [59/816] intraday_0059.csv.gz chunk 5  in=47,580,377  out=21,693,626  elapsed=65.3s

  [60/816] intraday_0060.csv.gz chunk 5  in=48,264,439  out=22,018,944  elapsed=66.2s

  [61/816] intraday_0061.csv.gz chunk 5  in=49,014,439  out=22,351,167  elapsed=67.2s

  [62/816] intraday_0062.csv.gz chunk 5  in=50,022,323  out=22,806,606  elapsed=68.6s

  [63/816] intraday_0063.csv.gz chunk 5  in=50,772,323  out=23,150,945  elapsed=69.6s

  [64/816] intraday_0064.csv.gz chunk 5  in=51,725,856  out=23,590,171  elapsed=71.0s

  [65/816] intraday_0065.csv.gz chunk 5  in=52,611,073  out=24,005,011  elapsed=72.2s

  [66/816] intraday_0066.csv.gz chunk 5  in=53,344,110  out=24,338,043  elapsed=73.3s

  [67/816] intraday_0067.csv.gz chunk 5  in=54,094,110  out=24,682,089  elapsed=74.3s

  [68/816] intraday_0068.csv.gz chunk 5  in=54,864,222  out=25,030,036  elapsed=75.3s

  [69/816] intraday_0069.csv.gz chunk 5  in=55,688,820  out=25,390,250  elapsed=76.4s

  [70/816] intraday_0070.csv.gz chunk 5  in=56,497,048  out=25,760,293  elapsed=77.8s

  [71/816] intraday_0071.csv.gz chunk 5  in=57,135,058  out=26,044,278  elapsed=78.7s

  [72/816] intraday_0072.csv.gz chunk 5  in=57,879,667  out=26,389,296  elapsed=79.9s

  [73/816] intraday_0073.csv.gz chunk 5  in=58,629,667  out=26,735,035  elapsed=81.6s

  [74/816] intraday_0074.csv.gz chunk 5  in=59,409,405  out=27,084,792  elapsed=82.6s

  [75/816] intraday_0075.csv.gz chunk 5  in=60,159,405  out=27,418,910  elapsed=83.7s

  [76/816] intraday_0076.csv.gz chunk 5  in=60,866,670  out=27,744,356  elapsed=84.7s

  [77/816] intraday_0077.csv.gz chunk 5  in=61,616,670  out=28,093,208  elapsed=85.7s

  [78/816] intraday_0078.csv.gz chunk 5  in=62,426,095  out=28,440,481  elapsed=86.9s

  [79/816] intraday_0079.csv.gz chunk 5  in=63,486,689  out=28,921,977  elapsed=88.4s

  [80/816] intraday_0080.csv.gz chunk 5  in=64,355,814  out=29,329,576  elapsed=89.6s

  [81/816] intraday_0081.csv.gz chunk 5  in=65,105,814  out=29,673,560  elapsed=90.6s

  [82/816] intraday_0082.csv.gz chunk 5  in=65,923,353  out=30,054,748  elapsed=91.7s

  [83/816] intraday_0083.csv.gz chunk 5  in=66,712,271  out=30,412,587  elapsed=92.9s

  [84/816] intraday_0084.csv.gz chunk 5  in=67,498,390  out=30,760,443  elapsed=94.0s

  [85/816] intraday_0085.csv.gz chunk 5  in=68,668,886  out=31,287,103  elapsed=95.6s

  [86/816] intraday_0086.csv.gz chunk 5  in=69,443,048  out=31,645,410  elapsed=96.7s

  [87/816] intraday_0087.csv.gz chunk 5  in=70,370,846  out=32,081,979  elapsed=98.0s

  [88/816] intraday_0088.csv.gz chunk 5  in=71,314,187  out=32,528,533  elapsed=99.4s

  [89/816] intraday_0089.csv.gz chunk 5  in=72,147,243  out=32,927,638  elapsed=100.5s

  [90/816] intraday_0090.csv.gz chunk 5  in=73,031,904  out=33,341,351  elapsed=101.7s

  [91/816] intraday_0091.csv.gz chunk 5  in=73,819,473  out=33,698,808  elapsed=102.8s

  [92/816] intraday_0092.csv.gz chunk 5  in=74,749,201  out=34,113,907  elapsed=104.1s

  [93/816] intraday_0093.csv.gz chunk 5  in=75,581,839  out=34,488,759  elapsed=105.2s

  [94/816] intraday_0094.csv.gz chunk 5  in=76,397,498  out=34,851,426  elapsed=106.4s

  [95/816] intraday_0095.csv.gz chunk 5  in=77,278,738  out=35,244,582  elapsed=107.6s

  [96/816] intraday_0096.csv.gz chunk 5  in=78,128,774  out=35,620,110  elapsed=108.8s

  [97/816] intraday_0097.csv.gz chunk 5  in=79,010,543  out=36,011,767  elapsed=110.1s

  [98/816] intraday_0098.csv.gz chunk 5  in=79,782,923  out=36,377,952  elapsed=111.1s

  [99/816] intraday_0099.csv.gz chunk 5  in=80,552,827  out=36,728,347  elapsed=112.2s

  [100/816] intraday_0100.csv.gz chunk 5  in=81,613,945  out=37,237,355  elapsed=113.7s

  [101/816] intraday_0101.csv.gz chunk 5  in=82,411,660  out=37,580,865  elapsed=114.8s

  [102/816] intraday_0102.csv.gz chunk 5  in=83,343,388  out=38,025,855  elapsed=116.1s

  [103/816] intraday_0103.csv.gz chunk 5  in=84,277,121  out=38,447,903  elapsed=117.4s

  [104/816] intraday_0104.csv.gz chunk 5  in=85,067,945  out=38,812,297  elapsed=118.5s

  [105/816] intraday_0105.csv.gz chunk 5  in=85,909,844  out=39,223,151  elapsed=119.7s

  [106/816] intraday_0106.csv.gz chunk 5  in=86,782,104  out=39,626,842  elapsed=120.9s

  [107/816] intraday_0107.csv.gz chunk 5  in=87,571,848  out=39,990,522  elapsed=122.0s

  [108/816] intraday_0108.csv.gz chunk 5  in=88,635,246  out=40,468,880  elapsed=123.5s

  [109/816] intraday_0109.csv.gz chunk 5  in=89,429,847  out=40,825,421  elapsed=124.7s

  [110/816] intraday_0110.csv.gz chunk 5  in=90,369,231  out=41,248,200  elapsed=126.0s

  [111/816] intraday_0111.csv.gz chunk 5  in=91,390,909  out=41,698,089  elapsed=127.4s

  [112/816] intraday_0112.csv.gz chunk 5  in=92,177,941  out=42,065,082  elapsed=128.6s

  [113/816] intraday_0113.csv.gz chunk 5  in=93,009,949  out=42,447,073  elapsed=129.8s

  [114/816] intraday_0114.csv.gz chunk 5  in=93,772,660  out=42,793,427  elapsed=130.9s

  [115/816] intraday_0115.csv.gz chunk 5  in=94,609,984  out=43,181,898  elapsed=132.0s

  [116/816] intraday_0116.csv.gz chunk 5  in=95,366,153  out=43,526,141  elapsed=133.2s

  [117/816] intraday_0117.csv.gz chunk 5  in=96,314,921  out=43,966,694  elapsed=134.6s

  [118/816] intraday_0118.csv.gz chunk 5  in=97,100,237  out=44,324,594  elapsed=135.8s

  [119/816] intraday_0119.csv.gz chunk 5  in=98,245,742  out=44,851,866  elapsed=137.5s

  [120/816] intraday_0120.csv.gz chunk 5  in=98,995,742  out=45,206,634  elapsed=138.7s

  [121/816] intraday_0121.csv.gz chunk 5  in=99,855,343  out=45,589,033  elapsed=139.9s

  [122/816] intraday_0122.csv.gz chunk 5  in=100,900,376  out=46,071,714  elapsed=141.4s

  [123/816] intraday_0123.csv.gz chunk 5  in=101,688,876  out=46,439,622  elapsed=142.5s

  [124/816] intraday_0124.csv.gz chunk 5  in=102,540,604  out=46,823,358  elapsed=143.7s

  [125/816] intraday_0125.csv.gz chunk 5  in=103,517,055  out=47,281,708  elapsed=145.1s

  [126/816] intraday_0126.csv.gz chunk 5  in=104,398,833  out=47,675,301  elapsed=146.3s

  [127/816] intraday_0127.csv.gz chunk 5  in=105,314,012  out=48,095,717  elapsed=147.6s

  [128/816] intraday_0128.csv.gz chunk 5  in=106,064,012  out=48,432,824  elapsed=148.7s

  [129/816] intraday_0129.csv.gz chunk 5  in=106,816,285  out=48,759,689  elapsed=149.9s

  [130/816] intraday_0130.csv.gz chunk 5  in=107,676,182  out=49,152,187  elapsed=151.1s

  [131/816] intraday_0131.csv.gz chunk 5  in=108,498,465  out=49,545,911  elapsed=152.4s

  [132/816] intraday_0132.csv.gz chunk 5  in=109,165,533  out=49,816,218  elapsed=153.3s

  [133/816] intraday_0133.csv.gz chunk 5  in=109,915,533  out=50,159,638  elapsed=154.3s

✅ DONE  in=170,816,322 → out=110,601,333  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 266.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [21]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [22]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [23]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [24]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=32.1s

[batch   10] rows=20,000,000  elapsed=64.1s

[batch   15] rows=30,000,000  elapsed=96.1s

[batch   20] rows=40,000,000  elapsed=128.1s

[batch   25] rows=50,000,000  elapsed=159.9s

[batch   30] rows=60,000,000  elapsed=192.0s

[batch   35] rows=70,000,000  elapsed=224.1s

[batch   40] rows=80,000,000  elapsed=256.4s

[batch   45] rows=90,000,000  elapsed=288.7s

[batch   50] rows=100,000,000  elapsed=320.5s

[batch   55] rows=110,000,000  elapsed=352.5s

✅ DONE  rows=110,601,333  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 356.6s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [25]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [26]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=4.5s

[batch   10] rows=20,000,000  elapsed=8.9s

[batch   15] rows=30,000,000  elapsed=13.3s

[batch   20] rows=40,000,000  elapsed=17.7s

[batch   25] rows=50,000,000  elapsed=22.2s

[batch   30] rows=60,000,000  elapsed=26.6s

[batch   35] rows=70,000,000  elapsed=31.0s

[batch   40] rows=80,000,000  elapsed=35.5s

[batch   45] rows=90,000,000  elapsed=39.9s

[batch   50] rows=100,000,000  elapsed=44.3s

[batch   55] rows=110,000,000  elapsed=48.8s

✅ DONE  rows=110,601,333  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 49.1s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [27]:
import os, re, time, math
import pandas as pd
from typing import Dict, List, Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


# ---------- НАДІЙНЕ ЧИТАННЯ МАПІНГУ (ticker, bench) ----------

def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Читає файл з відповідностями тікер↔бенч. Підтримка:
      - CSV (роздільник ; або , або \t), з/без заголовка
      - XLSX
      - Випадок "все в одній колонці": 'AAPL;SPY' / 'AAPL,SPY'
    Повертає DF: ['ticker','bench'] (UPPER, без дублікатів).
    """
    p = mapping_path
    ext = os.path.splitext(p)[1].lower()

    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(p)
    else:
        # 1) спроба autodetect
        try:
            df = pd.read_csv(p, sep=None, engine="python")
        except Exception:
            # 2) спроби з явними роздільниками
            for sep_try in (";", ",", "\t", "|"):
                try:
                    df = pd.read_csv(p, sep=sep_try, engine="python")
                    break
                except Exception:
                    df = None
            if df is None:
                # 3) можливо, файл без заголовка
                try:
                    df = pd.read_csv(p, header=None, sep=None, engine="python")
                except Exception:
                    # 4) остання спроба — явні сепаратори без заголовка
                    for sep_try in (";", ",", "\t", "|"):
                        try:
                            df = pd.read_csv(p, header=None, sep=sep_try, engine="python")
                            break
                        except Exception:
                            df = None
                    if df is None:
                        raise

    # Якщо одна колонка і виглядає як "AAPL;SPY" — сплітимо
    if df.shape[1] == 1:
        col = df.columns[0]
        # намагаємось розбити за ; або , або \t
        s = df[col].astype(str)
        if s.str.contains(";").any():
            parts = s.str.split(";", n=1, expand=True)
        elif s.str.contains(",").any():
            parts = s.str.split(",", n=1, expand=True)
        elif s.str.contains("\t").any():
            parts = s.str.split("\t", n=1, expand=True)
        else:
            raise KeyError("Не можу знайти роздільник між 'ticker' і 'bench'.")
        df = pd.DataFrame({"ticker": parts[0], "bench": parts[1]})

    # Вгадуємо назви колонок
    cols = {c.lower(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol")
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf")

    # Якщо заголовків нема, але 2 колонки — приймаємо їх як ticker/bench
    if tcol is None or bcol is None:
        if df.shape[1] >= 2:
            tcol = df.columns[0]
            bcol = df.columns[1]
        else:
            raise KeyError("Потрібні колонки 'ticker' і 'bench' у mapping-файлі.")

    out = (
        df[[tcol, bcol]]
        .rename(columns={tcol: "ticker", bcol: "bench"})
        .dropna()
    )
    out["ticker"] = out["ticker"].astype(str).str.strip().str.upper()
    out["bench"]  = out["bench"].astype(str).str.strip().str.upper()
    out = out[out["ticker"] != ""]
    out = out[out["bench"]  != ""]
    return out.drop_duplicates(ignore_index=True)


# ---------- ВИТЯГ corr/beta ДЛЯ ПАР (X, ФІКСОВАНИЙ BENCH) ----------

def _fetch_corr_beta_pairs(
    x_list: List[str],
    bench: str,
    *,
    period: str = "6 months",
    fmt: str = "json_records",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> pd.DataFrame:
    results: List[pd.DataFrame] = []
    i, n = 0, len(x_list)
    b = bench

    while i < n:
        cur_bs = min(batch_size, n - i)
        attempt = 0
        while True:
            xs = x_list[i : i + cur_bs]
            params = {
                "x_tickers": ",".join(xs),
                "y_tickers": b,
                "period": period,
                "as_pivot": False,
                "format": fmt,
            }
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)
                if df_chunk is not None and not df_chunk.empty:
                    # лишаємо тільки рядки для потрібного bench (на випадок, якщо API поверне зайве)
                    if "y_ticker" in df_chunk.columns:
                        df_chunk = df_chunk[df_chunk["y_ticker"].astype(str).str.upper() == b]
                    results.append(df_chunk)
                i += len(xs)
                time.sleep(pause)  # пауза тільки після успішного батча
                break
            except Exception as e:
                msg = str(e).lower()
                # 414: зменшуємо ЛИШЕ поточний батч
                if "414" in msg or "uri too large" in msg:
                    if cur_bs <= min_batch_size:
                        print(f"⚠️ 414 навіть при batch={cur_bs}. Пропускаю X[{i}:{i+cur_bs}] для {b}.")
                        i += cur_bs
                        break
                    new_bs = max(min_batch_size, cur_bs // 2)
                    print(f"⚠️ 414 → shrink {cur_bs} → {new_bs} для {b} і повторюю.")
                    cur_bs = new_bs
                    continue

                attempt += 1
                if attempt > max_retries:
                    print(f"⚠️  Пропуск X[{i}:{i+cur_bs}] для {b} після {max_reTRIES} ретраїв. Помилка: {e}")
                    i += cur_bs
                    break
                sleep_s = retry_backoff * (2 ** (attempt - 1))
                print(f"⚠️  {e} → retry {attempt}/{max_retries} через {sleep_s:.1f}s")
                time.sleep(sleep_s)

    return pd.concat(results, ignore_index=True) if results else pd.DataFrame()


# ---------- ГОЛОВНА ФУНКЦІЯ ----------

def corr_beta_from_mapping_to_parquet(
    mapping_path: str,
    out_parquet_path: str,
    *,
    period: str = "3 months",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> str:
    """
    Читає mapping (ticker, bench) будь-якого адекватного формату,
    групує тікери по бенчу, витягує corr/beta для кожної групи
    і потоково пише результат у Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для запису .parquet")

    map_df = _read_mapping(mapping_path)

    groups: Dict[str, List[str]] = (
        map_df.groupby("bench")["ticker"].apply(lambda s: sorted(set(s.tolist()))).to_dict()
    )

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    writer: Optional[pq.ParquetWriter] = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START corr/beta → {out_parquet_path} | період={period} | бенчів={len(groups)}")

    for b, xs in sorted(groups.items()):
        if not xs:
            continue
        print(f"— Bench {b}: {len(xs)} тикерів")
        df_b = _fetch_corr_beta_pairs(
            xs, b,
            period=period,
            batch_size=batch_size,
            min_batch_size=min_batch_size,
            pause=pause,
            max_retries=max_retries,
            retry_backoff=retry_backoff,
        )
        if df_b is None or df_b.empty:
            continue

        # типи
        for col in ("corr", "beta"):
            if col in df_b.columns:
                df_b[col] = pd.to_numeric(df_b[col], errors="coerce")

        table = pa.Table.from_pandas(df_b, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression="snappy")
        writer.write_table(table)
        total_rows += len(df_b)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path

In [28]:
out_path = corr_beta_from_mapping_to_parquet(
    mapping_path=str(WORK_DIR / "ticker_bench_.csv"),
    out_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    period="3 months",
    batch_size=150,
    pause=0.15,
)
print("Результат:", out_path)

▶️ START corr/beta → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet | період=3 months | бенчів=10
— Bench BITO: 45 тикерів

— Bench GDX: 117 тикерів

— Bench IWM: 2255 тикерів

— Bench KRE: 172 тикерів

— Bench KWEB: 38 тикерів

— Bench QQQ: 567 тикерів

— Bench SOXL: 16 тикерів

— Bench SPY: 3047 тикерів

— Bench XLE: 190 тикерів

— Bench XLF: 255 тикерів

✅ DONE rows=6,702 → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet  in 19.7s
Результат: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [29]:

y_list = ["SPY", "IWM", "GDX", "XLF", "QQQ", "XLE", "KRE", "BITO", "SOXL"]

In [30]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [31]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=9.8s

[batch   10] rows=20,000,000  elapsed=19.5s

[batch   15] rows=30,000,000  elapsed=29.3s

[batch   20] rows=40,000,000  elapsed=39.1s

[batch   25] rows=50,000,000  elapsed=48.9s

[batch   30] rows=60,000,000  elapsed=58.8s

[batch   35] rows=70,000,000  elapsed=68.5s

[batch   40] rows=80,000,000  elapsed=78.7s

[batch   45] rows=90,000,000  elapsed=88.9s

[batch   50] rows=100,000,000  elapsed=98.9s

[batch   55] rows=110,000,000  elapsed=108.7s

✅ DONE rows=110,601,333 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 109.4s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [32]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [33]:
peek_parquet("CRACEN/work/premarket_rows_final.parquet", n=620)

Файл: CRACEN/work/premarket_rows_final.parquet
Рядків (meta): 110,601,333
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:
    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench  corr  beta
0        A 2025-12-16 03:54:00  139.380005  139.380005  139.380005  139.380005       3.0  2025-12-16  140.48      140.59   -0.86   IWM  0.81   0.6
1        A 2025-12-16 08:31:00  140.990005  140.990005  140.990005  140.990005     100.0  2025-12-16  140.48      140.59    0.28   IWM  0.81   0.6
2        A 2025-12-16 09:30:00  140.479996  140.479996  139.919998  139.919998   16047.0  2025-12-16  140.48      140.59   -0.08   IWM  0.81   0.6
3        A 2025-12-16 09:31:00  140.455002  140.455002  139.550003  140.195007    2854.0  2025-12-16  140.48      140.59   -0.10   IWM  0.81   0.6
4        A 2025-12-16 09:32:00  140.195007  140.380005  140.149994  140.380005     800.0  2025-12-16  140.48      140.59   -0.28   IWM  0.81   0.6
5        A 2025-12-16 09:33:00  140.380005  140.506897  140.195007  140.195007     600.0  2025-12-16  140.48      140.59   -0.15   IWM  0.81   0.6
6        A 2025-12-16 09:34:00  140.059998  140.195007  139.869995  139.869995     700.0  2025-12-16  140.48      140.59   -0.38   IWM  0.81   0.6
7        A 2025-12-16 09:35:00  139.869995  140.377502  139.869995  140.324997     900.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6
8        A 2025-12-16 09:36:00  140.324997  140.324997  140.324997  140.324997     300.0  2025-12-16  140.48      140.59   -0.19   IWM  0.81   0.6
9        A 2025-12-16 09:37:00  139.869995  140.160004  139.869995  140.154999    1000.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6
10       A 2025-12-16 09:38:00  140.154999  140.154999  139.990005  140.154999    1234.0  2025-12-16  140.48      140.59   -0.31   IWM  0.81   0.6
11       A 2025-12-16 09:39:00  140.164993  140.164993  139.985001  139.990005    1468.0  2025-12-16  140.48      140.59   -0.30   IWM  0.81   0.6
12       A 2025-12-16 09:40:00  139.869995  140.235001  139.854996  139.967499    4552.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6
13       A 2025-12-16 09:41:00  139.960007  140.089996  139.850006  139.850006    2866.0  2025-12-16  140.48      140.59   -0.45   IWM  0.81   0.6
14       A 2025-12-16 09:42:00  139.919998  140.080002  139.919998  139.994995    2112.0  2025-12-16  140.48      140.59   -0.48   IWM  0.81   0.6
15       A 2025-12-16 09:43:00  139.994995  140.070007  139.940002  139.949997    1995.0  2025-12-16  140.48      140.59   -0.42   IWM  0.81   0.6
16       A 2025-12-16 09:44:00  139.919998  139.960007  139.785004  139.785004    1756.0  2025-12-16  140.48      140.59   -0.48   IWM  0.81   0.6
17       A 2025-12-16 09:45:00  139.794998  139.794998  139.690002  139.690002    3390.0  2025-12-16  140.48      140.59   -0.57   IWM  0.81   0.6
18       A 2025-12-16 09:46:00  139.585007  139.714996  139.414993  139.414993    1800.0  2025-12-16  140.48      140.59   -0.71   IWM  0.81   0.6
19       A 2025-12-16 09:47:00  139.529999  139.595001  139.529999  139.589996    3875.0  2025-12-16  140.48      140.59   -0.75   IWM  0.81   0.6
20       A 2025-12-16 09:48:00  139.585007  139.770004  139.429993  139.684998    3806.0  2025-12-16  140.48      140.59   -0.71   IWM  0.81   0.6
21       A 2025-12-16 09:49:00  139.679993  139.679993  139.570007  139.570007    1165.0  2025-12-16  140.48      140.59   -0.65   IWM  0.81   0.6
22       A 2025-12-16 09:50:00  139.570007  140.014999  139.570007  140.014999    3620.0  2025-12-16  140.48      140.59   -0.73   IWM  0.81   0.6
23       A 2025-12-16 09:51:00  140.074997  140.074997  139.854996  139.860001    1220.0  2025-12-16  140.48      140.59   -0.37   IWM  0.81   0.6
24       A 2025-12-16 09:52:00  139.744995  139.744995  139.729996  139.729996    1841.0  2025-12-16  140.48      140.59   -0.60   IWM  0.81   0.6
25       A 2025-12-16 09:53:00  139.725006  139.762497  139.600006  139.690002     616.0  2025-12-16  140.48      140.59   -0.62   IWM  0.81   0.6
26       A 2025-12-16 09:54:00  139.550003  139.740005  139.500000  139.625000    2203.0  2025-12-16  140.48      140.59   -0.74   IWM  0.81   0.6
27       A 2025-12-16 09:55:00  139.729996  139.899994  139.669998  139.889999    2400.0  2025-12-16  140.48      140.59   -0.61   IWM  0.81   0.6
28       A 2025-12-16 09:56:00  139.809998  139.979996  139.792496  139.904999    7703.0  2025-12-16  140.48      140.59   -0.55   IWM  0.81   0.6
29       A 2025-12-16 09:57:00  139.850006  139.850006  139.679993  139.684998    1339.0  2025-12-16  140.48      140.59   -0.53   IWM  0.81   0.6
30       A 2025-12-16 09:58:00  139.669998  139.669998  139.580002  139.580002    7692.0  2025-12-16  140.48      140.59   -0.65   IWM  0.81   0.6
31       A 2025-12-16 09:59:00  139.600006  139.679993  139.595001  139.679993     929.0  2025-12-16  140.48      140.59   -0.70   IWM  0.81   0.6
32       A 2025-12-16 10:00:00  139.690002  139.869995  139.679993  139.869995    3018.0  2025-12-16  140.48      140.59   -0.64   IWM  0.81   0.6
33       A 2025-12-16 10:01:00  139.714996  139.860001  139.699997  139.860001    1121.0  2025-12-16  140.48      140.59   -0.62   IWM  0.81   0.6
34       A 2025-12-16 10:02:00  139.710007  140.049896  139.710007  139.884995    1607.0  2025-12-16  140.48      140.59   -0.63   IWM  0.81   0.6
35       A 2025-12-16 10:03:00  139.720001  139.880005  139.720001  139.770096    2779.0  2025-12-16  140.48      140.59   -0.62   IWM  0.81   0.6
36       A 2025-12-16 10:04:00  139.839996  139.839996  139.839996  139.839996     400.0  2025-12-16  140.48      140.59   -0.53   IWM  0.81   0.6
37       A 2025-12-16 10:05:00  139.735001  139.884995  139.735001  139.884995    7871.0  2025-12-16  140.48      140.59   -0.61   IWM  0.81   0.6
38       A 2025-12-16 10:06:00  139.759995  139.860001  139.740005  139.860001    1902.0  2025-12-16  140.48      140.59   -0.59   IWM  0.81   0.6
39       A 2025-12-16 10:07:00  139.884995  139.889999  139.884995  139.889999     500.0  2025-12-16  140.48      140.59   -0.50   IWM  0.81   0.6
40       A 2025-12-16 10:08:00  139.880005  139.880005  139.740097  139.740097     200.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6
41       A 2025-12-16 10:09:00  139.904999  139.910004  139.904999  139.910004     700.0  2025-12-16  140.48      140.59   -0.49   IWM  0.81   0.6
42       A 2025-12-16 10:10:00  139.770004  139.904999  139.550003  139.580002    1800.0  2025-12-16  140.48      140.59   -0.58   IWM  0.81   0.6
43       A 2025-12-16 10:11:00  139.460007  139.551498  139.369995  139.369995    1599.0  2025-12-16  140.48      140.59   -0.80   IWM  0.81   0.6
44       A 2025-12-16 10:12:00  139.440002  139.529999  139.315002  139.315002     905.0  2025-12-16  140.48      140.59   -0.82   IWM  0.81   0.6
45       A 2025-12-16 10:13:00  139.369995  139.369995  139.300003  139.304993    1200.0  2025-12-16  140.48      140.59   -0.87   IWM  0.81   0.6
46       A 2025-12-16 10:14:00  139.369995  139.479996  139.317993  139.460007    1590.0  2025-12-16  140.48      140.59   -0.87   IWM  0.81   0.6
47       A 2025-12-16 10:15:00  139.469193  139.469193  139.250000  139.250000    2734.0  2025-12-16  140.48      140.59   -0.80   IWM  0.81   0.6
48       A 2025-12-16 10:16:00  139.190002  139.300003  139.190002  139.300003    1300.0  2025-12-16  140.48      140.59   -1.00   IWM  0.81   0.6
49       A 2025-12-16 10:17:00  139.179993  139.220001  139.154999  139.160004    1500.0  2025-12-16  140.48      140.59   -1.00   IWM  0.81   0.6
50       A 2025-12-16 10:18:00  139.154999  139.229996  139.070007  139.139999    2221.0  2025-12-16  140.48      140.59   -1.02   IWM  0.81   0.6
51       A 2025-12-16 10:19:00  139.138107  139.138107  139.138107  139.138107     100.0  2025-12-16  140.48      140.59   -1.03   IWM  0.81   0.6
52       A 2025-12-16 10:20:00  139.070099  139.145004  139.070007  139.145004     900.0  2025-12-16  140.48      140.59   -1.08   IWM  0.81   0.6
53       A 2025-12-16 10:21:00  139.149994  139.149994  138.899994  138.919998    2267.0  2025-12-16  140.48      140.59   -1.02   IWM  0.81   0.6
54       A 2025-12-16 10:22:00  138.839996  138.945007  138.835007  138.859604     930.0  2025-12-16  140.48      140.59   -1.24   IWM  0.81   0.6
55       A 2025-12-16 10:23:00  138.800003  139.050003  138.800003  139.050003    1200.0  2025-12-16  140.48      140.59   -1.27   IWM  0.81   0.6
56       A 2025-12-16 10:24:00  138.839996  138.960007  138.839996  138.960007    9036.0  2025-12-16  140.48      140.59   -1.24   IWM  0.81   0.6
57       A 2025-12-16 10:25:00  138.839996  138.839996  138.800003  138.800003     500.0  2025-12-16  140.48      140.59   -1.24   IWM  0.81   0.6
58       A 2025-12-16 10:26:00  138.895004  138.945007  138.895004  138.945007     800.0  2025-12-16  140.48      140.59   -1.21   IWM  0.81   0.6
59       A 2025-12-16 10:27:00  138.945007  139.020004  138.945007  138.945007     600.0  2025-12-16  140.48      140.59   -1.17   IWM  0.81   0.6
60       A 2025-12-16 10:28:00  138.945007  139.119995  138.945007  139.110001    3083.0  2025-12-16  140.48      140.59   -1.17   IWM  0.81   0.6
61       A 2025-12-16 10:29:00  139.110001  139.350006  139.110001  139.250000    2528.0  2025-12-16  140.48      140.59   -1.05   IWM  0.81   0.6
62       A 2025-12-16 10:30:00  139.279999  139.300003  139.279999  139.279999    1322.0  2025-12-16  140.48      140.59   -0.93   IWM  0.81   0.6
63       A 2025-12-16 10:31:00  139.250000  139.279999  139.250000  139.279999     400.0  2025-12-16  140.48      140.59   -0.95   IWM  0.81   0.6
64       A 2025-12-16 10:32:00  139.449997  139.520004  139.397995  139.397995    1160.0  2025-12-16  140.48      140.59   -0.81   IWM  0.81   0.6
65       A 2025-12-16 10:33:00  139.509995  139.570007  139.509995  139.520004    1284.0  2025-12-16  140.48      140.59   -0.77   IWM  0.81   0.6
66       A 2025-12-16 10:34:00  139.520004  139.520004  139.520004  139.520004     100.0  2025-12-16  140.48      140.59   -0.76   IWM  0.81   0.6
67       A 2025-12-16 10:35:00  139.410004  139.494995  139.350006  139.494995    1038.0  2025-12-16  140.48      140.59   -0.84   IWM  0.81   0.6
68       A 2025-12-16 10:36:00  139.360001  139.360001  139.100006  139.100006    1117.0  2025-12-16  140.48      140.59   -0.87   IWM  0.81   0.6
69       A 2025-12-16 10:37:00  139.080002  139.110001  139.009995  139.039993     800.0  2025-12-16  140.48      140.59   -1.07   IWM  0.81   0.6
70       A 2025-12-16 10:38:00  138.990005  139.005005  138.979996  138.999802    1427.0  2025-12-16  140.48      140.59   -1.14   IWM  0.81   0.6
71       A 2025-12-16 10:39:00  138.997498  139.009995  138.997498  139.009995     850.0  2025-12-16  140.48      140.59   -1.13   IWM  0.81   0.6
72       A 2025-12-16 10:40:00  139.089996  139.089996  138.889999  138.899994    2530.0  2025-12-16  140.48      140.59   -1.07   IWM  0.81   0.6
73       A 2025-12-16 10:41:00  138.975006  138.975006  138.975006  138.975006     100.0  2025-12-16  140.48      140.59   -1.15   IWM  0.81   0.6
74       A 2025-12-16 10:42:00  138.948196  138.994995  138.869995  138.960007    1665.0  2025-12-16  140.48      140.59   -1.17   IWM  0.81   0.6
75       A 2025-12-16 10:43:00  138.970001  138.970001  138.970001  138.970001     100.0  2025-12-16  140.48      140.59   -1.15   IWM  0.81   0.6
76       A 2025-12-16 10:44:00  138.889999  138.890106  138.889999  138.890106     831.0  2025-12-16  140.48      140.59   -1.21   IWM  0.81   0.6
77       A 2025-12-16 10:45:00  138.985001  139.050003  138.789993  138.789993    2869.0  2025-12-16  140.48      140.59   -1.14   IWM  0.81   0.6
78       A 2025-12-16 10:46:00  138.860001  138.865005  138.796005  138.796005    1741.0  2025-12-16  140.48      140.59   -1.23   IWM  0.81   0.6
79       A 2025-12-16 10:47:00  138.779999  138.835007  138.750000  138.759995     900.0  2025-12-16  140.48      140.59   -1.29   IWM  0.81   0.6
80       A 2025-12-16 10:48:00  138.710007  138.800003  138.710007  138.800003     900.0  2025-12-16  140.48      140.59   -1.34   IWM  0.81   0.6
81       A 2025-12-16 10:49:00  138.725006  138.800003  138.720001  138.720001    1042.0  2025-12-16  140.48      140.59   -1.33   IWM  0.81   0.6
82       A 2025-12-16 10:50:00  138.720001  138.720001  138.589996  138.589996    1341.0  2025-12-16  140.48      140.59   -1.33   IWM  0.81   0.6
83       A 2025-12-16 10:51:00  138.645004  138.649994  138.529999  138.649994     807.0  2025-12-16  140.48      140.59   -1.38   IWM  0.81   0.6
84       A 2025-12-16 10:52:00  138.649994  138.660004  138.630005  138.630005     600.0  2025-12-16  140.48      140.59   -1.38   IWM  0.81   0.6
85       A 2025-12-16 10:53:00  138.654999  138.725006  138.654999  138.654999     700.0  2025-12-16  140.48      140.59   -1.38   IWM  0.81   0.6
86       A 2025-12-16 10:54:00  138.729996  138.789993  138.664993  138.729996     750.0  2025-12-16  140.48      140.59   -1.32   IWM  0.81   0.6
87       A 2025-12-16 10:55:00  138.669998  138.669998  138.669998  138.669998     400.0  2025-12-16  140.48      140.59   -1.37   IWM  0.81   0.6
88       A 2025-12-16 10:56:00  138.699997  138.699997  138.660004  138.699997    1100.0  2025-12-16  140.48      140.59   -1.34   IWM  0.81   0.6
89       A 2025-12-16 10:57:00  138.589996  138.589996  138.300003  138.300003    2394.0  2025-12-16  140.48      140.59   -1.42   IWM  0.81   0.6
90       A 2025-12-16 10:58:00  138.259995  138.389999  138.259995  138.324997    1000.0  2025-12-16  140.48      140.59   -1.66   IWM  0.81   0.6
91       A 2025-12-16 10:59:00  138.384995  138.384995  138.244995  138.264999    1365.0  2025-12-16  140.48      140.59   -1.57   IWM  0.81   0.6
92       A 2025-12-16 11:00:00  138.229996  138.369995  138.229996  138.300003    1010.0  2025-12-16  140.48      140.59   -1.68   IWM  0.81   0.6
93       A 2025-12-16 11:01:00  138.440002  138.440002  138.250000  138.250000    1073.0  2025-12-16  140.48      140.59   -1.53   IWM  0.81   0.6
94       A 2025-12-16 11:02:00  138.335007  138.479996  138.335007  138.470001    2580.0  2025-12-16  140.48      140.59   -1.60   IWM  0.81   0.6
95       A 2025-12-16 11:03:00  138.529999  138.695099  138.529999  138.690002     876.0  2025-12-16  140.48      140.59   -1.47   IWM  0.81   0.6
96       A 2025-12-16 11:04:00  138.679993  138.679993  138.679993  138.679993     100.0  2025-12-16  140.48      140.59   -1.36   IWM  0.81   0.6
97       A 2025-12-16 11:05:00  138.690002  138.690002  138.528702  138.528702     893.0  2025-12-16  140.48      140.59   -1.35   IWM  0.81   0.6
98       A 2025-12-16 11:06:00  138.619995  138.690002  138.610001  138.690002     400.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6
99       A 2025-12-16 11:07:00  138.550003  138.565002  138.529999  138.529999     398.0  2025-12-16  140.48      140.59   -1.45   IWM  0.81   0.6
100      A 2025-12-16 11:08:00  138.460007  138.600006  138.460007  138.600006    1596.0  2025-12-16  140.48      140.59   -1.52   IWM  0.81   0.6
101      A 2025-12-16 11:10:00  138.714996  139.059998  138.714996  139.059998    2761.0  2025-12-16  140.48      140.59   -1.33   IWM  0.81   0.6
102      A 2025-12-16 11:11:00  138.804993  138.910004  138.804993  138.910004     400.0  2025-12-16  140.48      140.59   -1.27   IWM  0.81   0.6
103      A 2025-12-16 11:12:00  138.800003  138.809998  138.600006  138.600006    1893.0  2025-12-16  140.48      140.59   -1.27   IWM  0.81   0.6
104      A 2025-12-16 11:13:00  138.604996  138.604996  138.580002  138.580002     400.0  2025-12-16  140.48      140.59   -1.41   IWM  0.81   0.6
105      A 2025-12-16 11:14:00  138.759995  138.759995  138.744995  138.750000     300.0  2025-12-16  140.48      140.59   -1.30   IWM  0.81   0.6
106      A 2025-12-16 11:15:00  138.669998  138.720001  138.649994  138.720001     413.0  2025-12-16  140.48      140.59   -1.37   IWM  0.81   0.6
107      A 2025-12-16 11:16:00  138.695007  138.695007  138.520004  138.520004    1592.0  2025-12-16  140.48      140.59   -1.35   IWM  0.81   0.6
108      A 2025-12-16 11:17:00  138.429993  138.494995  138.404999  138.494995     700.0  2025-12-16  140.48      140.59   -1.54   IWM  0.81   0.6
109      A 2025-12-16 11:18:00  138.475006  138.589996  138.470001  138.589996    1500.0  2025-12-16  140.48      140.59   -1.50   IWM  0.81   0.6
110      A 2025-12-16 11:19:00  138.610001  138.610001  138.610001  138.610001     100.0  2025-12-16  140.48      140.59   -1.41   IWM  0.81   0.6
111      A 2025-12-16 11:20:00  138.614899  138.690002  138.490005  138.490005     400.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6
112      A 2025-12-16 11:21:00  138.524994  138.600006  138.524994  138.580795     460.0  2025-12-16  140.48      140.59   -1.47   IWM  0.81   0.6
113      A 2025-12-16 11:22:00  138.619995  138.630005  138.449997  138.449997    3493.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6
114      A 2025-12-16 11:23:00  138.440002  138.440002  138.340103  138.429993     625.0  2025-12-16  140.48      140.59   -1.53   IWM  0.81   0.6
115      A 2025-12-16 11:24:00  138.360001  138.360001  138.360001  138.360001     100.0  2025-12-16  140.48      140.59   -1.59   IWM  0.81   0.6
116      A 2025-12-16 11:26:00  138.429993  138.460007  138.389999  138.389999     400.0  2025-12-16  140.48      140.59   -1.54   IWM  0.81   0.6
117      A 2025-12-16 11:27:00  138.475006  138.475006  138.375000  138.375000    1048.0  2025-12-16  140.48      140.59   -1.50   IWM  0.81   0.6
118      A 2025-12-16 11:28:00  138.509995  138.649994  138.410004  138.610001    3170.0  2025-12-16  140.48      140.59   -1.48   IWM  0.81   0.6
119      A 2025-12-16 11:29:00  138.615005  138.669998  138.490005  138.570007    3331.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6
120      A 2025-12-16 11:30:00  138.570007  138.570007  138.529999  138.529999     300.0  2025-12-16  140.48      140.59   -1.44   IWM  0.81   0.6
121      A 2025-12-16 11:31:00  138.574997  138.869995  138.574997  138.869995   10235.0  2025-12-16  140.48      140.59   -1.43   IWM  0.81   0.6
122      A 2025-12-16 11:32:00  139.039993  139.039993  138.880005  138.880005    1004.0  2025-12-16  140.48      140.59   -1.10   IWM  0.81   0.6
123      A 2025-12-16 11:33:00  138.899994  138.970001  138.899994  138.910004     500.0  2025-12-16  140.48      140.59   -1.20   IWM  0.81   0.6
124      A 2025-12-16 11:34:00  138.914993  138.914993  138.809998  138.809998     411.0  2025-12-16  140.48      140.59   -1.19   IWM  0.81   0.6
125      A 2025-12-16 11:35:00  138.889999  138.889999  138.889999  138.889999     400.0  2025-12-16  140.48      140.59   -1.21   IWM  0.81   0.6
126      A 2025-12-16 11:36:00  138.889999  138.889999  138.779999  138.809998    1900.0  2025-12-16  140.48      140.59   -1.21   IWM  0.81   0.6
127      A 2025-12-16 11:37:00  138.740005  138.750000  138.649994  138.649994    1000.0  2025-12-16  140.48      140.59   -1.32   IWM  0.81   0.6
128      A 2025-12-16 11:40:00  138.764999  138.764999  138.759995  138.759995     380.0  2025-12-16  140.48      140.59   -1.30   IWM  0.81   0.6
129      A 2025-12-16 11:41:00  138.684692  138.684692  138.610001  138.615005    1435.0  2025-12-16  140.48      140.59   -1.36   IWM  0.81   0.6
130      A 2025-12-16 11:42:00  138.639999  138.669998  138.617599  138.617599     912.0  2025-12-16  140.48      140.59   -1.39   IWM  0.81   0.6
131      A 2025-12-16 11:46:00  138.630005  138.630005  138.570099  138.570099     500.0  2025-12-16  140.48      140.59   -1.39   IWM  0.81   0.6
132      A 2025-12-16 11:47:00  138.580002  138.639999  138.570007  138.600006    1099.0  2025-12-16  140.48      140.59   -1.43   IWM  0.81   0.6

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2025-12-16 03:54:00,139.380005,139.380005,139.380005,139.380005,3.0,2025-12-16,140.48,140.59,-0.86,IWM,0.81,0.6
1,A,2025-12-16 08:31:00,140.990005,140.990005,140.990005,140.990005,100.0,2025-12-16,140.48,140.59,0.28,IWM,0.81,0.6
2,A,2025-12-16 09:30:00,140.479996,140.479996,139.919998,139.919998,16047.0,2025-12-16,140.48,140.59,-0.08,IWM,0.81,0.6
3,A,2025-12-16 09:31:00,140.455002,140.455002,139.550003,140.195007,2854.0,2025-12-16,140.48,140.59,-0.10,IWM,0.81,0.6
4,A,2025-12-16 09:32:00,140.195007,140.380005,140.149994,140.380005,800.0,2025-12-16,140.48,140.59,-0.28,IWM,0.81,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2025-12-17 13:19:00,137.889999,137.889999,137.884995,137.884995,200.0,2025-12-17,138.67,139.18,-0.93,IWM,0.81,0.6
616,A,2025-12-17 13:20:00,137.800003,137.895004,137.800003,137.895004,1794.0,2025-12-17,138.67,139.18,-0.99,IWM,0.81,0.6
617,A,2025-12-17 13:21:00,137.830002,137.869995,137.779999,137.779999,1207.0,2025-12-17,138.67,139.18,-0.97,IWM,0.81,0.6
618,A,2025-12-17 13:22:00,137.869995,137.869995,137.869995,137.869995,400.0,2025-12-17,138.67,139.18,-0.94,IWM,0.81,0.6
619,A,2025-12-17 13:23:00,137.910004,137.910004,137.759995,137.800003,1100.0,2025-12-17,138.67,139.18,-0.91,IWM,0.81,0.6

In [34]:
# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [35]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=9,
    parallel_tickers=True,
    max_workers_tickers=4,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,   # ⬅️ додай це
)

▶ Починаємо: 10 тікерів (пропущено 0 по старому маніфесту) | 2025-12-16 00:00:00 → 2026-03-16 23:59:59 | interval=1 | next batch #0026 | run=850b45f8

   workers: tickers=4, chunks=9 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2025-12-16 → 2026-03-16 (89 днів)

   📈 обробляються дні: 2026-03-07 → 2026-03-14 (2 днів)

   psutil · старт · 🧠 RAM: 2,574.7 MB

[10/10] – SOXL: empty | 100.00% | ETA 00:00

   🔚 фінал · 🧠 RAM: 2,580.4 MB

🏁 Готово. Нових рядків: 0 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:00

In [36]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

✅ DONE  in=909,364 → out=909,364  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 2.0s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [37]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [38]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [39]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=909,364  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 1.6s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [40]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [41]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=909,364  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 0.4s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [42]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [43]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=11.0s

[batch   10] rows=20,000,000  elapsed=22.0s

[batch   15] rows=30,000,000  elapsed=33.1s

[batch   20] rows=40,000,000  elapsed=44.6s

[batch   25] rows=50,000,000  elapsed=56.3s

[batch   30] rows=60,000,000  elapsed=67.8s

[batch   35] rows=70,000,000  elapsed=79.0s

[batch   40] rows=80,000,000  elapsed=89.9s

[batch   45] rows=90,000,000  elapsed=100.9s

[batch   50] rows=100,000,000  elapsed=111.8s

[batch   55] rows=110,000,000  elapsed=122.6s

✅ DONE rows=110,601,333 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 123.5s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [44]:
import pandas as pd
from tqdm import tqdm   # прогрес-бар

def get_gaps_for_tickers(tickers_df, start_date, end_date):
    """
    Отримує гепи для всіх тикерів із DataFrame tickers_df (колонка 'ticker').
    Використовує ендпоінт /daily/gaps і об’єднує всі результати у один DataFrame.
    """
    all_results = []

    tickers = tickers_df["ticker"].dropna().astype(str).unique().tolist()

    for t in tqdm(tickers, desc="Processing tickers"):
        params = {
            "ticker": t,
            "start_date": start_date,
            "end_date": end_date,
            "format": "json_records"
        }

        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is not None and not df_gap.empty:
                all_results.append(df_gap)
        except Exception as e:
            print(f"⚠️ Проблема з {t}: {e}")

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    else:
        return pd.DataFrame()

# === приклад використання ===
df_gaps_all = get_gaps_for_tickers(top1500, start_date = start_date_str, end_date = end_date_str)

print(df_gaps_all.head())
print("Загалом рядків:", len(df_gaps_all))

Processing tickers:   0%|          | 0/6855 [00:00<?, ?it/s]

Processing tickers:   0%|          | 1/6855 [00:00<32:24,  3.52it/s]

Processing tickers:   0%|          | 2/6855 [00:00<27:05,  4.22it/s]

Processing tickers:   0%|          | 3/6855 [00:00<26:01,  4.39it/s]

Processing tickers:   0%|          | 4/6855 [00:00<25:14,  4.52it/s]

Processing tickers:   0%|          | 5/6855 [00:01<24:53,  4.59it/s]

Processing tickers:   0%|          | 6/6855 [00:01<24:33,  4.65it/s]

Processing tickers:   0%|          | 7/6855 [00:01<24:36,  4.64it/s]

Processing tickers:   0%|          | 8/6855 [00:01<24:21,  4.68it/s]

Processing tickers:   0%|          | 9/6855 [00:01<24:07,  4.73it/s]

Processing tickers:   0%|          | 10/6855 [00:02<24:24,  4.67it/s]

Processing tickers:   0%|          | 11/6855 [00:02<24:11,  4.72it/s]

Processing tickers:   0%|          | 12/6855 [00:02<23:51,  4.78it/s]

Processing tickers:   0%|          | 13/6855 [00:02<23:50,  4.78it/s]

Processing tickers:   0%|          | 14/6855 [00:03<23:55,  4.77it/s]

Processing tickers:   0%|          | 15/6855 [00:03<23:48,  4.79it/s]

Processing tickers:   0%|          | 16/6855 [00:03<23:49,  4.78it/s]

Processing tickers:   0%|          | 17/6855 [00:03<24:10,  4.71it/s]

Processing tickers:   0%|          | 18/6855 [00:03<24:55,  4.57it/s]

Processing tickers:   0%|          | 19/6855 [00:04<24:35,  4.63it/s]

Processing tickers:   0%|          | 20/6855 [00:04<24:23,  4.67it/s]

Processing tickers:   0%|          | 21/6855 [00:04<24:53,  4.58it/s]

Processing tickers:   0%|          | 22/6855 [00:04<25:32,  4.46it/s]

Processing tickers:   0%|          | 23/6855 [00:04<25:07,  4.53it/s]

Processing tickers:   0%|          | 24/6855 [00:05<24:45,  4.60it/s]

Processing tickers:   0%|          | 25/6855 [00:05<24:55,  4.57it/s]

Processing tickers:   0%|          | 26/6855 [00:05<24:35,  4.63it/s]

Processing tickers:   0%|          | 27/6855 [00:05<24:46,  4.59it/s]

Processing tickers:   0%|          | 28/6855 [00:06<24:19,  4.68it/s]

Processing tickers:   0%|          | 29/6855 [00:06<24:11,  4.70it/s]

Processing tickers:   0%|          | 30/6855 [00:06<24:05,  4.72it/s]

Processing tickers:   0%|          | 31/6855 [00:06<24:46,  4.59it/s]

Processing tickers:   0%|          | 32/6855 [00:06<24:26,  4.65it/s]

Processing tickers:   0%|          | 33/6855 [00:07<24:34,  4.63it/s]

Processing tickers:   0%|          | 34/6855 [00:07<24:21,  4.67it/s]

Processing tickers:   1%|          | 35/6855 [00:07<24:00,  4.74it/s]

Processing tickers:   1%|          | 36/6855 [00:07<23:47,  4.78it/s]

Processing tickers:   1%|          | 37/6855 [00:07<23:49,  4.77it/s]

Processing tickers:   1%|          | 38/6855 [00:08<24:29,  4.64it/s]

Processing tickers:   1%|          | 39/6855 [00:08<24:11,  4.69it/s]

Processing tickers:   1%|          | 40/6855 [00:08<24:09,  4.70it/s]

Processing tickers:   1%|          | 41/6855 [00:08<24:22,  4.66it/s]

Processing tickers:   1%|          | 42/6855 [00:09<24:20,  4.66it/s]

Processing tickers:   1%|          | 43/6855 [00:09<25:06,  4.52it/s]

Processing tickers:   1%|          | 44/6855 [00:09<24:32,  4.62it/s]

Processing tickers:   1%|          | 45/6855 [00:09<24:31,  4.63it/s]

Processing tickers:   1%|          | 46/6855 [00:09<24:21,  4.66it/s]

Processing tickers:   1%|          | 47/6855 [00:10<24:31,  4.63it/s]

Processing tickers:   1%|          | 48/6855 [00:10<24:22,  4.65it/s]

Processing tickers:   1%|          | 49/6855 [00:10<24:34,  4.61it/s]

Processing tickers:   1%|          | 50/6855 [00:10<24:58,  4.54it/s]

Processing tickers:   1%|          | 51/6855 [00:11<25:21,  4.47it/s]

Processing tickers:   1%|          | 52/6855 [00:11<24:48,  4.57it/s]

Processing tickers:   1%|          | 53/6855 [00:11<24:27,  4.64it/s]

Processing tickers:   1%|          | 54/6855 [00:11<24:11,  4.69it/s]

Processing tickers:   1%|          | 55/6855 [00:11<23:53,  4.74it/s]

Processing tickers:   1%|          | 56/6855 [00:12<23:58,  4.73it/s]

Processing tickers:   1%|          | 57/6855 [00:12<23:43,  4.78it/s]

Processing tickers:   1%|          | 58/6855 [00:12<23:39,  4.79it/s]

Processing tickers:   1%|          | 59/6855 [00:12<23:57,  4.73it/s]

Processing tickers:   1%|          | 60/6855 [00:12<23:48,  4.76it/s]

Processing tickers:   1%|          | 61/6855 [00:13<23:43,  4.77it/s]

Processing tickers:   1%|          | 62/6855 [00:13<23:42,  4.77it/s]

Processing tickers:   1%|          | 63/6855 [00:13<23:37,  4.79it/s]

Processing tickers:   1%|          | 64/6855 [00:13<23:32,  4.81it/s]

Processing tickers:   1%|          | 65/6855 [00:13<23:35,  4.80it/s]

Processing tickers:   1%|          | 66/6855 [00:14<24:15,  4.66it/s]

Processing tickers:   1%|          | 67/6855 [00:14<24:06,  4.69it/s]

Processing tickers:   1%|          | 68/6855 [00:14<23:55,  4.73it/s]

Processing tickers:   1%|          | 69/6855 [00:14<23:52,  4.74it/s]

Processing tickers:   1%|          | 70/6855 [00:15<23:47,  4.75it/s]

Processing tickers:   1%|          | 71/6855 [00:15<23:46,  4.75it/s]

Processing tickers:   1%|          | 72/6855 [00:15<23:48,  4.75it/s]

Processing tickers:   1%|          | 73/6855 [00:15<23:40,  4.78it/s]

Processing tickers:   1%|          | 74/6855 [00:15<23:49,  4.74it/s]

Processing tickers:   1%|          | 75/6855 [00:16<24:28,  4.62it/s]

Processing tickers:   1%|          | 76/6855 [00:16<24:06,  4.69it/s]

Processing tickers:   1%|          | 77/6855 [00:16<24:13,  4.66it/s]

Processing tickers:   1%|          | 78/6855 [00:16<24:23,  4.63it/s]

Processing tickers:   1%|          | 79/6855 [00:16<24:15,  4.66it/s]

Processing tickers:   1%|          | 80/6855 [00:17<24:05,  4.69it/s]

Processing tickers:   1%|          | 81/6855 [00:17<23:46,  4.75it/s]

Processing tickers:   1%|          | 82/6855 [00:17<23:38,  4.77it/s]

Processing tickers:   1%|          | 83/6855 [00:17<23:40,  4.77it/s]

Processing tickers:   1%|          | 84/6855 [00:17<24:17,  4.64it/s]

Processing tickers:   1%|          | 85/6855 [00:18<24:59,  4.52it/s]

Processing tickers:   1%|▏         | 86/6855 [00:18<25:15,  4.47it/s]

Processing tickers:   1%|▏         | 87/6855 [00:18<24:31,  4.60it/s]

Processing tickers:   1%|▏         | 88/6855 [00:18<24:12,  4.66it/s]

Processing tickers:   1%|▏         | 89/6855 [00:19<24:02,  4.69it/s]

Processing tickers:   1%|▏         | 90/6855 [00:19<23:54,  4.72it/s]

Processing tickers:   1%|▏         | 91/6855 [00:19<23:51,  4.73it/s]

Processing tickers:   1%|▏         | 92/6855 [00:19<24:07,  4.67it/s]

Processing tickers:   1%|▏         | 93/6855 [00:19<23:52,  4.72it/s]

Processing tickers:   1%|▏         | 94/6855 [00:20<23:37,  4.77it/s]

Processing tickers:   1%|▏         | 95/6855 [00:20<23:42,  4.75it/s]

Processing tickers:   1%|▏         | 96/6855 [00:20<23:28,  4.80it/s]

Processing tickers:   1%|▏         | 97/6855 [00:20<23:29,  4.80it/s]

Processing tickers:   1%|▏         | 98/6855 [00:20<23:28,  4.80it/s]

Processing tickers:   1%|▏         | 99/6855 [00:21<23:19,  4.83it/s]

Processing tickers:   1%|▏         | 100/6855 [00:21<23:22,  4.82it/s]

Processing tickers:   1%|▏         | 101/6855 [00:21<23:38,  4.76it/s]

Processing tickers:   1%|▏         | 102/6855 [00:21<23:36,  4.77it/s]

Processing tickers:   2%|▏         | 103/6855 [00:22<24:10,  4.65it/s]

Processing tickers:   2%|▏         | 104/6855 [00:22<24:14,  4.64it/s]

Processing tickers:   2%|▏         | 105/6855 [00:22<24:41,  4.56it/s]

Processing tickers:   2%|▏         | 106/6855 [00:22<25:06,  4.48it/s]

Processing tickers:   2%|▏         | 107/6855 [00:22<24:50,  4.53it/s]

Processing tickers:   2%|▏         | 108/6855 [00:23<24:37,  4.57it/s]

Processing tickers:   2%|▏         | 109/6855 [00:23<24:17,  4.63it/s]

Processing tickers:   2%|▏         | 110/6855 [00:23<23:53,  4.71it/s]

Processing tickers:   2%|▏         | 111/6855 [00:23<23:43,  4.74it/s]

Processing tickers:   2%|▏         | 112/6855 [00:23<23:37,  4.76it/s]

Processing tickers:   2%|▏         | 113/6855 [00:24<23:21,  4.81it/s]

Processing tickers:   2%|▏         | 114/6855 [00:24<23:11,  4.85it/s]

Processing tickers:   2%|▏         | 115/6855 [00:24<23:16,  4.83it/s]

Processing tickers:   2%|▏         | 116/6855 [00:24<23:17,  4.82it/s]

Processing tickers:   2%|▏         | 117/6855 [00:25<23:24,  4.80it/s]

Processing tickers:   2%|▏         | 118/6855 [00:25<23:21,  4.81it/s]

Processing tickers:   2%|▏         | 119/6855 [00:25<23:17,  4.82it/s]

Processing tickers:   2%|▏         | 120/6855 [00:25<23:48,  4.72it/s]

Processing tickers:   2%|▏         | 121/6855 [00:25<24:27,  4.59it/s]

Processing tickers:   2%|▏         | 122/6855 [00:26<24:14,  4.63it/s]

Processing tickers:   2%|▏         | 123/6855 [00:26<23:58,  4.68it/s]

Processing tickers:   2%|▏         | 124/6855 [00:26<24:30,  4.58it/s]

Processing tickers:   2%|▏         | 125/6855 [00:26<24:49,  4.52it/s]

Processing tickers:   2%|▏         | 126/6855 [00:26<25:12,  4.45it/s]

Processing tickers:   2%|▏         | 127/6855 [00:27<24:36,  4.56it/s]

Processing tickers:   2%|▏         | 128/6855 [00:27<24:16,  4.62it/s]

Processing tickers:   2%|▏         | 129/6855 [00:27<24:07,  4.65it/s]

Processing tickers:   2%|▏         | 130/6855 [00:27<23:58,  4.68it/s]

Processing tickers:   2%|▏         | 131/6855 [00:28<23:39,  4.74it/s]

Processing tickers:   2%|▏         | 132/6855 [00:28<23:51,  4.70it/s]

Processing tickers:   2%|▏         | 133/6855 [00:28<23:35,  4.75it/s]

Processing tickers:   2%|▏         | 134/6855 [00:28<23:27,  4.77it/s]

Processing tickers:   2%|▏         | 135/6855 [00:28<23:39,  4.73it/s]

Processing tickers:   2%|▏         | 136/6855 [00:29<23:25,  4.78it/s]

Processing tickers:   2%|▏         | 137/6855 [00:29<23:48,  4.70it/s]

Processing tickers:   2%|▏         | 138/6855 [00:29<23:51,  4.69it/s]

Processing tickers:   2%|▏         | 139/6855 [00:29<23:56,  4.67it/s]

Processing tickers:   2%|▏         | 140/6855 [00:29<24:12,  4.62it/s]

Processing tickers:   2%|▏         | 141/6855 [00:30<24:04,  4.65it/s]

Processing tickers:   2%|▏         | 142/6855 [00:30<23:57,  4.67it/s]

Processing tickers:   2%|▏         | 143/6855 [00:30<24:08,  4.63it/s]

Processing tickers:   2%|▏         | 144/6855 [00:30<23:57,  4.67it/s]

Processing tickers:   2%|▏         | 145/6855 [00:31<23:58,  4.66it/s]

Processing tickers:   2%|▏         | 146/6855 [00:31<23:54,  4.68it/s]

Processing tickers:   2%|▏         | 147/6855 [00:31<23:41,  4.72it/s]

Processing tickers:   2%|▏         | 148/6855 [00:31<23:37,  4.73it/s]

Processing tickers:   2%|▏         | 149/6855 [00:31<23:36,  4.73it/s]

Processing tickers:   2%|▏         | 150/6855 [00:32<23:33,  4.74it/s]

Processing tickers:   2%|▏         | 151/6855 [00:32<23:37,  4.73it/s]

Processing tickers:   2%|▏         | 152/6855 [00:32<23:34,  4.74it/s]

Processing tickers:   2%|▏         | 153/6855 [00:32<23:51,  4.68it/s]

Processing tickers:   2%|▏         | 154/6855 [00:32<23:37,  4.73it/s]

Processing tickers:   2%|▏         | 155/6855 [00:33<23:35,  4.73it/s]

Processing tickers:   2%|▏         | 156/6855 [00:33<23:48,  4.69it/s]

Processing tickers:   2%|▏         | 157/6855 [00:33<23:36,  4.73it/s]

Processing tickers:   2%|▏         | 158/6855 [00:33<23:32,  4.74it/s]

Processing tickers:   2%|▏         | 159/6855 [00:33<24:04,  4.63it/s]

Processing tickers:   2%|▏         | 160/6855 [00:34<23:49,  4.68it/s]

Processing tickers:   2%|▏         | 161/6855 [00:34<24:01,  4.65it/s]

Processing tickers:   2%|▏         | 162/6855 [00:34<23:53,  4.67it/s]

Processing tickers:   2%|▏         | 163/6855 [00:34<23:46,  4.69it/s]

Processing tickers:   2%|▏         | 164/6855 [00:35<23:35,  4.73it/s]

Processing tickers:   2%|▏         | 165/6855 [00:35<23:39,  4.71it/s]

Processing tickers:   2%|▏         | 166/6855 [00:35<23:34,  4.73it/s]

Processing tickers:   2%|▏         | 167/6855 [00:35<23:31,  4.74it/s]

Processing tickers:   2%|▏         | 168/6855 [00:35<23:27,  4.75it/s]

Processing tickers:   2%|▏         | 169/6855 [00:36<25:32,  4.36it/s]

Processing tickers:   2%|▏         | 170/6855 [00:36<24:43,  4.51it/s]

Processing tickers:   2%|▏         | 171/6855 [00:36<25:15,  4.41it/s]

Processing tickers:   3%|▎         | 172/6855 [00:36<24:44,  4.50it/s]

Processing tickers:   3%|▎         | 173/6855 [00:37<24:17,  4.58it/s]

Processing tickers:   3%|▎         | 174/6855 [00:37<24:09,  4.61it/s]

Processing tickers:   3%|▎         | 175/6855 [00:37<23:53,  4.66it/s]

Processing tickers:   3%|▎         | 176/6855 [00:37<23:33,  4.72it/s]

Processing tickers:   3%|▎         | 177/6855 [00:37<23:41,  4.70it/s]

Processing tickers:   3%|▎         | 178/6855 [00:38<23:42,  4.69it/s]

Processing tickers:   3%|▎         | 179/6855 [00:38<23:29,  4.74it/s]

Processing tickers:   3%|▎         | 180/6855 [00:38<23:35,  4.72it/s]

Processing tickers:   3%|▎         | 181/6855 [00:38<23:59,  4.64it/s]

Processing tickers:   3%|▎         | 182/6855 [00:38<23:44,  4.69it/s]

Processing tickers:   3%|▎         | 183/6855 [00:39<23:34,  4.72it/s]

Processing tickers:   3%|▎         | 184/6855 [00:39<23:30,  4.73it/s]

Processing tickers:   3%|▎         | 185/6855 [00:39<23:21,  4.76it/s]

Processing tickers:   3%|▎         | 186/6855 [00:39<23:19,  4.77it/s]

Processing tickers:   3%|▎         | 187/6855 [00:39<23:22,  4.75it/s]

Processing tickers:   3%|▎         | 188/6855 [00:40<23:26,  4.74it/s]

Processing tickers:   3%|▎         | 189/6855 [00:40<23:13,  4.78it/s]

Processing tickers:   3%|▎         | 190/6855 [00:40<22:59,  4.83it/s]

Processing tickers:   3%|▎         | 191/6855 [00:40<23:09,  4.80it/s]

Processing tickers:   3%|▎         | 192/6855 [00:41<23:04,  4.81it/s]

Processing tickers:   3%|▎         | 193/6855 [00:41<23:36,  4.70it/s]

Processing tickers:   3%|▎         | 194/6855 [00:41<23:47,  4.67it/s]

Processing tickers:   3%|▎         | 195/6855 [00:41<24:43,  4.49it/s]

Processing tickers:   3%|▎         | 196/6855 [00:41<24:19,  4.56it/s]

Processing tickers:   3%|▎         | 197/6855 [00:42<24:03,  4.61it/s]

Processing tickers:   3%|▎         | 198/6855 [00:42<24:10,  4.59it/s]

Processing tickers:   3%|▎         | 199/6855 [00:42<23:43,  4.68it/s]

Processing tickers:   3%|▎         | 200/6855 [00:42<23:34,  4.71it/s]

Processing tickers:   3%|▎         | 201/6855 [00:42<23:25,  4.73it/s]

Processing tickers:   3%|▎         | 202/6855 [00:43<23:20,  4.75it/s]

Processing tickers:   3%|▎         | 203/6855 [00:43<23:24,  4.74it/s]

Processing tickers:   3%|▎         | 204/6855 [00:43<23:28,  4.72it/s]

Processing tickers:   3%|▎         | 205/6855 [00:43<23:26,  4.73it/s]

Processing tickers:   3%|▎         | 206/6855 [00:44<23:23,  4.74it/s]

Processing tickers:   3%|▎         | 207/6855 [00:44<23:20,  4.75it/s]

Processing tickers:   3%|▎         | 208/6855 [00:44<23:17,  4.75it/s]

Processing tickers:   3%|▎         | 209/6855 [00:44<23:13,  4.77it/s]

Processing tickers:   3%|▎         | 210/6855 [00:44<23:15,  4.76it/s]

Processing tickers:   3%|▎         | 211/6855 [00:45<23:11,  4.77it/s]

Processing tickers:   3%|▎         | 212/6855 [00:45<23:08,  4.79it/s]

Processing tickers:   3%|▎         | 213/6855 [00:45<22:56,  4.83it/s]

Processing tickers:   3%|▎         | 214/6855 [00:45<23:24,  4.73it/s]

Processing tickers:   3%|▎         | 215/6855 [00:45<23:11,  4.77it/s]

Processing tickers:   3%|▎         | 216/6855 [00:46<23:29,  4.71it/s]

Processing tickers:   3%|▎         | 217/6855 [00:46<23:22,  4.73it/s]

Processing tickers:   3%|▎         | 218/6855 [00:46<24:12,  4.57it/s]

Processing tickers:   3%|▎         | 219/6855 [00:46<23:55,  4.62it/s]

Processing tickers:   3%|▎         | 220/6855 [00:46<23:55,  4.62it/s]

Processing tickers:   3%|▎         | 221/6855 [00:47<23:42,  4.66it/s]

Processing tickers:   3%|▎         | 222/6855 [00:47<23:33,  4.69it/s]

Processing tickers:   3%|▎         | 223/6855 [00:47<23:17,  4.75it/s]

Processing tickers:   3%|▎         | 224/6855 [00:47<23:32,  4.69it/s]

Processing tickers:   3%|▎         | 225/6855 [00:48<23:30,  4.70it/s]

Processing tickers:   3%|▎         | 226/6855 [00:48<23:23,  4.72it/s]

Processing tickers:   3%|▎         | 227/6855 [00:48<23:14,  4.75it/s]

Processing tickers:   3%|▎         | 228/6855 [00:48<23:15,  4.75it/s]

Processing tickers:   3%|▎         | 229/6855 [00:48<23:14,  4.75it/s]

Processing tickers:   3%|▎         | 230/6855 [00:49<23:29,  4.70it/s]

Processing tickers:   3%|▎         | 231/6855 [00:49<23:19,  4.73it/s]

Processing tickers:   3%|▎         | 232/6855 [00:49<23:13,  4.75it/s]

Processing tickers:   3%|▎         | 233/6855 [00:49<23:12,  4.76it/s]

Processing tickers:   3%|▎         | 234/6855 [00:49<23:17,  4.74it/s]

Processing tickers:   3%|▎         | 235/6855 [00:50<23:50,  4.63it/s]

Processing tickers:   3%|▎         | 236/6855 [00:50<23:29,  4.70it/s]

Processing tickers:   3%|▎         | 237/6855 [00:50<23:20,  4.73it/s]

Processing tickers:   3%|▎         | 238/6855 [00:50<23:20,  4.73it/s]

Processing tickers:   3%|▎         | 239/6855 [00:51<23:12,  4.75it/s]

Processing tickers:   4%|▎         | 240/6855 [00:51<23:03,  4.78it/s]

Processing tickers:   4%|▎         | 241/6855 [00:51<23:05,  4.77it/s]

Processing tickers:   4%|▎         | 242/6855 [00:51<23:06,  4.77it/s]

Processing tickers:   4%|▎         | 243/6855 [00:51<23:05,  4.77it/s]

Processing tickers:   4%|▎         | 244/6855 [00:52<23:08,  4.76it/s]

Processing tickers:   4%|▎         | 245/6855 [00:52<23:03,  4.78it/s]

Processing tickers:   4%|▎         | 246/6855 [00:52<23:04,  4.77it/s]

Processing tickers:   4%|▎         | 247/6855 [00:52<22:59,  4.79it/s]

Processing tickers:   4%|▎         | 248/6855 [00:52<22:55,  4.80it/s]

Processing tickers:   4%|▎         | 249/6855 [00:53<22:59,  4.79it/s]

Processing tickers:   4%|▎         | 250/6855 [00:53<23:01,  4.78it/s]

Processing tickers:   4%|▎         | 251/6855 [00:53<22:51,  4.82it/s]

Processing tickers:   4%|▎         | 252/6855 [00:53<23:19,  4.72it/s]

Processing tickers:   4%|▎         | 253/6855 [00:53<23:14,  4.73it/s]

Processing tickers:   4%|▎         | 254/6855 [00:54<23:15,  4.73it/s]

Processing tickers:   4%|▎         | 255/6855 [00:54<23:01,  4.78it/s]

Processing tickers:   4%|▎         | 256/6855 [00:54<23:12,  4.74it/s]

Processing tickers:   4%|▎         | 257/6855 [00:54<23:08,  4.75it/s]

Processing tickers:   4%|▍         | 258/6855 [00:54<22:57,  4.79it/s]

Processing tickers:   4%|▍         | 259/6855 [00:55<22:55,  4.80it/s]

Processing tickers:   4%|▍         | 260/6855 [00:55<22:47,  4.82it/s]

Processing tickers:   4%|▍         | 261/6855 [00:55<22:49,  4.81it/s]

Processing tickers:   4%|▍         | 262/6855 [00:55<22:54,  4.80it/s]

Processing tickers:   4%|▍         | 263/6855 [00:56<22:56,  4.79it/s]

Processing tickers:   4%|▍         | 264/6855 [00:56<23:22,  4.70it/s]

Processing tickers:   4%|▍         | 265/6855 [00:56<24:03,  4.56it/s]

Processing tickers:   4%|▍         | 266/6855 [00:56<24:06,  4.56it/s]

Processing tickers:   4%|▍         | 267/6855 [00:56<24:13,  4.53it/s]

Processing tickers:   4%|▍         | 268/6855 [00:57<24:01,  4.57it/s]

Processing tickers:   4%|▍         | 269/6855 [00:57<23:46,  4.62it/s]

Processing tickers:   4%|▍         | 270/6855 [00:57<23:41,  4.63it/s]

Processing tickers:   4%|▍         | 271/6855 [00:57<23:29,  4.67it/s]

Processing tickers:   4%|▍         | 272/6855 [00:57<23:34,  4.65it/s]

Processing tickers:   4%|▍         | 273/6855 [00:58<23:16,  4.71it/s]

Processing tickers:   4%|▍         | 274/6855 [00:58<23:11,  4.73it/s]

Processing tickers:   4%|▍         | 275/6855 [00:58<23:09,  4.73it/s]

Processing tickers:   4%|▍         | 276/6855 [00:58<23:10,  4.73it/s]

Processing tickers:   4%|▍         | 277/6855 [00:59<23:24,  4.68it/s]

Processing tickers:   4%|▍         | 278/6855 [00:59<23:55,  4.58it/s]

Processing tickers:   4%|▍         | 279/6855 [00:59<23:31,  4.66it/s]

Processing tickers:   4%|▍         | 280/6855 [00:59<23:39,  4.63it/s]

Processing tickers:   4%|▍         | 281/6855 [00:59<23:26,  4.67it/s]

Processing tickers:   4%|▍         | 282/6855 [01:00<23:35,  4.64it/s]

Processing tickers:   4%|▍         | 283/6855 [01:00<23:30,  4.66it/s]

Processing tickers:   4%|▍         | 284/6855 [01:00<23:15,  4.71it/s]

Processing tickers:   4%|▍         | 285/6855 [01:00<22:59,  4.76it/s]

Processing tickers:   4%|▍         | 286/6855 [01:00<22:57,  4.77it/s]

Processing tickers:   4%|▍         | 287/6855 [01:01<22:47,  4.80it/s]

Processing tickers:   4%|▍         | 288/6855 [01:01<23:36,  4.64it/s]

Processing tickers:   4%|▍         | 289/6855 [01:01<23:19,  4.69it/s]

Processing tickers:   4%|▍         | 290/6855 [01:01<22:59,  4.76it/s]

Processing tickers:   4%|▍         | 291/6855 [01:02<22:53,  4.78it/s]

Processing tickers:   4%|▍         | 292/6855 [01:02<23:16,  4.70it/s]

Processing tickers:   4%|▍         | 293/6855 [01:02<23:00,  4.75it/s]

Processing tickers:   4%|▍         | 294/6855 [01:02<22:44,  4.81it/s]

Processing tickers:   4%|▍         | 295/6855 [01:02<22:38,  4.83it/s]

Processing tickers:   4%|▍         | 296/6855 [01:03<22:41,  4.82it/s]

Processing tickers:   4%|▍         | 297/6855 [01:03<22:47,  4.80it/s]

Processing tickers:   4%|▍         | 298/6855 [01:03<22:41,  4.82it/s]

Processing tickers:   4%|▍         | 299/6855 [01:03<23:44,  4.60it/s]

Processing tickers:   4%|▍         | 300/6855 [01:03<23:19,  4.68it/s]

Processing tickers:   4%|▍         | 301/6855 [01:04<23:28,  4.65it/s]

Processing tickers:   4%|▍         | 302/6855 [01:04<23:08,  4.72it/s]

Processing tickers:   4%|▍         | 303/6855 [01:04<23:07,  4.72it/s]

Processing tickers:   4%|▍         | 304/6855 [01:04<23:06,  4.73it/s]

Processing tickers:   4%|▍         | 305/6855 [01:04<22:54,  4.77it/s]

Processing tickers:   4%|▍         | 306/6855 [01:05<22:58,  4.75it/s]

Processing tickers:   4%|▍         | 307/6855 [01:05<22:54,  4.77it/s]

Processing tickers:   4%|▍         | 308/6855 [01:05<23:32,  4.63it/s]

Processing tickers:   5%|▍         | 309/6855 [01:05<23:17,  4.68it/s]

Processing tickers:   5%|▍         | 310/6855 [01:06<23:16,  4.69it/s]

Processing tickers:   5%|▍         | 311/6855 [01:06<23:13,  4.70it/s]

Processing tickers:   5%|▍         | 312/6855 [01:06<23:01,  4.74it/s]

Processing tickers:   5%|▍         | 313/6855 [01:06<22:52,  4.77it/s]

Processing tickers:   5%|▍         | 314/6855 [01:06<23:22,  4.66it/s]

Processing tickers:   5%|▍         | 315/6855 [01:07<23:11,  4.70it/s]

Processing tickers:   5%|▍         | 316/6855 [01:07<22:54,  4.76it/s]

Processing tickers:   5%|▍         | 317/6855 [01:07<22:46,  4.78it/s]

Processing tickers:   5%|▍         | 318/6855 [01:07<22:56,  4.75it/s]

Processing tickers:   5%|▍         | 319/6855 [01:07<22:56,  4.75it/s]

Processing tickers:   5%|▍         | 320/6855 [01:08<22:57,  4.74it/s]

Processing tickers:   5%|▍         | 321/6855 [01:08<23:08,  4.70it/s]

Processing tickers:   5%|▍         | 322/6855 [01:08<22:59,  4.74it/s]

Processing tickers:   5%|▍         | 323/6855 [01:08<22:59,  4.74it/s]

Processing tickers:   5%|▍         | 324/6855 [01:09<23:09,  4.70it/s]

Processing tickers:   5%|▍         | 325/6855 [01:09<23:00,  4.73it/s]

Processing tickers:   5%|▍         | 326/6855 [01:09<22:55,  4.75it/s]

Processing tickers:   5%|▍         | 327/6855 [01:09<22:53,  4.75it/s]

Processing tickers:   5%|▍         | 328/6855 [01:09<23:31,  4.62it/s]

Processing tickers:   5%|▍         | 329/6855 [01:10<23:09,  4.70it/s]

Processing tickers:   5%|▍         | 330/6855 [01:10<22:53,  4.75it/s]

Processing tickers:   5%|▍         | 331/6855 [01:10<22:56,  4.74it/s]

Processing tickers:   5%|▍         | 332/6855 [01:10<22:57,  4.74it/s]

Processing tickers:   5%|▍         | 333/6855 [01:10<23:01,  4.72it/s]

Processing tickers:   5%|▍         | 334/6855 [01:11<23:05,  4.71it/s]

Processing tickers:   5%|▍         | 335/6855 [01:11<23:10,  4.69it/s]

Processing tickers:   5%|▍         | 336/6855 [01:11<23:22,  4.65it/s]

Processing tickers:   5%|▍         | 337/6855 [01:11<23:22,  4.65it/s]

Processing tickers:   5%|▍         | 338/6855 [01:11<23:15,  4.67it/s]

Processing tickers:   5%|▍         | 339/6855 [01:12<23:27,  4.63it/s]

Processing tickers:   5%|▍         | 340/6855 [01:12<23:53,  4.54it/s]

Processing tickers:   5%|▍         | 341/6855 [01:12<23:36,  4.60it/s]

Processing tickers:   5%|▍         | 342/6855 [01:12<23:29,  4.62it/s]

Processing tickers:   5%|▌         | 343/6855 [01:13<23:06,  4.70it/s]

Processing tickers:   5%|▌         | 344/6855 [01:13<22:51,  4.75it/s]

Processing tickers:   5%|▌         | 345/6855 [01:13<22:46,  4.77it/s]

Processing tickers:   5%|▌         | 346/6855 [01:13<23:10,  4.68it/s]

Processing tickers:   5%|▌         | 347/6855 [01:13<23:06,  4.69it/s]

Processing tickers:   5%|▌         | 348/6855 [01:14<23:04,  4.70it/s]

Processing tickers:   5%|▌         | 349/6855 [01:14<22:59,  4.72it/s]

Processing tickers:   5%|▌         | 350/6855 [01:14<23:04,  4.70it/s]

Processing tickers:   5%|▌         | 351/6855 [01:14<23:01,  4.71it/s]

Processing tickers:   5%|▌         | 352/6855 [01:14<22:49,  4.75it/s]

Processing tickers:   5%|▌         | 353/6855 [01:15<22:46,  4.76it/s]

Processing tickers:   5%|▌         | 354/6855 [01:15<22:56,  4.72it/s]

Processing tickers:   5%|▌         | 355/6855 [01:15<22:48,  4.75it/s]

Processing tickers:   5%|▌         | 356/6855 [01:15<22:50,  4.74it/s]

Processing tickers:   5%|▌         | 357/6855 [01:16<23:05,  4.69it/s]

Processing tickers:   5%|▌         | 358/6855 [01:16<22:52,  4.73it/s]

Processing tickers:   5%|▌         | 359/6855 [01:16<22:56,  4.72it/s]

Processing tickers:   5%|▌         | 360/6855 [01:16<23:59,  4.51it/s]

Processing tickers:   5%|▌         | 361/6855 [01:16<23:52,  4.53it/s]

Processing tickers:   5%|▌         | 362/6855 [01:17<23:26,  4.62it/s]

Processing tickers:   5%|▌         | 363/6855 [01:17<23:21,  4.63it/s]

Processing tickers:   5%|▌         | 364/6855 [01:17<23:17,  4.65it/s]

Processing tickers:   5%|▌         | 365/6855 [01:17<22:54,  4.72it/s]

Processing tickers:   5%|▌         | 366/6855 [01:17<22:54,  4.72it/s]

Processing tickers:   5%|▌         | 367/6855 [01:18<22:39,  4.77it/s]

Processing tickers:   5%|▌         | 368/6855 [01:18<23:11,  4.66it/s]

Processing tickers:   5%|▌         | 369/6855 [01:18<23:13,  4.66it/s]

Processing tickers:   5%|▌         | 370/6855 [01:18<23:17,  4.64it/s]

Processing tickers:   5%|▌         | 371/6855 [01:19<23:07,  4.67it/s]

Processing tickers:   5%|▌         | 372/6855 [01:19<22:59,  4.70it/s]

Processing tickers:   5%|▌         | 373/6855 [01:19<22:53,  4.72it/s]

Processing tickers:   5%|▌         | 374/6855 [01:19<22:48,  4.74it/s]

Processing tickers:   5%|▌         | 375/6855 [01:19<22:46,  4.74it/s]

Processing tickers:   5%|▌         | 376/6855 [01:20<22:46,  4.74it/s]

Processing tickers:   5%|▌         | 377/6855 [01:20<22:50,  4.73it/s]

Processing tickers:   6%|▌         | 378/6855 [01:20<22:51,  4.72it/s]

Processing tickers:   6%|▌         | 379/6855 [01:20<23:07,  4.67it/s]

Processing tickers:   6%|▌         | 380/6855 [01:20<22:53,  4.72it/s]

Processing tickers:   6%|▌         | 381/6855 [01:21<23:00,  4.69it/s]

Processing tickers:   6%|▌         | 382/6855 [01:21<22:53,  4.71it/s]

Processing tickers:   6%|▌         | 383/6855 [01:21<23:10,  4.65it/s]

Processing tickers:   6%|▌         | 384/6855 [01:21<23:08,  4.66it/s]

Processing tickers:   6%|▌         | 385/6855 [01:22<23:18,  4.63it/s]

Processing tickers:   6%|▌         | 386/6855 [01:22<23:47,  4.53it/s]

Processing tickers:   6%|▌         | 387/6855 [01:22<24:24,  4.42it/s]

Processing tickers:   6%|▌         | 388/6855 [01:22<24:11,  4.46it/s]

Processing tickers:   6%|▌         | 389/6855 [01:22<23:41,  4.55it/s]

Processing tickers:   6%|▌         | 390/6855 [01:23<23:13,  4.64it/s]

Processing tickers:   6%|▌         | 391/6855 [01:23<23:09,  4.65it/s]

Processing tickers:   6%|▌         | 392/6855 [01:23<22:47,  4.72it/s]

Processing tickers:   6%|▌         | 393/6855 [01:23<22:41,  4.75it/s]

Processing tickers:   6%|▌         | 394/6855 [01:23<22:44,  4.74it/s]

Processing tickers:   6%|▌         | 395/6855 [01:24<22:46,  4.73it/s]

Processing tickers:   6%|▌         | 396/6855 [01:24<23:06,  4.66it/s]

Processing tickers:   6%|▌         | 397/6855 [01:24<23:40,  4.55it/s]

Processing tickers:   6%|▌         | 398/6855 [01:24<24:06,  4.46it/s]

Processing tickers:   6%|▌         | 399/6855 [01:25<23:44,  4.53it/s]

Processing tickers:   6%|▌         | 400/6855 [01:25<23:28,  4.58it/s]

Processing tickers:   6%|▌         | 401/6855 [01:25<23:29,  4.58it/s]

Processing tickers:   6%|▌         | 402/6855 [01:25<23:50,  4.51it/s]

Processing tickers:   6%|▌         | 403/6855 [01:25<23:18,  4.61it/s]

Processing tickers:   6%|▌         | 404/6855 [01:26<23:09,  4.64it/s]

Processing tickers:   6%|▌         | 405/6855 [01:26<22:55,  4.69it/s]

Processing tickers:   6%|▌         | 406/6855 [01:26<22:49,  4.71it/s]

Processing tickers:   6%|▌         | 407/6855 [01:26<22:49,  4.71it/s]

Processing tickers:   6%|▌         | 408/6855 [01:27<23:19,  4.61it/s]

Processing tickers:   6%|▌         | 409/6855 [01:27<23:03,  4.66it/s]

Processing tickers:   6%|▌         | 410/6855 [01:27<22:51,  4.70it/s]

Processing tickers:   6%|▌         | 411/6855 [01:27<23:49,  4.51it/s]

Processing tickers:   6%|▌         | 412/6855 [01:27<23:15,  4.62it/s]

Processing tickers:   6%|▌         | 413/6855 [01:28<23:00,  4.67it/s]

Processing tickers:   6%|▌         | 414/6855 [01:28<23:22,  4.59it/s]

Processing tickers:   6%|▌         | 415/6855 [01:28<22:58,  4.67it/s]

Processing tickers:   6%|▌         | 416/6855 [01:28<23:21,  4.59it/s]

Processing tickers:   6%|▌         | 417/6855 [01:28<23:47,  4.51it/s]

Processing tickers:   6%|▌         | 418/6855 [01:29<23:25,  4.58it/s]

Processing tickers:   6%|▌         | 419/6855 [01:29<23:06,  4.64it/s]

Processing tickers:   6%|▌         | 420/6855 [01:29<23:14,  4.61it/s]

Processing tickers:   6%|▌         | 421/6855 [01:29<22:57,  4.67it/s]

Processing tickers:   6%|▌         | 422/6855 [01:30<23:34,  4.55it/s]

Processing tickers:   6%|▌         | 423/6855 [01:30<23:28,  4.57it/s]

Processing tickers:   6%|▌         | 424/6855 [01:30<23:25,  4.58it/s]

Processing tickers:   6%|▌         | 425/6855 [01:30<23:27,  4.57it/s]

Processing tickers:   6%|▌         | 426/6855 [01:30<23:16,  4.60it/s]

Processing tickers:   6%|▌         | 427/6855 [01:31<23:00,  4.66it/s]

Processing tickers:   6%|▌         | 428/6855 [01:31<22:59,  4.66it/s]

Processing tickers:   6%|▋         | 429/6855 [01:31<22:45,  4.71it/s]

Processing tickers:   6%|▋         | 430/6855 [01:31<22:36,  4.74it/s]

Processing tickers:   6%|▋         | 431/6855 [01:31<23:12,  4.61it/s]

Processing tickers:   6%|▋         | 432/6855 [01:32<22:53,  4.68it/s]

Processing tickers:   6%|▋         | 433/6855 [01:32<23:24,  4.57it/s]

Processing tickers:   6%|▋         | 434/6855 [01:32<23:07,  4.63it/s]

Processing tickers:   6%|▋         | 435/6855 [01:32<23:21,  4.58it/s]

Processing tickers:   6%|▋         | 436/6855 [01:33<23:03,  4.64it/s]

Processing tickers:   6%|▋         | 437/6855 [01:33<22:42,  4.71it/s]

Processing tickers:   6%|▋         | 438/6855 [01:33<22:34,  4.74it/s]

Processing tickers:   6%|▋         | 439/6855 [01:33<22:45,  4.70it/s]

Processing tickers:   6%|▋         | 440/6855 [01:33<22:30,  4.75it/s]

Processing tickers:   6%|▋         | 441/6855 [01:34<22:22,  4.78it/s]

Processing tickers:   6%|▋         | 442/6855 [01:34<22:06,  4.83it/s]

Processing tickers:   6%|▋         | 443/6855 [01:34<22:12,  4.81it/s]

Processing tickers:   6%|▋         | 444/6855 [01:34<22:27,  4.76it/s]

Processing tickers:   6%|▋         | 445/6855 [01:34<22:21,  4.78it/s]

Processing tickers:   7%|▋         | 446/6855 [01:35<22:44,  4.70it/s]

Processing tickers:   7%|▋         | 447/6855 [01:35<22:28,  4.75it/s]

Processing tickers:   7%|▋         | 448/6855 [01:35<22:20,  4.78it/s]

Processing tickers:   7%|▋         | 449/6855 [01:35<22:24,  4.76it/s]

Processing tickers:   7%|▋         | 450/6855 [01:36<22:24,  4.76it/s]

Processing tickers:   7%|▋         | 451/6855 [01:36<22:55,  4.66it/s]

Processing tickers:   7%|▋         | 452/6855 [01:36<22:46,  4.68it/s]

Processing tickers:   7%|▋         | 453/6855 [01:36<22:42,  4.70it/s]

Processing tickers:   7%|▋         | 454/6855 [01:36<22:32,  4.73it/s]

Processing tickers:   7%|▋         | 455/6855 [01:37<22:32,  4.73it/s]

Processing tickers:   7%|▋         | 456/6855 [01:37<22:33,  4.73it/s]

Processing tickers:   7%|▋         | 457/6855 [01:37<23:14,  4.59it/s]

Processing tickers:   7%|▋         | 458/6855 [01:37<23:41,  4.50it/s]

Processing tickers:   7%|▋         | 459/6855 [01:37<23:17,  4.58it/s]

Processing tickers:   7%|▋         | 460/6855 [01:38<23:25,  4.55it/s]

Processing tickers:   7%|▋         | 461/6855 [01:38<23:15,  4.58it/s]

Processing tickers:   7%|▋         | 462/6855 [01:38<23:39,  4.50it/s]

Processing tickers:   7%|▋         | 463/6855 [01:38<23:09,  4.60it/s]

Processing tickers:   7%|▋         | 464/6855 [01:39<23:20,  4.56it/s]

Processing tickers:   7%|▋         | 465/6855 [01:39<23:00,  4.63it/s]

Processing tickers:   7%|▋         | 466/6855 [01:39<23:08,  4.60it/s]

Processing tickers:   7%|▋         | 467/6855 [01:39<23:00,  4.63it/s]

Processing tickers:   7%|▋         | 468/6855 [01:39<22:47,  4.67it/s]

Processing tickers:   7%|▋         | 469/6855 [01:40<22:59,  4.63it/s]

Processing tickers:   7%|▋         | 470/6855 [01:40<22:49,  4.66it/s]

Processing tickers:   7%|▋         | 471/6855 [01:40<23:18,  4.56it/s]

Processing tickers:   7%|▋         | 472/6855 [01:40<23:13,  4.58it/s]

Processing tickers:   7%|▋         | 473/6855 [01:40<22:54,  4.64it/s]

Processing tickers:   7%|▋         | 474/6855 [01:41<22:35,  4.71it/s]

Processing tickers:   7%|▋         | 475/6855 [01:41<22:25,  4.74it/s]

Processing tickers:   7%|▋         | 476/6855 [01:41<22:30,  4.72it/s]

Processing tickers:   7%|▋         | 477/6855 [01:41<22:45,  4.67it/s]

Processing tickers:   7%|▋         | 478/6855 [01:42<23:30,  4.52it/s]

Processing tickers:   7%|▋         | 479/6855 [01:42<23:09,  4.59it/s]

Processing tickers:   7%|▋         | 480/6855 [01:42<23:23,  4.54it/s]

Processing tickers:   7%|▋         | 481/6855 [01:42<23:03,  4.61it/s]

Processing tickers:   7%|▋         | 482/6855 [01:42<23:18,  4.56it/s]

Processing tickers:   7%|▋         | 483/6855 [01:43<22:59,  4.62it/s]

Processing tickers:   7%|▋         | 484/6855 [01:43<22:48,  4.65it/s]

Processing tickers:   7%|▋         | 485/6855 [01:43<22:36,  4.69it/s]

Processing tickers:   7%|▋         | 486/6855 [01:43<22:25,  4.73it/s]

Processing tickers:   7%|▋         | 487/6855 [01:43<22:23,  4.74it/s]

Processing tickers:   7%|▋         | 488/6855 [01:44<22:24,  4.74it/s]

Processing tickers:   7%|▋         | 489/6855 [01:44<22:24,  4.74it/s]

Processing tickers:   7%|▋         | 490/6855 [01:44<22:30,  4.71it/s]

Processing tickers:   7%|▋         | 491/6855 [01:44<22:44,  4.66it/s]

Processing tickers:   7%|▋         | 492/6855 [01:45<22:34,  4.70it/s]

Processing tickers:   7%|▋         | 493/6855 [01:45<22:33,  4.70it/s]

Processing tickers:   7%|▋         | 494/6855 [01:45<23:13,  4.57it/s]

Processing tickers:   7%|▋         | 495/6855 [01:45<23:20,  4.54it/s]

Processing tickers:   7%|▋         | 496/6855 [01:45<22:56,  4.62it/s]

Processing tickers:   7%|▋         | 497/6855 [01:46<22:48,  4.65it/s]

Processing tickers:   7%|▋         | 498/6855 [01:46<22:30,  4.71it/s]

Processing tickers:   7%|▋         | 499/6855 [01:46<22:50,  4.64it/s]

Processing tickers:   7%|▋         | 500/6855 [01:46<22:29,  4.71it/s]

Processing tickers:   7%|▋         | 501/6855 [01:46<22:29,  4.71it/s]

Processing tickers:   7%|▋         | 502/6855 [01:47<22:50,  4.64it/s]

Processing tickers:   7%|▋         | 503/6855 [01:47<23:16,  4.55it/s]

Processing tickers:   7%|▋         | 504/6855 [01:47<22:55,  4.62it/s]

Processing tickers:   7%|▋         | 505/6855 [01:47<22:41,  4.66it/s]

Processing tickers:   7%|▋         | 506/6855 [01:48<22:38,  4.68it/s]

Processing tickers:   7%|▋         | 507/6855 [01:48<22:25,  4.72it/s]

Processing tickers:   7%|▋         | 508/6855 [01:48<22:30,  4.70it/s]

Processing tickers:   7%|▋         | 509/6855 [01:48<22:30,  4.70it/s]

Processing tickers:   7%|▋         | 510/6855 [01:48<22:17,  4.75it/s]

Processing tickers:   7%|▋         | 511/6855 [01:49<22:52,  4.62it/s]

Processing tickers:   7%|▋         | 512/6855 [01:49<22:37,  4.67it/s]

Processing tickers:   7%|▋         | 513/6855 [01:49<22:28,  4.70it/s]

Processing tickers:   7%|▋         | 514/6855 [01:49<22:28,  4.70it/s]

Processing tickers:   8%|▊         | 515/6855 [01:49<22:36,  4.67it/s]

Processing tickers:   8%|▊         | 516/6855 [01:50<23:05,  4.58it/s]

Processing tickers:   8%|▊         | 517/6855 [01:50<22:38,  4.66it/s]

Processing tickers:   8%|▊         | 518/6855 [01:50<22:37,  4.67it/s]

Processing tickers:   8%|▊         | 519/6855 [01:50<22:27,  4.70it/s]

Processing tickers:   8%|▊         | 520/6855 [01:51<22:16,  4.74it/s]

Processing tickers:   8%|▊         | 521/6855 [01:51<22:18,  4.73it/s]

Processing tickers:   8%|▊         | 522/6855 [01:51<22:16,  4.74it/s]

Processing tickers:   8%|▊         | 523/6855 [01:51<22:35,  4.67it/s]

Processing tickers:   8%|▊         | 524/6855 [01:51<23:08,  4.56it/s]

Processing tickers:   8%|▊         | 525/6855 [01:52<22:52,  4.61it/s]

Processing tickers:   8%|▊         | 526/6855 [01:52<22:28,  4.69it/s]

Processing tickers:   8%|▊         | 527/6855 [01:52<22:56,  4.60it/s]

Processing tickers:   8%|▊         | 528/6855 [01:52<22:42,  4.64it/s]

Processing tickers:   8%|▊         | 529/6855 [01:53<22:42,  4.64it/s]

Processing tickers:   8%|▊         | 530/6855 [01:53<23:26,  4.50it/s]

Processing tickers:   8%|▊         | 531/6855 [01:53<23:20,  4.52it/s]

Processing tickers:   8%|▊         | 532/6855 [01:53<23:02,  4.57it/s]

Processing tickers:   8%|▊         | 533/6855 [01:53<22:51,  4.61it/s]

Processing tickers:   8%|▊         | 534/6855 [01:54<22:53,  4.60it/s]

Processing tickers:   8%|▊         | 535/6855 [01:54<23:33,  4.47it/s]

Processing tickers:   8%|▊         | 536/6855 [01:54<23:08,  4.55it/s]

Processing tickers:   8%|▊         | 537/6855 [01:54<22:46,  4.62it/s]

Processing tickers:   8%|▊         | 538/6855 [01:54<23:14,  4.53it/s]

Processing tickers:   8%|▊         | 539/6855 [01:55<23:24,  4.50it/s]

Processing tickers:   8%|▊         | 540/6855 [01:55<23:10,  4.54it/s]

Processing tickers:   8%|▊         | 541/6855 [01:55<23:40,  4.44it/s]

Processing tickers:   8%|▊         | 542/6855 [01:55<23:36,  4.46it/s]

Processing tickers:   8%|▊         | 543/6855 [01:56<23:41,  4.44it/s]

Processing tickers:   8%|▊         | 544/6855 [01:56<23:57,  4.39it/s]

Processing tickers:   8%|▊         | 545/6855 [01:56<23:11,  4.54it/s]

Processing tickers:   8%|▊         | 546/6855 [01:56<23:11,  4.53it/s]

Processing tickers:   8%|▊         | 547/6855 [01:56<22:52,  4.60it/s]

Processing tickers:   8%|▊         | 548/6855 [01:57<22:44,  4.62it/s]

Processing tickers:   8%|▊         | 549/6855 [01:57<22:21,  4.70it/s]

Processing tickers:   8%|▊         | 550/6855 [01:57<22:37,  4.64it/s]

Processing tickers:   8%|▊         | 551/6855 [01:57<23:11,  4.53it/s]

Processing tickers:   8%|▊         | 552/6855 [01:58<23:25,  4.49it/s]

Processing tickers:   8%|▊         | 553/6855 [01:58<22:52,  4.59it/s]

Processing tickers:   8%|▊         | 554/6855 [01:58<22:41,  4.63it/s]

Processing tickers:   8%|▊         | 555/6855 [01:58<22:46,  4.61it/s]

Processing tickers:   8%|▊         | 556/6855 [01:58<22:36,  4.64it/s]

Processing tickers:   8%|▊         | 557/6855 [01:59<22:27,  4.67it/s]

Processing tickers:   8%|▊         | 558/6855 [01:59<22:13,  4.72it/s]

Processing tickers:   8%|▊         | 559/6855 [01:59<22:38,  4.64it/s]

Processing tickers:   8%|▊         | 560/6855 [01:59<23:11,  4.52it/s]

Processing tickers:   8%|▊         | 561/6855 [02:00<23:17,  4.50it/s]

Processing tickers:   8%|▊         | 562/6855 [02:00<22:52,  4.59it/s]

Processing tickers:   8%|▊         | 563/6855 [02:00<22:28,  4.66it/s]

Processing tickers:   8%|▊         | 564/6855 [02:00<22:12,  4.72it/s]

Processing tickers:   8%|▊         | 565/6855 [02:00<22:14,  4.72it/s]

Processing tickers:   8%|▊         | 566/6855 [02:01<22:04,  4.75it/s]

Processing tickers:   8%|▊         | 567/6855 [02:01<21:56,  4.78it/s]

Processing tickers:   8%|▊         | 568/6855 [02:01<21:59,  4.76it/s]

Processing tickers:   8%|▊         | 569/6855 [02:01<22:33,  4.64it/s]

Processing tickers:   8%|▊         | 570/6855 [02:01<22:27,  4.66it/s]

Processing tickers:   8%|▊         | 571/6855 [02:02<22:39,  4.62it/s]

Processing tickers:   8%|▊         | 572/6855 [02:02<22:18,  4.69it/s]

Processing tickers:   8%|▊         | 573/6855 [02:02<22:17,  4.70it/s]

Processing tickers:   8%|▊         | 574/6855 [02:02<23:05,  4.53it/s]

Processing tickers:   8%|▊         | 575/6855 [02:03<22:58,  4.56it/s]

Processing tickers:   8%|▊         | 576/6855 [02:03<23:23,  4.47it/s]

Processing tickers:   8%|▊         | 577/6855 [02:03<23:07,  4.52it/s]

Processing tickers:   8%|▊         | 578/6855 [02:03<23:00,  4.55it/s]

Processing tickers:   8%|▊         | 579/6855 [02:03<23:10,  4.51it/s]

Processing tickers:   8%|▊         | 580/6855 [02:04<23:24,  4.47it/s]

Processing tickers:   8%|▊         | 581/6855 [02:04<22:59,  4.55it/s]

Processing tickers:   8%|▊         | 582/6855 [02:04<22:33,  4.63it/s]

Processing tickers:   9%|▊         | 583/6855 [02:04<22:27,  4.65it/s]

Processing tickers:   9%|▊         | 584/6855 [02:04<22:20,  4.68it/s]

Processing tickers:   9%|▊         | 585/6855 [02:05<22:31,  4.64it/s]

Processing tickers:   9%|▊         | 586/6855 [02:05<22:22,  4.67it/s]

Processing tickers:   9%|▊         | 587/6855 [02:05<22:11,  4.71it/s]

Processing tickers:   9%|▊         | 588/6855 [02:05<22:36,  4.62it/s]

Processing tickers:   9%|▊         | 589/6855 [02:06<23:06,  4.52it/s]

Processing tickers:   9%|▊         | 590/6855 [02:06<23:25,  4.46it/s]

Processing tickers:   9%|▊         | 591/6855 [02:06<22:57,  4.55it/s]

Processing tickers:   9%|▊         | 592/6855 [02:06<22:33,  4.63it/s]

Processing tickers:   9%|▊         | 593/6855 [02:06<22:29,  4.64it/s]

Processing tickers:   9%|▊         | 594/6855 [02:07<22:23,  4.66it/s]

Processing tickers:   9%|▊         | 595/6855 [02:07<22:23,  4.66it/s]

Processing tickers:   9%|▊         | 596/6855 [02:07<22:17,  4.68it/s]

Processing tickers:   9%|▊         | 597/6855 [02:07<22:16,  4.68it/s]

Processing tickers:   9%|▊         | 598/6855 [02:08<22:04,  4.72it/s]

Processing tickers:   9%|▊         | 599/6855 [02:08<21:52,  4.77it/s]

Processing tickers:   9%|▉         | 600/6855 [02:08<22:14,  4.69it/s]

Processing tickers:   9%|▉         | 601/6855 [02:08<22:04,  4.72it/s]

Processing tickers:   9%|▉         | 602/6855 [02:08<21:58,  4.74it/s]

Processing tickers:   9%|▉         | 603/6855 [02:09<22:01,  4.73it/s]

Processing tickers:   9%|▉         | 604/6855 [02:09<21:54,  4.75it/s]

Processing tickers:   9%|▉         | 605/6855 [02:09<21:53,  4.76it/s]

Processing tickers:   9%|▉         | 606/6855 [02:09<21:58,  4.74it/s]

Processing tickers:   9%|▉         | 607/6855 [02:09<21:50,  4.77it/s]

Processing tickers:   9%|▉         | 608/6855 [02:10<21:53,  4.76it/s]

Processing tickers:   9%|▉         | 609/6855 [02:10<21:45,  4.79it/s]

Processing tickers:   9%|▉         | 610/6855 [02:10<21:43,  4.79it/s]

Processing tickers:   9%|▉         | 611/6855 [02:10<21:51,  4.76it/s]

Processing tickers:   9%|▉         | 612/6855 [02:10<21:55,  4.75it/s]

Processing tickers:   9%|▉         | 613/6855 [02:11<22:09,  4.70it/s]

Processing tickers:   9%|▉         | 614/6855 [02:11<22:08,  4.70it/s]

Processing tickers:   9%|▉         | 615/6855 [02:11<21:52,  4.76it/s]

Processing tickers:   9%|▉         | 616/6855 [02:11<22:10,  4.69it/s]

Processing tickers:   9%|▉         | 617/6855 [02:12<21:54,  4.75it/s]

Processing tickers:   9%|▉         | 618/6855 [02:12<21:44,  4.78it/s]

Processing tickers:   9%|▉         | 619/6855 [02:12<21:40,  4.80it/s]

Processing tickers:   9%|▉         | 620/6855 [02:12<21:37,  4.81it/s]

Processing tickers:   9%|▉         | 621/6855 [02:12<22:10,  4.68it/s]

Processing tickers:   9%|▉         | 622/6855 [02:13<22:03,  4.71it/s]

Processing tickers:   9%|▉         | 623/6855 [02:13<22:26,  4.63it/s]

Processing tickers:   9%|▉         | 624/6855 [02:13<22:05,  4.70it/s]

Processing tickers:   9%|▉         | 625/6855 [02:13<22:31,  4.61it/s]

Processing tickers:   9%|▉         | 626/6855 [02:13<22:16,  4.66it/s]

Processing tickers:   9%|▉         | 627/6855 [02:14<22:00,  4.72it/s]

Processing tickers:   9%|▉         | 628/6855 [02:14<22:13,  4.67it/s]

Processing tickers:   9%|▉         | 629/6855 [02:14<22:05,  4.70it/s]

Processing tickers:   9%|▉         | 630/6855 [02:14<21:48,  4.76it/s]

Processing tickers:   9%|▉         | 631/6855 [02:14<21:58,  4.72it/s]

Processing tickers:   9%|▉         | 632/6855 [02:15<22:37,  4.58it/s]

Processing tickers:   9%|▉         | 633/6855 [02:15<22:14,  4.66it/s]

Processing tickers:   9%|▉         | 634/6855 [02:15<22:02,  4.70it/s]

Processing tickers:   9%|▉         | 635/6855 [02:15<21:50,  4.75it/s]

Processing tickers:   9%|▉         | 636/6855 [02:16<22:34,  4.59it/s]

Processing tickers:   9%|▉         | 637/6855 [02:16<22:26,  4.62it/s]

Processing tickers:   9%|▉         | 638/6855 [02:16<22:13,  4.66it/s]

Processing tickers:   9%|▉         | 639/6855 [02:16<22:48,  4.54it/s]

Processing tickers:   9%|▉         | 640/6855 [02:16<22:34,  4.59it/s]

Processing tickers:   9%|▉         | 641/6855 [02:17<23:03,  4.49it/s]

Processing tickers:   9%|▉         | 642/6855 [02:17<22:51,  4.53it/s]

Processing tickers:   9%|▉         | 643/6855 [02:17<22:38,  4.57it/s]

Processing tickers:   9%|▉         | 644/6855 [02:17<23:11,  4.46it/s]

Processing tickers:   9%|▉         | 645/6855 [02:18<22:43,  4.56it/s]

Processing tickers:   9%|▉         | 646/6855 [02:18<23:06,  4.48it/s]

Processing tickers:   9%|▉         | 647/6855 [02:18<23:12,  4.46it/s]

Processing tickers:   9%|▉         | 648/6855 [02:18<22:53,  4.52it/s]

Processing tickers:   9%|▉         | 649/6855 [02:18<22:30,  4.60it/s]

Processing tickers:   9%|▉         | 650/6855 [02:19<22:46,  4.54it/s]

Processing tickers:   9%|▉         | 651/6855 [02:19<22:27,  4.61it/s]

Processing tickers:  10%|▉         | 652/6855 [02:19<22:12,  4.66it/s]

Processing tickers:  10%|▉         | 653/6855 [02:19<21:56,  4.71it/s]

Processing tickers:  10%|▉         | 654/6855 [02:19<21:45,  4.75it/s]

Processing tickers:  10%|▉         | 655/6855 [02:20<21:50,  4.73it/s]

Processing tickers:  10%|▉         | 656/6855 [02:20<21:44,  4.75it/s]

Processing tickers:  10%|▉         | 657/6855 [02:20<22:28,  4.60it/s]

Processing tickers:  10%|▉         | 658/6855 [02:20<22:29,  4.59it/s]

Processing tickers:  10%|▉         | 659/6855 [02:21<22:56,  4.50it/s]

Processing tickers:  10%|▉         | 660/6855 [02:21<22:33,  4.58it/s]

Processing tickers:  10%|▉         | 661/6855 [02:21<22:10,  4.66it/s]

Processing tickers:  10%|▉         | 662/6855 [02:21<21:55,  4.71it/s]

Processing tickers:  10%|▉         | 663/6855 [02:21<21:55,  4.71it/s]

Processing tickers:  10%|▉         | 664/6855 [02:22<21:45,  4.74it/s]

Processing tickers:  10%|▉         | 665/6855 [02:22<21:49,  4.73it/s]

Processing tickers:  10%|▉         | 666/6855 [02:22<22:26,  4.60it/s]

Processing tickers:  10%|▉         | 667/6855 [02:22<22:53,  4.50it/s]

Processing tickers:  10%|▉         | 668/6855 [02:23<23:02,  4.48it/s]

Processing tickers:  10%|▉         | 669/6855 [02:23<23:18,  4.42it/s]

Processing tickers:  10%|▉         | 670/6855 [02:23<23:24,  4.40it/s]

Processing tickers:  10%|▉         | 671/6855 [02:23<23:07,  4.46it/s]

Processing tickers:  10%|▉         | 672/6855 [02:23<22:34,  4.56it/s]

Processing tickers:  10%|▉         | 673/6855 [02:24<22:23,  4.60it/s]

Processing tickers:  10%|▉         | 674/6855 [02:24<22:09,  4.65it/s]

Processing tickers:  10%|▉         | 675/6855 [02:24<22:25,  4.59it/s]

Processing tickers:  10%|▉         | 676/6855 [02:24<22:09,  4.65it/s]

Processing tickers:  10%|▉         | 677/6855 [02:24<21:49,  4.72it/s]

Processing tickers:  10%|▉         | 678/6855 [02:25<21:41,  4.74it/s]

Processing tickers:  10%|▉         | 679/6855 [02:25<21:41,  4.74it/s]

Processing tickers:  10%|▉         | 680/6855 [02:25<21:46,  4.73it/s]

Processing tickers:  10%|▉         | 681/6855 [02:25<21:52,  4.70it/s]

Processing tickers:  10%|▉         | 682/6855 [02:26<22:28,  4.58it/s]

Processing tickers:  10%|▉         | 683/6855 [02:26<22:51,  4.50it/s]

Processing tickers:  10%|▉         | 684/6855 [02:26<22:38,  4.54it/s]

Processing tickers:  10%|▉         | 685/6855 [02:26<22:12,  4.63it/s]

Processing tickers:  10%|█         | 686/6855 [02:26<21:52,  4.70it/s]

Processing tickers:  10%|█         | 687/6855 [02:27<21:43,  4.73it/s]

Processing tickers:  10%|█         | 688/6855 [02:27<21:37,  4.75it/s]

Processing tickers:  10%|█         | 689/6855 [02:27<21:33,  4.77it/s]

Processing tickers:  10%|█         | 690/6855 [02:27<21:55,  4.69it/s]

Processing tickers:  10%|█         | 691/6855 [02:28<22:05,  4.65it/s]

Processing tickers:  10%|█         | 692/6855 [02:28<22:15,  4.61it/s]

Processing tickers:  10%|█         | 693/6855 [02:28<21:54,  4.69it/s]

Processing tickers:  10%|█         | 694/6855 [02:28<21:57,  4.68it/s]

Processing tickers:  10%|█         | 695/6855 [02:28<22:14,  4.62it/s]

Processing tickers:  10%|█         | 696/6855 [02:29<21:52,  4.69it/s]

Processing tickers:  10%|█         | 697/6855 [02:29<21:37,  4.75it/s]

Processing tickers:  10%|█         | 698/6855 [02:29<21:30,  4.77it/s]

Processing tickers:  10%|█         | 699/6855 [02:29<21:42,  4.73it/s]

Processing tickers:  10%|█         | 700/6855 [02:29<22:10,  4.63it/s]

Processing tickers:  10%|█         | 701/6855 [02:30<21:56,  4.67it/s]

Processing tickers:  10%|█         | 702/6855 [02:30<21:59,  4.66it/s]

Processing tickers:  10%|█         | 703/6855 [02:30<22:01,  4.66it/s]

Processing tickers:  10%|█         | 704/6855 [02:30<21:50,  4.69it/s]

Processing tickers:  10%|█         | 705/6855 [02:30<21:59,  4.66it/s]

Processing tickers:  10%|█         | 706/6855 [02:31<22:15,  4.60it/s]

Processing tickers:  10%|█         | 707/6855 [02:31<23:00,  4.45it/s]

Processing tickers:  10%|█         | 708/6855 [02:31<22:40,  4.52it/s]

Processing tickers:  10%|█         | 709/6855 [02:31<22:20,  4.58it/s]

Processing tickers:  10%|█         | 710/6855 [02:32<24:02,  4.26it/s]

Processing tickers:  10%|█         | 711/6855 [02:32<23:46,  4.31it/s]

Processing tickers:  10%|█         | 712/6855 [02:32<23:06,  4.43it/s]

Processing tickers:  10%|█         | 713/6855 [02:32<23:14,  4.40it/s]

Processing tickers:  10%|█         | 714/6855 [02:33<22:58,  4.45it/s]

Processing tickers:  10%|█         | 715/6855 [02:33<23:09,  4.42it/s]

Processing tickers:  10%|█         | 716/6855 [02:33<22:46,  4.49it/s]

Processing tickers:  10%|█         | 717/6855 [02:33<22:33,  4.53it/s]

Processing tickers:  10%|█         | 718/6855 [02:33<22:54,  4.47it/s]

Processing tickers:  10%|█         | 719/6855 [02:34<22:27,  4.55it/s]

Processing tickers:  11%|█         | 720/6855 [02:34<22:11,  4.61it/s]

Processing tickers:  11%|█         | 721/6855 [02:34<21:59,  4.65it/s]

Processing tickers:  11%|█         | 722/6855 [02:34<22:13,  4.60it/s]

Processing tickers:  11%|█         | 723/6855 [02:34<21:59,  4.65it/s]

Processing tickers:  11%|█         | 724/6855 [02:35<22:25,  4.56it/s]

Processing tickers:  11%|█         | 725/6855 [02:35<22:22,  4.57it/s]

Processing tickers:  11%|█         | 726/6855 [02:35<22:11,  4.60it/s]

Processing tickers:  11%|█         | 727/6855 [02:35<22:13,  4.59it/s]

Processing tickers:  11%|█         | 728/6855 [02:36<22:01,  4.64it/s]

Processing tickers:  11%|█         | 729/6855 [02:36<21:52,  4.67it/s]

Processing tickers:  11%|█         | 730/6855 [02:36<21:39,  4.71it/s]

Processing tickers:  11%|█         | 731/6855 [02:36<21:57,  4.65it/s]

Processing tickers:  11%|█         | 732/6855 [02:36<21:41,  4.71it/s]

Processing tickers:  11%|█         | 733/6855 [02:37<21:44,  4.69it/s]

Processing tickers:  11%|█         | 734/6855 [02:37<21:43,  4.70it/s]

Processing tickers:  11%|█         | 735/6855 [02:37<21:29,  4.75it/s]

Processing tickers:  11%|█         | 736/6855 [02:37<21:29,  4.74it/s]

Processing tickers:  11%|█         | 737/6855 [02:37<21:47,  4.68it/s]

Processing tickers:  11%|█         | 738/6855 [02:38<21:54,  4.65it/s]

Processing tickers:  11%|█         | 739/6855 [02:38<21:39,  4.71it/s]

Processing tickers:  11%|█         | 740/6855 [02:38<22:05,  4.61it/s]

Processing tickers:  11%|█         | 741/6855 [02:38<21:42,  4.69it/s]

Processing tickers:  11%|█         | 742/6855 [02:39<22:20,  4.56it/s]

Processing tickers:  11%|█         | 743/6855 [02:39<22:02,  4.62it/s]

Processing tickers:  11%|█         | 744/6855 [02:39<21:56,  4.64it/s]

Processing tickers:  11%|█         | 745/6855 [02:39<21:56,  4.64it/s]

Processing tickers:  11%|█         | 746/6855 [02:39<21:38,  4.70it/s]

Processing tickers:  11%|█         | 747/6855 [02:40<21:33,  4.72it/s]

Processing tickers:  11%|█         | 748/6855 [02:40<21:24,  4.75it/s]

Processing tickers:  11%|█         | 749/6855 [02:40<21:24,  4.75it/s]

Processing tickers:  11%|█         | 750/6855 [02:40<21:25,  4.75it/s]

Processing tickers:  11%|█         | 751/6855 [02:40<21:11,  4.80it/s]

Processing tickers:  11%|█         | 752/6855 [02:41<21:11,  4.80it/s]

Processing tickers:  11%|█         | 753/6855 [02:41<21:15,  4.78it/s]

Processing tickers:  11%|█         | 754/6855 [02:41<21:20,  4.76it/s]

Processing tickers:  11%|█         | 755/6855 [02:41<21:22,  4.76it/s]

Processing tickers:  11%|█         | 756/6855 [02:42<21:24,  4.75it/s]

Processing tickers:  11%|█         | 757/6855 [02:42<21:40,  4.69it/s]

Processing tickers:  11%|█         | 758/6855 [02:42<21:49,  4.65it/s]

Processing tickers:  11%|█         | 759/6855 [02:42<21:46,  4.66it/s]

Processing tickers:  11%|█         | 760/6855 [02:42<21:54,  4.64it/s]

Processing tickers:  11%|█         | 761/6855 [02:43<22:13,  4.57it/s]

Processing tickers:  11%|█         | 762/6855 [02:43<21:55,  4.63it/s]

Processing tickers:  11%|█         | 763/6855 [02:43<21:45,  4.67it/s]

Processing tickers:  11%|█         | 764/6855 [02:43<21:59,  4.62it/s]

Processing tickers:  11%|█         | 765/6855 [02:43<22:28,  4.51it/s]

Processing tickers:  11%|█         | 766/6855 [02:44<21:59,  4.61it/s]

Processing tickers:  11%|█         | 767/6855 [02:44<21:48,  4.65it/s]

Processing tickers:  11%|█         | 768/6855 [02:44<21:50,  4.65it/s]

Processing tickers:  11%|█         | 769/6855 [02:44<21:34,  4.70it/s]

Processing tickers:  11%|█         | 770/6855 [02:45<22:01,  4.60it/s]

Processing tickers:  11%|█         | 771/6855 [02:45<21:49,  4.64it/s]

Processing tickers:  11%|█▏        | 772/6855 [02:45<21:39,  4.68it/s]

Processing tickers:  11%|█▏        | 773/6855 [02:45<21:55,  4.62it/s]

Processing tickers:  11%|█▏        | 774/6855 [02:45<21:40,  4.68it/s]

Processing tickers:  11%|█▏        | 775/6855 [02:46<21:41,  4.67it/s]

Processing tickers:  11%|█▏        | 776/6855 [02:46<22:02,  4.60it/s]

Processing tickers:  11%|█▏        | 777/6855 [02:46<21:46,  4.65it/s]

Processing tickers:  11%|█▏        | 778/6855 [02:46<21:48,  4.65it/s]

Processing tickers:  11%|█▏        | 779/6855 [02:46<21:27,  4.72it/s]

Processing tickers:  11%|█▏        | 780/6855 [02:47<21:17,  4.76it/s]

Processing tickers:  11%|█▏        | 781/6855 [02:47<21:12,  4.77it/s]

Processing tickers:  11%|█▏        | 782/6855 [02:47<21:15,  4.76it/s]

Processing tickers:  11%|█▏        | 783/6855 [02:47<21:12,  4.77it/s]

Processing tickers:  11%|█▏        | 784/6855 [02:48<21:04,  4.80it/s]

Processing tickers:  11%|█▏        | 785/6855 [02:48<21:05,  4.80it/s]

Processing tickers:  11%|█▏        | 786/6855 [02:48<21:02,  4.81it/s]

Processing tickers:  11%|█▏        | 787/6855 [02:48<21:09,  4.78it/s]

Processing tickers:  11%|█▏        | 788/6855 [02:48<21:18,  4.75it/s]

Processing tickers:  12%|█▏        | 789/6855 [02:49<21:03,  4.80it/s]

Processing tickers:  12%|█▏        | 790/6855 [02:49<21:02,  4.80it/s]

Processing tickers:  12%|█▏        | 791/6855 [02:49<21:02,  4.81it/s]

Processing tickers:  12%|█▏        | 792/6855 [02:49<21:22,  4.73it/s]

Processing tickers:  12%|█▏        | 793/6855 [02:49<21:32,  4.69it/s]

Processing tickers:  12%|█▏        | 794/6855 [02:50<21:43,  4.65it/s]

Processing tickers:  12%|█▏        | 795/6855 [02:50<21:42,  4.65it/s]

Processing tickers:  12%|█▏        | 796/6855 [02:50<21:45,  4.64it/s]

Processing tickers:  12%|█▏        | 797/6855 [02:50<21:30,  4.69it/s]

Processing tickers:  12%|█▏        | 798/6855 [02:50<21:37,  4.67it/s]

Processing tickers:  12%|█▏        | 799/6855 [02:51<21:49,  4.63it/s]

Processing tickers:  12%|█▏        | 800/6855 [02:51<21:34,  4.68it/s]

Processing tickers:  12%|█▏        | 801/6855 [02:51<21:38,  4.66it/s]

Processing tickers:  12%|█▏        | 802/6855 [02:51<21:29,  4.69it/s]

Processing tickers:  12%|█▏        | 803/6855 [02:52<21:26,  4.70it/s]

Processing tickers:  12%|█▏        | 804/6855 [02:52<21:16,  4.74it/s]

Processing tickers:  12%|█▏        | 805/6855 [02:52<21:08,  4.77it/s]

Processing tickers:  12%|█▏        | 806/6855 [02:52<21:32,  4.68it/s]

Processing tickers:  12%|█▏        | 807/6855 [02:52<21:30,  4.69it/s]

Processing tickers:  12%|█▏        | 808/6855 [02:53<21:27,  4.70it/s]

Processing tickers:  12%|█▏        | 809/6855 [02:53<21:34,  4.67it/s]

Processing tickers:  12%|█▏        | 810/6855 [02:53<21:21,  4.72it/s]

Processing tickers:  12%|█▏        | 811/6855 [02:53<21:16,  4.74it/s]

Processing tickers:  12%|█▏        | 812/6855 [02:53<21:14,  4.74it/s]

Processing tickers:  12%|█▏        | 813/6855 [02:54<21:04,  4.78it/s]

Processing tickers:  12%|█▏        | 814/6855 [02:54<21:08,  4.76it/s]

Processing tickers:  12%|█▏        | 815/6855 [02:54<21:14,  4.74it/s]

Processing tickers:  12%|█▏        | 816/6855 [02:54<21:51,  4.60it/s]

Processing tickers:  12%|█▏        | 817/6855 [02:55<21:44,  4.63it/s]

Processing tickers:  12%|█▏        | 818/6855 [02:55<21:23,  4.70it/s]

Processing tickers:  12%|█▏        | 819/6855 [02:55<21:15,  4.73it/s]

Processing tickers:  12%|█▏        | 820/6855 [02:55<21:17,  4.73it/s]

Processing tickers:  12%|█▏        | 821/6855 [02:55<21:07,  4.76it/s]

Processing tickers:  12%|█▏        | 822/6855 [02:56<21:07,  4.76it/s]

Processing tickers:  12%|█▏        | 823/6855 [02:56<21:19,  4.71it/s]

Processing tickers:  12%|█▏        | 824/6855 [02:56<21:03,  4.77it/s]

Processing tickers:  12%|█▏        | 825/6855 [02:56<21:13,  4.74it/s]

Processing tickers:  12%|█▏        | 826/6855 [02:56<21:48,  4.61it/s]

Processing tickers:  12%|█▏        | 827/6855 [02:57<21:26,  4.68it/s]

Processing tickers:  12%|█▏        | 828/6855 [02:57<22:23,  4.49it/s]

Processing tickers:  12%|█▏        | 829/6855 [02:57<22:04,  4.55it/s]

Processing tickers:  12%|█▏        | 830/6855 [02:57<21:45,  4.62it/s]

Processing tickers:  12%|█▏        | 831/6855 [02:58<21:33,  4.66it/s]

Processing tickers:  12%|█▏        | 832/6855 [02:58<21:16,  4.72it/s]

Processing tickers:  12%|█▏        | 833/6855 [02:58<21:12,  4.73it/s]

Processing tickers:  12%|█▏        | 834/6855 [02:58<20:56,  4.79it/s]

Processing tickers:  12%|█▏        | 835/6855 [02:58<20:58,  4.78it/s]

Processing tickers:  12%|█▏        | 836/6855 [02:59<21:33,  4.65it/s]

Processing tickers:  12%|█▏        | 837/6855 [02:59<22:02,  4.55it/s]

Processing tickers:  12%|█▏        | 838/6855 [02:59<21:31,  4.66it/s]

Processing tickers:  12%|█▏        | 839/6855 [02:59<21:22,  4.69it/s]

Processing tickers:  12%|█▏        | 840/6855 [02:59<21:18,  4.70it/s]

Processing tickers:  12%|█▏        | 841/6855 [03:00<21:11,  4.73it/s]

Processing tickers:  12%|█▏        | 842/6855 [03:00<21:12,  4.73it/s]

Processing tickers:  12%|█▏        | 843/6855 [03:00<21:08,  4.74it/s]

Processing tickers:  12%|█▏        | 844/6855 [03:00<21:02,  4.76it/s]

Processing tickers:  12%|█▏        | 845/6855 [03:00<21:13,  4.72it/s]

Processing tickers:  12%|█▏        | 846/6855 [03:01<20:57,  4.78it/s]

Processing tickers:  12%|█▏        | 847/6855 [03:01<21:33,  4.64it/s]

Processing tickers:  12%|█▏        | 848/6855 [03:01<21:18,  4.70it/s]

Processing tickers:  12%|█▏        | 849/6855 [03:01<21:53,  4.57it/s]

Processing tickers:  12%|█▏        | 850/6855 [03:02<21:28,  4.66it/s]

Processing tickers:  12%|█▏        | 851/6855 [03:02<21:45,  4.60it/s]

Processing tickers:  12%|█▏        | 852/6855 [03:02<21:20,  4.69it/s]

Processing tickers:  12%|█▏        | 853/6855 [03:02<21:35,  4.63it/s]

Processing tickers:  12%|█▏        | 854/6855 [03:02<21:20,  4.69it/s]

Processing tickers:  12%|█▏        | 855/6855 [03:03<21:04,  4.75it/s]

Processing tickers:  12%|█▏        | 856/6855 [03:03<21:05,  4.74it/s]

Processing tickers:  13%|█▎        | 857/6855 [03:03<20:56,  4.77it/s]

Processing tickers:  13%|█▎        | 858/6855 [03:03<21:31,  4.64it/s]

Processing tickers:  13%|█▎        | 859/6855 [03:04<22:09,  4.51it/s]

Processing tickers:  13%|█▎        | 860/6855 [03:04<21:49,  4.58it/s]

Processing tickers:  13%|█▎        | 861/6855 [03:04<21:30,  4.64it/s]

Processing tickers:  13%|█▎        | 862/6855 [03:04<21:20,  4.68it/s]

Processing tickers:  13%|█▎        | 863/6855 [03:04<21:10,  4.72it/s]

Processing tickers:  13%|█▎        | 864/6855 [03:05<21:05,  4.73it/s]

Processing tickers:  13%|█▎        | 865/6855 [03:05<20:58,  4.76it/s]

Processing tickers:  13%|█▎        | 866/6855 [03:05<20:50,  4.79it/s]

Processing tickers:  13%|█▎        | 867/6855 [03:05<21:08,  4.72it/s]

Processing tickers:  13%|█▎        | 868/6855 [03:05<20:58,  4.76it/s]

Processing tickers:  13%|█▎        | 869/6855 [03:06<21:07,  4.72it/s]

Processing tickers:  13%|█▎        | 870/6855 [03:06<21:22,  4.67it/s]

Processing tickers:  13%|█▎        | 871/6855 [03:06<21:17,  4.69it/s]

Processing tickers:  13%|█▎        | 872/6855 [03:06<21:10,  4.71it/s]

Processing tickers:  13%|█▎        | 873/6855 [03:06<21:22,  4.66it/s]

Processing tickers:  13%|█▎        | 874/6855 [03:07<21:13,  4.70it/s]

Processing tickers:  13%|█▎        | 875/6855 [03:07<21:00,  4.74it/s]

Processing tickers:  13%|█▎        | 876/6855 [03:07<21:19,  4.67it/s]

Processing tickers:  13%|█▎        | 877/6855 [03:07<21:54,  4.55it/s]

Processing tickers:  13%|█▎        | 878/6855 [03:08<21:35,  4.61it/s]

Processing tickers:  13%|█▎        | 879/6855 [03:08<21:18,  4.68it/s]

Processing tickers:  13%|█▎        | 880/6855 [03:08<21:09,  4.71it/s]

Processing tickers:  13%|█▎        | 881/6855 [03:08<21:09,  4.71it/s]

Processing tickers:  13%|█▎        | 882/6855 [03:08<21:03,  4.73it/s]

Processing tickers:  13%|█▎        | 883/6855 [03:09<21:18,  4.67it/s]

Processing tickers:  13%|█▎        | 884/6855 [03:09<21:06,  4.72it/s]

Processing tickers:  13%|█▎        | 885/6855 [03:09<21:21,  4.66it/s]

Processing tickers:  13%|█▎        | 886/6855 [03:09<21:08,  4.71it/s]

Processing tickers:  13%|█▎        | 887/6855 [03:09<21:10,  4.70it/s]

Processing tickers:  13%|█▎        | 888/6855 [03:10<21:01,  4.73it/s]

Processing tickers:  13%|█▎        | 889/6855 [03:10<21:07,  4.71it/s]

Processing tickers:  13%|█▎        | 890/6855 [03:10<20:59,  4.74it/s]

Processing tickers:  13%|█▎        | 891/6855 [03:10<21:15,  4.68it/s]

Processing tickers:  13%|█▎        | 892/6855 [03:11<21:08,  4.70it/s]

Processing tickers:  13%|█▎        | 893/6855 [03:11<21:08,  4.70it/s]

Processing tickers:  13%|█▎        | 894/6855 [03:11<21:41,  4.58it/s]

Processing tickers:  13%|█▎        | 895/6855 [03:11<21:43,  4.57it/s]

Processing tickers:  13%|█▎        | 896/6855 [03:11<21:24,  4.64it/s]

Processing tickers:  13%|█▎        | 897/6855 [03:12<21:32,  4.61it/s]

Processing tickers:  13%|█▎        | 898/6855 [03:12<21:10,  4.69it/s]

Processing tickers:  13%|█▎        | 899/6855 [03:12<21:06,  4.70it/s]

Processing tickers:  13%|█▎        | 900/6855 [03:12<20:49,  4.77it/s]

Processing tickers:  13%|█▎        | 901/6855 [03:12<21:02,  4.72it/s]

Processing tickers:  13%|█▎        | 902/6855 [03:13<20:50,  4.76it/s]

Processing tickers:  13%|█▎        | 903/6855 [03:13<20:50,  4.76it/s]

Processing tickers:  13%|█▎        | 904/6855 [03:13<20:44,  4.78it/s]

Processing tickers:  13%|█▎        | 905/6855 [03:13<20:37,  4.81it/s]

Processing tickers:  13%|█▎        | 906/6855 [03:13<20:34,  4.82it/s]

Processing tickers:  13%|█▎        | 907/6855 [03:14<20:34,  4.82it/s]

Processing tickers:  13%|█▎        | 908/6855 [03:14<21:09,  4.68it/s]

Processing tickers:  13%|█▎        | 909/6855 [03:14<20:55,  4.74it/s]

Processing tickers:  13%|█▎        | 910/6855 [03:14<21:04,  4.70it/s]

Processing tickers:  13%|█▎        | 911/6855 [03:15<21:03,  4.70it/s]

Processing tickers:  13%|█▎        | 912/6855 [03:15<20:53,  4.74it/s]

Processing tickers:  13%|█▎        | 913/6855 [03:15<21:04,  4.70it/s]

Processing tickers:  13%|█▎        | 914/6855 [03:15<21:15,  4.66it/s]

Processing tickers:  13%|█▎        | 915/6855 [03:15<21:04,  4.70it/s]

Processing tickers:  13%|█▎        | 916/6855 [03:16<21:25,  4.62it/s]

Processing tickers:  13%|█▎        | 917/6855 [03:16<21:11,  4.67it/s]

Processing tickers:  13%|█▎        | 918/6855 [03:16<20:55,  4.73it/s]

Processing tickers:  13%|█▎        | 919/6855 [03:16<20:54,  4.73it/s]

Processing tickers:  13%|█▎        | 920/6855 [03:16<20:51,  4.74it/s]

Processing tickers:  13%|█▎        | 921/6855 [03:17<20:41,  4.78it/s]

Processing tickers:  13%|█▎        | 922/6855 [03:17<20:35,  4.80it/s]

Processing tickers:  13%|█▎        | 923/6855 [03:17<20:36,  4.80it/s]

Processing tickers:  13%|█▎        | 924/6855 [03:17<20:39,  4.78it/s]

Processing tickers:  13%|█▎        | 925/6855 [03:18<20:50,  4.74it/s]

Processing tickers:  14%|█▎        | 926/6855 [03:18<20:40,  4.78it/s]

Processing tickers:  14%|█▎        | 927/6855 [03:18<20:38,  4.79it/s]

Processing tickers:  14%|█▎        | 928/6855 [03:18<21:06,  4.68it/s]

Processing tickers:  14%|█▎        | 929/6855 [03:18<21:03,  4.69it/s]

Processing tickers:  14%|█▎        | 930/6855 [03:19<21:13,  4.65it/s]

Processing tickers:  14%|█▎        | 931/6855 [03:19<21:09,  4.66it/s]

Processing tickers:  14%|█▎        | 932/6855 [03:19<20:53,  4.72it/s]

Processing tickers:  14%|█▎        | 933/6855 [03:19<21:36,  4.57it/s]

Processing tickers:  14%|█▎        | 934/6855 [03:19<21:12,  4.65it/s]

Processing tickers:  14%|█▎        | 935/6855 [03:20<21:10,  4.66it/s]

Processing tickers:  14%|█▎        | 936/6855 [03:20<21:00,  4.70it/s]

Processing tickers:  14%|█▎        | 937/6855 [03:20<21:02,  4.69it/s]

Processing tickers:  14%|█▎        | 938/6855 [03:20<20:45,  4.75it/s]

Processing tickers:  14%|█▎        | 939/6855 [03:21<20:47,  4.74it/s]

Processing tickers:  14%|█▎        | 940/6855 [03:21<20:42,  4.76it/s]

Processing tickers:  14%|█▎        | 941/6855 [03:21<20:32,  4.80it/s]

Processing tickers:  14%|█▎        | 942/6855 [03:21<20:31,  4.80it/s]

Processing tickers:  14%|█▍        | 943/6855 [03:21<20:58,  4.70it/s]

Processing tickers:  14%|█▍        | 944/6855 [03:22<20:52,  4.72it/s]

Processing tickers:  14%|█▍        | 945/6855 [03:22<20:48,  4.73it/s]

Processing tickers:  14%|█▍        | 946/6855 [03:22<20:40,  4.76it/s]

Processing tickers:  14%|█▍        | 947/6855 [03:22<20:52,  4.72it/s]

Processing tickers:  14%|█▍        | 948/6855 [03:22<20:53,  4.71it/s]

Processing tickers:  14%|█▍        | 949/6855 [03:23<20:43,  4.75it/s]

Processing tickers:  14%|█▍        | 950/6855 [03:23<20:46,  4.74it/s]

Processing tickers:  14%|█▍        | 951/6855 [03:23<20:48,  4.73it/s]

Processing tickers:  14%|█▍        | 952/6855 [03:23<20:49,  4.72it/s]

Processing tickers:  14%|█▍        | 953/6855 [03:23<20:54,  4.70it/s]

Processing tickers:  14%|█▍        | 954/6855 [03:24<21:16,  4.62it/s]

Processing tickers:  14%|█▍        | 955/6855 [03:24<20:54,  4.70it/s]

Processing tickers:  14%|█▍        | 956/6855 [03:24<21:23,  4.60it/s]

Processing tickers:  14%|█▍        | 957/6855 [03:24<21:49,  4.50it/s]

Processing tickers:  14%|█▍        | 958/6855 [03:25<21:22,  4.60it/s]

Processing tickers:  14%|█▍        | 959/6855 [03:25<20:58,  4.69it/s]

Processing tickers:  14%|█▍        | 960/6855 [03:25<21:03,  4.67it/s]

Processing tickers:  14%|█▍        | 961/6855 [03:25<21:37,  4.54it/s]

Processing tickers:  14%|█▍        | 962/6855 [03:25<21:22,  4.60it/s]

Processing tickers:  14%|█▍        | 963/6855 [03:26<21:08,  4.64it/s]

Processing tickers:  14%|█▍        | 964/6855 [03:26<20:51,  4.71it/s]

Processing tickers:  14%|█▍        | 965/6855 [03:26<20:39,  4.75it/s]

Processing tickers:  14%|█▍        | 966/6855 [03:26<21:14,  4.62it/s]

Processing tickers:  14%|█▍        | 967/6855 [03:26<20:57,  4.68it/s]

Processing tickers:  14%|█▍        | 968/6855 [03:27<20:55,  4.69it/s]

Processing tickers:  14%|█▍        | 969/6855 [03:27<21:28,  4.57it/s]

Processing tickers:  14%|█▍        | 970/6855 [03:27<21:07,  4.64it/s]

Processing tickers:  14%|█▍        | 971/6855 [03:27<21:27,  4.57it/s]

Processing tickers:  14%|█▍        | 972/6855 [03:28<21:19,  4.60it/s]

Processing tickers:  14%|█▍        | 973/6855 [03:28<20:59,  4.67it/s]

Processing tickers:  14%|█▍        | 974/6855 [03:28<20:56,  4.68it/s]

Processing tickers:  14%|█▍        | 975/6855 [03:28<21:28,  4.56it/s]

Processing tickers:  14%|█▍        | 976/6855 [03:28<21:07,  4.64it/s]

Processing tickers:  14%|█▍        | 977/6855 [03:29<20:58,  4.67it/s]

Processing tickers:  14%|█▍        | 978/6855 [03:29<20:57,  4.67it/s]

Processing tickers:  14%|█▍        | 979/6855 [03:29<20:56,  4.68it/s]

Processing tickers:  14%|█▍        | 980/6855 [03:29<20:57,  4.67it/s]

Processing tickers:  14%|█▍        | 981/6855 [03:29<20:46,  4.71it/s]

Processing tickers:  14%|█▍        | 982/6855 [03:30<20:56,  4.67it/s]

Processing tickers:  14%|█▍        | 983/6855 [03:30<21:13,  4.61it/s]

Processing tickers:  14%|█▍        | 984/6855 [03:30<20:58,  4.67it/s]

Processing tickers:  14%|█▍        | 985/6855 [03:30<20:52,  4.69it/s]

Processing tickers:  14%|█▍        | 986/6855 [03:31<20:37,  4.74it/s]

Processing tickers:  14%|█▍        | 987/6855 [03:31<20:45,  4.71it/s]

Processing tickers:  14%|█▍        | 988/6855 [03:31<20:55,  4.67it/s]

Processing tickers:  14%|█▍        | 989/6855 [03:31<21:04,  4.64it/s]

Processing tickers:  14%|█▍        | 990/6855 [03:31<21:12,  4.61it/s]

Processing tickers:  14%|█▍        | 991/6855 [03:32<21:06,  4.63it/s]

Processing tickers:  14%|█▍        | 992/6855 [03:32<21:06,  4.63it/s]

Processing tickers:  14%|█▍        | 993/6855 [03:32<21:00,  4.65it/s]

Processing tickers:  15%|█▍        | 994/6855 [03:32<20:44,  4.71it/s]

Processing tickers:  15%|█▍        | 995/6855 [03:32<20:45,  4.71it/s]

Processing tickers:  15%|█▍        | 996/6855 [03:33<21:08,  4.62it/s]

Processing tickers:  15%|█▍        | 997/6855 [03:33<20:45,  4.70it/s]

Processing tickers:  15%|█▍        | 998/6855 [03:33<20:35,  4.74it/s]

Processing tickers:  15%|█▍        | 999/6855 [03:33<20:34,  4.74it/s]

Processing tickers:  15%|█▍        | 1000/6855 [03:34<20:24,  4.78it/s]

Processing tickers:  15%|█▍        | 1001/6855 [03:34<20:17,  4.81it/s]

Processing tickers:  15%|█▍        | 1002/6855 [03:34<20:42,  4.71it/s]

Processing tickers:  15%|█▍        | 1003/6855 [03:34<21:23,  4.56it/s]

Processing tickers:  15%|█▍        | 1004/6855 [03:34<21:40,  4.50it/s]

Processing tickers:  15%|█▍        | 1005/6855 [03:35<21:19,  4.57it/s]

Processing tickers:  15%|█▍        | 1006/6855 [03:35<20:54,  4.66it/s]

Processing tickers:  15%|█▍        | 1007/6855 [03:35<21:22,  4.56it/s]

Processing tickers:  15%|█▍        | 1008/6855 [03:35<21:02,  4.63it/s]

Processing tickers:  15%|█▍        | 1009/6855 [03:36<20:54,  4.66it/s]

Processing tickers:  15%|█▍        | 1010/6855 [03:36<20:59,  4.64it/s]

Processing tickers:  15%|█▍        | 1011/6855 [03:36<21:23,  4.55it/s]

Processing tickers:  15%|█▍        | 1012/6855 [03:36<21:24,  4.55it/s]

Processing tickers:  15%|█▍        | 1013/6855 [03:36<21:11,  4.59it/s]

Processing tickers:  15%|█▍        | 1014/6855 [03:37<21:02,  4.63it/s]

Processing tickers:  15%|█▍        | 1015/6855 [03:37<20:47,  4.68it/s]

Processing tickers:  15%|█▍        | 1016/6855 [03:37<21:18,  4.57it/s]

Processing tickers:  15%|█▍        | 1017/6855 [03:37<21:33,  4.51it/s]

Processing tickers:  15%|█▍        | 1018/6855 [03:37<21:16,  4.57it/s]

Processing tickers:  15%|█▍        | 1019/6855 [03:38<21:11,  4.59it/s]

Processing tickers:  15%|█▍        | 1020/6855 [03:38<20:49,  4.67it/s]

Processing tickers:  15%|█▍        | 1021/6855 [03:38<20:38,  4.71it/s]

Processing tickers:  15%|█▍        | 1022/6855 [03:38<20:31,  4.74it/s]

Processing tickers:  15%|█▍        | 1023/6855 [03:39<20:29,  4.74it/s]

Processing tickers:  15%|█▍        | 1024/6855 [03:39<20:30,  4.74it/s]

Processing tickers:  15%|█▍        | 1025/6855 [03:39<20:21,  4.77it/s]

Processing tickers:  15%|█▍        | 1026/6855 [03:39<20:13,  4.80it/s]

Processing tickers:  15%|█▍        | 1027/6855 [03:39<20:58,  4.63it/s]

Processing tickers:  15%|█▍        | 1028/6855 [03:40<20:38,  4.70it/s]

Processing tickers:  15%|█▌        | 1029/6855 [03:40<20:59,  4.63it/s]

Processing tickers:  15%|█▌        | 1030/6855 [03:40<20:50,  4.66it/s]

Processing tickers:  15%|█▌        | 1031/6855 [03:40<20:45,  4.68it/s]

Processing tickers:  15%|█▌        | 1032/6855 [03:40<21:08,  4.59it/s]

Processing tickers:  15%|█▌        | 1033/6855 [03:41<21:17,  4.56it/s]

Processing tickers:  15%|█▌        | 1034/6855 [03:41<20:54,  4.64it/s]

Processing tickers:  15%|█▌        | 1035/6855 [03:41<20:54,  4.64it/s]

Processing tickers:  15%|█▌        | 1036/6855 [03:41<20:49,  4.66it/s]

Processing tickers:  15%|█▌        | 1037/6855 [03:42<20:36,  4.71it/s]

Processing tickers:  15%|█▌        | 1038/6855 [03:42<20:30,  4.73it/s]

Processing tickers:  15%|█▌        | 1039/6855 [03:42<20:57,  4.62it/s]

Processing tickers:  15%|█▌        | 1040/6855 [03:42<21:45,  4.45it/s]

Processing tickers:  15%|█▌        | 1041/6855 [03:42<21:20,  4.54it/s]

Processing tickers:  15%|█▌        | 1042/6855 [03:43<20:58,  4.62it/s]

Processing tickers:  15%|█▌        | 1043/6855 [03:43<20:55,  4.63it/s]

Processing tickers:  15%|█▌        | 1044/6855 [03:43<20:33,  4.71it/s]

Processing tickers:  15%|█▌        | 1045/6855 [03:43<20:51,  4.64it/s]

Processing tickers:  15%|█▌        | 1046/6855 [03:43<20:45,  4.66it/s]

Processing tickers:  15%|█▌        | 1047/6855 [03:44<21:02,  4.60it/s]

Processing tickers:  15%|█▌        | 1048/6855 [03:44<20:44,  4.67it/s]

Processing tickers:  15%|█▌        | 1049/6855 [03:44<20:54,  4.63it/s]

Processing tickers:  15%|█▌        | 1050/6855 [03:44<20:43,  4.67it/s]

Processing tickers:  15%|█▌        | 1051/6855 [03:45<20:40,  4.68it/s]

Processing tickers:  15%|█▌        | 1052/6855 [03:45<21:08,  4.57it/s]

Processing tickers:  15%|█▌        | 1053/6855 [03:45<20:54,  4.63it/s]

Processing tickers:  15%|█▌        | 1054/6855 [03:45<21:19,  4.53it/s]

Processing tickers:  15%|█▌        | 1055/6855 [03:45<20:58,  4.61it/s]

Processing tickers:  15%|█▌        | 1056/6855 [03:46<20:58,  4.61it/s]

Processing tickers:  15%|█▌        | 1057/6855 [03:46<21:01,  4.60it/s]

Processing tickers:  15%|█▌        | 1058/6855 [03:46<20:56,  4.61it/s]

Processing tickers:  15%|█▌        | 1059/6855 [03:46<20:43,  4.66it/s]

Processing tickers:  15%|█▌        | 1060/6855 [03:47<21:10,  4.56it/s]

Processing tickers:  15%|█▌        | 1061/6855 [03:47<20:59,  4.60it/s]

Processing tickers:  15%|█▌        | 1062/6855 [03:47<20:48,  4.64it/s]

Processing tickers:  16%|█▌        | 1063/6855 [03:47<21:20,  4.52it/s]

Processing tickers:  16%|█▌        | 1064/6855 [03:47<20:58,  4.60it/s]

Processing tickers:  16%|█▌        | 1065/6855 [03:48<21:40,  4.45it/s]

Processing tickers:  16%|█▌        | 1066/6855 [03:48<21:18,  4.53it/s]

Processing tickers:  16%|█▌        | 1067/6855 [03:48<20:58,  4.60it/s]

Processing tickers:  16%|█▌        | 1068/6855 [03:48<20:55,  4.61it/s]

Processing tickers:  16%|█▌        | 1069/6855 [03:48<20:39,  4.67it/s]

Processing tickers:  16%|█▌        | 1070/6855 [03:49<20:23,  4.73it/s]

Processing tickers:  16%|█▌        | 1071/6855 [03:49<20:24,  4.72it/s]

Processing tickers:  16%|█▌        | 1072/6855 [03:49<20:19,  4.74it/s]

Processing tickers:  16%|█▌        | 1073/6855 [03:49<20:12,  4.77it/s]

Processing tickers:  16%|█▌        | 1074/6855 [03:50<20:16,  4.75it/s]

Processing tickers:  16%|█▌        | 1075/6855 [03:50<20:04,  4.80it/s]

Processing tickers:  16%|█▌        | 1076/6855 [03:50<20:29,  4.70it/s]

Processing tickers:  16%|█▌        | 1077/6855 [03:50<20:14,  4.76it/s]

Processing tickers:  16%|█▌        | 1078/6855 [03:50<20:20,  4.73it/s]

Processing tickers:  16%|█▌        | 1079/6855 [03:51<20:36,  4.67it/s]

Processing tickers:  16%|█▌        | 1080/6855 [03:51<20:29,  4.70it/s]

Processing tickers:  16%|█▌        | 1081/6855 [03:51<21:38,  4.45it/s]

Processing tickers:  16%|█▌        | 1082/6855 [03:51<21:45,  4.42it/s]

Processing tickers:  16%|█▌        | 1083/6855 [03:51<21:16,  4.52it/s]

Processing tickers:  16%|█▌        | 1084/6855 [03:52<20:56,  4.59it/s]

Processing tickers:  16%|█▌        | 1085/6855 [03:52<21:31,  4.47it/s]

Processing tickers:  16%|█▌        | 1086/6855 [03:52<21:02,  4.57it/s]

Processing tickers:  16%|█▌        | 1087/6855 [03:52<21:14,  4.53it/s]

Processing tickers:  16%|█▌        | 1088/6855 [03:53<21:11,  4.53it/s]

Processing tickers:  16%|█▌        | 1089/6855 [03:53<21:16,  4.52it/s]

Processing tickers:  16%|█▌        | 1090/6855 [03:53<21:37,  4.44it/s]

Processing tickers:  16%|█▌        | 1091/6855 [03:53<21:11,  4.53it/s]

Processing tickers:  16%|█▌        | 1092/6855 [03:54<26:59,  3.56it/s]

Processing tickers:  16%|█▌        | 1093/6855 [03:54<25:01,  3.84it/s]

Processing tickers:  16%|█▌        | 1094/6855 [03:54<23:29,  4.09it/s]

Processing tickers:  16%|█▌        | 1095/6855 [03:54<22:53,  4.19it/s]

Processing tickers:  16%|█▌        | 1096/6855 [03:55<22:04,  4.35it/s]

Processing tickers:  16%|█▌        | 1097/6855 [03:55<21:19,  4.50it/s]

Processing tickers:  16%|█▌        | 1098/6855 [03:55<20:47,  4.61it/s]

Processing tickers:  16%|█▌        | 1099/6855 [03:55<20:27,  4.69it/s]

Processing tickers:  16%|█▌        | 1100/6855 [03:55<20:23,  4.70it/s]

Processing tickers:  16%|█▌        | 1101/6855 [03:56<20:58,  4.57it/s]

Processing tickers:  16%|█▌        | 1102/6855 [03:56<20:43,  4.63it/s]

Processing tickers:  16%|█▌        | 1103/6855 [03:56<20:46,  4.62it/s]

Processing tickers:  16%|█▌        | 1104/6855 [03:56<20:57,  4.57it/s]

Processing tickers:  16%|█▌        | 1105/6855 [03:56<21:04,  4.55it/s]

Processing tickers:  16%|█▌        | 1106/6855 [03:57<20:45,  4.62it/s]

Processing tickers:  16%|█▌        | 1107/6855 [03:57<20:36,  4.65it/s]

Processing tickers:  16%|█▌        | 1108/6855 [03:57<20:24,  4.69it/s]

Processing tickers:  16%|█▌        | 1109/6855 [03:57<20:34,  4.65it/s]

Processing tickers:  16%|█▌        | 1110/6855 [03:58<20:27,  4.68it/s]

Processing tickers:  16%|█▌        | 1111/6855 [03:58<20:27,  4.68it/s]

Processing tickers:  16%|█▌        | 1112/6855 [03:58<20:31,  4.67it/s]

Processing tickers:  16%|█▌        | 1113/6855 [03:58<20:15,  4.72it/s]

Processing tickers:  16%|█▋        | 1114/6855 [03:58<20:10,  4.74it/s]

Processing tickers:  16%|█▋        | 1115/6855 [03:59<20:06,  4.76it/s]

Processing tickers:  16%|█▋        | 1116/6855 [03:59<19:59,  4.78it/s]

Processing tickers:  16%|█▋        | 1117/6855 [03:59<20:25,  4.68it/s]

Processing tickers:  16%|█▋        | 1118/6855 [03:59<20:30,  4.66it/s]

Processing tickers:  16%|█▋        | 1119/6855 [03:59<20:54,  4.57it/s]

Processing tickers:  16%|█▋        | 1120/6855 [04:00<21:16,  4.49it/s]

Processing tickers:  16%|█▋        | 1121/6855 [04:00<20:49,  4.59it/s]

Processing tickers:  16%|█▋        | 1122/6855 [04:00<20:32,  4.65it/s]

Processing tickers:  16%|█▋        | 1123/6855 [04:00<21:32,  4.44it/s]

Processing tickers:  16%|█▋        | 1124/6855 [04:01<21:05,  4.53it/s]

Processing tickers:  16%|█▋        | 1125/6855 [04:01<20:48,  4.59it/s]

Processing tickers:  16%|█▋        | 1126/6855 [04:01<21:06,  4.52it/s]

Processing tickers:  16%|█▋        | 1127/6855 [04:01<20:49,  4.59it/s]

Processing tickers:  16%|█▋        | 1128/6855 [04:01<21:05,  4.53it/s]

Processing tickers:  16%|█▋        | 1129/6855 [04:02<21:19,  4.48it/s]

Processing tickers:  16%|█▋        | 1130/6855 [04:02<20:52,  4.57it/s]

Processing tickers:  16%|█▋        | 1131/6855 [04:02<20:31,  4.65it/s]

Processing tickers:  17%|█▋        | 1132/6855 [04:02<20:58,  4.55it/s]

Processing tickers:  17%|█▋        | 1133/6855 [04:03<21:03,  4.53it/s]

Processing tickers:  17%|█▋        | 1134/6855 [04:03<20:40,  4.61it/s]

Processing tickers:  17%|█▋        | 1135/6855 [04:03<20:40,  4.61it/s]

Processing tickers:  17%|█▋        | 1136/6855 [04:03<20:28,  4.66it/s]

Processing tickers:  17%|█▋        | 1137/6855 [04:03<20:24,  4.67it/s]

Processing tickers:  17%|█▋        | 1138/6855 [04:04<20:17,  4.70it/s]

Processing tickers:  17%|█▋        | 1139/6855 [04:04<20:30,  4.64it/s]

Processing tickers:  17%|█▋        | 1140/6855 [04:04<20:19,  4.69it/s]

Processing tickers:  17%|█▋        | 1141/6855 [04:04<20:11,  4.72it/s]

Processing tickers:  17%|█▋        | 1142/6855 [04:04<20:13,  4.71it/s]

Processing tickers:  17%|█▋        | 1143/6855 [04:05<20:07,  4.73it/s]

Processing tickers:  17%|█▋        | 1144/6855 [04:05<20:39,  4.61it/s]

Processing tickers:  17%|█▋        | 1145/6855 [04:05<20:17,  4.69it/s]

Processing tickers:  17%|█▋        | 1146/6855 [04:05<20:10,  4.72it/s]

Processing tickers:  17%|█▋        | 1147/6855 [04:06<20:04,  4.74it/s]

Processing tickers:  17%|█▋        | 1148/6855 [04:06<20:51,  4.56it/s]

Processing tickers:  17%|█▋        | 1149/6855 [04:06<20:37,  4.61it/s]

Processing tickers:  17%|█▋        | 1150/6855 [04:06<20:18,  4.68it/s]

Processing tickers:  17%|█▋        | 1151/6855 [04:06<20:47,  4.57it/s]

Processing tickers:  17%|█▋        | 1152/6855 [04:07<20:44,  4.58it/s]

Processing tickers:  17%|█▋        | 1153/6855 [04:07<20:19,  4.68it/s]

Processing tickers:  17%|█▋        | 1154/6855 [04:07<20:01,  4.74it/s]

Processing tickers:  17%|█▋        | 1155/6855 [04:07<20:18,  4.68it/s]

Processing tickers:  17%|█▋        | 1156/6855 [04:07<19:58,  4.76it/s]

Processing tickers:  17%|█▋        | 1157/6855 [04:08<19:52,  4.78it/s]

Processing tickers:  17%|█▋        | 1158/6855 [04:08<19:47,  4.80it/s]

Processing tickers:  17%|█▋        | 1159/6855 [04:08<19:57,  4.76it/s]

Processing tickers:  17%|█▋        | 1160/6855 [04:08<20:00,  4.74it/s]

Processing tickers:  17%|█▋        | 1161/6855 [04:08<19:49,  4.79it/s]

Processing tickers:  17%|█▋        | 1162/6855 [04:09<19:52,  4.77it/s]

Processing tickers:  17%|█▋        | 1163/6855 [04:09<20:00,  4.74it/s]

Processing tickers:  17%|█▋        | 1164/6855 [04:09<19:56,  4.76it/s]

Processing tickers:  17%|█▋        | 1165/6855 [04:09<19:56,  4.76it/s]

Processing tickers:  17%|█▋        | 1166/6855 [04:10<20:12,  4.69it/s]

Processing tickers:  17%|█▋        | 1167/6855 [04:10<20:39,  4.59it/s]

Processing tickers:  17%|█▋        | 1168/6855 [04:10<20:27,  4.63it/s]

Processing tickers:  17%|█▋        | 1169/6855 [04:10<20:26,  4.64it/s]

Processing tickers:  17%|█▋        | 1170/6855 [04:10<20:08,  4.71it/s]

Processing tickers:  17%|█▋        | 1171/6855 [04:11<20:03,  4.72it/s]

Processing tickers:  17%|█▋        | 1172/6855 [04:11<20:19,  4.66it/s]

Processing tickers:  17%|█▋        | 1173/6855 [04:11<20:08,  4.70it/s]

Processing tickers:  17%|█▋        | 1174/6855 [04:11<20:33,  4.60it/s]

Processing tickers:  17%|█▋        | 1175/6855 [04:11<20:31,  4.61it/s]

Processing tickers:  17%|█▋        | 1176/6855 [04:12<21:03,  4.49it/s]

Processing tickers:  17%|█▋        | 1177/6855 [04:12<20:36,  4.59it/s]

Processing tickers:  17%|█▋        | 1178/6855 [04:12<20:22,  4.65it/s]

Processing tickers:  17%|█▋        | 1179/6855 [04:12<20:30,  4.61it/s]

Processing tickers:  17%|█▋        | 1180/6855 [04:13<20:15,  4.67it/s]

Processing tickers:  17%|█▋        | 1181/6855 [04:13<20:10,  4.69it/s]

Processing tickers:  17%|█▋        | 1182/6855 [04:13<20:02,  4.72it/s]

Processing tickers:  17%|█▋        | 1183/6855 [04:13<20:06,  4.70it/s]

Processing tickers:  17%|█▋        | 1184/6855 [04:13<20:04,  4.71it/s]

Processing tickers:  17%|█▋        | 1185/6855 [04:14<20:32,  4.60it/s]

Processing tickers:  17%|█▋        | 1186/6855 [04:14<20:15,  4.66it/s]

Processing tickers:  17%|█▋        | 1187/6855 [04:14<20:50,  4.53it/s]

Processing tickers:  17%|█▋        | 1188/6855 [04:14<20:38,  4.57it/s]

Processing tickers:  17%|█▋        | 1189/6855 [04:15<20:22,  4.63it/s]

Processing tickers:  17%|█▋        | 1190/6855 [04:15<20:50,  4.53it/s]

Processing tickers:  17%|█▋        | 1191/6855 [04:15<20:31,  4.60it/s]

Processing tickers:  17%|█▋        | 1192/6855 [04:15<20:33,  4.59it/s]

Processing tickers:  17%|█▋        | 1193/6855 [04:15<20:37,  4.57it/s]

Processing tickers:  17%|█▋        | 1194/6855 [04:16<20:32,  4.59it/s]

Processing tickers:  17%|█▋        | 1195/6855 [04:16<20:18,  4.65it/s]

Processing tickers:  17%|█▋        | 1196/6855 [04:16<20:03,  4.70it/s]

Processing tickers:  17%|█▋        | 1197/6855 [04:16<20:00,  4.71it/s]

Processing tickers:  17%|█▋        | 1198/6855 [04:16<20:07,  4.68it/s]

Processing tickers:  17%|█▋        | 1199/6855 [04:17<19:57,  4.72it/s]

Processing tickers:  18%|█▊        | 1200/6855 [04:17<19:54,  4.73it/s]

Processing tickers:  18%|█▊        | 1201/6855 [04:17<19:57,  4.72it/s]

Processing tickers:  18%|█▊        | 1202/6855 [04:17<19:57,  4.72it/s]

Processing tickers:  18%|█▊        | 1203/6855 [04:17<19:47,  4.76it/s]

Processing tickers:  18%|█▊        | 1204/6855 [04:18<20:33,  4.58it/s]

Processing tickers:  18%|█▊        | 1205/6855 [04:18<20:57,  4.49it/s]

Processing tickers:  18%|█▊        | 1206/6855 [04:18<20:28,  4.60it/s]

Processing tickers:  18%|█▊        | 1207/6855 [04:18<20:40,  4.55it/s]

Processing tickers:  18%|█▊        | 1208/6855 [04:19<20:58,  4.49it/s]

Processing tickers:  18%|█▊        | 1209/6855 [04:19<20:52,  4.51it/s]

Processing tickers:  18%|█▊        | 1210/6855 [04:19<21:41,  4.34it/s]

Processing tickers:  18%|█▊        | 1211/6855 [04:19<21:05,  4.46it/s]

Processing tickers:  18%|█▊        | 1212/6855 [04:20<20:41,  4.55it/s]

Processing tickers:  18%|█▊        | 1213/6855 [04:20<20:55,  4.49it/s]

Processing tickers:  18%|█▊        | 1214/6855 [04:20<20:29,  4.59it/s]

Processing tickers:  18%|█▊        | 1215/6855 [04:20<21:12,  4.43it/s]

Processing tickers:  18%|█▊        | 1216/6855 [04:20<21:17,  4.41it/s]

Processing tickers:  18%|█▊        | 1217/6855 [04:21<21:28,  4.37it/s]

Processing tickers:  18%|█▊        | 1218/6855 [04:21<20:56,  4.49it/s]

Processing tickers:  18%|█▊        | 1219/6855 [04:21<20:42,  4.54it/s]

Processing tickers:  18%|█▊        | 1220/6855 [04:21<20:28,  4.59it/s]

Processing tickers:  18%|█▊        | 1221/6855 [04:22<20:45,  4.52it/s]

Processing tickers:  18%|█▊        | 1222/6855 [04:22<20:54,  4.49it/s]

Processing tickers:  18%|█▊        | 1223/6855 [04:22<20:31,  4.57it/s]

Processing tickers:  18%|█▊        | 1224/6855 [04:22<20:23,  4.60it/s]

Processing tickers:  18%|█▊        | 1225/6855 [04:22<20:06,  4.67it/s]

Processing tickers:  18%|█▊        | 1226/6855 [04:23<20:31,  4.57it/s]

Processing tickers:  18%|█▊        | 1227/6855 [04:23<20:07,  4.66it/s]

Processing tickers:  18%|█▊        | 1228/6855 [04:23<19:54,  4.71it/s]

Processing tickers:  18%|█▊        | 1229/6855 [04:23<19:44,  4.75it/s]

Processing tickers:  18%|█▊        | 1230/6855 [04:23<19:45,  4.74it/s]

Processing tickers:  18%|█▊        | 1231/6855 [04:24<20:13,  4.63it/s]

Processing tickers:  18%|█▊        | 1232/6855 [04:24<19:59,  4.69it/s]

Processing tickers:  18%|█▊        | 1233/6855 [04:24<20:18,  4.61it/s]

Processing tickers:  18%|█▊        | 1234/6855 [04:24<20:39,  4.53it/s]

Processing tickers:  18%|█▊        | 1235/6855 [04:25<20:21,  4.60it/s]

Processing tickers:  18%|█▊        | 1236/6855 [04:25<20:08,  4.65it/s]

Processing tickers:  18%|█▊        | 1237/6855 [04:25<20:26,  4.58it/s]

Processing tickers:  18%|█▊        | 1238/6855 [04:25<21:21,  4.38it/s]

Processing tickers:  18%|█▊        | 1239/6855 [04:25<21:13,  4.41it/s]

Processing tickers:  18%|█▊        | 1240/6855 [04:26<21:16,  4.40it/s]

Processing tickers:  18%|█▊        | 1241/6855 [04:26<20:57,  4.46it/s]

Processing tickers:  18%|█▊        | 1242/6855 [04:26<20:28,  4.57it/s]

Processing tickers:  18%|█▊        | 1243/6855 [04:26<20:40,  4.52it/s]

Processing tickers:  18%|█▊        | 1244/6855 [04:27<20:26,  4.57it/s]

Processing tickers:  18%|█▊        | 1245/6855 [04:27<20:51,  4.48it/s]

Processing tickers:  18%|█▊        | 1246/6855 [04:27<20:32,  4.55it/s]

Processing tickers:  18%|█▊        | 1247/6855 [04:27<20:34,  4.54it/s]

Processing tickers:  18%|█▊        | 1248/6855 [04:27<20:08,  4.64it/s]

Processing tickers:  18%|█▊        | 1249/6855 [04:28<20:04,  4.65it/s]

Processing tickers:  18%|█▊        | 1250/6855 [04:28<20:04,  4.65it/s]

Processing tickers:  18%|█▊        | 1251/6855 [04:28<19:53,  4.70it/s]

Processing tickers:  18%|█▊        | 1252/6855 [04:28<19:39,  4.75it/s]

Processing tickers:  18%|█▊        | 1253/6855 [04:28<19:34,  4.77it/s]

Processing tickers:  18%|█▊        | 1254/6855 [04:29<19:30,  4.78it/s]

Processing tickers:  18%|█▊        | 1255/6855 [04:29<19:29,  4.79it/s]

Processing tickers:  18%|█▊        | 1256/6855 [04:29<19:27,  4.79it/s]

Processing tickers:  18%|█▊        | 1257/6855 [04:29<19:32,  4.77it/s]

Processing tickers:  18%|█▊        | 1258/6855 [04:30<19:25,  4.80it/s]

Processing tickers:  18%|█▊        | 1259/6855 [04:30<20:17,  4.60it/s]

Processing tickers:  18%|█▊        | 1260/6855 [04:30<20:02,  4.65it/s]

Processing tickers:  18%|█▊        | 1261/6855 [04:30<20:11,  4.62it/s]

Processing tickers:  18%|█▊        | 1262/6855 [04:30<20:16,  4.60it/s]

Processing tickers:  18%|█▊        | 1263/6855 [04:31<20:37,  4.52it/s]

Processing tickers:  18%|█▊        | 1264/6855 [04:31<20:51,  4.47it/s]

Processing tickers:  18%|█▊        | 1265/6855 [04:31<20:24,  4.57it/s]

Processing tickers:  18%|█▊        | 1266/6855 [04:31<20:05,  4.64it/s]

Processing tickers:  18%|█▊        | 1267/6855 [04:31<19:53,  4.68it/s]

Processing tickers:  18%|█▊        | 1268/6855 [04:32<19:47,  4.70it/s]

Processing tickers:  19%|█▊        | 1269/6855 [04:32<19:43,  4.72it/s]

Processing tickers:  19%|█▊        | 1270/6855 [04:32<19:54,  4.68it/s]

Processing tickers:  19%|█▊        | 1271/6855 [04:32<19:55,  4.67it/s]

Processing tickers:  19%|█▊        | 1272/6855 [04:33<20:24,  4.56it/s]

Processing tickers:  19%|█▊        | 1273/6855 [04:33<20:16,  4.59it/s]

Processing tickers:  19%|█▊        | 1274/6855 [04:33<20:11,  4.61it/s]

Processing tickers:  19%|█▊        | 1275/6855 [04:33<20:29,  4.54it/s]

Processing tickers:  19%|█▊        | 1276/6855 [04:33<20:42,  4.49it/s]

Processing tickers:  19%|█▊        | 1277/6855 [04:34<20:19,  4.57it/s]

Processing tickers:  19%|█▊        | 1278/6855 [04:34<19:58,  4.66it/s]

Processing tickers:  19%|█▊        | 1279/6855 [04:34<19:47,  4.70it/s]

Processing tickers:  19%|█▊        | 1280/6855 [04:34<19:42,  4.72it/s]

Processing tickers:  19%|█▊        | 1281/6855 [04:34<19:42,  4.71it/s]

Processing tickers:  19%|█▊        | 1282/6855 [04:35<19:34,  4.74it/s]

Processing tickers:  19%|█▊        | 1283/6855 [04:35<19:27,  4.77it/s]

Processing tickers:  19%|█▊        | 1284/6855 [04:35<19:50,  4.68it/s]

Processing tickers:  19%|█▊        | 1285/6855 [04:35<20:04,  4.63it/s]

Processing tickers:  19%|█▉        | 1286/6855 [04:36<19:54,  4.66it/s]

Processing tickers:  19%|█▉        | 1287/6855 [04:36<20:18,  4.57it/s]

Processing tickers:  19%|█▉        | 1288/6855 [04:36<20:00,  4.64it/s]

Processing tickers:  19%|█▉        | 1289/6855 [04:36<19:58,  4.64it/s]

Processing tickers:  19%|█▉        | 1290/6855 [04:36<19:43,  4.70it/s]

Processing tickers:  19%|█▉        | 1291/6855 [04:37<19:38,  4.72it/s]

Processing tickers:  19%|█▉        | 1292/6855 [04:37<20:19,  4.56it/s]

Processing tickers:  19%|█▉        | 1293/6855 [04:37<20:04,  4.62it/s]

Processing tickers:  19%|█▉        | 1294/6855 [04:37<19:54,  4.66it/s]

Processing tickers:  19%|█▉        | 1295/6855 [04:37<19:42,  4.70it/s]

Processing tickers:  19%|█▉        | 1296/6855 [04:38<19:41,  4.70it/s]

Processing tickers:  19%|█▉        | 1297/6855 [04:38<19:48,  4.68it/s]

Processing tickers:  19%|█▉        | 1298/6855 [04:38<19:43,  4.70it/s]

Processing tickers:  19%|█▉        | 1299/6855 [04:38<19:45,  4.69it/s]

Processing tickers:  19%|█▉        | 1300/6855 [04:39<19:30,  4.75it/s]

Processing tickers:  19%|█▉        | 1301/6855 [04:39<19:28,  4.76it/s]

Processing tickers:  19%|█▉        | 1302/6855 [04:39<19:29,  4.75it/s]

Processing tickers:  19%|█▉        | 1303/6855 [04:39<19:37,  4.72it/s]

Processing tickers:  19%|█▉        | 1304/6855 [04:39<19:31,  4.74it/s]

Processing tickers:  19%|█▉        | 1305/6855 [04:40<19:33,  4.73it/s]

Processing tickers:  19%|█▉        | 1306/6855 [04:40<19:31,  4.74it/s]

Processing tickers:  19%|█▉        | 1307/6855 [04:40<19:36,  4.71it/s]

Processing tickers:  19%|█▉        | 1308/6855 [04:40<19:37,  4.71it/s]

Processing tickers:  19%|█▉        | 1309/6855 [04:40<19:35,  4.72it/s]

Processing tickers:  19%|█▉        | 1310/6855 [04:41<20:03,  4.61it/s]

Processing tickers:  19%|█▉        | 1311/6855 [04:41<20:28,  4.51it/s]

Processing tickers:  19%|█▉        | 1312/6855 [04:41<20:06,  4.60it/s]

Processing tickers:  19%|█▉        | 1313/6855 [04:41<20:03,  4.61it/s]

Processing tickers:  19%|█▉        | 1314/6855 [04:42<19:49,  4.66it/s]

Processing tickers:  19%|█▉        | 1315/6855 [04:42<19:42,  4.69it/s]

Processing tickers:  19%|█▉        | 1316/6855 [04:42<19:33,  4.72it/s]

Processing tickers:  19%|█▉        | 1317/6855 [04:42<19:25,  4.75it/s]

Processing tickers:  19%|█▉        | 1318/6855 [04:42<19:38,  4.70it/s]

Processing tickers:  19%|█▉        | 1319/6855 [04:43<19:32,  4.72it/s]

Processing tickers:  19%|█▉        | 1320/6855 [04:43<19:27,  4.74it/s]

Processing tickers:  19%|█▉        | 1321/6855 [04:43<19:22,  4.76it/s]

Processing tickers:  19%|█▉        | 1322/6855 [04:43<19:20,  4.77it/s]

Processing tickers:  19%|█▉        | 1323/6855 [04:43<19:24,  4.75it/s]

Processing tickers:  19%|█▉        | 1324/6855 [04:44<19:25,  4.74it/s]

Processing tickers:  19%|█▉        | 1325/6855 [04:44<19:22,  4.76it/s]

Processing tickers:  19%|█▉        | 1326/6855 [04:44<19:24,  4.75it/s]

Processing tickers:  19%|█▉        | 1327/6855 [04:44<19:26,  4.74it/s]

Processing tickers:  19%|█▉        | 1328/6855 [04:45<19:31,  4.72it/s]

Processing tickers:  19%|█▉        | 1329/6855 [04:45<20:02,  4.60it/s]

Processing tickers:  19%|█▉        | 1330/6855 [04:45<20:50,  4.42it/s]

Processing tickers:  19%|█▉        | 1331/6855 [04:45<20:39,  4.46it/s]

Processing tickers:  19%|█▉        | 1332/6855 [04:45<20:55,  4.40it/s]

Processing tickers:  19%|█▉        | 1333/6855 [04:46<20:43,  4.44it/s]

Processing tickers:  19%|█▉        | 1334/6855 [04:46<20:12,  4.56it/s]

Processing tickers:  19%|█▉        | 1335/6855 [04:46<19:47,  4.65it/s]

Processing tickers:  19%|█▉        | 1336/6855 [04:46<19:26,  4.73it/s]

Processing tickers:  20%|█▉        | 1337/6855 [04:46<19:22,  4.75it/s]

Processing tickers:  20%|█▉        | 1338/6855 [04:47<19:16,  4.77it/s]

Processing tickers:  20%|█▉        | 1339/6855 [04:47<19:24,  4.74it/s]

Processing tickers:  20%|█▉        | 1340/6855 [04:47<19:47,  4.64it/s]

Processing tickers:  20%|█▉        | 1341/6855 [04:47<19:34,  4.70it/s]

Processing tickers:  20%|█▉        | 1342/6855 [04:48<20:30,  4.48it/s]

Processing tickers:  20%|█▉        | 1343/6855 [04:48<20:32,  4.47it/s]

Processing tickers:  20%|█▉        | 1344/6855 [04:48<20:24,  4.50it/s]

Processing tickers:  20%|█▉        | 1345/6855 [04:48<20:05,  4.57it/s]

Processing tickers:  20%|█▉        | 1346/6855 [04:48<19:54,  4.61it/s]

Processing tickers:  20%|█▉        | 1347/6855 [04:49<19:37,  4.68it/s]

Processing tickers:  20%|█▉        | 1348/6855 [04:49<19:32,  4.70it/s]

Processing tickers:  20%|█▉        | 1349/6855 [04:49<19:24,  4.73it/s]

Processing tickers:  20%|█▉        | 1350/6855 [04:49<19:33,  4.69it/s]

Processing tickers:  20%|█▉        | 1351/6855 [04:50<19:31,  4.70it/s]

Processing tickers:  20%|█▉        | 1352/6855 [04:50<19:45,  4.64it/s]

Processing tickers:  20%|█▉        | 1353/6855 [04:50<19:35,  4.68it/s]

Processing tickers:  20%|█▉        | 1354/6855 [04:50<19:19,  4.74it/s]

Processing tickers:  20%|█▉        | 1355/6855 [04:50<19:16,  4.75it/s]

Processing tickers:  20%|█▉        | 1356/6855 [04:51<19:34,  4.68it/s]

Processing tickers:  20%|█▉        | 1357/6855 [04:51<20:35,  4.45it/s]

Processing tickers:  20%|█▉        | 1358/6855 [04:51<20:07,  4.55it/s]

Processing tickers:  20%|█▉        | 1359/6855 [04:51<19:48,  4.63it/s]

Processing tickers:  20%|█▉        | 1360/6855 [04:51<19:38,  4.66it/s]

Processing tickers:  20%|█▉        | 1361/6855 [04:52<19:28,  4.70it/s]

Processing tickers:  20%|█▉        | 1362/6855 [04:52<19:25,  4.71it/s]

Processing tickers:  20%|█▉        | 1363/6855 [04:52<19:15,  4.75it/s]

Processing tickers:  20%|█▉        | 1364/6855 [04:52<19:23,  4.72it/s]

Processing tickers:  20%|█▉        | 1365/6855 [04:53<19:28,  4.70it/s]

Processing tickers:  20%|█▉        | 1366/6855 [04:53<19:54,  4.60it/s]

Processing tickers:  20%|█▉        | 1367/6855 [04:53<19:44,  4.63it/s]

Processing tickers:  20%|█▉        | 1368/6855 [04:53<19:32,  4.68it/s]

Processing tickers:  20%|█▉        | 1369/6855 [04:53<19:29,  4.69it/s]

Processing tickers:  20%|█▉        | 1370/6855 [04:54<19:21,  4.72it/s]

Processing tickers:  20%|██        | 1371/6855 [04:54<19:17,  4.74it/s]

Processing tickers:  20%|██        | 1372/6855 [04:54<19:11,  4.76it/s]

Processing tickers:  20%|██        | 1373/6855 [04:54<19:14,  4.75it/s]

Processing tickers:  20%|██        | 1374/6855 [04:54<19:19,  4.73it/s]

Processing tickers:  20%|██        | 1375/6855 [04:55<19:18,  4.73it/s]

Processing tickers:  20%|██        | 1376/6855 [04:55<19:16,  4.74it/s]

Processing tickers:  20%|██        | 1377/6855 [04:55<19:18,  4.73it/s]

Processing tickers:  20%|██        | 1378/6855 [04:55<19:09,  4.77it/s]

Processing tickers:  20%|██        | 1379/6855 [04:55<19:21,  4.71it/s]

Processing tickers:  20%|██        | 1380/6855 [04:56<19:16,  4.74it/s]

Processing tickers:  20%|██        | 1381/6855 [04:56<19:40,  4.64it/s]

Processing tickers:  20%|██        | 1382/6855 [04:56<19:19,  4.72it/s]

Processing tickers:  20%|██        | 1383/6855 [04:56<19:15,  4.74it/s]

Processing tickers:  20%|██        | 1384/6855 [04:57<19:05,  4.78it/s]

Processing tickers:  20%|██        | 1385/6855 [04:57<19:04,  4.78it/s]

Processing tickers:  20%|██        | 1386/6855 [04:57<19:47,  4.61it/s]

Processing tickers:  20%|██        | 1387/6855 [04:57<19:57,  4.57it/s]

Processing tickers:  20%|██        | 1388/6855 [04:57<19:39,  4.64it/s]

Processing tickers:  20%|██        | 1389/6855 [04:58<19:50,  4.59it/s]

Processing tickers:  20%|██        | 1390/6855 [04:58<19:39,  4.63it/s]

Processing tickers:  20%|██        | 1391/6855 [04:58<19:36,  4.64it/s]

Processing tickers:  20%|██        | 1392/6855 [04:58<19:33,  4.65it/s]

Processing tickers:  20%|██        | 1393/6855 [04:58<20:07,  4.52it/s]

Processing tickers:  20%|██        | 1394/6855 [04:59<19:57,  4.56it/s]

Processing tickers:  20%|██        | 1395/6855 [04:59<19:37,  4.64it/s]

Processing tickers:  20%|██        | 1396/6855 [04:59<20:13,  4.50it/s]

Processing tickers:  20%|██        | 1397/6855 [04:59<20:20,  4.47it/s]

Processing tickers:  20%|██        | 1398/6855 [05:00<19:49,  4.59it/s]

Processing tickers:  20%|██        | 1399/6855 [05:00<21:10,  4.29it/s]

Processing tickers:  20%|██        | 1400/6855 [05:00<20:37,  4.41it/s]

Processing tickers:  20%|██        | 1401/6855 [05:00<20:05,  4.52it/s]

Processing tickers:  20%|██        | 1402/6855 [05:00<19:40,  4.62it/s]

Processing tickers:  20%|██        | 1403/6855 [05:01<19:44,  4.60it/s]

Processing tickers:  20%|██        | 1404/6855 [05:01<19:24,  4.68it/s]

Processing tickers:  20%|██        | 1405/6855 [05:01<19:43,  4.60it/s]

Processing tickers:  21%|██        | 1406/6855 [05:01<19:25,  4.68it/s]

Processing tickers:  21%|██        | 1407/6855 [05:02<19:24,  4.68it/s]

Processing tickers:  21%|██        | 1408/6855 [05:02<19:15,  4.71it/s]

Processing tickers:  21%|██        | 1409/6855 [05:02<19:07,  4.74it/s]

Processing tickers:  21%|██        | 1410/6855 [05:02<19:06,  4.75it/s]

Processing tickers:  21%|██        | 1411/6855 [05:02<19:07,  4.75it/s]

Processing tickers:  21%|██        | 1412/6855 [05:03<19:11,  4.73it/s]

Processing tickers:  21%|██        | 1413/6855 [05:03<19:08,  4.74it/s]

Processing tickers:  21%|██        | 1414/6855 [05:03<18:59,  4.78it/s]

Processing tickers:  21%|██        | 1415/6855 [05:03<19:01,  4.77it/s]

Processing tickers:  21%|██        | 1416/6855 [05:03<19:31,  4.64it/s]

Processing tickers:  21%|██        | 1417/6855 [05:04<19:30,  4.64it/s]

Processing tickers:  21%|██        | 1418/6855 [05:04<19:16,  4.70it/s]

Processing tickers:  21%|██        | 1419/6855 [05:04<19:27,  4.66it/s]

Processing tickers:  21%|██        | 1420/6855 [05:04<19:13,  4.71it/s]

Processing tickers:  21%|██        | 1421/6855 [05:05<19:39,  4.61it/s]

Processing tickers:  21%|██        | 1422/6855 [05:05<19:22,  4.67it/s]

Processing tickers:  21%|██        | 1423/6855 [05:05<19:07,  4.73it/s]

Processing tickers:  21%|██        | 1424/6855 [05:05<19:17,  4.69it/s]

Processing tickers:  21%|██        | 1425/6855 [05:05<19:53,  4.55it/s]

Processing tickers:  21%|██        | 1426/6855 [05:06<20:11,  4.48it/s]

Processing tickers:  21%|██        | 1427/6855 [05:06<20:43,  4.36it/s]

Processing tickers:  21%|██        | 1428/6855 [05:06<20:42,  4.37it/s]

Processing tickers:  21%|██        | 1429/6855 [05:06<20:22,  4.44it/s]

Processing tickers:  21%|██        | 1430/6855 [05:07<20:04,  4.50it/s]

Processing tickers:  21%|██        | 1431/6855 [05:07<19:42,  4.59it/s]

Processing tickers:  21%|██        | 1432/6855 [05:07<19:31,  4.63it/s]

Processing tickers:  21%|██        | 1433/6855 [05:07<19:14,  4.69it/s]

Processing tickers:  21%|██        | 1434/6855 [05:07<19:28,  4.64it/s]

Processing tickers:  21%|██        | 1435/6855 [05:08<19:22,  4.66it/s]

Processing tickers:  21%|██        | 1436/6855 [05:08<19:21,  4.67it/s]

Processing tickers:  21%|██        | 1437/6855 [05:08<19:16,  4.69it/s]

Processing tickers:  21%|██        | 1438/6855 [05:08<19:06,  4.72it/s]

Processing tickers:  21%|██        | 1439/6855 [05:08<19:03,  4.73it/s]

Processing tickers:  21%|██        | 1440/6855 [05:09<19:04,  4.73it/s]

Processing tickers:  21%|██        | 1441/6855 [05:09<18:56,  4.76it/s]

Processing tickers:  21%|██        | 1442/6855 [05:09<18:45,  4.81it/s]

Processing tickers:  21%|██        | 1443/6855 [05:09<18:49,  4.79it/s]

Processing tickers:  21%|██        | 1444/6855 [05:09<18:51,  4.78it/s]

Processing tickers:  21%|██        | 1445/6855 [05:10<18:42,  4.82it/s]

Processing tickers:  21%|██        | 1446/6855 [05:10<18:42,  4.82it/s]

Processing tickers:  21%|██        | 1447/6855 [05:10<18:46,  4.80it/s]

Processing tickers:  21%|██        | 1448/6855 [05:10<18:51,  4.78it/s]

Processing tickers:  21%|██        | 1449/6855 [05:11<18:55,  4.76it/s]

Processing tickers:  21%|██        | 1450/6855 [05:11<19:33,  4.61it/s]

Processing tickers:  21%|██        | 1451/6855 [05:11<19:29,  4.62it/s]

Processing tickers:  21%|██        | 1452/6855 [05:11<19:55,  4.52it/s]

Processing tickers:  21%|██        | 1453/6855 [05:11<19:34,  4.60it/s]

Processing tickers:  21%|██        | 1454/6855 [05:12<19:30,  4.61it/s]

Processing tickers:  21%|██        | 1455/6855 [05:12<19:56,  4.51it/s]

Processing tickers:  21%|██        | 1456/6855 [05:12<19:31,  4.61it/s]

Processing tickers:  21%|██▏       | 1457/6855 [05:12<19:14,  4.67it/s]

Processing tickers:  21%|██▏       | 1458/6855 [05:12<19:07,  4.70it/s]

Processing tickers:  21%|██▏       | 1459/6855 [05:13<19:03,  4.72it/s]

Processing tickers:  21%|██▏       | 1460/6855 [05:13<19:21,  4.65it/s]

Processing tickers:  21%|██▏       | 1461/6855 [05:13<19:18,  4.66it/s]

Processing tickers:  21%|██▏       | 1462/6855 [05:13<19:06,  4.70it/s]

Processing tickers:  21%|██▏       | 1463/6855 [05:14<19:02,  4.72it/s]

Processing tickers:  21%|██▏       | 1464/6855 [05:14<18:56,  4.74it/s]

Processing tickers:  21%|██▏       | 1465/6855 [05:14<18:46,  4.78it/s]

Processing tickers:  21%|██▏       | 1466/6855 [05:14<18:55,  4.75it/s]

Processing tickers:  21%|██▏       | 1467/6855 [05:14<18:49,  4.77it/s]

Processing tickers:  21%|██▏       | 1468/6855 [05:15<18:45,  4.78it/s]

Processing tickers:  21%|██▏       | 1469/6855 [05:15<18:45,  4.78it/s]

Processing tickers:  21%|██▏       | 1470/6855 [05:15<18:44,  4.79it/s]

Processing tickers:  21%|██▏       | 1471/6855 [05:15<19:00,  4.72it/s]

Processing tickers:  21%|██▏       | 1472/6855 [05:15<18:52,  4.75it/s]

Processing tickers:  21%|██▏       | 1473/6855 [05:16<18:44,  4.79it/s]

Processing tickers:  22%|██▏       | 1474/6855 [05:16<18:50,  4.76it/s]

Processing tickers:  22%|██▏       | 1475/6855 [05:16<19:04,  4.70it/s]

Processing tickers:  22%|██▏       | 1476/6855 [05:16<19:35,  4.58it/s]

Processing tickers:  22%|██▏       | 1477/6855 [05:17<19:14,  4.66it/s]

Processing tickers:  22%|██▏       | 1478/6855 [05:17<19:09,  4.68it/s]

Processing tickers:  22%|██▏       | 1479/6855 [05:17<19:36,  4.57it/s]

Processing tickers:  22%|██▏       | 1480/6855 [05:17<19:22,  4.62it/s]

Processing tickers:  22%|██▏       | 1481/6855 [05:17<19:11,  4.67it/s]

Processing tickers:  22%|██▏       | 1482/6855 [05:18<19:14,  4.65it/s]

Processing tickers:  22%|██▏       | 1483/6855 [05:18<19:04,  4.70it/s]

Processing tickers:  22%|██▏       | 1484/6855 [05:18<18:53,  4.74it/s]

Processing tickers:  22%|██▏       | 1485/6855 [05:18<19:15,  4.65it/s]

Processing tickers:  22%|██▏       | 1486/6855 [05:18<19:01,  4.70it/s]

Processing tickers:  22%|██▏       | 1487/6855 [05:19<19:01,  4.70it/s]

Processing tickers:  22%|██▏       | 1488/6855 [05:19<18:49,  4.75it/s]

Processing tickers:  22%|██▏       | 1489/6855 [05:19<18:54,  4.73it/s]

Processing tickers:  22%|██▏       | 1490/6855 [05:19<18:50,  4.74it/s]

Processing tickers:  22%|██▏       | 1491/6855 [05:19<18:45,  4.77it/s]

Processing tickers:  22%|██▏       | 1492/6855 [05:20<18:38,  4.79it/s]

Processing tickers:  22%|██▏       | 1493/6855 [05:20<18:43,  4.77it/s]

Processing tickers:  22%|██▏       | 1494/6855 [05:20<18:46,  4.76it/s]

Processing tickers:  22%|██▏       | 1495/6855 [05:20<18:51,  4.74it/s]

Processing tickers:  22%|██▏       | 1496/6855 [05:21<18:53,  4.73it/s]

Processing tickers:  22%|██▏       | 1497/6855 [05:21<18:58,  4.71it/s]

Processing tickers:  22%|██▏       | 1498/6855 [05:21<18:59,  4.70it/s]

Processing tickers:  22%|██▏       | 1499/6855 [05:21<19:46,  4.51it/s]

Processing tickers:  22%|██▏       | 1500/6855 [05:21<19:19,  4.62it/s]

Processing tickers:  22%|██▏       | 1501/6855 [05:22<19:03,  4.68it/s]

Processing tickers:  22%|██▏       | 1502/6855 [05:22<18:55,  4.72it/s]

Processing tickers:  22%|██▏       | 1503/6855 [05:22<19:24,  4.60it/s]

Processing tickers:  22%|██▏       | 1504/6855 [05:22<19:16,  4.63it/s]

Processing tickers:  22%|██▏       | 1505/6855 [05:22<19:08,  4.66it/s]

Processing tickers:  22%|██▏       | 1506/6855 [05:23<18:58,  4.70it/s]

Processing tickers:  22%|██▏       | 1507/6855 [05:23<19:00,  4.69it/s]

Processing tickers:  22%|██▏       | 1508/6855 [05:23<18:46,  4.75it/s]

Processing tickers:  22%|██▏       | 1509/6855 [05:23<18:49,  4.74it/s]

Processing tickers:  22%|██▏       | 1510/6855 [05:24<18:44,  4.75it/s]

Processing tickers:  22%|██▏       | 1511/6855 [05:24<18:40,  4.77it/s]

Processing tickers:  22%|██▏       | 1512/6855 [05:24<18:56,  4.70it/s]

Processing tickers:  22%|██▏       | 1513/6855 [05:24<18:58,  4.69it/s]

Processing tickers:  22%|██▏       | 1514/6855 [05:24<18:48,  4.73it/s]

Processing tickers:  22%|██▏       | 1515/6855 [05:25<19:57,  4.46it/s]

Processing tickers:  22%|██▏       | 1516/6855 [05:25<19:45,  4.50it/s]

Processing tickers:  22%|██▏       | 1517/6855 [05:25<19:19,  4.60it/s]

Processing tickers:  22%|██▏       | 1518/6855 [05:25<19:08,  4.65it/s]

Processing tickers:  22%|██▏       | 1519/6855 [05:25<19:31,  4.55it/s]

Processing tickers:  22%|██▏       | 1520/6855 [05:26<19:48,  4.49it/s]

Processing tickers:  22%|██▏       | 1521/6855 [05:26<19:27,  4.57it/s]

Processing tickers:  22%|██▏       | 1522/6855 [05:26<19:33,  4.54it/s]

Processing tickers:  22%|██▏       | 1523/6855 [05:26<19:16,  4.61it/s]

Processing tickers:  22%|██▏       | 1524/6855 [05:27<19:33,  4.54it/s]

Processing tickers:  22%|██▏       | 1525/6855 [05:27<19:40,  4.52it/s]

Processing tickers:  22%|██▏       | 1526/6855 [05:27<19:24,  4.58it/s]

Processing tickers:  22%|██▏       | 1527/6855 [05:27<19:30,  4.55it/s]

Processing tickers:  22%|██▏       | 1528/6855 [05:27<19:14,  4.62it/s]

Processing tickers:  22%|██▏       | 1529/6855 [05:28<18:55,  4.69it/s]

Processing tickers:  22%|██▏       | 1530/6855 [05:28<19:09,  4.63it/s]

Processing tickers:  22%|██▏       | 1531/6855 [05:28<19:40,  4.51it/s]

Processing tickers:  22%|██▏       | 1532/6855 [05:28<19:15,  4.61it/s]

Processing tickers:  22%|██▏       | 1533/6855 [05:29<19:49,  4.47it/s]

Processing tickers:  22%|██▏       | 1534/6855 [05:29<19:24,  4.57it/s]

Processing tickers:  22%|██▏       | 1535/6855 [05:29<18:56,  4.68it/s]

Processing tickers:  22%|██▏       | 1536/6855 [05:29<19:24,  4.57it/s]

Processing tickers:  22%|██▏       | 1537/6855 [05:29<19:58,  4.44it/s]

Processing tickers:  22%|██▏       | 1538/6855 [05:30<19:38,  4.51it/s]

Processing tickers:  22%|██▏       | 1539/6855 [05:30<19:22,  4.57it/s]

Processing tickers:  22%|██▏       | 1540/6855 [05:30<19:11,  4.62it/s]

Processing tickers:  22%|██▏       | 1541/6855 [05:30<18:58,  4.67it/s]

Processing tickers:  22%|██▏       | 1542/6855 [05:31<19:17,  4.59it/s]

Processing tickers:  23%|██▎       | 1543/6855 [05:31<19:09,  4.62it/s]

Processing tickers:  23%|██▎       | 1544/6855 [05:31<18:52,  4.69it/s]

Processing tickers:  23%|██▎       | 1545/6855 [05:31<18:49,  4.70it/s]

Processing tickers:  23%|██▎       | 1546/6855 [05:31<19:29,  4.54it/s]

Processing tickers:  23%|██▎       | 1547/6855 [05:32<19:32,  4.53it/s]

Processing tickers:  23%|██▎       | 1548/6855 [05:32<19:47,  4.47it/s]

Processing tickers:  23%|██▎       | 1549/6855 [05:32<19:27,  4.54it/s]

Processing tickers:  23%|██▎       | 1550/6855 [05:32<19:34,  4.52it/s]

Processing tickers:  23%|██▎       | 1551/6855 [05:32<19:17,  4.58it/s]

Processing tickers:  23%|██▎       | 1552/6855 [05:33<19:09,  4.61it/s]

Processing tickers:  23%|██▎       | 1553/6855 [05:33<19:01,  4.65it/s]

Processing tickers:  23%|██▎       | 1554/6855 [05:33<18:49,  4.69it/s]

Processing tickers:  23%|██▎       | 1555/6855 [05:33<19:07,  4.62it/s]

Processing tickers:  23%|██▎       | 1556/6855 [05:34<18:53,  4.68it/s]

Processing tickers:  23%|██▎       | 1557/6855 [05:34<18:50,  4.68it/s]

Processing tickers:  23%|██▎       | 1558/6855 [05:34<18:51,  4.68it/s]

Processing tickers:  23%|██▎       | 1559/6855 [05:34<19:02,  4.63it/s]

Processing tickers:  23%|██▎       | 1560/6855 [05:34<18:45,  4.70it/s]

Processing tickers:  23%|██▎       | 1561/6855 [05:35<19:04,  4.63it/s]

Processing tickers:  23%|██▎       | 1562/6855 [05:35<18:52,  4.67it/s]

Processing tickers:  23%|██▎       | 1563/6855 [05:35<19:04,  4.62it/s]

Processing tickers:  23%|██▎       | 1564/6855 [05:35<18:46,  4.70it/s]

Processing tickers:  23%|██▎       | 1565/6855 [05:35<19:17,  4.57it/s]

Processing tickers:  23%|██▎       | 1566/6855 [05:36<19:05,  4.62it/s]

Processing tickers:  23%|██▎       | 1567/6855 [05:36<18:55,  4.66it/s]

Processing tickers:  23%|██▎       | 1568/6855 [05:36<18:45,  4.70it/s]

Processing tickers:  23%|██▎       | 1569/6855 [05:36<18:32,  4.75it/s]

Processing tickers:  23%|██▎       | 1570/6855 [05:37<18:41,  4.71it/s]

Processing tickers:  23%|██▎       | 1571/6855 [05:37<19:18,  4.56it/s]

Processing tickers:  23%|██▎       | 1572/6855 [05:37<19:00,  4.63it/s]

Processing tickers:  23%|██▎       | 1573/6855 [05:37<19:23,  4.54it/s]

Processing tickers:  23%|██▎       | 1574/6855 [05:37<19:42,  4.47it/s]

Processing tickers:  23%|██▎       | 1575/6855 [05:38<19:20,  4.55it/s]

Processing tickers:  23%|██▎       | 1576/6855 [05:38<19:28,  4.52it/s]

Processing tickers:  23%|██▎       | 1577/6855 [05:38<19:53,  4.42it/s]

Processing tickers:  23%|██▎       | 1578/6855 [05:38<19:36,  4.49it/s]

Processing tickers:  23%|██▎       | 1579/6855 [05:39<19:27,  4.52it/s]

Processing tickers:  23%|██▎       | 1580/6855 [05:39<19:20,  4.55it/s]

Processing tickers:  23%|██▎       | 1581/6855 [05:39<19:51,  4.43it/s]

Processing tickers:  23%|██▎       | 1582/6855 [05:39<19:21,  4.54it/s]

Processing tickers:  23%|██▎       | 1583/6855 [05:39<19:46,  4.44it/s]

Processing tickers:  23%|██▎       | 1584/6855 [05:40<19:33,  4.49it/s]

Processing tickers:  23%|██▎       | 1585/6855 [05:40<19:26,  4.52it/s]

Processing tickers:  23%|██▎       | 1586/6855 [05:40<19:10,  4.58it/s]

Processing tickers:  23%|██▎       | 1587/6855 [05:40<18:49,  4.66it/s]

Processing tickers:  23%|██▎       | 1588/6855 [05:41<18:38,  4.71it/s]

Processing tickers:  23%|██▎       | 1589/6855 [05:41<18:26,  4.76it/s]

Processing tickers:  23%|██▎       | 1590/6855 [05:41<18:22,  4.77it/s]

Processing tickers:  23%|██▎       | 1591/6855 [05:41<18:36,  4.71it/s]

Processing tickers:  23%|██▎       | 1592/6855 [05:41<19:05,  4.60it/s]

Processing tickers:  23%|██▎       | 1593/6855 [05:42<18:44,  4.68it/s]

Processing tickers:  23%|██▎       | 1594/6855 [05:42<18:39,  4.70it/s]

Processing tickers:  23%|██▎       | 1595/6855 [05:42<18:54,  4.64it/s]

Processing tickers:  23%|██▎       | 1596/6855 [05:42<18:48,  4.66it/s]

Processing tickers:  23%|██▎       | 1597/6855 [05:42<18:55,  4.63it/s]

Processing tickers:  23%|██▎       | 1598/6855 [05:43<18:57,  4.62it/s]

Processing tickers:  23%|██▎       | 1599/6855 [05:43<18:38,  4.70it/s]

Processing tickers:  23%|██▎       | 1600/6855 [05:43<18:40,  4.69it/s]

Processing tickers:  23%|██▎       | 1601/6855 [05:43<18:37,  4.70it/s]

Processing tickers:  23%|██▎       | 1602/6855 [05:44<18:30,  4.73it/s]

Processing tickers:  23%|██▎       | 1603/6855 [05:44<18:31,  4.72it/s]

Processing tickers:  23%|██▎       | 1604/6855 [05:44<18:31,  4.72it/s]

Processing tickers:  23%|██▎       | 1605/6855 [05:44<18:26,  4.75it/s]

Processing tickers:  23%|██▎       | 1606/6855 [05:44<18:40,  4.68it/s]

Processing tickers:  23%|██▎       | 1607/6855 [05:45<18:48,  4.65it/s]

Processing tickers:  23%|██▎       | 1608/6855 [05:45<18:52,  4.63it/s]

Processing tickers:  23%|██▎       | 1609/6855 [05:45<18:45,  4.66it/s]

Processing tickers:  23%|██▎       | 1610/6855 [05:45<18:43,  4.67it/s]

Processing tickers:  24%|██▎       | 1611/6855 [05:45<18:39,  4.68it/s]

Processing tickers:  24%|██▎       | 1612/6855 [05:46<18:40,  4.68it/s]

Processing tickers:  24%|██▎       | 1613/6855 [05:46<18:37,  4.69it/s]

Processing tickers:  24%|██▎       | 1614/6855 [05:46<18:25,  4.74it/s]

Processing tickers:  24%|██▎       | 1615/6855 [05:46<18:32,  4.71it/s]

Processing tickers:  24%|██▎       | 1616/6855 [05:46<18:37,  4.69it/s]

Processing tickers:  24%|██▎       | 1617/6855 [05:47<18:37,  4.69it/s]

Processing tickers:  24%|██▎       | 1618/6855 [05:47<18:59,  4.59it/s]

Processing tickers:  24%|██▎       | 1619/6855 [05:47<19:12,  4.54it/s]

Processing tickers:  24%|██▎       | 1620/6855 [05:47<19:26,  4.49it/s]

Processing tickers:  24%|██▎       | 1621/6855 [05:48<19:10,  4.55it/s]

Processing tickers:  24%|██▎       | 1622/6855 [05:48<18:56,  4.61it/s]

Processing tickers:  24%|██▎       | 1623/6855 [05:48<19:10,  4.55it/s]

Processing tickers:  24%|██▎       | 1624/6855 [05:48<19:32,  4.46it/s]

Processing tickers:  24%|██▎       | 1625/6855 [05:48<19:13,  4.54it/s]

Processing tickers:  24%|██▎       | 1626/6855 [05:49<20:18,  4.29it/s]

Processing tickers:  24%|██▎       | 1627/6855 [05:49<19:40,  4.43it/s]

Processing tickers:  24%|██▎       | 1628/6855 [05:49<19:16,  4.52it/s]

Processing tickers:  24%|██▍       | 1629/6855 [05:49<18:57,  4.59it/s]

Processing tickers:  24%|██▍       | 1630/6855 [05:50<19:13,  4.53it/s]

Processing tickers:  24%|██▍       | 1631/6855 [05:50<18:51,  4.62it/s]

Processing tickers:  24%|██▍       | 1632/6855 [05:50<18:58,  4.59it/s]

Processing tickers:  24%|██▍       | 1633/6855 [05:50<18:41,  4.66it/s]

Processing tickers:  24%|██▍       | 1634/6855 [05:50<18:28,  4.71it/s]

Processing tickers:  24%|██▍       | 1635/6855 [05:51<18:23,  4.73it/s]

Processing tickers:  24%|██▍       | 1636/6855 [05:51<18:18,  4.75it/s]

Processing tickers:  24%|██▍       | 1637/6855 [05:51<18:22,  4.73it/s]

Processing tickers:  24%|██▍       | 1638/6855 [05:51<18:20,  4.74it/s]

Processing tickers:  24%|██▍       | 1639/6855 [05:52<18:36,  4.67it/s]

Processing tickers:  24%|██▍       | 1640/6855 [05:52<18:39,  4.66it/s]

Processing tickers:  24%|██▍       | 1641/6855 [05:52<18:31,  4.69it/s]

Processing tickers:  24%|██▍       | 1642/6855 [05:52<18:51,  4.61it/s]

Processing tickers:  24%|██▍       | 1643/6855 [05:52<18:43,  4.64it/s]

Processing tickers:  24%|██▍       | 1644/6855 [05:53<18:35,  4.67it/s]

Processing tickers:  24%|██▍       | 1645/6855 [05:53<18:27,  4.71it/s]

Processing tickers:  24%|██▍       | 1646/6855 [05:53<19:14,  4.51it/s]

Processing tickers:  24%|██▍       | 1647/6855 [05:53<18:56,  4.58it/s]

Processing tickers:  24%|██▍       | 1648/6855 [05:53<18:41,  4.64it/s]

Processing tickers:  24%|██▍       | 1649/6855 [05:54<18:50,  4.61it/s]

Processing tickers:  24%|██▍       | 1650/6855 [05:54<18:49,  4.61it/s]

Processing tickers:  24%|██▍       | 1651/6855 [05:54<18:40,  4.64it/s]

Processing tickers:  24%|██▍       | 1652/6855 [05:54<18:29,  4.69it/s]

Processing tickers:  24%|██▍       | 1653/6855 [05:55<19:09,  4.53it/s]

Processing tickers:  24%|██▍       | 1654/6855 [05:55<18:55,  4.58it/s]

Processing tickers:  24%|██▍       | 1655/6855 [05:55<18:45,  4.62it/s]

Processing tickers:  24%|██▍       | 1656/6855 [05:55<18:48,  4.61it/s]

Processing tickers:  24%|██▍       | 1657/6855 [05:55<18:38,  4.65it/s]

Processing tickers:  24%|██▍       | 1658/6855 [05:56<18:30,  4.68it/s]

Processing tickers:  24%|██▍       | 1659/6855 [05:56<18:24,  4.70it/s]

Processing tickers:  24%|██▍       | 1660/6855 [05:56<18:15,  4.74it/s]

Processing tickers:  24%|██▍       | 1661/6855 [05:56<18:11,  4.76it/s]

Processing tickers:  24%|██▍       | 1662/6855 [05:56<18:15,  4.74it/s]

Processing tickers:  24%|██▍       | 1663/6855 [05:57<18:05,  4.78it/s]

Processing tickers:  24%|██▍       | 1664/6855 [05:57<18:30,  4.68it/s]

Processing tickers:  24%|██▍       | 1665/6855 [05:57<18:32,  4.66it/s]

Processing tickers:  24%|██▍       | 1666/6855 [05:57<19:00,  4.55it/s]

Processing tickers:  24%|██▍       | 1667/6855 [05:58<18:46,  4.61it/s]

Processing tickers:  24%|██▍       | 1668/6855 [05:58<18:52,  4.58it/s]

Processing tickers:  24%|██▍       | 1669/6855 [05:58<19:15,  4.49it/s]

Processing tickers:  24%|██▍       | 1670/6855 [05:58<19:16,  4.48it/s]

Processing tickers:  24%|██▍       | 1671/6855 [05:58<19:22,  4.46it/s]

Processing tickers:  24%|██▍       | 1672/6855 [05:59<19:34,  4.41it/s]

Processing tickers:  24%|██▍       | 1673/6855 [05:59<19:08,  4.51it/s]

Processing tickers:  24%|██▍       | 1674/6855 [05:59<18:46,  4.60it/s]

Processing tickers:  24%|██▍       | 1675/6855 [05:59<18:40,  4.62it/s]

Processing tickers:  24%|██▍       | 1676/6855 [06:00<19:09,  4.51it/s]

Processing tickers:  24%|██▍       | 1677/6855 [06:00<18:48,  4.59it/s]

Processing tickers:  24%|██▍       | 1678/6855 [06:00<18:35,  4.64it/s]

Processing tickers:  24%|██▍       | 1679/6855 [06:00<18:26,  4.68it/s]

Processing tickers:  25%|██▍       | 1680/6855 [06:00<18:51,  4.58it/s]

Processing tickers:  25%|██▍       | 1681/6855 [06:01<18:52,  4.57it/s]

Processing tickers:  25%|██▍       | 1682/6855 [06:01<18:59,  4.54it/s]

Processing tickers:  25%|██▍       | 1683/6855 [06:01<18:48,  4.58it/s]

Processing tickers:  25%|██▍       | 1684/6855 [06:01<18:55,  4.56it/s]

Processing tickers:  25%|██▍       | 1685/6855 [06:02<19:04,  4.52it/s]

Processing tickers:  25%|██▍       | 1686/6855 [06:02<18:54,  4.56it/s]

Processing tickers:  25%|██▍       | 1687/6855 [06:02<18:33,  4.64it/s]

Processing tickers:  25%|██▍       | 1688/6855 [06:02<18:25,  4.68it/s]

Processing tickers:  25%|██▍       | 1689/6855 [06:02<18:46,  4.59it/s]

Processing tickers:  25%|██▍       | 1690/6855 [06:03<19:04,  4.51it/s]

Processing tickers:  25%|██▍       | 1691/6855 [06:03<18:49,  4.57it/s]

Processing tickers:  25%|██▍       | 1692/6855 [06:03<18:31,  4.65it/s]

Processing tickers:  25%|██▍       | 1693/6855 [06:03<18:35,  4.63it/s]

Processing tickers:  25%|██▍       | 1694/6855 [06:03<18:31,  4.64it/s]

Processing tickers:  25%|██▍       | 1695/6855 [06:04<18:29,  4.65it/s]

Processing tickers:  25%|██▍       | 1696/6855 [06:04<18:27,  4.66it/s]

Processing tickers:  25%|██▍       | 1697/6855 [06:04<18:19,  4.69it/s]

Processing tickers:  25%|██▍       | 1698/6855 [06:04<18:19,  4.69it/s]

Processing tickers:  25%|██▍       | 1699/6855 [06:05<18:14,  4.71it/s]

Processing tickers:  25%|██▍       | 1700/6855 [06:05<18:05,  4.75it/s]

Processing tickers:  25%|██▍       | 1701/6855 [06:05<18:14,  4.71it/s]

Processing tickers:  25%|██▍       | 1702/6855 [06:05<18:15,  4.70it/s]

Processing tickers:  25%|██▍       | 1703/6855 [06:05<18:05,  4.75it/s]

Processing tickers:  25%|██▍       | 1704/6855 [06:06<18:03,  4.75it/s]

Processing tickers:  25%|██▍       | 1705/6855 [06:06<18:07,  4.73it/s]

Processing tickers:  25%|██▍       | 1706/6855 [06:06<18:08,  4.73it/s]

Processing tickers:  25%|██▍       | 1707/6855 [06:06<18:10,  4.72it/s]

Processing tickers:  25%|██▍       | 1708/6855 [06:06<18:02,  4.75it/s]

Processing tickers:  25%|██▍       | 1709/6855 [06:07<17:57,  4.78it/s]

Processing tickers:  25%|██▍       | 1710/6855 [06:07<18:18,  4.68it/s]

Processing tickers:  25%|██▍       | 1711/6855 [06:07<18:23,  4.66it/s]

Processing tickers:  25%|██▍       | 1712/6855 [06:07<18:14,  4.70it/s]

Processing tickers:  25%|██▍       | 1713/6855 [06:07<18:32,  4.62it/s]

Processing tickers:  25%|██▌       | 1714/6855 [06:08<18:24,  4.65it/s]

Processing tickers:  25%|██▌       | 1715/6855 [06:08<18:26,  4.64it/s]

Processing tickers:  25%|██▌       | 1716/6855 [06:08<18:20,  4.67it/s]

Processing tickers:  25%|██▌       | 1717/6855 [06:08<18:08,  4.72it/s]

Processing tickers:  25%|██▌       | 1718/6855 [06:09<18:09,  4.71it/s]

Processing tickers:  25%|██▌       | 1719/6855 [06:09<18:40,  4.58it/s]

Processing tickers:  25%|██▌       | 1720/6855 [06:09<18:28,  4.63it/s]

Processing tickers:  25%|██▌       | 1721/6855 [06:09<18:56,  4.52it/s]

Processing tickers:  25%|██▌       | 1722/6855 [06:09<18:45,  4.56it/s]

Processing tickers:  25%|██▌       | 1723/6855 [06:10<18:54,  4.53it/s]

Processing tickers:  25%|██▌       | 1724/6855 [06:10<18:39,  4.58it/s]

Processing tickers:  25%|██▌       | 1725/6855 [06:10<18:19,  4.67it/s]

Processing tickers:  25%|██▌       | 1726/6855 [06:10<18:14,  4.69it/s]

Processing tickers:  25%|██▌       | 1727/6855 [06:11<18:15,  4.68it/s]

Processing tickers:  25%|██▌       | 1728/6855 [06:11<18:04,  4.73it/s]

Processing tickers:  25%|██▌       | 1729/6855 [06:11<18:03,  4.73it/s]

Processing tickers:  25%|██▌       | 1730/6855 [06:11<18:00,  4.74it/s]

Processing tickers:  25%|██▌       | 1731/6855 [06:11<17:54,  4.77it/s]

Processing tickers:  25%|██▌       | 1732/6855 [06:12<17:49,  4.79it/s]

Processing tickers:  25%|██▌       | 1733/6855 [06:12<18:18,  4.66it/s]

Processing tickers:  25%|██▌       | 1734/6855 [06:12<18:13,  4.68it/s]

Processing tickers:  25%|██▌       | 1735/6855 [06:12<18:35,  4.59it/s]

Processing tickers:  25%|██▌       | 1736/6855 [06:12<18:17,  4.66it/s]

Processing tickers:  25%|██▌       | 1737/6855 [06:13<18:04,  4.72it/s]

Processing tickers:  25%|██▌       | 1738/6855 [06:13<18:19,  4.65it/s]

Processing tickers:  25%|██▌       | 1739/6855 [06:13<18:13,  4.68it/s]

Processing tickers:  25%|██▌       | 1740/6855 [06:13<18:08,  4.70it/s]

Processing tickers:  25%|██▌       | 1741/6855 [06:13<18:27,  4.62it/s]

Processing tickers:  25%|██▌       | 1742/6855 [06:14<18:13,  4.68it/s]

Processing tickers:  25%|██▌       | 1743/6855 [06:14<18:09,  4.69it/s]

Processing tickers:  25%|██▌       | 1744/6855 [06:14<18:07,  4.70it/s]

Processing tickers:  25%|██▌       | 1745/6855 [06:14<18:03,  4.71it/s]

Processing tickers:  25%|██▌       | 1746/6855 [06:15<18:06,  4.70it/s]

Processing tickers:  25%|██▌       | 1747/6855 [06:15<18:03,  4.72it/s]

Processing tickers:  25%|██▌       | 1748/6855 [06:15<18:15,  4.66it/s]

Processing tickers:  26%|██▌       | 1749/6855 [06:15<18:39,  4.56it/s]

Processing tickers:  26%|██▌       | 1750/6855 [06:15<18:29,  4.60it/s]

Processing tickers:  26%|██▌       | 1751/6855 [06:16<18:15,  4.66it/s]

Processing tickers:  26%|██▌       | 1752/6855 [06:16<18:31,  4.59it/s]

Processing tickers:  26%|██▌       | 1753/6855 [06:16<18:20,  4.64it/s]

Processing tickers:  26%|██▌       | 1754/6855 [06:16<18:10,  4.68it/s]

Processing tickers:  26%|██▌       | 1755/6855 [06:16<18:08,  4.69it/s]

Processing tickers:  26%|██▌       | 1756/6855 [06:17<18:07,  4.69it/s]

Processing tickers:  26%|██▌       | 1757/6855 [06:17<17:58,  4.73it/s]

Processing tickers:  26%|██▌       | 1758/6855 [06:17<17:57,  4.73it/s]

Processing tickers:  26%|██▌       | 1759/6855 [06:17<17:57,  4.73it/s]

Processing tickers:  26%|██▌       | 1760/6855 [06:18<17:59,  4.72it/s]

Processing tickers:  26%|██▌       | 1761/6855 [06:18<17:51,  4.75it/s]

Processing tickers:  26%|██▌       | 1762/6855 [06:18<17:45,  4.78it/s]

Processing tickers:  26%|██▌       | 1763/6855 [06:18<18:31,  4.58it/s]

Processing tickers:  26%|██▌       | 1764/6855 [06:18<18:37,  4.56it/s]

Processing tickers:  26%|██▌       | 1765/6855 [06:19<19:15,  4.40it/s]

Processing tickers:  26%|██▌       | 1766/6855 [06:19<18:51,  4.50it/s]

Processing tickers:  26%|██▌       | 1767/6855 [06:19<18:28,  4.59it/s]

Processing tickers:  26%|██▌       | 1768/6855 [06:19<18:34,  4.56it/s]

Processing tickers:  26%|██▌       | 1769/6855 [06:20<18:19,  4.62it/s]

Processing tickers:  26%|██▌       | 1770/6855 [06:20<18:05,  4.69it/s]

Processing tickers:  26%|██▌       | 1771/6855 [06:20<18:08,  4.67it/s]

Processing tickers:  26%|██▌       | 1772/6855 [06:20<18:07,  4.67it/s]

Processing tickers:  26%|██▌       | 1773/6855 [06:20<18:02,  4.70it/s]

Processing tickers:  26%|██▌       | 1774/6855 [06:21<17:56,  4.72it/s]

Processing tickers:  26%|██▌       | 1775/6855 [06:21<18:12,  4.65it/s]

Processing tickers:  26%|██▌       | 1776/6855 [06:21<18:02,  4.69it/s]

Processing tickers:  26%|██▌       | 1777/6855 [06:21<18:15,  4.63it/s]

Processing tickers:  26%|██▌       | 1778/6855 [06:21<18:05,  4.68it/s]

Processing tickers:  26%|██▌       | 1779/6855 [06:22<17:50,  4.74it/s]

Processing tickers:  26%|██▌       | 1780/6855 [06:22<18:12,  4.65it/s]

Processing tickers:  26%|██▌       | 1781/6855 [06:22<17:53,  4.73it/s]

Processing tickers:  26%|██▌       | 1782/6855 [06:22<18:06,  4.67it/s]

Processing tickers:  26%|██▌       | 1783/6855 [06:23<18:05,  4.67it/s]

Processing tickers:  26%|██▌       | 1784/6855 [06:23<17:58,  4.70it/s]

Processing tickers:  26%|██▌       | 1785/6855 [06:23<17:42,  4.77it/s]

Processing tickers:  26%|██▌       | 1786/6855 [06:23<17:35,  4.80it/s]

Processing tickers:  26%|██▌       | 1787/6855 [06:23<17:57,  4.70it/s]

Processing tickers:  26%|██▌       | 1788/6855 [06:24<17:47,  4.75it/s]

Processing tickers:  26%|██▌       | 1789/6855 [06:24<17:42,  4.77it/s]

Processing tickers:  26%|██▌       | 1790/6855 [06:24<17:40,  4.78it/s]

Processing tickers:  26%|██▌       | 1791/6855 [06:24<17:29,  4.82it/s]

Processing tickers:  26%|██▌       | 1792/6855 [06:24<17:24,  4.85it/s]

Processing tickers:  26%|██▌       | 1793/6855 [06:25<17:33,  4.80it/s]

Processing tickers:  26%|██▌       | 1794/6855 [06:25<17:24,  4.84it/s]

Processing tickers:  26%|██▌       | 1795/6855 [06:25<17:25,  4.84it/s]

Processing tickers:  26%|██▌       | 1796/6855 [06:25<17:52,  4.72it/s]

Processing tickers:  26%|██▌       | 1797/6855 [06:25<17:47,  4.74it/s]

Processing tickers:  26%|██▌       | 1798/6855 [06:26<17:43,  4.75it/s]

Processing tickers:  26%|██▌       | 1799/6855 [06:26<17:37,  4.78it/s]

Processing tickers:  26%|██▋       | 1800/6855 [06:26<17:59,  4.68it/s]

Processing tickers:  26%|██▋       | 1801/6855 [06:26<17:58,  4.69it/s]

Processing tickers:  26%|██▋       | 1802/6855 [06:26<17:51,  4.72it/s]

Processing tickers:  26%|██▋       | 1803/6855 [06:27<17:44,  4.75it/s]

Processing tickers:  26%|██▋       | 1804/6855 [06:27<18:04,  4.66it/s]

Processing tickers:  26%|██▋       | 1805/6855 [06:27<17:53,  4.70it/s]

Processing tickers:  26%|██▋       | 1806/6855 [06:27<18:30,  4.55it/s]

Processing tickers:  26%|██▋       | 1807/6855 [06:28<18:08,  4.64it/s]

Processing tickers:  26%|██▋       | 1808/6855 [06:28<17:52,  4.70it/s]

Processing tickers:  26%|██▋       | 1809/6855 [06:28<17:46,  4.73it/s]

Processing tickers:  26%|██▋       | 1810/6855 [06:28<17:59,  4.68it/s]

Processing tickers:  26%|██▋       | 1811/6855 [06:28<17:48,  4.72it/s]

Processing tickers:  26%|██▋       | 1812/6855 [06:29<18:10,  4.63it/s]

Processing tickers:  26%|██▋       | 1813/6855 [06:29<18:14,  4.61it/s]

Processing tickers:  26%|██▋       | 1814/6855 [06:29<18:30,  4.54it/s]

Processing tickers:  26%|██▋       | 1815/6855 [06:29<18:31,  4.53it/s]

Processing tickers:  26%|██▋       | 1816/6855 [06:30<18:45,  4.48it/s]

Processing tickers:  27%|██▋       | 1817/6855 [06:30<18:51,  4.45it/s]

Processing tickers:  27%|██▋       | 1818/6855 [06:30<18:23,  4.57it/s]

Processing tickers:  27%|██▋       | 1819/6855 [06:30<18:11,  4.61it/s]

Processing tickers:  27%|██▋       | 1820/6855 [06:30<18:01,  4.66it/s]

Processing tickers:  27%|██▋       | 1821/6855 [06:31<17:56,  4.68it/s]

Processing tickers:  27%|██▋       | 1822/6855 [06:31<17:49,  4.70it/s]

Processing tickers:  27%|██▋       | 1823/6855 [06:31<17:38,  4.75it/s]

Processing tickers:  27%|██▋       | 1824/6855 [06:31<17:43,  4.73it/s]

Processing tickers:  27%|██▋       | 1825/6855 [06:31<17:37,  4.76it/s]

Processing tickers:  27%|██▋       | 1826/6855 [06:32<17:33,  4.77it/s]

Processing tickers:  27%|██▋       | 1827/6855 [06:32<17:38,  4.75it/s]

Processing tickers:  27%|██▋       | 1828/6855 [06:32<17:38,  4.75it/s]

Processing tickers:  27%|██▋       | 1829/6855 [06:32<17:57,  4.66it/s]

Processing tickers:  27%|██▋       | 1830/6855 [06:33<18:06,  4.62it/s]

Processing tickers:  27%|██▋       | 1831/6855 [06:33<18:14,  4.59it/s]

Processing tickers:  27%|██▋       | 1832/6855 [06:33<18:12,  4.60it/s]

Processing tickers:  27%|██▋       | 1833/6855 [06:33<18:02,  4.64it/s]

Processing tickers:  27%|██▋       | 1834/6855 [06:33<17:53,  4.68it/s]

Processing tickers:  27%|██▋       | 1835/6855 [06:34<17:40,  4.73it/s]

Processing tickers:  27%|██▋       | 1836/6855 [06:34<17:54,  4.67it/s]

Processing tickers:  27%|██▋       | 1837/6855 [06:34<17:50,  4.69it/s]

Processing tickers:  27%|██▋       | 1838/6855 [06:34<18:05,  4.62it/s]

Processing tickers:  27%|██▋       | 1839/6855 [06:34<17:58,  4.65it/s]

Processing tickers:  27%|██▋       | 1840/6855 [06:35<17:46,  4.70it/s]

Processing tickers:  27%|██▋       | 1841/6855 [06:35<17:42,  4.72it/s]

Processing tickers:  27%|██▋       | 1842/6855 [06:35<17:38,  4.74it/s]

Processing tickers:  27%|██▋       | 1843/6855 [06:35<17:38,  4.73it/s]

Processing tickers:  27%|██▋       | 1844/6855 [06:35<17:34,  4.75it/s]

Processing tickers:  27%|██▋       | 1845/6855 [06:36<17:32,  4.76it/s]

Processing tickers:  27%|██▋       | 1846/6855 [06:36<17:33,  4.75it/s]

Processing tickers:  27%|██▋       | 1847/6855 [06:36<17:30,  4.77it/s]

Processing tickers:  27%|██▋       | 1848/6855 [06:36<17:39,  4.72it/s]

Processing tickers:  27%|██▋       | 1849/6855 [06:37<17:43,  4.71it/s]

Processing tickers:  27%|██▋       | 1850/6855 [06:37<17:34,  4.75it/s]

Processing tickers:  27%|██▋       | 1851/6855 [06:37<18:05,  4.61it/s]

Processing tickers:  27%|██▋       | 1852/6855 [06:37<18:11,  4.59it/s]

Processing tickers:  27%|██▋       | 1853/6855 [06:37<17:58,  4.64it/s]

Processing tickers:  27%|██▋       | 1854/6855 [06:38<17:48,  4.68it/s]

Processing tickers:  27%|██▋       | 1855/6855 [06:38<17:40,  4.72it/s]

Processing tickers:  27%|██▋       | 1856/6855 [06:38<17:48,  4.68it/s]

Processing tickers:  27%|██▋       | 1857/6855 [06:38<17:36,  4.73it/s]

Processing tickers:  27%|██▋       | 1858/6855 [06:38<18:01,  4.62it/s]

Processing tickers:  27%|██▋       | 1859/6855 [06:39<17:56,  4.64it/s]

Processing tickers:  27%|██▋       | 1860/6855 [06:39<17:46,  4.68it/s]

Processing tickers:  27%|██▋       | 1861/6855 [06:39<17:47,  4.68it/s]

Processing tickers:  27%|██▋       | 1862/6855 [06:39<17:43,  4.70it/s]

Processing tickers:  27%|██▋       | 1863/6855 [06:40<17:42,  4.70it/s]

Processing tickers:  27%|██▋       | 1864/6855 [06:40<17:34,  4.74it/s]

Processing tickers:  27%|██▋       | 1865/6855 [06:40<17:46,  4.68it/s]

Processing tickers:  27%|██▋       | 1866/6855 [06:40<17:42,  4.70it/s]

Processing tickers:  27%|██▋       | 1867/6855 [06:40<17:34,  4.73it/s]

Processing tickers:  27%|██▋       | 1868/6855 [06:41<17:36,  4.72it/s]

Processing tickers:  27%|██▋       | 1869/6855 [06:41<17:32,  4.74it/s]

Processing tickers:  27%|██▋       | 1870/6855 [06:41<17:24,  4.77it/s]

Processing tickers:  27%|██▋       | 1871/6855 [06:41<17:27,  4.76it/s]

Processing tickers:  27%|██▋       | 1872/6855 [06:41<17:26,  4.76it/s]

Processing tickers:  27%|██▋       | 1873/6855 [06:42<17:25,  4.76it/s]

Processing tickers:  27%|██▋       | 1874/6855 [06:42<17:31,  4.74it/s]

Processing tickers:  27%|██▋       | 1875/6855 [06:42<17:29,  4.75it/s]

Processing tickers:  27%|██▋       | 1876/6855 [06:42<17:22,  4.78it/s]

Processing tickers:  27%|██▋       | 1877/6855 [06:42<17:18,  4.80it/s]

Processing tickers:  27%|██▋       | 1878/6855 [06:43<17:55,  4.63it/s]

Processing tickers:  27%|██▋       | 1879/6855 [06:43<17:39,  4.69it/s]

Processing tickers:  27%|██▋       | 1880/6855 [06:43<17:32,  4.72it/s]

Processing tickers:  27%|██▋       | 1881/6855 [06:43<17:34,  4.72it/s]

Processing tickers:  27%|██▋       | 1882/6855 [06:44<17:58,  4.61it/s]

Processing tickers:  27%|██▋       | 1883/6855 [06:44<18:16,  4.53it/s]

Processing tickers:  27%|██▋       | 1884/6855 [06:44<17:50,  4.64it/s]

Processing tickers:  27%|██▋       | 1885/6855 [06:44<17:49,  4.65it/s]

Processing tickers:  28%|██▊       | 1886/6855 [06:44<17:48,  4.65it/s]

Processing tickers:  28%|██▊       | 1887/6855 [06:45<17:40,  4.68it/s]

Processing tickers:  28%|██▊       | 1888/6855 [06:45<17:38,  4.69it/s]

Processing tickers:  28%|██▊       | 1889/6855 [06:45<17:27,  4.74it/s]

Processing tickers:  28%|██▊       | 1890/6855 [06:45<17:21,  4.77it/s]

Processing tickers:  28%|██▊       | 1891/6855 [06:45<17:21,  4.77it/s]

Processing tickers:  28%|██▊       | 1892/6855 [06:46<17:44,  4.66it/s]

Processing tickers:  28%|██▊       | 1893/6855 [06:46<17:34,  4.71it/s]

Processing tickers:  28%|██▊       | 1894/6855 [06:46<17:20,  4.77it/s]

Processing tickers:  28%|██▊       | 1895/6855 [06:46<17:21,  4.76it/s]

Processing tickers:  28%|██▊       | 1896/6855 [06:47<17:20,  4.77it/s]

Processing tickers:  28%|██▊       | 1897/6855 [06:47<17:24,  4.75it/s]

Processing tickers:  28%|██▊       | 1898/6855 [06:47<17:31,  4.72it/s]

Processing tickers:  28%|██▊       | 1899/6855 [06:47<17:18,  4.77it/s]

Processing tickers:  28%|██▊       | 1900/6855 [06:47<17:24,  4.75it/s]

Processing tickers:  28%|██▊       | 1901/6855 [06:48<17:52,  4.62it/s]

Processing tickers:  28%|██▊       | 1902/6855 [06:48<17:37,  4.69it/s]

Processing tickers:  28%|██▊       | 1903/6855 [06:48<17:52,  4.62it/s]

Processing tickers:  28%|██▊       | 1904/6855 [06:48<18:16,  4.52it/s]

Processing tickers:  28%|██▊       | 1905/6855 [06:49<18:25,  4.48it/s]

Processing tickers:  28%|██▊       | 1906/6855 [06:49<18:08,  4.55it/s]

Processing tickers:  28%|██▊       | 1907/6855 [06:49<18:46,  4.39it/s]

Processing tickers:  28%|██▊       | 1908/6855 [06:49<18:17,  4.51it/s]

Processing tickers:  28%|██▊       | 1909/6855 [06:49<17:54,  4.60it/s]

Processing tickers:  28%|██▊       | 1910/6855 [06:50<17:53,  4.61it/s]

Processing tickers:  28%|██▊       | 1911/6855 [06:50<17:48,  4.63it/s]

Processing tickers:  28%|██▊       | 1912/6855 [06:50<17:37,  4.67it/s]

Processing tickers:  28%|██▊       | 1913/6855 [06:50<17:32,  4.69it/s]

Processing tickers:  28%|██▊       | 1914/6855 [06:50<17:22,  4.74it/s]

Processing tickers:  28%|██▊       | 1915/6855 [06:51<17:41,  4.65it/s]

Processing tickers:  28%|██▊       | 1916/6855 [06:51<17:37,  4.67it/s]

Processing tickers:  28%|██▊       | 1917/6855 [06:51<17:34,  4.68it/s]

Processing tickers:  28%|██▊       | 1918/6855 [06:51<17:43,  4.64it/s]

Processing tickers:  28%|██▊       | 1919/6855 [06:52<17:38,  4.66it/s]

Processing tickers:  28%|██▊       | 1920/6855 [06:52<17:33,  4.68it/s]

Processing tickers:  28%|██▊       | 1921/6855 [06:52<17:31,  4.69it/s]

Processing tickers:  28%|██▊       | 1922/6855 [06:52<17:26,  4.71it/s]

Processing tickers:  28%|██▊       | 1923/6855 [06:52<17:17,  4.75it/s]

Processing tickers:  28%|██▊       | 1924/6855 [06:53<17:17,  4.75it/s]

Processing tickers:  28%|██▊       | 1925/6855 [06:53<17:14,  4.76it/s]

Processing tickers:  28%|██▊       | 1926/6855 [06:53<17:19,  4.74it/s]

Processing tickers:  28%|██▊       | 1927/6855 [06:53<17:28,  4.70it/s]

Processing tickers:  28%|██▊       | 1928/6855 [06:53<17:19,  4.74it/s]

Processing tickers:  28%|██▊       | 1929/6855 [06:54<17:30,  4.69it/s]

Processing tickers:  28%|██▊       | 1930/6855 [06:54<17:23,  4.72it/s]

Processing tickers:  28%|██▊       | 1931/6855 [06:54<17:29,  4.69it/s]

Processing tickers:  28%|██▊       | 1932/6855 [06:54<17:37,  4.65it/s]

Processing tickers:  28%|██▊       | 1933/6855 [06:54<17:51,  4.60it/s]

Processing tickers:  28%|██▊       | 1934/6855 [06:55<17:40,  4.64it/s]

Processing tickers:  28%|██▊       | 1935/6855 [06:55<17:47,  4.61it/s]

Processing tickers:  28%|██▊       | 1936/6855 [06:55<17:31,  4.68it/s]

Processing tickers:  28%|██▊       | 1937/6855 [06:55<17:28,  4.69it/s]

Processing tickers:  28%|██▊       | 1938/6855 [06:56<17:28,  4.69it/s]

Processing tickers:  28%|██▊       | 1939/6855 [06:56<17:22,  4.71it/s]

Processing tickers:  28%|██▊       | 1940/6855 [06:56<17:50,  4.59it/s]

Processing tickers:  28%|██▊       | 1941/6855 [06:56<17:55,  4.57it/s]

Processing tickers:  28%|██▊       | 1942/6855 [06:56<17:41,  4.63it/s]

Processing tickers:  28%|██▊       | 1943/6855 [06:57<17:33,  4.66it/s]

Processing tickers:  28%|██▊       | 1944/6855 [06:57<17:21,  4.72it/s]

Processing tickers:  28%|██▊       | 1945/6855 [06:57<17:42,  4.62it/s]

Processing tickers:  28%|██▊       | 1946/6855 [06:57<18:00,  4.54it/s]

Processing tickers:  28%|██▊       | 1947/6855 [06:58<17:49,  4.59it/s]

Processing tickers:  28%|██▊       | 1948/6855 [06:58<17:38,  4.64it/s]

Processing tickers:  28%|██▊       | 1949/6855 [06:58<17:58,  4.55it/s]

Processing tickers:  28%|██▊       | 1950/6855 [06:58<18:23,  4.44it/s]

Processing tickers:  28%|██▊       | 1951/6855 [06:58<18:29,  4.42it/s]

Processing tickers:  28%|██▊       | 1952/6855 [06:59<17:59,  4.54it/s]

Processing tickers:  28%|██▊       | 1953/6855 [06:59<18:03,  4.52it/s]

Processing tickers:  29%|██▊       | 1954/6855 [06:59<18:17,  4.46it/s]

Processing tickers:  29%|██▊       | 1955/6855 [06:59<17:52,  4.57it/s]

Processing tickers:  29%|██▊       | 1956/6855 [07:00<18:19,  4.45it/s]

Processing tickers:  29%|██▊       | 1957/6855 [07:00<17:57,  4.55it/s]

Processing tickers:  29%|██▊       | 1958/6855 [07:00<17:41,  4.61it/s]

Processing tickers:  29%|██▊       | 1959/6855 [07:00<17:26,  4.68it/s]

Processing tickers:  29%|██▊       | 1960/6855 [07:00<17:20,  4.70it/s]

Processing tickers:  29%|██▊       | 1961/6855 [07:01<17:17,  4.72it/s]

Processing tickers:  29%|██▊       | 1962/6855 [07:01<17:10,  4.75it/s]

Processing tickers:  29%|██▊       | 1963/6855 [07:01<17:09,  4.75it/s]

Processing tickers:  29%|██▊       | 1964/6855 [07:01<17:23,  4.69it/s]

Processing tickers:  29%|██▊       | 1965/6855 [07:01<17:15,  4.72it/s]

Processing tickers:  29%|██▊       | 1966/6855 [07:02<17:29,  4.66it/s]

Processing tickers:  29%|██▊       | 1967/6855 [07:02<17:19,  4.70it/s]

Processing tickers:  29%|██▊       | 1968/6855 [07:02<17:17,  4.71it/s]

Processing tickers:  29%|██▊       | 1969/6855 [07:02<17:20,  4.70it/s]

Processing tickers:  29%|██▊       | 1970/6855 [07:03<17:44,  4.59it/s]

Processing tickers:  29%|██▉       | 1971/6855 [07:03<17:28,  4.66it/s]

Processing tickers:  29%|██▉       | 1972/6855 [07:03<17:24,  4.67it/s]

Processing tickers:  29%|██▉       | 1973/6855 [07:03<17:14,  4.72it/s]

Processing tickers:  29%|██▉       | 1974/6855 [07:03<17:02,  4.77it/s]

Processing tickers:  29%|██▉       | 1975/6855 [07:04<17:21,  4.68it/s]

Processing tickers:  29%|██▉       | 1976/6855 [07:04<17:21,  4.68it/s]

Processing tickers:  29%|██▉       | 1977/6855 [07:04<17:18,  4.70it/s]

Processing tickers:  29%|██▉       | 1978/6855 [07:04<17:32,  4.63it/s]

Processing tickers:  29%|██▉       | 1979/6855 [07:04<17:30,  4.64it/s]

Processing tickers:  29%|██▉       | 1980/6855 [07:05<17:36,  4.62it/s]

Processing tickers:  29%|██▉       | 1981/6855 [07:05<17:23,  4.67it/s]

Processing tickers:  29%|██▉       | 1982/6855 [07:05<17:15,  4.70it/s]

Processing tickers:  29%|██▉       | 1983/6855 [07:05<17:19,  4.69it/s]

Processing tickers:  29%|██▉       | 1984/6855 [07:05<17:10,  4.73it/s]

Processing tickers:  29%|██▉       | 1985/6855 [07:06<17:08,  4.74it/s]

Processing tickers:  29%|██▉       | 1986/6855 [07:06<17:12,  4.72it/s]

Processing tickers:  29%|██▉       | 1987/6855 [07:06<17:32,  4.63it/s]

Processing tickers:  29%|██▉       | 1988/6855 [07:06<17:33,  4.62it/s]

Processing tickers:  29%|██▉       | 1989/6855 [07:07<17:23,  4.66it/s]

Processing tickers:  29%|██▉       | 1990/6855 [07:07<17:19,  4.68it/s]

Processing tickers:  29%|██▉       | 1991/6855 [07:07<17:19,  4.68it/s]

Processing tickers:  29%|██▉       | 1992/6855 [07:07<17:30,  4.63it/s]

Processing tickers:  29%|██▉       | 1993/6855 [07:07<17:25,  4.65it/s]

Processing tickers:  29%|██▉       | 1994/6855 [07:08<17:16,  4.69it/s]

Processing tickers:  29%|██▉       | 1995/6855 [07:08<17:04,  4.74it/s]

Processing tickers:  29%|██▉       | 1996/6855 [07:08<17:03,  4.75it/s]

Processing tickers:  29%|██▉       | 1997/6855 [07:08<16:53,  4.79it/s]

Processing tickers:  29%|██▉       | 1998/6855 [07:08<17:27,  4.64it/s]

Processing tickers:  29%|██▉       | 1999/6855 [07:09<17:20,  4.67it/s]

Processing tickers:  29%|██▉       | 2000/6855 [07:09<17:28,  4.63it/s]

Processing tickers:  29%|██▉       | 2001/6855 [07:09<17:54,  4.52it/s]

Processing tickers:  29%|██▉       | 2002/6855 [07:09<18:06,  4.47it/s]

Processing tickers:  29%|██▉       | 2003/6855 [07:10<17:49,  4.54it/s]

Processing tickers:  29%|██▉       | 2004/6855 [07:10<17:38,  4.58it/s]

Processing tickers:  29%|██▉       | 2005/6855 [07:10<17:28,  4.63it/s]

Processing tickers:  29%|██▉       | 2006/6855 [07:10<17:23,  4.65it/s]

Processing tickers:  29%|██▉       | 2007/6855 [07:10<17:25,  4.64it/s]

Processing tickers:  29%|██▉       | 2008/6855 [07:11<17:17,  4.67it/s]

Processing tickers:  29%|██▉       | 2009/6855 [07:11<17:08,  4.71it/s]

Processing tickers:  29%|██▉       | 2010/6855 [07:11<17:12,  4.69it/s]

Processing tickers:  29%|██▉       | 2011/6855 [07:11<17:16,  4.67it/s]

Processing tickers:  29%|██▉       | 2012/6855 [07:11<17:06,  4.72it/s]

Processing tickers:  29%|██▉       | 2013/6855 [07:12<17:08,  4.71it/s]

Processing tickers:  29%|██▉       | 2014/6855 [07:12<17:00,  4.74it/s]

Processing tickers:  29%|██▉       | 2015/6855 [07:12<17:15,  4.68it/s]

Processing tickers:  29%|██▉       | 2016/6855 [07:12<17:19,  4.65it/s]

Processing tickers:  29%|██▉       | 2017/6855 [07:13<17:08,  4.70it/s]

Processing tickers:  29%|██▉       | 2018/6855 [07:13<16:57,  4.75it/s]

Processing tickers:  29%|██▉       | 2019/6855 [07:13<16:52,  4.78it/s]

Processing tickers:  29%|██▉       | 2020/6855 [07:13<17:20,  4.65it/s]

Processing tickers:  29%|██▉       | 2021/6855 [07:13<17:10,  4.69it/s]

Processing tickers:  29%|██▉       | 2022/6855 [07:14<17:25,  4.62it/s]

Processing tickers:  30%|██▉       | 2023/6855 [07:14<17:49,  4.52it/s]

Processing tickers:  30%|██▉       | 2024/6855 [07:14<17:53,  4.50it/s]

Processing tickers:  30%|██▉       | 2025/6855 [07:14<18:09,  4.44it/s]

Processing tickers:  30%|██▉       | 2026/6855 [07:15<17:46,  4.53it/s]

Processing tickers:  30%|██▉       | 2027/6855 [07:15<17:32,  4.59it/s]

Processing tickers:  30%|██▉       | 2028/6855 [07:15<17:24,  4.62it/s]

Processing tickers:  30%|██▉       | 2029/6855 [07:15<17:19,  4.64it/s]

Processing tickers:  30%|██▉       | 2030/6855 [07:15<17:00,  4.73it/s]

Processing tickers:  30%|██▉       | 2031/6855 [07:16<16:58,  4.73it/s]

Processing tickers:  30%|██▉       | 2032/6855 [07:16<16:52,  4.76it/s]

Processing tickers:  30%|██▉       | 2033/6855 [07:16<16:53,  4.76it/s]

Processing tickers:  30%|██▉       | 2034/6855 [07:16<17:06,  4.70it/s]

Processing tickers:  30%|██▉       | 2035/6855 [07:16<17:00,  4.72it/s]

Processing tickers:  30%|██▉       | 2036/6855 [07:17<16:54,  4.75it/s]

Processing tickers:  30%|██▉       | 2037/6855 [07:17<16:57,  4.74it/s]

Processing tickers:  30%|██▉       | 2038/6855 [07:17<16:56,  4.74it/s]

Processing tickers:  30%|██▉       | 2039/6855 [07:17<16:48,  4.77it/s]

Processing tickers:  30%|██▉       | 2040/6855 [07:17<16:43,  4.80it/s]

Processing tickers:  30%|██▉       | 2041/6855 [07:18<16:36,  4.83it/s]

Processing tickers:  30%|██▉       | 2042/6855 [07:18<16:38,  4.82it/s]

Processing tickers:  30%|██▉       | 2043/6855 [07:18<17:06,  4.69it/s]

Processing tickers:  30%|██▉       | 2044/6855 [07:18<17:03,  4.70it/s]

Processing tickers:  30%|██▉       | 2045/6855 [07:19<17:07,  4.68it/s]

Processing tickers:  30%|██▉       | 2046/6855 [07:19<17:02,  4.70it/s]

Processing tickers:  30%|██▉       | 2047/6855 [07:19<16:56,  4.73it/s]

Processing tickers:  30%|██▉       | 2048/6855 [07:19<16:59,  4.71it/s]

Processing tickers:  30%|██▉       | 2049/6855 [07:19<16:47,  4.77it/s]

Processing tickers:  30%|██▉       | 2050/6855 [07:20<16:43,  4.79it/s]

Processing tickers:  30%|██▉       | 2051/6855 [07:20<17:07,  4.68it/s]

Processing tickers:  30%|██▉       | 2052/6855 [07:20<17:03,  4.69it/s]

Processing tickers:  30%|██▉       | 2053/6855 [07:20<16:59,  4.71it/s]

Processing tickers:  30%|██▉       | 2054/6855 [07:20<17:07,  4.67it/s]

Processing tickers:  30%|██▉       | 2055/6855 [07:21<17:01,  4.70it/s]

Processing tickers:  30%|██▉       | 2056/6855 [07:21<16:50,  4.75it/s]

Processing tickers:  30%|███       | 2057/6855 [07:21<16:45,  4.77it/s]

Processing tickers:  30%|███       | 2058/6855 [07:21<16:40,  4.79it/s]

Processing tickers:  30%|███       | 2059/6855 [07:21<16:41,  4.79it/s]

Processing tickers:  30%|███       | 2060/6855 [07:22<16:47,  4.76it/s]

Processing tickers:  30%|███       | 2061/6855 [07:22<16:41,  4.79it/s]

Processing tickers:  30%|███       | 2062/6855 [07:22<16:42,  4.78it/s]

Processing tickers:  30%|███       | 2063/6855 [07:22<16:39,  4.80it/s]

Processing tickers:  30%|███       | 2064/6855 [07:23<16:36,  4.81it/s]

Processing tickers:  30%|███       | 2065/6855 [07:23<16:37,  4.80it/s]

Processing tickers:  30%|███       | 2066/6855 [07:23<17:10,  4.65it/s]

Processing tickers:  30%|███       | 2067/6855 [07:23<17:06,  4.66it/s]

Processing tickers:  30%|███       | 2068/6855 [07:23<17:00,  4.69it/s]

Processing tickers:  30%|███       | 2069/6855 [07:24<16:58,  4.70it/s]

Processing tickers:  30%|███       | 2070/6855 [07:24<17:16,  4.62it/s]

Processing tickers:  30%|███       | 2071/6855 [07:24<17:34,  4.54it/s]

Processing tickers:  30%|███       | 2072/6855 [07:24<17:14,  4.62it/s]

Processing tickers:  30%|███       | 2073/6855 [07:24<17:30,  4.55it/s]

Processing tickers:  30%|███       | 2074/6855 [07:25<17:17,  4.61it/s]

Processing tickers:  30%|███       | 2075/6855 [07:25<16:58,  4.70it/s]

Processing tickers:  30%|███       | 2076/6855 [07:25<16:43,  4.76it/s]

Processing tickers:  30%|███       | 2077/6855 [07:25<16:36,  4.80it/s]

Processing tickers:  30%|███       | 2078/6855 [07:26<16:43,  4.76it/s]

Processing tickers:  30%|███       | 2079/6855 [07:26<16:39,  4.78it/s]

Processing tickers:  30%|███       | 2080/6855 [07:26<16:41,  4.77it/s]

Processing tickers:  30%|███       | 2081/6855 [07:26<16:42,  4.76it/s]

Processing tickers:  30%|███       | 2082/6855 [07:26<16:44,  4.75it/s]

Processing tickers:  30%|███       | 2083/6855 [07:27<16:34,  4.80it/s]

Processing tickers:  30%|███       | 2084/6855 [07:27<16:59,  4.68it/s]

Processing tickers:  30%|███       | 2085/6855 [07:27<16:51,  4.72it/s]

Processing tickers:  30%|███       | 2086/6855 [07:27<17:09,  4.63it/s]

Processing tickers:  30%|███       | 2087/6855 [07:27<17:02,  4.66it/s]

Processing tickers:  30%|███       | 2088/6855 [07:28<17:15,  4.61it/s]

Processing tickers:  30%|███       | 2089/6855 [07:28<17:28,  4.55it/s]

Processing tickers:  30%|███       | 2090/6855 [07:28<17:49,  4.46it/s]

Processing tickers:  31%|███       | 2091/6855 [07:28<17:31,  4.53it/s]

Processing tickers:  31%|███       | 2092/6855 [07:29<17:27,  4.55it/s]

Processing tickers:  31%|███       | 2093/6855 [07:29<17:11,  4.62it/s]

Processing tickers:  31%|███       | 2094/6855 [07:29<17:28,  4.54it/s]

Processing tickers:  31%|███       | 2095/6855 [07:29<17:24,  4.56it/s]

Processing tickers:  31%|███       | 2096/6855 [07:29<17:39,  4.49it/s]

Processing tickers:  31%|███       | 2097/6855 [07:30<17:56,  4.42it/s]

Processing tickers:  31%|███       | 2098/6855 [07:30<17:56,  4.42it/s]

Processing tickers:  31%|███       | 2099/6855 [07:30<17:22,  4.56it/s]

Processing tickers:  31%|███       | 2100/6855 [07:30<17:32,  4.52it/s]

Processing tickers:  31%|███       | 2101/6855 [07:31<17:44,  4.47it/s]

Processing tickers:  31%|███       | 2102/6855 [07:31<18:02,  4.39it/s]

Processing tickers:  31%|███       | 2103/6855 [07:31<18:24,  4.30it/s]

Processing tickers:  31%|███       | 2104/6855 [07:31<17:44,  4.46it/s]

Processing tickers:  31%|███       | 2105/6855 [07:31<17:17,  4.58it/s]

Processing tickers:  31%|███       | 2106/6855 [07:32<17:36,  4.49it/s]

Processing tickers:  31%|███       | 2107/6855 [07:32<17:18,  4.57it/s]

Processing tickers:  31%|███       | 2108/6855 [07:32<17:38,  4.49it/s]

Processing tickers:  31%|███       | 2109/6855 [07:32<17:21,  4.56it/s]

Processing tickers:  31%|███       | 2110/6855 [07:33<17:05,  4.63it/s]

Processing tickers:  31%|███       | 2111/6855 [07:33<17:09,  4.61it/s]

Processing tickers:  31%|███       | 2112/6855 [07:33<17:01,  4.64it/s]

Processing tickers:  31%|███       | 2113/6855 [07:33<17:09,  4.61it/s]

Processing tickers:  31%|███       | 2114/6855 [07:33<17:01,  4.64it/s]

Processing tickers:  31%|███       | 2115/6855 [07:34<16:58,  4.65it/s]

Processing tickers:  31%|███       | 2116/6855 [07:34<17:13,  4.59it/s]

Processing tickers:  31%|███       | 2117/6855 [07:34<17:26,  4.53it/s]

Processing tickers:  31%|███       | 2118/6855 [07:34<17:33,  4.50it/s]

Processing tickers:  31%|███       | 2119/6855 [07:35<17:56,  4.40it/s]

Processing tickers:  31%|███       | 2120/6855 [07:35<17:34,  4.49it/s]

Processing tickers:  31%|███       | 2121/6855 [07:35<17:41,  4.46it/s]

Processing tickers:  31%|███       | 2122/6855 [07:35<18:20,  4.30it/s]

Processing tickers:  31%|███       | 2123/6855 [07:35<17:53,  4.41it/s]

Processing tickers:  31%|███       | 2124/6855 [07:36<17:28,  4.51it/s]

Processing tickers:  31%|███       | 2125/6855 [07:36<17:05,  4.61it/s]

Processing tickers:  31%|███       | 2126/6855 [07:36<16:56,  4.65it/s]

Processing tickers:  31%|███       | 2127/6855 [07:36<16:47,  4.69it/s]

Processing tickers:  31%|███       | 2128/6855 [07:37<17:19,  4.55it/s]

Processing tickers:  31%|███       | 2129/6855 [07:37<17:02,  4.62it/s]

Processing tickers:  31%|███       | 2130/6855 [07:37<16:41,  4.72it/s]

Processing tickers:  31%|███       | 2131/6855 [07:37<16:34,  4.75it/s]

Processing tickers:  31%|███       | 2132/6855 [07:37<16:32,  4.76it/s]

Processing tickers:  31%|███       | 2133/6855 [07:38<16:23,  4.80it/s]

Processing tickers:  31%|███       | 2134/6855 [07:38<16:37,  4.73it/s]

Processing tickers:  31%|███       | 2135/6855 [07:38<16:36,  4.74it/s]

Processing tickers:  31%|███       | 2136/6855 [07:38<16:39,  4.72it/s]

Processing tickers:  31%|███       | 2137/6855 [07:38<16:42,  4.71it/s]

Processing tickers:  31%|███       | 2138/6855 [07:39<16:32,  4.75it/s]

Processing tickers:  31%|███       | 2139/6855 [07:39<16:47,  4.68it/s]

Processing tickers:  31%|███       | 2140/6855 [07:39<16:41,  4.71it/s]

Processing tickers:  31%|███       | 2141/6855 [07:39<16:59,  4.63it/s]

Processing tickers:  31%|███       | 2142/6855 [07:39<16:47,  4.68it/s]

Processing tickers:  31%|███▏      | 2143/6855 [07:40<16:36,  4.73it/s]

Processing tickers:  31%|███▏      | 2144/6855 [07:40<17:03,  4.60it/s]

Processing tickers:  31%|███▏      | 2145/6855 [07:40<17:24,  4.51it/s]

Processing tickers:  31%|███▏      | 2146/6855 [07:40<17:11,  4.56it/s]

Processing tickers:  31%|███▏      | 2147/6855 [07:41<17:28,  4.49it/s]

Processing tickers:  31%|███▏      | 2148/6855 [07:41<17:26,  4.50it/s]

Processing tickers:  31%|███▏      | 2149/6855 [07:41<17:06,  4.59it/s]

Processing tickers:  31%|███▏      | 2150/6855 [07:41<16:57,  4.63it/s]

Processing tickers:  31%|███▏      | 2151/6855 [07:41<16:47,  4.67it/s]

Processing tickers:  31%|███▏      | 2152/6855 [07:42<16:36,  4.72it/s]

Processing tickers:  31%|███▏      | 2153/6855 [07:42<16:34,  4.73it/s]

Processing tickers:  31%|███▏      | 2154/6855 [07:42<16:30,  4.75it/s]

Processing tickers:  31%|███▏      | 2155/6855 [07:42<16:32,  4.73it/s]

Processing tickers:  31%|███▏      | 2156/6855 [07:42<16:26,  4.76it/s]

Processing tickers:  31%|███▏      | 2157/6855 [07:43<16:27,  4.76it/s]

Processing tickers:  31%|███▏      | 2158/6855 [07:43<16:22,  4.78it/s]

Processing tickers:  31%|███▏      | 2159/6855 [07:43<16:52,  4.64it/s]

Processing tickers:  32%|███▏      | 2160/6855 [07:43<17:16,  4.53it/s]

Processing tickers:  32%|███▏      | 2161/6855 [07:44<17:00,  4.60it/s]

Processing tickers:  32%|███▏      | 2162/6855 [07:44<17:16,  4.53it/s]

Processing tickers:  32%|███▏      | 2163/6855 [07:44<17:16,  4.53it/s]

Processing tickers:  32%|███▏      | 2164/6855 [07:44<17:23,  4.49it/s]

Processing tickers:  32%|███▏      | 2165/6855 [07:44<17:05,  4.57it/s]

Processing tickers:  32%|███▏      | 2166/6855 [07:45<16:54,  4.62it/s]

Processing tickers:  32%|███▏      | 2167/6855 [07:45<16:50,  4.64it/s]

Processing tickers:  32%|███▏      | 2168/6855 [07:45<16:47,  4.65it/s]

Processing tickers:  32%|███▏      | 2169/6855 [07:45<16:39,  4.69it/s]

Processing tickers:  32%|███▏      | 2170/6855 [07:46<16:39,  4.69it/s]

Processing tickers:  32%|███▏      | 2171/6855 [07:46<16:33,  4.72it/s]

Processing tickers:  32%|███▏      | 2172/6855 [07:46<16:56,  4.61it/s]

Processing tickers:  32%|███▏      | 2173/6855 [07:46<16:53,  4.62it/s]

Processing tickers:  32%|███▏      | 2174/6855 [07:46<16:44,  4.66it/s]

Processing tickers:  32%|███▏      | 2175/6855 [07:47<16:32,  4.72it/s]

Processing tickers:  32%|███▏      | 2176/6855 [07:47<16:25,  4.75it/s]

Processing tickers:  32%|███▏      | 2177/6855 [07:47<16:25,  4.75it/s]

Processing tickers:  32%|███▏      | 2178/6855 [07:47<16:33,  4.71it/s]

Processing tickers:  32%|███▏      | 2179/6855 [07:47<16:21,  4.76it/s]

Processing tickers:  32%|███▏      | 2180/6855 [07:48<16:22,  4.76it/s]

Processing tickers:  32%|███▏      | 2181/6855 [07:48<16:23,  4.75it/s]

Processing tickers:  32%|███▏      | 2182/6855 [07:48<16:37,  4.68it/s]

Processing tickers:  32%|███▏      | 2183/6855 [07:48<16:59,  4.58it/s]

Processing tickers:  32%|███▏      | 2184/6855 [07:49<16:58,  4.59it/s]

Processing tickers:  32%|███▏      | 2185/6855 [07:49<16:48,  4.63it/s]

Processing tickers:  32%|███▏      | 2186/6855 [07:49<16:33,  4.70it/s]

Processing tickers:  32%|███▏      | 2187/6855 [07:49<16:29,  4.72it/s]

Processing tickers:  32%|███▏      | 2188/6855 [07:49<16:27,  4.73it/s]

Processing tickers:  32%|███▏      | 2189/6855 [07:50<16:55,  4.59it/s]

Processing tickers:  32%|███▏      | 2190/6855 [07:50<17:15,  4.50it/s]

Processing tickers:  32%|███▏      | 2191/6855 [07:50<17:31,  4.43it/s]

Processing tickers:  32%|███▏      | 2192/6855 [07:50<17:10,  4.53it/s]

Processing tickers:  32%|███▏      | 2193/6855 [07:50<16:54,  4.59it/s]

Processing tickers:  32%|███▏      | 2194/6855 [07:51<16:46,  4.63it/s]

Processing tickers:  32%|███▏      | 2195/6855 [07:51<16:41,  4.65it/s]

Processing tickers:  32%|███▏      | 2196/6855 [07:51<16:34,  4.68it/s]

Processing tickers:  32%|███▏      | 2197/6855 [07:51<16:37,  4.67it/s]

Processing tickers:  32%|███▏      | 2198/6855 [07:52<16:27,  4.71it/s]

Processing tickers:  32%|███▏      | 2199/6855 [07:52<16:20,  4.75it/s]

Processing tickers:  32%|███▏      | 2200/6855 [07:52<16:23,  4.73it/s]

Processing tickers:  32%|███▏      | 2201/6855 [07:52<16:25,  4.72it/s]

Processing tickers:  32%|███▏      | 2202/6855 [07:52<16:22,  4.74it/s]

Processing tickers:  32%|███▏      | 2203/6855 [07:53<16:17,  4.76it/s]

Processing tickers:  32%|███▏      | 2204/6855 [07:53<16:15,  4.77it/s]

Processing tickers:  32%|███▏      | 2205/6855 [07:53<16:11,  4.79it/s]

Processing tickers:  32%|███▏      | 2206/6855 [07:53<16:25,  4.72it/s]

Processing tickers:  32%|███▏      | 2207/6855 [07:53<16:21,  4.73it/s]

Processing tickers:  32%|███▏      | 2208/6855 [07:54<16:21,  4.74it/s]

Processing tickers:  32%|███▏      | 2209/6855 [07:54<16:14,  4.77it/s]

Processing tickers:  32%|███▏      | 2210/6855 [07:54<16:26,  4.71it/s]

Processing tickers:  32%|███▏      | 2211/6855 [07:54<16:54,  4.58it/s]

Processing tickers:  32%|███▏      | 2212/6855 [07:55<17:01,  4.54it/s]

Processing tickers:  32%|███▏      | 2213/6855 [07:55<17:23,  4.45it/s]

Processing tickers:  32%|███▏      | 2214/6855 [07:55<17:30,  4.42it/s]

Processing tickers:  32%|███▏      | 2215/6855 [07:55<17:40,  4.38it/s]

Processing tickers:  32%|███▏      | 2216/6855 [07:55<17:16,  4.48it/s]

Processing tickers:  32%|███▏      | 2217/6855 [07:56<17:09,  4.50it/s]

Processing tickers:  32%|███▏      | 2218/6855 [07:56<17:17,  4.47it/s]

Processing tickers:  32%|███▏      | 2219/6855 [07:56<16:52,  4.58it/s]

Processing tickers:  32%|███▏      | 2220/6855 [07:56<17:17,  4.47it/s]

Processing tickers:  32%|███▏      | 2221/6855 [07:57<16:52,  4.58it/s]

Processing tickers:  32%|███▏      | 2222/6855 [07:57<16:40,  4.63it/s]

Processing tickers:  32%|███▏      | 2223/6855 [07:57<16:32,  4.67it/s]

Processing tickers:  32%|███▏      | 2224/6855 [07:57<16:28,  4.68it/s]

Processing tickers:  32%|███▏      | 2225/6855 [07:57<16:45,  4.61it/s]

Processing tickers:  32%|███▏      | 2226/6855 [07:58<16:39,  4.63it/s]

Processing tickers:  32%|███▏      | 2227/6855 [07:58<16:24,  4.70it/s]

Processing tickers:  33%|███▎      | 2228/6855 [07:58<16:14,  4.75it/s]

Processing tickers:  33%|███▎      | 2229/6855 [07:58<16:40,  4.62it/s]

Processing tickers:  33%|███▎      | 2230/6855 [07:58<16:47,  4.59it/s]

Processing tickers:  33%|███▎      | 2231/6855 [07:59<16:54,  4.56it/s]

Processing tickers:  33%|███▎      | 2232/6855 [07:59<16:42,  4.61it/s]

Processing tickers:  33%|███▎      | 2233/6855 [07:59<16:38,  4.63it/s]

Processing tickers:  33%|███▎      | 2234/6855 [07:59<16:45,  4.59it/s]

Processing tickers:  33%|███▎      | 2235/6855 [08:00<17:05,  4.51it/s]

Processing tickers:  33%|███▎      | 2236/6855 [08:00<17:12,  4.47it/s]

Processing tickers:  33%|███▎      | 2237/6855 [08:00<17:03,  4.51it/s]

Processing tickers:  33%|███▎      | 2238/6855 [08:00<17:12,  4.47it/s]

Processing tickers:  33%|███▎      | 2239/6855 [08:00<16:43,  4.60it/s]

Processing tickers:  33%|███▎      | 2240/6855 [08:01<16:30,  4.66it/s]

Processing tickers:  33%|███▎      | 2241/6855 [08:01<16:46,  4.59it/s]

Processing tickers:  33%|███▎      | 2242/6855 [08:01<16:23,  4.69it/s]

Processing tickers:  33%|███▎      | 2243/6855 [08:01<16:22,  4.69it/s]

Processing tickers:  33%|███▎      | 2244/6855 [08:01<16:09,  4.76it/s]

Processing tickers:  33%|███▎      | 2245/6855 [08:02<16:09,  4.76it/s]

Processing tickers:  33%|███▎      | 2246/6855 [08:02<16:03,  4.78it/s]

Processing tickers:  33%|███▎      | 2247/6855 [08:02<16:04,  4.78it/s]

Processing tickers:  33%|███▎      | 2248/6855 [08:02<16:03,  4.78it/s]

Processing tickers:  33%|███▎      | 2249/6855 [08:03<15:52,  4.83it/s]

Processing tickers:  33%|███▎      | 2250/6855 [08:03<15:58,  4.81it/s]

Processing tickers:  33%|███▎      | 2251/6855 [08:03<16:01,  4.79it/s]

Processing tickers:  33%|███▎      | 2252/6855 [08:03<15:55,  4.82it/s]

Processing tickers:  33%|███▎      | 2253/6855 [08:03<16:09,  4.75it/s]

Processing tickers:  33%|███▎      | 2254/6855 [08:04<16:06,  4.76it/s]

Processing tickers:  33%|███▎      | 2255/6855 [08:04<16:09,  4.75it/s]

Processing tickers:  33%|███▎      | 2256/6855 [08:04<15:59,  4.79it/s]

Processing tickers:  33%|███▎      | 2257/6855 [08:04<16:35,  4.62it/s]

Processing tickers:  33%|███▎      | 2258/6855 [08:04<16:25,  4.67it/s]

Processing tickers:  33%|███▎      | 2259/6855 [08:05<16:22,  4.68it/s]

Processing tickers:  33%|███▎      | 2260/6855 [08:05<16:37,  4.61it/s]

Processing tickers:  33%|███▎      | 2261/6855 [08:05<16:53,  4.53it/s]

Processing tickers:  33%|███▎      | 2262/6855 [08:05<17:13,  4.44it/s]

Processing tickers:  33%|███▎      | 2263/6855 [08:06<17:22,  4.41it/s]

Processing tickers:  33%|███▎      | 2264/6855 [08:06<16:58,  4.51it/s]

Processing tickers:  33%|███▎      | 2265/6855 [08:06<16:38,  4.60it/s]

Processing tickers:  33%|███▎      | 2266/6855 [08:06<16:47,  4.56it/s]

Processing tickers:  33%|███▎      | 2267/6855 [08:06<16:43,  4.57it/s]

Processing tickers:  33%|███▎      | 2268/6855 [08:07<16:37,  4.60it/s]

Processing tickers:  33%|███▎      | 2269/6855 [08:07<17:04,  4.48it/s]

Processing tickers:  33%|███▎      | 2270/6855 [08:07<16:45,  4.56it/s]

Processing tickers:  33%|███▎      | 2271/6855 [08:07<17:15,  4.43it/s]

Processing tickers:  33%|███▎      | 2272/6855 [08:08<16:51,  4.53it/s]

Processing tickers:  33%|███▎      | 2273/6855 [08:08<16:31,  4.62it/s]

Processing tickers:  33%|███▎      | 2274/6855 [08:08<16:33,  4.61it/s]

Processing tickers:  33%|███▎      | 2275/6855 [08:08<16:19,  4.68it/s]

Processing tickers:  33%|███▎      | 2276/6855 [08:08<16:06,  4.74it/s]

Processing tickers:  33%|███▎      | 2277/6855 [08:09<15:59,  4.77it/s]

Processing tickers:  33%|███▎      | 2278/6855 [08:09<15:57,  4.78it/s]

Processing tickers:  33%|███▎      | 2279/6855 [08:09<15:55,  4.79it/s]

Processing tickers:  33%|███▎      | 2280/6855 [08:09<16:04,  4.74it/s]

Processing tickers:  33%|███▎      | 2281/6855 [08:09<16:45,  4.55it/s]

Processing tickers:  33%|███▎      | 2282/6855 [08:10<16:32,  4.61it/s]

Processing tickers:  33%|███▎      | 2283/6855 [08:10<16:18,  4.67it/s]

Processing tickers:  33%|███▎      | 2284/6855 [08:10<16:29,  4.62it/s]

Processing tickers:  33%|███▎      | 2285/6855 [08:10<16:23,  4.65it/s]

Processing tickers:  33%|███▎      | 2286/6855 [08:11<16:09,  4.71it/s]

Processing tickers:  33%|███▎      | 2287/6855 [08:11<16:11,  4.70it/s]

Processing tickers:  33%|███▎      | 2288/6855 [08:11<16:01,  4.75it/s]

Processing tickers:  33%|███▎      | 2289/6855 [08:11<15:59,  4.76it/s]

Processing tickers:  33%|███▎      | 2290/6855 [08:11<16:17,  4.67it/s]

Processing tickers:  33%|███▎      | 2291/6855 [08:12<16:10,  4.70it/s]

Processing tickers:  33%|███▎      | 2292/6855 [08:12<16:19,  4.66it/s]

Processing tickers:  33%|███▎      | 2293/6855 [08:12<16:07,  4.71it/s]

Processing tickers:  33%|███▎      | 2294/6855 [08:12<16:47,  4.53it/s]

Processing tickers:  33%|███▎      | 2295/6855 [08:12<16:33,  4.59it/s]

Processing tickers:  33%|███▎      | 2296/6855 [08:13<16:43,  4.54it/s]

Processing tickers:  34%|███▎      | 2297/6855 [08:13<16:36,  4.57it/s]

Processing tickers:  34%|███▎      | 2298/6855 [08:13<16:24,  4.63it/s]

Processing tickers:  34%|███▎      | 2299/6855 [08:13<16:22,  4.64it/s]

Processing tickers:  34%|███▎      | 2300/6855 [08:14<16:17,  4.66it/s]

Processing tickers:  34%|███▎      | 2301/6855 [08:14<16:11,  4.69it/s]

Processing tickers:  34%|███▎      | 2302/6855 [08:14<16:03,  4.73it/s]

Processing tickers:  34%|███▎      | 2303/6855 [08:14<15:57,  4.75it/s]

Processing tickers:  34%|███▎      | 2304/6855 [08:14<15:57,  4.75it/s]

Processing tickers:  34%|███▎      | 2305/6855 [08:15<15:51,  4.78it/s]

Processing tickers:  34%|███▎      | 2306/6855 [08:15<15:51,  4.78it/s]

Processing tickers:  34%|███▎      | 2307/6855 [08:15<16:02,  4.72it/s]

Processing tickers:  34%|███▎      | 2308/6855 [08:15<16:12,  4.68it/s]

Processing tickers:  34%|███▎      | 2309/6855 [08:15<16:28,  4.60it/s]

Processing tickers:  34%|███▎      | 2310/6855 [08:16<16:49,  4.50it/s]

Processing tickers:  34%|███▎      | 2311/6855 [08:16<17:00,  4.45it/s]

Processing tickers:  34%|███▎      | 2312/6855 [08:16<16:38,  4.55it/s]

Processing tickers:  34%|███▎      | 2313/6855 [08:16<16:24,  4.61it/s]

Processing tickers:  34%|███▍      | 2314/6855 [08:17<16:49,  4.50it/s]

Processing tickers:  34%|███▍      | 2315/6855 [08:17<16:58,  4.46it/s]

Processing tickers:  34%|███▍      | 2316/6855 [08:17<16:46,  4.51it/s]

Processing tickers:  34%|███▍      | 2317/6855 [08:17<17:12,  4.40it/s]

Processing tickers:  34%|███▍      | 2318/6855 [08:17<16:51,  4.48it/s]

Processing tickers:  34%|███▍      | 2319/6855 [08:18<16:32,  4.57it/s]

Processing tickers:  34%|███▍      | 2320/6855 [08:18<16:23,  4.61it/s]

Processing tickers:  34%|███▍      | 2321/6855 [08:18<16:07,  4.68it/s]

Processing tickers:  34%|███▍      | 2322/6855 [08:18<15:57,  4.73it/s]

Processing tickers:  34%|███▍      | 2323/6855 [08:18<15:54,  4.75it/s]

Processing tickers:  34%|███▍      | 2324/6855 [08:19<16:10,  4.67it/s]

Processing tickers:  34%|███▍      | 2325/6855 [08:19<16:06,  4.69it/s]

Processing tickers:  34%|███▍      | 2326/6855 [08:19<15:53,  4.75it/s]

Processing tickers:  34%|███▍      | 2327/6855 [08:19<15:47,  4.78it/s]

Processing tickers:  34%|███▍      | 2328/6855 [08:20<15:48,  4.77it/s]

Processing tickers:  34%|███▍      | 2329/6855 [08:20<16:19,  4.62it/s]

Processing tickers:  34%|███▍      | 2330/6855 [08:20<16:11,  4.66it/s]

Processing tickers:  34%|███▍      | 2331/6855 [08:20<16:31,  4.56it/s]

Processing tickers:  34%|███▍      | 2332/6855 [08:20<16:18,  4.62it/s]

Processing tickers:  34%|███▍      | 2333/6855 [08:21<16:30,  4.57it/s]

Processing tickers:  34%|███▍      | 2334/6855 [08:21<16:50,  4.47it/s]

Processing tickers:  34%|███▍      | 2335/6855 [08:21<16:33,  4.55it/s]

Processing tickers:  34%|███▍      | 2336/6855 [08:21<16:16,  4.63it/s]

Processing tickers:  34%|███▍      | 2337/6855 [08:22<16:13,  4.64it/s]

Processing tickers:  34%|███▍      | 2338/6855 [08:22<16:42,  4.51it/s]

Processing tickers:  34%|███▍      | 2339/6855 [08:22<16:23,  4.59it/s]

Processing tickers:  34%|███▍      | 2340/6855 [08:22<16:12,  4.64it/s]

Processing tickers:  34%|███▍      | 2341/6855 [08:22<16:03,  4.68it/s]

Processing tickers:  34%|███▍      | 2342/6855 [08:23<16:20,  4.60it/s]

Processing tickers:  34%|███▍      | 2343/6855 [08:23<16:02,  4.69it/s]

Processing tickers:  34%|███▍      | 2344/6855 [08:23<16:00,  4.69it/s]

Processing tickers:  34%|███▍      | 2345/6855 [08:23<15:57,  4.71it/s]

Processing tickers:  34%|███▍      | 2346/6855 [08:23<16:08,  4.66it/s]

Processing tickers:  34%|███▍      | 2347/6855 [08:24<16:26,  4.57it/s]

Processing tickers:  34%|███▍      | 2348/6855 [08:24<16:11,  4.64it/s]

Processing tickers:  34%|███▍      | 2349/6855 [08:24<16:21,  4.59it/s]

Processing tickers:  34%|███▍      | 2350/6855 [08:24<16:10,  4.64it/s]

Processing tickers:  34%|███▍      | 2351/6855 [08:25<16:02,  4.68it/s]

Processing tickers:  34%|███▍      | 2352/6855 [08:25<16:09,  4.65it/s]

Processing tickers:  34%|███▍      | 2353/6855 [08:25<16:16,  4.61it/s]

Processing tickers:  34%|███▍      | 2354/6855 [08:25<16:15,  4.61it/s]

Processing tickers:  34%|███▍      | 2355/6855 [08:25<16:02,  4.67it/s]

Processing tickers:  34%|███▍      | 2356/6855 [08:26<15:56,  4.70it/s]

Processing tickers:  34%|███▍      | 2357/6855 [08:26<16:14,  4.61it/s]

Processing tickers:  34%|███▍      | 2358/6855 [08:26<16:31,  4.53it/s]

Processing tickers:  34%|███▍      | 2359/6855 [08:26<16:19,  4.59it/s]

Processing tickers:  34%|███▍      | 2360/6855 [08:27<16:45,  4.47it/s]

Processing tickers:  34%|███▍      | 2361/6855 [08:27<16:28,  4.55it/s]

Processing tickers:  34%|███▍      | 2362/6855 [08:27<16:14,  4.61it/s]

Processing tickers:  34%|███▍      | 2363/6855 [08:27<16:03,  4.66it/s]

Processing tickers:  34%|███▍      | 2364/6855 [08:27<15:53,  4.71it/s]

Processing tickers:  35%|███▍      | 2365/6855 [08:28<15:55,  4.70it/s]

Processing tickers:  35%|███▍      | 2366/6855 [08:28<15:46,  4.74it/s]

Processing tickers:  35%|███▍      | 2367/6855 [08:28<16:14,  4.60it/s]

Processing tickers:  35%|███▍      | 2368/6855 [08:28<16:10,  4.62it/s]

Processing tickers:  35%|███▍      | 2369/6855 [08:28<16:36,  4.50it/s]

Processing tickers:  35%|███▍      | 2370/6855 [08:29<16:47,  4.45it/s]

Processing tickers:  35%|███▍      | 2371/6855 [08:29<16:26,  4.55it/s]

Processing tickers:  35%|███▍      | 2372/6855 [08:29<16:04,  4.65it/s]

Processing tickers:  35%|███▍      | 2373/6855 [08:29<16:23,  4.56it/s]

Processing tickers:  35%|███▍      | 2374/6855 [08:30<16:41,  4.48it/s]

Processing tickers:  35%|███▍      | 2375/6855 [08:30<16:30,  4.52it/s]

Processing tickers:  35%|███▍      | 2376/6855 [08:30<16:17,  4.58it/s]

Processing tickers:  35%|███▍      | 2377/6855 [08:30<16:05,  4.64it/s]

Processing tickers:  35%|███▍      | 2378/6855 [08:30<16:01,  4.66it/s]

Processing tickers:  35%|███▍      | 2379/6855 [08:31<16:25,  4.54it/s]

Processing tickers:  35%|███▍      | 2380/6855 [08:31<16:40,  4.47it/s]

Processing tickers:  35%|███▍      | 2381/6855 [08:31<16:21,  4.56it/s]

Processing tickers:  35%|███▍      | 2382/6855 [08:31<16:10,  4.61it/s]

Processing tickers:  35%|███▍      | 2383/6855 [08:32<16:26,  4.54it/s]

Processing tickers:  35%|███▍      | 2384/6855 [08:32<16:45,  4.44it/s]

Processing tickers:  35%|███▍      | 2385/6855 [08:32<16:39,  4.47it/s]

Processing tickers:  35%|███▍      | 2386/6855 [08:32<16:24,  4.54it/s]

Processing tickers:  35%|███▍      | 2387/6855 [08:32<16:41,  4.46it/s]

Processing tickers:  35%|███▍      | 2388/6855 [08:33<16:15,  4.58it/s]

Processing tickers:  35%|███▍      | 2389/6855 [08:33<16:34,  4.49it/s]

Processing tickers:  35%|███▍      | 2390/6855 [08:33<16:52,  4.41it/s]

Processing tickers:  35%|███▍      | 2391/6855 [08:33<16:21,  4.55it/s]

Processing tickers:  35%|███▍      | 2392/6855 [08:34<16:03,  4.63it/s]

Processing tickers:  35%|███▍      | 2393/6855 [08:34<15:50,  4.70it/s]

Processing tickers:  35%|███▍      | 2394/6855 [08:34<15:42,  4.73it/s]

Processing tickers:  35%|███▍      | 2395/6855 [08:34<16:06,  4.61it/s]

Processing tickers:  35%|███▍      | 2396/6855 [08:34<15:55,  4.67it/s]

Processing tickers:  35%|███▍      | 2397/6855 [08:35<15:44,  4.72it/s]

Processing tickers:  35%|███▍      | 2398/6855 [08:35<15:51,  4.68it/s]

Processing tickers:  35%|███▍      | 2399/6855 [08:35<15:50,  4.69it/s]

Processing tickers:  35%|███▌      | 2400/6855 [08:35<16:06,  4.61it/s]

Processing tickers:  35%|███▌      | 2401/6855 [08:35<16:17,  4.56it/s]

Processing tickers:  35%|███▌      | 2402/6855 [08:36<16:06,  4.61it/s]

Processing tickers:  35%|███▌      | 2403/6855 [08:36<15:47,  4.70it/s]

Processing tickers:  35%|███▌      | 2404/6855 [08:36<15:42,  4.72it/s]

Processing tickers:  35%|███▌      | 2405/6855 [08:36<15:31,  4.78it/s]

Processing tickers:  35%|███▌      | 2406/6855 [08:36<15:36,  4.75it/s]

Processing tickers:  35%|███▌      | 2407/6855 [08:37<15:29,  4.79it/s]

Processing tickers:  35%|███▌      | 2408/6855 [08:37<15:41,  4.72it/s]

Processing tickers:  35%|███▌      | 2409/6855 [08:37<15:59,  4.64it/s]

Processing tickers:  35%|███▌      | 2410/6855 [08:37<15:48,  4.69it/s]

Processing tickers:  35%|███▌      | 2411/6855 [08:38<15:57,  4.64it/s]

Processing tickers:  35%|███▌      | 2412/6855 [08:38<15:47,  4.69it/s]

Processing tickers:  35%|███▌      | 2413/6855 [08:38<15:38,  4.73it/s]

Processing tickers:  35%|███▌      | 2414/6855 [08:38<15:45,  4.69it/s]

Processing tickers:  35%|███▌      | 2415/6855 [08:38<16:20,  4.53it/s]

Processing tickers:  35%|███▌      | 2416/6855 [08:39<16:16,  4.55it/s]

Processing tickers:  35%|███▌      | 2417/6855 [08:39<15:58,  4.63it/s]

Processing tickers:  35%|███▌      | 2418/6855 [08:39<15:51,  4.66it/s]

Processing tickers:  35%|███▌      | 2419/6855 [08:39<15:41,  4.71it/s]

Processing tickers:  35%|███▌      | 2420/6855 [08:40<15:57,  4.63it/s]

Processing tickers:  35%|███▌      | 2421/6855 [08:40<15:41,  4.71it/s]

Processing tickers:  35%|███▌      | 2422/6855 [08:40<16:20,  4.52it/s]

Processing tickers:  35%|███▌      | 2423/6855 [08:40<16:06,  4.59it/s]

Processing tickers:  35%|███▌      | 2424/6855 [08:40<16:10,  4.56it/s]

Processing tickers:  35%|███▌      | 2425/6855 [08:41<15:53,  4.65it/s]

Processing tickers:  35%|███▌      | 2426/6855 [08:41<15:56,  4.63it/s]

Processing tickers:  35%|███▌      | 2427/6855 [08:41<15:39,  4.71it/s]

Processing tickers:  35%|███▌      | 2428/6855 [08:41<15:41,  4.70it/s]

Processing tickers:  35%|███▌      | 2429/6855 [08:41<16:02,  4.60it/s]

Processing tickers:  35%|███▌      | 2430/6855 [08:42<15:54,  4.64it/s]

Processing tickers:  35%|███▌      | 2431/6855 [08:42<15:46,  4.67it/s]

Processing tickers:  35%|███▌      | 2432/6855 [08:42<16:05,  4.58it/s]

Processing tickers:  35%|███▌      | 2433/6855 [08:42<15:58,  4.61it/s]

Processing tickers:  36%|███▌      | 2434/6855 [08:43<15:44,  4.68it/s]

Processing tickers:  36%|███▌      | 2435/6855 [08:43<15:43,  4.69it/s]

Processing tickers:  36%|███▌      | 2436/6855 [08:43<15:38,  4.71it/s]

Processing tickers:  36%|███▌      | 2437/6855 [08:43<15:32,  4.74it/s]

Processing tickers:  36%|███▌      | 2438/6855 [08:43<15:33,  4.73it/s]

Processing tickers:  36%|███▌      | 2439/6855 [08:44<15:30,  4.74it/s]

Processing tickers:  36%|███▌      | 2440/6855 [08:44<15:31,  4.74it/s]

Processing tickers:  36%|███▌      | 2441/6855 [08:44<15:27,  4.76it/s]

Processing tickers:  36%|███▌      | 2442/6855 [08:44<15:33,  4.73it/s]

Processing tickers:  36%|███▌      | 2443/6855 [08:44<15:29,  4.75it/s]

Processing tickers:  36%|███▌      | 2444/6855 [08:45<15:26,  4.76it/s]

Processing tickers:  36%|███▌      | 2445/6855 [08:45<15:28,  4.75it/s]

Processing tickers:  36%|███▌      | 2446/6855 [08:45<15:31,  4.73it/s]

Processing tickers:  36%|███▌      | 2447/6855 [08:45<15:46,  4.66it/s]

Processing tickers:  36%|███▌      | 2448/6855 [08:45<15:38,  4.70it/s]

Processing tickers:  36%|███▌      | 2449/6855 [08:46<15:49,  4.64it/s]

Processing tickers:  36%|███▌      | 2450/6855 [08:46<15:48,  4.65it/s]

Processing tickers:  36%|███▌      | 2451/6855 [08:46<16:14,  4.52it/s]

Processing tickers:  36%|███▌      | 2452/6855 [08:46<16:40,  4.40it/s]

Processing tickers:  36%|███▌      | 2453/6855 [08:47<16:28,  4.45it/s]

Processing tickers:  36%|███▌      | 2454/6855 [08:47<16:05,  4.56it/s]

Processing tickers:  36%|███▌      | 2455/6855 [08:47<16:15,  4.51it/s]

Processing tickers:  36%|███▌      | 2456/6855 [08:47<15:59,  4.58it/s]

Processing tickers:  36%|███▌      | 2457/6855 [08:47<16:07,  4.55it/s]

Processing tickers:  36%|███▌      | 2458/6855 [08:48<15:56,  4.59it/s]

Processing tickers:  36%|███▌      | 2459/6855 [08:48<16:09,  4.53it/s]

Processing tickers:  36%|███▌      | 2460/6855 [08:48<15:52,  4.61it/s]

Processing tickers:  36%|███▌      | 2461/6855 [08:48<15:58,  4.59it/s]

Processing tickers:  36%|███▌      | 2462/6855 [08:49<15:55,  4.60it/s]

Processing tickers:  36%|███▌      | 2463/6855 [08:49<16:08,  4.54it/s]

Processing tickers:  36%|███▌      | 2464/6855 [08:49<15:51,  4.62it/s]

Processing tickers:  36%|███▌      | 2465/6855 [08:49<16:01,  4.57it/s]

Processing tickers:  36%|███▌      | 2466/6855 [08:49<16:06,  4.54it/s]

Processing tickers:  36%|███▌      | 2467/6855 [08:50<15:55,  4.59it/s]

Processing tickers:  36%|███▌      | 2468/6855 [08:50<15:57,  4.58it/s]

Processing tickers:  36%|███▌      | 2469/6855 [08:50<15:40,  4.66it/s]

Processing tickers:  36%|███▌      | 2470/6855 [08:50<15:40,  4.66it/s]

Processing tickers:  36%|███▌      | 2471/6855 [08:51<15:32,  4.70it/s]

Processing tickers:  36%|███▌      | 2472/6855 [08:51<15:43,  4.64it/s]

Processing tickers:  36%|███▌      | 2473/6855 [08:51<15:57,  4.57it/s]

Processing tickers:  36%|███▌      | 2474/6855 [08:51<15:43,  4.64it/s]

Processing tickers:  36%|███▌      | 2475/6855 [08:51<15:29,  4.71it/s]

Processing tickers:  36%|███▌      | 2476/6855 [08:52<15:36,  4.67it/s]

Processing tickers:  36%|███▌      | 2477/6855 [08:52<15:29,  4.71it/s]

Processing tickers:  36%|███▌      | 2478/6855 [08:52<15:45,  4.63it/s]

Processing tickers:  36%|███▌      | 2479/6855 [08:52<15:36,  4.67it/s]

Processing tickers:  36%|███▌      | 2480/6855 [08:52<15:28,  4.71it/s]

Processing tickers:  36%|███▌      | 2481/6855 [08:53<15:26,  4.72it/s]

Processing tickers:  36%|███▌      | 2482/6855 [08:53<15:17,  4.77it/s]

Processing tickers:  36%|███▌      | 2483/6855 [08:53<15:10,  4.80it/s]

Processing tickers:  36%|███▌      | 2484/6855 [08:53<15:27,  4.71it/s]

Processing tickers:  36%|███▋      | 2485/6855 [08:53<15:34,  4.68it/s]

Processing tickers:  36%|███▋      | 2486/6855 [08:54<15:59,  4.55it/s]

Processing tickers:  36%|███▋      | 2487/6855 [08:54<15:45,  4.62it/s]

Processing tickers:  36%|███▋      | 2488/6855 [08:54<15:31,  4.69it/s]

Processing tickers:  36%|███▋      | 2489/6855 [08:54<15:29,  4.70it/s]

Processing tickers:  36%|███▋      | 2490/6855 [08:55<15:28,  4.70it/s]

Processing tickers:  36%|███▋      | 2491/6855 [08:55<15:18,  4.75it/s]

Processing tickers:  36%|███▋      | 2492/6855 [08:55<15:35,  4.66it/s]

Processing tickers:  36%|███▋      | 2493/6855 [08:55<15:45,  4.61it/s]

Processing tickers:  36%|███▋      | 2494/6855 [08:55<15:40,  4.64it/s]

Processing tickers:  36%|███▋      | 2495/6855 [08:56<15:41,  4.63it/s]

Processing tickers:  36%|███▋      | 2496/6855 [08:56<15:46,  4.61it/s]

Processing tickers:  36%|███▋      | 2497/6855 [08:56<16:08,  4.50it/s]

Processing tickers:  36%|███▋      | 2498/6855 [08:56<15:46,  4.61it/s]

Processing tickers:  36%|███▋      | 2499/6855 [08:57<15:53,  4.57it/s]

Processing tickers:  36%|███▋      | 2500/6855 [08:57<15:56,  4.55it/s]

Processing tickers:  36%|███▋      | 2501/6855 [08:57<15:36,  4.65it/s]

Processing tickers:  36%|███▋      | 2502/6855 [08:57<15:35,  4.65it/s]

Processing tickers:  37%|███▋      | 2503/6855 [08:57<15:36,  4.65it/s]

Processing tickers:  37%|███▋      | 2504/6855 [08:58<15:29,  4.68it/s]

Processing tickers:  37%|███▋      | 2505/6855 [08:58<15:21,  4.72it/s]

Processing tickers:  37%|███▋      | 2506/6855 [08:58<15:56,  4.55it/s]

Processing tickers:  37%|███▋      | 2507/6855 [08:58<15:38,  4.63it/s]

Processing tickers:  37%|███▋      | 2508/6855 [08:58<15:27,  4.69it/s]

Processing tickers:  37%|███▋      | 2509/6855 [08:59<15:38,  4.63it/s]

Processing tickers:  37%|███▋      | 2510/6855 [08:59<15:31,  4.67it/s]

Processing tickers:  37%|███▋      | 2511/6855 [08:59<15:32,  4.66it/s]

Processing tickers:  37%|███▋      | 2512/6855 [08:59<15:55,  4.55it/s]

Processing tickers:  37%|███▋      | 2513/6855 [09:00<16:12,  4.47it/s]

Processing tickers:  37%|███▋      | 2514/6855 [09:00<15:51,  4.56it/s]

Processing tickers:  37%|███▋      | 2515/6855 [09:00<15:35,  4.64it/s]

Processing tickers:  37%|███▋      | 2516/6855 [09:00<15:36,  4.63it/s]

Processing tickers:  37%|███▋      | 2517/6855 [09:00<15:36,  4.63it/s]

Processing tickers:  37%|███▋      | 2518/6855 [09:01<15:21,  4.71it/s]

Processing tickers:  37%|███▋      | 2519/6855 [09:01<15:11,  4.75it/s]

Processing tickers:  37%|███▋      | 2520/6855 [09:01<15:04,  4.79it/s]

Processing tickers:  37%|███▋      | 2521/6855 [09:01<15:33,  4.64it/s]

Processing tickers:  37%|███▋      | 2522/6855 [09:01<15:25,  4.68it/s]

Processing tickers:  37%|███▋      | 2523/6855 [09:02<15:35,  4.63it/s]

Processing tickers:  37%|███▋      | 2524/6855 [09:02<15:25,  4.68it/s]

Processing tickers:  37%|███▋      | 2525/6855 [09:02<15:19,  4.71it/s]

Processing tickers:  37%|███▋      | 2526/6855 [09:02<15:12,  4.74it/s]

Processing tickers:  37%|███▋      | 2527/6855 [09:03<15:33,  4.64it/s]

Processing tickers:  37%|███▋      | 2528/6855 [09:03<15:14,  4.73it/s]

Processing tickers:  37%|███▋      | 2529/6855 [09:03<15:22,  4.69it/s]

Processing tickers:  37%|███▋      | 2530/6855 [09:03<15:46,  4.57it/s]

Processing tickers:  37%|███▋      | 2531/6855 [09:03<15:31,  4.64it/s]

Processing tickers:  37%|███▋      | 2532/6855 [09:04<15:30,  4.64it/s]

Processing tickers:  37%|███▋      | 2533/6855 [09:04<15:45,  4.57it/s]

Processing tickers:  37%|███▋      | 2534/6855 [09:04<15:31,  4.64it/s]

Processing tickers:  37%|███▋      | 2535/6855 [09:04<15:21,  4.69it/s]

Processing tickers:  37%|███▋      | 2536/6855 [09:04<15:13,  4.73it/s]

Processing tickers:  37%|███▋      | 2537/6855 [09:05<15:38,  4.60it/s]

Processing tickers:  37%|███▋      | 2538/6855 [09:05<15:24,  4.67it/s]

Processing tickers:  37%|███▋      | 2539/6855 [09:05<15:21,  4.68it/s]

Processing tickers:  37%|███▋      | 2540/6855 [09:05<15:13,  4.73it/s]

Processing tickers:  37%|███▋      | 2541/6855 [09:06<15:02,  4.78it/s]

Processing tickers:  37%|███▋      | 2542/6855 [09:06<15:04,  4.77it/s]

Processing tickers:  37%|███▋      | 2543/6855 [09:06<15:16,  4.71it/s]

Processing tickers:  37%|███▋      | 2544/6855 [09:06<15:21,  4.68it/s]

Processing tickers:  37%|███▋      | 2545/6855 [09:06<15:25,  4.66it/s]

Processing tickers:  37%|███▋      | 2546/6855 [09:07<15:19,  4.69it/s]

Processing tickers:  37%|███▋      | 2547/6855 [09:07<15:21,  4.68it/s]

Processing tickers:  37%|███▋      | 2548/6855 [09:07<15:16,  4.70it/s]

Processing tickers:  37%|███▋      | 2549/6855 [09:07<15:42,  4.57it/s]

Processing tickers:  37%|███▋      | 2550/6855 [09:07<15:31,  4.62it/s]

Processing tickers:  37%|███▋      | 2551/6855 [09:08<15:41,  4.57it/s]

Processing tickers:  37%|███▋      | 2552/6855 [09:08<15:28,  4.64it/s]

Processing tickers:  37%|███▋      | 2553/6855 [09:08<15:18,  4.68it/s]

Processing tickers:  37%|███▋      | 2554/6855 [09:08<15:11,  4.72it/s]

Processing tickers:  37%|███▋      | 2555/6855 [09:09<15:05,  4.75it/s]

Processing tickers:  37%|███▋      | 2556/6855 [09:09<14:55,  4.80it/s]

Processing tickers:  37%|███▋      | 2557/6855 [09:09<15:01,  4.77it/s]

Processing tickers:  37%|███▋      | 2558/6855 [09:09<14:57,  4.79it/s]

Processing tickers:  37%|███▋      | 2559/6855 [09:09<14:52,  4.81it/s]

Processing tickers:  37%|███▋      | 2560/6855 [09:10<15:08,  4.73it/s]

Processing tickers:  37%|███▋      | 2561/6855 [09:10<15:08,  4.73it/s]

Processing tickers:  37%|███▋      | 2562/6855 [09:10<15:06,  4.73it/s]

Processing tickers:  37%|███▋      | 2563/6855 [09:10<15:37,  4.58it/s]

Processing tickers:  37%|███▋      | 2564/6855 [09:10<15:27,  4.63it/s]

Processing tickers:  37%|███▋      | 2565/6855 [09:11<15:30,  4.61it/s]

Processing tickers:  37%|███▋      | 2566/6855 [09:11<15:49,  4.52it/s]

Processing tickers:  37%|███▋      | 2567/6855 [09:11<15:38,  4.57it/s]

Processing tickers:  37%|███▋      | 2568/6855 [09:11<15:33,  4.59it/s]

Processing tickers:  37%|███▋      | 2569/6855 [09:12<15:37,  4.57it/s]

Processing tickers:  37%|███▋      | 2570/6855 [09:12<15:28,  4.62it/s]

Processing tickers:  38%|███▊      | 2571/6855 [09:12<15:19,  4.66it/s]

Processing tickers:  38%|███▊      | 2572/6855 [09:12<15:16,  4.67it/s]

Processing tickers:  38%|███▊      | 2573/6855 [09:12<15:26,  4.62it/s]

Processing tickers:  38%|███▊      | 2574/6855 [09:13<15:17,  4.67it/s]

Processing tickers:  38%|███▊      | 2575/6855 [09:13<15:11,  4.69it/s]

Processing tickers:  38%|███▊      | 2576/6855 [09:13<15:03,  4.73it/s]

Processing tickers:  38%|███▊      | 2577/6855 [09:13<15:02,  4.74it/s]

Processing tickers:  38%|███▊      | 2578/6855 [09:13<14:57,  4.77it/s]

Processing tickers:  38%|███▊      | 2579/6855 [09:14<14:58,  4.76it/s]

Processing tickers:  38%|███▊      | 2580/6855 [09:14<15:02,  4.74it/s]

Processing tickers:  38%|███▊      | 2581/6855 [09:14<15:02,  4.74it/s]

Processing tickers:  38%|███▊      | 2582/6855 [09:14<14:55,  4.77it/s]

Processing tickers:  38%|███▊      | 2583/6855 [09:14<14:51,  4.79it/s]

Processing tickers:  38%|███▊      | 2584/6855 [09:15<15:15,  4.67it/s]

Processing tickers:  38%|███▊      | 2585/6855 [09:15<15:03,  4.73it/s]

Processing tickers:  38%|███▊      | 2586/6855 [09:15<15:03,  4.73it/s]

Processing tickers:  38%|███▊      | 2587/6855 [09:15<15:02,  4.73it/s]

Processing tickers:  38%|███▊      | 2588/6855 [09:16<15:10,  4.68it/s]

Processing tickers:  38%|███▊      | 2589/6855 [09:16<15:41,  4.53it/s]

Processing tickers:  38%|███▊      | 2590/6855 [09:16<15:50,  4.49it/s]

Processing tickers:  38%|███▊      | 2591/6855 [09:16<15:54,  4.47it/s]

Processing tickers:  38%|███▊      | 2592/6855 [09:17<16:10,  4.39it/s]

Processing tickers:  38%|███▊      | 2593/6855 [09:17<15:48,  4.49it/s]

Processing tickers:  38%|███▊      | 2594/6855 [09:17<15:27,  4.59it/s]

Processing tickers:  38%|███▊      | 2595/6855 [09:17<15:19,  4.63it/s]

Processing tickers:  38%|███▊      | 2596/6855 [09:17<15:09,  4.68it/s]

Processing tickers:  38%|███▊      | 2597/6855 [09:18<15:06,  4.70it/s]

Processing tickers:  38%|███▊      | 2598/6855 [09:18<15:10,  4.67it/s]

Processing tickers:  38%|███▊      | 2599/6855 [09:18<15:08,  4.68it/s]

Processing tickers:  38%|███▊      | 2600/6855 [09:18<15:25,  4.60it/s]

Processing tickers:  38%|███▊      | 2601/6855 [09:18<15:19,  4.63it/s]

Processing tickers:  38%|███▊      | 2602/6855 [09:19<15:11,  4.67it/s]

Processing tickers:  38%|███▊      | 2603/6855 [09:19<15:07,  4.69it/s]

Processing tickers:  38%|███▊      | 2604/6855 [09:19<15:27,  4.58it/s]

Processing tickers:  38%|███▊      | 2605/6855 [09:19<15:09,  4.67it/s]

Processing tickers:  38%|███▊      | 2606/6855 [09:19<15:08,  4.68it/s]

Processing tickers:  38%|███▊      | 2607/6855 [09:20<15:00,  4.72it/s]

Processing tickers:  38%|███▊      | 2608/6855 [09:20<14:59,  4.72it/s]

Processing tickers:  38%|███▊      | 2609/6855 [09:20<14:47,  4.79it/s]

Processing tickers:  38%|███▊      | 2610/6855 [09:20<14:42,  4.81it/s]

Processing tickers:  38%|███▊      | 2611/6855 [09:21<14:36,  4.84it/s]

Processing tickers:  38%|███▊      | 2612/6855 [09:21<14:50,  4.76it/s]

Processing tickers:  38%|███▊      | 2613/6855 [09:21<15:01,  4.71it/s]

Processing tickers:  38%|███▊      | 2614/6855 [09:21<14:54,  4.74it/s]

Processing tickers:  38%|███▊      | 2615/6855 [09:21<14:52,  4.75it/s]

Processing tickers:  38%|███▊      | 2616/6855 [09:22<14:54,  4.74it/s]

Processing tickers:  38%|███▊      | 2617/6855 [09:22<14:51,  4.75it/s]

Processing tickers:  38%|███▊      | 2618/6855 [09:22<14:54,  4.73it/s]

Processing tickers:  38%|███▊      | 2619/6855 [09:22<15:00,  4.70it/s]

Processing tickers:  38%|███▊      | 2620/6855 [09:22<14:56,  4.72it/s]

Processing tickers:  38%|███▊      | 2621/6855 [09:23<14:54,  4.73it/s]

Processing tickers:  38%|███▊      | 2622/6855 [09:23<14:52,  4.74it/s]

Processing tickers:  38%|███▊      | 2623/6855 [09:23<14:51,  4.75it/s]

Processing tickers:  38%|███▊      | 2624/6855 [09:23<14:49,  4.76it/s]

Processing tickers:  38%|███▊      | 2625/6855 [09:23<14:51,  4.74it/s]

Processing tickers:  38%|███▊      | 2626/6855 [09:24<14:59,  4.70it/s]

Processing tickers:  38%|███▊      | 2627/6855 [09:24<14:53,  4.73it/s]

Processing tickers:  38%|███▊      | 2628/6855 [09:24<14:44,  4.78it/s]

Processing tickers:  38%|███▊      | 2629/6855 [09:24<14:43,  4.79it/s]

Processing tickers:  38%|███▊      | 2630/6855 [09:25<14:37,  4.82it/s]

Processing tickers:  38%|███▊      | 2631/6855 [09:25<14:55,  4.72it/s]

Processing tickers:  38%|███▊      | 2632/6855 [09:25<14:51,  4.74it/s]

Processing tickers:  38%|███▊      | 2633/6855 [09:25<14:48,  4.75it/s]

Processing tickers:  38%|███▊      | 2634/6855 [09:25<14:43,  4.78it/s]

Processing tickers:  38%|███▊      | 2635/6855 [09:26<14:50,  4.74it/s]

Processing tickers:  38%|███▊      | 2636/6855 [09:26<14:46,  4.76it/s]

Processing tickers:  38%|███▊      | 2637/6855 [09:26<15:15,  4.61it/s]

Processing tickers:  38%|███▊      | 2638/6855 [09:26<15:30,  4.53it/s]

Processing tickers:  38%|███▊      | 2639/6855 [09:26<15:22,  4.57it/s]

Processing tickers:  39%|███▊      | 2640/6855 [09:27<15:10,  4.63it/s]

Processing tickers:  39%|███▊      | 2641/6855 [09:27<15:06,  4.65it/s]

Processing tickers:  39%|███▊      | 2642/6855 [09:27<14:52,  4.72it/s]

Processing tickers:  39%|███▊      | 2643/6855 [09:27<15:05,  4.65it/s]

Processing tickers:  39%|███▊      | 2644/6855 [09:28<14:59,  4.68it/s]

Processing tickers:  39%|███▊      | 2645/6855 [09:28<14:51,  4.72it/s]

Processing tickers:  39%|███▊      | 2646/6855 [09:28<14:49,  4.73it/s]

Processing tickers:  39%|███▊      | 2647/6855 [09:28<14:44,  4.76it/s]

Processing tickers:  39%|███▊      | 2648/6855 [09:28<14:49,  4.73it/s]

Processing tickers:  39%|███▊      | 2649/6855 [09:29<14:42,  4.77it/s]

Processing tickers:  39%|███▊      | 2650/6855 [09:29<14:36,  4.80it/s]

Processing tickers:  39%|███▊      | 2651/6855 [09:29<14:42,  4.76it/s]

Processing tickers:  39%|███▊      | 2652/6855 [09:29<15:04,  4.65it/s]

Processing tickers:  39%|███▊      | 2653/6855 [09:29<15:00,  4.66it/s]

Processing tickers:  39%|███▊      | 2654/6855 [09:30<14:46,  4.74it/s]

Processing tickers:  39%|███▊      | 2655/6855 [09:30<14:44,  4.75it/s]

Processing tickers:  39%|███▊      | 2656/6855 [09:30<15:03,  4.65it/s]

Processing tickers:  39%|███▉      | 2657/6855 [09:30<14:50,  4.71it/s]

Processing tickers:  39%|███▉      | 2658/6855 [09:30<14:43,  4.75it/s]

Processing tickers:  39%|███▉      | 2659/6855 [09:31<15:13,  4.59it/s]

Processing tickers:  39%|███▉      | 2660/6855 [09:31<15:06,  4.63it/s]

Processing tickers:  39%|███▉      | 2661/6855 [09:31<14:54,  4.69it/s]

Processing tickers:  39%|███▉      | 2662/6855 [09:31<15:07,  4.62it/s]

Processing tickers:  39%|███▉      | 2663/6855 [09:32<15:02,  4.65it/s]

Processing tickers:  39%|███▉      | 2664/6855 [09:32<14:52,  4.70it/s]

Processing tickers:  39%|███▉      | 2665/6855 [09:32<14:50,  4.71it/s]

Processing tickers:  39%|███▉      | 2666/6855 [09:32<15:19,  4.56it/s]

Processing tickers:  39%|███▉      | 2667/6855 [09:32<15:05,  4.63it/s]

Processing tickers:  39%|███▉      | 2668/6855 [09:33<14:58,  4.66it/s]

Processing tickers:  39%|███▉      | 2669/6855 [09:33<15:21,  4.54it/s]

Processing tickers:  39%|███▉      | 2670/6855 [09:33<15:12,  4.59it/s]

Processing tickers:  39%|███▉      | 2671/6855 [09:33<15:25,  4.52it/s]

Processing tickers:  39%|███▉      | 2672/6855 [09:34<15:11,  4.59it/s]

Processing tickers:  39%|███▉      | 2673/6855 [09:34<15:03,  4.63it/s]

Processing tickers:  39%|███▉      | 2674/6855 [09:34<15:07,  4.61it/s]

Processing tickers:  39%|███▉      | 2675/6855 [09:34<14:55,  4.67it/s]

Processing tickers:  39%|███▉      | 2676/6855 [09:34<14:51,  4.69it/s]

Processing tickers:  39%|███▉      | 2677/6855 [09:35<15:13,  4.57it/s]

Processing tickers:  39%|███▉      | 2678/6855 [09:35<14:59,  4.64it/s]

Processing tickers:  39%|███▉      | 2679/6855 [09:35<14:45,  4.71it/s]

Processing tickers:  39%|███▉      | 2680/6855 [09:35<14:37,  4.76it/s]

Processing tickers:  39%|███▉      | 2681/6855 [09:35<14:33,  4.78it/s]

Processing tickers:  39%|███▉      | 2682/6855 [09:36<14:35,  4.77it/s]

Processing tickers:  39%|███▉      | 2683/6855 [09:36<14:32,  4.78it/s]

Processing tickers:  39%|███▉      | 2684/6855 [09:36<14:27,  4.81it/s]

Processing tickers:  39%|███▉      | 2685/6855 [09:36<14:51,  4.68it/s]

Processing tickers:  39%|███▉      | 2686/6855 [09:37<15:08,  4.59it/s]

Processing tickers:  39%|███▉      | 2687/6855 [09:37<15:18,  4.54it/s]

Processing tickers:  39%|███▉      | 2688/6855 [09:37<15:09,  4.58it/s]

Processing tickers:  39%|███▉      | 2689/6855 [09:37<15:00,  4.63it/s]

Processing tickers:  39%|███▉      | 2690/6855 [09:37<14:50,  4.68it/s]

Processing tickers:  39%|███▉      | 2691/6855 [09:38<14:46,  4.70it/s]

Processing tickers:  39%|███▉      | 2692/6855 [09:38<14:43,  4.71it/s]

Processing tickers:  39%|███▉      | 2693/6855 [09:38<14:46,  4.70it/s]

Processing tickers:  39%|███▉      | 2694/6855 [09:38<14:41,  4.72it/s]

Processing tickers:  39%|███▉      | 2695/6855 [09:38<14:35,  4.75it/s]

Processing tickers:  39%|███▉      | 2696/6855 [09:39<14:29,  4.78it/s]

Processing tickers:  39%|███▉      | 2697/6855 [09:39<14:59,  4.62it/s]

Processing tickers:  39%|███▉      | 2698/6855 [09:39<14:54,  4.65it/s]

Processing tickers:  39%|███▉      | 2699/6855 [09:39<14:53,  4.65it/s]

Processing tickers:  39%|███▉      | 2700/6855 [09:40<14:45,  4.69it/s]

Processing tickers:  39%|███▉      | 2701/6855 [09:40<14:55,  4.64it/s]

Processing tickers:  39%|███▉      | 2702/6855 [09:40<14:47,  4.68it/s]

Processing tickers:  39%|███▉      | 2703/6855 [09:40<15:06,  4.58it/s]

Processing tickers:  39%|███▉      | 2704/6855 [09:40<14:52,  4.65it/s]

Processing tickers:  39%|███▉      | 2705/6855 [09:41<15:04,  4.59it/s]

Processing tickers:  39%|███▉      | 2706/6855 [09:41<14:54,  4.64it/s]

Processing tickers:  39%|███▉      | 2707/6855 [09:41<14:44,  4.69it/s]

Processing tickers:  40%|███▉      | 2708/6855 [09:41<14:55,  4.63it/s]

Processing tickers:  40%|███▉      | 2709/6855 [09:41<15:06,  4.57it/s]

Processing tickers:  40%|███▉      | 2710/6855 [09:42<15:14,  4.53it/s]

Processing tickers:  40%|███▉      | 2711/6855 [09:42<15:15,  4.53it/s]

Processing tickers:  40%|███▉      | 2712/6855 [09:42<14:52,  4.64it/s]

Processing tickers:  40%|███▉      | 2713/6855 [09:42<14:42,  4.69it/s]

Processing tickers:  40%|███▉      | 2714/6855 [09:43<14:35,  4.73it/s]

Processing tickers:  40%|███▉      | 2715/6855 [09:43<14:33,  4.74it/s]

Processing tickers:  40%|███▉      | 2716/6855 [09:43<15:03,  4.58it/s]

Processing tickers:  40%|███▉      | 2717/6855 [09:43<14:48,  4.66it/s]

Processing tickers:  40%|███▉      | 2718/6855 [09:43<14:45,  4.67it/s]

Processing tickers:  40%|███▉      | 2719/6855 [09:44<14:40,  4.70it/s]

Processing tickers:  40%|███▉      | 2720/6855 [09:44<15:00,  4.59it/s]

Processing tickers:  40%|███▉      | 2721/6855 [09:44<14:46,  4.66it/s]

Processing tickers:  40%|███▉      | 2722/6855 [09:44<14:30,  4.75it/s]

Processing tickers:  40%|███▉      | 2723/6855 [09:44<14:48,  4.65it/s]

Processing tickers:  40%|███▉      | 2724/6855 [09:45<14:43,  4.68it/s]

Processing tickers:  40%|███▉      | 2725/6855 [09:45<14:41,  4.69it/s]

Processing tickers:  40%|███▉      | 2726/6855 [09:45<14:59,  4.59it/s]

Processing tickers:  40%|███▉      | 2727/6855 [09:45<14:45,  4.66it/s]

Processing tickers:  40%|███▉      | 2728/6855 [09:46<14:35,  4.71it/s]

Processing tickers:  40%|███▉      | 2729/6855 [09:46<14:28,  4.75it/s]

Processing tickers:  40%|███▉      | 2730/6855 [09:46<14:57,  4.60it/s]

Processing tickers:  40%|███▉      | 2731/6855 [09:46<15:17,  4.49it/s]

Processing tickers:  40%|███▉      | 2732/6855 [09:46<14:59,  4.58it/s]

Processing tickers:  40%|███▉      | 2733/6855 [09:47<14:51,  4.62it/s]

Processing tickers:  40%|███▉      | 2734/6855 [09:47<14:42,  4.67it/s]

Processing tickers:  40%|███▉      | 2735/6855 [09:47<14:34,  4.71it/s]

Processing tickers:  40%|███▉      | 2736/6855 [09:47<14:29,  4.74it/s]

Processing tickers:  40%|███▉      | 2737/6855 [09:47<14:41,  4.67it/s]

Processing tickers:  40%|███▉      | 2738/6855 [09:48<14:36,  4.70it/s]

Processing tickers:  40%|███▉      | 2739/6855 [09:48<14:29,  4.73it/s]

Processing tickers:  40%|███▉      | 2740/6855 [09:48<14:25,  4.75it/s]

Processing tickers:  40%|███▉      | 2741/6855 [09:48<14:25,  4.75it/s]

Processing tickers:  40%|████      | 2742/6855 [09:49<14:47,  4.63it/s]

Processing tickers:  40%|████      | 2743/6855 [09:49<14:37,  4.68it/s]

Processing tickers:  40%|████      | 2744/6855 [09:49<14:32,  4.71it/s]

Processing tickers:  40%|████      | 2745/6855 [09:49<14:23,  4.76it/s]

Processing tickers:  40%|████      | 2746/6855 [09:49<14:33,  4.70it/s]

Processing tickers:  40%|████      | 2747/6855 [09:50<14:34,  4.70it/s]

Processing tickers:  40%|████      | 2748/6855 [09:50<14:26,  4.74it/s]

Processing tickers:  40%|████      | 2749/6855 [09:50<14:23,  4.76it/s]

Processing tickers:  40%|████      | 2750/6855 [09:50<14:33,  4.70it/s]

Processing tickers:  40%|████      | 2751/6855 [09:50<14:30,  4.72it/s]

Processing tickers:  40%|████      | 2752/6855 [09:51<14:21,  4.76it/s]

Processing tickers:  40%|████      | 2753/6855 [09:51<14:15,  4.80it/s]

Processing tickers:  40%|████      | 2754/6855 [09:51<14:11,  4.82it/s]

Processing tickers:  40%|████      | 2755/6855 [09:51<14:09,  4.83it/s]

Processing tickers:  40%|████      | 2756/6855 [09:51<14:35,  4.68it/s]

Processing tickers:  40%|████      | 2757/6855 [09:52<14:33,  4.69it/s]

Processing tickers:  40%|████      | 2758/6855 [09:52<14:29,  4.71it/s]

Processing tickers:  40%|████      | 2759/6855 [09:52<14:29,  4.71it/s]

Processing tickers:  40%|████      | 2760/6855 [09:52<14:50,  4.60it/s]

Processing tickers:  40%|████      | 2761/6855 [09:53<14:35,  4.68it/s]

Processing tickers:  40%|████      | 2762/6855 [09:53<14:32,  4.69it/s]

Processing tickers:  40%|████      | 2763/6855 [09:53<14:40,  4.65it/s]

Processing tickers:  40%|████      | 2764/6855 [09:53<14:38,  4.66it/s]

Processing tickers:  40%|████      | 2765/6855 [09:53<14:40,  4.64it/s]

Processing tickers:  40%|████      | 2766/6855 [09:54<14:54,  4.57it/s]

Processing tickers:  40%|████      | 2767/6855 [09:54<14:46,  4.61it/s]

Processing tickers:  40%|████      | 2768/6855 [09:54<14:39,  4.65it/s]

Processing tickers:  40%|████      | 2769/6855 [09:54<14:32,  4.68it/s]

Processing tickers:  40%|████      | 2770/6855 [09:54<14:22,  4.74it/s]

Processing tickers:  40%|████      | 2771/6855 [09:55<14:24,  4.73it/s]

Processing tickers:  40%|████      | 2772/6855 [09:55<14:33,  4.68it/s]

Processing tickers:  40%|████      | 2773/6855 [09:55<14:23,  4.73it/s]

Processing tickers:  40%|████      | 2774/6855 [09:55<14:53,  4.57it/s]

Processing tickers:  40%|████      | 2775/6855 [09:56<14:42,  4.62it/s]

Processing tickers:  40%|████      | 2776/6855 [09:56<14:38,  4.64it/s]

Processing tickers:  41%|████      | 2777/6855 [09:56<14:26,  4.71it/s]

Processing tickers:  41%|████      | 2778/6855 [09:56<14:30,  4.68it/s]

Processing tickers:  41%|████      | 2779/6855 [09:56<14:31,  4.68it/s]

Processing tickers:  41%|████      | 2780/6855 [09:57<14:55,  4.55it/s]

Processing tickers:  41%|████      | 2781/6855 [09:57<15:05,  4.50it/s]

Processing tickers:  41%|████      | 2782/6855 [09:57<14:47,  4.59it/s]

Processing tickers:  41%|████      | 2783/6855 [09:57<14:31,  4.67it/s]

Processing tickers:  41%|████      | 2784/6855 [09:57<14:22,  4.72it/s]

Processing tickers:  41%|████      | 2785/6855 [09:58<14:32,  4.66it/s]

Processing tickers:  41%|████      | 2786/6855 [09:58<14:31,  4.67it/s]

Processing tickers:  41%|████      | 2787/6855 [09:58<14:27,  4.69it/s]

Processing tickers:  41%|████      | 2788/6855 [09:58<14:24,  4.70it/s]

Processing tickers:  41%|████      | 2789/6855 [09:59<14:15,  4.75it/s]

Processing tickers:  41%|████      | 2790/6855 [09:59<14:05,  4.81it/s]

Processing tickers:  41%|████      | 2791/6855 [09:59<14:04,  4.81it/s]

Processing tickers:  41%|████      | 2792/6855 [09:59<14:31,  4.66it/s]

Processing tickers:  41%|████      | 2793/6855 [09:59<14:45,  4.59it/s]

Processing tickers:  41%|████      | 2794/6855 [10:00<14:58,  4.52it/s]

Processing tickers:  41%|████      | 2795/6855 [10:00<14:49,  4.57it/s]

Processing tickers:  41%|████      | 2796/6855 [10:00<14:38,  4.62it/s]

Processing tickers:  41%|████      | 2797/6855 [10:00<14:35,  4.63it/s]

Processing tickers:  41%|████      | 2798/6855 [10:01<14:29,  4.67it/s]

Processing tickers:  41%|████      | 2799/6855 [10:01<14:25,  4.69it/s]

Processing tickers:  41%|████      | 2800/6855 [10:01<14:16,  4.73it/s]

Processing tickers:  41%|████      | 2801/6855 [10:01<14:10,  4.77it/s]

Processing tickers:  41%|████      | 2802/6855 [10:01<14:16,  4.73it/s]

Processing tickers:  41%|████      | 2803/6855 [10:02<14:09,  4.77it/s]

Processing tickers:  41%|████      | 2804/6855 [10:02<14:04,  4.80it/s]

Processing tickers:  41%|████      | 2805/6855 [10:02<14:34,  4.63it/s]

Processing tickers:  41%|████      | 2806/6855 [10:02<15:07,  4.46it/s]

Processing tickers:  41%|████      | 2807/6855 [10:02<14:47,  4.56it/s]

Processing tickers:  41%|████      | 2808/6855 [10:03<14:32,  4.64it/s]

Processing tickers:  41%|████      | 2809/6855 [10:03<14:23,  4.68it/s]

Processing tickers:  41%|████      | 2810/6855 [10:03<14:16,  4.72it/s]

Processing tickers:  41%|████      | 2811/6855 [10:03<14:27,  4.66it/s]

Processing tickers:  41%|████      | 2812/6855 [10:03<14:24,  4.68it/s]

Processing tickers:  41%|████      | 2813/6855 [10:04<14:17,  4.71it/s]

Processing tickers:  41%|████      | 2814/6855 [10:04<14:13,  4.73it/s]

Processing tickers:  41%|████      | 2815/6855 [10:04<14:13,  4.74it/s]

Processing tickers:  41%|████      | 2816/6855 [10:04<14:17,  4.71it/s]

Processing tickers:  41%|████      | 2817/6855 [10:05<14:06,  4.77it/s]

Processing tickers:  41%|████      | 2818/6855 [10:05<14:39,  4.59it/s]

Processing tickers:  41%|████      | 2819/6855 [10:05<14:47,  4.55it/s]

Processing tickers:  41%|████      | 2820/6855 [10:05<14:51,  4.52it/s]

Processing tickers:  41%|████      | 2821/6855 [10:05<14:50,  4.53it/s]

Processing tickers:  41%|████      | 2822/6855 [10:06<14:36,  4.60it/s]

Processing tickers:  41%|████      | 2823/6855 [10:06<14:23,  4.67it/s]

Processing tickers:  41%|████      | 2824/6855 [10:06<14:21,  4.68it/s]

Processing tickers:  41%|████      | 2825/6855 [10:06<14:14,  4.71it/s]

Processing tickers:  41%|████      | 2826/6855 [10:06<14:04,  4.77it/s]

Processing tickers:  41%|████      | 2827/6855 [10:07<14:03,  4.77it/s]

Processing tickers:  41%|████▏     | 2828/6855 [10:07<14:13,  4.72it/s]

Processing tickers:  41%|████▏     | 2829/6855 [10:07<14:01,  4.78it/s]

Processing tickers:  41%|████▏     | 2830/6855 [10:07<14:17,  4.70it/s]

Processing tickers:  41%|████▏     | 2831/6855 [10:08<14:31,  4.62it/s]

Processing tickers:  41%|████▏     | 2832/6855 [10:08<14:27,  4.64it/s]

Processing tickers:  41%|████▏     | 2833/6855 [10:08<14:14,  4.70it/s]

Processing tickers:  41%|████▏     | 2834/6855 [10:08<14:14,  4.71it/s]

Processing tickers:  41%|████▏     | 2835/6855 [10:08<14:04,  4.76it/s]

Processing tickers:  41%|████▏     | 2836/6855 [10:09<14:12,  4.72it/s]

Processing tickers:  41%|████▏     | 2837/6855 [10:09<14:07,  4.74it/s]

Processing tickers:  41%|████▏     | 2838/6855 [10:09<13:58,  4.79it/s]

Processing tickers:  41%|████▏     | 2839/6855 [10:09<13:57,  4.79it/s]

Processing tickers:  41%|████▏     | 2840/6855 [10:09<14:11,  4.72it/s]

Processing tickers:  41%|████▏     | 2841/6855 [10:10<14:05,  4.75it/s]

Processing tickers:  41%|████▏     | 2842/6855 [10:10<13:58,  4.79it/s]

Processing tickers:  41%|████▏     | 2843/6855 [10:10<13:57,  4.79it/s]

Processing tickers:  41%|████▏     | 2844/6855 [10:10<14:02,  4.76it/s]

Processing tickers:  42%|████▏     | 2845/6855 [10:10<14:01,  4.76it/s]

Processing tickers:  42%|████▏     | 2846/6855 [10:11<14:15,  4.68it/s]

Processing tickers:  42%|████▏     | 2847/6855 [10:11<14:06,  4.73it/s]

Processing tickers:  42%|████▏     | 2848/6855 [10:11<14:10,  4.71it/s]

Processing tickers:  42%|████▏     | 2849/6855 [10:11<14:03,  4.75it/s]

Processing tickers:  42%|████▏     | 2850/6855 [10:12<14:01,  4.76it/s]

Processing tickers:  42%|████▏     | 2851/6855 [10:12<13:55,  4.79it/s]

Processing tickers:  42%|████▏     | 2852/6855 [10:12<14:21,  4.65it/s]

Processing tickers:  42%|████▏     | 2853/6855 [10:12<14:21,  4.64it/s]

Processing tickers:  42%|████▏     | 2854/6855 [10:12<14:44,  4.53it/s]

Processing tickers:  42%|████▏     | 2855/6855 [10:13<14:32,  4.59it/s]

Processing tickers:  42%|████▏     | 2856/6855 [10:13<14:14,  4.68it/s]

Processing tickers:  42%|████▏     | 2857/6855 [10:13<14:07,  4.72it/s]

Processing tickers:  42%|████▏     | 2858/6855 [10:13<14:07,  4.72it/s]

Processing tickers:  42%|████▏     | 2859/6855 [10:14<14:34,  4.57it/s]

Processing tickers:  42%|████▏     | 2860/6855 [10:14<14:16,  4.67it/s]

Processing tickers:  42%|████▏     | 2861/6855 [10:14<14:10,  4.70it/s]

Processing tickers:  42%|████▏     | 2862/6855 [10:14<14:19,  4.65it/s]

Processing tickers:  42%|████▏     | 2863/6855 [10:14<14:16,  4.66it/s]

Processing tickers:  42%|████▏     | 2864/6855 [10:15<14:05,  4.72it/s]

Processing tickers:  42%|████▏     | 2865/6855 [10:15<14:00,  4.75it/s]

Processing tickers:  42%|████▏     | 2866/6855 [10:15<14:01,  4.74it/s]

Processing tickers:  42%|████▏     | 2867/6855 [10:15<14:21,  4.63it/s]

Processing tickers:  42%|████▏     | 2868/6855 [10:15<14:41,  4.52it/s]

Processing tickers:  42%|████▏     | 2869/6855 [10:16<14:54,  4.45it/s]

Processing tickers:  42%|████▏     | 2870/6855 [10:16<14:36,  4.55it/s]

Processing tickers:  42%|████▏     | 2871/6855 [10:16<14:28,  4.59it/s]

Processing tickers:  42%|████▏     | 2872/6855 [10:16<14:21,  4.62it/s]

Processing tickers:  42%|████▏     | 2873/6855 [10:17<14:13,  4.66it/s]

Processing tickers:  42%|████▏     | 2874/6855 [10:17<14:07,  4.70it/s]

Processing tickers:  42%|████▏     | 2875/6855 [10:17<14:04,  4.72it/s]

Processing tickers:  42%|████▏     | 2876/6855 [10:17<13:57,  4.75it/s]

Processing tickers:  42%|████▏     | 2877/6855 [10:17<13:53,  4.78it/s]

Processing tickers:  42%|████▏     | 2878/6855 [10:18<14:05,  4.71it/s]

Processing tickers:  42%|████▏     | 2879/6855 [10:18<14:24,  4.60it/s]

Processing tickers:  42%|████▏     | 2880/6855 [10:18<14:10,  4.67it/s]

Processing tickers:  42%|████▏     | 2881/6855 [10:18<14:28,  4.58it/s]

Processing tickers:  42%|████▏     | 2882/6855 [10:18<14:23,  4.60it/s]

Processing tickers:  42%|████▏     | 2883/6855 [10:19<14:10,  4.67it/s]

Processing tickers:  42%|████▏     | 2884/6855 [10:19<14:02,  4.71it/s]

Processing tickers:  42%|████▏     | 2885/6855 [10:19<13:59,  4.73it/s]

Processing tickers:  42%|████▏     | 2886/6855 [10:19<13:53,  4.76it/s]

Processing tickers:  42%|████▏     | 2887/6855 [10:19<13:55,  4.75it/s]

Processing tickers:  42%|████▏     | 2888/6855 [10:20<14:02,  4.71it/s]

Processing tickers:  42%|████▏     | 2889/6855 [10:20<13:54,  4.75it/s]

Processing tickers:  42%|████▏     | 2890/6855 [10:20<13:53,  4.76it/s]

Processing tickers:  42%|████▏     | 2891/6855 [10:20<13:52,  4.76it/s]

Processing tickers:  42%|████▏     | 2892/6855 [10:21<14:09,  4.66it/s]

Processing tickers:  42%|████▏     | 2893/6855 [10:21<14:00,  4.71it/s]

Processing tickers:  42%|████▏     | 2894/6855 [10:21<14:11,  4.65it/s]

Processing tickers:  42%|████▏     | 2895/6855 [10:21<14:11,  4.65it/s]

Processing tickers:  42%|████▏     | 2896/6855 [10:21<14:15,  4.63it/s]

Processing tickers:  42%|████▏     | 2897/6855 [10:22<14:11,  4.65it/s]

Processing tickers:  42%|████▏     | 2898/6855 [10:22<14:23,  4.58it/s]

Processing tickers:  42%|████▏     | 2899/6855 [10:22<14:36,  4.52it/s]

Processing tickers:  42%|████▏     | 2900/6855 [10:22<14:19,  4.60it/s]

Processing tickers:  42%|████▏     | 2901/6855 [10:23<14:05,  4.67it/s]

Processing tickers:  42%|████▏     | 2902/6855 [10:23<13:57,  4.72it/s]

Processing tickers:  42%|████▏     | 2903/6855 [10:23<13:51,  4.75it/s]

Processing tickers:  42%|████▏     | 2904/6855 [10:23<13:49,  4.76it/s]

Processing tickers:  42%|████▏     | 2905/6855 [10:23<13:48,  4.77it/s]

Processing tickers:  42%|████▏     | 2906/6855 [10:24<13:43,  4.79it/s]

Processing tickers:  42%|████▏     | 2907/6855 [10:24<13:48,  4.76it/s]

Processing tickers:  42%|████▏     | 2908/6855 [10:24<13:50,  4.75it/s]

Processing tickers:  42%|████▏     | 2909/6855 [10:24<13:52,  4.74it/s]

Processing tickers:  42%|████▏     | 2910/6855 [10:24<14:26,  4.55it/s]

Processing tickers:  42%|████▏     | 2911/6855 [10:25<14:22,  4.57it/s]

Processing tickers:  42%|████▏     | 2912/6855 [10:25<14:11,  4.63it/s]

Processing tickers:  42%|████▏     | 2913/6855 [10:25<14:03,  4.67it/s]

Processing tickers:  43%|████▎     | 2914/6855 [10:25<13:55,  4.72it/s]

Processing tickers:  43%|████▎     | 2915/6855 [10:25<13:48,  4.76it/s]

Processing tickers:  43%|████▎     | 2916/6855 [10:26<14:05,  4.66it/s]

Processing tickers:  43%|████▎     | 2917/6855 [10:26<14:02,  4.68it/s]

Processing tickers:  43%|████▎     | 2918/6855 [10:26<13:50,  4.74it/s]

Processing tickers:  43%|████▎     | 2919/6855 [10:26<13:50,  4.74it/s]

Processing tickers:  43%|████▎     | 2920/6855 [10:27<13:42,  4.78it/s]

Processing tickers:  43%|████▎     | 2921/6855 [10:27<13:44,  4.77it/s]

Processing tickers:  43%|████▎     | 2922/6855 [10:27<13:45,  4.77it/s]

Processing tickers:  43%|████▎     | 2923/6855 [10:27<13:44,  4.77it/s]

Processing tickers:  43%|████▎     | 2924/6855 [10:27<13:42,  4.78it/s]

Processing tickers:  43%|████▎     | 2925/6855 [10:28<14:06,  4.64it/s]

Processing tickers:  43%|████▎     | 2926/6855 [10:28<13:53,  4.72it/s]

Processing tickers:  43%|████▎     | 2927/6855 [10:28<14:09,  4.62it/s]

Processing tickers:  43%|████▎     | 2928/6855 [10:28<14:07,  4.64it/s]

Processing tickers:  43%|████▎     | 2929/6855 [10:28<13:56,  4.69it/s]

Processing tickers:  43%|████▎     | 2930/6855 [10:29<13:52,  4.71it/s]

Processing tickers:  43%|████▎     | 2931/6855 [10:29<14:06,  4.64it/s]

Processing tickers:  43%|████▎     | 2932/6855 [10:29<13:57,  4.69it/s]

Processing tickers:  43%|████▎     | 2933/6855 [10:29<13:47,  4.74it/s]

Processing tickers:  43%|████▎     | 2934/6855 [10:30<13:48,  4.73it/s]

Processing tickers:  43%|████▎     | 2935/6855 [10:30<13:45,  4.75it/s]

Processing tickers:  43%|████▎     | 2936/6855 [10:30<13:47,  4.73it/s]

Processing tickers:  43%|████▎     | 2937/6855 [10:30<14:12,  4.59it/s]

Processing tickers:  43%|████▎     | 2938/6855 [10:30<13:59,  4.67it/s]

Processing tickers:  43%|████▎     | 2939/6855 [10:31<13:53,  4.70it/s]

Processing tickers:  43%|████▎     | 2940/6855 [10:31<13:43,  4.75it/s]

Processing tickers:  43%|████▎     | 2941/6855 [10:31<13:58,  4.67it/s]

Processing tickers:  43%|████▎     | 2942/6855 [10:31<14:01,  4.65it/s]

Processing tickers:  43%|████▎     | 2943/6855 [10:31<13:53,  4.69it/s]

Processing tickers:  43%|████▎     | 2944/6855 [10:32<13:53,  4.69it/s]

Processing tickers:  43%|████▎     | 2945/6855 [10:32<13:45,  4.74it/s]

Processing tickers:  43%|████▎     | 2946/6855 [10:32<13:47,  4.72it/s]

Processing tickers:  43%|████▎     | 2947/6855 [10:32<14:07,  4.61it/s]

Processing tickers:  43%|████▎     | 2948/6855 [10:32<13:53,  4.69it/s]

Processing tickers:  43%|████▎     | 2949/6855 [10:33<14:10,  4.59it/s]

Processing tickers:  43%|████▎     | 2950/6855 [10:33<13:59,  4.65it/s]

Processing tickers:  43%|████▎     | 2951/6855 [10:33<14:19,  4.54it/s]

Processing tickers:  43%|████▎     | 2952/6855 [10:33<14:06,  4.61it/s]

Processing tickers:  43%|████▎     | 2953/6855 [10:34<13:57,  4.66it/s]

Processing tickers:  43%|████▎     | 2954/6855 [10:34<13:47,  4.71it/s]

Processing tickers:  43%|████▎     | 2955/6855 [10:34<13:38,  4.77it/s]

Processing tickers:  43%|████▎     | 2956/6855 [10:34<13:52,  4.68it/s]

Processing tickers:  43%|████▎     | 2957/6855 [10:34<14:08,  4.59it/s]

Processing tickers:  43%|████▎     | 2958/6855 [10:35<14:00,  4.63it/s]

Processing tickers:  43%|████▎     | 2959/6855 [10:35<13:51,  4.69it/s]

Processing tickers:  43%|████▎     | 2960/6855 [10:35<13:47,  4.71it/s]

Processing tickers:  43%|████▎     | 2961/6855 [10:35<13:43,  4.73it/s]

Processing tickers:  43%|████▎     | 2962/6855 [10:36<14:09,  4.58it/s]

Processing tickers:  43%|████▎     | 2963/6855 [10:36<14:06,  4.60it/s]

Processing tickers:  43%|████▎     | 2964/6855 [10:36<14:01,  4.62it/s]

Processing tickers:  43%|████▎     | 2965/6855 [10:36<13:52,  4.68it/s]

Processing tickers:  43%|████▎     | 2966/6855 [10:36<13:43,  4.73it/s]

Processing tickers:  43%|████▎     | 2967/6855 [10:37<13:37,  4.76it/s]

Processing tickers:  43%|████▎     | 2968/6855 [10:37<13:32,  4.78it/s]

Processing tickers:  43%|████▎     | 2969/6855 [10:37<13:34,  4.77it/s]

Processing tickers:  43%|████▎     | 2970/6855 [10:37<13:51,  4.67it/s]

Processing tickers:  43%|████▎     | 2971/6855 [10:37<13:44,  4.71it/s]

Processing tickers:  43%|████▎     | 2972/6855 [10:38<13:56,  4.64it/s]

Processing tickers:  43%|████▎     | 2973/6855 [10:38<13:49,  4.68it/s]

Processing tickers:  43%|████▎     | 2974/6855 [10:38<13:42,  4.72it/s]

Processing tickers:  43%|████▎     | 2975/6855 [10:38<13:34,  4.77it/s]

Processing tickers:  43%|████▎     | 2976/6855 [10:38<13:29,  4.79it/s]

Processing tickers:  43%|████▎     | 2977/6855 [10:39<13:33,  4.77it/s]

Processing tickers:  43%|████▎     | 2978/6855 [10:39<13:34,  4.76it/s]

Processing tickers:  43%|████▎     | 2979/6855 [10:39<13:34,  4.76it/s]

Processing tickers:  43%|████▎     | 2980/6855 [10:39<13:40,  4.72it/s]

Processing tickers:  43%|████▎     | 2981/6855 [10:40<13:37,  4.74it/s]

Processing tickers:  44%|████▎     | 2982/6855 [10:40<13:36,  4.74it/s]

Processing tickers:  44%|████▎     | 2983/6855 [10:40<13:37,  4.74it/s]

Processing tickers:  44%|████▎     | 2984/6855 [10:40<13:32,  4.76it/s]

Processing tickers:  44%|████▎     | 2985/6855 [10:40<13:30,  4.77it/s]

Processing tickers:  44%|████▎     | 2986/6855 [10:41<13:28,  4.79it/s]

Processing tickers:  44%|████▎     | 2987/6855 [10:41<13:34,  4.75it/s]

Processing tickers:  44%|████▎     | 2988/6855 [10:41<13:38,  4.72it/s]

Processing tickers:  44%|████▎     | 2989/6855 [10:41<13:43,  4.70it/s]

Processing tickers:  44%|████▎     | 2990/6855 [10:41<13:37,  4.73it/s]

Processing tickers:  44%|████▎     | 2991/6855 [10:42<13:34,  4.75it/s]

Processing tickers:  44%|████▎     | 2992/6855 [10:42<13:38,  4.72it/s]

Processing tickers:  44%|████▎     | 2993/6855 [10:42<13:35,  4.74it/s]

Processing tickers:  44%|████▎     | 2994/6855 [10:42<13:33,  4.75it/s]

Processing tickers:  44%|████▎     | 2995/6855 [10:42<13:31,  4.76it/s]

Processing tickers:  44%|████▎     | 2996/6855 [10:43<13:26,  4.78it/s]

Processing tickers:  44%|████▎     | 2997/6855 [10:43<13:19,  4.82it/s]

Processing tickers:  44%|████▎     | 2998/6855 [10:43<13:21,  4.81it/s]

Processing tickers:  44%|████▎     | 2999/6855 [10:43<13:20,  4.82it/s]

Processing tickers:  44%|████▍     | 3000/6855 [10:44<13:22,  4.80it/s]

Processing tickers:  44%|████▍     | 3001/6855 [10:44<13:28,  4.76it/s]

Processing tickers:  44%|████▍     | 3002/6855 [10:44<13:58,  4.60it/s]

Processing tickers:  44%|████▍     | 3003/6855 [10:44<13:53,  4.62it/s]

Processing tickers:  44%|████▍     | 3004/6855 [10:44<13:47,  4.65it/s]

Processing tickers:  44%|████▍     | 3005/6855 [10:45<13:39,  4.70it/s]

Processing tickers:  44%|████▍     | 3006/6855 [10:45<13:36,  4.71it/s]

Processing tickers:  44%|████▍     | 3007/6855 [10:45<13:28,  4.76it/s]

Processing tickers:  44%|████▍     | 3008/6855 [10:45<13:31,  4.74it/s]

Processing tickers:  44%|████▍     | 3009/6855 [10:45<13:32,  4.73it/s]

Processing tickers:  44%|████▍     | 3010/6855 [10:46<13:35,  4.71it/s]

Processing tickers:  44%|████▍     | 3011/6855 [10:46<13:30,  4.74it/s]

Processing tickers:  44%|████▍     | 3012/6855 [10:46<13:32,  4.73it/s]

Processing tickers:  44%|████▍     | 3013/6855 [10:46<13:31,  4.74it/s]

Processing tickers:  44%|████▍     | 3014/6855 [10:46<13:29,  4.74it/s]

Processing tickers:  44%|████▍     | 3015/6855 [10:47<13:24,  4.77it/s]

Processing tickers:  44%|████▍     | 3016/6855 [10:47<13:24,  4.77it/s]

Processing tickers:  44%|████▍     | 3017/6855 [10:47<13:26,  4.76it/s]

Processing tickers:  44%|████▍     | 3018/6855 [10:47<13:25,  4.77it/s]

Processing tickers:  44%|████▍     | 3019/6855 [10:48<13:37,  4.69it/s]

Processing tickers:  44%|████▍     | 3020/6855 [10:48<13:57,  4.58it/s]

Processing tickers:  44%|████▍     | 3021/6855 [10:48<13:49,  4.62it/s]

Processing tickers:  44%|████▍     | 3022/6855 [10:48<14:07,  4.52it/s]

Processing tickers:  44%|████▍     | 3023/6855 [10:48<14:08,  4.52it/s]

Processing tickers:  44%|████▍     | 3024/6855 [10:49<14:13,  4.49it/s]

Processing tickers:  44%|████▍     | 3025/6855 [10:49<15:19,  4.16it/s]

Processing tickers:  44%|████▍     | 3026/6855 [10:49<14:41,  4.34it/s]

Processing tickers:  44%|████▍     | 3027/6855 [10:49<14:13,  4.48it/s]

Processing tickers:  44%|████▍     | 3028/6855 [10:50<13:55,  4.58it/s]

Processing tickers:  44%|████▍     | 3029/6855 [10:50<13:49,  4.61it/s]

Processing tickers:  44%|████▍     | 3030/6855 [10:50<13:36,  4.68it/s]

Processing tickers:  44%|████▍     | 3031/6855 [10:50<13:35,  4.69it/s]

Processing tickers:  44%|████▍     | 3032/6855 [10:50<13:40,  4.66it/s]

Processing tickers:  44%|████▍     | 3033/6855 [10:51<13:43,  4.64it/s]

Processing tickers:  44%|████▍     | 3034/6855 [10:51<13:41,  4.65it/s]

Processing tickers:  44%|████▍     | 3035/6855 [10:51<13:36,  4.68it/s]

Processing tickers:  44%|████▍     | 3036/6855 [10:51<13:43,  4.64it/s]

Processing tickers:  44%|████▍     | 3037/6855 [10:51<13:43,  4.64it/s]

Processing tickers:  44%|████▍     | 3038/6855 [10:52<13:36,  4.67it/s]

Processing tickers:  44%|████▍     | 3039/6855 [10:52<13:29,  4.71it/s]

Processing tickers:  44%|████▍     | 3040/6855 [10:52<13:23,  4.75it/s]

Processing tickers:  44%|████▍     | 3041/6855 [10:52<13:48,  4.60it/s]

Processing tickers:  44%|████▍     | 3042/6855 [10:53<13:34,  4.68it/s]

Processing tickers:  44%|████▍     | 3043/6855 [10:53<13:22,  4.75it/s]

Processing tickers:  44%|████▍     | 3044/6855 [10:53<13:34,  4.68it/s]

Processing tickers:  44%|████▍     | 3045/6855 [10:53<13:40,  4.64it/s]

Processing tickers:  44%|████▍     | 3046/6855 [10:53<13:35,  4.67it/s]

Processing tickers:  44%|████▍     | 3047/6855 [10:54<13:34,  4.68it/s]

Processing tickers:  44%|████▍     | 3048/6855 [10:54<14:29,  4.38it/s]

Processing tickers:  44%|████▍     | 3049/6855 [10:54<14:27,  4.39it/s]

Processing tickers:  44%|████▍     | 3050/6855 [10:54<14:11,  4.47it/s]

Processing tickers:  45%|████▍     | 3051/6855 [10:55<14:01,  4.52it/s]

Processing tickers:  45%|████▍     | 3052/6855 [10:55<13:41,  4.63it/s]

Processing tickers:  45%|████▍     | 3053/6855 [10:55<13:42,  4.62it/s]

Processing tickers:  45%|████▍     | 3054/6855 [10:55<13:33,  4.67it/s]

Processing tickers:  45%|████▍     | 3055/6855 [10:55<13:29,  4.70it/s]

Processing tickers:  45%|████▍     | 3056/6855 [10:56<13:33,  4.67it/s]

Processing tickers:  45%|████▍     | 3057/6855 [10:56<13:33,  4.67it/s]

Processing tickers:  45%|████▍     | 3058/6855 [10:56<13:29,  4.69it/s]

Processing tickers:  45%|████▍     | 3059/6855 [10:56<13:28,  4.70it/s]

Processing tickers:  45%|████▍     | 3060/6855 [10:56<13:29,  4.69it/s]

Processing tickers:  45%|████▍     | 3061/6855 [10:57<13:28,  4.69it/s]

Processing tickers:  45%|████▍     | 3062/6855 [10:57<13:19,  4.74it/s]

Processing tickers:  45%|████▍     | 3063/6855 [10:57<13:18,  4.75it/s]

Processing tickers:  45%|████▍     | 3064/6855 [10:57<13:29,  4.68it/s]

Processing tickers:  45%|████▍     | 3065/6855 [10:58<13:23,  4.72it/s]

Processing tickers:  45%|████▍     | 3066/6855 [10:58<13:19,  4.74it/s]

Processing tickers:  45%|████▍     | 3067/6855 [10:58<13:20,  4.73it/s]

Processing tickers:  45%|████▍     | 3068/6855 [10:58<13:16,  4.75it/s]

Processing tickers:  45%|████▍     | 3069/6855 [10:58<13:10,  4.79it/s]

Processing tickers:  45%|████▍     | 3070/6855 [10:59<13:10,  4.79it/s]

Processing tickers:  45%|████▍     | 3071/6855 [10:59<13:06,  4.81it/s]

Processing tickers:  45%|████▍     | 3072/6855 [10:59<13:38,  4.62it/s]

Processing tickers:  45%|████▍     | 3073/6855 [10:59<13:53,  4.54it/s]

Processing tickers:  45%|████▍     | 3074/6855 [10:59<13:46,  4.58it/s]

Processing tickers:  45%|████▍     | 3075/6855 [11:00<13:42,  4.60it/s]

Processing tickers:  45%|████▍     | 3076/6855 [11:00<13:35,  4.63it/s]

Processing tickers:  45%|████▍     | 3077/6855 [11:00<13:44,  4.58it/s]

Processing tickers:  45%|████▍     | 3078/6855 [11:00<13:36,  4.63it/s]

Processing tickers:  45%|████▍     | 3079/6855 [11:01<13:43,  4.58it/s]

Processing tickers:  45%|████▍     | 3080/6855 [11:01<13:34,  4.63it/s]

Processing tickers:  45%|████▍     | 3081/6855 [11:01<13:29,  4.66it/s]

Processing tickers:  45%|████▍     | 3082/6855 [11:01<13:23,  4.70it/s]

Processing tickers:  45%|████▍     | 3083/6855 [11:01<13:21,  4.71it/s]

Processing tickers:  45%|████▍     | 3084/6855 [11:02<13:13,  4.75it/s]

Processing tickers:  45%|████▌     | 3085/6855 [11:02<13:05,  4.80it/s]

Processing tickers:  45%|████▌     | 3086/6855 [11:02<13:08,  4.78it/s]

Processing tickers:  45%|████▌     | 3087/6855 [11:02<13:22,  4.70it/s]

Processing tickers:  45%|████▌     | 3088/6855 [11:02<13:21,  4.70it/s]

Processing tickers:  45%|████▌     | 3089/6855 [11:03<13:12,  4.75it/s]

Processing tickers:  45%|████▌     | 3090/6855 [11:03<13:37,  4.61it/s]

Processing tickers:  45%|████▌     | 3091/6855 [11:03<13:27,  4.66it/s]

Processing tickers:  45%|████▌     | 3092/6855 [11:03<13:22,  4.69it/s]

Processing tickers:  45%|████▌     | 3093/6855 [11:04<13:32,  4.63it/s]

Processing tickers:  45%|████▌     | 3094/6855 [11:04<13:50,  4.53it/s]

Processing tickers:  45%|████▌     | 3095/6855 [11:04<13:39,  4.59it/s]

Processing tickers:  45%|████▌     | 3096/6855 [11:04<13:31,  4.63it/s]

Processing tickers:  45%|████▌     | 3097/6855 [11:04<13:27,  4.65it/s]

Processing tickers:  45%|████▌     | 3098/6855 [11:05<13:25,  4.66it/s]

Processing tickers:  45%|████▌     | 3099/6855 [11:05<13:17,  4.71it/s]

Processing tickers:  45%|████▌     | 3100/6855 [11:05<13:12,  4.74it/s]

Processing tickers:  45%|████▌     | 3101/6855 [11:05<13:35,  4.60it/s]

Processing tickers:  45%|████▌     | 3102/6855 [11:05<13:26,  4.66it/s]

Processing tickers:  45%|████▌     | 3103/6855 [11:06<13:19,  4.69it/s]

Processing tickers:  45%|████▌     | 3104/6855 [11:06<13:13,  4.73it/s]

Processing tickers:  45%|████▌     | 3105/6855 [11:06<13:18,  4.70it/s]

Processing tickers:  45%|████▌     | 3106/6855 [11:06<13:15,  4.71it/s]

Processing tickers:  45%|████▌     | 3107/6855 [11:06<13:08,  4.76it/s]

Processing tickers:  45%|████▌     | 3108/6855 [11:07<13:09,  4.75it/s]

Processing tickers:  45%|████▌     | 3109/6855 [11:07<13:13,  4.72it/s]

Processing tickers:  45%|████▌     | 3110/6855 [11:07<13:08,  4.75it/s]

Processing tickers:  45%|████▌     | 3111/6855 [11:07<13:03,  4.78it/s]

Processing tickers:  45%|████▌     | 3112/6855 [11:08<13:08,  4.75it/s]

Processing tickers:  45%|████▌     | 3113/6855 [11:08<13:04,  4.77it/s]

Processing tickers:  45%|████▌     | 3114/6855 [11:08<13:19,  4.68it/s]

Processing tickers:  45%|████▌     | 3115/6855 [11:08<13:15,  4.70it/s]

Processing tickers:  45%|████▌     | 3116/6855 [11:08<13:29,  4.62it/s]

Processing tickers:  45%|████▌     | 3117/6855 [11:09<13:41,  4.55it/s]

Processing tickers:  45%|████▌     | 3118/6855 [11:09<13:27,  4.63it/s]

Processing tickers:  45%|████▌     | 3119/6855 [11:09<13:19,  4.67it/s]

Processing tickers:  46%|████▌     | 3120/6855 [11:09<13:16,  4.69it/s]

Processing tickers:  46%|████▌     | 3121/6855 [11:09<13:10,  4.72it/s]

Processing tickers:  46%|████▌     | 3122/6855 [11:10<13:07,  4.74it/s]

Processing tickers:  46%|████▌     | 3123/6855 [11:10<13:02,  4.77it/s]

Processing tickers:  46%|████▌     | 3124/6855 [11:10<13:01,  4.77it/s]

Processing tickers:  46%|████▌     | 3125/6855 [11:10<13:04,  4.76it/s]

Processing tickers:  46%|████▌     | 3126/6855 [11:11<13:01,  4.77it/s]

Processing tickers:  46%|████▌     | 3127/6855 [11:11<13:03,  4.76it/s]

Processing tickers:  46%|████▌     | 3128/6855 [11:11<12:58,  4.79it/s]

Processing tickers:  46%|████▌     | 3129/6855 [11:11<12:54,  4.81it/s]

Processing tickers:  46%|████▌     | 3130/6855 [11:11<13:01,  4.77it/s]

Processing tickers:  46%|████▌     | 3131/6855 [11:12<13:03,  4.75it/s]

Processing tickers:  46%|████▌     | 3132/6855 [11:12<13:07,  4.73it/s]

Processing tickers:  46%|████▌     | 3133/6855 [11:12<13:05,  4.74it/s]

Processing tickers:  46%|████▌     | 3134/6855 [11:12<13:06,  4.73it/s]

Processing tickers:  46%|████▌     | 3135/6855 [11:12<13:07,  4.72it/s]

Processing tickers:  46%|████▌     | 3136/6855 [11:13<13:14,  4.68it/s]

Processing tickers:  46%|████▌     | 3137/6855 [11:13<13:10,  4.70it/s]

Processing tickers:  46%|████▌     | 3138/6855 [11:13<13:20,  4.64it/s]

Processing tickers:  46%|████▌     | 3139/6855 [11:13<13:37,  4.55it/s]

Processing tickers:  46%|████▌     | 3140/6855 [11:14<13:44,  4.51it/s]

Processing tickers:  46%|████▌     | 3141/6855 [11:14<13:40,  4.53it/s]

Processing tickers:  46%|████▌     | 3142/6855 [11:14<13:24,  4.62it/s]

Processing tickers:  46%|████▌     | 3143/6855 [11:14<13:19,  4.64it/s]

Processing tickers:  46%|████▌     | 3144/6855 [11:14<13:10,  4.69it/s]

Processing tickers:  46%|████▌     | 3145/6855 [11:15<13:10,  4.69it/s]

Processing tickers:  46%|████▌     | 3146/6855 [11:15<13:08,  4.70it/s]

Processing tickers:  46%|████▌     | 3147/6855 [11:15<13:09,  4.70it/s]

Processing tickers:  46%|████▌     | 3148/6855 [11:15<13:13,  4.67it/s]

Processing tickers:  46%|████▌     | 3149/6855 [11:15<13:14,  4.67it/s]

Processing tickers:  46%|████▌     | 3150/6855 [11:16<13:22,  4.62it/s]

Processing tickers:  46%|████▌     | 3151/6855 [11:16<13:09,  4.69it/s]

Processing tickers:  46%|████▌     | 3152/6855 [11:16<12:59,  4.75it/s]

Processing tickers:  46%|████▌     | 3153/6855 [11:16<12:58,  4.76it/s]

Processing tickers:  46%|████▌     | 3154/6855 [11:16<12:58,  4.75it/s]

Processing tickers:  46%|████▌     | 3155/6855 [11:17<13:00,  4.74it/s]

Processing tickers:  46%|████▌     | 3156/6855 [11:17<12:59,  4.75it/s]

Processing tickers:  46%|████▌     | 3157/6855 [11:17<12:58,  4.75it/s]

Processing tickers:  46%|████▌     | 3158/6855 [11:17<12:55,  4.77it/s]

Processing tickers:  46%|████▌     | 3159/6855 [11:18<13:00,  4.74it/s]

Processing tickers:  46%|████▌     | 3160/6855 [11:18<12:55,  4.76it/s]

Processing tickers:  46%|████▌     | 3161/6855 [11:18<13:03,  4.72it/s]

Processing tickers:  46%|████▌     | 3162/6855 [11:18<13:44,  4.48it/s]

Processing tickers:  46%|████▌     | 3163/6855 [11:18<13:54,  4.42it/s]

Processing tickers:  46%|████▌     | 3164/6855 [11:19<14:01,  4.39it/s]

Processing tickers:  46%|████▌     | 3165/6855 [11:19<13:35,  4.52it/s]

Processing tickers:  46%|████▌     | 3166/6855 [11:19<13:37,  4.51it/s]

Processing tickers:  46%|████▌     | 3167/6855 [11:19<13:44,  4.47it/s]

Processing tickers:  46%|████▌     | 3168/6855 [11:20<13:52,  4.43it/s]

Processing tickers:  46%|████▌     | 3169/6855 [11:20<13:37,  4.51it/s]

Processing tickers:  46%|████▌     | 3170/6855 [11:20<13:19,  4.61it/s]

Processing tickers:  46%|████▋     | 3171/6855 [11:20<13:25,  4.57it/s]

Processing tickers:  46%|████▋     | 3172/6855 [11:20<13:11,  4.65it/s]

Processing tickers:  46%|████▋     | 3173/6855 [11:21<13:07,  4.67it/s]

Processing tickers:  46%|████▋     | 3174/6855 [11:21<12:54,  4.75it/s]

Processing tickers:  46%|████▋     | 3175/6855 [11:21<12:52,  4.76it/s]

Processing tickers:  46%|████▋     | 3176/6855 [11:21<12:53,  4.75it/s]

Processing tickers:  46%|████▋     | 3177/6855 [11:21<12:53,  4.75it/s]

Processing tickers:  46%|████▋     | 3178/6855 [11:22<13:00,  4.71it/s]

Processing tickers:  46%|████▋     | 3179/6855 [11:22<12:58,  4.72it/s]

Processing tickers:  46%|████▋     | 3180/6855 [11:22<12:52,  4.76it/s]

Processing tickers:  46%|████▋     | 3181/6855 [11:22<12:54,  4.75it/s]

Processing tickers:  46%|████▋     | 3182/6855 [11:23<12:58,  4.72it/s]

Processing tickers:  46%|████▋     | 3183/6855 [11:23<13:07,  4.66it/s]

Processing tickers:  46%|████▋     | 3184/6855 [11:23<13:22,  4.57it/s]

Processing tickers:  46%|████▋     | 3185/6855 [11:23<13:16,  4.61it/s]

Processing tickers:  46%|████▋     | 3186/6855 [11:23<13:07,  4.66it/s]

Processing tickers:  46%|████▋     | 3187/6855 [11:24<13:16,  4.60it/s]

Processing tickers:  47%|████▋     | 3188/6855 [11:24<13:32,  4.51it/s]

Processing tickers:  47%|████▋     | 3189/6855 [11:24<13:35,  4.49it/s]

Processing tickers:  47%|████▋     | 3190/6855 [11:24<13:24,  4.56it/s]

Processing tickers:  47%|████▋     | 3191/6855 [11:24<13:15,  4.61it/s]

Processing tickers:  47%|████▋     | 3192/6855 [11:25<13:10,  4.64it/s]

Processing tickers:  47%|████▋     | 3193/6855 [11:25<13:19,  4.58it/s]

Processing tickers:  47%|████▋     | 3194/6855 [11:25<13:22,  4.56it/s]

Processing tickers:  47%|████▋     | 3195/6855 [11:25<13:07,  4.65it/s]

Processing tickers:  47%|████▋     | 3196/6855 [11:26<13:04,  4.67it/s]

Processing tickers:  47%|████▋     | 3197/6855 [11:26<12:53,  4.73it/s]

Processing tickers:  47%|████▋     | 3198/6855 [11:26<12:43,  4.79it/s]

Processing tickers:  47%|████▋     | 3199/6855 [11:26<13:13,  4.61it/s]

Processing tickers:  47%|████▋     | 3200/6855 [11:26<13:07,  4.64it/s]

Processing tickers:  47%|████▋     | 3201/6855 [11:27<12:57,  4.70it/s]

Processing tickers:  47%|████▋     | 3202/6855 [11:27<12:51,  4.74it/s]

Processing tickers:  47%|████▋     | 3203/6855 [11:27<13:04,  4.66it/s]

Processing tickers:  47%|████▋     | 3204/6855 [11:27<13:03,  4.66it/s]

Processing tickers:  47%|████▋     | 3205/6855 [11:27<12:56,  4.70it/s]

Processing tickers:  47%|████▋     | 3206/6855 [11:28<13:18,  4.57it/s]

Processing tickers:  47%|████▋     | 3207/6855 [11:28<13:09,  4.62it/s]

Processing tickers:  47%|████▋     | 3208/6855 [11:28<13:26,  4.52it/s]

Processing tickers:  47%|████▋     | 3209/6855 [11:28<13:39,  4.45it/s]

Processing tickers:  47%|████▋     | 3210/6855 [11:29<13:46,  4.41it/s]

Processing tickers:  47%|████▋     | 3211/6855 [11:29<13:29,  4.50it/s]

Processing tickers:  47%|████▋     | 3212/6855 [11:29<13:13,  4.59it/s]

Processing tickers:  47%|████▋     | 3213/6855 [11:29<13:20,  4.55it/s]

Processing tickers:  47%|████▋     | 3214/6855 [11:30<13:31,  4.49it/s]

Processing tickers:  47%|████▋     | 3215/6855 [11:30<13:12,  4.59it/s]

Processing tickers:  47%|████▋     | 3216/6855 [11:30<12:55,  4.69it/s]

Processing tickers:  47%|████▋     | 3217/6855 [11:30<12:45,  4.75it/s]

Processing tickers:  47%|████▋     | 3218/6855 [11:30<12:40,  4.78it/s]

Processing tickers:  47%|████▋     | 3219/6855 [11:31<12:34,  4.82it/s]

Processing tickers:  47%|████▋     | 3220/6855 [11:31<12:45,  4.75it/s]

Processing tickers:  47%|████▋     | 3221/6855 [11:31<13:12,  4.59it/s]

Processing tickers:  47%|████▋     | 3222/6855 [11:31<13:19,  4.55it/s]

Processing tickers:  47%|████▋     | 3223/6855 [11:31<12:58,  4.66it/s]

Processing tickers:  47%|████▋     | 3224/6855 [11:32<13:15,  4.57it/s]

Processing tickers:  47%|████▋     | 3225/6855 [11:32<13:03,  4.63it/s]

Processing tickers:  47%|████▋     | 3226/6855 [11:32<12:55,  4.68it/s]

Processing tickers:  47%|████▋     | 3227/6855 [11:32<12:57,  4.67it/s]

Processing tickers:  47%|████▋     | 3228/6855 [11:32<12:49,  4.71it/s]

Processing tickers:  47%|████▋     | 3229/6855 [11:33<12:43,  4.75it/s]

Processing tickers:  47%|████▋     | 3230/6855 [11:33<12:55,  4.68it/s]

Processing tickers:  47%|████▋     | 3231/6855 [11:33<12:43,  4.75it/s]

Processing tickers:  47%|████▋     | 3232/6855 [11:33<12:38,  4.77it/s]

Processing tickers:  47%|████▋     | 3233/6855 [11:34<12:38,  4.77it/s]

Processing tickers:  47%|████▋     | 3234/6855 [11:34<13:07,  4.60it/s]

Processing tickers:  47%|████▋     | 3235/6855 [11:34<13:19,  4.53it/s]

Processing tickers:  47%|████▋     | 3236/6855 [11:34<13:11,  4.58it/s]

Processing tickers:  47%|████▋     | 3237/6855 [11:34<13:02,  4.63it/s]

Processing tickers:  47%|████▋     | 3238/6855 [11:35<12:58,  4.64it/s]

Processing tickers:  47%|████▋     | 3239/6855 [11:35<12:51,  4.69it/s]

Processing tickers:  47%|████▋     | 3240/6855 [11:35<12:50,  4.69it/s]

Processing tickers:  47%|████▋     | 3241/6855 [11:35<13:02,  4.62it/s]

Processing tickers:  47%|████▋     | 3242/6855 [11:35<12:50,  4.69it/s]

Processing tickers:  47%|████▋     | 3243/6855 [11:36<12:48,  4.70it/s]

Processing tickers:  47%|████▋     | 3244/6855 [11:36<13:00,  4.63it/s]

Processing tickers:  47%|████▋     | 3245/6855 [11:36<12:49,  4.69it/s]

Processing tickers:  47%|████▋     | 3246/6855 [11:36<12:43,  4.73it/s]

Processing tickers:  47%|████▋     | 3247/6855 [11:37<12:53,  4.67it/s]

Processing tickers:  47%|████▋     | 3248/6855 [11:37<13:10,  4.56it/s]

Processing tickers:  47%|████▋     | 3249/6855 [11:37<12:59,  4.63it/s]

Processing tickers:  47%|████▋     | 3250/6855 [11:37<13:08,  4.57it/s]

Processing tickers:  47%|████▋     | 3251/6855 [11:37<12:56,  4.64it/s]

Processing tickers:  47%|████▋     | 3252/6855 [11:38<12:47,  4.69it/s]

Processing tickers:  47%|████▋     | 3253/6855 [11:38<12:40,  4.74it/s]

Processing tickers:  47%|████▋     | 3254/6855 [11:38<12:42,  4.72it/s]

Processing tickers:  47%|████▋     | 3255/6855 [11:38<12:37,  4.75it/s]

Processing tickers:  47%|████▋     | 3256/6855 [11:38<13:09,  4.56it/s]

Processing tickers:  48%|████▊     | 3257/6855 [11:39<13:11,  4.54it/s]

Processing tickers:  48%|████▊     | 3258/6855 [11:39<13:17,  4.51it/s]

Processing tickers:  48%|████▊     | 3259/6855 [11:39<13:05,  4.58it/s]

Processing tickers:  48%|████▊     | 3260/6855 [11:39<13:22,  4.48it/s]

Processing tickers:  48%|████▊     | 3261/6855 [11:40<13:09,  4.55it/s]

Processing tickers:  48%|████▊     | 3262/6855 [11:40<12:57,  4.62it/s]

Processing tickers:  48%|████▊     | 3263/6855 [11:40<13:06,  4.57it/s]

Processing tickers:  48%|████▊     | 3264/6855 [11:40<12:56,  4.63it/s]

Processing tickers:  48%|████▊     | 3265/6855 [11:40<12:49,  4.66it/s]

Processing tickers:  48%|████▊     | 3266/6855 [11:41<12:58,  4.61it/s]

Processing tickers:  48%|████▊     | 3267/6855 [11:41<12:43,  4.70it/s]

Processing tickers:  48%|████▊     | 3268/6855 [11:41<12:40,  4.72it/s]

Processing tickers:  48%|████▊     | 3269/6855 [11:41<12:32,  4.76it/s]

Processing tickers:  48%|████▊     | 3270/6855 [11:41<12:29,  4.78it/s]

Processing tickers:  48%|████▊     | 3271/6855 [11:42<12:33,  4.75it/s]

Processing tickers:  48%|████▊     | 3272/6855 [11:42<12:33,  4.75it/s]

Processing tickers:  48%|████▊     | 3273/6855 [11:42<12:27,  4.79it/s]

Processing tickers:  48%|████▊     | 3274/6855 [11:42<12:46,  4.67it/s]

Processing tickers:  48%|████▊     | 3275/6855 [11:43<13:01,  4.58it/s]

Processing tickers:  48%|████▊     | 3276/6855 [11:43<12:51,  4.64it/s]

Processing tickers:  48%|████▊     | 3277/6855 [11:43<12:44,  4.68it/s]

Processing tickers:  48%|████▊     | 3278/6855 [11:43<12:47,  4.66it/s]

Processing tickers:  48%|████▊     | 3279/6855 [11:43<12:42,  4.69it/s]

Processing tickers:  48%|████▊     | 3280/6855 [11:44<13:07,  4.54it/s]

Processing tickers:  48%|████▊     | 3281/6855 [11:44<13:13,  4.50it/s]

Processing tickers:  48%|████▊     | 3282/6855 [11:44<13:24,  4.44it/s]

Processing tickers:  48%|████▊     | 3283/6855 [11:44<13:11,  4.51it/s]

Processing tickers:  48%|████▊     | 3284/6855 [11:45<13:02,  4.56it/s]

Processing tickers:  48%|████▊     | 3285/6855 [11:45<13:01,  4.57it/s]

Processing tickers:  48%|████▊     | 3286/6855 [11:45<12:51,  4.63it/s]

Processing tickers:  48%|████▊     | 3287/6855 [11:45<12:53,  4.61it/s]

Processing tickers:  48%|████▊     | 3288/6855 [11:45<12:45,  4.66it/s]

Processing tickers:  48%|████▊     | 3289/6855 [11:46<12:58,  4.58it/s]

Processing tickers:  48%|████▊     | 3290/6855 [11:46<13:09,  4.51it/s]

Processing tickers:  48%|████▊     | 3291/6855 [11:46<13:06,  4.53it/s]

Processing tickers:  48%|████▊     | 3292/6855 [11:46<12:51,  4.62it/s]

Processing tickers:  48%|████▊     | 3293/6855 [11:46<12:49,  4.63it/s]

Processing tickers:  48%|████▊     | 3294/6855 [11:47<12:47,  4.64it/s]

Processing tickers:  48%|████▊     | 3295/6855 [11:47<12:46,  4.65it/s]

Processing tickers:  48%|████▊     | 3296/6855 [11:47<12:38,  4.69it/s]

Processing tickers:  48%|████▊     | 3297/6855 [11:47<12:53,  4.60it/s]

Processing tickers:  48%|████▊     | 3298/6855 [11:48<12:45,  4.65it/s]

Processing tickers:  48%|████▊     | 3299/6855 [11:48<12:54,  4.59it/s]

Processing tickers:  48%|████▊     | 3300/6855 [11:48<12:44,  4.65it/s]

Processing tickers:  48%|████▊     | 3301/6855 [11:48<12:52,  4.60it/s]

Processing tickers:  48%|████▊     | 3302/6855 [11:48<12:40,  4.67it/s]

Processing tickers:  48%|████▊     | 3303/6855 [11:49<12:36,  4.69it/s]

Processing tickers:  48%|████▊     | 3304/6855 [11:49<12:32,  4.72it/s]

Processing tickers:  48%|████▊     | 3305/6855 [11:49<12:46,  4.63it/s]

Processing tickers:  48%|████▊     | 3306/6855 [11:49<13:01,  4.54it/s]

Processing tickers:  48%|████▊     | 3307/6855 [11:50<13:07,  4.50it/s]

Processing tickers:  48%|████▊     | 3308/6855 [11:50<12:49,  4.61it/s]

Processing tickers:  48%|████▊     | 3309/6855 [11:50<12:44,  4.64it/s]

Processing tickers:  48%|████▊     | 3310/6855 [11:50<12:34,  4.70it/s]

Processing tickers:  48%|████▊     | 3311/6855 [11:50<12:29,  4.73it/s]

Processing tickers:  48%|████▊     | 3312/6855 [11:51<12:28,  4.74it/s]

Processing tickers:  48%|████▊     | 3313/6855 [11:51<12:27,  4.74it/s]

Processing tickers:  48%|████▊     | 3314/6855 [11:51<12:23,  4.76it/s]

Processing tickers:  48%|████▊     | 3315/6855 [11:51<12:30,  4.72it/s]

Processing tickers:  48%|████▊     | 3316/6855 [11:51<12:37,  4.67it/s]

Processing tickers:  48%|████▊     | 3317/6855 [11:52<12:36,  4.67it/s]

Processing tickers:  48%|████▊     | 3318/6855 [11:52<12:44,  4.63it/s]

Processing tickers:  48%|████▊     | 3319/6855 [11:52<12:38,  4.66it/s]

Processing tickers:  48%|████▊     | 3320/6855 [11:52<12:53,  4.57it/s]

Processing tickers:  48%|████▊     | 3321/6855 [11:53<12:44,  4.62it/s]

Processing tickers:  48%|████▊     | 3322/6855 [11:53<12:33,  4.69it/s]

Processing tickers:  48%|████▊     | 3323/6855 [11:53<12:49,  4.59it/s]

Processing tickers:  48%|████▊     | 3324/6855 [11:53<12:36,  4.67it/s]

Processing tickers:  49%|████▊     | 3325/6855 [11:53<12:55,  4.55it/s]

Processing tickers:  49%|████▊     | 3326/6855 [11:54<12:44,  4.62it/s]

Processing tickers:  49%|████▊     | 3327/6855 [11:54<12:44,  4.61it/s]

Processing tickers:  49%|████▊     | 3328/6855 [11:54<12:32,  4.69it/s]

Processing tickers:  49%|████▊     | 3329/6855 [11:54<12:56,  4.54it/s]

Processing tickers:  49%|████▊     | 3330/6855 [11:54<12:42,  4.62it/s]

Processing tickers:  49%|████▊     | 3331/6855 [11:55<12:35,  4.66it/s]

Processing tickers:  49%|████▊     | 3332/6855 [11:55<12:25,  4.73it/s]

Processing tickers:  49%|████▊     | 3333/6855 [11:55<12:20,  4.76it/s]

Processing tickers:  49%|████▊     | 3334/6855 [11:55<12:17,  4.77it/s]

Processing tickers:  49%|████▊     | 3335/6855 [11:56<12:17,  4.77it/s]

Processing tickers:  49%|████▊     | 3336/6855 [11:56<12:18,  4.76it/s]

Processing tickers:  49%|████▊     | 3337/6855 [11:56<12:15,  4.78it/s]

Processing tickers:  49%|████▊     | 3338/6855 [11:56<12:11,  4.81it/s]

Processing tickers:  49%|████▊     | 3339/6855 [11:56<12:10,  4.81it/s]

Processing tickers:  49%|████▊     | 3340/6855 [11:57<12:10,  4.81it/s]

Processing tickers:  49%|████▊     | 3341/6855 [11:57<12:13,  4.79it/s]

Processing tickers:  49%|████▉     | 3342/6855 [11:57<12:10,  4.81it/s]

Processing tickers:  49%|████▉     | 3343/6855 [11:57<12:07,  4.83it/s]

Processing tickers:  49%|████▉     | 3344/6855 [11:57<12:09,  4.82it/s]

Processing tickers:  49%|████▉     | 3345/6855 [11:58<12:06,  4.83it/s]

Processing tickers:  49%|████▉     | 3346/6855 [11:58<12:07,  4.82it/s]

Processing tickers:  49%|████▉     | 3347/6855 [11:58<12:07,  4.82it/s]

Processing tickers:  49%|████▉     | 3348/6855 [11:58<12:27,  4.69it/s]

Processing tickers:  49%|████▉     | 3349/6855 [11:58<12:19,  4.74it/s]

Processing tickers:  49%|████▉     | 3350/6855 [11:59<12:18,  4.75it/s]

Processing tickers:  49%|████▉     | 3351/6855 [11:59<12:30,  4.67it/s]

Processing tickers:  49%|████▉     | 3352/6855 [11:59<12:23,  4.71it/s]

Processing tickers:  49%|████▉     | 3353/6855 [11:59<12:34,  4.64it/s]

Processing tickers:  49%|████▉     | 3354/6855 [12:00<12:55,  4.52it/s]

Processing tickers:  49%|████▉     | 3355/6855 [12:00<12:41,  4.60it/s]

Processing tickers:  49%|████▉     | 3356/6855 [12:00<12:35,  4.63it/s]

Processing tickers:  49%|████▉     | 3357/6855 [12:00<13:13,  4.41it/s]

Processing tickers:  49%|████▉     | 3358/6855 [12:00<13:11,  4.42it/s]

Processing tickers:  49%|████▉     | 3359/6855 [12:01<12:55,  4.51it/s]

Processing tickers:  49%|████▉     | 3360/6855 [12:01<12:44,  4.57it/s]

Processing tickers:  49%|████▉     | 3361/6855 [12:01<12:47,  4.55it/s]

Processing tickers:  49%|████▉     | 3362/6855 [12:01<12:39,  4.60it/s]

Processing tickers:  49%|████▉     | 3363/6855 [12:01<12:26,  4.68it/s]

Processing tickers:  49%|████▉     | 3364/6855 [12:02<12:22,  4.70it/s]

Processing tickers:  49%|████▉     | 3365/6855 [12:02<12:19,  4.72it/s]

Processing tickers:  49%|████▉     | 3366/6855 [12:02<12:18,  4.73it/s]

Processing tickers:  49%|████▉     | 3367/6855 [12:02<12:41,  4.58it/s]

Processing tickers:  49%|████▉     | 3368/6855 [12:03<12:35,  4.62it/s]

Processing tickers:  49%|████▉     | 3369/6855 [12:03<12:25,  4.67it/s]

Processing tickers:  49%|████▉     | 3370/6855 [12:03<12:21,  4.70it/s]

Processing tickers:  49%|████▉     | 3371/6855 [12:03<12:25,  4.67it/s]

Processing tickers:  49%|████▉     | 3372/6855 [12:03<12:16,  4.73it/s]

Processing tickers:  49%|████▉     | 3373/6855 [12:04<12:13,  4.74it/s]

Processing tickers:  49%|████▉     | 3374/6855 [12:04<12:09,  4.77it/s]

Processing tickers:  49%|████▉     | 3375/6855 [12:04<12:31,  4.63it/s]

Processing tickers:  49%|████▉     | 3376/6855 [12:04<12:46,  4.54it/s]

Processing tickers:  49%|████▉     | 3377/6855 [12:04<12:36,  4.60it/s]

Processing tickers:  49%|████▉     | 3378/6855 [12:05<12:38,  4.58it/s]

Processing tickers:  49%|████▉     | 3379/6855 [12:05<12:29,  4.64it/s]

Processing tickers:  49%|████▉     | 3380/6855 [12:05<12:33,  4.61it/s]

Processing tickers:  49%|████▉     | 3381/6855 [12:05<12:26,  4.65it/s]

Processing tickers:  49%|████▉     | 3382/6855 [12:06<12:42,  4.55it/s]

Processing tickers:  49%|████▉     | 3383/6855 [12:06<12:41,  4.56it/s]

Processing tickers:  49%|████▉     | 3384/6855 [12:06<12:53,  4.49it/s]

Processing tickers:  49%|████▉     | 3385/6855 [12:06<12:38,  4.57it/s]

Processing tickers:  49%|████▉     | 3386/6855 [12:06<12:37,  4.58it/s]

Processing tickers:  49%|████▉     | 3387/6855 [12:07<12:29,  4.62it/s]

Processing tickers:  49%|████▉     | 3388/6855 [12:07<12:26,  4.65it/s]

Processing tickers:  49%|████▉     | 3389/6855 [12:07<12:39,  4.57it/s]

Processing tickers:  49%|████▉     | 3390/6855 [12:07<12:33,  4.60it/s]

Processing tickers:  49%|████▉     | 3391/6855 [12:08<12:24,  4.65it/s]

Processing tickers:  49%|████▉     | 3392/6855 [12:08<12:26,  4.64it/s]

Processing tickers:  49%|████▉     | 3393/6855 [12:08<12:23,  4.66it/s]

Processing tickers:  50%|████▉     | 3394/6855 [12:08<12:13,  4.72it/s]

Processing tickers:  50%|████▉     | 3395/6855 [12:08<12:13,  4.72it/s]

Processing tickers:  50%|████▉     | 3396/6855 [12:09<12:13,  4.72it/s]

Processing tickers:  50%|████▉     | 3397/6855 [12:09<12:06,  4.76it/s]

Processing tickers:  50%|████▉     | 3398/6855 [12:09<11:59,  4.80it/s]

Processing tickers:  50%|████▉     | 3399/6855 [12:09<12:13,  4.71it/s]

Processing tickers:  50%|████▉     | 3400/6855 [12:09<12:08,  4.74it/s]

Processing tickers:  50%|████▉     | 3401/6855 [12:10<12:12,  4.71it/s]

Processing tickers:  50%|████▉     | 3402/6855 [12:10<12:18,  4.67it/s]

Processing tickers:  50%|████▉     | 3403/6855 [12:10<12:26,  4.62it/s]

Processing tickers:  50%|████▉     | 3404/6855 [12:10<12:17,  4.68it/s]

Processing tickers:  50%|████▉     | 3405/6855 [12:11<12:09,  4.73it/s]

Processing tickers:  50%|████▉     | 3406/6855 [12:11<12:05,  4.75it/s]

Processing tickers:  50%|████▉     | 3407/6855 [12:11<12:01,  4.78it/s]

Processing tickers:  50%|████▉     | 3408/6855 [12:11<12:05,  4.75it/s]

Processing tickers:  50%|████▉     | 3409/6855 [12:11<12:09,  4.72it/s]

Processing tickers:  50%|████▉     | 3410/6855 [12:12<12:08,  4.73it/s]

Processing tickers:  50%|████▉     | 3411/6855 [12:12<12:01,  4.77it/s]

Processing tickers:  50%|████▉     | 3412/6855 [12:12<12:03,  4.76it/s]

Processing tickers:  50%|████▉     | 3413/6855 [12:12<12:05,  4.74it/s]

Processing tickers:  50%|████▉     | 3414/6855 [12:12<12:11,  4.70it/s]

Processing tickers:  50%|████▉     | 3415/6855 [12:13<12:09,  4.72it/s]

Processing tickers:  50%|████▉     | 3416/6855 [12:13<12:07,  4.73it/s]

Processing tickers:  50%|████▉     | 3417/6855 [12:13<12:00,  4.77it/s]

Processing tickers:  50%|████▉     | 3418/6855 [12:13<12:00,  4.77it/s]

Processing tickers:  50%|████▉     | 3419/6855 [12:13<12:07,  4.72it/s]

Processing tickers:  50%|████▉     | 3420/6855 [12:14<12:01,  4.76it/s]

Processing tickers:  50%|████▉     | 3421/6855 [12:14<12:06,  4.73it/s]

Processing tickers:  50%|████▉     | 3422/6855 [12:14<12:07,  4.72it/s]

Processing tickers:  50%|████▉     | 3423/6855 [12:14<12:08,  4.71it/s]

Processing tickers:  50%|████▉     | 3424/6855 [12:15<12:01,  4.75it/s]

Processing tickers:  50%|████▉     | 3425/6855 [12:15<11:56,  4.79it/s]

Processing tickers:  50%|████▉     | 3426/6855 [12:15<11:53,  4.81it/s]

Processing tickers:  50%|████▉     | 3427/6855 [12:15<11:54,  4.80it/s]

Processing tickers:  50%|█████     | 3428/6855 [12:15<11:59,  4.77it/s]

Processing tickers:  50%|█████     | 3429/6855 [12:16<11:57,  4.78it/s]

Processing tickers:  50%|█████     | 3430/6855 [12:16<11:54,  4.79it/s]

Processing tickers:  50%|█████     | 3431/6855 [12:16<11:49,  4.83it/s]

Processing tickers:  50%|█████     | 3432/6855 [12:16<11:50,  4.82it/s]

Processing tickers:  50%|█████     | 3433/6855 [12:16<12:02,  4.74it/s]

Processing tickers:  50%|█████     | 3434/6855 [12:17<11:57,  4.77it/s]

Processing tickers:  50%|█████     | 3435/6855 [12:17<11:56,  4.77it/s]

Processing tickers:  50%|█████     | 3436/6855 [12:17<12:11,  4.67it/s]

Processing tickers:  50%|█████     | 3437/6855 [12:17<12:10,  4.68it/s]

Processing tickers:  50%|█████     | 3438/6855 [12:17<12:13,  4.66it/s]

Processing tickers:  50%|█████     | 3439/6855 [12:18<12:35,  4.52it/s]

Processing tickers:  50%|█████     | 3440/6855 [12:18<12:22,  4.60it/s]

Processing tickers:  50%|█████     | 3441/6855 [12:18<12:19,  4.62it/s]

Processing tickers:  50%|█████     | 3442/6855 [12:18<12:10,  4.67it/s]

Processing tickers:  50%|█████     | 3443/6855 [12:19<12:04,  4.71it/s]

Processing tickers:  50%|█████     | 3444/6855 [12:19<12:05,  4.70it/s]

Processing tickers:  50%|█████     | 3445/6855 [12:19<12:09,  4.67it/s]

Processing tickers:  50%|█████     | 3446/6855 [12:19<12:09,  4.67it/s]

Processing tickers:  50%|█████     | 3447/6855 [12:19<12:03,  4.71it/s]

Processing tickers:  50%|█████     | 3448/6855 [12:20<12:00,  4.73it/s]

Processing tickers:  50%|█████     | 3449/6855 [12:20<11:58,  4.74it/s]

Processing tickers:  50%|█████     | 3450/6855 [12:20<11:53,  4.78it/s]

Processing tickers:  50%|█████     | 3451/6855 [12:20<12:06,  4.69it/s]

Processing tickers:  50%|█████     | 3452/6855 [12:20<12:04,  4.70it/s]

Processing tickers:  50%|█████     | 3453/6855 [12:21<12:00,  4.72it/s]

Processing tickers:  50%|█████     | 3454/6855 [12:21<11:55,  4.75it/s]

Processing tickers:  50%|█████     | 3455/6855 [12:21<11:49,  4.79it/s]

Processing tickers:  50%|█████     | 3456/6855 [12:21<11:50,  4.78it/s]

Processing tickers:  50%|█████     | 3457/6855 [12:21<11:55,  4.75it/s]

Processing tickers:  50%|█████     | 3458/6855 [12:22<11:58,  4.73it/s]

Processing tickers:  50%|█████     | 3459/6855 [12:22<12:12,  4.63it/s]

Processing tickers:  50%|█████     | 3460/6855 [12:22<12:14,  4.62it/s]

Processing tickers:  50%|█████     | 3461/6855 [12:22<12:35,  4.49it/s]

Processing tickers:  51%|█████     | 3462/6855 [12:23<12:50,  4.40it/s]

Processing tickers:  51%|█████     | 3463/6855 [12:23<12:30,  4.52it/s]

Processing tickers:  51%|█████     | 3464/6855 [12:23<12:15,  4.61it/s]

Processing tickers:  51%|█████     | 3465/6855 [12:23<12:13,  4.62it/s]

Processing tickers:  51%|█████     | 3466/6855 [12:23<12:14,  4.61it/s]

Processing tickers:  51%|█████     | 3467/6855 [12:24<12:13,  4.62it/s]

Processing tickers:  51%|█████     | 3468/6855 [12:24<12:08,  4.65it/s]

Processing tickers:  51%|█████     | 3469/6855 [12:24<11:57,  4.72it/s]

Processing tickers:  51%|█████     | 3470/6855 [12:24<12:07,  4.65it/s]

Processing tickers:  51%|█████     | 3471/6855 [12:25<12:24,  4.54it/s]

Processing tickers:  51%|█████     | 3472/6855 [12:25<12:14,  4.61it/s]

Processing tickers:  51%|█████     | 3473/6855 [12:25<12:17,  4.59it/s]

Processing tickers:  51%|█████     | 3474/6855 [12:25<12:39,  4.45it/s]

Processing tickers:  51%|█████     | 3475/6855 [12:25<12:22,  4.55it/s]

Processing tickers:  51%|█████     | 3476/6855 [12:26<12:11,  4.62it/s]

Processing tickers:  51%|█████     | 3477/6855 [12:26<12:04,  4.66it/s]

Processing tickers:  51%|█████     | 3478/6855 [12:26<11:57,  4.71it/s]

Processing tickers:  51%|█████     | 3479/6855 [12:26<11:58,  4.70it/s]

Processing tickers:  51%|█████     | 3480/6855 [12:26<11:55,  4.71it/s]

Processing tickers:  51%|█████     | 3481/6855 [12:27<11:51,  4.74it/s]

Processing tickers:  51%|█████     | 3482/6855 [12:27<11:51,  4.74it/s]

Processing tickers:  51%|█████     | 3483/6855 [12:27<11:46,  4.77it/s]

Processing tickers:  51%|█████     | 3484/6855 [12:27<11:46,  4.77it/s]

Processing tickers:  51%|█████     | 3485/6855 [12:28<11:53,  4.72it/s]

Processing tickers:  51%|█████     | 3486/6855 [12:28<11:52,  4.73it/s]

Processing tickers:  51%|█████     | 3487/6855 [12:28<11:49,  4.75it/s]

Processing tickers:  51%|█████     | 3488/6855 [12:28<11:44,  4.78it/s]

Processing tickers:  51%|█████     | 3489/6855 [12:28<11:46,  4.76it/s]

Processing tickers:  51%|█████     | 3490/6855 [12:29<11:47,  4.75it/s]

Processing tickers:  51%|█████     | 3491/6855 [12:29<12:02,  4.65it/s]

Processing tickers:  51%|█████     | 3492/6855 [12:29<12:06,  4.63it/s]

Processing tickers:  51%|█████     | 3493/6855 [12:29<12:21,  4.54it/s]

Processing tickers:  51%|█████     | 3494/6855 [12:29<12:35,  4.45it/s]

Processing tickers:  51%|█████     | 3495/6855 [12:30<12:25,  4.51it/s]

Processing tickers:  51%|█████     | 3496/6855 [12:30<12:11,  4.59it/s]

Processing tickers:  51%|█████     | 3497/6855 [12:30<12:00,  4.66it/s]

Processing tickers:  51%|█████     | 3498/6855 [12:30<12:21,  4.53it/s]

Processing tickers:  51%|█████     | 3499/6855 [12:31<12:20,  4.53it/s]

Processing tickers:  51%|█████     | 3500/6855 [12:31<12:06,  4.62it/s]

Processing tickers:  51%|█████     | 3501/6855 [12:31<12:21,  4.52it/s]

Processing tickers:  51%|█████     | 3502/6855 [12:31<12:10,  4.59it/s]

Processing tickers:  51%|█████     | 3503/6855 [12:31<12:19,  4.54it/s]

Processing tickers:  51%|█████     | 3504/6855 [12:32<12:00,  4.65it/s]

Processing tickers:  51%|█████     | 3505/6855 [12:32<11:59,  4.66it/s]

Processing tickers:  51%|█████     | 3506/6855 [12:32<11:55,  4.68it/s]

Processing tickers:  51%|█████     | 3507/6855 [12:32<11:50,  4.71it/s]

Processing tickers:  51%|█████     | 3508/6855 [12:33<11:45,  4.74it/s]

Processing tickers:  51%|█████     | 3509/6855 [12:33<11:44,  4.75it/s]

Processing tickers:  51%|█████     | 3510/6855 [12:33<11:41,  4.77it/s]

Processing tickers:  51%|█████     | 3511/6855 [12:33<11:43,  4.76it/s]

Processing tickers:  51%|█████     | 3512/6855 [12:33<11:43,  4.75it/s]

Processing tickers:  51%|█████     | 3513/6855 [12:34<11:38,  4.78it/s]

Processing tickers:  51%|█████▏    | 3514/6855 [12:34<11:38,  4.78it/s]

Processing tickers:  51%|█████▏    | 3515/6855 [12:34<12:05,  4.61it/s]

Processing tickers:  51%|█████▏    | 3516/6855 [12:34<12:00,  4.63it/s]

Processing tickers:  51%|█████▏    | 3517/6855 [12:34<11:49,  4.70it/s]

Processing tickers:  51%|█████▏    | 3518/6855 [12:35<12:03,  4.61it/s]

Processing tickers:  51%|█████▏    | 3519/6855 [12:35<12:22,  4.49it/s]

Processing tickers:  51%|█████▏    | 3520/6855 [12:35<12:25,  4.47it/s]

Processing tickers:  51%|█████▏    | 3521/6855 [12:35<12:19,  4.51it/s]

Processing tickers:  51%|█████▏    | 3522/6855 [12:36<12:07,  4.58it/s]

Processing tickers:  51%|█████▏    | 3523/6855 [12:36<12:00,  4.62it/s]

Processing tickers:  51%|█████▏    | 3524/6855 [12:36<11:51,  4.68it/s]

Processing tickers:  51%|█████▏    | 3525/6855 [12:36<11:44,  4.73it/s]

Processing tickers:  51%|█████▏    | 3526/6855 [12:36<11:43,  4.73it/s]

Processing tickers:  51%|█████▏    | 3527/6855 [12:37<11:34,  4.79it/s]

Processing tickers:  51%|█████▏    | 3528/6855 [12:37<11:25,  4.85it/s]

Processing tickers:  51%|█████▏    | 3529/6855 [12:37<11:30,  4.82it/s]

Processing tickers:  51%|█████▏    | 3530/6855 [12:37<11:53,  4.66it/s]

Processing tickers:  52%|█████▏    | 3531/6855 [12:37<11:56,  4.64it/s]

Processing tickers:  52%|█████▏    | 3532/6855 [12:38<11:46,  4.70it/s]

Processing tickers:  52%|█████▏    | 3533/6855 [12:38<11:43,  4.72it/s]

Processing tickers:  52%|█████▏    | 3534/6855 [12:38<11:39,  4.75it/s]

Processing tickers:  52%|█████▏    | 3535/6855 [12:38<11:38,  4.75it/s]

Processing tickers:  52%|█████▏    | 3536/6855 [12:38<11:40,  4.74it/s]

Processing tickers:  52%|█████▏    | 3537/6855 [12:39<11:35,  4.77it/s]

Processing tickers:  52%|█████▏    | 3538/6855 [12:39<11:32,  4.79it/s]

Processing tickers:  52%|█████▏    | 3539/6855 [12:39<11:34,  4.78it/s]

Processing tickers:  52%|█████▏    | 3540/6855 [12:39<11:32,  4.78it/s]

Processing tickers:  52%|█████▏    | 3541/6855 [12:40<11:35,  4.76it/s]

Processing tickers:  52%|█████▏    | 3542/6855 [12:40<11:39,  4.74it/s]

Processing tickers:  52%|█████▏    | 3543/6855 [12:40<11:48,  4.68it/s]

Processing tickers:  52%|█████▏    | 3544/6855 [12:40<12:24,  4.45it/s]

Processing tickers:  52%|█████▏    | 3545/6855 [12:40<12:22,  4.46it/s]

Processing tickers:  52%|█████▏    | 3546/6855 [12:41<12:07,  4.55it/s]

Processing tickers:  52%|█████▏    | 3547/6855 [12:41<11:58,  4.60it/s]

Processing tickers:  52%|█████▏    | 3548/6855 [12:41<11:46,  4.68it/s]

Processing tickers:  52%|█████▏    | 3549/6855 [12:41<11:44,  4.69it/s]

Processing tickers:  52%|█████▏    | 3550/6855 [12:41<11:43,  4.70it/s]

Processing tickers:  52%|█████▏    | 3551/6855 [12:42<11:37,  4.73it/s]

Processing tickers:  52%|█████▏    | 3552/6855 [12:42<11:34,  4.75it/s]

Processing tickers:  52%|█████▏    | 3553/6855 [12:42<11:35,  4.75it/s]

Processing tickers:  52%|█████▏    | 3554/6855 [12:42<11:31,  4.77it/s]

Processing tickers:  52%|█████▏    | 3555/6855 [12:43<11:27,  4.80it/s]

Processing tickers:  52%|█████▏    | 3556/6855 [12:43<11:31,  4.77it/s]

Processing tickers:  52%|█████▏    | 3557/6855 [12:43<11:28,  4.79it/s]

Processing tickers:  52%|█████▏    | 3558/6855 [12:43<11:23,  4.82it/s]

Processing tickers:  52%|█████▏    | 3559/6855 [12:43<11:30,  4.77it/s]

Processing tickers:  52%|█████▏    | 3560/6855 [12:44<11:33,  4.75it/s]

Processing tickers:  52%|█████▏    | 3561/6855 [12:44<11:30,  4.77it/s]

Processing tickers:  52%|█████▏    | 3562/6855 [12:44<11:29,  4.78it/s]

Processing tickers:  52%|█████▏    | 3563/6855 [12:44<11:43,  4.68it/s]

Processing tickers:  52%|█████▏    | 3564/6855 [12:44<11:46,  4.66it/s]

Processing tickers:  52%|█████▏    | 3565/6855 [12:45<11:41,  4.69it/s]

Processing tickers:  52%|█████▏    | 3566/6855 [12:45<11:40,  4.69it/s]

Processing tickers:  52%|█████▏    | 3567/6855 [12:45<11:33,  4.74it/s]

Processing tickers:  52%|█████▏    | 3568/6855 [12:45<11:34,  4.73it/s]

Processing tickers:  52%|█████▏    | 3569/6855 [12:45<11:34,  4.73it/s]

Processing tickers:  52%|█████▏    | 3570/6855 [12:46<11:26,  4.78it/s]

Processing tickers:  52%|█████▏    | 3571/6855 [12:46<11:25,  4.79it/s]

Processing tickers:  52%|█████▏    | 3572/6855 [12:46<11:21,  4.82it/s]

Processing tickers:  52%|█████▏    | 3573/6855 [12:46<11:29,  4.76it/s]

Processing tickers:  52%|█████▏    | 3574/6855 [12:47<11:34,  4.72it/s]

Processing tickers:  52%|█████▏    | 3575/6855 [12:47<11:45,  4.65it/s]

Processing tickers:  52%|█████▏    | 3576/6855 [12:47<11:33,  4.73it/s]

Processing tickers:  52%|█████▏    | 3577/6855 [12:47<11:33,  4.73it/s]

Processing tickers:  52%|█████▏    | 3578/6855 [12:47<11:32,  4.73it/s]

Processing tickers:  52%|█████▏    | 3579/6855 [12:48<11:29,  4.75it/s]

Processing tickers:  52%|█████▏    | 3580/6855 [12:48<11:23,  4.79it/s]

Processing tickers:  52%|█████▏    | 3581/6855 [12:48<11:19,  4.82it/s]

Processing tickers:  52%|█████▏    | 3582/6855 [12:48<11:26,  4.77it/s]

Processing tickers:  52%|█████▏    | 3583/6855 [12:48<11:21,  4.80it/s]

Processing tickers:  52%|█████▏    | 3584/6855 [12:49<11:24,  4.78it/s]

Processing tickers:  52%|█████▏    | 3585/6855 [12:49<11:25,  4.77it/s]

Processing tickers:  52%|█████▏    | 3586/6855 [12:49<11:23,  4.78it/s]

Processing tickers:  52%|█████▏    | 3587/6855 [12:49<11:27,  4.75it/s]

Processing tickers:  52%|█████▏    | 3588/6855 [12:49<11:27,  4.75it/s]

Processing tickers:  52%|█████▏    | 3589/6855 [12:50<11:22,  4.78it/s]

Processing tickers:  52%|█████▏    | 3590/6855 [12:50<11:36,  4.69it/s]

Processing tickers:  52%|█████▏    | 3591/6855 [12:50<11:34,  4.70it/s]

Processing tickers:  52%|█████▏    | 3592/6855 [12:50<11:51,  4.58it/s]

Processing tickers:  52%|█████▏    | 3593/6855 [12:51<12:02,  4.52it/s]

Processing tickers:  52%|█████▏    | 3594/6855 [12:51<11:56,  4.55it/s]

Processing tickers:  52%|█████▏    | 3595/6855 [12:51<12:09,  4.47it/s]

Processing tickers:  52%|█████▏    | 3596/6855 [12:51<12:02,  4.51it/s]

Processing tickers:  52%|█████▏    | 3597/6855 [12:51<11:46,  4.61it/s]

Processing tickers:  52%|█████▏    | 3598/6855 [12:52<11:37,  4.67it/s]

Processing tickers:  53%|█████▎    | 3599/6855 [12:52<11:31,  4.71it/s]

Processing tickers:  53%|█████▎    | 3600/6855 [12:52<11:28,  4.73it/s]

Processing tickers:  53%|█████▎    | 3601/6855 [12:52<11:23,  4.76it/s]

Processing tickers:  53%|█████▎    | 3602/6855 [12:52<11:31,  4.70it/s]

Processing tickers:  53%|█████▎    | 3603/6855 [12:53<11:26,  4.73it/s]

Processing tickers:  53%|█████▎    | 3604/6855 [12:53<11:22,  4.76it/s]

Processing tickers:  53%|█████▎    | 3605/6855 [12:53<11:15,  4.81it/s]

Processing tickers:  53%|█████▎    | 3606/6855 [12:53<11:20,  4.77it/s]

Processing tickers:  53%|█████▎    | 3607/6855 [12:54<11:27,  4.73it/s]

Processing tickers:  53%|█████▎    | 3608/6855 [12:54<11:24,  4.75it/s]

Processing tickers:  53%|█████▎    | 3609/6855 [12:54<11:26,  4.73it/s]

Processing tickers:  53%|█████▎    | 3610/6855 [12:54<11:20,  4.77it/s]

Processing tickers:  53%|█████▎    | 3611/6855 [12:54<11:25,  4.73it/s]

Processing tickers:  53%|█████▎    | 3612/6855 [12:55<11:21,  4.76it/s]

Processing tickers:  53%|█████▎    | 3613/6855 [12:55<11:35,  4.66it/s]

Processing tickers:  53%|█████▎    | 3614/6855 [12:55<11:29,  4.70it/s]

Processing tickers:  53%|█████▎    | 3615/6855 [12:55<11:20,  4.76it/s]

Processing tickers:  53%|█████▎    | 3616/6855 [12:55<11:33,  4.67it/s]

Processing tickers:  53%|█████▎    | 3617/6855 [12:56<11:23,  4.74it/s]

Processing tickers:  53%|█████▎    | 3618/6855 [12:56<11:19,  4.76it/s]

Processing tickers:  53%|█████▎    | 3619/6855 [12:56<11:18,  4.77it/s]

Processing tickers:  53%|█████▎    | 3620/6855 [12:56<11:20,  4.75it/s]

Processing tickers:  53%|█████▎    | 3621/6855 [12:56<11:24,  4.73it/s]

Processing tickers:  53%|█████▎    | 3622/6855 [12:57<11:23,  4.73it/s]

Processing tickers:  53%|█████▎    | 3623/6855 [12:57<11:26,  4.70it/s]

Processing tickers:  53%|█████▎    | 3624/6855 [12:57<11:37,  4.64it/s]

Processing tickers:  53%|█████▎    | 3625/6855 [12:57<11:33,  4.66it/s]

Processing tickers:  53%|█████▎    | 3626/6855 [12:58<11:25,  4.71it/s]

Processing tickers:  53%|█████▎    | 3627/6855 [12:58<11:27,  4.70it/s]

Processing tickers:  53%|█████▎    | 3628/6855 [12:58<11:20,  4.74it/s]

Processing tickers:  53%|█████▎    | 3629/6855 [12:58<11:26,  4.70it/s]

Processing tickers:  53%|█████▎    | 3630/6855 [12:58<11:19,  4.75it/s]

Processing tickers:  53%|█████▎    | 3631/6855 [12:59<12:21,  4.35it/s]

Processing tickers:  53%|█████▎    | 3632/6855 [12:59<12:31,  4.29it/s]

Processing tickers:  53%|█████▎    | 3633/6855 [12:59<12:03,  4.45it/s]

Processing tickers:  53%|█████▎    | 3634/6855 [12:59<11:54,  4.51it/s]

Processing tickers:  53%|█████▎    | 3635/6855 [13:00<11:41,  4.59it/s]

Processing tickers:  53%|█████▎    | 3636/6855 [13:00<11:35,  4.63it/s]

Processing tickers:  53%|█████▎    | 3637/6855 [13:00<11:31,  4.65it/s]

Processing tickers:  53%|█████▎    | 3638/6855 [13:00<11:36,  4.62it/s]

Processing tickers:  53%|█████▎    | 3639/6855 [13:00<11:27,  4.68it/s]

Processing tickers:  53%|█████▎    | 3640/6855 [13:01<11:23,  4.71it/s]

Processing tickers:  53%|█████▎    | 3641/6855 [13:01<11:38,  4.60it/s]

Processing tickers:  53%|█████▎    | 3642/6855 [13:01<11:26,  4.68it/s]

Processing tickers:  53%|█████▎    | 3643/6855 [13:01<11:19,  4.73it/s]

Processing tickers:  53%|█████▎    | 3644/6855 [13:01<11:48,  4.53it/s]

Processing tickers:  53%|█████▎    | 3645/6855 [13:02<11:34,  4.62it/s]

Processing tickers:  53%|█████▎    | 3646/6855 [13:02<11:32,  4.63it/s]

Processing tickers:  53%|█████▎    | 3647/6855 [13:02<11:22,  4.70it/s]

Processing tickers:  53%|█████▎    | 3648/6855 [13:02<11:26,  4.67it/s]

Processing tickers:  53%|█████▎    | 3649/6855 [13:03<11:20,  4.71it/s]

Processing tickers:  53%|█████▎    | 3650/6855 [13:03<11:16,  4.74it/s]

Processing tickers:  53%|█████▎    | 3651/6855 [13:03<11:10,  4.78it/s]

Processing tickers:  53%|█████▎    | 3652/6855 [13:03<11:10,  4.78it/s]

Processing tickers:  53%|█████▎    | 3653/6855 [13:03<11:08,  4.79it/s]

Processing tickers:  53%|█████▎    | 3654/6855 [13:04<11:03,  4.83it/s]

Processing tickers:  53%|█████▎    | 3655/6855 [13:04<11:05,  4.81it/s]

Processing tickers:  53%|█████▎    | 3656/6855 [13:04<11:07,  4.80it/s]

Processing tickers:  53%|█████▎    | 3657/6855 [13:04<11:11,  4.76it/s]

Processing tickers:  53%|█████▎    | 3658/6855 [13:04<11:08,  4.78it/s]

Processing tickers:  53%|█████▎    | 3659/6855 [13:05<11:03,  4.82it/s]

Processing tickers:  53%|█████▎    | 3660/6855 [13:05<11:03,  4.82it/s]

Processing tickers:  53%|█████▎    | 3661/6855 [13:05<11:04,  4.81it/s]

Processing tickers:  53%|█████▎    | 3662/6855 [13:05<11:12,  4.75it/s]

Processing tickers:  53%|█████▎    | 3663/6855 [13:05<11:11,  4.76it/s]

Processing tickers:  53%|█████▎    | 3664/6855 [13:06<11:26,  4.65it/s]

Processing tickers:  53%|█████▎    | 3665/6855 [13:06<11:23,  4.67it/s]

Processing tickers:  53%|█████▎    | 3666/6855 [13:06<11:15,  4.72it/s]

Processing tickers:  53%|█████▎    | 3667/6855 [13:06<11:17,  4.71it/s]

Processing tickers:  54%|█████▎    | 3668/6855 [13:07<11:19,  4.69it/s]

Processing tickers:  54%|█████▎    | 3669/6855 [13:07<11:18,  4.70it/s]

Processing tickers:  54%|█████▎    | 3670/6855 [13:07<11:12,  4.74it/s]

Processing tickers:  54%|█████▎    | 3671/6855 [13:07<11:09,  4.76it/s]

Processing tickers:  54%|█████▎    | 3672/6855 [13:07<11:09,  4.75it/s]

Processing tickers:  54%|█████▎    | 3673/6855 [13:08<11:10,  4.74it/s]

Processing tickers:  54%|█████▎    | 3674/6855 [13:08<11:13,  4.72it/s]

Processing tickers:  54%|█████▎    | 3675/6855 [13:08<11:06,  4.77it/s]

Processing tickers:  54%|█████▎    | 3676/6855 [13:08<11:08,  4.76it/s]

Processing tickers:  54%|█████▎    | 3677/6855 [13:08<11:37,  4.55it/s]

Processing tickers:  54%|█████▎    | 3678/6855 [13:09<11:26,  4.63it/s]

Processing tickers:  54%|█████▎    | 3679/6855 [13:09<11:20,  4.67it/s]

Processing tickers:  54%|█████▎    | 3680/6855 [13:09<11:14,  4.71it/s]

Processing tickers:  54%|█████▎    | 3681/6855 [13:09<11:21,  4.66it/s]

Processing tickers:  54%|█████▎    | 3682/6855 [13:10<11:11,  4.73it/s]

Processing tickers:  54%|█████▎    | 3683/6855 [13:10<11:09,  4.74it/s]

Processing tickers:  54%|█████▎    | 3684/6855 [13:10<11:06,  4.75it/s]

Processing tickers:  54%|█████▍    | 3685/6855 [13:10<11:27,  4.61it/s]

Processing tickers:  54%|█████▍    | 3686/6855 [13:10<11:19,  4.67it/s]

Processing tickers:  54%|█████▍    | 3687/6855 [13:11<11:10,  4.72it/s]

Processing tickers:  54%|█████▍    | 3688/6855 [13:11<11:05,  4.76it/s]

Processing tickers:  54%|█████▍    | 3689/6855 [13:11<11:05,  4.76it/s]

Processing tickers:  54%|█████▍    | 3690/6855 [13:11<11:10,  4.72it/s]

Processing tickers:  54%|█████▍    | 3691/6855 [13:11<11:02,  4.78it/s]

Processing tickers:  54%|█████▍    | 3692/6855 [13:12<11:03,  4.77it/s]

Processing tickers:  54%|█████▍    | 3693/6855 [13:12<11:05,  4.75it/s]

Processing tickers:  54%|█████▍    | 3694/6855 [13:12<11:03,  4.77it/s]

Processing tickers:  54%|█████▍    | 3695/6855 [13:12<11:12,  4.70it/s]

Processing tickers:  54%|█████▍    | 3696/6855 [13:12<11:13,  4.69it/s]

Processing tickers:  54%|█████▍    | 3697/6855 [13:13<11:10,  4.71it/s]

Processing tickers:  54%|█████▍    | 3698/6855 [13:13<11:07,  4.73it/s]

Processing tickers:  54%|█████▍    | 3699/6855 [13:13<11:05,  4.75it/s]

Processing tickers:  54%|█████▍    | 3700/6855 [13:13<11:01,  4.77it/s]

Processing tickers:  54%|█████▍    | 3701/6855 [13:14<10:59,  4.79it/s]

Processing tickers:  54%|█████▍    | 3702/6855 [13:14<10:58,  4.79it/s]

Processing tickers:  54%|█████▍    | 3703/6855 [13:14<10:57,  4.79it/s]

Processing tickers:  54%|█████▍    | 3704/6855 [13:14<10:56,  4.80it/s]

Processing tickers:  54%|█████▍    | 3705/6855 [13:14<10:55,  4.80it/s]

Processing tickers:  54%|█████▍    | 3706/6855 [13:15<10:55,  4.80it/s]

Processing tickers:  54%|█████▍    | 3707/6855 [13:15<10:57,  4.78it/s]

Processing tickers:  54%|█████▍    | 3708/6855 [13:15<10:54,  4.81it/s]

Processing tickers:  54%|█████▍    | 3709/6855 [13:15<11:03,  4.74it/s]

Processing tickers:  54%|█████▍    | 3710/6855 [13:15<11:00,  4.77it/s]

Processing tickers:  54%|█████▍    | 3711/6855 [13:16<11:13,  4.67it/s]

Processing tickers:  54%|█████▍    | 3712/6855 [13:16<11:27,  4.57it/s]

Processing tickers:  54%|█████▍    | 3713/6855 [13:16<11:37,  4.51it/s]

Processing tickers:  54%|█████▍    | 3714/6855 [13:16<11:25,  4.58it/s]

Processing tickers:  54%|█████▍    | 3715/6855 [13:17<11:17,  4.64it/s]

Processing tickers:  54%|█████▍    | 3716/6855 [13:17<11:27,  4.57it/s]

Processing tickers:  54%|█████▍    | 3717/6855 [13:17<11:33,  4.52it/s]

Processing tickers:  54%|█████▍    | 3718/6855 [13:17<11:16,  4.64it/s]

Processing tickers:  54%|█████▍    | 3719/6855 [13:17<11:12,  4.66it/s]

Processing tickers:  54%|█████▍    | 3720/6855 [13:18<11:40,  4.48it/s]

Processing tickers:  54%|█████▍    | 3721/6855 [13:18<11:26,  4.57it/s]

Processing tickers:  54%|█████▍    | 3722/6855 [13:18<11:39,  4.48it/s]

Processing tickers:  54%|█████▍    | 3723/6855 [13:18<11:28,  4.55it/s]

Processing tickers:  54%|█████▍    | 3724/6855 [13:18<11:16,  4.63it/s]

Processing tickers:  54%|█████▍    | 3725/6855 [13:19<11:08,  4.68it/s]

Processing tickers:  54%|█████▍    | 3726/6855 [13:19<11:04,  4.71it/s]

Processing tickers:  54%|█████▍    | 3727/6855 [13:19<11:04,  4.70it/s]

Processing tickers:  54%|█████▍    | 3728/6855 [13:19<11:02,  4.72it/s]

Processing tickers:  54%|█████▍    | 3729/6855 [13:20<11:04,  4.71it/s]

Processing tickers:  54%|█████▍    | 3730/6855 [13:20<11:01,  4.72it/s]

Processing tickers:  54%|█████▍    | 3731/6855 [13:20<10:52,  4.79it/s]

Processing tickers:  54%|█████▍    | 3732/6855 [13:20<10:55,  4.77it/s]

Processing tickers:  54%|█████▍    | 3733/6855 [13:20<10:56,  4.76it/s]

Processing tickers:  54%|█████▍    | 3734/6855 [13:21<11:04,  4.70it/s]

Processing tickers:  54%|█████▍    | 3735/6855 [13:21<11:02,  4.71it/s]

Processing tickers:  55%|█████▍    | 3736/6855 [13:21<10:57,  4.75it/s]

Processing tickers:  55%|█████▍    | 3737/6855 [13:21<10:57,  4.74it/s]

Processing tickers:  55%|█████▍    | 3738/6855 [13:21<10:51,  4.78it/s]

Processing tickers:  55%|█████▍    | 3739/6855 [13:22<10:53,  4.77it/s]

Processing tickers:  55%|█████▍    | 3740/6855 [13:22<10:50,  4.79it/s]

Processing tickers:  55%|█████▍    | 3741/6855 [13:22<10:49,  4.80it/s]

Processing tickers:  55%|█████▍    | 3742/6855 [13:22<10:52,  4.77it/s]

Processing tickers:  55%|█████▍    | 3743/6855 [13:22<10:51,  4.78it/s]

Processing tickers:  55%|█████▍    | 3744/6855 [13:23<10:48,  4.80it/s]

Processing tickers:  55%|█████▍    | 3745/6855 [13:23<11:03,  4.69it/s]

Processing tickers:  55%|█████▍    | 3746/6855 [13:23<11:00,  4.71it/s]

Processing tickers:  55%|█████▍    | 3747/6855 [13:23<10:59,  4.71it/s]

Processing tickers:  55%|█████▍    | 3748/6855 [13:24<10:53,  4.75it/s]

Processing tickers:  55%|█████▍    | 3749/6855 [13:24<10:51,  4.76it/s]

Processing tickers:  55%|█████▍    | 3750/6855 [13:24<11:02,  4.69it/s]

Processing tickers:  55%|█████▍    | 3751/6855 [13:24<10:57,  4.72it/s]

Processing tickers:  55%|█████▍    | 3752/6855 [13:24<11:09,  4.64it/s]

Processing tickers:  55%|█████▍    | 3753/6855 [13:25<10:59,  4.70it/s]

Processing tickers:  55%|█████▍    | 3754/6855 [13:25<10:55,  4.73it/s]

Processing tickers:  55%|█████▍    | 3755/6855 [13:25<10:59,  4.70it/s]

Processing tickers:  55%|█████▍    | 3756/6855 [13:25<10:52,  4.75it/s]

Processing tickers:  55%|█████▍    | 3757/6855 [13:25<11:17,  4.58it/s]

Processing tickers:  55%|█████▍    | 3758/6855 [13:26<11:11,  4.61it/s]

Processing tickers:  55%|█████▍    | 3759/6855 [13:26<10:59,  4.69it/s]

Processing tickers:  55%|█████▍    | 3760/6855 [13:26<11:08,  4.63it/s]

Processing tickers:  55%|█████▍    | 3761/6855 [13:26<11:29,  4.49it/s]

Processing tickers:  55%|█████▍    | 3762/6855 [13:27<11:21,  4.54it/s]

Processing tickers:  55%|█████▍    | 3763/6855 [13:27<11:11,  4.61it/s]

Processing tickers:  55%|█████▍    | 3764/6855 [13:27<11:04,  4.65it/s]

Processing tickers:  55%|█████▍    | 3765/6855 [13:27<11:06,  4.64it/s]

Processing tickers:  55%|█████▍    | 3766/6855 [13:27<10:56,  4.70it/s]

Processing tickers:  55%|█████▍    | 3767/6855 [13:28<11:08,  4.62it/s]

Processing tickers:  55%|█████▍    | 3768/6855 [13:28<10:58,  4.69it/s]

Processing tickers:  55%|█████▍    | 3769/6855 [13:28<11:13,  4.58it/s]

Processing tickers:  55%|█████▍    | 3770/6855 [13:28<11:06,  4.63it/s]

Processing tickers:  55%|█████▌    | 3771/6855 [13:28<10:55,  4.70it/s]

Processing tickers:  55%|█████▌    | 3772/6855 [13:29<11:14,  4.57it/s]

Processing tickers:  55%|█████▌    | 3773/6855 [13:29<11:04,  4.64it/s]

Processing tickers:  55%|█████▌    | 3774/6855 [13:29<10:56,  4.69it/s]

Processing tickers:  55%|█████▌    | 3775/6855 [13:29<11:13,  4.57it/s]

Processing tickers:  55%|█████▌    | 3776/6855 [13:30<11:06,  4.62it/s]

Processing tickers:  55%|█████▌    | 3777/6855 [13:30<10:59,  4.67it/s]

Processing tickers:  55%|█████▌    | 3778/6855 [13:30<11:12,  4.57it/s]

Processing tickers:  55%|█████▌    | 3779/6855 [13:30<11:21,  4.51it/s]

Processing tickers:  55%|█████▌    | 3780/6855 [13:30<11:07,  4.61it/s]

Processing tickers:  55%|█████▌    | 3781/6855 [13:31<10:55,  4.69it/s]

Processing tickers:  55%|█████▌    | 3782/6855 [13:31<11:13,  4.56it/s]

Processing tickers:  55%|█████▌    | 3783/6855 [13:31<11:02,  4.64it/s]

Processing tickers:  55%|█████▌    | 3784/6855 [13:31<11:12,  4.57it/s]

Processing tickers:  55%|█████▌    | 3785/6855 [13:32<11:03,  4.63it/s]

Processing tickers:  55%|█████▌    | 3786/6855 [13:32<10:53,  4.70it/s]

Processing tickers:  55%|█████▌    | 3787/6855 [13:32<10:48,  4.73it/s]

Processing tickers:  55%|█████▌    | 3788/6855 [13:32<11:21,  4.50it/s]

Processing tickers:  55%|█████▌    | 3789/6855 [13:32<11:08,  4.58it/s]

Processing tickers:  55%|█████▌    | 3790/6855 [13:33<11:02,  4.63it/s]

Processing tickers:  55%|█████▌    | 3791/6855 [13:33<10:54,  4.68it/s]

Processing tickers:  55%|█████▌    | 3792/6855 [13:33<10:45,  4.74it/s]

Processing tickers:  55%|█████▌    | 3793/6855 [13:33<10:48,  4.72it/s]

Processing tickers:  55%|█████▌    | 3794/6855 [13:33<10:45,  4.74it/s]

Processing tickers:  55%|█████▌    | 3795/6855 [13:34<10:45,  4.74it/s]

Processing tickers:  55%|█████▌    | 3796/6855 [13:34<10:49,  4.71it/s]

Processing tickers:  55%|█████▌    | 3797/6855 [13:34<11:11,  4.55it/s]

Processing tickers:  55%|█████▌    | 3798/6855 [13:34<11:03,  4.61it/s]

Processing tickers:  55%|█████▌    | 3799/6855 [13:35<10:59,  4.63it/s]

Processing tickers:  55%|█████▌    | 3800/6855 [13:35<11:08,  4.57it/s]

Processing tickers:  55%|█████▌    | 3801/6855 [13:35<10:56,  4.66it/s]

Processing tickers:  55%|█████▌    | 3802/6855 [13:35<10:50,  4.70it/s]

Processing tickers:  55%|█████▌    | 3803/6855 [13:35<10:47,  4.71it/s]

Processing tickers:  55%|█████▌    | 3804/6855 [13:36<11:00,  4.62it/s]

Processing tickers:  56%|█████▌    | 3805/6855 [13:36<10:55,  4.66it/s]

Processing tickers:  56%|█████▌    | 3806/6855 [13:36<11:01,  4.61it/s]

Processing tickers:  56%|█████▌    | 3807/6855 [13:36<11:13,  4.52it/s]

Processing tickers:  56%|█████▌    | 3808/6855 [13:36<10:58,  4.62it/s]

Processing tickers:  56%|█████▌    | 3809/6855 [13:37<10:55,  4.64it/s]

Processing tickers:  56%|█████▌    | 3810/6855 [13:37<11:06,  4.57it/s]

Processing tickers:  56%|█████▌    | 3811/6855 [13:37<10:53,  4.66it/s]

Processing tickers:  56%|█████▌    | 3812/6855 [13:37<11:08,  4.55it/s]

Processing tickers:  56%|█████▌    | 3813/6855 [13:38<11:01,  4.60it/s]

Processing tickers:  56%|█████▌    | 3814/6855 [13:38<10:54,  4.64it/s]

Processing tickers:  56%|█████▌    | 3815/6855 [13:38<11:06,  4.56it/s]

Processing tickers:  56%|█████▌    | 3816/6855 [13:38<11:01,  4.60it/s]

Processing tickers:  56%|█████▌    | 3817/6855 [13:38<10:49,  4.67it/s]

Processing tickers:  56%|█████▌    | 3818/6855 [13:39<10:45,  4.71it/s]

Processing tickers:  56%|█████▌    | 3819/6855 [13:39<10:40,  4.74it/s]

Processing tickers:  56%|█████▌    | 3820/6855 [13:39<10:40,  4.74it/s]

Processing tickers:  56%|█████▌    | 3821/6855 [13:39<10:39,  4.75it/s]

Processing tickers:  56%|█████▌    | 3822/6855 [13:39<10:44,  4.70it/s]

Processing tickers:  56%|█████▌    | 3823/6855 [13:40<10:40,  4.74it/s]

Processing tickers:  56%|█████▌    | 3824/6855 [13:40<10:37,  4.75it/s]

Processing tickers:  56%|█████▌    | 3825/6855 [13:40<10:41,  4.72it/s]

Processing tickers:  56%|█████▌    | 3826/6855 [13:40<10:38,  4.75it/s]

Processing tickers:  56%|█████▌    | 3827/6855 [13:41<10:48,  4.67it/s]

Processing tickers:  56%|█████▌    | 3828/6855 [13:41<11:07,  4.53it/s]

Processing tickers:  56%|█████▌    | 3829/6855 [13:41<10:59,  4.59it/s]

Processing tickers:  56%|█████▌    | 3830/6855 [13:41<11:19,  4.45it/s]

Processing tickers:  56%|█████▌    | 3831/6855 [13:41<11:23,  4.42it/s]

Processing tickers:  56%|█████▌    | 3832/6855 [13:42<11:29,  4.38it/s]

Processing tickers:  56%|█████▌    | 3833/6855 [13:42<11:09,  4.52it/s]

Processing tickers:  56%|█████▌    | 3834/6855 [13:42<10:56,  4.60it/s]

Processing tickers:  56%|█████▌    | 3835/6855 [13:42<10:52,  4.63it/s]

Processing tickers:  56%|█████▌    | 3836/6855 [13:43<10:47,  4.66it/s]

Processing tickers:  56%|█████▌    | 3837/6855 [13:43<11:02,  4.55it/s]

Processing tickers:  56%|█████▌    | 3838/6855 [13:43<10:52,  4.63it/s]

Processing tickers:  56%|█████▌    | 3839/6855 [13:43<11:17,  4.45it/s]

Processing tickers:  56%|█████▌    | 3840/6855 [13:43<11:05,  4.53it/s]

Processing tickers:  56%|█████▌    | 3841/6855 [13:44<10:53,  4.61it/s]

Processing tickers:  56%|█████▌    | 3842/6855 [13:44<10:46,  4.66it/s]

Processing tickers:  56%|█████▌    | 3843/6855 [13:44<10:39,  4.71it/s]

Processing tickers:  56%|█████▌    | 3844/6855 [13:44<10:38,  4.71it/s]

Processing tickers:  56%|█████▌    | 3845/6855 [13:44<10:34,  4.74it/s]

Processing tickers:  56%|█████▌    | 3846/6855 [13:45<10:37,  4.72it/s]

Processing tickers:  56%|█████▌    | 3847/6855 [13:45<10:58,  4.57it/s]

Processing tickers:  56%|█████▌    | 3848/6855 [13:45<10:48,  4.64it/s]

Processing tickers:  56%|█████▌    | 3849/6855 [13:45<10:44,  4.66it/s]

Processing tickers:  56%|█████▌    | 3850/6855 [13:46<11:01,  4.54it/s]

Processing tickers:  56%|█████▌    | 3851/6855 [13:46<10:53,  4.60it/s]

Processing tickers:  56%|█████▌    | 3852/6855 [13:46<10:55,  4.58it/s]

Processing tickers:  56%|█████▌    | 3853/6855 [13:46<11:08,  4.49it/s]

Processing tickers:  56%|█████▌    | 3854/6855 [13:46<10:57,  4.56it/s]

Processing tickers:  56%|█████▌    | 3855/6855 [13:47<10:48,  4.63it/s]

Processing tickers:  56%|█████▋    | 3856/6855 [13:47<10:54,  4.58it/s]

Processing tickers:  56%|█████▋    | 3857/6855 [13:47<10:47,  4.63it/s]

Processing tickers:  56%|█████▋    | 3858/6855 [13:47<10:39,  4.69it/s]

Processing tickers:  56%|█████▋    | 3859/6855 [13:47<10:36,  4.71it/s]

Processing tickers:  56%|█████▋    | 3860/6855 [13:48<10:30,  4.75it/s]

Processing tickers:  56%|█████▋    | 3861/6855 [13:48<10:23,  4.80it/s]

Processing tickers:  56%|█████▋    | 3862/6855 [13:48<10:24,  4.79it/s]

Processing tickers:  56%|█████▋    | 3863/6855 [13:48<10:22,  4.81it/s]

Processing tickers:  56%|█████▋    | 3864/6855 [13:49<10:18,  4.83it/s]

Processing tickers:  56%|█████▋    | 3865/6855 [13:49<10:26,  4.77it/s]

Processing tickers:  56%|█████▋    | 3866/6855 [13:49<10:26,  4.77it/s]

Processing tickers:  56%|█████▋    | 3867/6855 [13:49<10:27,  4.76it/s]

Processing tickers:  56%|█████▋    | 3868/6855 [13:49<10:30,  4.74it/s]

Processing tickers:  56%|█████▋    | 3869/6855 [13:50<10:42,  4.65it/s]

Processing tickers:  56%|█████▋    | 3870/6855 [13:50<11:01,  4.51it/s]

Processing tickers:  56%|█████▋    | 3871/6855 [13:50<10:48,  4.60it/s]

Processing tickers:  56%|█████▋    | 3872/6855 [13:50<10:39,  4.67it/s]

Processing tickers:  56%|█████▋    | 3873/6855 [13:50<10:32,  4.71it/s]

Processing tickers:  57%|█████▋    | 3874/6855 [13:51<10:39,  4.66it/s]

Processing tickers:  57%|█████▋    | 3875/6855 [13:51<10:42,  4.64it/s]

Processing tickers:  57%|█████▋    | 3876/6855 [13:51<10:38,  4.67it/s]

Processing tickers:  57%|█████▋    | 3877/6855 [13:51<10:30,  4.72it/s]

Processing tickers:  57%|█████▋    | 3878/6855 [13:52<10:47,  4.60it/s]

Processing tickers:  57%|█████▋    | 3879/6855 [13:52<10:58,  4.52it/s]

Processing tickers:  57%|█████▋    | 3880/6855 [13:52<10:59,  4.51it/s]

Processing tickers:  57%|█████▋    | 3881/6855 [13:52<10:49,  4.58it/s]

Processing tickers:  57%|█████▋    | 3882/6855 [13:52<10:43,  4.62it/s]

Processing tickers:  57%|█████▋    | 3883/6855 [13:53<10:34,  4.69it/s]

Processing tickers:  57%|█████▋    | 3884/6855 [13:53<10:27,  4.73it/s]

Processing tickers:  57%|█████▋    | 3885/6855 [13:53<10:47,  4.59it/s]

Processing tickers:  57%|█████▋    | 3886/6855 [13:53<10:35,  4.67it/s]

Processing tickers:  57%|█████▋    | 3887/6855 [13:53<10:44,  4.61it/s]

Processing tickers:  57%|█████▋    | 3888/6855 [13:54<10:34,  4.68it/s]

Processing tickers:  57%|█████▋    | 3889/6855 [13:54<10:33,  4.68it/s]

Processing tickers:  57%|█████▋    | 3890/6855 [13:54<10:33,  4.68it/s]

Processing tickers:  57%|█████▋    | 3891/6855 [13:54<10:42,  4.61it/s]

Processing tickers:  57%|█████▋    | 3892/6855 [13:55<10:30,  4.70it/s]

Processing tickers:  57%|█████▋    | 3893/6855 [13:55<10:26,  4.73it/s]

Processing tickers:  57%|█████▋    | 3894/6855 [13:55<10:23,  4.75it/s]

Processing tickers:  57%|█████▋    | 3895/6855 [13:55<10:44,  4.59it/s]

Processing tickers:  57%|█████▋    | 3896/6855 [13:55<10:34,  4.66it/s]

Processing tickers:  57%|█████▋    | 3897/6855 [13:56<10:33,  4.67it/s]

Processing tickers:  57%|█████▋    | 3898/6855 [13:56<10:23,  4.74it/s]

Processing tickers:  57%|█████▋    | 3899/6855 [13:56<10:39,  4.62it/s]

Processing tickers:  57%|█████▋    | 3900/6855 [13:56<10:35,  4.65it/s]

Processing tickers:  57%|█████▋    | 3901/6855 [13:56<10:30,  4.68it/s]

Processing tickers:  57%|█████▋    | 3902/6855 [13:57<10:39,  4.62it/s]

Processing tickers:  57%|█████▋    | 3903/6855 [13:57<10:36,  4.64it/s]

Processing tickers:  57%|█████▋    | 3904/6855 [13:57<10:29,  4.69it/s]

Processing tickers:  57%|█████▋    | 3905/6855 [13:57<10:41,  4.60it/s]

Processing tickers:  57%|█████▋    | 3906/6855 [13:58<10:42,  4.59it/s]

Processing tickers:  57%|█████▋    | 3907/6855 [13:58<10:36,  4.63it/s]

Processing tickers:  57%|█████▋    | 3908/6855 [13:58<10:33,  4.65it/s]

Processing tickers:  57%|█████▋    | 3909/6855 [13:58<10:35,  4.63it/s]

Processing tickers:  57%|█████▋    | 3910/6855 [13:58<10:35,  4.63it/s]

Processing tickers:  57%|█████▋    | 3911/6855 [13:59<10:50,  4.52it/s]

Processing tickers:  57%|█████▋    | 3912/6855 [13:59<10:56,  4.48it/s]

Processing tickers:  57%|█████▋    | 3913/6855 [13:59<10:42,  4.58it/s]

Processing tickers:  57%|█████▋    | 3914/6855 [13:59<10:35,  4.63it/s]

Processing tickers:  57%|█████▋    | 3915/6855 [14:00<10:28,  4.67it/s]

Processing tickers:  57%|█████▋    | 3916/6855 [14:00<10:29,  4.67it/s]

Processing tickers:  57%|█████▋    | 3917/6855 [14:00<10:25,  4.70it/s]

Processing tickers:  57%|█████▋    | 3918/6855 [14:00<10:23,  4.71it/s]

Processing tickers:  57%|█████▋    | 3919/6855 [14:00<10:33,  4.63it/s]

Processing tickers:  57%|█████▋    | 3920/6855 [14:01<10:29,  4.66it/s]

Processing tickers:  57%|█████▋    | 3921/6855 [14:01<10:25,  4.69it/s]

Processing tickers:  57%|█████▋    | 3922/6855 [14:01<10:20,  4.73it/s]

Processing tickers:  57%|█████▋    | 3923/6855 [14:01<10:31,  4.64it/s]

Processing tickers:  57%|█████▋    | 3924/6855 [14:01<10:50,  4.51it/s]

Processing tickers:  57%|█████▋    | 3925/6855 [14:02<10:40,  4.58it/s]

Processing tickers:  57%|█████▋    | 3926/6855 [14:02<10:32,  4.63it/s]

Processing tickers:  57%|█████▋    | 3927/6855 [14:02<10:32,  4.63it/s]

Processing tickers:  57%|█████▋    | 3928/6855 [14:02<10:29,  4.65it/s]

Processing tickers:  57%|█████▋    | 3929/6855 [14:03<10:20,  4.72it/s]

Processing tickers:  57%|█████▋    | 3930/6855 [14:03<10:15,  4.75it/s]

Processing tickers:  57%|█████▋    | 3931/6855 [14:03<10:18,  4.73it/s]

Processing tickers:  57%|█████▋    | 3932/6855 [14:03<10:22,  4.69it/s]

Processing tickers:  57%|█████▋    | 3933/6855 [14:03<10:19,  4.72it/s]

Processing tickers:  57%|█████▋    | 3934/6855 [14:04<10:12,  4.77it/s]

Processing tickers:  57%|█████▋    | 3935/6855 [14:04<10:11,  4.77it/s]

Processing tickers:  57%|█████▋    | 3936/6855 [14:04<10:07,  4.80it/s]

Processing tickers:  57%|█████▋    | 3937/6855 [14:04<10:11,  4.77it/s]

Processing tickers:  57%|█████▋    | 3938/6855 [14:04<10:14,  4.75it/s]

Processing tickers:  57%|█████▋    | 3939/6855 [14:05<10:31,  4.62it/s]

Processing tickers:  57%|█████▋    | 3940/6855 [14:05<10:24,  4.67it/s]

Processing tickers:  57%|█████▋    | 3941/6855 [14:05<10:21,  4.69it/s]

Processing tickers:  58%|█████▊    | 3942/6855 [14:05<10:17,  4.72it/s]

Processing tickers:  58%|█████▊    | 3943/6855 [14:05<10:11,  4.76it/s]

Processing tickers:  58%|█████▊    | 3944/6855 [14:06<10:11,  4.76it/s]

Processing tickers:  58%|█████▊    | 3945/6855 [14:06<10:12,  4.75it/s]

Processing tickers:  58%|█████▊    | 3946/6855 [14:06<10:07,  4.79it/s]

Processing tickers:  58%|█████▊    | 3947/6855 [14:06<10:05,  4.80it/s]

Processing tickers:  58%|█████▊    | 3948/6855 [14:07<10:25,  4.65it/s]

Processing tickers:  58%|█████▊    | 3949/6855 [14:07<10:17,  4.71it/s]

Processing tickers:  58%|█████▊    | 3950/6855 [14:07<10:15,  4.72it/s]

Processing tickers:  58%|█████▊    | 3951/6855 [14:07<10:43,  4.51it/s]

Processing tickers:  58%|█████▊    | 3952/6855 [14:07<10:37,  4.55it/s]

Processing tickers:  58%|█████▊    | 3953/6855 [14:08<10:27,  4.63it/s]

Processing tickers:  58%|█████▊    | 3954/6855 [14:08<10:22,  4.66it/s]

Processing tickers:  58%|█████▊    | 3955/6855 [14:08<10:25,  4.64it/s]

Processing tickers:  58%|█████▊    | 3956/6855 [14:08<10:19,  4.68it/s]

Processing tickers:  58%|█████▊    | 3957/6855 [14:08<10:12,  4.73it/s]

Processing tickers:  58%|█████▊    | 3958/6855 [14:09<10:07,  4.77it/s]

Processing tickers:  58%|█████▊    | 3959/6855 [14:09<10:07,  4.77it/s]

Processing tickers:  58%|█████▊    | 3960/6855 [14:09<10:06,  4.78it/s]

Processing tickers:  58%|█████▊    | 3961/6855 [14:09<10:13,  4.72it/s]

Processing tickers:  58%|█████▊    | 3962/6855 [14:10<10:13,  4.72it/s]

Processing tickers:  58%|█████▊    | 3963/6855 [14:10<10:23,  4.64it/s]

Processing tickers:  58%|█████▊    | 3964/6855 [14:10<10:38,  4.53it/s]

Processing tickers:  58%|█████▊    | 3965/6855 [14:10<10:37,  4.53it/s]

Processing tickers:  58%|█████▊    | 3966/6855 [14:10<10:27,  4.60it/s]

Processing tickers:  58%|█████▊    | 3967/6855 [14:11<10:28,  4.59it/s]

Processing tickers:  58%|█████▊    | 3968/6855 [14:11<10:24,  4.63it/s]

Processing tickers:  58%|█████▊    | 3969/6855 [14:11<10:18,  4.66it/s]

Processing tickers:  58%|█████▊    | 3970/6855 [14:11<10:17,  4.67it/s]

Processing tickers:  58%|█████▊    | 3971/6855 [14:11<10:23,  4.62it/s]

Processing tickers:  58%|█████▊    | 3972/6855 [14:12<10:13,  4.70it/s]

Processing tickers:  58%|█████▊    | 3973/6855 [14:12<10:20,  4.65it/s]

Processing tickers:  58%|█████▊    | 3974/6855 [14:12<10:23,  4.62it/s]

Processing tickers:  58%|█████▊    | 3975/6855 [14:12<10:21,  4.63it/s]

Processing tickers:  58%|█████▊    | 3976/6855 [14:13<10:12,  4.70it/s]

Processing tickers:  58%|█████▊    | 3977/6855 [14:13<10:28,  4.58it/s]

Processing tickers:  58%|█████▊    | 3978/6855 [14:13<10:38,  4.50it/s]

Processing tickers:  58%|█████▊    | 3979/6855 [14:13<10:44,  4.46it/s]

Processing tickers:  58%|█████▊    | 3980/6855 [14:13<10:30,  4.56it/s]

Processing tickers:  58%|█████▊    | 3981/6855 [14:14<10:23,  4.61it/s]

Processing tickers:  58%|█████▊    | 3982/6855 [14:14<10:18,  4.64it/s]

Processing tickers:  58%|█████▊    | 3983/6855 [14:14<10:24,  4.60it/s]

Processing tickers:  58%|█████▊    | 3984/6855 [14:14<10:20,  4.62it/s]

Processing tickers:  58%|█████▊    | 3985/6855 [14:15<10:15,  4.66it/s]

Processing tickers:  58%|█████▊    | 3986/6855 [14:15<10:15,  4.66it/s]

Processing tickers:  58%|█████▊    | 3987/6855 [14:15<10:12,  4.68it/s]

Processing tickers:  58%|█████▊    | 3988/6855 [14:15<10:06,  4.73it/s]

Processing tickers:  58%|█████▊    | 3989/6855 [14:15<10:04,  4.74it/s]

Processing tickers:  58%|█████▊    | 3990/6855 [14:16<09:59,  4.78it/s]

Processing tickers:  58%|█████▊    | 3991/6855 [14:16<10:16,  4.65it/s]

Processing tickers:  58%|█████▊    | 3992/6855 [14:16<10:08,  4.70it/s]

Processing tickers:  58%|█████▊    | 3993/6855 [14:16<10:09,  4.70it/s]

Processing tickers:  58%|█████▊    | 3994/6855 [14:16<10:04,  4.73it/s]

Processing tickers:  58%|█████▊    | 3995/6855 [14:17<10:01,  4.75it/s]

Processing tickers:  58%|█████▊    | 3996/6855 [14:17<09:59,  4.77it/s]

Processing tickers:  58%|█████▊    | 3997/6855 [14:17<10:11,  4.68it/s]

Processing tickers:  58%|█████▊    | 3998/6855 [14:17<10:05,  4.72it/s]

Processing tickers:  58%|█████▊    | 3999/6855 [14:17<10:02,  4.74it/s]

Processing tickers:  58%|█████▊    | 4000/6855 [14:18<10:21,  4.59it/s]

Processing tickers:  58%|█████▊    | 4001/6855 [14:18<10:17,  4.62it/s]

Processing tickers:  58%|█████▊    | 4002/6855 [14:18<10:08,  4.69it/s]

Processing tickers:  58%|█████▊    | 4003/6855 [14:18<10:31,  4.52it/s]

Processing tickers:  58%|█████▊    | 4004/6855 [14:19<10:26,  4.55it/s]

Processing tickers:  58%|█████▊    | 4005/6855 [14:19<10:13,  4.64it/s]

Processing tickers:  58%|█████▊    | 4006/6855 [14:19<10:09,  4.67it/s]

Processing tickers:  58%|█████▊    | 4007/6855 [14:19<10:04,  4.71it/s]

Processing tickers:  58%|█████▊    | 4008/6855 [14:19<10:09,  4.67it/s]

Processing tickers:  58%|█████▊    | 4009/6855 [14:20<10:22,  4.57it/s]

Processing tickers:  58%|█████▊    | 4010/6855 [14:20<10:11,  4.65it/s]

Processing tickers:  59%|█████▊    | 4011/6855 [14:20<10:18,  4.60it/s]

Processing tickers:  59%|█████▊    | 4012/6855 [14:20<10:16,  4.61it/s]

Processing tickers:  59%|█████▊    | 4013/6855 [14:21<10:16,  4.61it/s]

Processing tickers:  59%|█████▊    | 4014/6855 [14:21<10:10,  4.66it/s]

Processing tickers:  59%|█████▊    | 4015/6855 [14:21<10:02,  4.71it/s]

Processing tickers:  59%|█████▊    | 4016/6855 [14:21<10:01,  4.72it/s]

Processing tickers:  59%|█████▊    | 4017/6855 [14:21<09:57,  4.75it/s]

Processing tickers:  59%|█████▊    | 4018/6855 [14:22<09:52,  4.79it/s]

Processing tickers:  59%|█████▊    | 4019/6855 [14:22<09:52,  4.78it/s]

Processing tickers:  59%|█████▊    | 4020/6855 [14:22<10:06,  4.67it/s]

Processing tickers:  59%|█████▊    | 4021/6855 [14:22<10:07,  4.67it/s]

Processing tickers:  59%|█████▊    | 4022/6855 [14:22<10:21,  4.56it/s]

Processing tickers:  59%|█████▊    | 4023/6855 [14:23<10:06,  4.67it/s]

Processing tickers:  59%|█████▊    | 4024/6855 [14:23<09:59,  4.72it/s]

Processing tickers:  59%|█████▊    | 4025/6855 [14:23<10:01,  4.71it/s]

Processing tickers:  59%|█████▊    | 4026/6855 [14:23<10:00,  4.71it/s]

Processing tickers:  59%|█████▊    | 4027/6855 [14:24<10:10,  4.63it/s]

Processing tickers:  59%|█████▉    | 4028/6855 [14:24<10:07,  4.65it/s]

Processing tickers:  59%|█████▉    | 4029/6855 [14:24<10:01,  4.70it/s]

Processing tickers:  59%|█████▉    | 4030/6855 [14:24<10:04,  4.67it/s]

Processing tickers:  59%|█████▉    | 4031/6855 [14:24<10:02,  4.69it/s]

Processing tickers:  59%|█████▉    | 4032/6855 [14:25<10:22,  4.54it/s]

Processing tickers:  59%|█████▉    | 4033/6855 [14:25<10:15,  4.59it/s]

Processing tickers:  59%|█████▉    | 4034/6855 [14:25<10:06,  4.65it/s]

Processing tickers:  59%|█████▉    | 4035/6855 [14:25<10:02,  4.68it/s]

Processing tickers:  59%|█████▉    | 4036/6855 [14:25<09:55,  4.74it/s]

Processing tickers:  59%|█████▉    | 4037/6855 [14:26<09:48,  4.78it/s]

Processing tickers:  59%|█████▉    | 4038/6855 [14:26<09:48,  4.79it/s]

Processing tickers:  59%|█████▉    | 4039/6855 [14:26<09:54,  4.74it/s]

Processing tickers:  59%|█████▉    | 4040/6855 [14:26<09:55,  4.73it/s]

Processing tickers:  59%|█████▉    | 4041/6855 [14:26<09:59,  4.70it/s]

Processing tickers:  59%|█████▉    | 4042/6855 [14:27<09:57,  4.71it/s]

Processing tickers:  59%|█████▉    | 4043/6855 [14:27<09:53,  4.74it/s]

Processing tickers:  59%|█████▉    | 4044/6855 [14:27<10:00,  4.68it/s]

Processing tickers:  59%|█████▉    | 4045/6855 [14:27<10:05,  4.64it/s]

Processing tickers:  59%|█████▉    | 4046/6855 [14:28<09:56,  4.71it/s]

Processing tickers:  59%|█████▉    | 4047/6855 [14:28<09:56,  4.71it/s]

Processing tickers:  59%|█████▉    | 4048/6855 [14:28<10:08,  4.61it/s]

Processing tickers:  59%|█████▉    | 4049/6855 [14:28<10:09,  4.60it/s]

Processing tickers:  59%|█████▉    | 4050/6855 [14:28<10:10,  4.60it/s]

Processing tickers:  59%|█████▉    | 4051/6855 [14:29<10:17,  4.54it/s]

Processing tickers:  59%|█████▉    | 4052/6855 [14:29<10:16,  4.54it/s]

Processing tickers:  59%|█████▉    | 4053/6855 [14:29<10:21,  4.51it/s]

Processing tickers:  59%|█████▉    | 4054/6855 [14:29<10:30,  4.45it/s]

Processing tickers:  59%|█████▉    | 4055/6855 [14:30<10:16,  4.54it/s]

Processing tickers:  59%|█████▉    | 4056/6855 [14:30<10:29,  4.45it/s]

Processing tickers:  59%|█████▉    | 4057/6855 [14:30<10:18,  4.52it/s]

Processing tickers:  59%|█████▉    | 4058/6855 [14:30<10:18,  4.52it/s]

Processing tickers:  59%|█████▉    | 4059/6855 [14:30<10:09,  4.59it/s]

Processing tickers:  59%|█████▉    | 4060/6855 [14:31<10:05,  4.61it/s]

Processing tickers:  59%|█████▉    | 4061/6855 [14:31<09:58,  4.67it/s]

Processing tickers:  59%|█████▉    | 4062/6855 [14:31<09:55,  4.69it/s]

Processing tickers:  59%|█████▉    | 4063/6855 [14:31<10:10,  4.57it/s]

Processing tickers:  59%|█████▉    | 4064/6855 [14:32<10:16,  4.53it/s]

Processing tickers:  59%|█████▉    | 4065/6855 [14:32<10:08,  4.59it/s]

Processing tickers:  59%|█████▉    | 4066/6855 [14:32<10:13,  4.55it/s]

Processing tickers:  59%|█████▉    | 4067/6855 [14:32<10:13,  4.54it/s]

Processing tickers:  59%|█████▉    | 4068/6855 [14:32<10:08,  4.58it/s]

Processing tickers:  59%|█████▉    | 4069/6855 [14:33<10:18,  4.50it/s]

Processing tickers:  59%|█████▉    | 4070/6855 [14:33<10:03,  4.61it/s]

Processing tickers:  59%|█████▉    | 4071/6855 [14:33<10:00,  4.64it/s]

Processing tickers:  59%|█████▉    | 4072/6855 [14:33<09:54,  4.68it/s]

Processing tickers:  59%|█████▉    | 4073/6855 [14:33<09:54,  4.68it/s]

Processing tickers:  59%|█████▉    | 4074/6855 [14:34<09:48,  4.73it/s]

Processing tickers:  59%|█████▉    | 4075/6855 [14:34<09:43,  4.76it/s]

Processing tickers:  59%|█████▉    | 4076/6855 [14:34<09:59,  4.63it/s]

Processing tickers:  59%|█████▉    | 4077/6855 [14:34<09:52,  4.69it/s]

Processing tickers:  59%|█████▉    | 4078/6855 [14:35<10:04,  4.59it/s]

Processing tickers:  60%|█████▉    | 4079/6855 [14:35<09:57,  4.64it/s]

Processing tickers:  60%|█████▉    | 4080/6855 [14:35<09:57,  4.64it/s]

Processing tickers:  60%|█████▉    | 4081/6855 [14:35<09:50,  4.70it/s]

Processing tickers:  60%|█████▉    | 4082/6855 [14:35<09:59,  4.63it/s]

Processing tickers:  60%|█████▉    | 4083/6855 [14:36<09:51,  4.69it/s]

Processing tickers:  60%|█████▉    | 4084/6855 [14:36<09:48,  4.71it/s]

Processing tickers:  60%|█████▉    | 4085/6855 [14:36<09:40,  4.77it/s]

Processing tickers:  60%|█████▉    | 4086/6855 [14:36<09:44,  4.74it/s]

Processing tickers:  60%|█████▉    | 4087/6855 [14:36<09:43,  4.74it/s]

Processing tickers:  60%|█████▉    | 4088/6855 [14:37<09:43,  4.74it/s]

Processing tickers:  60%|█████▉    | 4089/6855 [14:37<09:39,  4.78it/s]

Processing tickers:  60%|█████▉    | 4090/6855 [14:37<09:45,  4.72it/s]

Processing tickers:  60%|█████▉    | 4091/6855 [14:37<09:47,  4.71it/s]

Processing tickers:  60%|█████▉    | 4092/6855 [14:37<09:41,  4.75it/s]

Processing tickers:  60%|█████▉    | 4093/6855 [14:38<09:41,  4.75it/s]

Processing tickers:  60%|█████▉    | 4094/6855 [14:38<09:46,  4.71it/s]

Processing tickers:  60%|█████▉    | 4095/6855 [14:38<09:40,  4.75it/s]

Processing tickers:  60%|█████▉    | 4096/6855 [14:38<09:36,  4.79it/s]

Processing tickers:  60%|█████▉    | 4097/6855 [14:39<09:38,  4.77it/s]

Processing tickers:  60%|█████▉    | 4098/6855 [14:39<09:39,  4.76it/s]

Processing tickers:  60%|█████▉    | 4099/6855 [14:39<09:51,  4.66it/s]

Processing tickers:  60%|█████▉    | 4100/6855 [14:39<09:52,  4.65it/s]

Processing tickers:  60%|█████▉    | 4101/6855 [14:39<09:47,  4.69it/s]

Processing tickers:  60%|█████▉    | 4102/6855 [14:40<09:44,  4.71it/s]

Processing tickers:  60%|█████▉    | 4103/6855 [14:40<09:39,  4.75it/s]

Processing tickers:  60%|█████▉    | 4104/6855 [14:40<09:45,  4.70it/s]

Processing tickers:  60%|█████▉    | 4105/6855 [14:40<09:42,  4.72it/s]

Processing tickers:  60%|█████▉    | 4106/6855 [14:40<09:48,  4.67it/s]

Processing tickers:  60%|█████▉    | 4107/6855 [14:41<09:58,  4.59it/s]

Processing tickers:  60%|█████▉    | 4108/6855 [14:41<09:50,  4.65it/s]

Processing tickers:  60%|█████▉    | 4109/6855 [14:41<09:41,  4.72it/s]

Processing tickers:  60%|█████▉    | 4110/6855 [14:41<09:39,  4.74it/s]

Processing tickers:  60%|█████▉    | 4111/6855 [14:42<09:37,  4.75it/s]

Processing tickers:  60%|█████▉    | 4112/6855 [14:42<09:35,  4.77it/s]

Processing tickers:  60%|██████    | 4113/6855 [14:42<09:36,  4.76it/s]

Processing tickers:  60%|██████    | 4114/6855 [14:42<09:33,  4.78it/s]

Processing tickers:  60%|██████    | 4115/6855 [14:42<09:37,  4.74it/s]

Processing tickers:  60%|██████    | 4116/6855 [14:43<09:41,  4.71it/s]

Processing tickers:  60%|██████    | 4117/6855 [14:43<09:36,  4.75it/s]

Processing tickers:  60%|██████    | 4118/6855 [14:43<09:46,  4.67it/s]

Processing tickers:  60%|██████    | 4119/6855 [14:43<09:45,  4.68it/s]

Processing tickers:  60%|██████    | 4120/6855 [14:43<09:40,  4.71it/s]

Processing tickers:  60%|██████    | 4121/6855 [14:44<09:37,  4.73it/s]

Processing tickers:  60%|██████    | 4122/6855 [14:44<09:37,  4.73it/s]

Processing tickers:  60%|██████    | 4123/6855 [14:44<09:36,  4.74it/s]

Processing tickers:  60%|██████    | 4124/6855 [14:44<09:38,  4.72it/s]

Processing tickers:  60%|██████    | 4125/6855 [14:44<09:32,  4.77it/s]

Processing tickers:  60%|██████    | 4126/6855 [14:45<09:31,  4.77it/s]

Processing tickers:  60%|██████    | 4127/6855 [14:45<09:30,  4.78it/s]

Processing tickers:  60%|██████    | 4128/6855 [14:45<09:28,  4.80it/s]

Processing tickers:  60%|██████    | 4129/6855 [14:45<09:30,  4.78it/s]

Processing tickers:  60%|██████    | 4130/6855 [14:46<09:36,  4.73it/s]

Processing tickers:  60%|██████    | 4131/6855 [14:46<09:38,  4.71it/s]

Processing tickers:  60%|██████    | 4132/6855 [14:46<09:37,  4.72it/s]

Processing tickers:  60%|██████    | 4133/6855 [14:46<09:43,  4.67it/s]

Processing tickers:  60%|██████    | 4134/6855 [14:46<09:38,  4.70it/s]

Processing tickers:  60%|██████    | 4135/6855 [14:47<09:34,  4.73it/s]

Processing tickers:  60%|██████    | 4136/6855 [14:47<09:32,  4.75it/s]

Processing tickers:  60%|██████    | 4137/6855 [14:47<09:36,  4.72it/s]

Processing tickers:  60%|██████    | 4138/6855 [14:47<09:34,  4.73it/s]

Processing tickers:  60%|██████    | 4139/6855 [14:47<09:32,  4.74it/s]

Processing tickers:  60%|██████    | 4140/6855 [14:48<09:29,  4.76it/s]

Processing tickers:  60%|██████    | 4141/6855 [14:48<09:32,  4.74it/s]

Processing tickers:  60%|██████    | 4142/6855 [14:48<09:47,  4.62it/s]

Processing tickers:  60%|██████    | 4143/6855 [14:48<09:42,  4.66it/s]

Processing tickers:  60%|██████    | 4144/6855 [14:49<09:57,  4.54it/s]

Processing tickers:  60%|██████    | 4145/6855 [14:49<09:46,  4.62it/s]

Processing tickers:  60%|██████    | 4146/6855 [14:49<09:38,  4.68it/s]

Processing tickers:  60%|██████    | 4147/6855 [14:49<09:31,  4.74it/s]

Processing tickers:  61%|██████    | 4148/6855 [14:49<09:32,  4.73it/s]

Processing tickers:  61%|██████    | 4149/6855 [14:50<09:41,  4.66it/s]

Processing tickers:  61%|██████    | 4150/6855 [14:50<09:41,  4.65it/s]

Processing tickers:  61%|██████    | 4151/6855 [14:50<09:33,  4.72it/s]

Processing tickers:  61%|██████    | 4152/6855 [14:50<09:45,  4.62it/s]

Processing tickers:  61%|██████    | 4153/6855 [14:50<09:37,  4.68it/s]

Processing tickers:  61%|██████    | 4154/6855 [14:51<09:48,  4.59it/s]

Processing tickers:  61%|██████    | 4155/6855 [14:51<09:39,  4.66it/s]

Processing tickers:  61%|██████    | 4156/6855 [14:51<09:31,  4.72it/s]

Processing tickers:  61%|██████    | 4157/6855 [14:51<09:28,  4.75it/s]

Processing tickers:  61%|██████    | 4158/6855 [14:51<09:27,  4.75it/s]

Processing tickers:  61%|██████    | 4159/6855 [14:52<09:26,  4.76it/s]

Processing tickers:  61%|██████    | 4160/6855 [14:52<09:27,  4.75it/s]

Processing tickers:  61%|██████    | 4161/6855 [14:52<09:29,  4.73it/s]

Processing tickers:  61%|██████    | 4162/6855 [14:52<09:58,  4.50it/s]

Processing tickers:  61%|██████    | 4163/6855 [14:53<09:45,  4.59it/s]

Processing tickers:  61%|██████    | 4164/6855 [14:53<09:52,  4.54it/s]

Processing tickers:  61%|██████    | 4165/6855 [14:53<09:40,  4.63it/s]

Processing tickers:  61%|██████    | 4166/6855 [14:53<09:43,  4.61it/s]

Processing tickers:  61%|██████    | 4167/6855 [14:53<09:45,  4.59it/s]

Processing tickers:  61%|██████    | 4168/6855 [14:54<09:54,  4.52it/s]

Processing tickers:  61%|██████    | 4169/6855 [14:54<09:46,  4.58it/s]

Processing tickers:  61%|██████    | 4170/6855 [14:54<09:39,  4.63it/s]

Processing tickers:  61%|██████    | 4171/6855 [14:54<09:34,  4.67it/s]

Processing tickers:  61%|██████    | 4172/6855 [14:55<09:31,  4.69it/s]

Processing tickers:  61%|██████    | 4173/6855 [14:55<09:26,  4.73it/s]

Processing tickers:  61%|██████    | 4174/6855 [14:55<09:26,  4.73it/s]

Processing tickers:  61%|██████    | 4175/6855 [14:55<09:26,  4.73it/s]

Processing tickers:  61%|██████    | 4176/6855 [14:55<09:27,  4.72it/s]

Processing tickers:  61%|██████    | 4177/6855 [14:56<09:23,  4.75it/s]

Processing tickers:  61%|██████    | 4178/6855 [14:56<09:24,  4.74it/s]

Processing tickers:  61%|██████    | 4179/6855 [14:56<09:24,  4.74it/s]

Processing tickers:  61%|██████    | 4180/6855 [14:56<09:25,  4.73it/s]

Processing tickers:  61%|██████    | 4181/6855 [14:56<09:26,  4.72it/s]

Processing tickers:  61%|██████    | 4182/6855 [14:57<09:24,  4.73it/s]

Processing tickers:  61%|██████    | 4183/6855 [14:57<09:28,  4.70it/s]

Processing tickers:  61%|██████    | 4184/6855 [14:57<09:22,  4.75it/s]

Processing tickers:  61%|██████    | 4185/6855 [14:57<09:18,  4.78it/s]

Processing tickers:  61%|██████    | 4186/6855 [14:57<09:15,  4.81it/s]

Processing tickers:  61%|██████    | 4187/6855 [14:58<09:14,  4.82it/s]

Processing tickers:  61%|██████    | 4188/6855 [14:58<09:11,  4.84it/s]

Processing tickers:  61%|██████    | 4189/6855 [14:58<09:16,  4.79it/s]

Processing tickers:  61%|██████    | 4190/6855 [14:58<09:26,  4.71it/s]

Processing tickers:  61%|██████    | 4191/6855 [14:59<09:25,  4.71it/s]

Processing tickers:  61%|██████    | 4192/6855 [14:59<09:20,  4.75it/s]

Processing tickers:  61%|██████    | 4193/6855 [14:59<09:25,  4.71it/s]

Processing tickers:  61%|██████    | 4194/6855 [14:59<09:19,  4.76it/s]

Processing tickers:  61%|██████    | 4195/6855 [14:59<09:18,  4.76it/s]

Processing tickers:  61%|██████    | 4196/6855 [15:00<09:27,  4.68it/s]

Processing tickers:  61%|██████    | 4197/6855 [15:00<09:25,  4.70it/s]

Processing tickers:  61%|██████    | 4198/6855 [15:00<09:35,  4.62it/s]

Processing tickers:  61%|██████▏   | 4199/6855 [15:00<09:31,  4.65it/s]

Processing tickers:  61%|██████▏   | 4200/6855 [15:00<09:25,  4.69it/s]

Processing tickers:  61%|██████▏   | 4201/6855 [15:01<09:21,  4.72it/s]

Processing tickers:  61%|██████▏   | 4202/6855 [15:01<09:15,  4.77it/s]

Processing tickers:  61%|██████▏   | 4203/6855 [15:01<09:27,  4.67it/s]

Processing tickers:  61%|██████▏   | 4204/6855 [15:01<09:29,  4.66it/s]

Processing tickers:  61%|██████▏   | 4205/6855 [15:01<09:22,  4.71it/s]

Processing tickers:  61%|██████▏   | 4206/6855 [15:02<09:16,  4.76it/s]

Processing tickers:  61%|██████▏   | 4207/6855 [15:02<09:19,  4.73it/s]

Processing tickers:  61%|██████▏   | 4208/6855 [15:02<09:15,  4.76it/s]

Processing tickers:  61%|██████▏   | 4209/6855 [15:02<09:15,  4.76it/s]

Processing tickers:  61%|██████▏   | 4210/6855 [15:03<09:16,  4.76it/s]

Processing tickers:  61%|██████▏   | 4211/6855 [15:03<09:25,  4.68it/s]

Processing tickers:  61%|██████▏   | 4212/6855 [15:03<09:33,  4.61it/s]

Processing tickers:  61%|██████▏   | 4213/6855 [15:03<09:41,  4.54it/s]

Processing tickers:  61%|██████▏   | 4214/6855 [15:03<09:38,  4.56it/s]

Processing tickers:  61%|██████▏   | 4215/6855 [15:04<09:36,  4.58it/s]

Processing tickers:  62%|██████▏   | 4216/6855 [15:04<09:31,  4.62it/s]

Processing tickers:  62%|██████▏   | 4217/6855 [15:04<09:22,  4.69it/s]

Processing tickers:  62%|██████▏   | 4218/6855 [15:04<09:15,  4.75it/s]

Processing tickers:  62%|██████▏   | 4219/6855 [15:04<09:25,  4.66it/s]

Processing tickers:  62%|██████▏   | 4220/6855 [15:05<09:21,  4.69it/s]

Processing tickers:  62%|██████▏   | 4221/6855 [15:05<09:18,  4.71it/s]

Processing tickers:  62%|██████▏   | 4222/6855 [15:05<09:26,  4.65it/s]

Processing tickers:  62%|██████▏   | 4223/6855 [15:05<09:23,  4.67it/s]

Processing tickers:  62%|██████▏   | 4224/6855 [15:06<09:26,  4.64it/s]

Processing tickers:  62%|██████▏   | 4225/6855 [15:06<09:20,  4.69it/s]

Processing tickers:  62%|██████▏   | 4226/6855 [15:06<09:15,  4.73it/s]

Processing tickers:  62%|██████▏   | 4227/6855 [15:06<09:18,  4.71it/s]

Processing tickers:  62%|██████▏   | 4228/6855 [15:06<09:14,  4.74it/s]

Processing tickers:  62%|██████▏   | 4229/6855 [15:07<09:20,  4.69it/s]

Processing tickers:  62%|██████▏   | 4230/6855 [15:07<09:13,  4.74it/s]

Processing tickers:  62%|██████▏   | 4231/6855 [15:07<09:13,  4.74it/s]

Processing tickers:  62%|██████▏   | 4232/6855 [15:07<09:09,  4.77it/s]

Processing tickers:  62%|██████▏   | 4233/6855 [15:07<09:07,  4.79it/s]

Processing tickers:  62%|██████▏   | 4234/6855 [15:08<09:05,  4.80it/s]

Processing tickers:  62%|██████▏   | 4235/6855 [15:08<09:05,  4.80it/s]

Processing tickers:  62%|██████▏   | 4236/6855 [15:08<09:04,  4.81it/s]

Processing tickers:  62%|██████▏   | 4237/6855 [15:08<09:21,  4.66it/s]

Processing tickers:  62%|██████▏   | 4238/6855 [15:09<09:17,  4.69it/s]

Processing tickers:  62%|██████▏   | 4239/6855 [15:09<09:16,  4.70it/s]

Processing tickers:  62%|██████▏   | 4240/6855 [15:09<09:09,  4.76it/s]

Processing tickers:  62%|██████▏   | 4241/6855 [15:09<09:07,  4.78it/s]

Processing tickers:  62%|██████▏   | 4242/6855 [15:09<09:06,  4.78it/s]

Processing tickers:  62%|██████▏   | 4243/6855 [15:10<09:04,  4.79it/s]

Processing tickers:  62%|██████▏   | 4244/6855 [15:10<09:03,  4.81it/s]

Processing tickers:  62%|██████▏   | 4245/6855 [15:10<09:16,  4.69it/s]

Processing tickers:  62%|██████▏   | 4246/6855 [15:10<09:19,  4.67it/s]

Processing tickers:  62%|██████▏   | 4247/6855 [15:10<09:19,  4.67it/s]

Processing tickers:  62%|██████▏   | 4248/6855 [15:11<09:14,  4.70it/s]

Processing tickers:  62%|██████▏   | 4249/6855 [15:11<09:12,  4.72it/s]

Processing tickers:  62%|██████▏   | 4250/6855 [15:11<09:12,  4.72it/s]

Processing tickers:  62%|██████▏   | 4251/6855 [15:11<09:08,  4.75it/s]

Processing tickers:  62%|██████▏   | 4252/6855 [15:11<09:09,  4.74it/s]

Processing tickers:  62%|██████▏   | 4253/6855 [15:12<09:10,  4.73it/s]

Processing tickers:  62%|██████▏   | 4254/6855 [15:12<09:07,  4.75it/s]

Processing tickers:  62%|██████▏   | 4255/6855 [15:12<09:06,  4.76it/s]

Processing tickers:  62%|██████▏   | 4256/6855 [15:12<09:04,  4.77it/s]

Processing tickers:  62%|██████▏   | 4257/6855 [15:13<09:19,  4.64it/s]

Processing tickers:  62%|██████▏   | 4258/6855 [15:13<09:38,  4.49it/s]

Processing tickers:  62%|██████▏   | 4259/6855 [15:13<09:37,  4.49it/s]

Processing tickers:  62%|██████▏   | 4260/6855 [15:13<09:26,  4.58it/s]

Processing tickers:  62%|██████▏   | 4261/6855 [15:13<09:16,  4.66it/s]

Processing tickers:  62%|██████▏   | 4262/6855 [15:14<09:13,  4.69it/s]

Processing tickers:  62%|██████▏   | 4263/6855 [15:14<09:11,  4.70it/s]

Processing tickers:  62%|██████▏   | 4264/6855 [15:14<09:12,  4.69it/s]

Processing tickers:  62%|██████▏   | 4265/6855 [15:14<09:09,  4.71it/s]

Processing tickers:  62%|██████▏   | 4266/6855 [15:14<09:05,  4.74it/s]

Processing tickers:  62%|██████▏   | 4267/6855 [15:15<09:08,  4.72it/s]

Processing tickers:  62%|██████▏   | 4268/6855 [15:15<09:04,  4.75it/s]

Processing tickers:  62%|██████▏   | 4269/6855 [15:15<09:01,  4.78it/s]

Processing tickers:  62%|██████▏   | 4270/6855 [15:15<09:03,  4.76it/s]

Processing tickers:  62%|██████▏   | 4271/6855 [15:16<09:01,  4.77it/s]

Processing tickers:  62%|██████▏   | 4272/6855 [15:16<08:58,  4.80it/s]

Processing tickers:  62%|██████▏   | 4273/6855 [15:16<09:00,  4.78it/s]

Processing tickers:  62%|██████▏   | 4274/6855 [15:16<08:58,  4.80it/s]

Processing tickers:  62%|██████▏   | 4275/6855 [15:16<08:55,  4.82it/s]

Processing tickers:  62%|██████▏   | 4276/6855 [15:17<08:59,  4.78it/s]

Processing tickers:  62%|██████▏   | 4277/6855 [15:17<09:01,  4.76it/s]

Processing tickers:  62%|██████▏   | 4278/6855 [15:17<08:57,  4.79it/s]

Processing tickers:  62%|██████▏   | 4279/6855 [15:17<09:03,  4.74it/s]

Processing tickers:  62%|██████▏   | 4280/6855 [15:17<09:00,  4.77it/s]

Processing tickers:  62%|██████▏   | 4281/6855 [15:18<09:01,  4.76it/s]

Processing tickers:  62%|██████▏   | 4282/6855 [15:18<09:15,  4.63it/s]

Processing tickers:  62%|██████▏   | 4283/6855 [15:18<09:25,  4.55it/s]

Processing tickers:  62%|██████▏   | 4284/6855 [15:18<09:18,  4.61it/s]

Processing tickers:  63%|██████▎   | 4285/6855 [15:18<09:10,  4.67it/s]

Processing tickers:  63%|██████▎   | 4286/6855 [15:19<09:05,  4.71it/s]

Processing tickers:  63%|██████▎   | 4287/6855 [15:19<09:02,  4.73it/s]

Processing tickers:  63%|██████▎   | 4288/6855 [15:19<08:59,  4.76it/s]

Processing tickers:  63%|██████▎   | 4289/6855 [15:19<09:02,  4.73it/s]

Processing tickers:  63%|██████▎   | 4290/6855 [15:20<09:00,  4.75it/s]

Processing tickers:  63%|██████▎   | 4291/6855 [15:20<08:59,  4.76it/s]

Processing tickers:  63%|██████▎   | 4292/6855 [15:20<08:55,  4.79it/s]

Processing tickers:  63%|██████▎   | 4293/6855 [15:20<08:51,  4.82it/s]

Processing tickers:  63%|██████▎   | 4294/6855 [15:20<09:06,  4.69it/s]

Processing tickers:  63%|██████▎   | 4295/6855 [15:21<09:01,  4.72it/s]

Processing tickers:  63%|██████▎   | 4296/6855 [15:21<09:13,  4.62it/s]

Processing tickers:  63%|██████▎   | 4297/6855 [15:21<09:05,  4.69it/s]

Processing tickers:  63%|██████▎   | 4298/6855 [15:21<08:59,  4.74it/s]

Processing tickers:  63%|██████▎   | 4299/6855 [15:21<08:56,  4.76it/s]

Processing tickers:  63%|██████▎   | 4300/6855 [15:22<08:57,  4.75it/s]

Processing tickers:  63%|██████▎   | 4301/6855 [15:22<08:56,  4.76it/s]

Processing tickers:  63%|██████▎   | 4302/6855 [15:22<08:55,  4.77it/s]

Processing tickers:  63%|██████▎   | 4303/6855 [15:22<08:58,  4.74it/s]

Processing tickers:  63%|██████▎   | 4304/6855 [15:22<09:04,  4.68it/s]

Processing tickers:  63%|██████▎   | 4305/6855 [15:23<09:01,  4.71it/s]

Processing tickers:  63%|██████▎   | 4306/6855 [15:23<09:08,  4.64it/s]

Processing tickers:  63%|██████▎   | 4307/6855 [15:23<09:05,  4.67it/s]

Processing tickers:  63%|██████▎   | 4308/6855 [15:23<08:59,  4.72it/s]

Processing tickers:  63%|██████▎   | 4309/6855 [15:24<09:12,  4.61it/s]

Processing tickers:  63%|██████▎   | 4310/6855 [15:24<09:10,  4.62it/s]

Processing tickers:  63%|██████▎   | 4311/6855 [15:24<09:03,  4.68it/s]

Processing tickers:  63%|██████▎   | 4312/6855 [15:24<09:13,  4.59it/s]

Processing tickers:  63%|██████▎   | 4313/6855 [15:24<09:13,  4.59it/s]

Processing tickers:  63%|██████▎   | 4314/6855 [15:25<09:07,  4.64it/s]

Processing tickers:  63%|██████▎   | 4315/6855 [15:25<09:11,  4.60it/s]

Processing tickers:  63%|██████▎   | 4316/6855 [15:25<09:06,  4.65it/s]

Processing tickers:  63%|██████▎   | 4317/6855 [15:25<09:14,  4.58it/s]

Processing tickers:  63%|██████▎   | 4318/6855 [15:26<09:08,  4.62it/s]

Processing tickers:  63%|██████▎   | 4319/6855 [15:26<09:03,  4.66it/s]

Processing tickers:  63%|██████▎   | 4320/6855 [15:26<08:56,  4.73it/s]

Processing tickers:  63%|██████▎   | 4321/6855 [15:26<08:54,  4.74it/s]

Processing tickers:  63%|██████▎   | 4322/6855 [15:26<08:56,  4.73it/s]

Processing tickers:  63%|██████▎   | 4323/6855 [15:27<08:52,  4.75it/s]

Processing tickers:  63%|██████▎   | 4324/6855 [15:27<09:07,  4.62it/s]

Processing tickers:  63%|██████▎   | 4325/6855 [15:27<09:13,  4.57it/s]

Processing tickers:  63%|██████▎   | 4326/6855 [15:27<09:25,  4.47it/s]

Processing tickers:  63%|██████▎   | 4327/6855 [15:27<09:12,  4.57it/s]

Processing tickers:  63%|██████▎   | 4328/6855 [15:28<09:24,  4.48it/s]

Processing tickers:  63%|██████▎   | 4329/6855 [15:28<09:24,  4.47it/s]

Processing tickers:  63%|██████▎   | 4330/6855 [15:28<09:24,  4.47it/s]

Processing tickers:  63%|██████▎   | 4331/6855 [15:28<09:25,  4.47it/s]

Processing tickers:  63%|██████▎   | 4332/6855 [15:29<09:29,  4.43it/s]

Processing tickers:  63%|██████▎   | 4333/6855 [15:29<09:17,  4.53it/s]

Processing tickers:  63%|██████▎   | 4334/6855 [15:29<09:19,  4.51it/s]

Processing tickers:  63%|██████▎   | 4335/6855 [15:29<09:24,  4.46it/s]

Processing tickers:  63%|██████▎   | 4336/6855 [15:29<09:19,  4.51it/s]

Processing tickers:  63%|██████▎   | 4337/6855 [15:30<09:09,  4.58it/s]

Processing tickers:  63%|██████▎   | 4338/6855 [15:30<09:16,  4.52it/s]

Processing tickers:  63%|██████▎   | 4339/6855 [15:30<09:04,  4.62it/s]

Processing tickers:  63%|██████▎   | 4340/6855 [15:30<09:10,  4.57it/s]

Processing tickers:  63%|██████▎   | 4341/6855 [15:31<09:23,  4.46it/s]

Processing tickers:  63%|██████▎   | 4342/6855 [15:31<09:25,  4.45it/s]

Processing tickers:  63%|██████▎   | 4343/6855 [15:31<09:14,  4.53it/s]

Processing tickers:  63%|██████▎   | 4344/6855 [15:31<09:17,  4.51it/s]

Processing tickers:  63%|██████▎   | 4345/6855 [15:31<09:08,  4.58it/s]

Processing tickers:  63%|██████▎   | 4346/6855 [15:32<08:56,  4.68it/s]

Processing tickers:  63%|██████▎   | 4347/6855 [15:32<08:50,  4.73it/s]

Processing tickers:  63%|██████▎   | 4348/6855 [15:32<08:50,  4.73it/s]

Processing tickers:  63%|██████▎   | 4349/6855 [15:32<08:57,  4.67it/s]

Processing tickers:  63%|██████▎   | 4350/6855 [15:33<08:53,  4.70it/s]

Processing tickers:  63%|██████▎   | 4351/6855 [15:33<08:48,  4.74it/s]

Processing tickers:  63%|██████▎   | 4352/6855 [15:33<08:43,  4.78it/s]

Processing tickers:  64%|██████▎   | 4353/6855 [15:33<08:51,  4.70it/s]

Processing tickers:  64%|██████▎   | 4354/6855 [15:33<08:52,  4.69it/s]

Processing tickers:  64%|██████▎   | 4355/6855 [15:34<08:48,  4.73it/s]

Processing tickers:  64%|██████▎   | 4356/6855 [15:34<08:57,  4.65it/s]

Processing tickers:  64%|██████▎   | 4357/6855 [15:34<08:57,  4.65it/s]

Processing tickers:  64%|██████▎   | 4358/6855 [15:34<08:52,  4.69it/s]

Processing tickers:  64%|██████▎   | 4359/6855 [15:34<08:58,  4.63it/s]

Processing tickers:  64%|██████▎   | 4360/6855 [15:35<09:11,  4.53it/s]

Processing tickers:  64%|██████▎   | 4361/6855 [15:35<09:04,  4.58it/s]

Processing tickers:  64%|██████▎   | 4362/6855 [15:35<09:07,  4.56it/s]

Processing tickers:  64%|██████▎   | 4363/6855 [15:35<08:58,  4.62it/s]

Processing tickers:  64%|██████▎   | 4364/6855 [15:36<08:54,  4.66it/s]

Processing tickers:  64%|██████▎   | 4365/6855 [15:36<08:47,  4.72it/s]

Processing tickers:  64%|██████▎   | 4366/6855 [15:36<08:46,  4.72it/s]

Processing tickers:  64%|██████▎   | 4367/6855 [15:36<08:41,  4.77it/s]

Processing tickers:  64%|██████▎   | 4368/6855 [15:36<08:42,  4.76it/s]

Processing tickers:  64%|██████▎   | 4369/6855 [15:37<08:41,  4.76it/s]

Processing tickers:  64%|██████▎   | 4370/6855 [15:37<08:43,  4.75it/s]

Processing tickers:  64%|██████▍   | 4371/6855 [15:37<08:55,  4.64it/s]

Processing tickers:  64%|██████▍   | 4372/6855 [15:37<08:55,  4.64it/s]

Processing tickers:  64%|██████▍   | 4373/6855 [15:37<08:48,  4.69it/s]

Processing tickers:  64%|██████▍   | 4374/6855 [15:38<08:46,  4.72it/s]

Processing tickers:  64%|██████▍   | 4375/6855 [15:38<09:06,  4.53it/s]

Processing tickers:  64%|██████▍   | 4376/6855 [15:38<09:14,  4.47it/s]

Processing tickers:  64%|██████▍   | 4377/6855 [15:38<09:05,  4.54it/s]

Processing tickers:  64%|██████▍   | 4378/6855 [15:39<09:09,  4.50it/s]

Processing tickers:  64%|██████▍   | 4379/6855 [15:39<09:04,  4.55it/s]

Processing tickers:  64%|██████▍   | 4380/6855 [15:39<09:16,  4.44it/s]

Processing tickers:  64%|██████▍   | 4381/6855 [15:39<09:06,  4.53it/s]

Processing tickers:  64%|██████▍   | 4382/6855 [15:39<09:23,  4.39it/s]

Processing tickers:  64%|██████▍   | 4383/6855 [15:40<09:04,  4.54it/s]

Processing tickers:  64%|██████▍   | 4384/6855 [15:40<09:15,  4.45it/s]

Processing tickers:  64%|██████▍   | 4385/6855 [15:40<09:09,  4.50it/s]

Processing tickers:  64%|██████▍   | 4386/6855 [15:40<09:14,  4.45it/s]

Processing tickers:  64%|██████▍   | 4387/6855 [15:41<09:03,  4.54it/s]

Processing tickers:  64%|██████▍   | 4388/6855 [15:41<08:57,  4.59it/s]

Processing tickers:  64%|██████▍   | 4389/6855 [15:41<08:48,  4.67it/s]

Processing tickers:  64%|██████▍   | 4390/6855 [15:41<08:54,  4.61it/s]

Processing tickers:  64%|██████▍   | 4391/6855 [15:41<08:48,  4.66it/s]

Processing tickers:  64%|██████▍   | 4392/6855 [15:42<08:44,  4.70it/s]

Processing tickers:  64%|██████▍   | 4393/6855 [15:42<08:39,  4.74it/s]

Processing tickers:  64%|██████▍   | 4394/6855 [15:42<08:39,  4.74it/s]

Processing tickers:  64%|██████▍   | 4395/6855 [15:42<08:54,  4.61it/s]

Processing tickers:  64%|██████▍   | 4396/6855 [15:42<08:47,  4.66it/s]

Processing tickers:  64%|██████▍   | 4397/6855 [15:43<08:39,  4.73it/s]

Processing tickers:  64%|██████▍   | 4398/6855 [15:43<09:02,  4.53it/s]

Processing tickers:  64%|██████▍   | 4399/6855 [15:43<08:55,  4.58it/s]

Processing tickers:  64%|██████▍   | 4400/6855 [15:43<09:06,  4.49it/s]

Processing tickers:  64%|██████▍   | 4401/6855 [15:44<08:55,  4.58it/s]

Processing tickers:  64%|██████▍   | 4402/6855 [15:44<08:47,  4.65it/s]

Processing tickers:  64%|██████▍   | 4403/6855 [15:44<08:51,  4.61it/s]

Processing tickers:  64%|██████▍   | 4404/6855 [15:44<08:48,  4.64it/s]

Processing tickers:  64%|██████▍   | 4405/6855 [15:44<08:47,  4.65it/s]

Processing tickers:  64%|██████▍   | 4406/6855 [15:45<08:52,  4.60it/s]

Processing tickers:  64%|██████▍   | 4407/6855 [15:45<08:43,  4.68it/s]

Processing tickers:  64%|██████▍   | 4408/6855 [15:45<08:41,  4.69it/s]

Processing tickers:  64%|██████▍   | 4409/6855 [15:45<08:59,  4.53it/s]

Processing tickers:  64%|██████▍   | 4410/6855 [15:46<08:50,  4.61it/s]

Processing tickers:  64%|██████▍   | 4411/6855 [15:46<08:46,  4.64it/s]

Processing tickers:  64%|██████▍   | 4412/6855 [15:46<08:44,  4.66it/s]

Processing tickers:  64%|██████▍   | 4413/6855 [15:46<08:41,  4.68it/s]

Processing tickers:  64%|██████▍   | 4414/6855 [15:46<08:39,  4.70it/s]

Processing tickers:  64%|██████▍   | 4415/6855 [15:47<08:36,  4.72it/s]

Processing tickers:  64%|██████▍   | 4416/6855 [15:47<08:38,  4.71it/s]

Processing tickers:  64%|██████▍   | 4417/6855 [15:47<08:33,  4.75it/s]

Processing tickers:  64%|██████▍   | 4418/6855 [15:47<08:36,  4.72it/s]

Processing tickers:  64%|██████▍   | 4419/6855 [15:47<08:35,  4.72it/s]

Processing tickers:  64%|██████▍   | 4420/6855 [15:48<08:32,  4.75it/s]

Processing tickers:  64%|██████▍   | 4421/6855 [15:48<08:31,  4.76it/s]

Processing tickers:  65%|██████▍   | 4422/6855 [15:48<08:40,  4.67it/s]

Processing tickers:  65%|██████▍   | 4423/6855 [15:48<08:45,  4.63it/s]

Processing tickers:  65%|██████▍   | 4424/6855 [15:48<08:42,  4.65it/s]

Processing tickers:  65%|██████▍   | 4425/6855 [15:49<08:42,  4.66it/s]

Processing tickers:  65%|██████▍   | 4426/6855 [15:49<08:47,  4.60it/s]

Processing tickers:  65%|██████▍   | 4427/6855 [15:49<08:57,  4.51it/s]

Processing tickers:  65%|██████▍   | 4428/6855 [15:49<09:00,  4.49it/s]

Processing tickers:  65%|██████▍   | 4429/6855 [15:50<09:15,  4.37it/s]

Processing tickers:  65%|██████▍   | 4430/6855 [15:50<09:53,  4.08it/s]

Processing tickers:  65%|██████▍   | 4431/6855 [15:50<09:36,  4.20it/s]

Processing tickers:  65%|██████▍   | 4432/6855 [15:50<09:15,  4.36it/s]

Processing tickers:  65%|██████▍   | 4433/6855 [15:51<09:03,  4.46it/s]

Processing tickers:  65%|██████▍   | 4434/6855 [15:51<08:54,  4.53it/s]

Processing tickers:  65%|██████▍   | 4435/6855 [15:51<08:44,  4.62it/s]

Processing tickers:  65%|██████▍   | 4436/6855 [15:51<08:44,  4.61it/s]

Processing tickers:  65%|██████▍   | 4437/6855 [15:51<08:41,  4.64it/s]

Processing tickers:  65%|██████▍   | 4438/6855 [15:52<08:38,  4.66it/s]

Processing tickers:  65%|██████▍   | 4439/6855 [15:52<08:32,  4.72it/s]

Processing tickers:  65%|██████▍   | 4440/6855 [15:52<08:28,  4.75it/s]

Processing tickers:  65%|██████▍   | 4441/6855 [15:52<08:37,  4.67it/s]

Processing tickers:  65%|██████▍   | 4442/6855 [15:52<08:33,  4.70it/s]

Processing tickers:  65%|██████▍   | 4443/6855 [15:53<08:41,  4.63it/s]

Processing tickers:  65%|██████▍   | 4444/6855 [15:53<08:32,  4.71it/s]

Processing tickers:  65%|██████▍   | 4445/6855 [15:53<08:41,  4.62it/s]

Processing tickers:  65%|██████▍   | 4446/6855 [15:53<08:41,  4.62it/s]

Processing tickers:  65%|██████▍   | 4447/6855 [15:54<08:53,  4.51it/s]

Processing tickers:  65%|██████▍   | 4448/6855 [15:54<08:59,  4.46it/s]

Processing tickers:  65%|██████▍   | 4449/6855 [15:54<09:02,  4.44it/s]

Processing tickers:  65%|██████▍   | 4450/6855 [15:54<09:05,  4.41it/s]

Processing tickers:  65%|██████▍   | 4451/6855 [15:54<08:51,  4.52it/s]

Processing tickers:  65%|██████▍   | 4452/6855 [15:55<08:45,  4.57it/s]

Processing tickers:  65%|██████▍   | 4453/6855 [15:55<08:38,  4.63it/s]

Processing tickers:  65%|██████▍   | 4454/6855 [15:55<08:33,  4.67it/s]

Processing tickers:  65%|██████▍   | 4455/6855 [15:55<08:51,  4.51it/s]

Processing tickers:  65%|██████▌   | 4456/6855 [15:56<08:41,  4.60it/s]

Processing tickers:  65%|██████▌   | 4457/6855 [15:56<08:43,  4.58it/s]

Processing tickers:  65%|██████▌   | 4458/6855 [15:56<08:45,  4.56it/s]

Processing tickers:  65%|██████▌   | 4459/6855 [15:56<08:58,  4.45it/s]

Processing tickers:  65%|██████▌   | 4460/6855 [15:56<09:03,  4.41it/s]

Processing tickers:  65%|██████▌   | 4461/6855 [15:57<09:04,  4.39it/s]

Processing tickers:  65%|██████▌   | 4462/6855 [15:57<08:52,  4.49it/s]

Processing tickers:  65%|██████▌   | 4463/6855 [15:57<09:02,  4.41it/s]

Processing tickers:  65%|██████▌   | 4464/6855 [15:57<09:04,  4.39it/s]

Processing tickers:  65%|██████▌   | 4465/6855 [15:58<09:04,  4.39it/s]

Processing tickers:  65%|██████▌   | 4466/6855 [15:58<08:54,  4.47it/s]

Processing tickers:  65%|██████▌   | 4467/6855 [15:58<08:53,  4.47it/s]

Processing tickers:  65%|██████▌   | 4468/6855 [15:58<08:46,  4.54it/s]

Processing tickers:  65%|██████▌   | 4469/6855 [15:58<08:33,  4.65it/s]

Processing tickers:  65%|██████▌   | 4470/6855 [15:59<08:34,  4.64it/s]

Processing tickers:  65%|██████▌   | 4471/6855 [15:59<08:37,  4.60it/s]

Processing tickers:  65%|██████▌   | 4472/6855 [15:59<08:29,  4.67it/s]

Processing tickers:  65%|██████▌   | 4473/6855 [15:59<08:34,  4.63it/s]

Processing tickers:  65%|██████▌   | 4474/6855 [16:00<08:46,  4.53it/s]

Processing tickers:  65%|██████▌   | 4475/6855 [16:00<08:38,  4.59it/s]

Processing tickers:  65%|██████▌   | 4476/6855 [16:00<08:49,  4.49it/s]

Processing tickers:  65%|██████▌   | 4477/6855 [16:00<08:45,  4.53it/s]

Processing tickers:  65%|██████▌   | 4478/6855 [16:00<08:37,  4.59it/s]

Processing tickers:  65%|██████▌   | 4479/6855 [16:01<09:13,  4.30it/s]

Processing tickers:  65%|██████▌   | 4480/6855 [16:01<08:58,  4.41it/s]

Processing tickers:  65%|██████▌   | 4481/6855 [16:01<08:49,  4.48it/s]

Processing tickers:  65%|██████▌   | 4482/6855 [16:01<08:49,  4.48it/s]

Processing tickers:  65%|██████▌   | 4483/6855 [16:02<08:45,  4.52it/s]

Processing tickers:  65%|██████▌   | 4484/6855 [16:02<08:54,  4.44it/s]

Processing tickers:  65%|██████▌   | 4485/6855 [16:02<08:44,  4.52it/s]

Processing tickers:  65%|██████▌   | 4486/6855 [16:02<08:37,  4.58it/s]

Processing tickers:  65%|██████▌   | 4487/6855 [16:02<09:21,  4.22it/s]

Processing tickers:  65%|██████▌   | 4488/6855 [16:03<09:18,  4.24it/s]

Processing tickers:  65%|██████▌   | 4489/6855 [16:03<08:59,  4.38it/s]

Processing tickers:  65%|██████▌   | 4490/6855 [16:03<09:00,  4.37it/s]

Processing tickers:  66%|██████▌   | 4491/6855 [16:03<08:51,  4.45it/s]

Processing tickers:  66%|██████▌   | 4492/6855 [16:04<08:35,  4.59it/s]

Processing tickers:  66%|██████▌   | 4493/6855 [16:04<08:44,  4.50it/s]

Processing tickers:  66%|██████▌   | 4494/6855 [16:04<08:54,  4.42it/s]

Processing tickers:  66%|██████▌   | 4495/6855 [16:04<08:39,  4.54it/s]

Processing tickers:  66%|██████▌   | 4496/6855 [16:04<08:32,  4.60it/s]

Processing tickers:  66%|██████▌   | 4497/6855 [16:05<08:28,  4.64it/s]

Processing tickers:  66%|██████▌   | 4498/6855 [16:05<08:20,  4.71it/s]

Processing tickers:  66%|██████▌   | 4499/6855 [16:05<08:28,  4.63it/s]

Processing tickers:  66%|██████▌   | 4500/6855 [16:05<08:26,  4.65it/s]

Processing tickers:  66%|██████▌   | 4501/6855 [16:06<08:21,  4.69it/s]

Processing tickers:  66%|██████▌   | 4502/6855 [16:06<08:17,  4.73it/s]

Processing tickers:  66%|██████▌   | 4503/6855 [16:06<08:30,  4.60it/s]

Processing tickers:  66%|██████▌   | 4504/6855 [16:06<08:23,  4.67it/s]

Processing tickers:  66%|██████▌   | 4505/6855 [16:06<08:22,  4.68it/s]

Processing tickers:  66%|██████▌   | 4506/6855 [16:07<08:23,  4.67it/s]

Processing tickers:  66%|██████▌   | 4507/6855 [16:07<08:17,  4.72it/s]

Processing tickers:  66%|██████▌   | 4508/6855 [16:07<08:14,  4.75it/s]

Processing tickers:  66%|██████▌   | 4509/6855 [16:07<08:20,  4.69it/s]

Processing tickers:  66%|██████▌   | 4510/6855 [16:07<08:16,  4.72it/s]

Processing tickers:  66%|██████▌   | 4511/6855 [16:08<08:19,  4.70it/s]

Processing tickers:  66%|██████▌   | 4512/6855 [16:08<08:14,  4.74it/s]

Processing tickers:  66%|██████▌   | 4513/6855 [16:08<08:13,  4.75it/s]

Processing tickers:  66%|██████▌   | 4514/6855 [16:08<08:12,  4.75it/s]

Processing tickers:  66%|██████▌   | 4515/6855 [16:08<08:10,  4.77it/s]

Processing tickers:  66%|██████▌   | 4516/6855 [16:09<08:22,  4.65it/s]

Processing tickers:  66%|██████▌   | 4517/6855 [16:09<08:21,  4.66it/s]

Processing tickers:  66%|██████▌   | 4518/6855 [16:09<08:14,  4.72it/s]

Processing tickers:  66%|██████▌   | 4519/6855 [16:09<08:16,  4.70it/s]

Processing tickers:  66%|██████▌   | 4520/6855 [16:10<08:31,  4.57it/s]

Processing tickers:  66%|██████▌   | 4521/6855 [16:10<08:39,  4.49it/s]

Processing tickers:  66%|██████▌   | 4522/6855 [16:10<08:33,  4.55it/s]

Processing tickers:  66%|██████▌   | 4523/6855 [16:10<08:42,  4.46it/s]

Processing tickers:  66%|██████▌   | 4524/6855 [16:10<08:44,  4.44it/s]

Processing tickers:  66%|██████▌   | 4525/6855 [16:11<08:54,  4.36it/s]

Processing tickers:  66%|██████▌   | 4526/6855 [16:11<08:42,  4.46it/s]

Processing tickers:  66%|██████▌   | 4527/6855 [16:11<08:31,  4.55it/s]

Processing tickers:  66%|██████▌   | 4528/6855 [16:11<08:22,  4.63it/s]

Processing tickers:  66%|██████▌   | 4529/6855 [16:12<08:18,  4.67it/s]

Processing tickers:  66%|██████▌   | 4530/6855 [16:12<08:23,  4.62it/s]

Processing tickers:  66%|██████▌   | 4531/6855 [16:12<08:18,  4.67it/s]

Processing tickers:  66%|██████▌   | 4532/6855 [16:12<08:23,  4.62it/s]

Processing tickers:  66%|██████▌   | 4533/6855 [16:12<08:22,  4.62it/s]

Processing tickers:  66%|██████▌   | 4534/6855 [16:13<08:20,  4.63it/s]

Processing tickers:  66%|██████▌   | 4535/6855 [16:13<08:26,  4.58it/s]

Processing tickers:  66%|██████▌   | 4536/6855 [16:13<08:34,  4.51it/s]

Processing tickers:  66%|██████▌   | 4537/6855 [16:13<08:39,  4.46it/s]

Processing tickers:  66%|██████▌   | 4538/6855 [16:14<08:27,  4.56it/s]

Processing tickers:  66%|██████▌   | 4539/6855 [16:14<08:18,  4.64it/s]

Processing tickers:  66%|██████▌   | 4540/6855 [16:14<08:23,  4.60it/s]

Processing tickers:  66%|██████▌   | 4541/6855 [16:14<08:11,  4.70it/s]

Processing tickers:  66%|██████▋   | 4542/6855 [16:14<08:07,  4.75it/s]

Processing tickers:  66%|██████▋   | 4543/6855 [16:15<08:22,  4.60it/s]

Processing tickers:  66%|██████▋   | 4544/6855 [16:15<08:18,  4.64it/s]

Processing tickers:  66%|██████▋   | 4545/6855 [16:15<08:13,  4.68it/s]

Processing tickers:  66%|██████▋   | 4546/6855 [16:15<08:18,  4.63it/s]

Processing tickers:  66%|██████▋   | 4547/6855 [16:15<08:09,  4.72it/s]

Processing tickers:  66%|██████▋   | 4548/6855 [16:16<08:23,  4.58it/s]

Processing tickers:  66%|██████▋   | 4549/6855 [16:16<08:27,  4.55it/s]

Processing tickers:  66%|██████▋   | 4550/6855 [16:16<08:19,  4.61it/s]

Processing tickers:  66%|██████▋   | 4551/6855 [16:16<08:16,  4.64it/s]

Processing tickers:  66%|██████▋   | 4552/6855 [16:17<08:30,  4.51it/s]

Processing tickers:  66%|██████▋   | 4553/6855 [16:17<08:21,  4.59it/s]

Processing tickers:  66%|██████▋   | 4554/6855 [16:17<08:12,  4.67it/s]

Processing tickers:  66%|██████▋   | 4555/6855 [16:17<08:20,  4.59it/s]

Processing tickers:  66%|██████▋   | 4556/6855 [16:17<08:15,  4.64it/s]

Processing tickers:  66%|██████▋   | 4557/6855 [16:18<08:24,  4.55it/s]

Processing tickers:  66%|██████▋   | 4558/6855 [16:18<08:16,  4.63it/s]

Processing tickers:  67%|██████▋   | 4559/6855 [16:18<08:10,  4.68it/s]

Processing tickers:  67%|██████▋   | 4560/6855 [16:18<08:11,  4.67it/s]

Processing tickers:  67%|██████▋   | 4561/6855 [16:18<08:11,  4.67it/s]

Processing tickers:  67%|██████▋   | 4562/6855 [16:19<08:17,  4.61it/s]

Processing tickers:  67%|██████▋   | 4563/6855 [16:19<08:23,  4.55it/s]

Processing tickers:  67%|██████▋   | 4564/6855 [16:19<08:17,  4.61it/s]

Processing tickers:  67%|██████▋   | 4565/6855 [16:19<08:18,  4.60it/s]

Processing tickers:  67%|██████▋   | 4566/6855 [16:20<08:10,  4.67it/s]

Processing tickers:  67%|██████▋   | 4567/6855 [16:20<08:06,  4.71it/s]

Processing tickers:  67%|██████▋   | 4568/6855 [16:20<08:04,  4.72it/s]

Processing tickers:  67%|██████▋   | 4569/6855 [16:20<08:08,  4.68it/s]

Processing tickers:  67%|██████▋   | 4570/6855 [16:20<08:04,  4.72it/s]

Processing tickers:  67%|██████▋   | 4571/6855 [16:21<08:00,  4.76it/s]

Processing tickers:  67%|██████▋   | 4572/6855 [16:21<08:09,  4.66it/s]

Processing tickers:  67%|██████▋   | 4573/6855 [16:21<08:18,  4.58it/s]

Processing tickers:  67%|██████▋   | 4574/6855 [16:21<08:12,  4.64it/s]

Processing tickers:  67%|██████▋   | 4575/6855 [16:21<08:04,  4.70it/s]

Processing tickers:  67%|██████▋   | 4576/6855 [16:22<08:14,  4.61it/s]

Processing tickers:  67%|██████▋   | 4577/6855 [16:22<08:18,  4.57it/s]

Processing tickers:  67%|██████▋   | 4578/6855 [16:22<08:39,  4.38it/s]

Processing tickers:  67%|██████▋   | 4579/6855 [16:22<08:25,  4.50it/s]

Processing tickers:  67%|██████▋   | 4580/6855 [16:23<08:15,  4.59it/s]

Processing tickers:  67%|██████▋   | 4581/6855 [16:23<08:10,  4.64it/s]

Processing tickers:  67%|██████▋   | 4582/6855 [16:23<08:04,  4.69it/s]

Processing tickers:  67%|██████▋   | 4583/6855 [16:23<08:16,  4.57it/s]

Processing tickers:  67%|██████▋   | 4584/6855 [16:23<08:15,  4.59it/s]

Processing tickers:  67%|██████▋   | 4585/6855 [16:24<08:09,  4.64it/s]

Processing tickers:  67%|██████▋   | 4586/6855 [16:24<08:07,  4.66it/s]

Processing tickers:  67%|██████▋   | 4587/6855 [16:24<08:05,  4.67it/s]

Processing tickers:  67%|██████▋   | 4588/6855 [16:24<08:13,  4.59it/s]

Processing tickers:  67%|██████▋   | 4589/6855 [16:25<08:04,  4.68it/s]

Processing tickers:  67%|██████▋   | 4590/6855 [16:25<08:08,  4.64it/s]

Processing tickers:  67%|██████▋   | 4591/6855 [16:25<08:03,  4.68it/s]

Processing tickers:  67%|██████▋   | 4592/6855 [16:25<08:04,  4.67it/s]

Processing tickers:  67%|██████▋   | 4593/6855 [16:25<07:59,  4.72it/s]

Processing tickers:  67%|██████▋   | 4594/6855 [16:26<07:56,  4.74it/s]

Processing tickers:  67%|██████▋   | 4595/6855 [16:26<07:57,  4.73it/s]

Processing tickers:  67%|██████▋   | 4596/6855 [16:26<07:56,  4.74it/s]

Processing tickers:  67%|██████▋   | 4597/6855 [16:26<07:55,  4.74it/s]

Processing tickers:  67%|██████▋   | 4598/6855 [16:26<07:54,  4.76it/s]

Processing tickers:  67%|██████▋   | 4599/6855 [16:27<07:51,  4.78it/s]

Processing tickers:  67%|██████▋   | 4600/6855 [16:27<07:52,  4.78it/s]

Processing tickers:  67%|██████▋   | 4601/6855 [16:27<07:52,  4.77it/s]

Processing tickers:  67%|██████▋   | 4602/6855 [16:27<07:51,  4.77it/s]

Processing tickers:  67%|██████▋   | 4603/6855 [16:27<07:55,  4.74it/s]

Processing tickers:  67%|██████▋   | 4604/6855 [16:28<07:56,  4.72it/s]

Processing tickers:  67%|██████▋   | 4605/6855 [16:28<07:54,  4.74it/s]

Processing tickers:  67%|██████▋   | 4606/6855 [16:28<07:54,  4.74it/s]

Processing tickers:  67%|██████▋   | 4607/6855 [16:28<08:03,  4.65it/s]

Processing tickers:  67%|██████▋   | 4608/6855 [16:29<07:59,  4.69it/s]

Processing tickers:  67%|██████▋   | 4609/6855 [16:29<07:58,  4.69it/s]

Processing tickers:  67%|██████▋   | 4610/6855 [16:29<07:56,  4.71it/s]

Processing tickers:  67%|██████▋   | 4611/6855 [16:29<08:04,  4.63it/s]

Processing tickers:  67%|██████▋   | 4612/6855 [16:29<07:58,  4.69it/s]

Processing tickers:  67%|██████▋   | 4613/6855 [16:30<08:10,  4.58it/s]

Processing tickers:  67%|██████▋   | 4614/6855 [16:30<08:15,  4.52it/s]

Processing tickers:  67%|██████▋   | 4615/6855 [16:30<08:19,  4.48it/s]

Processing tickers:  67%|██████▋   | 4616/6855 [16:30<08:08,  4.58it/s]

Processing tickers:  67%|██████▋   | 4617/6855 [16:31<08:02,  4.64it/s]

Processing tickers:  67%|██████▋   | 4618/6855 [16:31<07:54,  4.71it/s]

Processing tickers:  67%|██████▋   | 4619/6855 [16:31<07:55,  4.70it/s]

Processing tickers:  67%|██████▋   | 4620/6855 [16:31<08:05,  4.60it/s]

Processing tickers:  67%|██████▋   | 4621/6855 [16:31<08:01,  4.64it/s]

Processing tickers:  67%|██████▋   | 4622/6855 [16:32<08:03,  4.62it/s]

Processing tickers:  67%|██████▋   | 4623/6855 [16:32<07:59,  4.66it/s]

Processing tickers:  67%|██████▋   | 4624/6855 [16:32<08:09,  4.56it/s]

Processing tickers:  67%|██████▋   | 4625/6855 [16:32<08:16,  4.49it/s]

Processing tickers:  67%|██████▋   | 4626/6855 [16:32<08:14,  4.51it/s]

Processing tickers:  67%|██████▋   | 4627/6855 [16:33<08:18,  4.47it/s]

Processing tickers:  68%|██████▊   | 4628/6855 [16:33<08:10,  4.54it/s]

Processing tickers:  68%|██████▊   | 4629/6855 [16:33<08:05,  4.58it/s]

Processing tickers:  68%|██████▊   | 4630/6855 [16:33<07:58,  4.65it/s]

Processing tickers:  68%|██████▊   | 4631/6855 [16:34<07:59,  4.63it/s]

Processing tickers:  68%|██████▊   | 4632/6855 [16:34<07:56,  4.67it/s]

Processing tickers:  68%|██████▊   | 4633/6855 [16:34<08:00,  4.62it/s]

Processing tickers:  68%|██████▊   | 4634/6855 [16:34<08:06,  4.57it/s]

Processing tickers:  68%|██████▊   | 4635/6855 [16:34<08:15,  4.48it/s]

Processing tickers:  68%|██████▊   | 4636/6855 [16:35<08:07,  4.55it/s]

Processing tickers:  68%|██████▊   | 4637/6855 [16:35<08:02,  4.60it/s]

Processing tickers:  68%|██████▊   | 4638/6855 [16:35<07:53,  4.68it/s]

Processing tickers:  68%|██████▊   | 4639/6855 [16:35<08:03,  4.58it/s]

Processing tickers:  68%|██████▊   | 4640/6855 [16:36<07:58,  4.63it/s]

Processing tickers:  68%|██████▊   | 4641/6855 [16:36<08:00,  4.61it/s]

Processing tickers:  68%|██████▊   | 4642/6855 [16:36<07:54,  4.67it/s]

Processing tickers:  68%|██████▊   | 4643/6855 [16:36<07:49,  4.71it/s]

Processing tickers:  68%|██████▊   | 4644/6855 [16:36<07:47,  4.73it/s]

Processing tickers:  68%|██████▊   | 4645/6855 [16:37<07:49,  4.71it/s]

Processing tickers:  68%|██████▊   | 4646/6855 [16:37<07:45,  4.75it/s]

Processing tickers:  68%|██████▊   | 4647/6855 [16:37<07:43,  4.77it/s]

Processing tickers:  68%|██████▊   | 4648/6855 [16:37<07:54,  4.65it/s]

Processing tickers:  68%|██████▊   | 4649/6855 [16:37<07:55,  4.64it/s]

Processing tickers:  68%|██████▊   | 4650/6855 [16:38<07:51,  4.68it/s]

Processing tickers:  68%|██████▊   | 4651/6855 [16:38<07:48,  4.71it/s]

Processing tickers:  68%|██████▊   | 4652/6855 [16:38<07:44,  4.74it/s]

Processing tickers:  68%|██████▊   | 4653/6855 [16:38<07:48,  4.70it/s]

Processing tickers:  68%|██████▊   | 4654/6855 [16:38<07:45,  4.73it/s]

Processing tickers:  68%|██████▊   | 4655/6855 [16:39<07:47,  4.70it/s]

Processing tickers:  68%|██████▊   | 4656/6855 [16:39<07:43,  4.74it/s]

Processing tickers:  68%|██████▊   | 4657/6855 [16:39<07:43,  4.75it/s]

Processing tickers:  68%|██████▊   | 4658/6855 [16:39<08:04,  4.53it/s]

Processing tickers:  68%|██████▊   | 4659/6855 [16:40<07:55,  4.61it/s]

Processing tickers:  68%|██████▊   | 4660/6855 [16:40<07:48,  4.69it/s]

Processing tickers:  68%|██████▊   | 4661/6855 [16:40<07:46,  4.71it/s]

Processing tickers:  68%|██████▊   | 4662/6855 [16:40<07:51,  4.65it/s]

Processing tickers:  68%|██████▊   | 4663/6855 [16:40<07:45,  4.71it/s]

Processing tickers:  68%|██████▊   | 4664/6855 [16:41<07:46,  4.70it/s]

Processing tickers:  68%|██████▊   | 4665/6855 [16:41<07:46,  4.69it/s]

Processing tickers:  68%|██████▊   | 4666/6855 [16:41<07:43,  4.72it/s]

Processing tickers:  68%|██████▊   | 4667/6855 [16:41<07:44,  4.71it/s]

Processing tickers:  68%|██████▊   | 4668/6855 [16:41<07:44,  4.71it/s]

Processing tickers:  68%|██████▊   | 4669/6855 [16:42<07:45,  4.70it/s]

Processing tickers:  68%|██████▊   | 4670/6855 [16:42<07:41,  4.73it/s]

Processing tickers:  68%|██████▊   | 4671/6855 [16:42<07:38,  4.76it/s]

Processing tickers:  68%|██████▊   | 4672/6855 [16:42<07:40,  4.74it/s]

Processing tickers:  68%|██████▊   | 4673/6855 [16:43<07:39,  4.75it/s]

Processing tickers:  68%|██████▊   | 4674/6855 [16:43<07:38,  4.75it/s]

Processing tickers:  68%|██████▊   | 4675/6855 [16:43<07:37,  4.76it/s]

Processing tickers:  68%|██████▊   | 4676/6855 [16:43<07:34,  4.80it/s]

Processing tickers:  68%|██████▊   | 4677/6855 [16:43<07:32,  4.82it/s]

Processing tickers:  68%|██████▊   | 4678/6855 [16:44<07:33,  4.80it/s]

Processing tickers:  68%|██████▊   | 4679/6855 [16:44<07:30,  4.83it/s]

Processing tickers:  68%|██████▊   | 4680/6855 [16:44<07:28,  4.85it/s]

Processing tickers:  68%|██████▊   | 4681/6855 [16:44<07:32,  4.80it/s]

Processing tickers:  68%|██████▊   | 4682/6855 [16:44<07:32,  4.81it/s]

Processing tickers:  68%|██████▊   | 4683/6855 [16:45<07:33,  4.79it/s]

Processing tickers:  68%|██████▊   | 4684/6855 [16:45<07:34,  4.78it/s]

Processing tickers:  68%|██████▊   | 4685/6855 [16:45<07:30,  4.82it/s]

Processing tickers:  68%|██████▊   | 4686/6855 [16:45<07:41,  4.70it/s]

Processing tickers:  68%|██████▊   | 4687/6855 [16:45<07:38,  4.73it/s]

Processing tickers:  68%|██████▊   | 4688/6855 [16:46<07:40,  4.71it/s]

Processing tickers:  68%|██████▊   | 4689/6855 [16:46<07:45,  4.66it/s]

Processing tickers:  68%|██████▊   | 4690/6855 [16:46<07:41,  4.69it/s]

Processing tickers:  68%|██████▊   | 4691/6855 [16:46<07:51,  4.59it/s]

Processing tickers:  68%|██████▊   | 4692/6855 [16:47<07:42,  4.68it/s]

Processing tickers:  68%|██████▊   | 4693/6855 [16:47<07:48,  4.62it/s]

Processing tickers:  68%|██████▊   | 4694/6855 [16:47<07:48,  4.61it/s]

Processing tickers:  68%|██████▊   | 4695/6855 [16:47<07:45,  4.64it/s]

Processing tickers:  69%|██████▊   | 4696/6855 [16:47<07:42,  4.67it/s]

Processing tickers:  69%|██████▊   | 4697/6855 [16:48<07:40,  4.69it/s]

Processing tickers:  69%|██████▊   | 4698/6855 [16:48<07:36,  4.73it/s]

Processing tickers:  69%|██████▊   | 4699/6855 [16:48<07:46,  4.63it/s]

Processing tickers:  69%|██████▊   | 4700/6855 [16:48<07:39,  4.69it/s]

Processing tickers:  69%|██████▊   | 4701/6855 [16:48<07:35,  4.73it/s]

Processing tickers:  69%|██████▊   | 4702/6855 [16:49<07:34,  4.73it/s]

Processing tickers:  69%|██████▊   | 4703/6855 [16:49<07:30,  4.78it/s]

Processing tickers:  69%|██████▊   | 4704/6855 [16:49<07:33,  4.75it/s]

Processing tickers:  69%|██████▊   | 4705/6855 [16:49<07:36,  4.71it/s]

Processing tickers:  69%|██████▊   | 4706/6855 [16:50<07:35,  4.72it/s]

Processing tickers:  69%|██████▊   | 4707/6855 [16:50<07:35,  4.72it/s]

Processing tickers:  69%|██████▊   | 4708/6855 [16:50<07:32,  4.74it/s]

Processing tickers:  69%|██████▊   | 4709/6855 [16:50<07:29,  4.78it/s]

Processing tickers:  69%|██████▊   | 4710/6855 [16:50<07:28,  4.78it/s]

Processing tickers:  69%|██████▊   | 4711/6855 [16:51<07:28,  4.78it/s]

Processing tickers:  69%|██████▊   | 4712/6855 [16:51<07:26,  4.80it/s]

Processing tickers:  69%|██████▉   | 4713/6855 [16:51<07:27,  4.79it/s]

Processing tickers:  69%|██████▉   | 4714/6855 [16:51<07:32,  4.73it/s]

Processing tickers:  69%|██████▉   | 4715/6855 [16:51<07:34,  4.71it/s]

Processing tickers:  69%|██████▉   | 4716/6855 [16:52<07:35,  4.70it/s]

Processing tickers:  69%|██████▉   | 4717/6855 [16:52<07:30,  4.74it/s]

Processing tickers:  69%|██████▉   | 4718/6855 [16:52<07:28,  4.76it/s]

Processing tickers:  69%|██████▉   | 4719/6855 [16:52<07:28,  4.76it/s]

Processing tickers:  69%|██████▉   | 4720/6855 [16:52<07:29,  4.75it/s]

Processing tickers:  69%|██████▉   | 4721/6855 [16:53<07:31,  4.72it/s]

Processing tickers:  69%|██████▉   | 4722/6855 [16:53<07:28,  4.75it/s]

Processing tickers:  69%|██████▉   | 4723/6855 [16:53<07:31,  4.72it/s]

Processing tickers:  69%|██████▉   | 4724/6855 [16:53<07:28,  4.75it/s]

Processing tickers:  69%|██████▉   | 4725/6855 [16:54<07:27,  4.76it/s]

Processing tickers:  69%|██████▉   | 4726/6855 [16:54<07:23,  4.80it/s]

Processing tickers:  69%|██████▉   | 4727/6855 [16:54<07:27,  4.76it/s]

Processing tickers:  69%|██████▉   | 4728/6855 [16:54<07:23,  4.79it/s]

Processing tickers:  69%|██████▉   | 4729/6855 [16:54<07:34,  4.68it/s]

Processing tickers:  69%|██████▉   | 4730/6855 [16:55<07:29,  4.73it/s]

Processing tickers:  69%|██████▉   | 4731/6855 [16:55<07:27,  4.74it/s]

Processing tickers:  69%|██████▉   | 4732/6855 [16:55<07:25,  4.76it/s]

Processing tickers:  69%|██████▉   | 4733/6855 [16:55<07:31,  4.70it/s]

Processing tickers:  69%|██████▉   | 4734/6855 [16:55<07:28,  4.73it/s]

Processing tickers:  69%|██████▉   | 4735/6855 [16:56<07:32,  4.69it/s]

Processing tickers:  69%|██████▉   | 4736/6855 [16:56<07:42,  4.58it/s]

Processing tickers:  69%|██████▉   | 4737/6855 [16:56<07:36,  4.64it/s]

Processing tickers:  69%|██████▉   | 4738/6855 [16:56<07:30,  4.70it/s]

Processing tickers:  69%|██████▉   | 4739/6855 [16:56<07:29,  4.70it/s]

Processing tickers:  69%|██████▉   | 4740/6855 [16:57<07:28,  4.72it/s]

Processing tickers:  69%|██████▉   | 4741/6855 [16:57<07:25,  4.75it/s]

Processing tickers:  69%|██████▉   | 4742/6855 [16:57<07:20,  4.79it/s]

Processing tickers:  69%|██████▉   | 4743/6855 [16:57<07:35,  4.63it/s]

Processing tickers:  69%|██████▉   | 4744/6855 [16:58<07:31,  4.68it/s]

Processing tickers:  69%|██████▉   | 4745/6855 [16:58<07:39,  4.59it/s]

Processing tickers:  69%|██████▉   | 4746/6855 [16:58<07:35,  4.63it/s]

Processing tickers:  69%|██████▉   | 4747/6855 [16:58<07:35,  4.63it/s]

Processing tickers:  69%|██████▉   | 4748/6855 [16:58<07:33,  4.65it/s]

Processing tickers:  69%|██████▉   | 4749/6855 [16:59<07:36,  4.61it/s]

Processing tickers:  69%|██████▉   | 4750/6855 [16:59<07:34,  4.63it/s]

Processing tickers:  69%|██████▉   | 4751/6855 [16:59<07:30,  4.67it/s]

Processing tickers:  69%|██████▉   | 4752/6855 [16:59<07:28,  4.69it/s]

Processing tickers:  69%|██████▉   | 4753/6855 [16:59<07:26,  4.71it/s]

Processing tickers:  69%|██████▉   | 4754/6855 [17:00<07:28,  4.69it/s]

Processing tickers:  69%|██████▉   | 4755/6855 [17:00<07:23,  4.73it/s]

Processing tickers:  69%|██████▉   | 4756/6855 [17:00<07:18,  4.79it/s]

Processing tickers:  69%|██████▉   | 4757/6855 [17:00<07:19,  4.78it/s]

Processing tickers:  69%|██████▉   | 4758/6855 [17:01<07:25,  4.71it/s]

Processing tickers:  69%|██████▉   | 4759/6855 [17:01<07:24,  4.71it/s]

Processing tickers:  69%|██████▉   | 4760/6855 [17:01<07:21,  4.75it/s]

Processing tickers:  69%|██████▉   | 4761/6855 [17:01<07:28,  4.67it/s]

Processing tickers:  69%|██████▉   | 4762/6855 [17:01<07:26,  4.69it/s]

Processing tickers:  69%|██████▉   | 4763/6855 [17:02<07:23,  4.72it/s]

Processing tickers:  69%|██████▉   | 4764/6855 [17:02<07:24,  4.71it/s]

Processing tickers:  70%|██████▉   | 4765/6855 [17:02<07:22,  4.72it/s]

Processing tickers:  70%|██████▉   | 4766/6855 [17:02<07:23,  4.71it/s]

Processing tickers:  70%|██████▉   | 4767/6855 [17:02<07:28,  4.66it/s]

Processing tickers:  70%|██████▉   | 4768/6855 [17:03<07:30,  4.63it/s]

Processing tickers:  70%|██████▉   | 4769/6855 [17:03<07:25,  4.68it/s]

Processing tickers:  70%|██████▉   | 4770/6855 [17:03<07:24,  4.69it/s]

Processing tickers:  70%|██████▉   | 4771/6855 [17:03<07:21,  4.72it/s]

Processing tickers:  70%|██████▉   | 4772/6855 [17:04<07:18,  4.75it/s]

Processing tickers:  70%|██████▉   | 4773/6855 [17:04<07:15,  4.78it/s]

Processing tickers:  70%|██████▉   | 4774/6855 [17:04<07:14,  4.79it/s]

Processing tickers:  70%|██████▉   | 4775/6855 [17:04<07:14,  4.79it/s]

Processing tickers:  70%|██████▉   | 4776/6855 [17:04<07:14,  4.78it/s]

Processing tickers:  70%|██████▉   | 4777/6855 [17:05<07:14,  4.78it/s]

Processing tickers:  70%|██████▉   | 4778/6855 [17:05<07:15,  4.77it/s]

Processing tickers:  70%|██████▉   | 4779/6855 [17:05<07:14,  4.78it/s]

Processing tickers:  70%|██████▉   | 4780/6855 [17:05<07:18,  4.74it/s]

Processing tickers:  70%|██████▉   | 4781/6855 [17:05<07:26,  4.64it/s]

Processing tickers:  70%|██████▉   | 4782/6855 [17:06<07:20,  4.71it/s]

Processing tickers:  70%|██████▉   | 4783/6855 [17:06<07:29,  4.61it/s]

Processing tickers:  70%|██████▉   | 4784/6855 [17:06<07:24,  4.66it/s]

Processing tickers:  70%|██████▉   | 4785/6855 [17:06<07:20,  4.70it/s]

Processing tickers:  70%|██████▉   | 4786/6855 [17:06<07:20,  4.70it/s]

Processing tickers:  70%|██████▉   | 4787/6855 [17:07<07:16,  4.74it/s]

Processing tickers:  70%|██████▉   | 4788/6855 [17:07<07:15,  4.75it/s]

Processing tickers:  70%|██████▉   | 4789/6855 [17:07<07:13,  4.77it/s]

Processing tickers:  70%|██████▉   | 4790/6855 [17:07<07:14,  4.75it/s]

Processing tickers:  70%|██████▉   | 4791/6855 [17:08<07:14,  4.75it/s]

Processing tickers:  70%|██████▉   | 4792/6855 [17:08<07:12,  4.77it/s]

Processing tickers:  70%|██████▉   | 4793/6855 [17:08<07:10,  4.79it/s]

Processing tickers:  70%|██████▉   | 4794/6855 [17:08<07:15,  4.73it/s]

Processing tickers:  70%|██████▉   | 4795/6855 [17:08<07:18,  4.70it/s]

Processing tickers:  70%|██████▉   | 4796/6855 [17:09<07:18,  4.70it/s]

Processing tickers:  70%|██████▉   | 4797/6855 [17:09<07:20,  4.67it/s]

Processing tickers:  70%|██████▉   | 4798/6855 [17:09<07:22,  4.65it/s]

Processing tickers:  70%|███████   | 4799/6855 [17:09<07:20,  4.67it/s]

Processing tickers:  70%|███████   | 4800/6855 [17:09<07:15,  4.72it/s]

Processing tickers:  70%|███████   | 4801/6855 [17:10<07:15,  4.72it/s]

Processing tickers:  70%|███████   | 4802/6855 [17:10<07:10,  4.77it/s]

Processing tickers:  70%|███████   | 4803/6855 [17:10<07:14,  4.72it/s]

Processing tickers:  70%|███████   | 4804/6855 [17:10<07:11,  4.75it/s]

Processing tickers:  70%|███████   | 4805/6855 [17:10<07:09,  4.77it/s]

Processing tickers:  70%|███████   | 4806/6855 [17:11<07:20,  4.65it/s]

Processing tickers:  70%|███████   | 4807/6855 [17:11<07:16,  4.69it/s]

Processing tickers:  70%|███████   | 4808/6855 [17:11<07:14,  4.71it/s]

Processing tickers:  70%|███████   | 4809/6855 [17:11<07:11,  4.74it/s]

Processing tickers:  70%|███████   | 4810/6855 [17:12<07:08,  4.77it/s]

Processing tickers:  70%|███████   | 4811/6855 [17:12<07:04,  4.81it/s]

Processing tickers:  70%|███████   | 4812/6855 [17:12<07:03,  4.83it/s]

Processing tickers:  70%|███████   | 4813/6855 [17:12<07:01,  4.84it/s]

Processing tickers:  70%|███████   | 4814/6855 [17:12<07:01,  4.84it/s]

Processing tickers:  70%|███████   | 4815/6855 [17:13<07:00,  4.86it/s]

Processing tickers:  70%|███████   | 4816/6855 [17:13<07:01,  4.83it/s]

Processing tickers:  70%|███████   | 4817/6855 [17:13<07:03,  4.81it/s]

Processing tickers:  70%|███████   | 4818/6855 [17:13<07:09,  4.74it/s]

Processing tickers:  70%|███████   | 4819/6855 [17:13<07:07,  4.77it/s]

Processing tickers:  70%|███████   | 4820/6855 [17:14<07:05,  4.78it/s]

Processing tickers:  70%|███████   | 4821/6855 [17:14<07:02,  4.82it/s]

Processing tickers:  70%|███████   | 4822/6855 [17:14<07:04,  4.79it/s]

Processing tickers:  70%|███████   | 4823/6855 [17:14<07:04,  4.79it/s]

Processing tickers:  70%|███████   | 4824/6855 [17:14<07:10,  4.72it/s]

Processing tickers:  70%|███████   | 4825/6855 [17:15<07:12,  4.69it/s]

Processing tickers:  70%|███████   | 4826/6855 [17:15<07:14,  4.67it/s]

Processing tickers:  70%|███████   | 4827/6855 [17:15<07:13,  4.68it/s]

Processing tickers:  70%|███████   | 4828/6855 [17:15<07:14,  4.67it/s]

Processing tickers:  70%|███████   | 4829/6855 [17:16<07:13,  4.68it/s]

Processing tickers:  70%|███████   | 4830/6855 [17:16<07:15,  4.66it/s]

Processing tickers:  70%|███████   | 4831/6855 [17:16<07:08,  4.73it/s]

Processing tickers:  70%|███████   | 4832/6855 [17:16<07:04,  4.77it/s]

Processing tickers:  71%|███████   | 4833/6855 [17:16<07:05,  4.75it/s]

Processing tickers:  71%|███████   | 4834/6855 [17:17<07:06,  4.74it/s]

Processing tickers:  71%|███████   | 4835/6855 [17:17<07:07,  4.72it/s]

Processing tickers:  71%|███████   | 4836/6855 [17:17<07:06,  4.74it/s]

Processing tickers:  71%|███████   | 4837/6855 [17:17<07:05,  4.75it/s]

Processing tickers:  71%|███████   | 4838/6855 [17:17<07:09,  4.69it/s]

Processing tickers:  71%|███████   | 4839/6855 [17:18<07:05,  4.74it/s]

Processing tickers:  71%|███████   | 4840/6855 [17:18<07:12,  4.66it/s]

Processing tickers:  71%|███████   | 4841/6855 [17:18<07:08,  4.70it/s]

Processing tickers:  71%|███████   | 4842/6855 [17:18<07:05,  4.73it/s]

Processing tickers:  71%|███████   | 4843/6855 [17:19<07:17,  4.60it/s]

Processing tickers:  71%|███████   | 4844/6855 [17:19<07:14,  4.63it/s]

Processing tickers:  71%|███████   | 4845/6855 [17:19<07:15,  4.62it/s]

Processing tickers:  71%|███████   | 4846/6855 [17:19<07:11,  4.65it/s]

Processing tickers:  71%|███████   | 4847/6855 [17:19<07:18,  4.58it/s]

Processing tickers:  71%|███████   | 4848/6855 [17:20<07:15,  4.61it/s]

Processing tickers:  71%|███████   | 4849/6855 [17:20<07:11,  4.65it/s]

Processing tickers:  71%|███████   | 4850/6855 [17:20<07:11,  4.64it/s]

Processing tickers:  71%|███████   | 4851/6855 [17:20<07:13,  4.63it/s]

Processing tickers:  71%|███████   | 4852/6855 [17:20<07:10,  4.65it/s]

Processing tickers:  71%|███████   | 4853/6855 [17:21<07:14,  4.61it/s]

Processing tickers:  71%|███████   | 4854/6855 [17:21<07:10,  4.65it/s]

Processing tickers:  71%|███████   | 4855/6855 [17:21<07:09,  4.65it/s]

Processing tickers:  71%|███████   | 4856/6855 [17:21<07:04,  4.71it/s]

Processing tickers:  71%|███████   | 4857/6855 [17:22<07:05,  4.70it/s]

Processing tickers:  71%|███████   | 4858/6855 [17:22<07:01,  4.74it/s]

Processing tickers:  71%|███████   | 4859/6855 [17:22<07:01,  4.74it/s]

Processing tickers:  71%|███████   | 4860/6855 [17:22<07:00,  4.75it/s]

Processing tickers:  71%|███████   | 4861/6855 [17:22<06:57,  4.77it/s]

Processing tickers:  71%|███████   | 4862/6855 [17:23<07:00,  4.73it/s]

Processing tickers:  71%|███████   | 4863/6855 [17:23<06:57,  4.77it/s]

Processing tickers:  71%|███████   | 4864/6855 [17:23<06:57,  4.77it/s]

Processing tickers:  71%|███████   | 4865/6855 [17:23<07:03,  4.70it/s]

Processing tickers:  71%|███████   | 4866/6855 [17:23<07:01,  4.71it/s]

Processing tickers:  71%|███████   | 4867/6855 [17:24<07:05,  4.68it/s]

Processing tickers:  71%|███████   | 4868/6855 [17:24<06:59,  4.73it/s]

Processing tickers:  71%|███████   | 4869/6855 [17:24<06:56,  4.77it/s]

Processing tickers:  71%|███████   | 4870/6855 [17:24<06:56,  4.76it/s]

Processing tickers:  71%|███████   | 4871/6855 [17:24<06:53,  4.79it/s]

Processing tickers:  71%|███████   | 4872/6855 [17:25<07:02,  4.70it/s]

Processing tickers:  71%|███████   | 4873/6855 [17:25<07:01,  4.70it/s]

Processing tickers:  71%|███████   | 4874/6855 [17:25<06:59,  4.73it/s]

Processing tickers:  71%|███████   | 4875/6855 [17:25<06:56,  4.75it/s]

Processing tickers:  71%|███████   | 4876/6855 [17:26<07:00,  4.70it/s]

Processing tickers:  71%|███████   | 4877/6855 [17:26<06:59,  4.72it/s]

Processing tickers:  71%|███████   | 4878/6855 [17:26<06:56,  4.75it/s]

Processing tickers:  71%|███████   | 4879/6855 [17:26<06:54,  4.77it/s]

Processing tickers:  71%|███████   | 4880/6855 [17:26<06:52,  4.79it/s]

Processing tickers:  71%|███████   | 4881/6855 [17:27<06:57,  4.73it/s]

Processing tickers:  71%|███████   | 4882/6855 [17:27<07:07,  4.61it/s]

Processing tickers:  71%|███████   | 4883/6855 [17:27<07:01,  4.68it/s]

Processing tickers:  71%|███████   | 4884/6855 [17:27<07:08,  4.60it/s]

Processing tickers:  71%|███████▏  | 4885/6855 [17:27<07:01,  4.67it/s]

Processing tickers:  71%|███████▏  | 4886/6855 [17:28<06:59,  4.69it/s]

Processing tickers:  71%|███████▏  | 4887/6855 [17:28<06:59,  4.69it/s]

Processing tickers:  71%|███████▏  | 4888/6855 [17:28<06:56,  4.72it/s]

Processing tickers:  71%|███████▏  | 4889/6855 [17:28<06:52,  4.77it/s]

Processing tickers:  71%|███████▏  | 4890/6855 [17:29<06:57,  4.70it/s]

Processing tickers:  71%|███████▏  | 4891/6855 [17:29<06:58,  4.69it/s]

Processing tickers:  71%|███████▏  | 4892/6855 [17:29<06:57,  4.70it/s]

Processing tickers:  71%|███████▏  | 4893/6855 [17:29<06:55,  4.72it/s]

Processing tickers:  71%|███████▏  | 4894/6855 [17:29<07:08,  4.58it/s]

Processing tickers:  71%|███████▏  | 4895/6855 [17:30<07:13,  4.52it/s]

Processing tickers:  71%|███████▏  | 4896/6855 [17:30<07:17,  4.48it/s]

Processing tickers:  71%|███████▏  | 4897/6855 [17:30<07:09,  4.56it/s]

Processing tickers:  71%|███████▏  | 4898/6855 [17:30<07:04,  4.61it/s]

Processing tickers:  71%|███████▏  | 4899/6855 [17:30<07:11,  4.54it/s]

Processing tickers:  71%|███████▏  | 4900/6855 [17:31<07:05,  4.59it/s]

Processing tickers:  71%|███████▏  | 4901/6855 [17:31<07:01,  4.64it/s]

Processing tickers:  72%|███████▏  | 4902/6855 [17:31<06:56,  4.69it/s]

Processing tickers:  72%|███████▏  | 4903/6855 [17:31<06:51,  4.75it/s]

Processing tickers:  72%|███████▏  | 4904/6855 [17:32<06:49,  4.76it/s]

Processing tickers:  72%|███████▏  | 4905/6855 [17:32<06:49,  4.76it/s]

Processing tickers:  72%|███████▏  | 4906/6855 [17:32<07:03,  4.60it/s]

Processing tickers:  72%|███████▏  | 4907/6855 [17:32<07:02,  4.61it/s]

Processing tickers:  72%|███████▏  | 4908/6855 [17:32<07:08,  4.54it/s]

Processing tickers:  72%|███████▏  | 4909/6855 [17:33<07:15,  4.47it/s]

Processing tickers:  72%|███████▏  | 4910/6855 [17:33<07:10,  4.52it/s]

Processing tickers:  72%|███████▏  | 4911/6855 [17:33<07:01,  4.61it/s]

Processing tickers:  72%|███████▏  | 4912/6855 [17:33<06:57,  4.65it/s]

Processing tickers:  72%|███████▏  | 4913/6855 [17:33<06:53,  4.70it/s]

Processing tickers:  72%|███████▏  | 4914/6855 [17:34<06:48,  4.75it/s]

Processing tickers:  72%|███████▏  | 4915/6855 [17:34<06:44,  4.79it/s]

Processing tickers:  72%|███████▏  | 4916/6855 [17:34<06:41,  4.83it/s]

Processing tickers:  72%|███████▏  | 4917/6855 [17:34<06:45,  4.77it/s]

Processing tickers:  72%|███████▏  | 4918/6855 [17:35<06:45,  4.78it/s]

Processing tickers:  72%|███████▏  | 4919/6855 [17:35<06:45,  4.78it/s]

Processing tickers:  72%|███████▏  | 4920/6855 [17:35<06:52,  4.69it/s]

Processing tickers:  72%|███████▏  | 4921/6855 [17:35<06:48,  4.73it/s]

Processing tickers:  72%|███████▏  | 4922/6855 [17:35<06:50,  4.71it/s]

Processing tickers:  72%|███████▏  | 4923/6855 [17:36<06:50,  4.71it/s]

Processing tickers:  72%|███████▏  | 4924/6855 [17:36<06:46,  4.75it/s]

Processing tickers:  72%|███████▏  | 4925/6855 [17:36<06:48,  4.73it/s]

Processing tickers:  72%|███████▏  | 4926/6855 [17:36<06:50,  4.70it/s]

Processing tickers:  72%|███████▏  | 4927/6855 [17:36<07:04,  4.54it/s]

Processing tickers:  72%|███████▏  | 4928/6855 [17:37<07:00,  4.59it/s]

Processing tickers:  72%|███████▏  | 4929/6855 [17:37<06:52,  4.67it/s]

Processing tickers:  72%|███████▏  | 4930/6855 [17:37<06:48,  4.71it/s]

Processing tickers:  72%|███████▏  | 4931/6855 [17:37<06:46,  4.74it/s]

Processing tickers:  72%|███████▏  | 4932/6855 [17:38<06:46,  4.74it/s]

Processing tickers:  72%|███████▏  | 4933/6855 [17:38<06:55,  4.63it/s]

Processing tickers:  72%|███████▏  | 4934/6855 [17:38<07:00,  4.57it/s]

Processing tickers:  72%|███████▏  | 4935/6855 [17:38<07:08,  4.48it/s]

Processing tickers:  72%|███████▏  | 4936/6855 [17:38<07:01,  4.55it/s]

Processing tickers:  72%|███████▏  | 4937/6855 [17:39<06:57,  4.59it/s]

Processing tickers:  72%|███████▏  | 4938/6855 [17:39<06:58,  4.59it/s]

Processing tickers:  72%|███████▏  | 4939/6855 [17:39<06:56,  4.60it/s]

Processing tickers:  72%|███████▏  | 4940/6855 [17:39<06:49,  4.68it/s]

Processing tickers:  72%|███████▏  | 4941/6855 [17:39<06:49,  4.67it/s]

Processing tickers:  72%|███████▏  | 4942/6855 [17:40<06:47,  4.69it/s]

Processing tickers:  72%|███████▏  | 4943/6855 [17:40<06:54,  4.62it/s]

Processing tickers:  72%|███████▏  | 4944/6855 [17:40<06:47,  4.69it/s]

Processing tickers:  72%|███████▏  | 4945/6855 [17:40<06:49,  4.67it/s]

Processing tickers:  72%|███████▏  | 4946/6855 [17:41<06:46,  4.70it/s]

Processing tickers:  72%|███████▏  | 4947/6855 [17:41<06:44,  4.71it/s]

Processing tickers:  72%|███████▏  | 4948/6855 [17:41<06:42,  4.74it/s]

Processing tickers:  72%|███████▏  | 4949/6855 [17:41<06:46,  4.68it/s]

Processing tickers:  72%|███████▏  | 4950/6855 [17:41<06:45,  4.70it/s]

Processing tickers:  72%|███████▏  | 4951/6855 [17:42<06:45,  4.69it/s]

Processing tickers:  72%|███████▏  | 4952/6855 [17:42<06:46,  4.68it/s]

Processing tickers:  72%|███████▏  | 4953/6855 [17:42<06:43,  4.72it/s]

Processing tickers:  72%|███████▏  | 4954/6855 [17:42<06:53,  4.60it/s]

Processing tickers:  72%|███████▏  | 4955/6855 [17:42<06:51,  4.62it/s]

Processing tickers:  72%|███████▏  | 4956/6855 [17:43<06:47,  4.67it/s]

Processing tickers:  72%|███████▏  | 4957/6855 [17:43<06:40,  4.73it/s]

Processing tickers:  72%|███████▏  | 4958/6855 [17:43<06:39,  4.75it/s]

Processing tickers:  72%|███████▏  | 4959/6855 [17:43<06:38,  4.75it/s]

Processing tickers:  72%|███████▏  | 4960/6855 [17:44<06:41,  4.72it/s]

Processing tickers:  72%|███████▏  | 4961/6855 [17:44<06:42,  4.70it/s]

Processing tickers:  72%|███████▏  | 4962/6855 [17:44<06:43,  4.69it/s]

Processing tickers:  72%|███████▏  | 4963/6855 [17:44<07:00,  4.50it/s]

Processing tickers:  72%|███████▏  | 4964/6855 [17:44<06:51,  4.59it/s]

Processing tickers:  72%|███████▏  | 4965/6855 [17:45<06:48,  4.62it/s]

Processing tickers:  72%|███████▏  | 4966/6855 [17:45<06:43,  4.69it/s]

Processing tickers:  72%|███████▏  | 4967/6855 [17:45<06:41,  4.70it/s]

Processing tickers:  72%|███████▏  | 4968/6855 [17:45<06:39,  4.72it/s]

Processing tickers:  72%|███████▏  | 4969/6855 [17:45<06:35,  4.77it/s]

Processing tickers:  73%|███████▎  | 4970/6855 [17:46<06:38,  4.73it/s]

Processing tickers:  73%|███████▎  | 4971/6855 [17:46<06:39,  4.72it/s]

Processing tickers:  73%|███████▎  | 4972/6855 [17:46<06:38,  4.73it/s]

Processing tickers:  73%|███████▎  | 4973/6855 [17:46<06:37,  4.73it/s]

Processing tickers:  73%|███████▎  | 4974/6855 [17:46<06:33,  4.78it/s]

Processing tickers:  73%|███████▎  | 4975/6855 [17:47<06:30,  4.82it/s]

Processing tickers:  73%|███████▎  | 4976/6855 [17:47<06:38,  4.71it/s]

Processing tickers:  73%|███████▎  | 4977/6855 [17:47<06:39,  4.70it/s]

Processing tickers:  73%|███████▎  | 4978/6855 [17:47<06:52,  4.55it/s]

Processing tickers:  73%|███████▎  | 4979/6855 [17:48<06:47,  4.60it/s]

Processing tickers:  73%|███████▎  | 4980/6855 [17:48<06:42,  4.65it/s]

Processing tickers:  73%|███████▎  | 4981/6855 [17:48<06:39,  4.69it/s]

Processing tickers:  73%|███████▎  | 4982/6855 [17:48<06:49,  4.58it/s]

Processing tickers:  73%|███████▎  | 4983/6855 [17:48<06:49,  4.57it/s]

Processing tickers:  73%|███████▎  | 4984/6855 [17:49<06:44,  4.62it/s]

Processing tickers:  73%|███████▎  | 4985/6855 [17:49<06:37,  4.70it/s]

Processing tickers:  73%|███████▎  | 4986/6855 [17:49<06:45,  4.61it/s]

Processing tickers:  73%|███████▎  | 4987/6855 [17:49<06:38,  4.68it/s]

Processing tickers:  73%|███████▎  | 4988/6855 [17:50<06:38,  4.68it/s]

Processing tickers:  73%|███████▎  | 4989/6855 [17:50<06:33,  4.75it/s]

Processing tickers:  73%|███████▎  | 4990/6855 [17:50<06:30,  4.78it/s]

Processing tickers:  73%|███████▎  | 4991/6855 [17:50<06:30,  4.77it/s]

Processing tickers:  73%|███████▎  | 4992/6855 [17:50<06:41,  4.63it/s]

Processing tickers:  73%|███████▎  | 4993/6855 [17:51<06:48,  4.55it/s]

Processing tickers:  73%|███████▎  | 4994/6855 [17:51<06:48,  4.55it/s]

Processing tickers:  73%|███████▎  | 4995/6855 [17:51<06:47,  4.56it/s]

Processing tickers:  73%|███████▎  | 4996/6855 [17:51<06:49,  4.54it/s]

Processing tickers:  73%|███████▎  | 4997/6855 [17:51<06:45,  4.59it/s]

Processing tickers:  73%|███████▎  | 4998/6855 [17:52<06:38,  4.66it/s]

Processing tickers:  73%|███████▎  | 4999/6855 [17:52<06:34,  4.70it/s]

Processing tickers:  73%|███████▎  | 5000/6855 [17:52<06:31,  4.74it/s]

Processing tickers:  73%|███████▎  | 5001/6855 [17:52<06:37,  4.66it/s]

Processing tickers:  73%|███████▎  | 5002/6855 [17:53<06:45,  4.57it/s]

Processing tickers:  73%|███████▎  | 5003/6855 [17:53<06:42,  4.60it/s]

Processing tickers:  73%|███████▎  | 5004/6855 [17:53<06:36,  4.67it/s]

Processing tickers:  73%|███████▎  | 5005/6855 [17:53<06:39,  4.63it/s]

Processing tickers:  73%|███████▎  | 5006/6855 [17:53<06:49,  4.51it/s]

Processing tickers:  73%|███████▎  | 5007/6855 [17:54<06:43,  4.58it/s]

Processing tickers:  73%|███████▎  | 5008/6855 [17:54<06:38,  4.64it/s]

Processing tickers:  73%|███████▎  | 5009/6855 [17:54<06:37,  4.65it/s]

Processing tickers:  73%|███████▎  | 5010/6855 [17:54<06:32,  4.70it/s]

Processing tickers:  73%|███████▎  | 5011/6855 [17:54<06:38,  4.63it/s]

Processing tickers:  73%|███████▎  | 5012/6855 [17:55<06:36,  4.65it/s]

Processing tickers:  73%|███████▎  | 5013/6855 [17:55<06:52,  4.47it/s]

Processing tickers:  73%|███████▎  | 5014/6855 [17:55<06:43,  4.56it/s]

Processing tickers:  73%|███████▎  | 5015/6855 [17:55<06:54,  4.44it/s]

Processing tickers:  73%|███████▎  | 5016/6855 [17:56<06:59,  4.38it/s]

Processing tickers:  73%|███████▎  | 5017/6855 [17:56<06:55,  4.42it/s]

Processing tickers:  73%|███████▎  | 5018/6855 [17:56<06:45,  4.53it/s]

Processing tickers:  73%|███████▎  | 5019/6855 [17:56<06:37,  4.62it/s]

Processing tickers:  73%|███████▎  | 5020/6855 [17:56<06:37,  4.61it/s]

Processing tickers:  73%|███████▎  | 5021/6855 [17:57<06:47,  4.50it/s]

Processing tickers:  73%|███████▎  | 5022/6855 [17:57<06:52,  4.44it/s]

Processing tickers:  73%|███████▎  | 5023/6855 [17:57<06:41,  4.57it/s]

Processing tickers:  73%|███████▎  | 5024/6855 [17:57<06:35,  4.63it/s]

Processing tickers:  73%|███████▎  | 5025/6855 [17:58<06:32,  4.66it/s]

Processing tickers:  73%|███████▎  | 5026/6855 [17:58<06:46,  4.50it/s]

Processing tickers:  73%|███████▎  | 5027/6855 [17:58<06:37,  4.60it/s]

Processing tickers:  73%|███████▎  | 5028/6855 [17:58<06:43,  4.52it/s]

Processing tickers:  73%|███████▎  | 5029/6855 [17:58<06:37,  4.60it/s]

Processing tickers:  73%|███████▎  | 5030/6855 [17:59<06:35,  4.62it/s]

Processing tickers:  73%|███████▎  | 5031/6855 [17:59<06:32,  4.65it/s]

Processing tickers:  73%|███████▎  | 5032/6855 [17:59<06:35,  4.61it/s]

Processing tickers:  73%|███████▎  | 5033/6855 [17:59<06:31,  4.66it/s]

Processing tickers:  73%|███████▎  | 5034/6855 [18:00<06:30,  4.66it/s]

Processing tickers:  73%|███████▎  | 5035/6855 [18:00<06:38,  4.57it/s]

Processing tickers:  73%|███████▎  | 5036/6855 [18:00<06:34,  4.62it/s]

Processing tickers:  73%|███████▎  | 5037/6855 [18:00<06:35,  4.59it/s]

Processing tickers:  73%|███████▎  | 5038/6855 [18:00<06:33,  4.61it/s]

Processing tickers:  74%|███████▎  | 5039/6855 [18:01<06:49,  4.43it/s]

Processing tickers:  74%|███████▎  | 5040/6855 [18:01<06:41,  4.52it/s]

Processing tickers:  74%|███████▎  | 5041/6855 [18:01<06:38,  4.55it/s]

Processing tickers:  74%|███████▎  | 5042/6855 [18:01<06:30,  4.64it/s]

Processing tickers:  74%|███████▎  | 5043/6855 [18:02<06:39,  4.54it/s]

Processing tickers:  74%|███████▎  | 5044/6855 [18:02<06:34,  4.60it/s]

Processing tickers:  74%|███████▎  | 5045/6855 [18:02<06:43,  4.49it/s]

Processing tickers:  74%|███████▎  | 5046/6855 [18:02<06:40,  4.52it/s]

Processing tickers:  74%|███████▎  | 5047/6855 [18:02<06:41,  4.50it/s]

Processing tickers:  74%|███████▎  | 5048/6855 [18:03<06:34,  4.58it/s]

Processing tickers:  74%|███████▎  | 5049/6855 [18:03<06:27,  4.66it/s]

Processing tickers:  74%|███████▎  | 5050/6855 [18:03<06:31,  4.61it/s]

Processing tickers:  74%|███████▎  | 5051/6855 [18:03<06:25,  4.69it/s]

Processing tickers:  74%|███████▎  | 5052/6855 [18:03<06:20,  4.73it/s]

Processing tickers:  74%|███████▎  | 5053/6855 [18:04<06:21,  4.73it/s]

Processing tickers:  74%|███████▎  | 5054/6855 [18:04<06:29,  4.63it/s]

Processing tickers:  74%|███████▎  | 5055/6855 [18:04<06:25,  4.67it/s]

Processing tickers:  74%|███████▍  | 5056/6855 [18:04<06:22,  4.71it/s]

Processing tickers:  74%|███████▍  | 5057/6855 [18:05<06:22,  4.70it/s]

Processing tickers:  74%|███████▍  | 5058/6855 [18:05<06:33,  4.57it/s]

Processing tickers:  74%|███████▍  | 5059/6855 [18:05<06:31,  4.58it/s]

Processing tickers:  74%|███████▍  | 5060/6855 [18:05<06:30,  4.60it/s]

Processing tickers:  74%|███████▍  | 5061/6855 [18:05<06:23,  4.68it/s]

Processing tickers:  74%|███████▍  | 5062/6855 [18:06<06:28,  4.61it/s]

Processing tickers:  74%|███████▍  | 5063/6855 [18:06<06:25,  4.64it/s]

Processing tickers:  74%|███████▍  | 5064/6855 [18:06<06:20,  4.71it/s]

Processing tickers:  74%|███████▍  | 5065/6855 [18:06<06:18,  4.73it/s]

Processing tickers:  74%|███████▍  | 5066/6855 [18:06<06:20,  4.70it/s]

Processing tickers:  74%|███████▍  | 5067/6855 [18:07<06:18,  4.72it/s]

Processing tickers:  74%|███████▍  | 5068/6855 [18:07<06:15,  4.75it/s]

Processing tickers:  74%|███████▍  | 5069/6855 [18:07<07:00,  4.25it/s]

Processing tickers:  74%|███████▍  | 5070/6855 [18:07<06:44,  4.41it/s]

Processing tickers:  74%|███████▍  | 5071/6855 [18:08<06:35,  4.51it/s]

Processing tickers:  74%|███████▍  | 5072/6855 [18:08<06:38,  4.47it/s]

Processing tickers:  74%|███████▍  | 5073/6855 [18:08<06:29,  4.57it/s]

Processing tickers:  74%|███████▍  | 5074/6855 [18:08<06:24,  4.63it/s]

Processing tickers:  74%|███████▍  | 5075/6855 [18:08<06:20,  4.68it/s]

Processing tickers:  74%|███████▍  | 5076/6855 [18:09<06:19,  4.69it/s]

Processing tickers:  74%|███████▍  | 5077/6855 [18:09<06:28,  4.58it/s]

Processing tickers:  74%|███████▍  | 5078/6855 [18:09<06:22,  4.64it/s]

Processing tickers:  74%|███████▍  | 5079/6855 [18:09<06:18,  4.69it/s]

Processing tickers:  74%|███████▍  | 5080/6855 [18:10<06:25,  4.61it/s]

Processing tickers:  74%|███████▍  | 5081/6855 [18:10<06:22,  4.63it/s]

Processing tickers:  74%|███████▍  | 5082/6855 [18:10<06:18,  4.69it/s]

Processing tickers:  74%|███████▍  | 5083/6855 [18:10<06:15,  4.71it/s]

Processing tickers:  74%|███████▍  | 5084/6855 [18:10<06:17,  4.69it/s]

Processing tickers:  74%|███████▍  | 5085/6855 [18:11<06:24,  4.60it/s]

Processing tickers:  74%|███████▍  | 5086/6855 [18:11<06:23,  4.62it/s]

Processing tickers:  74%|███████▍  | 5087/6855 [18:11<06:19,  4.65it/s]

Processing tickers:  74%|███████▍  | 5088/6855 [18:11<06:28,  4.55it/s]

Processing tickers:  74%|███████▍  | 5089/6855 [18:11<06:29,  4.54it/s]

Processing tickers:  74%|███████▍  | 5090/6855 [18:12<06:21,  4.63it/s]

Processing tickers:  74%|███████▍  | 5091/6855 [18:12<06:16,  4.68it/s]

Processing tickers:  74%|███████▍  | 5092/6855 [18:12<06:18,  4.66it/s]

Processing tickers:  74%|███████▍  | 5093/6855 [18:12<06:14,  4.70it/s]

Processing tickers:  74%|███████▍  | 5094/6855 [18:13<06:11,  4.74it/s]

Processing tickers:  74%|███████▍  | 5095/6855 [18:13<06:10,  4.75it/s]

Processing tickers:  74%|███████▍  | 5096/6855 [18:13<06:11,  4.73it/s]

Processing tickers:  74%|███████▍  | 5097/6855 [18:13<06:07,  4.79it/s]

Processing tickers:  74%|███████▍  | 5098/6855 [18:13<06:06,  4.80it/s]

Processing tickers:  74%|███████▍  | 5099/6855 [18:14<06:06,  4.80it/s]

Processing tickers:  74%|███████▍  | 5100/6855 [18:14<06:17,  4.65it/s]

Processing tickers:  74%|███████▍  | 5101/6855 [18:14<06:15,  4.67it/s]

Processing tickers:  74%|███████▍  | 5102/6855 [18:14<06:13,  4.69it/s]

Processing tickers:  74%|███████▍  | 5103/6855 [18:14<06:09,  4.74it/s]

Processing tickers:  74%|███████▍  | 5104/6855 [18:15<06:10,  4.73it/s]

Processing tickers:  74%|███████▍  | 5105/6855 [18:15<06:08,  4.75it/s]

Processing tickers:  74%|███████▍  | 5106/6855 [18:15<06:06,  4.77it/s]

Processing tickers:  75%|███████▍  | 5107/6855 [18:15<06:06,  4.77it/s]

Processing tickers:  75%|███████▍  | 5108/6855 [18:15<06:07,  4.76it/s]

Processing tickers:  75%|███████▍  | 5109/6855 [18:16<06:08,  4.74it/s]

Processing tickers:  75%|███████▍  | 5110/6855 [18:16<06:12,  4.68it/s]

Processing tickers:  75%|███████▍  | 5111/6855 [18:16<06:12,  4.68it/s]

Processing tickers:  75%|███████▍  | 5112/6855 [18:16<06:13,  4.67it/s]

Processing tickers:  75%|███████▍  | 5113/6855 [18:17<06:12,  4.68it/s]

Processing tickers:  75%|███████▍  | 5114/6855 [18:17<06:08,  4.73it/s]

Processing tickers:  75%|███████▍  | 5115/6855 [18:17<06:04,  4.78it/s]

Processing tickers:  75%|███████▍  | 5116/6855 [18:17<06:03,  4.79it/s]

Processing tickers:  75%|███████▍  | 5117/6855 [18:17<06:14,  4.64it/s]

Processing tickers:  75%|███████▍  | 5118/6855 [18:18<06:12,  4.67it/s]

Processing tickers:  75%|███████▍  | 5119/6855 [18:18<06:21,  4.55it/s]

Processing tickers:  75%|███████▍  | 5120/6855 [18:18<06:12,  4.65it/s]

Processing tickers:  75%|███████▍  | 5121/6855 [18:18<06:11,  4.67it/s]

Processing tickers:  75%|███████▍  | 5122/6855 [18:18<06:11,  4.66it/s]

Processing tickers:  75%|███████▍  | 5123/6855 [18:19<06:08,  4.71it/s]

Processing tickers:  75%|███████▍  | 5124/6855 [18:19<06:04,  4.75it/s]

Processing tickers:  75%|███████▍  | 5125/6855 [18:19<06:05,  4.74it/s]

Processing tickers:  75%|███████▍  | 5126/6855 [18:19<06:15,  4.61it/s]

Processing tickers:  75%|███████▍  | 5127/6855 [18:20<06:12,  4.64it/s]

Processing tickers:  75%|███████▍  | 5128/6855 [18:20<06:08,  4.69it/s]

Processing tickers:  75%|███████▍  | 5129/6855 [18:20<06:03,  4.74it/s]

Processing tickers:  75%|███████▍  | 5130/6855 [18:20<06:03,  4.75it/s]

Processing tickers:  75%|███████▍  | 5131/6855 [18:20<06:00,  4.78it/s]

Processing tickers:  75%|███████▍  | 5132/6855 [18:21<06:01,  4.76it/s]

Processing tickers:  75%|███████▍  | 5133/6855 [18:21<06:12,  4.63it/s]

Processing tickers:  75%|███████▍  | 5134/6855 [18:21<06:07,  4.68it/s]

Processing tickers:  75%|███████▍  | 5135/6855 [18:21<06:09,  4.65it/s]

Processing tickers:  75%|███████▍  | 5136/6855 [18:21<06:05,  4.71it/s]

Processing tickers:  75%|███████▍  | 5137/6855 [18:22<06:03,  4.73it/s]

Processing tickers:  75%|███████▍  | 5138/6855 [18:22<06:00,  4.76it/s]

Processing tickers:  75%|███████▍  | 5139/6855 [18:22<06:00,  4.76it/s]

Processing tickers:  75%|███████▍  | 5140/6855 [18:22<05:58,  4.78it/s]

Processing tickers:  75%|███████▍  | 5141/6855 [18:22<05:57,  4.80it/s]

Processing tickers:  75%|███████▌  | 5142/6855 [18:23<06:07,  4.66it/s]

Processing tickers:  75%|███████▌  | 5143/6855 [18:23<06:12,  4.60it/s]

Processing tickers:  75%|███████▌  | 5144/6855 [18:23<06:11,  4.60it/s]

Processing tickers:  75%|███████▌  | 5145/6855 [18:23<06:05,  4.68it/s]

Processing tickers:  75%|███████▌  | 5146/6855 [18:24<06:07,  4.65it/s]

Processing tickers:  75%|███████▌  | 5147/6855 [18:24<06:06,  4.66it/s]

Processing tickers:  75%|███████▌  | 5148/6855 [18:24<06:11,  4.59it/s]

Processing tickers:  75%|███████▌  | 5149/6855 [18:24<06:05,  4.66it/s]

Processing tickers:  75%|███████▌  | 5150/6855 [18:24<05:59,  4.74it/s]

Processing tickers:  75%|███████▌  | 5151/6855 [18:25<05:57,  4.76it/s]

Processing tickers:  75%|███████▌  | 5152/6855 [18:25<05:55,  4.79it/s]

Processing tickers:  75%|███████▌  | 5153/6855 [18:25<05:53,  4.81it/s]

Processing tickers:  75%|███████▌  | 5154/6855 [18:25<05:51,  4.84it/s]

Processing tickers:  75%|███████▌  | 5155/6855 [18:25<05:50,  4.85it/s]

Processing tickers:  75%|███████▌  | 5156/6855 [18:26<05:51,  4.83it/s]

Processing tickers:  75%|███████▌  | 5157/6855 [18:26<05:59,  4.72it/s]

Processing tickers:  75%|███████▌  | 5158/6855 [18:26<05:58,  4.73it/s]

Processing tickers:  75%|███████▌  | 5159/6855 [18:26<06:02,  4.67it/s]

Processing tickers:  75%|███████▌  | 5160/6855 [18:27<06:01,  4.69it/s]

Processing tickers:  75%|███████▌  | 5161/6855 [18:27<05:57,  4.74it/s]

Processing tickers:  75%|███████▌  | 5162/6855 [18:27<05:53,  4.78it/s]

Processing tickers:  75%|███████▌  | 5163/6855 [18:27<05:54,  4.78it/s]

Processing tickers:  75%|███████▌  | 5164/6855 [18:27<05:53,  4.78it/s]

Processing tickers:  75%|███████▌  | 5165/6855 [18:28<05:51,  4.81it/s]

Processing tickers:  75%|███████▌  | 5166/6855 [18:28<05:50,  4.82it/s]

Processing tickers:  75%|███████▌  | 5167/6855 [18:28<05:50,  4.81it/s]

Processing tickers:  75%|███████▌  | 5168/6855 [18:28<05:55,  4.74it/s]

Processing tickers:  75%|███████▌  | 5169/6855 [18:28<06:00,  4.67it/s]

Processing tickers:  75%|███████▌  | 5170/6855 [18:29<05:57,  4.71it/s]

Processing tickers:  75%|███████▌  | 5171/6855 [18:29<06:00,  4.67it/s]

Processing tickers:  75%|███████▌  | 5172/6855 [18:29<05:55,  4.74it/s]

Processing tickers:  75%|███████▌  | 5173/6855 [18:29<05:55,  4.74it/s]

Processing tickers:  75%|███████▌  | 5174/6855 [18:29<05:58,  4.69it/s]

Processing tickers:  75%|███████▌  | 5175/6855 [18:30<06:01,  4.65it/s]

Processing tickers:  76%|███████▌  | 5176/6855 [18:30<05:55,  4.72it/s]

Processing tickers:  76%|███████▌  | 5177/6855 [18:30<05:53,  4.74it/s]

Processing tickers:  76%|███████▌  | 5178/6855 [18:30<05:52,  4.75it/s]

Processing tickers:  76%|███████▌  | 5179/6855 [18:31<05:55,  4.71it/s]

Processing tickers:  76%|███████▌  | 5180/6855 [18:31<05:53,  4.74it/s]

Processing tickers:  76%|███████▌  | 5181/6855 [18:31<05:50,  4.77it/s]

Processing tickers:  76%|███████▌  | 5182/6855 [18:31<05:48,  4.80it/s]

Processing tickers:  76%|███████▌  | 5183/6855 [18:31<05:51,  4.76it/s]

Processing tickers:  76%|███████▌  | 5184/6855 [18:32<05:51,  4.76it/s]

Processing tickers:  76%|███████▌  | 5185/6855 [18:32<06:00,  4.63it/s]

Processing tickers:  76%|███████▌  | 5186/6855 [18:32<06:06,  4.55it/s]

Processing tickers:  76%|███████▌  | 5187/6855 [18:32<06:12,  4.48it/s]

Processing tickers:  76%|███████▌  | 5188/6855 [18:32<06:02,  4.59it/s]

Processing tickers:  76%|███████▌  | 5189/6855 [18:33<05:59,  4.63it/s]

Processing tickers:  76%|███████▌  | 5190/6855 [18:33<05:57,  4.66it/s]

Processing tickers:  76%|███████▌  | 5191/6855 [18:33<05:56,  4.67it/s]

Processing tickers:  76%|███████▌  | 5192/6855 [18:33<05:57,  4.65it/s]

Processing tickers:  76%|███████▌  | 5193/6855 [18:34<05:56,  4.66it/s]

Processing tickers:  76%|███████▌  | 5194/6855 [18:34<05:55,  4.67it/s]

Processing tickers:  76%|███████▌  | 5195/6855 [18:34<05:53,  4.69it/s]

Processing tickers:  76%|███████▌  | 5196/6855 [18:34<05:57,  4.64it/s]

Processing tickers:  76%|███████▌  | 5197/6855 [18:34<05:54,  4.68it/s]

Processing tickers:  76%|███████▌  | 5198/6855 [18:35<05:51,  4.72it/s]

Processing tickers:  76%|███████▌  | 5199/6855 [18:35<05:47,  4.77it/s]

Processing tickers:  76%|███████▌  | 5200/6855 [18:35<05:50,  4.73it/s]

Processing tickers:  76%|███████▌  | 5201/6855 [18:35<05:46,  4.77it/s]

Processing tickers:  76%|███████▌  | 5202/6855 [18:35<05:45,  4.79it/s]

Processing tickers:  76%|███████▌  | 5203/6855 [18:36<05:43,  4.80it/s]

Processing tickers:  76%|███████▌  | 5204/6855 [18:36<05:43,  4.81it/s]

Processing tickers:  76%|███████▌  | 5205/6855 [18:36<05:41,  4.83it/s]

Processing tickers:  76%|███████▌  | 5206/6855 [18:36<05:43,  4.80it/s]

Processing tickers:  76%|███████▌  | 5207/6855 [18:36<05:43,  4.79it/s]

Processing tickers:  76%|███████▌  | 5208/6855 [18:37<05:56,  4.62it/s]

Processing tickers:  76%|███████▌  | 5209/6855 [18:37<05:53,  4.66it/s]

Processing tickers:  76%|███████▌  | 5210/6855 [18:37<05:51,  4.68it/s]

Processing tickers:  76%|███████▌  | 5211/6855 [18:37<05:51,  4.68it/s]

Processing tickers:  76%|███████▌  | 5212/6855 [18:38<05:55,  4.62it/s]

Processing tickers:  76%|███████▌  | 5213/6855 [18:38<05:54,  4.63it/s]

Processing tickers:  76%|███████▌  | 5214/6855 [18:38<05:50,  4.68it/s]

Processing tickers:  76%|███████▌  | 5215/6855 [18:38<05:50,  4.67it/s]

Processing tickers:  76%|███████▌  | 5216/6855 [18:38<05:53,  4.64it/s]

Processing tickers:  76%|███████▌  | 5217/6855 [18:39<05:52,  4.65it/s]

Processing tickers:  76%|███████▌  | 5218/6855 [18:39<05:53,  4.63it/s]

Processing tickers:  76%|███████▌  | 5219/6855 [18:39<05:48,  4.69it/s]

Processing tickers:  76%|███████▌  | 5220/6855 [18:39<05:49,  4.68it/s]

Processing tickers:  76%|███████▌  | 5221/6855 [18:39<05:46,  4.72it/s]

Processing tickers:  76%|███████▌  | 5222/6855 [18:40<05:46,  4.72it/s]

Processing tickers:  76%|███████▌  | 5223/6855 [18:40<05:41,  4.78it/s]

Processing tickers:  76%|███████▌  | 5224/6855 [18:40<05:42,  4.77it/s]

Processing tickers:  76%|███████▌  | 5225/6855 [18:40<05:44,  4.74it/s]

Processing tickers:  76%|███████▌  | 5226/6855 [18:41<05:43,  4.74it/s]

Processing tickers:  76%|███████▋  | 5227/6855 [18:41<05:40,  4.78it/s]

Processing tickers:  76%|███████▋  | 5228/6855 [18:41<05:39,  4.80it/s]

Processing tickers:  76%|███████▋  | 5229/6855 [18:41<05:36,  4.83it/s]

Processing tickers:  76%|███████▋  | 5230/6855 [18:41<05:38,  4.80it/s]

Processing tickers:  76%|███████▋  | 5231/6855 [18:42<05:42,  4.75it/s]

Processing tickers:  76%|███████▋  | 5232/6855 [18:42<05:42,  4.74it/s]

Processing tickers:  76%|███████▋  | 5233/6855 [18:42<05:42,  4.74it/s]

Processing tickers:  76%|███████▋  | 5234/6855 [18:42<05:43,  4.72it/s]

Processing tickers:  76%|███████▋  | 5235/6855 [18:42<05:46,  4.68it/s]

Processing tickers:  76%|███████▋  | 5236/6855 [18:43<05:43,  4.71it/s]

Processing tickers:  76%|███████▋  | 5237/6855 [18:43<05:40,  4.75it/s]

Processing tickers:  76%|███████▋  | 5238/6855 [18:43<05:42,  4.72it/s]

Processing tickers:  76%|███████▋  | 5239/6855 [18:43<05:39,  4.77it/s]

Processing tickers:  76%|███████▋  | 5240/6855 [18:43<05:39,  4.76it/s]

Processing tickers:  76%|███████▋  | 5241/6855 [18:44<05:37,  4.78it/s]

Processing tickers:  76%|███████▋  | 5242/6855 [18:44<05:37,  4.77it/s]

Processing tickers:  76%|███████▋  | 5243/6855 [18:44<05:40,  4.74it/s]

Processing tickers:  76%|███████▋  | 5244/6855 [18:44<05:36,  4.79it/s]

Processing tickers:  77%|███████▋  | 5245/6855 [18:45<05:37,  4.78it/s]

Processing tickers:  77%|███████▋  | 5246/6855 [18:45<05:49,  4.60it/s]

Processing tickers:  77%|███████▋  | 5247/6855 [18:45<05:46,  4.64it/s]

Processing tickers:  77%|███████▋  | 5248/6855 [18:45<05:47,  4.62it/s]

Processing tickers:  77%|███████▋  | 5249/6855 [18:45<05:44,  4.66it/s]

Processing tickers:  77%|███████▋  | 5250/6855 [18:46<05:44,  4.66it/s]

Processing tickers:  77%|███████▋  | 5251/6855 [18:46<05:39,  4.73it/s]

Processing tickers:  77%|███████▋  | 5252/6855 [18:46<05:37,  4.76it/s]

Processing tickers:  77%|███████▋  | 5253/6855 [18:46<05:38,  4.74it/s]

Processing tickers:  77%|███████▋  | 5254/6855 [18:46<05:37,  4.74it/s]

Processing tickers:  77%|███████▋  | 5255/6855 [18:47<05:39,  4.72it/s]

Processing tickers:  77%|███████▋  | 5256/6855 [18:47<05:41,  4.68it/s]

Processing tickers:  77%|███████▋  | 5257/6855 [18:47<05:40,  4.69it/s]

Processing tickers:  77%|███████▋  | 5258/6855 [18:47<05:45,  4.62it/s]

Processing tickers:  77%|███████▋  | 5259/6855 [18:48<05:42,  4.66it/s]

Processing tickers:  77%|███████▋  | 5260/6855 [18:48<05:38,  4.71it/s]

Processing tickers:  77%|███████▋  | 5261/6855 [18:48<05:40,  4.68it/s]

Processing tickers:  77%|███████▋  | 5262/6855 [18:48<05:39,  4.69it/s]

Processing tickers:  77%|███████▋  | 5263/6855 [18:48<05:39,  4.70it/s]

Processing tickers:  77%|███████▋  | 5264/6855 [18:49<05:33,  4.76it/s]

Processing tickers:  77%|███████▋  | 5265/6855 [18:49<05:34,  4.76it/s]

Processing tickers:  77%|███████▋  | 5266/6855 [18:49<05:34,  4.75it/s]

Processing tickers:  77%|███████▋  | 5267/6855 [18:49<05:36,  4.72it/s]

Processing tickers:  77%|███████▋  | 5268/6855 [18:49<05:35,  4.73it/s]

Processing tickers:  77%|███████▋  | 5269/6855 [18:50<05:33,  4.75it/s]

Processing tickers:  77%|███████▋  | 5270/6855 [18:50<05:30,  4.79it/s]

Processing tickers:  77%|███████▋  | 5271/6855 [18:50<05:31,  4.77it/s]

Processing tickers:  77%|███████▋  | 5272/6855 [18:50<05:33,  4.75it/s]

Processing tickers:  77%|███████▋  | 5273/6855 [18:50<05:33,  4.74it/s]

Processing tickers:  77%|███████▋  | 5274/6855 [18:51<05:30,  4.78it/s]

Processing tickers:  77%|███████▋  | 5275/6855 [18:51<05:32,  4.76it/s]

Processing tickers:  77%|███████▋  | 5276/6855 [18:51<05:30,  4.77it/s]

Processing tickers:  77%|███████▋  | 5277/6855 [18:51<05:29,  4.78it/s]

Processing tickers:  77%|███████▋  | 5278/6855 [18:52<05:28,  4.80it/s]

Processing tickers:  77%|███████▋  | 5279/6855 [18:52<05:26,  4.82it/s]

Processing tickers:  77%|███████▋  | 5280/6855 [18:52<05:30,  4.77it/s]

Processing tickers:  77%|███████▋  | 5281/6855 [18:52<05:41,  4.60it/s]

Processing tickers:  77%|███████▋  | 5282/6855 [18:52<05:40,  4.61it/s]

Processing tickers:  77%|███████▋  | 5283/6855 [18:53<05:40,  4.61it/s]

Processing tickers:  77%|███████▋  | 5284/6855 [18:53<05:39,  4.63it/s]

Processing tickers:  77%|███████▋  | 5285/6855 [18:53<05:36,  4.66it/s]

Processing tickers:  77%|███████▋  | 5286/6855 [18:53<05:37,  4.65it/s]

Processing tickers:  77%|███████▋  | 5287/6855 [18:53<05:37,  4.65it/s]

Processing tickers:  77%|███████▋  | 5288/6855 [18:54<05:35,  4.68it/s]

Processing tickers:  77%|███████▋  | 5289/6855 [18:54<05:33,  4.70it/s]

Processing tickers:  77%|███████▋  | 5290/6855 [18:54<05:31,  4.72it/s]

Processing tickers:  77%|███████▋  | 5291/6855 [18:54<05:34,  4.68it/s]

Processing tickers:  77%|███████▋  | 5292/6855 [18:55<05:31,  4.71it/s]

Processing tickers:  77%|███████▋  | 5293/6855 [18:55<05:29,  4.74it/s]

Processing tickers:  77%|███████▋  | 5294/6855 [18:55<05:39,  4.60it/s]

Processing tickers:  77%|███████▋  | 5295/6855 [18:55<05:46,  4.50it/s]

Processing tickers:  77%|███████▋  | 5296/6855 [18:55<05:41,  4.57it/s]

Processing tickers:  77%|███████▋  | 5297/6855 [18:56<05:38,  4.61it/s]

Processing tickers:  77%|███████▋  | 5298/6855 [18:56<05:33,  4.66it/s]

Processing tickers:  77%|███████▋  | 5299/6855 [18:56<05:31,  4.70it/s]

Processing tickers:  77%|███████▋  | 5300/6855 [18:56<05:31,  4.69it/s]

Processing tickers:  77%|███████▋  | 5301/6855 [18:56<05:33,  4.66it/s]

Processing tickers:  77%|███████▋  | 5302/6855 [18:57<05:32,  4.68it/s]

Processing tickers:  77%|███████▋  | 5303/6855 [18:57<05:29,  4.71it/s]

Processing tickers:  77%|███████▋  | 5304/6855 [18:57<05:30,  4.70it/s]

Processing tickers:  77%|███████▋  | 5305/6855 [18:57<05:30,  4.68it/s]

Processing tickers:  77%|███████▋  | 5306/6855 [18:58<05:28,  4.71it/s]

Processing tickers:  77%|███████▋  | 5307/6855 [18:58<05:24,  4.76it/s]

Processing tickers:  77%|███████▋  | 5308/6855 [18:58<05:26,  4.73it/s]

Processing tickers:  77%|███████▋  | 5309/6855 [18:58<05:42,  4.52it/s]

Processing tickers:  77%|███████▋  | 5310/6855 [18:58<05:56,  4.33it/s]

Processing tickers:  77%|███████▋  | 5311/6855 [18:59<06:03,  4.24it/s]

Processing tickers:  77%|███████▋  | 5312/6855 [18:59<05:57,  4.32it/s]

Processing tickers:  78%|███████▊  | 5313/6855 [18:59<05:52,  4.37it/s]

Processing tickers:  78%|███████▊  | 5314/6855 [18:59<05:47,  4.43it/s]

Processing tickers:  78%|███████▊  | 5315/6855 [19:00<05:53,  4.36it/s]

Processing tickers:  78%|███████▊  | 5316/6855 [19:00<05:46,  4.44it/s]

Processing tickers:  78%|███████▊  | 5317/6855 [19:00<05:49,  4.40it/s]

Processing tickers:  78%|███████▊  | 5318/6855 [19:00<05:55,  4.33it/s]

Processing tickers:  78%|███████▊  | 5319/6855 [19:01<06:00,  4.26it/s]

Processing tickers:  78%|███████▊  | 5320/6855 [19:01<05:55,  4.31it/s]

Processing tickers:  78%|███████▊  | 5321/6855 [19:01<05:52,  4.36it/s]

Processing tickers:  78%|███████▊  | 5322/6855 [19:01<05:44,  4.45it/s]

Processing tickers:  78%|███████▊  | 5323/6855 [19:01<05:40,  4.51it/s]

Processing tickers:  78%|███████▊  | 5324/6855 [19:02<05:35,  4.57it/s]

Processing tickers:  78%|███████▊  | 5325/6855 [19:02<05:31,  4.61it/s]

Processing tickers:  78%|███████▊  | 5326/6855 [19:02<05:31,  4.61it/s]

Processing tickers:  78%|███████▊  | 5327/6855 [19:02<05:44,  4.44it/s]

Processing tickers:  78%|███████▊  | 5328/6855 [19:03<05:51,  4.34it/s]

Processing tickers:  78%|███████▊  | 5329/6855 [19:03<05:48,  4.38it/s]

Processing tickers:  78%|███████▊  | 5330/6855 [19:03<05:47,  4.39it/s]

Processing tickers:  78%|███████▊  | 5331/6855 [19:03<05:54,  4.30it/s]

Processing tickers:  78%|███████▊  | 5332/6855 [19:03<05:46,  4.40it/s]

Processing tickers:  78%|███████▊  | 5333/6855 [19:04<05:46,  4.39it/s]

Processing tickers:  78%|███████▊  | 5334/6855 [19:04<05:40,  4.46it/s]

Processing tickers:  78%|███████▊  | 5335/6855 [19:04<05:36,  4.51it/s]

Processing tickers:  78%|███████▊  | 5336/6855 [19:04<05:34,  4.54it/s]

Processing tickers:  78%|███████▊  | 5337/6855 [19:05<05:40,  4.46it/s]

Processing tickers:  78%|███████▊  | 5338/6855 [19:05<05:31,  4.58it/s]

Processing tickers:  78%|███████▊  | 5339/6855 [19:05<05:25,  4.66it/s]

Processing tickers:  78%|███████▊  | 5340/6855 [19:05<05:27,  4.63it/s]

Processing tickers:  78%|███████▊  | 5341/6855 [19:05<05:23,  4.67it/s]

Processing tickers:  78%|███████▊  | 5342/6855 [19:06<05:29,  4.59it/s]

Processing tickers:  78%|███████▊  | 5343/6855 [19:06<05:27,  4.61it/s]

Processing tickers:  78%|███████▊  | 5344/6855 [19:06<05:27,  4.62it/s]

Processing tickers:  78%|███████▊  | 5345/6855 [19:06<05:30,  4.57it/s]

Processing tickers:  78%|███████▊  | 5346/6855 [19:06<05:34,  4.52it/s]

Processing tickers:  78%|███████▊  | 5347/6855 [19:07<05:40,  4.43it/s]

Processing tickers:  78%|███████▊  | 5348/6855 [19:07<05:41,  4.42it/s]

Processing tickers:  78%|███████▊  | 5349/6855 [19:07<05:39,  4.43it/s]

Processing tickers:  78%|███████▊  | 5350/6855 [19:07<05:38,  4.44it/s]

Processing tickers:  78%|███████▊  | 5351/6855 [19:08<05:38,  4.45it/s]

Processing tickers:  78%|███████▊  | 5352/6855 [19:08<05:29,  4.56it/s]

Processing tickers:  78%|███████▊  | 5353/6855 [19:08<05:22,  4.66it/s]

Processing tickers:  78%|███████▊  | 5354/6855 [19:08<05:20,  4.68it/s]

Processing tickers:  78%|███████▊  | 5355/6855 [19:08<05:21,  4.67it/s]

Processing tickers:  78%|███████▊  | 5356/6855 [19:09<05:17,  4.73it/s]

Processing tickers:  78%|███████▊  | 5357/6855 [19:09<05:13,  4.78it/s]

Processing tickers:  78%|███████▊  | 5358/6855 [19:09<05:13,  4.77it/s]

Processing tickers:  78%|███████▊  | 5359/6855 [19:09<05:12,  4.79it/s]

Processing tickers:  78%|███████▊  | 5360/6855 [19:10<05:12,  4.79it/s]

Processing tickers:  78%|███████▊  | 5361/6855 [19:10<05:13,  4.77it/s]

Processing tickers:  78%|███████▊  | 5362/6855 [19:10<05:12,  4.77it/s]

Processing tickers:  78%|███████▊  | 5363/6855 [19:10<05:11,  4.79it/s]

Processing tickers:  78%|███████▊  | 5364/6855 [19:10<05:09,  4.81it/s]

Processing tickers:  78%|███████▊  | 5365/6855 [19:11<05:10,  4.80it/s]

Processing tickers:  78%|███████▊  | 5366/6855 [19:11<05:11,  4.78it/s]

Processing tickers:  78%|███████▊  | 5367/6855 [19:11<05:09,  4.80it/s]

Processing tickers:  78%|███████▊  | 5368/6855 [19:11<05:15,  4.71it/s]

Processing tickers:  78%|███████▊  | 5369/6855 [19:11<05:14,  4.73it/s]

Processing tickers:  78%|███████▊  | 5370/6855 [19:12<05:15,  4.71it/s]

Processing tickers:  78%|███████▊  | 5371/6855 [19:12<05:13,  4.73it/s]

Processing tickers:  78%|███████▊  | 5372/6855 [19:12<05:10,  4.78it/s]

Processing tickers:  78%|███████▊  | 5373/6855 [19:12<05:12,  4.74it/s]

Processing tickers:  78%|███████▊  | 5374/6855 [19:12<05:09,  4.78it/s]

Processing tickers:  78%|███████▊  | 5375/6855 [19:13<05:09,  4.79it/s]

Processing tickers:  78%|███████▊  | 5376/6855 [19:13<05:08,  4.79it/s]

Processing tickers:  78%|███████▊  | 5377/6855 [19:13<05:07,  4.80it/s]

Processing tickers:  78%|███████▊  | 5378/6855 [19:13<05:09,  4.77it/s]

Processing tickers:  78%|███████▊  | 5379/6855 [19:13<05:10,  4.76it/s]

Processing tickers:  78%|███████▊  | 5380/6855 [19:14<05:11,  4.73it/s]

Processing tickers:  78%|███████▊  | 5381/6855 [19:14<05:14,  4.68it/s]

Processing tickers:  79%|███████▊  | 5382/6855 [19:14<05:13,  4.71it/s]

Processing tickers:  79%|███████▊  | 5383/6855 [19:14<05:11,  4.73it/s]

Processing tickers:  79%|███████▊  | 5384/6855 [19:15<05:08,  4.77it/s]

Processing tickers:  79%|███████▊  | 5385/6855 [19:15<05:09,  4.74it/s]

Processing tickers:  79%|███████▊  | 5386/6855 [19:15<05:12,  4.70it/s]

Processing tickers:  79%|███████▊  | 5387/6855 [19:15<05:17,  4.63it/s]

Processing tickers:  79%|███████▊  | 5388/6855 [19:15<05:14,  4.66it/s]

Processing tickers:  79%|███████▊  | 5389/6855 [19:16<05:13,  4.68it/s]

Processing tickers:  79%|███████▊  | 5390/6855 [19:16<05:12,  4.70it/s]

Processing tickers:  79%|███████▊  | 5391/6855 [19:16<05:11,  4.70it/s]

Processing tickers:  79%|███████▊  | 5392/6855 [19:16<05:07,  4.76it/s]

Processing tickers:  79%|███████▊  | 5393/6855 [19:16<05:04,  4.80it/s]

Processing tickers:  79%|███████▊  | 5394/6855 [19:17<05:07,  4.75it/s]

Processing tickers:  79%|███████▊  | 5395/6855 [19:17<05:05,  4.78it/s]

Processing tickers:  79%|███████▊  | 5396/6855 [19:17<05:05,  4.78it/s]

Processing tickers:  79%|███████▊  | 5397/6855 [19:17<05:03,  4.80it/s]

Processing tickers:  79%|███████▊  | 5398/6855 [19:18<05:04,  4.78it/s]

Processing tickers:  79%|███████▉  | 5399/6855 [19:18<05:04,  4.78it/s]

Processing tickers:  79%|███████▉  | 5400/6855 [19:18<05:07,  4.72it/s]

Processing tickers:  79%|███████▉  | 5401/6855 [19:18<05:07,  4.74it/s]

Processing tickers:  79%|███████▉  | 5402/6855 [19:18<05:04,  4.77it/s]

Processing tickers:  79%|███████▉  | 5403/6855 [19:19<05:06,  4.74it/s]

Processing tickers:  79%|███████▉  | 5404/6855 [19:19<05:06,  4.74it/s]

Processing tickers:  79%|███████▉  | 5405/6855 [19:19<05:07,  4.72it/s]

Processing tickers:  79%|███████▉  | 5406/6855 [19:19<05:12,  4.64it/s]

Processing tickers:  79%|███████▉  | 5407/6855 [19:19<05:09,  4.68it/s]

Processing tickers:  79%|███████▉  | 5408/6855 [19:20<05:06,  4.71it/s]

Processing tickers:  79%|███████▉  | 5409/6855 [19:20<05:06,  4.72it/s]

Processing tickers:  79%|███████▉  | 5410/6855 [19:20<05:05,  4.73it/s]

Processing tickers:  79%|███████▉  | 5411/6855 [19:20<05:03,  4.75it/s]

Processing tickers:  79%|███████▉  | 5412/6855 [19:20<05:02,  4.78it/s]

Processing tickers:  79%|███████▉  | 5413/6855 [19:21<05:13,  4.60it/s]

Processing tickers:  79%|███████▉  | 5414/6855 [19:21<05:08,  4.67it/s]

Processing tickers:  79%|███████▉  | 5415/6855 [19:21<05:04,  4.72it/s]

Processing tickers:  79%|███████▉  | 5416/6855 [19:21<05:08,  4.67it/s]

Processing tickers:  79%|███████▉  | 5417/6855 [19:22<05:05,  4.70it/s]

Processing tickers:  79%|███████▉  | 5418/6855 [19:22<05:02,  4.75it/s]

Processing tickers:  79%|███████▉  | 5419/6855 [19:22<05:01,  4.76it/s]

Processing tickers:  79%|███████▉  | 5420/6855 [19:22<05:02,  4.74it/s]

Processing tickers:  79%|███████▉  | 5421/6855 [19:22<05:00,  4.76it/s]

Processing tickers:  79%|███████▉  | 5422/6855 [19:23<05:00,  4.78it/s]

Processing tickers:  79%|███████▉  | 5423/6855 [19:23<05:01,  4.75it/s]

Processing tickers:  79%|███████▉  | 5424/6855 [19:23<04:59,  4.78it/s]

Processing tickers:  79%|███████▉  | 5425/6855 [19:23<05:02,  4.73it/s]

Processing tickers:  79%|███████▉  | 5426/6855 [19:23<05:01,  4.74it/s]

Processing tickers:  79%|███████▉  | 5427/6855 [19:24<05:01,  4.74it/s]

Processing tickers:  79%|███████▉  | 5428/6855 [19:24<05:13,  4.55it/s]

Processing tickers:  79%|███████▉  | 5429/6855 [19:24<05:10,  4.59it/s]

Processing tickers:  79%|███████▉  | 5430/6855 [19:24<05:07,  4.64it/s]

Processing tickers:  79%|███████▉  | 5431/6855 [19:25<05:07,  4.63it/s]

Processing tickers:  79%|███████▉  | 5432/6855 [19:25<05:05,  4.66it/s]

Processing tickers:  79%|███████▉  | 5433/6855 [19:25<05:03,  4.69it/s]

Processing tickers:  79%|███████▉  | 5434/6855 [19:25<05:02,  4.70it/s]

Processing tickers:  79%|███████▉  | 5435/6855 [19:25<05:02,  4.70it/s]

Processing tickers:  79%|███████▉  | 5436/6855 [19:26<04:59,  4.75it/s]

Processing tickers:  79%|███████▉  | 5437/6855 [19:26<04:59,  4.73it/s]

Processing tickers:  79%|███████▉  | 5438/6855 [19:26<04:58,  4.74it/s]

Processing tickers:  79%|███████▉  | 5439/6855 [19:26<05:05,  4.63it/s]

Processing tickers:  79%|███████▉  | 5440/6855 [19:26<05:04,  4.65it/s]

Processing tickers:  79%|███████▉  | 5441/6855 [19:27<05:02,  4.67it/s]

Processing tickers:  79%|███████▉  | 5442/6855 [19:27<05:04,  4.64it/s]

Processing tickers:  79%|███████▉  | 5443/6855 [19:27<05:03,  4.65it/s]

Processing tickers:  79%|███████▉  | 5444/6855 [19:27<05:03,  4.66it/s]

Processing tickers:  79%|███████▉  | 5445/6855 [19:28<05:01,  4.68it/s]

Processing tickers:  79%|███████▉  | 5446/6855 [19:28<04:57,  4.74it/s]

Processing tickers:  79%|███████▉  | 5447/6855 [19:28<04:57,  4.73it/s]

Processing tickers:  79%|███████▉  | 5448/6855 [19:28<04:58,  4.72it/s]

Processing tickers:  79%|███████▉  | 5449/6855 [19:28<05:03,  4.63it/s]

Processing tickers:  80%|███████▉  | 5450/6855 [19:29<05:10,  4.53it/s]

Processing tickers:  80%|███████▉  | 5451/6855 [19:29<05:05,  4.60it/s]

Processing tickers:  80%|███████▉  | 5452/6855 [19:29<05:01,  4.65it/s]

Processing tickers:  80%|███████▉  | 5453/6855 [19:29<05:00,  4.66it/s]

Processing tickers:  80%|███████▉  | 5454/6855 [19:29<04:57,  4.72it/s]

Processing tickers:  80%|███████▉  | 5455/6855 [19:30<04:58,  4.69it/s]

Processing tickers:  80%|███████▉  | 5456/6855 [19:30<04:57,  4.70it/s]

Processing tickers:  80%|███████▉  | 5457/6855 [19:30<05:01,  4.63it/s]

Processing tickers:  80%|███████▉  | 5458/6855 [19:30<04:58,  4.68it/s]

Processing tickers:  80%|███████▉  | 5459/6855 [19:31<04:55,  4.73it/s]

Processing tickers:  80%|███████▉  | 5460/6855 [19:31<04:57,  4.68it/s]

Processing tickers:  80%|███████▉  | 5461/6855 [19:31<04:53,  4.75it/s]

Processing tickers:  80%|███████▉  | 5462/6855 [19:31<05:02,  4.60it/s]

Processing tickers:  80%|███████▉  | 5463/6855 [19:31<05:07,  4.53it/s]

Processing tickers:  80%|███████▉  | 5464/6855 [19:32<05:02,  4.60it/s]

Processing tickers:  80%|███████▉  | 5465/6855 [19:32<05:04,  4.56it/s]

Processing tickers:  80%|███████▉  | 5466/6855 [19:32<05:10,  4.47it/s]

Processing tickers:  80%|███████▉  | 5467/6855 [19:32<05:14,  4.42it/s]

Processing tickers:  80%|███████▉  | 5468/6855 [19:33<05:15,  4.40it/s]

Processing tickers:  80%|███████▉  | 5469/6855 [19:33<05:17,  4.37it/s]

Processing tickers:  80%|███████▉  | 5470/6855 [19:33<05:09,  4.48it/s]

Processing tickers:  80%|███████▉  | 5471/6855 [19:33<05:05,  4.53it/s]

Processing tickers:  80%|███████▉  | 5472/6855 [19:33<05:08,  4.48it/s]

Processing tickers:  80%|███████▉  | 5473/6855 [19:34<05:01,  4.59it/s]

Processing tickers:  80%|███████▉  | 5474/6855 [19:34<05:06,  4.51it/s]

Processing tickers:  80%|███████▉  | 5475/6855 [19:34<05:00,  4.59it/s]

Processing tickers:  80%|███████▉  | 5476/6855 [19:34<04:58,  4.63it/s]

Processing tickers:  80%|███████▉  | 5477/6855 [19:34<04:56,  4.65it/s]

Processing tickers:  80%|███████▉  | 5478/6855 [19:35<04:50,  4.74it/s]

Processing tickers:  80%|███████▉  | 5479/6855 [19:35<04:49,  4.76it/s]

Processing tickers:  80%|███████▉  | 5480/6855 [19:35<04:46,  4.79it/s]

Processing tickers:  80%|███████▉  | 5481/6855 [19:35<04:47,  4.79it/s]

Processing tickers:  80%|███████▉  | 5482/6855 [19:36<04:46,  4.79it/s]

Processing tickers:  80%|███████▉  | 5483/6855 [19:36<04:47,  4.78it/s]

Processing tickers:  80%|████████  | 5484/6855 [19:36<04:46,  4.78it/s]

Processing tickers:  80%|████████  | 5485/6855 [19:36<04:50,  4.71it/s]

Processing tickers:  80%|████████  | 5486/6855 [19:36<04:59,  4.57it/s]

Processing tickers:  80%|████████  | 5487/6855 [19:37<04:54,  4.65it/s]

Processing tickers:  80%|████████  | 5488/6855 [19:37<04:51,  4.69it/s]

Processing tickers:  80%|████████  | 5489/6855 [19:37<04:48,  4.74it/s]

Processing tickers:  80%|████████  | 5490/6855 [19:37<04:51,  4.68it/s]

Processing tickers:  80%|████████  | 5491/6855 [19:37<04:49,  4.71it/s]

Processing tickers:  80%|████████  | 5492/6855 [19:38<04:48,  4.72it/s]

Processing tickers:  80%|████████  | 5493/6855 [19:38<04:46,  4.76it/s]

Processing tickers:  80%|████████  | 5494/6855 [19:38<04:45,  4.77it/s]

Processing tickers:  80%|████████  | 5495/6855 [19:38<04:44,  4.77it/s]

Processing tickers:  80%|████████  | 5496/6855 [19:38<04:44,  4.78it/s]

Processing tickers:  80%|████████  | 5497/6855 [19:39<04:54,  4.61it/s]

Processing tickers:  80%|████████  | 5498/6855 [19:39<04:51,  4.65it/s]

Processing tickers:  80%|████████  | 5499/6855 [19:39<04:48,  4.70it/s]

Processing tickers:  80%|████████  | 5500/6855 [19:39<04:57,  4.55it/s]

Processing tickers:  80%|████████  | 5501/6855 [19:40<04:51,  4.65it/s]

Processing tickers:  80%|████████  | 5502/6855 [19:40<04:51,  4.65it/s]

Processing tickers:  80%|████████  | 5503/6855 [19:40<04:50,  4.66it/s]

Processing tickers:  80%|████████  | 5504/6855 [19:40<04:54,  4.58it/s]

Processing tickers:  80%|████████  | 5505/6855 [19:40<04:49,  4.66it/s]

Processing tickers:  80%|████████  | 5506/6855 [19:41<04:48,  4.67it/s]

Processing tickers:  80%|████████  | 5507/6855 [19:41<04:44,  4.73it/s]

Processing tickers:  80%|████████  | 5508/6855 [19:41<04:45,  4.72it/s]

Processing tickers:  80%|████████  | 5509/6855 [19:41<04:47,  4.69it/s]

Processing tickers:  80%|████████  | 5510/6855 [19:41<04:43,  4.74it/s]

Processing tickers:  80%|████████  | 5511/6855 [19:42<04:52,  4.59it/s]

Processing tickers:  80%|████████  | 5512/6855 [19:42<04:47,  4.67it/s]

Processing tickers:  80%|████████  | 5513/6855 [19:42<04:46,  4.68it/s]

Processing tickers:  80%|████████  | 5514/6855 [19:42<04:53,  4.57it/s]

Processing tickers:  80%|████████  | 5515/6855 [19:43<04:49,  4.63it/s]

Processing tickers:  80%|████████  | 5516/6855 [19:43<04:48,  4.64it/s]

Processing tickers:  80%|████████  | 5517/6855 [19:43<04:52,  4.58it/s]

Processing tickers:  80%|████████  | 5518/6855 [19:43<04:50,  4.61it/s]

Processing tickers:  81%|████████  | 5519/6855 [19:43<04:46,  4.66it/s]

Processing tickers:  81%|████████  | 5520/6855 [19:44<04:55,  4.52it/s]

Processing tickers:  81%|████████  | 5521/6855 [19:44<04:53,  4.54it/s]

Processing tickers:  81%|████████  | 5522/6855 [19:44<04:50,  4.58it/s]

Processing tickers:  81%|████████  | 5523/6855 [19:44<04:46,  4.64it/s]

Processing tickers:  81%|████████  | 5524/6855 [19:45<04:45,  4.67it/s]

Processing tickers:  81%|████████  | 5525/6855 [19:45<04:44,  4.67it/s]

Processing tickers:  81%|████████  | 5526/6855 [19:45<04:41,  4.71it/s]

Processing tickers:  81%|████████  | 5527/6855 [19:45<04:38,  4.76it/s]

Processing tickers:  81%|████████  | 5528/6855 [19:45<04:44,  4.66it/s]

Processing tickers:  81%|████████  | 5529/6855 [19:46<04:43,  4.67it/s]

Processing tickers:  81%|████████  | 5530/6855 [19:46<04:45,  4.64it/s]

Processing tickers:  81%|████████  | 5531/6855 [19:46<04:44,  4.65it/s]

Processing tickers:  81%|████████  | 5532/6855 [19:46<04:43,  4.67it/s]

Processing tickers:  81%|████████  | 5533/6855 [19:46<04:51,  4.53it/s]

Processing tickers:  81%|████████  | 5534/6855 [19:47<04:56,  4.45it/s]

Processing tickers:  81%|████████  | 5535/6855 [19:47<04:55,  4.46it/s]

Processing tickers:  81%|████████  | 5536/6855 [19:47<04:47,  4.58it/s]

Processing tickers:  81%|████████  | 5537/6855 [19:47<04:48,  4.57it/s]

Processing tickers:  81%|████████  | 5538/6855 [19:48<04:43,  4.64it/s]

Processing tickers:  81%|████████  | 5539/6855 [19:48<04:43,  4.65it/s]

Processing tickers:  81%|████████  | 5540/6855 [19:48<04:39,  4.70it/s]

Processing tickers:  81%|████████  | 5541/6855 [19:48<04:39,  4.70it/s]

Processing tickers:  81%|████████  | 5542/6855 [19:48<04:38,  4.71it/s]

Processing tickers:  81%|████████  | 5543/6855 [19:49<04:39,  4.69it/s]

Processing tickers:  81%|████████  | 5544/6855 [19:49<04:46,  4.58it/s]

Processing tickers:  81%|████████  | 5545/6855 [19:49<04:41,  4.65it/s]

Processing tickers:  81%|████████  | 5546/6855 [19:49<04:40,  4.67it/s]

Processing tickers:  81%|████████  | 5547/6855 [19:49<04:38,  4.70it/s]

Processing tickers:  81%|████████  | 5548/6855 [19:50<04:36,  4.72it/s]

Processing tickers:  81%|████████  | 5549/6855 [19:50<04:36,  4.72it/s]

Processing tickers:  81%|████████  | 5550/6855 [19:50<04:38,  4.68it/s]

Processing tickers:  81%|████████  | 5551/6855 [19:50<04:46,  4.55it/s]

Processing tickers:  81%|████████  | 5552/6855 [19:51<04:41,  4.63it/s]

Processing tickers:  81%|████████  | 5553/6855 [19:51<04:37,  4.69it/s]

Processing tickers:  81%|████████  | 5554/6855 [19:51<04:37,  4.68it/s]

Processing tickers:  81%|████████  | 5555/6855 [19:51<04:37,  4.68it/s]

Processing tickers:  81%|████████  | 5556/6855 [19:51<04:42,  4.60it/s]

Processing tickers:  81%|████████  | 5557/6855 [19:52<04:38,  4.65it/s]

Processing tickers:  81%|████████  | 5558/6855 [19:52<04:35,  4.71it/s]

Processing tickers:  81%|████████  | 5559/6855 [19:52<04:33,  4.74it/s]

Processing tickers:  81%|████████  | 5560/6855 [19:52<04:31,  4.78it/s]

Processing tickers:  81%|████████  | 5561/6855 [19:52<04:35,  4.70it/s]

Processing tickers:  81%|████████  | 5562/6855 [19:53<04:34,  4.71it/s]

Processing tickers:  81%|████████  | 5563/6855 [19:53<04:33,  4.73it/s]

Processing tickers:  81%|████████  | 5564/6855 [19:53<04:31,  4.76it/s]

Processing tickers:  81%|████████  | 5565/6855 [19:53<04:33,  4.71it/s]

Processing tickers:  81%|████████  | 5566/6855 [19:54<04:33,  4.71it/s]

Processing tickers:  81%|████████  | 5567/6855 [19:54<04:33,  4.71it/s]

Processing tickers:  81%|████████  | 5568/6855 [19:54<04:32,  4.73it/s]

Processing tickers:  81%|████████  | 5569/6855 [19:54<04:30,  4.76it/s]

Processing tickers:  81%|████████▏ | 5570/6855 [19:54<04:32,  4.72it/s]

Processing tickers:  81%|████████▏ | 5571/6855 [19:55<04:31,  4.74it/s]

Processing tickers:  81%|████████▏ | 5572/6855 [19:55<04:36,  4.65it/s]

Processing tickers:  81%|████████▏ | 5573/6855 [19:55<04:39,  4.59it/s]

Processing tickers:  81%|████████▏ | 5574/6855 [19:55<04:43,  4.51it/s]

Processing tickers:  81%|████████▏ | 5575/6855 [19:55<04:38,  4.60it/s]

Processing tickers:  81%|████████▏ | 5576/6855 [19:56<04:43,  4.50it/s]

Processing tickers:  81%|████████▏ | 5577/6855 [19:56<04:37,  4.61it/s]

Processing tickers:  81%|████████▏ | 5578/6855 [19:56<04:34,  4.65it/s]

Processing tickers:  81%|████████▏ | 5579/6855 [19:56<04:32,  4.68it/s]

Processing tickers:  81%|████████▏ | 5580/6855 [19:57<04:28,  4.74it/s]

Processing tickers:  81%|████████▏ | 5581/6855 [19:57<04:26,  4.78it/s]

Processing tickers:  81%|████████▏ | 5582/6855 [19:57<04:31,  4.69it/s]

Processing tickers:  81%|████████▏ | 5583/6855 [19:57<04:28,  4.74it/s]

Processing tickers:  81%|████████▏ | 5584/6855 [19:57<04:38,  4.56it/s]

Processing tickers:  81%|████████▏ | 5585/6855 [19:58<04:35,  4.61it/s]

Processing tickers:  81%|████████▏ | 5586/6855 [19:58<04:34,  4.63it/s]

Processing tickers:  82%|████████▏ | 5587/6855 [19:58<04:42,  4.49it/s]

Processing tickers:  82%|████████▏ | 5588/6855 [19:58<04:40,  4.52it/s]

Processing tickers:  82%|████████▏ | 5589/6855 [19:59<04:41,  4.49it/s]

Processing tickers:  82%|████████▏ | 5590/6855 [19:59<04:40,  4.51it/s]

Processing tickers:  82%|████████▏ | 5591/6855 [19:59<04:36,  4.57it/s]

Processing tickers:  82%|████████▏ | 5592/6855 [19:59<04:32,  4.63it/s]

Processing tickers:  82%|████████▏ | 5593/6855 [19:59<04:34,  4.60it/s]

Processing tickers:  82%|████████▏ | 5594/6855 [20:00<04:32,  4.62it/s]

Processing tickers:  82%|████████▏ | 5595/6855 [20:00<04:32,  4.63it/s]

Processing tickers:  82%|████████▏ | 5596/6855 [20:00<04:39,  4.50it/s]

Processing tickers:  82%|████████▏ | 5597/6855 [20:00<04:35,  4.57it/s]

Processing tickers:  82%|████████▏ | 5598/6855 [20:00<04:43,  4.44it/s]

Processing tickers:  82%|████████▏ | 5599/6855 [20:01<04:37,  4.52it/s]

Processing tickers:  82%|████████▏ | 5600/6855 [20:01<04:45,  4.40it/s]

Processing tickers:  82%|████████▏ | 5601/6855 [20:01<04:39,  4.49it/s]

Processing tickers:  82%|████████▏ | 5602/6855 [20:01<04:34,  4.57it/s]

Processing tickers:  82%|████████▏ | 5603/6855 [20:02<04:31,  4.62it/s]

Processing tickers:  82%|████████▏ | 5604/6855 [20:02<04:34,  4.56it/s]

Processing tickers:  82%|████████▏ | 5605/6855 [20:02<04:31,  4.60it/s]

Processing tickers:  82%|████████▏ | 5606/6855 [20:02<04:28,  4.65it/s]

Processing tickers:  82%|████████▏ | 5607/6855 [20:02<04:25,  4.69it/s]

Processing tickers:  82%|████████▏ | 5608/6855 [20:03<04:22,  4.75it/s]

Processing tickers:  82%|████████▏ | 5609/6855 [20:03<04:22,  4.74it/s]

Processing tickers:  82%|████████▏ | 5610/6855 [20:03<04:20,  4.79it/s]

Processing tickers:  82%|████████▏ | 5611/6855 [20:03<04:18,  4.82it/s]

Processing tickers:  82%|████████▏ | 5612/6855 [20:03<04:17,  4.82it/s]

Processing tickers:  82%|████████▏ | 5613/6855 [20:04<04:23,  4.71it/s]

Processing tickers:  82%|████████▏ | 5614/6855 [20:04<04:23,  4.72it/s]

Processing tickers:  82%|████████▏ | 5615/6855 [20:04<04:19,  4.77it/s]

Processing tickers:  82%|████████▏ | 5616/6855 [20:04<04:22,  4.72it/s]

Processing tickers:  82%|████████▏ | 5617/6855 [20:05<04:20,  4.76it/s]

Processing tickers:  82%|████████▏ | 5618/6855 [20:05<04:31,  4.56it/s]

Processing tickers:  82%|████████▏ | 5619/6855 [20:05<04:36,  4.48it/s]

Processing tickers:  82%|████████▏ | 5620/6855 [20:05<04:33,  4.51it/s]

Processing tickers:  82%|████████▏ | 5621/6855 [20:05<04:28,  4.59it/s]

Processing tickers:  82%|████████▏ | 5622/6855 [20:06<04:32,  4.52it/s]

Processing tickers:  82%|████████▏ | 5623/6855 [20:06<04:26,  4.62it/s]

Processing tickers:  82%|████████▏ | 5624/6855 [20:06<04:31,  4.53it/s]

Processing tickers:  82%|████████▏ | 5625/6855 [20:06<04:28,  4.58it/s]

Processing tickers:  82%|████████▏ | 5626/6855 [20:07<04:25,  4.63it/s]

Processing tickers:  82%|████████▏ | 5627/6855 [20:07<04:22,  4.68it/s]

Processing tickers:  82%|████████▏ | 5628/6855 [20:07<04:18,  4.75it/s]

Processing tickers:  82%|████████▏ | 5629/6855 [20:07<04:15,  4.80it/s]

Processing tickers:  82%|████████▏ | 5630/6855 [20:07<04:16,  4.77it/s]

Processing tickers:  82%|████████▏ | 5631/6855 [20:08<04:15,  4.79it/s]

Processing tickers:  82%|████████▏ | 5632/6855 [20:08<04:23,  4.63it/s]

Processing tickers:  82%|████████▏ | 5633/6855 [20:08<04:29,  4.54it/s]

Processing tickers:  82%|████████▏ | 5634/6855 [20:08<04:32,  4.47it/s]

Processing tickers:  82%|████████▏ | 5635/6855 [20:08<04:26,  4.57it/s]

Processing tickers:  82%|████████▏ | 5636/6855 [20:09<04:22,  4.65it/s]

Processing tickers:  82%|████████▏ | 5637/6855 [20:09<04:23,  4.62it/s]

Processing tickers:  82%|████████▏ | 5638/6855 [20:09<04:20,  4.67it/s]

Processing tickers:  82%|████████▏ | 5639/6855 [20:09<04:20,  4.66it/s]

Processing tickers:  82%|████████▏ | 5640/6855 [20:10<04:22,  4.62it/s]

Processing tickers:  82%|████████▏ | 5641/6855 [20:10<04:21,  4.64it/s]

Processing tickers:  82%|████████▏ | 5642/6855 [20:10<04:25,  4.57it/s]

Processing tickers:  82%|████████▏ | 5643/6855 [20:10<04:33,  4.44it/s]

Processing tickers:  82%|████████▏ | 5644/6855 [20:10<04:28,  4.51it/s]

Processing tickers:  82%|████████▏ | 5645/6855 [20:11<04:29,  4.49it/s]

Processing tickers:  82%|████████▏ | 5646/6855 [20:11<04:31,  4.46it/s]

Processing tickers:  82%|████████▏ | 5647/6855 [20:11<04:24,  4.56it/s]

Processing tickers:  82%|████████▏ | 5648/6855 [20:11<04:20,  4.64it/s]

Processing tickers:  82%|████████▏ | 5649/6855 [20:11<04:18,  4.66it/s]

Processing tickers:  82%|████████▏ | 5650/6855 [20:12<04:17,  4.68it/s]

Processing tickers:  82%|████████▏ | 5651/6855 [20:12<04:15,  4.71it/s]

Processing tickers:  82%|████████▏ | 5652/6855 [20:12<04:14,  4.72it/s]

Processing tickers:  82%|████████▏ | 5653/6855 [20:12<04:14,  4.72it/s]

Processing tickers:  82%|████████▏ | 5654/6855 [20:13<04:15,  4.69it/s]

Processing tickers:  82%|████████▏ | 5655/6855 [20:13<04:15,  4.71it/s]

Processing tickers:  83%|████████▎ | 5656/6855 [20:13<04:14,  4.71it/s]

Processing tickers:  83%|████████▎ | 5657/6855 [20:13<04:15,  4.69it/s]

Processing tickers:  83%|████████▎ | 5658/6855 [20:13<04:14,  4.70it/s]

Processing tickers:  83%|████████▎ | 5659/6855 [20:14<04:12,  4.75it/s]

Processing tickers:  83%|████████▎ | 5660/6855 [20:14<04:11,  4.75it/s]

Processing tickers:  83%|████████▎ | 5661/6855 [20:14<04:11,  4.74it/s]

Processing tickers:  83%|████████▎ | 5662/6855 [20:14<04:12,  4.73it/s]

Processing tickers:  83%|████████▎ | 5663/6855 [20:14<04:11,  4.74it/s]

Processing tickers:  83%|████████▎ | 5664/6855 [20:15<04:13,  4.70it/s]

Processing tickers:  83%|████████▎ | 5665/6855 [20:15<04:15,  4.66it/s]

Processing tickers:  83%|████████▎ | 5666/6855 [20:15<04:15,  4.65it/s]

Processing tickers:  83%|████████▎ | 5667/6855 [20:15<04:14,  4.67it/s]

Processing tickers:  83%|████████▎ | 5668/6855 [20:16<04:16,  4.64it/s]

Processing tickers:  83%|████████▎ | 5669/6855 [20:16<04:12,  4.70it/s]

Processing tickers:  83%|████████▎ | 5670/6855 [20:16<04:10,  4.73it/s]

Processing tickers:  83%|████████▎ | 5671/6855 [20:16<04:09,  4.75it/s]

Processing tickers:  83%|████████▎ | 5672/6855 [20:16<04:11,  4.70it/s]

Processing tickers:  83%|████████▎ | 5673/6855 [20:17<04:10,  4.72it/s]

Processing tickers:  83%|████████▎ | 5674/6855 [20:17<04:13,  4.66it/s]

Processing tickers:  83%|████████▎ | 5675/6855 [20:17<04:15,  4.61it/s]

Processing tickers:  83%|████████▎ | 5676/6855 [20:17<04:13,  4.64it/s]

Processing tickers:  83%|████████▎ | 5677/6855 [20:17<04:11,  4.68it/s]

Processing tickers:  83%|████████▎ | 5678/6855 [20:18<04:10,  4.70it/s]

Processing tickers:  83%|████████▎ | 5679/6855 [20:18<04:09,  4.71it/s]

Processing tickers:  83%|████████▎ | 5680/6855 [20:18<04:07,  4.74it/s]

Processing tickers:  83%|████████▎ | 5681/6855 [20:18<04:06,  4.77it/s]

Processing tickers:  83%|████████▎ | 5682/6855 [20:18<04:06,  4.77it/s]

Processing tickers:  83%|████████▎ | 5683/6855 [20:19<04:06,  4.75it/s]

Processing tickers:  83%|████████▎ | 5684/6855 [20:19<04:05,  4.76it/s]

Processing tickers:  83%|████████▎ | 5685/6855 [20:19<04:05,  4.77it/s]

Processing tickers:  83%|████████▎ | 5686/6855 [20:19<04:04,  4.78it/s]

Processing tickers:  83%|████████▎ | 5687/6855 [20:20<04:07,  4.71it/s]

Processing tickers:  83%|████████▎ | 5688/6855 [20:20<04:08,  4.70it/s]

Processing tickers:  83%|████████▎ | 5689/6855 [20:20<04:10,  4.65it/s]

Processing tickers:  83%|████████▎ | 5690/6855 [20:20<04:11,  4.62it/s]

Processing tickers:  83%|████████▎ | 5691/6855 [20:20<04:18,  4.51it/s]

Processing tickers:  83%|████████▎ | 5692/6855 [20:21<04:19,  4.48it/s]

Processing tickers:  83%|████████▎ | 5693/6855 [20:21<04:15,  4.54it/s]

Processing tickers:  83%|████████▎ | 5694/6855 [20:21<04:09,  4.65it/s]

Processing tickers:  83%|████████▎ | 5695/6855 [20:21<04:07,  4.68it/s]

Processing tickers:  83%|████████▎ | 5696/6855 [20:22<04:08,  4.67it/s]

Processing tickers:  83%|████████▎ | 5697/6855 [20:22<04:07,  4.68it/s]

Processing tickers:  83%|████████▎ | 5698/6855 [20:22<04:10,  4.62it/s]

Processing tickers:  83%|████████▎ | 5699/6855 [20:22<04:06,  4.69it/s]

Processing tickers:  83%|████████▎ | 5700/6855 [20:22<04:05,  4.71it/s]

Processing tickers:  83%|████████▎ | 5701/6855 [20:23<04:05,  4.71it/s]

Processing tickers:  83%|████████▎ | 5702/6855 [20:23<04:05,  4.69it/s]

Processing tickers:  83%|████████▎ | 5703/6855 [20:23<04:01,  4.76it/s]

Processing tickers:  83%|████████▎ | 5704/6855 [20:23<04:09,  4.62it/s]

Processing tickers:  83%|████████▎ | 5705/6855 [20:23<04:07,  4.64it/s]

Processing tickers:  83%|████████▎ | 5706/6855 [20:24<04:03,  4.72it/s]

Processing tickers:  83%|████████▎ | 5707/6855 [20:24<04:03,  4.71it/s]

Processing tickers:  83%|████████▎ | 5708/6855 [20:24<04:04,  4.68it/s]

Processing tickers:  83%|████████▎ | 5709/6855 [20:24<04:02,  4.73it/s]

Processing tickers:  83%|████████▎ | 5710/6855 [20:24<03:59,  4.77it/s]

Processing tickers:  83%|████████▎ | 5711/6855 [20:25<04:02,  4.72it/s]

Processing tickers:  83%|████████▎ | 5712/6855 [20:25<04:04,  4.67it/s]

Processing tickers:  83%|████████▎ | 5713/6855 [20:25<04:05,  4.65it/s]

Processing tickers:  83%|████████▎ | 5714/6855 [20:25<04:08,  4.59it/s]

Processing tickers:  83%|████████▎ | 5715/6855 [20:26<04:06,  4.63it/s]

Processing tickers:  83%|████████▎ | 5716/6855 [20:26<04:08,  4.58it/s]

Processing tickers:  83%|████████▎ | 5717/6855 [20:26<04:06,  4.62it/s]

Processing tickers:  83%|████████▎ | 5718/6855 [20:26<04:06,  4.61it/s]

Processing tickers:  83%|████████▎ | 5719/6855 [20:26<04:03,  4.67it/s]

Processing tickers:  83%|████████▎ | 5720/6855 [20:27<04:00,  4.72it/s]

Processing tickers:  83%|████████▎ | 5721/6855 [20:27<03:57,  4.77it/s]

Processing tickers:  83%|████████▎ | 5722/6855 [20:27<03:57,  4.77it/s]

Processing tickers:  83%|████████▎ | 5723/6855 [20:27<03:58,  4.76it/s]

Processing tickers:  84%|████████▎ | 5724/6855 [20:27<03:57,  4.76it/s]

Processing tickers:  84%|████████▎ | 5725/6855 [20:28<03:56,  4.77it/s]

Processing tickers:  84%|████████▎ | 5726/6855 [20:28<03:57,  4.76it/s]

Processing tickers:  84%|████████▎ | 5727/6855 [20:28<03:56,  4.77it/s]

Processing tickers:  84%|████████▎ | 5728/6855 [20:28<03:56,  4.76it/s]

Processing tickers:  84%|████████▎ | 5729/6855 [20:29<03:55,  4.77it/s]

Processing tickers:  84%|████████▎ | 5730/6855 [20:29<03:56,  4.76it/s]

Processing tickers:  84%|████████▎ | 5731/6855 [20:29<03:59,  4.68it/s]

Processing tickers:  84%|████████▎ | 5732/6855 [20:29<03:57,  4.73it/s]

Processing tickers:  84%|████████▎ | 5733/6855 [20:29<03:56,  4.74it/s]

Processing tickers:  84%|████████▎ | 5734/6855 [20:30<03:59,  4.67it/s]

Processing tickers:  84%|████████▎ | 5735/6855 [20:30<03:57,  4.72it/s]

Processing tickers:  84%|████████▎ | 5736/6855 [20:30<03:54,  4.76it/s]

Processing tickers:  84%|████████▎ | 5737/6855 [20:30<03:54,  4.76it/s]

Processing tickers:  84%|████████▎ | 5738/6855 [20:30<04:02,  4.61it/s]

Processing tickers:  84%|████████▎ | 5739/6855 [20:31<03:59,  4.66it/s]

Processing tickers:  84%|████████▎ | 5740/6855 [20:31<03:58,  4.68it/s]

Processing tickers:  84%|████████▎ | 5741/6855 [20:31<03:56,  4.71it/s]

Processing tickers:  84%|████████▍ | 5742/6855 [20:31<03:59,  4.64it/s]

Processing tickers:  84%|████████▍ | 5743/6855 [20:32<03:59,  4.64it/s]

Processing tickers:  84%|████████▍ | 5744/6855 [20:32<03:58,  4.67it/s]

Processing tickers:  84%|████████▍ | 5745/6855 [20:32<03:56,  4.69it/s]

Processing tickers:  84%|████████▍ | 5746/6855 [20:32<03:53,  4.74it/s]

Processing tickers:  84%|████████▍ | 5747/6855 [20:32<03:54,  4.73it/s]

Processing tickers:  84%|████████▍ | 5748/6855 [20:33<04:02,  4.56it/s]

Processing tickers:  84%|████████▍ | 5749/6855 [20:33<03:58,  4.64it/s]

Processing tickers:  84%|████████▍ | 5750/6855 [20:33<03:55,  4.70it/s]

Processing tickers:  84%|████████▍ | 5751/6855 [20:33<03:54,  4.70it/s]

Processing tickers:  84%|████████▍ | 5752/6855 [20:33<03:55,  4.69it/s]

Processing tickers:  84%|████████▍ | 5753/6855 [20:34<03:54,  4.70it/s]

Processing tickers:  84%|████████▍ | 5754/6855 [20:34<03:51,  4.75it/s]

Processing tickers:  84%|████████▍ | 5755/6855 [20:34<03:51,  4.76it/s]

Processing tickers:  84%|████████▍ | 5756/6855 [20:34<03:50,  4.77it/s]

Processing tickers:  84%|████████▍ | 5757/6855 [20:34<03:51,  4.74it/s]

Processing tickers:  84%|████████▍ | 5758/6855 [20:35<03:49,  4.78it/s]

Processing tickers:  84%|████████▍ | 5759/6855 [20:35<03:49,  4.78it/s]

Processing tickers:  84%|████████▍ | 5760/6855 [20:35<03:48,  4.78it/s]

Processing tickers:  84%|████████▍ | 5761/6855 [20:35<03:48,  4.79it/s]

Processing tickers:  84%|████████▍ | 5762/6855 [20:36<03:48,  4.79it/s]

Processing tickers:  84%|████████▍ | 5763/6855 [20:36<03:48,  4.77it/s]

Processing tickers:  84%|████████▍ | 5764/6855 [20:36<03:48,  4.77it/s]

Processing tickers:  84%|████████▍ | 5765/6855 [20:36<03:48,  4.77it/s]

Processing tickers:  84%|████████▍ | 5766/6855 [20:36<03:48,  4.76it/s]

Processing tickers:  84%|████████▍ | 5767/6855 [20:37<03:47,  4.79it/s]

Processing tickers:  84%|████████▍ | 5768/6855 [20:37<03:50,  4.72it/s]

Processing tickers:  84%|████████▍ | 5769/6855 [20:37<03:49,  4.74it/s]

Processing tickers:  84%|████████▍ | 5770/6855 [20:37<03:50,  4.71it/s]

Processing tickers:  84%|████████▍ | 5771/6855 [20:37<03:56,  4.59it/s]

Processing tickers:  84%|████████▍ | 5772/6855 [20:38<04:03,  4.45it/s]

Processing tickers:  84%|████████▍ | 5773/6855 [20:38<03:58,  4.53it/s]

Processing tickers:  84%|████████▍ | 5774/6855 [20:38<03:53,  4.62it/s]

Processing tickers:  84%|████████▍ | 5775/6855 [20:38<03:52,  4.65it/s]

Processing tickers:  84%|████████▍ | 5776/6855 [20:39<03:50,  4.68it/s]

Processing tickers:  84%|████████▍ | 5777/6855 [20:39<03:48,  4.71it/s]

Processing tickers:  84%|████████▍ | 5778/6855 [20:39<03:47,  4.73it/s]

Processing tickers:  84%|████████▍ | 5779/6855 [20:39<03:47,  4.72it/s]

Processing tickers:  84%|████████▍ | 5780/6855 [20:39<03:46,  4.74it/s]

Processing tickers:  84%|████████▍ | 5781/6855 [20:40<03:52,  4.62it/s]

Processing tickers:  84%|████████▍ | 5782/6855 [20:40<03:50,  4.65it/s]

Processing tickers:  84%|████████▍ | 5783/6855 [20:40<03:49,  4.67it/s]

Processing tickers:  84%|████████▍ | 5784/6855 [20:40<03:49,  4.67it/s]

Processing tickers:  84%|████████▍ | 5785/6855 [20:40<03:46,  4.73it/s]

Processing tickers:  84%|████████▍ | 5786/6855 [20:41<03:45,  4.73it/s]

Processing tickers:  84%|████████▍ | 5787/6855 [20:41<03:44,  4.77it/s]

Processing tickers:  84%|████████▍ | 5788/6855 [20:41<03:48,  4.67it/s]

Processing tickers:  84%|████████▍ | 5789/6855 [20:41<03:46,  4.71it/s]

Processing tickers:  84%|████████▍ | 5790/6855 [20:41<03:44,  4.74it/s]

Processing tickers:  84%|████████▍ | 5791/6855 [20:42<03:43,  4.75it/s]

Processing tickers:  84%|████████▍ | 5792/6855 [20:42<03:43,  4.75it/s]

Processing tickers:  85%|████████▍ | 5793/6855 [20:42<03:43,  4.74it/s]

Processing tickers:  85%|████████▍ | 5794/6855 [20:42<03:43,  4.75it/s]

Processing tickers:  85%|████████▍ | 5795/6855 [20:43<03:43,  4.75it/s]

Processing tickers:  85%|████████▍ | 5796/6855 [20:43<03:42,  4.77it/s]

Processing tickers:  85%|████████▍ | 5797/6855 [20:43<03:40,  4.79it/s]

Processing tickers:  85%|████████▍ | 5798/6855 [20:43<03:45,  4.69it/s]

Processing tickers:  85%|████████▍ | 5799/6855 [20:43<03:45,  4.68it/s]

Processing tickers:  85%|████████▍ | 5800/6855 [20:44<03:46,  4.66it/s]

Processing tickers:  85%|████████▍ | 5801/6855 [20:44<03:44,  4.70it/s]

Processing tickers:  85%|████████▍ | 5802/6855 [20:44<03:44,  4.68it/s]

Processing tickers:  85%|████████▍ | 5803/6855 [20:44<03:42,  4.72it/s]

Processing tickers:  85%|████████▍ | 5804/6855 [20:44<03:43,  4.70it/s]

Processing tickers:  85%|████████▍ | 5805/6855 [20:45<03:41,  4.75it/s]

Processing tickers:  85%|████████▍ | 5806/6855 [20:45<03:39,  4.78it/s]

Processing tickers:  85%|████████▍ | 5807/6855 [20:45<03:39,  4.78it/s]

Processing tickers:  85%|████████▍ | 5808/6855 [20:45<03:41,  4.73it/s]

Processing tickers:  85%|████████▍ | 5809/6855 [20:46<03:40,  4.74it/s]

Processing tickers:  85%|████████▍ | 5810/6855 [20:46<03:38,  4.77it/s]

Processing tickers:  85%|████████▍ | 5811/6855 [20:46<03:41,  4.72it/s]

Processing tickers:  85%|████████▍ | 5812/6855 [20:46<03:41,  4.71it/s]

Processing tickers:  85%|████████▍ | 5813/6855 [20:46<03:43,  4.66it/s]

Processing tickers:  85%|████████▍ | 5814/6855 [20:47<03:45,  4.61it/s]

Processing tickers:  85%|████████▍ | 5815/6855 [20:47<03:44,  4.64it/s]

Processing tickers:  85%|████████▍ | 5816/6855 [20:47<03:49,  4.52it/s]

Processing tickers:  85%|████████▍ | 5817/6855 [20:47<03:45,  4.60it/s]

Processing tickers:  85%|████████▍ | 5818/6855 [20:47<03:48,  4.53it/s]

Processing tickers:  85%|████████▍ | 5819/6855 [20:48<03:44,  4.62it/s]

Processing tickers:  85%|████████▍ | 5820/6855 [20:48<03:42,  4.66it/s]

Processing tickers:  85%|████████▍ | 5821/6855 [20:48<03:39,  4.70it/s]

Processing tickers:  85%|████████▍ | 5822/6855 [20:48<03:40,  4.69it/s]

Processing tickers:  85%|████████▍ | 5823/6855 [20:49<03:38,  4.73it/s]

Processing tickers:  85%|████████▍ | 5824/6855 [20:49<03:37,  4.74it/s]

Processing tickers:  85%|████████▍ | 5825/6855 [20:49<03:39,  4.70it/s]

Processing tickers:  85%|████████▍ | 5826/6855 [20:49<03:37,  4.73it/s]

Processing tickers:  85%|████████▌ | 5827/6855 [20:49<03:37,  4.73it/s]

Processing tickers:  85%|████████▌ | 5828/6855 [20:50<03:40,  4.66it/s]

Processing tickers:  85%|████████▌ | 5829/6855 [20:50<03:53,  4.39it/s]

Processing tickers:  85%|████████▌ | 5830/6855 [20:50<03:48,  4.49it/s]

Processing tickers:  85%|████████▌ | 5831/6855 [20:50<03:44,  4.56it/s]

Processing tickers:  85%|████████▌ | 5832/6855 [20:51<03:52,  4.39it/s]

Processing tickers:  85%|████████▌ | 5833/6855 [20:51<03:46,  4.51it/s]

Processing tickers:  85%|████████▌ | 5834/6855 [20:51<03:47,  4.48it/s]

Processing tickers:  85%|████████▌ | 5835/6855 [20:51<03:49,  4.44it/s]

Processing tickers:  85%|████████▌ | 5836/6855 [20:51<03:45,  4.51it/s]

Processing tickers:  85%|████████▌ | 5837/6855 [20:52<03:43,  4.55it/s]

Processing tickers:  85%|████████▌ | 5838/6855 [20:52<03:38,  4.65it/s]

Processing tickers:  85%|████████▌ | 5839/6855 [20:52<03:38,  4.65it/s]

Processing tickers:  85%|████████▌ | 5840/6855 [20:52<03:38,  4.65it/s]

Processing tickers:  85%|████████▌ | 5841/6855 [20:52<03:36,  4.69it/s]

Processing tickers:  85%|████████▌ | 5842/6855 [20:53<03:37,  4.66it/s]

Processing tickers:  85%|████████▌ | 5843/6855 [20:53<03:35,  4.69it/s]

Processing tickers:  85%|████████▌ | 5844/6855 [20:53<03:33,  4.73it/s]

Processing tickers:  85%|████████▌ | 5845/6855 [20:53<03:40,  4.58it/s]

Processing tickers:  85%|████████▌ | 5846/6855 [20:54<03:39,  4.59it/s]

Processing tickers:  85%|████████▌ | 5847/6855 [20:54<03:37,  4.63it/s]

Processing tickers:  85%|████████▌ | 5848/6855 [20:54<03:34,  4.69it/s]

Processing tickers:  85%|████████▌ | 5849/6855 [20:54<03:35,  4.67it/s]

Processing tickers:  85%|████████▌ | 5850/6855 [20:54<03:33,  4.70it/s]

Processing tickers:  85%|████████▌ | 5851/6855 [20:55<03:31,  4.74it/s]

Processing tickers:  85%|████████▌ | 5852/6855 [20:55<03:31,  4.75it/s]

Processing tickers:  85%|████████▌ | 5853/6855 [20:55<03:30,  4.77it/s]

Processing tickers:  85%|████████▌ | 5854/6855 [20:55<03:31,  4.72it/s]

Processing tickers:  85%|████████▌ | 5855/6855 [20:55<03:31,  4.73it/s]

Processing tickers:  85%|████████▌ | 5856/6855 [20:56<03:29,  4.77it/s]

Processing tickers:  85%|████████▌ | 5857/6855 [20:56<03:28,  4.79it/s]

Processing tickers:  85%|████████▌ | 5858/6855 [20:56<03:31,  4.72it/s]

Processing tickers:  85%|████████▌ | 5859/6855 [20:56<03:33,  4.67it/s]

Processing tickers:  85%|████████▌ | 5860/6855 [20:57<03:35,  4.61it/s]

Processing tickers:  85%|████████▌ | 5861/6855 [20:57<03:34,  4.63it/s]

Processing tickers:  86%|████████▌ | 5862/6855 [20:57<03:31,  4.69it/s]

Processing tickers:  86%|████████▌ | 5863/6855 [20:57<03:29,  4.73it/s]

Processing tickers:  86%|████████▌ | 5864/6855 [20:57<03:29,  4.73it/s]

Processing tickers:  86%|████████▌ | 5865/6855 [20:58<03:27,  4.77it/s]

Processing tickers:  86%|████████▌ | 5866/6855 [20:58<03:26,  4.78it/s]

Processing tickers:  86%|████████▌ | 5867/6855 [20:58<03:26,  4.78it/s]

Processing tickers:  86%|████████▌ | 5868/6855 [20:58<03:30,  4.68it/s]

Processing tickers:  86%|████████▌ | 5869/6855 [20:58<03:28,  4.73it/s]

Processing tickers:  86%|████████▌ | 5870/6855 [20:59<03:27,  4.74it/s]

Processing tickers:  86%|████████▌ | 5871/6855 [20:59<03:27,  4.74it/s]

Processing tickers:  86%|████████▌ | 5872/6855 [20:59<03:31,  4.65it/s]

Processing tickers:  86%|████████▌ | 5873/6855 [20:59<03:28,  4.71it/s]

Processing tickers:  86%|████████▌ | 5874/6855 [20:59<03:27,  4.74it/s]

Processing tickers:  86%|████████▌ | 5875/6855 [21:00<03:28,  4.70it/s]

Processing tickers:  86%|████████▌ | 5876/6855 [21:00<03:25,  4.76it/s]

Processing tickers:  86%|████████▌ | 5877/6855 [21:00<03:25,  4.76it/s]

Processing tickers:  86%|████████▌ | 5878/6855 [21:00<03:28,  4.68it/s]

Processing tickers:  86%|████████▌ | 5879/6855 [21:01<03:35,  4.52it/s]

Processing tickers:  86%|████████▌ | 5880/6855 [21:01<03:33,  4.58it/s]

Processing tickers:  86%|████████▌ | 5881/6855 [21:01<03:30,  4.62it/s]

Processing tickers:  86%|████████▌ | 5882/6855 [21:01<03:32,  4.58it/s]

Processing tickers:  86%|████████▌ | 5883/6855 [21:01<03:28,  4.66it/s]

Processing tickers:  86%|████████▌ | 5884/6855 [21:02<03:27,  4.68it/s]

Processing tickers:  86%|████████▌ | 5885/6855 [21:02<03:33,  4.55it/s]

Processing tickers:  86%|████████▌ | 5886/6855 [21:02<03:30,  4.60it/s]

Processing tickers:  86%|████████▌ | 5887/6855 [21:02<03:26,  4.68it/s]

Processing tickers:  86%|████████▌ | 5888/6855 [21:02<03:24,  4.72it/s]

Processing tickers:  86%|████████▌ | 5889/6855 [21:03<03:22,  4.77it/s]

Processing tickers:  86%|████████▌ | 5890/6855 [21:03<03:21,  4.80it/s]

Processing tickers:  86%|████████▌ | 5891/6855 [21:03<03:26,  4.67it/s]

Processing tickers:  86%|████████▌ | 5892/6855 [21:03<03:26,  4.66it/s]

Processing tickers:  86%|████████▌ | 5893/6855 [21:04<03:26,  4.66it/s]

Processing tickers:  86%|████████▌ | 5894/6855 [21:04<03:26,  4.66it/s]

Processing tickers:  86%|████████▌ | 5895/6855 [21:04<03:23,  4.71it/s]

Processing tickers:  86%|████████▌ | 5896/6855 [21:04<03:24,  4.68it/s]

Processing tickers:  86%|████████▌ | 5897/6855 [21:04<03:21,  4.75it/s]

Processing tickers:  86%|████████▌ | 5898/6855 [21:05<03:20,  4.78it/s]

Processing tickers:  86%|████████▌ | 5899/6855 [21:05<03:19,  4.80it/s]

Processing tickers:  86%|████████▌ | 5900/6855 [21:05<03:19,  4.78it/s]

Processing tickers:  86%|████████▌ | 5901/6855 [21:05<03:19,  4.77it/s]

Processing tickers:  86%|████████▌ | 5902/6855 [21:05<03:18,  4.81it/s]

Processing tickers:  86%|████████▌ | 5903/6855 [21:06<03:17,  4.81it/s]

Processing tickers:  86%|████████▌ | 5904/6855 [21:06<03:19,  4.77it/s]

Processing tickers:  86%|████████▌ | 5905/6855 [21:06<03:19,  4.76it/s]

Processing tickers:  86%|████████▌ | 5906/6855 [21:06<03:26,  4.60it/s]

Processing tickers:  86%|████████▌ | 5907/6855 [21:07<03:26,  4.60it/s]

Processing tickers:  86%|████████▌ | 5908/6855 [21:07<03:24,  4.63it/s]

Processing tickers:  86%|████████▌ | 5909/6855 [21:07<03:21,  4.69it/s]

Processing tickers:  86%|████████▌ | 5910/6855 [21:07<03:20,  4.72it/s]

Processing tickers:  86%|████████▌ | 5911/6855 [21:07<03:19,  4.72it/s]

Processing tickers:  86%|████████▌ | 5912/6855 [21:08<03:20,  4.71it/s]

Processing tickers:  86%|████████▋ | 5913/6855 [21:08<03:22,  4.65it/s]

Processing tickers:  86%|████████▋ | 5914/6855 [21:08<03:24,  4.59it/s]

Processing tickers:  86%|████████▋ | 5915/6855 [21:08<03:27,  4.52it/s]

Processing tickers:  86%|████████▋ | 5916/6855 [21:08<03:24,  4.58it/s]

Processing tickers:  86%|████████▋ | 5917/6855 [21:09<03:22,  4.63it/s]

Processing tickers:  86%|████████▋ | 5918/6855 [21:09<03:21,  4.65it/s]

Processing tickers:  86%|████████▋ | 5919/6855 [21:09<03:19,  4.70it/s]

Processing tickers:  86%|████████▋ | 5920/6855 [21:09<03:20,  4.65it/s]

Processing tickers:  86%|████████▋ | 5921/6855 [21:10<03:18,  4.70it/s]

Processing tickers:  86%|████████▋ | 5922/6855 [21:10<03:18,  4.70it/s]

Processing tickers:  86%|████████▋ | 5923/6855 [21:10<03:16,  4.73it/s]

Processing tickers:  86%|████████▋ | 5924/6855 [21:10<03:15,  4.76it/s]

Processing tickers:  86%|████████▋ | 5925/6855 [21:10<03:15,  4.76it/s]

Processing tickers:  86%|████████▋ | 5926/6855 [21:11<03:15,  4.74it/s]

Processing tickers:  86%|████████▋ | 5927/6855 [21:11<03:15,  4.74it/s]

Processing tickers:  86%|████████▋ | 5928/6855 [21:11<03:13,  4.78it/s]

Processing tickers:  86%|████████▋ | 5929/6855 [21:11<03:21,  4.60it/s]

Processing tickers:  87%|████████▋ | 5930/6855 [21:11<03:19,  4.64it/s]

Processing tickers:  87%|████████▋ | 5931/6855 [21:12<03:15,  4.71it/s]

Processing tickers:  87%|████████▋ | 5932/6855 [21:12<03:18,  4.65it/s]

Processing tickers:  87%|████████▋ | 5933/6855 [21:12<03:19,  4.62it/s]

Processing tickers:  87%|████████▋ | 5934/6855 [21:12<03:18,  4.65it/s]

Processing tickers:  87%|████████▋ | 5935/6855 [21:12<03:15,  4.71it/s]

Processing tickers:  87%|████████▋ | 5936/6855 [21:13<03:20,  4.57it/s]

Processing tickers:  87%|████████▋ | 5937/6855 [21:13<03:23,  4.51it/s]

Processing tickers:  87%|████████▋ | 5938/6855 [21:13<03:20,  4.58it/s]

Processing tickers:  87%|████████▋ | 5939/6855 [21:13<03:24,  4.48it/s]

Processing tickers:  87%|████████▋ | 5940/6855 [21:14<03:22,  4.52it/s]

Processing tickers:  87%|████████▋ | 5941/6855 [21:14<03:19,  4.58it/s]

Processing tickers:  87%|████████▋ | 5942/6855 [21:14<03:15,  4.67it/s]

Processing tickers:  87%|████████▋ | 5943/6855 [21:14<03:17,  4.63it/s]

Processing tickers:  87%|████████▋ | 5944/6855 [21:14<03:14,  4.68it/s]

Processing tickers:  87%|████████▋ | 5945/6855 [21:15<03:14,  4.69it/s]

Processing tickers:  87%|████████▋ | 5946/6855 [21:15<03:19,  4.57it/s]

Processing tickers:  87%|████████▋ | 5947/6855 [21:15<03:16,  4.63it/s]

Processing tickers:  87%|████████▋ | 5948/6855 [21:15<03:14,  4.66it/s]

Processing tickers:  87%|████████▋ | 5949/6855 [21:16<03:13,  4.69it/s]

Processing tickers:  87%|████████▋ | 5950/6855 [21:16<03:11,  4.73it/s]

Processing tickers:  87%|████████▋ | 5951/6855 [21:16<03:10,  4.75it/s]

Processing tickers:  87%|████████▋ | 5952/6855 [21:16<03:08,  4.78it/s]

Processing tickers:  87%|████████▋ | 5953/6855 [21:16<03:16,  4.58it/s]

Processing tickers:  87%|████████▋ | 5954/6855 [21:17<03:19,  4.53it/s]

Processing tickers:  87%|████████▋ | 5955/6855 [21:17<03:22,  4.46it/s]

Processing tickers:  87%|████████▋ | 5956/6855 [21:17<03:20,  4.48it/s]

Processing tickers:  87%|████████▋ | 5957/6855 [21:17<03:21,  4.46it/s]

Processing tickers:  87%|████████▋ | 5958/6855 [21:18<03:18,  4.52it/s]

Processing tickers:  87%|████████▋ | 5959/6855 [21:18<03:14,  4.61it/s]

Processing tickers:  87%|████████▋ | 5960/6855 [21:18<03:12,  4.65it/s]

Processing tickers:  87%|████████▋ | 5961/6855 [21:18<03:11,  4.68it/s]

Processing tickers:  87%|████████▋ | 5962/6855 [21:18<03:10,  4.70it/s]

Processing tickers:  87%|████████▋ | 5963/6855 [21:19<03:09,  4.71it/s]

Processing tickers:  87%|████████▋ | 5964/6855 [21:19<03:08,  4.73it/s]

Processing tickers:  87%|████████▋ | 5965/6855 [21:19<03:07,  4.74it/s]

Processing tickers:  87%|████████▋ | 5966/6855 [21:19<03:08,  4.71it/s]

Processing tickers:  87%|████████▋ | 5967/6855 [21:19<03:07,  4.75it/s]

Processing tickers:  87%|████████▋ | 5968/6855 [21:20<03:08,  4.70it/s]

Processing tickers:  87%|████████▋ | 5969/6855 [21:20<03:08,  4.70it/s]

Processing tickers:  87%|████████▋ | 5970/6855 [21:20<03:12,  4.60it/s]

Processing tickers:  87%|████████▋ | 5971/6855 [21:20<03:11,  4.62it/s]

Processing tickers:  87%|████████▋ | 5972/6855 [21:20<03:10,  4.63it/s]

Processing tickers:  87%|████████▋ | 5973/6855 [21:21<03:09,  4.66it/s]

Processing tickers:  87%|████████▋ | 5974/6855 [21:21<03:07,  4.69it/s]

Processing tickers:  87%|████████▋ | 5975/6855 [21:21<03:07,  4.71it/s]

Processing tickers:  87%|████████▋ | 5976/6855 [21:21<03:05,  4.74it/s]

Processing tickers:  87%|████████▋ | 5977/6855 [21:22<03:03,  4.77it/s]

Processing tickers:  87%|████████▋ | 5978/6855 [21:22<03:04,  4.76it/s]

Processing tickers:  87%|████████▋ | 5979/6855 [21:22<03:11,  4.59it/s]

Processing tickers:  87%|████████▋ | 5980/6855 [21:22<03:11,  4.57it/s]

Processing tickers:  87%|████████▋ | 5981/6855 [21:22<03:12,  4.53it/s]

Processing tickers:  87%|████████▋ | 5982/6855 [21:23<03:10,  4.59it/s]

Processing tickers:  87%|████████▋ | 5983/6855 [21:23<03:08,  4.63it/s]

Processing tickers:  87%|████████▋ | 5984/6855 [21:23<03:06,  4.66it/s]

Processing tickers:  87%|████████▋ | 5985/6855 [21:23<03:12,  4.51it/s]

Processing tickers:  87%|████████▋ | 5986/6855 [21:24<03:09,  4.60it/s]

Processing tickers:  87%|████████▋ | 5987/6855 [21:24<03:06,  4.65it/s]

Processing tickers:  87%|████████▋ | 5988/6855 [21:24<03:05,  4.69it/s]

Processing tickers:  87%|████████▋ | 5989/6855 [21:24<03:07,  4.62it/s]

Processing tickers:  87%|████████▋ | 5990/6855 [21:24<03:06,  4.65it/s]

Processing tickers:  87%|████████▋ | 5991/6855 [21:25<03:02,  4.72it/s]

Processing tickers:  87%|████████▋ | 5992/6855 [21:25<03:03,  4.71it/s]

Processing tickers:  87%|████████▋ | 5993/6855 [21:25<03:00,  4.77it/s]

Processing tickers:  87%|████████▋ | 5994/6855 [21:25<03:02,  4.71it/s]

Processing tickers:  87%|████████▋ | 5995/6855 [21:25<03:02,  4.72it/s]

Processing tickers:  87%|████████▋ | 5996/6855 [21:26<03:03,  4.68it/s]

Processing tickers:  87%|████████▋ | 5997/6855 [21:26<03:08,  4.54it/s]

Processing tickers:  87%|████████▋ | 5998/6855 [21:26<03:05,  4.61it/s]

Processing tickers:  88%|████████▊ | 5999/6855 [21:26<03:06,  4.59it/s]

Processing tickers:  88%|████████▊ | 6000/6855 [21:26<03:03,  4.65it/s]

Processing tickers:  88%|████████▊ | 6001/6855 [21:27<03:02,  4.67it/s]

Processing tickers:  88%|████████▊ | 6002/6855 [21:27<03:07,  4.55it/s]

Processing tickers:  88%|████████▊ | 6003/6855 [21:27<03:05,  4.60it/s]

Processing tickers:  88%|████████▊ | 6004/6855 [21:27<03:05,  4.58it/s]

Processing tickers:  88%|████████▊ | 6005/6855 [21:28<03:04,  4.61it/s]

Processing tickers:  88%|████████▊ | 6006/6855 [21:28<03:07,  4.53it/s]

Processing tickers:  88%|████████▊ | 6007/6855 [21:28<03:04,  4.60it/s]

Processing tickers:  88%|████████▊ | 6008/6855 [21:28<03:02,  4.64it/s]

Processing tickers:  88%|████████▊ | 6009/6855 [21:28<03:03,  4.60it/s]

Processing tickers:  88%|████████▊ | 6010/6855 [21:29<03:00,  4.67it/s]

Processing tickers:  88%|████████▊ | 6011/6855 [21:29<03:01,  4.66it/s]

Processing tickers:  88%|████████▊ | 6012/6855 [21:29<03:00,  4.67it/s]

Processing tickers:  88%|████████▊ | 6013/6855 [21:29<02:59,  4.70it/s]

Processing tickers:  88%|████████▊ | 6014/6855 [21:30<02:58,  4.71it/s]

Processing tickers:  88%|████████▊ | 6015/6855 [21:30<03:00,  4.66it/s]

Processing tickers:  88%|████████▊ | 6016/6855 [21:30<02:57,  4.71it/s]

Processing tickers:  88%|████████▊ | 6017/6855 [21:30<02:58,  4.70it/s]

Processing tickers:  88%|████████▊ | 6018/6855 [21:30<02:56,  4.74it/s]

Processing tickers:  88%|████████▊ | 6019/6855 [21:31<03:00,  4.63it/s]

Processing tickers:  88%|████████▊ | 6020/6855 [21:31<02:58,  4.68it/s]

Processing tickers:  88%|████████▊ | 6021/6855 [21:31<02:55,  4.74it/s]

Processing tickers:  88%|████████▊ | 6022/6855 [21:31<02:54,  4.76it/s]

Processing tickers:  88%|████████▊ | 6023/6855 [21:31<02:54,  4.78it/s]

Processing tickers:  88%|████████▊ | 6024/6855 [21:32<02:56,  4.72it/s]

Processing tickers:  88%|████████▊ | 6025/6855 [21:32<02:54,  4.76it/s]

Processing tickers:  88%|████████▊ | 6026/6855 [21:32<02:59,  4.62it/s]

Processing tickers:  88%|████████▊ | 6027/6855 [21:32<02:57,  4.67it/s]

Processing tickers:  88%|████████▊ | 6028/6855 [21:33<02:57,  4.66it/s]

Processing tickers:  88%|████████▊ | 6029/6855 [21:33<02:56,  4.68it/s]

Processing tickers:  88%|████████▊ | 6030/6855 [21:33<03:00,  4.58it/s]

Processing tickers:  88%|████████▊ | 6031/6855 [21:33<03:05,  4.45it/s]

Processing tickers:  88%|████████▊ | 6032/6855 [21:33<03:02,  4.51it/s]

Processing tickers:  88%|████████▊ | 6033/6855 [21:34<02:58,  4.60it/s]

Processing tickers:  88%|████████▊ | 6034/6855 [21:34<02:56,  4.65it/s]

Processing tickers:  88%|████████▊ | 6035/6855 [21:34<02:55,  4.67it/s]

Processing tickers:  88%|████████▊ | 6036/6855 [21:34<02:57,  4.61it/s]

Processing tickers:  88%|████████▊ | 6037/6855 [21:34<02:56,  4.65it/s]

Processing tickers:  88%|████████▊ | 6038/6855 [21:35<02:55,  4.65it/s]

Processing tickers:  88%|████████▊ | 6039/6855 [21:35<02:55,  4.65it/s]

Processing tickers:  88%|████████▊ | 6040/6855 [21:35<02:55,  4.64it/s]

Processing tickers:  88%|████████▊ | 6041/6855 [21:35<02:58,  4.56it/s]

Processing tickers:  88%|████████▊ | 6042/6855 [21:36<03:00,  4.49it/s]

Processing tickers:  88%|████████▊ | 6043/6855 [21:36<02:57,  4.57it/s]

Processing tickers:  88%|████████▊ | 6044/6855 [21:36<02:54,  4.64it/s]

Processing tickers:  88%|████████▊ | 6045/6855 [21:36<03:04,  4.38it/s]

Processing tickers:  88%|████████▊ | 6046/6855 [21:36<03:00,  4.47it/s]

Processing tickers:  88%|████████▊ | 6047/6855 [21:37<02:57,  4.55it/s]

Processing tickers:  88%|████████▊ | 6048/6855 [21:37<02:59,  4.48it/s]

Processing tickers:  88%|████████▊ | 6049/6855 [21:37<02:56,  4.57it/s]

Processing tickers:  88%|████████▊ | 6050/6855 [21:37<03:00,  4.46it/s]

Processing tickers:  88%|████████▊ | 6051/6855 [21:38<02:57,  4.52it/s]

Processing tickers:  88%|████████▊ | 6052/6855 [21:38<02:56,  4.54it/s]

Processing tickers:  88%|████████▊ | 6053/6855 [21:38<02:54,  4.58it/s]

Processing tickers:  88%|████████▊ | 6054/6855 [21:38<02:53,  4.61it/s]

Processing tickers:  88%|████████▊ | 6055/6855 [21:38<02:52,  4.63it/s]

Processing tickers:  88%|████████▊ | 6056/6855 [21:39<02:52,  4.63it/s]

Processing tickers:  88%|████████▊ | 6057/6855 [21:39<02:50,  4.68it/s]

Processing tickers:  88%|████████▊ | 6058/6855 [21:39<02:49,  4.71it/s]

Processing tickers:  88%|████████▊ | 6059/6855 [21:39<02:48,  4.72it/s]

Processing tickers:  88%|████████▊ | 6060/6855 [21:39<02:49,  4.69it/s]

Processing tickers:  88%|████████▊ | 6061/6855 [21:40<02:47,  4.75it/s]

Processing tickers:  88%|████████▊ | 6062/6855 [21:40<02:46,  4.75it/s]

Processing tickers:  88%|████████▊ | 6063/6855 [21:40<02:46,  4.77it/s]

Processing tickers:  88%|████████▊ | 6064/6855 [21:40<02:45,  4.78it/s]

Processing tickers:  88%|████████▊ | 6065/6855 [21:41<02:45,  4.78it/s]

Processing tickers:  88%|████████▊ | 6066/6855 [21:41<02:44,  4.79it/s]

Processing tickers:  89%|████████▊ | 6067/6855 [21:41<02:45,  4.77it/s]

Processing tickers:  89%|████████▊ | 6068/6855 [21:41<02:52,  4.55it/s]

Processing tickers:  89%|████████▊ | 6069/6855 [21:41<02:52,  4.56it/s]

Processing tickers:  89%|████████▊ | 6070/6855 [21:42<02:51,  4.58it/s]

Processing tickers:  89%|████████▊ | 6071/6855 [21:42<02:49,  4.63it/s]

Processing tickers:  89%|████████▊ | 6072/6855 [21:42<02:48,  4.65it/s]

Processing tickers:  89%|████████▊ | 6073/6855 [21:42<02:50,  4.57it/s]

Processing tickers:  89%|████████▊ | 6074/6855 [21:42<02:48,  4.64it/s]

Processing tickers:  89%|████████▊ | 6075/6855 [21:43<02:46,  4.70it/s]

Processing tickers:  89%|████████▊ | 6076/6855 [21:43<02:49,  4.61it/s]

Processing tickers:  89%|████████▊ | 6077/6855 [21:43<02:47,  4.65it/s]

Processing tickers:  89%|████████▊ | 6078/6855 [21:43<02:47,  4.63it/s]

Processing tickers:  89%|████████▊ | 6079/6855 [21:44<02:50,  4.56it/s]

Processing tickers:  89%|████████▊ | 6080/6855 [21:44<02:46,  4.64it/s]

Processing tickers:  89%|████████▊ | 6081/6855 [21:44<02:49,  4.56it/s]

Processing tickers:  89%|████████▊ | 6082/6855 [21:44<02:48,  4.59it/s]

Processing tickers:  89%|████████▊ | 6083/6855 [21:44<02:53,  4.46it/s]

Processing tickers:  89%|████████▉ | 6084/6855 [21:45<02:50,  4.51it/s]

Processing tickers:  89%|████████▉ | 6085/6855 [21:45<02:47,  4.59it/s]

Processing tickers:  89%|████████▉ | 6086/6855 [21:45<02:46,  4.62it/s]

Processing tickers:  89%|████████▉ | 6087/6855 [21:45<02:43,  4.69it/s]

Processing tickers:  89%|████████▉ | 6088/6855 [21:46<02:44,  4.67it/s]

Processing tickers:  89%|████████▉ | 6089/6855 [21:46<02:43,  4.68it/s]

Processing tickers:  89%|████████▉ | 6090/6855 [21:46<02:42,  4.71it/s]

Processing tickers:  89%|████████▉ | 6091/6855 [21:46<02:47,  4.57it/s]

Processing tickers:  89%|████████▉ | 6092/6855 [21:46<02:44,  4.63it/s]

Processing tickers:  89%|████████▉ | 6093/6855 [21:47<02:45,  4.60it/s]

Processing tickers:  89%|████████▉ | 6094/6855 [21:47<02:43,  4.65it/s]

Processing tickers:  89%|████████▉ | 6095/6855 [21:47<02:40,  4.74it/s]

Processing tickers:  89%|████████▉ | 6096/6855 [21:47<02:40,  4.72it/s]

Processing tickers:  89%|████████▉ | 6097/6855 [21:47<02:44,  4.62it/s]

Processing tickers:  89%|████████▉ | 6098/6855 [21:48<02:42,  4.66it/s]

Processing tickers:  89%|████████▉ | 6099/6855 [21:48<02:41,  4.68it/s]

Processing tickers:  89%|████████▉ | 6100/6855 [21:48<02:45,  4.56it/s]

Processing tickers:  89%|████████▉ | 6101/6855 [21:48<02:44,  4.59it/s]

Processing tickers:  89%|████████▉ | 6102/6855 [21:49<02:41,  4.66it/s]

Processing tickers:  89%|████████▉ | 6103/6855 [21:49<02:39,  4.72it/s]

Processing tickers:  89%|████████▉ | 6104/6855 [21:49<02:38,  4.74it/s]

Processing tickers:  89%|████████▉ | 6105/6855 [21:49<02:39,  4.72it/s]

Processing tickers:  89%|████████▉ | 6106/6855 [21:49<02:44,  4.56it/s]

Processing tickers:  89%|████████▉ | 6107/6855 [21:50<02:43,  4.57it/s]

Processing tickers:  89%|████████▉ | 6108/6855 [21:50<02:41,  4.62it/s]

Processing tickers:  89%|████████▉ | 6109/6855 [21:50<02:45,  4.49it/s]

Processing tickers:  89%|████████▉ | 6110/6855 [21:50<02:43,  4.55it/s]

Processing tickers:  89%|████████▉ | 6111/6855 [21:50<02:42,  4.58it/s]

Processing tickers:  89%|████████▉ | 6112/6855 [21:51<02:40,  4.63it/s]

Processing tickers:  89%|████████▉ | 6113/6855 [21:51<02:39,  4.64it/s]

Processing tickers:  89%|████████▉ | 6114/6855 [21:51<02:39,  4.66it/s]

Processing tickers:  89%|████████▉ | 6115/6855 [21:51<02:40,  4.60it/s]

Processing tickers:  89%|████████▉ | 6116/6855 [21:52<02:39,  4.62it/s]

Processing tickers:  89%|████████▉ | 6117/6855 [21:52<02:37,  4.69it/s]

Processing tickers:  89%|████████▉ | 6118/6855 [21:52<02:36,  4.70it/s]

Processing tickers:  89%|████████▉ | 6119/6855 [21:52<02:37,  4.69it/s]

Processing tickers:  89%|████████▉ | 6120/6855 [21:52<02:36,  4.69it/s]

Processing tickers:  89%|████████▉ | 6121/6855 [21:53<02:36,  4.68it/s]

Processing tickers:  89%|████████▉ | 6122/6855 [21:53<02:36,  4.70it/s]

Processing tickers:  89%|████████▉ | 6123/6855 [21:53<02:34,  4.75it/s]

Processing tickers:  89%|████████▉ | 6124/6855 [21:53<02:33,  4.77it/s]

Processing tickers:  89%|████████▉ | 6125/6855 [21:53<02:38,  4.61it/s]

Processing tickers:  89%|████████▉ | 6126/6855 [21:54<02:36,  4.66it/s]

Processing tickers:  89%|████████▉ | 6127/6855 [21:54<02:34,  4.70it/s]

Processing tickers:  89%|████████▉ | 6128/6855 [21:54<02:33,  4.73it/s]

Processing tickers:  89%|████████▉ | 6129/6855 [21:54<02:35,  4.68it/s]

Processing tickers:  89%|████████▉ | 6130/6855 [21:55<02:33,  4.73it/s]

Processing tickers:  89%|████████▉ | 6131/6855 [21:55<02:35,  4.66it/s]

Processing tickers:  89%|████████▉ | 6132/6855 [21:55<02:34,  4.69it/s]

Processing tickers:  89%|████████▉ | 6133/6855 [21:55<02:34,  4.67it/s]

Processing tickers:  89%|████████▉ | 6134/6855 [21:55<02:33,  4.69it/s]

Processing tickers:  89%|████████▉ | 6135/6855 [21:56<02:37,  4.59it/s]

Processing tickers:  90%|████████▉ | 6136/6855 [21:56<02:33,  4.67it/s]

Processing tickers:  90%|████████▉ | 6137/6855 [21:56<02:33,  4.66it/s]

Processing tickers:  90%|████████▉ | 6138/6855 [21:56<02:37,  4.56it/s]

Processing tickers:  90%|████████▉ | 6139/6855 [21:56<02:34,  4.64it/s]

Processing tickers:  90%|████████▉ | 6140/6855 [21:57<02:34,  4.63it/s]

Processing tickers:  90%|████████▉ | 6141/6855 [21:57<02:34,  4.64it/s]

Processing tickers:  90%|████████▉ | 6142/6855 [21:57<02:32,  4.67it/s]

Processing tickers:  90%|████████▉ | 6143/6855 [21:57<02:32,  4.68it/s]

Processing tickers:  90%|████████▉ | 6144/6855 [21:58<02:33,  4.64it/s]

Processing tickers:  90%|████████▉ | 6145/6855 [21:58<02:31,  4.68it/s]

Processing tickers:  90%|████████▉ | 6146/6855 [21:58<02:30,  4.71it/s]

Processing tickers:  90%|████████▉ | 6147/6855 [21:58<02:36,  4.51it/s]

Processing tickers:  90%|████████▉ | 6148/6855 [21:58<02:36,  4.52it/s]

Processing tickers:  90%|████████▉ | 6149/6855 [21:59<02:44,  4.29it/s]

Processing tickers:  90%|████████▉ | 6150/6855 [21:59<02:39,  4.43it/s]

Processing tickers:  90%|████████▉ | 6151/6855 [21:59<02:35,  4.53it/s]

Processing tickers:  90%|████████▉ | 6152/6855 [21:59<02:33,  4.59it/s]

Processing tickers:  90%|████████▉ | 6153/6855 [22:00<02:36,  4.48it/s]

Processing tickers:  90%|████████▉ | 6154/6855 [22:00<02:34,  4.53it/s]

Processing tickers:  90%|████████▉ | 6155/6855 [22:00<02:37,  4.46it/s]

Processing tickers:  90%|████████▉ | 6156/6855 [22:00<02:36,  4.46it/s]

Processing tickers:  90%|████████▉ | 6157/6855 [22:00<02:35,  4.49it/s]

Processing tickers:  90%|████████▉ | 6158/6855 [22:01<02:32,  4.56it/s]

Processing tickers:  90%|████████▉ | 6159/6855 [22:01<02:29,  4.64it/s]

Processing tickers:  90%|████████▉ | 6160/6855 [22:01<02:34,  4.48it/s]

Processing tickers:  90%|████████▉ | 6161/6855 [22:01<02:31,  4.58it/s]

Processing tickers:  90%|████████▉ | 6162/6855 [22:02<02:35,  4.46it/s]

Processing tickers:  90%|████████▉ | 6163/6855 [22:02<02:30,  4.60it/s]

Processing tickers:  90%|████████▉ | 6164/6855 [22:02<02:28,  4.67it/s]

Processing tickers:  90%|████████▉ | 6165/6855 [22:02<02:26,  4.72it/s]

Processing tickers:  90%|████████▉ | 6166/6855 [22:02<02:28,  4.64it/s]

Processing tickers:  90%|████████▉ | 6167/6855 [22:03<02:27,  4.66it/s]

Processing tickers:  90%|████████▉ | 6168/6855 [22:03<02:25,  4.71it/s]

Processing tickers:  90%|████████▉ | 6169/6855 [22:03<02:27,  4.65it/s]

Processing tickers:  90%|█████████ | 6170/6855 [22:04<05:54,  1.93it/s]

Processing tickers:  90%|█████████ | 6171/6855 [22:04<04:49,  2.36it/s]

Processing tickers:  90%|█████████ | 6172/6855 [22:05<04:06,  2.77it/s]

Processing tickers:  90%|█████████ | 6173/6855 [22:05<03:33,  3.19it/s]

Processing tickers:  90%|█████████ | 6174/6855 [22:05<03:12,  3.53it/s]

Processing tickers:  90%|█████████ | 6175/6855 [22:05<02:57,  3.82it/s]

Processing tickers:  90%|█████████ | 6176/6855 [22:06<02:48,  4.03it/s]

Processing tickers:  90%|█████████ | 6177/6855 [22:06<02:40,  4.22it/s]

Processing tickers:  90%|█████████ | 6178/6855 [22:06<02:39,  4.26it/s]

Processing tickers:  90%|█████████ | 6179/6855 [22:06<02:32,  4.42it/s]

Processing tickers:  90%|█████████ | 6180/6855 [22:06<02:31,  4.45it/s]

Processing tickers:  90%|█████████ | 6181/6855 [22:07<02:32,  4.42it/s]

Processing tickers:  90%|█████████ | 6182/6855 [22:07<02:28,  4.53it/s]

Processing tickers:  90%|█████████ | 6183/6855 [22:07<02:25,  4.62it/s]

Processing tickers:  90%|█████████ | 6184/6855 [22:07<02:23,  4.67it/s]

Processing tickers:  90%|█████████ | 6185/6855 [22:07<02:27,  4.53it/s]

Processing tickers:  90%|█████████ | 6186/6855 [22:08<02:29,  4.48it/s]

Processing tickers:  90%|█████████ | 6187/6855 [22:08<02:25,  4.58it/s]

Processing tickers:  90%|█████████ | 6188/6855 [22:08<02:26,  4.56it/s]

Processing tickers:  90%|█████████ | 6189/6855 [22:08<02:23,  4.65it/s]

Processing tickers:  90%|█████████ | 6190/6855 [22:09<02:26,  4.53it/s]

Processing tickers:  90%|█████████ | 6191/6855 [22:09<02:28,  4.47it/s]

Processing tickers:  90%|█████████ | 6192/6855 [22:09<02:26,  4.54it/s]

Processing tickers:  90%|█████████ | 6193/6855 [22:09<02:30,  4.40it/s]

Processing tickers:  90%|█████████ | 6194/6855 [22:09<02:27,  4.48it/s]

Processing tickers:  90%|█████████ | 6195/6855 [22:10<02:24,  4.58it/s]

Processing tickers:  90%|█████████ | 6196/6855 [22:10<02:22,  4.63it/s]

Processing tickers:  90%|█████████ | 6197/6855 [22:10<02:22,  4.62it/s]

Processing tickers:  90%|█████████ | 6198/6855 [22:10<02:25,  4.52it/s]

Processing tickers:  90%|█████████ | 6199/6855 [22:11<02:22,  4.59it/s]

Processing tickers:  90%|█████████ | 6200/6855 [22:11<02:22,  4.60it/s]

Processing tickers:  90%|█████████ | 6201/6855 [22:11<02:19,  4.68it/s]

Processing tickers:  90%|█████████ | 6202/6855 [22:11<02:22,  4.57it/s]

Processing tickers:  90%|█████████ | 6203/6855 [22:11<02:22,  4.58it/s]

Processing tickers:  91%|█████████ | 6204/6855 [22:12<02:21,  4.61it/s]

Processing tickers:  91%|█████████ | 6205/6855 [22:12<02:19,  4.65it/s]

Processing tickers:  91%|█████████ | 6206/6855 [22:12<02:18,  4.69it/s]

Processing tickers:  91%|█████████ | 6207/6855 [22:12<02:21,  4.57it/s]

Processing tickers:  91%|█████████ | 6208/6855 [22:13<02:25,  4.45it/s]

Processing tickers:  91%|█████████ | 6209/6855 [22:13<02:22,  4.53it/s]

Processing tickers:  91%|█████████ | 6210/6855 [22:13<02:24,  4.45it/s]

Processing tickers:  91%|█████████ | 6211/6855 [22:13<02:26,  4.40it/s]

Processing tickers:  91%|█████████ | 6212/6855 [22:13<02:28,  4.33it/s]

Processing tickers:  91%|█████████ | 6213/6855 [22:14<02:26,  4.37it/s]

Processing tickers:  91%|█████████ | 6214/6855 [22:14<02:24,  4.45it/s]

Processing tickers:  91%|█████████ | 6215/6855 [22:14<02:22,  4.48it/s]

Processing tickers:  91%|█████████ | 6216/6855 [22:14<02:20,  4.56it/s]

Processing tickers:  91%|█████████ | 6217/6855 [22:15<02:19,  4.57it/s]

Processing tickers:  91%|█████████ | 6218/6855 [22:15<02:19,  4.55it/s]

Processing tickers:  91%|█████████ | 6219/6855 [22:15<02:17,  4.64it/s]

Processing tickers:  91%|█████████ | 6220/6855 [22:15<02:15,  4.69it/s]

Processing tickers:  91%|█████████ | 6221/6855 [22:15<02:19,  4.55it/s]

Processing tickers:  91%|█████████ | 6222/6855 [22:16<02:17,  4.60it/s]

Processing tickers:  91%|█████████ | 6223/6855 [22:16<02:15,  4.67it/s]

Processing tickers:  91%|█████████ | 6224/6855 [22:16<02:14,  4.69it/s]

Processing tickers:  91%|█████████ | 6225/6855 [22:16<02:13,  4.73it/s]

Processing tickers:  91%|█████████ | 6226/6855 [22:16<02:12,  4.73it/s]

Processing tickers:  91%|█████████ | 6227/6855 [22:17<02:16,  4.59it/s]

Processing tickers:  91%|█████████ | 6228/6855 [22:17<02:14,  4.68it/s]

Processing tickers:  91%|█████████ | 6229/6855 [22:17<02:12,  4.72it/s]

Processing tickers:  91%|█████████ | 6230/6855 [22:17<02:13,  4.69it/s]

Processing tickers:  91%|█████████ | 6231/6855 [22:18<02:11,  4.73it/s]

Processing tickers:  91%|█████████ | 6232/6855 [22:18<02:11,  4.73it/s]

Processing tickers:  91%|█████████ | 6233/6855 [22:18<02:12,  4.70it/s]

Processing tickers:  91%|█████████ | 6234/6855 [22:18<02:11,  4.74it/s]

Processing tickers:  91%|█████████ | 6235/6855 [22:18<02:11,  4.71it/s]

Processing tickers:  91%|█████████ | 6236/6855 [22:19<02:14,  4.62it/s]

Processing tickers:  91%|█████████ | 6237/6855 [22:19<02:12,  4.66it/s]

Processing tickers:  91%|█████████ | 6238/6855 [22:19<02:11,  4.69it/s]

Processing tickers:  91%|█████████ | 6239/6855 [22:19<02:12,  4.64it/s]

Processing tickers:  91%|█████████ | 6240/6855 [22:19<02:14,  4.57it/s]

Processing tickers:  91%|█████████ | 6241/6855 [22:20<02:13,  4.59it/s]

Processing tickers:  91%|█████████ | 6242/6855 [22:20<02:11,  4.65it/s]

Processing tickers:  91%|█████████ | 6243/6855 [22:20<02:10,  4.69it/s]

Processing tickers:  91%|█████████ | 6244/6855 [22:20<02:10,  4.69it/s]

Processing tickers:  91%|█████████ | 6245/6855 [22:21<02:11,  4.65it/s]

Processing tickers:  91%|█████████ | 6246/6855 [22:21<02:09,  4.69it/s]

Processing tickers:  91%|█████████ | 6247/6855 [22:21<02:09,  4.69it/s]

Processing tickers:  91%|█████████ | 6248/6855 [22:21<02:09,  4.68it/s]

Processing tickers:  91%|█████████ | 6249/6855 [22:21<02:08,  4.71it/s]

Processing tickers:  91%|█████████ | 6250/6855 [22:22<02:13,  4.54it/s]

Processing tickers:  91%|█████████ | 6251/6855 [22:22<02:10,  4.62it/s]

Processing tickers:  91%|█████████ | 6252/6855 [22:22<02:08,  4.68it/s]

Processing tickers:  91%|█████████ | 6253/6855 [22:22<02:07,  4.73it/s]

Processing tickers:  91%|█████████ | 6254/6855 [22:22<02:06,  4.77it/s]

Processing tickers:  91%|█████████ | 6255/6855 [22:23<02:05,  4.77it/s]

Processing tickers:  91%|█████████▏| 6256/6855 [22:23<02:10,  4.58it/s]

Processing tickers:  91%|█████████▏| 6257/6855 [22:23<02:08,  4.65it/s]

Processing tickers:  91%|█████████▏| 6258/6855 [22:23<02:11,  4.55it/s]

Processing tickers:  91%|█████████▏| 6259/6855 [22:24<02:12,  4.49it/s]

Processing tickers:  91%|█████████▏| 6260/6855 [22:24<02:10,  4.54it/s]

Processing tickers:  91%|█████████▏| 6261/6855 [22:24<02:08,  4.62it/s]

Processing tickers:  91%|█████████▏| 6262/6855 [22:24<02:11,  4.50it/s]

Processing tickers:  91%|█████████▏| 6263/6855 [22:24<02:09,  4.57it/s]

Processing tickers:  91%|█████████▏| 6264/6855 [22:25<02:08,  4.61it/s]

Processing tickers:  91%|█████████▏| 6265/6855 [22:25<02:07,  4.63it/s]

Processing tickers:  91%|█████████▏| 6266/6855 [22:25<02:07,  4.63it/s]

Processing tickers:  91%|█████████▏| 6267/6855 [22:25<02:05,  4.70it/s]

Processing tickers:  91%|█████████▏| 6268/6855 [22:25<02:05,  4.68it/s]

Processing tickers:  91%|█████████▏| 6269/6855 [22:26<02:05,  4.68it/s]

Processing tickers:  91%|█████████▏| 6270/6855 [22:26<02:04,  4.70it/s]

Processing tickers:  91%|█████████▏| 6271/6855 [22:26<02:03,  4.72it/s]

Processing tickers:  91%|█████████▏| 6272/6855 [22:26<02:02,  4.77it/s]

Processing tickers:  92%|█████████▏| 6273/6855 [22:27<02:02,  4.75it/s]

Processing tickers:  92%|█████████▏| 6274/6855 [22:27<02:01,  4.79it/s]

Processing tickers:  92%|█████████▏| 6275/6855 [22:27<02:00,  4.81it/s]

Processing tickers:  92%|█████████▏| 6276/6855 [22:27<01:59,  4.83it/s]

Processing tickers:  92%|█████████▏| 6277/6855 [22:27<01:59,  4.82it/s]

Processing tickers:  92%|█████████▏| 6278/6855 [22:28<02:00,  4.78it/s]

Processing tickers:  92%|█████████▏| 6279/6855 [22:28<02:01,  4.74it/s]

Processing tickers:  92%|█████████▏| 6280/6855 [22:28<02:03,  4.64it/s]

Processing tickers:  92%|█████████▏| 6281/6855 [22:28<02:05,  4.58it/s]

Processing tickers:  92%|█████████▏| 6282/6855 [22:28<02:03,  4.65it/s]

Processing tickers:  92%|█████████▏| 6283/6855 [22:29<02:01,  4.69it/s]

Processing tickers:  92%|█████████▏| 6284/6855 [22:29<02:01,  4.71it/s]

Processing tickers:  92%|█████████▏| 6285/6855 [22:29<02:00,  4.73it/s]

Processing tickers:  92%|█████████▏| 6286/6855 [22:29<01:58,  4.78it/s]

Processing tickers:  92%|█████████▏| 6287/6855 [22:29<01:58,  4.79it/s]

Processing tickers:  92%|█████████▏| 6288/6855 [22:30<01:57,  4.81it/s]

Processing tickers:  92%|█████████▏| 6289/6855 [22:30<01:57,  4.80it/s]

Processing tickers:  92%|█████████▏| 6290/6855 [22:30<01:58,  4.78it/s]

Processing tickers:  92%|█████████▏| 6291/6855 [22:30<02:01,  4.65it/s]

Processing tickers:  92%|█████████▏| 6292/6855 [22:31<02:00,  4.66it/s]

Processing tickers:  92%|█████████▏| 6293/6855 [22:31<01:59,  4.69it/s]

Processing tickers:  92%|█████████▏| 6294/6855 [22:31<01:58,  4.74it/s]

Processing tickers:  92%|█████████▏| 6295/6855 [22:31<01:59,  4.70it/s]

Processing tickers:  92%|█████████▏| 6296/6855 [22:31<01:57,  4.74it/s]

Processing tickers:  92%|█████████▏| 6297/6855 [22:32<01:57,  4.76it/s]

Processing tickers:  92%|█████████▏| 6298/6855 [22:32<02:01,  4.57it/s]

Processing tickers:  92%|█████████▏| 6299/6855 [22:32<02:01,  4.58it/s]

Processing tickers:  92%|█████████▏| 6300/6855 [22:32<02:00,  4.62it/s]

Processing tickers:  92%|█████████▏| 6301/6855 [22:32<02:03,  4.49it/s]

Processing tickers:  92%|█████████▏| 6302/6855 [22:33<02:00,  4.57it/s]

Processing tickers:  92%|█████████▏| 6303/6855 [22:33<01:58,  4.65it/s]

Processing tickers:  92%|█████████▏| 6304/6855 [22:33<01:57,  4.69it/s]

Processing tickers:  92%|█████████▏| 6305/6855 [22:33<01:56,  4.72it/s]

Processing tickers:  92%|█████████▏| 6306/6855 [22:34<01:59,  4.61it/s]

Processing tickers:  92%|█████████▏| 6307/6855 [22:34<01:59,  4.58it/s]

Processing tickers:  92%|█████████▏| 6308/6855 [22:34<01:57,  4.64it/s]

Processing tickers:  92%|█████████▏| 6309/6855 [22:34<01:58,  4.61it/s]

Processing tickers:  92%|█████████▏| 6310/6855 [22:34<01:56,  4.70it/s]

Processing tickers:  92%|█████████▏| 6311/6855 [22:35<01:55,  4.70it/s]

Processing tickers:  92%|█████████▏| 6312/6855 [22:35<01:54,  4.75it/s]

Processing tickers:  92%|█████████▏| 6313/6855 [22:35<01:53,  4.78it/s]

Processing tickers:  92%|█████████▏| 6314/6855 [22:35<01:54,  4.75it/s]

Processing tickers:  92%|█████████▏| 6315/6855 [22:35<01:53,  4.77it/s]

Processing tickers:  92%|█████████▏| 6316/6855 [22:36<01:52,  4.79it/s]

Processing tickers:  92%|█████████▏| 6317/6855 [22:36<01:52,  4.77it/s]

Processing tickers:  92%|█████████▏| 6318/6855 [22:36<01:52,  4.76it/s]

Processing tickers:  92%|█████████▏| 6319/6855 [22:36<01:56,  4.58it/s]

Processing tickers:  92%|█████████▏| 6320/6855 [22:37<01:56,  4.61it/s]

Processing tickers:  92%|█████████▏| 6321/6855 [22:37<01:55,  4.60it/s]

Processing tickers:  92%|█████████▏| 6322/6855 [22:37<01:59,  4.45it/s]

Processing tickers:  92%|█████████▏| 6323/6855 [22:37<01:57,  4.54it/s]

Processing tickers:  92%|█████████▏| 6324/6855 [22:37<01:57,  4.50it/s]

Processing tickers:  92%|█████████▏| 6325/6855 [22:38<01:55,  4.58it/s]

Processing tickers:  92%|█████████▏| 6326/6855 [22:38<01:53,  4.66it/s]

Processing tickers:  92%|█████████▏| 6327/6855 [22:38<01:54,  4.62it/s]

Processing tickers:  92%|█████████▏| 6328/6855 [22:38<01:54,  4.60it/s]

Processing tickers:  92%|█████████▏| 6329/6855 [22:39<01:56,  4.53it/s]

Processing tickers:  92%|█████████▏| 6330/6855 [22:39<01:58,  4.45it/s]

Processing tickers:  92%|█████████▏| 6331/6855 [22:39<01:56,  4.52it/s]

Processing tickers:  92%|█████████▏| 6332/6855 [22:39<01:54,  4.56it/s]

Processing tickers:  92%|█████████▏| 6333/6855 [22:39<01:54,  4.56it/s]

Processing tickers:  92%|█████████▏| 6334/6855 [22:40<01:53,  4.58it/s]

Processing tickers:  92%|█████████▏| 6335/6855 [22:40<01:52,  4.63it/s]

Processing tickers:  92%|█████████▏| 6336/6855 [22:40<01:53,  4.59it/s]

Processing tickers:  92%|█████████▏| 6337/6855 [22:40<01:51,  4.66it/s]

Processing tickers:  92%|█████████▏| 6338/6855 [22:40<01:50,  4.69it/s]

Processing tickers:  92%|█████████▏| 6339/6855 [22:41<01:49,  4.72it/s]

Processing tickers:  92%|█████████▏| 6340/6855 [22:41<01:47,  4.77it/s]

Processing tickers:  93%|█████████▎| 6341/6855 [22:41<01:48,  4.76it/s]

Processing tickers:  93%|█████████▎| 6342/6855 [22:41<01:49,  4.69it/s]

Processing tickers:  93%|█████████▎| 6343/6855 [22:42<01:48,  4.71it/s]

Processing tickers:  93%|█████████▎| 6344/6855 [22:42<01:47,  4.75it/s]

Processing tickers:  93%|█████████▎| 6345/6855 [22:42<01:49,  4.65it/s]

Processing tickers:  93%|█████████▎| 6346/6855 [22:42<01:51,  4.57it/s]

Processing tickers:  93%|█████████▎| 6347/6855 [22:42<01:49,  4.64it/s]

Processing tickers:  93%|█████████▎| 6348/6855 [22:43<01:48,  4.66it/s]

Processing tickers:  93%|█████████▎| 6349/6855 [22:43<01:48,  4.67it/s]

Processing tickers:  93%|█████████▎| 6350/6855 [22:43<01:47,  4.68it/s]

Processing tickers:  93%|█████████▎| 6351/6855 [22:43<01:49,  4.60it/s]

Processing tickers:  93%|█████████▎| 6352/6855 [22:43<01:51,  4.52it/s]

Processing tickers:  93%|█████████▎| 6353/6855 [22:44<01:52,  4.46it/s]

Processing tickers:  93%|█████████▎| 6354/6855 [22:44<01:54,  4.37it/s]

Processing tickers:  93%|█████████▎| 6355/6855 [22:44<01:54,  4.37it/s]

Processing tickers:  93%|█████████▎| 6356/6855 [22:44<01:52,  4.43it/s]

Processing tickers:  93%|█████████▎| 6357/6855 [22:45<01:53,  4.38it/s]

Processing tickers:  93%|█████████▎| 6358/6855 [22:45<01:51,  4.48it/s]

Processing tickers:  93%|█████████▎| 6359/6855 [22:45<01:48,  4.59it/s]

Processing tickers:  93%|█████████▎| 6360/6855 [22:45<01:46,  4.64it/s]

Processing tickers:  93%|█████████▎| 6361/6855 [22:45<01:44,  4.71it/s]

Processing tickers:  93%|█████████▎| 6362/6855 [22:46<01:44,  4.74it/s]

Processing tickers:  93%|█████████▎| 6363/6855 [22:46<01:44,  4.72it/s]

Processing tickers:  93%|█████████▎| 6364/6855 [22:46<01:42,  4.77it/s]

Processing tickers:  93%|█████████▎| 6365/6855 [22:46<01:42,  4.78it/s]

Processing tickers:  93%|█████████▎| 6366/6855 [22:47<01:42,  4.76it/s]

Processing tickers:  93%|█████████▎| 6367/6855 [22:47<01:41,  4.79it/s]

Processing tickers:  93%|█████████▎| 6368/6855 [22:47<01:40,  4.84it/s]

Processing tickers:  93%|█████████▎| 6369/6855 [22:47<01:41,  4.81it/s]

Processing tickers:  93%|█████████▎| 6370/6855 [22:47<01:41,  4.79it/s]

Processing tickers:  93%|█████████▎| 6371/6855 [22:48<01:41,  4.79it/s]

Processing tickers:  93%|█████████▎| 6372/6855 [22:48<01:40,  4.80it/s]

Processing tickers:  93%|█████████▎| 6373/6855 [22:48<01:40,  4.81it/s]

Processing tickers:  93%|█████████▎| 6374/6855 [22:48<01:41,  4.74it/s]

Processing tickers:  93%|█████████▎| 6375/6855 [22:48<01:45,  4.54it/s]

Processing tickers:  93%|█████████▎| 6376/6855 [22:49<01:44,  4.60it/s]

Processing tickers:  93%|█████████▎| 6377/6855 [22:49<01:42,  4.67it/s]

Processing tickers:  93%|█████████▎| 6378/6855 [22:49<01:45,  4.54it/s]

Processing tickers:  93%|█████████▎| 6379/6855 [22:49<01:45,  4.52it/s]

Processing tickers:  93%|█████████▎| 6380/6855 [22:50<01:46,  4.48it/s]

Processing tickers:  93%|█████████▎| 6381/6855 [22:50<01:45,  4.51it/s]

Processing tickers:  93%|█████████▎| 6382/6855 [22:50<01:45,  4.49it/s]

Processing tickers:  93%|█████████▎| 6383/6855 [22:50<01:43,  4.55it/s]

Processing tickers:  93%|█████████▎| 6384/6855 [22:50<01:42,  4.59it/s]

Processing tickers:  93%|█████████▎| 6385/6855 [22:51<01:42,  4.60it/s]

Processing tickers:  93%|█████████▎| 6386/6855 [22:51<01:40,  4.66it/s]

Processing tickers:  93%|█████████▎| 6387/6855 [22:51<01:39,  4.71it/s]

Processing tickers:  93%|█████████▎| 6388/6855 [22:51<01:38,  4.73it/s]

Processing tickers:  93%|█████████▎| 6389/6855 [22:51<01:37,  4.77it/s]

Processing tickers:  93%|█████████▎| 6390/6855 [22:52<01:38,  4.74it/s]

Processing tickers:  93%|█████████▎| 6391/6855 [22:52<01:37,  4.75it/s]

Processing tickers:  93%|█████████▎| 6392/6855 [22:52<01:36,  4.77it/s]

Processing tickers:  93%|█████████▎| 6393/6855 [22:52<01:37,  4.75it/s]

Processing tickers:  93%|█████████▎| 6394/6855 [22:53<01:39,  4.62it/s]

Processing tickers:  93%|█████████▎| 6395/6855 [22:53<01:39,  4.61it/s]

Processing tickers:  93%|█████████▎| 6396/6855 [22:53<01:38,  4.66it/s]

Processing tickers:  93%|█████████▎| 6397/6855 [22:53<01:39,  4.61it/s]

Processing tickers:  93%|█████████▎| 6398/6855 [22:53<01:38,  4.64it/s]

Processing tickers:  93%|█████████▎| 6399/6855 [22:54<01:38,  4.65it/s]

Processing tickers:  93%|█████████▎| 6400/6855 [22:54<01:38,  4.64it/s]

Processing tickers:  93%|█████████▎| 6401/6855 [22:54<01:36,  4.68it/s]

Processing tickers:  93%|█████████▎| 6402/6855 [22:54<01:35,  4.72it/s]

Processing tickers:  93%|█████████▎| 6403/6855 [22:54<01:34,  4.76it/s]

Processing tickers:  93%|█████████▎| 6404/6855 [22:55<01:34,  4.77it/s]

Processing tickers:  93%|█████████▎| 6405/6855 [22:55<01:34,  4.76it/s]

Processing tickers:  93%|█████████▎| 6406/6855 [22:55<01:34,  4.76it/s]

Processing tickers:  93%|█████████▎| 6407/6855 [22:55<01:35,  4.71it/s]

Processing tickers:  93%|█████████▎| 6408/6855 [22:55<01:34,  4.72it/s]

Processing tickers:  93%|█████████▎| 6409/6855 [22:56<01:33,  4.75it/s]

Processing tickers:  94%|█████████▎| 6410/6855 [22:56<01:33,  4.74it/s]

Processing tickers:  94%|█████████▎| 6411/6855 [22:56<01:36,  4.62it/s]

Processing tickers:  94%|█████████▎| 6412/6855 [22:56<01:34,  4.68it/s]

Processing tickers:  94%|█████████▎| 6413/6855 [22:57<01:33,  4.72it/s]

Processing tickers:  94%|█████████▎| 6414/6855 [22:57<01:35,  4.60it/s]

Processing tickers:  94%|█████████▎| 6415/6855 [22:57<01:34,  4.64it/s]

Processing tickers:  94%|█████████▎| 6416/6855 [22:57<01:36,  4.56it/s]

Processing tickers:  94%|█████████▎| 6417/6855 [22:57<01:35,  4.57it/s]

Processing tickers:  94%|█████████▎| 6418/6855 [22:58<01:33,  4.67it/s]

Processing tickers:  94%|█████████▎| 6419/6855 [22:58<01:32,  4.71it/s]

Processing tickers:  94%|█████████▎| 6420/6855 [22:58<01:32,  4.68it/s]

Processing tickers:  94%|█████████▎| 6421/6855 [22:58<01:31,  4.75it/s]

Processing tickers:  94%|█████████▎| 6422/6855 [22:58<01:31,  4.74it/s]

Processing tickers:  94%|█████████▎| 6423/6855 [22:59<01:31,  4.74it/s]

Processing tickers:  94%|█████████▎| 6424/6855 [22:59<01:30,  4.76it/s]

Processing tickers:  94%|█████████▎| 6425/6855 [22:59<01:30,  4.74it/s]

Processing tickers:  94%|█████████▎| 6426/6855 [22:59<01:30,  4.75it/s]

Processing tickers:  94%|█████████▍| 6427/6855 [23:00<01:29,  4.76it/s]

Processing tickers:  94%|█████████▍| 6428/6855 [23:00<01:30,  4.74it/s]

Processing tickers:  94%|█████████▍| 6429/6855 [23:00<01:31,  4.64it/s]

Processing tickers:  94%|█████████▍| 6430/6855 [23:00<01:31,  4.64it/s]

Processing tickers:  94%|█████████▍| 6431/6855 [23:00<01:30,  4.69it/s]

Processing tickers:  94%|█████████▍| 6432/6855 [23:01<01:33,  4.53it/s]

Processing tickers:  94%|█████████▍| 6433/6855 [23:01<01:32,  4.57it/s]

Processing tickers:  94%|█████████▍| 6434/6855 [23:01<01:30,  4.66it/s]

Processing tickers:  94%|█████████▍| 6435/6855 [23:01<01:29,  4.71it/s]

Processing tickers:  94%|█████████▍| 6436/6855 [23:01<01:29,  4.70it/s]

Processing tickers:  94%|█████████▍| 6437/6855 [23:02<01:30,  4.61it/s]

Processing tickers:  94%|█████████▍| 6438/6855 [23:02<01:29,  4.65it/s]

Processing tickers:  94%|█████████▍| 6439/6855 [23:02<01:29,  4.65it/s]

Processing tickers:  94%|█████████▍| 6440/6855 [23:02<01:28,  4.67it/s]

Processing tickers:  94%|█████████▍| 6441/6855 [23:03<01:28,  4.70it/s]

Processing tickers:  94%|█████████▍| 6442/6855 [23:03<01:27,  4.73it/s]

Processing tickers:  94%|█████████▍| 6443/6855 [23:03<01:26,  4.76it/s]

Processing tickers:  94%|█████████▍| 6444/6855 [23:03<01:27,  4.68it/s]

Processing tickers:  94%|█████████▍| 6445/6855 [23:03<01:28,  4.62it/s]

Processing tickers:  94%|█████████▍| 6446/6855 [23:04<01:26,  4.70it/s]

Processing tickers:  94%|█████████▍| 6447/6855 [23:04<01:25,  4.75it/s]

Processing tickers:  94%|█████████▍| 6448/6855 [23:04<01:25,  4.77it/s]

Processing tickers:  94%|█████████▍| 6449/6855 [23:04<01:28,  4.60it/s]

Processing tickers:  94%|█████████▍| 6450/6855 [23:04<01:27,  4.64it/s]

Processing tickers:  94%|█████████▍| 6451/6855 [23:05<01:26,  4.65it/s]

Processing tickers:  94%|█████████▍| 6452/6855 [23:05<01:25,  4.70it/s]

Processing tickers:  94%|█████████▍| 6453/6855 [23:05<01:25,  4.73it/s]

Processing tickers:  94%|█████████▍| 6454/6855 [23:05<01:24,  4.74it/s]

Processing tickers:  94%|█████████▍| 6455/6855 [23:06<01:23,  4.77it/s]

Processing tickers:  94%|█████████▍| 6456/6855 [23:06<01:25,  4.67it/s]

Processing tickers:  94%|█████████▍| 6457/6855 [23:06<01:24,  4.69it/s]

Processing tickers:  94%|█████████▍| 6458/6855 [23:06<01:25,  4.67it/s]

Processing tickers:  94%|█████████▍| 6459/6855 [23:06<01:25,  4.62it/s]

Processing tickers:  94%|█████████▍| 6460/6855 [23:07<01:24,  4.69it/s]

Processing tickers:  94%|█████████▍| 6461/6855 [23:07<01:23,  4.71it/s]

Processing tickers:  94%|█████████▍| 6462/6855 [23:07<01:22,  4.74it/s]

Processing tickers:  94%|█████████▍| 6463/6855 [23:07<01:23,  4.70it/s]

Processing tickers:  94%|█████████▍| 6464/6855 [23:07<01:24,  4.62it/s]

Processing tickers:  94%|█████████▍| 6465/6855 [23:08<01:23,  4.69it/s]

Processing tickers:  94%|█████████▍| 6466/6855 [23:08<01:23,  4.67it/s]

Processing tickers:  94%|█████████▍| 6467/6855 [23:08<01:22,  4.70it/s]

Processing tickers:  94%|█████████▍| 6468/6855 [23:08<01:22,  4.68it/s]

Processing tickers:  94%|█████████▍| 6469/6855 [23:09<01:21,  4.75it/s]

Processing tickers:  94%|█████████▍| 6470/6855 [23:09<01:21,  4.71it/s]

Processing tickers:  94%|█████████▍| 6471/6855 [23:09<01:23,  4.60it/s]

Processing tickers:  94%|█████████▍| 6472/6855 [23:09<01:24,  4.54it/s]

Processing tickers:  94%|█████████▍| 6473/6855 [23:09<01:25,  4.48it/s]

Processing tickers:  94%|█████████▍| 6474/6855 [23:10<01:23,  4.58it/s]

Processing tickers:  94%|█████████▍| 6475/6855 [23:10<01:23,  4.56it/s]

Processing tickers:  94%|█████████▍| 6476/6855 [23:10<01:22,  4.58it/s]

Processing tickers:  94%|█████████▍| 6477/6855 [23:10<01:24,  4.45it/s]

Processing tickers:  95%|█████████▍| 6478/6855 [23:11<01:23,  4.53it/s]

Processing tickers:  95%|█████████▍| 6479/6855 [23:11<01:21,  4.60it/s]

Processing tickers:  95%|█████████▍| 6480/6855 [23:11<01:22,  4.52it/s]

Processing tickers:  95%|█████████▍| 6481/6855 [23:11<01:21,  4.58it/s]

Processing tickers:  95%|█████████▍| 6482/6855 [23:11<01:20,  4.63it/s]

Processing tickers:  95%|█████████▍| 6483/6855 [23:12<01:20,  4.62it/s]

Processing tickers:  95%|█████████▍| 6484/6855 [23:12<01:19,  4.65it/s]

Processing tickers:  95%|█████████▍| 6485/6855 [23:12<01:19,  4.68it/s]

Processing tickers:  95%|█████████▍| 6486/6855 [23:12<01:18,  4.69it/s]

Processing tickers:  95%|█████████▍| 6487/6855 [23:12<01:17,  4.73it/s]

Processing tickers:  95%|█████████▍| 6488/6855 [23:13<01:16,  4.77it/s]

Processing tickers:  95%|█████████▍| 6489/6855 [23:13<01:16,  4.80it/s]

Processing tickers:  95%|█████████▍| 6490/6855 [23:13<01:17,  4.72it/s]

Processing tickers:  95%|█████████▍| 6491/6855 [23:13<01:16,  4.76it/s]

Processing tickers:  95%|█████████▍| 6492/6855 [23:13<01:16,  4.73it/s]

Processing tickers:  95%|█████████▍| 6493/6855 [23:14<01:16,  4.71it/s]

Processing tickers:  95%|█████████▍| 6494/6855 [23:14<01:16,  4.74it/s]

Processing tickers:  95%|█████████▍| 6495/6855 [23:14<01:15,  4.75it/s]

Processing tickers:  95%|█████████▍| 6496/6855 [23:14<01:17,  4.61it/s]

Processing tickers:  95%|█████████▍| 6497/6855 [23:15<01:16,  4.67it/s]

Processing tickers:  95%|█████████▍| 6498/6855 [23:15<01:16,  4.67it/s]

Processing tickers:  95%|█████████▍| 6499/6855 [23:15<01:15,  4.71it/s]

Processing tickers:  95%|█████████▍| 6500/6855 [23:15<01:15,  4.69it/s]

Processing tickers:  95%|█████████▍| 6501/6855 [23:15<01:15,  4.71it/s]

Processing tickers:  95%|█████████▍| 6502/6855 [23:16<01:14,  4.73it/s]

Processing tickers:  95%|█████████▍| 6503/6855 [23:16<01:14,  4.72it/s]

Processing tickers:  95%|█████████▍| 6504/6855 [23:16<01:13,  4.75it/s]

Processing tickers:  95%|█████████▍| 6505/6855 [23:16<01:14,  4.70it/s]

Processing tickers:  95%|█████████▍| 6506/6855 [23:16<01:13,  4.73it/s]

Processing tickers:  95%|█████████▍| 6507/6855 [23:17<01:13,  4.72it/s]

Processing tickers:  95%|█████████▍| 6508/6855 [23:17<01:12,  4.76it/s]

Processing tickers:  95%|█████████▍| 6509/6855 [23:17<01:12,  4.77it/s]

Processing tickers:  95%|█████████▍| 6510/6855 [23:17<01:12,  4.79it/s]

Processing tickers:  95%|█████████▍| 6511/6855 [23:18<01:11,  4.79it/s]

Processing tickers:  95%|█████████▍| 6512/6855 [23:18<01:11,  4.78it/s]

Processing tickers:  95%|█████████▌| 6513/6855 [23:18<01:11,  4.79it/s]

Processing tickers:  95%|█████████▌| 6514/6855 [23:18<01:11,  4.78it/s]

Processing tickers:  95%|█████████▌| 6515/6855 [23:18<01:10,  4.81it/s]

Processing tickers:  95%|█████████▌| 6516/6855 [23:19<01:10,  4.79it/s]

Processing tickers:  95%|█████████▌| 6517/6855 [23:19<01:10,  4.79it/s]

Processing tickers:  95%|█████████▌| 6518/6855 [23:19<01:09,  4.83it/s]

Processing tickers:  95%|█████████▌| 6519/6855 [23:19<01:12,  4.65it/s]

Processing tickers:  95%|█████████▌| 6520/6855 [23:19<01:11,  4.70it/s]

Processing tickers:  95%|█████████▌| 6521/6855 [23:20<01:12,  4.58it/s]

Processing tickers:  95%|█████████▌| 6522/6855 [23:20<01:12,  4.58it/s]

Processing tickers:  95%|█████████▌| 6523/6855 [23:20<01:12,  4.57it/s]

Processing tickers:  95%|█████████▌| 6524/6855 [23:20<01:11,  4.63it/s]

Processing tickers:  95%|█████████▌| 6525/6855 [23:20<01:11,  4.65it/s]

Processing tickers:  95%|█████████▌| 6526/6855 [23:21<01:10,  4.67it/s]

Processing tickers:  95%|█████████▌| 6527/6855 [23:21<01:09,  4.70it/s]

Processing tickers:  95%|█████████▌| 6528/6855 [23:21<01:09,  4.74it/s]

Processing tickers:  95%|█████████▌| 6529/6855 [23:21<01:10,  4.61it/s]

Processing tickers:  95%|█████████▌| 6530/6855 [23:22<01:09,  4.67it/s]

Processing tickers:  95%|█████████▌| 6531/6855 [23:22<01:09,  4.69it/s]

Processing tickers:  95%|█████████▌| 6532/6855 [23:22<01:08,  4.70it/s]

Processing tickers:  95%|█████████▌| 6533/6855 [23:22<01:09,  4.60it/s]

Processing tickers:  95%|█████████▌| 6534/6855 [23:22<01:09,  4.64it/s]

Processing tickers:  95%|█████████▌| 6535/6855 [23:23<01:08,  4.68it/s]

Processing tickers:  95%|█████████▌| 6536/6855 [23:23<01:08,  4.68it/s]

Processing tickers:  95%|█████████▌| 6537/6855 [23:23<01:07,  4.69it/s]

Processing tickers:  95%|█████████▌| 6538/6855 [23:23<01:07,  4.72it/s]

Processing tickers:  95%|█████████▌| 6539/6855 [23:23<01:08,  4.60it/s]

Processing tickers:  95%|█████████▌| 6540/6855 [23:24<01:08,  4.63it/s]

Processing tickers:  95%|█████████▌| 6541/6855 [23:24<01:09,  4.54it/s]

Processing tickers:  95%|█████████▌| 6542/6855 [23:24<01:11,  4.39it/s]

Processing tickers:  95%|█████████▌| 6543/6855 [23:24<01:10,  4.41it/s]

Processing tickers:  95%|█████████▌| 6544/6855 [23:25<01:08,  4.54it/s]

Processing tickers:  95%|█████████▌| 6545/6855 [23:25<01:09,  4.44it/s]

Processing tickers:  95%|█████████▌| 6546/6855 [23:25<01:08,  4.53it/s]

Processing tickers:  96%|█████████▌| 6547/6855 [23:25<01:06,  4.60it/s]

Processing tickers:  96%|█████████▌| 6548/6855 [23:25<01:05,  4.67it/s]

Processing tickers:  96%|█████████▌| 6549/6855 [23:26<01:06,  4.62it/s]

Processing tickers:  96%|█████████▌| 6550/6855 [23:26<01:07,  4.54it/s]

Processing tickers:  96%|█████████▌| 6551/6855 [23:26<01:05,  4.61it/s]

Processing tickers:  96%|█████████▌| 6552/6855 [23:26<01:05,  4.66it/s]

Processing tickers:  96%|█████████▌| 6553/6855 [23:27<01:04,  4.67it/s]

Processing tickers:  96%|█████████▌| 6554/6855 [23:27<01:04,  4.64it/s]

Processing tickers:  96%|█████████▌| 6555/6855 [23:27<01:04,  4.66it/s]

Processing tickers:  96%|█████████▌| 6556/6855 [23:27<01:05,  4.59it/s]

Processing tickers:  96%|█████████▌| 6557/6855 [23:27<01:04,  4.59it/s]

Processing tickers:  96%|█████████▌| 6558/6855 [23:28<01:04,  4.62it/s]

Processing tickers:  96%|█████████▌| 6559/6855 [23:28<01:03,  4.66it/s]

Processing tickers:  96%|█████████▌| 6560/6855 [23:28<01:03,  4.68it/s]

Processing tickers:  96%|█████████▌| 6561/6855 [23:28<01:05,  4.46it/s]

Processing tickers:  96%|█████████▌| 6562/6855 [23:29<01:03,  4.61it/s]

Processing tickers:  96%|█████████▌| 6563/6855 [23:29<01:02,  4.67it/s]

Processing tickers:  96%|█████████▌| 6564/6855 [23:29<01:01,  4.71it/s]

Processing tickers:  96%|█████████▌| 6565/6855 [23:29<01:02,  4.65it/s]

Processing tickers:  96%|█████████▌| 6566/6855 [23:29<01:01,  4.69it/s]

Processing tickers:  96%|█████████▌| 6567/6855 [23:30<01:02,  4.60it/s]

Processing tickers:  96%|█████████▌| 6568/6855 [23:30<01:03,  4.53it/s]

Processing tickers:  96%|█████████▌| 6569/6855 [23:30<01:04,  4.44it/s]

Processing tickers:  96%|█████████▌| 6570/6855 [23:30<01:04,  4.42it/s]

Processing tickers:  96%|█████████▌| 6571/6855 [23:30<01:03,  4.49it/s]

Processing tickers:  96%|█████████▌| 6572/6855 [23:31<01:03,  4.44it/s]

Processing tickers:  96%|█████████▌| 6573/6855 [23:31<01:02,  4.53it/s]

Processing tickers:  96%|█████████▌| 6574/6855 [23:31<01:00,  4.62it/s]

Processing tickers:  96%|█████████▌| 6575/6855 [23:31<00:59,  4.72it/s]

Processing tickers:  96%|█████████▌| 6576/6855 [23:32<00:59,  4.66it/s]

Processing tickers:  96%|█████████▌| 6577/6855 [23:32<00:59,  4.67it/s]

Processing tickers:  96%|█████████▌| 6578/6855 [23:32<00:59,  4.69it/s]

Processing tickers:  96%|█████████▌| 6579/6855 [23:32<00:58,  4.70it/s]

Processing tickers:  96%|█████████▌| 6580/6855 [23:32<00:57,  4.76it/s]

Processing tickers:  96%|█████████▌| 6581/6855 [23:33<00:58,  4.71it/s]

Processing tickers:  96%|█████████▌| 6582/6855 [23:33<00:58,  4.67it/s]

Processing tickers:  96%|█████████▌| 6583/6855 [23:33<00:57,  4.69it/s]

Processing tickers:  96%|█████████▌| 6584/6855 [23:33<00:58,  4.60it/s]

Processing tickers:  96%|█████████▌| 6585/6855 [23:33<00:58,  4.63it/s]

Processing tickers:  96%|█████████▌| 6586/6855 [23:34<00:57,  4.66it/s]

Processing tickers:  96%|█████████▌| 6587/6855 [23:34<00:57,  4.67it/s]

Processing tickers:  96%|█████████▌| 6588/6855 [23:34<00:57,  4.67it/s]

Processing tickers:  96%|█████████▌| 6589/6855 [23:34<00:57,  4.66it/s]

Processing tickers:  96%|█████████▌| 6590/6855 [23:35<00:57,  4.64it/s]

Processing tickers:  96%|█████████▌| 6591/6855 [23:35<00:56,  4.69it/s]

Processing tickers:  96%|█████████▌| 6592/6855 [23:35<00:56,  4.68it/s]

Processing tickers:  96%|█████████▌| 6593/6855 [23:35<00:56,  4.66it/s]

Processing tickers:  96%|█████████▌| 6594/6855 [23:35<00:55,  4.70it/s]

Processing tickers:  96%|█████████▌| 6595/6855 [23:36<00:55,  4.65it/s]

Processing tickers:  96%|█████████▌| 6596/6855 [23:36<00:55,  4.70it/s]

Processing tickers:  96%|█████████▌| 6597/6855 [23:36<00:55,  4.64it/s]

Processing tickers:  96%|█████████▋| 6598/6855 [23:36<00:55,  4.60it/s]

Processing tickers:  96%|█████████▋| 6599/6855 [23:37<00:56,  4.49it/s]

Processing tickers:  96%|█████████▋| 6600/6855 [23:37<00:57,  4.42it/s]

Processing tickers:  96%|█████████▋| 6601/6855 [23:37<00:57,  4.44it/s]

Processing tickers:  96%|█████████▋| 6602/6855 [23:37<00:56,  4.47it/s]

Processing tickers:  96%|█████████▋| 6603/6855 [23:37<00:55,  4.55it/s]

Processing tickers:  96%|█████████▋| 6604/6855 [23:38<00:54,  4.57it/s]

Processing tickers:  96%|█████████▋| 6605/6855 [23:38<00:54,  4.59it/s]

Processing tickers:  96%|█████████▋| 6606/6855 [23:38<00:53,  4.64it/s]

Processing tickers:  96%|█████████▋| 6607/6855 [23:38<00:53,  4.67it/s]

Processing tickers:  96%|█████████▋| 6608/6855 [23:38<00:52,  4.73it/s]

Processing tickers:  96%|█████████▋| 6609/6855 [23:39<00:51,  4.73it/s]

Processing tickers:  96%|█████████▋| 6610/6855 [23:39<00:51,  4.76it/s]

Processing tickers:  96%|█████████▋| 6611/6855 [23:39<00:52,  4.65it/s]

Processing tickers:  96%|█████████▋| 6612/6855 [23:39<00:53,  4.55it/s]

Processing tickers:  96%|█████████▋| 6613/6855 [23:40<00:52,  4.63it/s]

Processing tickers:  96%|█████████▋| 6614/6855 [23:40<00:53,  4.51it/s]

Processing tickers:  96%|█████████▋| 6615/6855 [23:40<00:53,  4.46it/s]

Processing tickers:  97%|█████████▋| 6616/6855 [23:40<00:53,  4.50it/s]

Processing tickers:  97%|█████████▋| 6617/6855 [23:40<00:53,  4.47it/s]

Processing tickers:  97%|█████████▋| 6618/6855 [23:41<00:53,  4.41it/s]

Processing tickers:  97%|█████████▋| 6619/6855 [23:41<00:52,  4.54it/s]

Processing tickers:  97%|█████████▋| 6620/6855 [23:41<00:51,  4.59it/s]

Processing tickers:  97%|█████████▋| 6621/6855 [23:41<00:50,  4.60it/s]

Processing tickers:  97%|█████████▋| 6622/6855 [23:42<00:51,  4.53it/s]

Processing tickers:  97%|█████████▋| 6623/6855 [23:42<00:50,  4.57it/s]

Processing tickers:  97%|█████████▋| 6624/6855 [23:42<00:51,  4.50it/s]

Processing tickers:  97%|█████████▋| 6625/6855 [23:42<00:51,  4.45it/s]

Processing tickers:  97%|█████████▋| 6626/6855 [23:42<00:50,  4.55it/s]

Processing tickers:  97%|█████████▋| 6627/6855 [23:43<00:49,  4.63it/s]

Processing tickers:  97%|█████████▋| 6628/6855 [23:43<00:48,  4.63it/s]

Processing tickers:  97%|█████████▋| 6629/6855 [23:43<00:48,  4.63it/s]

Processing tickers:  97%|█████████▋| 6630/6855 [23:43<00:48,  4.64it/s]

Processing tickers:  97%|█████████▋| 6631/6855 [23:44<00:48,  4.58it/s]

Processing tickers:  97%|█████████▋| 6632/6855 [23:44<00:48,  4.64it/s]

Processing tickers:  97%|█████████▋| 6633/6855 [23:44<00:48,  4.55it/s]

Processing tickers:  97%|█████████▋| 6634/6855 [23:44<00:49,  4.44it/s]

Processing tickers:  97%|█████████▋| 6635/6855 [23:44<00:48,  4.55it/s]

Processing tickers:  97%|█████████▋| 6636/6855 [23:45<00:47,  4.62it/s]

Processing tickers:  97%|█████████▋| 6637/6855 [23:45<00:48,  4.53it/s]

Processing tickers:  97%|█████████▋| 6638/6855 [23:45<00:48,  4.50it/s]

Processing tickers:  97%|█████████▋| 6639/6855 [23:45<00:46,  4.61it/s]

Processing tickers:  97%|█████████▋| 6640/6855 [23:45<00:46,  4.66it/s]

Processing tickers:  97%|█████████▋| 6641/6855 [23:46<00:46,  4.58it/s]

Processing tickers:  97%|█████████▋| 6642/6855 [23:46<00:45,  4.64it/s]

Processing tickers:  97%|█████████▋| 6643/6855 [23:46<00:46,  4.61it/s]

Processing tickers:  97%|█████████▋| 6644/6855 [23:46<00:45,  4.67it/s]

Processing tickers:  97%|█████████▋| 6645/6855 [23:47<00:44,  4.71it/s]

Processing tickers:  97%|█████████▋| 6646/6855 [23:47<00:44,  4.72it/s]

Processing tickers:  97%|█████████▋| 6647/6855 [23:47<00:43,  4.75it/s]

Processing tickers:  97%|█████████▋| 6648/6855 [23:47<00:43,  4.72it/s]

Processing tickers:  97%|█████████▋| 6649/6855 [23:47<00:44,  4.62it/s]

Processing tickers:  97%|█████████▋| 6650/6855 [23:48<00:45,  4.51it/s]

Processing tickers:  97%|█████████▋| 6651/6855 [23:48<00:44,  4.58it/s]

Processing tickers:  97%|█████████▋| 6652/6855 [23:48<00:43,  4.66it/s]

Processing tickers:  97%|█████████▋| 6653/6855 [23:48<00:44,  4.53it/s]

Processing tickers:  97%|█████████▋| 6654/6855 [23:49<00:43,  4.59it/s]

Processing tickers:  97%|█████████▋| 6655/6855 [23:49<00:43,  4.61it/s]

Processing tickers:  97%|█████████▋| 6656/6855 [23:49<00:43,  4.60it/s]

Processing tickers:  97%|█████████▋| 6657/6855 [23:49<00:42,  4.68it/s]

Processing tickers:  97%|█████████▋| 6658/6855 [23:49<00:43,  4.55it/s]

Processing tickers:  97%|█████████▋| 6659/6855 [23:50<00:43,  4.49it/s]

Processing tickers:  97%|█████████▋| 6660/6855 [23:50<00:42,  4.55it/s]

Processing tickers:  97%|█████████▋| 6661/6855 [23:50<00:42,  4.57it/s]

Processing tickers:  97%|█████████▋| 6662/6855 [23:50<00:41,  4.60it/s]

Processing tickers:  97%|█████████▋| 6663/6855 [23:50<00:41,  4.67it/s]

Processing tickers:  97%|█████████▋| 6664/6855 [23:51<00:40,  4.66it/s]

Processing tickers:  97%|█████████▋| 6665/6855 [23:51<00:40,  4.69it/s]

Processing tickers:  97%|█████████▋| 6666/6855 [23:51<00:39,  4.75it/s]

Processing tickers:  97%|█████████▋| 6667/6855 [23:51<00:39,  4.76it/s]

Processing tickers:  97%|█████████▋| 6668/6855 [23:52<00:39,  4.72it/s]

Processing tickers:  97%|█████████▋| 6669/6855 [23:52<00:40,  4.65it/s]

Processing tickers:  97%|█████████▋| 6670/6855 [23:52<00:39,  4.70it/s]

Processing tickers:  97%|█████████▋| 6671/6855 [23:52<00:39,  4.70it/s]

Processing tickers:  97%|█████████▋| 6672/6855 [23:52<00:39,  4.68it/s]

Processing tickers:  97%|█████████▋| 6673/6855 [23:53<00:38,  4.70it/s]

Processing tickers:  97%|█████████▋| 6674/6855 [23:53<00:38,  4.75it/s]

Processing tickers:  97%|█████████▋| 6675/6855 [23:53<00:37,  4.79it/s]

Processing tickers:  97%|█████████▋| 6676/6855 [23:53<00:38,  4.67it/s]

Processing tickers:  97%|█████████▋| 6677/6855 [23:53<00:38,  4.61it/s]

Processing tickers:  97%|█████████▋| 6678/6855 [23:54<00:38,  4.66it/s]

Processing tickers:  97%|█████████▋| 6679/6855 [23:54<00:37,  4.65it/s]

Processing tickers:  97%|█████████▋| 6680/6855 [23:54<00:38,  4.60it/s]

Processing tickers:  97%|█████████▋| 6681/6855 [23:54<00:37,  4.65it/s]

Processing tickers:  97%|█████████▋| 6682/6855 [23:55<00:36,  4.68it/s]

Processing tickers:  97%|█████████▋| 6683/6855 [23:55<00:36,  4.72it/s]

Processing tickers:  98%|█████████▊| 6684/6855 [23:55<00:36,  4.66it/s]

Processing tickers:  98%|█████████▊| 6685/6855 [23:55<00:36,  4.67it/s]

Processing tickers:  98%|█████████▊| 6686/6855 [23:55<00:37,  4.46it/s]

Processing tickers:  98%|█████████▊| 6687/6855 [23:56<00:37,  4.50it/s]

Processing tickers:  98%|█████████▊| 6688/6855 [23:56<00:36,  4.57it/s]

Processing tickers:  98%|█████████▊| 6689/6855 [23:56<00:36,  4.61it/s]

Processing tickers:  98%|█████████▊| 6690/6855 [23:56<00:35,  4.65it/s]

Processing tickers:  98%|█████████▊| 6691/6855 [23:56<00:35,  4.64it/s]

Processing tickers:  98%|█████████▊| 6692/6855 [23:57<00:35,  4.65it/s]

Processing tickers:  98%|█████████▊| 6693/6855 [23:57<00:34,  4.72it/s]

Processing tickers:  98%|█████████▊| 6694/6855 [23:57<00:33,  4.75it/s]

Processing tickers:  98%|█████████▊| 6695/6855 [23:57<00:37,  4.24it/s]

Processing tickers:  98%|█████████▊| 6696/6855 [23:58<00:36,  4.35it/s]

Processing tickers:  98%|█████████▊| 6697/6855 [23:58<00:35,  4.46it/s]

Processing tickers:  98%|█████████▊| 6698/6855 [23:58<00:35,  4.40it/s]

Processing tickers:  98%|█████████▊| 6699/6855 [23:58<00:34,  4.47it/s]

Processing tickers:  98%|█████████▊| 6700/6855 [23:59<00:35,  4.40it/s]

Processing tickers:  98%|█████████▊| 6701/6855 [23:59<00:34,  4.51it/s]

Processing tickers:  98%|█████████▊| 6702/6855 [23:59<00:33,  4.61it/s]

Processing tickers:  98%|█████████▊| 6703/6855 [23:59<00:32,  4.66it/s]

Processing tickers:  98%|█████████▊| 6704/6855 [23:59<00:32,  4.65it/s]

Processing tickers:  98%|█████████▊| 6705/6855 [24:00<00:31,  4.71it/s]

Processing tickers:  98%|█████████▊| 6706/6855 [24:00<00:32,  4.63it/s]

Processing tickers:  98%|█████████▊| 6707/6855 [24:00<00:31,  4.68it/s]

Processing tickers:  98%|█████████▊| 6708/6855 [24:00<00:31,  4.67it/s]

Processing tickers:  98%|█████████▊| 6709/6855 [24:00<00:31,  4.58it/s]

Processing tickers:  98%|█████████▊| 6710/6855 [24:01<00:31,  4.66it/s]

Processing tickers:  98%|█████████▊| 6711/6855 [24:01<00:31,  4.64it/s]

Processing tickers:  98%|█████████▊| 6712/6855 [24:01<00:30,  4.71it/s]

Processing tickers:  98%|█████████▊| 6713/6855 [24:01<00:30,  4.62it/s]

Processing tickers:  98%|█████████▊| 6714/6855 [24:02<00:31,  4.53it/s]

Processing tickers:  98%|█████████▊| 6715/6855 [24:02<00:30,  4.61it/s]

Processing tickers:  98%|█████████▊| 6716/6855 [24:02<00:29,  4.65it/s]

Processing tickers:  98%|█████████▊| 6717/6855 [24:02<00:29,  4.69it/s]

Processing tickers:  98%|█████████▊| 6718/6855 [24:02<00:29,  4.72it/s]

Processing tickers:  98%|█████████▊| 6719/6855 [24:03<00:28,  4.76it/s]

Processing tickers:  98%|█████████▊| 6720/6855 [24:03<00:28,  4.80it/s]

Processing tickers:  98%|█████████▊| 6721/6855 [24:03<00:28,  4.68it/s]

Processing tickers:  98%|█████████▊| 6722/6855 [24:03<00:28,  4.65it/s]

Processing tickers:  98%|█████████▊| 6723/6855 [24:03<00:28,  4.66it/s]

Processing tickers:  98%|█████████▊| 6724/6855 [24:04<00:27,  4.72it/s]

Processing tickers:  98%|█████████▊| 6725/6855 [24:04<00:28,  4.61it/s]

Processing tickers:  98%|█████████▊| 6726/6855 [24:04<00:27,  4.65it/s]

Processing tickers:  98%|█████████▊| 6727/6855 [24:04<00:27,  4.58it/s]

Processing tickers:  98%|█████████▊| 6728/6855 [24:04<00:27,  4.63it/s]

Processing tickers:  98%|█████████▊| 6729/6855 [24:05<00:26,  4.68it/s]

Processing tickers:  98%|█████████▊| 6730/6855 [24:05<00:26,  4.68it/s]

Processing tickers:  98%|█████████▊| 6731/6855 [24:05<00:26,  4.67it/s]

Processing tickers:  98%|█████████▊| 6732/6855 [24:05<00:26,  4.70it/s]

Processing tickers:  98%|█████████▊| 6733/6855 [24:06<00:25,  4.71it/s]

Processing tickers:  98%|█████████▊| 6734/6855 [24:06<00:25,  4.70it/s]

Processing tickers:  98%|█████████▊| 6735/6855 [24:06<00:25,  4.63it/s]

Processing tickers:  98%|█████████▊| 6736/6855 [24:06<00:25,  4.66it/s]

Processing tickers:  98%|█████████▊| 6737/6855 [24:06<00:25,  4.69it/s]

Processing tickers:  98%|█████████▊| 6738/6855 [24:07<00:24,  4.76it/s]

Processing tickers:  98%|█████████▊| 6739/6855 [24:07<00:25,  4.61it/s]

Processing tickers:  98%|█████████▊| 6740/6855 [24:07<00:24,  4.63it/s]

Processing tickers:  98%|█████████▊| 6741/6855 [24:07<00:25,  4.53it/s]

Processing tickers:  98%|█████████▊| 6742/6855 [24:08<00:24,  4.57it/s]

Processing tickers:  98%|█████████▊| 6743/6855 [24:08<00:24,  4.56it/s]

Processing tickers:  98%|█████████▊| 6744/6855 [24:08<00:23,  4.64it/s]

Processing tickers:  98%|█████████▊| 6745/6855 [24:08<00:23,  4.67it/s]

Processing tickers:  98%|█████████▊| 6746/6855 [24:08<00:23,  4.68it/s]

Processing tickers:  98%|█████████▊| 6747/6855 [24:09<00:22,  4.71it/s]

Processing tickers:  98%|█████████▊| 6748/6855 [24:09<00:22,  4.77it/s]

Processing tickers:  98%|█████████▊| 6749/6855 [24:09<00:22,  4.75it/s]

Processing tickers:  98%|█████████▊| 6750/6855 [24:09<00:22,  4.70it/s]

Processing tickers:  98%|█████████▊| 6751/6855 [24:09<00:21,  4.76it/s]

Processing tickers:  98%|█████████▊| 6752/6855 [24:10<00:21,  4.76it/s]

Processing tickers:  99%|█████████▊| 6753/6855 [24:10<00:21,  4.69it/s]

Processing tickers:  99%|█████████▊| 6754/6855 [24:10<00:21,  4.66it/s]

Processing tickers:  99%|█████████▊| 6755/6855 [24:10<00:21,  4.67it/s]

Processing tickers:  99%|█████████▊| 6756/6855 [24:10<00:21,  4.63it/s]

Processing tickers:  99%|█████████▊| 6757/6855 [24:11<00:21,  4.50it/s]

Processing tickers:  99%|█████████▊| 6758/6855 [24:11<00:21,  4.51it/s]

Processing tickers:  99%|█████████▊| 6759/6855 [24:11<00:20,  4.60it/s]

Processing tickers:  99%|█████████▊| 6760/6855 [24:11<00:21,  4.48it/s]

Processing tickers:  99%|█████████▊| 6761/6855 [24:12<00:21,  4.45it/s]

Processing tickers:  99%|█████████▊| 6762/6855 [24:12<00:20,  4.51it/s]

Processing tickers:  99%|█████████▊| 6763/6855 [24:12<00:20,  4.53it/s]

Processing tickers:  99%|█████████▊| 6764/6855 [24:12<00:19,  4.57it/s]

Processing tickers:  99%|█████████▊| 6765/6855 [24:12<00:19,  4.63it/s]

Processing tickers:  99%|█████████▊| 6766/6855 [24:13<00:19,  4.66it/s]

Processing tickers:  99%|█████████▊| 6767/6855 [24:13<00:18,  4.69it/s]

Processing tickers:  99%|█████████▊| 6768/6855 [24:13<00:18,  4.68it/s]

Processing tickers:  99%|█████████▊| 6769/6855 [24:13<00:18,  4.58it/s]

Processing tickers:  99%|█████████▉| 6770/6855 [24:14<00:18,  4.63it/s]

Processing tickers:  99%|█████████▉| 6771/6855 [24:14<00:18,  4.56it/s]

Processing tickers:  99%|█████████▉| 6772/6855 [24:14<00:18,  4.45it/s]

Processing tickers:  99%|█████████▉| 6773/6855 [24:14<00:18,  4.55it/s]

Processing tickers:  99%|█████████▉| 6774/6855 [24:14<00:17,  4.61it/s]

Processing tickers:  99%|█████████▉| 6775/6855 [24:15<00:17,  4.65it/s]

Processing tickers:  99%|█████████▉| 6776/6855 [24:15<00:17,  4.63it/s]

Processing tickers:  99%|█████████▉| 6777/6855 [24:15<00:16,  4.67it/s]

Processing tickers:  99%|█████████▉| 6778/6855 [24:15<00:16,  4.69it/s]

Processing tickers:  99%|█████████▉| 6779/6855 [24:15<00:16,  4.72it/s]

Processing tickers:  99%|█████████▉| 6780/6855 [24:16<00:15,  4.71it/s]

Processing tickers:  99%|█████████▉| 6781/6855 [24:16<00:15,  4.71it/s]

Processing tickers:  99%|█████████▉| 6782/6855 [24:16<00:15,  4.74it/s]

Processing tickers:  99%|█████████▉| 6783/6855 [24:16<00:15,  4.70it/s]

Processing tickers:  99%|█████████▉| 6784/6855 [24:17<00:15,  4.73it/s]

Processing tickers:  99%|█████████▉| 6785/6855 [24:17<00:14,  4.73it/s]

Processing tickers:  99%|█████████▉| 6786/6855 [24:17<00:14,  4.75it/s]

Processing tickers:  99%|█████████▉| 6787/6855 [24:17<00:14,  4.61it/s]

Processing tickers:  99%|█████████▉| 6788/6855 [24:17<00:14,  4.69it/s]

Processing tickers:  99%|█████████▉| 6789/6855 [24:18<00:13,  4.72it/s]

Processing tickers:  99%|█████████▉| 6790/6855 [24:18<00:13,  4.75it/s]

Processing tickers:  99%|█████████▉| 6791/6855 [24:18<00:13,  4.80it/s]

Processing tickers:  99%|█████████▉| 6792/6855 [24:18<00:13,  4.70it/s]

Processing tickers:  99%|█████████▉| 6793/6855 [24:18<00:13,  4.72it/s]

Processing tickers:  99%|█████████▉| 6794/6855 [24:19<00:13,  4.66it/s]

Processing tickers:  99%|█████████▉| 6795/6855 [24:19<00:13,  4.56it/s]

Processing tickers:  99%|█████████▉| 6796/6855 [24:19<00:12,  4.63it/s]

Processing tickers:  99%|█████████▉| 6797/6855 [24:19<00:12,  4.65it/s]

Processing tickers:  99%|█████████▉| 6798/6855 [24:20<00:12,  4.71it/s]

Processing tickers:  99%|█████████▉| 6799/6855 [24:20<00:11,  4.73it/s]

Processing tickers:  99%|█████████▉| 6800/6855 [24:20<00:11,  4.74it/s]

Processing tickers:  99%|█████████▉| 6801/6855 [24:20<00:11,  4.58it/s]

Processing tickers:  99%|█████████▉| 6802/6855 [24:20<00:11,  4.57it/s]

Processing tickers:  99%|█████████▉| 6803/6855 [24:21<00:11,  4.65it/s]

Processing tickers:  99%|█████████▉| 6804/6855 [24:21<00:11,  4.58it/s]

Processing tickers:  99%|█████████▉| 6805/6855 [24:21<00:10,  4.67it/s]

Processing tickers:  99%|█████████▉| 6806/6855 [24:21<00:10,  4.73it/s]

Processing tickers:  99%|█████████▉| 6807/6855 [24:21<00:10,  4.71it/s]

Processing tickers:  99%|█████████▉| 6808/6855 [24:22<00:09,  4.70it/s]

Processing tickers:  99%|█████████▉| 6809/6855 [24:22<00:10,  4.59it/s]

Processing tickers:  99%|█████████▉| 6810/6855 [24:22<00:09,  4.66it/s]

Processing tickers:  99%|█████████▉| 6811/6855 [24:22<00:09,  4.54it/s]

Processing tickers:  99%|█████████▉| 6812/6855 [24:23<00:09,  4.55it/s]

Processing tickers:  99%|█████████▉| 6813/6855 [24:23<00:09,  4.62it/s]

Processing tickers:  99%|█████████▉| 6814/6855 [24:23<00:08,  4.68it/s]

Processing tickers:  99%|█████████▉| 6815/6855 [24:23<00:08,  4.54it/s]

Processing tickers:  99%|█████████▉| 6816/6855 [24:23<00:08,  4.64it/s]

Processing tickers:  99%|█████████▉| 6817/6855 [24:24<00:08,  4.72it/s]

Processing tickers:  99%|█████████▉| 6818/6855 [24:24<00:07,  4.77it/s]

Processing tickers:  99%|█████████▉| 6819/6855 [24:24<00:07,  4.78it/s]

Processing tickers:  99%|█████████▉| 6820/6855 [24:24<00:07,  4.73it/s]

Processing tickers: 100%|█████████▉| 6821/6855 [24:24<00:07,  4.73it/s]

Processing tickers: 100%|█████████▉| 6822/6855 [24:25<00:06,  4.74it/s]

Processing tickers: 100%|█████████▉| 6823/6855 [24:25<00:06,  4.77it/s]

Processing tickers: 100%|█████████▉| 6824/6855 [24:25<00:06,  4.71it/s]

Processing tickers: 100%|█████████▉| 6825/6855 [24:25<00:06,  4.60it/s]

Processing tickers: 100%|█████████▉| 6826/6855 [24:26<00:06,  4.68it/s]

Processing tickers: 100%|█████████▉| 6827/6855 [24:26<00:05,  4.75it/s]

Processing tickers: 100%|█████████▉| 6828/6855 [24:26<00:05,  4.77it/s]

Processing tickers: 100%|█████████▉| 6829/6855 [24:26<00:05,  4.79it/s]

Processing tickers: 100%|█████████▉| 6830/6855 [24:26<00:05,  4.71it/s]

Processing tickers: 100%|█████████▉| 6831/6855 [24:27<00:05,  4.74it/s]

Processing tickers: 100%|█████████▉| 6832/6855 [24:27<00:04,  4.78it/s]

Processing tickers: 100%|█████████▉| 6833/6855 [24:27<00:04,  4.77it/s]

Processing tickers: 100%|█████████▉| 6834/6855 [24:27<00:04,  4.79it/s]

Processing tickers: 100%|█████████▉| 6835/6855 [24:27<00:04,  4.80it/s]

Processing tickers: 100%|█████████▉| 6836/6855 [24:28<00:04,  4.71it/s]

Processing tickers: 100%|█████████▉| 6837/6855 [24:28<00:03,  4.64it/s]

Processing tickers: 100%|█████████▉| 6838/6855 [24:28<00:03,  4.67it/s]

Processing tickers: 100%|█████████▉| 6839/6855 [24:28<00:03,  4.73it/s]

Processing tickers: 100%|█████████▉| 6840/6855 [24:28<00:03,  4.70it/s]

Processing tickers: 100%|█████████▉| 6841/6855 [24:29<00:02,  4.75it/s]

Processing tickers: 100%|█████████▉| 6842/6855 [24:29<00:02,  4.79it/s]

Processing tickers: 100%|█████████▉| 6843/6855 [24:29<00:02,  4.80it/s]

Processing tickers: 100%|█████████▉| 6844/6855 [24:29<00:02,  4.82it/s]

Processing tickers: 100%|█████████▉| 6845/6855 [24:30<00:02,  4.84it/s]

Processing tickers: 100%|█████████▉| 6846/6855 [24:30<00:01,  4.82it/s]

Processing tickers: 100%|█████████▉| 6847/6855 [24:30<00:01,  4.79it/s]

Processing tickers: 100%|█████████▉| 6848/6855 [24:30<00:01,  4.83it/s]

Processing tickers: 100%|█████████▉| 6849/6855 [24:30<00:01,  4.71it/s]

Processing tickers: 100%|█████████▉| 6850/6855 [24:31<00:01,  4.60it/s]

Processing tickers: 100%|█████████▉| 6851/6855 [24:31<00:00,  4.65it/s]

Processing tickers: 100%|█████████▉| 6852/6855 [24:31<00:00,  4.69it/s]

Processing tickers: 100%|█████████▉| 6853/6855 [24:31<00:00,  4.73it/s]

Processing tickers: 100%|█████████▉| 6854/6855 [24:31<00:00,  4.61it/s]

Processing tickers: 100%|██████████| 6855/6855 [24:32<00:00,  4.66it/s]

Processing tickers: 100%|██████████| 6855/6855 [24:32<00:00,  4.66it/s]

         date ticker   gap
0  2025-12-16      A -0.09
1  2025-12-17      A -0.37
2  2025-12-18      A  0.31
3  2025-12-19      A  0.23
4  2025-12-22      A  0.28
Загалом рядків: 408885

In [45]:
std_by_ticker = (
    df_gaps_all.groupby("ticker")["gap"]
    .std()                 # std по групі (ddof=1)
    .round(2)              # округлення до 2 знаків
    .reset_index(name="sigma")
)

In [46]:
std_by_ticker

     ticker  sigma
0         A   0.77
1        AA   2.15
2      AAAU   1.78
3      AACG   3.65
4       AAL   1.60
...     ...    ...
6850    ZWS   0.97
6851   ZYBT   3.95
6852   ZYME   1.21
6853   ZYXI  19.79
6854  ZYXIQ  14.25

[6855 rows x 2 columns]

In [47]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [48]:
# std_by_ticker має колонки: ['ticker','sigma']
add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,  # <- твій DF зі скріна
    # або sigma_path="CRACEN/std_by_ticker.parquet"/".csv"
    insert_before=None,      # або "Bench%" / "pct_vs_prev_close" — куди вставити
)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=10.7s

[batch   10] rows=20,000,000  elapsed=21.3s

[batch   15] rows=30,000,000  elapsed=31.9s

[batch   20] rows=40,000,000  elapsed=42.5s

[batch   25] rows=50,000,000  elapsed=53.2s

[batch   30] rows=60,000,000  elapsed=63.8s

[batch   35] rows=70,000,000  elapsed=74.6s

[batch   40] rows=80,000,000  elapsed=85.2s

[batch   45] rows=90,000,000  elapsed=95.8s

[batch   50] rows=100,000,000  elapsed=106.5s

[batch   55] rows=110,000,000  elapsed=117.2s

✅ DONE rows=110,601,333 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 117.9s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct_with_sigma.parquet'

In [49]:
peek_parquet("CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet", n=21150)

Файл: CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 110,601,333
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 0/21150
NaN у 'beta' (у прев'ю): 0/21150

Перші рядки:

      ticker                  dt           o           h           l           c          v        date    open  prev_close  Stack% bench  corr  beta  Bench%  sigma
0          A 2025-12-16 03:54:00  139.380005  139.380005  139.380005  139.380005        3.0  2025-12-16  140.48      140.59   -0.86   IWM  0.81   0.6   -0.61   0.77
1          A 2025-12-16 08:31:00  140.990005  140.990005  140.990005  140.990005      100.0  2025-12-16  140.48      140.59    0.28   IWM  0.81   0.6    0.05   0.77
2          A 2025-12-16 09:30:00  140.479996  140.479996  139.919998  139.919998    16047.0  2025-12-16  140.48      140.59   -0.08   IWM  0.81   0.6   -0.64   0.77
3          A 2025-12-16 09:31:00  140.455002  140.455002  139.550003  140.195007     2854.0  2025-12-16  140.48      140.59   -0.10   IWM  0.81   0.6   -0.39   0.77
4          A 2025-12-16 09:32:00  140.195007  140.380005  140.149994  140.380005      800.0  2025-12-16  140.48      140.59   -0.28   IWM  0.81   0.6   -0.17   0.77
5          A 2025-12-16 09:33:00  140.380005  140.506897  140.195007  140.195007      600.0  2025-12-16  140.48      140.59   -0.15   IWM  0.81   0.6   -0.28   0.77
6          A 2025-12-16 09:34:00  140.059998  140.195007  139.869995  139.869995      700.0  2025-12-16  140.48      140.59   -0.38   IWM  0.81   0.6   -0.16   0.77
7          A 2025-12-16 09:35:00  139.869995  140.377502  139.869995  140.324997      900.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6   -0.25   0.77
8          A 2025-12-16 09:36:00  140.324997  140.324997  140.324997  140.324997      300.0  2025-12-16  140.48      140.59   -0.19   IWM  0.81   0.6   -0.13   0.77
9          A 2025-12-16 09:37:00  139.869995  140.160004  139.869995  140.154999     1000.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6   -0.15   0.77
10         A 2025-12-16 09:38:00  140.154999  140.154999  139.990005  140.154999     1234.0  2025-12-16  140.48      140.59   -0.31   IWM  0.81   0.6   -0.13   0.77
11         A 2025-12-16 09:39:00  140.164993  140.164993  139.985001  139.990005     1468.0  2025-12-16  140.48      140.59   -0.30   IWM  0.81   0.6   -0.20   0.77
12         A 2025-12-16 09:40:00  139.869995  140.235001  139.854996  139.967499     4552.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6   -0.23   0.77
13         A 2025-12-16 09:41:00  139.960007  140.089996  139.850006  139.850006     2866.0  2025-12-16  140.48      140.59   -0.45   IWM  0.81   0.6   -0.35   0.77
14         A 2025-12-16 09:42:00  139.919998  140.080002  139.919998  139.994995     2112.0  2025-12-16  140.48      140.59   -0.48   IWM  0.81   0.6   -0.45   0.77
15         A 2025-12-16 09:43:00  139.994995  140.070007  139.940002  139.949997     1995.0  2025-12-16  140.48      140.59   -0.42   IWM  0.81   0.6   -0.35   0.77
16         A 2025-12-16 09:44:00  139.919998  139.960007  139.785004  139.785004     1756.0  2025-12-16  140.48      140.59   -0.48   IWM  0.81   0.6   -0.47   0.77
17         A 2025-12-16 09:45:00  139.794998  139.794998  139.690002  139.690002     3390.0  2025-12-16  140.48      140.59   -0.57   IWM  0.81   0.6   -0.42   0.77
18         A 2025-12-16 09:46:00  139.585007  139.714996  139.414993  139.414993     1800.0  2025-12-16  140.48      140.59   -0.71   IWM  0.81   0.6   -0.60   0.77
19         A 2025-12-16 09:47:00  139.529999  139.595001  139.529999  139.589996     3875.0  2025-12-16  140.48      140.59   -0.75   IWM  0.81   0.6   -0.43   0.77
20         A 2025-12-16 09:48:00  139.585007  139.770004  139.429993  139.684998     3806.0  2025-12-16  140.48      140.59   -0.71   IWM  0.81   0.6   -0.12   0.77
21         A 2025-12-16 09:49:00  139.679993  139.679993  139.570007  139.570007     1165.0  2025-12-16  140.48      140.59   -0.65   IWM  0.81   0.6   -0.19   0.77
22         A 2025-12-16 09:50:00  139.570007  140.014999  139.570007  140.014999     3620.0  2025-12-16  140.48      140.59   -0.73   IWM  0.81   0.6   -0.28   0.77
23         A 2025-12-16 09:51:00  140.074997  140.074997  139.854996  139.860001     1220.0  2025-12-16  140.48      140.59   -0.37   IWM  0.81   0.6    0.02   0.77
24         A 2025-12-16 09:52:00  139.744995  139.744995  139.729996  139.729996     1841.0  2025-12-16  140.48      140.59   -0.60   IWM  0.81   0.6   -0.06   0.77
25         A 2025-12-16 09:53:00  139.725006  139.762497  139.600006  139.690002      616.0  2025-12-16  140.48      140.59   -0.62   IWM  0.81   0.6   -0.16   0.77
26         A 2025-12-16 09:54:00  139.550003  139.740005  139.500000  139.625000     2203.0  2025-12-16  140.48      140.59   -0.74   IWM  0.81   0.6   -0.24   0.77
27         A 2025-12-16 09:55:00  139.729996  139.899994  139.669998  139.889999     2400.0  2025-12-16  140.48      140.59   -0.61   IWM  0.81   0.6   -0.23   0.77
28         A 2025-12-16 09:56:00  139.809998  139.979996  139.792496  139.904999     7703.0  2025-12-16  140.48      140.59   -0.55   IWM  0.81   0.6   -0.10   0.77
29         A 2025-12-16 09:57:00  139.850006  139.850006  139.679993  139.684998     1339.0  2025-12-16  140.48      140.59   -0.53   IWM  0.81   0.6   -0.17   0.77
30         A 2025-12-16 09:58:00  139.669998  139.669998  139.580002  139.580002     7692.0  2025-12-16  140.48      140.59   -0.65   IWM  0.81   0.6   -0.19   0.77
31         A 2025-12-16 09:59:00  139.600006  139.679993  139.595001  139.679993      929.0  2025-12-16  140.48      140.59   -0.70   IWM  0.81   0.6   -0.22   0.77
32         A 2025-12-16 10:00:00  139.690002  139.869995  139.679993  139.869995     3018.0  2025-12-16  140.48      140.59   -0.64   IWM  0.81   0.6   -0.27   0.77
33         A 2025-12-16 10:01:00  139.714996  139.860001  139.699997  139.860001     1121.0  2025-12-16  140.48      140.59   -0.62   IWM  0.81   0.6   -0.26   0.77
34         A 2025-12-16 10:02:00  139.710007  140.049896  139.710007  139.884995     1607.0  2025-12-16  140.48      140.59   -0.63   IWM  0.81   0.6   -0.24   0.77
35         A 2025-12-16 10:03:00  139.720001  139.880005  139.720001  139.770096     2779.0  2025-12-16  140.48      140.59   -0.62   IWM  0.81   0.6   -0.39   0.77
36         A 2025-12-16 10:04:00  139.839996  139.839996  139.839996  139.839996      400.0  2025-12-16  140.48      140.59   -0.53   IWM  0.81   0.6   -0.46   0.77
37         A 2025-12-16 10:05:00  139.735001  139.884995  139.735001  139.884995     7871.0  2025-12-16  140.48      140.59   -0.61   IWM  0.81   0.6   -0.34   0.77
38         A 2025-12-16 10:06:00  139.759995  139.860001  139.740005  139.860001     1902.0  2025-12-16  140.48      140.59   -0.59   IWM  0.81   0.6   -0.32   0.77
39         A 2025-12-16 10:07:00  139.884995  139.889999  139.884995  139.889999      500.0  2025-12-16  140.48      140.59   -0.50   IWM  0.81   0.6   -0.26   0.77
40         A 2025-12-16 10:08:00  139.880005  139.880005  139.740097  139.740097      200.0  2025-12-16  140.48      140.59   -0.51   IWM  0.81   0.6   -0.13   0.77
41         A 2025-12-16 10:09:00  139.904999  139.910004  139.904999  139.910004      700.0  2025-12-16  140.48      140.59   -0.49   IWM  0.81   0.6   -0.14   0.77
42         A 2025-12-16 10:10:00  139.770004  139.904999  139.550003  139.580002     1800.0  2025-12-16  140.48      140.59   -0.58   IWM  0.81   0.6   -0.28   0.77
43         A 2025-12-16 10:11:00  139.460007  139.551498  139.369995  139.369995     1599.0  2025-12-16  140.48      140.59   -0.80   IWM  0.81   0.6   -0.39   0.77
44         A 2025-12-16 10:12:00  139.440002  139.529999  139.315002  139.315002      905.0  2025-12-16  140.48      140.59   -0.82   IWM  0.81   0.6   -0.33   0.77
45         A 2025-12-16 10:13:00  139.369995  139.369995  139.300003  139.304993     1200.0  2025-12-16  140.48      140.59   -0.87   IWM  0.81   0.6   -0.39   0.77
46         A 2025-12-16 10:14:00  139.369995  139.479996  139.317993  139.460007     1590.0  2025-12-16  140.48      140.59   -0.87   IWM  0.81   0.6   -0.47   0.77
47         A 2025-12-16 10:15:00  139.469193  139.469193  139.250000  139.250000     2734.0  2025-12-16  140.48      140.59   -0.80   IWM  0.81   0.6   -0.46   0.77
48         A 2025-12-16 10:16:00  139.190002  139.300003  139.190002  139.300003     1300.0  2025-12-16  140.48      140.59   -1.00   IWM  0.81   0.6   -0.52   0.77
49         A 2025-12-16 10:17:00  139.179993  139.220001  139.154999  139.160004     1500.0  2025-12-16  140.48      140.59   -1.00   IWM  0.81   0.6   -0.53   0.77
50         A 2025-12-16 10:18:00  139.154999  139.229996  139.070007  139.139999     2221.0  2025-12-16  140.48      140.59   -1.02   IWM  0.81   0.6   -0.65   0.77
51         A 2025-12-16 10:19:00  139.138107  139.138107  139.138107  139.138107      100.0  2025-12-16  140.48      140.59   -1.03   IWM  0.81   0.6   -0.62   0.77
52         A 2025-12-16 10:20:00  139.070099  139.145004  139.070007  139.145004      900.0  2025-12-16  140.48      140.59   -1.08   IWM  0.81   0.6   -0.58   0.77
53         A 2025-12-16 10:21:00  139.149994  139.149994  138.899994  138.919998     2267.0  2025-12-16  140.48      140.59   -1.02   IWM  0.81   0.6   -0.62   0.77
54         A 2025-12-16 10:22:00  138.839996  138.945007  138.835007  138.859604      930.0  2025-12-16  140.48      140.59   -1.24   IWM  0.81   0.6   -0.71   0.77
55         A 2025-12-16 10:23:00  138.800003  139.050003  138.800003  139.050003     1200.0  2025-12-16  140.48      140.59   -1.27   IWM  0.81   0.6   -0.74   0.77
56         A 2025-12-16 10:24:00  138.839996  138.960007  138.839996  138.960007     9036.0  2025-12-16  140.48      140.59   -1.24   IWM  0.81   0.6   -0.75   0.77
57         A 2025-12-16 10:25:00  138.839996  138.839996  138.800003  138.800003      500.0  2025-12-16  140.48      140.59   -1.24   IWM  0.81   0.6   -0.78   0.77
58         A 2025-12-16 10:26:00  138.895004  138.945007  138.895004  138.945007      800.0  2025-12-16  140.48      140.59   -1.21   IWM  0.81   0.6   -0.79   0.77
59         A 2025-12-16 10:27:00  138.945007  139.020004  138.945007  138.945007      600.0  2025-12-16  140.48      140.59   -1.17   IWM  0.81   0.6   -0.87   0.77
60         A 2025-12-16 10:28:00  138.945007  139.119995  138.945007  139.110001     3083.0  2025-12-16  140.48      140.59   -1.17   IWM  0.81   0.6   -0.85   0.77
61         A 2025-12-16 10:29:00  139.110001  139.350006  139.110001  139.250000     2528.0  2025-12-16  140.48      140.59   -1.05   IWM  0.81   0.6   -0.73   0.77
62         A 2025-12-16 10:30:00  139.279999  139.300003  139.279999  139.279999     1322.0  2025-12-16  140.48      140.59   -0.93   IWM  0.81   0.6   -0.69   0.77
63         A 2025-12-16 10:31:00  139.250000  139.279999  139.250000  139.279999      400.0  2025-12-16  140.48      140.59   -0.95   IWM  0.81   0.6   -0.68   0.77
64         A 2025-12-16 10:32:00  139.449997  139.520004  139.397995  139.397995     1160.0  2025-12-16  140.48      140.59   -0.81   IWM  0.81   0.6   -0.58   0.77
65         A 2025-12-16 10:33:00  139.509995  139.570007  139.509995  139.520004     1284.0  2025-12-16  140.48      140.59   -0.77   IWM  0.81   0.6   -0.50   0.77
66         A 2025-12-16 10:34:00  139.520004  139.520004  139.520004  139.520004      100.0  2025-12-16  140.48      140.59   -0.76   IWM  0.81   0.6   -0.52   0.77
67         A 2025-12-16 10:35:00  139.410004  139.494995  139.350006  139.494995     1038.0  2025-12-16  140.48      140.59   -0.84   IWM  0.81   0.6   -0.54   0.77
68         A 2025-12-16 10:36:00  139.360001  139.360001  139.100006  139.100006     1117.0  2025-12-16  140.48      140.59   -0.87   IWM  0.81   0.6   -0.52   0.77
69         A 2025-12-16 10:37:00  139.080002  139.110001  139.009995  139.039993      800.0  2025-12-16  140.48      140.59   -1.07   IWM  0.81   0.6   -0.60   0.77
70         A 2025-12-16 10:38:00  138.990005  139.005005  138.979996  138.999802     1427.0  2025-12-16  140.48      140.59   -1.14   IWM  0.81   0.6   -0.67   0.77
71         A 2025-12-16 10:39:00  138.997498  139.009995  138.997498  139.009995      850.0  2025-12-16  140.48      140.59   -1.13   IWM  0.81   0.6   -0.68   0.77
72         A 2025-12-16 10:40:00  139.089996  139.089996  138.889999  138.899994     2530.0  2025-12-16  140.48      140.59   -1.07   IWM  0.81   0.6   -0.55   0.77
73         A 2025-12-16 10:41:00  138.975006  138.975006  138.975006  138.975006      100.0  2025-12-16  140.48      140.59   -1.15   IWM  0.81   0.6   -0.66   0.77
74         A 2025-12-16 10:42:00  138.948196  138.994995  138.869995  138.960007     1665.0  2025-12-16  140.48      140.59   -1.17   IWM  0.81   0.6   -0.70   0.77
75         A 2025-12-16 10:43:00  138.970001  138.970001  138.970001  138.970001      100.0  2025-12-16  140.48      140.59   -1.15   IWM  0.81   0.6   -0.68   0.77
76         A 2025-12-16 10:44:00  138.889999  138.890106  138.889999  138.890106      831.0  2025-12-16  140.48      140.59   -1.21   IWM  0.81   0.6   -0.66   0.77
77         A 2025-12-16 10:45:00  138.985001  139.050003  138.789993  138.789993     2869.0  2025-12-16  140.48      140.59   -1.14   IWM  0.81   0.6   -0.56   0.77
78         A 2025-12-16 10:46:00  138.860001  138.865005  138.796005  138.796005     1741.0  2025-12-16  140.48      140.59   -1.23   IWM  0.81   0.6   -0.49   0.77
79         A 2025-12-16 10:47:00  138.779999  138.835007  138.750000  138.759995      900.0  2025-12-16  140.48      140.59   -1.29   IWM  0.81   0.6   -0.44   0.77
80         A 2025-12-16 10:48:00  138.710007  138.800003  138.710007  138.800003      900.0  2025-12-16  140.48      140.59   -1.34   IWM  0.81   0.6   -0.49   0.77
81         A 2025-12-16 10:49:00  138.725006  138.800003  138.720001  138.720001     1042.0  2025-12-16  140.48      140.59   -1.33   IWM  0.81   0.6   -0.53   0.77
82         A 2025-12-16 10:50:00  138.720001  138.720001  138.589996  138.589996     1341.0  2025-12-16  140.48      140.59   -1.33   IWM  0.81   0.6   -0.52   0.77
83         A 2025-12-16 10:51:00  138.645004  138.649994  138.529999  138.649994      807.0  2025-12-16  140.48      140.59   -1.38   IWM  0.81   0.6   -0.65   0.77
84         A 2025-12-16 10:52:00  138.649994  138.660004  138.630005  138.630005      600.0  2025-12-16  140.48      140.59   -1.38   IWM  0.81   0.6   -0.63   0.77
85         A 2025-12-16 10:53:00  138.654999  138.725006  138.654999  138.654999      700.0  2025-12-16  140.48      140.59   -1.38   IWM  0.81   0.6   -0.55   0.77
86         A 2025-12-16 10:54:00  138.729996  138.789993  138.664993  138.729996      750.0  2025-12-16  140.48      140.59   -1.32   IWM  0.81   0.6   -0.50   0.77
87         A 2025-12-16 10:55:00  138.669998  138.669998  138.669998  138.669998      400.0  2025-12-16  140.48      140.59   -1.37   IWM  0.81   0.6   -0.52   0.77
88         A 2025-12-16 10:56:00  138.699997  138.699997  138.660004  138.699997     1100.0  2025-12-16  140.48      140.59   -1.34   IWM  0.81   0.6   -0.48   0.77
89         A 2025-12-16 10:57:00  138.589996  138.589996  138.300003  138.300003     2394.0  2025-12-16  140.48      140.59   -1.42   IWM  0.81   0.6   -0.52   0.77
90         A 2025-12-16 10:58:00  138.259995  138.389999  138.259995  138.324997     1000.0  2025-12-16  140.48      140.59   -1.66   IWM  0.81   0.6   -0.59   0.77
91         A 2025-12-16 10:59:00  138.384995  138.384995  138.244995  138.264999     1365.0  2025-12-16  140.48      140.59   -1.57   IWM  0.81   0.6   -0.53   0.77
92         A 2025-12-16 11:00:00  138.229996  138.369995  138.229996  138.300003     1010.0  2025-12-16  140.48      140.59   -1.68   IWM  0.81   0.6   -0.48   0.77
93         A 2025-12-16 11:01:00  138.440002  138.440002  138.250000  138.250000     1073.0  2025-12-16  140.48      140.59   -1.53   IWM  0.81   0.6   -0.56   0.77
94         A 2025-12-16 11:02:00  138.335007  138.479996  138.335007  138.470001     2580.0  2025-12-16  140.48      140.59   -1.60   IWM  0.81   0.6   -0.58   0.77
95         A 2025-12-16 11:03:00  138.529999  138.695099  138.529999  138.690002      876.0  2025-12-16  140.48      140.59   -1.47   IWM  0.81   0.6   -0.61   0.77
96         A 2025-12-16 11:04:00  138.679993  138.679993  138.679993  138.679993      100.0  2025-12-16  140.48      140.59   -1.36   IWM  0.81   0.6   -0.64   0.77
97         A 2025-12-16 11:05:00  138.690002  138.690002  138.528702  138.528702      893.0  2025-12-16  140.48      140.59   -1.35   IWM  0.81   0.6   -0.68   0.77
98         A 2025-12-16 11:06:00  138.619995  138.690002  138.610001  138.690002      400.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6   -0.65   0.77
99         A 2025-12-16 11:07:00  138.550003  138.565002  138.529999  138.529999      398.0  2025-12-16  140.48      140.59   -1.45   IWM  0.81   0.6   -0.63   0.77
100        A 2025-12-16 11:08:00  138.460007  138.600006  138.460007  138.600006     1596.0  2025-12-16  140.48      140.59   -1.52   IWM  0.81   0.6   -0.74   0.77
101        A 2025-12-16 11:10:00  138.714996  139.059998  138.714996  139.059998     2761.0  2025-12-16  140.48      140.59   -1.33   IWM  0.81   0.6   -0.77   0.77
102        A 2025-12-16 11:11:00  138.804993  138.910004  138.804993  138.910004      400.0  2025-12-16  140.48      140.59   -1.27   IWM  0.81   0.6   -0.77   0.77
103        A 2025-12-16 11:12:00  138.800003  138.809998  138.600006  138.600006     1893.0  2025-12-16  140.48      140.59   -1.27   IWM  0.81   0.6   -0.82   0.77
104        A 2025-12-16 11:13:00  138.604996  138.604996  138.580002  138.580002      400.0  2025-12-16  140.48      140.59   -1.41   IWM  0.81   0.6   -0.87   0.77
105        A 2025-12-16 11:14:00  138.759995  138.759995  138.744995  138.750000      300.0  2025-12-16  140.48      140.59   -1.30   IWM  0.81   0.6   -0.80   0.77
106        A 2025-12-16 11:15:00  138.669998  138.720001  138.649994  138.720001      413.0  2025-12-16  140.48      140.59   -1.37   IWM  0.81   0.6   -0.83   0.77
107        A 2025-12-16 11:16:00  138.695007  138.695007  138.520004  138.520004     1592.0  2025-12-16  140.48      140.59   -1.35   IWM  0.81   0.6   -0.87   0.77
108        A 2025-12-16 11:17:00  138.429993  138.494995  138.404999  138.494995      700.0  2025-12-16  140.48      140.59   -1.54   IWM  0.81   0.6   -0.91   0.77
109        A 2025-12-16 11:18:00  138.475006  138.589996  138.470001  138.589996     1500.0  2025-12-16  140.48      140.59   -1.50   IWM  0.81   0.6   -0.88   0.77
110        A 2025-12-16 11:19:00  138.610001  138.610001  138.610001  138.610001      100.0  2025-12-16  140.48      140.59   -1.41   IWM  0.81   0.6   -0.78   0.77
111        A 2025-12-16 11:20:00  138.614899  138.690002  138.490005  138.490005      400.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6   -0.81   0.77
112        A 2025-12-16 11:21:00  138.524994  138.600006  138.524994  138.580795      460.0  2025-12-16  140.48      140.59   -1.47   IWM  0.81   0.6   -0.80   0.77
113        A 2025-12-16 11:22:00  138.619995  138.630005  138.449997  138.449997     3493.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6   -0.79   0.77
114        A 2025-12-16 11:23:00  138.440002  138.440002  138.340103  138.429993      625.0  2025-12-16  140.48      140.59   -1.53   IWM  0.81   0.6   -0.81   0.77
115        A 2025-12-16 11:24:00  138.360001  138.360001  138.360001  138.360001      100.0  2025-12-16  140.48      140.59   -1.59   IWM  0.81   0.6   -0.84   0.77
116        A 2025-12-16 11:26:00  138.429993  138.460007  138.389999  138.389999      400.0  2025-12-16  140.48      140.59   -1.54   IWM  0.81   0.6   -0.85   0.77
117        A 2025-12-16 11:27:00  138.475006  138.475006  138.375000  138.375000     1048.0  2025-12-16  140.48      140.59   -1.50   IWM  0.81   0.6   -0.89   0.77
118        A 2025-12-16 11:28:00  138.509995  138.649994  138.410004  138.610001     3170.0  2025-12-16  140.48      140.59   -1.48   IWM  0.81   0.6   -0.87   0.77
119        A 2025-12-16 11:29:00  138.615005  138.669998  138.490005  138.570007     3331.0  2025-12-16  140.48      140.59   -1.40   IWM  0.81   0.6   -0.87   0.77

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2025-12-16 03:54:00,139.380005,139.380005,139.380005,139.380005,3.0,2025-12-16,140.48,140.59,-0.86,IWM,0.81,0.6,-0.61,0.77
1,A,2025-12-16 08:31:00,140.990005,140.990005,140.990005,140.990005,100.0,2025-12-16,140.48,140.59,0.28,IWM,0.81,0.6,0.05,0.77
2,A,2025-12-16 09:30:00,140.479996,140.479996,139.919998,139.919998,16047.0,2025-12-16,140.48,140.59,-0.08,IWM,0.81,0.6,-0.64,0.77
3,A,2025-12-16 09:31:00,140.455002,140.455002,139.550003,140.195007,2854.0,2025-12-16,140.48,140.59,-0.10,IWM,0.81,0.6,-0.39,0.77
4,A,2025-12-16 09:32:00,140.195007,140.380005,140.149994,140.380005,800.0,2025-12-16,140.48,140.59,-0.28,IWM,0.81,0.6,-0.17,0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AA,2026-01-14 13:01:00,64.789902,64.789902,64.699997,64.750000,7320.0,2026-01-14,65.72,65.38,-0.90,SPY,0.77,2.6,-1.00,2.15
21146,AA,2026-01-14 13:02:00,64.750000,64.800003,64.709999,64.800003,6017.0,2026-01-14,65.72,65.38,-0.96,SPY,0.77,2.6,-1.02,2.15
21147,AA,2026-01-14 13:03:00,64.809998,65.011299,64.809998,64.989998,5108.0,2026-01-14,65.72,65.38,-0.87,SPY,0.77,2.6,-0.98,2.15
21148,AA,2026-01-14 13:04:00,65.000397,65.089996,64.970001,65.089996,20902.0,2026-01-14,65.72,65.38,-0.58,SPY,0.77,2.6,-0.97,2.15
21149,AA,2026-01-14 13:05:00,65.084999,65.129997,65.059998,65.059998,10000.0,2026-01-14,65.72,65.38,-0.45,SPY,0.77,2.6,-0.96,2.15

In [50]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [51]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=6.3s

[batch   10] rows=20,000,000  elapsed=12.7s

[batch   15] rows=30,000,000  elapsed=19.0s

[batch   20] rows=40,000,000  elapsed=25.2s

[batch   25] rows=50,000,000  elapsed=31.5s

[batch   30] rows=60,000,000  elapsed=37.7s

[batch   35] rows=70,000,000  elapsed=44.0s

[batch   40] rows=80,000,000  elapsed=50.3s

[batch   45] rows=90,000,000  elapsed=56.6s

[batch   50] rows=100,000,000  elapsed=62.8s

[batch   55] rows=110,000,000  elapsed=69.1s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_19628_1773785406 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=7,040 | has_date=True has_dt=True

  [   200/7,040] AIRE  written=3,246,540  elapsed=31.5s

  [   400/7,040] APUS  written=6,579,242  elapsed=64.5s

  [   600/7,040] AXG  written=9,873,382  elapsed=101.9s

  [   800/7,040] BIRK  written=12,741,280  elapsed=137.3s

  [  1000/7,040] BTGD  written=15,967,410  elapsed=174.6s

  [  1200/7,040] CFLT  written=19,032,227  elapsed=211.3s

  [  1400/7,040] COIN  written=21,914,321  elapsed=249.7s

  [  1600/7,040] CWCO  written=25,317,560  elapsed=290.1s

  [  1800/7,040] DOLE  written=28,340,894  elapsed=330.8s

  [  2000/7,040] EME  written=31,228,286  elapsed=371.2s

  [  2200/7,040] EZGO  written=34,496,391  elapsed=411.9s

  [  2400/7,040] FNLC  written=37,443,007  elapsed=452.6s

  [  2600/7,040] GIBO  written=40,434,020  elapsed=492.8s

  [  2800/7,040] HAL  written=43,505,893  elapsed=534.0s

  [  3000/7,040] HYT/R  written=46,435,438  elapsed=574.0s

  [  3200/7,040] INTT  written=49,357,206  elapsed=614.1s

  [  3400/7,040] JHG  written=52,710,923  elapsed=652.6s

  [  3600/7,040] KZIA  written=55,585,471  elapsed=691.3s

  [  3800/7,040] LVROF  written=58,424,409  elapsed=726.6s

  [  4000/7,040] MLTX  written=61,328,333  elapsed=762.8s

  [  4200/7,040] NATO  written=64,593,408  elapsed=799.2s

  [  4400/7,040] NUKK  written=67,652,810  elapsed=835.9s

  [  4600/7,040] ORGN  written=71,214,760  elapsed=871.8s

  [  4800/7,040] PII  written=74,425,430  elapsed=908.1s

  [  5000/7,040] PYPG  written=77,472,122  elapsed=943.5s

  [  5200/7,040] RHLD  written=80,730,375  elapsed=976.3s

  [  5400/7,040] SCHE  written=84,180,637  elapsed=1,009.6s

  [  5600/7,040] SLON  written=87,442,280  elapsed=1,042.7s

  [  5800/7,040] SPYI  written=90,965,076  elapsed=1,076.1s

  [  6000/7,040] TDW  written=94,086,542  elapsed=1,108.5s

  [  6200/7,040] TSII  written=97,354,620  elapsed=1,141.4s

  [  6400/7,040] USBC  written=101,015,639  elapsed=1,175.1s

  [  6600/7,040] VSCO  written=104,397,510  elapsed=1,208.0s

  [  6800/7,040] WTS  written=107,347,770  elapsed=1,238.1s

  [  7000/7,040] ZEO  written=109,991,221  elapsed=1,264.6s

✅ SORT DONE: 110,601,333 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=1,269.7s

✅ DONE: 110,601,333 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=1,345.5s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'

In [52]:
import pyarrow.dataset as ds

path = str(FINAL_PATH)

ticker = "AAPL"

dataset = ds.dataset(path, format="parquet")

table = dataset.to_table(
    filter=(ds.field("ticker") == ticker)
)

df = table.to_pandas()

# якщо є date + dt — відсортуємо, щоб це були саме "перші" по часу
if {"date", "dt"}.issubset(df.columns):
    df = df.sort_values(["date", "dt"])

display(df)

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma,t_p,deviation,dev_sig
0,AAPL,2025-12-16 00:00:00,273.010010,273.040009,273.010010,273.040009,76.0,2025-12-16,272.7,274.12,-0.40,SPY,0.76,0.6,-0.38,0.58,-0.24,0.14,0.241379
1,AAPL,2025-12-16 00:01:00,273.040009,273.040009,273.040009,273.040009,1.0,2025-12-16,272.7,274.12,-0.39,SPY,0.76,0.6,-0.39,0.58,-0.23,0.16,0.268966
2,AAPL,2025-12-16 00:02:00,273.029999,273.029999,272.899994,272.899994,187.0,2025-12-16,272.7,274.12,-0.40,SPY,0.76,0.6,-0.40,0.58,-0.24,0.16,0.275862
3,AAPL,2025-12-16 00:03:00,272.910004,272.910004,272.910004,272.910004,115.0,2025-12-16,272.7,274.12,-0.44,SPY,0.76,0.6,-0.40,0.58,-0.26,0.14,0.234483
4,AAPL,2025-12-16 00:05:00,272.910004,272.910004,272.910004,272.910004,1.0,2025-12-16,272.7,274.12,-0.44,SPY,0.76,0.6,-0.40,0.58,-0.26,0.14,0.234483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69724,AAPL,2026-03-16 23:52:00,251.779999,251.779999,251.779999,251.779999,3.0,2026-03-16,252.1,250.12,0.66,SPY,0.76,0.6,0.73,0.58,0.40,-0.33,-0.575862
69725,AAPL,2026-03-16 23:55:00,251.779999,251.779999,251.779999,251.779999,1.0,2026-03-16,252.1,250.12,0.66,SPY,0.76,0.6,0.71,0.58,0.40,-0.31,-0.541379
69726,AAPL,2026-03-16 23:56:00,251.779999,251.880005,251.779999,251.880005,4.0,2026-03-16,252.1,250.12,0.66,SPY,0.76,0.6,0.70,0.58,0.40,-0.30,-0.524138
69727,AAPL,2026-03-16 23:58:00,251.820007,251.830002,251.820007,251.830002,4.0,2026-03-16,252.1,250.12,0.68,SPY,0.76,0.6,0.70,0.58,0.41,-0.29,-0.503448
69728,AAPL,2026-03-16 23:59:00,251.869995,251.869995,251.869995,251.869995,146.0,2026-03-16,252.1,250.12,0.70,SPY,0.76,0.6,NaN,0.58,0.42,NaN,NaN